open spiel: absl::exponential_distribution< RealType > Class Template Reference
absl::exponential_distribution< RealType > Class Template Reference
Classes
class param_type
Public Types
using result_type = RealType
Public Member Functions
exponential_distribution (result_type lambda)
exponential_distribution (const param_type &p)
void reset ()
template<typename URBG >
result_type operator() (URBG &g)
template<typename URBG >
result_type operator() (URBG &g, const param_type &p)
param_type param () const
void param (const param_type &p)
result_type min () const
result_type max () const
result_type lambda () const
Friends
bool operator== (const exponential_distribution &a, const exponential_distribution &b)
bool operator!= (const exponential_distribution &a, const exponential_distribution &b)
Detailed Description
template<typename RealType = double>
class absl::exponential_distribution< RealType >
Definition at line 36 of file exponential_distribution.h.
Member Typedef Documentation
result_type
template<typename RealType = double> using absl::exponential_distribution< RealType >::result_type = RealType
Definition at line 38 of file exponential_distribution.h.
Constructor & Destructor Documentation
exponential_distribution() [1/3]
template<typename RealType = double> absl::exponential_distribution< RealType >::exponential_distribution () inline
Definition at line 71 of file exponential_distribution.h.
: exponential_distribution(1) {}
exponential_distribution() [2/3]
template<typename RealType = double> absl::exponential_distribution< RealType >::exponential_distribution (result_type lambda) inline explicit
Definition at line 73 of file exponential_distribution.h.
: param_(lambda) {}
exponential_distribution() [3/3]
template<typename RealType = double> absl::exponential_distribution< RealType >::exponential_distribution (const param_type & p) inline explicit
Definition at line 75 of file exponential_distribution.h.
: param_(p) {}
Member Function Documentation
lambda()
template<typename RealType = double> result_type absl::exponential_distribution< RealType >::lambda () const inline
Definition at line 97 of file exponential_distribution.h.
{ return param_.lambda(); }
max()
template<typename RealType = double> result_type absl::exponential_distribution< RealType >::max () const inline
Definition at line 93 of file exponential_distribution.h.
{
    return std::numeric_limits<result_type>::infinity();
  }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
template<typename RealType = double> result_type absl::exponential_distribution< RealType >::min () const inline
Definition at line 92 of file exponential_distribution.h.
{ return 0; }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
operator()() [1/2]
template<typename RealType = double> template<typename URBG > result_type absl::exponential_distribution< RealType >::operator() (URBG & g) inline
Definition at line 81 of file exponential_distribution.h.
                                  {  // NOLINT(runtime/references)
    return (*this)(g, param_);
  }
operator()() [2/2]
template<typename RealType > template<typename URBG > exponential_distribution< RealType >::result_type absl::exponential_distribution< RealType >::operator() (URBG & g, const param_type & p)
Definition at line 120 of file exponential_distribution.h.
{
  using random_internal::GenerateNegativeTag;
  using random_internal::GenerateRealFromBits;
  using real_type =
      absl::conditional_t<std::is_same<RealType, float>::value, float, double>;
  const result_type u = GenerateRealFromBits<real_type, GenerateNegativeTag,
                                             false>(fast_u64_(g));  // U(-1, 0)
  // log1p(-x) is mathematically equivalent to log(1 - x) but has more
  // accuracy for x near zero.
  return p.neg_inv_lambda_ * std::log1p(u);
}
param() [1/2]
template<typename RealType = double> param_type absl::exponential_distribution< RealType >::param () const inline
Definition at line 89 of file exponential_distribution.h.
{ return param_; }
param() [2/2]
template<typename RealType = double> void absl::exponential_distribution< RealType >::param (const param_type & p) inline
Definition at line 90 of file exponential_distribution.h.
{ param_ = p; }
reset()
template<typename RealType = double> void absl::exponential_distribution< RealType >::reset () inline
Definition at line 77 of file exponential_distribution.h.
{}
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear::__init__(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), open_spiel.python.rl_environment.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
Friends And Related Symbol Documentation
operator!=
template<typename RealType = double> bool operator!= (const exponential_distribution< RealType > & a, const exponential_distribution< RealType > & b) friend
Definition at line 103 of file exponential_distribution.h.
{
    return a.param_ != b.param_;
  }
operator==
template<typename RealType = double> bool operator== (const exponential_distribution< RealType > & a, const exponential_distribution< RealType > & b) friend
Definition at line 99 of file exponential_distribution.h.
{
    return a.param_ == b.param_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/exponential_distribution.h