open spiel: open_spiel::algorithms::torch_az::ModelImpl Class Reference
open_spiel::algorithms::torch_az::ModelImpl Class Reference
Public Member Functions
ModelImpl (const ModelConfig &config, const std::string &device)
std::vector< torch::Tensor > forward (torch::Tensor x, torch::Tensor mask)
std::vector< torch::Tensor > losses (torch::Tensor inputs, torch::Tensor masks, torch::Tensor policy_targets, torch::Tensor value_targets)
Detailed Description
Definition at line 184 of file model.h.
Constructor & Destructor Documentation
ModelImpl()
open_spiel::algorithms::torch_az::ModelImpl::ModelImpl (const ModelConfig & config, const std::string & device)
Definition at line 260 of file model.cc.
    : device_(device),
      num_torso_blocks_(config.nn_depth),
      weight_decay_(config.weight_decay) {
  // Save config.nn_model to class
  nn_model_ = config.nn_model;
  int input_size = 1;
  for (const auto& num : config.observation_tensor_shape) {
    if (num > 0) {
      input_size *= num;
    }
  }
  // Decide if resnet or MLP
  if (config.nn_model == "resnet") {
    int channels = config.observation_tensor_shape[0];
    int height = config.observation_tensor_shape[1];
    int width = config.observation_tensor_shape[2];
    ResInputBlockConfig input_config = {/*input_channels=*/channels,
                                        /*input_height=*/height,
                                        /*input_width=*/width,
                                        /*filters=*/config.nn_width,
                                        /*kernel_size=*/3,
                                        /*padding=*/1};
    ResTorsoBlockConfig residual_config = {/*input_channels=*/config.nn_width,
                                           /*filters=*/config.nn_width,
                                           /*kernel_size=*/3,
                                           /*padding=*/1};
    ResOutputBlockConfig output_config = {
        /*input_channels=*/config.nn_width,
        /*value_filters=*/1,
        /*policy_filters=*/2,
        /*kernel_size=*/1,
        /*padding=*/0,
        /*value_linear_in_features=*/1 * width * height,
        /*value_linear_out_features=*/config.nn_width,
        /*policy_linear_in_features=*/2 * width * height,
        /*policy_linear_out_features=*/config.number_of_actions,
        /*value_observation_size=*/1 * width * height,
        /*policy_observation_size=*/2 * width * height};
    layers_->push_back(ResInputBlock(input_config));
    for (int i = 0; i < num_torso_blocks_; i++) {
      layers_->push_back(ResTorsoBlock(residual_config, i));
    }
    layers_->push_back(ResOutputBlock(output_config));
    register_module("layers", layers_);
  } else if (config.nn_model == "mlp") {
    layers_->push_back(MLPBlock(input_size, config.nn_width));
    for (int i = 0; i < num_torso_blocks_; i++) {
      layers_->push_back(MLPBlock(config.nn_width, config.nn_width));
    }
    layers_->push_back(
        MLPOutputBlock(config.nn_width, config.number_of_actions));
    register_module("layers", layers_);
  } else {
    throw std::runtime_error("Unknown nn_model: " + config.nn_model);
  }
}
Member Function Documentation
forward()
std::vector< torch::Tensor > open_spiel::algorithms::torch_az::ModelImpl::forward (torch::Tensor x, torch::Tensor mask)
Definition at line 326 of file model.cc.
{
  std::vector<torch::Tensor> output = this->forward_(x, mask);
  return {output[0], torch::softmax(output[1], 1)};
}
losses()
std::vector< torch::Tensor > open_spiel::algorithms::torch_az::ModelImpl::losses (torch::Tensor inputs, torch::Tensor masks, torch::Tensor policy_targets, torch::Tensor value_targets)
Definition at line 332 of file model.cc.
{
  std::vector<torch::Tensor> output = this->forward_(inputs, masks);
  torch::Tensor value_predictions = output[0];
  torch::Tensor policy_predictions = output[1];
  // Policy loss (cross-entropy).
  torch::Tensor policy_loss = torch::sum(
      -policy_targets * torch::log_softmax(policy_predictions, 1), -1);
  policy_loss = torch::mean(policy_loss);
  // Value loss (mean-squared error).
  torch::nn::MSELoss mse_loss;
  torch::Tensor value_loss = mse_loss(value_predictions, value_targets);
  // L2 regularization loss (weights only).
  torch::Tensor l2_regularization_loss = torch::full(
      {1, 1}, 0, torch::TensorOptions().dtype(torch::kFloat32).device(device_));
  for (auto& named_parameter : this->named_parameters()) {
    // named_parameter is essentially a key-value pair:
    //   {key, value} == {std::string name, torch::Tensor parameter}
    std::string parameter_name = named_parameter.key();
    // Do not include bias' in the loss.
    if (parameter_name.find("bias") != std::string::npos) {
      continue;
    }
    // Copy TensorFlow's l2_loss function.
    // https://www.tensorflow.org/api_docs/python/tf/nn/l2_loss
    l2_regularization_loss +=
        weight_decay_ * torch::sum(torch::square(named_parameter.value())) / 2;
  }
  return {policy_loss, value_loss, l2_regularization_loss};
}
Referenced by open_spiel.python.algorithms.neurd.DeepNeurdModel::__init__(), open_spiel.python.algorithms.rcfr.DeepRcfrModel::__init__(), open_spiel.python.coalitional_games.least_core_lagrangian.CoreLagrangian::solve(), open_spiel.python.coalitional_games.least_core_lagrangian.CoreOptimization::solve(), and open_spiel.python.coalitional_games.least_core_lagrangian.CoreOptimizationLogits::solve().
The documentation for this class was generated from the following files:
open_spiel/algorithms/alpha_zero_torch/model.h
open_spiel/algorithms/alpha_zero_torch/model.cc