open spiel: open_spiel.python.rl_environment.TimeStep Class Reference
open_spiel.python.rl_environment.TimeStep Class Reference
Public Member Functions
first (self)
mid (self)
last (self)
is_simultaneous_move (self)
current_player (self)
Public Attributes
step_type
Detailed Description
Returned with every call to `step` and `reset`.
A `TimeStep` contains the data emitted by a game at each step of interaction.
A `TimeStep` holds an `observation` (list of dicts, one per player),
associated lists of `rewards`, `discounts` and a `step_type`.
The first `TimeStep` in a sequence will have `StepType.FIRST`. The final
`TimeStep` will have `StepType.LAST`. All other `TimeStep`s in a sequence will
have `StepType.MID.
Attributes:
  observations: a list of dicts containing observations per player.
  rewards: A list of scalars (one per player), or `None` if `step_type` is
    `StepType.FIRST`, i.e. at the start of a sequence.
  discounts: A list of discount values in the range `[0, 1]` (one per player),
    or `None` if `step_type` is `StepType.FIRST`.
  step_type: A `StepType` enum value.
Definition at line 58 of file rl_environment.py.
Member Function Documentation
current_player()
open_spiel.python.rl_environment.TimeStep.current_player (self)
Definition at line 93 of file rl_environment.py.
  def current_player(self):
    return self.observations["current_player"]
Referenced by open_spiel.python.games.liars_poker.LiarsPokerState.__str__(), open_spiel.python.games.block_dominoes.BlockDominoesState._apply_action(), open_spiel.python.games.team_dominoes.DominoesState._apply_action(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState._legal_actions(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState._legal_actions(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState._legal_actions(), open_spiel.python.mfg.games.normal_form_game.MFGNormalFormState._legal_actions(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState._legal_actions(), and open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState._legal_actions().
first()
open_spiel.python.rl_environment.TimeStep.first (self)
Definition at line 81 of file rl_environment.py.
  def first(self):
    return self.step_type == StepType.FIRST
is_simultaneous_move()
open_spiel.python.rl_environment.TimeStep.is_simultaneous_move (self)
Definition at line 90 of file rl_environment.py.
  def is_simultaneous_move(self):
    return self.observations["current_player"] == SIMULTANEOUS_PLAYER_ID
last()
open_spiel.python.rl_environment.TimeStep.last (self)
Definition at line 87 of file rl_environment.py.
  def last(self):
    return self.step_type == StepType.LAST
mid()
open_spiel.python.rl_environment.TimeStep.mid (self)
Definition at line 84 of file rl_environment.py.
  def mid(self):
    return self.step_type == StepType.MID
Member Data Documentation
step_type
open_spiel.python.rl_environment.TimeStep.step_type
Definition at line 82 of file rl_environment.py.
The documentation for this class was generated from the following file:
open_spiel/python/rl_environment.py