open spiel: open_spiel::algorithms::internal::TreeVector< T, Id > Class Template Reference
open_spiel::algorithms::internal::TreeVector< T, Id > Class Template Reference
Public Member Functions
TreeVector (const InfostateTree *tree)
TreeVector (const InfostateTree *tree, std::vector< T > vec)
T & operator[] (const Id &id)
const T & operator[] (const Id &id) const
std::ostream & operator<< (std::ostream &os) const
size_t size () const
Range< Id > range ()
Range< Id > range (size_t from, size_t to)
const InfostateTree * tree () const
Detailed Description
template<typename T, typename Id>
class open_spiel::algorithms::internal::TreeVector< T, Id >
Definition at line 659 of file infostate_tree.h.
Constructor & Destructor Documentation
TreeVector() [1/2]
template<typename T , typename Id > open_spiel::algorithms::internal::TreeVector< T, Id >::TreeVector (const InfostateTree * tree) inline explicit
Definition at line 664 of file infostate_tree.h.
      : tree_(tree), vec_(tree_->num_ids(Id(kUndefinedNodeId, tree))) {}
TreeVector() [2/2]
template<typename T , typename Id > open_spiel::algorithms::internal::TreeVector< T, Id >::TreeVector (const InfostateTree * tree, std::vector< T > vec) inline
Definition at line 666 of file infostate_tree.h.
      : tree_(tree), vec_(std::move(vec)) {
    SPIEL_CHECK_EQ(tree_->num_ids(Id(kUndefinedNodeId, tree)), vec_.size());
  }
Member Function Documentation
operator<<()
template<typename T , typename Id > std::ostream & open_spiel::algorithms::internal::TreeVector< T, Id >::operator<< (std::ostream & os) const inline
Definition at line 682 of file infostate_tree.h.
{
    return os << vec_ << " (for player " << tree_->acting_player() << ')';
  }
operator[]() [1/2]
template<typename T , typename Id > T & open_spiel::algorithms::internal::TreeVector< T, Id >::operator[] (const Id & id) inline
Definition at line 670 of file infostate_tree.h.
{
    SPIEL_DCHECK_TRUE(id.BelongsToTree(tree_));
    SPIEL_DCHECK_LE(0, id.id());
    SPIEL_DCHECK_LT(id.id(), vec_.size());
    return vec_[id.id()];
  }
operator[]() [2/2]
template<typename T , typename Id > const T & open_spiel::algorithms::internal::TreeVector< T, Id >::operator[] (const Id & id) const inline
Definition at line 676 of file infostate_tree.h.
{
    SPIEL_DCHECK_TRUE(id.BelongsToTree(tree_));
    SPIEL_DCHECK_LE(0, id.id());
    SPIEL_DCHECK_LT(id.id(), vec_.size());
    return vec_[id.id()];
  }
range() [1/2]
template<typename T , typename Id > Range< Id > open_spiel::algorithms::internal::TreeVector< T, Id >::range () inline
Definition at line 686 of file infostate_tree.h.
{ return Range<Id>(0, vec_.size(), tree_); }
range() [2/2]
template<typename T , typename Id > Range< Id > open_spiel::algorithms::internal::TreeVector< T, Id >::range (size_t from, size_t to) inline
Definition at line 687 of file infostate_tree.h.
{ return Range<Id>(from, to, tree_); }
size()
template<typename T , typename Id > size_t open_spiel::algorithms::internal::TreeVector< T, Id >::size () const inline
Definition at line 685 of file infostate_tree.h.
{ return vec_.size(); }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::__init__(), open_spiel.python.mfg.games.crowd_avoidance.Observer::__init__(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::__init__(), open_spiel.python.mfg.games.crowd_modelling.Observer::__init__(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::__init__(), open_spiel.python.mfg.games.linear_quadratic.Observer::__init__(), open_spiel.python.mfg.games.normal_form_game.MFGNormalFormState::__init__(), open_spiel.python.mfg.games.normal_form_game.Observer::__init__(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::__init__(), open_spiel.python.mfg.games.periodic_aversion.Observer::__init__(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::__init__(), open_spiel.python.mfg.games.predator_prey.Observer::__init__(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), and open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos().
tree()
template<typename T , typename Id > const InfostateTree * open_spiel::algorithms::internal::TreeVector< T, Id >::tree () const inline
Definition at line 688 of file infostate_tree.h.
{ return tree_; }
The documentation for this class was generated from the following file:
open_spiel/algorithms/infostate_tree.h