open spiel: open_spiel.python.algorithms.efr.LocalSwapTransform Class Reference
open_spiel.python.algorithms.efr.LocalSwapTransform Class Reference
Public Member Functions
__init__ (self, target, source, actions_num, is_external=True)
str __repr__ (self)
bool __eq__ (self, other)
__hash__ (self)
deviate (self, strategy)
Static Public Attributes
source_action = attr.ib()
target_action = attr.ib()
matrix_transform = attr.ib()
actions_num = attr.ib()
is_external = attr.ib()
Detailed Description
Represents a swap transformation (both external and internal).
Represents a swap transformation (both external and internal)
for an information state for a certain number of actions.
Definition at line 1285 of file efr.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.algorithms.efr.LocalSwapTransform.__init__ (self, target, source, actions_num, is_external = True)
Creates a matrix transformation.
Creates the matrix transformation describing the swap transformation
and initalises variables.
Args:
  target: the action that will be played when the deviation is triggered.
  source: the action that triggers a swap to the target action
    (used only by internal deviations, i.e is_external = False)
  actions_num: the number of actions that can be played for this
    information state.
  is_external: determine whether to create an internal or external
    deviation.
Definition at line 1298 of file efr.py.
  def __init__(self, target, source, actions_num, is_external=True):
    """Creates a matrix transformation.
    Creates the matrix transformation describing the swap transformation
    and initalises variables.
    Args:
      target: the action that will be played when the deviation is triggered.
      source: the action that triggers a swap to the target action
        (used only by internal deviations, i.e is_external = False)
      actions_num: the number of actions that can be played for this
        information state.
      is_external: determine whether to create an internal or external
        deviation.
    """
    self.source_action = source
    self.target_action = target
    self.actions_num = actions_num
    if is_external:
      self.source_action = None
      self.matrix_transform = np.zeros((actions_num, actions_num))
      self.matrix_transform[target] = np.ones(actions_num)
    else:
      self.matrix_transform = np.eye(actions_num)
      self.matrix_transform[target][source] = 1
      self.matrix_transform[source][source] = 0
References open_spiel.python.algorithms.efr.LocalSwapTransform.actions_num, open_spiel.python.algorithms.efr.LocalSwapTransform.matrix_transform, open_spiel.python.algorithms.efr.LocalSwapTransform.source_action, and open_spiel.python.algorithms.efr.LocalSwapTransform.target_action.
Member Function Documentation
__eq__()
bool open_spiel.python.algorithms.efr.LocalSwapTransform.__eq__ (self, other)
Definition at line 1333 of file efr.py.
  def __eq__(self, other) -> bool:
    return (
        self.source_action == other.source_action
        and self.target_action == other.target_action
        and self.actions_num == other.actions_num
    )
__hash__()
open_spiel.python.algorithms.efr.LocalSwapTransform.__hash__ (self)
Definition at line 1340 of file efr.py.
  def __hash__(self):
    return hash(
        f"{str(self.source_action)} {str(self.target_action)}                "
        f" {str(self.actions_num)} {str(self.is_external)}"
    )
__repr__()
str open_spiel.python.algorithms.efr.LocalSwapTransform.__repr__ (self)
Definition at line 1325 of file efr.py.
  def __repr__(self) -> str:
    return (
        "Swapping from Action: "
        + str(self.source_action)
        + " to Action: "
        + str(self.target_action)
    )
deviate()
open_spiel.python.algorithms.efr.LocalSwapTransform.deviate (self, strategy)
Returns a strategy array.
Returns the strategy array given by deviating according to
'self.matrix_transform' matrix.
Args:
  strategy: the strategy array to deviate from.
Returns:
  the matrix product of the the matrix_transform and the provided strategy.
Definition at line 1346 of file efr.py.
  def deviate(self, strategy):
    """Returns a strategy array.
    Returns the strategy array given by deviating according to
    'self.matrix_transform' matrix.
    Args:
      strategy: the strategy array to deviate from.
    Returns:
      the matrix product of the the matrix_transform and the provided strategy.
    """
    return np.matmul(self.matrix_transform, strategy)
References open_spiel.python.algorithms.efr.LocalSwapTransform.matrix_transform.
Member Data Documentation
actions_num
open_spiel.python.algorithms.efr.LocalSwapTransform.actions_num = attr.ib() static
Definition at line 1295 of file efr.py.
Referenced by open_spiel.python.algorithms.efr.LocalSwapTransform.__init__().
is_external
open_spiel.python.algorithms.efr.LocalSwapTransform.is_external = attr.ib() static
Definition at line 1296 of file efr.py.
matrix_transform
open_spiel.python.algorithms.efr.LocalSwapTransform.matrix_transform = attr.ib() static
Definition at line 1294 of file efr.py.
Referenced by open_spiel.python.algorithms.efr.LocalSwapTransform.__init__(), and open_spiel.python.algorithms.efr.LocalSwapTransform.deviate().
source_action
open_spiel.python.algorithms.efr.LocalSwapTransform.source_action = attr.ib() static
Definition at line 1292 of file efr.py.
Referenced by open_spiel.python.algorithms.efr.LocalSwapTransform.__init__().
target_action
open_spiel.python.algorithms.efr.LocalSwapTransform.target_action = attr.ib() static
Definition at line 1293 of file efr.py.
Referenced by open_spiel.python.algorithms.efr.LocalSwapTransform.__init__().
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/efr.py