open spiel: absl::time_internal::cctz::HasDifference< T1, T2 > Struct Template Reference
absl::time_internal::cctz::HasDifference< T1, T2 > Struct Template Reference
Static Public Member Functions
template<typename U1 , typename U2 >
static std::false_type test (...)
template<typename U1 , typename U2 >
static std::true_type test (decltype(std::declval< U1 >() - std::declval< U2 >()))
Static Public Attributes
static constexpr bool value = decltype(test<T1, T2>(0))::value
Detailed Description
template<typename T1, typename T2>
struct absl::time_internal::cctz::HasDifference< T1, T2 >
Definition at line 548 of file civil_time_test.cc.
Member Data Documentation
value
template<typename T1 , typename T2 > bool absl::time_internal::cctz::HasDifference< T1, T2 >::value = decltype(test<T1, T2>(0))::value static constexpr
Definition at line 553 of file civil_time_test.cc.
Referenced by open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::__init__(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::__init__(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), and open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/time/internal/cctz/src/civil_time_test.cc