open spiel: absl::container_internal::internal_compressed_tuple::Storage< T, I, UseBase > Struct Template Reference
absl::container_internal::internal_compressed_tuple::Storage< T, I, UseBase > Struct Template Reference
Public Member Functions
template<typename V >
constexpr Storage (absl::in_place_t, V &&v)
constexpr const T & get () const &
T & get () &
constexpr const T && get () const &&
T && get () &&
Public Attributes
T value
Detailed Description
template<typename T, size_t I, bool UseBase = ShouldUseBase<T>()>
struct absl::container_internal::internal_compressed_tuple::Storage< T, I, UseBase >
Definition at line 103 of file compressed_tuple.h.
Constructor & Destructor Documentation
Storage()
template<typename T , size_t I, bool UseBase = ShouldUseBase<T>()> template<typename V > absl::container_internal::internal_compressed_tuple::Storage< T, I, UseBase >::Storage (absl::in_place_t , V && v) inline explicit constexpr
Definition at line 107 of file compressed_tuple.h.
      : value(absl::forward<V>(v)) {}
Member Function Documentation
get() [1/4]
template<typename T , size_t I, bool UseBase = ShouldUseBase<T>()> T & absl::container_internal::internal_compressed_tuple::Storage< T, I, UseBase >::get () & inline
Definition at line 110 of file compressed_tuple.h.
{ return value; }
get() [2/4]
template<typename T , size_t I, bool UseBase = ShouldUseBase<T>()> T && absl::container_internal::internal_compressed_tuple::Storage< T, I, UseBase >::get () && inline
Definition at line 112 of file compressed_tuple.h.
{ return std::move(*this).value; }
get() [3/4]
template<typename T , size_t I, bool UseBase = ShouldUseBase<T>()> const T & absl::container_internal::internal_compressed_tuple::Storage< T, I, UseBase >::get () const & inline constexpr
Definition at line 109 of file compressed_tuple.h.
{ return value; }
get() [4/4]
template<typename T , size_t I, bool UseBase = ShouldUseBase<T>()> const T && absl::container_internal::internal_compressed_tuple::Storage< T, I, UseBase >::get () const && inline constexpr
Definition at line 111 of file compressed_tuple.h.
{ return absl::move(*this).value; }
Member Data Documentation
value
template<typename T , size_t I, bool UseBase = ShouldUseBase<T>()> T absl::container_internal::internal_compressed_tuple::Storage< T, I, UseBase >::value
Definition at line 104 of file compressed_tuple.h.
Referenced by open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::__init__(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::__init__(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), and open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/compressed_tuple.h