open spiel: absl::str_format_internal::FILERawSink Class Reference
absl::str_format_internal::FILERawSink Class Reference
Public Member Functions
FILERawSink (std::FILE *output)
void Write (string_view v)
size_t count () const
int error () const
Detailed Description
Definition at line 55 of file output.h.
Constructor & Destructor Documentation
FILERawSink()
absl::str_format_internal::FILERawSink::FILERawSink (std::FILE * output) inline explicit
Definition at line 57 of file output.h.
: output_(output) {}
Member Function Documentation
count()
size_t absl::str_format_internal::FILERawSink::count () const inline
Definition at line 61 of file output.h.
{ return count_; }
Referenced by open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_add_to_queue_count_weighted(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_lcb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_ucb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::delta(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::evaluate_strategy_profile(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::initialise_mean_and_count(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::run(), and open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::update_mean_and_count().
error()
int absl::str_format_internal::FILERawSink::error () const inline
Definition at line 62 of file output.h.
{ return error_; }
Write()
void absl::str_format_internal::FILERawSink::Write (string_view v)
Definition at line 42 of file output.cc.
{
  while (!v.empty() && !error_) {
    // Reset errno to zero in case the libc implementation doesn't set errno
    // when a failure occurs.
    ClearErrnoGuard guard;
    if (size_t result = std::fwrite(v.data(), 1, v.size(), output_)) {
      // Some progress was made.
      count_ += result;
      v.remove_prefix(result);
    } else {
      if (errno == EINTR) {
        continue;
      } else if (errno) {
        error_ = errno;
      } else if (std::ferror(output_)) {
        // Non-POSIX compliant libc implementations may not set errno, so we
        // have check the streams error indicator.
        error_ = EBADF;
      } else {
        // We're likely on a non-POSIX system that encountered EINTR but had no
        // way of reporting it.
        continue;
      }
    }
  }
}
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/str_format/output.h
open_spiel/abseil-cpp/absl/strings/internal/str_format/output.cc