open spiel: std::numeric_limits< absl::uint128 > Class Reference
std::numeric_limits< absl::uint128 > Class Reference
Static Public Member Functions
static constexpr absl::uint128 min ()
static constexpr absl::uint128 lowest ()
static constexpr absl::uint128 max ()
static constexpr absl::uint128 epsilon ()
static constexpr absl::uint128 round_error ()
static constexpr absl::uint128 infinity ()
static constexpr absl::uint128 quiet_NaN ()
static constexpr absl::uint128 signaling_NaN ()
static constexpr absl::uint128 denorm_min ()
Static Public Attributes
static constexpr bool is_specialized = true
static constexpr bool is_signed = false
static constexpr bool is_integer = true
static constexpr bool is_exact = true
static constexpr bool has_infinity = false
static constexpr bool has_quiet_NaN = false
static constexpr bool has_signaling_NaN = false
static constexpr float_denorm_style has_denorm = denorm_absent
static constexpr bool has_denorm_loss = false
static constexpr float_round_style round_style = round_toward_zero
static constexpr bool is_iec559 = false
static constexpr bool is_bounded = true
static constexpr bool is_modulo = true
static constexpr int digits = 128
static constexpr int digits10 = 38
static constexpr int max_digits10 = 0
static constexpr int radix = 2
static constexpr int min_exponent = 0
static constexpr int min_exponent10 = 0
static constexpr int max_exponent = 0
static constexpr int max_exponent10 = 0
static constexpr bool traps = numeric_limits<uint64_t>::traps
static constexpr bool tinyness_before = false
Detailed Description
Definition at line 259 of file int128.h.
Member Function Documentation
denorm_min()
static constexpr absl::uint128 std::numeric_limits< absl::uint128 >::denorm_min () inline static constexpr
Definition at line 297 of file int128.h.
{ return 0; }
epsilon()
static constexpr absl::uint128 std::numeric_limits< absl::uint128 >::epsilon () inline static constexpr
Definition at line 292 of file int128.h.
{ return 0; }
Referenced by open_spiel.python.coalitional_games.least_core_lagrangian.CoreOptimization::loss(), open_spiel.python.coalitional_games.least_core_lagrangian.CoreOptimizationLogits::loss(), open_spiel.python.coalitional_games.least_core_lagrangian.CoreOptimization::solve(), and open_spiel.python.coalitional_games.least_core_lagrangian.CoreOptimizationLogits::solve().
infinity()
static constexpr absl::uint128 std::numeric_limits< absl::uint128 >::infinity () inline static constexpr
Definition at line 294 of file int128.h.
{ return 0; }
lowest()
static constexpr absl::uint128 std::numeric_limits< absl::uint128 >::lowest () inline static constexpr
Definition at line 290 of file int128.h.
{ return 0; }
max()
static constexpr absl::uint128 std::numeric_limits< absl::uint128 >::max () inline static constexpr
Definition at line 291 of file int128.h.
{ return absl::Uint128Max(); }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
static constexpr absl::uint128 std::numeric_limits< absl::uint128 >::min () inline static constexpr
Definition at line 289 of file int128.h.
{ return 0; }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
quiet_NaN()
static constexpr absl::uint128 std::numeric_limits< absl::uint128 >::quiet_NaN () inline static constexpr
Definition at line 295 of file int128.h.
{ return 0; }
round_error()
static constexpr absl::uint128 std::numeric_limits< absl::uint128 >::round_error () inline static constexpr
Definition at line 293 of file int128.h.
{ return 0; }
signaling_NaN()
static constexpr absl::uint128 std::numeric_limits< absl::uint128 >::signaling_NaN () inline static constexpr
Definition at line 296 of file int128.h.
{ return 0; }
Member Data Documentation
digits
int std::numeric_limits< absl::uint128 >::digits = 128 static constexpr
Definition at line 274 of file int128.h.
digits10
int std::numeric_limits< absl::uint128 >::digits10 = 38 static constexpr
Definition at line 275 of file int128.h.
has_denorm
float_denorm_style std::numeric_limits< absl::uint128 >::has_denorm = denorm_absent static constexpr
Definition at line 268 of file int128.h.
has_denorm_loss
bool std::numeric_limits< absl::uint128 >::has_denorm_loss = false static constexpr
Definition at line 269 of file int128.h.
has_infinity
bool std::numeric_limits< absl::uint128 >::has_infinity = false static constexpr
Definition at line 265 of file int128.h.
has_quiet_NaN
bool std::numeric_limits< absl::uint128 >::has_quiet_NaN = false static constexpr
Definition at line 266 of file int128.h.
has_signaling_NaN
bool std::numeric_limits< absl::uint128 >::has_signaling_NaN = false static constexpr
Definition at line 267 of file int128.h.
is_bounded
bool std::numeric_limits< absl::uint128 >::is_bounded = true static constexpr
Definition at line 272 of file int128.h.
is_exact
bool std::numeric_limits< absl::uint128 >::is_exact = true static constexpr
Definition at line 264 of file int128.h.
is_iec559
bool std::numeric_limits< absl::uint128 >::is_iec559 = false static constexpr
Definition at line 271 of file int128.h.
is_integer
bool std::numeric_limits< absl::uint128 >::is_integer = true static constexpr
Definition at line 263 of file int128.h.
is_modulo
bool std::numeric_limits< absl::uint128 >::is_modulo = true static constexpr
Definition at line 273 of file int128.h.
is_signed
bool std::numeric_limits< absl::uint128 >::is_signed = false static constexpr
Definition at line 262 of file int128.h.
is_specialized
bool std::numeric_limits< absl::uint128 >::is_specialized = true static constexpr
Definition at line 261 of file int128.h.
max_digits10
int std::numeric_limits< absl::uint128 >::max_digits10 = 0 static constexpr
Definition at line 276 of file int128.h.
max_exponent
int std::numeric_limits< absl::uint128 >::max_exponent = 0 static constexpr
Definition at line 280 of file int128.h.
max_exponent10
int std::numeric_limits< absl::uint128 >::max_exponent10 = 0 static constexpr
Definition at line 281 of file int128.h.
min_exponent
int std::numeric_limits< absl::uint128 >::min_exponent = 0 static constexpr
Definition at line 278 of file int128.h.
min_exponent10
int std::numeric_limits< absl::uint128 >::min_exponent10 = 0 static constexpr
Definition at line 279 of file int128.h.
radix
int std::numeric_limits< absl::uint128 >::radix = 2 static constexpr
Definition at line 277 of file int128.h.
round_style
float_round_style std::numeric_limits< absl::uint128 >::round_style = round_toward_zero static constexpr
Definition at line 270 of file int128.h.
tinyness_before
bool std::numeric_limits< absl::uint128 >::tinyness_before = false static constexpr
Definition at line 287 of file int128.h.
traps
bool std::numeric_limits< absl::uint128 >::traps = numeric_limits<uint64_t>::traps static constexpr
Definition at line 285 of file int128.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/numeric/int128.h