open spiel: absl::random_internal::pcg_engine< Params, Mix > Class Template Reference
absl::random_internal::pcg_engine< Params, Mix > Class Template Reference
Public Types
using result_type = typename Mix::result_type
Public Member Functions
pcg_engine (uint64_t seed_value=0)
template<class SeedSequence , typename = typename absl::enable_if_t< !std::is_same<SeedSequence, pcg_engine>::value>>
pcg_engine (SeedSequence &&seq)
pcg_engine (const pcg_engine &)=default
pcg_engine & operator= (const pcg_engine &)=default
pcg_engine (pcg_engine &&)=default
pcg_engine & operator= (pcg_engine &&)=default
result_type operator() ()
void seed (uint64_t seed_value=0)
template<class SeedSequence >
absl::enable_if_t< !std::is_convertible< SeedSequence, uint64_t >::value, void > seed (SeedSequence &&seq)
void discard (uint64_t count)
bool operator== (const pcg_engine &other) const
bool operator!= (const pcg_engine &other) const
Static Public Member Functions
static constexpr result_type min ()
static constexpr result_type max ()
Friends
template<class CharT , class Traits >
absl::enable_if_t<(sizeof(state_type)==16), std::basic_ostream< CharT, Traits > & > operator<< (std::basic_ostream< CharT, Traits > &os, const pcg_engine &engine)
template<class CharT , class Traits >
absl::enable_if_t<(sizeof(state_type)<=8), std::basic_ostream< CharT, Traits > & > operator<< (std::basic_ostream< CharT, Traits > &os, const pcg_engine &engine)
template<class CharT , class Traits >
absl::enable_if_t<(sizeof(state_type)==16), std::basic_istream< CharT, Traits > & > operator>> (std::basic_istream< CharT, Traits > &is, pcg_engine &engine)
template<class CharT , class Traits >
absl::enable_if_t<(sizeof(state_type)<=8), std::basic_istream< CharT, Traits > & > operator>> (std::basic_istream< CharT, Traits > &is, pcg_engine &engine)
Detailed Description
template<typename Params, typename Mix>
class absl::random_internal::pcg_engine< Params, Mix >
Definition at line 41 of file pcg_engine.h.
Member Typedef Documentation
result_type
template<typename Params , typename Mix > using absl::random_internal::pcg_engine< Params, Mix >::result_type = typename Mix::result_type
Definition at line 57 of file pcg_engine.h.
Constructor & Destructor Documentation
pcg_engine() [1/2]
template<typename Params , typename Mix > absl::random_internal::pcg_engine< Params, Mix >::pcg_engine (uint64_t seed_value = 0) inline explicit
Definition at line 67 of file pcg_engine.h.
{ seed(seed_value); }
pcg_engine() [2/2]
template<typename Params , typename Mix > template<class SeedSequence , typename = typename absl::enable_if_t< !std::is_same<SeedSequence, pcg_engine>::value>> absl::random_internal::pcg_engine< Params, Mix >::pcg_engine (SeedSequence && seq) inline explicit
Definition at line 72 of file pcg_engine.h.
{
    seed(seq);
  }
Member Function Documentation
discard()
template<typename Params , typename Mix > void absl::random_internal::pcg_engine< Params, Mix >::discard (uint64_t count) inline
Definition at line 99 of file pcg_engine.h.
{ state_ = advance(state_, count); }
max()
template<typename Params , typename Mix > static constexpr result_type absl::random_internal::pcg_engine< Params, Mix >::max () inline static constexpr
Definition at line 63 of file pcg_engine.h.
{
    return (std::numeric_limits<result_type>::max)();
  }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
template<typename Params , typename Mix > static constexpr result_type absl::random_internal::pcg_engine< Params, Mix >::min () inline static constexpr
Definition at line 59 of file pcg_engine.h.
{
    return (std::numeric_limits<result_type>::min)();
  }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
operator!=()
template<typename Params , typename Mix > bool absl::random_internal::pcg_engine< Params, Mix >::operator!= (const pcg_engine< Params, Mix > & other) const inline
Definition at line 105 of file pcg_engine.h.
{ return !(*this == other); }
operator()()
template<typename Params , typename Mix > result_type absl::random_internal::pcg_engine< Params, Mix >::operator() () inline
Definition at line 81 of file pcg_engine.h.
{
    // Advance the LCG state, always using the new value to generate the output.
    state_ = lcg(state_);
    return Mix{}(state_);
  }
operator==()
template<typename Params , typename Mix > bool absl::random_internal::pcg_engine< Params, Mix >::operator== (const pcg_engine< Params, Mix > & other) const inline
Definition at line 101 of file pcg_engine.h.
{
    return state_ == other.state_;
  }
seed() [1/2]
template<typename Params , typename Mix > template<class SeedSequence > absl::enable_if_t< !std::is_convertible< SeedSequence, uint64_t >::value, void > absl::random_internal::pcg_engine< Params, Mix >::seed (SeedSequence && seq) inline
Definition at line 95 of file pcg_engine.h.
{
    reseed(seq);
  }
Referenced by open_spiel.python.algorithms.adidas_utils.games.big.TensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::__init__(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.small.MatrixGame::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.nonsymmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.symmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal_noaux.Solver::__init__(), and open_spiel.python.algorithms.adidas_utils.solvers.symmetric.regmatch.Solver::__init__().
seed() [2/2]
template<typename Params , typename Mix > void absl::random_internal::pcg_engine< Params, Mix >::seed (uint64_t seed_value = 0) inline
Definition at line 87 of file pcg_engine.h.
{
    state_type tmp = seed_value;
    state_ = lcg(tmp + Params::increment());
  }
Referenced by open_spiel.python.algorithms.adidas_utils.games.big.TensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::__init__(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.small.MatrixGame::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.nonsymmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.symmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal_noaux.Solver::__init__(), and open_spiel.python.algorithms.adidas_utils.solvers.symmetric.regmatch.Solver::__init__().
Friends And Related Symbol Documentation
operator<< [1/2]
template<typename Params , typename Mix > template<class CharT , class Traits > absl::enable_if_t<(sizeof(state_type)==16), std::basic_ostream< CharT, Traits > & > operator<< (std::basic_ostream< CharT, Traits > & os, const pcg_engine< Params, Mix > & engine) friend
Definition at line 108 of file pcg_engine.h.
{
    auto saver = random_internal::make_ostream_state_saver(os);
    random_internal::stream_u128_helper<state_type> helper;
    helper.write(pcg_engine::params_type::multiplier(), os);
    os << os.fill();
    helper.write(pcg_engine::params_type::increment(), os);
    os << os.fill();
    helper.write(engine.state_, os);
    return os;
  }
operator<< [2/2]
template<typename Params , typename Mix > template<class CharT , class Traits > absl::enable_if_t<(sizeof(state_type)<=8), std::basic_ostream< CharT, Traits > & > operator<< (std::basic_ostream< CharT, Traits > & os, const pcg_engine< Params, Mix > & engine) friend
Definition at line 124 of file pcg_engine.h.
{
    auto saver = random_internal::make_ostream_state_saver(os);
    os << pcg_engine::params_type::multiplier() << os.fill();
    os << pcg_engine::params_type::increment() << os.fill();
    os << engine.state_;
    return os;
  }
operator>> [1/2]
template<typename Params , typename Mix > template<class CharT , class Traits > absl::enable_if_t<(sizeof(state_type)==16), std::basic_istream< CharT, Traits > & > operator>> (std::basic_istream< CharT, Traits > & is, pcg_engine< Params, Mix > & engine) friend
Definition at line 139 of file pcg_engine.h.
                          {                   // NOLINT(runtime/references)
    random_internal::stream_u128_helper<state_type> helper;
    auto mult = helper.read(is);
    auto inc = helper.read(is);
    auto tmp = helper.read(is);
    if (mult != pcg_engine::params_type::multiplier() ||
        inc != pcg_engine::params_type::increment()) {
      // signal failure by setting the failbit.
      is.setstate(is.rdstate() | std::ios_base::failbit);
    }
    if (!is.fail()) {
      engine.state_ = tmp;
    }
    return is;
  }
operator>> [2/2]
template<typename Params , typename Mix > template<class CharT , class Traits > absl::enable_if_t<(sizeof(state_type)<=8), std::basic_istream< CharT, Traits > & > operator>> (std::basic_istream< CharT, Traits > & is, pcg_engine< Params, Mix > & engine) friend
Definition at line 160 of file pcg_engine.h.
                          {                   // NOLINT(runtime/references)
    state_type mult{}, inc{}, tmp{};
    is >> mult >> inc >> tmp;
    if (mult != pcg_engine::params_type::multiplier() ||
        inc != pcg_engine::params_type::increment()) {
      // signal failure by setting the failbit.
      is.setstate(is.rdstate() | std::ios_base::failbit);
    }
    if (!is.fail()) {
      engine.state_ = tmp;
    }
    return is;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/internal/pcg_engine.h