open spiel: open_spiel.python.algorithms.alpha_zero.model Namespace Reference
open_spiel.python.algorithms.alpha_zero.model Namespace Reference
Classes
class Losses
class Model
class TrainInput
Functions
cascade (x, fns)
batch_norm (training, updates, name)
residual_layer (inputs, num_filters, kernel_size, training, updates, name)
Variables
tfkl = tf.keras.layers
conv_2d = functools.partial(tfkl.Conv2D, padding="same")
Detailed Description
An AlphaZero style model with a policy and value head.
Function Documentation
batch_norm()
open_spiel.python.algorithms.alpha_zero.model.batch_norm (training, updates, name)
A batch norm layer.
Args:
  training: A placeholder of whether this is done in training or not.
  updates: A list to be extended with this layer's updates.
  name: Name of the layer.
Returns:
  A function to apply to the previous layer.
Definition at line 43 of file model.py.
def batch_norm(training, updates, name):
  """A batch norm layer.
  Args:
    training: A placeholder of whether this is done in training or not.
    updates: A list to be extended with this layer's updates.
    name: Name of the layer.
  Returns:
    A function to apply to the previous layer.
  """
  bn = tfkl.BatchNormalization(name=name)
  def batch_norm_layer(x):
    # This emits a warning that training is a placeholder instead of a concrete
    # bool, but seems to work anyway.
    applied = bn(x, training)
    updates.extend(bn.updates)
    return applied
  return batch_norm_layer
References open_spiel.python.algorithms.alpha_zero.model.batch_norm().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Model._define_graph(), and open_spiel.python.algorithms.alpha_zero.model.batch_norm().
cascade()
open_spiel.python.algorithms.alpha_zero.model.cascade (x, fns)
Definition at line 34 of file model.py.
def cascade(x, fns):
  for fn in fns:
    x = fn(x)
  return x
residual_layer()
open_spiel.python.algorithms.alpha_zero.model.residual_layer (inputs, num_filters, kernel_size, training, updates, name)
Definition at line 64 of file model.py.
def residual_layer(inputs, num_filters, kernel_size, training, updates, name):
  return cascade(inputs, [
      conv_2d(num_filters, kernel_size, name=f"{name}_res_conv1"),
      batch_norm(training, updates, f"{name}_res_batch_norm1"),
      tfkl.Activation("relu"),
      conv_2d(num_filters, kernel_size, name=f"{name}_res_conv2"),
      batch_norm(training, updates, f"{name}_res_batch_norm2"),
      lambda x: tfkl.add([x, inputs]),
      tfkl.Activation("relu"),
  ])
Variable Documentation
conv_2d
open_spiel.python.algorithms.alpha_zero.model.conv_2d = functools.partial(tfkl.Conv2D, padding="same")
Definition at line 40 of file model.py.
tfkl
open_spiel.python.algorithms.alpha_zero.model.tfkl = tf.keras.layers
Definition at line 39 of file model.py.