open spiel: open_spiel.python.tests.mfg_implementation_test.mfg_test Namespace Reference
open_spiel.python.tests.mfg_implementation_test.mfg_test Namespace Reference
Classes
class FiniteHorizonTest
Functions
_get_next_states (state, next_states, to_string)
_next_states (states, to_string)
type_from_states (states)
Variables
FLAGS = flags.FLAGS
Detailed Description
Tests that Mean Field Games are implemented properly.
These tests are intended to help developers to write mean field games that
satisfy most of the unspecified constraints assumed by the following algorithms:
- python/mfg/algorithms/policy_value.py
- python/mfg/algorithms/nash_conv.py
- python/mfg/algorithms/mirror_descent.py
- python/mfg/algorithms/fictitious_play.py
- python/mfg/algorithms/distribution.py
- python/mfg/algorithms/best_response_value.py
- python/rl_environment.py
These tests are not exhaustive and will be updated with time.
Function Documentation
_get_next_states()
open_spiel.python.tests.mfg_implementation_test.mfg_test._get_next_states (state, next_states, to_string) protected
Extract non-chance states for a subgame into the all_states dict.
Definition at line 51 of file mfg_test.py.
def _get_next_states(state, next_states, to_string):
  """Extract non-chance states for a subgame into the all_states dict."""
  is_mean_field = state.current_player() == pyspiel.PlayerId.MEAN_FIELD
  if state.is_chance_node():
    # Add only if not already present
    for action, _ in state.chance_outcomes():
      next_state = state.child(action)
      state_str = to_string(next_state)
      if state_str not in next_states:
        next_states[state_str] = next_state
  if is_mean_field:
    support = state.distribution_support()
    next_state = state.clone()
    support_length = len(support)
    # update with a dummy distribution
    next_state.update_distribution(
        [1.0 / support_length for _ in range(support_length)])
    state_str = to_string(next_state)
    if state_str not in next_states:
      next_states[state_str] = next_state
  if int(state.current_player()) >= 0:
    for action in state.legal_actions():
      next_state = state.child(action)
      state_str = to_string(next_state)
      if state_str not in next_states:
        next_states[state_str] = next_state
References open_spiel.python.tests.mfg_implementation_test.mfg_test._get_next_states().
Referenced by open_spiel.python.tests.mfg_implementation_test.mfg_test._get_next_states().
_next_states()
open_spiel.python.tests.mfg_implementation_test.mfg_test._next_states (states, to_string) protected
Definition at line 82 of file mfg_test.py.
def _next_states(states, to_string):
  next_states = {}
  for state in states:
    _get_next_states(state, next_states, to_string)
  return set(next_states.keys()), set(next_states.values())
type_from_states()
open_spiel.python.tests.mfg_implementation_test.mfg_test.type_from_states (states)
Get node type of a list of states and assert they are the same.
Definition at line 89 of file mfg_test.py.
def type_from_states(states):
  """Get node type of a list of states and assert they are the same."""
  types = [state.get_type() for state in states]
  assert len(set(types)) == 1
  return types[0]
Referenced by open_spiel.python.tests.mfg_implementation_test.mfg_test.FiniteHorizonTest.test_is_finite_horizon().
Variable Documentation
FLAGS
open_spiel.python.tests.mfg_implementation_test.mfg_test.FLAGS = flags.FLAGS
Definition at line 41 of file mfg_test.py.