open spiel: open_spiel.python.games.dynamic_routing_utils Namespace Reference
open_spiel.python.games.dynamic_routing_utils Namespace Reference
Classes
class Network
class OriginDestinationDemand
class Vehicle
Functions
str _road_section_from_nodes (str origin, str destination)
tuple[str, str] _nodes_from_road_section (str movement)
dict[str, Any] assign_dictionary_input_to_object (dict[str, Any] dict_object, Collection[str] road_sections, Any default_value)
Variables
int NO_POSSIBLE_ACTION = 0
Detailed Description
Utils module for dynamic routing game and mean field routing game.
This module has three main classes:
- Network
- Vehicle
- OriginDestinationDemand
Function Documentation
_nodes_from_road_section()
tuple[str, str] open_spiel.python.games.dynamic_routing_utils._nodes_from_road_section (str movement) protected
Split a road section 'A->B' to two nodes 'A' and 'B'.
Definition at line 40 of file dynamic_routing_utils.py.
def _nodes_from_road_section(movement: str) -> tuple[str, str]:
  """Split a road section 'A->B' to two nodes 'A' and 'B'."""
  origin, destination = movement.split("->")
  return origin, destination
Referenced by open_spiel.python.games.dynamic_routing_utils.Network.assert_valid_action(), open_spiel.python.games.dynamic_routing_utils.Network.is_location_at_sink_node(), open_spiel.python.games.dynamic_routing_utils.Network.return_list_for_matplotlib_quiver(), and open_spiel.python.games.dynamic_routing_utils.Network.return_position_of_road_section().
_road_section_from_nodes()
str open_spiel.python.games.dynamic_routing_utils._road_section_from_nodes (str origin, str destination) protected
Create a road section 'A->B' from two nodes 'A' and 'B'.
Definition at line 35 of file dynamic_routing_utils.py.
def _road_section_from_nodes(origin: str, destination: str) -> str:
  """Create a road section 'A->B' from two nodes 'A' and 'B'."""
  return f"{origin}->{destination}"
Referenced by open_spiel.python.games.dynamic_routing_utils.Network._create_action_by_road_section(), and open_spiel.python.games.dynamic_routing_utils.Network.get_action_id_from_movement().
assign_dictionary_input_to_object()
dict[str, Any] open_spiel.python.games.dynamic_routing_utils.assign_dictionary_input_to_object (dict[str, Any] dict_object, Collection[str] road_sections, Any default_value)
Check dictionary has road sections has key or return default_value dict.
Definition at line 46 of file dynamic_routing_utils.py.
                                      default_value: Any) -> dict[str, Any]:
  """Check dictionary has road sections has key or return default_value dict."""
  if dict_object:
    assert set(dict_object) == set(road_sections), (
        "Objects are not defined for each road sections.")
    return dict_object
  dict_object_returned = {}
  for road_section in road_sections:
    dict_object_returned[road_section] = default_value
  return dict_object_returned
Variable Documentation
NO_POSSIBLE_ACTION
int open_spiel.python.games.dynamic_routing_utils.NO_POSSIBLE_ACTION = 0
Definition at line 32 of file dynamic_routing_utils.py.