open spiel: open_spiel.python.egt.visualization Namespace Reference
open_spiel.python.egt.visualization Namespace Reference
Classes
class Dynamics2x2Axes
class Dynamics3x3Axes
class SimplexStreamMask
class SimplexTransform
Functions
_eval_dynamics_2x2_grid (dynamics, num_points)
_rk12_step (func, y0, dt)
Detailed Description
Visualization for single/multi-population dynamics in normal-form games.
  Example:
  game = pyspiel.load_game("matrix_pd")
  payoff_tensor = utils.game_payoffs_array(game)
  dyn = dynamics.MultiPopulationDynamics(payoff_tensor, dynamics.replicator)
  ax = plt.subplot(projection="2x2")
  ax.quiver(dyn)
Function Documentation
_eval_dynamics_2x2_grid()
open_spiel.python.egt.visualization._eval_dynamics_2x2_grid (dynamics, num_points) protected
Evaluates dynamics on a 2-D mesh-grid.
Args:
  dynamics: Population dynamics of type `dynamics.MultiPopulationDynamics`.
  num_points: Number of points along each dimension of the grid.
Returns:
  Mesh-grid (x, y) and corresponding derivatives of the first action for
    player 1 and 2 (u, v).
Definition at line 56 of file visualization.py.
def _eval_dynamics_2x2_grid(dynamics, num_points):
  """Evaluates dynamics on a 2-D mesh-grid.
  Args:
    dynamics: Population dynamics of type `dynamics.MultiPopulationDynamics`.
    num_points: Number of points along each dimension of the grid.
  Returns:
    Mesh-grid (x, y) and corresponding derivatives of the first action for
      player 1 and 2 (u, v).
  """
  assert dynamics.payoff_tensor.shape == (2, 2, 2)
  x = np.linspace(0., 1., num_points + 2)[1:-1]
  x, y = np.meshgrid(x, x)
  u = np.empty(x.shape)
  v = np.empty(x.shape)
  for i in range(num_points):
    for j in range(num_points):
      row_state = np.array([x[i, j], 1. - x[i, j]])
      col_state = np.array([y[i, j], 1. - y[i, j]])
      state = np.concatenate((row_state, col_state))
      dstate = dynamics(state)
      u[i][j] = dstate[0]
      v[i][j] = dstate[2]
  return x, y, u, v
Referenced by open_spiel.python.egt.visualization.Dynamics2x2Axes.quiver(), and open_spiel.python.egt.visualization.Dynamics2x2Axes.streamplot().
_rk12_step()
open_spiel.python.egt.visualization._rk12_step (func, y0, dt) protected
Improved Euler-Integration step to integrate dynamics.
Args:
  func: Function handle to time derivative.
  y0:   Current state.
  dt:   Integration step.
Returns:
  Next state.
Definition at line 85 of file visualization.py.
def _rk12_step(func, y0, dt):
  """Improved Euler-Integration step to integrate dynamics.
  Args:
    func: Function handle to time derivative.
    y0:   Current state.
    dt:   Integration step.
  Returns:
    Next state.
  """
  dy = func(y0)
  y_ = y0 + dt * dy
  return y0 + dt / 2. * (dy + func(y_))
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes.quiver().