open spiel: open_spiel.python.voting.kemeny_young.KemenyYoungVoting Class Reference
open_spiel.python.voting.kemeny_young.KemenyYoungVoting Class Reference
Public Member Functions
__init__ (self)
str name (self)
base.RankOutcome run_election (self, base.PreferenceProfile profile)
Public Member Functions inherited from open_spiel.python.voting.base.AbstractVotingMethod
bool is_valid_profile (self, PreferenceProfile profile)
Protected Member Functions
np.ndarray _score (self, np.ndarray pref_mat, Tuple[int,...] perm)
List[base.AlternativeId] _permutation_to_ranking (self, List[base.AlternativeId] alternatives, Tuple[base.AlternativeId,...] permutation)
Detailed Description
Implements Kemeny-Young's method.
Definition at line 25 of file kemeny_young.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.voting.kemeny_young.KemenyYoungVoting.__init__ (self)
Initializes the voting method.
Args:
  **method_specific_kwargs: optional extra args.
Reimplemented from open_spiel.python.voting.base.AbstractVotingMethod.
Definition at line 28 of file kemeny_young.py.
  def __init__(self):
    pass
Member Function Documentation
_permutation_to_ranking()
List[base.AlternativeId] open_spiel.python.voting.kemeny_young.KemenyYoungVoting._permutation_to_ranking (self, List[base.AlternativeId] alternatives, Tuple[base.AlternativeId, ...] permutation) protected
Definition at line 49 of file kemeny_young.py.
      permutation: Tuple[base.AlternativeId, ...]) -> List[base.AlternativeId]:
    assert len(permutation) == len(alternatives)
    return [alternatives[permutation[i]] for i in range(len(alternatives))]
Referenced by open_spiel.python.voting.kemeny_young.KemenyYoungVoting.run_election().
_score()
np.ndarray open_spiel.python.voting.kemeny_young.KemenyYoungVoting._score (self, np.ndarray pref_mat, Tuple[int, ...] perm) protected
Definition at line 34 of file kemeny_young.py.
  ) -> np.ndarray:
    # The score of alternative a_i in a ranking R is defined to be:
    #      KemenyScore(a_i) = sum_{a_j s.t. R(a_i) >= R(a_j)} N(a_i, a_j)
    # The score of ranking R is then sum_i KemenyScore(a_i).
    num_alts = len(perm)
    scores = np.zeros(num_alts, dtype=np.int32)
    for i in range(num_alts):
      for j in range(i+1, num_alts):
        scores[i] += pref_mat[perm[i], perm[j]]
    return scores
Referenced by open_spiel.python.voting.kemeny_young.KemenyYoungVoting.run_election().
name()
str open_spiel.python.voting.kemeny_young.KemenyYoungVoting.name (self)
Returns the name of the voting method.
Reimplemented from open_spiel.python.voting.base.AbstractVotingMethod.
Definition at line 31 of file kemeny_young.py.
  def name(self) -> str:
    return "kemeny_young"
run_election()
base.RankOutcome open_spiel.python.voting.kemeny_young.KemenyYoungVoting.run_election (self, base.PreferenceProfile profile)
Runs the election and returns the result.
Args:
    profile: a preference profile.
Returns:
    a RankOutcome object that can be queried for the results.
Reimplemented from open_spiel.python.voting.base.AbstractVotingMethod.
Definition at line 56 of file kemeny_young.py.
  def run_election(self, profile: base.PreferenceProfile) -> base.RankOutcome:
    assert self.is_valid_profile(profile)
    pref_mat = profile.pref_matrix()
    alternatives = profile.alternatives
    m = profile.num_alternatives()
    best_permutation = None
    best_score = -1
    best_score_array = None
    for permutation in itertools.permutations(range(m)):
      scores = self._score(pref_mat, permutation)
      total_score = scores.sum()
      if total_score > best_score:
        best_score = total_score
        best_score_array = scores
        best_permutation = permutation
    best_ranking = self._permutation_to_ranking(alternatives, best_permutation)
    outcome = base.RankOutcome(rankings=best_ranking,
                               scores=list(best_score_array))
    return outcome
References open_spiel.python.voting.kemeny_young.KemenyYoungVoting._permutation_to_ranking(), open_spiel.python.voting.kemeny_young.KemenyYoungVoting._score(), and open_spiel.python.voting.base.AbstractVotingMethod.is_valid_profile().
The documentation for this class was generated from the following file:
open_spiel/python/voting/kemeny_young.py