open spiel: open_spiel.python.examples.psro_v2_example Namespace Reference
open_spiel.python.examples.psro_v2_example Namespace Reference
Functions
init_pg_responder (sess, env)
init_br_responder (env)
init_dqn_responder (sess, env)
print_policy_analysis (policies, game, verbose=False)
gpsro_looper (env, oracle, agents)
main (argv)
Variables
FLAGS = flags.FLAGS
Detailed Description
Example running PSRO on OpenSpiel Sequential games.
To reproduce results from (Muller et al., "A Generalized Training Approach for
Multiagent Learning", ICLR 2020; https://arxiv.org/abs/1909.12823), run this
script with:
  - `game_name` in ['kuhn_poker', 'leduc_poker']
  - `n_players` in [2, 3, 4, 5]
  - `meta_strategy_method` in ['alpharank', 'uniform', 'nash', 'prd']
  - `rectifier` in ['', 'rectified']
The other parameters keeping their default values.
Function Documentation
gpsro_looper()
open_spiel.python.examples.psro_v2_example.gpsro_looper (env, oracle, agents)
Initializes and executes the GPSRO training loop.
Definition at line 244 of file psro_v2_example.py.
def gpsro_looper(env, oracle, agents):
  """Initializes and executes the GPSRO training loop."""
  sample_from_marginals = True  # TODO(somidshafiei) set False for alpharank
  training_strategy_selector = FLAGS.training_strategy_selector or strategy_selectors.probabilistic
  g_psro_solver = psro_v2.PSROSolver(
      env.game,
      oracle,
      initial_policies=agents,
      training_strategy_selector=training_strategy_selector,
      rectifier=FLAGS.rectifier,
      sims_per_entry=FLAGS.sims_per_entry,
      number_policies_selected=FLAGS.number_policies_selected,
      meta_strategy_method=FLAGS.meta_strategy_method,
      prd_iterations=50000,
      prd_gamma=1e-10,
      sample_from_marginals=sample_from_marginals,
      symmetric_game=FLAGS.symmetric_game)
  start_time = time.time()
  for gpsro_iteration in range(FLAGS.gpsro_iterations):
    if FLAGS.verbose:
      print("Iteration : {}".format(gpsro_iteration))
      print("Time so far: {}".format(time.time() - start_time))
    g_psro_solver.iteration()
    meta_game = g_psro_solver.get_meta_game()
    meta_probabilities = g_psro_solver.get_meta_strategies()
    policies = g_psro_solver.get_policies()
    if FLAGS.verbose:
      print("Meta game : {}".format(meta_game))
      print("Probabilities : {}".format(meta_probabilities))
    # The following lines only work for sequential games for the moment.
    if env.game.get_type().dynamics == pyspiel.GameType.Dynamics.SEQUENTIAL:
      aggregator = policy_aggregator.PolicyAggregator(env.game)
      aggr_policies = aggregator.aggregate(
          range(FLAGS.n_players), policies, meta_probabilities)
      exploitabilities, expl_per_player = exploitability.nash_conv(
          env.game, aggr_policies, return_only_nash_conv=False)
      _ = print_policy_analysis(policies, env.game, FLAGS.verbose)
      if FLAGS.verbose:
        print("Exploitabilities : {}".format(exploitabilities))
        print("Exploitabilities per player : {}".format(expl_per_player))
References open_spiel.python.examples.psro_v2_example.gpsro_looper(), open_spiel.python.examples.psro_v2_example.init_br_responder(), open_spiel.python.examples.psro_v2_example.init_dqn_responder(), open_spiel.python.examples.psro_v2_example.init_pg_responder(), and open_spiel.python.examples.psro_v2_example.print_policy_analysis().
Referenced by open_spiel.python.examples.psro_v2_example.gpsro_looper().
init_br_responder()
open_spiel.python.examples.psro_v2_example.init_br_responder (env)
Initializes the tabular best-response based responder and agents.
Definition at line 159 of file psro_v2_example.py.
def init_br_responder(env):
  """Initializes the tabular best-response based responder and agents."""
  random_policy = policy.TabularPolicy(env.game)
  oracle = best_response_oracle.BestResponseOracle(
      game=env.game, policy=random_policy)
  agents = [random_policy.__copy__() for _ in range(FLAGS.n_players)]
  return oracle, agents
Referenced by open_spiel.python.examples.psro_v2_example.gpsro_looper().
init_dqn_responder()
open_spiel.python.examples.psro_v2_example.init_dqn_responder (sess, env)
Initializes the Policy Gradient-based responder and agents.
Definition at line 168 of file psro_v2_example.py.
def init_dqn_responder(sess, env):
  """Initializes the Policy Gradient-based responder and agents."""
  state_representation_size = env.observation_spec()["info_state"][0]
  num_actions = env.action_spec()["num_actions"]
  agent_class = rl_policy.DQNPolicy
  agent_kwargs = {
      "session": sess,
      "state_representation_size": state_representation_size,
      "num_actions": num_actions,
      "hidden_layers_sizes": [FLAGS.hidden_layer_size] * FLAGS.n_hidden_layers,
      "batch_size": FLAGS.batch_size,
      "learning_rate": FLAGS.dqn_learning_rate,
      "update_target_network_every": FLAGS.update_target_network_every,
      "learn_every": FLAGS.learn_every,
      "optimizer_str": FLAGS.optimizer_str
  }
  oracle = rl_oracle.RLOracle(
      env,
      agent_class,
      agent_kwargs,
      number_training_episodes=FLAGS.number_training_episodes,
      self_play_proportion=FLAGS.self_play_proportion,
      sigma=FLAGS.sigma)
  agents = [
      agent_class(  # pylint: disable=g-complex-comprehension
          env,
          player_id,
          **agent_kwargs)
      for player_id in range(FLAGS.n_players)
  ]
  for agent in agents:
    agent.freeze()
  return oracle, agents
Referenced by open_spiel.python.examples.psro_v2_example.gpsro_looper().
init_pg_responder()
open_spiel.python.examples.psro_v2_example.init_pg_responder (sess, env)
Initializes the Policy Gradient-based responder and agents.
Definition at line 118 of file psro_v2_example.py.
def init_pg_responder(sess, env):
  """Initializes the Policy Gradient-based responder and agents."""
  info_state_size = env.observation_spec()["info_state"][0]
  num_actions = env.action_spec()["num_actions"]
  agent_class = rl_policy.PGPolicy
  agent_kwargs = {
      "session": sess,
      "info_state_size": info_state_size,
      "num_actions": num_actions,
      "loss_str": FLAGS.loss_str,
      "loss_class": False,
      "hidden_layers_sizes": [FLAGS.hidden_layer_size] * FLAGS.n_hidden_layers,
      "batch_size": FLAGS.batch_size,
      "entropy_cost": FLAGS.entropy_cost,
      "critic_learning_rate": FLAGS.critic_learning_rate,
      "pi_learning_rate": FLAGS.pi_learning_rate,
      "num_critic_before_pi": FLAGS.num_q_before_pi,
      "optimizer_str": FLAGS.optimizer_str
  }
  oracle = rl_oracle.RLOracle(
      env,
      agent_class,
      agent_kwargs,
      number_training_episodes=FLAGS.number_training_episodes,
      self_play_proportion=FLAGS.self_play_proportion,
      sigma=FLAGS.sigma)
  agents = [
      agent_class(  # pylint: disable=g-complex-comprehension
          env,
          player_id,
          **agent_kwargs)
      for player_id in range(FLAGS.n_players)
  ]
  for agent in agents:
    agent.freeze()
  return oracle, agents
Referenced by open_spiel.python.examples.psro_v2_example.gpsro_looper().
main()
open_spiel.python.examples.psro_v2_example.main (argv)
Definition at line 292 of file psro_v2_example.py.
def main(argv):
  if len(argv) > 1:
    raise app.UsageError("Too many command-line arguments.")
  np.random.seed(FLAGS.seed)
  game = pyspiel.load_game_as_turn_based(FLAGS.game_name,
                                         {"players": FLAGS.n_players})
  env = rl_environment.Environment(game)
  # Initialize oracle and agents
  with tf.Session() as sess:
    if FLAGS.oracle_type == "DQN":
      oracle, agents = init_dqn_responder(sess, env)
    elif FLAGS.oracle_type == "PG":
      oracle, agents = init_pg_responder(sess, env)
    elif FLAGS.oracle_type == "BR":
      oracle, agents = init_br_responder(env)
    sess.run(tf.global_variables_initializer())
    gpsro_looper(env, oracle, agents)
print_policy_analysis()
open_spiel.python.examples.psro_v2_example.print_policy_analysis (policies, game, verbose = False)
Function printing policy diversity within game's known policies.
Warning : only works with deterministic policies.
Args:
  policies: List of list of policies (One list per game player)
  game: OpenSpiel game object.
  verbose: Whether to print policy diversity information. (True : print)
Returns:
  List of list of unique policies (One list per player)
Definition at line 205 of file psro_v2_example.py.
def print_policy_analysis(policies, game, verbose=False):
  """Function printing policy diversity within game's known policies.
  Warning : only works with deterministic policies.
  Args:
    policies: List of list of policies (One list per game player)
    game: OpenSpiel game object.
    verbose: Whether to print policy diversity information. (True : print)
  Returns:
    List of list of unique policies (One list per player)
  """
  states_dict = get_all_states.get_all_states(game, np.infty, False, False)
  unique_policies = []
  for player in range(len(policies)):
    cur_policies = policies[player]
    cur_set = set()
    for pol in cur_policies:
      cur_str = ""
      for state_str in states_dict:
        if states_dict[state_str].current_player() == player:
          pol_action_dict = pol(states_dict[state_str])
          max_prob = max(list(pol_action_dict.values()))
          max_prob_actions = [
              a for a in pol_action_dict if pol_action_dict[a] == max_prob
          ]
          cur_str += "__" + state_str
          for a in max_prob_actions:
            cur_str += "-" + str(a)
      cur_set.add(cur_str)
    unique_policies.append(cur_set)
  if verbose:
    print("\n=====================================\nPolicy Diversity :")
    for player, cur_set in enumerate(unique_policies):
      print("Player {} : {} unique policies.".format(player, len(cur_set)))
  print("")
  return unique_policies
Referenced by open_spiel.python.examples.psro_v2_example.gpsro_looper().
Variable Documentation
FLAGS
open_spiel.python.examples.psro_v2_example.FLAGS = flags.FLAGS
Definition at line 51 of file psro_v2_example.py.