open spiel: absl::zipf_distribution< IntType > Class Template Reference
absl::zipf_distribution< IntType > Class Template Reference
Classes
class param_type
Public Types
using result_type = IntType
Public Member Functions
zipf_distribution (result_type k, double q=2.0, double v=1.0)
zipf_distribution (const param_type &p)
void reset ()
template<typename URBG >
result_type operator() (URBG &g)
template<typename URBG >
result_type operator() (URBG &g, const param_type &p)
result_type k () const
double q () const
double v () const
param_type param () const
void param (const param_type &p)
result_type min () const
result_type max () const
Friends
bool operator== (const zipf_distribution &a, const zipf_distribution &b)
bool operator!= (const zipf_distribution &a, const zipf_distribution &b)
Detailed Description
template<typename IntType = int>
class absl::zipf_distribution< IntType >
Definition at line 52 of file zipf_distribution.h.
Member Typedef Documentation
result_type
template<typename IntType = int> using absl::zipf_distribution< IntType >::result_type = IntType
Definition at line 54 of file zipf_distribution.h.
Constructor & Destructor Documentation
zipf_distribution() [1/3]
template<typename IntType = int> absl::zipf_distribution< IntType >::zipf_distribution () inline
Definition at line 103 of file zipf_distribution.h.
      : zipf_distribution((std::numeric_limits<IntType>::max)()) {}
zipf_distribution() [2/3]
template<typename IntType = int> absl::zipf_distribution< IntType >::zipf_distribution (result_type k, double q = 2.0, double v = 1.0) inline explicit
Definition at line 106 of file zipf_distribution.h.
      : param_(k, q, v) {}
zipf_distribution() [3/3]
template<typename IntType = int> absl::zipf_distribution< IntType >::zipf_distribution (const param_type & p) inline explicit
Definition at line 109 of file zipf_distribution.h.
: param_(p) {}
Member Function Documentation
k()
template<typename IntType = int> result_type absl::zipf_distribution< IntType >::k () const inline
Definition at line 122 of file zipf_distribution.h.
{ return param_.k(); }
max()
template<typename IntType = int> result_type absl::zipf_distribution< IntType >::max () const inline
Definition at line 130 of file zipf_distribution.h.
{ return k(); }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
template<typename IntType = int> result_type absl::zipf_distribution< IntType >::min () const inline
Definition at line 129 of file zipf_distribution.h.
{ return 0; }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
operator()() [1/2]
template<typename IntType = int> template<typename URBG > result_type absl::zipf_distribution< IntType >::operator() (URBG & g) inline
Definition at line 114 of file zipf_distribution.h.
                                  {  // NOLINT(runtime/references)
    return (*this)(g, param_);
  }
operator()() [2/2]
template<typename IntType > template<typename URBG > zipf_distribution< IntType >::result_type absl::zipf_distribution< IntType >::operator() (URBG & g, const param_type & p)
Definition at line 216 of file zipf_distribution.h.
                                  {  // NOLINT(runtime/references)
  absl::uniform_real_distribution<double> uniform_double;
  double k;
  for (;;) {
    const double v = uniform_double(g);
    const double u = p.hxm_ + v * p.hx0_minus_hxm_;
    const double x = p.hinv(u);
    k = rint(x);              // std::floor(x + 0.5);
    if (k > static_cast<double>(p.k())) continue;  // reject k > max_k
    if (k - x <= p.s_) break;
    const double h = p.h(k + 0.5);
    const double r = p.pow_negative_q(p.v_ + k);
    if (u >= h - r) break;
  }
  IntType ki = static_cast<IntType>(k);
  assert(ki <= p.k_);
  return ki;
}
param() [1/2]
template<typename IntType = int> param_type absl::zipf_distribution< IntType >::param () const inline
Definition at line 126 of file zipf_distribution.h.
{ return param_; }
param() [2/2]
template<typename IntType = int> void absl::zipf_distribution< IntType >::param (const param_type & p) inline
Definition at line 127 of file zipf_distribution.h.
{ param_ = p; }
q()
template<typename IntType = int> double absl::zipf_distribution< IntType >::q () const inline
Definition at line 123 of file zipf_distribution.h.
{ return param_.q(); }
reset()
template<typename IntType = int> void absl::zipf_distribution< IntType >::reset () inline
Definition at line 111 of file zipf_distribution.h.
{}
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear::__init__(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), open_spiel.python.rl_environment.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
v()
template<typename IntType = int> double absl::zipf_distribution< IntType >::v () const inline
Definition at line 124 of file zipf_distribution.h.
{ return param_.v(); }
Friends And Related Symbol Documentation
operator!=
template<typename IntType = int> bool operator!= (const zipf_distribution< IntType > & a, const zipf_distribution< IntType > & b) friend
Definition at line 136 of file zipf_distribution.h.
{
    return a.param_ != b.param_;
  }
operator==
template<typename IntType = int> bool operator== (const zipf_distribution< IntType > & a, const zipf_distribution< IntType > & b) friend
Definition at line 132 of file zipf_distribution.h.
{
    return a.param_ == b.param_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/zipf_distribution.h