open spiel: open_spiel.python.algorithms.regret_matching Namespace Reference
open_spiel.python.algorithms.regret_matching Namespace Reference
Functions
_partial_multi_dot (player_payoff_tensor, strategies, index_avoided)
_regret_matching_step (payoff_tensors, strategies, regrets, gamma)
regret_matching (payoff_tensors, initial_strategies=None, iterations=int(1e5), gamma=1e-6, average_over_last_n_strategies=None, **unused_kwargs)
Variables
int INITIAL_REGRET_DENOM = 1e6
Detailed Description
Regret-Matching Algorithm.
This is an N-player implementation of the regret-matching algorithm described in
Hart & Mas-Colell 2000:
https://onlinelibrary.wiley.com/doi/abs/10.1111/1468-0262.00153
Function Documentation
_partial_multi_dot()
open_spiel.python.algorithms.regret_matching._partial_multi_dot (player_payoff_tensor, strategies, index_avoided) protected
Computes a generalized dot product avoiding one dimension.
This is used to directly get the expected return of a given action, given
other players' strategies, for the player indexed by index_avoided.
Note that the numpy.dot function is used to compute this product, as it ended
up being (Slightly) faster in performance tests than np.tensordot. Using the
reduce function proved slower for both np.dot and np.tensordot.
Args:
  player_payoff_tensor: payoff tensor for player[index_avoided], of dimension
    (dim(vector[0]), dim(vector[1]), ..., dim(vector[-1])).
  strategies: Meta strategy probabilities for each player.
  index_avoided: Player for which we do not compute the dot product.
Returns:
  Vector of expected returns for each action of player [the player indexed by
    index_avoided].
Definition at line 29 of file regret_matching.py.
def _partial_multi_dot(player_payoff_tensor, strategies, index_avoided):
  """Computes a generalized dot product avoiding one dimension.
  This is used to directly get the expected return of a given action, given
  other players' strategies, for the player indexed by index_avoided.
  Note that the numpy.dot function is used to compute this product, as it ended
  up being (Slightly) faster in performance tests than np.tensordot. Using the
  reduce function proved slower for both np.dot and np.tensordot.
  Args:
    player_payoff_tensor: payoff tensor for player[index_avoided], of dimension
      (dim(vector[0]), dim(vector[1]), ..., dim(vector[-1])).
    strategies: Meta strategy probabilities for each player.
    index_avoided: Player for which we do not compute the dot product.
  Returns:
    Vector of expected returns for each action of player [the player indexed by
      index_avoided].
  """
  new_axis_order = [index_avoided] + [
      i for i in range(len(strategies)) if (i != index_avoided)
  ]
  accumulator = np.transpose(player_payoff_tensor, new_axis_order)
  for i in range(len(strategies) - 1, -1, -1):
    if i != index_avoided:
      accumulator = np.dot(accumulator, strategies[i])
  return accumulator
Referenced by open_spiel.python.algorithms.regret_matching._regret_matching_step().
_regret_matching_step()
open_spiel.python.algorithms.regret_matching._regret_matching_step (payoff_tensors, strategies, regrets, gamma) protected
Does one step of the projected replicator dynamics algorithm.
Args:
  payoff_tensors: List of payoff tensors for each player.
  strategies: List of the strategies used by each player.
  regrets: List of cumulative regrets used by each player.
  gamma: Minimum exploratory probability term.
Returns:
  A list of updated strategies for each player.
Definition at line 58 of file regret_matching.py.
def _regret_matching_step(payoff_tensors, strategies, regrets, gamma):
  """Does one step of the projected replicator dynamics algorithm.
  Args:
    payoff_tensors: List of payoff tensors for each player.
    strategies: List of the strategies used by each player.
    regrets: List of cumulative regrets used by each player.
    gamma: Minimum exploratory probability term.
  Returns:
    A list of updated strategies for each player.
  """
  # TODO(author4): Investigate whether this update could be fully vectorized.
  new_strategies = []
  for player in range(len(payoff_tensors)):
    current_payoff_tensor = payoff_tensors[player]
    current_strategy = strategies[player]
    values_per_strategy = _partial_multi_dot(current_payoff_tensor, strategies,
                                             player)
    average_return = np.dot(values_per_strategy, current_strategy)
    regrets[player] += values_per_strategy - average_return
    updated_strategy = regrets[player].copy()
    updated_strategy[updated_strategy < 0] = 0.0
    sum_regret = updated_strategy.sum()
    uniform_strategy = np.ones(len(updated_strategy)) / len(updated_strategy)
    if sum_regret > 0:
      updated_strategy /= sum_regret
      updated_strategy = gamma * uniform_strategy + (1 -
                                                     gamma) * updated_strategy
    else:
      updated_strategy = uniform_strategy
    new_strategies.append(updated_strategy)
  return new_strategies
References open_spiel.python.algorithms.regret_matching._partial_multi_dot().
Referenced by open_spiel.python.algorithms.regret_matching.regret_matching().
regret_matching()
open_spiel.python.algorithms.regret_matching.regret_matching (payoff_tensors, initial_strategies = None, iterations = int(1e5), gamma = 1e-6, average_over_last_n_strategies = None, ** unused_kwargs)
Runs regret-matching for the stated number of iterations.
Args:
  payoff_tensors: List of payoff tensors for each player.
  initial_strategies: Initial list of the strategies used by each player, if
    any. Could be used to speed up the search by providing a good initial
    solution.
  iterations: Number of algorithmic steps to take before returning an answer.
  gamma: Minimum exploratory probability term.
  average_over_last_n_strategies: Running average window size for average
    policy computation. If None, use the whole trajectory.
  **unused_kwargs: Convenient way of exposing an API compatible with other
    methods with possibly different arguments.
Returns:
  RM-computed strategies.
Definition at line 98 of file regret_matching.py.
                    **unused_kwargs):
  """Runs regret-matching for the stated number of iterations.
  Args:
    payoff_tensors: List of payoff tensors for each player.
    initial_strategies: Initial list of the strategies used by each player, if
      any. Could be used to speed up the search by providing a good initial
      solution.
    iterations: Number of algorithmic steps to take before returning an answer.
    gamma: Minimum exploratory probability term.
    average_over_last_n_strategies: Running average window size for average
      policy computation. If None, use the whole trajectory.
    **unused_kwargs: Convenient way of exposing an API compatible with other
      methods with possibly different arguments.
  Returns:
    RM-computed strategies.
  """
  number_players = len(payoff_tensors)
  # Number of actions available to each player.
  action_space_shapes = payoff_tensors[0].shape
  # If no initial starting position is given, start with uniform probabilities.
  new_strategies = initial_strategies or [
      np.ones(action_space_shapes[k]) / action_space_shapes[k]
      for k in range(number_players)
  ]
  regrets = [
      np.ones(action_space_shapes[k]) / INITIAL_REGRET_DENOM
      for k in range(number_players)
  ]
  averager = nfg_utils.StrategyAverager(number_players, action_space_shapes,
                                        average_over_last_n_strategies)
  averager.append(new_strategies)
  for _ in range(iterations):
    new_strategies = _regret_matching_step(payoff_tensors, new_strategies,
                                           regrets, gamma)
    averager.append(new_strategies)
  return averager.average_strategies()
References open_spiel.python.algorithms.regret_matching._regret_matching_step().
Variable Documentation
INITIAL_REGRET_DENOM
int open_spiel.python.algorithms.regret_matching.INITIAL_REGRET_DENOM = 1e6
Definition at line 26 of file regret_matching.py.