open spiel: absl::random_internal::sequence_urbg Class Reference
absl::random_internal::sequence_urbg Class Reference
Public Types
using result_type = uint64_t
Public Member Functions
sequence_urbg (std::initializer_list< result_type > data)
void reset ()
result_type operator() ()
size_t invocations () const
Static Public Member Functions
static constexpr result_type min ()
static constexpr result_type max ()
Detailed Description
Definition at line 33 of file sequence_urbg.h.
Member Typedef Documentation
result_type
using absl::random_internal::sequence_urbg::result_type = uint64_t
Definition at line 35 of file sequence_urbg.h.
Constructor & Destructor Documentation
sequence_urbg()
absl::random_internal::sequence_urbg::sequence_urbg (std::initializer_list< result_type > data) inline
Definition at line 44 of file sequence_urbg.h.
: i_(0), data_(data) {}
Member Function Documentation
invocations()
size_t absl::random_internal::sequence_urbg::invocations () const inline
Definition at line 49 of file sequence_urbg.h.
{ return i_; }
max()
static constexpr result_type absl::random_internal::sequence_urbg::max () inline static constexpr
Definition at line 40 of file sequence_urbg.h.
{
    return (std::numeric_limits<result_type>::max)();
  }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
static constexpr result_type absl::random_internal::sequence_urbg::min () inline static constexpr
Definition at line 37 of file sequence_urbg.h.
{
    return (std::numeric_limits<result_type>::min)();
  }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
operator()()
result_type absl::random_internal::sequence_urbg::operator() () inline
Definition at line 47 of file sequence_urbg.h.
{ return data_[i_++ % data_.size()]; }
reset()
void absl::random_internal::sequence_urbg::reset () inline
Definition at line 45 of file sequence_urbg.h.
{ i_ = 0; }
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear::__init__(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), open_spiel.python.rl_environment.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/internal/sequence_urbg.h