open spiel: open_spiel.python.examples.matrix_game_example Namespace Reference
open_spiel.python.examples.matrix_game_example Namespace Reference
Functions
_manually_create_game ()
_easy_create_game ()
_even_easier_create_game ()
_import_data_create_game ()
main (_)
Detailed Description
Python spiel example.
Function Documentation
_easy_create_game()
open_spiel.python.examples.matrix_game_example._easy_create_game () protected
Uses the helper function to create the same game as above.
Definition at line 55 of file matrix_game_example.py.
def _easy_create_game():
  """Uses the helper function to create the same game as above."""
  return pyspiel.create_matrix_game("matching_pennies", "Matching Pennies",
                                    ["Heads", "Tails"], ["Heads", "Tails"],
                                    [[-1, 1], [1, -1]], [[1, -1], [-1, 1]])
Referenced by open_spiel.python.examples.matrix_game_example._import_data_create_game().
_even_easier_create_game()
open_spiel.python.examples.matrix_game_example._even_easier_create_game () protected
Leave out the names too, if you prefer.
Definition at line 62 of file matrix_game_example.py.
def _even_easier_create_game():
  """Leave out the names too, if you prefer."""
  return pyspiel.create_matrix_game([[-1, 1], [1, -1]], [[1, -1], [-1, 1]])
Referenced by open_spiel.python.examples.matrix_game_example._import_data_create_game().
_import_data_create_game()
open_spiel.python.examples.matrix_game_example._import_data_create_game () protected
Creates a game via imported payoff data.
Definition at line 67 of file matrix_game_example.py.
def _import_data_create_game():
  """Creates a game via imported payoff data."""
  payoff_file = file_utils.find_file(
      "open_spiel/data/paper_data/response_graph_ucb/soccer.txt", 2)
  payoffs = np.loadtxt(payoff_file)*2-1
  return pyspiel.create_matrix_game(payoffs, payoffs.T)
References open_spiel.python.examples.matrix_game_example._easy_create_game(), open_spiel.python.examples.matrix_game_example._even_easier_create_game(), open_spiel.python.examples.matrix_game_example._import_data_create_game(), and open_spiel.python.examples.matrix_game_example._manually_create_game().
Referenced by open_spiel.python.examples.matrix_game_example._import_data_create_game().
_manually_create_game()
open_spiel.python.examples.matrix_game_example._manually_create_game () protected
Creates the game manually from the spiel building blocks.
Definition at line 26 of file matrix_game_example.py.
def _manually_create_game():
  """Creates the game manually from the spiel building blocks."""
  game_type = pyspiel.GameType(
      "matching_pennies",
      "Matching Pennies",
      pyspiel.GameType.Dynamics.SIMULTANEOUS,
      pyspiel.GameType.ChanceMode.DETERMINISTIC,
      pyspiel.GameType.Information.ONE_SHOT,
      pyspiel.GameType.Utility.ZERO_SUM,
      pyspiel.GameType.RewardModel.TERMINAL,
      2,  # max num players
      2,  # min_num_players
      True,  # provides_information_state
      True,  # provides_information_state_tensor
      False,  # provides_observation
      False,  # provides_observation_tensor
      dict()  # parameter_specification
  )
  game = pyspiel.MatrixGame(
      game_type,
      {},  # game_parameters
      ["Heads", "Tails"],  # row_action_names
      ["Heads", "Tails"],  # col_action_names
      [[-1, 1], [1, -1]],  # row player utilities
      [[1, -1], [-1, 1]]  # col player utilities
  )
  return game
Referenced by open_spiel.python.examples.matrix_game_example._import_data_create_game().
main()
open_spiel.python.examples.matrix_game_example.main (_)
Definition at line 75 of file matrix_game_example.py.
def main(_):
  games_list = pyspiel.registered_games()
  print("Registered games:")
  print(games_list)
  # Load a two-player normal-form game as a two-player matrix game.
  blotto_matrix_game = pyspiel.load_matrix_game("blotto")
  print("Number of rows in 2-player Blotto with default settings is {}".format(
      blotto_matrix_game.num_rows()))
  # Several ways to load/create the same game of matching pennies.
  print("Creating matrix game...")
  game = pyspiel.load_matrix_game("matrix_mp")
  game = _manually_create_game()
  game = _import_data_create_game()
  game = _easy_create_game()
  game = _even_easier_create_game()
  # Quick test: inspect top-left utility values:
  print("Values for joint action ({},{}) is {},{}".format(
      game.row_action_name(0), game.col_action_name(0),
      game.player_utility(0, 0, 0), game.player_utility(1, 0, 0)))
  state = game.new_initial_state()
  # Print the initial state
  print("State:")
  print(str(state))
  assert state.is_simultaneous_node()
  # Simultaneous node: sample actions for all players.
  chosen_actions = [
      random.choice(state.legal_actions(pid))
      for pid in range(game.num_players())
  ]
  print("Chosen actions: ", [
      state.action_to_string(pid, action)
      for pid, action in enumerate(chosen_actions)
  ])
  state.apply_actions(chosen_actions)
  assert state.is_terminal()
  # Game is now done. Print utilities for each player
  returns = state.returns()
  for pid in range(game.num_players()):
    print("Utility for player {} is {}".format(pid, returns[pid]))