open spiel: absl::bernoulli_distribution::param_type Class Reference
absl::bernoulli_distribution::param_type Class Reference
Public Types
using distribution_type = bernoulli_distribution
Public Member Functions
param_type (double p=0.5)
double p () const
Friends
bool operator== (const param_type &p1, const param_type &p2)
bool operator!= (const param_type &p1, const param_type &p2)
Detailed Description
Definition at line 39 of file bernoulli_distribution.h.
Member Typedef Documentation
distribution_type
using absl::bernoulli_distribution::param_type::distribution_type = bernoulli_distribution
Definition at line 41 of file bernoulli_distribution.h.
Constructor & Destructor Documentation
param_type()
absl::bernoulli_distribution::param_type::param_type (double p = 0.5) inline explicit
Definition at line 43 of file bernoulli_distribution.h.
                                        : prob_(p) {
      assert(p >= 0.0 && p <= 1.0);
    }
Member Function Documentation
p()
double absl::bernoulli_distribution::param_type::p () const inline
Definition at line 47 of file bernoulli_distribution.h.
{ return prob_; }
Referenced by open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::cheap_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::gradients(), and open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::gradients().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const param_type & p1, const param_type & p2) friend
Definition at line 52 of file bernoulli_distribution.h.
{
      return p1.p() != p2.p();
    }
operator==
bool operator== (const param_type & p1, const param_type & p2) friend
Definition at line 49 of file bernoulli_distribution.h.
{
      return p1.p() == p2.p();
    }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/bernoulli_distribution.h