open spiel: open_spiel.python.voting.base.AbstractVotingMethod Class Reference
open_spiel.python.voting.base.AbstractVotingMethod Class Reference
Public Member Functions
__init__ (self, **method_specific_kwargs)
str name (self)
RankOutcome run_election (self, PreferenceProfile profile)
bool is_valid_profile (self, PreferenceProfile profile)
Detailed Description
Abstract base class for voting methods.
Definition at line 457 of file base.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.voting.base.AbstractVotingMethod.__init__ (self, ** method_specific_kwargs)
Initializes the voting method.
Args:
  **method_specific_kwargs: optional extra args.
Reimplemented in open_spiel.python.voting.approval.ApprovalVoting, open_spiel.python.voting.borda.BordaVoting, open_spiel.python.voting.copeland.CopelandVoting, open_spiel.python.voting.kemeny_young.KemenyYoungVoting, open_spiel.python.voting.maximal_lotteries.MaximalLotteriesVoting, open_spiel.python.voting.plurality.PluralityVoting, open_spiel.python.voting.ranked_pairs.RankedPairsVoting, open_spiel.python.voting.schulze.SchulzeVoting, and open_spiel.python.voting.stv.STVVoting.
Definition at line 461 of file base.py.
  def __init__(self, **method_specific_kwargs):
    """Initializes the voting method.
    Args:
      **method_specific_kwargs: optional extra args.
    """
Member Function Documentation
is_valid_profile()
bool open_spiel.python.voting.base.AbstractVotingMethod.is_valid_profile (self, PreferenceProfile profile)
Returns true if a profile is valid.
A valid profile is valid if it contains at least one vote and one
alternative. Most voting schemes can't run unless the profile is valid.
Args:
  profile: the profile to check.
Definition at line 483 of file base.py.
  def is_valid_profile(self, profile: PreferenceProfile) -> bool:
    """Returns true if a profile is valid.
    A valid profile is valid if it contains at least one vote and one
    alternative. Most voting schemes can't run unless the profile is valid.
    Args:
      profile: the profile to check.
    """
    return profile.num_votes() > 0 and profile.num_alternatives() > 0
Referenced by open_spiel.python.voting.approval.ApprovalVoting.run_election(), open_spiel.python.voting.borda.BordaVoting.run_election(), open_spiel.python.voting.copeland.CopelandVoting.run_election(), open_spiel.python.voting.kemeny_young.KemenyYoungVoting.run_election(), open_spiel.python.voting.plurality.PluralityVoting.run_election(), open_spiel.python.voting.ranked_pairs.RankedPairsVoting.run_election(), open_spiel.python.voting.schulze.SchulzeVoting.run_election(), and open_spiel.python.voting.stv.STVVoting.run_election().
name()
str open_spiel.python.voting.base.AbstractVotingMethod.name (self)
Returns the name of the voting method.
Reimplemented in open_spiel.python.voting.approval.ApprovalVoting, open_spiel.python.voting.borda.BordaVoting, open_spiel.python.voting.copeland.CopelandVoting, open_spiel.python.voting.kemeny_young.KemenyYoungVoting, open_spiel.python.voting.maximal_lotteries.MaximalLotteriesVoting, open_spiel.python.voting.plurality.PluralityVoting, open_spiel.python.voting.ranked_pairs.RankedPairsVoting, open_spiel.python.voting.schulze.SchulzeVoting, and open_spiel.python.voting.stv.STVVoting.
Definition at line 469 of file base.py.
  def name(self) -> str:
    """Returns the name of the voting method."""
run_election()
RankOutcome open_spiel.python.voting.base.AbstractVotingMethod.run_election (self, PreferenceProfile profile)
Runs the election and returns the result.
Args:
    profile: a preference profile.
Returns:
    a RankOutcome object that can be queried for the results.
Reimplemented in open_spiel.python.voting.approval.ApprovalVoting, open_spiel.python.voting.borda.BordaVoting, open_spiel.python.voting.copeland.CopelandVoting, open_spiel.python.voting.kemeny_young.KemenyYoungVoting, open_spiel.python.voting.maximal_lotteries.MaximalLotteriesVoting, open_spiel.python.voting.plurality.PluralityVoting, open_spiel.python.voting.ranked_pairs.RankedPairsVoting, open_spiel.python.voting.schulze.SchulzeVoting, and open_spiel.python.voting.stv.STVVoting.
Definition at line 473 of file base.py.
  def run_election(self, profile: PreferenceProfile) -> RankOutcome:
    """Runs the election and returns the result.
    Args:
        profile: a preference profile.
    Returns:
        a RankOutcome object that can be queried for the results.
    """
The documentation for this class was generated from the following file:
open_spiel/python/voting/base.py