open spiel: open_spiel::algorithms::torch_dqn::DQN Class Reference
open_spiel::algorithms::torch_dqn::DQN Class Reference
Public Member Functions
DQN (const DQNSettings &settings)
Action Step (const State &state, bool is_evaluation=false) override
double GetEpsilon (bool is_evaluation, int power=1.0)
int seed () const
void Load (const std::string &data_path, const std::string &optimizer_data_path="")
void Save (const std::string &data_path, const std::string &optimizer_data_path="")
Detailed Description
Definition at line 96 of file dqn.h.
Constructor & Destructor Documentation
DQN()
open_spiel::algorithms::torch_dqn::DQN::DQN (const DQNSettings & settings)
Definition at line 47 of file dqn.cc.
    : seed_(settings.seed),
      use_observation_(settings.use_observation),
      player_id_(settings.player_id),
      input_size_(settings.state_representation_size),
      num_actions_(settings.num_actions),
      hidden_layers_sizes_(settings.hidden_layers_sizes),
      batch_size_(settings.batch_size),
      update_target_network_every_(settings.update_target_network_every),
      learn_every_(settings.learn_every),
      min_buffer_size_to_learn_(settings.min_buffer_size_to_learn),
      discount_factor_(settings.discount_factor),
      epsilon_start_(settings.epsilon_start),
      epsilon_end_(settings.epsilon_end),
      epsilon_decay_duration_(settings.epsilon_decay_duration),
      replay_buffer_(settings.replay_buffer_capacity),
      q_network_(input_size_, hidden_layers_sizes_, num_actions_),
      target_q_network_(input_size_, hidden_layers_sizes_, num_actions_),
      optimizer_(q_network_->parameters(),
                 torch::optim::SGDOptions(settings.learning_rate)),
      loss_str_(settings.loss_str),
      exists_prev_(false),
      prev_state_(nullptr),
      prev_action_(0),
      step_counter_(0),
      rng_(settings.seed) {}
Member Function Documentation
GetEpsilon()
double open_spiel::algorithms::torch_dqn::DQN::GetEpsilon (bool is_evaluation, int power = 1.0)
Definition at line 181 of file dqn.cc.
{
  if (is_evaluation) {
    return 0.0;
  }
  double decay_steps = std::min(
      static_cast<double>(step_counter_), epsilon_decay_duration_);
  double decayed_epsilon = (
    epsilon_end_ + (epsilon_start_ - epsilon_end_) *
    std::pow((1 - decay_steps / epsilon_decay_duration_), power));
  return decayed_epsilon;
}
Load()
void open_spiel::algorithms::torch_dqn::DQN::Load (const std::string & data_path, const std::string & optimizer_data_path = "")
Definition at line 275 of file dqn.cc.
{
  torch::load(q_network_, data_path);
  torch::load(target_q_network_, data_path);
  if (!optimizer_data_path.empty()) {
    torch::load(optimizer_, optimizer_data_path);
  }
}
Save()
void open_spiel::algorithms::torch_dqn::DQN::Save (const std::string & data_path, const std::string & optimizer_data_path = "")
Definition at line 284 of file dqn.cc.
{
  torch::save(q_network_, data_path);
  if (!optimizer_data_path.empty()) {
    torch::save(optimizer_, optimizer_data_path);
  }
}
seed()
int open_spiel::algorithms::torch_dqn::DQN::seed () const inline
Definition at line 103 of file dqn.h.
{ return seed_; }
Referenced by open_spiel.python.algorithms.adidas_utils.games.big.TensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::__init__(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.small.MatrixGame::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.nonsymmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.symmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal_noaux.Solver::__init__(), and open_spiel.python.algorithms.adidas_utils.solvers.symmetric.regmatch.Solver::__init__().
Step()
Action open_spiel::algorithms::torch_dqn::DQN::Step (const State & state, bool is_evaluation = false) override virtual
Implements open_spiel::algorithms::torch_dqn::Agent.
Definition at line 84 of file dqn.cc.
{
  // Chance nodes should be handled externally to the agent.
  SPIEL_CHECK_TRUE(!state.IsChanceNode());
  Action action;
  if (!state.IsTerminal() &&
      (state.CurrentPlayer() == player_id_ || state.IsSimultaneousNode())) {
    std::vector<float> info_state = GetInfoState(state,
                                                 player_id_,
                                                 use_observation_);
    std::vector<Action> legal_actions = state.LegalActions(player_id_);
    double epsilon = GetEpsilon(is_evaluation);
    action = EpsilonGreedy(info_state, legal_actions, epsilon);
  } else {
    action = 0;
  }
  if (!is_evaluation) {
    step_counter_++;
    if (step_counter_ % learn_every_ == 0) {
      Learn();
    }
    if (step_counter_ % update_target_network_every_ == 0) {
      std::stringstream stream;
      torch::save(q_network_, stream);
      torch::load(target_q_network_, stream);
    }
    if (exists_prev_) {
      AddTransition(*prev_state_, prev_action_, state);
    }
  }
  if (state.IsTerminal()) {
    exists_prev_ = false;
    prev_action_ = 0;
    prev_state_ = nullptr;
    return kInvalidAction;
  } else {
    exists_prev_ = true;
    prev_state_ = state.Clone();
    prev_action_ = action;
  }
  return action;
}
The documentation for this class was generated from the following files:
open_spiel/algorithms/dqn_torch/dqn.h
open_spiel/algorithms/dqn_torch/dqn.cc