open spiel: open_spiel::SpanTensorInfo Class Reference
open_spiel::SpanTensorInfo Class Reference
Public Types
using Shape = absl::InlinedVector<int, 4>
Public Member Functions
SpanTensorInfo (absl::string_view name, const Shape &shape)
const std::string & name () const
const Shape & shape () const
template<typename int_type = int32_t>
std::vector< int_type > vector_shape () const
int32_t size () const
int32_t nbytes () const
std::string DebugString () const
Detailed Description
Definition at line 68 of file observer.h.
Member Typedef Documentation
Shape
using open_spiel::SpanTensorInfo::Shape = absl::InlinedVector<int, 4>
Definition at line 70 of file observer.h.
Constructor & Destructor Documentation
SpanTensorInfo()
open_spiel::SpanTensorInfo::SpanTensorInfo (absl::string_view name, const Shape & shape) inline
Definition at line 72 of file observer.h.
      : name_(name), shape_(shape) {}
Member Function Documentation
DebugString()
std::string open_spiel::SpanTensorInfo::DebugString () const inline
Definition at line 93 of file observer.h.
{
    return absl::StrCat("SpanTensor(name='", name(), "', shape=(",
                        absl::StrJoin(shape_, ","), "), nbytes=", nbytes(),
                        ")");
  }
name()
const std::string & open_spiel::SpanTensorInfo::name () const inline
Definition at line 75 of file observer.h.
{ return name_; }
nbytes()
int32_t open_spiel::SpanTensorInfo::nbytes () const inline
Definition at line 91 of file observer.h.
{ return size() * sizeof(float); }
shape()
const Shape & open_spiel::SpanTensorInfo::shape () const inline
Definition at line 76 of file observer.h.
{ return shape_; }
size()
int32_t open_spiel::SpanTensorInfo::size () const inline
Definition at line 85 of file observer.h.
                       {
    return std::accumulate(shape_.begin(), shape_.end(), 1,
                           std::multiplies<int32_t>());
  }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::__init__(), open_spiel.python.mfg.games.crowd_avoidance.Observer::__init__(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::__init__(), open_spiel.python.mfg.games.crowd_modelling.Observer::__init__(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::__init__(), open_spiel.python.mfg.games.linear_quadratic.Observer::__init__(), open_spiel.python.mfg.games.normal_form_game.MFGNormalFormState::__init__(), open_spiel.python.mfg.games.normal_form_game.Observer::__init__(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::__init__(), open_spiel.python.mfg.games.periodic_aversion.Observer::__init__(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::__init__(), open_spiel.python.mfg.games.predator_prey.Observer::__init__(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), and open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos().
vector_shape()
template<typename int_type = int32_t> std::vector< int_type > open_spiel::SpanTensorInfo::vector_shape () const inline
Definition at line 80 of file observer.h.
{
    return {shape_.begin(), shape_.end()};
  }
The documentation for this class was generated from the following file:
open_spiel/observer.h