My Project: rnad.FineTuning Class Reference
rnad.FineTuning Class Reference
Public Member Functions
chex.Array __call__ (self, chex.Array policy, chex.Array mask, int learner_steps)
chex.Array post_process_policy (self, chex.Array policy, chex.Array mask)
Public Attributes
from_learner_steps
Static Public Attributes
int from_learner_steps = -1
float policy_threshold = 0.03
int policy_discretization = 32
Protected Member Functions
chex.Array _threshold (self, chex.Array policy, chex.Array mask)
chex.Array _discretize (self, chex.Array policy)
chex.Array _discretize_single (self, chex.Array mu)
Detailed Description
Fine tuning options, aka policy post-processing.
Even when fully trained, the resulting softmax-based policy may put
a small probability mass on bad actions. This results in an agent
waiting for the opponent (itself in self-play) to commit an error.
To address that the policy is post-processed using:
- thresholding: any action with probability smaller than self.threshold
  is simply removed from the policy.
- discretization: the probability values are rounded to the closest
  multiple of 1/self.discretization.
The post-processing is used on the learner, and thus must be jit-friendly.
Definition at line 135 of file rnad.py.
Member Function Documentation
__call__()
chex.Array rnad.FineTuning.__call__ (self, chex.Array policy, chex.Array mask, int learner_steps)
A configurable fine tuning of a policy.
Definition at line 162 of file rnad.py.
References rnad.FineTuning.from_learner_steps.
_discretize()
chex.Array rnad.FineTuning._discretize (self, chex.Array policy) protected
Round all action probabilities to a multiple of 1/self.discretize.
Definition at line 197 of file rnad.py.
References rnad.FineTuning._discretize_single(), and rnad.FineTuning.policy_discretization.
Referenced by rnad.FineTuning.post_process_policy().
_discretize_single()
chex.Array rnad.FineTuning._discretize_single (self, chex.Array mu) protected
A version of self._discretize but for the unbatched data.
Definition at line 217 of file rnad.py.
References rnad.FineTuning.policy_discretization.
Referenced by rnad.FineTuning._discretize().
_threshold()
chex.Array rnad.FineTuning._threshold (self, chex.Array policy, chex.Array mask) protected
Remove from the support the actions 'a' where policy(a) < threshold.
Definition at line 183 of file rnad.py.
References rnad.FineTuning.policy_threshold.
Referenced by rnad.FineTuning.post_process_policy().
post_process_policy()
chex.Array rnad.FineTuning.post_process_policy (self, chex.Array policy, chex.Array mask)
Unconditionally post process a given masked policy.
Definition at line 172 of file rnad.py.
References rnad.FineTuning._discretize(), and rnad.FineTuning._threshold().
Member Data Documentation
from_learner_steps [1/2]
int rnad.FineTuning.from_learner_steps = -1 static
Definition at line 153 of file rnad.py.
Referenced by rnad.FineTuning.__call__().
from_learner_steps [2/2]
rnad.FineTuning.from_learner_steps
Definition at line 167 of file rnad.py.
Referenced by rnad.FineTuning.__call__().
policy_discretization
int rnad.FineTuning.policy_discretization = 32 static
Definition at line 160 of file rnad.py.
Referenced by rnad.FineTuning._discretize(), and rnad.FineTuning._discretize_single().
policy_threshold
float rnad.FineTuning.policy_threshold = 0.03 static
Definition at line 156 of file rnad.py.
Referenced by rnad.FineTuning._threshold().
The documentation for this class was generated from the following file:
rnad.py