My Project: policy.UniformRandomPolicy Class Reference
policy.UniformRandomPolicy Class Reference
Public Member Functions
__init__ (self, game)
action_probabilities (self, state, player_id=None)
Public Member Functions inherited from policy.Policy
__init__ (self, game, player_ids)
action_probabilities (self, state, player_id=None)
__call__ (self, state, player_id=None)
to_tabular (self, states=None)
Additional Inherited Members
Public Attributes inherited from policy.Policy
game
player_ids
Detailed Description
Policy where the action distribution is uniform over all legal actions.
This is computed as needed, so can be used for games where a tabular policy
would be unfeasibly large, but incurs a legal action computation every time.
Definition at line 400 of file policy.py.
Constructor & Destructor Documentation
__init__()
policy.UniformRandomPolicy.__init__ (self, game)
Initializes a uniform random policy for all players in the game.
Reimplemented from policy.Policy.
Definition at line 407 of file policy.py.
References policy.UniformRandomPolicy.__init__().
Referenced by policy.UniformRandomPolicy.__init__().
Member Function Documentation
action_probabilities()
policy.UniformRandomPolicy.action_probabilities (self, state, player_id = None)
Returns a uniform random policy for a player in a state.
Args:
  state: A `pyspiel.State` object.
  player_id: Optional, the player id for which we want an action. Optional
    unless this is a simultaneous state at which multiple players can act.
Returns:
  A `dict` of `{action: probability}` for the specified player in the
  supplied state. This will contain all legal actions, each with the same
  probability, equal to 1 / num_legal_actions.
Reimplemented from policy.Policy.
Definition at line 412 of file policy.py.
Referenced by policy.Policy.__call__(), and policy.Policy.to_tabular().
The documentation for this class was generated from the following file:
policy.py