My Project: policy.FirstActionPolicy Class Reference
policy.FirstActionPolicy Class Reference
Public Member Functions
__init__ (self, game)
action_probabilities (self, state, player_id=None)
Public Member Functions inherited from policy.Policy
__init__ (self, game, player_ids)
action_probabilities (self, state, player_id=None)
__call__ (self, state, player_id=None)
to_tabular (self, states=None)
Additional Inherited Members
Public Attributes inherited from policy.Policy
game
player_ids
Detailed Description
A policy that always takes the lowest-numbered legal action.
Definition at line 434 of file policy.py.
Constructor & Destructor Documentation
__init__()
policy.FirstActionPolicy.__init__ (self, game)
Initializes a policy.
Args:
  game: the game for which this policy applies
  player_ids: list of player ids for which this policy applies; each should
    be in the range 0..game.num_players()-1.
Reimplemented from policy.Policy.
Definition at line 437 of file policy.py.
References policy.FirstActionPolicy.__init__().
Referenced by policy.FirstActionPolicy.__init__().
Member Function Documentation
action_probabilities()
policy.FirstActionPolicy.action_probabilities (self, state, player_id = None)
Returns a dictionary {action: prob} for all legal actions.
IMPORTANT: We assume the following properties hold:
- All probabilities are >=0 and sum to 1
- TLDR: Policy implementations should list the (action, prob) for all legal
  actions, but algorithms should not rely on this (yet).
  Details: Before May 2020, only legal actions were present in the mapping,
  but it did not have to be exhaustive: missing actions were considered to
  be associated to a zero probability.
  For example, a deterministic state-poliy was previously {action: 1.0}.
  Given this change of convention is new and hard to enforce, algorithms
  should not rely on the fact that all legal actions should be present.
Args:
  state: A `pyspiel.State` object.
  player_id: Optional, the player id for whom we want an action. Optional
    unless this is a simultaneous state at which multiple players can act.
Returns:
  A `dict` of `{action: probability}` for the specified player in the
  supplied state.
Reimplemented from policy.Policy.
Definition at line 441 of file policy.py.
Referenced by policy.Policy.__call__(), and policy.Policy.to_tabular().
The documentation for this class was generated from the following file:
policy.py