My Project: policy.TabularPolicy Class Reference
policy.TabularPolicy Class Reference
Public Member Functions
__init__ (self, game, players=None, to_string=lambda s:s.history_str(), states=None)
action_probabilities (self, state, player_id=None)
state_index (self, state)
policy_for_key (self, key)
to_dict (self)
__copy__ (self, copy_action_probability_array=True)
copy_with_noise (self, alpha=0.0, beta=0.0, random_state=np.random.RandomState())
Public Member Functions inherited from policy.Policy
__init__ (self, game, player_ids)
action_probabilities (self, state, player_id=None)
__call__ (self, state, player_id=None)
to_tabular (self, states=None)
Public Attributes
game_type
state_lookup
states_per_player
states
state_in
legal_actions_mask
action_probability_array
Public Attributes inherited from policy.Policy
game
player_ids
Protected Member Functions
_state_key (self, state, player)
Detailed Description
Policy implementation where the policy is in explicit tabular form.
In addition to implementing the `Policy` interface, this class exposes
details of the policy representation for easy manipulation.
The states are guaranteed to be grouped by player, which can simplify
code for users of this class, i.e. `action_probability_array` contains
states for player 0 first, followed by states for player 1, etc.
The policy uses `state.information_state_string` as the keys if available,
otherwise `state.observation_string`.
Usages:
- Set `policy(info_state, action)`:
```
tabular_policy = TabularPolicy(game)
info_state_str = state.information_state_string(<optional player>)
state_policy = tabular_policy.policy_for_key(info_state_str)
state_policy[action] = <value>
```
- Set `policy(info_state)`:
```
tabular_policy = TabularPolicy(game)
info_state_str = state.information_state_string(<optional player>)
state_policy = tabular_policy.policy_for_key(info_state_str)
state_policy[:] = <list or numpy.array>
```
Attributes:
  action_probability_array: array of shape `(num_states, num_actions)`, where
    `action_probability_array[s, a]` is the probability of choosing action `a`
    when at state `s`.
  state_lookup: `dict` mapping state key string to index into the
    `tabular_policy` array. If information state strings overlap, e.g. for
    different players or if the information state string has imperfect recall,
    then those states will be mapped to the same policy.
  legal_actions_mask: array of shape `(num_states, num_actions)`, each row
    representing which of the possible actions in the game are valid in this
    particular state, containing 1 for valid actions, 0 for invalid actions.
  states_per_player: A `list` per player of the state key strings at which
    they have a decision to make.
  states: A `list` of the states as ordered in the `action_probability_array`.
  state_in: array of shape `(num_states, state_vector_size)` containing the
    normalised vector representation of each information state. Populated only
    for games which support information_state_tensor(), and is None otherwise.
  game_type: The game attributes as returned by `Game::GetType`; used to
    determine whether to use information state or observation as the key in
    the tabular policy.
Definition at line 178 of file policy.py.
Constructor & Destructor Documentation
__init__()
policy.TabularPolicy.__init__ (self, game, players = None, to_string = lambda s: s.history_str(), states = None)
Initializes a uniform random policy for all players in the game.
Reimplemented from policy.Policy.
Definition at line 230 of file policy.py.
References policy.TabularPolicy.__init__().
Referenced by policy.TabularPolicy.__init__().
Member Function Documentation
__copy__()
policy.TabularPolicy.__copy__ (self, copy_action_probability_array = True)
Returns a shallow copy of self.
Most class attributes will be pointers to the copied object's attributes,
and therefore altering them could lead to unexpected behavioural changes.
Only action_probability_array is expected to be modified.
Args:
  copy_action_probability_array: Whether to also include
    action_probability_array in the copy operation.
Returns:
  Copy.
Definition at line 341 of file policy.py.
References policy.TabularPolicy.action_probability_array, policy.Policy.game, policy.TabularPolicy.game_type, policy.TabularPolicy.legal_actions_mask, policy.Policy.player_ids, policy.TabularPolicy.state_in, policy.TabularPolicy.state_lookup, policy.TabularPolicy.states, and policy.TabularPolicy.states_per_player.
Referenced by policy.TabularPolicy.copy_with_noise().
_state_key()
policy.TabularPolicy._state_key (self, state, player) protected
Returns the key to use to look up this (state, player) pair.
Definition at line 285 of file policy.py.
References policy.TabularPolicy.game_type.
Referenced by policy.TabularPolicy.action_probabilities(), and policy.TabularPolicy.state_index().
action_probabilities()
policy.TabularPolicy.action_probabilities (self, state, player_id = None)
Returns an {action: probability} dict, covering all legal actions.
Reimplemented from policy.Policy.
Definition at line 297 of file policy.py.
References policy.TabularPolicy._state_key(), and policy.TabularPolicy.policy_for_key().
Referenced by policy.Policy.__call__(), and policy.Policy.to_tabular().
copy_with_noise()
policy.TabularPolicy.copy_with_noise (self, alpha = 0.0, beta = 0.0, random_state = np.random.RandomState())
Returns a copy of this policy perturbed with noise.
Generates a new random distribution using a softmax on normal random
variables with temperature beta, and mixes it with the old distribution
using 1-alpha * old_distribution + alpha * random_distribution.
Args:
  alpha: Parameter characterizing the mixture amount between new and old
    distributions. Between 0 and 1.
    alpha = 0: keep old table.
    alpha = 1: keep random table.
  beta: Temperature of the softmax. Makes for more extreme policies.
  random_state: A numpy `RandomState` object. If not provided, a shared
    random state will be used.
Returns:
  Perturbed copy.
Definition at line 369 of file policy.py.
References policy.TabularPolicy.__copy__(), policy.TabularPolicy.action_probability_array, and policy.TabularPolicy.legal_actions_mask.
policy_for_key()
policy.TabularPolicy.policy_for_key (self, key)
Returns the policy as a vector given a state key string.
Args:
  key: A key for the specified state.
Returns:
  A vector of probabilities, one per action. This is a slice of the
  backing policy array, and so slice or index assignment will update the
  policy. For example:
  ```
  tabular_policy.policy_for_key(s)[:] = [0.1, 0.5, 0.4]
  ```
Definition at line 311 of file policy.py.
References policy.TabularPolicy.action_probability_array, and policy.TabularPolicy.state_lookup.
Referenced by policy.TabularPolicy.action_probabilities().
state_index()
policy.TabularPolicy.state_index (self, state)
Returns the index in the TabularPolicy associated to `state`.
Definition at line 307 of file policy.py.
References policy.TabularPolicy._state_key(), and policy.TabularPolicy.state_lookup.
to_dict()
policy.TabularPolicy.to_dict (self)
Returns a single dictionary representing the tabular policy.
Returns:
  A dictionary of string keys to lists of (action, prob) pairs.
Definition at line 327 of file policy.py.
References policy.TabularPolicy.action_probability_array, and policy.TabularPolicy.state_lookup.
Member Data Documentation
action_probability_array
policy.TabularPolicy.action_probability_array
Definition at line 281 of file policy.py.
Referenced by policy.TabularPolicy.__copy__(), policy.TabularPolicy.copy_with_noise(), policy.TabularPolicy.policy_for_key(), and policy.TabularPolicy.to_dict().
game_type
policy.TabularPolicy.game_type
Definition at line 238 of file policy.py.
Referenced by policy.TabularPolicy.__copy__(), and policy.TabularPolicy._state_key().
legal_actions_mask
policy.TabularPolicy.legal_actions_mask
Definition at line 280 of file policy.py.
Referenced by policy.TabularPolicy.__copy__(), and policy.TabularPolicy.copy_with_noise().
state_in
policy.TabularPolicy.state_in
Definition at line 277 of file policy.py.
Referenced by policy.TabularPolicy.__copy__().
state_lookup
policy.TabularPolicy.state_lookup
Definition at line 252 of file policy.py.
Referenced by policy.TabularPolicy.__copy__(), policy.TabularPolicy.policy_for_key(), policy.TabularPolicy.state_index(), and policy.TabularPolicy.to_dict().
states
policy.TabularPolicy.states
Definition at line 254 of file policy.py.
Referenced by policy.TabularPolicy.__copy__().
states_per_player
policy.TabularPolicy.states_per_player
Definition at line 253 of file policy.py.
Referenced by policy.TabularPolicy.__copy__().
The documentation for this class was generated from the following file:
policy.py