My Project: rnad Namespace Reference
rnad Namespace Reference
Classes
class ActorStep
class AdamConfig
class EntropySchedule
class EnvStep
class FineTuning
class NerdConfig
class RNaDConfig
class RNaDSolver
class StateRepresentation
class TimeStep
Functions
chex.Array _legal_policy (chex.Array logits, chex.Array legal_actions)
chex.Array legal_log_policy (chex.Array logits, chex.Array legal_actions)
chex.Array _player_others (chex.Array player_ids, chex.Array valid, int player)
chex.Array _policy_ratio (chex.Array pi, chex.Array mu, chex.Array actions_oh, chex.Array valid)
chex.ArrayTree _where (chex.Array pred, chex.ArrayTree true_data, chex.ArrayTree false_data)
chex.Array _has_played (chex.Array valid, chex.Array player_id, int player)
Tuple[Any, Any, Any] v_trace (chex.Array v, chex.Array valid, chex.Array player_id, chex.Array acting_policy, chex.Array merged_policy, chex.Array merged_log_policy, chex.Array player_others, chex.Array actions_oh, chex.Array reward, int player, float eta, float lambda_, float c, float rho)
chex.Array get_loss_v (Sequence[chex.Array] v_list, Sequence[chex.Array] v_target_list, Sequence[chex.Array] mask_list)
chex.Array apply_force_with_threshold (chex.Array decision_outputs, chex.Array force, float threshold, chex.Array threshold_center)
chex.Array renormalize (chex.Array loss, chex.Array mask)
chex.Array get_loss_nerd (Sequence[chex.Array] logit_list, Sequence[chex.Array] policy_list, Sequence[chex.Array] q_vr_list, chex.Array valid, Sequence[chex.Array] player_ids, chex.Array legal_actions, Sequence[chex.Array] importance_sampling_correction, float clip=100, float threshold=2)
Optimizer optax_optimizer (chex.ArrayTree params, optax.GradientTransformation init_and_update)
Variables
Params = chex.ArrayTree
Optimizer = Callable[[Params, Params], Params]
state
Detailed Description
Python implementation of R-NaD (https://arxiv.org/pdf/2206.15378.pdf).
Function Documentation
_has_played()
chex.Array rnad._has_played (chex.Array valid, chex.Array player_id, int player) protected
Compute a mask of states which have a next state in the sequence.
Definition at line 356 of file rnad.py.
References _where().
Referenced by v_trace().
_legal_policy()
chex.Array rnad._legal_policy (chex.Array logits, chex.Array legal_actions) protected
A soft-max policy that respects legal_actions.
Definition at line 260 of file rnad.py.
_player_others()
chex.Array rnad._player_others (chex.Array player_ids, chex.Array valid, int player) protected
A vector of 1 for the current player and -1 for others.
Args:
  player_ids: Tensor [...] containing player ids (0 <= player_id < N).
  valid: Tensor [...] containing whether these states are valid.
  player: The player id as int.
Returns:
  player_other: is 1 for the current player and -1 for others [..., 1].
Definition at line 296 of file rnad.py.
Referenced by rnad.RNaDSolver.loss().
_policy_ratio()
chex.Array rnad._policy_ratio (chex.Array pi, chex.Array mu, chex.Array actions_oh, chex.Array valid) protected
Returns a ratio of policy pi/mu when selecting action a.
By convention, this ratio is 1 on non valid states
Args:
  pi: the policy of shape [..., A].
  mu: the sampling policy of shape [..., A].
  actions_oh: a one-hot encoding of the current actions of shape [..., A].
  valid: 0 if the state is not valid and else 1 of shape [...].
Returns:
  pi/mu on valid states and 1 otherwise. The shape is the same
  as pi, mu or actions_oh but without the last dimension A.
Definition at line 316 of file rnad.py.
Referenced by v_trace().
_where()
chex.ArrayTree rnad._where (chex.Array pred, chex.ArrayTree true_data, chex.ArrayTree false_data) protected
Similar to jax.where but treats `pred` as a broadcastable prefix.
Definition at line 343 of file rnad.py.
Referenced by _has_played(), and v_trace().
apply_force_with_threshold()
chex.Array rnad.apply_force_with_threshold (chex.Array decision_outputs, chex.Array force, float threshold, chex.Array threshold_center)
Apply the force with below a given threshold.
Definition at line 530 of file rnad.py.
Referenced by get_loss_nerd().
get_loss_nerd()
chex.Array rnad.get_loss_nerd (Sequence[chex.Array] logit_list, Sequence[chex.Array] policy_list, Sequence[chex.Array] q_vr_list, chex.Array valid, Sequence[chex.Array] player_ids, chex.Array legal_actions, Sequence[chex.Array] importance_sampling_correction, float clip = 100, float threshold = 2)
Define the nerd loss.
Definition at line 551 of file rnad.py.
References apply_force_with_threshold(), and renormalize().
Referenced by rnad.RNaDSolver.loss().
get_loss_v()
chex.Array rnad.get_loss_v (Sequence[chex.Array] v_list, Sequence[chex.Array] v_target_list, Sequence[chex.Array] mask_list)
Define the loss function for the critic.
Definition at line 509 of file rnad.py.
Referenced by rnad.RNaDSolver.loss().
legal_log_policy()
chex.Array rnad.legal_log_policy (chex.Array logits, chex.Array legal_actions)
Return the log of the policy on legal action, 0 on illegal action.
Definition at line 274 of file rnad.py.
optax_optimizer()
Optimizer rnad.optax_optimizer (chex.ArrayTree params, optax.GradientTransformation init_and_update)
Creates a parameterized function that represents an optimizer.
Definition at line 692 of file rnad.py.
renormalize()
chex.Array rnad.renormalize (chex.Array loss, chex.Array mask)
The `normalization` is the number of steps over which loss is computed.
Definition at line 543 of file rnad.py.
Referenced by get_loss_nerd().
v_trace()
Tuple[Any, Any, Any] rnad.v_trace (chex.Array v, chex.Array valid, chex.Array player_id, chex.Array acting_policy, chex.Array merged_policy, chex.Array merged_log_policy, chex.Array player_others, chex.Array actions_oh, chex.Array reward, int player, float eta, float lambda_, float c, float rho)
Custom VTrace for trajectories with a mix of different player steps.
Definition at line 395 of file rnad.py.
References _has_played(), _policy_ratio(), and _where().
Referenced by rnad.RNaDSolver.loss().
Variable Documentation
Optimizer
rnad.Optimizer = Callable[[Params, Params], Params]
Definition at line 689 of file rnad.py.
Params
rnad.Params = chex.ArrayTree
Definition at line 37 of file rnad.py.
state
rnad.state
Definition at line 704 of file rnad.py.