My Project: policy Namespace Reference
policy Namespace Reference
Classes
class FirstActionPolicy
class Policy
class TabularPolicy
class UniformRandomPolicy
Functions
child (state, action)
joint_action_probabilities_aux (state, policy)
joint_action_probabilities (state, policy)
get_tabular_policy_states (game)
tabular_policy_from_callable (game, callable_policy, players=None)
pyspiel_policy_to_python_policy (game, pyspiel_tabular_policy, players=None)
python_policy_to_pyspiel_policy (python_tabular_policy)
python_policies_to_pyspiel_policies (policies)
merge_tabular_policies (tabular_policies, game)
Detailed Description
Representation of a policy for a game.
This is a standard representation for passing policies into algorithms,
with currently the following implementations:
  TabularPolicy - an explicit policy per state, stored in an array
    of shape `(num_states, num_actions)`, convenient for tabular policy
    solution methods.
  UniformRandomPolicy - a uniform distribution over all legal actions for
    the specified player. This is computed as needed, so can be used for
    games where a tabular policy would be unfeasibly large.
The main way of using a policy is to call `action_probabilities(state,
player_id`), to obtain a dict of {action: probability}. `TabularPolicy`
objects expose a lower-level interface, which may be more efficient for
some use cases.
Function Documentation
child()
policy.child (state, action)
Returns a child state, handling the simultaneous node case.
Definition at line 43 of file policy.py.
get_tabular_policy_states()
policy.get_tabular_policy_states (game)
Returns the states of the game for a tabular policy.
Definition at line 453 of file policy.py.
Referenced by policy.Policy.to_tabular().
joint_action_probabilities()
policy.joint_action_probabilities (state, policy)
Yields action, probability pairs for a joint policy in simultaneous state.
Args:
  state: a game state at a simultaneous decision node.
  policy: policy that gives the probability distribution over the legal
    actions for each players.
Yields:
  (action, probability) pairs. An action is a tuple of individual
    actions for each player of the game. The probability is a single joint
    probability (product of all the individual probabilities).
Definition at line 76 of file policy.py.
References joint_action_probabilities_aux().
joint_action_probabilities_aux()
policy.joint_action_probabilities_aux (state, policy)
Auxiliary function for joint_action_probabilities.
Args:
  state: a game state at a simultaneous decision node.
  policy: policy that gives the probability distribution over the legal
    actions for each players.
Returns:
  actions_per_player: list of list of actions for each player
  probs_per_player: list of list of probabilities do the corresponding action
   in actions_per_player for each player.
Definition at line 53 of file policy.py.
Referenced by joint_action_probabilities().
merge_tabular_policies()
policy.merge_tabular_policies (tabular_policies, game)
Merges n_player policies into single joint policy.
Missing states are filled with a valid uniform policy.
Args:
  tabular_policies: List of python TabularPolicy (one for each player).
  game: The game corresponding to the resulting TabularPolicy.
Returns:
  merged_policy: A TabularPolicy with each player i's policy taken from the
    ith joint_policy.
Definition at line 555 of file policy.py.
pyspiel_policy_to_python_policy()
policy.pyspiel_policy_to_python_policy (game, pyspiel_tabular_policy, players = None)
Converts a pyspiel.TabularPolicy to a TabularPolicy.
Args:
  game: The OpenSpiel game.
  pyspiel_tabular_policy: Pyspiel tabular policy to copy from.
  players: List of integer player ids to copy policy from. For example,
    `players=[0]` will only copy player 0's policy over into the python policy
    (the other player's policies will be undefined). Default value of `None`
    will copy all players' policies.
Returns:
  python_policy
Definition at line 502 of file policy.py.
python_policies_to_pyspiel_policies()
policy.python_policies_to_pyspiel_policies (policies)
Same conversion as above (list version).
Args:
  policies: a list of python.TabularPolicy
Returns:
  a list of pyspiel.TabularPolicy.
Definition at line 543 of file policy.py.
References python_policy_to_pyspiel_policy().
python_policy_to_pyspiel_policy()
policy.python_policy_to_pyspiel_policy (python_tabular_policy)
Converts a TabularPolicy to a pyspiel.TabularPolicy.
Definition at line 528 of file policy.py.
Referenced by python_policies_to_pyspiel_policies().
tabular_policy_from_callable()
policy.tabular_policy_from_callable (game, callable_policy, players = None)
Converts a legacy callable policy into a TabularPolicy.
Recommendation - instead of using this to convert your policy for evaluation
purposes, work directly with a `TabularPolicy` if possible.
Second choice - work with a `Policy` class and call `to_tabular` as needed.
Args:
  game: The game for which we want a TabularPolicy.
  callable_policy: A callable: state -> action probabilities dict or list.
  players: List of players this policy applies to. If `None`, applies to all
    players.
Returns:
  A TabularPolicy that materializes the callable policy.
Definition at line 475 of file policy.py.