open spiel: absl::ABSL_NAMESPACE_BEGIN::not_a_string_view Class Reference
absl::ABSL_NAMESPACE_BEGIN::not_a_string_view Class Reference
Public Member Functions
not_a_string_view (absl::string_view s)
not_a_string_view (const void *data, size_t size)
not_a_string_view remove_prefix (size_t n) const
not_a_string_view remove_suffix (size_t n) const
const void * data () const
size_t size () const
Detailed Description
Definition at line 143 of file cord_ring_test.cc.
Constructor & Destructor Documentation
not_a_string_view() [1/2]
absl::ABSL_NAMESPACE_BEGIN::not_a_string_view::not_a_string_view (absl::string_view s) inline explicit
Definition at line 145 of file cord_ring_test.cc.
      : data_(s.data()), size_(s.size()) {}
not_a_string_view() [2/2]
absl::ABSL_NAMESPACE_BEGIN::not_a_string_view::not_a_string_view (const void * data, size_t size) inline explicit
Definition at line 147 of file cord_ring_test.cc.
      : data_(data), size_(size) {}
Member Function Documentation
data()
const void * absl::ABSL_NAMESPACE_BEGIN::not_a_string_view::data () const inline
Definition at line 158 of file cord_ring_test.cc.
{ return data_; }
remove_prefix()
not_a_string_view absl::ABSL_NAMESPACE_BEGIN::not_a_string_view::remove_prefix (size_t n) const inline
Definition at line 150 of file cord_ring_test.cc.
{
    return not_a_string_view(static_cast<const char*>(data_) + n, size_ - n);
  }
remove_suffix()
not_a_string_view absl::ABSL_NAMESPACE_BEGIN::not_a_string_view::remove_suffix (size_t n) const inline
Definition at line 154 of file cord_ring_test.cc.
{
    return not_a_string_view(data_, size_ - n);
  }
size()
size_t absl::ABSL_NAMESPACE_BEGIN::not_a_string_view::size () const inline
Definition at line 159 of file cord_ring_test.cc.
{ return size_; }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::__init__(), open_spiel.python.mfg.games.crowd_avoidance.Observer::__init__(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::__init__(), open_spiel.python.mfg.games.crowd_modelling.Observer::__init__(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::__init__(), open_spiel.python.mfg.games.linear_quadratic.Observer::__init__(), open_spiel.python.mfg.games.normal_form_game.MFGNormalFormState::__init__(), open_spiel.python.mfg.games.normal_form_game.Observer::__init__(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::__init__(), open_spiel.python.mfg.games.periodic_aversion.Observer::__init__(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::__init__(), open_spiel.python.mfg.games.predator_prey.Observer::__init__(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), and open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/cord_ring_test.cc