open spiel: absl::beta_distribution< RealType > Class Template Reference
absl::beta_distribution< RealType > Class Template Reference
Classes
class param_type
Public Types
using result_type = RealType
Public Member Functions
beta_distribution (result_type alpha, result_type beta=1)
beta_distribution (const param_type &p)
void reset ()
template<typename URBG >
result_type operator() (URBG &g)
template<typename URBG >
result_type operator() (URBG &g, const param_type &p)
param_type param () const
void param (const param_type &p)
result_type min () const
result_type max () const
result_type alpha () const
result_type beta () const
Friends
bool operator== (const beta_distribution &a, const beta_distribution &b)
bool operator!= (const beta_distribution &a, const beta_distribution &b)
Detailed Description
template<typename RealType = double>
class absl::beta_distribution< RealType >
Definition at line 49 of file beta_distribution.h.
Member Typedef Documentation
result_type
template<typename RealType = double> using absl::beta_distribution< RealType >::result_type = RealType
Definition at line 51 of file beta_distribution.h.
Constructor & Destructor Documentation
beta_distribution() [1/3]
template<typename RealType = double> absl::beta_distribution< RealType >::beta_distribution () inline
Definition at line 202 of file beta_distribution.h.
: beta_distribution(1) {}
beta_distribution() [2/3]
template<typename RealType = double> absl::beta_distribution< RealType >::beta_distribution (result_type alpha, result_type beta = 1) inline explicit
Definition at line 204 of file beta_distribution.h.
      : param_(alpha, beta) {}
beta_distribution() [3/3]
template<typename RealType = double> absl::beta_distribution< RealType >::beta_distribution (const param_type & p) inline explicit
Definition at line 207 of file beta_distribution.h.
: param_(p) {}
Member Function Documentation
alpha()
template<typename RealType = double> result_type absl::beta_distribution< RealType >::alpha () const inline
Definition at line 227 of file beta_distribution.h.
{ return param_.alpha(); }
Referenced by open_spiel.python.algorithms.discounted_cfr._DCFRSolver::__init__(), open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::__init__(), open_spiel.python.algorithms.discounted_cfr._DCFRSolver::evaluate_and_update_policy(), open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::get_gap(), and open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::update_sequences().
beta()
template<typename RealType = double> result_type absl::beta_distribution< RealType >::beta () const inline
Definition at line 228 of file beta_distribution.h.
{ return param_.beta(); }
Referenced by open_spiel.python.algorithms.discounted_cfr._DCFRSolver::__init__(), and open_spiel.python.algorithms.discounted_cfr._DCFRSolver::evaluate_and_update_policy().
max()
template<typename RealType = double> result_type absl::beta_distribution< RealType >::max () const inline
Definition at line 225 of file beta_distribution.h.
{ return 1; }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
template<typename RealType = double> result_type absl::beta_distribution< RealType >::min () const inline
Definition at line 224 of file beta_distribution.h.
{ return 0; }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
operator()() [1/2]
template<typename RealType = double> template<typename URBG > result_type absl::beta_distribution< RealType >::operator() (URBG & g) inline
Definition at line 213 of file beta_distribution.h.
                                  {  // NOLINT(runtime/references)
    return (*this)(g, param_);
  }
operator()() [2/2]
template<typename RealType > template<typename URBG > beta_distribution< RealType >::result_type absl::beta_distribution< RealType >::operator() (URBG & g, const param_type & p)
Definition at line 382 of file beta_distribution.h.
{
  switch (p.method_) {
    case param_type::JOEHNK:
      return AlgorithmJoehnk(g, p);
    case param_type::CHENG_BA:
      ABSL_FALLTHROUGH_INTENDED;
    case param_type::CHENG_BB:
      return AlgorithmCheng(g, p);
    default:
      return DegenerateCase(g, p);
  }
}
param() [1/2]
template<typename RealType = double> param_type absl::beta_distribution< RealType >::param () const inline
Definition at line 221 of file beta_distribution.h.
{ return param_; }
param() [2/2]
template<typename RealType = double> void absl::beta_distribution< RealType >::param (const param_type & p) inline
Definition at line 222 of file beta_distribution.h.
{ param_ = p; }
reset()
template<typename RealType = double> void absl::beta_distribution< RealType >::reset () inline
Definition at line 209 of file beta_distribution.h.
{}
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear::__init__(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), open_spiel.python.rl_environment.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
Friends And Related Symbol Documentation
operator!=
template<typename RealType = double> bool operator!= (const beta_distribution< RealType > & a, const beta_distribution< RealType > & b) friend
Definition at line 234 of file beta_distribution.h.
{
    return a.param_ != b.param_;
  }
operator==
template<typename RealType = double> bool operator== (const beta_distribution< RealType > & a, const beta_distribution< RealType > & b) friend
Definition at line 230 of file beta_distribution.h.
{
    return a.param_ == b.param_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/beta_distribution.h