open spiel: absl::bernoulli_distribution Class Reference
absl::bernoulli_distribution Class Reference
Classes
class param_type
Public Types
using result_type = bool
Public Member Functions
bernoulli_distribution (double p)
bernoulli_distribution (param_type p)
void reset ()
template<typename URBG >
bool operator() (URBG &g)
template<typename URBG >
bool operator() (URBG &g, const param_type &param)
param_type param () const
void param (const param_type &param)
double p () const
result_type min () const
result_type max () const
Friends
bool operator== (const bernoulli_distribution &d1, const bernoulli_distribution &d2)
bool operator!= (const bernoulli_distribution &d1, const bernoulli_distribution &d2)
Detailed Description
Definition at line 35 of file bernoulli_distribution.h.
Member Typedef Documentation
result_type
using absl::bernoulli_distribution::result_type = bool
Definition at line 37 of file bernoulli_distribution.h.
Constructor & Destructor Documentation
bernoulli_distribution() [1/3]
absl::bernoulli_distribution::bernoulli_distribution () inline
Definition at line 60 of file bernoulli_distribution.h.
: bernoulli_distribution(0.5) {}
bernoulli_distribution() [2/3]
absl::bernoulli_distribution::bernoulli_distribution (double p) inline explicit
Definition at line 62 of file bernoulli_distribution.h.
: param_(p) {}
bernoulli_distribution() [3/3]
absl::bernoulli_distribution::bernoulli_distribution (param_type p) inline explicit
Definition at line 64 of file bernoulli_distribution.h.
: param_(p) {}
Member Function Documentation
max()
result_type absl::bernoulli_distribution::max () const inline
Definition at line 86 of file bernoulli_distribution.h.
{ return true; }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
result_type absl::bernoulli_distribution::min () const inline
Definition at line 85 of file bernoulli_distribution.h.
{ return false; }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
operator()() [1/2]
template<typename URBG > bool absl::bernoulli_distribution::operator() (URBG & g) inline
Definition at line 70 of file bernoulli_distribution.h.
                           {  // NOLINT(runtime/references)
    return Generate(param_.p(), g);
  }
operator()() [2/2]
template<typename URBG > bool absl::bernoulli_distribution::operator() (URBG & g, const param_type & param) inline
Definition at line 75 of file bernoulli_distribution.h.
{
    return Generate(param.p(), g);
  }
p()
double absl::bernoulli_distribution::p () const inline
Definition at line 83 of file bernoulli_distribution.h.
{ return param_.p(); }
Referenced by open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::cheap_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::exploitability(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::gradients(), and open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::gradients().
param() [1/2]
param_type absl::bernoulli_distribution::param () const inline
Definition at line 80 of file bernoulli_distribution.h.
{ return param_; }
param() [2/2]
void absl::bernoulli_distribution::param (const param_type & param) inline
Definition at line 81 of file bernoulli_distribution.h.
{ param_ = param; }
reset()
void absl::bernoulli_distribution::reset () inline
Definition at line 67 of file bernoulli_distribution.h.
{}
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear::__init__(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), open_spiel.python.rl_environment.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const bernoulli_distribution & d1, const bernoulli_distribution & d2) friend
Definition at line 93 of file bernoulli_distribution.h.
{
    return d1.param_ != d2.param_;
  }
operator==
bool operator== (const bernoulli_distribution & d1, const bernoulli_distribution & d2) friend
Definition at line 88 of file bernoulli_distribution.h.
{
    return d1.param_ == d2.param_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/bernoulli_distribution.h