open spiel: open_spiel.python.examples.chat_game_psro_example Namespace Reference
open_spiel.python.examples.chat_game_psro_example Namespace Reference
Classes
class Domain
class PSRO
class PSROReporting
Functions
get_config ()
sym (pt)
random_policy (rnd, state)
fixed_prompt_policy (rnd, state, prompt_action_dict)
mixed_prompt_policy (rnd, state, prompt_keys, mixture)
build_player_policy (policies)
simulate_dialogue (game, policy)
estimate_payoff_tensor (game, rnd, num_trials=5)
score_candidate_responses (game_str, config, load_dict, rnd, background_policies, candidates, player_ids=(0,), num_trials=5)
compute_sym_eq (pt)
main (_)
Variables
_SAVE_PATH
LLM_TYPE = chat_test_utils.TestLLM.MOCK
Detailed Description
Prompt-Space Response-Oracle (PSRO) experiment.
Runs PSRO exploring the space of `tones` with which to construct messages. Only
works with `tones` for now.
Function Documentation
build_player_policy()
open_spiel.python.examples.chat_game_psro_example.build_player_policy (policies)
Definition at line 132 of file chat_game_psro_example.py.
def build_player_policy(policies):
  def player_policy(player_id, state):
    return policies[player_id](state)
  return player_policy
compute_sym_eq()
open_spiel.python.examples.chat_game_psro_example.compute_sym_eq (pt)
Definition at line 237 of file chat_game_psro_example.py.
def compute_sym_eq(pt):
  game = nashpy.Game(pt[0], pt[1])
  p1_traj, p2_traj = game.asymmetric_replicator_dynamics()
  p1_strat = np.mean(p1_traj, axis=0)
  p2_strat = np.mean(p2_traj, axis=0)
  return 0.5 * p1_strat + 0.5 * p2_strat
estimate_payoff_tensor()
open_spiel.python.examples.chat_game_psro_example.estimate_payoff_tensor (game, rnd, num_trials = 5)
Simulate a batch of dialogues and returns payoffs for each player.
Definition at line 161 of file chat_game_psro_example.py.
def estimate_payoff_tensor(game, rnd, num_trials=5):
  """Simulate a batch of dialogues and returns payoffs for each player."""
  num_players = game.num_players()
  num_actions = len(game.given_prompt_actions["tone"])
  payoff_tensor = np.zeros(
      (num_trials, num_players) + (num_actions,) * num_players
  )
  joint_actions = list(itertools.product(range(num_actions),
                                         repeat=num_players))
  for trial in range(num_trials):
    for joint_action_idx in joint_actions:
      policies = []
      for _, tone_idx in zip(range(num_players), joint_action_idx):
        fixed_tone = {"tone": game.given_prompt_actions["tone"][tone_idx]}
        policy = lambda state: fixed_prompt_policy(rnd, state, fixed_tone)  # pylint:disable=cell-var-from-loop
        policies.append(policy)
      player_policy = build_player_policy(policies)
      returns = simulate_dialogue(game, player_policy)
      pt_index = (trial, slice(None)) + joint_action_idx
      payoff_tensor[pt_index] = returns
  return payoff_tensor
References open_spiel.python.examples.chat_game_psro_example.simulate_dialogue().
Referenced by open_spiel.python.examples.chat_game_psro_example.PSRO.run().
fixed_prompt_policy()
open_spiel.python.examples.chat_game_psro_example.fixed_prompt_policy (rnd, state, prompt_action_dict)
Definition at line 108 of file chat_game_psro_example.py.
def fixed_prompt_policy(rnd, state, prompt_action_dict):
  # all actions are legal for now
  action = [rnd.choice(a) for a in state.num_actions]
  for prompt_key, prompt_action in prompt_action_dict.items():
    prompt_key_idx = 1 + state.header.action_keys.index(prompt_key)
    prompt_val_idx = state.prompt_actions[prompt_key].index(prompt_action)
    action[prompt_key_idx] = prompt_val_idx
  action = tuple(action)
  return np.ravel_multi_index(action, state.num_actions)
get_config()
open_spiel.python.examples.chat_game_psro_example.get_config ()
Get configuration for imitation dataset construction.
Definition at line 55 of file chat_game_psro_example.py.
def get_config():
  """Get configuration for imitation dataset construction."""
  config = ml_collections.config_dict.ConfigDict()
  config.game_string = "chat_game"
  config.seed = 34239871
  config.num_iters = 4
  config.num_trials = 10
  config.num_candidates = 2
  config.domain = Domain.SCHEDULE_MEETING_W_TONE
  if config.domain == Domain.TRADE_FRUIT_W_TONE:
    config.env_config = config_trade_fruit_w_tone.get_config()
  elif config.domain == Domain.SCHEDULE_MEETING_W_TONE:
    config.env_config = config_schedule_meeting_w_tone.get_config()
  else:
    raise ValueError("Unknown domain: %s" % config.domain)
  return config
Referenced by open_spiel.python.examples.chat_game_psro_example.PSROReporting.report().
main()
open_spiel.python.examples.chat_game_psro_example.main (_)
Definition at line 405 of file chat_game_psro_example.py.
def main(_):
  logging.set_verbosity(logging.ERROR)  # silence internal game logging
  save_path = _SAVE_PATH.value
  config = get_config()
  psro = PSRO(save_path, config)
  psro.run()
mixed_prompt_policy()
open_spiel.python.examples.chat_game_psro_example.mixed_prompt_policy (rnd, state, prompt_keys, mixture)
Definition at line 119 of file chat_game_psro_example.py.
def mixed_prompt_policy(rnd, state, prompt_keys, mixture):
  # all actions are legal for now
  action = [rnd.choice(a) for a in state.num_actions]
  for prompt_key in prompt_keys:
    prompt_key_idx = 1 + state.header.action_keys.index(prompt_key)
    actions = state.prompt_actions[prompt_key]
    num_actions = len(actions)
    prompt_val_idx = rnd.choice(num_actions, p=mixture)
    action[prompt_key_idx] = prompt_val_idx
  action = tuple(action)
  return np.ravel_multi_index(action, state.num_actions)
random_policy()
open_spiel.python.examples.chat_game_psro_example.random_policy (rnd, state)
Definition at line 102 of file chat_game_psro_example.py.
def random_policy(rnd, state):
  # all actions are legal for now
  rnd_action = tuple([rnd.choice(a) for a in state.num_actions])
  return np.ravel_multi_index(rnd_action, state.num_actions)
score_candidate_responses()
open_spiel.python.examples.chat_game_psro_example.score_candidate_responses (game_str, config, load_dict, rnd, background_policies, candidates, player_ids = (0,), num_trials = 5)
Simulate a batch of dialogues and returns payoffs for each player.
Definition at line 191 of file chat_game_psro_example.py.
                              player_ids=(0,), num_trials=5):
  """Simulate a batch of dialogues and returns payoffs for each player."""
  num_players = config.params["num_players"]
  num_candidates = len(candidates)
  config.game.given_prompt_actions["tone"] += candidates
  num_actions = len(config.game.given_prompt_actions["tone"])
  config.params["num_distinct_actions"] = num_players * num_actions
  game = pyspiel.load_game(game_str, config.params.to_dict())
  game.load_chat_game(**load_dict, **config.game)
  payoffs = np.zeros((num_trials, len(player_ids), num_candidates))
  for player_id in player_ids:
    for trial in range(num_trials):
      for candidate_idx in range(num_candidates):
        policies = []
        for i in range(num_players):
          if player_id == i:
            fixed_tone = {"tone": candidates[candidate_idx]}
            policy = lambda state: fixed_prompt_policy(rnd, state, fixed_tone)  # pylint:disable=cell-var-from-loop
            policies.append(policy)
          else:
            policies.append(background_policies[i])
        player_policy = build_player_policy(policies)
        returns = simulate_dialogue(game, player_policy)
        payoffs[trial, player_id, candidate_idx] = returns[player_id]
  # undo changes to config (is this inplace?)
  config.game.given_prompt_actions["tone"] = config.game.given_prompt_actions[
      "tone"
  ][:-num_candidates]
  num_tones = len(config.game.given_prompt_actions["tone"])
  config.params["num_distinct_actions"] = num_players * num_tones
  return payoffs, candidates
References open_spiel.python.examples.chat_game_psro_example.simulate_dialogue().
Referenced by open_spiel.python.examples.chat_game_psro_example.PSRO.run().
simulate_dialogue()
open_spiel.python.examples.chat_game_psro_example.simulate_dialogue (game, policy)
Simulate a dialogue and returns payoffs for each player.
Definition at line 138 of file chat_game_psro_example.py.
def simulate_dialogue(game, policy):
  """Simulate a dialogue and returns payoffs for each player."""
  state = game.new_initial_state()
  while not state.is_terminal():
    if state.is_chance_node():
      # Chance node: sample an outcome
      outcomes = state.chance_outcomes()
      action_list, prob_list = zip(*outcomes)
      action = np.random.choice(action_list, p=prob_list)
      state.apply_action(action)
    else:
      # Decision node: sample action for the single current player
      action = policy(state.current_player(), state)
      state.apply_action(action)
  # Game is now done. Print utilities for each player
  returns = state.returns()
  return returns
Referenced by open_spiel.python.examples.chat_game_psro_example.estimate_payoff_tensor(), and open_spiel.python.examples.chat_game_psro_example.score_candidate_responses().
sym()
open_spiel.python.examples.chat_game_psro_example.sym (pt)
Symmetrize stack of payoff tensors (stacked along first dimension).
A payoff tensor can be `symmetrized' by averaging over all possible
permutations of the players. This means permuting the axes corresponding to
the player strategies as well as the payoffs assigned to the players. E.g.,
player A playing strategy 1 and player B playing strategy 3 is no different
from player A playing strategy 3 and player B playing strategy 1 in a
symmetric game. Note we permuted the strategies, but we must also permute the
payoffs.
Args:
  pt: tensor of shape: (num_players,) + (num_strategies,) * num_players
Returns:
  pt_sym: symmetrized payoff tensor of same shape
Definition at line 76 of file chat_game_psro_example.py.
def sym(pt):
  """Symmetrize stack of payoff tensors (stacked along first dimension).
  A payoff tensor can be `symmetrized' by averaging over all possible
  permutations of the players. This means permuting the axes corresponding to
  the player strategies as well as the payoffs assigned to the players. E.g.,
  player A playing strategy 1 and player B playing strategy 3 is no different
  from player A playing strategy 3 and player B playing strategy 1 in a
  symmetric game. Note we permuted the strategies, but we must also permute the
  payoffs.
  Args:
    pt: tensor of shape: (num_players,) + (num_strategies,) * num_players
  Returns:
    pt_sym: symmetrized payoff tensor of same shape
  """
  num_players = len(pt.shape[1:])
  num_perms = math.factorial(num_players)
  pt_sym = np.zeros_like(pt)
  for _, perm_players in enumerate(itertools.permutations(range(num_players))):
    perm_axes = tuple([pi + 1 for pi in perm_players])
    permuted_tensor = np.transpose(pt, (0,) + perm_axes)[list(perm_players)]
    pt_sym += permuted_tensor / float(num_perms)
  return pt_sym
Referenced by open_spiel.python.examples.chat_game_psro_example.PSRO.run().
Variable Documentation
_SAVE_PATH
open_spiel.python.examples.chat_game_psro_example._SAVE_PATH protected
Initial value:
=  flags.DEFINE_string("save_path",
                                 default="",
                                 help="path for writing results")
Definition at line 43 of file chat_game_psro_example.py.
LLM_TYPE
open_spiel.python.examples.chat_game_psro_example.LLM_TYPE = chat_test_utils.TestLLM.MOCK
Definition at line 47 of file chat_game_psro_example.py.