open spiel: absl::discrete_distribution< IntType > Class Template Reference
absl::discrete_distribution< IntType > Class Template Reference
Classes
class param_type
Public Types
using result_type = IntType
Public Member Functions
discrete_distribution (const param_type &p)
template<typename InputIterator >
discrete_distribution (InputIterator begin, InputIterator end)
discrete_distribution (std::initializer_list< double > weights)
template<class UnaryOperation >
discrete_distribution (size_t nw, double xmin, double xmax, UnaryOperation fw)
void reset ()
template<typename URBG >
result_type operator() (URBG &g)
template<typename URBG >
result_type operator() (URBG &g, const param_type &p)
const param_type & param () const
void param (const param_type &p)
result_type min () const
result_type max () const
const std::vector< double > & probabilities () const
Friends
bool operator== (const discrete_distribution &a, const discrete_distribution &b)
bool operator!= (const discrete_distribution &a, const discrete_distribution &b)
Detailed Description
template<typename IntType = int>
class absl::discrete_distribution< IntType >
Definition at line 52 of file discrete_distribution.h.
Member Typedef Documentation
result_type
template<typename IntType = int> using absl::discrete_distribution< IntType >::result_type = IntType
Definition at line 54 of file discrete_distribution.h.
Constructor & Destructor Documentation
discrete_distribution() [1/5]
template<typename IntType = int> absl::discrete_distribution< IntType >::discrete_distribution () inline
Definition at line 111 of file discrete_distribution.h.
: param_() {}
discrete_distribution() [2/5]
template<typename IntType = int> absl::discrete_distribution< IntType >::discrete_distribution (const param_type & p) inline explicit
Definition at line 113 of file discrete_distribution.h.
: param_(p) {}
discrete_distribution() [3/5]
template<typename IntType = int> template<typename InputIterator > absl::discrete_distribution< IntType >::discrete_distribution (InputIterator begin, InputIterator end) inline explicit
Definition at line 116 of file discrete_distribution.h.
      : param_(begin, end) {}
discrete_distribution() [4/5]
template<typename IntType = int> absl::discrete_distribution< IntType >::discrete_distribution (std::initializer_list< double > weights) inline explicit
Definition at line 119 of file discrete_distribution.h.
      : param_(weights) {}
discrete_distribution() [5/5]
template<typename IntType = int> template<class UnaryOperation > absl::discrete_distribution< IntType >::discrete_distribution (size_t nw, double xmin, double xmax, UnaryOperation fw) inline explicit
Definition at line 123 of file discrete_distribution.h.
      : param_(nw, xmin, xmax, std::move(fw)) {}
Member Function Documentation
max()
template<typename IntType = int> result_type absl::discrete_distribution< IntType >::max () const inline
Definition at line 143 of file discrete_distribution.h.
{
    return static_cast<result_type>(param_.n());
  }  // inclusive
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
template<typename IntType = int> result_type absl::discrete_distribution< IntType >::min () const inline
Definition at line 142 of file discrete_distribution.h.
{ return 0; }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
operator()() [1/2]
template<typename IntType = int> template<typename URBG > result_type absl::discrete_distribution< IntType >::operator() (URBG & g) inline
Definition at line 131 of file discrete_distribution.h.
                                  {  // NOLINT(runtime/references)
    return (*this)(g, param_);
  }
operator()() [2/2]
template<typename IntType > template<typename URBG > discrete_distribution< IntType >::result_type absl::discrete_distribution< IntType >::operator() (URBG & g, const param_type & p)
Definition at line 196 of file discrete_distribution.h.
{
  const auto idx = absl::uniform_int_distribution<result_type>(0, p.n())(g);
  const auto& q = p.q_[idx];
  const bool selected = absl::bernoulli_distribution(q.first)(g);
  return selected ? idx : static_cast<result_type>(q.second);
}
param() [1/2]
template<typename IntType = int> const param_type & absl::discrete_distribution< IntType >::param () const inline
Definition at line 139 of file discrete_distribution.h.
{ return param_; }
param() [2/2]
template<typename IntType = int> void absl::discrete_distribution< IntType >::param (const param_type & p) inline
Definition at line 140 of file discrete_distribution.h.
{ param_ = p; }
probabilities()
template<typename IntType = int> const std::vector< double > & absl::discrete_distribution< IntType >::probabilities () const inline
Definition at line 149 of file discrete_distribution.h.
{
    return param_.probabilities();
  }
reset()
template<typename IntType = int> void absl::discrete_distribution< IntType >::reset () inline
Definition at line 127 of file discrete_distribution.h.
{}
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear::__init__(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), open_spiel.python.rl_environment.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
Friends And Related Symbol Documentation
operator!=
template<typename IntType = int> bool operator!= (const discrete_distribution< IntType > & a, const discrete_distribution< IntType > & b) friend
Definition at line 157 of file discrete_distribution.h.
{
    return a.param_ != b.param_;
  }
operator==
template<typename IntType = int> bool operator== (const discrete_distribution< IntType > & a, const discrete_distribution< IntType > & b) friend
Definition at line 153 of file discrete_distribution.h.
{
    return a.param_ == b.param_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/discrete_distribution.h