open spiel: open_spiel.python.egt.visualization.Dynamics2x2Axes Class Reference
open_spiel.python.egt.visualization.Dynamics2x2Axes Class Reference
Public Member Functions
cla (self)
quiver (self, dynamics, num_points=9, normalize=False, pivot="middle", **kwargs)
streamplot (self, dynamics, num_points=50, linewidth=None, color=None, **kwargs)
Static Public Attributes
str name = "2x2"
Detailed Description
Axes for 2x2 game dynamics.
This class provides plotting functions for dynamics in two-player 2x2 games.
Attributes:
  name: Used for projection keyword when creating a new axes.
Definition at line 101 of file visualization.py.
Member Function Documentation
cla()
open_spiel.python.egt.visualization.Dynamics2x2Axes.cla (self)
Clear the current axes.
Definition at line 111 of file visualization.py.
  def cla(self):
    """Clear the current axes."""
    super(Dynamics2x2Axes, self).cla()
    self.set_aspect("equal")
    self.set_xlim(0, 1)
    self.set_ylim(0, 1)
References open_spiel.python.egt.visualization.Dynamics2x2Axes.cla().
Referenced by open_spiel.python.egt.visualization.Dynamics2x2Axes.cla().
quiver()
open_spiel.python.egt.visualization.Dynamics2x2Axes.quiver (self, dynamics, num_points = 9, normalize = False, pivot = "middle", ** kwargs)
Visualizes the dynamics as a directional field plot.
Args:
  dynamics: Population dynamics of type `dynamics.MultiPopulationDynamics`.
  num_points: Number of points along each dimension of the plot.
  normalize: Normalize each arrow to unit-length.
  pivot: In `{"tail", "middle", "tip"}`, optional, default: "middle". The
    part of the arrow that is anchored to the X, Y grid. The arrow rotates
    about this point.
  **kwargs: Additional keyword arguments passed on to `Axes.quiver`.
Returns:
  The `quiver.Quiver` object created by calling `Axes.quiver`.
Definition at line 118 of file visualization.py.
             **kwargs):
    """Visualizes the dynamics as a directional field plot.
    Args:
      dynamics: Population dynamics of type `dynamics.MultiPopulationDynamics`.
      num_points: Number of points along each dimension of the plot.
      normalize: Normalize each arrow to unit-length.
      pivot: In `{"tail", "middle", "tip"}`, optional, default: "middle". The
        part of the arrow that is anchored to the X, Y grid. The arrow rotates
        about this point.
      **kwargs: Additional keyword arguments passed on to `Axes.quiver`.
    Returns:
      The `quiver.Quiver` object created by calling `Axes.quiver`.
    """
    x, y, u, v = _eval_dynamics_2x2_grid(dynamics, num_points)
    if normalize:
      norm = np.sqrt(u**2 + v**2)
      u = np.divide(u, norm, out=np.zeros_like(u), where=norm != 0)
      v = np.divide(v, norm, out=np.zeros_like(v), where=norm != 0)
    return super(Dynamics2x2Axes, self).quiver(
        x, y, u, v, pivot=pivot, **kwargs)
References open_spiel.python.egt.visualization._eval_dynamics_2x2_grid(), and open_spiel.python.egt.visualization.Dynamics2x2Axes.quiver().
Referenced by open_spiel.python.egt.visualization.Dynamics2x2Axes.quiver().
streamplot()
open_spiel.python.egt.visualization.Dynamics2x2Axes.streamplot (self, dynamics, num_points = 50, linewidth = None, color = None, ** kwargs)
Visualizes the dynamics as a streamline plot.
Args:
  dynamics: Population dynamics of type `dynamics.MultiPopulationDynamics`.
  num_points: Number of points along each dimension of the plot.
  linewidth: In `{None, float, "velocity"}`, optional, default: None. If
    `linewidth="velocity"`, line width is scaled by the velocity of the
    dynamics. Defaults to `rcParams` if `linewidth=None`.
  color: In `{None, string, (r,g,b), (r,g,b,a), "velocity"}`, default: None.
    If `color="velocity"`, velocity of dynamics is used to color the
    streamlines. Defaults to `rcParams` if `color=None`.
  **kwargs: Additional keyword arguments passed on to `Axes.streamplot`.
Returns:
  The `streamplot.StreamplotSet` created by calling `Axes.streamplot`.
Definition at line 148 of file visualization.py.
                 **kwargs):
    """Visualizes the dynamics as a streamline plot.
    Args:
      dynamics: Population dynamics of type `dynamics.MultiPopulationDynamics`.
      num_points: Number of points along each dimension of the plot.
      linewidth: In `{None, float, "velocity"}`, optional, default: None. If
        `linewidth="velocity"`, line width is scaled by the velocity of the
        dynamics. Defaults to `rcParams` if `linewidth=None`.
      color: In `{None, string, (r,g,b), (r,g,b,a), "velocity"}`, default: None.
        If `color="velocity"`, velocity of dynamics is used to color the
        streamlines. Defaults to `rcParams` if `color=None`.
      **kwargs: Additional keyword arguments passed on to `Axes.streamplot`.
    Returns:
      The `streamplot.StreamplotSet` created by calling `Axes.streamplot`.
    """
    x, y, u, v = _eval_dynamics_2x2_grid(dynamics, num_points)
    if linewidth == "velocity" or color == "velocity":
      vel = np.sqrt(u**2 + v**2)
      vel = vel - np.min(vel)
      vel = vel / np.max(vel)
      if linewidth == "velocity":
        linewidth = 3. * vel
      if color == "velocity":
        color = vel
    return super(Dynamics2x2Axes, self).streamplot(
        x, y, u, v, minlength=0.1, linewidth=linewidth, color=color, **kwargs)
References open_spiel.python.egt.visualization._eval_dynamics_2x2_grid(), and open_spiel.python.egt.visualization.Dynamics2x2Axes.streamplot().
Referenced by open_spiel.python.egt.visualization.Dynamics2x2Axes.streamplot().
Member Data Documentation
name
str open_spiel.python.egt.visualization.Dynamics2x2Axes.name = "2x2" static
Definition at line 109 of file visualization.py.
The documentation for this class was generated from the following file:
open_spiel/python/egt/visualization.py