open spiel: absl::log_uniform_int_distribution< IntType > Class Template Reference
absl::log_uniform_int_distribution< IntType > Class Template Reference
Classes
class param_type
Public Types
using result_type = IntType
Public Member Functions
log_uniform_int_distribution (result_type min, result_type max=(std::numeric_limits< result_type >::max)(), result_type base=2)
log_uniform_int_distribution (const param_type &p)
void reset ()
template<typename URBG >
result_type operator() (URBG &g)
template<typename URBG >
result_type operator() (URBG &g, const param_type &p)
result_type min () const
result_type max () const
result_type base () const
param_type param () const
void param (const param_type &p)
template<typename URBG >
log_uniform_int_distribution< IntType >::unsigned_type Generate (URBG &g, const param_type &p)
Friends
bool operator== (const log_uniform_int_distribution &a, const log_uniform_int_distribution &b)
bool operator!= (const log_uniform_int_distribution &a, const log_uniform_int_distribution &b)
Detailed Description
template<typename IntType = int>
class absl::log_uniform_int_distribution< IntType >
Definition at line 44 of file log_uniform_int_distribution.h.
Member Typedef Documentation
result_type
template<typename IntType = int> using absl::log_uniform_int_distribution< IntType >::result_type = IntType
Definition at line 50 of file log_uniform_int_distribution.h.
Constructor & Destructor Documentation
log_uniform_int_distribution() [1/3]
template<typename IntType = int> absl::log_uniform_int_distribution< IntType >::log_uniform_int_distribution () inline
Definition at line 119 of file log_uniform_int_distribution.h.
: log_uniform_int_distribution(0) {}
log_uniform_int_distribution() [2/3]
template<typename IntType = int> absl::log_uniform_int_distribution< IntType >::log_uniform_int_distribution (result_type min, result_type max = (std::numeric_limits<result_type>::max)(), result_type base = 2) inline explicit
Definition at line 121 of file log_uniform_int_distribution.h.
      : param_(min, max, base) {}
log_uniform_int_distribution() [3/3]
template<typename IntType = int> absl::log_uniform_int_distribution< IntType >::log_uniform_int_distribution (const param_type & p) inline explicit
Definition at line 127 of file log_uniform_int_distribution.h.
: param_(p) {}
Member Function Documentation
base()
template<typename IntType = int> result_type absl::log_uniform_int_distribution< IntType >::base () const inline
Definition at line 145 of file log_uniform_int_distribution.h.
{ return param_.base(); }
Generate()
template<typename IntType = int> template<typename URBG > log_uniform_int_distribution< IntType >::unsigned_type absl::log_uniform_int_distribution< IntType >::Generate (URBG & g, const param_type & p)
Definition at line 172 of file log_uniform_int_distribution.h.
{
  // sample e over [0, log_range]. Map the results of e to this:
  // 0 => 0
  // 1 => [1, b-1]
  // 2 => [b, (b^2)-1]
  // n => [b^(n-1)..(b^n)-1]
  const int e = absl::uniform_int_distribution<int>(0, p.log_range())(g);
  if (e == 0) {
    return 0;
  }
  const int d = e - 1;
  unsigned_type base_e, top_e;
  if (p.base() == 2) {
    base_e = static_cast<unsigned_type>(1) << d;
    top_e = (e >= std::numeric_limits<unsigned_type>::digits)
                ? (std::numeric_limits<unsigned_type>::max)()
                : (static_cast<unsigned_type>(1) << e) - 1;
  } else {
    const double r = std::pow(static_cast<double>(p.base()), d);
    const double s = (r * static_cast<double>(p.base())) - 1.0;
    base_e =
        (r > static_cast<double>((std::numeric_limits<unsigned_type>::max)()))
            ? (std::numeric_limits<unsigned_type>::max)()
            : static_cast<unsigned_type>(r);
    top_e =
        (s > static_cast<double>((std::numeric_limits<unsigned_type>::max)()))
            ? (std::numeric_limits<unsigned_type>::max)()
            : static_cast<unsigned_type>(s);
  }
  const unsigned_type lo = (base_e >= p.range()) ? p.range() : base_e;
  const unsigned_type hi = (top_e >= p.range()) ? p.range() : top_e;
  // choose uniformly over [lo, hi]
  return absl::uniform_int_distribution<result_type>(
      static_cast<result_type>(lo), static_cast<result_type>(hi))(g);
}
max()
template<typename IntType = int> result_type absl::log_uniform_int_distribution< IntType >::max () const inline
Definition at line 144 of file log_uniform_int_distribution.h.
{ return (param_.max)(); }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
template<typename IntType = int> result_type absl::log_uniform_int_distribution< IntType >::min () const inline
Definition at line 143 of file log_uniform_int_distribution.h.
{ return (param_.min)(); }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
operator()() [1/2]
template<typename IntType = int> template<typename URBG > result_type absl::log_uniform_int_distribution< IntType >::operator() (URBG & g) inline
Definition at line 133 of file log_uniform_int_distribution.h.
                                  {  // NOLINT(runtime/references)
    return (*this)(g, param_);
  }
operator()() [2/2]
template<typename IntType = int> template<typename URBG > result_type absl::log_uniform_int_distribution< IntType >::operator() (URBG & g, const param_type & p) inline
Definition at line 138 of file log_uniform_int_distribution.h.
{
    return static_cast<result_type>((p.min)() + Generate(g, p));
  }
param() [1/2]
template<typename IntType = int> param_type absl::log_uniform_int_distribution< IntType >::param () const inline
Definition at line 147 of file log_uniform_int_distribution.h.
{ return param_; }
param() [2/2]
template<typename IntType = int> void absl::log_uniform_int_distribution< IntType >::param (const param_type & p) inline
Definition at line 148 of file log_uniform_int_distribution.h.
{ param_ = p; }
reset()
template<typename IntType = int> void absl::log_uniform_int_distribution< IntType >::reset () inline
Definition at line 129 of file log_uniform_int_distribution.h.
{}
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear::__init__(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), open_spiel.python.rl_environment.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
Friends And Related Symbol Documentation
operator!=
template<typename IntType = int> bool operator!= (const log_uniform_int_distribution< IntType > & a, const log_uniform_int_distribution< IntType > & b) friend
Definition at line 154 of file log_uniform_int_distribution.h.
{
    return a.param_ != b.param_;
  }
operator==
template<typename IntType = int> bool operator== (const log_uniform_int_distribution< IntType > & a, const log_uniform_int_distribution< IntType > & b) friend
Definition at line 150 of file log_uniform_int_distribution.h.
{
    return a.param_ == b.param_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/log_uniform_int_distribution.h