open spiel: open_spiel.python.algorithms.psro_v2.strategy_selectors_test.FakeSolver Class Reference
open_spiel.python.algorithms.psro_v2.strategy_selectors_test.FakeSolver Class Reference
Public Member Functions
__init__ (self, strategies, policies)
get_policies (self)
get_meta_strategies (self)
Public Attributes
strategies
policies
Detailed Description
Definition at line 22 of file strategy_selectors_test.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.algorithms.psro_v2.strategy_selectors_test.FakeSolver.__init__ (self, strategies, policies)
Definition at line 24 of file strategy_selectors_test.py.
  def __init__(self, strategies, policies):
    self.strategies = strategies
    self.policies = policies
Member Function Documentation
get_meta_strategies()
open_spiel.python.algorithms.psro_v2.strategy_selectors_test.FakeSolver.get_meta_strategies (self)
Definition at line 31 of file strategy_selectors_test.py.
  def get_meta_strategies(self):
    return self.strategies
Referenced by open_spiel.python.algorithms.psro_v2.psro_v2.PSROSolver.get_policies_and_strategies().
get_policies()
open_spiel.python.algorithms.psro_v2.strategy_selectors_test.FakeSolver.get_policies (self)
Definition at line 28 of file strategy_selectors_test.py.
  def get_policies(self):
    return self.policies
Referenced by open_spiel.python.algorithms.psro_v2.psro_v2.PSROSolver.get_joint_policies_from_id_list(), and open_spiel.python.algorithms.psro_v2.psro_v2.PSROSolver.get_policies_and_strategies().
Member Data Documentation
policies
open_spiel.python.algorithms.psro_v2.strategy_selectors_test.FakeSolver.policies
Definition at line 26 of file strategy_selectors_test.py.
Referenced by open_spiel.python.algorithms.fictitious_play.JointPolicy.__init__(), and open_spiel.python.algorithms.fictitious_play.JointPolicy.action_probabilities().
strategies
open_spiel.python.algorithms.psro_v2.strategy_selectors_test.FakeSolver.strategies
Definition at line 25 of file strategy_selectors_test.py.
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/psro_v2/strategy_selectors_test.py