open spiel: open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection Class Reference
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection Class Reference
Public Member Functions
__init__ (self, target, source, num_actions, prior_actions_weight, prior_memory_actions, is_external, use_unmodified_history=True)
deviate (self, strategy)
return_transform_matrix (self)
player_deviation_reach_probability (self, prior_possible_action_probabilities)
__eq__ (self, other)
__hash__ (self)
Static Public Attributes
local_swap_transform = attr.ib()
prior_actions_weight = attr.ib()
prior_memory_actions = attr.ib()
use_unmodified_history = attr.ib()
Detailed Description
Comprised of a swap transformation.
Comprised of a swap transformation that will be applied at the
current information state, a memory weighting which describes
the actions that are remembered and the memory action history
(prior_memory_actions) that is remembered.
Note that the "memory action history" might not equal the history in
the case of some deviation types (e.g tips deviations).
Definition at line 993 of file efr.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.__init__ (self, target, source, num_actions, prior_actions_weight, prior_memory_actions, is_external, use_unmodified_history = True)
Represents a swap transformation (either external and internal).
Represents a swap transformation (either external and internal) for a given
memory state.
Args:
  target: the action that will be played when the deviation is triggered.
  source: the action that will trigger the target action when suggested
    (used only by internal deviations, i.e is_external = False).
  num_actions: the number of actions that can be played for this
    information state.
  prior_actions_weight: an array (the length of the game history)
    of the information state actions have been forgotten (0)
    or remembered (1) wrt to the memory state.
    This is represented numerically for possible experimentation with
    "partially forgotten" actions (i.e in the range (0,1)).
  prior_memory_actions: the preceeding actions upto the the information
    state (which the LocalDeviationWithTimeSelection is defined with respect
    to).
  is_external: a boolean use to determine whether this is an
    internal or external deviation.
  use_unmodified_history: a boolean used to indicate whether the provided
    memory_actions are the same as the information state it was derived
    from.
Definition at line 1017 of file efr.py.
  ):
    """Represents a swap transformation (either external and internal).
    Represents a swap transformation (either external and internal) for a given
    memory state.
    Args:
      target: the action that will be played when the deviation is triggered.
      source: the action that will trigger the target action when suggested
        (used only by internal deviations, i.e is_external = False).
      num_actions: the number of actions that can be played for this
        information state.
      prior_actions_weight: an array (the length of the game history)
        of the information state actions have been forgotten (0)
        or remembered (1) wrt to the memory state.
        This is represented numerically for possible experimentation with
        "partially forgotten" actions (i.e in the range (0,1)).
      prior_memory_actions: the preceeding actions upto the the information
        state (which the LocalDeviationWithTimeSelection is defined with respect
        to).
      is_external: a boolean use to determine whether this is an
        internal or external deviation.
      use_unmodified_history: a boolean used to indicate whether the provided
        memory_actions are the same as the information state it was derived
        from.
    """
    self.local_swap_transform = LocalSwapTransform(
        target, source, num_actions, is_external=is_external
    )
    self.prior_actions_weight = prior_actions_weight
    self.prior_memory_actions = prior_memory_actions
    self.use_unmodified_history = use_unmodified_history
References open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.local_swap_transform, open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.prior_actions_weight, open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.prior_memory_actions, and open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.use_unmodified_history.
Member Function Documentation
__eq__()
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.__eq__ (self, other)
Definition at line 1128 of file efr.py.
  def __eq__(self, other):
    return self.local_swap_transform == other.local_swap_transform
__hash__()
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.__hash__ (self)
Definition at line 1131 of file efr.py.
  def __hash__(self):
    return hash(self.local_swap_transform)
deviate()
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.deviate (self, strategy)
Returns a strategy array.
Returns the strategy array given by deviating according to the
'self.local_swap_transform.matrix_transform' matrix.
Args:
  strategy: the strategy array to deviate from.
Returns:
  the matrix product of the the matrix_transform and the provided strategy.
Definition at line 1061 of file efr.py.
  def deviate(self, strategy):
    """Returns a strategy array.
    Returns the strategy array given by deviating according to the
    'self.local_swap_transform.matrix_transform' matrix.
    Args:
      strategy: the strategy array to deviate from.
    Returns:
      the matrix product of the the matrix_transform and the provided strategy.
    """
    return self.local_swap_transform.deviate(strategy)
References open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.deviate(), and open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.local_swap_transform.
Referenced by open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.deviate().
player_deviation_reach_probability()
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.player_deviation_reach_probability (self, prior_possible_action_probabilities)
Calculate the probability of reaching the current memory state.
Calculate the probability of reaching the current memory state
provided the player played from the start of the game to this state.
This is assuming that they play with their current strategy with the
deviation applied.
Args:
   prior_possible_action_probabilities: a 2d array of length [player's
     history]x[number of actions at that state]. These are the current
     strategies of the player, from start to end of their history.
Returns:
   The reach probability of the current memory state.
Definition at line 1082 of file efr.py.
  ):
    """Calculate the probability of reaching the current memory state.
    Calculate the probability of reaching the current memory state
    provided the player played from the start of the game to this state.
    This is assuming that they play with their current strategy with the
    deviation applied.
    Args:
       prior_possible_action_probabilities: a 2d array of length [player's
         history]x[number of actions at that state]. These are the current
         strategies of the player, from start to end of their history.
    Returns:
       The reach probability of the current memory state.
    """
    if (
        self.prior_actions_weight is None
        or self.prior_memory_actions is None
        or prior_possible_action_probabilities is None
    ):
      return 1.0
    memory_action_probabilities = np.ones(len(self.prior_actions_weight))
    # Reconstruct memory probabilities from history provided to the deviation
    # to reach info set and the current memory probs.
    memory_weightings = self.prior_actions_weight.copy()
    if self.use_unmodified_history:
      for state in range(len(self.prior_memory_actions)):
        if self.prior_actions_weight[state] != 0:
          memory_action_probabilities[state] = (
              prior_possible_action_probabilities[state][
                  self.prior_memory_actions[state]
              ]
          )
        else:
          memory_action_probabilities[state] = 1
          memory_weightings[state] = 1
    path_probability = np.multiply(
        memory_weightings, memory_action_probabilities
    )
    memory_reach_probability = np.prod(path_probability)
    return memory_reach_probability
References open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.local_swap_transform, open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.prior_actions_weight, open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.prior_memory_actions, and open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.use_unmodified_history.
return_transform_matrix()
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.return_transform_matrix (self)
Returns a matrix_transform.
Returns the matrix_transform of the associated `LocalSwapTransform` object.
Definition at line 1075 of file efr.py.
  def return_transform_matrix(self):
    """Returns a matrix_transform.
    Returns the matrix_transform of the associated `LocalSwapTransform` object.
    """
    return self.local_swap_transform.matrix_transform
References open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.local_swap_transform.
Member Data Documentation
local_swap_transform
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.local_swap_transform = attr.ib() static
Definition at line 1006 of file efr.py.
Referenced by open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.__init__(), open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.deviate(), open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.player_deviation_reach_probability(), and open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.return_transform_matrix().
prior_actions_weight
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.prior_actions_weight = attr.ib() static
Definition at line 1010 of file efr.py.
Referenced by open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.__init__(), and open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.player_deviation_reach_probability().
prior_memory_actions
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.prior_memory_actions = attr.ib() static
Definition at line 1013 of file efr.py.
Referenced by open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.__init__(), and open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.player_deviation_reach_probability().
use_unmodified_history
open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.use_unmodified_history = attr.ib() static
Definition at line 1015 of file efr.py.
Referenced by open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.__init__(), and open_spiel.python.algorithms.efr.LocalDeviationWithTimeSelection.player_deviation_reach_probability().
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/efr.py