open spiel: open_spiel.python.egt.visualization_test.VisualizationTest Class Reference
open_spiel.python.egt.visualization_test.VisualizationTest Class Reference
Public Member Functions
test_meshgrid (self)
test_quiver2x2 (self)
test_streamplot2x2 (self)
test_quiver3x3 (self)
test_streamplot3x3 (self)
Detailed Description
Definition at line 60 of file visualization_test.py.
Member Function Documentation
test_meshgrid()
open_spiel.python.egt.visualization_test.VisualizationTest.test_meshgrid (self)
Definition at line 62 of file visualization_test.py.
  def test_meshgrid(self):
    n = 10
    payoff_tensor = np.ones(shape=(2, 2, 2))
    identity = lambda x, f: x
    allzero = lambda x, f: np.zeros(x.shape)
    dyn = dynamics.MultiPopulationDynamics(payoff_tensor, (identity, allzero))
    x, y, u, v = visualization._eval_dynamics_2x2_grid(dyn, n)
    np.testing.assert_allclose(x, u)
    np.testing.assert_allclose(v, np.zeros(shape=(n, n)))
    dyn = dynamics.MultiPopulationDynamics(payoff_tensor, (allzero, identity))
    x, y, u, v = visualization._eval_dynamics_2x2_grid(dyn, n)
    np.testing.assert_allclose(u, np.zeros(shape=(n, n)))
    np.testing.assert_allclose(y, v)
test_quiver2x2()
open_spiel.python.egt.visualization_test.VisualizationTest.test_quiver2x2 (self)
Test 2x2 quiver plot.
Definition at line 77 of file visualization_test.py.
  def test_quiver2x2(self):
    """Test 2x2 quiver plot."""
    dyn = _build_dynamics2x2()
    fig = Figure(figsize=(4, 4))
    ax = fig.add_subplot(111, projection="2x2")
    res = ax.quiver(dyn)
    self.assertIsInstance(res, Quiver)
References open_spiel.python.egt.visualization_test._build_dynamics2x2().
test_quiver3x3()
open_spiel.python.egt.visualization_test.VisualizationTest.test_quiver3x3 (self)
Test 3x3 quiver plot.
Definition at line 93 of file visualization_test.py.
  def test_quiver3x3(self):
    """Test 3x3 quiver plot."""
    dyn = _build_dynamics3x3()
    fig = Figure(figsize=(4, 4))
    ax = fig.add_subplot(111, projection="3x3")
    res = ax.quiver(dyn)
    self.assertIsInstance(res, Quiver)
References open_spiel.python.egt.visualization_test._build_dynamics3x3().
test_streamplot2x2()
open_spiel.python.egt.visualization_test.VisualizationTest.test_streamplot2x2 (self)
Test 2x2 quiver plot.
Definition at line 85 of file visualization_test.py.
  def test_streamplot2x2(self):
    """Test 2x2 quiver plot."""
    dyn = _build_dynamics2x2()
    fig = Figure(figsize=(4, 4))
    ax = fig.add_subplot(111, projection="2x2")
    res = ax.streamplot(dyn)
    self.assertIsInstance(res, StreamplotSet)
References open_spiel.python.egt.visualization_test._build_dynamics2x2().
test_streamplot3x3()
open_spiel.python.egt.visualization_test.VisualizationTest.test_streamplot3x3 (self)
Test 3x3 quiver plot.
Definition at line 101 of file visualization_test.py.
  def test_streamplot3x3(self):
    """Test 3x3 quiver plot."""
    dyn = _build_dynamics3x3()
    fig = Figure(figsize=(4, 4))
    ax = fig.add_subplot(111, projection="3x3")
    res = ax.streamplot(dyn)
    self.assertIsInstance(res, visualization.SimplexStreamMask)
References open_spiel.python.egt.visualization_test._build_dynamics3x3().
The documentation for this class was generated from the following file:
open_spiel/python/egt/visualization_test.py