open spiel: open_spiel.python.bots.bluechip_bridge_uncontested_bidding Namespace Reference
open_spiel.python.bots.bluechip_bridge_uncontested_bidding Namespace Reference
Classes
class BlueChipBridgeBot
Functions
_string_to_action (call_str)
_action_to_string (action)
_expect_regex (client, regex)
_expect (client, expected)
_hand_string (state_vec)
_actions (state_vec)
_connect (client, seat, state_vec)
Variables
str _CONNECT = 'Connecting "(?P<client_name>.*)" as ANYPL using protocol version 18'
str _SELF_BID_OR_PASS = "{seat} ((?P<pass>PASSES)|bids (?P<bid>[^ ]*))(Alert.)?"
str _READY_FOR_TEAMS = "{seat} ready for teams"
str _READY_TO_START = "{seat} ready to start"
str _READY_FOR_DEAL = "{seat} ready for deal"
str _READY_FOR_CARDS = "{seat} ready for cards"
str _READY_FOR_BID = "{seat} ready for {other}'s bid"
str _SEATED = '{seat} ("{client_name}") seated'
str _TEAMS = 'Teams: N/S "opponents" E/W "bidders"'
str _START_BOARD = "start of board"
str _DEAL = "Board number 8. Dealer WEST. Neither vulnerable."
str _CARDS = "{seat}'s cards: {hand}"
str _OTHER_PLAYER_PASS = "{player} PASSES"
str _OTHER_PLAYER_BID = "{player} bids {bid}"
list _SEATS = ["WEST", "EAST"]
list _OPPONENTS = ["NORTH", "SOUTH"]
list _TRUMP_SUIT = ["C", "D", "H", "S", "NT"]
_NUMBER_TRUMP_SUITS = len(_TRUMP_SUIT)
list _RANKS = ["2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K", "A"]
int _PASS_ACTION = 0
Detailed Description
Wraps third-party bridge bots to make them usable in OpenSpiel.
This code enables OpenSpiel interoperation for bots which implement the BlueChip
bridge protocol. This is widely used, e.g. in the World computer bridge
championships. For a rough outline of the protocol, see:
http://www.bluechipbridge.co.uk/protocol.htm
No formal specification is available. This implementation has been verified
to work correctly with WBridge5.
This bot controls a single player in the game of uncontested bridge bidding. It
chooses its actions by invoking an external bot which plays the full game of
bridge. This means that each time the bot is asked for an action, it sends up to
three actions (forced passes from both opponents, plus partner's most recent
action) to the external bridge bot, and obtains an action in return.
Since we are restricting ourselves to the uncontested bidding game, we have
no support for Doubling, Redoubling, or the play of the cards.
Function Documentation
_action_to_string()
open_spiel.python.bots.bluechip_bridge_uncontested_bidding._action_to_string (action) protected
Converts OpenSpiel action id (an integer) to a BlueChip bid string.
Args:
  action: an integer action id corresponding to a bid.
Returns:
  A string in BlueChip format.
Inverse of `_string_to_action`. See documentation there.
Definition at line 110 of file bluechip_bridge_uncontested_bidding.py.
def _action_to_string(action):
  """Converts OpenSpiel action id (an integer) to a BlueChip bid string.
  Args:
    action: an integer action id corresponding to a bid.
  Returns:
    A string in BlueChip format.
  Inverse of `_string_to_action`. See documentation there.
  """
  level = str((action - 1) // _NUMBER_TRUMP_SUITS + 1)
  trumps = _TRUMP_SUIT[(action - 1) % _NUMBER_TRUMP_SUITS]
  return level + trumps
Referenced by open_spiel.python.bots.bluechip_bridge_uncontested_bidding.BlueChipBridgeBot.step().
_actions()
open_spiel.python.bots.bluechip_bridge_uncontested_bidding._actions (state_vec) protected
Returns the player actions that have been taken in the game so far.
Definition at line 159 of file bluechip_bridge_uncontested_bidding.py.
def _actions(state_vec):
  """Returns the player actions that have been taken in the game so far."""
  # See UncontestedBiddingState::InformationStateTensor
  # The first 52 elements are the cards held, then two elements for each
  # possible action, specifying which of the two players has taken it (if
  # either player has). Then two elements specifying which player we are.
  actions = state_vec[52:-2]
  return [index // 2 for index, value in enumerate(actions) if value]
Referenced by open_spiel.python.bots.bluechip_bridge_uncontested_bidding.BlueChipBridgeBot.step().
_connect()
open_spiel.python.bots.bluechip_bridge_uncontested_bidding._connect (client, seat, state_vec) protected
Performs the initial handshake with a BlueChip bot.
Definition at line 169 of file bluechip_bridge_uncontested_bidding.py.
def _connect(client, seat, state_vec):
  """Performs the initial handshake with a BlueChip bot."""
  client.start()
  client_name = _expect_regex(client, _CONNECT)["client_name"]
  client.send_line(_SEATED.format(seat=seat, client_name=client_name))
  _expect(client, _READY_FOR_TEAMS.format(seat=seat))
  client.send_line(_TEAMS)
  _expect(client, _READY_TO_START.format(seat=seat))
  client.send_line(_START_BOARD)
  _expect(client, _READY_FOR_DEAL.format(seat=seat))
  client.send_line(_DEAL)
  _expect(client, _READY_FOR_CARDS.format(seat=seat))
  client.send_line(_CARDS.format(seat=seat, hand=_hand_string(state_vec)))
References open_spiel.python.bots.bluechip_bridge_uncontested_bidding._expect(), open_spiel.python.bots.bluechip_bridge_uncontested_bidding._expect_regex(), and open_spiel.python.bots.bluechip_bridge_uncontested_bidding._hand_string().
Referenced by open_spiel.python.bots.bluechip_bridge_uncontested_bidding.BlueChipBridgeBot.step().
_expect()
open_spiel.python.bots.bluechip_bridge_uncontested_bidding._expect (client, expected) protected
Reads a line from the client, checks it matches expected line exactly.
Definition at line 136 of file bluechip_bridge_uncontested_bidding.py.
def _expect(client, expected):
  """Reads a line from the client, checks it matches expected line exactly."""
  line = client.read_line()
  if expected != line:
    raise ValueError("Received '{}' but expected '{}'".format(line, expected))
Referenced by open_spiel.python.bots.bluechip_bridge_uncontested_bidding._connect(), and open_spiel.python.bots.bluechip_bridge_uncontested_bidding.BlueChipBridgeBot.step().
_expect_regex()
open_spiel.python.bots.bluechip_bridge_uncontested_bidding._expect_regex (client, regex) protected
Reads a line from the client, parses it using the regular expression.
Definition at line 126 of file bluechip_bridge_uncontested_bidding.py.
def _expect_regex(client, regex):
  """Reads a line from the client, parses it using the regular expression."""
  line = client.read_line()
  match = re.match(regex, line)
  if not match:
    raise ValueError("Received '{}' which does not match regex '{}'".format(
        line, regex))
  return match.groupdict()
Referenced by open_spiel.python.bots.bluechip_bridge_uncontested_bidding._connect(), and open_spiel.python.bots.bluechip_bridge_uncontested_bidding.BlueChipBridgeBot.step().
_hand_string()
open_spiel.python.bots.bluechip_bridge_uncontested_bidding._hand_string (state_vec) protected
Returns the hand of the to-play player in the state in BlueChip format.
Definition at line 143 of file bluechip_bridge_uncontested_bidding.py.
def _hand_string(state_vec):
  """Returns the hand of the to-play player in the state in BlueChip format."""
  # See UncontestedBiddingState::InformationStateTensor
  # The first 52 elements are whether or not we hold the given card (cards
  # ordered suit-by-suit, in ascending order of rank).
  suits = []
  for suit in reversed(range(4)):
    cards = []
    for rank in reversed(range(13)):
      if state_vec[rank * 4 + suit]:
        cards.append(_RANKS[rank])
    suits.append(_TRUMP_SUIT[suit] + " " + (" ".join(cards) if cards else "-") +
                 ".")
  return " ".join(suits)
Referenced by open_spiel.python.bots.bluechip_bridge_uncontested_bidding._connect().
_string_to_action()
open_spiel.python.bots.bluechip_bridge_uncontested_bidding._string_to_action (call_str) protected
Converts a BlueChip bid string to an OpenSpiel action id (an integer).
Args:
  call_str: string representing a bid in the BlueChip format, i.e. "[level]
    (as a digit) + [trump suit (S, H, D, C or NT)]", e.g. "1C".
Returns:
  An integer action id - see `bridge_uncontested_bidding.cc`, functions
  `Denomination` and `Level`.
  0 is reserved for Pass, so bids are in order from 1 upwards: 1 = 1C,
  2 = 1D, etc.
Definition at line 92 of file bluechip_bridge_uncontested_bidding.py.
def _string_to_action(call_str):
  """Converts a BlueChip bid string to an OpenSpiel action id (an integer).
  Args:
    call_str: string representing a bid in the BlueChip format, i.e. "[level]
      (as a digit) + [trump suit (S, H, D, C or NT)]", e.g. "1C".
  Returns:
    An integer action id - see `bridge_uncontested_bidding.cc`, functions
    `Denomination` and `Level`.
    0 is reserved for Pass, so bids are in order from 1 upwards: 1 = 1C,
    2 = 1D, etc.
  """
  level = int(call_str[0])
  trumps = _TRUMP_SUIT.index(call_str[1:])
  return (level - 1) * _NUMBER_TRUMP_SUITS + trumps + 1
Referenced by open_spiel.python.bots.bluechip_bridge_uncontested_bidding.BlueChipBridgeBot.step().
Variable Documentation
_CARDS
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._CARDS = "{seat}'s cards: {hand}" protected
Definition at line 77 of file bluechip_bridge_uncontested_bidding.py.
_CONNECT
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._CONNECT = 'Connecting "(?P<client_name>.*)" as ANYPL using protocol version 18' protected
Definition at line 59 of file bluechip_bridge_uncontested_bidding.py.
_DEAL
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._DEAL = "Board number 8. Dealer WEST. Neither vulnerable." protected
Definition at line 76 of file bluechip_bridge_uncontested_bidding.py.
_NUMBER_TRUMP_SUITS
open_spiel.python.bots.bluechip_bridge_uncontested_bidding._NUMBER_TRUMP_SUITS = len(_TRUMP_SUIT) protected
Definition at line 85 of file bluechip_bridge_uncontested_bidding.py.
_OPPONENTS
list open_spiel.python.bots.bluechip_bridge_uncontested_bidding._OPPONENTS = ["NORTH", "SOUTH"] protected
Definition at line 83 of file bluechip_bridge_uncontested_bidding.py.
_OTHER_PLAYER_BID
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._OTHER_PLAYER_BID = "{player} bids {bid}" protected
Definition at line 79 of file bluechip_bridge_uncontested_bidding.py.
_OTHER_PLAYER_PASS
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._OTHER_PLAYER_PASS = "{player} PASSES" protected
Definition at line 78 of file bluechip_bridge_uncontested_bidding.py.
_PASS_ACTION
int open_spiel.python.bots.bluechip_bridge_uncontested_bidding._PASS_ACTION = 0 protected
Definition at line 89 of file bluechip_bridge_uncontested_bidding.py.
_RANKS
list open_spiel.python.bots.bluechip_bridge_uncontested_bidding._RANKS = ["2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K", "A"] protected
Definition at line 86 of file bluechip_bridge_uncontested_bidding.py.
_READY_FOR_BID
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._READY_FOR_BID = "{seat} ready for {other}'s bid" protected
Definition at line 67 of file bluechip_bridge_uncontested_bidding.py.
_READY_FOR_CARDS
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._READY_FOR_CARDS = "{seat} ready for cards" protected
Definition at line 66 of file bluechip_bridge_uncontested_bidding.py.
_READY_FOR_DEAL
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._READY_FOR_DEAL = "{seat} ready for deal" protected
Definition at line 65 of file bluechip_bridge_uncontested_bidding.py.
_READY_FOR_TEAMS
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._READY_FOR_TEAMS = "{seat} ready for teams" protected
Definition at line 63 of file bluechip_bridge_uncontested_bidding.py.
_READY_TO_START
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._READY_TO_START = "{seat} ready to start" protected
Definition at line 64 of file bluechip_bridge_uncontested_bidding.py.
_SEATED
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._SEATED = '{seat} ("{client_name}") seated' protected
Definition at line 70 of file bluechip_bridge_uncontested_bidding.py.
_SEATS
list open_spiel.python.bots.bluechip_bridge_uncontested_bidding._SEATS = ["WEST", "EAST"] protected
Definition at line 82 of file bluechip_bridge_uncontested_bidding.py.
_SELF_BID_OR_PASS
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._SELF_BID_OR_PASS = "{seat} ((?P<pass>PASSES)|bids (?P<bid>[^ ]*))(Alert.)?" protected
Definition at line 60 of file bluechip_bridge_uncontested_bidding.py.
_START_BOARD
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._START_BOARD = "start of board" protected
Definition at line 72 of file bluechip_bridge_uncontested_bidding.py.
_TEAMS
str open_spiel.python.bots.bluechip_bridge_uncontested_bidding._TEAMS = 'Teams: N/S "opponents" E/W "bidders"' protected
Definition at line 71 of file bluechip_bridge_uncontested_bidding.py.
_TRUMP_SUIT
list open_spiel.python.bots.bluechip_bridge_uncontested_bidding._TRUMP_SUIT = ["C", "D", "H", "S", "NT"] protected
Definition at line 84 of file bluechip_bridge_uncontested_bidding.py.