open spiel: absl::container_internal::FlatHashMapPolicy< K, V > Struct Template Reference
absl::container_internal::FlatHashMapPolicy< K, V > Struct Template Reference
Public Types
using slot_policy = container_internal::map_slot_policy<K, V>
using slot_type = typename slot_policy::slot_type
using key_type = K
using mapped_type = V
using init_type = std::pair< key_type, mapped_type>
Static Public Member Functions
template<class Allocator , class... Args>
static void construct (Allocator *alloc, slot_type *slot, Args &&... args)
template<class Allocator >
static void destroy (Allocator *alloc, slot_type *slot)
template<class Allocator >
static void transfer (Allocator *alloc, slot_type *new_slot, slot_type *old_slot)
template<class F , class... Args>
static decltype(absl::container_internal::DecomposePair(std::declval< F >(), std::declval< Args >()...)) apply (F &&f, Args &&... args)
static size_t space_used (const slot_type *)
static std::pair< const K, V > & element (slot_type *slot)
static V & value (std::pair< const K, V > *kv)
static const V & value (const std::pair< const K, V > *kv)
Detailed Description
template<class K, class V>
struct absl::container_internal::FlatHashMapPolicy< K, V >
Definition at line 560 of file flat_hash_map.h.
Member Typedef Documentation
init_type
template<class K , class V > using absl::container_internal::FlatHashMapPolicy< K, V >::init_type = std::pair< key_type, mapped_type>
Definition at line 565 of file flat_hash_map.h.
key_type
template<class K , class V > using absl::container_internal::FlatHashMapPolicy< K, V >::key_type = K
Definition at line 563 of file flat_hash_map.h.
mapped_type
template<class K , class V > using absl::container_internal::FlatHashMapPolicy< K, V >::mapped_type = V
Definition at line 564 of file flat_hash_map.h.
slot_policy
template<class K , class V > using absl::container_internal::FlatHashMapPolicy< K, V >::slot_policy = container_internal::map_slot_policy<K, V>
Definition at line 561 of file flat_hash_map.h.
slot_type
template<class K , class V > using absl::container_internal::FlatHashMapPolicy< K, V >::slot_type = typename slot_policy::slot_type
Definition at line 562 of file flat_hash_map.h.
Member Function Documentation
apply()
template<class K , class V > template<class F , class... Args> static decltype(absl::container_internal::DecomposePair(std::declval< F >(), std::declval< Args >()...)) absl::container_internal::FlatHashMapPolicy< K, V >::apply (F && f, Args &&... args) inline static
Definition at line 586 of file flat_hash_map.h.
{
    return absl::container_internal::DecomposePair(std::forward<F>(f),
                                                   std::forward<Args>(args)...);
  }
construct()
template<class K , class V > template<class Allocator , class... Args> static void absl::container_internal::FlatHashMapPolicy< K, V >::construct (Allocator * alloc, slot_type * slot, Args &&... args) inline static
Definition at line 568 of file flat_hash_map.h.
{
    slot_policy::construct(alloc, slot, std::forward<Args>(args)...);
  }
destroy()
template<class K , class V > template<class Allocator > static void absl::container_internal::FlatHashMapPolicy< K, V >::destroy (Allocator * alloc, slot_type * slot) inline static
Definition at line 573 of file flat_hash_map.h.
{
    slot_policy::destroy(alloc, slot);
  }
element()
template<class K , class V > static std::pair< const K, V > & absl::container_internal::FlatHashMapPolicy< K, V >::element (slot_type * slot) inline static
Definition at line 593 of file flat_hash_map.h.
{ return slot->value; }
space_used()
template<class K , class V > static size_t absl::container_internal::FlatHashMapPolicy< K, V >::space_used (const slot_type *) inline static
Definition at line 591 of file flat_hash_map.h.
{ return 0; }
transfer()
template<class K , class V > template<class Allocator > static void absl::container_internal::FlatHashMapPolicy< K, V >::transfer (Allocator * alloc, slot_type * new_slot, slot_type * old_slot) inline static
Definition at line 578 of file flat_hash_map.h.
{
    slot_policy::transfer(alloc, new_slot, old_slot);
  }
value() [1/2]
template<class K , class V > static const V & absl::container_internal::FlatHashMapPolicy< K, V >::value (const std::pair< const K, V > * kv) inline static
Definition at line 596 of file flat_hash_map.h.
{ return kv->second; }
Referenced by open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::__init__(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::__init__(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), and open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value().
value() [2/2]
template<class K , class V > static V & absl::container_internal::FlatHashMapPolicy< K, V >::value (std::pair< const K, V > * kv) inline static
Definition at line 595 of file flat_hash_map.h.
{ return kv->second; }
Referenced by open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::__init__(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::__init__(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), and open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/flat_hash_map.h