open spiel: absl::strings_internal::StringConstant< T > Struct Template Reference
absl::strings_internal::StringConstant< T > Struct Template Reference
Public Member Functions
constexpr absl::string_view operator() () const
Static Public Attributes
static constexpr absl::string_view value = T{}()
Detailed Description
template<typename T>
struct absl::strings_internal::StringConstant< T >
Definition at line 37 of file string_constant.h.
Member Function Documentation
operator()()
template<typename T > absl::string_view absl::strings_internal::StringConstant< T >::operator() () const inline constexpr
Definition at line 45 of file string_constant.h.
{ return value; }
Member Data Documentation
value
template<typename T > absl::string_view absl::strings_internal::StringConstant< T >::value = T{}() static constexpr
Definition at line 44 of file string_constant.h.
{}();
Referenced by open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::__init__(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::__init__(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), and open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/string_constant.h