open spiel: absl::random_internal::randen_engine< T > Class Template Reference
absl::random_internal::randen_engine< T > Class Template Reference
Public Types
using result_type = T
Public Member Functions
randen_engine (result_type seed_value)
template<class SeedSequence , typename = typename absl::enable_if_t< !std::is_same<SeedSequence, randen_engine>::value>>
randen_engine (SeedSequence &&seq)
randen_engine (const randen_engine &other)
randen_engine & operator= (const randen_engine &other)
result_type operator() ()
template<class SeedSequence >
absl::enable_if_t< !std::is_convertible< SeedSequence, result_type >::value > seed (SeedSequence &&seq)
void seed (result_type seed_value=0)
template<class SeedSequence >
void reseed (SeedSequence &seq)
void discard (uint64_t count)
bool operator== (const randen_engine &other) const
bool operator!= (const randen_engine &other) const
Static Public Member Functions
static constexpr result_type min ()
static constexpr result_type max ()
Friends
template<class CharT , class Traits >
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &os, const randen_engine< T > &engine)
template<class CharT , class Traits >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &is, randen_engine< T > &engine)
Detailed Description
template<typename T>
class absl::random_internal::randen_engine< T >
Definition at line 45 of file randen_engine.h.
Member Typedef Documentation
result_type
template<typename T > using absl::random_internal::randen_engine< T >::result_type = T
Definition at line 48 of file randen_engine.h.
Constructor & Destructor Documentation
randen_engine() [1/4]
template<typename T > absl::random_internal::randen_engine< T >::randen_engine () inline
Definition at line 61 of file randen_engine.h.
: randen_engine(0) {}
randen_engine() [2/4]
template<typename T > absl::random_internal::randen_engine< T >::randen_engine (result_type seed_value) inline explicit
Definition at line 62 of file randen_engine.h.
{ seed(seed_value); }
randen_engine() [3/4]
template<typename T > template<class SeedSequence , typename = typename absl::enable_if_t< !std::is_same<SeedSequence, randen_engine>::value>> absl::random_internal::randen_engine< T >::randen_engine (SeedSequence && seq) inline explicit
Definition at line 67 of file randen_engine.h.
{
    seed(seq);
  }
randen_engine() [4/4]
template<typename T > absl::random_internal::randen_engine< T >::randen_engine (const randen_engine< T > & other) inline
Definition at line 72 of file randen_engine.h.
      : next_(other.next_), impl_(other.impl_) {
    std::memcpy(state(), other.state(), kStateSizeT * sizeof(result_type));
  }
Member Function Documentation
discard()
template<typename T > void absl::random_internal::randen_engine< T >::discard (uint64_t count) inline
Definition at line 168 of file randen_engine.h.
{
    uint64_t step = std::min<uint64_t>(kStateSizeT - next_, count);
    count -= step;
    constexpr uint64_t kRateT = kStateSizeT - kCapacityT;
    auto* begin = state();
    while (count > 0) {
      next_ = kCapacityT;
      impl_.Generate(*reinterpret_cast<result_type(*)[kStateSizeT]>(begin));
      step = std::min<uint64_t>(kRateT, count);
      count -= step;
    }
    next_ += step;
  }
max()
template<typename T > static constexpr result_type absl::random_internal::randen_engine< T >::max () inline static constexpr
Definition at line 57 of file randen_engine.h.
{
    return (std::numeric_limits<result_type>::max)();
  }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
min()
template<typename T > static constexpr result_type absl::random_internal::randen_engine< T >::min () inline static constexpr
Definition at line 53 of file randen_engine.h.
{
    return (std::numeric_limits<result_type>::min)();
  }
Referenced by open_spiel.python.utils.stats.BasicStats::std_dev().
operator!=()
template<typename T > bool absl::random_internal::randen_engine< T >::operator!= (const randen_engine< T > & other) const inline
Definition at line 189 of file randen_engine.h.
{
    return !(*this == other);
  }
operator()()
template<typename T > result_type absl::random_internal::randen_engine< T >::operator() () inline
Definition at line 84 of file randen_engine.h.
{
    // Refill the buffer if needed (unlikely).
    auto* begin = state();
    if (next_ >= kStateSizeT) {
      next_ = kCapacityT;
      impl_.Generate(begin);
    }
    return little_endian::ToHost(begin[next_++]);
  }
operator=()
template<typename T > randen_engine & absl::random_internal::randen_engine< T >::operator= (const randen_engine< T > & other) inline
Definition at line 76 of file randen_engine.h.
{
    next_ = other.next_;
    impl_ = other.impl_;
    std::memcpy(state(), other.state(), kStateSizeT * sizeof(result_type));
    return *this;
  }
operator==()
template<typename T > bool absl::random_internal::randen_engine< T >::operator== (const randen_engine< T > & other) const inline
Definition at line 183 of file randen_engine.h.
{
    const auto* begin = state();
    return next_ == other.next_ &&
           std::equal(begin, begin + kStateSizeT, other.state());
  }
reseed()
template<typename T > template<class SeedSequence > void absl::random_internal::randen_engine< T >::reseed (SeedSequence & seq) inline
Definition at line 116 of file randen_engine.h.
{
    using sequence_result_type = typename SeedSequence::result_type;
    static_assert(sizeof(sequence_result_type) == 4,
                  "SeedSequence::result_type must be 32-bit");
    constexpr size_t kBufferSize =
        Randen::kSeedBytes / sizeof(sequence_result_type);
    alignas(16) sequence_result_type buffer[kBufferSize];
    // Randen::Absorb XORs the seed into state, which is then mixed by a call
    // to Randen::Generate. Seeding with only the provided entropy is preferred
    // to using an arbitrary generate() call, so use [rand.req.seed_seq]
    // size as a proxy for the number of entropy units that can be generated
    // without relying on seed sequence mixing...
    const size_t entropy_size = seq.size();
    if (entropy_size < kBufferSize) {
      // ... and only request that many values, or 256-bits, when unspecified.
      const size_t requested_entropy = (entropy_size == 0) ? 8u : entropy_size;
      std::fill(buffer + requested_entropy, buffer + kBufferSize, 0);
      seq.generate(buffer, buffer + requested_entropy);
#ifdef ABSL_IS_BIG_ENDIAN
      // Randen expects the seed buffer to be in Little Endian; reverse it on
      // Big Endian platforms.
      for (sequence_result_type& e : buffer) {
        e = absl::little_endian::FromHost(e);
      }
#endif
      // The Randen paper suggests preferentially initializing even-numbered
      // 128-bit vectors of the randen state (there are 16 such vectors).
      // The seed data is merged into the state offset by 128-bits, which
      // implies prefering seed bytes [16..31, ..., 208..223]. Since the
      // buffer is 32-bit values, we swap the corresponding buffer positions in
      // 128-bit chunks.
      size_t dst = kBufferSize;
      while (dst > 7) {
        // leave the odd bucket as-is.
        dst -= 4;
        size_t src = dst >> 1;
        // swap 128-bits into the even bucket
        std::swap(buffer[--dst], buffer[--src]);
        std::swap(buffer[--dst], buffer[--src]);
        std::swap(buffer[--dst], buffer[--src]);
        std::swap(buffer[--dst], buffer[--src]);
      }
    } else {
      seq.generate(buffer, buffer + kBufferSize);
    }
    impl_.Absorb(buffer, state());
    // Generate will be called when operator() is called
    next_ = kStateSizeT;
  }
seed() [1/2]
template<typename T > void absl::random_internal::randen_engine< T >::seed (result_type seed_value = 0) inline
Definition at line 103 of file randen_engine.h.
{
    next_ = kStateSizeT;
    // Zeroes the inner state and fills the outer state with seed_value to
    // mimic the behaviour of reseed
    auto* begin = state();
    std::fill(begin, begin + kCapacityT, 0);
    std::fill(begin + kCapacityT, begin + kStateSizeT, seed_value);
  }
Referenced by open_spiel.python.algorithms.adidas_utils.games.big.TensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::__init__(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.small.MatrixGame::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.nonsymmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.symmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal_noaux.Solver::__init__(), and open_spiel.python.algorithms.adidas_utils.solvers.symmetric.regmatch.Solver::__init__().
seed() [2/2]
template<typename T > template<class SeedSequence > absl::enable_if_t< !std::is_convertible< SeedSequence, result_type >::value > absl::random_internal::randen_engine< T >::seed (SeedSequence && seq) inline
Definition at line 97 of file randen_engine.h.
{
    // Zeroes the state.
    seed();
    reseed(seq);
  }
Referenced by open_spiel.python.algorithms.adidas_utils.games.big.TensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::__init__(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.games.small.MatrixGame::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.nonsymmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.symmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal_noaux.Solver::__init__(), and open_spiel.python.algorithms.adidas_utils.solvers.symmetric.regmatch.Solver::__init__().
Friends And Related Symbol Documentation
operator<<
template<typename T > template<class CharT , class Traits > std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > & os, const randen_engine< T > & engine) friend
Definition at line 194 of file randen_engine.h.
                                      {       // NOLINT(runtime/references)
    using numeric_type =
        typename random_internal::stream_format_type<result_type>::type;
    auto saver = random_internal::make_ostream_state_saver(os);
    auto* it = engine.state();
    for (auto* end = it + kStateSizeT; it < end; ++it) {
      // In the case that `elem` is `uint8_t`, it must be cast to something
      // larger so that it prints as an integer rather than a character. For
      // simplicity, apply the cast all circumstances.
      os << static_cast<numeric_type>(little_endian::FromHost(*it))
         << os.fill();
    }
    os << engine.next_;
    return os;
  }
operator>>
template<typename T > template<class CharT , class Traits > std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > & is, randen_engine< T > & engine) friend
Definition at line 213 of file randen_engine.h.
                                {             // NOLINT(runtime/references)
    using numeric_type =
        typename random_internal::stream_format_type<result_type>::type;
    result_type state[kStateSizeT];
    size_t next;
    for (auto& elem : state) {
      // It is not possible to read uint8_t from wide streams, so it is
      // necessary to read a wider type and then cast it to uint8_t.
      numeric_type value;
      is >> value;
      elem = little_endian::ToHost(static_cast<result_type>(value));
    }
    is >> next;
    if (is.fail()) {
      return is;
    }
    std::memcpy(engine.state(), state, sizeof(state));
    engine.next_ = next;
    return is;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/internal/randen_engine.h