open spiel: open_spiel.python.games.atari.NoopResetEnv Class Reference
open_spiel.python.games.atari.NoopResetEnv Class Reference
Public Member Functions
__init__ (self, gym.Env env, int noop_max=30)
np.ndarray reset (self, **kwargs)
Public Attributes
noop_max
override_num_noops
noop_action
Detailed Description
Sample initial states by taking random number of no-ops on reset.
No-op is assumed to be action 0. :param env: the environment to wrap :param
noop_max: the maximum value of no-ops to run
Definition at line 70 of file atari.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.games.atari.NoopResetEnv.__init__ (self, gym.Env env, int noop_max = 30)
Definition at line 77 of file atari.py.
  def __init__(self, env: gym.Env, noop_max: int = 30):
    gym.Wrapper.__init__(self, env)
    self.noop_max = noop_max
    self.override_num_noops = None
    self.noop_action = 0
    assert env.unwrapped.get_action_meanings()[0] == 'NOOP'
Member Function Documentation
reset()
np.ndarray open_spiel.python.games.atari.NoopResetEnv.reset (self, ** kwargs)
Definition at line 84 of file atari.py.
  def reset(self, **kwargs) -> np.ndarray:
    self.env.reset(**kwargs)
    if self.override_num_noops is not None:
      noops = self.override_num_noops
    else:
      noops = self.unwrapped.np_random.integers(1, self.noop_max + 1)
    assert noops > 0
    obs = np.zeros(0)
    for _ in range(noops):
      obs, _, done, _ = self.env.step(self.noop_action)
      if done:
        obs = self.env.reset(**kwargs)
    return obs
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear.__init__(), open_spiel.python.environments.catch.Environment.step(), open_spiel.python.environments.cliff_walking.Environment.step(), open_spiel.python.rl_environment.Environment.step(), and open_spiel.python.vector_env.SyncVectorEnv.step().
Member Data Documentation
noop_action
open_spiel.python.games.atari.NoopResetEnv.noop_action
Definition at line 81 of file atari.py.
noop_max
open_spiel.python.games.atari.NoopResetEnv.noop_max
Definition at line 79 of file atari.py.
override_num_noops
open_spiel.python.games.atari.NoopResetEnv.override_num_noops
Definition at line 80 of file atari.py.
The documentation for this class was generated from the following file:
open_spiel/python/games/atari.py