open spiel: open_spiel.python.games.chat_games.utils.logging_utils.ColorText Class Reference
open_spiel.python.games.chat_games.utils.logging_utils.ColorText Class Reference
Public Member Functions
__init__ (self, reset_color=RESET)
set_color (self, str color)
set_reset_color (self, str color)
reset (self)
color (self, str log_str, str color='')
Public Attributes
reset_color
current_color
Detailed Description
Color text class.
Definition at line 29 of file logging_utils.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.games.chat_games.utils.logging_utils.ColorText.__init__ (self, reset_color = RESET)
Definition at line 32 of file logging_utils.py.
  def __init__(self, reset_color=RESET):
    self.reset_color = reset_color
    self.current_color = reset_color
Member Function Documentation
color()
open_spiel.python.games.chat_games.utils.logging_utils.ColorText.color (self, str log_str, str color = '')
Definition at line 45 of file logging_utils.py.
  def color(self, log_str: str, color: str = ''):
    c = color if color else self.current_color
    log_str = c + log_str + self.reset_color
    return log_str
reset()
open_spiel.python.games.chat_games.utils.logging_utils.ColorText.reset (self)
Definition at line 42 of file logging_utils.py.
  def reset(self):
    self.current_color = self.reset_color
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear.__init__(), open_spiel.python.environments.catch.Environment.step(), open_spiel.python.environments.cliff_walking.Environment.step(), open_spiel.python.rl_environment.Environment.step(), and open_spiel.python.vector_env.SyncVectorEnv.step().
set_color()
open_spiel.python.games.chat_games.utils.logging_utils.ColorText.set_color (self, str color)
Definition at line 36 of file logging_utils.py.
  def set_color(self, color: str):
    self.current_color = color
set_reset_color()
open_spiel.python.games.chat_games.utils.logging_utils.ColorText.set_reset_color (self, str color)
Definition at line 39 of file logging_utils.py.
  def set_reset_color(self, color: str):
    self.reset_color = color
Member Data Documentation
current_color
open_spiel.python.games.chat_games.utils.logging_utils.ColorText.current_color
Definition at line 34 of file logging_utils.py.
reset_color
open_spiel.python.games.chat_games.utils.logging_utils.ColorText.reset_color
Definition at line 33 of file logging_utils.py.
The documentation for this class was generated from the following file:
open_spiel/python/games/chat_games/utils/logging_utils.py