open spiel: open_spiel.python.examples.bridge_supervised_learning Namespace Reference
open_spiel.python.examples.bridge_supervised_learning Namespace Reference
Functions
_no_play_trajectory (str line)
make_dataset (str file)
batch (dataset, int batch_size)
one_hot (x, k)
net_fn (x)
main (argv)
Variables
OptState = Any
Params = Any
FLAGS = flags.FLAGS
GAME = pyspiel.load_game('bridge(use_double_dummy_result=false)')
int NUM_ACTIONS = 38
int MIN_ACTION = 52
int NUM_CARDS = 52
int NUM_PLAYERS = 4
int TOP_K_ACTIONS = 5
Detailed Description
Train a policy net on bridge bidding based on a dataset of trajectories.
Suitable data for training, generated by WBridge5, may be downloaded from:
https://console.cloud.google.com/storage/browser/openspiel-data/bridge
Function Documentation
_no_play_trajectory()
open_spiel.python.examples.bridge_supervised_learning._no_play_trajectory (str line) protected
Returns the deal and bidding actions only given a text trajectory.
Definition at line 58 of file bridge_supervised_learning.py.
def _no_play_trajectory(line: str):
  """Returns the deal and bidding actions only given a text trajectory."""
  actions = [int(x) for x in line.split(' ')]
  # Usually a trajectory is NUM_CARDS chance events for the deal, plus one
  # action for every bid of the auction, plus NUM_CARDS actions for the play
  # phase. Exceptionally, if all NUM_PLAYERS players Pass, there is no play
  # phase and the trajectory is just of length NUM_CARDS + NUM_PLAYERS.
  if len(actions) == NUM_CARDS + NUM_PLAYERS:
    return tuple(actions)
  else:
    return tuple(actions[:-NUM_CARDS])
Referenced by open_spiel.python.examples.bridge_supervised_learning.make_dataset(), and open_spiel.python.examples.bridge_supervised_learning.net_fn().
batch()
open_spiel.python.examples.bridge_supervised_learning.batch (dataset, int batch_size)
Creates a batched dataset from a one-at-a-time dataset.
Definition at line 84 of file bridge_supervised_learning.py.
def batch(dataset, batch_size: int):
  """Creates a batched dataset from a one-at-a-time dataset."""
  observations = np.zeros([batch_size] + GAME.observation_tensor_shape(),
                          np.float32)
  labels = np.zeros(batch_size, dtype=np.int32)
  while True:
    for batch_index in range(batch_size):
      observations[batch_index], labels[batch_index] = next(dataset)
    yield observations, labels
Referenced by open_spiel.python.examples.bridge_supervised_learning.net_fn().
main()
open_spiel.python.examples.bridge_supervised_learning.main (argv)
Definition at line 117 of file bridge_supervised_learning.py.
def main(argv):
  if len(argv) > 1:
    raise app.UsageError('Too many command-line arguments.')
  # Make the network.
  net = hk.without_apply_rng(hk.transform(net_fn))
  # Make the optimiser.
  opt = optax.adam(1e-4)
  @jax.jit
  def loss(
      params: Params,
      inputs: np.ndarray,
      targets: np.ndarray,
  ) -> jax.Array:
    """Cross-entropy loss."""
    assert targets.dtype == np.int32
    log_probs = net.apply(params, inputs)
    return -jnp.mean(one_hot(targets, NUM_ACTIONS) * log_probs)
  @jax.jit
  def accuracy(
      params: Params,
      inputs: np.ndarray,
      targets: np.ndarray,
  ) -> jax.Array:
    """Classification accuracy."""
    predictions = net.apply(params, inputs)
    return jnp.mean(jnp.argmax(predictions, axis=-1) == targets)
  @jax.jit
  def update(
      params: Params,
      opt_state: OptState,
      inputs: np.ndarray,
      targets: np.ndarray,
  ) -> Tuple[Params, OptState]:
    """Learning rule (stochastic gradient descent)."""
    _, gradient = jax.value_and_grad(loss)(params, inputs, targets)
    updates, opt_state = opt.update(gradient, opt_state)
    new_params = optax.apply_updates(params, updates)
    return new_params, opt_state
  def output_samples(params: Params, max_samples: int):
    """Output some cases where the policy disagrees with the dataset action."""
    if max_samples == 0:
      return
    count = 0
    with open(os.path.join(FLAGS.data_path, 'test.txt')) as f:
      lines = list(f)
    np.random.shuffle(lines)
    for line in lines:
      state = GAME.new_initial_state()
      actions = _no_play_trajectory(line)
      for action in actions:
        if not state.is_chance_node():
          observation = np.array(state.observation_tensor(), np.float32)
          policy = np.exp(net.apply(params, observation))
          probs_actions = [(p, a + MIN_ACTION) for a, p in enumerate(policy)]
          pred = max(probs_actions)[1]
          if pred != action:
            print(state)
            for p, a in reversed(sorted(probs_actions)[-TOP_K_ACTIONS:]):
              print('{:7} {:.2f}'.format(state.action_to_string(a), p))
            print('Ground truth {}\n'.format(state.action_to_string(action)))
            count += 1
            break
        state.apply_action(action)
      if count >= max_samples:
        return
  # Make datasets.
  if FLAGS.data_path is None:
    raise app.UsageError(
        'Please generate your own supervised training data or download from '
        'https://console.cloud.google.com/storage/browser/openspiel-data/bridge'
        ' and supply the local location as --data_path')
  train = batch(
      make_dataset(os.path.join(FLAGS.data_path, 'train.txt')),
      FLAGS.train_batch)
  test = batch(
      make_dataset(os.path.join(FLAGS.data_path, 'test.txt')), FLAGS.eval_batch)
  # Initialize network and optimiser.
  rng = jax.random.PRNGKey(FLAGS.rng_seed)  # seed used for network weights
  inputs, unused_targets = next(train)
  params = net.init(rng, inputs)
  opt_state = opt.init(params)
  # Train/eval loop.
  for step in range(FLAGS.iterations):
    # Do SGD on a batch of training examples.
    inputs, targets = next(train)
    params, opt_state = update(params, opt_state, inputs, targets)
    # Periodically evaluate classification accuracy on the test set.
    if (1 + step) % FLAGS.eval_every == 0:
      inputs, targets = next(test)
      test_accuracy = accuracy(params, inputs, targets)
      print(f'After {1+step} steps, test accuracy: {test_accuracy}.')
      if FLAGS.save_path:
        filename = os.path.join(FLAGS.save_path, f'params-{1 + step}.pkl')
        with open(filename, 'wb') as pkl_file:
          pickle.dump(params, pkl_file)
      output_samples(params, FLAGS.num_examples)
make_dataset()
open_spiel.python.examples.bridge_supervised_learning.make_dataset (str file)
Creates dataset as a generator of single examples.
Definition at line 71 of file bridge_supervised_learning.py.
def make_dataset(file: str):
  """Creates dataset as a generator of single examples."""
  all_trajectories = [_no_play_trajectory(line) for line in open(file)]
  while True:
    np.random.shuffle(all_trajectories)
    for trajectory in all_trajectories:
      action_index = np.random.randint(52, len(trajectory))
      state = GAME.new_initial_state()
      for action in trajectory[:action_index]:
        state.apply_action(action)
      yield (state.observation_tensor(), trajectory[action_index] - MIN_ACTION)
References open_spiel.python.examples.bridge_supervised_learning._no_play_trajectory().
Referenced by open_spiel.python.examples.bridge_supervised_learning.net_fn().
net_fn()
open_spiel.python.examples.bridge_supervised_learning.net_fn (x)
Haiku module for our network.
Definition at line 100 of file bridge_supervised_learning.py.
def net_fn(x):
  """Haiku module for our network."""
  net = hk.Sequential([
      hk.Linear(1024),
      jax.nn.relu,
      hk.Linear(1024),
      jax.nn.relu,
      hk.Linear(1024),
      jax.nn.relu,
      hk.Linear(1024),
      jax.nn.relu,
      hk.Linear(NUM_ACTIONS),
      jax.nn.log_softmax,
  ])
  return net(x)
References open_spiel.python.examples.bridge_supervised_learning._no_play_trajectory(), open_spiel.python.examples.bridge_supervised_learning.batch(), open_spiel.python.examples.bridge_supervised_learning.make_dataset(), and open_spiel.python.examples.bridge_supervised_learning.one_hot().
one_hot()
open_spiel.python.examples.bridge_supervised_learning.one_hot (x, k)
Returns a one-hot encoding of `x` of size `k`.
Definition at line 95 of file bridge_supervised_learning.py.
def one_hot(x, k):
  """Returns a one-hot encoding of `x` of size `k`."""
  return jnp.array(x[..., jnp.newaxis] == jnp.arange(k), dtype=np.float32)
Referenced by open_spiel.python.examples.bridge_supervised_learning.net_fn().
Variable Documentation
FLAGS
open_spiel.python.examples.bridge_supervised_learning.FLAGS = flags.FLAGS
Definition at line 39 of file bridge_supervised_learning.py.
GAME
open_spiel.python.examples.bridge_supervised_learning.GAME = pyspiel.load_game('bridge(use_double_dummy_result=false)')
Definition at line 40 of file bridge_supervised_learning.py.
MIN_ACTION
int open_spiel.python.examples.bridge_supervised_learning.MIN_ACTION = 52
Definition at line 42 of file bridge_supervised_learning.py.
NUM_ACTIONS
int open_spiel.python.examples.bridge_supervised_learning.NUM_ACTIONS = 38
Definition at line 41 of file bridge_supervised_learning.py.
NUM_CARDS
int open_spiel.python.examples.bridge_supervised_learning.NUM_CARDS = 52
Definition at line 43 of file bridge_supervised_learning.py.
NUM_PLAYERS
int open_spiel.python.examples.bridge_supervised_learning.NUM_PLAYERS = 4
Definition at line 44 of file bridge_supervised_learning.py.
OptState
open_spiel.python.examples.bridge_supervised_learning.OptState = Any
Definition at line 36 of file bridge_supervised_learning.py.
Params
open_spiel.python.examples.bridge_supervised_learning.Params = Any
Definition at line 37 of file bridge_supervised_learning.py.
TOP_K_ACTIONS
int open_spiel.python.examples.bridge_supervised_learning.TOP_K_ACTIONS = 5
Definition at line 45 of file bridge_supervised_learning.py.