open spiel: open_spiel::oshi_zumo::OshiZumoGame Class Reference
open_spiel::oshi_zumo::OshiZumoGame Class Reference
Public Member Functions
OshiZumoGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
absl::optional< double > UtilitySum () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
int horizon () const
int starting_coins () const
int size () const
bool alesia () const
int min_bid () const
Public Member Functions inherited from open_spiel::Game
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 85 of file oshi_zumo.h.
Constructor & Destructor Documentation
OshiZumoGame()
open_spiel::oshi_zumo::OshiZumoGame::OshiZumoGame (const GameParameters & params) explicit
Definition at line 236 of file oshi_zumo.cc.
    : Game(kGameType, params),
      horizon_(ParameterValue<int>("horizon")),
      starting_coins_(ParameterValue<int>("coins")),
      size_(ParameterValue<int>("size")),
      alesia_(ParameterValue<bool>("alesia")),
      min_bid_(ParameterValue<int>("min_bid")) {
  SPIEL_CHECK_GE(min_bid_, 0);
  SPIEL_CHECK_LE(min_bid_, starting_coins_);
}
Member Function Documentation
alesia()
bool open_spiel::oshi_zumo::OshiZumoGame::alesia () const inline
Definition at line 103 of file oshi_zumo.h.
{ return alesia_; }
horizon()
int open_spiel::oshi_zumo::OshiZumoGame::horizon () const inline
Definition at line 100 of file oshi_zumo.h.
{ return horizon_; }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::__init__(), open_spiel.python.mfg.games.crowd_avoidance.Observer::__init__(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::__init__(), open_spiel.python.mfg.games.crowd_modelling.Observer::__init__(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::__init__(), open_spiel.python.mfg.games.linear_quadratic.Observer::__init__(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::__init__(), open_spiel.python.mfg.games.periodic_aversion.Observer::__init__(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::__init__(), open_spiel.python.mfg.games.predator_prey.Observer::__init__(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::eta_t(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::is_terminal(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::is_terminal(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::is_terminal(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::is_terminal(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::is_terminal(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceGame::max_chance_nodes_in_history(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingGame::max_chance_nodes_in_history(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticGame::max_chance_nodes_in_history(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionGame::max_chance_nodes_in_history(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyGame::max_chance_nodes_in_history(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), and open_spiel.python.mfg.games.predator_prey.Observer::set_from().
MaxChanceOutcomes()
int open_spiel::oshi_zumo::OshiZumoGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 91 of file oshi_zumo.h.
{ return 0; }
MaxGameLength()
int open_spiel::oshi_zumo::OshiZumoGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 97 of file oshi_zumo.h.
{ return horizon_; }
MaxUtility()
double open_spiel::oshi_zumo::OshiZumoGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 94 of file oshi_zumo.h.
{ return +1; }
min_bid()
int open_spiel::oshi_zumo::OshiZumoGame::min_bid () const inline
Definition at line 104 of file oshi_zumo.h.
{ return min_bid_; }
MinUtility()
double open_spiel::oshi_zumo::OshiZumoGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 93 of file oshi_zumo.h.
{ return -1; }
NewInitialState()
std::unique_ptr< State > open_spiel::oshi_zumo::OshiZumoGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 247 of file oshi_zumo.cc.
{
  return std::unique_ptr<State>(new OshiZumoState(shared_from_this()));
}
NumDistinctActions()
int open_spiel::oshi_zumo::OshiZumoGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 89 of file oshi_zumo.h.
{ return starting_coins_ + 1; }
NumPlayers()
int open_spiel::oshi_zumo::OshiZumoGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 92 of file oshi_zumo.h.
{ return 2; }
ObservationTensorShape()
std::vector< int > open_spiel::oshi_zumo::OshiZumoGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 251 of file oshi_zumo.cc.
{
  // 1 bit per coin value of player 1. { 0, 1, ..., starting_coins_ }
  // 1 bit per coin value of player 2. { 0, 1, ..., starting_coins_ }
  // 1 bit per position of the field. { 0, 1, ... , 2*size_+2 }
  return {(2 * (starting_coins_ + 1)) + (2 * size_ + 3)};
}
size()
int open_spiel::oshi_zumo::OshiZumoGame::size () const inline
Definition at line 102 of file oshi_zumo.h.
{ return size_; }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::__init__(), open_spiel.python.mfg.games.crowd_avoidance.Observer::__init__(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::__init__(), open_spiel.python.mfg.games.crowd_modelling.Observer::__init__(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::__init__(), open_spiel.python.mfg.games.linear_quadratic.Observer::__init__(), open_spiel.python.mfg.games.normal_form_game.MFGNormalFormState::__init__(), open_spiel.python.mfg.games.normal_form_game.Observer::__init__(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::__init__(), open_spiel.python.mfg.games.periodic_aversion.Observer::__init__(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::__init__(), open_spiel.python.mfg.games.predator_prey.Observer::__init__(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), and open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos().
starting_coins()
int open_spiel::oshi_zumo::OshiZumoGame::starting_coins () const inline
Definition at line 101 of file oshi_zumo.h.
{ return starting_coins_; }
UtilitySum()
absl::optional< double > open_spiel::oshi_zumo::OshiZumoGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 95 of file oshi_zumo.h.
{ return 0; }
The documentation for this class was generated from the following files:
open_spiel/games/oshi_zumo/oshi_zumo.h
open_spiel/games/oshi_zumo/oshi_zumo.cc