open spiel: world_representation.WorldState Class Reference
world_representation.WorldState Class Reference
Public Member Functions
__init__ (self)
List[int] get_distinct_actions (self)
bool is_terminal (self)
List[Any] get_actions (self)
Text get_infostate_string (self, int player)
None apply_actions (self, Tuple[int, int, int] actions)
float get_utility (self, int player)
Public Attributes
chance_policy
Protected Attributes
_history
Detailed Description
Base class for world state representation.
  We can implement this class for world state representations in both
  sequential and matrix games.
  Attributes:
    chance_policy: Policy of the chance node in the game tree.
Definition at line 21 of file world_representation.py.
Constructor & Destructor Documentation
__init__()
world_representation.WorldState.__init__ (self)
Definition at line 31 of file world_representation.py.
  def __init__(self):
    self.chance_policy = {0: 1.0}
    self._history = []
Member Function Documentation
apply_actions()
None world_representation.WorldState.apply_actions (self, Tuple[int, int, int] actions)
Applies the current player's action to change state of the world.
At each timestep of the game, the state of the world is changing by the
current player's action. At the same time, we should update self._history
with actions, by appending actions to self._history.
Args:
  actions: List of actions for chance node, player 1 and player 2.
Reimplemented in openspiel_api.WorldState.
Definition at line 64 of file world_representation.py.
  def apply_actions(self, actions: Tuple[int, int, int]) -> None:
    """Applies the current player's action to change state of the world.
    At each timestep of the game, the state of the world is changing by the
    current player's action. At the same time, we should update self._history
    with actions, by appending actions to self._history.
    Args:
      actions: List of actions for chance node, player 1 and player 2.
    """
    pass
get_actions()
List[Any] world_representation.WorldState.get_actions (self)
Returns the list of legal actions from the current state of the game.
Reimplemented in openspiel_api.WorldState.
Definition at line 46 of file world_representation.py.
  def get_actions(self) -> List[Any]:
    """Returns the list of legal actions from the current state of the game."""
    pass
get_distinct_actions()
List[int] world_representation.WorldState.get_distinct_actions (self)
Returns all possible distinct actions in the game.
Reimplemented in openspiel_api.WorldState.
Definition at line 36 of file world_representation.py.
  def get_distinct_actions(self) -> List[int]:
    """Returns all possible distinct actions in the game."""
    pass
get_infostate_string()
Text world_representation.WorldState.get_infostate_string (self, int player)
Returns the string form of infostate representation of a given player.
Args:
  player: Index of player.
Returns:
  The string representation of the infostate of player.
Reimplemented in openspiel_api.WorldState.
Definition at line 51 of file world_representation.py.
  def get_infostate_string(self, player: int) -> Text:
    """Returns the string form of infostate representation of a given player.
    Args:
      player: Index of player.
    Returns:
      The string representation of the infostate of player.
    """
    pass
get_utility()
float world_representation.WorldState.get_utility (self, int player)
Returns player's utility when the game reaches to a terminal state.
Args:
  player: Index of player.
Returns:
  Utility that player receives when we reach a terminal state in the game.
Reimplemented in openspiel_api.WorldState.
Definition at line 78 of file world_representation.py.
  def get_utility(self, player: int) -> float:
    """Returns player's utility when the game reaches to a terminal state.
    Args:
      player: Index of player.
    Returns:
      Utility that player receives when we reach a terminal state in the game.
    """
    pass
is_terminal()
bool world_representation.WorldState.is_terminal (self)
Returns if the current state of the game is a terminal or not.
Reimplemented in openspiel_api.WorldState.
Definition at line 41 of file world_representation.py.
  def is_terminal(self) -> bool:
    """Returns if the current state of the game is a terminal or not."""
    pass
Referenced by open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState._rewards(), open_spiel.python.games.chat_games.chat_game_base.ChatGameState.compute_rewards(), open_spiel.python.games.chat_games.chat_game_base.ChatGameState.current_player(), open_spiel.python.games.liars_poker.LiarsPokerState.current_player(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState.current_player(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState.current_player(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState.current_player(), open_spiel.python.mfg.games.normal_form_game.MFGNormalFormState.current_player(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState.current_player(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState.current_player(), openspiel_api.WorldState.get_actions(), openspiel_api.WorldState.get_chance_policy(), openspiel_api.WorldState.get_utility(), open_spiel.python.games.block_dominoes.BlockDominoesState.returns(), open_spiel.python.games.chat_games.chat_game_base.ChatGameState.returns(), open_spiel.python.games.team_dominoes.DominoesState.returns(), and open_spiel.python.mfg.games.normal_form_game.MFGNormalFormState.state_to_str().
Member Data Documentation
_history
world_representation.WorldState._history protected
Definition at line 33 of file world_representation.py.
Referenced by openspiel_api.WorldState.apply_actions(), and openspiel_api.WorldState.get_infostate_string().
chance_policy
world_representation.WorldState.chance_policy
Definition at line 32 of file world_representation.py.
Referenced by openspiel_api.WorldState.apply_actions().
The documentation for this class was generated from the following file:
open_spiel/python/examples/meta_cfr/sequential_games/world_representation.py