open spiel: open_spiel.python.utils.stats.HistogramNumbered Class Reference
open_spiel.python.utils.stats.HistogramNumbered Class Reference
Public Member Functions
__init__ (self, int num_buckets)
reset (self)
add (self, int bucket_id)
data (self)
Protected Attributes
_counts
Detailed Description
Track a histogram of occurences for `count` buckets.
You need to decide how to map your data into the buckets. Mainly useful for
scalar values.
Definition at line 94 of file stats.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.utils.stats.HistogramNumbered.__init__ (self, int num_buckets)
Definition at line 101 of file stats.py.
  def __init__(self, num_buckets: int):
    self._counts = [0] * num_buckets
Member Function Documentation
add()
open_spiel.python.utils.stats.HistogramNumbered.add (self, int bucket_id)
Definition at line 107 of file stats.py.
  def add(self, bucket_id: int):
    self._counts[bucket_id] += 1
data()
open_spiel.python.utils.stats.HistogramNumbered.data (self)
Definition at line 111 of file stats.py.
  def data(self):
    return self._counts
reset()
open_spiel.python.utils.stats.HistogramNumbered.reset (self)
Definition at line 104 of file stats.py.
  def reset(self):
    self._counts = [0] * len(self._counts)
Referenced by open_spiel.python.pytorch.deep_cfr.SonnetLinear.__init__(), open_spiel.python.environments.catch.Environment.step(), open_spiel.python.environments.cliff_walking.Environment.step(), open_spiel.python.rl_environment.Environment.step(), and open_spiel.python.vector_env.SyncVectorEnv.step().
Member Data Documentation
_counts
open_spiel.python.utils.stats.HistogramNumbered._counts protected
Definition at line 102 of file stats.py.
Referenced by open_spiel.python.games.liars_poker.LiarsPokerState._apply_action(), and open_spiel.python.games.dynamic_routing_utils.OriginDestinationDemand.counts().
The documentation for this class was generated from the following file:
open_spiel/python/utils/stats.py