open spiel: open_spiel.python.jax.opponent_shaping Namespace Reference
open_spiel.python.jax.opponent_shaping Namespace Reference
Classes
class OpponentShapingAgent
class TrainState
class TransitionBatch
Functions
typing.Iterator[TransitionBatch] get_minibatches (TransitionBatch batch, int num_minibatches)
UpdateFn get_critic_update_fn (int agent_id, hk.Transformed critic_network, optax.TransformUpdateFn optimizer, int num_minibatches=8, float gamma=0.99)
get_dice_update_fn (int agent_id, hk.PRNGSequence rng, hk.Transformed policy_network, hk.Transformed critic_network, optax.TransformUpdateFn optimizer, float opp_pi_lr, rl_environment.Environment env, int n_lookaheads=1, float gamma=0.99)
UpdateFn get_lola_update_fn (int agent_id, hk.Transformed policy_network, optax.TransformUpdateFn optimizer, float pi_lr, float gamma=0.99, float lola_weight=1.0)
UpdateFn get_opponent_update_fn (int agent_id, hk.Transformed policy_network, optax.TransformUpdateFn optimizer, int num_minibatches=1)
Variables
UpdateFn
Detailed Description
JAX implementation of LOLA and LOLA-DiCE (Foerster et al. 2018).
The DiCE implementation is also based on the pytorch implementation from
https://github.com/alexis-jacq/LOLA_DiCE by Alexis David Jacq.
Both algorithm implementations, LOLA and LOLA-DiCE, currently support only
two-player simultaneous move games and assume access to the opponent's
actions (the observation field in the time step must contain a key
'actions' with the opponent's actions).
Function Documentation
get_critic_update_fn()
UpdateFn open_spiel.python.jax.opponent_shaping.get_critic_update_fn (int agent_id, hk.Transformed critic_network, optax.TransformUpdateFn optimizer, int num_minibatches = 8, float gamma = 0.99)
Returns the update function for the critic parameters.
Args:
    agent_id: The id of the agent that will be updated.
    critic_network: A transformed haiku function.
    optimizer: Optimizer update function.
    num_minibatches: the number of minibatches.
    gamma: the discount factor.
Returns:
    An update function that takes the current train state together with a
    transition batch and returns the new train state and a dictionary of
    metrics.
Definition at line 113 of file opponent_shaping.py.
) -> UpdateFn:
  """Returns the update function for the critic parameters.
  Args:
      agent_id: The id of the agent that will be updated.
      critic_network: A transformed haiku function.
      optimizer: Optimizer update function.
      num_minibatches: the number of minibatches.
      gamma: the discount factor.
  Returns:
      An update function that takes the current train state together with a
      transition batch and returns the new train state and a dictionary of
      metrics.
  """
  def loss_fn(params, batch: TransitionBatch):
    info_states, rewards = batch.info_state[agent_id], batch.reward[agent_id]
    discounts = jnp.ones_like(rewards) * gamma
    values = critic_network.apply(params, info_states).squeeze()
    v_t = values[:, :-1].reshape(-1)
    v_tp1 = values[:, 1:].reshape(-1)
    r_t = rewards[:, :-1].reshape(-1)
    d_t = discounts[:, 1:].reshape(-1)
    td_error = jax.lax.stop_gradient(r_t + d_t * v_tp1) - v_t
    return jnp.mean(td_error**2)
  def update(train_state: TrainState, batch: TransitionBatch):
    """The critic update function.
    Updates the critic parameters of the train state with the given
    transition batch.
    Args:
        train_state: The current train state.
        batch: A transition batch.
    Returns:
        The updated train state with the new critic params and a dictionary
        with the critic loss
    """
    losses = []
    critic_params = train_state.critic_params[agent_id]
    opt_state = train_state.critic_opt_states[agent_id]
    for mini_batch in get_minibatches(batch, num_minibatches):
      loss, grads = jax.value_and_grad(loss_fn)(critic_params, mini_batch)
      updates, opt_state = optimizer(grads, opt_state)
      critic_params = optax.apply_updates(critic_params, updates)
      losses.append(loss)
    train_state = deepcopy(train_state)
    state = TrainState(
        policy_params=train_state.policy_params,
        policy_opt_states=train_state.policy_opt_states,
        critic_params={**train_state.critic_params, agent_id: critic_params},
        critic_opt_states={
            **train_state.critic_opt_states,
            agent_id: opt_state,
        },
    )
    return state, {'loss': jnp.mean(jnp.array(losses))}
  return update
References open_spiel.python.jax.opponent_shaping.get_minibatches().
Referenced by open_spiel.python.jax.opponent_shaping.OpponentShapingAgent.__init__().
get_dice_update_fn()
open_spiel.python.jax.opponent_shaping.get_dice_update_fn (int agent_id, hk.PRNGSequence rng, hk.Transformed policy_network, hk.Transformed critic_network, optax.TransformUpdateFn optimizer, float opp_pi_lr, rl_environment.Environment env, int n_lookaheads = 1, float gamma = 0.99)
Get the DiCE update function.
Definition at line 183 of file opponent_shaping.py.
):
  """Get the DiCE update function."""
  def magic_box(x):
    return jnp.exp(x - jax.lax.stop_gradient(x))
  @jax.jit
  @partial(jax.vmap, in_axes=(None, 0, 0))
  def get_action(params, s, rng_key):
    pi = policy_network.apply(params, s)
    action = pi.sample(seed=rng_key)
    return action
  def rollout(params, other_params):
    states, rewards, actions = [], [], []
    step = env.reset()
    batch_size = (
        step.observations['batch_size']
        if 'batch_size' in step.observations
        else 1
    )
    while not step.last():
      obs = step.observations
      s_1, s_2 = jnp.array(obs['info_state'][0]), jnp.array(
          obs['info_state'][1]
      )
      if batch_size == 1:
        s_1, s_2 = s_1[None, :], s_2[None, :]
      a_1 = get_action(params, s_1, jax.random.split(next(rng), num=batch_size))
      a_2 = get_action(
          other_params, s_2, jax.random.split(next(rng), num=batch_size)
      )
      a = jnp.stack([a_1, a_2], axis=1)
      step = env.step(a.squeeze())
      r_1, r_2 = jnp.array(step.rewards[0]), jnp.array(step.rewards[1])
      if batch_size == 1:
        r_1, r_2 = r_1[None], r_2[None]
      actions.append(a.T)
      states.append(jnp.stack([s_1, s_2], axis=0))
      rewards.append(jnp.stack([r_1, r_2], axis=0))
    return {
        'states': jnp.stack(states, axis=2),
        'rewards': jnp.stack(rewards, axis=2),
        'actions': jnp.stack(actions, axis=2),
    }
  def dice_correction(train_state: TrainState):
    """Computes the dice update for the given train state.
    Args:
        train_state: The current train state.
    Returns:
        The updated train state with the new policy params and metrics dict.
    """
    @jax.jit
    def dice_objective(params, other_params, states, actions, rewards, values):
      self_logprobs = vmap(
          vmap(lambda s, a: policy_network.apply(params, s).log_prob(a))
      )(states[0], actions[0])
      other_logprobs = vmap(
          vmap(lambda s, a: policy_network.apply(other_params, s).log_prob(a))
      )(states[1], actions[1])
      # apply discount:
      cum_discount = jnp.cumprod(gamma * jnp.ones_like(rewards), axis=1) / gamma
      discounted_rewards = rewards * cum_discount
      discounted_values = values.squeeze() * cum_discount
      # stochastics nodes involved in rewards dependencies:
      dependencies = jnp.cumsum(self_logprobs + other_logprobs, axis=1)
      # logprob of each stochastic nodes:
      stochastic_nodes = self_logprobs + other_logprobs
      # dice objective:
      dice_objective = jnp.mean(
          jnp.sum(magic_box(dependencies) * discounted_rewards, axis=1)
      )
      baseline_term = jnp.mean(
          jnp.sum((1 - magic_box(stochastic_nodes)) * discounted_values, axis=1)
      )
      dice_objective = dice_objective + baseline_term
      return -dice_objective  # want to minimize -objective
    def outer_update(params, opp_params, agent_id, opp_id):
      other_theta = opp_params
      for _ in range(n_lookaheads):
        trajectories = rollout(other_theta, params)
        other_grad = jax.grad(dice_objective)(
            other_theta,
            other_params=params,
            states=trajectories['states'],
            actions=trajectories['actions'],
            rewards=trajectories['rewards'][0],
            values=critic_network.apply(
                train_state.critic_params[opp_id], trajectories['states'][0]
            ),
        )
        # Update the other player's policy:
        other_theta = jax.tree_util.tree_map(
            lambda param, grad: param - opp_pi_lr * grad,
            other_theta,
            other_grad,
        )
      trajectories = rollout(params, other_theta)
      values = critic_network.apply(
          train_state.critic_params[agent_id], trajectories['states'][0]
      )
      loss = dice_objective(
          params=params,
          other_params=other_theta,
          states=trajectories['states'],
          actions=trajectories['actions'],
          rewards=trajectories['rewards'][0],
          values=values,
      )
      return loss, {'loss': loss}
    opp = 1 - agent_id
    grads, metrics = grad(outer_update, has_aux=True)(
        train_state.policy_params[agent_id],
        opp_params=train_state.policy_params[opp],
        agent_id=agent_id,
        opp_id=opp,
    )
    return grads, metrics
  def update(
      train_state: TrainState, batch: TransitionBatch
  ) -> typing.Tuple[TrainState, typing.Dict]:
    """Updates the policy parameters in train_state.
    If lola_weight > 0, the correction term according to Foerster et al. will be
    applied.
    Args:
        train_state: the agent's train state.
        batch: a transition batch
    Returns:
        A tuple (new_train_state, metrics)
    """
    del batch
    grads, metrics = dice_correction(train_state)
    updates, opt_state = optimizer(
        grads, train_state.policy_opt_states[agent_id]
    )
    policy_params = optax.apply_updates(
        train_state.policy_params[agent_id], updates
    )
    train_state = TrainState(
        policy_params={**train_state.policy_params, agent_id: policy_params},
        policy_opt_states={
            **train_state.policy_opt_states,
            agent_id: opt_state,
        },
        critic_params=deepcopy(train_state.critic_params),
        critic_opt_states=deepcopy(train_state.critic_opt_states),
    )
    return train_state, metrics
  return update
Referenced by open_spiel.python.jax.opponent_shaping.OpponentShapingAgent.__init__().
get_lola_update_fn()
UpdateFn open_spiel.python.jax.opponent_shaping.get_lola_update_fn (int agent_id, hk.Transformed policy_network, optax.TransformUpdateFn optimizer, float pi_lr, float gamma = 0.99, float lola_weight = 1.0)
Get the LOLA update function.
Returns a function that updates the policy parameters using the LOLA
correction formula.
Args:
    agent_id: the agent's id
    policy_network: A haiku transformed policy network.
    optimizer: An optax optimizer.
    pi_lr: Policy learning rate.
    gamma: Discount factor.
    lola_weight: The LOLA correction weight to scale the correction term.
Returns:
    A UpdateFn function that updates the policy parameters.
Definition at line 356 of file opponent_shaping.py.
) -> UpdateFn:
  """Get the LOLA update function.
  Returns a function that updates the policy parameters using the LOLA
  correction formula.
  Args:
      agent_id: the agent's id
      policy_network: A haiku transformed policy network.
      optimizer: An optax optimizer.
      pi_lr: Policy learning rate.
      gamma: Discount factor.
      lola_weight: The LOLA correction weight to scale the correction term.
  Returns:
      A UpdateFn function that updates the policy parameters.
  """
  def flat_params(
      params,
  ) -> typing.Tuple[
      typing.Dict[str, jnp.ndarray], typing.Dict[typing.Any, typing.Callable]
  ]:
    """Flattens the policy parameters.
    Flattens the parameters of the policy network into a single vector and
    returns the unravel function.
    Args:
        params: The policy parameters.
    Returns:
        A tuple (flat_params, unravel_fn)
    """
    flat_param_dict = {
        agent_id: jax.flatten_util.ravel_pytree(p)
        for agent_id, p in params.items()
    }
    params = dict((k, flat_param_dict[k][0]) for k in flat_param_dict)
    unravel_fns = dict((k, flat_param_dict[k][1]) for k in flat_param_dict)
    return params, unravel_fns
  def lola_correction(
      train_state: TrainState, batch: TransitionBatch
  ) -> hk.Params:
    """Computes the LOLA correction term.
    Args:
        train_state: The agent's current train state.
        batch: A transition batch.
    Returns:
        The LOLA correction term.
    """
    a_t, o_t, r_t, values = (
        batch.action,
        batch.info_state,
        batch.reward,
        batch.values,
    )
    params, unravel_fns = flat_params(train_state.policy_params)
    compute_returns = partial(rlax.lambda_returns, lambda_=0.0)
    g_t = vmap(vmap(compute_returns))(
        r_t=r_t, v_t=values, discount_t=jnp.full_like(r_t, gamma)
    )
    g_t = (g_t - g_t.mean()) / (g_t.std() + 1e-8)
    def log_pi(params, i, a_t, o_t):
      return policy_network.apply(unravel_fns[i](params), o_t).log_prob(a_t)
    opp_id = 1 - agent_id
    def cross_term(a_t, o_t, r_t):
      """Computes the second order correction term of the LOLA update.
      Args:
          a_t: actions of both players
          o_t: observations of both players
          r_t: rewards of both players
      Returns:
          The second order correction term.
      """
      grad_log_pi = vmap(jax.value_and_grad(log_pi), in_axes=(None, None, 0, 0))
      log_probs, grads = grad_log_pi(
          params[agent_id], agent_id, a_t[agent_id], o_t[agent_id]
      )
      opp_logrpobs, opp_grads = grad_log_pi(
          params[opp_id], opp_id, a_t[opp_id], o_t[opp_id]
      )
      grads = grads.cumsum(axis=0)
      opp_grads = opp_grads.cumsum(axis=0)
      log_probs = log_probs.cumsum(axis=0)
      opp_logrpobs = opp_logrpobs.cumsum(axis=0)
      cross_term = 0.0
      for t in range(0, len(a_t[agent_id])):
        discounted_reward = r_t[opp_id, t] * jnp.power(gamma, t)
        cross_term += (
            discounted_reward
            * jnp.outer(grads[t], opp_grads[t])
            * jnp.exp(log_probs[t] + opp_logrpobs[t])
        )
      return cross_term  # * jnp.exp(log_probs.sum() + opp_logrpobs.sum())
    def policy_gradient(a_t, o_t, g_t):
      grad_log_pi = vmap(grad(log_pi), in_axes=(None, None, 0, 0))
      opp_grads = grad_log_pi(params[opp_id], opp_id, a_t[opp_id], o_t[opp_id])
      pg = g_t[agent_id] @ opp_grads
      return pg
    cross = vmap(cross_term, in_axes=(1, 1, 1))(a_t, o_t, r_t).mean(axis=0)
    pg = vmap(policy_gradient, in_axes=(1, 1, 1))(a_t, o_t, g_t).mean(axis=0)
    correction = -pi_lr * (pg @ cross)
    return unravel_fns[agent_id](correction)
  def policy_loss(params, agent_id, batch):
    """Computes the policy gradient loss.
    Args:
        params: The policy parameters.
        agent_id: The agent's id.
        batch: A transition batch.
    Returns:
        The policy gradient loss.
    """
    a_t, o_t, r_t, values = (
        batch.action[agent_id],
        batch.info_state[agent_id],
        batch.reward[agent_id],
        batch.values[agent_id],
    )
    logits_t = vmap(vmap(lambda s: policy_network.apply(params, s).logits))(o_t)
    discount = jnp.full(r_t.shape, gamma)
    returns = vmap(rlax.lambda_returns)(
        r_t=r_t,
        v_t=values,
        discount_t=discount,
        lambda_=jnp.ones_like(discount),
    )
    adv_t = returns - values
    loss = vmap(rlax.policy_gradient_loss)(
        logits_t=logits_t, a_t=a_t, adv_t=adv_t, w_t=jnp.ones_like(adv_t)
    )
    return loss.mean()
  def update(
      train_state: TrainState, batch: TransitionBatch
  ) -> typing.Tuple[TrainState, typing.Dict]:
    """Updates the policy parameters in train_state.
    If lola_weight > 0, the correction term by Foerster et al. will be applied.
    Args:
        train_state: the agent's train state.
        batch: a transition batch
    Returns:
        A tuple (new_train_state, metrics)
    """
    loss, policy_grads = jax.value_and_grad(policy_loss)(
        train_state.policy_params[agent_id], agent_id, batch
    )
    correction = lola_correction(train_state, batch)
    policy_grads = jax.tree_util.tree_map(
        lambda grad, corr: grad - lola_weight * corr, policy_grads, correction
    )
    updates, opt_state = optimizer(
        policy_grads, train_state.policy_opt_states[agent_id]
    )
    policy_params = optax.apply_updates(
        train_state.policy_params[agent_id], updates
    )
    train_state = TrainState(
        policy_params={**train_state.policy_params, agent_id: policy_params},
        policy_opt_states={
            **train_state.policy_opt_states,
            agent_id: opt_state,
        },
        critic_params=deepcopy(train_state.critic_params),
        critic_opt_states=deepcopy(train_state.critic_opt_states),
    )
    return train_state, {'loss': loss}
  return update
Referenced by open_spiel.python.jax.opponent_shaping.OpponentShapingAgent.__init__().
get_minibatches()
typing.Iterator[TransitionBatch] open_spiel.python.jax.opponent_shaping.get_minibatches (TransitionBatch batch, int num_minibatches)
Yields an iterator over minibatches of the given batch.
Args:
    batch: A transition batch.
    num_minibatches: The number of minibatches to return.
Yields:
    An iterator over minibatches of the given batch.
Definition at line 87 of file opponent_shaping.py.
) -> typing.Iterator[TransitionBatch]:
  """Yields an iterator over minibatches of the given batch.
  Args:
      batch: A transition batch.
      num_minibatches: The number of minibatches to return.
  Yields:
      An iterator over minibatches of the given batch.
  """
  def get_minibatch(x, start, end):
    return x[:, start:end] if len(x.shape) > 2 else x
  for i in range(num_minibatches):
    start, end = i * (batch.reward.shape[1] // num_minibatches), (i + 1) * (
        batch.reward.shape[1] // num_minibatches
    )
    mini_batch = jax.tree_util.tree_map(
        partial(get_minibatch, start=start, end=end), batch
    )
    yield mini_batch
Referenced by open_spiel.python.jax.opponent_shaping.get_critic_update_fn(), and open_spiel.python.jax.opponent_shaping.get_opponent_update_fn().
get_opponent_update_fn()
UpdateFn open_spiel.python.jax.opponent_shaping.get_opponent_update_fn (int agent_id, hk.Transformed policy_network, optax.TransformUpdateFn optimizer, int num_minibatches = 1)
Get the opponent update function.
Definition at line 552 of file opponent_shaping.py.
) -> UpdateFn:
  """Get the opponent update function."""
  def loss_fn(params, batch: TransitionBatch):
    def loss(p, states, actions):
      log_prob = policy_network.apply(p, states).log_prob(actions)
      return log_prob
    log_probs = vmap(vmap(loss, in_axes=(None, 0, 0)), in_axes=(None, 0, 0))(
        params, batch.info_state[agent_id], batch.action[agent_id]
    )
    return -log_probs.sum(axis=-1).mean()
  def update(
      train_state: TrainState, batch: TransitionBatch
  ) -> typing.Tuple[TrainState, typing.Dict]:
    policy_params = train_state.policy_params[agent_id]
    opt_state = train_state.policy_opt_states[agent_id]
    loss = 0
    for mini_batch in get_minibatches(batch, num_minibatches):
      loss, policy_grads = jax.value_and_grad(loss_fn)(
          policy_params, mini_batch
      )
      updates, opt_state = optimizer(policy_grads, opt_state)
      policy_params = optax.apply_updates(
          train_state.policy_params[agent_id], updates
      )
    train_state = TrainState(
        policy_params={**train_state.policy_params, agent_id: policy_params},
        policy_opt_states={
            **train_state.policy_opt_states,
            agent_id: opt_state,
        },
        critic_params=deepcopy(train_state.critic_params),
        critic_opt_states=deepcopy(train_state.critic_opt_states),
    )
    return train_state, {'loss': loss}
  return update
References open_spiel.python.jax.opponent_shaping.get_minibatches().
Referenced by open_spiel.python.jax.opponent_shaping.OpponentShapingAgent.__init__().
Variable Documentation
UpdateFn
open_spiel.python.jax.opponent_shaping.UpdateFn
Initial value:
=  typing.Callable[
    [TrainState, TransitionBatch], typing.Tuple[TrainState, typing.Dict]
]
Definition at line 82 of file opponent_shaping.py.