open spiel: Empty< int > Struct Template Reference
Empty< int > Struct Template Reference
Public Member Functions
constexpr CallType value () const &
constexpr CallType value () const &&
Detailed Description
template<int>
struct Empty< int >
Definition at line 33 of file compressed_tuple_test.cc.
Member Function Documentation
value() [1/2]
template<int > CallType Empty< int >::value () const & inline constexpr
Definition at line 34 of file compressed_tuple_test.cc.
{ return CallType::kConstRef; }
Referenced by open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::__init__(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::__init__(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), and open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value().
value() [2/2]
template<int > CallType Empty< int >::value () const && inline constexpr
Definition at line 35 of file compressed_tuple_test.cc.
{ return CallType::kConstMove; }
Referenced by open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::__init__(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::__init__(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), and open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/compressed_tuple_test.cc