open spiel: open_spiel.python.voting.examples.atari_datasets Namespace Reference
open_spiel.python.voting.examples.atari_datasets Namespace Reference
Classes
class DataSet
Functions
float parse_value (str val_str)
List[float] parse_values (List[str] string_values_list)
delete_agent (DataSet dataset, str agent)
make_subset (DataSet dataset, List[str] agent_subset)
DataSet parse_atari_table (str filename)
Variables
str RAINBOW_TABLE5 = "atari_rainbow_table5.txt"
str RAINBOW_TABLE6 = "atari_rainbow_table6.txt"
str AGENT57_TABLE = "atari_agent57_table.txt"
str MUESLI_TABLE11 = "atari_muesli_table11.txt"
Detailed Description
Helper functions for loading Atari data.
Function Documentation
delete_agent()
open_spiel.python.voting.examples.atari_datasets.delete_agent (DataSet dataset, str agent)
Definition at line 104 of file atari_datasets.py.
def delete_agent(dataset: DataSet, agent: str):
  idx = dataset.agent_names.index(agent)
  assert 0 <= idx < len(dataset.agent_names)
  del dataset.agent_names[idx]
  for key in dataset.table_data.keys():
    del dataset.table_data[key][idx]
make_subset()
open_spiel.python.voting.examples.atari_datasets.make_subset (DataSet dataset, List[str] agent_subset)
Definition at line 112 of file atari_datasets.py.
def make_subset(dataset: DataSet, agent_subset: List[str]):
  for agent in dataset.agent_names:
    if agent not in agent_subset:
      delete_agent(dataset, agent)
parse_atari_table()
DataSet open_spiel.python.voting.examples.atari_datasets.parse_atari_table (str filename)
Parse an Atari data file.
The files are created by copy/paste from the papers.
Args:
  filename: the file that contains the dataset.
Returns:
    a DataSet object referring to the Atari data.
Definition at line 118 of file atari_datasets.py.
def parse_atari_table(filename: str) -> DataSet:
  """Parse an Atari data file.
  The files are created by copy/paste from the papers.
  Args:
    filename: the file that contains the dataset.
  Returns:
      a DataSet object referring to the Atari data.
  """
  with open(filename, "r") as f:
    string_data = f.read()
  # First line is a comment
  # Second line format is column descriptions, e.g.:
  # "# game <agent1 name> <agent2 name> ..."
  # Rest of the lines are copy/paste from the paper tables.
  lines = string_data.split("\n")
  assert lines[1].startswith("# game ")
  agent_names = lines[1].split()[2:]
  num_agents = len(agent_names)
  game_names = []
  table_data = {}
  for i in range(2, len(lines)):
    if lines[i].strip():
      parts = lines[i].split()
      game_name = parts[0]
      game_names.append(game_name)
      str_scores = parts[1:]
      assert len(str_scores) == num_agents, f"Error line: {lines[i]}"
      scores = parse_values(str_scores)
      table_data[game_name] = scores
  return DataSet(agent_names, game_names, table_data)
References open_spiel.python.voting.examples.atari_datasets.parse_values().
parse_value()
float open_spiel.python.voting.examples.atari_datasets.parse_value (str val_str)
Parse a numerical value from string, dropping ± part.
Definition at line 92 of file atari_datasets.py.
def parse_value(val_str: str) -> float:
  """Parse a numerical value from string, dropping ± part."""
  val_str = val_str.replace(",", "")
  val_str = val_str.split("±")[0]
  return float(val_str)
Referenced by open_spiel.python.voting.examples.atari_datasets.parse_values().
parse_values()
List[float] open_spiel.python.voting.examples.atari_datasets.parse_values (List[str] string_values_list)
Turn a list of strings into a list of floats.
Definition at line 99 of file atari_datasets.py.
def parse_values(string_values_list: List[str]) -> List[float]:
  """Turn a list of strings into a list of floats."""
  return [parse_value(val) for val in string_values_list]
References open_spiel.python.voting.examples.atari_datasets.parse_value().
Referenced by open_spiel.python.voting.examples.atari_datasets.parse_atari_table().
Variable Documentation
AGENT57_TABLE
str open_spiel.python.voting.examples.atari_datasets.AGENT57_TABLE = "atari_agent57_table.txt"
Definition at line 24 of file atari_datasets.py.
MUESLI_TABLE11
str open_spiel.python.voting.examples.atari_datasets.MUESLI_TABLE11 = "atari_muesli_table11.txt"
Definition at line 25 of file atari_datasets.py.
RAINBOW_TABLE5
str open_spiel.python.voting.examples.atari_datasets.RAINBOW_TABLE5 = "atari_rainbow_table5.txt"
Definition at line 22 of file atari_datasets.py.
RAINBOW_TABLE6
str open_spiel.python.voting.examples.atari_datasets.RAINBOW_TABLE6 = "atari_rainbow_table6.txt"
Definition at line 23 of file atari_datasets.py.