open spiel: open_spiel.python.jax.policy_gradient Namespace Reference
open_spiel.python.jax.policy_gradient Namespace Reference
Classes
class NetA2C
class NetPG
class PolicyGradient
Functions
generate_a2c_pi_loss (net_apply, loss_class, entropy_cost, l2_actor_weight, lambda_)
generate_a2c_critic_loss (net_apply, l2_critic_weight, lambda_)
generate_pg_pi_loss (net_apply, loss_class, entropy_cost, l2_actor_weight)
generate_pg_critic_loss (net_apply, l2_critic_weight, lambda_)
generate_act_func (net_apply)
Variables
Transition
Detailed Description
Policy gradient methods implemented in JAX.
Function Documentation
generate_a2c_critic_loss()
open_spiel.python.jax.policy_gradient.generate_a2c_critic_loss (net_apply, l2_critic_weight, lambda_)
A function generator generates loss function.
Definition at line 99 of file policy_gradient.py.
def generate_a2c_critic_loss(net_apply, l2_critic_weight, lambda_):
  """A function generator generates loss function."""
  def _a2c_critic_loss(net_params, batch):
    info_states, rewards, discounts = batch["info_states"], batch[
        "rewards"], batch["discounts"]
    _, baselines = net_apply(net_params, info_states)
    baselines = jnp.squeeze(baselines, axis=1)
    baselines = jnp.concatenate([baselines[:-1], jnp.zeros(1)])
    td_lambda = rlax.td_lambda(
        v_tm1=baselines[:-1],
        r_t=rewards,
        discount_t=discounts,
        v_t=baselines[1:],
        lambda_=lambda_,
        stop_target_gradients=True)
    l2_loss = jnp.sum(jnp.square(jax.flatten_util.ravel_pytree(net_params)[0]))
    return jnp.mean(jnp.square(td_lambda)) + l2_critic_weight * l2_loss
  return _a2c_critic_loss
Referenced by open_spiel.python.jax.policy_gradient.PolicyGradient.__init__().
generate_a2c_pi_loss()
open_spiel.python.jax.policy_gradient.generate_a2c_pi_loss (net_apply, loss_class, entropy_cost, l2_actor_weight, lambda_)
A function generator generates loss function.
Definition at line 66 of file policy_gradient.py.
                         lambda_):
  """A function generator generates loss function."""
  def _a2c_pi_loss(net_params, batch):
    info_states, actions, rewards, discounts = batch["info_states"], batch[
        "actions"], batch["rewards"], batch["discounts"]
    policy_logits, baselines = net_apply(net_params, info_states)
    policy_logits = policy_logits[:-1]
    baselines = jnp.squeeze(baselines, axis=1)
    baselines = jnp.concatenate([baselines[:-1], jnp.zeros(1)])
    td_returns = rlax.lambda_returns(
        rewards,
        discounts,
        baselines[1:],
        lambda_=lambda_,
        stop_target_gradients=True)
    advantages = td_returns - baselines[:-1]
    chex.assert_equal_shape([td_returns, actions, advantages])
    pi_loss = loss_class(
        logits_t=policy_logits,
        a_t=actions,
        adv_t=advantages,
        w_t=jnp.ones(td_returns.shape))
    ent_loss = rlax.entropy_loss(
        logits_t=policy_logits, w_t=jnp.ones(td_returns.shape))
    l2_loss = jnp.sum(jnp.square(jax.flatten_util.ravel_pytree(net_params)[0]))
    return pi_loss + entropy_cost * ent_loss + l2_actor_weight * l2_loss
  return _a2c_pi_loss
Referenced by open_spiel.python.jax.policy_gradient.PolicyGradient.__init__().
generate_act_func()
open_spiel.python.jax.policy_gradient.generate_act_func (net_apply)
A function generator generates act function.
Definition at line 165 of file policy_gradient.py.
def generate_act_func(net_apply):
  """A function generator generates act function."""
  def _act(net_params, info_state, action_mask, rng):
    info_state = jnp.reshape(info_state, [1, -1])
    policy_logits, _ = net_apply(net_params, info_state)
    policy_probs = jax.nn.softmax(policy_logits, axis=1)
    # Remove illegal actions, re-normalize probs
    probs = policy_probs[0] * action_mask
    probs /= jnp.sum(probs)
    action = jax.random.choice(rng, len(probs), p=probs)
    return action, probs
  return _act
Referenced by open_spiel.python.jax.policy_gradient.PolicyGradient.__init__().
generate_pg_critic_loss()
open_spiel.python.jax.policy_gradient.generate_pg_critic_loss (net_apply, l2_critic_weight, lambda_)
A function generator generates loss function.
Definition at line 138 of file policy_gradient.py.
def generate_pg_critic_loss(net_apply, l2_critic_weight, lambda_):
  """A function generator generates loss function."""
  def _critic_loss(net_params, batch):
    info_states, actions, rewards, discounts = batch["info_states"], batch[
        "actions"], batch["rewards"], batch["discounts"]
    _, q_values = net_apply(net_params, info_states)
    q_values = q_values[:-1]
    q_values = jnp.concatenate(
        [q_values, jnp.zeros(q_values[-1].reshape(1, -1).shape)])
    actions = jnp.concatenate([actions, jnp.zeros(1, dtype=int)])
    sarsa_lambda = rlax.sarsa_lambda(
        q_tm1=q_values[:-1],
        a_tm1=actions[:-1],
        r_t=rewards,
        discount_t=discounts,
        q_t=q_values[1:],
        a_t=actions[1:],
        lambda_=lambda_,
        stop_target_gradients=True)
    l2_loss = jnp.sum(jnp.square(jax.flatten_util.ravel_pytree(net_params)[0]))
    return jnp.mean(jnp.square(sarsa_lambda)) + l2_critic_weight * l2_loss
  return _critic_loss
Referenced by open_spiel.python.jax.policy_gradient.PolicyGradient.__init__().
generate_pg_pi_loss()
open_spiel.python.jax.policy_gradient.generate_pg_pi_loss (net_apply, loss_class, entropy_cost, l2_actor_weight)
A function generator generates loss function.
Definition at line 122 of file policy_gradient.py.
def generate_pg_pi_loss(net_apply, loss_class, entropy_cost, l2_actor_weight):
  """A function generator generates loss function."""
  def _pg_loss(net_params, batch):
    info_states = batch["info_states"]
    policy_logits, q_values = net_apply(net_params, info_states)
    chex.assert_equal_shape([policy_logits, q_values])
    pi_loss = loss_class(logits_t=policy_logits, q_t=q_values)
    ent_loss = rlax.entropy_loss(
        logits_t=policy_logits, w_t=jnp.ones(policy_logits.shape[:1]))
    l2_loss = jnp.sum(jnp.square(jax.flatten_util.ravel_pytree(net_params)[0]))
    return pi_loss + entropy_cost * ent_loss + l2_actor_weight * l2_loss
  return _pg_loss
Referenced by open_spiel.python.jax.policy_gradient.PolicyGradient.__init__().
Variable Documentation
Transition
open_spiel.python.jax.policy_gradient.Transition
Initial value:
=  collections.namedtuple(
    "Transition",
    "info_state action reward discount legal_actions_mask next_info_state")
Definition at line 27 of file policy_gradient.py.