open spiel: open_spiel.integration_tests.playthrough_test Namespace Reference
open_spiel.integration_tests.playthrough_test Namespace Reference
Classes
class PlaythroughTest
Functions
_is_optional_game (basename)
_playthrough_match (filename, regex)
_add_tests ()
Variables
str _DATA_DIR = "open_spiel/integration_tests/playthroughs/"
_OPTIONAL_GAMES = frozenset(["hanabi", "universal_poker"])
_AVAILABLE_GAMES = set(pyspiel.registered_names())
_MISSING_GAMES = set(["nfg_game", "efg_game", "restricted_nash_response"])
str _SHORTNAME = r'^GameType\.short_name = "(.*)"$'
Detailed Description
Re-run playthroughs and check for differences.
Function Documentation
_add_tests()
open_spiel.integration_tests.playthrough_test._add_tests () protected
Adds a test for each playthrough to the test class (above).
Definition at line 99 of file playthrough_test.py.
def _add_tests():
  """Adds a test for each playthrough to the test class (above)."""
  test_srcdir = os.environ.get("TEST_SRCDIR", "")
  path = os.path.join(test_srcdir, _DATA_DIR)
  basenames = sorted(os.listdir(path))
  if len(basenames) < 40:
    raise ValueError(f"Playthroughs are missing from {path}")
  for basename in basenames:
    test_name = f"test_playthrough_{basename}"
    test_func = lambda self, basename=basename: self.run_test(path, basename)
    test_func.__name__ = test_name
    setattr(PlaythroughTest, test_name, test_func)
References open_spiel.integration_tests.playthrough_test._add_tests().
Referenced by open_spiel.integration_tests.playthrough_test._add_tests().
_is_optional_game()
open_spiel.integration_tests.playthrough_test._is_optional_game (basename) protected
Returns (bool, game_name or None).
Args:
  basename: The basename of the file. It is assumed it starts with the game
    name.
Definition at line 41 of file playthrough_test.py.
def _is_optional_game(basename):
  """Returns (bool, game_name or None).
  Args:
    basename: The basename of the file. It is assumed it starts with the game
      name.
  """
  for game_name in _OPTIONAL_GAMES:
    if basename.startswith(game_name):
      return True, game_name
  return False, None
Referenced by open_spiel.integration_tests.playthrough_test.PlaythroughTest.run_test().
_playthrough_match()
open_spiel.integration_tests.playthrough_test._playthrough_match (filename, regex) protected
Returns the specified value fromm the playthrough.
Definition at line 54 of file playthrough_test.py.
def _playthrough_match(filename, regex):
  """Returns the specified value fromm the playthrough."""
  with open(filename, "r", encoding="utf-8") as f:
    data = f.read()
  return re.search(regex, data, re.MULTILINE)
Referenced by open_spiel.integration_tests.playthrough_test.PlaythroughTest.test_all_games_tested().
Variable Documentation
_AVAILABLE_GAMES
open_spiel.integration_tests.playthrough_test._AVAILABLE_GAMES = set(pyspiel.registered_names()) protected
Definition at line 29 of file playthrough_test.py.
_DATA_DIR
str open_spiel.integration_tests.playthrough_test._DATA_DIR = "open_spiel/integration_tests/playthroughs/" protected
Definition at line 26 of file playthrough_test.py.
_MISSING_GAMES
open_spiel.integration_tests.playthrough_test._MISSING_GAMES = set(["nfg_game", "efg_game", "restricted_nash_response"]) protected
Definition at line 34 of file playthrough_test.py.
_OPTIONAL_GAMES
open_spiel.integration_tests.playthrough_test._OPTIONAL_GAMES = frozenset(["hanabi", "universal_poker"]) protected
Definition at line 28 of file playthrough_test.py.
_SHORTNAME
str open_spiel.integration_tests.playthrough_test._SHORTNAME = r'^GameType\.short_name = "(.*)"$' protected
Definition at line 38 of file playthrough_test.py.