open spiel: open_spiel::go::GoState Class Reference
open_spiel::go::GoState Class Reference
Public Member Functions
GoState (std::shared_ptr< const Game > game, int board_size, float komi, int handicap)
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::string InformationStateString (int player) const override
std::string ObservationString (int player) const override
void ObservationTensor (int player, absl::Span< float > values) const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
const GoBoard & board () const
Public Member Functions inherited from open_spiel::State
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 70 of file go.h.
Constructor & Destructor Documentation
GoState()
open_spiel::go::GoState::GoState (std::shared_ptr< const Game > game, int board_size, float komi, int handicap)
Definition at line 86 of file go.cc.
    : State(std::move(game)),
      board_(board_size),
      komi_(komi),
      handicap_(handicap),
      max_game_length_(game_->MaxGameLength()),
      to_play_(GoColor::kBlack) {
  ResetBoard();
}
Member Function Documentation
ActionToString()
std::string open_spiel::go::GoState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 143 of file go.cc.
{
  return absl::StrCat(
      GoColorToString(static_cast<GoColor>(player)), " ",
      VirtualPointToString(board_.ActionToVirtualAction(action)));
}
board()
const GoBoard & open_spiel::go::GoState::board () const inline
Definition at line 97 of file go.h.
{ return board_; }
Referenced by open_spiel.python.games.tic_tac_toe.TicTacToeState::__init__(), open_spiel.python.games.tic_tac_toe.TicTacToeState::__str__(), open_spiel.python.games.tic_tac_toe.TicTacToeState::_apply_action(), and open_spiel.python.games.tic_tac_toe.TicTacToeState::_legal_actions().
Clone()
std::unique_ptr< State > open_spiel::go::GoState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 192 of file go.cc.
{
  return std::unique_ptr<State>(new GoState(*this));
}
CurrentPlayer()
Player open_spiel::go::GoState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 76 of file go.h.
{
    return IsTerminal() ? kTerminalPlayerId : ColorToPlayer(to_play_);
  }
DoApplyAction()
void open_spiel::go::GoState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 207 of file go.cc.
{
  SPIEL_CHECK_TRUE(
      board_.PlayMove(board_.ActionToVirtualAction(action), to_play_));
  to_play_ = OppColor(to_play_);
  bool was_inserted = repetitions_.insert(board_.HashValue()).second;
  if (!was_inserted && action != board_.pass_action()) {
    // We have encountered this position before.
    superko_ = true;
  }
}
InformationStateString()
std::string open_spiel::go::GoState::InformationStateString (int player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 97 of file go.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
IsTerminal()
bool open_spiel::go::GoState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 157 of file go.cc.
{
  if (history_.size() < 2) return false;
  return (history_.size() >= max_game_length_) || superko_ ||
         (history_[history_.size() - 1].action == board_.pass_action() &&
          history_[history_.size() - 2].action == board_.pass_action());
}
LegalActions()
std::vector< Action > open_spiel::go::GoState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 131 of file go.cc.
{
  std::vector<Action> actions{};
  if (IsTerminal()) return actions;
  for (VirtualPoint p : BoardPoints(board_.board_size())) {
    if (board_.IsLegalMove(p, to_play_)) {
      actions.push_back(board_.VirtualActionToAction(p));
    }
  }
  actions.push_back(board_.pass_action());
  return actions;
}
ObservationString()
std::string open_spiel::go::GoState::ObservationString (int player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 103 of file go.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
ObservationTensor()
void open_spiel::go::GoState::ObservationTensor (int player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 109 of file go.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  int num_cells = board_.board_size() * board_.board_size();
  SPIEL_CHECK_EQ(values.size(), num_cells * (CellStates() + 1));
  std::fill(values.begin(), values.end(), 0.);
  // Add planes: black, white, empty.
  int cell = 0;
  for (VirtualPoint p : BoardPoints(board_.board_size())) {
    int color_val = static_cast<int>(board_.PointColor(p));
    values[num_cells * color_val + cell] = 1.0;
    ++cell;
  }
  SPIEL_CHECK_EQ(cell, num_cells);
  // Add a fourth binary plane for komi (whether white is to play).
  std::fill(values.begin() + (CellStates() * num_cells), values.end(),
            (to_play_ == GoColor::kWhite ? 1.0 : 0.0));
}
Returns()
std::vector< double > open_spiel::go::GoState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 164 of file go.cc.
{
  if (!IsTerminal()) return {0.0, 0.0};
  if (superko_) {
    // Superko rules (https://senseis.xmp.net/?Superko) are complex and vary
    // between rulesets.
    // For simplicity and because superkos are very rare, we just treat them as
    // a draw.
    return {DrawUtility(), DrawUtility()};
  }
  // Score with Tromp-Taylor.
  float black_score = TrompTaylorScore(board_, komi_, handicap_);
  std::vector<double> returns(go::NumPlayers());
  if (black_score > 0) {
    returns[ColorToPlayer(GoColor::kBlack)] = WinUtility();
    returns[ColorToPlayer(GoColor::kWhite)] = LossUtility();
  } else if (black_score < 0) {
    returns[ColorToPlayer(GoColor::kBlack)] = LossUtility();
    returns[ColorToPlayer(GoColor::kWhite)] = WinUtility();
  } else {
    returns[ColorToPlayer(GoColor::kBlack)] = DrawUtility();
    returns[ColorToPlayer(GoColor::kWhite)] = DrawUtility();
  }
  return returns;
}
ToString()
std::string open_spiel::go::GoState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 149 of file go.cc.
{
  std::stringstream ss;
  ss << "GoState(komi=" << komi_ << ", to_play=" << GoColorToString(to_play_)
     << ", history.size()=" << history_.size() << ")\n";
  ss << board_;
  return ss.str();
}
UndoAction()
void open_spiel::go::GoState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 196 of file go.cc.
{
  // We don't have direct undo functionality, but copying the board and
  // replaying all actions is still pretty fast (> 1 million undos/second).
  history_.pop_back();
  --move_number_;
  ResetBoard();
  for (auto [_, action] : history_) {
    DoApplyAction(action);
  }
}
The documentation for this class was generated from the following files:
open_spiel/games/go/go.h
open_spiel/games/go/go.cc