open spiel: open_spiel.python.algorithms.rcfr Namespace Reference
open_spiel.python.algorithms.rcfr Namespace Reference
Classes
class _RcfrSolver
class DeepRcfrModel
class RcfrSolver
class ReservoirBuffer
class ReservoirRcfrSolver
class RootStateWrapper
Functions
tensor_to_matrix (tensor)
with_one_hot_action_features (state_features, legal_actions, num_distinct_actions)
sequence_features (state, num_distinct_actions)
num_features (game)
normalized_by_sum (v, axis=0, mutate=False)
relu (v)
_descendant_states (state, depth_limit, depth, include_terminals, include_chance_states)
all_states (initial_state, depth_limit=-1, include_terminals=False, include_chance_states=False)
sequence_weights_to_tabular_profile (root, policy_fn)
feedforward_evaluate (layers, x, use_skip_connections=False, hidden_are_factored=False)
Detailed Description
Regression counterfactual regret minimization (RCFR) [Waugh et al., 2015; Morrill, 2016].
In contrast to (tabular) counterfactual regret minimization (CFR)
[Zinkevich et al., 2007], RCFR replaces the table of regrets that generate the
current policy profile with a profile of regression models. The average
policy is still tracked exactly with a full game-size table. The exploitability
of the average policy in zero-sum games decreases as the model accuracy and
the number of iterations increase [Waugh et al., 2015; Morrill, 2016]. As long
as the regression model errors decrease across iterations, the average policy
converges toward a Nash equilibrium in zero-sum games.
# References
Dustin Morrill. Using Regret Estimation to Solve Games Compactly.
    M.Sc. thesis, Computing Science Department, University of Alberta,
    Apr 1, 2016, Edmonton Alberta, Canada.
Kevin Waugh, Dustin Morrill, J. Andrew Bagnell, and Michael Bowling.
    Solving Games with Functional Regret Estimation. At the Twenty-Ninth AAAI
    Conference on Artificial Intelligence, January 25-29, 2015, Austin Texas,
    USA. Pages 2138-2145.
Martin Zinkevich, Michael Johanson, Michael Bowling, and Carmelo Piccione.
    Regret Minimization in Games with Incomplete Information.
    At Advances in Neural Information Processing Systems 20 (NeurIPS). 2007.
Function Documentation
_descendant_states()
open_spiel.python.algorithms.rcfr._descendant_states (state, depth_limit, depth, include_terminals, include_chance_states) protected
Recursive descendant state generator.
Decision states are always yielded.
Args:
  state: The current state.
  depth_limit: The descendant depth limit. Zero will ensure only
    `initial_state` is generated and negative numbers specify the absence of a
    limit.
  depth: The current descendant depth.
  include_terminals: Whether or not to include terminal states.
  include_chance_states: Whether or not to include chance states.
Yields:
  `State`, a state that is `initial_state` or one of its descendants.
Definition at line 426 of file rcfr.py.
                       include_chance_states):
  """Recursive descendant state generator.
  Decision states are always yielded.
  Args:
    state: The current state.
    depth_limit: The descendant depth limit. Zero will ensure only
      `initial_state` is generated and negative numbers specify the absence of a
      limit.
    depth: The current descendant depth.
    include_terminals: Whether or not to include terminal states.
    include_chance_states: Whether or not to include chance states.
  Yields:
    `State`, a state that is `initial_state` or one of its descendants.
  """
  if state.is_terminal():
    if include_terminals:
      yield state
    return
  if depth > depth_limit >= 0:
    return
  if not state.is_chance_node() or include_chance_states:
    yield state
  for action in state.legal_actions():
    state_for_search = state.child(action)
    for substate in _descendant_states(state_for_search, depth_limit, depth + 1,
                                       include_terminals,
                                       include_chance_states):
      yield substate
References open_spiel.python.algorithms.rcfr._descendant_states().
Referenced by open_spiel.python.algorithms.rcfr._descendant_states(), and open_spiel.python.algorithms.rcfr.all_states().
all_states()
open_spiel.python.algorithms.rcfr.all_states (initial_state, depth_limit = -1, include_terminals = False, include_chance_states = False)
Generates states from `initial_state`.
Generates the set of states that includes only the `initial_state` and its
descendants that satisfy the inclusion criteria specified by the remaining
parameters. Decision states are always included.
Args:
  initial_state: The initial state from which to generate states.
  depth_limit: The descendant depth limit. Zero will ensure only
    `initial_state` is generated and negative numbers specify the absence of a
    limit. Defaults to no limit.
  include_terminals: Whether or not to include terminal states. Defaults to
    `False`.
  include_chance_states: Whether or not to include chance states. Defaults to
    `False`.
Returns:
  A generator that yields the `initial_state` and its descendants that
  satisfy the inclusion criteria specified by the remaining parameters.
Definition at line 463 of file rcfr.py.
               include_chance_states=False):
  """Generates states from `initial_state`.
  Generates the set of states that includes only the `initial_state` and its
  descendants that satisfy the inclusion criteria specified by the remaining
  parameters. Decision states are always included.
  Args:
    initial_state: The initial state from which to generate states.
    depth_limit: The descendant depth limit. Zero will ensure only
      `initial_state` is generated and negative numbers specify the absence of a
      limit. Defaults to no limit.
    include_terminals: Whether or not to include terminal states. Defaults to
      `False`.
    include_chance_states: Whether or not to include chance states. Defaults to
      `False`.
  Returns:
    A generator that yields the `initial_state` and its descendants that
    satisfy the inclusion criteria specified by the remaining parameters.
  """
  return _descendant_states(
      state=initial_state,
      depth_limit=depth_limit,
      depth=0,
      include_terminals=include_terminals,
      include_chance_states=include_chance_states)
References open_spiel.python.algorithms.rcfr._descendant_states().
Referenced by open_spiel.python.algorithms.rcfr.sequence_weights_to_tabular_profile().
feedforward_evaluate()
open_spiel.python.algorithms.rcfr.feedforward_evaluate (layers, x, use_skip_connections = False, hidden_are_factored = False)
Evaluates `layers` as a feedforward neural network on `x`.
Args:
  layers: The neural network layers (`tf.Tensor` -> `tf.Tensor` callables).
  x: The array-like input to evaluate. Must be trivially convertible to a
    matrix (tensor rank <= 2).
  use_skip_connections: Whether or not to use skip connections between layers.
    If the layer input has too few features to be added to the layer output,
    then the end of input is padded with zeros. If it has too many features,
    then the input is truncated.
  hidden_are_factored: Whether or not hidden logical layers are factored into
    two separate linear transformations stored as adjacent elements of
    `layers`.
Returns:
  The `tf.Tensor` evaluation result.
Raises:
  ValueError: If `x` has a rank greater than 2.
Definition at line 513 of file rcfr.py.
                         hidden_are_factored=False):
  """Evaluates `layers` as a feedforward neural network on `x`.
  Args:
    layers: The neural network layers (`tf.Tensor` -> `tf.Tensor` callables).
    x: The array-like input to evaluate. Must be trivially convertible to a
      matrix (tensor rank <= 2).
    use_skip_connections: Whether or not to use skip connections between layers.
      If the layer input has too few features to be added to the layer output,
      then the end of input is padded with zeros. If it has too many features,
      then the input is truncated.
    hidden_are_factored: Whether or not hidden logical layers are factored into
      two separate linear transformations stored as adjacent elements of
      `layers`.
  Returns:
    The `tf.Tensor` evaluation result.
  Raises:
    ValueError: If `x` has a rank greater than 2.
  """
  x = tensor_to_matrix(x)
  i = 0
  while i < len(layers) - 1:
    y = layers[i](x)
    i += 1
    if hidden_are_factored:
      y = layers[i](y)
      i += 1
    if use_skip_connections:
      my_num_features = x.shape[1].value
      padding = y.shape[1].value - my_num_features
      if padding > 0:
        zeros = tf.zeros([tf.shape(x)[0], padding])
        x = tf.concat([x, zeros], axis=1)
      elif padding < 0:
        x = tf.strided_slice(x, [0, 0], [tf.shape(x)[0], y.shape[1].value])
      y = x + y
    x = y
  return layers[-1](x)
References open_spiel.python.algorithms.rcfr.tensor_to_matrix().
Referenced by open_spiel.python.algorithms.rcfr.DeepRcfrModel.__call__().
normalized_by_sum()
open_spiel.python.algorithms.rcfr.normalized_by_sum (v, axis = 0, mutate = False)
Divides each element of `v` along `axis` by the sum of `v` along `axis`.
Assumes `v` is non-negative. Sets of `v` elements along `axis` that sum to
zero are normalized to `1 / v.shape[axis]` (a uniform distribution).
Args:
  v: Non-negative array of values.
  axis: An integer axis.
  mutate: Whether or not to store the result in `v`.
Returns:
  The normalized array.
Definition at line 389 of file rcfr.py.
def normalized_by_sum(v, axis=0, mutate=False):
  """Divides each element of `v` along `axis` by the sum of `v` along `axis`.
  Assumes `v` is non-negative. Sets of `v` elements along `axis` that sum to
  zero are normalized to `1 / v.shape[axis]` (a uniform distribution).
  Args:
    v: Non-negative array of values.
    axis: An integer axis.
    mutate: Whether or not to store the result in `v`.
  Returns:
    The normalized array.
  """
  v = np.asarray(v)
  denominator = v.sum(axis=axis, keepdims=True)
  denominator_is_zero = denominator == 0
  # Every element of `denominator_is_zero` that is true corresponds to a
  # set of elements in `v` along `axis` that are all zero. By setting these
  # denominators to `v.shape[axis]` and adding 1 to each of the corresponding
  # elements in `v`, these elements are normalized to `1 / v.shape[axis]`
  # (a uniform distribution).
  denominator += v.shape[axis] * denominator_is_zero
  if mutate:
    v += denominator_is_zero
    v /= denominator
  else:
    v = (v + denominator_is_zero) / denominator
  return v
Referenced by open_spiel.python.algorithms.rcfr.RootStateWrapper.counterfactual_regrets_and_reach_weights(), and open_spiel.python.algorithms.rcfr.RootStateWrapper.sequence_weights_to_policy().
num_features()
open_spiel.python.algorithms.rcfr.num_features (game)
Returns the number of features returned by `sequence_features`.
Args:
  game: An OpenSpiel `Game`.
Definition at line 134 of file rcfr.py.
def num_features(game):
  """Returns the number of features returned by `sequence_features`.
  Args:
    game: An OpenSpiel `Game`.
  """
  return game.information_state_tensor_size() + game.num_distinct_actions()
Referenced by open_spiel.python.algorithms.rcfr.DeepRcfrModel.__init__().
relu()
open_spiel.python.algorithms.rcfr.relu (v)
Returns the element-wise maximum between `v` and 0.
Definition at line 421 of file rcfr.py.
def relu(v):
  """Returns the element-wise maximum between `v` and 0."""
  return np.maximum(v, 0)
Referenced by open_spiel.python.algorithms.rcfr.RcfrSolver.evaluate_and_update_policy(), and open_spiel.python.algorithms.rcfr.ReservoirRcfrSolver.evaluate_and_update_policy().
sequence_features()
open_spiel.python.algorithms.rcfr.sequence_features (state, num_distinct_actions)
The sequence features at `state`.
Features are constructed by concatenating `state`'s normalized feature
vector with one-hot vectors indicating each action (see
`with_one_hot_action_features`).
Args:
  state: An OpenSpiel `State`.
  num_distinct_actions: The number of globally distinct actions in `state`'s
    game.
Returns:
  A `tf.Tensor` feature matrix with one row for each sequence.
Definition at line 114 of file rcfr.py.
def sequence_features(state, num_distinct_actions):
  """The sequence features at `state`.
  Features are constructed by concatenating `state`'s normalized feature
  vector with one-hot vectors indicating each action (see
  `with_one_hot_action_features`).
  Args:
    state: An OpenSpiel `State`.
    num_distinct_actions: The number of globally distinct actions in `state`'s
      game.
  Returns:
    A `tf.Tensor` feature matrix with one row for each sequence.
  """
  return with_one_hot_action_features(state.information_state_tensor(),
                                      state.legal_actions(),
                                      num_distinct_actions)
References open_spiel.python.algorithms.rcfr.with_one_hot_action_features().
sequence_weights_to_tabular_profile()
open_spiel.python.algorithms.rcfr.sequence_weights_to_tabular_profile (root, policy_fn)
Returns the `dict` of `list`s of action-prob pairs-form of `policy_fn`.
Definition at line 495 of file rcfr.py.
def sequence_weights_to_tabular_profile(root, policy_fn):
  """Returns the `dict` of `list`s of action-prob pairs-form of `policy_fn`."""
  tabular_policy = {}
  players = range(root.num_players())
  for state in all_states(root):
    for player in players:
      legal_actions = state.legal_actions(player)
      if len(legal_actions) < 1:
        continue
      info_state = state.information_state_string(player)
      if info_state in tabular_policy:
        continue
      my_policy = policy_fn(state)
      tabular_policy[info_state] = list(zip(legal_actions, my_policy))
  return tabular_policy
@tf.function
References open_spiel.python.algorithms.rcfr.all_states().
Referenced by open_spiel.python.algorithms.rcfr._RcfrSolver.average_policy(), and open_spiel.python.algorithms.rcfr._RcfrSolver.current_policy().
tensor_to_matrix()
open_spiel.python.algorithms.rcfr.tensor_to_matrix (tensor)
Converts `tensor` to a matrix (a rank-2 tensor) or raises an exception.
Args:
  tensor: The tensor to convert.
Returns:
  A TensorFlow matrix (rank-2 `tf.Tensor`).
Raises:
  ValueError: If `tensor` cannot be trivially converted to a matrix, i.e.
    `tensor` has a rank > 2.
Definition at line 57 of file rcfr.py.
def tensor_to_matrix(tensor):
  """Converts `tensor` to a matrix (a rank-2 tensor) or raises an exception.
  Args:
    tensor: The tensor to convert.
  Returns:
    A TensorFlow matrix (rank-2 `tf.Tensor`).
  Raises:
    ValueError: If `tensor` cannot be trivially converted to a matrix, i.e.
      `tensor` has a rank > 2.
  """
  tensor = tf.convert_to_tensor(tensor)
  rank = tensor.shape.rank
  if rank > 2:
    raise ValueError(
        ("Tensor {} cannot be converted into a matrix as it is rank "
         "{} > 2.").format(tensor, rank))
  elif rank < 2:
    num_columns = 1 if rank == 0 else tensor.shape[0].value
    tensor = tf.reshape(tensor, [1, num_columns])
  return tensor
Referenced by open_spiel.python.algorithms.rcfr.feedforward_evaluate(), and open_spiel.python.algorithms.rcfr.with_one_hot_action_features().
with_one_hot_action_features()
open_spiel.python.algorithms.rcfr.with_one_hot_action_features (state_features, legal_actions, num_distinct_actions)
Constructs features for each sequence by extending state features.
Sequences features are constructed by concatenating one-hot features
indicating each action to the information state features and stacking them.
Args:
  state_features: The features for the information state alone. Must be a
    `tf.Tensor` with a rank less than or equal to (if batched) 2.
  legal_actions: The list of legal actions in this state. Determines the
    number of rows in the returned feature matrix.
  num_distinct_actions: The number of globally distinct actions in the game.
    Determines the length of the action feature vector concatenated onto the
    state features.
Returns:
  A `tf.Tensor` feature matrix with one row for each sequence and # state
  features plus `num_distinct_actions`-columns.
Raises:
  ValueError: If `state_features` has a rank > 2.
Definition at line 81 of file rcfr.py.
                                 num_distinct_actions):
  """Constructs features for each sequence by extending state features.
  Sequences features are constructed by concatenating one-hot features
  indicating each action to the information state features and stacking them.
  Args:
    state_features: The features for the information state alone. Must be a
      `tf.Tensor` with a rank less than or equal to (if batched) 2.
    legal_actions: The list of legal actions in this state. Determines the
      number of rows in the returned feature matrix.
    num_distinct_actions: The number of globally distinct actions in the game.
      Determines the length of the action feature vector concatenated onto the
      state features.
  Returns:
    A `tf.Tensor` feature matrix with one row for each sequence and # state
    features plus `num_distinct_actions`-columns.
  Raises:
    ValueError: If `state_features` has a rank > 2.
  """
  state_features = tensor_to_matrix(state_features)
  with_action_features = []
  for action in legal_actions:
    action_features = tf.one_hot([action], num_distinct_actions)
    action_features = tf.tile(action_features, [tf.shape(state_features)[0], 1])
    all_features = tf.concat([state_features, action_features], axis=1)
    with_action_features.append(all_features)
  return tf.concat(with_action_features, axis=0)
References open_spiel.python.algorithms.rcfr.tensor_to_matrix().
Referenced by open_spiel.python.algorithms.rcfr.sequence_features().