open spiel: open_spiel.python.algorithms.psro_v2.meta_strategies Namespace Reference
open_spiel.python.algorithms.psro_v2.meta_strategies Namespace Reference
Functions
uniform_strategy (solver, return_joint=False)
softmax_on_range (number_policies)
uniform_biased_strategy (solver, return_joint=False)
renormalize (probabilities)
get_joint_strategy_from_marginals (probabilities)
nash_strategy (solver, return_joint=False)
prd_strategy (solver, return_joint=False)
rm_strategy (solver, return_joint=False)
Variables
int EPSILON_MIN_POSITIVE_PROBA = 1e-8
dict META_STRATEGY_METHODS
Detailed Description
Meta-strategy solvers for PSRO.
Function Documentation
get_joint_strategy_from_marginals()
open_spiel.python.algorithms.psro_v2.meta_strategies.get_joint_strategy_from_marginals (probabilities)
Returns a joint strategy tensor from a list of marginals.
Args:
  probabilities: list of probabilities.
Returns:
  A flat joint strategy from a list of marginals.
Definition at line 97 of file meta_strategies.py.
def get_joint_strategy_from_marginals(probabilities):
  """Returns a joint strategy tensor from a list of marginals.
  Args:
    probabilities: list of probabilities.
  Returns:
    A flat joint strategy from a list of marginals.
  """
  res = np.ones((1,), dtype=np.float64)
  for prob in probabilities:
    res = res[..., None] @ np.asarray(prob).reshape((1,) * res.ndim + (-1,))
  return res.reshape(-1)
Referenced by open_spiel.python.algorithms.psro_v2.meta_strategies.nash_strategy(), open_spiel.python.algorithms.psro_v2.meta_strategies.prd_strategy(), open_spiel.python.algorithms.psro_v2.meta_strategies.rm_strategy(), open_spiel.python.algorithms.psro_v2.meta_strategies.uniform_biased_strategy(), and open_spiel.python.algorithms.psro_v2.meta_strategies.uniform_strategy().
nash_strategy()
open_spiel.python.algorithms.psro_v2.meta_strategies.nash_strategy (solver, return_joint = False)
Returns nash distribution on meta game matrix.
This method only works for two player zero-sum games.
Args:
  solver: GenPSROSolver instance.
  return_joint: If true, only returns marginals. Otherwise marginals as well
    as joint probabilities.
Returns:
  Nash distribution on strategies.
Definition at line 112 of file meta_strategies.py.
def nash_strategy(solver, return_joint=False):
  """Returns nash distribution on meta game matrix.
  This method only works for two player zero-sum games.
  Args:
    solver: GenPSROSolver instance.
    return_joint: If true, only returns marginals. Otherwise marginals as well
      as joint probabilities.
  Returns:
    Nash distribution on strategies.
  """
  meta_games = solver.get_meta_game()
  if not isinstance(meta_games, list):
    meta_games = [meta_games, -meta_games]
  meta_games = [x.tolist() for x in meta_games]
  if len(meta_games) != 2:
    raise NotImplementedError(
        "nash_strategy solver works only for 2p zero-sum"
        "games, but was invoked for a {} player game".format(len(meta_games)))
  nash_prob_1, nash_prob_2, _, _ = (
      lp_solver.solve_zero_sum_matrix_game(
          pyspiel.create_matrix_game(*meta_games)))
  result = [
      renormalize(np.array(nash_prob_1).reshape(-1)),
      renormalize(np.array(nash_prob_2).reshape(-1))
  ]
  if not return_joint:
    return result
  else:
    joint_strategies = get_joint_strategy_from_marginals(result)
    return result, joint_strategies
References open_spiel.python.algorithms.psro_v2.meta_strategies.get_joint_strategy_from_marginals(), and open_spiel.python.algorithms.psro_v2.meta_strategies.renormalize().
prd_strategy()
open_spiel.python.algorithms.psro_v2.meta_strategies.prd_strategy (solver, return_joint = False)
Computes Projected Replicator Dynamics strategies.
Args:
  solver: GenPSROSolver instance.
  return_joint: If true, only returns marginals. Otherwise marginals as well
    as joint probabilities.
Returns:
  PRD-computed strategies.
Definition at line 148 of file meta_strategies.py.
def prd_strategy(solver, return_joint=False):
  """Computes Projected Replicator Dynamics strategies.
  Args:
    solver: GenPSROSolver instance.
    return_joint: If true, only returns marginals. Otherwise marginals as well
      as joint probabilities.
  Returns:
    PRD-computed strategies.
  """
  meta_games = solver.get_meta_game()
  if not isinstance(meta_games, list):
    meta_games = [meta_games, -meta_games]
  kwargs = solver.get_kwargs()
  result = projected_replicator_dynamics.projected_replicator_dynamics(
      meta_games, **kwargs)
  if not return_joint:
    return result
  else:
    joint_strategies = get_joint_strategy_from_marginals(result)
    return result, joint_strategies
References open_spiel.python.algorithms.psro_v2.meta_strategies.get_joint_strategy_from_marginals().
renormalize()
open_spiel.python.algorithms.psro_v2.meta_strategies.renormalize (probabilities)
Replaces all negative entries with zeroes and normalizes the result.
Args:
  probabilities: probability vector to renormalize. Has to be one-dimensional.
Returns:
  Renormalized probabilities.
Definition at line 83 of file meta_strategies.py.
def renormalize(probabilities):
  """Replaces all negative entries with zeroes and normalizes the result.
  Args:
    probabilities: probability vector to renormalize. Has to be one-dimensional.
  Returns:
    Renormalized probabilities.
  """
  probabilities[probabilities < 0] = 0
  probabilities = probabilities / np.sum(probabilities)
  return probabilities
Referenced by open_spiel.python.algorithms.psro_v2.meta_strategies.nash_strategy().
rm_strategy()
open_spiel.python.algorithms.psro_v2.meta_strategies.rm_strategy (solver, return_joint = False)
Computes regret-matching strategies.
Args:
  solver: GenPSROSolver instance.
  return_joint: If true, only returns marginals. Otherwise marginals as well
    as joint probabilities.
Returns:
  PRD-computed strategies.
Definition at line 172 of file meta_strategies.py.
def rm_strategy(solver, return_joint=False):
  """Computes regret-matching strategies.
  Args:
    solver: GenPSROSolver instance.
    return_joint: If true, only returns marginals. Otherwise marginals as well
      as joint probabilities.
  Returns:
    PRD-computed strategies.
  """
  meta_games = solver.get_meta_game()
  if not isinstance(meta_games, list):
    meta_games = [meta_games, -meta_games]
  kwargs = solver.get_kwargs()
  result = regret_matching.regret_matching(meta_games, **kwargs)
  if not return_joint:
    return result
  else:
    joint_strategies = get_joint_strategy_from_marginals(result)
    return result, joint_strategies
References open_spiel.python.algorithms.psro_v2.meta_strategies.get_joint_strategy_from_marginals().
softmax_on_range()
open_spiel.python.algorithms.psro_v2.meta_strategies.softmax_on_range (number_policies)
Definition at line 49 of file meta_strategies.py.
def softmax_on_range(number_policies):
  x = np.array(list(range(number_policies)))
  x = np.exp(x-x.max())
  x /= np.sum(x)
  return x
uniform_biased_strategy()
open_spiel.python.algorithms.psro_v2.meta_strategies.uniform_biased_strategy (solver, return_joint = False)
Returns a Biased Random Uniform distribution on policies.
The uniform distribution is biased to prioritize playing against more recent
policies (Policies that were appended to the policy list later in training)
instead of older ones.
Args:
  solver: GenPSROSolver instance.
  return_joint: If true, only returns marginals. Otherwise marginals as well
    as joint probabilities.
Returns:
  uniform distribution on strategies.
Definition at line 56 of file meta_strategies.py.
def uniform_biased_strategy(solver, return_joint=False):
  """Returns a Biased Random Uniform distribution on policies.
  The uniform distribution is biased to prioritize playing against more recent
  policies (Policies that were appended to the policy list later in training)
  instead of older ones.
  Args:
    solver: GenPSROSolver instance.
    return_joint: If true, only returns marginals. Otherwise marginals as well
      as joint probabilities.
  Returns:
    uniform distribution on strategies.
  """
  policies = solver.get_policies()
  if not isinstance(policies[0], list):
    policies = [policies]
  policy_lengths = [len(pol) for pol in policies]
  result = [softmax_on_range(pol_len) for pol_len in policy_lengths]
  if not return_joint:
    return result
  else:
    joint_strategies = get_joint_strategy_from_marginals(result)
    return result, joint_strategies
References open_spiel.python.algorithms.psro_v2.meta_strategies.get_joint_strategy_from_marginals().
uniform_strategy()
open_spiel.python.algorithms.psro_v2.meta_strategies.uniform_strategy (solver, return_joint = False)
Returns a Random Uniform distribution on policies.
Args:
  solver: GenPSROSolver instance.
  return_joint: If true, only returns marginals. Otherwise marginals as well
    as joint probabilities.
Returns:
  uniform distribution on strategies.
Definition at line 28 of file meta_strategies.py.
def uniform_strategy(solver, return_joint=False):
  """Returns a Random Uniform distribution on policies.
  Args:
    solver: GenPSROSolver instance.
    return_joint: If true, only returns marginals. Otherwise marginals as well
      as joint probabilities.
  Returns:
    uniform distribution on strategies.
  """
  policies = solver.get_policies()
  policy_lengths = [len(pol) for pol in policies]
  result = [np.ones(pol_len) / pol_len for pol_len in policy_lengths]
  if not return_joint:
    return result
  else:
    joint_strategies = get_joint_strategy_from_marginals(result)
    return result, joint_strategies
References open_spiel.python.algorithms.psro_v2.meta_strategies.get_joint_strategy_from_marginals().
Variable Documentation
EPSILON_MIN_POSITIVE_PROBA
int open_spiel.python.algorithms.psro_v2.meta_strategies.EPSILON_MIN_POSITIVE_PROBA = 1e-8
Definition at line 25 of file meta_strategies.py.
META_STRATEGY_METHODS
dict open_spiel.python.algorithms.psro_v2.meta_strategies.META_STRATEGY_METHODS
Initial value:
=  {
    "uniform_biased": uniform_biased_strategy,
    "uniform": uniform_strategy,
    "nash": nash_strategy,
    "prd": prd_strategy,
    "rm": rm_strategy,
}
Definition at line 195 of file meta_strategies.py.