open spiel: open_spiel.python.examples.nego_nbs_example.MaxBot Class Reference
open_spiel.python.examples.nego_nbs_example.MaxBot Class Reference
Public Member Functions
__init__ (self)
step (self, state)
Detailed Description
Finds the single (deterministic) trade offer that maximizes the NBS.
Definition at line 220 of file nego_nbs_example.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.examples.nego_nbs_example.MaxBot.__init__ (self)
Definition at line 223 of file nego_nbs_example.py.
  def __init__(self):
    pass
Member Function Documentation
step()
open_spiel.python.examples.nego_nbs_example.MaxBot.step (self, state)
Returns the NBS-maximizing action.
If i'm player 0, then search over all possible moves, assume player 2
takes the agree action, and choose the action that maximizes the NBS
Player 1 just always agrees.
Args:
  state: the OpenSpiel state to act from.
Definition at line 226 of file nego_nbs_example.py.
  def step(self, state):
    """Returns the NBS-maximizing action.
    If i'm player 0, then search over all possible moves, assume player 2
    takes the agree action, and choose the action that maximizes the NBS
    Player 1 just always agrees.
    Args:
      state: the OpenSpiel state to act from.
    """
    player = state.current_player()
    if player == 1:
      return state.agree_action()
    max_nbs = -1
    max_action = -1
    for action in state.legal_actions():
      state_clone = state.clone()
      state_clone.apply_action(action)
      state_clone.apply_action(state.agree_action())
      returns = state_clone.returns()
      nbs = np.prod(returns)
      if nbs > max_nbs:
        max_nbs = nbs
        max_action = action
    assert max_action >= 0
    return max_action
Referenced by open_spiel.python.jax.cfr.jax_cfr.JaxCFR.evaluate_and_update_policy(), open_spiel.python.jax.cfr.jax_cfr.JaxCFR.multiple_steps(), open_spiel.python.algorithms.double_oracle.DoubleOracleSolver.solve_yield(), nash_evolutionary_search.NashCMAES.step_for(), nash_random_search.NashRandomSearch.step_for(), open_spiel.python.mfg.algorithms.bandit_regret.PolynomialWeightAlgorithm.step_for(), and regret_minimizer.RegretMinimizer.step_for().
The documentation for this class was generated from the following file:
open_spiel/python/examples/nego_nbs_example.py