open spiel: open_spiel/games/bridge/double_dummy_solver/examples/AnalyseAllPlaysPBN.cpp File Reference
AnalyseAllPlaysPBN.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/dll.h"
#include "hands.h"
Functions
int main ()
Variables
unsigned char dcardSuit [5]
unsigned char dcardRank [16]
Function Documentation
main()
int main ()
Definition at line 23 of file AnalyseAllPlaysPBN.cpp.
{
  boardsPBN bo;
  playTracesPBN DDplays;
  solvedPlays solved;
  int chunkSize = 1, res;
  char line[80];
  bool match;
#if defined(__linux) || defined(__APPLE__)
  SetMaxThreads(0);
#endif
  bo.noOfBoards = 3;
  DDplays.noOfBoards = 3;
  for (int handno = 0; handno < 3; handno++)
  {
    bo.deals[handno].trump = trump[handno];
    bo.deals[handno].first = first[handno];
    bo.deals[handno].currentTrickSuit[0] = 0;
    bo.deals[handno].currentTrickSuit[1] = 0;
    bo.deals[handno].currentTrickSuit[2] = 0;
    bo.deals[handno].currentTrickRank[0] = 0;
    bo.deals[handno].currentTrickRank[1] = 0;
    bo.deals[handno].currentTrickRank[2] = 0;
    strcpy(bo.deals[handno].remainCards, PBN[handno]);
    DDplays.plays[handno].number = playNo[handno];
    strcpy(DDplays.plays[handno].cards, play[handno]);
  }
  res = AnalyseAllPlaysPBN(&bo, &DDplays, &solved, chunkSize);
  if (res != RETURN_NO_FAULT)
  {
    ErrorMessage(res, line);
    printf("DDS error: %s\n", line);
  }
  for (int handno = 0; handno < 3; handno++)
  {
    match = ComparePlay(&solved.solved[handno], handno);
    sprintf(line, "AnalyseAllPlaysBin, hand %d: %s\n",
            handno + 1, (match ? "OK" : "ERROR"));
    PrintPBNHand(line, bo.deals[handno].remainCards);
    PrintPBNPlay(&DDplays.plays[handno], &solved.solved[handno]);
  }
}
References AnalyseAllPlaysPBN(), playTracePBN::cards, ComparePlay(), dealPBN::currentTrickRank, dealPBN::currentTrickSuit, boardsPBN::deals, ErrorMessage(), dealPBN::first, first, boardsPBN::noOfBoards, playTracesPBN::noOfBoards, playTracePBN::number, PBN, play, playNo, playTracesPBN::plays, PrintPBNHand(), PrintPBNPlay(), dealPBN::remainCards, RETURN_NO_FAULT, SetMaxThreads(), dealPBN::trump, and trump.
Variable Documentation
dcardRank
unsigned char dcardRank[16]
Definition at line 21 of file AnalyseAllPlaysPBN.cpp.
dcardSuit
unsigned char dcardSuit[5] extern
Definition at line 268 of file hands.cpp.
{ 'S', 'H', 'D', 'C', 'N' };