open spiel: open_spiel/games/bridge/double_dummy_solver/examples/AnalysePlayPBN.cpp File Reference
AnalysePlayPBN.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/dll.h"
#include "hands.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 21 of file AnalysePlayPBN.cpp.
{
  dealPBN dlPBN;
  playTracePBN DDplayPBN;
  solvedPlay solved;
  int threadIndex = 0, res;
  char line[80];
  bool match;
#if defined(__linux) || defined(__APPLE__)
  SetMaxThreads(0);
#endif
  for (int handno = 0; handno < 3; handno++)
  {
    dlPBN.trump = trump[handno];
    dlPBN.first = first[handno];
    dlPBN.currentTrickSuit[0] = 0;
    dlPBN.currentTrickSuit[1] = 0;
    dlPBN.currentTrickSuit[2] = 0;
    dlPBN.currentTrickRank[0] = 0;
    dlPBN.currentTrickRank[1] = 0;
    dlPBN.currentTrickRank[2] = 0;
    strcpy(dlPBN.remainCards, PBN[handno]);
    DDplayPBN.number = playNo[handno];
    strcpy(DDplayPBN.cards, play[handno]);
    res = AnalysePlayPBN(dlPBN, DDplayPBN, &solved, threadIndex);
    if (res != RETURN_NO_FAULT)
    {
      ErrorMessage(res, line);
      printf("DDS error: %s\n", line);
    }
    match = ComparePlay(&solved, handno);
    sprintf(line, "AnalysePlayPBNBin, hand %d: %s\n",
            handno + 1, (match ? "OK" : "ERROR"));
    PrintPBNHand(line, dlPBN.remainCards);
    PrintPBNPlay(&DDplayPBN, &solved);
  }
}
References AnalysePlayPBN(), playTracePBN::cards, ComparePlay(), dealPBN::currentTrickRank, dealPBN::currentTrickSuit, ErrorMessage(), dealPBN::first, first, playTracePBN::number, PBN, play, playNo, PrintPBNHand(), PrintPBNPlay(), dealPBN::remainCards, RETURN_NO_FAULT, SetMaxThreads(), dealPBN::trump, and trump.