open spiel: open_spiel/games/bridge/double_dummy_solver/examples/AnalysePlayBin.cpp File Reference
AnalysePlayBin.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/dll.h"
#include "hands.h"
Functions
int main ()
Variables
unsigned char dcardSuit [5]
unsigned char dcardRank [16]
Function Documentation
main()
int main ()
Definition at line 23 of file AnalysePlayBin.cpp.
{
  deal dl;
  playTraceBin DDplay;
  solvedPlay solved;
  int threadIndex = 0, res;
  char line[80];
  bool match;
#if defined(__linux) || defined(__APPLE__)
  SetMaxThreads(0);
#endif
  for (int handno = 0; handno < 3; handno++)
  {
    dl.trump = trump[handno];
    dl.first = first[handno];
    dl.currentTrickSuit[0] = 0;
    dl.currentTrickSuit[1] = 0;
    dl.currentTrickSuit[2] = 0;
    dl.currentTrickRank[0] = 0;
    dl.currentTrickRank[1] = 0;
    dl.currentTrickRank[2] = 0;
    for (int h = 0; h < DDS_HANDS; h++)
      for (int s = 0; s < DDS_SUITS; s++)
        dl.remainCards[h][s] = holdings[handno][s][h];
    DDplay.number = playNo[handno];
    for (int i = 0; i < playNo[handno]; i++)
    {
      DDplay.suit[i] = playSuit[handno][i];
      DDplay.rank[i] = playRank[handno][i];
    }
    res = AnalysePlayBin(dl, DDplay, &solved, threadIndex);
    if (res != RETURN_NO_FAULT)
    {
      ErrorMessage(res, line);
      printf("DDS error: %s\n", line);
    }
    match = ComparePlay(&solved, handno);
    sprintf(line, "AnalysePlayBin, hand %d: %s\n",
            handno + 1, (match ? "OK" : "ERROR"));
    PrintHand(line, dl.remainCards);
    PrintBinPlay(&DDplay, &solved);
  }
}
References AnalysePlayBin(), ComparePlay(), deal::currentTrickRank, deal::currentTrickSuit, DDS_HANDS, DDS_SUITS, ErrorMessage(), deal::first, first, holdings, i, playTraceBin::number, playNo, playRank, playSuit, PrintBinPlay(), PrintHand(), playTraceBin::rank, deal::remainCards, RETURN_NO_FAULT, SetMaxThreads(), playTraceBin::suit, deal::trump, and trump.
Variable Documentation
dcardRank
unsigned char dcardRank[16]
Definition at line 21 of file AnalysePlayBin.cpp.
dcardSuit
unsigned char dcardSuit[5] extern
Definition at line 268 of file hands.cpp.
{ 'S', 'H', 'D', 'C', 'N' };
Referenced by PrintBinPlay(), PrintFut(), and PrintTable().