open spiel: open_spiel/games/bridge/double_dummy_solver/examples/CalcAllTablesPBN.cpp File Reference
CalcAllTablesPBN.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/dll.h"
#include "hands.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 21 of file CalcAllTablesPBN.cpp.
{
  ddTableDealsPBN DDdealsPBN;
  ddTablesRes tableRes;
  allParResults pres;
  int mode = 0; // No par calculation
  int trumpFilter[DDS_STRAINS] = {0, 0, 0, 0, 0}; // All
  int res;
  char line[80];
  bool match;
#if defined(__linux) || defined(__APPLE__)
  SetMaxThreads(0);
#endif
  DDdealsPBN.noOfTables = 3;
  for (int handno = 0; handno < 3; handno++)
  {
    strcpy(DDdealsPBN.deals[handno].cards, PBN[handno]);
  }
  res = CalcAllTablesPBN(&DDdealsPBN, mode, trumpFilter,
                         &tableRes, &pres);
  if (res != RETURN_NO_FAULT)
  {
    ErrorMessage(res, line);
    printf("DDS error: %s\n", line);
  }
  for (int handno = 0; handno < 3; handno++)
  {
    match = CompareTable(&tableRes.results[handno], handno);
    sprintf(line,
            "CalcDDtable, hand %d: %s\n",
            handno + 1, (match ? "OK" : "ERROR"));
    PrintPBNHand(line, DDdealsPBN.deals[handno].cards);
    PrintTable(&tableRes.results[handno]);
  }
}
References CalcAllTablesPBN(), ddTableDealPBN::cards, CompareTable(), DDS_STRAINS, ddTableDealsPBN::deals, ErrorMessage(), ddTableDealsPBN::noOfTables, PBN, PrintPBNHand(), PrintTable(), ddTablesRes::results, RETURN_NO_FAULT, and SetMaxThreads().