open spiel: open_spiel/games/bridge/double_dummy_solver/examples/CalcDDtable.cpp File Reference
CalcDDtable.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/dll.h"
#include "hands.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 21 of file CalcDDtable.cpp.
{
  ddTableDeal tableDeal;
  ddTableResults table;
  int res;
  char line[80];
  bool match;
#if defined(__linux) || defined(__APPLE__)
  SetMaxThreads(0);
#endif
  for (int handno = 0; handno < 3; handno++)
  {
    for (int h = 0; h < DDS_HANDS; h++)
      for (int s = 0; s < DDS_SUITS; s++)
        tableDeal.cards[h][s] = holdings[handno][s][h];
    res = CalcDDtable(tableDeal, &table);
    if (res != RETURN_NO_FAULT)
    {
      ErrorMessage(res, line);
      printf("DDS error: %s\n", line);
    }
    match = CompareTable(&table, handno);
    sprintf(line,
            "CalcDDtable, hand %d: %s\n",
            handno + 1, (match ? "OK" : "ERROR"));
    PrintHand(line, tableDeal.cards);
    PrintTable(&table);
  }
}
References CalcDDtable(), ddTableDeal::cards, CompareTable(), DDS_HANDS, DDS_SUITS, ErrorMessage(), holdings, PrintHand(), PrintTable(), RETURN_NO_FAULT, and SetMaxThreads().