open spiel: open_spiel/games/bridge/double_dummy_solver/examples/CalcAllTables.cpp File Reference
CalcAllTables.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/dll.h"
#include "hands.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 21 of file CalcAllTables.cpp.
{
  ddTableDeals DDdeals;
  ddTablesRes tableRes;
  allParResults pres;
  int mode = 0; // No par calculation
  int trumpFilter[DDS_STRAINS] = {0, 0, 0, 0, 0}; // All
  int res;
  char line[80];
  bool match;
#if defined(__linux) || defined(__APPLE__)
  SetMaxThreads(0);
#endif
  DDdeals.noOfTables = 3;
  for (int handno = 0; handno < 3; handno++)
  {
    for (int h = 0; h < DDS_HANDS; h++)
      for (int s = 0; s < DDS_SUITS; s++)
        DDdeals.deals[handno].cards[h][s] = holdings[handno][s][h];
  }
  res = CalcAllTables(&DDdeals, mode, trumpFilter, &tableRes, &pres);
  if (res != RETURN_NO_FAULT)
  {
    ErrorMessage(res, line);
    printf("DDS error: %s\n", line);
  }
  for (int handno = 0; handno < 3; handno++)
  {
    match = CompareTable(&tableRes.results[handno], handno);
    sprintf(line,
            "CalcDDtable, hand %d: %s\n",
            handno + 1, (match ? "OK" : "ERROR"));
    PrintHand(line, DDdeals.deals[handno].cards);
    PrintTable(&tableRes.results[handno]);
  }
}
References CalcAllTables(), ddTableDeal::cards, CompareTable(), DDS_HANDS, DDS_STRAINS, DDS_SUITS, ddTableDeals::deals, ErrorMessage(), holdings, ddTableDeals::noOfTables, PrintHand(), PrintTable(), ddTablesRes::results, RETURN_NO_FAULT, and SetMaxThreads().