open spiel: open_spiel/games/bridge/double_dummy_solver/src/CalcTables.h File Reference
CalcTables.h File Reference
#include <vector>
#include "dds.h"
Functions
void CalcSingleCommon (const int thrID, const int bno)
void CopyCalcSingle (const vector< int > &crossrefs)
void CalcChunkCommon (const int thrId)
void DetectCalcDuplicates (const boards &bds, vector< int > &uniques, vector< int > &crossrefs)
Function Documentation
CalcChunkCommon()
void CalcChunkCommon (const int thrId)
Definition at line 90 of file CalcTables.cpp.
{
  // Solves each deal and strain for all four declarers.
  vector<futureTricks> fut;
  fut.resize(static_cast<unsigned>(cparam.noOfBoards));
  int index;
  schedType st;
  while (1)
  {
    st = scheduler.GetNumber(thrId);
    index = st.number;
    if (index == -1)
      break;
    if (st.repeatOf != -1)
    {
      START_THREAD_TIMER(thrId);
      for (int k = 0; k < DDS_HANDS; k++)
      {
        cparam.bop->deals[index].first = k;
        cparam.solvedp->solvedBoard[index].score[k] =
          cparam.solvedp->solvedBoard[ st.repeatOf ].score[k];
      }
      END_THREAD_TIMER(thrId);
      continue;
    }
    CalcSingleCommon(thrId, index);
  }
}
References paramType::bop, CalcSingleCommon(), cparam, DDS_HANDS, boards::deals, END_THREAD_TIMER, deal::first, Scheduler::GetNumber(), paramType::noOfBoards, schedType::number, schedType::repeatOf, scheduler, futureTricks::score, solvedBoards::solvedBoard, paramType::solvedp, and START_THREAD_TIMER.
Referenced by System::Reset().
CalcSingleCommon()
void CalcSingleCommon (const int thrID, const int bno)
Definition at line 31 of file CalcTables.cpp.
{
  // Solves a single deal and strain for all four declarers.
  futureTricks fut;
  cparam.bop->deals[bno].first = 0;
  START_THREAD_TIMER(thrId);
  int res = SolveBoard(
                cparam.bop->deals[bno],
                cparam.bop->target[bno],
                cparam.bop->solutions[bno],
                cparam.bop->mode[bno],
                &fut,
                thrId);
  // SH: I'm making a terrible use of the fut structure here.
  if (res == 1)
    cparam.solvedp->solvedBoard[bno].score[0] = fut.score[0];
  else
    cparam.error = res;
  ThreadData * thrp = memory.GetPtr(static_cast<unsigned>(thrId));
  for (int k = 1; k < DDS_HANDS; k++)
  {
    int hint = (k == 2 ? fut.score[0] : 13 - fut.score[0]);
    cparam.bop->deals[bno].first = k; // Next declarer
    res = SolveSameBoard(thrp, cparam.bop->deals[bno], &fut, hint);
    if (res == 1)
      cparam.solvedp->solvedBoard[bno].score[k] = fut.score[0];
    else
      cparam.error = res;
  }
  END_THREAD_TIMER(thrId);
}
References paramType::bop, cparam, DDS_HANDS, boards::deals, END_THREAD_TIMER, paramType::error, deal::first, Memory::GetPtr(), memory, boards::mode, futureTricks::score, boards::solutions, SolveBoard(), solvedBoards::solvedBoard, paramType::solvedp, SolveSameBoard(), START_THREAD_TIMER, and boards::target.
Referenced by CalcChunkCommon(), and System::Reset().
CopyCalcSingle()
void CopyCalcSingle (const vector< int > & crossrefs)
Definition at line 74 of file CalcTables.cpp.
{
  for (unsigned i = 0; i < crossrefs.size(); i++)
  {
    if (crossrefs[i] == -1)
      continue;
    START_THREAD_TIMER(thrId);
    for (int k = 0; k < DDS_HANDS; k++)
      cparam.solvedp->solvedBoard[i].score[k] =
        cparam.solvedp->solvedBoard[ crossrefs[i] ].score[k];
    END_THREAD_TIMER(thrId);
  }
}
References cparam, DDS_HANDS, END_THREAD_TIMER, i, futureTricks::score, solvedBoards::solvedBoard, paramType::solvedp, and START_THREAD_TIMER.
Referenced by System::Reset().
DetectCalcDuplicates()
void DetectCalcDuplicates (const boards & bds, vector< int > & uniques, vector< int > & crossrefs)
Definition at line 354 of file CalcTables.cpp.
{
  // Could save a little bit of time with a dedicated checker that
  // only looks at the cards.
  return DetectSolveDuplicates(bds, uniques, crossrefs);
}
References DetectSolveDuplicates().
Referenced by System::Reset().