open spiel: open_spiel/games/bridge/double_dummy_solver/examples/CalcDDtablePBN.cpp File Reference
CalcDDtablePBN.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/dll.h"
#include "hands.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 21 of file CalcDDtablePBN.cpp.
{
  ddTableDealPBN tableDealPBN;
  ddTableResults table;
  int res;
  char line[80];
  bool match;
#if defined(__linux) || defined(__APPLE__)
  SetMaxThreads(0);
#endif
  for (int handno = 0; handno < 3; handno++)
  {
    strcpy(tableDealPBN.cards, PBN[handno]);
    res = CalcDDtablePBN(tableDealPBN, &table);
    if (res != RETURN_NO_FAULT)
    {
      ErrorMessage(res, line);
      printf("DDS error: %s\n", line);
    }
    match = CompareTable(&table, handno);
    sprintf(line,
            "CalcDDtable, hand %d: %s\n",
            handno + 1, (match ? "OK" : "ERROR"));
    PrintPBNHand(line, tableDealPBN.cards);
    PrintTable(&table);
  }
}
References CalcDDtablePBN(), ddTableDealPBN::cards, CompareTable(), ErrorMessage(), PBN, PrintPBNHand(), PrintTable(), RETURN_NO_FAULT, and SetMaxThreads().