open spiel: open_spiel/games/bridge/double_dummy_solver/src/PBN.cpp File Reference
PBN.cpp File Reference
#include "dds.h"
#include "PBN.h"
Functions
int IsCard (const char cardChar)
int ConvertFromPBN (char const *dealBuff, unsigned int remainCards[DDS_HANDS][DDS_SUITS])
int ConvertPlayFromPBN (const playTracePBN &playPBN, playTraceBin &playBin)
Function Documentation
ConvertFromPBN()
int ConvertFromPBN (char const * dealBuff, unsigned int remainCards[DDS_HANDS][DDS_SUITS])
Definition at line 17 of file PBN.cpp.
{
  for (int h = 0; h < DDS_HANDS; h++)
    for (int s = 0; s < DDS_SUITS; s++)
      remainCards[h][s] = 0;
  int bp = 0;
  while (((dealBuff[bp] != 'W') && (dealBuff[bp] != 'N') &&
          (dealBuff[bp] != 'E') && (dealBuff[bp] != 'S') &&
          (dealBuff[bp] != 'w') && (dealBuff[bp] != 'n') &&
          (dealBuff[bp] != 'e') && (dealBuff[bp] != 's')) && (bp < 3))
    bp++;
  if (bp >= 3)
    return 0;
  int first;
  if ((dealBuff[bp] == 'N') || (dealBuff[bp] == 'n'))
    first = 0;
  else if ((dealBuff[bp] == 'E') || (dealBuff[bp] == 'e'))
    first = 1;
  else if ((dealBuff[bp] == 'S') || (dealBuff[bp] == 's'))
    first = 2;
  else
    first = 3;
  bp++;
  bp++;
  int handRelFirst = 0;
  int suitInHand = 0;
  int card, hand;
  while ((bp < 80) && (dealBuff[bp] != '\0'))
  {
    card = IsCard(dealBuff[bp]);
    if (card)
    {
      switch (first)
      {
        case 0:
          hand = handRelFirst;
          break;
        case 1:
          if (handRelFirst == 0)
            hand = 1;
          else if (handRelFirst == 3)
            hand = 0;
          else
            hand = handRelFirst + 1;
          break;
        case 2:
          if (handRelFirst == 0)
            hand = 2;
          else if (handRelFirst == 1)
            hand = 3;
          else
            hand = handRelFirst - 2;
          break;
        default:
          if (handRelFirst == 0)
            hand = 3;
          else
            hand = handRelFirst - 1;
      }
      remainCards[hand][suitInHand] |=
        static_cast<unsigned>((bitMapRank[card] << 2));
    }
    else if (dealBuff[bp] == '.')
      suitInHand++;
    else if (dealBuff[bp] == ' ')
    {
      handRelFirst++;
      suitInHand = 0;
    }
    bp++;
  }
  return RETURN_NO_FAULT;
}
References bitMapRank, DDS_HANDS, DDS_SUITS, first, IsCard(), and RETURN_NO_FAULT.
Referenced by AnalyseAllPlaysPBN(), AnalysePlayPBN(), CalcAllTablesPBN(), CalcDDtablePBN(), CalcParPBN(), SolveAllBoards(), and SolveBoardPBN().
ConvertPlayFromPBN()
int ConvertPlayFromPBN (const playTracePBN & playPBN, playTraceBin & playBin)
Definition at line 143 of file PBN.cpp.
{
  const int n = playPBN.number;
  if (n < 0 || n > 52)
    return RETURN_PLAY_FAULT;
  playBin.number = n;
  for (int i = 0; i < 2 * n; i += 2)
  {
    char suit = playPBN.cards[i];
    int s;
    if (suit == 's' || suit == 'S')
      s = 0;
    else if (suit == 'h' || suit == 'H')
      s = 1;
    else if (suit == 'd' || suit == 'D')
      s = 2;
    else if (suit == 'c' || suit == 'C')
      s = 3;
    else
      return RETURN_PLAY_FAULT;
    playBin.suit[i >> 1] = s;
    int rank = IsCard(playPBN.cards[i+1]);
    if (rank == 0)
      return RETURN_PLAY_FAULT;
    playBin.rank[i >> 1] = rank;
  }
  return RETURN_NO_FAULT;
}
References playTracePBN::cards, i, IsCard(), n, playTraceBin::number, playTracePBN::number, playTraceBin::rank, rank, RETURN_NO_FAULT, RETURN_PLAY_FAULT, and playTraceBin::suit.
Referenced by AnalyseAllPlaysPBN(), and AnalysePlayPBN().
IsCard()
int IsCard (const char cardChar)
Definition at line 102 of file PBN.cpp.
{
  switch (cardChar)
  {
    case '2':
      return 2;
    case '3':
      return 3;
    case '4':
      return 4;
    case '5':
      return 5;
    case '6':
      return 6;
    case '7':
      return 7;
    case '8':
      return 8;
    case '9':
      return 9;
    case 'T':
    case 't':
      return 10;
    case 'J':
    case 'j':
      return 11;
    case 'Q':
    case 'q':
      return 12;
    case 'K':
    case 'k':
      return 13;
    case 'A':
    case 'a':
      return 14;
    default:
      return 0;
  }
}
Referenced by ConvertFromPBN(), and ConvertPlayFromPBN().