open spiel: open_spiel/games/bridge/double_dummy_solver/src/PlayAnalyser.h File Reference
PlayAnalyser.h File Reference
#include <vector>
#include "dds.h"
Functions
void PlaySingleCommon (const int thrId, const int bno)
void PlayChunkCommon (const int thrId)
void DetectPlayDuplicates (const boards &bds, vector< int > &uniques, vector< int > &crossrefs)
void CopyPlaySingle (const vector< int > &crossrefs)
Function Documentation
CopyPlaySingle()
void CopyPlaySingle (const vector< int > & crossrefs)
Definition at line 416 of file PlayAnalyser.cpp.
{
  UNUSED(crossrefs);
}
References UNUSED.
Referenced by System::Reset().
DetectPlayDuplicates()
void DetectPlayDuplicates (const boards & bds, vector< int > & uniques, vector< int > & crossrefs)
Definition at line 396 of file PlayAnalyser.cpp.
{
  // This dummy function is there for consistency in System.cpp.
  // In practice there is not much point in deteting play repeats,
  // as it is highly unlikely that the play went identically at
  // two tables.
  uniques.resize(static_cast<unsigned>(bds.noOfBoards));
  crossrefs.resize(static_cast<unsigned>(bds.noOfBoards));
  for (unsigned i = 0; i < uniques.size(); i++)
  {
    uniques[i] = static_cast<int>(i);
    crossrefs[i] = -1;
  }
}
References i, and boards::noOfBoards.
Referenced by System::Reset().
PlayChunkCommon()
void PlayChunkCommon (const int thrId)
Definition at line 288 of file PlayAnalyser.cpp.
{
  int index;
  schedType st;
  while (1)
  {
    st = scheduler.GetNumber(thrId);
    index = st.number;
    if (index == -1)
      break;
    PlaySingleCommon(thrId, index);
  }
}
References Scheduler::GetNumber(), schedType::number, PlaySingleCommon(), and scheduler.
Referenced by System::Reset().
PlaySingleCommon()
void PlaySingleCommon (const int thrId, const int bno)
Definition at line 268 of file PlayAnalyser.cpp.
{
  solvedPlay solved;
  int res = AnalysePlayBin(
    playparam.bop->deals[bno],
    traceparam.plp->plays[bno],
    &solved,
    thrId);
  // If there are multiple errors, this will catch one of them.
  if (res == 1)
    traceparam.solvedp->solved[bno] = solved;
  else
   playparam.error = res;
}
References AnalysePlayBin(), paramType::bop, boards::deals, paramType::error, playparam, playTracesBin::plays, playparamType::plp, solvedPlays::solved, playparamType::solvedp, and traceparam.
Referenced by PlayChunkCommon(), and System::Reset().