open spiel: open_spiel/games/bridge/double_dummy_solver/src/PlayAnalyser.cpp File Reference
PlayAnalyser.cpp File Reference
#include "PlayAnalyser.h"
#include "SolverIF.h"
#include "System.h"
#include "Memory.h"
#include "Scheduler.h"
#include "PBN.h"
#include "debug.h"
Classes
struct playparamType
Macros
#define DEBUG 0
Functions
int STDCALL AnalysePlayBin (deal dl, playTraceBin play, solvedPlay *solvedp, int thrId)
int STDCALL AnalysePlayPBN (dealPBN dlPBN, playTracePBN playPBN, solvedPlay *solvedp, int thrId)
void PlaySingleCommon (const int thrId, const int bno)
void PlayChunkCommon (const int thrId)
int STDCALL AnalyseAllPlaysBin (boards *bop, playTracesBin *plp, solvedPlays *solvedp, int chunkSize)
int STDCALL AnalyseAllPlaysPBN (boardsPBN *bopPBN, playTracesPBN *plpPBN, solvedPlays *solvedp, int chunkSize)
void DetectPlayDuplicates (const boards &bds, vector< int > &uniques, vector< int > &crossrefs)
void CopyPlaySingle (const vector< int > &crossrefs)
Variables
paramType playparam
playparamType traceparam
System sysdep
Memory memory
Scheduler scheduler
Macro Definition Documentation
DEBUG
#define DEBUG 0
Definition at line 22 of file PlayAnalyser.cpp.
Function Documentation
AnalyseAllPlaysBin()
int STDCALL AnalyseAllPlaysBin (boards * bop, playTracesBin * plp, solvedPlays * solvedp, int chunkSize)
Definition at line 305 of file PlayAnalyser.cpp.
{
  UNUSED(chunkSize);
  playparam.error = 0;
  if (bop->noOfBoards > MAXNOOFBOARDS)
    return RETURN_TOO_MANY_BOARDS;
  if (bop->noOfBoards != plp->noOfBoards)
    return RETURN_UNKNOWN_FAULT;
  playparam.bop = bop;
  traceparam.plp = plp;
  playparam.noOfBoards = bop->noOfBoards;
  traceparam.noOfBoards = bop->noOfBoards;
  traceparam.solvedp = solvedp;
  scheduler.RegisterRun(DDS_RUN_TRACE, * bop, * plp);
  sysdep.RegisterRun(DDS_RUN_TRACE, * bop);
  START_BLOCK_TIMER;
  int retRun = sysdep.RunThreads();
  END_BLOCK_TIMER;
  if (retRun != RETURN_NO_FAULT)
    return retRun;
  solvedp->noOfBoards = bop->noOfBoards;
#ifdef DDS_SCHEDULER
  scheduler.PrintTiming();
#endif
  if (playparam.error == 0)
    return RETURN_NO_FAULT;
  else
    return playparam.error;
}
References paramType::bop, DDS_RUN_TRACE, END_BLOCK_TIMER, paramType::error, MAXNOOFBOARDS, boards::noOfBoards, paramType::noOfBoards, playparamType::noOfBoards, playTracesBin::noOfBoards, solvedPlays::noOfBoards, playparam, playparamType::plp, Scheduler::RegisterRun(), System::RegisterRun(), RETURN_NO_FAULT, RETURN_TOO_MANY_BOARDS, RETURN_UNKNOWN_FAULT, System::RunThreads(), scheduler, playparamType::solvedp, START_BLOCK_TIMER, sysdep, traceparam, and UNUSED.
Referenced by AnalyseAllPlaysPBN(), and main().
AnalyseAllPlaysPBN()
int STDCALL AnalyseAllPlaysPBN (boardsPBN * bopPBN, playTracesPBN * plpPBN, solvedPlays * solvedp, int chunkSize)
Definition at line 350 of file PlayAnalyser.cpp.
{
  boards bd;
  playTracesBin pl;
  bd.noOfBoards = bopPBN->noOfBoards;
  if (bd.noOfBoards > MAXNOOFBOARDS)
    return RETURN_TOO_MANY_BOARDS;
  for (int k = 0; k < bopPBN->noOfBoards; k++)
  {
    deal& dl = bd.deals[k];
    dealPBN& dlp = bopPBN->deals[k];
    if (ConvertFromPBN(dlp.remainCards,
                       dl.remainCards) != RETURN_NO_FAULT)
      return RETURN_PBN_FAULT;
    dl.trump = dlp.trump;
    dl.first = dlp.first;
    for (int i = 0; i <= 2; i++)
    {
      dl.currentTrickSuit[i] = dlp.currentTrickSuit[i];
      dl.currentTrickRank[i] = dlp.currentTrickRank[i];
    }
  }
  pl.noOfBoards = plpPBN->noOfBoards;
  for (int k = 0; k < plpPBN->noOfBoards; k++)
  {
    if (ConvertPlayFromPBN(plpPBN->plays[k], pl.plays[k]) !=
        RETURN_NO_FAULT)
      return RETURN_PLAY_FAULT;
  }
  chunkSize = 1;
  return AnalyseAllPlaysBin(&bd, &pl, solvedp, chunkSize);
}
References AnalyseAllPlaysBin(), ConvertFromPBN(), ConvertPlayFromPBN(), deal::currentTrickRank, dealPBN::currentTrickRank, deal::currentTrickSuit, dealPBN::currentTrickSuit, boards::deals, boardsPBN::deals, deal::first, dealPBN::first, i, MAXNOOFBOARDS, boards::noOfBoards, boardsPBN::noOfBoards, playTracesBin::noOfBoards, playTracesPBN::noOfBoards, playTracesBin::plays, playTracesPBN::plays, deal::remainCards, dealPBN::remainCards, RETURN_NO_FAULT, RETURN_PBN_FAULT, RETURN_PLAY_FAULT, RETURN_TOO_MANY_BOARDS, deal::trump, and dealPBN::trump.
Referenced by loop_play(), and main().
AnalysePlayBin()
int STDCALL AnalysePlayBin (deal dl, playTraceBin play, solvedPlay * solvedp, int thrId)
Definition at line 44 of file PlayAnalyser.cpp.
{
  if (! sysdep.ThreadOK(thrId))
    return RETURN_THREAD_INDEX;
  ThreadData * thrp = memory.GetPtr(static_cast<unsigned>(thrId));
  moveType move;
  futureTricks fut;
  int ret = SolveBoardInternal(thrp, dl, -1, 1, 1, &fut);
  if (ret != RETURN_NO_FAULT)
    return ret;
  const int numTricks = ((thrp->iniDepth + 3) >> 2) + 1;
  const int numCardsPlayed = ((48 - thrp->iniDepth) % 4) + 1;
  int last_trick = (play.number + 3) / 4;
  int last_card = ((play.number + 3) % 4) + 1;
  if (last_trick >= numTricks)
  {
    last_trick = numTricks-1;
    last_card = 4;
  }
  solvedp->number = 0;
  solvedp->tricks[0] = (numCardsPlayed % 2 == 1 ?
    numTricks - fut.score[0] : fut.score[0]);
  int hint = solvedp->tricks[0];
  int hintDir;
  int running_remainder = numTricks;
  int running_declarer = 0;
  int running_player = dl.first;
  int running_side = 1; /* defenders */
  int start_side = running_player % 2;
  int solved_declarer = solvedp->tricks[0];
#if DEBUG
  int initial_par = solved_declarer;
  fout.open("trace.txt", ofstream::out | ofstream::app);
  fout << "Initial solve: " << initial_par << "\n";
  fout << "no " << play.number << ", Last trick " << last_trick <<
    ", last card " << last_card << "\n";
  fout << setw(5) << "trick" << setw(6) << "card" <<
    setw(6) << "rest" << setw(9) << "declarer" <<
    setw(7) << "player" << setw(7) << "side" <<
    setw(6) << "soln0" << setw(6) << "soln1" << setw(6) << "diff" << "\n";
#endif
  for (int trick = 1; trick <= last_trick; trick++)
  {
    int best_card = 0, best_suit = 0, best_player = 0, trump_played = 0;
    int lc = (trick == last_trick ? last_card : 4);
    bool haveCurrent = (numCardsPlayed > 1 && trick == 1);
    int offset = 4 * (trick - 1) - (numCardsPlayed - 1);
    for (int card = 1; card <= lc; card++)
    {
      int suit, rr;
      bool usingCurrent = (haveCurrent && card < numCardsPlayed);
      if (usingCurrent)
      {
        suit = dl.currentTrickSuit[card - 1];
        rr = dl.currentTrickRank[card - 1];
      }
      else
      {
        suit = play.suit[offset + card - 1];
        rr = play.rank[offset + card - 1];
      }
      unsigned hold = static_cast<unsigned>(bitMapRank[rr] << 2);
      move.suit = suit;
      move.rank = rr;
      move.sequence = rr;
      /* Keep track of the winner of the trick so far */
      if (card == 1)
      {
        best_card = rr;
        best_suit = suit;
        best_player = dl.first;
        trump_played = (suit == dl.trump ? 1 : 0);
      }
      else if (suit == dl.trump)
      {
        if (! trump_played || rr > best_card)
        {
          best_card = rr;
          best_suit = suit;
          best_player = running_player;
          trump_played = 1;
        }
      }
      else if (! trump_played && suit == best_suit && rr > best_card)
      {
        best_card = rr;
        best_player = running_player;
      }
      if ((dl.remainCards[running_player][suit] & hold) == 0)
      {
        if (! usingCurrent)
        {
#if DEBUG
          fout << "ERR Trick " << trick << " card " << card <<
            " pl " << running_player << ": suit " << suit <<
            " hold " << hold << "\n";
          fout.close();
#endif
          return RETURN_PLAY_FAULT;
        }
      }
      else
        dl.remainCards[running_player][suit] ^= hold;
#if DEBUG
      int resp_player = running_player;
#endif
      if (card == 4)
      {
        running_declarer += (best_player % 2 == start_side ? 0 : 1);
        running_remainder--;
        if ((dl.first + best_player) % 2 == 0)
        {
          hintDir = 0; // Same side leads again; lower bound
          hint = running_remainder - fut.score[0];
        }
        else
        {
          hintDir = 1; // Other ("our") side wins trick; upper bound
          hint = fut.score[0] - 1;
        }
        dl.first = best_player;
        running_side = (dl.first % 2 == start_side ? 1 : 0);
        running_player = dl.first;
      }
      else
      {
        running_player = (running_player + 1) % 4;
        running_side = 1 - running_side;
        hint = running_remainder - fut.score[0];
        hintDir = 0;
      }
      if (usingCurrent)
        continue;
      if ((ret = AnalyseLaterBoard(thrp, dl.first, &move, hint,
        hintDir, &fut))
          != RETURN_NO_FAULT)
      {
#if DEBUG
        fout << "SolveBoard failed, ret " << ret << "\n";
        fout.close();
#endif
        return ret;
      }
      int new_solved_decl = running_declarer + (running_side ?
        running_remainder - fut.score[0] : fut.score[0]);
      solvedp->tricks[offset + card] = new_solved_decl;
#if DEBUG
      fout << setw(5) << trick <<
        setw(6) << card <<
        setw(6) << running_remainder <<
        setw(9) << running_declarer <<
        setw(7) << cardHand[resp_player] <<
        setw(7) << running_side <<
        setw(6) << solved_declarer <<
        setw(6) << new_solved_decl <<
        setw(6) << new_solved_decl - solved_declarer << "\n";
#endif
      solved_declarer = new_solved_decl;
    }
  }
  solvedp->number = 4 * last_trick + last_card - 3 - (numCardsPlayed - 1);
#if DEBUG
  fout.close();
#endif
  return RETURN_NO_FAULT;
}
References AnalyseLaterBoard(), bitMapRank, cardHand, deal::currentTrickRank, deal::currentTrickSuit, deal::first, Memory::GetPtr(), ThreadData::iniDepth, memory, solvedPlay::number, play, deal::remainCards, RETURN_NO_FAULT, RETURN_PLAY_FAULT, RETURN_THREAD_INDEX, futureTricks::score, SolveBoardInternal(), sysdep, System::ThreadOK(), solvedPlay::tricks, and deal::trump.
Referenced by AnalysePlayPBN(), main(), and PlaySingleCommon().
AnalysePlayPBN()
int STDCALL AnalysePlayPBN (dealPBN dlPBN, playTracePBN playPBN, solvedPlay * solvedp, int thrId)
Definition at line 240 of file PlayAnalyser.cpp.
{
  deal dl;
  playTraceBin play;
  if (ConvertFromPBN(dlPBN.remainCards, dl.remainCards) !=
      RETURN_NO_FAULT)
    return RETURN_PBN_FAULT;
  dl.first = dlPBN.first;
  dl.trump = dlPBN.trump;
  for (int i = 0; i <= 2; i++)
  {
    dl.currentTrickSuit[i] = dlPBN.currentTrickSuit[i];
    dl.currentTrickRank[i] = dlPBN.currentTrickRank[i];
  }
  if (ConvertPlayFromPBN(playPBN, play) != RETURN_NO_FAULT)
    return RETURN_PLAY_FAULT;
  return AnalysePlayBin(dl, play, solvedp, thrId);
}
References AnalysePlayBin(), ConvertFromPBN(), ConvertPlayFromPBN(), deal::currentTrickRank, dealPBN::currentTrickRank, deal::currentTrickSuit, dealPBN::currentTrickSuit, deal::first, dealPBN::first, i, play, deal::remainCards, dealPBN::remainCards, RETURN_NO_FAULT, RETURN_PBN_FAULT, RETURN_PLAY_FAULT, deal::trump, and dealPBN::trump.
Referenced by main().
CopyPlaySingle()
void CopyPlaySingle (const vector< int > & crossrefs)
Definition at line 416 of file PlayAnalyser.cpp.
{
  UNUSED(crossrefs);
}
References UNUSED.
Referenced by System::Reset().
DetectPlayDuplicates()
void DetectPlayDuplicates (const boards & bds, vector< int > & uniques, vector< int > & crossrefs)
Definition at line 396 of file PlayAnalyser.cpp.
{
  // This dummy function is there for consistency in System.cpp.
  // In practice there is not much point in deteting play repeats,
  // as it is highly unlikely that the play went identically at
  // two tables.
  uniques.resize(static_cast<unsigned>(bds.noOfBoards));
  crossrefs.resize(static_cast<unsigned>(bds.noOfBoards));
  for (unsigned i = 0; i < uniques.size(); i++)
  {
    uniques[i] = static_cast<int>(i);
    crossrefs[i] = -1;
  }
}
References i, and boards::noOfBoards.
Referenced by System::Reset().
PlayChunkCommon()
void PlayChunkCommon (const int thrId)
Definition at line 288 of file PlayAnalyser.cpp.
{
  int index;
  schedType st;
  while (1)
  {
    st = scheduler.GetNumber(thrId);
    index = st.number;
    if (index == -1)
      break;
    PlaySingleCommon(thrId, index);
  }
}
References Scheduler::GetNumber(), schedType::number, PlaySingleCommon(), and scheduler.
Referenced by System::Reset().
PlaySingleCommon()
void PlaySingleCommon (const int thrId, const int bno)
Definition at line 268 of file PlayAnalyser.cpp.
{
  solvedPlay solved;
  int res = AnalysePlayBin(
    playparam.bop->deals[bno],
    traceparam.plp->plays[bno],
    &solved,
    thrId);
  // If there are multiple errors, this will catch one of them.
  if (res == 1)
    traceparam.solvedp->solved[bno] = solved;
  else
   playparam.error = res;
}
References AnalysePlayBin(), paramType::bop, boards::deals, paramType::error, playparam, playTracesBin::plays, playparamType::plp, solvedPlays::solved, playparamType::solvedp, and traceparam.
Referenced by PlayChunkCommon(), and System::Reset().
Variable Documentation
memory
Memory memory extern
Definition at line 22 of file Init.cpp.
Referenced by AnalysePlayBin().
playparam
paramType playparam
Definition at line 36 of file PlayAnalyser.cpp.
Referenced by AnalyseAllPlaysBin(), and PlaySingleCommon().
scheduler
Scheduler scheduler extern
Definition at line 23 of file Init.cpp.
Referenced by AnalyseAllPlaysBin(), and PlayChunkCommon().
sysdep
System sysdep extern
Definition at line 21 of file Init.cpp.
Referenced by AnalyseAllPlaysBin(), and AnalysePlayBin().
traceparam
playparamType traceparam
Definition at line 37 of file PlayAnalyser.cpp.
Referenced by AnalyseAllPlaysBin(), and PlaySingleCommon().