open spiel: open_spiel/games/bridge/double_dummy_solver/src/SolveBoard.h File Reference
SolveBoard.h File Reference
#include <vector>
#include "dds.h"
Functions
void SolveSingleCommon (const int thrId, const int bno)
void CopySolveSingle (const vector< int > &crossrefs)
void SolveChunkCommon (const int thrId)
void DetectSolveDuplicates (const boards &bds, vector< int > &uniques, vector< int > &crossrefs)
Function Documentation
CopySolveSingle()
void CopySolveSingle (const vector< int > & crossrefs)
Definition at line 59 of file SolveBoard.cpp.
{
  for (unsigned i = 0; i < crossrefs.size(); i++)
  {
    if (crossrefs[i] == -1)
      continue;
    START_THREAD_TIMER(thrId);
    param.solvedp->solvedBoard[i] =
      param.solvedp->solvedBoard[crossrefs[i]];
    END_THREAD_TIMER(thrId);
  }
}
References END_THREAD_TIMER, i, param, solvedBoards::solvedBoard, paramType::solvedp, and START_THREAD_TIMER.
Referenced by System::Reset().
DetectSolveDuplicates()
void DetectSolveDuplicates (const boards & bds, vector< int > & uniques, vector< int > & crossrefs)
Definition at line 246 of file SolveBoard.cpp.
{
  const unsigned nu = static_cast<unsigned>(bds.noOfBoards);
  uniques.clear();
  crossrefs.resize(nu);
  for (unsigned i = 0; i < nu; i++)
    crossrefs[i] = -1;
  for (unsigned i = 0; i < nu; i++)
  {
    if (crossrefs[i] != -1)
      continue;
    uniques.push_back(static_cast<int>(i));
    for (unsigned index = i+1; index < nu; index++)
    {
      if (SameBoard(bds, i, index))
        crossrefs[index] = static_cast<int>(i);
    }
  }
}
References i, boards::noOfBoards, and SameBoard().
Referenced by DetectCalcDuplicates(), and System::Reset().
SolveChunkCommon()
void SolveChunkCommon (const int thrId)
Definition at line 74 of file SolveBoard.cpp.
{
  int index;
  schedType st;
  while (1)
  {
    st = scheduler.GetNumber(thrId);
    index = st.number;
    if (index == -1)
      break;
    // This is not a perfect repeat detector, as the hands in
    // a group might have declarers N, S, N, N. Then the second
    // N would not reuse the first N. However, must reuses are
    // reasonably adjacent, and this is just an optimization anyway.
    if (st.repeatOf != -1 &&
        param.bop->deals[index ].first ==
        param.bop->deals[st.repeatOf].first)
    {
      START_THREAD_TIMER(thrId);
      param.solvedp->solvedBoard[index] =
        param.solvedp->solvedBoard[st.repeatOf];
      END_THREAD_TIMER(thrId);
      continue;
    }
    else
    {
      SolveSingleCommon(thrId, index);
    }
  }
}
References paramType::bop, boards::deals, END_THREAD_TIMER, deal::first, Scheduler::GetNumber(), schedType::number, param, schedType::repeatOf, scheduler, solvedBoards::solvedBoard, paramType::solvedp, SolveSingleCommon(), and START_THREAD_TIMER.
Referenced by System::Reset().
SolveSingleCommon()
void SolveSingleCommon (const int thrId, const int bno)
Definition at line 36 of file SolveBoard.cpp.
{
  futureTricks fut;
  START_THREAD_TIMER(thrId);
  int res = SolveBoard(
              param.bop->deals[bno],
              param.bop->target[bno],
              param.bop->solutions[bno],
              param.bop->mode[bno],
              &fut,
              thrId);
  END_THREAD_TIMER(thrId);
  if (res == 1)
    param.solvedp->solvedBoard[bno] = fut;
  else
    param.error = res;
}
References paramType::bop, boards::deals, END_THREAD_TIMER, paramType::error, boards::mode, param, boards::solutions, SolveBoard(), solvedBoards::solvedBoard, paramType::solvedp, START_THREAD_TIMER, and boards::target.
Referenced by System::Reset(), and SolveChunkCommon().