open spiel: open_spiel/games/bridge/double_dummy_solver/test/args.h File Reference
args.h File Reference
Functions
void Usage (const char base[])
void PrintOptions ()
void ReadArgs (int argc, char *argv[])
Function Documentation
PrintOptions()
void PrintOptions ()
Definition at line 176 of file args.cpp.
{
  cout << left;
  cout << setw(12) << "file" <<
    setw(12) <<  options.fname << "\n";
  cout << setw(12) << "solver" << setw(12) <<
    solverList[options.solver] << "\n";
  cout << setw(12) << "threading" << setw(12) <<
    threadingList[options.threading] << "\n";
  cout << setw(12) << "threads" << setw(12) <<
    options.numThreads << "\n";
  cout << setw(12) << "memory" << setw(12) <<
    options.memoryMB << " MB\n";
  cout << "\n" << right;
}
References OptionsType::fname, OptionsType::memoryMB, OptionsType::numThreads, options, OptionsType::solver, solverList, OptionsType::threading, and threadingList.
ReadArgs()
void ReadArgs (int argc, char * argv[])
Definition at line 193 of file args.cpp.
{
  for (unsigned i = 0; i < DTEST_NUM_OPTIONS; i++)
  {
    shortOptsAll += optList[i].shortName;
    if (optList[i].numArgs)
      shortOptsWithArg += optList[i].shortName;
  }
  if (argc == 1)
  {
    Usage(argv[0]);
    exit(0);
  }
  SetDefaults();
  int c, m = 0;
  bool errFlag = false, matchFlag;
  string stmp;
  char * ctmp;
  struct stat buffer;
  while ((c = GetNextArgToken(argc, argv)) > 0)
  {
    switch(c)
    {
      case 'f':
        if (stat(optarg, &buffer) == 0)
        {
          options.fname = string(optarg);
          break;
        }
        stmp = "../hands/list" + string(optarg) + ".txt";
        if (stat(stmp.c_str(), &buffer) == 0)
        {
          options.fname = stmp;
          break;
        }
        cout << "Input file '" << optarg << "' not found\n";
        cout << "Input file '" << stmp << "' not found\n";
        nextToken -= 2;
        errFlag = true;
        break;
      case 's':
        matchFlag = false;
        stmp = optarg;
        transform(stmp.begin(), stmp.end(), stmp.begin(), ::tolower);
        for (unsigned i = 0; i < DTEST_SOLVER_SIZE && ! matchFlag; i++)
        {
          string s = solverList[i];
          transform(s.begin(), s.end(), s.begin(), ::tolower);
          if (stmp == s)
          {
            m = static_cast<int>(i);
            matchFlag = true;
          }
        }
        if (matchFlag)
          options.solver = static_cast<Solver>(m);
        else
        {
          cout << "Solver '" << optarg << "' not found\n";
          nextToken -= 2;
          errFlag = true;
        }
        break;
      case 't':
        matchFlag = false;
        stmp = optarg;
        transform(stmp.begin(), stmp.end(), stmp.begin(), ::tolower);
        for (unsigned i = 0; i < DTEST_THREADING_SIZE && ! matchFlag; i++)
        {
          string s = threadingList[i];
          transform(s.begin(), s.end(), s.begin(), ::tolower);
          if (stmp == s)
          {
            m = static_cast<int>(i);
            matchFlag = true;
          }
        }
        if (matchFlag)
          options.threading = static_cast<Threading>(m);
        else
        {
          cout << "Threading '" << optarg << "' not found\n";
          nextToken -= 2;
          errFlag = true;
        }
        break;
      case 'n':
        m = static_cast<int>(strtol(optarg, &ctmp, 0));
        if (m < 0)
        {
          cout << "Number of threads must be >= 0\n\n";
          nextToken -= 2;
          errFlag = true;
        }
        options.numThreads = m;
        break;
      case 'm':
        m = static_cast<int>(strtol(optarg, &ctmp, 0));
        if (m < 0)
        {
          cout << "Memory in MB must be >= 0\n\n";
          nextToken -= 2;
          errFlag = true;
        }
        options.memoryMB = m;
        break;
      default:
        cout << "Unknown option\n";
        errFlag = true;
        break;
    }
    if (errFlag)
      break;
  }
  if (errFlag || c == -1)
  {
    cout << "Error while parsing option '" << argv[nextToken] << "'\n";
    cout << "Invoke the program without arguments for help" << endl;
    exit(0);
  }
}
References DTEST_NUM_OPTIONS, DTEST_SOLVER_SIZE, DTEST_THREADING_SIZE, OptionsType::fname, GetNextArgToken(), i, OptionsType::memoryMB, nextToken, OptionsType::numThreads, optarg, options, optList, SetDefaults(), optEntry::shortName, shortOptsAll, shortOptsWithArg, OptionsType::solver, solverList, OptionsType::threading, threadingList, and Usage().
Referenced by main().
Usage()
void Usage (const char base[])
Definition at line 84 of file args.cpp.
{
  string basename(base);
  const size_t l = basename.find_last_of("\\/");
  if (l != string::npos)
    basename.erase(0, l+1);
  cout <<
    "Usage: " << basename << " [options]\n\n" <<
    "-f, --file s       Input file, or the number n;\n" <<
    "                   '100' means ../hands/list100.txt).\n" <<
    "                   (Default: input.txt)\n" <<
    "\n" <<
    "-s, --solver       One of: solve, calc, play, par, dealerpar.\n" <<
    "                   (Default: solve)\n" <<
    "\n" <<
    "-t, --threading t  Currently one of (case-insensitive):\n" <<
    "                   default, none, winapi, openmp, gcd, boost,\n" <<
    "                   stl, tbb, stlimpl, pplimpl.\n" <<
    "                   (Default: default meaning that DDS decides)\n" <<
    "\n" <<
    "-n, --numthr n     Maximum number of threads.\n" <<
    "                   (Default: 0 meaning that DDS decides)\n" <<
    "\n" <<
    "-m, --memory n     Total DDS memory size in MB.\n" <<
    "                   (Default: 0 meaning that DDS decides)\n" <<
    "\n" <<
    endl;
}
Referenced by ReadArgs().