open spiel: open_spiel/games/bargaining/bargaining_instance_generator.cc File Reference
bargaining_instance_generator.cc File Reference
#include <numeric>
#include <random>
#include <string>
#include "open_spiel/abseil-cpp/absl/flags/flag.h"
#include "open_spiel/abseil-cpp/absl/flags/parse.h"
#include "open_spiel/abseil-cpp/absl/random/distributions.h"
#include "open_spiel/games/bargaining/bargaining.h"
#include "open_spiel/utils/file.h"
#include "open_spiel/utils/init.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
namespace open_spiel::bargaining
Functions
ABSL_FLAG (int, seed, 0, "Seed to use")
ABSL_FLAG (int, num_instances, 1000, "Number of boards to generate.")
ABSL_FLAG (std::string, filename, "/tmp/instances.txt", "File to save boards to.")
int main (int argc, char **argv)
Function Documentation
ABSL_FLAG() [1/3]
ABSL_FLAG (int , num_instances , 1000 , "Number of boards to generate.")
ABSL_FLAG() [2/3]
ABSL_FLAG (int , seed , 0 , "Seed to use")
ABSL_FLAG() [3/3]
ABSL_FLAG (std::string , filename , "/tmp/instances.txt" , "File to save boards to.")
main()
int main (int argc, char ** argv)
Definition at line 118 of file bargaining_instance_generator.cc.
{
  open_spiel::Init("", &argc, &argv, false);
  absl::ParseCommandLine(argc, argv);
  open_spiel::bargaining::GenerateInstances(absl::GetFlag(FLAGS_num_instances));
}
References absl::GetFlag(), open_spiel::Init(), and absl::ParseCommandLine().