open spiel: open_spiel/games/bargaining/bargaining_test.cc File Reference
bargaining_test.cc File Reference
#include "open_spiel/games/bargaining/bargaining.h"
#include <array>
#include <iostream>
#include <vector>
#include "open_spiel/abseil-cpp/absl/flags/flag.h"
#include "open_spiel/abseil-cpp/absl/flags/parse.h"
#include "open_spiel/abseil-cpp/absl/strings/str_cat.h"
#include "open_spiel/spiel.h"
#include "open_spiel/tests/basic_tests.h"
#include "open_spiel/utils/init.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
namespace open_spiel::bargaining
Functions
ABSL_FLAG (bool, enable_instances_file_test, false, "Whether to test loading of an instances file.")
int main (int argc, char **argv)
Function Documentation
ABSL_FLAG()
ABSL_FLAG (bool , enable_instances_file_test , false , "Whether to test loading of an instances file.")
main()
int main (int argc, char ** argv)
Definition at line 141 of file bargaining_test.cc.
{
  open_spiel::Init("", &argc, &argv, false);
  absl::ParseCommandLine(argc, argv);
  open_spiel::bargaining::BasicBargainingTests();
  if (absl::GetFlag(FLAGS_enable_instances_file_test)) {
    open_spiel::bargaining::BasicBargainingFromInstancesFileTests();
  }
  open_spiel::bargaining::BargainingMaxTurnsTest();
  open_spiel::bargaining::BargainingDiscountTest();
  open_spiel::bargaining::BargainingProbEndContinueTest();
  open_spiel::bargaining::BargainingProbEndEndTest();
}
References absl::GetFlag(), open_spiel::Init(), and absl::ParseCommandLine().