open spiel: open_spiel/games/battleship/battleship_test.cc File Reference
battleship_test.cc File Reference
#include <limits>
#include <memory>
#include "open_spiel/abseil-cpp/absl/container/flat_hash_set.h"
#include "open_spiel/abseil-cpp/absl/flags/flag.h"
#include "open_spiel/abseil-cpp/absl/flags/parse.h"
#include "open_spiel/abseil-cpp/absl/strings/str_split.h"
#include "open_spiel/game_parameters.h"
#include "open_spiel/algorithms/expected_returns.h"
#include "open_spiel/algorithms/get_all_states.h"
#include "open_spiel/algorithms/tabular_exploitability.h"
#include "open_spiel/policy.h"
#include "open_spiel/spiel_utils.h"
#include "open_spiel/tests/basic_tests.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
namespace open_spiel::battleship
Functions
ABSL_FLAG (int, num_sims, 20, "Number of simulations in the basic tests.")
ABSL_FLAG (bool, enable_game_sizes_test, false, "Whether to test the game sizes.")
int main (int argc, char **argv)
Function Documentation
ABSL_FLAG() [1/2]
ABSL_FLAG (bool , enable_game_sizes_test , false , "Whether to test the game sizes.")
ABSL_FLAG() [2/2]
ABSL_FLAG (int , num_sims , 20 , "Number of simulations in the basic tests.")
main()
int main (int argc, char ** argv)
Definition at line 443 of file battleship_test.cc.
{
  absl::ParseCommandLine(argc, argv);
  open_spiel::testing::LoadGameTest("battleship");
  open_spiel::battleship::BasicBattleshipTest();
  open_spiel::battleship::RandomTestsOnLargeBoards();
  open_spiel::battleship::TestZeroSumTrait();
  open_spiel::battleship::TestTightLayout1();
  open_spiel::battleship::TestTightLayout2();
  open_spiel::battleship::TestNashEquilibriumInSmallBoard();
  if (absl::GetFlag(FLAGS_enable_game_sizes_test)) {
    open_spiel::battleship::TestGameSizes();
  }
}
References absl::GetFlag(), open_spiel::testing::LoadGameTest(), and absl::ParseCommandLine().
Variable Documentation
num_infostates
uint32_t num_infostates[2] = {0, 0}
Definition at line 296 of file battleship_test.cc.
{0, 0};  // Layout: [Pl.0, Pl.1].
num_sequences
uint32_t num_sequences[2] = {0, 0}
Definition at line 295 of file battleship_test.cc.
{0, 0};   // Layout: [Pl.0, Pl.1].
num_terminal_states
uint32_t num_terminal_states = 0
Definition at line 297 of file battleship_test.cc.
Referenced by main().