open spiel: open_spiel/examples/benchmark_game.cc File Reference
benchmark_game.cc File Reference
#include <iostream>
#include <random>
#include <vector>
#include "open_spiel/abseil-cpp/absl/flags/flag.h"
#include "open_spiel/abseil-cpp/absl/flags/parse.h"
#include "open_spiel/abseil-cpp/absl/strings/str_format.h"
#include "open_spiel/spiel.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
Functions
ABSL_FLAG (std::string, game, "tic_tac_toe", "The name of the game to play.")
ABSL_FLAG (int, sims, 1000, "How many simulations to run.")
ABSL_FLAG (int, attempts, 5, "How many sets of simulations to run.")
ABSL_FLAG (bool, verbose, false, "Boolean flag indicating whether to print all simulation info.")
int open_spiel::RandomSimulation (std::mt19937 *rng, const Game &game, bool verbose)
void open_spiel::RandomSimBenchmark (const std::string &game_def, int num_sims, bool verbose)
int main (int argc, char **argv)
Function Documentation
ABSL_FLAG() [1/4]
ABSL_FLAG (bool , verbose , false , "Boolean flag indicating whether to print all simulation info.")
ABSL_FLAG() [2/4]
ABSL_FLAG (int , attempts , 5 , "How many sets of simulations to run.")
ABSL_FLAG() [3/4]
ABSL_FLAG (int , sims , 1000 , "How many simulations to run.")
ABSL_FLAG() [4/4]
ABSL_FLAG (std::string , game , "tic_tac_toe" , "The name of the game to play.")
main()
int main (int argc, char ** argv)
Definition at line 145 of file benchmark_game.cc.
{
  absl::ParseCommandLine(argc, argv);
  for (int i = 0; i < absl::GetFlag(FLAGS_attempts); ++i) {
    open_spiel::RandomSimBenchmark(absl::GetFlag(FLAGS_game),
                                   absl::GetFlag(FLAGS_sims),
                                   absl::GetFlag(FLAGS_verbose));
  }
}
References absl::GetFlag(), i, absl::ParseCommandLine(), and open_spiel::RandomSimBenchmark().