open spiel: open_spiel/examples/cfr_example.cc File Reference
cfr_example.cc File Reference
#include <string>
#include "open_spiel/abseil-cpp/absl/flags/flag.h"
#include "open_spiel/abseil-cpp/absl/flags/parse.h"
#include "open_spiel/algorithms/cfr.h"
#include "open_spiel/algorithms/tabular_exploitability.h"
#include "open_spiel/spiel.h"
#include "open_spiel/spiel_utils.h"
Functions
ABSL_FLAG (std::string, game_name, "kuhn_poker", "Game to run CFR on.")
ABSL_FLAG (int, num_iters, 1000, "How many iters to run for.")
ABSL_FLAG (int, report_every, 100, "How often to report exploitability.")
int main (int argc, char **argv)
Function Documentation
ABSL_FLAG() [1/3]
ABSL_FLAG (int , num_iters , 1000 , "How many iters to run for.")
ABSL_FLAG() [2/3]
ABSL_FLAG (int , report_every , 100 , "How often to report exploitability.")
ABSL_FLAG() [3/3]
ABSL_FLAG (std::string , game_name , "kuhn_poker" , "Game to run CFR on.")
main()
int main (int argc, char ** argv)
Definition at line 29 of file cfr_example.cc.
{
  absl::ParseCommandLine(argc, argv);
  std::shared_ptr<const open_spiel::Game> game =
      open_spiel::LoadGame(absl::GetFlag(FLAGS_game_name));
  open_spiel::algorithms::CFRSolver solver(*game);
  std::cerr << "Starting CFR on " << game->GetType().short_name
            << "..." << std::endl;
  for (int i = 0; i < absl::GetFlag(FLAGS_num_iters); ++i) {
    solver.EvaluateAndUpdatePolicy();
    if (i % absl::GetFlag(FLAGS_report_every) == 0 ||
        i == absl::GetFlag(FLAGS_num_iters) - 1) {
      double exploitability = open_spiel::algorithms::Exploitability(
          *game, *solver.AveragePolicy());
      std::cerr << "Iteration " << i << " exploitability=" << exploitability
                << std::endl;
    }
  }
}
References open_spiel::algorithms::CFRSolverBase::AveragePolicy(), open_spiel::algorithms::CFRSolverBase::EvaluateAndUpdatePolicy(), open_spiel::algorithms::Exploitability(), absl::GetFlag(), i, open_spiel::LoadGame(), and absl::ParseCommandLine().