open spiel: absl::ScopedMockLog Class Reference
absl::ScopedMockLog Class Reference final
#include <scoped_mock_log.h>
Public Member Functions
ScopedMockLog (MockLogDefault default_exp=MockLogDefault::kIgnoreUnexpected)
ScopedMockLog (const ScopedMockLog &)=delete
ScopedMockLog & operator= (const ScopedMockLog &)=delete
~ScopedMockLog ()
void StartCapturingLogs ()
void StopCapturingLogs ()
absl::LogSink & UseAsLocalSink ()
MOCK_METHOD (void, Log,(absl::LogSeverity severity, const std::string &file_path, const std::string &message))
MOCK_METHOD (void, Send,(const absl::LogEntry &))
MOCK_METHOD (void, Flush,())
Detailed Description
Definition at line 93 of file scoped_mock_log.h.
Constructor & Destructor Documentation
ScopedMockLog() [1/2]
ABSL_NAMESPACE_BEGIN absl::ScopedMockLog::ScopedMockLog (MockLogDefault default_exp = MockLogDefault::kIgnoreUnexpected) explicit
Definition at line 32 of file scoped_mock_log.cc.
    : sink_(this), is_capturing_logs_(false) {
  if (default_exp == MockLogDefault::kIgnoreUnexpected) {
    // Ignore all calls to Log we did not set expectations for.
    EXPECT_CALL(*this, Log).Times(::testing::AnyNumber());
  } else {
    // Disallow all calls to Log we did not set expectations for.
    EXPECT_CALL(*this, Log).Times(0);
  }
  // By default Send mock forwards to Log mock.
  EXPECT_CALL(*this, Send)
      .Times(::testing::AnyNumber())
      .WillRepeatedly([this](const absl::LogEntry& entry) {
        is_triggered_.store(true, std::memory_order_relaxed);
        Log(entry.log_severity(), std::string(entry.source_filename()),
            std::string(entry.text_message()));
      });
  // By default We ignore all Flush calls.
  EXPECT_CALL(*this, Flush).Times(::testing::AnyNumber());
}
References absl::kIgnoreUnexpected, absl::LogEntry::log_severity(), absl::LogEntry::source_filename(), and absl::LogEntry::text_message().
ScopedMockLog() [2/2]
absl::ScopedMockLog::ScopedMockLog (const ScopedMockLog &) delete
~ScopedMockLog()
absl::ScopedMockLog::~ScopedMockLog ()
Definition at line 54 of file scoped_mock_log.cc.
{
  ABSL_RAW_CHECK(is_triggered_.load(std::memory_order_relaxed),
                 "Did you forget to call StartCapturingLogs()?");
  if (is_capturing_logs_) StopCapturingLogs();
}
References ABSL_RAW_CHECK, and StopCapturingLogs().
Member Function Documentation
MOCK_METHOD() [1/3]
absl::ScopedMockLog::MOCK_METHOD (void , Flush , ())
MOCK_METHOD() [2/3]
absl::ScopedMockLog::MOCK_METHOD (void , Log , (absl::LogSeverity severity, const std::string &file_path, const std::string &message))
MOCK_METHOD() [3/3]
absl::ScopedMockLog::MOCK_METHOD (void , Send , (const absl::LogEntry &))
operator=()
ScopedMockLog & absl::ScopedMockLog::operator= (const ScopedMockLog &) delete
StartCapturingLogs()
void absl::ScopedMockLog::StartCapturingLogs ()
Definition at line 61 of file scoped_mock_log.cc.
{
  ABSL_RAW_CHECK(!is_capturing_logs_,
                 "StartCapturingLogs() can be called only when the "
                 "absl::ScopedMockLog object is not capturing logs.");
  is_capturing_logs_ = true;
  is_triggered_.store(true, std::memory_order_relaxed);
  absl::AddLogSink(&sink_);
}
References ABSL_RAW_CHECK, and absl::AddLogSink().
Referenced by absl_log_internal::TEST_P(), absl_log_internal::TEST_P(), absl_log_internal::TEST_P(), absl_log_internal::TEST_P(), absl_log_internal::TEST_P(), and absl_log_internal::TEST_P().
StopCapturingLogs()
void absl::ScopedMockLog::StopCapturingLogs ()
Definition at line 71 of file scoped_mock_log.cc.
{
  ABSL_RAW_CHECK(is_capturing_logs_,
                 "StopCapturingLogs() can be called only when the "
                 "absl::ScopedMockLog object is capturing logs.");
  is_capturing_logs_ = false;
  absl::RemoveLogSink(&sink_);
}
References ABSL_RAW_CHECK, and absl::RemoveLogSink().
Referenced by ~ScopedMockLog().
UseAsLocalSink()
absl::LogSink & absl::ScopedMockLog::UseAsLocalSink ()
Definition at line 80 of file scoped_mock_log.cc.
{
  is_triggered_.store(true, std::memory_order_relaxed);
  return sink_;
}
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/log/scoped_mock_log.h
open_spiel/abseil-cpp/absl/log/scoped_mock_log.cc