open spiel: open_spiel::skat::SkatState Class Reference
open_spiel::skat::SkatState Class Reference
#include <skat.h>
Public Member Functions
SkatState (std::shared_ptr< const Game > game)
SkatState (const SkatState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
std::string ToString () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 139 of file skat.h.
Constructor & Destructor Documentation
SkatState() [1/2]
open_spiel::skat::SkatState::SkatState (std::shared_ptr< const Game > game)
Definition at line 238 of file skat.cc.
      : State(game) {
  card_locations_.fill(kDeck);
  player_bids_.fill(kPass);
}
References open_spiel::skat::kDeck, and open_spiel::skat::kPass.
Referenced by Clone().
SkatState() [2/2]
open_spiel::skat::SkatState::SkatState (const SkatState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::skat::SkatState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 244 of file skat.cc.
{
  if (action_id < kBiddingActionBase) {
    return CardToString(action_id);
  } else {
    return SkatGameTypeToString(
        static_cast<SkatGameType>(action_id - kBiddingActionBase));
  }
}
References open_spiel::skat::CardToString(), open_spiel::skat::kBiddingActionBase, and open_spiel::skat::SkatGameTypeToString().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::skat::SkatState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 638 of file skat.cc.
{
  std::vector<std::pair<Action, double>> outcomes;
  int num_cards_remaining = kNumCards - history_.size();
  outcomes.reserve(num_cards_remaining);
  const double p_card = 1.0 / static_cast<double>(num_cards_remaining);
  for (int card = 0; card < kNumCards; ++card) {
    if (card_locations_[card] == kDeck) outcomes.emplace_back(card, p_card);
  }
  return outcomes;
}
References open_spiel::State::history_, open_spiel::skat::kDeck, and open_spiel::skat::kNumCards.
Clone()
std::unique_ptr< State > open_spiel::skat::SkatState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 151 of file skat.h.
{
    return std::unique_ptr<State>(new SkatState(*this));
  }
References SkatState().
CurrentPlayer()
Player open_spiel::skat::SkatState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 144 of file skat.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::skat::SkatState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 355 of file skat.cc.
{
  switch (phase_) {
    case kDeal:
      return ApplyDealAction(action);
    case kBidding:
      return ApplyBiddingAction(action - kBiddingActionBase);
    case kDiscardCards:
      return ApplyDiscardCardsAction(action);
    case kPlay:
      return ApplyPlayAction(action);
    case kGameOver:
      SpielFatalError("Cannot act in terminal states");
  }
}
References action, open_spiel::skat::kBidding, open_spiel::skat::kBiddingActionBase, open_spiel::skat::kDeal, open_spiel::skat::kDiscardCards, open_spiel::skat::kGameOver, open_spiel::skat::kPlay, and open_spiel::SpielFatalError().
IsTerminal()
bool open_spiel::skat::SkatState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 149 of file skat.h.
{ return phase_ == kGameOver; }
References open_spiel::skat::kGameOver.
Referenced by CurrentPlayer().
LegalActions()
std::vector< Action > open_spiel::skat::SkatState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 548 of file skat.cc.
{
  switch (phase_) {
    case kDeal:
      return DealLegalActions();
    case kBidding:
      return BiddingLegalActions();
    case kDiscardCards:
      return DiscardCardsLegalActions();
    case kPlay:
      return PlayLegalActions();
    default:
      return {};
  }
}
References open_spiel::skat::kBidding, open_spiel::skat::kDeal, open_spiel::skat::kDiscardCards, and open_spiel::skat::kPlay.
ObservationString()
std::string open_spiel::skat::SkatState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 728 of file skat.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // We construct the ObservationString from the ObservationTensor to give
  // some indication that the tensor representation is correct & complete.
  if (phase_ == Phase::kDeal) {
    return "No Observation";
  }
  std::vector<float> tensor(game_->ObservationTensorSize());
  ObservationTensor(player, absl::MakeSpan(tensor));
  std::string rv;
  auto ptr = tensor.begin();
  int player_pos = GetIntFromOneHot(ptr, kNumPlayers);
  absl::StrAppend(&rv, "PlPos:", player_pos);
  ptr += kNumPlayers;
  Phase phase = kDeal;
  if (ptr[0]) phase = kBidding;
  else if (ptr[1]) phase = kDiscardCards;
  else if (ptr[2]) phase = kPlay;
  else
    phase = kGameOver;
  absl::StrAppend(&rv, "|Phase:", PhaseToString(phase));
  ptr += 3;
  std::vector<int> player_cards = GetCardsFromMultiHot(ptr);
  absl::StrAppend(&rv, "|Hand:", CardsToString(player_cards));
  ptr += kNumCards;
  absl::StrAppend(&rv, "|Bids:");
  for (int i = 0; i < kNumPlayers; i++) {
    int player_bid = GetIntFromOneHot(ptr, kNumGameTypes);
    absl::StrAppend(
        &rv, SkatGameTypeToString(static_cast<SkatGameType>(player_bid)), " ");
    ptr += kNumGameTypes;
  }
  Player solo_player = GetIntFromOneHot(ptr, kNumPlayers);
  absl::StrAppend(&rv, "|SoloPl:", solo_player);
  ptr += kNumPlayers;
  std::vector<int> skat_cards = GetCardsFromMultiHot(ptr);
  absl::StrAppend(&rv, "|Skat:", CardsToString(skat_cards));
  ptr += kNumCards;
  SkatGameType game_type = SkatGameType(GetIntFromOneHot(ptr, kNumGameTypes));
  absl::StrAppend(&rv, "|Game:", SkatGameTypeToString(game_type));
  ptr += kNumGameTypes;
  Player current_trick_leader = GetIntFromOneHot(ptr, kNumPlayers);
  absl::StrAppend(&rv, "|CurrTrick(Leader:", current_trick_leader, "):");
  ptr += kNumPlayers;
  for (int i = 0; i < kNumPlayers; i++) {
    int card = GetIntFromOneHot(ptr, kNumCards);
    if (card >= 0) absl::StrAppend(&rv, ToCardSymbol(card), " ");
    ptr += kNumCards;
  }
  Player previous_trick_leader = GetIntFromOneHot(ptr, kNumPlayers);
  if (previous_trick_leader >= 0) {
    absl::StrAppend(&rv, "|PrevTrick(Leader:", previous_trick_leader, "):");
    ptr += kNumPlayers;
    for (int i = 0; i < kNumPlayers; i++) {
      int card = GetIntFromOneHot(ptr, kNumCards);
      if (card >= 0) absl::StrAppend(&rv, ToCardSymbol(card), " ");
      ptr += kNumCards;
    }
  }
  return rv;
}
References open_spiel::skat::CardsToString(), open_spiel::State::game_, open_spiel::skat::GetCardsFromMultiHot(), open_spiel::skat::GetIntFromOneHot(), i, open_spiel::skat::kBidding, open_spiel::skat::kDeal, open_spiel::skat::kDiscardCards, open_spiel::skat::kGameOver, open_spiel::skat::kNumCards, open_spiel::skat::kNumGameTypes, open_spiel::skat::kNumPlayers, open_spiel::skat::kPlay, absl::MakeSpan(), open_spiel::State::num_players_, open_spiel::State::ObservationTensor(), open_spiel::skat::PhaseToString(), player, ptr, open_spiel::skat::SkatGameTypeToString(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and open_spiel::skat::ToCardSymbol().
ObservationTensor()
void open_spiel::skat::SkatState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 649 of file skat.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::fill(values.begin(), values.end(), 0.0);
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  if (phase_ == Phase::kDeal) return;
  auto ptr = values.begin();
  // Position:
  ptr[player] = 1;
  ptr += kNumPlayers;
  // Phase
  if (phase_ >= kBidding && phase_ <= kPlay) ptr[phase_ - kBidding] = 1;
  ptr += 3;
  // Players Cards
  for (int i = 0; i < kNumCards; ++i)
    if (card_locations_[i] == PlayerToLocation(player)) ptr[i] = 1;
  ptr += kNumCards;
  // All player bids.
  for (int i = 0; i < kNumPlayers; i++) {
    ptr[player_bids_[i]] = 1;
    ptr += kNumGameTypes;
  }
  // Who is the solo player.
  if (solo_player_ >= 0) ptr[solo_player_] = 1;
  ptr += kNumPlayers;
  // Information about the Skat only for the solo_player_.
  if (player == solo_player_) {
    for (int i = 0; i < kNumCards; ++i)
      if (card_locations_[i] == kSkat) ptr[i] = 1;
  }
  ptr += kNumCards;
  // Game type
  ptr[game_type_] = 1;
  ptr += kNumGameTypes;
  // Current trick
  if (phase_ == kPlay) {
    ptr[CurrentTrick().Leader()] = 1;
    ptr += kNumPlayers;
    const auto& cards = CurrentTrick().GetCards();
    for (int i = 0; i < kNumPlayers; i++) {
      if (cards.size() > i) ptr[cards[i]] = 1;
      ptr += kNumCards;
    }
  } else {
    ptr += kNumPlayers + kNumPlayers * kNumCards;
  }
  // Previous Trick
  if (CurrentTrickIndex() > 0) {
    ptr[PreviousTrick().Leader()] = 1;
    ptr += kNumPlayers;
    const auto& cards = PreviousTrick().GetCards();
    for (int i = 0; i < kNumPlayers; i++) {
      if (cards.size() > i) ptr[cards[i]] = 1;
      ptr += kNumCards;
    }
  } else {
    ptr += kNumPlayers + kNumPlayers * kNumCards;
  }
}
References open_spiel::State::game_, open_spiel::skat::Trick::GetCards(), i, open_spiel::skat::kBidding, open_spiel::skat::kDeal, open_spiel::skat::kNumCards, open_spiel::skat::kNumGameTypes, open_spiel::skat::kNumPlayers, open_spiel::skat::kPlay, open_spiel::skat::kSkat, open_spiel::skat::Trick::Leader(), open_spiel::State::num_players_, player, open_spiel::skat::PlayerToLocation(), ptr, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::skat::SkatState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 150 of file skat.h.
{ return returns_; }
ToString()
std::string open_spiel::skat::SkatState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 253 of file skat.cc.
{
  std::string result = "";
  absl::StrAppendFormat(&result, "Phase: %s \n", PhaseToString(phase_));
  absl::StrAppendFormat(&result, "Current Player: %d", current_player_);
  absl::StrAppendFormat(&result, "\n%s\n", CardLocationsToString());
  if (phase_ == kPlay || phase_ == kGameOver) {
    absl::StrAppendFormat(&result, "Last trick won by player %d\n",
                          last_trick_winner_);
    absl::StrAppendFormat(&result, "Solo Player: %d\n", solo_player_);
    absl::StrAppendFormat(&result, "Points (Solo / Team): (%d / %d)\n",
                          points_solo_, points_team_);
    absl::StrAppendFormat(&result, "Current Trick: %s\n",
                          CurrentTrick().ToString());
    if (CurrentTrickIndex() > 0) {
      absl::StrAppendFormat(&result, "Last Trick: %s\n",
                            PreviousTrick().ToString());
    }
  }
  absl::StrAppendFormat(&result, "Game Type: %s\n",
                SkatGameTypeToString(game_type_));
  return result;
}
References open_spiel::skat::kGameOver, open_spiel::skat::kPlay, open_spiel::skat::PhaseToString(), open_spiel::skat::SkatGameTypeToString(), absl::StrAppendFormat(), and ToString().
Referenced by ToString().
The documentation for this class was generated from the following files:
open_spiel/games/skat/skat.h
open_spiel/games/skat/skat.cc