open spiel: open_spiel::universal_poker::logic::CardSet Class Reference
open_spiel::universal_poker::logic::CardSet Class Reference
#include <card_set.h>
Classes
union CardSetUnion
Public Member Functions
CardSet ()
CardSet (std::string cardString)
CardSet (std::vector< int > cards)
CardSet (uint16_t num_suits, uint16_t num_ranks)
std::string ToString () const
std::vector< uint8_t > ToCardArray () const
void AddCard (uint8_t card)
void RemoveCard (uint8_t card)
bool ContainsCards (uint8_t card) const
int NumCards () const
int RankCards () const
std::vector< CardSet > SampleCards (int nbCards)
Public Attributes
union open_spiel::universal_poker::logic::CardSet::CardSetUnion cs
Detailed Description
Definition at line 32 of file card_set.h.
Constructor & Destructor Documentation
CardSet() [1/4]
open_spiel::universal_poker::logic::CardSet::CardSet () inline
Definition at line 41 of file card_set.h.
: cs() {}
CardSet() [2/4]
open_spiel::universal_poker::logic::CardSet::CardSet (std::string cardString)
Definition at line 48 of file card_set.cc.
                                     : cs() {
  SPIEL_CHECK_LE(cardString.size(), 10);  // Max 5 cards.
  SPIEL_CHECK_EQ(cardString.size() % 2, 0);  // Each cards is 2 chars: RankSuit.
  for (int i = 0; i < cardString.size(); i += 2) {
    char rankChr = cardString[i];
    char suitChr = cardString[i + 1];
    uint8_t rank = (uint8_t)(kRankChars.find(rankChr));
    uint8_t suit = (uint8_t)(kSuitChars.find(suitChr));
    SPIEL_CHECK_LT(rank, MAX_RANKS);
    SPIEL_CHECK_LT(suit, MAX_SUITS);
    cs.bySuit[suit] |= ((uint16_t)1 << rank);
  }
}
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::bySuit, cs, absl::string_view::find(), i, kRankChars, kSuitChars, rank, SPIEL_CHECK_EQ, SPIEL_CHECK_LE, and SPIEL_CHECK_LT.
CardSet() [3/4]
open_spiel::universal_poker::logic::CardSet::CardSet (std::vector< int > cards)
Definition at line 64 of file card_set.cc.
                                     : cs() {
  for (int i = 0; i < cards.size(); ++i) {
    int rank = rankOfCard(cards[i]);
    int suit = suitOfCard(cards[i]);
    cs.bySuit[suit] |= ((uint16_t)1 << rank);
  }
}
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::bySuit, cs, i, and rank.
CardSet() [4/4]
open_spiel::universal_poker::logic::CardSet::CardSet (uint16_t num_suits, uint16_t num_ranks)
Definition at line 73 of file card_set.cc.
                                                       : cs() {
  for (uint16_t r = 0; r < num_ranks; r++) {
    for (uint16_t s = 0; s < num_suits; s++) {
      cs.bySuit[s] |= ((uint16_t)1 << r);
    }
  }
}
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::bySuit, cs, and r.
Member Function Documentation
AddCard()
void open_spiel::universal_poker::logic::CardSet::AddCard (uint8_t card)
Definition at line 111 of file card_set.cc.
{
  int rank = rankOfCard(card);
  int suit = suitOfCard(card);
  cs.bySuit[suit] |= ((uint16_t)1 << rank);
}
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::bySuit, cs, and rank.
Referenced by open_spiel::universal_poker::UniversalPokerState::GetHistoriesConsistentWithInfostate().
ContainsCards()
bool open_spiel::universal_poker::logic::CardSet::ContainsCards (uint8_t card) const
Definition at line 157 of file card_set.cc.
{
  int rank = rankOfCard(card);
  int suit = suitOfCard(card);
  return (cs.bySuit[suit] & ((uint16_t)1 << rank)) > 0;
}
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::bySuit, cs, and rank.
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::InformationStateTensor(), open_spiel::universal_poker::UniversalPokerState::LegalActions(), and open_spiel::universal_poker::UniversalPokerState::ObservationTensor().
NumCards()
int open_spiel::universal_poker::logic::CardSet::NumCards () const
Definition at line 125 of file card_set.cc.
{ return __builtin_popcountl(cs.cards); }
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::cards, and cs.
Referenced by open_spiel::universal_poker::logic::BasicCardSetTests(), open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::GetHistoriesConsistentWithInfostate(), open_spiel::universal_poker::UniversalPokerState::InformationStateTensor(), open_spiel::universal_poker::UniversalPokerState::LegalActions(), open_spiel::universal_poker::UniversalPokerState::ObservationTensor(), ToCardArray(), and open_spiel::universal_poker::UniversalPokerState::UniversalPokerState().
RankCards()
int open_spiel::universal_poker::logic::CardSet::RankCards () const
Definition at line 127 of file card_set.cc.
{
  ::Cardset csNative;
  csNative.cards = cs.cards;
  return rankCardset(csNative);
}
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::cards, and cs.
Referenced by open_spiel::universal_poker::logic::BasicCardSetTests().
RemoveCard()
void open_spiel::universal_poker::logic::CardSet::RemoveCard (uint8_t card)
Definition at line 118 of file card_set.cc.
{
  int rank = rankOfCard(card);
  int suit = suitOfCard(card);
  cs.bySuit[suit] ^= ((uint16_t)1 << rank);
}
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::bySuit, cs, and rank.
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::GetHistoriesConsistentWithInfostate(), and open_spiel::universal_poker::UniversalPokerState::UniversalPokerState().
SampleCards()
std::vector< CardSet > open_spiel::universal_poker::logic::CardSet::SampleCards (int nbCards)
Definition at line 133 of file card_set.cc.
{
  std::vector<CardSet> combinations;
  uint64_t p = 0;
  for (int i = 0; i < nbCards; ++i) {
    p += (1 << i);
  }
  // Enumerates all the uint64_t integers that with nbCards 1-bits.
  // The final n is ignored. It is fine as long as the rank < 16.
  for (uint64_t n = bit_twiddle_permute(p); n > p;
       p = n, n = bit_twiddle_permute(p)) {
    // Checks whether the CardSet represented by p is inside the CardSet.
    uint64_t combo = p & cs.cards;
    if (__builtin_popcountl(combo) == nbCards) {
      CardSet c;
      c.cs.cards = combo;
      combinations.emplace_back(c);
    }
  }
  // std::cout << "combinations.size() " << combinations.size() << std::endl;
  return combinations;
}
References open_spiel::universal_poker::logic::bit_twiddle_permute(), open_spiel::universal_poker::logic::CardSet::CardSetUnion::cards, cs, i, and n.
Referenced by open_spiel::universal_poker::logic::BasicCardSetTests().
ToCardArray()
std::vector< uint8_t > open_spiel::universal_poker::logic::CardSet::ToCardArray () const
Definition at line 96 of file card_set.cc.
{
  std::vector<uint8_t> result(NumCards(), 0);
  int i = 0;
  for (int r = 0; r < MAX_RANKS; ++r) {
    for (int s = 0; s < MAX_SUITS; ++s) {
      uint32_t mask = (uint32_t)1 << r;
      if (cs.bySuit[s] & mask) {
        result[i++] = makeCard(r, s);
      }
    }
  }
  return result;
}
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::bySuit, cs, i, NumCards(), and r.
Referenced by open_spiel::universal_poker::logic::BasicCardSetTests(), open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::GetHistoriesConsistentWithInfostate(), open_spiel::universal_poker::UniversalPokerState::InformationStateTensor(), open_spiel::universal_poker::UniversalPokerState::LegalActions(), open_spiel::universal_poker::UniversalPokerState::ObservationTensor(), and open_spiel::universal_poker::UniversalPokerState::UniversalPokerState().
ToString()
std::string open_spiel::universal_poker::logic::CardSet::ToString () const
Definition at line 81 of file card_set.cc.
{
  std::string result;
  for (int r = MAX_RANKS - 1; r >= 0; r--) {
    for (int s = MAX_SUITS - 1; s >= 0; s--) {
      uint32_t mask = (uint32_t)1 << r;
      if (cs.bySuit[s] & mask) {
        absl::StrAppend(&result, std::string(1, kRankChars[r]),
                        std::string(1, kSuitChars[s]));
      }
    }
  }
  return result;
}
References open_spiel::universal_poker::logic::CardSet::CardSetUnion::bySuit, cs, kRankChars, kSuitChars, r, and absl::StrAppend().
Referenced by open_spiel::universal_poker::logic::BasicCardSetTests(), open_spiel::universal_poker::MakeRandomSubgame(), and open_spiel::universal_poker::UniversalPokerState::ToString().
Member Data Documentation
cs
union open_spiel::universal_poker::logic::CardSet::CardSetUnion open_spiel::universal_poker::logic::CardSet::cs
Referenced by AddCard(), CardSet(), CardSet(), CardSet(), ContainsCards(), open_spiel::universal_poker::DistributeHands(), NumCards(), RankCards(), RemoveCard(), SampleCards(), ToCardArray(), and ToString().
The documentation for this class was generated from the following files:
open_spiel/games/universal_poker/logic/card_set.h
open_spiel/games/universal_poker/logic/card_set.cc