open spiel: open_spiel::ActionObservationHistory Class Reference
open_spiel::ActionObservationHistory Class Reference
#include <observation_history.h>
Public Member Functions
ActionObservationHistory (Player player, const State &target)
ActionObservationHistory (const State &target)
ActionObservationHistory (Player player, std::vector< std::pair< absl::optional< Action >, std::string > > history)
ActionObservationHistory (const ActionObservationHistory &)=default
~ActionObservationHistory ()=default
const std::vector< std::pair< absl::optional< Action >, std::string > > & History () const
Player GetPlayer () const
int MoveNumber () const
const std::string & ObservationAt (int time) const
absl::optional< Action > ActionAt (int time) const
bool CorrespondsToInitialState () const
bool CorrespondsTo (const ActionObservationHistory &other) const
bool CorrespondsTo (Player pl, const State &state) const
bool IsPrefixOf (const ActionObservationHistory &other) const
bool IsPrefixOf (Player pl, const State &state) const
bool IsExtensionOf (const ActionObservationHistory &other) const
bool IsExtensionOf (Player pl, const State &state) const
void Extend (const absl::optional< Action > action, const std::string &observation_string)
void RemoveLast ()
std::string ToString () const
bool operator== (const ActionObservationHistory &other) const
Detailed Description
Definition at line 47 of file observation_history.h.
Constructor & Destructor Documentation
ActionObservationHistory() [1/4]
open_spiel::ActionObservationHistory::ActionObservationHistory (Player player, const State & target)
Definition at line 32 of file observation_history.cc.
    : player_(player) {
  SPIEL_CHECK_GE(player_, 0);
  SPIEL_CHECK_LT(player_, target.NumPlayers());
  SPIEL_CHECK_TRUE(target.GetGame()->GetType().provides_observation_string);
  const std::vector<State::PlayerAction>& history = target.FullHistory();
  history_.reserve(history.size());
  std::unique_ptr<State> state = target.GetGame()->NewInitialState();
  history_.push_back({absl::nullopt, state->ObservationString(player)});
  for (int i = 0; i < history.size(); i++) {
    const auto& [history_player, action] = history[i];
    const bool is_acting = state->CurrentPlayer() == player;
    state->ApplyAction(action);
    history_.push_back({
      is_acting ? action : static_cast<absl::optional<Action>>(absl::nullopt),
      state->ObservationString(player)
    });
  }
}
References action, open_spiel::State::FullHistory(), open_spiel::State::GetGame(), i, open_spiel::State::NumPlayers(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, and state.
ActionObservationHistory() [2/4]
open_spiel::ActionObservationHistory::ActionObservationHistory (const State & target)
Definition at line 55 of file observation_history.cc.
    : ActionObservationHistory(target.CurrentPlayer(), target) {}
ActionObservationHistory() [3/4]
open_spiel::ActionObservationHistory::ActionObservationHistory (Player player, std::vector< std::pair< absl::optional< Action >, std::string > > history)
Definition at line 58 of file observation_history.cc.
    : player_(player), history_(std::move(history)) {
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_FALSE(history_.empty());  // There is always an obs for root node.
  SPIEL_CHECK_EQ(history_[0].first, absl::nullopt);  // No action available.
}
References first, player, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, and SPIEL_CHECK_GE.
ActionObservationHistory() [4/4]
open_spiel::ActionObservationHistory::ActionObservationHistory (const ActionObservationHistory &) default
~ActionObservationHistory()
open_spiel::ActionObservationHistory::~ActionObservationHistory () default
Member Function Documentation
ActionAt()
absl::optional< Action > open_spiel::ActionObservationHistory::ActionAt (int time) const
Definition at line 77 of file observation_history.cc.
{
  return history_.at(time).first;
}
CorrespondsTo() [1/2]
bool open_spiel::ActionObservationHistory::CorrespondsTo (const ActionObservationHistory & other) const
Definition at line 90 of file observation_history.cc.
{
  bool equal = player_ == other.player_ && history_ == other.history_;
  SPIEL_CHECK_TRUE(!equal || IsPrefixOf(other));
  SPIEL_CHECK_TRUE(!equal || IsExtensionOf(other));
  return equal;
}
References IsExtensionOf(), IsPrefixOf(), and SPIEL_CHECK_TRUE.
Referenced by open_spiel::algorithms::TargetedPolicy::IsTargetHit(), and operator==().
CorrespondsTo() [2/2]
bool open_spiel::ActionObservationHistory::CorrespondsTo (Player pl, const State & state) const
Definition at line 81 of file observation_history.cc.
{
  if (MoveNumber() != state.MoveNumber()) return false;
  bool equal = CheckStateCorrespondenceInSimulation(pl, state, MoveNumber());
  SPIEL_CHECK_TRUE(!equal || IsPrefixOf(pl, state));
  SPIEL_CHECK_TRUE(!equal || IsExtensionOf(pl, state));
  return equal;
}
References IsExtensionOf(), IsPrefixOf(), MoveNumber(), SPIEL_CHECK_TRUE, and state.
CorrespondsToInitialState()
bool open_spiel::ActionObservationHistory::CorrespondsToInitialState () const inline
Definition at line 94 of file observation_history.h.
{ return MoveNumber() == 0; }
References MoveNumber().
Referenced by IsPrefixOf(), IsPrefixOf(), and open_spiel::algorithms::OOSAlgorithm::RunTargetedIterations().
Extend()
void open_spiel::ActionObservationHistory::Extend (const absl::optional< Action > action, const std::string & observation_string)
Definition at line 145 of file observation_history.cc.
{
  history_.push_back({action, observation_string});
}
References action.
GetPlayer()
Player open_spiel::ActionObservationHistory::GetPlayer () const inline
Definition at line 78 of file observation_history.h.
{ return player_; }
Referenced by open_spiel::algorithms::TargetedPolicy::IsTargetHit().
History()
const std::vector< std::pair< absl::optional< Action >, std::string > > & open_spiel::ActionObservationHistory::History () const inline
Definition at line 76 of file observation_history.h.
            { return history_; }
IsExtensionOf() [1/2]
bool open_spiel::ActionObservationHistory::IsExtensionOf (const ActionObservationHistory & other) const
Definition at line 123 of file observation_history.cc.
{
  return other.IsPrefixOf(*this);
}
References IsPrefixOf().
Referenced by CorrespondsTo(), and CorrespondsTo().
IsExtensionOf() [2/2]
bool open_spiel::ActionObservationHistory::IsExtensionOf (Player pl, const State & state) const
Definition at line 128 of file observation_history.cc.
{
  const std::shared_ptr<const Game> game = state.GetGame();
  SPIEL_CHECK_TRUE(game->GetType().provides_observation_string);
  if (state.IsInitialState()) return true;
  // Cannot be extension if state is later.
  if (state.MoveNumber() > MoveNumber()) return false;
  // Check the latest observation is identical -- most observations
  // will differ only in the last items.
  if (state.ObservationString(pl) != ObservationAt(state.MoveNumber()))
    return false;
  return CheckStateCorrespondenceInSimulation(pl, state, state.MoveNumber());
}
References MoveNumber(), ObservationAt(), SPIEL_CHECK_TRUE, and state.
IsPrefixOf() [1/2]
bool open_spiel::ActionObservationHistory::IsPrefixOf (const ActionObservationHistory & other) const
Definition at line 98 of file observation_history.cc.
{
  if (player_ != other.player_) return false;
  if (CorrespondsToInitialState()) return true;
  if (other.CorrespondsToInitialState()) return false;
  const auto& a = history_;
  const auto& b = other.history_;
  if (a.size() > b.size()) return false;
  if (a.size() == b.size()) return a == b;
  return std::equal(a.begin(), a.end(), b.begin());
}
References a, b, and CorrespondsToInitialState().
Referenced by CorrespondsTo(), CorrespondsTo(), and IsExtensionOf().
IsPrefixOf() [2/2]
bool open_spiel::ActionObservationHistory::IsPrefixOf (Player pl, const State & state) const
Definition at line 112 of file observation_history.cc.
{
  const std::shared_ptr<const Game> game = state.GetGame();
  SPIEL_CHECK_TRUE(game->GetType().provides_observation_string);
  if (CorrespondsToInitialState()) return true;
  // Cannot be prefix if state is earlier.
  if (MoveNumber() > state.MoveNumber()) return false;
  return CheckStateCorrespondenceInSimulation(pl, state, MoveNumber());
}
References CorrespondsToInitialState(), MoveNumber(), SPIEL_CHECK_TRUE, and state.
MoveNumber()
int open_spiel::ActionObservationHistory::MoveNumber () const
Definition at line 67 of file observation_history.cc.
{
  SPIEL_CHECK_FALSE(history_.empty());
  SPIEL_CHECK_EQ(history_.at(0).first, absl::nullopt);
  return history_.size() - 1;
}
References SPIEL_CHECK_EQ, and SPIEL_CHECK_FALSE.
Referenced by CorrespondsTo(), CorrespondsToInitialState(), IsExtensionOf(), and IsPrefixOf().
ObservationAt()
const std::string & open_spiel::ActionObservationHistory::ObservationAt (int time) const
Definition at line 73 of file observation_history.cc.
{
  return history_.at(time).second;
}
Referenced by IsExtensionOf().
operator==()
bool open_spiel::ActionObservationHistory::operator== (const ActionObservationHistory & other) const inline
Definition at line 137 of file observation_history.h.
{
    return CorrespondsTo(other);
  }
References CorrespondsTo().
RemoveLast()
void open_spiel::ActionObservationHistory::RemoveLast ()
Definition at line 150 of file observation_history.cc.
{
  SPIEL_CHECK_GT(history_.size(), 0);
  history_.pop_back();
}
References SPIEL_CHECK_GT.
ToString()
std::string open_spiel::ActionObservationHistory::ToString () const
Definition at line 182 of file observation_history.cc.
{
  std::string s;
  for (int i = 0; i < history_.size(); i++) {
    const auto& action_observation = history_[i];
    if (i > 0) absl::StrAppend(&s, ", ");
    absl::StrAppend(&s, "(action=",
                    (action_observation.first == absl::nullopt
                         ? "None"
                         : std::to_string(*action_observation.first)),
                    ", observation=\"", action_observation.second, "\")");
  }
  return s;
}
References i, and absl::StrAppend().
Referenced by open_spiel::operator<<().
The documentation for this class was generated from the following files:
open_spiel/algorithms/observation_history.h
open_spiel/algorithms/observation_history.cc