open spiel: absl::substitute_internal::Arg Class Reference
absl::substitute_internal::Arg Class Reference
#include <substitute.h>
Public Member Functions
Arg (const char *value)
template<typename Allocator >
Arg (const std::basic_string< char, std::char_traits< char >, Allocator > &value) noexcept
Arg (absl::string_view value)
Arg (char value)
Arg (short value)
Arg (unsigned short value)
Arg (int value)
Arg (unsigned int value)
Arg (long value)
Arg (unsigned long value)
Arg (long long value)
Arg (unsigned long long value)
Arg (float value)
Arg (double value)
Arg (bool value)
template<typename T , typename = typename std::enable_if< strings_internal::HasAbslStringify<T>::value>::type>
Arg (const T &v, strings_internal::StringifySink &&sink={})
Arg (Hex hex)
Arg (Dec dec)
template<typename T , absl::enable_if_t< std::is_class< T >::value &&(std::is_same< T, std::vector< bool >::reference >::value||std::is_same< T, std::vector< bool >::const_reference >::value)> * = nullptr>
Arg (T value)
Arg (const void *value)
template<typename T , typename = typename std::enable_if< std::is_enum<T>{} && !std::is_convertible<T, int>{} && !strings_internal::HasAbslStringify<T>::value>::type>
Arg (T value)
Arg (const Arg &)=delete
Arg & operator= (const Arg &)=delete
absl::string_view piece () const
Detailed Description
Definition at line 103 of file substitute.h.
Constructor & Destructor Documentation
Arg() [1/22]
absl::substitute_internal::Arg::Arg (const char * value) inline
Definition at line 108 of file substitute.h.
      : piece_(absl::NullSafeStringView(value)) {}
Arg() [2/22]
template<typename Allocator > absl::substitute_internal::Arg::Arg (const std::basic_string< char, std::char_traits< char >, Allocator > & value) inline noexcept
Definition at line 111 of file substitute.h.
      : piece_(value) {}
Arg() [3/22]
absl::substitute_internal::Arg::Arg (absl::string_view value) inline
Definition at line 115 of file substitute.h.
      : piece_(value) {}
Arg() [4/22]
absl::substitute_internal::Arg::Arg (char value) inline
Definition at line 125 of file substitute.h.
      : piece_(scratch_, 1) {
    scratch_[0] = value;
  }
References value.
Arg() [5/22]
absl::substitute_internal::Arg::Arg (short value) inline
Definition at line 129 of file substitute.h.
      : piece_(scratch_,
               static_cast<size_t>(
                   numbers_internal::FastIntToBuffer(value, scratch_) -
                   scratch_)) {}
Arg() [6/22]
absl::substitute_internal::Arg::Arg (unsigned short value) inline
Definition at line 134 of file substitute.h.
      : piece_(scratch_,
               static_cast<size_t>(
                   numbers_internal::FastIntToBuffer(value, scratch_) -
                   scratch_)) {}
Arg() [7/22]
absl::substitute_internal::Arg::Arg (int value) inline
Definition at line 139 of file substitute.h.
      : piece_(scratch_,
               static_cast<size_t>(
                   numbers_internal::FastIntToBuffer(value, scratch_) -
                   scratch_)) {}
Arg() [8/22]
absl::substitute_internal::Arg::Arg (unsigned int value) inline
Definition at line 144 of file substitute.h.
      : piece_(scratch_,
               static_cast<size_t>(
                   numbers_internal::FastIntToBuffer(value, scratch_) -
                   scratch_)) {}
Arg() [9/22]
absl::substitute_internal::Arg::Arg (long value) inline
Definition at line 149 of file substitute.h.
      : piece_(scratch_,
               static_cast<size_t>(
                   numbers_internal::FastIntToBuffer(value, scratch_) -
                   scratch_)) {}
Arg() [10/22]
absl::substitute_internal::Arg::Arg (unsigned long value) inline
Definition at line 154 of file substitute.h.
      : piece_(scratch_,
               static_cast<size_t>(
                   numbers_internal::FastIntToBuffer(value, scratch_) -
                   scratch_)) {}
Arg() [11/22]
absl::substitute_internal::Arg::Arg (long long value) inline
Definition at line 159 of file substitute.h.
      : piece_(scratch_,
               static_cast<size_t>(
                   numbers_internal::FastIntToBuffer(value, scratch_) -
                   scratch_)) {}
Arg() [12/22]
absl::substitute_internal::Arg::Arg (unsigned long long value) inline
Definition at line 164 of file substitute.h.
      : piece_(scratch_,
               static_cast<size_t>(
                   numbers_internal::FastIntToBuffer(value, scratch_) -
                   scratch_)) {}
Arg() [13/22]
absl::substitute_internal::Arg::Arg (float value) inline
Definition at line 169 of file substitute.h.
      : piece_(scratch_, numbers_internal::SixDigitsToBuffer(value, scratch_)) {
  }
Arg() [14/22]
absl::substitute_internal::Arg::Arg (double value) inline
Definition at line 172 of file substitute.h.
      : piece_(scratch_, numbers_internal::SixDigitsToBuffer(value, scratch_)) {
  }
Arg() [15/22]
absl::substitute_internal::Arg::Arg (bool value) inline
Definition at line 175 of file substitute.h.
      : piece_(value ? "true" : "false") {}
Arg() [16/22]
template<typename T , typename = typename std::enable_if< strings_internal::HasAbslStringify<T>::value>::type> absl::substitute_internal::Arg::Arg (const T & v, strings_internal::StringifySink && sink = {}) inline
Definition at line 180 of file substitute.h.
                                                         {})
      : piece_(strings_internal::ExtractStringification(sink, v)) {}
Arg() [17/22]
absl::substitute_internal::Arg::Arg (Hex hex)
Definition at line 120 of file substitute.cc.
                {
  char* const end = &scratch_[numbers_internal::kFastToBufferSize];
  char* writer = end;
  uint64_t value = hex.value;
  do {
    *--writer = absl::numbers_internal::kHexChar[value & 0xF];
    value >>= 4;
  } while (value != 0);
  char* beg;
  if (end - writer < hex.width) {
    beg = end - hex.width;
    std::fill_n(beg, writer - beg, hex.fill);
  } else {
    beg = writer;
  }
  piece_ = absl::string_view(beg, static_cast<size_t>(end - beg));
}
References end, absl::hex, and absl::numbers_internal::kHexChar.
Arg() [18/22]
absl::substitute_internal::Arg::Arg (Dec dec)
Definition at line 141 of file substitute.cc.
                {
  assert(dec.width <= numbers_internal::kFastToBufferSize);
  char* const end = &scratch_[numbers_internal::kFastToBufferSize];
  char* const minfill = end - dec.width;
  char* writer = end;
  uint64_t value = dec.value;
  bool neg = dec.neg;
  while (value > 9) {
    *--writer = '0' + (value % 10);
    value /= 10;
  }
  *--writer = '0' + static_cast<char>(value);
  if (neg) *--writer = '-';
  ptrdiff_t fillers = writer - minfill;
  if (fillers > 0) {
    // Tricky: if the fill character is ' ', then it's <fill><+/-><digits>
    // But...: if the fill character is '0', then it's <+/-><fill><digits>
    bool add_sign_again = false;
    if (neg && dec.fill == '0') {  // If filling with '0',
      ++writer;                    // ignore the sign we just added
      add_sign_again = true;       // and re-add the sign later.
    }
    writer -= fillers;
    std::fill_n(writer, fillers, dec.fill);
    if (add_sign_again) *--writer = '-';
  }
  piece_ = absl::string_view(writer, static_cast<size_t>(end - writer));
}
References end, absl::Dec::fill, absl::Dec::neg, absl::Dec::value, value, and absl::Dec::width.
Arg() [19/22]
template<typename T , absl::enable_if_t< std::is_class< T >::value &&(std::is_same< T, std::vector< bool >::reference >::value||std::is_same< T, std::vector< bool >::const_reference >::value)> * = nullptr> absl::substitute_internal::Arg::Arg (T value) inline
Definition at line 195 of file substitute.h.
      : Arg(static_cast<bool>(value)) {}
Arg() [20/22]
absl::substitute_internal::Arg::Arg (const void * value)
Definition at line 100 of file substitute.cc.
{
  static_assert(sizeof(scratch_) >= sizeof(value) * 2 + 2,
                "fix sizeof(scratch_)");
  if (value == nullptr) {
    piece_ = "NULL";
  } else {
    char* ptr = scratch_ + sizeof(scratch_);
    uintptr_t num = reinterpret_cast<uintptr_t>(value);
    do {
      *--ptr = absl::numbers_internal::kHexChar[num & 0xf];
      num >>= 4;
    } while (num != 0);
    *--ptr = 'x';
    *--ptr = '0';
    piece_ = absl::string_view(
        ptr, static_cast<size_t>(scratch_ + sizeof(scratch_) - ptr));
  }
}
References absl::numbers_internal::kHexChar, num, ptr, and value.
Arg() [21/22]
template<typename T , typename = typename std::enable_if< std::is_enum<T>{} && !std::is_convertible<T, int>{} && !strings_internal::HasAbslStringify<T>::value>::type> absl::substitute_internal::Arg::Arg (T value) inline
Definition at line 208 of file substitute.h.
      : Arg(static_cast<typename std::underlying_type<T>::type>(value)) {}
Arg() [22/22]
absl::substitute_internal::Arg::Arg (const Arg &) delete
Member Function Documentation
operator=()
Arg & absl::substitute_internal::Arg::operator= (const Arg &) delete
piece()
absl::string_view absl::substitute_internal::Arg::piece () const inline
Definition at line 214 of file substitute.h.
{ return piece_; }
Referenced by absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), and absl::SubstituteAndAppend().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/substitute.h
open_spiel/abseil-cpp/absl/strings/substitute.cc