open spiel: open_spiel::lewis_signaling::LewisSignalingState Class Reference
open_spiel::lewis_signaling::LewisSignalingState Class Reference
#include <lewis_signaling.h>
Public Member Functions
LewisSignalingState (std::shared_ptr< const Game > game, int num_states, int num_messages, const std::vector< double > &payoffs)
LewisSignalingState (const LewisSignalingState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move_id) const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 57 of file lewis_signaling.h.
Constructor & Destructor Documentation
LewisSignalingState() [1/2]
open_spiel::lewis_signaling::LewisSignalingState::LewisSignalingState (std::shared_ptr< const Game > game, int num_states, int num_messages, const std::vector< double > & payoffs)
Definition at line 155 of file lewis_signaling.cc.
    : State(game),
      num_states_(num_states),
      num_messages_(num_messages),
      payoffs_(payoffs),
      cur_player_(kChancePlayerId),
      state_(kUnassignedValue),
      message_(kUnassignedValue),
      action_(kUnassignedValue) {}
Referenced by Clone().
LewisSignalingState() [2/2]
open_spiel::lewis_signaling::LewisSignalingState::LewisSignalingState (const LewisSignalingState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::lewis_signaling::LewisSignalingState::ActionToString (Player player, Action move_id) const override virtual
Implements open_spiel::State.
Definition at line 65 of file lewis_signaling.cc.
{
  if (player == kChancePlayerId) {
    return absl::StrCat("State ", move_id);
  } else if (static_cast<Players>(player) == Players::kSender) {
    return absl::StrCat("Message ", move_id);
  } else if (static_cast<Players>(player) == Players::kReceiver) {
    return absl::StrCat("Action ", move_id);
  } else {
    SpielFatalError("Invalid player");
  }
}
References open_spiel::kChancePlayerId, open_spiel::lewis_signaling::kReceiver, open_spiel::lewis_signaling::kSender, player, open_spiel::SpielFatalError(), and absl::StrCat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::lewis_signaling::LewisSignalingState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 215 of file lewis_signaling.cc.
          {
  SPIEL_CHECK_TRUE(IsChanceNode());
  std::vector<std::pair<Action, double>> outcomes;
  outcomes.reserve(num_states_);
  for (int i = 0; i < num_states_; ++i) {
    outcomes.push_back({i, 1.0 / num_states_});
  }
  return outcomes;
}
References i, open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::lewis_signaling::LewisSignalingState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 250 of file lewis_signaling.cc.
{
  return std::unique_ptr<State>(new LewisSignalingState(*this));
}
References LewisSignalingState().
CurrentPlayer()
int open_spiel::lewis_signaling::LewisSignalingState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 167 of file lewis_signaling.cc.
{
  return IsTerminal() ? kTerminalPlayerId : cur_player_;
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::lewis_signaling::LewisSignalingState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 171 of file lewis_signaling.cc.
{
  if (IsChanceNode()) {
    SPIEL_CHECK_LT(action, num_states_);
    state_ = action;
    cur_player_ = static_cast<int>(Players::kSender);
  } else {
    if (static_cast<Players>(cur_player_) == Players::kSender) {
      SPIEL_CHECK_LT(action, num_messages_);
      message_ = action;
      cur_player_ = static_cast<int>(Players::kReceiver);
    } else if (static_cast<Players>(cur_player_) == Players::kReceiver) {
      action_ = action;
    } else {
      SpielFatalError("Invalid player");
    }
  }
}
References action, open_spiel::State::IsChanceNode(), open_spiel::lewis_signaling::kReceiver, open_spiel::lewis_signaling::kSender, SPIEL_CHECK_LT, and open_spiel::SpielFatalError().
InformationStateString()
std::string open_spiel::lewis_signaling::LewisSignalingState::InformationStateString (Player player) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 72 of file lewis_signaling.h.
{
    return ObservationString(player);
  }
References open_spiel::State::ObservationString(), and player.
InformationStateTensor()
void open_spiel::lewis_signaling::LewisSignalingState::InformationStateTensor (Player player, absl::Span< float > values) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 75 of file lewis_signaling.h.
{
    return ObservationTensor(player, values);
  }
References open_spiel::State::ObservationTensor(), player, and values.
IsTerminal()
bool open_spiel::lewis_signaling::LewisSignalingState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 78 of file lewis_signaling.cc.
{
  // Game ends after chance, sender, and receiver act
  return (history_.size() == 3);
}
References open_spiel::State::history_.
Referenced by CurrentPlayer(), LegalActions(), ObservationTensor(), and Returns().
LegalActions()
std::vector< Action > open_spiel::lewis_signaling::LewisSignalingState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 189 of file lewis_signaling.cc.
{
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else if (IsTerminal()) {
    return {};
  } else if (static_cast<Players>(cur_player_) == Players::kSender) {
    // Choose one of the messages if player is the sender
    std::vector<Action> legal_actions;
    legal_actions.reserve(num_messages_);
    for (int i = 0; i < num_messages_; ++i) {
      legal_actions.push_back(i);
    }
    return legal_actions;
  } else if (static_cast<Players>(cur_player_) == Players::kReceiver) {
    // Choose one of the actions if player is the receiver
    std::vector<Action> legal_actions;
    legal_actions.reserve(num_states_);
    for (int i = 0; i < num_states_; ++i) {
      legal_actions.push_back(i);
    }
    return legal_actions;
  } else {
    SpielFatalError("Invalid node");
  }
}
References i, open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::lewis_signaling::kReceiver, open_spiel::lewis_signaling::kSender, open_spiel::State::LegalChanceOutcomes(), and open_spiel::SpielFatalError().
ObservationString()
std::string open_spiel::lewis_signaling::LewisSignalingState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 93 of file lewis_signaling.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (IsChanceNode()) {
    return "ChanceNode -- no observation";
  }
  std::string str = "";
  // Whose turn is it?
  absl::StrAppend(&str, "Current turn: ", cur_player_, "\n");
  // Show state to the sender, message to the receiver
  if (static_cast<Players>(player) == Players::kSender) {
    absl::StrAppend(&str, "State: ", state_, "\n");
  } else if (static_cast<Players>(player) == Players::kReceiver) {
    absl::StrAppend(&str, "Message: ", message_, "\n");
  } else {
    SpielFatalError("Invalid player");
  }
  return str;
}
References open_spiel::State::IsChanceNode(), open_spiel::lewis_signaling::kReceiver, open_spiel::lewis_signaling::kSender, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and absl::StrAppend().
ObservationTensor()
void open_spiel::lewis_signaling::LewisSignalingState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 117 of file lewis_signaling.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  std::fill(values.begin(), values.end(), 0);
  if (IsChanceNode()) {
    // No observations at chance nodes.
    return;
  }
  // 2 bits to indicate whose turn it is.
  int offset = 0;
  values[cur_player_] = 1;
  offset += 2;
  // 1 bit to indicate whether it's terminal
  values[offset] = IsTerminal() ? 1 : 0;
  offset += 1;
  // one-hot vector for the state/message
  if (static_cast<Players>(player) == Players::kSender) {
    if (state_ != kUnassignedValue) {
      values[offset + state_] = 1;
      offset += num_states_;
    }
  } else if (static_cast<Players>(player) == Players::kReceiver) {
    if (message_ != kUnassignedValue) {
      values[offset + message_] = 1;
      offset += num_messages_;
    }
  } else {
    SpielFatalError("Invalid player");
  }
}
References open_spiel::State::game_, open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::lewis_signaling::kReceiver, open_spiel::lewis_signaling::kSender, open_spiel::lewis_signaling::kUnassignedValue, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and values.
Returns()
std::vector< double > open_spiel::lewis_signaling::LewisSignalingState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 83 of file lewis_signaling.cc.
{
  if (!IsTerminal()) {
    return {0.0, 0.0};
  } else {
    // Find payoff from the payoff matrix based on state, action
    int payoff_idx = num_states_ * state_ + action_;
    return {payoffs_[payoff_idx], payoffs_[payoff_idx]};
  }
}
References IsTerminal().
ToString()
std::string open_spiel::lewis_signaling::LewisSignalingState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 226 of file lewis_signaling.cc.
{
  switch (history_.size()) {
    case 0:  // Before allocating state
      return "Initial chance node";
      break;
    case 1:  // After allocating state
      return absl::StrCat("State ", state_);
      break;
    case 2:  // After sending a message
      return absl::StrCat("State ", state_, ", Message ", message_);
      break;
    case 3:  // After taking an action
      return absl::StrCat("State ", state_, ", Message ", message_, ", Action ",
                          action_);
      break;
    default:
      SpielFatalError("Invalid state");
  }
}
References open_spiel::State::history_, open_spiel::SpielFatalError(), and absl::StrCat().
The documentation for this class was generated from the following files:
open_spiel/games/lewis_signaling/lewis_signaling.h
open_spiel/games/lewis_signaling/lewis_signaling.cc