open spiel: open_spiel::Policy Class Reference
open_spiel::Policy Class Reference
#include <policy.h>
Public Member Functions
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
virtual ActionsAndProbs GetStatePolicy (const State &state) const
virtual ActionsAndProbs GetStatePolicy (const State &state, Player player) const
virtual ActionsAndProbs GetStatePolicy (const std::string &info_state) const
virtual std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const
Detailed Description
Definition at line 69 of file policy.h.
Constructor & Destructor Documentation
~Policy()
virtual open_spiel::Policy::~Policy () virtual default
Member Function Documentation
GetStatePolicy() [1/3]
virtual ActionsAndProbs open_spiel::Policy::GetStatePolicy (const State & state) const inline virtual
Reimplemented in open_spiel::algorithms::AFCCETabularPolicy, open_spiel::algorithms::AFCETabularPolicy, open_spiel::algorithms::CCETabularPolicy, open_spiel::algorithms::CETabularPolicy, open_spiel::algorithms::CFRAveragePolicy, open_spiel::algorithms::CFRCurrentPolicy, open_spiel::algorithms::EFCCETabularPolicy, open_spiel::algorithms::EFCETabularPolicy, open_spiel::algorithms::ExplorativeSamplingPolicy, open_spiel::algorithms::TargetedPolicy, open_spiel::PartialTabularPolicy, open_spiel::PyPolicy, and open_spiel::universal_poker::UniformRestrictedActions.
Definition at line 116 of file policy.h.
{
    return GetStatePolicy(state, state.CurrentPlayer());
  }
References GetStatePolicy(), and state.
Referenced by open_spiel::algorithms::ExpectedReturns(), open_spiel::algorithms::GetStateDistribution(), GetStatePolicy(), GetStatePolicy(), GetStatePolicyAsMap(), GetStatePolicyAsMap(), GetStatePolicyAsParallelVectors(), GetStatePolicyAsParallelVectors(), and open_spiel::init_pyspiel_policy().
GetStatePolicy() [2/3]
virtual ActionsAndProbs open_spiel::Policy::GetStatePolicy (const State & state, Player player) const inline virtual
Reimplemented in open_spiel::algorithms::AFCCETabularPolicy, open_spiel::algorithms::AFCETabularPolicy, open_spiel::algorithms::CCETabularPolicy, open_spiel::algorithms::CETabularPolicy, open_spiel::algorithms::CFRAveragePolicy, open_spiel::algorithms::CFRCurrentPolicy, open_spiel::algorithms::EFCCETabularPolicy, open_spiel::algorithms::EFCETabularPolicy, open_spiel::FirstActionPolicy, open_spiel::PartialTabularPolicy, open_spiel::PreferredActionPolicy, open_spiel::PyPolicy, and open_spiel::UniformPolicy.
Definition at line 123 of file policy.h.
{
    return GetStatePolicy(state.InformationStateString(player));
  }
References GetStatePolicy(), player, and state.
GetStatePolicy() [3/3]
virtual ActionsAndProbs open_spiel::Policy::GetStatePolicy (const std::string & info_state) const inline virtual
Reimplemented in open_spiel::algorithms::AFCCETabularPolicy, open_spiel::algorithms::AFCETabularPolicy, open_spiel::algorithms::CCETabularPolicy, open_spiel::algorithms::CETabularPolicy, open_spiel::algorithms::CFRAveragePolicy, open_spiel::algorithms::CFRCurrentPolicy, open_spiel::algorithms::DeterministicTabularPolicy, open_spiel::algorithms::EFCCETabularPolicy, open_spiel::algorithms::EFCETabularPolicy, open_spiel::algorithms::ExplorativeSamplingPolicy, open_spiel::PartialTabularPolicy, open_spiel::PyPolicy, and open_spiel::TabularPolicy.
Definition at line 132 of file policy.h.
{
    SpielFatalError("GetStatePolicy(const std::string&) unimplemented.");
  }
References open_spiel::SpielFatalError().
GetStatePolicyAsMap() [1/2]
virtual std::unordered_map< Action, double > open_spiel::Policy::GetStatePolicyAsMap (const State & state) const inline virtual
Reimplemented in open_spiel::PyPolicy.
Definition at line 95 of file policy.h.
{
    std::unordered_map<Action, double> pmap;
    for (const auto& action_and_prob : GetStatePolicy(state)) {
      pmap[action_and_prob.first] = action_and_prob.second;
    }
    return pmap;
  }
References GetStatePolicy(), and state.
Referenced by open_spiel::init_pyspiel_policy().
GetStatePolicyAsMap() [2/2]
virtual std::unordered_map< Action, double > open_spiel::Policy::GetStatePolicyAsMap (const std::string & info_state) const inline virtual
Reimplemented in open_spiel::PyPolicy.
Definition at line 104 of file policy.h.
{
    std::unordered_map<Action, double> pmap;
    for (const auto& action_and_prob : GetStatePolicy(info_state)) {
      pmap[action_and_prob.first] = action_and_prob.second;
    }
    return pmap;
  }
References GetStatePolicy().
GetStatePolicyAsParallelVectors() [1/2]
virtual std::pair< std::vector< Action >, std::vector< double > > open_spiel::Policy::GetStatePolicyAsParallelVectors (const State & state) const inline virtual
Reimplemented in open_spiel::PyPolicy.
Definition at line 75 of file policy.h.
{
    std::pair<std::vector<Action>, std::vector<double>> parray;
    for (const auto& action_and_prob : GetStatePolicy(state)) {
      parray.first.push_back(action_and_prob.first);
      parray.second.push_back(action_and_prob.second);
    }
    return parray;
  }
References GetStatePolicy(), and state.
Referenced by open_spiel::init_pyspiel_policy().
GetStatePolicyAsParallelVectors() [2/2]
virtual std::pair< std::vector< Action >, std::vector< double > > open_spiel::Policy::GetStatePolicyAsParallelVectors (const std::string & info_state) const inline virtual
Reimplemented in open_spiel::PyPolicy.
Definition at line 86 of file policy.h.
{
    std::pair<std::vector<Action>, std::vector<double>> parray;
    for (const auto& action_and_prob : GetStatePolicy(info_state)) {
      parray.first.push_back(action_and_prob.first);
      parray.second.push_back(action_and_prob.second);
    }
    return parray;
  }
References GetStatePolicy().
Serialize()
virtual std::string open_spiel::Policy::Serialize (int double_precision = -1, std::string delimiter = "<~>") const inline virtual
Reimplemented in open_spiel::FirstActionPolicy, open_spiel::PreferredActionPolicy, open_spiel::PyPolicy, open_spiel::TabularPolicy, and open_spiel::UniformPolicy.
Definition at line 143 of file policy.h.
{
    SpielFatalError("Serialize(std::string delimiter) unimplemented.");
  }
References open_spiel::SpielFatalError().
Referenced by open_spiel::init_pyspiel_policy().
The documentation for this class was generated from the following file:
open_spiel/policy.h