open spiel: open_spiel::PyGame Class Reference
open_spiel::PyGame Class Reference
#include <python_games.h>
Public Member Functions
PyGame (GameType game_type, GameInfo game_info, GameParameters game_parameters)
std::unique_ptr< State > NewInitialState () const override
std::unique_ptr< State > NewInitialStateForPopulation (int population) const override
int MaxChanceNodesInHistory () const override
int NumDistinctActions () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
absl::optional< double > UtilitySum () const override
int MaxGameLength () const override
int MaxChanceOutcomes () const override
std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const override
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
const Observer & default_observer () const
const Observer & info_state_observer () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 29 of file python_games.h.
Constructor & Destructor Documentation
PyGame()
open_spiel::PyGame::PyGame (GameType game_type, GameInfo game_info, GameParameters game_parameters)
Definition at line 35 of file python_games.cc.
    : Game(game_type, game_parameters), info_(game_info) {}
Member Function Documentation
default_observer()
const Observer & open_spiel::PyGame::default_observer () const
Definition at line 57 of file python_games.cc.
{
  if (!default_observer_) default_observer_ = MakeObserver(kDefaultObsType, {});
  return *default_observer_;
}
References open_spiel::kDefaultObsType, and MakeObserver().
Referenced by ObservationTensorShape().
DeserializeState()
std::unique_ptr< State > open_spiel::PyGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 304 of file python_games.cc.
{
  std::unique_ptr<State> state = NewInitialState();
  open_spiel::down_cast<PyState*>(state.get())->Deserialize(str);
  return state;
}
References open_spiel::down_cast(), NewInitialState(), and state.
info_state_observer()
const Observer & open_spiel::PyGame::info_state_observer () const
Definition at line 62 of file python_games.cc.
{
  if (!info_state_observer_)
    info_state_observer_ = MakeObserver(kInfoStateObsType, {});
  return *info_state_observer_;
}
References open_spiel::kInfoStateObsType, and MakeObserver().
Referenced by InformationStateTensorShape().
InformationStateTensorShape()
std::vector< int > open_spiel::PyGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 273 of file python_games.cc.
{
  TrackingVectorAllocator allocator;
  auto state = NewInitialState();
  info_state_observer().WriteTensor(*state, kDefaultPlayerId, &allocator);
  return TensorShape(allocator);
}
References info_state_observer(), open_spiel::kDefaultPlayerId, NewInitialState(), state, and open_spiel::Observer::WriteTensor().
MakeObserver()
std::shared_ptr< Observer > open_spiel::PyGame::MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters & params) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 221 of file python_games.cc.
{
  py::object h = py::cast(this);
  py::function f = h.attr("make_py_observer");
  if (!f) SpielFatalError("make_py_observer not implemented");
  py::object observer = (iig_obs_type.has_value() ?
      f(iig_obs_type.value(), params) : f(params));
  return std::make_shared<PyObserver>(observer);
}
References absl::optional< T >::has_value(), open_spiel::SpielFatalError(), and absl::optional< T >::value().
Referenced by default_observer(), and info_state_observer().
MaxChanceNodesInHistory()
int open_spiel::PyGame::MaxChanceNodesInHistory () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 51 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(int, Game,
                              "max_chance_nodes_in_history",
                              MaxChanceNodesInHistory);
}
References MaxChanceNodesInHistory().
Referenced by MaxChanceNodesInHistory().
MaxChanceOutcomes()
int open_spiel::PyGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 47 of file python_games.h.
{ return info_.max_chance_outcomes; }
References open_spiel::GameInfo::max_chance_outcomes.
MaxGameLength()
int open_spiel::PyGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 46 of file python_games.h.
{ return info_.max_game_length; }
References open_spiel::GameInfo::max_game_length.
MaxUtility()
double open_spiel::PyGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 42 of file python_games.h.
{ return info_.max_utility; }
References open_spiel::GameInfo::max_utility.
MinUtility()
double open_spiel::PyGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 41 of file python_games.h.
{ return info_.min_utility; }
References open_spiel::GameInfo::min_utility.
NewInitialState()
std::unique_ptr< State > open_spiel::PyGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 39 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(std::unique_ptr<State>, Game, "new_initial_state",
                              NewInitialState);
}
References NewInitialState().
Referenced by DeserializeState(), InformationStateTensorShape(), NewInitialState(), and ObservationTensorShape().
NewInitialStateForPopulation()
std::unique_ptr< State > open_spiel::PyGame::NewInitialStateForPopulation (int population) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 44 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(std::unique_ptr<State>, Game,
                              "new_initial_state_for_population",
                              NewInitialStateForPopulation, population);
}
References NewInitialStateForPopulation().
Referenced by NewInitialStateForPopulation().
NumDistinctActions()
int open_spiel::PyGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 39 of file python_games.h.
{ return info_.num_distinct_actions; }
References open_spiel::GameInfo::num_distinct_actions.
NumPlayers()
int open_spiel::PyGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 40 of file python_games.h.
{ return info_.num_players; }
References open_spiel::GameInfo::num_players.
ObservationTensorShape()
std::vector< int > open_spiel::PyGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 288 of file python_games.cc.
{
  TrackingVectorAllocator allocator;
  auto state = NewInitialState();
  default_observer().WriteTensor(*state, kDefaultPlayerId, &allocator);
  return TensorShape(allocator);
}
References default_observer(), open_spiel::kDefaultPlayerId, NewInitialState(), state, and open_spiel::Observer::WriteTensor().
UtilitySum()
absl::optional< double > open_spiel::PyGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 43 of file python_games.h.
{
    return info_.utility_sum;
  }
References open_spiel::GameInfo::utility_sum.
The documentation for this class was generated from the following files:
open_spiel/python/pybind11/python_games.h
open_spiel/python/pybind11/python_games.cc