open spiel: open_spiel::hearts::XinxinBot Class Reference
open_spiel::hearts::XinxinBot Class Reference
#include <xinxin_bot.h>
Public Member Functions
XinxinBot (int rules, int uct_num_runs, double uct_c_val, int iimc_num_worlds, bool use_threads)
Action Step (const State &state) override
void InformAction (const State &state, Player player_id, Action action) override
void Restart () override
void RestartAt (const State &state) override
bool ProvidesForceAction () override
void ForceAction (const State &state, Action action) override
Public Member Functions inherited from open_spiel::Bot
virtual ~Bot ()=default
virtual void InformActions (const State &state, const std::vector< Action > &actions)
virtual bool ProvidesPolicy ()
virtual ActionsAndProbs GetPolicy (const State &state)
virtual std::pair< ActionsAndProbs, Action > StepWithPolicy (const State &state)
virtual bool IsClonable () const
virtual std::unique_ptr< Bot > Clone ()
Static Public Member Functions
static int XinxinRules (GameParameters params)
Detailed Description
Definition at line 34 of file xinxin_bot.h.
Constructor & Destructor Documentation
XinxinBot()
open_spiel::hearts::XinxinBot::XinxinBot (int rules, int uct_num_runs, double uct_c_val, int iimc_num_worlds, bool use_threads) explicit
Definition at line 59 of file xinxin_bot.cc.
    : uct_num_runs_(uct_num_runs),
      uct_c_val_(uct_c_val),
      iimc_num_worlds_(iimc_num_worlds),
      use_threads_(use_threads),
      initial_state_(nullptr) {
  pass_dir_ = ::hearts::tPassDir::kHold;
  num_cards_dealt_ = 0;
  game_state_ = std::make_unique<::hearts::HeartsGameState>();
  game_state_->setRules(rules);
  game_state_->deletePlayers();
  for (int i = 0; i < kNumPlayers; i++) {
    initial_deal_.push_back(std::vector<::hearts::card>());
    // The game state destructor deletes the players, so we do not manage their
    // memory in this bot.
    std::unique_ptr<::hearts::SafeSimpleHeartsPlayer> player = CreatePlayer();
    ::hearts::SafeSimpleHeartsPlayer* released_player = player.release();
    game_state_->addPlayer(released_player);
    released_player->setGameState(game_state_.get());
  }
  SPIEL_CHECK_EQ(xinxin_uct_.size(), kNumPlayers);
  SPIEL_CHECK_EQ(xinxin_mc_.size(), kNumPlayers);
  SPIEL_CHECK_EQ(xinxin_playouts_.size(), kNumPlayers);
}
References i, open_spiel::hearts::kNumPlayers, player, and SPIEL_CHECK_EQ.
Member Function Documentation
ForceAction()
void open_spiel::hearts::XinxinBot::ForceAction (const State & state, Action action) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 200 of file xinxin_bot.cc.
{
  ::hearts::Move* move = new ::hearts::CardMove(
      GetXinxinAction(action), game_state_->getNextPlayerNum());
  game_state_->ApplyMove(move);
  game_state_->freeMove(move);
}
References action, and open_spiel::hearts::GetXinxinAction().
InformAction()
void open_spiel::hearts::XinxinBot::InformAction (const State & state, Player player_id, Action action) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 163 of file xinxin_bot.cc.
{
  if (player_id == kChancePlayerId) {
    if (state.ChanceOutcomes().size() == 4 && num_cards_dealt_ == 0) {
      // this is guaranteed to be the pass dir selection action as long as
      // that remains as the first optional chance node in the Hearts
      // implementation
      pass_dir_ = kXinxinPassDir[action];
    } else {
      ::hearts::card card = GetXinxinAction(action);
      initial_deal_[num_cards_dealt_ % kNumPlayers].push_back(card);
      if (++num_cards_dealt_ == kNumCards) {
        NewDeal(&initial_deal_, pass_dir_, 0);
      }
    }
  } else {
    if (state.IsTerminal()) {
      if (!game_state_->Done()) {
        LogStateMismatchError(state, "xinxin state is not terminal.");
      }
      std::vector<double> returns = state.Returns();
      for (Player p = 0; p < returns.size(); p++) {
        // returns in open_spiel hearts are transformed from the score
        // to reflect that getting the least number of total points is better
        if (returns[p] != kTotalPositivePoints - game_state_->score(p)) {
          LogStateMismatchError(state, "xinxin score != OpenSpiel score");
        }
      }
    } else {
      ::hearts::Move* move =
          new ::hearts::CardMove(GetXinxinAction(action), player_id);
      game_state_->ApplyMove(move);
      game_state_->freeMove(move);
    }
  }
}
References action, open_spiel::hearts::GetXinxinAction(), open_spiel::kChancePlayerId, open_spiel::hearts::kNumCards, open_spiel::hearts::kNumPlayers, open_spiel::hearts::kTotalPositivePoints, and state.
ProvidesForceAction()
bool open_spiel::hearts::XinxinBot::ProvidesForceAction () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 44 of file xinxin_bot.h.
{ return true; }
Restart()
void open_spiel::hearts::XinxinBot::Restart () override virtual
Reimplemented from open_spiel::Bot.
Definition at line 85 of file xinxin_bot.cc.
{
  game_state_->Reset();
  pass_dir_ = ::hearts::tPassDir::kHold;
  num_cards_dealt_ = 0;
  for (auto& hand : initial_deal_) {
    hand.clear();
  }
}
Referenced by RestartAt().
RestartAt()
void open_spiel::hearts::XinxinBot::RestartAt (const State & state) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 94 of file xinxin_bot.cc.
{
  if (initial_state_ == nullptr) {
    initial_state_ = state.GetGame()->NewInitialState();
  }
  // TODO(author5): define a default operator== in State.
  if (state.ToString() != initial_state_->ToString()) {
    SpielFatalError("XinxinBot::RestartAt only supports restarts from the "
                    "initial state.");
  }
  Restart();
}
References Restart(), open_spiel::SpielFatalError(), and state.
Step()
Action open_spiel::hearts::XinxinBot::Step (const State & state) override virtual
Implements open_spiel::Bot.
Definition at line 138 of file xinxin_bot.cc.
{
  // check that xinxin and open_spiel agree on legal actions
  ::hearts::Move* all_moves = game_state_->getAllMoves();
  std::vector<Action> xinxin_actions;
  while (all_moves != nullptr) {
    ::hearts::card card = static_cast<::hearts::CardMove*>(all_moves)->c;
    xinxin_actions.push_back(GetOpenSpielAction(card));
    all_moves = all_moves->next;
  }
  absl::c_sort(xinxin_actions);
  std::vector<Action> legal_actions = state.LegalActions();
  if (legal_actions != xinxin_actions) {
    LogStateMismatchError(state,
                          "xinxin legal actions != OpenSpiel legal actions.");
  }
  // test passed!
  ::hearts::CardMove* move =
      static_cast<::hearts::CardMove*>(game_state_->getNextPlayer()->Play());
  game_state_->ApplyMove(move);
  Action act = GetOpenSpielAction(move->c);
  game_state_->freeMove(move);
  SPIEL_CHECK_TRUE(absl::c_binary_search(legal_actions, act));
  return act;
}
References absl::c_binary_search(), absl::c_sort(), open_spiel::hearts::GetOpenSpielAction(), SPIEL_CHECK_TRUE, and state.
XinxinRules()
int open_spiel::hearts::XinxinBot::XinxinRules (GameParameters params) static
Definition at line 207 of file xinxin_bot.cc.
{
  int rules = ::hearts::kQueenPenalty;
  if (params["pass_cards"].bool_value()) rules |= ::hearts::kDoPassCards;
  if (params["no_pts_on_first_trick"].bool_value())
    rules |= ::hearts::kNoHeartsFirstTrick | ::hearts::kNoQueenFirstTrick;
  if (params["can_lead_any_club"].bool_value()) {
    rules |= ::hearts::kLeadClubs;
  } else {
    rules |= ::hearts::kLead2Clubs;
  }
  if (params["jd_bonus"].bool_value()) rules |= ::hearts::kJackBonus;
  if (params["avoid_all_tricks_bonus"].bool_value())
    rules |= ::hearts::kNoTrickBonus;
  if (params["qs_breaks_hearts"].bool_value())
    rules |= ::hearts::kQueenBreaksHearts;
  if (params["must_break_hearts"].bool_value())
    rules |= ::hearts::kMustBreakHearts;
  if (params["can_lead_hearts_instead_of_qs"].bool_value()) {
    SpielFatalError("Xinxin does not support leading hearts instead of qs");
  }
  return rules;
}
References open_spiel::SpielFatalError().
Referenced by open_spiel::hearts::MakeXinxinBot().
The documentation for this class was generated from the following files:
open_spiel/bots/xinxin/xinxin_bot.h
open_spiel/bots/xinxin/xinxin_bot.cc