open spiel: absl::container_internal::CommonFieldsGenerationInfoDisabled Class Reference
absl::container_internal::CommonFieldsGenerationInfoDisabled Class Reference
#include <raw_hash_set.h>
Public Member Functions
CommonFieldsGenerationInfoDisabled ()=default
CommonFieldsGenerationInfoDisabled (CommonFieldsGenerationInfoDisabled &&)=default
CommonFieldsGenerationInfoDisabled & operator= (CommonFieldsGenerationInfoDisabled &&)=default
bool should_rehash_for_bug_detection_on_insert () const
void maybe_increment_generation_on_insert ()
void reset_reserved_growth (size_t, size_t)
size_t reserved_growth () const
void set_reserved_growth (size_t)
GenerationType generation () const
void set_generation (GenerationType)
GenerationType * generation_ptr () const
void set_generation_ptr (GenerationType *)
Detailed Description
Definition at line 815 of file raw_hash_set.h.
Constructor & Destructor Documentation
CommonFieldsGenerationInfoDisabled() [1/2]
absl::container_internal::CommonFieldsGenerationInfoDisabled::CommonFieldsGenerationInfoDisabled () default
CommonFieldsGenerationInfoDisabled() [2/2]
absl::container_internal::CommonFieldsGenerationInfoDisabled::CommonFieldsGenerationInfoDisabled (CommonFieldsGenerationInfoDisabled &&) default
Member Function Documentation
generation()
GenerationType absl::container_internal::CommonFieldsGenerationInfoDisabled::generation () const inline
Definition at line 828 of file raw_hash_set.h.
{ return 0; }
generation_ptr()
GenerationType * absl::container_internal::CommonFieldsGenerationInfoDisabled::generation_ptr () const inline
Definition at line 830 of file raw_hash_set.h.
{ return nullptr; }
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator_at(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator_at().
maybe_increment_generation_on_insert()
void absl::container_internal::CommonFieldsGenerationInfoDisabled::maybe_increment_generation_on_insert () inline
Definition at line 824 of file raw_hash_set.h.
{}
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set().
operator=()
CommonFieldsGenerationInfoDisabled & absl::container_internal::CommonFieldsGenerationInfoDisabled::operator= (CommonFieldsGenerationInfoDisabled &&) default
reserved_growth()
size_t absl::container_internal::CommonFieldsGenerationInfoDisabled::reserved_growth () const inline
Definition at line 826 of file raw_hash_set.h.
{ return 0; }
reset_reserved_growth()
void absl::container_internal::CommonFieldsGenerationInfoDisabled::reset_reserved_growth (size_t , size_t) inline
Definition at line 825 of file raw_hash_set.h.
{}
Referenced by absl::container_internal::CommonFields::reset_reserved_growth().
set_generation()
void absl::container_internal::CommonFieldsGenerationInfoDisabled::set_generation (GenerationType) inline
Definition at line 829 of file raw_hash_set.h.
{}
set_generation_ptr()
void absl::container_internal::CommonFieldsGenerationInfoDisabled::set_generation_ptr (GenerationType *) inline
Definition at line 831 of file raw_hash_set.h.
{}
set_reserved_growth()
void absl::container_internal::CommonFieldsGenerationInfoDisabled::set_reserved_growth (size_t) inline
Definition at line 827 of file raw_hash_set.h.
{}
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::clear().
should_rehash_for_bug_detection_on_insert()
bool absl::container_internal::CommonFieldsGenerationInfoDisabled::should_rehash_for_bug_detection_on_insert () const inline
Definition at line 823 of file raw_hash_set.h.
{ return false; }
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/raw_hash_set.h