open spiel: open_spiel::algorithms::ortools::SequenceFormLpSpecification Class Reference
open_spiel::algorithms::ortools::SequenceFormLpSpecification Class Reference
#include <sequence_form_lp.h>
Public Member Functions
SequenceFormLpSpecification (const Game &game, const std::string &solver_id=kDefaultLinProgSolver)
SequenceFormLpSpecification (std::vector< std::shared_ptr< InfostateTree > > trees, const std::string &solver_id=kDefaultLinProgSolver)
void SpecifyLinearProgram (Player pl)
double Solve ()
void ClearSpecification ()
TabularPolicy OptimalPolicy (Player for_player)
SfStrategy OptimalSfStrategy (Player for_player)
void PrintProblemSpecification ()
const std::vector< std::shared_ptr< InfostateTree > > & trees () const
std::array< const InfostateNode *, 2 > roots () const
std::unordered_map< const InfostateNode *, NodeSpecification > & node_spec ()
operations_research::MPSolver * solver ()
const BijectiveContainer< const InfostateNode * > & terminal_bijection () const
Protected Member Functions
void SpecifyReachProbsConstraints (InfostateNode *player_node)
void SpecifyCfValuesConstraints (InfostateNode *opponent_node)
void SpecifyRootConstraints (const InfostateNode *player_root_node)
void SpecifyObjective (const InfostateNode *opponent_root_node)
Protected Attributes
const std::vector< std::shared_ptr< InfostateTree > > trees_
const BijectiveContainer< const InfostateNode * > terminal_bijection_
std::unique_ptr< operations_research::MPSolver > solver_
std::unordered_map< const InfostateNode *, NodeSpecification > node_spec_
Detailed Description
Definition at line 83 of file sequence_form_lp.h.
Constructor & Destructor Documentation
SequenceFormLpSpecification() [1/2]
open_spiel::algorithms::ortools::SequenceFormLpSpecification::SequenceFormLpSpecification (const Game & game, const std::string & solver_id = kDefaultLinProgSolver)
Definition at line 32 of file sequence_form_lp.cc.
    : SequenceFormLpSpecification(
          {
              MakeInfostateTree(game, 0),
              MakeInfostateTree(game, 1),
          },
          solver_id) {}
References open_spiel::algorithms::MakeInfostateTree().
SequenceFormLpSpecification() [2/2]
open_spiel::algorithms::ortools::SequenceFormLpSpecification::SequenceFormLpSpecification (std::vector< std::shared_ptr< InfostateTree > > trees, const std::string & solver_id = kDefaultLinProgSolver)
Definition at line 41 of file sequence_form_lp.cc.
    : trees_(std::move(trees)),
      terminal_bijection_(ConnectTerminals(*trees_[0], *trees_[1])),
      solver_(MPSolver::CreateSolver(solver_id)),
      node_spec_() {
  SPIEL_CHECK_TRUE(solver_);
  SPIEL_CHECK_EQ(trees_.size(), 2);
}
References solver_, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and trees_.
Member Function Documentation
ClearSpecification()
void open_spiel::algorithms::ortools::SequenceFormLpSpecification::ClearSpecification ()
Definition at line 146 of file sequence_form_lp.cc.
{
  solver_->Clear();
  for (auto& [node, spec] : node_spec_) {
    spec.var_cf_value = nullptr;
    spec.var_reach_prob = nullptr;
    spec.ct_child_cf_value = nullptr;
    spec.ct_parent_cf_value = nullptr;
    spec.ct_child_reach_prob = nullptr;
    spec.ct_parent_reach_prob = nullptr;
  }
}
References node_spec_, and solver_.
Referenced by SpecifyLinearProgram().
node_spec()
std::unordered_map< const InfostateNode *, NodeSpecification > & open_spiel::algorithms::ortools::SequenceFormLpSpecification::node_spec () inline
Definition at line 119 of file sequence_form_lp.h.
{
    return node_spec_;
  }
References node_spec_.
OptimalPolicy()
TabularPolicy open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalPolicy (Player for_player)
Definition at line 186 of file sequence_form_lp.cc.
{
  SPIEL_CHECK_TRUE(for_player == 0 || for_player == 1);
  const InfostateTree* tree = trees_[for_player].get();
  TabularPolicy policy;
  for (DecisionId id : tree->AllDecisionIds()) {
    const InfostateNode* node = tree->decision_infostate(id);
    absl::Span<const Action> actions = node->legal_actions();
    SPIEL_CHECK_EQ(actions.size(), node->num_children());
    ActionsAndProbs state_policy;
    state_policy.reserve(node->num_children());
    double rp_sum = 0.;
    for (int i = 0; i < actions.size(); ++i) {
      rp_sum += node_spec_[node->child_at(i)].var_reach_prob->solution_value();
    }
    for (int i = 0; i < actions.size(); ++i) {
      double prob;
      if (rp_sum) {
        prob = node_spec_[node->child_at(i)].var_reach_prob->solution_value() /
               rp_sum;
      } else {
        // If the infostate is unreachable, the strategy is not defined.
        // However some code in the library may require having the strategy,
        // so we just put an uniform strategy here.
        prob = 1. / actions.size();
      }
      state_policy.push_back({actions[i], prob});
    }
    policy.SetStatePolicy(node->infostate_string(), state_policy);
  }
  return policy;
}
References open_spiel::algorithms::InfostateTree::AllDecisionIds(), open_spiel::algorithms::InfostateNode::child_at(), open_spiel::algorithms::InfostateTree::decision_infostate(), i, open_spiel::algorithms::InfostateNode::infostate_string(), open_spiel::algorithms::InfostateNode::legal_actions(), node_spec_, open_spiel::algorithms::InfostateNode::num_children(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and trees_.
OptimalSfStrategy()
SfStrategy open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalSfStrategy (Player for_player)
Definition at line 218 of file sequence_form_lp.cc.
{
  SPIEL_CHECK_TRUE(for_player == 0 || for_player == 1);
  const InfostateTree* tree = trees_[for_player].get();
  SfStrategy strategy(tree);
  for (SequenceId id : tree->AllSequenceIds()) {
    const InfostateNode* node = tree->observation_infostate(id);
    strategy[id] = node_spec_[node].var_reach_prob->solution_value();
  }
  return strategy;
}
References open_spiel::algorithms::InfostateTree::AllSequenceIds(), node_spec_, open_spiel::algorithms::InfostateTree::observation_infostate(), SPIEL_CHECK_TRUE, and trees_.
PrintProblemSpecification()
void open_spiel::algorithms::ortools::SequenceFormLpSpecification::PrintProblemSpecification ()
Definition at line 246 of file sequence_form_lp.cc.
{
  const std::vector<opres::MPVariable*>& variables = solver_->variables();
  const std::vector<opres::MPConstraint*>& constraints = solver_->constraints();
  const opres::MPObjective& objective = solver_->Objective();
  std::cout << "Objective:" << std::endl;
  if (objective.maximization()) {
    std::cout << "max ";
  } else {
    std::cout << "min ";
  }
  bool first_obj = true;
  for (int i = 0; i < variables.size(); ++i) {
    const double coef = objective.GetCoefficient(variables[i]);
    if (coef) {
      if (!first_obj) std::cout << "+ ";
      std::cout << coef << "*x" << i << " ";
      first_obj = false;
    }
  }
  std::cout << std::endl;
  std::cout << "Constraints:" << std::endl;
  for (auto& ct : constraints) {
    std::cout << ct->lb() << " <= ";
    bool first_ct = true;
    for (int i = 0; i < variables.size(); ++i) {
      const double coef = ct->GetCoefficient(variables[i]);
      if (coef) {
        if (!first_ct) std::cout << "+ ";
        std::cout << coef << "*x" << i << " ";
        first_ct = false;
      }
    }
    std::cout << "<= " << ct->ub() << " (" << ct->name() << ")" << std::endl;
  }
  std::cout << "Variables:" << std::endl;
  for (int i = 0; i < variables.size(); i++) {
    const auto& var = variables[i];
    std::cout << var->lb() << " <= "
              << "x" << i << " <= " << var->ub() << " (" << var->name() << ")"
              << std::endl;
  }
}
References i, and solver_.
roots()
std::array< const InfostateNode *, 2 > open_spiel::algorithms::ortools::SequenceFormLpSpecification::roots () const inline
Definition at line 116 of file sequence_form_lp.h.
{
    return {trees_[0]->mutable_root(), trees_[1]->mutable_root()};
  }
References trees_.
Solve()
double open_spiel::algorithms::ortools::SequenceFormLpSpecification::Solve ()
Definition at line 171 of file sequence_form_lp.cc.
{
  opres::MPSolver::ResultStatus status = solver_->Solve();
  //  // Export the model if the result was not optimal.
  //  // You can then use external debugging tools (like cplex studio).
  //  if (status != opres::MPSolver::ResultStatus::OPTIMAL) {
  //    std::string out;
  //    // Pick the format.
  //    solver_->ExportModelAsMpsFormat(false, false, &out);
  //    solver_->ExportModelAsLpFormat(false, &out);
  //    std::cout << out << "\n";
  //  }
  SPIEL_CHECK_EQ(status, opres::MPSolver::ResultStatus::OPTIMAL);
  return -solver_->Objective().Value();
}
References solver_, and SPIEL_CHECK_EQ.
solver()
operations_research::MPSolver * open_spiel::algorithms::ortools::SequenceFormLpSpecification::solver () inline
Definition at line 122 of file sequence_form_lp.h.
{ return solver_.get(); }
References solver_.
SpecifyCfValuesConstraints()
void open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyCfValuesConstraints (InfostateNode * opponent_node) protected
Definition at line 85 of file sequence_form_lp.cc.
{
  node_spec_[opponent_node].var_cf_value = solver_->MakeNumVar(
      /*lb=*/-opres::MPSolver::infinity(),
      /*ub=*/opres::MPSolver::infinity(), "");
  if (opponent_node->type() == kDecisionInfostateNode) {
    for (InfostateNode* opponent_child : opponent_node->child_iterator()) {
      SpecifyCfValuesConstraints(opponent_child);
      opres::MPConstraint* ct = node_spec_[opponent_child].ct_parent_cf_value =
          solver_->MakeRowConstraint();
      ct->SetUB(0.);
      ct->SetCoefficient(node_spec_[opponent_node].var_cf_value, -1);
      ct->SetCoefficient(node_spec_[opponent_child].var_cf_value, 1);
    }
    return;
  }
  opres::MPConstraint* ct = node_spec_[opponent_node].ct_child_cf_value =
      solver_->MakeRowConstraint();
  ct->SetUB(0.);
  ct->SetCoefficient(node_spec_[opponent_node].var_cf_value, -1);
  if (opponent_node->type() == kTerminalInfostateNode) {
    const std::map<const InfostateNode*, const InfostateNode*>& terminal_map =
        terminal_bijection_.association(opponent_node->tree().acting_player());
    const InfostateNode* player_node = terminal_map.at(opponent_node);
    const double value = opponent_node->terminal_utility() *
                         opponent_node->terminal_chance_reach_prob();
    // Terminal value constraint comes from the opponent.
    ct->SetCoefficient(node_spec_[player_node].var_reach_prob, value);
    return;
  }
  if (opponent_node->type() == kObservationInfostateNode) {
    // Value constraint: sum of children = parent
    ct->SetLB(0.);
    for (InfostateNode* opponent_child : opponent_node->child_iterator()) {
      SpecifyCfValuesConstraints(opponent_child);
      ct->SetCoefficient(node_spec_[opponent_child].var_cf_value, 1);
    }
    return;
  }
  SpielFatalError("Exhausted pattern match!");
}
References open_spiel::algorithms::InfostateTree::acting_player(), open_spiel::algorithms::InfostateNode::child_iterator(), open_spiel::algorithms::kDecisionInfostateNode, open_spiel::algorithms::kObservationInfostateNode, open_spiel::algorithms::kTerminalInfostateNode, node_spec_, solver_, SpecifyCfValuesConstraints(), open_spiel::SpielFatalError(), terminal_bijection_, open_spiel::algorithms::InfostateNode::terminal_chance_reach_prob(), open_spiel::algorithms::InfostateNode::terminal_utility(), open_spiel::algorithms::InfostateNode::tree(), and open_spiel::algorithms::InfostateNode::type().
Referenced by SpecifyCfValuesConstraints(), and SpecifyLinearProgram().
SpecifyLinearProgram()
void open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyLinearProgram (Player pl)
Definition at line 158 of file sequence_form_lp.cc.
{
  SPIEL_CHECK_TRUE(pl == 0 || pl == 1);
  ClearSpecification();
  SpecifyReachProbsConstraints(
      /*player_node=*/trees_[pl]->mutable_root());
  SpecifyRootConstraints(
      /*player_root_node=*/trees_[pl]->mutable_root());
  SpecifyCfValuesConstraints(
      /*opponent_node=*/trees_[1 - pl]->mutable_root());
  SpecifyObjective(
      /*opponent_root_node=*/trees_[1 - pl]->mutable_root());
}
References ClearSpecification(), SpecifyCfValuesConstraints(), SpecifyObjective(), SpecifyReachProbsConstraints(), SpecifyRootConstraints(), SPIEL_CHECK_TRUE, and trees_.
SpecifyObjective()
void open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyObjective (const InfostateNode * opponent_root_node) protected
Definition at line 139 of file sequence_form_lp.cc.
{
  opres::MPObjective* const objective = solver_->MutableObjective();
  objective->SetCoefficient(node_spec_[opponent_root_node].var_cf_value, 1);
  objective->SetMinimization();
}
References node_spec_, and solver_.
Referenced by SpecifyLinearProgram().
SpecifyReachProbsConstraints()
void open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyReachProbsConstraints (InfostateNode * player_node) protected
Definition at line 52 of file sequence_form_lp.cc.
{
  node_spec_[player_node].var_reach_prob = solver_->MakeNumVar(
      /*lb=*/0.0, /*ub=*/1., "");
  if (player_node->type() == kTerminalInfostateNode) return;  // Nothing to do.
  if (player_node->type() == kObservationInfostateNode) {
    for (InfostateNode* player_child : player_node->child_iterator()) {
      SpecifyReachProbsConstraints(player_child);
      // Equality constraint: parent = child
      opres::MPConstraint* ct = node_spec_[player_child].ct_parent_reach_prob =
          solver_->MakeRowConstraint(/*lb=*/0, /*ub=*/0, "");
      ct->SetCoefficient(node_spec_[player_node].var_reach_prob, -1);
      ct->SetCoefficient(node_spec_[player_child].var_reach_prob, 1);
    }
    return;
  }
  if (player_node->type() == kDecisionInfostateNode) {
    // Equality constraint: parent = sum of children
    opres::MPConstraint* ct = node_spec_[player_node].ct_child_reach_prob =
        solver_->MakeRowConstraint(/*lb=*/0, /*ub=*/0, "");
    ct->SetCoefficient(node_spec_[player_node].var_reach_prob, -1);
    for (InfostateNode* player_child : player_node->child_iterator()) {
      SpecifyReachProbsConstraints(player_child);
      ct->SetCoefficient(node_spec_[player_child].var_reach_prob, 1);
    }
    return;
  }
  SpielFatalError("Exhausted pattern match!");
}
References open_spiel::algorithms::InfostateNode::child_iterator(), open_spiel::algorithms::kDecisionInfostateNode, open_spiel::algorithms::kObservationInfostateNode, open_spiel::algorithms::kTerminalInfostateNode, node_spec_, solver_, SpecifyReachProbsConstraints(), open_spiel::SpielFatalError(), and open_spiel::algorithms::InfostateNode::type().
Referenced by SpecifyLinearProgram(), and SpecifyReachProbsConstraints().
SpecifyRootConstraints()
void open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyRootConstraints (const InfostateNode * player_root_node) protected
Definition at line 131 of file sequence_form_lp.cc.
{
  SPIEL_CHECK_TRUE(player_root_node->is_root_node());
  NodeSpecification& root_data = node_spec_.at(player_root_node);
  root_data.var_reach_prob->SetLB(1.);
  root_data.var_reach_prob->SetUB(1.);
}
References open_spiel::algorithms::InfostateNode::is_root_node(), node_spec_, SPIEL_CHECK_TRUE, and open_spiel::algorithms::ortools::NodeSpecification::var_reach_prob.
Referenced by SpecifyLinearProgram().
terminal_bijection()
const BijectiveContainer< const InfostateNode * > & open_spiel::algorithms::ortools::SequenceFormLpSpecification::terminal_bijection () const inline
Definition at line 124 of file sequence_form_lp.h.
{
    return terminal_bijection_;
  }
References terminal_bijection_.
trees()
const std::vector< std::shared_ptr< InfostateTree > > & open_spiel::algorithms::ortools::SequenceFormLpSpecification::trees () const inline
Definition at line 113 of file sequence_form_lp.h.
{
    return trees_;
  }
References trees_.
Member Data Documentation
node_spec_
std::unordered_map<const InfostateNode*, NodeSpecification> open_spiel::algorithms::ortools::SequenceFormLpSpecification::node_spec_ protected
Definition at line 132 of file sequence_form_lp.h.
Referenced by ClearSpecification(), node_spec(), OptimalPolicy(), OptimalSfStrategy(), SpecifyCfValuesConstraints(), SpecifyObjective(), SpecifyReachProbsConstraints(), and SpecifyRootConstraints().
solver_
std::unique_ptr<operations_research::MPSolver> open_spiel::algorithms::ortools::SequenceFormLpSpecification::solver_ protected
Definition at line 131 of file sequence_form_lp.h.
Referenced by ClearSpecification(), PrintProblemSpecification(), SequenceFormLpSpecification(), Solve(), solver(), SpecifyCfValuesConstraints(), SpecifyObjective(), and SpecifyReachProbsConstraints().
terminal_bijection_
const BijectiveContainer<const InfostateNode*> open_spiel::algorithms::ortools::SequenceFormLpSpecification::terminal_bijection_ protected
Definition at line 130 of file sequence_form_lp.h.
Referenced by SpecifyCfValuesConstraints(), and terminal_bijection().
trees_
const std::vector<std::shared_ptr<InfostateTree> > open_spiel::algorithms::ortools::SequenceFormLpSpecification::trees_ protected
Definition at line 129 of file sequence_form_lp.h.
Referenced by OptimalPolicy(), OptimalSfStrategy(), roots(), SequenceFormLpSpecification(), SpecifyLinearProgram(), and trees().
The documentation for this class was generated from the following files:
open_spiel/algorithms/ortools/sequence_form_lp.h
open_spiel/algorithms/ortools/sequence_form_lp.cc