open spiel: open_spiel::goofspiel::GoofspielState Class Reference
open_spiel::goofspiel::GoofspielState Class Reference
#include <goofspiel.h>
Public Member Functions
GoofspielState (std::shared_ptr< const Game > game, int num_cards, int num_turns, PointsOrder points_order, bool impinfo, bool egocentric, ReturnsType returns_type)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::vector< Action > LegalActions (Player player) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &actions) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Friends
class GoofspielObserver
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 90 of file goofspiel.h.
Constructor & Destructor Documentation
GoofspielState()
open_spiel::goofspiel::GoofspielState::GoofspielState (std::shared_ptr< const Game > game, int num_cards, int num_turns, PointsOrder points_order, bool impinfo, bool egocentric, ReturnsType returns_type) explicit
Definition at line 365 of file goofspiel.cc.
    : SimMoveState(game),
      num_cards_(num_cards),
      num_turns_(num_turns),
      points_order_(points_order),
      returns_type_(returns_type),
      impinfo_(impinfo),
      egocentric_(egocentric),
      current_player_(kInvalidPlayer),
      winners_({}),
      current_turn_(0),
      point_card_(-1),
      point_card_sequence_({}),
      win_sequence_({}),
      actions_history_({}) {
  SPIEL_CHECK_LE(num_turns_, num_cards_);
  // Points and point-card deck.
  points_.resize(num_players_);
  std::fill(points_.begin(), points_.end(), 0);
  // Player hands.
  player_hands_.clear();
  for (auto p = Player{0}; p < num_players_; ++p) {
    std::vector<bool> hand(num_cards_, true);
    player_hands_.push_back(hand);
  }
  // Set the points card index.
  if (points_order_ == PointsOrder::kRandom) {
    point_card_ = -1;
    current_player_ = kChancePlayerId;
  } else if (points_order_ == PointsOrder::kAscending) {
    DealPointCard(0);
    current_player_ = kSimultaneousPlayerId;
  } else if (points_order_ == PointsOrder::kDescending) {
    DealPointCard(num_cards - 1);
    current_player_ = kSimultaneousPlayerId;
  }
}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::goofspiel::GoofspielState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 551 of file goofspiel.cc.
{
  if (player == kSimultaneousPlayerId)
    return FlatJointActionToString(action_id);
  SPIEL_CHECK_GE(action_id, 0);
  SPIEL_CHECK_LT(action_id, num_cards_);
  if (player == kChancePlayerId) {
    return absl::StrCat("Deal ", action_id + 1);
  } else {
    return absl::StrCat("[P", player, "]Bid: ", (action_id + 1));
  }
}
References open_spiel::SimMoveState::FlatJointActionToString(), open_spiel::kChancePlayerId, open_spiel::kSimultaneousPlayerId, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::goofspiel::GoofspielState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 520 of file goofspiel.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  std::set<int> played(point_card_sequence_.begin(),
                       point_card_sequence_.end());
  std::vector<std::pair<Action, double>> outcomes;
  const int n = num_cards_ - played.size();
  const double p = 1.0 / n;
  outcomes.reserve(n);
  for (int i = 0; i < num_cards_; ++i) {
    if (played.count(i) == 0) outcomes.emplace_back(i, p);
  }
  SPIEL_CHECK_EQ(outcomes.size(), n);
  return outcomes;
}
References i, open_spiel::State::IsChanceNode(), n, SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::goofspiel::GoofspielState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 681 of file goofspiel.cc.
{
  return std::unique_ptr<State>(new GoofspielState(*this));
}
References GoofspielState().
CurrentPlayer()
int open_spiel::goofspiel::GoofspielState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 409 of file goofspiel.cc.
{ return current_player_; }
Referenced by LegalActions().
DoApplyAction()
void open_spiel::goofspiel::GoofspielState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 418 of file goofspiel.cc.
{
  if (IsSimultaneousNode()) {
    ApplyFlatJointAction(action_id);
    return;
  }
  SPIEL_CHECK_TRUE(IsChanceNode());
  DealPointCard(action_id);
  current_player_ = kSimultaneousPlayerId;
}
References open_spiel::SimMoveState::ApplyFlatJointAction(), open_spiel::State::IsChanceNode(), open_spiel::State::IsSimultaneousNode(), open_spiel::kSimultaneousPlayerId, and SPIEL_CHECK_TRUE.
Referenced by DoApplyActions().
DoApplyActions()
void open_spiel::goofspiel::GoofspielState::DoApplyActions (const std::vector< Action > & actions) override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 428 of file goofspiel.cc.
{
  // Check the actions are valid.
  SPIEL_CHECK_EQ(actions.size(), num_players_);
  for (auto p = Player{0}; p < num_players_; ++p) {
    const int action = actions[p];
    SPIEL_CHECK_GE(action, 0);
    SPIEL_CHECK_LT(action, num_cards_);
    SPIEL_CHECK_TRUE(player_hands_[p][action]);
  }
  // Find the highest bid
  int max_bid = -1;
  int num_max_bids = 0;
  int max_bidder = -1;
  for (int p = 0; p < actions.size(); ++p) {
    if (actions[p] > max_bid) {
      max_bid = actions[p];
      num_max_bids = 1;
      max_bidder = p;
    } else if (actions[p] == max_bid) {
      num_max_bids++;
    }
  }
  if (num_max_bids == 1) {
    // Winner takes the point card.
    points_[max_bidder] += CurrentPointValue();
    win_sequence_.push_back(max_bidder);
  } else {
    // Tied among several players: discarded.
    win_sequence_.push_back(kInvalidPlayer);
  }
  // Add these actions to the history.
  actions_history_.push_back(actions);
  // Remove the cards from the player's hands.
  for (auto p = Player{0}; p < num_players_; ++p) {
    player_hands_[p][actions[p]] = false;
  }
  // Next player's turn.
  current_turn_++;
  // Deal the next point card.
  if (current_turn_ < num_turns_) {
    if (points_order_ == PointsOrder::kRandom) {
      current_player_ = kChancePlayerId;
      point_card_ = -1;
    } else if (points_order_ == PointsOrder::kAscending) {
      if (point_card_ < num_cards_ - 1) DealPointCard(point_card_ + 1);
    } else if (points_order_ == PointsOrder::kDescending) {
      if (point_card_ > 0) DealPointCard(point_card_ - 1);
    }
  }
  // No choice at the last turn, so we can play it now
  // We use DoApplyAction(s) not to modify the history, as these actions are
  // not available in the tree.
  if (current_turn_ == num_cards_ - 1) {
    // There might be a chance event
    if (IsChanceNode()) {
      auto legal_actions = LegalChanceOutcomes();
      SPIEL_CHECK_EQ(legal_actions.size(), 1);
      DoApplyAction(legal_actions.front());
    }
    // Each player plays their last card
    std::vector<Action> actions(num_players_);
    for (auto p = Player{0}; p < num_players_; ++p) {
      auto legal_actions = LegalActions(p);
      SPIEL_CHECK_EQ(legal_actions.size(), 1);
      actions[p] = legal_actions[0];
    }
    DoApplyActions(actions);
  } else if (current_turn_ == num_turns_) {
    // Game over - determine winner.
    int max_points = -1;
    for (auto p = Player{0}; p < num_players_; ++p) {
      if (points_[p] > max_points) {
        winners_.clear();
        max_points = points_[p];
        winners_.insert(p);
      } else if (points_[p] == max_points) {
        winners_.insert(p);
      }
    }
    current_player_ = kTerminalPlayerId;
  }
}
References action, DoApplyAction(), DoApplyActions(), open_spiel::State::IsChanceNode(), open_spiel::goofspiel::kAscending, open_spiel::kChancePlayerId, open_spiel::goofspiel::kDescending, open_spiel::kInvalidPlayer, open_spiel::goofspiel::kRandom, open_spiel::kTerminalPlayerId, open_spiel::SimMoveState::LegalActions(), open_spiel::State::LegalChanceOutcomes(), open_spiel::State::num_players_, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and SPIEL_CHECK_TRUE.
Referenced by DoApplyActions().
InformationStateString()
std::string open_spiel::goofspiel::GoofspielState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 648 of file goofspiel.cc.
{
  const GoofspielGame& game =
      open_spiel::down_cast<const GoofspielGame&>(*game_);
  return game.info_state_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
InformationStateTensor()
void open_spiel::goofspiel::GoofspielState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 665 of file goofspiel.cc.
{
  ContiguousAllocator allocator(values);
  const GoofspielGame& game =
      open_spiel::down_cast<const GoofspielGame&>(*game_);
  game.info_state_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
IsTerminal()
bool open_spiel::goofspiel::GoofspielState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 604 of file goofspiel.cc.
{
  return current_player_ == kTerminalPlayerId;
}
References open_spiel::kTerminalPlayerId.
Referenced by Returns().
LegalActions()
std::vector< Action > open_spiel::goofspiel::GoofspielState::LegalActions (Player player) const override virtual
Implements open_spiel::SimMoveState.
Definition at line 535 of file goofspiel.cc.
{
  if (CurrentPlayer() == kTerminalPlayerId) return std::vector<Action>();
  if (player == kSimultaneousPlayerId) return LegalFlatJointActions();
  if (player == kChancePlayerId) return LegalChanceOutcomes();
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::vector<Action> movelist;
  for (int bid = 0; bid < player_hands_[player].size(); ++bid) {
    if (player_hands_[player][bid]) {
      movelist.push_back(bid);
    }
  }
  return movelist;
}
References CurrentPlayer(), open_spiel::kChancePlayerId, open_spiel::kSimultaneousPlayerId, open_spiel::kTerminalPlayerId, open_spiel::State::LegalChanceOutcomes(), open_spiel::SimMoveState::LegalFlatJointActions(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
ObservationString()
std::string open_spiel::goofspiel::GoofspielState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 654 of file goofspiel.cc.
{
  const GoofspielGame& game =
      open_spiel::down_cast<const GoofspielGame&>(*game_);
  return game.default_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
ObservationTensor()
void open_spiel::goofspiel::GoofspielState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 673 of file goofspiel.cc.
{
  ContiguousAllocator allocator(values);
  const GoofspielGame& game =
      open_spiel::down_cast<const GoofspielGame&>(*game_);
  game.default_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
Returns()
std::vector< double > open_spiel::goofspiel::GoofspielState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 608 of file goofspiel.cc.
{
  if (!IsTerminal()) {
    return std::vector<double>(num_players_, 0.0);
  }
  if (returns_type_ == ReturnsType::kWinLoss) {
    if (winners_.size() == num_players_) {
      // All players have same number of points? This is a draw.
      return std::vector<double>(num_players_, 0.0);
    } else {
      int num_winners = winners_.size();
      int num_losers = num_players_ - num_winners;
      std::vector<double> returns(num_players_, (-1.0 / num_losers));
      for (const auto& winner : winners_) {
        returns[winner] = 1.0 / num_winners;
      }
      return returns;
    }
  } else if (returns_type_ == ReturnsType::kPointDifference) {
    std::vector<double> returns(num_players_, 0);
    double sum = 0;
    for (Player p = 0; p < num_players_; ++p) {
      returns[p] = points_[p];
      sum += points_[p];
    }
    for (Player p = 0; p < num_players_; ++p) {
      returns[p] -= sum / num_players_;
    }
    return returns;
  } else if (returns_type_ == ReturnsType::kTotalPoints) {
    std::vector<double> returns(num_players_, 0);
    for (Player p = 0; p < num_players_; ++p) {
      returns[p] = points_[p];
    }
    return returns;
  } else {
    SpielFatalError(absl::StrCat("Unrecognized returns type: ", returns_type_));
  }
}
References IsTerminal(), open_spiel::goofspiel::kPointDifference, open_spiel::goofspiel::kTotalPoints, open_spiel::goofspiel::kWinLoss, open_spiel::State::num_players_, open_spiel::SpielFatalError(), and absl::StrCat().
ToString()
std::string open_spiel::goofspiel::GoofspielState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 564 of file goofspiel.cc.
{
  std::string points_line = "Points: ";
  std::string result = "";
  for (auto p = Player{0}; p < num_players_; ++p) {
    absl::StrAppend(&points_line, points_[p]);
    absl::StrAppend(&points_line, " ");
    absl::StrAppend(&result, "P");
    absl::StrAppend(&result, p);
    absl::StrAppend(&result, " hand: ");
    for (int c = 0; c < num_cards_; ++c) {
      if (player_hands_[p][c]) {
        absl::StrAppend(&result, c + 1);
        absl::StrAppend(&result, " ");
      }
    }
    absl::StrAppend(&result, "\n");
  }
  // In imperfect information, the full state depends on both betting sequences
  if (impinfo_) {
    for (auto p = Player{0}; p < num_players_; ++p) {
      absl::StrAppend(&result, "P", p, " actions: ");
      for (int i = 0; i < actions_history_.size(); ++i) {
        absl::StrAppend(&result, actions_history_[i][p]);
        absl::StrAppend(&result, " ");
      }
      absl::StrAppend(&result, "\n");
    }
  }
  absl::StrAppend(&result, "Point card sequence: ");
  for (int i = 0; i < point_card_sequence_.size(); ++i) {
    absl::StrAppend(&result, 1 + point_card_sequence_[i], " ");
  }
  absl::StrAppend(&result, "\n");
  return result + points_line + "\n";
}
References i, open_spiel::State::num_players_, and absl::StrAppend().
Friends And Related Symbol Documentation
GoofspielObserver
friend class GoofspielObserver friend
Definition at line 118 of file goofspiel.h.
The documentation for this class was generated from the following files:
open_spiel/games/goofspiel/goofspiel.h
open_spiel/games/goofspiel/goofspiel.cc