open spiel: open_spiel::PyState Class Reference
open_spiel::PyState Class Reference
#include <python_games.h>
Public Member Functions
PyState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::vector< Action > LegalActions (Player player) const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::vector< double > Rewards () const override
std::unique_ptr< State > Clone () const override
std::vector< std::string > DistributionSupport () override
void UpdateDistribution (const std::vector< double > &distribution) override
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &actions) override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
ActionsAndProbs ChanceOutcomes () const override
std::string Serialize () const override
int MeanFieldPopulation () const override
void Deserialize (const std::string &str)
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 69 of file python_games.h.
Constructor & Destructor Documentation
PyState()
open_spiel::PyState::PyState (std::shared_ptr< const Game > game)
Definition at line 68 of file python_games.cc.
: State(game) {}
Member Function Documentation
ActionToString()
std::string open_spiel::PyState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 92 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(std::string, State, "_action_to_string",
                              ActionToString, player, action_id);
}
References ActionToString(), and player.
Referenced by ActionToString().
ChanceOutcomes()
ActionsAndProbs open_spiel::PyState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 123 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(ActionsAndProbs, State, "chance_outcomes",
                              ChanceOutcomes);
}
References ChanceOutcomes().
Referenced by ChanceOutcomes().
Clone()
std::unique_ptr< State > open_spiel::PyState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 128 of file python_games.cc.
{
  // Create a new State of the right type.
  auto rv = game_->NewInitialState();
  // Copy the Python-side properties of the state.
  py::function deepcopy = py::module::import("copy").attr("deepcopy");
  py::object py_state = py::cast(*rv);
  for (auto [k, v] : PyDict(*this)) {
    py_state.attr(k) = deepcopy(v);
  }
  // Copy the C++-side properties of the state (all on the parent class).
  // Since we started with a valid initial state, we only need to copy
  // properties that change during the life of the state - hence num_players,
  // num_distinct_actions are omitted.
  PyState* state = open_spiel::down_cast<PyState*>(rv.get());
  state->history_ = history_;
  state->move_number_ = move_number_;
  return rv;
}
References open_spiel::down_cast(), open_spiel::State::game_, open_spiel::State::history_, open_spiel::State::move_number_, open_spiel::PyDict(), and state.
CurrentPlayer()
Player open_spiel::PyState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 70 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(Player, State, "current_player", CurrentPlayer);
}
References CurrentPlayer().
Referenced by CurrentPlayer(), LegalActions(), and LegalActions().
Deserialize()
void open_spiel::PyState::Deserialize (const std::string & str)
Definition at line 330 of file python_games.cc.
{
  std::vector<absl::string_view> pieces =
      absl::StrSplit(str, absl::MaxSplits('\n', 2));
  SPIEL_CHECK_EQ(pieces.size(), 3);
  SPIEL_CHECK_EQ(pieces[0].substr(0, kTagHistory.size()), kTagHistory);
  auto history_str = pieces[0].substr(kTagHistory.size());
  if (!history_str.empty()) {
    for (auto& h : absl::StrSplit(history_str, ',')) {
      std::vector<absl::string_view> p = absl::StrSplit(h, ':');
      SPIEL_CHECK_EQ(p.size(), 2);
      int player, action;
      SPIEL_CHECK_TRUE(absl::SimpleAtoi(p[0], &player));
      SPIEL_CHECK_TRUE(absl::SimpleAtoi(p[1], &action));
      history_.push_back({player, action});
    }
  }
  SPIEL_CHECK_EQ(pieces[1].substr(0, kTagMoveNumber.size()), kTagMoveNumber);
  SPIEL_CHECK_TRUE(
      absl::SimpleAtoi(pieces[1].substr(kTagMoveNumber.size()), &move_number_));
  SPIEL_CHECK_EQ(pieces[2].substr(0, kTagDict.size()), kTagDict);
  py::object py_state = py::cast(*this);
  for (const auto& [k, v] : decode_dict(pieces[2].substr(kTagDict.size()))) {
    py_state.attr(k) = v;
  }
}
References action, open_spiel::decode_dict(), open_spiel::State::history_, open_spiel::kTagDict, open_spiel::kTagHistory, open_spiel::kTagMoveNumber, absl::MaxSplits(), open_spiel::State::move_number_, player, absl::SimpleAtoi(), absl::string_view::size(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and absl::StrSplit().
DistributionSupport()
std::vector< std::string > open_spiel::PyState::DistributionSupport () override virtual
Reimplemented from open_spiel::State.
Definition at line 150 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(std::vector<std::string>, State,
                              "distribution_support", DistributionSupport);
}
References DistributionSupport().
Referenced by DistributionSupport().
DoApplyAction()
void open_spiel::PyState::DoApplyAction (Action action_id) override virtual
Reimplemented from open_spiel::State.
Definition at line 113 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(void, State, "_apply_action", DoApplyAction,
                              action_id);
}
References DoApplyAction().
Referenced by DoApplyAction().
DoApplyActions()
void open_spiel::PyState::DoApplyActions (const std::vector< Action > & actions) override virtual
Reimplemented from open_spiel::State.
Definition at line 118 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(void, State, "_apply_actions", DoApplyActions,
                              actions);
}
References DoApplyActions().
Referenced by DoApplyActions().
InformationStateString()
std::string open_spiel::PyState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 232 of file python_games.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, NumPlayers());
  const PyGame& game = open_spiel::down_cast<const PyGame&>(*game_);
  return game.info_state_observer().StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, open_spiel::State::NumPlayers(), player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
InformationStateTensor()
void open_spiel::PyState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 246 of file python_games.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, NumPlayers());
  ContiguousAllocator allocator(values);
  const PyGame& game = open_spiel::down_cast<const PyGame&>(*game_);
  game.info_state_observer().WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, open_spiel::State::NumPlayers(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::PyState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 101 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(bool, State, "is_terminal", IsTerminal);
}
References IsTerminal().
Referenced by IsTerminal(), and LegalActions().
LegalActions() [1/2]
std::vector< Action > open_spiel::PyState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 74 of file python_games.cc.
{
  return LegalActions(CurrentPlayer());
}
References CurrentPlayer(), and LegalActions().
Referenced by LegalActions(), and LegalActions().
LegalActions() [2/2]
std::vector< Action > open_spiel::PyState::LegalActions (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 78 of file python_games.cc.
{
  if (IsTerminal()) return {};
  if (IsChanceNode()) return LegalChanceOutcomes();
  if ((player == CurrentPlayer()) || (player >= 0 && IsSimultaneousNode())) {
    PYBIND11_OVERLOAD_PURE_NAME(std::vector<Action>, State, "_legal_actions",
                                LegalActions, player);
  } else if (player < 0) {
    SpielFatalError(
        absl::StrCat("Called LegalActions for pseudo-player ", player));
  } else {
    return {};
  }
}
References CurrentPlayer(), open_spiel::State::IsChanceNode(), open_spiel::State::IsSimultaneousNode(), IsTerminal(), LegalActions(), open_spiel::State::LegalChanceOutcomes(), player, open_spiel::SpielFatalError(), and absl::StrCat().
MeanFieldPopulation()
int open_spiel::PyState::MeanFieldPopulation () const override virtual
Reimplemented from open_spiel::State.
Definition at line 372 of file python_games.cc.
{
  // Use a Python implementation if available, fall back to the C++
  // implementation if not.
  PYBIND11_OVERRIDE_NAME(int, State, "mean_field_population",
                              MeanFieldPopulation, /* no arguments */);
}
References MeanFieldPopulation().
Referenced by MeanFieldPopulation().
ObservationString()
std::string open_spiel::PyState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 239 of file python_games.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, NumPlayers());
  const PyGame& game = open_spiel::down_cast<const PyGame&>(*game_);
  return game.default_observer().StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, open_spiel::State::NumPlayers(), player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
ObservationTensor()
void open_spiel::PyState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 280 of file python_games.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, NumPlayers());
  ContiguousAllocator allocator(values);
  const PyGame& game = open_spiel::down_cast<const PyGame&>(*game_);
  game.default_observer().WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, open_spiel::State::NumPlayers(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::PyState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 105 of file python_games.cc.
{
  PYBIND11_OVERRIDE_PURE_NAME(std::vector<double>, State, "returns", Returns);
}
References Returns().
Referenced by Returns().
Rewards()
std::vector< double > open_spiel::PyState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 109 of file python_games.cc.
{
  PYBIND11_OVERRIDE_NAME(std::vector<double>, State, "rewards", Rewards);
}
References Rewards().
Referenced by Rewards().
Serialize()
std::string open_spiel::PyState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 359 of file python_games.cc.
{
  return absl::StrCat(
      // C++ Attributes
      kTagHistory,
      absl::StrJoin(history_, ",",
                    [](std::string* out, const PlayerAction& pa) {
                      absl::StrAppend(out, pa.player, ":", pa.action);
                    }),
      "\n", kTagMoveNumber, move_number_, "\n",
      // Python attributes
      kTagDict, encode_dict(PyDict(*this)));
}
References open_spiel::State::PlayerAction::action, open_spiel::encode_dict(), open_spiel::State::history_, open_spiel::kTagDict, open_spiel::kTagHistory, open_spiel::kTagMoveNumber, open_spiel::State::move_number_, out, open_spiel::State::PlayerAction::player, open_spiel::PyDict(), absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
ToString()
std::string open_spiel::PyState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 97 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(std::string, State, "__str__", ToString);
}
References ToString().
Referenced by ToString().
UpdateDistribution()
void open_spiel::PyState::UpdateDistribution (const std::vector< double > & distribution) override virtual
Reimplemented from open_spiel::State.
Definition at line 154 of file python_games.cc.
{
  PYBIND11_OVERLOAD_PURE_NAME(void, State, "update_distribution",
                              UpdateDistribution, distribution);
}
References UpdateDistribution().
Referenced by UpdateDistribution().
The documentation for this class was generated from the following files:
open_spiel/python/pybind11/python_games.h
open_spiel/python/pybind11/python_games.cc