open spiel: open_spiel::json::Value Class Reference
open_spiel::json::Value Class Reference
#include <json.h>
Public Member Functions
Value (int v)
Value (const char *v)
bool IsNull () const
bool IsBool () const
bool IsTrue () const
bool IsFalse () const
bool IsInt () const
bool IsDouble () const
bool IsNumber () const
bool IsString () const
bool IsArray () const
bool IsObject () const
template<class T >
T get_val () const
template<class T >
T & get_ref ()
template<class T >
const T & get_const_ref () const
bool GetBool () const
int64_t GetInt () const
int64_t & GetInt ()
double GetDouble () const
double & GetDouble ()
const std::string & GetString () const
std::string & GetString ()
const Array & GetArray () const
Array & GetArray ()
const Object & GetObject () const
Object & GetObject ()
bool operator== (const Null &o) const
bool operator== (const bool &o) const
bool operator== (const int &o) const
bool operator== (const int64_t &o) const
bool operator== (const double &o) const
bool operator== (const char *o) const
bool operator== (const std::string &o) const
bool operator== (const Array &o) const
bool operator== (const Object &o) const
template<typename T >
bool operator!= (const T &o) const
Detailed Description
Definition at line 42 of file json.h.
Constructor & Destructor Documentation
Value() [1/2]
open_spiel::json::Value::Value (int v) inline
Definition at line 47 of file json.h.
: Value(static_cast<int64_t>(v)) {}
Value() [2/2]
open_spiel::json::Value::Value (const char * v) inline
Definition at line 48 of file json.h.
: Value(std::string(v)) {}
Member Function Documentation
get_const_ref()
template<class T > const T & open_spiel::json::Value::get_const_ref () const inline
Definition at line 82 of file json.h.
{
    if (auto *val = std::get_if<T>(this)) {
      return *val;
    } else {
      SpielFatalError(absl::StrCat(
          "Value does not contain the specified type: ", typeid(T).name()));
    }
  }
References name, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by GetArray(), GetObject(), and GetString().
get_ref()
template<class T > T & open_spiel::json::Value::get_ref () inline
Definition at line 73 of file json.h.
{
    if (auto *val = std::get_if<T>(this)) {
      return *val;
    } else {
      SpielFatalError(absl::StrCat(
          "Value does not contain the specified type: ", typeid(T).name()));
    }
  }
References name, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by GetArray(), GetDouble(), GetInt(), GetObject(), and GetString().
get_val()
template<class T > T open_spiel::json::Value::get_val () const inline
Definition at line 64 of file json.h.
{
    if (auto *val = std::get_if<T>(this)) {
      return *val;
    } else {
      SpielFatalError(absl::StrCat(
          "Value does not contain the specified type: ", typeid(T).name()));
    }
  }
References name, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by GetBool(), GetDouble(), and GetInt().
GetArray() [1/2]
Array & open_spiel::json::Value::GetArray () inline
Definition at line 99 of file json.h.
{ return get_ref<Array>(); }
References get_ref().
GetArray() [2/2]
const Array & open_spiel::json::Value::GetArray () const inline
Definition at line 98 of file json.h.
{ return get_const_ref<Array>(); }
References get_const_ref().
Referenced by operator==().
GetBool()
bool open_spiel::json::Value::GetBool () const inline
Definition at line 91 of file json.h.
{ return get_val<bool>(); }
References get_val().
Referenced by IsFalse(), IsTrue(), and operator==().
GetDouble() [1/2]
double & open_spiel::json::Value::GetDouble () inline
Definition at line 95 of file json.h.
{ return get_ref<double>(); }
References get_ref().
GetDouble() [2/2]
double open_spiel::json::Value::GetDouble () const inline
Definition at line 94 of file json.h.
{ return get_val<double>(); }
References get_val().
Referenced by operator==().
GetInt() [1/2]
int64_t & open_spiel::json::Value::GetInt () inline
Definition at line 93 of file json.h.
{ return get_ref<int64_t>(); }
References get_ref().
GetInt() [2/2]
int64_t open_spiel::json::Value::GetInt () const inline
Definition at line 92 of file json.h.
{ return get_val<int64_t>(); }
References get_val().
Referenced by operator==(), and operator==().
GetObject() [1/2]
Object & open_spiel::json::Value::GetObject () inline
Definition at line 101 of file json.h.
{ return get_ref<Object>(); }
References get_ref().
GetObject() [2/2]
const Object & open_spiel::json::Value::GetObject () const inline
Definition at line 100 of file json.h.
{ return get_const_ref<Object>(); }
References get_const_ref().
Referenced by operator==().
GetString() [1/2]
std::string & open_spiel::json::Value::GetString () inline
Definition at line 97 of file json.h.
{ return get_ref<std::string>(); }
References get_ref().
GetString() [2/2]
const std::string & open_spiel::json::Value::GetString () const inline
Definition at line 96 of file json.h.
{ return get_const_ref<std::string>(); }
References get_const_ref().
Referenced by operator==(), and operator==().
IsArray()
bool open_spiel::json::Value::IsArray () const inline
Definition at line 58 of file json.h.
{ return std::holds_alternative<Array>(*this); }
Referenced by operator==().
IsBool()
bool open_spiel::json::Value::IsBool () const inline
Definition at line 51 of file json.h.
{ return std::holds_alternative<bool>(*this); }
Referenced by IsFalse(), IsTrue(), and operator==().
IsDouble()
bool open_spiel::json::Value::IsDouble () const inline
Definition at line 55 of file json.h.
{ return std::holds_alternative<double>(*this); }
Referenced by IsNumber(), and operator==().
IsFalse()
bool open_spiel::json::Value::IsFalse () const inline
Definition at line 53 of file json.h.
{ return IsBool() && !GetBool(); }
References GetBool(), and IsBool().
IsInt()
bool open_spiel::json::Value::IsInt () const inline
Definition at line 54 of file json.h.
{ return std::holds_alternative<int64_t>(*this); }
Referenced by IsNumber(), operator==(), and operator==().
IsNull()
bool open_spiel::json::Value::IsNull () const inline
Definition at line 50 of file json.h.
{ return std::holds_alternative<Null>(*this); }
Referenced by operator==().
IsNumber()
bool open_spiel::json::Value::IsNumber () const inline
Definition at line 56 of file json.h.
{ return IsInt() || IsDouble(); }
References IsDouble(), and IsInt().
IsObject()
bool open_spiel::json::Value::IsObject () const inline
Definition at line 59 of file json.h.
{ return std::holds_alternative<Object>(*this); }
Referenced by operator==().
IsString()
bool open_spiel::json::Value::IsString () const inline
Definition at line 57 of file json.h.
{ return std::holds_alternative<std::string>(*this); }
Referenced by operator==(), and operator==().
IsTrue()
bool open_spiel::json::Value::IsTrue () const inline
Definition at line 52 of file json.h.
{ return IsBool() && GetBool(); }
References GetBool(), and IsBool().
operator!=()
template<typename T > bool open_spiel::json::Value::operator!= (const T & o) const inline
Definition at line 121 of file json.h.
{ return !(*this == o); }
References o.
operator==() [1/9]
bool open_spiel::json::Value::operator== (const Array & o) const inline
Definition at line 116 of file json.h.
{ return IsArray() && GetArray() == o; }
References GetArray(), IsArray(), and o.
operator==() [2/9]
bool open_spiel::json::Value::operator== (const bool & o) const inline
Definition at line 104 of file json.h.
{ return IsBool() && GetBool() == o; }
References GetBool(), IsBool(), and o.
operator==() [3/9]
bool open_spiel::json::Value::operator== (const char * o) const inline
Definition at line 110 of file json.h.
{
    return IsString() && GetString() == o;
  }
References GetString(), IsString(), and o.
operator==() [4/9]
bool open_spiel::json::Value::operator== (const double & o) const inline
Definition at line 107 of file json.h.
{
    return IsDouble() && GetDouble() == o;
  }
References GetDouble(), IsDouble(), and o.
operator==() [5/9]
bool open_spiel::json::Value::operator== (const int & o) const inline
Definition at line 105 of file json.h.
{ return IsInt() && GetInt() == o; }
References GetInt(), IsInt(), and o.
operator==() [6/9]
bool open_spiel::json::Value::operator== (const int64_t & o) const inline
Definition at line 106 of file json.h.
{ return IsInt() && GetInt() == o; }
References GetInt(), IsInt(), and o.
operator==() [7/9]
bool open_spiel::json::Value::operator== (const Null & o) const inline
Definition at line 103 of file json.h.
{ return IsNull(); }
References IsNull().
operator==() [8/9]
bool open_spiel::json::Value::operator== (const Object & o) const inline
Definition at line 117 of file json.h.
{
    return IsObject() && GetObject() == o;
  }
References GetObject(), IsObject(), and o.
operator==() [9/9]
bool open_spiel::json::Value::operator== (const std::string & o) const inline
Definition at line 113 of file json.h.
{
    return IsString() && GetString() == o;
  }
References GetString(), IsString(), and o.
The documentation for this class was generated from the following file:
open_spiel/utils/json.h