open spiel: open_spiel::coop_to_1p::CoopTo1pState Class Reference
open_spiel::coop_to_1p::CoopTo1pState Class Reference
#include <coop_to_1p.h>
Public Member Functions
CoopTo1pState (std::shared_ptr< const Game > game, int num_privates, std::unique_ptr< State > state)
CoopTo1pState (const CoopTo1pState &other)
Player CurrentPlayer () const override
std::vector< Action > LegalActions (Player player) const override
std::vector< Action > LegalActions () const override
std::vector< int > LegalActionsMask () const
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
ActionsAndProbs ChanceOutcomes () const override
std::vector< Action > LegalChanceOutcomes () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 87 of file coop_to_1p.h.
Constructor & Destructor Documentation
CoopTo1pState() [1/2]
open_spiel::coop_to_1p::CoopTo1pState::CoopTo1pState (std::shared_ptr< const Game > game, int num_privates, std::unique_ptr< State > state) inline
Definition at line 89 of file coop_to_1p.h.
      : State(game),
        state_(std::move(state)),
        num_privates_(num_privates),
        prev_player_(kInvalidPlayer),
        prev_action_(kInvalidAction) {}
Referenced by Clone().
CoopTo1pState() [2/2]
open_spiel::coop_to_1p::CoopTo1pState::CoopTo1pState (const CoopTo1pState & other) inline
Definition at line 96 of file coop_to_1p.h.
      : State(other),
        state_(other.state_->Clone()),
        num_privates_(other.num_privates_),
        privates_(other.privates_),
        actual_private_(other.actual_private_),
        prev_player_(other.prev_player_),
        prev_action_(other.prev_action_) {}
Member Function Documentation
ActionToString()
std::string open_spiel::coop_to_1p::CoopTo1pState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 72 of file coop_to_1p.cc.
{
  if (player == kChancePlayerId) {
    return state_->ActionToString(player, action_id);
  } else {
    Player pl = state_->CurrentPlayer();
    return absl::StrCat(privates_[pl].names[privates_[pl].next_unassigned],
                        "->", state_->ActionToString(pl, action_id));
  }
}
References open_spiel::kChancePlayerId, player, and absl::StrCat().
ChanceOutcomes()
ActionsAndProbs open_spiel::coop_to_1p::CoopTo1pState::ChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 133 of file coop_to_1p.h.
{
    return state_->ChanceOutcomes();
  }
Clone()
std::unique_ptr< State > open_spiel::coop_to_1p::CoopTo1pState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 63 of file coop_to_1p.cc.
{
  return std::unique_ptr<State>(new CoopTo1pState(*this));
}
References CoopTo1pState().
CurrentPlayer()
Player open_spiel::coop_to_1p::CoopTo1pState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 104 of file coop_to_1p.h.
{
    Player underlying_player = state_->CurrentPlayer();
    return underlying_player < 0 ? underlying_player : kPlayerId;
  }
References open_spiel::coop_to_1p::kPlayerId.
Referenced by LegalActions().
DoApplyAction()
void open_spiel::coop_to_1p::CoopTo1pState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 192 of file coop_to_1p.cc.
{
  if (IsChanceNode()) {
    // Assume this is the dealing of a private state. Capture info on possible
    // privates here.
    privates_.push_back(PlayerPrivate(num_privates_));
    actual_private_.push_back(action_id);
    for (int i = 0; i < num_privates_; ++i) {
      privates_.back().names[i] = state_->ActionToString(kChancePlayerId, i);
    }
    state_->ApplyAction(action_id);
  } else {
    // Update the assignment and maybe act in the underlying game.
    Player player = state_->CurrentPlayer();
    privates_[player].Assign(action_id);
    if (privates_[player].AssignmentsComplete()) {
      Action underlying_action =
          privates_[player].assignments[actual_private_[player]];
      state_->ApplyAction(underlying_action);
      prev_player_ = player;
      prev_action_ = underlying_action;
      privates_[player].Reset(underlying_action);
    }
  }
}
References i, open_spiel::State::IsChanceNode(), open_spiel::kChancePlayerId, and player.
IsTerminal()
bool open_spiel::coop_to_1p::CoopTo1pState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 120 of file coop_to_1p.h.
{ return state_->IsTerminal(); }
LegalActions() [1/2]
std::vector< Action > open_spiel::coop_to_1p::CoopTo1pState::LegalActions () const inline override virtual
Implements open_spiel::State.
Definition at line 114 of file coop_to_1p.h.
{
    return state_->LegalActions(state_->CurrentPlayer());
  }
Referenced by LegalActions().
LegalActions() [2/2]
std::vector< Action > open_spiel::coop_to_1p::CoopTo1pState::LegalActions (Player player) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 108 of file coop_to_1p.h.
{
    if (player == CurrentPlayer())
      return LegalActions();
    else
      return {};
  }
References CurrentPlayer(), LegalActions(), and player.
LegalActionsMask()
std::vector< int > open_spiel::coop_to_1p::CoopTo1pState::LegalActionsMask () const inline
Definition at line 117 of file coop_to_1p.h.
{
    return state_->LegalActionsMask(state_->CurrentPlayer());
  }
LegalChanceOutcomes()
std::vector< Action > open_spiel::coop_to_1p::CoopTo1pState::LegalChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 136 of file coop_to_1p.h.
{
    return state_->LegalChanceOutcomes();
  }
ObservationString()
std::string open_spiel::coop_to_1p::CoopTo1pState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 142 of file coop_to_1p.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return absl::StrCat("Player ", player, "\n", PublicStateString(), "\n",
                      Assignments());
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
ObservationTensor()
void open_spiel::coop_to_1p::CoopTo1pState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 149 of file coop_to_1p.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  const int num_actions = state_->NumDistinctActions();
  const int num_players = state_->NumPlayers();
  SPIEL_CHECK_EQ(values.size(),
                 num_privates_ * (num_players + num_actions + 1) + num_actions);
  std::fill(values.begin(), values.end(), 0);
  if (IsChanceNode()) return;
  // Last action in the underlying game
  int base = 0;
  if (prev_action_ != kInvalidAction) values.at(prev_action_) = 1;
  base += num_actions;
  // Possible privates for every player (multi-hot)
  for (int p = 0; p < num_players; ++p) {
    const auto& pvt = privates_[p];
    for (int i = 0; i < num_privates_; ++i) {
      values.at(base + i) = (pvt.assignments[i] != PlayerPrivate::kImpossible);
    }
    base += num_privates_;
  }
  // For terminal states, we don't need anything else.
  if (state_->IsTerminal()) return;
  // Currently-assigned privates for every action (multi-hot)
  Player current_player = state_->CurrentPlayer();
  const auto& pvt = privates_[current_player];
  for (Action a = 0; a < num_actions; ++a) {
    for (int i = 0; i < num_privates_; ++i) {
      values.at(base + i) = (pvt.assignments[i] == a);
    }
    base += num_privates_;
  }
  // The private we are currently considering (one-hot)
  if (!pvt.AssignmentsComplete()) values.at(base + pvt.next_unassigned) = 1;
  base += num_privates_;
}
References a, i, open_spiel::State::IsChanceNode(), open_spiel::coop_to_1p::PlayerPrivate::kImpossible, open_spiel::kInvalidAction, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::coop_to_1p::CoopTo1pState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 124 of file coop_to_1p.h.
{
    return {state_->Returns().front()};
  }
Rewards()
std::vector< double > open_spiel::coop_to_1p::CoopTo1pState::Rewards () const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 121 of file coop_to_1p.h.
{
    return {state_->Rewards().front()};
  }
ToString()
std::string open_spiel::coop_to_1p::CoopTo1pState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 126 of file coop_to_1p.cc.
{
  return absl::StrCat(state_->ToString(), "\n", Assignments());
}
References absl::StrCat().
The documentation for this class was generated from the following files:
open_spiel/game_transforms/coop_to_1p.h
open_spiel/game_transforms/coop_to_1p.cc