open spiel: absl::cord_internal::CordRepBtreeReader Class Reference
absl::cord_internal::CordRepBtreeReader Class Reference
#include <cord_rep_btree_reader.h>
Public Types
using ReadResult = CordRepBtreeNavigator::ReadResult
using Position = CordRepBtreeNavigator::Position
Public Member Functions
operator bool () const
CordRepBtree * btree () const
CordRep * node () const
size_t length () const
size_t remaining () const
void Reset ()
absl::string_view Init (CordRepBtree *tree)
absl::string_view Next ()
absl::string_view Skip (size_t skip)
absl::string_view Read (size_t n, size_t chunk_size, CordRep *&tree)
absl::string_view Seek (size_t offset)
Detailed Description
Definition at line 79 of file cord_rep_btree_reader.h.
Member Typedef Documentation
Position
using absl::cord_internal::CordRepBtreeReader::Position = CordRepBtreeNavigator::Position
Definition at line 82 of file cord_rep_btree_reader.h.
ReadResult
using absl::cord_internal::CordRepBtreeReader::ReadResult = CordRepBtreeNavigator::ReadResult
Definition at line 81 of file cord_rep_btree_reader.h.
Member Function Documentation
btree()
CordRepBtree * absl::cord_internal::CordRepBtreeReader::btree () const inline
Definition at line 88 of file cord_rep_btree_reader.h.
{ return navigator_.btree(); }
References absl::cord_internal::CordRepBtreeNavigator::btree().
Referenced by length().
Init()
absl::string_view absl::cord_internal::CordRepBtreeReader::Init (CordRepBtree * tree) inline
Definition at line 167 of file cord_rep_btree_reader.h.
{
  assert(tree != nullptr);
  const CordRep* edge = navigator_.InitFirst(tree);
  remaining_ = tree->length - edge->length;
  return EdgeData(edge);
}
References absl::cord_internal::EdgeData(), absl::cord_internal::CordRepBtreeNavigator::InitFirst(), and absl::cord_internal::CordRep::length.
length()
size_t absl::cord_internal::CordRepBtreeReader::length () const inline
Definition at line 162 of file cord_rep_btree_reader.h.
{
  assert(btree() != nullptr);
  return btree()->length;
}
References btree(), and absl::cord_internal::CordRep::length.
Referenced by Seek().
Next()
absl::string_view absl::cord_internal::CordRepBtreeReader::Next () inline
Definition at line 174 of file cord_rep_btree_reader.h.
{
  if (remaining_ == 0) return {};
  const CordRep* edge = navigator_.Next();
  assert(edge != nullptr);
  remaining_ -= edge->length;
  return EdgeData(edge);
}
References absl::cord_internal::EdgeData(), absl::cord_internal::CordRep::length, and absl::cord_internal::CordRepBtreeNavigator::Next().
node()
CordRep * absl::cord_internal::CordRepBtreeReader::node () const inline
Definition at line 92 of file cord_rep_btree_reader.h.
{ return navigator_.Current(); }
References absl::cord_internal::CordRepBtreeNavigator::Current().
operator bool()
absl::cord_internal::CordRepBtreeReader::operator bool () const inline explicit
Definition at line 85 of file cord_rep_btree_reader.h.
{ return navigator_.btree() != nullptr; }
References absl::cord_internal::CordRepBtreeNavigator::btree().
Read()
absl::string_view absl::cord_internal::CordRepBtreeReader::Read (size_t n, size_t chunk_size, CordRep *& tree)
Definition at line 30 of file cord_rep_btree_reader.cc.
{
  assert(chunk_size <= navigator_.Current()->length);
  // If chunk_size is non-zero, we need to start inside last returned edge.
  // Else we start reading at the next data edge of the tree.
  CordRep* edge = chunk_size ? navigator_.Current() : navigator_.Next();
  const size_t offset = chunk_size ? edge->length - chunk_size : 0;
  // Read the sub tree and verify we got what we wanted.
  ReadResult result = navigator_.Read(offset, n);
  tree = result.tree;
  // If the data returned in `tree` was covered entirely by `chunk_size`, i.e.,
  // read from the 'previous' edge, we did not consume any additional data, and
  // can directly return the substring into the current data edge as the next
  // chunk. We can easily establish from the above code that `navigator_.Next()`
  // has not been called as that requires `chunk_size` to be zero.
  if (n < chunk_size) return EdgeData(edge).substr(result.n);
  // The amount of data taken from the last edge is `chunk_size` and `result.n`
  // contains the offset into the current edge trailing the read data (which can
  // be 0). As the call to `navigator_.Read()` could have consumed all remaining
  // data, calling `navigator_.Current()` is not safe before checking if we
  // already consumed all remaining data.
  const size_t consumed_by_read = n - chunk_size - result.n;
  if (consumed_by_read >= remaining_) {
    remaining_ = 0;
    return {};
  }
  // We did not read all data, return remaining data from current edge.
  edge = navigator_.Current();
  remaining_ -= consumed_by_read + edge->length;
  return EdgeData(edge).substr(result.n);
}
References absl::cord_internal::CordRepBtreeNavigator::Current(), absl::cord_internal::EdgeData(), absl::cord_internal::CordRep::length, absl::cord_internal::CordRepBtreeNavigator::ReadResult::n, absl::n, absl::cord_internal::CordRepBtreeNavigator::Next(), absl::cord_internal::CordRepBtreeNavigator::Read(), absl::string_view::substr(), and absl::cord_internal::CordRepBtreeNavigator::ReadResult::tree.
remaining()
size_t absl::cord_internal::CordRepBtreeReader::remaining () const inline
Definition at line 105 of file cord_rep_btree_reader.h.
{ return remaining_; }
Reset()
void absl::cord_internal::CordRepBtreeReader::Reset () inline
Definition at line 108 of file cord_rep_btree_reader.h.
{ navigator_.Reset(); }
References absl::cord_internal::CordRepBtreeNavigator::Reset().
Seek()
absl::string_view absl::cord_internal::CordRepBtreeReader::Seek (size_t offset) inline
Definition at line 197 of file cord_rep_btree_reader.h.
{
  const CordRepBtreeNavigator::Position pos = navigator_.Seek(offset);
  if (ABSL_PREDICT_FALSE(pos.edge == nullptr)) {
    remaining_ = 0;
    return {};
  }
  absl::string_view chunk = EdgeData(pos.edge).substr(pos.offset);
  remaining_ = length() - offset - chunk.length();
  return chunk;
}
References ABSL_PREDICT_FALSE, absl::cord_internal::EdgeData(), length(), absl::string_view::length(), absl::cord_internal::CordRepBtreeNavigator::Seek(), and absl::string_view::substr().
Skip()
absl::string_view absl::cord_internal::CordRepBtreeReader::Skip (size_t skip) inline
Definition at line 182 of file cord_rep_btree_reader.h.
{
  // As we are always positioned on the last 'consumed' edge, we
  // need to skip the current edge as well as `skip`.
  const size_t edge_length = navigator_.Current()->length;
  CordRepBtreeNavigator::Position pos = navigator_.Skip(skip + edge_length);
  if (ABSL_PREDICT_FALSE(pos.edge == nullptr)) {
    remaining_ = 0;
    return {};
  }
  // The combined length of all edges skipped before `pos.edge` is `skip -
  // pos.offset`, all of which are 'consumed', as well as the current edge.
  remaining_ -= skip - pos.offset + pos.edge->length;
  return EdgeData(pos.edge).substr(pos.offset);
}
References ABSL_PREDICT_FALSE, absl::cord_internal::CordRepBtreeNavigator::Current(), absl::cord_internal::EdgeData(), absl::cord_internal::CordRep::length, pos::length, absl::cord_internal::CordRepBtreeNavigator::Skip(), and absl::string_view::substr().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_btree_reader.h
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_btree_reader.cc