open spiel: open_spiel::liars_dice::LiarsDiceGame Class Reference
open_spiel::liars_dice::LiarsDiceGame Class Reference
#include <liars_dice.h>
Public Member Functions
LiarsDiceGame (const GameParameters &params, GameType game_type)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
absl::optional< double > UtilitySum () const override
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int max_dice_per_player () const
int total_num_dice () const
std::vector< int > num_dice () const
const int dice_sides () const
const BiddingRule bidding_rule () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 133 of file liars_dice.h.
Constructor & Destructor Documentation
LiarsDiceGame()
open_spiel::liars_dice::LiarsDiceGame::LiarsDiceGame (const GameParameters & params, GameType game_type) explicit
Definition at line 493 of file liars_dice.cc.
    : Game(game_type, params),
      num_players_(ParameterValue<int>("players")),
      dice_sides_(ParameterValue<int>("dice_sides")),
      bidding_rule_(ParseBiddingRule(
          ParameterValue<std::string>("bidding_rule"))) {
  SPIEL_CHECK_GE(num_players_, kGameType.min_num_players);
  SPIEL_CHECK_LE(num_players_, kGameType.max_num_players);
  SPIEL_CHECK_GE(dice_sides_, 1);
  int def_num_dice = ParameterValue<int>("numdice");
  // Compute the number of dice for each player based on parameters,
  // and set default outcomes of unknown face values (-1).
  total_num_dice_ = 0;
  num_dice_.resize(num_players_, 0);
  for (auto p = Player{0}; p < num_players_; p++) {
    std::string key = absl::StrCat("numdice", p);
    int my_num_dice = def_num_dice;
    if (IsParameterSpecified(game_parameters_, key)) {
      my_num_dice = ParameterValue<int>(key);
    }
    num_dice_[p] = my_num_dice;
    total_num_dice_ += my_num_dice;
  }
  // Compute max dice per player (used for observations.)
  max_dice_per_player_ = -1;
  for (int nd : num_dice_) {
    if (nd > max_dice_per_player_) {
      max_dice_per_player_ = nd;
    }
  }
}
References open_spiel::Game::game_parameters_, open_spiel::IsParameterSpecified(), key, open_spiel::kGameType, open_spiel::GameType::max_num_players, open_spiel::GameType::min_num_players, open_spiel::Game::ParameterValue(), SPIEL_CHECK_GE, SPIEL_CHECK_LE, and absl::StrCat().
Member Function Documentation
bidding_rule()
const BiddingRule open_spiel::liars_dice::LiarsDiceGame::bidding_rule () const inline
Definition at line 159 of file liars_dice.h.
{ return bidding_rule_; }
dice_sides()
const int open_spiel::liars_dice::LiarsDiceGame::dice_sides () const inline
Definition at line 158 of file liars_dice.h.
{ return dice_sides_; }
InformationStateTensorShape()
std::vector< int > open_spiel::liars_dice::LiarsDiceGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 552 of file liars_dice.cc.
{
  // One-hot encoding for the player number.
  // One-hot encoding for each die (max_dice_per_player_ * sides).
  // One slot(bit) for each legal bid.
  // One slot(bit) for calling liar. (Necessary because observations and
  // information states need to be defined at terminals)
  return {num_players_ + (max_dice_per_player_ * dice_sides_) +
          (total_num_dice_ * dice_sides_) + 1};
}
max_dice_per_player()
int open_spiel::liars_dice::LiarsDiceGame::max_dice_per_player () const inline
Definition at line 150 of file liars_dice.h.
{ return max_dice_per_player_; }
Referenced by open_spiel::liars_dice::ImperfectRecallLiarsDiceGame::NewInitialState().
MaxChanceNodesInHistory()
int open_spiel::liars_dice::LiarsDiceGame::MaxChanceNodesInHistory () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 550 of file liars_dice.cc.
{ return total_num_dice_; }
MaxChanceOutcomes()
int open_spiel::liars_dice::LiarsDiceGame::MaxChanceOutcomes () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 544 of file liars_dice.cc.
{ return dice_sides_; }
MaxGameLength()
int open_spiel::liars_dice::LiarsDiceGame::MaxGameLength () const override virtual
Implements open_spiel::Game.
Definition at line 546 of file liars_dice.cc.
{
  // A bet for each side and number of total dice, plus "liar" action.
  return total_num_dice_ * dice_sides_ + 1;
}
MaxUtility()
double open_spiel::liars_dice::LiarsDiceGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 141 of file liars_dice.h.
{ return 1; }
MinUtility()
double open_spiel::liars_dice::LiarsDiceGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 140 of file liars_dice.h.
{ return -1; }
NewInitialState()
std::unique_ptr< State > open_spiel::liars_dice::LiarsDiceGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 535 of file liars_dice.cc.
{
  std::unique_ptr<LiarsDiceState> state(
      new LiarsDiceState(shared_from_this(),
                         /*total_num_dice=*/total_num_dice_,
                         /*max_dice_per_player=*/max_dice_per_player_,
                         /*num_dice=*/num_dice_));
  return state;
}
References state.
num_dice()
std::vector< int > open_spiel::liars_dice::LiarsDiceGame::num_dice () const inline
Definition at line 156 of file liars_dice.h.
{ return num_dice_; }
Referenced by open_spiel::liars_dice::ImperfectRecallLiarsDiceGame::NewInitialState().
NumDistinctActions()
int open_spiel::liars_dice::LiarsDiceGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 531 of file liars_dice.cc.
{
  return total_num_dice_ * dice_sides_ + 1;
}
NumPlayers()
int open_spiel::liars_dice::LiarsDiceGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 139 of file liars_dice.h.
{ return num_players_; }
ObservationTensorShape()
std::vector< int > open_spiel::liars_dice::LiarsDiceGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 562 of file liars_dice.cc.
{
  // One-hot encoding for the player number.
  // One-hot encoding for each die (max_dice_per_player_ * sides).
  // One slot(bit) for the num_players_ last legal bid.
  // One slot(bit) for calling liar. (Necessary because observations and
  // information states need to be defined at terminals)
  return {num_players_ + (max_dice_per_player_ * dice_sides_) +
          (total_num_dice_ * dice_sides_) + 1};
}
total_num_dice()
int open_spiel::liars_dice::LiarsDiceGame::total_num_dice () const inline
Definition at line 153 of file liars_dice.h.
{ return total_num_dice_; }
Referenced by open_spiel::liars_dice::ImperfectRecallLiarsDiceGame::NewInitialState().
UtilitySum()
absl::optional< double > open_spiel::liars_dice::LiarsDiceGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 142 of file liars_dice.h.
{ return 0; }
The documentation for this class was generated from the following files:
open_spiel/games/liars_dice/liars_dice.h
open_spiel/games/liars_dice/liars_dice.cc