open spiel: open_spiel::Observation Class Reference
open_spiel::Observation Class Reference
#include <observer.h>
Public Member Functions
Observation (const Game &game, std::shared_ptr< Observer > observer)
void SetFrom (const State &state, int player)
const std::vector< SpanTensorInfo > & tensors_info () const
std::vector< SpanTensor > tensors ()
std::string StringFrom (const State &state, int player) const
std::string Compress () const
void Decompress (absl::string_view compressed)
bool HasString () const
bool HasTensor () const
absl::Span< float > Tensor ()
Detailed Description
Definition at line 350 of file observer.h.
Constructor & Destructor Documentation
Observation()
open_spiel::Observation::Observation (const Game & game, std::shared_ptr< Observer > observer)
Definition at line 215 of file observer.cc.
    : observer_(std::move(observer)) {
  // Get an observation of the initial state to set up.
  if (HasTensor()) {
    auto state = game.NewInitialState();
    TrackingVectorAllocator allocator;
    observer_->WriteTensor(*state, /*player=*/0, &allocator);
    buffer_ = allocator.data();
    tensors_info_ = allocator.tensors_info();
  }
}
References open_spiel::TrackingVectorAllocator::data(), HasTensor(), state, and open_spiel::TrackingVectorAllocator::tensors_info().
Member Function Documentation
Compress()
std::string open_spiel::Observation::Compress () const
Definition at line 304 of file observer.cc.
{
  const bool data_is_binary =
      absl::c_all_of(buffer_, [](float x) { return x == 0 || x == 1; });
  return data_is_binary ? BinaryCompress::Compress(buffer_)
                        : NoCompress::Compress(buffer_);
}
References absl::c_all_of(), open_spiel::BinaryCompress::Compress(), open_spiel::NoCompress::Compress(), and x.
Decompress()
void open_spiel::Observation::Decompress (absl::string_view compressed)
Definition at line 311 of file observer.cc.
{
  SPIEL_CHECK_GT(compressed.size(), 0);
  switch (compressed[0]) {
    case kCompressionBinary:
      return BinaryCompress::Decompress(compressed, absl::MakeSpan(buffer_));
    case kCompressionNone:
      return NoCompress::Decompress(compressed, absl::MakeSpan(buffer_));
    default:
      SpielFatalError(absl::StrCat("Unrecognized compression scheme in '",
                                   compressed, "'"));
  }
}
References open_spiel::BinaryCompress::Decompress(), open_spiel::NoCompress::Decompress(), open_spiel::kCompressionBinary, open_spiel::kCompressionNone, absl::MakeSpan(), absl::string_view::size(), SPIEL_CHECK_GT, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::init_pyspiel_observer().
HasString()
bool open_spiel::Observation::HasString () const inline
Definition at line 393 of file observer.h.
{ return observer_->HasString(); }
Referenced by open_spiel::init_pyspiel_observer().
HasTensor()
bool open_spiel::Observation::HasTensor () const inline
Definition at line 394 of file observer.h.
{ return observer_->HasTensor(); }
Referenced by open_spiel::init_pyspiel_observer(), and Observation().
SetFrom()
void open_spiel::Observation::SetFrom (const State & state, int player)
Definition at line 227 of file observer.cc.
{
  ContiguousAllocator allocator(absl::MakeSpan(buffer_));
  observer_->WriteTensor(state, player, &allocator);
}
References absl::MakeSpan(), player, and state.
Referenced by open_spiel::init_pyspiel_observer().
StringFrom()
std::string open_spiel::Observation::StringFrom (const State & state, int player) const inline
Definition at line 368 of file observer.h.
{
    return observer_->StringFrom(state, player);
  }
References player, and state.
Referenced by open_spiel::init_pyspiel_observer().
Tensor()
absl::Span< float > open_spiel::Observation::Tensor () inline
Definition at line 401 of file observer.h.
{ return absl::MakeSpan(buffer_); }
References absl::MakeSpan().
Referenced by open_spiel::init_pyspiel_observer().
tensors()
std::vector< SpanTensor > open_spiel::Observation::tensors ()
Definition at line 232 of file observer.cc.
{
  std::vector<SpanTensor> result;
  result.reserve(tensors_info_.size());
  int offset = 0;
  for (const SpanTensorInfo& info : tensors_info_) {
    const int size = info.size();
    result.emplace_back(info, absl::MakeSpan(buffer_).subspan(offset, size));
    offset += size;
  }
  return result;
}
References absl::MakeSpan(), and size.
Referenced by open_spiel::init_pyspiel_observer().
tensors_info()
const std::vector< SpanTensorInfo > & open_spiel::Observation::tensors_info () const inline
Definition at line 360 of file observer.h.
{
    return tensors_info_;
  }
Referenced by open_spiel::init_pyspiel_observer().
The documentation for this class was generated from the following files:
open_spiel/observer.h
open_spiel/observer.cc