open spiel: open_spiel::uci::UCIBot Class Reference
open_spiel::uci::UCIBot Class Reference
#include <uci_bot.h>
Public Member Functions
UCIBot (const std::string &bot_binary_path, int search_limit_value, bool ponder, const Options &options, SearchLimitType search_limit_type=SearchLimitType::kMoveTime)
~UCIBot () override
Action Step (const State &state) override
void Restart () override
void RestartAt (const State &state) override
void InformAction (const State &state, Player player_id, Action action) override
void Write (const std::string &msg) const
std::string Read (bool wait) const
void Position (const std::string &fen, const std::vector< std::string > &moves={})
Public Member Functions inherited from open_spiel::Bot
virtual ~Bot ()=default
virtual void InformActions (const State &state, const std::vector< Action > &actions)
virtual bool ProvidesForceAction ()
virtual void ForceAction (const State &state, Action action)
virtual bool ProvidesPolicy ()
virtual ActionsAndProbs GetPolicy (const State &state)
virtual std::pair< ActionsAndProbs, Action > StepWithPolicy (const State &state)
virtual bool IsClonable () const
virtual std::unique_ptr< Bot > Clone ()
Detailed Description
Definition at line 46 of file uci_bot.h.
Constructor & Destructor Documentation
UCIBot()
open_spiel::uci::UCIBot::UCIBot (const std::string & bot_binary_path, int search_limit_value, bool ponder, const Options & options, SearchLimitType search_limit_type = SearchLimitType::kMoveTime)
Definition at line 44 of file uci_bot.cc.
    : ponder_(ponder) {
  SPIEL_CHECK_GT(search_limit_value, 0);
  SPIEL_CHECK_GT(bot_binary_path.size(), 0);
  search_limit_type_ = search_limit_type;
  search_limit_value_ = search_limit_value;
  if (search_limit_type_ == SearchLimitType::kMoveTime) {
    search_limit_string_ = "movetime " + std::to_string(search_limit_value_);
  } else if (search_limit_type_ == SearchLimitType::kNodes) {
    search_limit_string_ = "nodes " + std::to_string(search_limit_value_);
  } else if (search_limit_type_ == SearchLimitType::kDepth) {
    search_limit_string_ = "depth " + std::to_string(search_limit_value_);
  } else {
    SpielFatalError("Unsupported search limit type");
  }
  StartProcess(bot_binary_path);
  Uci();
  for (auto const &[name, value] : options) {
    SetOption(name, value);
  }
  IsReady();
  UciNewGame();
}
References open_spiel::uci::kDepth, open_spiel::uci::kMoveTime, open_spiel::uci::kNodes, name, options, SPIEL_CHECK_GT, and open_spiel::SpielFatalError().
~UCIBot()
open_spiel::uci::UCIBot::~UCIBot () override
Definition at line 71 of file uci_bot.cc.
                {
  Quit();
  int status;
  while (waitpid(pid_, &status, 0) == -1) {
    // Do nothing.
  }
  if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) {
    std::cerr << "Uci sub-process failed" << std::endl;
  }
}
Member Function Documentation
InformAction()
void open_spiel::uci::UCIBot::InformAction (const State & state, Player player_id, Action action) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 125 of file uci_bot.cc.
{
  auto chess_state = down_cast<const chess::ChessState &>(state);
  chess::Move move = chess::ActionToMove(action, chess_state.Board());
  std::string move_str = move.ToLAN();
  if (ponder_ && move_str == ponder_move_) {
    PonderHit();
    was_ponder_hit_ = true;
  }
}
References action, open_spiel::chess::ActionToMove(), open_spiel::down_cast(), and state.
Position()
void open_spiel::uci::UCIBot::Position (const std::string & fen, const std::vector< std::string > & moves = {})
Definition at line 211 of file uci_bot.cc.
{
  std::string msg = "position fen " + fen;
  if (!moves.empty()) {
    std::string moves_str = absl::StrJoin(moves, " ");
    msg += " moves " + moves_str;
  }
  Write(msg);
}
References absl::StrJoin(), and Write().
Referenced by RestartAt(), and Step().
Read()
std::string open_spiel::uci::UCIBot::Read (bool wait) const
Definition at line 270 of file uci_bot.cc.
{
  char *buff;
  int count = 0;
  std::string response;
  fd_set fds;
  FD_ZERO(&fds);
  FD_SET(input_fd_, &fds);
  timeval timeout = {5, 0};  // 5 second timeout.
  int ready_fd = select(/*nfds=*/input_fd_ + 1,
                        /*readfds=*/&fds,
                        /*writefds=*/nullptr,
                        /*exceptfds*/ nullptr, wait ? nullptr : &timeout);
  if (ready_fd == -1) {
    SpielFatalError("Failed to read from uci sub-process");
  }
  if (ready_fd == 0) {
    SpielFatalError("Response from uci sub-process not received in time");
  }
  if (ioctl(input_fd_, FIONREAD, &count) == -1) {
    SpielFatalError("Failed to read input size.");
  }
  if (count == 0) {
    return "";
  }
  buff = (char*)malloc(count);
  if (read(input_fd_, buff, count) != count) {
    SpielFatalError("Read wrong number of bytes");
  }
  response.assign(buff, count);
  free(buff);
  return response;
}
References open_spiel::SpielFatalError().
Restart()
void open_spiel::uci::UCIBot::Restart () override virtual
Reimplemented from open_spiel::Bot.
Definition at line 112 of file uci_bot.cc.
                     {
  ponder_move_ = absl::nullopt;
  was_ponder_hit_ = false;
  UciNewGame();
}
RestartAt()
void open_spiel::uci::UCIBot::RestartAt (const State & state) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 118 of file uci_bot.cc.
{
  ponder_move_ = absl::nullopt;
  was_ponder_hit_ = false;
  auto chess_state = down_cast<const chess::ChessState &>(state);
  Position(chess_state.Board().ToFEN());
}
References open_spiel::down_cast(), Position(), and state.
Step()
Action open_spiel::uci::UCIBot::Step (const State & state) override virtual
Implements open_spiel::Bot.
Definition at line 82 of file uci_bot.cc.
{
  std::string move_str;
  auto chess_state = down_cast<const chess::ChessState&>(state);
  if (ponder_ && ponder_move_) {
    if (!was_ponder_hit_) {
      Stop();
      Position(chess_state.Board().ToFEN());
      tie(move_str, ponder_move_) = Go();
    } else {
      tie(move_str, ponder_move_) = ReadBestMove();
    }
  } else {
    Position(chess_state.Board().ToFEN());
    tie(move_str, ponder_move_) = Go();
  }
  was_ponder_hit_ = false;
  auto move = chess_state.Board().ParseLANMove(move_str);
  if (!move) {
    SpielFatalError("Uci sub-process returned an illegal or invalid move");
  }
  if (ponder_ && ponder_move_) {
    Position(chess_state.Board().ToFEN(), {move_str, *ponder_move_});
    GoPonder();
  }
  Action action = chess::MoveToAction(*move);
  return action;
}
References action, open_spiel::down_cast(), open_spiel::chess::MoveToAction(), Position(), open_spiel::SpielFatalError(), and state.
Write()
void open_spiel::uci::UCIBot::Write (const std::string & msg) const
Definition at line 263 of file uci_bot.cc.
{
  if (write(output_fd_, (msg + "\n").c_str(), msg.size() + 1) !=
      msg.size() + 1) {
    SpielFatalError("Sending a command to uci sub-process failed");
  }
}
References open_spiel::SpielFatalError().
Referenced by Position().
The documentation for this class was generated from the following files:
open_spiel/bots/uci/uci_bot.h
open_spiel/bots/uci/uci_bot.cc