open spiel: absl::inlined_vector_internal::Storage< T, N, A > Class Template Reference
absl::inlined_vector_internal::Storage< T, N, A > Class Template Reference
#include <inlined_vector.h>
Classes
struct ElementwiseAssignPolicy
struct ElementwiseConstructPolicy
struct ElementwiseSwapPolicy
struct MemcpyPolicy
Public Types
using MoveAssignmentPolicy
using SwapPolicy
Public Member Functions
Storage ()
Storage (const A &allocator)
~Storage ()
SizeType< A > & GetSizeAndIsAllocated ()
const SizeType< A > & GetSizeAndIsAllocated () const
SizeType< A > GetSize () const
bool GetIsAllocated () const
Pointer< A > GetAllocatedData ()
ConstPointer< A > GetAllocatedData () const
Pointer< A > GetInlinedData ()
ConstPointer< A > GetInlinedData () const
SizeType< A > GetAllocatedCapacity () const
SizeType< A > GetInlinedCapacity () const
StorageView< A > MakeStorageView ()
A & GetAllocator ()
const A & GetAllocator () const
ABSL_ATTRIBUTE_NOINLINE void InitFrom (const Storage &other)
template<typename ValueAdapter >
void Initialize (ValueAdapter values, SizeType< A > new_size)
template<typename ValueAdapter >
void Assign (ValueAdapter values, SizeType< A > new_size)
template<typename ValueAdapter >
void Resize (ValueAdapter values, SizeType< A > new_size)
template<typename ValueAdapter >
Iterator< A > Insert (ConstIterator< A > pos, ValueAdapter values, SizeType< A > insert_count)
template<typename... Args>
Reference< A > EmplaceBack (Args &&... args)
Iterator< A > Erase (ConstIterator< A > from, ConstIterator< A > to)
void Reserve (SizeType< A > requested_capacity)
void ShrinkToFit ()
void Swap (Storage *other_storage_ptr)
void SetIsAllocated ()
void UnsetIsAllocated ()
void SetSize (SizeType< A > size)
void SetAllocatedSize (SizeType< A > size)
void SetInlinedSize (SizeType< A > size)
void AddSize (SizeType< A > count)
void SubtractSize (SizeType< A > count)
void SetAllocation (Allocation< A > allocation)
void MemcpyFrom (const Storage &other_storage)
void DeallocateIfAllocated ()
template<typename ValueAdapter >
auto Initialize (ValueAdapter values, SizeType< A > new_size) -> void
template<typename ValueAdapter >
auto Assign (ValueAdapter values, SizeType< A > new_size) -> void
template<typename ValueAdapter >
auto Resize (ValueAdapter values, SizeType< A > new_size) -> void
template<typename ValueAdapter >
auto Insert (ConstIterator< A > pos, ValueAdapter values, SizeType< A > insert_count) -> Iterator< A >
template<typename... Args>
auto EmplaceBack (Args &&... args) -> Reference< A >
template<typename... Args>
auto EmplaceBackSlow (Args &&... args) -> Reference< A >
Static Public Member Functions
static SizeType< A > NextCapacity (SizeType< A > current_capacity)
static SizeType< A > ComputeCapacity (SizeType< A > current_capacity, SizeType< A > requested_capacity)
Detailed Description
template<typename T, size_t N, typename A>
class absl::inlined_vector_internal::Storage< T, N, A >
Definition at line 303 of file inlined_vector.h.
Member Typedef Documentation
MoveAssignmentPolicy
template<typename T , size_t N, typename A > using absl::inlined_vector_internal::Storage< T, N, A >::MoveAssignmentPolicy
Initial value:
 absl::conditional_t<
      IsMemcpyOk<A>::value, MemcpyPolicy,
      absl::conditional_t<IsMoveAssignOk<A>::value, ElementwiseAssignPolicy,
                          ElementwiseConstructPolicy>>
Definition at line 310 of file inlined_vector.h.
SwapPolicy
template<typename T , size_t N, typename A > using absl::inlined_vector_internal::Storage< T, N, A >::SwapPolicy
Initial value:
 absl::conditional_t<
      IsMemcpyOk<A>::value, MemcpyPolicy,
      absl::conditional_t<IsSwapOk<A>::value, ElementwiseSwapPolicy,
                          ElementwiseConstructPolicy>>
Definition at line 314 of file inlined_vector.h.
Constructor & Destructor Documentation
Storage() [1/2]
template<typename T , size_t N, typename A > absl::inlined_vector_internal::Storage< T, N, A >::Storage () inline
Definition at line 332 of file inlined_vector.h.
: metadata_(A(), /* size and is_allocated */ 0u) {}
Storage() [2/2]
template<typename T , size_t N, typename A > absl::inlined_vector_internal::Storage< T, N, A >::Storage (const A & allocator) inline explicit
Definition at line 334 of file inlined_vector.h.
      : metadata_(allocator, /* size and is_allocated */ 0u) {}
~Storage()
template<typename T , size_t N, typename A > absl::inlined_vector_internal::Storage< T, N, A >::~Storage () inline
Definition at line 337 of file inlined_vector.h.
             {
    if (GetSizeAndIsAllocated() == 0) {
      // Empty and not allocated; nothing to do.
    } else if (IsMemcpyOk<A>::value) {
      // No destructors need to be run; just deallocate if necessary.
      DeallocateIfAllocated();
    } else {
      DestroyContents();
    }
  }
References absl::inlined_vector_internal::Storage< T, N, A >::DeallocateIfAllocated(), and absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated().
Member Function Documentation
AddSize()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::AddSize (SizeType< A > count) inline
Definition at line 448 of file inlined_vector.h.
{
    GetSizeAndIsAllocated() += count << static_cast<SizeType<A>>(1);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated().
Assign() [1/2]
template<typename T , size_t N, typename A > template<typename ValueAdapter > void absl::inlined_vector_internal::Storage< T, N, A >::Assign (ValueAdapter values, SizeType< A > new_size)
Referenced by absl::InlinedVector< T, N, A >::assign(), and absl::InlinedVector< T, N, A >::assign().
Assign() [2/2]
template<typename T , size_t N, typename A > template<typename ValueAdapter > auto absl::inlined_vector_internal::Storage< T, N, A >::Assign (ValueAdapter values, SizeType< A > new_size) -> void
Definition at line 589 of file inlined_vector.h.
            {
  StorageView<A> storage_view = MakeStorageView();
  AllocationTransaction<A> allocation_tx(GetAllocator());
  absl::Span<ValueType<A>> assign_loop;
  absl::Span<ValueType<A>> construct_loop;
  absl::Span<ValueType<A>> destroy_loop;
  if (new_size > storage_view.capacity) {
    SizeType<A> requested_capacity =
        ComputeCapacity(storage_view.capacity, new_size);
    construct_loop = {allocation_tx.Allocate(requested_capacity), new_size};
    destroy_loop = {storage_view.data, storage_view.size};
  } else if (new_size > storage_view.size) {
    assign_loop = {storage_view.data, storage_view.size};
    construct_loop = {storage_view.data + storage_view.size,
                      new_size - storage_view.size};
  } else {
    assign_loop = {storage_view.data, new_size};
    destroy_loop = {storage_view.data + new_size, storage_view.size - new_size};
  }
  AssignElements<A>(assign_loop.data(), values, assign_loop.size());
  ConstructElements<A>(GetAllocator(), construct_loop.data(), values,
                       construct_loop.size());
  DestroyAdapter<A>::DestroyElements(GetAllocator(), destroy_loop.data(),
                                     destroy_loop.size());
  if (allocation_tx.DidAllocate()) {
    DeallocateIfAllocated();
    SetAllocation(std::move(allocation_tx).Release());
    SetIsAllocated();
  }
  SetSize(new_size);
}
References absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), absl::inlined_vector_internal::AssignElements(), absl::inlined_vector_internal::StorageView< A >::capacity, absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::StorageView< A >::data, absl::Span< T >::data(), absl::inlined_vector_internal::AllocationTransaction< A >::DidAllocate(), absl::inlined_vector_internal::StorageView< A >::size, absl::Span< T >::size(), and values.
ComputeCapacity()
template<typename T , size_t N, typename A > static SizeType< A > absl::inlined_vector_internal::Storage< T, N, A >::ComputeCapacity (SizeType< A > current_capacity, SizeType< A > requested_capacity) inline static
Definition at line 323 of file inlined_vector.h.
{
    return (std::max)(NextCapacity(current_capacity), requested_capacity);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::NextCapacity().
DeallocateIfAllocated()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::DeallocateIfAllocated () inline
Definition at line 471 of file inlined_vector.h.
{
    if (GetIsAllocated()) {
      MallocAdapter<A>::Deallocate(GetAllocator(), GetAllocatedData(),
                                   GetAllocatedCapacity());
    }
  }
References absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned >::Deallocate(), absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedCapacity(), absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedData(), absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator(), and absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated().
Referenced by absl::InlinedVector< T, N, A >::clear(), and absl::inlined_vector_internal::Storage< T, N, A >::~Storage().
EmplaceBack() [1/2]
template<typename T , size_t N, typename A > template<typename... Args> Reference< A > absl::inlined_vector_internal::Storage< T, N, A >::EmplaceBack (Args &&... args)
Referenced by absl::InlinedVector< T, N, A >::emplace_back().
EmplaceBack() [2/2]
template<typename T , size_t N, typename A > template<typename... Args> auto absl::inlined_vector_internal::Storage< T, N, A >::EmplaceBack (Args &&... args) -> Reference<A>
Definition at line 768 of file inlined_vector.h.
{
  StorageView<A> storage_view = MakeStorageView();
  const SizeType<A> n = storage_view.size;
  if (ABSL_PREDICT_TRUE(n != storage_view.capacity)) {
    // Fast path; new element fits.
    Pointer<A> last_ptr = storage_view.data + n;
    AllocatorTraits<A>::construct(GetAllocator(), last_ptr,
                                  std::forward<Args>(args)...);
    AddSize(1);
    return *last_ptr;
  }
  // TODO(b/173712035): Annotate with musttail attribute to prevent regression.
  return EmplaceBackSlow(std::forward<Args>(args)...);
}
References ABSL_PREDICT_TRUE, absl::inlined_vector_internal::StorageView< A >::capacity, absl::inlined_vector_internal::StorageView< A >::data, absl::n, and absl::inlined_vector_internal::StorageView< A >::size.
EmplaceBackSlow()
template<typename T , size_t N, typename A > template<typename... Args> auto absl::inlined_vector_internal::Storage< T, N, A >::EmplaceBackSlow (Args &&... args) -> Reference<A>
Definition at line 785 of file inlined_vector.h.
{
  StorageView<A> storage_view = MakeStorageView();
  AllocationTransaction<A> allocation_tx(GetAllocator());
  IteratorValueAdapter<A, MoveIterator<A>> move_values(
      MoveIterator<A>(storage_view.data));
  SizeType<A> requested_capacity = NextCapacity(storage_view.capacity);
  Pointer<A> construct_data = allocation_tx.Allocate(requested_capacity);
  Pointer<A> last_ptr = construct_data + storage_view.size;
  // Construct new element.
  AllocatorTraits<A>::construct(GetAllocator(), last_ptr,
                                std::forward<Args>(args)...);
  // Move elements from old backing store to new backing store.
  ABSL_INTERNAL_TRY {
    ConstructElements<A>(GetAllocator(), allocation_tx.GetData(), move_values,
                         storage_view.size);
  }
  ABSL_INTERNAL_CATCH_ANY {
    AllocatorTraits<A>::destroy(GetAllocator(), last_ptr);
    ABSL_INTERNAL_RETHROW;
  }
  // Destroy elements in old backing store.
  DestroyAdapter<A>::DestroyElements(GetAllocator(), storage_view.data,
                                     storage_view.size);
  DeallocateIfAllocated();
  SetAllocation(std::move(allocation_tx).Release());
  SetIsAllocated();
  AddSize(1);
  return *last_ptr;
}
References ABSL_INTERNAL_CATCH_ANY, ABSL_INTERNAL_RETHROW, ABSL_INTERNAL_TRY, absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), absl::inlined_vector_internal::StorageView< A >::capacity, absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::StorageView< A >::data, absl::inlined_vector_internal::AllocationTransaction< A >::GetData(), and absl::inlined_vector_internal::StorageView< A >::size.
Erase()
template<typename T , size_t N, typename A > auto absl::inlined_vector_internal::Storage< T, N, A >::Erase (ConstIterator< A > from, ConstIterator< A > to)
Definition at line 818 of file inlined_vector.h.
                   {
  StorageView<A> storage_view = MakeStorageView();
  auto erase_size = static_cast<SizeType<A>>(std::distance(from, to));
  auto erase_index = static_cast<SizeType<A>>(
      std::distance(ConstIterator<A>(storage_view.data), from));
  SizeType<A> erase_end_index = erase_index + erase_size;
  IteratorValueAdapter<A, MoveIterator<A>> move_values(
      MoveIterator<A>(storage_view.data + erase_end_index));
  AssignElements<A>(storage_view.data + erase_index, move_values,
                    storage_view.size - erase_end_index);
  DestroyAdapter<A>::DestroyElements(
      GetAllocator(), storage_view.data + (storage_view.size - erase_size),
      erase_size);
  SubtractSize(erase_size);
  return Iterator<A>(storage_view.data + erase_index);
}
References absl::inlined_vector_internal::AssignElements(), absl::inlined_vector_internal::StorageView< A >::data, from, absl::inlined_vector_internal::StorageView< A >::size, and to.
Referenced by absl::InlinedVector< T, N, A >::erase(), and absl::InlinedVector< T, N, A >::erase().
GetAllocatedCapacity()
template<typename T , size_t N, typename A > SizeType< A > absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedCapacity () const inline
Definition at line 378 of file inlined_vector.h.
{
    return data_.allocated.allocated_capacity;
  }
Referenced by absl::InlinedVector< T, N, A >::capacity(), absl::inlined_vector_internal::Storage< T, N, A >::DeallocateIfAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::MakeStorageView(), and absl::inlined_vector_internal::Storage< T, N, A >::Swap().
GetAllocatedData() [1/2]
template<typename T , size_t N, typename A > Pointer< A > absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedData () inline
Definition at line 362 of file inlined_vector.h.
{ return data_.allocated.allocated_data; }
Referenced by absl::InlinedVector< T, N, A >::data(), absl::InlinedVector< T, N, A >::data(), absl::inlined_vector_internal::Storage< T, N, A >::DeallocateIfAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::InitFrom(), absl::inlined_vector_internal::Storage< T, N, A >::MakeStorageView(), and absl::inlined_vector_internal::Storage< T, N, A >::Swap().
GetAllocatedData() [2/2]
template<typename T , size_t N, typename A > ConstPointer< A > absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedData () const inline
Definition at line 364 of file inlined_vector.h.
{
    return data_.allocated.allocated_data;
  }
GetAllocator() [1/2]
template<typename T , size_t N, typename A > A & absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator () inline
Definition at line 393 of file inlined_vector.h.
{ return metadata_.template get<0>(); }
References absl::get().
Referenced by absl::InlinedVector< T, N, A >::clear(), absl::inlined_vector_internal::Storage< T, N, A >::DeallocateIfAllocated(), absl::InlinedVector< T, N, A >::get_allocator(), absl::InlinedVector< T, N, A >::InlinedVector(), absl::InlinedVector< T, N, A >::InlinedVector(), absl::InlinedVector< T, N, A >::max_size(), absl::InlinedVector< T, N, A >::pop_back(), and absl::inlined_vector_internal::Storage< T, N, A >::Swap().
GetAllocator() [2/2]
template<typename T , size_t N, typename A > const A & absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator () const inline
Definition at line 395 of file inlined_vector.h.
{ return metadata_.template get<0>(); }
References absl::get().
GetInlinedCapacity()
template<typename T , size_t N, typename A > SizeType< A > absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedCapacity () const inline
Definition at line 382 of file inlined_vector.h.
{
    return static_cast<SizeType<A>>(kOptimalInlinedSize);
  }
Referenced by absl::InlinedVector< T, N, A >::capacity(), and absl::inlined_vector_internal::Storage< T, N, A >::MakeStorageView().
GetInlinedData() [1/2]
template<typename T , size_t N, typename A > Pointer< A > absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedData () inline
Definition at line 368 of file inlined_vector.h.
{
    return reinterpret_cast<Pointer<A>>(
        std::addressof(data_.inlined.inlined_data[0]));
  }
Referenced by absl::InlinedVector< T, N, A >::data(), absl::InlinedVector< T, N, A >::data(), absl::inlined_vector_internal::Storage< T, N, A >::InitFrom(), absl::InlinedVector< T, N, A >::InlinedVector(), absl::inlined_vector_internal::Storage< T, N, A >::MakeStorageView(), and absl::inlined_vector_internal::Storage< T, N, A >::Swap().
GetInlinedData() [2/2]
template<typename T , size_t N, typename A > ConstPointer< A > absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedData () const inline
Definition at line 373 of file inlined_vector.h.
{
    return reinterpret_cast<ConstPointer<A>>(
        std::addressof(data_.inlined.inlined_data[0]));
  }
GetIsAllocated()
template<typename T , size_t N, typename A > bool absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated () const inline
Definition at line 360 of file inlined_vector.h.
{ return GetSizeAndIsAllocated() & 1; }
References absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated().
Referenced by absl::InlinedVector< T, N, A >::capacity(), absl::InlinedVector< T, N, A >::data(), absl::InlinedVector< T, N, A >::data(), absl::inlined_vector_internal::Storage< T, N, A >::DeallocateIfAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::InitFrom(), absl::InlinedVector< T, N, A >::InlinedVector(), absl::inlined_vector_internal::Storage< T, N, A >::MakeStorageView(), absl::inlined_vector_internal::Storage< T, N, A >::MemcpyFrom(), absl::inlined_vector_internal::Storage< T, N, A >::SetSize(), absl::InlinedVector< T, N, A >::shrink_to_fit(), and absl::inlined_vector_internal::Storage< T, N, A >::Swap().
GetSize()
template<typename T , size_t N, typename A > SizeType< A > absl::inlined_vector_internal::Storage< T, N, A >::GetSize () const inline
Definition at line 358 of file inlined_vector.h.
{ return GetSizeAndIsAllocated() >> 1; }
References absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated().
Referenced by absl::inlined_vector_internal::Storage< T, N, A >::InitFrom(), absl::inlined_vector_internal::Storage< T, N, A >::MakeStorageView(), absl::InlinedVector< T, N, A >::size(), absl::inlined_vector_internal::Storage< T, N, A >::SubtractSize(), and absl::inlined_vector_internal::Storage< T, N, A >::Swap().
GetSizeAndIsAllocated() [1/2]
template<typename T , size_t N, typename A > SizeType< A > & absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated () inline
Definition at line 352 of file inlined_vector.h.
{ return metadata_.template get<1>(); }
References absl::get().
Referenced by absl::inlined_vector_internal::Storage< T, N, A >::AddSize(), absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::GetSize(), absl::inlined_vector_internal::Storage< T, N, A >::InitFrom(), absl::inlined_vector_internal::Storage< T, N, A >::MemcpyFrom(), absl::inlined_vector_internal::Storage< T, N, A >::SetAllocatedSize(), absl::inlined_vector_internal::Storage< T, N, A >::SetInlinedSize(), absl::inlined_vector_internal::Storage< T, N, A >::SetIsAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::SetSize(), absl::inlined_vector_internal::Storage< T, N, A >::SubtractSize(), absl::inlined_vector_internal::Storage< T, N, A >::UnsetIsAllocated(), and absl::inlined_vector_internal::Storage< T, N, A >::~Storage().
GetSizeAndIsAllocated() [2/2]
template<typename T , size_t N, typename A > const SizeType< A > & absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated () const inline
Definition at line 354 of file inlined_vector.h.
{
    return metadata_.template get<1>();
  }
References absl::get().
InitFrom()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::InitFrom (const Storage< T, N, A > & other)
Definition at line 526 of file inlined_vector.h.
{
  const SizeType<A> n = other.GetSize();
  ABSL_HARDENING_ASSERT(n > 0);  // Empty sources handled handled in caller.
  ConstPointer<A> src;
  Pointer<A> dst;
  if (!other.GetIsAllocated()) {
    dst = GetInlinedData();
    src = other.GetInlinedData();
  } else {
    // Because this is only called from the `InlinedVector` constructors, it's
    // safe to take on the allocation with size `0`. If `ConstructElements(...)`
    // throws, deallocation will be automatically handled by `~Storage()`.
    SizeType<A> requested_capacity = ComputeCapacity(GetInlinedCapacity(), n);
    Allocation<A> allocation =
        MallocAdapter<A>::Allocate(GetAllocator(), requested_capacity);
    SetAllocation(allocation);
    dst = allocation.data;
    src = other.GetAllocatedData();
  }
  if (IsMemcpyOk<A>::value) {
    std::memcpy(reinterpret_cast<char*>(dst),
                reinterpret_cast<const char*>(src), n * sizeof(ValueType<A>));
  } else {
    auto values = IteratorValueAdapter<A, ConstPointer<A>>(src);
    ConstructElements<A>(GetAllocator(), dst, values, n);
  }
  GetSizeAndIsAllocated() = other.GetSizeAndIsAllocated();
}
References ABSL_HARDENING_ASSERT, absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned >::Allocate(), absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::Allocation< A >::data, absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedData(), absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedData(), absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::GetSize(), absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated(), absl::n, and values.
Referenced by absl::InlinedVector< T, N, A >::InlinedVector().
Initialize() [1/2]
template<typename T , size_t N, typename A > template<typename ValueAdapter > void absl::inlined_vector_internal::Storage< T, N, A >::Initialize (ValueAdapter values, SizeType< A > new_size)
Referenced by absl::InlinedVector< T, N, A >::InlinedVector(), absl::InlinedVector< T, N, A >::InlinedVector(), absl::InlinedVector< T, N, A >::InlinedVector(), and absl::InlinedVector< T, N, A >::InlinedVector().
Initialize() [2/2]
template<typename T , size_t N, typename A > template<typename ValueAdapter > auto absl::inlined_vector_internal::Storage< T, N, A >::Initialize (ValueAdapter values, SizeType< A > new_size) -> void
Definition at line 557 of file inlined_vector.h.
            {
  // Only callable from constructors!
  ABSL_HARDENING_ASSERT(!GetIsAllocated());
  ABSL_HARDENING_ASSERT(GetSize() == 0);
  Pointer<A> construct_data;
  if (new_size > GetInlinedCapacity()) {
    // Because this is only called from the `InlinedVector` constructors, it's
    // safe to take on the allocation with size `0`. If `ConstructElements(...)`
    // throws, deallocation will be automatically handled by `~Storage()`.
    SizeType<A> requested_capacity =
        ComputeCapacity(GetInlinedCapacity(), new_size);
    Allocation<A> allocation =
        MallocAdapter<A>::Allocate(GetAllocator(), requested_capacity);
    construct_data = allocation.data;
    SetAllocation(allocation);
    SetIsAllocated();
  } else {
    construct_data = GetInlinedData();
  }
  ConstructElements<A>(GetAllocator(), construct_data, values, new_size);
  // Since the initial size was guaranteed to be `0` and the allocated bit is
  // already correct for either case, *adding* `new_size` gives us the correct
  // result faster than setting it directly.
  AddSize(new_size);
}
References ABSL_HARDENING_ASSERT, absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned >::Allocate(), absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::Allocation< A >::data, and values.
Insert() [1/2]
template<typename T , size_t N, typename A > template<typename ValueAdapter > Iterator< A > absl::inlined_vector_internal::Storage< T, N, A >::Insert (ConstIterator< A > pos, ValueAdapter values, SizeType< A > insert_count)
Referenced by absl::InlinedVector< T, N, A >::emplace(), absl::InlinedVector< T, N, A >::insert(), and absl::InlinedVector< T, N, A >::insert().
Insert() [2/2]
template<typename T , size_t N, typename A > template<typename ValueAdapter > auto absl::inlined_vector_internal::Storage< T, N, A >::Insert (ConstIterator< A > pos, ValueAdapter values, SizeType< A > insert_count) -> Iterator<A>
Definition at line 675 of file inlined_vector.h.
{
  StorageView<A> storage_view = MakeStorageView();
  auto insert_index = static_cast<SizeType<A>>(
      std::distance(ConstIterator<A>(storage_view.data), pos));
  SizeType<A> insert_end_index = insert_index + insert_count;
  SizeType<A> new_size = storage_view.size + insert_count;
  if (new_size > storage_view.capacity) {
    AllocationTransaction<A> allocation_tx(GetAllocator());
    ConstructionTransaction<A> construction_tx(GetAllocator());
    ConstructionTransaction<A> move_construction_tx(GetAllocator());
    IteratorValueAdapter<A, MoveIterator<A>> move_values(
        MoveIterator<A>(storage_view.data));
    SizeType<A> requested_capacity =
        ComputeCapacity(storage_view.capacity, new_size);
    Pointer<A> new_data = allocation_tx.Allocate(requested_capacity);
    construction_tx.Construct(new_data + insert_index, values, insert_count);
    move_construction_tx.Construct(new_data, move_values, insert_index);
    ConstructElements<A>(GetAllocator(), new_data + insert_end_index,
                         move_values, storage_view.size - insert_index);
    DestroyAdapter<A>::DestroyElements(GetAllocator(), storage_view.data,
                                       storage_view.size);
    std::move(construction_tx).Commit();
    std::move(move_construction_tx).Commit();
    DeallocateIfAllocated();
    SetAllocation(std::move(allocation_tx).Release());
    SetAllocatedSize(new_size);
    return Iterator<A>(new_data + insert_index);
  } else {
    SizeType<A> move_construction_destination_index =
        (std::max)(insert_end_index, storage_view.size);
    ConstructionTransaction<A> move_construction_tx(GetAllocator());
    IteratorValueAdapter<A, MoveIterator<A>> move_construction_values(
        MoveIterator<A>(storage_view.data +
                        (move_construction_destination_index - insert_count)));
    absl::Span<ValueType<A>> move_construction = {
        storage_view.data + move_construction_destination_index,
        new_size - move_construction_destination_index};
    Pointer<A> move_assignment_values = storage_view.data + insert_index;
    absl::Span<ValueType<A>> move_assignment = {
        storage_view.data + insert_end_index,
        move_construction_destination_index - insert_end_index};
    absl::Span<ValueType<A>> insert_assignment = {move_assignment_values,
                                                  move_construction.size()};
    absl::Span<ValueType<A>> insert_construction = {
        insert_assignment.data() + insert_assignment.size(),
        insert_count - insert_assignment.size()};
    move_construction_tx.Construct(move_construction.data(),
                                   move_construction_values,
                                   move_construction.size());
    for (Pointer<A>
             destination = move_assignment.data() + move_assignment.size(),
             last_destination = move_assignment.data(),
             source = move_assignment_values + move_assignment.size();
         ;) {
      --destination;
      --source;
      if (destination < last_destination) break;
      *destination = std::move(*source);
    }
    AssignElements<A>(insert_assignment.data(), values,
                      insert_assignment.size());
    ConstructElements<A>(GetAllocator(), insert_construction.data(), values,
                         insert_construction.size());
    std::move(move_construction_tx).Commit();
    AddSize(insert_count);
    return Iterator<A>(storage_view.data + insert_index);
  }
}
References absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), absl::inlined_vector_internal::AssignElements(), absl::inlined_vector_internal::StorageView< A >::capacity, absl::inlined_vector_internal::ConstructionTransaction< A >::Construct(), absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::StorageView< A >::data, absl::Span< T >::data(), absl::inlined_vector_internal::StorageView< A >::size, absl::Span< T >::size(), and values.
MakeStorageView()
template<typename T , size_t N, typename A > StorageView< A > absl::inlined_vector_internal::Storage< T, N, A >::MakeStorageView () inline
Definition at line 386 of file inlined_vector.h.
{
    return GetIsAllocated() ? StorageView<A>{GetAllocatedData(), GetSize(),
                                             GetAllocatedCapacity()}
                            : StorageView<A>{GetInlinedData(), GetSize(),
                                             GetInlinedCapacity()};
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedCapacity(), absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedData(), absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedCapacity(), absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedData(), absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated(), and absl::inlined_vector_internal::Storage< T, N, A >::GetSize().
MemcpyFrom()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::MemcpyFrom (const Storage< T, N, A > & other_storage) inline
Definition at line 463 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(IsMemcpyOk<A>::value ||
                          other_storage.GetIsAllocated());
    GetSizeAndIsAllocated() = other_storage.GetSizeAndIsAllocated();
    data_ = other_storage.data_;
  }
References ABSL_HARDENING_ASSERT, absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated(), and absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated().
Referenced by absl::InlinedVector< T, N, A >::InlinedVector(), absl::InlinedVector< T, N, A >::InlinedVector(), and absl::InlinedVector< T, N, A >::InlinedVector().
NextCapacity()
template<typename T , size_t N, typename A > static SizeType< A > absl::inlined_vector_internal::Storage< T, N, A >::NextCapacity (SizeType< A > current_capacity) inline static
Definition at line 319 of file inlined_vector.h.
{
    return current_capacity * 2;
  }
Referenced by absl::inlined_vector_internal::Storage< T, N, A >::ComputeCapacity().
Reserve()
template<typename T , size_t N, typename A > auto absl::inlined_vector_internal::Storage< T, N, A >::Reserve (SizeType< A > requested_capacity)
Definition at line 842 of file inlined_vector.h.
{
  StorageView<A> storage_view = MakeStorageView();
  if (ABSL_PREDICT_FALSE(requested_capacity <= storage_view.capacity)) return;
  AllocationTransaction<A> allocation_tx(GetAllocator());
  IteratorValueAdapter<A, MoveIterator<A>> move_values(
      MoveIterator<A>(storage_view.data));
  SizeType<A> new_requested_capacity =
      ComputeCapacity(storage_view.capacity, requested_capacity);
  Pointer<A> new_data = allocation_tx.Allocate(new_requested_capacity);
  ConstructElements<A>(GetAllocator(), new_data, move_values,
                       storage_view.size);
  DestroyAdapter<A>::DestroyElements(GetAllocator(), storage_view.data,
                                     storage_view.size);
  DeallocateIfAllocated();
  SetAllocation(std::move(allocation_tx).Release());
  SetIsAllocated();
}
References ABSL_PREDICT_FALSE, absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), absl::inlined_vector_internal::StorageView< A >::capacity, absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::StorageView< A >::data, and absl::inlined_vector_internal::StorageView< A >::size.
Referenced by absl::InlinedVector< T, N, A >::reserve().
Resize() [1/2]
template<typename T , size_t N, typename A > template<typename ValueAdapter > void absl::inlined_vector_internal::Storage< T, N, A >::Resize (ValueAdapter values, SizeType< A > new_size)
Referenced by absl::InlinedVector< T, N, A >::resize(), and absl::InlinedVector< T, N, A >::resize().
Resize() [2/2]
template<typename T , size_t N, typename A > template<typename ValueAdapter > auto absl::inlined_vector_internal::Storage< T, N, A >::Resize (ValueAdapter values, SizeType< A > new_size) -> void
Definition at line 632 of file inlined_vector.h.
            {
  StorageView<A> storage_view = MakeStorageView();
  Pointer<A> const base = storage_view.data;
  const SizeType<A> size = storage_view.size;
  A& alloc = GetAllocator();
  if (new_size <= size) {
    // Destroy extra old elements.
    DestroyAdapter<A>::DestroyElements(alloc, base + new_size, size - new_size);
  } else if (new_size <= storage_view.capacity) {
    // Construct new elements in place.
    ConstructElements<A>(alloc, base + size, values, new_size - size);
  } else {
    // Steps:
    //  a. Allocate new backing store.
    //  b. Construct new elements in new backing store.
    //  c. Move existing elements from old backing store to new backing store.
    //  d. Destroy all elements in old backing store.
    // Use transactional wrappers for the first two steps so we can roll
    // back if necessary due to exceptions.
    AllocationTransaction<A> allocation_tx(alloc);
    SizeType<A> requested_capacity =
        ComputeCapacity(storage_view.capacity, new_size);
    Pointer<A> new_data = allocation_tx.Allocate(requested_capacity);
    ConstructionTransaction<A> construction_tx(alloc);
    construction_tx.Construct(new_data + size, values, new_size - size);
    IteratorValueAdapter<A, MoveIterator<A>> move_values(
        (MoveIterator<A>(base)));
    ConstructElements<A>(alloc, new_data, move_values, size);
    DestroyAdapter<A>::DestroyElements(alloc, base, size);
    std::move(construction_tx).Commit();
    DeallocateIfAllocated();
    SetAllocation(std::move(allocation_tx).Release());
    SetIsAllocated();
  }
  SetSize(new_size);
}
References alloc, absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), absl::inlined_vector_internal::StorageView< A >::capacity, absl::inlined_vector_internal::ConstructionTransaction< A >::Construct(), absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::StorageView< A >::data, absl::inlined_vector_internal::StorageView< A >::size, size, and values.
SetAllocatedSize()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::SetAllocatedSize (SizeType< A > size) inline
Definition at line 440 of file inlined_vector.h.
{
    GetSizeAndIsAllocated() = (size << 1) | static_cast<SizeType<A>>(1);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated(), and size.
Referenced by absl::InlinedVector< T, N, A >::InlinedVector(), and absl::InlinedVector< T, N, A >::InlinedVector().
SetAllocation()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::SetAllocation (Allocation< A > allocation) inline
Definition at line 458 of file inlined_vector.h.
{
    data_.allocated.allocated_data = allocation.data;
    data_.allocated.allocated_capacity = allocation.capacity;
  }
References absl::inlined_vector_internal::Allocation< A >::capacity, and absl::inlined_vector_internal::Allocation< A >::data.
Referenced by absl::InlinedVector< T, N, A >::InlinedVector(), absl::InlinedVector< T, N, A >::InlinedVector(), and absl::inlined_vector_internal::Storage< T, N, A >::Swap().
SetInlinedSize()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::SetInlinedSize (SizeType< A > size) inline
Definition at line 444 of file inlined_vector.h.
{
    GetSizeAndIsAllocated() = size << static_cast<SizeType<A>>(1);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated(), and size.
Referenced by absl::InlinedVector< T, N, A >::clear(), and absl::InlinedVector< T, N, A >::InlinedVector().
SetIsAllocated()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::SetIsAllocated () inline
Definition at line 427 of file inlined_vector.h.
{
    GetSizeAndIsAllocated() |= static_cast<SizeType<A>>(1);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated().
SetSize()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::SetSize (SizeType< A > size) inline
Definition at line 435 of file inlined_vector.h.
{
    GetSizeAndIsAllocated() =
        (size << 1) | static_cast<SizeType<A>>(GetIsAllocated());
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated(), and size.
ShrinkToFit()
template<typename T , size_t N, typename A > auto absl::inlined_vector_internal::Storage< T, N, A >::ShrinkToFit ()
Definition at line 868 of file inlined_vector.h.
{
  // May only be called on allocated instances!
  ABSL_HARDENING_ASSERT(GetIsAllocated());
  StorageView<A> storage_view{GetAllocatedData(), GetSize(),
                              GetAllocatedCapacity()};
  if (ABSL_PREDICT_FALSE(storage_view.size == storage_view.capacity)) return;
  AllocationTransaction<A> allocation_tx(GetAllocator());
  IteratorValueAdapter<A, MoveIterator<A>> move_values(
      MoveIterator<A>(storage_view.data));
  Pointer<A> construct_data;
  if (storage_view.size > GetInlinedCapacity()) {
    SizeType<A> requested_capacity = storage_view.size;
    construct_data = allocation_tx.Allocate(requested_capacity);
    if (allocation_tx.GetCapacity() >= storage_view.capacity) {
      // Already using the smallest available heap allocation.
      return;
    }
  } else {
    construct_data = GetInlinedData();
  }
  ABSL_INTERNAL_TRY {
    ConstructElements<A>(GetAllocator(), construct_data, move_values,
                         storage_view.size);
  }
  ABSL_INTERNAL_CATCH_ANY {
    SetAllocation({storage_view.data, storage_view.capacity});
    ABSL_INTERNAL_RETHROW;
  }
  DestroyAdapter<A>::DestroyElements(GetAllocator(), storage_view.data,
                                     storage_view.size);
  MallocAdapter<A>::Deallocate(GetAllocator(), storage_view.data,
                               storage_view.capacity);
  if (allocation_tx.DidAllocate()) {
    SetAllocation(std::move(allocation_tx).Release());
  } else {
    UnsetIsAllocated();
  }
}
References ABSL_HARDENING_ASSERT, ABSL_INTERNAL_CATCH_ANY, ABSL_INTERNAL_RETHROW, ABSL_INTERNAL_TRY, ABSL_PREDICT_FALSE, absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned >::Deallocate(), absl::inlined_vector_internal::AllocationTransaction< A >::DidAllocate(), and absl::inlined_vector_internal::AllocationTransaction< A >::GetCapacity().
Referenced by absl::InlinedVector< T, N, A >::shrink_to_fit().
SubtractSize()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::SubtractSize (SizeType< A > count) inline
Definition at line 452 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(count <= GetSize());
    GetSizeAndIsAllocated() -= count << static_cast<SizeType<A>>(1);
  }
References ABSL_HARDENING_ASSERT, absl::inlined_vector_internal::Storage< T, N, A >::GetSize(), and absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated().
Referenced by absl::InlinedVector< T, N, A >::pop_back().
Swap()
template<typename T , size_t N, typename A > auto absl::inlined_vector_internal::Storage< T, N, A >::Swap (Storage< T, N, A > * other_storage_ptr)
Definition at line 917 of file inlined_vector.h.
{
  using std::swap;
  ABSL_HARDENING_ASSERT(this != other_storage_ptr);
  if (GetIsAllocated() && other_storage_ptr->GetIsAllocated()) {
    swap(data_.allocated, other_storage_ptr->data_.allocated);
  } else if (!GetIsAllocated() && !other_storage_ptr->GetIsAllocated()) {
    SwapInlinedElements(SwapPolicy{}, other_storage_ptr);
  } else {
    Storage* allocated_ptr = this;
    Storage* inlined_ptr = other_storage_ptr;
    if (!allocated_ptr->GetIsAllocated()) swap(allocated_ptr, inlined_ptr);
    StorageView<A> allocated_storage_view{
        allocated_ptr->GetAllocatedData(), allocated_ptr->GetSize(),
        allocated_ptr->GetAllocatedCapacity()};
    IteratorValueAdapter<A, MoveIterator<A>> move_values(
        MoveIterator<A>(inlined_ptr->GetInlinedData()));
    ABSL_INTERNAL_TRY {
      ConstructElements<A>(inlined_ptr->GetAllocator(),
                           allocated_ptr->GetInlinedData(), move_values,
                           inlined_ptr->GetSize());
    }
    ABSL_INTERNAL_CATCH_ANY {
      allocated_ptr->SetAllocation(Allocation<A>{
          allocated_storage_view.data, allocated_storage_view.capacity});
      ABSL_INTERNAL_RETHROW;
    }
    DestroyAdapter<A>::DestroyElements(inlined_ptr->GetAllocator(),
                                       inlined_ptr->GetInlinedData(),
                                       inlined_ptr->GetSize());
    inlined_ptr->SetAllocation(Allocation<A>{allocated_storage_view.data,
                                             allocated_storage_view.capacity});
  }
  swap(GetSizeAndIsAllocated(), other_storage_ptr->GetSizeAndIsAllocated());
  swap(GetAllocator(), other_storage_ptr->GetAllocator());
}
References ABSL_HARDENING_ASSERT, ABSL_INTERNAL_CATCH_ANY, ABSL_INTERNAL_RETHROW, ABSL_INTERNAL_TRY, absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::Allocation< A >::data, absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedCapacity(), absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedData(), absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator(), absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedData(), absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::GetSize(), absl::inlined_vector_internal::Storage< T, N, A >::SetAllocation(), and absl::swap().
Referenced by absl::InlinedVector< T, N, A >::swap().
UnsetIsAllocated()
template<typename T , size_t N, typename A > void absl::inlined_vector_internal::Storage< T, N, A >::UnsetIsAllocated () inline
Definition at line 431 of file inlined_vector.h.
{
    GetSizeAndIsAllocated() &= ((std::numeric_limits<SizeType<A>>::max)() - 1);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetSizeAndIsAllocated().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/inlined_vector.h