open spiel: Memory Class Reference
Memory Class Reference
#include <Memory.h>
Public Member Functions
Memory ()
~Memory ()
void Reset ()
void ResetThread (const unsigned thrId)
void ReturnThread (const unsigned thrId)
void Resize (const unsigned n, const TTmemory flag, const int memDefault_MB, const int memMaximum_MB)
int NumThreads () const
ThreadData * GetPtr (const unsigned thrId)
double MemoryInUseMB (const unsigned thrId) const
void ReturnAllMemory ()
string ThreadSize (const unsigned thrId) const
Detailed Description
Definition at line 115 of file Memory.h.
Constructor & Destructor Documentation
Memory()
Memory::Memory ()
Definition at line 14 of file Memory.cpp.
{
  Memory::Reset();
}
References Reset().
~Memory()
Memory::~Memory ()
Definition at line 20 of file Memory.cpp.
{
}
Member Function Documentation
GetPtr()
ThreadData * Memory::GetPtr (const unsigned thrId)
Definition at line 102 of file Memory.cpp.
{
  if (thrId >= nThreads)
  {
    cout << "Critical Error in Memory::GetPtr: thrId(" << thrId << ") should be < nThreads(" << nThreads << ")." << endl;
    exit(1);
  }
  return memory[thrId];
}
Referenced by AnalysePlayBin(), CalcSingleCommon(), CloseDebugFiles(), InitDebugFiles(), and SolveBoard().
MemoryInUseMB()
double Memory::MemoryInUseMB (const unsigned thrId) const
Definition at line 113 of file Memory.cpp.
{
  return memory[thrId]->transTable->MemoryInUse() +
    8192. * sizeof(relRanksType) / static_cast<double>(1024.);
}
Referenced by ResetThread(), and ReturnThread().
NumThreads()
int Memory::NumThreads () const
Definition at line 96 of file Memory.cpp.
{
  return static_cast<int>(nThreads);
}
Referenced by SetResources().
Reset()
void Memory::Reset ()
Definition at line 25 of file Memory.cpp.
{
  nThreads = 0;
}
Referenced by Memory().
ResetThread()
void Memory::ResetThread (const unsigned thrId)
Definition at line 31 of file Memory.cpp.
{
  memory[thrId]->transTable->ResetMemory(TT_RESET_FREE_MEMORY);
  memory[thrId]->memUsed = Memory::MemoryInUseMB(thrId);
}
References MemoryInUseMB(), and TT_RESET_FREE_MEMORY.
Referenced by FreeThreadMem().
Resize()
void Memory::Resize (const unsigned n, const TTmemory flag, const int memDefault_MB, const int memMaximum_MB)
Definition at line 45 of file Memory.cpp.
{
  if (nThreads == n)
    return;
  if (nThreads > n)
  {
    // Downsize.
    for (unsigned i = n; i < nThreads; i++)
    {
      memory[i]->transTable->ReturnAllMemory();
      delete memory[i]->transTable;
      delete memory[i];
    }
    memory.resize(static_cast<unsigned>(n));
    threadSizes.resize(static_cast<unsigned>(n));
  }
  else
  {
    // Upsize.
    memory.resize(n);
    threadSizes.resize(n);
    for (unsigned i = nThreads; i < n; i++)
    {
      memory[i] = new ThreadData();
      if (flag == DDS_TT_SMALL)
      {
        memory[i]->transTable = new TransTableS;
        threadSizes[i] = "S";
      }
      else
      {
        memory[i]->transTable = new TransTableL;
        threadSizes[i] = "L";
      }
      memory[i]->transTable->SetMemoryDefault(memDefault_MB);
      memory[i]->transTable->SetMemoryMaximum(memMaximum_MB);
      memory[i]->transTable->MakeTT();
    }
  }
  nThreads = n;
}
References DDS_TT_SMALL, i, and n.
Referenced by ReturnAllMemory(), and SetResources().
ReturnAllMemory()
void Memory::ReturnAllMemory ()
Definition at line 120 of file Memory.cpp.
{
  Memory::Resize(0, DDS_TT_SMALL, 0, 0);
}
References DDS_TT_SMALL, and Resize().
ReturnThread()
void Memory::ReturnThread (const unsigned thrId)
Definition at line 38 of file Memory.cpp.
{
  memory[thrId]->transTable->ReturnAllMemory();
  memory[thrId]->memUsed = Memory::MemoryInUseMB(thrId);
}
References MemoryInUseMB().
Referenced by FreeMemory().
ThreadSize()
string Memory::ThreadSize (const unsigned thrId) const
Definition at line 126 of file Memory.cpp.
{
  return threadSizes[thrId];
}
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/Memory.h
open_spiel/games/bridge/double_dummy_solver/src/Memory.cpp