open spiel: open_spiel::dark_chess::DarkChessState Class Reference
open_spiel::dark_chess::DarkChessState Class Reference
#include <dark_chess.h>
Public Member Functions
DarkChessState (std::shared_ptr< const Game > game, int board_size, const std::string &fen)
DarkChessState (const DarkChessState &)=default
DarkChessState & operator= (const DarkChessState &)=default
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
chess::ChessBoard & Board ()
const chess::ChessBoard & Board () const
int BoardSize () const
chess::ChessBoard & StartBoard ()
const chess::ChessBoard & StartBoard () const
std::vector< chess::Move > & MovesHistory ()
const std::vector< chess::Move > & MovesHistory () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Friends
class DarkChessObserver
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 61 of file dark_chess.h.
Constructor & Destructor Documentation
DarkChessState() [1/2]
open_spiel::dark_chess::DarkChessState::DarkChessState (std::shared_ptr< const Game > game, int board_size, const std::string & fen)
Definition at line 448 of file dark_chess.cc.
    : State(game),
      start_board_(*chess::ChessBoard::BoardFromFEN(fen, board_size, true)),
      current_board_(start_board_) {
  SPIEL_CHECK_TRUE(&current_board_);
  repetitions_[current_board_.HashValue()] = 1;
}
References open_spiel::chess::ChessBoard::HashValue(), and SPIEL_CHECK_TRUE.
DarkChessState() [2/2]
open_spiel::dark_chess::DarkChessState::DarkChessState (const DarkChessState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::dark_chess::DarkChessState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 482 of file dark_chess.cc.
{
  chess::Move move = ActionToMove(action, Board());
  return move.ToSAN(Board());
}
References action, and Board().
Board() [1/2]
chess::ChessBoard & open_spiel::dark_chess::DarkChessState::Board () inline
Definition at line 90 of file dark_chess.h.
{ return current_board_; }
Referenced by ActionToString(), CurrentPlayer(), DoApplyAction(), and ToString().
Board() [2/2]
const chess::ChessBoard & open_spiel::dark_chess::DarkChessState::Board () const inline
Definition at line 91 of file dark_chess.h.
{ return current_board_; }
BoardSize()
int open_spiel::dark_chess::DarkChessState::BoardSize () const inline
Definition at line 92 of file dark_chess.h.
{ return current_board_.BoardSize(); }
References open_spiel::chess::ChessBoard::BoardSize().
Clone()
std::unique_ptr< State > open_spiel::dark_chess::DarkChessState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 510 of file dark_chess.cc.
{
  return std::make_unique<DarkChessState>(*this);
}
CurrentPlayer()
Player open_spiel::dark_chess::DarkChessState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 71 of file dark_chess.h.
{
    return IsTerminal() ? kTerminalPlayerId : ColorToPlayer(Board().ToPlay());
  }
References Board(), IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::dark_chess::DarkChessState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 457 of file dark_chess.cc.
{
  chess::Move move = ActionToMove(action, Board());
  moves_history_.push_back(move);
  Board().ApplyMove(move);
  ++repetitions_[current_board_.HashValue()];
  cached_legal_actions_.reset();
}
References action, open_spiel::chess::ChessBoard::ApplyMove(), Board(), open_spiel::chess::ChessBoard::HashValue(), and absl::optional< T >::reset().
IsTerminal()
bool open_spiel::dark_chess::DarkChessState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 78 of file dark_chess.h.
{
    return static_cast<bool>(MaybeFinalReturns());
  }
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::dark_chess::DarkChessState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 476 of file dark_chess.cc.
{
  MaybeGenerateLegalActions();
  if (IsTerminal()) return {};
  return *cached_legal_actions_;
}
References IsTerminal().
MovesHistory() [1/2]
std::vector< chess::Move > & open_spiel::dark_chess::DarkChessState::MovesHistory () inline
Definition at line 98 of file dark_chess.h.
{ return moves_history_; }
MovesHistory() [2/2]
const std::vector< chess::Move > & open_spiel::dark_chess::DarkChessState::MovesHistory () const inline
Definition at line 99 of file dark_chess.h.
{
    return moves_history_;
  }
ObservationString()
std::string open_spiel::dark_chess::DarkChessState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 498 of file dark_chess.cc.
{
  const auto& game = open_spiel::down_cast<const DarkChessGame&>(*game_);
  return game.default_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
ObservationTensor()
void open_spiel::dark_chess::DarkChessState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 503 of file dark_chess.cc.
{
  ContiguousAllocator allocator(values);
  const auto& game = open_spiel::down_cast<const DarkChessGame&>(*game_);
  game.default_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
operator=()
DarkChessState & open_spiel::dark_chess::DarkChessState::operator= (const DarkChessState &) default
Returns()
std::vector< double > open_spiel::dark_chess::DarkChessState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 489 of file dark_chess.cc.
{
  auto maybe_final_returns = MaybeFinalReturns();
  if (maybe_final_returns) {
    return *maybe_final_returns;
  } else {
    return {0.0, 0.0};
  }
}
StartBoard() [1/2]
chess::ChessBoard & open_spiel::dark_chess::DarkChessState::StartBoard () inline
Definition at line 95 of file dark_chess.h.
{ return start_board_; }
StartBoard() [2/2]
const chess::ChessBoard & open_spiel::dark_chess::DarkChessState::StartBoard () const inline
Definition at line 96 of file dark_chess.h.
{ return start_board_; }
ToString()
std::string open_spiel::dark_chess::DarkChessState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 487 of file dark_chess.cc.
{ return Board().ToFEN(); }
References Board(), and open_spiel::chess::ChessBoard::ToFEN().
UndoAction()
void open_spiel::dark_chess::DarkChessState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 514 of file dark_chess.cc.
{
  // TODO: Make this fast by storing undo info in another stack.
  SPIEL_CHECK_GE(moves_history_.size(), 1);
  --repetitions_[current_board_.HashValue()];
  moves_history_.pop_back();
  history_.pop_back();
  --move_number_;
  current_board_ = start_board_;
  for (const chess::Move& move : moves_history_) {
    current_board_.ApplyMove(move);
  }
}
References open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::chess::ChessBoard::HashValue(), open_spiel::State::history_, open_spiel::State::move_number_, and SPIEL_CHECK_GE.
Friends And Related Symbol Documentation
DarkChessObserver
friend class DarkChessObserver friend
Definition at line 107 of file dark_chess.h.
The documentation for this class was generated from the following files:
open_spiel/games/dark_chess/dark_chess.h
open_spiel/games/dark_chess/dark_chess.cc