open spiel: absl::random_internal::RandenPool< T > Class Template Reference
absl::random_internal::RandenPool< T > Class Template Reference
#include <pool_urbg.h>
Public Types
using result_type = T
Public Member Functions
RandenPool ()
result_type operator() ()
Static Public Member Functions
static constexpr result_type min ()
static constexpr result_type max ()
static void Fill (absl::Span< result_type > data)
Static Protected Member Functions
static result_type Generate ()
Detailed Description
template<typename T>
class absl::random_internal::RandenPool< T >
Definition at line 33 of file pool_urbg.h.
Member Typedef Documentation
result_type
template<typename T > using absl::random_internal::RandenPool< T >::result_type = T
Definition at line 35 of file pool_urbg.h.
Constructor & Destructor Documentation
RandenPool()
template<typename T > absl::random_internal::RandenPool< T >::RandenPool () inline
Definition at line 48 of file pool_urbg.h.
{}
Member Function Documentation
Fill()
template<typename T > void absl::random_internal::RandenPool< T >::Fill (absl::Span< result_type > data) static
Definition at line 240 of file pool_urbg.cc.
{
  auto* pool = GetPoolForCurrentThread();
  pool->Fill(reinterpret_cast<uint8_t*>(data.data()),
             data.size() * sizeof(result_type));
}
Referenced by absl::MakeSeedSeq().
Generate()
template<typename T > RandenPool< T >::result_type absl::random_internal::RandenPool< T >::Generate () static protected
Definition at line 234 of file pool_urbg.cc.
{
  auto* pool = GetPoolForCurrentThread();
  return pool->Generate<T>();
}
Referenced by absl::random_internal::RandenPool< T >::operator()().
max()
template<typename T > static constexpr result_type absl::random_internal::RandenPool< T >::max () inline static constexpr
Definition at line 44 of file pool_urbg.h.
{
    return (std::numeric_limits<result_type>::max)();
  }
min()
template<typename T > static constexpr result_type absl::random_internal::RandenPool< T >::min () inline static constexpr
Definition at line 40 of file pool_urbg.h.
{
    return (std::numeric_limits<result_type>::min)();
  }
operator()()
template<typename T > result_type absl::random_internal::RandenPool< T >::operator() () inline
Definition at line 51 of file pool_urbg.h.
{ return Generate(); }
References absl::random_internal::RandenPool< T >::Generate().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/random/internal/pool_urbg.h
open_spiel/abseil-cpp/absl/random/internal/pool_urbg.cc