open spiel: absl::strings_internal::Charmap Class Reference
absl::strings_internal::Charmap Class Reference
#include <char_map.h>
Public Member Functions
constexpr Charmap ()
Charmap (const char *str, int len)
Charmap (const char *str)
constexpr bool contains (unsigned char c) const
bool IntersectsWith (const Charmap &c) const
bool IsZero () const
Static Public Member Functions
static constexpr Charmap Char (char x)
static constexpr Charmap FromString (const char *s)
static constexpr Charmap Range (char lo, char hi)
Friends
constexpr Charmap operator& (const Charmap &a, const Charmap &b)
constexpr Charmap operator| (const Charmap &a, const Charmap &b)
constexpr Charmap operator~ (const Charmap &a)
Detailed Description
Definition at line 34 of file char_map.h.
Constructor & Destructor Documentation
Charmap() [1/3]
absl::strings_internal::Charmap::Charmap () inline constexpr
Definition at line 36 of file char_map.h.
: m_() {}
Referenced by Char(), and Range().
Charmap() [2/3]
absl::strings_internal::Charmap::Charmap (const char * str, int len) inline
Definition at line 40 of file char_map.h.
                                    : m_() {
    while (len--) SetChar(*str++);
  }
References len.
Charmap() [3/3]
absl::strings_internal::Charmap::Charmap (const char * str) inline explicit
Definition at line 46 of file char_map.h.
                                    : m_() {
    while (*str) SetChar(*str++);
  }
Member Function Documentation
Char()
static constexpr Charmap absl::strings_internal::Charmap::Char (char x) inline static constexpr
Definition at line 70 of file char_map.h.
{
    return Charmap(CharMaskForWord(x, 0), CharMaskForWord(x, 1),
                   CharMaskForWord(x, 2), CharMaskForWord(x, 3));
  }
References Charmap(), and absl::x.
Referenced by FromString().
contains()
bool absl::strings_internal::Charmap::contains (unsigned char c) const inline constexpr
Definition at line 50 of file char_map.h.
{
    return (m_[c / 64] >> (c % 64)) & 0x1;
  }
References absl::c.
FromString()
static constexpr Charmap absl::strings_internal::Charmap::FromString (const char * s) inline static constexpr
Definition at line 76 of file char_map.h.
{
    Charmap ret;
    while (*s) ret = ret | Char(*s++);
    return ret;
  }
References Char(), and absl::s.
Referenced by absl::strings_internal::BlankCharmap(), and absl::strings_internal::SpaceCharmap().
IntersectsWith()
bool absl::strings_internal::Charmap::IntersectsWith (const Charmap & c) const inline
Definition at line 55 of file char_map.h.
{
    for (size_t i = 0; i < ABSL_ARRAYSIZE(m_); ++i) {
      if ((m_[i] & c.m_[i]) != 0) return true;
    }
    return false;
  }
References ABSL_ARRAYSIZE, absl::c, and absl::i.
IsZero()
bool absl::strings_internal::Charmap::IsZero () const inline
Definition at line 62 of file char_map.h.
                      {
    for (uint64_t c : m_) {
      if (c != 0) return false;
    }
    return true;
  }
References absl::c.
Range()
static constexpr Charmap absl::strings_internal::Charmap::Range (char lo, char hi) inline static constexpr
Definition at line 83 of file char_map.h.
{
    return Charmap(RangeForWord(lo, hi, 0), RangeForWord(lo, hi, 1),
                   RangeForWord(lo, hi, 2), RangeForWord(lo, hi, 3));
  }
References Charmap().
Referenced by absl::strings_internal::CntrlCharmap(), absl::strings_internal::DigitCharmap(), absl::strings_internal::LowerCharmap(), absl::strings_internal::PrintCharmap(), absl::strings_internal::UpperCharmap(), and absl::strings_internal::XDigitCharmap().
Friends And Related Symbol Documentation
operator&
Charmap operator& (const Charmap & a, const Charmap & b) friend
Definition at line 88 of file char_map.h.
{
    return Charmap(a.m_[0] & b.m_[0], a.m_[1] & b.m_[1], a.m_[2] & b.m_[2],
                   a.m_[3] & b.m_[3]);
  }
operator|
Charmap operator| (const Charmap & a, const Charmap & b) friend
Definition at line 93 of file char_map.h.
{
    return Charmap(a.m_[0] | b.m_[0], a.m_[1] | b.m_[1], a.m_[2] | b.m_[2],
                   a.m_[3] | b.m_[3]);
  }
operator~
Charmap operator~ (const Charmap & a) friend
Definition at line 98 of file char_map.h.
{
    return Charmap(~a.m_[0], ~a.m_[1], ~a.m_[2], ~a.m_[3]);
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/char_map.h