open spiel: open_spiel::kuhn_poker::KuhnObserver Class Reference
open_spiel::kuhn_poker::KuhnObserver Class Reference
Public Member Functions
KuhnObserver (IIGObservationType iig_obs_type)
void WriteTensor (const State &observed_state, int player, Allocator *allocator) const override
std::string StringFrom (const State &observed_state, int player) const override
Public Member Functions inherited from open_spiel::Observer
Observer (bool has_string, bool has_tensor)
bool HasString () const
bool HasTensor () const
virtual ~Observer ()=default
Additional Inherited Members
Protected Attributes inherited from open_spiel::Observer
bool has_string_
bool has_tensor_
Detailed Description
Definition at line 66 of file kuhn_poker.cc.
Constructor & Destructor Documentation
KuhnObserver()
open_spiel::kuhn_poker::KuhnObserver::KuhnObserver (IIGObservationType iig_obs_type) inline
Definition at line 68 of file kuhn_poker.cc.
      : Observer(/*has_string=*/true, /*has_tensor=*/true),
        iig_obs_type_(iig_obs_type) {}
Member Function Documentation
StringFrom()
std::string open_spiel::kuhn_poker::KuhnObserver::StringFrom (const State & observed_state, int player) const inline override virtual
Implements open_spiel::Observer.
Definition at line 109 of file kuhn_poker.cc.
{
    const KuhnState& state =
        open_spiel::down_cast<const KuhnState&>(observed_state);
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, state.num_players_);
    std::string result;
    // Private card
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      if (iig_obs_type_.perfect_recall || iig_obs_type_.public_info) {
        if (state.history_.size() > player) {
          absl::StrAppend(&result, state.history_[player].action);
        }
      } else {
        if (state.history_.size() == 1 + player) {
          absl::StrAppend(&result, "Received card ",
                          state.history_[player].action);
        }
      }
    }
    // Betting.
    // TODO(author11) Make this more self-consistent.
    if (iig_obs_type_.public_info) {
      if (iig_obs_type_.perfect_recall) {
        // Perfect recall public info.
        for (int i = state.num_players_; i < state.history_.size(); ++i)
          result.push_back(state.history_[i].action ? 'b' : 'p');
      } else {
        // Imperfect recall public info - two different formats.
        if (iig_obs_type_.private_info == PrivateInfoType::kNone) {
          if (state.history_.empty()) {
            absl::StrAppend(&result, "start game");
          } else if (state.history_.size() > state.num_players_) {
            absl::StrAppend(&result,
                            state.history_.back().action ? "Bet" : "Pass");
          }
        } else {
          if (state.history_.size() > player) {
            for (auto p = Player{0}; p < state.num_players_; p++) {
              absl::StrAppend(&result, state.ante_[p]);
            }
          }
        }
      }
    }
    // Fact that we're dealing a card.
    if (iig_obs_type_.public_info &&
        iig_obs_type_.private_info == PrivateInfoType::kNone &&
        !state.history_.empty() &&
        state.history_.size() <= state.num_players_) {
      int currently_dealing_to_player = state.history_.size() - 1;
      absl::StrAppend(&result, "Deal to player ", currently_dealing_to_player);
    }
    return result;
  }
References open_spiel::down_cast(), i, open_spiel::kNone, open_spiel::kSinglePlayer, open_spiel::IIGObservationType::perfect_recall, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, state, and absl::StrAppend().
WriteTensor()
void open_spiel::kuhn_poker::KuhnObserver::WriteTensor (const State & observed_state, int player, Allocator * allocator) const inline override virtual
Implements open_spiel::Observer.
Definition at line 72 of file kuhn_poker.cc.
{
    const KuhnState& state =
        open_spiel::down_cast<const KuhnState&>(observed_state);
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, state.num_players_);
    const int num_players = state.num_players_;
    const int num_cards = num_players + 1;
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      {  // Observing player.
        auto out = allocator->Get("player", {num_players});
        out.at(player) = 1;
      }
      {  // The player's card, if one has been dealt.
        auto out = allocator->Get("private_card", {num_cards});
        if (state.history_.size() > player)
          out.at(state.history_[player].action) = 1;
      }
    }
    // Betting sequence.
    if (iig_obs_type_.public_info) {
      if (iig_obs_type_.perfect_recall) {
        auto out = allocator->Get("betting", {2 * num_players - 1, 2});
        for (int i = num_players; i < state.history_.size(); ++i) {
          out.at(i - num_players, state.history_[i].action) = 1;
        }
      } else {
        auto out = allocator->Get("pot_contribution", {num_players});
        for (auto p = Player{0}; p < state.num_players_; p++) {
          out.at(p) = state.ante_[p];
        }
      }
    }
  }
References open_spiel::SpanTensor::at(), open_spiel::down_cast(), open_spiel::Allocator::Get(), i, open_spiel::kSinglePlayer, out, open_spiel::IIGObservationType::perfect_recall, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and state.
The documentation for this class was generated from the following file:
open_spiel/games/kuhn_poker/kuhn_poker.cc