open spiel: open_spiel::blackjack::BlackjackState Class Reference
open_spiel::blackjack::BlackjackState Class Reference
#include <blackjack.h>
Public Member Functions
BlackjackState (const BlackjackState &)=default
BlackjackState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
ActionsAndProbs ChanceOutcomes () const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
int GetBestPlayerTotal (int player) const
int DealerId () const
int NextTurnPlayer () const
bool InitialCardsDealt (int player) const
int CardValue (int card) const
void EndPlayerTurn (int player)
void DealCardToPlayer (int player, int card)
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 37 of file blackjack.h.
Constructor & Destructor Documentation
BlackjackState() [1/2]
open_spiel::blackjack::BlackjackState::BlackjackState (const BlackjackState &) default
Referenced by Clone().
BlackjackState() [2/2]
open_spiel::blackjack::BlackjackState::BlackjackState (std::shared_ptr< const Game > game)
Definition at line 176 of file blackjack.cc.
                                                             : State(game) {
  total_moves_ = 0;
  cur_player_ = kChancePlayerId;
  turn_player_ = kPlayerId;
  live_players_ = 1;
  // The values are stored for the dealer as well, whose id is NumPlayers.
  // See DealerId().
  non_ace_total_.resize(game_->NumPlayers() + 1, 0);
  num_aces_.resize(game_->NumPlayers() + 1, 0);
  turn_over_.resize(game_->NumPlayers() + 1, false);
  cards_.resize(game_->NumPlayers() + 1);
  deck_.resize(kDeckSize);
  std::iota(deck_.begin(), deck_.end(), 0);
}
References open_spiel::State::game_, open_spiel::kChancePlayerId, and open_spiel::blackjack::kDeckSize.
Member Function Documentation
ActionToString()
std::string open_spiel::blackjack::BlackjackState::ActionToString (Player player, Action move_id) const override virtual
Implements open_spiel::State.
Definition at line 65 of file blackjack.cc.
{
  if (player == kChancePlayerId) {
    const char kSuitNames[kNumSuits + 1] = "CDHS";
    const char kRanks[kCardsPerSuit + 1] = "A23456789TJQK";
    return std::string(1, kSuitNames[move_id / kCardsPerSuit]) +
           std::string(1, kRanks[move_id % kCardsPerSuit]);
  } else if (move_id == ActionType::kHit) {
    return "Hit";
  } else {
    return "Stand";
  }
}
References open_spiel::blackjack::kCardsPerSuit, open_spiel::kChancePlayerId, open_spiel::blackjack::kNumSuits, and player.
CardValue()
int open_spiel::blackjack::BlackjackState::CardValue (int card) const
Definition at line 148 of file blackjack.cc.
{
  // Cards are indexed from 0 to kDeckSize-1;
  const int rank = card % kCardsPerSuit;
  if (rank == 0) {
    return kAceValue;
  } else if (rank <= 9) {
    return rank + 1;
  } else {
    // Ten or a face card.
    return 10;
  }
}
References open_spiel::blackjack::kCardsPerSuit, and rank.
Referenced by DealCardToPlayer().
ChanceOutcomes()
ActionsAndProbs open_spiel::blackjack::BlackjackState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 292 of file blackjack.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  ActionsAndProbs outcomes;
  outcomes.reserve(deck_.size());
  for (int card : deck_) {
    outcomes.emplace_back(card, 1.0 / deck_.size());
  }
  return outcomes;
}
References open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::blackjack::BlackjackState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 309 of file blackjack.cc.
{
  return std::unique_ptr<State>(new BlackjackState(*this));
}
References BlackjackState().
CurrentPlayer()
int open_spiel::blackjack::BlackjackState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 208 of file blackjack.cc.
{ return cur_player_; }
DealCardToPlayer()
void open_spiel::blackjack::BlackjackState::DealCardToPlayer (int player, int card)
Definition at line 161 of file blackjack.cc.
{
  // Remove card from deck.
  auto new_end = std::remove(deck_.begin(), deck_.end(), card);
  if (new_end == deck_.end()) SpielFatalError("Card not present in deck");
  deck_.erase(new_end, deck_.end());
  cards_[player].push_back(card);
  const int value = CardValue(card);
  if (value == kAceValue) {
    num_aces_[player]++;
  } else {
    non_ace_total_[player] += value;
  }
}
References CardValue(), player, open_spiel::SpielFatalError(), and value.
Referenced by DoApplyAction().
DealerId()
int open_spiel::blackjack::BlackjackState::DealerId () const
Definition at line 81 of file blackjack.cc.
{ return game_->NumPlayers(); }
References open_spiel::State::game_.
Referenced by DoApplyAction(), IsTerminal(), LegalActions(), NextTurnPlayer(), and Returns().
DoApplyAction()
void open_spiel::blackjack::BlackjackState::DoApplyAction (Action move_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 223 of file blackjack.cc.
{
  SPIEL_CHECK_EQ(IsTerminal(), false);
  if (!InitialCardsDealt(DealerId())) {
    // Still in the initial dealing phase. Deal the 'move' card to turn_player_.
    SPIEL_CHECK_EQ(IsChanceNode(), true);
    DealCardToPlayer(turn_player_, move);
    cur_player_ = kChancePlayerId;
    if (InitialCardsDealt(turn_player_)) {
      // Next player.
      turn_player_++;
      if (InitialCardsDealt(DealerId())) {
        // Hit/stand part of the game commences.
        turn_player_ = kPlayerId;
        cur_player_ = kPlayerId;
      }
    }
    return;
  }
  if (IsChanceNode()) {
    // Deal the 'move' card to turn_player_.
    DealCardToPlayer(turn_player_, move);
    cur_player_ = turn_player_;
    if (GetBestPlayerTotal(turn_player_) > kApproachScore) {
      if (turn_player_ != DealerId()) --live_players_;
      EndPlayerTurn(turn_player_);
    }
    MaybeApplyDealerAction();
    return;
  }
  total_moves_++;
  if (move == kHit) {
    cur_player_ = kChancePlayerId;
  } else if (move == kStand) {
    EndPlayerTurn(turn_player_);
    MaybeApplyDealerAction();
  }
}
References DealCardToPlayer(), DealerId(), EndPlayerTurn(), GetBestPlayerTotal(), InitialCardsDealt(), open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::kChancePlayerId, and SPIEL_CHECK_EQ.
EndPlayerTurn()
void open_spiel::blackjack::BlackjackState::EndPlayerTurn (int player)
Definition at line 217 of file blackjack.cc.
{
  turn_over_[player] = true;
  turn_player_ = NextTurnPlayer();
  cur_player_ = turn_player_;
}
References NextTurnPlayer(), and player.
Referenced by DoApplyAction().
GetBestPlayerTotal()
int open_spiel::blackjack::BlackjackState::GetBestPlayerTotal (int player) const
Definition at line 193 of file blackjack.cc.
{
  // Return the max possible total <= kApproachScore, depending on hard or soft
  // aces. 'Best' refers to the max non-bust score possible for the player.
  // If it is not possible, some value > kApproachScore is returned.
  int total = non_ace_total_[player] + num_aces_[player];
  for (int i = 1; i <= num_aces_[player]; i++) {
    int soft_total =
        non_ace_total_[player] + i * 11 + (num_aces_[player] - i) * 1;
    if (soft_total <= kApproachScore) {
      total = std::max(total, soft_total);
    }
  }
  return total;
}
References i, player, and total.
Referenced by DoApplyAction(), and Returns().
InitialCardsDealt()
bool open_spiel::blackjack::BlackjackState::InitialCardsDealt (int player) const
Definition at line 144 of file blackjack.cc.
{
  return cards_[player].size() >= kInitialCardsPerPlayer;
}
References player.
Referenced by DoApplyAction().
IsTerminal()
bool open_spiel::blackjack::BlackjackState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 79 of file blackjack.cc.
{ return turn_over_[DealerId()]; }
References DealerId().
Referenced by DoApplyAction(), LegalActions(), NextTurnPlayer(), ObservationTensor(), and Returns().
LegalActions()
std::vector< Action > open_spiel::blackjack::BlackjackState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 281 of file blackjack.cc.
{
  SPIEL_CHECK_NE(cur_player_, DealerId());
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else if (IsTerminal()) {
    return {};
  } else {
    return {kHit, kStand};
  }
}
References DealerId(), open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::State::LegalChanceOutcomes(), and SPIEL_CHECK_NE.
NextTurnPlayer()
int open_spiel::blackjack::BlackjackState::NextTurnPlayer () const
Definition at line 210 of file blackjack.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  }
  return turn_over_[kPlayerId] ? DealerId() : kPlayerId;
}
References DealerId(), IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by EndPlayerTurn().
ObservationString()
std::string open_spiel::blackjack::BlackjackState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 106 of file blackjack.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, game_->NumPlayers());
  return ToString();
}
References open_spiel::State::game_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::blackjack::BlackjackState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 112 of file blackjack.cc.
{
  std::fill(values.begin(), values.end(), 0);
  int offset = 0;
  // Whose turn is it?
  if (cur_player_ + 1 >= 0) {     // do not support kTerminalPlayerId
    values[cur_player_ + 1] = 1;  // to support kChancePlayerId (equals to -1)
  }
  offset += game_->NumPlayers() + 1;
  // Terminal?
  values[offset] = IsTerminal();
  offset += 1;
  // Number of aces for each player (incl. dealer)
  for (std::size_t player_id = 0; player_id < cards_.size(); player_id++) {
    values[offset + num_aces_[player_id]] = 1.0;
    offset += (kNumSuits + 1);
  }
  // Cards used by each player (incl. dealer)
  for (std::size_t player_id = 0; player_id < cards_.size(); player_id++) {
    for (const int& card : cards_[player_id]) {
      values[offset + card] = 1;
    }
    offset += kDeckSize;
  }
  SPIEL_CHECK_EQ(offset, values.size());
}
References open_spiel::State::game_, IsTerminal(), open_spiel::blackjack::kDeckSize, open_spiel::blackjack::kNumSuits, SPIEL_CHECK_EQ, and values.
Returns()
std::vector< double > open_spiel::blackjack::BlackjackState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 83 of file blackjack.cc.
{
  if (!IsTerminal()) {
    return {0};
  }
  int player_total = GetBestPlayerTotal(kPlayerId);
  int dealer_total = GetBestPlayerTotal(DealerId());
  if (player_total > kApproachScore) {
    // Bust.
    return {-1};
  } else if (dealer_total > kApproachScore) {
    // Bust.
    return {+1};
  } else if (player_total > dealer_total) {
    return {+1};
  } else if (player_total < dealer_total) {
    return {-1};
  } else {
    // Tie.
    return {0};
  }
}
References DealerId(), GetBestPlayerTotal(), and IsTerminal().
ToString()
std::string open_spiel::blackjack::BlackjackState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 302 of file blackjack.cc.
{
  return absl::StrCat("Non-Ace Total: ", absl::StrJoin(non_ace_total_, " "),
                      " Num Aces: ", absl::StrJoin(num_aces_, " "),
                      (cur_player_ == kChancePlayerId ? ", Chance Player\n"
                                                      : ", Player's Turn\n"));
}
References open_spiel::kChancePlayerId, absl::StrCat(), and absl::StrJoin().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/blackjack/blackjack.h
open_spiel/games/blackjack/blackjack.cc