open spiel: open_spiel::twixt::Cell Class Reference
open_spiel::twixt::Cell Class Reference
#include <twixtcell.h>
Public Member Functions
int color () const
void set_color (int color)
void set_link (int dir)
int links () const
bool HasLink (int dir) const
bool HasLinks () const
void SetBlockedNeighbor (int dir)
bool HasBlockedNeighbors () const
bool HasBlockedNeighborsEast () const
Position GetNeighbor (int dir) const
void SetNeighbor (int dir, Position c)
void SetLinkedToBorder (int player, int border)
bool IsLinkedToBorder (int player, int border) const
Detailed Description
Definition at line 65 of file twixtcell.h.
Member Function Documentation
color()
int open_spiel::twixt::Cell::color () const inline
Definition at line 67 of file twixtcell.h.
{ return color_; }
Referenced by open_spiel::twixt::TwixTState::ObservationTensor(), and set_color().
GetNeighbor()
Position open_spiel::twixt::Cell::GetNeighbor (int dir) const inline
Definition at line 81 of file twixtcell.h.
{ return neighbors_[dir]; }
References dir.
HasBlockedNeighbors()
bool open_spiel::twixt::Cell::HasBlockedNeighbors () const inline
Definition at line 76 of file twixtcell.h.
{ return blocked_neighbors_ > 0; }
HasBlockedNeighborsEast()
bool open_spiel::twixt::Cell::HasBlockedNeighborsEast () const inline
Definition at line 77 of file twixtcell.h.
{
    return (blocked_neighbors_ & 15UL) > 0;
  }
HasLink()
bool open_spiel::twixt::Cell::HasLink (int dir) const inline
Definition at line 72 of file twixtcell.h.
{ return links_ & (1UL << dir); }
References dir.
HasLinks()
bool open_spiel::twixt::Cell::HasLinks () const inline
Definition at line 73 of file twixtcell.h.
{ return links_ > 0; }
IsLinkedToBorder()
bool open_spiel::twixt::Cell::IsLinkedToBorder (int player, int border) const inline
Definition at line 88 of file twixtcell.h.
{
    return linked_to_border_[player][border];
  }
References player.
links()
int open_spiel::twixt::Cell::links () const inline
Definition at line 70 of file twixtcell.h.
{ return links_; }
set_color()
void open_spiel::twixt::Cell::set_color (int color) inline
Definition at line 68 of file twixtcell.h.
{ color_ = color; }
References color().
set_link()
void open_spiel::twixt::Cell::set_link (int dir) inline
Definition at line 69 of file twixtcell.h.
{ links_ |= (1UL << dir); }
References dir.
SetBlockedNeighbor()
void open_spiel::twixt::Cell::SetBlockedNeighbor (int dir) inline
Definition at line 75 of file twixtcell.h.
{ blocked_neighbors_ |= (1UL << dir); }
References dir.
SetLinkedToBorder()
void open_spiel::twixt::Cell::SetLinkedToBorder (int player, int border) inline
Definition at line 84 of file twixtcell.h.
{
    linked_to_border_[player][border] = true;
  }
References player.
SetNeighbor()
void open_spiel::twixt::Cell::SetNeighbor (int dir, Position c) inline
Definition at line 82 of file twixtcell.h.
{ neighbors_[dir] = c; }
References dir.
The documentation for this class was generated from the following file:
open_spiel/games/twixt/twixtcell.h