open spiel: open_spiel::twixt::TwixTGame Class Reference
open_spiel::twixt::TwixTGame Class Reference
#include <twixt.h>
Public Member Functions
TwixTGame (const GameParameters &params)
std::unique_ptr< State > NewInitialState () const override
int NumDistinctActions () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const
bool ansi_color_output () const
int board_size () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 113 of file twixt.h.
Constructor & Destructor Documentation
TwixTGame()
open_spiel::twixt::TwixTGame::TwixTGame (const GameParameters & params) explicit
Definition at line 132 of file twixt.cc.
    : Game(kGameType, params),
      ansi_color_output_(
          ParameterValue<bool>("ansi_color_output", kDefaultAnsiColorOutput)),
      board_size_(ParameterValue<int>("board_size", kDefaultBoardSize)) {
  if (board_size_ < kMinBoardSize || board_size_ > kMaxBoardSize) {
    SpielFatalError(
        "board_size out of range [" + std::to_string(kMinBoardSize) + ".." +
        std::to_string(kMaxBoardSize) + "]: " + std::to_string(board_size_));
  }
}
References open_spiel::twixt::kMaxBoardSize, open_spiel::twixt::kMinBoardSize, and open_spiel::SpielFatalError().
Member Function Documentation
ansi_color_output()
bool open_spiel::twixt::TwixTGame::ansi_color_output () const inline
Definition at line 137 of file twixt.h.
{ return ansi_color_output_; }
Referenced by open_spiel::twixt::TwixTState::TwixTState().
board_size()
int open_spiel::twixt::TwixTGame::board_size () const inline
Definition at line 138 of file twixt.h.
{ return board_size_; }
Referenced by open_spiel::twixt::TwixTState::TwixTState().
MaxGameLength()
int open_spiel::twixt::TwixTGame::MaxGameLength () const inline virtual
Implements open_spiel::Game.
Definition at line 133 of file twixt.h.
{
    // square - 4 corners + swap move
    return board_size_ * board_size_ - 4 + 1;
  }
MaxUtility()
double open_spiel::twixt::TwixTGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 126 of file twixt.h.
{ return 1.0; };
MinUtility()
double open_spiel::twixt::TwixTGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 124 of file twixt.h.
{ return -1.0; };
NewInitialState()
std::unique_ptr< State > open_spiel::twixt::TwixTGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 117 of file twixt.h.
{
    return std::unique_ptr<State>(new TwixTState(shared_from_this()));
  };
NumDistinctActions()
int open_spiel::twixt::TwixTGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 121 of file twixt.h.
{ return board_size_ * board_size_; };
NumPlayers()
int open_spiel::twixt::TwixTGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 123 of file twixt.h.
{ return kNumPlayers; };
References open_spiel::twixt::kNumPlayers.
ObservationTensorShape()
std::vector< int > open_spiel::twixt::TwixTGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 128 of file twixt.h.
{
    static std::vector<int> shape{kNumPlanes, board_size_, board_size_ - 2};
    return shape;
  }
References open_spiel::twixt::kNumPlanes.
UtilitySum()
absl::optional< double > open_spiel::twixt::TwixTGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 125 of file twixt.h.
{ return 0.0; };
The documentation for this class was generated from the following files:
open_spiel/games/twixt/twixt.h
open_spiel/games/twixt/twixt.cc