open spiel: absl::types_internal::ConformanceErrors Class Reference
absl::types_internal::ConformanceErrors Class Reference
#include <conformance_profile.h>
Public Member Functions
ConformanceErrors (std::string type_name)
void addTestSuccess (absl::string_view test_name)
template<class... P>
void addTestFailure (absl::string_view test_name, const P &... args)
::testing::AssertionResult assertionResult () const
::testing::AssertionResult expectFailedTests (const std::set< std::string > &test_names) const
Detailed Description
Definition at line 72 of file conformance_profile.h.
Constructor & Destructor Documentation
ConformanceErrors()
absl::types_internal::ConformanceErrors::ConformanceErrors (std::string type_name) inline explicit
Definition at line 76 of file conformance_profile.h.
      : assertion_result_(false), type_name_(std::move(type_name)) {
    assertion_result_ << "\n\n"
                         "Assuming the following type alias:\n"
                         "\n"
                         "  using _T = "
                      << type_name_ << ";\n\n";
    outputDivider();
  }
Member Function Documentation
addTestFailure()
template<class... P> void absl::types_internal::ConformanceErrors::addTestFailure (absl::string_view test_name, const P &... args) inline
Definition at line 108 of file conformance_profile.h.
{
    // Output a message related to the test failure.
    assertion_result_ << "\n\n"
                         "Failed test: "
                      << test_name << "\n\n";
    addTestFailureImpl(args...);
    assertion_result_ << "\n\n";
    outputDivider();
    auto normalized_test_name = absl::AsciiStrToLower(test_name);
    // If previous parts of this test succeeded, remove it from that set.
    test_successes_.erase(normalized_test_name);
    // Add the test name to the list of failed tests.
    test_failures_.insert(std::move(normalized_test_name));
    has_error_ = true;
  }
References absl::AsciiStrToLower().
Referenced by absl::types_internal::ExpectModelOfImpl(), and absl::types_internal::ExpectSameHash::operator()().
addTestSuccess()
void absl::types_internal::ConformanceErrors::addTestSuccess (absl::string_view test_name) inline
Definition at line 90 of file conformance_profile.h.
{
    auto normalized_test_name = absl::AsciiStrToLower(test_name);
    // If the test is already reported as failing, do not add it to the list of
    // successes.
    if (test_failures_.find(normalized_test_name) == test_failures_.end()) {
      test_successes_.insert(std::move(normalized_test_name));
    }
  }
References absl::AsciiStrToLower().
Referenced by absl::types_internal::ExpectModelOfImpl(), absl::types_internal::ExpectDefaultConstructWithDestruct< T >::operator()(), and absl::types_internal::ExpectSameHash::operator()().
assertionResult()
::testing::AssertionResult absl::types_internal::ConformanceErrors::assertionResult () const inline
Definition at line 130 of file conformance_profile.h.
{
    return has_error_ ? assertion_result_ : ::testing::AssertionSuccess();
  }
Referenced by absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_loose_profile(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_strict_profile().
expectFailedTests()
::testing::AssertionResult absl::types_internal::ConformanceErrors::expectFailedTests (const std::set< std::string > & test_names) const inline
Definition at line 137 of file conformance_profile.h.
{
    // Since we are expecting nonconformance, output an error message when the
    // type actually conformed to the specified profile.
    if (!has_error_) {
      return ::testing::AssertionFailure()
             << "Unexpected conformance of type:\n"
                "    "
             << type_name_ << "\n\n";
    }
    // Get a list of all expected failures that did not actually fail
    // (or that were not run).
    std::vector<std::string> nonfailing_tests;
    absl::c_set_difference(test_names, test_failures_,
                           std::back_inserter(nonfailing_tests));
    // Get a list of all "expected failures" that were never actually run.
    std::vector<std::string> unrun_tests;
    absl::c_set_difference(nonfailing_tests, test_successes_,
                           std::back_inserter(unrun_tests));
    // Report when the user specified tests that were not run.
    if (!unrun_tests.empty()) {
      const bool tests_were_run =
          !(test_failures_.empty() && test_successes_.empty());
      // Prepare an assertion result used in the case that tests pass that were
      // expected to fail.
      ::testing::AssertionResult result = ::testing::AssertionFailure();
      result << "When testing type:\n    " << type_name_
             << "\n\nThe following tests were expected to fail but were not "
                "run";
      if (tests_were_run) result << " (was the test name spelled correctly?)";
      result << ":\n\n";
      // List all of the tests that unexpectedly passed.
      for (const auto& test_name : unrun_tests) {
        result << "    " << test_name << "\n";
      }
      if (!tests_were_run) result << "\nNo tests were run.";
      if (!test_failures_.empty()) {
        // List test failures
        result << "\nThe tests that were run and failed are:\n\n";
        for (const auto& test_name : test_failures_) {
          result << "    " << test_name << "\n";
        }
      }
      if (!test_successes_.empty()) {
        // List test successes
        result << "\nThe tests that were run and succeeded are:\n\n";
        for (const auto& test_name : test_successes_) {
          result << "    " << test_name << "\n";
        }
      }
      return result;
    }
    // If some tests passed when they were expected to fail, alert the caller.
    if (nonfailing_tests.empty()) return ::testing::AssertionSuccess();
    // Prepare an assertion result used in the case that tests pass that were
    // expected to fail.
    ::testing::AssertionResult unexpected_successes =
        ::testing::AssertionFailure();
    unexpected_successes << "When testing type:\n    " << type_name_
                         << "\n\nThe following tests passed when they were "
                            "expected to fail:\n\n";
    // List all of the tests that unexpectedly passed.
    for (const auto& test_name : nonfailing_tests) {
      unexpected_successes << "    " << test_name << "\n";
    }
    return unexpected_successes;
  }
References absl::c_set_difference().
Referenced by absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_loose_profile(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_strict_profile().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/types/internal/conformance_profile.h