open spiel: absl::CordzSamplingIntervalHelper Class Reference
absl::CordzSamplingIntervalHelper Class Reference
#include <cordz_test_helpers.h>
Public Member Functions
CordzSamplingIntervalHelper (int32_t interval)
~CordzSamplingIntervalHelper ()
Detailed Description
Definition at line 103 of file cordz_test_helpers.h.
Constructor & Destructor Documentation
CordzSamplingIntervalHelper()
absl::CordzSamplingIntervalHelper::CordzSamplingIntervalHelper (int32_t interval) inline explicit
Definition at line 105 of file cordz_test_helpers.h.
      : orig_mean_interval_(absl::cord_internal::get_cordz_mean_interval()) {
    absl::cord_internal::set_cordz_mean_interval(interval);
    absl::cord_internal::cordz_set_next_sample_for_testing(interval);
  }
References absl::cord_internal::cordz_set_next_sample_for_testing(), and absl::cord_internal::set_cordz_mean_interval().
~CordzSamplingIntervalHelper()
absl::CordzSamplingIntervalHelper::~CordzSamplingIntervalHelper () inline
Definition at line 111 of file cordz_test_helpers.h.
{
    absl::cord_internal::set_cordz_mean_interval(orig_mean_interval_);
    absl::cord_internal::cordz_set_next_sample_for_testing(orig_mean_interval_);
  }
References absl::cord_internal::cordz_set_next_sample_for_testing(), and absl::cord_internal::set_cordz_mean_interval().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/cordz_test_helpers.h