open spiel: open_spiel::euchre::EuchreState Class Reference
open_spiel::euchre::EuchreState Class Reference
#include <euchre.h>
Public Member Functions
EuchreState (std::shared_ptr< const Game > game, bool allow_lone_defender, bool stick_the_dealer)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
int NumCardsDealt () const
int NumCardsPlayed () const
int NumPasses () const
int Upcard () const
int Discard () const
int TrumpSuit () const
int LeftBower () const
int RightBower () const
int Declarer () const
int FirstDefender () const
int DeclarerPartner () const
int SecondDefender () const
absl::optional< bool > DeclarerGoAlone () const
Player LoneDefender () const
std::vector< bool > ActivePlayers () const
Player Dealer () const
Phase CurrentPhase () const
int CurrentTrickIndex () const
Trick & CurrentTrick ()
const Trick & CurrentTrick () const
std::array< absl::optional< Player >, kNumCards > CardHolder () const
std::vector< Trick > Tricks () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
virtual std::string ObservationString (Player player) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 126 of file euchre.h.
Constructor & Destructor Documentation
EuchreState()
open_spiel::euchre::EuchreState::EuchreState (std::shared_ptr< const Game > game, bool allow_lone_defender, bool stick_the_dealer)
Definition at line 92 of file euchre.cc.
    : State(game),
      allow_lone_defender_(allow_lone_defender),
      stick_the_dealer_(stick_the_dealer) {}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::euchre::EuchreState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 98 of file euchre.cc.
{
  if (history_.empty()) return DirString(action);
  if (action == kPassAction) return "Pass";
  if (action == kClubsTrumpAction) return "Clubs";
  if (action == kDiamondsTrumpAction) return "Diamonds";
  if (action == kHeartsTrumpAction) return "Hearts";
  if (action == kSpadesTrumpAction) return "Spades";
  if (action == kGoAloneAction) return "Alone";
  if (action == kPlayWithPartnerAction) return "Partner";
  return CardString(action);
}
References action, open_spiel::euchre::CardString(), open_spiel::euchre::DirString(), open_spiel::State::history_, open_spiel::euchre::kClubsTrumpAction, open_spiel::euchre::kDiamondsTrumpAction, open_spiel::euchre::kGoAloneAction, open_spiel::euchre::kHeartsTrumpAction, open_spiel::euchre::kPassAction, open_spiel::euchre::kPlayWithPartnerAction, and open_spiel::euchre::kSpadesTrumpAction.
Referenced by ToString().
ActivePlayers()
std::vector< bool > open_spiel::euchre::EuchreState::ActivePlayers () const inline
Definition at line 157 of file euchre.h.
{ return active_players_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
CardHolder()
std::array< absl::optional< Player >, kNumCards > open_spiel::euchre::EuchreState::CardHolder () const inline
Definition at line 169 of file euchre.h.
{
    return holder_;
  }
Referenced by open_spiel::init_pyspiel_games_euchre().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::euchre::EuchreState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 463 of file euchre.cc.
{
  std::vector<std::pair<Action, double>> outcomes;
  if (history_.empty()) {
    outcomes.reserve(kNumPlayers);
    const double p = 1.0 / kNumPlayers;
    for (int dir = 0; dir < kNumPlayers; ++dir) {
      outcomes.emplace_back(dir, p);
    }
    return outcomes;
  }
  int num_cards_remaining = kNumCards - num_cards_dealt_;
  outcomes.reserve(num_cards_remaining);
  const double p = 1.0 / num_cards_remaining;
  for (int card = 0; card < kNumCards; ++card) {
    if (!holder_[card].has_value()) outcomes.emplace_back(card, p);
  }
  return outcomes;
}
References dir, open_spiel::State::history_, open_spiel::euchre::kNumCards, and open_spiel::euchre::kNumPlayers.
Clone()
std::unique_ptr< State > open_spiel::euchre::EuchreState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 137 of file euchre.h.
{
    return std::unique_ptr<State>(new EuchreState(*this));
  }
References EuchreState().
CurrentPhase()
Phase open_spiel::euchre::EuchreState::CurrentPhase () const inline
Definition at line 160 of file euchre.h.
{ return phase_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
CurrentPlayer()
Player open_spiel::euchre::EuchreState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 130 of file euchre.h.
{ return current_player_; }
CurrentTrick() [1/2]
Trick & open_spiel::euchre::EuchreState::CurrentTrick () inline
Definition at line 166 of file euchre.h.
{ return tricks_[CurrentTrickIndex()]; }
References CurrentTrickIndex().
Referenced by open_spiel::init_pyspiel_games_euchre().
CurrentTrick() [2/2]
const Trick & open_spiel::euchre::EuchreState::CurrentTrick () const inline
Definition at line 167 of file euchre.h.
{ return tricks_[CurrentTrickIndex()]; }
References CurrentTrickIndex().
CurrentTrickIndex()
int open_spiel::euchre::EuchreState::CurrentTrickIndex () const inline
Definition at line 162 of file euchre.h.
{
    return std::min(num_cards_played_ / num_active_players_,
                    static_cast<int>(tricks_.size()));
  }
Referenced by CurrentTrick(), CurrentTrick(), and open_spiel::init_pyspiel_games_euchre().
Dealer()
Player open_spiel::euchre::EuchreState::Dealer () const inline
Definition at line 158 of file euchre.h.
{ return dealer_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
Declarer()
int open_spiel::euchre::EuchreState::Declarer () const inline
Definition at line 151 of file euchre.h.
{ return declarer_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
DeclarerGoAlone()
absl::optional< bool > open_spiel::euchre::EuchreState::DeclarerGoAlone () const inline
Definition at line 155 of file euchre.h.
{ return declarer_go_alone_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
DeclarerPartner()
int open_spiel::euchre::EuchreState::DeclarerPartner () const inline
Definition at line 153 of file euchre.h.
{ return declarer_partner_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
Discard()
int open_spiel::euchre::EuchreState::Discard () const inline
Definition at line 147 of file euchre.h.
{ return discard_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
DoApplyAction()
void open_spiel::euchre::EuchreState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 482 of file euchre.cc.
{
  switch (phase_) {
    case Phase::kDealerSelection:
      return ApplyDealerSelectionAction(action);
    case Phase::kDeal:
      return ApplyDealAction(action);
    case Phase::kBidding:
      return ApplyBiddingAction(action);
    case Phase::kDiscard:
      return ApplyDiscardAction(action);
    case Phase::kGoAlone:
      return ApplyGoAloneAction(action);
    case Phase::kPlay:
      return ApplyPlayAction(action);
    case Phase::kGameOver:
      SpielFatalError("Cannot act in terminal states");
  }
}
References action, open_spiel::euchre::kBidding, open_spiel::euchre::kDeal, open_spiel::euchre::kDealerSelection, open_spiel::euchre::kDiscard, open_spiel::euchre::kGameOver, open_spiel::euchre::kGoAlone, open_spiel::euchre::kPlay, and open_spiel::SpielFatalError().
FirstDefender()
int open_spiel::euchre::EuchreState::FirstDefender () const inline
Definition at line 152 of file euchre.h.
{ return first_defender_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
InformationStateTensor()
void open_spiel::euchre::EuchreState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 240 of file euchre.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::fill(values.begin(), values.end(), 0.0);
  SPIEL_CHECK_EQ(values.size(), kInformationStateTensorSize);
  if (upcard_ == kInvalidAction) return;
  auto ptr = values.begin();
  // Dealer position
  ptr[static_cast<int>(dealer_)] = 1;
  ptr += kNumPlayers;
  // Upcard
  ptr[upcard_] = 1;
  ptr += kNumCards;
  // Bidding [Clubs, Diamonds, Hearts, Spades, Pass]
  for (int i = 0; i < num_passes_; ++i) {
    ptr[kNumSuits + 1] = 1;
    ptr += (kNumSuits + 1);
  }
  if (num_passes_ == 2 * kNumPlayers) return;
  if (trump_suit_ != Suit::kInvalidSuit) {
    ptr[static_cast<int>(trump_suit_)] = 1;
  }
  ptr += (kNumSuits + 1);
  for (int i = 0; i < 2 * kNumPlayers - num_passes_ - 1; ++i)
    ptr += (kNumSuits + 1);
  // Go alone
  if (declarer_go_alone_) ptr[0] = 1;
  if (lone_defender_ == first_defender_) ptr[1] = 1;
  if (lone_defender_ == second_defender_) ptr[2] = 1;
  ptr += 3;
  // Current hand
  for (int i = 0; i < kNumCards; ++i)
    if (holder_[i] == player) ptr[i] = 1;
  ptr += kNumCards;
  // History of tricks, presented in the format: N E S W N E S
  int current_trick = std::min(num_cards_played_ / num_active_players_,
                               static_cast<int>(tricks_.size() - 1));
  for (int i = 0; i < current_trick; ++i) {
    Player leader = tricks_[i].Leader();
    ptr += leader * kNumCards;
    int offset = 0;
    for (auto card : tricks_[i].Cards()) {
      ptr[card] = 1;
      ptr += kNumCards;
      ++offset;
      while (!active_players_[(leader + offset) % kNumPlayers]) {
        ptr += kNumCards;
        ++offset;
      }
    }
    SPIEL_CHECK_EQ(offset, kNumPlayers);
    ptr += (kNumPlayers - leader - 1) * kNumCards;
  }
  Player leader = tricks_[current_trick].Leader();
  int offset = 0;
  if (leader != kInvalidPlayer) {
    auto cards = tricks_[current_trick].Cards();
    ptr += leader * kNumCards;
    for (auto card : cards) {
      ptr[card] = 1;
      ptr += kNumCards;
      ++offset;
      while (!active_players_[(leader + offset) % kNumPlayers]) {
        ptr += kNumCards;
        ++offset;
      }
    }
  }
  // Current trick may contain less than four cards.
  if (offset < kNumPlayers) {
    ptr += (kNumPlayers - offset) * kNumCards;
  }
  // Move to the end of current trick.
  ptr += (kNumPlayers - std::max(leader, 0) - 1) * kNumCards;
  // Skip over unplayed tricks.
  ptr += (kNumTricks - current_trick - 1) * kTrickTensorSize;
  SPIEL_CHECK_EQ(ptr, values.end());
}
References i, open_spiel::euchre::kInformationStateTensorSize, open_spiel::kInvalidAction, open_spiel::kInvalidPlayer, open_spiel::euchre::kInvalidSuit, open_spiel::euchre::kNumCards, open_spiel::euchre::kNumPlayers, open_spiel::euchre::kNumSuits, open_spiel::euchre::kNumTricks, open_spiel::euchre::kTrickTensorSize, open_spiel::State::num_players_, player, ptr, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::euchre::EuchreState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 133 of file euchre.h.
{ return phase_ == Phase::kGameOver; }
References open_spiel::euchre::kGameOver.
LeftBower()
int open_spiel::euchre::EuchreState::LeftBower () const inline
Definition at line 149 of file euchre.h.
{ return left_bower_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
LegalActions()
std::vector< Action > open_spiel::euchre::EuchreState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 321 of file euchre.cc.
{
  switch (phase_) {
    case Phase::kDealerSelection:
      return DealerSelectionLegalActions();
    case Phase::kDeal:
      return DealLegalActions();
    case Phase::kBidding:
      return BiddingLegalActions();
    case Phase::kDiscard:
      return DiscardLegalActions();
    case Phase::kGoAlone:
      return GoAloneLegalActions();
    case Phase::kPlay:
      return PlayLegalActions();
    default:
      return {};
  }
}
References open_spiel::euchre::kBidding, open_spiel::euchre::kDeal, open_spiel::euchre::kDealerSelection, open_spiel::euchre::kDiscard, open_spiel::euchre::kGoAlone, and open_spiel::euchre::kPlay.
LoneDefender()
Player open_spiel::euchre::EuchreState::LoneDefender () const inline
Definition at line 156 of file euchre.h.
{ return lone_defender_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
NumCardsDealt()
int open_spiel::euchre::EuchreState::NumCardsDealt () const inline
Definition at line 143 of file euchre.h.
{ return num_cards_dealt_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
NumCardsPlayed()
int open_spiel::euchre::EuchreState::NumCardsPlayed () const inline
Definition at line 144 of file euchre.h.
{ return num_cards_played_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
NumPasses()
int open_spiel::euchre::EuchreState::NumPasses () const inline
Definition at line 145 of file euchre.h.
{ return num_passes_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
Returns()
std::vector< double > open_spiel::euchre::EuchreState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 134 of file euchre.h.
{ return points_; }
RightBower()
int open_spiel::euchre::EuchreState::RightBower () const inline
Definition at line 150 of file euchre.h.
{ return right_bower_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
SecondDefender()
int open_spiel::euchre::EuchreState::SecondDefender () const inline
Definition at line 154 of file euchre.h.
{ return second_defender_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
ToString()
std::string open_spiel::euchre::EuchreState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 110 of file euchre.cc.
{
  std::string rv = "Dealer: ";
  absl::StrAppend(&rv, DirString(dealer_), "\n\n");
  absl::StrAppend(&rv, FormatDeal());
  if (upcard_ != kInvalidAction)
    absl::StrAppend(&rv, "\nUpcard: ", ActionToString(kInvalidPlayer, upcard_));
  if (history_.size() > kFirstBiddingActionInHistory)
    absl::StrAppend(&rv, FormatBidding());
  if (discard_ != kInvalidAction) {
    absl::StrAppend(&rv, "\nDealer discard: ",
                    ActionToString(kInvalidPlayer, discard_), "\n");
  }
  if (declarer_go_alone_.has_value()) {
    absl::StrAppend(&rv, "\nDeclarer go alone: ");
    if (declarer_go_alone_.value())
      absl::StrAppend(&rv, "true\n");
    else
      absl::StrAppend(&rv, "false\n");
    if (allow_lone_defender_) {
      absl::StrAppend(&rv, "\nDefender go alone: ");
      if (lone_defender_ != kInvalidPlayer)
        absl::StrAppend(&rv, "true\n");
      else
        absl::StrAppend(&rv, "false\n");
    }
  }
  if (num_cards_played_ > 0) absl::StrAppend(&rv, FormatPlay(), FormatPoints());
  return rv;
}
References ActionToString(), open_spiel::euchre::DirString(), absl::optional< T >::has_value(), open_spiel::State::history_, open_spiel::euchre::kFirstBiddingActionInHistory, open_spiel::kInvalidAction, open_spiel::kInvalidPlayer, absl::StrAppend(), and absl::optional< T >::value().
Tricks()
std::vector< Trick > open_spiel::euchre::EuchreState::Tricks () const
Definition at line 679 of file euchre.cc.
{
  return std::vector<Trick>(tricks_.begin(), tricks_.end());
}
Referenced by open_spiel::init_pyspiel_games_euchre().
TrumpSuit()
int open_spiel::euchre::EuchreState::TrumpSuit () const inline
Definition at line 148 of file euchre.h.
{ return static_cast<int>(trump_suit_); }
Referenced by open_spiel::init_pyspiel_games_euchre().
Upcard()
int open_spiel::euchre::EuchreState::Upcard () const inline
Definition at line 146 of file euchre.h.
{ return upcard_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
The documentation for this class was generated from the following files:
open_spiel/games/euchre/euchre.h
open_spiel/games/euchre/euchre.cc