open spiel: open_spiel::algorithms::EFCCEState Class Reference
open_spiel::algorithms::EFCCEState Class Reference
#include <efcce.h>
Public Member Functions
EFCCEState (std::shared_ptr< const Game > game, std::unique_ptr< State > state, CorrDistConfig config, const CorrelationDevice &mu, Action follow_action, Action defect_action)
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalChanceOutcomes () const override
Player CurrentPlayer () const override
ActionsAndProbs ChanceOutcomes () const override
std::vector< Action > LegalActions () const override
std::string InformationStateString (Player player) const override
std::string ToString () const override
bool HasDefected (Player player) const
Public Member Functions inherited from open_spiel::WrappedState
WrappedState (std::shared_ptr< const Game > game, std::unique_ptr< State > state)
WrappedState (const WrappedState &other)
Player CurrentPlayer () const override
std::vector< Action > LegalActions (Player player) const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
void UndoAction (Player player, Action action) override
ActionsAndProbs ChanceOutcomes () const override
std::vector< Action > LegalChanceOutcomes () const override
const State & GetWrappedState () const
std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
Action CurRecommendation () const
void DoApplyAction (Action action_id) override
Protected Member Functions inherited from open_spiel::WrappedState
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &actions) override
Additional Inherited Members
Protected Attributes inherited from open_spiel::WrappedState
std::unique_ptr< State > state_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 37 of file efcce.h.
Constructor & Destructor Documentation
EFCCEState()
open_spiel::algorithms::EFCCEState::EFCCEState (std::shared_ptr< const Game > game, std::unique_ptr< State > state, CorrDistConfig config, const CorrelationDevice & mu, Action follow_action, Action defect_action)
Definition at line 23 of file efcce.cc.
    : WrappedState(game, std::move(state)),
      config_(config),
      mu_(mu),
      follow_action_(follow_action),
      defect_action_(defect_action),
      rec_index_(-1),
      defected_(game->NumPlayers(), 0),
      recommendation_seq_(game->NumPlayers(), std::vector<Action>({})) {}
Member Function Documentation
ChanceOutcomes()
ActionsAndProbs open_spiel::algorithms::EFCCEState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 45 of file efcce.cc.
{
  if (rec_index_ < 0) {
    ActionsAndProbs outcomes;
    for (int i = 0; i < mu_.size(); ++i) {
      outcomes.push_back({i, mu_[i].first});
    }
    return outcomes;
  } else {
    return state_->ChanceOutcomes();
  }
}
References i, and open_spiel::WrappedState::state_.
Clone()
std::unique_ptr< State > open_spiel::algorithms::EFCCEState::Clone () const inline override virtual
Implements open_spiel::WrappedState.
Definition at line 43 of file efcce.h.
{
    return std::make_unique<EFCCEState>(*this);
  }
CurRecommendation()
Action open_spiel::algorithms::EFCCEState::CurRecommendation () const protected
Definition at line 104 of file efcce.cc.
{
  ActionsAndProbs actions_and_probs =
      mu_[rec_index_].second.GetStatePolicy(state_->InformationStateString());
  Action rec_action = GetAction(actions_and_probs);
  SPIEL_CHECK_TRUE(rec_action != kInvalidAction);
  return rec_action;
}
References actions_and_probs, open_spiel::GetAction(), open_spiel::kInvalidAction, SPIEL_CHECK_TRUE, and open_spiel::WrappedState::state_.
Referenced by DoApplyAction().
CurrentPlayer()
Player open_spiel::algorithms::EFCCEState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 36 of file efcce.cc.
{
  // Only override this in the first chance actions.
  if (rec_index_ < 0) {
    return kChancePlayerId;
  } else {
    return state_->CurrentPlayer();
  }
}
References open_spiel::kChancePlayerId, and open_spiel::WrappedState::state_.
Referenced by DoApplyAction(), LegalActions(), and ToString().
DoApplyAction()
void open_spiel::algorithms::EFCCEState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 112 of file efcce.cc.
{
  if (rec_index_ < 0) {
    // Pick the joint policy which will provide recommendations.
    rec_index_ = action_id;
    SPIEL_CHECK_LT(rec_index_, mu_.size());
  } else if (state_->IsChanceNode()) {
    // Regular chance node
    state_->ApplyAction(action_id);
  } else {
    Player cur_player = CurrentPlayer();
    SPIEL_CHECK_GE(cur_player, 0);
    SPIEL_CHECK_LT(cur_player, game_->NumPlayers());
    if (!HasDefected(cur_player)) {
      // Can only submit these two actions.
      SPIEL_CHECK_TRUE(action_id == follow_action_ ||
                       action_id == defect_action_);
      // Check for defection at this point. This is because the
      // recommendations
      Action recommendation = CurRecommendation();
      if (action_id == follow_action_) {
        // Follow recommendation.
        std::vector<Action> legal_actions = state_->LegalActions();
        SPIEL_CHECK_TRUE(absl::c_find(legal_actions, recommendation) !=
                         legal_actions.end());
        state_->ApplyAction(recommendation);
        recommendation_seq_[cur_player].push_back(recommendation);
      } else {
        // Defect.
        defected_[cur_player] = 1;
      }
    } else {
      // Regular game from here on.
      state_->ApplyAction(action_id);
    }
  }
}
References absl::c_find(), CurRecommendation(), CurrentPlayer(), open_spiel::State::game_, HasDefected(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, and open_spiel::WrappedState::state_.
HasDefected()
bool open_spiel::algorithms::EFCCEState::HasDefected (Player player) const
Definition at line 98 of file efcce.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, game_->NumPlayers());
  return defected_[player] == 1;
}
References open_spiel::State::game_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Referenced by DoApplyAction(), InformationStateString(), and LegalActions().
InformationStateString()
std::string open_spiel::algorithms::EFCCEState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 76 of file efcce.cc.
{
  // should look like <infoset string> <delimiter> <defected? true | false>
  // <recommendation sequence, (excluding current recommendation)>
  std::string rec_str = absl::StrJoin(recommendation_seq_[player], ",");
  std::string infoset_str = state_->InformationStateString(player);
  SPIEL_CHECK_EQ(infoset_str.find(config_.recommendation_delimiter),
                 std::string::npos);
  return absl::StrCat(infoset_str, config_.recommendation_delimiter,
                      HasDefected(player) ? "true " : "false ", rec_str);
}
References HasDefected(), player, open_spiel::algorithms::CorrDistConfig::recommendation_delimiter, SPIEL_CHECK_EQ, open_spiel::WrappedState::state_, absl::StrCat(), and absl::StrJoin().
LegalActions()
std::vector< Action > open_spiel::algorithms::EFCCEState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 57 of file efcce.cc.
{
  SPIEL_CHECK_FALSE(IsSimultaneousNode());
  if (IsTerminal()) {
    return {};
  } else if (IsChanceNode()) {
    return LegalChanceOutcomes();
  }
  if (!HasDefected(CurrentPlayer())) {
    // If the player has not defected then they have exactly two choices:
    // follow or defect.
    return {follow_action_, defect_action_};
  } else {
    // Player has defected.. they are on their own.
    return state_->LegalActions();
  }
}
References CurrentPlayer(), HasDefected(), open_spiel::State::IsChanceNode(), open_spiel::State::IsSimultaneousNode(), open_spiel::WrappedState::IsTerminal(), LegalChanceOutcomes(), SPIEL_CHECK_FALSE, and open_spiel::WrappedState::state_.
LegalChanceOutcomes()
std::vector< Action > open_spiel::algorithms::EFCCEState::LegalChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 50 of file efcce.h.
{
    return State::LegalChanceOutcomes();
  }
References open_spiel::State::LegalChanceOutcomes().
Referenced by LegalActions().
ToString()
std::string open_spiel::algorithms::EFCCEState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 87 of file efcce.cc.
{
  std::string state_str = absl::StrFormat(
      "%s\nCur player: %i\nRec index %i\nDefected %s", state_->ToString(),
      CurrentPlayer(), rec_index_, absl::StrJoin(defected_, " "));
  for (Player p = 0; p < state_->NumPlayers(); ++p) {
    absl::StrAppend(&state_str, "\nPlayer ", p, " recommendation seq: ",
                    absl::StrJoin(recommendation_seq_[p], ","));
  }
  return state_str;
}
References CurrentPlayer(), open_spiel::WrappedState::state_, absl::StrAppend(), absl::StrFormat(), and absl::StrJoin().
The documentation for this class was generated from the following files:
open_spiel/algorithms/corr_dist/efcce.h
open_spiel/algorithms/corr_dist/efcce.cc