open spiel: open_spiel::algorithms::internal::NodeId< Self > Class Template Reference
open_spiel::algorithms::internal::NodeId< Self > Class Template Reference
#include <infostate_tree.h>
Public Member Functions
NodeId (size_t id_value, const InfostateTree *tree_ptr)
NodeId & operator= (Self &&rhs)
bool operator== (const Self &rhs) const
bool operator!= (const Self &rhs) const
bool BelongsToTree (const InfostateTree *other) const
constexpr NodeId ()
size_t id () const
bool is_undefined () const
void next ()
Detailed Description
template<class Self>
class open_spiel::algorithms::internal::NodeId< Self >
Definition at line 126 of file infostate_tree.h.
Constructor & Destructor Documentation
NodeId() [1/2]
template<class Self > open_spiel::algorithms::internal::NodeId< Self >::NodeId (size_t id_value, const InfostateTree * tree_ptr) inline
Definition at line 132 of file infostate_tree.h.
      : identifier_(id_value), tree_(tree_ptr) {}
NodeId() [2/2]
template<class Self > open_spiel::algorithms::internal::NodeId< Self >::NodeId () inline constexpr
Definition at line 169 of file infostate_tree.h.
{}
Member Function Documentation
BelongsToTree()
template<class Self > bool open_spiel::algorithms::internal::NodeId< Self >::BelongsToTree (const InfostateTree * other) const inline
Definition at line 151 of file infostate_tree.h.
{
    return tree_ == other;
  }
Referenced by open_spiel::algorithms::InfostateTree::decision_infostate(), open_spiel::algorithms::InfostateTree::decision_infostate(), open_spiel::algorithms::InfostateTree::DecisionForSequence(), open_spiel::algorithms::InfostateTree::DecisionIdForSequence(), open_spiel::algorithms::InfostateTree::IsLeafSequence(), open_spiel::algorithms::InfostateTree::leaf_node(), open_spiel::algorithms::InfostateTree::observation_infostate(), and open_spiel::algorithms::InfostateTree::observation_infostate().
id()
template<class Self > size_t open_spiel::algorithms::internal::NodeId< Self >::id () const inline
Definition at line 170 of file infostate_tree.h.
                    {
    SPIEL_CHECK_NE(identifier_, kUndefinedNodeId);
    return identifier_;
  }
References SPIEL_CHECK_NE.
Referenced by open_spiel::algorithms::InfostateNode::AllSequenceIds(), open_spiel::algorithms::InfostateTree::BestResponse(), open_spiel::algorithms::InfostateTree::decision_infostate(), open_spiel::algorithms::InfostateTree::decision_infostate(), open_spiel::algorithms::InfostateTree::DecisionForSequence(), open_spiel::algorithms::InfostateTree::DecisionIdForSequence(), open_spiel::algorithms::InfostateTree::DecisionIdsWithParentSeq(), open_spiel::algorithms::InfostateTree::IsLeafSequence(), open_spiel::algorithms::InfostateTree::leaf_node(), open_spiel::algorithms::InfostateTree::observation_infostate(), open_spiel::algorithms::InfostateTree::observation_infostate(), open_spiel::algorithms::internal::NodeId< Self >::operator!=(), and open_spiel::algorithms::internal::NodeId< Self >::operator==().
is_undefined()
template<class Self > bool open_spiel::algorithms::internal::NodeId< Self >::is_undefined () const inline
Definition at line 174 of file infostate_tree.h.
{ return identifier_ == kUndefinedNodeId; }
References open_spiel::algorithms::internal::kUndefinedNodeId.
Referenced by open_spiel::algorithms::InfostateNode::decision_id(), open_spiel::algorithms::InfostateNode::end_sequence_id(), open_spiel::algorithms::InfostateNode::sequence_id(), and open_spiel::algorithms::InfostateNode::start_sequence_id().
next()
template<class Self > void open_spiel::algorithms::internal::NodeId< Self >::next () inline
Definition at line 175 of file infostate_tree.h.
              {
    SPIEL_CHECK_NE(identifier_, kUndefinedNodeId);
    ++identifier_;
  }
References SPIEL_CHECK_NE.
Referenced by open_spiel::algorithms::InfostateTree::BestResponse().
operator!=()
template<class Self > bool open_spiel::algorithms::internal::NodeId< Self >::operator!= (const Self & rhs) const inline
Definition at line 147 of file infostate_tree.h.
{
    SPIEL_CHECK_EQ(tree_, rhs.tree_);
    return id() != rhs.id();
  }
References open_spiel::algorithms::internal::NodeId< Self >::id(), and SPIEL_CHECK_EQ.
operator=()
template<class Self > NodeId & open_spiel::algorithms::internal::NodeId< Self >::operator= (Self && rhs) inline
Definition at line 134 of file infostate_tree.h.
{
    SPIEL_CHECK_TRUE(
        tree_ == rhs.tree_ ||
        // The NodeId may be uninitialized, so allow to copy the rhs tree.
        tree_ == nullptr && rhs.tree_ != nullptr);
    identifier_ = rhs.id();
    tree_ == rhs.tree_;
    return *this;
  }
References SPIEL_CHECK_TRUE.
operator==()
template<class Self > bool open_spiel::algorithms::internal::NodeId< Self >::operator== (const Self & rhs) const inline
Definition at line 143 of file infostate_tree.h.
{
    SPIEL_CHECK_EQ(tree_, rhs.tree_);
    return id() == rhs.id();
  }
References open_spiel::algorithms::internal::NodeId< Self >::id(), and SPIEL_CHECK_EQ.
The documentation for this class was generated from the following file:
open_spiel/algorithms/infostate_tree.h