open spiel: open_spiel::othello::OthelloState Class Reference
open_spiel::othello::OthelloState Class Reference
#include <othello.h>
Public Member Functions
OthelloState (std::shared_ptr< const Game > game)
OthelloState (const OthelloState &)=default
OthelloState & operator= (const OthelloState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 87 of file othello.h.
Constructor & Destructor Documentation
OthelloState() [1/2]
open_spiel::othello::OthelloState::OthelloState (std::shared_ptr< const Game > game)
Definition at line 251 of file othello.cc.
                                                         : State(game) {
  absl::c_fill(board_, CellState::kEmpty);
  board_[Move(3, 3).GetAction()] = CellState::kWhite;
  board_[Move(3, 4).GetAction()] = CellState::kBlack;
  board_[Move(4, 3).GetAction()] = CellState::kBlack;
  board_[Move(4, 4).GetAction()] = CellState::kWhite;
}
References absl::c_fill(), open_spiel::othello::Move::GetAction(), open_spiel::othello::kBlack, open_spiel::othello::kEmpty, and open_spiel::othello::kWhite.
Referenced by Clone().
OthelloState() [2/2]
open_spiel::othello::OthelloState::OthelloState (const OthelloState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::othello::OthelloState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 242 of file othello.cc.
{
  if (action_id == kPassMove) {
    return "pass";
  } else {
    return Move(action_id).ToString();
  }
}
References open_spiel::othello::kPassMove, and open_spiel::othello::Move::ToString().
Clone()
std::unique_ptr< State > open_spiel::othello::OthelloState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 321 of file othello.cc.
{
  return std::unique_ptr<State>(new OthelloState(*this));
}
References OthelloState().
CurrentPlayer()
Player open_spiel::othello::OthelloState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 94 of file othello.h.
{ return current_player_; }
Referenced by ToString().
InformationStateString()
std::string open_spiel::othello::OthelloState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 290 of file othello.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::othello::OthelloState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 276 of file othello.cc.
{
  return current_player_ == kTerminalPlayerId;
}
References open_spiel::kTerminalPlayerId.
Referenced by LegalActions(), and ToString().
LegalActions()
std::vector< Action > open_spiel::othello::OthelloState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 235 of file othello.cc.
{
  if (IsTerminal()) return {};
  std::vector<Action> moves = LegalRegularActions(current_player_);
  if (moves.empty()) moves.push_back(kPassMove);
  return moves;
}
References IsTerminal(), and open_spiel::othello::kPassMove.
ObservationString()
std::string open_spiel::othello::OthelloState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 296 of file othello.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::othello::OthelloState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 302 of file othello.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // Treat `values` as a 2-d tensor.
  TensorView<2> view(values, {kCellStates, kNumCells}, true);
  for (int cell = 0; cell < kNumCells; ++cell) {
    if (board_[cell] == CellState::kEmpty) {
      view[{0, cell}] = 1;
    } else if (board_[cell] == PlayerToState(player)) {
      view[{1, cell}] = 1;
    } else {  // Opponent's piece
      view[{2, cell}] = 1;
    }
  }
}
References open_spiel::othello::kCellStates, open_spiel::othello::kEmpty, open_spiel::othello::kNumCells, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
operator=()
OthelloState & open_spiel::othello::OthelloState::operator= (const OthelloState &) default
Returns()
std::vector< double > open_spiel::othello::OthelloState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 280 of file othello.cc.
{
  if (outcome_ == Player{0}) {
    return {1.0, -1.0};
  } else if (outcome_ == Player{1}) {
    return {-1.0, 1.0};
  } else {
    return {0.0, 0.0};
  }
}
ToString()
std::string open_spiel::othello::OthelloState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 259 of file othello.cc.
{
  std::string col_labels = "  a b c d e f g h  ";
  std::string str = IsTerminal() ? std::string("Terminal State:\n")
                                 : absl::StrCat(PlayerToString(CurrentPlayer()),
                                                " to play:\n");
  absl::StrAppend(&str, col_labels, "\n");
  for (int r = 0; r < kNumRows; ++r) {
    absl::StrAppend(&str, RowString(r), " ");
    for (int c = 0; c < kNumCols; ++c) {
      absl::StrAppend(&str, StateToString(BoardAt(r, c)), " ");
    }
    absl::StrAppend(&str, RowString(r), "\n");
  }
  absl::StrAppend(&str, col_labels);
  return str;
}
References CurrentPlayer(), IsTerminal(), open_spiel::othello::kNumCols, open_spiel::othello::kNumRows, r, StateToString(), absl::StrAppend(), and absl::StrCat().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/othello/othello.h
open_spiel/games/othello/othello.cc