open spiel: open_spiel::Allocator Class Reference
open_spiel::Allocator Class Reference abstract
#include <observer.h>
Public Member Functions
virtual SpanTensor Get (absl::string_view name, const absl::InlinedVector< int, 4 > &shape)=0
virtual ~Allocator ()=default
Detailed Description
Definition at line 160 of file observer.h.
Constructor & Destructor Documentation
~Allocator()
virtual open_spiel::Allocator::~Allocator () virtual default
Member Function Documentation
Get()
virtual SpanTensor open_spiel::Allocator::Get (absl::string_view name, const absl::InlinedVector< int, 4 > & shape) pure virtual
Implemented in open_spiel::ContiguousAllocator, and open_spiel::TrackingVectorAllocator.
Referenced by open_spiel::leduc_poker::LeducObserver::WriteAllPlayerCards(), open_spiel::leduc_poker::LeducObserver::WriteBettingSequence(), open_spiel::leduc_poker::LeducObserver::WriteCommunityCard(), open_spiel::leduc_poker::LeducObserver::WriteObservingPlayer(), open_spiel::leduc_poker::LeducObserver::WritePotContribution(), open_spiel::leduc_poker::LeducObserver::WriteSinglePlayerCard(), open_spiel::kuhn_poker::KuhnObserver::WriteTensor(), open_spiel::phantom_go::PhantomGoObserver::WriteTensor(), open_spiel::PyObserver::WriteTensor(), and open_spiel::RestrictedNashResponseObserver::WriteTensor().
The documentation for this class was generated from the following file:
open_spiel/observer.h