open spiel: open_spiel::checkers::CheckersState Class Reference
open_spiel::checkers::CheckersState Class Reference
#include <checkers.h>
Public Member Functions
CheckersState (std::shared_ptr< const Game > game, int rows, int columns)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
bool InBounds (int row, int column) const
void SetCustomBoard (const std::string board_string)
CellState CrownStateIfLastRowReached (int row, CellState state)
CheckersAction SpielActionToCheckersAction (Action action) const
Action CheckersActionToSpielAction (CheckersAction move) const
void SetBoard (int row, int column, CellState state)
CellState BoardAt (int row, int column) const
std::vector< Action > LegalActions () const override
int ObservationPlane (CellState state, Player player) const
int GetRow () const
int GetCollumn () const
int GetCellState () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 100 of file checkers.h.
Constructor & Destructor Documentation
CheckersState()
open_spiel::checkers::CheckersState::CheckersState (std::shared_ptr< const Game > game, int rows, int columns) explicit
Definition at line 188 of file checkers.cc.
    : State(game), rows_(rows), columns_(columns) {
  SPIEL_CHECK_GE(rows_, 1);
  SPIEL_CHECK_GE(columns_, 1);
  SPIEL_CHECK_LE(rows_, 99);     // Only supports 1 and 2 digit row numbers.
  SPIEL_CHECK_LE(columns_, 26);  // Only 26 letters to represent columns.
  moves_without_capture_ = 0;
  board_ = std::vector<CellState>(rows_ * columns_, CellState::kEmpty);
  turn_history_info_ = {};
  for (int row = rows_ - 1; row >= 0; row--) {
    for (int column = 0; column < columns_; column++) {
      if ((row + column) % 2 == 1) {
        if (row >= 0 && row < kNumRowsWithPieces) {
          SetBoard(row, column, CellState::kBlack);
        } else if (row >= (rows_ - kNumRowsWithPieces)) {
          SetBoard(row, column, CellState::kWhite);
        }
      }
    }
  }
}
References open_spiel::checkers::kBlack, open_spiel::checkers::kEmpty, open_spiel::checkers::kWhite, SetBoard(), SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::checkers::CheckersState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 327 of file checkers.cc.
{
  CheckersAction checkers_action = SpielActionToCheckersAction(action_id);
  const int end_row =
      checkers_action.row + kDirRowOffsets[checkers_action.direction] *
                                (checkers_action.move_type + 1);
  const int end_column =
      checkers_action.column + kDirColumnOffsets[checkers_action.direction] *
                                   (checkers_action.move_type + 1);
  std::string action_string = absl::StrCat(
      ColumnLabel(checkers_action.column), RowLabel(rows_, checkers_action.row),
      ColumnLabel(end_column), RowLabel(rows_, end_row));
  return action_string;
}
References open_spiel::checkers::CheckersAction::column, open_spiel::checkers::CheckersAction::direction, open_spiel::checkers::CheckersAction::move_type, open_spiel::checkers::CheckersAction::row, SpielActionToCheckersAction(), and absl::StrCat().
BoardAt()
CellState open_spiel::checkers::CheckersState::BoardAt (int row, int column) const inline
Definition at line 127 of file checkers.h.
{
    return board_[row * columns_ + column];
  }
Referenced by DoApplyAction(), LegalActions(), ObservationTensor(), and ToString().
CheckersActionToSpielAction()
Action open_spiel::checkers::CheckersState::CheckersActionToSpielAction (CheckersAction move) const
Definition at line 246 of file checkers.cc.
{
  std::vector<int> action_bases = {rows_, columns_, kNumDirections,
                                   kNumMoveType};
  return RankActionMixedBase(
      action_bases, {move.row, move.column, move.direction, move.move_type});
}
References open_spiel::RankActionMixedBase().
Referenced by LegalActions().
Clone()
std::unique_ptr< State > open_spiel::checkers::CheckersState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 115 of file checkers.h.
{
    return std::unique_ptr<State>(new CheckersState(*this));
  }
References CheckersState().
CrownStateIfLastRowReached()
CellState open_spiel::checkers::CheckersState::CrownStateIfLastRowReached (int row, CellState state)
Definition at line 213 of file checkers.cc.
{
  if (row == 0 && state == CellState::kWhite) {
    return CellState::kWhiteKing;
  }
  if (row == rows_ - 1 && state == CellState::kBlack) {
    return CellState::kBlackKing;
  }
  return state;
}
References open_spiel::checkers::kBlack, open_spiel::checkers::kBlackKing, open_spiel::checkers::kWhite, open_spiel::checkers::kWhiteKing, and state.
Referenced by DoApplyAction().
CurrentPlayer()
Player open_spiel::checkers::CheckersState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 104 of file checkers.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::checkers::CheckersState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 253 of file checkers.cc.
{
  CheckersAction checkers_action = SpielActionToCheckersAction(action);
  SPIEL_CHECK_TRUE(InBounds(checkers_action.row, checkers_action.column));
  int end_row, end_column;
  multiple_jump_piece_ = kNoMultipleJumpsPossible;
  moves_without_capture_++;
  switch (checkers_action.move_type) {
    case MoveType::kNormal:
      end_row = checkers_action.row + kDirRowOffsets[checkers_action.direction];
      end_column =
          checkers_action.column + kDirColumnOffsets[checkers_action.direction];
      SPIEL_CHECK_TRUE(InBounds(end_row, end_column));
      SPIEL_CHECK_EQ(BoardAt(end_row, end_column), CellState::kEmpty);
      turn_history_info_.push_back(TurnHistoryInfo(
          action, current_player_, PieceType::kMan,
          StateToPiece(BoardAt(checkers_action.row, checkers_action.column))));
      SetBoard(
          end_row, end_column,
          CrownStateIfLastRowReached(
              end_row, BoardAt(checkers_action.row, checkers_action.column)));
      SetBoard(checkers_action.row, checkers_action.column, CellState::kEmpty);
      break;
    case MoveType::kCapture:
      end_row =
          checkers_action.row + kDirRowOffsets[checkers_action.direction] * 2;
      end_column = checkers_action.column +
                   kDirColumnOffsets[checkers_action.direction] * 2;
      SPIEL_CHECK_TRUE(InBounds(end_row, end_column));
      SPIEL_CHECK_EQ(BoardAt(end_row, end_column), CellState::kEmpty);
      PieceType captured_piece =
          StateToPiece(BoardAt((checkers_action.row + end_row) / 2,
                               (checkers_action.column + end_column) / 2));
      turn_history_info_.push_back(TurnHistoryInfo(
          action, current_player_, captured_piece,
          StateToPiece(BoardAt(checkers_action.row, checkers_action.column))));
      SetBoard((checkers_action.row + end_row) / 2,
               (checkers_action.column + end_column) / 2, CellState::kEmpty);
      CellState end_state = CrownStateIfLastRowReached(
          end_row, BoardAt(checkers_action.row, checkers_action.column));
      SetBoard(end_row, end_column, end_state);
      bool piece_crowned =
          BoardAt(checkers_action.row, checkers_action.column) != end_state;
      SetBoard(checkers_action.row, checkers_action.column, CellState::kEmpty);
      moves_without_capture_ = 0;
      // Check if multiple jump is possible for the piece that made the
      // last capture. If that is the case, then the current player gets
      // to move again with LegalActions restricted to multiple jump moves
      // for this piece.
      if (!piece_crowned) {
        std::vector<Action> moves = LegalActions();
        for (Action action : moves) {
          CheckersAction move = SpielActionToCheckersAction(action);
          if (move.row == end_row && move.column == end_column &&
              move.move_type == MoveType::kCapture) {
            multiple_jump_piece_ = end_row * rows_ + end_column;
            break;
          }
        }
      }
      break;
  }
  if (multiple_jump_piece_ == kNoMultipleJumpsPossible) {
    current_player_ = 1 - current_player_;
  }
  if (LegalActions().empty()) {
    outcome_ = 1 - current_player_;
  }
}
References action, BoardAt(), open_spiel::checkers::CheckersAction::column, CrownStateIfLastRowReached(), open_spiel::checkers::CheckersAction::direction, InBounds(), open_spiel::checkers::kCapture, open_spiel::checkers::kEmpty, open_spiel::checkers::kMan, open_spiel::checkers::kNoMultipleJumpsPossible, open_spiel::checkers::kNormal, LegalActions(), open_spiel::checkers::CheckersAction::move_type, open_spiel::checkers::CheckersAction::row, SetBoard(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and SpielActionToCheckersAction().
GetCellState()
int open_spiel::checkers::CheckersState::GetCellState () const inline
Definition at line 134 of file checkers.h.
{ return kCellStates; }
References open_spiel::checkers::kCellStates.
GetCollumn()
int open_spiel::checkers::CheckersState::GetCollumn () const inline
Definition at line 133 of file checkers.h.
{ return columns_; }
GetRow()
int open_spiel::checkers::CheckersState::GetRow () const inline
Definition at line 132 of file checkers.h.
{ return rows_; }
InBounds()
bool open_spiel::checkers::CheckersState::InBounds (int row, int column) const
Definition at line 414 of file checkers.cc.
{
  return (row >= 0 && row < rows_ && column >= 0 && column < columns_);
}
Referenced by DoApplyAction(), and LegalActions().
InformationStateString()
std::string open_spiel::checkers::CheckersState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 491 of file checkers.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::checkers::CheckersState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 477 of file checkers.cc.
{ return LegalActions().empty(); }
References LegalActions().
Referenced by CurrentPlayer().
LegalActions()
std::vector< Action > open_spiel::checkers::CheckersState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 344 of file checkers.cc.
{
  if (moves_without_capture_ >= kMaxMovesWithoutCapture) {
    return {};
  }
  std::vector<Action> move_list, capture_move_list;
  CellState current_player_state = PlayerToState(current_player_);
  CellState current_player_crowned = CrownState(current_player_state);
  for (int row = 0; row < rows_; row++) {
    for (int column = 0; column < columns_; column++) {
      if (BoardAt(row, column) == current_player_state ||
          BoardAt(row, column) == current_player_crowned) {
        for (int direction = 0; direction < kNumDirections; direction++) {
          // Only crowned pieces can move in all 4 directions.
          if (BoardAt(row, column) == current_player_state &&
              ((current_player_ == 0 && direction > 1) ||
               (current_player_ == 1 && direction < 2))) {
            continue;
          }
          int adjacent_row = row + kDirRowOffsets[direction];
          int adjacent_column = column + kDirColumnOffsets[direction];
          if (InBounds(adjacent_row, adjacent_column)) {
            CellState adjacent_state = BoardAt(adjacent_row, adjacent_column);
            CellState opponent_state = OpponentState(current_player_state);
            CellState opponent_state_crowned = CrownState(opponent_state);
            if (adjacent_state == CellState::kEmpty) {
              CheckersAction move =
                  CheckersAction(row, column, direction, MoveType::kNormal);
              move_list.push_back(CheckersActionToSpielAction(move));
            } else if (adjacent_state == opponent_state ||
                       adjacent_state == opponent_state_crowned) {
              int jumping_row = adjacent_row + kDirRowOffsets[direction];
              int jumping_column =
                  adjacent_column + kDirColumnOffsets[direction];
              if (InBounds(jumping_row, jumping_column) &&
                  BoardAt(jumping_row, jumping_column) == CellState::kEmpty) {
                CheckersAction move =
                    CheckersAction(row, column, direction, MoveType::kCapture);
                capture_move_list.push_back(CheckersActionToSpielAction(move));
              }
            }
          }
        }
      }
    }
  }
  // If capture moves are possible, it's mandatory to play them.
  if (!capture_move_list.empty()) {
    if (multiple_jump_piece_ != kNoMultipleJumpsPossible) {
      int multiple_jump_piece_row = multiple_jump_piece_ / rows_;
      int multiple_jump_piece_column = multiple_jump_piece_ % rows_;
      std::vector<Action> multiple_move_list;
      for (Action action : capture_move_list) {
        CheckersAction move = SpielActionToCheckersAction(action);
        if (move.row == multiple_jump_piece_row &&
            move.column == multiple_jump_piece_column) {
          multiple_move_list.push_back(action);
        }
      }
      SPIEL_CHECK_GT(multiple_move_list.size(), 0);
      return multiple_move_list;
    }
    return capture_move_list;
  }
  return move_list;
}
References action, BoardAt(), CheckersActionToSpielAction(), InBounds(), open_spiel::checkers::kCapture, open_spiel::checkers::kEmpty, open_spiel::checkers::kMaxMovesWithoutCapture, open_spiel::checkers::kNoMultipleJumpsPossible, open_spiel::checkers::kNormal, SPIEL_CHECK_GT, and SpielActionToCheckersAction().
Referenced by DoApplyAction(), and IsTerminal().
ObservationPlane()
int open_spiel::checkers::CheckersState::ObservationPlane (CellState state, Player player) const
Definition at line 451 of file checkers.cc.
{
  int state_value;
  switch (state) {
    case CellState::kWhite:
      state_value = 0;
      break;
    case CellState::kWhiteKing:
      state_value = 1;
      break;
    case CellState::kBlackKing:
      state_value = 2;
      break;
    case CellState::kBlack:
      state_value = 3;
      break;
    case CellState::kEmpty:
    default:
      return 4;
  }
  if (player == Player{0}) {
    return state_value;
  } else {
    return 3 - state_value;
  }
}
References open_spiel::checkers::kBlack, open_spiel::checkers::kBlackKing, open_spiel::checkers::kEmpty, open_spiel::checkers::kWhite, open_spiel::checkers::kWhiteKing, player, and state.
Referenced by ObservationTensor().
ObservationString()
std::string open_spiel::checkers::CheckersState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 497 of file checkers.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::checkers::CheckersState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 503 of file checkers.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<3> view(values, {kCellStates, rows_, columns_}, true);
  // Observation Tensor Representation:
  //  Plane 0: 1's where the current player's pieces are, 0's elsewhere.
  //  Plane 1: 1's where the oppponent's pieces are, 0's elsewhere.
  //  Plane 2: 1's where the current player's crowned pieces are, 0's elsewhere.
  //  Plane 3: 1's where the oppponent's crowned pieces are, 0's elsewhere.
  //  Plane 4: 1's where the empty cells are, 0's elsewhere.
  for (int row = 0; row < rows_; row++) {
    for (int column = 0; column < columns_; column++) {
      int plane = ObservationPlane(BoardAt(row, column), player);
      view[{plane, row, column}] = 1.0;
    }
  }
}
References BoardAt(), open_spiel::checkers::kCellStates, open_spiel::State::num_players_, ObservationPlane(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::checkers::CheckersState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 479 of file checkers.cc.
{
  if (outcome_ == kInvalidPlayer ||
      moves_without_capture_ >= kMaxMovesWithoutCapture) {
    return {0., 0.};
  } else if (outcome_ == Player{0}) {
    return {1.0, -1.0};
  } else if (outcome_ == Player{1}) {
    return {-1.0, 1.0};
  }
  return {0., 0.};
}
References open_spiel::kInvalidPlayer, and open_spiel::checkers::kMaxMovesWithoutCapture.
SetBoard()
void open_spiel::checkers::CheckersState::SetBoard (int row, int column, CellState state) inline
Definition at line 124 of file checkers.h.
{
    board_[row * columns_ + column] = state;
  }
References state.
Referenced by CheckersState(), DoApplyAction(), SetCustomBoard(), and UndoAction().
SetCustomBoard()
void open_spiel::checkers::CheckersState::SetCustomBoard (const std::string board_string)
Definition at line 223 of file checkers.cc.
{
  SPIEL_CHECK_EQ(rows_ * columns_, board_string.length() - 1);
  current_player_ = board_string[0] - '0';
  SPIEL_CHECK_GE(current_player_, 0);
  SPIEL_CHECK_LE(current_player_, 1);
  // Create the board from the board string. The characters 'o', '8' are White
  // (first player) & '+', '*' are Black (second player), and the character '.'
  // is an Empty cell. Population goes from top left to bottom right.
  for (int row = 0; row < rows_; row++) {
    for (int column = 0; column < columns_; column++) {
      char state_character = board_string[1 + row * columns_ + column];
      CellState state = StringToState(state_character);
      SetBoard(row, column, state);
    }
  }
}
References SetBoard(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and state.
SpielActionToCheckersAction()
CheckersAction open_spiel::checkers::CheckersState::SpielActionToCheckersAction (Action action) const
Definition at line 240 of file checkers.cc.
{
  std::vector<int> values = UnrankActionMixedBase(
      action, {rows_, columns_, kNumDirections, kNumMoveType});
  return CheckersAction(values[0], values[1], values[2], values[3]);
}
References action, open_spiel::UnrankActionMixedBase(), and values.
Referenced by ActionToString(), DoApplyAction(), LegalActions(), and UndoAction().
ToString()
std::string open_spiel::checkers::CheckersState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 418 of file checkers.cc.
{
  std::string result;
  result.reserve((rows_ + 1) * (columns_ + 3));
  for (int r = 0; r < rows_; r++) {
    // Ensure the row labels are aligned.
    if (rows_ - r < 10 && rows_ >= 10) {
      absl::StrAppend(&result, " ");
    }
    absl::StrAppend(&result, RowLabel(rows_, r));
    for (int c = 0; c < columns_; c++) {
      absl::StrAppend(&result, StateToString(BoardAt(r, c)));
    }
    result.append("\n");
  }
  // Add an extra space to the bottom row
  // if the row labels take up two spaces.
  if (rows_ >= 10) {
    absl::StrAppend(&result, " ");
  }
  absl::StrAppend(&result, " ");
  for (int c = 0; c < columns_; c++) {
    absl::StrAppend(&result, ColumnLabel(c));
  }
  absl::StrAppend(&result, "\n");
  return result;
}
References BoardAt(), r, StateToString(), and absl::StrAppend().
Referenced by ObservationString().
UndoAction()
void open_spiel::checkers::CheckersState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 529 of file checkers.cc.
{
  CheckersAction move = SpielActionToCheckersAction(action);
  const TurnHistoryInfo& thi = turn_history_info_.back();
  SPIEL_CHECK_EQ(thi.player, player);
  SPIEL_CHECK_EQ(thi.action, action);
  current_player_ = player;
  outcome_ = kInvalidPlayer;
  move_number_--;
  int end_row, end_column;
  CellState player_piece =
      GetPieceStateFromTurnHistory(player, thi.player_piece_type);
  switch (move.move_type) {
    case MoveType::kNormal:
      end_row = move.row + kDirRowOffsets[move.direction];
      end_column = move.column + kDirColumnOffsets[move.direction];
      SetBoard(move.row, move.column, player_piece);
      SetBoard(end_row, end_column, CellState::kEmpty);
      break;
    case MoveType::kCapture:
      end_row = move.row + kDirRowOffsets[move.direction] * 2;
      end_column = move.column + kDirColumnOffsets[move.direction] * 2;
      SetBoard(move.row, move.column, player_piece);
      SetBoard(end_row, end_column, CellState::kEmpty);
      CellState captured_piece =
          GetPieceStateFromTurnHistory(1 - player, thi.captured_piece_type);
      SetBoard((move.row + end_row) / 2, (move.column + end_column) / 2,
               captured_piece);
      break;
  }
  turn_history_info_.pop_back();
  history_.pop_back();
}
References action, open_spiel::checkers::TurnHistoryInfo::action, open_spiel::checkers::TurnHistoryInfo::captured_piece_type, open_spiel::checkers::GetPieceStateFromTurnHistory(), open_spiel::State::history_, open_spiel::checkers::kCapture, open_spiel::checkers::kEmpty, open_spiel::kInvalidPlayer, open_spiel::checkers::kNormal, open_spiel::State::move_number_, open_spiel::checkers::TurnHistoryInfo::player, player, open_spiel::checkers::TurnHistoryInfo::player_piece_type, SetBoard(), SPIEL_CHECK_EQ, and SpielActionToCheckersAction().
The documentation for this class was generated from the following files:
open_spiel/games/checkers/checkers.h
open_spiel/games/checkers/checkers.cc