open spiel: open_spiel::bridge::BridgeState Class Reference
open_spiel::bridge::BridgeState Class Reference
#include <bridge.h>
Public Member Functions
BridgeState (std::shared_ptr< const Game > game, bool use_double_dummy_result, bool is_dealer_vulnerable, bool is_non_dealer_vulnerable, int num_tricks)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void WriteObservationTensor (Player player, absl::Span< float > values) const
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string Serialize () const override
void SetDoubleDummyResults (ddTableResults double_dummy_results)
int ContractIndex () const
std::array< bool, kNumContracts > PossibleContracts () const
std::array< int, kNumContracts > ScoreByContract () const
std::vector< int > ScoreForContracts (int player, const std::vector< int > &contracts) const
std::vector< double > PrivateObservationTensor (Player player) const
std::vector< double > PublicObservationTensor () const
int CurrentPhase () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 101 of file bridge.h.
Constructor & Destructor Documentation
BridgeState()
open_spiel::bridge::BridgeState::BridgeState (std::shared_ptr< const Game > game, bool use_double_dummy_result, bool is_dealer_vulnerable, bool is_non_dealer_vulnerable, int num_tricks)
Definition at line 146 of file bridge.cc.
    : State(game),
      use_double_dummy_result_(use_double_dummy_result),
      is_vulnerable_{is_dealer_vulnerable, is_non_dealer_vulnerable},
      num_tricks_(num_tricks) {
  possible_contracts_.fill(true);
}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::bridge::BridgeState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 157 of file bridge.cc.
{
  return (action < kBiddingActionBase) ? CardString(action)
                                       : BidString(action - kBiddingActionBase);
}
References action, and open_spiel::bridge::kBiddingActionBase.
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::bridge::BridgeState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 692 of file bridge.cc.
{
  std::vector<std::pair<Action, double>> outcomes;
  int num_cards_remaining = kNumCards - history_.size();
  outcomes.reserve(num_cards_remaining);
  const double p = 1.0 / static_cast<double>(num_cards_remaining);
  for (int card = 0; card < kNumCards; ++card) {
    if (!holder_[card].has_value()) outcomes.emplace_back(card, p);
  }
  return outcomes;
}
References open_spiel::State::history_, and open_spiel::bridge::kNumCards.
Clone()
std::unique_ptr< State > open_spiel::bridge::BridgeState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 115 of file bridge.h.
{
    return std::unique_ptr<State>(new BridgeState(*this));
  }
References BridgeState().
ContractIndex()
int open_spiel::bridge::BridgeState::ContractIndex () const
Definition at line 944 of file bridge.cc.
{
  SPIEL_CHECK_TRUE(phase_ == Phase::kPlay || phase_ == Phase::kGameOver);
  return contract_.Index();
}
References open_spiel::bridge::Contract::Index(), and SPIEL_CHECK_TRUE.
Referenced by open_spiel::init_pyspiel_games_bridge().
CurrentPhase()
int open_spiel::bridge::BridgeState::CurrentPhase () const inline
Definition at line 153 of file bridge.h.
{ return static_cast<int>(phase_); }
Referenced by open_spiel::init_pyspiel_games_bridge().
CurrentPlayer()
Player open_spiel::bridge::BridgeState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 834 of file bridge.cc.
{
  if (phase_ == Phase::kDeal) {
    return kChancePlayerId;
  } else if (phase_ == Phase::kGameOver) {
    return kTerminalPlayerId;
  } else if (phase_ == Phase::kPlay &&
             Partnership(current_player_) == Partnership(contract_.declarer)) {
    // Declarer chooses cards for both players.
    return contract_.declarer;
  } else {
    return current_player_;
  }
}
References open_spiel::bridge::Contract::declarer, open_spiel::kChancePlayerId, and open_spiel::kTerminalPlayerId.
Referenced by ObservationString().
DoApplyAction()
void open_spiel::bridge::BridgeState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 703 of file bridge.cc.
{
  switch (phase_) {
    case Phase::kDeal:
      return ApplyDealAction(action);
    case Phase::kAuction:
      return ApplyBiddingAction(action - kBiddingActionBase);
    case Phase::kPlay:
      return ApplyPlayAction(action);
    case Phase::kGameOver:
      SpielFatalError("Cannot act in terminal states");
  }
}
References action, open_spiel::bridge::kBiddingActionBase, and open_spiel::SpielFatalError().
IsTerminal()
bool open_spiel::bridge::BridgeState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 109 of file bridge.h.
{ return phase_ == Phase::kGameOver; }
Referenced by ObservationString(), and ToString().
LegalActions()
std::vector< Action > open_spiel::bridge::BridgeState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 627 of file bridge.cc.
{
  switch (phase_) {
    case Phase::kDeal:
      return DealLegalActions();
    case Phase::kAuction:
      return BiddingLegalActions();
    case Phase::kPlay:
      return PlayLegalActions();
    default:
      return {};
  }
}
ObservationString()
std::string open_spiel::bridge::BridgeState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 190 of file bridge.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (IsTerminal()) return ToString();
  std::string rv = FormatVulnerability();
  auto cards = FormatHand(player, /*mark_voids=*/true, holder_);
  for (int suit = kNumSuits - 1; suit >= 0; --suit)
    absl::StrAppend(&rv, cards[suit], "\n");
  if (history_.size() > kNumCards)
    absl::StrAppend(
        &rv, FormatAuction(/*trailing_query=*/phase_ == Phase::kAuction &&
                           player == CurrentPlayer()));
  if (num_cards_played_ > 0) absl::StrAppend(&rv, FormatPlay());
  return rv;
}
References CurrentPlayer(), open_spiel::bridge::FormatHand(), open_spiel::State::history_, IsTerminal(), open_spiel::bridge::kNumCards, open_spiel::bridge::kNumSuits, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and ToString().
ObservationTensor()
void open_spiel::bridge::BridgeState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 300 of file bridge.cc.
{
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  WriteObservationTensor(player, values);
}
References open_spiel::State::game_, player, SPIEL_CHECK_EQ, values, and WriteObservationTensor().
PossibleContracts()
std::array< bool, kNumContracts > open_spiel::bridge::BridgeState::PossibleContracts () const inline
Definition at line 128 of file bridge.h.
{
    return possible_contracts_;
  }
Referenced by open_spiel::init_pyspiel_games_bridge().
PrivateObservationTensor()
std::vector< double > open_spiel::bridge::BridgeState::PrivateObservationTensor (Player player) const
Definition at line 469 of file bridge.cc.
{
  std::vector<double> rv(kNumCards);
  for (int i = 0; i < kNumCards; ++i)
    if (holder_[i] == player) rv[i] = 1;
  return rv;
}
References i, open_spiel::bridge::kNumCards, and player.
Referenced by open_spiel::init_pyspiel_games_bridge().
PublicObservationTensor()
std::vector< double > open_spiel::bridge::BridgeState::PublicObservationTensor () const
Definition at line 434 of file bridge.cc.
{
  SPIEL_CHECK_TRUE(phase_ == Phase::kAuction);
  std::vector<double> rv(kPublicInfoTensorSize);
  auto ptr = rv.begin();
  ptr[is_vulnerable_[0]] = 1;
  ptr += kNumVulnerabilities;
  ptr[is_vulnerable_[1]] = 1;
  ptr += kNumVulnerabilities;
  auto bidding = ptr + 2 * kNumPlayers;  // initial and recent passes
  int last_bid = 0;
  for (int i = kNumCards; i < history_.size(); ++i) {
    const int player = i % kNumPlayers;
    const int this_call = history_[i].action - kBiddingActionBase;
    if (this_call == kPass) {
      if (last_bid == 0) ptr[player] = 1;  // Leading passes
      ptr[kNumPlayers + player] = 1;       // Trailing passes
    } else {
      // Call is a non-Pass, so clear the trailing pass markers.
      for (int i = 0; i < kNumPlayers; ++i) ptr[kNumPlayers + i] = 0;
      if (this_call == kDouble) {
        auto base = bidding + (last_bid - kFirstBid) * kNumPlayers * 3;
        base[kNumPlayers + player] = 1;
      } else if (this_call == kRedouble) {
        auto base = bidding + (last_bid - kFirstBid) * kNumPlayers * 3;
        base[kNumPlayers * 2 + player] = 1;
      } else {
        last_bid = this_call;
        auto base = bidding + (last_bid - kFirstBid) * kNumPlayers * 3;
        base[player] = 1;
      }
    }
  }
  return rv;
}
References open_spiel::State::history_, i, open_spiel::bridge::kBiddingActionBase, open_spiel::bridge::kNumCards, open_spiel::bridge::kNumPlayers, open_spiel::bridge::kNumVulnerabilities, open_spiel::bridge::kPublicInfoTensorSize, player, ptr, and SPIEL_CHECK_TRUE.
Referenced by open_spiel::init_pyspiel_games_bridge().
Returns()
std::vector< double > open_spiel::bridge::BridgeState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 110 of file bridge.h.
{ return returns_; }
ScoreByContract()
std::array< int, kNumContracts > open_spiel::bridge::BridgeState::ScoreByContract () const inline
Definition at line 135 of file bridge.h.
{
    SPIEL_CHECK_TRUE(double_dummy_results_.has_value());
    return score_by_contract_;
  }
References absl::optional< T >::has_value(), and SPIEL_CHECK_TRUE.
Referenced by open_spiel::init_pyspiel_games_bridge().
ScoreForContracts()
std::vector< int > open_spiel::bridge::BridgeState::ScoreForContracts (int player, const std::vector< int > & contracts) const
Definition at line 506 of file bridge.cc.
{
  // Storage for the number of tricks.
  std::array<std::array<int, kNumPlayers>, kNumDenominations> dd_tricks;
  if (double_dummy_results_.has_value()) {
    // If we have already computed double-dummy results, use them.
    for (int declarer = 0; declarer < kNumPlayers; ++declarer) {
      for (int trumps = 0; trumps < kNumDenominations; ++trumps) {
        dd_tricks[trumps][declarer] =
            double_dummy_results_->resTable[trumps][declarer];
      }
    }
  } else {
    {
      // This performs some sort of global initialization; unclear
      // exactly what.
      absl::MutexLock lock(&dds_mutex);
      DDS_EXTERNAL(SetMaxThreads)(0);
    }
    // Working storage for DD calculation.
    auto thread_data = std::make_unique<ThreadData>();
    auto transposition_table = std::make_unique<TransTableL>();
    transposition_table->SetMemoryDefault(95);   // megabytes
    transposition_table->SetMemoryMaximum(160);  // megabytes
    transposition_table->MakeTT();
    thread_data->transTable = transposition_table.get();
    // Which trump suits do we need to handle?
    std::set<int> suits;
    for (auto index : contracts) {
      const auto& contract = kAllContracts[index];
      if (contract.level > 0) suits.emplace(contract.trumps);
    }
    // Build the deal
    ::deal dl{};
    for (int suit = 0; suit < kNumSuits; ++suit) {
      for (int rank = 0; rank < kNumCardsPerSuit; ++rank) {
        const int player = holder_[Card(Suit(suit), rank)].value();
        dl.remainCards[player][suit] += 1 << (2 + rank);
      }
    }
    for (int k = 0; k <= 2; k++) {
      dl.currentTrickRank[k] = 0;
      dl.currentTrickSuit[k] = 0;
    }
    // Analyze for each trump suit.
    for (int suit : suits) {
      dl.trump = suit;
      transposition_table->ResetMemory(TT_RESET_NEW_TRUMP);
      // Assemble the declarers we need to consider.
      std::set<int> declarers;
      for (auto index : contracts) {
        const auto& contract = kAllContracts[index];
        if (contract.level > 0 && contract.trumps == suit)
          declarers.emplace(contract.declarer);
      }
      // Analyze the deal for each declarer.
      absl::optional<Player> first_declarer;
      absl::optional<int> first_tricks;
      for (int declarer : declarers) {
        ::futureTricks fut;
        dl.first = (declarer + 1) % kNumPlayers;
        if (!first_declarer.has_value()) {
          // First time we're calculating this trump suit.
          const int return_code = SolveBoardInternal(
              thread_data.get(), dl,
              /*target=*/-1,    // Find max number of tricks
              /*solutions=*/1,  // Just the tricks (no card-by-card result)
              /*mode=*/2,       // Unclear
              &fut              // Output
          );
          if (return_code != RETURN_NO_FAULT) {
            char error_message[80];
            DDS_EXTERNAL(ErrorMessage)(return_code, error_message);
            SpielFatalError(
                absl::StrCat("double_dummy_solver:", error_message));
          }
          dd_tricks[suit][declarer] = 13 - fut.score[0];
          first_declarer = declarer;
          first_tricks = 13 - fut.score[0];
        } else {
          // Reuse data from last time.
          const int hint = Partnership(declarer) == Partnership(*first_declarer)
                               ? *first_tricks
                               : 13 - *first_tricks;
          const int return_code =
              SolveSameBoard(thread_data.get(), dl, &fut, hint);
          if (return_code != RETURN_NO_FAULT) {
            char error_message[80];
            DDS_EXTERNAL(ErrorMessage)(return_code, error_message);
            SpielFatalError(
                absl::StrCat("double_dummy_solver:", error_message));
          }
          dd_tricks[suit][declarer] = 13 - fut.score[0];
        }
      }
    }
  }
  // Compute the scores.
  std::vector<int> scores;
  scores.reserve(contracts.size());
  for (int contract_index : contracts) {
    const Contract& contract = kAllContracts[contract_index];
    const int declarer_score =
        (contract.level == 0)
            ? 0
            : Score(contract, dd_tricks[contract.trumps][contract.declarer],
                    is_vulnerable_[Partnership(contract.declarer)]);
    scores.push_back(Partnership(contract.declarer) == Partnership(player)
                         ? declarer_score
                         : -declarer_score);
  }
  return scores;
}
References DDS_EXTERNAL, open_spiel::bridge::dds_mutex(), open_spiel::bridge::Contract::declarer, ErrorMessage(), absl::optional< T >::has_value(), open_spiel::bridge::kAllContracts, open_spiel::bridge::kNumCardsPerSuit, open_spiel::bridge::kNumDenominations, open_spiel::bridge::kNumPlayers, open_spiel::bridge::kNumSuits, open_spiel::bridge::Contract::level, player, rank, ddTableResults::resTable, RETURN_NO_FAULT, open_spiel::bridge::Score(), futureTricks::score, SetMaxThreads(), SolveBoardInternal(), SolveSameBoard(), open_spiel::SpielFatalError(), absl::StrCat(), open_spiel::bridge::Contract::trumps, and TT_RESET_NEW_TRUMP.
Referenced by open_spiel::init_pyspiel_games_bridge().
Serialize()
std::string open_spiel::bridge::BridgeState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 900 of file bridge.cc.
{
  std::string serialized = State::Serialize();
  if (use_double_dummy_result_ && double_dummy_results_.has_value()) {
    std::string dd;
    for (int trumps = 0; trumps < kNumDenominations; ++trumps) {
      for (int player = 0; player < kNumPlayers; ++player) {
        absl::StrAppend(&dd, double_dummy_results_->resTable[trumps][player],
                        "\n");
      }
    }
    absl::StrAppend(&serialized, "Double Dummy Results\n", dd);
  }
  return serialized;
}
References absl::optional< T >::has_value(), open_spiel::bridge::kNumDenominations, open_spiel::bridge::kNumPlayers, player, ddTableResults::resTable, open_spiel::State::Serialize(), and absl::StrAppend().
SetDoubleDummyResults()
void open_spiel::bridge::BridgeState::SetDoubleDummyResults (ddTableResults double_dummy_results)
Definition at line 476 of file bridge.cc.
{
  double_dummy_results_ = double_dummy_results;
  ComputeScoreByContract();
}
ToString()
std::string open_spiel::bridge::BridgeState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 162 of file bridge.cc.
{
  std::string rv = absl::StrCat(FormatVulnerability(), FormatDeal());
  if (history_.size() > kNumCards)
    absl::StrAppend(&rv, FormatAuction(/*trailing_query=*/false));
  if (num_cards_played_ > 0) absl::StrAppend(&rv, FormatPlay());
  if (IsTerminal()) absl::StrAppend(&rv, FormatResult());
  return rv;
}
References open_spiel::State::history_, IsTerminal(), open_spiel::bridge::kNumCards, absl::StrAppend(), and absl::StrCat().
Referenced by ObservationString().
WriteObservationTensor()
void open_spiel::bridge::BridgeState::WriteObservationTensor (Player player, absl::Span< float > values) const
Definition at line 306 of file bridge.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::fill(values.begin(), values.end(), 0.0);
  if (phase_ == Phase::kDeal) return;
  int partnership = Partnership(player);
  auto ptr = values.begin();
  if (num_cards_played_ > 0) {
    // Observation for play phase
    const bool defending = (partnership != Partnership(contract_.declarer));
    if (phase_ == Phase::kPlay) ptr[2 + defending] = 1;
    ptr += kNumObservationTypes;
    // Contract
    ptr[contract_.level - 1] = 1;
    ptr += kNumBidLevels;
    // Trump suit
    ptr[contract_.trumps] = 1;
    ptr += kNumDenominations;
    // Double status
    *ptr++ = contract_.double_status == DoubleStatus::kUndoubled;
    *ptr++ = contract_.double_status == DoubleStatus::kDoubled;
    *ptr++ = contract_.double_status == DoubleStatus::kRedoubled;
    // Identity of the declarer.
    ptr[(contract_.declarer + kNumPlayers - player) % kNumPlayers] = 1;
    ptr += kNumPlayers;
    // Vulnerability.
    ptr[is_vulnerable_[Partnership(contract_.declarer)]] = 1.0;
    ptr += kNumVulnerabilities;
    // Our remaining cards.
    for (int i = 0; i < kNumCards; ++i)
      if (holder_[i] == player) ptr[i] = 1;
    ptr += kNumCards;
    // Dummy's remaining cards.
    const int dummy = Partner(contract_.declarer);
    for (int i = 0; i < kNumCards; ++i)
      if (holder_[i] == dummy) ptr[i] = 1;
    ptr += kNumCards;
    // Indexing into history for recent tricks.
    int current_trick = num_cards_played_ / kNumPlayers;
    int this_trick_cards_played = num_cards_played_ % kNumPlayers;
    int this_trick_start = history_.size() - this_trick_cards_played;
    // Current trick
    if (phase_ != Phase::kGameOver) {
      int leader = tricks_[current_trick].Leader();
      for (int i = 0; i < this_trick_cards_played; ++i) {
        int card = history_[this_trick_start + i].action;
        int relative_player = (i + leader + kNumPlayers - player) % kNumPlayers;
        ptr[relative_player * kNumCards + card] = 1;
      }
    }
    ptr += kNumPlayers * kNumCards;
    // Previous tricks
    for (int j = current_trick - 1;
         j >= std::max(0, current_trick - num_tricks_ + 1); --j) {
      int leader = tricks_[j].Leader();
      for (int i = 0; i < kNumPlayers; ++i) {
        int card =
            history_[this_trick_start - kNumPlayers * (current_trick - j) + i]
                .action;
        int relative_player = (i + leader + kNumPlayers - player) % kNumPlayers;
        ptr[relative_player * kNumCards + card] = 1;
      }
      ptr += kNumPlayers * kNumCards;
    }
    // Move pointer for future tricks to have a fixed size tensor
    if (num_tricks_ > current_trick + 1) {
      ptr += kNumPlayers * kNumCards * (num_tricks_ - current_trick - 1);
    }
    // Number of tricks taken by each side.
    ptr[num_declarer_tricks_] = 1;
    ptr += kNumTricks;
    ptr[num_cards_played_ / 4 - num_declarer_tricks_] = 1;
    ptr += kNumTricks;
    int kPlayTensorSize = BridgeGame::GetPlayTensorSize(num_tricks_);
    SPIEL_CHECK_EQ(std::distance(values.begin(), ptr),
                   kPlayTensorSize + kNumObservationTypes);
    SPIEL_CHECK_LE(std::distance(values.begin(), ptr), values.size());
  } else {
    // Observation for auction or opening lead.
    ptr[phase_ == Phase::kPlay ? 1 : 0] = 1;
    ptr += kNumObservationTypes;
    ptr[is_vulnerable_[partnership]] = 1;
    ptr += kNumVulnerabilities;
    ptr[is_vulnerable_[1 - partnership]] = 1;
    ptr += kNumVulnerabilities;
    int last_bid = 0;
    for (int i = kNumCards; i < history_.size(); ++i) {
      int this_call = history_[i].action - kBiddingActionBase;
      int relative_bidder = (i + kNumPlayers - player) % kNumPlayers;
      if (last_bid == 0 && this_call == kPass) ptr[relative_bidder] = 1;
      if (this_call == kDouble) {
        ptr[kNumPlayers + (last_bid - kFirstBid) * kNumPlayers * 3 +
            kNumPlayers + relative_bidder] = 1;
      } else if (this_call == kRedouble) {
        ptr[kNumPlayers + (last_bid - kFirstBid) * kNumPlayers * 3 +
            kNumPlayers * 2 + relative_bidder] = 1;
      } else if (this_call != kPass) {
        last_bid = this_call;
        ptr[kNumPlayers + (last_bid - kFirstBid) * kNumPlayers * 3 +
            relative_bidder] = 1;
      }
    }
    ptr += kNumPlayers * (1 + 3 * kNumBids);
    for (int i = 0; i < kNumCards; ++i)
      if (holder_[i] == player) ptr[i] = 1;
    ptr += kNumCards;
    SPIEL_CHECK_EQ(std::distance(values.begin(), ptr),
                   kAuctionTensorSize + kNumObservationTypes);
    SPIEL_CHECK_LE(std::distance(values.begin(), ptr), values.size());
  }
}
References action, open_spiel::bridge::Contract::declarer, open_spiel::bridge::Contract::double_status, open_spiel::bridge::BridgeGame::GetPlayTensorSize(), open_spiel::State::history_, i, open_spiel::bridge::kAuctionTensorSize, open_spiel::bridge::kBiddingActionBase, open_spiel::bridge::kDoubled, open_spiel::bridge::kNumBidLevels, open_spiel::bridge::kNumBids, open_spiel::bridge::kNumCards, open_spiel::bridge::kNumDenominations, open_spiel::bridge::kNumObservationTypes, open_spiel::bridge::kNumPlayers, open_spiel::bridge::kNumTricks, open_spiel::bridge::kNumVulnerabilities, open_spiel::bridge::kRedoubled, open_spiel::bridge::kUndoubled, open_spiel::bridge::Contract::level, open_spiel::State::num_players_, player, ptr, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, open_spiel::bridge::Contract::trumps, and values.
Referenced by ObservationTensor().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/bridge.h
open_spiel/games/bridge/bridge.cc