open spiel: absl::internal_statusor::Helper Class Reference
absl::internal_statusor::Helper Class Reference
#include <statusor_internal.h>
Static Public Member Functions
static void HandleInvalidStatusCtorArg (Status *)
static ABSL_ATTRIBUTE_NORETURN void Crash (const absl::Status &status)
Detailed Description
Definition at line 135 of file statusor_internal.h.
Member Function Documentation
Crash()
void absl::internal_statusor::Helper::Crash (const absl::Status & status) static
Definition at line 82 of file statusor.cc.
{
  ABSL_INTERNAL_LOG(
      FATAL,
      absl::StrCat("Attempting to fetch value instead of handling error ",
                   status.ToString()));
}
References ABSL_INTERNAL_LOG, and absl::StrCat().
Referenced by absl::internal_statusor::StatusOrData< T >::EnsureOk().
HandleInvalidStatusCtorArg()
void absl::internal_statusor::Helper::HandleInvalidStatusCtorArg (absl::Status * status) static
Definition at line 70 of file statusor.cc.
{
  const char* kMessage =
      "An OK status is not a valid constructor argument to StatusOr<T>";
#ifdef NDEBUG
  ABSL_INTERNAL_LOG(ERROR, kMessage);
#else
  ABSL_INTERNAL_LOG(FATAL, kMessage);
#endif
  // In optimized builds, we will fall back to InternalError.
  *status = absl::InternalError(kMessage);
}
References ABSL_INTERNAL_LOG, and absl::InternalError().
Referenced by absl::internal_statusor::StatusOrData< T >::EnsureNotOk().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/status/internal/statusor_internal.h
open_spiel/abseil-cpp/absl/status/statusor.cc