open spiel: open_spiel.python.voting.ranked_pairs.RankedPairsVoting Class Reference
open_spiel.python.voting.ranked_pairs.RankedPairsVoting Class Reference
Public Member Functions
__init__ (self)
str name (self)
RankedPairsRankOutcome run_election (self, base.PreferenceProfile profile)
Public Member Functions inherited from open_spiel.python.voting.base.AbstractVotingMethod
bool is_valid_profile (self, PreferenceProfile profile)
Protected Member Functions
bool _would_create_cycle (self, List[base.AlternativeId] alternatives, np.ndarray graph, int from_idx, int to_idx)
_is_source (self, np.ndarray graph, int idx)
_remove_node (self, np.ndarray graph, int idx)
int _get_score (self, np.ndarray graph, np.ndarray margin_matrix, int node_idx)
List[Tuple[Tuple[base.AlternativeId, base.AlternativeId], int]] _get_ranked_pairs (self, List[base.AlternativeId] alternatives, np.ndarray margin_matrix)
Detailed Description
Implements Ranked Pairs / Tideman's method.
Definition at line 48 of file ranked_pairs.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.voting.ranked_pairs.RankedPairsVoting.__init__ (self)
Initializes the voting method.
Args:
  **method_specific_kwargs: optional extra args.
Reimplemented from open_spiel.python.voting.base.AbstractVotingMethod.
Definition at line 51 of file ranked_pairs.py.
  def __init__(self):
    pass
Member Function Documentation
_get_ranked_pairs()
List[Tuple[Tuple[base.AlternativeId, base.AlternativeId], int]] open_spiel.python.voting.ranked_pairs.RankedPairsVoting._get_ranked_pairs (self, List[base.AlternativeId] alternatives, np.ndarray margin_matrix) protected
Returns the positively-valued ranked pairs coupled with their values.
Arguments:
  alternatives: the list of alternatives ids.
  margin_matrix: the margin matrix we use to get the values for each ranked
    pair.
Returns:
  A list of tuples of the form ((x, y), value) indicating x beating y by
  the specified value.
Definition at line 140 of file ranked_pairs.py.
  ) -> List[Tuple[Tuple[base.AlternativeId, base.AlternativeId], int]]:
    """Returns the positively-valued ranked pairs coupled with their values.
    Arguments:
      alternatives: the list of alternatives ids.
      margin_matrix: the margin matrix we use to get the values for each ranked
        pair.
    Returns:
      A list of tuples of the form ((x, y), value) indicating x beating y by
      the specified value.
    """
    ranked_pairs = {}
    rows, cols = np.where(margin_matrix > 0)
    for i, j in zip(rows, cols):
      key_tup = (alternatives[i], alternatives[j])
      ranked_pairs[key_tup] = margin_matrix[i, j]
    return sorted(ranked_pairs.items(), key=lambda item: item[1], reverse=True)
Referenced by open_spiel.python.voting.ranked_pairs.RankedPairsVoting.run_election().
_get_score()
int open_spiel.python.voting.ranked_pairs.RankedPairsVoting._get_score (self, np.ndarray graph, np.ndarray margin_matrix, int node_idx) protected
Computes the score of an alternative.
The score is defined as the sum of the margins between the subgraph
containing all reachable nodes from this node.
Args:
  graph: 2D adjacency matrix representing a directed acyclic graph. Row is
    the from node index, column the to node index.
  margin_matrix: the margin matrix from the profile
  node_idx: the node index in question.
Returns:
  the score of the alternative represented by this node index.
Definition at line 108 of file ranked_pairs.py.
  ) -> int:
    """Computes the score of an alternative.
    The score is defined as the sum of the margins between the subgraph
    containing all reachable nodes from this node.
    Args:
      graph: 2D adjacency matrix representing a directed acyclic graph. Row is
        the from node index, column the to node index.
      margin_matrix: the margin matrix from the profile
      node_idx: the node index in question.
    Returns:
      the score of the alternative represented by this node index.
    """
    # Flood fill to compute score from a source
    score = 0
    open_list = {node_idx: True}
    closed_list = {}
    while open_list:
      i = list(open_list.keys())[0]
      open_list.pop(i)
      outgoing_edges = np.where(graph[i][:] == 1)[0]
      for j in outgoing_edges:
        score += margin_matrix[i, j]
        if j not in open_list and j not in closed_list:
          open_list[j] = True
      closed_list[i] = True
    return score
Referenced by open_spiel.python.voting.ranked_pairs.RankedPairsVoting.run_election().
_is_source()
open_spiel.python.voting.ranked_pairs.RankedPairsVoting._is_source (self, np.ndarray graph, int idx) protected
Returns true if this node is a source, false otherwise.
Definition at line 97 of file ranked_pairs.py.
  def _is_source(self, graph: np.ndarray, idx: int):
    """Returns true if this node is a source, false otherwise."""
    num_incoming = np.sum(graph[:, idx])
    num_outgoing = np.sum(graph[idx])
    return num_outgoing > 0 and num_incoming == 0
Referenced by open_spiel.python.voting.ranked_pairs.RankedPairsVoting.run_election().
_remove_node()
open_spiel.python.voting.ranked_pairs.RankedPairsVoting._remove_node (self, np.ndarray graph, int idx) protected
Removes a node from the graph.
Definition at line 103 of file ranked_pairs.py.
  def _remove_node(self, graph: np.ndarray, idx: int):
    """Removes a node from the graph."""
    graph[idx, :] = 0
    graph[:, idx] = 0
Referenced by open_spiel.python.voting.ranked_pairs.RankedPairsVoting.run_election().
_would_create_cycle()
bool open_spiel.python.voting.ranked_pairs.RankedPairsVoting._would_create_cycle (self, List[base.AlternativeId] alternatives, np.ndarray graph, int from_idx, int to_idx) protected
Checks if adding a specific directed edge would result in a cycle.
Args:
  alternatives: list of alternatives.
  graph: 2D adjacency matrix representing a directed acyclic graph. Row is
    the from node index, column the to node index.
  from_idx: the edge to add (from index).
  to_idx: the edge to add (to index).
Returns:
  True if adding the specified edge would result in a cycle in the graph.
Definition at line 57 of file ranked_pairs.py.
  ) -> bool:
    """Checks if adding a specific directed edge would result in a cycle.
    Args:
      alternatives: list of alternatives.
      graph: 2D adjacency matrix representing a directed acyclic graph. Row is
        the from node index, column the to node index.
      from_idx: the edge to add (from index).
      to_idx: the edge to add (to index).
    Returns:
      True if adding the specified edge would result in a cycle in the graph.
    """
    # Perform a breadth-first flood fill using a status table.
    # Values in the status table represent:
    #    0  means it does not exist in the flood yet
    #    1  means it needs to be expanded
    #    -1 means it has been expanded (now closed, do not revisit)
    m = len(alternatives)
    status_table = np.zeros(m)
    status_table[to_idx] = 1
    num_expanded = 1
    while num_expanded > 0:
      num_expanded = 0
      for i in np.where(status_table == 1)[0]:
        num_expanded += 1
        for j in np.where(graph[i][:] == 1)[0]:
          if status_table[j] == 0:
            if j == from_idx:
              return True
            status_table[j] = 1
        status_table[i] = -1
    return False
References len.
Referenced by open_spiel.python.voting.ranked_pairs.RankedPairsVoting.run_election().
name()
str open_spiel.python.voting.ranked_pairs.RankedPairsVoting.name (self)
Returns the name of the voting method.
Reimplemented from open_spiel.python.voting.base.AbstractVotingMethod.
Definition at line 54 of file ranked_pairs.py.
  def name(self) -> str:
    return "ranked_pairs"
run_election()
RankedPairsRankOutcome open_spiel.python.voting.ranked_pairs.RankedPairsVoting.run_election (self, base.PreferenceProfile profile)
Runs the election and returns the result.
Args:
    profile: a preference profile.
Returns:
    a RankOutcome object that can be queried for the results.
Reimplemented from open_spiel.python.voting.base.AbstractVotingMethod.
Definition at line 161 of file ranked_pairs.py.
  ) -> RankedPairsRankOutcome:
    assert self.is_valid_profile(profile)
    alternatives = profile.alternatives
    m = len(alternatives)
    alt_idx = profile.alternatives_dict
    margin_matrix = profile.margin_matrix()
    # First, get the ranked pairs annotated with their values (delta(a,b)).
    sorted_pairs = self._get_ranked_pairs(alternatives, margin_matrix)
    # Now, create the graph: add edges that do not create cycles.
    graph = np.zeros(shape=(m, m), dtype=np.int32)
    if sorted_pairs:
      # Create the top-ranked pair. This needs to be in a conditional block,
      # because some profiles can legitimately lead to a graph with no edges (no
      # positively-valued ranked pairs)
      first_pair = sorted_pairs[0][0]
      p0_idx = alt_idx[first_pair[0]]
      p1_idx = alt_idx[first_pair[1]]
      graph[p0_idx, p1_idx] = 1
    for j in range(1, len(sorted_pairs)):
      pair = sorted_pairs[j][0]
      p0_idx = alt_idx[pair[0]]
      p1_idx = alt_idx[pair[1]]
      if not self._would_create_cycle(alternatives, graph, p0_idx, p1_idx):
        graph[p0_idx, p1_idx] = 1
    full_graph = graph.copy()  # Make a copy to return later.
    # Now, remove sources nodes in sequence to get the ranking.
    ranking = []
    scores = []
    alt_idx_remaining = []
    for i in range(m):
      alt_idx_remaining.append(i)
    while len(ranking) < m:
      has_source = False
      for j in range(m):
        if self._is_source(graph, j):
          ranking.append(alternatives[j])
          scores.append(self._get_score(graph, margin_matrix, j))
          self._remove_node(graph, j)
          alt_idx_remaining.remove(j)
          has_source = True
          break
      if not has_source:
        # At the end, it can happen that there are a number of disconnected
        # nodes (no incoming nor outgoing edges). Take the first one from the
        # graph.
        j = alt_idx_remaining[0]
        ranking.append(alternatives[j])
        scores.append(0)
        self._remove_node(graph, j)
        alt_idx_remaining.remove(j)
    # Finally, return the ranking and scores.
    outcome = RankedPairsRankOutcome(
        rankings=ranking, scores=scores, graph=full_graph
    )
    return outcome
References open_spiel.python.voting.ranked_pairs.RankedPairsVoting._get_ranked_pairs(), open_spiel.python.voting.ranked_pairs.RankedPairsVoting._get_score(), open_spiel.python.voting.ranked_pairs.RankedPairsVoting._is_source(), open_spiel.python.voting.ranked_pairs.RankedPairsVoting._remove_node(), open_spiel.python.voting.ranked_pairs.RankedPairsVoting._would_create_cycle(), open_spiel.python.voting.base.AbstractVotingMethod.is_valid_profile(), and len.
The documentation for this class was generated from the following file:
open_spiel/python/voting/ranked_pairs.py