open spiel: open_spiel::stones_and_gems::StonesNGemsState Class Reference
open_spiel::stones_and_gems::StonesNGemsState Class Reference
#include <stones_and_gems.h>
Public Member Functions
StonesNGemsState (const StonesNGemsState &)=default
StonesNGemsState (std::shared_ptr< const Game > game, int steps_remaining, int magic_wall_steps, bool magic_active, int blob_max_size, int blob_size, int blob_chance, Element blob_swap, bool blob_enclosed, int gems_required, int gems_collected, int current_reward, int sum_reward, Grid grid, bool obs_show_ids, int id_counter, Player player)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move_id) const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::vector< double > Rewards () const override
std::string ObservationString (Player player) const override
std::string Serialize () const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 253 of file stones_and_gems.h.
Constructor & Destructor Documentation
StonesNGemsState() [1/2]
open_spiel::stones_and_gems::StonesNGemsState::StonesNGemsState (const StonesNGemsState &) default
Referenced by Clone().
StonesNGemsState() [2/2]
open_spiel::stones_and_gems::StonesNGemsState::StonesNGemsState (std::shared_ptr< const Game > game, int steps_remaining, int magic_wall_steps, bool magic_active, int blob_max_size, int blob_size, int blob_chance, Element blob_swap, bool blob_enclosed, int gems_required, int gems_collected, int current_reward, int sum_reward, Grid grid, bool obs_show_ids, int id_counter, Player player)
Definition at line 1165 of file stones_and_gems.cc.
    : State(game),
      steps_remaining_(steps_remaining),
      magic_wall_steps_(magic_wall_steps),
      magic_active_(magic_active),
      blob_max_size_(blob_max_size),
      blob_size_(blob_size),
      blob_chance_(blob_chance),
      blob_swap_(blob_swap),
      blob_enclosed_(blob_enclosed),
      gems_required_(gems_required),
      gems_collected_(gems_collected),
      current_reward_(current_reward),
      sum_reward_(sum_reward),
      grid_(grid),
      obs_show_ids_(obs_show_ids),
      id_counter_(id_counter),
      cur_player_(player) {}
Member Function Documentation
ActionToString()
std::string open_spiel::stones_and_gems::StonesNGemsState::ActionToString (Player player, Action move_id) const override virtual
Implements open_spiel::State.
Definition at line 437 of file stones_and_gems.cc.
{
  if (player == kChancePlayerId) {
    return absl::StrCat("Chance outcome: ", move_id);
  } else {
    SPIEL_CHECK_GE(move_id, 0);
    SPIEL_CHECK_LT(move_id, kNumActions);
    if (kActionsToString.find(move_id) == kActionsToString.end()) {
      SpielFatalError("Unknown move_id");
    }
    return kActionsToString.at(move_id);
  }
}
References open_spiel::kChancePlayerId, open_spiel::stones_and_gems::kNumActions, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and absl::StrCat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::stones_and_gems::StonesNGemsState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 1096 of file stones_and_gems.cc.
          {
  SPIEL_CHECK_TRUE(IsChanceNode());
  std::vector<std::pair<Action, double>> outcomes = {std::make_pair(0, 1.0)};
  return outcomes;
}
References open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::stones_and_gems::StonesNGemsState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 1161 of file stones_and_gems.cc.
{
  return std::unique_ptr<State>(new StonesNGemsState(*this));
}
References StonesNGemsState().
CurrentPlayer()
int open_spiel::stones_and_gems::StonesNGemsState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 501 of file stones_and_gems.cc.
{
  return IsTerminal() ? kTerminalPlayerId : cur_player_;
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::stones_and_gems::StonesNGemsState::DoApplyAction (Action move_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 1034 of file stones_and_gems.cc.
{
  if (cur_player_ == kChancePlayerId) {
    // Check each cell and apply respective dynamics function
    for (int index = 0; index < grid_.num_cols * grid_.num_rows; ++index) {
      Element &e = grid_.elements[index];
      if (e.has_updated) {
        continue;
      } else if (e == kElStone) {
        UpdateStone(index);
      } else if (e == kElStoneFalling) {
        UpdateStoneFalling(index);
      } else if (e == kElDiamond) {
        UpdateDiamond(index);
      } else if (e == kElDiamondFalling) {
        UpdateDiamondFalling(index);
      } else if (e == kElNut) {
        UpdateNut(index);
      } else if (e == kElNutFalling) {
        UpdateNutFalling(index);
      } else if (e == kElBomb) {
        UpdateBomb(index);
      } else if (e == kElBombFalling) {
        UpdateBombFalling(index);
      } else if (e == kElExitClosed) {
        UpdateExit(index);
      } else if (IsButterfly(e)) {
        UpdateButterfly(index, kButterflyToDirection.at(e));
      } else if (IsFirefly(e)) {
        UpdateFirefly(index, kFireflyToDirection.at(e));
      } else if (IsOrange(e)) {
        UpdateOrange(index, kOrangeToDirection.at(e));
      } else if (IsMagicWall(e)) {
        UpdateMagicWall(index);
      } else if (e == kElBlob) {
        UpdateBlob(index);
      } else if (IsExplosion(e)) {
        UpdateExplosions(index);
      }
    }
    EndScan();
    cur_player_ = 0;
  } else {
    StartScan();
    // Find where the agent is, and update its position
    auto it = std::find(grid_.elements.begin(), grid_.elements.end(), kElAgent);
    int index = std::distance(grid_.elements.begin(), it);
    UpdateAgent(index, move);
    cur_player_ = kChancePlayerId;
  }
}
References open_spiel::stones_and_gems::Grid::elements, open_spiel::kChancePlayerId, open_spiel::stones_and_gems::Grid::num_cols, and open_spiel::stones_and_gems::Grid::num_rows.
IsTerminal()
bool open_spiel::stones_and_gems::StonesNGemsState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 451 of file stones_and_gems.cc.
{
  // Time complete or the agent exploded
  auto it = std::find(grid_.elements.begin(), grid_.elements.end(), kElAgent);
  return steps_remaining_ <= 0 || it == grid_.elements.end();
}
References open_spiel::stones_and_gems::Grid::elements.
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::stones_and_gems::StonesNGemsState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 1085 of file stones_and_gems.cc.
{
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else if (IsTerminal()) {
    return {};
  } else {
    return {Directions::kNone, Directions::kUp, Directions::kRight,
            Directions::kDown, Directions::kLeft};
  }
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::stones_and_gems::kDown, open_spiel::stones_and_gems::kLeft, open_spiel::stones_and_gems::kNone, open_spiel::stones_and_gems::kRight, open_spiel::stones_and_gems::kUp, and open_spiel::State::LegalChanceOutcomes().
ObservationString()
std::string open_spiel::stones_and_gems::StonesNGemsState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 467 of file stones_and_gems.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (IsChanceNode()) {
    return "ChanceNode -- no observation";
  }
  return ToString();
}
References open_spiel::State::IsChanceNode(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::stones_and_gems::StonesNGemsState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 476 of file stones_and_gems.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // Treat `values` as a 3-d tensor.
  TensorView<3> view(
      values, {kNumVisibleCellType, grid_.num_rows, grid_.num_cols}, true);
  // No observations at chance nodes.
  if (IsChanceNode()) {
    std::fill(values.begin(), values.end(), 0);
    return;
  }
  int i = 0;
  for (int row = 0; row < grid_.num_rows; ++row) {
    for (int col = 0; col < grid_.num_cols; ++col) {
      int channel = static_cast<int>(grid_.elements[i].visible_type);
      view[{channel, row, col}] = obs_show_ids_ ? grid_.ids[i] : 1.0;
      ++i;
    }
  }
}
References open_spiel::stones_and_gems::Grid::elements, i, open_spiel::stones_and_gems::Grid::ids, open_spiel::State::IsChanceNode(), open_spiel::stones_and_gems::kNumVisibleCellType, open_spiel::stones_and_gems::Grid::num_cols, open_spiel::State::num_players_, open_spiel::stones_and_gems::Grid::num_rows, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::stones_and_gems::StonesNGemsState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 457 of file stones_and_gems.cc.
{
  // Sum of rewards, and should agree with Rewards()
  return {static_cast<double>(sum_reward_)};
}
Rewards()
std::vector< double > open_spiel::stones_and_gems::StonesNGemsState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 462 of file stones_and_gems.cc.
{
  // reward for most recent state transition
  return {static_cast<double>(current_reward_)};
}
Serialize()
std::string open_spiel::stones_and_gems::StonesNGemsState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 1123 of file stones_and_gems.cc.
{
  std::string out_str;
  // grid properties
  absl::StrAppend(&out_str, grid_.num_cols, ",");
  absl::StrAppend(&out_str, grid_.num_rows, ",");
  absl::StrAppend(&out_str, steps_remaining_, ",");
  absl::StrAppend(&out_str, magic_wall_steps_, ",");
  absl::StrAppend(&out_str, magic_active_, ",");
  absl::StrAppend(&out_str, blob_max_size_, ",");
  absl::StrAppend(&out_str, blob_size_, ",");
  absl::StrAppend(&out_str, blob_chance_, ",");
  absl::StrAppend(&out_str, static_cast<int>(blob_swap_.cell_type), ",");
  absl::StrAppend(&out_str, blob_enclosed_, ",");
  absl::StrAppend(&out_str, gems_required_, ",");
  absl::StrAppend(&out_str, gems_collected_, ",");
  absl::StrAppend(&out_str, current_reward_, ",");
  absl::StrAppend(&out_str, sum_reward_, ",");
  absl::StrAppend(&out_str, obs_show_ids_, ",");
  absl::StrAppend(&out_str, id_counter_, ",");
  absl::StrAppend(&out_str, cur_player_, "\n");
  // grid contents
  int col_counter = 0;
  for (std::size_t i = 0; i < grid_.elements.size(); ++i) {
    ++col_counter;
    absl::StrAppend(&out_str, static_cast<int>(grid_.elements[i].cell_type),
                    ",");
    absl::StrAppend(&out_str, grid_.ids[i], ",");
    if (col_counter == grid_.num_cols) {
      out_str.pop_back();
      absl::StrAppend(&out_str, "\n");
      col_counter = 0;
    }
  }
  // remove trailing newline
  out_str.pop_back();
  return out_str;
}
References open_spiel::stones_and_gems::Element::cell_type, open_spiel::stones_and_gems::Grid::elements, i, open_spiel::stones_and_gems::Grid::ids, open_spiel::stones_and_gems::Grid::num_cols, open_spiel::stones_and_gems::Grid::num_rows, and absl::StrAppend().
ToString()
std::string open_spiel::stones_and_gems::StonesNGemsState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 1103 of file stones_and_gems.cc.
{
  if (IsChanceNode()) {
    return "chance node";
  }
  std::string out_str;
  int col_counter = 0;
  for (const auto el : grid_.elements) {
    ++col_counter;
    out_str += el.id;
    if (col_counter == grid_.num_cols) {
      absl::StrAppend(&out_str, "\n");
      col_counter = 0;
    }
  }
  absl::StrAppend(&out_str, "time left: ", steps_remaining_, ", ");
  absl::StrAppend(&out_str, "gems required: ", gems_required_, ", ");
  absl::StrAppend(&out_str, "gems collectred: ", gems_collected_);
  return out_str;
}
References open_spiel::stones_and_gems::Grid::elements, open_spiel::State::IsChanceNode(), open_spiel::stones_and_gems::Grid::num_cols, and absl::StrAppend().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/stones_and_gems/stones_and_gems.h
open_spiel/games/stones_and_gems/stones_and_gems.cc