open spiel: absl::ByLength Class Reference
absl::ByLength Class Reference
#include <str_split.h>
Public Member Functions
ByLength (ptrdiff_t length)
absl::string_view Find (absl::string_view text, size_t pos) const
Detailed Description
Definition at line 213 of file str_split.h.
Constructor & Destructor Documentation
ByLength()
absl::ByLength::ByLength (ptrdiff_t length) explicit
Definition at line 122 of file str_split.cc.
                                   : length_(length) {
  ABSL_RAW_CHECK(length > 0, "");
}
References ABSL_RAW_CHECK.
Member Function Documentation
Find()
absl::string_view absl::ByLength::Find (absl::string_view text, size_t pos) const
Definition at line 126 of file str_split.cc.
{
  pos = std::min(pos, text.size());  // truncate `pos`
  absl::string_view substr = text.substr(pos);
  // If the string is shorter than the chunk size we say we
  // "can't find the delimiter" so this will be the last chunk.
  if (substr.length() <= static_cast<size_t>(length_))
    return absl::string_view(text.data() + text.size(), 0);
  return absl::string_view(substr.data() + length_, 0);
}
References absl::string_view::data(), absl::string_view::length(), and absl::string_view::substr().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/str_split.h
open_spiel/abseil-cpp/absl/strings/str_split.cc