open spiel: absl::synchronization_internal::PerThreadSem Class Reference
absl::synchronization_internal::PerThreadSem Class Reference
#include <per_thread_sem.h>
Public Member Functions
PerThreadSem ()=delete
PerThreadSem (const PerThreadSem &)=delete
PerThreadSem & operator= (const PerThreadSem &)=delete
Static Public Member Functions
static void Tick (base_internal::ThreadIdentity *identity)
static void SetThreadBlockedCounter (std::atomic< int > *counter)
static std::atomic< int > * GetThreadBlockedCounter ()
Friends
class PerThreadSemTest
class absl::Mutex
void OneTimeInitThreadIdentity (absl::base_internal::ThreadIdentity *identity)
Detailed Description
Definition at line 41 of file per_thread_sem.h.
Constructor & Destructor Documentation
PerThreadSem() [1/2]
absl::synchronization_internal::PerThreadSem::PerThreadSem () delete
PerThreadSem() [2/2]
absl::synchronization_internal::PerThreadSem::PerThreadSem (const PerThreadSem &) delete
Member Function Documentation
GetThreadBlockedCounter()
std::atomic< int > * absl::synchronization_internal::PerThreadSem::GetThreadBlockedCounter () static
Definition at line 37 of file per_thread_sem.cc.
{
  base_internal::ThreadIdentity *identity;
  identity = GetOrCreateCurrentThreadIdentity();
  return identity->blocked_count_ptr;
}
References absl::base_internal::ThreadIdentity::blocked_count_ptr, and absl::synchronization_internal::GetOrCreateCurrentThreadIdentity().
operator=()
PerThreadSem & absl::synchronization_internal::PerThreadSem::operator= (const PerThreadSem &) delete
SetThreadBlockedCounter()
void absl::synchronization_internal::PerThreadSem::SetThreadBlockedCounter (std::atomic< int > * counter) static
Definition at line 31 of file per_thread_sem.cc.
{
  base_internal::ThreadIdentity *identity;
  identity = GetOrCreateCurrentThreadIdentity();
  identity->blocked_count_ptr = counter;
}
References absl::base_internal::ThreadIdentity::blocked_count_ptr, counter, and absl::synchronization_internal::GetOrCreateCurrentThreadIdentity().
Tick()
void absl::synchronization_internal::PerThreadSem::Tick (base_internal::ThreadIdentity * identity) static
Definition at line 50 of file per_thread_sem.cc.
{
  const int ticker =
      identity->ticker.fetch_add(1, std::memory_order_relaxed) + 1;
  const int wait_start = identity->wait_start.load(std::memory_order_relaxed);
  const bool is_idle = identity->is_idle.load(std::memory_order_relaxed);
  if (wait_start && (ticker - wait_start > Waiter::kIdlePeriods) && !is_idle) {
    // Wakeup the waiting thread since it is time for it to become idle.
    Waiter::GetWaiter(identity)->Poke();
  }
}
References absl::synchronization_internal::Waiter::GetWaiter(), absl::base_internal::ThreadIdentity::is_idle, absl::synchronization_internal::Waiter::kIdlePeriods, absl::synchronization_internal::Waiter::Poke(), absl::base_internal::ThreadIdentity::ticker, and absl::base_internal::ThreadIdentity::wait_start.
Referenced by absl::synchronization_internal::PerThreadSemTest::Tick().
Friends And Related Symbol Documentation
absl::Mutex
friend class absl::Mutex friend
Definition at line 79 of file per_thread_sem.h.
OneTimeInitThreadIdentity
void OneTimeInitThreadIdentity (absl::base_internal::ThreadIdentity * identity) friend
Definition at line 72 of file create_thread_identity.cc.
{
  PerThreadSem::Init(identity);
}
PerThreadSemTest
friend class PerThreadSemTest friend
Definition at line 78 of file per_thread_sem.h.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/synchronization/internal/per_thread_sem.h
open_spiel/abseil-cpp/absl/synchronization/internal/per_thread_sem.cc