open spiel: open_spiel::crowd_modelling::CrowdModellingGame Class Reference
open_spiel::crowd_modelling::CrowdModellingGame Class Reference
#include <crowd_modelling.h>
Public Member Functions
CrowdModellingGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
std::vector< int > ObservationTensorShape () const override
int MaxChanceOutcomes () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 117 of file crowd_modelling.h.
Constructor & Destructor Documentation
CrowdModellingGame()
open_spiel::crowd_modelling::CrowdModellingGame::CrowdModellingGame (const GameParameters & params) explicit
Definition at line 233 of file crowd_modelling.cc.
    : Game(kGameType, params),
      size_(ParameterValue<int>("size", kDefaultSize)),
      horizon_(ParameterValue<int>("horizon", kDefaultHorizon)) {}
Member Function Documentation
DeserializeState()
std::unique_ptr< State > open_spiel::crowd_modelling::CrowdModellingGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 243 of file crowd_modelling.cc.
{
  std::vector<std::string> lines = absl::StrSplit(str, '\n');
  if (lines.size() != 2) {
    SpielFatalError(absl::StrCat("Expected 2 lines in serialized state, got: ",
                                 lines.size()));
  }
  Player current_player;
  int is_chance_init;
  int x;
  int t;
  int last_action;
  double return_value;
  std::vector<std::string> properties = absl::StrSplit(lines[0], ',');
  if (properties.size() != 6) {
    SpielFatalError(
        absl::StrCat("Expected 6 properties for serialized state, got: ",
                     properties.size()));
  }
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[0], &current_player));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[1], &is_chance_init));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[2], &x));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[3], &t));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[4], &last_action));
  SPIEL_CHECK_TRUE(absl::SimpleAtod(properties[5], &return_value));
  std::vector<std::string> serialized_distrib = absl::StrSplit(lines[1], ',');
  std::vector<double> distribution;
  distribution.reserve(serialized_distrib.size());
  for (std::string& v : serialized_distrib) {
    double parsed_weight;
    SPIEL_CHECK_TRUE(absl::SimpleAtod(v, &parsed_weight));
    distribution.push_back(parsed_weight);
  }
  return absl::make_unique<CrowdModellingState>(
      shared_from_this(), size_, horizon_, current_player, is_chance_init, x, t,
      last_action, return_value, distribution);
}
References absl::SimpleAtod(), absl::SimpleAtoi(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), absl::StrCat(), absl::StrSplit(), and x.
MaxChanceNodesInHistory()
int open_spiel::crowd_modelling::CrowdModellingGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 133 of file crowd_modelling.h.
{
    // + 1 to account for the initial extra chance node.
    return horizon_ + 1;
  }
MaxChanceOutcomes()
int open_spiel::crowd_modelling::CrowdModellingGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 138 of file crowd_modelling.h.
{
    return std::max(size_, kNumChanceActions);
  }
References open_spiel::crowd_modelling::kNumChanceActions.
MaxGameLength()
int open_spiel::crowd_modelling::CrowdModellingGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 132 of file crowd_modelling.h.
{ return horizon_; }
MaxUtility()
double open_spiel::crowd_modelling::CrowdModellingGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 129 of file crowd_modelling.h.
{
    return std::numeric_limits<double>::infinity();
  }
MinUtility()
double open_spiel::crowd_modelling::CrowdModellingGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 126 of file crowd_modelling.h.
{
    return -std::numeric_limits<double>::infinity();
  }
NewInitialState()
std::unique_ptr< State > open_spiel::crowd_modelling::CrowdModellingGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 121 of file crowd_modelling.h.
{
    return absl::make_unique<CrowdModellingState>(shared_from_this(), size_,
                                                  horizon_);
  }
NumDistinctActions()
int open_spiel::crowd_modelling::CrowdModellingGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 120 of file crowd_modelling.h.
{ return kNumActions; }
References open_spiel::crowd_modelling::kNumActions.
NumPlayers()
int open_spiel::crowd_modelling::CrowdModellingGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 125 of file crowd_modelling.h.
{ return kNumPlayers; }
References open_spiel::crowd_modelling::kNumPlayers.
ObservationTensorShape()
std::vector< int > open_spiel::crowd_modelling::CrowdModellingGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 238 of file crowd_modelling.cc.
{
  // +1 to allow for t_ == horizon.
  return {size_ + horizon_ + 1};
}
The documentation for this class was generated from the following files:
open_spiel/games/mfg/crowd_modelling.h
open_spiel/games/mfg/crowd_modelling.cc