open spiel: absl::MutexLock Class Reference
absl::MutexLock Class Reference
#include <mutex.h>
Public Member Functions
MutexLock (Mutex *mu) ABSL_EXCLUSIVE_LOCK_FUNCTION(mu)
MutexLock (Mutex *mu, const Condition &cond) ABSL_EXCLUSIVE_LOCK_FUNCTION(mu)
MutexLock (const MutexLock &)=delete
MutexLock (MutexLock &&)=delete
MutexLock & operator= (const MutexLock &)=delete
MutexLock & operator= (MutexLock &&)=delete
~MutexLock () ABSL_UNLOCK_FUNCTION()
Detailed Description
Definition at line 527 of file mutex.h.
Constructor & Destructor Documentation
MutexLock() [1/4]
absl::MutexLock::MutexLock (Mutex * mu) inline explicit
Definition at line 534 of file mutex.h.
                                                                 : mu_(mu) {
    this->mu_->Lock();
  }
References absl::Mutex::Lock().
MutexLock() [2/4]
absl::MutexLock::MutexLock (Mutex * mu, const Condition & cond) inline explicit
Definition at line 541 of file mutex.h.
      : mu_(mu) {
    this->mu_->LockWhen(cond);
  }
References absl::Mutex::LockWhen().
MutexLock() [3/4]
absl::MutexLock::MutexLock (const MutexLock &) delete
MutexLock() [4/4]
absl::MutexLock::MutexLock (MutexLock &&) delete
~MutexLock()
absl::MutexLock::~MutexLock () inline
Definition at line 552 of file mutex.h.
{ this->mu_->Unlock(); }
References absl::Mutex::Unlock().
Member Function Documentation
operator=() [1/2]
MutexLock & absl::MutexLock::operator= (const MutexLock &) delete
operator=() [2/2]
MutexLock & absl::MutexLock::operator= (MutexLock &&) delete
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/synchronization/mutex.h