open spiel: absl::container_internal::btree_container< Tree > Class Template Reference
absl::container_internal::btree_container< Tree > Class Template Reference
#include <btree_container.h>
Classes
struct extract_and_get_next_return_type
Public Types
using key_type = typename Tree::key_type
using value_type = typename Tree::value_type
using size_type = typename Tree::size_type
using difference_type = typename Tree::difference_type
using key_compare = typename Tree::original_key_compare
using value_compare = typename Tree::value_compare
using allocator_type = typename Tree::allocator_type
using reference = typename Tree::reference
using const_reference = typename Tree::const_reference
using pointer = typename Tree::pointer
using const_pointer = typename Tree::const_pointer
using iterator = typename Tree::iterator
using const_iterator = typename Tree::const_iterator
using reverse_iterator = typename Tree::reverse_iterator
using const_reverse_iterator = typename Tree::const_reverse_iterator
using node_type = typename Tree::node_handle_type
Public Member Functions
btree_container ()
btree_container (const key_compare &comp, const allocator_type &alloc=allocator_type())
btree_container (const allocator_type &alloc)
btree_container (const btree_container &other)
btree_container (const btree_container &other, const allocator_type &alloc)
btree_container (btree_container &&other) noexcept(std::is_nothrow_move_constructible< Tree >::value)=default
btree_container (btree_container &&other, const allocator_type &alloc)
btree_container & operator= (const btree_container &other)=default
btree_container & operator= (btree_container &&other) noexcept(std::is_nothrow_move_assignable< Tree >::value)=default
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
template<typename K = key_type>
size_type count (const key_arg< K > &key) const
template<typename K = key_type>
iterator find (const key_arg< K > &key)
template<typename K = key_type>
const_iterator find (const key_arg< K > &key) const
template<typename K = key_type>
bool contains (const key_arg< K > &key) const
template<typename K = key_type>
iterator lower_bound (const key_arg< K > &key)
template<typename K = key_type>
const_iterator lower_bound (const key_arg< K > &key) const
template<typename K = key_type>
iterator upper_bound (const key_arg< K > &key)
template<typename K = key_type>
const_iterator upper_bound (const key_arg< K > &key) const
template<typename K = key_type>
std::pair< iterator, iterator > equal_range (const key_arg< K > &key)
template<typename K = key_type>
std::pair< const_iterator, const_iterator > equal_range (const key_arg< K > &key) const
iterator erase (const_iterator iter)
iterator erase (iterator iter)
iterator erase (const_iterator first, const_iterator last)
template<typename K = key_type>
size_type erase (const key_arg< K > &key)
extract_and_get_next_return_type extract_and_get_next (const_iterator position)
node_type extract (iterator position)
node_type extract (const_iterator position)
ABSL_ATTRIBUTE_REINITIALIZES void clear ()
void swap (btree_container &other)
void verify () const
size_type size () const
size_type max_size () const
bool empty () const
allocator_type get_allocator () const
key_compare key_comp () const
value_compare value_comp () const
Protected Types
template<class K >
using key_arg
Protected Attributes
Tree tree_
Friends
struct btree_access
bool operator== (const btree_container &x, const btree_container &y)
bool operator!= (const btree_container &x, const btree_container &y)
bool operator< (const btree_container &x, const btree_container &y)
bool operator> (const btree_container &x, const btree_container &y)
bool operator<= (const btree_container &x, const btree_container &y)
bool operator>= (const btree_container &x, const btree_container &y)
template<typename State >
State AbslHashValue (State h, const btree_container &b)
Detailed Description
template<typename Tree>
class absl::container_internal::btree_container< Tree >
Definition at line 37 of file btree_container.h.
Member Typedef Documentation
allocator_type
template<typename Tree > using absl::container_internal::btree_container< Tree >::allocator_type = typename Tree::allocator_type
Definition at line 57 of file btree_container.h.
const_iterator
template<typename Tree > using absl::container_internal::btree_container< Tree >::const_iterator = typename Tree::const_iterator
Definition at line 63 of file btree_container.h.
const_pointer
template<typename Tree > using absl::container_internal::btree_container< Tree >::const_pointer = typename Tree::const_pointer
Definition at line 61 of file btree_container.h.
const_reference
template<typename Tree > using absl::container_internal::btree_container< Tree >::const_reference = typename Tree::const_reference
Definition at line 59 of file btree_container.h.
const_reverse_iterator
template<typename Tree > using absl::container_internal::btree_container< Tree >::const_reverse_iterator = typename Tree::const_reverse_iterator
Definition at line 65 of file btree_container.h.
difference_type
template<typename Tree > using absl::container_internal::btree_container< Tree >::difference_type = typename Tree::difference_type
Definition at line 54 of file btree_container.h.
iterator
template<typename Tree > using absl::container_internal::btree_container< Tree >::iterator = typename Tree::iterator
Definition at line 62 of file btree_container.h.
key_arg
template<typename Tree > template<class K > using absl::container_internal::btree_container< Tree >::key_arg protected
Initial value:
      typename KeyArg<params_type::kIsKeyCompareTransparent>::template type<
          K, typename Tree::key_type>
Definition at line 46 of file btree_container.h.
key_compare
template<typename Tree > using absl::container_internal::btree_container< Tree >::key_compare = typename Tree::original_key_compare
Definition at line 55 of file btree_container.h.
key_type
template<typename Tree > using absl::container_internal::btree_container< Tree >::key_type = typename Tree::key_type
Definition at line 51 of file btree_container.h.
node_type
template<typename Tree > using absl::container_internal::btree_container< Tree >::node_type = typename Tree::node_handle_type
Definition at line 66 of file btree_container.h.
pointer
template<typename Tree > using absl::container_internal::btree_container< Tree >::pointer = typename Tree::pointer
Definition at line 60 of file btree_container.h.
reference
template<typename Tree > using absl::container_internal::btree_container< Tree >::reference = typename Tree::reference
Definition at line 58 of file btree_container.h.
reverse_iterator
template<typename Tree > using absl::container_internal::btree_container< Tree >::reverse_iterator = typename Tree::reverse_iterator
Definition at line 64 of file btree_container.h.
size_type
template<typename Tree > using absl::container_internal::btree_container< Tree >::size_type = typename Tree::size_type
Definition at line 53 of file btree_container.h.
value_compare
template<typename Tree > using absl::container_internal::btree_container< Tree >::value_compare = typename Tree::value_compare
Definition at line 56 of file btree_container.h.
value_type
template<typename Tree > using absl::container_internal::btree_container< Tree >::value_type = typename Tree::value_type
Definition at line 52 of file btree_container.h.
Constructor & Destructor Documentation
btree_container() [1/7]
template<typename Tree > absl::container_internal::btree_container< Tree >::btree_container () inline
Definition at line 74 of file btree_container.h.
: tree_(key_compare(), allocator_type()) {}
btree_container() [2/7]
template<typename Tree > absl::container_internal::btree_container< Tree >::btree_container (const key_compare & comp, const allocator_type & alloc = allocator_type()) inline explicit
Definition at line 75 of file btree_container.h.
      : tree_(comp, alloc) {}
btree_container() [3/7]
template<typename Tree > absl::container_internal::btree_container< Tree >::btree_container (const allocator_type & alloc) inline explicit
Definition at line 78 of file btree_container.h.
      : tree_(key_compare(), alloc) {}
btree_container() [4/7]
template<typename Tree > absl::container_internal::btree_container< Tree >::btree_container (const btree_container< Tree > & other) inline
Definition at line 81 of file btree_container.h.
      : btree_container(other, absl::allocator_traits<allocator_type>::
                                   select_on_container_copy_construction(
                                       other.get_allocator())) {}
btree_container() [5/7]
template<typename Tree > absl::container_internal::btree_container< Tree >::btree_container (const btree_container< Tree > & other, const allocator_type & alloc) inline
Definition at line 85 of file btree_container.h.
      : tree_(other.tree_, alloc) {}
btree_container() [6/7]
template<typename Tree > absl::container_internal::btree_container< Tree >::btree_container (btree_container< Tree > && other) const default noexcept
btree_container() [7/7]
template<typename Tree > absl::container_internal::btree_container< Tree >::btree_container (btree_container< Tree > && other, const allocator_type & alloc) inline
Definition at line 90 of file btree_container.h.
      : tree_(std::move(other.tree_), alloc) {}
Member Function Documentation
begin() [1/2]
template<typename Tree > iterator absl::container_internal::btree_container< Tree >::begin () inline
Definition at line 98 of file btree_container.h.
{ return tree_.begin(); }
References absl::container_internal::btree_container< Tree >::tree_.
Referenced by open_spiel::algorithms::TabularBestResponse::BestResponseActions(), absl::container_internal::btree_multiset_container< Tree >::merge(), and absl::container_internal::btree_set_container< Tree >::merge().
begin() [2/2]
template<typename Tree > const_iterator absl::container_internal::btree_container< Tree >::begin () const inline
Definition at line 99 of file btree_container.h.
{ return tree_.begin(); }
References absl::container_internal::btree_container< Tree >::tree_.
cbegin()
template<typename Tree > const_iterator absl::container_internal::btree_container< Tree >::cbegin () const inline
Definition at line 100 of file btree_container.h.
{ return tree_.begin(); }
References absl::container_internal::btree_container< Tree >::tree_.
cend()
template<typename Tree > const_iterator absl::container_internal::btree_container< Tree >::cend () const inline
Definition at line 103 of file btree_container.h.
{ return tree_.end(); }
References absl::container_internal::btree_container< Tree >::tree_.
clear()
template<typename Tree > ABSL_ATTRIBUTE_REINITIALIZES void absl::container_internal::btree_container< Tree >::clear () inline
Definition at line 195 of file btree_container.h.
{ tree_.clear(); }
References absl::container_internal::btree_container< Tree >::tree_.
Referenced by absl::container_internal::btree_multiset_container< Tree >::merge().
contains()
template<typename Tree > template<typename K = key_type> bool absl::container_internal::btree_container< Tree >::contains (const key_arg< K > & key) const inline
Definition at line 126 of file btree_container.h.
{
    return find(key) != end();
  }
References absl::container_internal::btree_container< Tree >::end(), absl::container_internal::btree_container< Tree >::find(), and key.
count()
template<typename Tree > template<typename K = key_type> size_type absl::container_internal::btree_container< Tree >::count (const key_arg< K > & key) const inline
Definition at line 113 of file btree_container.h.
{
    auto equal_range = this->equal_range(key);
    return equal_range.second - equal_range.first;
  }
References absl::container_internal::btree_container< Tree >::equal_range().
Referenced by open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_add_to_queue_count_weighted(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_lcb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_ucb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_ucb_standard_factor(), open_spiel::algorithms::TabularBestResponse::BestResponseActions(), open_spiel::testing::CheckChanceOutcomes(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::compute_total_steps(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::delta(), and open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::update_mean_and_count().
crbegin()
template<typename Tree > const_reverse_iterator absl::container_internal::btree_container< Tree >::crbegin () const inline
Definition at line 106 of file btree_container.h.
{ return tree_.rbegin(); }
References absl::container_internal::btree_container< Tree >::tree_.
crend()
template<typename Tree > const_reverse_iterator absl::container_internal::btree_container< Tree >::crend () const inline
Definition at line 109 of file btree_container.h.
{ return tree_.rend(); }
References absl::container_internal::btree_container< Tree >::tree_.
empty()
template<typename Tree > bool absl::container_internal::btree_container< Tree >::empty () const inline
Definition at line 202 of file btree_container.h.
{ return tree_.empty(); }
References absl::container_internal::btree_container< Tree >::tree_.
Referenced by open_spiel::algorithms::TabularBestResponse::BestResponseActions().
end() [1/2]
template<typename Tree > iterator absl::container_internal::btree_container< Tree >::end () inline
Definition at line 101 of file btree_container.h.
{ return tree_.end(); }
References absl::container_internal::btree_container< Tree >::tree_.
Referenced by absl::container_internal::btree_map_container< Tree >::at(), absl::container_internal::btree_map_container< Tree >::at(), open_spiel::algorithms::TabularBestResponse::BestResponseActions(), absl::container_internal::btree_container< Tree >::contains(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::merge(), and absl::container_internal::btree_set_container< Tree >::merge().
end() [2/2]
template<typename Tree > const_iterator absl::container_internal::btree_container< Tree >::end () const inline
Definition at line 102 of file btree_container.h.
{ return tree_.end(); }
References absl::container_internal::btree_container< Tree >::tree_.
equal_range() [1/2]
template<typename Tree > template<typename K = key_type> std::pair< iterator, iterator > absl::container_internal::btree_container< Tree >::equal_range (const key_arg< K > & key) inline
Definition at line 146 of file btree_container.h.
{
    return tree_.equal_range(key);
  }
References key, and absl::container_internal::btree_container< Tree >::tree_.
Referenced by absl::container_internal::btree_container< Tree >::count(), and absl::container_internal::btree_container< Tree >::erase().
equal_range() [2/2]
template<typename Tree > template<typename K = key_type> std::pair< const_iterator, const_iterator > absl::container_internal::btree_container< Tree >::equal_range (const key_arg< K > & key) const inline
Definition at line 150 of file btree_container.h.
{
    return tree_.equal_range(key);
  }
References key, and absl::container_internal::btree_container< Tree >::tree_.
erase() [1/4]
template<typename Tree > template<typename K = key_type> size_type absl::container_internal::btree_container< Tree >::erase (const key_arg< K > & key) inline
Definition at line 167 of file btree_container.h.
{
    auto equal_range = this->equal_range(key);
    return tree_.erase_range(equal_range.first, equal_range.second).first;
  }
References absl::container_internal::btree_container< Tree >::equal_range(), and absl::container_internal::btree_container< Tree >::tree_.
erase() [2/4]
template<typename Tree > iterator absl::container_internal::btree_container< Tree >::erase (const_iterator first, const_iterator last) inline
Definition at line 163 of file btree_container.h.
{
    return tree_.erase_range(iterator(first), iterator(last)).second;
  }
References first, and absl::container_internal::btree_container< Tree >::tree_.
erase() [3/4]
template<typename Tree > iterator absl::container_internal::btree_container< Tree >::erase (const_iterator iter) inline
Definition at line 161 of file btree_container.h.
{ return tree_.erase(iterator(iter)); }
References absl::container_internal::btree_container< Tree >::tree_.
Referenced by absl::container_internal::btree_container< Tree >::extract(), absl::container_internal::btree_container< Tree >::extract_and_get_next(), and absl::container_internal::btree_set_container< Tree >::merge().
erase() [4/4]
template<typename Tree > iterator absl::container_internal::btree_container< Tree >::erase (iterator iter) inline
Definition at line 162 of file btree_container.h.
{ return tree_.erase(iter); }
References absl::container_internal::btree_container< Tree >::tree_.
extract() [1/2]
template<typename Tree > node_type absl::container_internal::btree_container< Tree >::extract (const_iterator position) inline
Definition at line 190 of file btree_container.h.
{
    return extract(iterator(position));
  }
References absl::container_internal::btree_container< Tree >::extract().
extract() [2/2]
template<typename Tree > node_type absl::container_internal::btree_container< Tree >::extract (iterator position) inline
Definition at line 182 of file btree_container.h.
{
    // Use Construct instead of Transfer because the rebalancing code will
    // destroy the slot later.
    auto node =
        CommonAccess::Construct<node_type>(get_allocator(), position.slot());
    erase(position);
    return node;
  }
References absl::container_internal::CommonAccess::Construct(), absl::container_internal::btree_container< Tree >::erase(), and absl::container_internal::btree_container< Tree >::get_allocator().
Referenced by absl::container_internal::btree_container< Tree >::extract().
extract_and_get_next()
template<typename Tree > extract_and_get_next_return_type absl::container_internal::btree_container< Tree >::extract_and_get_next (const_iterator position) inline
Definition at line 173 of file btree_container.h.
{
    // Use Construct instead of Transfer because the rebalancing code will
    // destroy the slot later.
    // Note: we rely on erase() taking place after Construct().
    return {CommonAccess::Construct<node_type>(get_allocator(),
                                               iterator(position).slot()),
            erase(position)};
  }
References absl::container_internal::CommonAccess::Construct(), absl::container_internal::btree_container< Tree >::erase(), and absl::container_internal::btree_container< Tree >::get_allocator().
find() [1/2]
template<typename Tree > template<typename K = key_type> iterator absl::container_internal::btree_container< Tree >::find (const key_arg< K > & key) inline
Definition at line 118 of file btree_container.h.
{
    return tree_.find(key);
  }
References key, and absl::container_internal::btree_container< Tree >::tree_.
Referenced by absl::container_internal::btree_map_container< Tree >::at(), absl::container_internal::btree_map_container< Tree >::at(), and absl::container_internal::btree_container< Tree >::contains().
find() [2/2]
template<typename Tree > template<typename K = key_type> const_iterator absl::container_internal::btree_container< Tree >::find (const key_arg< K > & key) const inline
Definition at line 122 of file btree_container.h.
{
    return tree_.find(key);
  }
References key, and absl::container_internal::btree_container< Tree >::tree_.
get_allocator()
template<typename Tree > allocator_type absl::container_internal::btree_container< Tree >::get_allocator () const inline
Definition at line 230 of file btree_container.h.
{ return tree_.get_allocator(); }
References absl::container_internal::btree_container< Tree >::tree_.
Referenced by absl::container_internal::btree_multiset_container< Tree >::emplace(), absl::container_internal::btree_set_container< Tree >::emplace(), absl::container_internal::btree_multiset_container< Tree >::emplace_hint(), absl::container_internal::btree_set_container< Tree >::emplace_hint(), absl::container_internal::btree_container< Tree >::extract(), and absl::container_internal::btree_container< Tree >::extract_and_get_next().
key_comp()
template<typename Tree > key_compare absl::container_internal::btree_container< Tree >::key_comp () const inline
Definition at line 233 of file btree_container.h.
{ return key_compare(tree_.key_comp()); }
References absl::container_internal::btree_container< Tree >::tree_.
lower_bound() [1/2]
template<typename Tree > template<typename K = key_type> iterator absl::container_internal::btree_container< Tree >::lower_bound (const key_arg< K > & key) inline
Definition at line 130 of file btree_container.h.
{
    return tree_.lower_bound(key);
  }
References key, and absl::container_internal::btree_container< Tree >::tree_.
lower_bound() [2/2]
template<typename Tree > template<typename K = key_type> const_iterator absl::container_internal::btree_container< Tree >::lower_bound (const key_arg< K > & key) const inline
Definition at line 134 of file btree_container.h.
{
    return tree_.lower_bound(key);
  }
References key, and absl::container_internal::btree_container< Tree >::tree_.
max_size()
template<typename Tree > size_type absl::container_internal::btree_container< Tree >::max_size () const inline
Definition at line 201 of file btree_container.h.
{ return tree_.max_size(); }
References absl::container_internal::btree_container< Tree >::tree_.
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
operator=() [1/2]
template<typename Tree > btree_container & absl::container_internal::btree_container< Tree >::operator= (btree_container< Tree > && other) default noexcept
operator=() [2/2]
template<typename Tree > btree_container & absl::container_internal::btree_container< Tree >::operator= (const btree_container< Tree > & other) default
rbegin() [1/2]
template<typename Tree > reverse_iterator absl::container_internal::btree_container< Tree >::rbegin () inline
Definition at line 104 of file btree_container.h.
{ return tree_.rbegin(); }
References absl::container_internal::btree_container< Tree >::tree_.
rbegin() [2/2]
template<typename Tree > const_reverse_iterator absl::container_internal::btree_container< Tree >::rbegin () const inline
Definition at line 105 of file btree_container.h.
{ return tree_.rbegin(); }
References absl::container_internal::btree_container< Tree >::tree_.
rend() [1/2]
template<typename Tree > reverse_iterator absl::container_internal::btree_container< Tree >::rend () inline
Definition at line 107 of file btree_container.h.
{ return tree_.rend(); }
References absl::container_internal::btree_container< Tree >::tree_.
rend() [2/2]
template<typename Tree > const_reverse_iterator absl::container_internal::btree_container< Tree >::rend () const inline
Definition at line 108 of file btree_container.h.
{ return tree_.rend(); }
References absl::container_internal::btree_container< Tree >::tree_.
size()
template<typename Tree > size_type absl::container_internal::btree_container< Tree >::size () const inline
Definition at line 200 of file btree_container.h.
{ return tree_.size(); }
References absl::container_internal::btree_container< Tree >::tree_.
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel::algorithms::TabularBestResponse::BestResponseActions(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel::testing::CheckChanceOutcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::DistributionSupport(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
swap()
template<typename Tree > void absl::container_internal::btree_container< Tree >::swap (btree_container< Tree > & other) inline
Definition at line 196 of file btree_container.h.
{ tree_.swap(other.tree_); }
References absl::container_internal::btree_container< Tree >::tree_.
upper_bound() [1/2]
template<typename Tree > template<typename K = key_type> iterator absl::container_internal::btree_container< Tree >::upper_bound (const key_arg< K > & key) inline
Definition at line 138 of file btree_container.h.
{
    return tree_.upper_bound(key);
  }
References key, and absl::container_internal::btree_container< Tree >::tree_.
upper_bound() [2/2]
template<typename Tree > template<typename K = key_type> const_iterator absl::container_internal::btree_container< Tree >::upper_bound (const key_arg< K > & key) const inline
Definition at line 142 of file btree_container.h.
{
    return tree_.upper_bound(key);
  }
References key, and absl::container_internal::btree_container< Tree >::tree_.
value_comp()
template<typename Tree > value_compare absl::container_internal::btree_container< Tree >::value_comp () const inline
Definition at line 234 of file btree_container.h.
{ return tree_.value_comp(); }
References absl::container_internal::btree_container< Tree >::tree_.
verify()
template<typename Tree > void absl::container_internal::btree_container< Tree >::verify () const inline
Definition at line 197 of file btree_container.h.
{ tree_.verify(); }
References absl::container_internal::btree_container< Tree >::tree_.
Friends And Related Symbol Documentation
AbslHashValue
template<typename Tree > template<typename State > State AbslHashValue (State h, const btree_container< Tree > & b) friend
Definition at line 238 of file btree_container.h.
{
    for (const auto &v : b) {
      h = State::combine(std::move(h), v);
    }
    return State::combine(std::move(h), b.size());
  }
btree_access
template<typename Tree > friend struct btree_access friend
Definition at line 246 of file btree_container.h.
operator!=
template<typename Tree > bool operator!= (const btree_container< Tree > & x, const btree_container< Tree > & y) friend
Definition at line 209 of file btree_container.h.
{
    return !(x == y);
  }
operator<
template<typename Tree > bool operator< (const btree_container< Tree > & x, const btree_container< Tree > & y) friend
Definition at line 213 of file btree_container.h.
{
    return std::lexicographical_compare(x.begin(), x.end(), y.begin(), y.end());
  }
operator<=
template<typename Tree > bool operator<= (const btree_container< Tree > & x, const btree_container< Tree > & y) friend
Definition at line 221 of file btree_container.h.
{
    return !(y < x);
  }
operator==
template<typename Tree > bool operator== (const btree_container< Tree > & x, const btree_container< Tree > & y) friend
Definition at line 204 of file btree_container.h.
{
    if (x.size() != y.size()) return false;
    return std::equal(x.begin(), x.end(), y.begin());
  }
operator>
template<typename Tree > bool operator> (const btree_container< Tree > & x, const btree_container< Tree > & y) friend
Definition at line 217 of file btree_container.h.
{
    return y < x;
  }
operator>=
template<typename Tree > bool operator>= (const btree_container< Tree > & x, const btree_container< Tree > & y) friend
Definition at line 225 of file btree_container.h.
{
    return !(x < y);
  }
Member Data Documentation
tree_
template<typename Tree > Tree absl::container_internal::btree_container< Tree >::tree_ protected
Definition at line 247 of file btree_container.h.
Referenced by absl::container_internal::btree_container< Tree >::begin(), absl::container_internal::btree_container< Tree >::begin(), absl::container_internal::btree_container< Tree >::cbegin(), absl::container_internal::btree_container< Tree >::cend(), absl::container_internal::btree_container< Tree >::clear(), absl::container_internal::btree_container< Tree >::crbegin(), absl::container_internal::btree_container< Tree >::crend(), absl::container_internal::btree_multiset_container< Tree >::emplace(), absl::container_internal::btree_set_container< Tree >::emplace(), absl::container_internal::btree_multiset_container< Tree >::emplace_hint(), absl::container_internal::btree_set_container< Tree >::emplace_hint(), absl::container_internal::btree_container< Tree >::empty(), absl::container_internal::btree_container< Tree >::end(), absl::container_internal::btree_container< Tree >::end(), absl::container_internal::btree_container< Tree >::equal_range(), absl::container_internal::btree_container< Tree >::equal_range(), absl::container_internal::btree_container< Tree >::erase(), absl::container_internal::btree_container< Tree >::erase(), absl::container_internal::btree_container< Tree >::erase(), absl::container_internal::btree_container< Tree >::erase(), absl::container_internal::btree_multiset_container< Tree >::extract(), absl::container_internal::btree_set_container< Tree >::extract(), absl::container_internal::btree_container< Tree >::find(), absl::container_internal::btree_container< Tree >::find(), absl::container_internal::btree_container< Tree >::get_allocator(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_container< Tree >::key_comp(), absl::container_internal::btree_container< Tree >::lower_bound(), absl::container_internal::btree_container< Tree >::lower_bound(), absl::container_internal::btree_container< Tree >::max_size(), absl::container_internal::btree_container< Tree >::rbegin(), absl::container_internal::btree_container< Tree >::rbegin(), absl::container_internal::btree_container< Tree >::rend(), absl::container_internal::btree_container< Tree >::rend(), absl::container_internal::btree_container< Tree >::size(), absl::container_internal::btree_container< Tree >::swap(), absl::container_internal::btree_container< Tree >::upper_bound(), absl::container_internal::btree_container< Tree >::upper_bound(), absl::container_internal::btree_container< Tree >::value_comp(), and absl::container_internal::btree_container< Tree >::verify().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/btree_container.h