open spiel: open_spiel::stones_and_gems::StonesNGemsGame Class Reference
open_spiel::stones_and_gems::StonesNGemsGame Class Reference
#include <stones_and_gems.h>
Public Member Functions
StonesNGemsGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxGameLength () const override
int NumPlayers () const override
int MaxChanceOutcomes () const override
double MinUtility () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
std::string GetRNGState () const override
void SetRNGState (const std::string &rng_state) const override
std::mt19937 * rng () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Protected Member Functions
Grid ParseGrid (const std::string &grid_string, double blob_max_percentage)
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Additional Inherited Members
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 344 of file stones_and_gems.h.
Constructor & Destructor Documentation
StonesNGemsGame()
open_spiel::stones_and_gems::StonesNGemsGame::StonesNGemsGame (const GameParameters & params) explicit
Definition at line 1378 of file stones_and_gems.cc.
    : Game(kGameType, params),
      obs_show_ids_(ParameterValue<bool>("obs_show_ids")),
      magic_wall_steps_(ParameterValue<int>("magic_wall_steps")),
      blob_chance_(ParameterValue<int>("blob_chance")),
      rng_seed_(ParameterValue<int>("rng_seed")),
      grid_(ParseGrid(ParameterValue<std::string>("grid"),
                      ParameterValue<double>("blob_max_percentage"))) {}
Member Function Documentation
DeserializeState()
std::unique_ptr< State > open_spiel::stones_and_gems::StonesNGemsGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 1191 of file stones_and_gems.cc.
{
  // empty string
  if (str.empty()) {
    return NewInitialState();
  }
  std::vector<std::string> lines = absl::StrSplit(str, '\n');
  if (lines.size() < 2) {
    SpielFatalError("Empty map string passed.");
  }
  // Read grid properties
  std::vector<std::string> property_line = absl::StrSplit(lines[0], ',');
  Grid grid;
  int steps_remaining, magic_wall_steps, blob_max_size, blob_size, blob_chance,
      gems_required, gems_collected, current_reward, sum_reward, id_counter,
      cur_player, magic_active, blob_enclosed, obs_show_ids, blob_swap;
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[0], &grid.num_cols));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[1], &grid.num_rows));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[2], &steps_remaining));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[3], &magic_wall_steps));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[4], &magic_active));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[5], &blob_max_size));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[6], &blob_size));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[7], &blob_chance));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[8], &blob_swap));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[9], &blob_enclosed));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[10], &gems_required));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[11], &gems_collected));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[12], &current_reward));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[13], &sum_reward));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[14], &obs_show_ids));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[15], &id_counter));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[16], &cur_player));
  // Set grid elements
  for (std::size_t i = 1; i < lines.size(); ++i) {
    std::vector<std::string> grid_line = absl::StrSplit(lines[i], ',');
    // Check for proper number of columns
    if (grid_line.size() != grid.num_cols * 2) {
      SpielFatalError(absl::StrCat("Grid line ", i - 1,
                                   "doesn't have correct number of elements."));
    }
    // Check each element in row
    // for (const auto &type : grid_line) {
    for (std::size_t i = 0; i < grid_line.size() / 2; ++i) {
      // Element
      auto it = kCellTypeToElement.find(std::stoi(grid_line[2 * i]));
      if (it != kCellTypeToElement.end()) {
        grid.elements.push_back(it->second);
      } else {
        SpielFatalError(absl::StrCat("Unknown element id: ", grid_line[2 * i]));
      }
      // ID
      grid.ids.push_back(std::stoi(grid_line[2 * i + 1]));
    }
  }
  // Ensure we read proper number of rows
  if (lines.size() - 1 != grid.num_rows) {
    SpielFatalError(absl::StrCat("Incorrect number of rows, got ",
                                 lines.size() - 1, " but need ",
                                 grid.num_rows));
  }
  // Ensure the agent exists in the map
  auto it = std::find(grid_.elements.begin(), grid_.elements.end(), kElAgent);
  if (it == grid_.elements.end()) {
    SpielFatalError("Grid string doesn't contain the agent.");
  }
  return std::unique_ptr<State>(new StonesNGemsState(
      shared_from_this(), steps_remaining, magic_wall_steps, magic_active,
      blob_max_size, blob_size, blob_chance, kCellTypeToElement.at(blob_swap),
      blob_enclosed, gems_required, gems_collected, current_reward, sum_reward,
      grid, obs_show_ids, id_counter, cur_player));
}
References open_spiel::stones_and_gems::Grid::elements, i, open_spiel::stones_and_gems::Grid::ids, NewInitialState(), open_spiel::stones_and_gems::Grid::num_cols, open_spiel::stones_and_gems::Grid::num_rows, absl::SimpleAtoi(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), absl::StrCat(), and absl::StrSplit().
GetRNGState()
std::string open_spiel::stones_and_gems::StonesNGemsGame::GetRNGState () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 1265 of file stones_and_gems.cc.
{
  std::ostringstream rng_stream;
  rng_stream << rng_;
  return rng_stream.str();
}
MaxChanceOutcomes()
int open_spiel::stones_and_gems::StonesNGemsGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 357 of file stones_and_gems.h.
{ return 1; }
MaxGameLength()
int open_spiel::stones_and_gems::StonesNGemsGame::MaxGameLength () const override virtual
Implements open_spiel::Game.
Definition at line 1280 of file stones_and_gems.cc.
{ return max_steps_; }
MaxUtility()
double open_spiel::stones_and_gems::StonesNGemsGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 1286 of file stones_and_gems.cc.
{
  // Max utility really depends on the number of gems in the map,
  // so we have a lose upper bound.
  // Diamonds give points
  // Boulders can be converted to diamonds
  // Butterflies can drop diamonds
  // Nuts drop diamonds if cracked
  double max_util = max_steps_;
  max_util +=
      kGemPoints.at(kElDiamond) *
      std::count(grid_.elements.begin(), grid_.elements.end(), kElDiamond);
  max_util += kGemPoints.at(kElDiamond) * std::count(grid_.elements.begin(),
                                                     grid_.elements.end(),
                                                     kElDiamondFalling);
  max_util +=
      std::count(grid_.elements.begin(), grid_.elements.end(), kElStone);
  max_util +=
      std::count(grid_.elements.begin(), grid_.elements.end(), kElStoneFalling);
  max_util += 9 * std::count(grid_.elements.begin(), grid_.elements.end(),
                             kElButterflyUp);
  max_util += 9 * std::count(grid_.elements.begin(), grid_.elements.end(),
                             kElButterflyLeft);
  max_util += 9 * std::count(grid_.elements.begin(), grid_.elements.end(),
                             kElButterflyDown);
  max_util += 9 * std::count(grid_.elements.begin(), grid_.elements.end(),
                             kElButterflyRight);
  max_util += std::count(grid_.elements.begin(), grid_.elements.end(), kElNut);
  max_util +=
      std::count(grid_.elements.begin(), grid_.elements.end(), kElNutFalling);
  return max_util;
}
References open_spiel::stones_and_gems::Grid::elements.
MinUtility()
double open_spiel::stones_and_gems::StonesNGemsGame::MinUtility () const override virtual
Implements open_spiel::Game.
Definition at line 1284 of file stones_and_gems.cc.
{ return 0; }
NewInitialState()
std::unique_ptr< State > open_spiel::stones_and_gems::StonesNGemsGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 349 of file stones_and_gems.h.
{
    return std::unique_ptr<State>(new StonesNGemsState(
        shared_from_this(), max_steps_, magic_wall_steps_, false,
        blob_max_size_, 0, blob_chance_, kNullElement, true, gems_required_, 0,
        0, 0, grid_, obs_show_ids_, (int)grid_.ids.size(), 0));
  }
References open_spiel::stones_and_gems::Grid::ids, and open_spiel::stones_and_gems::kNullElement.
Referenced by DeserializeState().
NumDistinctActions()
int open_spiel::stones_and_gems::StonesNGemsGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 1277 of file stones_and_gems.cc.
{ return kNumActions; }
References open_spiel::stones_and_gems::kNumActions.
NumPlayers()
int open_spiel::stones_and_gems::StonesNGemsGame::NumPlayers () const override virtual
Implements open_spiel::Game.
Definition at line 1282 of file stones_and_gems.cc.
{ return 1; }
ObservationTensorShape()
std::vector< int > open_spiel::stones_and_gems::StonesNGemsGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 1318 of file stones_and_gems.cc.
{
  return {kNumVisibleCellType, grid_.num_rows, grid_.num_cols};
}
References open_spiel::stones_and_gems::kNumVisibleCellType, open_spiel::stones_and_gems::Grid::num_cols, and open_spiel::stones_and_gems::Grid::num_rows.
ParseGrid()
Grid open_spiel::stones_and_gems::StonesNGemsGame::ParseGrid (const std::string & grid_string, double blob_max_percentage) protected
Definition at line 1322 of file stones_and_gems.cc.
{
  Grid grid;
  std::vector<std::string> lines = absl::StrSplit(grid_string, '\n');
  if (lines.size() < 2) {
    SpielFatalError("Empty map string passed.");
  }
  // Parse first line which contains level properties
  std::vector<std::string> property_line = absl::StrSplit(lines[0], '|');
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[0], &grid.num_cols));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[1], &grid.num_rows));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[2], &max_steps_));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(property_line[3], &gems_required_));
  // Parse grid contents
  for (std::size_t i = 1; i < lines.size(); ++i) {
    // Check for proper number of columns
    std::vector<std::string> grid_line = absl::StrSplit(lines[i], '|');
    if (grid_line.size() != grid.num_cols) {
      SpielFatalError(absl::StrCat(
          "Grid line ", i - 1, " doesn't have correct number of elements.",
          " Received ", grid_line.size(), ", expected ", grid.num_cols));
    }
    // Check each element in row
    for (const auto &type : grid_line) {
      auto it = kCellTypeToElement.find(std::stoi(type));
      if (it != kCellTypeToElement.end()) {
        grid.elements.push_back(it->second);
      } else {
        SpielFatalError(absl::StrCat("Unknown element id: ", type));
      }
    }
  }
  // Ensure we read proper number of rows
  if (lines.size() - 1 != grid.num_rows) {
    SpielFatalError(absl::StrCat("Incorrect number of rows, received ",
                                 lines.size() - 1, ", expected ",
                                 grid.num_rows));
  }
  // Ensure the agent exists in the map
  auto it = std::find(grid_.elements.begin(), grid_.elements.end(), kElAgent);
  if (it == grid_.elements.end()) {
    SpielFatalError("Grid string doesn't contain the agent.");
  }
  blob_max_size_ = (int)(grid_.num_cols * grid_.num_rows * blob_max_percentage);
  // Initialize the grid element IDs
  grid_.ids.clear();
  for (std::size_t i = 0; i < grid.elements.size(); ++i) {
    grid_.ids.push_back(i + 1);
  }
  return grid;
}
References open_spiel::stones_and_gems::Grid::elements, i, open_spiel::stones_and_gems::Grid::ids, open_spiel::stones_and_gems::Grid::num_cols, open_spiel::stones_and_gems::Grid::num_rows, absl::SimpleAtoi(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), absl::StrCat(), and absl::StrSplit().
rng()
std::mt19937 * open_spiel::stones_and_gems::StonesNGemsGame::rng () const inline
Definition at line 366 of file stones_and_gems.h.
{ return &rng_; }
Referenced by models.OptimizerModel::initialize_optimizer_model(), and open_spiel.python.jax.policy_gradient.PolicyGradient::step().
SetRNGState()
void open_spiel::stones_and_gems::StonesNGemsGame::SetRNGState (const std::string & rng_state) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 1271 of file stones_and_gems.cc.
{
  if (rng_state.empty()) return;
  std::istringstream rng_stream(rng_state);
  rng_stream >> rng_;
}
The documentation for this class was generated from the following files:
open_spiel/games/stones_and_gems/stones_and_gems.h
open_spiel/games/stones_and_gems/stones_and_gems.cc