open spiel: open_spiel::dark_chess::DarkChessGame Class Reference
open_spiel::dark_chess::DarkChessGame Class Reference
#include <dark_chess.h>
Public Member Functions
DarkChessGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Public Attributes
std::shared_ptr< DarkChessObserver > default_observer_
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 146 of file dark_chess.h.
Constructor & Destructor Documentation
DarkChessGame()
open_spiel::dark_chess::DarkChessGame::DarkChessGame (const GameParameters & params) explicit
Definition at line 580 of file dark_chess.cc.
    : Game(kGameType, params),
      board_size_(ParameterValue<int>("board_size")),
      fen_(ParameterValue<std::string>("fen", chess::DefaultFen(board_size_))) {
  default_observer_ = std::make_shared<DarkChessObserver>(kDefaultObsType);
}
References default_observer_, and open_spiel::kDefaultObsType.
Member Function Documentation
MakeObserver()
std::shared_ptr< Observer > open_spiel::dark_chess::DarkChessGame::MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters & params) const virtual
Reimplemented from open_spiel::Game.
Definition at line 587 of file dark_chess.cc.
{
  if (!params.empty()) SpielFatalError("Observation params not supported");
  IIGObservationType obs_type = iig_obs_type.value_or(kDefaultObsType);
  if (ObserverHasString(obs_type) || ObserverHasTensor(obs_type)) {
    return std::make_shared<DarkChessObserver>(obs_type);
  }
  return nullptr;
}
References open_spiel::kDefaultObsType, open_spiel::SpielFatalError(), and absl::optional< T >::value_or().
MaxGameLength()
int open_spiel::dark_chess::DarkChessGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 172 of file dark_chess.h.
{ return chess::MaxGameLength(); }
References open_spiel::chess::MaxGameLength().
MaxUtility()
double open_spiel::dark_chess::DarkChessGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 159 of file dark_chess.h.
{ return WinUtility(); }
References open_spiel::dark_chess::WinUtility().
MinUtility()
double open_spiel::dark_chess::DarkChessGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 157 of file dark_chess.h.
{ return LossUtility(); }
References open_spiel::dark_chess::LossUtility().
NewInitialState()
std::unique_ptr< State > open_spiel::dark_chess::DarkChessGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 152 of file dark_chess.h.
{
    return absl::make_unique<DarkChessState>(shared_from_this(), board_size_,
                                             fen_);
  }
NumDistinctActions()
int open_spiel::dark_chess::DarkChessGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 149 of file dark_chess.h.
{
    return chess::NumDistinctActions();
  }
References open_spiel::chess::NumDistinctActions().
NumPlayers()
int open_spiel::dark_chess::DarkChessGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 156 of file dark_chess.h.
{ return chess::NumPlayers(); }
References open_spiel::chess::NumPlayers().
ObservationTensorShape()
std::vector< int > open_spiel::dark_chess::DarkChessGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 160 of file dark_chess.h.
{
    std::vector<int> shape{
        (13 +  // public boards:  piece types * colours + empty
         14)   // private boards: piece types * colours + empty + unknown
            * board_size_ * board_size_ +
        3 +    // public: repetitions count, one-hot encoding
        2 +    // public: side to play
        1 +    // public: irreversible move counter -- a fraction of $n over 100
        2 * 2  // private: left/right castling rights, one-hot encoded.
    };
    return shape;
  }
UtilitySum()
absl::optional< double > open_spiel::dark_chess::DarkChessGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 158 of file dark_chess.h.
{ return DrawUtility(); }
References open_spiel::dark_chess::DrawUtility().
Member Data Documentation
default_observer_
std::shared_ptr<DarkChessObserver> open_spiel::dark_chess::DarkChessGame::default_observer_
Definition at line 177 of file dark_chess.h.
Referenced by DarkChessGame().
The documentation for this class was generated from the following files:
open_spiel/games/dark_chess/dark_chess.h
open_spiel/games/dark_chess/dark_chess.cc