open spiel: absl::time_internal::cctz::TimeZoneInfo Class Reference
absl::time_internal::cctz::TimeZoneInfo Class Reference
#include <time_zone_info.h>
Public Member Functions
TimeZoneInfo ()=default
TimeZoneInfo (const TimeZoneInfo &)=delete
TimeZoneInfo & operator= (const TimeZoneInfo &)=delete
bool Load (const std::string &name)
time_zone::absolute_lookup BreakTime (const time_point< seconds > &tp) const override
time_zone::civil_lookup MakeTime (const civil_second &cs) const override
bool NextTransition (const time_point< seconds > &tp, time_zone::civil_transition *trans) const override
bool PrevTransition (const time_point< seconds > &tp, time_zone::civil_transition *trans) const override
std::string Version () const override
std::string Description () const override
Public Member Functions inherited from absl::time_internal::cctz::TimeZoneIf
virtual ~TimeZoneIf ()
Additional Inherited Members
Static Public Member Functions inherited from absl::time_internal::cctz::TimeZoneIf
static std::unique_ptr< TimeZoneIf > Load (const std::string &name)
Protected Member Functions inherited from absl::time_internal::cctz::TimeZoneIf
TimeZoneIf ()
Detailed Description
Definition at line 65 of file time_zone_info.h.
Constructor & Destructor Documentation
TimeZoneInfo() [1/2]
absl::time_internal::cctz::TimeZoneInfo::TimeZoneInfo () default
TimeZoneInfo() [2/2]
absl::time_internal::cctz::TimeZoneInfo::TimeZoneInfo (const TimeZoneInfo &) delete
Member Function Documentation
BreakTime()
time_zone::absolute_lookup absl::time_internal::cctz::TimeZoneInfo::BreakTime (const time_point< seconds > & tp) const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 860 of file time_zone_info.cc.
{
  std::int_fast64_t unix_time = ToUnixSeconds(tp);
  const std::size_t timecnt = transitions_.size();
  assert(timecnt != 0);  // We always add a transition.
  if (unix_time < transitions_[0].unix_time) {
    return LocalTime(unix_time, transition_types_[default_transition_type_]);
  }
  if (unix_time >= transitions_[timecnt - 1].unix_time) {
    // After the last transition. If we extended the transitions using
    // future_spec_, shift back to a supported year using the 400-year
    // cycle of calendaric equivalence and then compensate accordingly.
    if (extended_) {
      const std::int_fast64_t diff =
          unix_time - transitions_[timecnt - 1].unix_time;
      const year_t shift = diff / kSecsPer400Years + 1;
      const auto d = seconds(shift * kSecsPer400Years);
      time_zone::absolute_lookup al = BreakTime(tp - d);
      al.cs = YearShift(al.cs, shift * 400);
      return al;
    }
    return LocalTime(unix_time, transitions_[timecnt - 1]);
  }
  const std::size_t hint = local_time_hint_.load(std::memory_order_relaxed);
  if (0 < hint && hint < timecnt) {
    if (transitions_[hint - 1].unix_time <= unix_time) {
      if (unix_time < transitions_[hint].unix_time) {
        return LocalTime(unix_time, transitions_[hint - 1]);
      }
    }
  }
  const Transition target = {unix_time, 0, civil_second(), civil_second()};
  const Transition* begin = &transitions_[0];
  const Transition* tr = std::upper_bound(begin, begin + timecnt, target,
                                          Transition::ByUnixTime());
  local_time_hint_.store(static_cast<std::size_t>(tr - begin),
                         std::memory_order_relaxed);
  return LocalTime(unix_time, *--tr);
}
References BreakTime(), absl::time_internal::cctz::time_zone::absolute_lookup::cs, absl::d, and absl::time_internal::cctz::ToUnixSeconds().
Referenced by BreakTime().
Description()
std::string absl::time_internal::cctz::TimeZoneInfo::Description () const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 976 of file time_zone_info.cc.
{
  std::ostringstream oss;
  oss << "#trans=" << transitions_.size();
  oss << " #types=" << transition_types_.size();
  oss << " spec='" << future_spec_ << "'";
  return oss.str();
}
Load()
bool absl::time_internal::cctz::TimeZoneInfo::Load (const std::string & name)
Definition at line 798 of file time_zone_info.cc.
{
  // We can ensure that the loading of UTC or any other fixed-offset
  // zone never fails because the simple, fixed-offset state can be
  // internally generated. Note that this depends on our choice to not
  // accept leap-second encoded ("right") zoneinfo.
  auto offset = seconds::zero();
  if (FixedOffsetFromName(name, &offset)) {
    return ResetToBuiltinUTC(offset);
  }
  // Find and use a ZoneInfoSource to load the named zone.
  auto zip = cctz_extension::zone_info_source_factory(
      name, [](const std::string& n) -> std::unique_ptr<ZoneInfoSource> {
        if (auto z = FileZoneInfoSource::Open(n)) return z;
        if (auto z = AndroidZoneInfoSource::Open(n)) return z;
        if (auto z = FuchsiaZoneInfoSource::Open(n)) return z;
        return nullptr;
      });
  return zip != nullptr && Load(zip.get());
}
References absl::time_internal::cctz::FixedOffsetFromName(), Load(), absl::n, name, and absl::time_internal::cctz_extension::zone_info_source_factory.
Referenced by Load().
MakeTime()
time_zone::civil_lookup absl::time_internal::cctz::TimeZoneInfo::MakeTime (const civil_second & cs) const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 903 of file time_zone_info.cc.
{
  const std::size_t timecnt = transitions_.size();
  assert(timecnt != 0);  // We always add a transition.
  // Find the first transition after our target civil time.
  const Transition* tr = nullptr;
  const Transition* begin = &transitions_[0];
  const Transition* end = begin + timecnt;
  if (cs < begin->civil_sec) {
    tr = begin;
  } else if (cs >= transitions_[timecnt - 1].civil_sec) {
    tr = end;
  } else {
    const std::size_t hint = time_local_hint_.load(std::memory_order_relaxed);
    if (0 < hint && hint < timecnt) {
      if (transitions_[hint - 1].civil_sec <= cs) {
        if (cs < transitions_[hint].civil_sec) {
          tr = begin + hint;
        }
      }
    }
    if (tr == nullptr) {
      const Transition target = {0, 0, cs, civil_second()};
      tr = std::upper_bound(begin, end, target, Transition::ByCivilTime());
      time_local_hint_.store(static_cast<std::size_t>(tr - begin),
                             std::memory_order_relaxed);
    }
  }
  if (tr == begin) {
    if (tr->prev_civil_sec >= cs) {
      // Before first transition, so use the default offset.
      const TransitionType& tt(transition_types_[default_transition_type_]);
      if (cs < tt.civil_min) return MakeUnique(time_point<seconds>::min());
      return MakeUnique(cs - (civil_second() + tt.utc_offset));
    }
    // tr->prev_civil_sec < cs < tr->civil_sec
    return MakeSkipped(*tr, cs);
  }
  if (tr == end) {
    if (cs > (--tr)->prev_civil_sec) {
      // After the last transition. If we extended the transitions using
      // future_spec_, shift back to a supported year using the 400-year
      // cycle of calendaric equivalence and then compensate accordingly.
      if (extended_ && cs.year() > last_year_) {
        const year_t shift = (cs.year() - last_year_ - 1) / 400 + 1;
        return TimeLocal(YearShift(cs, shift * -400), shift);
      }
      const TransitionType& tt(transition_types_[tr->type_index]);
      if (cs > tt.civil_max) return MakeUnique(time_point<seconds>::max());
      return MakeUnique(tr->unix_time + (cs - tr->civil_sec));
    }
    // tr->civil_sec <= cs <= tr->prev_civil_sec
    return MakeRepeated(*tr, cs);
  }
  if (tr->prev_civil_sec < cs) {
    // tr->prev_civil_sec < cs < tr->civil_sec
    return MakeSkipped(*tr, cs);
  }
  if (cs <= (--tr)->prev_civil_sec) {
    // tr->civil_sec <= cs <= tr->prev_civil_sec
    return MakeRepeated(*tr, cs);
  }
  // In between transitions.
  return MakeUnique(tr->unix_time + (cs - tr->civil_sec));
}
References begin, absl::time_internal::cctz::TransitionType::civil_max, absl::time_internal::cctz::TransitionType::civil_min, absl::time_internal::cctz::Transition::civil_sec, end, absl::time_internal::cctz::Transition::prev_civil_sec, absl::time_internal::cctz::Transition::type_index, absl::time_internal::cctz::Transition::unix_time, absl::time_internal::cctz::TransitionType::utc_offset, and absl::time_internal::cctz::detail::civil_time< T >::year().
NextTransition()
bool absl::time_internal::cctz::TimeZoneInfo::NextTransition (const time_point< seconds > & tp, time_zone::civil_transition * trans) const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 984 of file time_zone_info.cc.
{
  if (transitions_.empty()) return false;
  const Transition* begin = &transitions_[0];
  const Transition* end = begin + transitions_.size();
  if (begin->unix_time <= -(1LL << 59)) {
    // Do not report the BIG_BANG found in some zoneinfo data as it is
    // really a sentinel, not a transition.  See pre-2018f tz/zic.c.
    ++begin;
  }
  std::int_fast64_t unix_time = ToUnixSeconds(tp);
  const Transition target = {unix_time, 0, civil_second(), civil_second()};
  const Transition* tr =
      std::upper_bound(begin, end, target, Transition::ByUnixTime());
  for (; tr != end; ++tr) {  // skip no-op transitions
    std::uint_fast8_t prev_type_index =
        (tr == begin) ? default_transition_type_ : tr[-1].type_index;
    if (!EquivTransitions(prev_type_index, tr[0].type_index)) break;
  }
  // When tr == end we return false, ignoring future_spec_.
  if (tr == end) return false;
  trans->from = tr->prev_civil_sec + 1;
  trans->to = tr->civil_sec;
  return true;
}
References begin, absl::time_internal::cctz::Transition::civil_sec, end, absl::time_internal::cctz::time_zone::civil_transition::from, absl::time_internal::cctz::Transition::prev_civil_sec, absl::time_internal::cctz::time_zone::civil_transition::to, absl::time_internal::cctz::ToUnixSeconds(), and absl::time_internal::cctz::Transition::type_index.
operator=()
TimeZoneInfo & absl::time_internal::cctz::TimeZoneInfo::operator= (const TimeZoneInfo &) delete
PrevTransition()
bool absl::time_internal::cctz::TimeZoneInfo::PrevTransition (const time_point< seconds > & tp, time_zone::civil_transition * trans) const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 1010 of file time_zone_info.cc.
{
  if (transitions_.empty()) return false;
  const Transition* begin = &transitions_[0];
  const Transition* end = begin + transitions_.size();
  if (begin->unix_time <= -(1LL << 59)) {
    // Do not report the BIG_BANG found in some zoneinfo data as it is
    // really a sentinel, not a transition.  See pre-2018f tz/zic.c.
    ++begin;
  }
  std::int_fast64_t unix_time = ToUnixSeconds(tp);
  if (FromUnixSeconds(unix_time) != tp) {
    if (unix_time == std::numeric_limits<std::int_fast64_t>::max()) {
      if (end == begin) return false;  // Ignore future_spec_.
      trans->from = (--end)->prev_civil_sec + 1;
      trans->to = end->civil_sec;
      return true;
    }
    unix_time += 1;  // ceils
  }
  const Transition target = {unix_time, 0, civil_second(), civil_second()};
  const Transition* tr =
      std::lower_bound(begin, end, target, Transition::ByUnixTime());
  for (; tr != begin; --tr) {  // skip no-op transitions
    std::uint_fast8_t prev_type_index =
        (tr - 1 == begin) ? default_transition_type_ : tr[-2].type_index;
    if (!EquivTransitions(prev_type_index, tr[-1].type_index)) break;
  }
  // When tr == end we return the "last" transition, ignoring future_spec_.
  if (tr == begin) return false;
  trans->from = (--tr)->prev_civil_sec + 1;
  trans->to = tr->civil_sec;
  return true;
}
References begin, absl::time_internal::cctz::Transition::civil_sec, end, absl::time_internal::cctz::time_zone::civil_transition::from, absl::time_internal::cctz::FromUnixSeconds(), absl::time_internal::cctz::time_zone::civil_transition::to, absl::time_internal::cctz::ToUnixSeconds(), and absl::time_internal::cctz::Transition::type_index.
Version()
std::string absl::time_internal::cctz::TimeZoneInfo::Version () const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 974 of file time_zone_info.cc.
{ return version_; }
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/time/internal/cctz/src/time_zone_info.h
open_spiel/abseil-cpp/absl/time/internal/cctz/src/time_zone_info.cc