open spiel: absl::container_internal::HashtablezInfoHandle Class Reference
absl::container_internal::HashtablezInfoHandle Class Reference
#include <hashtablez_sampler.h>
Public Member Functions
HashtablezInfoHandle ()=default
HashtablezInfoHandle (std::nullptr_t)
void Unregister ()
void RecordStorageChanged (size_t, size_t)
void RecordRehash (size_t)
void RecordReservation (size_t)
void RecordClearedReservation ()
void RecordInsert (size_t, size_t)
void RecordErase ()
Friends
void swap (HashtablezInfoHandle &, HashtablezInfoHandle &)
Detailed Description
Definition at line 195 of file hashtablez_sampler.h.
Constructor & Destructor Documentation
HashtablezInfoHandle() [1/2]
absl::container_internal::HashtablezInfoHandle::HashtablezInfoHandle () explicit default
HashtablezInfoHandle() [2/2]
absl::container_internal::HashtablezInfoHandle::HashtablezInfoHandle (std::nullptr_t) inline explicit
Definition at line 198 of file hashtablez_sampler.h.
{}
Member Function Documentation
RecordClearedReservation()
void absl::container_internal::HashtablezInfoHandle::RecordClearedReservation () inline
Definition at line 204 of file hashtablez_sampler.h.
{}
RecordErase()
void absl::container_internal::HashtablezInfoHandle::RecordErase () inline
Definition at line 206 of file hashtablez_sampler.h.
{}
RecordInsert()
void absl::container_internal::HashtablezInfoHandle::RecordInsert (size_t , size_t) inline
Definition at line 205 of file hashtablez_sampler.h.
{}
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set().
RecordRehash()
void absl::container_internal::HashtablezInfoHandle::RecordRehash (size_t) inline
Definition at line 202 of file hashtablez_sampler.h.
{}
Referenced by absl::container_internal::DropDeletesWithoutResize().
RecordReservation()
void absl::container_internal::HashtablezInfoHandle::RecordReservation (size_t) inline
Definition at line 203 of file hashtablez_sampler.h.
{}
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::rehash(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::reserve().
RecordStorageChanged()
void absl::container_internal::HashtablezInfoHandle::RecordStorageChanged (size_t , size_t) inline
Definition at line 201 of file hashtablez_sampler.h.
{}
Unregister()
void absl::container_internal::HashtablezInfoHandle::Unregister () inline
Definition at line 200 of file hashtablez_sampler.h.
{}
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::~raw_hash_set().
Friends And Related Symbol Documentation
swap
void swap (HashtablezInfoHandle & , HashtablezInfoHandle &) friend
Definition at line 208 of file hashtablez_sampler.h.
                                                   {}
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/hashtablez_sampler.h