open spiel: absl::container_internal::Layout< Ts > Class Template Reference
absl::container_internal::Layout< Ts > Class Template Reference
#include <layout.h>
Public Types
template<size_t NumSizes>
using PartialType = internal_layout::LayoutType<NumSizes, Ts...>
Public Member Functions
constexpr Layout (internal_layout::TypeToSize< Ts >... sizes)
Static Public Member Functions
template<class... Sizes>
static constexpr PartialType< sizeof...(Sizes)> Partial (Sizes &&... sizes)
Detailed Description
template<class... Ts>
class absl::container_internal::Layout< Ts >
Definition at line 684 of file layout.h.
Member Typedef Documentation
PartialType
template<class... Ts> template<size_t NumSizes> using absl::container_internal::Layout< Ts >::PartialType = internal_layout::LayoutType<NumSizes, Ts...>
Definition at line 693 of file layout.h.
Constructor & Destructor Documentation
Layout()
template<class... Ts> absl::container_internal::Layout< Ts >::Layout (internal_layout::TypeToSize< Ts >... sizes) inline explicit constexpr
Definition at line 735 of file layout.h.
      : internal_layout::LayoutType<sizeof...(Ts), Ts...>(sizes...) {}
Member Function Documentation
Partial()
template<class... Ts> template<class... Sizes> static constexpr PartialType< sizeof...(Sizes)> absl::container_internal::Layout< Ts >::Partial (Sizes &&... sizes) inline static constexpr
Definition at line 722 of file layout.h.
{
    static_assert(sizeof...(Sizes) <= sizeof...(Ts), "");
    return PartialType<sizeof...(Sizes)>(absl::forward<Sizes>(sizes)...);
  }
References absl::forward().
Referenced by absl::cord_internal::CordRepRing::entry_child(), absl::cord_internal::CordRepRing::entry_data_offset(), and absl::cord_internal::CordRepRing::entry_end_pos().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/layout.h