open spiel: open_spiel.python.algorithms.psro_v2.strategy_selectors_test.StrategySelectorsTest Class Reference
open_spiel.python.algorithms.psro_v2.strategy_selectors_test.StrategySelectorsTest Class Reference
Public Member Functions
test_vital (self)
Detailed Description
Definition at line 142 of file strategy_selectors_test.py.
Member Function Documentation
test_vital()
open_spiel.python.algorithms.psro_v2.strategy_selectors_test.StrategySelectorsTest.test_vital (self)
Definition at line 144 of file strategy_selectors_test.py.
  def test_vital(self):
    n_tests = 1000
    number_strategies = 50
    number_players = 3
    for i in range(n_tests):
      probabilities = np.random.uniform(size=(number_players,
                                              number_strategies))
      probabilities /= np.sum(probabilities, axis=1).reshape(-1, 1)
      probabilities = list(probabilities)
      policies = [list(range(number_strategies)) for _ in range(number_players)]
      solver = FakeSolver(probabilities, policies)
      # To see how rectified reacts to 0 probabilities.
      probabilities[0][0] = 0
      probabilities[-1][-1] = 0
      a, b = strategy_selectors.rectified(solver, 1)
      c, d = rectified_alias(solver, 1)
      self.assertEqual(a, c, "Rectified failed.")
      self.assertEqual(b, d, "Rectified failed.")
      a, b = strategy_selectors.top_k_probabilities(solver, 3)
      c, d = top_k_probabilities_alias(solver, 3)
      self.assertEqual(a, c, "Top k failed.")
      self.assertEqual(b, d, "Top k failed.")
      n_nonzero_policies = 2
      probabilities = [np.zeros(number_strategies) for _ in range(
          number_players)]
      for player in range(number_players):
        for _ in range(n_nonzero_policies):
          i = np.random.randint(0, high=number_strategies)
          while probabilities[player][i] > 1e-12:
            i = np.random.randint(0, high=number_strategies)
          probabilities[player][i] = 1.0 / n_nonzero_policies
        probabilities[player] /= np.sum(probabilities[player])
      solver = FakeSolver(probabilities, policies)
      a, b = strategy_selectors.probabilistic(solver, n_nonzero_policies)
      c, d = probabilistic_alias(solver, n_nonzero_policies)
      self.assertTrue(equal_to_transposition_lists(a, c),
                      "Probabilistic failed.")
      self.assertTrue(equal_to_transposition_lists(b, d),
                      "Probabilistic failed.")
References open_spiel.python.algorithms.psro_v2.strategy_selectors_test.equal_to_transposition_lists(), open_spiel.python.algorithms.psro_v2.strategy_selectors_test.probabilistic_alias(), open_spiel.python.algorithms.psro_v2.strategy_selectors_test.rectified_alias(), and open_spiel.python.algorithms.psro_v2.strategy_selectors_test.top_k_probabilities_alias().
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/psro_v2/strategy_selectors_test.py