open spiel: open_spiel::dark_hex::ImperfectRecallDarkHexState Class Reference
open_spiel::dark_hex::ImperfectRecallDarkHexState Class Reference
#include <dark_hex.h>
Public Member Functions
ImperfectRecallDarkHexState (std::shared_ptr< const Game > game, int num_rows_, int num_cols_, GameVersion game_version, ObservationType obs_type)
std::string InformationStateString (Player player) const override
std::unique_ptr< State > Clone () const override
Public Member Functions inherited from open_spiel::dark_hex::DarkHexState
DarkHexState (std::shared_ptr< const Game > game, int num_cols, int num_rows, GameVersion game_version, ObservationType obs_type)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::dark_hex::DarkHexState
void DoApplyAction (Action move) override
std::string ViewToString (Player player) const
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 173 of file dark_hex.h.
Constructor & Destructor Documentation
ImperfectRecallDarkHexState()
open_spiel::dark_hex::ImperfectRecallDarkHexState::ImperfectRecallDarkHexState (std::shared_ptr< const Game > game, int num_rows_, int num_cols_, GameVersion game_version, ObservationType obs_type) inline
Definition at line 175 of file dark_hex.h.
      : DarkHexState(game, num_rows_, num_cols_, game_version, obs_type) {}
Referenced by Clone().
Member Function Documentation
Clone()
std::unique_ptr< State > open_spiel::dark_hex::ImperfectRecallDarkHexState::Clone () const inline override virtual
Reimplemented from open_spiel::dark_hex::DarkHexState.
Definition at line 184 of file dark_hex.h.
{
    return std::unique_ptr<State>(new ImperfectRecallDarkHexState(*this));
  }
References ImperfectRecallDarkHexState().
InformationStateString()
std::string open_spiel::dark_hex::ImperfectRecallDarkHexState::InformationStateString (Player player) const inline override virtual
Reimplemented from open_spiel::dark_hex::DarkHexState.
Definition at line 179 of file dark_hex.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, num_players_);
    return absl::StrCat("P", player, " ", ViewToString(player));
  }
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrCat(), and open_spiel::dark_hex::DarkHexState::ViewToString().
The documentation for this class was generated from the following file:
open_spiel/games/dark_hex/dark_hex.h