open spiel: open_spiel::connect_four::ConnectFourState Class Reference
open_spiel::connect_four::ConnectFourState Class Reference
#include <connect_four.h>
Public Member Functions
ConnectFourState (std::shared_ptr< const Game >)
ConnectFourState (std::shared_ptr< const Game > game, const std::string &str)
ConnectFourState (const ConnectFourState &other)=default
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const override
std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 61 of file connect_four.h.
Constructor & Destructor Documentation
ConnectFourState() [1/3]
open_spiel::connect_four::ConnectFourState::ConnectFourState (std::shared_ptr< const Game > game)
Definition at line 163 of file connect_four.cc.
    : State(game) {
  std::fill(begin(board_), end(board_), CellState::kEmpty);
}
References begin, end, and open_spiel::connect_four::kEmpty.
Referenced by Clone().
ConnectFourState() [2/3]
open_spiel::connect_four::ConnectFourState::ConnectFourState (std::shared_ptr< const Game > game, const std::string & str) explicit
Definition at line 232 of file connect_four.cc.
    : State(game) {
  int xs = 0;
  int os = 0;
  int r = 5;
  int c = 0;
  for (const char ch : str) {
    switch (ch) {
      case '.':
        CellAt(r, c) = CellState::kEmpty;
        break;
      case 'x':
        ++xs;
        CellAt(r, c) = CellState::kCross;
        break;
      case 'o':
        ++os;
        CellAt(r, c) = CellState::kNought;
        break;
    }
    if (ch == '.' || ch == 'x' || ch == 'o') {
      ++c;
      if (c >= kCols) {
        r--;
        c = 0;
      }
    }
  }
  SPIEL_CHECK_TRUE(xs == os || xs == (os + 1));
  SPIEL_CHECK_TRUE(r == -1 && ("Problem parsing state (incorrect rows)."));
  SPIEL_CHECK_TRUE(c == 0 &&
                   ("Problem parsing state (column value should be 0)"));
  current_player_ = (xs == os) ? 0 : 1;
  if (HasLine(0)) {
    outcome_ = Outcome::kPlayer1;
  } else if (HasLine(1)) {
    outcome_ = Outcome::kPlayer2;
  } else if (IsFull()) {
    outcome_ = Outcome::kDraw;
  }
}
References open_spiel::connect_four::kCols, open_spiel::connect_four::kCross, open_spiel::connect_four::kDraw, open_spiel::connect_four::kEmpty, open_spiel::connect_four::kNought, open_spiel::connect_four::kPlayer1, open_spiel::connect_four::kPlayer2, r, and SPIEL_CHECK_TRUE.
ConnectFourState() [3/3]
open_spiel::connect_four::ConnectFourState::ConnectFourState (const ConnectFourState & other) default
Member Function Documentation
ActionsConsistentWithInformationFrom()
std::vector< Action > open_spiel::connect_four::ConnectFourState::ActionsConsistentWithInformationFrom (Action action) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 79 of file connect_four.h.
{
    return {action};
  }
References action.
ActionToString()
std::string open_spiel::connect_four::ConnectFourState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 120 of file connect_four.cc.
{
  return absl::StrCat(StateToString(PlayerToState(player)), action_id);
}
References player, StateToString(), and absl::StrCat().
Clone()
std::unique_ptr< State > open_spiel::connect_four::ConnectFourState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 225 of file connect_four.cc.
{
  return std::unique_ptr<State>(new ConnectFourState(*this));
}
References ConnectFourState().
Referenced by ResampleFromInfostate().
CurrentPlayer()
int open_spiel::connect_four::ConnectFourState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 87 of file connect_four.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  } else {
    return current_player_;
  }
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by DoApplyAction().
DoApplyAction()
void open_spiel::connect_four::ConnectFourState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 95 of file connect_four.cc.
{
  SPIEL_CHECK_EQ(CellAt(kRows - 1, move), CellState::kEmpty);
  int row = 0;
  while (CellAt(row, move) != CellState::kEmpty) ++row;
  CellAt(row, move) = PlayerToState(CurrentPlayer());
  if (HasLine(current_player_)) {
    outcome_ = static_cast<Outcome>(current_player_);
  } else if (IsFull()) {
    outcome_ = Outcome::kDraw;
  }
  current_player_ = 1 - current_player_;
}
References CurrentPlayer(), open_spiel::connect_four::kDraw, open_spiel::connect_four::kEmpty, open_spiel::connect_four::kRows, and SPIEL_CHECK_EQ.
InformationStateString()
std::string open_spiel::connect_four::ConnectFourState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 188 of file connect_four.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::connect_four::ConnectFourState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 178 of file connect_four.cc.
{
  return outcome_ != Outcome::kUnknown;
}
References open_spiel::connect_four::kUnknown.
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::connect_four::ConnectFourState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 110 of file connect_four.cc.
{
  // Can move in any non-full column.
  std::vector<Action> moves;
  if (IsTerminal()) return moves;
  for (int col = 0; col < kCols; ++col) {
    if (CellAt(kRows - 1, col) == CellState::kEmpty) moves.push_back(col);
  }
  return moves;
}
References IsTerminal(), open_spiel::connect_four::kCols, open_spiel::connect_four::kEmpty, and open_spiel::connect_four::kRows.
ObservationString()
std::string open_spiel::connect_four::ConnectFourState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 194 of file connect_four.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::connect_four::ConnectFourState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 213 of file connect_four.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<2> view(values, {kCellStates, kNumCells}, true);
  for (int cell = 0; cell < kNumCells; ++cell) {
    view[{PlayerRelative(board_[cell], player), cell}] = 1.0;
  }
}
References open_spiel::connect_four::kCellStates, open_spiel::connect_four::kNumCells, open_spiel::State::num_players_, player, open_spiel::connect_four::PlayerRelative(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
ResampleFromInfostate()
std::unique_ptr< State > open_spiel::connect_four::ConnectFourState::ResampleFromInfostate (int player_id, std::function< double()> rng) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 83 of file connect_four.h.
{
    return Clone();
  }
References Clone().
Returns()
std::vector< double > open_spiel::connect_four::ConnectFourState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 182 of file connect_four.cc.
{
  if (outcome_ == Outcome::kPlayer1) return {1.0, -1.0};
  if (outcome_ == Outcome::kPlayer2) return {-1.0, 1.0};
  return {0.0, 0.0};
}
References open_spiel::connect_four::kPlayer1, and open_spiel::connect_four::kPlayer2.
ToString()
std::string open_spiel::connect_four::ConnectFourState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 168 of file connect_four.cc.
{
  std::string str;
  for (int row = kRows - 1; row >= 0; --row) {
    for (int col = 0; col < kCols; ++col) {
      str.append(StateToString(CellAt(row, col)));
    }
    str.append("\n");
  }
  return str;
}
References open_spiel::connect_four::kCols, open_spiel::connect_four::kRows, and StateToString().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/connect_four/connect_four.h
open_spiel/games/connect_four/connect_four.cc