open spiel: absl::Span< T > Class Template Reference
absl::Span< T > Class Template Reference
#include <span.h>
Public Types
using element_type = T
using value_type = absl::remove_cv_t<T>
using pointer = T*
using const_pointer = const T*
using reference = T&
using const_reference = const T&
using iterator = pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator<iterator>
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using size_type = size_t
using difference_type = ptrdiff_t
Public Member Functions
constexpr Span () noexcept
constexpr Span (pointer array, size_type length) noexcept
template<size_t N>
constexpr Span (T(&a)[N]) noexcept
template<typename V , typename = EnableIfConvertibleFrom<V>, typename = EnableIfValueIsMutable<V>, typename = span_internal::EnableIfNotIsView<V>>
Span (V &v ABSL_ATTRIBUTE_LIFETIME_BOUND) noexcept
template<typename V , typename = EnableIfConvertibleFrom<V>, typename = EnableIfValueIsConst<V>, typename = span_internal::EnableIfNotIsView<V>>
constexpr Span (const V &v ABSL_ATTRIBUTE_LIFETIME_BOUND) noexcept
template<typename V , typename = EnableIfConvertibleFrom<V>, typename = EnableIfValueIsMutable<V>, span_internal::EnableIfIsView< V > = 0>
Span (V &v) noexcept
template<typename V , typename = EnableIfConvertibleFrom<V>, typename = EnableIfValueIsConst<V>, span_internal::EnableIfIsView< V > = 0>
constexpr Span (const V &v) noexcept
template<typename LazyT = T, typename = EnableIfValueIsConst<LazyT>>
Span (std::initializer_list< value_type > v ABSL_ATTRIBUTE_LIFETIME_BOUND) noexcept
constexpr pointer data () const noexcept
constexpr size_type size () const noexcept
constexpr size_type length () const noexcept
constexpr bool empty () const noexcept
constexpr reference operator[] (size_type i) const noexcept
constexpr reference at (size_type i) const
constexpr reference front () const noexcept
constexpr reference back () const noexcept
constexpr iterator begin () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr iterator end () const noexcept
constexpr const_iterator cend () const noexcept
constexpr reverse_iterator rbegin () const noexcept
constexpr const_reverse_iterator crbegin () const noexcept
constexpr reverse_iterator rend () const noexcept
constexpr const_reverse_iterator crend () const noexcept
void remove_prefix (size_type n) noexcept
void remove_suffix (size_type n) noexcept
constexpr Span subspan (size_type pos=0, size_type len=npos) const
constexpr Span first (size_type len) const
constexpr Span last (size_type len) const
Static Public Attributes
static const size_type npos = ~(size_type(0))
Friends
template<typename H >
H AbslHashValue (H h, Span v)
Detailed Description
template<typename T>
class absl::Span< T >
Definition at line 153 of file span.h.
Member Typedef Documentation
const_iterator
template<typename T > using absl::Span< T >::const_iterator = const_pointer
Definition at line 180 of file span.h.
const_pointer
template<typename T > using absl::Span< T >::const_pointer = const T*
Definition at line 176 of file span.h.
const_reference
template<typename T > using absl::Span< T >::const_reference = const T&
Definition at line 178 of file span.h.
const_reverse_iterator
template<typename T > using absl::Span< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 182 of file span.h.
difference_type
template<typename T > using absl::Span< T >::difference_type = ptrdiff_t
Definition at line 184 of file span.h.
element_type
template<typename T > using absl::Span< T >::element_type = T
Definition at line 173 of file span.h.
iterator
template<typename T > using absl::Span< T >::iterator = pointer
Definition at line 179 of file span.h.
pointer
template<typename T > using absl::Span< T >::pointer = T*
Definition at line 175 of file span.h.
reference
template<typename T > using absl::Span< T >::reference = T&
Definition at line 177 of file span.h.
reverse_iterator
template<typename T > using absl::Span< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 181 of file span.h.
size_type
template<typename T > using absl::Span< T >::size_type = size_t
Definition at line 183 of file span.h.
value_type
template<typename T > using absl::Span< T >::value_type = absl::remove_cv_t<T>
Definition at line 174 of file span.h.
Constructor & Destructor Documentation
Span() [1/8]
template<typename T > absl::Span< T >::Span () inline constexpr noexcept
Definition at line 188 of file span.h.
: Span(nullptr, 0) {}
Referenced by absl::Span< T >::first(), absl::Span< T >::last(), and absl::Span< T >::subspan().
Span() [2/8]
template<typename T > absl::Span< T >::Span (pointer array, size_type length) inline constexpr noexcept
Definition at line 189 of file span.h.
      : ptr_(array), len_(length) {}
Span() [3/8]
template<typename T > template<size_t N> absl::Span< T >::Span (T(&) a[N]) inline constexpr noexcept
Definition at line 194 of file span.h.
      : Span(a, N) {}
Span() [4/8]
template<typename T > template<typename V , typename = EnableIfConvertibleFrom<V>, typename = EnableIfValueIsMutable<V>, typename = span_internal::EnableIfNotIsView<V>> absl::Span< T >::Span (V &v ABSL_ATTRIBUTE_LIFETIME_BOUND) inline explicit noexcept
Definition at line 202 of file span.h.
      : Span(span_internal::GetData(v), v.size()) {}
Span() [5/8]
template<typename T > template<typename V , typename = EnableIfConvertibleFrom<V>, typename = EnableIfValueIsConst<V>, typename = span_internal::EnableIfNotIsView<V>> absl::Span< T >::Span (const V &v ABSL_ATTRIBUTE_LIFETIME_BOUND) inline constexpr noexcept
Definition at line 211 of file span.h.
      : Span(span_internal::GetData(v), v.size()) {}
Span() [6/8]
template<typename T > template<typename V , typename = EnableIfConvertibleFrom<V>, typename = EnableIfValueIsMutable<V>, span_internal::EnableIfIsView< V > = 0> absl::Span< T >::Span (V & v) inline explicit noexcept
Definition at line 223 of file span.h.
      : Span(span_internal::GetData(v), v.size()) {}
Span() [7/8]
template<typename T > template<typename V , typename = EnableIfConvertibleFrom<V>, typename = EnableIfValueIsConst<V>, span_internal::EnableIfIsView< V > = 0> absl::Span< T >::Span (const V & v) inline constexpr noexcept
Definition at line 228 of file span.h.
      : Span(span_internal::GetData(v), v.size()) {}
Span() [8/8]
template<typename T > template<typename LazyT = T, typename = EnableIfValueIsConst<LazyT>> absl::Span< T >::Span (std::initializer_list< value_type > v ABSL_ATTRIBUTE_LIFETIME_BOUND) inline noexcept
Definition at line 268 of file span.h.
      : Span(v.begin(), v.size()) {}
Member Function Documentation
at()
template<typename T > reference absl::Span< T >::at (size_type i) const inline constexpr
Definition at line 306 of file span.h.
{
    return ABSL_PREDICT_TRUE(i < size())  //
               ? *(data() + i)
               : (base_internal::ThrowStdOutOfRange(
                      "Span::at failed bounds check"),
                  *(data() + i));
  }
References ABSL_PREDICT_TRUE, absl::Span< T >::data(), absl::i, absl::Span< T >::size(), and absl::base_internal::ThrowStdOutOfRange().
back()
template<typename T > reference absl::Span< T >::back () const inline constexpr noexcept
Definition at line 326 of file span.h.
{
    return ABSL_HARDENING_ASSERT(size() > 0), *(data() + size() - 1);
  }
References ABSL_HARDENING_ASSERT, absl::Span< T >::data(), and absl::Span< T >::size().
Referenced by absl::ABSL_NAMESPACE_BEGIN::FromFlats().
begin()
template<typename T > iterator absl::Span< T >::begin () const inline constexpr noexcept
Definition at line 334 of file span.h.
{ return data(); }
References absl::Span< T >::data().
Referenced by absl::Span< T >::cbegin(), open_spiel::TensorView< Rank >::clear(), open_spiel::init_pyspiel_observer(), and absl::Span< T >::rend().
cbegin()
template<typename T > const_iterator absl::Span< T >::cbegin () const inline constexpr noexcept
Definition at line 340 of file span.h.
{ return begin(); }
References absl::Span< T >::begin().
cend()
template<typename T > const_iterator absl::Span< T >::cend () const inline constexpr noexcept
Definition at line 354 of file span.h.
{ return end(); }
References absl::Span< T >::end().
crbegin()
template<typename T > const_reverse_iterator absl::Span< T >::crbegin () const inline constexpr noexcept
Definition at line 368 of file span.h.
{ return rbegin(); }
References absl::Span< T >::rbegin().
crend()
template<typename T > const_reverse_iterator absl::Span< T >::crend () const inline constexpr noexcept
Definition at line 384 of file span.h.
{ return rend(); }
References absl::Span< T >::rend().
data()
template<typename T > pointer absl::Span< T >::data () const inline constexpr noexcept
Definition at line 278 of file span.h.
{ return ptr_; }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), absl::cord_internal::CordRepRing::Append(), absl::log_internal::AppendTruncated(), absl::log_internal::AppendTruncated(), absl::inlined_vector_internal::Storage< T, N, A >::Assign(), absl::Span< T >::at(), absl::Span< T >::back(), absl::Span< T >::begin(), absl::Span< T >::end(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), absl::log_internal::LogMessage::LogMessageData::FinalizeEncodingAndFormat(), absl::Span< T >::first(), absl::Span< T >::front(), open_spiel::init_pyspiel_observer(), absl::inlined_vector_internal::Storage< T, N, A >::Insert(), absl::Span< T >::last(), absl::log_internal::LogEntryTestPeer::LogEntryTestPeer(), absl::Span< T >::operator[](), absl::cord_internal::CordRepRing::Prepend(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample(), absl::Span< T >::subspan(), absl::LogEntry::text_message(), absl::LogEntry::text_message_with_newline(), absl::LogEntry::text_message_with_prefix(), absl::LogEntry::text_message_with_prefix_and_newline(), and absl::LogEntry::text_message_with_prefix_and_newline_c_str().
empty()
template<typename T > bool absl::Span< T >::empty () const inline constexpr noexcept
Definition at line 293 of file span.h.
{ return size() == 0; }
References absl::Span< T >::size().
Referenced by absl::cord_internal::CordRepRing::Append(), absl::cordrep_testing::CordRepBtreeFromFlats(), absl::ABSL_NAMESPACE_BEGIN::FromFlats(), open_spiel::Normalize(), and absl::cord_internal::CordRepRing::Prepend().
end()
template<typename T > iterator absl::Span< T >::end () const inline constexpr noexcept
Definition at line 347 of file span.h.
{ return data() + size(); }
References absl::Span< T >::data(), and absl::Span< T >::size().
Referenced by absl::Span< T >::cend(), open_spiel::TensorView< Rank >::clear(), open_spiel::init_pyspiel_observer(), and absl::Span< T >::rbegin().
first()
template<typename T > Span absl::Span< T >::first (size_type len) const inline constexpr
Definition at line 438 of file span.h.
{
    return (len <= size())
               ? Span(data(), len)
               : (base_internal::ThrowStdOutOfRange("len > size()"), Span());
  }
References absl::Span< T >::data(), len, absl::Span< T >::size(), absl::Span< T >::Span(), and absl::base_internal::ThrowStdOutOfRange().
front()
template<typename T > reference absl::Span< T >::front () const inline constexpr noexcept
Definition at line 318 of file span.h.
{
    return ABSL_HARDENING_ASSERT(size() > 0), *data();
  }
References ABSL_HARDENING_ASSERT, absl::Span< T >::data(), and absl::Span< T >::size().
Referenced by absl::ABSL_NAMESPACE_BEGIN::FromFlats().
last()
template<typename T > Span absl::Span< T >::last (size_type len) const inline constexpr
Definition at line 455 of file span.h.
{
    return (len <= size())
               ? Span(size() - len + data(), len)
               : (base_internal::ThrowStdOutOfRange("len > size()"), Span());
  }
References absl::Span< T >::data(), len, absl::Span< T >::size(), absl::Span< T >::Span(), and absl::base_internal::ThrowStdOutOfRange().
length()
template<typename T > size_type absl::Span< T >::length () const inline constexpr noexcept
Definition at line 288 of file span.h.
{ return size(); }
References absl::Span< T >::size().
Referenced by absl::cord_internal::CordRepRing::Append(), and absl::cord_internal::CordRepRing::Prepend().
operator[]()
template<typename T > reference absl::Span< T >::operator[] (size_type i) const inline constexpr noexcept
Definition at line 298 of file span.h.
{
    // MSVC 2015 accepts this as constexpr, but not ptr_[i]
    return ABSL_HARDENING_ASSERT(i < size()), *(data() + i);
  }
References ABSL_HARDENING_ASSERT, absl::Span< T >::data(), absl::i, and absl::Span< T >::size().
rbegin()
template<typename T > reverse_iterator absl::Span< T >::rbegin () const inline constexpr noexcept
Definition at line 360 of file span.h.
{
    return reverse_iterator(end());
  }
References absl::Span< T >::end().
Referenced by absl::Span< T >::crbegin().
remove_prefix()
template<typename T > void absl::Span< T >::remove_prefix (size_type n) inline noexcept
Definition at line 391 of file span.h.
{
    ABSL_HARDENING_ASSERT(size() >= n);
    ptr_ += n;
    len_ -= n;
  }
References ABSL_HARDENING_ASSERT, absl::n, and absl::Span< T >::size().
Referenced by absl::log_internal::AppendTruncated(), absl::log_internal::AppendTruncated(), absl::log_internal::ProtoField::DecodeFrom(), and absl::log_internal::LogEntryTestPeer::LogEntryTestPeer().
remove_suffix()
template<typename T > void absl::Span< T >::remove_suffix (size_type n) inline noexcept
Definition at line 400 of file span.h.
{
    ABSL_HARDENING_ASSERT(size() >= n);
    len_ -= n;
  }
References ABSL_HARDENING_ASSERT, absl::n, and absl::Span< T >::size().
Referenced by absl::log_internal::LogMessage::LogMessageData::FinalizeEncodingAndFormat(), and absl::log_internal::LogEntryTestPeer::LogEntryTestPeer().
rend()
template<typename T > reverse_iterator absl::Span< T >::rend () const inline constexpr noexcept
Definition at line 375 of file span.h.
{
    return reverse_iterator(begin());
  }
References absl::Span< T >::begin().
Referenced by absl::Span< T >::crend().
size()
template<typename T > size_type absl::Span< T >::size () const inline constexpr noexcept
Definition at line 283 of file span.h.
{ return len_; }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), absl::log_internal::AppendTruncated(), absl::log_internal::AppendTruncated(), absl::inlined_vector_internal::Storage< T, N, A >::Assign(), absl::Span< T >::at(), absl::Span< T >::back(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), pybind11::test::CheckSpan(), open_spiel::BinaryCompress::Compress(), open_spiel::NoCompress::Compress(), absl::cord_internal::CordRepBtree::Add< CordRepBtree::kFront >(), absl::cordrep_testing::CordRepBtreeFromFlats(), absl::log_internal::ProtoField::DecodeFrom(), open_spiel::BinaryCompress::Decompress(), open_spiel::NoCompress::Decompress(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), absl::Span< T >::empty(), absl::Span< T >::end(), absl::Span< T >::first(), absl::ABSL_NAMESPACE_BEGIN::FromFlats(), absl::Span< T >::front(), open_spiel::ContiguousAllocator::Get(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), absl::inlined_vector_internal::Storage< T, N, A >::Insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), absl::Span< T >::last(), absl::Span< T >::length(), absl::log_internal::LogEntryTestPeer::LogEntryTestPeer(), open_spiel::Normalize(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel::SamplerFromRng::operator()(), absl::Span< T >::operator[](), absl::Span< T >::remove_prefix(), absl::Span< T >::remove_suffix(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel::SpanTensor::SpanTensor(), absl::Span< T >::subspan(), open_spiel::TensorView< Rank >::TensorView(), absl::LogEntry::text_message(), absl::LogEntry::text_message_with_newline(), absl::LogEntry::text_message_with_prefix(), absl::LogEntry::text_message_with_prefix_and_newline(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
subspan()
template<typename T > Span absl::Span< T >::subspan (size_type pos = 0, size_type len = npos) const inline constexpr
Definition at line 421 of file span.h.
{
    return (pos <= size())
               ? Span(data() + pos, (std::min)(size() - pos, len))
               : (base_internal::ThrowStdOutOfRange("pos > size()"), Span());
  }
References absl::Span< T >::data(), len, absl::Span< T >::size(), absl::Span< T >::Span(), and absl::base_internal::ThrowStdOutOfRange().
Referenced by absl::CordBuffer::available_up_to(), absl::log_internal::ProtoField::DecodeFrom(), absl::log_internal::EncodeMessageStart(), and open_spiel::ContiguousAllocator::Get().
Friends And Related Symbol Documentation
AbslHashValue
template<typename T > template<typename H > H AbslHashValue (H h, Span< T > v) friend
Definition at line 463 of file span.h.
{
    return H::combine(H::combine_contiguous(std::move(h), v.data(), v.size()),
                      v.size());
  }
Member Data Documentation
npos
template<typename T > const Span< T >::size_type absl::Span< T >::npos = ~(size_type(0)) static
Definition at line 186 of file span.h.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/types/internal/span.h
open_spiel/abseil-cpp/absl/types/span.h