open spiel: open_spiel::laser_tag::LaserTagState Class Reference
open_spiel::laser_tag::LaserTagState Class Reference
#include <laser_tag.h>
Public Member Functions
LaserTagState (std::shared_ptr< const Game > game, const Grid &grid)
LaserTagState (const LaserTagState &)=default
std::string ActionToString (int player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string ObservationString (int player) const override
void ObservationTensor (int player, absl::Span< float > values) const override
int CurrentPlayer () const override
std::unique_ptr< State > Clone () const override
ActionsAndProbs ChanceOutcomes () const override
void Reset (int horizon, bool zero_sum)
std::vector< Action > LegalActions (int player) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &moves) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 96 of file laser_tag.h.
Constructor & Destructor Documentation
LaserTagState() [1/2]
open_spiel::laser_tag::LaserTagState::LaserTagState (std::shared_ptr< const Game > game, const Grid & grid) explicit
Definition at line 133 of file laser_tag.cc.
    : SimMoveState(game), grid_(grid) {
  GameParameters params = game_->GetParameters();
  auto it = params.find("fully_obs");
  if (it != params.end()) fully_obs_ = it->second.bool_value();
  it = params.find("obs_front");
  if (it != params.end()) obs_front_ = it->second.int_value();
  it = params.find("obs_back");
  if (it != params.end()) obs_back_ = it->second.int_value();
  it = params.find("obs_side");
  if (it != params.end()) obs_side_ = it->second.int_value();
}
References open_spiel::State::game_.
Referenced by Clone().
LaserTagState() [2/2]
open_spiel::laser_tag::LaserTagState::LaserTagState (const LaserTagState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::laser_tag::LaserTagState::ActionToString (int player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 146 of file laser_tag.cc.
{
  if (player == kSimultaneousPlayerId)
    return FlatJointActionToString(action_id);
  SPIEL_CHECK_GE(action_id, 0);
  std::string result = "";
  if (player == kChancePlayerId) {
    SPIEL_CHECK_LT(action_id, game_->MaxChanceOutcomes());
    // Chance moves.
    if (action_id == kChanceInit0Action) {
      result = "(A's action first)";
    } else if (action_id == kChanceInit1Action) {
      result = "(B's action first)";
    } else {
      return absl::StrCat("(spawned at location #",
                          action_id - kNumInitiativeChanceOutcomes, ")");
    }
  } else {
    SPIEL_CHECK_LT(action_id, game_->NumDistinctActions());
    // Regular move actions.
    if (action_id == kLeftTurn) {
      result = "left turn";
    } else if (action_id == kRightTurn) {
      result = "right turn";
    } else if (action_id == kForwardMove) {
      result = "move forward";
    } else if (action_id == kBackwardMove) {
      result = "move backward";
    } else if (action_id == kStepLeft) {
      result = "step left";
    } else if (action_id == kStepRight) {
      result = "step right";
    } else if (action_id == kStand) {
      result = "stand";
    } else if (action_id == kForwardLeft) {
      result = "step forward and left turn";
    } else if (action_id == kForwardRight) {
      result = "step forward and right turn";
    } else if (action_id == kFire) {
      result = "fire";
    }
  }
  return result;
}
References open_spiel::SimMoveState::FlatJointActionToString(), open_spiel::State::game_, open_spiel::laser_tag::kChanceInit0Action, open_spiel::laser_tag::kChanceInit1Action, open_spiel::kChancePlayerId, open_spiel::laser_tag::kNumInitiativeChanceOutcomes, open_spiel::kSimultaneousPlayerId, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::laser_tag::LaserTagState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 429 of file laser_tag.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  if (!needs_respawn_.empty()) {
    int num_legal_actions = 0;
    for (int i = 0; i < grid_.spawn_points.size(); ++i) {
      if (field(grid_.spawn_points[i].first,
                grid_.spawn_points[i].second) == '.') {
        num_legal_actions += 1;
      }
    }
    std::vector<std::pair<Action, double>> outcomes;
    const double unif_prob = 1.0 / num_legal_actions;
    for (int i = 0; i < grid_.spawn_points.size(); ++i) {
      if (field(grid_.spawn_points[i].first,
                grid_.spawn_points[i].second) == '.') {
        outcomes.push_back({kNumInitiativeChanceOutcomes + i, unif_prob});
      }
    }
    return outcomes;
  } else {
    return {{ToAction(ChanceOutcome::kChanceInit0), 0.5},
            {ToAction(ChanceOutcome::kChanceInit1), 0.5}};
  }
}
References i, open_spiel::State::IsChanceNode(), open_spiel::laser_tag::kChanceInit0, open_spiel::laser_tag::kChanceInit1, open_spiel::laser_tag::kNumInitiativeChanceOutcomes, open_spiel::laser_tag::Grid::spawn_points, and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::laser_tag::LaserTagState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 648 of file laser_tag.cc.
{
  return std::unique_ptr<State>(new LaserTagState(*this));
}
References LaserTagState().
CurrentPlayer()
int open_spiel::laser_tag::LaserTagState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 108 of file laser_tag.h.
{
    return IsTerminal() ? kTerminalPlayerId : cur_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::laser_tag::LaserTagState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 351 of file laser_tag.cc.
{
  if (IsSimultaneousNode()) {
    ApplyFlatJointAction(action_id);
    return;
  }
  SPIEL_CHECK_TRUE(IsChanceNode());
  SPIEL_CHECK_GE(action_id, 0);
  SPIEL_CHECK_LT(action_id, game_->MaxChanceOutcomes());
  if (action_id == kChanceInit0Action) {
    rewards_ = {0, 0};
    bool tagged = ResolveMove(0, moves_[0]);
    if (!tagged) {
      ResolveMove(1, moves_[1]);
    }
    returns_[0] += rewards_[0];
    returns_[1] += rewards_[1];
    total_moves_++;
  } else if (action_id == kChanceInit1Action) {
    rewards_ = {0, 0};
    bool tagged = ResolveMove(1, moves_[1]);
    if (!tagged) {
      ResolveMove(0, moves_[0]);
    }
    returns_[0] += rewards_[0];
    returns_[1] += rewards_[1];
    total_moves_++;
  } else {
    char spawning_player_char = ' ';
    int spawn_loc = action_id - kNumInitiativeChanceOutcomes;
    SPIEL_CHECK_GE(spawn_loc, 0);
    SPIEL_CHECK_LT(spawn_loc, grid_.spawn_points.size());
    // spawn locations and move resolve order
    if (!needs_respawn_.empty()) {
      int spawning_player = needs_respawn_.back();
      spawning_player_char = spawning_player == 0 ? 'A' : 'B';
    }
    SPIEL_CHECK_NE(spawning_player_char, ' ');
    SPIEL_CHECK_EQ(
        field(grid_.spawn_points[spawn_loc].first,
              grid_.spawn_points[spawn_loc].second), '.');
    SetField(grid_.spawn_points[spawn_loc].first,
             grid_.spawn_points[spawn_loc].second, spawning_player_char);
    needs_respawn_.pop_back();
  }
  if (needs_respawn_.empty()) {
    cur_player_ = kSimultaneousPlayerId;
  } else {
    cur_player_ = kChancePlayerId;
  }
}
References open_spiel::SimMoveState::ApplyFlatJointAction(), open_spiel::State::game_, open_spiel::State::IsChanceNode(), open_spiel::State::IsSimultaneousNode(), open_spiel::laser_tag::kChanceInit0Action, open_spiel::laser_tag::kChanceInit1Action, open_spiel::kChancePlayerId, open_spiel::laser_tag::kNumInitiativeChanceOutcomes, open_spiel::kSimultaneousPlayerId, open_spiel::laser_tag::Grid::spawn_points, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_NE, and SPIEL_CHECK_TRUE.
DoApplyActions()
void open_spiel::laser_tag::LaserTagState::DoApplyActions (const std::vector< Action > & moves) override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 227 of file laser_tag.cc.
{
  SPIEL_CHECK_EQ(moves.size(), 2);
  SPIEL_CHECK_EQ(cur_player_, kSimultaneousPlayerId);
  moves_[0] = moves[0];
  moves_[1] = moves[1];
  cur_player_ = kChancePlayerId;
}
References open_spiel::kChancePlayerId, open_spiel::kSimultaneousPlayerId, and SPIEL_CHECK_EQ.
IsTerminal()
bool open_spiel::laser_tag::LaserTagState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 524 of file laser_tag.cc.
{
  return ((horizon_ >= 0 && total_moves_ >= horizon_) ||
          (horizon_ < 0 && num_tags_ > 0));
}
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::laser_tag::LaserTagState::LegalActions (int player) const override virtual
Implements open_spiel::SimMoveState.
Definition at line 407 of file laser_tag.cc.
{
  if (IsTerminal()) return {};
  if (IsChanceNode()) {
    if (!needs_respawn_.empty()) {
      std::vector<Action> outcomes;
      for (int i = 0; i < grid_.spawn_points.size(); ++i) {
        if (field(grid_.spawn_points[i].first,
                  grid_.spawn_points[i].second) == '.') {
          outcomes.push_back(kNumInitiativeChanceOutcomes + i);
        }
      }
      return outcomes;
    } else {
      return {ToAction(ChanceOutcome::kChanceInit0),
              ToAction(ChanceOutcome::kChanceInit1)};
    }
  } else {
    return {kLeftTurn,  kRightTurn, kForwardMove, kBackwardMove, kStepLeft,
            kStepRight, kStand,     kForwardLeft, kForwardRight, kFire};
  }
}
References i, open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::laser_tag::kChanceInit0, open_spiel::laser_tag::kChanceInit1, open_spiel::laser_tag::kNumInitiativeChanceOutcomes, and open_spiel::laser_tag::Grid::spawn_points.
ObservationString()
std::string open_spiel::laser_tag::LaserTagState::ObservationString (int player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 471 of file laser_tag.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (fully_obs_) {
    return ToString();
  } else {
    return PartialObservationString(player);
  }
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::laser_tag::LaserTagState::ObservationTensor (int player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 591 of file laser_tag.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (fully_obs_) {
    FullObservationTensor(values);
  } else {
    PartialObservationTensor(player, values);
  }
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Reset()
void open_spiel::laser_tag::LaserTagState::Reset (int horizon, bool zero_sum)
Definition at line 209 of file laser_tag.cc.
{
  num_tags_ = 0;
  horizon_ = horizon;
  zero_sum_rewards_ = zero_sum;
  field_.resize(grid_.num_rows * grid_.num_cols, '.');
  for (auto i : grid_.obstacles) {
    SetField(i.first, i.second, '*');
  }
  cur_player_ = kChancePlayerId;
  total_moves_ = 0;
  needs_respawn_ = {0, 1};
  rewards_ = {0, 0};
  returns_ = {0, 0};
  player_facing_ = {{kSouth, kSouth}};
}
References i, open_spiel::kChancePlayerId, open_spiel::laser_tag::Grid::num_cols, open_spiel::laser_tag::Grid::num_rows, and open_spiel::laser_tag::Grid::obstacles.
Returns()
std::vector< double > open_spiel::laser_tag::LaserTagState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 531 of file laser_tag.cc.
{ return returns_; }
Rewards()
std::vector< double > open_spiel::laser_tag::LaserTagState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 529 of file laser_tag.cc.
{ return rewards_; }
ToString()
std::string open_spiel::laser_tag::LaserTagState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 454 of file laser_tag.cc.
{
  std::string result = "";
  for (int r = 0; r < grid_.num_rows; r++) {
    for (int c = 0; c < grid_.num_cols; c++) {
      result += field(r, c);
    }
    absl::StrAppend(&result, "\n");
  }
  absl::StrAppend(&result, "Orientations: ", player_facing_[0], " ",
                  player_facing_[1], "\n");
  if (IsChanceNode()) absl::StrAppend(&result, "Chance Node");
  return result;
}
References open_spiel::State::IsChanceNode(), open_spiel::laser_tag::Grid::num_cols, open_spiel::laser_tag::Grid::num_rows, r, and absl::StrAppend().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/laser_tag/laser_tag.h
open_spiel/games/laser_tag/laser_tag.cc