open spiel: absl::Status Class Reference
absl::Status Class Reference final
#include <status.h>
Public Member Functions
Status ()
Status (absl::StatusCode code, absl::string_view msg)
Status (const Status &)
Status & operator= (const Status &x)
Status (Status &&) noexcept
Status & operator= (Status &&)
~Status ()
void Update (const Status &new_status)
void Update (Status &&new_status)
ABSL_MUST_USE_RESULT bool ok () const
absl::StatusCode code () const
int raw_code () const
absl::string_view message () const
std::string ToString (StatusToStringMode mode=StatusToStringMode::kDefault) const
void IgnoreError () const
absl::optional< absl::Cord > GetPayload (absl::string_view type_url) const
void SetPayload (absl::string_view type_url, absl::Cord payload)
bool ErasePayload (absl::string_view type_url)
void ForEachPayload (absl::FunctionRef< void(absl::string_view, const absl::Cord &)> visitor) const
Friends
bool operator== (const Status &lhs, const Status &rhs)
bool operator!= (const Status &lhs, const Status &rhs)
void swap (absl::Status &a, absl::Status &b)
Status CancelledError ()
Detailed Description
Definition at line 424 of file status.h.
Constructor & Destructor Documentation
Status() [1/4]
absl::Status::Status () inline
Definition at line 758 of file status.h.
: rep_(CodeToInlinedRep(absl::StatusCode::kOk)) {}
Status() [2/4]
absl::Status::Status (absl::StatusCode code, absl::string_view msg)
Definition at line 225 of file status.cc.
    : rep_(CodeToInlinedRep(code)) {
  if (code != absl::StatusCode::kOk && !msg.empty()) {
    rep_ = PointerToRep(new status_internal::StatusRep(code, msg, nullptr));
  }
}
References code(), absl::kOk, and absl::msg.
Status() [3/4]
absl::Status::Status (const Status & x) inline
Definition at line 762 of file status.h.
: rep_(x.rep_) { Ref(rep_); }
Status() [4/4]
absl::Status::Status (Status && x) inline noexcept
Definition at line 774 of file status.h.
                                         : rep_(x.rep_) {
  x.rep_ = MovedFromRep();
}
References absl::x.
~Status()
absl::Status::~Status () inline
Definition at line 800 of file status.h.
{ Unref(rep_); }
Referenced by absl::internal_statusor::StatusOrData< T >::~StatusOrData().
Member Function Documentation
code()
absl::StatusCode absl::Status::code () const
Definition at line 240 of file status.cc.
{
  return status_internal::MapToLocalCode(raw_code());
}
References absl::status_internal::MapToLocalCode(), and raw_code().
Referenced by pybind11::google::internal::RegisterStatusBindings(), and Status().
ErasePayload()
bool absl::Status::ErasePayload (absl::string_view type_url)
Definition at line 154 of file status.cc.
{
  absl::optional<size_t> index =
      status_internal::FindPayloadIndexByUrl(GetPayloads(), type_url);
  if (index.has_value()) {
    PrepareToModify();
    GetPayloads()->erase(GetPayloads()->begin() + index.value());
    if (GetPayloads()->empty() && message().empty()) {
      // Special case: If this can be represented inlined, it MUST be
      // inlined (EqualsSlow depends on this behavior).
      StatusCode c = static_cast<StatusCode>(raw_code());
      Unref(rep_);
      rep_ = CodeToInlinedRep(c);
    }
    return true;
  }
  return false;
}
References begin, absl::c, absl::InlinedVector< T, N, A >::erase(), absl::optional< T >::has_value(), message(), raw_code(), and absl::optional< T >::value().
ForEachPayload()
void absl::Status::ForEachPayload (absl::FunctionRef< void(absl::string_view, const absl::Cord &)> visitor) const
Definition at line 173 of file status.cc.
          {
  if (auto* payloads = GetPayloads()) {
    bool in_reverse =
        payloads->size() > 1 && reinterpret_cast<uintptr_t>(payloads) % 13 > 6;
    for (size_t index = 0; index < payloads->size(); ++index) {
      const auto& elem =
          (*payloads)[in_reverse ? payloads->size() - 1 - index : index];
#ifdef NDEBUG
      visitor(elem.type_url, elem.payload);
#else
      // In debug mode invalidate the type url to prevent users from relying on
      // this string lifetime.
      // NOLINTNEXTLINE intentional extra conversion to force temporary.
      visitor(std::string(elem.type_url), elem.payload);
#endif  // NDEBUG
    }
  }
}
GetPayload()
absl::optional< absl::Cord > absl::Status::GetPayload (absl::string_view type_url) const
Definition at line 123 of file status.cc.
{
  const auto* payloads = GetPayloads();
  absl::optional<size_t> index =
      status_internal::FindPayloadIndexByUrl(payloads, type_url);
  if (index.has_value())
    return (*payloads)[index.value()].payload;
  return absl::nullopt;
}
References absl::optional< T >::has_value(), and absl::optional< T >::value().
IgnoreError()
void absl::Status::IgnoreError () const inline
Definition at line 825 of file status.h.
{
  // no-op
}
Referenced by pybind11::google::internal::RegisterStatusBindings().
message()
absl::string_view absl::Status::message () const inline
Definition at line 806 of file status.h.
{
  return !IsInlined(rep_)
             ? RepToPointer(rep_)->message
             : (IsMovedFrom(rep_) ? absl::string_view(kMovedFromString)
                                  : absl::string_view());
}
References absl::status_internal::StatusRep::message.
Referenced by ErasePayload(), and pybind11::google::internal::RegisterStatusBindings().
ok()
bool absl::Status::ok () const inline
Definition at line 802 of file status.h.
{
  return rep_ == CodeToInlinedRep(absl::StatusCode::kOk);
}
References absl::kOk.
Referenced by absl::internal_statusor::StatusOrData< T >::ok(), pybind11::google::internal::RegisterStatusBindings(), SetPayload(), ToString(), Update(), and Update().
operator=() [1/2]
Status & absl::Status::operator= (const Status & x) inline
Definition at line 764 of file status.h.
{
  uintptr_t old_rep = rep_;
  if (x.rep_ != old_rep) {
    Ref(x.rep_);
    rep_ = x.rep_;
    Unref(old_rep);
  }
  return *this;
}
References absl::x.
operator=() [2/2]
Status & absl::Status::operator= (Status && x) inline
Definition at line 778 of file status.h.
{
  uintptr_t old_rep = rep_;
  if (x.rep_ != old_rep) {
    rep_ = x.rep_;
    x.rep_ = MovedFromRep();
    Unref(old_rep);
  }
  return *this;
}
References absl::x.
raw_code()
int absl::Status::raw_code () const
Definition at line 232 of file status.cc.
{
  if (IsInlined(rep_)) {
    return static_cast<int>(InlinedRepToCode(rep_));
  }
  status_internal::StatusRep* rep = RepToPointer(rep_);
  return static_cast<int>(rep->code);
}
References rep.
Referenced by code(), ErasePayload(), and pybind11::google::internal::RegisterStatusBindings().
SetPayload()
void absl::Status::SetPayload (absl::string_view type_url, absl::Cord payload)
Definition at line 134 of file status.cc.
{
  if (ok()) return;
  PrepareToModify();
  status_internal::StatusRep* rep = RepToPointer(rep_);
  if (!rep->payloads) {
    rep->payloads = absl::make_unique<status_internal::Payloads>();
  }
  absl::optional<size_t> index =
      status_internal::FindPayloadIndexByUrl(rep->payloads.get(), type_url);
  if (index.has_value()) {
    (*rep->payloads)[index.value()].payload = std::move(payload);
    return;
  }
  rep->payloads->push_back({std::string(type_url), std::move(payload)});
}
References absl::optional< T >::has_value(), ok(), rep, and absl::optional< T >::value().
ToString()
std::string absl::Status::ToString (StatusToStringMode mode = StatusToStringMode::kDefault) const inline
Definition at line 821 of file status.h.
{
  return ok() ? "OK" : ToStringSlow(mode);
}
References ok().
Update() [1/2]
void absl::Status::Update (const Status & new_status) inline
Definition at line 788 of file status.h.
{
  if (ok()) {
    *this = new_status;
  }
}
References ok().
Referenced by pybind11::google::internal::RegisterStatusBindings().
Update() [2/2]
void absl::Status::Update (Status && new_status) inline
Definition at line 794 of file status.h.
{
  if (ok()) {
    *this = std::move(new_status);
  }
}
References ok().
Friends And Related Symbol Documentation
CancelledError
Status CancelledError () friend
Definition at line 887 of file status.h.
{ return Status(absl::StatusCode::kCancelled); }
operator!=
bool operator!= (const Status & lhs, const Status & rhs) friend
Definition at line 817 of file status.h.
{
  return !(lhs == rhs);
}
operator==
bool operator== (const Status & lhs, const Status & rhs) friend
Definition at line 813 of file status.h.
{
  return lhs.rep_ == rhs.rep_ || Status::EqualsSlow(lhs, rhs);
}
swap
void swap (absl::Status & a, absl::Status & b) friend
Definition at line 829 of file status.h.
{
  using std::swap;
  swap(a.rep_, b.rep_);
}
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/status/status.h
open_spiel/abseil-cpp/absl/status/status.cc