open spiel: absl::functional_internal::FrontBinder< F, BoundArgs > Class Template Reference
absl::functional_internal::FrontBinder< F, BoundArgs > Class Template Reference
#include <front_binder.h>
Public Member Functions
template<class... Ts>
constexpr FrontBinder (absl::in_place_t, Ts &&... ts)
template<class... FreeArgs, class R = base_internal::invoke_result_t< F&, BoundArgs&..., FreeArgs&&...>>
R operator() (FreeArgs &&... free_args) &
template<class... FreeArgs, class R = base_internal::invoke_result_t< const F&, const BoundArgs&..., FreeArgs&&...>>
R operator() (FreeArgs &&... free_args) const &
template<class... FreeArgs, class R = base_internal::invoke_result_t< F&&, BoundArgs&&..., FreeArgs&&...>>
R operator() (FreeArgs &&... free_args) &&
template<class... FreeArgs, class R = base_internal::invoke_result_t< const F&&, const BoundArgs&&..., FreeArgs&&...>>
R operator() (FreeArgs &&... free_args) const &&
Detailed Description
template<class F, class... BoundArgs>
class absl::functional_internal::FrontBinder< F, BoundArgs >
Definition at line 42 of file front_binder.h.
Constructor & Destructor Documentation
FrontBinder()
template<class F , class... BoundArgs> template<class... Ts> absl::functional_internal::FrontBinder< F, BoundArgs >::FrontBinder (absl::in_place_t , Ts &&... ts) inline explicit constexpr
Definition at line 50 of file front_binder.h.
      : bound_args_(absl::forward<Ts>(ts)...) {}
Member Function Documentation
operator()() [1/4]
template<class F , class... BoundArgs> template<class... FreeArgs, class R = base_internal::invoke_result_t< F&, BoundArgs&..., FreeArgs&&...>> R absl::functional_internal::FrontBinder< F, BoundArgs >::operator() (FreeArgs &&... free_args) & inline
Definition at line 55 of file front_binder.h.
{
    return functional_internal::Apply<R>(bound_args_, Idx(),
                                         absl::forward<FreeArgs>(free_args)...);
  }
References absl::functional_internal::Apply(), and absl::forward().
operator()() [2/4]
template<class F , class... BoundArgs> template<class... FreeArgs, class R = base_internal::invoke_result_t< F&&, BoundArgs&&..., FreeArgs&&...>> R absl::functional_internal::FrontBinder< F, BoundArgs >::operator() (FreeArgs &&... free_args) && inline
Definition at line 70 of file front_binder.h.
{
    // This overload is called when *this is an rvalue. If some of the bound
    // arguments are stored by value or rvalue reference, we move them.
    return functional_internal::Apply<R>(absl::move(bound_args_), Idx(),
                                         absl::forward<FreeArgs>(free_args)...);
  }
References absl::functional_internal::Apply(), absl::forward(), and absl::move().
operator()() [3/4]
template<class F , class... BoundArgs> template<class... FreeArgs, class R = base_internal::invoke_result_t< const F&, const BoundArgs&..., FreeArgs&&...>> R absl::functional_internal::FrontBinder< F, BoundArgs >::operator() (FreeArgs &&... free_args) const & inline
Definition at line 63 of file front_binder.h.
{
    return functional_internal::Apply<R>(bound_args_, Idx(),
                                         absl::forward<FreeArgs>(free_args)...);
  }
References absl::functional_internal::Apply(), and absl::forward().
operator()() [4/4]
template<class F , class... BoundArgs> template<class... FreeArgs, class R = base_internal::invoke_result_t< const F&&, const BoundArgs&&..., FreeArgs&&...>> R absl::functional_internal::FrontBinder< F, BoundArgs >::operator() (FreeArgs &&... free_args) const && inline
Definition at line 80 of file front_binder.h.
{
    // This overload is called when *this is an rvalue. If some of the bound
    // arguments are stored by value or rvalue reference, we move them.
    return functional_internal::Apply<R>(absl::move(bound_args_), Idx(),
                                         absl::forward<FreeArgs>(free_args)...);
  }
References absl::functional_internal::Apply(), absl::forward(), and absl::move().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/functional/internal/front_binder.h