open spiel: absl::WriterMutexLock Class Reference
absl::WriterMutexLock Class Reference
#include <mutex.h>
Public Member Functions
WriterMutexLock (Mutex *mu) ABSL_EXCLUSIVE_LOCK_FUNCTION(mu)
WriterMutexLock (Mutex *mu, const Condition &cond) ABSL_EXCLUSIVE_LOCK_FUNCTION(mu)
WriterMutexLock (const WriterMutexLock &)=delete
WriterMutexLock (WriterMutexLock &&)=delete
WriterMutexLock & operator= (const WriterMutexLock &)=delete
WriterMutexLock & operator= (WriterMutexLock &&)=delete
~WriterMutexLock () ABSL_UNLOCK_FUNCTION()
Detailed Description
Definition at line 589 of file mutex.h.
Constructor & Destructor Documentation
WriterMutexLock() [1/4]
absl::WriterMutexLock::WriterMutexLock (Mutex * mu) inline explicit
Definition at line 591 of file mutex.h.
      : mu_(mu) {
    mu->WriterLock();
  }
References absl::Mutex::WriterLock().
WriterMutexLock() [2/4]
absl::WriterMutexLock::WriterMutexLock (Mutex * mu, const Condition & cond) inline explicit
Definition at line 596 of file mutex.h.
      : mu_(mu) {
    mu->WriterLockWhen(cond);
  }
References absl::Mutex::WriterLockWhen().
WriterMutexLock() [3/4]
absl::WriterMutexLock::WriterMutexLock (const WriterMutexLock &) delete
WriterMutexLock() [4/4]
absl::WriterMutexLock::WriterMutexLock (WriterMutexLock &&) delete
~WriterMutexLock()
absl::WriterMutexLock::~WriterMutexLock () inline
Definition at line 607 of file mutex.h.
{ this->mu_->WriterUnlock(); }
References absl::Mutex::WriterUnlock().
Member Function Documentation
operator=() [1/2]
WriterMutexLock & absl::WriterMutexLock::operator= (const WriterMutexLock &) delete
operator=() [2/2]
WriterMutexLock & absl::WriterMutexLock::operator= (WriterMutexLock &&) delete
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/synchronization/mutex.h