open spiel: open_spiel::coin_game::CoinGame Class Reference
open_spiel::coin_game::CoinGame Class Reference
#include <coin_game.h>
Public Member Functions
CoinGame (const GameParameters &params)
int NumDistinctActions () const override
int MaxChanceOutcomes () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MaxUtility () const override
double MinUtility () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int NumRows () const
int NumColumns () const
int EpisodeLength () const
int NumCoinColors () const
int NumCoinsPerColor () const
int TotalCoins () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual std::vector< int > ObservationTensorShape () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 122 of file coin_game.h.
Constructor & Destructor Documentation
CoinGame()
open_spiel::coin_game::CoinGame::CoinGame (const GameParameters & params) explicit
Definition at line 451 of file coin_game.cc.
    : Game(kGameType, params),
      num_players_(ParameterValue<int>("players")),
      num_rows_(ParameterValue<int>("rows")),
      num_columns_(ParameterValue<int>("columns")),
      episode_length_(ParameterValue<int>("episode_length")),
      num_coin_colors_(num_players_ +
                       ParameterValue<int>("num_extra_coin_colors")),
      num_coins_per_color_(ParameterValue<int>("num_coins_per_color")) {
  int total_items = num_players_ + num_coin_colors_ * num_coins_per_color_;
  SPIEL_CHECK_LE(total_items, num_rows_ * num_columns_);
}
References SPIEL_CHECK_LE.
Member Function Documentation
EpisodeLength()
int open_spiel::coin_game::CoinGame::EpisodeLength () const inline
Definition at line 138 of file coin_game.h.
{ return episode_length_; }
Referenced by open_spiel::coin_game::CoinState::IsTerminal().
MaxChanceNodesInHistory()
int open_spiel::coin_game::CoinGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 134 of file coin_game.h.
{ return MaxGameLength(); }
References MaxGameLength().
MaxChanceOutcomes()
int open_spiel::coin_game::CoinGame::MaxChanceOutcomes () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 469 of file coin_game.cc.
{
  return std::max(num_coin_colors_, num_rows_ * num_columns_);
}
MaxGameLength()
int open_spiel::coin_game::CoinGame::MaxGameLength () const override virtual
Implements open_spiel::Game.
Definition at line 464 of file coin_game.cc.
{ return (episode_length_); }
Referenced by MaxChanceNodesInHistory().
MaxUtility()
double open_spiel::coin_game::CoinGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 447 of file coin_game.cc.
{ return std::pow(TotalCoins(), 2); }
References TotalCoins().
Referenced by MinUtility().
MinUtility()
double open_spiel::coin_game::CoinGame::MinUtility () const override virtual
Implements open_spiel::Game.
Definition at line 449 of file coin_game.cc.
{ return -MaxUtility(); }
References MaxUtility().
NewInitialState()
std::unique_ptr< State > open_spiel::coin_game::CoinGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 473 of file coin_game.cc.
{
  return std::unique_ptr<State>(new CoinState(shared_from_this()));
}
NumCoinColors()
int open_spiel::coin_game::CoinGame::NumCoinColors () const inline
Definition at line 139 of file coin_game.h.
{ return num_coin_colors_; }
Referenced by open_spiel::coin_game::CoinState::Returns().
NumCoinsPerColor()
int open_spiel::coin_game::CoinGame::NumCoinsPerColor () const inline
Definition at line 140 of file coin_game.h.
{ return num_coins_per_color_; }
NumColumns()
int open_spiel::coin_game::CoinGame::NumColumns () const inline
Definition at line 137 of file coin_game.h.
{ return num_columns_; }
NumDistinctActions()
int open_spiel::coin_game::CoinGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 467 of file coin_game.cc.
{ return offsets.size(); }
NumPlayers()
int open_spiel::coin_game::CoinGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 129 of file coin_game.h.
{ return num_players_; }
NumRows()
int open_spiel::coin_game::CoinGame::NumRows () const inline
Definition at line 136 of file coin_game.h.
{ return num_rows_; }
TotalCoins()
int open_spiel::coin_game::CoinGame::TotalCoins () const inline
Definition at line 141 of file coin_game.h.
{ return num_coin_colors_ * num_coins_per_color_; }
Referenced by MaxUtility().
The documentation for this class was generated from the following files:
open_spiel/games/coin_game/coin_game.h
open_spiel/games/coin_game/coin_game.cc