open spiel: open_spiel::ObserverRegisterer Class Reference
open_spiel::ObserverRegisterer Class Reference
#include <observer.h>
Public Types
using CreateFunc
Public Member Functions
ObserverRegisterer (const std::string &game_name, const std::string &observer_name, CreateFunc creator)
Static Public Member Functions
static void RegisterObserver (const std::string &game_name, const std::string &observer_name, CreateFunc creator)
static std::shared_ptr< Observer > CreateByName (const std::string &observer_name, const Game &game, absl::optional< IIGObservationType > iig_obs_type, const ObservationParams &params)
Detailed Description
Definition at line 414 of file observer.h.
Member Typedef Documentation
CreateFunc
using open_spiel::ObserverRegisterer::CreateFunc
Initial value:
 std::function<std::shared_ptr<Observer>(
      const Game& game, absl::optional<IIGObservationType> iig_obs_type,
      const ObservationParams& params)>
Definition at line 418 of file observer.h.
Constructor & Destructor Documentation
ObserverRegisterer()
open_spiel::ObserverRegisterer::ObserverRegisterer (const std::string & game_name, const std::string & observer_name, CreateFunc creator)
Definition at line 330 of file observer.cc.
{
  RegisterObserver(game_name, observer_name, creator);
}
References RegisterObserver().
Member Function Documentation
CreateByName()
std::shared_ptr< Observer > open_spiel::ObserverRegisterer::CreateByName (const std::string & observer_name, const Game & game, absl::optional< IIGObservationType > iig_obs_type, const ObservationParams & params) static
Definition at line 359 of file observer.cc.
{
  auto key = std::pair(game.GetType().short_name, observer_name);
  auto it = observers().find(key);
  if (it == observers().end()) {
    SpielFatalError(absl::StrCat("No observer '", key.second, "'",
                                 " found for game '", key.first, "'"));
  }
  return it->second(game, iig_obs_type, params);
}
References end, key, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::Game::MakeRegisteredObserver().
RegisterObserver()
void open_spiel::ObserverRegisterer::RegisterObserver (const std::string & game_name, const std::string & observer_name, CreateFunc creator) static
Definition at line 336 of file observer.cc.
{
  auto key = std::pair(game_name, observer_name);
  if (observers().find(key) != observers().end()) {
    SpielFatalError(absl::StrCat("Duplicate observer '", key.second, "'",
                                 " for game '", key.first, "'"));
  }
  observers()[key] = creator;
}
References end, key, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by ObserverRegisterer().
The documentation for this class was generated from the following files:
open_spiel/observer.h
open_spiel/observer.cc