open spiel: open_spiel::dou_dizhu::DouDizhuState Class Reference
open_spiel::dou_dizhu::DouDizhuState Class Reference
#include <dou_dizhu.h>
Public Member Functions
DouDizhuState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void WriteObservationTensor (Player player, absl::Span< float > values) const
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
int CurrentPhase () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 93 of file dou_dizhu.h.
Constructor & Destructor Documentation
DouDizhuState()
open_spiel::dou_dizhu::DouDizhuState::DouDizhuState (std::shared_ptr< const Game > game)
Definition at line 53 of file dou_dizhu.cc.
                                                           : State(game) {
  absl::c_fill(dealer_deck_, 1);
}
References absl::c_fill().
Member Function Documentation
ActionToString()
std::string open_spiel::dou_dizhu::DouDizhuState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 57 of file dou_dizhu.cc.
{
  if (player == kChancePlayerId) {
    if (action < kDealingActionBase) {
      return absl::StrCat("Decide first card up position ", action);
    } else if (action < kDealingActionBase + kNumCards) {
      return absl::StrCat("Deal ", CardString(action - kDealingActionBase));
    } else {
      SpielFatalError(
          absl::StrFormat("Non valid ID %d for chance player", action));
    }
  }
  if (action == kPass) {
    return "Pass";
  } else if (action > kPass && action < kPlayActionBase) {
    return absl::StrCat("Bid ", action - kBiddingActionBase);
  } else if (action >= kPlayActionBase && action <= kRocketActionBase) {
    // For aiplane combinations, need special treatment to resolve ambiguity
    if (action >= kAirplaneWithSoloActionBase && action < kBombActionBase) {
      return FormatAirplaneCombHand(action);
    }
    return FormatSingleHand(ActionToHand(action));
  } else {
    SpielFatalError("Non valid action ID!");
  }
}
References action, open_spiel::dou_dizhu::ActionToHand(), open_spiel::dou_dizhu::CardString(), open_spiel::dou_dizhu::FormatAirplaneCombHand(), open_spiel::dou_dizhu::FormatSingleHand(), open_spiel::dou_dizhu::kAirplaneWithSoloActionBase, open_spiel::dou_dizhu::kBiddingActionBase, open_spiel::dou_dizhu::kBombActionBase, open_spiel::kChancePlayerId, open_spiel::dou_dizhu::kDealingActionBase, open_spiel::dou_dizhu::kNumCards, open_spiel::dou_dizhu::kPass, open_spiel::dou_dizhu::kPlayActionBase, open_spiel::dou_dizhu::kRocketActionBase, player, open_spiel::SpielFatalError(), absl::StrCat(), and absl::StrFormat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::dou_dizhu::DouDizhuState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 293 of file dou_dizhu.cc.
{
  std::vector<std::pair<Action, double>> outcomes;
  int num_cards_remaining = 0;
  for (int i = 0; i < kNumCards; ++i) num_cards_remaining += dealer_deck_[i];
  outcomes.reserve(num_cards_remaining);
  if (card_face_up_position_ == -1) {
    for (int i = 0; i < kDealingActionBase; ++i)
      outcomes.emplace_back(i, 1.0 / static_cast<double>(kDealingActionBase));
  } else {
    for (int card = 0; card < kNumCards; ++card)
      if (dealer_deck_[card])
        outcomes.emplace_back(card + kDealingActionBase,
                              1.0 / static_cast<double>(num_cards_remaining));
  }
  return outcomes;
}
References i, open_spiel::dou_dizhu::kDealingActionBase, and open_spiel::dou_dizhu::kNumCards.
Clone()
std::unique_ptr< State > open_spiel::dou_dizhu::DouDizhuState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 105 of file dou_dizhu.h.
{
    return absl::make_unique<DouDizhuState>(*this);
  }
CurrentPhase()
int open_spiel::dou_dizhu::DouDizhuState::CurrentPhase () const inline
Definition at line 111 of file dou_dizhu.h.
{ return static_cast<int>(phase_); }
CurrentPlayer()
Player open_spiel::dou_dizhu::DouDizhuState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 437 of file dou_dizhu.cc.
{
  if (phase_ == Phase::kDeal) {
    return kChancePlayerId;
  } else if (phase_ == Phase::kGameOver) {
    return kTerminalPlayerId;
  } else {
    return current_player_;
  }
}
References open_spiel::kChancePlayerId, open_spiel::dou_dizhu::kDeal, open_spiel::dou_dizhu::kGameOver, and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::dou_dizhu::DouDizhuState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 312 of file dou_dizhu.cc.
{
  switch (phase_) {
    case Phase::kDeal:
      return ApplyDealAction(action);
    case Phase::kAuction:
      return ApplyBiddingAction(action);
    case Phase::kPlay:
      return ApplyPlayAction(action);
    case Phase::kGameOver:
      SpielFatalError("Cannot act in terminal states");
  }
}
References action, open_spiel::dou_dizhu::kAuction, open_spiel::dou_dizhu::kDeal, open_spiel::dou_dizhu::kGameOver, open_spiel::dou_dizhu::kPlay, and open_spiel::SpielFatalError().
IsTerminal()
bool open_spiel::dou_dizhu::DouDizhuState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 99 of file dou_dizhu.h.
{ return phase_ == Phase::kGameOver; }
References open_spiel::dou_dizhu::kGameOver.
Referenced by ToString().
LegalActions()
std::vector< Action > open_spiel::dou_dizhu::DouDizhuState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 242 of file dou_dizhu.cc.
{
  switch (phase_) {
    case Phase::kDeal:
      return DealLegalActions();
    case Phase::kAuction:
      return BiddingLegalActions();
    case Phase::kPlay:
      return PlayLegalActions();
    default:
      return {};
  }
}
References open_spiel::dou_dizhu::kAuction, open_spiel::dou_dizhu::kDeal, and open_spiel::dou_dizhu::kPlay.
ObservationString()
std::string open_spiel::dou_dizhu::DouDizhuState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 192 of file dou_dizhu.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string rv =
      absl::StrFormat("My hand %s\n", FormatSingleHand(holds_[player]));
  absl::StrAppend(&rv, absl::StrFormat("Played cards %s\n",
                                       FormatSingleHand(played_deck_)));
  absl::StrAppend(&rv,
                  absl::StrFormat("face up card rank: %d", card_rank_face_up_));
  absl::StrAppend(&rv, absl::StrFormat("start player: %d", first_player_));
  absl::StrAppend(
      &rv, absl::StrFormat("My position from Dizhu: %d",
                           (player - dizhu_ + kNumPlayers) % kNumPlayers));
  return rv;
}
References open_spiel::dou_dizhu::FormatSingleHand(), open_spiel::dou_dizhu::kNumPlayers, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and absl::StrFormat().
ObservationTensor()
void open_spiel::dou_dizhu::DouDizhuState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 208 of file dou_dizhu.cc.
{
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  WriteObservationTensor(player, values);
}
References open_spiel::State::game_, player, SPIEL_CHECK_EQ, values, and WriteObservationTensor().
Returns()
std::vector< double > open_spiel::dou_dizhu::DouDizhuState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 100 of file dou_dizhu.h.
{ return returns_; }
ToString()
std::string open_spiel::dou_dizhu::DouDizhuState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 84 of file dou_dizhu.cc.
{
  std::string rv = FormatDeal();
  if (history_.size() > kNumCards - kNumCardsLeftOver + 1)
    absl::StrAppend(&rv, FormatAuction());
  if (num_played_ > 0) absl::StrAppend(&rv, FormatPlay());
  if (IsTerminal()) absl::StrAppend(&rv, FormatResult());
  return rv;
}
References open_spiel::State::history_, IsTerminal(), open_spiel::dou_dizhu::kNumCards, open_spiel::dou_dizhu::kNumCardsLeftOver, and absl::StrAppend().
WriteObservationTensor()
void open_spiel::dou_dizhu::DouDizhuState::WriteObservationTensor (Player player, absl::Span< float > values) const
Definition at line 214 of file dou_dizhu.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  absl::c_fill(values, 0.);
  if (phase_ == Phase::kDeal) return;
  auto values_iterator = values.begin();
  const int played_deck_base = (kNumRanks - 2) * (kNumSuits + 1) + 2 * 2;
  for (int i = 0; i < kNumRanks; ++i) {
    values_iterator[i * (kNumSuits + 1) + holds_[player][i]] = 1;
    values_iterator[played_deck_base + i * (kNumSuits + 1) + played_deck_[i]] =
        1;
  }
  if (dizhu_ != kInvalidPlayer) {
    const int from_dizhu_base = 2 * played_deck_base;
    const int from_dizhu = (player - dizhu_ + kNumPlayers) % kNumPlayers;
    values_iterator[from_dizhu_base + from_dizhu] = 1;
  }
  if (first_player_ != kInvalidPlayer) {
    const int start_player_base = 2 * played_deck_base + kNumPlayers;
    values_iterator[start_player_base + first_player_] = 1;
    values_iterator[start_player_base + kNumPlayers + card_rank_face_up_] = 1;
  }
}
References absl::c_fill(), i, open_spiel::dou_dizhu::kDeal, open_spiel::kInvalidPlayer, open_spiel::dou_dizhu::kNumPlayers, open_spiel::dou_dizhu::kNumRanks, open_spiel::dou_dizhu::kNumSuits, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Referenced by ObservationTensor().
The documentation for this class was generated from the following files:
open_spiel/games/dou_dizhu/dou_dizhu.h
open_spiel/games/dou_dizhu/dou_dizhu.cc