open spiel: open_spiel::pathfinding::PathfindingGame Class Reference
open_spiel::pathfinding::PathfindingGame Class Reference
#include <pathfinding.h>
Public Member Functions
PathfindingGame (const GameParameters &params)
int NumDistinctActions () const
std::string ActionToString (int player, Action action_id) const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int NumObservationPlanes () const
const std::vector< Action > & legal_actions () const
double group_reward () const
double solve_reward () const
double step_reward () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::SimMoveGame
SimMoveGame (GameType game_type, GameParameters game_parameters)
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 96 of file pathfinding.h.
Constructor & Destructor Documentation
PathfindingGame()
open_spiel::pathfinding::PathfindingGame::PathfindingGame (const GameParameters & params) explicit
Definition at line 590 of file pathfinding.cc.
    : SimMoveGame(kGameType, params),
      grid_spec_(ParseGrid(ParameterValue<std::string>(
          "grid", std::string(kDefaultSingleAgentGrid)),
                           kGameType.max_num_players)),
      num_players_(ParameterValue<int>("players", kDefaultNumPlayers)),
      horizon_(ParameterValue<int>("horizon", kDefaultHorizon)),
      group_reward_(ParameterValue<double>("group_reward",
                                           kDefaultGroupReward)),
      solve_reward_(
          ParameterValue<double>("solve_reward", kDefaultSolveReward)),
      step_reward_(ParameterValue<double>("step_reward", kDefaultStepReward)),
      legal_actions_({kStay, kLeft, kUp, kRight, kDown}) {
  // Override the number of players from the grid specification.
  //
  // Currently, the game only supports specific grids, so this will always be
  // overridden. This will change in a future version with random grids.
  if (grid_spec_.num_players >= 1) {
    num_players_ = grid_spec_.num_players;
  }
}
References open_spiel::pathfinding::kLeft, open_spiel::pathfinding::kRight, open_spiel::pathfinding::kStay, and open_spiel::pathfinding::kUp.
Member Function Documentation
ActionToString()
std::string open_spiel::pathfinding::PathfindingGame::ActionToString (int player, Action action_id) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 566 of file pathfinding.cc.
{
  if (player == kChancePlayerId) {
    return absl::StrCat("Chance outcome ", action_id);
  }
  switch (action_id) {
    case kStay:
      return "Stay";
    case kLeft:
      return "Left";
    case kUp:
      return "Up";
    case kRight:
      return "Right";
    case kDown:
      return "Down";
    default:
      SpielFatalError(absl::StrCat("Unknown action: ", action_id));
  }
}
References open_spiel::kChancePlayerId, open_spiel::pathfinding::kDown, open_spiel::pathfinding::kLeft, open_spiel::pathfinding::kRight, open_spiel::pathfinding::kStay, open_spiel::pathfinding::kUp, player, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::pathfinding::PathfindingState::ActionToString().
group_reward()
double open_spiel::pathfinding::PathfindingGame::group_reward () const inline
Definition at line 112 of file pathfinding.h.
{ return group_reward_; }
Referenced by open_spiel::pathfinding::PathfindingState::DoApplyActions().
legal_actions()
const std::vector< Action > & open_spiel::pathfinding::PathfindingGame::legal_actions () const inline
Definition at line 111 of file pathfinding.h.
{ return legal_actions_; }
Referenced by open_spiel::pathfinding::PathfindingState::LegalActions().
MaxChanceNodesInHistory()
int open_spiel::pathfinding::PathfindingGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 108 of file pathfinding.h.
{ return MaxGameLength(); }
References MaxGameLength().
MaxChanceOutcomes()
int open_spiel::pathfinding::PathfindingGame::MaxChanceOutcomes () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 539 of file pathfinding.cc.
{
  return Factorial(NumPlayers());
}
References open_spiel::Factorial(), and NumPlayers().
MaxGameLength()
int open_spiel::pathfinding::PathfindingGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 107 of file pathfinding.h.
{ return horizon_; }
Referenced by MaxChanceNodesInHistory().
MaxUtility()
double open_spiel::pathfinding::PathfindingGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 548 of file pathfinding.cc.
{
  return solve_reward_ + group_reward_;
}
MinUtility()
double open_spiel::pathfinding::PathfindingGame::MinUtility () const override virtual
Implements open_spiel::Game.
Definition at line 543 of file pathfinding.cc.
{
  // Add a small constant here due to numeral issues.
  return horizon_ * step_reward_ - FloatingPointDefaultTolerance();
}
References open_spiel::FloatingPointDefaultTolerance().
NewInitialState()
std::unique_ptr< State > open_spiel::pathfinding::PathfindingGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 534 of file pathfinding.cc.
{
  return std::unique_ptr<PathfindingState>(
      new PathfindingState(shared_from_this(), grid_spec_, horizon_));
}
NumDistinctActions()
int open_spiel::pathfinding::PathfindingGame::NumDistinctActions () const inline virtual
Implements open_spiel::Game.
Definition at line 99 of file pathfinding.h.
{ return kNumActions; }
References open_spiel::pathfinding::kNumActions.
NumObservationPlanes()
int open_spiel::pathfinding::PathfindingGame::NumObservationPlanes () const
Definition at line 552 of file pathfinding.cc.
{
  // Number of position planes:
  // - one per player present on the pos
  // - one per player (starting position)
  // - one per player (destination)
  // - one for empty positions
  // - one for wall positions
  return 3 * grid_spec_.num_players + 2;
}
References open_spiel::pathfinding::GridSpec::num_players.
Referenced by open_spiel::pathfinding::PathfindingState::ObservationTensor(), and ObservationTensorShape().
NumPlayers()
int open_spiel::pathfinding::PathfindingGame::NumPlayers () const override virtual
Implements open_spiel::Game.
Definition at line 588 of file pathfinding.cc.
{ return num_players_; }
Referenced by MaxChanceOutcomes().
ObservationTensorShape()
std::vector< int > open_spiel::pathfinding::PathfindingGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 562 of file pathfinding.cc.
{
  return {NumObservationPlanes(), grid_spec_.num_rows, grid_spec_.num_cols};
}
References open_spiel::pathfinding::GridSpec::num_cols, open_spiel::pathfinding::GridSpec::num_rows, and NumObservationPlanes().
solve_reward()
double open_spiel::pathfinding::PathfindingGame::solve_reward () const inline
Definition at line 113 of file pathfinding.h.
{ return solve_reward_; }
step_reward()
double open_spiel::pathfinding::PathfindingGame::step_reward () const inline
Definition at line 114 of file pathfinding.h.
{ return step_reward_; }
The documentation for this class was generated from the following files:
open_spiel/games/pathfinding/pathfinding.h
open_spiel/games/pathfinding/pathfinding.cc