open spiel: absl::InlinedVector< T, N, A > Class Template Reference
absl::InlinedVector< T, N, A > Class Template Reference
#include <inlined_vector.h>
Public Types
using allocator_type = A
using value_type = inlined_vector_internal::ValueType<A>
using pointer = inlined_vector_internal::Pointer<A>
using const_pointer = inlined_vector_internal::ConstPointer<A>
using size_type = inlined_vector_internal::SizeType<A>
using difference_type = inlined_vector_internal::DifferenceType<A>
using reference = inlined_vector_internal::Reference<A>
using const_reference = inlined_vector_internal::ConstReference<A>
using iterator = inlined_vector_internal::Iterator<A>
using const_iterator = inlined_vector_internal::ConstIterator<A>
using reverse_iterator = inlined_vector_internal::ReverseIterator<A>
using const_reverse_iterator
Public Member Functions
InlinedVector () noexcept(noexcept(allocator_type()))
InlinedVector (const allocator_type &allocator) noexcept
InlinedVector (size_type n, const allocator_type &allocator=allocator_type())
InlinedVector (size_type n, const_reference v, const allocator_type &allocator=allocator_type())
InlinedVector (std::initializer_list< value_type > list, const allocator_type &allocator=allocator_type())
template<typename ForwardIterator , EnableIfAtLeastForwardIterator< ForwardIterator > = 0>
InlinedVector (ForwardIterator first, ForwardIterator last, const allocator_type &allocator=allocator_type())
template<typename InputIterator , DisableIfAtLeastForwardIterator< InputIterator > = 0>
InlinedVector (InputIterator first, InputIterator last, const allocator_type &allocator=allocator_type())
InlinedVector (const InlinedVector &other)
InlinedVector (const InlinedVector &other, const allocator_type &allocator)
InlinedVector (InlinedVector &&other) noexcept(absl::allocator_is_nothrow< allocator_type >::value||std::is_nothrow_move_constructible< value_type >::value)
InlinedVector (InlinedVector &&other, const allocator_type &allocator) noexcept(absl::allocator_is_nothrow< allocator_type >::value)
~InlinedVector ()
bool empty () const noexcept
size_type size () const noexcept
size_type max_size () const noexcept
size_type capacity () const noexcept
pointer data () noexcept
const_pointer data () const noexcept
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
reference at (size_type i)
const_reference at (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
allocator_type get_allocator () const
InlinedVector & operator= (std::initializer_list< value_type > list)
InlinedVector & operator= (const InlinedVector &other)
InlinedVector & operator= (InlinedVector &&other)
void assign (size_type n, const_reference v)
void assign (std::initializer_list< value_type > list)
template<typename ForwardIterator , EnableIfAtLeastForwardIterator< ForwardIterator > = 0>
void assign (ForwardIterator first, ForwardIterator last)
template<typename InputIterator , DisableIfAtLeastForwardIterator< InputIterator > = 0>
void assign (InputIterator first, InputIterator last)
void resize (size_type n)
void resize (size_type n, const_reference v)
iterator insert (const_iterator pos, const_reference v)
iterator insert (const_iterator pos, value_type &&v)
iterator insert (const_iterator pos, size_type n, const_reference v)
iterator insert (const_iterator pos, std::initializer_list< value_type > list)
template<typename ForwardIterator , EnableIfAtLeastForwardIterator< ForwardIterator > = 0>
iterator insert (const_iterator pos, ForwardIterator first, ForwardIterator last)
template<typename InputIterator , DisableIfAtLeastForwardIterator< InputIterator > = 0>
iterator insert (const_iterator pos, InputIterator first, InputIterator last)
template<typename... Args>
iterator emplace (const_iterator pos, Args &&... args)
template<typename... Args>
reference emplace_back (Args &&... args)
void push_back (const_reference v)
void push_back (value_type &&v)
void pop_back () noexcept
iterator erase (const_iterator pos)
iterator erase (const_iterator from, const_iterator to)
void clear () noexcept
void reserve (size_type n)
void shrink_to_fit ()
void swap (InlinedVector &other)
Friends
template<typename H , typename TheT , size_t TheN, typename TheA >
H AbslHashValue (H h, const absl::InlinedVector< TheT, TheN, TheA > &a)
Detailed Description
template<typename T, size_t N, typename A = std::allocator<T>>
class absl::InlinedVector< T, N, A >
Definition at line 70 of file inlined_vector.h.
Member Typedef Documentation
allocator_type
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::allocator_type = A
Definition at line 107 of file inlined_vector.h.
const_iterator
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::const_iterator = inlined_vector_internal::ConstIterator<A>
Definition at line 116 of file inlined_vector.h.
const_pointer
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::const_pointer = inlined_vector_internal::ConstPointer<A>
Definition at line 110 of file inlined_vector.h.
const_reference
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::const_reference = inlined_vector_internal::ConstReference<A>
Definition at line 114 of file inlined_vector.h.
const_reverse_iterator
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::const_reverse_iterator
Initial value:
      inlined_vector_internal::ConstReverseIterator<A>
Definition at line 118 of file inlined_vector.h.
difference_type
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::difference_type = inlined_vector_internal::DifferenceType<A>
Definition at line 112 of file inlined_vector.h.
iterator
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::iterator = inlined_vector_internal::Iterator<A>
Definition at line 115 of file inlined_vector.h.
pointer
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::pointer = inlined_vector_internal::Pointer<A>
Definition at line 109 of file inlined_vector.h.
reference
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::reference = inlined_vector_internal::Reference<A>
Definition at line 113 of file inlined_vector.h.
reverse_iterator
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::reverse_iterator = inlined_vector_internal::ReverseIterator<A>
Definition at line 117 of file inlined_vector.h.
size_type
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::size_type = inlined_vector_internal::SizeType<A>
Definition at line 111 of file inlined_vector.h.
value_type
template<typename T , size_t N, typename A = std::allocator<T>> using absl::InlinedVector< T, N, A >::value_type = inlined_vector_internal::ValueType<A>
Definition at line 108 of file inlined_vector.h.
Constructor & Destructor Documentation
InlinedVector() [1/11]
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::InlinedVector () inline noexcept
Definition at line 126 of file inlined_vector.h.
: storage_() {}
InlinedVector() [2/11]
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::InlinedVector (const allocator_type & allocator) inline explicit noexcept
Definition at line 129 of file inlined_vector.h.
      : storage_(allocator) {}
InlinedVector() [3/11]
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::InlinedVector (size_type n, const allocator_type & allocator = allocator_type()) inline explicit
Definition at line 133 of file inlined_vector.h.
      : storage_(allocator) {
    storage_.Initialize(DefaultValueAdapter<A>(), n);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::Initialize(), and absl::n.
InlinedVector() [4/11]
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::InlinedVector (size_type n, const_reference v, const allocator_type & allocator = allocator_type()) inline
Definition at line 140 of file inlined_vector.h.
      : storage_(allocator) {
    storage_.Initialize(CopyValueAdapter<A>(std::addressof(v)), n);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::Initialize(), absl::n, and absl::v.
InlinedVector() [5/11]
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::InlinedVector (std::initializer_list< value_type > list, const allocator_type & allocator = allocator_type()) inline
Definition at line 147 of file inlined_vector.h.
      : InlinedVector(list.begin(), list.end(), allocator) {}
InlinedVector() [6/11]
template<typename T , size_t N, typename A = std::allocator<T>> template<typename ForwardIterator , EnableIfAtLeastForwardIterator< ForwardIterator > = 0> absl::InlinedVector< T, N, A >::InlinedVector (ForwardIterator first, ForwardIterator last, const allocator_type & allocator = allocator_type()) inline
Definition at line 159 of file inlined_vector.h.
      : storage_(allocator) {
    storage_.Initialize(IteratorValueAdapter<A, ForwardIterator>(first),
                        static_cast<size_t>(std::distance(first, last)));
  }
References first, and absl::inlined_vector_internal::Storage< T, N, A >::Initialize().
InlinedVector() [7/11]
template<typename T , size_t N, typename A = std::allocator<T>> template<typename InputIterator , DisableIfAtLeastForwardIterator< InputIterator > = 0> absl::InlinedVector< T, N, A >::InlinedVector (InputIterator first, InputIterator last, const allocator_type & allocator = allocator_type()) inline
Definition at line 170 of file inlined_vector.h.
      : storage_(allocator) {
    std::copy(first, last, std::back_inserter(*this));
  }
References first.
InlinedVector() [8/11]
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::InlinedVector (const InlinedVector< T, N, A > & other) inline
Definition at line 178 of file inlined_vector.h.
      : InlinedVector(other, other.storage_.GetAllocator()) {}
InlinedVector() [9/11]
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::InlinedVector (const InlinedVector< T, N, A > & other, const allocator_type & allocator) inline
Definition at line 183 of file inlined_vector.h.
      : storage_(allocator) {
    if (other.empty()) {
      // Empty; nothing to do.
    } else if (IsMemcpyOk<A>::value && !other.storage_.GetIsAllocated()) {
      // Memcpy-able and do not need allocation.
      storage_.MemcpyFrom(other.storage_);
    } else {
      storage_.InitFrom(other.storage_);
    }
  }
References absl::InlinedVector< T, N, A >::empty(), absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::InitFrom(), and absl::inlined_vector_internal::Storage< T, N, A >::MemcpyFrom().
InlinedVector() [10/11]
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::InlinedVector (InlinedVector< T, N, A > && other) inline noexcept
Definition at line 209 of file inlined_vector.h.
      : storage_(other.storage_.GetAllocator()) {
    if (IsMemcpyOk<A>::value) {
      storage_.MemcpyFrom(other.storage_);
      other.storage_.SetInlinedSize(0);
    } else if (other.storage_.GetIsAllocated()) {
      storage_.SetAllocation({other.storage_.GetAllocatedData(),
                              other.storage_.GetAllocatedCapacity()});
      storage_.SetAllocatedSize(other.storage_.GetSize());
      other.storage_.SetInlinedSize(0);
    } else {
      IteratorValueAdapter<A, MoveIterator<A>> other_values(
          MoveIterator<A>(other.storage_.GetInlinedData()));
      inlined_vector_internal::ConstructElements<A>(
          storage_.GetAllocator(), storage_.GetInlinedData(), other_values,
          other.storage_.GetSize());
      storage_.SetInlinedSize(other.storage_.GetSize());
    }
  }
References absl::inlined_vector_internal::ConstructElements(), absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator(), absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedData(), absl::inlined_vector_internal::Storage< T, N, A >::MemcpyFrom(), absl::inlined_vector_internal::Storage< T, N, A >::SetAllocatedSize(), absl::inlined_vector_internal::Storage< T, N, A >::SetAllocation(), and absl::inlined_vector_internal::Storage< T, N, A >::SetInlinedSize().
InlinedVector() [11/11]
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::InlinedVector (InlinedVector< T, N, A > && other, const allocator_type & allocator) inline noexcept
Definition at line 242 of file inlined_vector.h.
      : storage_(allocator) {
    if (IsMemcpyOk<A>::value) {
      storage_.MemcpyFrom(other.storage_);
      other.storage_.SetInlinedSize(0);
    } else if ((storage_.GetAllocator() == other.storage_.GetAllocator()) &&
               other.storage_.GetIsAllocated()) {
      storage_.SetAllocation({other.storage_.GetAllocatedData(),
                              other.storage_.GetAllocatedCapacity()});
      storage_.SetAllocatedSize(other.storage_.GetSize());
      other.storage_.SetInlinedSize(0);
    } else {
      storage_.Initialize(IteratorValueAdapter<A, MoveIterator<A>>(
                              MoveIterator<A>(other.data())),
                          other.size());
    }
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator(), absl::inlined_vector_internal::Storage< T, N, A >::Initialize(), absl::inlined_vector_internal::Storage< T, N, A >::MemcpyFrom(), absl::inlined_vector_internal::Storage< T, N, A >::SetAllocatedSize(), and absl::inlined_vector_internal::Storage< T, N, A >::SetAllocation().
~InlinedVector()
template<typename T , size_t N, typename A = std::allocator<T>> absl::InlinedVector< T, N, A >::~InlinedVector () inline
Definition at line 265 of file inlined_vector.h.
{}
Member Function Documentation
assign() [1/4]
template<typename T , size_t N, typename A = std::allocator<T>> template<typename ForwardIterator , EnableIfAtLeastForwardIterator< ForwardIterator > = 0> void absl::InlinedVector< T, N, A >::assign (ForwardIterator first, ForwardIterator last) inline
Definition at line 523 of file inlined_vector.h.
{
    storage_.Assign(IteratorValueAdapter<A, ForwardIterator>(first),
                    static_cast<size_t>(std::distance(first, last)));
  }
References absl::inlined_vector_internal::Storage< T, N, A >::Assign(), and first.
assign() [2/4]
template<typename T , size_t N, typename A = std::allocator<T>> template<typename InputIterator , DisableIfAtLeastForwardIterator< InputIterator > = 0> void absl::InlinedVector< T, N, A >::assign (InputIterator first, InputIterator last) inline
Definition at line 534 of file inlined_vector.h.
{
    size_type i = 0;
    for (; i < size() && first != last; ++i, static_cast<void>(++first)) {
      data()[i] = *first;
    }
    erase(data() + i, data() + size());
    std::copy(first, last, std::back_inserter(*this));
  }
References absl::InlinedVector< T, N, A >::data(), absl::InlinedVector< T, N, A >::erase(), first, absl::i, and absl::InlinedVector< T, N, A >::size().
assign() [3/4]
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::assign (size_type n, const_reference v) inline
Definition at line 507 of file inlined_vector.h.
{
    storage_.Assign(CopyValueAdapter<A>(std::addressof(v)), n);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::Assign(), absl::n, and absl::v.
Referenced by absl::InlinedVector< T, N, A >::assign(), absl::InlinedVector< T, N, A >::operator=(), and absl::InlinedVector< T, N, A >::operator=().
assign() [4/4]
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::assign (std::initializer_list< value_type > list) inline
Definition at line 513 of file inlined_vector.h.
{
    assign(list.begin(), list.end());
  }
References absl::InlinedVector< T, N, A >::assign().
at() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> reference absl::InlinedVector< T, N, A >::at (size_type i) inline
Definition at line 349 of file inlined_vector.h.
{
    if (ABSL_PREDICT_FALSE(i >= size())) {
      base_internal::ThrowStdOutOfRange(
          "`InlinedVector::at(size_type)` failed bounds check");
    }
    return data()[i];
  }
References ABSL_PREDICT_FALSE, absl::InlinedVector< T, N, A >::data(), absl::i, absl::InlinedVector< T, N, A >::size(), and absl::base_internal::ThrowStdOutOfRange().
at() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> const_reference absl::InlinedVector< T, N, A >::at (size_type i) const inline
Definition at line 362 of file inlined_vector.h.
{
    if (ABSL_PREDICT_FALSE(i >= size())) {
      base_internal::ThrowStdOutOfRange(
          "`InlinedVector::at(size_type) const` failed bounds check");
    }
    return data()[i];
  }
References ABSL_PREDICT_FALSE, absl::InlinedVector< T, N, A >::data(), absl::i, absl::InlinedVector< T, N, A >::size(), and absl::base_internal::ThrowStdOutOfRange().
back() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> reference absl::InlinedVector< T, N, A >::back () inline
Definition at line 388 of file inlined_vector.h.
                   {
    ABSL_HARDENING_ASSERT(!empty());
    return data()[size() - 1];
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::data(), absl::InlinedVector< T, N, A >::empty(), and absl::InlinedVector< T, N, A >::size().
back() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> const_reference absl::InlinedVector< T, N, A >::back () const inline
Definition at line 395 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(!empty());
    return data()[size() - 1];
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::data(), absl::InlinedVector< T, N, A >::empty(), and absl::InlinedVector< T, N, A >::size().
begin() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> const_iterator absl::InlinedVector< T, N, A >::begin () const inline noexcept
Definition at line 407 of file inlined_vector.h.
{ return data(); }
References absl::InlinedVector< T, N, A >::data().
begin() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> iterator absl::InlinedVector< T, N, A >::begin () inline noexcept
Definition at line 403 of file inlined_vector.h.
{ return data(); }
References absl::InlinedVector< T, N, A >::data().
Referenced by absl::InlinedVector< T, N, A >::cbegin(), absl::InlinedVector< T, N, A >::emplace(), absl::InlinedVector< T, N, A >::erase(), absl::InlinedVector< T, N, A >::erase(), absl::InlinedVector< T, N, A >::insert(), absl::InlinedVector< T, N, A >::insert(), absl::InlinedVector< T, N, A >::insert(), absl::InlinedVector< T, N, A >::rend(), absl::InlinedVector< T, N, A >::rend(), open_spiel::SpanTensorInfo::size(), and open_spiel::SpanTensorInfo::vector_shape().
capacity()
template<typename T , size_t N, typename A = std::allocator<T>> size_type absl::InlinedVector< T, N, A >::capacity () const inline noexcept
Definition at line 302 of file inlined_vector.h.
{
    return storage_.GetIsAllocated() ? storage_.GetAllocatedCapacity()
                                     : storage_.GetInlinedCapacity();
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedCapacity(), absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedCapacity(), and absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated().
cbegin()
template<typename T , size_t N, typename A = std::allocator<T>> const_iterator absl::InlinedVector< T, N, A >::cbegin () const inline noexcept
Definition at line 421 of file inlined_vector.h.
{ return begin(); }
References absl::InlinedVector< T, N, A >::begin().
Referenced by absl::InlinedVector< T, N, A >::insert().
cend()
template<typename T , size_t N, typename A = std::allocator<T>> const_iterator absl::InlinedVector< T, N, A >::cend () const inline noexcept
Definition at line 426 of file inlined_vector.h.
{ return end(); }
References absl::InlinedVector< T, N, A >::end().
clear()
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::clear () inline noexcept
Definition at line 746 of file inlined_vector.h.
{
    inlined_vector_internal::DestroyAdapter<A>::DestroyElements(
        storage_.GetAllocator(), data(), size());
    storage_.DeallocateIfAllocated();
    storage_.SetInlinedSize(0);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::DeallocateIfAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator(), absl::inlined_vector_internal::Storage< T, N, A >::SetInlinedSize(), and absl::InlinedVector< T, N, A >::size().
crbegin()
template<typename T , size_t N, typename A = std::allocator<T>> const_reverse_iterator absl::InlinedVector< T, N, A >::crbegin () const inline noexcept
Definition at line 453 of file inlined_vector.h.
{ return rbegin(); }
References absl::InlinedVector< T, N, A >::rbegin().
crend()
template<typename T , size_t N, typename A = std::allocator<T>> const_reverse_iterator absl::InlinedVector< T, N, A >::crend () const inline noexcept
Definition at line 459 of file inlined_vector.h.
{ return rend(); }
References absl::InlinedVector< T, N, A >::rend().
data() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> const_pointer absl::InlinedVector< T, N, A >::data () const inline noexcept
Definition at line 323 of file inlined_vector.h.
{
    return storage_.GetIsAllocated() ? storage_.GetAllocatedData()
                                     : storage_.GetInlinedData();
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedData(), absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedData(), and absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated().
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample().
data() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> pointer absl::InlinedVector< T, N, A >::data () inline noexcept
Definition at line 313 of file inlined_vector.h.
{
    return storage_.GetIsAllocated() ? storage_.GetAllocatedData()
                                     : storage_.GetInlinedData();
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetAllocatedData(), absl::inlined_vector_internal::Storage< T, N, A >::GetInlinedData(), and absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated().
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), absl::InlinedVector< T, N, A >::assign(), absl::InlinedVector< T, N, A >::at(), absl::InlinedVector< T, N, A >::at(), absl::InlinedVector< T, N, A >::back(), absl::InlinedVector< T, N, A >::back(), absl::InlinedVector< T, N, A >::begin(), absl::InlinedVector< T, N, A >::begin(), absl::InlinedVector< T, N, A >::end(), absl::InlinedVector< T, N, A >::end(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), absl::InlinedVector< T, N, A >::front(), absl::InlinedVector< T, N, A >::front(), absl::InlinedVector< T, N, A >::insert(), absl::InlinedVector< T, N, A >::operator=(), absl::InlinedVector< T, N, A >::operator[](), absl::InlinedVector< T, N, A >::operator[](), and open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample().
emplace()
template<typename T , size_t N, typename A = std::allocator<T>> template<typename... Args> iterator absl::InlinedVector< T, N, A >::emplace (const_iterator pos, Args &&... args) inline
Definition at line 659 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(pos >= begin());
    ABSL_HARDENING_ASSERT(pos <= end());
    value_type dealias(std::forward<Args>(args)...);
    // https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102329#c2
    // It appears that GCC thinks that since `pos` is a const pointer and may
    // point to uninitialized memory at this point, a warning should be
    // issued. But `pos` is actually only used to compute an array index to
    // write to.
#if !defined(__clang__) && defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif
    return storage_.Insert(pos,
                           IteratorValueAdapter<A, MoveIterator<A>>(
                               MoveIterator<A>(std::addressof(dealias))),
                           1);
#if !defined(__clang__) && defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::begin(), absl::InlinedVector< T, N, A >::end(), and absl::inlined_vector_internal::Storage< T, N, A >::Insert().
Referenced by absl::InlinedVector< T, N, A >::insert(), and absl::InlinedVector< T, N, A >::insert().
emplace_back()
template<typename T , size_t N, typename A = std::allocator<T>> template<typename... Args> reference absl::InlinedVector< T, N, A >::emplace_back (Args &&... args) inline
Definition at line 687 of file inlined_vector.h.
{
    return storage_.EmplaceBack(std::forward<Args>(args)...);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::EmplaceBack().
Referenced by absl::InlinedVector< T, N, A >::push_back(), and absl::InlinedVector< T, N, A >::push_back().
empty()
template<typename T , size_t N, typename A = std::allocator<T>> bool absl::InlinedVector< T, N, A >::empty () const inline noexcept
Definition at line 274 of file inlined_vector.h.
{ return !size(); }
References absl::InlinedVector< T, N, A >::size().
Referenced by absl::InlinedVector< T, N, A >::back(), absl::InlinedVector< T, N, A >::back(), absl::InlinedVector< T, N, A >::front(), absl::InlinedVector< T, N, A >::front(), absl::InlinedVector< T, N, A >::InlinedVector(), and absl::InlinedVector< T, N, A >::pop_back().
end() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> const_iterator absl::InlinedVector< T, N, A >::end () const inline noexcept
Definition at line 416 of file inlined_vector.h.
{ return data() + size(); }
References absl::InlinedVector< T, N, A >::data(), and absl::InlinedVector< T, N, A >::size().
end() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> iterator absl::InlinedVector< T, N, A >::end () inline noexcept
Definition at line 412 of file inlined_vector.h.
{ return data() + size(); }
References absl::InlinedVector< T, N, A >::data(), and absl::InlinedVector< T, N, A >::size().
Referenced by absl::InlinedVector< T, N, A >::cend(), absl::InlinedVector< T, N, A >::emplace(), absl::InlinedVector< T, N, A >::erase(), absl::InlinedVector< T, N, A >::erase(), absl::InlinedVector< T, N, A >::insert(), absl::InlinedVector< T, N, A >::insert(), absl::InlinedVector< T, N, A >::insert(), absl::InlinedVector< T, N, A >::rbegin(), absl::InlinedVector< T, N, A >::rbegin(), open_spiel::SpanTensorInfo::size(), and open_spiel::SpanTensorInfo::vector_shape().
erase() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> iterator absl::InlinedVector< T, N, A >::erase (const_iterator from, const_iterator to) inline
Definition at line 730 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(from >= begin());
    ABSL_HARDENING_ASSERT(from <= to);
    ABSL_HARDENING_ASSERT(to <= end());
    if (ABSL_PREDICT_TRUE(from != to)) {
      return storage_.Erase(from, to);
    } else {
      return const_cast<iterator>(from);
    }
  }
References ABSL_HARDENING_ASSERT, ABSL_PREDICT_TRUE, absl::InlinedVector< T, N, A >::begin(), absl::InlinedVector< T, N, A >::end(), absl::inlined_vector_internal::Storage< T, N, A >::Erase(), from, and to.
erase() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> iterator absl::InlinedVector< T, N, A >::erase (const_iterator pos) inline
Definition at line 718 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(pos >= begin());
    ABSL_HARDENING_ASSERT(pos < end());
    return storage_.Erase(pos, pos + 1);
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::begin(), absl::InlinedVector< T, N, A >::end(), and absl::inlined_vector_internal::Storage< T, N, A >::Erase().
Referenced by absl::InlinedVector< T, N, A >::assign(), and absl::Status::ErasePayload().
front() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> reference absl::InlinedVector< T, N, A >::front () inline
Definition at line 373 of file inlined_vector.h.
                    {
    ABSL_HARDENING_ASSERT(!empty());
    return data()[0];
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::data(), and absl::InlinedVector< T, N, A >::empty().
front() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> const_reference absl::InlinedVector< T, N, A >::front () const inline
Definition at line 380 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(!empty());
    return data()[0];
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::data(), and absl::InlinedVector< T, N, A >::empty().
get_allocator()
template<typename T , size_t N, typename A = std::allocator<T>> allocator_type absl::InlinedVector< T, N, A >::get_allocator () const inline
Definition at line 464 of file inlined_vector.h.
{ return storage_.GetAllocator(); }
References absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator().
insert() [1/6]
template<typename T , size_t N, typename A = std::allocator<T>> iterator absl::InlinedVector< T, N, A >::insert (const_iterator pos, const_reference v) inline
Definition at line 569 of file inlined_vector.h.
{
    return emplace(pos, v);
  }
References absl::InlinedVector< T, N, A >::emplace(), and absl::v.
Referenced by absl::InlinedVector< T, N, A >::insert(), absl::InlinedVector< T, N, A >::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [2/6]
template<typename T , size_t N, typename A = std::allocator<T>> template<typename ForwardIterator , EnableIfAtLeastForwardIterator< ForwardIterator > = 0> iterator absl::InlinedVector< T, N, A >::insert (const_iterator pos, ForwardIterator first, ForwardIterator last) inline
Definition at line 621 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(pos >= begin());
    ABSL_HARDENING_ASSERT(pos <= end());
    if (ABSL_PREDICT_TRUE(first != last)) {
      return storage_.Insert(
          pos, IteratorValueAdapter<A, ForwardIterator>(first),
          static_cast<size_type>(std::distance(first, last)));
    } else {
      return const_cast<iterator>(pos);
    }
  }
References ABSL_HARDENING_ASSERT, ABSL_PREDICT_TRUE, absl::InlinedVector< T, N, A >::begin(), absl::InlinedVector< T, N, A >::end(), first, and absl::inlined_vector_internal::Storage< T, N, A >::Insert().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [3/6]
template<typename T , size_t N, typename A = std::allocator<T>> template<typename InputIterator , DisableIfAtLeastForwardIterator< InputIterator > = 0> iterator absl::InlinedVector< T, N, A >::insert (const_iterator pos, InputIterator first, InputIterator last) inline
Definition at line 642 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(pos >= begin());
    ABSL_HARDENING_ASSERT(pos <= end());
    size_type index = static_cast<size_type>(std::distance(cbegin(), pos));
    for (size_type i = index; first != last; ++i, static_cast<void>(++first)) {
      insert(data() + i, *first);
    }
    return iterator(data() + index);
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::begin(), absl::InlinedVector< T, N, A >::cbegin(), absl::InlinedVector< T, N, A >::data(), absl::InlinedVector< T, N, A >::end(), first, absl::i, and absl::InlinedVector< T, N, A >::insert().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [4/6]
template<typename T , size_t N, typename A = std::allocator<T>> iterator absl::InlinedVector< T, N, A >::insert (const_iterator pos, size_type n, const_reference v) inline
Definition at line 582 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(pos >= begin());
    ABSL_HARDENING_ASSERT(pos <= end());
    if (ABSL_PREDICT_TRUE(n != 0)) {
      value_type dealias = v;
      // https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102329#c2
      // It appears that GCC thinks that since `pos` is a const pointer and may
      // point to uninitialized memory at this point, a warning should be
      // issued. But `pos` is actually only used to compute an array index to
      // write to.
#if !defined(__clang__) && defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif
      return storage_.Insert(pos, CopyValueAdapter<A>(std::addressof(dealias)),
                             n);
#if !defined(__clang__) && defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
    } else {
      return const_cast<iterator>(pos);
    }
  }
References ABSL_HARDENING_ASSERT, ABSL_PREDICT_TRUE, absl::InlinedVector< T, N, A >::begin(), absl::InlinedVector< T, N, A >::end(), absl::inlined_vector_internal::Storage< T, N, A >::Insert(), absl::n, and absl::v.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [5/6]
template<typename T , size_t N, typename A = std::allocator<T>> iterator absl::InlinedVector< T, N, A >::insert (const_iterator pos, std::initializer_list< value_type > list) inline
Definition at line 610 of file inlined_vector.h.
{
    return insert(pos, list.begin(), list.end());
  }
References absl::InlinedVector< T, N, A >::insert().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [6/6]
template<typename T , size_t N, typename A = std::allocator<T>> iterator absl::InlinedVector< T, N, A >::insert (const_iterator pos, value_type && v) inline
Definition at line 575 of file inlined_vector.h.
{
    return emplace(pos, std::move(v));
  }
References absl::InlinedVector< T, N, A >::emplace(), and absl::v.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
max_size()
template<typename T , size_t N, typename A = std::allocator<T>> size_type absl::InlinedVector< T, N, A >::max_size () const inline noexcept
Definition at line 284 of file inlined_vector.h.
{
    // One bit of the size storage is used to indicate whether the inlined
    // vector contains allocated memory. As a result, the maximum size that the
    // inlined vector can express is the minimum of the limit of how many
    // objects we can allocate and std::numeric_limits<size_type>::max() / 2.
    return (std::min)(AllocatorTraits<A>::max_size(storage_.GetAllocator()),
                      (std::numeric_limits<size_type>::max)() / 2);
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator().
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), absl::InlinedVector< T, N, A >::resize(), absl::InlinedVector< T, N, A >::resize(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
operator=() [1/3]
template<typename T , size_t N, typename A = std::allocator<T>> InlinedVector & absl::InlinedVector< T, N, A >::operator= (const InlinedVector< T, N, A > & other) inline
Definition at line 482 of file inlined_vector.h.
{
    if (ABSL_PREDICT_TRUE(this != std::addressof(other))) {
      const_pointer other_data = other.data();
      assign(other_data, other_data + other.size());
    }
    return *this;
  }
References ABSL_PREDICT_TRUE, absl::InlinedVector< T, N, A >::assign(), absl::InlinedVector< T, N, A >::data(), and absl::InlinedVector< T, N, A >::size().
operator=() [2/3]
template<typename T , size_t N, typename A = std::allocator<T>> InlinedVector & absl::InlinedVector< T, N, A >::operator= (InlinedVector< T, N, A > && other) inline
Definition at line 496 of file inlined_vector.h.
{
    if (ABSL_PREDICT_TRUE(this != std::addressof(other))) {
      MoveAssignment(MoveAssignmentPolicy{}, std::move(other));
    }
    return *this;
  }
References ABSL_PREDICT_TRUE.
operator=() [3/3]
template<typename T , size_t N, typename A = std::allocator<T>> InlinedVector & absl::InlinedVector< T, N, A >::operator= (std::initializer_list< value_type > list) inline
Definition at line 474 of file inlined_vector.h.
{
    assign(list.begin(), list.end());
    return *this;
  }
References absl::InlinedVector< T, N, A >::assign().
operator[]() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> reference absl::InlinedVector< T, N, A >::operator[] (size_type i) inline
Definition at line 331 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(i < size());
    return data()[i];
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::data(), absl::i, and absl::InlinedVector< T, N, A >::size().
operator[]() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> const_reference absl::InlinedVector< T, N, A >::operator[] (size_type i) const inline
Definition at line 338 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(i < size());
    return data()[i];
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::data(), absl::i, and absl::InlinedVector< T, N, A >::size().
pop_back()
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::pop_back () inline noexcept
Definition at line 705 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(!empty());
    AllocatorTraits<A>::destroy(storage_.GetAllocator(), data() + (size() - 1));
    storage_.SubtractSize(1);
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::empty(), absl::inlined_vector_internal::Storage< T, N, A >::GetAllocator(), absl::InlinedVector< T, N, A >::size(), and absl::inlined_vector_internal::Storage< T, N, A >::SubtractSize().
push_back() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::push_back (const_reference v) inline
Definition at line 694 of file inlined_vector.h.
{ static_cast<void>(emplace_back(v)); }
References absl::InlinedVector< T, N, A >::emplace_back(), and absl::v.
push_back() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::push_back (value_type && v) inline
Definition at line 698 of file inlined_vector.h.
{
    static_cast<void>(emplace_back(std::move(v)));
  }
References absl::InlinedVector< T, N, A >::emplace_back(), and absl::v.
rbegin() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> const_reverse_iterator absl::InlinedVector< T, N, A >::rbegin () const inline noexcept
Definition at line 435 of file inlined_vector.h.
{
    return const_reverse_iterator(end());
  }
References absl::InlinedVector< T, N, A >::end().
rbegin() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> reverse_iterator absl::InlinedVector< T, N, A >::rbegin () inline noexcept
Definition at line 431 of file inlined_vector.h.
{ return reverse_iterator(end()); }
References absl::InlinedVector< T, N, A >::end().
Referenced by absl::InlinedVector< T, N, A >::crbegin().
rend() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> const_reverse_iterator absl::InlinedVector< T, N, A >::rend () const inline noexcept
Definition at line 446 of file inlined_vector.h.
{
    return const_reverse_iterator(begin());
  }
References absl::InlinedVector< T, N, A >::begin().
rend() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> reverse_iterator absl::InlinedVector< T, N, A >::rend () inline noexcept
Definition at line 442 of file inlined_vector.h.
{ return reverse_iterator(begin()); }
References absl::InlinedVector< T, N, A >::begin().
Referenced by absl::InlinedVector< T, N, A >::crend().
reserve()
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::reserve (size_type n) inline
Definition at line 757 of file inlined_vector.h.
{ storage_.Reserve(n); }
References absl::n, and absl::inlined_vector_internal::Storage< T, N, A >::Reserve().
resize() [1/2]
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::resize (size_type n) inline
Definition at line 550 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(n <= max_size());
    storage_.Resize(DefaultValueAdapter<A>(), n);
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::max_size(), absl::n, and absl::inlined_vector_internal::Storage< T, N, A >::Resize().
resize() [2/2]
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::resize (size_type n, const_reference v) inline
Definition at line 560 of file inlined_vector.h.
{
    ABSL_HARDENING_ASSERT(n <= max_size());
    storage_.Resize(CopyValueAdapter<A>(std::addressof(v)), n);
  }
References ABSL_HARDENING_ASSERT, absl::InlinedVector< T, N, A >::max_size(), absl::n, absl::inlined_vector_internal::Storage< T, N, A >::Resize(), and absl::v.
shrink_to_fit()
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::shrink_to_fit () inline
Definition at line 767 of file inlined_vector.h.
                       {
    if (storage_.GetIsAllocated()) {
      storage_.ShrinkToFit();
    }
  }
References absl::inlined_vector_internal::Storage< T, N, A >::GetIsAllocated(), and absl::inlined_vector_internal::Storage< T, N, A >::ShrinkToFit().
size()
template<typename T , size_t N, typename A = std::allocator<T>> size_type absl::InlinedVector< T, N, A >::size () const inline noexcept
Definition at line 279 of file inlined_vector.h.
{ return storage_.GetSize(); }
References absl::inlined_vector_internal::Storage< T, N, A >::GetSize().
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), absl::InlinedVector< T, N, A >::assign(), absl::InlinedVector< T, N, A >::at(), absl::InlinedVector< T, N, A >::at(), open_spiel::SpanTensor::at(), open_spiel::SpanTensor::at(), open_spiel::SpanTensor::at(), open_spiel::SpanTensor::at(), open_spiel::SpanTensor::at(), absl::InlinedVector< T, N, A >::back(), absl::InlinedVector< T, N, A >::back(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), absl::InlinedVector< T, N, A >::clear(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), absl::InlinedVector< T, N, A >::empty(), absl::InlinedVector< T, N, A >::end(), absl::InlinedVector< T, N, A >::end(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), absl::InlinedVector< T, N, A >::operator=(), absl::InlinedVector< T, N, A >::operator[](), absl::InlinedVector< T, N, A >::operator[](), absl::InlinedVector< T, N, A >::pop_back(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
swap()
template<typename T , size_t N, typename A = std::allocator<T>> void absl::InlinedVector< T, N, A >::swap (InlinedVector< T, N, A > & other) inline
Definition at line 776 of file inlined_vector.h.
{
    if (ABSL_PREDICT_TRUE(this != std::addressof(other))) {
      storage_.Swap(std::addressof(other.storage_));
    }
  }
References ABSL_PREDICT_TRUE, and absl::inlined_vector_internal::Storage< T, N, A >::Swap().
Friends And Related Symbol Documentation
AbslHashValue
template<typename T , size_t N, typename A = std::allocator<T>> template<typename H , typename TheT , size_t TheN, typename TheA > H AbslHashValue (H h, const absl::InlinedVector< TheT, TheN, TheA > & a) friend
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/inlined_vector.h