open spiel: open_spiel::go::GoBoard Class Reference
open_spiel::go::GoBoard Class Reference
#include <go_board.h>
Classes
class GroupIter
Public Member Functions
GoBoard (int board_size)
void Clear ()
int board_size () const
int pass_action () const
Action VirtualActionToAction (int virtual_action) const
int ActionToVirtualAction (Action action) const
GoColor PointColor (VirtualPoint p) const
bool IsEmpty (VirtualPoint p) const
bool IsInBoardArea (VirtualPoint p) const
bool IsLegalMove (VirtualPoint p, GoColor c) const
bool PlayMove (VirtualPoint p, GoColor c)
VirtualPoint LastKoPoint () const
int PseudoLiberty (VirtualPoint p) const
bool InAtari (VirtualPoint p) const
VirtualPoint SingleLiberty (VirtualPoint p) const
int RealLiberty (VirtualPoint p) const
uint64_t HashValue () const
VirtualPoint ChainHead (VirtualPoint p) const
int ChainSize (VirtualPoint p) const
std::string ToString ()
GroupIter LibIter (VirtualPoint p) const
GroupIter OppIter (VirtualPoint p) const
Detailed Description
Definition at line 109 of file go_board.h.
Constructor & Destructor Documentation
GoBoard()
open_spiel::go::GoBoard::GoBoard (int board_size) explicit
Definition at line 250 of file go_board.cc.
    : board_size_(board_size), pass_action_(board_size * board_size) {
  if (board_size_ > 19) {
    SpielFatalError(
        absl::StrCat("The current Go implementation supports board size up to "
                     "19. Provided: ",
                     board_size));
  }
  Clear();
}
References board_size(), Clear(), open_spiel::SpielFatalError(), and absl::StrCat().
Member Function Documentation
ActionToVirtualAction()
int open_spiel::go::GoBoard::ActionToVirtualAction (Action action) const inline
Definition at line 121 of file go_board.h.
{
    return go::ActionToVirtualAction(action, board_size_);
  }
References action, and open_spiel::go::ActionToVirtualAction().
Referenced by open_spiel::go::GoState::ActionToString(), and open_spiel::go::GoState::DoApplyAction().
board_size()
int open_spiel::go::GoBoard::board_size () const inline
Definition at line 115 of file go_board.h.
{ return board_size_; }
Referenced by GoBoard(), IsInBoardArea(), open_spiel::cursor_go::CursorGoState::LegalActions(), open_spiel::go::GoState::LegalActions(), open_spiel::cursor_go::CursorGoState::ObservationTensor(), open_spiel::go::GoState::ObservationTensor(), open_spiel::go::operator<<(), and open_spiel::go::TrompTaylorScore().
ChainHead()
VirtualPoint open_spiel::go::GoBoard::ChainHead (VirtualPoint p) const inline
Definition at line 169 of file go_board.h.
{
    return board_[p].chain_head;
  }
Referenced by open_spiel::go::GoBoard::GroupIter::GroupIter(), and SingleLiberty().
ChainSize()
int open_spiel::go::GoBoard::ChainSize (VirtualPoint p) const inline
Definition at line 174 of file go_board.h.
{ return chain(p).num_stones; }
Clear()
void open_spiel::go::GoBoard::Clear ()
Definition at line 261 of file go_board.cc.
                    {
  zobrist_hash_ = 0;
  for (int i = 0; i < board_.size(); ++i) {
    Vertex& v = board_[i];
    v.color = GoColor::kGuard;
    v.chain_head = static_cast<VirtualPoint>(i);
    v.chain_next = static_cast<VirtualPoint>(i);
    chains_[i].reset_border();
  }
  for (VirtualPoint p : BoardPoints(board_size_)) {
    board_[p].color = GoColor::kEmpty;
    chains_[p].reset();
  }
  for (VirtualPoint p : BoardPoints(board_size_)) {
    Neighbours(p, [this, p](VirtualPoint n) {
      if (IsEmpty(n)) chain(p).add_liberty(n);
    });
  }
  for (int i = 0; i < last_captures_.size(); ++i) {
    last_captures_[i] = kInvalidPoint;
  }
  last_ko_point_ = kInvalidPoint;
}
References open_spiel::go::BoardPoints(), i, IsEmpty(), open_spiel::go::kEmpty, open_spiel::go::kGuard, open_spiel::go::kInvalidPoint, and n.
Referenced by GoBoard().
HashValue()
uint64_t open_spiel::go::GoBoard::HashValue () const inline
Definition at line 165 of file go_board.h.
{ return zobrist_hash_; }
Referenced by open_spiel::cursor_go::CursorGoState::DoApplyAction(), and open_spiel::go::GoState::DoApplyAction().
InAtari()
bool open_spiel::go::GoBoard::InAtari (VirtualPoint p) const inline
Definition at line 149 of file go_board.h.
{ return chain(p).in_atari(); }
IsEmpty()
bool open_spiel::go::GoBoard::IsEmpty (VirtualPoint p) const inline
Definition at line 127 of file go_board.h.
{
    return PointColor(p) == GoColor::kEmpty;
  }
References open_spiel::go::kEmpty, and PointColor().
Referenced by Clear(), IsLegalMove(), open_spiel::go::operator<<(), and SingleLiberty().
IsInBoardArea()
bool open_spiel::go::GoBoard::IsInBoardArea (VirtualPoint p) const
Definition at line 466 of file go_board.cc.
{
  auto rc = VirtualPointTo2DPoint(p);
  return rc.first >= 0 && rc.first < board_size() && rc.second >= 0 &&
         rc.second < board_size();
}
References board_size(), and open_spiel::go::VirtualPointTo2DPoint().
Referenced by IsLegalMove(), and SingleLiberty().
IsLegalMove()
bool open_spiel::go::GoBoard::IsLegalMove (VirtualPoint p, GoColor c) const
Definition at line 472 of file go_board.cc.
{
  if (p == kVirtualPass) return true;
  if (!IsInBoardArea(p)) return false;
  if (!IsEmpty(p) || p == LastKoPoint()) return false;
  if (chain(p).num_pseudo_liberties > 0) return true;
  // For all checks below, the newly placed stone is completely surrounded by
  // enemy and friendly stones.
  // Allow to play if the placed stones connects to a group that still has at
  // least one other liberty after connecting.
  bool has_liberty = false;
  Neighbours(p, [this, c, &has_liberty](VirtualPoint n) {
    has_liberty |= (PointColor(n) == c && !chain(n).in_atari());
  });
  if (has_liberty) return true;
  // Allow to play if the placed stone will kill at least one group.
  bool kills_group = false;
  Neighbours(p, [this, c, &kills_group](VirtualPoint n) {
    kills_group |= (PointColor(n) == OppColor(c) && chain(n).in_atari());
  });
  if (kills_group) return true;
  return false;
}
References IsEmpty(), IsInBoardArea(), open_spiel::go::kVirtualPass, LastKoPoint(), n, open_spiel::go::OppColor(), and PointColor().
Referenced by open_spiel::cursor_go::CursorGoState::LegalActions(), and open_spiel::go::GoState::LegalActions().
LastKoPoint()
VirtualPoint open_spiel::go::GoBoard::LastKoPoint () const inline
Definition at line 138 of file go_board.h.
{ return last_ko_point_; }
Referenced by IsLegalMove().
LibIter()
GroupIter open_spiel::go::GoBoard::LibIter (VirtualPoint p) const inline
Definition at line 210 of file go_board.h.
{
    return GroupIter(this, p, GoColor::kEmpty);
  }
References open_spiel::go::kEmpty.
Referenced by RealLiberty().
OppIter()
GroupIter open_spiel::go::GoBoard::OppIter (VirtualPoint p) const inline
Definition at line 213 of file go_board.h.
{
    return GroupIter(this, p, OppColor(PointColor(p)));
  }
References open_spiel::go::OppColor(), and PointColor().
pass_action()
int open_spiel::go::GoBoard::pass_action () const inline
Definition at line 117 of file go_board.h.
{ return pass_action_; }
Referenced by open_spiel::go::GoState::DoApplyAction(), open_spiel::go::GoState::IsTerminal(), and open_spiel::go::GoState::LegalActions().
PlayMove()
bool open_spiel::go::GoBoard::PlayMove (VirtualPoint p, GoColor c)
Definition at line 290 of file go_board.cc.
{
  if (p == kVirtualPass) {
    last_ko_point_ = kInvalidPoint;
    return true;
  }
  if (board_[p].color != GoColor::kEmpty) {
    SpielFatalError(absl::StrCat("Trying to play the move ", GoColorToString(c),
                                 ": ", VirtualPointToString(p), " (", p,
                                 ") but the cell is already filled with ",
                                 GoColorToString(board_[p].color)));
  }
  SPIEL_CHECK_EQ(GoColor::kEmpty, board_[p].color);
  // Preparation for ko checking.
  bool played_in_enemy_eye = true;
  Neighbours(p, [this, c, &played_in_enemy_eye](VirtualPoint n) {
    GoColor s = PointColor(n);
    if (s == c || s == GoColor::kEmpty) {
      played_in_enemy_eye = false;
    }
  });
  JoinChainsAround(p, c);
  SetStone(p, c);
  RemoveLibertyFromNeighbouringChains(p);
  int stones_captured = CaptureDeadChains(p, c);
  if (played_in_enemy_eye && stones_captured == 1) {
    last_ko_point_ = last_captures_[0];
  } else {
    last_ko_point_ = kInvalidPoint;
  }
  SPIEL_CHECK_GT(chain(p).num_pseudo_liberties, 0);
  return true;
}
References open_spiel::go::GoColorToString(), open_spiel::go::kEmpty, open_spiel::go::kInvalidPoint, open_spiel::go::kVirtualPass, n, PointColor(), SPIEL_CHECK_EQ, SPIEL_CHECK_GT, open_spiel::SpielFatalError(), absl::StrCat(), and open_spiel::go::VirtualPointToString().
Referenced by open_spiel::go::CreateBoard(), open_spiel::cursor_go::CursorGoState::DoApplyAction(), and open_spiel::go::GoState::DoApplyAction().
PointColor()
GoColor open_spiel::go::GoBoard::PointColor (VirtualPoint p) const inline
Definition at line 125 of file go_board.h.
{ return board_[p].color; }
Referenced by IsEmpty(), IsLegalMove(), open_spiel::go::NumSurroundedPoints(), open_spiel::cursor_go::CursorGoState::ObservationTensor(), open_spiel::go::GoState::ObservationTensor(), open_spiel::go::operator<<(), OppIter(), PlayMove(), and open_spiel::go::TrompTaylorScore().
PseudoLiberty()
int open_spiel::go::GoBoard::PseudoLiberty (VirtualPoint p) const inline
Definition at line 143 of file go_board.h.
{
    return chain(p).num_pseudo_liberties == 0
               ? 0
               : (chain(p).in_atari() ? 1 : chain(p).num_pseudo_liberties);
  }
RealLiberty()
int open_spiel::go::GoBoard::RealLiberty (VirtualPoint p) const inline
Definition at line 157 of file go_board.h.
{
    int num_lib = 0;
    for (auto it = LibIter(p); it; ++it) {
      ++num_lib;
    }
    return num_lib;
  }
References LibIter().
SingleLiberty()
VirtualPoint open_spiel::go::GoBoard::SingleLiberty (VirtualPoint p) const
Definition at line 329 of file go_board.cc.
{
  VirtualPoint head = ChainHead(p);
  VirtualPoint liberty = chain(p).single_liberty();
  // Check it is really a liberty.
  SPIEL_CHECK_TRUE(IsInBoardArea(liberty));
  SPIEL_CHECK_TRUE(IsEmpty(liberty));
  // Make sure the liberty actually borders the group.
  for (auto n = Neighbours4(liberty); n; ++n) {
    if (ChainHead(*n) == head) return liberty;
  }
  SpielFatalError(
      absl::StrCat("liberty", liberty, " does not actually border group ", p));
}
References ChainHead(), IsEmpty(), IsInBoardArea(), n, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), and absl::StrCat().
ToString()
std::string open_spiel::go::GoBoard::ToString ()
Definition at line 551 of file go_board.cc.
{
  std::ostringstream stream;
  stream << *this;
  return stream.str();
}
VirtualActionToAction()
Action open_spiel::go::GoBoard::VirtualActionToAction (int virtual_action) const inline
Definition at line 118 of file go_board.h.
{
    return go::VirtualActionToAction(virtual_action, board_size_);
  }
References open_spiel::go::VirtualActionToAction().
Referenced by open_spiel::go::GoState::LegalActions().
The documentation for this class was generated from the following files:
open_spiel/games/go/go_board.h
open_spiel/games/go/go_board.cc