open spiel: absl::crc_internal::CRC Class Reference
absl::crc_internal::CRC Class Reference abstract
#include <crc.h>
Public Member Functions
virtual ~CRC ()
virtual void Empty (uint32_t *crc) const =0
virtual void Extend (uint32_t *crc, const void *bytes, size_t length) const =0
virtual void ExtendByZeroes (uint32_t *crc, size_t length) const =0
virtual void UnextendByZeroes (uint32_t *crc, size_t length) const =0
virtual void Concat (uint32_t *px, uint32_t y, size_t ylen)
virtual void Scramble (uint32_t *crc) const =0
virtual void Unscramble (uint32_t *crc) const =0
Static Public Member Functions
static CRC * Crc32c ()
Protected Member Functions
CRC ()
Detailed Description
Definition at line 39 of file crc.h.
Constructor & Destructor Documentation
~CRC()
absl::crc_internal::CRC::~CRC () virtual
Definition at line 429 of file crc.cc.
{}
CRC()
absl::crc_internal::CRC::CRC () protected
Definition at line 430 of file crc.cc.
{}
Member Function Documentation
Concat()
void absl::crc_internal::CRC::Concat (uint32_t * px, uint32_t y, size_t ylen) virtual
Definition at line 439 of file crc.cc.
{
  // https://en.wikipedia.org/wiki/Mathematics_of_cyclic_redundancy_checks
  // The CRC of a message M is the remainder of polynomial divison modulo G,
  // where the coefficient arithmetic is performed modulo 2 (so +/- are XOR):
  //   R(x) = M(x) x**n (mod G)
  // (n is the degree of G)
  // In practice, we use an initial value A and a bitmask B to get
  //   R = (A ^ B)x**|M| ^ Mx**n ^ B (mod G)
  // If M is the concatenation of two strings S and T, and Z is the string of
  // len(T) 0s, then the remainder CRC(ST) can be expressed as:
  //   R = (A ^ B)x**|ST| ^ STx**n ^ B
  //     = (A ^ B)x**|SZ| ^ SZx**n ^ B ^ Tx**n
  //     = CRC(SZ) ^ Tx**n
  // CRC(Z) = (A ^ B)x**|T| ^ B
  // CRC(T) = (A ^ B)x**|T| ^ Tx**n ^ B
  // So R = CRC(SZ) ^ CRC(Z) ^ CRC(T)
  //
  // And further, since CRC(SZ) = Extend(CRC(S), Z),
  //  CRC(SZ) ^ CRC(Z) = Extend(CRC(S) ^ CRC(''), Z).
  uint32_t z;
  uint32_t t;
  Empty(&z);
  t = *px ^ z;
  ExtendByZeroes(&t, ylen);
  *px = t ^ y;
}
References Empty(), ExtendByZeroes(), and y.
Crc32c()
CRC * absl::crc_internal::CRC::Crc32c () static
Definition at line 433 of file crc.cc.
                 {
  static CRC* singleton = CRCImpl::NewInternal();
  return singleton;
}
References absl::crc_internal::CRCImpl::NewInternal().
Referenced by absl::ABSL_NAMESPACE_BEGIN::CrcEngine().
Empty()
virtual void absl::crc_internal::CRC::Empty (uint32_t * crc) const pure virtual
Implemented in absl::crc_internal::CRCImpl.
Referenced by Concat().
Extend()
virtual void absl::crc_internal::CRC::Extend (uint32_t * crc, const void * bytes, size_t length) const pure virtual
Implemented in absl::crc_internal::CRC32.
ExtendByZeroes()
virtual void absl::crc_internal::CRC::ExtendByZeroes (uint32_t * crc, size_t length) const pure virtual
Implemented in absl::crc_internal::CRC32.
Referenced by Concat().
Scramble()
virtual void absl::crc_internal::CRC::Scramble (uint32_t * crc) const pure virtual
Implemented in absl::crc_internal::CRC32.
UnextendByZeroes()
virtual void absl::crc_internal::CRC::UnextendByZeroes (uint32_t * crc, size_t length) const pure virtual
Implemented in absl::crc_internal::CRC32.
Unscramble()
virtual void absl::crc_internal::CRC::Unscramble (uint32_t * crc) const pure virtual
Implemented in absl::crc_internal::CRC32.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/crc/internal/crc.h
open_spiel/abseil-cpp/absl/crc/internal/crc.cc