open spiel: open_spiel::nine_mens_morris::NineMensMorrisState Class Reference
open_spiel::nine_mens_morris::NineMensMorrisState Class Reference
#include <nine_mens_morris.h>
Public Member Functions
NineMensMorrisState (std::shared_ptr< const Game > game)
NineMensMorrisState (const NineMensMorrisState &)=default
NineMensMorrisState & operator= (const NineMensMorrisState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
CellState BoardAt (int cell) const
Player outcome () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes
std::array< CellState, kNumPoints > board_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 52 of file nine_mens_morris.h.
Constructor & Destructor Documentation
NineMensMorrisState() [1/2]
open_spiel::nine_mens_morris::NineMensMorrisState::NineMensMorrisState (std::shared_ptr< const Game > game)
Definition at line 329 of file nine_mens_morris.cc.
    : State(game) {
  std::fill(begin(board_), end(board_), CellState::kEmpty);
  GetCurrentLegalActions();
}
References begin, board_, end, and open_spiel::nine_mens_morris::kEmpty.
Referenced by Clone().
NineMensMorrisState() [2/2]
open_spiel::nine_mens_morris::NineMensMorrisState::NineMensMorrisState (const NineMensMorrisState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::nine_mens_morris::NineMensMorrisState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 324 of file nine_mens_morris.cc.
{
  return game_->ActionToString(player, action_id);
}
References open_spiel::State::game_, and player.
BoardAt()
CellState open_spiel::nine_mens_morris::NineMensMorrisState::BoardAt (int cell) const inline
Definition at line 74 of file nine_mens_morris.h.
{ return board_[cell]; }
References board_.
Clone()
std::unique_ptr< State > open_spiel::nine_mens_morris::NineMensMorrisState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 444 of file nine_mens_morris.cc.
{
  return std::unique_ptr<State>(new NineMensMorrisState(*this));
}
References NineMensMorrisState().
CurrentPlayer()
Player open_spiel::nine_mens_morris::NineMensMorrisState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 59 of file nine_mens_morris.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::nine_mens_morris::NineMensMorrisState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 270 of file nine_mens_morris.cc.
{
  cur_legal_actions_.clear();
  if (move < kNumPoints) {
    if (capture_) {
      // Capture move: choosing which piece to remove.
      SPIEL_CHECK_TRUE(board_[move] != CellState::kEmpty);
      Player opp = StateToPlayer(board_[move]);
      SPIEL_CHECK_TRUE(opp == 1 - current_player_);
      num_men_[opp]--;
      board_[move] = CellState::kEmpty;
      capture_ = false;
      current_player_ = 1 - current_player_;
      num_turns_++;
    } else {
      // Regular move in phase 1 (deployment)
      SPIEL_CHECK_TRUE(board_[move] == CellState::kEmpty);
      board_[move] = PlayerToState(current_player_);
      SPIEL_CHECK_GT(men_to_deploy_[current_player_], 0);
      men_to_deploy_[current_player_]--;
      bool mill = CheckInMill(move);
      if (mill) {
        capture_ = true;
      } else {
        current_player_ = 1 - current_player_;
        num_turns_++;
      }
    }
  } else {
    // Movement move (phase 2 or 3).
    int from_pos = -1, to_pos = -1;
    FromMoveAction(move, &from_pos, &to_pos);
    SPIEL_CHECK_TRUE(StateToPlayer(board_[from_pos]) == current_player_);
    SPIEL_CHECK_TRUE(board_[to_pos] == CellState::kEmpty);
    board_[to_pos] = board_[from_pos];
    board_[from_pos] = CellState::kEmpty;
    bool mill = CheckInMill(to_pos);
    if (mill) {
      capture_ = true;
    } else {
      current_player_ = 1 - current_player_;
      num_turns_++;
    }
  }
  if (cur_legal_actions_.empty()) {
    GetCurrentLegalActions();
  }
}
References board_, open_spiel::nine_mens_morris::FromMoveAction(), open_spiel::nine_mens_morris::kEmpty, open_spiel::nine_mens_morris::kNumPoints, open_spiel::nine_mens_morris::PlayerToState(), SPIEL_CHECK_GT, SPIEL_CHECK_TRUE, and open_spiel::nine_mens_morris::StateToPlayer().
InformationStateString()
std::string open_spiel::nine_mens_morris::NineMensMorrisState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 390 of file nine_mens_morris.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::nine_mens_morris::NineMensMorrisState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 368 of file nine_mens_morris.cc.
{
  return num_turns_ >= kMaxNumTurns || num_men_[0] <= 2 || num_men_[1] <= 2 ||
         cur_legal_actions_.empty();
}
References open_spiel::nine_mens_morris::kMaxNumTurns.
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::nine_mens_morris::NineMensMorrisState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 319 of file nine_mens_morris.cc.
{
  if (IsTerminal()) return {};
  return cur_legal_actions_;
}
References IsTerminal().
ObservationString()
std::string open_spiel::nine_mens_morris::NineMensMorrisState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 396 of file nine_mens_morris.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::nine_mens_morris::NineMensMorrisState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 402 of file nine_mens_morris.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string templ =
      ".--.--.\n"
      "|.-.-.|\n"
      "||...||\n"
      "... ...\n"
      "||...||\n"
      "|.-.-.|\n"
      ".--.--.\n";
  int pos = 0;
  TensorView<3> view(
      values, {kCellStates + 2, kObservationSize, kObservationSize}, true);
  for (int r = 0; r < kObservationSize; ++r) {
    for (int c = 0; c < kObservationSize; ++c) {
      int char_idx = r * 8 + c;
      int plane = -1;
      if (templ[char_idx] == '.') {
        if (board_[pos] == CellState::kWhite) {
          plane = 0;
        } else if (board_[pos] == CellState::kBlack) {
          plane = 1;
        } else {
          plane = 2;
        }
        pos++;
      } else if (templ[char_idx] == '-') {
        plane = 3;
      } else if (templ[char_idx] == '|') {
        plane = 4;
      }
      if (plane >= 0) {
        view[{plane, r, c}] = 1.0;
      }
    }
  }
}
References board_, open_spiel::nine_mens_morris::kBlack, open_spiel::nine_mens_morris::kObservationSize, open_spiel::nine_mens_morris::kWhite, open_spiel::State::num_players_, player, r, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
operator=()
NineMensMorrisState & open_spiel::nine_mens_morris::NineMensMorrisState::operator= (const NineMensMorrisState &) default
outcome()
Player open_spiel::nine_mens_morris::NineMensMorrisState::outcome () const inline
Definition at line 75 of file nine_mens_morris.h.
{ return outcome_; }
Referenced by open_spiel.python.examples.nego_nbs_example.Negotiation::__str__(), open_spiel.python.algorithms.mcts.SearchNode::puct_value(), open_spiel.python.algorithms.mcts.SearchNode::sort_key(), open_spiel.python.algorithms.mcts.SearchNode::to_str(), and open_spiel.python.algorithms.mcts.SearchNode::uct_value().
Returns()
std::vector< double > open_spiel::nine_mens_morris::NineMensMorrisState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 373 of file nine_mens_morris.cc.
{
  std::vector<double> returns = {0.0, 0.0};
  if (cur_legal_actions_.empty()) {
    Player opp = 1 - current_player_;
    returns[current_player_] = -1.0;
    returns[opp] = 1.0;
  } else if (num_men_[0] <= 2) {
    returns[0] = -1.0;
    returns[1] = 1.0;
  } else if (num_men_[1] <= 2) {
    returns[0] = 1.0;
    returns[1] = -1.0;
  }
  return returns;
}
ToString()
std::string open_spiel::nine_mens_morris::NineMensMorrisState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 335 of file nine_mens_morris.cc.
{
  std::string str =
      ".------.------.\n"
      "|      |      |\n"
      "| .----.----. |\n"
      "| |    |    | |\n"
      "| | .--.--. | |\n"
      "| | |     | | |\n"
      ".-.-.     .-.-.\n"
      "| | |     | | |\n"
      "| | .--.--. | |\n"
      "| |    |    | |\n"
      "| .----.----. |\n"
      "|      |      |\n"
      ".------.------.\n\n";
  absl::StrAppend(&str, "Current player: ", PlayerToStr(current_player_), "\n");
  absl::StrAppend(&str, "Turn number: ", num_turns_, "\n");
  absl::StrAppend(&str, "Men to deploy: ", men_to_deploy_[0], " ",
                  men_to_deploy_[1], "\n");
  absl::StrAppend(&str, "Num men: ", num_men_[0], " ", num_men_[1], "\n");
  if (capture_) {
    absl::StrAppend(&str, "Last move formed a mill. Capture time!");
  }
  for (int i = 0; i < kNumPoints; ++i) {
    int row = kPointStrCoords[i][0];
    int col = kPointStrCoords[i][1];
    int idx = row * 16 + col;
    str[idx] = StateToChar(board_[i]);
  }
  return str;
}
References board_, i, open_spiel::nine_mens_morris::kNumPoints, open_spiel::nine_mens_morris::PlayerToStr(), open_spiel::nine_mens_morris::StateToChar(), and absl::StrAppend().
Referenced by ObservationString().
Member Data Documentation
board_
std::array<CellState, kNumPoints> open_spiel::nine_mens_morris::NineMensMorrisState::board_ protected
Definition at line 78 of file nine_mens_morris.h.
Referenced by BoardAt(), DoApplyAction(), NineMensMorrisState(), ObservationTensor(), and ToString().
The documentation for this class was generated from the following files:
open_spiel/games/nine_mens_morris/nine_mens_morris.h
open_spiel/games/nine_mens_morris/nine_mens_morris.cc