open spiel: absl_test.AbslObjectSpanTest Class Reference
absl_test.AbslObjectSpanTest Class Reference
Public Member Functions
test_pass_object_pointers_span_from (self, objects)
test_pass_object_span_from (self, objects)
test_pass_object_span_no_convert_from_opaque_list (self)
test_pass_object_span_no_convert_fails_from_native_list (self)
test_fill_object_pointers_span_from (self, objects)
test_fill_object_span_no_convert_from_opaque_list (self)
test_fill_object_span_no_convert_fails_from_native_list (self)
Detailed Description
Definition at line 308 of file absl_test.py.
Member Function Documentation
test_fill_object_pointers_span_from()
absl_test.AbslObjectSpanTest.test_fill_object_pointers_span_from (self, objects)
Definition at line 327 of file absl_test.py.
  def test_fill_object_pointers_span_from(self, objects):
    absl_example.fill_object_pointers_span(42, objects)
    for obj in objects:
      self.assertEqual(obj.value, 42)
test_fill_object_span_no_convert_fails_from_native_list()
absl_test.AbslObjectSpanTest.test_fill_object_span_no_convert_fails_from_native_list (self)
Definition at line 338 of file absl_test.py.
  def test_fill_object_span_no_convert_fails_from_native_list(self):
    objects = make_native_list_of_objects()
    # Native list requires conversion.
    with self.assertRaises(TypeError):
      absl_example.fill_object_span(objects)
References absl_test.make_native_list_of_objects().
test_fill_object_span_no_convert_from_opaque_list()
absl_test.AbslObjectSpanTest.test_fill_object_span_no_convert_from_opaque_list (self)
Definition at line 332 of file absl_test.py.
  def test_fill_object_span_no_convert_from_opaque_list(self):
    objects = make_opaque_list_of_objects()
    absl_example.fill_object_span(42, objects)
    for obj in objects:
      self.assertEqual(obj.value, 42)
References absl_test.make_opaque_list_of_objects().
test_pass_object_pointers_span_from()
absl_test.AbslObjectSpanTest.test_pass_object_pointers_span_from (self, objects)
Definition at line 311 of file absl_test.py.
  def test_pass_object_pointers_span_from(self, objects):
    self.assertEqual(absl_example.sum_object_pointers_span(objects), 8)
test_pass_object_span_from()
absl_test.AbslObjectSpanTest.test_pass_object_span_from (self, objects)
Definition at line 315 of file absl_test.py.
  def test_pass_object_span_from(self, objects):
    self.assertEqual(absl_example.sum_object_span(objects), 8)
test_pass_object_span_no_convert_fails_from_native_list()
absl_test.AbslObjectSpanTest.test_pass_object_span_no_convert_fails_from_native_list (self)
Definition at line 321 of file absl_test.py.
  def test_pass_object_span_no_convert_fails_from_native_list(self):
    # Native list requires conversion.
    with self.assertRaises(TypeError):
      absl_example.sum_object_span_no_convert(make_native_list_of_objects())
References absl_test.make_native_list_of_objects().
test_pass_object_span_no_convert_from_opaque_list()
absl_test.AbslObjectSpanTest.test_pass_object_span_no_convert_from_opaque_list (self)
Definition at line 318 of file absl_test.py.
  def test_pass_object_span_no_convert_from_opaque_list(self):
    absl_example.sum_object_span_no_convert(make_opaque_list_of_objects())
References absl_test.make_opaque_list_of_objects().
The documentation for this class was generated from the following file:
open_spiel/pybind11_abseil/pybind11_abseil/tests/absl_test.py