open spiel: absl::Mutex Class Reference
absl::Mutex Class Reference
#include <mutex.h>
Public Types
typedef const struct MuHowS * MuHow
Public Member Functions
Mutex ()
constexpr Mutex (absl::ConstInitType)
~Mutex ()
void Lock () ABSL_EXCLUSIVE_LOCK_FUNCTION()
void Unlock () ABSL_UNLOCK_FUNCTION()
bool TryLock () ABSL_EXCLUSIVE_TRYLOCK_FUNCTION(true)
void AssertHeld () const ABSL_ASSERT_EXCLUSIVE_LOCK()
void ReaderLock () ABSL_SHARED_LOCK_FUNCTION()
void ReaderUnlock () ABSL_UNLOCK_FUNCTION()
bool ReaderTryLock () ABSL_SHARED_TRYLOCK_FUNCTION(true)
void AssertReaderHeld () const ABSL_ASSERT_SHARED_LOCK()
void WriterLock () ABSL_EXCLUSIVE_LOCK_FUNCTION()
void WriterUnlock () ABSL_UNLOCK_FUNCTION()
bool WriterTryLock () ABSL_EXCLUSIVE_TRYLOCK_FUNCTION(true)
void Await (const Condition &cond)
void LockWhen (const Condition &cond) ABSL_EXCLUSIVE_LOCK_FUNCTION()
void ReaderLockWhen (const Condition &cond) ABSL_SHARED_LOCK_FUNCTION()
void WriterLockWhen (const Condition &cond) ABSL_EXCLUSIVE_LOCK_FUNCTION()
bool AwaitWithTimeout (const Condition &cond, absl::Duration timeout)
bool AwaitWithDeadline (const Condition &cond, absl::Time deadline)
bool LockWhenWithTimeout (const Condition &cond, absl::Duration timeout) ABSL_EXCLUSIVE_LOCK_FUNCTION()
bool ReaderLockWhenWithTimeout (const Condition &cond, absl::Duration timeout) ABSL_SHARED_LOCK_FUNCTION()
bool WriterLockWhenWithTimeout (const Condition &cond, absl::Duration timeout) ABSL_EXCLUSIVE_LOCK_FUNCTION()
bool LockWhenWithDeadline (const Condition &cond, absl::Time deadline) ABSL_EXCLUSIVE_LOCK_FUNCTION()
bool ReaderLockWhenWithDeadline (const Condition &cond, absl::Time deadline) ABSL_SHARED_LOCK_FUNCTION()
bool WriterLockWhenWithDeadline (const Condition &cond, absl::Time deadline) ABSL_EXCLUSIVE_LOCK_FUNCTION()
void EnableInvariantDebugging (void(*invariant)(void *), void *arg)
void EnableDebugLog (const char *name)
void ForgetDeadlockInfo ()
void AssertNotHeld () const
Static Public Member Functions
static void InternalAttemptToUseMutexInFatalSignalHandler ()
Friends
class CondVar
Detailed Description
Definition at line 133 of file mutex.h.
Member Typedef Documentation
MuHow
typedef const struct MuHowS* absl::Mutex::MuHow
Definition at line 447 of file mutex.h.
Constructor & Destructor Documentation
Mutex() [1/2]
absl::Mutex::Mutex () inline
Definition at line 975 of file mutex.h.
                    : mu_(0) {
  ABSL_TSAN_MUTEX_CREATE(this, __tsan_mutex_not_static);
}
References ABSL_TSAN_MUTEX_CREATE.
Mutex() [2/2]
absl::Mutex::Mutex (absl::ConstInitType) inline explicit constexpr
Definition at line 979 of file mutex.h.
: mu_(0) {}
~Mutex()
absl::Mutex::~Mutex ()
Definition at line 765 of file mutex.cc.
              {
  intptr_t v = mu_.load(std::memory_order_relaxed);
  if ((v & kMuEvent) != 0 && !DebugOnlyIsExiting()) {
    ForgetSynchEvent(&this->mu_, kMuEvent, kMuSpin);
  }
  if (kDebugMode) {
    this->ForgetDeadlockInfo();
  }
  ABSL_TSAN_MUTEX_DESTROY(this, __tsan_mutex_not_static);
}
References ABSL_TSAN_MUTEX_DESTROY, and absl::v.
Member Function Documentation
AssertHeld()
void absl::Mutex::AssertHeld () const
Definition at line 2468 of file mutex.cc.
{
  if ((mu_.load(std::memory_order_relaxed) & kMuWriter) == 0) {
    SynchEvent *e = GetSynchEvent(this);
    ABSL_RAW_LOG(FATAL, "thread should hold write lock on Mutex %p %s",
                 static_cast<const void *>(this),
                 (e == nullptr ? "" : e->name));
  }
}
References ABSL_RAW_LOG, and absl::e.
AssertNotHeld()
void absl::Mutex::AssertNotHeld () const
Definition at line 1469 of file mutex.cc.
{
  // We have the data to allow this check only if in debug mode and deadlock
  // detection is enabled.
  if (kDebugMode &&
      (mu_.load(std::memory_order_relaxed) & (kMuWriter | kMuReader)) != 0 &&
      synch_deadlock_detection.load(std::memory_order_acquire) !=
          OnDeadlockCycle::kIgnore) {
    GraphId id = GetGraphId(const_cast<Mutex *>(this));
    SynchLocksHeld *locks = Synch_GetAllLocks();
    for (int i = 0; i != locks->n; i++) {
      if (locks->locks[i].id == id) {
        SynchEvent *mu_events = GetSynchEvent(this);
        ABSL_RAW_LOG(FATAL, "thread should not hold mutex %p %s",
                     static_cast<const void *>(this),
                     (mu_events == nullptr ? "" : mu_events->name));
      }
    }
  }
}
References ABSL_RAW_LOG, i, absl::SynchLocksHeld::id, absl::SynchLocksHeld::locks, and absl::SynchLocksHeld::n.
AssertReaderHeld()
void absl::Mutex::AssertReaderHeld () const
Definition at line 2477 of file mutex.cc.
{
  if ((mu_.load(std::memory_order_relaxed) & (kMuReader | kMuWriter)) == 0) {
    SynchEvent *e = GetSynchEvent(this);
    ABSL_RAW_LOG(
        FATAL, "thread should hold at least a read lock on Mutex %p %s",
        static_cast<const void *>(this), (e == nullptr ? "" : e->name));
  }
}
References ABSL_RAW_LOG, and absl::e.
Await()
void absl::Mutex::Await (const Condition & cond)
Definition at line 1585 of file mutex.cc.
{
  if (cond.Eval()) {    // condition already true; nothing to do
    if (kDebugMode) {
      this->AssertReaderHeld();
    }
  } else {              // normal case
    ABSL_RAW_CHECK(this->AwaitCommon(cond, KernelTimeout::Never()),
                   "condition untrue on return from Await");
  }
}
References ABSL_RAW_CHECK, absl::Condition::Eval(), and absl::synchronization_internal::KernelTimeout::Never().
Referenced by absl::Barrier::Block(), absl::BlockingCounter::Wait(), and absl::ThreadSafeCounter::WaitUntilGreaterOrEqual().
AwaitWithDeadline()
bool absl::Mutex::AwaitWithDeadline (const Condition & cond, absl::Time deadline)
Definition at line 1600 of file mutex.cc.
{
  if (cond.Eval()) {      // condition already true; nothing to do
    if (kDebugMode) {
      this->AssertReaderHeld();
    }
    return true;
  }
  KernelTimeout t{deadline};
  bool res = this->AwaitCommon(cond, t);
  ABSL_RAW_CHECK(res || t.has_timeout(),
                 "condition untrue on return from Await");
  return res;
}
References ABSL_RAW_CHECK, and absl::Condition::Eval().
AwaitWithTimeout()
bool absl::Mutex::AwaitWithTimeout (const Condition & cond, absl::Duration timeout)
Definition at line 1596 of file mutex.cc.
{
  return AwaitWithDeadline(cond, DeadlineFromTimeout(timeout));
}
EnableDebugLog()
void absl::Mutex::EnableDebugLog (const char * name)
Definition at line 776 of file mutex.cc.
{
  SynchEvent *e = EnsureSynchEvent(&this->mu_, name, kMuEvent, kMuSpin);
  e->log = true;
  UnrefSynchEvent(e);
}
References absl::e, and name.
EnableInvariantDebugging()
void absl::Mutex::EnableInvariantDebugging (void(* invariant)(void *), void * arg)
Definition at line 786 of file mutex.cc.
{
  if (synch_check_invariants.load(std::memory_order_acquire) &&
      invariant != nullptr) {
    SynchEvent *e = EnsureSynchEvent(&this->mu_, nullptr, kMuEvent, kMuSpin);
    e->invariant = invariant;
    e->arg = arg;
    UnrefSynchEvent(e);
  }
}
References arg, absl::e, and invariant.
ForgetDeadlockInfo()
void absl::Mutex::ForgetDeadlockInfo ()
Definition at line 1458 of file mutex.cc.
{
  if (kDebugMode && synch_deadlock_detection.load(std::memory_order_acquire) !=
                        OnDeadlockCycle::kIgnore) {
    deadlock_graph_mu.Lock();
    if (deadlock_graph != nullptr) {
      deadlock_graph->RemoveNode(this);
    }
    deadlock_graph_mu.Unlock();
  }
}
References absl::base_internal::SpinLock::Lock(), and absl::base_internal::SpinLock::Unlock().
InternalAttemptToUseMutexInFatalSignalHandler()
void absl::Mutex::InternalAttemptToUseMutexInFatalSignalHandler () static
Definition at line 627 of file mutex.cc.
{
  // Fix the per-thread state only if it exists.
  ThreadIdentity *identity = CurrentThreadIdentityIfPresent();
  if (identity != nullptr) {
    identity->per_thread_synch.suppress_fatal_errors = true;
  }
  // Don't do deadlock detection when we are already failing.
  synch_deadlock_detection.store(OnDeadlockCycle::kIgnore,
                                 std::memory_order_release);
}
References absl::base_internal::ThreadIdentity::per_thread_synch, and absl::base_internal::PerThreadSynch::suppress_fatal_errors.
Lock()
void absl::Mutex::Lock ()
Definition at line 1507 of file mutex.cc.
                 {
  ABSL_TSAN_MUTEX_PRE_LOCK(this, 0);
  GraphId id = DebugOnlyDeadlockCheck(this);
  intptr_t v = mu_.load(std::memory_order_relaxed);
  // try fast acquire, then spin loop
  if ((v & (kMuWriter | kMuReader | kMuEvent)) != 0 ||
      !mu_.compare_exchange_strong(v, kMuWriter | v,
                                   std::memory_order_acquire,
                                   std::memory_order_relaxed)) {
    // try spin acquire, then slow loop
    if (!TryAcquireWithSpinning(&this->mu_)) {
      this->LockSlow(kExclusive, nullptr, 0);
    }
  }
  DebugOnlyLockEnter(this, id);
  ABSL_TSAN_MUTEX_POST_LOCK(this, 0, 0);
}
References ABSL_TSAN_MUTEX_POST_LOCK, ABSL_TSAN_MUTEX_PRE_LOCK, and absl::v.
Referenced by absl::MutexLock::MutexLock(), absl::MutexLockMaybe::MutexLockMaybe(), absl::ReleasableMutexLock::ReleasableMutexLock(), absl::ABSL_NAMESPACE_BEGIN::TEST(), absl::ABSL_NAMESPACE_BEGIN::ThreadBody(), and absl::ABSL_NAMESPACE_BEGIN::WaitAndIncrement().
LockWhen()
void absl::Mutex::LockWhen (const Condition & cond)
Definition at line 1540 of file mutex.cc.
{
  ABSL_TSAN_MUTEX_PRE_LOCK(this, 0);
  GraphId id = DebugOnlyDeadlockCheck(this);
  this->LockSlow(kExclusive, &cond, 0);
  DebugOnlyLockEnter(this, id);
  ABSL_TSAN_MUTEX_POST_LOCK(this, 0, 0);
}
References ABSL_TSAN_MUTEX_POST_LOCK, and ABSL_TSAN_MUTEX_PRE_LOCK.
Referenced by absl::MutexLock::MutexLock(), absl::MutexLockMaybe::MutexLockMaybe(), absl::ReleasableMutexLock::ReleasableMutexLock(), absl::ABSL_NAMESPACE_BEGIN::TEST(), absl::ABSL_NAMESPACE_BEGIN::WaitAndIncrement(), and absl::Notification::WaitForNotification().
LockWhenWithDeadline()
bool absl::Mutex::LockWhenWithDeadline (const Condition & cond, absl::Time deadline)
Definition at line 1552 of file mutex.cc.
{
  ABSL_TSAN_MUTEX_PRE_LOCK(this, 0);
  GraphId id = DebugOnlyDeadlockCheck(this);
  bool res = LockSlowWithDeadline(kExclusive, &cond,
                                  KernelTimeout(deadline), 0);
  DebugOnlyLockEnter(this, id);
  ABSL_TSAN_MUTEX_POST_LOCK(this, 0, 0);
  return res;
}
References ABSL_TSAN_MUTEX_POST_LOCK, and ABSL_TSAN_MUTEX_PRE_LOCK.
Referenced by absl::Notification::WaitForNotificationWithDeadline().
LockWhenWithTimeout()
bool absl::Mutex::LockWhenWithTimeout (const Condition & cond, absl::Duration timeout)
Definition at line 1548 of file mutex.cc.
{
  return LockWhenWithDeadline(cond, DeadlineFromTimeout(timeout));
}
Referenced by absl::Notification::WaitForNotificationWithTimeout().
ReaderLock()
void absl::Mutex::ReaderLock ()
Definition at line 1525 of file mutex.cc.
                       {
  ABSL_TSAN_MUTEX_PRE_LOCK(this, __tsan_mutex_read_lock);
  GraphId id = DebugOnlyDeadlockCheck(this);
  intptr_t v = mu_.load(std::memory_order_relaxed);
  // try fast acquire, then slow loop
  if ((v & (kMuWriter | kMuWait | kMuEvent)) != 0 ||
      !mu_.compare_exchange_strong(v, (kMuReader | v) + kMuOne,
                                   std::memory_order_acquire,
                                   std::memory_order_relaxed)) {
    this->LockSlow(kShared, nullptr, 0);
  }
  DebugOnlyLockEnter(this, id);
  ABSL_TSAN_MUTEX_POST_LOCK(this, __tsan_mutex_read_lock, 0);
}
References ABSL_TSAN_MUTEX_POST_LOCK, ABSL_TSAN_MUTEX_PRE_LOCK, and absl::v.
Referenced by absl::ReaderMutexLock::ReaderMutexLock().
ReaderLockWhen()
void absl::Mutex::ReaderLockWhen (const Condition & cond)
Definition at line 1562 of file mutex.cc.
{
  ABSL_TSAN_MUTEX_PRE_LOCK(this, __tsan_mutex_read_lock);
  GraphId id = DebugOnlyDeadlockCheck(this);
  this->LockSlow(kShared, &cond, 0);
  DebugOnlyLockEnter(this, id);
  ABSL_TSAN_MUTEX_POST_LOCK(this, __tsan_mutex_read_lock, 0);
}
References ABSL_TSAN_MUTEX_POST_LOCK, and ABSL_TSAN_MUTEX_PRE_LOCK.
Referenced by absl::ReaderMutexLock::ReaderMutexLock().
ReaderLockWhenWithDeadline()
bool absl::Mutex::ReaderLockWhenWithDeadline (const Condition & cond, absl::Time deadline)
Definition at line 1575 of file mutex.cc.
{
  ABSL_TSAN_MUTEX_PRE_LOCK(this, __tsan_mutex_read_lock);
  GraphId id = DebugOnlyDeadlockCheck(this);
  bool res = LockSlowWithDeadline(kShared, &cond, KernelTimeout(deadline), 0);
  DebugOnlyLockEnter(this, id);
  ABSL_TSAN_MUTEX_POST_LOCK(this, __tsan_mutex_read_lock, 0);
  return res;
}
References ABSL_TSAN_MUTEX_POST_LOCK, and ABSL_TSAN_MUTEX_PRE_LOCK.
ReaderLockWhenWithTimeout()
bool absl::Mutex::ReaderLockWhenWithTimeout (const Condition & cond, absl::Duration timeout)
Definition at line 1570 of file mutex.cc.
{
  return ReaderLockWhenWithDeadline(cond, DeadlineFromTimeout(timeout));
}
ReaderTryLock()
bool absl::Mutex::ReaderTryLock ()
Definition at line 1667 of file mutex.cc.
{
  ABSL_TSAN_MUTEX_PRE_LOCK(this,
                           __tsan_mutex_read_lock | __tsan_mutex_try_lock);
  intptr_t v = mu_.load(std::memory_order_relaxed);
  // The while-loops (here and below) iterate only if the mutex word keeps
  // changing (typically because the reader count changes) under the CAS.  We
  // limit the number of attempts to avoid having to think about livelock.
  int loop_limit = 5;
  while ((v & (kMuWriter|kMuWait|kMuEvent)) == 0 && loop_limit != 0) {
    if (mu_.compare_exchange_strong(v, (kMuReader | v) + kMuOne,
                                    std::memory_order_acquire,
                                    std::memory_order_relaxed)) {
      DebugOnlyLockEnter(this);
      ABSL_TSAN_MUTEX_POST_LOCK(
          this, __tsan_mutex_read_lock | __tsan_mutex_try_lock, 0);
      return true;
    }
    loop_limit--;
    v = mu_.load(std::memory_order_relaxed);
  }
  if ((v & kMuEvent) != 0) {   // we're recording events
    loop_limit = 5;
    while ((v & kShared->slow_need_zero) == 0 && loop_limit != 0) {
      if (mu_.compare_exchange_strong(v, (kMuReader | v) + kMuOne,
                                      std::memory_order_acquire,
                                      std::memory_order_relaxed)) {
        DebugOnlyLockEnter(this);
        PostSynchEvent(this, SYNCH_EV_READERTRYLOCK_SUCCESS);
        ABSL_TSAN_MUTEX_POST_LOCK(
            this, __tsan_mutex_read_lock | __tsan_mutex_try_lock, 0);
        return true;
      }
      loop_limit--;
      v = mu_.load(std::memory_order_relaxed);
    }
    if ((v & kMuEvent) != 0) {
      PostSynchEvent(this, SYNCH_EV_READERTRYLOCK_FAILED);
    }
  }
  ABSL_TSAN_MUTEX_POST_LOCK(this,
                            __tsan_mutex_read_lock | __tsan_mutex_try_lock |
                                __tsan_mutex_try_lock_failed,
                            0);
  return false;
}
References ABSL_TSAN_MUTEX_POST_LOCK, ABSL_TSAN_MUTEX_PRE_LOCK, and absl::v.
ReaderUnlock()
void absl::Mutex::ReaderUnlock ()
Definition at line 1765 of file mutex.cc.
{
  ABSL_TSAN_MUTEX_PRE_UNLOCK(this, __tsan_mutex_read_lock);
  DebugOnlyLockLeave(this);
  intptr_t v = mu_.load(std::memory_order_relaxed);
  assert((v & (kMuWriter|kMuReader)) == kMuReader);
  if ((v & (kMuReader|kMuWait|kMuEvent)) == kMuReader) {
    // fast reader release (reader with no waiters)
    intptr_t clear = ExactlyOneReader(v) ? kMuReader|kMuOne : kMuOne;
    if (mu_.compare_exchange_strong(v, v - clear,
                                    std::memory_order_release,
                                    std::memory_order_relaxed)) {
      ABSL_TSAN_MUTEX_POST_UNLOCK(this, __tsan_mutex_read_lock);
      return;
    }
  }
  this->UnlockSlow(nullptr /*no waitp*/);  // take slow path
  ABSL_TSAN_MUTEX_POST_UNLOCK(this, __tsan_mutex_read_lock);
}
References ABSL_TSAN_MUTEX_POST_UNLOCK, ABSL_TSAN_MUTEX_PRE_UNLOCK, and absl::v.
Referenced by absl::ReaderMutexLock::~ReaderMutexLock().
TryLock()
bool absl::Mutex::TryLock ()
Definition at line 1638 of file mutex.cc.
                    {
  ABSL_TSAN_MUTEX_PRE_LOCK(this, __tsan_mutex_try_lock);
  intptr_t v = mu_.load(std::memory_order_relaxed);
  if ((v & (kMuWriter | kMuReader | kMuEvent)) == 0 &&  // try fast acquire
      mu_.compare_exchange_strong(v, kMuWriter | v,
                                  std::memory_order_acquire,
                                  std::memory_order_relaxed)) {
    DebugOnlyLockEnter(this);
    ABSL_TSAN_MUTEX_POST_LOCK(this, __tsan_mutex_try_lock, 0);
    return true;
  }
  if ((v & kMuEvent) != 0) {              // we're recording events
    if ((v & kExclusive->slow_need_zero) == 0 &&  // try fast acquire
        mu_.compare_exchange_strong(
            v, (kExclusive->fast_or | v) + kExclusive->fast_add,
            std::memory_order_acquire, std::memory_order_relaxed)) {
      DebugOnlyLockEnter(this);
      PostSynchEvent(this, SYNCH_EV_TRYLOCK_SUCCESS);
      ABSL_TSAN_MUTEX_POST_LOCK(this, __tsan_mutex_try_lock, 0);
      return true;
    } else {
      PostSynchEvent(this, SYNCH_EV_TRYLOCK_FAILED);
    }
  }
  ABSL_TSAN_MUTEX_POST_LOCK(
      this, __tsan_mutex_try_lock | __tsan_mutex_try_lock_failed, 0);
  return false;
}
References ABSL_TSAN_MUTEX_POST_LOCK, ABSL_TSAN_MUTEX_PRE_LOCK, absl::MuHowS::fast_add, absl::MuHowS::fast_or, absl::MuHowS::slow_need_zero, and absl::v.
Unlock()
void absl::Mutex::Unlock ()
Definition at line 1713 of file mutex.cc.
                   {
  ABSL_TSAN_MUTEX_PRE_UNLOCK(this, 0);
  DebugOnlyLockLeave(this);
  intptr_t v = mu_.load(std::memory_order_relaxed);
  if (kDebugMode && ((v & (kMuWriter | kMuReader)) != kMuWriter)) {
    ABSL_RAW_LOG(FATAL, "Mutex unlocked when destroyed or not locked: v=0x%x",
                 static_cast<unsigned>(v));
  }
  // should_try_cas is whether we'll try a compare-and-swap immediately.
  // NOTE: optimized out when kDebugMode is false.
  bool should_try_cas = ((v & (kMuEvent | kMuWriter)) == kMuWriter &&
                          (v & (kMuWait | kMuDesig)) != kMuWait);
  // But, we can use an alternate computation of it, that compilers
  // currently don't find on their own.  When that changes, this function
  // can be simplified.
  intptr_t x = (v ^ (kMuWriter | kMuWait)) & (kMuWriter | kMuEvent);
  intptr_t y = (v ^ (kMuWriter | kMuWait)) & (kMuWait | kMuDesig);
  // Claim: "x == 0 && y > 0" is equal to should_try_cas.
  // Also, because kMuWriter and kMuEvent exceed kMuDesig and kMuWait,
  // all possible non-zero values for x exceed all possible values for y.
  // Therefore, (x == 0 && y > 0) == (x < y).
  if (kDebugMode && should_try_cas != (x < y)) {
    // We would usually use PRIdPTR here, but is not correctly implemented
    // within the android toolchain.
    ABSL_RAW_LOG(FATAL, "internal logic error %llx %llx %llx\n",
                 static_cast<long long>(v), static_cast<long long>(x),
                 static_cast<long long>(y));
  }
  if (x < y &&
      mu_.compare_exchange_strong(v, v & ~(kMuWrWait | kMuWriter),
                                  std::memory_order_release,
                                  std::memory_order_relaxed)) {
    // fast writer release (writer with no waiters or with designated waker)
  } else {
    this->UnlockSlow(nullptr /*no waitp*/);  // take slow path
  }
  ABSL_TSAN_MUTEX_POST_UNLOCK(this, 0);
}
References ABSL_RAW_LOG, ABSL_TSAN_MUTEX_POST_UNLOCK, ABSL_TSAN_MUTEX_PRE_UNLOCK, absl::v, x, and y.
Referenced by absl::ReleasableMutexLock::Release(), absl::ABSL_NAMESPACE_BEGIN::TEST(), absl::ABSL_NAMESPACE_BEGIN::ThreadBody(), absl::ABSL_NAMESPACE_BEGIN::WaitAndIncrement(), absl::Notification::WaitForNotification(), absl::Notification::WaitForNotificationWithDeadline(), absl::Notification::WaitForNotificationWithTimeout(), absl::MutexLock::~MutexLock(), absl::MutexLockMaybe::~MutexLockMaybe(), and absl::ReleasableMutexLock::~ReleasableMutexLock().
WriterLock()
void absl::Mutex::WriterLock () inline
Definition at line 262 of file mutex.h.
{ this->Lock(); }
Referenced by absl::WriterMutexLock::WriterMutexLock().
WriterLockWhen()
void absl::Mutex::WriterLockWhen (const Condition & cond) inline
Definition at line 324 of file mutex.h.
{
    this->LockWhen(cond);
  }
Referenced by absl::WriterMutexLock::WriterMutexLock().
WriterLockWhenWithDeadline()
bool absl::Mutex::WriterLockWhenWithDeadline (const Condition & cond, absl::Time deadline) inline
Definition at line 388 of file mutex.h.
{
    return this->LockWhenWithDeadline(cond, deadline);
  }
WriterLockWhenWithTimeout()
bool absl::Mutex::WriterLockWhenWithTimeout (const Condition & cond, absl::Duration timeout) inline
Definition at line 368 of file mutex.h.
{
    return this->LockWhenWithTimeout(cond, timeout);
  }
WriterTryLock()
bool absl::Mutex::WriterTryLock () inline
Definition at line 266 of file mutex.h.
{
    return this->TryLock();
  }
WriterUnlock()
void absl::Mutex::WriterUnlock () inline
Definition at line 264 of file mutex.h.
{ this->Unlock(); }
Referenced by absl::WriterMutexLock::~WriterMutexLock().
Friends And Related Symbol Documentation
CondVar
friend class CondVar friend
Definition at line 493 of file mutex.h.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/synchronization/mutex.h
open_spiel/abseil-cpp/absl/synchronization/mutex.cc