open spiel: open_spiel::algorithms::ExternalSamplingMCCFRSolver Class Reference
open_spiel::algorithms::ExternalSamplingMCCFRSolver Class Reference
#include <external_sampling_mccfr.h>
Public Member Functions
ExternalSamplingMCCFRSolver (const Game &game, int seed=0, AverageType avg_type=AverageType::kSimple)
ExternalSamplingMCCFRSolver (const Game &game, std::shared_ptr< Policy > default_policy, int seed=0, AverageType avg_type=AverageType::kSimple)
ExternalSamplingMCCFRSolver (std::shared_ptr< const Game > game, std::shared_ptr< Policy > default_policy, std::unique_ptr< std::mt19937 > rng, AverageType avg_type)
void RunIteration ()
void RunIteration (std::mt19937 *rng)
CFRInfoStateValuesTable & InfoStateValuesTable ()
std::shared_ptr< Policy > AveragePolicy () const
std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const
Static Public Attributes
static constexpr double kInitialTableValues = 0.000001
Detailed Description
Definition at line 57 of file external_sampling_mccfr.h.
Constructor & Destructor Documentation
ExternalSamplingMCCFRSolver() [1/3]
open_spiel::algorithms::ExternalSamplingMCCFRSolver::ExternalSamplingMCCFRSolver (const Game & game, int seed = 0, AverageType avg_type = AverageType::kSimple)
Definition at line 40 of file external_sampling_mccfr.cc.
    : ExternalSamplingMCCFRSolver(game, std::make_shared<UniformPolicy>(), seed,
                                  avg_type) {}
ExternalSamplingMCCFRSolver() [2/3]
open_spiel::algorithms::ExternalSamplingMCCFRSolver::ExternalSamplingMCCFRSolver (const Game & game, std::shared_ptr< Policy > default_policy, int seed = 0, AverageType avg_type = AverageType::kSimple)
Definition at line 46 of file external_sampling_mccfr.cc.
    : ExternalSamplingMCCFRSolver(game.shared_from_this(), default_policy,
                                  std::make_unique<std::mt19937>(seed),
                                  avg_type) {}
ExternalSamplingMCCFRSolver() [3/3]
open_spiel::algorithms::ExternalSamplingMCCFRSolver::ExternalSamplingMCCFRSolver (std::shared_ptr< const Game > game, std::shared_ptr< Policy > default_policy, std::unique_ptr< std::mt19937 > rng, AverageType avg_type)
Definition at line 53 of file external_sampling_mccfr.cc.
    : game_(game),
      rng_(std::move(rng)),
      avg_type_(avg_type),
      dist_(0.0, 1.0),
      default_policy_(default_policy) {
  if (game_->GetType().dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError(
        "MCCFR requires sequential games. If you're trying to run it "
        "on a simultaneous (or normal-form) game, please first transform it "
        "using turn_based_simultaneous_game.");
  }
}
References open_spiel::GameType::kSequential, and open_spiel::SpielFatalError().
Member Function Documentation
AveragePolicy()
std::shared_ptr< Policy > open_spiel::algorithms::ExternalSamplingMCCFRSolver::AveragePolicy () const inline
Definition at line 93 of file external_sampling_mccfr.h.
{
    return std::make_shared<CFRAveragePolicy>(info_states_, default_policy_);
  }
Referenced by open_spiel::init_pyspiel_policy(), and main().
InfoStateValuesTable()
CFRInfoStateValuesTable & open_spiel::algorithms::ExternalSamplingMCCFRSolver::InfoStateValuesTable () inline
Definition at line 88 of file external_sampling_mccfr.h.
{ return info_states_; }
RunIteration() [1/2]
void open_spiel::algorithms::ExternalSamplingMCCFRSolver::RunIteration ()
Definition at line 69 of file external_sampling_mccfr.cc.
{ RunIteration(rng_.get()); }
References RunIteration().
Referenced by main(), and RunIteration().
RunIteration() [2/2]
void open_spiel::algorithms::ExternalSamplingMCCFRSolver::RunIteration (std::mt19937 * rng)
Definition at line 71 of file external_sampling_mccfr.cc.
{
  for (auto p = Player{0}; p < game_->NumPlayers(); ++p) {
    UpdateRegrets(*game_->NewInitialState(), p, rng);
  }
  if (avg_type_ == AverageType::kFull) {
    std::vector<double> reach_probs(game_->NumPlayers(), 1.0);
    FullUpdateAverage(*game_->NewInitialState(), reach_probs);
  }
}
References open_spiel::algorithms::kFull.
Serialize()
std::string open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize (int double_precision = -1, std::string delimiter = "<~>") const
Definition at line 82 of file external_sampling_mccfr.cc.
{
  SPIEL_CHECK_GE(double_precision, -1);
  std::string str = "";
  // Meta section
  absl::StrAppend(&str,
                  "# Automatically generated by OpenSpiel "
                  "ExternalSamplingMCCFRSolver::Serialize\n");
  absl::StrAppend(&str, kSerializeMetaSectionHeader, "\n");
  absl::StrAppend(&str, "Version: ", kSerializationVersion, "\n");
  absl::StrAppend(&str, "\n");
  // Game section
  absl::StrAppend(&str, kSerializeGameSectionHeader, "\n");
  absl::StrAppend(&str, game_->Serialize(), "\n");
  // Internal solver state section
  absl::StrAppend(&str, kSerializeSolverTypeSectionHeader, "\n");
  absl::StrAppend(&str, "ExternalSamplingMCCFRSolver", "\n");
  absl::StrAppend(&str, kSerializeSolverSpecificStateSectionHeader, "\n");
  // RNG section
  absl::StrAppend(&str, kSerializeSolverRNGSectionHeader, "\n");
  std::ostringstream rng_stream;
  rng_stream << *rng_;
  absl::StrAppend(&str, rng_stream.str(), "\n");
  // Average type section
  absl::StrAppend(&str, kSerializeSolverAverageTypeSectionHeader, "\n");
  if (avg_type_ == AverageType::kFull)
    absl::StrAppend(&str, "FullAverageType", "\n");
  else if (avg_type_ == AverageType::kSimple)
    absl::StrAppend(&str, "SimpleAverageType", "\n");
  // Default policy section
  absl::StrAppend(&str, kSerializeSolverDefaultPolicySectionHeader, "\n");
  absl::StrAppend(&str, default_policy_->Serialize(double_precision, delimiter),
                  "\n");
  // Info state values table section
  absl::StrAppend(&str, kSerializeSolverValuesTableSectionHeader, "\n");
  SerializeCFRInfoStateValuesTable(info_states_, &str, double_precision,
                                   delimiter);
  return str;
}
References open_spiel::algorithms::kFull, open_spiel::algorithms::kSerializationVersion, open_spiel::algorithms::kSerializeGameSectionHeader, open_spiel::algorithms::kSerializeMetaSectionHeader, open_spiel::algorithms::kSerializeSolverAverageTypeSectionHeader, open_spiel::algorithms::kSerializeSolverDefaultPolicySectionHeader, open_spiel::algorithms::kSerializeSolverRNGSectionHeader, open_spiel::algorithms::kSerializeSolverSpecificStateSectionHeader, open_spiel::algorithms::kSerializeSolverTypeSectionHeader, open_spiel::algorithms::kSerializeSolverValuesTableSectionHeader, open_spiel::algorithms::kSimple, open_spiel::algorithms::SerializeCFRInfoStateValuesTable(), SPIEL_CHECK_GE, and absl::StrAppend().
Member Data Documentation
kInitialTableValues
double open_spiel::algorithms::ExternalSamplingMCCFRSolver::kInitialTableValues = 0.000001 inline static constexpr
Definition at line 59 of file external_sampling_mccfr.h.
The documentation for this class was generated from the following files:
open_spiel/algorithms/external_sampling_mccfr.h
open_spiel/algorithms/external_sampling_mccfr.cc