open spiel: open_spiel::dynamic_routing::DynamicRoutingData Class Reference
open_spiel::dynamic_routing::DynamicRoutingData Class Reference
#include <dynamic_routing_data.h>
Static Public Member Functions
static std::unique_ptr< DynamicRoutingData > Create (DynamicRoutingDataName name)
Public Attributes
std::unique_ptr< Network > network_
std::unique_ptr< std::vector< OriginDestinationDemand > > od_demand_
Detailed Description
Definition at line 30 of file dynamic_routing_data.h.
Member Function Documentation
Create()
std::unique_ptr< DynamicRoutingData > open_spiel::dynamic_routing::DynamicRoutingData::Create (DynamicRoutingDataName name) static
Definition at line 29 of file dynamic_routing_data.cc.
{
  std::unique_ptr<DynamicRoutingData> data =
      absl::make_unique<DynamicRoutingData>();
  switch (name) {
    case DynamicRoutingDataName::kLine: {
      absl::flat_hash_map<std::string, std::vector<std::string>>
          adjacency_list = {{"bef_O", {"O"}},
                            {"O", {"A"}},
                            {"A", {"D"}},
                            {"D", {"aft_D"}},
                            {"aft_D", {}}};
      data->network_ = Network::Create(adjacency_list);
      data->od_demand_ =
          absl::make_unique<std::vector<OriginDestinationDemand>>(std::vector{
              OriginDestinationDemand("bef_O->O", "D->aft_D", 0, 100)});
      return data;
    }
    case DynamicRoutingDataName::kBraess: {
      const int kBraessNumPlayer = 5;
      absl::flat_hash_map<std::string, std::vector<std::string>>
          adjacency_list = {{"O", {"A"}}, {"A", {"B", "C"}}, {"B", {"C", "D"}},
                            {"C", {"D"}}, {"D", {"E"}},      {"E", {}}};
      absl::flat_hash_map<std::string, std::pair<float, float>> node_position =
          {{"O", {0, 0}},  {"A", {1, 0}}, {"B", {2, 1}},
           {"C", {2, -1}}, {"D", {3, 0}}, {"E", {4, 0}}};
      absl::flat_hash_map<std::string, float> bpr_a_coefficient = {
          {"O->A", 0}, {"A->B", 1.0}, {"A->C", 0}, {"B->C", 0},
          {"B->D", 0}, {"C->D", 1.0}, {"D->E", 0}};
      absl::flat_hash_map<std::string, float> bpr_b_coefficient = {
          {"O->A", 1.0}, {"A->B", 1.0}, {"A->C", 1.0}, {"B->C", 1.0},
          {"B->D", 1.0}, {"C->D", 1.0}, {"D->E", 1.0}};
      absl::flat_hash_map<std::string, float> capacity = {
          {"O->A", kBraessNumPlayer}, {"A->B", kBraessNumPlayer},
          {"A->C", kBraessNumPlayer}, {"B->C", kBraessNumPlayer},
          {"B->D", kBraessNumPlayer}, {"C->D", kBraessNumPlayer},
          {"D->E", kBraessNumPlayer}};
      absl::flat_hash_map<std::string, float> free_flow_travel_time = {
          {"O->A", 0},   {"A->B", 1.0}, {"A->C", 2.0}, {"B->C", 0.25},
          {"B->D", 2.0}, {"C->D", 1.0}, {"D->E", 0}};
      data->network_ =
          Network::Create(adjacency_list, node_position, bpr_a_coefficient,
                          bpr_b_coefficient, capacity, free_flow_travel_time);
      data->od_demand_ =
          absl::make_unique<std::vector<OriginDestinationDemand>>(std::vector{
              OriginDestinationDemand("O->A", "D->E", 0, kBraessNumPlayer)});
      return data;
    }
    default:
      open_spiel::SpielFatalError(
          absl::StrCat("Unknown Dynamic Routing Data Name: ", name));
  }
  return data;
}
References open_spiel::dynamic_routing::Network::Create(), data, open_spiel::dynamic_routing::kBraess, open_spiel::dynamic_routing::kLine, name, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGame::MeanFieldRoutingGame().
Member Data Documentation
network_
std::unique_ptr<Network> open_spiel::dynamic_routing::DynamicRoutingData::network_
Definition at line 36 of file dynamic_routing_data.h.
od_demand_
std::unique_ptr<std::vector<OriginDestinationDemand> > open_spiel::dynamic_routing::DynamicRoutingData::od_demand_
Definition at line 37 of file dynamic_routing_data.h.
The documentation for this class was generated from the following files:
open_spiel/games/dynamic_routing/dynamic_routing_data.h
open_spiel/games/dynamic_routing/dynamic_routing_data.cc