open spiel: open_spiel::algorithms::FSICFRGraph Class Reference
open_spiel::algorithms::FSICFRGraph Class Reference
#include <fsicfr.h>
Public Member Functions
FSICFRGraph ()
FSICFRNode * GetOrCreateDecisionNode (const std::vector< Action > &legal_actions, const std::string &info_state_string, Player player, int max_predecessors, int chance_id)
FSICFRNode * GetOrCreateTerminalNode (const std::string &terminal_string_key, double p0_utility, int max_predecessors)
FSICFRNode * GetNode (int id) const
int size () const
void TopSort ()
int ordered_node_id (int idx) const
Detailed Description
Definition at line 76 of file fsicfr.h.
Constructor & Destructor Documentation
FSICFRGraph()
open_spiel::algorithms::FSICFRGraph::FSICFRGraph () inline
Definition at line 78 of file fsicfr.h.
{}
Member Function Documentation
GetNode()
FSICFRNode * open_spiel::algorithms::FSICFRGraph::GetNode (int id) const inline
Definition at line 85 of file fsicfr.h.
{
    if (id < 0 || id >= nodes_.size()) {
      return nullptr;
    } else {
      FSICFRGraph* this_graph = const_cast<FSICFRGraph*>(this);
      return &this_graph->nodes_[id];
    }
  }
Referenced by open_spiel::algorithms::FSICFRSolver::GetAveragePolicy().
GetOrCreateDecisionNode()
FSICFRNode * open_spiel::algorithms::FSICFRGraph::GetOrCreateDecisionNode (const std::vector< Action > & legal_actions, const std::string & info_state_string, Player player, int max_predecessors, int chance_id)
Definition at line 54 of file fsicfr.cc.
                   {
  auto iter = string_key_to_node_id_map_.find(info_state_string);
  if (iter != string_key_to_node_id_map_.end()) {
    return &nodes_[iter->second];
  } else {
    FSICFRNode node;
    node.terminal = false;
    node.string_key = info_state_string;
    node.player = player;
    node.chance_id = chance_id;
    node.max_predecessors = max_predecessors;
    node.legal_actions = legal_actions;
    node.psum = {0.0, 0.0};
    node.strategy =
        std::vector<double>(legal_actions.size(), 1.0 / legal_actions.size());
    node.regrets =
        std::vector<double>(legal_actions.size(), 1.0 / legal_actions.size());
    node.ssum = std::vector<double>(legal_actions.size(), 0.0);
    node.id = nodes_.size();
    string_key_to_node_id_map_[info_state_string] = node.id;
    nodes_.push_back(node);
    return &nodes_[node.id];
  }
}
References open_spiel::algorithms::FSICFRNode::chance_id, open_spiel::algorithms::FSICFRNode::id, open_spiel::algorithms::FSICFRNode::legal_actions, open_spiel::algorithms::FSICFRNode::max_predecessors, open_spiel::algorithms::FSICFRNode::player, player, open_spiel::algorithms::FSICFRNode::psum, open_spiel::algorithms::FSICFRNode::regrets, open_spiel::algorithms::FSICFRNode::ssum, open_spiel::algorithms::FSICFRNode::strategy, open_spiel::algorithms::FSICFRNode::string_key, and open_spiel::algorithms::FSICFRNode::terminal.
GetOrCreateTerminalNode()
FSICFRNode * open_spiel::algorithms::FSICFRGraph::GetOrCreateTerminalNode (const std::string & terminal_string_key, double p0_utility, int max_predecessors)
Definition at line 82 of file fsicfr.cc.
{
  auto iter = string_key_to_node_id_map_.find(terminal_string_key);
  if (iter != string_key_to_node_id_map_.end()) {
    return &nodes_[iter->second];
  } else {
    FSICFRNode node;
    node.terminal = true;
    node.string_key = terminal_string_key;
    node.p0_utility = p0_utility;
    node.max_predecessors = max_predecessors;
    node.id = nodes_.size();
    string_key_to_node_id_map_[terminal_string_key] = node.id;
    nodes_.push_back(node);
    return &nodes_[node.id];
  }
}
References open_spiel::algorithms::FSICFRNode::id, open_spiel::algorithms::FSICFRNode::max_predecessors, open_spiel::algorithms::FSICFRNode::p0_utility, open_spiel::algorithms::FSICFRNode::string_key, and open_spiel::algorithms::FSICFRNode::terminal.
ordered_node_id()
int open_spiel::algorithms::FSICFRGraph::ordered_node_id (int idx) const inline
Definition at line 99 of file fsicfr.h.
{ return ordered_ids_[idx]; }
size()
int open_spiel::algorithms::FSICFRGraph::size () const inline
Definition at line 94 of file fsicfr.h.
{ return nodes_.size(); }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel::algorithms::FSICFRSolver::GetAveragePolicy(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
TopSort()
void open_spiel::algorithms::FSICFRGraph::TopSort ()
Definition at line 101 of file fsicfr.cc.
{
  int max_value = -1;
  int cur_value = 0;
  bool done = false;
  int num_nodes = 0;
  while (!done) {
    num_nodes = 0;
    for (int i = 0; i < nodes_.size(); ++i) {
      max_value = std::max(max_value, nodes_[i].max_predecessors);
      if (nodes_[i].max_predecessors == cur_value) {
        // std::cout << nodes_[i].max_predecessors << " "
        //           << nodes_[i].string_key << std::endl;
        ordered_ids_.push_back(i);
        num_nodes++;
      }
    }
    cur_value++;
    if (cur_value > max_value) {
      done = true;
    }
  }
  SPIEL_CHECK_EQ(nodes_.size(), ordered_ids_.size());
}
References i, and SPIEL_CHECK_EQ.
The documentation for this class was generated from the following files:
open_spiel/algorithms/fsicfr.h
open_spiel/algorithms/fsicfr.cc