open spiel: open_spiel::sheriff::SheriffState Class Reference
open_spiel::sheriff::SheriffState Class Reference final
#include <sheriff.h>
Public Member Functions
SheriffState (std::shared_ptr< const SheriffGame > sheriff_game)
~SheriffState ()=default
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
std::string InformationStateString (Player player) const override
void UndoAction (Player player, Action action_id) override
void InformationStateTensor (Player player, absl::Span< float > values) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
virtual std::string ObservationString (Player player) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 186 of file sheriff.h.
Constructor & Destructor Documentation
SheriffState()
open_spiel::sheriff::SheriffState::SheriffState (std::shared_ptr< const SheriffGame > sheriff_game) explicit
Definition at line 70 of file sheriff.cc.
    : State(sheriff_game), sheriff_game_(sheriff_game) {}
~SheriffState()
open_spiel::sheriff::SheriffState::~SheriffState () default
Member Function Documentation
ActionToString()
std::string open_spiel::sheriff::SheriffState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 140 of file sheriff.cc.
{
  return sheriff_game_->ActionToString(player, action_id);
}
References player.
Clone()
std::unique_ptr< State > open_spiel::sheriff::SheriffState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 196 of file sheriff.cc.
{
  return std::make_unique<SheriffState>(*this);
}
CurrentPlayer()
Player open_spiel::sheriff::SheriffState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 74 of file sheriff.cc.
{
  if (!num_illegal_items_) {
    // The smuggler still hasn't decided the number of illegal items to
    // place in the cargo. The game has just begun.
    return kSmuggler;
  } else if (bribes_.size() == inspection_feedback_.size()) {
    // The smuggler has received feedback for all the bribes.
    //
    // If the number of bribes is equal to the number of bribing turns in the
    // game, the game is over.
    if (bribes_.size() == sheriff_game_->conf.num_rounds) {
      return kTerminalPlayerId;
    } else {
      // Otherwise, a new bribing round begins.
      return kSmuggler;
    }
  } else {
    // The smuggles has made a bribe, but no feedback has been given out yet.
    return kSheriff;
  }
}
References open_spiel::sheriff::kSheriff, open_spiel::sheriff::kSmuggler, and open_spiel::kTerminalPlayerId.
Referenced by DoApplyAction(), InformationStateTensor(), IsTerminal(), and LegalActions().
DoApplyAction()
void open_spiel::sheriff::SheriffState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 315 of file sheriff.cc.
{
  SPIEL_CHECK_FALSE(IsTerminal());
  if (!num_illegal_items_) {
    // The action must represent the selection of the number of illegal items in
    // the cargo.
    SPIEL_CHECK_EQ(CurrentPlayer(), kSmuggler);
    num_illegal_items_ =
        sheriff_game_->DeserializeItemPlacementAction(action_id);
  } else if (bribes_.size() == inspection_feedback_.size()) {
    // The action must represent a new bribe made by the smuggler.
    SPIEL_CHECK_EQ(CurrentPlayer(), kSmuggler);
    bribes_.push_back(sheriff_game_->DeserializeBribe(action_id));
  } else {
    // The action must represent the inspection feedback returned by the
    // sheriff.
    SPIEL_CHECK_EQ(CurrentPlayer(), kSheriff);
    inspection_feedback_.push_back(
        sheriff_game_->DeserializeInspectionFeedback(action_id));
  }
}
References CurrentPlayer(), IsTerminal(), open_spiel::sheriff::kSheriff, open_spiel::sheriff::kSmuggler, SPIEL_CHECK_EQ, and SPIEL_CHECK_FALSE.
InformationStateString()
std::string open_spiel::sheriff::SheriffState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 200 of file sheriff.cc.
{
  SPIEL_CHECK_TRUE(player >= 0 && player < NumPlayers());
  std::string infostring = absl::StrCat("T=", MoveNumber(), " ");
  if (player == kSmuggler) {
    absl::StrAppend(&infostring, "num_illegal_items:");
    if (num_illegal_items_) {
      absl::StrAppend(&infostring, *num_illegal_items_);
    } else {
      absl::StrAppend(&infostring, "none");
    }
  }
  SPIEL_CHECK_GE(inspection_feedback_.size() + 1, bribes_.size());
  SPIEL_CHECK_LE(inspection_feedback_.size(), bribes_.size());
  for (size_t index = 0; index < bribes_.size(); ++index) {
    absl::StrAppend(&infostring, "/bribe:", bribes_.at(index));
    if (index < inspection_feedback_.size()) {
      absl::StrAppend(&infostring,
                      "/feedback:", inspection_feedback_.at(index));
    }
  }
  return infostring;
}
References open_spiel::sheriff::kSmuggler, open_spiel::State::MoveNumber(), open_spiel::State::NumPlayers(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_TRUE, absl::StrAppend(), and absl::StrCat().
InformationStateTensor()
void open_spiel::sheriff::SheriffState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 239 of file sheriff.cc.
{
  SPIEL_CHECK_TRUE(player >= 0 && player < NumPlayers());
  SPIEL_CHECK_EQ(values.size(), game_->InformationStateTensorSize());
  std::fill(values.begin(), values.end(), 0);
  // Two-player game.
  SPIEL_CHECK_TRUE(player == 0 || player == 1);
  int offset = 0;
  const int num_players = game_->NumPlayers();
  const Player cur_player = CurrentPlayer();
  const auto* parent_game = down_cast<const SheriffGame*>(game_.get());
  // Set a bit to indicate whose turn it is.
  if (cur_player != kTerminalPlayerId) {
    values[cur_player] = 1;
  }
  offset += num_players;
  // Set a bit to indicate whose is observing
  values[offset + player] = 1;
  offset += num_players;
  // Move number
  values[offset + MoveNumber()] = 1;
  offset += parent_game->num_rounds() + 1;
  // Number of items chosen by the smuggler
  if (player == kSmuggler) {
    int index = (num_illegal_items_ ? *num_illegal_items_ : 0);
    values[offset + index] = 1;
  }
  offset += parent_game->max_items() + 1;
  SPIEL_CHECK_GE(inspection_feedback_.size() + 1, bribes_.size());
  SPIEL_CHECK_LE(inspection_feedback_.size(), bribes_.size());
  for (size_t index = 0; index < bribes_.size(); ++index) {
    int inner_offset = index * (parent_game->max_bribe() + 2);
    values[offset + inner_offset + bribes_.at(index)] = 1;
    if (index < inspection_feedback_.size()) {
      int bool_bit = inspection_feedback_.at(index) ? 0 : 1;
      values[offset + inner_offset + parent_game->max_bribe() + 1] = bool_bit;
    }
  }
  offset += parent_game->num_rounds() * (parent_game->max_bribe() + 2);
  SPIEL_CHECK_EQ(offset, values.size());
}
References CurrentPlayer(), open_spiel::down_cast(), open_spiel::State::game_, open_spiel::sheriff::kSmuggler, open_spiel::kTerminalPlayerId, open_spiel::State::MoveNumber(), open_spiel::State::NumPlayers(), player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_TRUE, and values.
IsTerminal()
bool open_spiel::sheriff::SheriffState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 163 of file sheriff.cc.
{
  return CurrentPlayer() == kTerminalPlayerId;
}
References CurrentPlayer(), and open_spiel::kTerminalPlayerId.
Referenced by DoApplyAction(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::sheriff::SheriffState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 96 of file sheriff.cc.
{
  const SheriffGame::SheriffGameConfiguration& conf = sheriff_game_->conf;
  std::vector<Action> action_ids;
  if (IsTerminal()) {
    return {};
  } else if (!num_illegal_items_) {
    // This is the beginning of the game. The smuggles must decide how many
    // illegal items to place in the cargo, which must be an integer in the
    // range [0, conf.max_items]. The action id will correspond to the number
    // of illegal items placed in the cargo.
    action_ids.reserve(conf.max_items + 1);
    for (uint32_t num_illegal_items = 0; num_illegal_items <= conf.max_items;
         ++num_illegal_items) {
      action_ids.push_back(
          sheriff_game_->SerializeItemPlacementAction(num_illegal_items));
    }
  } else {
    // If we are here, we are inside of a bribing round. There are two cases:
    // - it is the *smuggler's* turn. This means that the bribing round has
    //   just started. The actions that the player can use correspond to the
    //   set of valid bribes, which is the range [0, conf.max_bribe].
    //
    //   The action id corresponds to the bribe amount.
    // - it is the *sheriff's* turn. The sheriff can decide to say they will
    //   _not_ inspect (action id: 0), or that they _will_ inspect the cargo
    //   (action id: 1).
    const Player player = CurrentPlayer();
    if (player == kSmuggler) {
      action_ids.reserve(conf.max_bribe + 1);
      for (uint32_t bribe = 0; bribe <= conf.max_bribe; ++bribe) {
        action_ids.push_back(sheriff_game_->SerializeBribe(bribe));
      }
    } else {
      action_ids = {sheriff_game_->SerializeInspectionFeedback(false),
                    sheriff_game_->SerializeInspectionFeedback(true)};
    }
  }
  return action_ids;
}
References CurrentPlayer(), IsTerminal(), open_spiel::sheriff::kSmuggler, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_bribe, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, and player.
Returns()
std::vector< double > open_spiel::sheriff::SheriffState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 167 of file sheriff.cc.
{
  if (!IsTerminal()) {
    return {0.0, 0.0};
  } else {
    SPIEL_CHECK_EQ(inspection_feedback_.size(), bribes_.size());
    SPIEL_CHECK_GT(inspection_feedback_.size(), 0);
    SPIEL_CHECK_TRUE(num_illegal_items_);
    const uint32_t num_illegal_items = *num_illegal_items_;
    const uint32_t bribe = bribes_.back();
    const bool sheriff_inspects = inspection_feedback_.back();
    const SheriffGame::SheriffGameConfiguration& conf = sheriff_game_->conf;
    if (sheriff_inspects) {
      if (num_illegal_items > 0) {
        // The smuggler was caught red-handed.
        return {-static_cast<double>(num_illegal_items) * conf.item_penalty,
                static_cast<double>(num_illegal_items) * conf.item_penalty};
      } else {
        // The sheriff must pay up for inspecting a legal cargo.
        return {conf.sheriff_penalty, -conf.sheriff_penalty};
      }
    } else {
      return {static_cast<double>(num_illegal_items) * conf.item_value - bribe,
              static_cast<double>(bribe)};
    }
  }
}
References IsTerminal(), open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::item_penalty, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::item_value, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::sheriff_penalty, SPIEL_CHECK_EQ, SPIEL_CHECK_GT, and SPIEL_CHECK_TRUE.
ToString()
std::string open_spiel::sheriff::SheriffState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 145 of file sheriff.cc.
{
  if (!num_illegal_items_) {
    return "Initial game state (smuggler hasn't decided the number of illegal "
           "cargo items yet)";
  } else {
    std::string state_str;
    absl::StrAppend(&state_str,
                    "Num illegal items in cargo: ", *num_illegal_items_, "\n");
    absl::StrAppend(&state_str, "Bribes  : ");
    StrAppendVector(&state_str, bribes_);
    absl::StrAppend(&state_str, "\nFeedback: ");
    StrAppendVector(&state_str, inspection_feedback_);
    return state_str;
  }
}
References absl::StrAppend().
UndoAction()
void open_spiel::sheriff::SheriffState::UndoAction (Player player, Action action_id) override virtual
Reimplemented from open_spiel::State.
Definition at line 291 of file sheriff.cc.
{
  SPIEL_CHECK_TRUE(!history_.empty() &&
                   (history_.back() == PlayerAction{player, action_id}));
  history_.pop_back();
  --move_number_;
  if (!bribes_.empty()) {
    if (bribes_.size() == inspection_feedback_.size()) {
      // The last action must have been for the sheriff to return feedback about
      // whether or not the sheriff would inspect the cargo.
      inspection_feedback_.pop_back();
    } else {
      // The last action must have been for the smuggler to offer a new bribe.
      bribes_.pop_back();
    }
  } else {
    // If there are no bribes yet, then the only possibility is that the game
    // has just started and the only action so far was for the smuggler to
    // select the number of illegal items to place into the smuggler's cargo.
    SPIEL_CHECK_TRUE(num_illegal_items_);
    num_illegal_items_ = absl::nullopt;
  }
}
References open_spiel::State::history_, open_spiel::State::move_number_, and SPIEL_CHECK_TRUE.
The documentation for this class was generated from the following files:
open_spiel/games/sheriff/sheriff.h
open_spiel/games/sheriff/sheriff.cc