open spiel: open_spiel::solitaire::SolitaireState Class Reference
open_spiel::solitaire::SolitaireState Class Reference
#include <solitaire.h>
Public Member Functions
SolitaireState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const override
std::unique_ptr< State > Clone () const override
bool IsTerminal () const override
bool IsChanceNode () const override
std::string ToString () const override
std::string ActionToString (Player player, Action action_id) const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
void DoApplyAction (Action action) override
std::vector< double > Returns () const override
std::vector< double > Rewards () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::vector< Card > Targets (const absl::optional< LocationType > &location=LocationType::kMissing) const
std::vector< Card > Sources (const absl::optional< LocationType > &location=LocationType::kMissing) const
std::vector< Move > CandidateMoves () const
Pile * GetPile (const Card &card)
const Pile * GetPile (const Card &card) const
void MoveCards (const Move &move)
bool IsReversible (const Card &source, const Pile *source_pile) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 259 of file solitaire.h.
Constructor & Destructor Documentation
SolitaireState()
open_spiel::solitaire::SolitaireState::SolitaireState (std::shared_ptr< const Game > game) explicit
Definition at line 944 of file solitaire.cc.
    : State(game), waste_() {
  // Extract parameters from `game`
  auto parameters = game->GetParameters();
  is_colored_ = parameters.at("is_colored").bool_value();
  depth_limit_ = parameters.at("depth_limit").int_value();
  // Create foundations_
  for (const auto& suit_ : kSuits) {
    foundations_.emplace_back(kSuitToPile.at(suit_), suit_);
  }
  // Create tableaus_
  for (int i = 1; i <= 7; i++) {
    // Create `i` hidden_ cards_
    std::vector<Card> cards_to_add;
    for (int j = 1; j <= i; j++) {
      cards_to_add.emplace_back(true, SuitType::kHidden, RankType::kHidden,
                                LocationType::kTableau);
    }
    // Create a new tableau and add cards_
    auto tableau = Tableau(kIntToPile.at(i));
    tableau.SetCards(cards_to_add);
    // Add resulting tableau to tableaus_
    tableaus_.push_back(tableau);
  }
  // Create waste_
  for (int i = 1; i <= 24; i++) {
    auto new_card =
        Card(true, SuitType::kHidden, RankType::kHidden, LocationType::kWaste);
    waste_.Extend({new_card});
  }
}
References open_spiel::solitaire::Pile::Extend(), i, open_spiel::solitaire::kHidden, open_spiel::solitaire::kTableau, and open_spiel::solitaire::kWaste.
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::solitaire::SolitaireState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 1046 of file solitaire.cc.
{
  if (action_id == kEnd) {
    return "kEnd";
  } else if (action_id >= kRevealStart && action_id <= kRevealEnd) {
    auto revealed_card = Card(static_cast<int>(action_id));
    std::string result;
    absl::StrAppend(&result, "Reveal", revealed_card.ToString(is_colored_));
    return result;
  } else if (action_id >= kMoveStart && action_id <= kMoveEnd) {
    auto move = Move(action_id);
    return move.ToString(is_colored_);
  } else {
    return "Missing Action";
  }
}
References absl::StrAppend().
CandidateMoves()
std::vector< Move > open_spiel::solitaire::SolitaireState::CandidateMoves () const
Definition at line 1365 of file solitaire.cc.
{
  std::vector<Move> candidate_moves;
  std::vector<Card> targets = Targets();
  std::vector<Card> sources = Sources();
  bool found_empty_tableau = false;
  for (auto& target : targets) {
    if (target.GetSuit() == SuitType::kNone &&
        target.GetRank() == RankType::kNone) {
      if (found_empty_tableau) {
        continue;
      } else {
        found_empty_tableau = true;
      }
    }
    for (auto& source : target.LegalChildren()) {
      if (std::find(sources.begin(), sources.end(), source) != sources.end()) {
        auto* source_pile = GetPile(source);
        if (target.GetLocation() == LocationType::kFoundation &&
            source_pile->GetType() == LocationType::kTableau) {
          if (source_pile->GetLastCard() == source) {
            candidate_moves.emplace_back(target, source);
          }
        } else if (source.GetRank() == RankType::kK &&
                   target.GetSuit() == SuitType::kNone &&
                   target.GetRank() == RankType::kNone) {
          // Check is source is not a bottom
          if (source_pile->GetType() == LocationType::kWaste ||
              (source_pile->GetType() == LocationType::kTableau &&
               !(source_pile->GetFirstCard() == source))) {
            candidate_moves.emplace_back(target, source);
          }
        } else {
          candidate_moves.emplace_back(target, source);
        }
      } else {
        continue;
      }
    }
  }
  return candidate_moves;
}
References GetPile(), open_spiel::solitaire::kFoundation, open_spiel::solitaire::kK, open_spiel::solitaire::kNone, open_spiel::solitaire::kTableau, open_spiel::solitaire::kWaste, Sources(), and Targets().
Referenced by LegalActions().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::solitaire::SolitaireState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 1227 of file solitaire.cc.
{
  std::vector<std::pair<Action, double>> outcomes;
  const double p = 1.0 / (52 - revealed_cards_.size());
  for (int i = 1; i <= 52; i++) {
    if (std::find(revealed_cards_.begin(), revealed_cards_.end(), i) ==
        revealed_cards_.end()) {
      outcomes.emplace_back(i, p);
    }
  }
  return outcomes;
}
References i.
Clone()
std::unique_ptr< State > open_spiel::solitaire::SolitaireState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 991 of file solitaire.cc.
{
  return std::unique_ptr<State>(new SolitaireState(*this));
}
References SolitaireState().
CurrentPlayer()
Player open_spiel::solitaire::SolitaireState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 981 of file solitaire.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  } else if (IsChanceNode()) {
    return kChancePlayerId;
  } else {
    return kPlayerId;
  }
}
References IsChanceNode(), IsTerminal(), open_spiel::kChancePlayerId, and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::solitaire::SolitaireState::DoApplyAction (Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 1127 of file solitaire.cc.
{
  if (action == kEnd) {
    is_finished_ = true;
    current_rewards_ = 0;
  } else if (action >= kRevealStart && action <= kRevealEnd) {
    auto revealed_card = Card(static_cast<int>(action));
    bool found_card = false;
    for (auto& tableau : tableaus_) {
      if (!tableau.GetIsEmpty() && tableau.GetLastCard().GetHidden()) {
        tableau.Reveal(revealed_card);
        card_map_.insert_or_assign(tableau.GetLastCard(), tableau.GetID());
        found_card = true;
        break;
      }
    }
    if (!found_card && !waste_.GetIsEmpty()) {
      waste_.Reveal(revealed_card);
      card_map_.insert_or_assign(revealed_card, waste_.GetID());
    }
    revealed_cards_.push_back(action);
  } else if (action >= kMoveStart && action <= kMoveEnd) {
    Move selected_move = Move(action);
    is_reversible_ = IsReversible(selected_move.GetSource(),
                                  GetPile(selected_move.GetSource()));
    if (is_reversible_) {
      std::string current_observation = ObservationString(0);
      previous_states_.insert(hasher(current_observation));
    } else {
      previous_states_.clear();
    }
    MoveCards(selected_move);
    current_returns_ += current_rewards_;
  }
  ++current_depth_;
  if (current_depth_ >= depth_limit_) {
    is_finished_ = true;
  }
}
References action, open_spiel::solitaire::Pile::GetID(), open_spiel::solitaire::Pile::GetIsEmpty(), GetPile(), open_spiel::solitaire::Move::GetSource(), open_spiel::solitaire::hasher, IsReversible(), MoveCards(), open_spiel::State::ObservationString(), and open_spiel::solitaire::Waste::Reveal().
GetPile() [1/2]
Pile * open_spiel::solitaire::SolitaireState::GetPile (const Card & card)
Definition at line 1331 of file solitaire.cc.
{
  PileID pile_id = PileID::kMissing;
  if (card.GetRank() == RankType::kNone) {
    if (card.GetSuit() == SuitType::kNone) {
      for (auto& tableau : tableaus_) {
        if (tableau.GetIsEmpty()) {
          return &tableau;
        }
      }
    } else if (card.GetSuit() != SuitType::kHidden) {
      for (auto& foundation : foundations_) {
        if (foundation.GetSuit() == card.GetSuit()) {
          return &foundation;
        }
      }
    } else {
      SpielFatalError("The pile containing the card wasn't found");
    }
  } else {
    pile_id = card_map_.at(card);
  }
  if (pile_id == PileID::kWaste) {
    return &waste_;
  } else if (pile_id >= PileID::kSpades && pile_id <= PileID::kDiamonds) {
    return &foundations_.at(static_cast<int>(pile_id) - 1);
  } else if (pile_id >= PileID::k1stTableau && pile_id <= PileID::k7thTableau) {
    return &tableaus_.at(static_cast<int>(pile_id) - 5);
  } else {
    SpielFatalError("The pile containing the card wasn't found");
  }
}
References open_spiel::solitaire::k1stTableau, open_spiel::solitaire::k7thTableau, open_spiel::solitaire::kDiamonds, open_spiel::solitaire::kHidden, open_spiel::solitaire::kMissing, open_spiel::solitaire::kNone, open_spiel::solitaire::kSpades, open_spiel::solitaire::kWaste, and open_spiel::SpielFatalError().
Referenced by CandidateMoves(), DoApplyAction(), LegalActions(), and MoveCards().
GetPile() [2/2]
const Pile * open_spiel::solitaire::SolitaireState::GetPile (const Card & card) const
Definition at line 1297 of file solitaire.cc.
{
  PileID pile_id = PileID::kMissing;
  if (card.GetRank() == RankType::kNone) {
    if (card.GetSuit() == SuitType::kNone) {
      for (auto& tableau : tableaus_) {
        if (tableau.GetIsEmpty()) {
          return &tableau;
        }
      }
    } else if (card.GetSuit() != SuitType::kHidden) {
      for (auto& foundation : foundations_) {
        if (foundation.GetSuit() == card.GetSuit()) {
          return &foundation;
        }
      }
    } else {
      SpielFatalError("The pile containing the card wasn't found");
    }
  } else {
    pile_id = card_map_.at(card);
  }
  if (pile_id == PileID::kWaste) {
    return &waste_;
  } else if (pile_id >= PileID::kSpades && pile_id <= PileID::kDiamonds) {
    return &foundations_.at(static_cast<int>(pile_id) - 1);
  } else if (pile_id >= PileID::k1stTableau && pile_id <= PileID::k7thTableau) {
    return &tableaus_.at(static_cast<int>(pile_id) - 5);
  } else {
    SpielFatalError("The pile containing the card wasn't found");
  }
}
References open_spiel::solitaire::k1stTableau, open_spiel::solitaire::k7thTableau, open_spiel::solitaire::kDiamonds, open_spiel::solitaire::kHidden, open_spiel::solitaire::kMissing, open_spiel::solitaire::kNone, open_spiel::solitaire::kSpades, open_spiel::solitaire::kWaste, and open_spiel::SpielFatalError().
InformationStateString()
std::string open_spiel::solitaire::SolitaireState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 1063 of file solitaire.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsChanceNode()
bool open_spiel::solitaire::SolitaireState::IsChanceNode () const override virtual
Reimplemented from open_spiel::State.
Definition at line 997 of file solitaire.cc.
{
  for (const auto& tableau : tableaus_) {
    if (!tableau.GetIsEmpty() && tableau.GetLastCard().GetHidden()) {
      return true;
    }
  }
  if (!waste_.GetIsEmpty()) {
    for (const auto& card : waste_.GetCards()) {
      if (card.GetHidden()) {
        return true;
      }
    }
  }
  return false;
}
References open_spiel::solitaire::Pile::GetCards(), and open_spiel::solitaire::Pile::GetIsEmpty().
Referenced by CurrentPlayer(), and LegalActions().
IsReversible()
bool open_spiel::solitaire::SolitaireState::IsReversible (const Card & source, const Pile * source_pile) const
Definition at line 1449 of file solitaire.cc.
{
  switch (source.GetLocation()) {
    case LocationType::kWaste: {
      return false;
    }
    case LocationType::kFoundation: {
      return true;
    }
    case LocationType::kTableau: {
      // Move is irreversible if its source is a bottom card or over a hidden
      // card. Basically if it's the first non-hidden_ card in the pile/tableau.
      auto it = std::find_if(source_pile->GetCards().begin(),
                             source_pile->GetCards().end(),
                             [](const Card& card) { return card.GetHidden(); });
      return !(*it == source);
    }
    default: {
      // Returns false if the source card is not in the waste, foundations,
      // or tableaus
      return false;
    }
  }
}
References open_spiel::solitaire::Pile::GetCards(), open_spiel::solitaire::Card::GetLocation(), open_spiel::solitaire::kFoundation, open_spiel::solitaire::kTableau, and open_spiel::solitaire::kWaste.
Referenced by DoApplyAction(), and LegalActions().
IsTerminal()
bool open_spiel::solitaire::SolitaireState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 995 of file solitaire.cc.
{ return is_finished_; }
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::solitaire::SolitaireState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 1182 of file solitaire.cc.
{
  if (IsTerminal()) {
    return {};
  } else if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else {
    std::vector<Action> legal_actions;
    if (is_reversible_) {
      // If the state is reversible, we need to check each move to see if it is
      // too.
      for (const auto& move : CandidateMoves()) {
        if (IsReversible(move.GetSource(), GetPile(move.GetSource()))) {
          auto action_id = move.ActionId();
          auto child = Child(action_id);
          if (child->CurrentPlayer() == kChancePlayerId) {
            legal_actions.push_back(action_id);
          } else {
            auto child_hash = hasher(child->ObservationString());
            if (previous_states_.count(child_hash) == 0) {
              legal_actions.push_back(action_id);
            }
          }
        } else {
          legal_actions.push_back(move.ActionId());
        }
      }
    } else {
      // If the state isn't reversible, all candidate moves are legal
      for (const auto& move : CandidateMoves()) {
        legal_actions.push_back(move.ActionId());
      }
    }
    if (!legal_actions.empty()) {
      std::sort(legal_actions.begin(), legal_actions.end());
    } else {
      legal_actions.push_back(kEnd);
    }
    return legal_actions;
  }
}
References CandidateMoves(), open_spiel::State::Child(), GetPile(), open_spiel::solitaire::hasher, IsChanceNode(), IsReversible(), IsTerminal(), open_spiel::kChancePlayerId, and open_spiel::State::LegalChanceOutcomes().
MoveCards()
void open_spiel::solitaire::SolitaireState::MoveCards (const Move & move)
Definition at line 1409 of file solitaire.cc.
{
  Card target = move.GetTarget();
  Card source = move.GetSource();
  auto* target_pile = GetPile(target);
  auto* source_pile = GetPile(source);
  std::vector<Card> split_cards = source_pile->Split(source);
  for (auto& card : split_cards) {
    card_map_.insert_or_assign(card, target_pile->GetID());
    target_pile->Extend({card});
  }
  // Calculate rewards/returns for this move in the current state
  double move_reward = 0.0;
  // Reward for moving a card to or from a foundation
  if (target_pile->GetType() == LocationType::kFoundation) {
    // Adds points for moving TO a foundation
    move_reward += kFoundationPoints.at(source.GetRank());
  } else if (source_pile->GetType() == LocationType::kFoundation) {
    // Subtracts points for moving AWAY from a foundation
    move_reward -= kFoundationPoints.at(source.GetRank());
  }
  // Reward for revealing a hidden_ card
  if (source_pile->GetType() == LocationType::kTableau &&
      !source_pile->GetIsEmpty() && source_pile->GetLastCard().GetHidden()) {
    move_reward += 20.0;
  }
  // Reward for moving a card from the waste_
  if (source_pile->GetType() == LocationType::kWaste) {
    move_reward += 20.0;
  }
  // Add current rewards to current returns
  current_rewards_ = move_reward;
}
References GetPile(), open_spiel::solitaire::Card::GetRank(), open_spiel::solitaire::kFoundation, open_spiel::solitaire::kTableau, and open_spiel::solitaire::kWaste.
Referenced by DoApplyAction().
ObservationString()
std::string open_spiel::solitaire::SolitaireState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 1069 of file solitaire.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::solitaire::SolitaireState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 1075 of file solitaire.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  std::fill(values.begin(), values.end(), 0.0);
  auto ptr = values.begin();
  for (const auto& foundation : foundations_) {
    if (foundation.GetIsEmpty()) {
      ptr[0] = 1;
    } else {
      auto last_rank = foundation.GetLastCard().GetRank();
      if (last_rank >= RankType::kA && last_rank <= RankType::kK) {
        ptr[static_cast<int>(last_rank)] = 1;
      }
    }
    ptr += kFoundationTensorLength;
  }
  for (const auto& tableau : tableaus_) {
    if (tableau.GetIsEmpty()) {
      ptr[7] = 1.0;
    } else {
      int num_hidden_cards = 0;
      for (const auto& card : tableau.GetCards()) {
        if (card.GetHidden() && num_hidden_cards <= kMaxHiddenCard) {
          ptr[num_hidden_cards] = 1.0;
          ++num_hidden_cards;
        } else {
          auto tensor_index = card.GetIndex() + kMaxHiddenCard;
          ptr[tensor_index] = 1.0;
        }
      }
    }
    ptr += kTableauTensorLength;
  }
  for (auto& card : waste_.GetCards()) {
    if (card.GetHidden()) {
      ptr[0] = 1.0;
    } else {
      auto tensor_index = card.GetIndex();
      ptr[tensor_index] = 1.0;
    }
    ptr += kWasteTensorLength;
  }
  SPIEL_CHECK_LE(ptr, values.end());
}
References open_spiel::State::game_, open_spiel::solitaire::Pile::GetCards(), open_spiel::solitaire::kA, open_spiel::solitaire::kK, open_spiel::State::num_players_, player, ptr, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::solitaire::SolitaireState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 1170 of file solitaire.cc.
{
  // Returns the sum of rewards up to and including the most recent state
  // transition.
  return {current_returns_};
}
Rewards()
std::vector< double > open_spiel::solitaire::SolitaireState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 1176 of file solitaire.cc.
{
  // Should be the reward for the action that created this state, not the action
  // applied to this state
  return {current_rewards_};
}
Sources()
std::vector< Card > open_spiel::solitaire::SolitaireState::Sources (const absl::optional< LocationType > & location = LocationType::kMissing) const
Definition at line 1267 of file solitaire.cc.
{
  LocationType loc = location.value_or(LocationType::kMissing);
  std::vector<Card> sources;
  if (loc == LocationType::kTableau || loc == LocationType::kMissing) {
    for (const auto& tableau : tableaus_) {
      std::vector<Card> current_sources = tableau.Sources();
      sources.insert(sources.end(), current_sources.begin(),
                     current_sources.end());
    }
  }
  if (loc == LocationType::kFoundation || loc == LocationType::kMissing) {
    for (const auto& foundation : foundations_) {
      std::vector<Card> current_sources = foundation.Sources();
      sources.insert(sources.end(), current_sources.begin(),
                     current_sources.end());
    }
  }
  if (loc == LocationType::kWaste || loc == LocationType::kMissing) {
    std::vector<Card> current_sources = waste_.Sources();
    sources.insert(sources.end(), current_sources.begin(),
                   current_sources.end());
  }
  return sources;
}
References open_spiel::solitaire::kFoundation, open_spiel::solitaire::kMissing, open_spiel::solitaire::kTableau, open_spiel::solitaire::kWaste, open_spiel::solitaire::Waste::Sources(), and absl::optional< T >::value_or().
Referenced by CandidateMoves(), and ToString().
Targets()
std::vector< Card > open_spiel::solitaire::SolitaireState::Targets (const absl::optional< LocationType > & location = LocationType::kMissing) const
Definition at line 1243 of file solitaire.cc.
{
  LocationType loc = location.value_or(LocationType::kMissing);
  std::vector<Card> targets;
  if (loc == LocationType::kTableau || loc == LocationType::kMissing) {
    for (const auto& tableau : tableaus_) {
      std::vector<Card> current_targets = tableau.Targets();
      targets.insert(targets.end(), current_targets.begin(),
                     current_targets.end());
    }
  }
  if (loc == LocationType::kFoundation || loc == LocationType::kMissing) {
    for (const auto& foundation : foundations_) {
      std::vector<Card> current_targets = foundation.Targets();
      targets.insert(targets.end(), current_targets.begin(),
                     current_targets.end());
    }
  }
  return targets;
}
References open_spiel::solitaire::kFoundation, open_spiel::solitaire::kMissing, open_spiel::solitaire::kTableau, and absl::optional< T >::value_or().
Referenced by CandidateMoves(), and ToString().
ToString()
std::string open_spiel::solitaire::SolitaireState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 1015 of file solitaire.cc.
{
  std::string result;
  absl::StrAppend(&result, "WASTE       : ", waste_.ToString(is_colored_));
  absl::StrAppend(&result, "\nFOUNDATIONS : ");
  for (const auto& foundation : foundations_) {
    absl::StrAppend(&result, foundation.Targets()[0].ToString(is_colored_),
                    " ");
  }
  absl::StrAppend(&result, "\nTABLEAUS    : ");
  for (const auto& tableau : tableaus_) {
    if (!tableau.GetIsEmpty()) {
      absl::StrAppend(&result, "\n", tableau.ToString(is_colored_));
    }
  }
  absl::StrAppend(&result, "\nTARGETS : ");
  for (const auto& card : Targets()) {
    absl::StrAppend(&result, card.ToString(is_colored_), " ");
  }
  absl::StrAppend(&result, "\nSOURCES : ");
  for (const auto& card : Sources()) {
    absl::StrAppend(&result, card.ToString(is_colored_), " ");
  }
  return result;
}
References Sources(), absl::StrAppend(), Targets(), and open_spiel::solitaire::Pile::ToString().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/solitaire/solitaire.h
open_spiel/games/solitaire/solitaire.cc