open spiel: absl::log_internal::ProtoField Class Reference
absl::log_internal::ProtoField Class Reference final
#include <proto.h>
Public Member Functions
bool DecodeFrom (absl::Span< const char > *data)
uint64_t tag () const
WireType type () const
double double_value () const
float float_value () const
int32_t int32_value () const
int64_t int64_value () const
int32_t sint32_value () const
int64_t sint64_value () const
uint32_t uint32_value () const
uint64_t uint64_value () const
bool bool_value () const
absl::Span< const char > bytes_value () const
absl::string_view string_value () const
uint64_t encoded_length () const
Detailed Description
Definition at line 230 of file proto.h.
Member Function Documentation
bool_value()
bool absl::log_internal::ProtoField::bool_value () const inline
Definition at line 258 of file proto.h.
{ return value_ != 0; }
bytes_value()
absl::Span< const char > absl::log_internal::ProtoField::bytes_value () const inline
Definition at line 265 of file proto.h.
{ return data_; }
Referenced by absl::log_internal::LogMessage::LogMessageData::FinalizeEncodingAndFormat(), and string_value().
DecodeFrom()
bool absl::log_internal::ProtoField::DecodeFrom (absl::Span< const char > * data)
Definition at line 192 of file proto.cc.
{
  if (data->empty()) return false;
  const uint64_t tag_type = DecodeVarint(data);
  tag_ = tag_type >> 3;
  type_ = static_cast<WireType>(tag_type & 0x07);
  switch (type_) {
    case WireType::kVarint:
      value_ = DecodeVarint(data);
      break;
    case WireType::k64Bit:
      value_ = Decode64Bit(data);
      break;
    case WireType::kLengthDelimited: {
      value_ = DecodeVarint(data);
      data_ = data->subspan(
          0, static_cast<size_t>(std::min<uint64_t>(value_, data->size())));
      data->remove_prefix(data_.size());
      break;
    }
    case WireType::k32Bit:
      value_ = Decode32Bit(data);
      break;
  }
  return true;
}
References absl::log_internal::k32Bit, absl::log_internal::k64Bit, absl::log_internal::kLengthDelimited, absl::log_internal::kVarint, absl::Span< T >::remove_prefix(), absl::Span< T >::size(), and absl::Span< T >::subspan().
Referenced by absl::log_internal::LogMessage::LogMessageData::FinalizeEncodingAndFormat().
double_value()
double absl::log_internal::ProtoField::double_value () const inline
Definition at line 242 of file proto.h.
{ return absl::bit_cast<double>(value_); }
References absl::bit_cast().
encoded_length()
uint64_t absl::log_internal::ProtoField::encoded_length () const inline
Definition at line 273 of file proto.h.
{ return value_; }
float_value()
float absl::log_internal::ProtoField::float_value () const inline
Definition at line 243 of file proto.h.
{
    return absl::bit_cast<float>(static_cast<uint32_t>(value_));
  }
References absl::bit_cast().
int32_value()
int32_t absl::log_internal::ProtoField::int32_value () const inline
Definition at line 246 of file proto.h.
{ return static_cast<int32_t>(value_); }
int64_value()
int64_t absl::log_internal::ProtoField::int64_value () const inline
Definition at line 247 of file proto.h.
{ return static_cast<int64_t>(value_); }
sint32_value()
int32_t absl::log_internal::ProtoField::sint32_value () const inline
Definition at line 248 of file proto.h.
{
    if (value_ % 2) return static_cast<int32_t>(0 - ((value_ - 1) / 2) - 1);
    return static_cast<int32_t>(value_ / 2);
  }
sint64_value()
int64_t absl::log_internal::ProtoField::sint64_value () const inline
Definition at line 252 of file proto.h.
{
    if (value_ % 2) return 0 - ((value_ - 1) / 2) - 1;
    return value_ / 2;
  }
string_value()
absl::string_view absl::log_internal::ProtoField::string_value () const inline
Definition at line 266 of file proto.h.
{
    const auto data = bytes_value();
    return absl::string_view(data.data(), data.size());
  }
References bytes_value().
tag()
uint64_t absl::log_internal::ProtoField::tag () const inline
Definition at line 235 of file proto.h.
{ return tag_; }
Referenced by absl::log_internal::LogMessage::LogMessageData::FinalizeEncodingAndFormat().
type()
WireType absl::log_internal::ProtoField::type () const inline
Definition at line 236 of file proto.h.
{ return type_; }
Referenced by absl::log_internal::LogMessage::LogMessageData::FinalizeEncodingAndFormat().
uint32_value()
uint32_t absl::log_internal::ProtoField::uint32_value () const inline
Definition at line 256 of file proto.h.
{ return static_cast<uint32_t>(value_); }
uint64_value()
uint64_t absl::log_internal::ProtoField::uint64_value () const inline
Definition at line 257 of file proto.h.
{ return value_; }
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/log/internal/proto.h
open_spiel/abseil-cpp/absl/log/internal/proto.cc