open spiel: open_spiel::algorithms::AFCCEGame Class Reference
open_spiel::algorithms::AFCCEGame Class Reference
#include <afcce.h>
Public Member Functions
AFCCEGame (std::shared_ptr< const Game > game, CorrDistConfig config, const CorrelationDevice &mu)
std::unique_ptr< State > NewInitialState () const override
int NumDistinctActions () const override
int FollowAction () const
int DefectAction () const
Public Member Functions inherited from open_spiel::WrappedGame
WrappedGame (std::shared_ptr< const Game > game, GameType game_type, GameParameters game_parameters)
int NumDistinctActions () const override
int MaxChanceOutcomes () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
absl::optional< double > UtilitySum () const override
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
TensorLayout InformationStateTensorLayout () const override
TensorLayout ObservationTensorLayout () const override
std::vector< int > PolicyTensorShape () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
int InformationStateTensorSize () const
int ObservationTensorSize () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::WrappedGame
std::shared_ptr< const Game > game_
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 83 of file afcce.h.
Constructor & Destructor Documentation
AFCCEGame()
open_spiel::algorithms::AFCCEGame::AFCCEGame (std::shared_ptr< const Game > game, CorrDistConfig config, const CorrelationDevice & mu) inline
Definition at line 85 of file afcce.h.
      : WrappedGame(game, game->GetType(), game->GetParameters()),
        config_(config),
        mu_(mu),
        orig_num_distinct_actions_(game->NumDistinctActions()) {}
Member Function Documentation
DefectAction()
int open_spiel::algorithms::AFCCEGame::DefectAction () const inline
Definition at line 104 of file afcce.h.
{ return orig_num_distinct_actions_ + 1; }
Referenced by NewInitialState().
FollowAction()
int open_spiel::algorithms::AFCCEGame::FollowAction () const inline
Definition at line 103 of file afcce.h.
{ return orig_num_distinct_actions_; }
Referenced by NewInitialState().
NewInitialState()
std::unique_ptr< State > open_spiel::algorithms::AFCCEGame::NewInitialState () const inline override virtual
Implements open_spiel::WrappedGame.
Definition at line 92 of file afcce.h.
{
    return std::make_unique<AFCCEState>(shared_from_this(),
                                        game_->NewInitialState(), config_, mu_,
                                        FollowAction(), DefectAction());
  }
References DefectAction(), FollowAction(), and open_spiel::WrappedGame::game_.
NumDistinctActions()
int open_spiel::algorithms::AFCCEGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 98 of file afcce.h.
{
    // 2 extra actions: cooperate/follow or defect
    return orig_num_distinct_actions_ + 2;
  }
The documentation for this class was generated from the following file:
open_spiel/algorithms/corr_dist/afcce.h