open spiel: open_spiel::coop_box_pushing::CoopBoxPushingState Class Reference
open_spiel::coop_box_pushing::CoopBoxPushingState Class Reference
#include <coop_box_pushing.h>
Public Member Functions
CoopBoxPushingState (std::shared_ptr< const Game > game, int horizon, bool fully_observable)
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::vector< double > Rewards () const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
Player CurrentPlayer () const override
std::unique_ptr< State > Clone () const override
ActionsAndProbs ChanceOutcomes () const override
void Reset (const GameParameters &params)
std::vector< Action > LegalActions (Player player) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
void DoApplyActions (const std::vector< Action > &actions) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 68 of file coop_box_pushing.h.
Constructor & Destructor Documentation
CoopBoxPushingState()
open_spiel::coop_box_pushing::CoopBoxPushingState::CoopBoxPushingState (std::shared_ptr< const Game > game, int horizon, bool fully_observable)
Definition at line 155 of file coop_box_pushing.cc.
    : SimMoveState(game),
      total_rewards_(0),
      horizon_(horizon),
      cur_player_(kSimultaneousPlayerId),
      total_moves_(0),
      initiative_(0),
      win_(false),
      fully_observable_(fully_observable),
      reward_(0),
      action_status_(
          {ActionStatusType::kUnresolved, ActionStatusType::kUnresolved}) {
  field_.resize(kRows * kCols, '.');
  // Small boxes.
  SetField({3, 1}, 'b');
  SetField({3, 6}, 'b');
  // Big box.
  SetField({3, 3}, 'B');
  SetField({3, 4}, 'B');
  // Agents.
  SetPlayer({6, 1}, 0, OrientationType::kEast);
  SetPlayer({6, 6}, 1, OrientationType::kWest);
}
References open_spiel::coop_box_pushing::kUnresolved.
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::coop_box_pushing::CoopBoxPushingState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 183 of file coop_box_pushing.cc.
{
  return ::open_spiel::coop_box_pushing::ActionToString(action);
}
References action.
ChanceOutcomes()
ActionsAndProbs open_spiel::coop_box_pushing::CoopBoxPushingState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 381 of file coop_box_pushing.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  if (action_status_[0] == ActionStatusType::kUnresolved ||
      action_status_[1] == ActionStatusType::kUnresolved) {
    // Determine success (0) or failure (1) of a player's action.
    return {std::pair<Action, double>(0, 0.9),
            std::pair<Action, double>(1, 0.1)};
  } else {
    // Determine initiative outcomes (2 and 3)
    return {std::pair<Action, double>(2, 0.5),
            std::pair<Action, double>(3, 0.5)};
  }
}
References open_spiel::State::IsChanceNode(), open_spiel::coop_box_pushing::kUnresolved, and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::coop_box_pushing::CoopBoxPushingState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 540 of file coop_box_pushing.cc.
{
  return std::unique_ptr<State>(new CoopBoxPushingState(*this));
}
References CoopBoxPushingState().
CurrentPlayer()
Player open_spiel::coop_box_pushing::CoopBoxPushingState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 82 of file coop_box_pushing.h.
{
    return IsTerminal() ? kTerminalPlayerId : cur_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::coop_box_pushing::CoopBoxPushingState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 331 of file coop_box_pushing.cc.
{
  reward_ = 0;
  if (IsSimultaneousNode()) return ApplyFlatJointAction(action);
  if (action == kChanceSuccess) {
    // Success.
    if (action_status_[0] == ActionStatusType::kUnresolved) {
      action_status_[0] = ActionStatusType::kSuccess;
    } else if (action_status_[1] == ActionStatusType::kUnresolved) {
      action_status_[1] = ActionStatusType::kSuccess;
    } else {
      SpielFatalError(absl::StrCat("Invalid chance move case: ", action));
    }
  } else if (action == kChanceFail) {
    // Fail!
    if (action_status_[0] == ActionStatusType::kUnresolved) {
      action_status_[0] = ActionStatusType::kFail;
    } else if (action_status_[1] == ActionStatusType::kUnresolved) {
      action_status_[1] = ActionStatusType::kFail;
    } else {
      SpielFatalError(absl::StrCat("Invalid chance move case: ", action));
    }
  } else if (action == kChanceInit1) {
    // Player 1 moves first.
    initiative_ = 0;
    ResolveMoves();
  } else {
    // Player 2 moves first.
    initiative_ = 1;
    ResolveMoves();
  }
}
References action, open_spiel::SimMoveState::ApplyFlatJointAction(), open_spiel::State::IsSimultaneousNode(), open_spiel::coop_box_pushing::kFail, open_spiel::coop_box_pushing::kSuccess, open_spiel::coop_box_pushing::kUnresolved, open_spiel::SpielFatalError(), and absl::StrCat().
DoApplyActions()
void open_spiel::coop_box_pushing::CoopBoxPushingState::DoApplyActions (const std::vector< Action > & actions) override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 207 of file coop_box_pushing.cc.
{
  SPIEL_CHECK_EQ(actions.size(), 2);
  SPIEL_CHECK_EQ(cur_player_, kSimultaneousPlayerId);
  moves_[0] = ToAction(actions[0]);
  moves_[1] = ToAction(actions[1]);
  cur_player_ = kChancePlayerId;
}
References open_spiel::kChancePlayerId, open_spiel::kSimultaneousPlayerId, and SPIEL_CHECK_EQ.
IsTerminal()
bool open_spiel::coop_box_pushing::CoopBoxPushingState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 464 of file coop_box_pushing.cc.
{
  return (total_moves_ >= horizon_ || win_);
}
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::coop_box_pushing::CoopBoxPushingState::LegalActions (Player player) const override virtual
Implements open_spiel::SimMoveState.
Definition at line 364 of file coop_box_pushing.cc.
{
  if (player == kSimultaneousPlayerId) {
    return LegalFlatJointActions();
  } else if (IsTerminal()) {
    return {};
  } else if (IsChanceNode()) {
    if (action_status_[0] == ActionStatusType::kUnresolved ||
        action_status_[1] == ActionStatusType::kUnresolved) {
      return {0, 1};
    } else {
      return {2, 3};
    }
  }
  // All the actions are legal at every state.
  return {0, 1, 2, 3};
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::kSimultaneousPlayerId, open_spiel::coop_box_pushing::kUnresolved, open_spiel::SimMoveState::LegalFlatJointActions(), and player.
ObservationString()
std::string open_spiel::coop_box_pushing::CoopBoxPushingState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 440 of file coop_box_pushing.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (fully_observable_) {
    return ToString();
  } else {
    ObservationType obs = PartialObservation(player);
    switch (obs) {
      case kEmptyFieldObs:
        return "field";
      case kWallObs:
        return "wall";
      case kOtherAgentObs:
        return "other agent";
      case kSmallBoxObs:
        return "small box";
      case kBigBoxObs:
        return "big box";
      default:
        SpielFatalError("Unrecognized observation!");
    }
  }
}
References open_spiel::coop_box_pushing::kBigBoxObs, open_spiel::coop_box_pushing::kEmptyFieldObs, open_spiel::coop_box_pushing::kOtherAgentObs, open_spiel::coop_box_pushing::kSmallBoxObs, open_spiel::coop_box_pushing::kWallObs, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and ToString().
ObservationTensor()
void open_spiel::coop_box_pushing::CoopBoxPushingState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 518 of file coop_box_pushing.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (fully_observable_) {
    TensorView<3> view(values, {kCellStates, kRows, kCols}, true);
    for (int r = 0; r < kRows; r++) {
      for (int c = 0; c < kCols; c++) {
        int plane = ObservationPlane({r, c}, player);
        SPIEL_CHECK_TRUE(plane >= 0 && plane < kCellStates);
        view[{plane, r, c}] = 1.0;
      }
    }
  } else {
    SPIEL_CHECK_EQ(values.size(), kNumObservations);
    std::fill(values.begin(), values.end(), 0);
    ObservationType obs = PartialObservation(player);
    values[obs] = 1;
  }
}
References open_spiel::coop_box_pushing::kNumObservations, open_spiel::State::num_players_, player, r, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, and values.
Reset()
void open_spiel::coop_box_pushing::CoopBoxPushingState::Reset (const GameParameters & params)
Returns()
std::vector< double > open_spiel::coop_box_pushing::CoopBoxPushingState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 468 of file coop_box_pushing.cc.
{
  // Cooperative game: all players get same reward.
  return {total_rewards_, total_rewards_};
}
Rewards()
std::vector< double > open_spiel::coop_box_pushing::CoopBoxPushingState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 473 of file coop_box_pushing.cc.
{
  // Cooperative game: all players get same reward.
  return {reward_, reward_};
}
ToString()
std::string open_spiel::coop_box_pushing::CoopBoxPushingState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 396 of file coop_box_pushing.cc.
{
  std::string result = "";
  absl::StrAppend(&result, "Total moves: ", total_moves_, "\n");
  absl::StrAppend(&result, "Most recent reward: ", reward_, "\n");
  absl::StrAppend(&result, "Total rewards: ", total_rewards_, "\n");
  for (int r = 0; r < kRows; r++) {
    for (int c = 0; c < kCols; c++) {
      result += field({r, c});
    }
    absl::StrAppend(&result, "\n");
  }
  return result;
}
References r, and absl::StrAppend().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/coop_box_pushing/coop_box_pushing.h
open_spiel/games/coop_box_pushing/coop_box_pushing.cc