open spiel: open_spiel::algorithms::TargetedPolicy Class Reference
open_spiel::algorithms::TargetedPolicy Class Reference
#include <oos.h>
Public Member Functions
TargetedPolicy (std::shared_ptr< const Game > game, const OOSInfoStateValuesTable &table, double bias_exploration=kDefaultExploration)
void NoTargeting ()
void UpdateTarget (const ActionObservationHistory *info_state)
void UpdateTarget (const PublicObservationHistory *public_state)
bool IsTargetHit (const State &h)
ActionsAndProbs GetStatePolicy (const State &h) const
void TrackStatistics (OnlineStats *stats)
Public Member Functions inherited from open_spiel::algorithms::CFRCurrentPolicy
CFRCurrentPolicy (const CFRInfoStateValuesTable &info_states, std::shared_ptr< Policy > default_policy)
ActionsAndProbs GetStatePolicy (const State &state, Player player) const override
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
TabularPolicy AsTabular () const
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
virtual std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const
Protected Attributes
const std::shared_ptr< const Game > game_
const double bias_exploration_
Targeting targeting_ = kDoNotUseTargeting
const ActionObservationHistory * target_info_state_
const PublicObservationHistory * target_public_state_
OnlineStats * stats_
Detailed Description
Definition at line 192 of file oos.h.
Constructor & Destructor Documentation
TargetedPolicy()
open_spiel::algorithms::TargetedPolicy::TargetedPolicy (std::shared_ptr< const Game > game, const OOSInfoStateValuesTable & table, double bias_exploration = kDefaultExploration) inline
Definition at line 208 of file oos.h.
      : CFRCurrentPolicy(table, std::make_shared<UniformPolicy>()),
        game_(game),
        bias_exploration_(bias_exploration) {}
Member Function Documentation
GetStatePolicy()
ActionsAndProbs open_spiel::algorithms::TargetedPolicy::GetStatePolicy (const State & h) const virtual
Reimplemented from open_spiel::algorithms::CFRCurrentPolicy.
Definition at line 103 of file oos.cc.
{
  // Check if current state is part of the currently built tree.
  ActionsAndProbs policy;
  if (h.IsChanceNode()) {
    policy = h.ChanceOutcomes();
  } else if (h.IsPlayerNode()) {
    policy = CFRCurrentPolicy::GetStatePolicy(h);
  } else {
    SpielFatalError("Could not get policy for this state.");
  }
  double biased_sum = 0.0;
  for (auto& [action, prob] : policy) {
    if (IsAllowedAction(h, action)) {
      biased_sum += prob;
    } else {
      prob = kBannedAction;
    }
  }
  // Normalize the biased policy if some actions have been banned.
  double bias_exploration = bias_exploration_;  // Default exploration.
  if (biased_sum > 0) {
    for (auto& [_, prob] : policy)  {
      prob /= biased_sum;
    }
  } else {
    // Do only uniform exploration when all actions are banned.
    // This means the targeted policy has become "lost" in the game due
    // to its imperfect information structure. Just because an action is locally
    // allowed, it does not mean that we will always reach the target by
    // following the (locally) allowed actions.
    bias_exploration = 1.;
    if (stats_) ++(stats_->missed_targets);
  }
  // Mix in exploration.
  const double unif = 1. / policy.size();
  for (auto& [_, prob] : policy) {
    prob = bias_exploration * unif + (1 - bias_exploration) * prob;
  }
  return policy;
}
References action, bias_exploration_, open_spiel::algorithms::CFRCurrentPolicy::GetStatePolicy(), open_spiel::algorithms::kBannedAction, open_spiel::algorithms::OnlineStats::missed_targets, open_spiel::SpielFatalError(), and stats_.
IsTargetHit()
bool open_spiel::algorithms::TargetedPolicy::IsTargetHit (const State & h)
Definition at line 167 of file oos.cc.
{
  SPIEL_CHECK_TRUE(targeting_ != kInfoStateTargeting ||
                   target_info_state_ != kNoActionObsTargetSpecified);
  SPIEL_CHECK_TRUE(targeting_ != kPublicStateTargeting ||
                   target_public_state_ != kNoPublicObsTargetSpecified);
  const bool hit_info_state =
      targeting_ == kInfoStateTargeting &&
      target_info_state_->CorrespondsTo(target_info_state_->GetPlayer(), h);
  const bool hit_public_state = targeting_ == kPublicStateTargeting &&
                                target_public_state_->CorrespondsTo(h);
  return hit_info_state || hit_public_state;
}
References open_spiel::ActionObservationHistory::CorrespondsTo(), open_spiel::PublicObservationHistory::CorrespondsTo(), open_spiel::ActionObservationHistory::GetPlayer(), open_spiel::algorithms::kInfoStateTargeting, open_spiel::algorithms::kNoActionObsTargetSpecified, open_spiel::algorithms::kNoPublicObsTargetSpecified, open_spiel::algorithms::kPublicStateTargeting, SPIEL_CHECK_TRUE, target_info_state_, target_public_state_, and targeting_.
NoTargeting()
void open_spiel::algorithms::TargetedPolicy::NoTargeting ()
Definition at line 78 of file oos.cc.
{
  targeting_ = kDoNotUseTargeting;
  target_public_state_ = kNoPublicObsTargetSpecified;
  target_info_state_ = kNoActionObsTargetSpecified;
}
References open_spiel::algorithms::kDoNotUseTargeting, open_spiel::algorithms::kNoActionObsTargetSpecified, open_spiel::algorithms::kNoPublicObsTargetSpecified, target_info_state_, target_public_state_, and targeting_.
Referenced by UpdateTarget(), and UpdateTarget().
TrackStatistics()
void open_spiel::algorithms::TargetedPolicy::TrackStatistics (OnlineStats * stats) inline
Definition at line 221 of file oos.h.
{ stats_ = stats; }
References stats_.
UpdateTarget() [1/2]
void open_spiel::algorithms::TargetedPolicy::UpdateTarget (const ActionObservationHistory * info_state)
Definition at line 84 of file oos.cc.
{
  NoTargeting();  // Reset.
  targeting_ = kInfoStateTargeting;
  target_info_state_ = info_state;
}
References open_spiel::algorithms::kInfoStateTargeting, NoTargeting(), target_info_state_, and targeting_.
UpdateTarget() [2/2]
void open_spiel::algorithms::TargetedPolicy::UpdateTarget (const PublicObservationHistory * public_state)
Definition at line 90 of file oos.cc.
{
  NoTargeting();  // Reset.
  targeting_ = kPublicStateTargeting;
  target_public_state_ = public_state;
}
References open_spiel::algorithms::kPublicStateTargeting, NoTargeting(), target_public_state_, and targeting_.
Member Data Documentation
bias_exploration_
const double open_spiel::algorithms::TargetedPolicy::bias_exploration_ protected
Definition at line 195 of file oos.h.
Referenced by GetStatePolicy().
game_
const std::shared_ptr<const Game> open_spiel::algorithms::TargetedPolicy::game_ protected
Definition at line 194 of file oos.h.
stats_
OnlineStats* open_spiel::algorithms::TargetedPolicy::stats_ protected
Definition at line 205 of file oos.h.
Referenced by GetStatePolicy(), and TrackStatistics().
target_info_state_
const ActionObservationHistory* open_spiel::algorithms::TargetedPolicy::target_info_state_ protected
Initial value:
=
      kNoActionObsTargetSpecified
Definition at line 199 of file oos.h.
Referenced by IsTargetHit(), NoTargeting(), and UpdateTarget().
target_public_state_
const PublicObservationHistory* open_spiel::algorithms::TargetedPolicy::target_public_state_ protected
Initial value:
=
      kNoPublicObsTargetSpecified
Definition at line 201 of file oos.h.
Referenced by IsTargetHit(), NoTargeting(), and UpdateTarget().
targeting_
Targeting open_spiel::algorithms::TargetedPolicy::targeting_ = kDoNotUseTargeting protected
Definition at line 197 of file oos.h.
Referenced by IsTargetHit(), NoTargeting(), UpdateTarget(), and UpdateTarget().
The documentation for this class was generated from the following files:
open_spiel/algorithms/oos.h
open_spiel/algorithms/oos.cc