open spiel: absl::MutexLockMaybe Class Reference
absl::MutexLockMaybe Class Reference
#include <mutex.h>
Public Member Functions
MutexLockMaybe (Mutex *mu) ABSL_EXCLUSIVE_LOCK_FUNCTION(mu)
MutexLockMaybe (Mutex *mu, const Condition &cond) ABSL_EXCLUSIVE_LOCK_FUNCTION(mu)
~MutexLockMaybe () ABSL_UNLOCK_FUNCTION()
Detailed Description
Definition at line 915 of file mutex.h.
Constructor & Destructor Documentation
MutexLockMaybe() [1/2]
absl::MutexLockMaybe::MutexLockMaybe (Mutex * mu) inline explicit
Definition at line 917 of file mutex.h.
      : mu_(mu) {
    if (this->mu_ != nullptr) {
      this->mu_->Lock();
    }
  }
References absl::Mutex::Lock().
MutexLockMaybe() [2/2]
absl::MutexLockMaybe::MutexLockMaybe (Mutex * mu, const Condition & cond) inline explicit
Definition at line 924 of file mutex.h.
      : mu_(mu) {
    if (this->mu_ != nullptr) {
      this->mu_->LockWhen(cond);
    }
  }
References absl::Mutex::LockWhen().
~MutexLockMaybe()
absl::MutexLockMaybe::~MutexLockMaybe () inline
Definition at line 932 of file mutex.h.
{
    if (this->mu_ != nullptr) { this->mu_->Unlock(); }
  }
References absl::Mutex::Unlock().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/synchronization/mutex.h