open spiel: absl::log_uniform_int_distribution< IntType >::param_type Class Reference
absl::log_uniform_int_distribution< IntType >::param_type Class Reference
#include <log_uniform_int_distribution.h>
Public Types
using distribution_type = log_uniform_int_distribution
Public Member Functions
param_type (result_type min=0, result_type max=(std::numeric_limits< result_type >::max)(), result_type base=2)
result_type min () const
result_type max () const
result_type base () const
Friends
class log_uniform_int_distribution
bool operator== (const param_type &a, const param_type &b)
bool operator!= (const param_type &a, const param_type &b)
Detailed Description
template<typename IntType = int>
class absl::log_uniform_int_distribution< IntType >::param_type
Definition at line 52 of file log_uniform_int_distribution.h.
Member Typedef Documentation
distribution_type
template<typename IntType = int> using absl::log_uniform_int_distribution< IntType >::param_type::distribution_type = log_uniform_int_distribution
Definition at line 54 of file log_uniform_int_distribution.h.
Constructor & Destructor Documentation
param_type()
template<typename IntType = int> absl::log_uniform_int_distribution< IntType >::param_type::param_type (result_type min = 0, result_type max = (std::numeric_limits<result_type>::max)(), result_type base = 2) inline explicit
Definition at line 56 of file log_uniform_int_distribution.h.
        : min_(min),
          max_(max),
          base_(base),
          range_(static_cast<unsigned_type>(max_) -
                 static_cast<unsigned_type>(min_)),
          log_range_(0) {
      assert(max_ >= min_);
      assert(base_ > 1);
      if (base_ == 2) {
        // Determine where the first set bit is on range(), giving a log2(range)
        // value which can be used to construct bounds.
        log_range_ = (std::min)(random_internal::BitWidth(range()),
                                std::numeric_limits<unsigned_type>::digits);
      } else {
        // NOTE: Computing the logN(x) introduces error from 2 sources:
        // 1. Conversion of int to double loses precision for values >=
        // 2^53, which may cause some log() computations to operate on
        // different values.
        // 2. The error introduced by the division will cause the result
        // to differ from the expected value.
        //
        // Thus a result which should equal K may equal K +/- epsilon,
        // which can eliminate some values depending on where the bounds fall.
        const double inv_log_base = 1.0 / std::log(static_cast<double>(base_));
        const double log_range = std::log(static_cast<double>(range()) + 0.5);
        log_range_ = static_cast<int>(std::ceil(inv_log_base * log_range));
      }
    }
References absl::random_internal::BitWidth().
Member Function Documentation
base()
template<typename IntType = int> result_type absl::log_uniform_int_distribution< IntType >::param_type::base () const inline
Definition at line 92 of file log_uniform_int_distribution.h.
{ return base_; }
Referenced by absl::log_uniform_int_distribution< IntType >::base().
max()
template<typename IntType = int> result_type absl::log_uniform_int_distribution< IntType >::param_type::max () const inline
Definition at line 91 of file log_uniform_int_distribution.h.
{ return max_; }
Referenced by absl::log_uniform_int_distribution< IntType >::max().
min()
template<typename IntType = int> result_type absl::log_uniform_int_distribution< IntType >::param_type::min () const inline
Definition at line 90 of file log_uniform_int_distribution.h.
{ return min_; }
Referenced by absl::log_uniform_int_distribution< IntType >::min().
Friends And Related Symbol Documentation
log_uniform_int_distribution
template<typename IntType = int> friend class log_uniform_int_distribution friend
Definition at line 103 of file log_uniform_int_distribution.h.
operator!=
template<typename IntType = int> bool operator!= (const param_type & a, const param_type & b) friend
Definition at line 98 of file log_uniform_int_distribution.h.
{
      return !(a == b);
    }
operator==
template<typename IntType = int> bool operator== (const param_type & a, const param_type & b) friend
Definition at line 94 of file log_uniform_int_distribution.h.
{
      return a.min_ == b.min_ && a.max_ == b.max_ && a.base_ == b.base_;
    }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/log_uniform_int_distribution.h