open spiel: absl::gaussian_distribution< RealType > Class Template Reference
absl::gaussian_distribution< RealType > Class Template Reference
#include <gaussian_distribution.h>
Classes
class param_type
Public Types
using result_type = RealType
Public Member Functions
gaussian_distribution ()
gaussian_distribution (result_type mean, result_type stddev=1)
gaussian_distribution (const param_type &p)
void reset ()
template<typename URBG >
result_type operator() (URBG &g)
template<typename URBG >
result_type operator() (URBG &g, const param_type &p)
param_type param () const
void param (const param_type &p)
result_type min () const
result_type max () const
result_type mean () const
result_type stddev () const
Friends
bool operator== (const gaussian_distribution &a, const gaussian_distribution &b)
bool operator!= (const gaussian_distribution &a, const gaussian_distribution &b)
Detailed Description
template<typename RealType = double>
class absl::gaussian_distribution< RealType >
Definition at line 87 of file gaussian_distribution.h.
Member Typedef Documentation
result_type
template<typename RealType = double> using absl::gaussian_distribution< RealType >::result_type = RealType
Definition at line 89 of file gaussian_distribution.h.
Constructor & Destructor Documentation
gaussian_distribution() [1/3]
template<typename RealType = double> absl::gaussian_distribution< RealType >::gaussian_distribution () inline
Definition at line 123 of file gaussian_distribution.h.
: gaussian_distribution(0) {}
gaussian_distribution() [2/3]
template<typename RealType = double> absl::gaussian_distribution< RealType >::gaussian_distribution (result_type mean, result_type stddev = 1) inline explicit
Definition at line 125 of file gaussian_distribution.h.
      : param_(mean, stddev) {}
gaussian_distribution() [3/3]
template<typename RealType = double> absl::gaussian_distribution< RealType >::gaussian_distribution (const param_type & p) inline explicit
Definition at line 128 of file gaussian_distribution.h.
: param_(p) {}
Member Function Documentation
max()
template<typename RealType = double> result_type absl::gaussian_distribution< RealType >::max () const inline
Definition at line 148 of file gaussian_distribution.h.
{
    return std::numeric_limits<result_type>::infinity();
  }
mean()
template<typename RealType = double> result_type absl::gaussian_distribution< RealType >::mean () const inline
Definition at line 152 of file gaussian_distribution.h.
{ return param_.mean(); }
References absl::gaussian_distribution< RealType >::param_type::mean().
min()
template<typename RealType = double> result_type absl::gaussian_distribution< RealType >::min () const inline
Definition at line 145 of file gaussian_distribution.h.
{
    return -std::numeric_limits<result_type>::infinity();
  }
operator()() [1/2]
template<typename RealType = double> template<typename URBG > result_type absl::gaussian_distribution< RealType >::operator() (URBG & g) inline
Definition at line 134 of file gaussian_distribution.h.
                                  {  // NOLINT(runtime/references)
    return (*this)(g, param_);
  }
References absl::g.
operator()() [2/2]
template<typename RealType > template<typename URBG > gaussian_distribution< RealType >::result_type absl::gaussian_distribution< RealType >::operator() (URBG & g, const param_type & p)
Definition at line 175 of file gaussian_distribution.h.
{
  return p.mean() + p.stddev() * static_cast<result_type>(zignor(g));
}
References absl::g, and absl::p.
param() [1/2]
template<typename RealType = double> param_type absl::gaussian_distribution< RealType >::param () const inline
Definition at line 142 of file gaussian_distribution.h.
{ return param_; }
param() [2/2]
template<typename RealType = double> void absl::gaussian_distribution< RealType >::param (const param_type & p) inline
Definition at line 143 of file gaussian_distribution.h.
{ param_ = p; }
References absl::p.
reset()
template<typename RealType = double> void absl::gaussian_distribution< RealType >::reset () inline
Definition at line 130 of file gaussian_distribution.h.
{}
Referenced by open_spiel.python.utils.stats.BasicStats::__init__(), open_spiel.python.algorithms.ismcts.ISMCTSBot::run_search(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
stddev()
template<typename RealType = double> result_type absl::gaussian_distribution< RealType >::stddev () const inline
Definition at line 153 of file gaussian_distribution.h.
{ return param_.stddev(); }
References absl::gaussian_distribution< RealType >::param_type::stddev().
Friends And Related Symbol Documentation
operator!=
template<typename RealType = double> bool operator!= (const gaussian_distribution< RealType > & a, const gaussian_distribution< RealType > & b) friend
Definition at line 159 of file gaussian_distribution.h.
{
    return a.param_ != b.param_;
  }
operator==
template<typename RealType = double> bool operator== (const gaussian_distribution< RealType > & a, const gaussian_distribution< RealType > & b) friend
Definition at line 155 of file gaussian_distribution.h.
{
    return a.param_ == b.param_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/gaussian_distribution.h