open spiel: absl::base_internal::LowLevelAlloc Class Reference
absl::base_internal::LowLevelAlloc Class Reference
#include <low_level_alloc.h>
Classes
struct Arena
Public Types
enum { kCallMallocHook = 0x0001 , kAsyncSignalSafe = 0x0002 }
Static Public Member Functions
static void * Alloc (size_t request) ABSL_ATTRIBUTE_SECTION(malloc_hook)
static void * AllocWithArena (size_t request, Arena *arena) ABSL_ATTRIBUTE_SECTION(malloc_hook)
static void Free (void *s) ABSL_ATTRIBUTE_SECTION(malloc_hook)
static Arena * NewArena (uint32_t flags)
static bool DeleteArena (Arena *arena)
static Arena * DefaultArena ()
Detailed Description
Definition at line 61 of file low_level_alloc.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kCallMallocHook
kAsyncSignalSafe
Definition at line 91 of file low_level_alloc.h.
       {
    // Report calls to Alloc() and Free() via the MallocHook interface.
    // Set in the DefaultArena.
    kCallMallocHook = 0x0001,
#ifndef ABSL_LOW_LEVEL_ALLOC_ASYNC_SIGNAL_SAFE_MISSING
    // Make calls to Alloc(), Free() be async-signal-safe. Not set in
    // DefaultArena(). Not supported on all platforms.
    kAsyncSignalSafe = 0x0002,
#endif
  };
Member Function Documentation
Alloc()
void * absl::base_internal::LowLevelAlloc::Alloc (size_t request) static
Definition at line 605 of file low_level_alloc.cc.
{
  void *result = DoAllocWithArena(request, DefaultArena());
  return result;
}
References DefaultArena().
AllocWithArena()
void * absl::base_internal::LowLevelAlloc::AllocWithArena (size_t request, Arena * arena) static
Definition at line 610 of file low_level_alloc.cc.
{
  ABSL_RAW_CHECK(arena != nullptr, "must pass a valid arena");
  void *result = DoAllocWithArena(request, arena);
  return result;
}
References ABSL_RAW_CHECK, and arena.
Referenced by absl::synchronization_internal::GraphCycles::GetId(), absl::synchronization_internal::GraphCycles::GraphCycles(), and NewArena().
DefaultArena()
LowLevelAlloc::Arena * absl::base_internal::LowLevelAlloc::DefaultArena () static
Definition at line 270 of file low_level_alloc.cc.
{
  base_internal::LowLevelCallOnce(&create_globals_once, CreateGlobalArenas);
  return reinterpret_cast<LowLevelAlloc::Arena*>(&default_arena_storage);
}
References absl::base_internal::LowLevelCallOnce().
Referenced by Alloc(), DeleteArena(), and NewArena().
DeleteArena()
bool absl::base_internal::LowLevelAlloc::DeleteArena (Arena * arena) static
Definition at line 383 of file low_level_alloc.cc.
{
  ABSL_RAW_CHECK(
      arena != nullptr && arena != DefaultArena() && arena != UnhookedArena(),
      "may not delete default arena");
  ArenaLock section(arena);
  if (arena->allocation_count != 0) {
    section.Leave();
    return false;
  }
  while (arena->freelist.next[0] != nullptr) {
    AllocList *region = arena->freelist.next[0];
    size_t size = region->header.size;
    arena->freelist.next[0] = region->next[0];
    ABSL_RAW_CHECK(
        region->header.magic == Magic(kMagicUnallocated, &region->header),
        "bad magic number in DeleteArena()");
    ABSL_RAW_CHECK(region->header.arena == arena,
                   "bad arena pointer in DeleteArena()");
    ABSL_RAW_CHECK(size % arena->pagesize == 0,
                   "empty arena has non-page-aligned block size");
    ABSL_RAW_CHECK(reinterpret_cast<uintptr_t>(region) % arena->pagesize == 0,
                   "empty arena has non-page-aligned block");
    int munmap_result;
#ifdef _WIN32
    munmap_result = VirtualFree(region, 0, MEM_RELEASE);
    ABSL_RAW_CHECK(munmap_result != 0,
                   "LowLevelAlloc::DeleteArena: VitualFree failed");
#else
#ifndef ABSL_LOW_LEVEL_ALLOC_ASYNC_SIGNAL_SAFE_MISSING
    if ((arena->flags & LowLevelAlloc::kAsyncSignalSafe) == 0) {
      munmap_result = munmap(region, size);
    } else {
      munmap_result = base_internal::DirectMunmap(region, size);
    }
#else
    munmap_result = munmap(region, size);
#endif  // ABSL_LOW_LEVEL_ALLOC_ASYNC_SIGNAL_SAFE_MISSING
    if (munmap_result != 0) {
      ABSL_RAW_LOG(FATAL, "LowLevelAlloc::DeleteArena: munmap failed: %d",
                   errno);
    }
#endif  // _WIN32
  }
  section.Leave();
  arena->~Arena();
  Free(arena);
  return true;
}
References ABSL_RAW_CHECK, ABSL_RAW_LOG, arena, DefaultArena(), Free(), kAsyncSignalSafe, and size.
Free()
void absl::base_internal::LowLevelAlloc::Free (void * s) static
Definition at line 509 of file low_level_alloc.cc.
{
  if (v != nullptr) {
    AllocList *f = reinterpret_cast<AllocList *>(
                        reinterpret_cast<char *>(v) - sizeof (f->header));
    LowLevelAlloc::Arena *arena = f->header.arena;
    ArenaLock section(arena);
    AddToFreelist(v, arena);
    ABSL_RAW_CHECK(arena->allocation_count > 0, "nothing in arena to free");
    arena->allocation_count--;
    section.Leave();
  }
}
References ABSL_RAW_CHECK, arena, absl::f, and absl::v.
Referenced by DeleteArena(), and absl::synchronization_internal::GraphCycles::~GraphCycles().
NewArena()
LowLevelAlloc::Arena * absl::base_internal::LowLevelAlloc::NewArena (uint32_t flags) static
Definition at line 367 of file low_level_alloc.cc.
{
  Arena *meta_data_arena = DefaultArena();
#ifndef ABSL_LOW_LEVEL_ALLOC_ASYNC_SIGNAL_SAFE_MISSING
  if ((flags & LowLevelAlloc::kAsyncSignalSafe) != 0) {
    meta_data_arena = UnhookedAsyncSigSafeArena();
  } else  // NOLINT(readability/braces)
#endif
      if ((flags & LowLevelAlloc::kCallMallocHook) == 0) {
    meta_data_arena = UnhookedArena();
  }
  Arena *result =
    new (AllocWithArena(sizeof (*result), meta_data_arena)) Arena(flags);
  return result;
}
References AllocWithArena(), DefaultArena(), kAsyncSignalSafe, and kCallMallocHook.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/base/internal/low_level_alloc.h
open_spiel/abseil-cpp/absl/base/internal/low_level_alloc.cc