open spiel: open_spiel::hex::HexState Class Reference
open_spiel::hex::HexState Class Reference
#include <hex.h>
Public Member Functions
HexState (std::shared_ptr< const Game > game, int num_cols, int num_rows)
HexState (const HexState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
CellState BoardAt (int cell) const
void ChangePlayer ()
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes
std::vector< CellState > board_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 66 of file hex.h.
Constructor & Destructor Documentation
HexState() [1/2]
open_spiel::hex::HexState::HexState (std::shared_ptr< const Game > game, int num_cols, int num_rows)
Definition at line 233 of file hex.cc.
    : State(game), num_cols_(num_cols), num_rows_(num_rows) {
  // for all num_colss & num_rowss -> num_colss_ >= num_rowss_
  board_.resize(num_cols * num_rows, CellState::kEmpty);
}
References board_, and open_spiel::hex::kEmpty.
Referenced by Clone().
HexState() [2/2]
open_spiel::hex::HexState::HexState (const HexState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::hex::HexState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 210 of file hex.cc.
{
  // This does not comply with the Hex Text Protocol
  // TODO(author8): Make compliant with HTP
  return absl::StrCat(StateToString(PlayerAndActionToState(player, action_id)),
                      "(", action_id % num_cols_, ",", action_id / num_cols_,
                      ")");
}
References player, open_spiel::hex::StateToString(), and absl::StrCat().
Referenced by open_spiel::dark_hex::DarkHexState::ActionToString().
BoardAt()
CellState open_spiel::hex::HexState::BoardAt (int cell) const inline
Definition at line 86 of file hex.h.
{ return board_[cell]; }
References board_.
Referenced by open_spiel::dark_hex::DarkHexState::DoApplyAction().
ChangePlayer()
void open_spiel::hex::HexState::ChangePlayer () inline
Definition at line 87 of file hex.h.
{ current_player_ = current_player_ == 0 ? 1 : 0; }
Referenced by open_spiel::dark_hex::DarkHexState::DoApplyAction().
Clone()
std::unique_ptr< State > open_spiel::hex::HexState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 289 of file hex.cc.
{
  return std::unique_ptr<State>(new HexState(*this));
}
References HexState().
CurrentPlayer()
Player open_spiel::hex::HexState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 72 of file hex.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by open_spiel::dark_hex::DarkHexState::CurrentPlayer(), and DoApplyAction().
DoApplyAction()
void open_spiel::hex::HexState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 162 of file hex.cc.
{
  SPIEL_CHECK_EQ(board_[move], CellState::kEmpty);
  CellState move_cell_state = PlayerAndActionToState(CurrentPlayer(), move);
  board_[move] = move_cell_state;
  if (move_cell_state == CellState::kBlackWin) {
    result_black_perspective_ = 1;
  } else if (move_cell_state == CellState::kWhiteWin) {
    result_black_perspective_ = -1;
  } else if (move_cell_state != CellState::kBlack &&
             move_cell_state != CellState::kWhite) {
    // Move is connected to an edge but not winning.
    // Update edge-connected groups with a flood-fill, to maintain that all edge
    // connected nodes are known about.
    // We don't do flood fill if a player has won, so it's impossible for a cell
    // connected to an edge to be changed by the flood-fill.
    CellState cell_state_to_change =
        (current_player_ == 0 ? CellState::kBlack : CellState::kWhite);
    // We assume that move can safely be cast to int
    std::vector<int> flood_stack = {static_cast<int>(move)};
    int latest_cell;
    while (!flood_stack.empty()) {
      latest_cell = flood_stack.back();
      flood_stack.pop_back();
      for (int neighbour : AdjacentCells(latest_cell)) {
        if (board_[neighbour] == cell_state_to_change) {
          // We make the change before putting the cell on the queue to avoid
          // putting the same cell on the queue multiple times
          board_[neighbour] = move_cell_state;
          flood_stack.push_back(neighbour);
        }
      }
    }
  }
  current_player_ = 1 - current_player_;
}
References board_, CurrentPlayer(), open_spiel::hex::kBlack, open_spiel::hex::kBlackWin, open_spiel::hex::kEmpty, open_spiel::hex::kWhite, open_spiel::hex::kWhiteWin, and SPIEL_CHECK_EQ.
InformationStateString()
std::string open_spiel::hex::HexState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 264 of file hex.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::hex::HexState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 258 of file hex.cc.
{ return result_black_perspective_ != 0; }
Referenced by CurrentPlayer(), open_spiel::dark_hex::DarkHexState::IsTerminal(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::hex::HexState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 198 of file hex.cc.
{
  // Can move in any empty cell.
  std::vector<Action> moves;
  if (IsTerminal()) return moves;
  for (int cell = 0; cell < board_.size(); ++cell) {
    if (board_[cell] == CellState::kEmpty) {
      moves.push_back(cell);
    }
  }
  return moves;
}
References board_, IsTerminal(), and open_spiel::hex::kEmpty.
ObservationString()
std::string open_spiel::hex::HexState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 270 of file hex.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::hex::HexState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 276 of file hex.cc.
{
  // TODO(author8): Make an option to not expose connection info
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<2> view(values, {kCellStates, static_cast<int>(board_.size())},
                     true);
  for (int cell = 0; cell < board_.size(); ++cell) {
    view[{static_cast<int>(board_[cell]) - kMinValueCellState, cell}] = 1.0;
  }
}
References board_, open_spiel::hex::kCellStates, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::hex::HexState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 260 of file hex.cc.
{
  return {result_black_perspective_, -result_black_perspective_};
}
Referenced by open_spiel::dark_hex::DarkHexState::Returns().
ToString()
std::string open_spiel::hex::HexState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 239 of file hex.cc.
{
  std::string str;
  // Each cell has the cell plus a space
  // nth line has n spaces, and 1 "\n", except last line has no "\n"
  str.reserve(num_cols_ * num_rows_ * 2 + num_rows_ * (num_rows_ + 1) / 2 - 1);
  int line_num = 0;
  for (int cell = 0; cell < board_.size(); ++cell) {
    // if it's the first cell in a new row
    if (cell && cell % num_cols_ == 0) {
      absl::StrAppend(&str, "\n");
      line_num++;
      absl::StrAppend(&str, std::string(line_num, ' '));
    }
    absl::StrAppend(&str, StateToString(board_[cell]));
    absl::StrAppend(&str, " ");
  }
  return str;
}
References board_, open_spiel::hex::StateToString(), and absl::StrAppend().
Referenced by ObservationString(), and open_spiel::dark_hex::DarkHexState::ToString().
Member Data Documentation
board_
std::vector<CellState> open_spiel::hex::HexState::board_ protected
Definition at line 90 of file hex.h.
Referenced by BoardAt(), DoApplyAction(), HexState(), LegalActions(), ObservationTensor(), and ToString().
The documentation for this class was generated from the following files:
open_spiel/games/hex/hex.h
open_spiel/games/hex/hex.cc