open spiel: open_spiel::RestrictedNashResponseState Class Reference
open_spiel::RestrictedNashResponseState Class Reference
#include <restricted_nash_response.h>
Public Member Functions
RestrictedNashResponseState (std::shared_ptr< const Game > game, std::unique_ptr< State > state, bool fixed, Player fixed_player, bool initial_state, double p, std::shared_ptr< Policy > fixed_policy)
RestrictedNashResponseState (const RestrictedNashResponseState &other)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::vector< Action > LegalActions (Player player) const override
std::vector< Action > LegalActions () const override
std::shared_ptr< const Game > GetOriginalGame () const
bool IsPlayerFixed (Player player) const
bool IsStateFixed () const
std::shared_ptr< State > GetOriginalState () const
bool IsRestrictedNashResponseInitialState () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &actions) override
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 40 of file restricted_nash_response.h.
Constructor & Destructor Documentation
RestrictedNashResponseState() [1/2]
open_spiel::RestrictedNashResponseState::RestrictedNashResponseState (std::shared_ptr< const Game > game, std::unique_ptr< State > state, bool fixed, Player fixed_player, bool initial_state, double p, std::shared_ptr< Policy > fixed_policy)
Definition at line 137 of file restricted_nash_response.cc.
    : State(std::move(game)),
      state_(std::move(state)),
      is_initial_(initial_state),
      fixed_(fixed),
      p_(p),
      fixed_player_(fixed_player),
      fixed_policy_(fixed_policy),
      use_fixed_policy_(fixed_policy) {}
Referenced by Clone().
RestrictedNashResponseState() [2/2]
open_spiel::RestrictedNashResponseState::RestrictedNashResponseState (const RestrictedNashResponseState & other)
Definition at line 303 of file restricted_nash_response.cc.
    : State(other),
      state_(other.state_->Clone()),
      is_initial_(other.is_initial_),
      fixed_(other.fixed_),
      p_(other.p_),
      fixed_player_(other.fixed_player_),
      fixed_policy_(other.fixed_policy_),
      use_fixed_policy_(other.use_fixed_policy_) {}
Member Function Documentation
ActionToString()
std::string open_spiel::RestrictedNashResponseState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 228 of file restricted_nash_response.cc.
{
  if (is_initial_) {
    SPIEL_CHECK_EQ(player, kChancePlayerId);
    return (action_id == kFixedAction ? "Fixed" : "Free");
  } else {
    Player action_player = player;
    if (action_player == kChancePlayerId && use_fixed_policy_ && fixed_ &&
        state_->CurrentPlayer() == fixed_player_) {
      // This is a chance node in the RNR game, but a regular player node
      // in the underlying game, so we need to use the player's true identity
      // at this node.
      action_player = state_->CurrentPlayer();
    }
    return state_->ActionToString(action_player, action_id);
  }
}
References open_spiel::kChancePlayerId, open_spiel::kFixedAction, player, and SPIEL_CHECK_EQ.
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::RestrictedNashResponseState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 180 of file restricted_nash_response.cc.
{
  if (is_initial_) {
    return {{Action(kFixedAction), p_}, {Action(kFreeAction), 1 - p_}};
  } else {
    if (state_->IsChanceNode()) {
      return state_->ChanceOutcomes();
    } else if (use_fixed_policy_ && fixed_ &&
               state_->CurrentPlayer() == fixed_player_) {
      return fixed_policy_->GetStatePolicy(*state_);
    }
  }
  return {};
}
References open_spiel::kFixedAction, and open_spiel::kFreeAction.
Clone()
std::unique_ptr< State > open_spiel::RestrictedNashResponseState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 314 of file restricted_nash_response.cc.
{
  return std::unique_ptr<State>(new RestrictedNashResponseState(*this));
}
References RestrictedNashResponseState().
CurrentPlayer()
Player open_spiel::RestrictedNashResponseState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 150 of file restricted_nash_response.cc.
{
  if (is_initial_) {
    return kChancePlayerId;
  } else {
    if (use_fixed_policy_ && fixed_ &&
        state_->CurrentPlayer() == fixed_player_) {
      return kChancePlayerId;
    } else {
      return state_->CurrentPlayer();
    }
  }
}
References open_spiel::kChancePlayerId.
DoApplyAction()
void open_spiel::RestrictedNashResponseState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 163 of file restricted_nash_response.cc.
{
  if (is_initial_) {
    is_initial_ = false;
    fixed_ = action_id == kFixedAction;
  } else {
    state_->ApplyAction(action_id);
  }
}
References open_spiel::kFixedAction.
DoApplyActions()
void open_spiel::RestrictedNashResponseState::DoApplyActions (const std::vector< Action > & actions) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 172 of file restricted_nash_response.cc.
{
  SPIEL_CHECK_EQ(game_->GetType().dynamics, GameType::Dynamics::kSimultaneous);
  SPIEL_CHECK_EQ(is_initial_, false);
  state_->ApplyActions(actions);
}
References open_spiel::State::game_, open_spiel::GameType::kSimultaneous, and SPIEL_CHECK_EQ.
GetOriginalGame()
std::shared_ptr< const Game > open_spiel::RestrictedNashResponseState::GetOriginalGame () const inline
Definition at line 77 of file restricted_nash_response.h.
{
    return state_->GetGame();
  }
GetOriginalState()
std::shared_ptr< State > open_spiel::RestrictedNashResponseState::GetOriginalState () const inline
Definition at line 85 of file restricted_nash_response.h.
{ return state_; }
InformationStateString()
std::string open_spiel::RestrictedNashResponseState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 273 of file restricted_nash_response.cc.
{
  const auto& game =
      open_spiel::down_cast<const RestrictedNashResponseGame &>(*game_);
  return game.info_state_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
InformationStateTensor()
void open_spiel::RestrictedNashResponseState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 280 of file restricted_nash_response.cc.
{
  ContiguousAllocator allocator(values);
  const auto &game =
      open_spiel::down_cast<const RestrictedNashResponseGame &>(*game_);
  game.info_state_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
IsPlayerFixed()
bool open_spiel::RestrictedNashResponseState::IsPlayerFixed (Player player) const inline
Definition at line 81 of file restricted_nash_response.h.
{ return player == fixed_player_; }
References player.
IsRestrictedNashResponseInitialState()
bool open_spiel::RestrictedNashResponseState::IsRestrictedNashResponseInitialState () const inline
Definition at line 87 of file restricted_nash_response.h.
{ return is_initial_; }
IsStateFixed()
bool open_spiel::RestrictedNashResponseState::IsStateFixed () const inline
Definition at line 83 of file restricted_nash_response.h.
{ return fixed_; }
IsTerminal()
bool open_spiel::RestrictedNashResponseState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 257 of file restricted_nash_response.cc.
{
  if (is_initial_) {
    return false;
  } else {
    return state_->IsTerminal();
  }
}
LegalActions() [1/2]
std::vector< Action > open_spiel::RestrictedNashResponseState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 194 of file restricted_nash_response.cc.
{
  if (is_initial_) {
    return {Action(kFixedAction), Action(kFreeAction)};
  } else {
    return state_->LegalActions();
  }
}
References open_spiel::kFixedAction, and open_spiel::kFreeAction.
LegalActions() [2/2]
std::vector< Action > open_spiel::RestrictedNashResponseState::LegalActions (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 202 of file restricted_nash_response.cc.
{
  // Initial state only has two actions to fixed or free tree
  if (is_initial_) {
    if (player == kChancePlayerId) {
      return {Action(kFixedAction), Action(kFreeAction)};
    } else {
      return {};
    }
  } else {
    if (use_fixed_policy_ && fixed_ &&
        state_->CurrentPlayer() == fixed_player_) {
      // In other states if we exchanged fixed player nodes for chance node we
      // return action for chance player
      if (player == kChancePlayerId) {
        return state_->LegalActions(fixed_player_);
      } else {
        return {};
      }
    } else {
      // Otherwise we just use original legal actions
      return state_->LegalActions(player);
    }
  }
}
References open_spiel::kChancePlayerId, open_spiel::kFixedAction, open_spiel::kFreeAction, and player.
ObservationString()
std::string open_spiel::RestrictedNashResponseState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 288 of file restricted_nash_response.cc.
{
  const auto& game =
      open_spiel::down_cast<const RestrictedNashResponseGame &>(*game_);
  return game.default_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
ObservationTensor()
void open_spiel::RestrictedNashResponseState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 295 of file restricted_nash_response.cc.
{
  ContiguousAllocator allocator(values);
  const auto &game =
      open_spiel::down_cast<const RestrictedNashResponseGame &>(*game_);
  game.default_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
Returns()
std::vector< double > open_spiel::RestrictedNashResponseState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 265 of file restricted_nash_response.cc.
{
  if (is_initial_) {
    return std::vector<double>(num_players_, 0.0);
  }
  return state_->Returns();
}
References open_spiel::State::num_players_.
ToString()
std::string open_spiel::RestrictedNashResponseState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 246 of file restricted_nash_response.cc.
{
  if (is_initial_) {
    return "Initial restricted Nash response state.";
  } else {
    std::string state_string = "Rnr state string of state in ";
    state_string += (fixed_ ? "fixed" : "free");
    state_string += " part with underlying state:\n";
    return state_string + state_->ToString();
  }
}
The documentation for this class was generated from the following files:
open_spiel/game_transforms/restricted_nash_response.h
open_spiel/game_transforms/restricted_nash_response.cc