open spiel: open_spiel::BasicStats Class Reference
open_spiel::BasicStats Class Reference
#include <stats.h>
Public Member Functions
BasicStats ()
void Reset ()
BasicStats & operator+= (const BasicStats &o)
void Add (double val)
int64_t Num () const
double Min () const
double Max () const
double Avg () const
double StdDev () const
json::Object ToJson () const
Detailed Description
Definition at line 27 of file stats.h.
Constructor & Destructor Documentation
BasicStats()
open_spiel::BasicStats::BasicStats () inline
Definition at line 29 of file stats.h.
{ Reset(); }
References Reset().
Member Function Documentation
Add()
void open_spiel::BasicStats::Add (double val) inline
Definition at line 50 of file stats.h.
                       {
    min_ = std::min(min_, val);
    max_ = std::max(max_, val);
    sum_ += val;
    sum_sq_ += val * val;
    num_ += 1;
  }
Referenced by open_spiel::algorithms::torch_az::learner().
Avg()
double open_spiel::BasicStats::Avg () const inline
Definition at line 61 of file stats.h.
{ return (num_ == 0 ? 0 : sum_ / num_); }
Referenced by ToJson().
Max()
double open_spiel::BasicStats::Max () const inline
Definition at line 60 of file stats.h.
{ return (num_ == 0 ? 0 : max_); }
Referenced by ToJson().
Min()
double open_spiel::BasicStats::Min () const inline
Definition at line 59 of file stats.h.
{ return (num_ == 0 ? 0 : min_); }
Referenced by ToJson().
Num()
int64_t open_spiel::BasicStats::Num () const inline
Definition at line 58 of file stats.h.
{ return num_; }
Referenced by ToJson().
operator+=()
BasicStats & open_spiel::BasicStats::operator+= (const BasicStats & o) inline
Definition at line 41 of file stats.h.
{
    num_ += o.num_;
    sum_ += o.sum_;
    sum_sq_ += o.sum_sq_;
    min_ = std::min(min_, o.min_);
    max_ = std::max(max_, o.max_);
    return *this;
  }
References o.
Reset()
void open_spiel::BasicStats::Reset () inline
Definition at line 32 of file stats.h.
               {
    num_ = 0;
    min_ = std::numeric_limits<double>::max();
    max_ = std::numeric_limits<double>::min();
    sum_ = 0;
    sum_sq_ = 0;
  }
Referenced by BasicStats(), open_spiel::algorithms::torch_az::learner(), and open_spiel::algorithms::torch_az::VPNetEvaluator::ResetBatchSizeStats().
StdDev()
double open_spiel::BasicStats::StdDev () const inline
Definition at line 62 of file stats.h.
{
    if (num_ <= 1) return 0;
    // Numerical precision can cause variance to be negative, leading to NaN's.
    double variance = (sum_sq_ - sum_ * sum_ / num_) / (num_ - 1);
    return variance <= 0 ? 0 : std::sqrt(variance);
  }
Referenced by ToJson().
ToJson()
json::Object open_spiel::BasicStats::ToJson () const inline
Definition at line 69 of file stats.h.
{
    return {
        {"num", Num()},
        {"min", Min()},
        {"max", Max()},
        {"avg", Avg()},
        {"std_dev", StdDev()},
    };
  }
References Avg(), Max(), Min(), Num(), and StdDev().
Referenced by open_spiel::algorithms::torch_az::learner().
The documentation for this class was generated from the following file:
open_spiel/utils/stats.h