open spiel: absl::cord_internal::CordRepBtreeNavigator Class Reference
absl::cord_internal::CordRepBtreeNavigator Class Reference
#include <cord_rep_btree_navigator.h>
Classes
struct Position
struct ReadResult
Public Member Functions
operator bool () const
CordRepBtree * btree () const
CordRep * Current () const
CordRep * InitFirst (CordRepBtree *tree)
CordRep * InitLast (CordRepBtree *tree)
Position InitOffset (CordRepBtree *tree, size_t offset)
CordRep * Next ()
CordRep * Previous ()
Position Seek (size_t offset)
ReadResult Read (size_t edge_offset, size_t n)
Position Skip (size_t n)
void Reset ()
Detailed Description
Definition at line 46 of file cord_rep_btree_navigator.h.
Member Function Documentation
btree()
CordRepBtree * absl::cord_internal::CordRepBtreeNavigator::btree () const inline
Definition at line 153 of file cord_rep_btree_navigator.h.
{
  return height_ >= 0 ? node_[height_] : nullptr;
}
Referenced by absl::cord_internal::CordRepBtreeReader::btree(), absl::cord_internal::CordRepBtreeReader::operator bool(), and Seek().
Current()
CordRep * absl::cord_internal::CordRepBtreeNavigator::Current () const inline
Definition at line 157 of file cord_rep_btree_navigator.h.
{
  assert(height_ >= 0);
  return node_[0]->Edge(index_[0]);
}
References absl::cord_internal::CordRepBtree::Edge().
Referenced by absl::cord_internal::CordRepBtreeReader::node(), absl::cord_internal::CordRepBtreeReader::Read(), and absl::cord_internal::CordRepBtreeReader::Skip().
InitFirst()
CordRep * absl::cord_internal::CordRepBtreeNavigator::InitFirst (CordRepBtree * tree) inline
Definition at line 164 of file cord_rep_btree_navigator.h.
{
  return Init<CordRepBtree::kFront>(tree);
}
Referenced by absl::cord_internal::CordRepBtreeReader::Init().
InitLast()
CordRep * absl::cord_internal::CordRepBtreeNavigator::InitLast (CordRepBtree * tree) inline
Definition at line 168 of file cord_rep_btree_navigator.h.
{
  return Init<CordRepBtree::kBack>(tree);
}
InitOffset()
CordRepBtreeNavigator::Position absl::cord_internal::CordRepBtreeNavigator::InitOffset (CordRepBtree * tree, size_t offset) inline
Definition at line 207 of file cord_rep_btree_navigator.h.
{
  assert(tree != nullptr);
  assert(tree->height() <= CordRepBtree::kMaxHeight);
  if (ABSL_PREDICT_FALSE(offset >= tree->length)) return {nullptr, 0};
  height_ = tree->height();
  node_[height_] = tree;
  return Seek(offset);
}
References ABSL_PREDICT_FALSE, absl::cord_internal::CordRepBtree::height(), absl::cord_internal::CordRepBtree::kMaxHeight, absl::cord_internal::CordRep::length, and Seek().
Next()
CordRep * absl::cord_internal::CordRepBtreeNavigator::Next () inline
Definition at line 217 of file cord_rep_btree_navigator.h.
{
  CordRepBtree* edge = node_[0];
  return index_[0] == edge->back() ? NextUp() : edge->Edge(++index_[0]);
}
References absl::cord_internal::CordRepBtree::back(), and absl::cord_internal::CordRepBtree::Edge().
Referenced by absl::cord_internal::CordRepBtreeReader::Next(), and absl::cord_internal::CordRepBtreeReader::Read().
operator bool()
absl::cord_internal::CordRepBtreeNavigator::operator bool () const inline explicit
Definition at line 151 of file cord_rep_btree_navigator.h.
{ return height_ >= 0; }
Previous()
CordRep * absl::cord_internal::CordRepBtreeNavigator::Previous () inline
Definition at line 222 of file cord_rep_btree_navigator.h.
{
  CordRepBtree* edge = node_[0];
  return index_[0] == edge->begin() ? PreviousUp() : edge->Edge(--index_[0]);
}
References absl::cord_internal::CordRepBtree::begin(), and absl::cord_internal::CordRepBtree::Edge().
Read()
ReadResult absl::cord_internal::CordRepBtreeNavigator::Read (size_t edge_offset, size_t n)
Definition at line 108 of file cord_rep_btree_navigator.cc.
{
  int height = 0;
  size_t length = edge_offset + n;
  size_t index = index_[0];
  CordRepBtree* node = node_[0];
  CordRep* edge = node->Edge(index);
  assert(edge_offset < edge->length);
  if (length < edge->length) {
    return {Substring(edge, edge_offset, n), length};
  }
  // Similar to 'Skip', we consume all edges that are inside the 'length' of
  // data that needs to be read. If we exhaust the current level, we move one
  // level up the tree and repeat until we hit the final edge that must be
  // (partially) read. We consume all edges into `subtree`.
  CordRepBtree* subtree = CordRepBtree::New(Substring(edge, edge_offset));
  size_t subtree_end = 1;
  do {
    length -= edge->length;
    while (++index == node->end()) {
      index_[height] = static_cast<uint8_t>(index);
      if (++height > height_) {
        subtree->set_end(subtree_end);
        if (length == 0) return {subtree, 0};
        CordRep::Unref(subtree);
        return {nullptr, length};
      }
      if (length != 0) {
        subtree->set_end(subtree_end);
        subtree = CordRepBtree::New(subtree);
        subtree_end = 1;
      }
      node = node_[height];
      index = index_[height];
    }
    edge = node->Edge(index);
    if (length >= edge->length) {
      subtree->length += edge->length;
      subtree->edges_[subtree_end++] = CordRep::Ref(edge);
    }
  } while (length >= edge->length);
  CordRepBtree* tree = subtree;
  subtree->length += length;
  // If we moved up the tree, descend down to the leaf level, consuming all
  // edges that must be read, adding 'down' nodes to `subtree`.
  while (height > 0) {
    node = edge->btree();
    index_[height] = static_cast<uint8_t>(index);
    node_[--height] = node;
    index = node->begin();
    edge = node->Edge(index);
    if (length != 0) {
      CordRepBtree* right = CordRepBtree::New(height);
      right->length = length;
      subtree->edges_[subtree_end++] = right;
      subtree->set_end(subtree_end);
      subtree = right;
      subtree_end = 0;
      while (length >= edge->length) {
        subtree->edges_[subtree_end++] = CordRep::Ref(edge);
        length -= edge->length;
        edge = node->Edge(++index);
      }
    }
  }
  // Add any (partial) edge still remaining at the leaf level.
  if (length != 0) {
    subtree->edges_[subtree_end++] = Substring(edge, 0, length);
  }
  subtree->set_end(subtree_end);
  index_[0] = static_cast<uint8_t>(index);
  return {tree, length};
}
References absl::cord_internal::CordRepBtree::begin(), absl::cord_internal::CordRep::btree(), absl::cord_internal::CordRepBtree::Edge(), absl::cord_internal::CordRepBtree::end(), absl::cord_internal::CordRep::length, absl::n, absl::cord_internal::CordRepBtree::New(), absl::cord_internal::CordRep::Ref(), and absl::cord_internal::CordRep::Unref().
Referenced by absl::cord_internal::CordRepBtreeReader::Read().
Reset()
void absl::cord_internal::CordRepBtreeNavigator::Reset () inline
Definition at line 162 of file cord_rep_btree_navigator.h.
{ height_ = -1; }
Referenced by absl::cord_internal::CordRepBtreeReader::Reset().
Seek()
CordRepBtreeNavigator::Position absl::cord_internal::CordRepBtreeNavigator::Seek (size_t offset) inline
Definition at line 190 of file cord_rep_btree_navigator.h.
                   {
  assert(btree() != nullptr);
  int height = height_;
  CordRepBtree* edge = node_[height];
  if (ABSL_PREDICT_FALSE(offset >= edge->length)) return {nullptr, 0};
  CordRepBtree::Position index = edge->IndexOf(offset);
  index_[height] = static_cast<uint8_t>(index.index);
  while (--height >= 0) {
    edge = edge->Edge(index.index)->btree();
    node_[height] = edge;
    index = edge->IndexOf(index.n);
    index_[height] = static_cast<uint8_t>(index.index);
  }
  return {edge->Edge(index.index), index.n};
}
References ABSL_PREDICT_FALSE, absl::cord_internal::CordRep::btree(), btree(), absl::cord_internal::CordRepBtree::Edge(), absl::cord_internal::CordRepBtree::Position::index, absl::cord_internal::CordRep::length, and absl::cord_internal::CordRepBtree::Position::n.
Referenced by InitOffset(), and absl::cord_internal::CordRepBtreeReader::Seek().
Skip()
CordRepBtreeNavigator::Position absl::cord_internal::CordRepBtreeNavigator::Skip (size_t n)
Definition at line 68 of file cord_rep_btree_navigator.cc.
{
  int height = 0;
  size_t index = index_[0];
  CordRepBtree* node = node_[0];
  CordRep* edge = node->Edge(index);
  // Overall logic: Find an edge of at least the length we need to skip.
  // We consume all edges which are smaller (i.e., must be 100% skipped).
  // If we exhausted all edges on the current level, we move one level
  // up the tree, and repeat until we either find the edge, or until we hit
  // the top of the tree meaning the skip exceeds tree->length.
  while (n >= edge->length) {
    n -= edge->length;
    while (++index == node->end()) {
      if (++height > height_) return {nullptr, n};
      node = node_[height];
      index = index_[height];
    }
    edge = node->Edge(index);
  }
  // If we moved up the tree, descend down to the leaf level, consuming all
  // edges that must be skipped.
  while (height > 0) {
    node = edge->btree();
    index_[height] = static_cast<uint8_t>(index);
    node_[--height] = node;
    index = node->begin();
    edge = node->Edge(index);
    while (n >= edge->length) {
      n -= edge->length;
      ++index;
      assert(index != node->end());
      edge = node->Edge(index);
    }
  }
  index_[0] = static_cast<uint8_t>(index);
  return {edge, n};
}
References absl::cord_internal::CordRepBtree::begin(), absl::cord_internal::CordRep::btree(), absl::cord_internal::CordRepBtree::Edge(), absl::cord_internal::CordRepBtree::end(), absl::cord_internal::CordRep::length, and absl::n.
Referenced by absl::cord_internal::CordRepBtreeReader::Skip().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_btree_navigator.h
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_btree_navigator.cc