open spiel: open_spiel::algorithms::OOSAlgorithm Class Reference
open_spiel::algorithms::OOSAlgorithm Class Reference
#include <oos.h>
Public Member Functions
OOSAlgorithm (const std::shared_ptr< const Game > game, std::unique_ptr< OOSInfoStateValuesTable > values, std::unique_ptr< Random > random, std::unique_ptr< Policy > sample_policy, std::unique_ptr< TargetedPolicy > bias_policy, std::shared_ptr< Policy > default_policy, double target_biasing)
OOSAlgorithm (std::shared_ptr< const Game > game)
void RunUnbiasedIterations (int iterations)
void RunTargetedIterations (const ActionObservationHistory &target_info_state, int iterations)
void RunTargetedIterations (const PublicObservationHistory &target_public_state, int iterations)
std::unique_ptr< Policy > AveragePolicy () const
std::unique_ptr< Policy > CurrentPolicy () const
const OnlineStats & GetStats ()
Protected Member Functions
void RunTargetedIterations (int iterations)
void RootIteration (State *h, Player exploringPl)
double Iteration (State *h, double rm_h_pl, double rm_h_opp, double bs_h_all, double us_h_all, double us_h_cn, Player exploringPl)
double IterationTerminalNode (State *h, double bs_h_all, double us_h_all, Player exploringPl)
double IterationChanceNode (State *h, double rm_h_pl, double rm_h_opp, double bs_h_all, double us_h_all, double us_h_cn, Player exploringPl)
double IterationPlayerNode (State *h, double rm_h_pl, double rm_h_opp, double bs_h_all, double us_h_all, double us_h_cn, Player exploringPl)
PlayerNodeOutcome IncrementallyBuildTree (State *h, const std::string &info_state, double s_h_all, Player exploringPl)
PlayerNodeOutcome SampleExistingTree (State *h, const std::string &info_state, CFRInfoStateValues *values, double rm_h_pl, double rm_h_opp, double bs_h_all, double us_h_all, double us_h_cn, Player exploringPl)
TakeAction SelectAction (State *h, bool do_biased_sample)
bool IsBiasingApplicable (double bs_h_all)
void UpdateInfoStateCumulativeRegrets (CFRInfoStateValues *values, Action a, double u_ha, double u_h, double importance_sampling_ratio)
void UpdateInfoStateCumulativePolicy (CFRInfoStateValues *values, double importance_sampling_ratio)
double Bias (double biased, double non_biased) const
Protected Attributes
const std::shared_ptr< const Game > game_
std::unique_ptr< OOSInfoStateValuesTable > values_
std::unique_ptr< Random > random_
std::unique_ptr< Policy > sample_policy_
std::unique_ptr< TargetedPolicy > bias_policy_
std::shared_ptr< Policy > default_policy_
const double target_biasing_
bool is_biased_iteration_ = false
bool is_below_target_ = false
double s_z_all_ = -1
double u_z_ = 0.0
OnlineStats stats_
Detailed Description
Definition at line 254 of file oos.h.
Constructor & Destructor Documentation
OOSAlgorithm() [1/2]
open_spiel::algorithms::OOSAlgorithm::OOSAlgorithm (const std::shared_ptr< const Game > game, std::unique_ptr< OOSInfoStateValuesTable > values, std::unique_ptr< Random > random, std::unique_ptr< Policy > sample_policy, std::unique_ptr< TargetedPolicy > bias_policy, std::shared_ptr< Policy > default_policy, double target_biasing)
Definition at line 229 of file oos.cc.
    : game_(game),
      values_(std::move(values)),
      random_(std::move(random)),
      sample_policy_(std::move(sample_policy)),
      bias_policy_(std::move(bias_policy)),
      default_policy_(std::move(default_policy)),
      target_biasing_(target_biasing) {
  SPIEL_CHECK_PROB(target_biasing_);
  SPIEL_CHECK_EQ(game->GetType().dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_TRUE(game->GetType().provides_observation_string);
  SPIEL_CHECK_TRUE(game->GetType().provides_information_state_string);
  stats_.Reset();
  if (bias_policy_) bias_policy_->TrackStatistics(&stats_);
}
References bias_policy_, open_spiel::GameType::kSequential, open_spiel::algorithms::OnlineStats::Reset(), SPIEL_CHECK_EQ, SPIEL_CHECK_PROB, SPIEL_CHECK_TRUE, stats_, target_biasing_, and values.
OOSAlgorithm() [2/2]
open_spiel::algorithms::OOSAlgorithm::OOSAlgorithm (std::shared_ptr< const Game > game) explicit
Definition at line 251 of file oos.cc.
    : OOSAlgorithm(std::move(game), std::make_unique<OOSInfoStateValuesTable>(),
                   std::make_unique<RandomMT>(/*seed=*/0),
                   /*sample_policy=*/nullptr,
                   /*bias_policy=*/nullptr,
                   /*default_policy=*/std::make_shared<UniformPolicy>(),
                   kDefaultBiasing) {
  // Make sure the policies receive references to the values table.
  sample_policy_ = std::make_unique<ExplorativeSamplingPolicy>(*values_);
  bias_policy_ = std::make_unique<TargetedPolicy>(game_, *values_);
  bias_policy_->TrackStatistics(&stats_);
}
References bias_policy_, game_, sample_policy_, stats_, and values_.
Member Function Documentation
AveragePolicy()
std::unique_ptr< Policy > open_spiel::algorithms::OOSAlgorithm::AveragePolicy () const inline
Definition at line 280 of file oos.h.
{
    return std::make_unique<CFRAveragePolicy>(*values_, default_policy_);
  }
References default_policy_, and values_.
Bias()
double open_spiel::algorithms::OOSAlgorithm::Bias (double biased, double non_biased) const inline protected
Definition at line 336 of file oos.h.
{
    return target_biasing_ * biased + (1 - target_biasing_) * non_biased;
  }
References target_biasing_.
Referenced by IterationChanceNode(), IterationPlayerNode(), IterationTerminalNode(), and SampleExistingTree().
CurrentPolicy()
std::unique_ptr< Policy > open_spiel::algorithms::OOSAlgorithm::CurrentPolicy () const inline
Definition at line 287 of file oos.h.
{
    return std::make_unique<CFRCurrentPolicy>(*values_, default_policy_);
  }
References default_policy_, and values_.
GetStats()
const OnlineStats & open_spiel::algorithms::OOSAlgorithm::GetStats () inline
Definition at line 291 of file oos.h.
{ return stats_; }
References stats_.
IncrementallyBuildTree()
PlayerNodeOutcome open_spiel::algorithms::OOSAlgorithm::IncrementallyBuildTree (State * h, const std::string & info_state, double s_h_all, Player exploringPl) protected
Definition at line 471 of file oos.cc.
{
  SPIEL_DCHECK_FALSE(std::isnan(s_h_all));
  ++stats_.rollouts;
  // The current history is a leaf within the currently built look-ahead tree.
  // By adding info state values, we make sure that next sampling from here
  // will be into the existing tree.
  const std::vector<Action> actions = h->LegalActions();
  const auto [it, state_inserted] =
      values_->emplace(info_state, CFRInfoStateValues(actions));
  // If it was already in the values, we shouldn't be building the tree.
  SPIEL_DCHECK_TRUE(state_inserted);
  const double rm_ha_both = 1.0 / actions.size();
  double reach_prob = 1.0;
  Action first_action = kInvalidAction;
  SPIEL_DCHECK_TRUE(h->IsPlayerNode());
  while (!h->IsTerminal()) {
    ActionsAndProbs policy;
    if (h->IsChanceNode()) {
      policy = h->ChanceOutcomes();
    } else if (h->IsPlayerNode()) {
      policy = UniformStatePolicy(*h);
    } else {
      SpielFatalError("Invalid state");
    }
    const auto [action, prob] = SampleAction(policy, random_->RandomUniform());
    if (first_action == kInvalidAction) {
      first_action = action;
    }
    reach_prob *= prob;
    h->ApplyAction(action);
  }
  SPIEL_DCHECK_NE(first_action, kInvalidAction);
  u_z_ = h->PlayerReturn(exploringPl);
  s_z_all_ = s_h_all * reach_prob;
  // The expected values for u(h) must be unbiased so MCCFR can work correctly.
  // Normally we use importance sampling, but since the strategy and sampling
  // policy are the same, they cancel each other out. Leaving just leaf value
  // for the current estimate.
  const double u_h = u_z_;
  const double u_ha = u_z_;
  return PlayerNodeOutcome{first_action, rm_ha_both, u_h, u_ha, it->second};
}
References action, open_spiel::kInvalidAction, random_, open_spiel::algorithms::OnlineStats::rollouts, s_z_all_, open_spiel::SampleAction(), SPIEL_DCHECK_FALSE, SPIEL_DCHECK_NE, SPIEL_DCHECK_TRUE, open_spiel::SpielFatalError(), stats_, u_z_, open_spiel::UniformStatePolicy(), and values_.
Referenced by IterationPlayerNode().
IsBiasingApplicable()
bool open_spiel::algorithms::OOSAlgorithm::IsBiasingApplicable (double bs_h_all) protected
Definition at line 523 of file oos.cc.
{
  return is_biased_iteration_ && !is_below_target_ && bs_h_all > 0.0;
}
References is_below_target_, and is_biased_iteration_.
Referenced by IterationChanceNode(), and SampleExistingTree().
Iteration()
double open_spiel::algorithms::OOSAlgorithm::Iteration (State * h, double rm_h_pl, double rm_h_opp, double bs_h_all, double us_h_all, double us_h_cn, Player exploringPl) protected
Definition at line 333 of file oos.cc.
{
  // Have we hit the target? And update some statistics.
  ++stats_.state_visits;
  if (bias_policy_->IsTargetHit(*h)) {
    is_below_target_ = true;
    ++stats_.target_visits;
    if (is_biased_iteration_) ++stats_.target_biased_visits;
  }
  // Dispatch to appropriate methods.
  if (h->IsTerminal()) {
    ++stats_.terminal_visits;
    return IterationTerminalNode(h, bs_h_all, us_h_all, exploringPl);
  }
  if (h->IsChanceNode()) {
    return IterationChanceNode(h, rm_h_pl, rm_h_opp, bs_h_all, us_h_all,
                               us_h_cn, exploringPl);
  }
  if (h->IsPlayerNode()) {
    return IterationPlayerNode(h, rm_h_pl, rm_h_opp, bs_h_all, us_h_all,
                               us_h_cn, exploringPl);
  }
  SpielFatalError("Unrecognized state type.");
}
References bias_policy_, is_below_target_, is_biased_iteration_, IterationChanceNode(), IterationPlayerNode(), IterationTerminalNode(), open_spiel::SpielFatalError(), open_spiel::algorithms::OnlineStats::state_visits, stats_, open_spiel::algorithms::OnlineStats::target_biased_visits, open_spiel::algorithms::OnlineStats::target_visits, and open_spiel::algorithms::OnlineStats::terminal_visits.
Referenced by IterationChanceNode(), RootIteration(), and SampleExistingTree().
IterationChanceNode()
double open_spiel::algorithms::OOSAlgorithm::IterationChanceNode (State * h, double rm_h_pl, double rm_h_opp, double bs_h_all, double us_h_all, double us_h_cn, Player exploringPl) protected
Definition at line 374 of file oos.cc.
{
  SPIEL_DCHECK_TRUE(h->IsChanceNode());
  const TakeAction take = SelectAction(h, IsBiasingApplicable(bs_h_all));
  const double s_ha_all = Bias(take.bs, take.us);
  SPIEL_DCHECK_GT(s_ha_all, 0);
  h->ApplyAction(take.action);
  const double u_ha =
      Iteration(h, rm_h_pl, rm_h_opp, bs_h_all * take.bs, us_h_all * take.us,
                us_h_cn * take.us, exploringPl);
  // Compute estimate of the expected utility.
  double u_h = u_ha * take.us / s_ha_all;
  SPIEL_DCHECK_FALSE(std::isnan(u_h));
  SPIEL_DCHECK_FALSE(std::isinf(u_h));
  return u_h;
}
References open_spiel::algorithms::TakeAction::action, Bias(), open_spiel::algorithms::TakeAction::bs, IsBiasingApplicable(), Iteration(), SelectAction(), SPIEL_DCHECK_FALSE, SPIEL_DCHECK_GT, SPIEL_DCHECK_TRUE, and open_spiel::algorithms::TakeAction::us.
Referenced by Iteration().
IterationPlayerNode()
double open_spiel::algorithms::OOSAlgorithm::IterationPlayerNode (State * h, double rm_h_pl, double rm_h_opp, double bs_h_all, double us_h_all, double us_h_cn, Player exploringPl) protected
Definition at line 396 of file oos.cc.
{
  SPIEL_DCHECK_TRUE(h->IsPlayerNode());
  bool exploring_move_in_node = h->CurrentPlayer() == exploringPl;
  const std::string info_state = h->InformationStateString();
  const double s_h_all = Bias(bs_h_all, us_h_all);
  SPIEL_DCHECK_GT(s_h_all, 0);
  const auto it = values_->find(info_state);
  bool is_leaf_state = it == values_->end();
  // Note: we cannot use h / aoh after this code executes,
  // as it will be set to leaf values.
  const PlayerNodeOutcome outcome =
      is_leaf_state
          ? IncrementallyBuildTree(h, info_state, s_h_all, exploringPl)
          : SampleExistingTree(h, info_state, &it->second, rm_h_pl, rm_h_opp,
                               bs_h_all, us_h_all, us_h_cn, exploringPl);
  SPIEL_DCHECK_TRUE(h->IsTerminal());
  SPIEL_DCHECK_FALSE(std::isnan(u_z_));
  SPIEL_DCHECK_FALSE(std::isnan(outcome.u_h));
  SPIEL_DCHECK_FALSE(std::isinf(outcome.u_h));
  // Note: the only probability that's missing here is rm_h_pl
  // for it to be full reach probability weighted by full sampling probability.
  double importance_sampling_ratio = rm_h_opp * us_h_cn / s_h_all;
  if (exploring_move_in_node) {
    UpdateInfoStateCumulativeRegrets(&outcome.data, outcome.action,
                                     outcome.u_ha, outcome.u_h,
                                     importance_sampling_ratio);
  } else {
    UpdateInfoStateCumulativePolicy(&outcome.data, importance_sampling_ratio);
  }
  return outcome.u_h;
}
References open_spiel::algorithms::PlayerNodeOutcome::action, Bias(), open_spiel::algorithms::PlayerNodeOutcome::data, IncrementallyBuildTree(), SampleExistingTree(), SPIEL_DCHECK_FALSE, SPIEL_DCHECK_GT, SPIEL_DCHECK_TRUE, open_spiel::algorithms::PlayerNodeOutcome::u_h, open_spiel::algorithms::PlayerNodeOutcome::u_ha, u_z_, UpdateInfoStateCumulativePolicy(), UpdateInfoStateCumulativeRegrets(), and values_.
Referenced by Iteration().
IterationTerminalNode()
double open_spiel::algorithms::OOSAlgorithm::IterationTerminalNode (State * h, double bs_h_all, double us_h_all, Player exploringPl) protected
Definition at line 365 of file oos.cc.
{
  SPIEL_DCHECK_TRUE(h->IsTerminal());
  s_z_all_ = Bias(bs_h_all, us_h_all);
  u_z_ = h->PlayerReturn(exploringPl);
  return u_z_;
}
References Bias(), s_z_all_, SPIEL_DCHECK_TRUE, and u_z_.
Referenced by Iteration().
RootIteration()
void open_spiel::algorithms::OOSAlgorithm::RootIteration (State * h, Player exploringPl) protected
Definition at line 319 of file oos.cc.
{
  ++stats_.root_visits;
  // Make sure we don't use mutable vars where we shouldn't.
  // We have bunch of not-nan tests all over the code to catch any bugs.
  u_z_ = std::numeric_limits<double>::quiet_NaN();
  s_z_all_ = std::numeric_limits<double>::quiet_NaN();
  Iteration(h,
            /*rm_h_pl=*/1.0, /*rm_h_opp=*/1.0,
            /*bs_h_all=*/1.0, /*us_h_all=*/1.0,
            /*us_h_cn=*/1.0, exploringPl);
}
References Iteration(), open_spiel::algorithms::OnlineStats::root_visits, s_z_all_, stats_, and u_z_.
Referenced by RunTargetedIterations(), and RunUnbiasedIterations().
RunTargetedIterations() [1/3]
void open_spiel::algorithms::OOSAlgorithm::RunTargetedIterations (const ActionObservationHistory & target_info_state, int iterations)
Definition at line 278 of file oos.cc.
{
  if (target_info_state.CorrespondsToInitialState())
    return RunUnbiasedIterations(iterations);
  bias_policy_->UpdateTarget(&target_info_state);
  RunTargetedIterations(iterations);
}
References bias_policy_, open_spiel::ActionObservationHistory::CorrespondsToInitialState(), RunTargetedIterations(), and RunUnbiasedIterations().
Referenced by RunTargetedIterations(), and RunTargetedIterations().
RunTargetedIterations() [2/3]
void open_spiel::algorithms::OOSAlgorithm::RunTargetedIterations (const PublicObservationHistory & target_public_state, int iterations)
Definition at line 287 of file oos.cc.
{
  if (target_public_state.CorrespondsToInitialState())
    return RunUnbiasedIterations(iterations);
  bias_policy_->UpdateTarget(&target_public_state);
  RunTargetedIterations(iterations);
}
References bias_policy_, open_spiel::PublicObservationHistory::CorrespondsToInitialState(), RunTargetedIterations(), and RunUnbiasedIterations().
RunTargetedIterations() [3/3]
void open_spiel::algorithms::OOSAlgorithm::RunTargetedIterations (int iterations) protected
Definition at line 300 of file oos.cc.
{
  if (target_biasing_ == 0.) {
    return RunUnbiasedIterations(iterations);
  }
  for (int t = 0; t < iterations; ++t) {
    for (Player exploringPl = 0; exploringPl < 2; ++exploringPl) {
      std::unique_ptr<State> h = game_->NewInitialState();
      is_biased_iteration_ = random_->RandomUniform() <= target_biasing_;
      // We always have a target, which cannot be a root node
      // (this was handled by publicly facing methods)
      is_below_target_ = false;
      if (is_biased_iteration_) stats_.biased_iterations++;
      RootIteration(h.get(), Player(exploringPl));
    }
  }
}
References open_spiel::algorithms::OnlineStats::biased_iterations, game_, is_below_target_, is_biased_iteration_, random_, RootIteration(), RunUnbiasedIterations(), stats_, and target_biasing_.
RunUnbiasedIterations()
void open_spiel::algorithms::OOSAlgorithm::RunUnbiasedIterations (int iterations)
Definition at line 264 of file oos.cc.
{
  bias_policy_->NoTargeting();
  for (int t = 0; t < iterations; ++t) {
    for (Player exploringPl = 0; exploringPl < 2; ++exploringPl) {
      std::unique_ptr<State> h = game_->NewInitialState();
      is_biased_iteration_ = false;
      is_below_target_ = true;
      RootIteration(h.get(), Player(exploringPl));
    }
  }
}
References bias_policy_, game_, is_below_target_, is_biased_iteration_, and RootIteration().
Referenced by RunTargetedIterations(), RunTargetedIterations(), and RunTargetedIterations().
SampleExistingTree()
PlayerNodeOutcome open_spiel::algorithms::OOSAlgorithm::SampleExistingTree (State * h, const std::string & info_state, CFRInfoStateValues * values, double rm_h_pl, double rm_h_opp, double bs_h_all, double us_h_all, double us_h_cn, Player exploringPl) protected
Definition at line 438 of file oos.cc.
{
  SPIEL_DCHECK_TRUE(h->IsPlayerNode());
  SPIEL_DCHECK_FALSE(std::isnan(rm_h_pl));
  SPIEL_DCHECK_FALSE(std::isnan(rm_h_opp));
  SPIEL_DCHECK_FALSE(std::isnan(bs_h_all));
  SPIEL_DCHECK_FALSE(std::isnan(us_h_all));
  SPIEL_DCHECK_FALSE(std::isnan(us_h_cn));
  const bool exploring_move_in_node = h->CurrentPlayer() == exploringPl;
  const TakeAction take = SelectAction(h, IsBiasingApplicable(bs_h_all));
  const int action_index = values->GetActionIndex(take.action);
  const double rm_ha_both = values->current_policy[action_index];
  const double s_ha_all = Bias(take.bs, take.us);
  SPIEL_DCHECK_GT(s_ha_all, 0);
  h->ApplyAction(take.action);
  const double u_ha =
      Iteration(h, (exploring_move_in_node) ? rm_h_pl * rm_ha_both : rm_h_pl,
                (exploring_move_in_node) ? rm_h_opp : rm_h_opp * rm_ha_both,
                bs_h_all * take.bs, us_h_all * take.us, us_h_cn, exploringPl);
  double u_h = u_ha * rm_ha_both / s_ha_all;
  SPIEL_DCHECK_FALSE(std::isnan(rm_ha_both));
  SPIEL_DCHECK_FALSE(std::isnan(u_h));
  return PlayerNodeOutcome{take.action, rm_ha_both, u_h, u_ha / s_ha_all,
                           *values};
}
References open_spiel::algorithms::TakeAction::action, Bias(), open_spiel::algorithms::TakeAction::bs, IsBiasingApplicable(), Iteration(), SelectAction(), SPIEL_DCHECK_FALSE, SPIEL_DCHECK_GT, SPIEL_DCHECK_TRUE, open_spiel::algorithms::TakeAction::us, and values.
Referenced by IterationPlayerNode().
SelectAction()
TakeAction open_spiel::algorithms::OOSAlgorithm::SelectAction (State * h, bool do_biased_sample) protected
Definition at line 527 of file oos.cc.
{
  const ActionsAndProbs& sample_probs = sample_policy_->GetStatePolicy(*h);
  const ActionsAndProbs& biased_probs = bias_policy_->GetStatePolicy(*h);
  // Check what comes out of policies are proper distributions.
  SPIEL_DCHECK_TRUE(IsValidProbDistribution(biased_probs));
  // All leaves must be reachable under sample policy!
  SPIEL_DCHECK_TRUE(IsPositiveProbDistribution(sample_probs));
  // When we do biased sampling, we completely ignore
  // the sample policy for choosing any actions.
  const ActionsAndProbs& followProbs =
      do_biased_sample ? biased_probs : sample_probs;
  auto [action, prob] = SampleAction(followProbs, random_->RandomUniform());
  return TakeAction{action, GetProb(sample_probs, action),
                    GetProb(biased_probs, action)};
}
References action, bias_policy_, open_spiel::GetProb(), open_spiel::algorithms::IsPositiveProbDistribution(), open_spiel::algorithms::IsValidProbDistribution(), random_, sample_policy_, open_spiel::SampleAction(), and SPIEL_DCHECK_TRUE.
Referenced by IterationChanceNode(), and SampleExistingTree().
UpdateInfoStateCumulativePolicy()
void open_spiel::algorithms::OOSAlgorithm::UpdateInfoStateCumulativePolicy (CFRInfoStateValues * values, double importance_sampling_ratio) protected
Definition at line 546 of file oos.cc.
{
  // We use stochastically weighted averaging.
  for (int i = 0; i < values->cumulative_policy.size(); i++) {
    SPIEL_DCHECK_GE(values->cumulative_policy[i], 0);
    values->cumulative_policy[i] +=
        importance_sampling_ratio * values->current_policy[i];
  }
}
References i, SPIEL_DCHECK_GE, and values.
Referenced by IterationPlayerNode().
UpdateInfoStateCumulativeRegrets()
void open_spiel::algorithms::OOSAlgorithm::UpdateInfoStateCumulativeRegrets (CFRInfoStateValues * values, Action a, double u_ha, double u_h, double importance_sampling_ratio) protected
Definition at line 556 of file oos.cc.
{
  SPIEL_DCHECK_FALSE(std::isnan(u_ha));
  SPIEL_DCHECK_FALSE(std::isnan(u_h));
  SPIEL_DCHECK_FALSE(std::isnan(importance_sampling_ratio));
  auto& regs = values->cumulative_regrets;
  const int action_index = values->GetActionIndex(a);
  for (int i = 0; i < regs.size(); i++) {
    if (i == action_index) {
      regs[i] += (u_ha - u_h) * importance_sampling_ratio;
    } else {
      regs[i] += (-u_h) * importance_sampling_ratio;
    }
  }
  values->ApplyRegretMatching();
}
References a, i, SPIEL_DCHECK_FALSE, and values.
Referenced by IterationPlayerNode().
Member Data Documentation
bias_policy_
std::unique_ptr<TargetedPolicy> open_spiel::algorithms::OOSAlgorithm::bias_policy_ protected
Definition at line 344 of file oos.h.
Referenced by Iteration(), OOSAlgorithm(), OOSAlgorithm(), RunTargetedIterations(), RunTargetedIterations(), RunUnbiasedIterations(), and SelectAction().
default_policy_
std::shared_ptr<Policy> open_spiel::algorithms::OOSAlgorithm::default_policy_ protected
Definition at line 345 of file oos.h.
Referenced by AveragePolicy(), and CurrentPolicy().
game_
const std::shared_ptr<const Game> open_spiel::algorithms::OOSAlgorithm::game_ protected
Definition at line 340 of file oos.h.
Referenced by OOSAlgorithm(), RunTargetedIterations(), and RunUnbiasedIterations().
is_below_target_
bool open_spiel::algorithms::OOSAlgorithm::is_below_target_ = false protected
Definition at line 357 of file oos.h.
Referenced by IsBiasingApplicable(), Iteration(), RunTargetedIterations(), and RunUnbiasedIterations().
is_biased_iteration_
bool open_spiel::algorithms::OOSAlgorithm::is_biased_iteration_ = false protected
Definition at line 352 of file oos.h.
Referenced by IsBiasingApplicable(), Iteration(), RunTargetedIterations(), and RunUnbiasedIterations().
random_
std::unique_ptr<Random> open_spiel::algorithms::OOSAlgorithm::random_ protected
Definition at line 342 of file oos.h.
Referenced by IncrementallyBuildTree(), RunTargetedIterations(), and SelectAction().
s_z_all_
double open_spiel::algorithms::OOSAlgorithm::s_z_all_ = -1 protected
Definition at line 360 of file oos.h.
Referenced by IncrementallyBuildTree(), IterationTerminalNode(), and RootIteration().
sample_policy_
std::unique_ptr<Policy> open_spiel::algorithms::OOSAlgorithm::sample_policy_ protected
Definition at line 343 of file oos.h.
Referenced by OOSAlgorithm(), and SelectAction().
stats_
OnlineStats open_spiel::algorithms::OOSAlgorithm::stats_ protected
Definition at line 366 of file oos.h.
Referenced by GetStats(), IncrementallyBuildTree(), Iteration(), OOSAlgorithm(), OOSAlgorithm(), RootIteration(), and RunTargetedIterations().
target_biasing_
const double open_spiel::algorithms::OOSAlgorithm::target_biasing_ protected
Definition at line 348 of file oos.h.
Referenced by Bias(), OOSAlgorithm(), and RunTargetedIterations().
u_z_
double open_spiel::algorithms::OOSAlgorithm::u_z_ = 0.0 protected
Definition at line 362 of file oos.h.
Referenced by IncrementallyBuildTree(), IterationPlayerNode(), IterationTerminalNode(), and RootIteration().
values_
std::unique_ptr<OOSInfoStateValuesTable> open_spiel::algorithms::OOSAlgorithm::values_ protected
Definition at line 341 of file oos.h.
Referenced by AveragePolicy(), CurrentPolicy(), IncrementallyBuildTree(), IterationPlayerNode(), and OOSAlgorithm().
The documentation for this class was generated from the following files:
open_spiel/algorithms/oos.h
open_spiel/algorithms/oos.cc