open spiel: open_spiel::algorithms::HistoryNode Class Reference
open_spiel::algorithms::HistoryNode Class Reference
#include <history_tree.h>
Public Member Functions
HistoryNode (Player player_id, std::unique_ptr< State > game_state)
State * GetState ()
const std::string & GetInfoState ()
const std::string & GetHistory ()
const StateType & GetType ()
double GetValue () const
Action NumChildren () const
void AddChild (Action outcome, std::pair< double, std::unique_ptr< HistoryNode > > child)
std::vector< Action > GetChildActions () const
std::pair< double, HistoryNode * > GetChild (Action outcome)
Static Public Attributes
static constexpr const char * kChanceNodeInfostateString = "Chance Node"
static constexpr const char * kTerminalNodeInfostateString = "Terminal node"
Detailed Description
Definition at line 37 of file history_tree.h.
Constructor & Destructor Documentation
HistoryNode()
open_spiel::algorithms::HistoryNode::HistoryNode (Player player_id, std::unique_ptr< State > game_state)
Definition at line 82 of file history_tree.cc.
    : state_(std::move(game_state)),
      history_(state_->HistoryString()),
      type_(state_->GetType()) {
  // Unless it's the opposing player's turn, we always view the game from the
  // view of player player_id.
  if (type_ == StateType::kDecision && state_->CurrentPlayer() != player_id) {
    infostate_ = state_->InformationStateString();
  } else if (type_ == StateType::kChance) {
    infostate_ = kChanceNodeInfostateString;
  } else if (type_ == StateType::kTerminal) {
    infostate_ = kTerminalNodeInfostateString;
  } else {
    infostate_ = state_->InformationStateString(player_id);
  }
  // Compute & store the legal actions so we can check that all actions we're
  // adding are legal.
  for (Action action : state_->LegalActions()) legal_actions_.insert(action);
  if (type_ == StateType::kTerminal) value_ = state_->PlayerReturn(player_id);
}
References action, absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), open_spiel::kChance, kChanceNodeInfostateString, open_spiel::kDecision, open_spiel::kTerminal, and kTerminalNodeInfostateString.
Member Function Documentation
AddChild()
void open_spiel::algorithms::HistoryNode::AddChild (Action outcome, std::pair< double, std::unique_ptr< HistoryNode > > child)
Definition at line 103 of file history_tree.cc.
{
  if (!legal_actions_.count(outcome)) SpielFatalError("Child is not legal.");
  if (child.second == nullptr) {
    SpielFatalError("Error inserting child; child is null.");
  }
  SPIEL_CHECK_PROB_TOLERANCE(child.first, ProbabilityDefaultTolerance());
  child_info_[outcome] = std::move(child);
  if (child_info_.size() > legal_actions_.size()) {
    SpielFatalError("More children than legal actions.");
  }
}
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::count(), open_spiel::ProbabilityDefaultTolerance(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::size(), SPIEL_CHECK_PROB_TOLERANCE, and open_spiel::SpielFatalError().
GetChild()
std::pair< double, HistoryNode * > open_spiel::algorithms::HistoryNode::GetChild (Action outcome)
Definition at line 116 of file history_tree.cc.
{
  auto it = child_info_.find(outcome);
  if (it == child_info_.end()) {
    SpielFatalError("Error getting child; action not found.");
  }
  // it->second.first is the probability associated with outcome, so as it is a
  // probability, it must be in [0, 1].
  SPIEL_CHECK_PROB_TOLERANCE(it->second.first, ProbabilityDefaultTolerance());
  std::pair<double, HistoryNode*> child =
      std::make_pair(it->second.first, it->second.second.get());
  if (child.second == nullptr) {
    SpielFatalError("Error getting child; child is null.");
  }
  return child;
}
References open_spiel::ProbabilityDefaultTolerance(), SPIEL_CHECK_PROB_TOLERANCE, and open_spiel::SpielFatalError().
Referenced by open_spiel::algorithms::TabularBestResponse::BestResponseAction(), open_spiel::algorithms::TabularBestResponse::BestResponseActions(), and open_spiel::algorithms::TabularBestResponse::BestResponseActionValues().
GetChildActions()
std::vector< Action > open_spiel::algorithms::HistoryNode::GetChildActions () const
Definition at line 132 of file history_tree.cc.
{
  std::vector<Action> actions;
  actions.reserve(child_info_.size());
  for (const auto& [action, _] : child_info_) actions.push_back(action);
  return actions;
}
References action.
GetHistory()
const std::string & open_spiel::algorithms::HistoryNode::GetHistory () inline
Definition at line 50 of file history_tree.h.
{ return history_; }
Referenced by open_spiel::algorithms::TabularBestResponse::BestResponseAction(), open_spiel::algorithms::TabularBestResponse::BestResponseActions(), and open_spiel::algorithms::TabularBestResponse::BestResponseActionValues().
GetInfoState()
const std::string & open_spiel::algorithms::HistoryNode::GetInfoState () inline
Definition at line 48 of file history_tree.h.
{ return infostate_; }
GetState()
State * open_spiel::algorithms::HistoryNode::GetState () inline
Definition at line 46 of file history_tree.h.
{ return state_.get(); }
GetType()
const StateType & open_spiel::algorithms::HistoryNode::GetType () inline
Definition at line 52 of file history_tree.h.
{ return type_; }
Referenced by open_spiel::algorithms::TabularBestResponse::Value().
GetValue()
double open_spiel::algorithms::HistoryNode::GetValue () const inline
Definition at line 54 of file history_tree.h.
{ return value_; }
NumChildren()
Action open_spiel::algorithms::HistoryNode::NumChildren () const inline
Definition at line 56 of file history_tree.h.
{ return child_info_.size(); }
Member Data Documentation
kChanceNodeInfostateString
const char* open_spiel::algorithms::HistoryNode::kChanceNodeInfostateString = "Chance Node" static constexpr
Definition at line 41 of file history_tree.h.
Referenced by HistoryNode().
kTerminalNodeInfostateString
const char* open_spiel::algorithms::HistoryNode::kTerminalNodeInfostateString = "Terminal node" static constexpr
Definition at line 42 of file history_tree.h.
Referenced by HistoryNode().
The documentation for this class was generated from the following files:
open_spiel/algorithms/history_tree.h
open_spiel/algorithms/history_tree.cc