open spiel: open_spiel::deep_sea::DeepSeaState Class Reference
open_spiel::deep_sea::DeepSeaState Class Reference
#include <deep_sea.h>
Public Member Functions
DeepSeaState (const std::shared_ptr< const Game > game)
DeepSeaState (const DeepSeaState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action move) override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 57 of file deep_sea.h.
Constructor & Destructor Documentation
DeepSeaState() [1/2]
open_spiel::deep_sea::DeepSeaState::DeepSeaState (const std::shared_ptr< const Game > game)
Definition at line 64 of file deep_sea.cc.
                                                         : State(game) {
  SPIEL_CHECK_TRUE(game);
  const DeepSeaGame& parent_game = static_cast<const DeepSeaGame&>(*game);
  size_ = parent_game.MaxGameLength();
  move_cost_ = -parent_game.UnscaledMoveCost() / size_;
  action_mapping_ = parent_game.ActionMapping();
}
References open_spiel::deep_sea::DeepSeaGame::ActionMapping(), open_spiel::deep_sea::DeepSeaGame::MaxGameLength(), SPIEL_CHECK_TRUE, and open_spiel::deep_sea::DeepSeaGame::UnscaledMoveCost().
Referenced by Clone().
DeepSeaState() [2/2]
open_spiel::deep_sea::DeepSeaState::DeepSeaState (const DeepSeaState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::deep_sea::DeepSeaState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 82 of file deep_sea.cc.
{
  SPIEL_CHECK_EQ(player, 0);
  return action_id ? "RIGHT" : "LEFT";
}
References player, and SPIEL_CHECK_EQ.
Clone()
std::unique_ptr< State > open_spiel::deep_sea::DeepSeaState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 151 of file deep_sea.cc.
{
  return std::unique_ptr<State>(new DeepSeaState(*this));
}
References DeepSeaState().
CurrentPlayer()
int open_spiel::deep_sea::DeepSeaState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 72 of file deep_sea.cc.
{
  if (IsTerminal()) return kTerminalPlayerId;
  return 0;
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::deep_sea::DeepSeaState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 174 of file deep_sea.cc.
{
  const int i = player_row_ * size_ + player_col_;
  const bool action_right = move == action_mapping_[i];
  if (action_right) {
    ++player_col_;
  } else if (player_col_ > 0) {
    --player_col_;
  }
  ++player_row_;
  direction_history_.push_back(action_right);
}
References i.
IsTerminal()
bool open_spiel::deep_sea::DeepSeaState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 106 of file deep_sea.cc.
{ return player_row_ == size_; }
Referenced by CurrentPlayer(), LegalActions(), Returns(), and Rewards().
LegalActions()
std::vector< Action > open_spiel::deep_sea::DeepSeaState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 77 of file deep_sea.cc.
{
  if (IsTerminal()) return {};
  return {0, 1};
}
References IsTerminal().
ObservationString()
std::string open_spiel::deep_sea::DeepSeaState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 129 of file deep_sea.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // We need to account for the possibility that `player_row == size_` at
  // terminal states, so that's why we add the +1.
  std::string str((size_ + 1) * size_, '.');
  str[player_row_ * size_ + player_col_] = 'x';
  return str;
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
ObservationTensor()
void open_spiel::deep_sea::DeepSeaState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 140 of file deep_sea.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::fill(values.begin(), values.end(), 0.);
  SPIEL_CHECK_EQ(values.size(), size_ * size_);
  if (player_row_ < size_ && player_col_ < size_)
    values[player_row_ * size_ + player_col_] = 1.0;
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::deep_sea::DeepSeaState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 119 of file deep_sea.cc.
{
  double reward_sum = 0;
  for (bool direction : direction_history_)
    if (direction) reward_sum += move_cost_;
  if (IsTerminal() && player_col_ == size_) {
    reward_sum += 1;
  }
  return {reward_sum};
}
References IsTerminal().
Rewards()
std::vector< double > open_spiel::deep_sea::DeepSeaState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 108 of file deep_sea.cc.
{
  double reward = 0;
  if (!direction_history_.empty() && direction_history_.back()) {
    reward += move_cost_;
  }
  if (IsTerminal() && player_col_ == size_) {
    reward += 1;
  }
  return {reward};
}
References IsTerminal().
ToString()
std::string open_spiel::deep_sea::DeepSeaState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 88 of file deep_sea.cc.
{
  std::string str;
  str.reserve((size_ + 1) * (size_ + 2));
  for (int r = 0; r < size_ + 1; ++r) {
    for (int c = 0; c < size_ + 1; ++c) {
      if (player_row_ == r && player_col_ == c) {
        str += "x";
      } else if (r < size_ && c <= r) {
        str += action_mapping_[r * size_ + c] ? 'R' : 'L';
      } else {
        str += ".";
      }
    }
    str += "\n";
  }
  return str;
}
References r.
UndoAction()
void open_spiel::deep_sea::DeepSeaState::UndoAction (Player player, Action move) override virtual
Reimplemented from open_spiel::State.
Definition at line 155 of file deep_sea.cc.
{
  // Can only reliably undo by replaying the actions. This is because moving
  // left from column 0 is a no-op, so we can't deduce the previous column if
  // we're now at column 0.
  direction_history_.pop_back();
  history_.pop_back();
  --move_number_;
  player_row_ = 0;
  player_col_ = 0;
  for (auto action_right : direction_history_) {
    if (action_right) {
      ++player_col_;
    } else if (player_col_ > 0) {
      --player_col_;
    }
    ++player_row_;
  }
}
References open_spiel::State::history_, and open_spiel::State::move_number_.
The documentation for this class was generated from the following files:
open_spiel/games/deep_sea/deep_sea.h
open_spiel/games/deep_sea/deep_sea.cc