open spiel: open_spiel::tensor_game::TensorGame Class Reference
open_spiel::tensor_game::TensorGame Class Reference
#include <tensor_game.h>
Public Member Functions
TensorGame (GameType game_type, GameParameters game_parameters, std::vector< std::vector< std::string > > action_names, std::vector< std::vector< double > > utilities)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
std::string ActionToString (Player player, Action action) const override
const std::vector< int > & Shape () const
const double PlayerUtility (const Player player, const std::vector< Action > &actions) const
const std::vector< double > & PlayerUtilities (const Player player) const
const std::string & ActionName (const Player player, const Action &action) const
bool operator== (const Game &other_game) const override
bool ApproxEqual (const Game &other_game, double tolerance) const
std::vector< double > GetUtilities (const std::vector< Action > &joint_action) const override
double GetUtility (Player player, const std::vector< Action > &joint_action) const override
std::shared_ptr< const matrix_game::MatrixGame > AsMatrixGame () const
Public Member Functions inherited from open_spiel::NormalFormGame
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
absl::optional< double > UtilitySum () const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::NormalFormGame
NormalFormGame (GameType game_type, GameParameters game_parameters)
Protected Member Functions inherited from open_spiel::SimMoveGame
SimMoveGame (GameType game_type, GameParameters game_parameters)
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 36 of file tensor_game.h.
Constructor & Destructor Documentation
TensorGame()
open_spiel::tensor_game::TensorGame::TensorGame (GameType game_type, GameParameters game_parameters, std::vector< std::vector< std::string > > action_names, std::vector< std::vector< double > > utilities) inline
Definition at line 41 of file tensor_game.h.
      : NormalFormGame(std::move(game_type), std::move(game_parameters)),
        action_names_(std::move(action_names)),
        utilities_(std::move(utilities)),
        shape_(utilities_.size()) {
    int size = 1;
    for (Player player = 0; player < action_names_.size(); ++player) {
      size *= action_names_[player].size();
      shape_[player] = action_names_[player].size();
    }
    ComputeMinMaxUtility();
    SPIEL_CHECK_TRUE(std::all_of(utilities_.begin(), utilities_.end(),
                                 [size](const auto& player_utils) {
                                   return player_utils.size() == size;
                                 }));
  }
References SPIEL_CHECK_TRUE.
Member Function Documentation
ActionName()
const std::string & open_spiel::tensor_game::TensorGame::ActionName (const Player player, const Action & action) const inline
Definition at line 89 of file tensor_game.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, NumPlayers());
    return action_names_[player][action];
  }
References NumPlayers(), SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Referenced by ActionToString(), and open_spiel::tensor_game::TensorState::ActionToString().
ActionToString()
std::string open_spiel::tensor_game::TensorGame::ActionToString (Player player, Action action) const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 73 of file tensor_game.h.
{
    return ActionName(player, action);
  }
References ActionName().
ApproxEqual()
bool open_spiel::tensor_game::TensorGame::ApproxEqual (const Game & other_game, double tolerance) const inline
Definition at line 101 of file tensor_game.h.
{
    const auto& other = down_cast<const TensorGame&>(other_game);
    if (shape_ != other.shape_) {
      return false;
    }
    for (Player p = 0; p < NumPlayers(); ++p) {
      if (!AllNear(utilities_[p], other.utilities_[p], tolerance)) {
        return false;
      }
    }
    return true;
  }
References open_spiel::AllNear(), open_spiel::down_cast(), and NumPlayers().
AsMatrixGame()
std::shared_ptr< const matrix_game::MatrixGame > open_spiel::tensor_game::TensorGame::AsMatrixGame () const inline
Definition at line 130 of file tensor_game.h.
{
    SPIEL_CHECK_EQ(NumPlayers(), 2);
    const GameType& game_type = GetType();
    return matrix_game::CreateMatrixGame(
        game_type.short_name, game_type.long_name,
        action_names_[0], action_names_[1],
        utilities_[0], utilities_[1]);
  }
References open_spiel::matrix_game::CreateMatrixGame(), open_spiel::Game::GetType(), open_spiel::GameType::long_name, NumPlayers(), open_spiel::GameType::short_name, and SPIEL_CHECK_EQ.
GetUtilities()
std::vector< double > open_spiel::tensor_game::TensorGame::GetUtilities (const std::vector< Action > & joint_action) const inline override virtual
Reimplemented from open_spiel::NormalFormGame.
Definition at line 114 of file tensor_game.h.
                     {
    int idx = index(joint_action);
    std::vector<double> utilities;
    utilities.reserve(NumPlayers());
    for (Player p = 0; p < NumPlayers(); ++p) {
      utilities.push_back(utilities_[p][idx]);
    }
    return utilities;
  }
References NumPlayers().
GetUtility()
double open_spiel::tensor_game::TensorGame::GetUtility (Player player, const std::vector< Action > & joint_action) const inline override virtual
Reimplemented from open_spiel::NormalFormGame.
Definition at line 125 of file tensor_game.h.
                     {
    return PlayerUtility(player, joint_action);
  }
References PlayerUtility().
MaxUtility()
double open_spiel::tensor_game::TensorGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 71 of file tensor_game.h.
{ return max_utility_; }
MinUtility()
double open_spiel::tensor_game::TensorGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 69 of file tensor_game.h.
{ return min_utility_; }
NewInitialState()
std::unique_ptr< State > open_spiel::tensor_game::TensorGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 90 of file tensor_game.cc.
{
  return std::unique_ptr<State>(new TensorState(shared_from_this()));
}
NumDistinctActions()
int open_spiel::tensor_game::TensorGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 61 of file tensor_game.h.
{
    return *std::max_element(begin(shape_), end(shape_));
  }
NumPlayers()
int open_spiel::tensor_game::TensorGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 67 of file tensor_game.h.
{ return utilities_.size(); }
Referenced by ActionName(), ApproxEqual(), AsMatrixGame(), GetUtilities(), PlayerUtilities(), and PlayerUtility().
operator==()
bool open_spiel::tensor_game::TensorGame::operator== (const Game & other_game) const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 96 of file tensor_game.h.
{
    const auto& other = down_cast<const TensorGame&>(other_game);
    return (shape_ == other.shape_ && utilities_ == other.utilities_);
  }
References open_spiel::down_cast().
PlayerUtilities()
const std::vector< double > & open_spiel::tensor_game::TensorGame::PlayerUtilities (const Player player) const inline
Definition at line 84 of file tensor_game.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, NumPlayers());
    return utilities_[player];
  }
References NumPlayers(), SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
PlayerUtility()
const double open_spiel::tensor_game::TensorGame::PlayerUtility (const Player player, const std::vector< Action > & actions) const inline
Definition at line 78 of file tensor_game.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, NumPlayers());
    return utilities_[player][index(actions)];
  }
References NumPlayers(), SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Referenced by GetUtility(), and open_spiel::tensor_game::TensorState::Returns().
Shape()
const std::vector< int > & open_spiel::tensor_game::TensorGame::Shape () const inline
Definition at line 77 of file tensor_game.h.
{ return shape_; }
Referenced by open_spiel::tensor_game::TensorState::DoApplyActions(), and open_spiel::tensor_game::TensorState::LegalActions().
The documentation for this class was generated from the following files:
open_spiel/tensor_game.h
open_spiel/tensor_game.cc