open spiel: open_spiel::coordinated_mp::PenniesObserver Class Reference
open_spiel::coordinated_mp::PenniesObserver Class Reference
Public Member Functions
PenniesObserver (IIGObservationType iig_obs_type)
void WriteTensor (const State &observed_state, int player, Allocator *allocator) const override
std::string StringFrom (const State &observed_state, int player) const
Public Member Functions inherited from open_spiel::Observer
Observer (bool has_string, bool has_tensor)
bool HasString () const
bool HasTensor () const
virtual ~Observer ()=default
Additional Inherited Members
Protected Attributes inherited from open_spiel::Observer
bool has_string_
bool has_tensor_
Detailed Description
Definition at line 59 of file coordinated_mp.cc.
Constructor & Destructor Documentation
PenniesObserver()
open_spiel::coordinated_mp::PenniesObserver::PenniesObserver (IIGObservationType iig_obs_type) inline
Definition at line 61 of file coordinated_mp.cc.
      : Observer(/*has_string=*/true, /*has_tensor=*/false),
        iig_obs_type_(iig_obs_type) {}
Member Function Documentation
StringFrom()
std::string open_spiel::coordinated_mp::PenniesObserver::StringFrom (const State & observed_state, int player) const inline virtual
Implements open_spiel::Observer.
Definition at line 70 of file coordinated_mp.cc.
{
    const PenniesState &state =
        open_spiel::down_cast<const PenniesState &>(observed_state);
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, state.num_players_);
    std::string str;
    if (iig_obs_type_.perfect_recall) {
      absl::StrAppend(&str, state.MoveNumber());
    }
    if (iig_obs_type_.perfect_recall &&
        (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers ||
         (player == 0 &&
          iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer))) {
      if (state.actionA_ == kHeads) str.push_back('H');
      if (state.actionA_ == kTails) str.push_back('T');
    }
    if (iig_obs_type_.private_info != PrivateInfoType::kNone) {
      // TODO(author13)
      // This information appears to be private information for both players,
      // but not public information. Is this a bug?
      if (state.infoset_ == kTop) str.push_back('T');
      if (state.infoset_ == kBottom) str.push_back('B');
    }
    if (iig_obs_type_.perfect_recall &&
        (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers ||
         (player == 1 &&
          iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer))) {
      if (state.actionB_ == kHeads) str.push_back('H');
      if (state.actionB_ == kTails) str.push_back('T');
    }
    if (iig_obs_type_.public_info &&
        iig_obs_type_.private_info == PrivateInfoType::kNone) {
      if (state.IsInitialState())
        absl::StrAppend(&str, "start game");
      else
        absl::StrAppend(&str, "clock tick");
    }
    return str;
  }
References open_spiel::down_cast(), open_spiel::kAllPlayers, open_spiel::coordinated_mp::kBottom, open_spiel::coordinated_mp::kHeads, open_spiel::kNone, open_spiel::kSinglePlayer, open_spiel::coordinated_mp::kTails, open_spiel::coordinated_mp::kTop, open_spiel::IIGObservationType::perfect_recall, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, state, and absl::StrAppend().
WriteTensor()
void open_spiel::coordinated_mp::PenniesObserver::WriteTensor (const State & observed_state, int player, Allocator * allocator) const inline override virtual
Implements open_spiel::Observer.
Definition at line 65 of file coordinated_mp.cc.
{
    SpielFatalError("Unimplemented");
  }
References open_spiel::SpielFatalError().
The documentation for this class was generated from the following file:
open_spiel/games/coordinated_mp/coordinated_mp.cc