open spiel: open_spiel.python.egt.visualization.Dynamics3x3Axes Class Reference
open_spiel.python.egt.visualization.Dynamics3x3Axes Class Reference
Public Member Functions
__init__ (self, fig, rect, *args, **kwargs)
cla (self)
get_labels (self)
set_labels (self, labels, padding=0.02)
can_zoom (self)
can_pan (self)
plot (self, points, **kwargs)
scatter (self, points, **kwargs)
quiver (self, dynamics, step=0.05, boundary=False, normalize=False, pivot="middle", **kwargs)
streamplot (self, dynamics, initial_points=None, dt=0.01, density=1., min_length=0.4, linewidth=None, color="k", **kwargs)
Public Attributes
bgpatch
grid
ticks
tick_labels
Static Public Attributes
str name = "3x3"
Protected Member Functions
_create_bgpatch (self, **kwargs)
_create_grid (self, step=0.2, **kwargs)
_create_ticks (self, step=0.2, tick_length=0.025, **kwargs)
_create_labels (self, labels, padding)
_linecollection (self, points, linewidth, color)
_integrate (self, x, func, mask, dt, min_dist=0.01)
Protected Attributes
_simplex_transform
_labels
_VERTICES
Static Protected Attributes
list _VERTICES = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
Properties
labels = property(get_labels, set_labels)
Detailed Description
Axes for 3x3 game dynamics.
This class provides plotting functions for dynamics in symmetric 3x3 games.
Attributes:
  name: Used for projection keyword when creating a new axes.
Definition at line 236 of file visualization.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.egt.visualization.Dynamics3x3Axes.__init__ (self, fig, rect, * args, ** kwargs)
Definition at line 247 of file visualization.py.
  def __init__(self, fig, rect, *args, **kwargs):
    self._simplex_transform = SimplexTransform()
    self._labels = None
    super(axes.Axes, self).__init__(fig, rect, *args, **kwargs)
Member Function Documentation
_create_bgpatch()
open_spiel.python.egt.visualization.Dynamics3x3Axes._create_bgpatch (self, ** kwargs) protected
Definition at line 287 of file visualization.py.
  def _create_bgpatch(self, **kwargs):
    codes = [Path.MOVETO] + [Path.LINETO] * 2 + [Path.CLOSEPOLY]
    vertices = self._VERTICES + [self._VERTICES[0]]
    vertices = self._simplex_transform.transform(np.array(vertices))
    return PathPatch(Path(vertices, codes), **kwargs)
References open_spiel.python.egt.visualization.Dynamics3x3Axes._simplex_transform, and open_spiel.python.egt.visualization.Dynamics3x3Axes._VERTICES.
_create_grid()
open_spiel.python.egt.visualization.Dynamics3x3Axes._create_grid (self, step = 0.2, ** kwargs) protected
Definition at line 293 of file visualization.py.
  def _create_grid(self, step=0.2, **kwargs):
    x = np.arange(step, 1., step)
    n = x.shape[0]
    line_start, line_end = np.zeros((n, 3)), np.zeros((n, 3))
    line_start[:, 0] = line_end[::-1, 1] = x
    line_start[:, 2] = line_end[::-1, 0] = 1. - x
    segs = np.zeros((3 * n, 2, 2))
    for i, perm in enumerate([(0, 2, 1), (1, 0, 2), (2, 1, 0)]):
      start = self._simplex_transform.transform(line_start[:, perm])
      end = self._simplex_transform.transform(line_end[:, perm])
      segs[i * n:(i + 1) * n, 0, :], segs[i * n:(i + 1) * n, 1, :] = start, end
    line_segments = LineCollection(segs, **kwargs)
    return line_segments
References open_spiel.python.egt.visualization.Dynamics3x3Axes._simplex_transform.
_create_labels()
open_spiel.python.egt.visualization.Dynamics3x3Axes._create_labels (self, labels, padding) protected
Definition at line 343 of file visualization.py.
  def _create_labels(self, labels, padding):
    artists = []
    aligns = ["top", "top", "bottom"]
    for label, pos, align in zip(labels, self._VERTICES, aligns):
      x, y = self._simplex_transform.transform(pos)
      labelpad = padding if align == "bottom" else -padding
      label = Text(
          x=x,
          y=y + labelpad,
          text=label,
          fontproperties=font_manager.FontProperties(
              size=rcParams["axes.labelsize"],
              weight=rcParams["axes.labelweight"]),
          color=rcParams["axes.labelcolor"],
          verticalalignment=align,
          horizontalalignment="center")
      artists.append(label)
    return artists
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes.set_labels().
_create_ticks()
open_spiel.python.egt.visualization.Dynamics3x3Axes._create_ticks (self, step = 0.2, tick_length = 0.025, ** kwargs) protected
Definition at line 307 of file visualization.py.
  def _create_ticks(self, step=0.2, tick_length=0.025, **kwargs):
    x = np.arange(step, 1., step)
    n = x.shape[0]
    tick_start, tick_end = np.zeros((n, 3)), np.zeros((n, 3))
    tick_start[:, 0] = x
    tick_start[:, 2] = 1. - x
    tick_end[:, 0] = x
    tick_end[:, 2] = 1. - x + tick_length
    tick_end[:, 1] = -tick_length
    tick_labels = []
    ha = ["center", "left", "right"]
    va = ["top", "bottom", "center"]
    rot = [-60, 60, 0]
    segs = np.zeros((n * 3, 2, 2))
    for i, perm in enumerate([(0, 2, 1), (1, 0, 2), (2, 1, 0)]):
      start = self._simplex_transform.transform(tick_start[:, perm])
      end = self._simplex_transform.transform(tick_end[:, perm])
      segs[i * n:(i + 1) * n, 0, :], segs[i * n:(i + 1) * n, 1, :] = start, end
      for j, x_ in enumerate(x):
        tick_labels.append(
            Text(
                end[j, 0],
                end[j, 1],
                "{0:.1f}".format(x_),
                horizontalalignment=ha[i],
                verticalalignment=va[i],
                rotation=rot[i],
                color=kwargs["color"],
                fontsize=rcParams["xtick.labelsize"]))
    line_segments = LineCollection(segs, **kwargs)
    return line_segments, tick_labels
References open_spiel.python.egt.visualization.Dynamics3x3Axes._simplex_transform.
_integrate()
open_spiel.python.egt.visualization.Dynamics3x3Axes._integrate (self, x, func, mask, dt, min_dist = 0.01) protected
Definition at line 461 of file visualization.py.
  def _integrate(self, x, func, mask, dt, min_dist=0.01):
    cells = []
    trajectory = [x]
    x_ = x
    for dt in [dt, -dt]:
      while not mask[x]:
        cell = mask.index(x)
        cells.append(cell)
        while mask.index(x) == cell:
          # integrate up to cell boundary
          if np.sqrt(np.sum((x_ - x)**2)) > min_dist:
            x_ = x
            if dt > 0:
              trajectory.append(x)
            else:
              trajectory.insert(0, x)
          x = _rk12_step(func, x, dt=dt)
        if dt > 0:
          mask[trajectory[-1]] = True
        else:
          mask[trajectory[0]] = True
      # restore to integrate backwards
      if dt > 0. and len(cells):
        trajectory.append(_rk12_step(func, x, dt=-dt))
        mask[mask.point(cells[0])] = False
        x = trajectory[0]
        x_ = x
      else:
        trajectory.insert(0, _rk12_step(func, x, dt=-dt))
    return (np.array(trajectory), cells) if len(trajectory) > 2 else None
References open_spiel.python.egt.visualization._rk12_step(), and len.
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes.streamplot().
_linecollection()
open_spiel.python.egt.visualization.Dynamics3x3Axes._linecollection (self, points, linewidth, color) protected
Definition at line 455 of file visualization.py.
  def _linecollection(self, points, linewidth, color):
    points = self._simplex_transform.transform(points).reshape(-1, 1, 2)
    segments = np.concatenate([points[:-1], points[1:]], axis=1)
    lc = LineCollection(segments, linewidths=linewidth, color=color)
    return lc
References open_spiel.python.egt.visualization.Dynamics3x3Axes._simplex_transform.
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes.streamplot().
can_pan()
open_spiel.python.egt.visualization.Dynamics3x3Axes.can_pan (self)
Definition at line 380 of file visualization.py.
  def can_pan(self):
    return False
can_zoom()
open_spiel.python.egt.visualization.Dynamics3x3Axes.can_zoom (self)
Definition at line 377 of file visualization.py.
  def can_zoom(self):
    return False
cla()
open_spiel.python.egt.visualization.Dynamics3x3Axes.cla (self)
Clear the current axes.
Definition at line 252 of file visualization.py.
  def cla(self):
    """Clear the current axes."""
    super(axes.Axes, self).cla()
    self.set_aspect("equal")
    self.get_xaxis().set_visible(False)
    self.get_yaxis().set_visible(False)
    self.patch.set_visible(False)
    self.set_frame_on(False)
    # draw invisiple vertices to set x/y limits of plot
    self.scatter(Dynamics3x3Axes._VERTICES, alpha=0.)
    self.margins(0.15)
    self.bgpatch = self._create_bgpatch(
        facecolor=rcParams["axes.facecolor"],
        edgecolor=rcParams["axes.edgecolor"],
        linewidth=rcParams["axes.linewidth"],
        zorder=-1)
    self.add_artist(self.bgpatch)
    if rcParams["axes.grid"]:
      self.grid = self._create_grid(
          color=rcParams["grid.color"],
          alpha=rcParams["grid.alpha"],
          linestyle=rcParams["grid.linestyle"],
          linewidth=rcParams["grid.linewidth"],
          zorder=0)
      self.add_collection(self.grid)
    self.ticks, self.tick_labels = self._create_ticks(
        color=rcParams["xtick.color"], zorder=0)
    self.add_collection(self.ticks)
    for label in self.tick_labels:
      self.add_artist(label)
References open_spiel.python.egt.visualization.Dynamics3x3Axes.cla(), DDSInfo.patch, and open_spiel.python.egt.visualization.Dynamics3x3Axes.scatter().
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes.cla().
get_labels()
open_spiel.python.egt.visualization.Dynamics3x3Axes.get_labels (self)
Definition at line 362 of file visualization.py.
  def get_labels(self):
    return self._labels
References open_spiel.python.egt.visualization.Dynamics3x3Axes._labels.
plot()
open_spiel.python.egt.visualization.Dynamics3x3Axes.plot (self, points, ** kwargs)
Creates a line plot.
Args:
  points: Points in policy space.
  **kwargs: Additional keyword arguments passed on to `Axes.plot`.
Returns:
  The line plot.
Definition at line 383 of file visualization.py.
  def plot(self, points, **kwargs):
    """Creates a line plot.
    Args:
      points: Points in policy space.
      **kwargs: Additional keyword arguments passed on to `Axes.plot`.
    Returns:
      The line plot.
    """
    points = np.array(points)
    assert points.shape[1] == 3
    points = self._simplex_transform.transform(points)
    return super(Dynamics3x3Axes, self).plot(points[:, 0], points[:, 1],
                                             **kwargs)
References open_spiel.python.egt.visualization.Dynamics3x3Axes._simplex_transform, and open_spiel.python.egt.visualization.Dynamics3x3Axes.plot().
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes.plot().
quiver()
open_spiel.python.egt.visualization.Dynamics3x3Axes.quiver (self, dynamics, step = 0.05, boundary = False, normalize = False, pivot = "middle", ** kwargs)
Visualizes the dynamics as a directional field plot.
Args:
  dynamics: Population dynamics of type `dynamics.SinglePopulationDynamics`.
  step: Distance between arrows along one dimension.
  boundary: Include arrows on the boundary/face of the simplex.
  normalize: Normalize each arrow to unit-length.
  pivot: In `{"tail", "middle", "tip"}`, optional, default: "middle". The
    part of the arrow that is anchored to the X, Y grid. The arrow rotates
    about this point.
  **kwargs: Additional keyword arguments passed on to `Axes.quiver`.
Returns:
  The `quiver.Quiver` object created by calling `Axes.quiver`.
Definition at line 415 of file visualization.py.
             **kwargs):
    """Visualizes the dynamics as a directional field plot.
    Args:
      dynamics: Population dynamics of type `dynamics.SinglePopulationDynamics`.
      step: Distance between arrows along one dimension.
      boundary: Include arrows on the boundary/face of the simplex.
      normalize: Normalize each arrow to unit-length.
      pivot: In `{"tail", "middle", "tip"}`, optional, default: "middle". The
        part of the arrow that is anchored to the X, Y grid. The arrow rotates
        about this point.
      **kwargs: Additional keyword arguments passed on to `Axes.quiver`.
    Returns:
      The `quiver.Quiver` object created by calling `Axes.quiver`.
    """
    x = np.array([x for x in utils.grid_simplex(step=step, boundary=boundary)])
    dx = np.apply_along_axis(dynamics, 1, x)
    p = self._simplex_transform.transform(x)
    v = self._simplex_transform.transform(dx)
    x, y = p[:, 0], p[:, 1]
    u, v = v[:, 0], v[:, 1]
    if normalize:
      norm = np.sqrt(u**2 + v**2)
      u, v = u / norm, v / norm
    if "pivot" not in kwargs:
      kwargs["pivot"] = "middle"
    return super(Dynamics3x3Axes, self).quiver(x, y, u, v, **kwargs)
References open_spiel.python.egt.visualization.Dynamics3x3Axes._simplex_transform, and open_spiel.python.egt.visualization.Dynamics3x3Axes.quiver().
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes.quiver().
scatter()
open_spiel.python.egt.visualization.Dynamics3x3Axes.scatter (self, points, ** kwargs)
Creates a scatter plot.
Args:
  points: Points in policy space.
  **kwargs: Additional keyword arguments passed on to `Axes.scatter`.
Returns:
  The scatter plot.
Definition at line 399 of file visualization.py.
  def scatter(self, points, **kwargs):
    """Creates a scatter plot.
    Args:
      points: Points in policy space.
      **kwargs: Additional keyword arguments passed on to `Axes.scatter`.
    Returns:
      The scatter plot.
    """
    points = np.array(points)
    assert points.shape[1] == 3
    points = self._simplex_transform.transform(points)
    return super(Dynamics3x3Axes, self).scatter(points[:, 0], points[:, 1],
                                                **kwargs)
References open_spiel.python.egt.visualization.Dynamics3x3Axes._simplex_transform, and open_spiel.python.egt.visualization.Dynamics3x3Axes.scatter().
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes.cla(), and open_spiel.python.egt.visualization.Dynamics3x3Axes.scatter().
set_labels()
open_spiel.python.egt.visualization.Dynamics3x3Axes.set_labels (self, labels, padding = 0.02)
Definition at line 365 of file visualization.py.
  def set_labels(self, labels, padding=0.02):
    assert len(labels) == 3
    if self._labels is None:
      self._labels = self._create_labels(labels, padding)
      for label in self._labels:
        self.add_artist(label)
    else:
      for artist, label in zip(self._labels, labels):
        artist.set_text(label)
References open_spiel.python.egt.visualization.Dynamics3x3Axes._create_labels(), open_spiel.python.egt.visualization.Dynamics3x3Axes._labels, and len.
streamplot()
open_spiel.python.egt.visualization.Dynamics3x3Axes.streamplot (self, dynamics, initial_points = None, dt = 0.01, density = 1., min_length = 0.4, linewidth = None, color = "k", ** kwargs)
Visualizes the dynamics as a streamline plot.
Mimics the visuals of `Axes.streamplot` for simplex plots.
Args:
  dynamics: Population dynamics of type `dynamics.SinglePopulationDynamics`.
  initial_points: Starting points for streamlines
  dt: Integration step.
  density: Controls the density of streamlines in the plot.
  min_length: Streamlines with length < min_length will be discarded.
  linewidth: In `{None, float, "velocity"}`, optional, default: None. If
    `linewidth="velocity"`, line width is scaled by the velocity of the
    dynamics. Defaults to `rcParams` if `linewidth=None`.
  color: In `{None, string, (r,g,b), (r,g,b,a), "velocity"}`, default: None.
    If `color="velocity"`, velocity of dynamics is used to color the
    streamlines. Defaults to `rcParams` if `color=None`.
  **kwargs: Additional keyword arguments passed on to `Axes.streamplot`.
Returns:
  The `SimplexStreamMask`.
Definition at line 495 of file visualization.py.
                 **kwargs):
    """Visualizes the dynamics as a streamline plot.
    Mimics the visuals of `Axes.streamplot` for simplex plots.
    Args:
      dynamics: Population dynamics of type `dynamics.SinglePopulationDynamics`.
      initial_points: Starting points for streamlines
      dt: Integration step.
      density: Controls the density of streamlines in the plot.
      min_length: Streamlines with length < min_length will be discarded.
      linewidth: In `{None, float, "velocity"}`, optional, default: None. If
        `linewidth="velocity"`, line width is scaled by the velocity of the
        dynamics. Defaults to `rcParams` if `linewidth=None`.
      color: In `{None, string, (r,g,b), (r,g,b,a), "velocity"}`, default: None.
        If `color="velocity"`, velocity of dynamics is used to color the
        streamlines. Defaults to `rcParams` if `color=None`.
      **kwargs: Additional keyword arguments passed on to `Axes.streamplot`.
    Returns:
      The `SimplexStreamMask`.
    """
    mask = SimplexStreamMask(density=density)
    trajectories = []
    if initial_points is None:
      eps = 0.1
      initial_points = np.array([[1. - eps, eps / 2., eps / 2.],
                                 [eps / 2., 1. - eps, eps / 2.],
                                 [eps / 2., eps / 2., 1. - eps]])
      initial_points = np.vstack(
          (initial_points, utils.sample_from_simplex(100)))
      # TODO(author10): add heuristic for initial points
    else:
      initial_points = np.array(initial_points)
      assert initial_points.ndim == 2
      assert initial_points.shape[1] == 3
    # generate trajectories
    for p in initial_points:
      # center initial point on grid cell
      p = mask.point(mask.index(p))
      res = self._integrate(p, dynamics, mask, dt=dt)
      if res is not None:
        t, cells = res  # pylint: disable=unpacking-non-sequence
        cum_len = np.cumsum(
            np.sqrt(
                np.diff(t[:, 0])**2 + np.diff(t[:, 1])**2 +
                np.diff(t[:, 2])**2))
        if cum_len[-1] < min_length:
          for cell in cells:
            mask[mask.point(cell)] = False
          continue
        trajectories.append(t)
    lc_color = arrow_color = color
    lc_linewidth = linewidth
    if linewidth == "velocity" or color == "velocity":
      vel_max = 0
      vel_min = float("inf")
      velocities = []
      for t in trajectories:
        dx = np.apply_along_axis(dynamics, 1, t)
        vel = np.sqrt(np.sum(dx**2, axis=1))
        vel_max = max(np.max(vel), vel_max)
        vel_min = min(np.min(vel), vel_min)
        velocities.append(vel)
    # add trajectories to plot
    for i, t in enumerate(trajectories):
      cum_len = np.cumsum(
          np.sqrt(
              np.diff(t[:, 0])**2 + np.diff(t[:, 1])**2 + np.diff(t[:, 2])**2))
      mid_idx = np.searchsorted(cum_len, cum_len[-1] / 2.)
      if linewidth == "velocity" or color == "velocity":
        vel = (velocities[i] - vel_min) / vel_max
        if linewidth == "velocity":
          lc_linewidth = 3. * vel + 0.5
        if color == "velocity":
          cmap = matplotlib.cm.get_cmap(rcParams["image.cmap"])
          lc_color = cmap(vel)
          arrow_color = cmap(vel[mid_idx])
      lc = self._linecollection(t, linewidth=lc_linewidth, color=lc_color)
      self.add_collection(lc)
      # add arrow centered on trajectory
      arrow_tail = self._simplex_transform.transform(t[mid_idx - 1])
      arrow_head = self._simplex_transform.transform(t[mid_idx])
      arrow_kw = dict(arrowstyle="-|>", mutation_scale=10 * 1.)
      arrow_patch = FancyArrowPatch(
          arrow_tail,
          arrow_head,
          linewidth=None,
          color=arrow_color,
          zorder=3,
          **arrow_kw)
      self.add_patch(arrow_patch)
    return mask
References open_spiel.python.egt.visualization.Dynamics3x3Axes._integrate(), open_spiel.python.egt.visualization.Dynamics3x3Axes._linecollection(), and open_spiel.python.egt.visualization.Dynamics3x3Axes._simplex_transform.
Member Data Documentation
_labels
open_spiel.python.egt.visualization.Dynamics3x3Axes._labels protected
Definition at line 249 of file visualization.py.
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes.get_labels(), and open_spiel.python.egt.visualization.Dynamics3x3Axes.set_labels().
_simplex_transform
open_spiel.python.egt.visualization.Dynamics3x3Axes._simplex_transform protected
Definition at line 248 of file visualization.py.
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes._create_bgpatch(), open_spiel.python.egt.visualization.Dynamics3x3Axes._create_grid(), open_spiel.python.egt.visualization.Dynamics3x3Axes._create_ticks(), open_spiel.python.egt.visualization.Dynamics3x3Axes._linecollection(), open_spiel.python.egt.visualization.Dynamics3x3Axes.plot(), open_spiel.python.egt.visualization.Dynamics3x3Axes.quiver(), open_spiel.python.egt.visualization.Dynamics3x3Axes.scatter(), and open_spiel.python.egt.visualization.Dynamics3x3Axes.streamplot().
_VERTICES [1/2]
list open_spiel.python.egt.visualization.Dynamics3x3Axes._VERTICES = [[1, 0, 0], [0, 1, 0], [0, 0, 1]] static protected
Definition at line 245 of file visualization.py.
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes._create_bgpatch().
_VERTICES [2/2]
open_spiel.python.egt.visualization.Dynamics3x3Axes._VERTICES protected
Definition at line 346 of file visualization.py.
Referenced by open_spiel.python.egt.visualization.Dynamics3x3Axes._create_bgpatch().
bgpatch
open_spiel.python.egt.visualization.Dynamics3x3Axes.bgpatch
Definition at line 265 of file visualization.py.
grid
open_spiel.python.egt.visualization.Dynamics3x3Axes.grid
Definition at line 273 of file visualization.py.
name
str open_spiel.python.egt.visualization.Dynamics3x3Axes.name = "3x3" static
Definition at line 244 of file visualization.py.
tick_labels
open_spiel.python.egt.visualization.Dynamics3x3Axes.tick_labels
Definition at line 281 of file visualization.py.
ticks
open_spiel.python.egt.visualization.Dynamics3x3Axes.ticks
Definition at line 281 of file visualization.py.
Property Documentation
labels
open_spiel.python.egt.visualization.Dynamics3x3Axes.labels = property(get_labels, set_labels) static
Definition at line 375 of file visualization.py.
The documentation for this class was generated from the following file:
open_spiel/python/egt/visualization.py