open spiel: open_spiel::algorithms::TabularBestResponse Class Reference
open_spiel::algorithms::TabularBestResponse Class Reference
#include <best_response.h>
Public Member Functions
TabularBestResponse (const Game &game, Player best_responder, const Policy *policy, const float prob_cut_threshold=-1.0, const float action_value_tolerance=-1.0)
TabularBestResponse (const Game &game, Player best_responder, const std::unordered_map< std::string, ActionsAndProbs > &policy_table, const float prob_cut_threshold=-1.0, const float action_value_tolerance=-1.0)
TabularBestResponse (TabularBestResponse &&)=default
Action BestResponseAction (const std::string &infostate)
Action BestResponseAction (const State &state)
std::vector< Action > BestResponseActions (const std::string &infostate, double tolerance)
std::vector< Action > BestResponseActions (const State &state, double tolerance)
std::vector< std::pair< Action, double > > BestResponseActionValues (const std::string &infostate)
std::vector< std::pair< Action, double > > BestResponseActionValues (const State &state)
std::unordered_map< std::string, Action > GetBestResponseActions ()
TabularPolicy GetBestResponsePolicy ()
double Value (const std::string &history)
double Value (const State &state)
void SetPolicy (const Policy *policy)
void SetPolicy (const std::unordered_map< std::string, ActionsAndProbs > &policy_table)
Detailed Description
Definition at line 55 of file best_response.h.
Constructor & Destructor Documentation
TabularBestResponse() [1/3]
open_spiel::algorithms::TabularBestResponse::TabularBestResponse (const Game & game, Player best_responder, const Policy * policy, const float prob_cut_threshold = -1.0, const float action_value_tolerance = -1.0)
Definition at line 34 of file best_response.cc.
    : best_responder_(best_responder),
      tabular_policy_container_(),
      policy_(policy),
      tree_(HistoryTree(game.NewInitialState(), best_responder_)),
      num_players_(game.NumPlayers()),
      prob_cut_threshold_(prob_cut_threshold),
      action_value_tolerance_(action_value_tolerance),
      infosets_(GetAllInfoSets(game.NewInitialState(), best_responder, policy,
                               &tree_)),
      root_(game.NewInitialState()),
      dummy_policy_(new TabularPolicy(GetUniformPolicy(game))) {
  if (game.GetType().dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError("The game must be turn-based.");
  }
}
References open_spiel::GameType::kSequential, and open_spiel::SpielFatalError().
TabularBestResponse() [2/3]
open_spiel::algorithms::TabularBestResponse::TabularBestResponse (const Game & game, Player best_responder, const std::unordered_map< std::string, ActionsAndProbs > & policy_table, const float prob_cut_threshold = -1.0, const float action_value_tolerance = -1.0)
Definition at line 55 of file best_response.cc.
    : best_responder_(best_responder),
      tabular_policy_container_(policy_table),
      policy_(&tabular_policy_container_),
      tree_(HistoryTree(game.NewInitialState(), best_responder_)),
      num_players_(game.NumPlayers()),
      prob_cut_threshold_(prob_cut_threshold),
      action_value_tolerance_(action_value_tolerance),
      infosets_(GetAllInfoSets(game.NewInitialState(), best_responder, policy_,
                               &tree_)),
      root_(game.NewInitialState()),
      dummy_policy_(new TabularPolicy(GetUniformPolicy(game))) {
  if (game.GetType().dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError("The game must be turn-based.");
  }
}
References open_spiel::GameType::kSequential, and open_spiel::SpielFatalError().
TabularBestResponse() [3/3]
open_spiel::algorithms::TabularBestResponse::TabularBestResponse (TabularBestResponse &&) default
Member Function Documentation
BestResponseAction() [1/2]
Action open_spiel::algorithms::TabularBestResponse::BestResponseAction (const State & state) inline
Definition at line 73 of file best_response.h.
{
    SPIEL_CHECK_EQ(state.CurrentPlayer(), best_responder_);
    return BestResponseAction(state.InformationStateString(best_responder_));
  }
References BestResponseAction(), SPIEL_CHECK_EQ, and state.
BestResponseAction() [2/2]
Action open_spiel::algorithms::TabularBestResponse::BestResponseAction (const std::string & infostate)
Definition at line 194 of file best_response.cc.
{
  auto it = best_response_policy_.find(infostate);
  if (it != best_response_policy_.end()) return it->second.begin()->first;
  std::vector<std::pair<HistoryNode*, double>> infoset = infosets_[infostate];
  Action best_action = -1;
  double best_value = std::numeric_limits<double>::lowest();
  // The legal actions are the same for all children, so we arbitrarily pick
  // the first one to get the legal actions from.
  for (const auto& action : infoset[0].first->GetChildActions()) {
    double value = 0;
    // Prob here is the counterfactual reach-weighted probability.
    for (const auto& state_and_prob : infoset) {
      if (state_and_prob.second <= prob_cut_threshold_) continue;
      HistoryNode* state_node = state_and_prob.first;
      HistoryNode* child_node = state_node->GetChild(action).second;
      SPIEL_CHECK_TRUE(child_node != nullptr);
      value += state_and_prob.second * Value(child_node->GetHistory());
    }
    if (value > best_value) {
      best_value = value;
      best_action = action;
    }
  }
  if (best_action == -1) SpielFatalError("No action was chosen.");
  ActionsAndProbs actions_and_probs;
  for (const auto& action : infoset[0].first->GetChildActions()) {
    double prob = 0.0;
    if (action == best_action) prob = 1.0;
    actions_and_probs.push_back(std::make_pair(action, prob));
  }
  best_response_policy_[infostate] = actions_and_probs;
  best_response_actions_[infostate] = best_action;
  return best_action;
}
References action, actions_and_probs, open_spiel::algorithms::HistoryNode::GetChild(), open_spiel::algorithms::HistoryNode::GetHistory(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), Value(), and value.
Referenced by BestResponseAction().
BestResponseActions() [1/2]
std::vector< Action > open_spiel::algorithms::TabularBestResponse::BestResponseActions (const State & state, double tolerance) inline
Definition at line 83 of file best_response.h.
{
    SPIEL_CHECK_EQ(state.CurrentPlayer(), best_responder_);
    return BestResponseActions(state.InformationStateString(best_responder_),
                               tolerance);
  }
References BestResponseActions(), SPIEL_CHECK_EQ, and state.
BestResponseActions() [2/2]
std::vector< Action > open_spiel::algorithms::TabularBestResponse::BestResponseActions (const std::string & infostate, double tolerance)
Definition at line 229 of file best_response.cc.
{
  absl::btree_set<Action> best_actions;
  std::vector<std::pair<Action, double>> action_values;
  std::vector<std::pair<HistoryNode*, double>> infoset =
      infosets_.at(infostate);
  double best_value = std::numeric_limits<double>::lowest();
  // The legal actions are the same for all children, so we arbitrarily pick
  // the first one to get the legal actions from.
  for (const Action& action : infoset[0].first->GetChildActions()) {
    double value = 0;
    // Prob here is the counterfactual reach-weighted probability.
    for (const auto& [state_node, prob] : infoset) {
      if (prob <= prob_cut_threshold_) continue;
      HistoryNode* child_node = state_node->GetChild(action).second;
      SPIEL_CHECK_TRUE(child_node != nullptr);
      value += prob * Value(child_node->GetHistory());
    }
    action_values.push_back({action, value});
    if (value > best_value) {
      best_value = value;
    }
  }
  for (const auto& [action, value] : action_values) {
    if (value >= best_value - tolerance) {
      best_actions.insert(action);
    }
  }
  if (best_actions.empty()) SpielFatalError("No action was chosen.");
  ActionsAndProbs actions_and_probs;
  for (const auto& action : infoset[0].first->GetChildActions()) {
    double prob = 0.0;
    if (best_actions.count(action)) {
      prob = 1.0 / best_actions.size();
    }
    actions_and_probs.push_back(std::make_pair(action, prob));
  }
  best_response_policy_[infostate] = actions_and_probs;
  return std::vector<Action>(best_actions.begin(), best_actions.end());
}
References action, actions_and_probs, absl::container_internal::btree_container< Tree >::begin(), absl::container_internal::btree_container< Tree >::count(), absl::container_internal::btree_container< Tree >::empty(), absl::container_internal::btree_container< Tree >::end(), open_spiel::algorithms::HistoryNode::GetChild(), open_spiel::algorithms::HistoryNode::GetHistory(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_container< Tree >::size(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), Value(), and value.
Referenced by BestResponseActions().
BestResponseActionValues() [1/2]
std::vector< std::pair< Action, double > > open_spiel::algorithms::TabularBestResponse::BestResponseActionValues (const State & state) inline
Definition at line 94 of file best_response.h.
{
    SPIEL_CHECK_EQ(state.CurrentPlayer(), best_responder_);
    return BestResponseActionValues(
        state.InformationStateString(best_responder_));
  }
References BestResponseActionValues(), SPIEL_CHECK_EQ, and state.
BestResponseActionValues() [2/2]
std::vector< std::pair< Action, double > > open_spiel::algorithms::TabularBestResponse::BestResponseActionValues (const std::string & infostate)
Definition at line 270 of file best_response.cc.
{
  std::vector<std::pair<Action, double>> action_values;
  std::vector<std::pair<HistoryNode*, double>> infoset =
      infosets_.at(infostate);
  action_values.reserve(infoset[0].first->GetChildActions().size());
  for (Action action : infoset[0].first->GetChildActions()) {
    double value = 0;
    double normalizer = 0;
    // Prob here is the counterfactual reach-weighted probability.
    for (const auto& [state_node, prob] : infoset) {
      if (prob <= prob_cut_threshold_) continue;
      HistoryNode* child_node = state_node->GetChild(action).second;
      SPIEL_CHECK_TRUE(child_node != nullptr);
      value += prob * Value(child_node->GetHistory());
      normalizer += prob;
    }
    SPIEL_CHECK_GT(normalizer, 0);
    action_values.push_back({action, value / normalizer});
  }
  return action_values;
}
References action, first, open_spiel::algorithms::HistoryNode::GetChild(), open_spiel::algorithms::HistoryNode::GetHistory(), SPIEL_CHECK_GT, SPIEL_CHECK_TRUE, and Value().
Referenced by BestResponseActionValues().
GetBestResponseActions()
std::unordered_map< std::string, Action > open_spiel::algorithms::TabularBestResponse::GetBestResponseActions () inline
Definition at line 106 of file best_response.h.
{
    if (action_value_tolerance_ >= 0.0)
      SpielFatalError(
          "TabularBestResponse is returning the max-entropy best-response but "
          "deterministic best-response is requested.");
    // If the best_response_policy_ cache is empty, we fill it by
    // calculating all best responses, starting at the root.
    if (best_response_actions_.empty()) Value(*root_);
    return best_response_actions_;
  }
References open_spiel::SpielFatalError(), and Value().
Referenced by define_julia_module().
GetBestResponsePolicy()
TabularPolicy open_spiel::algorithms::TabularBestResponse::GetBestResponsePolicy () inline
Definition at line 118 of file best_response.h.
{
    // If the best_response_policy_ cache is empty, we fill it by calculating
    // all best responses, starting at the root.
    if (best_response_policy_.empty()) Value(*root_);
    return TabularPolicy(best_response_policy_);
  }
References Value().
Referenced by define_julia_module().
SetPolicy() [1/2]
void open_spiel::algorithms::TabularBestResponse::SetPolicy (const Policy * policy) inline
Definition at line 133 of file best_response.h.
{
    policy_ = policy;
    value_cache_.clear();
    best_response_actions_.clear();
    best_response_policy_.clear();
    // TODO(author1): Replace this with something that traverses the tree
    // and rebuilds the probabilities.
    infosets_ =
        GetAllInfoSets(root_->Clone(), best_responder_, policy_, &tree_);
  }
References open_spiel::algorithms::GetAllInfoSets().
Referenced by SetPolicy().
SetPolicy() [2/2]
void open_spiel::algorithms::TabularBestResponse::SetPolicy (const std::unordered_map< std::string, ActionsAndProbs > & policy_table) inline
Definition at line 145 of file best_response.h.
{
    tabular_policy_container_ = TabularPolicy(policy_table);
    SetPolicy(&tabular_policy_container_);
  }
References SetPolicy().
Value() [1/2]
double open_spiel::algorithms::TabularBestResponse::Value (const State & state) inline
Definition at line 128 of file best_response.h.
{ return Value(state.HistoryString()); }
References state, and Value().
Referenced by Value().
Value() [2/2]
double open_spiel::algorithms::TabularBestResponse::Value (const std::string & history)
Definition at line 168 of file best_response.cc.
{
  auto it = value_cache_.find(history);
  if (it != value_cache_.end()) return it->second;
  HistoryNode* node = tree_.GetByHistory(history);
  if (node == nullptr) SpielFatalError("node returned is null.");
  double cache_value = 0;
  switch (node->GetType()) {
    case StateType::kTerminal: {
      cache_value = HandleTerminalCase(*node);
      break;
    }
    case StateType::kDecision: {
      cache_value = HandleDecisionCase(node);
      break;
    }
    case StateType::kChance: {
      cache_value = HandleChanceCase(node);
      break;
    }
    case StateType::kMeanField: {
      SpielFatalError("kMeanField not supported.");
    }
  }
  value_cache_[history] = cache_value;
  return value_cache_[history];
}
References open_spiel::algorithms::HistoryTree::GetByHistory(), open_spiel::algorithms::HistoryNode::GetType(), open_spiel::kChance, open_spiel::kDecision, open_spiel::kMeanField, open_spiel::kTerminal, and open_spiel::SpielFatalError().
Referenced by BestResponseAction(), BestResponseActions(), BestResponseActionValues(), GetBestResponseActions(), and GetBestResponsePolicy().
The documentation for this class was generated from the following files:
open_spiel/algorithms/best_response.h
open_spiel/algorithms/best_response.cc