open spiel: open_spiel::battleship::BattleshipState Class Reference
open_spiel::battleship::BattleshipState Class Reference final
#include <battleship.h>
Public Member Functions
BattleshipState (const std::shared_ptr< const BattleshipGame > bs_game)
~BattleshipState ()=default
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
void UndoAction (Player player, Action action_id) override
std::string OwnBoardString (const Player player) const
std::string ShotsBoardString (const Player player) const
std::string ToPrettyString () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 244 of file battleship.h.
Constructor & Destructor Documentation
BattleshipState()
open_spiel::battleship::BattleshipState::BattleshipState (const std::shared_ptr< const BattleshipGame > bs_game) explicit
Definition at line 29 of file battleship.cc.
    : State(bs_game), bs_game_(bs_game) {}
~BattleshipState()
open_spiel::battleship::BattleshipState::~BattleshipState () default
Member Function Documentation
ActionToString()
std::string open_spiel::battleship::BattleshipState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 176 of file battleship.cc.
{
  return bs_game_->ActionToString(player, action_id);
}
References player.
Clone()
std::unique_ptr< State > open_spiel::battleship::BattleshipState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 234 of file battleship.cc.
{
  return std::make_unique<BattleshipState>(*this);
}
CurrentPlayer()
Player open_spiel::battleship::BattleshipState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 33 of file battleship.cc.
{
  const BattleshipConfiguration& conf = bs_game_->conf;
  // The players place the ships on the board in turns, starting from
  // Player 1.
  //
  // NOTE: It is important whether or not the players place all their ships at
  // once or not for correlated equilibria purposes. This is because in
  // correlated equilibria, the recommender can stop issuing recommendations
  // after a player deviates from a recommended *action*.
  if (!AllShipsPlaced()) {
    // In this case, if an even number (possibly 0) of ships have been placed,
    // then it is Player 1's turn to act next. Else, it is Player 2's.
    if (NumShipsPlaced() % 2 == 0) {
      return Player{0};
    } else {
      return Player{1};
    }
  } else {
    // In this case, all ships have been placed. The players can take turns
    // for their next moves, starting from Player 1.
    // First, we check whether the game is over.
    //
    // The game is over only in two cases:
    // * Both players have taken `conf.num_shots` shots; or
    // * At least one player has lost all of their ships.
    if (moves_.size() == 2 * conf.ships.size() + 2 * conf.num_shots) {
      return kTerminalPlayerId;
    } else if (AllPlayersShipsSank(Player{0}) ||
               AllPlayersShipsSank(Player{1})) {
      return kTerminalPlayerId;
    }
    // If we are here, the game is not over yet.
    if (moves_.size() % 2 == 0) {
      return Player{0};
    } else {
      return Player{1};
    }
  }
}
References open_spiel::kTerminalPlayerId, open_spiel::battleship::BattleshipConfiguration::num_shots, and open_spiel::battleship::BattleshipConfiguration::ships.
Referenced by LegalActions().
DoApplyAction()
void open_spiel::battleship::BattleshipState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 610 of file battleship.cc.
{
  SPIEL_CHECK_FALSE(IsTerminal());
  const Player player = CurrentPlayer();
  const auto legal_action_ids = LegalActions();
  // Instead of validating the input action, we simply check that it is one
  // of the legal actions. This effectively moves all the burden of validation
  // onto `LegalActions`.
  SPIEL_CHECK_EQ(
      std::count(legal_action_ids.begin(), legal_action_ids.end(), action_id),
      1);
  const absl::variant<CellAndDirection, Shot> action =
      bs_game_->DeserializeAction(action_id);
  if (absl::holds_alternative<CellAndDirection>(action)) {
    const CellAndDirection& cell_and_dir = absl::get<CellAndDirection>(action);
    const ShipPlacement placement(
        /* direction = */ cell_and_dir.direction,
        /* ship = */ NextShipToPlace(player),
        /* tl_corner = */ cell_and_dir.TopLeftCorner());
    moves_.push_back(GameMove{CurrentPlayer(), placement});
  } else {
    SPIEL_DCHECK_TRUE(absl::holds_alternative<Shot>(action));
    moves_.push_back(GameMove{CurrentPlayer(), absl::get<Shot>(action)});
  }
}  // namespace battleship
References action, open_spiel::battleship::CellAndDirection::direction, absl::get(), absl::holds_alternative(), player, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_DCHECK_TRUE, and open_spiel::battleship::CellAndDirection::TopLeftCorner().
InformationStateString()
std::string open_spiel::battleship::BattleshipState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 238 of file battleship.cc.
{
  SPIEL_CHECK_TRUE(player >= 0 && player < NumPlayers());
  const BattleshipConfiguration& conf = bs_game_->conf;
  const Player opponent = (player == Player{0}) ? Player{1} : Player{0};
  // We will need to figure out whether each of the player's shots (i) hit the
  // water, (ii) damaged but did not sink yet one of the opponent's ships, or
  // (iii) damaged and sank one of the opponent's ships.
  //
  // To be able to figure that out, we will keep track of the damage that each
  // of the opponent's ship has received so far. The vector `ship_damage`
  // contains and updates this information as each player's shot is processed
  // in order. Position i corresponds to the damage that the opponent's ship
  // in position i of bs_game->conf.ships has suffered.
  std::vector<int> ship_damage(conf.ships.size(), 0);
  // Since in general we might have repeated shots, we cannot simply increase
  // the ship damage every time a shot hits a ship. For that, we keep track of
  // whether a cell was already hit in the past. We reuse the
  // serialization/deserialization routines for shots to map from (r, c) to
  // cell index r * board_width + c.
  std::vector<bool> cell_hit(conf.board_width * conf.board_height, false);
  // NOTE: OpenSpiel's automatic observation consistency checks require that
  //     agents be able to distinguish that someone else has moved (though the
  //     move itself might not be observed). So, the information_state string
  //     we return has to be able to distinguish between, e.g., "Player 1
  //     still hasn't placed the first ship" and "Player 1 has placed the ship
  //     and it's now my turn" in the first two moves.
  //
  //     For that reason, we prepend the move number in the information state to
  //     resolve the ambiguity.
  std::string information_state = absl::StrCat("T=", MoveNumber(), " ");
  for (const auto& move : moves_) {
    if (absl::holds_alternative<ShipPlacement>(move.action)) {
      // The player observed *their own* ship placements.
      if (move.player == player) {
        absl::StrAppend(&information_state, "/");
        absl::StrAppend(&information_state,
                        absl::get<ShipPlacement>(move.action).ToString());
      }
    } else {
      const Shot& shot = absl::get<Shot>(move.action);
      if (move.player != player) {
        // If the shot came from the opponent, the player has seen it.
        absl::StrAppend(&information_state, "/oppshot_", shot.ToString());
      } else {
        const int cell_index = bs_game_->SerializeShotAction(shot);
        char shot_outcome = 'W';  // For 'water'.
        for (int ship_index = 0; ship_index < conf.ships.size(); ++ship_index) {
          const Ship& ship = conf.ships.at(ship_index);
          // SAFETY: the call to FindShipPlacement_ is safe, because if we are
          // here it means that all ships have been placed.
          const ShipPlacement ship_placement =
              FindShipPlacement(ship, opponent);
          if (ship_placement.CoversCell(shot)) {
            if (!cell_hit[cell_index]) {
              // This is a new hit: we have to increas the ship damage and
              // mark the cell as already hit.
              ++ship_damage.at(ship_index);
              cell_hit.at(cell_index) = true;
            }
            if (ship_damage.at(ship_index) == ship.length) {
              shot_outcome = 'S';  // For 'sunk'.
            } else {
              shot_outcome = 'H';  // For 'hit' (but not sunk).
            }
          }
        }
        // Otherwise, the player knows they shot, but also knows whether the
        // shot hit the water, hit a ship (but did not sink it), or sank a
        // ship.
        absl::StrAppend(&information_state, "/shot_", shot.ToString(), ":");
        information_state.push_back(shot_outcome);
      }
    }
  }
  return information_state;
}
References open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, open_spiel::battleship::ShipPlacement::CoversCell(), absl::get(), absl::holds_alternative(), open_spiel::battleship::Ship::length, player, open_spiel::battleship::BattleshipConfiguration::ships, SPIEL_CHECK_TRUE, absl::StrAppend(), absl::StrCat(), and open_spiel::battleship::Cell::ToString().
InformationStateTensor()
void open_spiel::battleship::BattleshipState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 324 of file battleship.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->InformationStateTensorSize());
  std::fill(values.begin(), values.end(), 0);
  int offset = 0;
  const BattleshipConfiguration& conf = bs_game_->conf;
  const Player opponent = (player == Player{0}) ? Player{1} : Player{0};
  const int height = conf.board_height;
  const int width = conf.board_width;
  std::vector<int> ship_damage(conf.ships.size(), 0);
  std::vector<bool> cell_hit(conf.board_width * conf.board_height, false);
  if (IsTerminal()) {
    values[offset] = 1;
  }
  offset += 1;
  values[offset + player] = 1;
  offset += 2;
  if (!IsTerminal()) {
    values[offset + CurrentPlayer()] = 1;
  }
  offset += 2;
  for (const auto& move : moves_) {
    if (absl::holds_alternative<ShipPlacement>(move.action)) {
      // The player observed *their own* ship placements.
      if (move.player == player) {
        const ShipPlacement& placement = absl::get<ShipPlacement>(move.action);
        if (placement.direction == CellAndDirection::Horizontal) {
          values[offset] = 1;
        } else {
          values[offset + 1] = 1;
        }
        offset += 2;
        values[offset + placement.TopLeftCorner().row] = 1;
        offset += height;
        values[offset + placement.TopLeftCorner().col] = 1;
        offset += width;
      }
    } else {
      const Shot& shot = absl::get<Shot>(move.action);
      values[offset + move.player] = 1;
      offset += bs_game_->NumPlayers();
      values[offset + shot.row] = 1;
      offset += height;
      values[offset + shot.col] = 1;
      offset += width;
      // Add info of hit, shot, or sunk only for my shots (same as in the
      // info state string).
      if (move.player == player) {
        const int cell_index = bs_game_->SerializeShotAction(shot);
        char shot_outcome = 'W';  // For 'water'.
        for (int ship_index = 0; ship_index < conf.ships.size(); ++ship_index) {
          const Ship& ship = conf.ships.at(ship_index);
          // SAFETY: the call to FindShipPlacement_ is safe, because if we are
          // here it means that all ships have been placed.
          const ShipPlacement ship_placement =
              FindShipPlacement(ship, opponent);
          if (ship_placement.CoversCell(shot)) {
            if (!cell_hit[cell_index]) {
              // This is a new hit: we have to increas the ship damage and
              // mark the cell as already hit.
              ++ship_damage.at(ship_index);
              cell_hit.at(cell_index) = true;
            }
            if (ship_damage.at(ship_index) == ship.length) {
              shot_outcome = 'S';  // For 'sunk'.
            } else {
              shot_outcome = 'H';  // For 'hit' (but not sunk).
            }
          }
        }
        switch (shot_outcome) {
            case 'W': values[offset] = 1; break;
            case 'H': values[offset + 1] = 1; break;
            case 'S': values[offset + 2] = 1; break;
            default:
              std::string error = "Bad shot outcome: ";
              error.push_back(shot_outcome);
              SpielFatalError(error);
        }
      }
      // Bits for For W/H/S.
      offset += 3;
    }
  }
  SPIEL_CHECK_LE(offset, values.size());
}
References open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, open_spiel::battleship::Cell::col, open_spiel::battleship::ShipPlacement::CoversCell(), open_spiel::battleship::CellAndDirection::direction, absl::get(), absl::holds_alternative(), open_spiel::battleship::Ship::length, player, open_spiel::battleship::Cell::row, open_spiel::battleship::BattleshipConfiguration::ships, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), open_spiel::battleship::CellAndDirection::TopLeftCorner(), and values.
IsTerminal()
bool open_spiel::battleship::BattleshipState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 207 of file battleship.cc.
{
  return CurrentPlayer() == kTerminalPlayerId;
}
References open_spiel::kTerminalPlayerId.
Referenced by LegalActions().
LegalActions()
std::vector< Action > open_spiel::battleship::BattleshipState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 76 of file battleship.cc.
{
  if (IsTerminal()) {
    return {};
  } else {
    const Player player = CurrentPlayer();
    const BattleshipConfiguration& conf = bs_game_->conf;
    std::vector<Action> action_ids;
    action_ids.reserve(NumDistinctActions());
    if (!AllShipsPlaced()) {
      std::vector<ShipPlacement> partial_placement;
      for (const auto& move : moves_) {
        if (move.player == player &&
            absl::holds_alternative<ShipPlacement>(move.action)) {
          partial_placement.push_back(absl::get<ShipPlacement>(move.action));
        }
      }
      // If we are here, we still have some ships to place on the board.
      //
      // First, we find the first ship that hasn't been placed on the board
      // yet.
      const Ship next_ship = NextShipToPlace(player);
      // Horizontal placement.
      if (next_ship.length <= conf.board_width) {
        for (int row = 0; row < conf.board_height; ++row) {
          for (int col = 0; col < conf.board_width - next_ship.length + 1;
               ++col) {
            const ShipPlacement placement(ShipPlacement::Direction::Horizontal,
                                          /* ship = */ next_ship,
                                          /* tl_corner = */ Cell{row, col});
            partial_placement.push_back(placement);
            if (PlacementDoesNotOverlap(placement, player) &&
                ExistsFeasiblePlacement(conf, &partial_placement)) {
              action_ids.push_back(
                  bs_game_->SerializeShipPlacementAction(placement));
            }
            partial_placement.pop_back();
          }
        }
      }
      // Vertical placement.
      //
      // NOTE: vertical placement is defined only for ships with length more
      //     than one. This avoids duplicating placement actions for 1x1
      //     ships.
      if (next_ship.length > 1 && next_ship.length <= conf.board_height) {
        for (int row = 0; row < conf.board_height - next_ship.length + 1;
             ++row) {
          for (int col = 0; col < conf.board_width; ++col) {
            const ShipPlacement placement(ShipPlacement::Direction::Vertical,
                                          /* ship = */ next_ship,
                                          /* tl_corner = */ Cell{row, col});
            partial_placement.push_back(placement);
            if (PlacementDoesNotOverlap(placement, player) &&
                ExistsFeasiblePlacement(conf, &partial_placement)) {
              action_ids.push_back(
                  bs_game_->SerializeShipPlacementAction(placement));
            }
            partial_placement.pop_back();
          }
        }
      }
      // Since the constructor of the game checks that there exists a feasible
      // placement of ships for each player, and since we only consider
      // placement actions that preserve feasibility, it is impossible that all
      // of a sudden we find ourselves painted in a corner where no placement
      // can be performed.
      SPIEL_CHECK_GT(action_ids.size(), 0);
    } else {
      // In this case, the only thing the player can do is to shoot on a cell
      //
      // Depending on whether repeated shots are allowed or not, we might
      // filter out some cells.
      for (int row = 0; row < conf.board_height; ++row) {
        for (int col = 0; col < conf.board_width; ++col) {
          if (!conf.allow_repeated_shots &&
              AlreadyShot(Cell{row, col}, CurrentPlayer())) {
            // We do not duplicate the shot, so nothing to do here...
          } else {
            action_ids.push_back(bs_game_->SerializeShotAction(Shot{row, col}));
          }
        }
      }
      // SAFETY: The assert below can never fail, because when
      //     allow_repeated_shot is false, we check at game construction time
      //     that the number of shots per player is <= the number of cells in
      //     the board.
      SPIEL_DCHECK_FALSE(action_ids.empty());
    }
    return action_ids;
  }
}
References open_spiel::battleship::BattleshipConfiguration::allow_repeated_shots, open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, CurrentPlayer(), open_spiel::battleship::ExistsFeasiblePlacement(), absl::get(), absl::holds_alternative(), IsTerminal(), open_spiel::battleship::Ship::length, open_spiel::State::NumDistinctActions(), player, SPIEL_CHECK_GT, and SPIEL_DCHECK_FALSE.
ObservationString()
std::string open_spiel::battleship::BattleshipState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 428 of file battleship.cc.
{
  std::string output = "State of player's ships:\n";
  absl::StrAppend(&output, OwnBoardString(player));
  absl::StrAppend(&output, "\nPlayer's shot outcomes:\n");
  absl::StrAppend(&output, ShotsBoardString(player));
  return output;
}
References player, and absl::StrAppend().
OwnBoardString()
std::string open_spiel::battleship::BattleshipState::OwnBoardString (const Player player) const
Definition at line 448 of file battleship.cc.
{
  SPIEL_CHECK_TRUE(player >= 0 && player < NumPlayers());
  const Player opponent = (player == Player{0}) ? Player{1} : Player{0};
  const BattleshipConfiguration& conf = bs_game_->conf;
  // We keep the board in memory as vectors of strings. Initially, all strings
  // only contain whitespace.
  std::vector<std::string> player_board(conf.board_height,
                                        std::string(conf.board_width, ' '));
  // We start by drawing the ships on the player's board. For now, we do not
  // include any information about where the opponent shot.
  char ship_id = 'a';
  for (const auto& move : moves_) {
    if (move.player == player &&
        absl::holds_alternative<ShipPlacement>(move.action)) {
      const ShipPlacement& placement = absl::get<ShipPlacement>(move.action);
      // We now iterate over all the cells that the ship covers on the board
      // and fill in the `player_board` string representation.
      Cell cell = placement.TopLeftCorner();
      for (int i = 0; i < placement.ship.length; ++i) {
        SPIEL_DCHECK_TRUE(cell.row >= 0 && cell.row < conf.board_height);
        SPIEL_DCHECK_TRUE(cell.col >= 0 && cell.col < conf.board_width);
        // The ships do not overlap.
        SPIEL_DCHECK_EQ(player_board[cell.row][cell.col], ' ');
        player_board[cell.row][cell.col] = ship_id;
        if (placement.direction == ShipPlacement::Direction::Horizontal) {
          ++cell.col;
        } else {
          SPIEL_DCHECK_TRUE(placement.direction ==
                            ShipPlacement::Direction::Vertical);
          ++cell.row;
        }
      }
      ++ship_id;
    }
  }
  // It is impossible that the player placed more ships than they own.
  SPIEL_DCHECK_LE(ship_id, 'a' + conf.ships.size());
  // We now include the opponent's shots on the player's board.
  for (const auto& move : moves_) {
    if (move.player == opponent && absl::holds_alternative<Shot>(move.action)) {
      const Shot& shot = absl::get<Shot>(move.action);
      if (player_board[shot.row][shot.col] == ' ' ||
          player_board[shot.row][shot.col] == '*') {
        // If the cell contains a '*' it means that we have already shot at that
        // cell before. That can only happen if repeated shots are allowed.
        SPIEL_DCHECK_TRUE(conf.allow_repeated_shots ||
                          player_board[shot.row][shot.col] == ' ');
        player_board[shot.row][shot.col] = '*';
      } else {
        SPIEL_DCHECK_TRUE(std::isalpha(player_board[shot.row][shot.col]));
        // The shot hit one of the ships. In this case, we use the uppercase
        // letter corresponding to the ship.
        player_board[shot.row][shot.col] =
            std::toupper(player_board[shot.row][shot.col]);
      }
    }
  }
  std::string output;
  absl::StrAppend(&output, "+", std::string(conf.board_width, '-'), "+\n");
  for (const auto& row : player_board) {
    absl::StrAppend(&output, "|", row, "|\n");
  }
  absl::StrAppend(&output, "+", std::string(conf.board_width, '-'), "+\n");
  return output;
}
References open_spiel::battleship::BattleshipConfiguration::allow_repeated_shots, open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, open_spiel::battleship::Cell::col, open_spiel::battleship::CellAndDirection::direction, absl::get(), absl::holds_alternative(), i, open_spiel::battleship::Ship::length, player, open_spiel::battleship::Cell::row, open_spiel::battleship::ShipPlacement::ship, open_spiel::battleship::BattleshipConfiguration::ships, SPIEL_CHECK_TRUE, SPIEL_DCHECK_EQ, SPIEL_DCHECK_LE, SPIEL_DCHECK_TRUE, absl::StrAppend(), and open_spiel::battleship::CellAndDirection::TopLeftCorner().
Returns()
std::vector< double > open_spiel::battleship::BattleshipState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 211 of file battleship.cc.
{
  if (!IsTerminal()) {
    return {0.0, 0.0};
  } else {
    const BattleshipConfiguration& conf = bs_game_->conf;
    // The description of the game in the header file contains more details
    // about how the payoffs for the players are computed at the end of the
    // game, as well as the meaning of the `loss_multiplier`.
    const double loss_multiplier = conf.loss_multiplier;
    double damage_pl1 = 0.0;
    double damage_pl2 = 0.0;
    for (const Ship& ship : conf.ships) {
      if (DidShipSink(ship, Player{0})) damage_pl1 += ship.value;
      if (DidShipSink(ship, Player{1})) damage_pl2 += ship.value;
    }
    return {damage_pl2 - loss_multiplier * damage_pl1,
            damage_pl1 - loss_multiplier * damage_pl2};
  }
}
References open_spiel::battleship::BattleshipConfiguration::loss_multiplier, and open_spiel::battleship::BattleshipConfiguration::ships.
ShotsBoardString()
std::string open_spiel::battleship::BattleshipState::ShotsBoardString (const Player player) const
Definition at line 526 of file battleship.cc.
{
  SPIEL_CHECK_TRUE(player >= 0 && player < NumPlayers());
  const Player opponent = (player == Player{0}) ? Player{1} : Player{0};
  const BattleshipConfiguration& conf = bs_game_->conf;
  // We keep the board in memory as vectors of strings. Initially, all strings
  // only contain whitespace.
  std::vector<std::string> shots_board(conf.board_height,
                                       std::string(conf.board_width, ' '));
  // We fill in the board that represents the outcome of the player's
  // shots.
  //
  // We start by adding a '@' to all the positions where the player shot.
  // That corresponds to marking all shots as 'misses'. We will promote them
  // to ship-hit marks '#' in a shortly.
  for (const auto& move : moves_) {
    if (move.player == player && absl::holds_alternative<Shot>(move.action)) {
      const Shot& shot = absl::get<Shot>(move.action);
      if (conf.allow_repeated_shots) {
        SPIEL_DCHECK_TRUE(shots_board[shot.row][shot.col] == ' ' ||
                          shots_board[shot.row][shot.col] == '@');
      } else {
        SPIEL_DCHECK_EQ(shots_board[shot.row][shot.col], ' ');
      }
      shots_board[shot.row][shot.col] = '@';
    }
  }
  // Now, we iterate through the ship placements of the opponent. If a ship
  // has been hit, then we will promote '@' to '#'.
  for (const auto& move : moves_) {
    if (move.player == opponent &&
        absl::holds_alternative<ShipPlacement>(move.action)) {
      const ShipPlacement& placement = absl::get<ShipPlacement>(move.action);
      // We now iterate over all the cells that the ship covers on the board
      // and fill in the `player_board` string representation.
      Cell cell = placement.TopLeftCorner();
      for (int i = 0; i < placement.ship.length; ++i) {
        SPIEL_DCHECK_TRUE(cell.row >= 0 && cell.row < conf.board_height);
        SPIEL_DCHECK_TRUE(cell.col >= 0 && cell.col < conf.board_width);
        if (shots_board[cell.row][cell.col] == '@') {
          shots_board[cell.row][cell.col] = '#';
        } else {
          // Ships cannot intersect, so it's impossible that we would go over
          // a '#'.
          SPIEL_DCHECK_EQ(shots_board[cell.row][cell.col], ' ');
        }
        if (placement.direction == ShipPlacement::Direction::Horizontal) {
          ++cell.col;
        } else {
          SPIEL_DCHECK_TRUE(placement.direction ==
                            ShipPlacement::Direction::Vertical);
          ++cell.row;
        }
      }
    }
  }
  std::string output;
  absl::StrAppend(&output, "+", std::string(conf.board_width, '-'), "+\n");
  for (const auto& row : shots_board) {
    absl::StrAppend(&output, "|", row, "|\n");
  }
  absl::StrAppend(&output, "+", std::string(conf.board_width, '-'), "+\n");
  return output;
}
References open_spiel::battleship::BattleshipConfiguration::allow_repeated_shots, open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, open_spiel::battleship::Cell::col, open_spiel::battleship::CellAndDirection::direction, absl::get(), absl::holds_alternative(), i, open_spiel::battleship::Ship::length, player, open_spiel::battleship::Cell::row, open_spiel::battleship::ShipPlacement::ship, SPIEL_CHECK_TRUE, SPIEL_DCHECK_EQ, SPIEL_DCHECK_TRUE, absl::StrAppend(), and open_spiel::battleship::CellAndDirection::TopLeftCorner().
ToPrettyString()
std::string open_spiel::battleship::BattleshipState::ToPrettyString () const
Definition at line 599 of file battleship.cc.
{
  std::string state_str;
  absl::StrAppend(&state_str, "Player 0's board:\n");
  absl::StrAppend(&state_str, OwnBoardString(Player{0}));
  absl::StrAppend(&state_str, "\nPlayer 1's board:\n");
  absl::StrAppend(&state_str, OwnBoardString(Player{1}));
  return state_str;
}
References absl::StrAppend().
ToString()
std::string open_spiel::battleship::BattleshipState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 181 of file battleship.cc.
{
  std::string state_str = ToPrettyString();
  // The board representation returned by `ToPrettyString` does not distinguish
  // between the order of moves. To disambiguate and have ToString fully capture
  // the state, we also include the order of the moves in a separate line.
  absl::StrAppend(&state_str, "\nFull history: ");
  for (const auto& move : moves_) {
    if (move.player == Player{0}) {
      absl::StrAppend(&state_str, "/0:");
    } else {
      absl::StrAppend(&state_str, "/1:");
    }
    if (absl::holds_alternative<ShipPlacement>(move.action)) {
      absl::StrAppend(&state_str,
                      absl::get<ShipPlacement>(move.action).ToString());
    } else {
      SPIEL_DCHECK_TRUE(absl::holds_alternative<Shot>(move.action));
      absl::StrAppend(&state_str, absl::get<Shot>(move.action).ToString());
    }
  }
  absl::StrAppend(&state_str, "\n");
  return state_str;
}
References absl::get(), absl::holds_alternative(), SPIEL_DCHECK_TRUE, and absl::StrAppend().
UndoAction()
void open_spiel::battleship::BattleshipState::UndoAction (Player player, Action action_id) override virtual
Reimplemented from open_spiel::State.
Definition at line 436 of file battleship.cc.
{
  SPIEL_CHECK_GT(moves_.size(), 0);
  // XXX(gfarina): It looks like SPIEL_CHECK_EQ wants to print a PlayerAction
  //     on failure, but std::cout was not overloaded. For now I moved to a
  //     SPIEL_CHECK_TRUE.
  SPIEL_CHECK_TRUE((history_.back() == PlayerAction{player, action_id}));
  history_.pop_back();
  moves_.pop_back();
  --move_number_;
}
References SPIEL_CHECK_GT, and SPIEL_CHECK_TRUE.
The documentation for this class was generated from the following files:
open_spiel/games/battleship/battleship.h
open_spiel/games/battleship/battleship.cc