open spiel: CordAppendBufferTest Class Reference
CordAppendBufferTest Class Reference
Public Member Functions
size_t is_default () const
size_t limit () const
size_t maximum_payload () const
absl::CordBuffer GetAppendBuffer (absl::Cord &cord, size_t capacity, size_t min_capacity=16)
Static Public Member Functions
static std::string ToString (testing::TestParamInfo< bool > param)
Detailed Description
Definition at line 735 of file cord_test.cc.
Member Function Documentation
GetAppendBuffer()
absl::CordBuffer CordAppendBufferTest::GetAppendBuffer (absl::Cord & cord, size_t capacity, size_t min_capacity = 16) inline
Definition at line 754 of file cord_test.cc.
{
    return is_default()
               ? cord.GetAppendBuffer(capacity, min_capacity)
               : cord.GetCustomAppendBuffer(limit(), capacity, min_capacity);
  }
References absl::Cord::GetAppendBuffer(), absl::Cord::GetCustomAppendBuffer(), is_default(), and limit().
is_default()
size_t CordAppendBufferTest::is_default () const inline
Definition at line 737 of file cord_test.cc.
{ return GetParam(); }
Referenced by GetAppendBuffer(), limit(), and maximum_payload().
limit()
size_t CordAppendBufferTest::limit () const inline
Definition at line 744 of file cord_test.cc.
                       {
    return is_default() ? absl::CordBuffer::kDefaultLimit
                        : absl::CordBuffer::kCustomLimit;
  }
References is_default(), absl::CordBuffer::kCustomLimit, and absl::CordBuffer::kDefaultLimit.
Referenced by GetAppendBuffer(), and maximum_payload().
maximum_payload()
size_t CordAppendBufferTest::maximum_payload () const inline
Definition at line 749 of file cord_test.cc.
{
    return is_default() ? absl::CordBuffer::MaximumPayload()
                        : absl::CordBuffer::MaximumPayload(limit());
  }
References is_default(), limit(), and absl::CordBuffer::MaximumPayload().
ToString()
static std::string CordAppendBufferTest::ToString (testing::TestParamInfo< bool > param) inline static
Definition at line 740 of file cord_test.cc.
{
    return param.param ? "DefaultLimit" : "CustomLimit";
  }
References param.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/cord_test.cc