open spiel: absl::TimeZone Class Reference
absl::TimeZone Class Reference
#include <time.h>
Classes
struct CivilInfo
struct CivilTransition
struct TimeInfo
Public Member Functions
TimeZone (time_internal::cctz::time_zone tz)
TimeZone ()=default
TimeZone (const TimeZone &)=default
TimeZone & operator= (const TimeZone &)=default
operator time_internal::cctz::time_zone () const
std::string name () const
CivilInfo At (Time t) const
TimeInfo At (CivilSecond ct) const
bool NextTransition (Time t, CivilTransition *trans) const
bool PrevTransition (Time t, CivilTransition *trans) const
Friends
template<typename H >
H AbslHashValue (H h, TimeZone tz)
bool operator== (TimeZone a, TimeZone b)
bool operator!= (TimeZone a, TimeZone b)
std::ostream & operator<< (std::ostream &os, TimeZone tz)
Detailed Description
Definition at line 975 of file time.h.
Constructor & Destructor Documentation
TimeZone() [1/3]
absl::TimeZone::TimeZone (time_internal::cctz::time_zone tz) inline explicit
Definition at line 977 of file time.h.
: cz_(tz) {}
TimeZone() [2/3]
absl::TimeZone::TimeZone () default
TimeZone() [3/3]
absl::TimeZone::TimeZone (const TimeZone &) default
Member Function Documentation
At() [1/2]
absl::TimeZone::TimeInfo absl::TimeZone::At (CivilSecond ct) const
Definition at line 368 of file time.cc.
{
  const cctz::civil_second cs(ct);
  const auto cl = cz_.lookup(cs);
  TimeZone::TimeInfo ti;
  switch (cl.kind) {
    case cctz::time_zone::civil_lookup::UNIQUE:
      ti.kind = TimeZone::TimeInfo::UNIQUE;
      break;
    case cctz::time_zone::civil_lookup::SKIPPED:
      ti.kind = TimeZone::TimeInfo::SKIPPED;
      break;
    case cctz::time_zone::civil_lookup::REPEATED:
      ti.kind = TimeZone::TimeInfo::REPEATED;
      break;
  }
  ti.pre = MakeTimeWithOverflow(cl.pre, cs, cz_);
  ti.trans = MakeTimeWithOverflow(cl.trans, cs, cz_);
  ti.post = MakeTimeWithOverflow(cl.post, cs, cz_);
  return ti;
}
References absl::time_internal::cctz::time_zone::lookup(), absl::TimeZone::TimeInfo::REPEATED, absl::TimeZone::TimeInfo::SKIPPED, and absl::TimeZone::TimeInfo::UNIQUE.
At() [2/2]
absl::TimeZone::CivilInfo absl::TimeZone::At (Time t) const
Definition at line 351 of file time.cc.
{
  if (t == absl::InfiniteFuture()) return InfiniteFutureCivilInfo();
  if (t == absl::InfinitePast()) return InfinitePastCivilInfo();
  const auto ud = time_internal::ToUnixDuration(t);
  const auto tp = unix_epoch() + cctz::seconds(time_internal::GetRepHi(ud));
  const auto al = cz_.lookup(tp);
  TimeZone::CivilInfo ci;
  ci.cs = CivilSecond(al.cs);
  ci.subsecond = time_internal::MakeDuration(0, time_internal::GetRepLo(ud));
  ci.offset = al.offset;
  ci.is_dst = al.is_dst;
  ci.zone_abbr = al.abbr;
  return ci;
}
References absl::TimeZone::CivilInfo::cs, absl::time_internal::GetRepHi(), absl::time_internal::GetRepLo(), absl::InfiniteFuture(), absl::InfinitePast(), absl::TimeZone::CivilInfo::is_dst, absl::time_internal::cctz::time_zone::lookup(), absl::time_internal::MakeDuration(), absl::TimeZone::CivilInfo::offset, absl::TimeZone::CivilInfo::subsecond, absl::time_internal::ToUnixDuration(), and absl::TimeZone::CivilInfo::zone_abbr.
name()
std::string absl::TimeZone::name () const inline
Definition at line 986 of file time.h.
{ return cz_.name(); }
Referenced by pybind11::detail::type_caster< absl::TimeZone >::cast().
NextTransition()
bool absl::TimeZone::NextTransition (Time t, CivilTransition * trans) const
Definition at line 390 of file time.cc.
{
  return FindTransition(cz_, &cctz::time_zone::next_transition, t, trans);
}
operator time_internal::cctz::time_zone()
absl::TimeZone::operator time_internal::cctz::time_zone () const inline explicit
Definition at line 984 of file time.h.
{ return cz_; }
operator=()
TimeZone & absl::TimeZone::operator= (const TimeZone &) default
PrevTransition()
bool absl::TimeZone::PrevTransition (Time t, CivilTransition * trans) const
Definition at line 394 of file time.cc.
{
  return FindTransition(cz_, &cctz::time_zone::prev_transition, t, trans);
}
Friends And Related Symbol Documentation
AbslHashValue
template<typename H > H AbslHashValue (H h, TimeZone tz) friend
Definition at line 1119 of file time.h.
{
    return H::combine(std::move(h), tz.cz_);
  }
operator!=
bool operator!= (TimeZone a, TimeZone b) friend
Definition at line 1125 of file time.h.
{ return a.cz_ != b.cz_; }
operator<<
std::ostream & operator<< (std::ostream & os, TimeZone tz) friend
Definition at line 1126 of file time.h.
{
    return os << tz.name();
  }
operator==
bool operator== (TimeZone a, TimeZone b) friend
Definition at line 1124 of file time.h.
{ return a.cz_ == b.cz_; }
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/time/time.h
open_spiel/abseil-cpp/absl/time/time.cc