open spiel: absl::flags_internal::FlagSaverImpl Class Reference
absl::flags_internal::FlagSaverImpl Class Reference
Public Member Functions
FlagSaverImpl ()=default
FlagSaverImpl (const FlagSaverImpl &)=delete
void operator= (const FlagSaverImpl &)=delete
void SaveFromRegistry ()
void RestoreToRegistry ()
Detailed Description
Definition at line 291 of file reflection.cc.
Constructor & Destructor Documentation
FlagSaverImpl() [1/2]
absl::flags_internal::FlagSaverImpl::FlagSaverImpl () default
FlagSaverImpl() [2/2]
absl::flags_internal::FlagSaverImpl::FlagSaverImpl (const FlagSaverImpl &) delete
Member Function Documentation
operator=()
void absl::flags_internal::FlagSaverImpl::operator= (const FlagSaverImpl &) delete
RestoreToRegistry()
void absl::flags_internal::FlagSaverImpl::RestoreToRegistry () inline
Definition at line 310 of file reflection.cc.
{
    for (const auto& flag_state : backup_registry_) {
      flag_state->Restore();
    }
  }
Referenced by absl::FlagSaver::~FlagSaver().
SaveFromRegistry()
void absl::flags_internal::FlagSaverImpl::SaveFromRegistry () inline
Definition at line 299 of file reflection.cc.
{
    assert(backup_registry_.empty());  // call only once!
    flags_internal::ForEachFlag([&](CommandLineFlag& flag) {
      if (auto flag_state =
              flags_internal::PrivateHandleAccessor::SaveState(flag)) {
        backup_registry_.emplace_back(std::move(flag_state));
      }
    });
  }
References absl::flags_internal::ForEachFlag(), and absl::flags_internal::PrivateHandleAccessor::SaveState().
Referenced by absl::FlagSaver::FlagSaver().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/flags/reflection.cc