open spiel: open_spiel::quoridor::QuoridorGame Class Reference
open_spiel::quoridor::QuoridorGame Class Reference
#include <quoridor.h>
Public Member Functions
QuoridorGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
int NumCellStates () const
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 163 of file quoridor.h.
Constructor & Destructor Documentation
QuoridorGame()
open_spiel::quoridor::QuoridorGame::QuoridorGame (const GameParameters & params) explicit
Definition at line 663 of file quoridor.cc.
    : Game(kGameType, params),
      board_size_(ParameterValue<int>("board_size")),
      wall_count_(
          ParameterValue<int>("wall_count", board_size_ * board_size_ / 8)),
      ansi_color_output_(ParameterValue<bool>("ansi_color_output")),
      num_players_(ParameterValue<int>("players")) {
  if (board_size_ < 3) {
    // For relative moves, we need to be able to describe moves using a 3x3 grid
    // and since we use the board to number the moves (see above), we need the
    // playing board to be at least that big.
    SpielFatalError("Board size must be at least 3x3.");
  }
}
References open_spiel::SpielFatalError().
Member Function Documentation
MaxGameLength()
int open_spiel::quoridor::QuoridorGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 180 of file quoridor.h.
{
    // There's no anti-repetition rule, so this could be infinite, but no sane
    // agent would take more moves than placing all the walls and visiting
    // all squares.
    return kMaxGameLengthFactor * board_size_ * board_size_;
  }
References open_spiel::quoridor::kMaxGameLengthFactor.
MaxUtility()
double open_spiel::quoridor::QuoridorGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 176 of file quoridor.h.
{ return 1; }
MinUtility()
double open_spiel::quoridor::QuoridorGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 174 of file quoridor.h.
{ return -1; }
NewInitialState()
std::unique_ptr< State > open_spiel::quoridor::QuoridorGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 168 of file quoridor.h.
{
    return std::unique_ptr<State>(new QuoridorState(
        shared_from_this(), board_size_, wall_count_, ansi_color_output_));
  }
NumCellStates()
int open_spiel::quoridor::QuoridorGame::NumCellStates () const inline
Definition at line 173 of file quoridor.h.
{ return num_players_ + 1; }
Referenced by ObservationTensorShape().
NumDistinctActions()
int open_spiel::quoridor::QuoridorGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 167 of file quoridor.h.
{ return Diameter() * Diameter(); }
NumPlayers()
int open_spiel::quoridor::QuoridorGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 172 of file quoridor.h.
{ return num_players_; }
ObservationTensorShape()
std::vector< int > open_spiel::quoridor::QuoridorGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 177 of file quoridor.h.
{
    return {NumCellStates() + num_players_, Diameter(), Diameter()};
  }
References NumCellStates().
UtilitySum()
absl::optional< double > open_spiel::quoridor::QuoridorGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 175 of file quoridor.h.
{ return 0; }
The documentation for this class was generated from the following files:
open_spiel/games/quoridor/quoridor.h
open_spiel/games/quoridor/quoridor.cc