open spiel: open_spiel::backgammon::BackgammonState Class Reference
open_spiel::backgammon::BackgammonState Class Reference
#include <backgammon.h>
Public Member Functions
BackgammonState (const BackgammonState &)=default
BackgammonState (std::shared_ptr< const Game >, ScoringType scoring_type, bool hyper_backgammone)
Player CurrentPlayer () const override
void UndoAction (Player player, Action action) override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action move_id) const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void SetState (int cur_player, bool double_turn, const std::vector< int > &dice, const std::vector< int > &bar, const std::vector< int > &scores, const std::vector< std::vector< int > > &board)
int Opponent (int player) const
int GetDistance (int player, int from, int to) const
bool IsOff (int player, int pos) const
bool IsFurther (int player, int pos1, int pos2) const
bool IsLegalFromTo (int player, int from_pos, int to_pos, int my_checkers_from, int opp_checkers_to) const
int GetToPos (int player, int from_pos, int pips) const
int CountTotalCheckers (int player) const
bool IsHit (Player player, int from_pos, int num) const
int player_turns () const
int player_turns (int player) const
int bar (int player) const
int score (int player) const
int dice (int i) const
bool double_turn () const
int board (int player, int pos) const
Action CheckerMovesToSpielMove (const std::vector< CheckerMove > &moves) const
std::vector< CheckerMove > SpielMoveToCheckerMoves (int player, Action spiel_move) const
Action TranslateAction (int from1, int from2, bool use_high_die_first) const
std::vector< CheckerMove > AugmentWithHitInfo (Player player, const std::vector< CheckerMove > &cmoves) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 121 of file backgammon.h.
Constructor & Destructor Documentation
BackgammonState() [1/2]
open_spiel::backgammon::BackgammonState::BackgammonState (const BackgammonState &) default
Referenced by Clone().
BackgammonState() [2/2]
open_spiel::backgammon::BackgammonState::BackgammonState (std::shared_ptr< const Game > game, ScoringType scoring_type, bool hyper_backgammone)
Definition at line 338 of file backgammon.cc.
    : State(game),
      scoring_type_(scoring_type),
      hyper_backgammon_(hyper_backgammon),
      cur_player_(kChancePlayerId),
      prev_player_(kChancePlayerId),
      turns_(-1),
      x_turns_(0),
      o_turns_(0),
      double_turn_(false),
      dice_({}),
      bar_({0, 0}),
      scores_({0, 0}),
      board_(
          {std::vector<int>(kNumPoints, 0), std::vector<int>(kNumPoints, 0)}),
      turn_history_info_({}) {
  SetupInitialBoard();
}
Member Function Documentation
ActionToString()
std::string open_spiel::backgammon::BackgammonState::ActionToString (Player player, Action move_id) const override virtual
Implements open_spiel::State.
Definition at line 168 of file backgammon.cc.
{
  if (player == kChancePlayerId) {
    if (turns_ >= 0) {
      // Normal chance roll.
      return absl::StrCat("chance outcome ", move_id,
                          " (roll: ", kChanceOutcomeValues[move_id][0],
                          kChanceOutcomeValues[move_id][1], ")");
    } else {
      // Initial roll to determine who starts.
      const char* starter = (move_id < kNumNonDoubleOutcomes ?
                             "X starts" : "O starts");
      if (move_id >= kNumNonDoubleOutcomes) {
        move_id -= kNumNonDoubleOutcomes;
      }
      return absl::StrCat("chance outcome ", move_id, " ", starter, ", ",
                          "(roll: ", kChanceOutcomeValues[move_id][0],
                          kChanceOutcomeValues[move_id][1], ")");
    }
  } else {
    // Assemble a human-readable string representation of the move using
    // standard backgammon notation:
    //
    // - Always show the numbering going from Bar->24->0->Off, irrespective of
    //   which player is moving.
    // - Show the start position followed by end position.
    // - Show hits with an asterisk, e.g. 9/7*.
    // - Order the moves by highest number first, e.g. 22/7 10/8 not 10/8 22/7.
    //   Not an official requirement, but seems to be standard convention.
    // - Show duplicate moves as 10/8(2).
    // - Show moves on a single piece as 10/8/5 not 10/8 8/5
    //
    // Note that there are tests to ensure the ActionToString follows this
    // output format. Any changes would need to be reflected in the tests as
    // well.
    std::vector<CheckerMove> cmoves = SpielMoveToCheckerMoves(player, move_id);
    int cmove0_start;
    int cmove1_start;
    if (player == kOPlayerId) {
      cmove0_start = (cmoves[0].pos == kBarPos ? kNumBarPosHumanReadable
                                               : cmoves[0].pos + 1);
      cmove1_start = (cmoves[1].pos == kBarPos ? kNumBarPosHumanReadable
                                               : cmoves[1].pos + 1);
    } else {
      // swap the board numbering round for Player X so player is moving
      // from 24->0
      cmove0_start = (cmoves[0].pos == kBarPos ? kNumBarPosHumanReadable
                                               : kNumPoints - cmoves[0].pos);
      cmove1_start = (cmoves[1].pos == kBarPos ? kNumBarPosHumanReadable
                                               : kNumPoints - cmoves[1].pos);
    }
    // Add hit information and compute whether the moves go off the board.
    int cmove0_end = AugmentCheckerMove(&cmoves[0], player, cmove0_start);
    int cmove1_end = AugmentCheckerMove(&cmoves[1], player, cmove1_start);
    // check for 2 pieces hitting on the same point.
    bool double_hit =
        (cmoves[1].hit && cmoves[0].hit && cmove1_end == cmove0_end);
    std::string returnVal = "";
    if (cmove0_start == cmove1_start &&
        cmove0_end == cmove1_end) {     // same move, show as (2).
      if (cmoves[1].num == kPassPos) {  // Player can't move at all!
        returnVal = "Pass";
      } else {
        returnVal = absl::StrCat(move_id, " - ",
                                 PositionToStringHumanReadable(cmove0_start),
                                 "/", PositionToStringHumanReadable(cmove0_end),
                                 cmoves[0].hit ? "*" : "", "(2)");
      }
    } else if ((cmove0_start < cmove1_start ||
                (cmove0_start == cmove1_start && cmove0_end < cmove1_end) ||
                cmoves[0].num == kPassPos) &&
               cmoves[1].num != kPassPos) {
      // tradition to start with higher numbers first,
      // so swap moves round if this not the case. If
      // there is a pass move, put it last.
      if (cmove1_end == cmove0_start) {
        // Check to see if the same piece is moving for both
        // moves, as this changes the format of the output.
        returnVal = absl::StrCat(
            move_id, " - ", PositionToStringHumanReadable(cmove1_start), "/",
            PositionToStringHumanReadable(cmove1_end), cmoves[1].hit ? "*" : "",
            "/", PositionToStringHumanReadable(cmove0_end),
            cmoves[0].hit ? "*" : "");
      } else {
        returnVal = absl::StrCat(
            move_id, " - ", PositionToStringHumanReadable(cmove1_start), "/",
            PositionToStringHumanReadable(cmove1_end), cmoves[1].hit ? "*" : "",
            " ",
            (cmoves[0].num != kPassPos)
                ? PositionToStringHumanReadable(cmove0_start)
                : "",
            (cmoves[0].num != kPassPos) ? "/" : "",
            PositionToStringHumanReadable(cmove0_end),
            (cmoves[0].hit && !double_hit) ? "*" : "");
      }
    } else {
      if (cmove0_end == cmove1_start) {
        // Check to see if the same piece is moving for both
        // moves, as this changes the format of the output.
        returnVal = absl::StrCat(
            move_id, " - ", PositionToStringHumanReadable(cmove0_start), "/",
            PositionToStringHumanReadable(cmove0_end), cmoves[0].hit ? "*" : "",
            "/", PositionToStringHumanReadable(cmove1_end),
            cmoves[1].hit ? "*" : "");
      } else {
        returnVal = absl::StrCat(
            move_id, " - ", PositionToStringHumanReadable(cmove0_start), "/",
            PositionToStringHumanReadable(cmove0_end), cmoves[0].hit ? "*" : "",
            " ",
            (cmoves[1].num != kPassPos)
                ? PositionToStringHumanReadable(cmove1_start)
                : "",
            (cmoves[1].num != kPassPos) ? "/" : "",
            PositionToStringHumanReadable(cmove1_end),
            (cmoves[1].hit && !double_hit) ? "*" : "");
      }
    }
    return returnVal;
  }
}
References open_spiel::backgammon::kBarPos, open_spiel::kChancePlayerId, open_spiel::backgammon::kNumPoints, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kPassPos, num, player, open_spiel::backgammon::PositionToStringHumanReadable(), SpielMoveToCheckerMoves(), and absl::StrCat().
AugmentWithHitInfo()
std::vector< CheckerMove > open_spiel::backgammon::BackgammonState::AugmentWithHitInfo (Player player, const std::vector< CheckerMove > & cmoves) const
Definition at line 632 of file backgammon.cc.
{
  std::vector<CheckerMove> new_cmoves = cmoves;
  for (int i = 0; i < 2; ++i) {
    new_cmoves[i].hit = IsHit(player, cmoves[i].pos, cmoves[i].num);
  }
  return new_cmoves;
}
References i, IsHit(), num, and player.
bar()
int open_spiel::backgammon::BackgammonState::bar (int player) const inline
Definition at line 185 of file backgammon.h.
{ return bar_[player]; }
References player.
Referenced by SetState().
board()
int open_spiel::backgammon::BackgammonState::board (int player, int pos) const
Definition at line 380 of file backgammon.cc.
{
  if (pos == kBarPos) {
    return bar_[player];
  } else {
    SPIEL_CHECK_GE(pos, 0);
    SPIEL_CHECK_LT(pos, kNumPoints);
    return board_[player][pos];
  }
}
References open_spiel::backgammon::kBarPos, open_spiel::backgammon::kNumPoints, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Referenced by open_spiel.python.games.tic_tac_toe.TicTacToeState::__str__(), open_spiel.python.games.tic_tac_toe.TicTacToeState::_apply_action(), open_spiel.python.games.tic_tac_toe.TicTacToeState::_legal_actions(), IsHit(), IsLegalFromTo(), and SetState().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::backgammon::BackgammonState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 1154 of file backgammon.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  if (turns_ == -1) {
    // Doubles not allowed for the initial roll to determine who goes first.
    // Range 0-14: X goes first, range 15-29: O goes first.
    std::vector<std::pair<Action, double>> outcomes;
    int num_outcomes = kNumNonDoubleOutcomes * 2;
    outcomes.reserve(num_outcomes);
    const double uniform_prob = 1.0 / num_outcomes;
    for (Action action = 0; action < num_outcomes; ++action) {
      outcomes.push_back({action, uniform_prob});
    }
    return outcomes;
  } else {
    return kChanceOutcomes;
  }
}
References action, open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
CheckerMovesToSpielMove()
Action open_spiel::backgammon::BackgammonState::CheckerMovesToSpielMove (const std::vector< CheckerMove > & moves) const
Definition at line 554 of file backgammon.cc.
{
  SPIEL_CHECK_LE(moves.size(), 2);
  int dig0 = EncodedPassMove();
  int dig1 = EncodedPassMove();
  bool high_roll_first = false;
  int high_roll = DiceValue(0) >= DiceValue(1) ? DiceValue(0) : DiceValue(1);
  if (!moves.empty()) {
    int pos1 = moves[0].pos;
    if (pos1 == kBarPos) {
      pos1 = EncodedBarMove();
    }
    if (pos1 != kPassPos) {
      int num1 = moves[0].num;
      dig0 = pos1;
      high_roll_first = num1 == high_roll;
    }
  }
  if (moves.size() > 1) {
    int pos2 = moves[1].pos;
    if (pos2 == kBarPos) {
      pos2 = EncodedBarMove();
    }
    if (pos2 != kPassPos) {
      dig1 = pos2;
    }
  }
  Action move = dig1 * 26 + dig0;
  if (!high_roll_first) {
    move += 676;  // 26**2
  }
  SPIEL_CHECK_GE(move, 0);
  SPIEL_CHECK_LT(move, kNumDistinctActions);
  return move;
}
References open_spiel::backgammon::kBarPos, open_spiel::backgammon::kNumDistinctActions, open_spiel::backgammon::kPassPos, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and SPIEL_CHECK_LT.
Referenced by TranslateAction().
Clone()
std::unique_ptr< State > open_spiel::backgammon::BackgammonState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 1279 of file backgammon.cc.
{
  return std::unique_ptr<State>(new BackgammonState(*this));
}
References BackgammonState().
Referenced by LegalActions().
CountTotalCheckers()
int open_spiel::backgammon::BackgammonState::CountTotalCheckers (int player) const
Definition at line 859 of file backgammon.cc.
{
  int total = 0;
  for (int i = 0; i < 24; ++i) {
    SPIEL_CHECK_GE(board_[player][i], 0);
    total += board_[player][i];
  }
  SPIEL_CHECK_GE(bar_[player], 0);
  total += bar_[player];
  SPIEL_CHECK_GE(scores_[player], 0);
  total += scores_[player];
  return total;
}
References i, player, SPIEL_CHECK_GE, and total.
Referenced by LegalActions(), and SetState().
CurrentPlayer()
Player open_spiel::backgammon::BackgammonState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 390 of file backgammon.cc.
{
  return IsTerminal() ? kTerminalPlayerId : Player{cur_player_};
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by TranslateAction().
dice()
int open_spiel::backgammon::BackgammonState::dice (int i) const inline
Definition at line 187 of file backgammon.h.
{ return dice_[i]; }
References i.
Referenced by SetState().
DoApplyAction()
void open_spiel::backgammon::BackgammonState::DoApplyAction (Action move_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 416 of file backgammon.cc.
{
  if (IsChanceNode()) {
    turn_history_info_.push_back(TurnHistoryInfo(kChancePlayerId, prev_player_,
                                                 dice_, move, double_turn_,
                                                 false, false));
    if (turns_ == -1) {
      // The first chance node determines who goes first: X or O.
      // The move is between 0 and 29 and the range determines whether X starts
      // or O starts. The value is then converted to a number between 0 and 15,
      // which represents the non-double chance outcome that the first player
      // starts with (see RollDice(move) below). These 30 possibilities are
      // constructed in GetChanceOutcomes().
      SPIEL_CHECK_TRUE(dice_.empty());
      if (move < kNumNonDoubleOutcomes) {
        // X starts.
        cur_player_ = prev_player_ = kXPlayerId;
      } else {
        // O Starts
        cur_player_ = prev_player_ = kOPlayerId;
        move -= kNumNonDoubleOutcomes;
      }
      RollDice(move);
      turns_ = 0;
      return;
    } else {
      // Normal chance node.
      SPIEL_CHECK_TRUE(dice_.empty());
      RollDice(move);
      cur_player_ = Opponent(prev_player_);
      return;
    }
  }
  // Normal move action.
  std::vector<CheckerMove> moves = SpielMoveToCheckerMoves(cur_player_, move);
  bool first_move_hit = ApplyCheckerMove(cur_player_, moves[0]);
  bool second_move_hit = ApplyCheckerMove(cur_player_, moves[1]);
  turn_history_info_.push_back(
      TurnHistoryInfo(cur_player_, prev_player_, dice_, move, double_turn_,
                      first_move_hit, second_move_hit));
  if (!double_turn_) {
    turns_++;
    if (cur_player_ == kXPlayerId) {
      x_turns_++;
    } else if (cur_player_ == kOPlayerId) {
      o_turns_++;
    }
  }
  prev_player_ = cur_player_;
  // Check for doubles.
  bool extra_turn = false;
  if (!double_turn_ && dice_[0] == dice_[1]) {
    // Check the dice, and unuse them if they are used.
    int dice_used = 0;
    for (int i = 0; i < 2; i++) {
      if (dice_[i] > 6) {
        dice_[i] -= 6;
        dice_used++;
      }
      SPIEL_CHECK_GE(dice_[i], 1);
      SPIEL_CHECK_LE(dice_[i], 6);
    }
    if (dice_used == 2) {
      extra_turn = true;
    }
  }
  if (extra_turn) {
    // Dice have been unused above.
    double_turn_ = true;
  } else {
    cur_player_ = kChancePlayerId;
    dice_.clear();
    double_turn_ = false;
  }
}
References i, open_spiel::State::IsChanceNode(), open_spiel::kChancePlayerId, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kXPlayerId, Opponent(), SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_TRUE, and SpielMoveToCheckerMoves().
double_turn()
bool open_spiel::backgammon::BackgammonState::double_turn () const inline
Definition at line 188 of file backgammon.h.
{ return double_turn_; }
Referenced by SetState().
GetDistance()
int open_spiel::backgammon::BackgammonState::GetDistance (int player, int from, int to) const
Definition at line 750 of file backgammon.cc.
{
  SPIEL_CHECK_NE(from, kScorePos);
  SPIEL_CHECK_NE(to, kScorePos);
  if (from == kBarPos && player == kXPlayerId) {
    from = -1;
  } else if (from == kBarPos && player == kOPlayerId) {
    from = 24;
  }
  return std::abs(to - from);
}
References from, open_spiel::backgammon::kBarPos, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kScorePos, open_spiel::backgammon::kXPlayerId, player, SPIEL_CHECK_NE, and to.
GetToPos()
int open_spiel::backgammon::BackgammonState::GetToPos (int player, int from_pos, int pips) const
Definition at line 792 of file backgammon.cc.
{
  if (player == kXPlayerId) {
    return (from_pos == kBarPos ? -1 : from_pos) + pips;
  } else if (player == kOPlayerId) {
    return (from_pos == kBarPos ? 24 : from_pos) - pips;
  } else {
    SpielFatalError(absl::StrCat("Player (", player, ") unrecognized."));
  }
}
References open_spiel::backgammon::kBarPos, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kXPlayerId, player, open_spiel::SpielFatalError(), and absl::StrCat().
IsFurther()
bool open_spiel::backgammon::BackgammonState::IsFurther (int player, int pos1, int pos2) const
Definition at line 767 of file backgammon.cc.
{
  if (pos1 == pos2) {
    return false;
  }
  if (pos1 == kBarPos) {
    return true;
  }
  if (pos2 == kBarPos) {
    return false;
  }
  if (pos1 == kPassPos) {
    return false;
  }
  if (pos2 == kPassPos) {
    return false;
  }
  return ((player == kXPlayerId && pos1 < pos2) ||
          (player == kOPlayerId && pos1 > pos2));
}
References open_spiel::backgammon::kBarPos, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kPassPos, open_spiel::backgammon::kXPlayerId, and player.
IsHit()
bool open_spiel::backgammon::BackgammonState::IsHit (Player player, int from_pos, int num) const
Definition at line 530 of file backgammon.cc.
{
  if (from_pos != kPassPos) {
    int to = PositionFrom(player, from_pos, num);
    return to != kScorePos && board(Opponent(player), to) == 1;
  } else {
    return false;
  }
}
References board(), open_spiel::backgammon::kPassPos, open_spiel::backgammon::kScorePos, num, Opponent(), player, and to.
Referenced by AugmentWithHitInfo(), and TranslateAction().
IsLegalFromTo()
bool open_spiel::backgammon::BackgammonState::IsLegalFromTo (int player, int from_pos, int to_pos, int my_checkers_from, int opp_checkers_to) const
Definition at line 803 of file backgammon.cc.
{
  // Must have at least one checker the from position.
  if (my_checkers_from == 0) {
    return false;
  }
  if (opp_checkers_to > 1) {
    return false;
  }
  // Quick validity checks out of the way. This appears to be a valid move.
  // Now, must check: if there are moves on this player's bar, they must move
  // them first, and if there are no legal moves out of the bar, the player
  // loses their turn.
  int my_bar_checkers = board(player, kBarPos);
  if (my_bar_checkers > 0 && from_pos != kBarPos) {
    return false;
  }
  // If this is a scoring move, then check that all this player's checkers are
  // either scored or home.
  if (to_pos < 0 || to_pos > 23) {
    if ((CheckersInHome(player) + scores_[player]) != 15) {
      return false;
    }
    // If it's not *exactly* the right amount, then we have to do a check to see
    // if there exist checkers further from home, as those must be moved first.
    if (player == kXPlayerId && to_pos > 24) {
      for (int pos = from_pos - 1; pos >= 18; pos--) {
        if (board(player, pos) > 0) {
          return false;
        }
      }
    } else if (player == kOPlayerId && to_pos < -1) {
      for (int pos = from_pos + 1; pos <= 5; pos++) {
        if (board(player, pos) > 0) {
          return false;
        }
      }
    }
  }
  return true;
}
References board(), open_spiel::backgammon::kBarPos, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kXPlayerId, and player.
IsOff()
bool open_spiel::backgammon::BackgammonState::IsOff (int player, int pos) const
Definition at line 761 of file backgammon.cc.
{
  // Returns if an absolute position is off the board.
  return ((player == kXPlayerId && pos > 23) ||
          (player == kOPlayerId && pos < 0));
}
References open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kXPlayerId, and player.
IsTerminal()
bool open_spiel::backgammon::BackgammonState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 1239 of file backgammon.cc.
{
  return (scores_[kXPlayerId] == NumCheckersPerPlayer(game_.get()) ||
          scores_[kOPlayerId] == NumCheckersPerPlayer(game_.get()));
}
References open_spiel::State::game_, open_spiel::backgammon::kOPlayerId, and open_spiel::backgammon::kXPlayerId.
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::backgammon::BackgammonState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 1134 of file backgammon.cc.
{
  if (IsChanceNode()) return LegalChanceOutcomes();
  if (IsTerminal()) return {};
  SPIEL_CHECK_EQ(CountTotalCheckers(kXPlayerId),
                 NumCheckersPerPlayer(game_.get()));
  SPIEL_CHECK_EQ(CountTotalCheckers(kOPlayerId),
                 NumCheckersPerPlayer(game_.get()));
  std::unique_ptr<State> cstate = this->Clone();
  BackgammonState* state = dynamic_cast<BackgammonState*>(cstate.get());
  std::set<std::vector<CheckerMove>> movelist;
  int max_moves = state->RecLegalMoves({}, &movelist);
  SPIEL_CHECK_GE(max_moves, 0);
  SPIEL_CHECK_LE(max_moves, 2);
  std::vector<Action> legal_actions = ProcessLegalMoves(max_moves, movelist);
  std::sort(legal_actions.begin(), legal_actions.end());
  return legal_actions;
}
References Clone(), CountTotalCheckers(), open_spiel::State::game_, open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kXPlayerId, open_spiel::State::LegalChanceOutcomes(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and state.
ObservationString()
std::string open_spiel::backgammon::BackgammonState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 294 of file backgammon.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::backgammon::BackgammonState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 300 of file backgammon.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  int opponent = Opponent(player);
  SPIEL_CHECK_EQ(values.size(), kStateEncodingSize);
  auto value_it = values.begin();
  // The format of this vector is described in Section 3.4 of "G. Tesauro,
  // Practical issues in temporal-difference learning, 1994."
  // https://link.springer.com/article/10.1007/BF00992697
  // The values of the dice are added in the last two positions of the vector.
  for (int count : board_[player]) {
    *value_it++ = ((count == 1) ? 1 : 0);
    *value_it++ = ((count == 2) ? 1 : 0);
    *value_it++ = ((count == 3) ? 1 : 0);
    *value_it++ = ((count > 3) ? (count - 3) : 0);
  }
  for (int count : board_[opponent]) {
    *value_it++ = ((count == 1) ? 1 : 0);
    *value_it++ = ((count == 2) ? 1 : 0);
    *value_it++ = ((count == 3) ? 1 : 0);
    *value_it++ = ((count > 3) ? (count - 3) : 0);
  }
  *value_it++ = (bar_[player]);
  *value_it++ = (scores_[player]);
  *value_it++ = ((cur_player_ == player) ? 1 : 0);
  *value_it++ = (bar_[opponent]);
  *value_it++ = (scores_[opponent]);
  *value_it++ = ((cur_player_ == opponent) ? 1 : 0);
  *value_it++ = ((!dice_.empty()) ? dice_[0] : 0);
  *value_it++ = ((dice_.size() > 1) ? dice_[1] : 0);
  SPIEL_CHECK_EQ(value_it, values.end());
}
References open_spiel::backgammon::kStateEncodingSize, open_spiel::State::num_players_, Opponent(), player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Opponent()
int open_spiel::backgammon::BackgammonState::Opponent (int player) const
Definition at line 394 of file backgammon.cc.
{ return 1 - player; }
References player.
Referenced by DoApplyAction(), IsHit(), and ObservationTensor().
player_turns() [1/2]
int open_spiel::backgammon::BackgammonState::player_turns () const inline
Definition at line 181 of file backgammon.h.
{ return turns_; }
player_turns() [2/2]
int open_spiel::backgammon::BackgammonState::player_turns (int player) const inline
Definition at line 182 of file backgammon.h.
{
    return (player == kXPlayerId ? x_turns_ : o_turns_);
  }
References open_spiel::backgammon::kXPlayerId, and player.
Returns()
std::vector< double > open_spiel::backgammon::BackgammonState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 1244 of file backgammon.cc.
{
  int winner = -1;
  int loser = -1;
  if (scores_[kXPlayerId] == 15) {
    winner = kXPlayerId;
    loser = kOPlayerId;
  } else if (scores_[kOPlayerId] == 15) {
    winner = kOPlayerId;
    loser = kXPlayerId;
  } else {
    return {0.0, 0.0};
  }
  // Magnify the util based on the scoring rules for this game.
  int util_mag = 1;
  switch (scoring_type_) {
    case ScoringType::kWinLossScoring:
    default:
      break;
    case ScoringType::kEnableGammons:
      util_mag = (IsGammoned(loser) ? 2 : 1);
      break;
    case ScoringType::kFullScoring:
      util_mag = (IsBackgammoned(loser) ? 3 : IsGammoned(loser) ? 2 : 1);
      break;
  }
  std::vector<double> returns(kNumPlayers);
  returns[winner] = util_mag;
  returns[loser] = -util_mag;
  return returns;
}
References open_spiel::backgammon::kEnableGammons, open_spiel::backgammon::kFullScoring, open_spiel::backgammon::kNumPlayers, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kWinLossScoring, and open_spiel::backgammon::kXPlayerId.
score()
int open_spiel::backgammon::BackgammonState::score (int player) const inline
Definition at line 186 of file backgammon.h.
{ return scores_[player]; }
References player.
SetState()
void open_spiel::backgammon::BackgammonState::SetState (int cur_player, bool double_turn, const std::vector< int > & dice, const std::vector< int > & bar, const std::vector< int > & scores, const std::vector< std::vector< int > > & board)
Definition at line 1283 of file backgammon.cc.
{
  cur_player_ = cur_player;
  double_turn_ = double_turn;
  dice_ = dice;
  bar_ = bar;
  scores_ = scores;
  board_ = board;
  SPIEL_CHECK_EQ(CountTotalCheckers(kXPlayerId),
                 NumCheckersPerPlayer(game_.get()));
  SPIEL_CHECK_EQ(CountTotalCheckers(kOPlayerId),
                 NumCheckersPerPlayer(game_.get()));
}
References bar(), board(), CountTotalCheckers(), dice(), double_turn(), open_spiel::State::game_, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kXPlayerId, and SPIEL_CHECK_EQ.
SpielMoveToCheckerMoves()
std::vector< CheckerMove > open_spiel::backgammon::BackgammonState::SpielMoveToCheckerMoves (int player, Action spiel_move) const
Definition at line 593 of file backgammon.cc.
{
  SPIEL_CHECK_GE(spiel_move, 0);
  SPIEL_CHECK_LT(spiel_move, kNumDistinctActions);
  bool high_roll_first = spiel_move < 676;
  if (!high_roll_first) {
    spiel_move -= 676;
  }
  std::vector<Action> digits = {spiel_move % 26, spiel_move / 26};
  std::vector<CheckerMove> cmoves;
  int high_roll = DiceValue(0) >= DiceValue(1) ? DiceValue(0) : DiceValue(1);
  int low_roll = DiceValue(0) < DiceValue(1) ? DiceValue(0) : DiceValue(1);
  for (int i = 0; i < 2; ++i) {
    SPIEL_CHECK_GE(digits[i], 0);
    SPIEL_CHECK_LE(digits[i], 25);
    int num = -1;
    if (i == 0) {
      num = high_roll_first ? high_roll : low_roll;
    } else {
      num = high_roll_first ? low_roll : high_roll;
    }
    SPIEL_CHECK_GE(num, 1);
    SPIEL_CHECK_LE(num, 6);
    if (digits[i] == EncodedPassMove()) {
      cmoves.push_back(CheckerMove(kPassPos, -1, false));
    } else {
      cmoves.push_back(CheckerMove(
          digits[i] == EncodedBarMove() ? kBarPos : digits[i], num, false));
    }
  }
  return cmoves;
}
References i, open_spiel::backgammon::kBarPos, open_spiel::backgammon::kNumDistinctActions, open_spiel::backgammon::kPassPos, num, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and SPIEL_CHECK_LT.
Referenced by ActionToString(), DoApplyAction(), and UndoAction().
ToString()
std::string open_spiel::backgammon::BackgammonState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 1172 of file backgammon.cc.
{
  std::vector<std::string> board_array = {
      "+------|------+", "|......|......|", "|......|......|",
      "|......|......|", "|......|......|", "|......|......|",
      "|      |      |", "|......|......|", "|......|......|",
      "|......|......|", "|......|......|", "|......|......|",
      "+------|------+"};
  // Fill the board.
  for (int pos = 0; pos < 24; pos++) {
    if (board_[kXPlayerId][pos] > 0 || board_[kOPlayerId][pos] > 0) {
      int start_row = (pos < 12 ? 11 : 1);
      int col = (pos < 12 ? (pos >= 6 ? 12 - pos : 13 - pos)
                          : (pos < 18 ? pos - 11 : pos - 10));
      int row_offset = (pos < 12 ? -1 : 1);
      int owner = board_[kXPlayerId][pos] > 0 ? kXPlayerId : kOPlayerId;
      char piece = (owner == kXPlayerId ? 'x' : 'o');
      int my_checkers = board_[owner][pos];
      for (int i = 0; i < 5 && i < my_checkers; i++) {
        board_array[start_row + i * row_offset][col] = piece;
      }
      // Check for special display of >= 10 and >5 pieces
      if (my_checkers >= 10) {
        char lsd = std::to_string(my_checkers % 10)[0];
        // Make sure it reads downward.
        if (pos < 12) {
          board_array[start_row + row_offset][col] = '1';
          board_array[start_row][col] = lsd;
        } else {
          board_array[start_row][col] = '1';
          board_array[start_row + row_offset][col] = lsd;
        }
      } else if (my_checkers > 5) {
        board_array[start_row][col] = std::to_string(my_checkers)[0];
      }
    }
  }
  std::string board_str = absl::StrJoin(board_array, "\n") + "\n";
  // Extra info like whose turn it is etc.
  absl::StrAppend(&board_str, "Turn: ");
  absl::StrAppend(&board_str, CurPlayerToString(cur_player_));
  absl::StrAppend(&board_str, "\n");
  absl::StrAppend(&board_str, "Dice: ");
  absl::StrAppend(&board_str, !dice_.empty() ? DiceToString(dice_[0]) : "");
  absl::StrAppend(&board_str, dice_.size() > 1 ? DiceToString(dice_[1]) : "");
  absl::StrAppend(&board_str, "\n");
  absl::StrAppend(&board_str, "Bar:");
  absl::StrAppend(&board_str,
                  (bar_[kXPlayerId] > 0 || bar_[kOPlayerId] > 0 ? " " : ""));
  for (int p = 0; p < 2; p++) {
    for (int n = 0; n < bar_[p]; n++) {
      absl::StrAppend(&board_str, (p == kXPlayerId ? "x" : "o"));
    }
  }
  absl::StrAppend(&board_str, "\n");
  absl::StrAppend(&board_str, "Scores, X: ", scores_[kXPlayerId]);
  absl::StrAppend(&board_str, ", O: ", scores_[kOPlayerId], "\n");
  return board_str;
}
References open_spiel::backgammon::CurPlayerToString(), i, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kXPlayerId, n, absl::StrAppend(), and absl::StrJoin().
Referenced by ObservationString().
TranslateAction()
Action open_spiel::backgammon::BackgammonState::TranslateAction (int from1, int from2, bool use_high_die_first) const
Definition at line 539 of file backgammon.cc.
{
  int player = CurrentPlayer();
  int num1 = use_high_die_first ? dice_.at(1) : dice_.at(0);
  int num2 = use_high_die_first ? dice_.at(0) : dice_.at(1);
  bool hit1 = IsHit(player, from1, num1);
  bool hit2 = IsHit(player, from2, num2);
  std::vector<CheckerMove> moves = {{from1, num1, hit1}, {from2, num2, hit2}};
  return CheckerMovesToSpielMove(moves);
}
References CheckerMovesToSpielMove(), CurrentPlayer(), IsHit(), and player.
UndoAction()
void open_spiel::backgammon::BackgammonState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 499 of file backgammon.cc.
{
  {
    const TurnHistoryInfo& thi = turn_history_info_.back();
    SPIEL_CHECK_EQ(thi.player, player);
    SPIEL_CHECK_EQ(action, thi.action);
    cur_player_ = thi.player;
    prev_player_ = thi.prev_player;
    dice_ = thi.dice;
    double_turn_ = thi.double_turn;
    if (player != kChancePlayerId) {
      std::vector<CheckerMove> moves = SpielMoveToCheckerMoves(player, action);
      SPIEL_CHECK_EQ(moves.size(), 2);
      moves[0].hit = thi.first_move_hit;
      moves[1].hit = thi.second_move_hit;
      UndoCheckerMove(player, moves[1]);
      UndoCheckerMove(player, moves[0]);
      turns_--;
      if (!double_turn_) {
        if (player == kXPlayerId) {
          x_turns_--;
        } else if (player == kOPlayerId) {
          o_turns_--;
        }
      }
    }
  }
  turn_history_info_.pop_back();
  history_.pop_back();
  --move_number_;
}
References action, open_spiel::backgammon::TurnHistoryInfo::action, open_spiel::backgammon::TurnHistoryInfo::dice, open_spiel::backgammon::TurnHistoryInfo::double_turn, open_spiel::backgammon::TurnHistoryInfo::first_move_hit, open_spiel::State::history_, open_spiel::kChancePlayerId, open_spiel::backgammon::kOPlayerId, open_spiel::backgammon::kXPlayerId, open_spiel::State::move_number_, open_spiel::backgammon::TurnHistoryInfo::player, player, open_spiel::backgammon::TurnHistoryInfo::prev_player, open_spiel::backgammon::TurnHistoryInfo::second_move_hit, SPIEL_CHECK_EQ, and SpielMoveToCheckerMoves().
The documentation for this class was generated from the following files:
open_spiel/games/backgammon/backgammon.h
open_spiel/games/backgammon/backgammon.cc