open spiel: open_spiel::dark_chess::DarkChessObserver Class Reference
open_spiel::dark_chess::DarkChessObserver Class Reference
Public Member Functions
DarkChessObserver (IIGObservationType iig_obs_type)
void WriteTensor (const State &observed_state, int player, Allocator *allocator) const override
std::string StringFrom (const State &observed_state, int player) const override
Public Member Functions inherited from open_spiel::Observer
Observer (bool has_string, bool has_tensor)
bool HasString () const
bool HasTensor () const
virtual ~Observer ()=default
Additional Inherited Members
Protected Attributes inherited from open_spiel::Observer
bool has_string_
bool has_tensor_
Detailed Description
Definition at line 263 of file dark_chess.cc.
Constructor & Destructor Documentation
DarkChessObserver()
open_spiel::dark_chess::DarkChessObserver::DarkChessObserver (IIGObservationType iig_obs_type) inline explicit
Definition at line 265 of file dark_chess.cc.
      : Observer(/*has_string=*/ObserverHasString(iig_obs_type),
                 /*has_tensor=*/ObserverHasTensor(iig_obs_type)),
        iig_obs_type_(iig_obs_type) {}
Member Function Documentation
StringFrom()
std::string open_spiel::dark_chess::DarkChessObserver::StringFrom (const State & observed_state, int player) const inline override virtual
Implements open_spiel::Observer.
Definition at line 300 of file dark_chess.cc.
{
    auto& state = open_spiel::down_cast<const DarkChessState&>(observed_state);
    auto& game = open_spiel::down_cast<const DarkChessGame&>(*state.GetGame());
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, game.NumPlayers());
    if (iig_obs_type_.perfect_recall) {
      SpielFatalError(
          "DarkChessObserver: string with perfect recall is not supported");
    }
    if (iig_obs_type_.public_info &&
        iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      chess::Color color = chess::PlayerToColor(player);
      chess::ObservationTable empty_public_info_table{};
      auto obs_table = ComputePrivateInfoTable(state.Board(), color,
                                               empty_public_info_table);
      return state.Board().ToDarkFEN(obs_table, color);
    } else {
      SpielFatalError(
          "DarkChessObserver: string with imperfect recall is implemented only"
          " for the (default) observation type.");
    }
  }
References open_spiel::down_cast(), open_spiel::kSinglePlayer, open_spiel::IIGObservationType::perfect_recall, player, open_spiel::chess::PlayerToColor(), open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and state.
WriteTensor()
void open_spiel::dark_chess::DarkChessObserver::WriteTensor (const State & observed_state, int player, Allocator * allocator) const inline override virtual
Implements open_spiel::Observer.
Definition at line 270 of file dark_chess.cc.
{
    auto& state = open_spiel::down_cast<const DarkChessState&>(observed_state);
    auto& game = open_spiel::down_cast<const DarkChessGame&>(*state.GetGame());
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, game.NumPlayers());
    if (iig_obs_type_.perfect_recall) {
      SpielFatalError(
          "DarkChessObserver: tensor with perfect recall not implemented.");
    }
    const auto public_info_table = ComputePublicInfoTable(state.Board());
    if (iig_obs_type_.public_info) {
      WritePublicInfoTensor(state, public_info_table, allocator);
    }
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      std::string prefix = "private";
      WritePrivateInfoTensor(state, public_info_table, player, prefix,
                             allocator);
    } else if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers) {
      for (int i = 0; i < chess::NumPlayers(); ++i) {
        chess::Color color = chess::PlayerToColor(player);
        std::string prefix = chess::ColorToString(color);
        WritePrivateInfoTensor(state, public_info_table, i, prefix, allocator);
      }
    }
  }
References open_spiel::chess::ColorToString(), open_spiel::down_cast(), i, open_spiel::kAllPlayers, open_spiel::kSinglePlayer, open_spiel::chess::NumPlayers(), open_spiel::IIGObservationType::perfect_recall, player, open_spiel::chess::PlayerToColor(), open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and state.
The documentation for this class was generated from the following file:
open_spiel/games/dark_chess/dark_chess.cc