open spiel: TransTableS Class Reference
TransTableS Class Reference
#include <TransTableS.h>
Public Member Functions
TransTableS ()
~TransTableS ()
void Init (const int handLookup[][15])
void SetMemoryDefault (const int megabytes)
void SetMemoryMaximum (const int megabytes)
void MakeTT ()
void ResetMemory (const TTresetReason reason)
void ReturnAllMemory ()
double MemoryInUse () const
nodeCardsType const * Lookup (const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[], const int limit, bool &lowerFlag)
void Add (const int trick, const int hand, const unsigned short aggrTarget[], const unsigned short winRanksArg[], const nodeCardsType &first, const bool flag)
void PrintNodeStats (ofstream &fout) const
void PrintResetStats (ofstream &fout) const
Public Member Functions inherited from TransTable
TransTable ()
virtual ~TransTable ()
virtual void PrintSuits (ofstream &fout, const int trick, const int hand) const
virtual void PrintAllSuits (ofstream &fout) const
virtual void PrintSuitStats (ofstream &fout, const int trick, const int hand) const
virtual void PrintAllSuitStats (ofstream &fout) const
virtual void PrintSummarySuitStats (ofstream &fout) const
virtual void PrintEntriesDist (ofstream &fout, const int trick, const int hand, const int handDist[]) const
virtual void PrintEntriesDistAndCards (ofstream &fout, const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[]) const
virtual void PrintEntries (ofstream &fout, const int trick, const int hand) const
virtual void PrintAllEntries (ofstream &fout) const
virtual void PrintEntryStats (ofstream &fout, const int trick, const int hand) const
virtual void PrintAllEntryStats (ofstream &fout) const
virtual void PrintSummaryEntryStats (ofstream &fout) const
virtual void PrintPageSummary (ofstream &fout) const
Detailed Description
Definition at line 28 of file TransTableS.h.
Constructor & Destructor Documentation
TransTableS()
TransTableS::TransTableS ()
Definition at line 27 of file TransTableS.cpp.
{
  if (! _constantsSet)
  {
    _constantsSet = true;
    TransTableS::SetConstants();
  }
  TTInUse = 0;
}
~TransTableS()
TransTableS::~TransTableS ()
Definition at line 39 of file TransTableS.cpp.
{
  TransTableS::ReturnAllMemory();
}
References ReturnAllMemory().
Member Function Documentation
Add()
void TransTableS::Add (const int trick, const int hand, const unsigned short aggrTarget[], const unsigned short winRanksArg[], const nodeCardsType & first, const bool flag) virtual
Reimplemented from TransTable.
Definition at line 409 of file TransTableS.cpp.
{
  BuildSOP(ourWinRanks, aggrTarget, first, suitLengths[tricks],
           tricks, hand, flag);
  if (clearTTflag)
    ResetMemory(TT_RESET_MEMORY_EXHAUSTED);
  return;
}
References first, ResetMemory(), and TT_RESET_MEMORY_EXHAUSTED.
Init()
void TransTableS::Init (const int handLookup[][15]) virtual
Reimplemented from TransTable.
Definition at line 61 of file TransTableS.cpp.
{
  unsigned int topBitRank = 1;
  unsigned int topBitNo = 2;
  for (int s = 0; s < DDS_SUITS; s++)
  {
    aggp[0].aggrRanks[s] = 0;
    aggp[0].winMask[s] = 0;
  }
  for (unsigned int ind = 1; ind < 8192; ind++)
  {
    if (ind >= (topBitRank + topBitRank))
    {
      /* Next top bit */
      topBitRank <<= 1;
      topBitNo++;
    }
    aggp[ind] = aggp[ind ^ topBitRank];
    for (int s = 0; s < 4; s++)
    {
      aggp[ind].aggrRanks[s] =
        (aggp[ind].aggrRanks[s] >> 2) |
        (handLookup[s][topBitNo] << 24);
      aggp[ind].winMask[s] =
        (aggp[ind].winMask[s] >> 2) | (3 << 24);
    }
  }
  resetText.resize(TT_RESET_SIZE);
  resetText[TT_RESET_UNKNOWN] = "Unknown reason";
  resetText[TT_RESET_TOO_MANY_NODES] = "Too many nodes";
  resetText[TT_RESET_NEW_DEAL] = "New deal";
  resetText[TT_RESET_NEW_TRUMP] = "New trump";
  resetText[TT_RESET_MEMORY_EXHAUSTED] = "Memory exhausted";
  resetText[TT_RESET_FREE_MEMORY] = "Free thread memory";
  return;
}
References DDS_SUITS, TT_RESET_FREE_MEMORY, TT_RESET_MEMORY_EXHAUSTED, TT_RESET_NEW_DEAL, TT_RESET_NEW_TRUMP, TT_RESET_SIZE, TT_RESET_TOO_MANY_NODES, and TT_RESET_UNKNOWN.
Lookup()
nodeCardsType const * TransTableS::Lookup (const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[], const int limit, bool & lowerFlag) virtual
Reimplemented from TransTable.
Definition at line 360 of file TransTableS.cpp.
{
  bool res;
  posSearchTypeSmall * pp;
  int orderSet[DDS_SUITS];
  nodeCardsType const * cardsP;
  suitLengths[trick] =
    (static_cast<long long>(handDist[0]) << 36) |
    (static_cast<long long>(handDist[1]) << 24) |
    (static_cast<long long>(handDist[2]) << 12) |
    (static_cast<long long>(handDist[3]));
  pp = SearchLenAndInsert(rootnp[trick][hand],
    suitLengths[trick], false, trick, hand, res);
  /* Find node that fits the suit lengths */
  if ((pp != NULL) && res)
  {
    for (int ss = 0; ss < DDS_SUITS; ss++)
    {
      orderSet[ss] =
        aggp[aggrTarget[ss]].aggrRanks[ss];
    }
    if (pp->posSearchPoint == NULL)
      cardsP = NULL;
    else
    {
      cardsP = FindSOP(orderSet, limit, pp->posSearchPoint, lowerFlag);
      if (cardsP == NULL)
        return cardsP;
    }
  }
  else
  {
    cardsP = NULL;
  }
  return cardsP;
}
References DDS_SUITS.
MakeTT()
void TransTableS::MakeTT () virtual
Reimplemented from TransTable.
Definition at line 117 of file TransTableS.cpp.
{
  int i;
  if (!TTInUse)
  {
    TTInUse = 1;
    summem = (WINIT + 1) * sizeof(winCardType) +
             (NINIT + 1) * sizeof(nodeCardsType) +
             (LSIZE + 1) * 52 * sizeof(posSearchTypeSmall);
    wmem = static_cast<int>((WSIZE + 1) * sizeof(winCardType));
    nmem = static_cast<int>((NSIZE + 1) * sizeof(nodeCardsType));
    maxIndex = static_cast<int>(
      (maxmem - summem) / ((WSIZE + 1) * sizeof(winCardType)));
    pw = static_cast<winCardType **>(calloc(static_cast<unsigned int>(maxIndex + 1), sizeof(winCardType *)));
    if (pw == NULL)
      exit(1);
    pn = static_cast<nodeCardsType **>(calloc(static_cast<unsigned int>(maxIndex + 1), sizeof(nodeCardsType *)));
    if (pn == NULL)
      exit(1);
    for (int k = 1; k <= 13; k++)
      for (int h = 0; h < DDS_HANDS; h++)
      {
        pl[k][h] = static_cast
                   <posSearchTypeSmall **>(calloc(static_cast<unsigned int>(maxIndex + 1),
                                             sizeof(posSearchTypeSmall *)));
        if (pl[k][h] == NULL)
          exit(1);
      }
    for (i = 0; i <= maxIndex; i++)
    {
      if (pw[i])
        free(pw[i]);
      pw[i] = NULL;
    }
    for (i = 0; i <= maxIndex; i++)
    {
      if (pn[i])
        free(pn[i]);
      pn[i] = NULL;
    }
    for (int k = 1; k <= 13; k++)
    {
      for (int h = 0; h < DDS_HANDS; h++)
      {
        for (i = 0; i <= maxIndex; i++)
        {
          if (pl[k][h][i])
            free(pl[k][h][i]);
          pl[k][h][i] = NULL;
        }
      }
    }
    pw[0] = static_cast<winCardType *>(calloc(WINIT + 1, sizeof(winCardType)));
    if (pw[0] == NULL)
      exit(1);
    pn[0] = static_cast<nodeCardsType *>(calloc(NINIT + 1, sizeof(nodeCardsType)));
    if (pn[0] == NULL)
      exit(1);
    for (int k = 1; k <= 13; k++)
      for (int h = 0; h < DDS_HANDS; h++)
      {
        pl[k][h][0] = static_cast<posSearchTypeSmall *>(calloc((LSIZE + 1),
                      sizeof(posSearchTypeSmall)));
        if (pl[k][h][0] == NULL)
          exit(1);
      }
    aggp = static_cast<ttAggrType *>(calloc(8192, sizeof(ttAggrType)));
    if (aggp == NULL)
      exit(1);
    InitTT();
    for (int k = 1; k <= 13; k++)
      aggrLenSets[k] = 0;
    statsResets.noOfResets = 0;
    for (int k = 0; k <= 5; k++)
      statsResets.aggrResets[k] = 0;
  }
  return;
}
References DDS_HANDS, i, LSIZE, NINIT, NSIZE, WINIT, and WSIZE.
MemoryInUse()
double TransTableS::MemoryInUse () const virtual
Reimplemented from TransTable.
Definition at line 352 of file TransTableS.cpp.
{
  int ttMem = static_cast<int>(allocmem);
  int aggrMem = 8192 * static_cast<int>(sizeof(ttAggrType));
  return (ttMem + aggrMem) / static_cast<double>(1024.);
}
PrintNodeStats()
void TransTableS::PrintNodeStats (ofstream & fout) const virtual
Reimplemented from TransTable.
Definition at line 919 of file TransTableS.cpp.
{
  fout << "Report of generated PosSearch nodes per trick level.\n";
  fout << "Trick level 13 is highest level with all 52 cards.\n";
  fout << string(51, '-') << "\n";
  fout << setw(5) << "Trick" <<
    setw(14) << right << "Created nodes" << "\n";
  for (int k = 13; k > 0; k--)
    fout << setw(5) << k << setw(14) << aggrLenSets[k-1] << "\n";
  fout << endl;
}
PrintResetStats()
void TransTableS::PrintResetStats (ofstream & fout) const virtual
Reimplemented from TransTable.
Definition at line 935 of file TransTableS.cpp.
{
  fout << "Total no. of resets: " << statsResets.noOfResets << "\n" << endl;
  fout << setw(18) << left << "Reason" <<
    setw(6) << right << "Count" << "\n";
  for (unsigned k = 0; k < TT_RESET_SIZE; k++)
    fout << setw(18) << left << resetText[k] <<
      setw(6) << right << statsResets.aggrResets[k] << "\n";
}
References TT_RESET_SIZE.
ResetMemory()
void TransTableS::ResetMemory (const TTresetReason reason) virtual
Reimplemented from TransTable.
Definition at line 279 of file TransTableS.cpp.
{
  Wipe();
  InitTT();
  for (int k = 1; k <= 13; k++)
  {
    for (int h = 0; h < DDS_HANDS; h++)
    {
      rootnp[k][h] = &(posSearch[k][h][0]);
      posSearch[k][h][0].suitLengths = 0;
      posSearch[k][h][0].posSearchPoint = NULL;
      posSearch[k][h][0].left = NULL;
      posSearch[k][h][0].right = NULL;
      lenSetInd[k][h] = 1;
    }
  }
#if defined(DDS_TT_STATS)
  statsResets.noOfResets++;
  statsResets.aggrResets[reason]++;
#else
  UNUSED(reason);
#endif
  return;
}
References DDS_HANDS, and UNUSED.
Referenced by Add().
ReturnAllMemory()
void TransTableS::ReturnAllMemory () virtual
Reimplemented from TransTable.
Definition at line 309 of file TransTableS.cpp.
{
  if (!TTInUse)
    return;
  TTInUse = 0;
  Wipe();
  if (pw[0])
    free(pw[0]);
  pw[0] = NULL;
  if (pn[0])
    free(pn[0]);
  pn[0] = NULL;
  for (int k = 1; k <= 13; k++)
  {
    for (int h = 0; h < DDS_HANDS; h++)
    {
      if (pl[k][h][0])
        free(pl[k][h][0]);
      pl[k][h][0] = NULL;
    }
  }
  if (pw)
    free(pw);
  pw = NULL;
  if (pn)
    free(pn);
  pn = NULL;
  if (aggp)
    free(aggp);
  aggp = NULL;
  return;
}
References DDS_HANDS.
Referenced by ~TransTableS().
SetMemoryDefault()
void TransTableS::SetMemoryDefault (const int megabytes) virtual
Reimplemented from TransTable.
Definition at line 105 of file TransTableS.cpp.
{
  UNUSED(megabytes);
}
References UNUSED.
SetMemoryMaximum()
void TransTableS::SetMemoryMaximum (const int megabytes) virtual
Reimplemented from TransTable.
Definition at line 111 of file TransTableS.cpp.
{
  maxmem = static_cast<unsigned long long>(1000000 * megabytes);
}
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/TransTableS.h
open_spiel/games/bridge/double_dummy_solver/src/TransTableS.cpp