open spiel: open_spiel::algorithms::DeterministicTabularPolicy Class Reference
open_spiel::algorithms::DeterministicTabularPolicy Class Reference
#include <deterministic_policy.h>
Public Member Functions
DeterministicTabularPolicy (const Game &game, Player player, const std::unordered_map< std::string, Action > policy)
DeterministicTabularPolicy (const Game &game, Player player)
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
Action GetAction (const std::string &info_state) const
TabularPolicy GetTabularPolicy () const
bool NextPolicy ()
void ResetDefaultPolicy ()
std::string ToString (const std::string &delimiter) const
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
virtual ActionsAndProbs GetStatePolicy (const State &state) const
virtual ActionsAndProbs GetStatePolicy (const State &state, Player player) const
virtual std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const
Detailed Description
Definition at line 68 of file deterministic_policy.h.
Constructor & Destructor Documentation
DeterministicTabularPolicy() [1/2]
open_spiel::algorithms::DeterministicTabularPolicy::DeterministicTabularPolicy (const Game & game, Player player, const std::unordered_map< std::string, Action > policy)
Definition at line 43 of file deterministic_policy.cc.
    : table_(), player_(player) {
  CreateTable(game, player);
  for (const auto& info_state_action : policy) {
    auto iter = table_.find(info_state_action.first);
    SPIEL_CHECK_TRUE(iter != table_.end());
    iter->second.SetAction(info_state_action.second);
  }
}
References player, and SPIEL_CHECK_TRUE.
DeterministicTabularPolicy() [2/2]
open_spiel::algorithms::DeterministicTabularPolicy::DeterministicTabularPolicy (const Game & game, Player player)
Definition at line 55 of file deterministic_policy.cc.
    : table_(), player_(player) {
  CreateTable(game, player);
}
References player.
Member Function Documentation
GetAction()
Action open_spiel::algorithms::DeterministicTabularPolicy::GetAction (const std::string & info_state) const
Definition at line 73 of file deterministic_policy.cc.
{
  auto iter = table_.find(info_state);
  SPIEL_CHECK_TRUE(iter != table_.end());
  return iter->second.GetAction();
}
References SPIEL_CHECK_TRUE.
GetStatePolicy()
ActionsAndProbs open_spiel::algorithms::DeterministicTabularPolicy::GetStatePolicy (const std::string & info_state) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 61 of file deterministic_policy.cc.
{
  auto iter = table_.find(info_state);
  SPIEL_CHECK_TRUE(iter != table_.end());
  ActionsAndProbs state_policy;
  Action policy_action = iter->second.GetAction();
  for (const auto& action : iter->second.legal_actions_) {
    state_policy.push_back({action, action == policy_action ? 1.0 : 0.0});
  }
  return state_policy;
}
References action, and SPIEL_CHECK_TRUE.
GetTabularPolicy()
TabularPolicy open_spiel::algorithms::DeterministicTabularPolicy::GetTabularPolicy () const
Definition at line 80 of file deterministic_policy.cc.
{
  TabularPolicy tabular_policy;
  for (const auto& infostate_and_legals : table_) {
    ActionsAndProbs state_policy;
    Action policy_action = infostate_and_legals.second.GetAction();
    for (const auto& action : infostate_and_legals.second.legal_actions_) {
      state_policy.push_back({action, action == policy_action ? 1.0 : 0.0});
    }
    tabular_policy.SetStatePolicy(infostate_and_legals.first, state_policy);
  }
  return tabular_policy;
}
References action, and open_spiel::TabularPolicy::SetStatePolicy().
NextPolicy()
bool open_spiel::algorithms::DeterministicTabularPolicy::NextPolicy ()
Definition at line 93 of file deterministic_policy.cc.
{
  // Treat the current indices as digits in a mixed base. Starting at the
  // beginning of the table, add 1. If can't, continue trying. If we reach the
  // end without being able to add 1, then this is the end of the order.
  // Otherwise, increment the digit we land on by 1, and reset all the ones
  // we skipped over earlier in the order.
  for (auto iter = table_.begin(); iter != table_.end(); ++iter) {
    if (iter->second.TryIncIndex()) {
      for (auto iter2 = table_.begin(); iter2 != iter; ++iter2) {
        iter2->second.index = 0;
      }
      return true;
    }
  }
  return false;
}
ResetDefaultPolicy()
void open_spiel::algorithms::DeterministicTabularPolicy::ResetDefaultPolicy ()
Definition at line 110 of file deterministic_policy.cc.
{
  for (auto& info_state_entry : table_) {
    info_state_entry.second.index = 0;
  }
}
Referenced by open_spiel::algorithms::ExtensiveToMatrixGame().
ToString()
std::string open_spiel::algorithms::DeterministicTabularPolicy::ToString (const std::string & delimiter) const
Definition at line 125 of file deterministic_policy.cc.
{
  std::string str = "";
  for (const auto& info_state_entry : table_) {
    absl::StrAppend(&str, info_state_entry.first, " ", delimiter, " ",
                    "action = ", info_state_entry.second.GetAction(), "\n");
  }
  return str;
}
References absl::StrAppend().
The documentation for this class was generated from the following files:
open_spiel/algorithms/deterministic_policy.h
open_spiel/algorithms/deterministic_policy.cc