open spiel: open_spiel::algorithms::torch_az::DeviceManager Class Reference
open_spiel::algorithms::torch_az::DeviceManager Class Reference
#include <device_manager.h>
Classes
class DeviceLoan
Public Member Functions
DeviceManager ()
void AddDevice (VPNetModel model)
DeviceLoan Get (int requests, int device_id=-1)
void SetLearning (bool value)
int Count () const
Detailed Description
Definition at line 31 of file device_manager.h.
Constructor & Destructor Documentation
DeviceManager()
open_spiel::algorithms::torch_az::DeviceManager::DeviceManager () inline
Definition at line 33 of file device_manager.h.
                  {
    learning_ = false;
    multiple_devices_ = false;
  }
Member Function Documentation
AddDevice()
void open_spiel::algorithms::torch_az::DeviceManager::AddDevice (VPNetModel model) inline
Definition at line 38 of file device_manager.h.
                                   {  // Not thread safe.
    devices.emplace_back(Device{std::move(model)});
    multiple_devices_ = devices.size() > 1;
  }
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), and main().
Count()
int open_spiel::algorithms::torch_az::DeviceManager::Count () const inline
Definition at line 93 of file device_manager.h.
{ return devices.size(); }
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), and open_spiel::algorithms::torch_az::learner().
Get()
DeviceLoan open_spiel::algorithms::torch_az::DeviceManager::Get (int requests, int device_id = -1) inline
Definition at line 70 of file device_manager.h.
{
    absl::MutexLock lock(&m_);
    if (device_id < 0) {
      // The starting device changes depending on if we are allowed to
      // use the first device or not.
      device_id = 0 + (learning_ && multiple_devices_);
      for (int i = 1 + (learning_ && multiple_devices_); i < devices.size();
           ++i) {
        if (devices[i].requests < devices[device_id].requests) {
          device_id = i;
        }
      }
    }
    devices[device_id].requests += requests;
    return DeviceLoan(this, &devices[device_id].model, device_id, requests);
  }
References i.
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), open_spiel::algorithms::torch_az::learner(), and main().
SetLearning()
void open_spiel::algorithms::torch_az::DeviceManager::SetLearning (bool value) inline
Definition at line 91 of file device_manager.h.
{ learning_ = value; }
References value.
Referenced by open_spiel::algorithms::torch_az::learner().
The documentation for this class was generated from the following file:
open_spiel/algorithms/alpha_zero_torch/device_manager.h