open spiel: Scheduler Class Reference
Scheduler Class Reference
#include <Scheduler.h>
Public Member Functions
Scheduler ()
~Scheduler ()
void RegisterThreads (const int n)
void RegisterRun (const enum RunMode mode, const boards &bds, const playTracesBin &pl)
void RegisterRun (const enum RunMode mode, const boards &bds)
schedType GetNumber (const int thrId)
int NumGroups () const
Detailed Description
Definition at line 43 of file Scheduler.h.
Constructor & Destructor Documentation
Scheduler()
Scheduler::Scheduler ()
Definition at line 19 of file Scheduler.cpp.
{
  numThreads = 0;
  numHands = 0;
  Scheduler::InitHighCards();
#ifdef DDS_SCHEDULER
  Scheduler::InitTimes();
  for (int i = 0; i < 10000; i++)
  {
    timeHist[i] = 0;
    timeHistNT[i] = 0;
    timeHistSuit[i] = 0;
  }
#endif
  Scheduler::RegisterThreads(1);
}
References i, and RegisterThreads().
~Scheduler()
Scheduler::~Scheduler ()
Definition at line 88 of file Scheduler.cpp.
{
}
Member Function Documentation
GetNumber()
schedType Scheduler::GetNumber (const int thrId)
Definition at line 721 of file Scheduler.cpp.
{
  const unsigned tu = static_cast<unsigned>(thrId);
  int g = threadGroup[tu];
  listType * lp;
  schedType st;
  if (g == -1)
  {
    // Find a new group
    if (currGroup >= numGroups - 1)
    {
      // Out of groups. Just an optimization not to touch the
      // shared variable unnecessarily.
      st.number = -1;
      return st;
    }
    // Atomic.
    g = ++currGroup;
    if (g >= numGroups)
    {
      // Out of groups. currGroup could have changed in the
      // meantime in another thread, so test again.
      st.number = -1;
      return st;
    }
    // A bit inelegant to duplicate this, but seems better than
    // the alternative, as threadGroup must get set to -1 in some
    // cases.
    threadGroup[tu] = g;
    threadCurrGroup[tu] = g;
    group[g].repeatNo = 0;
    group[g].actual = 0;
  }
  // Continue with existing or new group
  int strain = group[g].strain;
  int key = group[g].hash;
  lp = &list[strain][key];
  st.number = lp->first;
  lp->first = hands[lp->first].next;
  if (group[g].repeatNo == 0)
  {
    group[g].head = st.number;
    st.repeatOf = -1;
    // Only first-solve suited hands for statistics right now.
    hands[st.number].selectFlag =
      (hands[st.number].strain == 4 ? 1 : 0);
  }
  else
  {
    st.repeatOf = group[g].head;
    //hands[st.number].selectFlag = 0;
    if (hands[st.number].first == hands[st.repeatOf].first)
      hands[st.number].selectFlag = 0;
    else if (hands[st.number].strain == 4)
      hands[st.number].selectFlag = 1;
    else
      hands[st.number].selectFlag = 0;
  }
  hands[st.number].repeatNo = group[g].repeatNo++;
  threadToHand[tu] = st.number;
  if (lp->first == -1)
    threadGroup[tu] = -1;
  return st;
}
References key, schedType::number, and schedType::repeatOf.
Referenced by CalcChunkCommon(), PlayChunkCommon(), and SolveChunkCommon().
NumGroups()
int Scheduler::NumGroups () const
Definition at line 803 of file Scheduler.cpp.
{
  return numGroups;
}
RegisterRun() [1/2]
void Scheduler::RegisterRun (const enum RunMode mode, const boards & bds)
Definition at line 147 of file Scheduler.cpp.
{
  Scheduler::Reset();
  numHands = bds.noOfBoards;
  // First split the hands according to strain and hash key.
  // This will lead to a few random collisions as well.
  Scheduler::MakeGroups(bds);
  // Then check whether groups with at least two elements are
  // homogeneous or whether they need to be split.
  Scheduler::FinetuneGroups();
  Scheduler::SortHands(mode);
}
References boards::noOfBoards.
RegisterRun() [2/2]
void Scheduler::RegisterRun (const enum RunMode mode, const boards & bds, const playTracesBin & pl)
Definition at line 135 of file Scheduler.cpp.
{
  for (int b = 0; b < bds.noOfBoards; b++)
    hands[b].depth = pl.plays[b].number;
  Scheduler::RegisterRun(mode, bds);
}
References b, boards::noOfBoards, playTraceBin::number, playTracesBin::plays, and RegisterRun().
Referenced by AnalyseAllPlaysBin(), CalcAllBoardsN(), RegisterRun(), and SolveAllBoardsN().
RegisterThreads()
void Scheduler::RegisterThreads (const int n)
Definition at line 116 of file Scheduler.cpp.
{
  if (n == numThreads)
    return;
  numThreads = n;
  const unsigned nu = static_cast<unsigned>(n);
  threadGroup.resize(nu);
  threadCurrGroup.resize(nu);
  threadToHand.resize(nu);
#ifdef DDS_SCHEDULER
  timeThread.Init("Threads", numThreads);
  timersThread.resize(numThreads);
#endif
}
References n.
Referenced by Scheduler(), and SetResources().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/Scheduler.h
open_spiel/games/bridge/double_dummy_solver/src/Scheduler.cpp