open spiel: absl::random_internal::Randen Class Reference
absl::random_internal::Randen Class Reference
#include <randen.h>
Public Member Functions
~Randen ()=default
Randen ()
void Generate (void *state) const
void Absorb (const void *seed, void *state) const
Static Public Attributes
static constexpr size_t kStateBytes = RandenTraits::kStateBytes
static constexpr size_t kCapacityBytes = RandenTraits::kCapacityBytes
static constexpr size_t kSeedBytes = RandenTraits::kSeedBytes
Detailed Description
Definition at line 34 of file randen.h.
Constructor & Destructor Documentation
~Randen()
absl::random_internal::Randen::~Randen () default
Randen()
absl::random_internal::Randen::Randen ()
Definition at line 81 of file randen.cc.
               {
  auto tmp = GetRandenState();
  keys_ = tmp.keys;
#if ABSL_RANDOM_INTERNAL_AES_DISPATCH
  has_crypto_ = tmp.has_crypto;
#endif
}
Member Function Documentation
Absorb()
void absl::random_internal::Randen::Absorb (const void * seed, void * state) const inline
Definition at line 68 of file randen.h.
{
#if ABSL_RANDOM_INTERNAL_AES_DISPATCH
    // HW AES Dispatch.
    if (has_crypto_) {
      RandenHwAes::Absorb(seed, state);
    } else {
      RandenSlow::Absorb(seed, state);
    }
#elif ABSL_HAVE_ACCELERATED_AES
    // HW AES is enabled.
    RandenHwAes::Absorb(seed, state);
#else
    // HW AES is disabled.
    RandenSlow::Absorb(seed, state);
#endif
  }
References absl::random_internal::RandenHwAes::Absorb(), absl::random_internal::RandenSlow::Absorb(), and state.
Referenced by absl::random_internal::randen_engine< T >::reseed().
Generate()
void absl::random_internal::Randen::Generate (void * state) const inline
Definition at line 47 of file randen.h.
{
#if ABSL_RANDOM_INTERNAL_AES_DISPATCH
    // HW AES Dispatch.
    if (has_crypto_) {
      RandenHwAes::Generate(keys_, state);
    } else {
      RandenSlow::Generate(keys_, state);
    }
#elif ABSL_HAVE_ACCELERATED_AES
    // HW AES is enabled.
    RandenHwAes::Generate(keys_, state);
#else
    // HW AES is disabled.
    RandenSlow::Generate(keys_, state);
#endif
  }
References absl::random_internal::RandenHwAes::Generate(), absl::random_internal::RandenSlow::Generate(), and state.
Referenced by absl::random_internal::randen_engine< T >::discard(), and absl::random_internal::randen_engine< T >::operator()().
Member Data Documentation
kCapacityBytes
size_t absl::random_internal::Randen::kCapacityBytes = RandenTraits::kCapacityBytes static constexpr
Definition at line 37 of file randen.h.
kSeedBytes
size_t absl::random_internal::Randen::kSeedBytes = RandenTraits::kSeedBytes static constexpr
Definition at line 38 of file randen.h.
Referenced by absl::random_internal::randen_engine< T >::reseed().
kStateBytes
size_t absl::random_internal::Randen::kStateBytes = RandenTraits::kStateBytes static constexpr
Definition at line 36 of file randen.h.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/random/internal/randen.h
open_spiel/abseil-cpp/absl/random/internal/randen.cc