open spiel: absl::cord_internal::CordzHandle Class Reference
absl::cord_internal::CordzHandle Class Reference
#include <cordz_handle.h>
Public Member Functions
CordzHandle ()
bool is_snapshot () const
bool SafeToDelete () const
bool DiagnosticsHandleIsSafeToInspect (const CordzHandle *handle) const
std::vector< const CordzHandle * > DiagnosticsGetSafeToInspectDeletedHandles ()
Static Public Member Functions
static void Delete (CordzHandle *handle)
static std::vector< const CordzHandle * > DiagnosticsGetDeleteQueue ()
Protected Member Functions
CordzHandle (bool is_snapshot)
virtual ~CordzHandle ()
Detailed Description
Definition at line 37 of file cordz_handle.h.
Constructor & Destructor Documentation
CordzHandle() [1/2]
absl::cord_internal::CordzHandle::CordzHandle () inline
Definition at line 39 of file cordz_handle.h.
: CordzHandle(false) {}
CordzHandle() [2/2]
absl::cord_internal::CordzHandle::CordzHandle (bool is_snapshot) explicit protected
Definition at line 29 of file cordz_handle.cc.
                                         : is_snapshot_(is_snapshot) {
  if (is_snapshot) {
    SpinLockHolder lock(&queue_->mutex);
    CordzHandle* dq_tail = queue_->dq_tail.load(std::memory_order_acquire);
    if (dq_tail != nullptr) {
      dq_prev_ = dq_tail;
      dq_tail->dq_next_ = this;
    }
    queue_->dq_tail.store(this, std::memory_order_release);
  }
}
References is_snapshot().
~CordzHandle()
absl::cord_internal::CordzHandle::~CordzHandle () protected virtual
Definition at line 41 of file cordz_handle.cc.
{
  ODRCheck();
  if (is_snapshot_) {
    std::vector<CordzHandle*> to_delete;
    {
      SpinLockHolder lock(&queue_->mutex);
      CordzHandle* next = dq_next_;
      if (dq_prev_ == nullptr) {
        // We were head of the queue, delete every CordzHandle until we reach
        // either the end of the list, or a snapshot handle.
        while (next && !next->is_snapshot_) {
          to_delete.push_back(next);
          next = next->dq_next_;
        }
      } else {
        // Another CordzHandle existed before this one, don't delete anything.
        dq_prev_->dq_next_ = next;
      }
      if (next) {
        next->dq_prev_ = dq_prev_;
      } else {
        queue_->dq_tail.store(dq_prev_, std::memory_order_release);
      }
    }
    for (CordzHandle* handle : to_delete) {
      delete handle;
    }
  }
}
References next.
Member Function Documentation
Delete()
void absl::cord_internal::CordzHandle::Delete (CordzHandle * handle) static
Definition at line 75 of file cordz_handle.cc.
{
  assert(handle);
  if (handle) {
    handle->ODRCheck();
    Queue* const queue = handle->queue_;
    if (!handle->SafeToDelete()) {
      SpinLockHolder lock(&queue->mutex);
      CordzHandle* dq_tail = queue->dq_tail.load(std::memory_order_acquire);
      if (dq_tail != nullptr) {
        handle->dq_prev_ = dq_tail;
        dq_tail->dq_next_ = handle;
        queue->dq_tail.store(handle, std::memory_order_release);
        return;
      }
    }
    delete handle;
  }
}
References SafeToDelete().
Referenced by absl::cord_internal::CordzInfo::Untrack().
DiagnosticsGetDeleteQueue()
std::vector< const CordzHandle * > absl::cord_internal::CordzHandle::DiagnosticsGetDeleteQueue () static
Definition at line 94 of file cordz_handle.cc.
{
  std::vector<const CordzHandle*> handles;
  SpinLockHolder lock(&global_queue_.mutex);
  CordzHandle* dq_tail = global_queue_.dq_tail.load(std::memory_order_acquire);
  for (const CordzHandle* p = dq_tail; p; p = p->dq_prev_) {
    handles.push_back(p);
  }
  return handles;
}
References absl::p.
DiagnosticsGetSafeToInspectDeletedHandles()
std::vector< const CordzHandle * > absl::cord_internal::CordzHandle::DiagnosticsGetSafeToInspectDeletedHandles ()
Definition at line 121 of file cordz_handle.cc.
{
  ODRCheck();
  std::vector<const CordzHandle*> handles;
  if (!is_snapshot()) {
    return handles;
  }
  SpinLockHolder lock(&queue_->mutex);
  for (const CordzHandle* p = dq_next_; p != nullptr; p = p->dq_next_) {
    if (!p->is_snapshot()) {
      handles.push_back(p);
    }
  }
  return handles;
}
References is_snapshot(), and absl::p.
DiagnosticsHandleIsSafeToInspect()
bool absl::cord_internal::CordzHandle::DiagnosticsHandleIsSafeToInspect (const CordzHandle * handle) const
Definition at line 104 of file cordz_handle.cc.
{
  ODRCheck();
  if (!is_snapshot_) return false;
  if (handle == nullptr) return true;
  if (handle->is_snapshot_) return false;
  bool snapshot_found = false;
  SpinLockHolder lock(&queue_->mutex);
  for (const CordzHandle* p = queue_->dq_tail; p; p = p->dq_prev_) {
    if (p == handle) return !snapshot_found;
    if (p == this) snapshot_found = true;
  }
  ABSL_ASSERT(snapshot_found);  // Assert that 'this' is in delete queue.
  return true;
}
References ABSL_ASSERT, and absl::p.
Referenced by absl::cord_internal::CordzInfo::Head(), and absl::cord_internal::CordzInfo::Next().
is_snapshot()
bool absl::cord_internal::CordzHandle::is_snapshot () const inline
Definition at line 41 of file cordz_handle.h.
{ return is_snapshot_; }
Referenced by CordzHandle(), DiagnosticsGetSafeToInspectDeletedHandles(), absl::cord_internal::CordzInfo::Head(), and absl::cord_internal::CordzInfo::Next().
SafeToDelete()
bool absl::cord_internal::CordzHandle::SafeToDelete () const
Definition at line 71 of file cordz_handle.cc.
{
  return is_snapshot_ || queue_->IsEmpty();
}
Referenced by Delete(), and absl::cord_internal::CordzInfo::Untrack().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/cordz_handle.h
open_spiel/abseil-cpp/absl/strings/internal/cordz_handle.cc