open spiel: cfr_test.CfrTest Class Reference
cfr_test.CfrTest Class Reference
Public Member Functions
test_zero_policy_is_uniform (self, game)
test_cfr_leduc_poker (self)
test_cfr_kuhn_poker (self)
Detailed Description
Definition at line 31 of file cfr_test.py.
Member Function Documentation
test_cfr_kuhn_poker()
cfr_test.CfrTest.test_cfr_kuhn_poker (self)
Definition at line 69 of file cfr_test.py.
  def test_cfr_kuhn_poker(self):
    config = {'players': 2}
    exploitability_error = 0.2
    cfr_game_tree = trees.build_game_tree(
        openspiel_api.WorldState(
            game_name='kuhn_poker', config=config, perturbation=False))
    best_response_value_p1, best_response_value_p2 = cfr.compute_cfr_values(
        cfr_game_tree, 20)
    last_best_response_value_player_1 = best_response_value_p1[-1]
    last_best_response_value_player_2 = best_response_value_p2[-1]
    exploitability = (last_best_response_value_player_1 +
                      last_best_response_value_player_2) / 2
    # Exploitability values are computed using OpenSpiel cfr
    self.assertLessEqual(exploitability, 0.06 + exploitability_error)
References cfr.compute_cfr_values().
test_cfr_leduc_poker()
cfr_test.CfrTest.test_cfr_leduc_poker (self)
Definition at line 54 of file cfr_test.py.
  def test_cfr_leduc_poker(self):
    config = {'players': 2}
    exploitability_error = 0.2
    cfr_game_tree = trees.build_game_tree(
        openspiel_api.WorldState(
            game_name='leduc_poker', config=config, perturbation=False))
    best_response_value_p1, best_response_value_p2 = cfr.compute_cfr_values(
        cfr_game_tree, 20)
    last_best_response_value_player_1 = best_response_value_p1[-1]
    last_best_response_value_player_2 = best_response_value_p2[-1]
    exploitability = (last_best_response_value_player_1 +
                      last_best_response_value_player_2) / 2
    # Exploitability values are computed using OpenSpiel cfr
    self.assertLessEqual(exploitability, 0.59 + exploitability_error)
References cfr.compute_cfr_values().
test_zero_policy_is_uniform()
cfr_test.CfrTest.test_zero_policy_is_uniform (self, game)
Definition at line 35 of file cfr_test.py.
  def test_zero_policy_is_uniform(self, game):
    config = {'players': 2}
    cfr_game_tree = trees.build_game_tree(
        openspiel_api.WorldState(
            game_name=game, config=config, perturbation=False))
    cfr.compute_cfr_values(cfr_game_tree, 1)
    infostates_p1 = list(cfr_game_tree.all_infostates_map[1].values())
    infostates_p2 = list(cfr_game_tree.all_infostates_map[2].values())
    with self.subTest('player_1_initial_policy'):
      for i in range(len(infostates_p1)):
        self.assertListEqual(
            list(infostates_p1[i].policy.values()),
            _uniform_policy(len(infostates_p1[i].policy.values())))
    with self.subTest('player_2_initial_policy'):
      for i in range(len(infostates_p2)):
        self.assertListEqual(
            list(infostates_p2[i].policy.values()),
            _uniform_policy(len(infostates_p2[i].policy.values())))
References cfr_test._uniform_policy(), cfr.compute_cfr_values(), and len.
The documentation for this class was generated from the following file:
open_spiel/python/examples/meta_cfr/sequential_games/cfr_test.py