open spiel: open_spiel::algorithms::EFCETabularPolicy Class Reference
open_spiel::algorithms::EFCETabularPolicy Class Reference
#include <efce.h>
Public Member Functions
EFCETabularPolicy (const CorrDistConfig &config)
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
ActionsAndProbs GetStatePolicy (const State &state, Player pl) const override
ActionsAndProbs GetStatePolicy (const State &state) const override
Public Member Functions inherited from open_spiel::TabularPolicy
TabularPolicy ()=default
TabularPolicy (const Game &game)
TabularPolicy (const TabularPolicy &other)=default
TabularPolicy (const std::unordered_map< std::string, ActionsAndProbs > &table)
TabularPolicy (const Game &game, const Policy &policy)
TabularPolicy (const TabularPolicy &dummy_policy, const std::unordered_map< std::string, Action > &action_map)
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const override
void ImportPolicy (const TabularPolicy &other_policy)
void SetProb (const std::string &info_state, Action action, double prob)
void SetStatePolicy (const std::string &info_state, const ActionsAndProbs &state_policy)
std::unordered_map< std::string, ActionsAndProbs > & PolicyTable ()
const std::unordered_map< std::string, ActionsAndProbs > & PolicyTable () const
int size () const
std::string ToString () const
std::string ToStringSorted () const
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
Additional Inherited Members
Protected Attributes inherited from open_spiel::TabularPolicy
std::unordered_map< std::string, ActionsAndProbs > policy_table_
Detailed Description
Definition at line 113 of file efce.h.
Constructor & Destructor Documentation
EFCETabularPolicy()
open_spiel::algorithms::EFCETabularPolicy::EFCETabularPolicy (const CorrDistConfig & config) inline
Definition at line 115 of file efce.h.
: config_(config) {}
Member Function Documentation
GetStatePolicy() [1/3]
ActionsAndProbs open_spiel::algorithms::EFCETabularPolicy::GetStatePolicy (const State & state) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 139 of file efce.cc.
{
  // The best response code has to have a policy defined everywhere when it
  // builds its initial tree. For the fixed policies, the players will not
  // defect, so we define a uniform policy in the regions where players have
  // defected (which will not affect the best responding player, since the
  // opponents will never reach these regions).
  const auto* efce_state = dynamic_cast<const EFCEState*>(&state);
  SPIEL_CHECK_TRUE(efce_state != nullptr);
  if (efce_state->HasDefected(state.CurrentPlayer())) {
    return UniformStatePolicy(state);
  }
  // Otherwise, simply returns a fixed policy with prob 1 on the recommended
  // action (extrapolated from the information state string) and 0 on the
  // others.
  std::string info_state = state.InformationStateString();
  const size_t idx = info_state.find(config_.recommendation_delimiter);
  SPIEL_CHECK_NE(idx, std::string::npos);
  std::vector<std::string> rec_seq = absl::StrSplit(
      info_state.substr(idx + config_.recommendation_delimiter.length()), ',');
  SPIEL_CHECK_GE(rec_seq.size(), 1);
  Action rec_action;
  ActionsAndProbs state_policy;
  std::vector<Action> legal_actions = state.LegalActions();
  state_policy.reserve(legal_actions.size());
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(rec_seq.back(), &rec_action));
  for (Action action : legal_actions) {
    state_policy.push_back({action, action == rec_action ? 1.0 : 0.0});
  }
  return state_policy;
}
References action, open_spiel::algorithms::CorrDistConfig::recommendation_delimiter, absl::SimpleAtoi(), SPIEL_CHECK_GE, SPIEL_CHECK_NE, SPIEL_CHECK_TRUE, state, absl::StrSplit(), and open_spiel::UniformStatePolicy().
GetStatePolicy() [2/3]
ActionsAndProbs open_spiel::algorithms::EFCETabularPolicy::GetStatePolicy (const State & state, Player pl) const inline override virtual
Reimplemented from open_spiel::Policy.
Definition at line 121 of file efce.h.
{
    SPIEL_CHECK_EQ(state.CurrentPlayer(), pl);
    return GetStatePolicy(state);
  }
References GetStatePolicy(), SPIEL_CHECK_EQ, and state.
GetStatePolicy() [3/3]
ActionsAndProbs open_spiel::algorithms::EFCETabularPolicy::GetStatePolicy (const std::string & info_state) const inline override virtual
Reimplemented from open_spiel::Policy.
Definition at line 117 of file efce.h.
{
    SpielFatalError("GetStatePolicy(const std::string&) should not be called.");
    return TabularPolicy::GetStatePolicy(info_state);
  }
References open_spiel::TabularPolicy::GetStatePolicy(), and open_spiel::SpielFatalError().
Referenced by GetStatePolicy().
The documentation for this class was generated from the following files:
open_spiel/algorithms/corr_dist/efce.h
open_spiel/algorithms/corr_dist/efce.cc