open spiel: absl::beta_distribution< RealType >::param_type Class Reference
absl::beta_distribution< RealType >::param_type Class Reference
#include <beta_distribution.h>
Public Types
using distribution_type = beta_distribution
Public Member Functions
param_type (result_type alpha, result_type beta)
result_type alpha () const
result_type beta () const
Friends
class beta_distribution
bool operator== (const param_type &a, const param_type &b)
bool operator!= (const param_type &a, const param_type &b)
Detailed Description
template<typename RealType = double>
class absl::beta_distribution< RealType >::param_type
Definition at line 53 of file beta_distribution.h.
Member Typedef Documentation
distribution_type
template<typename RealType = double> using absl::beta_distribution< RealType >::param_type::distribution_type = beta_distribution
Definition at line 55 of file beta_distribution.h.
Constructor & Destructor Documentation
param_type()
template<typename RealType = double> absl::beta_distribution< RealType >::param_type::param_type (result_type alpha, result_type beta) inline explicit
Definition at line 57 of file beta_distribution.h.
        : alpha_(alpha), beta_(beta) {
      assert(alpha >= 0);
      assert(beta >= 0);
      assert(alpha <= (std::numeric_limits<result_type>::max)());
      assert(beta <= (std::numeric_limits<result_type>::max)());
      if (alpha == 0 || beta == 0) {
        method_ = DEGENERATE_SMALL;
        x_ = (alpha >= beta) ? 1 : 0;
        return;
      }
      // a_ = min(beta, alpha), b_ = max(beta, alpha).
      if (beta < alpha) {
        inverted_ = true;
        a_ = beta;
        b_ = alpha;
      } else {
        inverted_ = false;
        a_ = alpha;
        b_ = beta;
      }
      if (a_ <= 1 && b_ >= ThresholdForLargeA()) {
        method_ = DEGENERATE_SMALL;
        x_ = inverted_ ? result_type(1) : result_type(0);
        return;
      }
      // For threshold values, see also:
      // Evaluation of Beta Generation Algorithms, Ying-Chao Hung, et. al.
      // February, 2009.
      if ((b_ < 1.0 && a_ + b_ <= 1.2) || a_ <= ThresholdForSmallA()) {
        // Choose Joehnk over Cheng when it's faster or when Cheng encounters
        // numerical issues.
        method_ = JOEHNK;
        a_ = result_type(1) / alpha_;
        b_ = result_type(1) / beta_;
        if (std::isinf(a_) || std::isinf(b_)) {
          method_ = DEGENERATE_SMALL;
          x_ = inverted_ ? result_type(1) : result_type(0);
        }
        return;
      }
      if (a_ >= ThresholdForLargeA()) {
        method_ = DEGENERATE_LARGE;
        // Note: on PPC for long double, evaluating
        // `std::numeric_limits::max() / ThresholdForLargeA` results in NaN.
        result_type r = a_ / b_;
        x_ = (inverted_ ? result_type(1) : r) / (1 + r);
        return;
      }
      x_ = a_ + b_;
      log_x_ = std::log(x_);
      if (a_ <= 1) {
        method_ = CHENG_BA;
        y_ = result_type(1) / a_;
        gamma_ = a_ + a_;
        return;
      }
      method_ = CHENG_BB;
      result_type r = (a_ - 1) / (b_ - 1);
      y_ = std::sqrt((1 + r) / (b_ * r * 2 - r + 1));
      gamma_ = a_ + result_type(1) / y_;
    }
References absl::beta_distribution< RealType >::param_type::alpha(), absl::beta_distribution< RealType >::param_type::beta(), and r.
Member Function Documentation
alpha()
template<typename RealType = double> result_type absl::beta_distribution< RealType >::param_type::alpha () const inline
Definition at line 120 of file beta_distribution.h.
{ return alpha_; }
Referenced by absl::beta_distribution< RealType >::alpha(), open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::get_gap(), absl::beta_distribution< RealType >::param_type::param_type(), and open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::update_sequences().
beta()
template<typename RealType = double> result_type absl::beta_distribution< RealType >::param_type::beta () const inline
Definition at line 121 of file beta_distribution.h.
{ return beta_; }
Referenced by absl::beta_distribution< RealType >::beta(), and absl::beta_distribution< RealType >::param_type::param_type().
Friends And Related Symbol Documentation
beta_distribution
template<typename RealType = double> friend class beta_distribution friend
Definition at line 132 of file beta_distribution.h.
operator!=
template<typename RealType = double> bool operator!= (const param_type & a, const param_type & b) friend
Definition at line 127 of file beta_distribution.h.
{
      return !(a == b);
    }
operator==
template<typename RealType = double> bool operator== (const param_type & a, const param_type & b) friend
Definition at line 123 of file beta_distribution.h.
{
      return a.alpha_ == b.alpha_ && a.beta_ == b.beta_;
    }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/beta_distribution.h