open spiel: open_spiel::oh_hell::DeckProperties Class Reference
open_spiel::oh_hell::DeckProperties Class Reference
#include <oh_hell.h>
Public Member Functions
DeckProperties ()
DeckProperties (int num_suits, int num_cards_per_suit)
int NumSuits () const
int NumCardsPerSuit () const
int NumCards () const
Suit CardSuit (int card) const
int CardRank (int card) const
int Card (Suit suit, int rank) const
std::string CardString (int card) const
Detailed Description
Definition at line 82 of file oh_hell.h.
Constructor & Destructor Documentation
DeckProperties() [1/2]
open_spiel::oh_hell::DeckProperties::DeckProperties () inline
Definition at line 84 of file oh_hell.h.
: DeckProperties(0, 0) {}
DeckProperties() [2/2]
open_spiel::oh_hell::DeckProperties::DeckProperties (int num_suits, int num_cards_per_suit) inline
Definition at line 85 of file oh_hell.h.
                                                        : num_suits_(num_suits),
      num_cards_per_suit_(num_cards_per_suit) {}
Member Function Documentation
Card()
int open_spiel::oh_hell::DeckProperties::Card (Suit suit, int rank) const inline
Definition at line 98 of file oh_hell.h.
{
    return rank * num_suits_ + static_cast<int>(suit);
  }
References rank.
CardRank()
int open_spiel::oh_hell::DeckProperties::CardRank (int card) const inline
Definition at line 94 of file oh_hell.h.
{
    if (num_suits_ <= 0) return kInvalidRank;
    return card / num_suits_;
  }
References open_spiel::oh_hell::kInvalidRank.
Referenced by CardString(), and open_spiel::oh_hell::Trick::Play().
CardString()
std::string open_spiel::oh_hell::DeckProperties::CardString (int card) const inline
Definition at line 101 of file oh_hell.h.
{
    return {kSuitChar[static_cast<int>(CardSuit(card))],
            kRankChar[CardRank(card)]};
  }
References CardRank(), CardSuit(), open_spiel::oh_hell::kRankChar, and open_spiel::oh_hell::kSuitChar.
Referenced by open_spiel::oh_hell::OhHellState::ActionToString().
CardSuit()
Suit open_spiel::oh_hell::DeckProperties::CardSuit (int card) const inline
Definition at line 90 of file oh_hell.h.
{
    if (num_suits_ <= 0) return Suit::kInvalidSuit;
    return Suit(card % num_suits_);
  }
References open_spiel::oh_hell::kInvalidSuit.
Referenced by CardString(), and open_spiel::oh_hell::Trick::Play().
NumCards()
int open_spiel::oh_hell::DeckProperties::NumCards () const inline
Definition at line 89 of file oh_hell.h.
{ return num_suits_ * num_cards_per_suit_; }
Referenced by open_spiel::oh_hell::OhHellState::ActionToString(), open_spiel::oh_hell::OhHellState::ChanceOutcomes(), open_spiel::oh_hell::OhHellState::DoApplyAction(), open_spiel::oh_hell::OhHellState::InformationStateTensor(), open_spiel::oh_hell::OhHellGame::InformationStateTensorShape(), open_spiel::oh_hell::OhHellGame::MaxChanceOutcomes(), open_spiel::oh_hell::OhHellGame::MaxNumTricks(), open_spiel::oh_hell::OhHellGame::NumDistinctActions(), open_spiel::oh_hell::OhHellGame::OhHellGame(), open_spiel::oh_hell::OhHellState::OhHellState(), and open_spiel::oh_hell::OhHellState::ResampleFromInfostate().
NumCardsPerSuit()
int open_spiel::oh_hell::DeckProperties::NumCardsPerSuit () const inline
Definition at line 88 of file oh_hell.h.
{ return num_cards_per_suit_; }
Referenced by open_spiel::oh_hell::OhHellGame::OhHellGame().
NumSuits()
int open_spiel::oh_hell::DeckProperties::NumSuits () const inline
Definition at line 87 of file oh_hell.h.
{ return num_suits_; }
Referenced by open_spiel::oh_hell::OhHellGame::OhHellGame().
The documentation for this class was generated from the following file:
open_spiel/games/oh_hell/oh_hell.h