open spiel: open_spiel::rbc::RbcState Class Reference
open_spiel::rbc::RbcState Class Reference
#include <rbc.h>
Public Member Functions
RbcState (std::shared_ptr< const Game > game, int board_size, const std::string &fen)
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
chess::ChessBoard & Board ()
const chess::ChessBoard & Board () const
int BoardSize () const
chess::ChessBoard & StartBoard ()
const chess::ChessBoard & StartBoard () const
std::vector< chess::Move > & MovesHistory ()
const std::vector< chess::Move > & MovesHistory () const
bool IsRepetitionDraw () const
const RbcGame * game () const
MovePhase phase () const
const std::array< int, 2 > & sense_location () const
bool move_captured () const
bool illegal_move_attempted () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Friends
class RbcObserver
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 135 of file rbc.h.
Constructor & Destructor Documentation
RbcState()
open_spiel::rbc::RbcState::RbcState (std::shared_ptr< const Game > game, int board_size, const std::string & fen)
Definition at line 343 of file rbc.cc.
    : State(game),
      start_board_(*chess::ChessBoard::BoardFromFEN(
          fen, board_size,
          /*king_in_check_allowed=*/true,
          /*allow_pass_move=*/true)),
      current_board_(start_board_),
      phase_(MovePhase::kSensing) {
  SPIEL_CHECK_TRUE(&current_board_);
  repetitions_[current_board_.HashValue()] = 1;
}
References open_spiel::chess::ChessBoard::HashValue(), and SPIEL_CHECK_TRUE.
Member Function Documentation
ActionToString()
std::string open_spiel::rbc::RbcState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 453 of file rbc.cc.
{
  if (phase_ == MovePhase::kSensing) {
    std::string from = chess::SquareToString(
        chess::IndexToSquare(action, game()->inner_size()));
    return absl::StrCat("Sense ", from);
  } else {
    if (action == chess::kPassAction) return "pass";
    chess::Move move = ActionToMove(action, Board());
    return move.ToLAN();
  }
}
References action, Board(), from, game(), open_spiel::chess::IndexToSquare(), open_spiel::chess::kPassAction, open_spiel::rbc::kSensing, and absl::StrCat().
Board() [1/2]
chess::ChessBoard & open_spiel::rbc::RbcState::Board () inline
Definition at line 161 of file rbc.h.
{ return current_board_; }
Referenced by ActionToString(), CurrentPlayer(), DoApplyAction(), IsRepetitionDraw(), and ToString().
Board() [2/2]
const chess::ChessBoard & open_spiel::rbc::RbcState::Board () const inline
Definition at line 162 of file rbc.h.
{ return current_board_; }
BoardSize()
int open_spiel::rbc::RbcState::BoardSize () const inline
Definition at line 163 of file rbc.h.
{ return current_board_.BoardSize(); }
References open_spiel::chess::ChessBoard::BoardSize().
Clone()
std::unique_ptr< State > open_spiel::rbc::RbcState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 488 of file rbc.cc.
{
  return std::make_unique<RbcState>(*this);
}
CurrentPlayer()
Player open_spiel::rbc::RbcState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 142 of file rbc.h.
{
    return IsTerminal() ? kTerminalPlayerId : ColorToPlayer(Board().ToPlay());
  }
References Board(), IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by DoApplyAction().
DoApplyAction()
void open_spiel::rbc::RbcState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 356 of file rbc.cc.
{
  // Reset common flags.
  illegal_move_attempted_ = false;
  move_captured_ = false;
  if (phase_ == MovePhase::kSensing) {
    sense_location_[CurrentPlayer()] = action;
    phase_ = MovePhase::kMoving;
  } else {
    SPIEL_CHECK_TRUE(phase_ == MovePhase::kMoving);
    chess::Move move = ActionToMove(action, Board());
    // Handle special cases for RBC.
    if (move == chess::kPassMove) {
      // The RBC's pass move is handled via ChessBoard flag allow_pass_move.
      // Nothing here. Values set above.
    } else if (Board().IsBreachingMove(move)) {
      SPIEL_DCHECK_FALSE(Board().IsMoveLegal(move));
      Board().BreachingMoveToCaptureMove(&move);
      // Transformed move must be legal.
      SPIEL_DCHECK_TRUE(Board().IsMoveLegal(move));
      // And it must be a capture, since we breached unseen opponent pieces.
      SPIEL_DCHECK_NE(Board().at(move.from).color, Board().at(move.to).color);
      move_captured_ = true;
    } else if (!Board().IsMoveLegal(move)) {
      // Illegal move was chosen.
      illegal_move_attempted_ = true;
      // Check why the move was illegal:
      // if it is pawn two-squares-forward move,
      // and there is an enemy piece blocking it, the attempt to move only one
      // square forward (if that would be a legal move).
      // if it is pawn move to last rank, change to pawn move & queen promotion
      // (if that would be a legal move)
      if (move.piece.type == chess::PieceType::kPawn &&
          abs(move.from.y - move.to.y) == 2) {
        const int dy = move.to.y - move.from.y > 0 ? 1 : -1;
        chess::Move one_forward_move = move;
        one_forward_move.to.y -= dy;
        move = Board().IsMoveLegal(one_forward_move) ? one_forward_move
                                                     : chess::kPassMove;
      } else if (move.piece.type == chess::PieceType::kPawn &&
                 Board().IsPawnPromotionRank(move.to)) {
        chess::Move promote_move = move;
        promote_move.promotion_type = chess::PieceType::kQueen;
        move = Board().IsMoveLegal(promote_move) ? promote_move
                                                 : chess::kPassMove;
      } else {
        // Treat the illegal move as a pass.
        move = chess::kPassMove;
      }
    } else {
      // All other moves
      SPIEL_DCHECK_EQ(Board().at(move.from).color, Board().ToPlay());
      move_captured_ =
          Board().at(move.to).color == chess::OppColor(Board().ToPlay());
    }
    SPIEL_DCHECK_TRUE(Board().IsMoveLegal(move));
    moves_history_.push_back(move);
    Board().ApplyMove(move);
    ++repetitions_[current_board_.HashValue()];
    phase_ = MovePhase::kSensing;
  }
  cached_legal_actions_.reset();
}
References action, open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::chess::ChessBoard::at(), Board(), open_spiel::chess::ChessBoard::BreachingMoveToCaptureMove(), open_spiel::chess::Piece::color, CurrentPlayer(), open_spiel::chess::ChessBoard::HashValue(), open_spiel::chess::ChessBoard::IsMoveLegal(), open_spiel::rbc::kMoving, open_spiel::chess::kPassMove, open_spiel::chess::kPawn, open_spiel::chess::kQueen, open_spiel::rbc::kSensing, open_spiel::chess::OppColor(), open_spiel::chess::Move::promotion_type, absl::optional< T >::reset(), SPIEL_CHECK_TRUE, SPIEL_DCHECK_EQ, SPIEL_DCHECK_FALSE, SPIEL_DCHECK_NE, SPIEL_DCHECK_TRUE, open_spiel::chess::Move::to, and open_spiel::chess_common::Square::y.
game()
const RbcGame * open_spiel::rbc::RbcState::game () const inline
Definition at line 178 of file rbc.h.
{
    return open_spiel::down_cast<const RbcGame*>(game_.get());
  }
References open_spiel::down_cast(), and open_spiel::State::game_.
Referenced by open_spiel.python.policy.TabularPolicy::__copy__(), ActionToString(), open_spiel.python.jax.cfr.jax_cfr.JaxCFR::average_policy(), open_spiel.python.mfg.algorithms.distribution.DistributionPolicy::evaluate(), open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::get_avg_policies(), open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::get_gap(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::get_payoffs_for_strategies(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::get_payoffs_for_strategies(), open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::get_policies(), open_spiel.python.jax.cfr.jax_cfr.JaxCFR::init(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::num_players(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::num_players(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::num_strategies(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::num_strategies(), ObservationString(), ObservationTensor(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::payoff_tensor(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::payoff_tensor(), open_spiel.python.examples.chat_game_psro_example.PSRO::run(), open_spiel.python.rl_environment.Environment::set_state(), open_spiel.python.tests.policy_test.TabularTicTacToePolicyTest::test_call_for_state(), open_spiel.integration_tests.api_test.EnforceAPIOnFullTreeBase::test_constant_sum(), open_spiel.integration_tests.api_test.EnforceAPIOnFullTreeBase::test_current_player_infosets_no_overlap_between_players(), open_spiel.integration_tests.api_test.EnforceAPIOnFullTreeBase::test_game_is_perfect_recall(), open_spiel.integration_tests.api_test.EnforceAPIOnPartialTreeBase::test_no_invalid_public_observations(), open_spiel.integration_tests.api_test.EnforceAPIOnPartialTreeBase::test_observations_raises_error_on_invalid_player(), open_spiel.integration_tests.api_test.EnforceAPIOnPartialTreeBase::test_private_information_contents(), open_spiel.integration_tests.api_test.EnforceAPIOnPartialTreeBase::test_sequence_lengths(), open_spiel.python.policy.Policy::to_tabular(), and open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::update_sequences().
illegal_move_attempted()
bool open_spiel::rbc::RbcState::illegal_move_attempted () const inline
Definition at line 185 of file rbc.h.
{ return illegal_move_attempted_; }
IsRepetitionDraw()
bool open_spiel::rbc::RbcState::IsRepetitionDraw () const
Definition at line 512 of file rbc.cc.
{
  const auto entry = repetitions_.find(Board().HashValue());
  SPIEL_CHECK_FALSE(entry == repetitions_.end());
  return entry->second >= kNumRepetitionsToDraw;
}
References Board(), and SPIEL_CHECK_FALSE.
IsTerminal()
bool open_spiel::rbc::RbcState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 149 of file rbc.h.
{
    return static_cast<bool>(MaybeFinalReturns());
  }
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::rbc::RbcState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 447 of file rbc.cc.
{
  if (IsTerminal()) return {};
  MaybeGenerateLegalActions();
  return *cached_legal_actions_;
}
References IsTerminal().
move_captured()
bool open_spiel::rbc::RbcState::move_captured () const inline
Definition at line 184 of file rbc.h.
{ return move_captured_; }
MovesHistory() [1/2]
std::vector< chess::Move > & open_spiel::rbc::RbcState::MovesHistory () inline
Definition at line 169 of file rbc.h.
{ return moves_history_; }
MovesHistory() [2/2]
const std::vector< chess::Move > & open_spiel::rbc::RbcState::MovesHistory () const inline
Definition at line 170 of file rbc.h.
{
    return moves_history_;
  }
ObservationString()
std::string open_spiel::rbc::RbcState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 476 of file rbc.cc.
{
  const auto& game = open_spiel::down_cast<const RbcGame&>(*game_);
  return game.default_observer_->StringFrom(*this, player);
}
References open_spiel::rbc::RbcGame::default_observer_, open_spiel::down_cast(), game(), open_spiel::State::game_, and player.
ObservationTensor()
void open_spiel::rbc::RbcState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 481 of file rbc.cc.
{
  ContiguousAllocator allocator(values);
  const auto& game = open_spiel::down_cast<const RbcGame&>(*game_);
  game.default_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::rbc::RbcGame::default_observer_, open_spiel::down_cast(), game(), open_spiel::State::game_, player, and values.
phase()
MovePhase open_spiel::rbc::RbcState::phase () const inline
Definition at line 182 of file rbc.h.
{ return phase_; }
Returns()
std::vector< double > open_spiel::rbc::RbcState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 467 of file rbc.cc.
{
  auto maybe_final_returns = MaybeFinalReturns();
  if (maybe_final_returns) {
    return *maybe_final_returns;
  } else {
    return {0.0, 0.0};
  }
}
sense_location()
const std::array< int, 2 > & open_spiel::rbc::RbcState::sense_location () const inline
Definition at line 183 of file rbc.h.
{ return sense_location_; }
StartBoard() [1/2]
chess::ChessBoard & open_spiel::rbc::RbcState::StartBoard () inline
Definition at line 166 of file rbc.h.
{ return start_board_; }
StartBoard() [2/2]
const chess::ChessBoard & open_spiel::rbc::RbcState::StartBoard () const inline
Definition at line 167 of file rbc.h.
{ return start_board_; }
ToString()
std::string open_spiel::rbc::RbcState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 465 of file rbc.cc.
{ return Board().ToFEN(); }
References Board(), and open_spiel::chess::ChessBoard::ToFEN().
UndoAction()
void open_spiel::rbc::RbcState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 492 of file rbc.cc.
{
  // TODO: Make this fast by storing undo info in another stack.
  SPIEL_CHECK_FALSE(history_.empty());  // Can't undo initial state.
  history_.pop_back();
  --move_number_;
  if (phase_ == MovePhase::kMoving) {
    phase_ = MovePhase::kSensing;
  } else {
    SPIEL_CHECK_GE(moves_history_.size(), 1);
    phase_ = MovePhase::kMoving;
    --repetitions_[current_board_.HashValue()];
    moves_history_.pop_back();
    current_board_ = start_board_;
    for (const chess::Move& move : moves_history_) {
      current_board_.ApplyMove(move);
    }
  }
}
References open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::chess::ChessBoard::HashValue(), open_spiel::State::history_, open_spiel::rbc::kMoving, open_spiel::rbc::kSensing, open_spiel::State::move_number_, SPIEL_CHECK_FALSE, and SPIEL_CHECK_GE.
Friends And Related Symbol Documentation
RbcObserver
friend class RbcObserver friend
Definition at line 191 of file rbc.h.
The documentation for this class was generated from the following files:
open_spiel/games/rbc/rbc.h
open_spiel/games/rbc/rbc.cc