open spiel: absl::time_internal::cctz::time_zone Class Reference
absl::time_internal::cctz::time_zone Class Reference
#include <time_zone.h>
Classes
struct absolute_lookup
struct civil_lookup
struct civil_transition
class Impl
Public Member Functions
time_zone ()
time_zone (const time_zone &)=default
time_zone & operator= (const time_zone &)=default
std::string name () const
absolute_lookup lookup (const time_point< seconds > &tp) const
template<typename D >
absolute_lookup lookup (const time_point< D > &tp) const
civil_lookup lookup (const civil_second &cs) const
bool next_transition (const time_point< seconds > &tp, civil_transition *trans) const
template<typename D >
bool next_transition (const time_point< D > &tp, civil_transition *trans) const
bool prev_transition (const time_point< seconds > &tp, civil_transition *trans) const
template<typename D >
bool prev_transition (const time_point< D > &tp, civil_transition *trans) const
std::string version () const
std::string description () const
Friends
bool operator== (time_zone lhs, time_zone rhs)
bool operator!= (time_zone lhs, time_zone rhs)
template<typename H >
H AbslHashValue (H h, time_zone tz)
Detailed Description
Definition at line 68 of file time_zone.h.
Constructor & Destructor Documentation
time_zone() [1/2]
absl::time_internal::cctz::time_zone::time_zone () inline
Definition at line 70 of file time_zone.h.
: time_zone(nullptr) {}  // Equivalent to UTC
Referenced by absl::time_internal::cctz::time_zone::Impl::LoadTimeZone(), and absl::time_internal::cctz::time_zone::Impl::UTC().
time_zone() [2/2]
absl::time_internal::cctz::time_zone::time_zone (const time_zone &) default
Member Function Documentation
description()
std::string absl::time_internal::cctz::time_zone::description () const
Definition at line 102 of file time_zone_lookup.cc.
{
  return effective_impl().Description();
}
References absl::time_internal::cctz::time_zone::Impl::Description().
lookup() [1/3]
time_zone::civil_lookup absl::time_internal::cctz::time_zone::lookup (const civil_second & cs) const
Definition at line 86 of file time_zone_lookup.cc.
{
  return effective_impl().MakeTime(cs);
}
References absl::time_internal::cctz::time_zone::Impl::MakeTime().
lookup() [2/3]
template<typename D > absolute_lookup absl::time_internal::cctz::time_zone::lookup (const time_point< D > & tp) const inline
Definition at line 97 of file time_zone.h.
{
    return lookup(detail::split_seconds(tp).first);
  }
References first, lookup(), and absl::time_internal::cctz::detail::split_seconds().
lookup() [3/3]
time_zone::absolute_lookup absl::time_internal::cctz::time_zone::lookup (const time_point< seconds > & tp) const
Definition at line 81 of file time_zone_lookup.cc.
{
  return effective_impl().BreakTime(tp);
}
References absl::time_internal::cctz::time_zone::Impl::BreakTime().
Referenced by absl::TimeZone::At(), absl::TimeZone::At(), absl::Time::In(), lookup(), and absl::time_internal::cctz::detail::parse().
name()
std::string absl::time_internal::cctz::time_zone::name () const
Definition at line 79 of file time_zone_lookup.cc.
{ return effective_impl().Name(); }
References absl::time_internal::cctz::time_zone::Impl::Name().
Referenced by absl::time_internal::cctz::time_zone::Impl::LoadTimeZone(), absl::time_internal::cctz::TEST(), and absl::time_internal::cctz::TEST().
next_transition() [1/2]
template<typename D > bool absl::time_internal::cctz::time_zone::next_transition (const time_point< D > & tp, civil_transition * trans) const inline
Definition at line 189 of file time_zone.h.
{
    return next_transition(detail::split_seconds(tp).first, trans);
  }
References first, next_transition(), and absl::time_internal::cctz::detail::split_seconds().
next_transition() [2/2]
bool absl::time_internal::cctz::time_zone::next_transition (const time_point< seconds > & tp, civil_transition * trans) const
Definition at line 90 of file time_zone_lookup.cc.
{
  return effective_impl().NextTransition(tp, trans);
}
References absl::time_internal::cctz::time_zone::Impl::NextTransition().
Referenced by next_transition().
operator=()
time_zone & absl::time_internal::cctz::time_zone::operator= (const time_zone &) default
prev_transition() [1/2]
template<typename D > bool absl::time_internal::cctz::time_zone::prev_transition (const time_point< D > & tp, civil_transition * trans) const inline
Definition at line 195 of file time_zone.h.
{
    return prev_transition(detail::split_seconds(tp).first, trans);
  }
References first, prev_transition(), and absl::time_internal::cctz::detail::split_seconds().
prev_transition() [2/2]
bool absl::time_internal::cctz::time_zone::prev_transition (const time_point< seconds > & tp, civil_transition * trans) const
Definition at line 95 of file time_zone_lookup.cc.
{
  return effective_impl().PrevTransition(tp, trans);
}
References absl::time_internal::cctz::time_zone::Impl::PrevTransition().
Referenced by prev_transition().
version()
std::string absl::time_internal::cctz::time_zone::version () const
Definition at line 100 of file time_zone_lookup.cc.
{ return effective_impl().Version(); }
References absl::time_internal::cctz::time_zone::Impl::Version().
Friends And Related Symbol Documentation
AbslHashValue
template<typename H > H AbslHashValue (H h, time_zone tz) friend
Definition at line 216 of file time_zone.h.
{
    return H::combine(std::move(h), &tz.effective_impl());
  }
operator!=
bool operator!= (time_zone lhs, time_zone rhs) friend
Definition at line 213 of file time_zone.h.
{ return !(lhs == rhs); }
operator==
bool operator== (time_zone lhs, time_zone rhs) friend
Definition at line 210 of file time_zone.h.
{
    return &lhs.effective_impl() == &rhs.effective_impl();
  }
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/time/internal/cctz/include/cctz/time_zone.h
open_spiel/abseil-cpp/absl/time/internal/cctz/src/time_zone_lookup.cc