open spiel: open_spiel::SimMoveState Class Reference
open_spiel::SimMoveState Class Reference abstract
#include <simultaneous_move_game.h>
Public Member Functions
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions (Player player) const override=0
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual Player CurrentPlayer () const =0
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
virtual std::string ActionToString (Player player, Action action_id) const =0
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual std::string ToString () const =0
virtual bool operator== (const State &other) const
virtual bool IsTerminal () const =0
virtual std::vector< double > Rewards () const
virtual std::vector< double > Returns () const =0
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
virtual std::string ObservationString (Player player) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
virtual std::unique_ptr< State > Clone () const =0
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
void DoApplyActions (const std::vector< Action > &actions) override=0
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyAction (Action action_id)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 40 of file simultaneous_move_game.h.
Constructor & Destructor Documentation
SimMoveState() [1/2]
open_spiel::SimMoveState::SimMoveState (std::shared_ptr< const Game > game) inline
Definition at line 42 of file simultaneous_move_game.h.
: State(game) {}
SimMoveState() [2/2]
open_spiel::SimMoveState::SimMoveState (const SimMoveState &) default
Member Function Documentation
ApplyAction()
void open_spiel::SimMoveState::ApplyAction (Action action) inline override virtual
Reimplemented from open_spiel::State.
Definition at line 66 of file simultaneous_move_game.h.
{
    if (IsSimultaneousNode()) {
      ApplyFlatJointAction(action);
    } else {
      const Player player = CurrentPlayer();
      DoApplyAction(action);
      history_.push_back({player, action});
    }
  }
References action, ApplyFlatJointAction(), open_spiel::State::CurrentPlayer(), open_spiel::State::DoApplyAction(), open_spiel::State::history_, open_spiel::State::IsSimultaneousNode(), and player.
ApplyFlatJointAction()
void open_spiel::SimMoveState::ApplyFlatJointAction (Action flat_action) protected
Definition at line 47 of file simultaneous_move_game.cc.
{
  ApplyActions(FlatJointActionToActions(flat_action));
}
References open_spiel::State::ApplyActions(), and FlatJointActionToActions().
Referenced by ApplyAction(), open_spiel::coop_box_pushing::CoopBoxPushingState::DoApplyAction(), open_spiel::goofspiel::GoofspielState::DoApplyAction(), open_spiel::laser_tag::LaserTagState::DoApplyAction(), open_spiel::markov_soccer::MarkovSoccerState::DoApplyAction(), and open_spiel::pathfinding::PathfindingState::DoApplyAction().
DoApplyActions()
void open_spiel::SimMoveState::DoApplyActions (const std::vector< Action > & actions) override protected pure virtual
Reimplemented from open_spiel::State.
Implemented in open_spiel::blotto::BlottoState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::goofspiel::GoofspielState, open_spiel::laser_tag::LaserTagState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::matching_pennies_3p::MatchingPennies3pState, open_spiel::matrix_game::MatrixState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::pathfinding::PathfindingState, open_spiel::RepeatedState, and open_spiel::tensor_game::TensorState.
FlatJointActionToActions()
std::vector< Action > open_spiel::SimMoveState::FlatJointActionToActions (Action flat_action) const
Definition at line 28 of file simultaneous_move_game.cc.
{
  std::vector<Action> actions(num_players_, kInvalidAction);
  for (Player player = 0; player < num_players_; ++player) {
    // For each player with legal actions available:
    const auto legal_actions = LegalActions(player);
    int num_actions = legal_actions.size();
    if (num_actions > 0) {
      // Extract the least-significant digit (radix = the number legal actions
      // for the current player) from flat_action. Use the digit as an index
      // into the player's set of legal actions.
      actions[player] = legal_actions[flat_action % num_actions];
      // Update the flat_action to be for the remaining players only.
      flat_action /= num_actions;
    }
  }
  return actions;
}
References open_spiel::kInvalidAction, LegalActions(), open_spiel::State::num_players_, and player.
Referenced by ApplyFlatJointAction(), and open_spiel::algorithms::ortools::ComputeCorrelatedEquilibrium().
FlatJointActionToString()
std::string open_spiel::SimMoveState::FlatJointActionToString (Action flat_action) const protected
Definition at line 62 of file simultaneous_move_game.cc.
{
  // Assembles the string for each individual player action into a single
  // string. For example, [Heads, Tails] would mean than player 0 chooses Heads,
  // and player 1 chooses Tails.
  std::string str;
  for (auto player = Player{0}; player < num_players_; ++player) {
    if (!str.empty()) str.append(", ");
    const auto legal_actions = LegalActions(player);
    int num_actions = legal_actions.size();
    str.append(
        ActionToString(player, legal_actions[flat_action % num_actions]));
    flat_action /= num_actions;
  }
  return absl::StrCat("[", str, "]");
}
References open_spiel::State::ActionToString(), LegalActions(), open_spiel::State::num_players_, player, and absl::StrCat().
Referenced by open_spiel::goofspiel::GoofspielState::ActionToString(), open_spiel::laser_tag::LaserTagState::ActionToString(), open_spiel::markov_soccer::MarkovSoccerState::ActionToString(), open_spiel::matrix_game::MatrixState::ActionToString(), open_spiel::oshi_zumo::OshiZumoState::ActionToString(), and open_spiel::tensor_game::TensorState::ActionToString().
LegalActions() [1/2]
std::vector< Action > open_spiel::SimMoveState::LegalActions () const inline override virtual
Implements open_spiel::State.
Definition at line 52 of file simultaneous_move_game.h.
{
    if (IsSimultaneousNode()) {
      return LegalFlatJointActions();
    } else if (IsTerminal()) {
      return {};
    } else if (IsChanceNode()) {
      return LegalChanceOutcomes();
    } else {
      return LegalActions(CurrentPlayer());
    }
  }
References open_spiel::State::CurrentPlayer(), open_spiel::State::IsChanceNode(), open_spiel::State::IsSimultaneousNode(), open_spiel::State::IsTerminal(), LegalActions(), open_spiel::State::LegalChanceOutcomes(), and LegalFlatJointActions().
Referenced by open_spiel::goofspiel::GoofspielState::DoApplyActions(), FlatJointActionToActions(), FlatJointActionToString(), LegalActions(), and open_spiel::matrix_game::MatrixState::ToString().
LegalActions() [2/2]
std::vector< Action > open_spiel::SimMoveState::LegalActions (Player player) const override pure virtual
Reimplemented from open_spiel::State.
Implemented in open_spiel::blotto::BlottoState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::goofspiel::GoofspielState, open_spiel::laser_tag::LaserTagState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::matching_pennies_3p::MatchingPennies3pState, open_spiel::matrix_game::MatrixState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::pathfinding::PathfindingState, open_spiel::RepeatedState, and open_spiel::tensor_game::TensorState.
Referenced by open_spiel::algorithms::ortools::ComputeCorrelatedEquilibrium().
LegalFlatJointActions()
std::vector< Action > open_spiel::SimMoveState::LegalFlatJointActions () const protected
Definition at line 51 of file simultaneous_move_game.cc.
{
  ActionView view(*this);
  FlatJointActions flat_joint_actions = view.flat_joint_actions();
  std::vector<Action> joint_actions;
  joint_actions.reserve(flat_joint_actions.num_flat_joint_actions);
  for (Action flat_joint_action : flat_joint_actions) {
    joint_actions.push_back(flat_joint_action);
  }
  return joint_actions;
}
References open_spiel::ActionView::flat_joint_actions(), and open_spiel::FlatJointActions::num_flat_joint_actions.
Referenced by open_spiel::coop_box_pushing::CoopBoxPushingState::LegalActions(), open_spiel::goofspiel::GoofspielState::LegalActions(), open_spiel::matrix_game::MatrixState::LegalActions(), open_spiel::oshi_zumo::OshiZumoState::LegalActions(), LegalActions(), and open_spiel::tensor_game::TensorState::LegalActions().
The documentation for this class was generated from the following files:
open_spiel/simultaneous_move_game.h
open_spiel/simultaneous_move_game.cc