open spiel: open_spiel::add_noise::AddNoiseState Class Reference
open_spiel::add_noise::AddNoiseState Class Reference
#include <add_noise.h>
Public Member Functions
AddNoiseState (std::shared_ptr< const Game > game, std::unique_ptr< State > state)
AddNoiseState (const AddNoiseState &other)=default
std::unique_ptr< State > Clone () const override
std::vector< double > Returns () const override
std::vector< double > Rewards () const override
Public Member Functions inherited from open_spiel::WrappedState
WrappedState (std::shared_ptr< const Game > game, std::unique_ptr< State > state)
WrappedState (const WrappedState &other)
Player CurrentPlayer () const override
std::vector< Action > LegalActions (Player player) const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
void UndoAction (Player player, Action action) override
ActionsAndProbs ChanceOutcomes () const override
std::vector< Action > LegalChanceOutcomes () const override
const State & GetWrappedState () const
std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::WrappedState
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &actions) override
Protected Attributes inherited from open_spiel::WrappedState
std::unique_ptr< State > state_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 33 of file add_noise.h.
Constructor & Destructor Documentation
AddNoiseState() [1/2]
open_spiel::add_noise::AddNoiseState::AddNoiseState (std::shared_ptr< const Game > game, std::unique_ptr< State > state)
Definition at line 95 of file add_noise.cc.
    : WrappedState(transformed_game, std::move(state)) {}
AddNoiseState() [2/2]
open_spiel::add_noise::AddNoiseState::AddNoiseState (const AddNoiseState & other) default
Member Function Documentation
Clone()
std::unique_ptr< State > open_spiel::add_noise::AddNoiseState::Clone () const inline override virtual
Implements open_spiel::WrappedState.
Definition at line 37 of file add_noise.h.
{
    return std::make_unique<AddNoiseState>(*this);
  }
Returns()
std::vector< double > open_spiel::add_noise::AddNoiseState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 99 of file add_noise.cc.
{
  std::vector<double> returns = state_->Returns();
  SPIEL_CHECK_EQ(returns.size(), 2);
  if (state_->IsTerminal()) {
    auto const_noise_game = down_cast<const AddNoiseGame*>(game_.get());
    AddNoiseGame* noise_game = const_cast<AddNoiseGame*>(const_noise_game);
    double noise = noise_game->GetNoise(*this);
    returns[0] += noise;
    returns[1] -= noise;
  }
  return returns;
}
References open_spiel::down_cast(), open_spiel::State::game_, open_spiel::add_noise::AddNoiseGame::GetNoise(), open_spiel::WrappedState::Returns(), SPIEL_CHECK_EQ, and open_spiel::WrappedState::state_.
Referenced by Rewards().
Rewards()
std::vector< double > open_spiel::add_noise::AddNoiseState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 114 of file add_noise.cc.
{
  if (IsTerminal()) {
    return Returns();
  } else {
    SPIEL_CHECK_FALSE(IsChanceNode());
    return std::vector<double>(num_players_, 0.0);
  }
}
References open_spiel::State::IsChanceNode(), open_spiel::WrappedState::IsTerminal(), open_spiel::State::num_players_, Returns(), and SPIEL_CHECK_FALSE.
The documentation for this class was generated from the following files:
open_spiel/game_transforms/add_noise.h
open_spiel/game_transforms/add_noise.cc