open spiel: open_spiel::Bot Class Reference
open_spiel::Bot Class Reference abstract
#include <spiel_bots.h>
Public Member Functions
virtual ~Bot ()=default
virtual Action Step (const State &state)=0
virtual void InformAction (const State &state, Player player_id, Action action)
virtual void InformActions (const State &state, const std::vector< Action > &actions)
virtual void Restart ()
virtual void RestartAt (const State &state)
virtual bool ProvidesForceAction ()
virtual void ForceAction (const State &state, Action action)
virtual bool ProvidesPolicy ()
virtual ActionsAndProbs GetPolicy (const State &state)
virtual std::pair< ActionsAndProbs, Action > StepWithPolicy (const State &state)
virtual bool IsClonable () const
virtual std::unique_ptr< Bot > Clone ()
Detailed Description
Definition at line 72 of file spiel_bots.h.
Constructor & Destructor Documentation
~Bot()
virtual open_spiel::Bot::~Bot () virtual default
Member Function Documentation
Clone()
virtual std::unique_ptr< Bot > open_spiel::Bot::Clone () inline virtual
Reimplemented in open_spiel::gin_rummy::SimpleGinRummyBot, and open_spiel::PyBot< BotBase >.
Definition at line 174 of file spiel_bots.h.
{
    SpielFatalError("Clone method not implemented.");
  }
References open_spiel::SpielFatalError().
Referenced by open_spiel::init_pyspiel_bots().
ForceAction()
virtual void open_spiel::Bot::ForceAction (const State & state, Action action) inline virtual
Reimplemented in open_spiel::hearts::XinxinBot, and open_spiel::PyBot< BotBase >.
Definition at line 123 of file spiel_bots.h.
{
    if (ProvidesForceAction()) {
      SpielFatalError(
          "ForceAction not implemented but should because the bot is "
          "registered as overridable.");
    } else {
      SpielFatalError(
          "ForceAction not implemented because the bot is not overridable");
    }
  }
References ProvidesForceAction(), and open_spiel::SpielFatalError().
Referenced by define_julia_module(), and open_spiel::init_pyspiel_bots().
GetPolicy()
virtual ActionsAndProbs open_spiel::Bot::GetPolicy (const State & state) inline virtual
Reimplemented in open_spiel::algorithms::ISMCTSBot, open_spiel::gin_rummy::SimpleGinRummyBot, open_spiel::PIMCBot, and open_spiel::PyBot< BotBase >.
Definition at line 137 of file spiel_bots.h.
{
    if (ProvidesPolicy()) {
      SpielFatalError(
          "GetPolicy not implemented but should because the bot is registered "
          "as exposing its policy.");
    } else {
      SpielFatalError(
          "GetPolicy not implemented because the bot is not exposing any "
          "policy.");
    }
  }
References ProvidesPolicy(), and open_spiel::SpielFatalError().
Referenced by define_julia_module(), and open_spiel::init_pyspiel_bots().
InformAction()
virtual void open_spiel::Bot::InformAction (const State & state, Player player_id, Action action) inline virtual
Reimplemented in open_spiel::hearts::XinxinBot, open_spiel::PyBot< BotBase >, and open_spiel::uci::UCIBot.
Definition at line 102 of file spiel_bots.h.
                                           {}
Referenced by open_spiel::init_pyspiel_bots().
InformActions()
virtual void open_spiel::Bot::InformActions (const State & state, const std::vector< Action > & actions) inline virtual
Reimplemented in open_spiel::PyBot< BotBase >.
Definition at line 106 of file spiel_bots.h.
                                                               {}
Referenced by open_spiel::init_pyspiel_bots().
IsClonable()
virtual bool open_spiel::Bot::IsClonable () const inline virtual
Reimplemented in open_spiel::gin_rummy::SimpleGinRummyBot, open_spiel::PIMCBot, and open_spiel::PyBot< BotBase >.
Definition at line 173 of file spiel_bots.h.
{ return false; }
Referenced by open_spiel::init_pyspiel_bots().
ProvidesForceAction()
virtual bool open_spiel::Bot::ProvidesForceAction () inline virtual
Reimplemented in open_spiel::hearts::XinxinBot, and open_spiel::PyBot< BotBase >.
Definition at line 120 of file spiel_bots.h.
{ return false; }
Referenced by define_julia_module(), ForceAction(), and open_spiel::init_pyspiel_bots().
ProvidesPolicy()
virtual bool open_spiel::Bot::ProvidesPolicy () inline virtual
Reimplemented in open_spiel::algorithms::ISMCTSBot, open_spiel::gin_rummy::SimpleGinRummyBot, open_spiel::PIMCBot, and open_spiel::PyBot< BotBase >.
Definition at line 136 of file spiel_bots.h.
{ return false; }
Referenced by define_julia_module(), GetPolicy(), open_spiel::init_pyspiel_bots(), and StepWithPolicy().
Restart()
virtual void open_spiel::Bot::Restart () inline virtual
Reimplemented in open_spiel::algorithms::ISMCTSBot, open_spiel::algorithms::MCTSBot, open_spiel::gin_rummy::SimpleGinRummyBot, open_spiel::hearts::XinxinBot, open_spiel::PyBot< BotBase >, open_spiel::roshambo::RoshamboBot, and open_spiel::uci::UCIBot.
Definition at line 110 of file spiel_bots.h.
{}
Referenced by define_julia_module(), and open_spiel::init_pyspiel_bots().
RestartAt()
virtual void open_spiel::Bot::RestartAt (const State & state) inline virtual
Reimplemented in open_spiel::algorithms::ISMCTSBot, open_spiel::algorithms::MCTSBot, open_spiel::hearts::XinxinBot, open_spiel::PyBot< BotBase >, and open_spiel::uci::UCIBot.
Definition at line 113 of file spiel_bots.h.
{
    SpielFatalError("RestartAt(state) not implemented.");
  }
References open_spiel::SpielFatalError().
Referenced by define_julia_module(), and open_spiel::init_pyspiel_bots().
Step()
virtual Action open_spiel::Bot::Step (const State & state) pure virtual
Implemented in open_spiel::algorithms::ISMCTSBot, open_spiel::algorithms::MCTSBot, open_spiel::gin_rummy::SimpleGinRummyBot, open_spiel::hearts::XinxinBot, open_spiel::HumanBot, open_spiel::PIMCBot, open_spiel::PyBot< BotBase >, open_spiel::roshambo::RoshamboBot, and open_spiel::uci::UCIBot.
Referenced by define_julia_module(), and open_spiel::init_pyspiel_bots().
StepWithPolicy()
virtual std::pair< ActionsAndProbs, Action > open_spiel::Bot::StepWithPolicy (const State & state) inline virtual
Reimplemented in open_spiel::algorithms::ISMCTSBot, open_spiel::algorithms::MCTSBot, open_spiel::gin_rummy::SimpleGinRummyBot, open_spiel::PIMCBot, and open_spiel::PyBot< BotBase >.
Definition at line 148 of file spiel_bots.h.
{
    if (ProvidesPolicy()) {
      SpielFatalError(
          "StepWithPolicy not implemented but should because the bot is "
          "registered as exposing its policy.");
    } else {
      SpielFatalError(
          "StepWithPolicy not implemented because the bot is not exposing any "
          "policy.");
    }
  }
References ProvidesPolicy(), and open_spiel::SpielFatalError().
Referenced by define_julia_module(), and open_spiel::init_pyspiel_bots().
The documentation for this class was generated from the following file:
open_spiel/spiel_bots.h