open spiel: open_spiel::algorithms::MDP Class Reference
open_spiel::algorithms::MDP Class Reference
#include <tabular_best_response_mdp.h>
Public Member Functions
MDP ()
MDPNode * CreateTerminalNode (const std::string &node_key)
MDPNode * LookupOrCreateNode (const std::string &node_key, bool terminal=false)
MDPNode * RootNode ()
double Solve (double tolerance, TabularPolicy *br_policy)
int NumNonTerminalNodes () const
int TotalSize () const
Detailed Description
Definition at line 104 of file tabular_best_response_mdp.h.
Constructor & Destructor Documentation
MDP()
open_spiel::algorithms::MDP::MDP ()
Definition at line 45 of file tabular_best_response_mdp.cc.
         : terminal_node_uid_(0), num_nonterminal_nodes_(0) {
  node_map_[kRootKey] = absl::make_unique<MDPNode>(std::string(kRootKey));
  node_map_[kRootKey]->add_weight(1.0);
}
Member Function Documentation
CreateTerminalNode()
MDPNode * open_spiel::algorithms::MDP::CreateTerminalNode (const std::string & node_key)
Definition at line 50 of file tabular_best_response_mdp.cc.
{
  ++terminal_node_uid_;
  MDPNode *terminal_node = LookupOrCreateNode(node_key, true);
  terminal_node->set_terminal(true);
  return terminal_node;
}
References LookupOrCreateNode(), and open_spiel::algorithms::MDPNode::set_terminal().
LookupOrCreateNode()
MDPNode * open_spiel::algorithms::MDP::LookupOrCreateNode (const std::string & node_key, bool terminal = false)
Definition at line 57 of file tabular_best_response_mdp.cc.
{
  const auto &iter = node_map_.find(node_key);
  if (iter != node_map_.end()) {
    return iter->second.get();
  } else {
    MDPNode *new_node = new MDPNode(node_key);
    node_map_[node_key].reset(new_node);
    if (!terminal) {
      num_nonterminal_nodes_++;
    }
    return new_node;
  }
}
Referenced by CreateTerminalNode().
NumNonTerminalNodes()
int open_spiel::algorithms::MDP::NumNonTerminalNodes () const inline
Definition at line 113 of file tabular_best_response_mdp.h.
{ return num_nonterminal_nodes_; }
RootNode()
MDPNode * open_spiel::algorithms::MDP::RootNode () inline
Definition at line 110 of file tabular_best_response_mdp.h.
{ return node_map_[kRootKey].get(); }
Referenced by Solve().
Solve()
double open_spiel::algorithms::MDP::Solve (double tolerance, TabularPolicy * br_policy)
Definition at line 71 of file tabular_best_response_mdp.cc.
{
  double delta = 0;
  do {
    delta = 0.0;
    for (auto &key_and_node : node_map_) {
      MDPNode *node = key_and_node.second.get();
      if (node->terminal()) {
        continue;
      }
      double max_value = -std::numeric_limits<double>::infinity();
      Action max_action = kInvalidAction;
      double node_weight = node->total_weight();
      SPIEL_CHECK_GE(node_weight, 0.0);
      // Compute Bellman value from children.
      for (const auto &action_and_child : node->children()) {
        double action_value = 0.0;
        Action action = action_and_child.first;
        for (auto &child_value : node->children()[action]) {
          MDPNode *child = child_value.first;
          double transition_weight = child_value.second;
          SPIEL_CHECK_TRUE(child != nullptr);
          double prob = transition_weight / node_weight;
          if (std::isnan(prob)) {
            // When transition_weight = node_weight = 0, set to 0
            prob = 0.0;
          }
          SPIEL_CHECK_PROB(prob);
          action_value += prob * child->value();
        }
        if (action_value > max_value) {
          max_value = action_value;
          max_action = action;
        }
      }
      SPIEL_CHECK_NE(max_action, kInvalidAction);
      delta += std::abs(node->value() - max_value);
      node->set_value(max_value);
      // Set the best response to the maximum-value action, if it's non-null.
      if (node->node_key() != kRootKey) {
        ActionsAndProbs br_state_policy;
        for (const auto &[action, child] : node->children()) {
          SetProb(&br_state_policy, action, action == max_action ? 1.0 : 0.0);
        }
        br_policy->SetStatePolicy(node->node_key(), br_state_policy);
      }
    }
  } while (delta > tolerance);
  return RootNode()->value();
}
References action, open_spiel::algorithms::MDPNode::children(), open_spiel::kInvalidAction, open_spiel::algorithms::MDPNode::node_key(), RootNode(), open_spiel::algorithms::MDPNode::set_value(), open_spiel::SetProb(), open_spiel::TabularPolicy::SetStatePolicy(), SPIEL_CHECK_GE, SPIEL_CHECK_NE, SPIEL_CHECK_PROB, SPIEL_CHECK_TRUE, open_spiel::algorithms::MDPNode::terminal(), open_spiel::algorithms::MDPNode::total_weight(), and open_spiel::algorithms::MDPNode::value().
TotalSize()
int open_spiel::algorithms::MDP::TotalSize () const inline
Definition at line 114 of file tabular_best_response_mdp.h.
{ return node_map_.size(); }
The documentation for this class was generated from the following files:
open_spiel/algorithms/tabular_best_response_mdp.h
open_spiel/algorithms/tabular_best_response_mdp.cc