open spiel: open_spiel::chess::ChessState Class Reference
open_spiel::chess::ChessState Class Reference
#include <chess.h>
Public Member Functions
ChessState (std::shared_ptr< const Game > game)
ChessState (std::shared_ptr< const Game > game, const std::string &fen)
ChessState (const ChessState &)=default
ChessState & operator= (const ChessState &)=default
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
ChessBoard & Board ()
const ChessBoard & Board () const
int BoardSize () const
ChessBoard & StartBoard ()
const ChessBoard & StartBoard () const
std::vector< Move > & MovesHistory ()
const std::vector< Move > & MovesHistory () const
std::string DebugString ()
Action ParseMoveToAction (const std::string &move_str) const
std::string Serialize () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 123 of file chess.h.
Constructor & Destructor Documentation
ChessState() [1/3]
open_spiel::chess::ChessState::ChessState (std::shared_ptr< const Game > game)
Definition at line 92 of file chess.cc.
    : State(game),
      start_board_(MakeDefaultBoard()),
      current_board_(start_board_) {
  repetitions_[current_board_.HashValue()] = 1;
}
References open_spiel::chess::ChessBoard::HashValue().
Referenced by Clone().
ChessState() [2/3]
open_spiel::chess::ChessState::ChessState (std::shared_ptr< const Game > game, const std::string & fen)
Definition at line 99 of file chess.cc.
    : State(game) {
  auto maybe_board = ChessBoard::BoardFromFEN(fen);
  SPIEL_CHECK_TRUE(maybe_board);
  start_board_ = *maybe_board;
  current_board_ = start_board_;
  repetitions_[current_board_.HashValue()] = 1;
}
References open_spiel::chess::ChessBoard::BoardFromFEN(), open_spiel::chess::ChessBoard::HashValue(), and SPIEL_CHECK_TRUE.
ChessState() [3/3]
open_spiel::chess::ChessState::ChessState (const ChessState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::chess::ChessState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 294 of file chess.cc.
{
  Move move = ActionToMove(action, Board());
  return move.ToSAN(Board());
}
References action, open_spiel::chess::ActionToMove(), and Board().
Board() [1/2]
ChessBoard & open_spiel::chess::ChessState::Board () inline
Definition at line 155 of file chess.h.
{ return current_board_; }
Referenced by ActionToString(), CurrentPlayer(), DoApplyAction(), ObservationTensor(), ParseMoveToAction(), open_spiel::uci::RandomUciBot(), and ToString().
Board() [2/2]
const ChessBoard & open_spiel::chess::ChessState::Board () const inline
Definition at line 156 of file chess.h.
{ return current_board_; }
BoardSize()
int open_spiel::chess::ChessState::BoardSize () const inline
Definition at line 157 of file chess.h.
{ return current_board_.BoardSize(); }
References open_spiel::chess::ChessBoard::BoardSize().
Referenced by ParseMoveToAction().
Clone()
std::unique_ptr< State > open_spiel::chess::ChessState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 368 of file chess.cc.
{
  return std::unique_ptr<State>(new ChessState(*this));
}
References ChessState().
CurrentPlayer()
Player open_spiel::chess::ChessState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 135 of file chess.h.
{
    return IsTerminal() ? kTerminalPlayerId : ColorToPlayer(Board().ToPlay());
  }
References Board(), open_spiel::chess::ColorToPlayer(), IsTerminal(), and open_spiel::kTerminalPlayerId.
DebugString()
std::string open_spiel::chess::ChessState::DebugString () inline
Definition at line 167 of file chess.h.
{ return current_board_.DebugString(); }
References open_spiel::chess::ChessBoard::DebugString().
DoApplyAction()
void open_spiel::chess::ChessState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 116 of file chess.cc.
{
  Move move = ActionToMove(action, Board());
  moves_history_.push_back(move);
  Board().ApplyMove(move);
  ++repetitions_[current_board_.HashValue()];
  cached_legal_actions_.reset();
}
References action, open_spiel::chess::ActionToMove(), open_spiel::chess::ChessBoard::ApplyMove(), Board(), open_spiel::chess::ChessBoard::HashValue(), and absl::optional< T >::reset().
InformationStateString()
std::string open_spiel::chess::ChessState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 310 of file chess.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::chess::ChessState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 142 of file chess.h.
{
    return static_cast<bool>(MaybeFinalReturns());
  }
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::chess::ChessState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 135 of file chess.cc.
{
  MaybeGenerateLegalActions();
  if (IsTerminal()) return {};
  return *cached_legal_actions_;
}
References IsTerminal().
MovesHistory() [1/2]
std::vector< Move > & open_spiel::chess::ChessState::MovesHistory () inline
Definition at line 163 of file chess.h.
{ return moves_history_; }
MovesHistory() [2/2]
const std::vector< Move > & open_spiel::chess::ChessState::MovesHistory () const inline
Definition at line 164 of file chess.h.
{ return moves_history_; }
ObservationString()
std::string open_spiel::chess::ChessState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 316 of file chess.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::chess::ChessState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 322 of file chess.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  auto value_it = values.begin();
  // Piece configuration.
  for (const auto& piece_type : kPieceTypes) {
    AddPieceTypePlane(Color::kWhite, piece_type, Board(), value_it);
    AddPieceTypePlane(Color::kBlack, piece_type, Board(), value_it);
  }
  AddPieceTypePlane(Color::kEmpty, PieceType::kEmpty, Board(), value_it);
  const auto entry = repetitions_.find(Board().HashValue());
  SPIEL_CHECK_FALSE(entry == repetitions_.end());
  int repetitions = entry->second;
  // Num repetitions for the current board.
  AddScalarPlane(repetitions, 1, 3, value_it);
  // Side to play.
  AddScalarPlane(ColorToPlayer(Board().ToPlay()), 0, 1, value_it);
  // Irreversible move counter.
  AddScalarPlane(Board().IrreversibleMoveCounter(), 0, 101, value_it);
  // Castling rights.
  AddBinaryPlane(Board().CastlingRight(Color::kWhite, CastlingDirection::kLeft),
                 value_it);
  AddBinaryPlane(
      Board().CastlingRight(Color::kWhite, CastlingDirection::kRight),
      value_it);
  AddBinaryPlane(Board().CastlingRight(Color::kBlack, CastlingDirection::kLeft),
                 value_it);
  AddBinaryPlane(
      Board().CastlingRight(Color::kBlack, CastlingDirection::kRight),
      value_it);
  SPIEL_CHECK_EQ(value_it, values.end());
}
References Board(), open_spiel::chess::ColorToPlayer(), open_spiel::chess::kBlack, open_spiel::chess::kEmpty, open_spiel::chess::kLeft, open_spiel::chess::kRight, open_spiel::chess::kWhite, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
operator=()
ChessState & open_spiel::chess::ChessState::operator= (const ChessState &) default
ParseMoveToAction()
Action open_spiel::chess::ChessState::ParseMoveToAction (const std::string & move_str) const
Definition at line 108 of file chess.cc.
{
  absl::optional<Move> move = Board().ParseMove(move_str);
  if (!move.has_value()) {
    return kInvalidAction;
  }
  return MoveToAction(*move, BoardSize());
}
References Board(), BoardSize(), open_spiel::kInvalidAction, open_spiel::chess::MoveToAction(), and open_spiel::chess::ChessBoard::ParseMove().
Referenced by open_spiel::uci::RandomUciBot().
Returns()
std::vector< double > open_spiel::chess::ChessState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 301 of file chess.cc.
{
  auto maybe_final_returns = MaybeFinalReturns();
  if (maybe_final_returns) {
    return *maybe_final_returns;
  } else {
    return {0.0, 0.0};
  }
}
Serialize()
std::string open_spiel::chess::ChessState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 427 of file chess.cc.
{
  std::string state_str = "";
  absl::StrAppend(&state_str, "FEN: ", start_board_.ToFEN(), "\n");
  absl::StrAppend(&state_str, absl::StrJoin(History(), "\n"), "\n");
  return state_str;
}
References open_spiel::State::History(), absl::StrAppend(), absl::StrJoin(), and open_spiel::chess::ChessBoard::ToFEN().
StartBoard() [1/2]
ChessBoard & open_spiel::chess::ChessState::StartBoard () inline
Definition at line 160 of file chess.h.
{ return start_board_; }
StartBoard() [2/2]
const ChessBoard & open_spiel::chess::ChessState::StartBoard () const inline
Definition at line 161 of file chess.h.
{ return start_board_; }
ToString()
std::string open_spiel::chess::ChessState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 299 of file chess.cc.
{ return Board().ToFEN(); }
References Board(), and open_spiel::chess::ChessBoard::ToFEN().
Referenced by ObservationString().
UndoAction()
void open_spiel::chess::ChessState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 372 of file chess.cc.
{
  // TODO: Make this fast by storing undo info in another stack.
  SPIEL_CHECK_GE(moves_history_.size(), 1);
  --repetitions_[current_board_.HashValue()];
  moves_history_.pop_back();
  history_.pop_back();
  --move_number_;
  current_board_ = start_board_;
  for (const Move& move : moves_history_) {
    current_board_.ApplyMove(move);
  }
}
References open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::chess::ChessBoard::HashValue(), open_spiel::State::history_, open_spiel::State::move_number_, and SPIEL_CHECK_GE.
The documentation for this class was generated from the following files:
open_spiel/games/chess/chess.h
open_spiel/games/chess/chess.cc