open spiel: open_spiel::Logger Class Reference
open_spiel::Logger Class Reference abstract
#include <logger.h>
Public Member Functions
virtual ~Logger ()=default
virtual void Print (const std::string &str)=0
template<typename Arg1 , typename... Args>
void Print (const absl::FormatSpec< Arg1, Args... > &format, const Arg1 &arg1, const Args &... args)
Detailed Description
Definition at line 28 of file logger.h.
Constructor & Destructor Documentation
~Logger()
virtual open_spiel::Logger::~Logger () virtual default
Member Function Documentation
Print() [1/2]
template<typename Arg1 , typename... Args> void open_spiel::Logger::Print (const absl::FormatSpec< Arg1, Args... > & format, const Arg1 & arg1, const Args &... args) inline
Definition at line 35 of file logger.h.
{
    Print(absl::StrFormat(format, arg1, args...));
  }
References Print(), and absl::StrFormat().
Print() [2/2]
virtual void open_spiel::Logger::Print (const std::string & str) pure virtual
Implemented in open_spiel::FileLogger, and open_spiel::NoopLogger.
Referenced by open_spiel::algorithms::torch_az::PlayGame(), and Print().
The documentation for this class was generated from the following file:
open_spiel/utils/logger.h