open spiel: open_spiel::leduc_poker::LeducState Class Reference
open_spiel::leduc_poker::LeducState Class Reference
#include <leduc_poker.h>
Public Member Functions
LeducState (std::shared_ptr< const Game > game, bool action_mapping, bool suit_isomorphism)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
int round () const
int deck_size () const
int public_card () const
int raises () const
int private_card (Player player) const
std::vector< Action > LegalActions () const override
std::vector< int > GetPrivateCards () const
int GetPublicCard () const
int GetPot () const
std::vector< double > GetMoney () const
std::vector< int > GetRound1 () const
std::vector< int > GetRound2 () const
void SetPrivateCards (const std::vector< int > &new_private_cards)
std::vector< int > padded_betting_sequence () const
std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const override
std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Friends
class LeducObserver
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 72 of file leduc_poker.h.
Constructor & Destructor Documentation
LeducState()
open_spiel::leduc_poker::LeducState::LeducState (std::shared_ptr< const Game > game, bool action_mapping, bool suit_isomorphism) explicit
Definition at line 242 of file leduc_poker.cc.
    : State(game),
      cur_player_(kChancePlayerId),
      num_calls_(0),
      num_raises_(0),
      round_(1),   // Round number (1 or 2).
      stakes_(1),  // The current 'level' of the bet.
      num_winners_(-1),
      pot_(kAnte * game->NumPlayers()),  // Number of chips in the pot.
      public_card_(kInvalidCard),
      // Number of cards remaining; not equal deck_.size()!
      deck_size_((game->NumPlayers() + 1) * kNumSuits),
      private_cards_dealt_(0),
      remaining_players_(game->NumPlayers()),
      // Is this player a winner? Indexed by pid.
      winner_(game->NumPlayers(), false),
      // Each player's single private card. Indexed by pid.
      private_cards_(game->NumPlayers(), kInvalidCard),
      // How much money each player has, indexed by pid.
      money_(game->NumPlayers(), kStartingMoney - kAnte),
      // How much each player has contributed to the pot, indexed by pid.
      ante_(game->NumPlayers(), kAnte),
      // Flag for whether the player has folded, indexed by pid.
      folded_(game->NumPlayers(), false),
      // Sequence of actions for each round. Needed to report information
      // state.
      round1_sequence_(),
      round2_sequence_(),
      // Always regard all actions as legal, and internally map otherwise
      // illegal actions to check/call.
      action_mapping_(action_mapping),
      // Players cannot distinguish between cards of different suits with the
      // same rank.
      suit_isomorphism_(suit_isomorphism) {
  // Cards by value (0-6 for standard 2-player game, kInvalidCard if no longer
  // in the deck.)
  deck_.resize(deck_size_);
  std::iota(deck_.begin(), deck_.end(), 0);
}
Referenced by Clone().
Member Function Documentation
ActionsConsistentWithInformationFrom()
std::vector< Action > open_spiel::leduc_poker::LeducState::ActionsConsistentWithInformationFrom (Action action) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 127 of file leduc_poker.h.
{
    return {action};
  }
References action.
ActionToString()
std::string open_spiel::leduc_poker::LeducState::ActionToString (Player player, Action move) const override virtual
Implements open_spiel::State.
Definition at line 455 of file leduc_poker.cc.
{
  return GetGame()->ActionToString(player, move);
}
References open_spiel::State::GetGame(), and player.
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::leduc_poker::LeducState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 537 of file leduc_poker.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  std::vector<std::pair<Action, double>> outcomes;
  if (suit_isomorphism_) {
    const double p = 1.0 / deck_size_;
    // Consecutive cards in deck are viewed identically.
    for (int card = 0; card < deck_.size() / 2; card++) {
      if (deck_[card * 2] != kInvalidCard &&
          deck_[card * 2 + 1] != kInvalidCard) {
        outcomes.push_back({card, p * 2});
      } else if (deck_[card * 2] != kInvalidCard ||
                 deck_[card * 2 + 1] != kInvalidCard) {
        outcomes.push_back({card, p});
      }
    }
    return outcomes;
  }
  const double p = 1.0 / deck_size_;
  for (int card = 0; card < deck_.size(); card++) {
    // This card is still in the deck, prob is 1/decksize.
    if (deck_[card] != kInvalidCard) outcomes.push_back({card, p});
  }
  return outcomes;
}
References open_spiel::State::IsChanceNode(), open_spiel::leduc_poker::kInvalidCard, and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::leduc_poker::LeducState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 533 of file leduc_poker.cc.
{
  return std::unique_ptr<State>(new LeducState(*this));
}
References LeducState().
CurrentPlayer()
int open_spiel::leduc_poker::LeducState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 283 of file leduc_poker.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  } else {
    return cur_player_;
  }
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
deck_size()
int open_spiel::leduc_poker::LeducState::deck_size () const inline
Definition at line 94 of file leduc_poker.h.
{ return deck_size_; }
DoApplyAction()
void open_spiel::leduc_poker::LeducState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 294 of file leduc_poker.cc.
{
  if (IsChanceNode()) {
    SPIEL_CHECK_GE(move, 0);
    SPIEL_CHECK_LT(move, deck_.size());
    if (suit_isomorphism_) {
      // One of the two identical cards must be left in the deck.
      SPIEL_CHECK_TRUE(deck_[move * 2] != kInvalidCard ||
                       deck_[move * 2 + 1] != kInvalidCard);
    } else {
      SPIEL_CHECK_NE(deck_[move], kInvalidCard);
    }
    if (private_cards_dealt_ < num_players_) {
      SetPrivate(private_cards_dealt_, move);
    } else {
      // Round 2: A single public card.
      if (suit_isomorphism_) {
        public_card_ = move;
        if (deck_[move * 2] != kInvalidCard) {
          deck_[move * 2] = kInvalidCard;
        } else if (deck_[move * 2 + 1] != kInvalidCard) {
          deck_[move * 2 + 1] = kInvalidCard;
        } else {
          SpielFatalError("Suit isomorphism error.");
        }
        deck_size_--;
      } else {
        public_card_ = deck_[move];
        deck_[move] = kInvalidCard;
        deck_size_--;
      }
      // We have finished the public card, let's bet!
      cur_player_ = NextPlayer();
    }
  } else {
    // Player node.
    if (action_mapping_) {
      // Map otherwise illegal actions to kCall.
      if (move == ActionType::kFold) {
        if (stakes_ <= ante_[cur_player_]) {
          move = ActionType::kCall;
        }
      } else if (move == ActionType::kRaise) {
        if (num_raises_ >= 2) {
          move = ActionType::kCall;
        }
      }
    }
    if (move == ActionType::kFold) {
      SPIEL_CHECK_NE(cur_player_, kChancePlayerId);
      SequenceAppendMove(ActionType::kFold);
      // Player is now out.
      folded_[cur_player_] = true;
      remaining_players_--;
      if (IsTerminal()) {
        ResolveWinner();
      } else if (ReadyForNextRound()) {
        NewRound();
      } else {
        cur_player_ = NextPlayer();
      }
    } else if (move == ActionType::kCall) {
      SPIEL_CHECK_NE(cur_player_, kChancePlayerId);
      // Current player puts in an amount of money equal to the current level
      // (stakes) minus what they have contributed to level their contribution
      // off. Note: this action also acts as a 'check' where the stakes are
      // equal to each player's ante.
      SPIEL_CHECK_GE(stakes_, ante_[cur_player_]);
      int amount = stakes_ - ante_[cur_player_];
      Ante(cur_player_, amount);
      num_calls_++;
      SequenceAppendMove(ActionType::kCall);
      if (IsTerminal()) {
        ResolveWinner();
      } else if (ReadyForNextRound()) {
        NewRound();
      } else {
        cur_player_ = NextPlayer();
      }
    } else if (move == ActionType::kRaise) {
      SPIEL_CHECK_NE(cur_player_, kChancePlayerId);
      // This player matches the current stakes and then brings the stakes up.
      SPIEL_CHECK_LT(num_raises_, kMaxRaises);
      int call_amount = stakes_ - ante_[cur_player_];
      // First, match the current stakes if necessary
      SPIEL_CHECK_GE(call_amount, 0);
      if (call_amount > 0) {
        Ante(cur_player_, call_amount);
      }
      // Now, raise the stakes.
      int raise_amount = (round_ == 1 ? kFirstRaiseAmount : kSecondRaiseAmount);
      stakes_ += raise_amount;
      Ante(cur_player_, raise_amount);
      num_raises_++;
      num_calls_ = 0;
      SequenceAppendMove(ActionType::kRaise);
      if (IsTerminal()) {
        ResolveWinner();
      } else {
        cur_player_ = NextPlayer();
      }
    } else {
      SpielFatalError(absl::StrCat("Move ", move, " is invalid. ChanceNode?",
                                   IsChanceNode()));
    }
  }
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::leduc_poker::kCall, open_spiel::kChancePlayerId, open_spiel::leduc_poker::kFirstRaiseAmount, open_spiel::leduc_poker::kFold, open_spiel::leduc_poker::kInvalidCard, open_spiel::leduc_poker::kMaxRaises, open_spiel::leduc_poker::kRaise, open_spiel::leduc_poker::kSecondRaiseAmount, open_spiel::State::num_players_, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_NE, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), and absl::StrCat().
GetMoney()
std::vector< double > open_spiel::leduc_poker::LeducState::GetMoney () const inline
Definition at line 110 of file leduc_poker.h.
{ return money_; }
GetPot()
int open_spiel::leduc_poker::LeducState::GetPot () const inline
Definition at line 107 of file leduc_poker.h.
{ return pot_; }
GetPrivateCards()
std::vector< int > open_spiel::leduc_poker::LeducState::GetPrivateCards () const inline
Definition at line 101 of file leduc_poker.h.
{ return private_cards_; }
GetPublicCard()
int open_spiel::leduc_poker::LeducState::GetPublicCard () const inline
Definition at line 104 of file leduc_poker.h.
{ return public_card_; }
GetRound1()
std::vector< int > open_spiel::leduc_poker::LeducState::GetRound1 () const inline
Definition at line 113 of file leduc_poker.h.
{ return round1_sequence_; }
GetRound2()
std::vector< int > open_spiel::leduc_poker::LeducState::GetRound2 () const inline
Definition at line 114 of file leduc_poker.h.
{ return round2_sequence_; }
InformationStateString()
std::string open_spiel::leduc_poker::LeducState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 508 of file leduc_poker.cc.
{
  const LeducGame& game = open_spiel::down_cast<const LeducGame&>(*game_);
  return game.info_state_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
InformationStateTensor()
void open_spiel::leduc_poker::LeducState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 519 of file leduc_poker.cc.
{
  ContiguousAllocator allocator(values);
  const LeducGame& game = open_spiel::down_cast<const LeducGame&>(*game_);
  game.info_state_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
IsTerminal()
bool open_spiel::leduc_poker::LeducState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 489 of file leduc_poker.cc.
{
  return remaining_players_ == 1 || (round_ == 2 && ReadyForNextRound());
}
Referenced by CurrentPlayer(), DoApplyAction(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::leduc_poker::LeducState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 412 of file leduc_poker.cc.
{
  if (IsTerminal()) return {};
  std::vector<Action> movelist;
  if (IsChanceNode()) {
    if (suit_isomorphism_) {
      // Consecutive cards are identical under suit isomorphism.
      for (int card = 0; card < deck_.size() / 2; card++) {
        if (deck_[card * 2] != kInvalidCard ||
            deck_[card * 2 + 1] != kInvalidCard) {
          movelist.push_back(card);
        }
      }
    } else {
      for (int card = 0; card < deck_.size(); card++) {
        if (deck_[card] != kInvalidCard) movelist.push_back(card);
      }
    }
    return movelist;
  }
  if (action_mapping_) {
    // All actions are regarded as legal
    movelist.push_back(ActionType::kFold);
    movelist.push_back(ActionType::kCall);
    movelist.push_back(ActionType::kRaise);
    return movelist;
  }
  // Can't just randomly fold; only allow fold when under pressure.
  if (stakes_ > ante_[cur_player_]) {
    movelist.push_back(ActionType::kFold);
  }
  // Can always call/check
  movelist.push_back(ActionType::kCall);
  if (num_raises_ < 2) {
    movelist.push_back(ActionType::kRaise);
  }
  return movelist;
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::leduc_poker::kCall, open_spiel::leduc_poker::kFold, open_spiel::leduc_poker::kInvalidCard, and open_spiel::leduc_poker::kRaise.
ObservationString()
std::string open_spiel::leduc_poker::LeducState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 514 of file leduc_poker.cc.
{
  const LeducGame& game = open_spiel::down_cast<const LeducGame&>(*game_);
  return game.default_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
ObservationTensor()
void open_spiel::leduc_poker::LeducState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 526 of file leduc_poker.cc.
{
  ContiguousAllocator allocator(values);
  const LeducGame& game = open_spiel::down_cast<const LeducGame&>(*game_);
  game.default_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
padded_betting_sequence()
std::vector< int > open_spiel::leduc_poker::LeducState::padded_betting_sequence () const
Definition at line 701 of file leduc_poker.cc.
{
  std::vector<int> history = round1_sequence_;
  // We pad the history to the end of the first round with kPaddingAction.
  history.resize(game_->MaxGameLength() / 2, kInvalidAction);
  // We insert the actions that happened in the second round, and fill to
  // MaxGameLength.
  history.insert(history.end(), round2_sequence_.begin(),
                 round2_sequence_.end());
  history.resize(game_->MaxGameLength(), kInvalidAction);
  return history;
}
References open_spiel::State::game_, and open_spiel::kInvalidAction.
private_card()
int open_spiel::leduc_poker::LeducState::private_card (Player player) const inline
Definition at line 97 of file leduc_poker.h.
{ return private_cards_[player]; }
References player.
public_card()
int open_spiel::leduc_poker::LeducState::public_card () const inline
Definition at line 95 of file leduc_poker.h.
{ return public_card_; }
raises()
int open_spiel::leduc_poker::LeducState::raises () const inline
Definition at line 96 of file leduc_poker.h.
{ return num_raises_; }
ResampleFromInfostate()
std::unique_ptr< State > open_spiel::leduc_poker::LeducState::ResampleFromInfostate (int player_id, std::function< double()> rng) const override virtual
Reimplemented from open_spiel::State.
Definition at line 739 of file leduc_poker.cc.
{
  std::unique_ptr<State> clone = game_->NewInitialState();
  // First, deal out cards:
  Action player_chance = history_.at(player_id).action;
  for (int p = 0; p < GetGame()->NumPlayers(); ++p) {
    if (p == player_id) {
      clone->ApplyAction(history_.at(p).action);
    } else {
      Action chosen_action = player_chance;
      while (chosen_action == player_chance || chosen_action == public_card_) {
        chosen_action = SampleAction(clone->ChanceOutcomes(), rng()).first;
      }
      clone->ApplyAction(chosen_action);
    }
  }
  for (int action : round1_sequence_) clone->ApplyAction(action);
  if (public_card_ != kInvalidCard) {
    clone->ApplyAction(public_card_);
    for (int action : round2_sequence_) clone->ApplyAction(action);
  }
  return clone;
}
References action, open_spiel::State::game_, open_spiel::State::GetGame(), open_spiel::State::history_, open_spiel::leduc_poker::kInvalidCard, and open_spiel::SampleAction().
Returns()
std::vector< double > open_spiel::leduc_poker::LeducState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 493 of file leduc_poker.cc.
{
  if (!IsTerminal()) {
    return std::vector<double>(num_players_, 0.0);
  }
  std::vector<double> returns(num_players_);
  for (auto player = Player{0}; player < num_players_; ++player) {
    // Money vs money at start.
    returns[player] = money_[player] - kStartingMoney;
  }
  return returns;
}
References IsTerminal(), open_spiel::leduc_poker::kStartingMoney, open_spiel::State::num_players_, and player.
round()
int open_spiel::leduc_poker::LeducState::round () const inline
Definition at line 93 of file leduc_poker.h.
{ return round_; }
SetPrivateCards()
void open_spiel::leduc_poker::LeducState::SetPrivateCards (const std::vector< int > & new_private_cards)
Definition at line 770 of file leduc_poker.cc.
{
  SPIEL_CHECK_EQ(new_private_cards.size(), NumPlayers());
  private_cards_ = new_private_cards;
}
References open_spiel::State::NumPlayers(), and SPIEL_CHECK_EQ.
ToString()
std::string open_spiel::leduc_poker::LeducState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 459 of file leduc_poker.cc.
{
  std::string result;
  absl::StrAppend(&result, "Round: ", round_, "\nPlayer: ", cur_player_,
                  "\nPot: ", pot_, "\nMoney (p1 p2 ...):");
  for (auto p = Player{0}; p < num_players_; p++) {
    absl::StrAppend(&result, " ", money_[p]);
  }
  absl::StrAppend(&result, "\nCards (public p1 p2 ...): ", public_card_, " ");
  for (Player player_index = 0; player_index < num_players_; player_index++) {
    absl::StrAppend(&result, private_cards_[player_index], " ");
  }
  absl::StrAppend(&result, "\nRound 1 sequence: ");
  for (int i = 0; i < round1_sequence_.size(); ++i) {
    Action action = round1_sequence_[i];
    if (i > 0) absl::StrAppend(&result, ", ");
    absl::StrAppend(&result, StatelessActionToString(action));
  }
  absl::StrAppend(&result, "\nRound 2 sequence: ");
  for (int i = 0; i < round2_sequence_.size(); ++i) {
    Action action = round2_sequence_[i];
    if (i > 0) absl::StrAppend(&result, ", ");
    absl::StrAppend(&result, StatelessActionToString(action));
  }
  absl::StrAppend(&result, "\n");
  return result;
}
References action, i, open_spiel::State::num_players_, and absl::StrAppend().
Friends And Related Symbol Documentation
LeducObserver
friend class LeducObserver friend
Definition at line 152 of file leduc_poker.h.
The documentation for this class was generated from the following files:
open_spiel/games/leduc_poker/leduc_poker.h
open_spiel/games/leduc_poker/leduc_poker.cc