open spiel: open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator Class Reference
open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator Class Reference
Public Member Functions
__init__ (self, game, model, cache_size=2 **16)
cache_info (self)
clear_cache (self)
evaluate (self, state)
prior (self, state)
Protected Member Functions
_inference (self, state)
Protected Attributes
_model
_cache
Detailed Description
An AlphaZero MCTS Evaluator.
Definition at line 24 of file evaluator.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator.__init__ (self, game, model, cache_size = 2**16)
An AlphaZero MCTS Evaluator.
Definition at line 27 of file evaluator.py.
  def __init__(self, game, model, cache_size=2**16):
    """An AlphaZero MCTS Evaluator."""
    if game.num_players() != 2:
      raise ValueError("Game must be for two players.")
    game_type = game.get_type()
    if game_type.reward_model != pyspiel.GameType.RewardModel.TERMINAL:
      raise ValueError("Game must have terminal rewards.")
    if game_type.dynamics != pyspiel.GameType.Dynamics.SEQUENTIAL:
      raise ValueError("Game must have sequential turns.")
    self._model = model
    self._cache = lru_cache.LRUCache(cache_size)
Member Function Documentation
_inference()
open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._inference (self, state) protected
Definition at line 46 of file evaluator.py.
  def _inference(self, state):
    # Make a singleton batch
    obs = np.expand_dims(state.observation_tensor(), 0)
    mask = np.expand_dims(state.legal_actions_mask(), 0)
    # ndarray isn't hashable
    cache_key = obs.tobytes() + mask.tobytes()
    value, policy = self._cache.make(
        cache_key, lambda: self._model.inference(obs, mask))
    return value[0, 0], policy[0]  # Unpack batch
References open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._cache, and open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._model.
Referenced by open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator.evaluate(), and open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator.prior().
cache_info()
open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator.cache_info (self)
Definition at line 40 of file evaluator.py.
  def cache_info(self):
    return self._cache.info()
References open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._cache.
clear_cache()
open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator.clear_cache (self)
Definition at line 43 of file evaluator.py.
  def clear_cache(self):
    self._cache.clear()
References open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._cache.
evaluate()
open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator.evaluate (self, state)
Returns a value for the given state.
Reimplemented from open_spiel.python.algorithms.mcts.Evaluator.
Definition at line 59 of file evaluator.py.
  def evaluate(self, state):
    """Returns a value for the given state."""
    value, _ = self._inference(state)
    return np.array([value, -value])
References open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._inference().
prior()
open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator.prior (self, state)
Returns a probability for each legal action in the given state.
Reimplemented from open_spiel.python.algorithms.mcts.Evaluator.
Definition at line 64 of file evaluator.py.
  def prior(self, state):
    if state.is_chance_node():
      return state.chance_outcomes()
    else:
      # Returns the probabilities for all actions.
      _, policy = self._inference(state)
      return [(action, policy[action]) for action in state.legal_actions()]
References open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._inference().
Referenced by open_spiel.python.algorithms.mcts.SearchNode.puct_value(), and open_spiel.python.algorithms.mcts.SearchNode.to_str().
Member Data Documentation
_cache
open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._cache protected
Definition at line 38 of file evaluator.py.
Referenced by open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._inference(), open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator.cache_info(), and open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator.clear_cache().
_model
open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._model protected
Definition at line 37 of file evaluator.py.
Referenced by open_spiel.python.algorithms.alpha_zero.evaluator.AlphaZeroEvaluator._inference().
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/alpha_zero/evaluator.py