open spiel: open_spiel::algorithms::TabularBestResponseMDP Class Reference
open_spiel::algorithms::TabularBestResponseMDP Class Reference
#include <tabular_best_response_mdp.h>
Public Member Functions
TabularBestResponseMDP (const Game &game, const Policy &fixed_policy)
TabularBestResponseMDPInfo ComputeBestResponses ()
TabularBestResponseMDPInfo NashConv ()
TabularBestResponseMDPInfo Exploitability ()
TabularBestResponseMDPInfo ComputeBestResponse (Player max_player)
int TotalNumNonterminals () const
int TotalSize () const
Detailed Description
Definition at line 141 of file tabular_best_response_mdp.h.
Constructor & Destructor Documentation
TabularBestResponseMDP()
open_spiel::algorithms::TabularBestResponseMDP::TabularBestResponseMDP (const Game & game, const Policy & fixed_policy)
Definition at line 312 of file tabular_best_response_mdp.cc.
    : game_(game), fixed_policy_(fixed_policy),
      num_players_(game.NumPlayers()) {}
Member Function Documentation
ComputeBestResponse()
TabularBestResponseMDPInfo open_spiel::algorithms::TabularBestResponseMDP::ComputeBestResponse (Player max_player)
Definition at line 363 of file tabular_best_response_mdp.cc.
{
  TabularBestResponseMDPInfo br_info(num_players_);
  if (mdps_.empty()) {
    mdps_.resize(num_players_);
    mdps_[max_player] = absl::make_unique<MDP>();
  }
  std::vector<MDPNode*> parent_nodes(num_players_, nullptr);
  parent_nodes[max_player] = mdps_[max_player]->RootNode();
  std::vector<double> reach_probs(num_players_ + 1, 1.0);  // include chance.
  std::vector<Action> parent_actions(num_players_, 0);
  std::unique_ptr<State> initial_state = game_.NewInitialState();
  BuildMDPs(*initial_state, reach_probs, parent_nodes, parent_actions,
            max_player);
  br_info.br_values[max_player] =
        mdps_[max_player]->Solve(kSolveTolerance,
                                 &br_info.br_policies[max_player]);
  return br_info;
}
References open_spiel::algorithms::TabularBestResponseMDPInfo::br_policies, open_spiel::algorithms::TabularBestResponseMDPInfo::br_values, and open_spiel::Game::NewInitialState().
ComputeBestResponses()
TabularBestResponseMDPInfo open_spiel::algorithms::TabularBestResponseMDP::ComputeBestResponses ()
Definition at line 333 of file tabular_best_response_mdp.cc.
{
  TabularBestResponseMDPInfo br_info(num_players_);
  // Initialize IS-MDPs for each player, if necessary.
  if (mdps_.empty()) {
    for (Player p = 0; p < num_players_; p++) {
      mdps_.push_back(absl::make_unique<MDP>());
    }
  }
  std::vector<MDPNode*> parent_nodes;
  parent_nodes.reserve(num_players_);
  for (Player p = 0; p < num_players_; p++) {
    parent_nodes.push_back(mdps_[p]->RootNode());
  }
  std::vector<double> reach_probs(num_players_ + 1, 1.0);  // include chance.
  std::vector<Action> parent_actions(num_players_, 0);
  std::unique_ptr<State> initial_state = game_.NewInitialState();
  BuildMDPs(*initial_state, reach_probs, parent_nodes, parent_actions);
  for (Player p = 0; p < num_players_; p++) {
    br_info.br_values[p] =
        mdps_[p]->Solve(kSolveTolerance, &br_info.br_policies[p]);
  }
  return br_info;
}
References open_spiel::algorithms::TabularBestResponseMDPInfo::br_policies, open_spiel::algorithms::TabularBestResponseMDPInfo::br_values, and open_spiel::Game::NewInitialState().
Referenced by Exploitability(), and NashConv().
Exploitability()
TabularBestResponseMDPInfo open_spiel::algorithms::TabularBestResponseMDP::Exploitability ()
Definition at line 400 of file tabular_best_response_mdp.cc.
{
  SPIEL_CHECK_TRUE(game_.GetType().utility == GameType::Utility::kZeroSum ||
                   game_.GetType().utility == GameType::Utility::kConstantSum);
  TabularBestResponseMDPInfo br_info = ComputeBestResponses();
  br_info.nash_conv = absl::c_accumulate(br_info.br_values, 0.0);
  br_info.exploitability =
      (br_info.nash_conv - *game_.UtilitySum()) / num_players_;
  return br_info;
}
References open_spiel::algorithms::TabularBestResponseMDPInfo::br_values, absl::c_accumulate(), ComputeBestResponses(), open_spiel::algorithms::TabularBestResponseMDPInfo::exploitability, open_spiel::Game::GetType(), open_spiel::GameType::kConstantSum, open_spiel::GameType::kZeroSum, open_spiel::algorithms::TabularBestResponseMDPInfo::nash_conv, SPIEL_CHECK_TRUE, open_spiel::GameType::utility, and open_spiel::Game::UtilitySum().
NashConv()
TabularBestResponseMDPInfo open_spiel::algorithms::TabularBestResponseMDP::NashConv ()
Definition at line 386 of file tabular_best_response_mdp.cc.
{
  TabularBestResponseMDPInfo br_info = ComputeBestResponses();
  std::unique_ptr<State> state = game_.NewInitialState();
  br_info.on_policy_values =
      ExpectedReturns(*state, fixed_policy_,
                      /*depth_limit*/ -1, /*use_infostate_get_policy*/ false);
  for (Player p = 0; p < num_players_; ++p) {
    br_info.deviation_incentives[p] =
        br_info.br_values[p] - br_info.on_policy_values[p];
    br_info.nash_conv += br_info.deviation_incentives[p];
  }
  return br_info;
}
References open_spiel::algorithms::TabularBestResponseMDPInfo::br_values, ComputeBestResponses(), open_spiel::algorithms::TabularBestResponseMDPInfo::deviation_incentives, open_spiel::algorithms::ExpectedReturns(), open_spiel::algorithms::TabularBestResponseMDPInfo::nash_conv, open_spiel::Game::NewInitialState(), open_spiel::algorithms::TabularBestResponseMDPInfo::on_policy_values, and state.
TotalNumNonterminals()
int open_spiel::algorithms::TabularBestResponseMDP::TotalNumNonterminals () const
Definition at line 317 of file tabular_best_response_mdp.cc.
{
  int total_num_nonterminals = 0;
  for (Player p = 0; p < num_players_; ++p) {
    total_num_nonterminals += mdps_[p]->NumNonTerminalNodes();
  }
  return total_num_nonterminals;
}
TotalSize()
int open_spiel::algorithms::TabularBestResponseMDP::TotalSize () const
Definition at line 325 of file tabular_best_response_mdp.cc.
{
  int total_size = 0;
  for (Player p = 0; p < num_players_; ++p) {
    total_size += mdps_[p]->TotalSize();
  }
  return total_size;
}
The documentation for this class was generated from the following files:
open_spiel/algorithms/tabular_best_response_mdp.h
open_spiel/algorithms/tabular_best_response_mdp.cc