open spiel: absl::profiling_internal::ExponentialBiased Class Reference
absl::profiling_internal::ExponentialBiased Class Reference
#include <exponential_biased.h>
Public Member Functions
int64_t GetSkipCount (int64_t mean)
int64_t GetStride (int64_t mean)
Static Public Member Functions
static uint64_t NextRandom (uint64_t rnd)
Static Public Attributes
static constexpr int kPrngNumBits = 48
Detailed Description
Definition at line 74 of file exponential_biased.h.
Member Function Documentation
GetSkipCount()
int64_t absl::profiling_internal::ExponentialBiased::GetSkipCount (int64_t mean)
Definition at line 41 of file exponential_biased.cc.
{
  if (ABSL_PREDICT_FALSE(!initialized_)) {
    Initialize();
  }
  uint64_t rng = NextRandom(rng_);
  rng_ = rng;
  // Take the top 26 bits as the random number
  // (This plus the 1<<58 sampling bound give a max possible step of
  // 5194297183973780480 bytes.)
  // The uint32_t cast is to prevent a (hard-to-reproduce) NAN
  // under piii debug for some binaries.
  double q = static_cast<uint32_t>(rng >> (kPrngNumBits - 26)) + 1.0;
  // Put the computed p-value through the CDF of a geometric.
  double interval = bias_ + (std::log2(q) - 26) * (-std::log(2.0) * mean);
  // Very large values of interval overflow int64_t. To avoid that, we will
  // cheat and clamp any huge values to (int64_t max)/2. This is a potential
  // source of bias, but the mean would need to be such a large value that it's
  // not likely to come up. For example, with a mean of 1e18, the probability of
  // hitting this condition is about 1/1000. For a mean of 1e17, standard
  // calculators claim that this event won't happen.
  if (interval > static_cast<double>(std::numeric_limits<int64_t>::max() / 2)) {
    // Assume huge values are bias neutral, retain bias for next call.
    return std::numeric_limits<int64_t>::max() / 2;
  }
  double value = std::rint(interval);
  bias_ = interval - value;
  return value;
}
References ABSL_PREDICT_FALSE, kPrngNumBits, NextRandom(), and value.
Referenced by GetStride().
GetStride()
int64_t absl::profiling_internal::ExponentialBiased::GetStride (int64_t mean)
Definition at line 72 of file exponential_biased.cc.
{
  return GetSkipCount(mean - 1) + 1;
}
References GetSkipCount().
NextRandom()
uint64_t absl::profiling_internal::ExponentialBiased::NextRandom (uint64_t rnd) inline static
Definition at line 117 of file exponential_biased.h.
{
  const uint64_t prng_mult = uint64_t{0x5DEECE66D};
  const uint64_t prng_add = 0xB;
  const uint64_t prng_mod_power = 48;
  const uint64_t prng_mod_mask =
      ~((~static_cast<uint64_t>(0)) << prng_mod_power);
  return (prng_mult * rnd + prng_add) & prng_mod_mask;
}
Referenced by GetSkipCount().
Member Data Documentation
kPrngNumBits
int absl::profiling_internal::ExponentialBiased::kPrngNumBits = 48 static constexpr
Definition at line 77 of file exponential_biased.h.
Referenced by GetSkipCount().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/profiling/internal/exponential_biased.h
open_spiel/abseil-cpp/absl/profiling/internal/exponential_biased.cc