open spiel: absl::container_internal::base_checker< TreeType, CheckerType > Class Template Reference
absl::container_internal::base_checker< TreeType, CheckerType > Class Template Reference
Public Types
using key_type = typename TreeType::key_type
using value_type = typename TreeType::value_type
using key_compare = typename TreeType::key_compare
using pointer = typename TreeType::pointer
using const_pointer = typename TreeType::const_pointer
using reference = typename TreeType::reference
using const_reference = typename TreeType::const_reference
using size_type = typename TreeType::size_type
using difference_type = typename TreeType::difference_type
using iterator = typename TreeType::iterator
using const_iterator = typename TreeType::const_iterator
using reverse_iterator = typename TreeType::reverse_iterator
using const_reverse_iterator = typename TreeType::const_reverse_iterator
Public Member Functions
base_checker ()
base_checker (const base_checker &other)
template<typename InputIterator >
base_checker (InputIterator b, InputIterator e)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
template<typename IterType , typename CheckerIterType >
IterType iter_check (IterType tree_iter, CheckerIterType checker_iter) const
template<typename IterType , typename CheckerIterType >
IterType riter_check (IterType tree_iter, CheckerIterType checker_iter) const
void value_check (const value_type &v)
void erase_check (const key_type &key)
iterator lower_bound (const key_type &key)
const_iterator lower_bound (const key_type &key) const
iterator upper_bound (const key_type &key)
const_iterator upper_bound (const key_type &key) const
std::pair< iterator, iterator > equal_range (const key_type &key)
std::pair< const_iterator, const_iterator > equal_range (const key_type &key) const
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
bool contains (const key_type &key) const
size_type count (const key_type &key) const
base_checker & operator= (const base_checker &other)
int erase (const key_type &key)
iterator erase (iterator iter)
void erase (iterator begin, iterator end)
void clear ()
void swap (base_checker &other)
void verify () const
const TreeType & tree () const
size_type size () const
size_type max_size () const
bool empty () const
Protected Attributes
TreeType tree_
const TreeType & const_tree_
CheckerType checker_
Detailed Description
template<typename TreeType, typename CheckerType>
class absl::container_internal::base_checker< TreeType, CheckerType >
Definition at line 94 of file btree_test.cc.
Member Typedef Documentation
const_iterator
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::const_iterator = typename TreeType::const_iterator
Definition at line 106 of file btree_test.cc.
const_pointer
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::const_pointer = typename TreeType::const_pointer
Definition at line 100 of file btree_test.cc.
const_reference
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::const_reference = typename TreeType::const_reference
Definition at line 102 of file btree_test.cc.
const_reverse_iterator
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::const_reverse_iterator = typename TreeType::const_reverse_iterator
Definition at line 108 of file btree_test.cc.
difference_type
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::difference_type = typename TreeType::difference_type
Definition at line 104 of file btree_test.cc.
iterator
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::iterator = typename TreeType::iterator
Definition at line 105 of file btree_test.cc.
key_compare
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::key_compare = typename TreeType::key_compare
Definition at line 98 of file btree_test.cc.
key_type
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::key_type = typename TreeType::key_type
Definition at line 96 of file btree_test.cc.
pointer
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::pointer = typename TreeType::pointer
Definition at line 99 of file btree_test.cc.
reference
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::reference = typename TreeType::reference
Definition at line 101 of file btree_test.cc.
reverse_iterator
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::reverse_iterator = typename TreeType::reverse_iterator
Definition at line 107 of file btree_test.cc.
size_type
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::size_type = typename TreeType::size_type
Definition at line 103 of file btree_test.cc.
value_type
template<typename TreeType , typename CheckerType > using absl::container_internal::base_checker< TreeType, CheckerType >::value_type = typename TreeType::value_type
Definition at line 97 of file btree_test.cc.
Constructor & Destructor Documentation
base_checker() [1/3]
template<typename TreeType , typename CheckerType > absl::container_internal::base_checker< TreeType, CheckerType >::base_checker () inline
Definition at line 111 of file btree_test.cc.
: const_tree_(tree_) {}
base_checker() [2/3]
template<typename TreeType , typename CheckerType > absl::container_internal::base_checker< TreeType, CheckerType >::base_checker (const base_checker< TreeType, CheckerType > & other) inline
Definition at line 112 of file btree_test.cc.
      : tree_(other.tree_), const_tree_(tree_), checker_(other.checker_) {}
base_checker() [3/3]
template<typename TreeType , typename CheckerType > template<typename InputIterator > absl::container_internal::base_checker< TreeType, CheckerType >::base_checker (InputIterator b, InputIterator e) inline
Definition at line 115 of file btree_test.cc.
      : tree_(b, e), const_tree_(tree_), checker_(b, e) {}
Member Function Documentation
begin() [1/2]
template<typename TreeType , typename CheckerType > iterator absl::container_internal::base_checker< TreeType, CheckerType >::begin () inline
Definition at line 118 of file btree_test.cc.
{ return tree_.begin(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::erase().
begin() [2/2]
template<typename TreeType , typename CheckerType > const_iterator absl::container_internal::base_checker< TreeType, CheckerType >::begin () const inline
Definition at line 119 of file btree_test.cc.
{ return tree_.begin(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
clear()
template<typename TreeType , typename CheckerType > void absl::container_internal::base_checker< TreeType, CheckerType >::clear () inline
Definition at line 269 of file btree_test.cc.
               {
    tree_.clear();
    checker_.clear();
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
contains()
template<typename TreeType , typename CheckerType > bool absl::container_internal::base_checker< TreeType, CheckerType >::contains (const key_type & key) const inline
Definition at line 203 of file btree_test.cc.
{ return find(key) != end(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::end(), absl::container_internal::base_checker< TreeType, CheckerType >::find(), and key.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::value_check().
count()
template<typename TreeType , typename CheckerType > size_type absl::container_internal::base_checker< TreeType, CheckerType >::count (const key_type & key) const inline
Definition at line 204 of file btree_test.cc.
{
    size_type res = checker_.count(key);
    EXPECT_EQ(res, tree_.count(key));
    return res;
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_add_to_queue_count_weighted(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_lcb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_ucb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_ucb_standard_factor(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::compute_total_steps(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::delta(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::update_mean_and_count(), and absl::container_internal::base_checker< TreeType, CheckerType >::value_check().
empty()
template<typename TreeType , typename CheckerType > bool absl::container_internal::base_checker< TreeType, CheckerType >::empty () const inline
Definition at line 322 of file btree_test.cc.
                     {
    EXPECT_EQ(tree_.empty(), checker_.empty());
    return tree_.empty();
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
end() [1/2]
template<typename TreeType , typename CheckerType > iterator absl::container_internal::base_checker< TreeType, CheckerType >::end () inline
Definition at line 120 of file btree_test.cc.
{ return tree_.end(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::contains(), and absl::container_internal::base_checker< TreeType, CheckerType >::erase().
end() [2/2]
template<typename TreeType , typename CheckerType > const_iterator absl::container_internal::base_checker< TreeType, CheckerType >::end () const inline
Definition at line 121 of file btree_test.cc.
{ return tree_.end(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
equal_range() [1/2]
template<typename TreeType , typename CheckerType > std::pair< iterator, iterator > absl::container_internal::base_checker< TreeType, CheckerType >::equal_range (const key_type & key) inline
Definition at line 179 of file btree_test.cc.
{
    std::pair<typename CheckerType::iterator, typename CheckerType::iterator>
        checker_res = checker_.equal_range(key);
    std::pair<iterator, iterator> tree_res = tree_.equal_range(key);
    iter_check(tree_res.first, checker_res.first);
    iter_check(tree_res.second, checker_res.second);
    return tree_res;
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::value_check().
equal_range() [2/2]
template<typename TreeType , typename CheckerType > std::pair< const_iterator, const_iterator > absl::container_internal::base_checker< TreeType, CheckerType >::equal_range (const key_type & key) const inline
Definition at line 187 of file btree_test.cc.
{
    std::pair<typename CheckerType::const_iterator,
              typename CheckerType::const_iterator>
        checker_res = checker_.equal_range(key);
    std::pair<const_iterator, const_iterator> tree_res = tree_.equal_range(key);
    iter_check(tree_res.first, checker_res.first);
    iter_check(tree_res.second, checker_res.second);
    return tree_res;
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
erase() [1/3]
template<typename TreeType , typename CheckerType > int absl::container_internal::base_checker< TreeType, CheckerType >::erase (const key_type & key) inline
Definition at line 216 of file btree_test.cc.
{
    int size = tree_.size();
    int res = checker_.erase(key);
    EXPECT_EQ(res, tree_.count(key));
    EXPECT_EQ(res, tree_.erase(key));
    EXPECT_EQ(tree_.count(key), 0);
    EXPECT_EQ(tree_.size(), size - res);
    erase_check(key);
    return res;
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::erase_check(), key, absl::container_internal::base_checker< TreeType, CheckerType >::size(), and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
erase() [2/3]
template<typename TreeType , typename CheckerType > void absl::container_internal::base_checker< TreeType, CheckerType >::erase (iterator begin, iterator end) inline
Definition at line 247 of file btree_test.cc.
{
    int size = tree_.size();
    int count = std::distance(begin, end);
    auto checker_begin = checker_.lower_bound(begin.key());
    for (iterator tmp(tree_.lower_bound(begin.key())); tmp != begin; ++tmp) {
      ++checker_begin;
    }
    auto checker_end =
        end == tree_.end() ? checker_.end() : checker_.lower_bound(end.key());
    if (end != tree_.end()) {
      for (iterator tmp(tree_.lower_bound(end.key())); tmp != end; ++tmp) {
        ++checker_end;
      }
    }
    const auto checker_ret = checker_.erase(checker_begin, checker_end);
    const auto tree_ret = tree_.erase(begin, end);
    EXPECT_EQ(std::distance(checker_.begin(), checker_ret),
              std::distance(tree_.begin(), tree_ret));
    EXPECT_EQ(tree_.size(), checker_.size());
    EXPECT_EQ(tree_.size(), size - count);
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::begin(), absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::count(), absl::container_internal::base_checker< TreeType, CheckerType >::end(), absl::container_internal::base_checker< TreeType, CheckerType >::size(), and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
erase() [3/3]
template<typename TreeType , typename CheckerType > iterator absl::container_internal::base_checker< TreeType, CheckerType >::erase (iterator iter) inline
Definition at line 226 of file btree_test.cc.
{
    key_type key = iter.key();
    int size = tree_.size();
    int count = tree_.count(key);
    auto checker_iter = checker_.lower_bound(key);
    for (iterator tmp(tree_.lower_bound(key)); tmp != iter; ++tmp) {
      ++checker_iter;
    }
    auto checker_next = checker_iter;
    ++checker_next;
    checker_.erase(checker_iter);
    iter = tree_.erase(iter);
    EXPECT_EQ(tree_.size(), checker_.size());
    EXPECT_EQ(tree_.size(), size - 1);
    EXPECT_EQ(tree_.count(key), count - 1);
    if (count == 1) {
      erase_check(key);
    }
    return iter_check(iter, checker_next);
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::count(), absl::container_internal::base_checker< TreeType, CheckerType >::erase_check(), absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), key, absl::container_internal::base_checker< TreeType, CheckerType >::size(), and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
erase_check()
template<typename TreeType , typename CheckerType > void absl::container_internal::base_checker< TreeType, CheckerType >::erase_check (const key_type & key) inline
Definition at line 158 of file btree_test.cc.
{
    EXPECT_FALSE(tree_.contains(key));
    EXPECT_EQ(tree_.find(key), const_tree_.end());
    EXPECT_FALSE(const_tree_.contains(key));
    EXPECT_EQ(const_tree_.find(key), tree_.end());
    EXPECT_EQ(tree_.equal_range(key).first,
              const_tree_.equal_range(key).second);
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::const_tree_, key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::erase(), and absl::container_internal::base_checker< TreeType, CheckerType >::erase().
find() [1/2]
template<typename TreeType , typename CheckerType > iterator absl::container_internal::base_checker< TreeType, CheckerType >::find (const key_type & key) inline
Definition at line 197 of file btree_test.cc.
{
    return iter_check(tree_.find(key), checker_.find(key));
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::contains(), and absl::container_internal::base_checker< TreeType, CheckerType >::value_check().
find() [2/2]
template<typename TreeType , typename CheckerType > const_iterator absl::container_internal::base_checker< TreeType, CheckerType >::find (const key_type & key) const inline
Definition at line 200 of file btree_test.cc.
{
    return iter_check(tree_.find(key), checker_.find(key));
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
iter_check()
template<typename TreeType , typename CheckerType > template<typename IterType , typename CheckerIterType > IterType absl::container_internal::base_checker< TreeType, CheckerType >::iter_check (IterType tree_iter, CheckerIterType checker_iter) const inline
Definition at line 128 of file btree_test.cc.
{
    if (tree_iter == tree_.end()) {
      ABSL_INTERNAL_CHECK(checker_iter == checker_.end(),
                          "Checker iterator not at end.");
    } else {
      CheckPairEquals(*tree_iter, *checker_iter);
    }
    return tree_iter;
  }
References ABSL_INTERNAL_CHECK, absl::container_internal::base_checker< TreeType, CheckerType >::checker_, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::equal_range(), absl::container_internal::base_checker< TreeType, CheckerType >::equal_range(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::find(), absl::container_internal::base_checker< TreeType, CheckerType >::find(), absl::container_internal::base_checker< TreeType, CheckerType >::lower_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::lower_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::upper_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::upper_bound(), and absl::container_internal::base_checker< TreeType, CheckerType >::verify().
lower_bound() [1/2]
template<typename TreeType , typename CheckerType > iterator absl::container_internal::base_checker< TreeType, CheckerType >::lower_bound (const key_type & key) inline
Definition at line 167 of file btree_test.cc.
{
    return iter_check(tree_.lower_bound(key), checker_.lower_bound(key));
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::value_check().
lower_bound() [2/2]
template<typename TreeType , typename CheckerType > const_iterator absl::container_internal::base_checker< TreeType, CheckerType >::lower_bound (const key_type & key) const inline
Definition at line 170 of file btree_test.cc.
{
    return iter_check(tree_.lower_bound(key), checker_.lower_bound(key));
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
max_size()
template<typename TreeType , typename CheckerType > size_type absl::container_internal::base_checker< TreeType, CheckerType >::max_size () const inline
Definition at line 321 of file btree_test.cc.
{ return tree_.max_size(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
operator=()
template<typename TreeType , typename CheckerType > base_checker & absl::container_internal::base_checker< TreeType, CheckerType >::operator= (const base_checker< TreeType, CheckerType > & other) inline
Definition at line 210 of file btree_test.cc.
{
    tree_ = other.tree_;
    checker_ = other.checker_;
    return *this;
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
rbegin() [1/2]
template<typename TreeType , typename CheckerType > reverse_iterator absl::container_internal::base_checker< TreeType, CheckerType >::rbegin () inline
Definition at line 122 of file btree_test.cc.
{ return tree_.rbegin(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
rbegin() [2/2]
template<typename TreeType , typename CheckerType > const_reverse_iterator absl::container_internal::base_checker< TreeType, CheckerType >::rbegin () const inline
Definition at line 123 of file btree_test.cc.
{ return tree_.rbegin(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
rend() [1/2]
template<typename TreeType , typename CheckerType > reverse_iterator absl::container_internal::base_checker< TreeType, CheckerType >::rend () inline
Definition at line 124 of file btree_test.cc.
{ return tree_.rend(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
rend() [2/2]
template<typename TreeType , typename CheckerType > const_reverse_iterator absl::container_internal::base_checker< TreeType, CheckerType >::rend () const inline
Definition at line 125 of file btree_test.cc.
{ return tree_.rend(); }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
riter_check()
template<typename TreeType , typename CheckerType > template<typename IterType , typename CheckerIterType > IterType absl::container_internal::base_checker< TreeType, CheckerType >::riter_check (IterType tree_iter, CheckerIterType checker_iter) const inline
Definition at line 138 of file btree_test.cc.
{
    if (tree_iter == tree_.rend()) {
      ABSL_INTERNAL_CHECK(checker_iter == checker_.rend(),
                          "Checker iterator not at rend.");
    } else {
      CheckPairEquals(*tree_iter, *checker_iter);
    }
    return tree_iter;
  }
References ABSL_INTERNAL_CHECK, absl::container_internal::base_checker< TreeType, CheckerType >::checker_, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::verify().
size()
template<typename TreeType , typename CheckerType > size_type absl::container_internal::base_checker< TreeType, CheckerType >::size () const inline
Definition at line 317 of file btree_test.cc.
{
    EXPECT_EQ(tree_.size(), checker_.size());
    return tree_.size();
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
swap()
template<typename TreeType , typename CheckerType > void absl::container_internal::base_checker< TreeType, CheckerType >::swap (base_checker< TreeType, CheckerType > & other) inline
Definition at line 273 of file btree_test.cc.
{
    tree_.swap(other.tree_);
    checker_.swap(other.checker_);
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
tree()
template<typename TreeType , typename CheckerType > const TreeType & absl::container_internal::base_checker< TreeType, CheckerType >::tree () const inline
Definition at line 315 of file btree_test.cc.
{ return tree_; }
References absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
upper_bound() [1/2]
template<typename TreeType , typename CheckerType > iterator absl::container_internal::base_checker< TreeType, CheckerType >::upper_bound (const key_type & key) inline
Definition at line 173 of file btree_test.cc.
{
    return iter_check(tree_.upper_bound(key), checker_.upper_bound(key));
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::value_check().
upper_bound() [2/2]
template<typename TreeType , typename CheckerType > const_iterator absl::container_internal::base_checker< TreeType, CheckerType >::upper_bound (const key_type & key) const inline
Definition at line 176 of file btree_test.cc.
{
    return iter_check(tree_.upper_bound(key), checker_.upper_bound(key));
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), key, and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
value_check()
template<typename TreeType , typename CheckerType > void absl::container_internal::base_checker< TreeType, CheckerType >::value_check (const value_type & v) inline
Definition at line 147 of file btree_test.cc.
{
    typename KeyOfValue<typename TreeType::key_type,
                        typename TreeType::value_type>::type key_of_value;
    const key_type &key = key_of_value(v);
    CheckPairEquals(*find(key), v);
    lower_bound(key);
    upper_bound(key);
    equal_range(key);
    contains(key);
    count(key);
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::contains(), absl::container_internal::base_checker< TreeType, CheckerType >::count(), absl::container_internal::base_checker< TreeType, CheckerType >::equal_range(), absl::container_internal::base_checker< TreeType, CheckerType >::find(), key, absl::container_internal::base_checker< TreeType, CheckerType >::lower_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::upper_bound(), and absl::v.
verify()
template<typename TreeType , typename CheckerType > void absl::container_internal::base_checker< TreeType, CheckerType >::verify () const inline
Definition at line 278 of file btree_test.cc.
                      {
    tree_.verify();
    EXPECT_EQ(tree_.size(), checker_.size());
    // Move through the forward iterators using increment.
    auto checker_iter = checker_.begin();
    const_iterator tree_iter(tree_.begin());
    for (; tree_iter != tree_.end(); ++tree_iter, ++checker_iter) {
      CheckPairEquals(*tree_iter, *checker_iter);
    }
    // Move through the forward iterators using decrement.
    for (int n = tree_.size() - 1; n >= 0; --n) {
      iter_check(tree_iter, checker_iter);
      --tree_iter;
      --checker_iter;
    }
    EXPECT_EQ(tree_iter, tree_.begin());
    EXPECT_EQ(checker_iter, checker_.begin());
    // Move through the reverse iterators using increment.
    auto checker_riter = checker_.rbegin();
    const_reverse_iterator tree_riter(tree_.rbegin());
    for (; tree_riter != tree_.rend(); ++tree_riter, ++checker_riter) {
      CheckPairEquals(*tree_riter, *checker_riter);
    }
    // Move through the reverse iterators using decrement.
    for (int n = tree_.size() - 1; n >= 0; --n) {
      riter_check(tree_riter, checker_riter);
      --tree_riter;
      --checker_riter;
    }
    EXPECT_EQ(tree_riter, tree_.rbegin());
    EXPECT_EQ(checker_riter, checker_.rbegin());
  }
References absl::container_internal::base_checker< TreeType, CheckerType >::checker_, absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), absl::n, absl::container_internal::base_checker< TreeType, CheckerType >::riter_check(), and absl::container_internal::base_checker< TreeType, CheckerType >::tree_.
Member Data Documentation
checker_
template<typename TreeType , typename CheckerType > CheckerType absl::container_internal::base_checker< TreeType, CheckerType >::checker_ protected
Definition at line 330 of file btree_test.cc.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::clear(), absl::container_internal::base_checker< TreeType, CheckerType >::count(), absl::container_internal::base_checker< TreeType, CheckerType >::empty(), absl::container_internal::base_checker< TreeType, CheckerType >::equal_range(), absl::container_internal::base_checker< TreeType, CheckerType >::equal_range(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::find(), absl::container_internal::base_checker< TreeType, CheckerType >::find(), absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), absl::container_internal::base_checker< TreeType, CheckerType >::lower_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::lower_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::operator=(), absl::container_internal::base_checker< TreeType, CheckerType >::riter_check(), absl::container_internal::base_checker< TreeType, CheckerType >::size(), absl::container_internal::base_checker< TreeType, CheckerType >::swap(), absl::container_internal::base_checker< TreeType, CheckerType >::upper_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::upper_bound(), and absl::container_internal::base_checker< TreeType, CheckerType >::verify().
const_tree_
template<typename TreeType , typename CheckerType > const TreeType& absl::container_internal::base_checker< TreeType, CheckerType >::const_tree_ protected
Definition at line 329 of file btree_test.cc.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::erase_check().
tree_
template<typename TreeType , typename CheckerType > TreeType absl::container_internal::base_checker< TreeType, CheckerType >::tree_ protected
Definition at line 328 of file btree_test.cc.
Referenced by absl::container_internal::base_checker< TreeType, CheckerType >::begin(), absl::container_internal::base_checker< TreeType, CheckerType >::begin(), absl::container_internal::base_checker< TreeType, CheckerType >::clear(), absl::container_internal::base_checker< TreeType, CheckerType >::count(), absl::container_internal::base_checker< TreeType, CheckerType >::empty(), absl::container_internal::base_checker< TreeType, CheckerType >::end(), absl::container_internal::base_checker< TreeType, CheckerType >::end(), absl::container_internal::base_checker< TreeType, CheckerType >::equal_range(), absl::container_internal::base_checker< TreeType, CheckerType >::equal_range(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::erase(), absl::container_internal::base_checker< TreeType, CheckerType >::erase_check(), absl::container_internal::base_checker< TreeType, CheckerType >::find(), absl::container_internal::base_checker< TreeType, CheckerType >::find(), absl::container_internal::base_checker< TreeType, CheckerType >::iter_check(), absl::container_internal::base_checker< TreeType, CheckerType >::lower_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::lower_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::max_size(), absl::container_internal::base_checker< TreeType, CheckerType >::operator=(), absl::container_internal::base_checker< TreeType, CheckerType >::rbegin(), absl::container_internal::base_checker< TreeType, CheckerType >::rbegin(), absl::container_internal::base_checker< TreeType, CheckerType >::rend(), absl::container_internal::base_checker< TreeType, CheckerType >::rend(), absl::container_internal::base_checker< TreeType, CheckerType >::riter_check(), absl::container_internal::base_checker< TreeType, CheckerType >::size(), absl::container_internal::base_checker< TreeType, CheckerType >::swap(), absl::container_internal::base_checker< TreeType, CheckerType >::tree(), absl::container_internal::base_checker< TreeType, CheckerType >::upper_bound(), absl::container_internal::base_checker< TreeType, CheckerType >::upper_bound(), and absl::container_internal::base_checker< TreeType, CheckerType >::verify().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/btree_test.cc