open spiel: open_spiel::bargaining::BargainingState Class Reference
open_spiel::bargaining::BargainingState Class Reference
#include <bargaining.h>
Public Member Functions
BargainingState (std::shared_ptr< const Game > game)
BargainingState (const BargainingState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move_id) const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string InformationStateString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const override
Instance GetInstance () const
void SetInstance (Instance instance)
std::vector< Offer > Offers () const
Action AgreeAction () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 103 of file bargaining.h.
Constructor & Destructor Documentation
BargainingState() [1/2]
open_spiel::bargaining::BargainingState::BargainingState (std::shared_ptr< const Game > game)
Definition at line 314 of file bargaining.cc.
    : State(game),
      cur_player_(kChancePlayerId),
      agreement_reached_(false),
      parent_game_(down_cast<const BargainingGame*>(game.get())),
      next_player_(0),
      discount_(1.0),
      game_ended_(false) {}
Referenced by Clone().
BargainingState() [2/2]
open_spiel::bargaining::BargainingState::BargainingState (const BargainingState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::bargaining::BargainingState::ActionToString (Player player, Action move_id) const override virtual
Implements open_spiel::State.
Definition at line 82 of file bargaining.cc.
{
  return parent_game_->ActionToString(player, move_id);
}
References open_spiel::bargaining::BargainingGame::ActionToString(), and player.
AgreeAction()
Action open_spiel::bargaining::BargainingState::AgreeAction () const
Definition at line 327 of file bargaining.cc.
{
  return parent_game_->AllOffers().size();
}
References open_spiel::bargaining::BargainingGame::AllOffers().
Referenced by DoApplyAction().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::bargaining::BargainingState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 400 of file bargaining.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  std::vector<std::pair<Action, double>> outcomes;
  const int num_boards = parent_game_->AllInstances().size();
  if (move_number_ == 0) {
    // First chance move of the game. This is for determining the instance.
    outcomes.reserve(num_boards);
    double uniform_prob = 1.0 / num_boards;
    for (int i = 0; i < num_boards; ++i) {
      outcomes.push_back({i, uniform_prob});
    }
  } else {
    const double prob_end = parent_game_->prob_end();
    SPIEL_CHECK_TRUE(move_number_ >= 3);
    outcomes = {{parent_game_->ContinueOutcome(), 1.0 - prob_end},
                {parent_game_->EndOutcome(), prob_end}};
  }
  return outcomes;
}
References open_spiel::bargaining::BargainingGame::AllInstances(), open_spiel::bargaining::BargainingGame::ContinueOutcome(), open_spiel::bargaining::BargainingGame::EndOutcome(), i, open_spiel::State::IsChanceNode(), open_spiel::State::move_number_, open_spiel::bargaining::BargainingGame::prob_end(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::bargaining::BargainingState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 436 of file bargaining.cc.
{
  return std::unique_ptr<State>(new BargainingState(*this));
}
References BargainingState().
CurrentPlayer()
int open_spiel::bargaining::BargainingState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 323 of file bargaining.cc.
{
  return IsTerminal() ? kTerminalPlayerId : cur_player_;
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::bargaining::BargainingState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 331 of file bargaining.cc.
{
  if (IsChanceNode()) {
    if (move_number_ == 0) {
      instance_ = parent_game_->GetInstance(action);
      cur_player_ = 0;
    } else {
      if (action == parent_game_->ContinueOutcome()) {
        cur_player_ = next_player_;
      } else {
        SPIEL_CHECK_EQ(action, parent_game_->EndOutcome());
        game_ended_ = true;
        cur_player_ = kTerminalPlayerId;
      }
    }
  } else {
    // Check to apply discount.
    if (move_number_ >= 3 && parent_game_->discount() < 1.0) {
      discount_ *= parent_game_->discount();
    }
    const std::vector<Offer>& all_offers = parent_game_->AllOffers();
    if (action != AgreeAction()) {
      offers_.push_back(all_offers.at(action));
      if (move_number_ >= 2 && parent_game_->prob_end() > 0.0) {
        next_player_ = 1 - cur_player_;
        cur_player_ = kChancePlayerId;
      } else {
        cur_player_ = 1 - cur_player_;
      }
    } else {
      // Agree action.
      SPIEL_CHECK_EQ(action, AgreeAction());
      agreement_reached_ = true;
    }
  }
}
References action, AgreeAction(), open_spiel::bargaining::BargainingGame::AllOffers(), open_spiel::bargaining::BargainingGame::ContinueOutcome(), open_spiel::bargaining::BargainingGame::discount(), open_spiel::bargaining::BargainingGame::EndOutcome(), open_spiel::bargaining::BargainingGame::GetInstance(), open_spiel::State::IsChanceNode(), open_spiel::kChancePlayerId, open_spiel::kTerminalPlayerId, open_spiel::State::move_number_, open_spiel::bargaining::BargainingGame::prob_end(), and SPIEL_CHECK_EQ.
GetInstance()
Instance open_spiel::bargaining::BargainingState::GetInstance () const inline
Definition at line 128 of file bargaining.h.
{ return instance_; }
InformationStateString()
std::string open_spiel::bargaining::BargainingState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 138 of file bargaining.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (IsChanceNode()) {
    return "Initial chance node";
  }
  std::string str = absl::StrCat("Pool: ", absl::StrJoin(instance_.pool, " "));
  absl::StrAppend(&str,
                  "\nMy values: ", absl::StrJoin(instance_.values[player], " "),
                  "\n");
  absl::StrAppend(&str, "Agreement reached? ", agreement_reached_, "\n");
  for (int i = 0; i < offers_.size(); ++i) {
    int proposer = i % 2;
    absl::StrAppend(&str, "P", proposer, " offers: ", offers_[i].ToString(),
                    "\n");
  }
  return str;
}
References i, open_spiel::State::IsChanceNode(), open_spiel::State::num_players_, player, open_spiel::bargaining::Instance::pool, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), absl::StrCat(), absl::StrJoin(), ToString(), and open_spiel::bargaining::Instance::values.
InformationStateTensor()
void open_spiel::bargaining::BargainingState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 243 of file bargaining.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->InformationStateTensorSize());
  std::fill(values.begin(), values.end(), 0);
  if (IsChanceNode()) {
    // No observations at chance nodes.
    return;
  }
  int offset = 0;
  // Agreement reached?
  if (agreement_reached_) {
    values[offset] = 1;
  }
  offset += 1;
  // How many trade offers have happened?
  values[offers_.size()] = 1;
  offset += parent_game_->max_turns() + 1;
  // Pool
  for (int i = 0; i < kNumItemTypes; ++i) {
    for (int j = 0; j <= instance_.pool[i]; ++j) {
      values[offset + j] = 1;
    }
    offset += kPoolMaxNumItems + 1;
  }
  // My values
  for (int i = 0; i < kNumItemTypes; ++i) {
    for (int j = 0; j <= instance_.values[player][i]; ++j) {
      values[offset + j] = 1;
    }
    offset += kTotalValueAllItems + 1;
  }
  // Offers
  for (int k = 0; k < parent_game_->max_turns(); ++k) {
    if (k < offers_.size()) {
      for (int i = 0; i < kNumItemTypes; ++i) {
        for (int j = 0; j <= offers_[k].quantities[i]; ++j) {
          values[offset + j] = 1;
        }
        offset += kPoolMaxNumItems + 1;
      }
    } else {
      offset += (kPoolMaxNumItems + 1) * kNumItemTypes;
    }
  }
  SPIEL_CHECK_EQ(offset, values.size());
}
References open_spiel::State::game_, i, open_spiel::State::IsChanceNode(), open_spiel::bargaining::kNumItemTypes, open_spiel::bargaining::kPoolMaxNumItems, open_spiel::bargaining::kTotalValueAllItems, open_spiel::bargaining::BargainingGame::max_turns(), open_spiel::State::num_players_, player, open_spiel::bargaining::Instance::pool, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::bargaining::Instance::values, and values.
IsTerminal()
bool open_spiel::bargaining::BargainingState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 87 of file bargaining.cc.
{
  return agreement_reached_ || game_ended_ ||
         offers_.size() >= parent_game_->max_turns();
}
References open_spiel::bargaining::BargainingGame::max_turns().
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::bargaining::BargainingState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 379 of file bargaining.cc.
{
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else if (IsTerminal()) {
    return {};
  } else {
    const std::vector<Offer>& all_offers = parent_game_->AllOffers();
    std::vector<Action> legal_actions;
    for (int i = 0; i < all_offers.size(); ++i) {
      if (IsLegalOffer(all_offers.at(i))) {
        legal_actions.push_back(i);
      }
    }
    // Add the agree action if there's at least one offer on the table.
    if (!offers_.empty()) {
      legal_actions.push_back(all_offers.size());
    }
    return legal_actions;
  }
}
References open_spiel::bargaining::BargainingGame::AllOffers(), i, open_spiel::State::IsChanceNode(), IsTerminal(), and open_spiel::State::LegalChanceOutcomes().
ObservationString()
std::string open_spiel::bargaining::BargainingState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 116 of file bargaining.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (IsChanceNode()) {
    return "Initial chance node";
  }
  std::string str = absl::StrCat("Pool: ", absl::StrJoin(instance_.pool, " "));
  absl::StrAppend(&str,
                  "\nMy values: ", absl::StrJoin(instance_.values[player], " "),
                  "\n");
  absl::StrAppend(&str, "Agreement reached? ", agreement_reached_, "\n");
  absl::StrAppend(&str, "Number of offers: ", offers_.size(), "\n");
  if (!offers_.empty()) {
    // Only the most recent offer.
    absl::StrAppend(&str, "P", (offers_.size() + 1) % 2,
                    " offers: ", offers_.back().ToString(), "\n");
  }
  return str;
}
References open_spiel::State::IsChanceNode(), open_spiel::State::num_players_, player, open_spiel::bargaining::Instance::pool, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), absl::StrCat(), absl::StrJoin(), and open_spiel::bargaining::Instance::values.
ObservationTensor()
void open_spiel::bargaining::BargainingState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 188 of file bargaining.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  std::fill(values.begin(), values.end(), 0);
  if (IsChanceNode()) {
    // No observations at chance nodes.
    return;
  }
  int offset = 0;
  // Agreement reached?
  if (agreement_reached_) {
    values[offset] = 1;
  }
  offset += 1;
  // How many trade offers have happened?
  values[offers_.size()] = 1;
  offset += parent_game_->max_turns() + 1;
  // Pool
  for (int i = 0; i < kNumItemTypes; ++i) {
    for (int j = 0; j <= instance_.pool[i]; ++j) {
      values[offset + j] = 1;
    }
    offset += kPoolMaxNumItems + 1;
  }
  // My values
  for (int i = 0; i < kNumItemTypes; ++i) {
    for (int j = 0; j <= instance_.values[player][i]; ++j) {
      values[offset + j] = 1;
    }
    offset += kTotalValueAllItems + 1;
  }
  // Just the last offer
  if (!offers_.empty()) {
    for (int i = 0; i < kNumItemTypes; ++i) {
      for (int j = 0; j <= offers_.back().quantities[i]; ++j) {
        values[offset + j] = 1;
      }
      offset += kPoolMaxNumItems + 1;
    }
  } else {
    offset += (kPoolMaxNumItems + 1) * kNumItemTypes;
  }
  SPIEL_CHECK_EQ(offset, values.size());
}
References open_spiel::State::game_, i, open_spiel::State::IsChanceNode(), open_spiel::bargaining::kNumItemTypes, open_spiel::bargaining::kPoolMaxNumItems, open_spiel::bargaining::kTotalValueAllItems, open_spiel::bargaining::BargainingGame::max_turns(), open_spiel::State::num_players_, player, open_spiel::bargaining::Instance::pool, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::bargaining::Instance::values, and values.
Offers()
std::vector< Offer > open_spiel::bargaining::BargainingState::Offers () const inline
Definition at line 131 of file bargaining.h.
{ return offers_; }
ResampleFromInfostate()
std::unique_ptr< State > open_spiel::bargaining::BargainingState::ResampleFromInfostate (int player_id, std::function< double()> rng) const override virtual
Reimplemented from open_spiel::State.
Definition at line 159 of file bargaining.cc.
{
  std::vector<int> valid_indices;
  const int num_instances = parent_game_->AllInstances().size();
  for (int i = 0; i < num_instances; ++i) {
    const Instance& instance = parent_game_->GetInstance(i);
    if (instance_.pool == instance.pool &&
        instance_.values[player_id] == instance.values[player_id]) {
      valid_indices.push_back(i);
    }
  }
  SPIEL_CHECK_FALSE(valid_indices.empty());
  int idx = static_cast<int>(rng() * valid_indices.size());
  SPIEL_CHECK_GE(idx, 0);
  SPIEL_CHECK_LT(idx, valid_indices.size());
  int instance_idx = valid_indices[idx];
  std::unique_ptr<State> state = parent_game_->NewInitialState();
  for (Action action : History()) {
    if (state->IsChanceNode()) {
      state->ApplyAction(instance_idx);
    } else {
      state->ApplyAction(action);
    }
  }
  return state;
}
References action, open_spiel::bargaining::BargainingGame::AllInstances(), open_spiel::bargaining::BargainingGame::GetInstance(), open_spiel::State::History(), i, open_spiel::bargaining::BargainingGame::NewInitialState(), open_spiel::bargaining::Instance::pool, SPIEL_CHECK_FALSE, SPIEL_CHECK_GE, SPIEL_CHECK_LT, state, and open_spiel::bargaining::Instance::values.
Returns()
std::vector< double > open_spiel::bargaining::BargainingState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 92 of file bargaining.cc.
{
  if (agreement_reached_) {
    int proposing_player = (offers_.size() + 1) % kNumPlayers;
    int other_player = 1 - proposing_player;
    std::vector<double> returns(kNumPlayers, 0);
    for (int i = 0; i < kNumItemTypes; ++i) {
      returns[proposing_player] +=
          instance_.values[proposing_player][i] * offers_.back().quantities[i];
      returns[other_player] +=
          instance_.values[other_player][i] *
          (instance_.pool[i] - offers_.back().quantities[i]);
    }
    // Apply discount.
    if (discount_ < 1.0) {
      for (Player p = 0; p < num_players_; ++p) {
        returns[p] *= discount_;
      }
    }
    return returns;
  } else {
    return std::vector<double>(kNumPlayers, 0);
  }
}
References i, open_spiel::bargaining::kNumItemTypes, open_spiel::bargaining::kNumPlayers, open_spiel::State::num_players_, open_spiel::bargaining::Instance::pool, and open_spiel::bargaining::Instance::values.
SetInstance()
void open_spiel::bargaining::BargainingState::SetInstance (Instance instance)
Definition at line 300 of file bargaining.cc.
{
  instance_ = instance;
  // TODO(author5): we could (should?) add the ability to check if the instance
  // abides by the rules of the game here (refactoring that logic out of the
  // instance generator into a general helper function).
  // Check if this is at the start of the game. If so, make it no longer the
  // chance player.
  if (IsChanceNode()) {
    SPIEL_CHECK_TRUE(offers_.empty());
    cur_player_ = 0;
  }
}
References open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
ToString()
std::string open_spiel::bargaining::BargainingState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 421 of file bargaining.cc.
{
  if (IsChanceNode()) {
    return "Initial chance node";
  }
  std::string str = instance_.ToPrettyString();
  absl::StrAppend(&str, "Agreement reached? ", agreement_reached_, "\n");
  for (int i = 0; i < offers_.size(); ++i) {
    int proposer = i % 2;
    absl::StrAppend(&str, "P", proposer, " offers: ", offers_[i].ToString(),
                    "\n");
  }
  return str;
}
References i, open_spiel::State::IsChanceNode(), absl::StrAppend(), open_spiel::bargaining::Instance::ToPrettyString(), and ToString().
Referenced by InformationStateString(), and ToString().
The documentation for this class was generated from the following files:
open_spiel/games/bargaining/bargaining.h
open_spiel/games/bargaining/bargaining.cc