open spiel: open_spiel::phantom_ttt::PhantomTTTGame Class Reference
open_spiel::phantom_ttt::PhantomTTTGame Class Reference
#include <phantom_ttt.h>
Public Member Functions
PhantomTTTGame (const GameParameters &params, GameType game_type)
std::unique_ptr< State > NewInitialState () const override
int NumDistinctActions () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
std::string ActionToString (Player player, Action action_id) const override
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
ObservationType obs_type () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 98 of file phantom_ttt.h.
Constructor & Destructor Documentation
PhantomTTTGame()
open_spiel::phantom_ttt::PhantomTTTGame::PhantomTTTGame (const GameParameters & params, GameType game_type)
Definition at line 279 of file phantom_ttt.cc.
    : Game(game_type, params),
      game_(std::static_pointer_cast<const tic_tac_toe::TicTacToeGame>(
          LoadGame("tic_tac_toe"))) {
  std::string obs_type = ParameterValue<std::string>("obstype");
  if (obs_type == "reveal-nothing") {
    obs_type_ = ObservationType::kRevealNothing;
  } else if (obs_type == "reveal-numturns") {
    obs_type_ = ObservationType::kRevealNumTurns;
  } else {
    SpielFatalError(absl::StrCat("Unrecognized observation type: ", obs_type));
  }
}
References open_spiel::phantom_ttt::kRevealNothing, open_spiel::phantom_ttt::kRevealNumTurns, obs_type(), open_spiel::Game::ParameterValue(), open_spiel::SpielFatalError(), and absl::StrCat().
Member Function Documentation
ActionToString()
std::string open_spiel::phantom_ttt::PhantomTTTGame::ActionToString (Player player, Action action_id) const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 114 of file phantom_ttt.h.
{
    return game_->ActionToString(player, action_id);
  }
References player.
InformationStateTensorShape()
std::vector< int > open_spiel::phantom_ttt::PhantomTTTGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 293 of file phantom_ttt.cc.
{
  // Enc
  return {1, kNumCells * kCellStates + kLongestSequence * (1 + kBitsPerAction)};
}
References open_spiel::phantom_ttt::kBitsPerAction, and open_spiel::phantom_ttt::kLongestSequence.
MaxGameLength()
int open_spiel::phantom_ttt::PhantomTTTGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 122 of file phantom_ttt.h.
{ return kLongestSequence; }
References open_spiel::phantom_ttt::kLongestSequence.
MaxUtility()
double open_spiel::phantom_ttt::PhantomTTTGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 113 of file phantom_ttt.h.
{ return game_->MaxUtility(); }
MinUtility()
double open_spiel::phantom_ttt::PhantomTTTGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 109 of file phantom_ttt.h.
{ return game_->MinUtility(); }
NewInitialState()
std::unique_ptr< State > open_spiel::phantom_ttt::PhantomTTTGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 101 of file phantom_ttt.h.
{
    return std::unique_ptr<State>(
        new PhantomTTTState(shared_from_this(), obs_type_));
  }
NumDistinctActions()
int open_spiel::phantom_ttt::PhantomTTTGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 105 of file phantom_ttt.h.
{
    return game_->NumDistinctActions();
  }
NumPlayers()
int open_spiel::phantom_ttt::PhantomTTTGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 108 of file phantom_ttt.h.
{ return game_->NumPlayers(); }
obs_type()
ObservationType open_spiel::phantom_ttt::PhantomTTTGame::obs_type () const inline
Definition at line 124 of file phantom_ttt.h.
{ return obs_type_; }
Referenced by open_spiel::phantom_ttt::ImperfectRecallPTTTGame::NewInitialState(), and PhantomTTTGame().
ObservationTensorShape()
std::vector< int > open_spiel::phantom_ttt::PhantomTTTGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 298 of file phantom_ttt.cc.
{
  if (obs_type_ == ObservationType::kRevealNothing) {
    return {kNumCells * kCellStates};
  } else if (obs_type_ == ObservationType::kRevealNumTurns) {
    return {kNumCells * kCellStates + kLongestSequence};
  } else {
    SpielFatalError("Uknown observation type");
  }
}
References open_spiel::phantom_ttt::kLongestSequence, open_spiel::phantom_ttt::kRevealNothing, open_spiel::phantom_ttt::kRevealNumTurns, and open_spiel::SpielFatalError().
UtilitySum()
absl::optional< double > open_spiel::phantom_ttt::PhantomTTTGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 110 of file phantom_ttt.h.
{
    return game_->UtilitySum();
  }
The documentation for this class was generated from the following files:
open_spiel/games/phantom_ttt/phantom_ttt.h
open_spiel/games/phantom_ttt/phantom_ttt.cc