open spiel: open_spiel::gin_rummy::GinRummyState Class Reference
open_spiel::gin_rummy::GinRummyState Class Reference
#include <gin_rummy.h>
Public Member Functions
GinRummyState (std::shared_ptr< const Game > game, bool oklahoma, int knock_card, int gin_bonus, int undercut_bonus, int num_ranks, int num_suits, int hand_size)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
Phase CurrentPhase () const
bool FinishedLayoffs () const
absl::optional< int > Upcard () const
int StockSize () const
std::vector< std::vector< int > > Hands () const
std::vector< int > DiscardPile () const
std::vector< int > Deadwood () const
std::vector< bool > Knocked () const
std::vector< bool > PassOnFirstUpcard () const
std::vector< std::vector< int > > LayedMelds () const
std::vector< int > Layoffs () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Friends
class GinRummyObserver
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 103 of file gin_rummy.h.
Constructor & Destructor Documentation
GinRummyState()
open_spiel::gin_rummy::GinRummyState::GinRummyState (std::shared_ptr< const Game > game, bool oklahoma, int knock_card, int gin_bonus, int undercut_bonus, int num_ranks, int num_suits, int hand_size) explicit
Definition at line 277 of file gin_rummy.cc.
    : State(std::move(game)),
      oklahoma_(oklahoma),
      knock_card_(knock_card),
      gin_bonus_(gin_bonus),
      undercut_bonus_(undercut_bonus),
      num_ranks_(num_ranks),
      num_suits_(num_suits),
      num_cards_(num_ranks * num_suits),
      hand_size_(hand_size),
      utils_(GinRummyUtils(num_ranks, num_suits, hand_size)),
      stock_size_(num_ranks * num_suits),
      deck_(num_ranks * num_suits, true) {
  aohs_.reserve(kNumPlayers);
  for (Player player = 0; player < kNumPlayers; ++player) {
    std::vector<std::pair<absl::optional<Action>, std::string>> aoh;
    aoh.push_back({{}, ObservationString(player)});
    aohs_.push_back(open_spiel::ActionObservationHistory(player, aoh));
  }
}
References open_spiel::gin_rummy::kNumPlayers, open_spiel::State::ObservationString(), and player.
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::gin_rummy::GinRummyState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 688 of file gin_rummy.cc.
{
  if (player == kChancePlayerId) {
    return absl::StrCat("Chance outcome: ", utils_.CardString(action));
  } else {
    std::string action_str;
    if (action < num_cards_) {
      action_str = utils_.CardString(action);
    } else if (action == kDrawUpcardAction) {
      action_str = "Draw upcard";
    } else if (action == kDrawStockAction) {
      action_str = "Draw stock";
    } else if (action == kPassAction) {
      action_str = "Pass";
    } else if (action == kKnockAction) {
      action_str = "Knock";
    } else if (action < kMeldActionBase + kNumMeldActions) {
      std::vector<int> meld = utils_.int_to_meld.at(action - kMeldActionBase);
      std::vector<std::string> meld_str = utils_.CardIntsToCardStrings(meld);
      action_str = absl::StrJoin(meld_str, "");
    } else {
      SpielFatalError(
          absl::StrCat("Error in GinRummyState::ActionToString()."));
    }
    return absl::StrCat("Player: ", player, " Action: ", action_str);
  }
}
References action, open_spiel::gin_rummy::GinRummyUtils::CardIntsToCardStrings(), open_spiel::gin_rummy::GinRummyUtils::CardString(), open_spiel::gin_rummy::GinRummyUtils::int_to_meld, open_spiel::kChancePlayerId, open_spiel::gin_rummy::kDrawStockAction, open_spiel::gin_rummy::kDrawUpcardAction, open_spiel::gin_rummy::kKnockAction, open_spiel::gin_rummy::kMeldActionBase, open_spiel::gin_rummy::kNumMeldActions, open_spiel::gin_rummy::kPassAction, player, open_spiel::SpielFatalError(), absl::StrCat(), and absl::StrJoin().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::gin_rummy::GinRummyState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 676 of file gin_rummy.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  std::vector<std::pair<Action, double>> outcomes;
  outcomes.reserve(stock_size_);
  const double p = 1.0 / stock_size_;
  for (int card = 0; card < num_cards_; ++card) {
    // This card is still in the deck, prob is 1/stock_size_.
    if (deck_[card]) outcomes.push_back({card, p});
  }
  return outcomes;
}
References open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::gin_rummy::GinRummyState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 812 of file gin_rummy.cc.
{
  return std::unique_ptr<State>(new GinRummyState(*this));
}
References GinRummyState().
CurrentPhase()
Phase open_spiel::gin_rummy::GinRummyState::CurrentPhase () const inline
Definition at line 122 of file gin_rummy.h.
{ return phase_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
CurrentPlayer()
int open_spiel::gin_rummy::GinRummyState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 300 of file gin_rummy.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  } else {
    return cur_player_;
  }
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by DoApplyAction(), and open_spiel::init_pyspiel_games_gin_rummy().
Deadwood()
std::vector< int > open_spiel::gin_rummy::GinRummyState::Deadwood () const inline
Definition at line 128 of file gin_rummy.h.
{ return deadwood_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
DiscardPile()
std::vector< int > open_spiel::gin_rummy::GinRummyState::DiscardPile () const inline
Definition at line 127 of file gin_rummy.h.
{ return discard_pile_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
DoApplyAction()
void open_spiel::gin_rummy::GinRummyState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 308 of file gin_rummy.cc.
{
  Player current_player = CurrentPlayer();
  switch (phase_) {
    case Phase::kDeal:
      ApplyDealAction(action);
      break;
    case Phase::kFirstUpcard:
      ApplyFirstUpcardAction(action);
      break;
    case Phase::kDraw:
      ApplyDrawAction(action);
      break;
    case Phase::kDiscard:
      ApplyDiscardAction(action);
      break;
    case Phase::kKnock:
      ApplyKnockAction(action);
      break;
    case Phase::kLayoff:
      ApplyLayoffAction(action);
      break;
    case Phase::kWall:
      ApplyWallAction(action);
      break;
    case Phase::kGameOver:
      SpielFatalError("Cannot act in terminal states.");
      break;
    default:
      SpielFatalError("Invalid game phase.");
  }
  for (Player player = 0; player < NumPlayers(); ++player) {
    absl::optional<Action> a = {};
    if (current_player == player) a = action;
    aohs_[player].Extend(a, ObservationString(player));
  }
}
References a, action, CurrentPlayer(), open_spiel::gin_rummy::kDeal, open_spiel::gin_rummy::kDiscard, open_spiel::gin_rummy::kDraw, open_spiel::gin_rummy::kFirstUpcard, open_spiel::gin_rummy::kGameOver, open_spiel::gin_rummy::kKnock, open_spiel::gin_rummy::kLayoff, open_spiel::gin_rummy::kWall, open_spiel::State::NumPlayers(), open_spiel::State::ObservationString(), player, and open_spiel::SpielFatalError().
FinishedLayoffs()
bool open_spiel::gin_rummy::GinRummyState::FinishedLayoffs () const inline
Definition at line 123 of file gin_rummy.h.
{ return finished_layoffs_ ; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
Hands()
std::vector< std::vector< int > > open_spiel::gin_rummy::GinRummyState::Hands () const inline
Definition at line 126 of file gin_rummy.h.
{ return hands_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
InformationStateString()
std::string open_spiel::gin_rummy::GinRummyState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 816 of file gin_rummy.cc.
{
  const auto& game = open_spiel::down_cast<const GinRummyGame&>(*game_);
  return game.info_state_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
IsTerminal()
bool open_spiel::gin_rummy::GinRummyState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 111 of file gin_rummy.h.
{ return phase_ == Phase::kGameOver; }
References open_spiel::gin_rummy::kGameOver.
Referenced by CurrentPlayer(), and Returns().
Knocked()
std::vector< bool > open_spiel::gin_rummy::GinRummyState::Knocked () const inline
Definition at line 129 of file gin_rummy.h.
{ return knocked_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
LayedMelds()
std::vector< std::vector< int > > open_spiel::gin_rummy::GinRummyState::LayedMelds () const inline
Definition at line 131 of file gin_rummy.h.
{ return layed_melds_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
Layoffs()
std::vector< int > open_spiel::gin_rummy::GinRummyState::Layoffs () const inline
Definition at line 132 of file gin_rummy.h.
{ return layoffs_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
LegalActions()
std::vector< Action > open_spiel::gin_rummy::GinRummyState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 554 of file gin_rummy.cc.
{
  switch (phase_) {
    case Phase::kDeal:
      return DealLegalActions();
    case Phase::kFirstUpcard:
      return FirstUpcardLegalActions();
    case Phase::kDraw:
      return DrawLegalActions();
    case Phase::kDiscard:
      return DiscardLegalActions();
    case Phase::kKnock:
      return KnockLegalActions();
    case Phase::kLayoff:
      return LayoffLegalActions();
    case Phase::kWall:
      return WallLegalActions();
    default:
      return {};
  }
}
References open_spiel::gin_rummy::kDeal, open_spiel::gin_rummy::kDiscard, open_spiel::gin_rummy::kDraw, open_spiel::gin_rummy::kFirstUpcard, open_spiel::gin_rummy::kKnock, open_spiel::gin_rummy::kLayoff, and open_spiel::gin_rummy::kWall.
ObservationString()
std::string open_spiel::gin_rummy::GinRummyState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 821 of file gin_rummy.cc.
{
  const GinRummyGame& game = open_spiel::down_cast<const GinRummyGame&>(*game_);
  return game.default_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
ObservationTensor()
void open_spiel::gin_rummy::GinRummyState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 826 of file gin_rummy.cc.
{
  ContiguousAllocator allocator(values);
  const GinRummyGame& game = open_spiel::down_cast<const GinRummyGame&>(*game_);
  game.default_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
PassOnFirstUpcard()
std::vector< bool > open_spiel::gin_rummy::GinRummyState::PassOnFirstUpcard () const inline
Definition at line 130 of file gin_rummy.h.
{ return pass_on_first_upcard_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
Returns()
std::vector< double > open_spiel::gin_rummy::GinRummyState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 758 of file gin_rummy.cc.
{
  if (!IsTerminal()) {
    return std::vector<double>(kNumPlayers, 0.0);
  }
  std::vector<double> returns(kNumPlayers, 0.0);
  // player 0 knocked
  if (knocked_[0]) {
    returns[0] = deadwood_[1] - deadwood_[0];
    if (deadwood_[0] == 0) {
      returns[0] += gin_bonus_;
    }
    if (returns[0] < 0) {
      returns[0] -= undercut_bonus_;
    }
    returns[1] = -returns[0];
  } else if (knocked_[1]) {
    // player 1 knocked
    returns[1] = deadwood_[0] - deadwood_[1];
    if (deadwood_[1] == 0) {
      returns[1] += gin_bonus_;
    }
    if (returns[1] < 0) {
      returns[1] -= undercut_bonus_;
    }
    returns[0] = -returns[1];
  }
  // If neither player knocked both players get 0.
  return returns;
}
References IsTerminal(), and open_spiel::gin_rummy::kNumPlayers.
StockSize()
int open_spiel::gin_rummy::GinRummyState::StockSize () const inline
Definition at line 125 of file gin_rummy.h.
{ return stock_size_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
ToString()
std::string open_spiel::gin_rummy::GinRummyState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 715 of file gin_rummy.cc.
{
  std::string rv;
  absl::StrAppend(&rv, "\nKnock card: ", knock_card_);
  absl::StrAppend(&rv, "\nPrev upcard: ", utils_.CardString(prev_upcard_));
  absl::StrAppend(&rv, "\nRepeated move: ", repeated_move_);
  absl::StrAppend(&rv, "\nCurrent player: ", cur_player_);
  absl::StrAppend(&rv, "\nPhase: ", kPhaseString[static_cast<int>(phase_)],
                  "\n");
  absl::StrAppend(&rv, "\nPlayer0: Deadwood=", deadwood_[0]);
  if (knocked_[1] && !layoffs_.empty()) {
    absl::StrAppend(&rv, "\nLayoffs: ");
    for (int card : layoffs_) absl::StrAppend(&rv, utils_.CardString(card));
  }
  if (!layed_melds_[0].empty()) {
    absl::StrAppend(&rv, "\nLayed melds:");
    for (int meld_id : layed_melds_[0]) {
      absl::StrAppend(&rv, " ");
      std::vector<int> meld = utils_.int_to_meld.at(meld_id);
      for (int card : meld) absl::StrAppend(&rv, utils_.CardString(card));
    }
  }
  absl::StrAppend(&rv, "\n", utils_.HandToString(hands_[0]));
  absl::StrAppend(&rv, "\nStock size: ", stock_size_);
  absl::StrAppend(&rv, "  Upcard: ", utils_.CardString(upcard_));
  absl::StrAppend(&rv, "\nDiscard pile: ");
  for (int card : discard_pile_) absl::StrAppend(&rv, utils_.CardString(card));
  absl::StrAppend(&rv, "\n\nPlayer1: Deadwood=", deadwood_[1]);
  if (knocked_[0] && !layoffs_.empty()) {
    absl::StrAppend(&rv, "\nLayoffs: ");
    for (int card : layoffs_) absl::StrAppend(&rv, utils_.CardString(card));
  }
  if (!layed_melds_[1].empty()) {
    absl::StrAppend(&rv, "\nLayed melds:");
    for (int meld_id : layed_melds_[1]) {
      absl::StrAppend(&rv, " ");
      std::vector<int> meld = utils_.int_to_meld.at(meld_id);
      for (int card : meld) absl::StrAppend(&rv, utils_.CardString(card));
    }
  }
  absl::StrAppend(&rv, "\n", utils_.HandToString(hands_[1]));
  return rv;
}
References open_spiel::gin_rummy::GinRummyUtils::CardString(), open_spiel::gin_rummy::GinRummyUtils::HandToString(), open_spiel::gin_rummy::GinRummyUtils::int_to_meld, and absl::StrAppend().
Upcard()
absl::optional< int > open_spiel::gin_rummy::GinRummyState::Upcard () const inline
Definition at line 124 of file gin_rummy.h.
{ return upcard_; }
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
Friends And Related Symbol Documentation
GinRummyObserver
friend class GinRummyObserver friend
Definition at line 138 of file gin_rummy.h.
The documentation for this class was generated from the following files:
open_spiel/games/gin_rummy/gin_rummy.h
open_spiel/games/gin_rummy/gin_rummy.cc