open spiel: open_spiel::colored_trails::ColoredTrailsGame Class Reference
open_spiel::colored_trails::ColoredTrailsGame Class Reference
#include <colored_trails.h>
Public Member Functions
ColoredTrailsGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int NumPlayers () const override
double MaxUtility () const override
double MinUtility () const override
std::vector< int > ObservationTensorShape () const override
std::vector< int > InformationStateTensorShape () const override
const std::vector< Board > & AllBoards () const
const Trade & LookupTrade (int trade_id) const
Action ResponderTradeWithPlayerAction (Player player) const
Action PassAction () const
int LookupTradeId (const std::string &trade_str) const
std::vector< Action > LookupTradesCache (const std::string &key) const
void AddToTradesCache (const std::string &key, std::vector< Action > &actions) const
std::pair< Board, Action > SampleRandomBoardCompletion (int seed, const Board &board, Player player) const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 203 of file colored_trails.h.
Constructor & Destructor Documentation
ColoredTrailsGame()
open_spiel::colored_trails::ColoredTrailsGame::ColoredTrailsGame (const GameParameters & params) explicit
Definition at line 721 of file colored_trails.cc.
    : Game(kGameType, params),
      num_colors_(ParameterValue<int>("num_colors", kDefaultNumColors)),
      board_size_(ParameterValue<int>("board_size", kDefaultBoardSize)),
      num_players_(ParameterValue<int>("players", kDefaultNumPlayers)) {
  // Only support the 3-player game.
  SPIEL_CHECK_EQ(num_players_, kDefaultNumPlayers);
  std::string filename = ParameterValue<std::string>("boards_file", "");
  if (!filename.empty()) {
    ParseBoardsFile(&all_boards_, filename, num_colors_, board_size_,
                    num_players_);
  } else {
    ParseBoardsString(&all_boards_, kDefaultBoardsString, num_colors_,
                      board_size_, num_players_);
  }
  InitTradeInfo(&trade_info_, num_colors_);
}
References open_spiel::colored_trails::InitTradeInfo(), open_spiel::colored_trails::kDefaultBoardsString, open_spiel::colored_trails::kDefaultNumPlayers, open_spiel::Game::ParameterValue(), open_spiel::colored_trails::ParseBoardsFile(), open_spiel::colored_trails::ParseBoardsString(), and SPIEL_CHECK_EQ.
Member Function Documentation
AddToTradesCache()
void open_spiel::colored_trails::ColoredTrailsGame::AddToTradesCache (const std::string & key, std::vector< Action > & actions) const
Definition at line 771 of file colored_trails.cc.
{
  trades_cache_[key] = actions;
}
References key.
Referenced by SampleRandomBoardCompletion().
AllBoards()
const std::vector< Board > & open_spiel::colored_trails::ColoredTrailsGame::AllBoards () const inline
Definition at line 230 of file colored_trails.h.
{ return all_boards_; }
Referenced by open_spiel::colored_trails::ColoredTrailsState::ChanceOutcomes(), open_spiel::colored_trails::ColoredTrailsState::DoApplyAction(), and open_spiel::colored_trails::ColoredTrailsState::ResampleFromInfostate().
InformationStateTensorShape()
std::vector< int > open_spiel::colored_trails::ColoredTrailsGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 748 of file colored_trails.cc.
{
  return {
    num_players_ +   // Who is observing
    1 +              // is it terminal?
    board_size_ * board_size_ * num_colors_ +  // board
    board_size_ * board_size_ * (num_players_ + 1) +  // player + flag positions
    // thermometer of bits representation of the chips (proposers + receiver)
    (kNumChipsUpperBound + 1) * num_colors_ * 3 +
    // thermometer of bits representation of the proposals
    // 0 to upperboard of chip combos for each in X for Y, and max two proposals
    (kNumChipsUpperBound + 1) * num_colors_ * 2 * (num_players_ - 1)
  };
}
Referenced by ObservationTensorShape().
LookupTrade()
const Trade & open_spiel::colored_trails::ColoredTrailsGame::LookupTrade (int trade_id) const inline
Definition at line 232 of file colored_trails.h.
{
    if (trade_id == PassAction()) {
      return pass_trade_;
    } else {
      return *(trade_info_.possible_trades.at(trade_id));
    }
  }
References PassAction(), and open_spiel::colored_trails::TradeInfo::possible_trades.
Referenced by open_spiel::colored_trails::ColoredTrailsState::ActionToString(), open_spiel::colored_trails::ColoredTrailsState::DoApplyAction(), and open_spiel::colored_trails::ColoredTrailsState::SetChipsAndTradeProposal().
LookupTradeId()
int open_spiel::colored_trails::ColoredTrailsGame::LookupTradeId (const std::string & trade_str) const inline
Definition at line 248 of file colored_trails.h.
{
    return trade_info_.trade_str_to_id.at(trade_str);
  }
References open_spiel::colored_trails::TradeInfo::trade_str_to_id.
LookupTradesCache()
std::vector< Action > open_spiel::colored_trails::ColoredTrailsGame::LookupTradesCache (const std::string & key) const
Definition at line 762 of file colored_trails.cc.
{
  const auto& iter = trades_cache_.find(key);
  if (iter == trades_cache_.end()) {
    return {};
  }
  return iter->second;
}
References key.
Referenced by SampleRandomBoardCompletion().
MaxChanceNodesInHistory()
int open_spiel::colored_trails::ColoredTrailsGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 215 of file colored_trails.h.
{ return MaxGameLength(); }
References MaxGameLength().
MaxChanceOutcomes()
int open_spiel::colored_trails::ColoredTrailsGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 212 of file colored_trails.h.
{ return all_boards_.size(); }
MaxGameLength()
int open_spiel::colored_trails::ColoredTrailsGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 214 of file colored_trails.h.
{ return 3; }
Referenced by MaxChanceNodesInHistory().
MaxUtility()
double open_spiel::colored_trails::ColoredTrailsGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 218 of file colored_trails.h.
{
    // Get max chips, then do a 1-for-8 trade, and only use 1 chip.
    // = 0 (for reaching goal) + (8 - 1 + 8) * leftover_chip_value
    return kLeftoverChipScore * (kNumChipsUpperBound - 1 + kNumChipsUpperBound);
  }
References open_spiel::colored_trails::kLeftoverChipScore, and open_spiel::colored_trails::kNumChipsUpperBound.
MinUtility()
double open_spiel::colored_trails::ColoredTrailsGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 223 of file colored_trails.h.
{
    // No chips left and as far away from the goal as possible.
    return board_size_ * board_size_ * kFlagPenaltyPerCell;
  }
References open_spiel::colored_trails::kFlagPenaltyPerCell.
NewInitialState()
std::unique_ptr< State > open_spiel::colored_trails::ColoredTrailsGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 208 of file colored_trails.h.
{
    return std::unique_ptr<State>(
        new ColoredTrailsState(shared_from_this(), board_size_, num_colors_));
  }
Referenced by open_spiel::colored_trails::ColoredTrailsState::ResampleFromInfostate().
NumDistinctActions()
int open_spiel::colored_trails::ColoredTrailsGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 740 of file colored_trails.cc.
{
  return trade_info_.possible_trades.size() + 3;
}
References open_spiel::colored_trails::TradeInfo::possible_trades.
Referenced by PassAction(), and ResponderTradeWithPlayerAction().
NumPlayers()
int open_spiel::colored_trails::ColoredTrailsGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 217 of file colored_trails.h.
{ return num_players_; }
ObservationTensorShape()
std::vector< int > open_spiel::colored_trails::ColoredTrailsGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 744 of file colored_trails.cc.
{
  return InformationStateTensorShape();
}
References InformationStateTensorShape().
PassAction()
Action open_spiel::colored_trails::ColoredTrailsGame::PassAction () const inline
Definition at line 246 of file colored_trails.h.
{ return NumDistinctActions() - 1; }
References NumDistinctActions().
Referenced by open_spiel::colored_trails::ColoredTrailsState::DoApplyAction(), open_spiel::colored_trails::ColoredTrailsState::LegalActions(), and LookupTrade().
ResponderTradeWithPlayerAction()
Action open_spiel::colored_trails::ColoredTrailsGame::ResponderTradeWithPlayerAction (Player player) const inline
Definition at line 240 of file colored_trails.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LE(player, 1);
    return NumDistinctActions() - 3 + player;
  }
References NumDistinctActions(), player, SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Referenced by open_spiel::colored_trails::ColoredTrailsState::DoApplyAction(), and open_spiel::colored_trails::ColoredTrailsState::LegalActions().
SampleRandomBoardCompletion()
std::pair< Board, Action > open_spiel::colored_trails::ColoredTrailsGame::SampleRandomBoardCompletion (int seed, const Board & board, Player player) const
Definition at line 875 of file colored_trails.cc.
{
  std::mt19937 rng(seed);
  Board new_board = board;
  const int max_tries = 1000;
  int tries = 0;
  do {
    tries += 1;
    for (int i = 0; i < new_board.chips[player].size(); ++i) {
      new_board.chips[player][i] = 0;
    }
    int width = kNumChipsUpperBound - kNumChipsLowerBound + 1;
    new_board.num_chips[player] =
        kNumChipsLowerBound + absl::Uniform<int>(rng, 0, width);
    for (int i = 0; i < new_board.num_chips[player]; ++i) {
      int chip = absl::Uniform<int>(rng, 0, new_board.num_colors);
      new_board.chips[player][chip]++;
    }
  } while (!CheckBoardForProposer(new_board, player) && tries < max_tries);
  SPIEL_CHECK_LT(tries, max_tries);
  std::string key = absl::StrCat(ComboToString(new_board.chips[player]), " ",
                                 ComboToString(new_board.chips[kResponderId]));
  std::vector<Action> actions = LookupTradesCache(key);
  if (actions.empty()) {
    actions = GenerateLegalActionsForChips(this, new_board,
                                           new_board.chips[player],
                                           new_board.chips[kResponderId]);
    AddToTradesCache(key, actions);
  }
  Action action = actions[absl::Uniform<int>(rng, 0, actions.size())];
  return {new_board, action};
}
References action, AddToTradesCache(), open_spiel::colored_trails::CheckBoardForProposer(), open_spiel::colored_trails::Board::chips, open_spiel::colored_trails::ComboToString(), i, key, open_spiel::colored_trails::kResponderId, LookupTradesCache(), open_spiel::colored_trails::Board::num_chips, open_spiel::colored_trails::Board::num_colors, player, SPIEL_CHECK_LT, absl::StrCat(), and absl::Uniform().
The documentation for this class was generated from the following files:
open_spiel/games/colored_trails/colored_trails.h
open_spiel/games/colored_trails/colored_trails.cc