open spiel: absl::Cord Class Reference
absl::Cord Class Reference
#include <cord.h>
Classes
class CharIterator
class CharRange
class ChunkIterator
class ChunkRange
Public Member Functions
constexpr Cord () noexcept
Cord (const Cord &src)
Cord (Cord &&src) noexcept
Cord & operator= (const Cord &x)
Cord & operator= (Cord &&x) noexcept
Cord (absl::string_view src)
Cord & operator= (absl::string_view src)
template<typename T , EnableIfString< T > = 0>
Cord (T &&src)
template<typename T , EnableIfString< T > = 0>
Cord & operator= (T &&src)
~Cord ()
ABSL_ATTRIBUTE_REINITIALIZES void Clear ()
void Append (const Cord &src)
void Append (Cord &&src)
void Append (absl::string_view src)
template<typename T , EnableIfString< T > = 0>
void Append (T &&src)
void Append (CordBuffer buffer)
CordBuffer GetAppendBuffer (size_t capacity, size_t min_capacity=16)
CordBuffer GetCustomAppendBuffer (size_t block_size, size_t capacity, size_t min_capacity=16)
void Prepend (const Cord &src)
void Prepend (absl::string_view src)
template<typename T , EnableIfString< T > = 0>
void Prepend (T &&src)
void Prepend (CordBuffer buffer)
void RemovePrefix (size_t n)
void RemoveSuffix (size_t n)
Cord Subcord (size_t pos, size_t new_size) const
void swap (Cord &other) noexcept
size_t size () const
bool empty () const
size_t EstimatedMemoryUsage (CordMemoryAccounting accounting_method=CordMemoryAccounting::kTotal) const
int Compare (absl::string_view rhs) const
int Compare (const Cord &rhs) const
bool StartsWith (const Cord &rhs) const
bool StartsWith (absl::string_view rhs) const
bool EndsWith (absl::string_view rhs) const
bool EndsWith (const Cord &rhs) const
operator std::string () const
ChunkIterator chunk_begin () const
ChunkIterator chunk_end () const
ChunkRange Chunks () const
CharIterator char_begin () const
CharIterator char_end () const
CharRange Chars () const
char operator[] (size_t i) const
absl::optional< absl::string_view > TryFlat () const
absl::string_view Flatten ()
void SetExpectedChecksum (uint32_t crc)
absl::optional< uint32_t > ExpectedChecksum () const
template<typename T >
constexpr Cord (strings_internal::StringConstant< T >)
Static Public Member Functions
static Cord AdvanceAndRead (CharIterator *it, size_t n_bytes)
static void Advance (CharIterator *it, size_t n_bytes)
static absl::string_view ChunkRemaining (const CharIterator &it)
Friends
class CordTestPeer
class CrcCord
template<typename Releaser >
Cord MakeCordFromExternal (absl::string_view data, Releaser &&releaser)
void swap (Cord &x, Cord &y) noexcept
void CopyCordToString (const Cord &src, std::string *dst)
void AbslFormatFlush (absl::Cord *cord, absl::string_view part)
template<typename H >
H AbslHashValue (H hash_state, const absl::Cord &c)
bool operator== (const Cord &lhs, const Cord &rhs)
bool operator== (const Cord &lhs, absl::string_view rhs)
const CordzInfo * GetCordzInfoForTesting (const Cord &cord)
template<typename ResultType , typename RHS >
ResultType GenericCompare (const Cord &lhs, const RHS &rhs, size_t size_to_compare)
Detailed Description
Definition at line 150 of file cord.h.
Constructor & Destructor Documentation
Cord() [1/6]
absl::Cord::Cord () inline constexpr noexcept
Definition at line 1222 of file cord.h.
{}
Referenced by EstimatedMemoryUsage().
Cord() [2/6]
absl::Cord::Cord (const Cord & src) inline
Definition at line 1250 of file cord.h.
: contents_(src.contents_) {}
Cord() [3/6]
absl::Cord::Cord (Cord && src) inline noexcept
Definition at line 1252 of file cord.h.
: contents_(std::move(src.contents_)) {}
Cord() [4/6]
absl::Cord::Cord (absl::string_view src) inline explicit
Definition at line 1224 of file cord.h.
    : Cord(src, CordzUpdateTracker::kConstructorString) {}
Cord() [5/6]
template<typename T , Cord::EnableIfString< T > > absl::Cord::Cord (T && src) explicit
Definition at line 343 of file cord.cc.
                  : contents_(InlineData::kDefaultInit) {
  if (src.size() <= InlineRep::kMaxInline) {
    contents_.set_data(src.data(), src.size());
  } else {
    CordRep* rep = CordRepFromString(std::forward<T>(src));
    contents_.EmplaceTree(rep, CordzUpdateTracker::kConstructorString);
  }
}
References absl::string_view::data(), absl::cord_internal::CordzUpdateTracker::kConstructorString, rep, and absl::string_view::size().
~Cord()
absl::Cord::~Cord () inline
Definition at line 186 of file cord.h.
          {
    if (contents_.is_tree()) DestroyCordSlow();
  }
Cord() [6/6]
template<typename T > absl::Cord::Cord (strings_internal::StringConstant< T >) constexpr
Definition at line 1228 of file cord.h.
    : contents_(strings_internal::StringConstant<T>::value,
                strings_internal::StringConstant<T>::value.size() <=
                        cord_internal::kMaxInline
                    ? nullptr
                    : &cord_internal::ConstInitExternalStorage<
                          strings_internal::StringConstant<T>>::value) {}
Member Function Documentation
Advance()
void absl::Cord::Advance (CharIterator * it, size_t n_bytes) inline static
Definition at line 1538 of file cord.h.
{
  assert(it != nullptr);
  it->chunk_iterator_.AdvanceBytes(n_bytes);
}
Referenced by TEST_P().
AdvanceAndRead()
Cord absl::Cord::AdvanceAndRead (CharIterator * it, size_t n_bytes) inline static
Definition at line 1533 of file cord.h.
{
  assert(it != nullptr);
  return it->chunk_iterator_.AdvanceAndReadBytes(n_bytes);
}
Referenced by TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
Append() [1/5]
void absl::Cord::Append (absl::string_view src) inline
Definition at line 1310 of file cord.h.
{
  contents_.AppendArray(src, CordzUpdateTracker::kAppendString);
}
References absl::cord_internal::CordzUpdateTracker::kAppendString.
Append() [2/5]
void absl::Cord::Append (const Cord & src)
Definition at line 577 of file cord.cc.
{
  AppendImpl(src);
}
Referenced by Append(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
Append() [3/5]
void absl::Cord::Append (Cord && src)
Definition at line 581 of file cord.cc.
{
  AppendImpl(std::move(src));
}
Append() [4/5]
void absl::Cord::Append (CordBuffer buffer) inline
Definition at line 1318 of file cord.h.
{
  if (ABSL_PREDICT_FALSE(buffer.length() == 0)) return;
  absl::string_view short_value;
  if (CordRep* rep = buffer.ConsumeValue(short_value)) {
    contents_.AppendTree(rep, CordzUpdateTracker::kAppendCordBuffer);
  } else {
    AppendPrecise(short_value, CordzUpdateTracker::kAppendCordBuffer);
  }
}
References ABSL_PREDICT_FALSE, absl::cord_internal::CordzUpdateTracker::kAppendCordBuffer, absl::CordBuffer::length(), and rep.
Append() [5/5]
template<typename T , Cord::EnableIfString< T > > void absl::Cord::Append (T && src)
Definition at line 586 of file cord.cc.
{
  if (src.size() <= kMaxBytesToCopy) {
    Append(absl::string_view(src));
  } else {
    CordRep* rep = CordRepFromString(std::forward<T>(src));
    contents_.AppendTree(rep, CordzUpdateTracker::kAppendString);
  }
}
References Append(), absl::cord_internal::CordzUpdateTracker::kAppendString, rep, and absl::string_view::size().
char_begin()
Cord::CharIterator absl::Cord::char_begin () const inline
Definition at line 1547 of file cord.h.
{
  return CharIterator(this);
}
Referenced by TEST_P(), TEST_P(), and TEST_P().
char_end()
Cord::CharIterator absl::Cord::char_end () const inline
Definition at line 1551 of file cord.h.
{ return CharIterator(); }
Referenced by TEST_P().
Chars()
Cord::CharRange absl::Cord::Chars () const inline
Definition at line 1561 of file cord.h.
{ return CharRange(this); }
Referenced by TEST_P(), TEST_P(), TEST_P(), and TEST_P().
chunk_begin()
Cord::ChunkIterator absl::Cord::chunk_begin () const inline
Definition at line 1486 of file cord.h.
{
  return ChunkIterator(this);
}
Referenced by Subcord(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
chunk_end()
Cord::ChunkIterator absl::Cord::chunk_end () const inline
Definition at line 1490 of file cord.h.
{ return ChunkIterator(); }
Referenced by TEST_P(), TEST_P(), TEST_P(), and TEST_P().
ChunkRemaining()
absl::string_view absl::Cord::ChunkRemaining (const CharIterator & it) inline static
Definition at line 1543 of file cord.h.
{
  return *it.chunk_iterator_;
}
Referenced by TEST_P().
Chunks()
Cord::ChunkRange absl::Cord::Chunks () const inline
Definition at line 1500 of file cord.h.
{ return ChunkRange(this); }
Referenced by absl::operator<<(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
Clear()
void absl::Cord::Clear ()
Definition at line 365 of file cord.cc.
                 {
  if (CordRep* tree = contents_.clear()) {
    CordRep::Unref(tree);
  }
}
References absl::cord_internal::CordRep::Unref().
Compare() [1/2]
int absl::Cord::Compare (absl::string_view rhs) const
Definition at line 1011 of file cord.cc.
{
  return SharedCompareImpl(*this, rhs);
}
References absl::SharedCompareImpl().
Referenced by absl::container_internal::StringBtreeDefaultGreater::operator()(), absl::container_internal::StringBtreeDefaultGreater::operator()(), absl::container_internal::StringBtreeDefaultGreater::operator()(), absl::container_internal::StringBtreeDefaultLess::operator()(), absl::container_internal::StringBtreeDefaultLess::operator()(), absl::container_internal::StringBtreeDefaultLess::operator()(), TEST_P(), TEST_P(), and TEST_P().
Compare() [2/2]
int absl::Cord::Compare (const Cord & rhs) const inline
Definition at line 1356 of file cord.h.
{
  if (!contents_.is_tree() && !rhs.contents_.is_tree()) {
    return contents_.data_.Compare(rhs.contents_.data_);
  }
  return CompareImpl(rhs);
}
empty()
bool absl::Cord::empty () const inline
Definition at line 1270 of file cord.h.
{ return size() == 0; }
References size().
Referenced by GetAppendBuffer(), GetCustomAppendBuffer(), Prepend(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
EndsWith() [1/2]
bool absl::Cord::EndsWith (absl::string_view rhs) const
Definition at line 1019 of file cord.cc.
{
  size_t my_size = size();
  size_t rhs_size = rhs.size();
  if (my_size < rhs_size) return false;
  Cord tmp(*this);
  tmp.RemovePrefix(my_size - rhs_size);
  return tmp.EqualsImpl(rhs, rhs_size);
}
References RemovePrefix(), size(), and absl::string_view::size().
Referenced by TEST_P(), and TEST_P().
EndsWith() [2/2]
bool absl::Cord::EndsWith (const Cord & rhs) const
Definition at line 1030 of file cord.cc.
{
  size_t my_size = size();
  size_t rhs_size = rhs.size();
  if (my_size < rhs_size) return false;
  Cord tmp(*this);
  tmp.RemovePrefix(my_size - rhs_size);
  return tmp.EqualsImpl(rhs, rhs_size);
}
References RemovePrefix(), and size().
EstimatedMemoryUsage()
size_t absl::Cord::EstimatedMemoryUsage (CordMemoryAccounting accounting_method = CordMemoryAccounting::kTotal) const inline
Definition at line 1272 of file cord.h.
{
  size_t result = sizeof(Cord);
  if (const absl::cord_internal::CordRep* rep = contents_.tree()) {
    if (accounting_method == CordMemoryAccounting::kFairShare) {
      result += cord_internal::GetEstimatedFairShareMemoryUsage(rep);
    } else {
      result += cord_internal::GetEstimatedMemoryUsage(rep);
    }
  }
  return result;
}
References Cord(), absl::cord_internal::GetEstimatedFairShareMemoryUsage(), absl::cord_internal::GetEstimatedMemoryUsage(), absl::kFairShare, and rep.
Referenced by TEST_P(), TEST_P(), and TEST_P().
ExpectedChecksum()
absl::optional< uint32_t > absl::Cord::ExpectedChecksum () const
Definition at line 888 of file cord.cc.
{
  if (!contents_.is_tree() || !contents_.tree()->IsCrc()) {
    return absl::nullopt;
  }
  return static_cast<uint32_t>(
      contents_.tree()->crc()->crc_cord_state.Checksum());
}
References absl::crc_internal::CrcCordState::Checksum(), absl::cord_internal::CordRep::crc(), absl::cord_internal::CordRepCrc::crc_cord_state, and absl::cord_internal::CordRep::IsCrc().
Referenced by absl::CordTestPeer::MakeSubstring(), TEST_P(), TEST_P(), and TEST_P().
Flatten()
absl::string_view absl::Cord::Flatten () inline
Definition at line 1297 of file cord.h.
{
  absl::cord_internal::CordRep* rep = contents_.tree();
  if (rep == nullptr) {
    return absl::string_view(contents_.data(), contents_.size());
  } else {
    absl::string_view already_flat_contents;
    if (GetFlatAux(rep, &already_flat_contents)) {
      return already_flat_contents;
    }
  }
  return FlattenSlowPath();
}
References rep.
Referenced by FlatCord().
GetAppendBuffer()
CordBuffer absl::Cord::GetAppendBuffer (size_t capacity, size_t min_capacity = 16) inline
Definition at line 1338 of file cord.h.
{
  if (empty()) return CordBuffer::CreateWithDefaultLimit(capacity);
  return GetAppendBufferSlowPath(0, capacity, min_capacity);
}
References absl::CordBuffer::CreateWithDefaultLimit(), and empty().
Referenced by CordAppendBufferTest::GetAppendBuffer().
GetCustomAppendBuffer()
CordBuffer absl::Cord::GetCustomAppendBuffer (size_t block_size, size_t capacity, size_t min_capacity = 16) inline
Definition at line 1343 of file cord.h.
{
  if (empty()) {
    return block_size ? CordBuffer::CreateWithCustomLimit(block_size, capacity)
                      : CordBuffer::CreateWithDefaultLimit(capacity);
  }
  return GetAppendBufferSlowPath(block_size, capacity, min_capacity);
}
References absl::CordBuffer::CreateWithCustomLimit(), absl::CordBuffer::CreateWithDefaultLimit(), and empty().
Referenced by CordAppendBufferTest::GetAppendBuffer().
operator std::string()
absl::Cord::operator std::string () const explicit
Definition at line 1044 of file cord.cc.
{
  std::string s;
  absl::CopyCordToString(*this, &s);
  return s;
}
References absl::CopyCordToString(), and absl::s.
operator=() [1/4]
Cord & absl::Cord::operator= (absl::string_view src)
Definition at line 385 of file cord.cc.
{
  auto constexpr method = CordzUpdateTracker::kAssignString;
  const char* data = src.data();
  size_t length = src.size();
  CordRep* tree = contents_.tree();
  if (length <= InlineRep::kMaxInline) {
    // Embed into this->contents_, which is somewhat subtle:
    // - MaybeUntrackCord must be called before Unref(tree).
    // - MaybeUntrackCord must be called before set_data() clobbers cordz_info.
    // - set_data() must be called before Unref(tree) as it may reference tree.
    if (tree != nullptr) CordzInfo::MaybeUntrackCord(contents_.cordz_info());
    contents_.set_data(data, length);
    if (tree != nullptr) CordRep::Unref(tree);
    return *this;
  }
  if (tree != nullptr) {
    CordzUpdateScope scope(contents_.cordz_info(), method);
    if (tree->IsFlat() && tree->flat()->Capacity() >= length &&
        tree->refcount.IsOne()) {
      // Copy in place if the existing FLAT node is reusable.
      memmove(tree->flat()->Data(), data, length);
      tree->length = length;
      VerifyTree(tree);
      return *this;
    }
    contents_.SetTree(NewTree(data, length, 0), scope);
    CordRep::Unref(tree);
  } else {
    contents_.EmplaceTree(NewTree(data, length, 0), method);
  }
  return *this;
}
References absl::cord_internal::CordRepFlat::Capacity(), absl::cord_internal::CordRepFlat::Data(), absl::string_view::data(), absl::cord_internal::CordRep::flat(), absl::cord_internal::CordRep::IsFlat(), absl::cord_internal::RefcountAndFlags::IsOne(), absl::cord_internal::CordzUpdateTracker::kAssignString, absl::cord_internal::CordRep::length, absl::cord_internal::CordzInfo::MaybeUntrackCord(), absl::cord_internal::CordRep::refcount, absl::string_view::size(), and absl::cord_internal::CordRep::Unref().
operator=() [2/4]
Cord & absl::Cord::operator= (const Cord & x) inline
Definition at line 1236 of file cord.h.
{
  contents_ = x.contents_;
  return *this;
}
References absl::x.
Referenced by operator=().
operator=() [3/4]
Cord & absl::Cord::operator= (Cord && x) inline noexcept
Definition at line 1258 of file cord.h.
{
  contents_ = std::move(x.contents_);
  return *this;
}
References absl::x.
operator=() [4/4]
template<typename T , Cord::EnableIfString< T > > Cord & absl::Cord::operator= (T && src)
Definition at line 1242 of file cord.h.
{
  if (src.size() <= cord_internal::kMaxBytesToCopy) {
    return operator=(absl::string_view(src));
  } else {
    return AssignLargeString(std::forward<T>(src));
  }
}
References absl::cord_internal::kMaxBytesToCopy, and operator=().
operator[]()
char absl::Cord::operator[] (size_t i) const
Definition at line 1141 of file cord.cc.
{
  ABSL_HARDENING_ASSERT(i < size());
  size_t offset = i;
  const CordRep* rep = contents_.tree();
  if (rep == nullptr) {
    return contents_.data()[i];
  }
  rep = cord_internal::SkipCrcNode(rep);
  while (true) {
    assert(rep != nullptr);
    assert(offset < rep->length);
    if (rep->IsFlat()) {
      // Get the "i"th character directly from the flat array.
      return rep->flat()->Data()[offset];
    } else if (rep->IsBtree()) {
      return rep->btree()->GetCharacter(offset);
    } else if (rep->IsExternal()) {
      // Get the "i"th character from the external array.
      return rep->external()->base[offset];
    } else {
      // This must be a substring a node, so bypass it to get to the child.
      assert(rep->IsSubstring());
      offset += rep->substring()->start;
      rep = rep->substring()->child;
    }
  }
}
References ABSL_HARDENING_ASSERT, absl::cord_internal::CordRepExternal::base, absl::cord_internal::CordRep::btree(), absl::cord_internal::CordRepSubstring::child, absl::cord_internal::CordRepFlat::Data(), absl::cord_internal::CordRep::external(), absl::cord_internal::CordRep::flat(), absl::cord_internal::CordRepBtree::GetCharacter(), absl::i, absl::cord_internal::CordRep::IsBtree(), absl::cord_internal::CordRep::IsExternal(), absl::cord_internal::CordRep::IsFlat(), absl::cord_internal::CordRep::IsSubstring(), rep, size(), absl::cord_internal::SkipCrcNode(), absl::cord_internal::CordRepSubstring::start, and absl::cord_internal::CordRep::substring().
Prepend() [1/4]
void absl::Cord::Prepend (absl::string_view src) inline
Definition at line 1314 of file cord.h.
{
  PrependArray(src, CordzUpdateTracker::kPrependString);
}
References absl::cord_internal::CordzUpdateTracker::kPrependString.
Prepend() [2/4]
void absl::Cord::Prepend (const Cord & src)
Definition at line 597 of file cord.cc.
{
  contents_.MaybeRemoveEmptyCrcNode();
  if (src.empty()) return;
  CordRep* src_tree = src.contents_.tree();
  if (src_tree != nullptr) {
    CordRep::Ref(src_tree);
    contents_.PrependTree(cord_internal::RemoveCrcNode(src_tree),
                          CordzUpdateTracker::kPrependCord);
    return;
  }
  // `src` cord is inlined.
  absl::string_view src_contents(src.contents_.data(), src.contents_.size());
  return Prepend(src_contents);
}
References empty(), absl::cord_internal::CordzUpdateTracker::kPrependCord, Prepend(), absl::cord_internal::CordRep::Ref(), and absl::cord_internal::RemoveCrcNode().
Referenced by absl::MakeFragmentedCord(), Prepend(), Prepend(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
Prepend() [3/4]
void absl::Cord::Prepend (CordBuffer buffer) inline
Definition at line 1328 of file cord.h.
{
  if (ABSL_PREDICT_FALSE(buffer.length() == 0)) return;
  absl::string_view short_value;
  if (CordRep* rep = buffer.ConsumeValue(short_value)) {
    contents_.PrependTree(rep, CordzUpdateTracker::kPrependCordBuffer);
  } else {
    PrependPrecise(short_value, CordzUpdateTracker::kPrependCordBuffer);
  }
}
References ABSL_PREDICT_FALSE, absl::cord_internal::CordzUpdateTracker::kPrependCordBuffer, absl::CordBuffer::length(), and rep.
Prepend() [4/4]
template<typename T , Cord::EnableIfString< T > > void absl::Cord::Prepend (T && src) inline
Definition at line 662 of file cord.cc.
{
  if (src.size() <= kMaxBytesToCopy) {
    Prepend(absl::string_view(src));
  } else {
    CordRep* rep = CordRepFromString(std::forward<T>(src));
    contents_.PrependTree(rep, CordzUpdateTracker::kPrependString);
  }
}
References absl::cord_internal::CordzUpdateTracker::kPrependString, Prepend(), rep, and absl::string_view::size().
RemovePrefix()
void absl::Cord::RemovePrefix (size_t n)
Definition at line 673 of file cord.cc.
{
  ABSL_INTERNAL_CHECK(n <= size(),
                      absl::StrCat("Requested prefix size ", n,
                                   " exceeds Cord's size ", size()));
  contents_.MaybeRemoveEmptyCrcNode();
  CordRep* tree = contents_.tree();
  if (tree == nullptr) {
    contents_.remove_prefix(n);
  } else {
    auto constexpr method = CordzUpdateTracker::kRemovePrefix;
    CordzUpdateScope scope(contents_.cordz_info(), method);
    tree = cord_internal::RemoveCrcNode(tree);
    if (n >= tree->length) {
      CordRep::Unref(tree);
      tree = nullptr;
    } else if (tree->IsBtree()) {
      CordRep* old = tree;
      tree = tree->btree()->SubTree(n, tree->length - n);
      CordRep::Unref(old);
    } else if (tree->IsSubstring() && tree->refcount.IsOne()) {
      tree->substring()->start += n;
      tree->length -= n;
    } else {
      CordRep* rep = CordRepSubstring::Substring(tree, n, tree->length - n);
      CordRep::Unref(tree);
      tree = rep;
    }
    contents_.SetTreeOrEmpty(tree, scope);
  }
}
References ABSL_INTERNAL_CHECK, absl::cord_internal::CordRep::btree(), absl::cord_internal::CordRep::IsBtree(), absl::cord_internal::RefcountAndFlags::IsOne(), absl::cord_internal::CordRep::IsSubstring(), absl::cord_internal::CordzUpdateTracker::kRemovePrefix, absl::cord_internal::CordRep::length, absl::n, absl::cord_internal::CordRep::refcount, absl::cord_internal::RemoveCrcNode(), rep, size(), absl::cord_internal::CordRepSubstring::start, absl::StrCat(), absl::cord_internal::CordRep::substring(), absl::cord_internal::CordRepBtree::SubTree(), and absl::cord_internal::CordRep::Unref().
Referenced by EndsWith(), EndsWith(), TEST_P(), TEST_P(), and TEST_P().
RemoveSuffix()
void absl::Cord::RemoveSuffix (size_t n)
Definition at line 704 of file cord.cc.
{
  ABSL_INTERNAL_CHECK(n <= size(),
                      absl::StrCat("Requested suffix size ", n,
                                   " exceeds Cord's size ", size()));
  contents_.MaybeRemoveEmptyCrcNode();
  CordRep* tree = contents_.tree();
  if (tree == nullptr) {
    contents_.reduce_size(n);
  } else {
    auto constexpr method = CordzUpdateTracker::kRemoveSuffix;
    CordzUpdateScope scope(contents_.cordz_info(), method);
    tree = cord_internal::RemoveCrcNode(tree);
    if (n >= tree->length) {
      CordRep::Unref(tree);
      tree = nullptr;
    } else if (tree->IsBtree()) {
      tree = CordRepBtree::RemoveSuffix(tree->btree(), n);
    } else if (!tree->IsExternal() && tree->refcount.IsOne()) {
      assert(tree->IsFlat() || tree->IsSubstring());
      tree->length -= n;
    } else {
      CordRep* rep = CordRepSubstring::Substring(tree, 0, tree->length - n);
      CordRep::Unref(tree);
      tree = rep;
    }
    contents_.SetTreeOrEmpty(tree, scope);
  }
}
References ABSL_INTERNAL_CHECK, absl::cord_internal::CordRep::btree(), absl::cord_internal::CordRep::IsBtree(), absl::cord_internal::CordRep::IsExternal(), absl::cord_internal::CordRep::IsFlat(), absl::cord_internal::RefcountAndFlags::IsOne(), absl::cord_internal::CordRep::IsSubstring(), absl::cord_internal::CordzUpdateTracker::kRemoveSuffix, absl::cord_internal::CordRep::length, absl::n, absl::cord_internal::CordRep::refcount, absl::cord_internal::RemoveCrcNode(), rep, size(), absl::StrCat(), and absl::cord_internal::CordRep::Unref().
Referenced by TEST_P(), and TEST_P().
SetExpectedChecksum()
void absl::Cord::SetExpectedChecksum (uint32_t crc)
Definition at line 873 of file cord.cc.
{
  // Construct a CrcCordState with a single chunk.
  crc_internal::CrcCordState state;
  state.mutable_rep()->prefix_crc.push_back(
      crc_internal::CrcCordState::PrefixCrc(size(), absl::crc32c_t{crc}));
  SetCrcCordState(std::move(state));
}
References absl::crc_internal::CrcCordState::mutable_rep(), absl::crc_internal::CrcCordState::Rep::prefix_crc, size(), and state.
Referenced by TEST_P(), and TEST_P().
size()
size_t absl::Cord::size () const inline
Definition at line 1265 of file cord.h.
{
  // Length is 1st field in str.rep_
  return contents_.size();
}
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), empty(), EndsWith(), EndsWith(), FragmentedCord(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), operator[](), RemovePrefix(), RemoveSuffix(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), SetExpectedChecksum(), absl::SharedCompareImpl(), StartsWith(), StartsWith(), Subcord(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
StartsWith() [1/2]
bool absl::Cord::StartsWith (absl::string_view rhs) const inline
Definition at line 1372 of file cord.h.
{
  size_t rhs_size = rhs.size();
  if (size() < rhs_size) return false;
  return EqualsImpl(rhs, rhs_size);
}
References size(), and absl::string_view::size().
StartsWith() [2/2]
bool absl::Cord::StartsWith (const Cord & rhs) const inline
Definition at line 1365 of file cord.h.
{
  if (contents_.IsSame(rhs.contents_)) return true;
  size_t rhs_size = rhs.size();
  if (size() < rhs_size) return false;
  return EqualsImpl(rhs, rhs_size);
}
References size().
Referenced by TEST_P(), TEST_P(), and TEST_P().
Subcord()
Cord absl::Cord::Subcord (size_t pos, size_t new_size) const
Definition at line 733 of file cord.cc.
{
  Cord sub_cord;
  size_t length = size();
  if (pos > length) pos = length;
  if (new_size > length - pos) new_size = length - pos;
  if (new_size == 0) return sub_cord;
  CordRep* tree = contents_.tree();
  if (tree == nullptr) {
    sub_cord.contents_.set_data(contents_.data() + pos, new_size);
    return sub_cord;
  }
  if (new_size <= InlineRep::kMaxInline) {
    sub_cord.contents_.set_inline_size(new_size);
    char* dest = sub_cord.contents_.data_.as_chars();
    Cord::ChunkIterator it = chunk_begin();
    it.AdvanceBytes(pos);
    size_t remaining_size = new_size;
    while (remaining_size > it->size()) {
      cord_internal::SmallMemmove(dest, it->data(), it->size());
      remaining_size -= it->size();
      dest += it->size();
      ++it;
    }
    cord_internal::SmallMemmove(dest, it->data(), remaining_size);
    return sub_cord;
  }
  tree = cord_internal::SkipCrcNode(tree);
  if (tree->IsBtree()) {
    tree = tree->btree()->SubTree(pos, new_size);
  } else {
    tree = CordRepSubstring::Substring(tree, pos, new_size);
  }
  sub_cord.contents_.EmplaceTree(tree, contents_.data_,
                                 CordzUpdateTracker::kSubCord);
  return sub_cord;
}
References absl::cord_internal::InlineData::as_chars(), absl::cord_internal::CordRep::btree(), chunk_begin(), absl::string_view::data(), absl::cord_internal::CordRep::IsBtree(), absl::cord_internal::CordzUpdateTracker::kSubCord, size(), absl::string_view::size(), absl::cord_internal::SkipCrcNode(), absl::cord_internal::SmallMemmove(), and absl::cord_internal::CordRepBtree::SubTree().
Referenced by TEST_P(), TEST_P(), TEST_P(), and TEST_P().
swap()
void absl::Cord::swap (Cord & other) inline noexcept
Definition at line 1254 of file cord.h.
{
  contents_.Swap(&other.contents_);
}
TryFlat()
absl::optional< absl::string_view > absl::Cord::TryFlat () const inline
Definition at line 1285 of file cord.h.
{
  absl::cord_internal::CordRep* rep = contents_.tree();
  if (rep == nullptr) {
    return absl::string_view(contents_.data(), contents_.size());
  }
  absl::string_view fragment;
  if (GetFlatAux(rep, &fragment)) {
    return fragment;
  }
  return absl::nullopt;
}
References rep.
Referenced by TEST_P(), TEST_P(), and TEST_P().
Friends And Related Symbol Documentation
AbslFormatFlush
void AbslFormatFlush (absl::Cord * cord, absl::string_view part) friend
Definition at line 729 of file cord.h.
{
    cord->Append(part);
  }
AbslHashValue
template<typename H > H AbslHashValue (H hash_state, const absl::Cord & c) friend
Definition at line 757 of file cord.h.
{
    absl::optional<absl::string_view> maybe_flat = c.TryFlat();
    if (maybe_flat.has_value()) {
      return H::combine(std::move(hash_state), *maybe_flat);
    }
    return c.HashFragmented(std::move(hash_state));
  }
CopyCordToString
void CopyCordToString (const Cord & src, std::string * dst) friend
Definition at line 1050 of file cord.cc.
{
  if (!src.contents_.is_tree()) {
    src.contents_.CopyTo(dst);
  } else {
    absl::strings_internal::STLStringResizeUninitialized(dst, src.size());
    src.CopyToArraySlowPath(&(*dst)[0]);
  }
}
CordTestPeer
friend class CordTestPeer friend
Definition at line 787 of file cord.h.
CrcCord
friend class CrcCord friend
Definition at line 1006 of file cord.h.
GenericCompare
template<typename ResultType , typename RHS > ResultType GenericCompare (const Cord & lhs, const RHS & rhs, size_t size_to_compare) friend
Definition at line 971 of file cord.cc.
{
  absl::string_view lhs_chunk = Cord::GetFirstChunk(lhs);
  absl::string_view rhs_chunk = Cord::GetFirstChunk(rhs);
  size_t compared_size = std::min(lhs_chunk.size(), rhs_chunk.size());
  assert(size_to_compare >= compared_size);
  int memcmp_res = ::memcmp(lhs_chunk.data(), rhs_chunk.data(), compared_size);
  if (compared_size == size_to_compare || memcmp_res != 0) {
    return ComputeCompareResult<ResultType>(memcmp_res);
  }
  return ComputeCompareResult<ResultType>(
      lhs.CompareSlowPath(rhs, compared_size, size_to_compare));
}
Referenced by absl::SharedCompareImpl().
GetCordzInfoForTesting
const CordzInfo * GetCordzInfoForTesting (const Cord & cord) friend
Definition at line 36 of file cordz_test_helpers.h.
                      {
  if (!cord.contents_.is_tree()) return nullptr;
  return cord.contents_.cordz_info();
}
MakeCordFromExternal
template<typename Releaser > Cord MakeCordFromExternal (absl::string_view data, Releaser && releaser) friend
Definition at line 1053 of file cord.h.
{
  Cord cord;
  if (ABSL_PREDICT_TRUE(!data.empty())) {
    cord.contents_.EmplaceTree(::absl::cord_internal::NewExternalRep(
                                   data, std::forward<Releaser>(releaser)),
                               Cord::MethodIdentifier::kMakeCordFromExternal);
  } else {
    using ReleaserType = absl::decay_t<Releaser>;
    cord_internal::InvokeReleaser(
        cord_internal::Rank0{}, ReleaserType(std::forward<Releaser>(releaser)),
        data);
  }
  return cord;
}
operator== [1/2]
bool operator== (const Cord & lhs, absl::string_view rhs) friend
Definition at line 1595 of file cord.h.
{
  size_t lhs_size = lhs.size();
  size_t rhs_size = rhs.size();
  if (lhs_size != rhs_size) return false;
  return lhs.EqualsImpl(rhs, rhs_size);
}
operator== [2/2]
bool operator== (const Cord & lhs, const Cord & rhs) friend
Definition at line 1574 of file cord.h.
{
  if (lhs.contents_.IsSame(rhs.contents_)) return true;
  size_t rhs_size = rhs.size();
  if (lhs.size() != rhs_size) return false;
  return lhs.EqualsImpl(rhs, rhs_size);
}
swap
void swap (Cord & x, Cord & y) friend
Definition at line 335 of file cord.h.
{ x.swap(y); }
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/cord.h
open_spiel/abseil-cpp/absl/strings/cord.cc