open spiel: open_spiel.python.algorithms.regret_matching_test.RegretMatchingTest Class Reference
open_spiel.python.algorithms.regret_matching_test.RegretMatchingTest Class Reference
Public Member Functions
test_two_players (self)
test_three_players (self)
test_rps (self)
test_biased_rps (self)
Detailed Description
Definition at line 24 of file regret_matching_test.py.
Member Function Documentation
test_biased_rps()
open_spiel.python.algorithms.regret_matching_test.RegretMatchingTest.test_biased_rps (self)
Definition at line 73 of file regret_matching_test.py.
  def test_biased_rps(self):
    game = pyspiel.load_game("matrix_brps")
    payoffs_array = game_payoffs_array(game)
    strategies = regret_matching.regret_matching(
        [payoffs_array[0], payoffs_array[1]], iterations=50000, gamma=1e-8)
    self.assertLen(strategies, 2, "Wrong strategy length.")
    # places=1 corresponds to an absolute difference of < 0.01
    self.assertAlmostEqual(strategies[0][0], 1 / 16., places=1)
    self.assertAlmostEqual(strategies[0][1], 10 / 16., places=1)
    self.assertAlmostEqual(strategies[0][2], 5 / 16., places=1)
References regret_matching.regret_matching().
test_rps()
open_spiel.python.algorithms.regret_matching_test.RegretMatchingTest.test_rps (self)
Definition at line 56 of file regret_matching_test.py.
  def test_rps(self):
    game = pyspiel.load_game("matrix_rps")
    payoffs_array = game_payoffs_array(game)
    strategies = regret_matching.regret_matching(
        [payoffs_array[0], payoffs_array[1]],
        initial_strategies=[
            np.array([0.1, 0.4, 0.5]),
            np.array([0.9, 0.1, 0.01])
        ],
        iterations=50000,
        gamma=1e-6)
    self.assertLen(strategies, 2, "Wrong strategy length.")
    # places=1 corresponds to an absolute difference of < 0.001
    self.assertAlmostEqual(strategies[0][0], 1 / 3., places=2)
    self.assertAlmostEqual(strategies[0][1], 1 / 3., places=2)
    self.assertAlmostEqual(strategies[0][2], 1 / 3., places=2)
References regret_matching.regret_matching().
test_three_players()
open_spiel.python.algorithms.regret_matching_test.RegretMatchingTest.test_three_players (self)
Definition at line 41 of file regret_matching_test.py.
  def test_three_players(self):
    test_a = np.array([[[2, 1, 0], [1, 0, -1]], [[1, 0, -1], [0, -1, -2]]])
    test_b = np.array([[[2, 1, 0], [1, 0, -1]], [[1, 0, -1], [0, -1, -2]]])
    test_c = np.array([[[2, 1, 0], [1, 0, -1]], [[1, 0, -1], [0, -1, -2]]])
    strategies = regret_matching.regret_matching(
        [test_a, test_b, test_c],
        initial_strategies=None,
        iterations=50000,
        gamma=1e-6,
        average_over_last_n_strategies=10)
    self.assertLen(strategies, 3, "Wrong strategy length.")
    self.assertGreater(strategies[0][0], 0.999,
                       "Regret matching failed in trivial case.")
References regret_matching.regret_matching().
test_two_players()
open_spiel.python.algorithms.regret_matching_test.RegretMatchingTest.test_two_players (self)
Definition at line 26 of file regret_matching_test.py.
  def test_two_players(self):
    test_a = np.array([[2, 1, 0], [0, -1, -2]])
    test_b = np.array([[2, 1, 0], [0, -1, -2]])
    strategies = regret_matching.regret_matching(
        [test_a, test_b],
        initial_strategies=None,
        iterations=50000,
        prd_gamma=1e-8,
        average_over_last_n_strategies=10)
    self.assertLen(strategies, 2, "Wrong strategy length.")
    self.assertGreater(strategies[0][0], 0.999,
                       "Regret matching failed in trivial case.")
References regret_matching.regret_matching().
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/regret_matching_test.py