open spiel: open_spiel::TrackingVectorAllocator Class Reference
open_spiel::TrackingVectorAllocator Class Reference
#include <observer.h>
Public Member Functions
TrackingVectorAllocator ()
SpanTensor Get (absl::string_view name, const absl::InlinedVector< int, 4 > &shape) override
std::vector< SpanTensorInfo > tensors_info () const
std::vector< float > & data ()
const std::vector< float > & data () const
Public Member Functions inherited from open_spiel::Allocator
virtual ~Allocator ()=default
Detailed Description
Definition at line 190 of file observer.h.
Constructor & Destructor Documentation
TrackingVectorAllocator()
open_spiel::TrackingVectorAllocator::TrackingVectorAllocator () inline
Definition at line 192 of file observer.h.
{}
Member Function Documentation
data() [1/2]
std::vector< float > & open_spiel::TrackingVectorAllocator::data () inline
Definition at line 201 of file observer.h.
{ return data_; }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), open_spiel::Observation::Observation(), open_spiel::ObserverTensorShape(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample(), and open_spiel::TensorFromObserver().
data() [2/2]
const std::vector< float > & open_spiel::TrackingVectorAllocator::data () const inline
Definition at line 202 of file observer.h.
{ return data_; }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample().
Get()
SpanTensor open_spiel::TrackingVectorAllocator::Get (absl::string_view name, const absl::InlinedVector< int, 4 > & shape) override virtual
Implements open_spiel::Allocator.
Definition at line 192 of file observer.cc.
{
  SPIEL_DCHECK_TRUE(IsNameUnique(name));
  SpanTensorInfo info(name, shape);
  tensors_info_.push_back(info);
  const int offset = data_.size();
  const int size = info.size();
  data_.resize(offset + size);
  return SpanTensor(std::move(info),
                    absl::MakeSpan(data_).subspan(offset, size));
}
References absl::MakeSpan(), name, size, and SPIEL_DCHECK_TRUE.
tensors_info()
std::vector< SpanTensorInfo > open_spiel::TrackingVectorAllocator::tensors_info () const inline
Definition at line 199 of file observer.h.
{ return tensors_info_; }
Referenced by open_spiel::Observation::Observation(), and open_spiel::ObserverTensorShape().
The documentation for this class was generated from the following files:
open_spiel/observer.h
open_spiel/observer.cc