open spiel: open_spiel::algorithms::MDPNode Class Reference
open_spiel::algorithms::MDPNode Class Reference
#include <tabular_best_response_mdp.h>
Public Member Functions
MDPNode (const std::string &node_key)
bool terminal () const
double total_weight () const
double value () const
std::string node_key () const
void set_terminal (bool terminal)
void add_weight (double weight)
void set_value (double value)
absl::flat_hash_map< Action, absl::flat_hash_map< MDPNode *, double > > & children ()
void IncTransitionWeight (Action a, MDPNode *child, double weight)
Detailed Description
Definition at line 75 of file tabular_best_response_mdp.h.
Constructor & Destructor Documentation
MDPNode()
open_spiel::algorithms::MDPNode::MDPNode (const std::string & node_key) explicit
Definition at line 36 of file tabular_best_response_mdp.cc.
    : terminal_(false), total_weight_(0), children_(), value_(0),
      node_key_(node_key) {}
Member Function Documentation
add_weight()
void open_spiel::algorithms::MDPNode::add_weight (double weight) inline
Definition at line 84 of file tabular_best_response_mdp.h.
{ total_weight_ += weight; }
children()
absl::flat_hash_map< Action, absl::flat_hash_map< MDPNode *, double > > & open_spiel::algorithms::MDPNode::children () inline
Definition at line 88 of file tabular_best_response_mdp.h.
             {
    return children_;
  }
Referenced by game_tree_utils.HistoryTreeNode::add_child(), game_tree_utils.InfoState::add_child_infostate(), open_spiel.python.algorithms.mcts.SearchNode::best_child(), open_spiel.python.algorithms.mcts.SearchNode::children_str(), game_tree_utils.HistoryTreeNode::get_child(), open_spiel::algorithms::MDP::Solve(), and open_spiel.python.algorithms.mcts.SearchNode::to_str().
IncTransitionWeight()
void open_spiel::algorithms::MDPNode::IncTransitionWeight (Action a, MDPNode * child, double weight)
Definition at line 40 of file tabular_best_response_mdp.cc.
{
  SPIEL_CHECK_TRUE(child != nullptr);
  children_[a][child] += weight;
}
References a, and SPIEL_CHECK_TRUE.
node_key()
std::string open_spiel::algorithms::MDPNode::node_key () const inline
Definition at line 82 of file tabular_best_response_mdp.h.
{ return node_key_; }
Referenced by open_spiel::algorithms::MDP::Solve().
set_terminal()
void open_spiel::algorithms::MDPNode::set_terminal (bool terminal) inline
Definition at line 83 of file tabular_best_response_mdp.h.
{ terminal_ = terminal; }
References terminal().
Referenced by open_spiel::algorithms::MDP::CreateTerminalNode().
set_value()
void open_spiel::algorithms::MDPNode::set_value (double value) inline
Definition at line 85 of file tabular_best_response_mdp.h.
{ value_ = value; }
References value().
Referenced by open_spiel.python.mfg.value.ValueFunction::add_value(), and open_spiel::algorithms::MDP::Solve().
terminal()
bool open_spiel::algorithms::MDPNode::terminal () const inline
Definition at line 79 of file tabular_best_response_mdp.h.
{ return terminal_; }
Referenced by set_terminal(), and open_spiel::algorithms::MDP::Solve().
total_weight()
double open_spiel::algorithms::MDPNode::total_weight () const inline
Definition at line 80 of file tabular_best_response_mdp.h.
{ return total_weight_; }
Referenced by open_spiel::algorithms::MDP::Solve().
value()
double open_spiel::algorithms::MDPNode::value () const inline
Definition at line 81 of file tabular_best_response_mdp.h.
{ return value_; }
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), set_value(), open_spiel::algorithms::MDP::Solve(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
The documentation for this class was generated from the following files:
open_spiel/algorithms/tabular_best_response_mdp.h
open_spiel/algorithms/tabular_best_response_mdp.cc