open spiel: open_spiel::RestrictedNashResponseObserver Class Reference
open_spiel::RestrictedNashResponseObserver Class Reference
Public Member Functions
RestrictedNashResponseObserver (IIGObservationType iig_obs_type)
void WriteTensor (const State &observed_state, int player, Allocator *allocator) const override
std::string StringFrom (const State &observed_state, int player) const override
Public Member Functions inherited from open_spiel::Observer
Observer (bool has_string, bool has_tensor)
bool HasString () const
bool HasTensor () const
virtual ~Observer ()=default
Additional Inherited Members
Protected Attributes inherited from open_spiel::Observer
bool has_string_
bool has_tensor_
Detailed Description
Definition at line 61 of file restricted_nash_response.cc.
Constructor & Destructor Documentation
RestrictedNashResponseObserver()
open_spiel::RestrictedNashResponseObserver::RestrictedNashResponseObserver (IIGObservationType iig_obs_type) inline
Definition at line 63 of file restricted_nash_response.cc.
      : Observer(/*has_string=*/true, /*has_tensor=*/true),
        iig_obs_type_(iig_obs_type) {}
Member Function Documentation
StringFrom()
std::string open_spiel::RestrictedNashResponseObserver::StringFrom (const State & observed_state, int player) const inline override virtual
Implements open_spiel::Observer.
Definition at line 104 of file restricted_nash_response.cc.
{
    auto& state = open_spiel::down_cast<const RestrictedNashResponseState &>(
        observed_state);
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, state.NumPlayers());
    std::string result;
    std::shared_ptr<const Game> original_game = state.GetOriginalGame();
    GameParameters params;
    std::shared_ptr<Observer> observer =
        original_game->MakeObserver(iig_obs_type_, params);
    if (iig_obs_type_.public_info) {
      if (state.IsRestrictedNashResponseInitialState()) {
        return "Initial";
      }
    }
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      if (state.IsPlayerFixed(player)) {
        result += state.IsStateFixed() ? "[Rnr: fixed]" : "[Rnr: free]";
      }
    } else if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers) {
      result += state.IsStateFixed() ? "[Rnr: fixed]" : "[Rnr: free]";
    }
    result += observer->StringFrom(*state.GetOriginalState(), player);
    return result;
  }
References open_spiel::down_cast(), open_spiel::kAllPlayers, open_spiel::kSinglePlayer, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and state.
WriteTensor()
void open_spiel::RestrictedNashResponseObserver::WriteTensor (const State & observed_state, int player, Allocator * allocator) const inline override virtual
Implements open_spiel::Observer.
Definition at line 70 of file restricted_nash_response.cc.
{
    auto& state = open_spiel::down_cast<const RestrictedNashResponseState &>(
        observed_state);
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, state.NumPlayers());
    std::shared_ptr<const Game> original_game = state.GetOriginalGame();
    GameParameters params;
    std::shared_ptr<Observer> observer =
        original_game->MakeObserver(iig_obs_type_, params);
    // Observing player.
    auto out = allocator->Get("initial_and_fixed", {2});
    if (iig_obs_type_.public_info) {
      if (state.IsRestrictedNashResponseInitialState()) {
        out.at(0) = 1;
      }
    }
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      if (state.IsPlayerFixed(player)) {
        out.at(1) = state.IsStateFixed();
      } else {
        out.at(1) = 0;
      }
    } else if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers) {
      out.at(1) = state.IsStateFixed();
    }
    observer->WriteTensor(*state.GetOriginalState(), player, allocator);
  }
References open_spiel::SpanTensor::at(), open_spiel::down_cast(), open_spiel::Allocator::Get(), open_spiel::kAllPlayers, open_spiel::kSinglePlayer, out, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and state.
The documentation for this class was generated from the following file:
open_spiel/game_transforms/restricted_nash_response.cc