open spiel: open_spiel::spades::SpadesGame Class Reference
open_spiel::spades::SpadesGame Class Reference
#include <spades.h>
Public Member Functions
SpadesGame (const GameParameters &params)
int NumDistinctActions () const override
int MaxChanceOutcomes () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
int NumPossibleContracts () const
std::string ContractString (int bid) const
int PrivateObservationTensorSize () const
int PublicObservationTensorSize () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Static Public Member Functions
static int GetPlayTensorSize (int num_tricks)
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 180 of file spades.h.
Constructor & Destructor Documentation
SpadesGame()
open_spiel::spades::SpadesGame::SpadesGame (const GameParameters & params) explicit
Definition at line 114 of file spades.cc.
    : Game(kGameType, params) {}
Member Function Documentation
ContractString()
std::string open_spiel::spades::SpadesGame::ContractString (int bid) const
Definition at line 606 of file spades.cc.
{
  return (bid == 0) ? "Nil" : std::to_string(bid);
}
DeserializeState()
std::unique_ptr< State > open_spiel::spades::SpadesGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 592 of file spades.cc.
{
  return Game::DeserializeState(str);
}
References open_spiel::Game::DeserializeState().
GetPlayTensorSize()
static int open_spiel::spades::SpadesGame::GetPlayTensorSize (int num_tricks) inline static
Definition at line 196 of file spades.h.
{
    return kNumBids * kNumPlayers  // What each player's contract is
           + kNumCards             // Our remaining cards
           + num_tricks * kNumPlayers * kNumCards  // Number of played tricks
           + kNumTricks * kNumPlayers;  // Number of tricks each player has won
  }
References open_spiel::spades::kNumBids, open_spiel::spades::kNumCards, open_spiel::spades::kNumPlayers, and open_spiel::spades::kNumTricks.
Referenced by ObservationTensorShape(), and open_spiel::spades::SpadesState::WriteObservationTensor().
MaxChanceNodesInHistory()
int open_spiel::spades::SpadesGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 209 of file spades.h.
{ return kNumCards; }
References open_spiel::spades::kNumCards.
MaxChanceOutcomes()
int open_spiel::spades::SpadesGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 186 of file spades.h.
{ return kNumCards; }
References open_spiel::spades::kNumCards.
MaxGameLength()
int open_spiel::spades::SpadesGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 208 of file spades.h.
{ return kMaxAuctionLength + kNumCards; }
References open_spiel::spades::kMaxAuctionLength, and open_spiel::spades::kNumCards.
MaxUtility()
double open_spiel::spades::SpadesGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 194 of file spades.h.
{ return kMaxScore; }
References open_spiel::spades::kMaxScore.
MinUtility()
double open_spiel::spades::SpadesGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 193 of file spades.h.
{ return -kMaxScore; }
References open_spiel::spades::kMaxScore.
NewInitialState()
std::unique_ptr< State > open_spiel::spades::SpadesGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 187 of file spades.h.
{
    return std::unique_ptr<State>(new SpadesState(
        shared_from_this(), UseMercyRule(), MercyThreshold(), WinThreshold(),
        PartnershipScore(0), PartnershipScore(1), NumTricks()));
  }
NumDistinctActions()
int open_spiel::spades::SpadesGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 183 of file spades.h.
{
    return kBiddingActionBase + kNumBids;
  }
References open_spiel::spades::kBiddingActionBase, and open_spiel::spades::kNumBids.
NumPlayers()
int open_spiel::spades::SpadesGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 192 of file spades.h.
{ return kNumPlayers; }
References open_spiel::spades::kNumPlayers.
NumPossibleContracts()
int open_spiel::spades::SpadesGame::NumPossibleContracts () const inline
Definition at line 215 of file spades.h.
{ return kNumContracts; }
References open_spiel::spades::kNumContracts.
ObservationTensorShape()
std::vector< int > open_spiel::spades::SpadesGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 203 of file spades.h.
{
    return {kPhaseInfoSize +
            std::max(GetPlayTensorSize(NumTricks()), kAuctionTensorSize)};
  }
References GetPlayTensorSize(), open_spiel::spades::kAuctionTensorSize, and open_spiel::spades::kPhaseInfoSize.
PrivateObservationTensorSize()
int open_spiel::spades::SpadesGame::PrivateObservationTensorSize () const inline
Definition at line 221 of file spades.h.
{ return kNumCards; }
References open_spiel::spades::kNumCards.
PublicObservationTensorSize()
int open_spiel::spades::SpadesGame::PublicObservationTensorSize () const inline
Definition at line 222 of file spades.h.
{ return kPublicInfoTensorSize; }
References open_spiel::spades::kPublicInfoTensorSize.
The documentation for this class was generated from the following files:
open_spiel/games/spades/spades.h
open_spiel/games/spades/spades.cc