open spiel: absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > > Class Template Reference
absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > > Class Template Reference
#include <layout.h>
Public Types
using ElementTypes = std::tuple<typename Type<Elements>::type...>
template<size_t N>
using ElementType = typename std::tuple_element<N, ElementTypes>::type
Public Member Functions
constexpr LayoutImpl (IntToSize< SizeSeq >... sizes)
template<size_t N, EnableIf< N==0 > = 0>
constexpr size_t Offset () const
template<size_t N, EnableIf< N !=0 > = 0>
constexpr size_t Offset () const
template<class T >
constexpr size_t Offset () const
constexpr std::array< size_t, NumOffsets > Offsets () const
template<size_t N>
constexpr size_t Size () const
template<class T >
constexpr size_t Size () const
constexpr std::array< size_t, NumSizes > Sizes () const
template<size_t N, class Char >
CopyConst< Char, ElementType< N > > * Pointer (Char *p) const
template<class T , class Char >
CopyConst< Char, T > * Pointer (Char *p) const
template<class Char >
std::tuple< CopyConst< Char, typename std::tuple_element< OffsetSeq, ElementTypes >::type > *... > Pointers (Char *p) const
template<size_t N, class Char >
SliceType< CopyConst< Char, ElementType< N > > > Slice (Char *p) const
template<class T , class Char >
SliceType< CopyConst< Char, T > > Slice (Char *p) const
template<class Char >
std::tuple< SliceType< CopyConst< Char, typename std::tuple_element< SizeSeq, ElementTypes >::type > >... > Slices (Char *p) const
constexpr size_t AllocSize () const
template<class Char , size_t N = NumOffsets - 1, EnableIf< N==0 > = 0>
void PoisonPadding (const Char *p) const
template<class Char , size_t N = NumOffsets - 1, EnableIf< N !=0 > = 0>
void PoisonPadding (const Char *p) const
std::string DebugString () const
Static Public Member Functions
static constexpr size_t Alignment ()
Detailed Description
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq>
class absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >
Definition at line 341 of file layout.h.
Member Typedef Documentation
ElementType
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<size_t N> using absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::ElementType = typename std::tuple_element<N, ElementTypes>::type
Definition at line 379 of file layout.h.
ElementTypes
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> using absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::ElementTypes = std::tuple<typename Type<Elements>::type...>
Definition at line 375 of file layout.h.
Constructor & Destructor Documentation
LayoutImpl()
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::LayoutImpl (IntToSize< SizeSeq >... sizes) inline explicit constexpr
Definition at line 381 of file layout.h.
      : size_{sizes...} {}
Member Function Documentation
Alignment()
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> static constexpr size_t absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Alignment () inline static constexpr
Definition at line 386 of file layout.h.
{
    return adl_barrier::Max(AlignOf<Elements>::value...);
  }
References absl::container_internal::internal_layout::adl_barrier::Max().
AllocSize()
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> size_t absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::AllocSize () const inline constexpr
Definition at line 597 of file layout.h.
{
    static_assert(NumTypes == NumSizes, "You must specify sizes of all fields");
    return Offset<NumTypes - 1>() +
        SizeOf<ElementType<NumTypes - 1>>::value * size_[NumTypes - 1];
  }
DebugString()
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> std::string absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::DebugString () const inline
Definition at line 646 of file layout.h.
{
    const auto offsets = Offsets();
    const size_t sizes[] = {SizeOf<ElementType<OffsetSeq>>::value...};
    const std::string types[] = {
        adl_barrier::TypeName<ElementType<OffsetSeq>>()...};
    std::string res = absl::StrCat("@0", types[0], "(", sizes[0], ")");
    for (size_t i = 0; i != NumOffsets - 1; ++i) {
      absl::StrAppend(&res, "[", size_[i], "]; @", offsets[i + 1], types[i + 1],
                      "(", sizes[i + 1], ")");
    }
    // NumSizes is a constant that may be zero. Some compilers cannot see that
    // inside the if statement "size_[NumSizes - 1]" must be valid.
    int last = static_cast<int>(NumSizes) - 1;
    if (NumTypes == NumSizes && last >= 0) {
      absl::StrAppend(&res, "[", size_[last], "]");
    }
    return res;
  }
References absl::i, absl::StrAppend(), absl::StrCat(), and absl::container_internal::internal_layout::adl_barrier::TypeName().
Offset() [1/3]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<size_t N, EnableIf< N==0 > = 0> size_t absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Offset () const inline constexpr
Definition at line 399 of file layout.h.
{
    return 0;
  }
Offset() [2/3]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<size_t N, EnableIf< N !=0 > = 0> size_t absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Offset () const inline constexpr
Definition at line 404 of file layout.h.
{
    static_assert(N < NumOffsets, "Index out of bounds");
    return adl_barrier::Align(
        Offset<N - 1>() + SizeOf<ElementType<N - 1>>::value * size_[N - 1],
        ElementAlignment<N>::value);
  }
References absl::container_internal::internal_layout::adl_barrier::Align().
Offset() [3/3]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<class T > size_t absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Offset () const inline constexpr
Definition at line 420 of file layout.h.
{
    return Offset<ElementIndex<T>()>();
  }
Offsets()
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> std::array< size_t, NumOffsets > absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Offsets () const inline constexpr
Definition at line 425 of file layout.h.
{
    return {{Offset<OffsetSeq>()...}};
  }
Pointer() [1/2]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<size_t N, class Char > CopyConst< Char, ElementType< N > > * absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Pointer (Char * p) const inline
Definition at line 475 of file layout.h.
{
    using C = typename std::remove_const<Char>::type;
    static_assert(
        std::is_same<C, char>() || std::is_same<C, unsigned char>() ||
            std::is_same<C, signed char>(),
        "The argument must be a pointer to [const] [signed|unsigned] char");
    constexpr size_t alignment = Alignment();
    (void)alignment;
    assert(reinterpret_cast<uintptr_t>(p) % alignment == 0);
    return reinterpret_cast<CopyConst<Char, ElementType<N>>*>(p + Offset<N>());
  }
References C, and absl::p.
Pointer() [2/2]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<class T , class Char > CopyConst< Char, T > * absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Pointer (Char * p) const inline
Definition at line 501 of file layout.h.
{
    return Pointer<ElementIndex<T>()>(p);
  }
References absl::p.
Pointers()
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<class Char > std::tuple< CopyConst< Char, typename std::tuple_element< OffsetSeq, ElementTypes >::type > *... > absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Pointers (Char * p) const inline
Definition at line 524 of file layout.h.
{
    return std::tuple<CopyConst<Char, ElementType<OffsetSeq>>*...>(
        Pointer<OffsetSeq>(p)...);
  }
References absl::p.
PoisonPadding() [1/2]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<class Char , size_t N = NumOffsets - 1, EnableIf< N==0 > = 0> void absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::PoisonPadding (const Char * p) const inline
Definition at line 611 of file layout.h.
{
    Pointer<0>(p);  // verify the requirements on `Char` and `p`
  }
References absl::p.
PoisonPadding() [2/2]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<class Char , size_t N = NumOffsets - 1, EnableIf< N !=0 > = 0> void absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::PoisonPadding (const Char * p) const inline
Definition at line 616 of file layout.h.
{
    static_assert(N < NumOffsets, "Index out of bounds");
    (void)p;
#ifdef ABSL_HAVE_ADDRESS_SANITIZER
    PoisonPadding<Char, N - 1>(p);
    // The `if` is an optimization. It doesn't affect the observable behaviour.
    if (ElementAlignment<N - 1>::value % ElementAlignment<N>::value) {
      size_t start =
          Offset<N - 1>() + SizeOf<ElementType<N - 1>>::value * size_[N - 1];
      ASAN_POISON_MEMORY_REGION(p + start, Offset<N>() - start);
    }
#endif
  }
References absl::p.
Size() [1/2]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<size_t N> size_t absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Size () const inline constexpr
Definition at line 439 of file layout.h.
{
    static_assert(N < NumSizes, "Index out of bounds");
    return size_[N];
  }
Size() [2/2]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<class T > size_t absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Size () const inline constexpr
Definition at line 453 of file layout.h.
{
    return Size<ElementIndex<T>()>();
  }
Sizes()
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> std::array< size_t, NumSizes > absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Sizes () const inline constexpr
Definition at line 458 of file layout.h.
{
    return {{Size<SizeSeq>()...}};
  }
Slice() [1/2]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<size_t N, class Char > SliceType< CopyConst< Char, ElementType< N > > > absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Slice (Char * p) const inline
Definition at line 542 of file layout.h.
{
    return SliceType<CopyConst<Char, ElementType<N>>>(Pointer<N>(p), Size<N>());
  }
References absl::p.
Slice() [2/2]
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<class T , class Char > SliceType< CopyConst< Char, T > > absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Slice (Char * p) const inline
Definition at line 559 of file layout.h.
{
    return Slice<ElementIndex<T>()>(p);
  }
References absl::p.
Slices()
template<class... Elements, size_t... SizeSeq, size_t... OffsetSeq> template<class Char > std::tuple< SliceType< CopyConst< Char, typename std::tuple_element< SizeSeq, ElementTypes >::type > >... > absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Slices (Char * p) const inline
Definition at line 582 of file layout.h.
{
    // Workaround for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63875 (fixed
    // in 6.1).
    (void)p;
    return std::tuple<SliceType<CopyConst<Char, ElementType<SizeSeq>>>...>(
        Slice<SizeSeq>(p)...);
  }
References absl::p.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/layout.h