open spiel: open_spiel::Observer Class Reference
open_spiel::Observer Class Reference abstract
#include <observer.h>
Public Member Functions
Observer (bool has_string, bool has_tensor)
virtual void WriteTensor (const State &state, int player, Allocator *allocator) const =0
virtual std::string StringFrom (const State &state, int player) const =0
bool HasString () const
bool HasTensor () const
virtual ~Observer ()=default
Protected Attributes
bool has_string_
bool has_tensor_
Detailed Description
Definition at line 322 of file observer.h.
Constructor & Destructor Documentation
Observer()
open_spiel::Observer::Observer (bool has_string, bool has_tensor) inline
Definition at line 324 of file observer.h.
      : has_string_(has_string), has_tensor_(has_tensor) {
    SPIEL_CHECK_TRUE(has_string || has_tensor);
  }
References SPIEL_CHECK_TRUE.
~Observer()
virtual open_spiel::Observer::~Observer () virtual default
Member Function Documentation
HasString()
bool open_spiel::Observer::HasString () const inline
Definition at line 338 of file observer.h.
{ return has_string_; }
References has_string_.
HasTensor()
bool open_spiel::Observer::HasTensor () const inline
Definition at line 339 of file observer.h.
{ return has_tensor_; }
References has_tensor_.
StringFrom()
virtual std::string open_spiel::Observer::StringFrom (const State & state, int player) const pure virtual
Implemented in open_spiel::coordinated_mp::PenniesObserver, open_spiel::dark_chess::DarkChessObserver, open_spiel::gin_rummy::GinRummyObserver, open_spiel::goofspiel::GoofspielObserver, open_spiel::kriegspiel::KriegspielObserver, open_spiel::kuhn_poker::KuhnObserver, open_spiel::leduc_poker::LeducObserver, open_spiel::phantom_go::PhantomGoObserver, open_spiel::PyObserver, open_spiel::rbc::RbcObserver, and open_spiel::RestrictedNashResponseObserver.
WriteTensor()
virtual void open_spiel::Observer::WriteTensor (const State & state, int player, Allocator * allocator) const pure virtual
Implemented in open_spiel::coordinated_mp::PenniesObserver, open_spiel::dark_chess::DarkChessObserver, open_spiel::gin_rummy::GinRummyObserver, open_spiel::goofspiel::GoofspielObserver, open_spiel::kriegspiel::KriegspielObserver, open_spiel::kuhn_poker::KuhnObserver, open_spiel::leduc_poker::LeducObserver, open_spiel::phantom_go::PhantomGoObserver, open_spiel::PyObserver, open_spiel::rbc::RbcObserver, and open_spiel::RestrictedNashResponseObserver.
Referenced by open_spiel::PyGame::InformationStateTensorShape(), open_spiel::PyGame::ObservationTensorShape(), open_spiel::ObserverTensorShape(), and open_spiel::TensorFromObserver().
Member Data Documentation
has_string_
bool open_spiel::Observer::has_string_ protected
Definition at line 345 of file observer.h.
Referenced by HasString().
has_tensor_
bool open_spiel::Observer::has_tensor_ protected
Definition at line 346 of file observer.h.
Referenced by HasTensor(), and open_spiel::PyObserver::PyObserver().
The documentation for this class was generated from the following file:
open_spiel/observer.h