open spiel: open_spiel::tiny_bridge::TinyBridgeGame4p Class Reference
open_spiel::tiny_bridge::TinyBridgeGame4p Class Reference
#include <tiny_bridge.h>
Public Member Functions
TinyBridgeGame4p (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int MaxChanceOutcomes () const override
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 106 of file tiny_bridge.h.
Constructor & Destructor Documentation
TinyBridgeGame4p()
open_spiel::tiny_bridge::TinyBridgeGame4p::TinyBridgeGame4p (const GameParameters & params) explicit
Definition at line 273 of file tiny_bridge.cc.
    : Game(kGameType4p, params) {}
Member Function Documentation
InformationStateTensorShape()
std::vector< int > open_spiel::tiny_bridge::TinyBridgeGame4p::InformationStateTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 119 of file tiny_bridge.h.
{
    return {kDeckSize + (kNumBids * 3 + 1) * NumPlayers()};
  }
References open_spiel::tiny_bridge::kDeckSize, open_spiel::tiny_bridge::kNumBids, and NumPlayers().
MaxChanceNodesInHistory()
int open_spiel::tiny_bridge::TinyBridgeGame4p::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 117 of file tiny_bridge.h.
{ return MaxGameLength(); }
References MaxGameLength().
MaxChanceOutcomes()
int open_spiel::tiny_bridge::TinyBridgeGame4p::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 118 of file tiny_bridge.h.
{ return kNumPrivates; }
References open_spiel::tiny_bridge::kNumPrivates.
MaxGameLength()
int open_spiel::tiny_bridge::TinyBridgeGame4p::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 115 of file tiny_bridge.h.
{ return 57; }
Referenced by MaxChanceNodesInHistory().
MaxUtility()
double open_spiel::tiny_bridge::TinyBridgeGame4p::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 114 of file tiny_bridge.h.
{ return 160; }
MinUtility()
double open_spiel::tiny_bridge::TinyBridgeGame4p::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 112 of file tiny_bridge.h.
{ return -160; }
NewInitialState()
std::unique_ptr< State > open_spiel::tiny_bridge::TinyBridgeGame4p::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 276 of file tiny_bridge.cc.
{
  return std::unique_ptr<State>(
      new TinyBridgeAuctionState(shared_from_this(), /*is_abstracted=*/false));
}
NumDistinctActions()
int open_spiel::tiny_bridge::TinyBridgeGame4p::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 109 of file tiny_bridge.h.
{ return kNumActions4p; }
References open_spiel::tiny_bridge::kNumActions4p.
NumPlayers()
int open_spiel::tiny_bridge::TinyBridgeGame4p::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 111 of file tiny_bridge.h.
{ return 4; }
Referenced by InformationStateTensorShape(), and ObservationTensorShape().
ObservationTensorShape()
std::vector< int > open_spiel::tiny_bridge::TinyBridgeGame4p::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 122 of file tiny_bridge.h.
{
    return {kDeckSize + kNumBids + 4 * NumPlayers()};
  }
References open_spiel::tiny_bridge::kDeckSize, open_spiel::tiny_bridge::kNumBids, and NumPlayers().
UtilitySum()
absl::optional< double > open_spiel::tiny_bridge::TinyBridgeGame4p::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 113 of file tiny_bridge.h.
{ return 0; }
The documentation for this class was generated from the following files:
open_spiel/games/tiny_bridge/tiny_bridge.h
open_spiel/games/tiny_bridge/tiny_bridge.cc