open spiel: absl::time_internal::cctz::TimeZoneLibC Class Reference
absl::time_internal::cctz::TimeZoneLibC Class Reference
#include <time_zone_libc.h>
Public Member Functions
TimeZoneLibC (const std::string &name)
time_zone::absolute_lookup BreakTime (const time_point< seconds > &tp) const override
time_zone::civil_lookup MakeTime (const civil_second &cs) const override
bool NextTransition (const time_point< seconds > &tp, time_zone::civil_transition *trans) const override
bool PrevTransition (const time_point< seconds > &tp, time_zone::civil_transition *trans) const override
std::string Version () const override
std::string Description () const override
Public Member Functions inherited from absl::time_internal::cctz::TimeZoneIf
virtual ~TimeZoneIf ()
Additional Inherited Members
Static Public Member Functions inherited from absl::time_internal::cctz::TimeZoneIf
static std::unique_ptr< TimeZoneIf > Load (const std::string &name)
Protected Member Functions inherited from absl::time_internal::cctz::TimeZoneIf
TimeZoneIf ()
Detailed Description
Definition at line 31 of file time_zone_libc.h.
Constructor & Destructor Documentation
TimeZoneLibC()
absl::time_internal::cctz::TimeZoneLibC::TimeZoneLibC (const std::string & name) explicit
Definition at line 186 of file time_zone_libc.cc.
    : local_(name == "localtime") {}
Member Function Documentation
BreakTime()
time_zone::absolute_lookup absl::time_internal::cctz::TimeZoneLibC::BreakTime (const time_point< seconds > & tp) const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 189 of file time_zone_libc.cc.
{
  time_zone::absolute_lookup al;
  al.offset = 0;
  al.is_dst = false;
  al.abbr = "-00";
  const std::int_fast64_t s = ToUnixSeconds(tp);
  // If std::time_t cannot hold the input we saturate the output.
  if (s < std::numeric_limits<std::time_t>::min()) {
    al.cs = civil_second::min();
    return al;
  }
  if (s > std::numeric_limits<std::time_t>::max()) {
    al.cs = civil_second::max();
    return al;
  }
  const std::time_t t = static_cast<std::time_t>(s);
  std::tm tm;
  std::tm* tmp = local_ ? local_time(&t, &tm) : gm_time(&t, &tm);
  // If std::tm cannot hold the result we saturate the output.
  if (tmp == nullptr) {
    al.cs = (s < 0) ? civil_second::min() : civil_second::max();
    return al;
  }
  const year_t year = tmp->tm_year + year_t{1900};
  al.cs = civil_second(year, tmp->tm_mon + 1, tmp->tm_mday, tmp->tm_hour,
                       tmp->tm_min, tmp->tm_sec);
  al.offset = static_cast<int>(tm_gmtoff(*tmp));
  al.abbr = local_ ? tm_zone(*tmp) : "UTC";  // as expected by cctz
  al.is_dst = tmp->tm_isdst > 0;
  return al;
}
References absl::time_internal::cctz::time_zone::absolute_lookup::abbr, absl::time_internal::cctz::time_zone::absolute_lookup::cs, absl::time_internal::cctz::time_zone::absolute_lookup::is_dst, absl::time_internal::cctz::detail::civil_time< T >::max(), absl::time_internal::cctz::detail::civil_time< T >::min(), absl::time_internal::cctz::time_zone::absolute_lookup::offset, absl::s, and absl::time_internal::cctz::ToUnixSeconds().
Description()
std::string absl::time_internal::cctz::TimeZoneLibC::Description () const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 308 of file time_zone_libc.cc.
{
  return local_ ? "localtime" : "UTC";
}
MakeTime()
time_zone::civil_lookup absl::time_internal::cctz::TimeZoneLibC::MakeTime (const civil_second & cs) const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 227 of file time_zone_libc.cc.
{
  if (!local_) {
    // If time_point<seconds> cannot hold the result we saturate.
    static const civil_second min_tp_cs =
        civil_second() + ToUnixSeconds(time_point<seconds>::min());
    static const civil_second max_tp_cs =
        civil_second() + ToUnixSeconds(time_point<seconds>::max());
    const time_point<seconds> tp = (cs < min_tp_cs) ? time_point<seconds>::min()
                                   : (cs > max_tp_cs)
                                       ? time_point<seconds>::max()
                                       : FromUnixSeconds(cs - civil_second());
    return {time_zone::civil_lookup::UNIQUE, tp, tp, tp};
  }
  // If tm_year cannot hold the requested year we saturate the result.
  if (cs.year() < 0) {
    if (cs.year() < std::numeric_limits<int>::min() + year_t{1900}) {
      const time_point<seconds> tp = time_point<seconds>::min();
      return {time_zone::civil_lookup::UNIQUE, tp, tp, tp};
    }
  } else {
    if (cs.year() - year_t{1900} > std::numeric_limits<int>::max()) {
      const time_point<seconds> tp = time_point<seconds>::max();
      return {time_zone::civil_lookup::UNIQUE, tp, tp, tp};
    }
  }
  // We probe with "is_dst" values of 0 and 1 to try to distinguish unique
  // civil seconds from skipped or repeated ones.  This is not always possible
  // however, as the "dst" flag does not change over some offset transitions.
  // We are also subject to the vagaries of mktime() implementations.
  std::time_t t0, t1;
  int offset0, offset1;
  if (make_time(cs, 0, &t0, &offset0) && make_time(cs, 1, &t1, &offset1)) {
    if (t0 == t1) {
      // The civil time was singular (pre == trans == post).
      const time_point<seconds> tp = FromUnixSeconds(t0);
      return {time_zone::civil_lookup::UNIQUE, tp, tp, tp};
    }
    if (t0 > t1) {
      std::swap(t0, t1);
      std::swap(offset0, offset1);
    }
    const std::time_t tt = find_trans(t0, t1, offset1);
    const time_point<seconds> trans = FromUnixSeconds(tt);
    if (offset0 < offset1) {
      // The civil time did not exist (pre >= trans > post).
      const time_point<seconds> pre = FromUnixSeconds(t1);
      const time_point<seconds> post = FromUnixSeconds(t0);
      return {time_zone::civil_lookup::SKIPPED, pre, trans, post};
    }
    // The civil time was ambiguous (pre < trans <= post).
    const time_point<seconds> pre = FromUnixSeconds(t0);
    const time_point<seconds> post = FromUnixSeconds(t1);
    return {time_zone::civil_lookup::REPEATED, pre, trans, post};
  }
  // make_time() failed somehow so we saturate the result.
  const time_point<seconds> tp = (cs < civil_second())
                                     ? time_point<seconds>::min()
                                     : time_point<seconds>::max();
  return {time_zone::civil_lookup::UNIQUE, tp, tp, tp};
}
References absl::time_internal::cctz::FromUnixSeconds(), absl::time_internal::cctz::time_zone::civil_lookup::REPEATED, absl::time_internal::cctz::time_zone::civil_lookup::SKIPPED, t1, absl::time_internal::cctz::ToUnixSeconds(), absl::time_internal::cctz::time_zone::civil_lookup::UNIQUE, and absl::time_internal::cctz::detail::civil_time< T >::year().
NextTransition()
bool absl::time_internal::cctz::TimeZoneLibC::NextTransition (const time_point< seconds > & tp, time_zone::civil_transition * trans) const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 294 of file time_zone_libc.cc.
{
  return false;
}
PrevTransition()
bool absl::time_internal::cctz::TimeZoneLibC::PrevTransition (const time_point< seconds > & tp, time_zone::civil_transition * trans) const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 299 of file time_zone_libc.cc.
{
  return false;
}
Version()
std::string absl::time_internal::cctz::TimeZoneLibC::Version () const override virtual
Implements absl::time_internal::cctz::TimeZoneIf.
Definition at line 304 of file time_zone_libc.cc.
{
  return std::string();  // unknown
}
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/time/internal/cctz/src/time_zone_libc.h
open_spiel/abseil-cpp/absl/time/internal/cctz/src/time_zone_libc.cc