open spiel: open_spiel::battleship::ShipPlacement Class Reference
open_spiel::battleship::ShipPlacement Class Reference final
#include <battleship_types.h>
Public Types
enum Direction
Public Types inherited from open_spiel::battleship::CellAndDirection
enum Direction { Horizontal = 0 , Vertical = 1 }
Public Member Functions
ShipPlacement (const Direction direction, const Ship &ship, const Cell &tl_corner)
bool CoversCell (const Cell &cell) const
Cell BottomRightCorner () const
bool OverlapsWith (const ShipPlacement &other) const
bool IsWithinBounds (const int board_width, const int board_height) const
std::string ToString () const
Public Member Functions inherited from open_spiel::battleship::CellAndDirection
CellAndDirection (const Direction direction, const Cell &tl_corner)
Cell TopLeftCorner () const
Public Attributes
Ship ship
Public Attributes inherited from open_spiel::battleship::CellAndDirection
Direction direction
Additional Inherited Members
Protected Attributes inherited from open_spiel::battleship::CellAndDirection
Cell tl_corner_
Detailed Description
Definition at line 66 of file battleship_types.h.
Member Enumeration Documentation
Direction
enum open_spiel::battleship::CellAndDirection::Direction
Definition at line 51 of file battleship_types.h.
{ Horizontal = 0, Vertical = 1 };
Constructor & Destructor Documentation
ShipPlacement()
open_spiel::battleship::ShipPlacement::ShipPlacement (const Direction direction, const Ship & ship, const Cell & tl_corner)
Definition at line 115 of file battleship_types.cc.
    : CellAndDirection(dir, tl_corner), ship(ship) {
  SPIEL_CHECK_GE(ship.length, 1);
}
References open_spiel::battleship::Ship::length, ship, and SPIEL_CHECK_GE.
Member Function Documentation
BottomRightCorner()
Cell open_spiel::battleship::ShipPlacement::BottomRightCorner () const
Definition at line 132 of file battleship_types.cc.
{
  if (direction == Direction::Horizontal) {
    return Cell{tl_corner_.row, tl_corner_.col + ship.length - 1};
  } else {
    SPIEL_CHECK_EQ(direction, Direction::Vertical);
    return Cell{tl_corner_.row + ship.length - 1, tl_corner_.col};
  }
}
References open_spiel::battleship::Cell::col, open_spiel::battleship::CellAndDirection::direction, open_spiel::battleship::Ship::length, open_spiel::battleship::Cell::row, ship, SPIEL_CHECK_EQ, and open_spiel::battleship::CellAndDirection::tl_corner_.
Referenced by IsWithinBounds(), and OverlapsWith().
CoversCell()
bool open_spiel::battleship::ShipPlacement::CoversCell (const Cell & cell) const
Definition at line 121 of file battleship_types.cc.
{
  if (direction == Direction::Horizontal) {
    return cell.row == tl_corner_.row && cell.col >= tl_corner_.col &&
           cell.col < tl_corner_.col + ship.length;
  } else {
    SPIEL_CHECK_EQ(direction, Direction::Vertical);
    return cell.col == tl_corner_.col && cell.row >= tl_corner_.row &&
           cell.row < tl_corner_.row + ship.length;
  }
}
References open_spiel::battleship::Cell::col, open_spiel::battleship::CellAndDirection::direction, open_spiel::battleship::Ship::length, open_spiel::battleship::Cell::row, ship, SPIEL_CHECK_EQ, and open_spiel::battleship::CellAndDirection::tl_corner_.
Referenced by open_spiel::battleship::BattleshipState::InformationStateString(), and open_spiel::battleship::BattleshipState::InformationStateTensor().
IsWithinBounds()
bool open_spiel::battleship::ShipPlacement::IsWithinBounds (const int board_width, const int board_height) const
Definition at line 158 of file battleship_types.cc.
{
  const Cell tl_corner = TopLeftCorner();
  const Cell br_corner = BottomRightCorner();
  return (tl_corner.row >= 0 && tl_corner.row < board_height) &&
         (br_corner.row >= 0 && br_corner.row < board_height) &&
         (tl_corner.col >= 0 && tl_corner.col < board_width) &&
         (br_corner.col >= 0 && br_corner.col < board_width);
}
References BottomRightCorner(), open_spiel::battleship::Cell::col, open_spiel::battleship::Cell::row, and open_spiel::battleship::CellAndDirection::TopLeftCorner().
Referenced by open_spiel::battleship::ExistsFeasiblePlacement().
OverlapsWith()
bool open_spiel::battleship::ShipPlacement::OverlapsWith (const ShipPlacement & other) const
Definition at line 141 of file battleship_types.cc.
{
  if (other.BottomRightCorner().row < TopLeftCorner().row) {
    // `other` is completely above `this`.
    return false;
  } else if (other.TopLeftCorner().row > BottomRightCorner().row) {
    // `other` is completely below `this`.
    return false;
  } else if (other.BottomRightCorner().col < TopLeftCorner().col) {
    // `other` is completely to the left of `this`.
    return false;
  } else if (other.TopLeftCorner().col > BottomRightCorner().col) {
    // `other` is completely to the right of `this`.
    return false;
  }
  return true;
}
References BottomRightCorner(), open_spiel::battleship::Cell::col, open_spiel::battleship::Cell::row, and open_spiel::battleship::CellAndDirection::TopLeftCorner().
ToString()
std::string open_spiel::battleship::ShipPlacement::ToString () const
Definition at line 169 of file battleship_types.cc.
{
  const char direction_char = direction == Direction::Horizontal ? 'h' : 'v';
  return absl::StrFormat("%c_%d_%d", direction_char, tl_corner_.row,
                         tl_corner_.col);
}
References open_spiel::battleship::Cell::col, open_spiel::battleship::CellAndDirection::direction, open_spiel::battleship::Cell::row, absl::StrFormat(), and open_spiel::battleship::CellAndDirection::tl_corner_.
Member Data Documentation
ship
Ship open_spiel::battleship::ShipPlacement::ship
Definition at line 95 of file battleship_types.h.
Referenced by BottomRightCorner(), CoversCell(), open_spiel::battleship::ExistsFeasiblePlacement(), open_spiel::battleship::BattleshipState::OwnBoardString(), ShipPlacement(), and open_spiel::battleship::BattleshipState::ShotsBoardString().
The documentation for this class was generated from the following files:
open_spiel/games/battleship/battleship_types.h
open_spiel/games/battleship/battleship_types.cc