open spiel: absl::CommandLineFlag Class Reference
absl::CommandLineFlag Class Reference abstract
#include <commandlineflag.h>
Public Member Functions
constexpr CommandLineFlag ()=default
CommandLineFlag (const CommandLineFlag &)=delete
CommandLineFlag & operator= (const CommandLineFlag &)=delete
template<typename T >
bool IsOfType () const
template<typename T >
absl::optional< T > TryGet () const
virtual absl::string_view Name () const =0
virtual std::string Filename () const =0
virtual std::string Help () const =0
virtual bool IsRetired () const
virtual std::string DefaultValue () const =0
virtual std::string CurrentValue () const =0
bool ParseFrom (absl::string_view value, std::string *error)
Protected Member Functions
~CommandLineFlag ()=default
Friends
class flags_internal::PrivateHandleAccessor
Detailed Description
Definition at line 62 of file commandlineflag.h.
Constructor & Destructor Documentation
CommandLineFlag() [1/2]
absl::CommandLineFlag::CommandLineFlag () constexpr default
CommandLineFlag() [2/2]
absl::CommandLineFlag::CommandLineFlag (const CommandLineFlag &) delete
~CommandLineFlag()
absl::CommandLineFlag::~CommandLineFlag () protected default
Member Function Documentation
CurrentValue()
virtual std::string absl::CommandLineFlag::CurrentValue () const pure virtual
DefaultValue()
virtual std::string absl::CommandLineFlag::DefaultValue () const pure virtual
Filename()
virtual std::string absl::CommandLineFlag::Filename () const pure virtual
Referenced by absl::flags_internal::FlagRegistry::RegisterFlag().
Help()
virtual std::string absl::CommandLineFlag::Help () const pure virtual
IsOfType()
template<typename T > bool absl::CommandLineFlag::IsOfType () const inline
Definition at line 74 of file commandlineflag.h.
{
    return TypeId() == base_internal::FastTypeId<T>();
  }
References absl::base_internal::FastTypeId().
Referenced by TryGet().
IsRetired()
ABSL_NAMESPACE_BEGIN bool absl::CommandLineFlag::IsRetired () const virtual
Definition at line 27 of file commandlineflag.cc.
{ return false; }
Referenced by absl::GetAllFlags(), absl::flags_internal::ParseCommandLineImpl(), absl::flags_internal::FlagRegistry::RegisterFlag(), and TryGet().
Name()
virtual absl::string_view absl::CommandLineFlag::Name () const pure virtual
Referenced by absl::flags_internal::FlagRegistry::RegisterFlag().
operator=()
CommandLineFlag & absl::CommandLineFlag::operator= (const CommandLineFlag &) delete
ParseFrom()
bool absl::CommandLineFlag::ParseFrom (absl::string_view value, std::string * error)
Definition at line 28 of file commandlineflag.cc.
{
  return ParseFrom(value, flags_internal::SET_FLAGS_VALUE,
                   flags_internal::kProgrammaticChange, *error);
}
References absl::flags_internal::kProgrammaticChange, ParseFrom(), and absl::flags_internal::SET_FLAGS_VALUE.
Referenced by ParseFrom(), and absl::flags_internal::PrivateHandleAccessor::ParseFrom().
TryGet()
template<typename T > absl::optional< T > absl::CommandLineFlag::TryGet () const inline
Definition at line 83 of file commandlineflag.h.
{
    if (IsRetired() || !IsOfType<T>()) {
      return absl::nullopt;
    }
    // Implementation notes:
    //
    // We are wrapping a union around the value of `T` to serve three purposes:
    //
    //  1. `U.value` has correct size and alignment for a value of type `T`
    //  2. The `U.value` constructor is not invoked since U's constructor does
    //     not do it explicitly.
    //  3. The `U.value` destructor is invoked since U's destructor does it
    //     explicitly. This makes `U` a kind of RAII wrapper around non default
    //     constructible value of T, which is destructed when we leave the
    //     scope. We do need to destroy U.value, which is constructed by
    //     CommandLineFlag::Read even though we left it in a moved-from state
    //     after std::move.
    //
    // All of this serves to avoid requiring `T` being default constructible.
    union U {
      T value;
      U() {}
      ~U() { value.~T(); }
    };
    U u;
    Read(&u.value);
    // allow retired flags to be "read", so we can report invalid access.
    if (IsRetired()) {
      return absl::nullopt;
    }
    return std::move(u.value);
  }
References IsOfType(), IsRetired(), absl::u, and value.
Friends And Related Symbol Documentation
flags_internal::PrivateHandleAccessor
friend class flags_internal::PrivateHandleAccessor friend
Definition at line 159 of file commandlineflag.h.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/flags/commandlineflag.h
open_spiel/abseil-cpp/absl/flags/commandlineflag.cc