open spiel: TimerList Class Reference
TimerList Class Reference
#include <TimerList.h>
Public Member Functions
TimerList ()
~TimerList ()
void Reset ()
void Start (const ABTimerType groupno, const unsigned timerno)
void End (const ABTimerType groupno, const unsigned timerno)
bool Used () const
void PrintStats (ofstream &fout) const
Detailed Description
Definition at line 81 of file TimerList.h.
Constructor & Destructor Documentation
TimerList()
TimerList::TimerList ()
Definition at line 21 of file TimerList.cpp.
{
  TimerList::Reset();
}
References Reset().
~TimerList()
TimerList::~TimerList ()
Definition at line 27 of file TimerList.cpp.
{
}
Member Function Documentation
End()
void TimerList::End (const ABTimerType groupno, const unsigned timerno)
Definition at line 59 of file TimerList.cpp.
{
  if (groupno >= TIMER_NO_SIZE)
    return;
  timerGroups[groupno].End(timerno);
}
References TIMER_NO_SIZE.
PrintStats()
void TimerList::PrintStats (ofstream & fout) const
Definition at line 80 of file TimerList.cpp.
{
  if (! TimerList::Used())
    return;
  // Approximate the exclusive times of each function.
  // The ABsearch*() functions are recursively nested,
  // so subtract out the one below.
  // The other ones are subtracted out based on knowledge
  // of the functions.
  TimerGroup ABGroup;
  ABGroup = timerGroups[0];
  ABGroup.Differentiate();
  for (unsigned g = 1; g < TIMER_NO_SIZE; g++)
    ABGroup -= timerGroups[g];
  Timer ABTotal;
  ABGroup.SetNames("AB");
  ABGroup.Sum(ABTotal);
  ABTotal.SetName("Sum");
  Timer sumTotal = ABTotal;
  for (unsigned g = 1; g < TIMER_NO_SIZE; g++)
  {
    Timer t;
    timerGroups[g].Sum(t);
    sumTotal += t;
  }
  fout << timerGroups[0].Header();
  fout << ABGroup.SumLine(sumTotal);
  for (unsigned g = 1; g < TIMER_NO_SIZE; g++)
    fout << timerGroups[g].SumLine(sumTotal);
  fout << timerGroups[0].DashLine();
  fout << sumTotal.SumLine(sumTotal) << endl;
  if (ABGroup.Used())
  {
    fout << ABGroup.Header();
    fout << ABGroup.TimerLines(ABTotal);
    fout << ABGroup.DashLine();
    fout << ABTotal.SumLine(ABTotal) << endl;
  }
#ifdef DDS_TIMING_DETAILS
  fout << timerGroups[0].DetailHeader();
  for (unsigned g = 0; g < TIMER_NO_SIZE; g++)
    fout << timerGroups[g].DetailLines();
  fout << endl;
#endif
}
References TimerGroup::DashLine(), TimerGroup::Differentiate(), TimerGroup::Header(), Timer::SetName(), TimerGroup::SetNames(), TimerGroup::Sum(), Timer::SumLine(), TimerGroup::SumLine(), TIMER_NO_SIZE, TimerGroup::TimerLines(), TimerGroup::Used(), and Used().
Reset()
void TimerList::Reset ()
Definition at line 32 of file TimerList.cpp.
{
  timerGroups.resize(TIMER_NO_SIZE);
  timerGroups[TIMER_NO_AB].SetNames("AB");
  timerGroups[TIMER_NO_MAKE].SetNames("Make");
  timerGroups[TIMER_NO_UNDO].SetNames("Undo");
  timerGroups[TIMER_NO_EVALUATE].SetNames("Evaluate");
  timerGroups[TIMER_NO_NEXTMOVE].SetNames("NextMove");
  timerGroups[TIMER_NO_QT].SetNames("QuickTricks");
  timerGroups[TIMER_NO_LT].SetNames("LaterTricks");
  timerGroups[TIMER_NO_MOVEGEN].SetNames("MoveGen");
  timerGroups[TIMER_NO_LOOKUP].SetNames("Lookup");
  timerGroups[TIMER_NO_BUILD].SetNames("Build");
}
References TIMER_NO_AB, TIMER_NO_BUILD, TIMER_NO_EVALUATE, TIMER_NO_LOOKUP, TIMER_NO_LT, TIMER_NO_MAKE, TIMER_NO_MOVEGEN, TIMER_NO_NEXTMOVE, TIMER_NO_QT, TIMER_NO_SIZE, and TIMER_NO_UNDO.
Referenced by TimerList().
Start()
void TimerList::Start (const ABTimerType groupno, const unsigned timerno)
Definition at line 49 of file TimerList.cpp.
{
  if (groupno >= TIMER_NO_SIZE)
    return;
  timerGroups[groupno].Start(timerno);
}
References TIMER_NO_SIZE.
Used()
bool TimerList::Used () const
Definition at line 69 of file TimerList.cpp.
{
  for (unsigned g = 0; g < TIMER_NO_SIZE; g++)
  {
    if (timerGroups[g].Used())
      return true;
  }
  return false;
}
References TIMER_NO_SIZE, and Used().
Referenced by PrintStats(), and Used().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/TimerList.h
open_spiel/games/bridge/double_dummy_solver/src/TimerList.cpp