open spiel: open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix Class Reference
open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix Class Reference
#include <tiny_hanabi.h>
Public Member Functions
int operator() (const std::vector< State::PlayerAction > &history) const
TinyHanabiPayoffMatrix (int num_players, int num_chance, int num_actions, std::vector< int > payoff)
int NumPlayers () const
int NumChance () const
int NumActions () const
int MinUtility () const
int MaxUtility () const
Detailed Description
Definition at line 44 of file tiny_hanabi.h.
Constructor & Destructor Documentation
TinyHanabiPayoffMatrix()
open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::TinyHanabiPayoffMatrix (int num_players, int num_chance, int num_actions, std::vector< int > payoff) inline
Definition at line 55 of file tiny_hanabi.h.
      : num_players_(num_players),
        num_chance_(num_chance),
        num_actions_(num_actions),
        payoff_(payoff) {
    // Check payoff.size() == (num_chance * num_actions)**num_players
    const int n = num_chance_ * num_actions_;
    int expected_payoff_size = 1;
    for (int i = 0; i < num_players; ++i) expected_payoff_size *= n;
    SPIEL_CHECK_EQ(payoff_.size(), expected_payoff_size);
  }
References i, n, and SPIEL_CHECK_EQ.
Member Function Documentation
MaxUtility()
int open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::MaxUtility () const inline
Definition at line 72 of file tiny_hanabi.h.
{ return *absl::c_max_element(payoff_); }
References absl::c_max_element().
Referenced by open_spiel::tiny_hanabi::TinyHanabiGame::MaxUtility().
MinUtility()
int open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::MinUtility () const inline
Definition at line 71 of file tiny_hanabi.h.
{ return *absl::c_min_element(payoff_); }
References absl::c_min_element().
Referenced by open_spiel::tiny_hanabi::TinyHanabiGame::MinUtility().
NumActions()
int open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumActions () const inline
Definition at line 70 of file tiny_hanabi.h.
{ return num_actions_; }
Referenced by open_spiel::tiny_hanabi::TinyHanabiState::InformationStateTensor(), open_spiel::tiny_hanabi::TinyHanabiGame::InformationStateTensorShape(), open_spiel::tiny_hanabi::TinyHanabiState::LegalActions(), and open_spiel::tiny_hanabi::TinyHanabiGame::NumDistinctActions().
NumChance()
int open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumChance () const inline
Definition at line 69 of file tiny_hanabi.h.
{ return num_chance_; }
Referenced by open_spiel::tiny_hanabi::TinyHanabiState::ChanceOutcomes(), open_spiel::tiny_hanabi::TinyHanabiState::InformationStateTensor(), open_spiel::tiny_hanabi::TinyHanabiGame::InformationStateTensorShape(), open_spiel::tiny_hanabi::TinyHanabiState::LegalActions(), and open_spiel::tiny_hanabi::TinyHanabiGame::MaxChanceOutcomes().
NumPlayers()
int open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumPlayers () const inline
Definition at line 68 of file tiny_hanabi.h.
{ return num_players_; }
Referenced by open_spiel::tiny_hanabi::TinyHanabiState::InformationStateString(), open_spiel::tiny_hanabi::TinyHanabiState::InformationStateTensor(), open_spiel::tiny_hanabi::TinyHanabiGame::InformationStateTensorShape(), open_spiel::tiny_hanabi::TinyHanabiGame::MaxGameLength(), open_spiel::tiny_hanabi::TinyHanabiGame::NumPlayers(), open_spiel::tiny_hanabi::TinyHanabiState::Returns(), and open_spiel::tiny_hanabi::TinyHanabiState::ToString().
operator()()
int open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::operator() (const std::vector< State::PlayerAction > & history) const inline
Definition at line 46 of file tiny_hanabi.h.
{
    SPIEL_CHECK_EQ(num_players_ * 2, history.size());
    int idx = 0;
    for (int i = 0; i < num_players_; ++i)
      idx = (idx * num_chance_) + history[i].action;
    for (int i = num_players_; i < 2 * num_players_; ++i)
      idx = (idx * num_actions_) + history[i].action;
    return payoff_[idx];
  }
References i, and SPIEL_CHECK_EQ.
The documentation for this class was generated from the following file:
open_spiel/games/tiny_hanabi/tiny_hanabi.h