open spiel: absl::cord_internal::CordzInfo Class Reference
absl::cord_internal::CordzInfo Class Reference
#include <cordz_info.h>
Public Types
using MethodIdentifier = CordzUpdateTracker::MethodIdentifier
Public Member Functions
void Untrack ()
CordzInfo ()=delete
CordzInfo (const CordzInfo &)=delete
CordzInfo & operator= (const CordzInfo &)=delete
CordzInfo * Next (const CordzSnapshot &snapshot) const ABSL_NO_THREAD_SAFETY_ANALYSIS
void Lock (MethodIdentifier method) ABSL_EXCLUSIVE_LOCK_FUNCTION(mutex_)
void Unlock () ABSL_UNLOCK_FUNCTION(mutex_)
void AssertHeld () ABSL_ASSERT_EXCLUSIVE_LOCK(mutex_)
void SetCordRep (CordRep *rep)
CordRep * RefCordRep () const ABSL_LOCKS_EXCLUDED(mutex_)
CordRep * GetCordRepForTesting () const ABSL_NO_THREAD_SAFETY_ANALYSIS
void SetCordRepForTesting (CordRep *rep) ABSL_NO_THREAD_SAFETY_ANALYSIS
absl::Span< void *const > GetStack () const
absl::Span< void *const > GetParentStack () const
CordzStatistics GetCordzStatistics () const
Public Member Functions inherited from absl::cord_internal::CordzHandle
CordzHandle ()
bool is_snapshot () const
bool SafeToDelete () const
bool DiagnosticsHandleIsSafeToInspect (const CordzHandle *handle) const
std::vector< const CordzHandle * > DiagnosticsGetSafeToInspectDeletedHandles ()
Static Public Member Functions
static void TrackCord (InlineData &cord, MethodIdentifier method)
static void TrackCord (InlineData &cord, const InlineData &src, MethodIdentifier method)
static void MaybeTrackCord (InlineData &cord, MethodIdentifier method)
static void MaybeTrackCord (InlineData &cord, const InlineData &src, MethodIdentifier method)
static void MaybeUntrackCord (CordzInfo *info)
static CordzInfo * Head (const CordzSnapshot &snapshot) ABSL_NO_THREAD_SAFETY_ANALYSIS
Static Public Member Functions inherited from absl::cord_internal::CordzHandle
static void Delete (CordzHandle *handle)
static std::vector< const CordzHandle * > DiagnosticsGetDeleteQueue ()
Additional Inherited Members
Protected Member Functions inherited from absl::cord_internal::CordzHandle
CordzHandle (bool is_snapshot)
virtual ~CordzHandle ()
Detailed Description
Definition at line 47 of file cordz_info.h.
Member Typedef Documentation
MethodIdentifier
using absl::cord_internal::CordzInfo::MethodIdentifier = CordzUpdateTracker::MethodIdentifier
Definition at line 49 of file cordz_info.h.
Constructor & Destructor Documentation
CordzInfo() [1/2]
absl::cord_internal::CordzInfo::CordzInfo () delete
Referenced by TrackCord(), and TrackCord().
CordzInfo() [2/2]
absl::cord_internal::CordzInfo::CordzInfo (const CordzInfo &) delete
Member Function Documentation
AssertHeld()
void absl::cord_internal::CordzInfo::AssertHeld () inline
Definition at line 276 of file cordz_info.h.
{
#ifndef NDEBUG
  mutex_.AssertHeld();
#endif
}
Referenced by SetCordRep().
GetCordRepForTesting()
CordRep * absl::cord_internal::CordzInfo::GetCordRepForTesting () const inline
Definition at line 157 of file cordz_info.h.
{
    return rep_;
  }
GetCordzStatistics()
CordzStatistics absl::cord_internal::CordzInfo::GetCordzStatistics () const
Definition at line 405 of file cordz_info.cc.
{
  CordzStatistics stats;
  stats.method = method_;
  stats.parent_method = parent_method_;
  stats.update_tracker = update_tracker_;
  if (CordRep* rep = RefCordRep()) {
    stats.size = rep->length;
    CordRepAnalyzer analyzer(stats);
    analyzer.AnalyzeCordRep(rep);
    CordRep::Unref(rep);
  }
  return stats;
}
References absl::cord_internal::CordzStatistics::method, RefCordRep(), rep, and absl::cord_internal::CordRep::Unref().
Referenced by absl::MATCHER_P(), and absl::MATCHER_P2().
GetParentStack()
absl::Span< void *const > absl::cord_internal::CordzInfo::GetParentStack () const
Definition at line 401 of file cordz_info.cc.
{
  return absl::MakeConstSpan(parent_stack_, parent_stack_depth_);
}
References absl::MakeConstSpan().
GetStack()
absl::Span< void *const > absl::cord_internal::CordzInfo::GetStack () const
Definition at line 397 of file cordz_info.cc.
{
  return absl::MakeConstSpan(stack_, stack_depth_);
}
References absl::MakeConstSpan().
Head()
CordzInfo * absl::cord_internal::CordzInfo::Head (const CordzSnapshot & snapshot) static
Definition at line 230 of file cordz_info.cc.
{
  ABSL_ASSERT(snapshot.is_snapshot());
  // We can do an 'unsafe' load of 'head', as we are guaranteed that the
  // instance it points to is kept alive by the provided CordzSnapshot, so we
  // can simply return the current value using an acquire load.
  // We do enforce in DEBUG builds that the 'head' value is present in the
  // delete queue: ODR violations may lead to 'snapshot' and 'global_list_'
  // being in different libraries / modules.
  CordzInfo* head = global_list_.head.load(std::memory_order_acquire);
  ABSL_ASSERT(snapshot.DiagnosticsHandleIsSafeToInspect(head));
  return head;
}
References ABSL_ASSERT, absl::cord_internal::CordzHandle::DiagnosticsHandleIsSafeToInspect(), and absl::cord_internal::CordzHandle::is_snapshot().
Lock()
void absl::cord_internal::CordzInfo::Lock (MethodIdentifier method)
Definition at line 382 of file cordz_info.cc.
{
  mutex_.Lock();
  update_tracker_.LossyAdd(method);
  assert(rep_);
}
MaybeTrackCord() [1/2]
ABSL_ATTRIBUTE_ALWAYS_INLINE void absl::cord_internal::CordzInfo::MaybeTrackCord (InlineData & cord, const InlineData & src, MethodIdentifier method) inline static
Definition at line 262 of file cordz_info.h.
{
  if (ABSL_PREDICT_FALSE(InlineData::is_either_profiled(cord, src))) {
    MaybeTrackCordImpl(cord, src, method);
  }
}
References ABSL_PREDICT_FALSE, and absl::cord_internal::InlineData::is_either_profiled().
MaybeTrackCord() [2/2]
ABSL_ATTRIBUTE_ALWAYS_INLINE void absl::cord_internal::CordzInfo::MaybeTrackCord (InlineData & cord, MethodIdentifier method) inline static
Definition at line 255 of file cordz_info.h.
{
  if (ABSL_PREDICT_FALSE(cordz_should_profile())) {
    TrackCord(cord, method);
  }
}
References ABSL_PREDICT_FALSE, absl::cord_internal::cordz_should_profile(), and TrackCord().
MaybeUntrackCord()
ABSL_ATTRIBUTE_ALWAYS_INLINE void absl::cord_internal::CordzInfo::MaybeUntrackCord (CordzInfo * info) inline static
Definition at line 269 of file cordz_info.h.
                     {
  if (ABSL_PREDICT_FALSE(info)) {
    info->Untrack();
  }
}
References ABSL_PREDICT_FALSE.
Referenced by absl::Cord::operator=().
Next()
CordzInfo * absl::cord_internal::CordzInfo::Next (const CordzSnapshot & snapshot) const
Definition at line 244 of file cordz_info.cc.
{
  ABSL_ASSERT(snapshot.is_snapshot());
  // Similar to the 'Head()' function, we do not need a mutex here.
  CordzInfo* next = ci_next_.load(std::memory_order_acquire);
  ABSL_ASSERT(snapshot.DiagnosticsHandleIsSafeToInspect(this));
  ABSL_ASSERT(snapshot.DiagnosticsHandleIsSafeToInspect(next));
  return next;
}
References ABSL_ASSERT, absl::cord_internal::CordzHandle::DiagnosticsHandleIsSafeToInspect(), absl::cord_internal::CordzHandle::is_snapshot(), and next.
Referenced by absl::cord_internal::CordzSampleToken::Iterator::operator++().
operator=()
CordzInfo & absl::cord_internal::CordzInfo::operator= (const CordzInfo &) delete
RefCordRep()
CordRep * absl::cord_internal::CordzInfo::RefCordRep () const inline
Definition at line 289 of file cordz_info.h.
{
  MutexLock lock(&mutex_);
  return rep_ ? CordRep::Ref(rep_) : nullptr;
}
References absl::cord_internal::CordRep::Ref().
Referenced by GetCordzStatistics().
SetCordRep()
void absl::cord_internal::CordzInfo::SetCordRep (CordRep * rep) inline
Definition at line 282 of file cordz_info.h.
{
  AssertHeld();
  rep_ = rep;
}
References AssertHeld(), and rep.
SetCordRepForTesting()
void absl::cord_internal::CordzInfo::SetCordRepForTesting (CordRep * rep) inline
Definition at line 162 of file cordz_info.h.
{
    rep_ = rep;
  }
References rep.
TrackCord() [1/2]
void absl::cord_internal::CordzInfo::TrackCord (InlineData & cord, const InlineData & src, MethodIdentifier method) static
Definition at line 262 of file cordz_info.cc.
{
  assert(cord.is_tree());
  assert(src.is_tree());
  // Unsample current as we the current cord is being replaced with 'src',
  // so any method history is no longer relevant.
  CordzInfo* cordz_info = cord.cordz_info();
  if (cordz_info != nullptr) cordz_info->Untrack();
  // Start new cord sample
  cordz_info = new CordzInfo(cord.as_tree(), src.cordz_info(), method);
  cord.set_cordz_info(cordz_info);
  cordz_info->Track();
}
References absl::cord_internal::InlineData::as_tree(), absl::cord_internal::InlineData::cordz_info(), CordzInfo(), absl::cord_internal::InlineData::is_tree(), absl::cord_internal::InlineData::set_cordz_info(), and Untrack().
TrackCord() [2/2]
void absl::cord_internal::CordzInfo::TrackCord (InlineData & cord, MethodIdentifier method) static
Definition at line 254 of file cordz_info.cc.
{
  assert(cord.is_tree());
  assert(!cord.is_profiled());
  CordzInfo* cordz_info = new CordzInfo(cord.as_tree(), nullptr, method);
  cord.set_cordz_info(cordz_info);
  cordz_info->Track();
}
References absl::cord_internal::InlineData::as_tree(), CordzInfo(), absl::cord_internal::InlineData::is_profiled(), absl::cord_internal::InlineData::is_tree(), and absl::cord_internal::InlineData::set_cordz_info().
Referenced by MaybeTrackCord().
Unlock()
void absl::cord_internal::CordzInfo::Unlock ()
Definition at line 389 of file cordz_info.cc.
{
  bool tracked = rep_ != nullptr;
  mutex_.Unlock();
  if (!tracked) {
    Untrack();
  }
}
References Untrack().
Untrack()
void absl::cord_internal::CordzInfo::Untrack ()
Definition at line 343 of file cordz_info.cc.
{
  ODRCheck();
  {
    SpinLockHolder l(&list_->mutex);
    CordzInfo* const head = list_->head.load(std::memory_order_acquire);
    CordzInfo* const next = ci_next_.load(std::memory_order_acquire);
    CordzInfo* const prev = ci_prev_.load(std::memory_order_acquire);
    if (next) {
      ABSL_ASSERT(next->ci_prev_.load(std::memory_order_acquire) == this);
      next->ci_prev_.store(prev, std::memory_order_release);
    }
    if (prev) {
      ABSL_ASSERT(head != this);
      ABSL_ASSERT(prev->ci_next_.load(std::memory_order_acquire) == this);
      prev->ci_next_.store(next, std::memory_order_release);
    } else {
      ABSL_ASSERT(head == this);
      list_->head.store(next, std::memory_order_release);
    }
  }
  // We can no longer be discovered: perform a fast path check if we are not
  // listed on any delete queue, so we can directly delete this instance.
  if (SafeToDelete()) {
    UnsafeSetCordRep(nullptr);
    delete this;
    return;
  }
  // We are likely part of a snapshot, extend the life of the CordRep
  {
    absl::MutexLock lock(&mutex_);
    if (rep_) CordRep::Ref(rep_);
  }
  CordzHandle::Delete(this);
}
References ABSL_ASSERT, absl::cord_internal::CordzHandle::Delete(), next, absl::cord_internal::CordRep::Ref(), and absl::cord_internal::CordzHandle::SafeToDelete().
Referenced by TrackCord(), and Unlock().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/cordz_info.h
open_spiel/abseil-cpp/absl/strings/internal/cordz_info.cc