open spiel: absl::variant< T0, Tn... > Class Template Reference
absl::variant< T0, Tn... > Class Template Reference
#include <variant.h>
Public Member Functions
constexpr variant ()=default
variant (const variant &other)=default
variant (variant &&other)=default
template<class T , std::size_t I = std::enable_if< variant_internal::IsNeitherSelfNorInPlace<variant, absl::decay_t<T>>::value, variant_internal::IndexOfConstructedType<variant, T>>::type::value, class Tj = absl::variant_alternative_t<I, variant>, absl::enable_if_t< std::is_constructible< Tj, T >::value > * = nullptr>
constexpr variant (T &&t) noexcept(std::is_nothrow_constructible< Tj, T >::value)
template<class T , class... Args, typename std::enable_if< std::is_constructible< variant_internal::UnambiguousTypeOfT< variant, T >, Args... >::value >::type * = nullptr>
constexpr variant (in_place_type_t< T >, Args &&... args)
template<class T , class U , class... Args, typename std::enable_if< std::is_constructible< variant_internal::UnambiguousTypeOfT< variant, T >, std::initializer_list< U > &, Args... >::value >::type * = nullptr>
constexpr variant (in_place_type_t< T >, std::initializer_list< U > il, Args &&... args)
template<std::size_t I, class... Args, typename std::enable_if< std::is_constructible< variant_internal::VariantAlternativeSfinaeT< I, variant >, Args... >::value >::type * = nullptr>
constexpr variant (in_place_index_t< I >, Args &&... args)
template<std::size_t I, class U , class... Args, typename std::enable_if< std::is_constructible< variant_internal::VariantAlternativeSfinaeT< I, variant >, std::initializer_list< U > &, Args... >::value >::type * = nullptr>
constexpr variant (in_place_index_t< I >, std::initializer_list< U > il, Args &&... args)
~variant ()=default
variant & operator= (const variant &other)=default
variant & operator= (variant &&other)=default
template<class T , std::size_t I = std::enable_if< !std::is_same<absl::decay_t<T>, variant>::value, variant_internal::IndexOfConstructedType<variant, T>>::type::value, class Tj = absl::variant_alternative_t<I, variant>, typename std::enable_if< std::is_assignable< Tj &, T >::value &&std::is_constructible< Tj, T >::value >::type * = nullptr>
variant & operator= (T &&t) noexcept(std::is_nothrow_assignable< Tj &, T >::value &&std::is_nothrow_constructible< Tj, T >::value)
template<class T , class... Args, typename std::enable_if< std::is_constructible< absl::variant_alternative_t< variant_internal::UnambiguousIndexOf< variant, T >::value, variant >, Args... >::value >::type * = nullptr>
T & emplace (Args &&... args)
template<class T , class U , class... Args, typename std::enable_if< std::is_constructible< absl::variant_alternative_t< variant_internal::UnambiguousIndexOf< variant, T >::value, variant >, std::initializer_list< U > &, Args... >::value >::type * = nullptr>
T & emplace (std::initializer_list< U > il, Args &&... args)
template<std::size_t I, class... Args, typename std::enable_if< std::is_constructible< absl::variant_alternative_t< I, variant >, Args... >::value >::type * = nullptr>
absl::variant_alternative_t< I, variant > & emplace (Args &&... args)
template<std::size_t I, class U , class... Args, typename std::enable_if< std::is_constructible< absl::variant_alternative_t< I, variant >, std::initializer_list< U > &, Args... >::value >::type * = nullptr>
absl::variant_alternative_t< I, variant > & emplace (std::initializer_list< U > il, Args &&... args)
constexpr bool valueless_by_exception () const noexcept
constexpr std::size_t index () const noexcept
void swap (variant &rhs) noexcept(absl::conjunction< std::is_nothrow_move_constructible< T0 >, std::is_nothrow_move_constructible< Tn >..., type_traits_internal::IsNothrowSwappable< T0 >, type_traits_internal::IsNothrowSwappable< Tn >... >::value)
Friends
struct variant_internal::VariantCoreAccess
Detailed Description
template<typename T0, typename... Tn>
class absl::variant< T0, Tn... >
Definition at line 460 of file variant.h.
Constructor & Destructor Documentation
variant() [1/8]
template<typename T0 , typename... Tn> absl::variant< T0, Tn... >::variant () constexpr default
variant() [2/8]
template<typename T0 , typename... Tn> absl::variant< T0, Tn... >::variant (const variant< T0, Tn... > & other) default
variant() [3/8]
template<typename T0 , typename... Tn> absl::variant< T0, Tn... >::variant (variant< T0, Tn... > && other) default
variant() [4/8]
template<typename T0 , typename... Tn> template<class T , std::size_t I = std::enable_if< variant_internal::IsNeitherSelfNorInPlace<variant, absl::decay_t<T>>::value, variant_internal::IndexOfConstructedType<variant, T>>::type::value, class Tj = absl::variant_alternative_t<I, variant>, absl::enable_if_t< std::is_constructible< Tj, T >::value > * = nullptr> absl::variant< T0, Tn... >::variant (T && t) inline constexpr noexcept
Definition at line 512 of file variant.h.
      : Base(variant_internal::EmplaceTag<I>(), absl::forward<T>(t)) {}
variant() [5/8]
template<typename T0 , typename... Tn> template<class T , class... Args, typename std::enable_if< std::is_constructible< variant_internal::UnambiguousTypeOfT< variant, T >, Args... >::value >::type * = nullptr> absl::variant< T0, Tn... >::variant (in_place_type_t< T > , Args &&... args) inline explicit constexpr
Definition at line 524 of file variant.h.
      : Base(variant_internal::EmplaceTag<
                 variant_internal::UnambiguousIndexOf<variant, T>::value>(),
             absl::forward<Args>(args)...) {}
variant() [6/8]
template<typename T0 , typename... Tn> template<class T , class U , class... Args, typename std::enable_if< std::is_constructible< variant_internal::UnambiguousTypeOfT< variant, T >, std::initializer_list< U > &, Args... >::value >::type * = nullptr> absl::variant< T0, Tn... >::variant (in_place_type_t< T > , std::initializer_list< U > il, Args &&... args) inline explicit constexpr
Definition at line 538 of file variant.h.
      : Base(variant_internal::EmplaceTag<
                 variant_internal::UnambiguousIndexOf<variant, T>::value>(),
             il, absl::forward<Args>(args)...) {}
variant() [7/8]
template<typename T0 , typename... Tn> template<std::size_t I, class... Args, typename std::enable_if< std::is_constructible< variant_internal::VariantAlternativeSfinaeT< I, variant >, Args... >::value >::type * = nullptr> absl::variant< T0, Tn... >::variant (in_place_index_t< I > , Args &&... args) inline explicit constexpr
Definition at line 550 of file variant.h.
      : Base(variant_internal::EmplaceTag<I>(), absl::forward<Args>(args)...) {}
variant() [8/8]
template<typename T0 , typename... Tn> template<std::size_t I, class U , class... Args, typename std::enable_if< std::is_constructible< variant_internal::VariantAlternativeSfinaeT< I, variant >, std::initializer_list< U > &, Args... >::value >::type * = nullptr> absl::variant< T0, Tn... >::variant (in_place_index_t< I > , std::initializer_list< U > il, Args &&... args) inline explicit constexpr
Definition at line 560 of file variant.h.
      : Base(variant_internal::EmplaceTag<I>(), il,
             absl::forward<Args>(args)...) {}
~variant()
template<typename T0 , typename... Tn> absl::variant< T0, Tn... >::~variant () default
Member Function Documentation
emplace() [1/4]
template<typename T0 , typename... Tn> template<class T , class... Args, typename std::enable_if< std::is_constructible< absl::variant_alternative_t< variant_internal::UnambiguousIndexOf< variant, T >::value, variant >, Args... >::value >::type * = nullptr> T & absl::variant< T0, Tn... >::emplace (Args &&... args) inline
Definition at line 623 of file variant.h.
{
    return variant_internal::VariantCoreAccess::Replace<
        variant_internal::UnambiguousIndexOf<variant, T>::value>(
        this, absl::forward<Args>(args)...);
  }
References absl::forward(), and absl::variant_internal::VariantCoreAccess::Replace().
emplace() [2/4]
template<typename T0 , typename... Tn> template<std::size_t I, class... Args, typename std::enable_if< std::is_constructible< absl::variant_alternative_t< I, variant >, Args... >::value >::type * = nullptr> absl::variant_alternative_t< I, variant > & absl::variant< T0, Tn... >::emplace (Args &&... args) inline
Definition at line 664 of file variant.h.
{
    return variant_internal::VariantCoreAccess::Replace<I>(
        this, absl::forward<Args>(args)...);
  }
References absl::forward(), and absl::variant_internal::VariantCoreAccess::Replace().
emplace() [3/4]
template<typename T0 , typename... Tn> template<class T , class U , class... Args, typename std::enable_if< std::is_constructible< absl::variant_alternative_t< variant_internal::UnambiguousIndexOf< variant, T >::value, variant >, std::initializer_list< U > &, Args... >::value >::type * = nullptr> T & absl::variant< T0, Tn... >::emplace (std::initializer_list< U > il, Args &&... args) inline
Definition at line 644 of file variant.h.
{
    return variant_internal::VariantCoreAccess::Replace<
        variant_internal::UnambiguousIndexOf<variant, T>::value>(
        this, il, absl::forward<Args>(args)...);
  }
References absl::forward(), and absl::variant_internal::VariantCoreAccess::Replace().
emplace() [4/4]
template<typename T0 , typename... Tn> template<std::size_t I, class U , class... Args, typename std::enable_if< std::is_constructible< absl::variant_alternative_t< I, variant >, std::initializer_list< U > &, Args... >::value >::type * = nullptr> absl::variant_alternative_t< I, variant > & absl::variant< T0, Tn... >::emplace (std::initializer_list< U > il, Args &&... args) inline
Definition at line 681 of file variant.h.
{
    return variant_internal::VariantCoreAccess::Replace<I>(
        this, il, absl::forward<Args>(args)...);
  }
References absl::forward(), and absl::variant_internal::VariantCoreAccess::Replace().
index()
template<typename T0 , typename... Tn> std::size_t absl::variant< T0, Tn... >::index () const inline constexpr noexcept
Definition at line 698 of file variant.h.
{ return this->index_; }
Referenced by open_spiel.python.egt.visualization.SimplexStreamMask::__getitem__(), and open_spiel.python.egt.visualization.SimplexStreamMask::__setitem__().
operator=() [1/3]
template<typename T0 , typename... Tn> variant & absl::variant< T0, Tn... >::operator= (const variant< T0, Tn... > & other) default
operator=() [2/3]
template<typename T0 , typename... Tn> template<class T , std::size_t I = std::enable_if< !std::is_same<absl::decay_t<T>, variant>::value, variant_internal::IndexOfConstructedType<variant, T>>::type::value, class Tj = absl::variant_alternative_t<I, variant>, typename std::enable_if< std::is_assignable< Tj &, T >::value &&std::is_constructible< Tj, T >::value >::type * = nullptr> variant & absl::variant< T0, Tn... >::operator= (T && t) inline noexcept
Definition at line 593 of file variant.h.
{
    variant_internal::VisitIndices<sizeof...(Tn) + 1>::Run(
        variant_internal::VariantCoreAccess::MakeConversionAssignVisitor(
            this, absl::forward<T>(t)),
        index());
    return *this;
  }
References absl::forward(), and absl::variant_internal::VariantCoreAccess::MakeConversionAssignVisitor().
operator=() [3/3]
template<typename T0 , typename... Tn> variant & absl::variant< T0, Tn... >::operator= (variant< T0, Tn... > && other) default
swap()
template<typename T0 , typename... Tn> void absl::variant< T0, Tn... >::swap (variant< T0, Tn... > & rhs) inline noexcept
Definition at line 704 of file variant.h.
{
    return variant_internal::VisitIndices<sizeof...(Tn) + 1>::Run(
        variant_internal::Swap<T0, Tn...>{this, &rhs}, rhs.index());
  }
valueless_by_exception()
template<typename T0 , typename... Tn> bool absl::variant< T0, Tn... >::valueless_by_exception () const inline constexpr noexcept
Definition at line 690 of file variant.h.
{
    return this->index_ == absl::variant_npos;
  }
Friends And Related Symbol Documentation
variant_internal::VariantCoreAccess
template<typename T0 , typename... Tn> friend struct variant_internal::VariantCoreAccess friend
Definition at line 475 of file variant.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/types/variant.h