open spiel: open_spiel::algorithms::MCTSBot Class Reference
open_spiel::algorithms::MCTSBot Class Reference
#include <mcts.h>
Public Member Functions
MCTSBot (const Game &game, std::shared_ptr< Evaluator > evaluator, double uct_c, int max_simulations, int64_t max_memory_mb, bool solve, int seed, bool verbose, ChildSelectionPolicy child_selection_policy=ChildSelectionPolicy::UCT, double dirichlet_alpha=0, double dirichlet_epsilon=0, bool dont_return_chance_node=false)
~MCTSBot ()=default
void Restart () override
void RestartAt (const State &state) override
Action Step (const State &state) override
std::pair< ActionsAndProbs, Action > StepWithPolicy (const State &state) override
std::unique_ptr< SearchNode > MCTSearch (const State &state)
Public Member Functions inherited from open_spiel::Bot
virtual ~Bot ()=default
virtual void InformAction (const State &state, Player player_id, Action action)
virtual void InformActions (const State &state, const std::vector< Action > &actions)
virtual bool ProvidesForceAction ()
virtual void ForceAction (const State &state, Action action)
virtual bool ProvidesPolicy ()
virtual ActionsAndProbs GetPolicy (const State &state)
virtual bool IsClonable () const
virtual std::unique_ptr< Bot > Clone ()
Detailed Description
Definition at line 149 of file mcts.h.
Constructor & Destructor Documentation
MCTSBot()
open_spiel::algorithms::MCTSBot::MCTSBot (const Game & game, std::shared_ptr< Evaluator > evaluator, double uct_c, int max_simulations, int64_t max_memory_mb, bool solve, int seed, bool verbose, ChildSelectionPolicy child_selection_policy = ChildSelectionPolicy::UCT, double dirichlet_alpha = 0, double dirichlet_epsilon = 0, bool dont_return_chance_node = false)
Definition at line 204 of file mcts.cc.
    : uct_c_{uct_c},
      max_simulations_{max_simulations},
      max_nodes_((max_memory_mb << 20) / sizeof(SearchNode) + 1),
      nodes_(0),
      gc_limit_(MIN_GC_LIMIT),
      verbose_(verbose),
      solve_(solve),
      max_utility_(game.MaxUtility()),
      dirichlet_alpha_(dirichlet_alpha),
      dirichlet_epsilon_(dirichlet_epsilon),
      dont_return_chance_node_(dont_return_chance_node),
      rng_(seed),
      child_selection_policy_(child_selection_policy),
      evaluator_(evaluator) {
  GameType game_type = game.GetType();
  if (game_type.reward_model != GameType::RewardModel::kTerminal)
    SpielFatalError("Game must have terminal rewards.");
  if (game_type.dynamics != GameType::Dynamics::kSequential)
    SpielFatalError("Game must have sequential turns.");
}
References open_spiel::GameType::dynamics, open_spiel::GameType::kSequential, open_spiel::GameType::kTerminal, open_spiel::GameType::reward_model, and open_spiel::SpielFatalError().
~MCTSBot()
open_spiel::algorithms::MCTSBot::~MCTSBot () default
Member Function Documentation
MCTSearch()
std::unique_ptr< SearchNode > open_spiel::algorithms::MCTSBot::MCTSearch (const State & state)
Definition at line 351 of file mcts.cc.
{
  nodes_ = 1;
  gc_limit_ = MIN_GC_LIMIT;
  auto root = std::make_unique<SearchNode>(kInvalidAction,
                                           state.CurrentPlayer(), 1);
  std::vector<SearchNode*> visit_path;
  std::vector<double> returns;
  visit_path.reserve(64);
  for (int i = 0; i < max_simulations_; ++i) {
    visit_path.clear();
    returns.clear();
    std::unique_ptr<State> working_state =
        ApplyTreePolicy(root.get(), state, &visit_path);
    bool solved;
    if (working_state->IsTerminal()) {
      returns = working_state->Returns();
      visit_path[visit_path.size() - 1]->outcome = returns;
      solved = solve_;
    } else {
      returns = evaluator_->Evaluate(*working_state);
      solved = false;
    }
    // Propagate values back.
    while (!visit_path.empty()) {
      int decision_node_idx = visit_path.size() - 1;
      SearchNode* node = visit_path[decision_node_idx];
      // If it's a chance node, find the parent player id.
      while (visit_path[decision_node_idx]->player == kChancePlayerId) {
        decision_node_idx--;
      }
      node->total_reward += returns[visit_path[decision_node_idx]->player];
      node->explore_count += 1;
      visit_path.pop_back();
      // Back up solved results as well.
      if (solved && !node->children.empty()) {
        Player player = node->children[0].player;
        if (player == kChancePlayerId) {
          // Only back up chance nodes if all have the same outcome.
          // An alternative would be to back up the weighted average of
          // outcomes if all children are solved, but that is less clear.
          const std::vector<double>& outcome = node->children[0].outcome;
          if (!outcome.empty() &&
              std::all_of(node->children.begin() + 1, node->children.end(),
                          [&outcome](const SearchNode& c) {
                            return c.outcome == outcome;
                          })) {
            node->outcome = outcome;
          } else {
            solved = false;
          }
        } else {
          // If any have max utility (won?), or all children are solved,
          // choose the one best for the player choosing.
          const SearchNode* best = nullptr;
          bool all_solved = true;
          for (const SearchNode& child : node->children) {
            if (child.outcome.empty()) {
              all_solved = false;
            } else if (best == nullptr ||
                       child.outcome[player] > best->outcome[player]) {
              best = &child;
            }
          }
          if (best != nullptr &&
              (all_solved || best->outcome[player] == max_utility_)) {
            node->outcome = best->outcome;
          } else {
            solved = false;
          }
        }
      }
    }
    if (!root->outcome.empty() ||  // Full game tree is solved.
        root->children.size() == 1) {
      break;
    }
    if (max_nodes_ > 1 && nodes_ >= max_nodes_) {
      // Note that actual memory used as counted by ps/top might exceed the
      // counted value here, possibly by a significant margin (1.5x even!). Part
      // of that is not counting the outcome array, but most of that is due to
      // memory fragmentation and is out of our control without writing our own
      // memory manager.
      if (verbose_) {
        std::cerr << absl::StrFormat(
            ("Approx %d mb in %d nodes after %d sims, garbage collecting with "
             "limit %d ... "),
            MemoryUsedMb(nodes_), nodes_, i, gc_limit_);
      }
      GarbageCollect(root.get());
      // Slowly increase or decrease to target releasing half the memory.
      gc_limit_ *= (nodes_ > max_nodes_ / 2 ? 1.25 : 0.9);
      gc_limit_ = std::max(MIN_GC_LIMIT, gc_limit_);
      if (verbose_) {
        std::cerr << absl::StrFormat(
            "%d mb in %d nodes remaining\n",
            MemoryUsedMb(nodes_), nodes_);
      }
    }
  }
  return root;
}
References open_spiel::algorithms::SearchNode::children, open_spiel::algorithms::SearchNode::explore_count, i, open_spiel::kChancePlayerId, open_spiel::kInvalidAction, open_spiel::algorithms::MemoryUsedMb(), open_spiel::algorithms::MIN_GC_LIMIT, open_spiel::algorithms::SearchNode::outcome, player, state, absl::StrFormat(), and open_spiel::algorithms::SearchNode::total_reward.
Referenced by define_julia_module(), open_spiel::init_pyspiel_bots(), and Step().
Restart()
void open_spiel::algorithms::MCTSBot::Restart () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 172 of file mcts.h.
{}
Referenced by define_julia_module().
RestartAt()
void open_spiel::algorithms::MCTSBot::RestartAt (const State & state) inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 173 of file mcts.h.
{}
Referenced by define_julia_module().
Step()
Action open_spiel::algorithms::MCTSBot::Step (const State & state) override virtual
Implements open_spiel::Bot.
Definition at line 231 of file mcts.cc.
{
  absl::Time start = absl::Now();
  std::unique_ptr<SearchNode> root = MCTSearch(state);
  if (max_simulations_ <= 1) {
    // sample from prior
    return root->SampleFromPrior(state, evaluator_.get(), &rng_);
  } else {
    // return best action
    const SearchNode& best = root->BestChild();
    if (verbose_) {
      double seconds = absl::ToDoubleSeconds(absl::Now() - start);
      std::cerr << absl::StrFormat(
                       ("Finished %d sims in %.3f secs, %.1f sims/s, "
                        "tree size: %d nodes / %d mb."),
                       root->explore_count, seconds,
                       (root->explore_count / seconds), nodes_,
                       MemoryUsedMb(nodes_))
                << std::endl;
      std::cerr << "Root:" << std::endl;
      std::cerr << root->ToString(state) << std::endl;
      std::cerr << "Children:" << std::endl;
      std::cerr << root->ChildrenStr(state) << std::endl;
      if (!best.children.empty()) {
        std::unique_ptr<State> chosen_state = state.Clone();
        chosen_state->ApplyAction(best.action);
        std::cerr << "Children of chosen:" << std::endl;
        std::cerr << best.ChildrenStr(*chosen_state) << std::endl;
      }
    }
    return best.action;
  }
}
References open_spiel::algorithms::SearchNode::action, open_spiel::algorithms::SearchNode::BestChild(), open_spiel::algorithms::SearchNode::children, open_spiel::algorithms::SearchNode::ChildrenStr(), MCTSearch(), open_spiel::algorithms::MemoryUsedMb(), absl::Now(), state, absl::StrFormat(), and absl::ToDoubleSeconds().
Referenced by define_julia_module(), open_spiel::init_pyspiel_bots(), and StepWithPolicy().
StepWithPolicy()
std::pair< ActionsAndProbs, Action > open_spiel::algorithms::MCTSBot::StepWithPolicy (const State & state) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 266 of file mcts.cc.
{
  Action action = Step(state);
  return {{{action, 1.}}, action};
}
References action, state, and Step().
Referenced by define_julia_module().
The documentation for this class was generated from the following files:
open_spiel/algorithms/mcts.h
open_spiel/algorithms/mcts.cc