open spiel: absl::poisson_distribution< IntType > Class Template Reference
absl::poisson_distribution< IntType > Class Template Reference
#include <poisson_distribution.h>
Classes
class param_type
Public Types
using result_type = IntType
Public Member Functions
poisson_distribution ()
poisson_distribution (double mean)
poisson_distribution (const param_type &p)
void reset ()
template<typename URBG >
result_type operator() (URBG &g)
template<typename URBG >
result_type operator() (URBG &g, const param_type &p)
param_type param () const
void param (const param_type &p)
result_type min () const
result_type max () const
double mean () const
Friends
bool operator== (const poisson_distribution &a, const poisson_distribution &b)
bool operator!= (const poisson_distribution &a, const poisson_distribution &b)
Detailed Description
template<typename IntType = int>
class absl::poisson_distribution< IntType >
Definition at line 55 of file poisson_distribution.h.
Member Typedef Documentation
result_type
template<typename IntType = int> using absl::poisson_distribution< IntType >::result_type = IntType
Definition at line 57 of file poisson_distribution.h.
Constructor & Destructor Documentation
poisson_distribution() [1/3]
template<typename IntType = int> absl::poisson_distribution< IntType >::poisson_distribution () inline
Definition at line 89 of file poisson_distribution.h.
: poisson_distribution(1.0) {}
poisson_distribution() [2/3]
template<typename IntType = int> absl::poisson_distribution< IntType >::poisson_distribution (double mean) inline explicit
Definition at line 91 of file poisson_distribution.h.
: param_(mean) {}
poisson_distribution() [3/3]
template<typename IntType = int> absl::poisson_distribution< IntType >::poisson_distribution (const param_type & p) inline explicit
Definition at line 93 of file poisson_distribution.h.
: param_(p) {}
Member Function Documentation
max()
template<typename IntType = int> result_type absl::poisson_distribution< IntType >::max () const inline
Definition at line 111 of file poisson_distribution.h.
{ return (std::numeric_limits<result_type>::max)(); }
Referenced by absl::poisson_distribution< IntType >::operator()().
mean()
template<typename IntType = int> double absl::poisson_distribution< IntType >::mean () const inline
Definition at line 113 of file poisson_distribution.h.
{ return param_.mean(); }
References absl::poisson_distribution< IntType >::param_type::mean().
Referenced by absl::operator>>().
min()
template<typename IntType = int> result_type absl::poisson_distribution< IntType >::min () const inline
Definition at line 110 of file poisson_distribution.h.
{ return 0; }
operator()() [1/2]
template<typename IntType = int> template<typename URBG > result_type absl::poisson_distribution< IntType >::operator() (URBG & g) inline
Definition at line 99 of file poisson_distribution.h.
                                  {  // NOLINT(runtime/references)
    return (*this)(g, param_);
  }
References absl::g.
operator()() [2/2]
template<typename IntType > template<typename URBG > poisson_distribution< IntType >::result_type absl::poisson_distribution< IntType >::operator() (URBG & g, const param_type & p)
Definition at line 167 of file poisson_distribution.h.
{
  using random_internal::GeneratePositiveTag;
  using random_internal::GenerateRealFromBits;
  using random_internal::GenerateSignedTag;
  if (p.split_ != 0) {
    // Use Knuth's algorithm with range splitting to avoid floating-point
    // errors. Knuth's algorithm is: Ui is a sequence of uniform variates on
    // (0,1); return the number of variates required for product(Ui) <
    // exp(-lambda).
    //
    // The expected number of variates required for Knuth's method can be
    // computed as follows:
    // The expected value of U is 0.5, so solving for 0.5^n < exp(-lambda) gives
    // the expected number of uniform variates
    // required for a given lambda, which is:
    //  lambda = [2, 5,  9, 10, 11, 12, 13, 14, 15, 16, 17]
    //  n      = [3, 8, 13, 15, 16, 18, 19, 21, 22, 24, 25]
    //
    result_type n = 0;
    for (int split = p.split_; split > 0; --split) {
      double r = 1.0;
      do {
        r *= GenerateRealFromBits<double, GeneratePositiveTag, true>(
            fast_u64_(g));  // U(-1, 0)
        ++n;
      } while (r > p.emu_);
      --n;
    }
    return n;
  }
  // Use ratio of uniforms method.
  //
  // Let u ~ Uniform(0, 1), v ~ Uniform(-1, 1),
  //     a = lambda + 1/2,
  //     s = 1.5 - sqrt(3/e) + sqrt(2(lambda + 1/2)/e),
  //     x = s * v/u + a.
  // P(floor(x) = k | u^2 < f(floor(x))/k), where
  // f(m) = lambda^m exp(-lambda)/ m!, for 0 <= m, and f(m) = 0 otherwise,
  // and k = max(f).
  const double a = p.mean_ + 0.5;
  for (;;) {
    const double u = GenerateRealFromBits<double, GeneratePositiveTag, false>(
        fast_u64_(g));  // U(0, 1)
    const double v = GenerateRealFromBits<double, GenerateSignedTag, false>(
        fast_u64_(g));  // U(-1, 1)
    const double x = std::floor(p.s_ * v / u + a);
    if (x < 0) continue;  // f(negative) = 0
    const double rhs = x * p.lmu_;
    // clang-format off
    double s = (x <= 1.0) ? 0.0
             : (x == 2.0) ? 0.693147180559945
             : absl::random_internal::StirlingLogFactorial(x);
    // clang-format on
    const double lhs = 2.0 * std::log(u) + p.log_k_ + s;
    if (lhs < rhs) {
      return x > static_cast<double>((max)())
                 ? (max)()
                 : static_cast<result_type>(x);  // f(x)/k >= u^2
    }
  }
}
References absl::a, absl::g, absl::random_internal::GenerateRealFromBits(), absl::poisson_distribution< IntType >::max(), absl::n, absl::p, r, absl::s, absl::random_internal::StirlingLogFactorial(), absl::u, absl::v, and absl::x.
param() [1/2]
template<typename IntType = int> param_type absl::poisson_distribution< IntType >::param () const inline
Definition at line 107 of file poisson_distribution.h.
{ return param_; }
param() [2/2]
template<typename IntType = int> void absl::poisson_distribution< IntType >::param (const param_type & p) inline
Definition at line 108 of file poisson_distribution.h.
{ param_ = p; }
References absl::p.
reset()
template<typename IntType = int> void absl::poisson_distribution< IntType >::reset () inline
Definition at line 95 of file poisson_distribution.h.
{}
Referenced by open_spiel.python.utils.stats.BasicStats::__init__(), open_spiel.python.algorithms.ismcts.ISMCTSBot::run_search(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
Friends And Related Symbol Documentation
operator!=
template<typename IntType = int> bool operator!= (const poisson_distribution< IntType > & a, const poisson_distribution< IntType > & b) friend
Definition at line 119 of file poisson_distribution.h.
{
    return a.param_ != b.param_;
  }
operator==
template<typename IntType = int> bool operator== (const poisson_distribution< IntType > & a, const poisson_distribution< IntType > & b) friend
Definition at line 115 of file poisson_distribution.h.
{
    return a.param_ == b.param_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/poisson_distribution.h