open spiel: open_spiel::StopToken Class Reference
open_spiel::StopToken Class Reference
#include <thread.h>
Public Member Functions
StopToken ()
void Stop ()
bool StopRequested () const
Detailed Description
Definition at line 46 of file thread.h.
Constructor & Destructor Documentation
StopToken()
open_spiel::StopToken::StopToken () inline
Definition at line 48 of file thread.h.
: token_(false) {}
Member Function Documentation
Stop()
void open_spiel::StopToken::Stop () inline
Definition at line 49 of file thread.h.
{ token_ = true; }
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), signal_handler(), and open_spiel::algorithms::torch_az::VPNetEvaluator::~VPNetEvaluator().
StopRequested()
bool open_spiel::StopToken::StopRequested () const inline
Definition at line 50 of file thread.h.
{ return token_; }
Referenced by open_spiel::algorithms::torch_az::actor(), open_spiel::algorithms::torch_az::AlphaZero(), open_spiel::algorithms::torch_az::evaluator(), open_spiel::algorithms::torch_az::learner(), and signal_handler().
The documentation for this class was generated from the following file:
open_spiel/utils/thread.h