open spiel: absl::crc_internal::CRC32 Class Reference
absl::crc_internal::CRC32 Class Reference
#include <crc_internal.h>
Public Member Functions
CRC32 ()
~CRC32 () override
void Extend (uint32_t *crc, const void *bytes, size_t length) const override
void ExtendByZeroes (uint32_t *crc, size_t length) const override
void Scramble (uint32_t *crc) const override
void Unscramble (uint32_t *crc) const override
void UnextendByZeroes (uint32_t *crc, size_t length) const override
void InitTables () override
Public Member Functions inherited from absl::crc_internal::CRCImpl
CRCImpl ()
~CRCImpl () override=default
void Empty (uint32_t *crc) const override
Public Member Functions inherited from absl::crc_internal::CRC
virtual ~CRC ()
virtual void Concat (uint32_t *px, uint32_t y, size_t ylen)
Additional Inherited Members
Public Types inherited from absl::crc_internal::CRCImpl
using Uint32By256 = uint32_t[256]
Static Public Member Functions inherited from absl::crc_internal::CRCImpl
static CRCImpl * NewInternal ()
static void FillWordTable (uint32_t poly, uint32_t last, int word_size, Uint32By256 *t)
static int FillZeroesTable (uint32_t poly, Uint32By256 *t)
Static Public Member Functions inherited from absl::crc_internal::CRC
static CRC * Crc32c ()
Protected Member Functions inherited from absl::crc_internal::CRC
CRC ()
Detailed Description
Definition at line 97 of file crc_internal.h.
Constructor & Destructor Documentation
CRC32()
absl::crc_internal::CRC32::CRC32 () inline
Definition at line 99 of file crc_internal.h.
{}
~CRC32()
absl::crc_internal::CRC32::~CRC32 () inline override
Definition at line 100 of file crc_internal.h.
{}
Member Function Documentation
Extend()
void absl::crc_internal::CRC32::Extend (uint32_t * crc, const void * bytes, size_t length) const override virtual
Implements absl::crc_internal::CRC.
Definition at line 259 of file crc.cc.
{
  const uint8_t* p = static_cast<const uint8_t*>(bytes);
  const uint8_t* e = p + length;
  uint32_t l = *crc;
  auto step_one_byte = [this, &p, &l] () {
    int c = (l & 0xff) ^ *p++;
    l = this->table0_[c] ^ (l >> 8);
  };
  if (kNeedAlignedLoads) {
    // point x at first 4-byte aligned byte in string. this might be past the
    // end of the string.
    const uint8_t* x = RoundUp<4>(p);
    if (x <= e) {
      // Process bytes until finished or p is 4-byte aligned
      while (p != x) {
        step_one_byte();
      }
    }
  }
  const size_t kSwathSize = 16;
  if (static_cast<size_t>(e - p) >= kSwathSize) {
    // Load one swath of data into the operating buffers.
    uint32_t buf0 = absl::little_endian::Load32(p) ^ l;
    uint32_t buf1 = absl::little_endian::Load32(p + 4);
    uint32_t buf2 = absl::little_endian::Load32(p + 8);
    uint32_t buf3 = absl::little_endian::Load32(p + 12);
    p += kSwathSize;
    // Increment a CRC value by a "swath"; this combines the four bytes
    // starting at `ptr` and twelve zero bytes, so that four CRCs can be
    // built incrementally and combined at the end.
    const auto step_swath = [this](uint32_t crc_in, const std::uint8_t* ptr) {
      return absl::little_endian::Load32(ptr) ^
             this->table_[3][crc_in & 0xff] ^
             this->table_[2][(crc_in >> 8) & 0xff] ^
             this->table_[1][(crc_in >> 16) & 0xff] ^
             this->table_[0][crc_in >> 24];
    };
    // Run one CRC calculation step over all swaths in one 16-byte stride
    const auto step_stride = [&]() {
      buf0 = step_swath(buf0, p);
      buf1 = step_swath(buf1, p + 4);
      buf2 = step_swath(buf2, p + 8);
      buf3 = step_swath(buf3, p + 12);
      p += 16;
    };
    // Process kStride interleaved swaths through the data in parallel.
    while ((e - p) > kPrefetchHorizon) {
      base_internal::PrefetchNta(
          reinterpret_cast<const void*>(p + kPrefetchHorizon));
      // Process 64 bytes at a time
      step_stride();
      step_stride();
      step_stride();
      step_stride();
    }
    while (static_cast<size_t>(e - p) >= kSwathSize) {
      step_stride();
    }
    // Now advance one word at a time as far as possible. This isn't worth
    // doing if we have word-advance tables.
    while (static_cast<size_t>(e - p) >= 4) {
      buf0 = step_swath(buf0, p);
      uint32_t tmp = buf0;
      buf0 = buf1;
      buf1 = buf2;
      buf2 = buf3;
      buf3 = tmp;
      p += 4;
    }
    // Combine the results from the different swaths. This is just a CRC
    // on the data values in the bufX words.
    auto combine_one_word = [this](uint32_t crc_in, uint32_t w) {
      w ^= crc_in;
      for (size_t i = 0; i < 4; ++i) {
        w = (w >> 8) ^ this->table0_[w & 0xff];
      }
      return w;
    };
    l = combine_one_word(0, buf0);
    l = combine_one_word(l, buf1);
    l = combine_one_word(l, buf2);
    l = combine_one_word(l, buf3);
  }
  // Process the last few bytes
  while (p != e) {
    step_one_byte();
  }
  *crc = l;
}
References absl::c, absl::e, absl::i, absl::crc_internal::kPrefetchHorizon, absl::little_endian::Load32(), absl::p, absl::base_internal::PrefetchNta(), ptr, absl::crc_internal::RoundUp(), and absl::x.
ExtendByZeroes()
void absl::crc_internal::CRC32::ExtendByZeroes (uint32_t * crc, size_t length) const override virtual
Implements absl::crc_internal::CRC.
Definition at line 400 of file crc.cc.
{
  return CRC32::ExtendByZeroesImpl(crc, length, zeroes_, table0_);
}
InitTables()
void absl::crc_internal::CRC32::InitTables () override virtual
Implements absl::crc_internal::CRCImpl.
Definition at line 184 of file crc.cc.
                       {
  // Compute the table for extending a CRC by one byte.
  Uint32By256* t = new Uint32By256[4];
  FillWordTable(kCrc32cPoly, kCrc32cPoly, 1, t);
  for (int i = 0; i != 256; i++) {
    this->table0_[i] = t[0][i];
  }
  // Construct a table for updating the CRC by 4 bytes data followed by
  // 12 bytes of zeroes.
  //
  // Note: the data word size could be larger than the CRC size; it might
  // be slightly faster to use a 64-bit data word, but doing so doubles the
  // table size.
  uint32_t last = kCrc32cPoly;
  const size_t size = 12;
  for (size_t i = 0; i < size; ++i) {
    last = (last >> 8) ^ this->table0_[last & 0xff];
  }
  FillWordTable(kCrc32cPoly, last, 4, t);
  for (size_t b = 0; b < 4; ++b) {
    for (int i = 0; i < 256; ++i) {
      this->table_[b][i] = t[b][i];
    }
  }
  int j = FillZeroesTable(kCrc32cPoly, t);
  ABSL_RAW_CHECK(j <= static_cast<int>(ABSL_ARRAYSIZE(this->zeroes_)), "");
  for (int i = 0; i < j; i++) {
    this->zeroes_[i] = t[0][i];
  }
  delete[] t;
  // Build up tables for _reversing_ the operation of doing CRC operations on
  // zero bytes.
  // In C++, extending `crc` by a single zero bit is done by the following:
  // (A)  bool low_bit_set = (crc & 1);
  //      crc >>= 1;
  //      if (low_bit_set) crc ^= kCrc32cPoly;
  //
  // In particular note that the high bit of `crc` after this operation will be
  // set if and only if the low bit of `crc` was set before it.  This means that
  // no information is lost, and the operation can be reversed, as follows:
  // (B)  bool high_bit_set = (crc & 0x80000000u);
  //      if (high_bit_set) crc ^= kCrc32cPoly;
  //      crc <<= 1;
  //      if (high_bit_set) crc ^= 1;
  //
  // Or, equivalently:
  // (C)  bool high_bit_set = (crc & 0x80000000u);
  //      crc <<= 1;
  //      if (high_bit_set) crc ^= ((kCrc32cPoly << 1) ^ 1);
  //
  // The last observation is, if we store our checksums in variable `rcrc`,
  // with order of the bits reversed, the inverse operation becomes:
  // (D)  bool low_bit_set = (rcrc & 1);
  //      rcrc >>= 1;
  //      if (low_bit_set) rcrc ^= ReverseBits((kCrc32cPoly << 1) ^ 1)
  //
  // This is the same algorithm (A) that we started with, only with a different
  // polynomial bit pattern.  This means that by building up our tables with
  // this alternate polynomial, we can apply the CRC algorithms to a
  // bit-reversed CRC checksum to perform inverse zero-extension.
  const uint32_t kCrc32cUnextendPoly =
      ReverseBits(static_cast<uint32_t>((kCrc32cPoly << 1) ^ 1));
  FillWordTable(kCrc32cUnextendPoly, kCrc32cUnextendPoly, 1, &reverse_table0_);
  j = FillZeroesTable(kCrc32cUnextendPoly, &reverse_zeroes_);
  ABSL_RAW_CHECK(j <= static_cast<int>(ABSL_ARRAYSIZE(this->reverse_zeroes_)),
                 "");
}
References ABSL_ARRAYSIZE, ABSL_RAW_CHECK, b, absl::crc_internal::CRCImpl::FillWordTable(), absl::crc_internal::CRCImpl::FillZeroesTable(), absl::i, and size.
Scramble()
void absl::crc_internal::CRC32::Scramble (uint32_t * crc) const override virtual
Implements absl::crc_internal::CRC.
Definition at line 412 of file crc.cc.
{
  // Rotate by near half the word size plus 1.  See the scramble comment in
  // crc_internal.h for an explanation.
  constexpr int scramble_rotate = (32 / 2) + 1;
  *crc = RotateRight<uint32_t>(static_cast<unsigned int>(*crc + kScrambleLo),
                               32, scramble_rotate) &
         MaskOfLength<uint32_t>(32);
}
References absl::crc_internal::kScrambleLo, absl::crc_internal::MaskOfLength(), and absl::crc_internal::RotateRight().
UnextendByZeroes()
void absl::crc_internal::CRC32::UnextendByZeroes (uint32_t * crc, size_t length) const override virtual
Implements absl::crc_internal::CRC.
Definition at line 404 of file crc.cc.
{
  // See the comment in CRC32::InitTables() for an explanation of the algorithm
  // below.
  *crc = ReverseBits(*crc);
  ExtendByZeroesImpl(crc, length, reverse_zeroes_, reverse_table0_);
  *crc = ReverseBits(*crc);
}
Unscramble()
void absl::crc_internal::CRC32::Unscramble (uint32_t * crc) const override virtual
Implements absl::crc_internal::CRC.
Definition at line 421 of file crc.cc.
{
  constexpr int scramble_rotate = (32 / 2) + 1;
  uint64_t rotated = RotateRight<uint32_t>(static_cast<unsigned int>(*crc), 32,
                                           32 - scramble_rotate);
  *crc = (rotated - kScrambleLo) & MaskOfLength<uint32_t>(32);
}
References absl::crc_internal::kScrambleLo, absl::crc_internal::MaskOfLength(), and absl::crc_internal::RotateRight().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/crc/internal/crc_internal.h
open_spiel/abseil-cpp/absl/crc/internal/crc.cc