open spiel: absl::cord_internal::CordRepRingReader Class Reference
absl::cord_internal::CordRepRingReader Class Reference
#include <cord_rep_ring_reader.h>
Public Member Functions
operator bool () const
CordRepRing * ring () const
CordRepRing::index_type index () const
CordRep * node () const
size_t length () const
size_t consumed () const
size_t remaining () const
void Reset ()
absl::string_view Reset (CordRepRing *ring)
absl::string_view Next ()
absl::string_view Seek (size_t offset)
Detailed Description
Definition at line 31 of file cord_rep_ring_reader.h.
Member Function Documentation
consumed()
size_t absl::cord_internal::CordRepRingReader::consumed () const inline
Definition at line 59 of file cord_rep_ring_reader.h.
{
    assert(ring_);
    return ring_->entry_end_offset(index_);
  }
References absl::cord_internal::CordRepRing::entry_end_offset().
Referenced by remaining().
index()
CordRepRing::index_type absl::cord_internal::CordRepRingReader::index () const inline
Definition at line 41 of file cord_rep_ring_reader.h.
{ return index_; }
Referenced by open_spiel.python.egt.visualization.SimplexStreamMask::__getitem__(), and open_spiel.python.egt.visualization.SimplexStreamMask::__setitem__().
length()
size_t absl::cord_internal::CordRepRingReader::length () const inline
Definition at line 49 of file cord_rep_ring_reader.h.
{
    assert(ring_);
    return ring_->length;
  }
References absl::cord_internal::CordRep::length.
Referenced by remaining(), and Seek().
Next()
absl::string_view absl::cord_internal::CordRepRingReader::Next () inline
Definition at line 86 of file cord_rep_ring_reader.h.
{
    assert(remaining());
    index_ = ring_->advance(index_);
    return ring_->entry_data(index_);
  }
References absl::cord_internal::CordRepRing::advance(), absl::cord_internal::CordRepRing::entry_data(), and remaining().
node()
CordRep * absl::cord_internal::CordRepRingReader::node () const inline
Definition at line 45 of file cord_rep_ring_reader.h.
{ return ring_->entry_child(index_); }
References absl::cord_internal::CordRepRing::entry_child().
operator bool()
absl::cord_internal::CordRepRingReader::operator bool () const inline explicit
Definition at line 34 of file cord_rep_ring_reader.h.
{ return ring_ != nullptr; }
remaining()
size_t absl::cord_internal::CordRepRingReader::remaining () const inline
Definition at line 66 of file cord_rep_ring_reader.h.
{
    assert(ring_);
    return length() - consumed();
  }
References consumed(), and length().
Referenced by Next().
Reset() [1/2]
void absl::cord_internal::CordRepRingReader::Reset () inline
Definition at line 72 of file cord_rep_ring_reader.h.
{ ring_ = nullptr; }
Reset() [2/2]
absl::string_view absl::cord_internal::CordRepRingReader::Reset (CordRepRing * ring) inline
Definition at line 76 of file cord_rep_ring_reader.h.
{
    assert(ring);
    ring_ = ring;
    index_ = ring_->head();
    return ring_->entry_data(index_);
  }
References absl::cord_internal::CordRepRing::entry_data(), absl::cord_internal::CordRepRing::head(), and ring().
ring()
CordRepRing * absl::cord_internal::CordRepRingReader::ring () const inline
Definition at line 37 of file cord_rep_ring_reader.h.
{ return ring_; }
Referenced by Reset().
Seek()
absl::string_view absl::cord_internal::CordRepRingReader::Seek (size_t offset) inline
Definition at line 98 of file cord_rep_ring_reader.h.
{
    assert(offset < length());
    size_t current = ring_->entry_end_offset(index_);
    CordRepRing::index_type hint = (offset >= current) ? index_ : ring_->head();
    const CordRepRing::Position head = ring_->Find(hint, offset);
    index_ = head.index;
    auto data = ring_->entry_data(head.index);
    data.remove_prefix(head.offset);
    return data;
  }
References data, absl::cord_internal::CordRepRing::entry_data(), absl::cord_internal::CordRepRing::entry_end_offset(), absl::cord_internal::CordRepRing::Find(), absl::cord_internal::CordRepRing::head(), absl::cord_internal::CordRepRing::Position::index, length(), absl::cord_internal::CordRepRing::Position::offset, and absl::string_view::remove_prefix().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_ring_reader.h