open spiel: absl::uniform_int_distribution< IntType > Class Template Reference
absl::uniform_int_distribution< IntType > Class Template Reference
#include <uniform_int_distribution.h>
Classes
class param_type
Public Types
using result_type = IntType
Public Member Functions
uniform_int_distribution ()
uniform_int_distribution (result_type lo, result_type hi=(std::numeric_limits< result_type >::max)())
uniform_int_distribution (const param_type &param)
void reset ()
template<typename URBG >
result_type operator() (URBG &gen)
template<typename URBG >
result_type operator() (URBG &gen, const param_type &param)
result_type a () const
result_type b () const
param_type param () const
void param (const param_type &params)
result_type min () const
result_type max () const
template<typename URBG >
random_internal::make_unsigned_bits< IntType >::type Generate (URBG &g, typename random_internal::make_unsigned_bits< IntType >::type R)
Friends
bool operator== (const uniform_int_distribution &a, const uniform_int_distribution &b)
bool operator!= (const uniform_int_distribution &a, const uniform_int_distribution &b)
Detailed Description
template<typename IntType = int>
class absl::uniform_int_distribution< IntType >
Definition at line 58 of file uniform_int_distribution.h.
Member Typedef Documentation
result_type
template<typename IntType = int> using absl::uniform_int_distribution< IntType >::result_type = IntType
Definition at line 64 of file uniform_int_distribution.h.
Constructor & Destructor Documentation
uniform_int_distribution() [1/3]
template<typename IntType = int> absl::uniform_int_distribution< IntType >::uniform_int_distribution () inline
Definition at line 105 of file uniform_int_distribution.h.
: uniform_int_distribution(0) {}
uniform_int_distribution() [2/3]
template<typename IntType = int> absl::uniform_int_distribution< IntType >::uniform_int_distribution (result_type lo, result_type hi = (std::numeric_limits<result_type>::max)()) inline explicit
Definition at line 107 of file uniform_int_distribution.h.
      : param_(lo, hi) {}
uniform_int_distribution() [3/3]
template<typename IntType = int> absl::uniform_int_distribution< IntType >::uniform_int_distribution (const param_type & param) inline explicit
Definition at line 112 of file uniform_int_distribution.h.
: param_(param) {}
Member Function Documentation
a()
template<typename IntType = int> result_type absl::uniform_int_distribution< IntType >::a () const inline
Definition at line 131 of file uniform_int_distribution.h.
{ return param_.a(); }
References absl::uniform_int_distribution< IntType >::param_type::a().
Referenced by absl::uniform_int_distribution< IntType >::min().
b()
template<typename IntType = int> result_type absl::uniform_int_distribution< IntType >::b () const inline
Definition at line 132 of file uniform_int_distribution.h.
{ return param_.b(); }
References absl::uniform_int_distribution< IntType >::param_type::b().
Referenced by absl::uniform_int_distribution< IntType >::max().
Generate()
template<typename IntType = int> template<typename URBG > random_internal::make_unsigned_bits< IntType >::type absl::uniform_int_distribution< IntType >::Generate (URBG & g, typename random_internal::make_unsigned_bits< IntType >::type R)
Definition at line 196 of file uniform_int_distribution.h.
{
  random_internal::FastUniformBits<unsigned_type> fast_bits;
  unsigned_type bits = fast_bits(g);
  const unsigned_type Lim = R + 1;
  if ((R & Lim) == 0) {
    // If the interval's length is a power of two range, just take the low bits.
    return bits & R;
  }
  // Generates a uniform variate on [0, Lim) using fixed-point multiplication.
  // The above fast-path guarantees that Lim is representable in unsigned_type.
  //
  // Algorithm adapted from
  // http://lemire.me/blog/2016/06/30/fast-random-shuffling/, with added
  // explanation.
  //
  // The algorithm creates a uniform variate `bits` in the interval [0, 2^N),
  // and treats it as the fractional part of a fixed-point real value in [0, 1),
  // multiplied by 2^N.  For example, 0.25 would be represented as 2^(N - 2),
  // because 2^N * 0.25 == 2^(N - 2).
  //
  // Next, `bits` and `Lim` are multiplied with a wide-multiply to bring the
  // value into the range [0, Lim).  The integral part (the high word of the
  // multiplication result) is then very nearly the desired result.  However,
  // this is not quite accurate; viewing the multiplication result as one
  // double-width integer, the resulting values for the sample are mapped as
  // follows:
  //
  // If the result lies in this interval:       Return this value:
  //        [0, 2^N)                                    0
  //        [2^N, 2 * 2^N)                              1
  //        ...                                         ...
  //        [K * 2^N, (K + 1) * 2^N)                    K
  //        ...                                         ...
  //        [(Lim - 1) * 2^N, Lim * 2^N)                Lim - 1
  //
  // While all of these intervals have the same size, the result of `bits * Lim`
  // must be a multiple of `Lim`, and not all of these intervals contain the
  // same number of multiples of `Lim`.  In particular, some contain
  // `F = floor(2^N / Lim)` and some contain `F + 1 = ceil(2^N / Lim)`.  This
  // difference produces a small nonuniformity, which is corrected by applying
  // rejection sampling to one of the values in the "larger intervals" (i.e.,
  // the intervals containing `F + 1` multiples of `Lim`.
  //
  // An interval contains `F + 1` multiples of `Lim` if and only if its smallest
  // value modulo 2^N is less than `2^N % Lim`.  The unique value satisfying
  // this property is used as the one for rejection.  That is, a value of
  // `bits * Lim` is rejected if `(bit * Lim) % 2^N < (2^N % Lim)`.
  using helper = random_internal::wide_multiply<unsigned_type>;
  auto product = helper::multiply(bits, Lim);
  // Two optimizations here:
  // * Rejection occurs with some probability less than 1/2, and for reasonable
  //   ranges considerably less (in particular, less than 1/(F+1)), so
  //   ABSL_PREDICT_FALSE is apt.
  // * `Lim` is an overestimate of `threshold`, and doesn't require a divide.
  if (ABSL_PREDICT_FALSE(helper::lo(product) < Lim)) {
    // This quantity is exactly equal to `2^N % Lim`, but does not require high
    // precision calculations: `2^N % Lim` is congruent to `(2^N - Lim) % Lim`.
    // Ideally this could be expressed simply as `-X` rather than `2^N - X`, but
    // for types smaller than int, this calculation is incorrect due to integer
    // promotion rules.
    const unsigned_type threshold =
        ((std::numeric_limits<unsigned_type>::max)() - Lim + 1) % Lim;
    while (helper::lo(product) < threshold) {
      bits = fast_bits(g);
      product = helper::multiply(bits, Lim);
    }
  }
  return helper::hi(product);
}
References ABSL_PREDICT_FALSE, and absl::g.
max()
template<typename IntType = int> result_type absl::uniform_int_distribution< IntType >::max () const inline
Definition at line 138 of file uniform_int_distribution.h.
{ return b(); }
References absl::uniform_int_distribution< IntType >::b().
min()
template<typename IntType = int> result_type absl::uniform_int_distribution< IntType >::min () const inline
Definition at line 137 of file uniform_int_distribution.h.
{ return a(); }
References absl::uniform_int_distribution< IntType >::a().
operator()() [1/2]
template<typename IntType = int> template<typename URBG > result_type absl::uniform_int_distribution< IntType >::operator() (URBG & gen) inline
Definition at line 121 of file uniform_int_distribution.h.
                                    {  // NOLINT(runtime/references)
    return (*this)(gen, param());
  }
References absl::uniform_int_distribution< IntType >::param().
operator()() [2/2]
template<typename IntType = int> template<typename URBG > result_type absl::uniform_int_distribution< IntType >::operator() (URBG & gen, const param_type & param) inline
Definition at line 126 of file uniform_int_distribution.h.
                                          {  // NOLINT(runtime/references)
    return static_cast<result_type>(param.a() + Generate(gen, param.range()));
  }
References absl::uniform_int_distribution< IntType >::param_type::a(), and absl::uniform_int_distribution< IntType >::param().
param() [1/2]
template<typename IntType = int> param_type absl::uniform_int_distribution< IntType >::param () const inline
Definition at line 134 of file uniform_int_distribution.h.
{ return param_; }
Referenced by absl::uniform_int_distribution< IntType >::operator()(), and absl::uniform_int_distribution< IntType >::operator()().
param() [2/2]
template<typename IntType = int> void absl::uniform_int_distribution< IntType >::param (const param_type & params) inline
Definition at line 135 of file uniform_int_distribution.h.
{ param_ = params; }
reset()
template<typename IntType = int> void absl::uniform_int_distribution< IntType >::reset () inline
Definition at line 118 of file uniform_int_distribution.h.
{}
Referenced by open_spiel.python.utils.stats.BasicStats::__init__(), open_spiel.python.algorithms.ismcts.ISMCTSBot::run_search(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
Friends And Related Symbol Documentation
operator!=
template<typename IntType = int> bool operator!= (const uniform_int_distribution< IntType > & a, const uniform_int_distribution< IntType > & b) friend
Definition at line 144 of file uniform_int_distribution.h.
{
    return !(a == b);
  }
operator==
template<typename IntType = int> bool operator== (const uniform_int_distribution< IntType > & a, const uniform_int_distribution< IntType > & b) friend
Definition at line 140 of file uniform_int_distribution.h.
{
    return a.param_ == b.param_;
  }
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/random/internal/uniform_helper.h
open_spiel/abseil-cpp/absl/random/uniform_int_distribution.h