open spiel: absl::uniform_real_distribution< RealType > Class Template Reference
absl::uniform_real_distribution< RealType > Class Template Reference
#include <uniform_real_distribution.h>
Classes
class param_type
Public Types
using result_type = RealType
Public Member Functions
uniform_real_distribution ()
uniform_real_distribution (result_type lo, result_type hi=1)
uniform_real_distribution (const param_type &param)
void reset ()
template<typename URBG >
result_type operator() (URBG &gen)
template<typename URBG >
result_type operator() (URBG &gen, const param_type &p)
result_type a () const
result_type b () const
param_type param () const
void param (const param_type &params)
result_type min () const
result_type max () const
Friends
bool operator== (const uniform_real_distribution &a, const uniform_real_distribution &b)
bool operator!= (const uniform_real_distribution &a, const uniform_real_distribution &b)
Detailed Description
template<typename RealType = double>
class absl::uniform_real_distribution< RealType >
Definition at line 64 of file uniform_real_distribution.h.
Member Typedef Documentation
result_type
template<typename RealType = double> using absl::uniform_real_distribution< RealType >::result_type = RealType
Definition at line 66 of file uniform_real_distribution.h.
Constructor & Destructor Documentation
uniform_real_distribution() [1/3]
template<typename RealType = double> absl::uniform_real_distribution< RealType >::uniform_real_distribution () inline
Definition at line 104 of file uniform_real_distribution.h.
: uniform_real_distribution(0) {}
uniform_real_distribution() [2/3]
template<typename RealType = double> absl::uniform_real_distribution< RealType >::uniform_real_distribution (result_type lo, result_type hi = 1) inline explicit
Definition at line 106 of file uniform_real_distribution.h.
      : param_(lo, hi) {}
uniform_real_distribution() [3/3]
template<typename RealType = double> absl::uniform_real_distribution< RealType >::uniform_real_distribution (const param_type & param) inline explicit
Definition at line 109 of file uniform_real_distribution.h.
: param_(param) {}
Member Function Documentation
a()
template<typename RealType = double> result_type absl::uniform_real_distribution< RealType >::a () const inline
Definition at line 126 of file uniform_real_distribution.h.
{ return param_.a(); }
References absl::uniform_real_distribution< RealType >::param_type::a().
Referenced by absl::uniform_real_distribution< RealType >::min().
b()
template<typename RealType = double> result_type absl::uniform_real_distribution< RealType >::b () const inline
Definition at line 127 of file uniform_real_distribution.h.
{ return param_.b(); }
References absl::uniform_real_distribution< RealType >::param_type::b().
Referenced by absl::uniform_real_distribution< RealType >::max().
max()
template<typename RealType = double> result_type absl::uniform_real_distribution< RealType >::max () const inline
Definition at line 133 of file uniform_real_distribution.h.
{ return b(); }
References absl::uniform_real_distribution< RealType >::b().
min()
template<typename RealType = double> result_type absl::uniform_real_distribution< RealType >::min () const inline
Definition at line 132 of file uniform_real_distribution.h.
{ return a(); }
References absl::uniform_real_distribution< RealType >::a().
operator()() [1/2]
template<typename RealType = double> template<typename URBG > result_type absl::uniform_real_distribution< RealType >::operator() (URBG & gen) inline
Definition at line 118 of file uniform_real_distribution.h.
                                    {  // NOLINT(runtime/references)
    return operator()(gen, param_);
  }
References absl::uniform_real_distribution< RealType >::operator()().
Referenced by absl::uniform_real_distribution< RealType >::operator()().
operator()() [2/2]
template<typename RealType > template<typename URBG > uniform_real_distribution< RealType >::result_type absl::uniform_real_distribution< RealType >::operator() (URBG & gen, const param_type & p)
Definition at line 155 of file uniform_real_distribution.h.
                                    {  // NOLINT(runtime/references)
  using random_internal::GeneratePositiveTag;
  using random_internal::GenerateRealFromBits;
  using real_type =
      absl::conditional_t<std::is_same<RealType, float>::value, float, double>;
  while (true) {
    const result_type sample =
        GenerateRealFromBits<real_type, GeneratePositiveTag, true>(
            fast_u64_(gen));
    const result_type res = p.a() + (sample * p.range_);
    if (res < p.b() || p.range_ <= 0 || !std::isfinite(p.range_)) {
      return res;
    }
    // else sample rejected, try again.
  }
}
References absl::random_internal::GenerateRealFromBits(), and absl::p.
param() [1/2]
template<typename RealType = double> param_type absl::uniform_real_distribution< RealType >::param () const inline
Definition at line 129 of file uniform_real_distribution.h.
{ return param_; }
param() [2/2]
template<typename RealType = double> void absl::uniform_real_distribution< RealType >::param (const param_type & params) inline
Definition at line 130 of file uniform_real_distribution.h.
{ param_ = params; }
reset()
template<typename RealType = double> void absl::uniform_real_distribution< RealType >::reset () inline
Definition at line 115 of file uniform_real_distribution.h.
{}
Referenced by open_spiel.python.utils.stats.BasicStats::__init__(), open_spiel.python.algorithms.ismcts.ISMCTSBot::run_search(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
Friends And Related Symbol Documentation
operator!=
template<typename RealType = double> bool operator!= (const uniform_real_distribution< RealType > & a, const uniform_real_distribution< RealType > & b) friend
Definition at line 139 of file uniform_real_distribution.h.
{
    return a.param_ != b.param_;
  }
operator==
template<typename RealType = double> bool operator== (const uniform_real_distribution< RealType > & a, const uniform_real_distribution< RealType > & b) friend
Definition at line 135 of file uniform_real_distribution.h.
{
    return a.param_ == b.param_;
  }
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/random/internal/uniform_helper.h
open_spiel/abseil-cpp/absl/random/uniform_real_distribution.h