open spiel: open_spiel::pentago::PentagoState Class Reference
open_spiel::pentago::PentagoState Class Reference
#include <pentago.h>
Public Member Functions
PentagoState (std::shared_ptr< const Game > game, bool ansi_color_output=false)
PentagoState (const PentagoState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
PentagoPlayer get (int x, int y) const
PentagoPlayer get (int i) const
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 52 of file pentago.h.
Constructor & Destructor Documentation
PentagoState() [1/2]
open_spiel::pentago::PentagoState::PentagoState (std::shared_ptr< const Game > game, bool ansi_color_output = false)
Definition at line 152 of file pentago.cc.
    : State(std::move(game)), ansi_color_output_(ansi_color_output) {
  board_[0] = 0;
  board_[1] = 0;
}
Referenced by Clone().
PentagoState() [2/2]
open_spiel::pentago::PentagoState::PentagoState (const PentagoState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::pentago::PentagoState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 176 of file pentago.cc.
{
  return Move(action_id).ToString();
}
Clone()
std::unique_ptr< State > open_spiel::pentago::PentagoState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 321 of file pentago.cc.
{
  return std::unique_ptr<State>(new PentagoState(*this));
}
References PentagoState().
CurrentPlayer()
Player open_spiel::pentago::PentagoState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 59 of file pentago.h.
{
    return IsTerminal() ? kTerminalPlayerId : static_cast<int>(current_player_);
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::pentago::PentagoState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 281 of file pentago.cc.
{
  SPIEL_CHECK_EQ(outcome_, kPlayerNone);
  Move move(action);
  SPIEL_CHECK_EQ(get(move.xy), kPlayerNone);
  // Apply the move.
  board_[current_player_] |= xy_bit_mask[move.xy];
  if (move.dir == 0) {
    board_[0] = rotate_quadrant_ccw(board_[0], move.quadrant);
    board_[1] = rotate_quadrant_ccw(board_[1], move.quadrant);
  } else {
    board_[0] = rotate_quadrant_cw(board_[0], move.quadrant);
    board_[1] = rotate_quadrant_cw(board_[1], move.quadrant);
  }
  moves_made_++;
  // Check the win conditions.
  bool p1_won = false;
  bool p2_won = false;
  for (int i = 0; i < kPossibleWinConditions; i++) {
    uint64_t wm = win_mask[i];
    if ((board_[0] & wm) == wm) p1_won = true;
    if ((board_[1] & wm) == wm) p2_won = true;
  }
  // Note that you can rotate such that you cause your opponent to win.
  if (p1_won && p2_won) {
    outcome_ = kPlayerDraw;
  } else if (p1_won) {
    outcome_ = kPlayer1;
  } else if (p2_won) {
    outcome_ = kPlayer2;
  } else if (moves_made_ == kBoardPositions) {
    outcome_ = kPlayerDraw;
  }
  current_player_ = (current_player_ == kPlayer1 ? kPlayer2 : kPlayer1);
}
References action, get(), i, open_spiel::pentago::kBoardPositions, open_spiel::pentago::kPlayer1, open_spiel::pentago::kPlayer2, open_spiel::pentago::kPlayerDraw, open_spiel::pentago::kPlayerNone, open_spiel::pentago::kPossibleWinConditions, and SPIEL_CHECK_EQ.
get() [1/2]
PentagoPlayer open_spiel::pentago::PentagoState::get (int i) const protected
Definition at line 232 of file pentago.cc.
{
  return (board_[0] & xy_bit_mask[i]
              ? kPlayer1
              : board_[1] & xy_bit_mask[i] ? kPlayer2 : kPlayerNone);
}
References i, open_spiel::pentago::kPlayer1, open_spiel::pentago::kPlayer2, and open_spiel::pentago::kPlayerNone.
Referenced by open_spiel.python.utils.spawn._ProcessQueue::get_nowait().
get() [2/2]
PentagoPlayer open_spiel::pentago::PentagoState::get (int x, int y) const inline protected
Definition at line 79 of file pentago.h.
{ return get(x + y * kBoardSize); }
References get(), open_spiel::pentago::kBoardSize, x, and y.
Referenced by DoApplyAction(), get(), open_spiel.python.utils.spawn._ProcessQueue::get_nowait(), LegalActions(), ObservationTensor(), and ToString().
InformationStateString()
std::string open_spiel::pentago::PentagoState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 245 of file pentago.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::pentago::PentagoState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 64 of file pentago.h.
{ return outcome_ != kPlayerNone; }
References open_spiel::pentago::kPlayerNone.
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::pentago::PentagoState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 159 of file pentago.cc.
{
  // Can move in any empty cell, and do all rotations.
  std::vector<Action> moves;
  if (IsTerminal()) return moves;
  moves.reserve((kBoardPositions - moves_made_) * kPossibleRotations);
  for (int y = 0; y < kBoardSize; y++) {
    for (int x = 0; x < kBoardSize; x++) {
      if (get(x, y) == kPlayerNone) {
        for (int r = 0; r < kPossibleRotations; r++) {
          moves.push_back(Move(x, y, r).ToAction());
        }
      }
    }
  }
  return moves;
}
References get(), IsTerminal(), open_spiel::pentago::kBoardPositions, open_spiel::pentago::kBoardSize, open_spiel::pentago::kPlayerNone, open_spiel::pentago::kPossibleRotations, r, x, and y.
ObservationString()
std::string open_spiel::pentago::PentagoState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 251 of file pentago.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::pentago::PentagoState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 270 of file pentago.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<2> view(values, {kCellStates, kBoardPositions}, true);
  for (int i = 0; i < kBoardPositions; i++) {
    view[{PlayerRelative(get(i), player), i}] = 1.0;
  }
}
References get(), i, open_spiel::pentago::kBoardPositions, open_spiel::pentago::kCellStates, open_spiel::State::num_players_, player, open_spiel::pentago::PlayerRelative(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::pentago::PentagoState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 238 of file pentago.cc.
{
  if (outcome_ == kPlayer1) return {1, -1};
  if (outcome_ == kPlayer2) return {-1, 1};
  if (outcome_ == kPlayerDraw) return {0, 0};
  return {0, 0};  // Unfinished
}
References open_spiel::pentago::kPlayer1, open_spiel::pentago::kPlayer2, and open_spiel::pentago::kPlayerDraw.
ToString()
std::string open_spiel::pentago::PentagoState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 181 of file pentago.cc.
{
  // Generates something like:
  //     > t     u <
  //     a b c d e f
  // v 1 . . O @ . O v
  // s 2 . . O . . @ v
  //   3 . @ @ . @ O
  //   4 . @ @ . O .
  // z 5 @ . O @ O . w
  // ^ 6 @ O @ O O O ^
  //     > y     x <
  std::string white = "O";
  std::string black = "@";
  std::string empty = ".";
  std::string coord = "";
  std::string reset = "";
  if (ansi_color_output_) {
    std::string esc = "\033";
    reset = esc + "[0m";
    coord = esc + "[1;37m";  // bright white
    empty = reset + ".";
    white = esc + "[1;33m" + "@";  // bright yellow
    black = esc + "[1;34m" + "@";  // bright blue
  }
  // Enable the arrows if/when open_spiel allows unicode in strings.
  // constexpr char const* arrows[] = {"", "", "", "", "", "", "", ""};
  constexpr char const* arrows[] = {"v", ">", "<", "v", "^", "<", ">", "^"};
  constexpr char const* left[] = {arrows[0], "s", " ", " ", "z", arrows[7]};
  constexpr char const* right[] = {arrows[3], "v", " ", " ", "w", arrows[4]};
  std::ostringstream out;
  out << coord;
  out << "    " << arrows[1] << " t     u " << arrows[2] << "\n";
  out << "    a b c d e f\n";
  for (int y = 0; y < kBoardSize; y++) {
    out << left[y] << " " << (y + 1) << " ";
    for (int x = 0; x < kBoardSize; x++) {
      Player p = get(x, y);
      if (p == kPlayerNone) out << empty;
      if (p == kPlayer1) out << white;
      if (p == kPlayer2) out << black;
      out << " ";
    }
    out << coord << right[y] << "\n";
  }
  out << "    " << arrows[6] << " y     x " << arrows[5] << reset << "\n";
  return out.str();
}
References get(), open_spiel::pentago::kBoardSize, open_spiel::pentago::kPlayer1, open_spiel::pentago::kPlayer2, open_spiel::pentago::kPlayerNone, out, x, and y.
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/pentago/pentago.h
open_spiel/games/pentago/pentago.cc