open spiel: open_spiel::PreferredActionPolicy Class Reference
open_spiel::PreferredActionPolicy Class Reference
#include <policy.h>
Public Member Functions
PreferredActionPolicy (const std::vector< Action > &preference_order)
ActionsAndProbs GetStatePolicy (const State &state, Player player) const override
std::string Serialize (int double_precision=-1, std::string delimiter="") const override
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
virtual ActionsAndProbs GetStatePolicy (const State &state) const
virtual ActionsAndProbs GetStatePolicy (const std::string &info_state) const
Detailed Description
Definition at line 363 of file policy.h.
Constructor & Destructor Documentation
PreferredActionPolicy()
open_spiel::PreferredActionPolicy::PreferredActionPolicy (const std::vector< Action > & preference_order) inline
Definition at line 365 of file policy.h.
      : preference_order_(preference_order) {}
Member Function Documentation
GetStatePolicy()
ActionsAndProbs open_spiel::PreferredActionPolicy::GetStatePolicy (const State & state, Player player) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 477 of file policy.cc.
{
  std::vector<Action> legal_actions = state.LegalActions(player);
  for (Action action : preference_order_) {
    if (absl::c_find(legal_actions, action) != legal_actions.end()) {
      return GetDeterministicPolicy(legal_actions, action);
    }
  }
  SpielFatalError("No preferred action found in the legal actions!");
}
References open_spiel::GetDeterministicPolicy(), and open_spiel::SpielFatalError().
Serialize()
std::string open_spiel::PreferredActionPolicy::Serialize (int double_precision = -1, std::string delimiter = "") const inline override virtual
Reimplemented from open_spiel::Policy.
Definition at line 371 of file policy.h.
{
    SpielFatalError("Unimplemented.");
  }
References open_spiel::SpielFatalError().
The documentation for this class was generated from the following files:
open_spiel/policy.h
open_spiel/policy.cc