open spiel: open_spiel::algorithms::FSICFRSolver Class Reference
open_spiel::algorithms::FSICFRSolver Class Reference
#include <fsicfr.h>
Public Member Functions
FSICFRSolver (const Game &game, int seed, const std::vector< int > &chance_outcome_ranges, const FSICFRGraph *graph)
void RunIteration ()
void RunIterations (int n)
TabularPolicy GetAveragePolicy () const
Detailed Description
Definition at line 114 of file fsicfr.h.
Constructor & Destructor Documentation
FSICFRSolver()
open_spiel::algorithms::FSICFRSolver::FSICFRSolver (const Game & game, int seed, const std::vector< int > & chance_outcome_ranges, const FSICFRGraph * graph)
Definition at line 128 of file fsicfr.cc.
    : game_(game),
      rng_(seed),
      total_iterations_(0),
      chance_outcome_ranges_(chance_outcome_ranges),
      sampled_chance_outcomes_(game.NumPlayers()),
      graph_(graph) {}
Member Function Documentation
GetAveragePolicy()
TabularPolicy open_spiel::algorithms::FSICFRSolver::GetAveragePolicy () const
Definition at line 231 of file fsicfr.cc.
{
  TabularPolicy policy;
  for (int idx = 0; idx < graph_->size(); ++idx) {
    FSICFRNode* node = graph_->GetNode(idx);
    if (!node->terminal) {
      ActionsAndProbs state_policy;
      double denom = std::accumulate(node->ssum.begin(), node->ssum.end(), 0.0);
      SPIEL_CHECK_GE(denom, 0.0);
      for (int a = 0; a < node->legal_actions.size(); ++a) {
        Action action = node->legal_actions[a];
        double prob = denom > 0 ? node->ssum[a] / denom
                                : 1.0 / node->legal_actions.size();
        SPIEL_CHECK_PROB(prob);
        state_policy.push_back({action, prob});
      }
      policy.SetStatePolicy(node->string_key, state_policy);
    }
  }
  return policy;
}
References a, action, open_spiel::algorithms::FSICFRGraph::GetNode(), open_spiel::algorithms::FSICFRNode::legal_actions, open_spiel::algorithms::FSICFRGraph::size(), SPIEL_CHECK_GE, SPIEL_CHECK_PROB, open_spiel::algorithms::FSICFRNode::ssum, open_spiel::algorithms::FSICFRNode::string_key, and open_spiel::algorithms::FSICFRNode::terminal.
RunIteration()
void open_spiel::algorithms::FSICFRSolver::RunIteration ()
Definition at line 138 of file fsicfr.cc.
{
  // Predetermine chance outcomes (one per player).
  for (int i = 0; i < sampled_chance_outcomes_.size(); ++i) {
    sampled_chance_outcomes_[i] =
        absl::Uniform<int>(rng_, 0, chance_outcome_ranges_[i]);
    SPIEL_CHECK_GE(sampled_chance_outcomes_[i], 0);
    SPIEL_CHECK_LT(sampled_chance_outcomes_[i], chance_outcome_ranges_[i]);
  }
  ForwardPass();
  BackwardPass();
  total_iterations_++;
}
References i, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::Uniform().
Referenced by RunIterations().
RunIterations()
void open_spiel::algorithms::FSICFRSolver::RunIterations (int n)
Definition at line 151 of file fsicfr.cc.
{
  for (int i = 0; i < n; ++i) {
    RunIteration();
  }
}
References i, n, and RunIteration().
The documentation for this class was generated from the following files:
open_spiel/algorithms/fsicfr.h
open_spiel/algorithms/fsicfr.cc