open spiel: open_spiel::PyPolicy Class Reference
open_spiel::PyPolicy Class Reference
#include <python_policy.h>
Public Member Functions
~PyPolicy () override=default
PyPolicy ()=default
std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const override
std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const override
std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const override
std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const override
ActionsAndProbs GetStatePolicy (const State &state) const override
ActionsAndProbs GetStatePolicy (const State &state, Player player) const override
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
std::string Serialize (int double_precision, std::string delimiter) const override
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
Detailed Description
Definition at line 31 of file python_policy.h.
Constructor & Destructor Documentation
~PyPolicy()
open_spiel::PyPolicy::~PyPolicy () override default
PyPolicy()
open_spiel::PyPolicy::PyPolicy () default
Member Function Documentation
GetStatePolicy() [1/3]
ActionsAndProbs open_spiel::PyPolicy::GetStatePolicy (const State & state) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 50 of file python_policy.cc.
{
  PYBIND11_OVERRIDE_NAME(ActionsAndProbs, Policy, "get_state_policy",
                         GetStatePolicy, state);
}
References GetStatePolicy(), and state.
Referenced by GetStatePolicy(), GetStatePolicy(), and GetStatePolicy().
GetStatePolicy() [2/3]
ActionsAndProbs open_spiel::PyPolicy::GetStatePolicy (const State & state, Player player) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 54 of file python_policy.cc.
{
  PYBIND11_OVERRIDE_NAME(ActionsAndProbs, Policy, "get_state_policy",
                         GetStatePolicy, state, player);
}
References GetStatePolicy(), player, and state.
GetStatePolicy() [3/3]
ActionsAndProbs open_spiel::PyPolicy::GetStatePolicy (const std::string & info_state) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 59 of file python_policy.cc.
{
  PYBIND11_OVERRIDE_NAME(ActionsAndProbs, Policy, "get_state_policy",
                         GetStatePolicy, info_state);
}
References GetStatePolicy().
GetStatePolicyAsMap() [1/2]
std::unordered_map< Action, double > open_spiel::PyPolicy::GetStatePolicyAsMap (const State & state) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 39 of file python_policy.cc.
{
  PYBIND11_OVERRIDE_NAME(SINGLE_ARG(std::unordered_map<Action, double>), Policy,
                         "action_probabilities", GetStatePolicyAsMap, state);
}
References GetStatePolicyAsMap(), SINGLE_ARG, and state.
Referenced by GetStatePolicyAsMap(), and GetStatePolicyAsMap().
GetStatePolicyAsMap() [2/2]
std::unordered_map< Action, double > open_spiel::PyPolicy::GetStatePolicyAsMap (const std::string & info_state) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 44 of file python_policy.cc.
{
  PYBIND11_OVERRIDE_NAME(SINGLE_ARG(std::unordered_map<Action, double>), Policy,
                         "action_probabilities", GetStatePolicyAsMap,
                         info_state);
}
References GetStatePolicyAsMap(), and SINGLE_ARG.
GetStatePolicyAsParallelVectors() [1/2]
std::pair< std::vector< Action >, std::vector< double > > open_spiel::PyPolicy::GetStatePolicyAsParallelVectors (const State & state) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 26 of file python_policy.cc.
{
  PYBIND11_OVERRIDE_NAME(
      SINGLE_ARG(std::pair<std::vector<Action>, std::vector<double> >), Policy,
      "get_state_policy_as_parallel_vectors", GetStatePolicyAsParallelVectors,
      state);
}
References GetStatePolicyAsParallelVectors(), SINGLE_ARG, and state.
Referenced by GetStatePolicyAsParallelVectors(), and GetStatePolicyAsParallelVectors().
GetStatePolicyAsParallelVectors() [2/2]
std::pair< std::vector< Action >, std::vector< double > > open_spiel::PyPolicy::GetStatePolicyAsParallelVectors (const std::string & info_state) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 33 of file python_policy.cc.
{
  PYBIND11_OVERRIDE_NAME(
      SINGLE_ARG(std::pair<std::vector<Action>, std::vector<double> >), Policy,
      "get_state_policy_as_parallel_vectors", GetStatePolicyAsParallelVectors,
      info_state);
}
References GetStatePolicyAsParallelVectors(), and SINGLE_ARG.
Serialize()
std::string open_spiel::PyPolicy::Serialize (int double_precision, std::string delimiter) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 63 of file python_policy.cc.
{
  PYBIND11_OVERRIDE_NAME(std::string, Policy, "serialize", Serialize,
                         double_precision, delimiter);
}
References Serialize().
Referenced by Serialize().
The documentation for this class was generated from the following files:
open_spiel/python/pybind11/python_policy.h
open_spiel/python/pybind11/python_policy.cc