open spiel: open_spiel::solitaire::Move Class Reference
open_spiel::solitaire::Move Class Reference
#include <solitaire.h>
Public Member Functions
Move (Card target_card, Card source_card)
Move (RankType target_rank, SuitType target_suit, RankType source_rank, SuitType source_suit)
Move (Action action)
Card GetTarget () const
Card GetSource () const
std::string ToString (bool colored=true) const
bool operator< (const Move &other_move) const
Action ActionId () const
Detailed Description
Definition at line 212 of file solitaire.h.
Constructor & Destructor Documentation
Move() [1/3]
open_spiel::solitaire::Move::Move (Card target_card, Card source_card)
Definition at line 781 of file solitaire.cc.
{
  target_ = target_card;
  source_ = source_card;
}
Move() [2/3]
open_spiel::solitaire::Move::Move (RankType target_rank, SuitType target_suit, RankType source_rank, SuitType source_suit)
Definition at line 786 of file solitaire.cc.
{
  target_ = Card(false, target_suit, target_rank, LocationType::kMissing);
  source_ = Card(false, source_suit, source_rank, LocationType::kMissing);
}
References open_spiel::solitaire::kMissing.
Move() [3/3]
open_spiel::solitaire::Move::Move (Action action) explicit
Definition at line 792 of file solitaire.cc.
{
  // `base` refers to the starting point that indices start from (e.g. if it's
  // 7, and there's 3 cards in its group, their action ids will be 8, 9, 10).
  // `residual` is just the difference between the id and the base.
  int residual;
  int target_rank;
  int source_rank;
  int target_suit;
  int source_suit;
  std::vector<SuitType> opposite_suits;
  action -= kActionOffset;
  // The numbers used in the cases below are just used to divide action ids into
  // groups (e.g. 1-132 are regular moves, 133-136 are the action ids of moves
  // that move an ace to an empty foundation, etc.)
  if (action >= 1 && action <= 132) {
    // Handles ordinary moves
    target_rank = ((action - 1) / 3) % 11 + 2;
    target_suit = ((action - 1) / 33) + 1;
    residual = ((action - 1) % 3);
    if (residual == 0) {
      source_rank = target_rank + 1;
      source_suit = target_suit;
    } else {
      opposite_suits = GetOppositeSuits(static_cast<SuitType>(target_suit));
      source_rank = target_rank - 1;
      source_suit = static_cast<int>(opposite_suits[residual - 1]);
    }
  } else if (action >= 133 && action <= 136) {
    // Handles ace to empty foundation moves
    target_rank = 0;
    target_suit = action - 132;
    source_rank = 1;
    source_suit = target_suit;
  } else if (action >= 137 && action <= 140) {
    // Handles king to empty tableau moves
    target_rank = 0;
    target_suit = 0;
    source_rank = 13;
    source_suit = action - 136;
  } else if (action >= 141 && action <= 144) {
    // Handles moves with ace targets
    target_rank = 1;
    target_suit = action - 140;
    source_rank = 2;
    source_suit = target_suit;
  } else if (action >= 145 && action <= 152) {
    // Handles moves with king targets
    target_rank = 13;
    target_suit = (action - 143) / 2;
    residual = (action - 143) % 2;
    opposite_suits = GetOppositeSuits(static_cast<SuitType>(target_suit));
    source_rank = 12;
    source_suit = static_cast<int>(opposite_suits[residual]);
  } else {
    SpielFatalError("action provided does not correspond with a move");
  }
  target_ = Card(false, static_cast<SuitType>(target_suit),
                 static_cast<RankType>(target_rank));
  source_ = Card(false, static_cast<SuitType>(source_suit),
                 static_cast<RankType>(source_rank));
}
References action, open_spiel::solitaire::GetOppositeSuits(), and open_spiel::SpielFatalError().
Member Function Documentation
ActionId()
Action open_spiel::solitaire::Move::ActionId () const
Definition at line 869 of file solitaire.cc.
{
  int target_rank = static_cast<int>(target_.GetRank());
  int source_rank = static_cast<int>(source_.GetRank());
  int target_suit = static_cast<int>(target_.GetSuit());
  int source_suit = static_cast<int>(source_.GetSuit());
  int base;
  int residual;
  // `base` refers to the starting point that indices start from (e.g. if it's
  // 7, and there's 3 cards in its group, their action ids will be 8, 9, 10).
  // `residual` is just the difference between the id and the base.
  switch (target_rank) {
    case static_cast<int>(RankType::kNone): {
      switch (source_rank) {
        case static_cast<int>(RankType::kA): {
          base = 132;
          break;
        }
        case static_cast<int>(RankType::kK): {
          base = 136;
          break;
        }
        default: {
          base = -999;
          break;
          // SpielFatalError("source_.rank_ has an incorrect value");
        }
      }
      return base + source_suit + kActionOffset;
    }
    case static_cast<int>(RankType::kA): {
      base = 140;
      return base + source_suit + kActionOffset;
    }
    case static_cast<int>(RankType::kK): {
      base = 144;
      if (source_suit <= 2) {
        residual = -1;
      } else {
        residual = 0;
      }
      return base + (2 * target_suit) + residual + kActionOffset;
    }
    default: {
      base = (target_suit - 1) * 33 + (target_rank - 2) * 3;
      if (target_suit == source_suit) {
        residual = 1;
      } else if (source_suit <= 2) {
        residual = 2;
      } else {
        residual = 3;
      }
      return base + residual + kActionOffset;
    }
  }
}
References open_spiel::solitaire::Card::GetRank(), open_spiel::solitaire::Card::GetSuit(), open_spiel::solitaire::kA, open_spiel::solitaire::kK, and open_spiel::solitaire::kNone.
GetSource()
Card open_spiel::solitaire::Move::GetSource () const
Definition at line 865 of file solitaire.cc.
{ return source_; }
Referenced by open_spiel::solitaire::SolitaireState::DoApplyAction().
GetTarget()
Card open_spiel::solitaire::Move::GetTarget () const
Definition at line 863 of file solitaire.cc.
{ return target_; }
operator<()
bool open_spiel::solitaire::Move::operator< (const Move & other_move) const
Definition at line 935 of file solitaire.cc.
{
  int index_ = target_.GetIndex() * 100 + source_.GetIndex();
  int other_index =
      other_move.target_.GetIndex() * 100 + other_move.source_.GetIndex();
  return index_ < other_index;
}
References open_spiel::solitaire::Card::GetIndex().
ToString()
std::string open_spiel::solitaire::Move::ToString (bool colored = true) const
Definition at line 928 of file solitaire.cc.
{
  std::string result;
  absl::StrAppend(&result, target_.ToString(colored), " ", kGlyphArrow, " ",
                  source_.ToString(colored));
  return result;
}
References absl::StrAppend(), and open_spiel::solitaire::Card::ToString().
The documentation for this class was generated from the following files:
open_spiel/games/solitaire/solitaire.h
open_spiel/games/solitaire/solitaire.cc