open spiel: open_spiel::skat::Trick Class Reference
open_spiel::skat::Trick Class Reference
#include <skat.h>
Public Member Functions
Trick ()
Trick (Player leader)
int FirstCard () const
Player Leader () const
int CardsPlayed () const
std::vector< int > GetCards () const
void PlayCard (int card)
int PlayerAtPosition (int position) const
int Points () const
std::string ToString () const
Detailed Description
Definition at line 110 of file skat.h.
Constructor & Destructor Documentation
Trick() [1/2]
open_spiel::skat::Trick::Trick () inline
Definition at line 112 of file skat.h.
: Trick{-1} {}
Trick() [2/2]
open_spiel::skat::Trick::Trick (Player leader) inline
Definition at line 113 of file skat.h.
{ leader_ = leader; }
Member Function Documentation
CardsPlayed()
int open_spiel::skat::Trick::CardsPlayed () const inline
Definition at line 117 of file skat.h.
{ return cards_.size(); }
FirstCard()
int open_spiel::skat::Trick::FirstCard () const
Definition at line 198 of file skat.cc.
{
  if (cards_.empty()) {
    return -1;
  } else {
    return cards_[0];
  }
}
GetCards()
std::vector< int > open_spiel::skat::Trick::GetCards () const inline
Definition at line 121 of file skat.h.
{ return cards_; }
Referenced by open_spiel::skat::SkatState::ObservationTensor().
Leader()
Player open_spiel::skat::Trick::Leader () const inline
Definition at line 115 of file skat.h.
{ return leader_; }
Referenced by open_spiel::skat::SkatState::ObservationTensor().
PlayCard()
void open_spiel::skat::Trick::PlayCard (int card)
Definition at line 206 of file skat.cc.
{
  SPIEL_CHECK_LE(cards_.size(), kNumPlayers);
  cards_.push_back(card);
}
References open_spiel::skat::kNumPlayers, and SPIEL_CHECK_LE.
PlayerAtPosition()
int open_spiel::skat::Trick::PlayerAtPosition (int position) const
Definition at line 211 of file skat.cc.
{
  SPIEL_CHECK_GE(position, 0);
  SPIEL_CHECK_LE(position, 2);
  return (leader_ + position) % kNumPlayers;
}
References open_spiel::skat::kNumPlayers, SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Points()
int open_spiel::skat::Trick::Points () const
Definition at line 217 of file skat.cc.
{
  int sum = 0;
  for (auto& card : cards_) {
    sum += CardValue(card);
  }
  return sum;
}
References open_spiel::skat::CardValue().
ToString()
std::string open_spiel::skat::Trick::ToString () const
Definition at line 225 of file skat.cc.
{
  std::string result = absl::StrFormat("Leader: %d, ", leader_);
  for (auto& card : cards_) {
    if (card >= 0 && card < kNumCards)
      absl::StrAppendFormat(&result, "%s ", ToCardSymbol(card));
    else
      absl::StrAppendFormat(&result, "%s ", kEmptyCardSymbol);
  }
  return result;
}
References open_spiel::skat::kEmptyCardSymbol, open_spiel::skat::kNumCards, absl::StrAppendFormat(), absl::StrFormat(), and open_spiel::skat::ToCardSymbol().
The documentation for this class was generated from the following files:
open_spiel/games/skat/skat.h
open_spiel/games/skat/skat.cc