open spiel: absl::string_view Class Reference
absl::string_view Class Reference
#include <string_view.h>
Public Types
using traits_type = std::char_traits<char>
using value_type = char
using pointer = char*
using const_pointer = const char*
using reference = char&
using const_reference = const char&
using const_iterator = const char*
using iterator = const_iterator
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using reverse_iterator = const_reverse_iterator
using size_type = size_t
using difference_type = std::ptrdiff_t
Public Member Functions
constexpr string_view () noexcept
template<typename Allocator >
string_view (const std::basic_string< char, std::char_traits< char >, Allocator > &str ABSL_ATTRIBUTE_LIFETIME_BOUND) noexcept
constexpr string_view (const char *str)
constexpr string_view (const char *data, size_type len)
constexpr const_iterator begin () const noexcept
constexpr const_iterator end () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr const_iterator cend () const noexcept
const_reverse_iterator rbegin () const noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
constexpr size_type size () const noexcept
constexpr size_type length () const noexcept
constexpr size_type max_size () const noexcept
constexpr bool empty () const noexcept
constexpr const_reference operator[] (size_type i) const
constexpr const_reference at (size_type i) const
constexpr const_reference front () const
constexpr const_reference back () const
constexpr const_pointer data () const noexcept
constexpr void remove_prefix (size_type n)
constexpr void remove_suffix (size_type n)
constexpr void swap (string_view &s) noexcept
template<typename A >
operator std::basic_string< char, traits_type, A > () const
size_type copy (char *buf, size_type n, size_type pos=0) const
constexpr string_view substr (size_type pos=0, size_type n=npos) const
constexpr int compare (string_view x) const noexcept
constexpr int compare (size_type pos1, size_type count1, string_view v) const
constexpr int compare (size_type pos1, size_type count1, string_view v, size_type pos2, size_type count2) const
constexpr int compare (const char *s) const
constexpr int compare (size_type pos1, size_type count1, const char *s) const
constexpr int compare (size_type pos1, size_type count1, const char *s, size_type count2) const
size_type find (string_view s, size_type pos=0) const noexcept
size_type find (char c, size_type pos=0) const noexcept
size_type find (const char *s, size_type pos, size_type count) const
size_type find (const char *s, size_type pos=0) const
size_type rfind (string_view s, size_type pos=npos) const noexcept
size_type rfind (char c, size_type pos=npos) const noexcept
size_type rfind (const char *s, size_type pos, size_type count) const
size_type rfind (const char *s, size_type pos=npos) const
size_type find_first_of (string_view s, size_type pos=0) const noexcept
size_type find_first_of (char c, size_type pos=0) const noexcept
size_type find_first_of (const char *s, size_type pos, size_type count) const
size_type find_first_of (const char *s, size_type pos=0) const
size_type find_last_of (string_view s, size_type pos=npos) const noexcept
size_type find_last_of (char c, size_type pos=npos) const noexcept
size_type find_last_of (const char *s, size_type pos, size_type count) const
size_type find_last_of (const char *s, size_type pos=npos) const
size_type find_first_not_of (string_view s, size_type pos=0) const noexcept
size_type find_first_not_of (char c, size_type pos=0) const noexcept
size_type find_first_not_of (const char *s, size_type pos, size_type count) const
size_type find_first_not_of (const char *s, size_type pos=0) const
size_type find_last_not_of (string_view s, size_type pos=npos) const noexcept
size_type find_last_not_of (char c, size_type pos=npos) const noexcept
size_type find_last_not_of (const char *s, size_type pos, size_type count) const
size_type find_last_not_of (const char *s, size_type pos=npos) const
Static Public Attributes
static constexpr size_type npos = static_cast<size_type>(-1)
Detailed Description
Definition at line 161 of file string_view.h.
Member Typedef Documentation
const_iterator
using absl::string_view::const_iterator = const char*
Definition at line 169 of file string_view.h.
const_pointer
using absl::string_view::const_pointer = const char*
Definition at line 166 of file string_view.h.
const_reference
using absl::string_view::const_reference = const char&
Definition at line 168 of file string_view.h.
const_reverse_iterator
using absl::string_view::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 171 of file string_view.h.
difference_type
using absl::string_view::difference_type = std::ptrdiff_t
Definition at line 174 of file string_view.h.
iterator
using absl::string_view::iterator = const_iterator
Definition at line 170 of file string_view.h.
pointer
using absl::string_view::pointer = char*
Definition at line 165 of file string_view.h.
reference
using absl::string_view::reference = char&
Definition at line 167 of file string_view.h.
reverse_iterator
using absl::string_view::reverse_iterator = const_reverse_iterator
Definition at line 172 of file string_view.h.
size_type
using absl::string_view::size_type = size_t
Definition at line 173 of file string_view.h.
traits_type
using absl::string_view::traits_type = std::char_traits<char>
Definition at line 163 of file string_view.h.
value_type
using absl::string_view::value_type = char
Definition at line 164 of file string_view.h.
Constructor & Destructor Documentation
string_view() [1/4]
absl::string_view::string_view () inline constexpr noexcept
Definition at line 179 of file string_view.h.
: ptr_(nullptr), length_(0) {}
Referenced by compare(), compare(), compare(), find(), find(), find_first_not_of(), find_first_not_of(), find_first_of(), find_first_of(), find_last_not_of(), find_last_not_of(), find_last_of(), find_last_of(), rfind(), rfind(), and substr().
string_view() [2/4]
template<typename Allocator > absl::string_view::string_view (const std::basic_string< char, std::char_traits< char >, Allocator > &str ABSL_ATTRIBUTE_LIFETIME_BOUND) inline noexcept
Definition at line 184 of file string_view.h.
      : string_view(str.data(), str.size(), SkipCheckLengthTag{}) {}
string_view() [3/4]
absl::string_view::string_view (const char * str) inline constexpr
Definition at line 197 of file string_view.h.
      : ptr_(str), length_(str ? StrlenInternal(str) : 0) {}
string_view() [4/4]
absl::string_view::string_view (const char * data, size_type len) inline constexpr
Definition at line 201 of file string_view.h.
      : ptr_(data), length_(CheckLengthInternal(len)) {}
Member Function Documentation
at()
const_reference absl::string_view::at (size_type i) const inline constexpr
Definition at line 301 of file string_view.h.
{
    return ABSL_PREDICT_TRUE(i < size())
               ? ptr_[i]
               : ((void)base_internal::ThrowStdOutOfRange(
                      "absl::string_view::at"),
                  ptr_[i]);
  }
References ABSL_PREDICT_TRUE, absl::i, size(), and absl::base_internal::ThrowStdOutOfRange().
back()
const_reference absl::string_view::back () const inline constexpr
Definition at line 319 of file string_view.h.
{
    return ABSL_HARDENING_ASSERT(!empty()), ptr_[size() - 1];
  }
References ABSL_HARDENING_ASSERT, empty(), and size().
begin()
const_iterator absl::string_view::begin () const inline constexpr noexcept
Definition at line 214 of file string_view.h.
{ return ptr_; }
Referenced by absl::strings_internal::BigUnsigned< max_words >::BigUnsigned(), cbegin(), rend(), and absl::substitute_internal::SubstituteAndAppendArray().
cbegin()
const_iterator absl::string_view::cbegin () const inline constexpr noexcept
Definition at line 227 of file string_view.h.
{ return begin(); }
References begin().
cend()
const_iterator absl::string_view::cend () const inline constexpr noexcept
Definition at line 234 of file string_view.h.
{ return end(); }
References end().
compare() [1/6]
int absl::string_view::compare (const char * s) const inline constexpr
Definition at line 430 of file string_view.h.
{ return compare(string_view(s)); }
References compare(), absl::s, and string_view().
Referenced by compare().
compare() [2/6]
int absl::string_view::compare (size_type pos1, size_type count1, const char * s) const inline constexpr
Definition at line 434 of file string_view.h.
{
    return substr(pos1, count1).compare(string_view(s));
  }
References compare(), absl::s, string_view(), and substr().
compare() [3/6]
int absl::string_view::compare (size_type pos1, size_type count1, const char * s, size_type count2) const inline constexpr
Definition at line 440 of file string_view.h.
{
    return substr(pos1, count1).compare(string_view(s, count2));
  }
References compare(), absl::s, string_view(), and substr().
compare() [4/6]
int absl::string_view::compare (size_type pos1, size_type count1, string_view v) const inline constexpr
Definition at line 417 of file string_view.h.
{
    return substr(pos1, count1).compare(v);
  }
References compare(), substr(), and absl::v.
compare() [5/6]
int absl::string_view::compare (size_type pos1, size_type count1, string_view v, size_type pos2, size_type count2) const inline constexpr
Definition at line 423 of file string_view.h.
{
    return substr(pos1, count1).compare(v.substr(pos2, count2));
  }
References compare(), substr(), and absl::v.
compare() [6/6]
int absl::string_view::compare (string_view x) const inline constexpr noexcept
Definition at line 407 of file string_view.h.
{
    return CompareImpl(length_, x.length_,
                       Min(length_, x.length_) == 0
                           ? 0
                           : ABSL_INTERNAL_STRING_VIEW_MEMCMP(
                                 ptr_, x.ptr_, Min(length_, x.length_)));
  }
References ABSL_INTERNAL_STRING_VIEW_MEMCMP, and absl::x.
Referenced by compare(), compare(), compare(), compare(), absl::container_internal::StringBtreeDefaultGreater::operator()(), and absl::container_internal::StringBtreeDefaultLess::operator()().
copy()
size_type absl::string_view::copy (char * buf, size_type n, size_type pos = 0) const inline
Definition at line 375 of file string_view.h.
{
    if (ABSL_PREDICT_FALSE(pos > length_)) {
      base_internal::ThrowStdOutOfRange("absl::string_view::copy");
    }
    size_type rlen = (std::min)(length_ - pos, n);
    if (rlen > 0) {
      const char* start = ptr_ + pos;
      traits_type::copy(buf, start, rlen);
    }
    return rlen;
  }
References ABSL_PREDICT_FALSE, buf, absl::n, and absl::base_internal::ThrowStdOutOfRange().
Referenced by conanfile.AbseilConan::package().
crbegin()
const_reverse_iterator absl::string_view::crbegin () const inline noexcept
Definition at line 257 of file string_view.h.
{ return rbegin(); }
References rbegin().
crend()
const_reverse_iterator absl::string_view::crend () const inline noexcept
Definition at line 264 of file string_view.h.
{ return rend(); }
References rend().
data()
const_pointer absl::string_view::data () const inline constexpr noexcept
Definition at line 330 of file string_view.h.
{ return ptr_; }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), absl::log_internal::AppendTruncated(), absl::Base64Escape(), absl::Base64Escape(), absl::Base64Unescape(), absl::strings_internal::BigUnsigned< max_words >::BigUnsigned(), absl::ABSL_NAMESPACE_BEGIN::CEscapeAndAppendInternal(), absl::Cord::Cord(), absl::ABSL_NAMESPACE_BEGIN::CUnescapeInternal(), absl::AlphaNum::data(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), absl::ExtendCrc32c(), absl::crc_internal::ExtendCrc32cInternal(), absl::ByLength::Find(), absl::strings_internal::JoinAlgorithm(), operator std::basic_string< char, traits_type, A >(), absl::strings_internal::JoinTupleLoop< I, N >::operator()(), absl::Cord::CharIterator::operator*(), absl::operator<<(), absl::operator<<(), absl::Cord::operator=(), absl::ParseDuration(), absl::str_format_internal::ParseFormatString(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample(), absl::flags_internal::SetFlagsHelpMatchSubstr(), absl::flags_internal::SetProgramInvocationName(), absl::strings_internal::SplitIterator< Splitter >::SplitIterator(), absl::Cord::Subcord(), TEST_P(), absl::ABSL_NAMESPACE_BEGIN::ToString(), absl::WebSafeBase64Escape(), absl::WebSafeBase64Escape(), absl::WebSafeBase64Unescape(), and absl::log_internal::WriteToStderr().
empty()
bool absl::string_view::empty () const inline constexpr noexcept
Definition at line 286 of file string_view.h.
{ return length_ == 0; }
Referenced by back(), absl::strings_internal::BigUnsigned< max_words >::BigUnsigned(), absl::strings_internal::CappedDamerauLevenshteinDistance(), absl::cordrep_testing::CreateFlatsFromString(), open_spiel::algorithms::DeserializeCFRInfoStateValues(), open_spiel::algorithms::DeserializeCFRInfoStateValuesTable(), absl::cord_internal::CordRepBtree::Dump(), absl::strings_internal::FindSubstitutions(), absl::flags_internal::FlagsHelp(), front(), absl::ABSL_NAMESPACE_BEGIN::GenericFind(), main(), absl::SkipEmpty::operator()(), absl::SkipWhitespace::operator()(), absl::flags_internal::ParseCommandLineImpl(), absl::ParseDuration(), absl::ParseTime(), open_spiel::crowd_modelling_2d::ProcessStringParam(), and TEST_P().
end()
const_iterator absl::string_view::end () const inline constexpr noexcept
Definition at line 221 of file string_view.h.
{ return ptr_ + length_; }
Referenced by absl::strings_internal::BigUnsigned< max_words >::BigUnsigned(), cend(), rbegin(), and absl::substitute_internal::SubstituteAndAppendArray().
find() [1/4]
string_view::size_type absl::string_view::find (char c, size_type pos = 0) const noexcept
Definition at line 92 of file string_view.cc.
{
  if (empty() || pos >= length_) {
    return npos;
  }
  const char* result =
      static_cast<const char*>(memchr(ptr_ + pos, c, length_ - pos));
  return result != nullptr ? static_cast<size_type>(result - ptr_) : npos;
}
References absl::c.
find() [2/4]
size_type absl::string_view::find (const char * s, size_type pos, size_type count) const inline
Definition at line 460 of file string_view.h.
{
    return find(string_view(s, count), pos);
  }
References find(), absl::s, and string_view().
find() [3/4]
size_type absl::string_view::find (const char * s, size_type pos = 0) const inline
Definition at line 466 of file string_view.h.
{
    return find(string_view(s), pos);
  }
References find(), absl::s, and string_view().
find() [4/4]
string_view::size_type absl::string_view::find (string_view s, size_type pos = 0) const noexcept
Definition at line 81 of file string_view.cc.
{
  if (empty() || pos > length_) {
    if (empty() && pos == 0 && s.empty()) return 0;
    return npos;
  }
  const char* result =
      strings_internal::memmatch(ptr_ + pos, length_ - pos, s.ptr_, s.length_);
  return result ? static_cast<size_type>(result - ptr_) : npos;
}
References absl::strings_internal::memmatch(), and absl::s.
Referenced by open_spiel::universal_poker::logic::CardSet::CardSet(), absl::ByChar::Find(), absl::ByString::Find(), find(), find(), and find_first_of().
find_first_not_of() [1/4]
string_view::size_type absl::string_view::find_first_not_of (char c, size_type pos = 0) const noexcept
Definition at line 154 of file string_view.cc.
{
  if (empty()) return npos;
  for (; pos < length_; ++pos) {
    if (ptr_[pos] != c) {
      return pos;
    }
  }
  return npos;
}
References absl::c.
find_first_not_of() [2/4]
size_type absl::string_view::find_first_not_of (const char * s, size_type pos, size_type count) const inline
Definition at line 557 of file string_view.h.
{
    return find_first_not_of(string_view(s, count), pos);
  }
References find_first_not_of(), absl::s, and string_view().
find_first_not_of() [3/4]
size_type absl::string_view::find_first_not_of (const char * s, size_type pos = 0) const inline
Definition at line 564 of file string_view.h.
{
    return find_first_not_of(string_view(s), pos);
  }
References find_first_not_of(), absl::s, and string_view().
find_first_not_of() [4/4]
string_view::size_type absl::string_view::find_first_not_of (string_view s, size_type pos = 0) const noexcept
Definition at line 140 of file string_view.cc.
{
  if (empty()) return npos;
  // Avoid the cost of LookupTable() for a single-character search.
  if (s.length_ == 1) return find_first_not_of(s.ptr_[0], pos);
  LookupTable tbl(s);
  for (size_type i = pos; i < length_; ++i) {
    if (!tbl[ptr_[i]]) {
      return i;
    }
  }
  return npos;
}
References absl::i, and absl::s.
Referenced by find_first_not_of(), and find_first_not_of().
find_first_of() [1/4]
size_type absl::string_view::find_first_of (char c, size_type pos = 0) const inline noexcept
Definition at line 502 of file string_view.h.
{
    return find(c, pos);
  }
References absl::c, and find().
find_first_of() [2/4]
size_type absl::string_view::find_first_of (const char * s, size_type pos, size_type count) const inline
Definition at line 508 of file string_view.h.
{
    return find_first_of(string_view(s, count), pos);
  }
References find_first_of(), absl::s, and string_view().
find_first_of() [3/4]
size_type absl::string_view::find_first_of (const char * s, size_type pos = 0) const inline
Definition at line 515 of file string_view.h.
{
    return find_first_of(string_view(s), pos);
  }
References find_first_of(), absl::s, and string_view().
find_first_of() [4/4]
string_view::size_type absl::string_view::find_first_of (string_view s, size_type pos = 0) const noexcept
Definition at line 124 of file string_view.cc.
{
  if (empty() || s.empty()) {
    return npos;
  }
  // Avoid the cost of LookupTable() for a single-character search.
  if (s.length_ == 1) return find_first_of(s.ptr_[0], pos);
  LookupTable tbl(s);
  for (size_type i = pos; i < length_; ++i) {
    if (tbl[ptr_[i]]) {
      return i;
    }
  }
  return npos;
}
References absl::i, and absl::s.
Referenced by find_first_of(), and find_first_of().
find_last_not_of() [1/4]
string_view::size_type absl::string_view::find_last_not_of (char c, size_type pos = npos) const noexcept
Definition at line 197 of file string_view.cc.
{
  if (empty()) return npos;
  size_type i = std::min(pos, length_ - 1);
  for (;; --i) {
    if (ptr_[i] != c) {
      return i;
    }
    if (i == 0) break;
  }
  return npos;
}
References absl::c, and absl::i.
find_last_not_of() [2/4]
size_type absl::string_view::find_last_not_of (const char * s, size_type pos, size_type count) const inline
Definition at line 582 of file string_view.h.
{
    return find_last_not_of(string_view(s, count), pos);
  }
References find_last_not_of(), absl::s, and string_view().
find_last_not_of() [3/4]
size_type absl::string_view::find_last_not_of (const char * s, size_type pos = npos) const inline
Definition at line 589 of file string_view.h.
{
    return find_last_not_of(string_view(s), pos);
  }
References find_last_not_of(), absl::s, and string_view().
find_last_not_of() [4/4]
string_view::size_type absl::string_view::find_last_not_of (string_view s, size_type pos = npos) const noexcept
Definition at line 180 of file string_view.cc.
{
  if (empty()) return npos;
  size_type i = std::min(pos, length_ - 1);
  if (s.empty()) return i;
  // Avoid the cost of LookupTable() for a single-character search.
  if (s.length_ == 1) return find_last_not_of(s.ptr_[0], pos);
  LookupTable tbl(s);
  for (;; --i) {
    if (!tbl[ptr_[i]]) {
      return i;
    }
    if (i == 0) break;
  }
  return npos;
}
References absl::i, and absl::s.
Referenced by find_last_not_of(), and find_last_not_of().
find_last_of() [1/4]
size_type absl::string_view::find_last_of (char c, size_type pos = npos) const inline noexcept
Definition at line 528 of file string_view.h.
{
    return rfind(c, pos);
  }
References absl::c, and rfind().
find_last_of() [2/4]
size_type absl::string_view::find_last_of (const char * s, size_type pos, size_type count) const inline
Definition at line 534 of file string_view.h.
{
    return find_last_of(string_view(s, count), pos);
  }
References find_last_of(), absl::s, and string_view().
find_last_of() [3/4]
size_type absl::string_view::find_last_of (const char * s, size_type pos = npos) const inline
Definition at line 540 of file string_view.h.
{
    return find_last_of(string_view(s), pos);
  }
References find_last_of(), absl::s, and string_view().
find_last_of() [4/4]
string_view::size_type absl::string_view::find_last_of (string_view s, size_type pos = npos) const noexcept
Definition at line 165 of file string_view.cc.
{
  if (empty() || s.empty()) return npos;
  // Avoid the cost of LookupTable() for a single-character search.
  if (s.length_ == 1) return find_last_of(s.ptr_[0], pos);
  LookupTable tbl(s);
  for (size_type i = std::min(pos, length_ - 1);; --i) {
    if (tbl[ptr_[i]]) {
      return i;
    }
    if (i == 0) break;
  }
  return npos;
}
References absl::i, and absl::s.
Referenced by absl::flags_internal::Basename(), find_last_of(), find_last_of(), and absl::flags_internal::Package().
front()
const_reference absl::string_view::front () const inline constexpr
Definition at line 312 of file string_view.h.
{
    return ABSL_HARDENING_ASSERT(!empty()), ptr_[0];
  }
References ABSL_HARDENING_ASSERT, and empty().
length()
size_type absl::string_view::length () const inline constexpr noexcept
Definition at line 276 of file string_view.h.
{ return size(); }
References size().
Referenced by absl::ByLength::Find(), absl::ABSL_NAMESPACE_BEGIN::LiteralPolicy::Length(), absl::cord_internal::CordRepBtreeReader::Seek(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), and absl::ABSL_NAMESPACE_BEGIN::TEST_P().
max_size()
size_type absl::string_view::max_size () const inline constexpr noexcept
Definition at line 281 of file string_view.h.
{ return kMaxSize; }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
operator std::basic_string< char, traits_type, A >()
template<typename A > absl::string_view::operator std::basic_string< char, traits_type, A > () const inline explicit
Definition at line 366 of file string_view.h.
{
    if (!data()) return {};
    return std::basic_string<char, traits_type, A>(data(), size());
  }
References data(), and size().
operator[]()
const_reference absl::string_view::operator[] (size_type i) const inline constexpr
Definition at line 292 of file string_view.h.
{
    return ABSL_HARDENING_ASSERT(i < size()), ptr_[i];
  }
References ABSL_HARDENING_ASSERT, absl::i, and size().
rbegin()
const_reverse_iterator absl::string_view::rbegin () const inline noexcept
Definition at line 240 of file string_view.h.
{
    return const_reverse_iterator(end());
  }
References end().
Referenced by crbegin().
remove_prefix()
void absl::string_view::remove_prefix (size_type n) inline constexpr
Definition at line 338 of file string_view.h.
{
    ABSL_HARDENING_ASSERT(n <= length_);
    ptr_ += n;
    length_ -= n;
  }
References ABSL_HARDENING_ASSERT, and absl::n.
Referenced by absl::ParseTime(), absl::cord_internal::CordRepRingReader::Seek(), and absl::StripPrefix().
remove_suffix()
void absl::string_view::remove_suffix (size_type n) inline constexpr
Definition at line 348 of file string_view.h.
{
    ABSL_HARDENING_ASSERT(n <= length_);
    length_ -= n;
  }
References ABSL_HARDENING_ASSERT, and absl::n.
Referenced by absl::StripSuffix(), and absl::log_internal::TextPrefix().
rend()
const_reverse_iterator absl::string_view::rend () const inline noexcept
Definition at line 249 of file string_view.h.
{
    return const_reverse_iterator(begin());
  }
References begin().
Referenced by crend().
rfind() [1/4]
string_view::size_type absl::string_view::rfind (char c, size_type pos = npos) const noexcept
Definition at line 111 of file string_view.cc.
{
  // Note: memrchr() is not available on Windows.
  if (empty()) return npos;
  for (size_type i = std::min(pos, length_ - 1);; --i) {
    if (ptr_[i] == c) {
      return i;
    }
    if (i == 0) break;
  }
  return npos;
}
References absl::c, and absl::i.
rfind() [2/4]
size_type absl::string_view::rfind (const char * s, size_type pos, size_type count) const inline
Definition at line 483 of file string_view.h.
{
    return rfind(string_view(s, count), pos);
  }
References rfind(), absl::s, and string_view().
rfind() [3/4]
size_type absl::string_view::rfind (const char * s, size_type pos = npos) const inline
Definition at line 489 of file string_view.h.
{
    return rfind(string_view(s), pos);
  }
References rfind(), absl::s, and string_view().
rfind() [4/4]
string_view::size_type absl::string_view::rfind (string_view s, size_type pos = npos) const noexcept
Definition at line 101 of file string_view.cc.
{
  if (length_ < s.length_) return npos;
  if (s.empty()) return std::min(length_, pos);
  const char* last = ptr_ + std::min(length_ - s.length_, pos) + s.length_;
  const char* result = std::find_end(ptr_, last, s.ptr_, s.ptr_ + s.length_);
  return result != last ? static_cast<size_type>(result - ptr_) : npos;
}
References absl::s.
Referenced by find_last_of(), rfind(), and rfind().
size()
size_type absl::string_view::size () const inline constexpr noexcept
Definition at line 271 of file string_view.h.
{ return length_; }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), absl::Cord::Append(), absl::log_internal::AppendTruncated(), at(), back(), absl::Base64Escape(), absl::Base64Escape(), absl::Base64Unescape(), absl::strings_internal::BigUnsigned< max_words >::BigUnsigned(), absl::strings_internal::CappedDamerauLevenshteinDistance(), absl::ABSL_NAMESPACE_BEGIN::CEscapeAndAppendInternal(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), absl::ConsumePrefix(), absl::ConsumeSuffix(), absl::Cord::Cord(), absl::ABSL_NAMESPACE_BEGIN::CUnescapeInternal(), absl::ABSL_NAMESPACE_BEGIN::CUnescapeInternal(), open_spiel::BinaryCompress::Decompress(), open_spiel::NoCompress::Decompress(), open_spiel::Observation::Decompress(), open_spiel::PyState::Deserialize(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), absl::Cord::EndsWith(), absl::ExtendCrc32c(), absl::crc_internal::ExtendCrc32cInternal(), absl::time_internal::cctz::FixedOffsetToAbbr(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), absl::flags_internal::GetMisspellingHints(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), absl::strings_internal::JoinAlgorithm(), length(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), absl::strings_internal::ViableSubstitution::OccursBefore(), operator std::basic_string< char, traits_type, A >(), absl::strings_internal::JoinTupleLoop< I, N >::operator()(), absl::strings_internal::SplitIterator< Splitter >::operator++(), absl::operator<<(), absl::operator<<(), absl::Cord::operator=(), operator[](), absl::ParseDuration(), absl::str_format_internal::ParseFormatString(), absl::Cord::Prepend(), absl::str_format_internal::FormatSinkImpl::PutPaddedString(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), absl::flags_internal::SetFlagsHelpMatchSubstr(), absl::flags_internal::SetProgramInvocationName(), absl::AlphaNum::size(), absl::strings_internal::SplitIterator< Splitter >::SplitIterator(), absl::Cord::StartsWith(), absl::StripSuffix(), absl::Cord::Subcord(), absl::substitute_internal::SubstituteAndAppendArray(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::log_internal::TextPrefix(), absl::ABSL_NAMESPACE_BEGIN::ToString(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), open_spiel.python.utils.lru_cache.CacheInfo::usage(), absl::WebSafeBase64Escape(), absl::WebSafeBase64Escape(), absl::WebSafeBase64Unescape(), and absl::log_internal::WriteToStderr().
substr()
string_view absl::string_view::substr (size_type pos = 0, size_type n = npos) const inline constexpr
Definition at line 393 of file string_view.h.
{
    return ABSL_PREDICT_FALSE(pos > length_)
               ? (base_internal::ThrowStdOutOfRange(
                      "absl::string_view::substr"),
                  string_view())
               : string_view(ptr_ + pos, Min(n, length_ - pos));
  }
References ABSL_PREDICT_FALSE, absl::n, string_view(), and absl::base_internal::ThrowStdOutOfRange().
Referenced by ABSL_FLAG(), absl::log_internal::AppendTruncated(), absl::flags_internal::Basename(), compare(), compare(), compare(), compare(), absl::ByLength::Find(), absl::cord_internal::CordRepBtree::IsFlat(), absl::cord_internal::CordRepRing::IsFlat(), absl::strings_internal::SplitIterator< Splitter >::operator++(), absl::flags_internal::Package(), absl::cord_internal::CordRepBtreeReader::Read(), absl::cord_internal::CordRepBtreeReader::Seek(), absl::cord_internal::CordRepBtreeReader::Skip(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), absl::ABSL_NAMESPACE_BEGIN::TEST_P(), and TEST_P().
swap()
void absl::string_view::swap (string_view & s) inline constexpr noexcept
Definition at line 356 of file string_view.h.
{
    auto t = *this;
    *this = s;
    s = t;
  }
References absl::s.
Member Data Documentation
npos
size_type absl::string_view::npos = static_cast<size_type>(-1) static constexpr
Definition at line 176 of file string_view.h.
Referenced by absl::flags_internal::Basename(), absl::ByChar::Find(), absl::ByString::Find(), absl::ABSL_NAMESPACE_BEGIN::GenericFind(), and absl::flags_internal::Package().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/string_view.h
open_spiel/abseil-cpp/absl/strings/string_view.cc