open spiel: open_spiel::algorithms::CorrDevBuilder Class Reference
open_spiel::algorithms::CorrDevBuilder Class Reference
#include <corr_dev_builder.h>
Public Member Functions
CorrDevBuilder (int seed=0)
void AddDeterminsticJointPolicy (const TabularPolicy &policy, double weight=1.0)
void AddSampledJointPolicy (const TabularPolicy &policy, int num_samples, double weight=1.0)
void AddMixedJointPolicy (const TabularPolicy &policy, double weight=1.0)
CorrelationDevice GetCorrelationDevice () const
Detailed Description
Definition at line 39 of file corr_dev_builder.h.
Constructor & Destructor Documentation
CorrDevBuilder()
open_spiel::algorithms::CorrDevBuilder::CorrDevBuilder (int seed = 0)
Definition at line 23 of file corr_dev_builder.cc.
: rng_(seed), total_weight_(0.0) {}
Member Function Documentation
AddDeterminsticJointPolicy()
void open_spiel::algorithms::CorrDevBuilder::AddDeterminsticJointPolicy (const TabularPolicy & policy, double weight = 1.0)
Definition at line 25 of file corr_dev_builder.cc.
{
  std::string key = policy.ToStringSorted();
  auto iter = policy_weights_.find(key);
  if (iter == policy_weights_.end()) {
    policy_weights_[key] = weight;
    policy_map_[key] = policy;
  } else {
    iter->second += weight;
  }
  total_weight_ += weight;
}
References key.
Referenced by AddMixedJointPolicy(), AddSampledJointPolicy(), and open_spiel::init_pyspiel_algorithms_corr_dist().
AddMixedJointPolicy()
void open_spiel::algorithms::CorrDevBuilder::AddMixedJointPolicy (const TabularPolicy & policy, double weight = 1.0)
Definition at line 51 of file corr_dev_builder.cc.
{
  std::vector<int> action_indices(policy.PolicyTable().size(), 0);
  bool done = false;
  double total_prob = 0.0;
  while (!done) {
    // Construct the joint policy and add it.
    TabularPolicy deterministic_policy;
    double prob = 1.0;
    int info_state_idx = 0;
    for (const auto& iter : policy.PolicyTable()) {
      Action action = iter.second[action_indices[info_state_idx]].first;
      prob *= GetProb(iter.second, action);
      if (prob == 0.0) {
        break;
      }
      deterministic_policy.SetStatePolicy(
          iter.first, ToDeterministicPolicy(iter.second, action));
      info_state_idx++;
    }
    SPIEL_CHECK_PROB(prob);
    if (prob > 0.0) {
      AddDeterminsticJointPolicy(deterministic_policy, prob * weight);
      total_prob += prob;
    }
    // Now, try to move to the next joint policy.
    info_state_idx = 0;
    done = true;
    for (const auto& iter : policy.PolicyTable()) {
      if (++action_indices[info_state_idx] < iter.second.size()) {
        done = false;
        break;
      } else {
        action_indices[info_state_idx] = 0;
      }
      info_state_idx++;
    }
  }
  SPIEL_CHECK_TRUE(Near(total_prob, 1.0, 1e-10));
}
References action, AddDeterminsticJointPolicy(), open_spiel::GetProb(), open_spiel::Near(), open_spiel::TabularPolicy::SetStatePolicy(), SPIEL_CHECK_PROB, SPIEL_CHECK_TRUE, and open_spiel::ToDeterministicPolicy().
Referenced by open_spiel::algorithms::DeterminizeCorrDev(), and open_spiel::init_pyspiel_algorithms_corr_dist().
AddSampledJointPolicy()
void open_spiel::algorithms::CorrDevBuilder::AddSampledJointPolicy (const TabularPolicy & policy, int num_samples, double weight = 1.0)
Definition at line 38 of file corr_dev_builder.cc.
{
  for (int sample = 0; sample < num_samples; ++sample) {
    TabularPolicy sampled_policy;
    for (const auto& iter : policy.PolicyTable()) {
      Action sampled_action = SampleAction(iter.second, rng_).first;
      sampled_policy.SetStatePolicy(
          iter.first, ToDeterministicPolicy(iter.second, sampled_action));
    }
    AddDeterminsticJointPolicy(sampled_policy, 1.0 / num_samples * weight);
  }
}
References AddDeterminsticJointPolicy(), open_spiel::SampleAction(), open_spiel::TabularPolicy::SetStatePolicy(), and open_spiel::ToDeterministicPolicy().
Referenced by open_spiel::init_pyspiel_algorithms_corr_dist(), and open_spiel::algorithms::SampledDeterminizeCorrDev().
GetCorrelationDevice()
CorrelationDevice open_spiel::algorithms::CorrDevBuilder::GetCorrelationDevice () const
Definition at line 96 of file corr_dev_builder.cc.
{
  SPIEL_CHECK_GT(total_weight_, 0);
  CorrelationDevice corr_dev;
  double sum_weight = 0;
  for (const auto& key_and_policy : policy_map_) {
    double weight = policy_weights_.at(key_and_policy.first);
    sum_weight += weight;
    corr_dev.push_back({weight / total_weight_, key_and_policy.second});
  }
  SPIEL_CHECK_TRUE(Near(sum_weight, total_weight_));
  return corr_dev;
}
References open_spiel::Near(), SPIEL_CHECK_GT, and SPIEL_CHECK_TRUE.
Referenced by open_spiel::algorithms::DeterminizeCorrDev(), open_spiel::init_pyspiel_algorithms_corr_dist(), and open_spiel::algorithms::SampledDeterminizeCorrDev().
The documentation for this class was generated from the following files:
open_spiel/algorithms/corr_dev_builder.h
open_spiel/algorithms/corr_dev_builder.cc