open spiel: open_spiel::tic_tac_toe::TicTacToeGame Class Reference
open_spiel::tic_tac_toe::TicTacToeGame Class Reference
#include <tic_tac_toe.h>
Public Member Functions
TicTacToeGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
std::string ActionToString (Player player, Action action_id) const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 95 of file tic_tac_toe.h.
Constructor & Destructor Documentation
TicTacToeGame()
open_spiel::tic_tac_toe::TicTacToeGame::TicTacToeGame (const GameParameters & params) explicit
Definition at line 202 of file tic_tac_toe.cc.
    : Game(kGameType, params) {}
Member Function Documentation
ActionToString()
std::string open_spiel::tic_tac_toe::TicTacToeGame::ActionToString (Player player, Action action_id) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 196 of file tic_tac_toe.cc.
{
  return absl::StrCat(StateToString(PlayerToState(player)), "(",
                      action_id / kNumCols, ",", action_id % kNumCols, ")");
}
References player, open_spiel::tic_tac_toe::PlayerToState(), open_spiel::tic_tac_toe::StateToString(), and absl::StrCat().
MaxGameLength()
int open_spiel::tic_tac_toe::TicTacToeGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 109 of file tic_tac_toe.h.
{ return kNumCells; }
References open_spiel::tic_tac_toe::kNumCells.
MaxUtility()
double open_spiel::tic_tac_toe::TicTacToeGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 105 of file tic_tac_toe.h.
{ return 1; }
MinUtility()
double open_spiel::tic_tac_toe::TicTacToeGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 103 of file tic_tac_toe.h.
{ return -1; }
NewInitialState()
std::unique_ptr< State > open_spiel::tic_tac_toe::TicTacToeGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 99 of file tic_tac_toe.h.
{
    return std::unique_ptr<State>(new TicTacToeState(shared_from_this()));
  }
Referenced by open_spiel::ultimate_tic_tac_toe::UltimateTTTState::UltimateTTTState().
NumDistinctActions()
int open_spiel::tic_tac_toe::TicTacToeGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 98 of file tic_tac_toe.h.
{ return kNumCells; }
References open_spiel::tic_tac_toe::kNumCells.
NumPlayers()
int open_spiel::tic_tac_toe::TicTacToeGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 102 of file tic_tac_toe.h.
{ return kNumPlayers; }
References open_spiel::tic_tac_toe::kNumPlayers.
ObservationTensorShape()
std::vector< int > open_spiel::tic_tac_toe::TicTacToeGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 106 of file tic_tac_toe.h.
{
    return {kCellStates, kNumRows, kNumCols};
  }
References open_spiel::tic_tac_toe::kCellStates, and open_spiel::tic_tac_toe::kNumRows.
UtilitySum()
absl::optional< double > open_spiel::tic_tac_toe::TicTacToeGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 104 of file tic_tac_toe.h.
{ return 0; }
The documentation for this class was generated from the following files:
open_spiel/games/tic_tac_toe/tic_tac_toe.h
open_spiel/games/tic_tac_toe/tic_tac_toe.cc