open spiel: open_spiel::algorithms::CFRSolverBase Class Reference
open_spiel::algorithms::CFRSolverBase Class Reference
#include <cfr.h>
Public Member Functions
CFRSolverBase (const Game &game, bool alternating_updates, bool linear_averaging, bool regret_matching_plus, bool random_initial_regrets=false, int seed=0)
CFRSolverBase (std::shared_ptr< const Game > game, bool alternating_updates, bool linear_averaging, bool regret_matching_plus, int iteration, bool random_initial_regrets=false, int seed=0)
virtual ~CFRSolverBase ()=default
virtual void EvaluateAndUpdatePolicy ()
std::shared_ptr< Policy > AveragePolicy () const
TabularPolicy TabularAveragePolicy () const
std::shared_ptr< Policy > CurrentPolicy () const
TabularPolicy TabularCurrentPolicy () const
CFRInfoStateValuesTable & InfoStateValuesTable ()
std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const
Protected Member Functions
std::vector< double > ComputeCounterFactualRegret (const State &state, const absl::optional< int > &alternating_player, const std::vector< double > &reach_probabilities, const std::vector< const Policy * > *policy_overrides)
void ApplyRegretMatching ()
virtual std::string SerializeThisType () const
Protected Attributes
std::shared_ptr< const Game > game_
int iteration_ = 0
CFRInfoStateValuesTable info_states_
const std::unique_ptr< State > root_state_
const std::vector< double > root_reach_probs_
Detailed Description
Definition at line 188 of file cfr.h.
Constructor & Destructor Documentation
CFRSolverBase() [1/2]
open_spiel::algorithms::CFRSolverBase::CFRSolverBase (const Game & game, bool alternating_updates, bool linear_averaging, bool regret_matching_plus, bool random_initial_regrets = false, int seed = 0)
Definition at line 191 of file cfr.cc.
    : game_(game.shared_from_this()),
      root_state_(game.NewInitialState()),
      root_reach_probs_(game_->NumPlayers() + 1, 1.0),
      regret_matching_plus_(regret_matching_plus),
      alternating_updates_(alternating_updates),
      linear_averaging_(linear_averaging),
      random_initial_regrets_(random_initial_regrets),
      chance_player_(game.NumPlayers()),
      rng_(seed) {
  if (game_->GetType().dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError(
        "CFR requires sequential games. If you're trying to run it "
        "on a simultaneous (or normal-form) game, please first transform it "
        "using turn_based_simultaneous_game.");
  }
  InitializeInfostateNodes(*root_state_);
}
References game_, open_spiel::GameType::kSequential, root_state_, and open_spiel::SpielFatalError().
CFRSolverBase() [2/2]
open_spiel::algorithms::CFRSolverBase::CFRSolverBase (std::shared_ptr< const Game > game, bool alternating_updates, bool linear_averaging, bool regret_matching_plus, int iteration, bool random_initial_regrets = false, int seed = 0)
Definition at line 212 of file cfr.cc.
    : game_(game),
      iteration_(iteration),
      root_state_(game->NewInitialState()),
      root_reach_probs_(game_->NumPlayers() + 1, 1.0),
      regret_matching_plus_(regret_matching_plus),
      alternating_updates_(alternating_updates),
      linear_averaging_(linear_averaging),
      random_initial_regrets_(random_initial_regrets),
      chance_player_(game->NumPlayers()),
      rng_(seed) {
  if (game_->GetType().dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError(
        "CFR requires sequential games. If you're trying to run it "
        "on a simultaneous (or normal-form) game, please first transform it "
        "using turn_based_simultaneous_game.");
  }
}
References game_, open_spiel::GameType::kSequential, and open_spiel::SpielFatalError().
~CFRSolverBase()
virtual open_spiel::algorithms::CFRSolverBase::~CFRSolverBase () virtual default
Member Function Documentation
ApplyRegretMatching()
void open_spiel::algorithms::CFRSolverBase::ApplyRegretMatching () protected
Definition at line 693 of file cfr.cc.
{
  for (auto& entry : info_states_) {
    entry.second.ApplyRegretMatching();
  }
}
References info_states_.
Referenced by open_spiel::algorithms::CFRBRSolver::EvaluateAndUpdatePolicy(), and EvaluateAndUpdatePolicy().
AveragePolicy()
std::shared_ptr< Policy > open_spiel::algorithms::CFRSolverBase::AveragePolicy () const inline
Definition at line 205 of file cfr.h.
{
    return std::make_shared<CFRAveragePolicy>(info_states_, nullptr);
  }
References info_states_.
Referenced by define_julia_module(), open_spiel::init_pyspiel_policy(), and main().
ComputeCounterFactualRegret()
std::vector< double > open_spiel::algorithms::CFRSolverBase::ComputeCounterFactualRegret (const State & state, const absl::optional< int > & alternating_player, const std::vector< double > & reach_probabilities, const std::vector< const Policy * > * policy_overrides) protected
Definition at line 331 of file cfr.cc.
{
  if (state.IsTerminal()) {
    return state.Returns();
  }
  if (state.IsChanceNode()) {
    ActionsAndProbs actions_and_probs = state.ChanceOutcomes();
    std::vector<double> dist(actions_and_probs.size(), 0);
    std::vector<Action> outcomes(actions_and_probs.size(), 0);
    for (int oidx = 0; oidx < actions_and_probs.size(); ++oidx) {
      outcomes[oidx] = actions_and_probs[oidx].first;
      dist[oidx] = actions_and_probs[oidx].second;
    }
    return ComputeCounterFactualRegretForActionProbs(
        state, alternating_player, reach_probabilities, chance_player_, dist,
        outcomes, nullptr, policy_overrides);
  }
  if (AllPlayersHaveZeroReachProb(reach_probabilities)) {
    // The value returned is not used: if the reach probability for all players
    // is 0, then the last taken action has probability 0, so the
    // returned value is not impacting the parent node value.
    return std::vector<double>(game_->NumPlayers(), 0.0);
  }
  int current_player = state.CurrentPlayer();
  std::string info_state = state.InformationStateString();
  std::vector<Action> legal_actions = state.LegalActions(current_player);
  // Load current policy.
  std::vector<double> info_state_policy;
  if (policy_overrides && policy_overrides->at(current_player)) {
    GetInfoStatePolicyFromPolicy(&info_state_policy, legal_actions,
                                 policy_overrides->at(current_player),
                                 info_state);
  } else {
    info_state_policy = GetPolicy(info_state, legal_actions);
  }
  std::vector<double> child_utilities;
  child_utilities.reserve(legal_actions.size());
  const std::vector<double> state_value =
      ComputeCounterFactualRegretForActionProbs(
          state, alternating_player, reach_probabilities, current_player,
          info_state_policy, legal_actions, &child_utilities, policy_overrides);
  // Perform regret and average strategy updates.
  if (!alternating_player || *alternating_player == current_player) {
    CFRInfoStateValues is_vals = info_states_[info_state];
    SPIEL_CHECK_FALSE(is_vals.empty());
    const double self_reach_prob = reach_probabilities[current_player];
    const double cfr_reach_prob =
        CounterFactualReachProb(reach_probabilities, current_player);
    for (int aidx = 0; aidx < legal_actions.size(); ++aidx) {
      // Update regrets.
      double cfr_regret = cfr_reach_prob *
                          (child_utilities[aidx] - state_value[current_player]);
      is_vals.cumulative_regrets[aidx] += cfr_regret;
      // Update average policy.
      if (linear_averaging_) {
        is_vals.cumulative_policy[aidx] +=
            iteration_ * self_reach_prob * info_state_policy[aidx];
      } else {
        is_vals.cumulative_policy[aidx] +=
            self_reach_prob * info_state_policy[aidx];
      }
    }
    info_states_[info_state] = is_vals;
  }
  return state_value;
}
References actions_and_probs, open_spiel::algorithms::CFRInfoStateValues::cumulative_policy, open_spiel::algorithms::CFRInfoStateValues::cumulative_regrets, open_spiel::algorithms::CFRInfoStateValues::empty(), game_, info_states_, iteration_, SPIEL_CHECK_FALSE, and state.
Referenced by open_spiel::algorithms::CFRBRSolver::EvaluateAndUpdatePolicy(), and EvaluateAndUpdatePolicy().
CurrentPolicy()
std::shared_ptr< Policy > open_spiel::algorithms::CFRSolverBase::CurrentPolicy () const inline
Definition at line 217 of file cfr.h.
{
    return std::make_shared<CFRCurrentPolicy>(info_states_, nullptr);
  }
References info_states_.
Referenced by define_julia_module(), open_spiel::algorithms::CFRBRSolver::EvaluateAndUpdatePolicy(), and open_spiel::init_pyspiel_policy().
EvaluateAndUpdatePolicy()
void open_spiel::algorithms::CFRSolverBase::EvaluateAndUpdatePolicy () virtual
Reimplemented in open_spiel::algorithms::CFRBRSolver.
Definition at line 263 of file cfr.cc.
{
  ++iteration_;
  if (alternating_updates_) {
    for (int player = 0; player < game_->NumPlayers(); player++) {
      ComputeCounterFactualRegret(*root_state_, player, root_reach_probs_,
                                  nullptr);
      if (regret_matching_plus_) {
        ApplyRegretMatchingPlusReset();
      }
      ApplyRegretMatching();
    }
  } else {
    ComputeCounterFactualRegret(*root_state_, absl::nullopt, root_reach_probs_,
                                nullptr);
    if (regret_matching_plus_) {
      ApplyRegretMatchingPlusReset();
    }
    ApplyRegretMatching();
  }
}
References ApplyRegretMatching(), ComputeCounterFactualRegret(), game_, iteration_, player, root_reach_probs_, and root_state_.
Referenced by define_julia_module(), open_spiel::init_pyspiel_policy(), and main().
InfoStateValuesTable()
CFRInfoStateValuesTable & open_spiel::algorithms::CFRSolverBase::InfoStateValuesTable () inline
Definition at line 226 of file cfr.h.
{ return info_states_; }
References info_states_.
Serialize()
std::string open_spiel::algorithms::CFRSolverBase::Serialize (int double_precision = -1, std::string delimiter = "<~>") const
Definition at line 284 of file cfr.cc.
{
  SPIEL_CHECK_GE(double_precision, -1);
  std::string str = "";
  // Meta section
  absl::StrAppend(&str,
                  "# Automatically generated by OpenSpiel "
                  "CFRSolverBase::Serialize\n");
  absl::StrAppend(&str, kSerializeMetaSectionHeader, "\n");
  absl::StrAppend(&str, "Version: ", kSerializationVersion, "\n");
  absl::StrAppend(&str, "\n");
  // Game section
  absl::StrAppend(&str, kSerializeGameSectionHeader, "\n");
  absl::StrAppend(&str, game_->Serialize(), "\n");
  // Internal solver state section
  absl::StrAppend(&str, kSerializeSolverTypeSectionHeader, "\n");
  absl::StrAppend(&str, SerializeThisType(), "\n");
  absl::StrAppend(&str, kSerializeSolverSpecificStateSectionHeader, "\n");
  absl::StrAppend(&str, iteration_, "\n");
  absl::StrAppend(&str, kSerializeSolverValuesTableSectionHeader, "\n");
  SerializeCFRInfoStateValuesTable(info_states_, &str, double_precision,
                                   delimiter);
  return str;
}
References game_, info_states_, iteration_, open_spiel::algorithms::kSerializationVersion, open_spiel::algorithms::kSerializeGameSectionHeader, open_spiel::algorithms::kSerializeMetaSectionHeader, open_spiel::algorithms::kSerializeSolverSpecificStateSectionHeader, open_spiel::algorithms::kSerializeSolverTypeSectionHeader, open_spiel::algorithms::kSerializeSolverValuesTableSectionHeader, open_spiel::algorithms::SerializeCFRInfoStateValuesTable(), SerializeThisType(), SPIEL_CHECK_GE, and absl::StrAppend().
Referenced by open_spiel::init_pyspiel_policy().
SerializeThisType()
virtual std::string open_spiel::algorithms::CFRSolverBase::SerializeThisType () const inline protected virtual
Reimplemented in open_spiel::algorithms::CFRBRSolver, open_spiel::algorithms::CFRPlusSolver, and open_spiel::algorithms::CFRSolver.
Definition at line 261 of file cfr.h.
{
    SpielFatalError("Serialization of the base class is not supported.");
  }
References open_spiel::SpielFatalError().
Referenced by Serialize().
TabularAveragePolicy()
TabularPolicy open_spiel::algorithms::CFRSolverBase::TabularAveragePolicy () const inline
Definition at line 209 of file cfr.h.
{
    CFRAveragePolicy policy(info_states_, nullptr);
    return policy.AsTabular();
  }
References info_states_.
Referenced by open_spiel::init_pyspiel_policy(), and main().
TabularCurrentPolicy()
TabularPolicy open_spiel::algorithms::CFRSolverBase::TabularCurrentPolicy () const inline
Definition at line 221 of file cfr.h.
{
    CFRCurrentPolicy policy(info_states_, nullptr);
    return policy.AsTabular();
  }
References info_states_.
Referenced by open_spiel::init_pyspiel_policy().
Member Data Documentation
game_
std::shared_ptr<const Game> open_spiel::algorithms::CFRSolverBase::game_ protected
Definition at line 234 of file cfr.h.
Referenced by CFRSolverBase(), CFRSolverBase(), ComputeCounterFactualRegret(), open_spiel::algorithms::CFRBRSolver::EvaluateAndUpdatePolicy(), EvaluateAndUpdatePolicy(), and Serialize().
info_states_
CFRInfoStateValuesTable open_spiel::algorithms::CFRSolverBase::info_states_ protected
Definition at line 238 of file cfr.h.
Referenced by ApplyRegretMatching(), AveragePolicy(), ComputeCounterFactualRegret(), CurrentPolicy(), InfoStateValuesTable(), Serialize(), TabularAveragePolicy(), and TabularCurrentPolicy().
iteration_
int open_spiel::algorithms::CFRSolverBase::iteration_ = 0 protected
Definition at line 237 of file cfr.h.
Referenced by ComputeCounterFactualRegret(), open_spiel::algorithms::CFRBRSolver::EvaluateAndUpdatePolicy(), EvaluateAndUpdatePolicy(), and Serialize().
root_reach_probs_
const std::vector<double> open_spiel::algorithms::CFRSolverBase::root_reach_probs_ protected
Definition at line 240 of file cfr.h.
Referenced by open_spiel::algorithms::CFRBRSolver::EvaluateAndUpdatePolicy(), and EvaluateAndUpdatePolicy().
root_state_
const std::unique_ptr<State> open_spiel::algorithms::CFRSolverBase::root_state_ protected
Definition at line 239 of file cfr.h.
Referenced by CFRSolverBase(), open_spiel::algorithms::CFRBRSolver::EvaluateAndUpdatePolicy(), and EvaluateAndUpdatePolicy().
The documentation for this class was generated from the following files:
open_spiel/algorithms/cfr.h
open_spiel/algorithms/cfr.cc