open spiel: absl::container_internal::btree_set_container< Tree > Class Template Reference
absl::container_internal::btree_set_container< Tree > Class Template Reference
#include <btree_container.h>
Public Types
using key_type = typename Tree::key_type
using value_type = typename Tree::value_type
using size_type = typename Tree::size_type
using key_compare = typename Tree::original_key_compare
using allocator_type = typename Tree::allocator_type
using iterator = typename Tree::iterator
using const_iterator = typename Tree::const_iterator
using node_type = typename super_type::node_type
using insert_return_type = InsertReturnType<iterator, node_type>
Public Types inherited from absl::container_internal::btree_container< Tree >
using key_type = typename Tree::key_type
using value_type = typename Tree::value_type
using size_type = typename Tree::size_type
using difference_type = typename Tree::difference_type
using key_compare = typename Tree::original_key_compare
using value_compare = typename Tree::value_compare
using allocator_type = typename Tree::allocator_type
using reference = typename Tree::reference
using const_reference = typename Tree::const_reference
using pointer = typename Tree::pointer
using const_pointer = typename Tree::const_pointer
using iterator = typename Tree::iterator
using const_iterator = typename Tree::const_iterator
using reverse_iterator = typename Tree::reverse_iterator
using const_reverse_iterator = typename Tree::const_reverse_iterator
using node_type = typename Tree::node_handle_type
Public Member Functions
btree_set_container ()
template<class InputIterator >
btree_set_container (InputIterator b, InputIterator e, const key_compare &comp=key_compare(), const allocator_type &alloc=allocator_type())
template<class InputIterator >
btree_set_container (InputIterator b, InputIterator e, const allocator_type &alloc)
btree_set_container (std::initializer_list< init_type > init, const key_compare &comp=key_compare(), const allocator_type &alloc=allocator_type())
btree_set_container (std::initializer_list< init_type > init, const allocator_type &alloc)
std::pair< iterator, bool > insert (const value_type &v)
std::pair< iterator, bool > insert (value_type &&v)
template<typename... Args>
std::pair< iterator, bool > emplace (Args &&... args)
iterator insert (const_iterator hint, const value_type &v)
iterator insert (const_iterator hint, value_type &&v)
template<typename... Args>
iterator emplace_hint (const_iterator hint, Args &&... args)
template<typename InputIterator >
void insert (InputIterator b, InputIterator e)
void insert (std::initializer_list< init_type > init)
insert_return_type insert (node_type &&node)
iterator insert (const_iterator hint, node_type &&node)
template<typename K = key_type>
node_type extract (const key_arg< K > &key)
template<typename T , typename absl::enable_if_t< absl::conjunction< std::is_same< value_type, typename T::value_type >, std::is_same< allocator_type, typename T::allocator_type >, std::is_same< typename params_type::is_map_container, typename T::params_type::is_map_container > >::value, int > = 0>
void merge (btree_container< T > &src)
template<typename T , typename absl::enable_if_t< absl::conjunction< std::is_same< value_type, typename T::value_type >, std::is_same< allocator_type, typename T::allocator_type >, std::is_same< typename params_type::is_map_container, typename T::params_type::is_map_container > >::value, int > = 0>
void merge (btree_container< T > &&src)
node_type extract (iterator position)
node_type extract (const_iterator position)
Public Member Functions inherited from absl::container_internal::btree_container< Tree >
btree_container ()
btree_container (const key_compare &comp, const allocator_type &alloc=allocator_type())
btree_container (const allocator_type &alloc)
btree_container (const btree_container &other)
btree_container (const btree_container &other, const allocator_type &alloc)
btree_container (btree_container &&other) noexcept(std::is_nothrow_move_constructible< Tree >::value)=default
btree_container (btree_container &&other, const allocator_type &alloc)
btree_container & operator= (const btree_container &other)=default
btree_container & operator= (btree_container &&other) noexcept(std::is_nothrow_move_assignable< Tree >::value)=default
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
template<typename K = key_type>
size_type count (const key_arg< K > &key) const
template<typename K = key_type>
iterator find (const key_arg< K > &key)
template<typename K = key_type>
const_iterator find (const key_arg< K > &key) const
template<typename K = key_type>
bool contains (const key_arg< K > &key) const
template<typename K = key_type>
iterator lower_bound (const key_arg< K > &key)
template<typename K = key_type>
const_iterator lower_bound (const key_arg< K > &key) const
template<typename K = key_type>
iterator upper_bound (const key_arg< K > &key)
template<typename K = key_type>
const_iterator upper_bound (const key_arg< K > &key) const
template<typename K = key_type>
std::pair< iterator, iterator > equal_range (const key_arg< K > &key)
template<typename K = key_type>
std::pair< const_iterator, const_iterator > equal_range (const key_arg< K > &key) const
iterator erase (const_iterator iter)
iterator erase (iterator iter)
iterator erase (const_iterator first, const_iterator last)
template<typename K = key_type>
size_type erase (const key_arg< K > &key)
extract_and_get_next_return_type extract_and_get_next (const_iterator position)
node_type extract (iterator position)
node_type extract (const_iterator position)
ABSL_ATTRIBUTE_REINITIALIZES void clear ()
void swap (btree_container &other)
void verify () const
size_type size () const
size_type max_size () const
bool empty () const
allocator_type get_allocator () const
key_compare key_comp () const
value_compare value_comp () const
Protected Types
template<class K >
using key_arg = typename super_type::template key_arg<K>
Protected Types inherited from absl::container_internal::btree_container< Tree >
template<class K >
using key_arg
Friends
class BtreeNodePeer
Additional Inherited Members
Protected Attributes inherited from absl::container_internal::btree_container< Tree >
Tree tree_
Detailed Description
template<typename Tree>
class absl::container_internal::btree_set_container< Tree >
Definition at line 252 of file btree_container.h.
Member Typedef Documentation
allocator_type
template<typename Tree > using absl::container_internal::btree_set_container< Tree >::allocator_type = typename Tree::allocator_type
Definition at line 268 of file btree_container.h.
const_iterator
template<typename Tree > using absl::container_internal::btree_set_container< Tree >::const_iterator = typename Tree::const_iterator
Definition at line 270 of file btree_container.h.
insert_return_type
template<typename Tree > using absl::container_internal::btree_set_container< Tree >::insert_return_type = InsertReturnType<iterator, node_type>
Definition at line 272 of file btree_container.h.
iterator
template<typename Tree > using absl::container_internal::btree_set_container< Tree >::iterator = typename Tree::iterator
Definition at line 269 of file btree_container.h.
key_arg
template<typename Tree > template<class K > using absl::container_internal::btree_set_container< Tree >::key_arg = typename super_type::template key_arg<K> protected
Definition at line 261 of file btree_container.h.
key_compare
template<typename Tree > using absl::container_internal::btree_set_container< Tree >::key_compare = typename Tree::original_key_compare
Definition at line 267 of file btree_container.h.
key_type
template<typename Tree > using absl::container_internal::btree_set_container< Tree >::key_type = typename Tree::key_type
Definition at line 264 of file btree_container.h.
node_type
template<typename Tree > using absl::container_internal::btree_set_container< Tree >::node_type = typename super_type::node_type
Definition at line 271 of file btree_container.h.
size_type
template<typename Tree > using absl::container_internal::btree_set_container< Tree >::size_type = typename Tree::size_type
Definition at line 266 of file btree_container.h.
value_type
template<typename Tree > using absl::container_internal::btree_set_container< Tree >::value_type = typename Tree::value_type
Definition at line 265 of file btree_container.h.
Constructor & Destructor Documentation
btree_set_container() [1/5]
template<typename Tree > absl::container_internal::btree_set_container< Tree >::btree_set_container () inline
Definition at line 276 of file btree_container.h.
{}
btree_set_container() [2/5]
template<typename Tree > template<class InputIterator > absl::container_internal::btree_set_container< Tree >::btree_set_container (InputIterator b, InputIterator e, const key_compare & comp = key_compare(), const allocator_type & alloc = allocator_type()) inline
Definition at line 280 of file btree_container.h.
      : super_type(comp, alloc) {
    insert(b, e);
  }
References b, absl::e, and absl::container_internal::btree_set_container< Tree >::insert().
btree_set_container() [3/5]
template<typename Tree > template<class InputIterator > absl::container_internal::btree_set_container< Tree >::btree_set_container (InputIterator b, InputIterator e, const allocator_type & alloc) inline
Definition at line 287 of file btree_container.h.
      : btree_set_container(b, e, key_compare(), alloc) {}
btree_set_container() [4/5]
template<typename Tree > absl::container_internal::btree_set_container< Tree >::btree_set_container (std::initializer_list< init_type > init, const key_compare & comp = key_compare(), const allocator_type & alloc = allocator_type()) inline
Definition at line 292 of file btree_container.h.
      : btree_set_container(init.begin(), init.end(), comp, alloc) {}
btree_set_container() [5/5]
template<typename Tree > absl::container_internal::btree_set_container< Tree >::btree_set_container (std::initializer_list< init_type > init, const allocator_type & alloc) inline
Definition at line 296 of file btree_container.h.
      : btree_set_container(init.begin(), init.end(), alloc) {}
Member Function Documentation
emplace()
template<typename Tree > template<typename... Args> std::pair< iterator, bool > absl::container_internal::btree_set_container< Tree >::emplace (Args &&... args) inline
Definition at line 308 of file btree_container.h.
{
    // Use a node handle to manage a temp slot.
    auto node = CommonAccess::Construct<node_type>(this->get_allocator(),
                                                   std::forward<Args>(args)...);
    auto *slot = CommonAccess::GetSlot(node);
    return this->tree_.insert_unique(params_type::key(slot), slot);
  }
References absl::container_internal::CommonAccess::Construct(), absl::container_internal::btree_container< Tree >::get_allocator(), absl::container_internal::CommonAccess::GetSlot(), and absl::container_internal::btree_container< Tree >::tree_.
emplace_hint()
template<typename Tree > template<typename... Args> iterator absl::container_internal::btree_set_container< Tree >::emplace_hint (const_iterator hint, Args &&... args) inline
Definition at line 326 of file btree_container.h.
{
    // Use a node handle to manage a temp slot.
    auto node = CommonAccess::Construct<node_type>(this->get_allocator(),
                                                   std::forward<Args>(args)...);
    auto *slot = CommonAccess::GetSlot(node);
    return this->tree_
        .insert_hint_unique(iterator(hint), params_type::key(slot), slot)
        .first;
  }
References absl::container_internal::CommonAccess::Construct(), absl::container_internal::btree_container< Tree >::get_allocator(), absl::container_internal::CommonAccess::GetSlot(), and absl::container_internal::btree_container< Tree >::tree_.
extract() [1/3]
template<typename Tree > template<typename K = key_type> node_type absl::container_internal::btree_set_container< Tree >::extract (const key_arg< K > & key) inline
Definition at line 365 of file btree_container.h.
{
    const std::pair<iterator, bool> lower_and_equal =
        this->tree_.lower_bound_equal(key);
    return lower_and_equal.second ? extract(lower_and_equal.first)
                                  : node_type();
  }
References absl::container_internal::btree_set_container< Tree >::extract(), and absl::container_internal::btree_container< Tree >::tree_.
Referenced by absl::container_internal::btree_set_container< Tree >::extract().
extract() [2/3]
template<typename Tree > node_type absl::container_internal::btree_container< Tree >::extract (const_iterator position) inline
Definition at line 190 of file btree_container.h.
{
    return extract(iterator(position));
  }
extract() [3/3]
template<typename Tree > node_type absl::container_internal::btree_container< Tree >::extract (iterator position) inline
Definition at line 182 of file btree_container.h.
{
    // Use Construct instead of Transfer because the rebalancing code will
    // destroy the slot later.
    auto node =
        CommonAccess::Construct<node_type>(get_allocator(), position.slot());
    erase(position);
    return node;
  }
insert() [1/8]
template<typename Tree > std::pair< iterator, bool > absl::container_internal::btree_set_container< Tree >::insert (const value_type & v) inline
Definition at line 301 of file btree_container.h.
{
    return this->tree_.insert_unique(params_type::key(v), v);
  }
References absl::container_internal::btree_container< Tree >::tree_, and absl::v.
Referenced by open_spiel::algorithms::TabularBestResponse::BestResponseActions(), absl::container_internal::btree_set_container< Tree >::btree_set_container(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all(), and absl::container_internal::btree_set_container< Tree >::merge().
insert() [2/8]
template<typename Tree > iterator absl::container_internal::btree_set_container< Tree >::insert (const_iterator hint, const value_type & v) inline
Definition at line 315 of file btree_container.h.
{
    return this->tree_
        .insert_hint_unique(iterator(hint), params_type::key(v), v)
        .first;
  }
References absl::container_internal::btree_container< Tree >::tree_, and absl::v.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [3/8]
template<typename Tree > iterator absl::container_internal::btree_set_container< Tree >::insert (const_iterator hint, node_type && node) inline
Definition at line 354 of file btree_container.h.
{
    if (!node) return this->end();
    std::pair<iterator, bool> res = this->tree_.insert_hint_unique(
        iterator(hint), params_type::key(CommonAccess::GetSlot(node)),
        CommonAccess::GetSlot(node));
    if (res.second) CommonAccess::Destroy(&node);
    return res.first;
  }
References absl::container_internal::CommonAccess::Destroy(), absl::container_internal::btree_container< Tree >::end(), absl::container_internal::CommonAccess::GetSlot(), and absl::container_internal::btree_container< Tree >::tree_.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [4/8]
template<typename Tree > iterator absl::container_internal::btree_set_container< Tree >::insert (const_iterator hint, value_type && v) inline
Definition at line 320 of file btree_container.h.
{
    return this->tree_
        .insert_hint_unique(iterator(hint), params_type::key(v), std::move(v))
        .first;
  }
References absl::container_internal::btree_container< Tree >::tree_, and absl::v.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [5/8]
template<typename Tree > template<typename InputIterator > void absl::container_internal::btree_set_container< Tree >::insert (InputIterator b, InputIterator e) inline
Definition at line 336 of file btree_container.h.
{
    this->tree_.insert_iterator_unique(b, e, 0);
  }
References absl::e, and absl::container_internal::btree_container< Tree >::tree_.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [6/8]
template<typename Tree > insert_return_type absl::container_internal::btree_set_container< Tree >::insert (node_type && node) inline
Definition at line 342 of file btree_container.h.
{
    if (!node) return {this->end(), false, node_type()};
    std::pair<iterator, bool> res =
        this->tree_.insert_unique(params_type::key(CommonAccess::GetSlot(node)),
                                  CommonAccess::GetSlot(node));
    if (res.second) {
      CommonAccess::Destroy(&node);
      return {res.first, true, node_type()};
    } else {
      return {res.first, false, std::move(node)};
    }
  }
References absl::container_internal::CommonAccess::Destroy(), absl::container_internal::btree_container< Tree >::end(), absl::container_internal::CommonAccess::GetSlot(), and absl::container_internal::btree_container< Tree >::tree_.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [7/8]
template<typename Tree > void absl::container_internal::btree_set_container< Tree >::insert (std::initializer_list< init_type > init) inline
Definition at line 339 of file btree_container.h.
{
    this->tree_.insert_iterator_unique(init.begin(), init.end(), 0);
  }
References absl::container_internal::btree_container< Tree >::tree_.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [8/8]
template<typename Tree > std::pair< iterator, bool > absl::container_internal::btree_set_container< Tree >::insert (value_type && v) inline
Definition at line 304 of file btree_container.h.
{
    return this->tree_.insert_unique(params_type::key(v), std::move(v));
  }
References absl::container_internal::btree_container< Tree >::tree_, and absl::v.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
merge() [1/2]
template<typename Tree > template<typename T , typename absl::enable_if_t< absl::conjunction< std::is_same< value_type, typename T::value_type >, std::is_same< allocator_type, typename T::allocator_type >, std::is_same< typename params_type::is_map_container, typename T::params_type::is_map_container > >::value, int > = 0> void absl::container_internal::btree_set_container< Tree >::merge (btree_container< T > && src) inline
Definition at line 404 of file btree_container.h.
{
    merge(src);
  }
References absl::container_internal::btree_set_container< Tree >::merge().
merge() [2/2]
template<typename Tree > template<typename T , typename absl::enable_if_t< absl::conjunction< std::is_same< value_type, typename T::value_type >, std::is_same< allocator_type, typename T::allocator_type >, std::is_same< typename params_type::is_map_container, typename T::params_type::is_map_container > >::value, int > = 0> void absl::container_internal::btree_set_container< Tree >::merge (btree_container< T > & src) inline
Definition at line 385 of file btree_container.h.
                                      {  // NOLINT
    for (auto src_it = src.begin(); src_it != src.end();) {
      if (insert(std::move(params_type::element(src_it.slot()))).second) {
        src_it = src.erase(src_it);
      } else {
        ++src_it;
      }
    }
  }
References absl::container_internal::btree_container< Tree >::begin(), absl::container_internal::btree_container< Tree >::end(), absl::container_internal::btree_container< Tree >::erase(), and absl::container_internal::btree_set_container< Tree >::insert().
Referenced by absl::container_internal::btree_set_container< Tree >::merge().
Friends And Related Symbol Documentation
BtreeNodePeer
template<typename Tree > friend class BtreeNodePeer friend
Definition at line 257 of file btree_container.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/btree_container.h