open spiel: absl::poisson_distribution< IntType >::param_type Class Reference
absl::poisson_distribution< IntType >::param_type Class Reference
#include <poisson_distribution.h>
Public Types
using distribution_type = poisson_distribution
Public Member Functions
param_type (double mean=1.0)
double mean () const
Friends
class poisson_distribution
bool operator== (const param_type &a, const param_type &b)
bool operator!= (const param_type &a, const param_type &b)
Detailed Description
template<typename IntType = int>
class absl::poisson_distribution< IntType >::param_type
Definition at line 59 of file poisson_distribution.h.
Member Typedef Documentation
distribution_type
template<typename IntType = int> using absl::poisson_distribution< IntType >::param_type::distribution_type = poisson_distribution
Definition at line 61 of file poisson_distribution.h.
Constructor & Destructor Documentation
param_type()
template<typename IntType > absl::poisson_distribution< IntType >::param_type::param_type (double mean = 1.0) explicit
Definition at line 134 of file poisson_distribution.h.
    : mean_(mean), split_(0) {
  assert(mean >= 0);
  assert(mean <=
         static_cast<double>((std::numeric_limits<result_type>::max)()));
  // As a defensive measure, avoid large values of the mean.  The rejection
  // algorithm used does not support very large values well.  It my be worth
  // changing algorithms to better deal with these cases.
  assert(mean <= 1e10);
  if (mean_ < 10) {
    // For small lambda, use the knuth method.
    split_ = 1;
    emu_ = std::exp(-mean_);
  } else if (mean_ <= 50) {
    // Use split-knuth method.
    split_ = 1 + static_cast<int>(mean_ / 10.0);
    emu_ = std::exp(-mean_ / static_cast<double>(split_));
  } else {
    // Use ratio of uniforms method.
    constexpr double k2E = 0.7357588823428846;
    constexpr double kSA = 0.4494580810294493;
    lmu_ = std::log(mean_);
    double a = mean_ + 0.5;
    s_ = kSA + std::sqrt(k2E * a);
    const double mode = std::ceil(mean_) - 1;
    log_k_ = lmu_ * mode - absl::random_internal::StirlingLogFactorial(mode);
  }
}
References absl::a, absl::poisson_distribution< IntType >::param_type::mean(), and absl::random_internal::StirlingLogFactorial().
Member Function Documentation
mean()
template<typename IntType = int> double absl::poisson_distribution< IntType >::param_type::mean () const inline
Definition at line 64 of file poisson_distribution.h.
{ return mean_; }
Referenced by absl::poisson_distribution< IntType >::mean(), and absl::poisson_distribution< IntType >::param_type::param_type().
Friends And Related Symbol Documentation
operator!=
template<typename IntType = int> bool operator!= (const param_type & a, const param_type & b) friend
Definition at line 70 of file poisson_distribution.h.
{
      return !(a == b);
    }
operator==
template<typename IntType = int> bool operator== (const param_type & a, const param_type & b) friend
Definition at line 66 of file poisson_distribution.h.
{
      return a.mean_ == b.mean_;
    }
poisson_distribution
template<typename IntType = int> friend class poisson_distribution friend
Definition at line 75 of file poisson_distribution.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/poisson_distribution.h