open spiel: open_spiel::chess::ChessGame Class Reference
open_spiel::chess::ChessGame Class Reference
#include <chess.h>
Public Member Functions
ChessGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState (const std::string &fen) const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 217 of file chess.h.
Constructor & Destructor Documentation
ChessGame()
open_spiel::chess::ChessGame::ChessGame (const GameParameters & params) explicit
Definition at line 434 of file chess.cc.
: Game(kGameType, params) {}
Member Function Documentation
DeserializeState()
std::unique_ptr< State > open_spiel::chess::ChessGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 436 of file chess.cc.
{
  const std::string prefix("FEN: ");
  if (!absl::StartsWith(str, prefix)) {
    // Backward compatibility.
    return Game::DeserializeState(str);
  }
  std::vector<std::string> lines = absl::StrSplit(str, '\n');
  // Create initial state from FEN (first line of serialized state).
  std::unique_ptr<State> state = NewInitialState(
      lines[0].substr(prefix.length()));
  for (int i = 1; i < lines.size(); ++i) {
    if (lines[i].empty()) {
      break;
    }
    Action action = static_cast<Action>(std::stol(lines[i]));
    state->ApplyAction(action);
  }
  return state;
}
References action, open_spiel::Game::DeserializeState(), i, NewInitialState(), absl::StartsWith(), state, and absl::StrSplit().
MaxGameLength()
int open_spiel::chess::ChessGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 237 of file chess.h.
{ return chess::MaxGameLength(); }
References open_spiel::chess::MaxGameLength().
MaxUtility()
double open_spiel::chess::ChessGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 233 of file chess.h.
{ return WinUtility(); }
References open_spiel::chess::WinUtility().
MinUtility()
double open_spiel::chess::ChessGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 231 of file chess.h.
{ return LossUtility(); }
References open_spiel::chess::LossUtility().
NewInitialState() [1/2]
std::unique_ptr< State > open_spiel::chess::ChessGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 227 of file chess.h.
{
    return absl::make_unique<ChessState>(shared_from_this());
  }
Referenced by DeserializeState().
NewInitialState() [2/2]
std::unique_ptr< State > open_spiel::chess::ChessGame::NewInitialState (const std::string & fen) const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 223 of file chess.h.
{
    return absl::make_unique<ChessState>(shared_from_this(), fen);
  }
NumDistinctActions()
int open_spiel::chess::ChessGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 220 of file chess.h.
{
    return chess::NumDistinctActions();
  }
References open_spiel::chess::NumDistinctActions().
NumPlayers()
int open_spiel::chess::ChessGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 230 of file chess.h.
{ return chess::NumPlayers(); }
References open_spiel::chess::NumPlayers().
ObservationTensorShape()
std::vector< int > open_spiel::chess::ChessGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 234 of file chess.h.
{
    return chess::ObservationTensorShape();
  }
References open_spiel::chess::ObservationTensorShape().
UtilitySum()
absl::optional< double > open_spiel::chess::ChessGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 232 of file chess.h.
{ return DrawUtility(); }
References open_spiel::chess::DrawUtility().
The documentation for this class was generated from the following files:
open_spiel/games/chess/chess.h
open_spiel/games/chess/chess.cc