open spiel: open_spiel::crazy_eights::CrazyEightsState Class Reference
open_spiel::crazy_eights::CrazyEightsState Class Reference
#include <crazy_eights.h>
Public Member Functions
CrazyEightsState (std::shared_ptr< const Game > game, int num_players, int max_draw_cards, bool use_special_cards, bool reshuffle)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void WriteObservationTensor (Player player, absl::Span< float > values) const
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 95 of file crazy_eights.h.
Constructor & Destructor Documentation
CrazyEightsState()
open_spiel::crazy_eights::CrazyEightsState::CrazyEightsState (std::shared_ptr< const Game > game, int num_players, int max_draw_cards, bool use_special_cards, bool reshuffle)
Definition at line 105 of file crazy_eights.cc.
    : State(game),
      reshuffle_(reshuffle),
      num_players_(num_players),
      max_draw_cards_(max_draw_cards),
      use_special_cards_(use_special_cards) {
  num_initial_cards_ =
      num_players == 2 ? kNumInitialCardsForTwoPlayers : kNumInitialCards;
  num_decks_ = num_players > 5 ? 2 : 1;
  num_cards_left_ = num_decks_ * kNumCards;
  absl::c_fill(dealer_deck_, num_decks_);
  for (int i = 0; i < num_players; ++i) {
    hands_.push_back(std::vector<int>(kNumCards, 0));
    returns_.push_back(0);
  }
}
References absl::c_fill(), i, and open_spiel::crazy_eights::kNumCards.
Member Function Documentation
ActionToString()
std::string open_spiel::crazy_eights::CrazyEightsState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 124 of file crazy_eights.cc.
{
  if (player == kChancePlayerId) {
    if (action < kDraw) {
      return absl::StrFormat("Deal %s", GetCardStr(action));
    } else if (action < kDecideDealerActionBase + num_players_) {
      return absl::StrFormat("Decide Player %d to be the dealer",
                             action - kDecideDealerActionBase);
    } else {
      SpielFatalError(
          absl::StrFormat("Non action valid Id  %d for chance player", action));
    }
  }
  if (action < kDraw) {
    return absl::StrFormat("Play %s", GetCardStr(action));
  } else if (action == kDraw) {
    return "Draw";
  } else if (action == kPass) {
    return "Pass";
  } else if (action < kNominateSuitActionBase + kNumSuits) {
    return absl::StrFormat("Nominate suit %c",
                           kSuitChar[action - kNominateSuitActionBase]);
  } else {
    SpielFatalError(
        absl::StrFormat("Non valid Id %d for player: %d", action, player));
  }
}
References action, open_spiel::kChancePlayerId, open_spiel::crazy_eights::kDecideDealerActionBase, open_spiel::crazy_eights::kDraw, open_spiel::crazy_eights::kNominateSuitActionBase, open_spiel::crazy_eights::kNumSuits, open_spiel::crazy_eights::kPass, player, open_spiel::SpielFatalError(), and absl::StrFormat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::crazy_eights::CrazyEightsState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 347 of file crazy_eights.cc.
          {
  std::vector<std::pair<Action, double>> outcomes;
  if (history_.empty()) {
    for (int player = 0; player < num_players_; ++player) {
        outcomes.emplace_back(player + kDecideDealerActionBase,
                            1.0 / num_players_);
    }
  } else {
    int num_cards_remaining = 0;
    for (int card = 0; card < kNumCards; ++card) {
      SPIEL_CHECK_GE(dealer_deck_[card], 0);
      SPIEL_CHECK_LE(dealer_deck_[card], num_decks_);
      num_cards_remaining += dealer_deck_[card];
    }
    outcomes.reserve(num_cards_remaining);
    for (int card = 0; card < kNumCards; ++card) {
      if (dealer_deck_[card]) {
        outcomes.emplace_back(card, static_cast<double>(dealer_deck_[card]) /
                              num_cards_remaining);
      }
    }
  }
  return outcomes;
}
References open_spiel::State::history_, open_spiel::crazy_eights::kDecideDealerActionBase, open_spiel::crazy_eights::kNumCards, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Clone()
std::unique_ptr< State > open_spiel::crazy_eights::CrazyEightsState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 108 of file crazy_eights.h.
{
    return absl::make_unique<CrazyEightsState>(*this);
  }
CurrentPlayer()
Player open_spiel::crazy_eights::CrazyEightsState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 685 of file crazy_eights.cc.
{
  if (phase_ == Phase::kDeal) {
    return kChancePlayerId;
  } else if (phase_ == Phase::kGameOver) {
    return kTerminalPlayerId;
  } else {
    return current_player_;
  }
}
References open_spiel::kChancePlayerId, open_spiel::crazy_eights::kDeal, open_spiel::crazy_eights::kGameOver, and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::crazy_eights::CrazyEightsState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 373 of file crazy_eights.cc.
{
  switch (phase_) {
    case Phase::kDeal:
      return ApplyDealAction(action);
    case Phase::kPlay:
      return ApplyPlayAction(action);
    case Phase::kGameOver:
      SpielFatalError("Cannot act in terminal states");
    default:
      SpielFatalError("Invalid Phase!");
  }
}
References action, open_spiel::crazy_eights::kDeal, open_spiel::crazy_eights::kGameOver, open_spiel::crazy_eights::kPlay, and open_spiel::SpielFatalError().
IsTerminal()
bool open_spiel::crazy_eights::CrazyEightsState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 102 of file crazy_eights.h.
{ return phase_ == Phase::kGameOver; }
References open_spiel::crazy_eights::kGameOver.
LegalActions()
std::vector< Action > open_spiel::crazy_eights::CrazyEightsState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 336 of file crazy_eights.cc.
{
  switch (phase_) {
    case Phase::kDeal:
      return DealLegalActions();
    case Phase::kPlay:
      return PlayLegalActions();
    default:
      return {};
  }
}
References open_spiel::crazy_eights::kDeal, and open_spiel::crazy_eights::kPlay.
ObservationString()
std::string open_spiel::crazy_eights::CrazyEightsState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 266 of file crazy_eights.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string str;
  if (phase_ == Phase::kDeal) return str;
  absl::StrAppend(&str, "Currently I have: \n");
  std::vector<std::string> hands = FormatHand(player);
  for (int suit = 0; suit < kNumSuits; ++suit) {
    absl::StrAppend(
        &str, absl::StrFormat("Suit %c: %s\n", kSuitChar[suit], hands[suit]));
  }
  absl::StrAppend(
      &str, absl::StrFormat("Previous card: %s\n", GetCardStr(last_card_)));
  absl::StrAppend(
      &str, absl::StrFormat("Previous suit: %c\n", kSuitChar[last_suit_]));
  absl::StrAppend(&str, "Starting counterclockwise, other players have: ");
  for (int i = 0; i <= num_players_ - 1; ++i) {
    int player_idx = (player + i) % num_players_;
    int player_num_cards = 0;
    for (int card = 0; card < kNumCards; ++card) {
      player_num_cards += hands_[player_idx][card];
    }
    if (i != num_players_ - 1) {
      absl::StrAppend(&str, absl::StrFormat("%d, ", player_num_cards));
    } else {
      absl::StrAppend(&str, absl::StrFormat("%d cards.\n", player_num_cards));
    }
  }
  if (use_special_cards_) {
    absl::StrAppend(&str, absl::StrFormat("The direction is %s\n",
                                          direction_ == 1 ? "counterclockwise"
                                                          : "clockwise"));
  }
  return str;
}
References i, open_spiel::crazy_eights::kDeal, open_spiel::crazy_eights::kNumCards, open_spiel::crazy_eights::kNumSuits, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and absl::StrFormat().
ObservationTensor()
void open_spiel::crazy_eights::CrazyEightsState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 302 of file crazy_eights.cc.
{
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  WriteObservationTensor(player, values);
}
References open_spiel::State::game_, player, SPIEL_CHECK_EQ, values, and WriteObservationTensor().
Returns()
std::vector< double > open_spiel::crazy_eights::CrazyEightsState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 103 of file crazy_eights.h.
{ return returns_; }
ToString()
std::string open_spiel::crazy_eights::CrazyEightsState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 208 of file crazy_eights.cc.
{
  std::string str;
  int playing_player = dealer_;
  for (int i = 0; i < history_.size(); ++i) {
    if (i == 0) {
      absl::StrAppend(
          &str, absl::StrFormat("Player %d becomes the dealer\n", dealer_));
    } else if (i <= num_players_ * num_initial_cards_) {
      int player = (dealer_ + i) % num_players_;
      absl::StrAppend(&str, absl::StrFormat("Player %d is dealt %s\n", player,
                                            GetCardStr(history_[i].action)));
    } else {
      if (history_[i].player == kChancePlayerId) {
        absl::StrAppend(&str,
                        absl::StrFormat("Player %d draws %s\n", playing_player,
                                        GetCardStr(history_[i].action)));
      } else if (history_[i].player != kTerminalPlayerId) {
        playing_player = history_[i].player;
        if (history_[i].action == kDraw) {
          absl::StrAppend(&str, absl::StrFormat("Player %d starts drawing\n",
                                                playing_player));
        } else if (history_[i].action == kPass) {
          absl::StrAppend(
              &str, absl::StrFormat("Player %d passes\n", playing_player));
        } else if (history_[i].action >= kNominateSuitActionBase &&
                   history_[i].action < kNominateSuitActionBase + kNumSuits) {
          int suit = history_[i].action - kNominateSuitActionBase;
          absl::StrAppend(&str,
                          absl::StrFormat("Player %d nominates suit %c\n",
                                          playing_player, kSuitChar[suit]));
        } else {
          SPIEL_CHECK_GE(history_[i].action, 0);
          SPIEL_CHECK_LT(history_[i].action, kNumCards);
          absl::StrAppend(
              &str, absl::StrFormat("Player %d plays %s\n", playing_player,
                                    GetCardStr(history_[i].action)));
        }
      } else {
        absl::StrAppend(&str, "Final scores\n");
        for (int player = 0; player < num_players_; ++player) {
          absl::StrAppend(&str, absl::StrFormat("Player %d gets score %f\n",
                                                player, returns_[player]));
        }
      }
    }
  }
  if (last_card_ != kInvalidAction) {
    absl::StrAppend(&str,
                    absl::StrFormat("Last card: %s\n", GetCardStr(last_card_)));
    absl::StrAppend(&str,
                    absl::StrFormat("Last suit: %c\n", kSuitChar[last_suit_]));
  }
  absl::StrAppend(&str, absl::StrFormat("Number of cards left in deck: %d\n",
                                        num_cards_left_));
  absl::StrAppend(&str, FormatAllHands());
  return str;
}
References action, open_spiel::State::history_, i, open_spiel::kChancePlayerId, open_spiel::crazy_eights::kDraw, open_spiel::kInvalidAction, open_spiel::crazy_eights::kNominateSuitActionBase, open_spiel::crazy_eights::kNumCards, open_spiel::crazy_eights::kNumSuits, open_spiel::crazy_eights::kPass, open_spiel::kTerminalPlayerId, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and absl::StrFormat().
WriteObservationTensor()
void open_spiel::crazy_eights::CrazyEightsState::WriteObservationTensor (Player player, absl::Span< float > values) const
Definition at line 308 of file crazy_eights.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  absl::c_fill(values, 0.);
  if (phase_ == Phase::kDeal) return;
  for (int card = 0; card < kNumCards; ++card) {
    values[card * (num_decks_ + 1) + hands_[player][card]] = 1;
  }
  values[(num_decks_ + 1) * kNumCards + last_card_] = 1;
  values[(num_decks_ + 1) * kNumCards + kNumCards + last_suit_] = 1;
  int tmp_base = (num_decks_ + 1) * kNumCards + kNumCards + kNumSuits;
  for (int i = 1; i <= num_players_ - 1; ++i) {
    int num_cards = 0;
    for (int card = 0; card < kNumCards; ++card) {
      num_cards += hands_[(player + i) % num_players_][card];
    }
    values[tmp_base + (i - 1) * (num_decks_ * kNumCards + 1) + num_cards] = 1;
  }
  if (use_special_cards_) {
    tmp_base += (num_decks_ * kNumCards + 1) * (num_players_ - 1);
    values[tmp_base] = (direction_ + 1) / 2;
  }
}
References absl::c_fill(), i, open_spiel::crazy_eights::kDeal, open_spiel::crazy_eights::kNumCards, open_spiel::crazy_eights::kNumSuits, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Referenced by ObservationTensor().
The documentation for this class was generated from the following files:
open_spiel/games/crazy_eights/crazy_eights.h
open_spiel/games/crazy_eights/crazy_eights.cc