open spiel: open_spiel::clobber::ClobberState Class Reference
open_spiel::clobber::ClobberState Class Reference
#include <clobber.h>
Public Member Functions
ClobberState (std::shared_ptr< const Game > game, int rows, int columns)
ClobberState (std::shared_ptr< const Game > game, int rows, int columns, const std::string &board_string)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
bool InBounds (int row, int column) const
void SetBoard (int row, int column, CellState state)
CellState BoardAt (int row, int column) const
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 74 of file clobber.h.
Constructor & Destructor Documentation
ClobberState() [1/2]
open_spiel::clobber::ClobberState::ClobberState (std::shared_ptr< const Game > game, int rows, int columns) explicit
Definition at line 153 of file clobber.cc.
    : State(game), rows_(rows), columns_(columns) {
  SPIEL_CHECK_GE(rows_, 1);
  SPIEL_CHECK_GE(columns_, 1);
  SPIEL_CHECK_LE(rows_, 99);     // Only supports 1 and 2 digit row numbers.
  SPIEL_CHECK_LE(columns_, 26);  // Only 26 letters to represent columns.
  board_ = std::vector<CellState>(rows_ * columns_, CellState::kEmpty);
  // Put the pieces on the board (checkerboard pattern) starting with
  // the first player (White, or 'o') in the bottom left corner.
  for (int row = rows_ - 1; row >= 0; row--) {
    for (int column = 0; column < columns_; column++) {
      if ((IsEven(row + (rows_ - 1)) && IsEven(column)) ||
          (!IsEven(row + (rows_ - 1)) && !IsEven(column))) {
        SetBoard(row, column, CellState::kWhite);
      } else {
        SetBoard(row, column, CellState::kBlack);
      }
    }
  }
}
References open_spiel::clobber::kBlack, open_spiel::clobber::kEmpty, open_spiel::clobber::kWhite, SetBoard(), SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Referenced by Clone().
ClobberState() [2/2]
open_spiel::clobber::ClobberState::ClobberState (std::shared_ptr< const Game > game, int rows, int columns, const std::string & board_string) explicit
Definition at line 177 of file clobber.cc.
    : State(game), rows_(rows), columns_(columns) {
  SPIEL_CHECK_GE(rows_, 1);
  SPIEL_CHECK_GE(columns_, 1);
  SPIEL_CHECK_LE(rows_, 99);     // Only supports 1 and 2 digit row numbers.
  SPIEL_CHECK_LE(columns_, 26);  // Only 26 letters to represent columns.
  SPIEL_CHECK_GE(board_string[0], '0');
  SPIEL_CHECK_LE(board_string[0], '1');
  SPIEL_CHECK_EQ(rows_ * columns_, board_string.length() - 1);
  board_ = std::vector<CellState>(rows_ * columns_, CellState::kEmpty);
  current_player_ = board_string[0] - '0';
  // Create the board from the board string. The character 'o' is White
  // (first player), 'x' is Black (second player), and the character '.'
  // is an Empty cell. Population goes from top left to bottom right.
  for (int row = 0; row < rows_; row++) {
    for (int column = 0; column < columns_; column++) {
      char state_character = board_string[1 + row * columns_ + column];
      CellState state = StringToState(std::string(1, state_character));
      SetBoard(row, column, state);
    }
  }
  // If the given state is terminal, the current player
  // cannot play. Therefore, the other player wins.
  if (!MovesRemaining()) {
    outcome_ = 1 - current_player_;
  }
}
References open_spiel::clobber::kEmpty, SetBoard(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and state.
Member Function Documentation
ActionToString()
std::string open_spiel::clobber::ClobberState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 236 of file clobber.cc.
{
  std::vector<int> values =
      UnrankActionMixedBase(action_id, {rows_, columns_, kNumDirections});
  const int start_row = values[0];
  const int start_column = values[1];
  const int direction = values[2];
  const int end_row = start_row + kDirRowOffsets[direction];
  const int end_column = start_column + kDirColumnOffsets[direction];
  std::string action_string =
      absl::StrCat(ColumnLabel(start_column), RowLabel(rows_, start_row),
                   ColumnLabel(end_column), RowLabel(rows_, end_row));
  return action_string;
}
References absl::StrCat(), open_spiel::UnrankActionMixedBase(), and values.
BoardAt()
CellState open_spiel::clobber::ClobberState::BoardAt (int row, int column) const inline
Definition at line 99 of file clobber.h.
{
    return board_[row * columns_ + column];
  }
Referenced by DoApplyAction(), LegalActions(), ObservationTensor(), ToString(), and UndoAction().
Clone()
std::unique_ptr< State > open_spiel::clobber::ClobberState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 91 of file clobber.h.
{
    return std::unique_ptr<State>(new ClobberState(*this));
  }
References ClobberState().
CurrentPlayer()
Player open_spiel::clobber::ClobberState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 80 of file clobber.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by LegalActions().
DoApplyAction()
void open_spiel::clobber::ClobberState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 209 of file clobber.cc.
{
  std::vector<int> values =
      UnrankActionMixedBase(action, {rows_, columns_, kNumDirections});
  const int start_row = values[0];
  const int start_column = values[1];
  const int direction = values[2];
  const int end_row = start_row + kDirRowOffsets[direction];
  const int end_column = start_column + kDirColumnOffsets[direction];
  SPIEL_CHECK_TRUE(InBounds(start_row, start_column));
  SPIEL_CHECK_TRUE(InBounds(end_row, end_column));
  SPIEL_CHECK_EQ(BoardAt(start_row, start_column),
                 OpponentState(BoardAt(end_row, end_column)));
  SetBoard(end_row, end_column, BoardAt(start_row, start_column));
  SetBoard(start_row, start_column, CellState::kEmpty);
  // Does the other player have any moves left?
  if (!MovesRemaining()) {
    outcome_ = current_player_;
  }
  current_player_ = 1 - current_player_;
  num_moves_++;
}
References action, BoardAt(), InBounds(), open_spiel::clobber::kEmpty, SetBoard(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, open_spiel::UnrankActionMixedBase(), and values.
InBounds()
bool open_spiel::clobber::ClobberState::InBounds (int row, int column) const
Definition at line 296 of file clobber.cc.
{
  return (row >= 0 && row < rows_ && column >= 0 && column < columns_);
}
Referenced by DoApplyAction(), and LegalActions().
InformationStateString()
std::string open_spiel::clobber::ClobberState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 378 of file clobber.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::clobber::ClobberState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 366 of file clobber.cc.
{ return outcome_ != kInvalidPlayer; }
References open_spiel::kInvalidPlayer.
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::clobber::ClobberState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 254 of file clobber.cc.
{
  std::vector<Action> move_list;
  if (IsTerminal()) {
    return move_list;
  }
  CellState current_player_state = PlayerToState(CurrentPlayer());
  std::vector<int> action_bases = {rows_, columns_, kNumDirections};
  std::vector<int> action_values = {0, 0, 0};
  for (int row = 0; row < rows_; row++) {
    for (int column = 0; column < columns_; column++) {
      if (BoardAt(row, column) == current_player_state) {
        for (int direction = 0; direction < kNumDirections; direction++) {
          int adjacent_row = row + kDirRowOffsets[direction];
          int adjacent_column = column + kDirColumnOffsets[direction];
          if (InBounds(adjacent_row, adjacent_column)) {
            CellState adjacent_state = BoardAt(adjacent_row, adjacent_column);
            CellState opponent_state = OpponentState(current_player_state);
            if (adjacent_state == opponent_state) {
              // The adjacent cell is in bounds and contains the opponent
              // player, therefore playing to this adjacent cell would be
              // a valid move.
              action_values[0] = row;
              action_values[1] = column;
              action_values[2] = direction;
              move_list.push_back(
                  RankActionMixedBase(action_bases, action_values));
            }
          }
        }
      }
    }
  }
  return move_list;
}
References BoardAt(), CurrentPlayer(), InBounds(), IsTerminal(), and open_spiel::RankActionMixedBase().
ObservationString()
std::string open_spiel::clobber::ClobberState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 384 of file clobber.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::clobber::ClobberState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 390 of file clobber.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<3> view(values, {kCellStates, rows_, columns_},
                               true);
  // Observation Tensor Representation:
  //   Plane 0: 1's where the current player's pieces are, 0's elsewhere.
  //   Plane 1: 1's where the oppponent's pieces are, 0's elsewhere.
  //   Plane 2: 1's where the empty cells are, 0's elsewhere.
  for (int row = 0; row < rows_; row++) {
    for (int column = 0; column < columns_; column++) {
      int plane = ObservationPlane(BoardAt(row, column), player);
      view[{plane, row, column}] = 1.0;
    }
  }
}
References BoardAt(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::clobber::ClobberState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 368 of file clobber.cc.
{
  if (outcome_ == kInvalidPlayer) {
    return {0., 0.};
  } else if (outcome_ == Player{0}) {
    return {1.0, -1.0};
  } else {
    return {-1.0, 1.0};
  }
}
References open_spiel::kInvalidPlayer.
SetBoard()
void open_spiel::clobber::ClobberState::SetBoard (int row, int column, CellState state) inline
Definition at line 96 of file clobber.h.
{
    board_[row * columns_ + column] = state;
  }
References state.
Referenced by ClobberState(), ClobberState(), DoApplyAction(), and UndoAction().
ToString()
std::string open_spiel::clobber::ClobberState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 300 of file clobber.cc.
{
  std::string result = "";
  for (int r = 0; r < rows_; r++) {
    // Ensure the row labels are aligned.
    if (rows_ - r < 10 && rows_ >= 10) {
      absl::StrAppend(&result, " ");
    }
    absl::StrAppend(&result, RowLabel(rows_, r));
    for (int c = 0; c < columns_; c++) {
      absl::StrAppend(&result, StateToString(BoardAt(r, c)));
    }
    result.append("\n");
  }
  // Add an extra space to the bottom row
  // if the row labels take up two spaces.
  if (rows_ >= 10) {
    absl::StrAppend(&result, " ");
  }
  absl::StrAppend(&result, " ");
  for (int c = 0; c < columns_; c++) {
    absl::StrAppend(&result, ColumnLabel(c));
  }
  absl::StrAppend(&result, "\n");
  return result;
}
References BoardAt(), r, StateToString(), and absl::StrAppend().
Referenced by ObservationString().
UndoAction()
void open_spiel::clobber::ClobberState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 410 of file clobber.cc.
{
  std::vector<int> values =
      UnrankActionMixedBase(action, {rows_, columns_, kNumDirections});
  const int start_row = values[0];
  const int start_column = values[1];
  const int direction = values[2];
  const int end_row = start_row + kDirRowOffsets[direction];
  const int end_column = start_column + kDirColumnOffsets[direction];
  current_player_ = player;
  outcome_ = kInvalidPlayer;
  num_moves_--;
  if (BoardAt(end_row, end_column) == CellState::kWhite) {
    SetBoard(end_row, end_column, CellState::kBlack);
    SetBoard(start_row, start_column, CellState::kWhite);
  } else {
    SetBoard(end_row, end_column, CellState::kWhite);
    SetBoard(start_row, start_column, CellState::kBlack);
  }
  history_.pop_back();
}
References action, BoardAt(), open_spiel::State::history_, open_spiel::clobber::kBlack, open_spiel::kInvalidPlayer, open_spiel::clobber::kWhite, player, SetBoard(), open_spiel::UnrankActionMixedBase(), and values.
The documentation for this class was generated from the following files:
open_spiel/games/clobber/clobber.h
open_spiel/games/clobber/clobber.cc