open spiel: open_spiel::leduc_poker::LeducObserver Class Reference
open_spiel::leduc_poker::LeducObserver Class Reference
Public Member Functions
LeducObserver (IIGObservationType iig_obs_type)
void WriteTensor (const State &observed_state, int player, Allocator *allocator) const override
std::string StringFrom (const State &observed_state, int player) const override
Public Member Functions inherited from open_spiel::Observer
Observer (bool has_string, bool has_tensor)
bool HasString () const
bool HasTensor () const
virtual ~Observer ()=default
Static Public Member Functions
static void WriteObservingPlayer (const LeducState &state, int player, Allocator *allocator)
static void WriteSinglePlayerCard (const LeducState &state, int player, Allocator *allocator)
static void WriteAllPlayerCards (const LeducState &state, Allocator *allocator)
static void WriteCommunityCard (const LeducState &state, Allocator *allocator)
static void WriteBettingSequence (const LeducState &state, Allocator *allocator)
static void WritePotContribution (const LeducState &state, Allocator *allocator)
Additional Inherited Members
Protected Attributes inherited from open_spiel::Observer
bool has_string_
bool has_tensor_
Detailed Description
Definition at line 89 of file leduc_poker.cc.
Constructor & Destructor Documentation
LeducObserver()
open_spiel::leduc_poker::LeducObserver::LeducObserver (IIGObservationType iig_obs_type) inline
Definition at line 91 of file leduc_poker.cc.
      : Observer(/*has_string=*/true, /*has_tensor=*/true),
        iig_obs_type_(iig_obs_type) {}
Member Function Documentation
StringFrom()
std::string open_spiel::leduc_poker::LeducObserver::StringFrom (const State & observed_state, int player) const inline override virtual
Implements open_spiel::Observer.
Definition at line 195 of file leduc_poker.cc.
{
    auto& state = open_spiel::down_cast<const LeducState&>(observed_state);
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, state.num_players_);
    std::string result;
    // Private card(s).
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      absl::StrAppend(&result, "[Observer: ", player, "]");
      absl::StrAppend(&result, "[Private: ", state.private_cards_[player], "]");
    } else if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers) {
      absl::StrAppend(
          &result, "[Privates: ", absl::StrJoin(state.private_cards_, ""), "]");
    }
    // Public info. Not all of this is strictly necessary, but it makes the
    // string easier to understand.
    if (iig_obs_type_.public_info) {
      absl::StrAppend(&result, "[Round ", state.round_, "]");
      absl::StrAppend(&result, "[Player: ", state.cur_player_, "]");
      absl::StrAppend(&result, "[Pot: ", state.pot_, "]");
      absl::StrAppend(&result, "[Money: ", absl::StrJoin(state.money_, " "),
                      "]");
      if (state.public_card_ != kInvalidCard) {
        absl::StrAppend(&result, "[Public: ", state.public_card_, "]");
      }
      if (iig_obs_type_.perfect_recall) {
        // Betting Sequence (for the perfect recall case)
        absl::StrAppend(
            &result, "[Round1: ", absl::StrJoin(state.round1_sequence_, " "),
            "][Round2: ", absl::StrJoin(state.round2_sequence_, " "), "]");
      } else {
        // Pot contributions (imperfect recall)
        absl::StrAppend(&result, "[Ante: ", absl::StrJoin(state.ante_, " "),
                        "]");
      }
    }
    // Done.
    return result;
  }
References open_spiel::down_cast(), open_spiel::kAllPlayers, open_spiel::leduc_poker::kInvalidCard, open_spiel::kSinglePlayer, open_spiel::IIGObservationType::perfect_recall, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, state, absl::StrAppend(), and absl::StrJoin().
WriteAllPlayerCards()
static void open_spiel::leduc_poker::LeducObserver::WriteAllPlayerCards (const LeducState & state, Allocator * allocator) inline static
Definition at line 115 of file leduc_poker.cc.
{
    auto out = allocator->Get("private_cards",
                              {state.num_players_, state.NumObservableCards()});
    for (int p = 0; p < state.num_players_; ++p) {
      int card = state.private_cards_[p];
      if (card != kInvalidCard) out.at(p, state.private_cards_[p]) = 1;
    }
  }
References open_spiel::Allocator::Get(), open_spiel::leduc_poker::kInvalidCard, out, and state.
Referenced by WriteTensor().
WriteBettingSequence()
static void open_spiel::leduc_poker::LeducObserver::WriteBettingSequence (const LeducState & state, Allocator * allocator) inline static
Definition at line 135 of file leduc_poker.cc.
{
    const int kNumRounds = 2;
    const int kBitsPerAction = 2;
    const int max_bets_per_round = state.MaxBetsPerRound();
    auto out = allocator->Get("betting",
                              {kNumRounds, max_bets_per_round, kBitsPerAction});
    for (int round : {0, 1}) {
      const auto& bets =
          (round == 0) ? state.round1_sequence_ : state.round2_sequence_;
      for (int i = 0; i < bets.size(); ++i) {
        if (bets[i] == ActionType::kCall) {
          out.at(round, i, 0) = 1;  // Encode call as 10.
        } else if (bets[i] == ActionType::kRaise) {
          out.at(round, i, 1) = 1;  // Encode raise as 01.
        }
      }
    }
  }
References open_spiel::Allocator::Get(), i, open_spiel::leduc_poker::kCall, open_spiel::leduc_poker::kRaise, out, and state.
Referenced by WriteTensor().
WriteCommunityCard()
static void open_spiel::leduc_poker::LeducObserver::WriteCommunityCard (const LeducState & state, Allocator * allocator) inline static
Definition at line 126 of file leduc_poker.cc.
{
    auto out = allocator->Get("community_card", {state.NumObservableCards()});
    if (state.public_card_ != kInvalidCard) {
      out.at(state.public_card_) = 1;
    }
  }
References open_spiel::SpanTensor::at(), open_spiel::Allocator::Get(), open_spiel::leduc_poker::kInvalidCard, out, and state.
Referenced by WriteTensor().
WriteObservingPlayer()
static void open_spiel::leduc_poker::LeducObserver::WriteObservingPlayer (const LeducState & state, int player, Allocator * allocator) inline static
Definition at line 100 of file leduc_poker.cc.
{
    auto out = allocator->Get("player", {state.num_players_});
    out.at(player) = 1;
  }
References open_spiel::SpanTensor::at(), open_spiel::Allocator::Get(), out, player, and state.
Referenced by WriteTensor().
WritePotContribution()
static void open_spiel::leduc_poker::LeducObserver::WritePotContribution (const LeducState & state, Allocator * allocator) inline static
Definition at line 156 of file leduc_poker.cc.
{
    auto out = allocator->Get("pot_contribution", {state.num_players_});
    for (auto p = Player{0}; p < state.num_players_; p++) {
      out.at(p) = state.ante_[p];
    }
  }
References open_spiel::SpanTensor::at(), open_spiel::Allocator::Get(), out, and state.
Referenced by WriteTensor().
WriteSinglePlayerCard()
static void open_spiel::leduc_poker::LeducObserver::WriteSinglePlayerCard (const LeducState & state, int player, Allocator * allocator) inline static
Definition at line 107 of file leduc_poker.cc.
{
    auto out = allocator->Get("private_card", {state.NumObservableCards()});
    int card = state.private_cards_[player];
    if (card != kInvalidCard) out.at(card) = 1;
  }
References open_spiel::Allocator::Get(), open_spiel::leduc_poker::kInvalidCard, out, player, and state.
Referenced by WriteTensor().
WriteTensor()
void open_spiel::leduc_poker::LeducObserver::WriteTensor (const State & observed_state, int player, Allocator * allocator) const inline override virtual
Implements open_spiel::Observer.
Definition at line 167 of file leduc_poker.cc.
{
    auto& state = open_spiel::down_cast<const LeducState&>(observed_state);
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, state.num_players_);
    // Observing player.
    WriteObservingPlayer(state, player, allocator);
    // Private card(s).
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      WriteSinglePlayerCard(state, player, allocator);
    } else if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers) {
      WriteAllPlayerCards(state, allocator);
    }
    // Public information.
    if (iig_obs_type_.public_info) {
      WriteCommunityCard(state, allocator);
      iig_obs_type_.perfect_recall ? WriteBettingSequence(state, allocator)
                                   : WritePotContribution(state, allocator);
    }
  }
References open_spiel::down_cast(), open_spiel::kAllPlayers, open_spiel::kSinglePlayer, open_spiel::IIGObservationType::perfect_recall, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, state, WriteAllPlayerCards(), WriteBettingSequence(), WriteCommunityCard(), WriteObservingPlayer(), WritePotContribution(), and WriteSinglePlayerCard().
The documentation for this class was generated from the following file:
open_spiel/games/leduc_poker/leduc_poker.cc