open spiel: absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift > Class Template Reference
absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift > Class Template Reference
#include <raw_hash_set.h>
Public Member Functions
NonIterableBitMask (T mask)
operator bool () const
uint32_t LowestBitSet () const
uint32_t HighestBitSet () const
uint32_t TrailingZeros () const
uint32_t LeadingZeros () const
Public Attributes
T mask_
Detailed Description
template<class T, int SignificantBits, int Shift = 0>
class absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >
Definition at line 354 of file raw_hash_set.h.
Constructor & Destructor Documentation
NonIterableBitMask()
template<class T , int SignificantBits, int Shift = 0> absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::NonIterableBitMask (T mask) inline explicit
Definition at line 356 of file raw_hash_set.h.
: mask_(mask) {}
Member Function Documentation
HighestBitSet()
template<class T , int SignificantBits, int Shift = 0> uint32_t absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::HighestBitSet () const inline
Definition at line 366 of file raw_hash_set.h.
{
    return static_cast<uint32_t>((bit_width(mask_) - 1) >> Shift);
  }
References absl::bit_width(), and absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::mask_.
LeadingZeros()
template<class T , int SignificantBits, int Shift = 0> uint32_t absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::LeadingZeros () const inline
Definition at line 376 of file raw_hash_set.h.
{
    constexpr int total_significant_bits = SignificantBits << Shift;
    constexpr int extra_bits = sizeof(T) * 8 - total_significant_bits;
    return static_cast<uint32_t>(countl_zero(mask_ << extra_bits)) >> Shift;
  }
References absl::countl_zero(), and absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::mask_.
LowestBitSet()
template<class T , int SignificantBits, int Shift = 0> uint32_t absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::LowestBitSet () const inline
Definition at line 361 of file raw_hash_set.h.
{
    return container_internal::TrailingZeros(mask_) >> Shift;
  }
References absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::mask_, and absl::container_internal::TrailingZeros().
Referenced by absl::container_internal::BitMask< T, SignificantBits, Shift >::operator*().
operator bool()
template<class T , int SignificantBits, int Shift = 0> absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::operator bool () const inline explicit
Definition at line 358 of file raw_hash_set.h.
{ return this->mask_ != 0; }
References absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::mask_.
TrailingZeros()
template<class T , int SignificantBits, int Shift = 0> uint32_t absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::TrailingZeros () const inline
Definition at line 371 of file raw_hash_set.h.
{
    return container_internal::TrailingZeros(mask_) >> Shift;
  }
References absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::mask_, and absl::container_internal::TrailingZeros().
Member Data Documentation
mask_
template<class T , int SignificantBits, int Shift = 0> T absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::mask_
Definition at line 382 of file raw_hash_set.h.
Referenced by absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::HighestBitSet(), absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::LeadingZeros(), absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::LowestBitSet(), absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::operator bool(), and absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::TrailingZeros().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/raw_hash_set.h