open spiel: open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy Class Reference
open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy Class Reference
Public Member Functions
__init__ (self, dynamic_routing.DynamicRoutingGame game, policy.Policy mfg_policy)
Dict[int, float] action_probabilities (self, dynamic_routing.DynamicRoutingGameState state, player_id=None)
Public Member Functions inherited from open_spiel.python.policy.Policy
__call__ (self, state, player_id=None)
to_tabular (self, states=None)
Protected Member Functions
mean_field_routing_game.MeanFieldRoutingGameState _convert_state_to_mean_field_state (self, dynamic_routing.DynamicRoutingGameState n_player_state, int player_id)
Protected Attributes
_mfg_policy
_mfg_empty_state
_state_memoization
Additional Inherited Members
Public Attributes inherited from open_spiel.python.policy.Policy
game
player_ids
Detailed Description
Policy that apply mean field policy to N player game for dynamic routing.
Attributes:
  _mfg_policy: the mean field game policy.
  _mfg_empty_state: an empty mfg state to clone for the state conversion.
  _state_memoization: dictionary to memoize conversion of N player game state
    string representation to the corresponding MFG state.
Definition at line 64 of file dynamic_routing_to_mean_field_game.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy.__init__ (self, dynamic_routing.DynamicRoutingGame game, policy.Policy mfg_policy)
Initializes a uniform random policy for all players in the game.
Reimplemented from open_spiel.python.policy.Policy.
Definition at line 74 of file dynamic_routing_to_mean_field_game.py.
               mfg_policy: policy.Policy):
    """Initializes a uniform random policy for all players in the game."""
    super().__init__(game, list(range(game.num_players())))
    self._mfg_policy = mfg_policy
    self._mfg_empty_state = _create_empty_mfg_state(game)
    self._state_memoization = {}
References open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy.__init__().
Referenced by open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy.__init__().
Member Function Documentation
_convert_state_to_mean_field_state()
mean_field_routing_game.MeanFieldRoutingGameState open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._convert_state_to_mean_field_state (self, dynamic_routing.DynamicRoutingGameState n_player_state, int player_id) protected
Convert a N player state to a mean field state.
Definition at line 82 of file dynamic_routing_to_mean_field_game.py.
      player_id: int) -> mean_field_routing_game.MeanFieldRoutingGameState:
    """Convert a N player state to a mean field state."""
    assert player_id >= 0, "player_id should be a positive integer."
    # create a string key for N player game.
    state_key = (str(n_player_state), player_id)
    mfg_state = self._state_memoization.get(state_key)
    if mfg_state is not None:
      return mfg_state
    mfg_state = self._mfg_empty_state.clone()
    # pylint:disable=protected-access
    mfg_state._is_chance_init = False
    mfg_state._current_time_step = n_player_state._current_time_step
    mfg_state._is_terminal = n_player_state._is_terminal
    mfg_state._player_id = pyspiel.PlayerId.DEFAULT_PLAYER_ID
    mfg_state._waiting_time = n_player_state._waiting_times[player_id]
    mfg_state._vehicle_at_destination = (
        player_id in n_player_state._vehicle_at_destination)
    mfg_state._vehicle_destination = n_player_state._vehicle_destinations[
        player_id]
    mfg_state._vehicle_final_arrival_time = (
        n_player_state._vehicle_final_arrival_times[player_id])
    mfg_state._vehicle_location = n_player_state._vehicle_locations[player_id]
    mfg_state._vehicle_without_legal_action = (
        player_id in n_player_state._vehicle_without_legal_actions)
    # pylint:enable=protected-access
    self._state_memoization[state_key] = mfg_state
    return mfg_state
References open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._mfg_empty_state, and open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._state_memoization.
Referenced by open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy.action_probabilities().
action_probabilities()
Dict[int, float] open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy.action_probabilities (self, dynamic_routing.DynamicRoutingGameState state, player_id = None)
Returns the mean field action to apply in the N player state.
Args:
  state: An N player dynamic routing game state.
  player_id: the player id for which we want an action. Should be given to
    the function.
Returns:
  A `dict` of `{action: probability}` for the specified player in the
  supplied state.
Reimplemented from open_spiel.python.policy.Policy.
Definition at line 112 of file dynamic_routing_to_mean_field_game.py.
                           player_id=None) -> Dict[int, float]:
    """Returns the mean field action to apply in the N player state.
    Args:
      state: An N player dynamic routing game state.
      player_id: the player id for which we want an action. Should be given to
        the function.
    Returns:
      A `dict` of `{action: probability}` for the specified player in the
      supplied state.
    """
    assert player_id is not None
    mfg_state = self._convert_state_to_mean_field_state(state, player_id)
    # Due to memoization, action_probabilities should not change mfg_state. In
    # case action_probabilities changes mfg_state, then mfg_state.clone() should
    # be passed to the function.
    return self._mfg_policy.action_probabilities(mfg_state)
References open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._convert_state_to_mean_field_state(), open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._mfg_policy, and open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy.action_probabilities().
Referenced by open_spiel.python.policy.Policy.__call__(), open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy.action_probabilities(), and open_spiel.python.policy.Policy.to_tabular().
Member Data Documentation
_mfg_empty_state
open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._mfg_empty_state protected
Definition at line 79 of file dynamic_routing_to_mean_field_game.py.
Referenced by open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._convert_state_to_mean_field_state().
_mfg_policy
open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._mfg_policy protected
Definition at line 78 of file dynamic_routing_to_mean_field_game.py.
Referenced by open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy.action_probabilities().
_state_memoization
open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._state_memoization protected
Definition at line 80 of file dynamic_routing_to_mean_field_game.py.
Referenced by open_spiel.python.games.dynamic_routing_to_mean_field_game.DerivedNPlayerPolicyFromMeanFieldPolicy._convert_state_to_mean_field_state().
The documentation for this class was generated from the following file:
open_spiel/python/games/dynamic_routing_to_mean_field_game.py