open spiel: open_spiel::kuhn_poker::KuhnState Class Reference
open_spiel::kuhn_poker::KuhnState Class Reference
#include <kuhn_poker.h>
Public Member Functions
KuhnState (std::shared_ptr< const Game > game)
KuhnState (const KuhnState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action move) override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::vector< Action > LegalActions () const override
std::vector< int > hand () const
std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const override
const std::vector< int > & CardDealt () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Friends
class KuhnObserver
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 50 of file kuhn_poker.h.
Constructor & Destructor Documentation
KuhnState() [1/2]
open_spiel::kuhn_poker::KuhnState::KuhnState (std::shared_ptr< const Game > game) explicit
Definition at line 172 of file kuhn_poker.cc.
    : State(game),
      first_bettor_(kInvalidPlayer),
      card_dealt_(game->NumPlayers() + 1, kInvalidPlayer),
      winner_(kInvalidPlayer),
      pot_(kAnte * game->NumPlayers()),
      // How much each player has contributed to the pot, indexed by pid.
      ante_(game->NumPlayers(), kAnte) {}
Referenced by Clone().
KuhnState() [2/2]
open_spiel::kuhn_poker::KuhnState::KuhnState (const KuhnState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::kuhn_poker::KuhnState::ActionToString (Player player, Action move) const override virtual
Implements open_spiel::State.
Definition at line 244 of file kuhn_poker.cc.
{
  if (player == kChancePlayerId)
    return absl::StrCat("Deal:", move);
  else if (move == ActionType::kPass)
    return "Pass";
  else
    return "Bet";
}
References open_spiel::kChancePlayerId, open_spiel::kuhn_poker::kPass, player, and absl::StrCat().
CardDealt()
const std::vector< int > & open_spiel::kuhn_poker::KuhnState::CardDealt () const inline
Definition at line 75 of file kuhn_poker.h.
{ return card_dealt_; }
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::kuhn_poker::KuhnState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 329 of file kuhn_poker.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  std::vector<std::pair<Action, double>> outcomes;
  const double p = 1.0 / (num_players_ + 1 - history_.size());
  for (int card = 0; card < card_dealt_.size(); ++card) {
    if (card_dealt_[card] == kInvalidPlayer) outcomes.push_back({card, p});
  }
  return outcomes;
}
References open_spiel::State::history_, open_spiel::State::IsChanceNode(), open_spiel::kInvalidPlayer, open_spiel::State::num_players_, and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::kuhn_poker::KuhnState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 309 of file kuhn_poker.cc.
{
  return std::unique_ptr<State>(new KuhnState(*this));
}
References KuhnState().
CurrentPlayer()
int open_spiel::kuhn_poker::KuhnState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 181 of file kuhn_poker.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  } else {
    return (history_.size() < num_players_) ? kChancePlayerId
                                            : history_.size() % num_players_;
  }
}
References open_spiel::State::history_, IsTerminal(), open_spiel::kChancePlayerId, open_spiel::kTerminalPlayerId, and open_spiel::State::num_players_.
Referenced by DoApplyAction(), and hand().
DoApplyAction()
void open_spiel::kuhn_poker::KuhnState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 190 of file kuhn_poker.cc.
{
  // Additional book-keeping
  if (history_.size() < num_players_) {
    // Give card `move` to player `history_.size()` (CurrentPlayer will return
    // kChancePlayerId, so we use that instead).
    card_dealt_[move] = history_.size();
  } else if (move == ActionType::kBet) {
    if (first_bettor_ == kInvalidPlayer) first_bettor_ = CurrentPlayer();
    pot_ += 1;
    ante_[CurrentPlayer()] += kAnte;
  }
  // We undo that before exiting the method.
  // This is used in `DidBet`.
  history_.push_back({CurrentPlayer(), move});
  // Check for the game being over.
  const int num_actions = history_.size() - num_players_;
  if (first_bettor_ == kInvalidPlayer && num_actions == num_players_) {
    // Nobody bet; the winner is the person with the highest card dealt,
    // which is either the highest or the next-highest card.
    // Losers lose 1, winner wins 1 * (num_players - 1)
    winner_ = card_dealt_[num_players_];
    if (winner_ == kInvalidPlayer) winner_ = card_dealt_[num_players_ - 1];
  } else if (first_bettor_ != kInvalidPlayer &&
             num_actions == num_players_ + first_bettor_) {
    // There was betting; so the winner is the person with the highest card
    // who stayed in the hand.
    // Check players in turn starting with the highest card.
    for (int card = num_players_; card >= 0; --card) {
      const Player player = card_dealt_[card];
      if (player != kInvalidPlayer && DidBet(player)) {
        winner_ = player;
        break;
      }
    }
    SPIEL_CHECK_NE(winner_, kInvalidPlayer);
  }
  history_.pop_back();
}
References CurrentPlayer(), open_spiel::State::history_, open_spiel::kuhn_poker::kBet, open_spiel::kInvalidPlayer, open_spiel::State::num_players_, player, and SPIEL_CHECK_NE.
hand()
std::vector< int > open_spiel::kuhn_poker::KuhnState::hand () const inline
Definition at line 71 of file kuhn_poker.h.
{ return {card_dealt_[CurrentPlayer()]}; }
References CurrentPlayer().
InformationStateString()
std::string open_spiel::kuhn_poker::KuhnState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 285 of file kuhn_poker.cc.
{
  const KuhnGame& game = open_spiel::down_cast<const KuhnGame&>(*game_);
  return game.info_state_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
InformationStateTensor()
void open_spiel::kuhn_poker::KuhnState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 295 of file kuhn_poker.cc.
{
  ContiguousAllocator allocator(values);
  const KuhnGame& game = open_spiel::down_cast<const KuhnGame&>(*game_);
  game.info_state_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
IsTerminal()
bool open_spiel::kuhn_poker::KuhnState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 270 of file kuhn_poker.cc.
{ return winner_ != kInvalidPlayer; }
References open_spiel::kInvalidPlayer.
Referenced by CurrentPlayer(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::kuhn_poker::KuhnState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 231 of file kuhn_poker.cc.
{
  if (IsTerminal()) return {};
  if (IsChanceNode()) {
    std::vector<Action> actions;
    for (int card = 0; card < card_dealt_.size(); ++card) {
      if (card_dealt_[card] == kInvalidPlayer) actions.push_back(card);
    }
    return actions;
  } else {
    return {ActionType::kPass, ActionType::kBet};
  }
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::kuhn_poker::kBet, open_spiel::kInvalidPlayer, and open_spiel::kuhn_poker::kPass.
ObservationString()
std::string open_spiel::kuhn_poker::KuhnState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 290 of file kuhn_poker.cc.
{
  const KuhnGame& game = open_spiel::down_cast<const KuhnGame&>(*game_);
  return game.default_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
ObservationTensor()
void open_spiel::kuhn_poker::KuhnState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 302 of file kuhn_poker.cc.
{
  ContiguousAllocator allocator(values);
  const KuhnGame& game = open_spiel::down_cast<const KuhnGame&>(*game_);
  game.default_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
ResampleFromInfostate()
std::unique_ptr< State > open_spiel::kuhn_poker::KuhnState::ResampleFromInfostate (int player_id, std::function< double()> rng) const override virtual
Reimplemented from open_spiel::State.
Definition at line 351 of file kuhn_poker.cc.
{
  std::unique_ptr<State> state = game_->NewInitialState();
  Action player_chance = history_.at(player_id).action;
  for (int p = 0; p < game_->NumPlayers(); ++p) {
    if (p == history_.size()) return state;
    if (p == player_id) {
      state->ApplyAction(player_chance);
    } else {
      Action other_chance = player_chance;
      while (other_chance == player_chance) {
        other_chance = SampleAction(state->ChanceOutcomes(), rng()).first;
      }
      state->ApplyAction(other_chance);
    }
  }
  SPIEL_CHECK_GE(state->CurrentPlayer(), 0);
  if (game_->NumPlayers() == history_.size()) return state;
  for (int i = game_->NumPlayers(); i < history_.size(); ++i) {
    state->ApplyAction(history_.at(i).action);
  }
  return state;
}
References open_spiel::State::game_, open_spiel::State::history_, i, open_spiel::SampleAction(), SPIEL_CHECK_GE, and state.
Returns()
std::vector< double > open_spiel::kuhn_poker::KuhnState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 272 of file kuhn_poker.cc.
{
  if (!IsTerminal()) {
    return std::vector<double>(num_players_, 0.0);
  }
  std::vector<double> returns(num_players_);
  for (auto player = Player{0}; player < num_players_; ++player) {
    const int bet = DidBet(player) ? 2 : 1;
    returns[player] = (player == winner_) ? (pot_ - bet) : -bet;
  }
  return returns;
}
References IsTerminal(), open_spiel::State::num_players_, and player.
ToString()
std::string open_spiel::kuhn_poker::KuhnState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 253 of file kuhn_poker.cc.
{
  // The deal: space separated card per player
  std::string str;
  for (int i = 0; i < history_.size() && i < num_players_; ++i) {
    if (!str.empty()) str.push_back(' ');
    absl::StrAppend(&str, history_[i].action);
  }
  // The betting history: p for Pass, b for Bet
  if (history_.size() > num_players_) str.push_back(' ');
  for (int i = num_players_; i < history_.size(); ++i) {
    str.push_back(history_[i].action ? 'b' : 'p');
  }
  return str;
}
References action, open_spiel::State::history_, i, open_spiel::State::num_players_, and absl::StrAppend().
UndoAction()
void open_spiel::kuhn_poker::KuhnState::UndoAction (Player player, Action move) override virtual
Reimplemented from open_spiel::State.
Definition at line 313 of file kuhn_poker.cc.
{
  if (history_.size() <= num_players_) {
    // Undoing a deal move.
    card_dealt_[move] = kInvalidPlayer;
  } else {
    // Undoing a bet / pass.
    if (move == ActionType::kBet) {
      pot_ -= 1;
      if (player == first_bettor_) first_bettor_ = kInvalidPlayer;
    }
    winner_ = kInvalidPlayer;
  }
  history_.pop_back();
  --move_number_;
}
References open_spiel::State::history_, open_spiel::kuhn_poker::kBet, open_spiel::kInvalidPlayer, open_spiel::State::move_number_, open_spiel::State::num_players_, and player.
Friends And Related Symbol Documentation
KuhnObserver
friend class KuhnObserver friend
Definition at line 81 of file kuhn_poker.h.
The documentation for this class was generated from the following files:
open_spiel/games/kuhn_poker/kuhn_poker.h
open_spiel/games/kuhn_poker/kuhn_poker.cc