open spiel: open_spiel::solitaire::Tableau Class Reference
open_spiel::solitaire::Tableau Class Reference
#include <solitaire.h>
Public Member Functions
Tableau (PileID id)
std::vector< Card > Sources () const override
std::vector< Card > Targets () const override
std::vector< Card > Split (Card card) override
void Reveal (Card card_to_reveal) override
Public Member Functions inherited from open_spiel::solitaire::Pile
Pile (LocationType type, PileID id, SuitType suit=SuitType::kNone)
virtual ~Pile ()=default
bool GetIsEmpty () const
SuitType GetSuit () const
LocationType GetType () const
PileID GetID () const
Card GetFirstCard () const
Card GetLastCard () const
std::vector< Card > GetCards () const
void SetCards (std::vector< Card > new_cards)
void Extend (std::vector< Card > source_cards)
std::string ToString (bool colored=true) const
Additional Inherited Members
Protected Attributes inherited from open_spiel::solitaire::Pile
std::vector< Card > cards_
const LocationType type_
const SuitType suit_
const PileID id_
const int max_size_
Detailed Description
Definition at line 177 of file solitaire.h.
Constructor & Destructor Documentation
Tableau()
open_spiel::solitaire::Tableau::Tableau (PileID id) explicit
Definition at line 633 of file solitaire.cc.
    : Pile(LocationType::kTableau, id, SuitType::kNone) {}
Member Function Documentation
Reveal()
void open_spiel::solitaire::Tableau::Reveal (Card card_to_reveal) override virtual
Reimplemented from open_spiel::solitaire::Pile.
Definition at line 685 of file solitaire.cc.
{
  cards_.back().SetRank(card_to_reveal.GetRank());
  cards_.back().SetSuit(card_to_reveal.GetSuit());
  cards_.back().SetHidden(false);
}
References open_spiel::solitaire::Pile::cards_, open_spiel::solitaire::Card::GetRank(), open_spiel::solitaire::Card::GetSuit(), and open_spiel::solitaire::Card::SetRank().
Sources()
std::vector< Card > open_spiel::solitaire::Tableau::Sources () const override virtual
Reimplemented from open_spiel::solitaire::Pile.
Definition at line 651 of file solitaire.cc.
{
  std::vector<Card> sources;
  sources.reserve(kMaxSourcesTableau);
  if (!cards_.empty()) {
    for (const auto& card : cards_) {
      if (!card.GetHidden()) {
        sources.push_back(card);
      }
    }
    return sources;
  } else {
    return {};
  }
}
References open_spiel::solitaire::Pile::cards_.
Split()
std::vector< Card > open_spiel::solitaire::Tableau::Split (Card card) override virtual
Reimplemented from open_spiel::solitaire::Pile.
Definition at line 666 of file solitaire.cc.
{
  std::vector<Card> split_cards;
  if (!cards_.empty()) {
    bool split_flag = false;
    for (auto it = cards_.begin(); it != cards_.end();) {
      if (*it == card) {
        split_flag = true;
      }
      if (split_flag) {
        split_cards.push_back(*it);
        it = cards_.erase(it);
      } else {
        ++it;
      }
    }
  }
  return split_cards;
}
References open_spiel::solitaire::Pile::cards_.
Targets()
std::vector< Card > open_spiel::solitaire::Tableau::Targets () const override virtual
Reimplemented from open_spiel::solitaire::Pile.
Definition at line 636 of file solitaire.cc.
{
  if (!cards_.empty()) {
    auto back_card = cards_.back();
    if (!back_card.GetHidden()) {
      return {cards_.back()};
    } else {
      return {};
    }
  } else {
    // Empty tableau card (no rank or suit)
    return {
        Card(false, SuitType::kNone, RankType::kNone, LocationType::kTableau)};
  }
}
References open_spiel::solitaire::Pile::cards_, open_spiel::solitaire::kNone, and open_spiel::solitaire::kTableau.
The documentation for this class was generated from the following files:
open_spiel/games/solitaire/solitaire.h
open_spiel/games/solitaire/solitaire.cc