open spiel: open_spiel::tensor_game::TensorState Class Reference
open_spiel::tensor_game::TensorState Class Reference
#include <tensor_game.h>
Public Member Functions
TensorState (std::shared_ptr< const Game > game)
TensorState (const TensorState &)=default
std::vector< Action > LegalActions (Player player) const override
std::string ToString () const override
std::string ActionToString (Player player, Action action_id) const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
Public Member Functions inherited from open_spiel::NFGState
NFGState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const final
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyActions (const std::vector< Action > &moves) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyAction (Action action_id)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 174 of file tensor_game.h.
Constructor & Destructor Documentation
TensorState() [1/2]
open_spiel::tensor_game::TensorState::TensorState (std::shared_ptr< const Game > game) explicit
Definition at line 75 of file tensor_game.cc.
    : NFGState(game),
      tensor_game_(static_cast<const TensorGame*>(game.get())) {}
Referenced by Clone().
TensorState() [2/2]
open_spiel::tensor_game::TensorState::TensorState (const TensorState &) explicit default
Member Function Documentation
ActionToString()
std::string open_spiel::tensor_game::TensorState::ActionToString (Player player, Action action_id) const inline override virtual
Implements open_spiel::State.
Definition at line 192 of file tensor_game.h.
{
    if (player == kSimultaneousPlayerId)
      return FlatJointActionToString(action_id);
    else
      return tensor_game_->ActionName(player, action_id);
  }
References open_spiel::tensor_game::TensorGame::ActionName(), open_spiel::SimMoveState::FlatJointActionToString(), open_spiel::kSimultaneousPlayerId, and player.
Clone()
std::unique_ptr< State > open_spiel::tensor_game::TensorState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 211 of file tensor_game.h.
{
    return std::unique_ptr<State>(new TensorState(*this));
  }
References TensorState().
DoApplyActions()
void open_spiel::tensor_game::TensorState::DoApplyActions (const std::vector< Action > & moves) inline override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 216 of file tensor_game.h.
{
    SPIEL_CHECK_EQ(moves.size(), NumPlayers());
    for (Player player = 0; player < NumPlayers(); player++) {
      SPIEL_CHECK_GE(moves[player], 0);
      SPIEL_CHECK_LT(moves[player], tensor_game_->Shape()[player]);
    }
    joint_move_ = moves;
  }
References open_spiel::State::NumPlayers(), player, open_spiel::tensor_game::TensorGame::Shape(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::tensor_game::TensorState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 199 of file tensor_game.h.
{ return !joint_move_.empty(); }
Referenced by LegalActions(), Returns(), and ToString().
LegalActions()
std::vector< Action > open_spiel::tensor_game::TensorState::LegalActions (Player player) const inline override virtual
Implements open_spiel::SimMoveState.
Definition at line 179 of file tensor_game.h.
{
    if (IsTerminal()) return {};
    if (player == kSimultaneousPlayerId) {
      return LegalFlatJointActions();
    } else {
      std::vector<Action> moves(tensor_game_->Shape()[player]);
      std::iota(moves.begin(), moves.end(), 0);  // fill with values 0...n-1
      return moves;
    }
  }
References IsTerminal(), open_spiel::kSimultaneousPlayerId, open_spiel::SimMoveState::LegalFlatJointActions(), player, and open_spiel::tensor_game::TensorGame::Shape().
Returns()
std::vector< double > open_spiel::tensor_game::TensorState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 201 of file tensor_game.h.
{
    std::vector<double> returns(NumPlayers());
    if (IsTerminal()) {
      for (Player player = 0; player < returns.size(); player++) {
        returns[player] = tensor_game_->PlayerUtility(player, joint_move_);
      }
    }
    return returns;
  }
References IsTerminal(), open_spiel::State::NumPlayers(), player, and open_spiel::tensor_game::TensorGame::PlayerUtility().
Referenced by ToString().
ToString()
std::string open_spiel::tensor_game::TensorState::ToString () const override virtual
Reimplemented from open_spiel::NFGState.
Definition at line 79 of file tensor_game.cc.
{
  std::string result = "";
  absl::StrAppend(&result, "Terminal? ", IsTerminal() ? "true" : "false", "\n");
  if (IsTerminal()) {
    absl::StrAppend(&result, "History: ", HistoryString(), "\n");
    absl::StrAppend(&result, "Returns: ", absl::StrJoin(Returns(), ","), "\n");
  }
  return result;
}
References open_spiel::State::HistoryString(), IsTerminal(), Returns(), absl::StrAppend(), and absl::StrJoin().
The documentation for this class was generated from the following files:
open_spiel/tensor_game.h
open_spiel/tensor_game.cc