open spiel: absl::str_format_internal::UnboundConversion::InputValue Class Reference
absl::str_format_internal::UnboundConversion::InputValue Class Reference
#include <constexpr_parser.h>
Public Member Functions
constexpr void set_value (int value)
constexpr int value () const
constexpr void set_from_arg (int value)
constexpr bool is_from_arg () const
constexpr int get_from_arg () const
Detailed Description
Definition at line 42 of file constexpr_parser.h.
Member Function Documentation
get_from_arg()
int absl::str_format_internal::UnboundConversion::InputValue::get_from_arg () const inline constexpr
Definition at line 60 of file constexpr_parser.h.
{
      assert(is_from_arg());
      return -value_ - 1;
    }
References is_from_arg().
is_from_arg()
bool absl::str_format_internal::UnboundConversion::InputValue::is_from_arg () const inline constexpr
Definition at line 59 of file constexpr_parser.h.
{ return value_ < -1; }
Referenced by get_from_arg().
set_from_arg()
void absl::str_format_internal::UnboundConversion::InputValue::set_from_arg (int value) inline constexpr
Definition at line 55 of file constexpr_parser.h.
{
      assert(value > 0);
      value_ = -value - 1;
    }
set_value()
void absl::str_format_internal::UnboundConversion::InputValue::set_value (int value) inline constexpr
Definition at line 44 of file constexpr_parser.h.
{
      assert(value >= 0);
      value_ = value;
    }
References value().
Referenced by open_spiel.python.mfg.value.ValueFunction::add_value().
value()
int absl::str_format_internal::UnboundConversion::InputValue::value () const inline constexpr
Definition at line 48 of file constexpr_parser.h.
{ return value_; }
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), set_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/str_format/constexpr_parser.h