open spiel: absl::Notification Class Reference
absl::Notification Class Reference
#include <notification.h>
Public Member Functions
Notification ()
Notification (bool prenotify)
Notification (const Notification &)=delete
Notification & operator= (const Notification &)=delete
~Notification ()
ABSL_MUST_USE_RESULT bool HasBeenNotified () const
void WaitForNotification () const
bool WaitForNotificationWithTimeout (absl::Duration timeout) const
bool WaitForNotificationWithDeadline (absl::Time deadline) const
void Notify ()
Detailed Description
Definition at line 65 of file notification.h.
Constructor & Destructor Documentation
Notification() [1/3]
absl::Notification::Notification () inline
Definition at line 68 of file notification.h.
: notified_yet_(false) {}
Notification() [2/3]
absl::Notification::Notification (bool prenotify) inline explicit
Definition at line 69 of file notification.h.
: notified_yet_(prenotify) {}
Notification() [3/3]
absl::Notification::Notification (const Notification &) delete
~Notification()
absl::Notification::~Notification ()
Definition at line 41 of file notification.cc.
{
  // Make sure that the thread running Notify() exits before the object is
  // destructed.
  MutexLock l(&this->mutex_);
}
Member Function Documentation
HasBeenNotified()
ABSL_MUST_USE_RESULT bool absl::Notification::HasBeenNotified () const inline
Definition at line 77 of file notification.h.
{
    return HasBeenNotifiedInternal(&this->notified_yet_);
  }
Notify()
ABSL_NAMESPACE_BEGIN void absl::Notification::Notify ()
Definition at line 26 of file notification.cc.
{
  MutexLock l(&this->mutex_);
#ifndef NDEBUG
  if (ABSL_PREDICT_FALSE(notified_yet_.load(std::memory_order_relaxed))) {
    ABSL_RAW_LOG(
        FATAL,
        "Notify() method called more than once for Notification object %p",
        static_cast<void *>(this));
  }
#endif
  notified_yet_.store(true, std::memory_order_release);
}
References ABSL_PREDICT_FALSE, and ABSL_RAW_LOG.
operator=()
Notification & absl::Notification::operator= (const Notification &) delete
WaitForNotification()
void absl::Notification::WaitForNotification () const
Definition at line 47 of file notification.cc.
{
  if (!HasBeenNotifiedInternal(&this->notified_yet_)) {
    this->mutex_.LockWhen(Condition(&HasBeenNotifiedInternal,
                                    &this->notified_yet_));
    this->mutex_.Unlock();
  }
}
References absl::Mutex::LockWhen(), and absl::Mutex::Unlock().
WaitForNotificationWithDeadline()
bool absl::Notification::WaitForNotificationWithDeadline (absl::Time deadline) const
Definition at line 66 of file notification.cc.
{
  bool notified = HasBeenNotifiedInternal(&this->notified_yet_);
  if (!notified) {
    notified = this->mutex_.LockWhenWithDeadline(
        Condition(&HasBeenNotifiedInternal, &this->notified_yet_), deadline);
    this->mutex_.Unlock();
  }
  return notified;
}
References absl::Mutex::LockWhenWithDeadline(), and absl::Mutex::Unlock().
WaitForNotificationWithTimeout()
bool absl::Notification::WaitForNotificationWithTimeout (absl::Duration timeout) const
Definition at line 55 of file notification.cc.
{
  bool notified = HasBeenNotifiedInternal(&this->notified_yet_);
  if (!notified) {
    notified = this->mutex_.LockWhenWithTimeout(
        Condition(&HasBeenNotifiedInternal, &this->notified_yet_), timeout);
    this->mutex_.Unlock();
  }
  return notified;
}
References absl::Mutex::LockWhenWithTimeout(), and absl::Mutex::Unlock().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/synchronization/notification.h
open_spiel/abseil-cpp/absl/synchronization/notification.cc