open spiel: open_spiel::breakthrough::BreakthroughState Class Reference
open_spiel::breakthrough::BreakthroughState Class Reference
#include <breakthrough.h>
Public Member Functions
BreakthroughState (std::shared_ptr< const Game > game, int rows, int cols)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
bool InBounds (int r, int c) const
void SetBoard (int r, int c, CellState cs)
void SetPieces (int idx, int value)
CellState board (int row, int col) const
int pieces (int idx) const
int rows () const
int cols () const
std::vector< Action > LegalActions () const override
std::string Serialize () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 51 of file breakthrough.h.
Constructor & Destructor Documentation
BreakthroughState()
open_spiel::breakthrough::BreakthroughState::BreakthroughState (std::shared_ptr< const Game > game, int rows, int cols) explicit
Definition at line 121 of file breakthrough.cc.
    : State(game), rows_(rows), cols_(cols) {
  SPIEL_CHECK_GT(rows_, 1);
  SPIEL_CHECK_GT(cols_, 1);
  board_ = std::vector<CellState>(rows_ * cols_, CellState::kEmpty);
  for (int r = 0; r < rows_; r++) {
    for (int c = 0; c < cols_; c++) {
      // Only use two rows if there are at least 6 rows.
      if (r == 0 || (rows_ >= kNumRowsForFullPieces && r == 1)) {
        SetBoard(r, c, CellState::kBlack);
      } else if (r == (rows_ - 1) ||
                 (rows_ >= kNumRowsForFullPieces && r == (rows_ - 2))) {
        SetBoard(r, c, CellState::kWhite);
      }
    }
  }
  winner_ = kInvalidPlayer;
  pieces_[0] = pieces_[1] = cols_ * (rows_ >= kNumRowsForFullPieces ? 2 : 1);
  cur_player_ = 0;
  total_moves_ = 0;
}
References open_spiel::breakthrough::kBlack, open_spiel::breakthrough::kEmpty, open_spiel::kInvalidPlayer, open_spiel::breakthrough::kWhite, r, SetBoard(), and SPIEL_CHECK_GT.
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::breakthrough::BreakthroughState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 196 of file breakthrough.cc.
{
  std::vector<int> values =
      UnrankActionMixedBase(action, {rows_, cols_, kNumDirections, 2});
  int r1 = values[0];
  int c1 = values[1];
  int dir = values[2];
  bool capture = values[3] == 1;
  int r2 = r1 + kDirRowOffsets[dir];
  int c2 = c1 + kDirColOffsets[dir];
  std::string action_string = "";
  absl::StrAppend(&action_string, ColLabel(c1));
  absl::StrAppend(&action_string, RowLabel(rows_, r1));
  absl::StrAppend(&action_string, ColLabel(c2));
  absl::StrAppend(&action_string, RowLabel(rows_, r2));
  if (capture) {
    absl::StrAppend(&action_string, "*");
  }
  return action_string;
}
References action, dir, absl::StrAppend(), open_spiel::UnrankActionMixedBase(), and values.
board()
CellState open_spiel::breakthrough::BreakthroughState::board (int row, int col) const inline
Definition at line 69 of file breakthrough.h.
{ return board_[row * cols_ + col]; }
Referenced by open_spiel.python.games.tic_tac_toe.TicTacToeState::__str__(), open_spiel.python.games.tic_tac_toe.TicTacToeState::_apply_action(), open_spiel.python.games.tic_tac_toe.TicTacToeState::_legal_actions(), DoApplyAction(), LegalActions(), Serialize(), ToString(), and UndoAction().
Clone()
std::unique_ptr< State > open_spiel::breakthrough::BreakthroughState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 379 of file breakthrough.cc.
{
  return std::unique_ptr<State>(new BreakthroughState(*this));
}
References BreakthroughState().
cols()
int open_spiel::breakthrough::BreakthroughState::cols () const inline
Definition at line 72 of file breakthrough.h.
{ return cols_; }
CurrentPlayer()
int open_spiel::breakthrough::BreakthroughState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 146 of file breakthrough.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  } else {
    return cur_player_;
  }
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by LegalActions().
DoApplyAction()
void open_spiel::breakthrough::BreakthroughState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 154 of file breakthrough.cc.
{
  std::vector<int> values =
      UnrankActionMixedBase(action, {rows_, cols_, kNumDirections, 2});
  int r1 = values[0];
  int c1 = values[1];
  int dir = values[2];
  bool capture = values[3] == 1;
  int r2 = r1 + kDirRowOffsets[dir];
  int c2 = c1 + kDirColOffsets[dir];
  SPIEL_CHECK_TRUE(InBounds(r1, c1));
  SPIEL_CHECK_TRUE(InBounds(r2, c2));
  // Remove pieces if captured.
  if (board(r2, c2) == CellState::kWhite) {
    pieces_[StateToPlayer(CellState::kWhite)]--;
    SPIEL_CHECK_EQ(board(r1, c1), CellState::kBlack);
    SPIEL_CHECK_EQ(cur_player_, StateToPlayer(CellState::kBlack));
  } else if (board(r2, c2) == CellState::kBlack) {
    pieces_[StateToPlayer(CellState::kBlack)]--;
    SPIEL_CHECK_EQ(board(r1, c1), CellState::kWhite);
    SPIEL_CHECK_EQ(cur_player_, StateToPlayer(CellState::kWhite));
  }
  // Move the piece.
  if (capture) {
    SPIEL_CHECK_EQ(board(r2, c2), OpponentState(board(r1, c1)));
  }
  SetBoard(r2, c2, board(r1, c1));
  SetBoard(r1, c1, CellState::kEmpty);
  // Check for winner.
  if (cur_player_ == 0 && r2 == (rows_ - 1)) {
    winner_ = 0;
  } else if (cur_player_ == 1 && r2 == 0) {
    winner_ = 1;
  }
  cur_player_ = NextPlayerRoundRobin(cur_player_, kNumPlayers);
  total_moves_++;
}
References action, board(), dir, InBounds(), open_spiel::breakthrough::kBlack, open_spiel::breakthrough::kEmpty, open_spiel::breakthrough::kNumPlayers, open_spiel::breakthrough::kWhite, open_spiel::NextPlayerRoundRobin(), SetBoard(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, open_spiel::UnrankActionMixedBase(), and values.
InBounds()
bool open_spiel::breakthrough::BreakthroughState::InBounds (int r, int c) const
Definition at line 260 of file breakthrough.cc.
{
  return (r >= 0 && r < rows_ && c >= 0 && c < cols_);
}
References r.
Referenced by DoApplyAction(), and LegalActions().
IsTerminal()
bool open_spiel::breakthrough::BreakthroughState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 308 of file breakthrough.cc.
{
  return (winner_ >= 0 || (pieces_[0] == 0 || pieces_[1] == 0));
}
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::breakthrough::BreakthroughState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 219 of file breakthrough.cc.
{
  std::vector<Action> movelist;
  if (IsTerminal()) return movelist;
  const Player player = CurrentPlayer();
  CellState mystate = PlayerToState(player);
  std::vector<int> action_bases = {rows_, cols_, kNumDirections, 2};
  std::vector<int> action_values = {0, 0, 0, 0};
  for (int r = 0; r < rows_; r++) {
    for (int c = 0; c < cols_; c++) {
      if (board(r, c) == mystate) {
        for (int o = 0; o < kNumDirections / 2; o++) {
          int dir = player * kNumDirections / 2 + o;
          int rp = r + kDirRowOffsets[dir];
          int cp = c + kDirColOffsets[dir];
          if (InBounds(rp, cp)) {
            action_values[0] = r;
            action_values[1] = c;
            action_values[2] = dir;
            if (board(rp, cp) == CellState::kEmpty) {
              // Regular move.
              action_values[3] = 0;
              movelist.push_back(
                  RankActionMixedBase(action_bases, action_values));
            } else if ((o == 0 || o == 2) &&
                       board(rp, cp) == OpponentState(mystate)) {
              // Capture move (can only capture diagonally)
              action_values[3] = 1;
              movelist.push_back(
                  RankActionMixedBase(action_bases, action_values));
            }
          }
        }
      }
    }
  }
  return movelist;
}
References board(), CurrentPlayer(), dir, InBounds(), IsTerminal(), open_spiel::breakthrough::kEmpty, o, player, r, and open_spiel::RankActionMixedBase().
ObservationString()
std::string open_spiel::breakthrough::BreakthroughState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 322 of file breakthrough.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::breakthrough::BreakthroughState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 328 of file breakthrough.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<3> view(values, {kCellStates, rows_, cols_}, true);
  for (int r = 0; r < rows_; r++) {
    for (int c = 0; c < cols_; c++) {
      int plane = observation_plane(r, c);
      SPIEL_CHECK_TRUE(plane >= 0 && plane < kCellStates);
      view[{plane, r, c}] = 1.0;
    }
  }
}
References open_spiel::breakthrough::kCellStates, open_spiel::State::num_players_, player, r, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, and values.
pieces()
int open_spiel::breakthrough::BreakthroughState::pieces (int idx) const inline
Definition at line 70 of file breakthrough.h.
{ return pieces_[idx]; }
Referenced by open_spiel::breakthrough::BreakthroughGame::DeserializeState().
Returns()
std::vector< double > open_spiel::breakthrough::BreakthroughState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 312 of file breakthrough.cc.
{
  if (winner_ == 0 || pieces_[1] == 0) {
    return {1.0, -1.0};
  } else if (winner_ == 1 || pieces_[0] == 0) {
    return {-1.0, 1.0};
  } else {
    return {0.0, 0.0};
  }
}
rows()
int open_spiel::breakthrough::BreakthroughState::rows () const inline
Definition at line 71 of file breakthrough.h.
{ return rows_; }
Serialize()
std::string open_spiel::breakthrough::BreakthroughState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 392 of file breakthrough.cc.
{
  std::string str = "";
  for (int r = 0; r < rows_; r++) {
    for (int c = 0; c < cols_; c++) {
      absl::StrAppend(&str, CellToString(board(r, c)));
    }
  }
  return str;
}
References board(), r, and absl::StrAppend().
SetBoard()
void open_spiel::breakthrough::BreakthroughState::SetBoard (int r, int c, CellState cs) inline
Definition at line 67 of file breakthrough.h.
{ board_[r * cols_ + c] = cs; }
References r.
Referenced by BreakthroughState(), open_spiel::breakthrough::BreakthroughGame::DeserializeState(), DoApplyAction(), and UndoAction().
SetPieces()
void open_spiel::breakthrough::BreakthroughState::SetPieces (int idx, int value) inline
Definition at line 68 of file breakthrough.h.
{ pieces_[idx] = value; }
References value.
Referenced by open_spiel::breakthrough::BreakthroughGame::DeserializeState().
ToString()
std::string open_spiel::breakthrough::BreakthroughState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 264 of file breakthrough.cc.
{
  std::string result = "";
  for (int r = 0; r < rows_; r++) {
    absl::StrAppend(&result, RowLabel(rows_, r));
    for (int c = 0; c < cols_; c++) {
      absl::StrAppend(&result, CellToString(board(r, c)));
    }
    result.append("\n");
  }
  absl::StrAppend(&result, " ");
  for (int c = 0; c < cols_; c++) {
    absl::StrAppend(&result, ColLabel(c));
  }
  absl::StrAppend(&result, "\n");
  return result;
}
References board(), r, and absl::StrAppend().
Referenced by ObservationString().
UndoAction()
void open_spiel::breakthrough::BreakthroughState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 344 of file breakthrough.cc.
{
  std::vector<int> values =
      UnrankActionMixedBase(action, {rows_, cols_, kNumDirections, 2});
  int r1 = values[0];
  int c1 = values[1];
  int dir = values[2];
  bool capture = values[3] == 1;
  int r2 = r1 + kDirRowOffsets[dir];
  int c2 = c1 + kDirColOffsets[dir];
  cur_player_ = PreviousPlayerRoundRobin(cur_player_, 2);
  total_moves_--;
  // Undo win status.
  winner_ = kInvalidPlayer;
  // Move back the piece, and put back the opponent's piece if necessary.
  // The move is (r1, c1) -> (r2, c2) where r is row and c is column.
  SetBoard(r1, c1, board(r2, c2));
  SetBoard(r2, c2, CellState::kEmpty);
  if (capture) {
    if (board(r1, c1) == CellState::kWhite) {
      // It was a white move: put back the black piece.
      SetBoard(r2, c2, CellState::kBlack);
      pieces_[kBlackPlayerId]++;
    } else if (board(r1, c1) == CellState::kBlack) {
      // It was a black move: put back the white piece.
      SetBoard(r2, c2, CellState::kWhite);
      pieces_[kWhitePlayerId]++;
    }
  }
  history_.pop_back();
  --move_number_;
}
References action, board(), dir, open_spiel::State::history_, open_spiel::breakthrough::kBlack, open_spiel::breakthrough::kBlackPlayerId, open_spiel::breakthrough::kEmpty, open_spiel::kInvalidPlayer, open_spiel::breakthrough::kWhite, open_spiel::breakthrough::kWhitePlayerId, open_spiel::State::move_number_, open_spiel::PreviousPlayerRoundRobin(), SetBoard(), open_spiel::UnrankActionMixedBase(), and values.
The documentation for this class was generated from the following files:
open_spiel/games/breakthrough/breakthrough.h
open_spiel/games/breakthrough/breakthrough.cc