open spiel: absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator Class Reference
absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator Class Reference
#include <raw_hash_set.h>
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = typename raw_hash_set::value_type
using reference
using pointer = absl::remove_reference_t<reference>*
using difference_type = typename raw_hash_set::difference_type
Public Member Functions
iterator ()
reference operator* () const
pointer operator-> () const
iterator & operator++ ()
iterator operator++ (int)
Friends
class raw_hash_set
bool operator== (const iterator &a, const iterator &b)
bool operator!= (const iterator &a, const iterator &b)
Detailed Description
template<class Policy, class Hash, class Eq, class Alloc>
class absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator
Definition at line 1406 of file raw_hash_set.h.
Member Typedef Documentation
difference_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::difference_type = typename raw_hash_set::difference_type
Definition at line 1416 of file raw_hash_set.h.
iterator_category
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::iterator_category = std::forward_iterator_tag
Definition at line 1410 of file raw_hash_set.h.
pointer
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::pointer = absl::remove_reference_t<reference>*
Definition at line 1415 of file raw_hash_set.h.
reference
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::reference
Initial value:
        absl::conditional_t<PolicyTraits::constant_iterators::value,
                            const value_type&, value_type&>
Definition at line 1412 of file raw_hash_set.h.
value_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::value_type = typename raw_hash_set::value_type
Definition at line 1411 of file raw_hash_set.h.
Constructor & Destructor Documentation
iterator()
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::iterator () inline
Definition at line 1418 of file raw_hash_set.h.
{}
Member Function Documentation
operator*()
template<class Policy , class Hash , class Eq , class Alloc > reference absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator* () const inline
Definition at line 1421 of file raw_hash_set.h.
{
      ABSL_INTERNAL_ASSERT_IS_FULL(ctrl_, generation(), generation_ptr(),
                                   "operator*()");
      return PolicyTraits::element(slot_);
    }
References ABSL_INTERNAL_ASSERT_IS_FULL, absl::container_internal::common_policy_traits< Policy, class >::element(), absl::container_internal::HashSetIteratorGenerationInfoDisabled::generation(), absl::container_internal::HashSetIteratorGenerationInfoDisabled::generation_ptr(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::slot_.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator->().
operator++() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > iterator & absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator++ () inline
Definition at line 1435 of file raw_hash_set.h.
{
      ABSL_INTERNAL_ASSERT_IS_FULL(ctrl_, generation(), generation_ptr(),
                                   "operator++");
      ++ctrl_;
      ++slot_;
      skip_empty_or_deleted();
      return *this;
    }
References ABSL_INTERNAL_ASSERT_IS_FULL, absl::container_internal::HashSetIteratorGenerationInfoDisabled::generation(), absl::container_internal::HashSetIteratorGenerationInfoDisabled::generation_ptr(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::slot_.
operator++() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator++ (int) inline
Definition at line 1444 of file raw_hash_set.h.
{
      auto tmp = *this;
      ++*this;
      return tmp;
    }
operator->()
template<class Policy , class Hash , class Eq , class Alloc > pointer absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator-> () const inline
Definition at line 1428 of file raw_hash_set.h.
{
      ABSL_INTERNAL_ASSERT_IS_FULL(ctrl_, generation(), generation_ptr(),
                                   "operator->");
      return &operator*();
    }
References ABSL_INTERNAL_ASSERT_IS_FULL, absl::container_internal::HashSetIteratorGenerationInfoDisabled::generation(), absl::container_internal::HashSetIteratorGenerationInfoDisabled::generation_ptr(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator*().
Friends And Related Symbol Documentation
operator!=
template<class Policy , class Hash , class Eq , class Alloc > bool operator!= (const iterator & a, const iterator & b) friend
Definition at line 1456 of file raw_hash_set.h.
{
      return !(a == b);
    }
operator==
template<class Policy , class Hash , class Eq , class Alloc > bool operator== (const iterator & a, const iterator & b) friend
Definition at line 1450 of file raw_hash_set.h.
{
      AssertSameContainer(a.ctrl_, b.ctrl_, a.slot_, b.slot_);
      AssertIsValidForComparison(a.ctrl_, a.generation(), a.generation_ptr());
      AssertIsValidForComparison(b.ctrl_, b.generation(), b.generation_ptr());
      return a.ctrl_ == b.ctrl_;
    }
raw_hash_set
template<class Policy , class Hash , class Eq , class Alloc > friend class raw_hash_set friend
Definition at line 1407 of file raw_hash_set.h.
Member Data Documentation
slot_
template<class Policy , class Hash , class Eq , class Alloc > slot_type* absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::slot_
Definition at line 1491 of file raw_hash_set.h.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::extract(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator*(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator++().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/raw_hash_set.h