open spiel: System Class Reference
System Class Reference
#include <System.h>
Public Member Functions
System ()
~System ()
void Reset ()
int RegisterParams (const int nThreads, const int mem_usable_MB)
int RegisterRun (const RunMode r, const boards &bop)
bool IsSingleThreaded () const
bool IsIMPL () const
unsigned NumThreads () const
bool ThreadOK (const int thrId) const
void GetHardware (int &ncores, unsigned long long &kilobytesFree) const
int PreferThreading (const unsigned code)
int RunThreads ()
string str (DDSInfo *info) const
Detailed Description
Definition at line 31 of file System.h.
Constructor & Destructor Documentation
System()
System::System ()
Definition at line 80 of file System.cpp.
{
  System::Reset();
}
References Reset().
~System()
System::~System ()
Definition at line 86 of file System.cpp.
{
}
Member Function Documentation
GetHardware()
void System::GetHardware (int & ncores, unsigned long long & kilobytesFree) const
Definition at line 179 of file System.cpp.
{
  kilobytesFree = 0;
  ncores = 1;
  (void) System::GetCores(ncores);
#if defined(_WIN32) || defined(__CYGWIN__)
  // Using GlobalMemoryStatusEx instead of GlobalMemoryStatus
  // was suggested by Lorne Anderson.
  MEMORYSTATUSEX statex;
  statex.dwLength = sizeof(statex);
  GlobalMemoryStatusEx(&statex);
  kilobytesFree = static_cast<unsigned long long>(
                    statex.ullTotalPhys / 1024);
  SYSTEM_INFO sysinfo;
  GetSystemInfo(&sysinfo);
  ncores = static_cast<int>(sysinfo.dwNumberOfProcessors);
  return;
#endif
#ifdef __APPLE__
  // The code for Mac OS X was suggested by Matthew Kidd.
  // This is physical memory, rather than "free" memory as below
  // for Linux.  Always leave 0.5 GB for the OS and other stuff.
  // It would be better to find free memory (how?) but in practice
  // the number of cores rather than free memory is almost certainly
  // the limit for Macs which have  standardized hardware (whereas
  // say a 32 core Linux server is hardly unusual).
  FILE * fifo = popen("sysctl -n hw.memsize", "r");
  fscanf(fifo, "%lld", &kilobytesFree);
  fclose(fifo);
  kilobytesFree /= 1024;
  if (kilobytesFree > 500000)
  {
    kilobytesFree -= 500000;
  }
  ncores = sysconf(_SC_NPROCESSORS_ONLN);
  return;
#endif
#ifdef __linux__
  // The code for linux was suggested by Antony Lee.
  FILE * fifo = popen(
    "free -k | tail -n+3 | head -n1 | awk '{print $NF}'", "r");
  int ignore = fscanf(fifo, "%llu", &kilobytesFree);
  fclose(fifo);
  ncores = sysconf(_SC_NPROCESSORS_ONLN);
  return;
#endif
}
Referenced by SetResources().
IsIMPL()
bool System::IsIMPL () const
Definition at line 271 of file System.cpp.
{
  return (preferredSystem >= DDS_SYSTEM_THREAD_STLIMPL);
}
References DDS_SYSTEM_THREAD_STLIMPL.
Referenced by SetResources().
IsSingleThreaded()
bool System::IsSingleThreaded () const
Definition at line 265 of file System.cpp.
{
  return (preferredSystem == DDS_SYSTEM_THREAD_BASIC);
}
References DDS_SYSTEM_THREAD_BASIC.
Referenced by SetResources().
NumThreads()
unsigned System::NumThreads () const
Definition at line 277 of file System.cpp.
{
  return static_cast<unsigned>(numThreads);
}
Referenced by CloseDebugFiles(), FreeMemory(), FreeThreadMem(), and InitDebugFiles().
PreferThreading()
int System::PreferThreading (const unsigned code)
Definition at line 289 of file System.cpp.
{
  if (code >= DDS_SYSTEM_THREAD_SIZE)
    return RETURN_THREAD_MISSING;
  if (! availableSystem[code])
    return RETURN_THREAD_MISSING;
  preferredSystem = code;
  return RETURN_NO_FAULT;
}
References DDS_SYSTEM_THREAD_SIZE, RETURN_NO_FAULT, and RETURN_THREAD_MISSING.
Referenced by SetThreading().
RegisterParams()
int System::RegisterParams (const int nThreads, const int mem_usable_MB)
Definition at line 238 of file System.cpp.
{
  // No upper limit -- caveat emptor.
  if (nThreads < 1)
    return RETURN_THREAD_INDEX;
  numThreads = nThreads;
  sysMem_MB = mem_usable_MB;
  return RETURN_NO_FAULT;
}
References RETURN_NO_FAULT, and RETURN_THREAD_INDEX.
Referenced by SetResources().
RegisterRun()
int System::RegisterRun (const RunMode r, const boards & bop)
Definition at line 252 of file System.cpp.
{
  if (mode >= DDS_RUN_SIZE)
    return RETURN_THREAD_MISSING; // Not quite right;
  runCat = mode;
  bop = &bdsIn;
  return RETURN_NO_FAULT;
}
References DDS_RUN_SIZE, RETURN_NO_FAULT, and RETURN_THREAD_MISSING.
Referenced by AnalyseAllPlaysBin(), CalcAllBoardsN(), and SolveAllBoardsN().
Reset()
void System::Reset ()
Definition at line 91 of file System.cpp.
{
  runCat = DDS_RUN_SOLVE;
  numThreads = 1;
  preferredSystem = DDS_SYSTEM_THREAD_BASIC;
  availableSystem.resize(DDS_SYSTEM_THREAD_SIZE);
  availableSystem[DDS_SYSTEM_THREAD_BASIC] = true;
  for (unsigned i = 1; i < DDS_SYSTEM_THREAD_SIZE; i++)
    availableSystem[i] = false;
#ifdef DDS_THREADS_WINAPI
  availableSystem[DDS_SYSTEM_THREAD_WINAPI] = true;
#endif
#ifdef DDS_THREADS_OPENMP
  availableSystem[DDS_SYSTEM_THREAD_OPENMP] = true;
#endif
#ifdef DDS_THREADS_GCD
  availableSystem[DDS_SYSTEM_THREAD_GCD] = true;
#endif
#ifdef DDS_THREADS_BOOST
  availableSystem[DDS_SYSTEM_THREAD_BOOST] = true;
#endif
#ifdef DDS_THREADS_STL
  availableSystem[DDS_SYSTEM_THREAD_STL] = true;
#endif
#ifdef DDS_THREADS_TBB
  availableSystem[DDS_SYSTEM_THREAD_TBB] = true;
#endif
#ifdef DDS_THREADS_STLIMPL
  availableSystem[DDS_SYSTEM_THREAD_STLIMPL] = true;
#endif
#ifdef DDS_THREADS_PPLIMPL
  availableSystem[DDS_SYSTEM_THREAD_PPLIMPL] = true;
#endif
  // Take the first of any multi-threading system defined.
  for (unsigned k = 1; k < availableSystem.size(); k++)
  {
    if (availableSystem[k])
    {
      preferredSystem = k;
      break;
    }
  }
  RunPtrList.resize(DDS_SYSTEM_THREAD_SIZE);
  RunPtrList[DDS_SYSTEM_THREAD_BASIC] = &System::RunThreadsBasic;
  RunPtrList[DDS_SYSTEM_THREAD_WINAPI] = &System::RunThreadsWinAPI;
  RunPtrList[DDS_SYSTEM_THREAD_OPENMP] = &System::RunThreadsOpenMP;
  RunPtrList[DDS_SYSTEM_THREAD_GCD] = &System::RunThreadsGCD;
  RunPtrList[DDS_SYSTEM_THREAD_BOOST] = &System::RunThreadsBoost;
  RunPtrList[DDS_SYSTEM_THREAD_STL] = &System::RunThreadsSTL;
  RunPtrList[DDS_SYSTEM_THREAD_TBB] = &System::RunThreadsTBB;
  RunPtrList[DDS_SYSTEM_THREAD_STLIMPL] =
    &System::RunThreadsSTLIMPL;
  RunPtrList[DDS_SYSTEM_THREAD_PPLIMPL] =
    &System::RunThreadsPPLIMPL;
  CallbackSimpleList.resize(DDS_RUN_SIZE);
  CallbackSimpleList[DDS_RUN_SOLVE] = SolveChunkCommon;
  CallbackSimpleList[DDS_RUN_CALC] = CalcChunkCommon;
  CallbackSimpleList[DDS_RUN_TRACE] = PlayChunkCommon;
  CallbackDuplList.resize(DDS_RUN_SIZE);
  CallbackDuplList[DDS_RUN_SOLVE] = DetectSolveDuplicates;
  CallbackDuplList[DDS_RUN_CALC] = DetectCalcDuplicates;
  CallbackDuplList[DDS_RUN_TRACE] = DetectPlayDuplicates;
  CallbackSingleList.resize(DDS_RUN_SIZE);
  CallbackSingleList[DDS_RUN_SOLVE] = SolveSingleCommon;
  CallbackSingleList[DDS_RUN_CALC] = CalcSingleCommon;
  CallbackSingleList[DDS_RUN_TRACE] = PlaySingleCommon;
  CallbackCopyList.resize(DDS_RUN_SIZE);
  CallbackCopyList[DDS_RUN_SOLVE] = CopySolveSingle;
  CallbackCopyList[DDS_RUN_CALC] = CopyCalcSingle;
  CallbackCopyList[DDS_RUN_TRACE] = CopyPlaySingle;
}
References CalcChunkCommon(), CalcSingleCommon(), CopyCalcSingle(), CopyPlaySingle(), CopySolveSingle(), DDS_RUN_CALC, DDS_RUN_SIZE, DDS_RUN_SOLVE, DDS_RUN_TRACE, DDS_SYSTEM_THREAD_BASIC, DDS_SYSTEM_THREAD_BOOST, DDS_SYSTEM_THREAD_GCD, DDS_SYSTEM_THREAD_OPENMP, DDS_SYSTEM_THREAD_PPLIMPL, DDS_SYSTEM_THREAD_SIZE, DDS_SYSTEM_THREAD_STL, DDS_SYSTEM_THREAD_STLIMPL, DDS_SYSTEM_THREAD_TBB, DDS_SYSTEM_THREAD_WINAPI, DetectCalcDuplicates(), DetectPlayDuplicates(), DetectSolveDuplicates(), i, PlayChunkCommon(), PlaySingleCommon(), SolveChunkCommon(), and SolveSingleCommon().
Referenced by System().
RunThreads()
int System::RunThreads ()
Definition at line 615 of file System.cpp.
{
  fptr = CallbackSimpleList[runCat];
  return (this->*RunPtrList[preferredSystem])();
}
Referenced by AnalyseAllPlaysBin(), CalcAllBoardsN(), and SolveAllBoardsN().
str()
string System::str (DDSInfo * info) const
Definition at line 777 of file System.cpp.
{
  stringstream ss;
  ss << "DDS DLL\n-------\n";
  const string strSystem = System::GetSystem(info->system);
  ss << left << setw(13) << "System" <<
    setw(20) << right << strSystem << "\n";
  const string strBits = System::GetBits(info->numBits);
  ss << left << setw(13) << "Word size" <<
    setw(20) << right << strBits << "\n";
  const string strCompiler = System::GetCompiler(info->compiler);
  ss << left << setw(13) << "Compiler" <<
    setw(20) << right << strCompiler << "\n";
  const string strConstructor = System::GetConstructor(info->constructor);
  ss << left << setw(13) << "Constructor" <<
    setw(20) << right << strConstructor << "\n";
  const string strVersion = System::GetVersion(info->major,
    info->minor, info->patch);
  ss << left << setw(13) << "Version" <<
    setw(20) << right << strVersion << "\n";
  strcpy(info->versionString, strVersion.c_str());
  ss << left << setw(17) << "Memory max (MB)" <<
    setw(16) << right << sysMem_MB << "\n";
  const string stm = to_string(THREADMEM_SMALL_DEF_MB) + "-" +
    to_string(THREADMEM_SMALL_MAX_MB) + " / " +
    to_string(THREADMEM_LARGE_DEF_MB) + "-" +
    to_string(THREADMEM_LARGE_MAX_MB);
  ss << left << setw(17) << "Threads (MB)" <<
    setw(16) << right << stm << "\n";
  System::GetCores(info->numCores);
  ss << left << setw(17) << "Number of cores" <<
    setw(16) << right << info->numCores << "\n";
  info->noOfThreads = numThreads;
  ss << left << setw(17) << "Number of threads" <<
    setw(16) << right << numThreads << "\n";
  const string strThrSizes = System::GetThreadSizes(info->threadSizes);
  ss << left << setw(13) << "Thread sizes" <<
    setw(20) << right << strThrSizes << "\n";
  const string strThreading = System::GetThreading(info->threading);
  ss << left << setw(9) << "Threading" <<
    setw(24) << right << strThreading << "\n";
  const string st = ss.str();
  strcpy(info->systemString, st.c_str());
  return st;
}
References THREADMEM_LARGE_DEF_MB, THREADMEM_LARGE_MAX_MB, THREADMEM_SMALL_DEF_MB, and THREADMEM_SMALL_MAX_MB.
Referenced by GetDDSInfo().
ThreadOK()
bool System::ThreadOK (const int thrId) const
Definition at line 283 of file System.cpp.
{
  return (thrId >= 0 && thrId < numThreads);
}
Referenced by AnalysePlayBin(), and SolveBoard().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/System.h
open_spiel/games/bridge/double_dummy_solver/src/System.cpp