open spiel: absl::crc_internal::CrcCordState Class Reference
absl::crc_internal::CrcCordState Class Reference
#include <crc_cord_state.h>
Classes
struct PrefixCrc
struct Rep
Public Member Functions
CrcCordState ()
CrcCordState (const CrcCordState &)
CrcCordState (CrcCordState &&)
~CrcCordState ()
CrcCordState & operator= (const CrcCordState &)
CrcCordState & operator= (CrcCordState &&)
const Rep & rep () const
Rep * mutable_rep ()
absl::crc32c_t Checksum () const
bool IsNormalized () const
void Normalize ()
size_t NumChunks () const
PrefixCrc NormalizedPrefixCrcAtNthChunk (size_t n) const
void Poison ()
Detailed Description
Definition at line 41 of file crc_cord_state.h.
Constructor & Destructor Documentation
CrcCordState() [1/3]
absl::crc_internal::CrcCordState::CrcCordState ()
Definition at line 37 of file crc_cord_state.cc.
: refcounted_rep_(new RefcountedRep) {}
CrcCordState() [2/3]
absl::crc_internal::CrcCordState::CrcCordState (const CrcCordState & other)
Definition at line 39 of file crc_cord_state.cc.
    : refcounted_rep_(other.refcounted_rep_) {
  Ref(refcounted_rep_);
}
CrcCordState() [3/3]
absl::crc_internal::CrcCordState::CrcCordState (CrcCordState && other)
Definition at line 44 of file crc_cord_state.cc.
    : refcounted_rep_(other.refcounted_rep_) {
  // Make `other` valid for use after move.
  other.refcounted_rep_ = RefSharedEmptyRep();
}
~CrcCordState()
absl::crc_internal::CrcCordState::~CrcCordState ()
Definition at line 69 of file crc_cord_state.cc.
{
  Unref(refcounted_rep_);
}
Member Function Documentation
Checksum()
crc32c_t absl::crc_internal::CrcCordState::Checksum () const
Definition at line 73 of file crc_cord_state.cc.
{
  if (rep().prefix_crc.empty()) {
    return absl::crc32c_t{0};
  }
  if (IsNormalized()) {
    return rep().prefix_crc.back().crc;
  }
  return absl::RemoveCrc32cPrefix(
      rep().removed_prefix.crc, rep().prefix_crc.back().crc,
      rep().prefix_crc.back().length - rep().removed_prefix.length);
}
References IsNormalized(), absl::crc_internal::CrcCordState::Rep::prefix_crc, absl::RemoveCrc32cPrefix(), and rep().
Referenced by absl::Cord::ExpectedChecksum().
IsNormalized()
bool absl::crc_internal::CrcCordState::IsNormalized () const inline
Definition at line 110 of file crc_cord_state.h.
{ return rep().removed_prefix.length == 0; }
References absl::crc_internal::CrcCordState::PrefixCrc::length, absl::crc_internal::CrcCordState::Rep::removed_prefix, and rep().
Referenced by Checksum(), Normalize(), and NormalizedPrefixCrcAtNthChunk().
mutable_rep()
Rep * absl::crc_internal::CrcCordState::mutable_rep () inline
Definition at line 96 of file crc_cord_state.h.
                     {
    if (refcounted_rep_->count.load(std::memory_order_acquire) != 1) {
      RefcountedRep* copy = new RefcountedRep;
      copy->rep = refcounted_rep_->rep;
      Unref(refcounted_rep_);
      refcounted_rep_ = copy;
    }
    return &refcounted_rep_->rep;
  }
Referenced by Normalize(), Poison(), and absl::Cord::SetExpectedChecksum().
Normalize()
void absl::crc_internal::CrcCordState::Normalize ()
Definition at line 97 of file crc_cord_state.cc.
{
  if (IsNormalized() || rep().prefix_crc.empty()) {
    return;
  }
  Rep* r = mutable_rep();
  for (auto& prefix_crc : r->prefix_crc) {
    size_t remaining = prefix_crc.length - r->removed_prefix.length;
    prefix_crc.crc = absl::RemoveCrc32cPrefix(r->removed_prefix.crc,
                                              prefix_crc.crc, remaining);
    prefix_crc.length = remaining;
  }
  r->removed_prefix = PrefixCrc();
}
References IsNormalized(), mutable_rep(), r, absl::RemoveCrc32cPrefix(), and rep().
NormalizedPrefixCrcAtNthChunk()
CrcCordState::PrefixCrc absl::crc_internal::CrcCordState::NormalizedPrefixCrcAtNthChunk (size_t n) const
Definition at line 85 of file crc_cord_state.cc.
                    {
  assert(n < NumChunks());
  if (IsNormalized()) {
    return rep().prefix_crc[n];
  }
  size_t length = rep().prefix_crc[n].length - rep().removed_prefix.length;
  return PrefixCrc(length,
                   absl::RemoveCrc32cPrefix(rep().removed_prefix.crc,
                                            rep().prefix_crc[n].crc, length));
}
References IsNormalized(), absl::crc_internal::CrcCordState::PrefixCrc::length, absl::n, NumChunks(), absl::crc_internal::CrcCordState::Rep::prefix_crc, absl::RemoveCrc32cPrefix(), absl::crc_internal::CrcCordState::Rep::removed_prefix, and rep().
NumChunks()
size_t absl::crc_internal::CrcCordState::NumChunks () const inline
Definition at line 117 of file crc_cord_state.h.
{ return rep().prefix_crc.size(); }
References absl::crc_internal::CrcCordState::Rep::prefix_crc, and rep().
Referenced by NormalizedPrefixCrcAtNthChunk(), and Poison().
operator=() [1/2]
CrcCordState & absl::crc_internal::CrcCordState::operator= (const CrcCordState & other)
Definition at line 50 of file crc_cord_state.cc.
{
  if (this != &other) {
    Unref(refcounted_rep_);
    refcounted_rep_ = other.refcounted_rep_;
    Ref(refcounted_rep_);
  }
  return *this;
}
operator=() [2/2]
CrcCordState & absl::crc_internal::CrcCordState::operator= (CrcCordState && other)
Definition at line 59 of file crc_cord_state.cc.
{
  if (this != &other) {
    Unref(refcounted_rep_);
    refcounted_rep_ = other.refcounted_rep_;
    // Make `other` valid for use after move.
    other.refcounted_rep_ = RefSharedEmptyRep();
  }
  return *this;
}
Poison()
void absl::crc_internal::CrcCordState::Poison ()
Definition at line 112 of file crc_cord_state.cc.
{
  Rep* rep = mutable_rep();
  if (NumChunks() > 0) {
    for (auto& prefix_crc : rep->prefix_crc) {
      // This is basically CRC32::Scramble().
      uint32_t crc = static_cast<uint32_t>(prefix_crc.crc);
      crc += 0x2e76e41b;
      crc = absl::rotr(crc, 17);
      prefix_crc.crc = crc32c_t{crc};
    }
  } else {
    // Add a fake corrupt chunk.
    rep->prefix_crc.push_back(PrefixCrc(0, crc32c_t{1}));
  }
}
References mutable_rep(), NumChunks(), absl::crc_internal::CrcCordState::Rep::prefix_crc, rep(), and absl::rotr().
rep()
const Rep & absl::crc_internal::CrcCordState::rep () const inline
Definition at line 90 of file crc_cord_state.h.
{ return refcounted_rep_->rep; }
Referenced by Checksum(), IsNormalized(), Normalize(), NormalizedPrefixCrcAtNthChunk(), NumChunks(), and Poison().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/crc/internal/crc_cord_state.h
open_spiel/abseil-cpp/absl/crc/internal/crc_cord_state.cc