open spiel: absl::synchronization_internal::GraphCycles Class Reference
absl::synchronization_internal::GraphCycles Class Reference
#include <graphcycles.h>
Classes
struct Rep
Public Member Functions
GraphCycles ()
~GraphCycles ()
GraphId GetId (void *ptr)
void RemoveNode (void *ptr)
void * Ptr (GraphId id)
bool InsertEdge (GraphId source_node, GraphId dest_node)
void RemoveEdge (GraphId source_node, GraphId dest_node)
bool HasNode (GraphId node)
bool HasEdge (GraphId source_node, GraphId dest_node) const
bool IsReachable (GraphId source_node, GraphId dest_node) const
int FindPath (GraphId source, GraphId dest, int max_path_len, GraphId path[]) const
void UpdateStackTrace (GraphId id, int priority, int(*get_stack_trace)(void **, int))
int GetStackTrace (GraphId id, void ***ptr)
bool CheckInvariants () const
Detailed Description
Definition at line 62 of file graphcycles.h.
Constructor & Destructor Documentation
GraphCycles()
absl::synchronization_internal::GraphCycles::GraphCycles ()
Definition at line 367 of file graphcycles.cc.
{
  InitArenaIfNecessary();
  rep_ = new (base_internal::LowLevelAlloc::AllocWithArena(sizeof(Rep), arena))
      Rep;
}
References absl::base_internal::LowLevelAlloc::AllocWithArena(), and arena.
~GraphCycles()
absl::synchronization_internal::GraphCycles::~GraphCycles ()
Definition at line 373 of file graphcycles.cc.
{
  for (auto* node : rep_->nodes_) {
    node->Node::~Node();
    base_internal::LowLevelAlloc::Free(node);
  }
  rep_->Rep::~Rep();
  base_internal::LowLevelAlloc::Free(rep_);
}
References absl::base_internal::LowLevelAlloc::Free(), and absl::synchronization_internal::GraphCycles::Rep::nodes_.
Member Function Documentation
CheckInvariants()
bool absl::synchronization_internal::GraphCycles::CheckInvariants () const
Definition at line 382 of file graphcycles.cc.
{
  Rep* r = rep_;
  NodeSet ranks;  // Set of ranks seen so far.
  for (uint32_t x = 0; x < r->nodes_.size(); x++) {
    Node* nx = r->nodes_[x];
    void* ptr = base_internal::UnhidePtr<void>(nx->masked_ptr);
    if (ptr != nullptr && static_cast<uint32_t>(r->ptrmap_.Find(ptr)) != x) {
      ABSL_RAW_LOG(FATAL, "Did not find live node in hash table %u %p", x, ptr);
    }
    if (nx->visited) {
      ABSL_RAW_LOG(FATAL, "Did not clear visited marker on node %u", x);
    }
    if (!ranks.insert(nx->rank)) {
      ABSL_RAW_LOG(FATAL, "Duplicate occurrence of rank %d", nx->rank);
    }
    HASH_FOR_EACH(y, nx->out) {
      Node* ny = r->nodes_[static_cast<uint32_t>(y)];
      if (nx->rank >= ny->rank) {
        ABSL_RAW_LOG(FATAL, "Edge %u->%d has bad rank assignment %d->%d", x, y,
                     nx->rank, ny->rank);
      }
    }
  }
  return true;
}
References ABSL_RAW_LOG, HASH_FOR_EACH, absl::synchronization_internal::GraphCycles::Rep::nodes_, ptr, r, absl::base_internal::UnhidePtr(), absl::x, and y.
FindPath()
int absl::synchronization_internal::GraphCycles::FindPath (GraphId source, GraphId dest, int max_path_len, GraphId path[]) const
Definition at line 630 of file graphcycles.cc.
{
  Rep* r = rep_;
  if (FindNode(r, idx) == nullptr || FindNode(r, idy) == nullptr) return 0;
  const int32_t x = NodeIndex(idx);
  const int32_t y = NodeIndex(idy);
  // Forward depth first search starting at x until we hit y.
  // As we descend into a node, we push it onto the path.
  // As we leave a node, we remove it from the path.
  int path_len = 0;
  NodeSet seen;
  r->stack_.clear();
  r->stack_.push_back(x);
  while (!r->stack_.empty()) {
    int32_t n = r->stack_.back();
    r->stack_.pop_back();
    if (n < 0) {
      // Marker to indicate that we are leaving a node
      path_len--;
      continue;
    }
    if (path_len < max_path_len) {
      path[path_len] =
          MakeId(n, rep_->nodes_[static_cast<uint32_t>(n)]->version);
    }
    path_len++;
    r->stack_.push_back(-1);  // Will remove tentative path entry
    if (n == y) {
      return path_len;
    }
    HASH_FOR_EACH(w, r->nodes_[static_cast<uint32_t>(n)]->out) {
      if (seen.insert(w)) {
        r->stack_.push_back(w);
      }
    }
  }
  return 0;
}
References HASH_FOR_EACH, absl::n, absl::synchronization_internal::GraphCycles::Rep::nodes_, r, absl::x, and y.
Referenced by IsReachable(), absl::synchronization_internal::GraphCyclesTest::Path(), and absl::synchronization_internal::TEST().
GetId()
GraphId absl::synchronization_internal::GraphCycles::GetId (void * ptr)
Definition at line 408 of file graphcycles.cc.
{
  int32_t i = rep_->ptrmap_.Find(ptr);
  if (i != -1) {
    return MakeId(i, rep_->nodes_[static_cast<uint32_t>(i)]->version);
  } else if (rep_->free_nodes_.empty()) {
    Node* n =
        new (base_internal::LowLevelAlloc::AllocWithArena(sizeof(Node), arena))
            Node;
    n->version = 1;  // Avoid 0 since it is used by InvalidGraphId()
    n->visited = false;
    n->rank = static_cast<int32_t>(rep_->nodes_.size());
    n->masked_ptr = base_internal::HidePtr(ptr);
    n->nstack = 0;
    n->priority = 0;
    rep_->nodes_.push_back(n);
    rep_->ptrmap_.Add(ptr, n->rank);
    return MakeId(n->rank, n->version);
  } else {
    // Preserve preceding rank since the set of ranks in use must be
    // a permutation of [0,rep_->nodes_.size()-1].
    int32_t r = rep_->free_nodes_.back();
    rep_->free_nodes_.pop_back();
    Node* n = rep_->nodes_[static_cast<uint32_t>(r)];
    n->masked_ptr = base_internal::HidePtr(ptr);
    n->nstack = 0;
    n->priority = 0;
    rep_->ptrmap_.Add(ptr, r);
    return MakeId(r, n->version);
  }
}
References absl::base_internal::LowLevelAlloc::AllocWithArena(), arena, absl::synchronization_internal::GraphCycles::Rep::free_nodes_, absl::base_internal::HidePtr(), absl::i, absl::n, absl::synchronization_internal::GraphCycles::Rep::nodes_, ptr, absl::synchronization_internal::GraphCycles::Rep::ptrmap_, and r.
Referenced by absl::synchronization_internal::GraphCyclesTest::GraphCyclesTest(), and absl::synchronization_internal::TEST().
GetStackTrace()
int absl::synchronization_internal::GraphCycles::GetStackTrace (GraphId id, void *** ptr)
Definition at line 689 of file graphcycles.cc.
{
  Node* n = FindNode(rep_, id);
  if (n == nullptr) {
    *ptr = nullptr;
    return 0;
  } else {
    *ptr = n->stack;
    return n->nstack;
  }
}
References absl::n, and ptr.
HasEdge()
bool absl::synchronization_internal::GraphCycles::HasEdge (GraphId source_node, GraphId dest_node) const
Definition at line 472 of file graphcycles.cc.
{
  Node* xn = FindNode(rep_, x);
  return xn && FindNode(rep_, y) && xn->out.contains(NodeIndex(y));
}
References absl::x, and y.
Referenced by absl::synchronization_internal::TEST().
HasNode()
bool absl::synchronization_internal::GraphCycles::HasNode (GraphId node)
Definition at line 468 of file graphcycles.cc.
{
  return FindNode(rep_, node) != nullptr;
}
InsertEdge()
bool absl::synchronization_internal::GraphCycles::InsertEdge (GraphId source_node, GraphId dest_node)
Definition at line 495 of file graphcycles.cc.
{
  Rep* r = rep_;
  const int32_t x = NodeIndex(idx);
  const int32_t y = NodeIndex(idy);
  Node* nx = FindNode(r, idx);
  Node* ny = FindNode(r, idy);
  if (nx == nullptr || ny == nullptr) return true;  // Expired ids
  if (nx == ny) return false;  // Self edge
  if (!nx->out.insert(y)) {
    // Edge already exists.
    return true;
  }
  ny->in.insert(x);
  if (nx->rank <= ny->rank) {
    // New edge is consistent with existing rank assignment.
    return true;
  }
  // Current rank assignments are incompatible with the new edge.  Recompute.
  // We only need to consider nodes that fall in the range [ny->rank,nx->rank].
  if (!ForwardDFS(r, y, nx->rank)) {
    // Found a cycle.  Undo the insertion and tell caller.
    nx->out.erase(y);
    ny->in.erase(x);
    // Since we do not call Reorder() on this path, clear any visited
    // markers left by ForwardDFS.
    for (const auto& d : r->deltaf_) {
      r->nodes_[static_cast<uint32_t>(d)]->visited = false;
    }
    return false;
  }
  BackwardDFS(r, x, ny->rank);
  Reorder(r);
  return true;
}
References absl::d, r, visited, absl::x, and y.
Referenced by absl::synchronization_internal::GraphCyclesTest::AddEdge(), and absl::synchronization_internal::TEST().
IsReachable()
bool absl::synchronization_internal::GraphCycles::IsReachable (GraphId source_node, GraphId dest_node) const
Definition at line 675 of file graphcycles.cc.
{
  return FindPath(x, y, 0, nullptr) > 0;
}
References FindPath(), absl::x, and y.
Referenced by absl::synchronization_internal::TEST().
Ptr()
void * absl::synchronization_internal::GraphCycles::Ptr (GraphId id)
Definition at line 462 of file graphcycles.cc.
{
  Node* n = FindNode(rep_, id);
  return n == nullptr ? nullptr
                      : base_internal::UnhidePtr<void>(n->masked_ptr);
}
References absl::n, and absl::base_internal::UnhidePtr().
Referenced by absl::synchronization_internal::GraphCyclesTest::Path(), and absl::synchronization_internal::TEST().
RemoveEdge()
void absl::synchronization_internal::GraphCycles::RemoveEdge (GraphId source_node, GraphId dest_node)
Definition at line 477 of file graphcycles.cc.
{
  Node* xn = FindNode(rep_, x);
  Node* yn = FindNode(rep_, y);
  if (xn && yn) {
    xn->out.erase(NodeIndex(y));
    yn->in.erase(NodeIndex(x));
    // No need to update the rank assignment since a previous valid
    // rank assignment remains valid after an edge deletion.
  }
}
References absl::x, and y.
Referenced by absl::synchronization_internal::TEST().
RemoveNode()
void absl::synchronization_internal::GraphCycles::RemoveNode (void * ptr)
Definition at line 439 of file graphcycles.cc.
{
  int32_t i = rep_->ptrmap_.Remove(ptr);
  if (i == -1) {
    return;
  }
  Node* x = rep_->nodes_[static_cast<uint32_t>(i)];
  HASH_FOR_EACH(y, x->out) {
    rep_->nodes_[static_cast<uint32_t>(y)]->in.erase(i);
  }
  HASH_FOR_EACH(y, x->in) {
    rep_->nodes_[static_cast<uint32_t>(y)]->out.erase(i);
  }
  x->in.clear();
  x->out.clear();
  x->masked_ptr = base_internal::HidePtr<void>(nullptr);
  if (x->version == std::numeric_limits<uint32_t>::max()) {
    // Cannot use x any more
  } else {
    x->version++;  // Invalidates all copies of node.
    rep_->free_nodes_.push_back(i);
  }
}
References absl::synchronization_internal::GraphCycles::Rep::free_nodes_, HASH_FOR_EACH, absl::base_internal::HidePtr(), absl::i, in, absl::synchronization_internal::GraphCycles::Rep::nodes_, absl::out, ptr, absl::synchronization_internal::GraphCycles::Rep::ptrmap_, absl::x, and y.
Referenced by absl::synchronization_internal::TEST().
UpdateStackTrace()
void absl::synchronization_internal::GraphCycles::UpdateStackTrace (GraphId id, int priority, int(* get_stack_trace)(void **, int))
Definition at line 679 of file graphcycles.cc.
{
  Node* n = FindNode(rep_, id);
  if (n == nullptr || n->priority >= priority) {
    return;
  }
  n->nstack = (*get_stack_trace)(n->stack, ABSL_ARRAYSIZE(n->stack));
  n->priority = priority;
}
References ABSL_ARRAYSIZE, absl::n, and priority.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/synchronization/internal/graphcycles.h
open_spiel/abseil-cpp/absl/synchronization/internal/graphcycles.cc