open spiel: open_spiel::trade_comm::TradeCommState Class Reference
open_spiel::trade_comm::TradeCommState Class Reference
#include <trade_comm.h>
Public Member Functions
TradeCommState (std::shared_ptr< const Game > game, int num_items)
TradeCommState (const TradeCommState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move_id) const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string InformationStateString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 58 of file trade_comm.h.
Constructor & Destructor Documentation
TradeCommState() [1/2]
open_spiel::trade_comm::TradeCommState::TradeCommState (std::shared_ptr< const Game > game, int num_items)
Definition at line 229 of file trade_comm.cc.
    : State(game),
      num_items_(num_items),
      cur_player_(kChancePlayerId),
      phase_(Phase::kCommunication) {}
Referenced by Clone().
TradeCommState() [2/2]
open_spiel::trade_comm::TradeCommState::TradeCommState (const TradeCommState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::trade_comm::TradeCommState::ActionToString (Player player, Action move_id) const override virtual
Implements open_spiel::State.
Definition at line 71 of file trade_comm.cc.
{
  if (player == kChancePlayerId) {
    std::pair<int, int> allocation = DecodeAllocation(move_id, num_items_);
    return absl::StrCat("Allocate ", allocation.first, " ", allocation.second);
  } else {
    if (move_id < num_items_) {
      return absl::StrCat("Utter ", move_id);
    } else {
      std::pair<int, int> trade = DecodeTrade(move_id, num_items_);
      return absl::StrCat("Trade ", trade.first, ":", trade.second);
    }
  }
}
References open_spiel::kChancePlayerId, player, and absl::StrCat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::trade_comm::TradeCommState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 287 of file trade_comm.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  int num_outcomes = num_items_ * num_items_;
  std::vector<std::pair<Action, double>> outcomes;
  outcomes.reserve(num_outcomes);
  for (int i = 0; i < num_outcomes; ++i) {
    outcomes.push_back({i, 1.0 / num_outcomes});
  }
  return outcomes;
}
References i, open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::trade_comm::TradeCommState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 317 of file trade_comm.cc.
{
  return std::unique_ptr<State>(new TradeCommState(*this));
}
References TradeCommState().
CurrentPlayer()
int open_spiel::trade_comm::TradeCommState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 235 of file trade_comm.cc.
{
  return IsTerminal() ? kTerminalPlayerId : cur_player_;
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::trade_comm::TradeCommState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 239 of file trade_comm.cc.
{
  if (IsChanceNode()) {
    std::pair<int, int> allocation = DecodeAllocation(action, num_items_);
    items_.push_back(allocation.first);
    items_.push_back(allocation.second);
    cur_player_ = 0;
  } else {
    if (phase_ == Phase::kCommunication) {
      comm_history_.push_back(action);
      if (comm_history_.size() == 2) {
        phase_ = Phase::kTrade;
      }
      cur_player_ = NextPlayerRoundRobin(cur_player_, num_players_);
    } else {
      trade_history_.push_back(action);
      cur_player_ = NextPlayerRoundRobin(cur_player_, num_players_);
    }
  }
}
References action, open_spiel::State::IsChanceNode(), open_spiel::trade_comm::kCommunication, open_spiel::trade_comm::kTrade, open_spiel::NextPlayerRoundRobin(), and open_spiel::State::num_players_.
InformationStateString()
std::string open_spiel::trade_comm::TradeCommState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 155 of file trade_comm.cc.
{
  // Currently the observation and information state are the same, since the
  // game only contains one step of each phase. This may change in the
  // multi-step game in the future.
  return ObservationString(player);
}
References open_spiel::State::ObservationString(), and player.
InformationStateTensor()
void open_spiel::trade_comm::TradeCommState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 221 of file trade_comm.cc.
{
  // Currently the observation and information state are the same, since the
  // game only contains one step of each phase. This may change in the
  // multi-step game in the future.
  ObservationTensor(player, values);
}
References open_spiel::State::ObservationTensor(), player, and values.
IsTerminal()
bool open_spiel::trade_comm::TradeCommState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 86 of file trade_comm.cc.
{
  return (phase_ == Phase::kTrade && trade_history_.size() == 2);
}
References open_spiel::trade_comm::kTrade.
Referenced by CurrentPlayer(), LegalActions(), ObservationString(), ObservationTensor(), and Returns().
LegalActions()
std::vector< Action > open_spiel::trade_comm::TradeCommState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 259 of file trade_comm.cc.
{
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else if (IsTerminal()) {
    return {};
  } else if (phase_ == Phase::kCommunication) {
    // Can utter anything. Utterances are actions 0 to num_items_ - 1 for now.
    std::vector<Action> legal_actions;
    legal_actions.reserve(num_items_);
    for (int i = 0; i < num_items_; ++i) {
      legal_actions.push_back(i);
    }
    return legal_actions;
  } else if (phase_ == Phase::kTrade) {
    // 1:1 trades for k items = k*k actions (includes trading an item for the
    // same item) starting at num_items_.
    std::vector<Action> legal_actions;
    int num_trade_actions = num_items_ * num_items_;
    legal_actions.reserve(num_trade_actions);
    for (int i = 0; i < num_trade_actions; ++i) {
      legal_actions.push_back(num_items_ + i);
    }
    return legal_actions;
  } else {
    SpielFatalError("Invalid phase?");
  }
}
References i, open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::trade_comm::kCommunication, open_spiel::trade_comm::kTrade, open_spiel::State::LegalChanceOutcomes(), and open_spiel::SpielFatalError().
ObservationString()
std::string open_spiel::trade_comm::TradeCommState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 108 of file trade_comm.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (IsChanceNode()) {
    return "ChanceNode -- no observation";
  }
  std::string str = "";
  // Whose turn is it?
  absl::StrAppend(&str, "Current turn: ", cur_player_, "\n");
  // A player can see their own item.
  absl::StrAppend(&str, "My item: ", items_[player], "\n");
  // A player see all the utterances, in the right order:
  absl::StrAppend(&str, "Phase: ", phase_ == Phase::kTrade ? "trade" : "comm");
  absl::StrAppend(&str, "\nComm history: ");
  for (int comm : comm_history_) {
    absl::StrAppend(&str, " ", comm);
  }
  absl::StrAppend(&str, "\n");
  // Trade proposals are treated as simultaneous, so not included in the
  // observation, but we do mark how many trade actions have happened to agents
  // can work out what trading round they're on.
  absl::StrAppend(&str, "Trade history size: ", trade_history_.size(), "\n");
  // Players can see their own trades if they were made.
  if (player < trade_history_.size()) {
    absl::StrAppend(&str, "Observer's trade offer: ");
    std::pair<int, int> trade = DecodeTrade(trade_history_[player], num_items_);
    absl::StrAppend(&str, " ", trade.first, ":", trade.second, "\n");
  }
  // Players can see the other trade offers after the round.
  if (IsTerminal()) {
    SPIEL_CHECK_LT(1 - player, trade_history_.size());
    absl::StrAppend(&str, "Other players's trade offer: ");
    std::pair<int, int> trade =
        DecodeTrade(trade_history_[1 - player], num_items_);
    absl::StrAppend(&str, " ", trade.first, ":", trade.second, "\n");
  }
  return str;
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::trade_comm::kTrade, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrAppend().
ObservationTensor()
void open_spiel::trade_comm::TradeCommState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 162 of file trade_comm.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->InformationStateTensorSize());
  std::fill(values.begin(), values.end(), 0);
  if (IsChanceNode()) {
    // No observations at chance nodes.
    return;
  }
  SPIEL_CHECK_TRUE(player == 0 || player == 1);
  // 2 bits to indicate whose turn it is.
  int offset = 0;
  values[cur_player_] = 1;
  offset += 2;
  // 1 bit to indicate whether it's terminal
  values[offset] = IsTerminal() ? 1 : 0;
  offset += 1;
  // Single bit for the phase: 0 = comm, 1 = trade.
  values[offset] = (phase_ == Phase::kCommunication ? 0 : 1);
  offset += 1;
  // one-hot vector for the item the observing player got
  values[offset + items_[player]] = 1;
  offset += num_items_;
  if (player < comm_history_.size()) {
    // one-hot vector for the utterance the observing player made
    values[offset + comm_history_[player]] = 1;
  }
  offset += num_items_;
  // one-hot vector for the utterance the observing player observed
  if (1 - player < comm_history_.size()) {
    values[offset + comm_history_[1 - player]] = 1;
  }
  offset += num_items_;
  // one-hot vector for the size of the trade history
  values[offset + trade_history_.size()] = 1;
  offset += 3;
  // one-hot vector for observing player's trade history if it has been made.
  if (player < trade_history_.size()) {
    const auto& trade = DecodeTrade(trade_history_[player], num_items_);
    values[offset + trade.first] = 1;
    values[offset + num_items_ + trade.second] = 1;
  }
  offset += 2 * num_items_;
  SPIEL_CHECK_EQ(offset, values.size());
}
References open_spiel::State::game_, open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::trade_comm::kCommunication, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, and values.
Returns()
std::vector< double > open_spiel::trade_comm::TradeCommState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 90 of file trade_comm.cc.
{
  if (!IsTerminal()) {
    return {0.0, 0.0};
  } else {
    // Check for a compatible trade. A compatible trade satisfies:
    //   - Agent X has item A, and offers A for B
    //   - Agent Y has item B, and offers B for A
    std::pair<int, int> trade0 = DecodeTrade(trade_history_[0], num_items_);
    std::pair<int, int> trade1 = DecodeTrade(trade_history_[1], num_items_);
    if (items_[0] == trade0.first && items_[1] == trade1.first &&
        trade0.first == trade1.second && trade1.first == trade0.second) {
      return {1.0, 1.0};
    } else {
      return {0.0, 0.0};
    }
  }
}
References IsTerminal().
ToString()
std::string open_spiel::trade_comm::TradeCommState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 298 of file trade_comm.cc.
{
  if (IsChanceNode()) {
    return "Initial chance node";
  }
  std::string str = absl::StrCat("Items: ", absl::StrJoin(items_, " "));
  absl::StrAppend(&str,
                  "\nPhase: ", phase_ == Phase::kTrade ? "trade" : "comm");
  absl::StrAppend(&str, "\nComm history: ", absl::StrJoin(comm_history_, " "));
  absl::StrAppend(&str, "\nTrade history:");
  for (Action trade_action : trade_history_) {
    std::pair<int, int> trade = DecodeTrade(trade_action, num_items_);
    absl::StrAppend(&str, " ", trade.first, ":", trade.second);
  }
  absl::StrAppend(&str, "\n");
  return str;
}
References open_spiel::State::IsChanceNode(), open_spiel::trade_comm::kTrade, absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
The documentation for this class was generated from the following files:
open_spiel/games/trade_comm/trade_comm.h
open_spiel/games/trade_comm/trade_comm.cc