open spiel: absl::container_internal::BitMask< T, SignificantBits, Shift > Class Template Reference
absl::container_internal::BitMask< T, SignificantBits, Shift > Class Template Reference
#include <raw_hash_set.h>
Public Types
using value_type = int
using iterator = BitMask
using const_iterator = BitMask
Public Member Functions
BitMask (T mask)
BitMask & operator++ ()
uint32_t operator* () const
BitMask begin () const
BitMask end () const
Public Member Functions inherited from absl::container_internal::NonIterableBitMask< T, SignificantBits, 0 >
NonIterableBitMask (T mask)
operator bool () const
uint32_t LowestBitSet () const
uint32_t HighestBitSet () const
uint32_t TrailingZeros () const
uint32_t LeadingZeros () const
Friends
bool operator== (const BitMask &a, const BitMask &b)
bool operator!= (const BitMask &a, const BitMask &b)
Additional Inherited Members
Public Attributes inherited from absl::container_internal::NonIterableBitMask< T, SignificantBits, 0 >
T mask_
Detailed Description
template<class T, int SignificantBits, int Shift = 0>
class absl::container_internal::BitMask< T, SignificantBits, Shift >
Definition at line 396 of file raw_hash_set.h.
Member Typedef Documentation
const_iterator
template<class T , int SignificantBits, int Shift = 0> using absl::container_internal::BitMask< T, SignificantBits, Shift >::const_iterator = BitMask
Definition at line 406 of file raw_hash_set.h.
iterator
template<class T , int SignificantBits, int Shift = 0> using absl::container_internal::BitMask< T, SignificantBits, Shift >::iterator = BitMask
Definition at line 405 of file raw_hash_set.h.
value_type
template<class T , int SignificantBits, int Shift = 0> using absl::container_internal::BitMask< T, SignificantBits, Shift >::value_type = int
Definition at line 404 of file raw_hash_set.h.
Constructor & Destructor Documentation
BitMask()
template<class T , int SignificantBits, int Shift = 0> absl::container_internal::BitMask< T, SignificantBits, Shift >::BitMask (T mask) inline explicit
Definition at line 402 of file raw_hash_set.h.
: Base(mask) {}
Referenced by absl::container_internal::BitMask< T, SignificantBits, Shift >::end().
Member Function Documentation
begin()
template<class T , int SignificantBits, int Shift = 0> BitMask absl::container_internal::BitMask< T, SignificantBits, Shift >::begin () const inline
Definition at line 415 of file raw_hash_set.h.
{ return *this; }
end()
template<class T , int SignificantBits, int Shift = 0> BitMask absl::container_internal::BitMask< T, SignificantBits, Shift >::end () const inline
Definition at line 416 of file raw_hash_set.h.
{ return BitMask(0); }
References absl::container_internal::BitMask< T, SignificantBits, Shift >::BitMask().
operator*()
template<class T , int SignificantBits, int Shift = 0> uint32_t absl::container_internal::BitMask< T, SignificantBits, Shift >::operator* () const inline
Definition at line 413 of file raw_hash_set.h.
{ return Base::LowestBitSet(); }
References absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::LowestBitSet().
operator++()
template<class T , int SignificantBits, int Shift = 0> BitMask & absl::container_internal::BitMask< T, SignificantBits, Shift >::operator++ () inline
Definition at line 408 of file raw_hash_set.h.
{
    this->mask_ &= (this->mask_ - 1);
    return *this;
  }
References absl::container_internal::NonIterableBitMask< T, SignificantBits, 0 >::mask_.
Friends And Related Symbol Documentation
operator!=
template<class T , int SignificantBits, int Shift = 0> bool operator!= (const BitMask< T, SignificantBits, Shift > & a, const BitMask< T, SignificantBits, Shift > & b) friend
Definition at line 422 of file raw_hash_set.h.
{
    return a.mask_ != b.mask_;
  }
operator==
template<class T , int SignificantBits, int Shift = 0> bool operator== (const BitMask< T, SignificantBits, Shift > & a, const BitMask< T, SignificantBits, Shift > & b) friend
Definition at line 419 of file raw_hash_set.h.
{
    return a.mask_ == b.mask_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/raw_hash_set.h