open spiel: absl::hash_internal::SpyHashStateImpl< T > Class Template Reference
absl::hash_internal::SpyHashStateImpl< T > Class Template Reference
#include <spy_hash_state.h>
Public Types
enum class CompareResult { kEqual , kASuffixB , kBSuffixA , kUnequal }
Public Types inherited from absl::hash_internal::HashStateBase< SpyHashStateImpl< T > >
using AbslInternalPiecewiseCombiner
using is_hashable
Public Member Functions
SpyHashStateImpl ()
SpyHashStateImpl (const SpyHashStateImpl &)=delete
SpyHashStateImpl & operator= (const SpyHashStateImpl &)=delete
SpyHashStateImpl (SpyHashStateImpl &&other) noexcept
SpyHashStateImpl & operator= (SpyHashStateImpl &&other) noexcept
template<typename U >
SpyHashStateImpl (SpyHashStateImpl< U > &&other)
absl::optional< std::string > error () const
Static Public Member Functions
template<typename A , typename... Args>
static SpyHashStateImpl combine (SpyHashStateImpl s, const A &a, const Args &... args)
static SpyHashStateImpl combine (SpyHashStateImpl s)
static void SetDirectAbslHashValueError ()
static CompareResult Compare (const SpyHashStateImpl &a, const SpyHashStateImpl &b)
static SpyHashStateImpl combine_contiguous (SpyHashStateImpl hash_state, const unsigned char *begin, size_t size)
template<typename CombinerT >
static SpyHashStateImpl RunCombineUnordered (SpyHashStateImpl state, CombinerT combiner)
Static Public Member Functions inherited from absl::hash_internal::HashStateBase< SpyHashStateImpl< T > >
static SpyHashStateImpl< T > combine (SpyHashStateImpl< T > state, const T &value, const Ts &... values)
static SpyHashStateImpl< T > combine (SpyHashStateImpl< T > state)
static SpyHashStateImpl< T > combine_contiguous (SpyHashStateImpl< T > state, const T *data, size_t size)
static SpyHashStateImpl< T > combine_unordered (SpyHashStateImpl< T > state, I begin, I end)
Friends
template<typename U >
class SpyHashStateImpl
bool operator== (const SpyHashStateImpl &lhs, const SpyHashStateImpl &rhs)
bool operator!= (const SpyHashStateImpl &lhs, const SpyHashStateImpl &rhs)
std::ostream & operator<< (std::ostream &out, const SpyHashStateImpl &hash_state)
Detailed Description
template<typename T>
class absl::hash_internal::SpyHashStateImpl< T >
Definition at line 42 of file spy_hash_state.h.
Member Enumeration Documentation
CompareResult
template<typename T > enum class absl::hash_internal::SpyHashStateImpl::CompareResult strong
Enumerator
kEqual
kASuffixB
kBSuffixA
kUnequal
Definition at line 107 of file spy_hash_state.h.
{
    kEqual,
    kASuffixB,
    kBSuffixA,
    kUnequal,
  };
Constructor & Destructor Documentation
SpyHashStateImpl() [1/4]
template<typename T > absl::hash_internal::SpyHashStateImpl< T >::SpyHashStateImpl () inline
Definition at line 44 of file spy_hash_state.h.
                     : error_(std::make_shared<absl::optional<std::string>>()) {
    static_assert(std::is_void<T>::value, "");
  }
SpyHashStateImpl() [2/4]
template<typename T > absl::hash_internal::SpyHashStateImpl< T >::SpyHashStateImpl (const SpyHashStateImpl< T > &) delete
SpyHashStateImpl() [3/4]
template<typename T > absl::hash_internal::SpyHashStateImpl< T >::SpyHashStateImpl (SpyHashStateImpl< T > && other) inline noexcept
Definition at line 52 of file spy_hash_state.h.
{
    *this = std::move(other);
  }
SpyHashStateImpl() [4/4]
template<typename T > template<typename U > absl::hash_internal::SpyHashStateImpl< T >::SpyHashStateImpl (SpyHashStateImpl< U > && other) inline
Definition at line 65 of file spy_hash_state.h.
                                                {  // NOLINT
    hash_representation_ = std::move(other.hash_representation_);
    error_ = other.error_;
    moved_from_ = other.moved_from_;
    other.moved_from_ = true;
  }
Member Function Documentation
combine() [1/2]
template<typename T > static SpyHashStateImpl absl::hash_internal::SpyHashStateImpl< T >::combine (SpyHashStateImpl< T > s) inline static
Definition at line 82 of file spy_hash_state.h.
{
    if (direct_absl_hash_value_error_) {
      *s.error_ = "AbslHashValue should not be invoked directly.";
    } else if (s.moved_from_) {
      *s.error_ = "Used moved-from instance of the hash state object.";
    }
    return s;
  }
References absl::s.
combine() [2/2]
template<typename T > template<typename A , typename... Args> static SpyHashStateImpl absl::hash_internal::SpyHashStateImpl< T >::combine (SpyHashStateImpl< T > s, const A & a, const Args &... args) inline static
Definition at line 73 of file spy_hash_state.h.
{
    // Pass an instance of SpyHashStateImpl<A> when trying to combine `A`. This
    // allows us to test that the user only uses this instance for combine calls
    // and does not call AbslHashValue directly.
    // See AbslHashValue implementation at the bottom.
    s = SpyHashStateImpl<A>::HashStateBase::combine(std::move(s), a);
    return SpyHashStateImpl::combine(std::move(s), args...);
  }
References absl::a, absl::hash_internal::SpyHashStateImpl< T >::combine(), and absl::s.
Referenced by absl::hash_internal::SpyHashStateImpl< T >::combine(), and absl::hash_internal::ExpandVisitor::operator()().
combine_contiguous()
template<typename T > static SpyHashStateImpl absl::hash_internal::SpyHashStateImpl< T >::combine_contiguous (SpyHashStateImpl< T > hash_state, const unsigned char * begin, size_t size) inline static
Definition at line 148 of file spy_hash_state.h.
{
    const size_t large_chunk_stride = PiecewiseChunkSize();
    if (size > large_chunk_stride) {
      // Combining a large contiguous buffer must have the same effect as
      // doing it piecewise by the stride length, followed by the (possibly
      // empty) remainder.
      while (size >= large_chunk_stride) {
        hash_state = SpyHashStateImpl::combine_contiguous(
            std::move(hash_state), begin, large_chunk_stride);
        begin += large_chunk_stride;
        size -= large_chunk_stride;
      }
    }
    hash_state.hash_representation_.emplace_back(
        reinterpret_cast<const char*>(begin), size);
    return hash_state;
  }
References absl::hash_internal::SpyHashStateImpl< T >::combine_contiguous(), absl::hash_internal::PiecewiseChunkSize(), and size.
Referenced by absl::hash_internal::SpyHashStateImpl< T >::combine_contiguous().
Compare()
template<typename T > static CompareResult absl::hash_internal::SpyHashStateImpl< T >::Compare (const SpyHashStateImpl< T > & a, const SpyHashStateImpl< T > & b) inline static
Definition at line 114 of file spy_hash_state.h.
{
    const std::string a_flat = absl::StrJoin(a.hash_representation_, "");
    const std::string b_flat = absl::StrJoin(b.hash_representation_, "");
    if (a_flat == b_flat) return CompareResult::kEqual;
    if (absl::EndsWith(a_flat, b_flat)) return CompareResult::kBSuffixA;
    if (absl::EndsWith(b_flat, a_flat)) return CompareResult::kASuffixB;
    return CompareResult::kUnequal;
  }
References absl::a, b, absl::EndsWith(), absl::hash_internal::SpyHashStateImpl< T >::kASuffixB, absl::hash_internal::SpyHashStateImpl< T >::kBSuffixA, absl::hash_internal::SpyHashStateImpl< T >::kEqual, absl::hash_internal::SpyHashStateImpl< T >::kUnequal, and absl::StrJoin().
Referenced by absl::hash_internal::VerifyTypeImplementsAbslHashCorrectly().
error()
template<typename T > absl::optional< std::string > absl::hash_internal::SpyHashStateImpl< T >::error () const inline
Definition at line 189 of file spy_hash_state.h.
{
    if (moved_from_) {
      return "Returned a moved-from instance of the hash state object.";
    }
    return *error_;
  }
operator=() [1/2]
template<typename T > SpyHashStateImpl & absl::hash_internal::SpyHashStateImpl< T >::operator= (const SpyHashStateImpl< T > &) delete
operator=() [2/2]
template<typename T > SpyHashStateImpl & absl::hash_internal::SpyHashStateImpl< T >::operator= (SpyHashStateImpl< T > && other) inline noexcept
Definition at line 56 of file spy_hash_state.h.
{
    hash_representation_ = std::move(other.hash_representation_);
    error_ = other.error_;
    moved_from_ = other.moved_from_;
    other.moved_from_ = true;
    return *this;
  }
RunCombineUnordered()
template<typename T > template<typename CombinerT > static SpyHashStateImpl absl::hash_internal::SpyHashStateImpl< T >::RunCombineUnordered (SpyHashStateImpl< T > state, CombinerT combiner) inline static
Definition at line 172 of file spy_hash_state.h.
{
    UnorderedCombinerCallback cb;
    combiner(SpyHashStateImpl<void>{}, std::ref(cb));
    std::sort(cb.element_hash_representations.begin(),
              cb.element_hash_representations.end());
    state.hash_representation_.insert(state.hash_representation_.end(),
                                      cb.element_hash_representations.begin(),
                                      cb.element_hash_representations.end());
    if (cb.error && cb.error->has_value()) {
      state.error_ = std::move(cb.error);
    }
    return state;
  }
References state.
SetDirectAbslHashValueError()
template<typename T > static void absl::hash_internal::SpyHashStateImpl< T >::SetDirectAbslHashValueError () inline static
Definition at line 91 of file spy_hash_state.h.
{
    direct_absl_hash_value_error_ = true;
  }
Friends And Related Symbol Documentation
operator!=
template<typename T > bool operator!= (const SpyHashStateImpl< T > & lhs, const SpyHashStateImpl< T > & rhs) friend
Definition at line 102 of file spy_hash_state.h.
{
    return !(lhs == rhs);
  }
operator<<
template<typename T > std::ostream & operator<< (std::ostream & out, const SpyHashStateImpl< T > & hash_state) friend
Definition at line 126 of file spy_hash_state.h.
{
    out << "[\n";
    for (auto& s : hash_state.hash_representation_) {
      size_t offset = 0;
      for (char c : s) {
        if (offset % 16 == 0) {
          out << absl::StreamFormat("\n0x%04x: ", offset);
        }
        if (offset % 2 == 0) {
          out << " ";
        }
        out << absl::StreamFormat("%02x", c);
        ++offset;
      }
      out << "\n";
    }
    return out << "]";
  }
operator==
template<typename T > bool operator== (const SpyHashStateImpl< T > & lhs, const SpyHashStateImpl< T > & rhs) friend
Definition at line 97 of file spy_hash_state.h.
{
    return lhs.hash_representation_ == rhs.hash_representation_;
  }
SpyHashStateImpl
template<typename T > template<typename U > friend class SpyHashStateImpl friend
Definition at line 198 of file spy_hash_state.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/hash/internal/spy_hash_state.h