open spiel: open_spiel::universal_poker::UniversalPokerGame Class Reference
open_spiel::universal_poker::UniversalPokerGame Class Reference
#include <universal_poker.h>
Public Member Functions
UniversalPokerGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
int MaxChanceOutcomes () const override
absl::optional< double > UtilitySum () const override
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
BettingAbstraction betting_abstraction () const
int big_blind () const
double MaxCommitment () const
const acpc_cpp::ACPCGame * GetACPCGame () const
std::string parseParameters (const GameParameters &map)
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 205 of file universal_poker.h.
Constructor & Destructor Documentation
UniversalPokerGame()
open_spiel::universal_poker::UniversalPokerGame::UniversalPokerGame (const GameParameters & params) explicit
Universal Poker Game Constructor
Parameters
params
Definition at line 1005 of file universal_poker.cc.
    : Game(kGameType, params),
      gameDesc_(parseParameters(params)),
      acpc_game_(gameDesc_),
      potSize_(ParameterValue<int>("potSize")),
      boardCards_(ParameterValue<std::string>("boardCards")),
      handReaches_(ParameterValue<std::string>("handReaches")) {
  std::string betting_abstraction =
      ParameterValue<std::string>("bettingAbstraction");
  if (betting_abstraction == "fc") {
    betting_abstraction_ = BettingAbstraction::kFC;
  } else if (betting_abstraction == "fcpa") {
    betting_abstraction_ = BettingAbstraction::kFCPA;
  } else if (betting_abstraction == "fchpa") {
    betting_abstraction_ = BettingAbstraction::kFCHPA;
  } else if (betting_abstraction == "fullgame") {
    betting_abstraction_ = BettingAbstraction::kFULLGAME;
  } else {
    SpielFatalError(absl::StrFormat("bettingAbstraction: %s not supported.",
                                    betting_abstraction));
  }
  max_game_length_ = MaxGameLength();
  SPIEL_CHECK_TRUE(max_game_length_.has_value());
}
References betting_abstraction(), absl::optional< T >::has_value(), open_spiel::universal_poker::kFC, open_spiel::universal_poker::kFCHPA, open_spiel::universal_poker::kFCPA, open_spiel::universal_poker::kFULLGAME, MaxGameLength(), open_spiel::Game::ParameterValue(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), and absl::StrFormat().
Member Function Documentation
betting_abstraction()
BettingAbstraction open_spiel::universal_poker::UniversalPokerGame::betting_abstraction () const inline
Definition at line 221 of file universal_poker.h.
{
    return betting_abstraction_;
  }
Referenced by UniversalPokerGame().
big_blind()
int open_spiel::universal_poker::UniversalPokerGame::big_blind () const inline
Definition at line 225 of file universal_poker.h.
{ return big_blind_; }
Referenced by MaxCommitment().
GetACPCGame()
const acpc_cpp::ACPCGame * open_spiel::universal_poker::UniversalPokerGame::GetACPCGame () const inline
Definition at line 227 of file universal_poker.h.
{ return &acpc_game_; }
Referenced by main().
InformationStateTensorShape()
std::vector< int > open_spiel::universal_poker::UniversalPokerGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 1034 of file universal_poker.cc.
{
  // Layout:
  //   my player number: num_players bits
  //   my cards: Initial deck size bits (1 means you have the card), i.e.
  //             MaxChanceOutcomes() = NumSuits * NumRanks
  //   public cards: Same as above, but for the public cards.
  //   action sequence: (max game length)*2 bits (fold/raise/call/all-in)
  //   action sequence sizings: (max game length) integers with value >= 0,
  //                             0 when corresponding to 'deal' or 'check'.
  const int num_players = acpc_game_.GetNbPlayers();
  const int gameLength = MaxGameLength();
  const int total_num_cards = MaxChanceOutcomes();
  return {num_players + 2 * total_num_cards + (2 + 1) * gameLength};
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), MaxChanceOutcomes(), and MaxGameLength().
MaxChanceNodesInHistory()
int open_spiel::universal_poker::UniversalPokerGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 220 of file universal_poker.h.
{ return MaxGameLength(); }
References MaxGameLength().
MaxChanceOutcomes()
int open_spiel::universal_poker::UniversalPokerGame::MaxChanceOutcomes () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 1095 of file universal_poker.cc.
{
  return acpc_game_.NumSuitsDeck() * acpc_game_.NumRanksDeck();
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRanksDeck(), and open_spiel::universal_poker::acpc_cpp::ACPCGame::NumSuitsDeck().
Referenced by InformationStateTensorShape(), and ObservationTensorShape().
MaxCommitment()
double open_spiel::universal_poker::UniversalPokerGame::MaxCommitment () const
Definition at line 1059 of file universal_poker.cc.
{
  int max_commit = 0;
  if (acpc_game_.IsLimitGame()) {
    // The most a player can put into the pot is the raise amounts on each round
    // times the maximum number of raises, plus the original chips they put in
    // to play, which has the big blind as an upper bound.
    const auto &acpc_game = acpc_game_.Game();
    max_commit = big_blind();
    for (int i = 0; i < acpc_game_.NumRounds(); ++i) {
      max_commit += acpc_game.maxRaises[i] * acpc_game.raiseSize[i];
    }
  } else {
    // In No-Limit games, this isn't true, as there is no maximum raise value,
    // so the limit is the number of chips that the player has.
    max_commit = acpc_game_.StackSize(0);
  }
  return static_cast<double>(max_commit);
}
References big_blind(), open_spiel::universal_poker::acpc_cpp::ACPCGame::Game(), i, open_spiel::universal_poker::acpc_cpp::ACPCGame::IsLimitGame(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRounds(), and open_spiel::universal_poker::acpc_cpp::ACPCGame::StackSize().
Referenced by MaxUtility(), and MinUtility().
MaxGameLength()
int open_spiel::universal_poker::UniversalPokerGame::MaxGameLength () const override virtual
Implements open_spiel::Game.
Definition at line 1112 of file universal_poker.cc.
{
  // We cache this as this is very slow to calculate.
  if (max_game_length_) return *max_game_length_;
  // Make a good guess here because bruteforcing the tree is far too slow
  // One Terminal Action
  int length = 1;
  // Deal Actions
  length += acpc_game_.GetTotalNbBoardCards() +
            acpc_game_.GetNbHoleCardsRequired() * acpc_game_.GetNbPlayers();
  // The longest game (with a single betting round, for simplicity) consists of:
  // n-1 players checking,
  // 1 player betting, n-2 players calling,
  // 1 player raising, n-2 players calling,
  // etc...,
  // 1 player raising, n-1 players calling
  // Check Actions
  length += (NumPlayers() * acpc_game_.NumRounds());
  // Bet/Raise/Call Actions
  double maxStack = 0;
  double maxBlind = 0;
  for (uint32_t p = 0; p < NumPlayers(); p++) {
    maxStack =
        acpc_game_.StackSize(p) > maxStack ? acpc_game_.StackSize(p) : maxStack;
    maxBlind =
        acpc_game_.BlindSize(p) > maxBlind ? acpc_game_.BlindSize(p) : maxBlind;
  }
  int max_num_raises = 0;
  if (betting_abstraction_ == BettingAbstraction::kFC) {
    // no raises
  } else if (betting_abstraction_ == BettingAbstraction::kFCPA) {
    double pot_size = maxBlind * NumPlayers();
    while (pot_size / NumPlayers() < maxStack) {
      max_num_raises++;
      pot_size += pot_size * NumPlayers();
    }
  } else if (betting_abstraction_ == BettingAbstraction::kFCHPA) {
    double pot_size = maxBlind * NumPlayers();
    while (pot_size / NumPlayers() < maxStack) {
      max_num_raises++;
      pot_size += NumPlayers() * pot_size/2;
    }
  } else if (betting_abstraction_ == BettingAbstraction::kFULLGAME) {
    max_num_raises = (maxStack + maxBlind - 1)/maxBlind;  // ceil divide
  } else {
    SpielFatalError("Unknown Betting Abstraction");
  }
  // each bet/raise is followed by n-2 calls, for a total of n-1 actions:
  length += max_num_raises * (NumPlayers() - 1);
  return length;
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::BlindSize(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbHoleCardsRequired(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetTotalNbBoardCards(), open_spiel::universal_poker::kFC, open_spiel::universal_poker::kFCHPA, open_spiel::universal_poker::kFCPA, open_spiel::universal_poker::kFULLGAME, NumPlayers(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRounds(), open_spiel::SpielFatalError(), and open_spiel::universal_poker::acpc_cpp::ACPCGame::StackSize().
Referenced by InformationStateTensorShape(), MaxChanceNodesInHistory(), and UniversalPokerGame().
MaxUtility()
double open_spiel::universal_poker::UniversalPokerGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 1078 of file universal_poker.cc.
{
  // In poker, the utility is defined as the money a player has at the end of
  // the game minus then money the player had before starting the game.
  // The most a player can win *per opponent* is the most each player can put
  // into the pot,
  // The maximum amount of money a player can win is the maximum bet any player
  // can make, times the number of players (excluding the original player).
  return MaxCommitment() * (acpc_game_.GetNbPlayers() - 1);
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), and MaxCommitment().
MinUtility()
double open_spiel::universal_poker::UniversalPokerGame::MinUtility () const override virtual
Implements open_spiel::Game.
Definition at line 1088 of file universal_poker.cc.
{
  // In poker, the utility is defined as the money a player has at the end of
  // the game minus then money the player had before starting the game. As such,
  // the most a player can lose is the maximum amount they can bet.
  return -1 * MaxCommitment();
}
References MaxCommitment().
NewInitialState()
std::unique_ptr< State > open_spiel::universal_poker::UniversalPokerGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 1030 of file universal_poker.cc.
{
  return absl::make_unique<UniversalPokerState>(shared_from_this());
}
NumDistinctActions()
int open_spiel::universal_poker::UniversalPokerGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 1101 of file universal_poker.cc.
{
  if (betting_abstraction_ == BettingAbstraction::kFULLGAME) {
    // 0 -> fold, 1 -> check/call, N -> bet size
    return max_stack_size_ + 1;
  } else if (betting_abstraction_ == BettingAbstraction::kFCHPA) {
    return kNumActionsFCHPA;
  } else {
    return GetMaxBettingActions(acpc_game_);
  }
}
References open_spiel::universal_poker::GetMaxBettingActions(), open_spiel::universal_poker::kFCHPA, open_spiel::universal_poker::kFULLGAME, and open_spiel::universal_poker::kNumActionsFCHPA.
NumPlayers()
int open_spiel::universal_poker::UniversalPokerGame::NumPlayers () const override virtual
Implements open_spiel::Game.
Definition at line 1099 of file universal_poker.cc.
{ return acpc_game_.GetNbPlayers(); }
References open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers().
Referenced by MaxGameLength().
ObservationTensorShape()
std::vector< int > open_spiel::universal_poker::UniversalPokerGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 1050 of file universal_poker.cc.
{
  // One-hot encoding for player number (who is to play).
  // 2 slots of cards (total_cards_ bits each): private card, public card
  // Followed by the contribution of each player to the pot
  const int num_players = acpc_game_.GetNbPlayers();
  const int total_num_cards = MaxChanceOutcomes();
  return {2 * (num_players + total_num_cards)};
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), and MaxChanceOutcomes().
parseParameters()
std::string open_spiel::universal_poker::UniversalPokerGame::parseParameters (const GameParameters & map)
Parses the Game Paramters and makes a gameDesc out of it
Parameters
map
Returns
Definition at line 1174 of file universal_poker.cc.
{
  std::string generated_gamedef = "GAMEDEF\n";
  absl::StrAppend(
      &generated_gamedef, ParameterValue<std::string>("betting"), "\n",
      "numPlayers = ", ParameterValue<int>("numPlayers"), "\n",
      "numRounds = ", ParameterValue<int>("numRounds"), "\n",
      "numsuits = ", ParameterValue<int>("numSuits"), "\n",
      "firstPlayer = ", ParameterValue<std::string>("firstPlayer"), "\n",
      "numRanks = ", ParameterValue<int>("numRanks"), "\n",
      "numHoleCards = ", ParameterValue<int>("numHoleCards"), "\n",
      "numBoardCards = ", ParameterValue<std::string>("numBoardCards"), "\n");
  std::string max_raises = ParameterValue<std::string>("maxRaises");
  if (!max_raises.empty()) {
    absl::StrAppend(&generated_gamedef, "maxRaises = ", max_raises, "\n");
  }
  if (ParameterValue<std::string>("betting") == "limit") {
    std::string raise_size = ParameterValue<std::string>("raiseSize");
    if (!raise_size.empty()) {
      absl::StrAppend(&generated_gamedef, "raiseSize = ", raise_size, "\n");
    }
  } else if (ParameterValue<std::string>("betting") == "nolimit") {
    std::string stack = ParameterValue<std::string>("stack");
    if (!stack.empty()) {
      absl::StrAppend(&generated_gamedef, "stack = ", stack, "\n");
    }
  } else {
    SpielFatalError(absl::StrCat("betting should be limit or nolimit, not ",
                                 ParameterValue<std::string>("betting")));
  }
  absl::StrAppend(&generated_gamedef,
                  "blind = ", ParameterValue<std::string>("blind"), "\n");
  absl::StrAppend(&generated_gamedef, "END GAMEDEF\n");
  std::vector<std::string> blinds =
      absl::StrSplit(ParameterValue<std::string>("blind"), ' ');
  big_blind_ = 0;
  for (const std::string &blind : blinds) {
    big_blind_ = std::max(big_blind_, std::stoi(blind));
  }
  // By requiring a blind/ante of at least a single chip, we're able to
  // structure the action space more intuitively in the kFULLGAME setting.
  // Specifically, action 0 -> fold, 1 -> call, and N -> raise to N chips.
  // While the ACPC server does not require it, in practice poker is always
  // played with a blind or ante, so this is a minor restriction.
  if (big_blind_ <= 0) {
    SpielFatalError("Must have a blind of at least one chip.");
  }
  std::vector<std::string> stacks =
      absl::StrSplit(ParameterValue<std::string>("stack"), ' ');
  max_stack_size_ = 0;
  for (const std::string &stack : stacks) {
    max_stack_size_ = std::max(max_stack_size_, std::stoi(stack));
  }
  return generated_gamedef;
}
References open_spiel::Game::ParameterValue(), open_spiel::SpielFatalError(), stack, absl::StrAppend(), absl::StrCat(), and absl::StrSplit().
UtilitySum()
absl::optional< double > open_spiel::universal_poker::UniversalPokerGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 215 of file universal_poker.h.
{ return 0; }
The documentation for this class was generated from the following files:
open_spiel/games/universal_poker/universal_poker.h
open_spiel/games/universal_poker/universal_poker.cc