open spiel: open_spiel::universal_poker::UniformRestrictedActions Class Reference
open_spiel::universal_poker::UniformRestrictedActions Class Reference
#include <universal_poker.h>
Public Member Functions
UniformRestrictedActions (absl::Span< const ActionType > actions)
ActionsAndProbs GetStatePolicy (const State &state) const
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
virtual ActionsAndProbs GetStatePolicy (const State &state, Player player) const
virtual ActionsAndProbs GetStatePolicy (const std::string &info_state) const
virtual std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const
Detailed Description
Definition at line 244 of file universal_poker.h.
Constructor & Destructor Documentation
UniformRestrictedActions()
open_spiel::universal_poker::UniformRestrictedActions::UniformRestrictedActions (absl::Span< const ActionType > actions) inline explicit
Definition at line 248 of file universal_poker.h.
      : actions_(actions.begin(), actions.end()),
        max_action_(*absl::c_max_element(actions)) {}
Member Function Documentation
GetStatePolicy()
ActionsAndProbs open_spiel::universal_poker::UniformRestrictedActions::GetStatePolicy (const State & state) const inline virtual
Reimplemented from open_spiel::Policy.
Definition at line 252 of file universal_poker.h.
{
    ActionsAndProbs policy;
    policy.reserve(actions_.size());
    const std::vector<Action> legal_actions = state.LegalActions();
    for (Action action : legal_actions) {
      if (actions_.contains(static_cast<ActionType>(action))) {
        policy.emplace_back(action, 1.);
      }
      if (policy.size() >= actions_.size() || action > max_action_) break;
    }
    // It is always legal to check/call.
    if (policy.empty()) {
      SPIEL_DCHECK_TRUE(absl::c_find(legal_actions, ActionType::kCall) !=
                        legal_actions.end());
      policy.push_back({static_cast<Action>(ActionType::kCall), 1.});
    }
    // If we have a non-empty policy, normalize it!
    if (policy.size() > 1) NormalizePolicy(&policy);
    return policy;
  }
References action, absl::c_find(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::contains(), open_spiel::universal_poker::kCall, open_spiel::NormalizePolicy(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::size(), SPIEL_DCHECK_TRUE, and state.
The documentation for this class was generated from the following file:
open_spiel/games/universal_poker/universal_poker.h