open spiel: absl::str_format_internal::FormatConversionSpecImpl Class Reference
absl::str_format_internal::FormatConversionSpecImpl Class Reference
#include <extension.h>
Public Member Functions
bool is_basic () const
bool has_left_flag () const
bool has_show_pos_flag () const
bool has_sign_col_flag () const
bool has_alt_flag () const
bool has_zero_flag () const
FormatConversionChar conversion_char () const
void set_conversion_char (FormatConversionChar c)
int width () const
int precision () const
template<typename T >
T Wrap ()
Friends
struct str_format_internal::FormatConversionSpecImplFriend
Detailed Description
Definition at line 274 of file extension.h.
Member Function Documentation
conversion_char()
FormatConversionChar absl::str_format_internal::FormatConversionSpecImpl::conversion_char () const inline
Definition at line 288 of file extension.h.
{
    // Keep this field first in the struct . It generates better code when
    // accessing it when ConversionSpec is passed by value in registers.
    static_assert(offsetof(FormatConversionSpecImpl, conv_) == 0, "");
    return conv_;
  }
Referenced by absl::FormatConversionSpec::conversion_char(), absl::str_format_internal::ConvertIntArg(), absl::str_format_internal::FormatConvertImpl(), and absl::str_format_internal::FormatConvertImpl().
has_alt_flag()
bool absl::str_format_internal::FormatConversionSpecImpl::has_alt_flag () const inline
Definition at line 285 of file extension.h.
{ return FlagsContains(flags_, Flags::kAlt); }
References absl::str_format_internal::FlagsContains(), and absl::str_format_internal::kAlt.
Referenced by absl::FormatConversionSpec::has_alt_flag().
has_left_flag()
bool absl::str_format_internal::FormatConversionSpecImpl::has_left_flag () const inline
Definition at line 278 of file extension.h.
{ return FlagsContains(flags_, Flags::kLeft); }
References absl::str_format_internal::FlagsContains(), and absl::str_format_internal::kLeft.
Referenced by absl::str_format_internal::FormatConvertImpl(), and absl::FormatConversionSpec::has_left_flag().
has_show_pos_flag()
bool absl::str_format_internal::FormatConversionSpecImpl::has_show_pos_flag () const inline
Definition at line 279 of file extension.h.
{
    return FlagsContains(flags_, Flags::kShowPos);
  }
References absl::str_format_internal::FlagsContains(), and absl::str_format_internal::kShowPos.
Referenced by absl::FormatConversionSpec::has_show_pos_flag().
has_sign_col_flag()
bool absl::str_format_internal::FormatConversionSpecImpl::has_sign_col_flag () const inline
Definition at line 282 of file extension.h.
{
    return FlagsContains(flags_, Flags::kSignCol);
  }
References absl::str_format_internal::FlagsContains(), and absl::str_format_internal::kSignCol.
Referenced by absl::FormatConversionSpec::has_sign_col_flag().
has_zero_flag()
bool absl::str_format_internal::FormatConversionSpecImpl::has_zero_flag () const inline
Definition at line 286 of file extension.h.
{ return FlagsContains(flags_, Flags::kZero); }
References absl::str_format_internal::FlagsContains(), and absl::str_format_internal::kZero.
Referenced by absl::FormatConversionSpec::has_zero_flag().
is_basic()
bool absl::str_format_internal::FormatConversionSpecImpl::is_basic () const inline
Definition at line 277 of file extension.h.
{ return flags_ == Flags::kBasic; }
References absl::str_format_internal::kBasic.
Referenced by absl::str_format_internal::ConvertIntArg(), and absl::FormatConversionSpec::is_basic().
precision()
int absl::str_format_internal::FormatConversionSpecImpl::precision () const inline
Definition at line 302 of file extension.h.
{ return precision_; }
Referenced by absl::str_format_internal::CheckFastPathSetting(), absl::str_format_internal::ConsumeConversion(), absl::str_format_internal::FormatConvertImpl(), absl::str_format_internal::FormatConvertImpl(), and absl::FormatConversionSpec::precision().
set_conversion_char()
void absl::str_format_internal::FormatConversionSpecImpl::set_conversion_char (FormatConversionChar c) inline
Definition at line 295 of file extension.h.
{ conv_ = c; }
References absl::c.
Referenced by absl::str_format_internal::ConvertIntArg().
width()
int absl::str_format_internal::FormatConversionSpecImpl::width () const inline
Definition at line 299 of file extension.h.
{ return width_; }
Referenced by absl::str_format_internal::CheckFastPathSetting(), absl::str_format_internal::ConsumeConversion(), absl::str_format_internal::FormatConvertImpl(), and absl::FormatConversionSpec::width().
Wrap()
template<typename T > T absl::str_format_internal::FormatConversionSpecImpl::Wrap () inline
Definition at line 305 of file extension.h.
           {
    return T(*this);
  }
Referenced by absl::str_format_internal::FormatConvertImpl().
Friends And Related Symbol Documentation
str_format_internal::FormatConversionSpecImplFriend
friend struct str_format_internal::FormatConversionSpecImplFriend friend
Definition at line 310 of file extension.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/str_format/extension.h