open spiel: absl::flags_internal::FlagImpl Class Reference
absl::flags_internal::FlagImpl Class Reference final
#include <flag.h>
Public Member Functions
constexpr FlagImpl (const char *name, const char *filename, FlagOpFn op, FlagHelpArg help, FlagValueStorageKind value_kind, FlagDefaultArg default_arg)
int64_t ReadOneWord () const ABSL_LOCKS_EXCLUDED(*DataGuard())
bool ReadOneBool () const ABSL_LOCKS_EXCLUDED(*DataGuard())
void Read (void *dst) const override ABSL_LOCKS_EXCLUDED(*DataGuard())
void Read (bool *value) const ABSL_LOCKS_EXCLUDED(*DataGuard())
template<typename T , absl::enable_if_t< flags_internal::StorageKind< T >()==FlagValueStorageKind::kOneWordAtomic, int > = 0>
void Read (T *value) const ABSL_LOCKS_EXCLUDED(*DataGuard())
template<typename T , typename std::enable_if< flags_internal::StorageKind< T >()==FlagValueStorageKind::kValueAndInitBit, int >::type = 0>
void Read (T *value) const ABSL_LOCKS_EXCLUDED(*DataGuard())
void Write (const void *src) ABSL_LOCKS_EXCLUDED(*DataGuard())
void SetCallback (const FlagCallbackFunc mutation_callback) ABSL_LOCKS_EXCLUDED(*DataGuard())
void InvokeCallback () const ABSL_EXCLUSIVE_LOCKS_REQUIRED(*DataGuard())
void AssertValidType (FlagFastTypeId type_id, const std::type_info *(*gen_rtti)()) const
Public Member Functions inherited from absl::CommandLineFlag
constexpr CommandLineFlag ()=default
CommandLineFlag (const CommandLineFlag &)=delete
CommandLineFlag & operator= (const CommandLineFlag &)=delete
template<typename T >
bool IsOfType () const
template<typename T >
absl::optional< T > TryGet () const
virtual bool IsRetired () const
bool ParseFrom (absl::string_view value, std::string *error)
Friends
template<typename T >
class Flag
class FlagState
Additional Inherited Members
Protected Member Functions inherited from absl::CommandLineFlag
~CommandLineFlag ()=default
Detailed Description
Definition at line 432 of file flag.h.
Constructor & Destructor Documentation
FlagImpl()
absl::flags_internal::FlagImpl::FlagImpl (const char * name, const char * filename, FlagOpFn op, FlagHelpArg help, FlagValueStorageKind value_kind, FlagDefaultArg default_arg) inline constexpr
Definition at line 434 of file flag.h.
      : name_(name),
        filename_(filename),
        op_(op),
        help_(help.source),
        help_source_kind_(static_cast<uint8_t>(help.kind)),
        value_storage_kind_(static_cast<uint8_t>(value_kind)),
        def_kind_(static_cast<uint8_t>(default_arg.kind)),
        modified_(false),
        on_command_line_(false),
        callback_(nullptr),
        default_value_(default_arg.source),
        data_guard_{} {}
Referenced by absl::flags_internal::FlagOps().
Member Function Documentation
AssertValidType()
void absl::flags_internal::FlagImpl::AssertValidType (FlagFastTypeId type_id, const std::type_info *(* gen_rtti)()) const
Definition at line 195 of file flag.cc.
{
  FlagFastTypeId lhs_type_id = flags_internal::FastTypeId(op_);
  // `rhs_type_id` is the fast type id corresponding to the declaration
  // visibile at the call site. `lhs_type_id` is the fast type id
  // corresponding to the type specified in flag definition. They must match
  //  for this operation to be well-defined.
  if (ABSL_PREDICT_TRUE(lhs_type_id == rhs_type_id)) return;
  const std::type_info* lhs_runtime_type_id =
      flags_internal::RuntimeTypeId(op_);
  const std::type_info* rhs_runtime_type_id = (*gen_rtti)();
  if (lhs_runtime_type_id == rhs_runtime_type_id) return;
#ifdef ABSL_INTERNAL_HAS_RTTI
  if (*lhs_runtime_type_id == *rhs_runtime_type_id) return;
#endif
  ABSL_INTERNAL_LOG(
      FATAL, absl::StrCat("Flag '", Name(),
                          "' is defined as one type and declared as another"));
}
References ABSL_INTERNAL_LOG, ABSL_PREDICT_TRUE, absl::flags_internal::FastTypeId(), absl::flags_internal::RuntimeTypeId(), and absl::StrCat().
InvokeCallback()
void absl::flags_internal::FlagImpl::InvokeCallback () const
Definition at line 328 of file flag.cc.
{
  if (!callback_) return;
  // Make a copy of the C-style function pointer that we are about to invoke
  // before we release the lock guarding it.
  FlagCallbackFunc cb = callback_->func;
  // If the flag has a mutation callback this function invokes it. While the
  // callback is being invoked the primary flag's mutex is unlocked and it is
  // re-locked back after call to callback is completed. Callback invocation is
  // guarded by flag's secondary mutex instead which prevents concurrent
  // callback invocation. Note that it is possible for other thread to grab the
  // primary lock and update flag's value at any time during the callback
  // invocation. This is by design. Callback can get a value of the flag if
  // necessary, but it might be different from the value initiated the callback
  // and it also can be different by the time the callback invocation is
  // completed. Requires that *primary_lock be held in exclusive mode; it may be
  // released and reacquired by the implementation.
  MutexRelock relock(*DataGuard());
  absl::MutexLock lock(&callback_->guard);
  cb();
}
Referenced by SetCallback().
Read() [1/4]
void absl::flags_internal::FlagImpl::Read (bool * value) const inline
Definition at line 454 of file flag.h.
{
    *value = ReadOneBool();
  }
References ReadOneBool().
Read() [2/4]
template<typename T , absl::enable_if_t< flags_internal::StorageKind< T >()==FlagValueStorageKind::kOneWordAtomic, int > = 0> void absl::flags_internal::FlagImpl::Read (T * value) const inline
Definition at line 461 of file flag.h.
{
    int64_t v = ReadOneWord();
    std::memcpy(value, static_cast<const void*>(&v), sizeof(T));
  }
References ReadOneWord(), and absl::v.
Read() [3/4]
template<typename T , typename std::enable_if< flags_internal::StorageKind< T >()==FlagValueStorageKind::kValueAndInitBit, int >::type = 0> void absl::flags_internal::FlagImpl::Read (T * value) const inline
Definition at line 469 of file flag.h.
{
    *value = absl::bit_cast<FlagValueAndInitBit<T>>(ReadOneWord()).value;
  }
References absl::bit_cast(), and ReadOneWord().
Read() [4/4]
void absl::flags_internal::FlagImpl::Read (void * dst) const override virtual
Implements absl::CommandLineFlag.
Definition at line 449 of file flag.cc.
{
  auto* guard = DataGuard();  // Make sure flag initialized
  switch (ValueStorageKind()) {
    case FlagValueStorageKind::kValueAndInitBit:
    case FlagValueStorageKind::kOneWordAtomic: {
      const int64_t one_word_val =
          OneWordValue().load(std::memory_order_acquire);
      std::memcpy(dst, &one_word_val, Sizeof(op_));
      break;
    }
    case FlagValueStorageKind::kSequenceLocked: {
      ReadSequenceLockedData(dst);
      break;
    }
    case FlagValueStorageKind::kAlignedBuffer: {
      absl::MutexLock l(guard);
      flags_internal::CopyConstruct(op_, AlignedBufferValue(), dst);
      break;
    }
  }
}
References absl::flags_internal::CopyConstruct(), absl::flags_internal::kAlignedBuffer, absl::flags_internal::kOneWordAtomic, absl::flags_internal::kSequenceLocked, absl::flags_internal::kValueAndInitBit, and absl::flags_internal::Sizeof().
ReadOneBool()
bool absl::flags_internal::FlagImpl::ReadOneBool () const
Definition at line 479 of file flag.cc.
{
  assert(ValueStorageKind() == FlagValueStorageKind::kValueAndInitBit);
  auto* guard = DataGuard();  // Make sure flag initialized
  (void)guard;
  return absl::bit_cast<FlagValueAndInitBit<bool>>(
             OneWordValue().load(std::memory_order_acquire))
      .value;
}
References absl::bit_cast(), and absl::flags_internal::kValueAndInitBit.
Referenced by Read().
ReadOneWord()
int64_t absl::flags_internal::FlagImpl::ReadOneWord () const
Definition at line 471 of file flag.cc.
{
  assert(ValueStorageKind() == FlagValueStorageKind::kOneWordAtomic ||
         ValueStorageKind() == FlagValueStorageKind::kValueAndInitBit);
  auto* guard = DataGuard();  // Make sure flag initialized
  (void)guard;
  return OneWordValue().load(std::memory_order_acquire);
}
References absl::flags_internal::kOneWordAtomic, and absl::flags_internal::kValueAndInitBit.
Referenced by Read().
SetCallback()
void absl::flags_internal::FlagImpl::SetCallback (const FlagCallbackFunc mutation_callback)
Definition at line 317 of file flag.cc.
{
  absl::MutexLock l(DataGuard());
  if (callback_ == nullptr) {
    callback_ = new FlagCallback;
  }
  callback_->func = mutation_callback;
  InvokeCallback();
}
References InvokeCallback().
Write()
void absl::flags_internal::FlagImpl::Write (const void * src)
Definition at line 502 of file flag.cc.
{
  absl::MutexLock l(DataGuard());
  if (ShouldValidateFlagValue(flags_internal::FastTypeId(op_))) {
    std::unique_ptr<void, DynValueDeleter> obj{flags_internal::Clone(op_, src),
                                               DynValueDeleter{op_}};
    std::string ignored_error;
    std::string src_as_str = flags_internal::Unparse(op_, src);
    if (!flags_internal::Parse(op_, src_as_str, obj.get(), &ignored_error)) {
      ABSL_INTERNAL_LOG(ERROR, absl::StrCat("Attempt to set flag '", Name(),
                                            "' to invalid value ", src_as_str));
    }
  }
  StoreValue(src);
}
References ABSL_INTERNAL_LOG, absl::flags_internal::Clone(), absl::flags_internal::FastTypeId(), absl::flags_internal::Parse(), absl::StrCat(), and absl::flags_internal::Unparse().
Friends And Related Symbol Documentation
Flag
template<typename T > friend class Flag friend
Definition at line 492 of file flag.h.
FlagState
friend class FlagState friend
Definition at line 493 of file flag.h.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/flags/internal/flag.h
open_spiel/abseil-cpp/absl/flags/internal/flag.cc