open spiel: absl::cord_internal::CordRepBtree Class Reference
absl::cord_internal::CordRepBtree Class Reference
#include <cord_rep_btree.h>
Classes
struct CopyResult
struct OpResult
struct Position
Public Types
enum class EdgeType { kFront , kBack }
enum Action { kSelf , kCopied , kPopped }
Public Member Functions
CordRep * SubTree (size_t offset, size_t n)
char GetCharacter (size_t offset) const
bool IsFlat (absl::string_view *fragment) const
bool IsFlat (size_t offset, size_t n, absl::string_view *fragment) const
Span< char > GetAppendBuffer (size_t size)
int height () const
size_t begin () const
size_t back () const
size_t end () const
size_t index (EdgeType edge) const
size_t size () const
size_t capacity () const
CordRep * Edge (size_t index) const
CordRep * Edge (EdgeType edge_type) const
absl::Span< CordRep *const > Edges () const
absl::Span< CordRep *const > Edges (size_t begin, size_t end) const
absl::string_view Data (size_t index) const
template<EdgeType edge_type>
OpResult AddEdge (bool owned, CordRep *edge, size_t delta)
template<EdgeType edge_type>
OpResult SetEdge (bool owned, CordRep *edge, size_t delta)
Public Member Functions inherited from absl::cord_internal::CordRep
CordRep ()=default
constexpr CordRep (RefcountAndFlags::Immortal immortal, size_t l)
constexpr bool IsRing () const
constexpr bool IsSubstring () const
constexpr bool IsCrc () const
constexpr bool IsExternal () const
constexpr bool IsFlat () const
constexpr bool IsBtree () const
CordRepRing * ring ()
const CordRepRing * ring () const
CordRepSubstring * substring ()
const CordRepSubstring * substring () const
CordRepCrc * crc ()
const CordRepCrc * crc () const
CordRepExternal * external ()
const CordRepExternal * external () const
CordRepFlat * flat ()
const CordRepFlat * flat () const
CordRepBtree * btree ()
const CordRepBtree * btree () const
Static Public Member Functions
static CordRepBtree * Create (CordRep *rep)
static void Destroy (CordRepBtree *tree)
static void Delete (CordRepBtree *tree)
static void Unref (absl::Span< CordRep *const > edges)
static CordRepBtree * Append (CordRepBtree *tree, CordRep *rep)
static CordRepBtree * Prepend (CordRepBtree *tree, CordRep *rep)
static CordRepBtree * Append (CordRepBtree *tree, string_view data, size_t extra=0)
static CordRepBtree * Prepend (CordRepBtree *tree, string_view data, size_t extra=0)
static CordRep * RemoveSuffix (CordRepBtree *tree, size_t n)
static ExtractResult ExtractAppendBuffer (CordRepBtree *tree, size_t extra_capacity=1)
static bool IsValid (const CordRepBtree *tree, bool shallow=false)
static CordRepBtree * AssertValid (CordRepBtree *tree, bool shallow=true)
static const CordRepBtree * AssertValid (const CordRepBtree *tree, bool shallow=true)
static void Dump (const CordRep *rep, std::ostream &stream)
static void Dump (const CordRep *rep, absl::string_view label, std::ostream &stream)
static void Dump (const CordRep *rep, absl::string_view label, bool include_contents, std::ostream &stream)
static CordRepBtree * New (int height=0)
static CordRepBtree * New (CordRep *rep)
static CordRepBtree * New (CordRepBtree *front, CordRepBtree *back)
static CordRepBtree * Rebuild (CordRepBtree *tree)
static void Unref (CordRep *rep)
Static Public Member Functions inherited from absl::cord_internal::CordRep
static void Destroy (CordRep *rep)
static CordRep * Ref (CordRep *rep)
static void Unref (CordRep *rep)
Static Public Attributes
static constexpr EdgeType kFront = EdgeType::kFront
static constexpr EdgeType kBack = EdgeType::kBack
static constexpr size_t kMaxCapacity = 6
static constexpr size_t kMaxDepth = 12
static constexpr int kMaxHeight = static_cast<int>(kMaxDepth - 1)
Friends
class CordRepBtreeTestPeer
class CordRepBtreeNavigator
Additional Inherited Members
Public Attributes inherited from absl::cord_internal::CordRep
size_t length
RefcountAndFlags refcount
uint8_t tag
uint8_t storage [3]
Detailed Description
Definition at line 63 of file cord_rep_btree.h.
Member Enumeration Documentation
Action
enum absl::cord_internal::CordRepBtree::Action
Enumerator
kSelf
kCopied
kPopped
Definition at line 131 of file cord_rep_btree.h.
{ kSelf, kCopied, kPopped };
EdgeType
enum class absl::cord_internal::CordRepBtree::EdgeType strong
Enumerator
kFront
kBack
Definition at line 70 of file cord_rep_btree.h.
{ kFront, kBack };
Member Function Documentation
AddEdge()
template<EdgeType edge_type> OpResult absl::cord_internal::CordRepBtree::AddEdge (bool owned, CordRep * edge, size_t delta) inline
Definition at line 486 of file cord_rep_btree.cc.
{
  if (size() >= kMaxCapacity) return {New(edge), kPopped};
  OpResult result = ToOpResult(owned);
  result.tree->Add<edge_type>(edge);
  result.tree->length += delta;
  return result;
}
References kMaxCapacity, kPopped, absl::cord_internal::CordRep::length, New(), owned, size(), and absl::cord_internal::CordRepBtree::OpResult::tree.
Append() [1/2]
CordRepBtree * absl::cord_internal::CordRepBtree::Append (CordRepBtree * tree, CordRep * rep) inline static
Definition at line 904 of file cord_rep_btree.h.
{
  if (ABSL_PREDICT_TRUE(IsDataEdge(rep))) {
    return CordRepBtree::AddCordRep<kBack>(tree, rep);
  }
  return AppendSlow(tree, rep);
}
References ABSL_PREDICT_TRUE, absl::cord_internal::IsDataEdge(), and rep.
Referenced by absl::cordrep_testing::CordRepBtreeFromFlats().
Append() [2/2]
CordRepBtree * absl::cord_internal::CordRepBtree::Append (CordRepBtree * tree, absl::string_view data, size_t extra = 0) static
Definition at line 1079 of file cord_rep_btree.cc.
{
  return CordRepBtree::AddData<kBack>(tree, data, extra);
}
AssertValid() [1/2]
const CordRepBtree * absl::cord_internal::CordRepBtree::AssertValid (const CordRepBtree * tree, bool shallow = true) static
Definition at line 474 of file cord_rep_btree.cc.
{
  if (!IsValid(tree, shallow)) {
    Dump(tree, "CordRepBtree validation failed:", false, std::cout);
    ABSL_RAW_LOG(FATAL, "CordRepBtree::CheckValid() FAILED");
  }
  return tree;
}
References ABSL_RAW_LOG, Dump(), and IsValid().
AssertValid() [2/2]
CordRepBtree * absl::cord_internal::CordRepBtree::AssertValid (CordRepBtree * tree, bool shallow = true) static
Definition at line 466 of file cord_rep_btree.cc.
{
  if (!IsValid(tree, shallow)) {
    Dump(tree, "CordRepBtree validation failed:", false, std::cout);
    ABSL_RAW_LOG(FATAL, "CordRepBtree::CheckValid() FAILED");
  }
  return tree;
}
References ABSL_RAW_LOG, Dump(), and IsValid().
Referenced by RemoveSuffix(), and SubTree().
back()
size_t absl::cord_internal::CordRepBtree::back () const inline
Definition at line 290 of file cord_rep_btree.h.
{ return static_cast<size_t>(storage[2]) - 1; }
References absl::cord_internal::CordRep::storage.
Referenced by Edge(), index(), New(), absl::cord_internal::CordRepBtreeNavigator::Next(), SetEdge(), and SubTree().
begin()
size_t absl::cord_internal::CordRepBtree::begin () const inline
Definition at line 289 of file cord_rep_btree.h.
{ return static_cast<size_t>(storage[1]); }
References absl::cord_internal::CordRep::storage.
Referenced by Edge(), Edge(), Edges(), Edges(), index(), IsFlat(), IsValid(), absl::cord_internal::CordRepBtreeNavigator::Previous(), absl::cord_internal::CordRepBtreeNavigator::Read(), RemoveSuffix(), SetEdge(), size(), and absl::cord_internal::CordRepBtreeNavigator::Skip().
capacity()
size_t absl::cord_internal::CordRepBtree::capacity () const inline
Definition at line 303 of file cord_rep_btree.h.
{ return kMaxCapacity; }
References kMaxCapacity.
Referenced by IsValid().
Create()
CordRepBtree * absl::cord_internal::CordRepBtree::Create (CordRep * rep) inline static
Definition at line 843 of file cord_rep_btree.h.
{
  if (IsDataEdge(rep)) return New(rep);
  return CreateSlow(rep);
}
References absl::cord_internal::IsDataEdge(), New(), and rep.
Referenced by absl::cordrep_testing::CordRepBtreeFromFlats().
Data()
absl::string_view absl::cord_internal::CordRepBtree::Data (size_t index) const inline
Definition at line 629 of file cord_rep_btree.h.
{
  assert(height() == 0);
  return EdgeData(Edge(index));
}
References Edge(), absl::cord_internal::EdgeData(), height(), and index().
Referenced by GetCharacter(), and IsFlat().
Delete()
static void absl::cord_internal::CordRepBtree::Delete (CordRepBtree * tree) inline static
Definition at line 169 of file cord_rep_btree.h.
{ delete tree; }
Referenced by Destroy(), and ExtractAppendBuffer().
Destroy()
void absl::cord_internal::CordRepBtree::Destroy (CordRepBtree * tree) static
Definition at line 405 of file cord_rep_btree.cc.
{
  switch (tree->height()) {
    case 0:
      for (CordRep* edge : tree->Edges()) {
        if (!edge->refcount.Decrement()) {
          DeleteLeafEdge(edge);
        }
      }
      return CordRepBtree::Delete(tree);
    case 1:
      return DestroyTree<1>(tree);
    default:
      return DestroyTree<2>(tree);
  }
}
References Delete(), Edges(), and height().
Referenced by absl::cord_internal::CordRep::Destroy().
Dump() [1/3]
void absl::cord_internal::CordRepBtree::Dump (const CordRep * rep, absl::string_view label, bool include_contents, std::ostream & stream) static
Definition at line 365 of file cord_rep_btree.cc.
{
  stream << "===================================\n";
  if (!label.empty()) {
    stream << label << '\n';
    stream << "-----------------------------------\n";
  }
  if (rep) {
    DumpAll(rep, include_contents, stream);
  } else {
    stream << "NULL\n";
  }
}
References absl::string_view::empty(), and rep.
Dump() [2/3]
void absl::cord_internal::CordRepBtree::Dump (const CordRep * rep, absl::string_view label, std::ostream & stream) static
Definition at line 379 of file cord_rep_btree.cc.
{
  Dump(rep, label, false, stream);
}
References Dump(), and rep.
Dump() [3/3]
void absl::cord_internal::CordRepBtree::Dump (const CordRep * rep, std::ostream & stream) static
Definition at line 384 of file cord_rep_btree.cc.
{
  Dump(rep, absl::string_view(), false, stream);
}
References Dump(), and rep.
Referenced by AssertValid(), AssertValid(), Dump(), and Dump().
Edge() [1/2]
CordRep * absl::cord_internal::CordRepBtree::Edge (EdgeType edge_type) const inline
Definition at line 613 of file cord_rep_btree.h.
{
  return edges_[edge_type == kFront ? begin() : back()];
}
References back(), begin(), and kFront.
Edge() [2/2]
CordRep * absl::cord_internal::CordRepBtree::Edge (size_t index) const inline
Definition at line 607 of file cord_rep_btree.h.
{
  assert(index >= begin());
  assert(index < end());
  return edges_[index];
}
References begin(), end(), and index().
Referenced by absl::cord_internal::CordRepBtreeNavigator::Current(), Data(), ExtractAppendBuffer(), GetAppendBuffer(), GetCharacter(), IsFlat(), absl::cord_internal::CordRepBtreeNavigator::Next(), absl::cord_internal::CordRepBtreeNavigator::Previous(), absl::cord_internal::CordRepBtreeNavigator::Read(), RemoveSuffix(), absl::cord_internal::CordRepBtreeNavigator::Seek(), and absl::cord_internal::CordRepBtreeNavigator::Skip().
Edges() [1/2]
absl::Span< CordRep *const > absl::cord_internal::CordRepBtree::Edges () const inline
Definition at line 617 of file cord_rep_btree.h.
{
  return {edges_ + begin(), size()};
}
References begin(), and size().
Referenced by Destroy(), IsValid(), SetEdge(), and SubTree().
Edges() [2/2]
absl::Span< CordRep *const > absl::cord_internal::CordRepBtree::Edges (size_t begin, size_t end) const inline
Definition at line 621 of file cord_rep_btree.h.
{
  assert(begin <= end);
  assert(begin >= this->begin());
  assert(end <= this->end());
  return {edges_ + begin, static_cast<size_t>(end - begin)};
}
References begin(), and end().
end()
size_t absl::cord_internal::CordRepBtree::end () const inline
Definition at line 291 of file cord_rep_btree.h.
{ return static_cast<size_t>(storage[2]); }
References absl::cord_internal::CordRep::storage.
Referenced by Edge(), Edges(), ExtractAppendBuffer(), IsValid(), absl::cord_internal::CordRepBtreeNavigator::Read(), size(), and absl::cord_internal::CordRepBtreeNavigator::Skip().
ExtractAppendBuffer()
CordRepBtree::ExtractResult absl::cord_internal::CordRepBtree::ExtractAppendBuffer (CordRepBtree * tree, size_t extra_capacity = 1) static
Definition at line 1157 of file cord_rep_btree.cc.
{
  int depth = 0;
  NodeStack stack;
  // Set up default 'no success' result which is {tree, nullptr}.
  ExtractResult result;
  result.tree = tree;
  result.extracted = nullptr;
  // Dive down the right side of the tree, making sure no edges are shared.
  while (tree->height() > 0) {
    if (!tree->refcount.IsOne()) return result;
    stack[depth++] = tree;
    tree = tree->Edge(kBack)->btree();
  }
  if (!tree->refcount.IsOne()) return result;
  // Validate we ended on a non shared flat.
  CordRep* rep = tree->Edge(kBack);
  if (!(rep->IsFlat() && rep->refcount.IsOne())) return result;
  // Verify it has at least the requested extra capacity.
  CordRepFlat* flat = rep->flat();
  const size_t length = flat->length;
  const size_t avail = flat->Capacity() - flat->length;
  if (extra_capacity > avail) return result;
  // Set the extracted flat in the result.
  result.extracted = flat;
  // Cascading delete all nodes that become empty.
  while (tree->size() == 1) {
    CordRepBtree::Delete(tree);
    if (--depth < 0) {
      // We consumed the entire tree: return nullptr for new tree.
      result.tree = nullptr;
      return result;
    }
    rep = tree;
    tree = stack[depth];
  }
  // Remove the edge or cascaded up parent node.
  tree->set_end(tree->end() - 1);
  tree->length -= length;
  // Adjust lengths up the tree.
  while (depth > 0) {
    tree = stack[--depth];
    tree->length -= length;
  }
  // Remove unnecessary top nodes with size = 1. This may iterate all the way
  // down to the leaf node in which case we simply return the remaining last
  // edge in that node and the extracted flat.
  while (tree->size() == 1) {
    int height = tree->height();
    rep = tree->Edge(kBack);
    Delete(tree);
    if (height == 0) {
      // We consumed the leaf: return the sole data edge as the new tree.
      result.tree = rep;
      return result;
    }
    tree = rep->btree();
  }
  // Done: return the (new) top level node and extracted flat.
  result.tree = tree;
  return result;
}
References absl::cord_internal::CordRep::btree(), absl::cord_internal::CordRepFlat::Capacity(), Delete(), Edge(), end(), absl::cord_internal::CordRep::ExtractResult::extracted, absl::cord_internal::CordRep::flat(), height(), absl::cord_internal::RefcountAndFlags::IsOne(), kBack, absl::cord_internal::CordRep::length, absl::cord_internal::CordRep::refcount, rep, size(), stack, and absl::cord_internal::CordRep::ExtractResult::tree.
GetAppendBuffer()
Span< char > absl::cord_internal::CordRepBtree::GetAppendBuffer (size_t size) inline
Definition at line 848 of file cord_rep_btree.h.
{
  assert(refcount.IsOne());
  CordRepBtree* tree = this;
  const int height = this->height();
  CordRepBtree* n1 = tree;
  CordRepBtree* n2 = tree;
  CordRepBtree* n3 = tree;
  switch (height) {
    case 3:
      tree = tree->Edge(kBack)->btree();
      if (!tree->refcount.IsOne()) return {};
      n2 = tree;
      ABSL_FALLTHROUGH_INTENDED;
    case 2:
      tree = tree->Edge(kBack)->btree();
      if (!tree->refcount.IsOne()) return {};
      n1 = tree;
      ABSL_FALLTHROUGH_INTENDED;
    case 1:
      tree = tree->Edge(kBack)->btree();
      if (!tree->refcount.IsOne()) return {};
      ABSL_FALLTHROUGH_INTENDED;
    case 0:
      CordRep* edge = tree->Edge(kBack);
      if (!edge->refcount.IsOne()) return {};
      if (edge->tag < FLAT) return {};
      size_t avail = edge->flat()->Capacity() - edge->length;
      if (avail == 0) return {};
      size_t delta = (std::min)(size, avail);
      Span<char> span = {edge->flat()->Data() + edge->length, delta};
      edge->length += delta;
      switch (height) {
        case 3:
          n3->length += delta;
          ABSL_FALLTHROUGH_INTENDED;
        case 2:
          n2->length += delta;
          ABSL_FALLTHROUGH_INTENDED;
        case 1:
          n1->length += delta;
          ABSL_FALLTHROUGH_INTENDED;
        case 0:
          tree->length += delta;
          return span;
      }
      break;
  }
  return GetAppendBufferSlow(size);
}
References ABSL_FALLTHROUGH_INTENDED, absl::cord_internal::CordRep::btree(), absl::cord_internal::CordRepFlat::Capacity(), absl::cord_internal::CordRepFlat::Data(), Edge(), absl::cord_internal::FLAT, absl::cord_internal::CordRep::flat(), height(), absl::cord_internal::RefcountAndFlags::IsOne(), kBack, absl::cord_internal::CordRep::length, absl::cord_internal::CordRep::refcount, size(), and absl::cord_internal::CordRep::tag.
GetCharacter()
char absl::cord_internal::CordRepBtree::GetCharacter (size_t offset) const
Definition at line 992 of file cord_rep_btree.cc.
{
  assert(offset < length);
  const CordRepBtree* node = this;
  int height = node->height();
  for (;;) {
    Position front = node->IndexOf(offset);
    if (--height < 0) return node->Data(front.index)[front.n];
    offset = front.n;
    node = node->Edge(front.index)->btree();
  }
}
References absl::cord_internal::CordRep::btree(), Data(), Edge(), height(), absl::cord_internal::CordRepBtree::Position::index, absl::cord_internal::CordRep::length, and absl::cord_internal::CordRepBtree::Position::n.
Referenced by absl::Cord::operator[]().
height()
int absl::cord_internal::CordRepBtree::height () const inline
Definition at line 286 of file cord_rep_btree.h.
{ return static_cast<int>(storage[0]); }
References absl::cord_internal::CordRep::storage.
Referenced by Data(), Destroy(), ExtractAppendBuffer(), GetAppendBuffer(), GetCharacter(), absl::cord_internal::CordRepBtreeNavigator::InitOffset(), IsFlat(), IsFlat(), IsValid(), New(), New(), New(), RemoveSuffix(), and SubTree().
index()
size_t absl::cord_internal::CordRepBtree::index (EdgeType edge) const inline
Definition at line 292 of file cord_rep_btree.h.
{
    return edge == kFront ? begin() : back();
  }
References back(), begin(), and kFront.
Referenced by open_spiel.python.egt.visualization.SimplexStreamMask::__getitem__(), open_spiel.python.egt.visualization.SimplexStreamMask::__setitem__(), Data(), Edge(), and SetEdge().
IsFlat() [1/2]
bool absl::cord_internal::CordRepBtree::IsFlat (absl::string_view * fragment) const
Definition at line 964 of file cord_rep_btree.cc.
{
  if (height() == 0 && size() == 1) {
    if (fragment) *fragment = Data(begin());
    return true;
  }
  return false;
}
References begin(), Data(), height(), and size().
IsFlat() [2/2]
bool absl::cord_internal::CordRepBtree::IsFlat (size_t offset, size_t n, absl::string_view * fragment) const
Definition at line 972 of file cord_rep_btree.cc.
{
  assert(n <= this->length);
  assert(offset <= this->length - n);
  if (ABSL_PREDICT_FALSE(n == 0)) return false;
  int height = this->height();
  const CordRepBtree* node = this;
  for (;;) {
    const Position front = node->IndexOf(offset);
    const CordRep* edge = node->Edge(front.index);
    if (edge->length < front.n + n) return false;
    if (--height < 0) {
      if (fragment) *fragment = EdgeData(edge).substr(front.n, n);
      return true;
    }
    offset = front.n;
    node = node->Edge(front.index)->btree();
  }
}
References ABSL_PREDICT_FALSE, absl::cord_internal::CordRep::btree(), Edge(), absl::cord_internal::EdgeData(), height(), absl::cord_internal::CordRepBtree::Position::index, absl::cord_internal::CordRep::length, absl::cord_internal::CordRepBtree::Position::n, absl::n, and absl::string_view::substr().
IsValid()
bool absl::cord_internal::CordRepBtree::IsValid (const CordRepBtree * tree, bool shallow = false) static
Definition at line 421 of file cord_rep_btree.cc.
{
#define NODE_CHECK_VALID(x)                                           \
  if (!(x)) {                                                         \
    ABSL_RAW_LOG(ERROR, "CordRepBtree::CheckValid() FAILED: %s", #x); \
    return false;                                                     \
  }
#define NODE_CHECK_EQ(x, y)                                                    \
  if ((x) != (y)) {                                                            \
    ABSL_RAW_LOG(ERROR,                                                        \
                 "CordRepBtree::CheckValid() FAILED: %s != %s (%s vs %s)", #x, \
                 #y, absl::StrCat(x).c_str(), absl::StrCat(y).c_str());        \
    return false;                                                              \
  }
  NODE_CHECK_VALID(tree != nullptr);
  NODE_CHECK_VALID(tree->IsBtree());
  NODE_CHECK_VALID(tree->height() <= kMaxHeight);
  NODE_CHECK_VALID(tree->begin() < tree->capacity());
  NODE_CHECK_VALID(tree->end() <= tree->capacity());
  NODE_CHECK_VALID(tree->begin() <= tree->end());
  size_t child_length = 0;
  for (CordRep* edge : tree->Edges()) {
    NODE_CHECK_VALID(edge != nullptr);
    if (tree->height() > 0) {
      NODE_CHECK_VALID(edge->IsBtree());
      NODE_CHECK_VALID(edge->btree()->height() == tree->height() - 1);
    } else {
      NODE_CHECK_VALID(IsDataEdge(edge));
    }
    child_length += edge->length;
  }
  NODE_CHECK_EQ(child_length, tree->length);
  if ((!shallow || exhaustive_validation()) && tree->height() > 0) {
    for (CordRep* edge : tree->Edges()) {
      if (!IsValid(edge->btree(), shallow)) return false;
    }
  }
  return true;
#undef NODE_CHECK_VALID
#undef NODE_CHECK_EQ
}
References begin(), capacity(), Edges(), end(), height(), absl::cord_internal::CordRep::IsBtree(), absl::cord_internal::IsDataEdge(), IsValid(), kMaxHeight, absl::cord_internal::CordRep::length, NODE_CHECK_EQ, and NODE_CHECK_VALID.
Referenced by AssertValid(), AssertValid(), and IsValid().
New() [1/3]
CordRepBtree * absl::cord_internal::CordRepBtree::New (CordRep * rep) inline static
Definition at line 641 of file cord_rep_btree.h.
{
  CordRepBtree* tree = new CordRepBtree;
  int height = rep->IsBtree() ? rep->btree()->height() + 1 : 0;
  tree->length = rep->length;
  tree->InitInstance(height, /*begin=*/0, /*end=*/1);
  tree->edges_[0] = rep;
  return tree;
}
References height(), absl::cord_internal::CordRep::IsBtree(), absl::cord_internal::CordRep::length, and rep.
New() [2/3]
CordRepBtree * absl::cord_internal::CordRepBtree::New (CordRepBtree * front, CordRepBtree * back) inline static
Definition at line 650 of file cord_rep_btree.h.
{
  assert(front->height() == back->height());
  CordRepBtree* tree = new CordRepBtree;
  tree->length = front->length + back->length;
  tree->InitInstance(front->height() + 1, /*begin=*/0, /*end=*/2);
  tree->edges_[0] = front;
  tree->edges_[1] = back;
  return tree;
}
References back(), height(), and absl::cord_internal::CordRep::length.
New() [3/3]
CordRepBtree * absl::cord_internal::CordRepBtree::New (int height = 0) inline static
Definition at line 634 of file cord_rep_btree.h.
{
  CordRepBtree* tree = new CordRepBtree;
  tree->length = 0;
  tree->InitInstance(height);
  return tree;
}
References height(), and absl::cord_internal::CordRep::length.
Referenced by AddEdge(), Create(), absl::cord_internal::CordRepBtreeNavigator::Read(), Rebuild(), and SubTree().
Prepend() [1/2]
CordRepBtree * absl::cord_internal::CordRepBtree::Prepend (CordRepBtree * tree, CordRep * rep) inline static
Definition at line 911 of file cord_rep_btree.h.
{
  if (ABSL_PREDICT_TRUE(IsDataEdge(rep))) {
    return CordRepBtree::AddCordRep<kFront>(tree, rep);
  }
  return PrependSlow(tree, rep);
}
References ABSL_PREDICT_TRUE, absl::cord_internal::IsDataEdge(), and rep.
Prepend() [2/2]
CordRepBtree * absl::cord_internal::CordRepBtree::Prepend (CordRepBtree * tree, absl::string_view data, size_t extra = 0) static
Definition at line 1084 of file cord_rep_btree.cc.
{
  return CordRepBtree::AddData<kFront>(tree, data, extra);
}
Rebuild()
CordRepBtree * absl::cord_internal::CordRepBtree::Rebuild (CordRepBtree * tree) static
Definition at line 1138 of file cord_rep_btree.cc.
{
  // Set up initial stack with empty leaf node.
  CordRepBtree* node = CordRepBtree::New();
  CordRepBtree* stack[CordRepBtree::kMaxDepth + 1] = {node};
  // Recursively build the tree, consuming the input tree.
  Rebuild(stack, tree, /* consume reference */ true);
  // Return top most node
  for (CordRepBtree* parent : stack) {
    if (parent == nullptr) return node;
    node = parent;
  }
  // Unreachable
  assert(false);
  return nullptr;
}
References kMaxDepth, New(), Rebuild(), and stack.
Referenced by Rebuild().
RemoveSuffix()
CordRep * absl::cord_internal::CordRepBtree::RemoveSuffix (CordRepBtree * tree, size_t n) static
Definition at line 832 of file cord_rep_btree.cc.
{
  // Check input and deal with trivial cases 'Remove all/none'
  assert(tree != nullptr);
  assert(n <= tree->length);
  const size_t len = tree->length;
  if (ABSL_PREDICT_FALSE(n == 0)) {
    return tree;
  }
  if (ABSL_PREDICT_FALSE(n >= len)) {
    CordRepBtree::Unref(tree);
    return nullptr;
  }
  size_t length = len - n;
  int height = tree->height();
  bool is_mutable = tree->refcount.IsOne();
  // Extract all top nodes which are reduced to size = 1
  Position pos = tree->IndexOfLength(length);
  while (pos.index == tree->begin()) {
    CordRep* edge = ExtractFront(tree);
    is_mutable &= edge->refcount.IsOne();
    if (height-- == 0) return ResizeEdge(edge, length, is_mutable);
    tree = edge->btree();
    pos = tree->IndexOfLength(length);
  }
  // Repeat the following sequence traversing down the tree:
  // - Crop the top node to the 'last remaining edge' adjusting length.
  // - Set the length for down edges to the partial length in that last edge.
  // - Repeat this until the last edge is 'included in full'
  // - If we hit the data edge level, resize and return the last data edge
  CordRepBtree* top = tree = ConsumeBeginTo(tree, pos.index + 1, length);
  CordRep* edge = tree->Edge(pos.index);
  length = pos.n;
  while (length != edge->length) {
    // ConsumeBeginTo guarantees `tree` is a clean, privately owned copy.
    assert(tree->refcount.IsOne());
    const bool edge_is_mutable = edge->refcount.IsOne();
    if (height-- == 0) {
      tree->edges_[pos.index] = ResizeEdge(edge, length, edge_is_mutable);
      return AssertValid(top);
    }
    if (!edge_is_mutable) {
      // We can't 'in place' remove any suffixes down this edge.
      // Replace this edge with a prefix copy instead.
      tree->edges_[pos.index] = edge->btree()->CopyPrefix(length, false).edge;
      CordRep::Unref(edge);
      return AssertValid(top);
    }
    // Move down one level, rinse repeat.
    tree = edge->btree();
    pos = tree->IndexOfLength(length);
    tree = ConsumeBeginTo(edge->btree(), pos.index + 1, length);
    edge = tree->Edge(pos.index);
    length = pos.n;
  }
  return AssertValid(top);
}
References ABSL_PREDICT_FALSE, AssertValid(), begin(), absl::cord_internal::CordRep::btree(), Edge(), absl::cord_internal::CordRepBtree::CopyResult::edge, height(), absl::cord_internal::RefcountAndFlags::IsOne(), len, absl::cord_internal::CordRep::length, absl::n, absl::cord_internal::CordRep::refcount, absl::cord_internal::CordRep::Unref(), and Unref().
SetEdge()
template<EdgeType edge_type> OpResult absl::cord_internal::CordRepBtree::SetEdge (bool owned, CordRep * edge, size_t delta)
Definition at line 495 of file cord_rep_btree.cc.
{
  OpResult result;
  const size_t idx = index(edge_type);
  if (owned) {
    result = {this, kSelf};
    CordRep::Unref(edges_[idx]);
  } else {
    // Create a copy containing all unchanged edges. Unchanged edges are the
    // open interval [begin, back) or [begin + 1, end) depending on `edge_type`.
    // We conveniently cover both case using a constexpr `shift` being 0 or 1
    // as `end :== back + 1`.
    result = {CopyRaw(length), kCopied};
    constexpr int shift = edge_type == kFront ? 1 : 0;
    for (CordRep* r : Edges(begin() + shift, back() + shift)) {
      CordRep::Ref(r);
    }
  }
  result.tree->edges_[idx] = edge;
  result.tree->length += delta;
  return result;
}
References back(), begin(), Edges(), index(), kCopied, kFront, kSelf, absl::cord_internal::CordRep::length, owned, r, absl::cord_internal::CordRep::Ref(), absl::cord_internal::CordRepBtree::OpResult::tree, and absl::cord_internal::CordRep::Unref().
size()
size_t absl::cord_internal::CordRepBtree::size () const inline
Definition at line 302 of file cord_rep_btree.h.
{ return end() - begin(); }
References begin(), and end().
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), AddEdge(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), Edges(), ExtractAppendBuffer(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), GetAppendBuffer(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), IsFlat(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
SubTree()
CordRep * absl::cord_internal::CordRepBtree::SubTree (size_t offset, size_t n)
Definition at line 896 of file cord_rep_btree.cc.
{
  assert(n <= this->length);
  assert(offset <= this->length - n);
  if (ABSL_PREDICT_FALSE(n == 0)) return nullptr;
  CordRepBtree* node = this;
  int height = node->height();
  Position front = node->IndexOf(offset);
  CordRep* left = node->edges_[front.index];
  while (front.n + n <= left->length) {
    if (--height < 0) return MakeSubstring(CordRep::Ref(left), front.n, n);
    node = left->btree();
    front = node->IndexOf(front.n);
    left = node->edges_[front.index];
  }
  const Position back = node->IndexBefore(front, n);
  CordRep* const right = node->edges_[back.index];
  assert(back.index > front.index);
  // Get partial suffix and prefix entries.
  CopyResult prefix;
  CopyResult suffix;
  if (height > 0) {
    // Copy prefix and suffix of the boundary nodes.
    prefix = left->btree()->CopySuffix(front.n);
    suffix = right->btree()->CopyPrefix(back.n);
    // If there is an edge between the prefix and suffix edges, then the tree
    // must remain at its previous (full) height. If we have no edges between
    // prefix and suffix edges, then the tree must be as high as either the
    // suffix or prefix edges (which are collapsed to their minimum heights).
    if (front.index + 1 == back.index) {
      height = (std::max)(prefix.height, suffix.height) + 1;
    }
    // Raise prefix and suffixes to the new tree height.
    for (int h = prefix.height + 1; h < height; ++h) {
      prefix.edge = CordRepBtree::New(prefix.edge);
    }
    for (int h = suffix.height + 1; h < height; ++h) {
      suffix.edge = CordRepBtree::New(suffix.edge);
    }
  } else {
    // Leaf node, simply take substrings for prefix and suffix.
    prefix = CopyResult{MakeSubstring(CordRep::Ref(left), front.n), -1};
    suffix = CopyResult{MakeSubstring(CordRep::Ref(right), 0, back.n), -1};
  }
  // Compose resulting tree.
  CordRepBtree* sub = CordRepBtree::New(height);
  size_t end = 0;
  sub->edges_[end++] = prefix.edge;
  for (CordRep* r : node->Edges(front.index + 1, back.index)) {
    sub->edges_[end++] = CordRep::Ref(r);
  }
  sub->edges_[end++] = suffix.edge;
  sub->set_end(end);
  sub->length = n;
  return AssertValid(sub);
}
References ABSL_PREDICT_FALSE, AssertValid(), back(), absl::cord_internal::CordRep::btree(), absl::cord_internal::CordRepBtree::CopyResult::edge, Edges(), absl::cord_internal::CordRepBtree::CopyResult::height, height(), absl::cord_internal::CordRepBtree::Position::index, absl::cord_internal::CordRep::length, absl::cord_internal::CordRepBtree::Position::n, absl::n, New(), r, and absl::cord_internal::CordRep::Ref().
Referenced by absl::Cord::RemovePrefix(), and absl::Cord::Subcord().
Unref() [1/2]
void absl::cord_internal::CordRepBtree::Unref (absl::Span< CordRep *const > edges) inline static
Definition at line 661 of file cord_rep_btree.h.
{
  for (CordRep* edge : edges) {
    if (ABSL_PREDICT_FALSE(!edge->refcount.Decrement())) {
      CordRep::Destroy(edge);
    }
  }
}
References ABSL_PREDICT_FALSE, and absl::cord_internal::CordRep::Destroy().
Referenced by RemoveSuffix().
Unref() [2/2]
void absl::cord_internal::CordRep::Unref (CordRep * rep) inline static
Definition at line 334 of file cord_internal.h.
{
  assert(rep != nullptr);
  // Expect refcount to be 0. Avoiding the cost of an atomic decrement should
  // typically outweigh the cost of an extra branch checking for ref == 1.
  if (ABSL_PREDICT_FALSE(!rep->refcount.DecrementExpectHighRefcount())) {
    Destroy(rep);
  }
}
Friends And Related Symbol Documentation
CordRepBtreeNavigator
friend class CordRepBtreeNavigator friend
Definition at line 587 of file cord_rep_btree.h.
CordRepBtreeTestPeer
friend class CordRepBtreeTestPeer friend
Definition at line 586 of file cord_rep_btree.h.
Member Data Documentation
kBack
EdgeType absl::cord_internal::CordRepBtree::kBack = EdgeType::kBack static constexpr
Definition at line 74 of file cord_rep_btree.h.
Referenced by ExtractAppendBuffer(), and GetAppendBuffer().
kFront
EdgeType absl::cord_internal::CordRepBtree::kFront = EdgeType::kFront static constexpr
Definition at line 73 of file cord_rep_btree.h.
Referenced by Edge(), index(), and SetEdge().
kMaxCapacity
size_t absl::cord_internal::CordRepBtree::kMaxCapacity = 6 static constexpr
Definition at line 81 of file cord_rep_btree.h.
Referenced by AddEdge(), and capacity().
kMaxDepth
size_t absl::cord_internal::CordRepBtree::kMaxDepth = 12 static constexpr
Definition at line 98 of file cord_rep_btree.h.
Referenced by Rebuild().
kMaxHeight
int absl::cord_internal::CordRepBtree::kMaxHeight = static_cast<int>(kMaxDepth - 1) static constexpr
Definition at line 100 of file cord_rep_btree.h.
Referenced by absl::cord_internal::CordRepBtreeNavigator::InitOffset(), and IsValid().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_btree.h
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_btree.cc