open spiel: absl_test.AbslTimeTest Class Reference
absl_test.AbslTimeTest Class Reference
Public Member Functions
test_return_positive_duration (self)
test_return_negative_duration (self)
test_pass_positive_duration (self)
test_pass_negative_duration (self)
test_pass_float_duration (self)
test_pass_integer_duration (self)
test_duration_integer_overflow (self)
test_return_datetime (self)
test_pass_date (self)
test_pass_datetime (self)
test_pass_datetime_with_timezone (self)
test_pass_datetime_dst_with_timezone (self)
test_pass_datetime_dst (self)
test_dst_datetime_from_timestamp (self, offs)
test_pass_datetime_pre_unix_epoch (self)
test_return_civilsecond (self)
test_pass_datetime_as_civilsecond (self)
test_return_civilminute (self)
test_pass_datetime_as_civilminute (self)
test_return_civilhour (self)
test_pass_datetime_as_civilhour (self)
test_return_civilday (self)
test_pass_datetime_as_civilday (self)
test_return_civilmonth (self)
test_pass_datetime_as_civilmonth (self)
test_return_civilyear (self)
test_pass_datetime_as_civilyear (self)
test_timezone (self)
Public Attributes
POSITIVE_SECS
NEGATIVE_SECS
SECONDS_IN_DAY
Static Public Attributes
int SECONDS_IN_DAY = 24 * 60 * 60
int POSITIVE_SECS = 3 * SECONDS_IN_DAY + 2.5
int NEGATIVE_SECS = -3 * SECONDS_IN_DAY + 2.5
TEST_DATETIME = datetime.datetime(2000, 1, 2, 3, 4, 5, int(5e5))
TEST_DATETIME_UTC = TEST_DATETIME.replace(tzinfo=tz.tzutc())
TEST_DATE = datetime.date(2000, 1, 2)
Detailed Description
Definition at line 18 of file absl_test.py.
Member Function Documentation
test_dst_datetime_from_timestamp()
absl_test.AbslTimeTest.test_dst_datetime_from_timestamp (self, offs)
Definition at line 114 of file absl_test.py.
  def test_dst_datetime_from_timestamp(self, offs):
    secs_flip = 1604224799  # 2020-11-01T02:00:00-08:00
    secs = secs_flip + offs
    time_utc = datetime.datetime.fromtimestamp(secs, tz.tzutc())
    time_local_aware = time_utc.astimezone(tz.gettz())
    time_local_naive = time_local_aware.replace(tzinfo=None)
    for time in (time_utc, time_local_aware, time_local_naive):
      self.assertTrue(absl_example.check_datetime(time, secs))
test_duration_integer_overflow()
absl_test.AbslTimeTest.test_duration_integer_overflow (self)
Definition at line 57 of file absl_test.py.
  def test_duration_integer_overflow(self):
    duration = 2**129
    with self.assertRaises(RuntimeError):
      absl_example.check_duration(duration, duration)
test_pass_date()
absl_test.AbslTimeTest.test_pass_date (self)
Definition at line 81 of file absl_test.py.
  def test_pass_date(self):
    secs = datetime.datetime(self.TEST_DATE.year, self.TEST_DATE.month,
                             self.TEST_DATE.day).timestamp()
    self.assertTrue(absl_example.check_datetime(self.TEST_DATE, secs))
References absl_test.AbslTimeTest.TEST_DATE.
test_pass_datetime()
absl_test.AbslTimeTest.test_pass_datetime (self)
Definition at line 86 of file absl_test.py.
  def test_pass_datetime(self):
    secs = self.TEST_DATETIME.timestamp()
    self.assertTrue(absl_example.check_datetime(self.TEST_DATETIME, secs))
References absl_test.AbslTimeTest.TEST_DATETIME.
test_pass_datetime_as_civilday()
absl_test.AbslTimeTest.test_pass_datetime_as_civilday (self)
Definition at line 174 of file absl_test.py.
  def test_pass_datetime_as_civilday(self):
    truncated = self.TEST_DATETIME_UTC.replace(
        hour=0, minute=0, second=0, microsecond=0)
    self.assertTrue(
        absl_example.check_civilday(self.TEST_DATETIME, truncated.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_pass_datetime_as_civilhour()
absl_test.AbslTimeTest.test_pass_datetime_as_civilhour (self)
Definition at line 161 of file absl_test.py.
  def test_pass_datetime_as_civilhour(self):
    truncated = self.TEST_DATETIME_UTC.replace(
        minute=0, second=0, microsecond=0)
    self.assertTrue(
        absl_example.check_civilhour(self.TEST_DATETIME, truncated.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_pass_datetime_as_civilminute()
absl_test.AbslTimeTest.test_pass_datetime_as_civilminute (self)
Definition at line 149 of file absl_test.py.
  def test_pass_datetime_as_civilminute(self):
    truncated = self.TEST_DATETIME_UTC.replace(second=0, microsecond=0)
    self.assertTrue(
        absl_example.check_civilminute(self.TEST_DATETIME,
                                       truncated.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_pass_datetime_as_civilmonth()
absl_test.AbslTimeTest.test_pass_datetime_as_civilmonth (self)
Definition at line 187 of file absl_test.py.
  def test_pass_datetime_as_civilmonth(self):
    truncated = self.TEST_DATETIME_UTC.replace(
        day=1, hour=0, minute=0, second=0, microsecond=0)
    self.assertTrue(
        absl_example.check_civilmonth(self.TEST_DATETIME,
                                      truncated.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_pass_datetime_as_civilsecond()
absl_test.AbslTimeTest.test_pass_datetime_as_civilsecond (self)
Definition at line 137 of file absl_test.py.
  def test_pass_datetime_as_civilsecond(self):
    truncated = self.TEST_DATETIME_UTC.replace(microsecond=0)
    self.assertTrue(
        absl_example.check_civilsecond(self.TEST_DATETIME,
                                       truncated.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_pass_datetime_as_civilyear()
absl_test.AbslTimeTest.test_pass_datetime_as_civilyear (self)
Definition at line 201 of file absl_test.py.
  def test_pass_datetime_as_civilyear(self):
    truncated = self.TEST_DATETIME_UTC.replace(
        month=1, day=1, hour=0, minute=0, second=0, microsecond=0)
    self.assertTrue(
        absl_example.check_civilyear(self.TEST_DATETIME, truncated.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_pass_datetime_dst()
absl_test.AbslTimeTest.test_pass_datetime_dst (self)
Definition at line 108 of file absl_test.py.
  def test_pass_datetime_dst(self):
    dst_end = datetime.datetime(2020, 11, 1, 2, 0, 0)
    secs = dst_end.timestamp()
    self.assertTrue(absl_example.check_datetime(dst_end, secs))
test_pass_datetime_dst_with_timezone()
absl_test.AbslTimeTest.test_pass_datetime_dst_with_timezone (self)
Definition at line 100 of file absl_test.py.
  def test_pass_datetime_dst_with_timezone(self):
    pacific_tz = tz.gettz('America/Los_Angeles')
    # pylint: disable=g-tzinfo-datetime
    dst_end = datetime.datetime(2020, 11, 1, 2, 0, 0, tzinfo=pacific_tz)
    # pylint: enable=g-tzinfo-datetime
    secs = dst_end.timestamp()
    self.assertTrue(absl_example.check_datetime(dst_end, secs))
test_pass_datetime_pre_unix_epoch()
absl_test.AbslTimeTest.test_pass_datetime_pre_unix_epoch (self)
Definition at line 123 of file absl_test.py.
  def test_pass_datetime_pre_unix_epoch(self):
    dt = datetime.datetime(1969, 7, 16, 10, 56, 7, microsecond=140)
    secs = dt.timestamp()
    self.assertTrue(absl_example.check_datetime(dt, secs))
test_pass_datetime_with_timezone()
absl_test.AbslTimeTest.test_pass_datetime_with_timezone (self)
Definition at line 90 of file absl_test.py.
  def test_pass_datetime_with_timezone(self):
    pacific_tz = tz.gettz('America/Los_Angeles')
    # pylint: disable=g-tzinfo-datetime
    # Warning about tzinfo applies to pytz, but we are using dateutil.tz
    dt_with_tz = datetime.datetime(
        year=2020, month=2, day=1, hour=20, tzinfo=pacific_tz)
    # pylint: enable=g-tzinfo-datetime
    secs = dt_with_tz.timestamp()
    self.assertTrue(absl_example.check_datetime(dt_with_tz, secs))
test_pass_float_duration()
absl_test.AbslTimeTest.test_pass_float_duration (self)
Definition at line 49 of file absl_test.py.
  def test_pass_float_duration(self):
    self.assertTrue(
        absl_example.check_duration(self.POSITIVE_SECS, self.POSITIVE_SECS))
References absl_test.AbslTimeTest.POSITIVE_SECS.
test_pass_integer_duration()
absl_test.AbslTimeTest.test_pass_integer_duration (self)
Definition at line 53 of file absl_test.py.
  def test_pass_integer_duration(self):
    self.assertTrue(
        absl_example.check_duration(self.SECONDS_IN_DAY, self.SECONDS_IN_DAY))
test_pass_negative_duration()
absl_test.AbslTimeTest.test_pass_negative_duration (self)
Definition at line 45 of file absl_test.py.
  def test_pass_negative_duration(self):
    duration = datetime.timedelta(seconds=self.NEGATIVE_SECS)
    self.assertTrue(absl_example.check_duration(duration, self.NEGATIVE_SECS))
References absl_test.AbslTimeTest.NEGATIVE_SECS.
test_pass_positive_duration()
absl_test.AbslTimeTest.test_pass_positive_duration (self)
Definition at line 41 of file absl_test.py.
  def test_pass_positive_duration(self):
    duration = datetime.timedelta(seconds=self.POSITIVE_SECS)
    self.assertTrue(absl_example.check_duration(duration, self.POSITIVE_SECS))
References absl_test.AbslTimeTest.POSITIVE_SECS.
test_return_civilday()
absl_test.AbslTimeTest.test_return_civilday (self)
Definition at line 167 of file absl_test.py.
  def test_return_civilday(self):
    truncated = self.TEST_DATETIME.replace(
        hour=0, minute=0, second=0, microsecond=0)
    self.assertEqual(
        truncated,
        absl_example.make_civilday(self.TEST_DATETIME_UTC.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_return_civilhour()
absl_test.AbslTimeTest.test_return_civilhour (self)
Definition at line 155 of file absl_test.py.
  def test_return_civilhour(self):
    truncated = self.TEST_DATETIME.replace(minute=0, second=0, microsecond=0)
    self.assertEqual(
        truncated,
        absl_example.make_civilhour(self.TEST_DATETIME_UTC.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_return_civilminute()
absl_test.AbslTimeTest.test_return_civilminute (self)
Definition at line 143 of file absl_test.py.
  def test_return_civilminute(self):
    truncated = self.TEST_DATETIME.replace(second=0, microsecond=0)
    self.assertEqual(
        truncated,
        absl_example.make_civilminute(self.TEST_DATETIME_UTC.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_return_civilmonth()
absl_test.AbslTimeTest.test_return_civilmonth (self)
Definition at line 180 of file absl_test.py.
  def test_return_civilmonth(self):
    truncated = self.TEST_DATETIME.replace(
        day=1, hour=0, minute=0, second=0, microsecond=0)
    self.assertEqual(
        truncated,
        absl_example.make_civilmonth(self.TEST_DATETIME_UTC.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_return_civilsecond()
absl_test.AbslTimeTest.test_return_civilsecond (self)
Definition at line 128 of file absl_test.py.
  def test_return_civilsecond(self):
    # We need to use a timezone aware datetime here, otherwise
    # datetime.timestamp converts to localtime. UTC is chosen as the convention
    # in the test cases.
    truncated = self.TEST_DATETIME.replace(microsecond=0)
    self.assertEqual(
        truncated,
        absl_example.make_civilsecond(self.TEST_DATETIME_UTC.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_return_civilyear()
absl_test.AbslTimeTest.test_return_civilyear (self)
Definition at line 194 of file absl_test.py.
  def test_return_civilyear(self):
    truncated = self.TEST_DATETIME.replace(
        month=1, day=1, hour=0, minute=0, second=0, microsecond=0)
    self.assertEqual(
        truncated,
        absl_example.make_civilyear(self.TEST_DATETIME_UTC.timestamp()))
References absl_test.AbslTimeTest.TEST_DATETIME, and absl_test.AbslTimeTest.TEST_DATETIME_UTC.
test_return_datetime()
absl_test.AbslTimeTest.test_return_datetime (self)
Definition at line 62 of file absl_test.py.
  def test_return_datetime(self):
    secs = self.TEST_DATETIME.timestamp()
    local_tz = tz.gettz()
    # pylint: disable=g-tzinfo-datetime
    # Warning about tzinfo applies to pytz, but we are using dateutil.tz
    expected_datetime = datetime.datetime(
        year=self.TEST_DATETIME.year,
        month=self.TEST_DATETIME.month,
        day=self.TEST_DATETIME.day,
        hour=self.TEST_DATETIME.hour,
        minute=self.TEST_DATETIME.minute,
        second=self.TEST_DATETIME.second,
        microsecond=self.TEST_DATETIME.microsecond,
        tzinfo=local_tz)
    # pylint: enable=g-tzinfo-datetime
    # datetime handling code will set the local timezone on C++ times for want
    # of a better alternative
    self.assertEqual(expected_datetime, absl_example.make_datetime(secs))
References absl_test.AbslTimeTest.TEST_DATETIME.
test_return_negative_duration()
absl_test.AbslTimeTest.test_return_negative_duration (self)
Definition at line 35 of file absl_test.py.
  def test_return_negative_duration(self):
    duration = absl_example.make_duration(self.NEGATIVE_SECS)
    self.assertEqual(duration.days, -3)
    self.assertEqual(duration.seconds, 2)
    self.assertEqual(duration.microseconds, 5e5)
References absl_test.AbslTimeTest.NEGATIVE_SECS.
test_return_positive_duration()
absl_test.AbslTimeTest.test_return_positive_duration (self)
Definition at line 29 of file absl_test.py.
  def test_return_positive_duration(self):
    duration = absl_example.make_duration(self.POSITIVE_SECS)
    self.assertEqual(duration.days, 3)
    self.assertEqual(duration.seconds, 2)
    self.assertEqual(duration.microseconds, 5e5)
References absl_test.AbslTimeTest.POSITIVE_SECS.
test_timezone()
absl_test.AbslTimeTest.test_timezone (self)
Definition at line 207 of file absl_test.py.
  def test_timezone(self):
    expected_timezone = 'Fixed/UTC+02:00:00'
    timezone = absl_example.roundtrip_timezone(expected_timezone)
    self.assertEqual(expected_timezone, timezone)
    timezone = absl_example.roundtrip_timezone(2 * 60 * 60)
    self.assertEqual(expected_timezone, timezone)
    with self.assertRaises(TypeError):
      absl_example.roundtrip_timezone('Not a timezone')
Member Data Documentation
NEGATIVE_SECS [1/2]
int absl_test.AbslTimeTest.NEGATIVE_SECS = -3 * SECONDS_IN_DAY + 2.5 static
Definition at line 21 of file absl_test.py.
Referenced by absl_test.AbslTimeTest.test_pass_negative_duration(), and absl_test.AbslTimeTest.test_return_negative_duration().
NEGATIVE_SECS [2/2]
absl_test.AbslTimeTest.NEGATIVE_SECS
Definition at line 47 of file absl_test.py.
Referenced by absl_test.AbslTimeTest.test_pass_negative_duration(), and absl_test.AbslTimeTest.test_return_negative_duration().
POSITIVE_SECS [1/2]
int absl_test.AbslTimeTest.POSITIVE_SECS = 3 * SECONDS_IN_DAY + 2.5 static
Definition at line 20 of file absl_test.py.
Referenced by absl_test.AbslTimeTest.test_pass_float_duration(), absl_test.AbslTimeTest.test_pass_positive_duration(), and absl_test.AbslTimeTest.test_return_positive_duration().
POSITIVE_SECS [2/2]
absl_test.AbslTimeTest.POSITIVE_SECS
Definition at line 43 of file absl_test.py.
Referenced by absl_test.AbslTimeTest.test_pass_float_duration(), absl_test.AbslTimeTest.test_pass_positive_duration(), and absl_test.AbslTimeTest.test_return_positive_duration().
SECONDS_IN_DAY [1/2]
int absl_test.AbslTimeTest.SECONDS_IN_DAY = 24 * 60 * 60 static
Definition at line 19 of file absl_test.py.
SECONDS_IN_DAY [2/2]
absl_test.AbslTimeTest.SECONDS_IN_DAY
Definition at line 55 of file absl_test.py.
TEST_DATE
absl_test.AbslTimeTest.TEST_DATE = datetime.date(2000, 1, 2) static
Definition at line 27 of file absl_test.py.
Referenced by absl_test.AbslTimeTest.test_pass_date().
TEST_DATETIME
absl_test.AbslTimeTest.TEST_DATETIME = datetime.datetime(2000, 1, 2, 3, 4, 5, int(5e5)) static
Definition at line 22 of file absl_test.py.
Referenced by absl_test.AbslTimeTest.test_pass_datetime(), absl_test.AbslTimeTest.test_pass_datetime_as_civilday(), absl_test.AbslTimeTest.test_pass_datetime_as_civilhour(), absl_test.AbslTimeTest.test_pass_datetime_as_civilminute(), absl_test.AbslTimeTest.test_pass_datetime_as_civilmonth(), absl_test.AbslTimeTest.test_pass_datetime_as_civilsecond(), absl_test.AbslTimeTest.test_pass_datetime_as_civilyear(), absl_test.AbslTimeTest.test_return_civilday(), absl_test.AbslTimeTest.test_return_civilhour(), absl_test.AbslTimeTest.test_return_civilminute(), absl_test.AbslTimeTest.test_return_civilmonth(), absl_test.AbslTimeTest.test_return_civilsecond(), absl_test.AbslTimeTest.test_return_civilyear(), and absl_test.AbslTimeTest.test_return_datetime().
TEST_DATETIME_UTC
absl_test.AbslTimeTest.TEST_DATETIME_UTC = TEST_DATETIME.replace(tzinfo=tz.tzutc()) static
Definition at line 25 of file absl_test.py.
Referenced by absl_test.AbslTimeTest.test_pass_datetime_as_civilday(), absl_test.AbslTimeTest.test_pass_datetime_as_civilhour(), absl_test.AbslTimeTest.test_pass_datetime_as_civilminute(), absl_test.AbslTimeTest.test_pass_datetime_as_civilmonth(), absl_test.AbslTimeTest.test_pass_datetime_as_civilsecond(), absl_test.AbslTimeTest.test_pass_datetime_as_civilyear(), absl_test.AbslTimeTest.test_return_civilday(), absl_test.AbslTimeTest.test_return_civilhour(), absl_test.AbslTimeTest.test_return_civilminute(), absl_test.AbslTimeTest.test_return_civilmonth(), absl_test.AbslTimeTest.test_return_civilsecond(), and absl_test.AbslTimeTest.test_return_civilyear().
The documentation for this class was generated from the following file:
open_spiel/pybind11_abseil/pybind11_abseil/tests/absl_test.py