open spiel: open_spiel::colored_trails::ColoredTrailsState Class Reference
open_spiel::colored_trails::ColoredTrailsState Class Reference
#include <colored_trails.h>
Public Member Functions
ColoredTrailsState (std::shared_ptr< const Game > game, int board_size, int num_colors)
ColoredTrailsState (const ColoredTrailsState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move_id) const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string InformationStateString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const override
void SetChipsAndTradeProposal (Player player, std::vector< int > chips, Trade trade, std::vector< double > &rng_rolls)
const Board & board ()
const std::vector< Trade > & proposals ()
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 144 of file colored_trails.h.
Constructor & Destructor Documentation
ColoredTrailsState() [1/2]
open_spiel::colored_trails::ColoredTrailsState::ColoredTrailsState (std::shared_ptr< const Game > game, int board_size, int num_colors)
Definition at line 485 of file colored_trails.cc.
    : State(game),
      cur_player_(kChancePlayerId),
      parent_game_(down_cast<const ColoredTrailsGame*>(game.get())),
      board_(board_size, num_colors, game->NumPlayers()),
      returns_(game->NumPlayers(), 0) {}
Referenced by Clone().
ColoredTrailsState() [2/2]
open_spiel::colored_trails::ColoredTrailsState::ColoredTrailsState (const ColoredTrailsState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::colored_trails::ColoredTrailsState::ActionToString (Player player, Action move_id) const override virtual
Implements open_spiel::State.
Definition at line 273 of file colored_trails.cc.
{
  if (player == kChancePlayerId) {
    return absl::StrCat("Chance outcome ", move_id);
  } else if (player < kResponderId) {
    return absl::StrCat("Proposer ", player, ": ",
                        parent_game_->LookupTrade(move_id).ToString());
  } else if (player == kResponderId) {
    if (move_id == num_distinct_actions_ - 3) {
      return "Deal: trade with proposer 0";
    } else if (move_id == num_distinct_actions_ - 2) {
      return "Deal: trade with proposer 1";
    } else if (move_id == num_distinct_actions_ - 1) {
      return "No Deal!";
    } else {
      SpielFatalError(absl::StrCat("move_id unrecognized: ", move_id));
    }
  } else {
    SpielFatalError(absl::StrCat("Player and move case unrecognized: ", player,
                                 " ", move_id));
  }
}
References open_spiel::kChancePlayerId, open_spiel::colored_trails::kResponderId, open_spiel::colored_trails::ColoredTrailsGame::LookupTrade(), open_spiel::State::num_distinct_actions_, player, open_spiel::SpielFatalError(), absl::StrCat(), and open_spiel::colored_trails::Trade::ToString().
board()
const Board & open_spiel::colored_trails::ColoredTrailsState::board () inline
Definition at line 180 of file colored_trails.h.
{ return board_; }
Referenced by open_spiel.python.games.tic_tac_toe.TicTacToeState::__str__(), open_spiel.python.games.tic_tac_toe.TicTacToeState::_apply_action(), and open_spiel.python.games.tic_tac_toe.TicTacToeState::_legal_actions().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::colored_trails::ColoredTrailsState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 596 of file colored_trails.cc.
          {
  SPIEL_CHECK_TRUE(IsChanceNode());
  std::vector<std::pair<Action, double>> outcomes;
  const int num_boards = parent_game_->AllBoards().size();
  outcomes.reserve(num_boards);
  double uniform_prob = 1.0 / num_boards;
  for (int i = 0; i < num_boards; ++i) {
    outcomes.push_back({i, uniform_prob});
  }
  return outcomes;
}
References open_spiel::colored_trails::ColoredTrailsGame::AllBoards(), i, open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::colored_trails::ColoredTrailsState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 631 of file colored_trails.cc.
{
  return std::unique_ptr<State>(new ColoredTrailsState(*this));
}
References ColoredTrailsState().
CurrentPlayer()
int open_spiel::colored_trails::ColoredTrailsState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 493 of file colored_trails.cc.
{
  return IsTerminal() ? kTerminalPlayerId : cur_player_;
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by InformationStateString(), and InformationStateTensor().
DoApplyAction()
void open_spiel::colored_trails::ColoredTrailsState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 497 of file colored_trails.cc.
{
  if (IsChanceNode()) {
    const std::vector<Board>& all_boards = parent_game_->AllBoards();
    SPIEL_CHECK_GE(action, 0);
    SPIEL_CHECK_LT(action, all_boards.size());
    board_ = all_boards[action];
    cur_player_ = 0;
  } else if (cur_player_ < kResponderId) {
    proposals_.push_back(parent_game_->LookupTrade(action));
    cur_player_++;
    // Special case when using SetChipsAndProposals, check the future_trade_.
    // If it's now the second player, and there's a future trade queued, apply
    // it.
    if (cur_player_ == 1 &&
        (!future_trade_.giving.empty() || !future_trade_.receiving.empty())) {
      proposals_.push_back(future_trade_);
      cur_player_++;
    }
  } else {
    // Base scores.
    SPIEL_CHECK_EQ(cur_player_, kResponderId);
    for (Player p = 0; p < board_.num_players; ++p) {
      returns_[p] = Score(p, board_).first;
    }
    if (action == parent_game_->ResponderTradeWithPlayerAction(0)) {
      if (!IsPassTrade(proposals_[0])) {
        board_.ApplyTrade({0, kResponderId}, proposals_[0]);
      }
    } else if (action == parent_game_->ResponderTradeWithPlayerAction(1)) {
      if (!IsPassTrade(proposals_[1])) {
        board_.ApplyTrade({1, kResponderId}, proposals_[1]);
      }
    } else if (action == parent_game_->PassAction()) {
      // No trade.
    } else {
      std::string error = absl::StrCat("Invalid action: ", action,
          parent_game_->ActionToString(kResponderId, action), "\n",
                                       ToString());
      SpielFatalErrorWithStateInfo(error, *parent_game_, *this);
    }
    // Gain is final score minus base score.
    for (Player p = 0; p < board_.num_players; ++p) {
      returns_[p] = Score(p, board_).first - returns_[p];
    }
    cur_player_ = kTerminalPlayerId;
  }
}
References action, open_spiel::Game::ActionToString(), open_spiel::colored_trails::ColoredTrailsGame::AllBoards(), open_spiel::colored_trails::Board::ApplyTrade(), open_spiel::colored_trails::Trade::giving, open_spiel::State::IsChanceNode(), open_spiel::colored_trails::kResponderId, open_spiel::kTerminalPlayerId, open_spiel::colored_trails::ColoredTrailsGame::LookupTrade(), open_spiel::colored_trails::Board::num_players, open_spiel::colored_trails::ColoredTrailsGame::PassAction(), open_spiel::colored_trails::Trade::receiving, open_spiel::colored_trails::ColoredTrailsGame::ResponderTradeWithPlayerAction(), open_spiel::colored_trails::Score(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalErrorWithStateInfo(), absl::StrCat(), and ToString().
InformationStateString()
std::string open_spiel::colored_trails::ColoredTrailsState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 306 of file colored_trails.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string str =
      absl::StrCat(board_.PrettyBoardString(), "\n");
  absl::StrAppend(&str, "Player: ", player, "\nPos: ",
                  absl::StrJoin(board_.positions, " "), "\n");
  if (player < kResponderId) {
    absl::StrAppend(&str, "My chips: ", ComboToString(board_.chips[player]),
                    "\n");
    absl::StrAppend(&str, "Responder chips: ",
                    ComboToString(board_.chips[kResponderId]), "\n");
  } else if (player == kResponderId) {
    absl::StrAppend(&str, "P0 chips: ", ComboToString(board_.chips[0]), "\n");
    absl::StrAppend(&str, "P1 chips: ", ComboToString(board_.chips[1]), "\n");
    if (CurrentPlayer() == kResponderId) {
      SPIEL_CHECK_EQ(proposals_.size(), 2);
      absl::StrAppend(&str, "Proposal 0: ", proposals_[0].ToString(), "\n");
      absl::StrAppend(&str, "Proposal 1: ", proposals_[1].ToString(), "\n");
    }
  } else {
    SpielFatalError(absl::StrCat("Bad player id: ", player));
  }
  return str;
}
References open_spiel::colored_trails::Board::chips, open_spiel::colored_trails::ComboToString(), CurrentPlayer(), open_spiel::colored_trails::kResponderId, open_spiel::State::num_players_, player, open_spiel::colored_trails::Board::positions, open_spiel::colored_trails::Board::PrettyBoardString(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), absl::StrAppend(), absl::StrCat(), absl::StrJoin(), and ToString().
InformationStateTensor()
void open_spiel::colored_trails::ColoredTrailsState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 397 of file colored_trails.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->InformationStateTensorSize());
  std::fill(values.begin(), values.end(), 0);
  if (IsChanceNode()) {
    // No observations at chance nodes.
    return;
  }
  int offset = 0;
  // Player.
  values[player] = 1;
  offset += num_players_;
  // Terminal?
  if (IsTerminal()) {
    values[offset] = 1;
  }
  offset += 1;
  // The board
  for (int i = 0; i < board_.board.size(); ++i) {
    values[offset + board_.board[i]] = 1;
    offset += board_.num_colors;
  }
  // Positions
  for (int i = 0; i < board_.positions.size(); ++i) {
    values[offset + board_.positions[i]] = 1;
    offset += board_.size * board_.size;
  }
  // Chips.
  std::array<const std::vector<int>*, 3> chips_ptrs;
  std::vector<int> zeros(board_.num_colors, 0);
  if (player < kResponderId) {
    chips_ptrs[0] = &board_.chips[player];
    chips_ptrs[1] = &zeros;
    chips_ptrs[2] = &board_.chips[kResponderId];
  } else {
    chips_ptrs[0] = &board_.chips[0];
    chips_ptrs[1] = &board_.chips[1];
    chips_ptrs[2] = &board_.chips[kResponderId];
  }
  for (int c = 0; c < 3; ++c) {
    for (int i = 0; i < board_.num_colors; ++i) {
      for (int j = 0; j <= chips_ptrs[c]->at(i); ++j) {
        values[offset + j] = 1;
      }
      offset += (kNumChipsUpperBound + 1);
    }
  }
  // Proposals
  if (player == kResponderId && CurrentPlayer() == kResponderId) {
    SPIEL_CHECK_EQ(proposals_.size(), 2);
    for (int p : {0, 1}) {
      if (IsPassTrade(proposals_[p])) {
        chips_ptrs[0] = &zeros;
        chips_ptrs[1] = &zeros;
      } else {
        chips_ptrs[0] = &(proposals_[p].giving);
        chips_ptrs[1] = &(proposals_[p].receiving);
      }
      for (int c = 0; c < 2; ++c) {
        for (int i = 0; i < board_.num_colors; ++i) {
          for (int j = 0; j <= chips_ptrs[c]->at(i); ++j) {
            values[offset + j] = 1;
          }
          offset += (kNumChipsUpperBound + 1);
        }
      }
    }
  } else {
    // Proposers have no observations of the proposals.
    // Responder doesn't observe the chips until its their turn.
    offset += (kNumChipsUpperBound + 1) * board_.num_colors * 2 *
        (num_players_ - 1);
  }
  SPIEL_CHECK_EQ(offset, values.size());
}
References open_spiel::colored_trails::Board::board, open_spiel::colored_trails::Board::chips, CurrentPlayer(), open_spiel::State::game_, i, open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::colored_trails::kResponderId, open_spiel::colored_trails::Board::num_colors, open_spiel::State::num_players_, player, open_spiel::colored_trails::Board::positions, open_spiel::colored_trails::Board::size, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, values, and zeros.
IsTerminal()
bool open_spiel::colored_trails::ColoredTrailsState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 296 of file colored_trails.cc.
{
  return cur_player_ == kTerminalPlayerId;
}
References open_spiel::kTerminalPlayerId.
Referenced by CurrentPlayer(), InformationStateTensor(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::colored_trails::ColoredTrailsState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 578 of file colored_trails.cc.
{
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else if (IsTerminal()) {
    return {};
  } else if (cur_player_ < kResponderId) {
    return LegalActionsForChips(board_.chips[cur_player_],
                                board_.chips[kResponderId]);
  } else {
    SPIEL_CHECK_EQ(cur_player_, kResponderId);
    // Last three actions correspond to "trade with 0", "trade with 1", and
    // "no trade".
    return {parent_game_->ResponderTradeWithPlayerAction(0),
            parent_game_->ResponderTradeWithPlayerAction(1),
            parent_game_->PassAction()};
  }
}
References open_spiel::colored_trails::Board::chips, open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::colored_trails::kResponderId, open_spiel::State::LegalChanceOutcomes(), open_spiel::colored_trails::ColoredTrailsGame::PassAction(), open_spiel::colored_trails::ColoredTrailsGame::ResponderTradeWithPlayerAction(), and SPIEL_CHECK_EQ.
ObservationString()
std::string open_spiel::colored_trails::ColoredTrailsState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 302 of file colored_trails.cc.
{
  return InformationStateString(player);
}
References open_spiel::State::InformationStateString(), and player.
ObservationTensor()
void open_spiel::colored_trails::ColoredTrailsState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 333 of file colored_trails.cc.
{
  InformationStateTensor(player, values);
}
References open_spiel::State::InformationStateTensor(), player, and values.
proposals()
const std::vector< Trade > & open_spiel::colored_trails::ColoredTrailsState::proposals () inline
Definition at line 181 of file colored_trails.h.
{ return proposals_; }
ResampleFromInfostate()
std::unique_ptr< State > open_spiel::colored_trails::ColoredTrailsState::ResampleFromInfostate (int player_id, std::function< double()> rng) const override virtual
Reimplemented from open_spiel::State.
Definition at line 338 of file colored_trails.cc.
{
  std::vector<std::unique_ptr<State>> candidates;
  const std::vector<Board>& all_boards = parent_game_->AllBoards();
  for (int o = 0; o < all_boards.size(); ++o) {
    if (board_.ToString() != all_boards[o].ToString()) {
      continue;
    }
    std::unique_ptr<State> candidate_state = parent_game_->NewInitialState();
    candidate_state->ApplyAction(o);
    if (player_id == 0) {
      if (candidate_state->InformationStateString(0) ==
          InformationStateString(0)) {
        candidates.push_back(std::move(candidate_state));
      }
    } else if (player_id == 1) {
      // Enumerate legal moves.
      for (Action action : candidate_state->LegalActions()) {
        std::unique_ptr<State> candidate_child = candidate_state->Child(action);
        if (candidate_child->InformationStateString(1) ==
            InformationStateString(1)) {
          candidates.push_back(std::move(candidate_child));
        } else {
          // Player 0's move is hidden. No need to keep trying actions if P1's
          // infostate doesn't match.
          break;
        }
      }
    } else {
      SPIEL_CHECK_EQ(player_id, 2);
      SPIEL_CHECK_EQ(History().size(), 3);
      Action p0_action = History()[1];
      Action p1_action = History()[2];
      // Receiver sees everything, so replay the moves.
      std::vector<Action> legal_actions = candidate_state->LegalActions();
      if (absl::c_find(legal_actions, p0_action) != legal_actions.end()) {
        candidate_state->ApplyAction(p0_action);
        legal_actions = candidate_state->LegalActions();
        if (absl::c_find(legal_actions, p1_action) != legal_actions.end()) {
          candidate_state->ApplyAction(p1_action);
          candidates.push_back(std::move(candidate_state));
        }
      }
    }
  }
  SPIEL_CHECK_GE(candidates.size(), 1);
  if (candidates.size() == 1) {
    return std::move(candidates[0]);
  } else {
    int idx = static_cast<int>(rng() * candidates.size());
    SPIEL_CHECK_LE(idx, candidates.size());
    return std::move(candidates[idx]);
  }
}
References action, open_spiel::colored_trails::ColoredTrailsGame::AllBoards(), absl::c_find(), open_spiel::State::History(), open_spiel::State::InformationStateString(), open_spiel::colored_trails::ColoredTrailsGame::NewInitialState(), o, size, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and open_spiel::colored_trails::Board::ToString().
Returns()
std::vector< double > open_spiel::colored_trails::ColoredTrailsState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 300 of file colored_trails.cc.
{ return returns_; }
SetChipsAndTradeProposal()
void open_spiel::colored_trails::ColoredTrailsState::SetChipsAndTradeProposal (Player player, std::vector< int > chips, Trade trade, std::vector< double > & rng_rolls)
Definition at line 635 of file colored_trails.cc.
{
  // First, check the chips.
  int rng_idx = 0;
  int num_chips = std::accumulate(chips.begin(), chips.end(), 0);
  while (num_chips < kNumChipsLowerBound) {
    std::vector<int> indices;
    for (int i = 0; i < chips.size(); i++) {
      if (chips[i] == 0) {
        indices.push_back(i);
      }
    }
    SPIEL_CHECK_LT(rng_idx, rng_rolls.size());
    int selected_idx =
        indices[static_cast<int>(rng_rolls[rng_idx] * indices.size())];
    chips[selected_idx]++;
    rng_idx++;
    num_chips = std::accumulate(chips.begin(), chips.end(), 0);
  }
  while (num_chips > kNumChipsUpperBound) {
    std::vector<int> indices;
    for (int i = 0; i < chips.size(); i++) {
      if (chips[i] > 0) {
        indices.push_back(i);
      }
    }
    SPIEL_CHECK_LT(rng_idx, rng_rolls.size());
    int selected_idx =
        indices[static_cast<int>(rng_rolls[rng_idx] * indices.size())];
    chips[selected_idx]--;
    rng_idx++;
    num_chips = std::accumulate(chips.begin(), chips.end(), 0);
  }
  board_.chips[player] = chips;
  trade.reduce();
  // Now check if the Trade is legal. If not, chose one of the closest legal
  // ones in edit distance
  if (!IsLegalTrade(player, trade)) {
    std::vector<Trade> closest_trades;
    int lowest_distance = kDefaultTradeDistanceUpperBound + 100;
    std::vector<Action> legal_actions =
        LegalActionsForChips(chips, board_.chips[kResponderId]);
    for (Action action : legal_actions) {
      const Trade& legal_trade = parent_game_->LookupTrade(action);
      int dist = trade.DistanceTo(legal_trade);
      if (dist == lowest_distance) {
        closest_trades.push_back(legal_trade);
      } else if (dist < lowest_distance) {
        lowest_distance = dist;
        closest_trades = {legal_trade};
      }
    }
    if (closest_trades.empty()) {
      std::cout << ToString() << std::endl;
      std::cout << "Trade: " << trade.ToString() << std::endl;
    }
    SPIEL_CHECK_GT(closest_trades.size(), 0);
    if (closest_trades.size() == 1) {
      trade = closest_trades[0];
    } else {
      trade = closest_trades[static_cast<int>(rng_rolls[rng_idx] *
                                              closest_trades.size())];
      rng_idx++;
    }
  }
  if (player == 0) {
    SPIEL_CHECK_NE(cur_player_, 0);
    proposals_[0] = trade;
  } else if (player == 1) {
    SPIEL_CHECK_NE(cur_player_, 1);
    if (cur_player_ == 0) {
      future_trade_ = trade;
    } else {
      proposals_[1] = trade;
    }
  }
}
References action, open_spiel::colored_trails::Board::chips, open_spiel::colored_trails::Trade::DistanceTo(), i, open_spiel::colored_trails::kDefaultTradeDistanceUpperBound, open_spiel::colored_trails::kResponderId, open_spiel::colored_trails::ColoredTrailsGame::LookupTrade(), player, open_spiel::colored_trails::Trade::reduce(), SPIEL_CHECK_GT, SPIEL_CHECK_LT, SPIEL_CHECK_NE, ToString(), and open_spiel::colored_trails::Trade::ToString().
ToString()
std::string open_spiel::colored_trails::ColoredTrailsState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 609 of file colored_trails.cc.
{
  if (IsChanceNode()) {
    return "Initial chance node";
  }
  std::string str;
  if (MoveNumber() > 0) {
    absl::StrAppend(&str, "Move Number: ", MoveNumber(), "\n",
                    board_.PrettyBoardString(), "\n");
    for (Player p = 0; p < num_players_; ++p) {
      absl::StrAppend(&str, "P", p, " chips: ", ComboToString(board_.chips[p]),
                      "\n");
    }
  }
  absl::StrAppend(&str, "Pos: ", absl::StrJoin(board_.positions, " "), "\n");
  for (int i = 0; i < proposals_.size(); ++i) {
    absl::StrAppend(&str, "Proposal ", i, ": ", proposals_[i].ToString(), "\n");
  }
  return str;
}
References open_spiel::colored_trails::Board::chips, open_spiel::colored_trails::ComboToString(), i, open_spiel::State::IsChanceNode(), open_spiel::State::MoveNumber(), open_spiel::State::num_players_, open_spiel::colored_trails::Board::positions, open_spiel::colored_trails::Board::PrettyBoardString(), absl::StrAppend(), absl::StrJoin(), and ToString().
Referenced by DoApplyAction(), InformationStateString(), SetChipsAndTradeProposal(), and ToString().
The documentation for this class was generated from the following files:
open_spiel/games/colored_trails/colored_trails.h
open_spiel/games/colored_trails/colored_trails.cc