open spiel: absl::CondVar Class Reference
absl::CondVar Class Reference
#include <mutex.h>
Public Member Functions
CondVar ()
~CondVar ()
void Wait (Mutex *mu)
bool WaitWithTimeout (Mutex *mu, absl::Duration timeout)
bool WaitWithDeadline (Mutex *mu, absl::Time deadline)
void Signal ()
void SignalAll ()
void EnableDebugLog (const char *name)
Detailed Description
Definition at line 832 of file mutex.h.
Constructor & Destructor Documentation
CondVar()
absl::CondVar::CondVar () inline
Definition at line 981 of file mutex.h.
: cv_(0) {}
~CondVar()
absl::CondVar::~CondVar ()
Definition at line 2504 of file mutex.cc.
                  {
  if ((cv_.load(std::memory_order_relaxed) & kCvEvent) != 0) {
    ForgetSynchEvent(&this->cv_, kCvEvent, kCvSpin);
  }
}
Member Function Documentation
EnableDebugLog()
void absl::CondVar::EnableDebugLog (const char * name)
Definition at line 2498 of file mutex.cc.
{
  SynchEvent *e = EnsureSynchEvent(&this->cv_, name, kCvEvent, kCvSpin);
  e->log = true;
  UnrefSynchEvent(e);
}
References absl::e, and name.
Signal()
void absl::CondVar::Signal ()
Definition at line 2691 of file mutex.cc.
                     {
  SchedulingGuard::ScopedDisable disable_rescheduling;
  ABSL_TSAN_MUTEX_PRE_SIGNAL(nullptr, 0);
  intptr_t v;
  int c = 0;
  for (v = cv_.load(std::memory_order_relaxed); v != 0;
       v = cv_.load(std::memory_order_relaxed)) {
    if ((v & kCvSpin) == 0 &&  // attempt to acquire spinlock
        cv_.compare_exchange_strong(v, v | kCvSpin,
                                    std::memory_order_acquire,
                                    std::memory_order_relaxed)) {
      PerThreadSynch *h = reinterpret_cast<PerThreadSynch *>(v & ~kCvLow);
      PerThreadSynch *w = nullptr;
      if (h != nullptr) {  // remove first waiter
        w = h->next;
        if (w == h) {
          h = nullptr;
        } else {
          h->next = w->next;
        }
      }
                                      // release spinlock
      cv_.store((v & kCvEvent) | reinterpret_cast<intptr_t>(h),
                std::memory_order_release);
      if (w != nullptr) {
        CondVar::Wakeup(w);                // wake waiter, if there was one
        cond_var_tracer("Signal wakeup", this);
      }
      if ((v & kCvEvent) != 0) {
        PostSynchEvent(this, SYNCH_EV_SIGNAL);
      }
      ABSL_TSAN_MUTEX_POST_SIGNAL(nullptr, 0);
      return;
    } else {
      c = synchronization_internal::MutexDelay(c, GENTLE);
    }
  }
  ABSL_TSAN_MUTEX_POST_SIGNAL(nullptr, 0);
}
References ABSL_TSAN_MUTEX_POST_SIGNAL, ABSL_TSAN_MUTEX_PRE_SIGNAL, absl::c, absl::base_internal::PerThreadSynch::next, and absl::v.
Referenced by open_spiel::ThreadedQueue< T >::Pop(), and open_spiel::ThreadedQueue< T >::Push().
SignalAll()
void absl::CondVar::SignalAll ()
Definition at line 2731 of file mutex.cc.
{
  ABSL_TSAN_MUTEX_PRE_SIGNAL(nullptr, 0);
  intptr_t v;
  int c = 0;
  for (v = cv_.load(std::memory_order_relaxed); v != 0;
       v = cv_.load(std::memory_order_relaxed)) {
    // empty the list if spinlock free
    // We do this by simply setting the list to empty using
    // compare and swap.   We then have the entire list in our hands,
    // which cannot be changing since we grabbed it while no one
    // held the lock.
    if ((v & kCvSpin) == 0 &&
        cv_.compare_exchange_strong(v, v & kCvEvent, std::memory_order_acquire,
                                    std::memory_order_relaxed)) {
      PerThreadSynch *h = reinterpret_cast<PerThreadSynch *>(v & ~kCvLow);
      if (h != nullptr) {
        PerThreadSynch *w;
        PerThreadSynch *n = h->next;
        do {                          // for every thread, wake it up
          w = n;
          n = n->next;
          CondVar::Wakeup(w);
        } while (w != h);
        cond_var_tracer("SignalAll wakeup", this);
      }
      if ((v & kCvEvent) != 0) {
        PostSynchEvent(this, SYNCH_EV_SIGNALALL);
      }
      ABSL_TSAN_MUTEX_POST_SIGNAL(nullptr, 0);
      return;
    } else {
      // try again after a delay
      c = synchronization_internal::MutexDelay(c, GENTLE);
    }
  }
  ABSL_TSAN_MUTEX_POST_SIGNAL(nullptr, 0);
}
References ABSL_TSAN_MUTEX_POST_SIGNAL, ABSL_TSAN_MUTEX_PRE_SIGNAL, absl::c, n, absl::base_internal::PerThreadSynch::next, and absl::v.
Referenced by open_spiel::ThreadedQueue< T >::BlockNewValues().
Wait()
void absl::CondVar::Wait (Mutex * mu)
Definition at line 2670 of file mutex.cc.
{
  WaitCommon(mu, KernelTimeout::Never());
}
References absl::synchronization_internal::KernelTimeout::Never().
WaitWithDeadline()
bool absl::CondVar::WaitWithDeadline (Mutex * mu, absl::Time deadline)
Definition at line 2666 of file mutex.cc.
{
  return WaitCommon(mu, KernelTimeout(deadline));
}
Referenced by open_spiel::ThreadedQueue< T >::Pop(), and open_spiel::ThreadedQueue< T >::Push().
WaitWithTimeout()
bool absl::CondVar::WaitWithTimeout (Mutex * mu, absl::Duration timeout)
Definition at line 2662 of file mutex.cc.
{
  return WaitWithDeadline(mu, DeadlineFromTimeout(timeout));
}
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/synchronization/mutex.h
open_spiel/abseil-cpp/absl/synchronization/mutex.cc