open spiel: open_spiel::universal_poker::acpc_cpp::ACPCGame Class Reference
open_spiel::universal_poker::acpc_cpp::ACPCGame Class Reference
#include <acpc_game.h>
Public Member Functions
ACPCGame (const std::string &gameDef)
ACPCGame (const ACPCGame &other)
std::string ToString () const
bool IsLimitGame () const
int NumRounds () const
int GetNbPlayers () const
uint8_t GetNbHoleCardsRequired () const
uint8_t GetNbBoardCardsRequired (uint8_t round) const
uint8_t NumSuitsDeck () const
uint8_t NumRanksDeck () const
uint8_t NumBoardCards (int round) const
uint32_t StackSize (uint8_t player) const
uint32_t TotalMoney () const
uint32_t BlindSize (uint8_t player) const
uint8_t GetTotalNbBoardCards () const
::project_acpc_server::Game * MutableGame () const
const project_acpc_server::Game & Game () const
uint32_t HandId () const
absl::Span< const int32_t > blinds () const
bool operator== (const ACPCGame &other) const
bool operator!= (const ACPCGame &other) const
Detailed Description
Definition at line 34 of file acpc_game.h.
Constructor & Destructor Documentation
ACPCGame() [1/2]
open_spiel::universal_poker::acpc_cpp::ACPCGame::ACPCGame (const std::string & gameDef) explicit
Definition at line 73 of file acpc_game.cc.
{
  readGameToStruct(gameDef, &acpc_game_);
}
ACPCGame() [2/2]
open_spiel::universal_poker::acpc_cpp::ACPCGame::ACPCGame (const ACPCGame & other) explicit
Definition at line 77 of file acpc_game.cc.
    : handId_(other.handId_), acpc_game_(other.acpc_game_) {}
Member Function Documentation
blinds()
absl::Span< const int32_t > open_spiel::universal_poker::acpc_cpp::ACPCGame::blinds () const inline
Definition at line 67 of file acpc_game.h.
{
    return absl::Span<const int32_t>(acpc_game_.blind, acpc_game_.numPlayers);
  }
BlindSize()
uint32_t open_spiel::universal_poker::acpc_cpp::ACPCGame::BlindSize (uint8_t player) const
Definition at line 166 of file acpc_game.cc.
{
  SPIEL_CHECK_LE(0, player);
  SPIEL_CHECK_LT(player, GetNbPlayers());
  return acpc_game_.blind[player];
}
References GetNbPlayers(), player, SPIEL_CHECK_LE, and SPIEL_CHECK_LT.
Referenced by open_spiel::universal_poker::UniversalPokerGame::MaxGameLength().
Game()
const project_acpc_server::Game & open_spiel::universal_poker::acpc_cpp::ACPCGame::Game () const inline
Definition at line 65 of file acpc_game.h.
{ return acpc_game_; }
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerGame::MaxCommitment(), operator==(), and open_spiel::universal_poker::UniversalPokerState::PotSize().
GetNbBoardCardsRequired()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbBoardCardsRequired (uint8_t round) const
Definition at line 140 of file acpc_game.cc.
{
  SPIEL_CHECK_LT(round, acpc_game_.numRounds);
  uint8_t nbCards = 0;
  for (int r = 0; r <= round; ++r) {
    nbCards += acpc_game_.numBoardCards[r];
  }
  return nbCards;
}
References r, and SPIEL_CHECK_LT.
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), and open_spiel::universal_poker::acpc_cpp::ACPCState::SetHoleAndBoardCards().
GetNbHoleCardsRequired()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbHoleCardsRequired () const inline
Definition at line 50 of file acpc_game.h.
{ return acpc_game_.numHoleCards; }
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerGame::MaxGameLength(), and open_spiel::universal_poker::acpc_cpp::ACPCState::SetHoleAndBoardCards().
GetNbPlayers()
int open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers () const inline
Definition at line 47 of file acpc_game.h.
{ return acpc_game_.numPlayers; }
Referenced by open_spiel::universal_poker::acpc_cpp::ACPCState::Ante(), BlindSize(), open_spiel::universal_poker::acpc_cpp::ACPCState::CurrentSpent(), open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::GetHistoriesConsistentWithInfostate(), open_spiel::universal_poker::UniversalPokerState::InformationStateString(), open_spiel::universal_poker::UniversalPokerGame::InformationStateTensorShape(), open_spiel::universal_poker::UniversalPokerGame::MaxGameLength(), open_spiel::universal_poker::UniversalPokerGame::MaxUtility(), open_spiel::universal_poker::acpc_cpp::ACPCState::Money(), open_spiel::universal_poker::UniversalPokerGame::NumPlayers(), open_spiel::universal_poker::UniversalPokerState::ObservationString(), open_spiel::universal_poker::UniversalPokerGame::ObservationTensorShape(), open_spiel::universal_poker::acpc_cpp::ACPCState::SetHoleAndBoardCards(), open_spiel::universal_poker::acpc_cpp::ACPCState::SetPotSize(), StackSize(), open_spiel::universal_poker::acpc_cpp::ACPCState::ToString(), and open_spiel::universal_poker::UniversalPokerState::ToString().
GetTotalNbBoardCards()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCGame::GetTotalNbBoardCards () const
Definition at line 150 of file acpc_game.cc.
{
  uint8_t nbCards = 0;
  for (int r = 0; r < acpc_game_.numRounds; ++r) {
    nbCards += acpc_game_.numBoardCards[r];
  }
  return nbCards;
}
References r.
Referenced by open_spiel::universal_poker::UniversalPokerGame::MaxGameLength().
HandId()
uint32_t open_spiel::universal_poker::acpc_cpp::ACPCGame::HandId () const inline
Definition at line 66 of file acpc_game.h.
{ return handId_; }
Referenced by open_spiel::universal_poker::acpc_cpp::ACPCState::ACPCState().
IsLimitGame()
bool open_spiel::universal_poker::acpc_cpp::ACPCGame::IsLimitGame () const inline
Definition at line 41 of file acpc_game.h.
{
    return acpc_game_.bettingType == project_acpc_server::limitBetting;
  }
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::GetMaxBettingActions(), and open_spiel::universal_poker::UniversalPokerGame::MaxCommitment().
MutableGame()
::project_acpc_server::Game * open_spiel::universal_poker::acpc_cpp::ACPCGame::MutableGame () const inline
Definition at line 64 of file acpc_game.h.
{ return &acpc_game_; }
Referenced by open_spiel::universal_poker::acpc_cpp::ACPCState::ACPCState(), open_spiel::universal_poker::acpc_cpp::ACPCState::CurrentPlayer(), open_spiel::universal_poker::acpc_cpp::ACPCState::DoAction(), open_spiel::universal_poker::acpc_cpp::ACPCState::IsValidAction(), open_spiel::universal_poker::acpc_cpp::ACPCState::NumFolded(), open_spiel::universal_poker::acpc_cpp::ACPCState::RaiseIsValid(), open_spiel::universal_poker::acpc_cpp::ACPCState::ToString(), and open_spiel::universal_poker::acpc_cpp::ACPCState::ValueOfState().
NumBoardCards()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCGame::NumBoardCards (int round) const inline
Definition at line 54 of file acpc_game.h.
{
    return acpc_game_.numBoardCards[round];
  }
Referenced by open_spiel::universal_poker::UniversalPokerState::UniversalPokerState().
NumRanksDeck()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRanksDeck () const inline
Definition at line 53 of file acpc_game.h.
{ return acpc_game_.numRanks; }
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::GetHistoriesConsistentWithInfostate(), open_spiel::universal_poker::UniversalPokerState::InformationStateTensor(), open_spiel::universal_poker::UniversalPokerState::LegalActions(), open_spiel::universal_poker::UniversalPokerGame::MaxChanceOutcomes(), and open_spiel::universal_poker::UniversalPokerState::ObservationTensor().
NumRounds()
int open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRounds () const inline
Definition at line 46 of file acpc_game.h.
{ return acpc_game_.numRounds; }
Referenced by open_spiel::universal_poker::acpc_cpp::ACPCState::BettingSequence(), open_spiel::universal_poker::UniversalPokerGame::MaxCommitment(), and open_spiel::universal_poker::UniversalPokerGame::MaxGameLength().
NumSuitsDeck()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCGame::NumSuitsDeck () const inline
Definition at line 52 of file acpc_game.h.
{ return acpc_game_.numSuits; }
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::GetHistoriesConsistentWithInfostate(), open_spiel::universal_poker::UniversalPokerState::InformationStateTensor(), open_spiel::universal_poker::UniversalPokerState::LegalActions(), open_spiel::universal_poker::UniversalPokerGame::MaxChanceOutcomes(), and open_spiel::universal_poker::UniversalPokerState::ObservationTensor().
operator!=()
bool open_spiel::universal_poker::acpc_cpp::ACPCGame::operator!= (const ACPCGame & other) const inline
Definition at line 73 of file acpc_game.h.
{ return !(*this == other); }
operator==()
bool open_spiel::universal_poker::acpc_cpp::ACPCGame::operator== (const ACPCGame & other) const
Definition at line 83 of file acpc_game.cc.
{
  // See project_acpc_server/game.h:42. 12 fields total.
  // int32_t stack[ MAX_PLAYERS ];
  // int32_t blind[ MAX_PLAYERS ];
  // int32_t raiseSize[ MAX_ROUNDS ];
  // enum BettingType bettingType;
  // uint8_t numPlayers;
  // uint8_t numRounds;
  // uint8_t firstPlayer[ MAX_ROUNDS ];
  // uint8_t maxRaises[ MAX_ROUNDS ];
  // uint8_t numSuits;
  // uint8_t numRanks;
  // uint8_t numHoleCards;
  // uint8_t numBoardCards[ MAX_ROUNDS ];
  const project_acpc_server::Game *first = &acpc_game_;
  const project_acpc_server::Game &second = other.Game();
  const int num_players = first->numPlayers;
  const int num_rounds = first->numRounds;
  // We check for `raiseSize` only for limit betting.
  if (first->bettingType != second.bettingType) {
    return false;
  }
  if (first->bettingType == project_acpc_server::limitBetting) {
    if (!std::equal(first->raiseSize, first->raiseSize + num_rounds,
                    second.raiseSize)) {
      return false;
    }
  }
  return (  // new line
      first->numPlayers == second.numPlayers &&
      first->numRounds == second.numRounds &&
      std::equal(first->stack, first->stack + num_players, second.stack) &&
      std::equal(first->blind, first->blind + num_players, second.blind) &&
      std::equal(first->firstPlayer, first->firstPlayer + num_rounds,
                 second.firstPlayer) &&
      std::equal(first->maxRaises, first->maxRaises + num_rounds,
                 second.maxRaises) &&
      first->numSuits == second.numSuits &&
      first->numRanks == second.numRanks &&
      first->numHoleCards == second.numHoleCards &&
      std::equal(first->numBoardCards, first->numBoardCards + num_rounds,
                 second.numBoardCards));
}
References first, and Game().
StackSize()
uint32_t open_spiel::universal_poker::acpc_cpp::ACPCGame::StackSize (uint8_t player) const
Definition at line 160 of file acpc_game.cc.
{
  SPIEL_CHECK_LE(0, player);
  SPIEL_CHECK_LT(player, GetNbPlayers());
  return acpc_game_.stack[player];
}
References GetNbPlayers(), player, SPIEL_CHECK_LE, and SPIEL_CHECK_LT.
Referenced by open_spiel::universal_poker::UniversalPokerGame::MaxCommitment(), open_spiel::universal_poker::UniversalPokerGame::MaxGameLength(), and open_spiel::universal_poker::acpc_cpp::ACPCState::Money().
ToString()
std::string open_spiel::universal_poker::acpc_cpp::ACPCGame::ToString () const
Definition at line 128 of file acpc_game.cc.
{
  char buf[kStringBuffersize];
  memset(buf, 0, kStringBuffersize);
  FILE *f = fmemopen(&buf, kStringBuffersize, "w");
  project_acpc_server::printGame(f, &acpc_game_);
  std::ostringstream result;
  rewind(f);
  result << buf;
  fclose(f);
  return result.str();
}
References buf, and open_spiel::universal_poker::acpc_cpp::kStringBuffersize.
Referenced by main().
TotalMoney()
uint32_t open_spiel::universal_poker::acpc_cpp::ACPCGame::TotalMoney () const
Definition at line 171 of file acpc_game.cc.
{
  int money_pool = 0;
  for (int pl = 0; pl < acpc_game_.numPlayers; ++pl) {
    money_pool += acpc_game_.stack[pl];
  }
  return money_pool;
}
Referenced by open_spiel::universal_poker::acpc_cpp::ACPCState::SetPotSize().
The documentation for this class was generated from the following files:
open_spiel/games/universal_poker/acpc_cpp/acpc_game.h
open_spiel/games/universal_poker/acpc_cpp/acpc_game.cc