open spiel: absl::cord_internal::CordRepRing Class Reference
absl::cord_internal::CordRepRing Class Reference
#include <cord_rep_ring.h>
Classes
class Filler
struct Position
Public Types
using pos_type = size_t
using index_type = uint32_t
using offset_type = uint32_t
Public Member Functions
CordRepRing ()=delete
CordRepRing (const CordRepRing &)=delete
CordRepRing & operator= (const CordRepRing &)=delete
bool IsValid (std::ostream &output) const
index_type head () const
index_type tail () const
index_type capacity () const
index_type entries () const
pos_type begin_pos () const
index_type entries (index_type head, index_type tail) const
pos_type const & entry_end_pos (index_type index) const
CordRep *const & entry_child (index_type index) const
offset_type const & entry_data_offset (index_type index) const
Span< char > GetAppendBuffer (size_t size)
Span< char > GetPrependBuffer (size_t size)
char GetCharacter (size_t offset) const
bool IsFlat (absl::string_view *fragment) const
bool IsFlat (size_t offset, size_t len, absl::string_view *fragment) const
void SetCapacityForTesting (size_t capacity)
index_type advance (index_type index) const
index_type advance (index_type index, index_type n) const
index_type retreat (index_type index) const
index_type retreat (index_type index, index_type n) const
pos_type const & entry_begin_pos (index_type index) const
size_t entry_start_offset (index_type index) const
size_t entry_end_offset (index_type index) const
size_t entry_length (index_type index) const
absl::string_view entry_data (index_type index) const
Position Find (size_t offset) const
Position Find (index_type head, size_t offset) const
Position FindTail (size_t offset) const
Position FindTail (index_type head, size_t offset) const
template<typename F >
void ForEach (index_type head, index_type tail, F &&f) const
template<typename F >
void ForEach (F &&f) const
Public Member Functions inherited from absl::cord_internal::CordRep
CordRep ()=default
constexpr CordRep (RefcountAndFlags::Immortal immortal, size_t l)
constexpr bool IsRing () const
constexpr bool IsSubstring () const
constexpr bool IsCrc () const
constexpr bool IsExternal () const
constexpr bool IsFlat () const
constexpr bool IsBtree () const
CordRepRing * ring ()
const CordRepRing * ring () const
CordRepSubstring * substring ()
const CordRepSubstring * substring () const
CordRepCrc * crc ()
const CordRepCrc * crc () const
CordRepExternal * external ()
const CordRepExternal * external () const
CordRepFlat * flat ()
const CordRepFlat * flat () const
CordRepBtree * btree ()
const CordRepBtree * btree () const
Static Public Member Functions
static constexpr size_t AllocSize (size_t capacity)
static constexpr size_t Distance (pos_type pos, pos_type end_pos)
static CordRepRing * Create (CordRep *child, size_t extra=0)
static CordRepRing * Append (CordRepRing *rep, CordRep *child)
static CordRepRing * Append (CordRepRing *rep, string_view data, size_t extra=0)
static CordRepRing * Prepend (CordRepRing *rep, CordRep *child)
static CordRepRing * Prepend (CordRepRing *rep, string_view data, size_t extra=0)
static CordRepRing * SubRing (CordRepRing *r, size_t offset, size_t len, size_t extra=0)
static CordRepRing * RemoveSuffix (CordRepRing *r, size_t len, size_t extra=0)
static CordRepRing * RemovePrefix (CordRepRing *r, size_t len, size_t extra=0)
static const char * GetLeafData (const CordRep *rep)
static const char * GetRepData (const CordRep *rep)
Static Public Member Functions inherited from absl::cord_internal::CordRep
static void Destroy (CordRep *rep)
static CordRep * Ref (CordRep *rep)
static void Unref (CordRep *rep)
Static Public Attributes
static constexpr size_t kMaxCapacity = (std::numeric_limits<uint32_t>::max)()
Friends
struct CordRep
std::ostream & operator<< (std::ostream &s, const CordRepRing &rep)
Additional Inherited Members
Public Attributes inherited from absl::cord_internal::CordRep
size_t length
RefcountAndFlags refcount
uint8_t tag
uint8_t storage [3]
Detailed Description
Definition at line 70 of file cord_rep_ring.h.
Member Typedef Documentation
index_type
using absl::cord_internal::CordRepRing::index_type = uint32_t
Definition at line 81 of file cord_rep_ring.h.
offset_type
using absl::cord_internal::CordRepRing::offset_type = uint32_t
Definition at line 84 of file cord_rep_ring.h.
pos_type
using absl::cord_internal::CordRepRing::pos_type = size_t
Definition at line 77 of file cord_rep_ring.h.
Constructor & Destructor Documentation
CordRepRing() [1/2]
absl::cord_internal::CordRepRing::CordRepRing () delete
Referenced by AllocSize().
CordRepRing() [2/2]
absl::cord_internal::CordRepRing::CordRepRing (const CordRepRing &) delete
Member Function Documentation
advance() [1/2]
CordRepRing::index_type absl::cord_internal::CordRepRing::advance (index_type index) const inline
Definition at line 507 of file cord_rep_ring.h.
{
  assert(index < capacity_);
  return ++index == capacity_ ? 0 : index;
}
Referenced by absl::cord_internal::CordRepRingReader::Next().
advance() [2/2]
CordRepRing::index_type absl::cord_internal::CordRepRing::advance (index_type index, index_type n) const inline
Definition at line 512 of file cord_rep_ring.h.
{
  assert(index < capacity_ && n <= capacity_);
  return (index += n) >= capacity_ ? index - capacity_ : index;
}
References absl::n.
AllocSize()
size_t absl::cord_internal::CordRepRing::AllocSize (size_t capacity) static constexpr
Definition at line 488 of file cord_rep_ring.h.
{
  return sizeof(CordRepRing) - sizeof(data_) +
         Layout(capacity, capacity, capacity).AllocSize();
}
References capacity(), and CordRepRing().
Append() [1/2]
CordRepRing * absl::cord_internal::CordRepRing::Append (CordRepRing * rep, CordRep * child) static
Definition at line 460 of file cord_rep_ring.cc.
{
  size_t length = child->length;
  if (IsFlatOrExternal(child)) {
    return AppendLeaf(rep, child, 0, length);
  }
  if (child->IsRing()) {
    return AddRing<AddMode::kAppend>(rep, child->ring(), 0, length);
  }
  return AppendSlow(rep, child);
}
References rep.
Append() [2/2]
CordRepRing * absl::cord_internal::CordRepRing::Append (CordRepRing * rep, absl::string_view data, size_t extra = 0) static
Definition at line 507 of file cord_rep_ring.cc.
{
  if (rep->refcount.IsOne()) {
    Span<char> avail = rep->GetAppendBuffer(data.length());
    if (!avail.empty()) {
      memcpy(avail.data(), data.data(), avail.length());
      data.remove_prefix(avail.length());
    }
  }
  if (data.empty()) return Validate(rep);
  const size_t flats = (data.length() - 1) / kMaxFlatLength + 1;
  rep = Mutable(rep, flats);
  Filler filler(rep, rep->tail_);
  pos_type pos = rep->begin_pos_ + rep->length;
  while (data.length() >= kMaxFlatLength) {
    auto* flat = CreateFlat(data.data(), kMaxFlatLength);
    filler.Add(flat, 0, pos += kMaxFlatLength);
    data.remove_prefix(kMaxFlatLength);
  }
  if (data.length()) {
    auto* flat = CreateFlat(data.data(), data.length(), extra);
    filler.Add(flat, 0, pos += data.length());
  }
  rep->length = pos - rep->begin_pos_;
  rep->tail_ = filler.pos();
  return Validate(rep);
}
References absl::cord_internal::CordRepRing::Filler::Add(), absl::Span< T >::data(), absl::Span< T >::empty(), absl::Span< T >::length(), pos::length, absl::cord_internal::CordRepRing::Filler::pos(), and rep.
begin_pos()
pos_type absl::cord_internal::CordRepRing::begin_pos () const inline
Definition at line 126 of file cord_rep_ring.h.
{ return begin_pos_; }
capacity()
index_type absl::cord_internal::CordRepRing::capacity () const inline
Definition at line 120 of file cord_rep_ring.h.
{ return capacity_; }
Referenced by AllocSize(), entry_child(), and entry_data_offset().
Create()
CordRepRing * absl::cord_internal::CordRepRing::Create (CordRep * child, size_t extra = 0) static
Definition at line 360 of file cord_rep_ring.cc.
{
  size_t length = child->length;
  if (IsFlatOrExternal(child)) {
    return CreateFromLeaf(child, 0, length, extra);
  }
  if (child->IsRing()) {
    return Mutable(child->ring(), extra);
  }
  return CreateSlow(child, extra);
}
Distance()
size_t absl::cord_internal::CordRepRing::Distance (pos_type pos, pos_type end_pos) inline static constexpr
Definition at line 493 of file cord_rep_ring.h.
{
  return (end_pos - pos);
}
Referenced by entry_end_offset(), entry_length(), and entry_start_offset().
entries() [1/2]
index_type absl::cord_internal::CordRepRing::entries () const inline
Definition at line 123 of file cord_rep_ring.h.
{ return entries(head_, tail_); }
References entries().
Referenced by entries(), and IsFlat().
entries() [2/2]
index_type absl::cord_internal::CordRepRing::entries (index_type head, index_type tail) const inline
Definition at line 130 of file cord_rep_ring.h.
{
    assert(head < capacity_ && tail < capacity_);
    return tail - head + ((tail > head) ? 0 : capacity_);
  }
References head(), and tail().
entry_begin_pos()
pos_type const & absl::cord_internal::CordRepRing::entry_begin_pos (index_type index) const inline
Definition at line 271 of file cord_rep_ring.h.
{
    return (index == head_) ? begin_pos_ : entry_end_pos(retreat(index));
  }
References entry_end_pos(), and retreat().
Referenced by entry_length(), and entry_start_offset().
entry_child()
CordRep *const & absl::cord_internal::CordRepRing::entry_child (index_type index) const inline
Definition at line 142 of file cord_rep_ring.h.
{
    assert(IsValidIndex(index));
    return Layout::Partial(capacity()).Pointer<1>(data_)[index];
  }
References capacity(), and absl::container_internal::Layout< Ts >::Partial().
Referenced by entry_data(), and absl::cord_internal::CordRepRingReader::node().
entry_data()
absl::string_view absl::cord_internal::CordRepRing::entry_data (index_type index) const inline
Definition at line 529 of file cord_rep_ring.h.
{
  size_t data_offset = entry_data_offset(index);
  return {GetRepData(entry_child(index)) + data_offset, entry_length(index)};
}
References entry_child(), entry_data_offset(), entry_length(), and GetRepData().
Referenced by IsFlat(), IsFlat(), absl::cord_internal::CordRepRingReader::Next(), absl::cord_internal::CordRepRingReader::Reset(), and absl::cord_internal::CordRepRingReader::Seek().
entry_data_offset()
offset_type const & absl::cord_internal::CordRepRing::entry_data_offset (index_type index) const inline
Definition at line 148 of file cord_rep_ring.h.
{
    assert(IsValidIndex(index));
    return Layout::Partial(capacity(), capacity()).Pointer<2>(data_)[index];
  }
References capacity(), and absl::container_internal::Layout< Ts >::Partial().
Referenced by entry_data().
entry_end_offset()
size_t absl::cord_internal::CordRepRing::entry_end_offset (index_type index) const inline
Definition at line 281 of file cord_rep_ring.h.
{
    return Distance(begin_pos_, entry_end_pos(index));
  }
References Distance(), and entry_end_pos().
Referenced by absl::cord_internal::CordRepRingReader::consumed(), and absl::cord_internal::CordRepRingReader::Seek().
entry_end_pos()
pos_type const & absl::cord_internal::CordRepRing::entry_end_pos (index_type index) const inline
Definition at line 136 of file cord_rep_ring.h.
{
    assert(IsValidIndex(index));
    return Layout::Partial().Pointer<0>(data_)[index];
  }
References absl::container_internal::Layout< Ts >::Partial().
Referenced by entry_begin_pos(), entry_end_offset(), and entry_length().
entry_length()
size_t absl::cord_internal::CordRepRing::entry_length (index_type index) const inline
Definition at line 286 of file cord_rep_ring.h.
{
    return Distance(entry_begin_pos(index), entry_end_pos(index));
  }
References Distance(), entry_begin_pos(), and entry_end_pos().
Referenced by entry_data().
entry_start_offset()
size_t absl::cord_internal::CordRepRing::entry_start_offset (index_type index) const inline
Definition at line 276 of file cord_rep_ring.h.
{
    return Distance(begin_pos_, entry_begin_pos(index));
  }
References Distance(), and entry_begin_pos().
Referenced by Find(), and FindTail().
Find() [1/2]
CordRepRing::Position absl::cord_internal::CordRepRing::Find (index_type head, size_t offset) const inline
Definition at line 552 of file cord_rep_ring.h.
{
  assert(offset < length);
  assert(IsValidIndex(head) && offset >= entry_start_offset(head));
  return (offset == 0) ? Position{head_, 0} : FindSlow(head, offset);
}
References entry_start_offset(), head(), and absl::cord_internal::CordRep::length.
Find() [2/2]
CordRepRing::Position absl::cord_internal::CordRepRing::Find (size_t offset) const inline
Definition at line 547 of file cord_rep_ring.h.
{
  assert(offset < length);
  return (offset == 0) ? Position{head_, 0} : FindSlow(head_, offset);
}
References absl::cord_internal::CordRep::length.
Referenced by IsFlat(), and absl::cord_internal::CordRepRingReader::Seek().
FindTail() [1/2]
CordRepRing::Position absl::cord_internal::CordRepRing::FindTail (index_type head, size_t offset) const inline
Definition at line 564 of file cord_rep_ring.h.
{
  assert(offset > 0 && offset <= length);
  assert(IsValidIndex(head) && offset >= entry_start_offset(head) + 1);
  return (offset == length) ? Position{tail_, 0} : FindTailSlow(head, offset);
}
References entry_start_offset(), head(), and absl::cord_internal::CordRep::length.
FindTail() [2/2]
CordRepRing::Position absl::cord_internal::CordRepRing::FindTail (size_t offset) const inline
Definition at line 559 of file cord_rep_ring.h.
{
  assert(offset > 0 && offset <= length);
  return (offset == length) ? Position{tail_, 0} : FindTailSlow(head_, offset);
}
References absl::cord_internal::CordRep::length.
ForEach() [1/2]
template<typename F > void absl::cord_internal::CordRepRing::ForEach (F && f) const inline
Definition at line 343 of file cord_rep_ring.h.
{
    ForEach(head_, tail_, std::forward<F>(f));
  }
References absl::f, and ForEach().
ForEach() [2/2]
template<typename F > void absl::cord_internal::CordRepRing::ForEach (index_type head, index_type tail, F && f) const inline
Definition at line 333 of file cord_rep_ring.h.
{
    index_type n1 = (tail > head) ? tail : capacity_;
    for (index_type i = head; i < n1; ++i) f(i);
    if (tail <= head) {
      for (index_type i = 0; i < tail; ++i) f(i);
    }
  }
References absl::f, head(), absl::i, and tail().
Referenced by ForEach().
GetAppendBuffer()
Span< char > absl::cord_internal::CordRepRing::GetAppendBuffer (size_t size)
Definition at line 296 of file cord_rep_ring.cc.
{
  assert(refcount.IsOne());
  index_type back = retreat(tail_);
  CordRep* child = entry_child(back);
  if (child->tag >= FLAT && child->refcount.IsOne()) {
    size_t capacity = child->flat()->Capacity();
    pos_type end_pos = entry_end_pos(back);
    size_t data_offset = entry_data_offset(back);
    size_t entry_length = Distance(entry_begin_pos(back), end_pos);
    size_t used = data_offset + entry_length;
    if (size_t n = (std::min)(capacity - used, size)) {
      child->length = data_offset + entry_length + n;
      entry_end_pos()[back] = end_pos + n;
      this->length += n;
      return {child->flat()->Data() + used, n};
    }
  }
  return {nullptr, 0};
}
References absl::cord_internal::FLAT, absl::n, refcount, and size.
GetCharacter()
char absl::cord_internal::CordRepRing::GetCharacter (size_t offset) const
Definition at line 660 of file cord_rep_ring.cc.
{
  assert(offset < length);
  Position pos = Find(offset);
  size_t data_offset = entry_data_offset(pos.index) + pos.offset;
  return GetRepData(entry_child(pos.index))[data_offset];
}
GetLeafData()
const char * absl::cord_internal::CordRepRing::GetLeafData (const CordRep * rep) inline static
Definition at line 497 of file cord_rep_ring.h.
{
  return rep->tag != EXTERNAL ? rep->flat()->Data() : rep->external()->base;
}
References absl::cord_internal::EXTERNAL, and rep.
Referenced by GetRepData().
GetPrependBuffer()
Span< char > absl::cord_internal::CordRepRing::GetPrependBuffer (size_t size)
Definition at line 316 of file cord_rep_ring.cc.
{
  assert(refcount.IsOne());
  CordRep* child = entry_child(head_);
  size_t data_offset = entry_data_offset(head_);
  if (data_offset && child->refcount.IsOne() && child->tag >= FLAT) {
    size_t n = (std::min)(data_offset, size);
    this->length += n;
    begin_pos_ -= n;
    data_offset -= n;
    entry_data_offset()[head_] = static_cast<offset_type>(data_offset);
    return {child->flat()->Data() + data_offset, n};
  }
  return {nullptr, 0};
}
References absl::cord_internal::FLAT, absl::n, refcount, and size.
GetRepData()
const char * absl::cord_internal::CordRepRing::GetRepData (const CordRep * rep) inline static
Definition at line 501 of file cord_rep_ring.h.
{
  if (rep->tag >= FLAT) return rep->flat()->Data();
  if (rep->tag == EXTERNAL) return rep->external()->base;
  return GetLeafData(rep->substring()->child) + rep->substring()->start;
}
References absl::cord_internal::EXTERNAL, absl::cord_internal::FLAT, GetLeafData(), and rep.
Referenced by entry_data().
head()
index_type absl::cord_internal::CordRepRing::head () const inline
Definition at line 118 of file cord_rep_ring.h.
{ return head_; }
Referenced by entries(), Find(), FindTail(), ForEach(), IsFlat(), absl::cord_internal::CordRepRingReader::Reset(), and absl::cord_internal::CordRepRingReader::Seek().
IsFlat() [1/2]
bool absl::cord_internal::CordRepRing::IsFlat (absl::string_view * fragment) const inline
Definition at line 582 of file cord_rep_ring.h.
{
  if (entries() == 1) {
    if (fragment) *fragment = entry_data(head());
    return true;
  }
  return false;
}
References entries(), entry_data(), and head().
IsFlat() [2/2]
bool absl::cord_internal::CordRepRing::IsFlat (size_t offset, size_t len, absl::string_view * fragment) const inline
Definition at line 590 of file cord_rep_ring.h.
{
  const Position pos = Find(offset);
  const absl::string_view data = entry_data(pos.index);
  if (data.length() >= len && data.length() - len >= pos.offset) {
    if (fragment) *fragment = data.substr(pos.offset, len);
    return true;
  }
  return false;
}
References entry_data(), Find(), len, and absl::string_view::substr().
IsValid()
bool absl::cord_internal::CordRepRing::IsValid (std::ostream & output) const
Definition at line 136 of file cord_rep_ring.cc.
{
  if (capacity_ == 0) {
    output << "capacity == 0";
    return false;
  }
  if (head_ >= capacity_ || tail_ >= capacity_) {
    output << "head " << head_ << " and/or tail " << tail_ << "exceed capacity "
           << capacity_;
    return false;
  }
  const index_type back = retreat(tail_);
  size_t pos_length = Distance(begin_pos_, entry_end_pos(back));
  if (pos_length != length) {
    output << "length " << length << " does not match positional length "
           << pos_length << " from begin_pos " << begin_pos_ << " and entry["
           << back << "].end_pos " << entry_end_pos(back);
    return false;
  }
  index_type head = head_;
  pos_type begin_pos = begin_pos_;
  do {
    pos_type end_pos = entry_end_pos(head);
    size_t entry_length = Distance(begin_pos, end_pos);
    if (entry_length == 0) {
      output << "entry[" << head << "] has an invalid length " << entry_length
             << " from begin_pos " << begin_pos << " and end_pos " << end_pos;
      return false;
    }
    CordRep* child = entry_child(head);
    if (child == nullptr) {
      output << "entry[" << head << "].child == nullptr";
      return false;
    }
    if (child->tag < FLAT && child->tag != EXTERNAL) {
      output << "entry[" << head << "].child has an invalid tag "
             << static_cast<int>(child->tag);
      return false;
    }
    size_t offset = entry_data_offset(head);
    if (offset >= child->length || entry_length > child->length - offset) {
      output << "entry[" << head << "] has offset " << offset
             << " and entry length " << entry_length
             << " which are outside of the child's length of " << child->length;
      return false;
    }
    begin_pos = end_pos;
    head = advance(head);
  } while (head != tail_);
  return true;
}
References absl::cord_internal::EXTERNAL, and absl::cord_internal::FLAT.
operator=()
CordRepRing & absl::cord_internal::CordRepRing::operator= (const CordRepRing &) delete
Prepend() [1/2]
CordRepRing * absl::cord_internal::CordRepRing::Prepend (CordRepRing * rep, CordRep * child) static
Definition at line 496 of file cord_rep_ring.cc.
{
  size_t length = child->length;
  if (IsFlatOrExternal(child)) {
    return PrependLeaf(rep, child, 0, length);
  }
  if (child->IsRing()) {
    return AddRing<AddMode::kPrepend>(rep, child->ring(), 0, length);
  }
  return PrependSlow(rep, child);
}
References rep.
Prepend() [2/2]
CordRepRing * absl::cord_internal::CordRepRing::Prepend (CordRepRing * rep, absl::string_view data, size_t extra = 0) static
Definition at line 541 of file cord_rep_ring.cc.
{
  if (rep->refcount.IsOne()) {
    Span<char> avail = rep->GetPrependBuffer(data.length());
    if (!avail.empty()) {
      const char* tail = data.data() + data.length() - avail.length();
      memcpy(avail.data(), tail, avail.length());
      data.remove_suffix(avail.length());
    }
  }
  if (data.empty()) return rep;
  const size_t flats = (data.length() - 1) / kMaxFlatLength + 1;
  rep = Mutable(rep, flats);
  pos_type pos = rep->begin_pos_;
  Filler filler(rep, rep->retreat(rep->head_, static_cast<index_type>(flats)));
  size_t first_size = data.size() - (flats - 1) * kMaxFlatLength;
  CordRepFlat* flat = CordRepFlat::New(first_size + extra);
  flat->length = first_size + extra;
  memcpy(flat->Data() + extra, data.data(), first_size);
  data.remove_prefix(first_size);
  filler.Add(flat, extra, pos);
  pos -= first_size;
  while (!data.empty()) {
    assert(data.size() >= kMaxFlatLength);
    flat = CreateFlat(data.data(), kMaxFlatLength);
    filler.Add(flat, 0, pos);
    pos -= kMaxFlatLength;
    data.remove_prefix(kMaxFlatLength);
  }
  rep->head_ = filler.head();
  rep->length += rep->begin_pos_ - pos;
  rep->begin_pos_ = pos;
  return Validate(rep);
}
References absl::cord_internal::CordRepRing::Filler::Add(), absl::cord_internal::CordRepFlat::Data(), absl::Span< T >::data(), absl::Span< T >::empty(), absl::cord_internal::CordRepRing::Filler::head(), absl::cord_internal::CordRep::length, absl::Span< T >::length(), and rep.
RemovePrefix()
CordRepRing * absl::cord_internal::CordRepRing::RemovePrefix (CordRepRing * r, size_t len, size_t extra = 0) static
Definition at line 711 of file cord_rep_ring.cc.
{
  assert(len <= rep->length);
  if (len == rep->length) {
    CordRep::Unref(rep);
    return nullptr;
  }
  Position head = rep->Find(len);
  if (rep->refcount.IsOne()) {
    if (head.index != rep->head_) UnrefEntries(rep, rep->head_, head.index);
    rep->head_ = head.index;
  } else {
    rep = Copy(rep, head.index, rep->tail_, extra);
    head.index = rep->head_;
  }
  // Adjust begin_pos and length
  rep->length -= len;
  rep->begin_pos_ += len;
  // Adjust head block
  if (head.offset) {
    rep->AddDataOffset(head.index, head.offset);
  }
  return Validate(rep);
}
References absl::cord_internal::CordRepRing::Position::index, len, absl::cord_internal::CordRepRing::Position::offset, and rep.
RemoveSuffix()
CordRepRing * absl::cord_internal::CordRepRing::RemoveSuffix (CordRepRing * r, size_t len, size_t extra = 0) static
Definition at line 740 of file cord_rep_ring.cc.
{
  assert(len <= rep->length);
  if (len == rep->length) {
    CordRep::Unref(rep);
    return nullptr;
  }
  Position tail = rep->FindTail(rep->length - len);
  if (rep->refcount.IsOne()) {
    // We adopt a privately owned rep, scrub.
    if (tail.index != rep->tail_) UnrefEntries(rep, tail.index, rep->tail_);
    rep->tail_ = tail.index;
  } else {
    // Copy subset to new rep
    rep = Copy(rep, rep->head_, tail.index, extra);
    tail.index = rep->tail_;
  }
  // Adjust length
  rep->length -= len;
  // Adjust tail block
  if (tail.offset) {
    rep->SubLength(rep->retreat(tail.index), tail.offset);
  }
  return Validate(rep);
}
References absl::cord_internal::CordRepRing::Position::index, len, absl::cord_internal::CordRepRing::Position::offset, and rep.
retreat() [1/2]
CordRepRing::index_type absl::cord_internal::CordRepRing::retreat (index_type index) const inline
Definition at line 518 of file cord_rep_ring.h.
{
  assert(index < capacity_);
  return (index > 0 ? index : capacity_) - 1;
}
Referenced by entry_begin_pos().
retreat() [2/2]
CordRepRing::index_type absl::cord_internal::CordRepRing::retreat (index_type index, index_type n) const inline
Definition at line 523 of file cord_rep_ring.h.
{
  assert(index < capacity_ && n <= capacity_);
  return index >= n ? index - n : capacity_ - n + index;
}
References absl::n.
SetCapacityForTesting()
void absl::cord_internal::CordRepRing::SetCapacityForTesting (size_t capacity)
Definition at line 220 of file cord_rep_ring.cc.
{
  // Adjust for the changed layout
  assert(capacity <= capacity_);
  assert(head() == 0 || head() < tail());
  memmove(Layout::Partial(capacity).Pointer<1>(data_) + head(),
          Layout::Partial(capacity_).Pointer<1>(data_) + head(),
          entries() * sizeof(Layout::ElementType<1>));
  memmove(Layout::Partial(capacity, capacity).Pointer<2>(data_) + head(),
          Layout::Partial(capacity_, capacity_).Pointer<2>(data_) + head(),
          entries() * sizeof(Layout::ElementType<2>));
  capacity_ = static_cast<index_type>(capacity);
}
SubRing()
CordRepRing * absl::cord_internal::CordRepRing::SubRing (CordRepRing * r, size_t offset, size_t len, size_t extra = 0) static
Definition at line 668 of file cord_rep_ring.cc.
{
  assert(offset <= rep->length);
  assert(offset <= rep->length - len);
  if (len == 0) {
    CordRep::Unref(rep);
    return nullptr;
  }
  // Find position of first byte
  Position head = rep->Find(offset);
  Position tail = rep->FindTail(head.index, offset + len);
  const size_t new_entries = rep->entries(head.index, tail.index);
  if (rep->refcount.IsOne() && extra <= (rep->capacity() - new_entries)) {
    // We adopt a privately owned rep and no extra entries needed.
    if (head.index != rep->head_) UnrefEntries(rep, rep->head_, head.index);
    if (tail.index != rep->tail_) UnrefEntries(rep, tail.index, rep->tail_);
    rep->head_ = head.index;
    rep->tail_ = tail.index;
  } else {
    // Copy subset to new rep
    rep = Copy(rep, head.index, tail.index, extra);
    head.index = rep->head_;
    tail.index = rep->tail_;
  }
  // Adjust begin_pos and length
  rep->length = len;
  rep->begin_pos_ += offset;
  // Adjust head and tail blocks
  if (head.offset) {
    rep->AddDataOffset(head.index, head.offset);
  }
  if (tail.offset) {
    rep->SubLength(rep->retreat(tail.index), tail.offset);
  }
  return Validate(rep);
}
References absl::cord_internal::CordRepRing::Position::index, len, absl::cord_internal::CordRepRing::Position::offset, and rep.
tail()
index_type absl::cord_internal::CordRepRing::tail () const inline
Definition at line 119 of file cord_rep_ring.h.
{ return tail_; }
Referenced by entries(), and ForEach().
Friends And Related Symbol Documentation
CordRep
friend struct CordRep friend
Definition at line 485 of file cord_rep_ring.h.
operator<<
std::ostream & operator<< (std::ostream & s, const CordRepRing & rep) friend
Definition at line 81 of file cord_rep_ring.cc.
{
  // Note: 'pos' values are defined as size_t (for overflow reasons), but that
  // prints really awkward for small prepended values such as -5. ssize_t is not
  // portable (POSIX), so we use ptrdiff_t instead to cast to signed values.
  s << "  CordRepRing(" << &rep << ", length = " << rep.length
    << ", head = " << rep.head_ << ", tail = " << rep.tail_
    << ", cap = " << rep.capacity_ << ", rc = " << rep.refcount.Get()
    << ", begin_pos_ = " << static_cast<ptrdiff_t>(rep.begin_pos_) << ") {\n";
  CordRepRing::index_type head = rep.head();
  do {
    CordRep* child = rep.entry_child(head);
    s << " entry[" << head << "] length = " << rep.entry_length(head)
      << ", child " << child << ", clen = " << child->length
      << ", tag = " << static_cast<int>(child->tag)
      << ", rc = " << child->refcount.Get()
      << ", offset = " << rep.entry_data_offset(head)
      << ", end_pos = " << static_cast<ptrdiff_t>(rep.entry_end_pos(head))
      << "\n";
    head = rep.advance(head);
  } while (head != rep.tail());
  return s << "}\n";
}
Member Data Documentation
kMaxCapacity
size_t absl::cord_internal::CordRepRing::kMaxCapacity = (std::numeric_limits<uint32_t>::max)() static constexpr
Definition at line 95 of file cord_rep_ring.h.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_ring.h
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_ring.cc