open spiel: absl::inlined_vector_internal::ConstructionTransaction< A > Class Template Reference
absl::inlined_vector_internal::ConstructionTransaction< A > Class Template Reference
#include <inlined_vector.h>
Public Member Functions
ConstructionTransaction (A &allocator)
~ConstructionTransaction ()
ConstructionTransaction (const ConstructionTransaction &)=delete
void operator= (const ConstructionTransaction &)=delete
A & GetAllocator ()
Pointer< A > & GetData ()
SizeType< A > & GetSize ()
bool DidConstruct ()
template<typename ValueAdapter >
void Construct (Pointer< A > data, ValueAdapter &values, SizeType< A > size)
void Commit () &&
Detailed Description
template<typename A>
class absl::inlined_vector_internal::ConstructionTransaction< A >
Definition at line 267 of file inlined_vector.h.
Constructor & Destructor Documentation
ConstructionTransaction() [1/2]
template<typename A > absl::inlined_vector_internal::ConstructionTransaction< A >::ConstructionTransaction (A & allocator) inline explicit
Definition at line 269 of file inlined_vector.h.
      : allocator_data_(allocator, nullptr), size_(0) {}
~ConstructionTransaction()
template<typename A > absl::inlined_vector_internal::ConstructionTransaction< A >::~ConstructionTransaction () inline
Definition at line 272 of file inlined_vector.h.
{
    if (DidConstruct()) {
      DestroyAdapter<A>::DestroyElements(GetAllocator(), GetData(), GetSize());
    }
  }
References absl::inlined_vector_internal::ConstructionTransaction< A >::DidConstruct(), absl::inlined_vector_internal::ConstructionTransaction< A >::GetAllocator(), absl::inlined_vector_internal::ConstructionTransaction< A >::GetData(), and absl::inlined_vector_internal::ConstructionTransaction< A >::GetSize().
ConstructionTransaction() [2/2]
template<typename A > absl::inlined_vector_internal::ConstructionTransaction< A >::ConstructionTransaction (const ConstructionTransaction< A > &) delete
Member Function Documentation
Commit()
template<typename A > void absl::inlined_vector_internal::ConstructionTransaction< A >::Commit () && inline
Definition at line 292 of file inlined_vector.h.
                   {
    GetData() = nullptr;
    GetSize() = 0;
  }
References absl::inlined_vector_internal::ConstructionTransaction< A >::GetData(), and absl::inlined_vector_internal::ConstructionTransaction< A >::GetSize().
Construct()
template<typename A > template<typename ValueAdapter > void absl::inlined_vector_internal::ConstructionTransaction< A >::Construct (Pointer< A > data, ValueAdapter & values, SizeType< A > size) inline
Definition at line 287 of file inlined_vector.h.
{
    ConstructElements<A>(GetAllocator(), data, values, size);
    GetData() = data;
    GetSize() = size;
  }
References absl::inlined_vector_internal::ConstructElements(), data, absl::inlined_vector_internal::ConstructionTransaction< A >::GetAllocator(), absl::inlined_vector_internal::ConstructionTransaction< A >::GetData(), absl::inlined_vector_internal::ConstructionTransaction< A >::GetSize(), size, and values.
Referenced by absl::inlined_vector_internal::Storage< T, N, A >::Insert(), and absl::inlined_vector_internal::Storage< T, N, A >::Resize().
DidConstruct()
template<typename A > bool absl::inlined_vector_internal::ConstructionTransaction< A >::DidConstruct () inline
Definition at line 285 of file inlined_vector.h.
{ return GetData() != nullptr; }
References absl::inlined_vector_internal::ConstructionTransaction< A >::GetData().
Referenced by absl::inlined_vector_internal::ConstructionTransaction< A >::~ConstructionTransaction().
GetAllocator()
template<typename A > A & absl::inlined_vector_internal::ConstructionTransaction< A >::GetAllocator () inline
Definition at line 281 of file inlined_vector.h.
{ return allocator_data_.template get<0>(); }
References absl::get().
Referenced by absl::inlined_vector_internal::ConstructionTransaction< A >::Construct(), and absl::inlined_vector_internal::ConstructionTransaction< A >::~ConstructionTransaction().
GetData()
template<typename A > Pointer< A > & absl::inlined_vector_internal::ConstructionTransaction< A >::GetData () inline
Definition at line 282 of file inlined_vector.h.
{ return allocator_data_.template get<1>(); }
References absl::get().
Referenced by absl::inlined_vector_internal::ConstructionTransaction< A >::Commit(), absl::inlined_vector_internal::ConstructionTransaction< A >::Construct(), absl::inlined_vector_internal::ConstructionTransaction< A >::DidConstruct(), and absl::inlined_vector_internal::ConstructionTransaction< A >::~ConstructionTransaction().
GetSize()
template<typename A > SizeType< A > & absl::inlined_vector_internal::ConstructionTransaction< A >::GetSize () inline
Definition at line 283 of file inlined_vector.h.
{ return size_; }
Referenced by absl::inlined_vector_internal::ConstructionTransaction< A >::Commit(), absl::inlined_vector_internal::ConstructionTransaction< A >::Construct(), and absl::inlined_vector_internal::ConstructionTransaction< A >::~ConstructionTransaction().
operator=()
template<typename A > void absl::inlined_vector_internal::ConstructionTransaction< A >::operator= (const ConstructionTransaction< A > &) delete
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/inlined_vector.h