open spiel: absl::log_internal::LogEntryTestPeer Class Reference
absl::log_internal::LogEntryTestPeer Class Reference
Public Member Functions
LogEntryTestPeer (absl::string_view base_filename, int line, bool prefix, absl::LogSeverity severity, absl::string_view timestamp, absl::LogEntry::tid_t tid, PrefixFormat format, absl::string_view text_message)
LogEntryTestPeer (const LogEntryTestPeer &)=delete
LogEntryTestPeer & operator= (const LogEntryTestPeer &)=delete
std::string FormatLogMessage () const
std::string FormatPrefixIntoSizedBuffer (size_t sz)
const absl::LogEntry & entry () const
Detailed Description
Definition at line 58 of file log_entry_test.cc.
Constructor & Destructor Documentation
LogEntryTestPeer() [1/2]
absl::log_internal::LogEntryTestPeer::LogEntryTestPeer (absl::string_view base_filename, int line, bool prefix, absl::LogSeverity severity, absl::string_view timestamp, absl::LogEntry::tid_t tid, PrefixFormat format, absl::string_view text_message) inline
Definition at line 60 of file log_entry_test.cc.
      : format_{format}, buf_(15000, '\0') {
    entry_.base_filename_ = base_filename;
    entry_.line_ = line;
    entry_.prefix_ = prefix;
    entry_.severity_ = severity;
    std::string time_err;
    EXPECT_THAT(
        absl::ParseTime("%Y-%m-%d%ET%H:%M:%E*S", timestamp,
                        absl::LocalTimeZone(), &entry_.timestamp_, &time_err),
        IsTrue())
        << "Failed to parse time " << timestamp << ": " << time_err;
    entry_.tid_ = tid;
    std::pair<absl::string_view, std::string> timestamp_bits =
        absl::StrSplit(timestamp, absl::ByChar('.'));
    EXPECT_THAT(absl::ParseCivilTime(timestamp_bits.first, &ci_.cs), IsTrue())
        << "Failed to parse time " << timestamp_bits.first;
    timestamp_bits.second.resize(9, '0');
    int64_t nanos = 0;
    EXPECT_THAT(absl::SimpleAtoi(timestamp_bits.second, &nanos), IsTrue())
        << "Failed to parse time " << timestamp_bits.first;
    ci_.subsecond = absl::Nanoseconds(nanos);
    absl::Span<char> view = absl::MakeSpan(buf_);
    view.remove_suffix(2);
    entry_.prefix_len_ =
        entry_.prefix_
            ? log_internal::FormatLogPrefix(
                  entry_.log_severity(), entry_.timestamp(), entry_.tid(),
                  entry_.source_basename(), entry_.source_line(), format_, view)
            : 0;
    EXPECT_THAT(entry_.prefix_len_,
                Eq(static_cast<size_t>(view.data() - buf_.data())));
    log_internal::AppendTruncated(text_message, view);
    view = absl::Span<char>(view.data(), view.size() + 2);
    view[0] = '\n';
    view[1] = '\0';
    view.remove_prefix(2);
    buf_.resize(static_cast<size_t>(view.data() - buf_.data()));
    entry_.text_message_with_prefix_and_newline_and_nul_ = absl::MakeSpan(buf_);
  }
References absl::log_internal::AppendTruncated(), absl::TimeZone::CivilInfo::cs, absl::Span< T >::data(), absl::log_internal::FormatLogPrefix(), absl::LocalTimeZone(), absl::LogEntry::log_severity(), absl::MakeSpan(), absl::Nanoseconds(), absl::ParseCivilTime(), absl::ParseTime(), absl::Span< T >::remove_prefix(), absl::Span< T >::remove_suffix(), absl::SimpleAtoi(), absl::Span< T >::size(), absl::LogEntry::source_basename(), absl::LogEntry::source_line(), absl::StrSplit(), absl::TimeZone::CivilInfo::subsecond, absl::LogEntry::tid(), and absl::LogEntry::timestamp().
LogEntryTestPeer() [2/2]
absl::log_internal::LogEntryTestPeer::LogEntryTestPeer (const LogEntryTestPeer &) delete
Member Function Documentation
entry()
const absl::LogEntry & absl::log_internal::LogEntryTestPeer::entry () const inline
Definition at line 124 of file log_entry_test.cc.
{ return entry_; }
FormatLogMessage()
std::string absl::log_internal::LogEntryTestPeer::FormatLogMessage () const inline
Definition at line 108 of file log_entry_test.cc.
{
    return log_internal::FormatLogMessage(
        entry_.log_severity(), ci_.cs, ci_.subsecond, entry_.tid(),
        entry_.source_basename(), entry_.source_line(), format_,
        entry_.text_message());
  }
References absl::TimeZone::CivilInfo::cs, absl::log_internal::FormatLogMessage(), absl::LogEntry::log_severity(), absl::LogEntry::source_basename(), absl::LogEntry::source_line(), absl::TimeZone::CivilInfo::subsecond, absl::LogEntry::text_message(), and absl::LogEntry::tid().
FormatPrefixIntoSizedBuffer()
std::string absl::log_internal::LogEntryTestPeer::FormatPrefixIntoSizedBuffer (size_t sz) inline
Definition at line 114 of file log_entry_test.cc.
{
    std::string str(sz, '\0');
    absl::Span<char> buf(&str[0], str.size());
    const size_t prefix_size = log_internal::FormatLogPrefix(
        entry_.log_severity(), entry_.timestamp(), entry_.tid(),
        entry_.source_basename(), entry_.source_line(), format_, buf);
    EXPECT_THAT(prefix_size, Eq(static_cast<size_t>(buf.data() - str.data())));
    str.resize(prefix_size);
    return str;
  }
References buf, absl::log_internal::FormatLogPrefix(), absl::LogEntry::log_severity(), absl::LogEntry::source_basename(), absl::LogEntry::source_line(), absl::LogEntry::tid(), and absl::LogEntry::timestamp().
operator=()
LogEntryTestPeer & absl::log_internal::LogEntryTestPeer::operator= (const LogEntryTestPeer &) delete
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/log/log_entry_test.cc