open spiel: open_spiel::phantom_ttt::PhantomTTTState Class Reference
open_spiel::phantom_ttt::PhantomTTTState Class Reference
#include <phantom_ttt.h>
Public Member Functions
PhantomTTTState (std::shared_ptr< const Game > game, ObservationType obs_type)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action move) override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
std::string ViewToString (Player player) const
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 58 of file phantom_ttt.h.
Constructor & Destructor Documentation
PhantomTTTState()
open_spiel::phantom_ttt::PhantomTTTState::PhantomTTTState (std::shared_ptr< const Game > game, ObservationType obs_type)
Definition at line 95 of file phantom_ttt.cc.
    : State(game), state_(game), obs_type_(obs_type) {
  std::fill(begin(x_view_), end(x_view_), CellState::kEmpty);
  std::fill(begin(o_view_), end(o_view_), CellState::kEmpty);
}
References begin, and end.
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::phantom_ttt::PhantomTTTState::ActionToString (Player player, Action action_id) const inline override virtual
Implements open_spiel::State.
Definition at line 64 of file phantom_ttt.h.
{
    return state_.ActionToString(player, action_id);
  }
References open_spiel::tic_tac_toe::TicTacToeState::ActionToString(), and player.
Clone()
std::unique_ptr< State > open_spiel::phantom_ttt::PhantomTTTState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 254 of file phantom_ttt.cc.
{
  return std::unique_ptr<State>(new PhantomTTTState(*this));
}
References PhantomTTTState().
CurrentPlayer()
Player open_spiel::phantom_ttt::PhantomTTTState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 63 of file phantom_ttt.h.
{ return state_.CurrentPlayer(); }
References open_spiel::tic_tac_toe::TicTacToeState::CurrentPlayer().
Referenced by DoApplyAction(), and LegalActions().
DoApplyAction()
void open_spiel::phantom_ttt::PhantomTTTState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 102 of file phantom_ttt.cc.
{
  // Current player's view.
  Player cur_player = CurrentPlayer();
  auto& cur_view = cur_player == 0 ? x_view_ : o_view_;
  // Two cases: either there is a mark already there, or not.
  if (state_.BoardAt(move) == CellState::kEmpty) {
    // No mark on board, so play this normally.
    state_.ApplyAction(move);
  }
  // Update current player's view, and action sequence.
  SPIEL_CHECK_EQ(cur_view[move], CellState::kEmpty);
  cur_view[move] = state_.BoardAt(move);
  action_sequence_.push_back(std::pair<int, Action>(cur_player, move));
  // Note: do not modify player's turn here, it will have been done above
  // if necessary.
}
References open_spiel::State::ApplyAction(), open_spiel::tic_tac_toe::TicTacToeState::BoardAt(), CurrentPlayer(), and SPIEL_CHECK_EQ.
InformationStateString()
std::string open_spiel::phantom_ttt::PhantomTTTState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 173 of file phantom_ttt.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string str;
  absl::StrAppend(&str, ViewToString(player), "\n");
  if (obs_type_ != ObservationType::kRevealNothing) {
    absl::StrAppend(&str, history_.size(), "\n");
  }
  absl::StrAppend(&str, ActionSequenceToString(player));
  return str;
}
References open_spiel::State::history_, open_spiel::phantom_ttt::kRevealNothing, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and ViewToString().
InformationStateTensor()
void open_spiel::phantom_ttt::PhantomTTTState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 185 of file phantom_ttt.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // First 27 bits encodes the player's view in the same way as TicTacToe.
  // Then the action sequence follows (one-hot encoded, per action).
  // Encoded in the same way as InformationStateAsString, so full sequences
  // which may contain action value 10 to represent "I don't know."
  const auto& player_view = player == 0 ? x_view_ : o_view_;
  SPIEL_CHECK_EQ(values.size(), kNumCells * kCellStates +
                                    kLongestSequence * (1 + kBitsPerAction));
  std::fill(values.begin(), values.end(), 0.);
  for (int cell = 0; cell < kNumCells; ++cell) {
    values[kNumCells * static_cast<int>(player_view[cell]) + cell] = 1.0;
  }
  // Now encode the sequence. Each (player, action) pair uses 11 bits:
  //   - first bit is the player taking the action (0 or 1)
  //   - next 10 bits is the one-hot encoded action (10 = "I don't know")
  int offset = kNumCells * kCellStates;
  for (const auto& player_with_action : action_sequence_) {
    if (player_with_action.first == player) {
      // Always include the observing player's actions.
      values[offset] = player_with_action.first;  // Player 0 or 1
      values[offset + 1 + player_with_action.second] = 1.0;
    } else if (obs_type_ == ObservationType::kRevealNumTurns) {
      // If the number of turns are revealed, then each of the other player's
      // actions will show up as unknowns.
      values[offset] = player_with_action.first;
      values[offset + 1 + 10] = 1.0;  // I don't know.
    } else {
      // Do not reveal anything about the number of actions taken by opponent.
      SPIEL_CHECK_EQ(obs_type_, ObservationType::kRevealNothing);
    }
    offset += (1 + kBitsPerAction);
  }
}
References open_spiel::phantom_ttt::kBitsPerAction, open_spiel::phantom_ttt::kLongestSequence, open_spiel::phantom_ttt::kRevealNothing, open_spiel::phantom_ttt::kRevealNumTurns, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::phantom_ttt::PhantomTTTState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 68 of file phantom_ttt.h.
{ return state_.IsTerminal(); }
References open_spiel::tic_tac_toe::TicTacToeState::IsTerminal().
Referenced by LegalActions().
LegalActions()
std::vector< Action > open_spiel::phantom_ttt::PhantomTTTState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 122 of file phantom_ttt.cc.
{
  if (IsTerminal()) return {};
  std::vector<Action> moves;
  const Player player = CurrentPlayer();
  const auto& cur_view = player == 0 ? x_view_ : o_view_;
  for (Action move = 0; move < kNumCells; ++move) {
    if (cur_view[move] == CellState::kEmpty) {
      moves.push_back(move);
    }
  }
  return moves;
}
References CurrentPlayer(), IsTerminal(), and player.
ObservationString()
std::string open_spiel::phantom_ttt::PhantomTTTState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 225 of file phantom_ttt.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string observation = ViewToString(player);
  if (obs_type_ == ObservationType::kRevealNumTurns) {
    absl::StrAppend(&observation, "\nTotal turns: ", action_sequence_.size());
  }
  return observation;
}
References open_spiel::phantom_ttt::kRevealNumTurns, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and ViewToString().
ObservationTensor()
void open_spiel::phantom_ttt::PhantomTTTState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 235 of file phantom_ttt.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  std::fill(values.begin(), values.end(), 0.);
  // First 27 bits encodes the player's view in the same way as TicTacToe.
  const auto& player_view = player == 0 ? x_view_ : o_view_;
  for (int cell = 0; cell < kNumCells; ++cell) {
    values[kNumCells * static_cast<int>(player_view[cell]) + cell] = 1.0;
  }
  // Then a one-hot to represent total number of turns.
  if (obs_type_ == ObservationType::kRevealNumTurns) {
    values[kNumCells * kCellStates + action_sequence_.size()] = 1.0;
  }
}
References open_spiel::State::game_, open_spiel::phantom_ttt::kRevealNumTurns, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::phantom_ttt::PhantomTTTState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 69 of file phantom_ttt.h.
{ return state_.Returns(); }
References open_spiel::tic_tac_toe::TicTacToeState::Returns().
ToString()
std::string open_spiel::phantom_ttt::PhantomTTTState::ToString () const inline override virtual
Implements open_spiel::State.
Definition at line 67 of file phantom_ttt.h.
{ return state_.ToString(); }
References open_spiel::tic_tac_toe::TicTacToeState::ToString().
UndoAction()
void open_spiel::phantom_ttt::PhantomTTTState::UndoAction (Player player, Action move) override virtual
Reimplemented from open_spiel::State.
Definition at line 258 of file phantom_ttt.cc.
{
  Action last_move = action_sequence_.back().second;
  SPIEL_CHECK_EQ(last_move, move);
  if (state_.BoardAt(move) == PlayerToState(player)) {
    // If the board has a mark that is the undoing player, then this was
    // a successful move. Undo as normal.
    state_.UndoAction(player, move);
  }
  // Undo the action from that player's view, and pop from the action seq
  auto& player_view = player == 0 ? x_view_ : o_view_;
  player_view[move] = CellState::kEmpty;
  action_sequence_.pop_back();
  history_.pop_back();
  --move_number_;
  // Note, do not change the player.. this will already have been done above
  // if necessary.
}
References open_spiel::tic_tac_toe::TicTacToeState::BoardAt(), open_spiel::State::history_, open_spiel::State::move_number_, player, SPIEL_CHECK_EQ, and open_spiel::tic_tac_toe::TicTacToeState::UndoAction().
ViewToString()
std::string open_spiel::phantom_ttt::PhantomTTTState::ViewToString (Player player) const protected
Definition at line 137 of file phantom_ttt.cc.
{
  const auto& cur_view = player == 0 ? x_view_ : o_view_;
  std::string str;
  for (int r = 0; r < kNumRows; ++r) {
    for (int c = 0; c < kNumCols; ++c) {
      absl::StrAppend(&str, StateToString(cur_view[r * kNumCols + c]));
    }
    if (r < (kNumRows - 1)) {
      absl::StrAppend(&str, "\n");
    }
  }
  return str;
}
References player, r, StateToString(), and absl::StrAppend().
Referenced by open_spiel::phantom_ttt::ImperfectRecallPTTTState::InformationStateString(), InformationStateString(), and ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/phantom_ttt/phantom_ttt.h
open_spiel/games/phantom_ttt/phantom_ttt.cc