open spiel: open_spiel::DataLoggerJsonLines Class Reference
open_spiel::DataLoggerJsonLines Class Reference
#include <data_logger.h>
Public Member Functions
DataLoggerJsonLines (const std::string &path, const std::string &name, bool flush=false, const std::string &mode="w", absl::Time start_time=absl::Now())
~DataLoggerJsonLines () override
DataLoggerJsonLines (DataLoggerJsonLines &&other)=default
DataLoggerJsonLines & operator= (DataLoggerJsonLines &&other)=default
DataLoggerJsonLines (const DataLoggerJsonLines &)=delete
DataLoggerJsonLines & operator= (const DataLoggerJsonLines &)=delete
void Write (Record record) override
void Flush () override
Public Member Functions inherited from open_spiel::DataLogger
virtual ~DataLogger ()=default
Additional Inherited Members
Public Types inherited from open_spiel::DataLogger
using Record = json::Object
Detailed Description
Definition at line 38 of file data_logger.h.
Constructor & Destructor Documentation
DataLoggerJsonLines() [1/3]
open_spiel::DataLoggerJsonLines::DataLoggerJsonLines (const std::string & path, const std::string & name, bool flush = false, const std::string & mode = "w", absl::Time start_time = absl::Now()) explicit
Definition at line 26 of file data_logger.cc.
    : fd_(absl::StrFormat("%s/%s.jsonl", path, name), mode),
      flush_(flush),
      start_time_(start_time) {}
~DataLoggerJsonLines()
open_spiel::DataLoggerJsonLines::~DataLoggerJsonLines () override
Definition at line 51 of file data_logger.cc.
{ Flush(); }
References Flush().
DataLoggerJsonLines() [2/3]
open_spiel::DataLoggerJsonLines::DataLoggerJsonLines (DataLoggerJsonLines && other) default
DataLoggerJsonLines() [3/3]
open_spiel::DataLoggerJsonLines::DataLoggerJsonLines (const DataLoggerJsonLines &) delete
Member Function Documentation
Flush()
void open_spiel::DataLoggerJsonLines::Flush () override virtual
Reimplemented from open_spiel::DataLogger.
Definition at line 49 of file data_logger.cc.
{ fd_.Flush(); }
References open_spiel::file::File::Flush().
Referenced by Write(), and ~DataLoggerJsonLines().
operator=() [1/2]
DataLoggerJsonLines & open_spiel::DataLoggerJsonLines::operator= (const DataLoggerJsonLines &) delete
operator=() [2/2]
DataLoggerJsonLines & open_spiel::DataLoggerJsonLines::operator= (DataLoggerJsonLines && other) default
Write()
void open_spiel::DataLoggerJsonLines::Write (DataLogger::Record record) override virtual
Implements open_spiel::DataLogger.
Definition at line 34 of file data_logger.cc.
{
  static absl::TimeZone utc = absl::UTCTimeZone();
  absl::Time now = absl::Now();
  record.insert({
      {"time_str", absl::FormatTime("%Y-%m-%d %H:%M:%E6S %z", now, utc)},
      {"time_abs", absl::ToUnixMicros(now) / 1000000.},
      {"time_rel", absl::ToDoubleSeconds(now - start_time_)},
  });
  fd_.Write(json::ToString(record));
  fd_.Write("\n");
  if (flush_) {
    Flush();
  }
}
References Flush(), absl::FormatTime(), absl::Now(), absl::ToDoubleSeconds(), open_spiel::json::ToString(), absl::ToUnixMicros(), absl::UTCTimeZone(), and open_spiel::file::File::Write().
The documentation for this class was generated from the following files:
open_spiel/utils/data_logger.h
open_spiel/utils/data_logger.cc