open spiel: open_spiel::algorithms::torch_az::VPNetEvaluator Class Reference
open_spiel::algorithms::torch_az::VPNetEvaluator Class Reference
#include <vpevaluator.h>
Public Member Functions
VPNetEvaluator (DeviceManager *device_manager, int batch_size, int threads, int cache_size, int cache_shards=1)
~VPNetEvaluator () override
std::vector< double > Evaluate (const State &state) override
ActionsAndProbs Prior (const State &state) override
void ClearCache ()
LRUCacheInfo CacheInfo ()
void ResetBatchSizeStats ()
open_spiel::BasicStats BatchSizeStats ()
open_spiel::HistogramNumbered BatchSizeHistogram ()
Public Member Functions inherited from open_spiel::algorithms::Evaluator
virtual ~Evaluator ()=default
Detailed Description
Definition at line 35 of file vpevaluator.h.
Constructor & Destructor Documentation
VPNetEvaluator()
open_spiel::algorithms::torch_az::VPNetEvaluator::VPNetEvaluator (DeviceManager * device_manager, int batch_size, int threads, int cache_size, int cache_shards = 1) explicit
Definition at line 28 of file vpevaluator.cc.
    : device_manager_(*device_manager),
      batch_size_(batch_size),
      queue_(batch_size * threads * 4),
      batch_size_hist_(batch_size + 1) {
  cache_shards = std::max(1, cache_shards);
  cache_.reserve(cache_shards);
  for (int i = 0; i < cache_shards; ++i) {
    cache_.push_back(
        std::make_unique<LRUCache<uint64_t, VPNetModel::InferenceOutputs>>(
            cache_size / cache_shards));
  }
  if (batch_size_ <= 1) {
    threads = 0;
  }
  inference_threads_.reserve(threads);
  for (int i = 0; i < threads; ++i) {
    inference_threads_.emplace_back([this]() { this->Runner(); });
  }
}
References i.
~VPNetEvaluator()
open_spiel::algorithms::torch_az::VPNetEvaluator::~VPNetEvaluator () override
Definition at line 50 of file vpevaluator.cc.
{
  stop_.Stop();
  queue_.BlockNewValues();
  queue_.Clear();
  for (auto& t : inference_threads_) {
    t.join();
  }
}
References open_spiel::ThreadedQueue< T >::BlockNewValues(), open_spiel::ThreadedQueue< T >::Clear(), and open_spiel::StopToken::Stop().
Member Function Documentation
BatchSizeHistogram()
open_spiel::HistogramNumbered open_spiel::algorithms::torch_az::VPNetEvaluator::BatchSizeHistogram ()
Definition at line 172 of file vpevaluator.cc.
{
  absl::MutexLock lock(&stats_m_);
  return batch_size_hist_;
}
BatchSizeStats()
open_spiel::BasicStats open_spiel::algorithms::torch_az::VPNetEvaluator::BatchSizeStats ()
Definition at line 167 of file vpevaluator.cc.
{
  absl::MutexLock lock(&stats_m_);
  return batch_size_stats_;
}
CacheInfo()
LRUCacheInfo open_spiel::algorithms::torch_az::VPNetEvaluator::CacheInfo ()
Definition at line 65 of file vpevaluator.cc.
{
  LRUCacheInfo info;
  for (auto& c : cache_) {
    info += c->Info();
  }
  return info;
}
ClearCache()
void open_spiel::algorithms::torch_az::VPNetEvaluator::ClearCache ()
Definition at line 59 of file vpevaluator.cc.
{
  for (auto& c : cache_) {
    c->Clear();
  }
}
Evaluate()
std::vector< double > open_spiel::algorithms::torch_az::VPNetEvaluator::Evaluate (const State & state) override virtual
Implements open_spiel::algorithms::Evaluator.
Definition at line 73 of file vpevaluator.cc.
{
  // TODO(author5): currently assumes zero-sum.
  double p0value = Inference(state).value;
  return {p0value, -p0value};
}
References state, and open_spiel::algorithms::torch_az::VPNetModel::InferenceOutputs::value.
Prior()
open_spiel::ActionsAndProbs open_spiel::algorithms::torch_az::VPNetEvaluator::Prior (const State & state) override virtual
Implements open_spiel::algorithms::Evaluator.
Definition at line 79 of file vpevaluator.cc.
{
  if (state.IsChanceNode()) {
    return state.ChanceOutcomes();
  } else {
    return Inference(state).policy;
  }
}
References open_spiel::algorithms::torch_az::VPNetModel::InferenceOutputs::policy, and state.
ResetBatchSizeStats()
void open_spiel::algorithms::torch_az::VPNetEvaluator::ResetBatchSizeStats ()
Definition at line 161 of file vpevaluator.cc.
{
  absl::MutexLock lock(&stats_m_);
  batch_size_stats_.Reset();
  batch_size_hist_.Reset();
}
References open_spiel::BasicStats::Reset(), and open_spiel::HistogramNumbered::Reset().
The documentation for this class was generated from the following files:
open_spiel/algorithms/alpha_zero_torch/vpevaluator.h
open_spiel/algorithms/alpha_zero_torch/vpevaluator.cc