open spiel: open_spiel::havannah::HavannahState Class Reference
open_spiel::havannah::HavannahState Class Reference
#include <havannah.h>
Public Member Functions
HavannahState (std::shared_ptr< const Game > game, int board_size, bool ansi_color_output=false, bool allow_swap=false)
HavannahState (const HavannahState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
int FindGroupLeader (int cell)
bool JoinGroups (int cell_a, int cell_b)
bool CheckRingDFS (const Move &move, int left, int right)
Move ActionToMove (Action action_id) const
bool AllowSwap () const
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 96 of file havannah.h.
Constructor & Destructor Documentation
HavannahState() [1/2]
open_spiel::havannah::HavannahState::HavannahState (std::shared_ptr< const Game > game, int board_size, bool ansi_color_output = false, bool allow_swap = false)
Definition at line 158 of file havannah.cc.
    : State(game),
      board_size_(board_size),
      board_diameter_(board_size * 2 - 1),
      valid_cells_((board_size * 2 - 1) * (board_size * 2 - 1) -
                   board_size * (board_size - 1)),  // diameter^2 - corners
      neighbors_(get_neighbors(board_size)),
      ansi_color_output_(ansi_color_output),
      allow_swap_(allow_swap) {
  board_.resize(board_diameter_ * board_diameter_);
  for (int i = 0; i < board_.size(); i++) {
    Move m = ActionToMove(i);
    board_[i] = Cell((m.OnBoard() ? kPlayerNone : kPlayerInvalid), i,
                     m.Corner(board_size), m.Edge(board_size));
  }
}
References ActionToMove(), open_spiel::havannah::Move::Corner(), open_spiel::havannah::Move::Edge(), i, open_spiel::havannah::kPlayerInvalid, open_spiel::havannah::kPlayerNone, and open_spiel::havannah::Move::OnBoard().
Referenced by Clone().
HavannahState() [2/2]
open_spiel::havannah::HavannahState::HavannahState (const HavannahState &) default
Member Function Documentation
ActionToMove()
Move open_spiel::havannah::HavannahState::ActionToMove (Action action_id) const protected
Definition at line 176 of file havannah.cc.
{
  return Move(action_id % board_diameter_, action_id / board_diameter_,
              board_size_);
}
Referenced by ActionToString(), DoApplyAction(), and HavannahState().
ActionToString()
std::string open_spiel::havannah::HavannahState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 198 of file havannah.cc.
{
  return ActionToMove(action_id).ToString();
}
References ActionToMove(), and open_spiel::havannah::Move::ToString().
AllowSwap()
bool open_spiel::havannah::HavannahState::AllowSwap () const protected
Definition at line 203 of file havannah.cc.
{
  return allow_swap_ && moves_made_ == 1 && current_player_ == kPlayer2;
}
References open_spiel::havannah::kPlayer2.
Referenced by DoApplyAction(), and LegalActions().
CheckRingDFS()
bool open_spiel::havannah::HavannahState::CheckRingDFS (const Move & move, int left, int right) protected
Definition at line 403 of file havannah.cc.
{
  if (!move.OnBoard()) return false;
  Cell& c = board_[move.xy];
  if (current_player_ != c.player) return false;
  if (c.mark) return true;  // Found a ring!
  c.mark = true;
  bool success = false;
  for (int i = left; !success && i <= right; i++) {
    int dir = (i + 6) % 6;  // Normalize.
    success = CheckRingDFS(neighbors_[move.xy][dir], dir - 1, dir + 1);
  }
  c.mark = false;
  return success;
}
References CheckRingDFS(), dir, and i.
Referenced by CheckRingDFS(), and DoApplyAction().
Clone()
std::unique_ptr< State > open_spiel::havannah::HavannahState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 420 of file havannah.cc.
{
  return std::unique_ptr<State>(new HavannahState(*this));
}
References HavannahState().
CurrentPlayer()
Player open_spiel::havannah::HavannahState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 142 of file havannah.h.
{
    return IsTerminal() ? kTerminalPlayerId : static_cast<int>(current_player_);
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::havannah::HavannahState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 328 of file havannah.cc.
{
  SPIEL_CHECK_EQ(outcome_, kPlayerNone);
  Move move = ActionToMove(action);
  SPIEL_CHECK_TRUE(move.OnBoard());
  if (last_move_ == move) {
    SPIEL_CHECK_TRUE(AllowSwap());
  } else {
    SPIEL_CHECK_EQ(board_[move.xy].player, kPlayerNone);
    moves_made_++;
    last_move_ = move;
  }
  board_[move.xy].player = current_player_;
  bool alreadyjoined = false;  // Useful for finding rings.
  bool skip = false;
  for (const Move& m : neighbors_[move.xy]) {
    if (skip) {
      skip = false;
    } else if (m.OnBoard()) {
      if (current_player_ == board_[m.xy].player) {
        alreadyjoined |= JoinGroups(move.xy, m.xy);
        // Skip the next one. If it is the same group, it is already connected
        // and forms a sharp corner, which we can ignore.
        skip = true;
      }
    }
  }
  const Cell& group = board_[FindGroupLeader(move.xy)];
  if (group.NumEdges() >= 3 || group.NumCorners() >= 2 ||
      (alreadyjoined && CheckRingDFS(move, 0, 3))) {
    outcome_ = current_player_;
  } else if (moves_made_ == valid_cells_) {
    outcome_ = kPlayerDraw;
  }
  current_player_ = (current_player_ == kPlayer1 ? kPlayer2 : kPlayer1);
}
References action, ActionToMove(), AllowSwap(), CheckRingDFS(), FindGroupLeader(), JoinGroups(), open_spiel::havannah::kPlayer1, open_spiel::havannah::kPlayer2, open_spiel::havannah::kPlayerDraw, open_spiel::havannah::kPlayerNone, SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
FindGroupLeader()
int open_spiel::havannah::HavannahState::FindGroupLeader (int cell) protected
Definition at line 370 of file havannah.cc.
{
  int parent = board_[cell].parent;
  if (parent != cell) {
    do {  // Follow the parent chain up to the group leader.
      parent = board_[parent].parent;
    } while (parent != board_[parent].parent);
    // Do path compression, but only the current one to avoid recursion.
    board_[cell].parent = parent;
  }
  return parent;
}
Referenced by DoApplyAction(), and JoinGroups().
InformationStateString()
std::string open_spiel::havannah::HavannahState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 289 of file havannah.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::havannah::HavannahState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 147 of file havannah.h.
{ return outcome_ != kPlayerNone; }
References open_spiel::havannah::kPlayerNone.
Referenced by CurrentPlayer(), and LegalActions().
JoinGroups()
bool open_spiel::havannah::HavannahState::JoinGroups (int cell_a, int cell_b) protected
Definition at line 382 of file havannah.cc.
{
  int leader_a = FindGroupLeader(cell_a);
  int leader_b = FindGroupLeader(cell_b);
  if (leader_a == leader_b)  // Already the same group.
    return true;
  if (board_[leader_a].size < board_[leader_b].size) {
    // Force group a's subtree to be bigger.
    std::swap(leader_a, leader_b);
  }
  // Group b joins group a.
  board_[leader_b].parent = leader_a;
  board_[leader_a].size += board_[leader_b].size;
  board_[leader_a].corner |= board_[leader_b].corner;
  board_[leader_a].edge |= board_[leader_b].edge;
  return false;
}
References FindGroupLeader(), and size.
Referenced by DoApplyAction().
LegalActions()
std::vector< Action > open_spiel::havannah::HavannahState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 181 of file havannah.cc.
{
  // Can move in any empty cell.
  std::vector<Action> moves;
  if (IsTerminal()) return {};
  moves.reserve(board_.size() - moves_made_);
  for (int cell = 0; cell < board_.size(); ++cell) {
    if (board_[cell].player == kPlayerNone) {
      moves.push_back(cell);
    }
  }
  if (AllowSwap()) {  // The second move is allowed to replace the first one.
    moves.push_back(last_move_.xy);
    absl::c_sort(moves);
  }
  return moves;
}
References AllowSwap(), absl::c_sort(), IsTerminal(), open_spiel::havannah::kPlayerNone, player, and open_spiel::havannah::Move::xy.
ObservationString()
std::string open_spiel::havannah::HavannahState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 295 of file havannah.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::havannah::HavannahState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 314 of file havannah.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<2> view(values, {kCellStates, static_cast<int>(board_.size())},
                     true);
  for (int i = 0; i < board_.size(); ++i) {
    if (board_[i].player < kCellStates) {
      view[{PlayerRelative(board_[i].player, player), i}] = 1.0;
    }
  }
}
References i, open_spiel::havannah::kCellStates, open_spiel::State::num_players_, player, open_spiel::havannah::PlayerRelative(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::havannah::HavannahState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 282 of file havannah.cc.
{
  if (outcome_ == kPlayer1) return {1, -1};
  if (outcome_ == kPlayer2) return {-1, 1};
  if (outcome_ == kPlayerDraw) return {0, 0};
  return {0, 0};  // Unfinished
}
References open_spiel::havannah::kPlayer1, open_spiel::havannah::kPlayer2, and open_spiel::havannah::kPlayerDraw.
ToString()
std::string open_spiel::havannah::HavannahState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 207 of file havannah.cc.
{
  // Generates something like:
  //        a b c d e
  //     1 @ O . @ O f
  //    2 . O O @ O @ g
  //   3 . @ @ . . @ O h
  //  4 . @ @ . . . O O i
  // 5 @ . . O . @ @ O .
  //  6 @ O . O O @ @[O]
  //   7 . @ O . O O O
  //    8 @ O @ O O O
  //     9 @ O @ @ @
  std::string white = "O";
  std::string black = "@";
  std::string empty = ".";
  std::string coord = "";
  std::string reset = "";
  if (ansi_color_output_) {
    std::string esc = "\033";
    reset = esc + "[0m";
    coord = esc + "[1;37m";  // bright white
    empty = reset + ".";
    white = esc + "[1;33m" + "@";  // bright yellow
    black = esc + "[1;34m" + "@";  // bright blue
  }
  std::ostringstream out;
  // Top x coords.
  out << std::string(board_size_ + 3, ' ');
  for (int x = 0; x < board_size_; x++) {
    out << ' ' << coord << static_cast<char>('a' + x);
  }
  out << '\n';
  for (int y = 0; y < board_diameter_; y++) {
    out << std::string(abs(board_size_ - 1 - y) + 1 + ((y + 1) < 10), ' ');
    out << coord << (y + 1);  // Leading y coord.
    bool found_last = false;
    int start_x = (y < board_size_ ? 0 : y - board_size_ + 1);
    int end_x = (y < board_size_ ? board_size_ + y : board_diameter_);
    for (int x = start_x; x < end_x; x++) {
      Move pos(x, y, board_size_);
      // Spacing and last-move highlight.
      if (found_last) {
        out << coord << ']';
        found_last = false;
      } else if (last_move_ == pos) {
        out << coord << '[';
        found_last = true;
      } else {
        out << ' ';
      }
      // Actual piece.
      Player p = board_[pos.xy].player;
      if (p == kPlayerNone) out << empty;
      if (p == kPlayer1) out << white;
      if (p == kPlayer2) out << black;
    }
    if (found_last) {
      out << coord << ']';
    }
    if (y < board_size_ - 1) {  // Trailing x coord.
      out << ' ' << coord << static_cast<char>('a' + board_size_ + y);
    }
    out << '\n';
  }
  out << reset;
  return out.str();
}
References open_spiel::havannah::kPlayer1, open_spiel::havannah::kPlayer2, open_spiel::havannah::kPlayerNone, out, x, and y.
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/havannah/havannah.h
open_spiel/games/havannah/havannah.cc