open spiel: absl::hash_internal::PiecewiseCombiner Class Reference
absl::hash_internal::PiecewiseCombiner Class Reference
#include <hash.h>
Public Member Functions
PiecewiseCombiner ()
PiecewiseCombiner (const PiecewiseCombiner &)=delete
PiecewiseCombiner & operator= (const PiecewiseCombiner &)=delete
template<typename H >
H add_buffer (H state, const unsigned char *data, size_t size)
template<typename H >
H add_buffer (H state, const char *data, size_t size)
template<typename H >
H finalize (H state)
Detailed Description
Definition at line 90 of file hash.h.
Constructor & Destructor Documentation
PiecewiseCombiner() [1/2]
absl::hash_internal::PiecewiseCombiner::PiecewiseCombiner () inline
Definition at line 92 of file hash.h.
: position_(0) {}
PiecewiseCombiner() [2/2]
absl::hash_internal::PiecewiseCombiner::PiecewiseCombiner (const PiecewiseCombiner &) delete
Member Function Documentation
add_buffer() [1/2]
template<typename H > H absl::hash_internal::PiecewiseCombiner::add_buffer (H state, const char * data, size_t size) inline
Definition at line 103 of file hash.h.
{
    return add_buffer(std::move(state),
                      reinterpret_cast<const unsigned char*>(data), size);
  }
References add_buffer(), size, and state.
add_buffer() [2/2]
template<typename H > H absl::hash_internal::PiecewiseCombiner::add_buffer (H state, const unsigned char * data, size_t size)
Definition at line 1263 of file hash.h.
{
  if (position_ + size < PiecewiseChunkSize()) {
    // This partial chunk does not fill our existing buffer
    memcpy(buf_ + position_, data, size);
    position_ += size;
    return state;
  }
  // If the buffer is partially filled we need to complete the buffer
  // and hash it.
  if (position_ != 0) {
    const size_t bytes_needed = PiecewiseChunkSize() - position_;
    memcpy(buf_ + position_, data, bytes_needed);
    state = H::combine_contiguous(std::move(state), buf_, PiecewiseChunkSize());
    data += bytes_needed;
    size -= bytes_needed;
  }
  // Hash whatever chunks we can without copying
  while (size >= PiecewiseChunkSize()) {
    state = H::combine_contiguous(std::move(state), data, PiecewiseChunkSize());
    data += PiecewiseChunkSize();
    size -= PiecewiseChunkSize();
  }
  // Fill the buffer with the remainder
  memcpy(buf_, data, size);
  position_ = size;
  return state;
}
References absl::hash_internal::PiecewiseChunkSize(), size, and state.
Referenced by add_buffer().
finalize()
template<typename H > H absl::hash_internal::PiecewiseCombiner::finalize (H state)
Definition at line 1296 of file hash.h.
{
  // Hash the remainder left in the buffer, which may be empty
  return H::combine_contiguous(std::move(state), buf_, position_);
}
References state.
operator=()
PiecewiseCombiner & absl::hash_internal::PiecewiseCombiner::operator= (const PiecewiseCombiner &) delete
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/hash/internal/hash.h