open spiel: absl::crc_internal::CRCImpl Class Reference
absl::crc_internal::CRCImpl Class Reference abstract
#include <crc_internal.h>
Public Types
using Uint32By256 = uint32_t[256]
Public Member Functions
CRCImpl ()
~CRCImpl () override=default
void Empty (uint32_t *crc) const override
virtual void InitTables ()=0
Public Member Functions inherited from absl::crc_internal::CRC
virtual ~CRC ()
virtual void Extend (uint32_t *crc, const void *bytes, size_t length) const =0
virtual void ExtendByZeroes (uint32_t *crc, size_t length) const =0
virtual void UnextendByZeroes (uint32_t *crc, size_t length) const =0
virtual void Concat (uint32_t *px, uint32_t y, size_t ylen)
virtual void Scramble (uint32_t *crc) const =0
virtual void Unscramble (uint32_t *crc) const =0
Static Public Member Functions
static CRCImpl * NewInternal ()
static void FillWordTable (uint32_t poly, uint32_t last, int word_size, Uint32By256 *t)
static int FillZeroesTable (uint32_t poly, Uint32By256 *t)
Static Public Member Functions inherited from absl::crc_internal::CRC
static CRC * Crc32c ()
Additional Inherited Members
Protected Member Functions inherited from absl::crc_internal::CRC
CRC ()
Detailed Description
Definition at line 63 of file crc_internal.h.
Member Typedef Documentation
Uint32By256
using absl::crc_internal::CRCImpl::Uint32By256 = uint32_t[256]
Definition at line 65 of file crc_internal.h.
Constructor & Destructor Documentation
CRCImpl()
absl::crc_internal::CRCImpl::CRCImpl () inline
Definition at line 67 of file crc_internal.h.
{}
~CRCImpl()
absl::crc_internal::CRCImpl::~CRCImpl () override default
Member Function Documentation
Empty()
void absl::crc_internal::CRCImpl::Empty (uint32_t * crc) const override virtual
Implements absl::crc_internal::CRC.
Definition at line 180 of file crc.cc.
{ *crc = kCrc32cPoly; }
FillWordTable()
void absl::crc_internal::CRCImpl::FillWordTable (uint32_t poly, uint32_t last, int word_size, Uint32By256 * t) static
Definition at line 101 of file crc.cc.
{
  for (int j = 0; j != word_size; j++) {  // for each byte of extension....
    t[j][0] = 0;                          // a zero has no effect
    for (int i = 128; i != 0; i >>= 1) {  // fill in entries for powers of 2
      if (j == 0 && i == 128) {
        t[j][i] = last;  // top bit in last byte is given
      } else {
        // each successive power of two is derived from the previous
        // one, either in this table, or the last table
        uint32_t pred;
        if (i == 128) {
          pred = t[j - 1][1];
        } else {
          pred = t[j][i << 1];
        }
        // Advance the CRC by one bit (multiply by X, and take remainder
        // through one step of polynomial long division)
        if (pred & 1) {
          t[j][i] = (pred >> 1) ^ poly;
        } else {
          t[j][i] = pred >> 1;
        }
      }
    }
    // CRCs have the property that CRC(a xor b) == CRC(a) xor CRC(b)
    // so we can make all the tables for non-powers of two by
    // xoring previously created entries.
    for (int i = 2; i != 256; i <<= 1) {
      for (int k = i + 1; k != (i << 1); k++) {
        t[j][k] = t[j][i] ^ t[j][k - i];
      }
    }
  }
}
References absl::i.
Referenced by absl::crc_internal::CRC32::InitTables().
FillZeroesTable()
int absl::crc_internal::CRCImpl::FillZeroesTable (uint32_t poly, Uint32By256 * t) static
Definition at line 137 of file crc.cc.
{
  uint32_t inc = 1;
  inc <<= 31;
  // Extend by one zero bit. We know degree > 1 so (inc & 1) == 0.
  inc >>= 1;
  // Now extend by 2, 4, and 8 bits, so now `inc` is extended by one zero byte.
  for (int i = 0; i < 3; ++i) {
    PolyMultiply(&inc, inc, poly);
  }
  int j = 0;
  for (uint64_t inc_len = 1; inc_len != 0; inc_len <<= ZEROES_BASE_LG) {
    // Every entry in the table adds an additional inc_len zeroes.
    uint32_t v = inc;
    for (int a = 1; a != ZEROES_BASE; a++) {
      t[0][j] = v;
      PolyMultiply(&v, inc, poly);
      j++;
    }
    inc = v;
  }
  ABSL_RAW_CHECK(j <= 256, "");
  return j;
}
References absl::a, ABSL_RAW_CHECK, absl::i, and absl::v.
Referenced by absl::crc_internal::CRC32::InitTables().
InitTables()
virtual void absl::crc_internal::CRCImpl::InitTables () pure virtual
Implemented in absl::crc_internal::CRC32.
Referenced by NewInternal().
NewInternal()
CRCImpl * absl::crc_internal::CRCImpl::NewInternal () static
Definition at line 165 of file crc.cc.
{
  // Find an accelearated implementation first.
  CRCImpl* result = TryNewCRC32AcceleratedX86ARMCombined();
  // Fall back to generic implementions if no acceleration is available.
  if (result == nullptr) {
    result = new CRC32();
  }
  result->InitTables();
  return result;
}
References InitTables(), and absl::crc_internal::TryNewCRC32AcceleratedX86ARMCombined().
Referenced by absl::crc_internal::CRC::Crc32c().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/crc/internal/crc_internal.h
open_spiel/abseil-cpp/absl/crc/internal/crc.cc