open spiel: absl::FormatSink Class Reference
absl::FormatSink Class Reference
#include <str_format.h>
Public Member Functions
void Append (size_t count, char ch)
void Append (string_view v)
bool PutPaddedString (string_view v, int width, int precision, bool left)
Friends
void AbslFormatFlush (FormatSink *sink, absl::string_view v)
Detailed Description
Definition at line 827 of file str_format.h.
Member Function Documentation
Append() [1/2]
void absl::FormatSink::Append (size_t count, char ch) inline
Definition at line 832 of file str_format.h.
{ sink_->Append(count, ch); }
References absl::str_format_internal::FormatSinkImpl::Append().
Append() [2/2]
void absl::FormatSink::Append (string_view v) inline
Definition at line 836 of file str_format.h.
{ sink_->Append(v); }
References absl::str_format_internal::FormatSinkImpl::Append(), and absl::v.
PutPaddedString()
bool absl::FormatSink::PutPaddedString (string_view v, int width, int precision, bool left) inline
Definition at line 844 of file str_format.h.
{
    return sink_->PutPaddedString(v, width, precision, left);
  }
References precision, absl::str_format_internal::FormatSinkImpl::PutPaddedString(), and absl::v.
Friends And Related Symbol Documentation
AbslFormatFlush
void AbslFormatFlush (FormatSink * sink, absl::string_view v) friend
Definition at line 849 of file str_format.h.
{
    sink->Append(v);
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/str_format.h