open spiel: open_spiel::State Class Reference
open_spiel::State Class Reference abstract
#include <spiel.h>
Inherited by open_spiel::PyState, open_spiel::RestrictedNashResponseState, open_spiel::SimMoveState, open_spiel::TurnBasedSimultaneousState, open_spiel::WrappedState, open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::sheriff::SheriffState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, and open_spiel::y_game::YState.
Classes
struct PlayerAction
Public Member Functions
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual Player CurrentPlayer () const =0
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
virtual std::vector< Action > LegalActions () const =0
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
virtual std::string ActionToString (Player player, Action action_id) const =0
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual std::string ToString () const =0
virtual bool operator== (const State &other) const
virtual bool IsTerminal () const =0
virtual std::vector< double > Rewards () const
virtual std::vector< double > Returns () const =0
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
virtual std::string ObservationString (Player player) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
virtual std::unique_ptr< State > Clone () const =0
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
virtual void DoApplyAction (Action action_id)
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 210 of file spiel.h.
Constructor & Destructor Documentation
~State()
virtual open_spiel::State::~State () virtual default
State() [1/2]
open_spiel::State::State (std::shared_ptr< const Game > game)
Definition at line 258 of file spiel.cc.
    : game_(game),
      num_distinct_actions_(game->NumDistinctActions()),
      num_players_(game->NumPlayers()),
      move_number_(0) {}
State() [2/2]
open_spiel::State::State (const State &) default
Member Function Documentation
ActionsConsistentWithInformationFrom()
virtual std::vector< Action > open_spiel::State::ActionsConsistentWithInformationFrom (Action action) const inline virtual
Reimplemented in open_spiel::connect_four::ConnectFourState, open_spiel::leduc_poker::LeducState, open_spiel::universal_poker::UniversalPokerState, and open_spiel::WrappedState.
Definition at line 682 of file spiel.h.
{
    SpielFatalError(
        "ActionsConsistentWithInformationFrom has not been implemented.");
    return {};
  }
References open_spiel::SpielFatalError().
ActionToString() [1/2]
std::string open_spiel::State::ActionToString (Action action_id) const inline
Definition at line 295 of file spiel.h.
{
    return ActionToString(CurrentPlayer(), action_id);
  }
References ActionToString(), and CurrentPlayer().
ActionToString() [2/2]
virtual std::string open_spiel::State::ActionToString (Player player, Action action_id) const pure virtual
Implemented in open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::blotto::BlottoState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::matching_pennies_3p::MatchingPennies3pState, open_spiel::matrix_game::MatrixState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pathfinding::PathfindingState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tensor_game::TensorState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, and open_spiel::y_game::YState.
Referenced by ActionToString(), ApplyActionsWithLegalityChecks(), ApplyActionWithLegalityCheck(), open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::SimMoveState::FlatJointActionToString(), StateActionToString(), and StringToAction().
ApplyAction()
void open_spiel::State::ApplyAction (Action action_id) virtual
Reimplemented in open_spiel::SimMoveState.
Definition at line 338 of file spiel.cc.
{
  // history_ needs to be modified *after* DoApplyAction which could
  // be using it.
  // Cannot apply an invalid action.
  SPIEL_CHECK_NE(action_id, kInvalidAction);
  Player player = CurrentPlayer();
  DoApplyAction(action_id);
  history_.push_back({player, action_id});
  ++move_number_;
}
References CurrentPlayer(), DoApplyAction(), history_, open_spiel::kInvalidAction, move_number_, player, and SPIEL_CHECK_NE.
Referenced by ApplyActionWithLegalityCheck(), define_julia_module(), open_spiel::negotiation::NegotiationGame::DeserializeState(), open_spiel::dark_hex::DarkHexState::DoApplyAction(), open_spiel::phantom_ttt::PhantomTTTState::DoApplyAction(), and StateApplyAction().
ApplyActions()
void open_spiel::State::ApplyActions (const std::vector< Action > & actions)
Definition at line 362 of file spiel.cc.
{
  // history_ needs to be modified *after* DoApplyActions which could
  // be using it.
  DoApplyActions(actions);
  history_.reserve(history_.size() + actions.size());
  for (int player = 0; player < actions.size(); ++player) {
    history_.push_back({player, actions[player]});
  }
  ++move_number_;
}
References DoApplyActions(), history_, move_number_, and player.
Referenced by ApplyActionsWithLegalityChecks(), and open_spiel::SimMoveState::ApplyFlatJointAction().
ApplyActionsWithLegalityChecks()
void open_spiel::State::ApplyActionsWithLegalityChecks (const std::vector< Action > & actions)
Definition at line 373 of file spiel.cc.
{
  for (Player player = 0; player < actions.size(); ++player) {
    std::vector<Action> legal_actions = LegalActions(player);
    if (!legal_actions.empty() &&
        absl::c_find(legal_actions, actions[player]) == legal_actions.end()) {
      SpielFatalError(
          absl::StrCat("Player ", player, " calling ApplyAction ",
                       "with illegal action (", actions[player], "): ",
                       ActionToString(player, actions[player])));
    }
  }
  ApplyActions(actions);
}
References ActionToString(), ApplyActions(), absl::c_find(), LegalActions(), player, open_spiel::SpielFatalError(), and absl::StrCat().
ApplyActionWithLegalityCheck()
void open_spiel::State::ApplyActionWithLegalityCheck (Action action_id) virtual
Definition at line 350 of file spiel.cc.
{
  std::vector<Action> legal_actions = LegalActions();
  if (absl::c_find(legal_actions, action_id) == legal_actions.end()) {
    Player cur_player = CurrentPlayer();
    SpielFatalError(
        absl::StrCat("Current player ", cur_player, " calling ApplyAction ",
                     "with illegal action (", action_id, "): ",
                     ActionToString(cur_player, action_id)));
  }
  ApplyAction(action_id);
}
References ActionToString(), ApplyAction(), absl::c_find(), CurrentPlayer(), LegalActions(), open_spiel::SpielFatalError(), and absl::StrCat().
ChanceOutcomes()
virtual ActionsAndProbs open_spiel::State::ChanceOutcomes () const inline virtual
Reimplemented in open_spiel::algorithms::AFCCEState, open_spiel::algorithms::AFCEState, open_spiel::algorithms::CCEState, open_spiel::algorithms::CEState, open_spiel::algorithms::EFCCEState, open_spiel::algorithms::EFCEState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::blackjack::BlackjackState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::hearts::HeartsState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::negotiation::NegotiationState, open_spiel::oh_hell::OhHellState, open_spiel::pathfinding::PathfindingState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::RestrictedNashResponseState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::universal_poker::UniversalPokerState, and open_spiel::WrappedState.
Definition at line 616 of file spiel.h.
{
    SpielFatalError("ChanceOutcomes unimplemented!");
  }
References open_spiel::SpielFatalError().
Referenced by define_julia_module(), LegalChanceOutcomes(), StateFillChanceOutcomes(), and StateSizeChanceOutcomes().
Child()
std::unique_ptr< State > open_spiel::State::Child (Action action) const inline
Definition at line 566 of file spiel.h.
{
    std::unique_ptr<State> child = Clone();
    child->ApplyAction(action);
    return child;
  }
References action, and Clone().
Referenced by open_spiel::algorithms::DecisionNodes(), define_julia_module(), and open_spiel::solitaire::SolitaireState::LegalActions().
Clone()
virtual std::unique_ptr< State > open_spiel::State::Clone () const pure virtual
Implemented in open_spiel::add_noise::AddNoiseState, open_spiel::algorithms::AFCCEState, open_spiel::algorithms::AFCEState, open_spiel::algorithms::CCEState, open_spiel::algorithms::CEState, open_spiel::algorithms::EFCCEState, open_spiel::algorithms::EFCEState, open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::blotto::BlottoState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::dark_hex::ImperfectRecallDarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::ImperfectRecallLiarsDiceState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::matching_pennies_3p::MatchingPennies3pState, open_spiel::matrix_game::MatrixState, open_spiel::MisereState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pathfinding::PathfindingState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::ImperfectRecallPTTTState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::StartAtTransformationState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tensor_game::TensorState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, open_spiel::y_game::YState, and open_spiel::ZeroSumState.
Referenced by Child(), open_spiel::testing::ConsolePlayTest(), open_spiel::algorithms::DecisionNodes(), define_julia_module(), open_spiel::algorithms::RecordTrajectory(), and StateClone().
CurrentPlayer()
virtual Player open_spiel::State::CurrentPlayer () const pure virtual
Implemented in open_spiel::algorithms::AFCCEState, open_spiel::algorithms::AFCEState, open_spiel::algorithms::CCEState, open_spiel::algorithms::CEState, open_spiel::algorithms::EFCCEState, open_spiel::algorithms::EFCEState, open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::NFGState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pathfinding::PathfindingState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, and open_spiel::y_game::YState.
Referenced by ActionToString(), open_spiel::SimMoveState::ApplyAction(), ApplyAction(), ApplyActionWithLegalityCheck(), open_spiel::algorithms::DecisionNodes(), define_julia_module(), GetHistoriesConsistentWithInfostate(), GetType(), InformationStateString(), InformationStateTensor(), IsChanceNode(), IsMeanFieldNode(), IsPlayerActing(), IsPlayerNode(), IsSimultaneousNode(), open_spiel::SimMoveState::LegalActions(), LegalActions(), LegalActionsMask(), ObservationString(), ObservationTensor(), StateCurrentPlayer(), and StringToAction().
DistributionSupport()
virtual std::vector< std::string > open_spiel::State::DistributionSupport () inline virtual
Reimplemented in open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::garnet::GarnetState, and open_spiel::PyState.
Definition at line 700 of file spiel.h.
{
    SpielFatalError("DistributionSupport has not been implemented");
  }
References open_spiel::SpielFatalError().
Referenced by define_julia_module().
DoApplyAction()
virtual void open_spiel::State::DoApplyAction (Action action_id) inline protected virtual
Reimplemented in open_spiel::algorithms::AFCCEState, open_spiel::algorithms::AFCEState, open_spiel::algorithms::CCEState, open_spiel::algorithms::CEState, open_spiel::algorithms::EFCCEState, open_spiel::algorithms::EFCEState, open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::oware::OwareState, open_spiel::pathfinding::PathfindingState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, and open_spiel::y_game::YState.
Definition at line 718 of file spiel.h.
{
    SpielFatalError("DoApplyAction is not implemented.");
  }
References open_spiel::SpielFatalError().
Referenced by open_spiel::SimMoveState::ApplyAction(), and ApplyAction().
DoApplyActions()
virtual void open_spiel::State::DoApplyActions (const std::vector< Action > & actions) inline protected virtual
Reimplemented in open_spiel::blotto::BlottoState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::goofspiel::GoofspielState, open_spiel::laser_tag::LaserTagState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::matching_pennies_3p::MatchingPennies3pState, open_spiel::matrix_game::MatrixState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::pathfinding::PathfindingState, open_spiel::PyState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::SimMoveState, open_spiel::tensor_game::TensorState, and open_spiel::WrappedState.
Definition at line 722 of file spiel.h.
{
    SpielFatalError("DoApplyActions is not implemented.");
  }
References open_spiel::SpielFatalError().
Referenced by ApplyActions().
FullHistory()
const std::vector< PlayerAction > & open_spiel::State::FullHistory () const inline
Definition at line 416 of file spiel.h.
{ return history_; }
References history_.
Referenced by open_spiel::ActionObservationHistory::ActionObservationHistory(), open_spiel::algorithms::CheckBeliefs(), define_julia_module(), and open_spiel::hearts::HeartsState::ResampleFromInfostate().
GetGame()
std::shared_ptr< const Game > open_spiel::State::GetGame () const inline
Definition at line 602 of file spiel.h.
{ return game_; }
References game_.
Referenced by open_spiel::ActionObservationHistory::ActionObservationHistory(), open_spiel::leduc_poker::LeducState::ActionToString(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::DoApplyAction(), MeanFieldPopulation(), open_spiel::leduc_poker::LeducState::ResampleFromInfostate(), StateSizeInformationState(), and StateSizeObservation().
GetHistoriesConsistentWithInfostate() [1/2]
virtual std::unique_ptr< HistoryDistribution > open_spiel::State::GetHistoriesConsistentWithInfostate () const inline virtual
Definition at line 673 of file spiel.h.
{
    return GetHistoriesConsistentWithInfostate(CurrentPlayer());
  }
References CurrentPlayer(), and GetHistoriesConsistentWithInfostate().
Referenced by GetHistoriesConsistentWithInfostate(), and open_spiel::universal_poker::UniversalPokerState::ResampleFromInfostate().
GetHistoriesConsistentWithInfostate() [2/2]
virtual std::unique_ptr< HistoryDistribution > open_spiel::State::GetHistoriesConsistentWithInfostate (int player_id) const inline virtual
Reimplemented in open_spiel::universal_poker::UniversalPokerState.
Definition at line 668 of file spiel.h.
{
    return {};
  }
GetType()
StateType open_spiel::State::GetType () const
Definition at line 118 of file spiel.cc.
{
  if (IsChanceNode()) {
    return StateType::kChance;
  } else if (IsTerminal()) {
    return StateType::kTerminal;
  } else if (CurrentPlayer() == kMeanFieldPlayerId) {
    return StateType::kMeanField;
  } else {
    return StateType::kDecision;
  }
}
References CurrentPlayer(), IsChanceNode(), IsTerminal(), open_spiel::kChance, open_spiel::kDecision, open_spiel::kMeanField, open_spiel::kMeanFieldPlayerId, and open_spiel::kTerminal.
Referenced by define_julia_module(), and MeanFieldPopulation().
History()
std::vector< Action > open_spiel::State::History () const inline
Definition at line 408 of file spiel.h.
{
    std::vector<Action> history;
    history.reserve(history_.size());
    for (auto& h : history_) history.push_back(h.action);
    return history;
  }
References history_.
Referenced by define_julia_module(), HistoryString(), open_spiel::bargaining::BargainingState::ResampleFromInfostate(), open_spiel::colored_trails::ColoredTrailsState::ResampleFromInfostate(), open_spiel::oh_hell::OhHellState::ResampleFromInfostate(), open_spiel::chess::ChessState::Serialize(), Serialize(), and open_spiel::tarok::TarokState::Serialize().
HistoryString()
std::string open_spiel::State::HistoryString () const inline
Definition at line 421 of file spiel.h.
{ return absl::StrJoin(History(), ", "); }
References History(), and absl::StrJoin().
Referenced by define_julia_module(), open_spiel::amazons::AmazonsState::InformationStateString(), open_spiel::checkers::CheckersState::InformationStateString(), open_spiel::chess::ChessState::InformationStateString(), open_spiel::cliff_walking::CliffWalkingState::InformationStateString(), open_spiel::clobber::ClobberState::InformationStateString(), open_spiel::connect_four::ConnectFourState::InformationStateString(), open_spiel::crowd_modelling::CrowdModellingState::InformationStateString(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::InformationStateString(), open_spiel::cursor_go::CursorGoState::InformationStateString(), open_spiel::dots_and_boxes::DotsAndBoxesState::InformationStateString(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::InformationStateString(), open_spiel::go::GoState::InformationStateString(), open_spiel::havannah::HavannahState::InformationStateString(), open_spiel::hex::HexState::InformationStateString(), open_spiel::morpion_solitaire::MorpionState::InformationStateString(), open_spiel::NFGState::InformationStateString(), open_spiel::nim::NimState::InformationStateString(), open_spiel::nine_mens_morris::NineMensMorrisState::InformationStateString(), open_spiel::oshi_zumo::OshiZumoState::InformationStateString(), open_spiel::othello::OthelloState::InformationStateString(), open_spiel::pentago::PentagoState::InformationStateString(), open_spiel::quoridor::QuoridorState::InformationStateString(), open_spiel::solitaire::SolitaireState::InformationStateString(), open_spiel::tic_tac_toe::TicTacToeState::InformationStateString(), open_spiel::twenty_forty_eight::TwentyFortyEightState::InformationStateString(), open_spiel::ultimate_tic_tac_toe::UltimateTTTState::InformationStateString(), open_spiel::y_game::YState::InformationStateString(), open_spiel::NFGState::ObservationString(), open_spiel::negotiation::NegotiationState::Serialize(), open_spiel::matrix_game::MatrixState::ToString(), open_spiel::NFGState::ToString(), and open_spiel::tensor_game::TensorState::ToString().
InformationStateString() [1/2]
std::string open_spiel::State::InformationStateString () const inline
Definition at line 484 of file spiel.h.
{
    return InformationStateString(CurrentPlayer());
  }
References CurrentPlayer(), and InformationStateString().
Referenced by open_spiel::algorithms::CCEState::CurrentRecommendedStatePolicy(), InformationStateString(), open_spiel::colored_trails::ColoredTrailsState::ObservationString(), open_spiel::tiny_hanabi::TinyHanabiState::ObservationString(), open_spiel::colored_trails::ColoredTrailsState::ResampleFromInfostate(), open_spiel::hearts::HeartsState::ResampleFromInfostate(), and open_spiel::oh_hell::OhHellState::ResampleFromInfostate().
InformationStateString() [2/2]
virtual std::string open_spiel::State::InformationStateString (Player player) const inline virtual
Reimplemented in open_spiel::algorithms::AFCCEState, open_spiel::algorithms::AFCEState, open_spiel::algorithms::CCEState, open_spiel::algorithms::CEState, open_spiel::algorithms::EFCCEState, open_spiel::algorithms::EFCEState, open_spiel::amazons::AmazonsState, open_spiel::bargaining::BargainingState, open_spiel::battleship::BattleshipState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coordinated_mp::PenniesState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_hex::DarkHexState, open_spiel::dark_hex::ImperfectRecallDarkHexState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kuhn_poker::KuhnState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::ImperfectRecallLiarsDiceState, open_spiel::liars_dice::LiarsDiceState, open_spiel::morpion_solitaire::MorpionState, open_spiel::NFGState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::othello::OthelloState, open_spiel::pentago::PentagoState, open_spiel::phantom_ttt::ImperfectRecallPTTTState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::solitaire::SolitaireState, open_spiel::tarok::TarokState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, and open_spiel::y_game::YState.
Definition at line 481 of file spiel.h.
{
    SpielFatalError("InformationStateString is not implemented.");
  }
References open_spiel::SpielFatalError().
Referenced by open_spiel::algorithms::CheckBeliefs().
InformationStateTensor() [1/4]
std::vector< float > open_spiel::State::InformationStateTensor () const inline
Definition at line 510 of file spiel.h.
{
    return InformationStateTensor(CurrentPlayer());
  }
References CurrentPlayer(), and InformationStateTensor().
Referenced by InformationStateTensor(), InformationStateTensor(), InformationStateTensor(), open_spiel::colored_trails::ColoredTrailsState::ObservationTensor(), and open_spiel::tiny_hanabi::TinyHanabiState::ObservationTensor().
InformationStateTensor() [2/4]
std::vector< float > open_spiel::State::InformationStateTensor (Player player) const
Definition at line 789 of file spiel.cc.
{
  // We add this player check, to prevent errors if the game implementation
  // lacks that check (in particular as this function is the one used in
  // Python). This can lead to doing this check twice.
  // TODO(author2): Do we want to prevent executing this twice for games
  // that implement it?
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::vector<float> info_state(game_->InformationStateTensorSize());
  InformationStateTensor(player, absl::MakeSpan(info_state));
  return info_state;
}
References game_, InformationStateTensor(), absl::MakeSpan(), num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
InformationStateTensor() [3/4]
virtual void open_spiel::State::InformationStateTensor (Player player, absl::Span< float > values) const inline virtual
Reimplemented in open_spiel::bargaining::BargainingState, open_spiel::battleship::BattleshipState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::dark_hex::DarkHexState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::goofspiel::GoofspielState, open_spiel::hearts::HeartsState, open_spiel::kuhn_poker::KuhnState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::NFGState, open_spiel::oh_hell::OhHellState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::PyState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::universal_poker::UniversalPokerState, and open_spiel::WrappedState.
Definition at line 505 of file spiel.h.
{
    SpielFatalError("InformationStateTensor unimplemented!");
  }
References open_spiel::SpielFatalError().
Referenced by StateFillInformationState(), and StateFillInformationStatePlayer().
InformationStateTensor() [4/4]
void open_spiel::State::InformationStateTensor (Player player, std::vector< float > * values) const virtual
Definition at line 802 of file spiel.cc.
{
  // Retained for backwards compatibility.
  values->resize(game_->InformationStateTensorSize());
  InformationStateTensor(player, absl::MakeSpan(*values));
}
References game_, InformationStateTensor(), absl::MakeSpan(), player, and values.
IsChanceNode()
virtual bool open_spiel::State::IsChanceNode () const inline virtual
Reimplemented in open_spiel::solitaire::SolitaireState, and open_spiel::universal_poker::UniversalPokerState.
Definition at line 371 of file spiel.h.
{
    return CurrentPlayer() == kChancePlayerId;
  }
References CurrentPlayer(), and open_spiel::kChancePlayerId.
Referenced by open_spiel::coordinated_mp::PenniesState::ActionToString(), open_spiel::crowd_modelling::CrowdModellingState::ActionToString(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::ActionToString(), open_spiel::garnet::GarnetState::ActionToString(), open_spiel::backgammon::BackgammonState::ChanceOutcomes(), open_spiel::bargaining::BargainingState::ChanceOutcomes(), open_spiel::blackjack::BlackjackState::ChanceOutcomes(), open_spiel::colored_trails::ColoredTrailsState::ChanceOutcomes(), open_spiel::coop_box_pushing::CoopBoxPushingState::ChanceOutcomes(), open_spiel::coordinated_mp::PenniesState::ChanceOutcomes(), open_spiel::efg_game::EFGState::ChanceOutcomes(), open_spiel::gin_rummy::GinRummyState::ChanceOutcomes(), open_spiel::goofspiel::GoofspielState::ChanceOutcomes(), open_spiel::kuhn_poker::KuhnState::ChanceOutcomes(), open_spiel::laser_tag::LaserTagState::ChanceOutcomes(), open_spiel::leduc_poker::LeducState::ChanceOutcomes(), open_spiel::lewis_signaling::LewisSignalingState::ChanceOutcomes(), open_spiel::liars_dice::LiarsDiceState::ChanceOutcomes(), open_spiel::maedn::MaednState::ChanceOutcomes(), open_spiel::markov_soccer::MarkovSoccerState::ChanceOutcomes(), open_spiel::negotiation::NegotiationState::ChanceOutcomes(), open_spiel::pathfinding::PathfindingState::ChanceOutcomes(), open_spiel::pig::PigState::ChanceOutcomes(), open_spiel::stones_and_gems::StonesNGemsState::ChanceOutcomes(), open_spiel::tiny_hanabi::TinyHanabiState::ChanceOutcomes(), open_spiel::trade_comm::TradeCommState::ChanceOutcomes(), define_julia_module(), open_spiel::backgammon::BackgammonState::DoApplyAction(), open_spiel::bargaining::BargainingState::DoApplyAction(), open_spiel::blackjack::BlackjackState::DoApplyAction(), open_spiel::colored_trails::ColoredTrailsState::DoApplyAction(), open_spiel::coop_to_1p::CoopTo1pState::DoApplyAction(), open_spiel::efg_game::EFGState::DoApplyAction(), open_spiel::goofspiel::GoofspielState::DoApplyAction(), open_spiel::hanabi::OpenSpielHanabiState::DoApplyAction(), open_spiel::laser_tag::LaserTagState::DoApplyAction(), open_spiel::leduc_poker::LeducState::DoApplyAction(), open_spiel::lewis_signaling::LewisSignalingState::DoApplyAction(), open_spiel::liars_dice::LiarsDiceState::DoApplyAction(), open_spiel::maedn::MaednState::DoApplyAction(), open_spiel::markov_soccer::MarkovSoccerState::DoApplyAction(), open_spiel::negotiation::NegotiationState::DoApplyAction(), open_spiel::pathfinding::PathfindingState::DoApplyAction(), open_spiel::pig::PigState::DoApplyAction(), open_spiel::trade_comm::TradeCommState::DoApplyAction(), open_spiel::twenty_forty_eight::TwentyFortyEightState::DoApplyAction(), open_spiel::goofspiel::GoofspielState::DoApplyActions(), GetType(), open_spiel::algorithms::AFCEState::InformationStateString(), open_spiel::algorithms::CEState::InformationStateString(), open_spiel::algorithms::EFCEState::InformationStateString(), open_spiel::bargaining::BargainingState::InformationStateString(), open_spiel::bargaining::BargainingState::InformationStateTensor(), open_spiel::colored_trails::ColoredTrailsState::InformationStateTensor(), open_spiel::algorithms::AFCCEState::LegalActions(), open_spiel::algorithms::AFCEState::LegalActions(), open_spiel::algorithms::CCEState::LegalActions(), open_spiel::algorithms::CEState::LegalActions(), open_spiel::algorithms::EFCCEState::LegalActions(), open_spiel::algorithms::EFCEState::LegalActions(), open_spiel::backgammon::BackgammonState::LegalActions(), open_spiel::bargaining::BargainingState::LegalActions(), open_spiel::blackjack::BlackjackState::LegalActions(), open_spiel::colored_trails::ColoredTrailsState::LegalActions(), open_spiel::coop_box_pushing::CoopBoxPushingState::LegalActions(), open_spiel::coordinated_mp::PenniesState::LegalActions(), open_spiel::crowd_modelling::CrowdModellingState::LegalActions(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::LegalActions(), open_spiel::garnet::GarnetState::LegalActions(), open_spiel::hanabi::OpenSpielHanabiState::LegalActions(), open_spiel::kuhn_poker::KuhnState::LegalActions(), open_spiel::laser_tag::LaserTagState::LegalActions(), open_spiel::leduc_poker::LeducState::LegalActions(), open_spiel::lewis_signaling::LewisSignalingState::LegalActions(), open_spiel::liars_dice::LiarsDiceState::LegalActions(), open_spiel::maedn::MaednState::LegalActions(), open_spiel::markov_soccer::MarkovSoccerState::LegalActions(), open_spiel::negotiation::NegotiationState::LegalActions(), open_spiel::oshi_zumo::OshiZumoState::LegalActions(), open_spiel::pathfinding::PathfindingState::LegalActions(), open_spiel::pig::PigState::LegalActions(), open_spiel::PyState::LegalActions(), open_spiel::SimMoveState::LegalActions(), LegalActions(), open_spiel::stones_and_gems::StonesNGemsState::LegalActions(), open_spiel::tiny_bridge::TinyBridgeAuctionState::LegalActions(), open_spiel::tiny_hanabi::TinyHanabiState::LegalActions(), open_spiel::trade_comm::TradeCommState::LegalActions(), open_spiel::twenty_forty_eight::TwentyFortyEightState::LegalActions(), open_spiel::bargaining::BargainingState::ObservationString(), open_spiel::lewis_signaling::LewisSignalingState::ObservationString(), open_spiel::negotiation::NegotiationState::ObservationString(), open_spiel::stones_and_gems::StonesNGemsState::ObservationString(), open_spiel::trade_comm::TradeCommState::ObservationString(), open_spiel::bargaining::BargainingState::ObservationTensor(), open_spiel::coop_to_1p::CoopTo1pState::ObservationTensor(), open_spiel::lewis_signaling::LewisSignalingState::ObservationTensor(), open_spiel::negotiation::NegotiationState::ObservationTensor(), open_spiel::stones_and_gems::StonesNGemsState::ObservationTensor(), open_spiel::trade_comm::TradeCommState::ObservationTensor(), open_spiel::add_noise::AddNoiseState::Rewards(), Rewards(), open_spiel::negotiation::NegotiationState::Serialize(), open_spiel::bargaining::BargainingState::SetInstance(), StateIsChanceNode(), open_spiel::bargaining::BargainingState::ToString(), open_spiel::colored_trails::ColoredTrailsState::ToString(), open_spiel::laser_tag::LaserTagState::ToString(), open_spiel::liars_dice::LiarsDiceState::ToString(), open_spiel::markov_soccer::MarkovSoccerState::ToString(), open_spiel::negotiation::NegotiationState::ToString(), open_spiel::stones_and_gems::StonesNGemsState::ToString(), and open_spiel::trade_comm::TradeCommState::ToString().
IsInitialState()
bool open_spiel::State::IsInitialState () const inline
Definition at line 431 of file spiel.h.
{ return history_.empty(); }
References history_.
Referenced by define_julia_module().
IsMeanFieldNode()
virtual bool open_spiel::State::IsMeanFieldNode () const inline virtual
Definition at line 378 of file spiel.h.
{
    return CurrentPlayer() == kMeanFieldPlayerId;
  }
References CurrentPlayer(), and open_spiel::kMeanFieldPlayerId.
Referenced by define_julia_module(), open_spiel::crowd_modelling::CrowdModellingState::LegalActions(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::LegalActions(), and open_spiel::garnet::GarnetState::LegalActions().
IsPlayerActing()
bool open_spiel::State::IsPlayerActing (Player player) const inline
Definition at line 393 of file spiel.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, NumPlayers());
    return CurrentPlayer() == player || IsSimultaneousNode();
  }
References CurrentPlayer(), IsSimultaneousNode(), NumPlayers(), player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsPlayerNode()
virtual bool open_spiel::State::IsPlayerNode () const inline virtual
Definition at line 383 of file spiel.h.
{ return CurrentPlayer() >= 0; }
References CurrentPlayer().
Referenced by define_julia_module(), open_spiel::crowd_modelling::CrowdModellingState::LegalActions(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::LegalActions(), and open_spiel::garnet::GarnetState::LegalActions().
IsSimultaneousNode()
bool open_spiel::State::IsSimultaneousNode () const inline
Definition at line 388 of file spiel.h.
{
    return CurrentPlayer() == kSimultaneousPlayerId;
  }
References CurrentPlayer(), and open_spiel::kSimultaneousPlayerId.
Referenced by open_spiel::SimMoveState::ApplyAction(), define_julia_module(), open_spiel::coop_box_pushing::CoopBoxPushingState::DoApplyAction(), open_spiel::goofspiel::GoofspielState::DoApplyAction(), open_spiel::laser_tag::LaserTagState::DoApplyAction(), open_spiel::markov_soccer::MarkovSoccerState::DoApplyAction(), open_spiel::pathfinding::PathfindingState::DoApplyAction(), IsPlayerActing(), open_spiel::algorithms::AFCCEState::LegalActions(), open_spiel::algorithms::AFCEState::LegalActions(), open_spiel::algorithms::CCEState::LegalActions(), open_spiel::algorithms::CEState::LegalActions(), open_spiel::algorithms::EFCCEState::LegalActions(), open_spiel::algorithms::EFCEState::LegalActions(), open_spiel::PyState::LegalActions(), and open_spiel::SimMoveState::LegalActions().
IsTerminal()
virtual bool open_spiel::State::IsTerminal () const pure virtual
Implemented in open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::blotto::BlottoState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::matching_pennies_3p::MatchingPennies3pState, open_spiel::matrix_game::MatrixState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pathfinding::PathfindingState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tensor_game::TensorState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, and open_spiel::y_game::YState.
Referenced by open_spiel::algorithms::CheckBeliefs(), open_spiel::NFGState::CurrentPlayer(), open_spiel::algorithms::DecisionNodes(), define_julia_module(), GetType(), open_spiel::NFGState::InformationStateString(), open_spiel::NFGState::InformationStateTensor(), open_spiel::SimMoveState::LegalActions(), LegalActions(), open_spiel::NFGState::ObservationString(), open_spiel::NFGState::ObservationTensor(), Rewards(), StateIsTerminal(), and open_spiel::NFGState::ToString().
LegalActions() [1/2]
virtual std::vector< Action > open_spiel::State::LegalActions () const pure virtual
Implemented in open_spiel::algorithms::AFCCEState, open_spiel::algorithms::AFCEState, open_spiel::algorithms::CCEState, open_spiel::algorithms::CEState, open_spiel::algorithms::EFCCEState, open_spiel::algorithms::EFCEState, open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::SimMoveState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, and open_spiel::y_game::YState.
Referenced by ApplyActionsWithLegalityChecks(), ApplyActionWithLegalityCheck(), LegalActions(), LegalActionsMask(), and StringToAction().
LegalActions() [2/2]
virtual std::vector< Action > open_spiel::State::LegalActions (Player player) const inline virtual
Reimplemented in open_spiel::blotto::BlottoState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::goofspiel::GoofspielState, open_spiel::laser_tag::LaserTagState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::matching_pennies_3p::MatchingPennies3pState, open_spiel::matrix_game::MatrixState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::pathfinding::PathfindingState, open_spiel::PyState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::SimMoveState, open_spiel::tensor_game::TensorState, and open_spiel::WrappedState.
Definition at line 255 of file spiel.h.
{
    if (!IsTerminal() && player == CurrentPlayer()) {
      return IsChanceNode() ? LegalChanceOutcomes() : LegalActions();
    } else {
      return {};
    }
  }
References CurrentPlayer(), IsChanceNode(), IsTerminal(), LegalActions(), LegalChanceOutcomes(), and player.
Referenced by open_spiel::algorithms::DecisionNodes(), and StateNumLegalActions().
LegalActionsMask() [1/2]
std::vector< int > open_spiel::State::LegalActionsMask () const inline
Definition at line 285 of file spiel.h.
{
    return LegalActionsMask(CurrentPlayer());
  }
References CurrentPlayer(), and LegalActionsMask().
Referenced by LegalActionsMask().
LegalActionsMask() [2/2]
std::vector< int > open_spiel::State::LegalActionsMask (Player player) const
Definition at line 387 of file spiel.cc.
{
  int length = (player == kChancePlayerId) ? game_->MaxChanceOutcomes()
                                           : num_distinct_actions_;
  std::vector<int> mask(length, 0);
  for (int action : LegalActions(player)) mask[action] = 1;
  return mask;
}
References action, game_, open_spiel::kChancePlayerId, LegalActions(), num_distinct_actions_, and player.
Referenced by StateFillLegalActionsMask().
LegalChanceOutcomes()
virtual std::vector< Action > open_spiel::State::LegalChanceOutcomes () const inline virtual
Reimplemented in open_spiel::algorithms::AFCCEState, open_spiel::algorithms::AFCEState, open_spiel::algorithms::CCEState, open_spiel::algorithms::CEState, open_spiel::algorithms::EFCCEState, open_spiel::algorithms::EFCEState, open_spiel::coop_to_1p::CoopTo1pState, and open_spiel::WrappedState.
Definition at line 622 of file spiel.h.
{
    ActionsAndProbs outcomes_with_probs = ChanceOutcomes();
    std::vector<Action> outcome_list;
    outcome_list.reserve(outcomes_with_probs.size());
    for (auto& pair : outcomes_with_probs) {
      outcome_list.push_back(pair.first);
    }
    return outcome_list;
  }
References ChanceOutcomes(), and pair.
Referenced by open_spiel::goofspiel::GoofspielState::DoApplyActions(), open_spiel::backgammon::BackgammonState::LegalActions(), open_spiel::bargaining::BargainingState::LegalActions(), open_spiel::blackjack::BlackjackState::LegalActions(), open_spiel::colored_trails::ColoredTrailsState::LegalActions(), open_spiel::crowd_modelling::CrowdModellingState::LegalActions(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::LegalActions(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::LegalActions(), open_spiel::garnet::GarnetState::LegalActions(), open_spiel::goofspiel::GoofspielState::LegalActions(), open_spiel::lewis_signaling::LewisSignalingState::LegalActions(), open_spiel::liars_dice::LiarsDiceState::LegalActions(), open_spiel::maedn::MaednState::LegalActions(), open_spiel::negotiation::NegotiationState::LegalActions(), open_spiel::pathfinding::PathfindingState::LegalActions(), open_spiel::pig::PigState::LegalActions(), open_spiel::PyState::LegalActions(), open_spiel::SimMoveState::LegalActions(), open_spiel::solitaire::SolitaireState::LegalActions(), LegalActions(), open_spiel::stones_and_gems::StonesNGemsState::LegalActions(), open_spiel::tiny_bridge::TinyBridgeAuctionState::LegalActions(), open_spiel::trade_comm::TradeCommState::LegalActions(), open_spiel::twenty_forty_eight::TwentyFortyEightState::LegalActions(), open_spiel::algorithms::AFCCEState::LegalChanceOutcomes(), open_spiel::algorithms::AFCEState::LegalChanceOutcomes(), open_spiel::algorithms::CCEState::LegalChanceOutcomes(), open_spiel::algorithms::CEState::LegalChanceOutcomes(), open_spiel::algorithms::EFCCEState::LegalChanceOutcomes(), and open_spiel::algorithms::EFCEState::LegalChanceOutcomes().
MeanFieldPopulation()
int open_spiel::State::MeanFieldPopulation () const virtual
Reimplemented in open_spiel::PyState.
Definition at line 813 of file spiel.cc.
{
  if (GetGame()->GetType().dynamics != GameType::Dynamics::kMeanField) {
    SpielFatalError(
        "MeanFieldPopulation() does not make sense for games that are not mean "
        "field games.");
  }
  return 0;
}
References GetGame(), GetType(), open_spiel::GameType::kMeanField, and open_spiel::SpielFatalError().
MoveNumber()
int open_spiel::State::MoveNumber () const inline
Definition at line 428 of file spiel.h.
{ return move_number_; }
References move_number_.
Referenced by open_spiel::sheriff::SheriffState::InformationStateString(), open_spiel::sheriff::SheriffState::InformationStateTensor(), and open_spiel::colored_trails::ColoredTrailsState::ToString().
NumDistinctActions()
int open_spiel::State::NumDistinctActions () const inline
Definition at line 596 of file spiel.h.
{ return num_distinct_actions_; }
References num_distinct_actions_.
Referenced by define_julia_module(), open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::battleship::BattleshipState::LegalActions(), and StateNumDistinctActions().
NumPlayers()
int open_spiel::State::NumPlayers () const inline
Definition at line 599 of file spiel.h.
{ return num_players_; }
References num_players_.
Referenced by open_spiel::ActionObservationHistory::ActionObservationHistory(), define_julia_module(), open_spiel::gin_rummy::GinRummyState::DoApplyAction(), open_spiel::matching_pennies_3p::MatchingPennies3pState::DoApplyActions(), open_spiel::tensor_game::TensorState::DoApplyActions(), open_spiel::PyState::InformationStateString(), open_spiel::sheriff::SheriffState::InformationStateString(), open_spiel::PyState::InformationStateTensor(), open_spiel::sheriff::SheriffState::InformationStateTensor(), open_spiel::universal_poker::UniversalPokerState::InformationStateTensor(), IsPlayerActing(), open_spiel::PyState::ObservationString(), open_spiel::PyState::ObservationTensor(), open_spiel::universal_poker::UniversalPokerState::ObservationTensor(), open_spiel::hanabi::OpenSpielHanabiState::Returns(), open_spiel::tensor_game::TensorState::Returns(), open_spiel::universal_poker::UniversalPokerState::Returns(), open_spiel::hanabi::OpenSpielHanabiState::Rewards(), open_spiel::negotiation::NegotiationState::Serialize(), and open_spiel::leduc_poker::LeducState::SetPrivateCards().
ObservationString() [1/2]
std::string open_spiel::State::ObservationString () const inline
Definition at line 543 of file spiel.h.
{
    return ObservationString(CurrentPlayer());
  }
References CurrentPlayer(), and ObservationString().
Referenced by open_spiel::gin_rummy::GinRummyState::DoApplyAction(), open_spiel::solitaire::SolitaireState::DoApplyAction(), open_spiel::gin_rummy::GinRummyState::GinRummyState(), open_spiel::lewis_signaling::LewisSignalingState::InformationStateString(), open_spiel::trade_comm::TradeCommState::InformationStateString(), and ObservationString().
ObservationString() [2/2]
virtual std::string open_spiel::State::ObservationString (Player player) const inline virtual
Reimplemented in open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::NFGState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pathfinding::PathfindingState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, and open_spiel::y_game::YState.
Definition at line 540 of file spiel.h.
{
    SpielFatalError("ObservationString is not implemented.");
  }
References open_spiel::SpielFatalError().
ObservationTensor() [1/4]
std::vector< float > open_spiel::State::ObservationTensor () const inline
Definition at line 557 of file spiel.h.
{
    return ObservationTensor(CurrentPlayer());
  }
References CurrentPlayer(), and ObservationTensor().
Referenced by open_spiel::lewis_signaling::LewisSignalingState::InformationStateTensor(), open_spiel::trade_comm::TradeCommState::InformationStateTensor(), open_spiel::skat::SkatState::ObservationString(), ObservationTensor(), ObservationTensor(), and ObservationTensor().
ObservationTensor() [2/4]
std::vector< float > open_spiel::State::ObservationTensor (Player player) const
Definition at line 770 of file spiel.cc.
{
  // We add this player check, to prevent errors if the game implementation
  // lacks that check (in particular as this function is the one used in
  // Python). This can lead to doing this check twice.
  // TODO(author2): Do we want to prevent executing this twice for games
  // that implement it?
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::vector<float> observation(game_->ObservationTensorSize());
  ObservationTensor(player, absl::MakeSpan(observation));
  return observation;
}
References game_, absl::MakeSpan(), num_players_, ObservationTensor(), player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
ObservationTensor() [3/4]
virtual void open_spiel::State::ObservationTensor (Player player, absl::Span< float > values) const inline virtual
Reimplemented in open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::blackjack::BlackjackState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::negotiation::NegotiationState, open_spiel::NFGState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pathfinding::PathfindingState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, and open_spiel::y_game::YState.
Definition at line 552 of file spiel.h.
{
    SpielFatalError("ObservationTensor unimplemented!");
  }
References open_spiel::SpielFatalError().
Referenced by StateFillObservationPlayer().
ObservationTensor() [4/4]
void open_spiel::State::ObservationTensor (Player player, std::vector< float > * values) const
Definition at line 783 of file spiel.cc.
{
  // Retained for backwards compatibility.
  values->resize(game_->ObservationTensorSize());
  ObservationTensor(player, absl::MakeSpan(*values));
}
References game_, absl::MakeSpan(), ObservationTensor(), player, and values.
operator==()
virtual bool open_spiel::State::operator== (const State & other) const inline virtual
Definition at line 318 of file spiel.h.
{
    return ToString() == other.ToString();
  }
References ToString().
PlayerReturn()
virtual double open_spiel::State::PlayerReturn (Player player) const inline virtual
Definition at line 361 of file spiel.h.
{
    auto returns = Returns();
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, returns.size());
    return returns[player];
  }
References player, Returns(), SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Referenced by define_julia_module(), and StatePlayerReturn().
PlayerReward()
virtual double open_spiel::State::PlayerReward (Player player) const inline virtual
Definition at line 353 of file spiel.h.
{
    auto rewards = Rewards();
    SPIEL_CHECK_LT(player, rewards.size());
    return rewards[player];
  }
References player, Rewards(), and SPIEL_CHECK_LT.
Referenced by define_julia_module().
ResampleFromInfostate()
virtual std::unique_ptr< State > open_spiel::State::ResampleFromInfostate (int player_id, std::function< double()> rng) const inline virtual
Reimplemented in open_spiel::bargaining::BargainingState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::hearts::HeartsState, open_spiel::kuhn_poker::KuhnState, open_spiel::leduc_poker::LeducState, open_spiel::oh_hell::OhHellState, and open_spiel::universal_poker::UniversalPokerState.
Definition at line 657 of file spiel.h.
{
    SpielFatalError("ResampleFromInfostate() not implemented.");
  }
References open_spiel::SpielFatalError().
Returns()
virtual std::vector< double > open_spiel::State::Returns () const pure virtual
Implemented in open_spiel::add_noise::AddNoiseState, open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::blotto::BlottoState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::matching_pennies_3p::MatchingPennies3pState, open_spiel::matrix_game::MatrixState, open_spiel::MisereState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pathfinding::PathfindingState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tensor_game::TensorState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, open_spiel::y_game::YState, and open_spiel::ZeroSumState.
Referenced by define_julia_module(), PlayerReturn(), Rewards(), and open_spiel::NFGState::ToString().
Rewards()
virtual std::vector< double > open_spiel::State::Rewards () const inline virtual
Reimplemented in open_spiel::add_noise::AddNoiseState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::deep_sea::DeepSeaState, open_spiel::garnet::GarnetState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::laser_tag::LaserTagState, open_spiel::MisereState, open_spiel::morpion_solitaire::MorpionState, open_spiel::pathfinding::PathfindingState, open_spiel::PyState, open_spiel::RepeatedState, open_spiel::solitaire::SolitaireState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::WrappedState, and open_spiel::ZeroSumState.
Definition at line 337 of file spiel.h.
{
    if (IsTerminal()) {
      return Returns();
    } else {
      SPIEL_CHECK_FALSE(IsChanceNode());
      return std::vector<double>(num_players_, 0.0);
    }
  }
References IsChanceNode(), IsTerminal(), num_players_, Returns(), and SPIEL_CHECK_FALSE.
Referenced by define_julia_module(), and PlayerReward().
Serialize()
std::string open_spiel::State::Serialize () const virtual
Reimplemented in open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::chess::ChessState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::garnet::GarnetState, open_spiel::negotiation::NegotiationState, open_spiel::PyState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, and open_spiel::tarok::TarokState.
Definition at line 313 of file spiel.cc.
{
  // This simple serialization doesn't work for the following games:
  // - games with sampled chance nodes, since the history doesn't give us enough
  //   information to reconstruct the state.
  // - Mean field games, since this base class does not store the history of
  //   state distributions passed in UpdateDistribution() (and it would be
  //   very expensive to do so for games with many possible states and a long
  //   time horizon).
  // If you wish to serialize states in such games, you must implement custom
  // serialization and deserialization for the state.
  SPIEL_CHECK_NE(game_->GetType().chance_mode,
                 GameType::ChanceMode::kSampledStochastic);
  SPIEL_CHECK_NE(game_->GetType().dynamics, GameType::Dynamics::kMeanField);
  return absl::StrCat(absl::StrJoin(History(), "\n"), "\n");
}
References game_, History(), open_spiel::GameType::kMeanField, open_spiel::GameType::kSampledStochastic, SPIEL_CHECK_NE, absl::StrCat(), and absl::StrJoin().
Referenced by define_julia_module(), open_spiel::bridge::BridgeState::Serialize(), and open_spiel::spades::SpadesState::Serialize().
StringToAction() [1/2]
Action open_spiel::State::StringToAction (const std::string & action_str) const inline
Definition at line 304 of file spiel.h.
{
    return StringToAction(CurrentPlayer(), action_str);
  }
References CurrentPlayer(), and StringToAction().
StringToAction() [2/2]
Action open_spiel::State::StringToAction (Player player, const std::string & action_str) const virtual
Definition at line 329 of file spiel.cc.
{
  for (const Action action : LegalActions()) {
    if (action_str == ActionToString(player, action)) return action;
  }
  SpielFatalError(
      absl::StrCat("Couldn't find an action matching ", action_str));
}
References action, ActionToString(), LegalActions(), player, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by StringToAction().
ToString()
virtual std::string open_spiel::State::ToString () const pure virtual
Implemented in open_spiel::algorithms::AFCCEState, open_spiel::algorithms::AFCEState, open_spiel::algorithms::CCEState, open_spiel::algorithms::CEState, open_spiel::algorithms::EFCCEState, open_spiel::algorithms::EFCEState, open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::bargaining::BargainingState, open_spiel::baseT::baseTState, open_spiel::battleship::BattleshipState, open_spiel::blackjack::BlackjackState, open_spiel::blotto::BlottoState, open_spiel::breakthrough::BreakthroughState, open_spiel::bridge::BridgeState, open_spiel::bridge_uncontested_bidding::UncontestedBiddingState, open_spiel::catch_::CatchState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::cliff_walking::CliffWalkingState, open_spiel::clobber::ClobberState, open_spiel::coin_game::CoinState, open_spiel::colored_trails::ColoredTrailsState, open_spiel::connect_four::ConnectFourState, open_spiel::coop_box_pushing::CoopBoxPushingState, open_spiel::coop_to_1p::CoopTo1pState, open_spiel::coordinated_mp::PenniesState, open_spiel::crazy_eights::CrazyEightsState, open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::cursor_go::CursorGoState, open_spiel::dark_chess::DarkChessState, open_spiel::dark_hex::DarkHexState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::dou_dizhu::DouDizhuState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::efg_game::EFGState, open_spiel::euchre::EuchreState, open_spiel::first_sealed_auction::FPSBAState, open_spiel::garnet::GarnetState, open_spiel::gin_rummy::GinRummyState, open_spiel::go::GoState, open_spiel::goofspiel::GoofspielState, open_spiel::hanabi::OpenSpielHanabiState, open_spiel::havannah::HavannahState, open_spiel::hearts::HeartsState, open_spiel::hex::HexState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::laser_tag::LaserTagState, open_spiel::leduc_poker::LeducState, open_spiel::lewis_signaling::LewisSignalingState, open_spiel::liars_dice::LiarsDiceState, open_spiel::maedn::MaednState, open_spiel::mancala::MancalaState, open_spiel::markov_soccer::MarkovSoccerState, open_spiel::matrix_game::MatrixState, open_spiel::morpion_solitaire::MorpionState, open_spiel::negotiation::NegotiationState, open_spiel::NFGState, open_spiel::nim::NimState, open_spiel::nine_mens_morris::NineMensMorrisState, open_spiel::oh_hell::OhHellState, open_spiel::oshi_zumo::OshiZumoState, open_spiel::othello::OthelloState, open_spiel::oware::OwareState, open_spiel::pathfinding::PathfindingState, open_spiel::pentago::PentagoState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::pig::PigState, open_spiel::PyState, open_spiel::quoridor::QuoridorState, open_spiel::rbc::RbcState, open_spiel::RepeatedState, open_spiel::RestrictedNashResponseState, open_spiel::sheriff::SheriffState, open_spiel::skat::SkatState, open_spiel::solitaire::SolitaireState, open_spiel::spades::SpadesState, open_spiel::stones_and_gems::StonesNGemsState, open_spiel::tarok::TarokState, open_spiel::tensor_game::TensorState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::tiny_hanabi::TinyHanabiState, open_spiel::trade_comm::TradeCommState, open_spiel::TurnBasedSimultaneousState, open_spiel::twenty_forty_eight::TwentyFortyEightState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, open_spiel::universal_poker::UniversalPokerState, open_spiel::WrappedState, and open_spiel::y_game::YState.
Referenced by define_julia_module(), operator==(), and StateToString().
UndoAction()
virtual void open_spiel::State::UndoAction (Player player, Action action) inline virtual
Reimplemented in open_spiel::amazons::AmazonsState, open_spiel::backgammon::BackgammonState, open_spiel::battleship::BattleshipState, open_spiel::breakthrough::BreakthroughState, open_spiel::checkers::CheckersState, open_spiel::chess::ChessState, open_spiel::clobber::ClobberState, open_spiel::dark_chess::DarkChessState, open_spiel::deep_sea::DeepSeaState, open_spiel::dots_and_boxes::DotsAndBoxesState, open_spiel::efg_game::EFGState, open_spiel::go::GoState, open_spiel::kriegspiel::KriegspielState, open_spiel::kuhn_poker::KuhnState, open_spiel::maedn::MaednState, open_spiel::morpion_solitaire::MorpionState, open_spiel::nim::NimState, open_spiel::phantom_go::PhantomGoState, open_spiel::phantom_ttt::PhantomTTTState, open_spiel::rbc::RbcState, open_spiel::sheriff::SheriffState, open_spiel::tic_tac_toe::TicTacToeState, open_spiel::tiny_bridge::TinyBridgeAuctionState, open_spiel::tiny_bridge::TinyBridgePlayState, open_spiel::twixt::TwixTState, open_spiel::ultimate_tic_tac_toe::UltimateTTTState, and open_spiel::WrappedState.
Definition at line 577 of file spiel.h.
{
    SpielFatalError("UndoAction function is not overridden; not undoing.");
  }
References open_spiel::SpielFatalError().
Referenced by define_julia_module().
UpdateDistribution()
virtual void open_spiel::State::UpdateDistribution (const std::vector< double > & distribution) inline virtual
Reimplemented in open_spiel::crowd_modelling::CrowdModellingState, open_spiel::crowd_modelling_2d::CrowdModelling2dState, open_spiel::dynamic_routing::MeanFieldRoutingGameState, open_spiel::garnet::GarnetState, and open_spiel::PyState.
Definition at line 707 of file spiel.h.
{
    SpielFatalError("UpdateDistribution has not been implemented");
  }
References open_spiel::SpielFatalError().
Member Data Documentation
game_
const std::shared_ptr<const Game> open_spiel::State::game_ protected
Definition at line 728 of file spiel.h.
Referenced by open_spiel::blotto::BlottoState::ActionToString(), open_spiel::laser_tag::LaserTagState::ActionToString(), open_spiel::markov_soccer::MarkovSoccerState::ActionToString(), open_spiel::nine_mens_morris::NineMensMorrisState::ActionToString(), open_spiel::tic_tac_toe::TicTacToeState::ActionToString(), open_spiel::blackjack::BlackjackState::BlackjackState(), open_spiel::PyState::Clone(), open_spiel::blackjack::BlackjackState::DealerId(), open_spiel::liars_dice::LiarsDiceState::dice_sides(), open_spiel::algorithms::AFCCEState::DoApplyAction(), open_spiel::algorithms::AFCEState::DoApplyAction(), open_spiel::algorithms::EFCCEState::DoApplyAction(), open_spiel::algorithms::EFCEState::DoApplyAction(), open_spiel::efg_game::EFGState::DoApplyAction(), open_spiel::laser_tag::LaserTagState::DoApplyAction(), open_spiel::markov_soccer::MarkovSoccerState::DoApplyAction(), open_spiel::RestrictedNashResponseState::DoApplyActions(), open_spiel::rbc::RbcState::game(), GetGame(), open_spiel::universal_poker::UniversalPokerState::GetHistoriesConsistentWithInfostate(), open_spiel::algorithms::AFCCEState::HasDefected(), open_spiel::algorithms::AFCEState::HasDefected(), open_spiel::algorithms::EFCCEState::HasDefected(), open_spiel::algorithms::EFCEState::HasDefected(), open_spiel::algorithms::CEState::InformationStateString(), open_spiel::coordinated_mp::PenniesState::InformationStateString(), open_spiel::gin_rummy::GinRummyState::InformationStateString(), open_spiel::goofspiel::GoofspielState::InformationStateString(), open_spiel::kuhn_poker::KuhnState::InformationStateString(), open_spiel::leduc_poker::LeducState::InformationStateString(), open_spiel::liars_dice::ImperfectRecallLiarsDiceState::InformationStateString(), open_spiel::PyState::InformationStateString(), open_spiel::RestrictedNashResponseState::InformationStateString(), open_spiel::bargaining::BargainingState::InformationStateTensor(), open_spiel::colored_trails::ColoredTrailsState::InformationStateTensor(), open_spiel::efg_game::EFGState::InformationStateTensor(), open_spiel::goofspiel::GoofspielState::InformationStateTensor(), open_spiel::kuhn_poker::KuhnState::InformationStateTensor(), open_spiel::leduc_poker::LeducState::InformationStateTensor(), open_spiel::oh_hell::OhHellState::InformationStateTensor(), open_spiel::PyState::InformationStateTensor(), open_spiel::RepeatedState::InformationStateTensor(), open_spiel::RestrictedNashResponseState::InformationStateTensor(), open_spiel::sheriff::SheriffState::InformationStateTensor(), InformationStateTensor(), InformationStateTensor(), open_spiel::TurnBasedSimultaneousState::InformationStateTensor(), open_spiel::universal_poker::UniversalPokerState::InformationStateTensor(), open_spiel::backgammon::BackgammonState::IsTerminal(), open_spiel::mancala::MancalaState::IsTerminal(), open_spiel::laser_tag::LaserTagState::LaserTagState(), open_spiel::backgammon::BackgammonState::LegalActions(), LegalActionsMask(), open_spiel::blackjack::BlackjackState::ObservationString(), open_spiel::coordinated_mp::PenniesState::ObservationString(), open_spiel::dark_chess::DarkChessState::ObservationString(), open_spiel::gin_rummy::GinRummyState::ObservationString(), open_spiel::goofspiel::GoofspielState::ObservationString(), open_spiel::kriegspiel::KriegspielState::ObservationString(), open_spiel::kuhn_poker::KuhnState::ObservationString(), open_spiel::leduc_poker::LeducState::ObservationString(), open_spiel::PyState::ObservationString(), open_spiel::rbc::RbcState::ObservationString(), open_spiel::RestrictedNashResponseState::ObservationString(), open_spiel::skat::SkatState::ObservationString(), open_spiel::bargaining::BargainingState::ObservationTensor(), open_spiel::blackjack::BlackjackState::ObservationTensor(), open_spiel::bridge::BridgeState::ObservationTensor(), open_spiel::crazy_eights::CrazyEightsState::ObservationTensor(), open_spiel::dark_chess::DarkChessState::ObservationTensor(), open_spiel::dark_hex::DarkHexState::ObservationTensor(), open_spiel::dou_dizhu::DouDizhuState::ObservationTensor(), open_spiel::gin_rummy::GinRummyState::ObservationTensor(), open_spiel::goofspiel::GoofspielState::ObservationTensor(), open_spiel::kriegspiel::KriegspielState::ObservationTensor(), open_spiel::kuhn_poker::KuhnState::ObservationTensor(), open_spiel::leduc_poker::LeducState::ObservationTensor(), open_spiel::lewis_signaling::LewisSignalingState::ObservationTensor(), open_spiel::phantom_go::PhantomGoState::ObservationTensor(), open_spiel::phantom_ttt::PhantomTTTState::ObservationTensor(), open_spiel::PyState::ObservationTensor(), open_spiel::rbc::RbcState::ObservationTensor(), open_spiel::RepeatedState::ObservationTensor(), open_spiel::RestrictedNashResponseState::ObservationTensor(), open_spiel::skat::SkatState::ObservationTensor(), open_spiel::solitaire::SolitaireState::ObservationTensor(), open_spiel::spades::SpadesState::ObservationTensor(), ObservationTensor(), ObservationTensor(), open_spiel::trade_comm::TradeCommState::ObservationTensor(), open_spiel::TurnBasedSimultaneousState::ObservationTensor(), open_spiel::universal_poker::UniversalPokerState::ObservationTensor(), open_spiel::leduc_poker::LeducState::padded_betting_sequence(), open_spiel::hearts::HeartsState::ResampleFromInfostate(), open_spiel::kuhn_poker::KuhnState::ResampleFromInfostate(), open_spiel::leduc_poker::LeducState::ResampleFromInfostate(), open_spiel::oh_hell::OhHellState::ResampleFromInfostate(), open_spiel::add_noise::AddNoiseState::Returns(), Serialize(), open_spiel::backgammon::BackgammonState::SetState(), and open_spiel::StartAtTransformationState::StartAtTransformationState().
history_
std::vector<PlayerAction> open_spiel::State::history_ protected
Definition at line 733 of file spiel.h.
Referenced by open_spiel::euchre::EuchreState::ActionToString(), open_spiel::hearts::HeartsState::ActionToString(), open_spiel::SimMoveState::ApplyAction(), ApplyAction(), ApplyActions(), open_spiel::bridge::BridgeState::ChanceOutcomes(), open_spiel::crazy_eights::CrazyEightsState::ChanceOutcomes(), open_spiel::euchre::EuchreState::ChanceOutcomes(), open_spiel::hearts::HeartsState::ChanceOutcomes(), open_spiel::kuhn_poker::KuhnState::ChanceOutcomes(), open_spiel::skat::SkatState::ChanceOutcomes(), open_spiel::spades::SpadesState::ChanceOutcomes(), open_spiel::PyState::Clone(), open_spiel::kuhn_poker::KuhnState::CurrentPlayer(), open_spiel::tiny_hanabi::TinyHanabiState::CurrentPlayer(), open_spiel::PyState::Deserialize(), open_spiel::kuhn_poker::KuhnState::DoApplyAction(), open_spiel::oware::OwareState::DoApplyAction(), FullHistory(), History(), open_spiel::dark_hex::DarkHexState::InformationStateString(), open_spiel::phantom_ttt::PhantomTTTState::InformationStateString(), open_spiel::tiny_hanabi::TinyHanabiState::InformationStateString(), open_spiel::cliff_walking::CliffWalkingState::InformationStateTensor(), open_spiel::oh_hell::OhHellState::InformationStateTensor(), open_spiel::tiny_hanabi::TinyHanabiState::InformationStateTensor(), IsInitialState(), open_spiel::go::GoState::IsTerminal(), open_spiel::lewis_signaling::LewisSignalingState::IsTerminal(), open_spiel::phantom_go::PhantomGoState::IsTerminal(), open_spiel::tiny_hanabi::TinyHanabiState::IsTerminal(), open_spiel::bridge::BridgeState::ObservationString(), open_spiel::spades::SpadesState::ObservationString(), open_spiel::bridge::BridgeState::PublicObservationTensor(), open_spiel::hearts::HeartsState::ResampleFromInfostate(), open_spiel::kuhn_poker::KuhnState::ResampleFromInfostate(), open_spiel::leduc_poker::LeducState::ResampleFromInfostate(), open_spiel::oh_hell::OhHellState::ResampleFromInfostate(), open_spiel::tiny_hanabi::TinyHanabiState::Returns(), open_spiel::PyState::Serialize(), open_spiel::bridge::BridgeState::ToString(), open_spiel::crazy_eights::CrazyEightsState::ToString(), open_spiel::cursor_go::CursorGoState::ToString(), open_spiel::dou_dizhu::DouDizhuState::ToString(), open_spiel::euchre::EuchreState::ToString(), open_spiel::go::GoState::ToString(), open_spiel::kuhn_poker::KuhnState::ToString(), open_spiel::lewis_signaling::LewisSignalingState::ToString(), open_spiel::phantom_go::PhantomGoState::ToString(), open_spiel::spades::SpadesState::ToString(), open_spiel::tiny_hanabi::TinyHanabiState::ToString(), open_spiel::amazons::AmazonsState::UndoAction(), open_spiel::backgammon::BackgammonState::UndoAction(), open_spiel::breakthrough::BreakthroughState::UndoAction(), open_spiel::checkers::CheckersState::UndoAction(), open_spiel::chess::ChessState::UndoAction(), open_spiel::clobber::ClobberState::UndoAction(), open_spiel::dark_chess::DarkChessState::UndoAction(), open_spiel::deep_sea::DeepSeaState::UndoAction(), open_spiel::dots_and_boxes::DotsAndBoxesState::UndoAction(), open_spiel::go::GoState::UndoAction(), open_spiel::kriegspiel::KriegspielState::UndoAction(), open_spiel::kuhn_poker::KuhnState::UndoAction(), open_spiel::maedn::MaednState::UndoAction(), open_spiel::morpion_solitaire::MorpionState::UndoAction(), open_spiel::nim::NimState::UndoAction(), open_spiel::phantom_go::PhantomGoState::UndoAction(), open_spiel::phantom_ttt::PhantomTTTState::UndoAction(), open_spiel::rbc::RbcState::UndoAction(), open_spiel::sheriff::SheriffState::UndoAction(), open_spiel::tic_tac_toe::TicTacToeState::UndoAction(), open_spiel::tiny_bridge::TinyBridgeAuctionState::UndoAction(), open_spiel::tiny_bridge::TinyBridgePlayState::UndoAction(), open_spiel::WrappedState::UndoAction(), open_spiel::bridge::BridgeState::WriteObservationTensor(), and open_spiel::spades::SpadesState::WriteObservationTensor().
move_number_
int open_spiel::State::move_number_ protected
Definition at line 734 of file spiel.h.
Referenced by ApplyAction(), ApplyActions(), open_spiel::bargaining::BargainingState::ChanceOutcomes(), open_spiel::PyState::Clone(), open_spiel::PyState::Deserialize(), open_spiel::bargaining::BargainingState::DoApplyAction(), open_spiel::mancala::MancalaState::IsTerminal(), open_spiel::twenty_forty_eight::TwentyFortyEightState::IsTerminal(), MoveNumber(), open_spiel::morpion_solitaire::MorpionState::Rewards(), open_spiel::PyState::Serialize(), open_spiel::amazons::AmazonsState::UndoAction(), open_spiel::backgammon::BackgammonState::UndoAction(), open_spiel::breakthrough::BreakthroughState::UndoAction(), open_spiel::checkers::CheckersState::UndoAction(), open_spiel::chess::ChessState::UndoAction(), open_spiel::dark_chess::DarkChessState::UndoAction(), open_spiel::deep_sea::DeepSeaState::UndoAction(), open_spiel::dots_and_boxes::DotsAndBoxesState::UndoAction(), open_spiel::go::GoState::UndoAction(), open_spiel::kuhn_poker::KuhnState::UndoAction(), open_spiel::maedn::MaednState::UndoAction(), open_spiel::morpion_solitaire::MorpionState::UndoAction(), open_spiel::nim::NimState::UndoAction(), open_spiel::phantom_go::PhantomGoState::UndoAction(), open_spiel::phantom_ttt::PhantomTTTState::UndoAction(), open_spiel::rbc::RbcState::UndoAction(), open_spiel::sheriff::SheriffState::UndoAction(), open_spiel::tic_tac_toe::TicTacToeState::UndoAction(), open_spiel::tiny_bridge::TinyBridgeAuctionState::UndoAction(), and open_spiel::tiny_bridge::TinyBridgePlayState::UndoAction().
num_distinct_actions_
const int open_spiel::State::num_distinct_actions_ protected
Definition at line 729 of file spiel.h.
Referenced by open_spiel::colored_trails::ColoredTrailsState::ActionToString(), LegalActionsMask(), and NumDistinctActions().
num_players_
const int open_spiel::State::num_players_ protected
Definition at line 730 of file spiel.h.
Referenced by open_spiel::first_sealed_auction::FPSBAState::ActionToString(), open_spiel::tiny_bridge::TinyBridgeAuctionState::AuctionString(), open_spiel::tarok::TarokState::CapturedMondPenalties(), open_spiel::baseT::baseTState::cells_to_obs(), open_spiel::first_sealed_auction::FPSBAState::ChanceOutcomes(), open_spiel::kuhn_poker::KuhnState::ChanceOutcomes(), open_spiel::efg_game::EFGState::CurrentPlayer(), open_spiel::first_sealed_auction::FPSBAState::CurrentPlayer(), open_spiel::kuhn_poker::KuhnState::CurrentPlayer(), open_spiel::tiny_bridge::TinyBridgeAuctionState::CurrentPlayer(), open_spiel::tiny_hanabi::TinyHanabiState::CurrentPlayer(), open_spiel::tiny_bridge::TinyBridgeAuctionState::DealString(), open_spiel::baseT::baseTState::deploy_unit(), open_spiel::first_sealed_auction::FPSBAState::DoApplyAction(), open_spiel::kuhn_poker::KuhnState::DoApplyAction(), open_spiel::leduc_poker::LeducState::DoApplyAction(), open_spiel::liars_dice::LiarsDiceState::DoApplyAction(), open_spiel::maedn::MaednState::DoApplyAction(), open_spiel::pig::PigState::DoApplyAction(), open_spiel::quoridor::QuoridorState::DoApplyAction(), open_spiel::tiny_bridge::TinyBridgeAuctionState::DoApplyAction(), open_spiel::trade_comm::TradeCommState::DoApplyAction(), open_spiel::TurnBasedSimultaneousState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::blotto::BlottoState::DoApplyActions(), open_spiel::goofspiel::GoofspielState::DoApplyActions(), open_spiel::pathfinding::PathfindingState::DoApplyActions(), open_spiel::RepeatedState::DoApplyActions(), open_spiel::SimMoveState::FlatJointActionToActions(), open_spiel::SimMoveState::FlatJointActionToString(), open_spiel::maedn::MaednState::FromObservationTensor(), open_spiel::amazons::AmazonsState::InformationStateString(), open_spiel::bargaining::BargainingState::InformationStateString(), open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::InformationStateString(), open_spiel::checkers::CheckersState::InformationStateString(), open_spiel::chess::ChessState::InformationStateString(), open_spiel::cliff_walking::CliffWalkingState::InformationStateString(), open_spiel::clobber::ClobberState::InformationStateString(), open_spiel::colored_trails::ColoredTrailsState::InformationStateString(), open_spiel::connect_four::ConnectFourState::InformationStateString(), open_spiel::crowd_modelling::CrowdModellingState::InformationStateString(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::InformationStateString(), open_spiel::cursor_go::CursorGoState::InformationStateString(), open_spiel::dark_hex::DarkHexState::InformationStateString(), open_spiel::dark_hex::ImperfectRecallDarkHexState::InformationStateString(), open_spiel::dots_and_boxes::DotsAndBoxesState::InformationStateString(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::InformationStateString(), open_spiel::efg_game::EFGState::InformationStateString(), open_spiel::first_sealed_auction::FPSBAState::InformationStateString(), open_spiel::garnet::GarnetState::InformationStateString(), open_spiel::go::GoState::InformationStateString(), open_spiel::havannah::HavannahState::InformationStateString(), open_spiel::hearts::HeartsState::InformationStateString(), open_spiel::hex::HexState::InformationStateString(), open_spiel::liars_dice::ImperfectRecallLiarsDiceState::InformationStateString(), open_spiel::liars_dice::LiarsDiceState::InformationStateString(), open_spiel::morpion_solitaire::MorpionState::InformationStateString(), open_spiel::NFGState::InformationStateString(), open_spiel::nim::NimState::InformationStateString(), open_spiel::nine_mens_morris::NineMensMorrisState::InformationStateString(), open_spiel::oshi_zumo::OshiZumoState::InformationStateString(), open_spiel::othello::OthelloState::InformationStateString(), open_spiel::pentago::PentagoState::InformationStateString(), open_spiel::phantom_ttt::ImperfectRecallPTTTState::InformationStateString(), open_spiel::phantom_ttt::PhantomTTTState::InformationStateString(), open_spiel::quoridor::QuoridorState::InformationStateString(), open_spiel::RepeatedState::InformationStateString(), open_spiel::solitaire::SolitaireState::InformationStateString(), open_spiel::tarok::TarokState::InformationStateString(), open_spiel::tic_tac_toe::TicTacToeState::InformationStateString(), open_spiel::tiny_bridge::TinyBridgeAuctionState::InformationStateString(), open_spiel::tiny_hanabi::TinyHanabiState::InformationStateString(), open_spiel::TurnBasedSimultaneousState::InformationStateString(), open_spiel::twenty_forty_eight::TwentyFortyEightState::InformationStateString(), open_spiel::ultimate_tic_tac_toe::UltimateTTTState::InformationStateString(), open_spiel::y_game::YState::InformationStateString(), open_spiel::bargaining::BargainingState::InformationStateTensor(), open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::InformationStateTensor(), open_spiel::cliff_walking::CliffWalkingState::InformationStateTensor(), open_spiel::colored_trails::ColoredTrailsState::InformationStateTensor(), open_spiel::dark_hex::DarkHexState::InformationStateTensor(), open_spiel::efg_game::EFGState::InformationStateTensor(), open_spiel::euchre::EuchreState::InformationStateTensor(), open_spiel::first_sealed_auction::FPSBAState::InformationStateTensor(), open_spiel::hearts::HeartsState::InformationStateTensor(), open_spiel::liars_dice::LiarsDiceState::InformationStateTensor(), open_spiel::NFGState::InformationStateTensor(), open_spiel::phantom_ttt::PhantomTTTState::InformationStateTensor(), open_spiel::RepeatedState::InformationStateTensor(), InformationStateTensor(), open_spiel::tiny_bridge::TinyBridgeAuctionState::InformationStateTensor(), open_spiel::tiny_hanabi::TinyHanabiState::InformationStateTensor(), open_spiel::TurnBasedSimultaneousState::InformationStateTensor(), open_spiel::universal_poker::UniversalPokerState::InformationStateTensor(), open_spiel::baseT::baseTState::init_first(), open_spiel::kbg::kbgState::init_map(), open_spiel::kbg::kbgState::init_unit(), open_spiel::maedn::MaednState::IsTerminal(), open_spiel::pig::PigState::IsTerminal(), open_spiel::tiny_hanabi::TinyHanabiState::IsTerminal(), open_spiel::first_sealed_auction::FPSBAState::LegalActions(), open_spiel::goofspiel::GoofspielState::LegalActions(), open_spiel::quoridor::QuoridorState::LegalActions(), open_spiel::tiny_bridge::TinyBridgeAuctionState::LegalActions(), open_spiel::quoridor::QuoridorState::NumCellStates(), NumPlayers(), open_spiel::amazons::AmazonsState::ObservationString(), open_spiel::backgammon::BackgammonState::ObservationString(), open_spiel::bargaining::BargainingState::ObservationString(), open_spiel::breakthrough::BreakthroughState::ObservationString(), open_spiel::bridge::BridgeState::ObservationString(), open_spiel::catch_::CatchState::ObservationString(), open_spiel::checkers::CheckersState::ObservationString(), open_spiel::chess::ChessState::ObservationString(), open_spiel::cliff_walking::CliffWalkingState::ObservationString(), open_spiel::clobber::ClobberState::ObservationString(), open_spiel::coin_game::CoinState::ObservationString(), open_spiel::connect_four::ConnectFourState::ObservationString(), open_spiel::coop_box_pushing::CoopBoxPushingState::ObservationString(), open_spiel::coop_to_1p::CoopTo1pState::ObservationString(), open_spiel::crowd_modelling::CrowdModellingState::ObservationString(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::ObservationString(), open_spiel::cursor_go::CursorGoState::ObservationString(), open_spiel::dark_hex::DarkHexState::ObservationString(), open_spiel::deep_sea::DeepSeaState::ObservationString(), open_spiel::dots_and_boxes::DotsAndBoxesState::ObservationString(), open_spiel::dou_dizhu::DouDizhuState::ObservationString(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::ObservationString(), open_spiel::efg_game::EFGState::ObservationString(), open_spiel::first_sealed_auction::FPSBAState::ObservationString(), open_spiel::garnet::GarnetState::ObservationString(), open_spiel::go::GoState::ObservationString(), open_spiel::hanabi::OpenSpielHanabiState::ObservationString(), open_spiel::havannah::HavannahState::ObservationString(), open_spiel::hex::HexState::ObservationString(), open_spiel::laser_tag::LaserTagState::ObservationString(), open_spiel::lewis_signaling::LewisSignalingState::ObservationString(), open_spiel::maedn::MaednState::ObservationString(), open_spiel::mancala::MancalaState::ObservationString(), open_spiel::markov_soccer::MarkovSoccerState::ObservationString(), open_spiel::morpion_solitaire::MorpionState::ObservationString(), open_spiel::negotiation::NegotiationState::ObservationString(), open_spiel::NFGState::ObservationString(), open_spiel::nim::NimState::ObservationString(), open_spiel::nine_mens_morris::NineMensMorrisState::ObservationString(), open_spiel::oshi_zumo::OshiZumoState::ObservationString(), open_spiel::othello::OthelloState::ObservationString(), open_spiel::oware::OwareState::ObservationString(), open_spiel::pathfinding::PathfindingState::ObservationString(), open_spiel::pentago::PentagoState::ObservationString(), open_spiel::phantom_go::PhantomGoState::ObservationString(), open_spiel::phantom_ttt::PhantomTTTState::ObservationString(), open_spiel::pig::PigState::ObservationString(), open_spiel::quoridor::QuoridorState::ObservationString(), open_spiel::RepeatedState::ObservationString(), open_spiel::skat::SkatState::ObservationString(), open_spiel::solitaire::SolitaireState::ObservationString(), open_spiel::spades::SpadesState::ObservationString(), open_spiel::stones_and_gems::StonesNGemsState::ObservationString(), open_spiel::tic_tac_toe::TicTacToeState::ObservationString(), open_spiel::tiny_bridge::TinyBridgeAuctionState::ObservationString(), open_spiel::tiny_hanabi::TinyHanabiState::ObservationString(), open_spiel::trade_comm::TradeCommState::ObservationString(), open_spiel::TurnBasedSimultaneousState::ObservationString(), open_spiel::twenty_forty_eight::TwentyFortyEightState::ObservationString(), open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ObservationString(), open_spiel::universal_poker::UniversalPokerState::ObservationString(), open_spiel::y_game::YState::ObservationString(), open_spiel::amazons::AmazonsState::ObservationTensor(), open_spiel::backgammon::BackgammonState::ObservationTensor(), open_spiel::bargaining::BargainingState::ObservationTensor(), open_spiel::breakthrough::BreakthroughState::ObservationTensor(), open_spiel::catch_::CatchState::ObservationTensor(), open_spiel::checkers::CheckersState::ObservationTensor(), open_spiel::chess::ChessState::ObservationTensor(), open_spiel::cliff_walking::CliffWalkingState::ObservationTensor(), open_spiel::clobber::ClobberState::ObservationTensor(), open_spiel::connect_four::ConnectFourState::ObservationTensor(), open_spiel::coop_box_pushing::CoopBoxPushingState::ObservationTensor(), open_spiel::coop_to_1p::CoopTo1pState::ObservationTensor(), open_spiel::crowd_modelling::CrowdModellingState::ObservationTensor(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::ObservationTensor(), open_spiel::cursor_go::CursorGoState::ObservationTensor(), open_spiel::dark_hex::DarkHexState::ObservationTensor(), open_spiel::deep_sea::DeepSeaState::ObservationTensor(), open_spiel::dots_and_boxes::DotsAndBoxesState::ObservationTensor(), open_spiel::first_sealed_auction::FPSBAState::ObservationTensor(), open_spiel::garnet::GarnetState::ObservationTensor(), open_spiel::go::GoState::ObservationTensor(), open_spiel::hanabi::OpenSpielHanabiState::ObservationTensor(), open_spiel::havannah::HavannahState::ObservationTensor(), open_spiel::hex::HexState::ObservationTensor(), open_spiel::laser_tag::LaserTagState::ObservationTensor(), open_spiel::lewis_signaling::LewisSignalingState::ObservationTensor(), open_spiel::liars_dice::LiarsDiceState::ObservationTensor(), open_spiel::maedn::MaednState::ObservationTensor(), open_spiel::mancala::MancalaState::ObservationTensor(), open_spiel::markov_soccer::MarkovSoccerState::ObservationTensor(), open_spiel::negotiation::NegotiationState::ObservationTensor(), open_spiel::NFGState::ObservationTensor(), open_spiel::nim::NimState::ObservationTensor(), open_spiel::nine_mens_morris::NineMensMorrisState::ObservationTensor(), open_spiel::oshi_zumo::OshiZumoState::ObservationTensor(), open_spiel::othello::OthelloState::ObservationTensor(), open_spiel::oware::OwareState::ObservationTensor(), open_spiel::pathfinding::PathfindingState::ObservationTensor(), open_spiel::pentago::PentagoState::ObservationTensor(), open_spiel::phantom_ttt::PhantomTTTState::ObservationTensor(), open_spiel::pig::PigState::ObservationTensor(), open_spiel::quoridor::QuoridorState::ObservationTensor(), open_spiel::RepeatedState::ObservationTensor(), open_spiel::skat::SkatState::ObservationTensor(), open_spiel::solitaire::SolitaireState::ObservationTensor(), ObservationTensor(), open_spiel::stones_and_gems::StonesNGemsState::ObservationTensor(), open_spiel::tic_tac_toe::TicTacToeState::ObservationTensor(), open_spiel::tiny_bridge::TinyBridgeAuctionState::ObservationTensor(), open_spiel::tiny_hanabi::TinyHanabiState::ObservationTensor(), open_spiel::trade_comm::TradeCommState::ObservationTensor(), open_spiel::TurnBasedSimultaneousState::ObservationTensor(), open_spiel::twenty_forty_eight::TwentyFortyEightState::ObservationTensor(), open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ObservationTensor(), open_spiel::y_game::YState::ObservationTensor(), open_spiel::pathfinding::PathfindingState::PathfindingState(), open_spiel::pathfinding::PathfindingState::PlayerAtPos(), open_spiel::quoridor::QuoridorState::QuoridorState(), open_spiel::bargaining::BargainingState::Returns(), open_spiel::blotto::BlottoState::Returns(), open_spiel::coin_game::CoinState::Returns(), open_spiel::efg_game::EFGState::Returns(), open_spiel::first_sealed_auction::FPSBAState::Returns(), open_spiel::goofspiel::GoofspielState::Returns(), open_spiel::kuhn_poker::KuhnState::Returns(), open_spiel::leduc_poker::LeducState::Returns(), open_spiel::liars_dice::LiarsDiceState::Returns(), open_spiel::maedn::MaednState::Returns(), open_spiel::negotiation::NegotiationState::Returns(), open_spiel::pig::PigState::Returns(), open_spiel::quoridor::QuoridorState::Returns(), open_spiel::RepeatedState::Returns(), open_spiel::RestrictedNashResponseState::Returns(), open_spiel::tarok::TarokState::Returns(), open_spiel::tiny_bridge::TinyBridgeAuctionState::Returns(), open_spiel::tiny_bridge::TinyBridgePlayState::Returns(), open_spiel::add_noise::AddNoiseState::Rewards(), open_spiel::RepeatedState::Rewards(), Rewards(), open_spiel::TurnBasedSimultaneousState::Rewards(), open_spiel::tarok::TarokState::ScoresWithoutCapturedMondPenalties(), open_spiel::baseT::baseTState::set_cell_and_obs(), open_spiel::baseT::baseTState::SetNextPlayer(), open_spiel::tarok::TarokState::TarokState(), open_spiel::colored_trails::ColoredTrailsState::ToString(), open_spiel::goofspiel::GoofspielState::ToString(), open_spiel::kuhn_poker::KuhnState::ToString(), open_spiel::leduc_poker::LeducState::ToString(), open_spiel::liars_dice::LiarsDiceState::ToString(), open_spiel::negotiation::NegotiationState::ToString(), open_spiel::pathfinding::PathfindingState::ToString(), open_spiel::quoridor::QuoridorState::ToString(), open_spiel::RepeatedState::ToString(), open_spiel::kuhn_poker::KuhnState::UndoAction(), open_spiel::bridge::BridgeState::WriteObservationTensor(), open_spiel::dou_dizhu::DouDizhuState::WriteObservationTensor(), and open_spiel::spades::SpadesState::WriteObservationTensor().
The documentation for this class was generated from the following files:
open_spiel/spiel.h
open_spiel/spiel.cc