open spiel: absl::str_format_internal::ExtendedParsedFormat< C > Class Template Reference
absl::str_format_internal::ExtendedParsedFormat< C > Class Template Reference
#include <parser.h>
Public Member Functions
ExtendedParsedFormat (string_view format)
Public Member Functions inherited from absl::str_format_internal::ParsedFormatBase
ParsedFormatBase (string_view format, bool allow_ignored, std::initializer_list< FormatConversionCharSet > convs)
ParsedFormatBase (const ParsedFormatBase &other)
ParsedFormatBase (ParsedFormatBase &&other)
ParsedFormatBase & operator= (const ParsedFormatBase &other)
ParsedFormatBase & operator= (ParsedFormatBase &&other)
template<typename Consumer >
bool ProcessFormat (Consumer consumer) const
bool has_error () const
Static Public Member Functions
static std::unique_ptr< ExtendedParsedFormat > New (string_view format)
static std::unique_ptr< ExtendedParsedFormat > NewAllowIgnored (string_view format)
Detailed Description
template<FormatConversionCharSet... C>
class absl::str_format_internal::ExtendedParsedFormat< C >
Definition at line 219 of file parser.h.
Constructor & Destructor Documentation
ExtendedParsedFormat()
template<FormatConversionCharSet... C> absl::str_format_internal::ExtendedParsedFormat< C >::ExtendedParsedFormat (string_view format) inline explicit
Definition at line 221 of file parser.h.
      : ExtendedParsedFormat(format, false) {
  }
Member Function Documentation
New()
template<FormatConversionCharSet... C> static std::unique_ptr< ExtendedParsedFormat > absl::str_format_internal::ExtendedParsedFormat< C >::New (string_view format) inline static
Definition at line 244 of file parser.h.
{
    return New(format, false);
  }
References absl::str_format_internal::ExtendedParsedFormat< C >::New().
Referenced by absl::str_format_internal::ExtendedParsedFormat< C >::New(), absl::str_format_internal::ExtendedParsedFormat< C >::NewAllowIgnored(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), and absl::ABSL_NAMESPACE_BEGIN::TEST_F().
NewAllowIgnored()
template<FormatConversionCharSet... C> static std::unique_ptr< ExtendedParsedFormat > absl::str_format_internal::ExtendedParsedFormat< C >::NewAllowIgnored (string_view format) inline static
Definition at line 247 of file parser.h.
{
    return New(format, true);
  }
References absl::str_format_internal::ExtendedParsedFormat< C >::New().
Referenced by absl::ABSL_NAMESPACE_BEGIN::TEST_F(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), and absl::ABSL_NAMESPACE_BEGIN::TEST_F().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/str_format/parser.h