open spiel: open_spiel::universal_poker::UniversalPokerState Class Reference
open_spiel::universal_poker::UniversalPokerState Class Reference
#include <universal_poker.h>
Public Member Functions
UniversalPokerState (std::shared_ptr< const Game > game)
bool IsTerminal () const override
bool IsChanceNode () const override
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move) const override
std::string ToString () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::vector< Action > LegalActions () const override
std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const override
std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const override
std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
const acpc_cpp::ACPCState & acpc_state () const
const BettingAbstraction & betting () const
int PotSize (double multiple=1.) const
int AllInSize () const
void ApplyChoiceAction (StateActionType action_type, int size)
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 68 of file universal_poker.h.
Constructor & Destructor Documentation
UniversalPokerState()
open_spiel::universal_poker::UniversalPokerState::UniversalPokerState (std::shared_ptr< const Game > game) explicit
Definition at line 207 of file universal_poker.cc.
    : State(game),
      acpc_game_(
          static_cast<const UniversalPokerGame *>(game.get())->GetACPCGame()),
      acpc_state_(acpc_game_),
      deck_(/*num_suits=*/acpc_game_->NumSuitsDeck(),
            /*num_ranks=*/acpc_game_->NumRanksDeck()),
      cur_player_(kChancePlayerId),
      possibleActions_(ACTION_DEAL),
      betting_abstraction_(static_cast<const UniversalPokerGame *>(game.get())
                               ->betting_abstraction()) {
  // -- Optionally apply subgame parameters. -----------------------------------
  // Pot size.
  const int pot_size = game->GetParameters().at("potSize").int_value();
  if (pot_size > 0) {
    acpc_state_.SetPotSize(pot_size);
  }
  // Board cards.
  const std::string board_cards =
      game->GetParameters().at("boardCards").string_value();
  if (!board_cards.empty()) {
    // Add the cards.
    logic::CardSet cs(board_cards);
    int before_add = deck_.NumCards();
    for (uint8_t card : cs.ToCardArray()) {
      AddBoardCard(card);
      deck_.RemoveCard(card);
    }
    SPIEL_CHECK_EQ(deck_.NumCards(), before_add - cs.NumCards());
    // Advance the round according to the number of board cards.
    int num_cards = cs.NumCards();
    int round = 0;
    do  {
      num_cards -= acpc_game_->NumBoardCards(round);
      round++;
    } while (round < acpc_game_->NumRounds() && num_cards > 0);
    acpc_state_.mutable_state()->round = round - 1;
  }
  // Set specific hand reach probabilities.
  const std::string handReaches =
      game->GetParameters().at("handReaches").string_value();
  if (!handReaches.empty()) {
    std::stringstream iss(handReaches);
    double number;
    while ( iss >> number ) {
      handReaches_.push_back(number);
    }
    SPIEL_CHECK_EQ(handReaches_.size(), kSubgameUniqueHands * 2);
  }
}
References open_spiel::universal_poker::kSubgameUniqueHands, open_spiel::universal_poker::acpc_cpp::ACPCState::mutable_state(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumBoardCards(), open_spiel::universal_poker::logic::CardSet::NumCards(), open_spiel::universal_poker::logic::CardSet::RemoveCard(), open_spiel::universal_poker::acpc_cpp::ACPCState::SetPotSize(), SPIEL_CHECK_EQ, and open_spiel::universal_poker::logic::CardSet::ToCardArray().
Member Function Documentation
acpc_state()
const acpc_cpp::ACPCState & open_spiel::universal_poker::UniversalPokerState::acpc_state () const inline
Definition at line 104 of file universal_poker.h.
{ return acpc_state_; }
ActionsConsistentWithInformationFrom()
std::vector< Action > open_spiel::universal_poker::UniversalPokerState::ActionsConsistentWithInformationFrom (Action action) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 97 of file universal_poker.h.
{
    return {action};
  }
References action.
ActionToString()
std::string open_spiel::universal_poker::UniversalPokerState::ActionToString (Player player, Action move) const override virtual
Implements open_spiel::State.
Definition at line 305 of file universal_poker.cc.
{
  std::string move_str;
  if (IsChanceNode()) {
    move_str = absl::StrCat("Deal(", move, ")");
  } else if (static_cast<ActionType>(move) == ActionType::kFold) {
    move_str = "Fold";
  } else if (static_cast<ActionType>(move) == ActionType::kCall) {
    move_str = "Call";
  } else if (static_cast<ActionType>(move) == ActionType::kHalfPot &&
             // Avoids an edge case where we interpret a bet size that's
             // literally meant to be '4' as a half pot bet (since that's the
             // actual value of ActionTye::kHalfPot).
             betting_abstraction_ != BettingAbstraction::kFULLGAME) {
    move_str = "HalfPot";
  } else if (betting_abstraction_ == BettingAbstraction::kFULLGAME) {
    SPIEL_CHECK_GE(move, 2);
    move_str = absl::StrCat("Bet", move);
  } else if (static_cast<ActionType>(move) == ActionType::kBet) {
    move_str = "Bet";
  } else if (static_cast<ActionType>(move) == ActionType::kAllIn) {
    move_str = "AllIn";
  } else if (move > kBet) {
    SPIEL_CHECK_EQ(betting_abstraction_, BettingAbstraction::kFCHPA);
    move_str = absl::StrCat("r", move);
  } else {
    SpielFatalError(absl::StrCat("Unknown action: ", move));
  }
  return absl::StrCat("player=", player, " move=", move_str);
}
References IsChanceNode(), open_spiel::universal_poker::kAllIn, open_spiel::universal_poker::kBet, open_spiel::universal_poker::kCall, open_spiel::universal_poker::kFCHPA, open_spiel::universal_poker::kFold, open_spiel::universal_poker::kFULLGAME, open_spiel::universal_poker::kHalfPot, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, open_spiel::SpielFatalError(), and absl::StrCat().
AllInSize()
int open_spiel::universal_poker::UniversalPokerState::AllInSize () const
Definition at line 826 of file universal_poker.cc.
{
  int32_t unused_min_bet_size;
  int32_t all_in_size;
  acpc_state_.RaiseIsValid(&unused_min_bet_size, &all_in_size);
  return all_in_size;
}
References open_spiel::universal_poker::acpc_cpp::ACPCState::RaiseIsValid().
Referenced by DoApplyAction().
ApplyChoiceAction()
void open_spiel::universal_poker::UniversalPokerState::ApplyChoiceAction (StateActionType action_type, int size)
Definition at line 1236 of file universal_poker.cc.
{
  SPIEL_CHECK_GE(cur_player_, 0);  // No chance not terminal.
  const auto &up_game = static_cast<const UniversalPokerGame &>(*game_);
  // We redirect these actions to check/call, as they are semantically a
  // check/call action. For some reason, ACPC prefers it this way.
  if (size == up_game.MaxCommitment() * up_game.NumPlayers()) {
    action_type = StateActionType::ACTION_CHECK_CALL;
    size = 0;
  }
  actionSequence_ += (char)actions[action_type];
  // Note: call actions all have size '0', which means that the
  // actionSequenceSizing value will be identical regardless of what size stack
  // the caller has in all-in situations.
  actionSequenceSizings_.push_back(size);
  if (action_type == ACTION_DEAL) SpielFatalError("Cannot apply deal action.");
  acpc_state_.DoAction(UniversalPokerActionTypeToACPCActionType(action_type),
                       size);
  _CalculateActionsAndNodeType();
}
References open_spiel::universal_poker::ACTION_CHECK_CALL, open_spiel::universal_poker::ACTION_DEAL, open_spiel::universal_poker::actions, open_spiel::universal_poker::acpc_cpp::ACPCState::DoAction(), size, SPIEL_CHECK_GE, and open_spiel::SpielFatalError().
Referenced by DoApplyAction().
betting()
const BettingAbstraction & open_spiel::universal_poker::UniversalPokerState::betting () const inline
Definition at line 105 of file universal_poker.h.
{ return betting_abstraction_; }
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::universal_poker::UniversalPokerState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 730 of file universal_poker.cc.
          {
  SPIEL_CHECK_TRUE(IsChanceNode());
  if (IsDistributingSingleCard()) {
    auto available_cards = LegalActions();
    const int num_cards = available_cards.size();
    const double p = 1.0 / num_cards;
    // We need to convert std::vector<uint8_t> into std::vector<Action>.
    std::vector<std::pair<Action, double>> outcomes;
    outcomes.reserve(num_cards);
    for (const auto &card : available_cards) {
      outcomes.push_back({Action{card}, p});
    }
    return outcomes;
  } else {
    return DistributeHandCardsInSubgame();
  }
}
References IsChanceNode(), LegalActions(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::universal_poker::UniversalPokerState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 557 of file universal_poker.cc.
{
  return absl::make_unique<UniversalPokerState>(*this);
}
CurrentPlayer()
Player open_spiel::universal_poker::UniversalPokerState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 346 of file universal_poker.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  }
  if (IsChanceNode()) {
    return kChancePlayerId;
  }
  return Player(acpc_state_.CurrentPlayer());
}
References open_spiel::universal_poker::acpc_cpp::ACPCState::CurrentPlayer(), IsChanceNode(), IsTerminal(), open_spiel::kChancePlayerId, and open_spiel::kTerminalPlayerId.
Referenced by InformationStateString(), and ObservationString().
DoApplyAction()
void open_spiel::universal_poker::UniversalPokerState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 836 of file universal_poker.cc.
{
  if (IsChanceNode()) {
    if (IsDistributingSingleCard()) {
      // In chance nodes, the action_id is an index into the full deck.
      uint8_t card =
          logic::CardSet(acpc_game_->NumSuitsDeck(), acpc_game_->NumRanksDeck())
              .ToCardArray()[action_id];
      deck_.RemoveCard(card);
      actionSequence_ += 'd';
      actionSequenceSizings_.push_back(0);
      // Check where to add this card
      if (hole_cards_dealt_ <
          acpc_game_->GetNbPlayers() * acpc_game_->GetNbHoleCardsRequired()) {
        AddHoleCard(card);
        _CalculateActionsAndNodeType();
        return;
      }
      if (board_cards_dealt_ <
          acpc_game_->GetNbBoardCardsRequired(acpc_state_.GetRound())) {
        AddBoardCard(card);
        _CalculateActionsAndNodeType();
        return;
      }
    } else {
      // We are creating the subgame: therefore we distribute the hole cards
      // to each player.
      std::vector<int> base = GetEncodingBase();
      std::vector<int> cards = UnrankActionMixedBase(action_id, base);
      int num_hole_cards = acpc_game_->GetNbHoleCardsRequired();
      int num_cards_before_dist = deck_.NumCards();
      for (int pl = 0; pl < num_players_; ++pl) {
        for (int i = 0; i < num_hole_cards; ++i) {
          int card = cards.at(pl*num_hole_cards + i);
          SPIEL_CHECK_GE(rankOfCard(card), 0);
          SPIEL_CHECK_LT(rankOfCard(card), MAX_RANKS);
          SPIEL_CHECK_GE(suitOfCard(card), 0);
          SPIEL_CHECK_LT(suitOfCard(card), MAX_SUITS);
          SPIEL_CHECK_TRUE(deck_.ContainsCards(card));
          acpc_state_.AddHoleCard(pl, i, card);
          deck_.RemoveCard(card);
          SPIEL_CHECK_FALSE(deck_.ContainsCards(card));
          ++hole_cards_dealt_;
        }
      }
      SPIEL_CHECK_EQ(deck_.NumCards(), num_cards_before_dist - cards.size());
      _CalculateActionsAndNodeType();
    }
  } else {
    int action_int = static_cast<int>(action_id);
    if (action_int == kFold) {
      ApplyChoiceAction(ACTION_FOLD, 0);
      return;
    }
    if (action_int == kCall) {
      ApplyChoiceAction(ACTION_CHECK_CALL, 0);
      return;
    }
    if (betting_abstraction_ == BettingAbstraction::kFC) {
      SpielFatalError(absl::StrCat(
          "Tried to apply action that was not fold or call. Action: ",
          State::ActionToString(action_id)));
    }
    if (betting_abstraction_ != BettingAbstraction::kFULLGAME) {
      if (action_int == kHalfPot) {
        ApplyChoiceAction(ACTION_BET, PotSize(0.5));
        return;
      }
      if (action_int == kBet && acpc_game_->IsLimitGame()) {
        // In a limit game, the bet size is fixed, so the ACPC code expects size
        // to be 0.
        ApplyChoiceAction(ACTION_BET, /*size=*/0);
        return;
      }
      if (action_int == kBet && !acpc_game_->IsLimitGame()) {
        ApplyChoiceAction(ACTION_BET, PotSize());
        return;
      }
      if (action_int == kAllIn) {
        ApplyChoiceAction(ACTION_ALL_IN, AllInSize());
        return;
      }
      // FCHPA allows for arbitrary bets.
      if (betting_abstraction_ == BettingAbstraction::kFCHPA) {
        SPIEL_CHECK_LE(action_int, acpc_game_->Game().stack[0]);
        ApplyChoiceAction(ACTION_BET, action_int);
        return;
      }
    }
    if (betting_abstraction_ != BettingAbstraction::kFULLGAME) {
      SpielFatalError(absl::StrCat(
          "Tried to apply action that was not allowed by the betting "
          "abstraction. Action: ",
          State::ActionToString(action_id),
          ", abstraction: ", betting_abstraction_));
    }
    if (action_int >= static_cast<int>(kBet) &&
        action_int <= NumDistinctActions()) {
      ApplyChoiceAction(ACTION_BET, action_int);
      return;
    }
    SpielFatalError(absl::StrFormat("Action not recognized: %i", action_id));
  }
}
References open_spiel::universal_poker::ACTION_ALL_IN, open_spiel::universal_poker::ACTION_BET, open_spiel::universal_poker::ACTION_CHECK_CALL, open_spiel::universal_poker::ACTION_FOLD, open_spiel::State::ActionToString(), open_spiel::universal_poker::acpc_cpp::ACPCState::AddHoleCard(), AllInSize(), ApplyChoiceAction(), open_spiel::universal_poker::logic::CardSet::ContainsCards(), open_spiel::universal_poker::acpc_cpp::ACPCGame::Game(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbBoardCardsRequired(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbHoleCardsRequired(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), open_spiel::universal_poker::acpc_cpp::ACPCState::GetRound(), i, IsChanceNode(), open_spiel::universal_poker::acpc_cpp::ACPCGame::IsLimitGame(), open_spiel::universal_poker::kAllIn, open_spiel::universal_poker::kBet, open_spiel::universal_poker::kCall, open_spiel::universal_poker::kFC, open_spiel::universal_poker::kFCHPA, open_spiel::universal_poker::kFold, open_spiel::universal_poker::kFULLGAME, open_spiel::universal_poker::kHalfPot, open_spiel::State::num_players_, open_spiel::universal_poker::logic::CardSet::NumCards(), open_spiel::State::NumDistinctActions(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRanksDeck(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumSuitsDeck(), PotSize(), open_spiel::universal_poker::logic::CardSet::RemoveCard(), SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), absl::StrCat(), absl::StrFormat(), open_spiel::universal_poker::logic::CardSet::ToCardArray(), and open_spiel::UnrankActionMixedBase().
GetHistoriesConsistentWithInfostate()
std::unique_ptr< HistoryDistribution > open_spiel::universal_poker::UniversalPokerState::GetHistoriesConsistentWithInfostate (int player_id) const override virtual
Reimplemented from open_spiel::State.
Definition at line 958 of file universal_poker.cc.
{
  // This is only implemented for 2 players.
  if (acpc_game_->GetNbPlayers() != 2) return {};
  logic::CardSet is_cards;
  logic::CardSet our_cards = HoleCards(player_id);
  for (uint8_t card : our_cards.ToCardArray()) is_cards.AddCard(card);
  for (uint8_t card : BoardCards().ToCardArray()) is_cards.AddCard(card);
  logic::CardSet fresh_deck(/*num_suits=*/acpc_game_->NumSuitsDeck(),
                            /*num_ranks=*/acpc_game_->NumRanksDeck());
  for (uint8_t card : is_cards.ToCardArray()) fresh_deck.RemoveCard(card);
  auto dist = absl::make_unique<HistoryDistribution>();
  // We only consider half the possible hands as we only look at each pair of
  // hands once, i.e. order does not matter.
  const int num_hands =
      0.5 * fresh_deck.NumCards() * (fresh_deck.NumCards() - 1);
  dist->first.reserve(num_hands);
  for (uint8_t hole_card1 : fresh_deck.ToCardArray()) {
    logic::CardSet subset_deck = fresh_deck;
    subset_deck.RemoveCard(hole_card1);
    for (uint8_t hole_card2 : subset_deck.ToCardArray()) {
      if (hole_card1 < hole_card2) continue;
      std::unique_ptr<State> root = game_->NewInitialState();
      if (player_id == 0) {
        for (uint8_t card : our_cards.ToCardArray()) root->ApplyAction(card);
        root->ApplyAction(hole_card1);
        root->ApplyAction(hole_card2);
      } else if (player_id == 1) {
        root->ApplyAction(hole_card1);
        root->ApplyAction(hole_card2);
        for (uint8_t card : our_cards.ToCardArray()) root->ApplyAction(card);
      }
      SPIEL_CHECK_FALSE(root->IsChanceNode());
      dist->first.push_back(std::move(root));
    }
  }
  SPIEL_DCHECK_EQ(dist->first.size(), num_hands);
  const double divisor = 1. / static_cast<double>(dist->first.size());
  dist->second.assign(dist->first.size(), divisor);
  return dist;
}
References open_spiel::universal_poker::logic::CardSet::AddCard(), open_spiel::State::game_, open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), open_spiel::universal_poker::logic::CardSet::NumCards(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRanksDeck(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumSuitsDeck(), open_spiel::universal_poker::logic::CardSet::RemoveCard(), SPIEL_CHECK_FALSE, SPIEL_DCHECK_EQ, and open_spiel::universal_poker::logic::CardSet::ToCardArray().
InformationStateString()
std::string open_spiel::universal_poker::UniversalPokerState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 505 of file universal_poker.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, acpc_game_->GetNbPlayers());
  const uint32_t pot = acpc_state_.MaxSpend() *
                       (acpc_game_->GetNbPlayers() - acpc_state_.NumFolded());
  std::string money;
  money.reserve(acpc_game_->GetNbPlayers() * 2);
  for (auto p = Player{0}; p < acpc_game_->GetNbPlayers(); p++) {
    if (p != Player{0}) absl::StrAppend(&money, " ");
    absl::StrAppend(&money, acpc_state_.Money(p));
  }
  std::string sequences;
  sequences.reserve(acpc_state_.GetRound() * 2);
  for (auto r = 0; r <= acpc_state_.GetRound(); r++) {
    if (r != 0) absl::StrAppend(&sequences, "|");
    absl::StrAppend(&sequences, acpc_state_.BettingSequence(r));
  }
  return absl::StrFormat(
      "[Round %i][Player: %i][Pot: %i][Money: %s][Private: %s][Public: "
      "%s][Sequences: %s]",
      acpc_state_.GetRound(), CurrentPlayer(), pot, money,
      HoleCards(player).ToString(), BoardCards().ToString(), sequences);
}
References open_spiel::universal_poker::acpc_cpp::ACPCState::BettingSequence(), CurrentPlayer(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), open_spiel::universal_poker::acpc_cpp::ACPCState::GetRound(), open_spiel::universal_poker::acpc_cpp::ACPCState::MaxSpend(), open_spiel::universal_poker::acpc_cpp::ACPCState::Money(), open_spiel::universal_poker::acpc_cpp::ACPCState::NumFolded(), player, r, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), absl::StrFormat(), and ToString().
InformationStateTensor()
void open_spiel::universal_poker::UniversalPokerState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 371 of file universal_poker.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->InformationStateTensorShape()[0]);
  std::fill(values.begin(), values.end(), 0.);
  // Layout:
  //   my player number: num_players bits
  //   my cards: Initial deck size bits (1 means you have the card), i.e.
  //             MaxChanceOutcomes() = NumSuits * NumRanks
  //   public cards: Same as above, but for the public cards.
  //   action sequence: (max game length)*2 bits (fold/raise/call/all-in)
  //   action sequence sizings: (max game length) integers with value >= 0,
  //                             0 when corresponding to 'deal' or 'check'.
  int offset = 0;
  // Mark who I am.
  values[player] = 1;
  offset += NumPlayers();
  const logic::CardSet full_deck(acpc_game_->NumSuitsDeck(),
                                 acpc_game_->NumRanksDeck());
  const std::vector<uint8_t> deckCards = full_deck.ToCardArray();
  logic::CardSet holeCards = HoleCards(player);
  logic::CardSet boardCards = BoardCards();
  // Mark my private cards
  // (Note: it should be way more efficient to iterate over the cards of the
  // player, rather than iterating over all the cards. We may want to change
  // this in the future.)
  for (uint32_t i = 0; i < full_deck.NumCards(); i++) {
    values[i + offset] = holeCards.ContainsCards(deckCards[i]) ? 1.0 : 0.0;
  }
  offset += full_deck.NumCards();
  // Mark the public cards
  for (int i = 0; i < full_deck.NumCards(); ++i) {
    values[i + offset] = boardCards.ContainsCards(deckCards[i]) ? 1.0 : 0.0;
  }
  offset += full_deck.NumCards();
  const std::string actionSeq = GetActionSequence();
  const int length = actionSeq.length();
  SPIEL_CHECK_LT(length, game_->MaxGameLength());
  // Mark the action sequence (abstracted).
  for (int i = 0; i < length; ++i) {
    SPIEL_CHECK_LT(offset + i + 1, values.size());
    if (actionSeq[i] == 'c') {
      // Encode call as 10.
      values[offset + (2 * i)] = 1;
      values[offset + (2 * i) + 1] = 0;
    } else if (actionSeq[i] == 'p') {
      // Encode raise as 01.
      values[offset + (2 * i)] = 0;
      values[offset + (2 * i) + 1] = 1;
    } else if (actionSeq[i] == 'a') {
      // Encode all-in as 11.
      values[offset + (2 * i)] = 1;
      values[offset + (2 * i) + 1] = 1;
    } else if (actionSeq[i] == 'f') {
      // Encode fold as 00.
      // TODO(author2): Should this be 11?
      values[offset + (2 * i)] = 0;
      values[offset + (2 * i) + 1] = 0;
    } else if (actionSeq[i] == 'd') {
      values[offset + (2 * i)] = 0;
      values[offset + (2 * i) + 1] = 0;
    } else {
      SPIEL_CHECK_EQ(actionSeq[i], 'd');
    }
  }
  // Move offset to the end of the abstracted betting sequence (since 2 entries
  // per move).
  offset += game_->MaxGameLength() * 2;
  // Mark the action sequence sizings.
  const std::vector<int> action_sequence_sizings = GetActionSequenceSizings();
  SPIEL_CHECK_EQ(length, action_sequence_sizings.size());
  for (int i = 0; i < length; ++i) {
    values[offset + i] = action_sequence_sizings[i];
  }
  // Move offset to the end of the un-abstracted betting sequence.
  offset += game_->MaxGameLength();
  SPIEL_CHECK_EQ(offset, game_->InformationStateTensorShape()[0]);
}
References open_spiel::universal_poker::logic::CardSet::ContainsCards(), open_spiel::State::game_, i, open_spiel::State::num_players_, open_spiel::universal_poker::logic::CardSet::NumCards(), open_spiel::State::NumPlayers(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRanksDeck(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumSuitsDeck(), player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::universal_poker::logic::CardSet::ToCardArray(), and values.
IsChanceNode()
bool open_spiel::universal_poker::UniversalPokerState::IsChanceNode () const override virtual
Reimplemented from open_spiel::State.
Definition at line 342 of file universal_poker.cc.
{
  return cur_player_ == kChancePlayerId;
}
References open_spiel::kChancePlayerId.
Referenced by ActionToString(), ChanceOutcomes(), CurrentPlayer(), DoApplyAction(), LegalActions(), and ToString().
IsTerminal()
bool open_spiel::universal_poker::UniversalPokerState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 336 of file universal_poker.cc.
{
  bool finished = cur_player_ == kTerminalPlayerId;
  assert(acpc_state_.IsFinished() || !finished);
  return finished;
}
References open_spiel::universal_poker::acpc_cpp::ACPCState::IsFinished(), and open_spiel::kTerminalPlayerId.
Referenced by CurrentPlayer(), Returns(), and ToString().
LegalActions()
std::vector< Action > open_spiel::universal_poker::UniversalPokerState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 750 of file universal_poker.cc.
{
  if (IsChanceNode()) {
    if (IsDistributingSingleCard()) {
      const logic::CardSet full_deck(acpc_game_->NumSuitsDeck(),
                                     acpc_game_->NumRanksDeck());
      const std::vector<uint8_t> all_cards = full_deck.ToCardArray();
      std::vector<Action> actions;
      actions.reserve(deck_.NumCards());
      for (uint32_t i = 0; i < full_deck.NumCards(); i++) {
        if (deck_.ContainsCards(all_cards[i])) actions.push_back(i);
      }
      return actions;
    } else {
      // Strip away probability outcomes.
      std::vector<std::pair<Action, double>> outcomes =
          DistributeHandCardsInSubgame();
      std::vector <Action> actions;
      actions.reserve(outcomes.size());
      for (auto&[action, p] : outcomes) actions.push_back(action);
      return actions;
    }
  }
  std::vector<Action> legal_actions;
  if (betting_abstraction_ != BettingAbstraction::kFULLGAME) {
    if (ACTION_FOLD & possibleActions_) legal_actions.push_back(kFold);
    if (ACTION_CHECK_CALL & possibleActions_) legal_actions.push_back(kCall);
    if (ACTION_BET & possibleActions_) legal_actions.push_back(kBet);
    if (ACTION_ALL_IN & possibleActions_) legal_actions.push_back(kAllIn);
    // For legacy reasons, kHalfPot is the biggest action (in terms of the
    // action representation).
    // Note that FCHPA only tells the players about HalfPot + FCPA, but it will
    // accept most of the other ones.
    if (ACTION_BET & possibleActions_ && betting_abstraction_ == kFCHPA) {
      legal_actions.push_back(kHalfPot);
    }
    return legal_actions;
  } else {
    if (acpc_state_.IsFinished()) {
      return legal_actions;
    }
    if (acpc_state_.IsValidAction(
            acpc_cpp::ACPCState::ACPCActionType::ACPC_FOLD, 0)) {
      legal_actions.push_back(kFold);
    }
    if (acpc_state_.IsValidAction(
            acpc_cpp::ACPCState::ACPCActionType::ACPC_CALL, 0)) {
      legal_actions.push_back(kCall);
    }
    int32_t min_bet_size = 0;
    int32_t max_bet_size = 0;
    if (acpc_state_.RaiseIsValid(&min_bet_size, &max_bet_size)) {
      const int original_size = legal_actions.size();
      legal_actions.resize(original_size + max_bet_size - min_bet_size + 1);
      std::iota(legal_actions.begin() + original_size, legal_actions.end(),
                min_bet_size);
    }
  }
  return legal_actions;
}
References open_spiel::universal_poker::acpc_cpp::ACPCState::ACPC_CALL, open_spiel::universal_poker::acpc_cpp::ACPCState::ACPC_FOLD, action, open_spiel::universal_poker::ACTION_ALL_IN, open_spiel::universal_poker::ACTION_BET, open_spiel::universal_poker::ACTION_CHECK_CALL, open_spiel::universal_poker::ACTION_FOLD, open_spiel::universal_poker::actions, open_spiel::universal_poker::logic::CardSet::ContainsCards(), i, IsChanceNode(), open_spiel::universal_poker::acpc_cpp::ACPCState::IsFinished(), open_spiel::universal_poker::acpc_cpp::ACPCState::IsValidAction(), open_spiel::universal_poker::kAllIn, open_spiel::universal_poker::kBet, open_spiel::universal_poker::kCall, open_spiel::universal_poker::kFCHPA, open_spiel::universal_poker::kFold, open_spiel::universal_poker::kFULLGAME, open_spiel::universal_poker::kHalfPot, open_spiel::universal_poker::logic::CardSet::NumCards(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRanksDeck(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumSuitsDeck(), open_spiel::universal_poker::acpc_cpp::ACPCState::RaiseIsValid(), and open_spiel::universal_poker::logic::CardSet::ToCardArray().
Referenced by ChanceOutcomes().
ObservationString()
std::string open_spiel::universal_poker::UniversalPokerState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 530 of file universal_poker.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, acpc_game_->GetNbPlayers());
  std::string result;
  const uint32_t pot = acpc_state_.MaxSpend() *
                       (acpc_game_->GetNbPlayers() - acpc_state_.NumFolded());
  absl::StrAppend(&result, "[Round ", acpc_state_.GetRound(),
                  "][Player: ", CurrentPlayer(), "][Pot: ", pot, "][Money:");
  for (auto p = Player{0}; p < acpc_game_->GetNbPlayers(); p++) {
    absl::StrAppend(&result, " ", acpc_state_.Money(p));
  }
  absl::StrAppend(&result, "]");
  // Add the player's private cards
  if (player != kChancePlayerId) {
    absl::StrAppend(&result, "[Private: ", HoleCards(player).ToString(), "]");
  }
  // Adding the contribution of each players to the pot
  absl::StrAppend(&result, "[Ante:");
  for (auto p = Player{0}; p < num_players_; p++) {
    absl::StrAppend(&result, " ", acpc_state_.Ante(p));
  }
  absl::StrAppend(&result, "]");
  return result;
}
References open_spiel::universal_poker::acpc_cpp::ACPCState::Ante(), CurrentPlayer(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), open_spiel::universal_poker::acpc_cpp::ACPCState::GetRound(), open_spiel::kChancePlayerId, open_spiel::universal_poker::acpc_cpp::ACPCState::MaxSpend(), open_spiel::universal_poker::acpc_cpp::ACPCState::Money(), open_spiel::State::num_players_, open_spiel::universal_poker::acpc_cpp::ACPCState::NumFolded(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and ToString().
ObservationTensor()
void open_spiel::universal_poker::UniversalPokerState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 461 of file universal_poker.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, NumPlayers());
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorShape()[0]);
  std::fill(values.begin(), values.end(), 0.);
  // Layout of observation:
  //   my player number: num_players bits
  //   my cards: Initial deck size bits (1 means you have the card), i.e.
  //             MaxChanceOutcomes() = NumSuits * NumRanks
  //   public cards: Same as above, but for the public cards.
  //   the contribution of each player to the pot. num_players integers.
  int offset = 0;
  // Mark who I am.
  values[player] = 1;
  offset += NumPlayers();
  const logic::CardSet full_deck(acpc_game_->NumSuitsDeck(),
                                 acpc_game_->NumRanksDeck());
  const std::vector<uint8_t> all_cards = full_deck.ToCardArray();
  logic::CardSet holeCards = HoleCards(player);
  logic::CardSet boardCards = BoardCards();
  for (uint32_t i = 0; i < full_deck.NumCards(); i++) {
    values[i + offset] = holeCards.ContainsCards(all_cards[i]) ? 1.0 : 0.0;
  }
  offset += full_deck.NumCards();
  for (uint32_t i = 0; i < full_deck.NumCards(); i++) {
    values[i + offset] = boardCards.ContainsCards(all_cards[i]) ? 1.0 : 0.0;
  }
  offset += full_deck.NumCards();
  // Adding the contribution of each players to the pot.
  for (auto p = Player{0}; p < NumPlayers(); p++) {
    values[offset + p] = acpc_state_.Ante(p);
  }
  offset += NumPlayers();
  SPIEL_CHECK_EQ(offset, game_->ObservationTensorShape()[0]);
}
References open_spiel::universal_poker::acpc_cpp::ACPCState::Ante(), open_spiel::universal_poker::logic::CardSet::ContainsCards(), open_spiel::State::game_, i, open_spiel::universal_poker::logic::CardSet::NumCards(), open_spiel::State::NumPlayers(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRanksDeck(), open_spiel::universal_poker::acpc_cpp::ACPCGame::NumSuitsDeck(), player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::universal_poker::logic::CardSet::ToCardArray(), and values.
PotSize()
int open_spiel::universal_poker::UniversalPokerState::PotSize (double multiple = 1.) const
Definition at line 814 of file universal_poker.cc.
{
  const project_acpc_server::State &state = acpc_state_.raw_state();
  const project_acpc_server::Game &game = acpc_state_.game()->Game();
  const int pot_size = absl::c_accumulate(
      absl::Span<const int32_t>(state.spent, game.numPlayers), 0);
  const int amount_to_call =
      state.maxSpent -
      state.spent[project_acpc_server::currentPlayer(&game, &state)];
  const int pot_after_call = amount_to_call + pot_size;
  return std::round(state.maxSpent + multiple * pot_after_call);
}
References absl::c_accumulate(), open_spiel::universal_poker::acpc_cpp::ACPCGame::Game(), open_spiel::universal_poker::acpc_cpp::ACPCState::game(), open_spiel::universal_poker::acpc_cpp::ACPCState::raw_state(), and state.
Referenced by DoApplyAction().
ResampleFromInfostate()
std::unique_ptr< State > open_spiel::universal_poker::UniversalPokerState::ResampleFromInfostate (int player_id, std::function< double()> rng) const virtual
Reimplemented from open_spiel::State.
Definition at line 949 of file universal_poker.cc.
{
  std::unique_ptr<HistoryDistribution> potential_histories =
      GetHistoriesConsistentWithInfostate(player_id);
  const int index = SamplerFromRng(rng)(potential_histories->second);
  return std::move(potential_histories->first[index]);
}
References open_spiel::State::GetHistoriesConsistentWithInfostate().
Returns()
std::vector< double > open_spiel::universal_poker::UniversalPokerState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 357 of file universal_poker.cc.
{
  if (!IsTerminal()) {
    return std::vector<double>(NumPlayers(), 0.0);
  }
  std::vector<double> returns(NumPlayers());
  for (Player player = 0; player < NumPlayers(); ++player) {
    // Money vs money at start.
    returns[player] = GetTotalReward(player);
  }
  return returns;
}
References IsTerminal(), open_spiel::State::NumPlayers(), and player.
ToString()
std::string open_spiel::universal_poker::UniversalPokerState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 258 of file universal_poker.cc.
{
  std::string str =
      absl::StrCat(BettingAbstractionToString(betting_abstraction_), "\n");
  for (int p = 0; p < acpc_game_->GetNbPlayers(); ++p) {
    absl::StrAppend(&str, "P", p, " Cards: ", HoleCards(p).ToString(), "\n");
  }
  absl::StrAppend(&str, "BoardCards ", BoardCards().ToString(), "\n");
  if (IsChanceNode()) {
    absl::StrAppend(&str, "PossibleCardsToDeal ", deck_.ToString(), "\n");
  }
  if (IsTerminal()) {
    for (int p = 0; p < acpc_game_->GetNbPlayers(); ++p) {
      absl::StrAppend(&str, "P", p, " Reward: ", GetTotalReward(p), "\n");
    }
  }
  absl::StrAppend(&str, "Node type?: ");
  if (IsChanceNode()) {
    absl::StrAppend(&str, "Chance node\n");
  } else if (IsTerminal()) {
    absl::StrAppend(&str, "Terminal Node!\n");
  } else {
    absl::StrAppend(&str, "Player node for player ", cur_player_, "\n");
  }
  if (betting_abstraction_ == BettingAbstraction::kFC ||
      betting_abstraction_ == BettingAbstraction::kFCPA) {
    absl::StrAppend(&str, "PossibleActions (", GetPossibleActionCount(),
                    "): [");
    for (StateActionType action : ALL_ACTIONS) {
      if (action & possibleActions_) {
        if (action == ACTION_ALL_IN) absl::StrAppend(&str, " ACTION_ALL_IN ");
        if (action == ACTION_BET) absl::StrAppend(&str, " ACTION_BET ");
        if (action == ACTION_CHECK_CALL) {
          absl::StrAppend(&str, " ACTION_CHECK_CALL ");
        }
        if (action == ACTION_FOLD) absl::StrAppend(&str, " ACTION_FOLD ");
        if (action == ACTION_DEAL) absl::StrAppend(&str, " ACTION_DEAL ");
      }
    }
  }
  absl::StrAppend(&str, "]", "\nRound: ", acpc_state_.GetRound(),
                  "\nACPC State: ", acpc_state_.ToString(),
                  "\nAction Sequence: ", actionSequence_);
  return str;
}
References action, open_spiel::universal_poker::ACTION_ALL_IN, open_spiel::universal_poker::ACTION_BET, open_spiel::universal_poker::ACTION_CHECK_CALL, open_spiel::universal_poker::ACTION_DEAL, open_spiel::universal_poker::ACTION_FOLD, open_spiel::universal_poker::ALL_ACTIONS, open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), open_spiel::universal_poker::acpc_cpp::ACPCState::GetRound(), IsChanceNode(), IsTerminal(), open_spiel::universal_poker::kFC, open_spiel::universal_poker::kFCPA, absl::StrAppend(), absl::StrCat(), open_spiel::universal_poker::acpc_cpp::ACPCState::ToString(), open_spiel::universal_poker::logic::CardSet::ToString(), and ToString().
Referenced by InformationStateString(), ObservationString(), and ToString().
The documentation for this class was generated from the following files:
open_spiel/games/universal_poker/universal_poker.h
open_spiel/games/universal_poker/universal_poker.cc