open spiel: absl::profiling_internal::PeriodicSamplerBase Class Reference
absl::profiling_internal::PeriodicSamplerBase Class Reference abstract
#include <periodic_sampler.h>
Public Member Functions
PeriodicSamplerBase ()=default
PeriodicSamplerBase (PeriodicSamplerBase &&)=default
PeriodicSamplerBase (const PeriodicSamplerBase &)=default
bool Sample () noexcept
bool SubtleMaybeSample () noexcept
bool SubtleConfirmSample () noexcept
Protected Member Functions
~PeriodicSamplerBase ()=default
virtual int64_t GetExponentialBiased (int period) noexcept
Detailed Description
Definition at line 36 of file periodic_sampler.h.
Constructor & Destructor Documentation
PeriodicSamplerBase() [1/3]
absl::profiling_internal::PeriodicSamplerBase::PeriodicSamplerBase () default
PeriodicSamplerBase() [2/3]
absl::profiling_internal::PeriodicSamplerBase::PeriodicSamplerBase (PeriodicSamplerBase &&) default
PeriodicSamplerBase() [3/3]
absl::profiling_internal::PeriodicSamplerBase::PeriodicSamplerBase (const PeriodicSamplerBase &) default
~PeriodicSamplerBase()
absl::profiling_internal::PeriodicSamplerBase::~PeriodicSamplerBase () protected default
Member Function Documentation
GetExponentialBiased()
int64_t absl::profiling_internal::PeriodicSamplerBase::GetExponentialBiased (int period) protected virtual noexcept
Definition at line 25 of file periodic_sampler.cc.
{
  return rng_.GetStride(period);
}
Referenced by SubtleConfirmSample().
Sample()
bool absl::profiling_internal::PeriodicSamplerBase::Sample () inline noexcept
Definition at line 163 of file periodic_sampler.h.
{
  return ABSL_PREDICT_FALSE(SubtleMaybeSample()) ? SubtleConfirmSample()
                                                 : false;
}
References ABSL_PREDICT_FALSE, SubtleConfirmSample(), and SubtleMaybeSample().
SubtleConfirmSample()
bool absl::profiling_internal::PeriodicSamplerBase::SubtleConfirmSample () noexcept
Definition at line 29 of file periodic_sampler.cc.
{
  int current_period = period();
  // Deal with period case 0 (always off) and 1 (always on)
  if (ABSL_PREDICT_FALSE(current_period < 2)) {
    stride_ = 0;
    return current_period == 1;
  }
  // Check if this is the first call to Sample()
  if (ABSL_PREDICT_FALSE(stride_ == 1)) {
    stride_ = static_cast<uint64_t>(-GetExponentialBiased(current_period));
    if (static_cast<int64_t>(stride_) < -1) {
      ++stride_;
      return false;
    }
  }
  stride_ = static_cast<uint64_t>(-GetExponentialBiased(current_period));
  return true;
}
References ABSL_PREDICT_FALSE, and GetExponentialBiased().
Referenced by Sample().
SubtleMaybeSample()
bool absl::profiling_internal::PeriodicSamplerBase::SubtleMaybeSample () inline noexcept
Definition at line 155 of file periodic_sampler.h.
{
  // See comments on `stride_` for the unsigned increment / signed compare.
  if (ABSL_PREDICT_TRUE(static_cast<int64_t>(++stride_) < 0)) {
    return false;
  }
  return true;
}
References ABSL_PREDICT_TRUE.
Referenced by Sample().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/profiling/internal/periodic_sampler.h
open_spiel/abseil-cpp/absl/profiling/internal/periodic_sampler.cc