open spiel: open_spiel::algorithms::InfostateTree Class Reference
open_spiel::algorithms::InfostateTree Class Reference final
#include <infostate_tree.h>
Public Member Functions
const InfostateNode & root () const
InfostateNode * mutable_root ()
int root_branching_factor () const
Player acting_player () const
size_t tree_height () const
size_t num_decisions () const
size_t num_sequences () const
size_t num_leaves () const
size_t num_ids (DecisionId) const
size_t num_ids (SequenceId) const
size_t num_ids (LeafId) const
SequenceId empty_sequence () const
InfostateNode * observation_infostate (const SequenceId &sequence_id)
const InfostateNode * observation_infostate (const SequenceId &sequence_id) const
Range< SequenceId > AllSequenceIds () const
std::vector< DecisionId > DecisionIdsWithParentSeq (const SequenceId &) const
absl::optional< DecisionId > DecisionIdForSequence (const SequenceId &) const
absl::optional< InfostateNode * > DecisionForSequence (const SequenceId &)
bool IsLeafSequence (const SequenceId &) const
InfostateNode * decision_infostate (const DecisionId &decision_id)
const InfostateNode * decision_infostate (const DecisionId &decision_id) const
const std::vector< InfostateNode * > & AllDecisionInfostates () const
Range< DecisionId > AllDecisionIds () const
DecisionId DecisionIdFromInfostateString (const std::string &infostate_string) const
const std::vector< InfostateNode * > & leaf_nodes () const
InfostateNode * leaf_node (const LeafId &leaf_id) const
const std::vector< std::vector< InfostateNode * > > & nodes_at_depths () const
const std::vector< InfostateNode * > & nodes_at_depth (size_t depth) const
std::pair< double, SfStrategy > BestResponse (TreeplexVector< double > &&gradient) const
double BestResponseValue (LeafVector< double > &&gradient) const
std::ostream & operator<< (std::ostream &os) const
Friends
std::shared_ptr< InfostateTree > MakeInfostateTree (const Game &game, Player acting_player, int max_move_limit=1000)
std::shared_ptr< InfostateTree > MakeInfostateTree (const std::vector< const State * > &start_states, const std::vector< double > &chance_reach_probs, std::shared_ptr< Observer > infostate_observer, Player acting_player, int max_move_ahead_limit=1000)
std::shared_ptr< InfostateTree > MakeInfostateTree (const std::vector< const InfostateNode * > &start_nodes, int max_move_ahead_limit=1000)
Detailed Description
Definition at line 288 of file infostate_tree.h.
Member Function Documentation
acting_player()
Player open_spiel::algorithms::InfostateTree::acting_player () const inline
Definition at line 314 of file infostate_tree.h.
{ return acting_player_; }
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyCfValuesConstraints().
AllDecisionIds()
Range< DecisionId > open_spiel::algorithms::InfostateTree::AllDecisionIds () const inline
Definition at line 363 of file infostate_tree.h.
{
    return Range<DecisionId>(0, decision_infostates_.size(), this);
  }
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalPolicy().
AllDecisionInfostates()
const std::vector< InfostateNode * > & open_spiel::algorithms::InfostateTree::AllDecisionInfostates () const inline
Definition at line 360 of file infostate_tree.h.
{
    return decision_infostates_;
  }
AllSequenceIds()
Range< SequenceId > open_spiel::algorithms::InfostateTree::AllSequenceIds () const inline
Definition at line 339 of file infostate_tree.h.
{
    return Range<SequenceId>(0, sequences_.size(), this);
  }
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalSfStrategy().
BestResponse()
std::pair< double, SfStrategy > open_spiel::algorithms::InfostateTree::BestResponse (TreeplexVector< double > && gradient) const
Definition at line 597 of file infostate_tree.cc.
{
  SPIEL_CHECK_EQ(this, gradient.tree());
  SPIEL_CHECK_EQ(num_sequences(), gradient.size());
  SfStrategy response(this);
  // 1. Compute counterfactual best response
  // (i.e. in all infostates, even unreachable ones)
  SequenceId current(0, this);
  const double init_value = -std::numeric_limits<double>::infinity();
  while (current.id() <= empty_sequence().id()) {
    double max_value = init_value;
    SequenceId max_id = current;
    const InfostateNode* node = observation_infostate(current);
    for (current = node->start_sequence_id();
         current != node->end_sequence_id(); current.next()) {
      if (gradient[current] > max_value) {
        max_value = gradient[current];
        max_id = current;
      }
    }
    if (init_value != max_value) {
      gradient[node->sequence_id()] += max_value;
      response[max_id] = 1.;
    }
    current.next();
  }
  SPIEL_CHECK_EQ(current.id(), empty_sequence().id() + 1);
  // 2. Prune away unreachable subtrees.
  //
  // This can be done with a more costly recursion.
  // Instead we make a more cache-friendly double pass through the response
  // vector: we increment the visited path by 1, resulting in a value of 2.
  // Then we zero-out all values but 2.
  current = empty_sequence();
  response[current] = 2.;
  while (!IsLeafSequence(current)) {
    for (SequenceId seq : observation_infostate(current)->AllSequenceIds()) {
      if (response[seq] == 1.) {
        current = seq;
        response[seq] += 1.;
        break;
      }
    }
  }
  for (SequenceId seq : response.range()) {
    response[seq] = response[seq] == 2. ? 1. : 0.;
  }
  SPIEL_DCHECK_TRUE(IsValidSfStrategy(response));
  return {gradient[empty_sequence()], response};
}
References open_spiel::algorithms::InfostateNode::AllSequenceIds(), empty_sequence(), open_spiel::algorithms::InfostateNode::end_sequence_id(), open_spiel::algorithms::internal::NodeId< Self >::id(), IsLeafSequence(), open_spiel::algorithms::IsValidSfStrategy(), open_spiel::algorithms::internal::NodeId< Self >::next(), num_sequences(), observation_infostate(), open_spiel::algorithms::internal::TreeVector< T, Id >::range(), open_spiel::algorithms::InfostateNode::sequence_id(), SPIEL_CHECK_EQ, SPIEL_DCHECK_TRUE, and open_spiel::algorithms::InfostateNode::start_sequence_id().
BestResponseValue()
double open_spiel::algorithms::InfostateTree::BestResponseValue (LeafVector< double > && gradient) const
Definition at line 650 of file infostate_tree.cc.
{
  // Loop over all heights.
  for (int d = tree_height_ - 1; d >= 0; d--) {
    int left_offset = 0;
    // Loop over all parents of current nodes.
    for (int parent_idx = 0; parent_idx < nodes_at_depths_[d].size();
         parent_idx++) {
      const InfostateNode* node = nodes_at_depths_[d][parent_idx];
      const int num_children = node->num_children();
      const Range<LeafId> children_range =
          gradient.range(left_offset, left_offset + num_children);
      const LeafId parent_id(parent_idx, this);
      if (node->type() == kDecisionInfostateNode) {
        double max_value = std::numeric_limits<double>::min();
        for (LeafId id : children_range) {
          max_value = std::fmax(max_value, gradient[id]);
        }
        gradient[parent_id] = max_value;
      } else {
        SPIEL_DCHECK_EQ(node->type(), kObservationInfostateNode);
        double sum_value = 0.;
        for (LeafId id : children_range) {
          sum_value += gradient[id];
        }
        gradient[parent_id] = sum_value;
      }
      left_offset += num_children;
    }
    // Check that we passed over all of the children.
    SPIEL_DCHECK_EQ(left_offset, nodes_at_depths_[d + 1].size());
  }
  const LeafId root_id(0, this);
  return gradient[root_id];
}
References open_spiel::algorithms::kDecisionInfostateNode, open_spiel::algorithms::kObservationInfostateNode, open_spiel::algorithms::InfostateNode::num_children(), size, SPIEL_DCHECK_EQ, and open_spiel::algorithms::InfostateNode::type().
decision_infostate() [1/2]
InfostateNode * open_spiel::algorithms::InfostateTree::decision_infostate (const DecisionId & decision_id) inline
Definition at line 352 of file infostate_tree.h.
{
    SPIEL_DCHECK_TRUE(decision_id.BelongsToTree(this));
    return decision_infostates_.at(decision_id.id());
  }
References open_spiel::algorithms::internal::NodeId< Self >::BelongsToTree(), open_spiel::algorithms::internal::NodeId< Self >::id(), and SPIEL_DCHECK_TRUE.
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalPolicy().
decision_infostate() [2/2]
const InfostateNode * open_spiel::algorithms::InfostateTree::decision_infostate (const DecisionId & decision_id) const inline
Definition at line 356 of file infostate_tree.h.
{
    SPIEL_DCHECK_TRUE(decision_id.BelongsToTree(this));
    return decision_infostates_.at(decision_id.id());
  }
References open_spiel::algorithms::internal::NodeId< Self >::BelongsToTree(), open_spiel::algorithms::internal::NodeId< Self >::id(), and SPIEL_DCHECK_TRUE.
DecisionForSequence()
absl::optional< InfostateNode * > open_spiel::algorithms::InfostateTree::DecisionForSequence (const SequenceId & sequence_id)
Definition at line 487 of file infostate_tree.cc.
{
  SPIEL_DCHECK_TRUE(sequence_id.BelongsToTree(this));
  InfostateNode* node = sequences_.at(sequence_id.id());
  SPIEL_DCHECK_TRUE(node);
  if (node->is_root_node()) {
    return {};
  } else {
    return node->parent_;
  }
}
References open_spiel::algorithms::internal::NodeId< Self >::BelongsToTree(), open_spiel::algorithms::internal::NodeId< Self >::id(), open_spiel::algorithms::InfostateNode::is_root_node(), and SPIEL_DCHECK_TRUE.
DecisionIdForSequence()
absl::optional< DecisionId > open_spiel::algorithms::InfostateTree::DecisionIdForSequence (const SequenceId & sequence_id) const
Definition at line 476 of file infostate_tree.cc.
{
  SPIEL_DCHECK_TRUE(sequence_id.BelongsToTree(this));
  InfostateNode* node = sequences_.at(sequence_id.id());
  SPIEL_DCHECK_TRUE(node);
  if (node->is_root_node()) {
    return {};
  } else {
    return node->parent_->decision_id();
  }
}
References open_spiel::algorithms::internal::NodeId< Self >::BelongsToTree(), open_spiel::algorithms::InfostateNode::decision_id(), open_spiel::algorithms::internal::NodeId< Self >::id(), open_spiel::algorithms::InfostateNode::is_root_node(), and SPIEL_DCHECK_TRUE.
DecisionIdFromInfostateString()
DecisionId open_spiel::algorithms::InfostateTree::DecisionIdFromInfostateString (const std::string & infostate_string) const
Definition at line 686 of file infostate_tree.cc.
{
  for (InfostateNode* node : decision_infostates_) {
    if (node->infostate_string() == infostate_string)
      return node->decision_id();
  }
  return kUndefinedDecisionId;
}
References open_spiel::algorithms::kUndefinedDecisionId.
DecisionIdsWithParentSeq()
std::vector< DecisionId > open_spiel::algorithms::InfostateTree::DecisionIdsWithParentSeq (const SequenceId & sequence_id) const
Definition at line 504 of file infostate_tree.cc.
{
  std::vector<DecisionId> out;
  const InfostateNode* observation_node = sequences_.at(sequence_id.id());
  std::stack<const InfostateNode*> open_set;
  for (const InfostateNode* child : observation_node->child_iterator()) {
    open_set.push(child);
  }
  while (!open_set.empty()) {
    const InfostateNode* node = open_set.top();
    open_set.pop();
    if (node->type() == kDecisionInfostateNode &&
        node->sequence_id() == sequence_id) {
      out.push_back(node->decision_id());
    } else {
      for (const InfostateNode* child : node->child_iterator()) {
        open_set.push(child);
      }
    }
  }
  return out;
}
References open_spiel::algorithms::InfostateNode::child_iterator(), open_spiel::algorithms::InfostateNode::decision_id(), open_spiel::algorithms::internal::NodeId< Self >::id(), open_spiel::algorithms::kDecisionInfostateNode, out, open_spiel::algorithms::InfostateNode::sequence_id(), and open_spiel::algorithms::InfostateNode::type().
empty_sequence()
SequenceId open_spiel::algorithms::InfostateTree::empty_sequence () const
Definition at line 473 of file infostate_tree.cc.
{
  return root().sequence_id();
}
References root(), and open_spiel::algorithms::InfostateNode::sequence_id().
Referenced by BestResponse(), and open_spiel::algorithms::IsValidSfStrategy().
IsLeafSequence()
bool open_spiel::algorithms::InfostateTree::IsLeafSequence (const SequenceId & sequence_id) const
Definition at line 498 of file infostate_tree.cc.
{
  SPIEL_DCHECK_TRUE(sequence_id.BelongsToTree(this));
  InfostateNode* node = sequences_.at(sequence_id.id());
  SPIEL_DCHECK_TRUE(node);
  return node->start_sequence_id() == node->end_sequence_id();
}
References open_spiel::algorithms::internal::NodeId< Self >::BelongsToTree(), open_spiel::algorithms::InfostateNode::end_sequence_id(), open_spiel::algorithms::internal::NodeId< Self >::id(), SPIEL_DCHECK_TRUE, and open_spiel::algorithms::InfostateNode::start_sequence_id().
Referenced by BestResponse(), and open_spiel::algorithms::CheckSum().
leaf_node()
InfostateNode * open_spiel::algorithms::InfostateTree::leaf_node (const LeafId & leaf_id) const inline
Definition at line 373 of file infostate_tree.h.
{
    SPIEL_DCHECK_TRUE(leaf_id.BelongsToTree(this));
    return leaf_nodes().at(leaf_id.id());
  }
References open_spiel::algorithms::internal::NodeId< Self >::BelongsToTree(), open_spiel::algorithms::internal::NodeId< Self >::id(), leaf_nodes(), and SPIEL_DCHECK_TRUE.
leaf_nodes()
const std::vector< InfostateNode * > & open_spiel::algorithms::InfostateTree::leaf_nodes () const inline
Definition at line 370 of file infostate_tree.h.
{
    return nodes_at_depths_.back();
  }
Referenced by open_spiel::algorithms::ortools::ConnectTerminals(), and leaf_node().
mutable_root()
InfostateNode * open_spiel::algorithms::InfostateTree::mutable_root () inline
Definition at line 310 of file infostate_tree.h.
{ return root_.get(); }
nodes_at_depth()
const std::vector< InfostateNode * > & open_spiel::algorithms::InfostateTree::nodes_at_depth (size_t depth) const inline
Definition at line 380 of file infostate_tree.h.
{
    return nodes_at_depths_.at(depth);
  }
nodes_at_depths()
const std::vector< std::vector< InfostateNode * > > & open_spiel::algorithms::InfostateTree::nodes_at_depths () const inline
Definition at line 377 of file infostate_tree.h.
{
    return nodes_at_depths_;
  }
num_decisions()
size_t open_spiel::algorithms::InfostateTree::num_decisions () const inline
Definition at line 320 of file infostate_tree.h.
{ return decision_infostates_.size(); }
Referenced by num_ids(), and operator<<().
num_ids() [1/3]
size_t open_spiel::algorithms::InfostateTree::num_ids (DecisionId) const inline
Definition at line 324 of file infostate_tree.h.
{ return num_decisions(); }
References num_decisions().
num_ids() [2/3]
size_t open_spiel::algorithms::InfostateTree::num_ids (LeafId) const inline
Definition at line 326 of file infostate_tree.h.
{ return num_leaves(); }
References num_leaves().
num_ids() [3/3]
size_t open_spiel::algorithms::InfostateTree::num_ids (SequenceId) const inline
Definition at line 325 of file infostate_tree.h.
{ return num_sequences(); }
References num_sequences().
num_leaves()
size_t open_spiel::algorithms::InfostateTree::num_leaves () const inline
Definition at line 322 of file infostate_tree.h.
{ return nodes_at_depths_.back().size(); }
Referenced by num_ids(), and operator<<().
num_sequences()
size_t open_spiel::algorithms::InfostateTree::num_sequences () const inline
Definition at line 321 of file infostate_tree.h.
{ return sequences_.size(); }
Referenced by BestResponse(), num_ids(), and operator<<().
observation_infostate() [1/2]
InfostateNode * open_spiel::algorithms::InfostateTree::observation_infostate (const SequenceId & sequence_id) inline
Definition at line 330 of file infostate_tree.h.
{
    SPIEL_DCHECK_TRUE(sequence_id.BelongsToTree(this));
    return sequences_.at(sequence_id.id());
  }
References open_spiel::algorithms::internal::NodeId< Self >::BelongsToTree(), open_spiel::algorithms::internal::NodeId< Self >::id(), and SPIEL_DCHECK_TRUE.
Referenced by BestResponse(), open_spiel::algorithms::CheckSum(), and open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalSfStrategy().
observation_infostate() [2/2]
const InfostateNode * open_spiel::algorithms::InfostateTree::observation_infostate (const SequenceId & sequence_id) const inline
Definition at line 334 of file infostate_tree.h.
{
    SPIEL_DCHECK_TRUE(sequence_id.BelongsToTree(this));
    return sequences_.at(sequence_id.id());
  }
References open_spiel::algorithms::internal::NodeId< Self >::BelongsToTree(), open_spiel::algorithms::internal::NodeId< Self >::id(), and SPIEL_DCHECK_TRUE.
operator<<()
std::ostream & open_spiel::algorithms::InfostateTree::operator<< (std::ostream & os) const
Definition at line 203 of file infostate_tree.cc.
{
  return os << "Infostate tree for player " << acting_player_ << ".\n"
            << "Tree height: " << tree_height_ << '\n'
            << "Root branching: " << root_branching_factor() << '\n'
            << "Number of decision infostate nodes: " << num_decisions() << '\n'
            << "Number of sequences: " << num_sequences() << '\n'
            << "Number of leaves: " << num_leaves() << '\n'
            << "Tree certificate: " << '\n'
            << root().MakeCertificate() << '\n';
}
References open_spiel::algorithms::InfostateNode::MakeCertificate(), num_decisions(), num_leaves(), num_sequences(), root(), and root_branching_factor().
root()
const InfostateNode & open_spiel::algorithms::InfostateTree::root () const inline
Definition at line 309 of file infostate_tree.h.
{ return *root_; }
Referenced by open_spiel.python.algorithms.rcfr.RootStateWrapper::counterfactual_regrets_and_reach_weights(), open_spiel.python.pytorch.rcfr.RootStateWrapper::counterfactual_regrets_and_reach_weights(), empty_sequence(), operator<<(), open_spiel.python.algorithms.rcfr.RootStateWrapper::sequence_weights_to_tabular_profile(), and open_spiel.python.pytorch.rcfr.RootStateWrapper::sequence_weights_to_tabular_profile().
root_branching_factor()
int open_spiel::algorithms::InfostateTree::root_branching_factor () const
Definition at line 406 of file infostate_tree.cc.
{
  return root_->num_children();
}
Referenced by operator<<().
tree_height()
size_t open_spiel::algorithms::InfostateTree::tree_height () const inline
Definition at line 317 of file infostate_tree.h.
{ return tree_height_; }
Friends And Related Symbol Documentation
MakeInfostateTree [1/3]
std::shared_ptr< InfostateTree > MakeInfostateTree (const Game & game, Player acting_player, int max_move_limit = 1000) friend
Definition at line 410 of file infostate_tree.cc.
{
  // Uses new instead of make_shared, because shared_ptr is not a friend and
  // can't call private constructors.
  return std::shared_ptr<InfostateTree>(new InfostateTree(
      {game.NewInitialState().get()}, /*chance_reach_probs=*/{1.},
      game.MakeObserver(kInfoStateObsType, {}), acting_player, max_move_limit));
}
MakeInfostateTree [2/3]
std::shared_ptr< InfostateTree > MakeInfostateTree (const std::vector< const InfostateNode * > & start_nodes, int max_move_ahead_limit = 1000) friend
Definition at line 427 of file infostate_tree.cc.
{
  SPIEL_CHECK_FALSE(start_nodes.empty());
  const InfostateNode* some_node = start_nodes[0];
  const InfostateTree& originating_tree = some_node->tree();
  SPIEL_DCHECK_TRUE([&]() {
    for (const InfostateNode* node : start_nodes) {
      if (!node) return false;
      if (!node->is_leaf_node()) return false;
      if (node->depth() != some_node->depth()) return false;
      if (&node->tree() != &originating_tree) return false;
    }
    return true;
  }());
  // We reserve a larger number of states, as infostate nodes typically contain
  // a large number of States. (8 is an arbitrary choice though).
  std::vector<const State*> start_states;
  start_states.reserve(start_nodes.size() * 8);
  std::vector<double> chance_reach_probs;
  chance_reach_probs.reserve(start_nodes.size() * 8);
  for (const InfostateNode* node : start_nodes) {
    for (int i = 0; i < node->corresponding_states_size(); ++i) {
      start_states.push_back(node->corresponding_states()[i].get());
      chance_reach_probs.push_back(node->corresponding_chance_reach_probs()[i]);
    }
  }
  // Uses new instead of make_shared, because shared_ptr is not a friend and
  // can't call private constructors.
  return std::shared_ptr<InfostateTree>(new InfostateTree(
      start_states, chance_reach_probs, originating_tree.infostate_observer_,
      originating_tree.acting_player_, max_move_ahead_limit));
}
MakeInfostateTree [3/3]
std::shared_ptr< InfostateTree > MakeInfostateTree (const std::vector< const State * > & start_states, const std::vector< double > & chance_reach_probs, std::shared_ptr< Observer > infostate_observer, Player acting_player, int max_move_ahead_limit = 1000) friend
Definition at line 464 of file infostate_tree.cc.
{
  return std::shared_ptr<InfostateTree>(
      new InfostateTree(start_states, chance_reach_probs, infostate_observer,
                        acting_player, max_move_ahead_limit));
}
The documentation for this class was generated from the following files:
open_spiel/algorithms/infostate_tree.h
open_spiel/algorithms/infostate_tree.cc