open spiel: open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame Class Reference
open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame Class Reference
#include <bridge_uncontested_bidding.h>
Public Member Functions
UncontestedBiddingGame (const GameParameters &params)
int NumDistinctActions () const override
int MaxChanceOutcomes () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
std::vector< int > InformationStateTensorShape () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
std::string GetRNGState () const
void SetRNGState (const std::string &rng_state) const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual std::vector< int > ObservationTensorShape () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 207 of file bridge_uncontested_bidding.h.
Constructor & Destructor Documentation
UncontestedBiddingGame()
open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::UncontestedBiddingGame (const GameParameters & params) explicit
Definition at line 336 of file bridge_uncontested_bidding.cc.
    : Game(kGameType, params),
      forced_actions_{},
      deal_filter_{NoFilter},
      rng_seed_(ParameterValue<int>("rng_seed")),
      num_redeals_(ParameterValue<int>("num_redeals")) {
  std::string subgame = ParameterValue<std::string>("subgame");
  if (subgame == "2NT") {
    deal_filter_ = Is2NTDeal;
    forced_actions_ = {k2NT};
    if (ParameterValue<bool>("relative_scoring")) {
      reference_contracts_ = {
          {2, kNoTrump, kUndoubled, 0},  {3, kClubs, kUndoubled, 1},
          {3, kDiamonds, kUndoubled, 0}, {3, kDiamonds, kUndoubled, 1},
          {3, kHearts, kUndoubled, 0},   {3, kHearts, kUndoubled, 1},
          {3, kSpades, kUndoubled, 0},   {3, kSpades, kUndoubled, 1},
          {3, kNoTrump, kUndoubled, 0},  {4, kClubs, kUndoubled, 0},
          {4, kHearts, kUndoubled, 0},   {4, kHearts, kUndoubled, 1},
          {4, kSpades, kUndoubled, 0},   {4, kSpades, kUndoubled, 1},
          {5, kClubs, kUndoubled, 0},    {5, kClubs, kUndoubled, 1},
          {5, kDiamonds, kUndoubled, 0}, {5, kDiamonds, kUndoubled, 1},
          {6, kClubs, kUndoubled, 0},    {6, kClubs, kUndoubled, 1},
          {6, kDiamonds, kUndoubled, 0}, {6, kDiamonds, kUndoubled, 1},
          {6, kHearts, kUndoubled, 0},   {6, kHearts, kUndoubled, 1},
          {6, kSpades, kUndoubled, 0},   {6, kSpades, kUndoubled, 1},
          {6, kNoTrump, kUndoubled, 0},  {7, kClubs, kUndoubled, 0},
          {7, kClubs, kUndoubled, 1},    {7, kDiamonds, kUndoubled, 0},
          {7, kDiamonds, kUndoubled, 1}, {7, kHearts, kUndoubled, 0},
          {7, kHearts, kUndoubled, 1},   {7, kSpades, kUndoubled, 0},
          {7, kSpades, kUndoubled, 1},   {7, kNoTrump, kUndoubled, 0}};
    }
  } else {
    SPIEL_CHECK_EQ(subgame, "");
    if (ParameterValue<bool>("relative_scoring")) {
      reference_contracts_ = {
          {0, kNoTrump, kUndoubled, 0},  {1, kClubs, kUndoubled, 0},
          {1, kClubs, kUndoubled, 1},    {1, kDiamonds, kUndoubled, 0},
          {1, kDiamonds, kUndoubled, 1}, {1, kHearts, kUndoubled, 0},
          {1, kHearts, kUndoubled, 1},   {1, kSpades, kUndoubled, 0},
          {1, kSpades, kUndoubled, 1},   {1, kNoTrump, kUndoubled, 0},
          {1, kNoTrump, kUndoubled, 1},  {3, kNoTrump, kUndoubled, 0},
          {3, kNoTrump, kUndoubled, 1},  {4, kHearts, kUndoubled, 0},
          {4, kHearts, kUndoubled, 1},   {4, kSpades, kUndoubled, 0},
          {4, kSpades, kUndoubled, 1},   {5, kClubs, kUndoubled, 0},
          {5, kClubs, kUndoubled, 1},    {5, kDiamonds, kUndoubled, 0},
          {5, kDiamonds, kUndoubled, 1}, {6, kClubs, kUndoubled, 0},
          {6, kClubs, kUndoubled, 1},    {6, kDiamonds, kUndoubled, 0},
          {6, kDiamonds, kUndoubled, 1}, {6, kHearts, kUndoubled, 0},
          {6, kHearts, kUndoubled, 1},   {6, kSpades, kUndoubled, 0},
          {6, kSpades, kUndoubled, 1},   {6, kNoTrump, kUndoubled, 0},
          {6, kNoTrump, kUndoubled, 1},  {7, kClubs, kUndoubled, 0},
          {7, kClubs, kUndoubled, 1},    {7, kDiamonds, kUndoubled, 0},
          {7, kDiamonds, kUndoubled, 1}, {7, kHearts, kUndoubled, 0},
          {7, kHearts, kUndoubled, 1},   {7, kSpades, kUndoubled, 0},
          {7, kSpades, kUndoubled, 1},   {7, kNoTrump, kUndoubled, 0},
          {7, kNoTrump, kUndoubled, 1}};
    }
  }
}
References open_spiel::Game::ParameterValue(), and SPIEL_CHECK_EQ.
Member Function Documentation
DeserializeState()
std::unique_ptr< State > open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 398 of file bridge_uncontested_bidding.cc.
{
  if (str.empty()) {
    return absl::make_unique<UncontestedBiddingState>(
        shared_from_this(), reference_contracts_, deal_filter_, forced_actions_,
        rng_seed_, num_redeals_);
  }
  SPIEL_CHECK_GE(str.length(),
                 kNumPlayers * (kNumCardsPerHand + kNumSuits) - 1);
  std::array<int, kNumCards> cards{};
  std::array<int, kNumCards> cards_dealt{};
  for (Player player = 0; player < kNumPlayers; ++player) {
    int suit = 0;
    int start = player * (kNumCardsPerHand + kNumSuits);
    for (int i = 0; i < kNumCardsPerHand; ++i) {
      char ch = str[start + i + suit];
      while (ch == '.') {
        ++suit;
        ch = str[start + i + suit];
      }
      const int rank = (std::strchr(kRankChar, ch) - kRankChar);
      const int card = rank * 4 + (3 - suit);
      SPIEL_CHECK_FALSE(cards_dealt[card]);
      cards[player * kNumCardsPerHand + i] = card;
      cards_dealt[card] = true;
    }
  }
  int i = kNumPlayers * kNumCardsPerHand;
  for (int c = 0; c < 52; ++c) {
    if (!cards_dealt[c]) cards[i++] = c;
  }
  // Get any actions there may be.
  std::vector<Action> actions;
  int start = kNumPlayers * (kNumCardsPerHand + kNumSuits);
  while (start < str.length()) {
    auto end = str.find('-', start);
    if (end == std::string::npos) end = str.length();
    actions.push_back(ActionFromString(str.substr(start, end - start)));
    start = end + 1;
  }
  // Check that early actions agree with the forced actions in this game.
  SPIEL_CHECK_GE(actions.size(), forced_actions_.size());
  for (int i = 0; i < forced_actions_.size(); ++i) {
    SPIEL_CHECK_EQ(actions[i], forced_actions_[i]);
  }
  return absl::make_unique<UncontestedBiddingState>(
      shared_from_this(), reference_contracts_, Deal(cards), actions, rng_seed_,
      num_redeals_);
}
References open_spiel::bridge_uncontested_bidding::ActionFromString(), i, open_spiel::bridge_uncontested_bidding::kNumCardsPerHand, open_spiel::bridge_uncontested_bidding::kNumPlayers, open_spiel::bridge_uncontested_bidding::kNumSuits, open_spiel::bridge_uncontested_bidding::kRankChar, player, rank, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, and SPIEL_CHECK_GE.
GetRNGState()
std::string open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::GetRNGState () const virtual
Reimplemented from open_spiel::Game.
Definition at line 451 of file bridge_uncontested_bidding.cc.
{
  return std::to_string(rng_seed_);
}
InformationStateTensorShape()
std::vector< int > open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::InformationStateTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 224 of file bridge_uncontested_bidding.h.
{
    return {kStateSize};
  }
References open_spiel::bridge_uncontested_bidding::kStateSize.
MaxChanceNodesInHistory()
int open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 228 of file bridge_uncontested_bidding.h.
{ return 1; }
MaxChanceOutcomes()
int open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 211 of file bridge_uncontested_bidding.h.
{ return 1; }
MaxGameLength()
int open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 227 of file bridge_uncontested_bidding.h.
{ return kNumActions; }
References open_spiel::bridge_uncontested_bidding::kNumActions.
MaxUtility()
double open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 221 of file bridge_uncontested_bidding.h.
{
    return reference_contracts_.empty() ? kMaxScore : 0;
  }
References open_spiel::bridge_uncontested_bidding::kMaxScore.
MinUtility()
double open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 218 of file bridge_uncontested_bidding.h.
{
    return reference_contracts_.empty() ? kMinScore : kMinScore - kMaxScore;
  }
References open_spiel::bridge_uncontested_bidding::kMaxScore, and open_spiel::bridge_uncontested_bidding::kMinScore.
NewInitialState()
std::unique_ptr< State > open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 212 of file bridge_uncontested_bidding.h.
{
    return absl::make_unique<UncontestedBiddingState>(
        shared_from_this(), reference_contracts_, deal_filter_, forced_actions_,
        ++rng_seed_, num_redeals_);
  }
NumDistinctActions()
int open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 210 of file bridge_uncontested_bidding.h.
{ return kNumActions; }
References open_spiel::bridge_uncontested_bidding::kNumActions.
NumPlayers()
int open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 217 of file bridge_uncontested_bidding.h.
{ return kNumPlayers; }
References open_spiel::bridge_uncontested_bidding::kNumPlayers.
SetRNGState()
void open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::SetRNGState (const std::string & rng_state) const virtual
Reimplemented from open_spiel::Game.
Definition at line 455 of file bridge_uncontested_bidding.cc.
{
  if (rng_state.empty()) return;
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(rng_state, &rng_seed_));
}
References absl::SimpleAtoi(), and SPIEL_CHECK_TRUE.
The documentation for this class was generated from the following files:
open_spiel/games/bridge/bridge_uncontested_bidding.h
open_spiel/games/bridge/bridge_uncontested_bidding.cc