open spiel: absl::ReleasableMutexLock Class Reference
absl::ReleasableMutexLock Class Reference
#include <mutex.h>
Public Member Functions
ReleasableMutexLock (Mutex *mu) ABSL_EXCLUSIVE_LOCK_FUNCTION(mu)
ReleasableMutexLock (Mutex *mu, const Condition &cond) ABSL_EXCLUSIVE_LOCK_FUNCTION(mu)
~ReleasableMutexLock () ABSL_UNLOCK_FUNCTION()
void Release () ABSL_UNLOCK_FUNCTION()
Detailed Description
Definition at line 948 of file mutex.h.
Constructor & Destructor Documentation
ReleasableMutexLock() [1/2]
absl::ReleasableMutexLock::ReleasableMutexLock (Mutex * mu) inline explicit
Definition at line 950 of file mutex.h.
      : mu_(mu) {
    this->mu_->Lock();
  }
References absl::Mutex::Lock().
ReleasableMutexLock() [2/2]
absl::ReleasableMutexLock::ReleasableMutexLock (Mutex * mu, const Condition & cond) inline explicit
Definition at line 955 of file mutex.h.
      : mu_(mu) {
    this->mu_->LockWhen(cond);
  }
References absl::Mutex::LockWhen().
~ReleasableMutexLock()
absl::ReleasableMutexLock::~ReleasableMutexLock () inline
Definition at line 961 of file mutex.h.
{
    if (this->mu_ != nullptr) { this->mu_->Unlock(); }
  }
References absl::Mutex::Unlock().
Member Function Documentation
Release()
void absl::ReleasableMutexLock::Release ()
Definition at line 2769 of file mutex.cc.
{
  ABSL_RAW_CHECK(this->mu_ != nullptr,
                 "ReleasableMutexLock::Release may only be called once");
  this->mu_->Unlock();
  this->mu_ = nullptr;
}
References ABSL_RAW_CHECK, and absl::Mutex::Unlock().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/synchronization/mutex.h
open_spiel/abseil-cpp/absl/synchronization/mutex.cc