open spiel: open_spiel::crowd_modelling_2d::CrowdModelling2dState Class Reference
open_spiel::crowd_modelling_2d::CrowdModelling2dState Class Reference
#include <crowd_modelling_2d.h>
Public Member Functions
CrowdModelling2dState (std::shared_ptr< const Game > game, int size, int horizon, bool only_distribution_reward, const std::string &forbidden_states, const std::string &initial_distribution, const std::string &initial_distribution_value, const std::string &positional_reward, const std::string &positional_reward_value, bool with_congestion, double noise_intensity, double crowd_aversion_coef)
CrowdModelling2dState (std::shared_ptr< const Game > game, int size, int horizon, bool only_distribution_reward, const std::string &forbidden_states, const std::string &initial_distribution, const std::string &initial_distribution_value, const std::string &positional_reward, const std::string &positional_reward_value, Player current_player, bool is_chance_init_, int x, int y, int t, int last_action, double return_value, const std::vector< double > &distribution, bool with_congestion, double noise_intensity, double crowd_aversion_coef)
CrowdModelling2dState (const CrowdModelling2dState &)=default
CrowdModelling2dState & operator= (const CrowdModelling2dState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
ActionsAndProbs ChanceOutcomes () const override
std::vector< std::string > DistributionSupport () override
void UpdateDistribution (const std::vector< double > &distribution) override
std::string Serialize () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
bool IsForbidden (Action action) const
bool IsForbiddenPosition (int x, int y) const
std::vector< Action > LegalPlayerActions () const
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 83 of file crowd_modelling_2d.h.
Constructor & Destructor Documentation
CrowdModelling2dState() [1/3]
open_spiel::crowd_modelling_2d::CrowdModelling2dState::CrowdModelling2dState (std::shared_ptr< const Game > game, int size, int horizon, bool only_distribution_reward, const std::string & forbidden_states, const std::string & initial_distribution, const std::string & initial_distribution_value, const std::string & positional_reward, const std::string & positional_reward_value, bool with_congestion, double noise_intensity, double crowd_aversion_coef)
Definition at line 188 of file crowd_modelling_2d.cc.
    : State(game),
      size_(size),
      horizon_(horizon),
      only_distribution_reward_(only_distribution_reward),
      with_congestion_(with_congestion),
      noise_intensity_(noise_intensity),
      crowd_aversion_coef_(crowd_aversion_coef),
      distribution_(size_ * size_, 1. / (size_ * size_)) {
  std::vector<absl::string_view> initial_distribution_list =
      ProcessStringParam(initial_distribution, size_);
  std::vector<absl::string_view> initial_distribution_value_list =
      ProcessStringParam(initial_distribution_value, size_);
  SPIEL_CHECK_EQ(initial_distribution_list.size(),
                 initial_distribution_value_list.size());
  auto initial_distribution_pair = StringListToPairs(initial_distribution_list);
  auto initial_distribution_value_f =
      StringListToFloats(initial_distribution_value_list);
  int initial_distribution_action_prob_size = initial_distribution_list.size();
  if (initial_distribution_action_prob_size == 0) {
    for (int i = 0; i < size_ * size_; ++i) {
      initial_distribution_action_prob_.push_back({i, 1. / (size_ * size_)});
    }
  } else {
    for (int i = 0; i < initial_distribution_action_prob_size; ++i) {
      int kk = MergeXY(initial_distribution_pair[i].first,
                       initial_distribution_pair[i].second, size_);
      initial_distribution_action_prob_.push_back(
          {kk, initial_distribution_value_f[i]});
    }
  }
  std::sort(initial_distribution_action_prob_.begin(),
            initial_distribution_action_prob_.end(), ComparisonPair);
  std::vector<absl::string_view> forbidden_states_list =
      ProcessStringParam(forbidden_states, size_);
  forbidden_states_xy_ = StringListToPairs(forbidden_states_list);
  for (const auto& forbidden_state_xy : forbidden_states_xy_) {
    SPIEL_CHECK_GE(forbidden_state_xy.first, 0);
    SPIEL_CHECK_LE(forbidden_state_xy.first, size_ - 1);
    SPIEL_CHECK_GE(forbidden_state_xy.second, 0);
    SPIEL_CHECK_LE(forbidden_state_xy.second, size_ - 1);
  }
  std::vector<absl::string_view> positional_reward_list =
      ProcessStringParam(positional_reward, size_);
  std::vector<absl::string_view> positional_reward_value_list =
      ProcessStringParam(positional_reward_value, size_);
  positional_reward_xy_ = StringListToPairs(positional_reward_list);
  positional_reward_value_ = StringListToFloats(positional_reward_value_list);
  // There should be a reward for each positional reward XY pair.
  SPIEL_CHECK_EQ(positional_reward_xy_.size(), positional_reward_value_.size());
  for (const auto& positional_reward_xy : positional_reward_xy_) {
    SPIEL_CHECK_GE(positional_reward_xy.first, 0);
    SPIEL_CHECK_LE(positional_reward_xy.first, size_ - 1);
    SPIEL_CHECK_GE(positional_reward_xy.second, 0);
    SPIEL_CHECK_LE(positional_reward_xy.second, size_ - 1);
  }
  if (positional_reward_xy_.empty()) {
    // Use the center point as the reward position.
    positional_reward_xy_.push_back({size_ / 2, size_ / 2});
    positional_reward_value_.push_back(1.0);
  }
  // Forbid to the initial distribution and the forbidden states to overlap.
  auto forbidden_states_int = StringListToInts(forbidden_states_list, size_);
  auto initial_distribution_int =
      StringListToInts(initial_distribution_list, size_);
  std::vector<int> intersection;
  std::sort(forbidden_states_int.begin(), forbidden_states_int.end());
  std::sort(initial_distribution_int.begin(), initial_distribution_int.end());
  std::set_intersection(
      forbidden_states_int.begin(), forbidden_states_int.end(),
      initial_distribution_int.begin(), initial_distribution_int.end(),
      back_inserter(intersection));
  SPIEL_CHECK_EQ(intersection.size(), 0);
}
References first, i, open_spiel::crowd_modelling_2d::ProcessStringParam(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Referenced by Clone().
CrowdModelling2dState() [2/3]
open_spiel::crowd_modelling_2d::CrowdModelling2dState::CrowdModelling2dState (std::shared_ptr< const Game > game, int size, int horizon, bool only_distribution_reward, const std::string & forbidden_states, const std::string & initial_distribution, const std::string & initial_distribution_value, const std::string & positional_reward, const std::string & positional_reward_value, Player current_player, bool is_chance_init_, int x, int y, int t, int last_action, double return_value, const std::vector< double > & distribution, bool with_congestion, double noise_intensity, double crowd_aversion_coef)
Definition at line 279 of file crowd_modelling_2d.cc.
    : CrowdModelling2dState(game, size, horizon, only_distribution_reward,
                            forbidden_states, initial_distribution,
                            initial_distribution_value, positional_reward,
                            positional_reward_value, with_congestion,
                            noise_intensity, crowd_aversion_coef) {
  current_player_ = current_player;
  is_chance_init_ = is_chance_init;
  x_ = x;
  y_ = y;
  t_ = t;
  last_action_ = last_action;
  return_value_ = return_value;
}
References x, and y.
CrowdModelling2dState() [3/3]
open_spiel::crowd_modelling_2d::CrowdModelling2dState::CrowdModelling2dState (const CrowdModelling2dState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::crowd_modelling_2d::CrowdModelling2dState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 392 of file crowd_modelling_2d.cc.
{
  if (IsChanceNode() && is_chance_init_) {
    return absl::Substitute("init_state=$0", action);
  }
  return absl::Substitute("($0,$1)", kActionToMoveX.at(action),
                          kActionToMoveY.at(action));
}
References action, open_spiel::State::IsChanceNode(), and absl::Substitute().
ChanceOutcomes()
ActionsAndProbs open_spiel::crowd_modelling_2d::CrowdModelling2dState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 322 of file crowd_modelling_2d.cc.
{
  if (is_chance_init_) {
    return initial_distribution_action_prob_;
  }
  const std::vector<Action> legal_actions = LegalPlayerActions();
  ActionsAndProbs outcomes;
  if (legal_actions.empty()) {
    return outcomes;
  }
  // Neutral action will always be present in the legal actions.
  const double prob = noise_intensity_ / legal_actions.size();
  outcomes.reserve(legal_actions.size());
  for (const Action action : legal_actions) {
    if (action == kNeutralAction) {
      outcomes.emplace_back(action, 1.0 - noise_intensity_ + prob);
    } else {
      outcomes.emplace_back(action, prob);
    }
  }
  return outcomes;
}
References action, open_spiel::crowd_modelling_2d::kNeutralAction, and LegalPlayerActions().
Clone()
std::unique_ptr< State > open_spiel::crowd_modelling_2d::CrowdModelling2dState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 494 of file crowd_modelling_2d.cc.
{
  return std::unique_ptr<State>(new CrowdModelling2dState(*this));
}
References CrowdModelling2dState().
CurrentPlayer()
Player open_spiel::crowd_modelling_2d::CrowdModelling2dState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 114 of file crowd_modelling_2d.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DistributionSupport()
std::vector< std::string > open_spiel::crowd_modelling_2d::CrowdModelling2dState::DistributionSupport () override virtual
Reimplemented from open_spiel::State.
Definition at line 401 of file crowd_modelling_2d.cc.
{
  std::vector<std::string> support;
  support.reserve(size_ * size_);
  for (int x = 0; x < size_; ++x) {
    for (int y = 0; y < size_; ++y) {
      support.push_back(StateToString(x, y, t_, kMeanFieldPlayerId, false));
    }
  }
  return support;
}
References open_spiel::kMeanFieldPlayerId, StateToString(), x, and y.
DoApplyAction()
void open_spiel::crowd_modelling_2d::CrowdModelling2dState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 359 of file crowd_modelling_2d.cc.
{
  SPIEL_CHECK_NE(current_player_, kMeanFieldPlayerId);
  return_value_ += Rewards()[0];
  int xx;
  int yy;
  // Compute the next state
  if (is_chance_init_) {
    SPIEL_CHECK_GE(action, 0);
    SPIEL_CHECK_LT(action, (size_ * size_));
    SPIEL_CHECK_EQ(current_player_, kChancePlayerId);
    xx = GetX(action, size_);
    yy = GetY(action, size_);
    is_chance_init_ = false;
    current_player_ = 0;
  } else if (current_player_ == kChancePlayerId) {
    xx = (x_ + kActionToMoveX.at(action) + size_) % size_;
    yy = (y_ + kActionToMoveY.at(action) + size_) % size_;
    ++t_;
    current_player_ = kMeanFieldPlayerId;
  } else {
    SPIEL_CHECK_EQ(current_player_, 0);
    xx = (x_ + kActionToMoveX.at(action) + size_) % size_;
    yy = (y_ + kActionToMoveY.at(action) + size_) % size_;
    last_action_ = action;
    current_player_ = kChancePlayerId;
  }
  // Assign the new (x,y) position if it isn't forbidden.
  if (!IsForbiddenPosition(xx, yy) || is_chance_init_) {
    x_ = xx;
    y_ = yy;
  }
}
References action, IsForbiddenPosition(), open_spiel::kChancePlayerId, open_spiel::kMeanFieldPlayerId, Rewards(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and SPIEL_CHECK_NE.
InformationStateString()
std::string open_spiel::crowd_modelling_2d::CrowdModelling2dState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 459 of file crowd_modelling_2d.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsForbidden()
bool open_spiel::crowd_modelling_2d::CrowdModelling2dState::IsForbidden (Action action) const protected
Definition at line 344 of file crowd_modelling_2d.cc.
{
  int xx = (x_ + kActionToMoveX.at(action) + size_) % size_;
  int yy = (y_ + kActionToMoveY.at(action) + size_) % size_;
  return IsForbiddenPosition(xx, yy);
}
References action, and IsForbiddenPosition().
Referenced by LegalPlayerActions().
IsForbiddenPosition()
bool open_spiel::crowd_modelling_2d::CrowdModelling2dState::IsForbiddenPosition (int x, int y) const protected
Definition at line 350 of file crowd_modelling_2d.cc.
{
  for (const auto& forbidden_xy : forbidden_states_xy_) {
    if (x == forbidden_xy.first && y == forbidden_xy.second) {
      return true;
    }
  }
  return false;
}
References x, and y.
Referenced by DoApplyAction(), and IsForbidden().
IsTerminal()
bool open_spiel::crowd_modelling_2d::CrowdModelling2dState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 420 of file crowd_modelling_2d.cc.
{ return t_ >= horizon_; }
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::crowd_modelling_2d::CrowdModelling2dState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 314 of file crowd_modelling_2d.cc.
{
  if (IsTerminal()) return {};
  if (IsChanceNode()) return LegalChanceOutcomes();
  if (IsMeanFieldNode()) return {};
  SPIEL_CHECK_TRUE(IsPlayerNode());
  return LegalPlayerActions();
}
References open_spiel::State::IsChanceNode(), open_spiel::State::IsMeanFieldNode(), open_spiel::State::IsPlayerNode(), IsTerminal(), open_spiel::State::LegalChanceOutcomes(), LegalPlayerActions(), and SPIEL_CHECK_TRUE.
LegalPlayerActions()
std::vector< Action > open_spiel::crowd_modelling_2d::CrowdModelling2dState::LegalPlayerActions () const protected
Definition at line 303 of file crowd_modelling_2d.cc.
{
  std::vector<Action> legal_actions;
  legal_actions.reserve(kNumActions);
  for (Action action = 0; action < kNumActions; ++action) {
    if (!IsForbidden(action)) {
      legal_actions.push_back(action);
    }
  }
  return legal_actions;
}
References action, IsForbidden(), and open_spiel::crowd_modelling_2d::kNumActions.
Referenced by ChanceOutcomes(), and LegalActions().
ObservationString()
std::string open_spiel::crowd_modelling_2d::CrowdModelling2dState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 465 of file crowd_modelling_2d.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::crowd_modelling_2d::CrowdModelling2dState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 471 of file crowd_modelling_2d.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), 2 * size_ + horizon_ + 1);
  SPIEL_CHECK_LT(x_, size_);
  SPIEL_CHECK_LT(y_, size_);
  SPIEL_CHECK_GE(t_, 0);
  // Allow t_ == horizon_.
  SPIEL_CHECK_LE(t_, horizon_);
  std::fill(values.begin(), values.end(), 0.);
  if (x_ >= 0 && y_ >= 0) {
    values[x_] = 1.;
    values[y_ + size_] = 1.;
  } else {
    // x_ and y_ equal -1 for the initial (blank) state, don't set any position
    // bit in that case.
    SPIEL_CHECK_EQ(x_, -1);
    SPIEL_CHECK_EQ(y_, -1);
  }
  values[2 * size_ + t_] = 1.;
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, and values.
operator=()
CrowdModelling2dState & open_spiel::crowd_modelling_2d::CrowdModelling2dState::operator= (const CrowdModelling2dState &) default
Returns()
std::vector< double > open_spiel::crowd_modelling_2d::CrowdModelling2dState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 451 of file crowd_modelling_2d.cc.
{
  return {return_value_ + Rewards()[0]};
}
References Rewards().
Rewards()
std::vector< double > open_spiel::crowd_modelling_2d::CrowdModelling2dState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 422 of file crowd_modelling_2d.cc.
{
  if (current_player_ != 0) {
    return {0.};
  }
  // Distribution-based reward
  double r_mu = -crowd_aversion_coef_ *
                std::log(distribution_[MergeXY(x_, y_, size_)] + kEpsilon);
  if (only_distribution_reward_) {
    return {r_mu};
  }
  // Positional reward
  double r_x = 1;
  double r_y = 1;
  for (int i = 0; i < positional_reward_xy_.size(); ++i) {
    double val_r = 2.0 * positional_reward_value_[i] / size_;
    r_x -= val_r * std::abs(x_ - positional_reward_xy_[i].first);
    r_y -= val_r * std::abs(y_ - positional_reward_xy_[i].second);
  }
  double r_a = -1.0 *
               (std::abs(kActionToMoveX.at(last_action_)) +
                std::abs(kActionToMoveY.at(last_action_))) /
               size_;
  if (with_congestion_) {
    // Congestion effect: higher penalty when moving in a high-density area
    r_a *= distribution_[MergeXY(x_, y_, size_)];
  }
  return {r_x + r_y + r_a + r_mu};
}
References first, and i.
Referenced by DoApplyAction(), and Returns().
Serialize()
std::string open_spiel::crowd_modelling_2d::CrowdModelling2dState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 498 of file crowd_modelling_2d.cc.
{
  std::string out =
      absl::StrCat(current_player_, ",", is_chance_init_, ",", x_, ",", y_, ",",
                   t_, ",", last_action_, ",", return_value_, "\n");
  absl::StrAppend(&out, absl::StrJoin(distribution_, ","));
  return out;
}
References out, absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
ToString()
std::string open_spiel::crowd_modelling_2d::CrowdModelling2dState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 455 of file crowd_modelling_2d.cc.
{
  return StateToString(x_, y_, t_, current_player_, is_chance_init_);
}
References StateToString().
Referenced by ObservationString().
UpdateDistribution()
void open_spiel::crowd_modelling_2d::CrowdModelling2dState::UpdateDistribution (const std::vector< double > & distribution) override virtual
Reimplemented from open_spiel::State.
Definition at line 412 of file crowd_modelling_2d.cc.
{
  SPIEL_CHECK_EQ(current_player_, kMeanFieldPlayerId);
  SPIEL_CHECK_EQ(distribution.size(), size_ * size_);
  distribution_ = distribution;
  current_player_ = kDefaultPlayerId;
}
References open_spiel::kDefaultPlayerId, open_spiel::kMeanFieldPlayerId, and SPIEL_CHECK_EQ.
The documentation for this class was generated from the following files:
open_spiel/games/mfg/crowd_modelling_2d.h
open_spiel/games/mfg/crowd_modelling_2d.cc