open spiel: open_spiel::FileLogger Class Reference
open_spiel::FileLogger Class Reference
#include <logger.h>
Public Member Functions
FileLogger (const std::string &path, const std::string &name, const std::string &mode="w")
void Print (const std::string &str) override
~FileLogger () override
template<typename Arg1 , typename... Args>
void Print (const absl::FormatSpec< Arg1, Args... > &format, const Arg1 &arg1, const Args &... args)
Public Member Functions inherited from open_spiel::Logger
virtual ~Logger ()=default
template<typename Arg1 , typename... Args>
void Print (const absl::FormatSpec< Arg1, Args... > &format, const Arg1 &arg1, const Args &... args)
Detailed Description
Definition at line 43 of file logger.h.
Constructor & Destructor Documentation
FileLogger()
open_spiel::FileLogger::FileLogger (const std::string & path, const std::string & name, const std::string & mode = "w") inline
Definition at line 45 of file logger.h.
      : fd_(absl::StrFormat("%s/log-%s.txt", path, name), mode),
        tz_(absl::LocalTimeZone()) {
    Print("%s started", name);
  }
References name, and Print().
~FileLogger()
open_spiel::FileLogger::~FileLogger () inline override
Definition at line 60 of file logger.h.
{ Print("Closing the log."); }
References Print().
Member Function Documentation
Print() [1/2]
template<typename Arg1 , typename... Args> void open_spiel::Logger::Print (const absl::FormatSpec< Arg1, Args... > & format, const Arg1 & arg1, const Args &... args) inline
Definition at line 35 of file logger.h.
{
    Print(absl::StrFormat(format, arg1, args...));
  }
Print() [2/2]
void open_spiel::FileLogger::Print (const std::string & str) inline override virtual
Implements open_spiel::Logger.
Definition at line 53 of file logger.h.
{
    std::string time =
        absl::FormatTime("%Y-%m-%d %H:%M:%E3S", absl::Now(), tz_);
    fd_.Write(absl::StrFormat("[%s] %s\n", time, str));
    fd_.Flush();
  }
References open_spiel::file::File::Flush(), absl::FormatTime(), absl::Now(), absl::StrFormat(), and open_spiel::file::File::Write().
Referenced by open_spiel::algorithms::torch_az::evaluator(), FileLogger(), open_spiel::algorithms::torch_az::learner(), and ~FileLogger().
The documentation for this class was generated from the following file:
open_spiel/utils/logger.h