open spiel: absl::container_internal::btree< Params > Class Template Reference
absl::container_internal::btree< Params > Class Template Reference
#include <btree.h>
Public Types
using key_type = typename Params::key_type
using value_type = typename Params::value_type
using size_type = typename Params::size_type
using difference_type = typename Params::difference_type
using key_compare = typename Params::key_compare
using original_key_compare = typename Params::original_key_compare
using value_compare = typename Params::value_compare
using allocator_type = typename Params::allocator_type
using reference = typename Params::reference
using const_reference = typename Params::const_reference
using pointer = typename Params::pointer
using const_pointer = typename Params::const_pointer
using iterator
using const_iterator = typename iterator::const_iterator
using reverse_iterator = std::reverse_iterator<iterator>
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using node_handle_type = node_handle<Params, Params, allocator_type>
using params_type = Params
using slot_type = typename Params::slot_type
Public Member Functions
btree (const key_compare &comp, const allocator_type &alloc)
btree (const btree &other)
btree (const btree &other, const allocator_type &alloc)
btree (btree &&other) noexcept
btree (btree &&other, const allocator_type &alloc)
~btree ()
btree & operator= (const btree &other)
btree & operator= (btree &&other) noexcept
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
template<typename K >
iterator lower_bound (const K &key)
template<typename K >
const_iterator lower_bound (const K &key) const
template<typename K >
std::pair< iterator, bool > lower_bound_equal (const K &key) const
template<typename K >
iterator upper_bound (const K &key)
template<typename K >
const_iterator upper_bound (const K &key) const
template<typename K >
std::pair< iterator, iterator > equal_range (const K &key)
template<typename K >
std::pair< const_iterator, const_iterator > equal_range (const K &key) const
template<typename K , typename... Args>
std::pair< iterator, bool > insert_unique (const K &key, Args &&...args)
template<typename K , typename... Args>
std::pair< iterator, bool > insert_hint_unique (iterator position, const K &key, Args &&...args)
template<typename InputIterator , typename = decltype(std::declval<const key_compare &>()(params_type::key(*std::declval<InputIterator>()), std::declval<const key_type &>()))>
void insert_iterator_unique (InputIterator b, InputIterator e, int)
template<typename InputIterator >
void insert_iterator_unique (InputIterator b, InputIterator e, char)
template<typename ValueType >
iterator insert_multi (const key_type &key, ValueType &&v)
template<typename ValueType >
iterator insert_multi (ValueType &&v)
template<typename ValueType >
iterator insert_hint_multi (iterator position, ValueType &&v)
template<typename InputIterator >
void insert_iterator_multi (InputIterator b, InputIterator e)
iterator erase (iterator iter)
std::pair< size_type, iterator > erase_range (iterator begin, iterator end)
template<typename K >
iterator find (const K &key)
template<typename K >
const_iterator find (const K &key) const
void clear ()
void swap (btree &other)
const key_compare & key_comp () const noexcept
template<typename K1 , typename K2 >
bool compare_keys (const K1 &a, const K2 &b) const
value_compare value_comp () const
void verify () const
size_type size () const
size_type max_size () const
bool empty () const
size_type height () const
size_type leaf_nodes () const
size_type internal_nodes () const
size_type nodes () const
size_type bytes_used () const
double fullness () const
double overhead () const
allocator_type get_allocator () const
template<typename K >
auto lower_bound_equal (const K &key) const -> std::pair< iterator, bool >
template<typename K >
auto equal_range (const K &key) -> std::pair< iterator, iterator >
template<typename K , typename... Args>
auto insert_unique (const K &key, Args &&...args) -> std::pair< iterator, bool >
template<typename K , typename... Args>
auto insert_hint_unique (iterator position, const K &key, Args &&...args) -> std::pair< iterator, bool >
template<typename ValueType >
auto insert_multi (const key_type &key, ValueType &&v) -> iterator
template<typename ValueType >
auto insert_hint_multi (iterator position, ValueType &&v) -> iterator
template<typename... Args>
auto internal_emplace (iterator iter, Args &&...args) -> iterator
template<typename K >
auto internal_locate (const K &key) const -> SearchResult< iterator, is_key_compare_to::value >
template<typename K >
auto internal_lower_bound (const K &key) const -> SearchResult< iterator, is_key_compare_to::value >
template<typename K >
auto internal_upper_bound (const K &key) const -> iterator
template<typename K >
auto internal_find (const K &key) const -> iterator
Static Public Member Functions
static double average_bytes_per_value ()
Friends
struct btree_access
Detailed Description
template<typename Params>
class absl::container_internal::btree< Params >
Definition at line 1279 of file btree.h.
Member Typedef Documentation
allocator_type
template<typename Params > using absl::container_internal::btree< Params >::allocator_type = typename Params::allocator_type
Definition at line 1348 of file btree.h.
const_iterator
template<typename Params > using absl::container_internal::btree< Params >::const_iterator = typename iterator::const_iterator
Definition at line 1355 of file btree.h.
const_pointer
template<typename Params > using absl::container_internal::btree< Params >::const_pointer = typename Params::const_pointer
Definition at line 1352 of file btree.h.
const_reference
template<typename Params > using absl::container_internal::btree< Params >::const_reference = typename Params::const_reference
Definition at line 1350 of file btree.h.
const_reverse_iterator
template<typename Params > using absl::container_internal::btree< Params >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 1357 of file btree.h.
difference_type
template<typename Params > using absl::container_internal::btree< Params >::difference_type = typename Params::difference_type
Definition at line 1344 of file btree.h.
iterator
template<typename Params > using absl::container_internal::btree< Params >::iterator
Initial value:
      typename btree_iterator<node_type, reference, pointer>::iterator
Definition at line 1353 of file btree.h.
key_compare
template<typename Params > using absl::container_internal::btree< Params >::key_compare = typename Params::key_compare
Definition at line 1345 of file btree.h.
key_type
template<typename Params > using absl::container_internal::btree< Params >::key_type = typename Params::key_type
Definition at line 1341 of file btree.h.
node_handle_type
template<typename Params > using absl::container_internal::btree< Params >::node_handle_type = node_handle<Params, Params, allocator_type>
Definition at line 1358 of file btree.h.
original_key_compare
template<typename Params > using absl::container_internal::btree< Params >::original_key_compare = typename Params::original_key_compare
Definition at line 1346 of file btree.h.
params_type
template<typename Params > using absl::container_internal::btree< Params >::params_type = Params
Definition at line 1361 of file btree.h.
pointer
template<typename Params > using absl::container_internal::btree< Params >::pointer = typename Params::pointer
Definition at line 1351 of file btree.h.
reference
template<typename Params > using absl::container_internal::btree< Params >::reference = typename Params::reference
Definition at line 1349 of file btree.h.
reverse_iterator
template<typename Params > using absl::container_internal::btree< Params >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 1356 of file btree.h.
size_type
template<typename Params > using absl::container_internal::btree< Params >::size_type = typename Params::size_type
Definition at line 1343 of file btree.h.
slot_type
template<typename Params > using absl::container_internal::btree< Params >::slot_type = typename Params::slot_type
Definition at line 1362 of file btree.h.
value_compare
template<typename Params > using absl::container_internal::btree< Params >::value_compare = typename Params::value_compare
Definition at line 1347 of file btree.h.
value_type
template<typename Params > using absl::container_internal::btree< Params >::value_type = typename Params::value_type
Definition at line 1342 of file btree.h.
Constructor & Destructor Documentation
btree() [1/5]
template<typename Params > absl::container_internal::btree< Params >::btree (const key_compare & comp, const allocator_type & alloc) inline
Definition at line 1376 of file btree.h.
      : root_(EmptyNode()), rightmost_(comp, alloc, EmptyNode()), size_(0) {}
btree() [2/5]
template<typename Params > absl::container_internal::btree< Params >::btree (const btree< Params > & other) inline
Definition at line 1379 of file btree.h.
: btree(other, other.allocator()) {}
btree() [3/5]
template<typename Params > absl::container_internal::btree< Params >::btree (const btree< Params > & other, const allocator_type & alloc) inline
Definition at line 1380 of file btree.h.
      : btree(other.key_comp(), alloc) {
    copy_or_move_values_in_order(other);
  }
btree() [4/5]
template<typename Params > absl::container_internal::btree< Params >::btree (btree< Params > && other) inline noexcept
Definition at line 1384 of file btree.h.
      : root_(absl::exchange(other.root_, EmptyNode())),
        rightmost_(std::move(other.rightmost_)),
        size_(absl::exchange(other.size_, 0u)) {
    other.mutable_rightmost() = EmptyNode();
  }
btree() [5/5]
template<typename Params > absl::container_internal::btree< Params >::btree (btree< Params > && other, const allocator_type & alloc) inline
Definition at line 1390 of file btree.h.
      : btree(other.key_comp(), alloc) {
    if (alloc == other.allocator()) {
      swap(other);
    } else {
      // Move values from `other` one at a time when allocators are different.
      copy_or_move_values_in_order(other);
    }
  }
~btree()
template<typename Params > absl::container_internal::btree< Params >::~btree () inline
Definition at line 1400 of file btree.h.
           {
    // Put static_asserts in destructor to avoid triggering them before the type
    // is complete.
    static_assert(static_assert_validation(), "This call must be elided.");
    clear();
  }
Member Function Documentation
average_bytes_per_value()
template<typename Params > static double absl::container_internal::btree< Params >::average_bytes_per_value () inline static
Definition at line 1600 of file btree.h.
{
    // The expected number of values per node with random insertion order is the
    // average of the maximum and minimum numbers of values per node.
    const double expected_values_per_node = (kNodeSlots + kMinNodeValues) / 2.0;
    return node_type::LeafSize() / expected_values_per_node;
  }
begin() [1/2]
template<typename Params > iterator absl::container_internal::btree< Params >::begin () inline
Definition at line 1411 of file btree.h.
{ return iterator(leftmost()); }
begin() [2/2]
template<typename Params > const_iterator absl::container_internal::btree< Params >::begin () const inline
Definition at line 1412 of file btree.h.
{ return const_iterator(leftmost()); }
bytes_used()
template<typename Params > size_type absl::container_internal::btree< Params >::bytes_used () const inline
Definition at line 1588 of file btree.h.
{
    node_stats stats = internal_stats(root());
    if (stats.leaf_nodes == 1 && stats.internal_nodes == 0) {
      return sizeof(*this) + node_type::LeafSize(root()->max_count());
    } else {
      return sizeof(*this) + stats.leaf_nodes * node_type::LeafSize() +
             stats.internal_nodes * node_type::InternalSize();
    }
  }
clear()
template<typename P > void absl::container_internal::btree< P >::clear ()
Definition at line 2545 of file btree.h.
                     {
  if (!empty()) {
    node_type::clear_and_delete(root(), mutable_allocator());
  }
  mutable_root() = mutable_rightmost() = EmptyNode();
  size_ = 0;
}
compare_keys()
template<typename Params > template<typename K1 , typename K2 > bool absl::container_internal::btree< Params >::compare_keys (const K1 & a, const K2 & b) const inline
Definition at line 1543 of file btree.h.
{
    return compare_internal::compare_result_as_less_than(key_comp()(a, b));
  }
empty()
template<typename Params > bool absl::container_internal::btree< Params >::empty () const inline
Definition at line 1557 of file btree.h.
{ return size_ == 0; }
end() [1/2]
template<typename Params > iterator absl::container_internal::btree< Params >::end () inline
Definition at line 1413 of file btree.h.
{ return iterator(rightmost(), rightmost()->finish()); }
end() [2/2]
template<typename Params > const_iterator absl::container_internal::btree< Params >::end () const inline
Definition at line 1414 of file btree.h.
{
    return const_iterator(rightmost(), rightmost()->finish());
  }
equal_range() [1/3]
template<typename Params > template<typename K > std::pair< iterator, iterator > absl::container_internal::btree< Params >::equal_range (const K & key)
equal_range() [2/3]
template<typename Params > template<typename K > auto absl::container_internal::btree< Params >::equal_range (const K & key) -> std::pair<iterator, iterator>
Definition at line 2220 of file btree.h.
{
  const std::pair<iterator, bool> lower_and_equal = lower_bound_equal(key);
  const iterator lower = lower_and_equal.first;
  if (!lower_and_equal.second) {
    return {lower, lower};
  }
  const iterator next = std::next(lower);
  if (!params_type::template can_have_multiple_equivalent_keys<K>()) {
    // The next iterator after lower must point to a key greater than `key`.
    // Note: if this assert fails, then it may indicate that the comparator does
    // not meet the equivalence requirements for Compare
    // (see https://en.cppreference.com/w/cpp/named_req/Compare).
    assert(next == end() || compare_keys(key, next.key()));
    return {lower, next};
  }
  // Try once more to avoid the call to upper_bound() if there's only one
  // equivalent key. This should prevent all calls to upper_bound() in cases of
  // unique-containers with heterogeneous comparators in which all comparison
  // operators have the same equivalence classes.
  if (next == end() || compare_keys(key, next.key())) return {lower, next};
  // In this case, we need to call upper_bound() to avoid worst case O(N)
  // behavior if we were to iterate over equal keys.
  return {lower, upper_bound(key)};
}
equal_range() [3/3]
template<typename Params > template<typename K > std::pair< const_iterator, const_iterator > absl::container_internal::btree< Params >::equal_range (const K & key) const inline
Definition at line 1457 of file btree.h.
{
    return const_cast<btree *>(this)->equal_range(key);
  }
erase()
template<typename P > auto absl::container_internal::btree< P >::erase (iterator iter)
Definition at line 2411 of file btree.h.
{
  iter.node_->value_destroy(static_cast<field_type>(iter.position_),
                            mutable_allocator());
  iter.update_generation();
  const bool internal_delete = iter.node_->is_internal();
  if (internal_delete) {
    // Deletion of a value on an internal node. First, transfer the largest
    // value from our left child here, then erase/rebalance from that position.
    // We can get to the largest value from our left child by decrementing iter.
    iterator internal_iter(iter);
    --iter;
    assert(iter.node_->is_leaf());
    internal_iter.node_->transfer(
        static_cast<size_type>(internal_iter.position_),
        static_cast<size_type>(iter.position_), iter.node_,
        mutable_allocator());
  } else {
    // Shift values after erased position in leaf. In the internal case, we
    // don't need to do this because the leaf position is the end of the node.
    const field_type transfer_from =
        static_cast<field_type>(iter.position_ + 1);
    const field_type num_to_transfer = iter.node_->finish() - transfer_from;
    iter.node_->transfer_n(num_to_transfer,
                           static_cast<size_type>(iter.position_),
                           transfer_from, iter.node_, mutable_allocator());
  }
  // Update node finish and container size.
  iter.node_->set_finish(iter.node_->finish() - 1);
  --size_;
  // We want to return the next value after the one we just erased. If we
  // erased from an internal node (internal_delete == true), then the next
  // value is ++(++iter). If we erased from a leaf node (internal_delete ==
  // false) then the next value is ++iter. Note that ++iter may point to an
  // internal node and the value in the internal node may move to a leaf node
  // (iter.node_) when rebalancing is performed at the leaf level.
  iterator res = rebalance_after_delete(iter);
  // If we erased from an internal node, advance the iterator.
  if (internal_delete) {
    ++res;
  }
  return res;
}
erase_range()
template<typename P > auto absl::container_internal::btree< P >::erase_range (iterator begin, iterator end)
Definition at line 2500 of file btree.h.
{
  size_type count = static_cast<size_type>(end - begin);
  assert(count >= 0);
  if (count == 0) {
    return {0, begin};
  }
  if (static_cast<size_type>(count) == size_) {
    clear();
    return {count, this->end()};
  }
  if (begin.node_ == end.node_) {
    assert(end.position_ > begin.position_);
    begin.node_->remove_values(
        static_cast<field_type>(begin.position_),
        static_cast<field_type>(end.position_ - begin.position_),
        mutable_allocator());
    size_ -= count;
    return {count, rebalance_after_delete(begin)};
  }
  const size_type target_size = size_ - count;
  while (size_ > target_size) {
    if (begin.node_->is_leaf()) {
      const size_type remaining_to_erase = size_ - target_size;
      const size_type remaining_in_node =
          static_cast<size_type>(begin.node_->finish() - begin.position_);
      const field_type to_erase = static_cast<field_type>(
          (std::min)(remaining_to_erase, remaining_in_node));
      begin.node_->remove_values(static_cast<field_type>(begin.position_),
                                 to_erase, mutable_allocator());
      size_ -= to_erase;
      begin = rebalance_after_delete(begin);
    } else {
      begin = erase(begin);
    }
  }
  begin.update_generation();
  return {count, begin};
}
find() [1/2]
template<typename Params > template<typename K > iterator absl::container_internal::btree< Params >::find (const K & key) inline
Definition at line 1525 of file btree.h.
{
    return internal_end(internal_find(key));
  }
find() [2/2]
template<typename Params > template<typename K > const_iterator absl::container_internal::btree< Params >::find (const K & key) const inline
Definition at line 1529 of file btree.h.
{
    return internal_end(internal_find(key));
  }
fullness()
template<typename Params > double absl::container_internal::btree< Params >::fullness () const inline
Definition at line 1612 of file btree.h.
{
    if (empty()) return 0.0;
    return static_cast<double>(size()) / (nodes() * kNodeSlots);
  }
get_allocator()
template<typename Params > allocator_type absl::container_internal::btree< Params >::get_allocator () const inline
Definition at line 1627 of file btree.h.
{ return allocator(); }
height()
template<typename Params > size_type absl::container_internal::btree< Params >::height () const inline
Definition at line 1560 of file btree.h.
{
    size_type h = 0;
    if (!empty()) {
      // Count the length of the chain from the leftmost node up to the
      // root. We actually count from the root back around to the level below
      // the root, but the calculation is the same because of the circularity
      // of that traversal.
      const node_type *n = root();
      do {
        ++h;
        n = n->parent();
      } while (n != root());
    }
    return h;
  }
insert_hint_multi() [1/2]
template<typename Params > template<typename ValueType > iterator absl::container_internal::btree< Params >::insert_hint_multi (iterator position, ValueType && v)
insert_hint_multi() [2/2]
template<typename Params > template<typename ValueType > auto absl::container_internal::btree< Params >::insert_hint_multi (iterator position, ValueType && v) -> iterator
Definition at line 2334 of file btree.h.
{
  if (!empty()) {
    const key_type &key = params_type::key(v);
    if (position == end() || !compare_keys(position.key(), key)) {
      if (position == begin() ||
          !compare_keys(key, std::prev(position).key())) {
        // prev.key() <= key <= position.key()
        return internal_emplace(position, std::forward<ValueType>(v));
      }
    } else {
      ++position;
      if (position == end() || !compare_keys(position.key(), key)) {
        // {original `position`}.key() < key < {current `position`}.key()
        return internal_emplace(position, std::forward<ValueType>(v));
      }
    }
  }
  return insert_multi(std::forward<ValueType>(v));
}
insert_hint_unique() [1/2]
template<typename Params > template<typename K , typename... Args> std::pair< iterator, bool > absl::container_internal::btree< Params >::insert_hint_unique (iterator position, const K & key, Args &&... args)
insert_hint_unique() [2/2]
template<typename Params > template<typename K , typename... Args> auto absl::container_internal::btree< Params >::insert_hint_unique (iterator position, const K & key, Args &&... args) -> std::pair<iterator, bool> inline
Definition at line 2275 of file btree.h.
{
  if (!empty()) {
    if (position == end() || compare_keys(key, position.key())) {
      if (position == begin() || compare_keys(std::prev(position).key(), key)) {
        // prev.key() < key < position.key()
        return {internal_emplace(position, std::forward<Args>(args)...), true};
      }
    } else if (compare_keys(position.key(), key)) {
      ++position;
      if (position == end() || compare_keys(key, position.key())) {
        // {original `position`}.key() < key < {current `position`}.key()
        return {internal_emplace(position, std::forward<Args>(args)...), true};
      }
    } else {
      // position.key() == key
      return {position, false};
    }
  }
  return insert_unique(key, std::forward<Args>(args)...);
}
insert_iterator_multi()
template<typename P > template<typename InputIterator > void absl::container_internal::btree< P >::insert_iterator_multi (InputIterator b, InputIterator e)
Definition at line 2356 of file btree.h.
{
  for (; b != e; ++b) {
    insert_hint_multi(end(), *b);
  }
}
insert_iterator_unique() [1/2]
template<typename P > template<typename InputIterator > void absl::container_internal::btree< P >::insert_iterator_unique (InputIterator b, InputIterator e, char)
Definition at line 2308 of file btree.h.
{
  for (; b != e; ++b) {
    // Use a node handle to manage a temp slot.
    auto node_handle =
        CommonAccess::Construct<node_handle_type>(get_allocator(), *b);
    slot_type *slot = CommonAccess::GetSlot(node_handle);
    insert_hint_unique(end(), params_type::key(slot), slot);
  }
}
insert_iterator_unique() [2/2]
template<typename P > template<typename InputIterator , typename > void absl::container_internal::btree< P >::insert_iterator_unique (InputIterator b, InputIterator e, int)
Definition at line 2300 of file btree.h.
{
  for (; b != e; ++b) {
    insert_hint_unique(end(), params_type::key(*b), *b);
  }
}
insert_multi() [1/3]
template<typename Params > template<typename ValueType > iterator absl::container_internal::btree< Params >::insert_multi (const key_type & key, ValueType && v)
insert_multi() [2/3]
template<typename Params > template<typename ValueType > auto absl::container_internal::btree< Params >::insert_multi (const key_type & key, ValueType && v) -> iterator
Definition at line 2320 of file btree.h.
{
  if (empty()) {
    mutable_root() = mutable_rightmost() = new_leaf_root_node(1);
  }
  iterator iter = internal_upper_bound(key);
  if (iter.node_ == nullptr) {
    iter = end();
  }
  return internal_emplace(iter, std::forward<ValueType>(v));
}
insert_multi() [3/3]
template<typename Params > template<typename ValueType > iterator absl::container_internal::btree< Params >::insert_multi (ValueType && v) inline
Definition at line 1497 of file btree.h.
{
    return insert_multi(params_type::key(v), std::forward<ValueType>(v));
  }
insert_unique() [1/2]
template<typename Params > template<typename K , typename... Args> std::pair< iterator, bool > absl::container_internal::btree< Params >::insert_unique (const K & key, Args &&... args)
insert_unique() [2/2]
template<typename Params > template<typename K , typename... Args> auto absl::container_internal::btree< Params >::insert_unique (const K & key, Args &&... args) -> std::pair<iterator, bool>
Definition at line 2249 of file btree.h.
{
  if (empty()) {
    mutable_root() = mutable_rightmost() = new_leaf_root_node(1);
  }
  SearchResult<iterator, is_key_compare_to::value> res = internal_locate(key);
  iterator iter = res.value;
  if (res.HasMatch()) {
    if (res.IsEq()) {
      // The key already exists in the tree, do nothing.
      return {iter, false};
    }
  } else {
    iterator last = internal_last(iter);
    if (last.node_ && !compare_keys(key, last.key())) {
      // The key already exists in the tree, do nothing.
      return {last, false};
    }
  }
  return {internal_emplace(iter, std::forward<Args>(args)...), true};
}
internal_emplace()
template<typename Params > template<typename... Args> auto absl::container_internal::btree< Params >::internal_emplace (iterator iter, Args &&... args) -> iterator inline
Definition at line 2785 of file btree.h.
                {
  if (iter.node_->is_internal()) {
    // We can't insert on an internal node. Instead, we'll insert after the
    // previous value which is guaranteed to be on a leaf node.
    --iter;
    ++iter.position_;
  }
  const field_type max_count = iter.node_->max_count();
  allocator_type *alloc = mutable_allocator();
  if (iter.node_->count() == max_count) {
    // Make room in the leaf for the new item.
    if (max_count < kNodeSlots) {
      // Insertion into the root where the root is smaller than the full node
      // size. Simply grow the size of the root node.
      assert(iter.node_ == root());
      iter.node_ = new_leaf_root_node(static_cast<field_type>(
          (std::min)(static_cast<int>(kNodeSlots), 2 * max_count)));
      // Transfer the values from the old root to the new root.
      node_type *old_root = root();
      node_type *new_root = iter.node_;
      new_root->transfer_n(old_root->count(), new_root->start(),
                           old_root->start(), old_root, alloc);
      new_root->set_finish(old_root->finish());
      old_root->set_finish(old_root->start());
      new_root->set_generation(old_root->generation());
      node_type::clear_and_delete(old_root, alloc);
      mutable_root() = mutable_rightmost() = new_root;
    } else {
      rebalance_or_split(&iter);
    }
  }
  iter.node_->emplace_value(static_cast<field_type>(iter.position_), alloc,
                            std::forward<Args>(args)...);
  ++size_;
  iter.update_generation();
  return iter;
}
internal_find()
template<typename Params > template<typename K > auto absl::container_internal::btree< Params >::internal_find (const K & key) const -> iterator
Definition at line 2891 of file btree.h.
{
  SearchResult<iterator, is_key_compare_to::value> res = internal_locate(key);
  if (res.HasMatch()) {
    if (res.IsEq()) {
      return res.value;
    }
  } else {
    const iterator iter = internal_last(res.value);
    if (iter.node_ != nullptr && !compare_keys(key, iter.key())) {
      return iter;
    }
  }
  return {nullptr, 0};
}
internal_locate()
template<typename Params > template<typename K > auto absl::container_internal::btree< Params >::internal_locate (const K & key) const -> SearchResult<iterator, is_key_compare_to::value> inline
Definition at line 2826 of file btree.h.
{
  iterator iter(const_cast<node_type *>(root()));
  for (;;) {
    SearchResult<size_type, is_key_compare_to::value> res =
        iter.node_->lower_bound(key, key_comp());
    iter.position_ = static_cast<int>(res.value);
    if (res.IsEq()) {
      return {iter, MatchKind::kEq};
    }
    // Note: in the non-key-compare-to case, we don't need to walk all the way
    // down the tree if the keys are equal, but determining equality would
    // require doing an extra comparison on each node on the way down, and we
    // will need to go all the way to the leaf node in the expected case.
    if (iter.node_->is_leaf()) {
      break;
    }
    iter.node_ = iter.node_->child(static_cast<field_type>(iter.position_));
  }
  // Note: in the non-key-compare-to case, the key may actually be equivalent
  // here (and the MatchKind::kNe is ignored).
  return {iter, MatchKind::kNe};
}
internal_lower_bound()
template<typename Params > template<typename K > auto absl::container_internal::btree< Params >::internal_lower_bound (const K & key) const -> SearchResult<iterator, is_key_compare_to::value>
Definition at line 2852 of file btree.h.
{
  if (!params_type::template can_have_multiple_equivalent_keys<K>()) {
    SearchResult<iterator, is_key_compare_to::value> ret = internal_locate(key);
    ret.value = internal_last(ret.value);
    return ret;
  }
  iterator iter(const_cast<node_type *>(root()));
  SearchResult<size_type, is_key_compare_to::value> res;
  bool seen_eq = false;
  for (;;) {
    res = iter.node_->lower_bound(key, key_comp());
    iter.position_ = static_cast<int>(res.value);
    if (iter.node_->is_leaf()) {
      break;
    }
    seen_eq = seen_eq || res.IsEq();
    iter.node_ = iter.node_->child(static_cast<field_type>(iter.position_));
  }
  if (res.IsEq()) return {iter, MatchKind::kEq};
  return {internal_last(iter), seen_eq ? MatchKind::kEq : MatchKind::kNe};
}
internal_nodes()
template<typename Params > size_type absl::container_internal::btree< Params >::internal_nodes () const inline
Definition at line 1578 of file btree.h.
{
    return internal_stats(root()).internal_nodes;
  }
internal_upper_bound()
template<typename Params > template<typename K > auto absl::container_internal::btree< Params >::internal_upper_bound (const K & key) const -> iterator
Definition at line 2877 of file btree.h.
{
  iterator iter(const_cast<node_type *>(root()));
  for (;;) {
    iter.position_ = static_cast<int>(iter.node_->upper_bound(key, key_comp()));
    if (iter.node_->is_leaf()) {
      break;
    }
    iter.node_ = iter.node_->child(static_cast<field_type>(iter.position_));
  }
  return internal_last(iter);
}
key_comp()
template<typename Params > const key_compare & absl::container_internal::btree< Params >::key_comp () const inline noexcept
Definition at line 1539 of file btree.h.
{
    return rightmost_.template get<0>();
  }
leaf_nodes()
template<typename Params > size_type absl::container_internal::btree< Params >::leaf_nodes () const inline
Definition at line 1577 of file btree.h.
{ return internal_stats(root()).leaf_nodes; }
lower_bound() [1/2]
template<typename Params > template<typename K > iterator absl::container_internal::btree< Params >::lower_bound (const K & key) inline
Definition at line 1428 of file btree.h.
{
    return internal_end(internal_lower_bound(key).value);
  }
lower_bound() [2/2]
template<typename Params > template<typename K > const_iterator absl::container_internal::btree< Params >::lower_bound (const K & key) const inline
Definition at line 1432 of file btree.h.
{
    return internal_end(internal_lower_bound(key).value);
  }
lower_bound_equal() [1/2]
template<typename Params > template<typename K > std::pair< iterator, bool > absl::container_internal::btree< Params >::lower_bound_equal (const K & key) const
lower_bound_equal() [2/2]
template<typename Params > template<typename K > auto absl::container_internal::btree< Params >::lower_bound_equal (const K & key) const -> std::pair<iterator, bool>
Definition at line 2207 of file btree.h.
{
  const SearchResult<iterator, is_key_compare_to::value> res =
      internal_lower_bound(key);
  const iterator lower = iterator(internal_end(res.value));
  const bool equal = res.HasMatch()
                         ? res.IsEq()
                         : lower != end() && !compare_keys(key, lower.key());
  return {lower, equal};
}
max_size()
template<typename Params > size_type absl::container_internal::btree< Params >::max_size () const inline
Definition at line 1556 of file btree.h.
{ return (std::numeric_limits<size_type>::max)(); }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
nodes()
template<typename Params > size_type absl::container_internal::btree< Params >::nodes () const inline
Definition at line 1581 of file btree.h.
{
    node_stats stats = internal_stats(root());
    return stats.leaf_nodes + stats.internal_nodes;
  }
operator=() [1/2]
template<typename P > auto absl::container_internal::btree< P >::operator= (btree< Params > && other) noexcept
Definition at line 2379 of file btree.h.
{
  if (this != &other) {
    clear();
    using std::swap;
    if (absl::allocator_traits<
            allocator_type>::propagate_on_container_copy_assignment::value) {
      swap(root_, other.root_);
      // Note: `rightmost_` also contains the allocator and the key comparator.
      swap(rightmost_, other.rightmost_);
      swap(size_, other.size_);
    } else {
      if (allocator() == other.allocator()) {
        swap(mutable_root(), other.mutable_root());
        swap(*mutable_key_comp(), *other.mutable_key_comp());
        swap(mutable_rightmost(), other.mutable_rightmost());
        swap(size_, other.size_);
      } else {
        // We aren't allowed to propagate the allocator and the allocator is
        // different so we can't take over its memory. We must move each element
        // individually. We need both `other` and `this` to have `other`s key
        // comparator while moving the values so we can't swap the key
        // comparators.
        *mutable_key_comp() = other.key_comp();
        copy_or_move_values_in_order(other);
      }
    }
  }
  return *this;
}
operator=() [2/2]
template<typename P > auto absl::container_internal::btree< P >::operator= (const btree< Params > & other)
Definition at line 2363 of file btree.h.
{
  if (this != &other) {
    clear();
    *mutable_key_comp() = other.key_comp();
    if (absl::allocator_traits<
            allocator_type>::propagate_on_container_copy_assignment::value) {
      *mutable_allocator() = other.allocator();
    }
    copy_or_move_values_in_order(other);
  }
  return *this;
}
overhead()
template<typename Params > double absl::container_internal::btree< Params >::overhead () const inline
Definition at line 1620 of file btree.h.
{
    if (empty()) return 0.0;
    return (bytes_used() - size() * sizeof(value_type)) /
           static_cast<double>(size());
  }
rbegin() [1/2]
template<typename Params > reverse_iterator absl::container_internal::btree< Params >::rbegin () inline
Definition at line 1417 of file btree.h.
{ return reverse_iterator(end()); }
rbegin() [2/2]
template<typename Params > const_reverse_iterator absl::container_internal::btree< Params >::rbegin () const inline
Definition at line 1418 of file btree.h.
{
    return const_reverse_iterator(end());
  }
rend() [1/2]
template<typename Params > reverse_iterator absl::container_internal::btree< Params >::rend () inline
Definition at line 1421 of file btree.h.
{ return reverse_iterator(begin()); }
rend() [2/2]
template<typename Params > const_reverse_iterator absl::container_internal::btree< Params >::rend () const inline
Definition at line 1422 of file btree.h.
{
    return const_reverse_iterator(begin());
  }
size()
template<typename Params > size_type absl::container_internal::btree< Params >::size () const inline
Definition at line 1555 of file btree.h.
{ return size_; }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
swap()
template<typename P > void absl::container_internal::btree< P >::swap (btree< Params > & other)
Definition at line 2554 of file btree.h.
{
  using std::swap;
  if (absl::allocator_traits<
          allocator_type>::propagate_on_container_swap::value) {
    // Note: `rightmost_` also contains the allocator and the key comparator.
    swap(rightmost_, other.rightmost_);
  } else {
    // It's undefined behavior if the allocators are unequal here.
    assert(allocator() == other.allocator());
    swap(mutable_rightmost(), other.mutable_rightmost());
    swap(*mutable_key_comp(), *other.mutable_key_comp());
  }
  swap(mutable_root(), other.mutable_root());
  swap(size_, other.size_);
}
upper_bound() [1/2]
template<typename Params > template<typename K > iterator absl::container_internal::btree< Params >::upper_bound (const K & key) inline
Definition at line 1443 of file btree.h.
{
    return internal_end(internal_upper_bound(key));
  }
upper_bound() [2/2]
template<typename Params > template<typename K > const_iterator absl::container_internal::btree< Params >::upper_bound (const K & key) const inline
Definition at line 1447 of file btree.h.
{
    return internal_end(internal_upper_bound(key));
  }
value_comp()
template<typename Params > value_compare absl::container_internal::btree< Params >::value_comp () const inline
Definition at line 1547 of file btree.h.
{
    return value_compare(original_key_compare(key_comp()));
  }
verify()
template<typename P > void absl::container_internal::btree< P >::verify () const
Definition at line 2571 of file btree.h.
{
  assert(root() != nullptr);
  assert(leftmost() != nullptr);
  assert(rightmost() != nullptr);
  assert(empty() || size() == internal_verify(root(), nullptr, nullptr));
  assert(leftmost() == (++const_iterator(root(), -1)).node_);
  assert(rightmost() == (--const_iterator(root(), root()->finish())).node_);
  assert(leftmost()->is_leaf());
  assert(rightmost()->is_leaf());
}
Friends And Related Symbol Documentation
btree_access
template<typename Params > friend struct btree_access friend
Definition at line 1630 of file btree.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/btree.h