open spiel: open_spiel::SerializableCircularBuffer< T > Class Template Reference
open_spiel::SerializableCircularBuffer< T > Class Template Reference
#include <serializable_circular_buffer.h>
Public Member Functions
SerializableCircularBuffer (int max_size)
void SaveBuffer (const std::string &path) const
void LoadBuffer (const std::string &path)
Public Member Functions inherited from open_spiel::CircularBuffer< T >
CircularBuffer (int max_size)
void Add (const T &value)
std::vector< T > Sample (std::mt19937 *rng, int num)
const std::vector< T > & Data () const
const T & operator[] (int i) const
int Size () const
bool Empty () const
int64_t TotalAdded () const
Additional Inherited Members
Protected Attributes inherited from open_spiel::CircularBuffer< T >
const int max_size_
int64_t total_added_
std::vector< T > data_
Detailed Description
template<class T>
class open_spiel::SerializableCircularBuffer< T >
Definition at line 36 of file serializable_circular_buffer.h.
Constructor & Destructor Documentation
SerializableCircularBuffer()
template<class T > open_spiel::SerializableCircularBuffer< T >::SerializableCircularBuffer (int max_size) inline explicit
Definition at line 38 of file serializable_circular_buffer.h.
      : CircularBuffer<T>(max_size) {}
Member Function Documentation
LoadBuffer()
template<class T > void open_spiel::SerializableCircularBuffer< T >::LoadBuffer (const std::string & path) inline
Definition at line 50 of file serializable_circular_buffer.h.
{
    nop::Deserializer<nop::StreamReader<std::ifstream>> deserializer{path};
    // Ensure this buffer's max size equals the max size of the saved buffer.
    int max_size;
    deserializer.Read(&max_size);
    if (max_size != this->max_size_) {
      SpielFatalError(absl::StrFormat("Cannot load data from a buffer with max"
                                      "size %d into a buffer with max size %d.",
                                      max_size,
                                      this->max_size_));
    }
    deserializer.Read(&(this->total_added_));
    deserializer.Read(&(this->data_));
  }
References open_spiel::CircularBuffer< T >::data_, open_spiel::CircularBuffer< T >::max_size_, open_spiel::SpielFatalError(), absl::StrFormat(), and open_spiel::CircularBuffer< T >::total_added_.
Referenced by open_spiel::algorithms::torch_az::learner().
SaveBuffer()
template<class T > void open_spiel::SerializableCircularBuffer< T >::SaveBuffer (const std::string & path) const inline
Definition at line 42 of file serializable_circular_buffer.h.
{
    nop::Serializer<nop::StreamWriter<std::ofstream>> serializer{path};
    serializer.Write(this->max_size_);
    serializer.Write(this->total_added_);
    serializer.Write(this->data_);
  }
References open_spiel::CircularBuffer< T >::data_, open_spiel::CircularBuffer< T >::max_size_, and open_spiel::CircularBuffer< T >::total_added_.
Referenced by open_spiel::algorithms::torch_az::learner().
The documentation for this class was generated from the following file:
open_spiel/utils/serializable_circular_buffer.h