open spiel: absl::cord_internal::RefcountAndFlags Class Reference
absl::cord_internal::RefcountAndFlags Class Reference
#include <cord_internal.h>
Classes
struct Immortal
Public Member Functions
constexpr RefcountAndFlags ()
constexpr RefcountAndFlags (Immortal)
void Increment ()
bool Decrement ()
bool DecrementExpectHighRefcount ()
size_t Get () const
bool IsOne ()
bool IsImmortal () const
Detailed Description
Definition at line 147 of file cord_internal.h.
Constructor & Destructor Documentation
RefcountAndFlags() [1/2]
absl::cord_internal::RefcountAndFlags::RefcountAndFlags () inline constexpr
Definition at line 149 of file cord_internal.h.
: count_{kRefIncrement} {}
RefcountAndFlags() [2/2]
absl::cord_internal::RefcountAndFlags::RefcountAndFlags (Immortal) inline explicit constexpr
Definition at line 151 of file cord_internal.h.
: count_(kImmortalFlag) {}
Member Function Documentation
Decrement()
bool absl::cord_internal::RefcountAndFlags::Decrement () inline
Definition at line 165 of file cord_internal.h.
{
    int32_t refcount = count_.load(std::memory_order_acquire) & kRefcountMask;
    assert(refcount > 0 || refcount & kImmortalFlag);
    return refcount != kRefIncrement &&
           (count_.fetch_sub(kRefIncrement, std::memory_order_acq_rel) &
            kRefcountMask) != kRefIncrement;
  }
References refcount.
DecrementExpectHighRefcount()
bool absl::cord_internal::RefcountAndFlags::DecrementExpectHighRefcount () inline
Definition at line 174 of file cord_internal.h.
{
    int32_t refcount =
        count_.fetch_sub(kRefIncrement, std::memory_order_acq_rel) &
        kRefcountMask;
    assert(refcount > 0 || refcount & kImmortalFlag);
    return refcount != kRefIncrement;
  }
References refcount.
Get()
size_t absl::cord_internal::RefcountAndFlags::Get () const inline
Definition at line 183 of file cord_internal.h.
{
    return static_cast<size_t>(count_.load(std::memory_order_acquire) >>
                               kNumFlags);
  }
Increment()
void absl::cord_internal::RefcountAndFlags::Increment () inline
Definition at line 154 of file cord_internal.h.
{
    count_.fetch_add(kRefIncrement, std::memory_order_relaxed);
  }
IsImmortal()
bool absl::cord_internal::RefcountAndFlags::IsImmortal () const inline
Definition at line 201 of file cord_internal.h.
{
    return (count_.load(std::memory_order_relaxed) & kImmortalFlag) != 0;
  }
IsOne()
bool absl::cord_internal::RefcountAndFlags::IsOne () inline
Definition at line 196 of file cord_internal.h.
                      {
    return (count_.load(std::memory_order_acquire) & kRefcountMask) ==
           kRefIncrement;
  }
Referenced by absl::cord_internal::CordRepBtree::ExtractAppendBuffer(), absl::cord_internal::CordRepBtree::GetAppendBuffer(), absl::cord_internal::CordRepCrc::New(), absl::Cord::operator=(), absl::cord_internal::RemoveCrcNode(), absl::Cord::RemovePrefix(), absl::Cord::RemoveSuffix(), and absl::cord_internal::CordRepBtree::RemoveSuffix().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/cord_internal.h