open spiel: open_spiel::algorithms::torch_az::VPNetModel Class Reference
open_spiel::algorithms::torch_az::VPNetModel Class Reference
#include <vpnet.h>
Classes
struct InferenceInputs
struct InferenceOutputs
class LossInfo
struct TrainInputs
Public Types
enum CheckpointStep { kMostRecentCheckpointStep = -1 , kInvalidCheckpointStep = -2 }
Public Member Functions
VPNetModel (const Game &game, const std::string &path, const std::string &file_name, const std::string &device="/cpu:0")
VPNetModel (VPNetModel &&other)=default
VPNetModel & operator= (VPNetModel &&other)=default
VPNetModel (const VPNetModel &)=delete
VPNetModel & operator= (const VPNetModel &)=delete
std::vector< InferenceOutputs > Inference (const std::vector< InferenceInputs > &inputs)
LossInfo Learn (const std::vector< TrainInputs > &inputs)
std::string SaveCheckpoint (int step)
void LoadCheckpoint (int step)
void LoadCheckpoint (const std::string &path)
const std::string Device () const
Detailed Description
Definition at line 38 of file vpnet.h.
Member Enumeration Documentation
CheckpointStep
enum open_spiel::algorithms::torch_az::VPNetModel::CheckpointStep
Enumerator
kMostRecentCheckpointStep
kInvalidCheckpointStep
Definition at line 101 of file vpnet.h.
                      {
    kMostRecentCheckpointStep = -1,
    kInvalidCheckpointStep = -2
  };
Constructor & Destructor Documentation
VPNetModel() [1/3]
open_spiel::algorithms::torch_az::VPNetModel::VPNetModel (const Game & game, const std::string & path, const std::string & file_name, const std::string & device = "/cpu:0")
Definition at line 111 of file vpnet.cc.
    : device_(device), path_(path),
      flat_input_size_(game.ObservationTensorSize()),
      num_actions_(game.NumDistinctActions()),
      model_config_(LoadModelConfig(path, file_name)),
      torch_device_(TorchDeviceName(device)),
      model_(model_config_, TorchDeviceName(device)),
      model_optimizer_(model_->parameters(),
                       torch::optim::AdamOptions(model_config_.learning_rate)) {
  // Some assumptions that we can remove eventually. The value net returns
  // a single value in terms of player 0 and the game is assumed to be zero-sum,
  // so player 1 can just be -value.
  SPIEL_CHECK_EQ(game.NumPlayers(), 2);
  SPIEL_CHECK_EQ(game.GetType().utility, GameType::Utility::kZeroSum);
  // Put this model on the specified device.
  model_->to(torch_device_);
}
References open_spiel::GameType::kZeroSum, and SPIEL_CHECK_EQ.
VPNetModel() [2/3]
open_spiel::algorithms::torch_az::VPNetModel::VPNetModel (VPNetModel && other) default
VPNetModel() [3/3]
open_spiel::algorithms::torch_az::VPNetModel::VPNetModel (const VPNetModel &) delete
Member Function Documentation
Device()
const std::string open_spiel::algorithms::torch_az::VPNetModel::Device () const inline
Definition at line 127 of file vpnet.h.
{ return device_; }
Referenced by open_spiel::algorithms::torch_az::learner().
Inference()
std::vector< VPNetModel::InferenceOutputs > open_spiel::algorithms::torch_az::VPNetModel::Inference (const std::vector< InferenceInputs > & inputs)
Definition at line 151 of file vpnet.cc.
{
  int inference_batch_size = inputs.size();
  // Torch tensors by default use a dense, row-aligned memory layout.
  //   - Their default data type is a 32-bit float
  //   - Use the byte data type for boolean
  torch::Tensor torch_inf_inputs =
      torch::empty({inference_batch_size, flat_input_size_}, torch_device_);
  torch::Tensor torch_inf_legal_mask = torch::full(
      {inference_batch_size, num_actions_}, false,
      torch::TensorOptions().dtype(torch::kByte).device(torch_device_));
  for (int batch = 0; batch < inference_batch_size; ++batch) {
    // Copy legal mask(s) to a Torch tensor.
    for (Action action : inputs[batch].legal_actions) {
      torch_inf_legal_mask[batch][action] = true;
    }
    // Copy the observation(s) to a Torch tensor.
    for (int i = 0; i < inputs[batch].observations.size(); ++i) {
      torch_inf_inputs[batch][i] = inputs[batch].observations[i];
    }
  }
  // Run the inference.
  model_->eval();
  std::vector<torch::Tensor> torch_outputs =
      model_(torch_inf_inputs, torch_inf_legal_mask);
  torch::Tensor value_batch = torch_outputs[0];
  torch::Tensor policy_batch = torch_outputs[1];
  // Copy the Torch tensor output to the appropriate structure.
  std::vector<InferenceOutputs> output;
  output.reserve(inference_batch_size);
  for (int batch = 0; batch < inference_batch_size; ++batch) {
    double value = value_batch[batch].item<double>();
    ActionsAndProbs state_policy;
    state_policy.reserve(inputs[batch].legal_actions.size());
    for (Action action : inputs[batch].legal_actions) {
      state_policy.push_back(
          {action, policy_batch[batch][action].item<float>()});
    }
    output.push_back({value, state_policy});
  }
  return output;
}
References action, i, and value.
Learn()
VPNetModel::LossInfo open_spiel::algorithms::torch_az::VPNetModel::Learn (const std::vector< TrainInputs > & inputs)
Definition at line 204 of file vpnet.cc.
{
  int training_batch_size = inputs.size();
  // Torch tensors by default use a dense, row-aligned memory layout.
  //   - Their default data type is a 32-bit float
  //   - Use the byte data type for boolean
  torch::Tensor torch_train_inputs =
      torch::empty({training_batch_size, flat_input_size_}, torch_device_);
  torch::Tensor torch_train_legal_mask = torch::full(
      {training_batch_size, num_actions_}, false,
      torch::TensorOptions().dtype(torch::kByte).device(torch_device_));
  torch::Tensor torch_policy_targets =
      torch::zeros({training_batch_size, num_actions_}, torch_device_);
  torch::Tensor torch_value_targets =
      torch::empty({training_batch_size, 1}, torch_device_);
  for (int batch = 0; batch < training_batch_size; ++batch) {
    // Copy the legal mask(s) to a Torch tensor.
    for (Action action : inputs[batch].legal_actions) {
      torch_train_legal_mask[batch][action] = true;
    }
    // Copy the observation(s) to a Torch tensor.
    for (int i = 0; i < inputs[batch].observations.size(); ++i) {
      torch_train_inputs[batch][i] = inputs[batch].observations[i];
    }
    // Copy the policy target(s) to a Torch tensor.
    for (const auto& [action, probability] : inputs[batch].policy) {
      torch_policy_targets[batch][action] = probability;
    }
    // Copy the value target(s) to a Torch tensor.
    torch_value_targets[batch][0] = inputs[batch].value;
  }
  // Run a training step and get the losses.
  model_->train();
  model_->zero_grad();
  std::vector<torch::Tensor> torch_outputs =
      model_->losses(torch_train_inputs, torch_train_legal_mask,
                     torch_policy_targets, torch_value_targets);
  torch::Tensor total_loss =
      torch_outputs[0] + torch_outputs[1] + torch_outputs[2];
  total_loss.backward();
  model_optimizer_.step();
  return LossInfo(torch_outputs[0].item<float>(),
                  torch_outputs[1].item<float>(),
                  torch_outputs[2].item<float>());
}
References action, and i.
Referenced by open_spiel::algorithms::torch_az::learner().
LoadCheckpoint() [1/2]
void open_spiel::algorithms::torch_az::VPNetModel::LoadCheckpoint (const std::string & path)
Definition at line 145 of file vpnet.cc.
{
  torch::load(model_, absl::StrCat(path, ".pt"), torch_device_);
  torch::load(model_optimizer_, absl::StrCat(path, "-optimizer.pt"),
              torch_device_);
}
References absl::StrCat().
LoadCheckpoint() [2/2]
void open_spiel::algorithms::torch_az::VPNetModel::LoadCheckpoint (int step)
Definition at line 140 of file vpnet.cc.
{
  // Load checkpoint from the path given at its initialization.
  LoadCheckpoint(absl::StrCat(path_, "/checkpoint-", step));
}
References LoadCheckpoint(), and absl::StrCat().
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), open_spiel::algorithms::torch_az::learner(), LoadCheckpoint(), and main().
operator=() [1/2]
VPNetModel & open_spiel::algorithms::torch_az::VPNetModel::operator= (const VPNetModel &) delete
operator=() [2/2]
VPNetModel & open_spiel::algorithms::torch_az::VPNetModel::operator= (VPNetModel && other) default
SaveCheckpoint()
std::string open_spiel::algorithms::torch_az::VPNetModel::SaveCheckpoint (int step)
Definition at line 131 of file vpnet.cc.
{
  std::string full_path = absl::StrCat(path_, "/checkpoint-", step);
  torch::save(model_, absl::StrCat(full_path, ".pt"));
  torch::save(model_optimizer_, absl::StrCat(full_path, "-optimizer.pt"));
  return full_path;
}
References absl::StrCat().
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), and open_spiel::algorithms::torch_az::learner().
The documentation for this class was generated from the following files:
open_spiel/algorithms/alpha_zero_torch/vpnet.h
open_spiel/algorithms/alpha_zero_torch/vpnet.cc