open spiel: open_spiel::kbg::kbgState Class Reference
open_spiel::kbg::kbgState Class Reference
#include <ki_bo_gung.h>
Public Member Functions
kbgState (std::shared_ptr< const Game > game)
kbgState (const kbgState &)=default
virtual ~kbgState ()
kbgState & operator= (const kbgState &)=default
void init_map () override
맵을 생성한다. 타일을 깔아야 한다.
void init_unit () override
말을 생성하고 배치한다.
Public Member Functions inherited from open_spiel::baseT::baseTState
baseTState (std::shared_ptr< const Game > game)
baseTState (const baseTState &)=default
virtual ~baseTState ()
virtual baseTState & operator= (const baseTState &)=default
virtual std::string ActionToString (Player player, Action action_id) const override
virtual Player CurrentPlayer () const override
virtual bool IsTerminal () const override
virtual std::vector< Action > LegalActions () const override
virtual std::vector< double > Returns () const
virtual std::string ToString () const override
virtual std::unique_ptr< State > Clone () const override
virtual std::string ObservationString (Player player) const override
virtual void set_next_unit_to_action ()
void deploy_unit (int player_id, bool is_alive, int shift_dstc, int atk_dstc, int vw_dstc, float hp, float power, UnitClass unit_class, MapCoord crd, std::string name)
UnitActionState CurrentUAS () const
PlayerActionState CurrentPAS () const
int CurrentUniqueUnitId () const
int CurrentUnitId () const
void SetNextUAS ()
void SetNextPAS ()
void SetNextPlayer ()
void ObservationTensorBaseT (Player player)
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::baseT::baseTState
virtual void DoApplyAction (Action move) override
virtual int action_select_tile (int pn, int unit_id, MapCoord tg_crd, bool is_init)
virtual void scout (int pn, int unit_id, ObsRefCount o_r_c)
virtual void init_first (int max_u, int piece_tn, int last_mn, int supply_n, int land_channel_d, UnitSelectionOrder uso, MapCoord ms, UnitActionKind game_uak)
virtual std::string get_cell_observation_string (MapState state, MapCoord crd, int p) const
virtual std::string get_set_error (std::string log, bool is_save)
virtual MapCoord id_to_crd (Action a)
virtual Action crd_to_id (MapCoord crd)
int ObservationTensorBaseT_Land (Player player, int last_index)
virtual void set_next_unit_to_action_rand_all_p ()
virtual void set_next_unit_to_action_rand_per_p ()
Unit & get_unit_by_uniqueId (int unique_id)
virtual void ObservationTensor (Player player, absl::Span< float > values) const
void set_cell_and_obs (struct Cell_set_flags flags, struct Cell cell, struct MapCoord crd, int player_n, int8_t ref_c, struct scout_info sc_info)
void cells_to_obs ()
int is_watched_by_others (Player player, std::vector< int8_t > &being_observed_by)
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes inherited from open_spiel::baseT::baseTState
MapCoord map_size
MapState msn
std::vector< MapState > Map_history
int max_units
std::vector< int8_t > unit_id_count
int unique_unit_id_count
std::vector< std::vector< int8_t > > turn_unit_per_p_v
std::vector< int8_t > turn_unit_all_p_v
PlayerActionState current_pas
UnitSelectionOrder unit_selection_order
int ground_type_num
int land_info_channel_depth
int piece_type_n
std::vector< std::vector< std::vector< std::vector< std::vector< int8_t > > > > > obs_per_p_v
int obs_total_channel_depth
int last_move_len
std::vector< FP16 > supply_v
std::vector< P_UnitId > unique_id_to_player_id_v
enum UnitActionKind game_uak
std::unique_ptr< SocketServer > ipc_server
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 53 of file ki_bo_gung.h.
Constructor & Destructor Documentation
kbgState() [1/2]
open_spiel::kbg::kbgState::kbgState (std::shared_ptr< const Game > game)
Definition at line 55 of file ki_bo_gung.cc.
                                                 : baseTState(game)
{
  //무조건 맨 처음에 불러줘야 함
  // max_unit=4, piece_type_n=3, last_m=5, supply=20, land_c=3
  init_first(4, 3, 5, 20, 3, USO_ALL_P_RAND,{1,10,10},UA_Kind_1step);
}
References open_spiel::baseT::baseTState::init_first(), open_spiel::baseT::UA_Kind_1step, and open_spiel::baseT::USO_ALL_P_RAND.
kbgState() [2/2]
open_spiel::kbg::kbgState::kbgState (const kbgState &) default
~kbgState()
open_spiel::kbg::kbgState::~kbgState () virtual
Definition at line 62 of file ki_bo_gung.cc.
{
}
Member Function Documentation
init_map()
void open_spiel::kbg::kbgState::init_map () override virtual
맵을 생성한다. 타일을 깔아야 한다.
Reimplemented from open_spiel::baseT::baseTState.
Definition at line 77 of file ki_bo_gung.cc.
{
  /* 10X10 맵에서 가운데에 1X4 호수가 있다.  */
  // 비어있는 관찰자 벡터
  std::vector<int8_t> obp(num_players_, 0);
  // 2. 맵 만들기. 3차원 이므로 1차원부터 만들어서 삽입해야 한다.
  // [z][row][col]
  //init_cells_and_obs();
  // 호수 만들기
  Cell water_ground = {GT_CannotEnter, PNone, UNone, UNone, obp};
  //msn.cells_v[0][4][3] = water_ground;
  //msn.cells_v[0][4][4] = water_ground;
  //msn.cells_v[0][4][5] = water_ground;
  //msn.cells_v[0][5][3] = water_ground;
  //msn.cells_v[0][5][4] = water_ground;
  //msn.cells_v[0][5][5] = water_ground;
  set_cell_and_obs({1,1,1,1,1},water_ground,{0,4,3},-1,-1,{false,-1,-1,ObsRefNone});
  set_cell_and_obs({1,1,1,1,1},water_ground,{0,4,4},-1,-1,{false,-1,-1,ObsRefNone});
  set_cell_and_obs({1,1,1,1,1},water_ground,{0,4,5},-1,-1,{false,-1,-1,ObsRefNone});
  set_cell_and_obs({1,1,1,1,1},water_ground,{0,5,3},-1,-1,{false,-1,-1,ObsRefNone});
  set_cell_and_obs({1,1,1,1,1},water_ground,{0,5,4},-1,-1,{false,-1,-1,ObsRefNone});
  set_cell_and_obs({1,1,1,1,1},water_ground,{0,5,5},-1,-1,{false,-1,-1,ObsRefNone});
}
References open_spiel::baseT::GT_CannotEnter, open_spiel::State::num_players_, open_spiel::baseT::ObsRefNone, open_spiel::baseT::PNone, open_spiel::baseT::baseTState::set_cell_and_obs(), and open_spiel::baseT::UNone.
init_unit()
void open_spiel::kbg::kbgState::init_unit () override virtual
말을 생성하고 배치한다.
Reimplemented from open_spiel::baseT::baseTState.
Definition at line 110 of file ki_bo_gung.cc.
{
  std::vector<int8_t> empty_v(num_players_, 0);
  // kind ki:0 bo:1 gung:2s
  // live. id 0, 이거 2, 공거 1, 시야 4, 체 1, 공 1, class 0, p 0, crd , drc, pb, name
  // live. id 0, 이거 1, 공거 1, 시야 4, 체 2, 공 1
  // live. id 0, 이거 1, 공거 2, 시야 4, 체 1, 공 1
  //P0 units
  deploy_unit(0,true, 2, 1, 4, 1, 1, C0, {0,8,5}, "ki");
  deploy_unit(0,true, 1, 1, 4, 2, 1, C1, {0,8,4}, "bo");
  deploy_unit(0,true, 1, 1, 4, 2, 1, C1, {0,8,3}, "bo");
  deploy_unit(0,true, 1, 2, 4, 1, 1, C2, {0,9,4}, "gu");
  //P1 units
  deploy_unit(1, true, 2, 1, 4, 1, 1, C0, {0,1,5}, "ki");
  deploy_unit(1, true, 1, 1, 4, 2, 1, C1, {0,1,4}, "bo");
  deploy_unit(1, true, 1, 1, 4, 2, 1, C1, {0,1,3}, "bo");
  deploy_unit(1, true, 1, 2, 4, 1, 1, C2, {0,0,4}, "gu");
}
References open_spiel::baseT::C0, open_spiel::baseT::C1, open_spiel::baseT::C2, open_spiel::baseT::baseTState::deploy_unit(), and open_spiel::State::num_players_.
operator=()
kbgState & open_spiel::kbg::kbgState::operator= (const kbgState &) default
The documentation for this class was generated from the following files:
open_spiel/games/SG/ki_bo_gung.h
open_spiel/games/SG/ki_bo_gung.cc