open spiel: open_spiel::algorithms::ExplorativeSamplingPolicy Class Reference
open_spiel::algorithms::ExplorativeSamplingPolicy Class Reference
#include <oos.h>
Public Member Functions
ExplorativeSamplingPolicy (const OOSInfoStateValuesTable &table, double exploration=kDefaultExploration)
ActionsAndProbs GetStatePolicy (const State &state) const override
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
Public Member Functions inherited from open_spiel::algorithms::CFRCurrentPolicy
CFRCurrentPolicy (const CFRInfoStateValuesTable &info_states, std::shared_ptr< Policy > default_policy)
ActionsAndProbs GetStatePolicy (const State &state, Player player) const override
TabularPolicy AsTabular () const
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
virtual std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const
Public Attributes
const double exploration_
Detailed Description
Definition at line 160 of file oos.h.
Constructor & Destructor Documentation
ExplorativeSamplingPolicy()
open_spiel::algorithms::ExplorativeSamplingPolicy::ExplorativeSamplingPolicy (const OOSInfoStateValuesTable & table, double exploration = kDefaultExploration) inline
Definition at line 164 of file oos.h.
      : CFRCurrentPolicy(table, std::make_shared<UniformPolicy>()),
        exploration_(exploration) {
    // We need the exploration to be positive to guarantee all leaves are
    // reachable.
    SPIEL_CHECK_GT(exploration_, 0);
    SPIEL_CHECK_LE(exploration_, 1);
  }
References exploration_, SPIEL_CHECK_GT, and SPIEL_CHECK_LE.
Member Function Documentation
GetStatePolicy() [1/2]
ActionsAndProbs open_spiel::algorithms::ExplorativeSamplingPolicy::GetStatePolicy (const State & state) const override virtual
Reimplemented from open_spiel::algorithms::CFRCurrentPolicy.
Definition at line 54 of file oos.cc.
{
  if (state.IsChanceNode()) {
    return state.ChanceOutcomes();
  } else if (state.IsPlayerNode()) {
    return GetStatePolicy(state.InformationStateString());
  }
  SpielFatalError("Could not get policy for this state.");
}
References GetStatePolicy(), open_spiel::SpielFatalError(), and state.
Referenced by GetStatePolicy().
GetStatePolicy() [2/2]
ActionsAndProbs open_spiel::algorithms::ExplorativeSamplingPolicy::GetStatePolicy (const std::string & info_state) const override virtual
Reimplemented from open_spiel::algorithms::CFRCurrentPolicy.
Definition at line 64 of file oos.cc.
{
  auto policy = CFRCurrentPolicy::GetStatePolicy(info_state);
  const double unif = 1. / policy.size();
  for (auto& [_, prob] : policy) {
    prob = exploration_ * unif + (1 - exploration_) * prob;
  }
  return policy;
}
References exploration_, and open_spiel::algorithms::CFRCurrentPolicy::GetStatePolicy().
Member Data Documentation
exploration_
const double open_spiel::algorithms::ExplorativeSamplingPolicy::exploration_
Definition at line 162 of file oos.h.
Referenced by ExplorativeSamplingPolicy(), and GetStatePolicy().
The documentation for this class was generated from the following files:
open_spiel/algorithms/oos.h
open_spiel/algorithms/oos.cc