open spiel: open_spiel::oh_hell::OhHellGame Class Reference
open_spiel::oh_hell::OhHellGame Class Reference
#include <oh_hell.h>
Public Member Functions
OhHellGame (const GameParameters &params)
int NumDistinctActions () const override
int MaxChanceOutcomes () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
std::vector< int > InformationStateTensorShape () const override
int MaxNumTricks () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual std::vector< int > ObservationTensorShape () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 216 of file oh_hell.h.
Constructor & Destructor Documentation
OhHellGame()
open_spiel::oh_hell::OhHellGame::OhHellGame (const GameParameters & params) explicit
Definition at line 75 of file oh_hell.cc.
    : Game(kGameType, params),
      num_players_(ParameterValue<int>("players")),
      deck_props_(ParameterValue<int>("num_suits"),
                  ParameterValue<int>("num_cards_per_suit")),
      num_tricks_fixed_(ParameterValue<int>("num_tricks_fixed")),
      off_bid_penalty_(ParameterValue<bool>("off_bid_penalty")),
      points_per_trick_(ParameterValue<int>("points_per_trick")) {
  SPIEL_CHECK_TRUE(num_players_ >= kMinNumPlayers &&
                   num_players_ <= kMaxNumPlayers);
  SPIEL_CHECK_TRUE(deck_props_.NumSuits() >= kMinNumSuits &&
                   deck_props_.NumSuits() <= kMaxNumSuits);
  SPIEL_CHECK_TRUE(deck_props_.NumCardsPerSuit() >= kMinNumCardsPerSuit &&
                   deck_props_.NumCardsPerSuit() <= kMaxNumCardsPerSuit);
  // need at least num_players + 1 cards
  SPIEL_CHECK_TRUE(num_players_ <= deck_props_.NumCards() - kNumTrumpDeal);
  SPIEL_CHECK_TRUE(num_tricks_fixed_ == kRandomNumTricks ||
                   (num_tricks_fixed_ >= kMinNumTricks &&
                   num_tricks_fixed_ <= MaxNumTricks()));
}
References open_spiel::oh_hell::kMaxNumCardsPerSuit, open_spiel::oh_hell::kMaxNumPlayers, open_spiel::oh_hell::kMaxNumSuits, open_spiel::oh_hell::kMinNumCardsPerSuit, open_spiel::oh_hell::kMinNumPlayers, open_spiel::oh_hell::kMinNumSuits, open_spiel::oh_hell::kMinNumTricks, open_spiel::oh_hell::kNumTrumpDeal, open_spiel::oh_hell::kRandomNumTricks, MaxNumTricks(), open_spiel::oh_hell::DeckProperties::NumCards(), open_spiel::oh_hell::DeckProperties::NumCardsPerSuit(), open_spiel::oh_hell::DeckProperties::NumSuits(), and SPIEL_CHECK_TRUE.
Member Function Documentation
InformationStateTensorShape()
std::vector< int > open_spiel::oh_hell::OhHellGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 96 of file oh_hell.cc.
{
  // initial chance actions (incl trump dealing)
  int len = MaxNumTricks() + num_players_ + deck_props_.NumCards();
  // initial hand and current hand
  len += 2 * deck_props_.NumCards();
  // bids, legal range is [no bid, 0, 1, ..., max legal bid]
  len += num_players_ * (MaxNumTricks() + 2);
  // tricks won so far
  len += MaxNumTricks() * num_players_;
  // tricks
  len += MaxNumTricks() * (2 * num_players_ - 1) * deck_props_.NumCards();
  return {len};
}
References len, MaxNumTricks(), and open_spiel::oh_hell::DeckProperties::NumCards().
MaxChanceNodesInHistory()
int open_spiel::oh_hell::OhHellGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 248 of file oh_hell.h.
{
    return kNumPreDealChanceActions + MaxNumTricks() * num_players_
                                    + kNumTrumpDeal;
  }
References open_spiel::oh_hell::kNumPreDealChanceActions, open_spiel::oh_hell::kNumTrumpDeal, and MaxNumTricks().
MaxChanceOutcomes()
int open_spiel::oh_hell::OhHellGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 222 of file oh_hell.h.
{ return deck_props_.NumCards(); }
References open_spiel::oh_hell::DeckProperties::NumCards().
MaxGameLength()
int open_spiel::oh_hell::OhHellGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 244 of file oh_hell.h.
{
    return 2 * MaxNumTricks() * num_players_ + num_players_
             + kNumPreDealChanceActions + kNumTrumpDeal;
  }
References open_spiel::oh_hell::kNumPreDealChanceActions, open_spiel::oh_hell::kNumTrumpDeal, and MaxNumTricks().
MaxNumTricks()
int open_spiel::oh_hell::OhHellGame::MaxNumTricks () const inline
Definition at line 255 of file oh_hell.h.
{
    if (num_tricks_fixed_ > 0) return num_tricks_fixed_;
    return (deck_props_.NumCards() - kNumTrumpDeal) / num_players_;
  }
References open_spiel::oh_hell::kNumTrumpDeal, and open_spiel::oh_hell::DeckProperties::NumCards().
Referenced by InformationStateTensorShape(), MaxChanceNodesInHistory(), MaxGameLength(), MaxUtility(), MinUtility(), NumDistinctActions(), and OhHellGame().
MaxUtility()
double open_spiel::oh_hell::OhHellGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 237 of file oh_hell.h.
{
    return MaxNumTricks() * points_per_trick_ + kMadeBidBonus;
  }
References open_spiel::oh_hell::kMadeBidBonus, and MaxNumTricks().
MinUtility()
double open_spiel::oh_hell::OhHellGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 233 of file oh_hell.h.
{
    if (off_bid_penalty_) return (- MaxNumTricks() * points_per_trick_);
    return 0;
  }
References MaxNumTricks().
NewInitialState()
std::unique_ptr< State > open_spiel::oh_hell::OhHellGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 223 of file oh_hell.h.
{
    return std::unique_ptr<State>(new OhHellState(
        shared_from_this(),
        /*num_players=*/num_players_,
        /*deck_props=*/deck_props_,
        /*num_tricks_fixed=*/num_tricks_fixed_,
        /*off_bid_penalty=*/off_bid_penalty_,
        /*points_per_trick=*/points_per_trick_));
  }
NumDistinctActions()
int open_spiel::oh_hell::OhHellGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 219 of file oh_hell.h.
{
    return deck_props_.NumCards() + MaxNumTricks() + 1;
  }
References MaxNumTricks(), and open_spiel::oh_hell::DeckProperties::NumCards().
NumPlayers()
int open_spiel::oh_hell::OhHellGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 232 of file oh_hell.h.
{ return num_players_; }
The documentation for this class was generated from the following files:
open_spiel/games/oh_hell/oh_hell.h
open_spiel/games/oh_hell/oh_hell.cc