open spiel: absl::uint128 Class Reference
absl::uint128 Class Reference
#include <int128.h>
Public Member Functions
uint128 ()=default
constexpr uint128 (int v)
constexpr uint128 (unsigned int v)
constexpr uint128 (long v)
constexpr uint128 (unsigned long v)
constexpr uint128 (long long v)
constexpr uint128 (unsigned long long v)
constexpr uint128 (int128 v)
uint128 (float v)
uint128 (double v)
uint128 (long double v)
uint128 & operator= (int v)
uint128 & operator= (unsigned int v)
uint128 & operator= (long v)
uint128 & operator= (unsigned long v)
uint128 & operator= (long long v)
uint128 & operator= (unsigned long long v)
uint128 & operator= (int128 v)
constexpr operator bool () const
constexpr operator char () const
constexpr operator signed char () const
constexpr operator unsigned char () const
constexpr operator char16_t () const
constexpr operator char32_t () const
constexpr operator ABSL_INTERNAL_WCHAR_T () const
constexpr operator short () const
constexpr operator unsigned short () const
constexpr operator int () const
constexpr operator unsigned int () const
constexpr operator long () const
constexpr operator unsigned long () const
constexpr operator long long () const
constexpr operator unsigned long long () const
operator float () const
operator double () const
operator long double () const
uint128 & operator+= (uint128 other)
uint128 & operator-= (uint128 other)
uint128 & operator*= (uint128 other)
uint128 & operator/= (uint128 other)
uint128 & operator%= (uint128 other)
uint128 operator++ (int)
uint128 operator-- (int)
uint128 & operator<<= (int)
uint128 & operator>>= (int)
uint128 & operator&= (uint128 other)
uint128 & operator|= (uint128 other)
uint128 & operator^= (uint128 other)
uint128 & operator++ ()
uint128 & operator-- ()
Friends
constexpr uint64_t Uint128Low64 (uint128 v)
constexpr uint64_t Uint128High64 (uint128 v)
constexpr uint128 MakeUint128 (uint64_t high, uint64_t low)
constexpr uint128 Uint128Max ()
template<typename H >
H AbslHashValue (H h, uint128 v)
Detailed Description
Definition at line 104 of file int128.h.
Constructor & Destructor Documentation
uint128() [1/11]
absl::uint128::uint128 () default
Referenced by operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), and operator=().
uint128() [2/11]
absl::uint128::uint128 (int v) constexpr
uint128() [3/11]
absl::uint128::uint128 (unsigned int v) constexpr
uint128() [4/11]
absl::uint128::uint128 (long v) constexpr
uint128() [5/11]
absl::uint128::uint128 (unsigned long v) constexpr
uint128() [6/11]
absl::uint128::uint128 (long long v) constexpr
uint128() [7/11]
absl::uint128::uint128 (unsigned long long v) constexpr
uint128() [8/11]
absl::uint128::uint128 (int128 v) constexpr
uint128() [9/11]
absl::uint128::uint128 (float v) explicit
Definition at line 137 of file int128.cc.
: uint128(MakeUint128FromFloat(v)) {}
uint128() [10/11]
absl::uint128::uint128 (double v) explicit
Definition at line 138 of file int128.cc.
: uint128(MakeUint128FromFloat(v)) {}
uint128() [11/11]
absl::uint128::uint128 (long double v) explicit
Definition at line 139 of file int128.cc.
: uint128(MakeUint128FromFloat(v)) {}
Member Function Documentation
operator ABSL_INTERNAL_WCHAR_T()
absl::uint128::operator ABSL_INTERNAL_WCHAR_T () const explicit constexpr
Definition at line 730 of file int128.h.
{
  return static_cast<ABSL_INTERNAL_WCHAR_T>(lo_);
}
References ABSL_INTERNAL_WCHAR_T.
operator bool()
absl::uint128::operator bool () const explicit constexpr
Definition at line 710 of file int128.h.
{ return lo_ || hi_; }
operator char()
absl::uint128::operator char () const explicit constexpr
Definition at line 712 of file int128.h.
{ return static_cast<char>(lo_); }
operator char16_t()
absl::uint128::operator char16_t () const explicit constexpr
Definition at line 722 of file int128.h.
{
  return static_cast<char16_t>(lo_);
}
operator char32_t()
absl::uint128::operator char32_t () const explicit constexpr
Definition at line 726 of file int128.h.
{
  return static_cast<char32_t>(lo_);
}
operator double()
absl::uint128::operator double () const inline explicit
Definition at line 778 of file int128.h.
{
  return static_cast<double>(lo_) + std::ldexp(static_cast<double>(hi_), 64);
}
operator float()
absl::uint128::operator float () const inline explicit
Definition at line 774 of file int128.h.
{
  return static_cast<float>(lo_) + std::ldexp(static_cast<float>(hi_), 64);
}
operator int()
absl::uint128::operator int () const explicit constexpr
Definition at line 741 of file int128.h.
{ return static_cast<int>(lo_); }
operator long()
absl::uint128::operator long () const explicit constexpr
Definition at line 748 of file int128.h.
{ return static_cast<long>(lo_); }
operator long double()
absl::uint128::operator long double () const inline explicit
Definition at line 782 of file int128.h.
{
  return static_cast<long double>(lo_) +
         std::ldexp(static_cast<long double>(hi_), 64);
}
operator long long()
absl::uint128::operator long long () const explicit constexpr
Definition at line 754 of file int128.h.
                                            {  // NOLINT(runtime/int)
  return static_cast<long long>(lo_);            // NOLINT(runtime/int)
}
operator short()
absl::uint128::operator short () const explicit constexpr
Definition at line 735 of file int128.h.
{ return static_cast<short>(lo_); }
operator signed char()
absl::uint128::operator signed char () const explicit constexpr
Definition at line 714 of file int128.h.
{
  return static_cast<signed char>(lo_);
}
operator unsigned char()
absl::uint128::operator unsigned char () const explicit constexpr
Definition at line 718 of file int128.h.
{
  return static_cast<unsigned char>(lo_);
}
operator unsigned int()
absl::uint128::operator unsigned int () const explicit constexpr
Definition at line 743 of file int128.h.
{
  return static_cast<unsigned int>(lo_);
}
operator unsigned long()
absl::uint128::operator unsigned long () const explicit constexpr
Definition at line 750 of file int128.h.
                                                {  // NOLINT(runtime/int)
  return static_cast<unsigned long>(lo_);            // NOLINT(runtime/int)
}
operator unsigned long long()
absl::uint128::operator unsigned long long () const explicit constexpr
Definition at line 758 of file int128.h.
                                                     {  // NOLINT(runtime/int)
  return static_cast<unsigned long long>(lo_);            // NOLINT(runtime/int)
}
operator unsigned short()
absl::uint128::operator unsigned short () const explicit constexpr
Definition at line 737 of file int128.h.
                                                 {  // NOLINT(runtime/int)
  return static_cast<unsigned short>(lo_);            // NOLINT(runtime/int)
}
operator%=()
uint128 & absl::uint128::operator%= (uint128 other) inline
Definition at line 627 of file int128.h.
{
  *this = *this % other;
  return *this;
}
operator&=()
uint128 & absl::uint128::operator&= (uint128 other) inline
Definition at line 891 of file int128.h.
{
  *this = *this & other;
  return *this;
}
operator*=()
uint128 & absl::uint128::operator*= (uint128 other) inline
Definition at line 617 of file int128.h.
{
  *this = *this * other;
  return *this;
}
operator++() [1/2]
uint128 & absl::uint128::operator++ () inline
Definition at line 1030 of file int128.h.
{
  *this += 1;
  return *this;
}
operator++() [2/2]
uint128 absl::uint128::operator++ (int) inline
Definition at line 1018 of file int128.h.
{
  uint128 tmp(*this);
  *this += 1;
  return tmp;
}
operator+=()
uint128 & absl::uint128::operator+= (uint128 other) inline
Definition at line 607 of file int128.h.
{
  *this = *this + other;
  return *this;
}
operator--() [1/2]
uint128 & absl::uint128::operator-- () inline
Definition at line 1035 of file int128.h.
{
  *this -= 1;
  return *this;
}
operator--() [2/2]
uint128 absl::uint128::operator-- (int) inline
Definition at line 1024 of file int128.h.
{
  uint128 tmp(*this);
  *this -= 1;
  return tmp;
}
operator-=()
uint128 & absl::uint128::operator-= (uint128 other) inline
Definition at line 612 of file int128.h.
{
  *this = *this - other;
  return *this;
}
operator/=()
uint128 & absl::uint128::operator/= (uint128 other) inline
Definition at line 622 of file int128.h.
{
  *this = *this / other;
  return *this;
}
operator<<=()
uint128 & absl::uint128::operator<<= (int amount) inline
Definition at line 597 of file int128.h.
{
  *this = *this << amount;
  return *this;
}
operator=() [1/7]
uint128 & absl::uint128::operator= (int v) inline
Definition at line 548 of file int128.h.
{ return *this = uint128(v); }
References uint128(), and absl::v.
operator=() [2/7]
uint128 & absl::uint128::operator= (int128 v) inline
Definition at line 583 of file int128.h.
{
  return *this = uint128(v);
}
References uint128(), and absl::v.
operator=() [3/7]
uint128 & absl::uint128::operator= (long long v) inline
Definition at line 564 of file int128.h.
{
  return *this = uint128(v);
}
References uint128(), and absl::v.
operator=() [4/7]
uint128 & absl::uint128::operator= (long v) inline
Definition at line 554 of file int128.h.
                                         {  // NOLINT(runtime/int)
  return *this = uint128(v);
}
References uint128(), and absl::v.
operator=() [5/7]
uint128 & absl::uint128::operator= (unsigned int v) inline
Definition at line 550 of file int128.h.
{
  return *this = uint128(v);
}
References uint128(), and absl::v.
operator=() [6/7]
uint128 & absl::uint128::operator= (unsigned long long v) inline
Definition at line 569 of file int128.h.
{
  return *this = uint128(v);
}
References uint128(), and absl::v.
operator=() [7/7]
uint128 & absl::uint128::operator= (unsigned long v) inline
Definition at line 559 of file int128.h.
{
  return *this = uint128(v);
}
References uint128(), and absl::v.
operator>>=()
uint128 & absl::uint128::operator>>= (int amount) inline
Definition at line 602 of file int128.h.
{
  *this = *this >> amount;
  return *this;
}
operator^=()
uint128 & absl::uint128::operator^= (uint128 other) inline
Definition at line 896 of file int128.h.
{
  *this = *this ^ other;
  return *this;
}
operator|=()
uint128 & absl::uint128::operator|= (uint128 other) inline
Definition at line 886 of file int128.h.
{
  *this = *this | other;
  return *this;
}
Friends And Related Symbol Documentation
AbslHashValue
template<typename H > H AbslHashValue (H h, uint128 v) friend
Definition at line 216 of file int128.h.
{
    return H::combine(std::move(h), Uint128High64(v), Uint128Low64(v));
  }
MakeUint128
uint128 MakeUint128 (uint64_t high, uint64_t low) friend
Definition at line 542 of file int128.h.
{
  return uint128(high, low);
}
Uint128High64
uint64_t Uint128High64 (uint128 v) friend
Definition at line 634 of file int128.h.
{ return v.hi_; }
Uint128Low64
uint64_t Uint128Low64 (uint128 v) friend
Definition at line 632 of file int128.h.
{ return v.lo_; }
Uint128Max
uint128 Uint128Max () friend
Definition at line 248 of file int128.h.
{
  return uint128((std::numeric_limits<uint64_t>::max)(),
                 (std::numeric_limits<uint64_t>::max)());
}
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/numeric/int128.h
open_spiel/abseil-cpp/absl/numeric/int128.cc