open spiel: open_spiel::oshi_zumo::OshiZumoState Class Reference
open_spiel::oshi_zumo::OshiZumoState Class Reference
#include <oshi_zumo.h>
Public Member Functions
OshiZumoState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions (Player player) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyActions (const std::vector< Action > &actions) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyAction (Action action_id)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 53 of file oshi_zumo.h.
Constructor & Destructor Documentation
OshiZumoState()
open_spiel::oshi_zumo::OshiZumoState::OshiZumoState (std::shared_ptr< const Game > game) explicit
Definition at line 69 of file oshi_zumo.cc.
    : SimMoveState(game),
      parent_game_(static_cast<const OshiZumoGame&>(*game)),
      // Fields set to bad values. Use Game::NewInitialState().
      winner_(kNoWinner),
      total_moves_(0),
      horizon_(parent_game_.horizon()),
      starting_coins_(parent_game_.starting_coins()),
      size_(parent_game_.size()),
      alesia_(parent_game_.alesia()),
      min_bid_(parent_game_.min_bid()),
      // pos 0 and pos 2*size_+2 are "off the edge".
      wrestler_pos_(size_ + 1),
      coins_({{starting_coins_, starting_coins_}})
{}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::oshi_zumo::OshiZumoState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 138 of file oshi_zumo.cc.
{
  if (player == kSimultaneousPlayerId)
    return FlatJointActionToString(action_id);
  SPIEL_CHECK_GE(action_id, 0);
  std::string result = "";
  absl::StrAppend(&result, "[P", player, "]Bid: ", action_id);
  return result;
}
References open_spiel::SimMoveState::FlatJointActionToString(), open_spiel::kSimultaneousPlayerId, player, SPIEL_CHECK_GE, and absl::StrAppend().
Clone()
std::unique_ptr< State > open_spiel::oshi_zumo::OshiZumoState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 232 of file oshi_zumo.cc.
{
  return std::unique_ptr<State>(new OshiZumoState(*this));
}
References OshiZumoState().
CurrentPlayer()
int open_spiel::oshi_zumo::OshiZumoState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 86 of file oshi_zumo.cc.
{
  return IsTerminal() ? kTerminalPlayerId : kSimultaneousPlayerId;
}
References IsTerminal(), open_spiel::kSimultaneousPlayerId, and open_spiel::kTerminalPlayerId.
DoApplyActions()
void open_spiel::oshi_zumo::OshiZumoState::DoApplyActions (const std::vector< Action > & actions) override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 90 of file oshi_zumo.cc.
{
  SPIEL_CHECK_EQ(actions.size(), 2);
  SPIEL_CHECK_TRUE(actions[0] >= 0);
  SPIEL_CHECK_TRUE(actions[1] >= 0);
  SPIEL_CHECK_TRUE(actions[0] <= coins_[0]);
  SPIEL_CHECK_TRUE(actions[1] <= coins_[1]);
  // Move the wrestler.
  if (actions[0] > actions[1]) {
    wrestler_pos_++;
  } else if (actions[0] < actions[1]) {
    wrestler_pos_--;
  }
  // Remove coins.
  coins_[0] -= actions[0];
  coins_[1] -= actions[1];
  // Check winner.
  if (wrestler_pos_ == 0) {
    winner_ = 1;
  } else if (wrestler_pos_ == (2 * size_ + 2)) {
    winner_ = 0;
  }
  total_moves_++;
}
References SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
InformationStateString()
std::string open_spiel::oshi_zumo::OshiZumoState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 198 of file oshi_zumo.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();  // All the information is public.
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::oshi_zumo::OshiZumoState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 170 of file oshi_zumo.cc.
{
  return (total_moves_ >= horizon_ || winner_ != kNoWinner ||
          (coins_[0] == 0 && coins_[1] == 0));
}
Referenced by CurrentPlayer(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::oshi_zumo::OshiZumoState::LegalActions (Player player) const override virtual
Implements open_spiel::SimMoveState.
Definition at line 118 of file oshi_zumo.cc.
{
  if (IsTerminal()) return {};
  if (player == kSimultaneousPlayerId) return LegalFlatJointActions();
  SPIEL_CHECK_FALSE(IsChanceNode());
  SPIEL_CHECK_TRUE(player == Player{0} || player == Player{1});
  std::vector<Action> movelist;
  for (int bet = min_bid_; bet <= coins_[player]; bet++) {
    movelist.push_back(bet);
  }
  if (movelist.empty()) {
    // Player does not have the minimum bid: force them to play what they have
    // left.
    movelist.push_back(coins_[player]);
  }
  return movelist;
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::kSimultaneousPlayerId, open_spiel::SimMoveState::LegalFlatJointActions(), player, SPIEL_CHECK_FALSE, and SPIEL_CHECK_TRUE.
ObservationString()
std::string open_spiel::oshi_zumo::OshiZumoState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 204 of file oshi_zumo.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();  // All the information is public.
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::oshi_zumo::OshiZumoState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 210 of file oshi_zumo.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), parent_game_.ObservationTensorShape()[0]);
  std::fill(values.begin(), values.end(), 0.);
  // 1 bit per coin value of player 1. { 0, 1, ... , starting_coins_ }
  // 1 bit per coin value of player 2. { 0, 1, ... , starting_coins_ }
  // 1 bit per position of the field. { 0, 1, ... , 2*size_+2 }
  int offset = 0;
  values[offset + coins_[0]] = 1;
  offset += (starting_coins_ + 1);
  values[offset + coins_[1]] = 1;
  offset += (starting_coins_ + 1);
  values[offset + wrestler_pos_] = 1;
}
References open_spiel::State::num_players_, open_spiel::oshi_zumo::OshiZumoGame::ObservationTensorShape(), player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::oshi_zumo::OshiZumoState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 175 of file oshi_zumo.cc.
{
  if (!IsTerminal()) {
    return {0.0, 0.0};
  }
  if (winner_ == 0) {
    return {1.0, -1.0};
  } else if (winner_ == 1) {
    return {-1.0, 1.0};
  } else {
    // Wrestler not off the edge.
    if (alesia_) {
      return {0.0, 0.0};
    } else if (wrestler_pos_ > (size_ + 1)) {
      return {1.0, -1.0};
    } else if (wrestler_pos_ < (size_ + 1)) {
      return {-1.0, 1.0};
    } else {
      return {0.0, 0.0};
    }
  }
}
References IsTerminal().
ToString()
std::string open_spiel::oshi_zumo::OshiZumoState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 148 of file oshi_zumo.cc.
{
  std::string result = "Coins: ";
  absl::StrAppend(&result, coins_[0]);
  absl::StrAppend(&result, " ");
  absl::StrAppend(&result, coins_[1]);
  absl::StrAppend(&result, ", Field: ");
  for (int p = 0; p <= 2 * size_ + 2; p++) {
    if (p == wrestler_pos_) {
      result += kWrestler;
    } else if (p == 0 || p == (2 * size_ + 2)) {
      result += kBoundaryPos;
    } else {
      result += kOpenPos;
    }
  }
  absl::StrAppend(&result, "\n");
  return result;
}
References absl::StrAppend().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/oshi_zumo/oshi_zumo.h
open_spiel/games/oshi_zumo/oshi_zumo.cc