open spiel: open_spiel::phantom_go::PhantomGoGame Class Reference
open_spiel::phantom_go::PhantomGoGame Class Reference
#include <phantom_go.h>
Public Member Functions
PhantomGoGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
std::vector< int > ObservationTensorShape () const override
TensorLayout ObservationTensorLayout () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
int MaxGameLength () const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Public Attributes
std::shared_ptr< PhantomGoObserver > default_observer_
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 139 of file phantom_go.h.
Constructor & Destructor Documentation
PhantomGoGame()
open_spiel::phantom_go::PhantomGoGame::PhantomGoGame (const GameParameters & params) explicit
Definition at line 343 of file phantom_go.cc.
    : Game(kGameType, params),
      komi_(ParameterValue<double>("komi")),
      board_size_(ParameterValue<int>("board_size")),
      handicap_(ParameterValue<int>("handicap")),
      max_game_length_(ParameterValue<int>("max_game_length",
                                           DefaultMaxGameLength(board_size_))) {
  default_observer_ = std::make_shared<PhantomGoObserver>(kDefaultObsType);
}
References default_observer_, and open_spiel::kDefaultObsType.
Member Function Documentation
MaxGameLength()
int open_spiel::phantom_go::PhantomGoGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 173 of file phantom_go.h.
{ return max_game_length_; }
MaxUtility()
double open_spiel::phantom_go::PhantomGoGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 171 of file phantom_go.h.
{ return WinUtility(); }
References open_spiel::phantom_go::WinUtility().
MinUtility()
double open_spiel::phantom_go::PhantomGoGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 167 of file phantom_go.h.
{ return LossUtility(); }
References open_spiel::phantom_go::LossUtility().
NewInitialState()
std::unique_ptr< State > open_spiel::phantom_go::PhantomGoGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 149 of file phantom_go.h.
{
    return std::unique_ptr<State>(
        new PhantomGoState(shared_from_this(), board_size_, komi_, handicap_));
  }
NumDistinctActions()
int open_spiel::phantom_go::PhantomGoGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 145 of file phantom_go.h.
{
    return phantom_go::NumDistinctActions(board_size_);
  }
References open_spiel::phantom_go::NumDistinctActions().
NumPlayers()
int open_spiel::phantom_go::PhantomGoGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 165 of file phantom_go.h.
{ return phantom_go::NumPlayers(); }
References open_spiel::phantom_go::NumPlayers().
ObservationTensorLayout()
TensorLayout open_spiel::phantom_go::PhantomGoGame::ObservationTensorLayout () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 161 of file phantom_go.h.
{
    return TensorLayout::kCHW;
  }
References open_spiel::kCHW.
ObservationTensorShape()
std::vector< int > open_spiel::phantom_go::PhantomGoGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 154 of file phantom_go.h.
{
    // Planes: black, white, empty, and a bias plane indicating komi (whether
    // white is to play)
    // and 2 for stone count of white and black
    return {2 + board_size_ * board_size_ * (CellStates() + 1)};
  }
References open_spiel::phantom_go::CellStates().
UtilitySum()
absl::optional< double > open_spiel::phantom_go::PhantomGoGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 168 of file phantom_go.h.
{
    return LossUtility() + WinUtility();
  }
References open_spiel::phantom_go::LossUtility(), and open_spiel::phantom_go::WinUtility().
Member Data Documentation
default_observer_
std::shared_ptr<PhantomGoObserver> open_spiel::phantom_go::PhantomGoGame::default_observer_
Definition at line 143 of file phantom_go.h.
Referenced by PhantomGoGame().
The documentation for this class was generated from the following files:
open_spiel/games/phantom_go/phantom_go.h
open_spiel/games/phantom_go/phantom_go.cc