open spiel: absl::container_internal::CommonFields Class Reference
absl::container_internal::CommonFields Class Reference
#include <raw_hash_set.h>
Public Member Functions
CommonFields ()=default
CommonFields (const CommonFields &)=delete
CommonFields & operator= (const CommonFields &)=delete
CommonFields (CommonFields &&that)
CommonFields & operator= (CommonFields &&)=default
size_t & growth_left ()
HashtablezInfoHandle & infoz ()
const HashtablezInfoHandle & infoz () const
void reset_reserved_growth (size_t reservation)
Public Member Functions inherited from absl::container_internal::CommonFieldsGenerationInfoDisabled
CommonFieldsGenerationInfoDisabled ()=default
CommonFieldsGenerationInfoDisabled (CommonFieldsGenerationInfoDisabled &&)=default
CommonFieldsGenerationInfoDisabled & operator= (CommonFieldsGenerationInfoDisabled &&)=default
bool should_rehash_for_bug_detection_on_insert () const
void maybe_increment_generation_on_insert ()
void reset_reserved_growth (size_t, size_t)
size_t reserved_growth () const
void set_reserved_growth (size_t)
GenerationType generation () const
void set_generation (GenerationType)
GenerationType * generation_ptr () const
void set_generation_ptr (GenerationType *)
Public Attributes
ctrl_t * control_ = EmptyGroup()
void * slots_ = nullptr
size_t size_ = 0
size_t capacity_ = 0
absl::container_internal::CompressedTuple< size_t, HashtablezInfoHandle > compressed_tuple_ {0u, HashtablezInfoHandle{}}
Detailed Description
Definition at line 873 of file raw_hash_set.h.
Constructor & Destructor Documentation
CommonFields() [1/3]
absl::container_internal::CommonFields::CommonFields () default
CommonFields() [2/3]
absl::container_internal::CommonFields::CommonFields (const CommonFields &) delete
CommonFields() [3/3]
absl::container_internal::CommonFields::CommonFields (CommonFields && that) inline
Definition at line 882 of file raw_hash_set.h.
      : CommonFieldsGenerationInfo(
            std::move(static_cast<CommonFieldsGenerationInfo&&>(that))),
        // Explicitly copying fields into "this" and then resetting "that"
        // fields generates less code then calling absl::exchange per field.
        control_(that.control_),
        slots_(that.slots_),
        size_(that.size_),
        capacity_(that.capacity_),
        compressed_tuple_(that.growth_left(), std::move(that.infoz())) {
    that.control_ = EmptyGroup();
    that.slots_ = nullptr;
    that.size_ = 0;
    that.capacity_ = 0;
    that.growth_left() = 0;
  }
References absl::container_internal::EmptyGroup().
Member Function Documentation
growth_left()
size_t & absl::container_internal::CommonFields::growth_left () inline
Definition at line 901 of file raw_hash_set.h.
{ return compressed_tuple_.template get<0>(); }
References compressed_tuple_, and absl::get().
Referenced by absl::container_internal::ResetGrowthLeft().
infoz() [1/2]
HashtablezInfoHandle & absl::container_internal::CommonFields::infoz () inline
Definition at line 903 of file raw_hash_set.h.
{ return compressed_tuple_.template get<1>(); }
References compressed_tuple_, and absl::get().
Referenced by absl::container_internal::DropDeletesWithoutResize().
infoz() [2/2]
const HashtablezInfoHandle & absl::container_internal::CommonFields::infoz () const inline
Definition at line 904 of file raw_hash_set.h.
{
    return compressed_tuple_.template get<1>();
  }
References compressed_tuple_, and absl::get().
operator=() [1/2]
CommonFields & absl::container_internal::CommonFields::operator= (CommonFields &&) default
operator=() [2/2]
CommonFields & absl::container_internal::CommonFields::operator= (const CommonFields &) delete
reset_reserved_growth()
void absl::container_internal::CommonFields::reset_reserved_growth (size_t reservation) inline
Definition at line 908 of file raw_hash_set.h.
{
    CommonFieldsGenerationInfo::reset_reserved_growth(reservation, size_);
  }
References absl::container_internal::CommonFieldsGenerationInfoDisabled::reset_reserved_growth(), and size_.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::reserve().
Member Data Documentation
capacity_
size_t absl::container_internal::CommonFields::capacity_ = 0
Definition at line 930 of file raw_hash_set.h.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity(), absl::container_internal::DropDeletesWithoutResize(), absl::container_internal::find_first_non_full(), absl::container_internal::probe(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set(), absl::container_internal::ResetCtrl(), absl::container_internal::ResetGrowthLeft(), and absl::container_internal::SetCtrl().
compressed_tuple_
absl::container_internal::CompressedTuple<size_t, HashtablezInfoHandle> absl::container_internal::CommonFields::compressed_tuple_ {0u, HashtablezInfoHandle{}}
Definition at line 935 of file raw_hash_set.h.
{0u, HashtablezInfoHandle{}};
Referenced by growth_left(), infoz(), and infoz().
control_
ctrl_t* absl::container_internal::CommonFields::control_ = EmptyGroup()
Definition at line 920 of file raw_hash_set.h.
Referenced by absl::container_internal::DropDeletesWithoutResize(), absl::container_internal::find_first_non_full(), absl::container_internal::probe(), absl::container_internal::ResetCtrl(), and absl::container_internal::SetCtrl().
size_
size_t absl::container_internal::CommonFields::size_ = 0
Definition at line 927 of file raw_hash_set.h.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set(), reset_reserved_growth(), absl::container_internal::ResetGrowthLeft(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::size().
slots_
void* absl::container_internal::CommonFields::slots_ = nullptr
Definition at line 924 of file raw_hash_set.h.
Referenced by absl::container_internal::DropDeletesWithoutResize(), absl::container_internal::ResetCtrl(), and absl::container_internal::SetCtrl().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/raw_hash_set.h