open spiel: absl::synchronization_internal::KernelTimeout Class Reference
absl::synchronization_internal::KernelTimeout Class Reference
#include <kernel_timeout.h>
Public Member Functions
KernelTimeout (absl::Time t)
KernelTimeout ()
bool has_timeout () const
struct timespec MakeAbsTimespec () const
int64_t MakeAbsNanos () const
Static Public Member Functions
static KernelTimeout Never ()
Detailed Description
Definition at line 44 of file kernel_timeout.h.
Constructor & Destructor Documentation
KernelTimeout() [1/2]
absl::synchronization_internal::KernelTimeout::KernelTimeout (absl::Time t) inline explicit
Definition at line 49 of file kernel_timeout.h.
: ns_(MakeNs(t)) {}
KernelTimeout() [2/2]
absl::synchronization_internal::KernelTimeout::KernelTimeout () inline
Definition at line 51 of file kernel_timeout.h.
: ns_(0) {}
Member Function Documentation
has_timeout()
bool absl::synchronization_internal::KernelTimeout::has_timeout () const inline
Definition at line 59 of file kernel_timeout.h.
{ return ns_ != 0; }
MakeAbsNanos()
int64_t absl::synchronization_internal::KernelTimeout::MakeAbsNanos () const inline
Definition at line 155 of file kernel_timeout.h.
{
  if (ns_ == 0) {
    ABSL_RAW_LOG(
        ERROR, "Tried to create a timeout from a non-timeout; never do this.");
    // But we'll try to continue sanely.  no-timeout ~= saturated timeout.
    return (std::numeric_limits<int64_t>::max)();
  }
  return ns_;
}
References ABSL_RAW_LOG.
MakeAbsTimespec()
struct timespec absl::synchronization_internal::KernelTimeout::MakeAbsTimespec () const inline
Definition at line 131 of file kernel_timeout.h.
{
  int64_t n = ns_;
  static const int64_t kNanosPerSecond = 1000 * 1000 * 1000;
  if (n == 0) {
    ABSL_RAW_LOG(
        ERROR, "Tried to create a timespec from a non-timeout; never do this.");
    // But we'll try to continue sanely.  no-timeout ~= saturated timeout.
    n = (std::numeric_limits<int64_t>::max)();
  }
  // Kernel APIs validate timespecs as being at or after the epoch,
  // despite the kernel time type being signed.  However, no one can
  // tell the difference between a timeout at or before the epoch (since
  // all such timeouts have expired!)
  if (n < 0) n = 0;
  struct timespec abstime;
  int64_t seconds = (std::min)(n / kNanosPerSecond,
                               int64_t{(std::numeric_limits<time_t>::max)()});
  abstime.tv_sec = static_cast<time_t>(seconds);
  abstime.tv_nsec = static_cast<decltype(abstime.tv_nsec)>(n % kNanosPerSecond);
  return abstime;
}
References ABSL_RAW_LOG, and n.
Never()
static KernelTimeout absl::synchronization_internal::KernelTimeout::Never () inline static
Definition at line 54 of file kernel_timeout.h.
{ return {}; }
Referenced by absl::Mutex::Await(), absl::synchronization_internal::PerThreadSemTest::TestTiming(), and absl::CondVar::Wait().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/synchronization/internal/kernel_timeout.h