open spiel: absl::Time Class Reference
absl::Time Class Reference
#include <time.h>
Classes
struct Breakdown
Public Member Functions
constexpr Time ()=default
constexpr Time (const Time &t)=default
Time & operator= (const Time &t)=default
Time & operator+= (Duration d)
Time & operator-= (Duration d)
Breakdown In (TimeZone tz) const
Friends
template<typename H >
H AbslHashValue (H h, Time t)
constexpr Time time_internal::FromUnixDuration (Duration d)
constexpr Duration time_internal::ToUnixDuration (Time t)
constexpr bool operator< (Time lhs, Time rhs)
constexpr bool operator== (Time lhs, Time rhs)
Duration operator- (Time lhs, Time rhs)
constexpr Time UniversalEpoch ()
constexpr Time InfiniteFuture ()
constexpr Time InfinitePast ()
Detailed Description
Definition at line 683 of file time.h.
Constructor & Destructor Documentation
Time() [1/2]
absl::Time::Time () constexpr default
Time() [2/2]
absl::Time::Time (const Time & t) constexpr default
Member Function Documentation
In()
absl::Time::Breakdown absl::Time::In (absl::TimeZone tz) const
Definition at line 206 of file time.cc.
{
  if (*this == absl::InfiniteFuture()) return InfiniteFutureBreakdown();
  if (*this == absl::InfinitePast()) return InfinitePastBreakdown();
  const auto tp = unix_epoch() + cctz::seconds(time_internal::GetRepHi(rep_));
  const auto al = cctz::time_zone(tz).lookup(tp);
  const auto cs = al.cs;
  const auto cd = cctz::civil_day(cs);
  absl::Time::Breakdown bd;
  bd.year = cs.year();
  bd.month = cs.month();
  bd.day = cs.day();
  bd.hour = cs.hour();
  bd.minute = cs.minute();
  bd.second = cs.second();
  bd.subsecond = time_internal::MakeDuration(0, time_internal::GetRepLo(rep_));
  bd.weekday = MapWeekday(cctz::get_weekday(cd));
  bd.yearday = cctz::get_yearday(cd);
  bd.offset = al.offset;
  bd.is_dst = al.is_dst;
  bd.zone_abbr = al.abbr;
  return bd;
}
References absl::time_internal::cctz::time_zone::absolute_lookup::cs, absl::Time::Breakdown::day, absl::time_internal::GetRepHi(), absl::time_internal::GetRepLo(), absl::Time::Breakdown::hour, absl::InfiniteFuture(), absl::InfinitePast(), absl::Time::Breakdown::is_dst, absl::time_internal::cctz::time_zone::lookup(), absl::time_internal::MakeDuration(), absl::Time::Breakdown::minute, absl::Time::Breakdown::month, absl::Time::Breakdown::offset, absl::Time::Breakdown::second, absl::Time::Breakdown::subsecond, absl::Time::Breakdown::weekday, absl::Time::Breakdown::year, absl::Time::Breakdown::yearday, and absl::Time::Breakdown::zone_abbr.
operator+=()
Time & absl::Time::operator+= (Duration d) inline
Definition at line 703 of file time.h.
{
    rep_ += d;
    return *this;
  }
References absl::d.
operator-=()
Time & absl::Time::operator-= (Duration d) inline
Definition at line 707 of file time.h.
{
    rep_ -= d;
    return *this;
  }
References absl::d.
operator=()
Time & absl::Time::operator= (const Time & t) default
Friends And Related Symbol Documentation
AbslHashValue
template<typename H > H AbslHashValue (H h, Time t) friend
Definition at line 751 of file time.h.
{
    return H::combine(std::move(h), t.rep_);
  }
InfiniteFuture
Time InfiniteFuture () friend
Definition at line 821 of file time.h.
{
  return Time(time_internal::MakeDuration((std::numeric_limits<int64_t>::max)(),
                                          ~uint32_t{0}));
}
InfinitePast
Time InfinitePast () friend
Definition at line 829 of file time.h.
{
  return Time(time_internal::MakeDuration((std::numeric_limits<int64_t>::min)(),
                                          ~uint32_t{0}));
}
operator-
Duration operator- (Time lhs, Time rhs) friend
Definition at line 798 of file time.h.
{
  return lhs.rep_ - rhs.rep_;
}
operator<
bool operator< (Time lhs, Time rhs) friend
Definition at line 769 of file time.h.
{
  return lhs.rep_ < rhs.rep_;
}
operator==
bool operator== (Time lhs, Time rhs) friend
Definition at line 781 of file time.h.
{
  return lhs.rep_ == rhs.rep_;
}
time_internal::FromUnixDuration
Time time_internal::FromUnixDuration (Duration d) friend
time_internal::ToUnixDuration
Duration time_internal::ToUnixDuration (Time t) friend
UniversalEpoch
Time UniversalEpoch () friend
Definition at line 811 of file time.h.
{
  // 719162 is the number of days from 0001-01-01 to 1970-01-01,
  // assuming the Gregorian calendar.
  return Time(
      time_internal::MakeDuration(-24 * 719162 * int64_t{3600}, uint32_t{0}));
}
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/time/time.h
open_spiel/abseil-cpp/absl/time/time.cc