open spiel: open_spiel::ContiguousAllocator Class Reference
open_spiel::ContiguousAllocator Class Reference
#include <observer.h>
Public Member Functions
ContiguousAllocator (absl::Span< float > data)
SpanTensor Get (absl::string_view name, const absl::InlinedVector< int, 4 > &shape) override
Public Member Functions inherited from open_spiel::Allocator
virtual ~Allocator ()=default
Detailed Description
Definition at line 174 of file observer.h.
Constructor & Destructor Documentation
ContiguousAllocator()
open_spiel::ContiguousAllocator::ContiguousAllocator (absl::Span< float > data) inline
Definition at line 176 of file observer.h.
                                            : data_(data), offset_(0) {
    absl::c_fill(data, 0);
  }
References absl::c_fill().
Member Function Documentation
Get()
SpanTensor open_spiel::ContiguousAllocator::Get (absl::string_view name, const absl::InlinedVector< int, 4 > & shape) override virtual
Implements open_spiel::Allocator.
Definition at line 28 of file observer.cc.
{
  const int size = absl::c_accumulate(shape, 1, std::multiplies<int>());
  SPIEL_DCHECK_LE(offset_, data_.size());
  auto buffer = data_.subspan(offset_, size);
  offset_ += size;
  return SpanTensor(SpanTensorInfo(name, shape), buffer);
}
References absl::c_accumulate(), name, absl::Span< T >::size(), size, SPIEL_DCHECK_LE, and absl::Span< T >::subspan().
The documentation for this class was generated from the following files:
open_spiel/observer.h
open_spiel/observer.cc