open spiel: absl::cord_internal::CordRepRing::Filler Class Reference
absl::cord_internal::CordRepRing::Filler Class Reference
Public Member Functions
Filler (CordRepRing *rep, index_type pos)
index_type head () const
index_type pos () const
void Add (CordRep *child, size_t offset, pos_type end_pos)
Detailed Description
Definition at line 112 of file cord_rep_ring.cc.
Constructor & Destructor Documentation
Filler()
absl::cord_internal::CordRepRing::Filler::Filler (CordRepRing * rep, index_type pos) inline
Definition at line 114 of file cord_rep_ring.cc.
: rep_(rep), head_(pos), pos_(pos) {}
Member Function Documentation
Add()
void absl::cord_internal::CordRepRing::Filler::Add (CordRep * child, size_t offset, pos_type end_pos) inline
Definition at line 119 of file cord_rep_ring.cc.
{
    rep_->entry_end_pos()[pos_] = end_pos;
    rep_->entry_child()[pos_] = child;
    rep_->entry_data_offset()[pos_] = static_cast<offset_type>(offset);
    pos_ = rep_->advance(pos_);
  }
Referenced by absl::cord_internal::CordRepRing::Append(), and absl::cord_internal::CordRepRing::Prepend().
head()
index_type absl::cord_internal::CordRepRing::Filler::head () const inline
Definition at line 116 of file cord_rep_ring.cc.
{ return head_; }
Referenced by absl::cord_internal::CordRepRing::Prepend().
pos()
index_type absl::cord_internal::CordRepRing::Filler::pos () const inline
Definition at line 117 of file cord_rep_ring.cc.
{ return pos_; }
Referenced by absl::cord_internal::CordRepRing::Append().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_ring.cc