open spiel: TransTable Class Reference
TransTable Class Reference
#include <TransTable.h>
Public Member Functions
TransTable ()
virtual ~TransTable ()
virtual void Init (const int handLookup[][15])
virtual void SetMemoryDefault (const int megabytes)
virtual void SetMemoryMaximum (const int megabytes)
virtual void MakeTT ()
virtual void ResetMemory (const TTresetReason reason)
virtual void ReturnAllMemory ()
virtual double MemoryInUse () const
virtual nodeCardsType const * Lookup (const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[], const int limit, bool &lowerFlag)
virtual void Add (const int trick, const int hand, const unsigned short aggrTarget[], const unsigned short winRanksArg[], const nodeCardsType &first, const bool flag)
virtual void PrintSuits (ofstream &fout, const int trick, const int hand) const
virtual void PrintAllSuits (ofstream &fout) const
virtual void PrintSuitStats (ofstream &fout, const int trick, const int hand) const
virtual void PrintAllSuitStats (ofstream &fout) const
virtual void PrintSummarySuitStats (ofstream &fout) const
virtual void PrintEntriesDist (ofstream &fout, const int trick, const int hand, const int handDist[]) const
virtual void PrintEntriesDistAndCards (ofstream &fout, const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[]) const
virtual void PrintEntries (ofstream &fout, const int trick, const int hand) const
virtual void PrintAllEntries (ofstream &fout) const
virtual void PrintEntryStats (ofstream &fout, const int trick, const int hand) const
virtual void PrintAllEntryStats (ofstream &fout) const
virtual void PrintSummaryEntryStats (ofstream &fout) const
virtual void PrintPageSummary (ofstream &fout) const
virtual void PrintNodeStats (ofstream &fout) const
virtual void PrintResetStats (ofstream &fout) const
Detailed Description
Definition at line 64 of file TransTable.h.
Constructor & Destructor Documentation
TransTable()
TransTable::TransTable () inline
Definition at line 67 of file TransTable.h.
{};
~TransTable()
virtual TransTable::~TransTable () inline virtual
Definition at line 69 of file TransTable.h.
{};
Member Function Documentation
Add()
virtual void TransTable::Add (const int trick, const int hand, const unsigned short aggrTarget[], const unsigned short winRanksArg[], const nodeCardsType & first, const bool flag) inline virtual
Reimplemented in TransTableL, and TransTableS.
Definition at line 93 of file TransTable.h.
                      {};
Referenced by ABsearch0().
Init()
virtual void TransTable::Init (const int handLookup[][15]) inline virtual
Reimplemented in TransTableL, and TransTableS.
Definition at line 71 of file TransTable.h.
{};
Referenced by SetDealTables().
Lookup()
virtual nodeCardsType const * TransTable::Lookup (const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[], const int limit, bool & lowerFlag) inline virtual
Reimplemented in TransTableL, and TransTableS.
Definition at line 85 of file TransTable.h.
                      {return NULL;};
Referenced by ABsearch0().
MakeTT()
virtual void TransTable::MakeTT () inline virtual
Reimplemented in TransTableL, and TransTableS.
Definition at line 77 of file TransTable.h.
{};
MemoryInUse()
virtual double TransTable::MemoryInUse () const inline virtual
Reimplemented in TransTableL, and TransTableS.
Definition at line 83 of file TransTable.h.
{return 0.;};
Referenced by AnalyseLaterBoard(), ResetBestMoves(), SolveBoardInternal(), and SolveSameBoard().
PrintAllEntries()
virtual void TransTable::PrintAllEntries (ofstream & fout) const inline virtual
Reimplemented in TransTableL.
Definition at line 135 of file TransTable.h.
{};
PrintAllEntryStats()
virtual void TransTable::PrintAllEntryStats (ofstream & fout) const inline virtual
Reimplemented in TransTableL.
Definition at line 142 of file TransTable.h.
{};
PrintAllSuits()
virtual void TransTable::PrintAllSuits (ofstream & fout) const inline virtual
Reimplemented in TransTableL.
Definition at line 106 of file TransTable.h.
{};
PrintAllSuitStats()
virtual void TransTable::PrintAllSuitStats (ofstream & fout) const inline virtual
Reimplemented in TransTableL.
Definition at line 113 of file TransTable.h.
{};
PrintEntries()
virtual void TransTable::PrintEntries (ofstream & fout, const int trick, const int hand) const inline virtual
Reimplemented in TransTableL.
Definition at line 130 of file TransTable.h.
                            {};
PrintEntriesDist()
virtual void TransTable::PrintEntriesDist (ofstream & fout, const int trick, const int hand, const int handDist[]) const inline virtual
Reimplemented in TransTableL.
Definition at line 117 of file TransTable.h.
                                  {};
PrintEntriesDistAndCards()
virtual void TransTable::PrintEntriesDistAndCards (ofstream & fout, const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[]) const inline virtual
Reimplemented in TransTableL.
Definition at line 123 of file TransTable.h.
                                  {};
PrintEntryStats()
virtual void TransTable::PrintEntryStats (ofstream & fout, const int trick, const int hand) const inline virtual
Reimplemented in TransTableL.
Definition at line 137 of file TransTable.h.
                            {};
PrintNodeStats()
virtual void TransTable::PrintNodeStats (ofstream & fout) const inline virtual
Reimplemented in TransTableS.
Definition at line 148 of file TransTable.h.
{};
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().
PrintPageSummary()
virtual void TransTable::PrintPageSummary (ofstream & fout) const inline virtual
Definition at line 146 of file TransTable.h.
{};
PrintResetStats()
virtual void TransTable::PrintResetStats (ofstream & fout) const inline virtual
Reimplemented in TransTableS.
Definition at line 150 of file TransTable.h.
{};
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().
PrintSuits()
virtual void TransTable::PrintSuits (ofstream & fout, const int trick, const int hand) const inline virtual
Reimplemented in TransTableL.
Definition at line 101 of file TransTable.h.
                            {};
PrintSuitStats()
virtual void TransTable::PrintSuitStats (ofstream & fout, const int trick, const int hand) const inline virtual
Reimplemented in TransTableL.
Definition at line 108 of file TransTable.h.
                            {};
PrintSummaryEntryStats()
virtual void TransTable::PrintSummaryEntryStats (ofstream & fout) const inline virtual
Reimplemented in TransTableL.
Definition at line 144 of file TransTable.h.
{};
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().
PrintSummarySuitStats()
virtual void TransTable::PrintSummarySuitStats (ofstream & fout) const inline virtual
Reimplemented in TransTableL.
Definition at line 115 of file TransTable.h.
{};
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().
ResetMemory()
virtual void TransTable::ResetMemory (const TTresetReason reason) inline virtual
Reimplemented in TransTableL, and TransTableS.
Definition at line 79 of file TransTable.h.
{};
Referenced by SolveBoardInternal().
ReturnAllMemory()
virtual void TransTable::ReturnAllMemory () inline virtual
Reimplemented in TransTableL, and TransTableS.
Definition at line 81 of file TransTable.h.
{};
SetMemoryDefault()
virtual void TransTable::SetMemoryDefault (const int megabytes) inline virtual
Reimplemented in TransTableL, and TransTableS.
Definition at line 73 of file TransTable.h.
{};
SetMemoryMaximum()
virtual void TransTable::SetMemoryMaximum (const int megabytes) inline virtual
Reimplemented in TransTableL, and TransTableS.
Definition at line 75 of file TransTable.h.
{};
The documentation for this class was generated from the following file:
open_spiel/games/bridge/double_dummy_solver/src/TransTable.h