open spiel: open_spiel::file::File Class Reference
open_spiel::file::File Class Reference
#include <file.h>
Public Member Functions
File (const std::string &filename, const std::string &mode)
File (File &&other)
File & operator= (File &&other)
File (const File &)=delete
File & operator= (const File &)=delete
~File ()
bool Flush ()
std::int64_t Tell ()
bool Seek (std::int64_t offset)
std::string Read (std::int64_t count)
std::string ReadContents ()
bool Write (absl::string_view str)
std::int64_t Length ()
Detailed Description
Definition at line 28 of file file.h.
Constructor & Destructor Documentation
File() [1/3]
open_spiel::file::File::File (const std::string & filename, const std::string & mode)
Definition at line 41 of file file.cc.
{
  fd_.reset(static_cast<FileImpl*>(std::fopen(filename.c_str(), mode.c_str())));
  SPIEL_CHECK_TRUE(fd_);
}
References SPIEL_CHECK_TRUE.
File() [2/3]
open_spiel::file::File::File (File && other) default
File() [3/3]
open_spiel::file::File::File (const File &) delete
~File()
open_spiel::file::File::~File ()
Definition at line 46 of file file.cc.
            {
  if (fd_) {
    Flush();
    Close();
  }
}
References Flush().
Member Function Documentation
Flush()
bool open_spiel::file::File::Flush ()
Definition at line 57 of file file.cc.
{ return !std::fflush(fd_.get()); }
Referenced by open_spiel::DataLoggerJsonLines::Flush(), open_spiel::FileLogger::Print(), and ~File().
Length()
std::int64_t open_spiel::file::File::Length ()
Definition at line 80 of file file.cc.
{
  std::int64_t current = std::ftell(fd_.get());
  std::fseek(fd_.get(), 0, SEEK_END);
  std::int64_t length = std::ftell(fd_.get());
  std::fseek(fd_.get(), current, SEEK_SET);
  return length;
}
Referenced by ReadContents().
operator=() [1/2]
File & open_spiel::file::File::operator= (const File &) delete
operator=() [2/2]
File & open_spiel::file::File::operator= (File && other) default
Read()
std::string open_spiel::file::File::Read (std::int64_t count)
Definition at line 63 of file file.cc.
{
  std::string out(count, '\0');
  int read = std::fread(out.data(), sizeof(char), count, fd_.get());
  out.resize(read);
  return out;
}
References out.
Referenced by ReadContents().
ReadContents()
std::string open_spiel::file::File::ReadContents ()
Definition at line 70 of file file.cc.
{
  Seek(0);
  return Read(Length());
}
References Length(), Read(), and Seek().
Referenced by main(), open_spiel::colored_trails::ParseBoardsFile(), and open_spiel::algorithms::torch_az::StartInfoFromLearnerJson().
Seek()
bool open_spiel::file::File::Seek (std::int64_t offset)
Definition at line 59 of file file.cc.
{
  return !std::fseek(fd_.get(), offset, SEEK_SET);
}
Referenced by ReadContents().
Tell()
std::int64_t open_spiel::file::File::Tell ()
Definition at line 58 of file file.cc.
{ return std::ftell(fd_.get()); }
Write()
bool open_spiel::file::File::Write (absl::string_view str)
Definition at line 75 of file file.cc.
{
  return std::fwrite(str.data(), sizeof(char), str.size(), fd_.get()) ==
         str.size();
}
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), main(), open_spiel::FileLogger::Print(), and open_spiel::DataLoggerJsonLines::Write().
The documentation for this class was generated from the following files:
open_spiel/utils/file.h
open_spiel/utils/file.cc