open spiel: open_spiel::oh_hell::OhHellState Class Reference
open_spiel::oh_hell::OhHellState Class Reference
#include <oh_hell.h>
Public Member Functions
OhHellState (std::shared_ptr< const Game > game, int num_players, DeckProperties deck_props, int num_tricks_fixed, bool off_bid_penalty, int points_per_trick)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
virtual std::string ObservationString (Player player) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 134 of file oh_hell.h.
Constructor & Destructor Documentation
OhHellState()
open_spiel::oh_hell::OhHellState::OhHellState (std::shared_ptr< const Game > game, int num_players, DeckProperties deck_props, int num_tricks_fixed, bool off_bid_penalty, int points_per_trick)
Definition at line 110 of file oh_hell.cc.
    : State(game),
      num_players_(num_players),
      num_tricks_fixed_(num_tricks_fixed),
      deck_props_(deck_props),
      off_bid_penalty_(off_bid_penalty),
      points_per_trick_(points_per_trick) {
  bids_.resize(num_players_);
  // need to differentiate between no bid and a bid of 0
  std::fill(bids_.begin(), bids_.end(), kInvalidBid);
  num_tricks_won_.resize(num_players_);
  returns_.resize(num_players_);
  holder_.resize(deck_props_.NumCards());
  initial_deal_.resize(deck_props_.NumCards());
}
References open_spiel::oh_hell::kInvalidBid, and open_spiel::oh_hell::DeckProperties::NumCards().
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::oh_hell::OhHellState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 141 of file oh_hell.cc.
{
  switch (phase_) {
    case Phase::kChooseNumTricks:
    case Phase::kDealer:
      return absl::StrFormat("%d", action);
    case Phase::kDeal:
    case Phase::kPlay:
      return deck_props_.CardString(action);
    case Phase::kBid:
      return absl::StrFormat("%d", action - deck_props_.NumCards());
    default:
      return "";
  }
}
References action, open_spiel::oh_hell::DeckProperties::CardString(), open_spiel::oh_hell::DeckProperties::NumCards(), and absl::StrFormat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::oh_hell::OhHellState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 324 of file oh_hell.cc.
{
  std::vector<std::pair<Action, double>> outcomes;
  double p;
  if (phase_ == Phase::kChooseNumTricks) {
    // uniform randomly select between all legal numbers of tricks possible
    // given the number of players and size of the deck
    if (num_tricks_fixed_ < kMinNumTricks) {
      p = 1.0 / static_cast<double>(MaxNumTricks());
      for (int i = 0; i < MaxNumTricks(); ++i) outcomes.emplace_back(i + 1, p);
    } else {
      outcomes.emplace_back(num_tricks_fixed_, 1.0);
    }
  } else if (phase_ == Phase::kDealer) {
    // uniform randomly select a player
    p = 1.0 / static_cast<double>(num_players_);
    for (int i = 0; i < num_players_; ++i) outcomes.emplace_back(i, p);
  } else if (num_cards_dealt_ < num_players_ * num_tricks_ + kNumTrumpDeal) {
    // the only other chance nodes are when cards are dealt
    int num_cards_rem = deck_props_.NumCards() - num_cards_dealt_;
    outcomes.reserve(num_cards_rem);
    p = 1.0 / static_cast<double>(num_cards_rem);
    for (int card = 0; card < deck_props_.NumCards(); ++card) {
      if (!initial_deal_[card].has_value()) outcomes.emplace_back(card, p);
    }
  }
  return outcomes;
}
References i, open_spiel::oh_hell::kMinNumTricks, open_spiel::oh_hell::kNumTrumpDeal, and open_spiel::oh_hell::DeckProperties::NumCards().
Clone()
std::unique_ptr< State > open_spiel::oh_hell::OhHellState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 147 of file oh_hell.h.
{
    return std::unique_ptr<State>(new OhHellState(*this));
  }
References OhHellState().
CurrentPlayer()
Player open_spiel::oh_hell::OhHellState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 426 of file oh_hell.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  } else if (phase_ == Phase::kBid || phase_ == Phase::kPlay) {
    return current_player_;
  } else {
    return kChancePlayerId;
  }
}
References IsTerminal(), open_spiel::kChancePlayerId, and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::oh_hell::OhHellState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 352 of file oh_hell.cc.
{
  switch (phase_) {
    case Phase::kChooseNumTricks:
      return ApplyChooseNumTricksAction(action);
    case Phase::kDealer:
      return ApplyDealerAction(action);
    case Phase::kDeal:
      return ApplyDealAction(action);
    case Phase::kBid:
      return ApplyBiddingAction(action - deck_props_.NumCards());
    case Phase::kPlay:
      return ApplyPlayAction(action);
    case Phase::kGameOver:
      SpielFatalError("Cannot act in terminal states");
  }
}
References action, open_spiel::oh_hell::DeckProperties::NumCards(), and open_spiel::SpielFatalError().
InformationStateString()
std::string open_spiel::oh_hell::OhHellState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 456 of file oh_hell.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string rv = "";
  if (IsTerminal()) return ToString();
  if (phase_ == Phase::kChooseNumTricks) return rv;
  absl::StrAppend(&rv, FormatChooseNumTricks());
  if (phase_ == Phase::kDealer) return rv;
  absl::StrAppend(&rv, FormatDealer());
  absl::StrAppend(&rv, FormatNumCardsDealt());
  if (num_cards_dealt_ > num_players_ * num_tricks_) {
    absl::StrAppend(&rv, FormatTrump());
  }
  absl::StrAppend(&rv, FormatHand(player));
  if (num_cards_played_ > 0) absl::StrAppend(&rv, FormatPlay());
  absl::StrAppend(&rv, FormatBids());
  return rv;
}
References IsTerminal(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and ToString().
InformationStateTensor()
void open_spiel::oh_hell::OhHellState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 475 of file oh_hell.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::fill(values.begin(), values.end(), 0.0);
  SPIEL_CHECK_EQ(values.size(), game_->InformationStateTensorSize());
  if (phase_ != Phase::kBid && phase_ != Phase::kPlay) return;
  auto ptr = values.begin();
  // total number of tricks
  ptr[num_tricks_ - 1] = 1;
  ptr += MaxNumTricks();
  // which player is dealer
  ptr[dealer_] = 1;
  ptr += num_players_;
  // trump
  ptr[trump_] = 1;
  ptr += deck_props_.NumCards();
  // initial hand
  for (int i = 0; i < deck_props_.NumCards(); ++i)
    if (initial_deal_[i] == player) ptr[i] = 1;
  ptr += deck_props_.NumCards();
  // Current hand
  for (int i = 0; i < deck_props_.NumCards(); ++i)
    if (holder_[i] == player) ptr[i] = 1;
  ptr += deck_props_.NumCards();
  // all bids
  for (Player p = 0; p < num_players_; ++p) {
    ptr[bids_[p] + 1] = 1;
    // need to account for bid of 0 and if player hasn't bid yet
    ptr += MaxNumTricks() + 2;
  }
  // each player's number of tricks won so far (temperature encoding)
  for (Player p = 0; p < num_players_; ++p) {
    for (int i = 0; i < MaxNumTricks(); ++i) {
      if (num_tricks_won_[p] > i) ptr[i] = 1;
    }
    ptr += MaxNumTricks();
  }
  // History of tricks, each in the format: 0 1 ... n 0 1 ... n-1
  int current_trick = num_cards_played_ / num_players_;
  auto play_hist = history_.begin() + NumChanceActions() + num_players_;
  for (int i = 0; i <= current_trick; ++i) {
    Player leader = tricks_[i].Leader();
    ptr += std::max(leader, 0) * deck_props_.NumCards();
    for (int i = 0; i < num_players_; i++) {
      if (play_hist < history_.end()) {
        ptr[play_hist->action] = 1;
        ++play_hist;
      }
      ptr += deck_props_.NumCards();
    }
    ptr += (num_players_ - std::max(leader, 0) - 1) * deck_props_.NumCards();
  }
  // Skip over unplayed tricks.
  int trick_tensor_size = (2 * num_players_ - 1) * deck_props_.NumCards();
  ptr += (MaxNumTricks() - current_trick - 1) * trick_tensor_size;
  SPIEL_CHECK_EQ(ptr, values.end());
}
References open_spiel::State::game_, open_spiel::State::history_, i, open_spiel::oh_hell::DeckProperties::NumCards(), player, ptr, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::oh_hell::OhHellState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 142 of file oh_hell.h.
{ return phase_ == Phase::kGameOver; }
Referenced by CurrentPlayer(), InformationStateString(), and ToString().
LegalActions()
std::vector< Action > open_spiel::oh_hell::OhHellState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 241 of file oh_hell.cc.
{
  switch (phase_) {
    case Phase::kChooseNumTricks:
      return ChooseNumTricksLegalActions();
    case Phase::kDealer:
      return DealerLegalActions();
    case Phase::kDeal:
      return DealLegalActions();
    case Phase::kBid:
      return BiddingLegalActions();
    case Phase::kPlay:
      return PlayLegalActions();
    default:
      return {};
  }
}
ResampleFromInfostate()
std::unique_ptr< State > open_spiel::oh_hell::OhHellState::ResampleFromInfostate (int player_id, std::function< double()> rng) const override virtual
Reimplemented from open_spiel::State.
Definition at line 538 of file oh_hell.cc.
{
  std::unique_ptr<State> clone = game_->NewInitialState();
  if (phase_ != Phase::kBid && phase_ != Phase::kPlay) return clone;
  // initial chance actions (choose num tricks and dealer)
  clone->ApplyAction(num_tricks_);
  clone->ApplyAction(dealer_);
  // deal needs to be consistent with the player's hand, and the opponent's
  // played cards
  std::vector<std::vector<int>> known(num_players_);
  for (int card = 0; card < deck_props_.NumCards(); ++card) {
    absl::optional<Player> p = initial_deal_[card];
    if (p.has_value() && (*p == player_id || !holder_[card].has_value())) {
      // if player_id was initially dealt the card, or if anyone was but no
      // longer holds it (because it was played), player_id knows where it was
      // dealt
      known[*p].push_back(card);
    }
  }
  // the only other known card is trump
  // apply num_tricks * num_players deal actions
  std::vector<int> known_deal_counter(num_players_, 0);
  for (int i = 0; i < num_players_ * num_tricks_; ++i) {
    Player deal_to = i % num_players_;
    if (known_deal_counter[deal_to] < known[deal_to].size()) {
      clone->ApplyAction(known[deal_to][known_deal_counter[deal_to]]);
      known_deal_counter[deal_to]++;
    } else {
      // deal randomly from the remaining unknown cards
      Action candidate = kInvalidAction;
      while (candidate == kInvalidAction) {
        candidate = SampleAction(clone->ChanceOutcomes(), rng()).first;
        absl::optional<Player> p = initial_deal_[candidate];
        if (candidate == trump_ ||  (p.has_value() &&
            (*p == player_id || !holder_[candidate].has_value()))) {
          // can't use this card if player_id has it, or if it was played by
          // any player
          candidate = kInvalidAction;
        }
      }
      clone->ApplyAction(candidate);
    }
  }
  // deal the trump card
  clone->ApplyAction(trump_);
  // now apply all of the bid and play phase actions in the same order as the
  // original state
  int start = kNumPreDealChanceActions + num_players_ * num_tricks_ + 1;
  for (size_t i = start; i < history_.size(); i++) {
    clone->ApplyAction(history_.at(i).action);
  }
  SPIEL_CHECK_EQ(History().size(), clone->History().size());
  SPIEL_CHECK_EQ(InformationStateString(player_id),
                 clone->InformationStateString(player_id));
  return clone;
}
References open_spiel::State::game_, open_spiel::State::History(), open_spiel::State::history_, i, open_spiel::State::InformationStateString(), open_spiel::kInvalidAction, open_spiel::oh_hell::kNumPreDealChanceActions, open_spiel::oh_hell::DeckProperties::NumCards(), open_spiel::SampleAction(), size, and SPIEL_CHECK_EQ.
Returns()
std::vector< double > open_spiel::oh_hell::OhHellState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 143 of file oh_hell.h.
{ return returns_; }
ToString()
std::string open_spiel::oh_hell::OhHellState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 128 of file oh_hell.cc.
{
  std::string rv = absl::StrCat(FormatPhase(), FormatChooseNumTricks());
  absl::StrAppend(&rv, FormatDealer());
  absl::StrAppend(&rv, FormatDeal());
  if (num_cards_dealt_ > num_players_ * num_tricks_) {
    absl::StrAppend(&rv, FormatTrump());
  }
  if (num_cards_played_ > 0) absl::StrAppend(&rv, FormatPlay());
  absl::StrAppend(&rv, FormatBids());
  if (IsTerminal()) absl::StrAppend(&rv, FormatResult());
  return rv;
}
References IsTerminal(), absl::StrAppend(), and absl::StrCat().
Referenced by InformationStateString().
The documentation for this class was generated from the following files:
open_spiel/games/oh_hell/oh_hell.h
open_spiel/games/oh_hell/oh_hell.cc