open spiel: absl::synchronization_internal::GraphCyclesTest Class Reference
absl::synchronization_internal::GraphCyclesTest Class Reference
Public Member Functions
GraphCyclesTest ()
bool AddEdge (int x, int y)
void AddMultiples ()
std::string Path (int x, int y)
Static Public Member Functions
static void * Ptr (int i)
static int Num (void *ptr)
Public Attributes
IdMap id_
GraphCycles g_
Detailed Description
Definition at line 354 of file graphcycles_test.cc.
Constructor & Destructor Documentation
GraphCyclesTest()
absl::synchronization_internal::GraphCyclesTest::GraphCyclesTest () inline
Definition at line 368 of file graphcycles_test.cc.
                    {
    for (int i = 0; i < 100; i++) {
      id_[i] = g_.GetId(Ptr(i));
    }
    CheckInvariants(g_);
  }
References g_, absl::synchronization_internal::GraphCycles::GetId(), absl::i, id_, and Ptr().
Member Function Documentation
AddEdge()
bool absl::synchronization_internal::GraphCyclesTest::AddEdge (int x, int y) inline
Definition at line 375 of file graphcycles_test.cc.
{
    return g_.InsertEdge(Get(id_, x), Get(id_, y));
  }
References g_, id_, absl::synchronization_internal::GraphCycles::InsertEdge(), absl::x, and y.
Referenced by AddMultiples().
AddMultiples()
void absl::synchronization_internal::GraphCyclesTest::AddMultiples () inline
Definition at line 379 of file graphcycles_test.cc.
                      {
    // For every node x > 0: add edge to 2*x, 3*x
    for (int x = 1; x < 25; x++) {
      EXPECT_TRUE(AddEdge(x, 2*x)) << x;
      EXPECT_TRUE(AddEdge(x, 3*x)) << x;
    }
    CheckInvariants(g_);
  }
References AddEdge(), g_, and absl::x.
Num()
static int absl::synchronization_internal::GraphCyclesTest::Num (void * ptr) inline static
Definition at line 363 of file graphcycles_test.cc.
{
    return static_cast<int>(reinterpret_cast<uintptr_t>(ptr));
  }
References ptr.
Referenced by Path().
Path()
std::string absl::synchronization_internal::GraphCyclesTest::Path (int x, int y) inline
Definition at line 388 of file graphcycles_test.cc.
{
    GraphId path[5];
    int np = g_.FindPath(Get(id_, x), Get(id_, y), ABSL_ARRAYSIZE(path), path);
    std::string result;
    for (int i = 0; i < np; i++) {
      if (i >= ABSL_ARRAYSIZE(path)) {
        result += " ...";
        break;
      }
      if (!result.empty()) result.push_back(' ');
      char buf[20];
      snprintf(buf, sizeof(buf), "%d", Num(g_.Ptr(path[i])));
      result += buf;
    }
    return result;
  }
References ABSL_ARRAYSIZE, buf, absl::synchronization_internal::GraphCycles::FindPath(), g_, absl::i, id_, Num(), absl::synchronization_internal::GraphCycles::Ptr(), absl::x, and y.
Ptr()
static void * absl::synchronization_internal::GraphCyclesTest::Ptr (int i) inline static
Definition at line 359 of file graphcycles_test.cc.
{
    return reinterpret_cast<void*>(static_cast<uintptr_t>(i));
  }
References absl::i.
Referenced by GraphCyclesTest().
Member Data Documentation
g_
GraphCycles absl::synchronization_internal::GraphCyclesTest::g_
Definition at line 357 of file graphcycles_test.cc.
Referenced by AddEdge(), AddMultiples(), GraphCyclesTest(), and Path().
id_
IdMap absl::synchronization_internal::GraphCyclesTest::id_
Definition at line 356 of file graphcycles_test.cc.
Referenced by AddEdge(), GraphCyclesTest(), and Path().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/synchronization/internal/graphcycles_test.cc