open spiel: open_spiel::kriegspiel::KriegspielObserver Class Reference
open_spiel::kriegspiel::KriegspielObserver Class Reference
Public Member Functions
KriegspielObserver (IIGObservationType iig_obs_type)
void WriteTensor (const State &observed_state, int player, Allocator *allocator) const override
std::string StringFrom (const State &observed_state, int player) const override
Public Member Functions inherited from open_spiel::Observer
Observer (bool has_string, bool has_tensor)
bool HasString () const
bool HasTensor () const
virtual ~Observer ()=default
Additional Inherited Members
Protected Attributes inherited from open_spiel::Observer
bool has_string_
bool has_tensor_
Detailed Description
Definition at line 85 of file kriegspiel.cc.
Constructor & Destructor Documentation
KriegspielObserver()
open_spiel::kriegspiel::KriegspielObserver::KriegspielObserver (IIGObservationType iig_obs_type) inline explicit
Definition at line 87 of file kriegspiel.cc.
      : Observer(/*has_string=*/ObserverHasString(iig_obs_type),
                 /*has_tensor=*/ObserverHasTensor(iig_obs_type)),
        iig_obs_type_(iig_obs_type) {}
Member Function Documentation
StringFrom()
std::string open_spiel::kriegspiel::KriegspielObserver::StringFrom (const State & observed_state, int player) const inline override virtual
Implements open_spiel::Observer.
Definition at line 121 of file kriegspiel.cc.
{
    auto &state =
        open_spiel::down_cast<const KriegspielState &>(observed_state);
    auto &game =
        open_spiel::down_cast<const KriegspielGame &>(*state.GetGame());
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, game.NumPlayers());
    if (iig_obs_type_.perfect_recall) {
      SpielFatalError(
          "KriegspielObserver: string with perfect recall is unimplemented");
    }
    if (iig_obs_type_.public_info &&
        iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      // No observation before the first move
      if (state.MoveMsgHistory().empty()) {
        return std::string();
      }
      // Write last umpire message
      return state.last_umpire_msg_->ToString();
    } else {
      SpielFatalError(
          "KriegspielObserver: string with imperfect recall is implemented only"
          " for the (default) observation type.");
    }
  }
References open_spiel::down_cast(), open_spiel::kSinglePlayer, open_spiel::IIGObservationType::perfect_recall, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and state.
WriteTensor()
void open_spiel::kriegspiel::KriegspielObserver::WriteTensor (const State & observed_state, int player, Allocator * allocator) const inline override virtual
Implements open_spiel::Observer.
Definition at line 92 of file kriegspiel.cc.
{
    auto &state =
        open_spiel::down_cast<const KriegspielState &>(observed_state);
    auto &game =
        open_spiel::down_cast<const KriegspielGame &>(*state.GetGame());
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, game.NumPlayers());
    chess::Color color = chess::PlayerToColor(player);
    if (iig_obs_type_.perfect_recall) {
      SpielFatalError(
          "KriegspielObserver: tensor with perfect recall not implemented.");
    }
    if (iig_obs_type_.public_info) {
      WritePublicInfoTensor(state, "public", allocator);
    }
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      std::string prefix = "private";
      WritePrivateInfoTensor(state, player, prefix, allocator);
    } else if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers) {
      for (int i = 0; i < chess::NumPlayers(); ++i) {
        std::string prefix = chess::ColorToString(color);
        WritePrivateInfoTensor(state, i, prefix, allocator);
      }
    }
  }
References open_spiel::chess::ColorToString(), open_spiel::down_cast(), i, open_spiel::kAllPlayers, open_spiel::kSinglePlayer, open_spiel::chess::NumPlayers(), open_spiel::IIGObservationType::perfect_recall, player, open_spiel::chess::PlayerToColor(), open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and state.
The documentation for this class was generated from the following file:
open_spiel/games/kriegspiel/kriegspiel.cc