open spiel: open_spiel::efg_game::EFGGame Class Reference
open_spiel::efg_game::EFGGame Class Reference
#include <efg_game.h>
Public Member Functions
EFGGame (const GameParameters &params)
EFGGame (const std::string &data)
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int NumDistinctActions () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int MaxMoveNumber () const override
int MaxHistoryLength () const override
std::vector< int > InformationStateTensorShape () const override
Action GetAction (const std::string &label) const
Action GetChanceAction (const std::string &label) const
Action AddOrGetAction (const std::string &label)
Action AddOrGetChanceOutcome (const std::string &label)
std::string GetInformationStateStringByName (Player player, const std::string &name) const
std::string GetInformationStateStringByNumber (Player player, int number) const
int NumInfoStates (Player player) const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual std::vector< int > ObservationTensorShape () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 108 of file efg_game.h.
Constructor & Destructor Documentation
EFGGame() [1/2]
open_spiel::efg_game::EFGGame::EFGGame (const GameParameters & params) explicit
Definition at line 280 of file efg_game.cc.
    : Game(kGameType, params),
      filename_(ParameterValue<std::string>("filename")),
      string_data_(file::ReadContentsFromFile(filename_, "r")),
      pos_(0),
      num_chance_nodes_(0),
      max_actions_(0),
      max_depth_(0),
      constant_sum_(true),
      identical_payoffs_(true),
      general_sum_(true),
      perfect_information_(true) {
  SPIEL_CHECK_GT(string_data_.size(), 0);
  // Now parse the string data into a data structure.
  ParseGame();
}
References SPIEL_CHECK_GT.
EFGGame() [2/2]
open_spiel::efg_game::EFGGame::EFGGame (const std::string & data) explicit
Definition at line 298 of file efg_game.cc.
    : Game(kGameType, {}),
      string_data_(data),
      pos_(0),
      num_chance_nodes_(0),
      max_actions_(0),
      max_depth_(0),
      constant_sum_(true),
      identical_payoffs_(true),
      general_sum_(true),
      perfect_information_(true) {
  ParseGame();
}
Member Function Documentation
AddOrGetAction()
Action open_spiel::efg_game::EFGGame::AddOrGetAction (const std::string & label) inline
Definition at line 143 of file efg_game.h.
{
    auto iter = action_ids_.find(label);
    if (iter != action_ids_.end()) {
      return iter->second;
    }
    Action new_action = action_ids_.size();
    action_ids_[label] = new_action;
    return new_action;
  }
AddOrGetChanceOutcome()
Action open_spiel::efg_game::EFGGame::AddOrGetChanceOutcome (const std::string & label) inline
Definition at line 153 of file efg_game.h.
{
    auto iter = chance_action_ids_.find(label);
    if (iter != chance_action_ids_.end()) {
      return iter->second;
    }
    Action new_action = chance_action_ids_.size();
    chance_action_ids_[label] = new_action;
    return new_action;
  }
GetAction()
Action open_spiel::efg_game::EFGGame::GetAction (const std::string & label) const inline
Definition at line 130 of file efg_game.h.
{
    auto iter = action_ids_.find(label);
    SPIEL_CHECK_TRUE(iter != action_ids_.end());
    return iter->second;
  }
References SPIEL_CHECK_TRUE.
Referenced by open_spiel::efg_game::EFGGameTabularPolicy().
GetChanceAction()
Action open_spiel::efg_game::EFGGame::GetChanceAction (const std::string & label) const inline
Definition at line 137 of file efg_game.h.
{
    auto iter = chance_action_ids_.find(label);
    SPIEL_CHECK_TRUE(iter != chance_action_ids_.end());
    return iter->second;
  }
References SPIEL_CHECK_TRUE.
GetInformationStateStringByName()
std::string open_spiel::efg_game::EFGGame::GetInformationStateStringByName (Player player, const std::string & name) const
Definition at line 772 of file efg_game.cc.
{
  const auto& iter = infoset_name_to_player_num_.find(name);
  if (iter == infoset_name_to_player_num_.end()) {
    SpielFatalError(absl::StrCat("Information state not found: ", name));
  }
  if (iter->second.first != player) {
    SpielFatalError(absl::StrCat("Player mismatch in lookup by name: ", name,
                                 " ", player, " ", iter->second.first));
  }
  return EFGInformationStateString(player, player, iter->second.second, name);
}
References name, player, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::efg_game::EFGGameTabularPolicy().
GetInformationStateStringByNumber()
std::string open_spiel::efg_game::EFGGame::GetInformationStateStringByNumber (Player player, int number) const
Definition at line 785 of file efg_game.cc.
{
  const auto& iter = infoset_player_num_to_name_.find({player, number});
  if (iter == infoset_player_num_to_name_.end()) {
    SpielFatalError(
        absl::StrCat("Information state not found: ", player, ",", number));
  }
  return EFGInformationStateString(player, player, number, iter->second);
}
References player, open_spiel::SpielFatalError(), and absl::StrCat().
InformationStateTensorShape()
std::vector< int > open_spiel::efg_game::EFGGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 266 of file efg_game.cc.
{
  int max_player_infosets = 0;
  for (Player p = 0; p < num_players_; ++p) {
    max_player_infosets = std::max<int>(max_player_infosets,
                                        infoset_num_to_states_count_[p].size());
  }
  return {
    num_players_ + 1 +    // Current player (plus special for terminal).
    num_players_ +        // Current observing player.
    max_player_infosets   // Information set number (for the current player).
  };
}
References size.
MaxChanceNodesInHistory()
int open_spiel::efg_game::EFGGame::MaxChanceNodesInHistory () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 260 of file efg_game.cc.
{ return num_chance_nodes_; }
MaxChanceOutcomes()
int open_spiel::efg_game::EFGGame::MaxChanceOutcomes () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 241 of file efg_game.cc.
{ return chance_action_ids_.size(); }
MaxGameLength()
int open_spiel::efg_game::EFGGame::MaxGameLength () const override virtual
Implements open_spiel::Game.
Definition at line 258 of file efg_game.cc.
{ return max_depth_; }
MaxHistoryLength()
int open_spiel::efg_game::EFGGame::MaxHistoryLength () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 264 of file efg_game.cc.
{ return max_depth_; }
MaxMoveNumber()
int open_spiel::efg_game::EFGGame::MaxMoveNumber () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 262 of file efg_game.cc.
{ return max_depth_; }
MaxUtility()
double open_spiel::efg_game::EFGGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 256 of file efg_game.cc.
{ return max_util_.value(); }
References absl::optional< T >::value().
MinUtility()
double open_spiel::efg_game::EFGGame::MinUtility () const override virtual
Implements open_spiel::Game.
Definition at line 247 of file efg_game.cc.
{ return min_util_.value(); }
References absl::optional< T >::value().
NewInitialState()
std::unique_ptr< State > open_spiel::efg_game::EFGGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 112 of file efg_game.h.
{
    return std::unique_ptr<State>(
        new EFGState(shared_from_this(), nodes_[0].get()));
  }
References get().
NumDistinctActions()
int open_spiel::efg_game::EFGGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 243 of file efg_game.cc.
{ return action_ids_.size(); }
NumInfoStates()
int open_spiel::efg_game::EFGGame::NumInfoStates (Player player) const inline
Definition at line 175 of file efg_game.h.
{
    return infoset_num_to_states_count_[player].size();
  }
References player.
NumPlayers()
int open_spiel::efg_game::EFGGame::NumPlayers () const override virtual
Implements open_spiel::Game.
Definition at line 245 of file efg_game.cc.
{ return num_players_; }
UtilitySum()
absl::optional< double > open_spiel::efg_game::EFGGame::UtilitySum () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 249 of file efg_game.cc.
{
  if (constant_sum_)
    return util_sum_;
  else
    return absl::nullopt;
}
The documentation for this class was generated from the following files:
open_spiel/games/efg_game/efg_game.h
open_spiel/games/efg_game/efg_game.cc