open spiel: open_spiel::algorithms::torch_az::VPNetModel::LossInfo Class Reference
open_spiel::algorithms::torch_az::VPNetModel::LossInfo Class Reference
#include <vpnet.h>
Public Member Functions
LossInfo ()
LossInfo (double policy, double value, double l2)
LossInfo & operator+= (const LossInfo &other)
double Policy () const
double Value () const
double L2 () const
double Total () const
Detailed Description
Definition at line 41 of file vpnet.h.
Constructor & Destructor Documentation
LossInfo() [1/2]
open_spiel::algorithms::torch_az::VPNetModel::LossInfo::LossInfo () inline
Definition at line 43 of file vpnet.h.
{}
LossInfo() [2/2]
open_spiel::algorithms::torch_az::VPNetModel::LossInfo::LossInfo (double policy, double value, double l2) inline
Definition at line 44 of file vpnet.h.
        : policy_(policy), value_(value), l2_(l2), batches_(1) {}
Member Function Documentation
L2()
double open_spiel::algorithms::torch_az::VPNetModel::LossInfo::L2 () const inline
Definition at line 59 of file vpnet.h.
{ return l2_ / batches_; }
Referenced by open_spiel::algorithms::torch_az::learner(), and Total().
operator+=()
LossInfo & open_spiel::algorithms::torch_az::VPNetModel::LossInfo::operator+= (const LossInfo & other) inline
Definition at line 48 of file vpnet.h.
{
      policy_ += other.policy_;
      value_ += other.value_;
      l2_ += other.l2_;
      batches_ += other.batches_;
      return *this;
    }
Policy()
double open_spiel::algorithms::torch_az::VPNetModel::LossInfo::Policy () const inline
Definition at line 57 of file vpnet.h.
{ return policy_ / batches_; }
Referenced by open_spiel::algorithms::torch_az::learner(), and Total().
Total()
double open_spiel::algorithms::torch_az::VPNetModel::LossInfo::Total () const inline
Definition at line 60 of file vpnet.h.
{ return Policy() + Value() + L2(); }
References L2(), Policy(), and Value().
Referenced by open_spiel::algorithms::torch_az::learner().
Value()
double open_spiel::algorithms::torch_az::VPNetModel::LossInfo::Value () const inline
Definition at line 58 of file vpnet.h.
{ return value_ / batches_; }
Referenced by open_spiel::algorithms::torch_az::learner(), and Total().
The documentation for this class was generated from the following file:
open_spiel/algorithms/alpha_zero_torch/vpnet.h