open spiel: open_spiel::coin_game::CoinState Class Reference
open_spiel::coin_game::CoinState Class Reference
#include <coin_game.h>
Public Member Functions
CoinState (std::shared_ptr< const Game > game)
CoinState (const CoinState &)=default
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
ActionsAndProbs ChanceOutcomes () const override
std::string ObservationString (Player player) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 69 of file coin_game.h.
Constructor & Destructor Documentation
CoinState() [1/2]
open_spiel::coin_game::CoinState::CoinState (std::shared_ptr< const Game > game) explicit
Definition at line 160 of file coin_game.cc.
    : State(game),
      parent_game_(static_cast<const CoinGame&>(*game)),
      setup_(parent_game_.NumRows(), parent_game_.NumColumns(),
             parent_game_.NumCoinColors()),
      player_preferences_(game->NumPlayers()),
      player_location_(game->NumPlayers()),
      field_(parent_game_.NumRows() * parent_game_.NumColumns(), kEmptySymbol),
      player_coins_(game->NumPlayers() * parent_game_.NumCoinColors(), 0) {}
Referenced by Clone().
CoinState() [2/2]
open_spiel::coin_game::CoinState::CoinState (const CoinState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::coin_game::CoinState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 328 of file coin_game.cc.
{
  if (player == kChancePlayerId) {
    return absl::StrCat(action_id);
  } else {
    if (action_id == kUp) {
      return "up";
    } else if (action_id == kDown) {
      return "down";
    } else if (action_id == kLeft) {
      return "left";
    } else if (action_id == kRight) {
      return "right";
    } else if (action_id == kStand) {
      return "stand";
    } else {
      SpielFatalError(absl::StrCat("Unexpected action ", action_id));
    }
  }
}
References open_spiel::kChancePlayerId, player, open_spiel::SpielFatalError(), and absl::StrCat().
ChanceOutcomes()
ActionsAndProbs open_spiel::coin_game::CoinState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 200 of file coin_game.cc.
{
  switch (GetPhase()) {
    case GamePhase::kAssignPreferences:
      return ActionProbRange(setup_.available_coin_colors_);
    case GamePhase::kDeployPlayers:
      return ActionProbRange(setup_.available_positions_);
    case GamePhase::kDeployCoins:
      return ActionProbRange(setup_.available_positions_);
    case GamePhase::kPlay:
      SpielFatalError("ChanceOutcomes invoked in play phase");
    default:
      SpielFatalError("Unknown phase.");
      return {};
  }
}
References open_spiel::coin_game::Setup::available_coin_colors_, open_spiel::coin_game::Setup::available_positions_, open_spiel::coin_game::kAssignPreferences, open_spiel::coin_game::kDeployCoins, open_spiel::coin_game::kDeployPlayers, open_spiel::coin_game::kPlay, and open_spiel::SpielFatalError().
Clone()
std::unique_ptr< State > open_spiel::coin_game::CoinState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 439 of file coin_game.cc.
{
  return std::unique_ptr<State>(new CoinState(*this));
}
References CoinState().
CurrentPlayer()
int open_spiel::coin_game::CoinState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 443 of file coin_game.cc.
{
  return IsTerminal() ? kTerminalPlayerId : cur_player_;
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::coin_game::CoinState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 303 of file coin_game.cc.
{
  switch (GetPhase()) {
    case GamePhase::kAssignPreferences:
      ApplyAssignPreferenceAction(action);
      break;
    case GamePhase::kDeployPlayers:
      ApplyDeployPlayersAction(action);
      break;
    case GamePhase::kDeployCoins:
      ApplyDeployCoinsAction(action);
      break;
    case GamePhase::kPlay:
      ApplyPlayAction(action);
      break;
  }
}
References action, open_spiel::coin_game::kAssignPreferences, open_spiel::coin_game::kDeployCoins, open_spiel::coin_game::kDeployPlayers, and open_spiel::coin_game::kPlay.
IsTerminal()
bool open_spiel::coin_game::CoinState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 405 of file coin_game.cc.
{
  return total_moves_ >= parent_game_.EpisodeLength();
}
References open_spiel::coin_game::CoinGame::EpisodeLength().
Referenced by CurrentPlayer(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::coin_game::CoinState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 184 of file coin_game.cc.
{
  if (IsTerminal()) return {};
  switch (GetPhase()) {
    case GamePhase::kAssignPreferences:
      return ActionRange(setup_.available_coin_colors_);
    case GamePhase::kDeployPlayers:
      return ActionRange(setup_.available_positions_);
    case GamePhase::kDeployCoins:
      return ActionRange(setup_.available_positions_);
    case GamePhase::kPlay:
      return Range(offsets.size());
    default:
      SpielFatalError("Unknown phase.");
  }
}
References open_spiel::coin_game::Setup::available_coin_colors_, open_spiel::coin_game::Setup::available_positions_, IsTerminal(), open_spiel::coin_game::kAssignPreferences, open_spiel::coin_game::kDeployCoins, open_spiel::coin_game::kDeployPlayers, open_spiel::coin_game::kPlay, and open_spiel::SpielFatalError().
ObservationString()
std::string open_spiel::coin_game::CoinState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 216 of file coin_game.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::ostringstream out;
  // A player only learns its own preference.
  out << player_preferences_[player] << "\n";
  // Table of how many coins of each type were collected by each player.
  PrintCoinsCollected(out);
  // Current positions of all coins and players on the board.
  PrintBoard(out);
  return out.str();
}
References open_spiel::State::num_players_, out, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Returns()
std::vector< double > open_spiel::coin_game::CoinState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 409 of file coin_game.cc.
{
  if (!IsTerminal()) {
    return std::vector<double>(num_players_, 0.0);
  }
  int collected_coins = 0;
  std::vector<int> coin_count(parent_game_.NumCoinColors());
  for (int coin_color = 0; coin_color < parent_game_.NumCoinColors();
       coin_color++) {
    for (auto player = Player{0}; player < num_players_; player++) {
      Player player_coins = GetPlayerCoinCount(player, coin_color);
      coin_count[coin_color] += player_coins;
      collected_coins += player_coins;
    }
  }
  int good_coins = 0;
  for (int preference : player_preferences_) {
    good_coins += coin_count[preference];
  }
  const int bad_coins = collected_coins - good_coins;
  std::vector<double> rewards(num_players_);
  for (auto player = Player{0}; player < num_players_; player++) {
    int self_coins = coin_count[player_preferences_[player]];
    int other_coins = good_coins - self_coins;
    rewards[player] = (std::pow(self_coins, 2) + std::pow(other_coins, 2) -
                       std::pow(bad_coins, 2));
  }
  return rewards;
}
References IsTerminal(), open_spiel::State::num_players_, open_spiel::coin_game::CoinGame::NumCoinColors(), and player.
ToString()
std::string open_spiel::coin_game::CoinState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 395 of file coin_game.cc.
{
  std::ostringstream out;
  out << "phase=" << GamePhaseToString(GetPhase()) << "\n";
  PrintPreferences(out);
  out << "moves=" << total_moves_ << "\n";
  PrintCoinsCollected(out);
  PrintBoard(out);
  return out.str();
}
References out.
The documentation for this class was generated from the following files:
open_spiel/games/coin_game/coin_game.h
open_spiel/games/coin_game/coin_game.cc