open spiel: open_spiel::TabularPolicy Class Reference
open_spiel::TabularPolicy Class Reference
#include <policy.h>
Public Member Functions
TabularPolicy ()=default
TabularPolicy (const Game &game)
TabularPolicy (const TabularPolicy &other)=default
TabularPolicy (const std::unordered_map< std::string, ActionsAndProbs > &table)
TabularPolicy (const Game &game, const Policy &policy)
TabularPolicy (const TabularPolicy &dummy_policy, const std::unordered_map< std::string, Action > &action_map)
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const override
void ImportPolicy (const TabularPolicy &other_policy)
void SetProb (const std::string &info_state, Action action, double prob)
void SetStatePolicy (const std::string &info_state, const ActionsAndProbs &state_policy)
std::unordered_map< std::string, ActionsAndProbs > & PolicyTable ()
const std::unordered_map< std::string, ActionsAndProbs > & PolicyTable () const
int size () const
std::string ToString () const
std::string ToStringSorted () const
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
virtual ActionsAndProbs GetStatePolicy (const State &state) const
virtual ActionsAndProbs GetStatePolicy (const State &state, Player player) const
Protected Attributes
std::unordered_map< std::string, ActionsAndProbs > policy_table_
Detailed Description
Definition at line 158 of file policy.h.
Constructor & Destructor Documentation
TabularPolicy() [1/6]
open_spiel::TabularPolicy::TabularPolicy () default
TabularPolicy() [2/6]
open_spiel::TabularPolicy::TabularPolicy (const Game & game)
Definition at line 158 of file policy.cc.
    : TabularPolicy(GetRandomPolicy(game)) {}
TabularPolicy() [3/6]
open_spiel::TabularPolicy::TabularPolicy (const TabularPolicy & other) default
TabularPolicy() [4/6]
open_spiel::TabularPolicy::TabularPolicy (const std::unordered_map< std::string, ActionsAndProbs > & table) inline
Definition at line 163 of file policy.h.
      : policy_table_(table) {}
TabularPolicy() [5/6]
open_spiel::TabularPolicy::TabularPolicy (const Game & game, const Policy & policy) inline
Definition at line 167 of file policy.h.
                                                        : TabularPolicy(game) {
    for (auto& [infostate, is_policy] : policy_table_) {
      is_policy = policy.GetStatePolicy(infostate);
    }
  }
References GetStatePolicy(), and policy_table_.
TabularPolicy() [6/6]
open_spiel::TabularPolicy::TabularPolicy (const TabularPolicy & dummy_policy, const std::unordered_map< std::string, Action > & action_map) inline
Definition at line 176 of file policy.h.
      : policy_table_(dummy_policy.policy_table_) {
    for (const auto& entry : action_map) {
      std::string info_state = entry.first;
      Action action_taken = action_map.at(entry.first);
      for (auto& action_and_prob : policy_table_[info_state]) {
        action_and_prob.second =
            (action_and_prob.first == action_taken ? 1.0 : 0.0);
      }
    }
  }
References policy_table_.
Member Function Documentation
GetStatePolicy()
ActionsAndProbs open_spiel::TabularPolicy::GetStatePolicy (const std::string & info_state) const inline override virtual
Reimplemented from open_spiel::Policy.
Definition at line 189 of file policy.h.
{
    auto iter = policy_table_.find(info_state);
    if (iter == policy_table_.end()) {
      return {};
    } else {
      return iter->second;
    }
  }
References policy_table_.
Referenced by define_julia_module(), open_spiel::algorithms::AFCCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::AFCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::CCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::CETabularPolicy::GetStatePolicy(), open_spiel::algorithms::EFCCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::EFCETabularPolicy::GetStatePolicy(), open_spiel::init_pyspiel_policy(), and TabularPolicy().
ImportPolicy()
void open_spiel::TabularPolicy::ImportPolicy (const TabularPolicy & other_policy) inline
Definition at line 239 of file policy.h.
{
    for (const auto& [info_state, actions_and_probs] :
         other_policy.policy_table_) {
      SetStatePolicy(info_state, actions_and_probs);
    }
  }
References actions_and_probs, policy_table_, and SetStatePolicy().
Referenced by open_spiel::ToJointTabularPolicy().
PolicyTable() [1/2]
std::unordered_map< std::string, ActionsAndProbs > & open_spiel::TabularPolicy::PolicyTable () inline
Definition at line 263 of file policy.h.
{
    return policy_table_;
  }
References policy_table_.
Referenced by open_spiel::algorithms::CEDist(), open_spiel::algorithms::CEGame::CEGame(), open_spiel::init_pyspiel_policy(), and open_spiel::ToJointTabularPolicy().
PolicyTable() [2/2]
const std::unordered_map< std::string, ActionsAndProbs > & open_spiel::TabularPolicy::PolicyTable () const inline
Definition at line 267 of file policy.h.
{
    return policy_table_;
  }
References policy_table_.
Serialize()
std::string open_spiel::TabularPolicy::Serialize (int double_precision = -1, std::string delimiter = "<~>") const inline override virtual
Reimplemented from open_spiel::Policy.
Definition at line 198 of file policy.h.
{
    SPIEL_CHECK_GE(double_precision, -1);
    if (delimiter == "," || delimiter == "=") {
      // The two delimiters are used for de/serialization of policy_table_
      SpielFatalError(
          "Please select a different delimiter,"
          "invalid values are \",\" and \"=\".");
    }
    std::string str = "TabularPolicy:";
    if (policy_table_.empty()) return str;
    for (auto const& [info_state, policy] : policy_table_) {
      if (info_state.find(delimiter) != std::string::npos) {
        SpielFatalError(absl::StrCat(
            "Info state contains delimiter \"", delimiter,
            "\", please fix the info state or select a different delimiter."));
      }
      std::string policy_str;
      if (double_precision == -1) {
        policy_str =
            absl::StrJoin(policy, ",",
                          absl::PairFormatter(absl::AlphaNumFormatter(), "=",
                                              HexDoubleFormatter()));
      } else {
        policy_str = absl::StrJoin(
            policy, ",",
            absl::PairFormatter(absl::AlphaNumFormatter(), "=",
                                SimpleDoubleFormatter(double_precision)));
      }
      absl::StrAppend(&str, info_state, delimiter, policy_str, delimiter);
    }
    // Remove the trailing delimiter
    str.erase(str.length() - delimiter.length());
    return str;
  }
References absl::AlphaNumFormatter(), absl::PairFormatter(), policy_table_, SPIEL_CHECK_GE, open_spiel::SpielFatalError(), absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
SetProb()
void open_spiel::TabularPolicy::SetProb (const std::string & info_state, Action action, double prob) inline
Definition at line 249 of file policy.h.
{
    auto iter = policy_table_.find(info_state);
    if (iter == policy_table_.end()) {
      auto iter_and_bool = policy_table_.insert({info_state, {}});
      iter = iter_and_bool.first;
    }
    open_spiel::SetProb(&(iter->second), action, prob);
  }
References action, policy_table_, and open_spiel::SetProb().
Referenced by open_spiel::init_pyspiel_policy().
SetStatePolicy()
void open_spiel::TabularPolicy::SetStatePolicy (const std::string & info_state, const ActionsAndProbs & state_policy) inline
Definition at line 258 of file policy.h.
{
    policy_table_[info_state] = state_policy;
  }
References policy_table_.
Referenced by open_spiel::algorithms::CorrDevBuilder::AddMixedJointPolicy(), open_spiel::algorithms::CorrDevBuilder::AddSampledJointPolicy(), open_spiel::algorithms::CFRCurrentPolicy::AsTabular(), open_spiel::algorithms::DeterministicTabularPolicy::GetTabularPolicy(), ImportPolicy(), open_spiel::init_pyspiel_policy(), open_spiel::algorithms::MDP::Solve(), and open_spiel::ToTabularPolicy().
size()
int open_spiel::TabularPolicy::size () const inline
Definition at line 271 of file policy.h.
{ return policy_table_.size(); }
References policy_table_.
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel::init_pyspiel_policy(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
ToString()
std::string open_spiel::TabularPolicy::ToString () const
Definition at line 198 of file policy.cc.
{
  std::string str = "";
  for (const auto& infostate_and_policy : policy_table_) {
    absl::StrAppend(&str, infostate_and_policy.first, ": ");
    for (const auto& policy : infostate_and_policy.second) {
      absl::StrAppend(&str, " ", policy.first, "=", policy.second);
    }
    absl::StrAppend(&str, "\n");
  }
  return str;
}
References policy_table_, and absl::StrAppend().
Referenced by open_spiel::init_pyspiel_policy().
ToStringSorted()
std::string open_spiel::TabularPolicy::ToStringSorted () const
Definition at line 210 of file policy.cc.
{
  std::vector<std::string> keys;
  keys.reserve(policy_table_.size());
  for (const auto& infostate_and_policy : policy_table_) {
    keys.push_back(infostate_and_policy.first);
  }
  std::sort(keys.begin(), keys.end());
  std::string str = "";
  for (const std::string& key : keys) {
    absl::StrAppend(&str, key, ": ");
    for (const auto& policy : policy_table_.at(key)) {
      absl::StrAppend(&str, " ", policy.first, "=", policy.second);
    }
    absl::StrAppend(&str, "\n");
  }
  return str;
}
References key, keys, policy_table_, and absl::StrAppend().
Referenced by main().
Member Data Documentation
policy_table_
std::unordered_map<std::string, ActionsAndProbs> open_spiel::TabularPolicy::policy_table_ protected
Definition at line 279 of file policy.h.
Referenced by open_spiel::PartialTabularPolicy::GetStatePolicy(), open_spiel::PartialTabularPolicy::GetStatePolicy(), open_spiel::PartialTabularPolicy::GetStatePolicy(), GetStatePolicy(), ImportPolicy(), PolicyTable(), PolicyTable(), Serialize(), SetProb(), SetStatePolicy(), size(), TabularPolicy(), TabularPolicy(), ToString(), and ToStringSorted().
The documentation for this class was generated from the following files:
open_spiel/policy.h
open_spiel/policy.cc