open spiel: absl::FixedArray< T, N, A > Class Template Reference
absl::FixedArray< T, N, A > Class Template Reference
#include <fixed_array.h>
Public Types
using allocator_type = typename AllocatorTraits::allocator_type
using value_type = typename AllocatorTraits::value_type
using pointer = typename AllocatorTraits::pointer
using const_pointer = typename AllocatorTraits::const_pointer
using reference = value_type&
using const_reference = const value_type&
using size_type = typename AllocatorTraits::size_type
using difference_type = typename AllocatorTraits::difference_type
using iterator = pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator<iterator>
using const_reverse_iterator = std::reverse_iterator<const_iterator>
Public Member Functions
FixedArray (const FixedArray &other, const allocator_type &a=allocator_type()) noexcept(NoexceptCopyable())
FixedArray (FixedArray &&other, const allocator_type &a=allocator_type()) noexcept(NoexceptMovable())
FixedArray (size_type n, const allocator_type &a=allocator_type())
FixedArray (size_type n, const value_type &val, const allocator_type &a=allocator_type())
FixedArray (std::initializer_list< value_type > init_list, const allocator_type &a=allocator_type())
template<typename Iterator , EnableIfForwardIterator< Iterator > * = nullptr>
FixedArray (Iterator first, Iterator last, const allocator_type &a=allocator_type())
~FixedArray () noexcept
void operator= (FixedArray &&)=delete
void operator= (const FixedArray &)=delete
size_type size () const
constexpr size_type max_size () const
bool empty () const
size_t memsize () const
const_pointer data () const
pointer data ()
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
reference at (size_type i)
const_reference at (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
void fill (const value_type &val)
Static Public Attributes
static constexpr size_type inline_elements
Friends
bool operator== (const FixedArray &lhs, const FixedArray &rhs)
bool operator!= (const FixedArray &lhs, const FixedArray &rhs)
bool operator< (const FixedArray &lhs, const FixedArray &rhs)
bool operator> (const FixedArray &lhs, const FixedArray &rhs)
bool operator<= (const FixedArray &lhs, const FixedArray &rhs)
bool operator>= (const FixedArray &lhs, const FixedArray &rhs)
template<typename H >
H AbslHashValue (H h, const FixedArray &v)
Detailed Description
template<typename T, size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>>
class absl::FixedArray< T, N, A >
Definition at line 77 of file fixed_array.h.
Member Typedef Documentation
allocator_type
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::allocator_type = typename AllocatorTraits::allocator_type
Definition at line 103 of file fixed_array.h.
const_iterator
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::const_iterator = const_pointer
Definition at line 112 of file fixed_array.h.
const_pointer
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::const_pointer = typename AllocatorTraits::const_pointer
Definition at line 106 of file fixed_array.h.
const_reference
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::const_reference = const value_type&
Definition at line 108 of file fixed_array.h.
const_reverse_iterator
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 114 of file fixed_array.h.
difference_type
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::difference_type = typename AllocatorTraits::difference_type
Definition at line 110 of file fixed_array.h.
iterator
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::iterator = pointer
Definition at line 111 of file fixed_array.h.
pointer
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::pointer = typename AllocatorTraits::pointer
Definition at line 105 of file fixed_array.h.
reference
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::reference = value_type&
Definition at line 107 of file fixed_array.h.
reverse_iterator
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 113 of file fixed_array.h.
size_type
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::size_type = typename AllocatorTraits::size_type
Definition at line 109 of file fixed_array.h.
value_type
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> using absl::FixedArray< T, N, A >::value_type = typename AllocatorTraits::value_type
Definition at line 104 of file fixed_array.h.
Constructor & Destructor Documentation
FixedArray() [1/6]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> absl::FixedArray< T, N, A >::FixedArray (const FixedArray< T, N, A > & other, const allocator_type & a = allocator_type()) inline noexcept
Definition at line 120 of file fixed_array.h.
      : FixedArray(other.begin(), other.end(), a) {}
FixedArray() [2/6]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> absl::FixedArray< T, N, A >::FixedArray (FixedArray< T, N, A > && other, const allocator_type & a = allocator_type()) inline noexcept
Definition at line 125 of file fixed_array.h.
      : FixedArray(std::make_move_iterator(other.begin()),
                   std::make_move_iterator(other.end()), a) {}
FixedArray() [3/6]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> absl::FixedArray< T, N, A >::FixedArray (size_type n, const allocator_type & a = allocator_type()) inline explicit
Definition at line 133 of file fixed_array.h.
      : storage_(n, a) {
    if (DefaultConstructorIsNonTrivial()) {
      memory_internal::ConstructRange(storage_.alloc(), storage_.begin(),
                                      storage_.end());
    }
  }
References absl::memory_internal::ConstructRange().
FixedArray() [4/6]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> absl::FixedArray< T, N, A >::FixedArray (size_type n, const value_type & val, const allocator_type & a = allocator_type()) inline
Definition at line 142 of file fixed_array.h.
      : storage_(n, a) {
    memory_internal::ConstructRange(storage_.alloc(), storage_.begin(),
                                    storage_.end(), val);
  }
References absl::memory_internal::ConstructRange().
FixedArray() [5/6]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> absl::FixedArray< T, N, A >::FixedArray (std::initializer_list< value_type > init_list, const allocator_type & a = allocator_type()) inline
Definition at line 150 of file fixed_array.h.
      : FixedArray(init_list.begin(), init_list.end(), a) {}
FixedArray() [6/6]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> template<typename Iterator , EnableIfForwardIterator< Iterator > * = nullptr> absl::FixedArray< T, N, A >::FixedArray (Iterator first, Iterator last, const allocator_type & a = allocator_type()) inline
Definition at line 158 of file fixed_array.h.
      : storage_(std::distance(first, last), a) {
    memory_internal::CopyRange(storage_.alloc(), storage_.begin(), first, last);
  }
References absl::memory_internal::CopyRange(), and first.
~FixedArray()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> absl::FixedArray< T, N, A >::~FixedArray () inline noexcept
Definition at line 164 of file fixed_array.h.
{
    for (auto* cur = storage_.begin(); cur != storage_.end(); ++cur) {
      AllocatorTraits::destroy(storage_.alloc(), cur);
    }
  }
Member Function Documentation
at() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> reference absl::FixedArray< T, N, A >::at (size_type i) inline
Definition at line 231 of file fixed_array.h.
{
    if (ABSL_PREDICT_FALSE(i >= size())) {
      base_internal::ThrowStdOutOfRange("FixedArray::at failed bounds check");
    }
    return data()[i];
  }
References ABSL_PREDICT_FALSE, absl::FixedArray< T, N, A >::data(), absl::i, absl::FixedArray< T, N, A >::size(), and absl::base_internal::ThrowStdOutOfRange().
at() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_reference absl::FixedArray< T, N, A >::at (size_type i) const inline
Definition at line 240 of file fixed_array.h.
{
    if (ABSL_PREDICT_FALSE(i >= size())) {
      base_internal::ThrowStdOutOfRange("FixedArray::at failed bounds check");
    }
    return data()[i];
  }
References ABSL_PREDICT_FALSE, absl::FixedArray< T, N, A >::data(), absl::i, absl::FixedArray< T, N, A >::size(), and absl::base_internal::ThrowStdOutOfRange().
back() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> reference absl::FixedArray< T, N, A >::back () inline
Definition at line 265 of file fixed_array.h.
                   {
    ABSL_HARDENING_ASSERT(!empty());
    return data()[size() - 1];
  }
References ABSL_HARDENING_ASSERT, absl::FixedArray< T, N, A >::data(), absl::FixedArray< T, N, A >::empty(), and absl::FixedArray< T, N, A >::size().
back() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_reference absl::FixedArray< T, N, A >::back () const inline
Definition at line 272 of file fixed_array.h.
{
    ABSL_HARDENING_ASSERT(!empty());
    return data()[size() - 1];
  }
References ABSL_HARDENING_ASSERT, absl::FixedArray< T, N, A >::data(), absl::FixedArray< T, N, A >::empty(), and absl::FixedArray< T, N, A >::size().
begin() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> iterator absl::FixedArray< T, N, A >::begin () inline
Definition at line 280 of file fixed_array.h.
{ return data(); }
References absl::FixedArray< T, N, A >::data().
Referenced by absl::FixedArray< T, N, A >::cbegin(), absl::FixedArray< T, N, A >::fill(), absl::FixedArray< T, N, A >::rend(), and absl::FixedArray< T, N, A >::rend().
begin() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_iterator absl::FixedArray< T, N, A >::begin () const inline
Definition at line 284 of file fixed_array.h.
{ return data(); }
References absl::FixedArray< T, N, A >::data().
cbegin()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_iterator absl::FixedArray< T, N, A >::cbegin () const inline
Definition at line 289 of file fixed_array.h.
{ return begin(); }
References absl::FixedArray< T, N, A >::begin().
cend()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_iterator absl::FixedArray< T, N, A >::cend () const inline
Definition at line 303 of file fixed_array.h.
{ return end(); }
References absl::FixedArray< T, N, A >::end().
crbegin()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_reverse_iterator absl::FixedArray< T, N, A >::crbegin () const inline
Definition at line 319 of file fixed_array.h.
{ return rbegin(); }
References absl::FixedArray< T, N, A >::rbegin().
crend()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_reverse_iterator absl::FixedArray< T, N, A >::crend () const inline
Definition at line 335 of file fixed_array.h.
{ return rend(); }
References absl::FixedArray< T, N, A >::rend().
data() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> pointer absl::FixedArray< T, N, A >::data () inline
Definition at line 208 of file fixed_array.h.
{ return AsValueType(storage_.begin()); }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample().
data() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_pointer absl::FixedArray< T, N, A >::data () const inline
Definition at line 203 of file fixed_array.h.
{ return AsValueType(storage_.begin()); }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), absl::FixedArray< T, N, A >::at(), absl::FixedArray< T, N, A >::at(), absl::FixedArray< T, N, A >::back(), absl::FixedArray< T, N, A >::back(), absl::FixedArray< T, N, A >::begin(), absl::FixedArray< T, N, A >::begin(), absl::FixedArray< T, N, A >::end(), absl::FixedArray< T, N, A >::end(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), absl::FixedArray< T, N, A >::front(), absl::FixedArray< T, N, A >::front(), absl::FixedArray< T, N, A >::operator[](), absl::FixedArray< T, N, A >::operator[](), and open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample().
empty()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> bool absl::FixedArray< T, N, A >::empty () const inline
Definition at line 192 of file fixed_array.h.
{ return size() == 0; }
References absl::FixedArray< T, N, A >::size().
Referenced by absl::FixedArray< T, N, A >::back(), absl::FixedArray< T, N, A >::back(), absl::FixedArray< T, N, A >::front(), and absl::FixedArray< T, N, A >::front().
end() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> iterator absl::FixedArray< T, N, A >::end () inline
Definition at line 294 of file fixed_array.h.
{ return data() + size(); }
References absl::FixedArray< T, N, A >::data(), and absl::FixedArray< T, N, A >::size().
Referenced by absl::FixedArray< T, N, A >::cend(), absl::FixedArray< T, N, A >::fill(), absl::FixedArray< T, N, A >::rbegin(), and absl::FixedArray< T, N, A >::rbegin().
end() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_iterator absl::FixedArray< T, N, A >::end () const inline
Definition at line 298 of file fixed_array.h.
{ return data() + size(); }
References absl::FixedArray< T, N, A >::data(), and absl::FixedArray< T, N, A >::size().
fill()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> void absl::FixedArray< T, N, A >::fill (const value_type & val) inline
Definition at line 340 of file fixed_array.h.
{ std::fill(begin(), end(), val); }
References absl::FixedArray< T, N, A >::begin(), and absl::FixedArray< T, N, A >::end().
front() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> reference absl::FixedArray< T, N, A >::front () inline
Definition at line 250 of file fixed_array.h.
                    {
    ABSL_HARDENING_ASSERT(!empty());
    return data()[0];
  }
References ABSL_HARDENING_ASSERT, absl::FixedArray< T, N, A >::data(), and absl::FixedArray< T, N, A >::empty().
front() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_reference absl::FixedArray< T, N, A >::front () const inline
Definition at line 257 of file fixed_array.h.
{
    ABSL_HARDENING_ASSERT(!empty());
    return data()[0];
  }
References ABSL_HARDENING_ASSERT, absl::FixedArray< T, N, A >::data(), and absl::FixedArray< T, N, A >::empty().
max_size()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> size_type absl::FixedArray< T, N, A >::max_size () const inline constexpr
Definition at line 185 of file fixed_array.h.
{
    return (std::numeric_limits<difference_type>::max)() / sizeof(value_type);
  }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
memsize()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> size_t absl::FixedArray< T, N, A >::memsize () const inline
Definition at line 197 of file fixed_array.h.
{ return size() * sizeof(value_type); }
References absl::FixedArray< T, N, A >::size().
operator=() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> void absl::FixedArray< T, N, A >::operator= (const FixedArray< T, N, A > &) delete
operator=() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> void absl::FixedArray< T, N, A >::operator= (FixedArray< T, N, A > &&) delete
operator[]() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> reference absl::FixedArray< T, N, A >::operator[] (size_type i) inline
Definition at line 214 of file fixed_array.h.
{
    ABSL_HARDENING_ASSERT(i < size());
    return data()[i];
  }
References ABSL_HARDENING_ASSERT, absl::FixedArray< T, N, A >::data(), absl::i, and absl::FixedArray< T, N, A >::size().
operator[]() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_reference absl::FixedArray< T, N, A >::operator[] (size_type i) const inline
Definition at line 222 of file fixed_array.h.
{
    ABSL_HARDENING_ASSERT(i < size());
    return data()[i];
  }
References ABSL_HARDENING_ASSERT, absl::FixedArray< T, N, A >::data(), absl::i, and absl::FixedArray< T, N, A >::size().
rbegin() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> reverse_iterator absl::FixedArray< T, N, A >::rbegin () inline
Definition at line 308 of file fixed_array.h.
{ return reverse_iterator(end()); }
References absl::FixedArray< T, N, A >::end().
Referenced by absl::FixedArray< T, N, A >::crbegin().
rbegin() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_reverse_iterator absl::FixedArray< T, N, A >::rbegin () const inline
Definition at line 312 of file fixed_array.h.
{
    return const_reverse_iterator(end());
  }
References absl::FixedArray< T, N, A >::end().
rend() [1/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> reverse_iterator absl::FixedArray< T, N, A >::rend () inline
Definition at line 324 of file fixed_array.h.
{ return reverse_iterator(begin()); }
References absl::FixedArray< T, N, A >::begin().
Referenced by absl::FixedArray< T, N, A >::crend().
rend() [2/2]
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> const_reverse_iterator absl::FixedArray< T, N, A >::rend () const inline
Definition at line 328 of file fixed_array.h.
{
    return const_reverse_iterator(begin());
  }
References absl::FixedArray< T, N, A >::begin().
size()
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> size_type absl::FixedArray< T, N, A >::size () const inline
Definition at line 178 of file fixed_array.h.
{ return storage_.size(); }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), absl::FixedArray< T, N, A >::at(), absl::FixedArray< T, N, A >::at(), absl::FixedArray< T, N, A >::back(), absl::FixedArray< T, N, A >::back(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), absl::FixedArray< T, N, A >::empty(), absl::FixedArray< T, N, A >::end(), absl::FixedArray< T, N, A >::end(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), absl::FixedArray< T, N, A >::memsize(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), absl::FixedArray< T, N, A >::operator[](), absl::FixedArray< T, N, A >::operator[](), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
Friends And Related Symbol Documentation
AbslHashValue
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> template<typename H > H AbslHashValue (H h, const FixedArray< T, N, A > & v) friend
Definition at line 370 of file fixed_array.h.
{
    return H::combine(H::combine_contiguous(std::move(h), v.data(), v.size()),
                      v.size());
  }
operator!=
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> bool operator!= (const FixedArray< T, N, A > & lhs, const FixedArray< T, N, A > & rhs) friend
Definition at line 348 of file fixed_array.h.
{
    return !(lhs == rhs);
  }
operator<
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> bool operator< (const FixedArray< T, N, A > & lhs, const FixedArray< T, N, A > & rhs) friend
Definition at line 352 of file fixed_array.h.
{
    return std::lexicographical_compare(lhs.begin(), lhs.end(), rhs.begin(),
                                        rhs.end());
  }
operator<=
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> bool operator<= (const FixedArray< T, N, A > & lhs, const FixedArray< T, N, A > & rhs) friend
Definition at line 361 of file fixed_array.h.
{
    return !(rhs < lhs);
  }
operator==
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> bool operator== (const FixedArray< T, N, A > & lhs, const FixedArray< T, N, A > & rhs) friend
Definition at line 344 of file fixed_array.h.
{
    return absl::equal(lhs.begin(), lhs.end(), rhs.begin(), rhs.end());
  }
operator>
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> bool operator> (const FixedArray< T, N, A > & lhs, const FixedArray< T, N, A > & rhs) friend
Definition at line 357 of file fixed_array.h.
{
    return rhs < lhs;
  }
operator>=
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> bool operator>= (const FixedArray< T, N, A > & lhs, const FixedArray< T, N, A > & rhs) friend
Definition at line 365 of file fixed_array.h.
{
    return !(lhs < rhs);
  }
Member Data Documentation
inline_elements
template<typename T , size_t N = kFixedArrayUseDefault, typename A = std::allocator<T>> size_type absl::FixedArray< T, N, A >::inline_elements static constexpr
Initial value:
=
      (N == kFixedArrayUseDefault ? kInlineBytesDefault / sizeof(value_type)
                                  : static_cast<size_type>(N))
Definition at line 116 of file fixed_array.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/fixed_array.h