open spiel: open_spiel::algorithms::CCETabularPolicy Class Reference
open_spiel::algorithms::CCETabularPolicy Class Reference
#include <cce.h>
Public Member Functions
CCETabularPolicy ()
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
ActionsAndProbs GetStatePolicy (const State &state, Player pl) const override
ActionsAndProbs GetStatePolicy (const State &state) const override
Public Member Functions inherited from open_spiel::TabularPolicy
TabularPolicy ()=default
TabularPolicy (const Game &game)
TabularPolicy (const TabularPolicy &other)=default
TabularPolicy (const std::unordered_map< std::string, ActionsAndProbs > &table)
TabularPolicy (const Game &game, const Policy &policy)
TabularPolicy (const TabularPolicy &dummy_policy, const std::unordered_map< std::string, Action > &action_map)
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const override
void ImportPolicy (const TabularPolicy &other_policy)
void SetProb (const std::string &info_state, Action action, double prob)
void SetStatePolicy (const std::string &info_state, const ActionsAndProbs &state_policy)
std::unordered_map< std::string, ActionsAndProbs > & PolicyTable ()
const std::unordered_map< std::string, ActionsAndProbs > & PolicyTable () const
int size () const
std::string ToString () const
std::string ToStringSorted () const
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
Additional Inherited Members
Protected Attributes inherited from open_spiel::TabularPolicy
std::unordered_map< std::string, ActionsAndProbs > policy_table_
Detailed Description
Definition at line 88 of file cce.h.
Constructor & Destructor Documentation
CCETabularPolicy()
open_spiel::algorithms::CCETabularPolicy::CCETabularPolicy () inline
Definition at line 90 of file cce.h.
{}
Member Function Documentation
GetStatePolicy() [1/3]
ActionsAndProbs open_spiel::algorithms::CCETabularPolicy::GetStatePolicy (const State & state) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 96 of file cce.cc.
{
  const auto* cce_state = dynamic_cast<const CCEState*>(&state);
  SPIEL_CHECK_TRUE(cce_state != nullptr);
  return cce_state->CurrentRecommendedStatePolicy();
}
References SPIEL_CHECK_TRUE, and state.
GetStatePolicy() [2/3]
ActionsAndProbs open_spiel::algorithms::CCETabularPolicy::GetStatePolicy (const State & state, Player pl) const inline override virtual
Reimplemented from open_spiel::Policy.
Definition at line 96 of file cce.h.
{
    SPIEL_CHECK_EQ(state.CurrentPlayer(), pl);
    return GetStatePolicy(state);
  }
References GetStatePolicy(), SPIEL_CHECK_EQ, and state.
GetStatePolicy() [3/3]
ActionsAndProbs open_spiel::algorithms::CCETabularPolicy::GetStatePolicy (const std::string & info_state) const inline override virtual
Reimplemented from open_spiel::Policy.
Definition at line 92 of file cce.h.
{
    SpielFatalError("GetStatePolicy(const std::string&) should not be called.");
    return TabularPolicy::GetStatePolicy(info_state);
  }
References open_spiel::TabularPolicy::GetStatePolicy(), and open_spiel::SpielFatalError().
Referenced by GetStatePolicy().
The documentation for this class was generated from the following files:
open_spiel/algorithms/corr_dist/cce.h
open_spiel/algorithms/corr_dist/cce.cc