open spiel: open_spiel::NFGState Class Reference
open_spiel::NFGState Class Reference
#include <normal_form_game.h>
Public Member Functions
NFGState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const final
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
std::string ToString () const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions (Player player) const override=0
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
virtual std::string ActionToString (Player player, Action action_id) const =0
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual bool IsTerminal () const =0
virtual std::vector< double > Rewards () const
virtual std::vector< double > Returns () const =0
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
virtual std::unique_ptr< State > Clone () const =0
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
void DoApplyActions (const std::vector< Action > &actions) override=0
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyAction (Action action_id)
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 37 of file normal_form_game.h.
Constructor & Destructor Documentation
NFGState()
open_spiel::NFGState::NFGState (std::shared_ptr< const Game > game) inline
Definition at line 39 of file normal_form_game.h.
: SimMoveState(game) {}
Member Function Documentation
CurrentPlayer()
Player open_spiel::NFGState::CurrentPlayer () const inline final virtual
Implements open_spiel::State.
Definition at line 42 of file normal_form_game.h.
{
    return IsTerminal() ? kTerminalPlayerId : kSimultaneousPlayerId;
  }
References open_spiel::State::IsTerminal(), open_spiel::kSimultaneousPlayerId, and open_spiel::kTerminalPlayerId.
InformationStateString()
std::string open_spiel::NFGState::InformationStateString (Player player) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 47 of file normal_form_game.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, num_players_);
    std::string info_state = absl::StrCat("Observing player: ", player, ". ");
    if (!IsTerminal()) {
      absl::StrAppend(&info_state, "Non-terminal");
    } else {
      absl::StrAppend(&info_state,
                      "Terminal. History string: ", HistoryString());
    }
    return info_state;
  }
References open_spiel::State::HistoryString(), open_spiel::State::IsTerminal(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and absl::StrCat().
InformationStateTensor()
void open_spiel::NFGState::InformationStateTensor (Player player, absl::Span< float > values) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 83 of file normal_form_game.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, num_players_);
    SPIEL_CHECK_EQ(values.size(), 1);
    if (IsTerminal()) {
      values[0] = 1;
    } else {
      values[0] = 0;
    }
  }
References open_spiel::State::IsTerminal(), open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
ObservationString()
std::string open_spiel::NFGState::ObservationString (Player player) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 60 of file normal_form_game.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, num_players_);
    std::string obs_str;
    if (!IsTerminal()) {
      absl::StrAppend(&obs_str, "Non-terminal");
    } else {
      absl::StrAppend(&obs_str, "Terminal. History string: ", HistoryString());
    }
    return obs_str;
  }
References open_spiel::State::HistoryString(), open_spiel::State::IsTerminal(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrAppend().
ObservationTensor()
void open_spiel::NFGState::ObservationTensor (Player player, absl::Span< float > values) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 95 of file normal_form_game.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, num_players_);
    SPIEL_CHECK_EQ(values.size(), 1);
    if (IsTerminal()) {
      values[0] = 1;
    } else {
      values[0] = 0;
    }
  }
References open_spiel::State::IsTerminal(), open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
ToString()
std::string open_spiel::NFGState::ToString () const inline override virtual
Implements open_spiel::State.
Reimplemented in open_spiel::tensor_game::TensorState.
Definition at line 72 of file normal_form_game.h.
{
    std::string result = "Normal form game default NFGState::ToString. ";
    if (IsTerminal()) {
      absl::StrAppend(&result, "Terminal, history: ", HistoryString(),
                      ", returns: ", absl::StrJoin(Returns(), ","));
    } else {
      absl::StrAppend(&result, "Non-terminal");
    }
    return result;
  }
References open_spiel::State::HistoryString(), open_spiel::State::IsTerminal(), open_spiel::State::Returns(), absl::StrAppend(), and absl::StrJoin().
The documentation for this class was generated from the following file:
open_spiel/normal_form_game.h