open spiel: absl::container_internal::node_handle_base< PolicyTraits, Alloc > Class Template Reference
absl::container_internal::node_handle_base< PolicyTraits, Alloc > Class Template Reference
#include <common.h>
Classes
struct construct_tag_t
struct transfer_tag_t
Public Types
using allocator_type = Alloc
Public Member Functions
constexpr node_handle_base ()=default
node_handle_base (node_handle_base &&other) noexcept
~node_handle_base ()
node_handle_base & operator= (node_handle_base &&other) noexcept
bool empty () const noexcept
operator bool () const noexcept
allocator_type get_allocator () const
Protected Types
using slot_type = typename PolicyTraits::slot_type
Protected Member Functions
node_handle_base (transfer_tag_t, const allocator_type &a, slot_type *s)
template<typename... Args>
node_handle_base (construct_tag_t, const allocator_type &a, Args &&... args)
void destroy ()
void reset ()
slot_type * slot () const
allocator_type * alloc ()
Friends
struct CommonAccess
Detailed Description
template<typename PolicyTraits, typename Alloc>
class absl::container_internal::node_handle_base< PolicyTraits, Alloc >
Definition at line 52 of file common.h.
Member Typedef Documentation
allocator_type
template<typename PolicyTraits , typename Alloc > using absl::container_internal::node_handle_base< PolicyTraits, Alloc >::allocator_type = Alloc
Definition at line 57 of file common.h.
slot_type
template<typename PolicyTraits , typename Alloc > using absl::container_internal::node_handle_base< PolicyTraits, Alloc >::slot_type = typename PolicyTraits::slot_type protected
Definition at line 54 of file common.h.
Constructor & Destructor Documentation
node_handle_base() [1/4]
template<typename PolicyTraits , typename Alloc > absl::container_internal::node_handle_base< PolicyTraits, Alloc >::node_handle_base () constexpr default
node_handle_base() [2/4]
template<typename PolicyTraits , typename Alloc > absl::container_internal::node_handle_base< PolicyTraits, Alloc >::node_handle_base (node_handle_base< PolicyTraits, Alloc > && other) inline noexcept
Definition at line 60 of file common.h.
{
    *this = std::move(other);
  }
~node_handle_base()
template<typename PolicyTraits , typename Alloc > absl::container_internal::node_handle_base< PolicyTraits, Alloc >::~node_handle_base () inline
Definition at line 63 of file common.h.
{ destroy(); }
References absl::container_internal::node_handle_base< PolicyTraits, Alloc >::destroy().
node_handle_base() [3/4]
template<typename PolicyTraits , typename Alloc > absl::container_internal::node_handle_base< PolicyTraits, Alloc >::node_handle_base (transfer_tag_t , const allocator_type & a, slot_type * s) inline protected
Definition at line 82 of file common.h.
      : alloc_(a) {
    PolicyTraits::transfer(alloc(), slot(), s);
  }
References absl::container_internal::node_handle_base< PolicyTraits, Alloc >::alloc(), absl::s, and absl::container_internal::node_handle_base< PolicyTraits, Alloc >::slot().
node_handle_base() [4/4]
template<typename PolicyTraits , typename Alloc > template<typename... Args> absl::container_internal::node_handle_base< PolicyTraits, Alloc >::node_handle_base (construct_tag_t , const allocator_type & a, Args &&... args) inline protected
Definition at line 89 of file common.h.
      : alloc_(a) {
    PolicyTraits::construct(alloc(), slot(), std::forward<Args>(args)...);
  }
References absl::container_internal::node_handle_base< PolicyTraits, Alloc >::alloc(), and absl::container_internal::node_handle_base< PolicyTraits, Alloc >::slot().
Member Function Documentation
alloc()
template<typename PolicyTraits , typename Alloc > allocator_type * absl::container_internal::node_handle_base< PolicyTraits, Alloc >::alloc () inline protected
Definition at line 110 of file common.h.
{ return std::addressof(*alloc_); }
Referenced by absl::container_internal::node_handle_base< PolicyTraits, Alloc >::destroy(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::node_handle_base(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::node_handle_base(), and absl::container_internal::node_handle_base< PolicyTraits, Alloc >::operator=().
destroy()
template<typename PolicyTraits , typename Alloc > void absl::container_internal::node_handle_base< PolicyTraits, Alloc >::destroy () inline protected
Definition at line 94 of file common.h.
                 {
    if (!empty()) {
      PolicyTraits::destroy(alloc(), slot());
      reset();
    }
  }
References absl::container_internal::node_handle_base< PolicyTraits, Alloc >::alloc(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::empty(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::reset(), and absl::container_internal::node_handle_base< PolicyTraits, Alloc >::slot().
Referenced by absl::container_internal::node_handle_base< PolicyTraits, Alloc >::operator=(), and absl::container_internal::node_handle_base< PolicyTraits, Alloc >::~node_handle_base().
empty()
template<typename PolicyTraits , typename Alloc > bool absl::container_internal::node_handle_base< PolicyTraits, Alloc >::empty () const inline noexcept
Definition at line 74 of file common.h.
{ return !alloc_; }
Referenced by absl::container_internal::node_handle_base< PolicyTraits, Alloc >::destroy(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::operator bool(), and absl::container_internal::node_handle_base< PolicyTraits, Alloc >::slot().
get_allocator()
template<typename PolicyTraits , typename Alloc > allocator_type absl::container_internal::node_handle_base< PolicyTraits, Alloc >::get_allocator () const inline
Definition at line 76 of file common.h.
{ return *alloc_; }
operator bool()
template<typename PolicyTraits , typename Alloc > absl::container_internal::node_handle_base< PolicyTraits, Alloc >::operator bool () const inline explicit noexcept
Definition at line 75 of file common.h.
{ return !empty(); }
References absl::container_internal::node_handle_base< PolicyTraits, Alloc >::empty().
operator=()
template<typename PolicyTraits , typename Alloc > node_handle_base & absl::container_internal::node_handle_base< PolicyTraits, Alloc >::operator= (node_handle_base< PolicyTraits, Alloc > && other) inline noexcept
Definition at line 64 of file common.h.
{
    destroy();
    if (!other.empty()) {
      alloc_ = other.alloc_;
      PolicyTraits::transfer(alloc(), slot(), other.slot());
      other.reset();
    }
    return *this;
  }
References absl::container_internal::node_handle_base< PolicyTraits, Alloc >::alloc(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::destroy(), and absl::container_internal::node_handle_base< PolicyTraits, Alloc >::slot().
reset()
template<typename PolicyTraits , typename Alloc > void absl::container_internal::node_handle_base< PolicyTraits, Alloc >::reset () inline protected
Definition at line 101 of file common.h.
               {
    assert(alloc_.has_value());
    alloc_ = absl::nullopt;
  }
Referenced by open_spiel.python.utils.stats.BasicStats::__init__(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::destroy(), open_spiel.python.algorithms.ismcts.ISMCTSBot::run_search(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
slot()
template<typename PolicyTraits , typename Alloc > slot_type * absl::container_internal::node_handle_base< PolicyTraits, Alloc >::slot () const inline protected
Definition at line 106 of file common.h.
{
    assert(!empty());
    return reinterpret_cast<slot_type*>(std::addressof(slot_space_));
  }
References absl::container_internal::node_handle_base< PolicyTraits, Alloc >::empty().
Referenced by absl::container_internal::node_handle_base< PolicyTraits, Alloc >::destroy(), absl::container_internal::node_handle< Policy, PolicyTraits, Alloc, absl::void_t< typename Policy::mapped_type > >::key(), absl::container_internal::node_handle< Policy, PolicyTraits, Alloc, absl::void_t< typename Policy::mapped_type > >::mapped(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::node_handle_base(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::node_handle_base(), absl::container_internal::node_handle_base< PolicyTraits, Alloc >::operator=(), and absl::container_internal::node_handle< Policy, PolicyTraits, Alloc, typename >::value().
Friends And Related Symbol Documentation
CommonAccess
template<typename PolicyTraits , typename Alloc > friend struct CommonAccess friend
Definition at line 79 of file common.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/common.h