open spiel: open_spiel::solitaire::Card Class Reference
open_spiel::solitaire::Card Class Reference
#include <solitaire.h>
Public Member Functions
Card (bool hidden=false, SuitType suit=SuitType::kHidden, RankType rank=RankType::kHidden, LocationType location=LocationType::kMissing)
Card (int index, bool hidden=false, LocationType location=LocationType::kMissing)
RankType GetRank () const
SuitType GetSuit () const
LocationType GetLocation () const
bool GetHidden () const
int GetIndex () const
void SetRank (RankType new_rank)
void SetSuit (SuitType new_suit)
void SetLocation (LocationType new_location)
void SetHidden (bool new_hidden)
bool operator== (const Card &other_card) const
bool operator< (const Card &other_card) const
std::string ToString (bool colored=true) const
std::vector< Card > LegalChildren () const
Detailed Description
Definition at line 104 of file solitaire.h.
Constructor & Destructor Documentation
Card() [1/2]
open_spiel::solitaire::Card::Card (bool hidden = false, SuitType suit = SuitType::kHidden, RankType rank = RankType::kHidden, LocationType location = LocationType::kMissing) explicit
Definition at line 259 of file solitaire.cc.
    : rank_(rank), suit_(suit), location_(location), hidden_(hidden) {}
Referenced by LegalChildren().
Card() [2/2]
open_spiel::solitaire::Card::Card (int index, bool hidden = false, LocationType location = LocationType::kMissing) explicit
Definition at line 262 of file solitaire.cc.
    : location_(location), hidden_(hidden), index_(index) {
  if (!hidden_) {
    switch (index_) {
      case kHiddenCard: {
        rank_ = RankType::kHidden;
        suit_ = SuitType::kHidden;
        break;
      }
      case kEmptyTableauCard: {
        rank_ = RankType::kNone;
        suit_ = SuitType::kNone;
        break;
      }
      case kEmptySpadeCard: {
        rank_ = RankType::kNone;
        suit_ = SuitType::kSpades;
        break;
      }
      case kEmptyHeartCard: {
        rank_ = RankType::kNone;
        suit_ = SuitType::kHearts;
        break;
      }
      case kEmptyClubCard: {
        rank_ = RankType::kNone;
        suit_ = SuitType::kClubs;
        break;
      }
      case kEmptyDiamondCard: {
        rank_ = RankType::kNone;
        suit_ = SuitType::kDiamonds;
        break;
      }
      default: {
        // Converts an index back into a rank and suit for ordinary cards
        rank_ = static_cast<RankType>(1 + ((index_ - 1) % kNumRanks));
        suit_ = static_cast<SuitType>(
            static_cast<int>(1 + floor((index_ - 1) / 13.0)));
      }
    }
  }
}
References open_spiel::solitaire::kClubs, open_spiel::solitaire::kDiamonds, open_spiel::solitaire::kHearts, open_spiel::solitaire::kHidden, open_spiel::solitaire::kHiddenCard, open_spiel::solitaire::kNone, and open_spiel::solitaire::kSpades.
Member Function Documentation
GetHidden()
bool open_spiel::solitaire::Card::GetHidden () const
Definition at line 314 of file solitaire.cc.
{ return hidden_; }
GetIndex()
int open_spiel::solitaire::Card::GetIndex () const
Definition at line 316 of file solitaire.cc.
{
  /* Basically it just calculates the index if it hasn't been calculated before,
   * otherwise it will just return a stored value. If `force` is true and the
   * card isn't hidden, then the index is calculated again. */
  return hidden_ ? kHiddenCard : GetCardIndex(rank_, suit_);
}
References open_spiel::solitaire::GetCardIndex(), and open_spiel::solitaire::kHiddenCard.
Referenced by open_spiel::solitaire::Move::operator<().
GetLocation()
LocationType open_spiel::solitaire::Card::GetLocation () const
Definition at line 312 of file solitaire.cc.
{ return location_; }
Referenced by open_spiel::solitaire::SolitaireState::IsReversible().
GetRank()
RankType open_spiel::solitaire::Card::GetRank () const
Definition at line 308 of file solitaire.cc.
{ return rank_; }
Referenced by open_spiel::solitaire::Move::ActionId(), open_spiel::solitaire::SolitaireState::MoveCards(), open_spiel::solitaire::Tableau::Reveal(), and open_spiel::solitaire::Waste::Reveal().
GetSuit()
SuitType open_spiel::solitaire::Card::GetSuit () const
Definition at line 310 of file solitaire.cc.
{ return suit_; }
Referenced by open_spiel::solitaire::Move::ActionId(), open_spiel::solitaire::Tableau::Reveal(), and open_spiel::solitaire::Waste::Reveal().
LegalChildren()
std::vector< Card > open_spiel::solitaire::Card::LegalChildren () const
Definition at line 365 of file solitaire.cc.
{
  if (hidden_) {
    return {};
  } else {
    RankType child_rank;
    std::vector<SuitType> child_suits;
    // A card can have a maximum of 4 children
    // (specifically, an empty tableau card can accept a king of any suit)
    child_suits.reserve(4);
    switch (location_) {
      case LocationType::kTableau: {
        if (rank_ == RankType::kNone) {
          if (suit_ == SuitType::kNone) {
            // Empty tableaus can accept a king of any suit
            child_rank = RankType::kK;
            child_suits = kSuits;
            break;
          } else {
            return {};
          }
        } else if (rank_ >= RankType::k2 && rank_ <= RankType::kK) {
          // Ordinary cards (except aces) can accept cards of an opposite
          // suit that is one rank lower
          child_rank = static_cast<RankType>(static_cast<int>(rank_) - 1);
          child_suits = GetOppositeSuits(suit_);
          break;
        } else {
          // This will catch RankType::kA and RankType::kHidden
          return {};
        }
        break;
      }
      case LocationType::kFoundation: {
        if (rank_ == RankType::kNone) {
          if (suit_ != SuitType::kNone) {
            child_rank = static_cast<RankType>(static_cast<int>(rank_) + 1);
            child_suits = {suit_};
          } else {
            return {};
          }
        } else if (rank_ >= RankType::kA && rank_ <= RankType::kQ) {
          // Cards (except kings) can accept a card of the same suit that is
          // one rank higher
          child_rank = static_cast<RankType>(static_cast<int>(rank_) + 1);
          child_suits = {suit_};
        } else {
          // This could catch RankType::kK and RankType::kHidden
          return {};
        }
        break;
      }
      default: {
        // This catches all cards_ that aren't located in a tableau or
        // foundation
        return {};
      }
    }
    std::vector<Card> legal_children;
    legal_children.reserve(4);
    if (child_suits.empty()) {
      SpielFatalError("child_suits should not be empty");
    }
    for (const auto& child_suit : child_suits) {
      auto child = Card(false, child_suit, child_rank);
      legal_children.push_back(child);
    }
    return legal_children;
  }
}
References Card(), open_spiel::solitaire::GetOppositeSuits(), open_spiel::solitaire::k2, open_spiel::solitaire::kA, open_spiel::solitaire::kFoundation, open_spiel::solitaire::kK, open_spiel::solitaire::kNone, open_spiel::solitaire::kQ, open_spiel::solitaire::kTableau, and open_spiel::SpielFatalError().
operator<()
bool open_spiel::solitaire::Card::operator< (const Card & other_card) const
Definition at line 445 of file solitaire.cc.
{
  if (suit_ != other_card.suit_) {
    return suit_ < other_card.suit_;
  } else if (rank_ != other_card.rank_) {
    return rank_ < other_card.rank_;
  } else {
    return false;
  }
}
operator==()
bool open_spiel::solitaire::Card::operator== (const Card & other_card) const
Definition at line 441 of file solitaire.cc.
{
  return rank_ == other_card.rank_ && suit_ == other_card.suit_;
}
SetHidden()
void open_spiel::solitaire::Card::SetHidden (bool new_hidden)
Definition at line 331 of file solitaire.cc.
{ hidden_ = new_hidden; }
SetLocation()
void open_spiel::solitaire::Card::SetLocation (LocationType new_location)
Definition at line 329 of file solitaire.cc.
{ location_ = new_location; }
SetRank()
void open_spiel::solitaire::Card::SetRank (RankType new_rank)
Definition at line 325 of file solitaire.cc.
{ rank_ = new_rank; }
Referenced by open_spiel::solitaire::Tableau::Reveal().
SetSuit()
void open_spiel::solitaire::Card::SetSuit (SuitType new_suit)
Definition at line 327 of file solitaire.cc.
{ suit_ = new_suit; }
ToString()
std::string open_spiel::solitaire::Card::ToString (bool colored = true) const
Definition at line 335 of file solitaire.cc.
{
  std::string result;
  // Determine color of string
  if (colored && !hidden_) {
    if (suit_ == SuitType::kSpades || suit_ == SuitType::kClubs) {
      absl::StrAppend(&result, kBlack);
    } else if (suit_ == SuitType::kHearts || suit_ == SuitType::kDiamonds) {
      absl::StrAppend(&result, kRed);
    }
  }
  // Determine contents of string
  if (rank_ == RankType::kHidden || suit_ == SuitType::kHidden) {
    absl::StrAppend(&result, kGlyphHidden, " ");
  } else if (rank_ == RankType::kNone && suit_ == SuitType::kNone) {
    absl::StrAppend(&result, kGlyphEmpty);
  } else {
    absl::StrAppend(&result, kRankStrs.at(static_cast<int>(rank_)));
    absl::StrAppend(&result, kSuitStrs.at(static_cast<int>(suit_)));
  }
  if (colored) {
    // Reset color if applicable
    absl::StrAppend(&result, kReset);
  }
  return result;
}
References open_spiel::solitaire::kClubs, open_spiel::solitaire::kDiamonds, open_spiel::solitaire::kHearts, open_spiel::solitaire::kHidden, open_spiel::solitaire::kNone, open_spiel::solitaire::kSpades, and absl::StrAppend().
Referenced by open_spiel::solitaire::Move::ToString().
The documentation for this class was generated from the following files:
open_spiel/games/solitaire/solitaire.h
open_spiel/games/solitaire/solitaire.cc