open spiel: open_spiel::PublicObservationHistory Class Reference
open_spiel::PublicObservationHistory Class Reference
#include <observation_history.h>
Public Member Functions
PublicObservationHistory (const State &target)
PublicObservationHistory (std::vector< std::string > history)
PublicObservationHistory (const PublicObservationHistory &)=default
~PublicObservationHistory ()=default
const std::vector< std::string > & History () const
int MoveNumber () const
const std::string & ObservationAt (int time) const
bool CorrespondsToInitialState () const
bool CorrespondsTo (const PublicObservationHistory &other) const
bool CorrespondsTo (const State &state) const
bool IsPrefixOf (const PublicObservationHistory &other) const
bool IsPrefixOf (const State &state) const
bool IsExtensionOf (const PublicObservationHistory &other) const
bool IsExtensionOf (const State &state) const
std::string ToString () const
bool operator== (const PublicObservationHistory &other) const
Detailed Description
Definition at line 154 of file observation_history.h.
Constructor & Destructor Documentation
PublicObservationHistory() [1/3]
open_spiel::PublicObservationHistory::PublicObservationHistory (const State & target)
Definition at line 200 of file observation_history.cc.
    : observer_(target.GetGame()->MakeObserver(
          IIGObservationType{/*public_info*/true,
                             /*perfect_recall*/false,
                             /*private_info*/PrivateInfoType::kNone},
          {})) {
  history_.reserve(target.FullHistory().size());
  std::unique_ptr<State> state = target.GetGame()->NewInitialState();
  // Use FullHistory even though we don't need the player -- prevent
  // doing a copy.
  for (const auto& [_, action] : target.FullHistory()) {
    history_.push_back(observer_->StringFrom(*state, kDefaultPlayerId));
    state->ApplyAction(action);
  }
  history_.push_back(observer_->StringFrom(*state, kDefaultPlayerId));
}
PublicObservationHistory() [2/3]
open_spiel::PublicObservationHistory::PublicObservationHistory (std::vector< std::string > history)
Definition at line 218 of file observation_history.cc.
    : history_(std::move(history)) {
  SPIEL_CHECK_FALSE(history_.empty());
}
References SPIEL_CHECK_FALSE.
PublicObservationHistory() [3/3]
open_spiel::PublicObservationHistory::PublicObservationHistory (const PublicObservationHistory &) default
~PublicObservationHistory()
open_spiel::PublicObservationHistory::~PublicObservationHistory () default
Member Function Documentation
CorrespondsTo() [1/2]
bool open_spiel::PublicObservationHistory::CorrespondsTo (const PublicObservationHistory & other) const
Definition at line 233 of file observation_history.cc.
{
  return history_ == other.history_;
}
Referenced by open_spiel::algorithms::TargetedPolicy::IsTargetHit(), and operator==().
CorrespondsTo() [2/2]
bool open_spiel::PublicObservationHistory::CorrespondsTo (const State & state) const
Definition at line 238 of file observation_history.cc.
{
  if (MoveNumber() != state.MoveNumber()) return false;
  bool equal = CheckStateCorrespondenceInSimulation(state, MoveNumber());
  SPIEL_CHECK_TRUE(!equal || IsPrefixOf(state));
  SPIEL_CHECK_TRUE(!equal || IsExtensionOf(state));
  return equal;
}
References IsExtensionOf(), IsPrefixOf(), MoveNumber(), SPIEL_CHECK_TRUE, and state.
CorrespondsToInitialState()
bool open_spiel::PublicObservationHistory::CorrespondsToInitialState () const inline
Definition at line 185 of file observation_history.h.
{ return MoveNumber() == 0; }
References MoveNumber().
Referenced by IsPrefixOf(), IsPrefixOf(), and open_spiel::algorithms::OOSAlgorithm::RunTargetedIterations().
History()
const std::vector< std::string > & open_spiel::PublicObservationHistory::History () const inline
Definition at line 174 of file observation_history.h.
{ return history_; }
IsExtensionOf() [1/2]
bool open_spiel::PublicObservationHistory::IsExtensionOf (const PublicObservationHistory & other) const
Definition at line 266 of file observation_history.cc.
{
  return other.IsPrefixOf(*this);
}
References IsPrefixOf().
Referenced by CorrespondsTo().
IsExtensionOf() [2/2]
bool open_spiel::PublicObservationHistory::IsExtensionOf (const State & state) const
Definition at line 271 of file observation_history.cc.
{
  if (state.MoveNumber() > MoveNumber()) return false;
  // Check the latest observation is identical -- most observations
  // will differ only in the last items.
  if (observer_->StringFrom(state, kDefaultPlayerId) !=
      ObservationAt(state.MoveNumber()))
    return false;
  return CheckStateCorrespondenceInSimulation(state, state.MoveNumber());
}
References open_spiel::kDefaultPlayerId, MoveNumber(), ObservationAt(), and state.
IsPrefixOf() [1/2]
bool open_spiel::PublicObservationHistory::IsPrefixOf (const PublicObservationHistory & other) const
Definition at line 246 of file observation_history.cc.
{
  if (CorrespondsToInitialState()) return true;
  if (other.CorrespondsToInitialState()) return false;
  const auto& a = history_;
  const auto& b = other.history_;
  if (a.size() > b.size()) return false;
  if (a.size() == b.size()) return a == b;
  return std::equal(a.begin(), a.end(), b.begin());
}
References a, b, and CorrespondsToInitialState().
Referenced by CorrespondsTo(), and IsExtensionOf().
IsPrefixOf() [2/2]
bool open_spiel::PublicObservationHistory::IsPrefixOf (const State & state) const
Definition at line 258 of file observation_history.cc.
{
  if (CorrespondsToInitialState()) return true;
  // Cannot be prefix if state is earlier.
  if (state.MoveNumber() < MoveNumber()) return false;
  return CheckStateCorrespondenceInSimulation(state, MoveNumber());
}
References CorrespondsToInitialState(), MoveNumber(), and state.
MoveNumber()
int open_spiel::PublicObservationHistory::MoveNumber () const
Definition at line 224 of file observation_history.cc.
{
  SPIEL_CHECK_FALSE(history_.empty());
  return history_.size() - 1;
}
References SPIEL_CHECK_FALSE.
Referenced by CorrespondsTo(), CorrespondsToInitialState(), IsExtensionOf(), and IsPrefixOf().
ObservationAt()
const std::string & open_spiel::PublicObservationHistory::ObservationAt (int time) const
Definition at line 229 of file observation_history.cc.
{
  return history_.at(time);
}
Referenced by IsExtensionOf().
operator==()
bool open_spiel::PublicObservationHistory::operator== (const PublicObservationHistory & other) const inline
Definition at line 221 of file observation_history.h.
{
    return CorrespondsTo(other);
  }
References CorrespondsTo().
ToString()
std::string open_spiel::PublicObservationHistory::ToString () const
Definition at line 283 of file observation_history.cc.
{
  return absl::StrJoin(history_, ", ");
}
References absl::StrJoin().
Referenced by open_spiel::operator<<().
The documentation for this class was generated from the following files:
open_spiel/algorithms/observation_history.h
open_spiel/algorithms/observation_history.cc