open spiel: open_spiel::tiny_bridge::TinyBridgeAuctionState Class Reference
open_spiel::tiny_bridge::TinyBridgeAuctionState Class Reference
#include <tiny_bridge.h>
Classes
struct AuctionState
Public Member Functions
TinyBridgeAuctionState (std::shared_ptr< const Game > game, bool is_abstracted)
TinyBridgeAuctionState (const TinyBridgeAuctionState &)=default
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string AuctionString () const
std::string PlayerHandString (Player player, bool abstracted) const
std::string DealString () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 140 of file tiny_bridge.h.
Constructor & Destructor Documentation
TinyBridgeAuctionState() [1/2]
open_spiel::tiny_bridge::TinyBridgeAuctionState::TinyBridgeAuctionState (std::shared_ptr< const Game > game, bool is_abstracted) inline
Definition at line 149 of file tiny_bridge.h.
      : State(std::move(game)), is_abstracted_(is_abstracted) {}
Referenced by Clone().
TinyBridgeAuctionState() [2/2]
open_spiel::tiny_bridge::TinyBridgeAuctionState::TinyBridgeAuctionState (const TinyBridgeAuctionState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::tiny_bridge::TinyBridgeAuctionState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 504 of file tiny_bridge.cc.
{
  if (player == kChancePlayerId) {
    return HandString(action_id);
  } else {
    return kActionStr[action_id];
  }
}
References open_spiel::tiny_bridge::HandString(), open_spiel::tiny_bridge::kActionStr, open_spiel::kChancePlayerId, and player.
Referenced by AuctionString(), and ObservationString().
AuctionString()
std::string open_spiel::tiny_bridge::TinyBridgeAuctionState::AuctionString () const
Definition at line 519 of file tiny_bridge.cc.
{
  std::string auction{};
  for (int i = num_players_; i < actions_.size(); ++i) {
    if (!auction.empty()) auction.push_back('-');
    auction.append(ActionToString(i % num_players_, actions_[i]));
  }
  return auction;
}
References ActionToString(), i, and open_spiel::State::num_players_.
Referenced by InformationStateString(), and ToString().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::tiny_bridge::TinyBridgeAuctionState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 484 of file tiny_bridge.cc.
          {
  std::vector<Action> actions;
  auto holder = CardHolders();
  for (int card1 = 0; card1 < kDeckSize; ++card1) {
    if (holder[card1] != kInvalidSeat) continue;
    for (int card2 = card1 + 1; card2 < kDeckSize; ++card2) {
      if (holder[card2] != kInvalidSeat) continue;
      actions.push_back(CardsToChanceOutcome(card2, card1));
    }
  }
  const int num_actions = actions.size();
  std::vector<std::pair<Action, double>> outcomes;
  outcomes.reserve(num_actions);
  for (auto action : actions) {
    outcomes.emplace_back(action, 1.0 / num_actions);
  }
  return outcomes;
}
References action, open_spiel::tiny_bridge::kDeckSize, and open_spiel::tiny_bridge::kInvalidSeat.
Clone()
std::unique_ptr< State > open_spiel::tiny_bridge::TinyBridgeAuctionState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 710 of file tiny_bridge.cc.
{
  return std::unique_ptr<State>{new TinyBridgeAuctionState(*this)};
}
References TinyBridgeAuctionState().
CurrentPlayer()
int open_spiel::tiny_bridge::TinyBridgeAuctionState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 513 of file tiny_bridge.cc.
{
  if (IsTerminal()) return kTerminalPlayerId;
  return actions_.size() < num_players_ ? kChancePlayerId
                                        : actions_.size() % num_players_;
}
References IsTerminal(), open_spiel::kChancePlayerId, open_spiel::kTerminalPlayerId, and open_spiel::State::num_players_.
Referenced by LegalActions().
DealString()
std::string open_spiel::tiny_bridge::TinyBridgeAuctionState::DealString () const
Definition at line 316 of file tiny_bridge.cc.
{
  std::string deal;
  for (auto player = Player{0}; player < num_players_; ++player) {
    if (player != 0) deal.push_back(' ');
    absl::StrAppend(&deal, SeatString(PlayerToSeat(player)), ":",
                    PlayerHandString(player, /*abstracted=*/false));
  }
  return deal;
}
References open_spiel::State::num_players_, player, PlayerHandString(), open_spiel::tiny_bridge::SeatString(), and absl::StrAppend().
Referenced by ToString().
DoApplyAction()
void open_spiel::tiny_bridge::TinyBridgeAuctionState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 442 of file tiny_bridge.cc.
{
  actions_.push_back(action);
  if (num_players_ == 2) {
    if (actions_.size() >= 2 * num_players_ && actions_.back() == Call::kPass) {
      is_terminal_ = true;
      utility_p0 = Score_2p(actions_[0], actions_[1], AnalyzeAuction());
    }
  } else {
    if (actions_.size() >= 2 * num_players_ &&
        actions_[actions_.size() - 1] == Call::kPass &&
        actions_[actions_.size() - 2] == Call::kPass &&
        actions_[actions_.size() - 3] == Call::kPass) {
      is_terminal_ = true;
      utility_p0 = Score_p0(CardHolders(), AnalyzeAuction());
    }
  }
}
References action, open_spiel::tiny_bridge::kPass, open_spiel::State::num_players_, open_spiel::tiny_bridge::Score_2p(), and open_spiel::tiny_bridge::Score_p0().
InformationStateString()
std::string open_spiel::tiny_bridge::TinyBridgeAuctionState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 552 of file tiny_bridge.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string hand = PlayerHandString(player, is_abstracted_);
  std::string dealer = RelativeSeatString(Seat::kWest, PlayerToSeat(player));
  std::string auction = AuctionString();
  if (!auction.empty())
    return absl::StrCat(hand, " ", dealer, " ", auction);
  else
    return hand;
}
References AuctionString(), dealer, open_spiel::tiny_bridge::kWest, open_spiel::State::num_players_, player, PlayerHandString(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
InformationStateTensor()
void open_spiel::tiny_bridge::TinyBridgeAuctionState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 607 of file tiny_bridge.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  const int hand_size = is_abstracted_ ? kNumAbstractHands : kDeckSize;
  const int auction_size = (num_players_ == 2)
                               ? kNumActions2p * num_players_
                               : num_players_ + kNumBids * num_players_ * 3;
  std::fill(values.begin(), values.end(), 0);
  SPIEL_CHECK_EQ(values.size(), hand_size + auction_size);
  if (IsDealt(player)) {
    if (is_abstracted_) {
      const int abstraction = ChanceOutcomeToHandAbstraction(actions_[player]);
      values.at(abstraction) = 1;
    } else {
      const auto cards = ChanceOutcomeToCards(actions_[player]);
      values.at(cards.first) = 1;
      values.at(cards.second) = 1;
    }
  }
  if (num_players_ == 2) {
    for (int i = num_players_; i < actions_.size(); ++i) {
      values.at(hand_size + actions_[i] * 2 + (i - player) % num_players_) = 1;
    }
  } else {
    auto last_bid = Call::kPass;
    auto observer = PlayerToSeat(player);
    for (int i = num_players_; i < actions_.size(); ++i) {
      int bidder = RelativeSeatIndex(Seat(i % num_players_), observer);
      if (actions_[i] == Call::kPass) {
        if (last_bid == Call::kPass) {
          values.at(hand_size + bidder) = 1;
        }
      } else if (actions_[i] == Call::kDouble) {
        values.at(hand_size + num_players_ +
                  (last_bid - 1) * (3 * num_players_) + bidder) = 1;
      } else if (actions_[i] == Call::kRedouble) {
        values.at(hand_size + num_players_ +
                  (last_bid - 1) * (3 * num_players_) + num_players_ + bidder) =
            1;
      } else {
        last_bid = Call(actions_[i]);
        values.at(hand_size + num_players_ +
                  (last_bid - 1) * (3 * num_players_) + num_players_ * 2 +
                  bidder) = 1;
      }
    }
  }
}
References i, open_spiel::tiny_bridge::kDeckSize, open_spiel::tiny_bridge::kDouble, open_spiel::tiny_bridge::kNumAbstractHands, open_spiel::tiny_bridge::kNumActions2p, open_spiel::tiny_bridge::kNumBids, open_spiel::tiny_bridge::kPass, open_spiel::tiny_bridge::kRedouble, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::tiny_bridge::TinyBridgeAuctionState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 537 of file tiny_bridge.cc.
{ return is_terminal_; }
Referenced by CurrentPlayer(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::tiny_bridge::TinyBridgeAuctionState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 460 of file tiny_bridge.cc.
{
  std::vector<Action> actions;
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else if (IsTerminal()) {
    return {};
  } else {
    auto state = AnalyzeAuction();
    actions.push_back(Call::kPass);
    for (int bid = state.last_bid + 1; bid <= Call::k2NT; ++bid) {
      actions.push_back(bid);
    }
    if (num_players_ == 4 && state.last_bidder != kInvalidSeat) {
      if (state.last_bidder % 2 != CurrentPlayer() % 2) {
        if (state.doubler == kInvalidSeat) actions.push_back(Call::kDouble);
      } else {
        if (state.doubler != kInvalidSeat && state.redoubler == kInvalidSeat)
          actions.push_back(Call::kRedouble);
      }
    }
  }
  return actions;
}
References CurrentPlayer(), open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::tiny_bridge::k2NT, open_spiel::tiny_bridge::kDouble, open_spiel::tiny_bridge::kInvalidSeat, open_spiel::tiny_bridge::kPass, open_spiel::tiny_bridge::kRedouble, open_spiel::State::LegalChanceOutcomes(), open_spiel::State::num_players_, and state.
ObservationString()
std::string open_spiel::tiny_bridge::TinyBridgeAuctionState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 573 of file tiny_bridge.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string observation = PlayerHandString(player, is_abstracted_);
  if (HasAuctionStarted()) {
    auto state = AnalyzeAuction();
    if (state.last_bid != Call::kPass) {
      absl::StrAppend(
          &observation, " ", ActionToString(state.last_bidder, state.last_bid),
          ":", RelativeSeatString(state.last_bidder, PlayerToSeat(player)));
    }
    if (state.doubler != kInvalidSeat)
      absl::StrAppend(&observation, " ", "Dbl:",
                      RelativeSeatString(state.doubler, PlayerToSeat(player)));
    if (state.redoubler != kInvalidSeat)
      absl::StrAppend(
          &observation, " ",
          "RDbl:", RelativeSeatString(state.redoubler, PlayerToSeat(player)));
  }
  return observation;
}
References ActionToString(), open_spiel::tiny_bridge::kInvalidSeat, open_spiel::tiny_bridge::kPass, open_spiel::State::num_players_, player, PlayerHandString(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, state, and absl::StrAppend().
ObservationTensor()
void open_spiel::tiny_bridge::TinyBridgeAuctionState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 668 of file tiny_bridge.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  const int hand_size = is_abstracted_ ? kNumAbstractHands : kDeckSize;
  const int auction_size =
      num_players_ == 2 ? kNumActions2p : kNumBids + 4 * num_players_;
  std::fill(values.begin(), values.end(), 0);
  SPIEL_CHECK_EQ(values.size(), hand_size + auction_size);
  if (IsDealt(player)) {
    if (is_abstracted_) {
      const int abstraction = ChanceOutcomeToHandAbstraction(actions_[player]);
      values.at(abstraction) = 1;
    } else {
      const auto cards = ChanceOutcomeToCards(actions_[player]);
      values.at(cards.first) = 1;
      values.at(cards.second) = 1;
    }
  }
  if (num_players_ == 2) {
    if (HasAuctionStarted()) {
      values.at(hand_size + actions_.back()) = 1;
    }
  } else {
    auto state = AnalyzeAuction();
    auto seat = PlayerToSeat(player);
    if (state.last_bidder != kInvalidSeat)
      values.at(hand_size + RelativeSeatIndex(state.last_bidder, seat)) = 1;
    if (state.doubler != kInvalidSeat)
      values.at(hand_size + kNumSeats +
                RelativeSeatIndex(state.doubler, seat)) = 1;
    if (state.redoubler != kInvalidSeat)
      values.at(hand_size + kNumSeats * 2 +
                RelativeSeatIndex(state.redoubler, seat)) = 1;
    values.at(hand_size + kNumSeats * 3 +
              RelativeSeatIndex(Seat::kWest, seat)) = 1;
    if (state.last_bidder != kInvalidSeat)
      values.at(hand_size + kNumSeats * 4 + state.last_bid - 1) = 1;
  }
}
References open_spiel::tiny_bridge::kDeckSize, open_spiel::tiny_bridge::kInvalidSeat, open_spiel::tiny_bridge::kNumAbstractHands, open_spiel::tiny_bridge::kNumActions2p, open_spiel::tiny_bridge::kNumBids, open_spiel::tiny_bridge::kNumSeats, open_spiel::tiny_bridge::kWest, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, state, and values.
PlayerHandString()
std::string open_spiel::tiny_bridge::TinyBridgeAuctionState::PlayerHandString (Player player, bool abstracted) const
Definition at line 309 of file tiny_bridge.cc.
{
  if (!IsDealt(player)) return "??";
  return abstracted ? ChanceOutcomeToHandAbstractionString(actions_[player])
                    : HandString(actions_[player]);
}
References open_spiel::tiny_bridge::HandString(), and player.
Referenced by DealString(), InformationStateString(), and ObservationString().
Returns()
std::vector< double > open_spiel::tiny_bridge::TinyBridgeAuctionState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 539 of file tiny_bridge.cc.
{
  if (!IsTerminal()) {
    return std::vector<double>(num_players_, 0.0);
  }
  if (num_players_ == 2) {
    return {utility_p0, utility_p0};
  } else {
    // 4 player version.
    return {utility_p0, -utility_p0, utility_p0, -utility_p0};
  }
}
References IsTerminal(), and open_spiel::State::num_players_.
ToString()
std::string open_spiel::tiny_bridge::TinyBridgeAuctionState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 528 of file tiny_bridge.cc.
{
  std::string deal = DealString();
  std::string auction = AuctionString();
  if (!auction.empty())
    return absl::StrCat(deal, " ", auction);
  else
    return deal;
}
References AuctionString(), DealString(), and absl::StrCat().
UndoAction()
void open_spiel::tiny_bridge::TinyBridgeAuctionState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 714 of file tiny_bridge.cc.
{
  actions_.pop_back();
  history_.pop_back();
  --move_number_;
  is_terminal_ = false;
}
References open_spiel::State::history_, and open_spiel::State::move_number_.
The documentation for this class was generated from the following files:
open_spiel/games/tiny_bridge/tiny_bridge.h
open_spiel/games/tiny_bridge/tiny_bridge.cc