open spiel: open_spiel::negotiation::NegotiationState Class Reference
open_spiel::negotiation::NegotiationState Class Reference
#include <negotiation.h>
Public Member Functions
NegotiationState (std::shared_ptr< const Game > game)
NegotiationState (const NegotiationState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move_id) const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
const std::vector< int > & ItemPool () const
const std::vector< std::vector< int > > & AgentUtils () const
std::vector< int > & ItemPool ()
std::vector< std::vector< int > > & AgentUtils ()
void SetCurrentPlayer (Player p)
int MaxSteps () const
void SetMaxSteps (int max_steps)
std::string Serialize () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 74 of file negotiation.h.
Constructor & Destructor Documentation
NegotiationState() [1/2]
open_spiel::negotiation::NegotiationState::NegotiationState (std::shared_ptr< const Game > game)
Definition at line 261 of file negotiation.cc.
    : State(game),
      parent_game_(static_cast<const NegotiationGame&>(*game)),
      enable_proposals_(parent_game_.EnableProposals()),
      enable_utterances_(parent_game_.EnableUtterances()),
      num_items_(parent_game_.NumItems()),
      num_symbols_(parent_game_.NumSymbols()),
      utterance_dim_(parent_game_.UtteranceDim()),
      num_steps_(0),
      max_steps_(-1),
      agreement_reached_(false),
      cur_player_(kChancePlayerId),
      turn_type_(TurnType::kProposal),
      item_pool_({}),
      agent_utils_({}),
      proposals_({}),
      utterances_({}) {}
Referenced by Clone().
NegotiationState() [2/2]
open_spiel::negotiation::NegotiationState::NegotiationState (const NegotiationState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::negotiation::NegotiationState::ActionToString (Player player, Action move_id) const override virtual
Implements open_spiel::State.
Definition at line 79 of file negotiation.cc.
{
  if (player == kChancePlayerId) {
    return absl::StrCat("chance outcome ", move_id);
  } else {
    std::string action_string = "";
    if (turn_type_ == TurnType::kProposal) {
      if (move_id == parent_game_.NumDistinctProposals() - 1) {
        absl::StrAppend(&action_string, "Proposal: Agreement reached!");
      } else {
        std::vector<int> proposal = DecodeProposal(move_id);
        std::string prop_str = absl::StrJoin(proposal, ", ");
        absl::StrAppend(&action_string, "Proposal: [", prop_str, "]");
      }
    } else {
      std::vector<int> utterance = DecodeUtterance(move_id);
      std::string utt_str = absl::StrJoin(utterance, ", ");
      absl::StrAppend(&action_string, ", Utterance: [", utt_str, "]");
    }
    return action_string;
  }
}
References open_spiel::kChancePlayerId, open_spiel::negotiation::kProposal, open_spiel::negotiation::NegotiationGame::NumDistinctProposals(), player, absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
AgentUtils() [1/2]
std::vector< std::vector< int > > & open_spiel::negotiation::NegotiationState::AgentUtils () inline
Definition at line 97 of file negotiation.h.
{ return agent_utils_; }
AgentUtils() [2/2]
const std::vector< std::vector< int > > & open_spiel::negotiation::NegotiationState::AgentUtils () const inline
Definition at line 93 of file negotiation.h.
{
    return agent_utils_;
  }
Referenced by open_spiel::negotiation::NegotiationGame::DeserializeState(), and Serialize().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::negotiation::NegotiationState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 452 of file negotiation.cc.
          {
  SPIEL_CHECK_TRUE(IsChanceNode());
  // The game has chance mode kSampledStochastic, so there is only a single
  // outcome, and it's all randomized in the ApplyAction.
  std::vector<std::pair<Action, double>> outcomes = {std::make_pair(0, 1.0)};
  return outcomes;
}
References open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::negotiation::NegotiationState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 496 of file negotiation.cc.
{
  return std::unique_ptr<State>(new NegotiationState(*this));
}
References NegotiationState().
CurrentPlayer()
int open_spiel::negotiation::NegotiationState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 279 of file negotiation.cc.
{
  return IsTerminal() ? kTerminalPlayerId : cur_player_;
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by ObservationString(), and ObservationTensor().
DoApplyAction()
void open_spiel::negotiation::NegotiationState::DoApplyAction (Action move_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 326 of file negotiation.cc.
{
  if (IsChanceNode()) {
    DetermineItemPoolAndUtilities();
    InitializeEpisode();
  } else {
    if (turn_type_ == TurnType::kProposal) {
      if (move_id == parent_game_.NumDistinctProposals() - 1) {
        // Agreement!
        agreement_reached_ = true;
      } else {
        std::vector<int> proposal = DecodeProposal(move_id);
        proposals_.push_back(proposal);
      }
      if (enable_utterances_) {
        // Note: do not move to next player yet.
        turn_type_ = TurnType::kUtterance;
      } else {
        // Keep it at kProposal, but move to next player.
        cur_player_ = 1 - cur_player_;
      }
    } else {
      SPIEL_CHECK_TRUE(enable_utterances_);
      std::vector<int> utterance = DecodeUtterance(move_id);
      utterances_.push_back(utterance);
      turn_type_ = TurnType::kProposal;
      cur_player_ = 1 - cur_player_;
    }
  }
}
References open_spiel::State::IsChanceNode(), open_spiel::negotiation::kProposal, open_spiel::negotiation::kUtterance, open_spiel::negotiation::NegotiationGame::NumDistinctProposals(), and SPIEL_CHECK_TRUE.
IsTerminal()
bool open_spiel::negotiation::NegotiationState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 102 of file negotiation.cc.
{
  // If utterances are enabled, force the agent to utter something even when
  // they accept the proposal or run out of steps (i.e. on ther last turn).
  bool utterance_check =
      (enable_utterances_ ? utterances_.size() == proposals_.size() : true);
  return (agreement_reached_ || proposals_.size() >= max_steps_) &&
         utterance_check;
}
Referenced by CurrentPlayer(), LegalActions(), ObservationTensor(), and Returns().
ItemPool() [1/2]
std::vector< int > & open_spiel::negotiation::NegotiationState::ItemPool () inline
Definition at line 96 of file negotiation.h.
{ return item_pool_; }
ItemPool() [2/2]
const std::vector< int > & open_spiel::negotiation::NegotiationState::ItemPool () const inline
Definition at line 92 of file negotiation.h.
{ return item_pool_; }
Referenced by open_spiel::negotiation::NegotiationGame::DeserializeState(), and Serialize().
LegalActions()
std::vector< Action > open_spiel::negotiation::NegotiationState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 423 of file negotiation.cc.
{
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else if (IsTerminal()) {
    return {};
  } else if (turn_type_ == TurnType::kProposal) {
    std::vector<Action> legal_actions;
    // Proposals are always enabled, so first contruct them.
    std::vector<int> proposal(num_items_, 0);
    legal_actions.push_back(EncodeProposal(proposal));
    while (NextProposal(&proposal)) {
      legal_actions.push_back(EncodeProposal(proposal));
    }
    if (!proposals_.empty()) {
      // Add the agreement action only if there's been at least one proposal.
      legal_actions.push_back(parent_game_.NumDistinctProposals() - 1);
    }
    return legal_actions;
  } else {
    SPIEL_CHECK_TRUE(enable_utterances_);
    SPIEL_CHECK_FALSE(parent_game_.LegalUtterances().empty());
    return parent_game_.LegalUtterances();
  }
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::negotiation::kProposal, open_spiel::State::LegalChanceOutcomes(), open_spiel::negotiation::NegotiationGame::LegalUtterances(), open_spiel::negotiation::NegotiationGame::NumDistinctProposals(), SPIEL_CHECK_FALSE, and SPIEL_CHECK_TRUE.
MaxSteps()
int open_spiel::negotiation::NegotiationState::MaxSteps () const inline
Definition at line 99 of file negotiation.h.
{ return max_steps_; }
Referenced by Serialize().
ObservationString()
std::string open_spiel::negotiation::NegotiationState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 131 of file negotiation.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (IsChanceNode()) {
    return "ChanceNode -- no observation";
  }
  std::string str = absl::StrCat("Max steps: ", max_steps_, "\n");
  absl::StrAppend(&str, "Item pool: ", absl::StrJoin(item_pool_, " "), "\n");
  if (!agent_utils_.empty()) {
    absl::StrAppend(&str, "Agent ", player,
                    " util vec: ", absl::StrJoin(agent_utils_[player], " "),
                    "\n");
  }
  absl::StrAppend(&str, "Current player: ", CurrentPlayer(), "\n");
  absl::StrAppend(&str, "Turn Type: ", TurnTypeToString(turn_type_), "\n");
  if (!proposals_.empty()) {
    absl::StrAppend(&str, "Most recent proposal: [",
                    absl::StrJoin(proposals_.back(), ", "), "]\n");
  }
  if (!utterances_.empty()) {
    absl::StrAppend(&str, "Most recent utterance: [",
                    absl::StrJoin(utterances_.back(), ", "), "]\n");
  }
  return str;
}
References CurrentPlayer(), open_spiel::State::IsChanceNode(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
ObservationTensor()
void open_spiel::negotiation::NegotiationState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 180 of file negotiation.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), parent_game_.ObservationTensorSize());
  std::fill(values.begin(), values.end(), 0);
  // No observations at chance nodes.
  if (IsChanceNode()) {
    return;
  }
  // 1D vector with shape:
  //   - Current player: 2 bits
  //   - Turn type: 2 bits
  //   - Terminal status: 2 bits: (Terminal? and Agreement reached?)
  //   - Context:
  //     - item pool      (num_items * (max_quantity + 1) bits)
  //     - my utilities   (num_items * (max_value + 1) bits)
  //   - Last proposal:   (num_items * (max_quantity + 1) bits)
  // If utterances are enabled, another:
  //   - Last utterance:  (utterance_dim * num_symbols) bits)
  // Current player.
  int offset = 0;
  if (!IsTerminal()) {
    values[offset + CurrentPlayer()] = 1;
  }
  offset += kNumPlayers;
  // Current turn type.
  if (turn_type_ == TurnType::kProposal) {
    values[offset] = 1;
  } else {
    values[offset + 1] = 1;
  }
  offset += 2;
  // Terminal status: 2 bits
  values[offset] = IsTerminal() ? 1 : 0;
  values[offset + 1] = agreement_reached_ ? 1 : 0;
  offset += 2;
  // Item pool.
  for (int item = 0; item < num_items_; ++item) {
    values[offset + item_pool_[item]] = 1;
    offset += kMaxQuantity + 1;
  }
  // Utilities.
  for (int item = 0; item < num_items_; ++item) {
    values[offset + agent_utils_[player][item]] = 1;
    offset += kMaxValue + 1;
  }
  // Last proposal.
  if (!proposals_.empty()) {
    for (int item = 0; item < num_items_; ++item) {
      values[offset + proposals_.back()[item]] = 1;
      offset += kMaxQuantity + 1;
    }
  } else {
    offset += num_items_ * (kMaxQuantity + 1);
  }
  // Last utterance.
  if (enable_utterances_) {
    if (!utterances_.empty()) {
      for (int dim = 0; dim < utterance_dim_; ++dim) {
        values[offset + utterances_.back()[dim]] = 1;
        offset += num_symbols_;
      }
    } else {
      offset += utterance_dim_ * num_symbols_;
    }
  }
  SPIEL_CHECK_EQ(offset, values.size());
}
References CurrentPlayer(), open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::negotiation::kMaxQuantity, open_spiel::negotiation::kMaxValue, open_spiel::negotiation::kNumPlayers, open_spiel::negotiation::kProposal, open_spiel::State::num_players_, open_spiel::Game::ObservationTensorSize(), player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::negotiation::NegotiationState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 111 of file negotiation.cc.
{
  if (!IsTerminal() || !agreement_reached_) {
    return std::vector<double>(num_players_, 0.0);
  }
  int proposing_player = proposals_.size() % 2 == 1 ? 0 : 1;
  int other_player = 1 - proposing_player;
  const std::vector<int>& final_proposal = proposals_.back();
  std::vector<double> returns(num_players_, 0.0);
  for (int j = 0; j < num_items_; ++j) {
    returns[proposing_player] +=
        agent_utils_[proposing_player][j] * final_proposal[j];
    returns[other_player] +=
        agent_utils_[other_player][j] * (item_pool_[j] - final_proposal[j]);
  }
  return returns;
}
References IsTerminal(), and open_spiel::State::num_players_.
Serialize()
std::string open_spiel::negotiation::NegotiationState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 553 of file negotiation.cc.
{
  if (IsChanceNode()) {
    return "chance";
  } else {
    std::string state_str = "";
    absl::StrAppend(&state_str, MaxSteps(), "\n");
    absl::StrAppend(&state_str, absl::StrJoin(ItemPool(), " "), "\n");
    for (int p = 0; p < NumPlayers(); ++p) {
      absl::StrAppend(&state_str, absl::StrJoin(AgentUtils()[p], " "), "\n");
    }
    absl::StrAppend(&state_str, HistoryString(), "\n");
    return state_str;
  }
}
References AgentUtils(), open_spiel::State::HistoryString(), open_spiel::State::IsChanceNode(), ItemPool(), MaxSteps(), open_spiel::State::NumPlayers(), absl::StrAppend(), and absl::StrJoin().
SetCurrentPlayer()
void open_spiel::negotiation::NegotiationState::SetCurrentPlayer (Player p) inline
Definition at line 98 of file negotiation.h.
{ cur_player_ = p; }
Referenced by open_spiel::negotiation::NegotiationGame::DeserializeState().
SetMaxSteps()
void open_spiel::negotiation::NegotiationState::SetMaxSteps (int max_steps) inline
Definition at line 100 of file negotiation.h.
{ max_steps_ = max_steps; }
Referenced by open_spiel::negotiation::NegotiationGame::DeserializeState().
ToString()
std::string open_spiel::negotiation::NegotiationState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 461 of file negotiation.cc.
{
  if (IsChanceNode()) {
    return "Initial chance node";
  }
  std::string str = absl::StrCat("Max steps: ", max_steps_, "\n");
  absl::StrAppend(&str, "Item pool: ", absl::StrJoin(item_pool_, " "), "\n");
  if (!agent_utils_.empty()) {
    for (int i = 0; i < num_players_; ++i) {
      absl::StrAppend(&str, "Agent ", i,
                      " util vec: ", absl::StrJoin(agent_utils_[i], " "), "\n");
    }
  }
  absl::StrAppend(&str, "Current player: ", cur_player_, "\n");
  absl::StrAppend(&str, "Turn Type: ", TurnTypeToString(turn_type_), "\n");
  for (int i = 0; i < proposals_.size(); ++i) {
    absl::StrAppend(&str, "Player ", i % 2, " proposes: [",
                    absl::StrJoin(proposals_[i], ", "), "]");
    if (enable_utterances_ && i < utterances_.size()) {
      absl::StrAppend(&str, " utters: [", absl::StrJoin(utterances_[i], ", "),
                      "]");
    }
    absl::StrAppend(&str, "\n");
  }
  if (agreement_reached_) {
    absl::StrAppend(&str, "Agreement reached!\n");
  }
  return str;
}
References i, open_spiel::State::IsChanceNode(), open_spiel::State::num_players_, absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
The documentation for this class was generated from the following files:
open_spiel/games/negotiation/negotiation.h
open_spiel/games/negotiation/negotiation.cc