open spiel: open_spiel::dynamic_routing::Network Class Reference
open_spiel::dynamic_routing::Network Class Reference
#include <dynamic_routing_utils.h>
Public Member Functions
bool IsLocationASinkNode (absl::string_view road_section) const
float GetTravelTime (absl::string_view road_section, float volume) const
int GetActionIdFromMovement (absl::string_view origin, absl::string_view destination) const
int num_links () const
int num_actions () const
std::vector< std::string > GetSuccessors (absl::string_view node) const
std::string GetRoadSectionFromActionId (int action) const
int GetRoadSectionAsInt (std::string section) const
void AssertValidAction (int action, std::string road_section="") const
void CheckListOfOdDemandIsCorrect (std::vector< OriginDestinationDemand > *od_demands)
Static Public Member Functions
static std::unique_ptr< Network > Create (const absl::flat_hash_map< std::string, std::vector< std::string > > &adjacency_list, const absl::flat_hash_map< std::string, std::pair< float, float > > &node_position={}, const absl::flat_hash_map< std::string, float > &bpr_a_coefficient={}, const absl::flat_hash_map< std::string, float > &bpr_b_coefficient={}, const absl::flat_hash_map< std::string, float > &capacity={}, const absl::flat_hash_map< std::string, float > &free_flow_travel_time={})
Detailed Description
Definition at line 95 of file dynamic_routing_utils.h.
Member Function Documentation
AssertValidAction()
void open_spiel::dynamic_routing::Network::AssertValidAction (int action, std::string road_section = "") const
Definition at line 175 of file dynamic_routing_utils.cc.
{
  SPIEL_CHECK_GE(action, 1);
  SPIEL_CHECK_LT(action, num_actions());
  if (!road_section.empty()) {
    std::string new_road_section = GetRoadSectionFromActionId(action);
    std::vector<std::string> nodes = NodesFromRoadSection(new_road_section);
    std::string origin_new_section = nodes[0];
    std::string end_new_section = nodes[1];
    std::string end_section_node = NodesFromRoadSection(road_section)[1];
    SPIEL_CHECK_EQ(end_section_node, origin_new_section);
    std::vector<std::string> successors = GetSuccessors(origin_new_section);
    SPIEL_CHECK_TRUE(std::find(successors.begin(), successors.end(),
                               end_new_section) != successors.end());
  }
}
References action, GetRoadSectionFromActionId(), GetSuccessors(), open_spiel::dynamic_routing::NodesFromRoadSection(), num_actions(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and SPIEL_CHECK_TRUE.
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGameState::ActionToString(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::DoApplyAction(), and open_spiel::dynamic_routing::MeanFieldRoutingGameState::LegalActions().
CheckListOfOdDemandIsCorrect()
void open_spiel::dynamic_routing::Network::CheckListOfOdDemandIsCorrect (std::vector< OriginDestinationDemand > * od_demands)
Definition at line 191 of file dynamic_routing_utils.cc.
{
  for (const OriginDestinationDemand& od_demand : *od_demands) {
    SPIEL_CHECK_TRUE(
        action_by_road_section_.contains(od_demand.vehicle.origin));
    SPIEL_CHECK_TRUE(
        action_by_road_section_.contains(od_demand.vehicle.destination));
  }
}
References SPIEL_CHECK_TRUE.
Create()
std::unique_ptr< Network > open_spiel::dynamic_routing::Network::Create (const absl::flat_hash_map< std::string, std::vector< std::string > > & adjacency_list, const absl::flat_hash_map< std::string, std::pair< float, float > > & node_position = {}, const absl::flat_hash_map< std::string, float > & bpr_a_coefficient = {}, const absl::flat_hash_map< std::string, float > & bpr_b_coefficient = {}, const absl::flat_hash_map< std::string, float > & capacity = {}, const absl::flat_hash_map< std::string, float > & free_flow_travel_time = {}) static
Definition at line 72 of file dynamic_routing_utils.cc.
{
  return absl::WrapUnique(new Network(adjacency_list, node_position,
                                      bpr_a_coefficient, bpr_b_coefficient,
                                      capacity, free_flow_travel_time));
}
References absl::WrapUnique().
Referenced by open_spiel::dynamic_routing::DynamicRoutingData::Create().
GetActionIdFromMovement()
int open_spiel::dynamic_routing::Network::GetActionIdFromMovement (absl::string_view origin, absl::string_view destination) const
Definition at line 145 of file dynamic_routing_utils.cc.
{
  std::string section = RoadSectionFromNodes(origin, destination);
  SPIEL_CHECK_TRUE(action_by_road_section_.contains(section));
  return action_by_road_section_.at(section);
}
References open_spiel::dynamic_routing::RoadSectionFromNodes(), and SPIEL_CHECK_TRUE.
Referenced by GetRoadSectionAsInt(), and open_spiel::dynamic_routing::MeanFieldRoutingGameState::LegalActions().
GetRoadSectionAsInt()
int open_spiel::dynamic_routing::Network::GetRoadSectionAsInt (std::string section) const
Definition at line 165 of file dynamic_routing_utils.cc.
{
  if (section.empty()) {
    return 0;
  }
  std::vector<std::string> nodes = NodesFromRoadSection(section);
  std::string start_node = nodes[0];
  std::string end_node = nodes[1];
  return GetActionIdFromMovement(start_node, end_node);
}
References GetActionIdFromMovement(), and open_spiel::dynamic_routing::NodesFromRoadSection().
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGameState::GetDestinationAsActionInt(), and open_spiel::dynamic_routing::MeanFieldRoutingGameState::GetLocationAsActionInt().
GetRoadSectionFromActionId()
std::string open_spiel::dynamic_routing::Network::GetRoadSectionFromActionId (int action) const
Definition at line 161 of file dynamic_routing_utils.cc.
{
  return road_section_by_action.at(action);
}
References action.
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGameState::ActionToString(), AssertValidAction(), and open_spiel::dynamic_routing::MeanFieldRoutingGameState::DoApplyAction().
GetSuccessors()
std::vector< std::string > open_spiel::dynamic_routing::Network::GetSuccessors (absl::string_view node) const
Definition at line 156 of file dynamic_routing_utils.cc.
{
  SPIEL_CHECK_TRUE(adjacency_list_.contains(node));
  return adjacency_list_.at(node);
}
References SPIEL_CHECK_TRUE.
Referenced by AssertValidAction(), and open_spiel::dynamic_routing::MeanFieldRoutingGameState::LegalActions().
GetTravelTime()
float open_spiel::dynamic_routing::Network::GetTravelTime (absl::string_view road_section, float volume) const
Definition at line 127 of file dynamic_routing_utils.cc.
{
  SPIEL_CHECK_TRUE(free_flow_travel_time_.contains(road_section));
  SPIEL_CHECK_TRUE(bpr_a_coefficient_.contains(road_section));
  SPIEL_CHECK_TRUE(bpr_b_coefficient_.contains(road_section));
  SPIEL_CHECK_TRUE(capacity_.contains(road_section));
  float free_flow_travel_time = free_flow_travel_time_.at(road_section);
  float a = bpr_a_coefficient_.at(road_section);
  float b = bpr_b_coefficient_.at(road_section);
  float capacity = capacity_.at(road_section);
  return free_flow_travel_time * (1.0 + a * pow(volume / capacity, b));
}
References a, b, and SPIEL_CHECK_TRUE.
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGameState::UpdateDistribution().
IsLocationASinkNode()
bool open_spiel::dynamic_routing::Network::IsLocationASinkNode (absl::string_view road_section) const
Definition at line 141 of file dynamic_routing_utils.cc.
{
  return sink_road_sections_.contains(road_section);
}
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::contains().
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGameState::DoApplyAction().
num_actions()
int open_spiel::dynamic_routing::Network::num_actions () const
Definition at line 154 of file dynamic_routing_utils.cc.
{ return 1 + this->num_links(); }
References num_links().
Referenced by open_spiel.python.games.dynamic_routing_utils.Network::assert_valid_action(), AssertValidAction(), open_spiel.python.pytorch.ppo.PPOAgent::get_action_and_value(), open_spiel.python.pytorch.ppo.PPOAtariAgent::get_action_and_value(), models.OptimizerModel::initialize_optimizer_model(), open_spiel.python.pytorch.ppo.PPO::learn(), regret_matching_agent.RegretMatchingAgent::regret_matching_policy(), and open_spiel.python.pytorch.ppo.PPO::step().
num_links()
int open_spiel::dynamic_routing::Network::num_links () const
Definition at line 152 of file dynamic_routing_utils.cc.
{ return this->action_by_road_section_.size(); }
Referenced by open_spiel.python.games.dynamic_routing_utils.Network::num_actions(), and num_actions().
The documentation for this class was generated from the following files:
open_spiel/games/dynamic_routing/dynamic_routing_utils.h
open_spiel/games/dynamic_routing/dynamic_routing_utils.cc