open spiel: open_spiel::ThreadedQueue< T > Class Template Reference
open_spiel::ThreadedQueue< T > Class Template Reference
#include <threaded_queue.h>
Public Member Functions
ThreadedQueue (int max_size)
bool Push (const T &value)
bool Push (const T &value, absl::Duration wait)
bool Push (const T &value, absl::Time deadline)
absl::optional< T > Pop ()
absl::optional< T > Pop (absl::Duration wait)
absl::optional< T > Pop (absl::Time deadline)
bool Empty ()
void Clear ()
int Size ()
void BlockNewValues ()
Detailed Description
template<class T>
class open_spiel::ThreadedQueue< T >
Definition at line 29 of file threaded_queue.h.
Constructor & Destructor Documentation
ThreadedQueue()
template<class T > open_spiel::ThreadedQueue< T >::ThreadedQueue (int max_size) inline explicit
Definition at line 31 of file threaded_queue.h.
: max_size_(max_size) {}
Member Function Documentation
BlockNewValues()
template<class T > void open_spiel::ThreadedQueue< T >::BlockNewValues () inline
Definition at line 88 of file threaded_queue.h.
{
    absl::MutexLock lock(&m_);
    block_new_values_ = true;
    cv_.SignalAll();
  }
References absl::CondVar::SignalAll().
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), and open_spiel::algorithms::torch_az::VPNetEvaluator::~VPNetEvaluator().
Clear()
template<class T > void open_spiel::ThreadedQueue< T >::Clear () inline
Definition at line 75 of file threaded_queue.h.
               {
    absl::MutexLock lock(&m_);
    while (!q_.empty()) {
      q_.pop();
    }
  }
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), and open_spiel::algorithms::torch_az::VPNetEvaluator::~VPNetEvaluator().
Empty()
template<class T > bool open_spiel::ThreadedQueue< T >::Empty () inline
Definition at line 70 of file threaded_queue.h.
               {
    absl::MutexLock lock(&m_);
    return q_.empty();
  }
Pop() [1/3]
template<class T > absl::optional< T > open_spiel::ThreadedQueue< T >::Pop () inline
Definition at line 54 of file threaded_queue.h.
{ return Pop(absl::InfiniteDuration()); }
References absl::InfiniteDuration(), and open_spiel::ThreadedQueue< T >::Pop().
Referenced by open_spiel::algorithms::torch_az::learner(), and open_spiel::ThreadedQueue< T >::Pop().
Pop() [2/3]
template<class T > absl::optional< T > open_spiel::ThreadedQueue< T >::Pop (absl::Duration wait) inline
Definition at line 55 of file threaded_queue.h.
{ return Pop(absl::Now() + wait); }
References absl::Now(), and open_spiel::ThreadedQueue< T >::Pop().
Referenced by open_spiel::ThreadedQueue< T >::Pop().
Pop() [3/3]
template<class T > absl::optional< T > open_spiel::ThreadedQueue< T >::Pop (absl::Time deadline) inline
Definition at line 56 of file threaded_queue.h.
{
    absl::MutexLock lock(&m_);
    while (q_.empty()) {
      if (absl::Now() > deadline || block_new_values_) {
        return absl::nullopt;
      }
      cv_.WaitWithDeadline(&m_, deadline);
    }
    T val = q_.front();
    q_.pop();
    cv_.Signal();
    return val;
  }
References absl::Now(), absl::CondVar::Signal(), and absl::CondVar::WaitWithDeadline().
Push() [1/3]
template<class T > bool open_spiel::ThreadedQueue< T >::Push (const T & value) inline
Definition at line 34 of file threaded_queue.h.
{ return Push(value, absl::InfiniteDuration()); }
References absl::InfiniteDuration(), and open_spiel::ThreadedQueue< T >::Push().
Referenced by open_spiel::algorithms::torch_az::actor(), open_spiel::ThreadedQueue< T >::Push(), and open_spiel::ThreadedQueue< T >::Push().
Push() [2/3]
template<class T > bool open_spiel::ThreadedQueue< T >::Push (const T & value, absl::Duration wait) inline
Definition at line 35 of file threaded_queue.h.
{
    return Push(value, absl::Now() + wait);
  }
References absl::Now(), and open_spiel::ThreadedQueue< T >::Push().
Push() [3/3]
template<class T > bool open_spiel::ThreadedQueue< T >::Push (const T & value, absl::Time deadline) inline
Definition at line 38 of file threaded_queue.h.
{
    absl::MutexLock lock(&m_);
    if (block_new_values_) {
      return false;
    }
    while (q_.size() >= max_size_) {
      if (absl::Now() > deadline || block_new_values_) {
        return false;
      }
      cv_.WaitWithDeadline(&m_, deadline);
    }
    q_.push(value);
    cv_.Signal();
    return true;
  }
References absl::Now(), absl::CondVar::Signal(), and absl::CondVar::WaitWithDeadline().
Size()
template<class T > int open_spiel::ThreadedQueue< T >::Size () inline
Definition at line 82 of file threaded_queue.h.
             {
    absl::MutexLock lock(&m_);
    return q_.size();
  }
Referenced by open_spiel::algorithms::torch_az::learner().
The documentation for this class was generated from the following file:
open_spiel/utils/threaded_queue.h