open spiel: open_spiel::twixt::Board Class Reference
open_spiel::twixt::Board Class Reference
#include <twixtboard.h>
Public Member Functions
~Board ()
Board ()
Board (int, bool)
int size () const
std::string ToString () const
int result () const
int move_counter () const
std::vector< Action > GetLegalActions (Player player) const
void ApplyAction (Player, Action)
Cell & GetCell (Position position)
const Cell & GetConstCell (Position position) const
Position ActionToPosition (Action action) const
Action PositionToAction (Position position) const
Position GetTensorPosition (Position position, bool turn) const
Detailed Description
Definition at line 52 of file twixtboard.h.
Constructor & Destructor Documentation
~Board()
open_spiel::twixt::Board::~Board () inline
Definition at line 54 of file twixtboard.h.
{}
Board() [1/2]
open_spiel::twixt::Board::Board () inline
Definition at line 55 of file twixtboard.h.
{}
Board() [2/2]
open_spiel::twixt::Board::Board (int size, bool ansi_color_output)
Definition at line 170 of file twixtboard.cc.
{
  set_size(size);
  set_ansi_color_output(ansi_color_output);
  InitializeCells(true);
  InitializeLegalActions();
}
References size().
Member Function Documentation
ActionToPosition()
Position open_spiel::twixt::Board::ActionToPosition (Action action) const
Definition at line 596 of file twixtboard.cc.
{
  return {static_cast<int>(action) / size_, static_cast<int>(action) % size_};
}
References action.
Referenced by open_spiel::twixt::TwixTState::ActionToString(), and ApplyAction().
ApplyAction()
void open_spiel::twixt::Board::ApplyAction (Player player, Action action)
Definition at line 454 of file twixtboard.cc.
{
  Position position = ActionToPosition(action);
  if (move_counter() == 1) {
    // it's the second position
    if (position == move_one()) {
      // blue player swapped
      set_swapped(true);
      // undo the first move: (remove peg and restore legal actions)
      UndoFirstMove();
      // turn position 90° clockwise:
      // [2,3]->[3,5]; [1,4]->[4,6]; [3,2]->[2,4]
      int x = position.y;
      int y = size() - position.x - 1;
      position = {x, y};
    } else {
      // blue player hasn't swapped => regular move
      // remove move one from legal moves
      RemoveLegalAction(kRedPlayer, move_one());
      RemoveLegalAction(kBluePlayer, move_one());
    }
  }
  SetPegAndLinks(player, position);
  if (move_counter() == 0) {
    // do not remove the move from legal actions but store it
    // because second player might want to swap, by choosing the same move
    set_move_one(position);
  } else {
    // otherwise remove move from legal actions
    RemoveLegalAction(kRedPlayer, position);
    RemoveLegalAction(kBluePlayer, position);
  }
  IncMoveCounter();
  // Update the predicted result and update current_player_...
  UpdateResult(player, position);
}
References action, ActionToPosition(), open_spiel::twixt::kBluePlayer, open_spiel::twixt::kRedPlayer, move_counter(), player, size(), Position::x, x, Position::y, and y.
Referenced by open_spiel::twixt::TwixTState::DoApplyAction().
GetCell()
Cell & open_spiel::twixt::Board::GetCell (Position position) inline
Definition at line 66 of file twixtboard.h.
{ return cell_[position.x][position.y]; }
References Position::x, and Position::y.
GetConstCell()
const Cell & open_spiel::twixt::Board::GetConstCell (Position position) const inline
Definition at line 67 of file twixtboard.h.
{
    return cell_[position.x][position.y];
  }
References Position::x, and Position::y.
Referenced by open_spiel::twixt::TwixTState::ObservationTensor().
GetLegalActions()
std::vector< Action > open_spiel::twixt::Board::GetLegalActions (Player player) const inline
Definition at line 62 of file twixtboard.h.
{
    return legal_actions_[player];
  }
References player.
Referenced by open_spiel::twixt::TwixTState::LegalActions().
GetTensorPosition()
Position open_spiel::twixt::Board::GetTensorPosition (Position position, bool turn) const
Definition at line 587 of file twixtboard.cc.
{
  // we flip x/y and top/bottom for better readability in playthrough output
  if (turn) {
    return {size() - position.x - 1, size() - position.y - 2};
  } else {
    return {size() - position.y - 1, position.x - 1};
  }
}
References size(), Position::x, and Position::y.
move_counter()
int open_spiel::twixt::Board::move_counter () const inline
Definition at line 61 of file twixtboard.h.
{ return move_counter_; }
Referenced by ApplyAction().
PositionToAction()
Action open_spiel::twixt::Board::PositionToAction (Position position) const
Definition at line 600 of file twixtboard.cc.
{
  return position.x * size() + position.y;
}
References size(), Position::x, and Position::y.
result()
int open_spiel::twixt::Board::result () const inline
Definition at line 60 of file twixtboard.h.
{ return result_; }
Referenced by open_spiel::twixt::TwixTState::DoApplyAction(), open_spiel::twixt::TwixTState::IsTerminal(), and open_spiel::twixt::TwixTState::Returns().
size()
int open_spiel::twixt::Board::size () const inline
Definition at line 58 of file twixtboard.h.
{ return size_; }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel::twixt::TwixTState::ActionToString(), ApplyAction(), Board(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), GetTensorPosition(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel::twixt::TwixTState::ObservationTensor(), PositionToAction(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), ToString(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
ToString()
std::string open_spiel::twixt::Board::ToString () const
Definition at line 280 of file twixtboard.cc.
{
  std::string s = "";
  // head line
  s.append("     ");
  for (int y = 0; y < size(); y++) {
    std::string letter = "";
    letter += static_cast<int>('a') + y;
    letter += "  ";
    AppendColorString(s, kAnsiRed, letter);
  }
  s.append("\n");
  for (int y = size() - 1; y >= 0; y--) {
    // print "before" row
    s.append("    ");
    for (int x = 0; x < size(); x++) {
      AppendBeforeRow(s, {x, y});
    }
    s.append("\n");
    // print "peg" row
    size() - y < 10 ? s.append("  ") : s.append(" ");
    AppendColorString(s, kAnsiBlue, std::to_string(size() - y) + " ");
    for (int x = 0; x < size(); x++) {
      AppendPegRow(s, {x, y});
    }
    s.append("\n");
    // print "after" row
    s.append("    ");
    for (int x = 0; x < size(); x++) {
      AppendAfterRow(s, {x, y});
    }
    s.append("\n");
  }
  s.append("\n");
  if (swapped_) s.append("[swapped]");
  switch (result_) {
    case kOpen: {
      break;
    }
    case kRedWin: {
      s.append("[x has won]");
      break;
    }
    case kBlueWin: {
      s.append("[o has won]");
      break;
    }
    case kDraw: {
      s.append("[draw]");
      break;
    }
    default: {
      break;
    }
  }
  return s;
}
References open_spiel::twixt::kAnsiBlue, open_spiel::twixt::kAnsiRed, open_spiel::twixt::kBlueWin, open_spiel::twixt::kDraw, open_spiel::twixt::kOpen, open_spiel::twixt::kRedWin, size(), x, and y.
Referenced by open_spiel::twixt::TwixTState::ToString().
The documentation for this class was generated from the following files:
open_spiel/games/twixt/twixtboard.h
open_spiel/games/twixt/twixtboard.cc