open spiel: absl::test_internal::InstanceTracker Class Reference
absl::test_internal::InstanceTracker Class Reference
#include <test_instance_tracker.h>
Public Member Functions
InstanceTracker ()
~InstanceTracker ()
int instances () const
int live_instances () const
int moves () const
int copies () const
int swaps () const
int comparisons () const
void ResetCopiesMovesSwaps ()
Detailed Description
Definition at line 160 of file test_instance_tracker.h.
Constructor & Destructor Documentation
InstanceTracker()
absl::test_internal::InstanceTracker::InstanceTracker () inline
Definition at line 162 of file test_instance_tracker.h.
      : start_instances_(BaseCountedInstance::num_instances_),
        start_live_instances_(BaseCountedInstance::num_live_instances_) {
    ResetCopiesMovesSwaps();
  }
References ResetCopiesMovesSwaps().
~InstanceTracker()
absl::test_internal::InstanceTracker::~InstanceTracker () inline
Definition at line 167 of file test_instance_tracker.h.
                     {
    if (instances() != 0) std::abort();
    if (live_instances() != 0) std::abort();
  }
References instances(), and live_instances().
Member Function Documentation
comparisons()
int absl::test_internal::InstanceTracker::comparisons () const inline
Definition at line 201 of file test_instance_tracker.h.
{
    return BaseCountedInstance::num_comparisons_ - start_comparisons_;
  }
copies()
int absl::test_internal::InstanceTracker::copies () const inline
Definition at line 191 of file test_instance_tracker.h.
                     {
    return BaseCountedInstance::num_copies_ - start_copies_;
  }
instances()
int absl::test_internal::InstanceTracker::instances () const inline
Definition at line 175 of file test_instance_tracker.h.
{
    return BaseCountedInstance::num_instances_ - start_instances_;
  }
Referenced by ~InstanceTracker().
live_instances()
int absl::test_internal::InstanceTracker::live_instances () const inline
Definition at line 181 of file test_instance_tracker.h.
{
    return BaseCountedInstance::num_live_instances_ - start_live_instances_;
  }
Referenced by ~InstanceTracker().
moves()
int absl::test_internal::InstanceTracker::moves () const inline
Definition at line 187 of file test_instance_tracker.h.
{ return BaseCountedInstance::num_moves_ - start_moves_; }
ResetCopiesMovesSwaps()
void absl::test_internal::InstanceTracker::ResetCopiesMovesSwaps () inline
Definition at line 209 of file test_instance_tracker.h.
{
    start_moves_ = BaseCountedInstance::num_moves_;
    start_copies_ = BaseCountedInstance::num_copies_;
    start_swaps_ = BaseCountedInstance::num_swaps_;
    start_comparisons_ = BaseCountedInstance::num_comparisons_;
  }
Referenced by InstanceTracker().
swaps()
int absl::test_internal::InstanceTracker::swaps () const inline
Definition at line 197 of file test_instance_tracker.h.
{ return BaseCountedInstance::num_swaps_ - start_swaps_; }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/test_instance_tracker.h