open spiel: open_spiel::algorithms::torch_az::EvalResults Class Reference
open_spiel::algorithms::torch_az::EvalResults Class Reference
Public Member Functions
EvalResults (int count, int evaluation_window)
int EvalCount ()
std::pair< int, bool > Next ()
void Add (int i, double value)
std::vector< double > AvgResults ()
Detailed Description
Definition at line 209 of file alpha_zero.cc.
Constructor & Destructor Documentation
EvalResults()
open_spiel::algorithms::torch_az::EvalResults::EvalResults (int count, int evaluation_window) inline explicit
Definition at line 211 of file alpha_zero.cc.
{
    results_.reserve(count);
    for (int i = 0; i < count; ++i) {
      results_.emplace_back(evaluation_window);
    }
  }
References i.
Member Function Documentation
Add()
void open_spiel::algorithms::torch_az::EvalResults::Add (int i, double value) inline
Definition at line 232 of file alpha_zero.cc.
{
    absl::MutexLock lock(&m_);
    results_[i].Add(value);
  }
References i.
Referenced by open_spiel::algorithms::torch_az::evaluator().
AvgResults()
std::vector< double > open_spiel::algorithms::torch_az::EvalResults::AvgResults () inline
Definition at line 237 of file alpha_zero.cc.
{
    absl::MutexLock lock(&m_);
    std::vector<double> out;
    out.reserve(results_.size());
    for (const auto& result : results_) {
      out.push_back(result.Empty() ? 0
                                   : (absl::c_accumulate(result.Data(), 0.0) /
                                      result.Size()));
    }
    return out;
  }
References absl::c_accumulate(), and out.
Referenced by open_spiel::algorithms::torch_az::learner().
EvalCount()
int open_spiel::algorithms::torch_az::EvalResults::EvalCount () inline
Definition at line 219 of file alpha_zero.cc.
                  {
    absl::MutexLock lock(&m_);
    return eval_num_ / results_.size();
  }
Referenced by open_spiel::algorithms::torch_az::learner().
Next()
std::pair< int, bool > open_spiel::algorithms::torch_az::EvalResults::Next () inline
Definition at line 225 of file alpha_zero.cc.
{
    absl::MutexLock lock(&m_);
    int next = eval_num_ % (results_.size() * 2);
    eval_num_ += 1;
    return {next / 2, next % 2};
  }
References next.
Referenced by open_spiel::algorithms::torch_az::evaluator().
The documentation for this class was generated from the following file:
open_spiel/algorithms/alpha_zero_torch/alpha_zero.cc