open spiel: open_spiel::leduc_poker::LeducGame Class Reference
open_spiel::leduc_poker::LeducGame Class Reference
#include <leduc_poker.h>
Public Member Functions
LeducGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
absl::optional< double > UtilitySum () const override
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
constexpr int MaxBetsPerRound () const
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int NumObservableCards () const
std::string ActionToString (Player player, Action action) const override
std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Public Attributes
std::shared_ptr< LeducObserver > default_observer_
std::shared_ptr< LeducObserver > info_state_observer_
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 203 of file leduc_poker.h.
Constructor & Destructor Documentation
LeducGame()
open_spiel::leduc_poker::LeducGame::LeducGame (const GameParameters & params) explicit
Definition at line 775 of file leduc_poker.cc.
    : Game(kGameType, params),
      num_players_(ParameterValue<int>("players")),
      total_cards_((num_players_ + 1) * kNumSuits),
      action_mapping_(ParameterValue<bool>("action_mapping")),
      suit_isomorphism_(ParameterValue<bool>("suit_isomorphism")) {
  SPIEL_CHECK_GE(num_players_, kGameType.min_num_players);
  SPIEL_CHECK_LE(num_players_, kGameType.max_num_players);
  default_observer_ = std::make_shared<LeducObserver>(kDefaultObsType);
  info_state_observer_ = std::make_shared<LeducObserver>(kInfoStateObsType);
}
References default_observer_, info_state_observer_, open_spiel::kDefaultObsType, open_spiel::kGameType, open_spiel::kInfoStateObsType, open_spiel::GameType::max_num_players, open_spiel::GameType::min_num_players, SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Member Function Documentation
ActionToString()
std::string open_spiel::leduc_poker::LeducGame::ActionToString (Player player, Action action) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 854 of file leduc_poker.cc.
{
  if (player == kChancePlayerId) {
    return absl::StrCat("Chance outcome:", action);
  } else {
    return StatelessActionToString(action);
  }
}
References action, open_spiel::kChancePlayerId, player, and absl::StrCat().
InformationStateTensorShape()
std::vector< int > open_spiel::leduc_poker::LeducGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 801 of file leduc_poker.cc.
{
  // One-hot encoding for player number (who is to play).
  // 2 slots of cards (total_cards_ bits each): private card, public card
  // Followed by maximum game length * 2 bits each (call / raise)
  if (suit_isomorphism_) {
    return {(num_players_) + (total_cards_) + (MaxGameLength() * 2)};
  } else {
    return {(num_players_) + (total_cards_ * 2) + (MaxGameLength() * 2)};
  }
}
References MaxGameLength().
MakeObserver()
std::shared_ptr< Observer > open_spiel::leduc_poker::LeducGame::MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters & params) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 843 of file leduc_poker.cc.
{
  if (params.empty()) {
    return std::make_shared<LeducObserver>(
        iig_obs_type.value_or(kDefaultObsType));
  } else {
    return MakeRegisteredObserver(iig_obs_type, params);
  }
}
References open_spiel::kDefaultObsType, open_spiel::Game::MakeRegisteredObserver(), and absl::optional< T >::value_or().
MaxBetsPerRound()
int open_spiel::leduc_poker::LeducGame::MaxBetsPerRound () const inline constexpr
Definition at line 216 of file leduc_poker.h.
{
    // E.g. longest round for 4-player is 10 bets:
    //   check, check, check, bet, call, call, raise, call, call, call
    // = 1 bet + 1 raise + (num_players_-1)*2 calls + (num_players_-2) calls
    return 3 * num_players_ - 2;
  }
Referenced by MaxGameLength().
MaxChanceNodesInHistory()
int open_spiel::leduc_poker::LeducGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 226 of file leduc_poker.h.
{ return 3; }
MaxChanceOutcomes()
int open_spiel::leduc_poker::LeducGame::MaxChanceOutcomes () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 793 of file leduc_poker.cc.
{
  if (suit_isomorphism_) {
    return total_cards_ / 2;
  } else {
    return total_cards_;
  }
}
MaxGameLength()
int open_spiel::leduc_poker::LeducGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 222 of file leduc_poker.h.
{
    // 2 rounds.
    return 2 * MaxBetsPerRound();
  }
References MaxBetsPerRound().
Referenced by InformationStateTensorShape().
MaxUtility()
double open_spiel::leduc_poker::LeducGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 823 of file leduc_poker.cc.
{
  // In poker, the utility is defined as the money a player has at the end of
  // the game minus then money the player had before starting the game.
  // The most a player can win *per opponent* is the most each player can put
  // into the pot, which is the raise amounts on each round times the maximum
  // number raises, plus the original chip they put in to play.
  return (num_players_ - 1) * (kTotalRaisesPerRound * kFirstRaiseAmount +
                               kTotalRaisesPerRound * kSecondRaiseAmount + 1);
}
References open_spiel::leduc_poker::kFirstRaiseAmount, open_spiel::leduc_poker::kSecondRaiseAmount, and open_spiel::leduc_poker::kTotalRaisesPerRound.
MinUtility()
double open_spiel::leduc_poker::LeducGame::MinUtility () const override virtual
Implements open_spiel::Game.
Definition at line 833 of file leduc_poker.cc.
{
  // In poker, the utility is defined as the money a player has at the end of
  // the game minus then money the player had before starting the game.
  // The most any single player can lose is the maximum number of raises per
  // round times the amounts of each of the raises, plus the original chip
  // they put in to play.
  return -1 * (kTotalRaisesPerRound * kFirstRaiseAmount +
               kTotalRaisesPerRound * kSecondRaiseAmount + 1);
}
References open_spiel::leduc_poker::kFirstRaiseAmount, open_spiel::leduc_poker::kSecondRaiseAmount, and open_spiel::leduc_poker::kTotalRaisesPerRound.
NewInitialState()
std::unique_ptr< State > open_spiel::leduc_poker::LeducGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 787 of file leduc_poker.cc.
{
  return absl::make_unique<LeducState>(shared_from_this(),
                                       /*action_mapping=*/action_mapping_,
                                       /*suit_isomorphism=*/suit_isomorphism_);
}
NumDistinctActions()
int open_spiel::leduc_poker::LeducGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 207 of file leduc_poker.h.
{ return 3; }
NumObservableCards()
int open_spiel::leduc_poker::LeducGame::NumObservableCards () const inline
Definition at line 227 of file leduc_poker.h.
{
    return suit_isomorphism_ ? total_cards_ / 2 : total_cards_;
  }
NumPlayers()
int open_spiel::leduc_poker::LeducGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 210 of file leduc_poker.h.
{ return num_players_; }
ObservationTensorShape()
std::vector< int > open_spiel::leduc_poker::LeducGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 812 of file leduc_poker.cc.
{
  // One-hot encoding for player number (who is to play).
  // 2 slots of cards (total_cards_ bits each): private card, public card
  // Followed by the contribution of each player to the pot
  if (suit_isomorphism_) {
    return {(num_players_) + (total_cards_) + (num_players_)};
  } else {
    return {(num_players_) + (total_cards_ * 2) + (num_players_)};
  }
}
UtilitySum()
absl::optional< double > open_spiel::leduc_poker::LeducGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 213 of file leduc_poker.h.
{ return 0; }
Member Data Documentation
default_observer_
std::shared_ptr<LeducObserver> open_spiel::leduc_poker::LeducGame::default_observer_
Definition at line 238 of file leduc_poker.h.
Referenced by LeducGame().
info_state_observer_
std::shared_ptr<LeducObserver> open_spiel::leduc_poker::LeducGame::info_state_observer_
Definition at line 239 of file leduc_poker.h.
Referenced by LeducGame().
The documentation for this class was generated from the following files:
open_spiel/games/leduc_poker/leduc_poker.h
open_spiel/games/leduc_poker/leduc_poker.cc