open spiel: open_spiel::Game Class Reference
open_spiel::Game Class Reference abstract
#include <spiel.h>
Inherits std::enable_shared_from_this< Game >.
Inherited by open_spiel::PyGame, open_spiel::SimMoveGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::WrappedGame, open_spiel::amazons::AmazonsGame, open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::baseT::baseTGame, open_spiel::battleship::BattleshipGame, open_spiel::blackjack::BlackjackGame, open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::catch_::CatchGame, open_spiel::checkers::CheckersGame, open_spiel::chess::ChessGame, open_spiel::cliff_walking::CliffWalkingGame, open_spiel::clobber::ClobberGame, open_spiel::coin_game::CoinGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::connect_four::ConnectFourGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::crazy_eights::CrazyEightsGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::cursor_go::CursorGoGame, open_spiel::dark_chess::DarkChessGame, open_spiel::dark_hex::DarkHexGame, open_spiel::deep_sea::DeepSeaGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::go::GoGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::havannah::HavannahGame, open_spiel::hearts::HeartsGame, open_spiel::hex::HexGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::mancala::MancalaGame, open_spiel::morpion_solitaire::MorpionGame, open_spiel::negotiation::NegotiationGame, open_spiel::nim::NimGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::oh_hell::OhHellGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::othello::OthelloGame, open_spiel::oware::OwareGame, open_spiel::pentago::PentagoGame, open_spiel::phantom_go::PhantomGoGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::pig::PigGame, open_spiel::quoridor::QuoridorGame, open_spiel::rbc::RbcGame, open_spiel::sheriff::SheriffGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::stones_and_gems::StonesNGemsGame, open_spiel::tarok::TarokGame, open_spiel::tic_tac_toe::TicTacToeGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_bridge::TinyBridgePlayGame, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::twenty_forty_eight::TwentyFortyEightGame, open_spiel::twixt::TwixTGame, open_spiel::ultimate_tic_tac_toe::UltimateTTTGame, open_spiel::universal_poker::UniversalPokerGame, and open_spiel::y_game::YGame.
Public Member Functions
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual int NumDistinctActions () const =0
virtual std::unique_ptr< State > NewInitialState () const =0
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
virtual int NumPlayers () const =0
virtual double MinUtility () const =0
virtual double MaxUtility () const =0
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual std::vector< int > ObservationTensorShape () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxGameLength () const =0
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Protected Member Functions
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 746 of file spiel.h.
Constructor & Destructor Documentation
~Game()
virtual open_spiel::Game::~Game () virtual default
Game() [1/2]
open_spiel::Game::Game (const Game &) delete
Game() [2/2]
open_spiel::Game::Game (GameType game_type, GameParameters game_parameters) inline protected
Definition at line 980 of file spiel.h.
      : game_type_(game_type), game_parameters_(game_parameters) {}
Member Function Documentation
ABSL_GUARDED_BY()
GameParameters defaulted_parameters_ open_spiel::Game::ABSL_GUARDED_BY (mutex_defaulted_parameters_) mutable protected
ActionToString()
virtual std::string open_spiel::Game::ActionToString (Player player, Action action_id) const inline virtual
Reimplemented in open_spiel::bargaining::BargainingGame, open_spiel::battleship::BattleshipGame, open_spiel::blotto::BlottoGame, open_spiel::leduc_poker::LeducGame, open_spiel::matrix_game::MatrixGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::pathfinding::PathfindingGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::sheriff::SheriffGame, open_spiel::tensor_game::TensorGame, and open_spiel::tic_tac_toe::TicTacToeGame.
Definition at line 955 of file spiel.h.
{
    return absl::StrCat("Action(id=", action_id, ", player=", player, ")");
  }
References player, and absl::StrCat().
Referenced by open_spiel::colored_trails::ColoredTrailsState::DoApplyAction().
DeserializeState()
std::unique_ptr< State > open_spiel::Game::DeserializeState (const std::string & str) const virtual
Reimplemented in open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::chess::ChessGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::garnet::GarnetGame, open_spiel::negotiation::NegotiationGame, open_spiel::PyGame, open_spiel::spades::SpadesGame, open_spiel::stones_and_gems::StonesNGemsGame, and open_spiel::tarok::TarokGame.
Definition at line 409 of file spiel.cc.
{
  // This does not work for games with sampled chance nodes and for mean field
  //  games. See comments in State::Serialize() for the explanation. If you wish
  //  to serialize states in such games, you must implement custom serialization
  //  and deserialization for the state.
  SPIEL_CHECK_NE(game_type_.chance_mode,
                 GameType::ChanceMode::kSampledStochastic);
  SPIEL_CHECK_NE(game_type_.dynamics,
                 GameType::Dynamics::kMeanField);
  std::unique_ptr<State> state = NewInitialState();
  if (str.empty()) {
    return state;
  }
  std::vector<std::string> lines = absl::StrSplit(str, '\n');
  for (int i = 0; i < lines.size(); ++i) {
    if (lines[i].empty()) continue;
    if (state->IsSimultaneousNode()) {
      std::vector<Action> actions;
      for (int p = 0; p < state->NumPlayers(); ++p, ++i) {
        SPIEL_CHECK_LT(i, lines.size());
        Action action = static_cast<Action>(std::stol(lines[i]));
        actions.push_back(action);
      }
      state->ApplyActions(actions);
      // Must decrement i here, otherwise it is incremented too many times.
      --i;
    } else {
      Action action = static_cast<Action>(std::stol(lines[i]));
      state->ApplyAction(action);
    }
  }
  return state;
}
References action, open_spiel::GameType::chance_mode, open_spiel::GameType::dynamics, game_type_, i, open_spiel::GameType::kMeanField, open_spiel::GameType::kSampledStochastic, NewInitialState(), SPIEL_CHECK_LT, SPIEL_CHECK_NE, state, and absl::StrSplit().
Referenced by define_julia_module(), open_spiel::bridge::BridgeGame::DeserializeState(), open_spiel::chess::ChessGame::DeserializeState(), and open_spiel::spades::SpadesGame::DeserializeState().
GetParameters()
GameParameters open_spiel::Game::GetParameters () const inline
Definition at line 787 of file spiel.h.
{
    absl::MutexLock lock(&mutex_defaulted_parameters_);
    GameParameters params = game_parameters_;
    params.insert(defaulted_parameters_.begin(), defaulted_parameters_.end());
    return params;
  }
References game_parameters_, and mutex_defaulted_parameters_.
Referenced by define_julia_module(), operator==(), and open_spiel::EFGWriter::Write().
GetRNGState()
virtual std::string open_spiel::Game::GetRNGState () const inline virtual
Reimplemented in open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::negotiation::NegotiationGame, open_spiel::stones_and_gems::StonesNGemsGame, and open_spiel::tarok::TarokGame.
Definition at line 931 of file spiel.h.
{
    SpielFatalError("GetRNGState unimplemented.");
  }
References open_spiel::SpielFatalError().
Referenced by Serialize().
GetType()
const GameType & open_spiel::Game::GetType () const inline
Definition at line 809 of file spiel.h.
{ return game_type_; }
References game_type_.
Referenced by open_spiel::tensor_game::TensorGame::AsMatrixGame(), open_spiel::CreateRepeatedGame(), define_julia_module(), open_spiel::EFGWriter::EFGWriter(), open_spiel::algorithms::TabularBestResponseMDP::Exploitability(), MaxChanceNodesInHistory(), MaxHistoryLength(), NewInitialStates(), Serialize(), and open_spiel::algorithms::ortools::SolveZeroSumMatrixGame().
InformationStateTensorLayout()
virtual TensorLayout open_spiel::Game::InformationStateTensorLayout () const inline virtual
Reimplemented in open_spiel::WrappedGame.
Definition at line 823 of file spiel.h.
{
    return TensorLayout::kCHW;
  }
References open_spiel::kCHW.
InformationStateTensorShape()
virtual std::vector< int > open_spiel::Game::InformationStateTensorShape () const inline virtual
Reimplemented in open_spiel::bargaining::BargainingGame, open_spiel::baseT::baseTGame, open_spiel::battleship::BattleshipGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::cliff_walking::CliffWalkingGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::dark_hex::DarkHexGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hearts::HeartsGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::NormalFormGame, open_spiel::oh_hell::OhHellGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::PyGame, open_spiel::RepeatedGame, open_spiel::RestrictedNashResponseGame, open_spiel::sheriff::SheriffGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::universal_poker::UniversalPokerGame, and open_spiel::WrappedGame.
Definition at line 820 of file spiel.h.
{
    SpielFatalError("InformationStateTensorShape unimplemented.");
  }
References open_spiel::SpielFatalError().
Referenced by define_julia_module(), and InformationStateTensorSize().
InformationStateTensorSize()
int open_spiel::Game::InformationStateTensorSize () const inline
Definition at line 829 of file spiel.h.
{
    std::vector<int> shape = InformationStateTensorShape();
    return shape.empty() ? 0
                         : absl::c_accumulate(shape, 1, std::multiplies<int>());
  }
References absl::c_accumulate(), and InformationStateTensorShape().
Referenced by define_julia_module().
MakeBuiltInObserver()
std::shared_ptr< Observer > open_spiel::Game::MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
Definition at line 137 of file observer.cc.
{
  if (!iig_obs_type) {
    if (game_type_.provides_observation()) {
      return absl::make_unique<DefaultObserver>(*this);
    } else {
      return nullptr;
    }
  }
  const bool perfect_info_game =
      game_type_.information == GameType::Information::kPerfectInformation;
  // Perfect information games can provide public information regardless
  // of requested PrivateInfoType (as they have no private information).
  if (perfect_info_game) {
    // Handle the dummy case, where we do not use any public information.
    // The game will just have empty private observations.
    if (!iig_obs_type->public_info)
      return absl::make_unique<NoPrivateObserver>(*this);
    if (game_type_.provides_information_state() && iig_obs_type->perfect_recall)
      return absl::make_unique<InformationStateObserver>(*this);
    if (game_type_.provides_observation() && !iig_obs_type->perfect_recall)
      return absl::make_unique<DefaultObserver>(*this);
  }
  // TODO(author11) Reinstate this check
  // SPIEL_CHECK_EQ(GetType().information,
  //                GameType::Information::kImperfectInformation);
  if (iig_obs_type.value() == kDefaultObsType) {
    if (game_type_.provides_observation())
      return absl::make_unique<DefaultObserver>(*this);
  }
  if (iig_obs_type.value() == kInfoStateObsType) {
    if (game_type_.provides_information_state())
      return absl::make_unique<InformationStateObserver>(*this);
  }
  return nullptr;
}
References game_type_, open_spiel::GameType::information, open_spiel::kDefaultObsType, open_spiel::kInfoStateObsType, open_spiel::GameType::kPerfectInformation, open_spiel::GameType::provides_information_state(), open_spiel::GameType::provides_observation(), and absl::optional< T >::value().
Referenced by MakeObserver().
MakeObserver()
std::shared_ptr< Observer > open_spiel::Game::MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters & params) const virtual
Reimplemented in open_spiel::coordinated_mp::PenniesGame, open_spiel::dark_chess::DarkChessGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::goofspiel::GoofspielGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::leduc_poker::LeducGame, open_spiel::PyGame, open_spiel::rbc::RbcGame, and open_spiel::RestrictedNashResponseGame.
Definition at line 177 of file observer.cc.
{
  // This implementation falls back to the original information state and
  // observation methods in case of empty parameters and otherwise creates
  // a registered observer based on its name.
  // New games can register observers which can be selected by name, or override
  // MakeObserver to return a game-specific observer.
  if (params.empty()) {
    return MakeBuiltInObserver(iig_obs_type);
  } else {
    return MakeRegisteredObserver(iig_obs_type, params);
  }
}
References MakeBuiltInObserver(), and MakeRegisteredObserver().
MakeRegisteredObserver()
std::shared_ptr< Observer > open_spiel::Game::MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters & params) const
Definition at line 125 of file observer.cc.
{
  auto iter = params.find("name");
  if (iter == params.end()) {
    SpielFatalError("A 'name' parameter is expected to create a registered "
                    "observer");
  }
  auto name = iter->second.string_value();
  return ObserverRegisterer::CreateByName(name, *this, iig_obs_type, params);
}
References open_spiel::ObserverRegisterer::CreateByName(), name, and open_spiel::SpielFatalError().
Referenced by MakeObserver(), open_spiel::kuhn_poker::KuhnGame::MakeObserver(), open_spiel::leduc_poker::LeducGame::MakeObserver(), and open_spiel::RestrictedNashResponseGame::MakeObserver().
MaxChanceNodesInHistory()
virtual int open_spiel::Game::MaxChanceNodesInHistory () const inline virtual
Reimplemented in open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::catch_::CatchGame, open_spiel::coin_game::CoinGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::coop_box_pushing::CoopBoxPushingGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::hearts::HeartsGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::negotiation::NegotiationGame, open_spiel::NormalFormGame, open_spiel::oh_hell::OhHellGame, open_spiel::pathfinding::PathfindingGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::RestrictedNashResponseGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::universal_poker::UniversalPokerGame, and open_spiel::WrappedGame.
Definition at line 882 of file spiel.h.
{
    if (GetType().chance_mode == GameType::ChanceMode::kDeterministic) {
      return 0;
    }
    SpielFatalError("MaxChanceNodesInHistory() is not implemented");
  }
References GetType(), open_spiel::GameType::kDeterministic, and open_spiel::SpielFatalError().
Referenced by MaxHistoryLength(), and MaxMoveNumber().
MaxChanceOutcomes()
virtual int open_spiel::Game::MaxChanceOutcomes () const inline virtual
Reimplemented in open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::baseT::baseTGame, open_spiel::battleship::BattleshipGame, open_spiel::blackjack::BlackjackGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::catch_::CatchGame, open_spiel::coin_game::CoinGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::coop_box_pushing::CoopBoxPushingGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::crazy_eights::CrazyEightsGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::deep_sea::DeepSeaGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::hearts::HeartsGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::negotiation::NegotiationGame, open_spiel::oh_hell::OhHellGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::pathfinding::PathfindingGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::RestrictedNashResponseGame, open_spiel::sheriff::SheriffGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::stones_and_gems::StonesNGemsGame, open_spiel::tarok::TarokGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::twenty_forty_eight::TwentyFortyEightGame, open_spiel::universal_poker::UniversalPokerGame, and open_spiel::WrappedGame.
Definition at line 782 of file spiel.h.
{ return 0; }
Referenced by define_julia_module().
MaxGameLength()
virtual int open_spiel::Game::MaxGameLength () const pure virtual
Implemented in open_spiel::amazons::AmazonsGame, open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::baseT::baseTGame, open_spiel::battleship::BattleshipGame, open_spiel::blackjack::BlackjackGame, open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::catch_::CatchGame, open_spiel::checkers::CheckersGame, open_spiel::chess::ChessGame, open_spiel::cliff_walking::CliffWalkingGame, open_spiel::clobber::ClobberGame, open_spiel::coin_game::CoinGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::connect_four::ConnectFourGame, open_spiel::coop_box_pushing::CoopBoxPushingGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::crazy_eights::CrazyEightsGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::cursor_go::CursorGoGame, open_spiel::dark_chess::DarkChessGame, open_spiel::dark_hex::DarkHexGame, open_spiel::deep_sea::DeepSeaGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::go::GoGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::havannah::HavannahGame, open_spiel::hearts::HeartsGame, open_spiel::hex::HexGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::mancala::MancalaGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::morpion_solitaire::MorpionGame, open_spiel::negotiation::NegotiationGame, open_spiel::nim::NimGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::NormalFormGame, open_spiel::oh_hell::OhHellGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::othello::OthelloGame, open_spiel::oware::OwareGame, open_spiel::pathfinding::PathfindingGame, open_spiel::pentago::PentagoGame, open_spiel::phantom_go::PhantomGoGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::quoridor::QuoridorGame, open_spiel::rbc::RbcGame, open_spiel::RepeatedGame, open_spiel::RestrictedNashResponseGame, open_spiel::sheriff::SheriffGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::stones_and_gems::StonesNGemsGame, open_spiel::tarok::TarokGame, open_spiel::tic_tac_toe::TicTacToeGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_bridge::TinyBridgePlayGame, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::twenty_forty_eight::TwentyFortyEightGame, open_spiel::twixt::TwixTGame, open_spiel::ultimate_tic_tac_toe::UltimateTTTGame, open_spiel::universal_poker::UniversalPokerGame, open_spiel::WrappedGame, and open_spiel::y_game::YGame.
Referenced by open_spiel::CreateRepeatedGame(), define_julia_module(), MaxHistoryLength(), and MaxMoveNumber().
MaxHistoryLength()
virtual int open_spiel::Game::MaxHistoryLength () const inline virtual
Reimplemented in open_spiel::efg_game::EFGGame.
Definition at line 897 of file spiel.h.
{
    if (GetType().dynamics == GameType::Dynamics::kSimultaneous) {
      // The history of simultaneous move games is flattened, so count number
      // of actions of each player.
      return MaxGameLength() * NumPlayers() + MaxChanceNodesInHistory();
    }
    if (GetType().dynamics == GameType::Dynamics::kSequential) {
      return MaxGameLength() + MaxChanceNodesInHistory();
    }
    SpielFatalError("Unknown game dynamics.");
  }
References GetType(), open_spiel::GameType::kSequential, open_spiel::GameType::kSimultaneous, MaxChanceNodesInHistory(), MaxGameLength(), NumPlayers(), and open_spiel::SpielFatalError().
MaxMoveNumber()
virtual int open_spiel::Game::MaxMoveNumber () const inline virtual
Reimplemented in open_spiel::efg_game::EFGGame.
Definition at line 891 of file spiel.h.
{
    return MaxGameLength() + MaxChanceNodesInHistory();
  }
References MaxChanceNodesInHistory(), and MaxGameLength().
MaxUtility()
virtual double open_spiel::Game::MaxUtility () const pure virtual
Implemented in open_spiel::add_noise::AddNoiseGame, open_spiel::amazons::AmazonsGame, open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::baseT::baseTGame, open_spiel::battleship::BattleshipGame, open_spiel::blackjack::BlackjackGame, open_spiel::blotto::BlottoGame, open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::catch_::CatchGame, open_spiel::checkers::CheckersGame, open_spiel::chess::ChessGame, open_spiel::cliff_walking::CliffWalkingGame, open_spiel::clobber::ClobberGame, open_spiel::coin_game::CoinGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::connect_four::ConnectFourGame, open_spiel::coop_box_pushing::CoopBoxPushingGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::crazy_eights::CrazyEightsGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::cursor_go::CursorGoGame, open_spiel::dark_chess::DarkChessGame, open_spiel::dark_hex::DarkHexGame, open_spiel::deep_sea::DeepSeaGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::go::GoGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::havannah::HavannahGame, open_spiel::hearts::HeartsGame, open_spiel::hex::HexGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::mancala::MancalaGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::matching_pennies_3p::MatchingPennies3pGame, open_spiel::matrix_game::MatrixGame, open_spiel::MisereGame, open_spiel::morpion_solitaire::MorpionGame, open_spiel::negotiation::NegotiationGame, open_spiel::nim::NimGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::oh_hell::OhHellGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::othello::OthelloGame, open_spiel::oware::OwareGame, open_spiel::pathfinding::PathfindingGame, open_spiel::pentago::PentagoGame, open_spiel::phantom_go::PhantomGoGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::quoridor::QuoridorGame, open_spiel::rbc::RbcGame, open_spiel::RepeatedGame, open_spiel::RestrictedNashResponseGame, open_spiel::sheriff::SheriffGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::stones_and_gems::StonesNGemsGame, open_spiel::tarok::TarokGame, open_spiel::tensor_game::TensorGame, open_spiel::tic_tac_toe::TicTacToeGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_bridge::TinyBridgePlayGame, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::twenty_forty_eight::TwentyFortyEightGame, open_spiel::twixt::TwixTGame, open_spiel::ultimate_tic_tac_toe::UltimateTTTGame, open_spiel::universal_poker::UniversalPokerGame, open_spiel::WrappedGame, open_spiel::y_game::YGame, and open_spiel::ZeroSumGame.
Referenced by define_julia_module().
MinUtility()
virtual double open_spiel::Game::MinUtility () const pure virtual
Implemented in open_spiel::add_noise::AddNoiseGame, open_spiel::amazons::AmazonsGame, open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::baseT::baseTGame, open_spiel::battleship::BattleshipGame, open_spiel::blackjack::BlackjackGame, open_spiel::blotto::BlottoGame, open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::catch_::CatchGame, open_spiel::checkers::CheckersGame, open_spiel::chess::ChessGame, open_spiel::cliff_walking::CliffWalkingGame, open_spiel::clobber::ClobberGame, open_spiel::coin_game::CoinGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::connect_four::ConnectFourGame, open_spiel::coop_box_pushing::CoopBoxPushingGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::crazy_eights::CrazyEightsGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::cursor_go::CursorGoGame, open_spiel::dark_chess::DarkChessGame, open_spiel::dark_hex::DarkHexGame, open_spiel::deep_sea::DeepSeaGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::go::GoGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::havannah::HavannahGame, open_spiel::hearts::HeartsGame, open_spiel::hex::HexGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::mancala::MancalaGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::matching_pennies_3p::MatchingPennies3pGame, open_spiel::matrix_game::MatrixGame, open_spiel::MisereGame, open_spiel::morpion_solitaire::MorpionGame, open_spiel::negotiation::NegotiationGame, open_spiel::nim::NimGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::oh_hell::OhHellGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::othello::OthelloGame, open_spiel::oware::OwareGame, open_spiel::pathfinding::PathfindingGame, open_spiel::pentago::PentagoGame, open_spiel::phantom_go::PhantomGoGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::quoridor::QuoridorGame, open_spiel::rbc::RbcGame, open_spiel::RepeatedGame, open_spiel::RestrictedNashResponseGame, open_spiel::sheriff::SheriffGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::stones_and_gems::StonesNGemsGame, open_spiel::tarok::TarokGame, open_spiel::tensor_game::TensorGame, open_spiel::tic_tac_toe::TicTacToeGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_bridge::TinyBridgePlayGame, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::twenty_forty_eight::TwentyFortyEightGame, open_spiel::twixt::TwixTGame, open_spiel::ultimate_tic_tac_toe::UltimateTTTGame, open_spiel::universal_poker::UniversalPokerGame, open_spiel::WrappedGame, open_spiel::y_game::YGame, and open_spiel::ZeroSumGame.
Referenced by define_julia_module().
NewInitialState() [1/2]
virtual std::unique_ptr< State > open_spiel::Game::NewInitialState () const pure virtual
Implemented in open_spiel::add_noise::AddNoiseGame, open_spiel::algorithms::AFCCEGame, open_spiel::algorithms::AFCEGame, open_spiel::algorithms::CCEGame, open_spiel::algorithms::CEGame, open_spiel::algorithms::EFCCEGame, open_spiel::algorithms::EFCEGame, open_spiel::amazons::AmazonsGame, open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::baseT::baseTGame, open_spiel::battleship::BattleshipGame, open_spiel::blackjack::BlackjackGame, open_spiel::blotto::BlottoGame, open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::catch_::CatchGame, open_spiel::checkers::CheckersGame, open_spiel::chess::ChessGame, open_spiel::cliff_walking::CliffWalkingGame, open_spiel::clobber::ClobberGame, open_spiel::coin_game::CoinGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::connect_four::ConnectFourGame, open_spiel::coop_box_pushing::CoopBoxPushingGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::crazy_eights::CrazyEightsGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::cursor_go::CursorGoGame, open_spiel::dark_chess::DarkChessGame, open_spiel::dark_hex::DarkHexGame, open_spiel::dark_hex::ImperfectRecallDarkHexGame, open_spiel::deep_sea::DeepSeaGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::go::GoGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::havannah::HavannahGame, open_spiel::hearts::HeartsGame, open_spiel::hex::HexGame, open_spiel::kbg::kbgGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::ImperfectRecallLiarsDiceGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::mancala::MancalaGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::matching_pennies_3p::MatchingPennies3pGame, open_spiel::matrix_game::MatrixGame, open_spiel::MisereGame, open_spiel::morpion_solitaire::MorpionGame, open_spiel::negotiation::NegotiationGame, open_spiel::nim::NimGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::oh_hell::OhHellGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::othello::OthelloGame, open_spiel::oware::OwareGame, open_spiel::pathfinding::PathfindingGame, open_spiel::pentago::PentagoGame, open_spiel::phantom_go::PhantomGoGame, open_spiel::phantom_ttt::ImperfectRecallPTTTGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::quoridor::QuoridorGame, open_spiel::rbc::RbcGame, open_spiel::RepeatedGame, open_spiel::RestrictedNashResponseGame, open_spiel::sheriff::SheriffGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::StartAtTransformationGame, open_spiel::stones_and_gems::StonesNGemsGame, open_spiel::tarok::TarokGame, open_spiel::tensor_game::TensorGame, open_spiel::tic_tac_toe::TicTacToeGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_bridge::TinyBridgePlayGame, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::twenty_forty_eight::TwentyFortyEightGame, open_spiel::twixt::TwixTGame, open_spiel::ultimate_tic_tac_toe::UltimateTTTGame, open_spiel::universal_poker::UniversalPokerGame, open_spiel::WrappedGame, open_spiel::y_game::YGame, and open_spiel::ZeroSumGame.
Referenced by open_spiel::algorithms::TabularBestResponseMDP::ComputeBestResponse(), open_spiel::algorithms::TabularBestResponseMDP::ComputeBestResponses(), DeserializeState(), open_spiel::NormalFormGame::GetUtilities(), open_spiel::algorithms::TabularBestResponseMDP::NashConv(), NewInitialStates(), and open_spiel::EFGWriter::Write().
NewInitialState() [2/2]
virtual std::unique_ptr< State > open_spiel::Game::NewInitialState (const std::string & str) const inline virtual
Reimplemented in open_spiel::chess::ChessGame, open_spiel::clobber::ClobberGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, and open_spiel::rbc::RbcGame.
Definition at line 769 of file spiel.h.
{
    SpielFatalError("NewInitialState from string is not implemented.");
  }
References open_spiel::SpielFatalError().
NewInitialStateForPopulation()
virtual std::unique_ptr< State > open_spiel::Game::NewInitialStateForPopulation (int population) const inline virtual
Reimplemented in open_spiel::PyGame.
Definition at line 974 of file spiel.h.
{
    SpielFatalError("NewInitialStateForPopulation is not implemented.");
  }
References open_spiel::SpielFatalError().
Referenced by NewInitialStates().
NewInitialStates()
std::vector< std::unique_ptr< State > > open_spiel::Game::NewInitialStates () const virtual
Definition at line 395 of file spiel.cc.
{
  std::vector<std::unique_ptr<State>> states;
  if (GetType().dynamics == GameType::Dynamics::kMeanField &&
      NumPlayers() >= 2) {
    states.reserve(NumPlayers());
    for (int p = 0; p < NumPlayers(); ++p) {
      states.push_back(NewInitialStateForPopulation(p));
    }
    return states;
  }
  states.push_back(NewInitialState());
  return states;
}
References GetType(), open_spiel::GameType::kMeanField, NewInitialState(), NewInitialStateForPopulation(), and NumPlayers().
NumDistinctActions()
virtual int open_spiel::Game::NumDistinctActions () const pure virtual
Implemented in open_spiel::algorithms::AFCCEGame, open_spiel::algorithms::CCEGame, open_spiel::algorithms::CEGame, open_spiel::algorithms::EFCCEGame, open_spiel::amazons::AmazonsGame, open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::baseT::baseTGame, open_spiel::battleship::BattleshipGame, open_spiel::blackjack::BlackjackGame, open_spiel::blotto::BlottoGame, open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::catch_::CatchGame, open_spiel::checkers::CheckersGame, open_spiel::chess::ChessGame, open_spiel::cliff_walking::CliffWalkingGame, open_spiel::clobber::ClobberGame, open_spiel::coin_game::CoinGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::connect_four::ConnectFourGame, open_spiel::coop_box_pushing::CoopBoxPushingGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::crazy_eights::CrazyEightsGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::cursor_go::CursorGoGame, open_spiel::dark_chess::DarkChessGame, open_spiel::dark_hex::DarkHexGame, open_spiel::deep_sea::DeepSeaGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::go::GoGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::havannah::HavannahGame, open_spiel::hearts::HeartsGame, open_spiel::hex::HexGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::mancala::MancalaGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::matching_pennies_3p::MatchingPennies3pGame, open_spiel::matrix_game::MatrixGame, open_spiel::morpion_solitaire::MorpionGame, open_spiel::negotiation::NegotiationGame, open_spiel::nim::NimGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::oh_hell::OhHellGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::othello::OthelloGame, open_spiel::oware::OwareGame, open_spiel::pathfinding::PathfindingGame, open_spiel::pentago::PentagoGame, open_spiel::phantom_go::PhantomGoGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::quoridor::QuoridorGame, open_spiel::rbc::RbcGame, open_spiel::RepeatedGame, open_spiel::RestrictedNashResponseGame, open_spiel::sheriff::SheriffGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::stones_and_gems::StonesNGemsGame, open_spiel::tarok::TarokGame, open_spiel::tensor_game::TensorGame, open_spiel::tic_tac_toe::TicTacToeGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_bridge::TinyBridgePlayGame, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::twenty_forty_eight::TwentyFortyEightGame, open_spiel::twixt::TwixTGame, open_spiel::ultimate_tic_tac_toe::UltimateTTTGame, open_spiel::universal_poker::UniversalPokerGame, open_spiel::WrappedGame, and open_spiel::y_game::YGame.
Referenced by define_julia_module(), and PolicyTensorShape().
NumPlayers()
virtual int open_spiel::Game::NumPlayers () const pure virtual
Implemented in open_spiel::amazons::AmazonsGame, open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::battleship::BattleshipGame, open_spiel::blackjack::BlackjackGame, open_spiel::blotto::BlottoGame, open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::catch_::CatchGame, open_spiel::checkers::CheckersGame, open_spiel::chess::ChessGame, open_spiel::cliff_walking::CliffWalkingGame, open_spiel::clobber::ClobberGame, open_spiel::coin_game::CoinGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::connect_four::ConnectFourGame, open_spiel::coop_box_pushing::CoopBoxPushingGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::crazy_eights::CrazyEightsGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::cursor_go::CursorGoGame, open_spiel::dark_chess::DarkChessGame, open_spiel::dark_hex::DarkHexGame, open_spiel::deep_sea::DeepSeaGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::go::GoGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::havannah::HavannahGame, open_spiel::hearts::HeartsGame, open_spiel::hex::HexGame, open_spiel::kbg::kbgGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::mancala::MancalaGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::matching_pennies_3p::MatchingPennies3pGame, open_spiel::matrix_game::MatrixGame, open_spiel::morpion_solitaire::MorpionGame, open_spiel::negotiation::NegotiationGame, open_spiel::nim::NimGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::oh_hell::OhHellGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::othello::OthelloGame, open_spiel::oware::OwareGame, open_spiel::pathfinding::PathfindingGame, open_spiel::pentago::PentagoGame, open_spiel::phantom_go::PhantomGoGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::quoridor::QuoridorGame, open_spiel::rbc::RbcGame, open_spiel::RepeatedGame, open_spiel::RestrictedNashResponseGame, open_spiel::sheriff::SheriffGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::stones_and_gems::StonesNGemsGame, open_spiel::tarok::TarokGame, open_spiel::tensor_game::TensorGame, open_spiel::tic_tac_toe::TicTacToeGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_bridge::TinyBridgePlayGame, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::twenty_forty_eight::TwentyFortyEightGame, open_spiel::twixt::TwixTGame, open_spiel::ultimate_tic_tac_toe::UltimateTTTGame, open_spiel::universal_poker::UniversalPokerGame, open_spiel::WrappedGame, and open_spiel::y_game::YGame.
Referenced by define_julia_module(), open_spiel::algorithms::LoadMatrixGame(), MaxHistoryLength(), NewInitialStates(), open_spiel::NormalFormGame::UtilitySum(), and open_spiel::EFGWriter::Write().
ObservationTensorLayout()
virtual TensorLayout open_spiel::Game::ObservationTensorLayout () const inline virtual
Reimplemented in open_spiel::go::GoGame, open_spiel::phantom_go::PhantomGoGame, and open_spiel::WrappedGame.
Definition at line 843 of file spiel.h.
{
    return TensorLayout::kCHW;
  }
References open_spiel::kCHW.
ObservationTensorShape()
virtual std::vector< int > open_spiel::Game::ObservationTensorShape () const inline virtual
Reimplemented in open_spiel::amazons::AmazonsGame, open_spiel::backgammon::BackgammonGame, open_spiel::bargaining::BargainingGame, open_spiel::baseT::baseTGame, open_spiel::blackjack::BlackjackGame, open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::catch_::CatchGame, open_spiel::checkers::CheckersGame, open_spiel::chess::ChessGame, open_spiel::cliff_walking::CliffWalkingGame, open_spiel::clobber::ClobberGame, open_spiel::colored_trails::ColoredTrailsGame, open_spiel::connect_four::ConnectFourGame, open_spiel::coop_box_pushing::CoopBoxPushingGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::crazy_eights::CrazyEightsGame, open_spiel::crowd_modelling::CrowdModellingGame, open_spiel::crowd_modelling_2d::CrowdModelling2dGame, open_spiel::cursor_go::CursorGoGame, open_spiel::dark_chess::DarkChessGame, open_spiel::dark_hex::DarkHexGame, open_spiel::deep_sea::DeepSeaGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::dynamic_routing::MeanFieldRoutingGame, open_spiel::first_sealed_auction::FPSBAGame, open_spiel::garnet::GarnetGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::go::GoGame, open_spiel::goofspiel::GoofspielGame, open_spiel::hanabi::OpenSpielHanabiGame, open_spiel::havannah::HavannahGame, open_spiel::hex::HexGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::lewis_signaling::LewisSignalingGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::mancala::MancalaGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::negotiation::NegotiationGame, open_spiel::nim::NimGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::NormalFormGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::othello::OthelloGame, open_spiel::oware::OwareGame, open_spiel::pathfinding::PathfindingGame, open_spiel::pentago::PentagoGame, open_spiel::phantom_go::PhantomGoGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::quoridor::QuoridorGame, open_spiel::rbc::RbcGame, open_spiel::RepeatedGame, open_spiel::RestrictedNashResponseGame, open_spiel::skat::SkatGame, open_spiel::solitaire::SolitaireGame, open_spiel::spades::SpadesGame, open_spiel::stones_and_gems::StonesNGemsGame, open_spiel::tic_tac_toe::TicTacToeGame, open_spiel::tiny_bridge::TinyBridgeGame2p, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::tiny_hanabi::TinyHanabiGame, open_spiel::trade_comm::TradeCommGame, open_spiel::TurnBasedSimultaneousGame, open_spiel::twenty_forty_eight::TwentyFortyEightGame, open_spiel::twixt::TwixTGame, open_spiel::ultimate_tic_tac_toe::UltimateTTTGame, open_spiel::universal_poker::UniversalPokerGame, open_spiel::WrappedGame, and open_spiel::y_game::YGame.
Definition at line 840 of file spiel.h.
{
    SpielFatalError("ObservationTensorShape unimplemented.");
  }
References open_spiel::SpielFatalError().
Referenced by define_julia_module(), and ObservationTensorSize().
ObservationTensorSize()
int open_spiel::Game::ObservationTensorSize () const inline
Definition at line 849 of file spiel.h.
{
    std::vector<int> shape = ObservationTensorShape();
    return shape.empty() ? 0
                         : absl::c_accumulate(shape, 1, std::multiplies<int>());
  }
References absl::c_accumulate(), and ObservationTensorShape().
Referenced by define_julia_module(), and open_spiel::negotiation::NegotiationState::ObservationTensor().
operator=()
Game & open_spiel::Game::operator= (const Game &) delete
operator==()
virtual bool open_spiel::Game::operator== (const Game & other) const inline virtual
Reimplemented in open_spiel::matrix_game::MatrixGame, and open_spiel::tensor_game::TensorGame.
Definition at line 919 of file spiel.h.
{
    // GetParameters() includes default values. So comparing GetParameters
    // instead of game_parameters_ makes sure that game equality is independent
    // of the presence of explicitly passed game parameters with default values.
    return game_type_.short_name == other.game_type_.short_name &&
           GetParameters() == other.GetParameters();
  }
References game_type_, GetParameters(), and open_spiel::GameType::short_name.
ParameterValue()
template<typename T > T open_spiel::Game::ParameterValue (const std::string & key, absl::optional< T > default_value = absl::nullopt) const inline protected
Definition at line 988 of file spiel.h.
{
    // Return the value if found.
    auto iter = game_parameters_.find(key);
    if (iter != game_parameters_.end()) {
      return iter->second.value<T>();
    }
    // Pick the defaulted value.
    GameParameter default_game_parameter;
    if (default_value.has_value()) {
      default_game_parameter = GameParameter(default_value.value());
    } else {
      auto default_iter = game_type_.parameter_specification.find(key);
      if (default_iter == game_type_.parameter_specification.end()) {
        SpielFatalError(absl::StrCat("The parameter for ", key,
                                     " is missing in game ", ToString()));
      }
      default_game_parameter = default_iter->second;
    }
    // Return the default value, storing it.
    absl::MutexLock lock(&mutex_defaulted_parameters_);
    iter = defaulted_parameters_.find(key);
    if (iter == defaulted_parameters_.end()) {
      // We haven't previously defaulted this value, so store the default we
      // used.
      defaulted_parameters_[key] = default_game_parameter;
    } else {
      // Already defaulted, so check we are being consistent.
      // Using different default values at different times means the game isn't
      // well-defined.
      if (default_game_parameter != iter->second) {
        SpielFatalError(absl::StrCat("Parameter ", key, " is defaulted to ",
                                     default_game_parameter.ToReprString(),
                                     " having previously been defaulted to ",
                                     iter->second.ToReprString(), " in game ",
                                     ToString()));
      }
    }
    return default_game_parameter.value<T>();
  }
References game_parameters_, game_type_, key, mutex_defaulted_parameters_, open_spiel::GameType::parameter_specification, open_spiel::SpielFatalError(), absl::StrCat(), open_spiel::GameParameter::ToReprString(), ToString(), and open_spiel::GameParameter::value().
Referenced by open_spiel::bargaining::BargainingGame::BargainingGame(), open_spiel::battleship::BattleshipGame::BattleshipGame(), open_spiel::colored_trails::ColoredTrailsGame::ColoredTrailsGame(), open_spiel::dark_hex::DarkHexGame::DarkHexGame(), open_spiel::deep_sea::DeepSeaGame::DeepSeaGame(), open_spiel::lewis_signaling::LewisSignalingGame::LewisSignalingGame(), open_spiel::liars_dice::LiarsDiceGame::LiarsDiceGame(), open_spiel::dynamic_routing::MeanFieldRoutingGame::MeanFieldRoutingGame(), open_spiel::markov_soccer::MarkovSoccerGame::NewInitialState(), open_spiel::tiny_bridge::TinyBridgePlayGame::NewInitialState(), open_spiel::crowd_modelling_2d::CrowdModelling2dGame::ObservationTensorShape(), open_spiel::universal_poker::UniversalPokerGame::parseParameters(), open_spiel::phantom_ttt::PhantomTTTGame::PhantomTTTGame(), open_spiel::sheriff::SheriffGame::SheriffGame(), open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame::UncontestedBiddingGame(), and open_spiel::universal_poker::UniversalPokerGame::UniversalPokerGame().
PolicyTensorShape()
virtual std::vector< int > open_spiel::Game::PolicyTensorShape () const inline virtual
Reimplemented in open_spiel::WrappedGame.
Definition at line 859 of file spiel.h.
{
    return {NumDistinctActions()};
  }
References NumDistinctActions().
Serialize()
std::string open_spiel::Game::Serialize () const
Definition at line 655 of file spiel.cc.
{
  std::string str = ToString();
  if (GetType().chance_mode == GameType::ChanceMode::kSampledStochastic) {
    absl::StrAppend(&str, "\n", kSerializeGameRNGStateSectionHeader, "\n",
                    GetRNGState());
  }
  return str;
}
References GetRNGState(), GetType(), open_spiel::GameType::kSampledStochastic, absl::StrAppend(), and ToString().
SetRNGState()
virtual void open_spiel::Game::SetRNGState (const std::string & rng_state) const inline virtual
Reimplemented in open_spiel::bridge_uncontested_bidding::UncontestedBiddingGame, open_spiel::negotiation::NegotiationGame, open_spiel::stones_and_gems::StonesNGemsGame, and open_spiel::tarok::TarokGame.
Definition at line 937 of file spiel.h.
{
    SpielFatalError("SetRNGState unimplemented.");
  }
References open_spiel::SpielFatalError().
ToString()
std::string open_spiel::Game::ToString () const
Definition at line 664 of file spiel.cc.
{
  GameParameters params = game_parameters_;
  params["name"] = GameParameter(game_type_.short_name);
  return GameParametersToString(params);
}
References game_parameters_, game_type_, open_spiel::GameParametersToString(), and open_spiel::GameType::short_name.
Referenced by define_julia_module(), ParameterValue(), Serialize(), and open_spiel::EFGWriter::Write().
UtilitySum()
virtual absl::optional< double > open_spiel::Game::UtilitySum () const inline virtual
Reimplemented in open_spiel::amazons::AmazonsGame, open_spiel::backgammon::BackgammonGame, open_spiel::baseT::baseTGame, open_spiel::battleship::BattleshipGame, open_spiel::blotto::BlottoGame, open_spiel::breakthrough::BreakthroughGame, open_spiel::bridge::BridgeGame, open_spiel::checkers::CheckersGame, open_spiel::chess::ChessGame, open_spiel::clobber::ClobberGame, open_spiel::connect_four::ConnectFourGame, open_spiel::coop_to_1p::CoopTo1pGame, open_spiel::coordinated_mp::PenniesGame, open_spiel::cursor_go::CursorGoGame, open_spiel::dark_chess::DarkChessGame, open_spiel::dark_hex::DarkHexGame, open_spiel::dots_and_boxes::DotsAndBoxesGame, open_spiel::dou_dizhu::DouDizhuGame, open_spiel::efg_game::EFGGame, open_spiel::euchre::EuchreGame, open_spiel::gin_rummy::GinRummyGame, open_spiel::go::GoGame, open_spiel::goofspiel::GoofspielGame, open_spiel::havannah::HavannahGame, open_spiel::hex::HexGame, open_spiel::kriegspiel::KriegspielGame, open_spiel::kuhn_poker::KuhnGame, open_spiel::laser_tag::LaserTagGame, open_spiel::leduc_poker::LeducGame, open_spiel::liars_dice::LiarsDiceGame, open_spiel::maedn::MaednGame, open_spiel::mancala::MancalaGame, open_spiel::markov_soccer::MarkovSoccerGame, open_spiel::matrix_game::MatrixGame, open_spiel::MisereGame, open_spiel::nim::NimGame, open_spiel::nine_mens_morris::NineMensMorrisGame, open_spiel::NormalFormGame, open_spiel::oshi_zumo::OshiZumoGame, open_spiel::othello::OthelloGame, open_spiel::oware::OwareGame, open_spiel::pentago::PentagoGame, open_spiel::phantom_go::PhantomGoGame, open_spiel::phantom_ttt::PhantomTTTGame, open_spiel::pig::PigGame, open_spiel::PyGame, open_spiel::quoridor::QuoridorGame, open_spiel::rbc::RbcGame, open_spiel::RepeatedGame, open_spiel::RestrictedNashResponseGame, open_spiel::skat::SkatGame, open_spiel::tic_tac_toe::TicTacToeGame, open_spiel::tiny_bridge::TinyBridgeGame4p, open_spiel::TurnBasedSimultaneousGame, open_spiel::twixt::TwixTGame, open_spiel::ultimate_tic_tac_toe::UltimateTTTGame, open_spiel::universal_poker::UniversalPokerGame, open_spiel::WrappedGame, open_spiel::y_game::YGame, and open_spiel::ZeroSumGame.
Definition at line 813 of file spiel.h.
{ return absl::nullopt; }
Referenced by open_spiel::algorithms::TabularBestResponseMDP::Exploitability().
Member Data Documentation
game_parameters_
GameParameters open_spiel::Game::game_parameters_ protected
Definition at line 1035 of file spiel.h.
Referenced by GetParameters(), open_spiel::liars_dice::LiarsDiceGame::LiarsDiceGame(), ParameterValue(), and ToString().
game_type_
GameType open_spiel::Game::game_type_ protected
Definition at line 1032 of file spiel.h.
Referenced by open_spiel::battleship::BattleshipGame::BattleshipGame(), DeserializeState(), GetType(), open_spiel::goofspiel::GoofspielGame::GoofspielGame(), MakeBuiltInObserver(), operator==(), ParameterValue(), ToString(), and open_spiel::NormalFormGame::UtilitySum().
mutex_defaulted_parameters_
absl::Mutex open_spiel::Game::mutex_defaulted_parameters_ mutable protected
Definition at line 1041 of file spiel.h.
Referenced by GetParameters(), and ParameterValue().
The documentation for this class was generated from the following files:
open_spiel/spiel.h
open_spiel/observer.cc
open_spiel/spiel.cc