open spiel: TransTableL Class Reference
TransTableL Class Reference
#include <TransTableL.h>
Public Member Functions
TransTableL ()
~TransTableL ()
void Init (const int handLookup[][15])
void SetMemoryDefault (const int megabytes)
void SetMemoryMaximum (const int megabytes)
void MakeTT ()
void ResetMemory (const TTresetReason reason)
void ReturnAllMemory ()
double MemoryInUse () const
nodeCardsType * Lookup (const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[], const int limit, bool &lowerFlag)
void Add (const int trick, const int hand, const unsigned short aggrTarget[], const unsigned short winRanksArg[], const nodeCardsType &first, const bool flag)
void PrintSuits (ofstream &fout, const int trick, const int hand) const
void PrintAllSuits (ofstream &fout) const
void PrintSuitStats (ofstream &fout, const int trick, const int hand) const
void PrintAllSuitStats (ofstream &fout) const
void PrintSummarySuitStats (ofstream &fout) const
void PrintEntriesDist (ofstream &fout, const int trick, const int hand, const int handDist[]) const
void PrintEntriesDistAndCards (ofstream &fout, const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[]) const
void PrintEntries (ofstream &fout, const int trick, const int hand) const
void PrintAllEntries (ofstream &fout) const
void PrintEntryStats (ofstream &fout, const int trick, const int hand) const
void PrintAllEntryStats (ofstream &fout) const
void PrintSummaryEntryStats (ofstream &fout) const
Public Member Functions inherited from TransTable
TransTable ()
virtual ~TransTable ()
virtual void PrintPageSummary (ofstream &fout) const
virtual void PrintNodeStats (ofstream &fout) const
virtual void PrintResetStats (ofstream &fout) const
Detailed Description
Definition at line 46 of file TransTableL.h.
Constructor & Destructor Documentation
TransTableL()
TransTableL::TransTableL ()
Definition at line 103 of file TransTableL.cpp.
{
  if (! _constantsSet)
  {
    _constantsSet = true;
    TransTableL::SetConstants();
  }
  poolp = nullptr;
  pagesDefault = NUM_PAGES_DEFAULT;
  pagesMaximum = NUM_PAGES_MAXIMUM;
  pagesCurrent = 0;
  memState = FROM_POOL;
  harvestTrick = FIRST_HARVEST_TRICK;
  harvestHand = 0;
  harvested.nextBlockNo = 0;
  timestamp = 0;
  pageStats.numResets = 0;
  pageStats.numCallocs = 0;
  pageStats.numFrees = 0;
  pageStats.numHarvests = 0;
  pageStats.lastCurrent = 0;
  TTInUse = 0;
}
References FIRST_HARVEST_TRICK, NUM_PAGES_DEFAULT, and NUM_PAGES_MAXIMUM.
~TransTableL()
TransTableL::~TransTableL ()
Definition at line 134 of file TransTableL.cpp.
{
  TransTableL::ReturnAllMemory();
}
References ReturnAllMemory().
Member Function Documentation
Add()
void TransTableL::Add (const int trick, const int hand, const unsigned short aggrTarget[], const unsigned short winRanksArg[], const nodeCardsType & first, const bool flag) virtual
Reimplemented from TransTable.
Definition at line 911 of file TransTableL.cpp.
{
  if (lastBlockSeen[tricks][hand] == nullptr)
  {
    // We have recently reset the entire memory, and we were
    // in the middle of a recursion. So we'll just have to
    // drop this entry that we were supposed to be adding.
    return;
  }
  unsigned * ab[DDS_SUITS];
  unsigned * mb[DDS_SUITS];
  char low[DDS_SUITS];
  unsigned short int ag;
  int w;
  winMatchType TTentry;
  // Inefficient, as it also copies leastWin.
  // In fact I'm not quite happy with the treatment of
  // leastWin in general.
  TTentry.first = first;
  TTentry.xorSet = 0;
  for (int ss = 0; ss < DDS_SUITS; ss++)
  {
    w = static_cast<int>(ourWinRanks[ss]);
    if (w == 0)
    {
      ab[ss] = aggr[0].aggrBytes[ss];
      mb[ss] = maskBytes[0][ss];
      low[ss] = 15;
      TTentry.first.leastWin[ss] = 0;
    }
    else
    {
      w = w & (-w); /* Only lowest win */
      ag = static_cast<unsigned short>(aggrTarget[ss] & (-w));
      ab[ss] = aggr[ag].aggrBytes[ss];
      mb[ss] = maskBytes[ag][ss];
      low[ss] = static_cast<char>(TTlowestRank[ag]);
      TTentry.first.leastWin[ss] = 15 - low[ss];
      TTentry.xorSet ^= aggr[ag].aggrRanks[ss];
    }
  }
  // It's a bit annoying that we may be regenerating these.
  // But winRanks can cause them to change after lookup().
  TTentry.topSet1 = ab[0][0] | ab[1][0] | ab[2][0] | ab[3][0];
  TTentry.topSet2 = ab[0][1] | ab[1][1] | ab[2][1] | ab[3][1];
  TTentry.topSet3 = ab[0][2] | ab[1][2] | ab[2][2] | ab[3][2];
  TTentry.topSet4 = ab[0][3] | ab[1][3] | ab[2][3] | ab[3][3];
  TTentry.topMask1 = mb[0][0] | mb[1][0] | mb[2][0] | mb[3][0];
  TTentry.topMask2 = mb[0][1] | mb[1][1] | mb[2][1] | mb[3][1];
  TTentry.topMask3 = mb[0][2] | mb[1][2] | mb[2][2] | mb[3][2];
  TTentry.topMask4 = mb[0][3] | mb[1][3] | mb[2][3] | mb[3][3];
  TTentry.maskIndex =
    (low[0] << 12) | (low[1] << 8) | (low[2] << 4) | low[3];
  if (TTentry.topMask2 == 0)
    TTentry.lastMaskNo = 1;
  else if (TTentry.topMask3 == 0)
    TTentry.lastMaskNo = 2;
  else if (TTentry.topMask4 == 0)
    TTentry.lastMaskNo = 3;
  else
    TTentry.lastMaskNo = 4;
  TransTableL::CreateOrUpdate(lastBlockSeen[tricks][hand],
    TTentry, flag);
}
References DDS_SUITS, first, and nodeCardsType::leastWin.
Init()
void TransTableL::Init (const int handLookup[][15]) virtual
Reimplemented from TransTable.
Definition at line 183 of file TransTableL.cpp.
{
  // This is very similar to SetConstants, except that it
  // happens with actual cards. It also makes sense to
  // keep a record of aggrRanks for each suit. These are
  // only used later for xorSet.
  unsigned int topBitRank = 1;
  unsigned int topBitNo = 2;
  aggrType * ap;
  for (int s = 0; s < DDS_SUITS; s++)
  {
    aggr[0].aggrRanks[s] = 0;
    aggr[0].aggrBytes[s][0] = 0;
    aggr[0].aggrBytes[s][1] = 0;
    aggr[0].aggrBytes[s][2] = 0;
    aggr[0].aggrBytes[s][3] = 0;
  }
  for (unsigned ind = 1; ind < 8192; ind++)
  {
    if (ind >= (topBitRank << 1))
    {
      /* Next top bit */
      topBitRank <<= 1;
      topBitNo++;
    }
    aggr[ind] = aggr[ind ^ topBitRank];
    ap = &aggr[ind];
    for (int s = 0; s < DDS_SUITS; s++)
    {
      ap->aggrRanks[s] = ap->aggrRanks[s] >> 2 |
                          static_cast<unsigned>(handLookup[s][topBitNo] << 24);
    }
    ap->aggrBytes[0][0] = (ap->aggrRanks[0] << 6) & 0xff000000;
    ap->aggrBytes[0][1] = (ap->aggrRanks[0] << 14) & 0xff000000;
    ap->aggrBytes[0][2] = (ap->aggrRanks[0] << 22) & 0xff000000;
    ap->aggrBytes[0][3] = (ap->aggrRanks[0] << 30) & 0xff000000;
    ap->aggrBytes[1][0] = (ap->aggrRanks[1] >> 2) & 0x00ff0000;
    ap->aggrBytes[1][1] = (ap->aggrRanks[1] << 6) & 0x00ff0000;
    ap->aggrBytes[1][2] = (ap->aggrRanks[1] << 14) & 0x00ff0000;
    ap->aggrBytes[1][3] = (ap->aggrRanks[1] << 22) & 0x00ff0000;
    ap->aggrBytes[2][0] = (ap->aggrRanks[2] >> 10) & 0x0000ff00;
    ap->aggrBytes[2][1] = (ap->aggrRanks[2] >> 2) & 0x0000ff00;
    ap->aggrBytes[2][2] = (ap->aggrRanks[2] << 6) & 0x0000ff00;
    ap->aggrBytes[2][3] = (ap->aggrRanks[2] << 14) & 0x0000ff00;
    ap->aggrBytes[3][0] = (ap->aggrRanks[3] >> 18) & 0x000000ff;
    ap->aggrBytes[3][1] = (ap->aggrRanks[3] >> 10) & 0x000000ff;
    ap->aggrBytes[3][2] = (ap->aggrRanks[3] >> 2) & 0x000000ff;
    ap->aggrBytes[3][3] = (ap->aggrRanks[3] << 6) & 0x000000ff;
  }
}
References DDS_SUITS.
Lookup()
nodeCardsType * TransTableL::Lookup (const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[], const int limit, bool & lowerFlag) virtual
Reimplemented from TransTable.
Definition at line 670 of file TransTableL.cpp.
{
  // First look up distribution.
  long long suitLengths =
    (static_cast<long long>(handDist[0]) << 36) |
    (static_cast<long long>(handDist[1]) << 24) |
    (static_cast<long long>(handDist[2]) << 12) |
    (static_cast<long long>(handDist[3]) );
  int hashkey = hash8(handDist);
  bool empty;
  lastBlockSeen[tricks][hand] =
    LookupSuit(&TTroot[tricks][hand][hashkey], suitLengths, empty);
  if (empty)
    return nullptr;
  // If that worked, look up cards.
  unsigned * ab0 = aggr[ aggrTarget[0] ].aggrBytes[0];
  unsigned * ab1 = aggr[ aggrTarget[1] ].aggrBytes[1];
  unsigned * ab2 = aggr[ aggrTarget[2] ].aggrBytes[2];
  unsigned * ab3 = aggr[ aggrTarget[3] ].aggrBytes[3];
  winMatchType TTentry;
  TTentry.topSet1 = ab0[0] | ab1[0] | ab2[0] | ab3[0];
  TTentry.topSet2 = ab0[1] | ab1[1] | ab2[1] | ab3[1];
  TTentry.topSet3 = ab0[2] | ab1[2] | ab2[2] | ab3[2];
  TTentry.topSet4 = ab0[3] | ab1[3] | ab2[3] | ab3[3];
  return TransTableL::LookupCards(TTentry,
    lastBlockSeen[tricks][hand], limit, lowerFlag);
}
MakeTT()
void TransTableL::MakeTT () virtual
Reimplemented from TransTable.
Definition at line 268 of file TransTableL.cpp.
{
  if (! TTInUse)
  {
    TTInUse = 1;
    for (int t = 0; t < TT_TRICKS; t++)
    {
      for (int h = 0; h < DDS_HANDS; h++)
      {
        TTroot[t][h] = static_cast<distHashType *>
                       (malloc(256 * sizeof(distHashType)));
        if (TTroot[t][h] == nullptr)
          exit(1);
      }
    }
  }
  TransTableL::InitTT();
}
References DDS_HANDS, and TT_TRICKS.
MemoryInUse()
double TransTableL::MemoryInUse () const virtual
Reimplemented from TransTable.
Definition at line 416 of file TransTableL.cpp.
{
  int blockMem = BLOCKS_PER_PAGE * pagesCurrent *
                 static_cast<int>(sizeof(winBlockType));
  int aggrMem = 8192 * static_cast<int>(sizeof(aggrType));
  int rootMem = TT_TRICKS * DDS_HANDS * 256 *
                 static_cast<int>(sizeof(distHashType));
  return (blockMem + aggrMem + rootMem) / static_cast<double>(1024.);
}
References BLOCKS_PER_PAGE, DDS_HANDS, and TT_TRICKS.
PrintAllEntries()
void TransTableL::PrintAllEntries (ofstream & fout) const virtual
Reimplemented from TransTable.
Definition at line 1624 of file TransTableL.cpp.
{
  for (int trick = 11; trick >= 1; trick--)
  {
    for (int hand = 0; hand < DDS_HANDS; hand++)
    {
      const string st = "Entries, trick " + to_string(trick) +
        ", hand " + players[static_cast<unsigned>(hand)];
      fout << st << "\n";
      fout << string(st.size(), '=') << "\n\n";
      TransTableL::PrintEntries(fout, trick, hand);
    }
  }
  fout << "\n";
}
References DDS_HANDS, and PrintEntries().
PrintAllEntryStats()
void TransTableL::PrintAllEntryStats (ofstream & fout) const virtual
Reimplemented from TransTable.
Definition at line 1717 of file TransTableL.cpp.
{
  int hist[BLOCKS_PER_ENTRY+1];
  int num_wraps;
  int suitWraps = 0;
  int suitHist[BLOCKS_PER_ENTRY+1];
  for (int i = 0; i <= BLOCKS_PER_ENTRY; i++)
    suitHist[i] = 0;
  for (int trick = 11; trick >= 1; trick--)
  {
    for (int hand = 0; hand < DDS_HANDS; hand++)
    {
      TransTableL::UpdateEntryHist(trick, hand, hist, suitHist,
        num_wraps, suitWraps);
      fout << "Entry histogram for trick " << trick << ", hands " <<
        players[static_cast<unsigned>(hand)] << "\n";
      TransTableL::PrintHist(fout, hist, num_wraps, BLOCKS_PER_ENTRY);
    }
  }
  fout << "Overall entry histogram\n";
  TransTableL::PrintHist(fout, suitHist, suitWraps, BLOCKS_PER_ENTRY);
}
References BLOCKS_PER_ENTRY, DDS_HANDS, and i.
PrintAllSuits()
void TransTableL::PrintAllSuits (ofstream & fout) const virtual
Reimplemented from TransTable.
Definition at line 1190 of file TransTableL.cpp.
{
  for (int trick = 11; trick >= 1; trick--)
  {
    for (int hand = 0; hand < DDS_HANDS; hand++)
    {
      fout << "Trick " << trick << ", hand " <<
        players[static_cast<unsigned>(hand)] << "\n";
      fout << string(20, '=') << "\n\n";
      TransTableL::PrintSuits(fout, trick, hand);
    }
  }
}
References DDS_HANDS, and PrintSuits().
PrintAllSuitStats()
void TransTableL::PrintAllSuitStats (ofstream & fout) const virtual
Reimplemented from TransTable.
Definition at line 1362 of file TransTableL.cpp.
{
  int num_wraps;
  int suitWraps = 0;
  // Really the maximum of BLOCKS_PER_ENTRY and DISTS_PER_ENTRY.
  int hist[DISTS_PER_ENTRY+1];
  int suitHist[DISTS_PER_ENTRY+1];
  for (int i = 0; i <= DISTS_PER_ENTRY; i++)
    suitHist[i] = 0;
  for (int trick = 11; trick >= 1; trick--)
  {
    for (int hand = 0; hand < DDS_HANDS; hand++)
    {
      TransTableL::UpdateSuitHist(trick, hand, hist, suitHist,
        num_wraps, suitWraps);
      fout << "Suit histogram for trick " << trick << ", hand " <<
        players[static_cast<unsigned>(hand)] << "\n";
      TransTableL::PrintHist(fout, hist, num_wraps, DISTS_PER_ENTRY);
    }
  }
  fout << "Overall suit histogram\n";
  TransTableL::PrintHist(fout, suitHist, suitWraps, DISTS_PER_ENTRY);
}
References DDS_HANDS, DISTS_PER_ENTRY, and i.
PrintEntries()
void TransTableL::PrintEntries (ofstream & fout, const int trick, const int hand) const virtual
Reimplemented from TransTable.
Definition at line 1599 of file TransTableL.cpp.
{
  winBlockType * bp;
  distHashType * dp;
  int handDist[DDS_HANDS];
  unsigned char lengths[DDS_HANDS][DDS_SUITS];
  for (int hashkey = 0; hashkey < 256; hashkey++)
  {
    dp = &TTroot[trick][hand][hashkey];
    for (int i = 0; i < dp->nextNo; i++)
    {
      bp = dp->list[i].posBlock;
      TransTableL::KeyToDist(dp->list[i].key, handDist);
      TransTableL::DistToLengths(trick, handDist, lengths);
      TransTableL::PrintEntriesBlock(fout, bp, lengths);
    }
  }
}
References DDS_HANDS, DDS_SUITS, and i.
Referenced by PrintAllEntries().
PrintEntriesDist()
void TransTableL::PrintEntriesDist (ofstream & fout, const int trick, const int hand, const int handDist[]) const virtual
Reimplemented from TransTable.
Definition at line 1574 of file TransTableL.cpp.
{
  unsigned char len[DDS_HANDS][DDS_SUITS];
  winBlockType const * bp =
    TransTableL::FindMatchingDist(trick, hand, handDist);
  TransTableL::DistToLengths(trick, handDist, len);
  if (! bp)
  {
    fout << "Entry not found: Trick " << trick << ", hand " <<
      players[static_cast<unsigned>(hand)] << "\n";
    fout << TransTableL::LenToStr(len) << "\n\n";
    return;
  }
  TransTableL::PrintEntriesBlock(fout, bp, len);
}
References DDS_HANDS, DDS_SUITS, and len.
PrintEntriesDistAndCards()
void TransTableL::PrintEntriesDistAndCards (ofstream & fout, const int trick, const int hand, const unsigned short aggrTarget[], const int handDist[]) const virtual
Reimplemented from TransTable.
Definition at line 1506 of file TransTableL.cpp.
{
  unsigned char len[DDS_HANDS][DDS_SUITS];
  winBlockType const * bp =
    TransTableL::FindMatchingDist(trick, hand, handDist);
  TransTableL::DistToLengths(trick, handDist, len);
  fout << "Looking up entry for trick " << trick << ", hand " <<
    players[static_cast<unsigned>(hand)] << "\n";
  fout << TransTableL::LenToStr(len) << "\n\n";
  if (! bp)
  {
    fout << "Entry not found\n\n";
    return;
  }
  unsigned const * ab0 = aggr[ aggrTarget[0] ].aggrBytes[0];
  unsigned const * ab1 = aggr[ aggrTarget[1] ].aggrBytes[1];
  unsigned const * ab2 = aggr[ aggrTarget[2] ].aggrBytes[2];
  unsigned const * ab3 = aggr[ aggrTarget[3] ].aggrBytes[3];
  winMatchType TTentry;
  TTentry.topSet1 = ab0[0] | ab1[0] | ab2[0] | ab3[0];
  TTentry.topSet2 = ab0[1] | ab1[1] | ab2[1] | ab3[1];
  TTentry.topSet3 = ab0[2] | ab1[2] | ab2[2] | ab3[2];
  TTentry.topSet4 = ab0[3] | ab1[3] | ab2[3] | ab3[3];
  int matchNo = 1;
  int n = bp->nextMatchNo - 1;
  winMatchType const * wp = &bp->list[n];
  for (int i = n; i >= 0; i--, wp--)
  {
    if ((wp->topSet1 ^ TTentry.topSet1) & wp->topMask1)
      continue;
    if (wp->lastMaskNo != 1)
    {
      if ((wp->topSet2 ^ TTentry.topSet2) & wp->topMask2)
        continue;
      if (wp->lastMaskNo != 2)
      {
        if ((wp->topSet3 ^ TTentry.topSet3) & wp->topMask3)
          continue;
      }
    }
    fout << "Match number " << matchNo++ << "\n";
    fout << string(15, '-') << "\n";
    TransTableL::PrintMatch(fout, bp->list[i], len);
  }
  if (matchNo == 1)
    fout << n << " matches for suit, none for cards\n\n";
  else
    fout << "\n";
}
References DDS_HANDS, DDS_SUITS, i, len, and n.
PrintEntryStats()
void TransTableL::PrintEntryStats (ofstream & fout, const int trick, const int hand) const virtual
Reimplemented from TransTable.
Definition at line 1701 of file TransTableL.cpp.
{
  int hist[BLOCKS_PER_ENTRY+1];
  int num_wraps;
  TransTableL::UpdateEntryHist(trick, hand, hist, num_wraps);
  fout << "Entry histogram for trick " << trick << ", hands " <<
    players[static_cast<unsigned>(hand)] << "\n";
  TransTableL::PrintHist(fout, hist, num_wraps, BLOCKS_PER_ENTRY);
}
References BLOCKS_PER_ENTRY.
PrintSuits()
void TransTableL::PrintSuits (ofstream & fout, const int trick, const int hand) const virtual
Reimplemented from TransTable.
Definition at line 1150 of file TransTableL.cpp.
{
  distHashType * dp;
  int handDist[DDS_HANDS];
  unsigned char len[DDS_HANDS][DDS_SUITS];
  fout << setw(4) << left << "Key" <<
    setw(3) << right << "No" <<
    setw(8) << right << players[0] <<
    setw(8) << players[1] <<
    setw(8) << players[2] <<
    setw(8) << players[3] << "\n";
  for (int hashkey = 0; hashkey < 256; hashkey++)
  {
    dp = &TTroot[trick][hand][hashkey];
    if (dp->nextNo == 0)
      continue;
    for (int i = 0; i < dp->nextNo; i++)
    {
      if (i == 0)
        fout << "0x" << setw(2) << hex << hashkey <<
          setw(3) << right << dec << dp->nextNo << " ";
      else
        fout << setw(8) << "";
      TransTableL::KeyToDist(dp->list[i].key, handDist);
      TransTableL::DistToLengths(trick, handDist, len);
      fout << TransTableL::LenToStr(len) << "\n";
    }
  }
  fout << "\n";
}
References DDS_HANDS, DDS_SUITS, i, and len.
Referenced by PrintAllSuits().
PrintSuitStats()
void TransTableL::PrintSuitStats (ofstream & fout, const int trick, const int hand) const virtual
Reimplemented from TransTable.
Definition at line 1346 of file TransTableL.cpp.
{
  int hist[DISTS_PER_ENTRY+1];
  int num_wraps;
  TransTableL::UpdateSuitHist(trick, hand, hist, num_wraps);
  fout << "Suit histogram for trick " << trick << ", hand " <<
    players[static_cast<unsigned>(hand)] << "\n";
  TransTableL::PrintHist(fout, hist, num_wraps, DISTS_PER_ENTRY);
}
References DISTS_PER_ENTRY.
PrintSummaryEntryStats()
void TransTableL::PrintSummaryEntryStats (ofstream & fout) const virtual
Reimplemented from TransTable.
Definition at line 1770 of file TransTableL.cpp.
{
  int hist[BLOCKS_PER_ENTRY + 1];
  int count, prod_sum, prod_sumsq, max_len, num_wraps;
  int cumCount = 0;
  double cumProd = 0.;
  int cumMemory = 0;
  fout << "Entry depth statistics\n\n";
  fout << setw(5) << right << "Trick" <<
    setw(7) << "Player" <<
    setw(8) << "Entries" <<
    setw(8) << "Full" <<
    setw(8) << "Average" <<
    setw(8) << "Std.dev" <<
    setw(8) << "Maximum" <<
    "   P" << setw(4) << setprecision(2) << fixed << TT_PERCENTILE << "\n";
  for (int trick = 11; trick >= 1; trick--)
  {
    for (int hand = 0; hand < DDS_HANDS; hand++)
    {
      TransTableL::UpdateEntryHist(trick, hand, hist, num_wraps);
      TransTableL::MakeHistStats(hist,
        count, prod_sum, prod_sumsq, max_len, BLOCKS_PER_ENTRY);
      cumCount += count;
      cumProd += prod_sum;
      cumMemory += TransTableL::EffectOfBlockBound(hist, 20);
      double mean = prod_sum / static_cast<double>(count);
      double var = (count > 1 ?
        (prod_sumsq - count*mean*mean) /
          static_cast<double>(count-1) : 0.);
      if (var < 0.)
        var = 0.;
      const int percentile = TransTableL::CalcPercentile(hist,
         TT_PERCENTILE * count, BLOCKS_PER_ENTRY);
      fout << setw(5) << right << trick <<
        setw(7) << players[static_cast<unsigned>(hand)] <<
        setw(8) << count <<
        setw(8) << num_wraps <<
        setw(8) << mean <<
        setw(8) << sqrt(var) <<
        setw(8) << max_len <<
        setw(8) << setprecision(2) << fixed << percentile << "\n";
    }
    fout << "\n";
  }
  fout << "\n";
  fout << setw(16) << left << "Blocks counted " <<
    setw(8) << right << cumCount << "\n";
  fout << setw(16) << left << "Blocks produced " <<
    setw(8) << right << TransTableL::BlocksInUse() << "\n";
  fout << setw(16) << left << "Mem scenario" <<
    setw(7) << right << setprecision(2) << fixed <<
      100. * cumMemory /
        (static_cast<double>(BLOCKS_PER_ENTRY * cumCount)) << "%\n";
  if (cumCount)
    fout << setw(16) << left << "Fullness" <<
      setw(7) << right << setprecision(2) << fixed <<
        100. * cumProd / (BLOCKS_PER_ENTRY * cumCount) << "%\n";
  fout << "\n";
}
References BLOCKS_PER_ENTRY, DDS_HANDS, and TT_PERCENTILE.
PrintSummarySuitStats()
void TransTableL::PrintSummarySuitStats (ofstream & fout) const virtual
Reimplemented from TransTable.
Definition at line 1392 of file TransTableL.cpp.
{
  int hist[DISTS_PER_ENTRY+1];
  int count, prod_sum, prod_sumsq, max_len, num_wraps;
  fout << "Suit depth statistics\n\n";
  fout << setw(5) << right << "Trick" <<
    setw(7) << "Player" <<
    setw(8) << "Entries" <<
    setw(8) << "Full" <<
    setw(8) << "Average" <<
    setw(8) << "Std.dev" <<
    setw(8) << "Maximum" <<
    "   P" << setw(4) << setprecision(2) << fixed << TT_PERCENTILE << "\n";
  for (int trick = 11; trick >= 1; trick--)
  {
    for (int hand = 0; hand < DDS_HANDS; hand++)
    {
      TransTableL::UpdateSuitHist(trick, hand, hist, num_wraps);
      TransTableL::MakeHistStats(hist,
        count, prod_sum, prod_sumsq, max_len, DISTS_PER_ENTRY);
      double mean = 0., var = 0.;
      if (count > 1)
      {
        mean = prod_sum / static_cast<double>(count);
        var = (prod_sumsq - count*mean*mean) /
          static_cast<double>(count-1);
        if (var < 0.)
          var = 0.;
      }
      const int percentile =
        TransTableL::CalcPercentile(hist,
          TT_PERCENTILE * count, DISTS_PER_ENTRY);
      fout << setw(5) << right << trick <<
        setw(7) << players[static_cast<unsigned>(hand)] <<
        setw(8) << count <<
        setw(8) << num_wraps;
      if (count > 0)
        fout << setw(8) << mean <<
          setw(8) << setprecision(2) << fixed << sqrt(var);
      else
        fout << setw(8) << '-' << setw(8) << '-';
      fout << setw(8) << max_len <<
        setw(8) << setprecision(2) << fixed << percentile << "\n";
    }
    fout << "\n";
  }
  fout << "\n";
}
References DDS_HANDS, DISTS_PER_ENTRY, and TT_PERCENTILE.
ResetMemory()
void TransTableL::ResetMemory (const TTresetReason reason) virtual
Reimplemented from TransTable.
Definition at line 328 of file TransTableL.cpp.
{
  UNUSED(reason);
  if (poolp == nullptr)
    return;
  pageStats.numResets++;
  pageStats.numCallocs += pagesCurrent - pageStats.lastCurrent;
  pageStats.lastCurrent = pagesCurrent;
  while (pagesCurrent > pagesDefault)
  {
    free(poolp->list);
    poolp = poolp->prev;
    free(poolp->next);
    poolp->next = nullptr;
    pagesCurrent--;
  }
  pageStats.numFrees += pageStats.lastCurrent - pagesCurrent;
  pageStats.lastCurrent = pagesCurrent;
  while (poolp->prev)
    poolp = poolp->prev;
  poolp->nextBlockNo = 0;
  nextBlockp = poolp->list;
  TransTableL::InitTT();
  timestamp = 0;
  memState = FROM_POOL;
  return;
}
References UNUSED.
ReturnAllMemory()
void TransTableL::ReturnAllMemory () virtual
Reimplemented from TransTable.
Definition at line 368 of file TransTableL.cpp.
{
  poolType * tmp;
  if (poolp)
  {
    while (poolp->next)
      poolp = poolp->next;
    while (poolp)
    {
      free(poolp->list);
      tmp = poolp;
      poolp = poolp->prev;
      free(tmp);
    }
  }
  pagesCurrent = 0;
  pageStats.numResets = 0;
  pageStats.numCallocs = 0;
  pageStats.numFrees = 0;
  pageStats.numHarvests = 0;
  pageStats.lastCurrent = 0;
  TransTableL::ReleaseTT();
  return;
}
Referenced by ~TransTableL().
SetMemoryDefault()
void TransTableL::SetMemoryDefault (const int megabytes) virtual
Reimplemented from TransTable.
Definition at line 244 of file TransTableL.cpp.
{
  double blockMem = BLOCKS_PER_PAGE * sizeof(winBlockType) /
                    static_cast<double>(1024.);
  pagesDefault = static_cast<int>((1024 * megabytes) / blockMem);
}
References BLOCKS_PER_PAGE.
SetMemoryMaximum()
void TransTableL::SetMemoryMaximum (const int megabytes) virtual
Reimplemented from TransTable.
Definition at line 253 of file TransTableL.cpp.
{
  double blockMem = BLOCKS_PER_PAGE * sizeof(winBlockType) /
                    static_cast<double>(1024.);
  pagesMaximum = static_cast<int>((1024 * megabytes) / blockMem);
}
References BLOCKS_PER_PAGE.
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/TransTableL.h
open_spiel/games/bridge/double_dummy_solver/src/TransTableL.cpp