open spiel: open_spiel::crowd_modelling::CrowdModellingState Class Reference
open_spiel::crowd_modelling::CrowdModellingState Class Reference
#include <crowd_modelling.h>
Public Member Functions
CrowdModellingState (std::shared_ptr< const Game > game, int size, int horizon)
CrowdModellingState (std::shared_ptr< const Game > game, int size, int horizon, Player current_player, bool is_chance_init, int x, int t, int last_action, double return_value, const std::vector< double > &distribution)
CrowdModellingState (const CrowdModellingState &)=default
CrowdModellingState & operator= (const CrowdModellingState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
ActionsAndProbs ChanceOutcomes () const override
std::vector< std::string > DistributionSupport () override
void UpdateDistribution (const std::vector< double > &distribution) override
std::vector< double > Distribution () const
std::string Serialize () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 61 of file crowd_modelling.h.
Constructor & Destructor Documentation
CrowdModellingState() [1/3]
open_spiel::crowd_modelling::CrowdModellingState::CrowdModellingState (std::shared_ptr< const Game > game, int size, int horizon)
Definition at line 83 of file crowd_modelling.cc.
    : State(game),
      size_(size),
      horizon_(horizon),
      distribution_(size_, 1. / size_) {}
Referenced by Clone().
CrowdModellingState() [2/3]
open_spiel::crowd_modelling::CrowdModellingState::CrowdModellingState (std::shared_ptr< const Game > game, int size, int horizon, Player current_player, bool is_chance_init, int x, int t, int last_action, double return_value, const std::vector< double > & distribution)
Definition at line 90 of file crowd_modelling.cc.
    : State(game),
      size_(size),
      horizon_(horizon),
      current_player_(current_player),
      is_chance_init_(is_chance_init),
      x_(x),
      t_(t),
      last_action_(last_action),
      return_value_(return_value),
      distribution_(distribution) {}
CrowdModellingState() [3/3]
open_spiel::crowd_modelling::CrowdModellingState::CrowdModellingState (const CrowdModellingState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::crowd_modelling::CrowdModellingState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 146 of file crowd_modelling.cc.
{
  if (IsChanceNode() && is_chance_init_) {
    return absl::Substitute("init_state=$0", action);
  }
  return std::to_string(kActionToMove.at(action));
}
References action, open_spiel::State::IsChanceNode(), and absl::Substitute().
ChanceOutcomes()
ActionsAndProbs open_spiel::crowd_modelling::CrowdModellingState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 113 of file crowd_modelling.cc.
{
  if (is_chance_init_) {
    ActionsAndProbs outcomes;
    for (int i = 0; i < size_; ++i) {
      outcomes.push_back({i, 1. / size_});
    }
    return outcomes;
  }
  return {{0, 1. / 3}, {1, 1. / 3}, {2, 1. / 3}};
}
References i.
Clone()
std::unique_ptr< State > open_spiel::crowd_modelling::CrowdModellingState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 221 of file crowd_modelling.cc.
{
  return std::unique_ptr<State>(new CrowdModellingState(*this));
}
References CrowdModellingState().
CurrentPlayer()
Player open_spiel::crowd_modelling::CrowdModellingState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 72 of file crowd_modelling.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Distribution()
std::vector< double > open_spiel::crowd_modelling::CrowdModellingState::Distribution () const inline
Definition at line 90 of file crowd_modelling.h.
{ return distribution_; }
DistributionSupport()
std::vector< std::string > open_spiel::crowd_modelling::CrowdModellingState::DistributionSupport () override virtual
Reimplemented from open_spiel::State.
Definition at line 154 of file crowd_modelling.cc.
{
  std::vector<std::string> support;
  support.reserve(size_);
  for (int x = 0; x < size_; ++x) {
    support.push_back(StateToString(x, t_, kMeanFieldPlayerId, false));
  }
  return support;
}
References open_spiel::kMeanFieldPlayerId, StateToString(), and x.
DoApplyAction()
void open_spiel::crowd_modelling::CrowdModellingState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 124 of file crowd_modelling.cc.
{
  SPIEL_CHECK_NE(current_player_, kMeanFieldPlayerId);
  return_value_ += Rewards()[0];
  if (is_chance_init_) {
    SPIEL_CHECK_GE(action, 0);
    SPIEL_CHECK_LT(action, size_);
    SPIEL_CHECK_EQ(current_player_, kChancePlayerId);
    x_ = action;
    is_chance_init_ = false;
    current_player_ = 0;
  } else if (current_player_ == kChancePlayerId) {
    x_ = (x_ + kActionToMove.at(action) + size_) % size_;
    ++t_;
    current_player_ = kMeanFieldPlayerId;
  } else {
    SPIEL_CHECK_EQ(current_player_, 0);
    x_ = (x_ + kActionToMove.at(action) + size_) % size_;
    last_action_ = action;
    current_player_ = kChancePlayerId;
  }
}
References action, open_spiel::kChancePlayerId, open_spiel::kMeanFieldPlayerId, Rewards(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and SPIEL_CHECK_NE.
InformationStateString()
std::string open_spiel::crowd_modelling::CrowdModellingState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 191 of file crowd_modelling.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::crowd_modelling::CrowdModellingState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 171 of file crowd_modelling.cc.
{ return t_ >= horizon_; }
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::crowd_modelling::CrowdModellingState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 105 of file crowd_modelling.cc.
{
  if (IsTerminal()) return {};
  if (IsChanceNode()) return LegalChanceOutcomes();
  if (IsMeanFieldNode()) return {};
  SPIEL_CHECK_TRUE(IsPlayerNode());
  return {0, 1, 2};
}
References open_spiel::State::IsChanceNode(), open_spiel::State::IsMeanFieldNode(), open_spiel::State::IsPlayerNode(), IsTerminal(), open_spiel::State::LegalChanceOutcomes(), and SPIEL_CHECK_TRUE.
ObservationString()
std::string open_spiel::crowd_modelling::CrowdModellingState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 197 of file crowd_modelling.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::crowd_modelling::CrowdModellingState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 203 of file crowd_modelling.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), size_ + horizon_ + 1);
  SPIEL_CHECK_LT(x_, size_);
  SPIEL_CHECK_GE(t_, 0);
  // Allow t_ == horizon_.
  SPIEL_CHECK_LE(t_, horizon_);
  std::fill(values.begin(), values.end(), 0.);
  if (x_ >= 0) {
    values[x_] = 1.;
  }
  // x_ equals -1 for the initial (blank) state, don't set any
  // position bit in that case.
  values[size_ + t_] = 1.;
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, and values.
operator=()
CrowdModellingState & open_spiel::crowd_modelling::CrowdModellingState::operator= (const CrowdModellingState &) default
Returns()
std::vector< double > open_spiel::crowd_modelling::CrowdModellingState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 183 of file crowd_modelling.cc.
{
  return {return_value_ + Rewards()[0]};
}
References Rewards().
Rewards()
std::vector< double > open_spiel::crowd_modelling::CrowdModellingState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 173 of file crowd_modelling.cc.
{
  if (current_player_ != 0) {
    return {0.};
  }
  double r_x = 1 - 1.0 * std::abs(x_ - size_ / 2) / (size_ / 2);
  double r_a = -1.0 * std::abs(kActionToMove.at(last_action_)) / size_;
  double r_mu = -std::log(distribution_[x_]+kEpsilon);
  return {r_x + r_a + r_mu};
}
Referenced by DoApplyAction(), and Returns().
Serialize()
std::string open_spiel::crowd_modelling::CrowdModellingState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 225 of file crowd_modelling.cc.
{
  std::string out =
      absl::StrCat(current_player_, ",", is_chance_init_, ",", x_, ",", t_, ",",
                   last_action_, ",", return_value_, "\n");
  absl::StrAppend(&out, absl::StrJoin(distribution_, ","));
  return out;
}
References out, absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
ToString()
std::string open_spiel::crowd_modelling::CrowdModellingState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 187 of file crowd_modelling.cc.
{
  return StateToString(x_, t_, current_player_, is_chance_init_);
}
References StateToString().
Referenced by ObservationString().
UpdateDistribution()
void open_spiel::crowd_modelling::CrowdModellingState::UpdateDistribution (const std::vector< double > & distribution) override virtual
Reimplemented from open_spiel::State.
Definition at line 163 of file crowd_modelling.cc.
{
  SPIEL_CHECK_EQ(current_player_, kMeanFieldPlayerId);
  SPIEL_CHECK_EQ(distribution.size(), size_);
  distribution_ = distribution;
  current_player_ = kDefaultPlayerId;
}
References open_spiel::kDefaultPlayerId, open_spiel::kMeanFieldPlayerId, and SPIEL_CHECK_EQ.
The documentation for this class was generated from the following files:
open_spiel/games/mfg/crowd_modelling.h
open_spiel/games/mfg/crowd_modelling.cc