open spiel: open_spiel::SpanTensor Class Reference
open_spiel::SpanTensor Class Reference
#include <observer.h>
Public Member Functions
SpanTensor (SpanTensorInfo info, absl::Span< float > data)
const SpanTensorInfo & info () const
absl::Span< float > data () const
std::string DebugString () const
float & at () const
float & at (int idx) const
float & at (int idx1, int idx2) const
float & at (int idx1, int idx2, int idx3) const
float & at (int idx1, int idx2, int idx3, int idx4) const
Detailed Description
Definition at line 113 of file observer.h.
Constructor & Destructor Documentation
SpanTensor()
open_spiel::SpanTensor::SpanTensor (SpanTensorInfo info, absl::Span< float > data) inline
Definition at line 115 of file observer.h.
      : info_(std::move(info)), data_(data) {
    SPIEL_CHECK_EQ(info_.size(), data_.size());
  }
References absl::Span< T >::size(), open_spiel::SpanTensorInfo::size(), and SPIEL_CHECK_EQ.
Member Function Documentation
at() [1/5]
float & open_spiel::SpanTensor::at () const inline
Definition at line 127 of file observer.h.
                    {
    SPIEL_DCHECK_EQ(info_.shape().size(), 0);
    return data_[0];
  }
References open_spiel::SpanTensorInfo::shape(), absl::InlinedVector< T, N, A >::size(), and SPIEL_DCHECK_EQ.
Referenced by open_spiel::leduc_poker::LeducObserver::WriteCommunityCard(), open_spiel::leduc_poker::LeducObserver::WriteObservingPlayer(), open_spiel::leduc_poker::LeducObserver::WritePotContribution(), open_spiel::kuhn_poker::KuhnObserver::WriteTensor(), open_spiel::phantom_go::PhantomGoObserver::WriteTensor(), and open_spiel::RestrictedNashResponseObserver::WriteTensor().
at() [2/5]
float & open_spiel::SpanTensor::at (int idx) const inline
Definition at line 132 of file observer.h.
{
    SPIEL_DCHECK_EQ(info_.shape().size(), 1);
    return data_[idx];
  }
References open_spiel::SpanTensorInfo::shape(), absl::InlinedVector< T, N, A >::size(), and SPIEL_DCHECK_EQ.
at() [3/5]
float & open_spiel::SpanTensor::at (int idx1, int idx2) const inline
Definition at line 137 of file observer.h.
{
    SPIEL_DCHECK_EQ(info_.shape().size(), 2);
    return data_[idx1 * info_.shape()[1] + idx2];
  }
References open_spiel::SpanTensorInfo::shape(), absl::InlinedVector< T, N, A >::size(), and SPIEL_DCHECK_EQ.
at() [4/5]
float & open_spiel::SpanTensor::at (int idx1, int idx2, int idx3) const inline
Definition at line 142 of file observer.h.
{
    SPIEL_DCHECK_EQ(info_.shape().size(), 3);
    return data_[(idx1 * info_.shape()[1] + idx2) * info_.shape()[2] + idx3];
  }
References open_spiel::SpanTensorInfo::shape(), absl::InlinedVector< T, N, A >::size(), and SPIEL_DCHECK_EQ.
at() [5/5]
float & open_spiel::SpanTensor::at (int idx1, int idx2, int idx3, int idx4) const inline
Definition at line 147 of file observer.h.
{
    SPIEL_DCHECK_EQ(info_.shape().size(), 4);
    return data_[((idx1 * info_.shape()[1] + idx2) * info_.shape()[2] + idx3) *
                     info_.shape()[3] +
                 idx4];
  }
References open_spiel::SpanTensorInfo::shape(), absl::InlinedVector< T, N, A >::size(), and SPIEL_DCHECK_EQ.
data()
absl::Span< float > open_spiel::SpanTensor::data () const inline
Definition at line 122 of file observer.h.
{ return data_; }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), open_spiel::init_pyspiel_observer(), and open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample().
DebugString()
std::string open_spiel::SpanTensor::DebugString () const inline
Definition at line 124 of file observer.h.
{ return info_.DebugString(); }
References open_spiel::SpanTensorInfo::DebugString().
Referenced by open_spiel::init_pyspiel_observer().
info()
const SpanTensorInfo & open_spiel::SpanTensor::info () const inline
Definition at line 120 of file observer.h.
{ return info_; }
Referenced by open_spiel::init_pyspiel_observer().
The documentation for this class was generated from the following file:
open_spiel/observer.h