open spiel: open_spiel::tic_tac_toe::TicTacToeState Class Reference
open_spiel::tic_tac_toe::TicTacToeState Class Reference
#include <tic_tac_toe.h>
Public Member Functions
TicTacToeState (std::shared_ptr< const Game > game)
TicTacToeState (const TicTacToeState &)=default
TicTacToeState & operator= (const TicTacToeState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action move) override
std::vector< Action > LegalActions () const override
CellState BoardAt (int cell) const
CellState BoardAt (int row, int column) const
Player outcome () const
void SetCurrentPlayer (Player player)
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes
std::array< CellState, kNumCells > board_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 52 of file tic_tac_toe.h.
Constructor & Destructor Documentation
TicTacToeState() [1/2]
open_spiel::tic_tac_toe::TicTacToeState::TicTacToeState (std::shared_ptr< const Game > game)
Definition at line 128 of file tic_tac_toe.cc.
                                                             : State(game) {
  std::fill(begin(board_), end(board_), CellState::kEmpty);
}
References begin, board_, end, and open_spiel::tic_tac_toe::kEmpty.
Referenced by Clone().
TicTacToeState() [2/2]
open_spiel::tic_tac_toe::TicTacToeState::TicTacToeState (const TicTacToeState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::tic_tac_toe::TicTacToeState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 117 of file tic_tac_toe.cc.
{
  return game_->ActionToString(player, action_id);
}
References open_spiel::State::game_, and player.
Referenced by open_spiel::phantom_ttt::PhantomTTTState::ActionToString().
BoardAt() [1/2]
CellState open_spiel::tic_tac_toe::TicTacToeState::BoardAt (int cell) const inline
Definition at line 73 of file tic_tac_toe.h.
{ return board_[cell]; }
References board_.
Referenced by open_spiel::phantom_ttt::PhantomTTTState::DoApplyAction(), open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ObservationTensor(), ToString(), and open_spiel::phantom_ttt::PhantomTTTState::UndoAction().
BoardAt() [2/2]
CellState open_spiel::tic_tac_toe::TicTacToeState::BoardAt (int row, int column) const inline
Definition at line 74 of file tic_tac_toe.h.
{
    return board_[row * kNumCols + column];
  }
References board_.
Clone()
std::unique_ptr< State > open_spiel::tic_tac_toe::TicTacToeState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 192 of file tic_tac_toe.cc.
{
  return std::unique_ptr<State>(new TicTacToeState(*this));
}
References TicTacToeState().
CurrentPlayer()
Player open_spiel::tic_tac_toe::TicTacToeState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 59 of file tic_tac_toe.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by open_spiel::phantom_ttt::PhantomTTTState::CurrentPlayer(), and DoApplyAction().
DoApplyAction()
void open_spiel::tic_tac_toe::TicTacToeState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 95 of file tic_tac_toe.cc.
{
  SPIEL_CHECK_EQ(board_[move], CellState::kEmpty);
  board_[move] = PlayerToState(CurrentPlayer());
  if (HasLine(current_player_)) {
    outcome_ = current_player_;
  }
  current_player_ = 1 - current_player_;
  num_moves_ += 1;
}
References board_, CurrentPlayer(), open_spiel::tic_tac_toe::kEmpty, open_spiel::tic_tac_toe::PlayerToState(), and SPIEL_CHECK_EQ.
InformationStateString()
std::string open_spiel::tic_tac_toe::TicTacToeState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 159 of file tic_tac_toe.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::tic_tac_toe::TicTacToeState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 145 of file tic_tac_toe.cc.
{
  return outcome_ != kInvalidPlayer || IsFull();
}
References open_spiel::kInvalidPlayer.
Referenced by CurrentPlayer(), open_spiel::phantom_ttt::PhantomTTTState::IsTerminal(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::tic_tac_toe::TicTacToeState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 105 of file tic_tac_toe.cc.
{
  if (IsTerminal()) return {};
  // Can move in any empty cell.
  std::vector<Action> moves;
  for (int cell = 0; cell < kNumCells; ++cell) {
    if (board_[cell] == CellState::kEmpty) {
      moves.push_back(cell);
    }
  }
  return moves;
}
References board_, IsTerminal(), open_spiel::tic_tac_toe::kEmpty, and open_spiel::tic_tac_toe::kNumCells.
ObservationString()
std::string open_spiel::tic_tac_toe::TicTacToeState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 165 of file tic_tac_toe.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::tic_tac_toe::TicTacToeState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 171 of file tic_tac_toe.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // Treat `values` as a 2-d tensor.
  TensorView<2> view(values, {kCellStates, kNumCells}, true);
  for (int cell = 0; cell < kNumCells; ++cell) {
    view[{static_cast<int>(board_[cell]), cell}] = 1.0;
  }
}
References board_, open_spiel::tic_tac_toe::kCellStates, open_spiel::tic_tac_toe::kNumCells, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
operator=()
TicTacToeState & open_spiel::tic_tac_toe::TicTacToeState::operator= (const TicTacToeState &) default
outcome()
Player open_spiel::tic_tac_toe::TicTacToeState::outcome () const inline
Definition at line 77 of file tic_tac_toe.h.
{ return outcome_; }
Referenced by open_spiel.python.examples.nego_nbs_example.Negotiation::__str__(), open_spiel::ultimate_tic_tac_toe::UltimateTTTState::DoApplyAction(), open_spiel.python.algorithms.mcts.SearchNode::puct_value(), open_spiel.python.algorithms.mcts.SearchNode::sort_key(), open_spiel.python.algorithms.mcts.SearchNode::to_str(), and open_spiel.python.algorithms.mcts.SearchNode::uct_value().
Returns()
std::vector< double > open_spiel::tic_tac_toe::TicTacToeState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 149 of file tic_tac_toe.cc.
{
  if (HasLine(Player{0})) {
    return {1.0, -1.0};
  } else if (HasLine(Player{1})) {
    return {-1.0, 1.0};
  } else {
    return {0.0, 0.0};
  }
}
Referenced by open_spiel::phantom_ttt::PhantomTTTState::Returns().
SetCurrentPlayer()
void open_spiel::tic_tac_toe::TicTacToeState::SetCurrentPlayer (Player player) inline
Definition at line 80 of file tic_tac_toe.h.
{ current_player_ = player; }
References player.
Referenced by open_spiel::ultimate_tic_tac_toe::UltimateTTTState::DoApplyAction().
ToString()
std::string open_spiel::tic_tac_toe::TicTacToeState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 132 of file tic_tac_toe.cc.
{
  std::string str;
  for (int r = 0; r < kNumRows; ++r) {
    for (int c = 0; c < kNumCols; ++c) {
      absl::StrAppend(&str, StateToString(BoardAt(r, c)));
    }
    if (r < (kNumRows - 1)) {
      absl::StrAppend(&str, "\n");
    }
  }
  return str;
}
References BoardAt(), open_spiel::tic_tac_toe::kNumCols, open_spiel::tic_tac_toe::kNumRows, r, open_spiel::tic_tac_toe::StateToString(), and absl::StrAppend().
Referenced by ObservationString(), and open_spiel::phantom_ttt::PhantomTTTState::ToString().
UndoAction()
void open_spiel::tic_tac_toe::TicTacToeState::UndoAction (Player player, Action move) override virtual
Reimplemented from open_spiel::State.
Definition at line 183 of file tic_tac_toe.cc.
{
  board_[move] = CellState::kEmpty;
  current_player_ = player;
  outcome_ = kInvalidPlayer;
  num_moves_ -= 1;
  history_.pop_back();
  --move_number_;
}
References board_, open_spiel::State::history_, open_spiel::tic_tac_toe::kEmpty, open_spiel::kInvalidPlayer, open_spiel::State::move_number_, and player.
Referenced by open_spiel::phantom_ttt::PhantomTTTState::UndoAction().
Member Data Documentation
board_
std::array<CellState, kNumCells> open_spiel::tic_tac_toe::TicTacToeState::board_ protected
Definition at line 83 of file tic_tac_toe.h.
Referenced by BoardAt(), BoardAt(), DoApplyAction(), LegalActions(), ObservationTensor(), TicTacToeState(), and UndoAction().
The documentation for this class was generated from the following files:
open_spiel/games/tic_tac_toe/tic_tac_toe.h
open_spiel/games/tic_tac_toe/tic_tac_toe.cc