open spiel: open_spiel::bridge_uncontested_bidding::Deal Class Reference
open_spiel::bridge_uncontested_bidding::Deal Class Reference
#include <bridge_uncontested_bidding.h>
Public Member Functions
Deal ()
void Shuffle (std::mt19937 *rng, int begin=0, int end=kNumCards)
Deal (const std::array< int, kNumCards > &cards)
int Card (int i) const
int Suit (int i) const
int Rank (int i) const
std::string HandString (int begin, int end) const
Detailed Description
Definition at line 119 of file bridge_uncontested_bidding.h.
Constructor & Destructor Documentation
Deal() [1/2]
open_spiel::bridge_uncontested_bidding::Deal::Deal () inline
Definition at line 121 of file bridge_uncontested_bidding.h.
{ std::iota(std::begin(cards_), std::end(cards_), 0); }
Deal() [2/2]
open_spiel::bridge_uncontested_bidding::Deal::Deal (const std::array< int, kNumCards > & cards) inline
Definition at line 131 of file bridge_uncontested_bidding.h.
: cards_(cards) {}
Member Function Documentation
Card()
int open_spiel::bridge_uncontested_bidding::Deal::Card (int i) const inline
Definition at line 132 of file bridge_uncontested_bidding.h.
{ return cards_[i]; }
References i.
Referenced by open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::InformationStateTensor().
HandString()
std::string open_spiel::bridge_uncontested_bidding::Deal::HandString (int begin, int end) const
Definition at line 127 of file bridge_uncontested_bidding.cc.
{
  bool cards[kNumSuits][kNumCardsPerSuit] = {{false}};
  for (int i = begin; i < end; ++i) {
    cards[Suit(i)][Rank(i)] = true;
  }
  std::string hand;
  for (int s = 3; s >= 0; --s) {
    for (int r = 12; r >= 0; --r) {
      if (cards[s][r]) {
        hand.push_back(kRankChar[r]);
      }
    }
    if (s) hand.push_back('.');
  }
  return hand;
}
References end, i, open_spiel::bridge_uncontested_bidding::kNumCardsPerSuit, open_spiel::bridge_uncontested_bidding::kNumSuits, open_spiel::bridge_uncontested_bidding::kRankChar, r, Rank(), and Suit().
Referenced by open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::InformationStateString(), and open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::ToString().
Rank()
int open_spiel::bridge_uncontested_bidding::Deal::Rank (int i) const inline
Definition at line 134 of file bridge_uncontested_bidding.h.
{ return cards_[i] / kNumSuits; }
References i, and open_spiel::bridge_uncontested_bidding::kNumSuits.
Referenced by HandString(), and open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::ScoreDeal().
Shuffle()
void open_spiel::bridge_uncontested_bidding::Deal::Shuffle (std::mt19937 * rng, int begin = 0, int end = kNumCards) inline
Definition at line 122 of file bridge_uncontested_bidding.h.
{
    for (int i = begin; i < end - 1; ++i) {
      // We don't use absl::uniform_int_distribution because it behaves
      // differently in different versions of C++, and we want reproducible
      // tests.
      int j = i + (*rng)() % (end - i);
      std::swap(cards_[i], cards_[j]);
    }
  }
References i.
Referenced by open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::DoApplyAction(), and open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::ScoreDeal().
Suit()
int open_spiel::bridge_uncontested_bidding::Deal::Suit (int i) const inline
Definition at line 133 of file bridge_uncontested_bidding.h.
{ return cards_[i] % kNumSuits; }
References i, and open_spiel::bridge_uncontested_bidding::kNumSuits.
Referenced by HandString(), and open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::ScoreDeal().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/bridge_uncontested_bidding.h
open_spiel/games/bridge/bridge_uncontested_bidding.cc