open spiel: absl::CordTestPeer Class Reference
absl::CordTestPeer Class Reference
Static Public Member Functions
static void ForEachChunk (const Cord &c, absl::FunctionRef< void(absl::string_view)> callback)
static bool IsTree (const Cord &c)
static CordRep * Tree (const Cord &c)
static cord_internal::CordzInfo * GetCordzInfo (const Cord &c)
static Cord MakeSubstring (Cord src, size_t offset, size_t length)
Detailed Description
Definition at line 196 of file cord_test.cc.
Member Function Documentation
ForEachChunk()
static void absl::CordTestPeer::ForEachChunk (const Cord & c, absl::FunctionRef< void(absl::string_view)> callback) inline static
Definition at line 198 of file cord_test.cc.
{
    c.ForEachChunk(callback);
  }
References absl::c.
Referenced by TEST_P().
GetCordzInfo()
static cord_internal::CordzInfo * absl::CordTestPeer::GetCordzInfo (const Cord & c) inline static
Definition at line 206 of file cord_test.cc.
{
    return c.contents_.cordz_info();
  }
References absl::c.
IsTree()
static bool absl::CordTestPeer::IsTree (const Cord & c) inline static
Definition at line 203 of file cord_test.cc.
{ return c.contents_.is_tree(); }
References absl::c.
Referenced by TestConstinitConstructor().
MakeSubstring()
static Cord absl::CordTestPeer::MakeSubstring (Cord src, size_t offset, size_t length) inline static
Definition at line 210 of file cord_test.cc.
{
    ABSL_RAW_CHECK(src.contents_.is_tree(), "Can not be inlined");
    ABSL_RAW_CHECK(src.ExpectedChecksum() == absl::nullopt,
                   "Can not be hardened");
    Cord cord;
    auto* tree = cord_internal::SkipCrcNode(src.contents_.tree());
    auto* rep = CordRepSubstring::Create(CordRep::Ref(tree), offset, length);
    cord.contents_.EmplaceTree(rep, CordzUpdateTracker::kSubCord);
    return cord;
  }
References ABSL_RAW_CHECK, absl::Cord::ExpectedChecksum(), rep, and absl::cord_internal::SkipCrcNode().
Referenced by TEST_P(), and TEST_P().
Tree()
static CordRep * absl::CordTestPeer::Tree (const Cord & c) inline static
Definition at line 204 of file cord_test.cc.
{ return c.contents_.tree(); }
References absl::c.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/cord_test.cc