open spiel: absl::LogEntry Class Reference
absl::LogEntry Class Reference final
#include <log_entry.h>
Public Types
using tid_t = log_internal::Tid
Public Member Functions
LogEntry (const LogEntry &)=delete
LogEntry & operator= (const LogEntry &)=delete
absl::string_view source_filename () const ABSL_ATTRIBUTE_LIFETIME_BOUND
absl::string_view source_basename () const ABSL_ATTRIBUTE_LIFETIME_BOUND
int source_line () const
bool prefix () const
absl::LogSeverity log_severity () const
int verbosity () const
absl::Time timestamp () const
tid_t tid () const
absl::string_view text_message_with_prefix_and_newline () const ABSL_ATTRIBUTE_LIFETIME_BOUND
absl::string_view text_message_with_prefix () const ABSL_ATTRIBUTE_LIFETIME_BOUND
absl::string_view text_message_with_newline () const ABSL_ATTRIBUTE_LIFETIME_BOUND
absl::string_view text_message () const ABSL_ATTRIBUTE_LIFETIME_BOUND
const char * text_message_with_prefix_and_newline_c_str () const ABSL_ATTRIBUTE_LIFETIME_BOUND
absl::string_view encoded_message () const ABSL_ATTRIBUTE_LIFETIME_BOUND
absl::string_view stacktrace () const ABSL_ATTRIBUTE_LIFETIME_BOUND
Static Public Attributes
static constexpr int kNoVerbosityLevel = -1
static constexpr int kNoVerboseLevel = -1
Friends
class log_internal::LogEntryTestPeer
class log_internal::LogMessage
Detailed Description
Definition at line 53 of file log_entry.h.
Member Typedef Documentation
tid_t
using absl::LogEntry::tid_t = log_internal::Tid
Definition at line 55 of file log_entry.h.
Constructor & Destructor Documentation
LogEntry()
absl::LogEntry::LogEntry (const LogEntry &) delete
Member Function Documentation
encoded_message()
absl::string_view absl::LogEntry::encoded_message () const inline
Definition at line 177 of file log_entry.h.
{
    return encoding_;
  }
Referenced by absl::log_internal::WriteEntryToStderr::operator()(), and absl::log_internal::RawEncodedMessage().
log_severity()
absl::LogSeverity absl::LogEntry::log_severity () const inline
Definition at line 94 of file log_entry.h.
{ return severity_; }
Referenced by absl::log_internal::LogEntryTestPeer::FormatLogMessage(), absl::log_internal::LogEntryTestPeer::FormatPrefixIntoSizedBuffer(), absl::log_internal::LogEntryTestPeer::LogEntryTestPeer(), absl::log_internal::LogSeverity(), absl::log_internal::WriteEntryToStderr::operator()(), and absl::ScopedMockLog::ScopedMockLog().
operator=()
LogEntry & absl::LogEntry::operator= (const LogEntry &) delete
prefix()
bool absl::LogEntry::prefix () const inline
Definition at line 88 of file log_entry.h.
{ return prefix_; }
Referenced by absl::log_internal::WriteEntryToStderr::operator()(), and absl::log_internal::Prefix().
source_basename()
absl::string_view absl::LogEntry::source_basename () const inline
Definition at line 78 of file log_entry.h.
{
    return base_filename_;
  }
Referenced by absl::log_internal::LogEntryTestPeer::FormatLogMessage(), absl::log_internal::LogEntryTestPeer::FormatPrefixIntoSizedBuffer(), absl::log_internal::LogEntryTestPeer::LogEntryTestPeer(), absl::log_internal::WriteEntryToStderr::operator()(), and absl::log_internal::SourceBasename().
source_filename()
absl::string_view absl::LogEntry::source_filename () const inline
Definition at line 75 of file log_entry.h.
{
    return full_filename_;
  }
Referenced by absl::log_internal::WriteEntryToStderr::operator()(), absl::log_internal::WriteToStderrWithFilename::operator()(), absl::ScopedMockLog::ScopedMockLog(), and absl::log_internal::SourceFilename().
source_line()
int absl::LogEntry::source_line () const inline
Definition at line 81 of file log_entry.h.
{ return line_; }
Referenced by absl::log_internal::LogEntryTestPeer::FormatLogMessage(), absl::log_internal::LogEntryTestPeer::FormatPrefixIntoSizedBuffer(), absl::log_internal::LogEntryTestPeer::LogEntryTestPeer(), absl::log_internal::WriteEntryToStderr::operator()(), and absl::log_internal::SourceLine().
stacktrace()
absl::string_view absl::LogEntry::stacktrace () const inline
Definition at line 193 of file log_entry.h.
{
    return stacktrace_;
  }
Referenced by absl::log_internal::Stacktrace().
text_message()
absl::string_view absl::LogEntry::text_message () const inline
Definition at line 162 of file log_entry.h.
{
    return absl::string_view(
        text_message_with_prefix_and_newline_and_nul_.data() + prefix_len_,
        text_message_with_prefix_and_newline_and_nul_.size() - prefix_len_ - 2);
  }
References absl::Span< T >::data(), and absl::Span< T >::size().
Referenced by absl::log_internal::LogEntryTestPeer::FormatLogMessage(), absl::log_internal::WriteEntryToStderr::operator()(), absl::ScopedMockLog::ScopedMockLog(), absl::log_internal::TextMessage(), and absl::log_internal::TextPrefix().
text_message_with_newline()
absl::string_view absl::LogEntry::text_message_with_newline () const inline
Definition at line 156 of file log_entry.h.
{
    return absl::string_view(
        text_message_with_prefix_and_newline_and_nul_.data() + prefix_len_,
        text_message_with_prefix_and_newline_and_nul_.size() - prefix_len_ - 1);
  }
References absl::Span< T >::data(), and absl::Span< T >::size().
text_message_with_prefix()
absl::string_view absl::LogEntry::text_message_with_prefix () const inline
Definition at line 150 of file log_entry.h.
{
    return absl::string_view(
        text_message_with_prefix_and_newline_and_nul_.data(),
        text_message_with_prefix_and_newline_and_nul_.size() - 2);
  }
References absl::Span< T >::data(), and absl::Span< T >::size().
Referenced by absl::log_internal::TextMessageWithPrefix(), and absl::log_internal::TextPrefix().
text_message_with_prefix_and_newline()
absl::string_view absl::LogEntry::text_message_with_prefix_and_newline () const inline
Definition at line 144 of file log_entry.h.
{
    return absl::string_view(
        text_message_with_prefix_and_newline_and_nul_.data(),
        text_message_with_prefix_and_newline_and_nul_.size() - 1);
  }
References absl::Span< T >::data(), and absl::Span< T >::size().
Referenced by absl::log_internal::TextMessageWithPrefixAndNewline().
text_message_with_prefix_and_newline_c_str()
const char * absl::LogEntry::text_message_with_prefix_and_newline_c_str () const inline
Definition at line 167 of file log_entry.h.
{
    return text_message_with_prefix_and_newline_and_nul_.data();
  }
References absl::Span< T >::data().
tid()
tid_t absl::LogEntry::tid () const inline
Definition at line 120 of file log_entry.h.
{ return tid_; }
Referenced by absl::log_internal::LogEntryTestPeer::FormatLogMessage(), absl::log_internal::LogEntryTestPeer::FormatPrefixIntoSizedBuffer(), absl::log_internal::LogEntryTestPeer::LogEntryTestPeer(), and absl::log_internal::ThreadID().
timestamp()
absl::Time absl::LogEntry::timestamp () const inline
Definition at line 111 of file log_entry.h.
{ return timestamp_; }
Referenced by absl::log_internal::LogEntryTestPeer::FormatPrefixIntoSizedBuffer(), absl::log_internal::LogEntryTestPeer::LogEntryTestPeer(), absl::log_internal::WriteEntryToStderr::operator()(), absl::log_internal::Timestamp(), and absl::log_internal::TimestampInMatchWindow().
verbosity()
int absl::LogEntry::verbosity () const inline
Definition at line 100 of file log_entry.h.
{ return verbose_level_; }
Referenced by absl::log_internal::WriteEntryToStderr::operator()(), and absl::log_internal::Verbosity().
Friends And Related Symbol Documentation
log_internal::LogEntryTestPeer
friend class log_internal::LogEntryTestPeer friend
Definition at line 213 of file log_entry.h.
log_internal::LogMessage
friend class log_internal::LogMessage friend
Definition at line 214 of file log_entry.h.
Member Data Documentation
kNoVerboseLevel
int absl::LogEntry::kNoVerboseLevel = -1 static constexpr
Definition at line 59 of file log_entry.h.
kNoVerbosityLevel
int absl::LogEntry::kNoVerbosityLevel = -1 static constexpr
Definition at line 58 of file log_entry.h.
Referenced by absl::log_internal::LogMessage::LogMessageData::LogMessageData(), absl_log_internal::TEST_P(), absl_log_internal::TEST_P(), absl_log_internal::TEST_P(), absl_log_internal::TEST_P(), and absl::log_internal::LogMessage::WithVerbosity().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/log/log_entry.h