open spiel: Timer Class Reference
Timer Class Reference
#include <Timer.h>
Public Member Functions
Timer ()
~Timer ()
void Reset ()
void SetName (const string &nameIn)
void Start ()
void End ()
bool Used () const
int UserTime () const
void operator+= (const Timer &add)
void operator-= (const Timer &deduct)
string SumLine (const Timer &divisor, const string &bname="") const
string DetailLine () const
Detailed Description
Definition at line 22 of file Timer.h.
Constructor & Destructor Documentation
Timer()
Timer::Timer ()
Definition at line 21 of file Timer.cpp.
{
  Timer::Reset();
}
References Reset().
~Timer()
Timer::~Timer ()
Definition at line 27 of file Timer.cpp.
{
}
Member Function Documentation
DetailLine()
string Timer::DetailLine () const
Definition at line 139 of file Timer.cpp.
{
  stringstream ss;
  ss << setw(15) << left << name <<
    setw(10) << right << count <<
    setw(11) << right << userCum <<
    setw(11) << setprecision(2) << fixed <<
      userCum / static_cast<double>(count) <<
    setw(11) << setprecision(0) << fixed <<
      1000000 * systCum / static_cast<double>(CLOCKS_PER_SEC) <<
    setw(11) << setprecision(2) << fixed <<
      1000000 * systCum /
        static_cast<double>(count * CLOCKS_PER_SEC) << "\n";
  return ss.str();
}
End()
void Timer::End ()
Definition at line 54 of file Timer.cpp.
{
  time_point<Clock> user1 = Clock::now();
  clock_t syst1 = clock();
  chrono::duration<double, micro> d = user1 - user0;
  int tuser = static_cast<int>(d.count());
  count++;
  userCum += tuser;
  systCum += static_cast<long>(syst1) -
    static_cast<long>(syst0);
}
operator+=()
void Timer::operator+= (const Timer & add)
Definition at line 81 of file Timer.cpp.
{
  count += add.count;
  userCum += add.userCum;
  systCum += add.systCum;
}
operator-=()
void Timer::operator-= (const Timer & deduct)
Definition at line 89 of file Timer.cpp.
{
  if (deduct.userCum > userCum)
    userCum = 0;
  else
    userCum -= deduct.userCum;
  if (deduct.systCum > systCum)
    systCum = 0;
  else
    systCum -= deduct.systCum;
}
Reset()
void Timer::Reset ()
Definition at line 32 of file Timer.cpp.
{
  name = "";
  count = 0;
  userCum = 0;
  systCum = 0;
}
Referenced by Timer().
SetName()
void Timer::SetName (const string & nameIn)
Definition at line 41 of file Timer.cpp.
{
  name = nameIn;
}
Referenced by TimerList::PrintStats().
Start()
void Timer::Start ()
Definition at line 47 of file Timer.cpp.
{
  user0 = Clock::now();
  syst0 = clock();
}
SumLine()
string Timer::SumLine (const Timer & divisor, const string & bname = "") const
Definition at line 103 of file Timer.cpp.
{
  stringstream ss;
  if (count > 0)
  {
    ss << setw(14) << left << (bname == "" ? name : bname) <<
      setw(9) << right << count <<
      setw(11) << userCum <<
      setw(7) << setprecision(2) << fixed <<
        userCum / static_cast<double>(count) <<
      setw(5) << setprecision(1) << fixed <<
        100. * userCum / divisor.userCum <<
      setw(11) << setprecision(0) << fixed <<
        1000000 * systCum / static_cast<double>(CLOCKS_PER_SEC) <<
      setw(7) << setprecision(2) << fixed <<
        1000000 * systCum / static_cast<double>(count * CLOCKS_PER_SEC) <<
      setw(5) << setprecision(1) << fixed <<
        100. * systCum / divisor.systCum << "\n";
  }
  else
  {
    ss << setw(14) << left << (bname == "" ? name : bname) <<
      setw(9) << right << count <<
      setw(11) << userCum <<
      setw(7) << "-" <<
      setw(5) << "-" <<
      setw(11) << 1000000 * systCum / static_cast<double>(CLOCKS_PER_SEC) <<
      setw(7) << "-" <<
      setw(5) << "-" << "\n";
  }
  return ss.str();
}
Referenced by TimerList::PrintStats(), and TimerGroup::SumLine().
Used()
bool Timer::Used () const
Definition at line 69 of file Timer.cpp.
{
  return (count > 0);
}
UserTime()
int Timer::UserTime () const
Definition at line 75 of file Timer.cpp.
{
  return static_cast<int>(userCum);
}
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/Timer.h
open_spiel/games/bridge/double_dummy_solver/src/Timer.cpp