open spiel: dds::File Class Reference
dds::File Class Reference
#include <File.h>
Classes
class FileImpl
Public Member Functions
File ()
~File ()
void Reset ()
void SetName (const string &fnameIn)
ofstream & GetStream ()
void Close ()
Detailed Description
Definition at line 19 of file File.h.
Constructor & Destructor Documentation
File()
File::File ()
Definition at line 17 of file File.cpp.
{
  File::Reset();
}
References Reset().
~File()
File::~File ()
Definition at line 23 of file File.cpp.
{
  File::Close();
}
References Close().
Member Function Documentation
Close()
void File::Close ()
Definition at line 55 of file File.cpp.
{
  if (fileOpen)
  {
    fout.close();
    fileOpen = false;
  }
}
Referenced by ~File().
GetStream()
ofstream & File::GetStream ()
Definition at line 43 of file File.cpp.
{
  if (! fileOpen)
  {
    fout.open(fname);
    fileOpen = true;
  }
  return fout;
}
Reset()
void File::Reset ()
Definition at line 29 of file File.cpp.
{
  fname = "";
  fileOpen = false;
}
Referenced by File().
SetName()
void File::SetName (const string & fnameIn)
Definition at line 36 of file File.cpp.
{
  // No error checking!
  fname =  fnameIn;
}
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/File.h
open_spiel/games/bridge/double_dummy_solver/src/File.cpp