open spiel: absl::strings_internal::Splitter< Delimiter, Predicate, StringType > Class Template Reference
absl::strings_internal::Splitter< Delimiter, Predicate, StringType > Class Template Reference
#include <str_split_internal.h>
Public Types
using DelimiterType = Delimiter
using PredicateType = Predicate
using const_iterator = strings_internal::SplitIterator<Splitter>
using value_type = typename std::iterator_traits<const_iterator>::value_type
Public Member Functions
Splitter (StringType input_text, Delimiter d, Predicate p)
absl::string_view text () const
const Delimiter & delimiter () const
const Predicate & predicate () const
const_iterator begin () const
const_iterator end () const
template<typename Container , typename = typename std::enable_if< SplitterIsConvertibleTo<Container>::value>::type>
operator Container () const
template<typename First , typename Second >
operator std::pair< First, Second > () const
Detailed Description
template<typename Delimiter, typename Predicate, typename StringType>
class absl::strings_internal::Splitter< Delimiter, Predicate, StringType >
Definition at line 260 of file str_split_internal.h.
Member Typedef Documentation
const_iterator
template<typename Delimiter , typename Predicate , typename StringType > using absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::const_iterator = strings_internal::SplitIterator<Splitter>
Definition at line 264 of file str_split_internal.h.
DelimiterType
template<typename Delimiter , typename Predicate , typename StringType > using absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::DelimiterType = Delimiter
Definition at line 262 of file str_split_internal.h.
PredicateType
template<typename Delimiter , typename Predicate , typename StringType > using absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::PredicateType = Predicate
Definition at line 263 of file str_split_internal.h.
value_type
template<typename Delimiter , typename Predicate , typename StringType > using absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::value_type = typename std::iterator_traits<const_iterator>::value_type
Definition at line 265 of file str_split_internal.h.
Constructor & Destructor Documentation
Splitter()
template<typename Delimiter , typename Predicate , typename StringType > absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::Splitter (StringType input_text, Delimiter d, Predicate p) inline
Definition at line 267 of file str_split_internal.h.
      : text_(std::move(input_text)),
        delimiter_(std::move(d)),
        predicate_(std::move(p)) {}
Member Function Documentation
begin()
template<typename Delimiter , typename Predicate , typename StringType > const_iterator absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::begin () const inline
Definition at line 279 of file str_split_internal.h.
{ return {const_iterator::kInitState, this}; }
References absl::strings_internal::SplitIterator< Splitter >::kInitState.
Referenced by absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::operator std::pair< First, Second >().
delimiter()
template<typename Delimiter , typename Predicate , typename StringType > const Delimiter & absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::delimiter () const inline
Definition at line 273 of file str_split_internal.h.
{ return delimiter_; }
end()
template<typename Delimiter , typename Predicate , typename StringType > const_iterator absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::end () const inline
Definition at line 280 of file str_split_internal.h.
{ return {const_iterator::kEndState, this}; }
References absl::strings_internal::SplitIterator< Splitter >::kEndState.
Referenced by absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::operator std::pair< First, Second >().
operator Container()
template<typename Delimiter , typename Predicate , typename StringType > template<typename Container , typename = typename std::enable_if< SplitterIsConvertibleTo<Container>::value>::type> absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::operator Container () const inline
Definition at line 287 of file str_split_internal.h.
                             {  // NOLINT(runtime/explicit)
    return ConvertToContainer<Container, typename Container::value_type,
                              HasMappedType<Container>::value>()(*this);
  }
operator std::pair< First, Second >()
template<typename Delimiter , typename Predicate , typename StringType > template<typename First , typename Second > absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::operator std::pair< First, Second > () const inline
Definition at line 297 of file str_split_internal.h.
                                          {  // NOLINT(runtime/explicit)
    absl::string_view first, second;
    auto it = begin();
    if (it != end()) {
      first = *it;
      if (++it != end()) {
        second = *it;
      }
    }
    return {First(first), Second(second)};
  }
References absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::begin(), absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::end(), and first.
predicate()
template<typename Delimiter , typename Predicate , typename StringType > const Predicate & absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::predicate () const inline
Definition at line 274 of file str_split_internal.h.
{ return predicate_; }
text()
template<typename Delimiter , typename Predicate , typename StringType > absl::string_view absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::text () const inline
Definition at line 272 of file str_split_internal.h.
{ return text_; }
Referenced by absl::strings_internal::SplitIterator< Splitter >::operator++(), and absl::strings_internal::SplitIterator< Splitter >::SplitIterator().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/str_split_internal.h