open spiel: open_spiel::EFGWriter Class Reference
open_spiel::EFGWriter Class Reference
#include <efg_writer.h>
Public Member Functions
EFGWriter (const Game &game, const std::string filename, bool action_names=true, bool separate_infostate_numbers=true)
void Write ()
Detailed Description
Definition at line 34 of file efg_writer.h.
Constructor & Destructor Documentation
EFGWriter()
open_spiel::EFGWriter::EFGWriter (const Game & game, const std::string filename, bool action_names = true, bool separate_infostate_numbers = true)
Definition at line 26 of file efg_writer.cc.
    : game_(game),
      filename_(filename),
      action_names_(action_names),
      separate_infostate_numbers_(separate_infostate_numbers),
      // Node indices start at 1.
      chance_node_counter_(1),
      terminal_node_counter_(1) {
  const auto& info = game_.GetType();
  SPIEL_CHECK_EQ(info.dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(info.reward_model, GameType::RewardModel::kTerminal);
  SPIEL_CHECK_NE(info.chance_mode, GameType::ChanceMode::kSampledStochastic);
}
References open_spiel::Game::GetType(), open_spiel::GameType::kSampledStochastic, open_spiel::GameType::kSequential, open_spiel::GameType::kTerminal, SPIEL_CHECK_EQ, and SPIEL_CHECK_NE.
Member Function Documentation
Write()
void open_spiel::EFGWriter::Write ()
Definition at line 41 of file efg_writer.cc.
                      {
  std::ofstream efg_file(filename_);
  efg_file << "EFG 2 R";
  GameParameters params = game_.GetParameters();
  efg_file << " \"" << game_.ToString() << "\" { ";
  for (int i = 1; i <= game_.NumPlayers(); i++) {
    // EFG player index starts at 1.
    efg_file << '"' << "Player " << i << "\" ";
    infostate_numbers_.push_back(std::map<std::string, int>());
  }
  efg_file << "}\n";
  // Get the root state.
  Write(efg_file, *game_.NewInitialState());
  efg_file.close();
}
References open_spiel::Game::GetParameters(), i, open_spiel::Game::NewInitialState(), open_spiel::Game::NumPlayers(), open_spiel::Game::ToString(), and Write().
Referenced by Write(), and open_spiel::WriteAndLoadGame().
The documentation for this class was generated from the following files:
open_spiel/game_transforms/efg_writer.h
open_spiel/game_transforms/efg_writer.cc