open spiel: open_spiel::twenty_forty_eight::TwentyFortyEightState Class Reference
open_spiel::twenty_forty_eight::TwentyFortyEightState Class Reference
#include <2048.h>
Public Member Functions
TwentyFortyEightState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< double > Rewards () const override
std::vector< Action > LegalActions () const override
ActionsAndProbs ChanceOutcomes () const override
Tile BoardAt (int row, int column) const
Tile BoardAt (Coordinate coordinate) const
void SetCustomBoard (const std::vector< int > &board_seq)
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 79 of file 2048.h.
Constructor & Destructor Documentation
TwentyFortyEightState()
open_spiel::twenty_forty_eight::TwentyFortyEightState::TwentyFortyEightState (std::shared_ptr< const Game > game) explicit
Definition at line 77 of file 2048.cc.
    : State(game),
      parent_game_(open_spiel::down_cast<const TwentyFortyEightGame&>(*game)),
      board_(std::vector<Tile>(kRows * kColumns)) {}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::twenty_forty_eight::TwentyFortyEightState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 252 of file 2048.cc.
{
  if (player == kChancePlayerId) {
    if (action_id == kNoCellAvailableAction) {
      return "No Cell Available";
    }
    ChanceAction chance_action = SpielActionToChanceAction(action_id);
    return absl::StrCat(chance_action.is_four ? 4 : 2, " added to row ",
                        chance_action.row + 1, ", column ",
                        chance_action.column + 1);
  }
  switch (action_id) {
    case kMoveUp:
      return "Up";
    case kMoveRight:
      return "Right";
    case kMoveDown:
      return "Down";
    case kMoveLeft:
      return "Left";
    default:
      return "Invalid action";
  }
}
References open_spiel::twenty_forty_eight::ChanceAction::column, open_spiel::twenty_forty_eight::ChanceAction::is_four, open_spiel::kChancePlayerId, open_spiel::twenty_forty_eight::kMoveDown, open_spiel::twenty_forty_eight::kMoveLeft, open_spiel::twenty_forty_eight::kMoveRight, open_spiel::twenty_forty_eight::kMoveUp, open_spiel::twenty_forty_eight::kNoCellAvailableAction, player, open_spiel::twenty_forty_eight::ChanceAction::row, and absl::StrCat().
BoardAt() [1/2]
Tile open_spiel::twenty_forty_eight::TwentyFortyEightState::BoardAt (Coordinate coordinate) const inline
Definition at line 104 of file 2048.h.
{
    return board_[coordinate.row * kColumns + coordinate.column];
  }
References open_spiel::twenty_forty_eight::Coordinate::column, open_spiel::twenty_forty_eight::kColumns, and open_spiel::twenty_forty_eight::Coordinate::row.
BoardAt() [2/2]
Tile open_spiel::twenty_forty_eight::TwentyFortyEightState::BoardAt (int row, int column) const inline
Definition at line 101 of file 2048.h.
{
    return board_[row * kColumns + column];
  }
References open_spiel::twenty_forty_eight::kColumns.
Referenced by ChanceOutcomes(), DoApplyAction(), IsTerminal(), ObservationTensor(), and ToString().
ChanceOutcomes()
ActionsAndProbs open_spiel::twenty_forty_eight::TwentyFortyEightState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 289 of file 2048.cc.
{
  int count = AvailableCellCount();
  if (count == 0) {
    return {{kNoCellAvailableAction, 1.0}};
  }
  ActionsAndProbs action_and_probs;
  action_and_probs.reserve(count * 2);
  for (int r = 0; r < kRows; r++) {
    for (int c = 0; c < kColumns; c++) {
      if (BoardAt(r, c).value == 0) {
        // 2 appearing randomly on the board should be 9 times as likely as a 4.
        action_and_probs.emplace_back(
            ChanceActionToSpielAction(ChanceAction(r, c, false)), .9 / count);
        action_and_probs.emplace_back(
            ChanceActionToSpielAction(ChanceAction(r, c, true)), .1 / count);
      }
    }
  }
  return action_and_probs;
}
References BoardAt(), open_spiel::twenty_forty_eight::kColumns, open_spiel::twenty_forty_eight::kNoCellAvailableAction, open_spiel::twenty_forty_eight::kRows, and r.
Clone()
std::unique_ptr< State > open_spiel::twenty_forty_eight::TwentyFortyEightState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 93 of file 2048.h.
{
    return std::unique_ptr<State>(new TwentyFortyEightState(*this));
  }
References TwentyFortyEightState().
CurrentPlayer()
Player open_spiel::twenty_forty_eight::TwentyFortyEightState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 82 of file 2048.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::twenty_forty_eight::TwentyFortyEightState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 176 of file 2048.cc.
{
  if (IsChanceNode()) {
    // The original 2048 game starts with two random tiles. To achieve this,
    // an extra move is given to the chance player during the beginning of the
    // game.
    if (!extra_chance_turn_) {
      current_player_ = 0;
    }
    extra_chance_turn_ = false;
    if (action == kNoCellAvailableAction) {
      return;
    }
    ChanceAction chance_action = SpielActionToChanceAction(action);
    SetBoard(
        chance_action.row, chance_action.column,
        Tile(chance_action.is_four ? kChanceTiles[1] : kChanceTiles[0], false));
    return;
  }
  action_score_ = 0;
  const std::array<std::array<int, 4>, 2>& traversals = kTraversals[action];
  PrepareTiles();
  for (int r : traversals[0]) {
    for (int c : traversals[1]) {
      int tile = GetCellContent(r, c);
      if (tile > 0) {
        bool moved = false;
        std::array<Coordinate, 2> positions =
            FindFarthestPosition(r, c, action);
        Coordinate farthest_pos = positions[0];
        Coordinate next_pos = positions[1];
        int next_cell = GetCellContent(next_pos.row, next_pos.column);
        if (next_cell > 0 && next_cell == tile &&
            !BoardAt(next_pos).is_merged) {
          int merged = tile * 2;
          action_score_ += merged;
          SetBoard(next_pos.row, next_pos.column, Tile(merged, true));
          moved = true;
        } else if (farthest_pos.row != r || farthest_pos.column != c) {
          SetBoard(farthest_pos.row, farthest_pos.column, Tile(tile, false));
          moved = true;
        }
        if (moved) {
          SetBoard(r, c, Tile(0, false));
          current_player_ = kChancePlayerId;
        }
      }
    }
  }
  total_score_ += action_score_;
  total_actions_++;
}
References action, BoardAt(), open_spiel::twenty_forty_eight::ChanceAction::column, open_spiel::twenty_forty_eight::Coordinate::column, open_spiel::twenty_forty_eight::ChanceAction::is_four, open_spiel::State::IsChanceNode(), open_spiel::kChancePlayerId, open_spiel::twenty_forty_eight::kChanceTiles, open_spiel::twenty_forty_eight::kNoCellAvailableAction, r, open_spiel::twenty_forty_eight::ChanceAction::row, and open_spiel::twenty_forty_eight::Coordinate::row.
InformationStateString()
std::string open_spiel::twenty_forty_eight::TwentyFortyEightState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 384 of file 2048.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::twenty_forty_eight::TwentyFortyEightState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 342 of file 2048.cc.
{
  if (move_number_ >= parent_game_.MaxGameLength()) {
    return true;
  }
  // Scan the board.
  int count = 0;
  int tile_matches_available = 0;
  for (int r = 0; r < kRows; r++) {
    for (int c = 0; c < kColumns; c++) {
      // Check for 2048, if necessary,
      if (BoardAt(r, c).value == parent_game_.max_tile()) {
        return true;
      }
      // Check for increase of available cell count.
      if (BoardAt(r, c).value == 0) {
        count++;
      }
      // Check for tile matches.
      if (TileMatchAvailable(r, c)) {
        tile_matches_available++;
      }
    }
  }
  if (count == 0 && tile_matches_available == 0) {
    return true;
  } else {
    return false;
  }
}
References BoardAt(), open_spiel::twenty_forty_eight::kColumns, open_spiel::twenty_forty_eight::kRows, open_spiel::twenty_forty_eight::TwentyFortyEightGame::max_tile(), open_spiel::twenty_forty_eight::TwentyFortyEightGame::MaxGameLength(), open_spiel::State::move_number_, and r.
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::twenty_forty_eight::TwentyFortyEightState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 310 of file 2048.cc.
{
  if (IsTerminal()) {
    return {};
  }
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  }
  // Construct a vector from the array.
  std::vector<Action> actions =
      std::vector<Action>(kPlayerActions.begin(), kPlayerActions.end());
  std::vector<Action> actions_allowed = {};
  for (Action action : actions) {
    if (DoesActionChangeBoard(action)) actions_allowed.push_back(action);
  }
  return actions_allowed;
}
References action, open_spiel::State::IsChanceNode(), IsTerminal(), and open_spiel::State::LegalChanceOutcomes().
ObservationString()
std::string open_spiel::twenty_forty_eight::TwentyFortyEightState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 390 of file 2048.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::twenty_forty_eight::TwentyFortyEightState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 396 of file 2048.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<2> view(values, {kRows, kColumns}, true);
  for (int row = 0; row < kRows; row++) {
    for (int column = 0; column < kColumns; column++) {
      view[{row, column}] = BoardAt(row, column).value;
    }
  }
}
References BoardAt(), open_spiel::twenty_forty_eight::kColumns, open_spiel::twenty_forty_eight::kRows, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::twenty_forty_eight::Tile::value, and values.
Returns()
std::vector< double > open_spiel::twenty_forty_eight::TwentyFortyEightState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 380 of file 2048.cc.
{
  return {static_cast<double>(total_score_)};
}
Rewards()
std::vector< double > open_spiel::twenty_forty_eight::TwentyFortyEightState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 376 of file 2048.cc.
{
  return {static_cast<double>(action_score_)};
}
SetCustomBoard()
void open_spiel::twenty_forty_eight::TwentyFortyEightState::SetCustomBoard (const std::vector< int > & board_seq)
Definition at line 82 of file 2048.cc.
{
  current_player_ = 0;
  for (int r = 0; r < kRows; r++) {
    for (int c = 0; c < kColumns; c++) {
      SetBoard(r, c, Tile(board_seq[r * kColumns + c], false));
    }
  }
}
References open_spiel::twenty_forty_eight::kColumns, open_spiel::twenty_forty_eight::kRows, and r.
ToString()
std::string open_spiel::twenty_forty_eight::TwentyFortyEightState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 329 of file 2048.cc.
{
  std::string str;
  for (int r = 0; r < kRows; ++r) {
    for (int c = 0; c < kColumns; ++c) {
      std::string tile = std::to_string(BoardAt(r, c).value);
      absl::StrAppend(&str, std::string(5 - tile.length(), ' '));
      absl::StrAppend(&str, tile);
    }
    absl::StrAppend(&str, "\n");
  }
  return str;
}
References BoardAt(), open_spiel::twenty_forty_eight::kColumns, open_spiel::twenty_forty_eight::kRows, r, and absl::StrAppend().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/twenty_forty_eight/2048.h
open_spiel/games/twenty_forty_eight/2048.cc