open spiel: absl::container_internal::CompressedTuple< Ts > Class Template Reference
absl::container_internal::CompressedTuple< Ts > Class Template Reference
#include <compressed_tuple.h>
Public Member Functions
constexpr CompressedTuple ()=default
constexpr CompressedTuple (const Ts &... base)
template<typename First , typename... Vs, absl::enable_if_t< absl::conjunction< absl::negation< std::is_same< void(CompressedTuple), void(absl::decay_t< First >)> >, internal_compressed_tuple::TupleItemsMoveConstructible< CompressedTuple< Ts... >, First, Vs... > >::value , bool >
constexpr CompressedTuple (First &&first, Vs &&... base)
template<int I>
ElemT< I > & get () &
template<int I>
constexpr const ElemT< I > & get () const &
template<int I>
ElemT< I > && get () &&
template<int I>
constexpr const ElemT< I > && get () const &&
Detailed Description
template<typename... Ts>
class absl::container_internal::CompressedTuple< Ts >
Definition at line 221 of file compressed_tuple.h.
Constructor & Destructor Documentation
CompressedTuple() [1/3]
template<typename... Ts> absl::container_internal::CompressedTuple< Ts >::CompressedTuple () constexpr default
CompressedTuple() [2/3]
template<typename... Ts> absl::container_internal::CompressedTuple< Ts >::CompressedTuple (const Ts &... base) inline explicit constexpr
Definition at line 241 of file compressed_tuple.h.
      : CompressedTuple::CompressedTupleImpl(absl::in_place, base...) {}
CompressedTuple() [3/3]
template<typename... Ts> template<typename First , typename... Vs, absl::enable_if_t< absl::conjunction< absl::negation< std::is_same< void(CompressedTuple), void(absl::decay_t< First >)> >, internal_compressed_tuple::TupleItemsMoveConstructible< CompressedTuple< Ts... >, First, Vs... > >::value , bool > absl::container_internal::CompressedTuple< Ts >::CompressedTuple (First && first, Vs &&... base) inline explicit constexpr
Definition at line 253 of file compressed_tuple.h.
      : CompressedTuple::CompressedTupleImpl(absl::in_place,
                                             absl::forward<First>(first),
                                             absl::forward<Vs>(base)...) {}
References absl::forward().
Member Function Documentation
get() [1/4]
template<typename... Ts> template<int I> ElemT< I > & absl::container_internal::CompressedTuple< Ts >::get () & inline
Definition at line 259 of file compressed_tuple.h.
                    {
    return StorageT<I>::get();
  }
Referenced by open_spiel.python.utils.spawn._ProcessQueue::get_nowait().
get() [2/4]
template<typename... Ts> template<int I> ElemT< I > && absl::container_internal::CompressedTuple< Ts >::get () && inline
Definition at line 269 of file compressed_tuple.h.
                      {
    return std::move(*this).StorageT<I>::get();
  }
Referenced by open_spiel.python.utils.spawn._ProcessQueue::get_nowait().
get() [3/4]
template<typename... Ts> template<int I> const ElemT< I > & absl::container_internal::CompressedTuple< Ts >::get () const & inline constexpr
Definition at line 264 of file compressed_tuple.h.
{
    return StorageT<I>::get();
  }
Referenced by open_spiel.python.utils.spawn._ProcessQueue::get_nowait().
get() [4/4]
template<typename... Ts> template<int I> const ElemT< I > && absl::container_internal::CompressedTuple< Ts >::get () const && inline constexpr
Definition at line 274 of file compressed_tuple.h.
{
    return absl::move(*this).StorageT<I>::get();
  }
References absl::move().
Referenced by open_spiel.python.utils.spawn._ProcessQueue::get_nowait().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/compressed_tuple.h