open spiel: open_spiel::pathfinding::PathfindingState Class Reference
open_spiel::pathfinding::PathfindingState Class Reference
#include <pathfinding.h>
Public Member Functions
PathfindingState (std::shared_ptr< const Game > game, const GridSpec &grid_spec, int horizon)
PathfindingState (const PathfindingState &)=default
std::string ActionToString (int player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string ObservationString (int player) const override
void ObservationTensor (int player, absl::Span< float > values) const override
int CurrentPlayer () const override
std::unique_ptr< State > Clone () const override
ActionsAndProbs ChanceOutcomes () const override
std::vector< Action > LegalActions (int player) const override
std::pair< int, int > PlayerPos (int player) const
Player PlayerAtPos (const std::pair< int, int > &coord) const
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &moves) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 126 of file pathfinding.h.
Constructor & Destructor Documentation
PathfindingState() [1/2]
open_spiel::pathfinding::PathfindingState::PathfindingState (std::shared_ptr< const Game > game, const GridSpec & grid_spec, int horizon) explicit
Definition at line 134 of file pathfinding.cc.
    : SimMoveState(game),
      parent_game_(down_cast<const PathfindingGame&>(*game)),
      grid_spec_(grid_spec),
      cur_player_(kSimultaneousPlayerId),
      total_moves_(0),
      horizon_(horizon),
      player_positions_(num_players_),
      actions_(num_players_, kInvalidAction),
      rewards_(num_players_, 0.0),
      returns_(num_players_, 0.0),
      contested_players_(num_players_, 0),
      reached_destinations_(num_players_, 0) {
  grid_.reserve(grid_spec_.num_rows);
  for (int r = 0; r < grid_spec_.num_rows; ++r) {
    grid_.push_back(std::vector<int>(grid_spec_.num_cols, kEmpty));
  }
  for (const std::pair<int, int>& c : grid_spec_.obstacles) {
    grid_[c.first][c.second] = kWall;
  }
  SPIEL_CHECK_EQ(grid_spec_.starting_positions.size(), num_players_);
  for (Player p = 0; p < num_players_; ++p) {
    const std::pair<int, int>& c = grid_spec_.starting_positions[p];
    SPIEL_CHECK_EQ(grid_[c.first][c.second], kEmpty);
    grid_[c.first][c.second] = p;
    player_positions_[p] = c;
  }
}
References open_spiel::pathfinding::kEmpty, open_spiel::pathfinding::kWall, open_spiel::pathfinding::GridSpec::num_cols, open_spiel::State::num_players_, open_spiel::pathfinding::GridSpec::num_rows, open_spiel::pathfinding::GridSpec::obstacles, r, SPIEL_CHECK_EQ, and open_spiel::pathfinding::GridSpec::starting_positions.
Referenced by Clone().
PathfindingState() [2/2]
open_spiel::pathfinding::PathfindingState::PathfindingState (const PathfindingState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::pathfinding::PathfindingState::ActionToString (int player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 166 of file pathfinding.cc.
{
  return parent_game_.ActionToString(player, action_id);
}
References open_spiel::pathfinding::PathfindingGame::ActionToString(), and player.
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::pathfinding::PathfindingState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 396 of file pathfinding.cc.
          {
  SPIEL_CHECK_TRUE(IsChanceNode());
  int num_contested_players =
      std::count_if(contested_players_.begin(), contested_players_.end(),
                    [](int i) { return i == 1; });
  int num_permutations = Factorial(num_contested_players);
  double prob = 1.0 / num_permutations;
  ActionsAndProbs outcomes;
  outcomes.reserve(num_permutations);
  for (int i = 0; i < num_permutations; ++i) {
    outcomes.push_back({i, prob});
  }
  return outcomes;
}
References open_spiel::Factorial(), i, open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::pathfinding::PathfindingState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 530 of file pathfinding.cc.
{
  return std::unique_ptr<State>(new PathfindingState(*this));
}
References PathfindingState().
CurrentPlayer()
int open_spiel::pathfinding::PathfindingState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 139 of file pathfinding.h.
{
    return IsTerminal() ? kTerminalPlayerId : cur_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::pathfinding::PathfindingState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 358 of file pathfinding.cc.
{
  if (IsSimultaneousNode()) {
    ApplyFlatJointAction(action_id);
    return;
  } else {
    SPIEL_CHECK_TRUE(IsChanceNode());
    int num_contested_players =
        std::count_if(contested_players_.begin(), contested_players_.end(),
                      [](int i) { return i == 1; });
    std::vector<Player> contested_player_ids;
    contested_player_ids.reserve(num_contested_players);
    for (Player p = 0; p < contested_players_.size(); ++p) {
      if (contested_players_[p] == 1) {
        contested_player_ids.push_back(p);
      }
    }
    SPIEL_CHECK_EQ(contested_player_ids.size(), num_contested_players);
    std::vector<int> indices(num_contested_players);
    std::iota(indices.begin(), indices.end(), 0);
    std::vector<int> resolution_order = UnrankPermutation(indices, action_id);
    for (int idx : resolution_order) {
      ResolvePlayerAction(contested_player_ids[idx]);
    }
    std::fill(contested_players_.begin(), contested_players_.end(), 0);
    cur_player_ = kSimultaneousPlayerId;
    total_moves_++;
  }
}
References open_spiel::SimMoveState::ApplyFlatJointAction(), i, open_spiel::State::IsChanceNode(), open_spiel::State::IsSimultaneousNode(), open_spiel::kSimultaneousPlayerId, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and open_spiel::UnrankPermutation().
DoApplyActions()
void open_spiel::pathfinding::PathfindingState::DoApplyActions (const std::vector< Action > & moves) override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 171 of file pathfinding.cc.
{
  SPIEL_CHECK_EQ(moves.size(), num_players_);
  SPIEL_CHECK_EQ(cur_player_, kSimultaneousPlayerId);
  std::fill(rewards_.begin(), rewards_.end(), 0.0);
  std::fill(contested_players_.begin(), contested_players_.end(), 0);
  actions_ = moves;
  if (num_players_ == 1) {
    ResolvePlayerAction(0);
  } else {
    ResolveActions();
  }
  if (cur_player_ == kSimultaneousPlayerId) {
    // Only increment total moves if actions fully resolved.
    total_moves_++;
  }
  // If all players are at their destinations.
  if (AllPlayersOnDestinations()) {
    // Terminal state reached, all players get a bonus.
    for (Player p = 0; p < num_players_; ++p) {
      rewards_[p] += parent_game_.group_reward();
      returns_[p] += parent_game_.group_reward();
    }
  }
}
References open_spiel::pathfinding::PathfindingGame::group_reward(), open_spiel::kSimultaneousPlayerId, open_spiel::State::num_players_, and SPIEL_CHECK_EQ.
IsTerminal()
bool open_spiel::pathfinding::PathfindingState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 517 of file pathfinding.cc.
{
  if (total_moves_ >= horizon_) {
    return true;
  }
  // Check if all players at their destinations.
  return AllPlayersOnDestinations();
}
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::pathfinding::PathfindingState::LegalActions (int player) const override virtual
Implements open_spiel::SimMoveState.
Definition at line 387 of file pathfinding.cc.
{
  if (IsTerminal()) return {};
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  } else {
    return parent_game_.legal_actions();
  }
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::pathfinding::PathfindingGame::legal_actions(), and open_spiel::State::LegalChanceOutcomes().
ObservationString()
std::string open_spiel::pathfinding::PathfindingState::ObservationString (int player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 447 of file pathfinding.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::pathfinding::PathfindingState::ObservationTensor (int player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 455 of file pathfinding.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::fill(values.begin(), values.end(), 0.0);
  TensorView<3> view(values,
                     {parent_game_.NumObservationPlanes(), grid_spec_.num_rows,
                      grid_spec_.num_cols},
                     true);
  // Let n be the number of players.
  //   - First n planes refer to player
  //   - Second n planes refer to player's starting position
  //   - Third n planes refer to player's destination position
  //   - 1 plane for wall
  //   - 1 plane for empty
  //
  // The first three sets of n planes corresponding to the players are each
  // ordered ego-centrically:
  //   - the first plane is the observing player's plane, followed by the next
  //     player, followed by the next etc. so in a 4-player game, if player 2
  //     is the observing player, the planes would be ordered by player 2, 3, 0,
  //     1.
  for (int r = 0; r < grid_spec_.num_rows; ++r) {
    for (int c = 0; c < grid_spec_.num_cols; ++c) {
      // Player on the position.
      if (grid_[r][c] >= 0 && grid_[r][c] < num_players_) {
        view[{PlayerPlaneIndex(player, grid_[r][c]), r, c}] = 1.0;
      }
      // Wall
      if (grid_[r][c] == kWall) {
        view[{3 * num_players_, r, c}] = 1.0;
      }
      // Empty
      if (grid_[r][c] == kEmpty) {
        view[{3 * num_players_ + 1, r, c}] = 1.0;
      }
    }
  }
  for (Player p = 0; p < num_players_; ++p) {
    const std::pair<int, int>& start_pos = grid_spec_.starting_positions[p];
    const std::pair<int, int>& dest_pos = grid_spec_.destinations[p];
    int pidx = PlayerPlaneIndex(player, p);
    view[{num_players_ + pidx, start_pos.first, start_pos.second}] = 1.0;
    view[{2 * num_players_ + pidx, dest_pos.first, dest_pos.second}] = 1.0;
  }
}
References open_spiel::pathfinding::GridSpec::destinations, open_spiel::pathfinding::kEmpty, open_spiel::pathfinding::kWall, open_spiel::pathfinding::GridSpec::num_cols, open_spiel::State::num_players_, open_spiel::pathfinding::GridSpec::num_rows, open_spiel::pathfinding::PathfindingGame::NumObservationPlanes(), player, r, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::pathfinding::GridSpec::starting_positions, and values.
PlayerAtPos()
Player open_spiel::pathfinding::PathfindingState::PlayerAtPos (const std::pair< int, int > & coord) const
Definition at line 412 of file pathfinding.cc.
{
  if (grid_[coord.first][coord.second] >= 0 &&
      grid_[coord.first][coord.second] < num_players_) {
    return grid_[coord.first][coord.second];
  } else {
    return kInvalidPlayer;
  }
}
References open_spiel::kInvalidPlayer, and open_spiel::State::num_players_.
PlayerPos()
std::pair< int, int > open_spiel::pathfinding::PathfindingState::PlayerPos (int player) const inline
Definition at line 148 of file pathfinding.h.
{
    return player_positions_[player];
  }
References player.
Returns()
std::vector< double > open_spiel::pathfinding::PathfindingState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 528 of file pathfinding.cc.
{ return returns_; }
Rewards()
std::vector< double > open_spiel::pathfinding::PathfindingState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 526 of file pathfinding.cc.
{ return rewards_; }
ToString()
std::string open_spiel::pathfinding::PathfindingState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 421 of file pathfinding.cc.
{
  std::string str;
  for (int r = 0; r < grid_spec_.num_rows; ++r) {
    for (int c = 0; c < grid_spec_.num_cols; ++c) {
      if (grid_[r][c] >= 0 && grid_[r][c] < num_players_) {
        absl::StrAppend(&str, grid_[r][c]);
      } else if (grid_[r][c] == kWall) {
        absl::StrAppend(&str, "*");
      } else {
        absl::StrAppend(&str, ".");
      }
    }
    absl::StrAppend(&str, "\n");
  }
  return str;
}
References open_spiel::pathfinding::kWall, open_spiel::pathfinding::GridSpec::num_cols, open_spiel::State::num_players_, open_spiel::pathfinding::GridSpec::num_rows, r, and absl::StrAppend().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/pathfinding/pathfinding.h
open_spiel/games/pathfinding/pathfinding.cc