open spiel: open_spiel::universal_poker::acpc_cpp::ACPCState Class Reference
open_spiel::universal_poker::acpc_cpp::ACPCState Class Reference
#include <acpc_game.h>
Public Types
enum ACPCActionType { ACPC_FOLD , ACPC_CALL , ACPC_RAISE , ACPC_INVALID }
Public Member Functions
ACPCState (const ACPCGame *game)
ACPCState (const ACPCState &other)
void SetHoleAndBoardCards (uint8_t holeCards[10][3], uint8_t boardCards[7], uint8_t nbHoleCards[10], uint8_t nbBoardCards)
uint8_t CurrentPlayer () const
uint8_t NumFolded () const
uint32_t Money (const uint8_t player) const
uint32_t Ante (const uint8_t player) const
uint32_t TotalSpent () const
uint32_t CurrentSpent (const uint8_t player) const
std::string ToString () const
std::string BettingSequence (uint8_t round) const
int RaiseIsValid (int32_t *minSize, int32_t *maxSize) const
int IsValidAction (const ACPCActionType actionType, const int32_t size) const
void DoAction (const ACPCActionType actionType, const int32_t size)
double ValueOfState (const uint8_t player) const
bool IsFinished () const
uint32_t MaxSpend () const
uint8_t hole_cards (int player_index, int card_index) const
uint8_t board_cards (int card_index) const
void AddHoleCard (int player_index, int card_index, uint8_t card)
void AddBoardCard (int card_index, uint8_t card)
void SetPotSize (int pot_size)
int GetRound () const
const ACPCGame * game () const
const RawACPCState & raw_state () const
RawACPCState * mutable_state ()
Detailed Description
Definition at line 80 of file acpc_game.h.
Member Enumeration Documentation
ACPCActionType
enum open_spiel::universal_poker::acpc_cpp::ACPCState::ACPCActionType
Enumerator
ACPC_FOLD
ACPC_CALL
ACPC_RAISE
ACPC_INVALID
Definition at line 82 of file acpc_game.h.
{ ACPC_FOLD, ACPC_CALL, ACPC_RAISE, ACPC_INVALID };
Constructor & Destructor Documentation
ACPCState() [1/2]
open_spiel::universal_poker::acpc_cpp::ACPCState::ACPCState (const ACPCGame * game) explicit
Definition at line 212 of file acpc_game.cc.
    : game_(game), acpcState_() {
  project_acpc_server::initState(game_->MutableGame(),
                                 game_->HandId()
                                 /*TODO this make a unit test fail++*/,
                                 &acpcState_);
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::HandId(), and open_spiel::universal_poker::acpc_cpp::ACPCGame::MutableGame().
ACPCState() [2/2]
open_spiel::universal_poker::acpc_cpp::ACPCState::ACPCState (const ACPCState & other) inline explicit
Definition at line 85 of file acpc_game.h.
      : game_(other.game_), acpcState_(other.acpcState_) {}
Member Function Documentation
AddBoardCard()
void open_spiel::universal_poker::acpc_cpp::ACPCState::AddBoardCard (int card_index, uint8_t card) inline
Definition at line 125 of file acpc_game.h.
{
    SPIEL_CHECK_LT(card_index, MAX_BOARD_CARDS);
    acpcState_.boardCards[card_index] = card;
  }
References SPIEL_CHECK_LT.
AddHoleCard()
void open_spiel::universal_poker::acpc_cpp::ACPCState::AddHoleCard (int player_index, int card_index, uint8_t card) inline
Definition at line 119 of file acpc_game.h.
{
    SPIEL_CHECK_LT(player_index, MAX_PLAYERS);
    SPIEL_CHECK_LT(card_index, MAX_HOLE_CARDS);
    acpcState_.holeCards[player_index][card_index] = card;
  }
References SPIEL_CHECK_LT.
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction().
Ante()
uint32_t open_spiel::universal_poker::acpc_cpp::ACPCState::Ante (const uint8_t player) const
Definition at line 241 of file acpc_game.cc.
{
  SPIEL_CHECK_LE(player, game_->GetNbPlayers());
  return acpcState_.spent[player];
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), player, and SPIEL_CHECK_LE.
Referenced by open_spiel::universal_poker::UniversalPokerState::ObservationString(), and open_spiel::universal_poker::UniversalPokerState::ObservationTensor().
BettingSequence()
std::string open_spiel::universal_poker::acpc_cpp::ACPCState::BettingSequence (uint8_t round) const
Definition at line 270 of file acpc_game.cc.
{
  SPIEL_CHECK_LT(round, game_->NumRounds());
  std::string out;
  for (int a = 0; a < acpcState_.numActions[round]; a++) {
    absl::StrAppend(&out, ActionToString(acpcState_.action[round][a]));
  }
  return out;
}
References a, open_spiel::universal_poker::acpc_cpp::ACPCGame::NumRounds(), out, SPIEL_CHECK_LT, and absl::StrAppend().
Referenced by open_spiel::universal_poker::UniversalPokerState::InformationStateString().
board_cards()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCState::board_cards (int card_index) const inline
Definition at line 114 of file acpc_game.h.
{
    SPIEL_CHECK_LT(card_index, MAX_BOARD_CARDS);
    return acpcState_.boardCards[card_index];
  }
References SPIEL_CHECK_LT.
CurrentPlayer()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCState::CurrentPlayer () const
Definition at line 208 of file acpc_game.cc.
{
  return project_acpc_server::currentPlayer(game_->MutableGame(), &acpcState_);
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::MutableGame().
Referenced by open_spiel::universal_poker::UniversalPokerState::CurrentPlayer().
CurrentSpent()
uint32_t open_spiel::universal_poker::acpc_cpp::ACPCState::CurrentSpent (const uint8_t player) const
Definition at line 250 of file acpc_game.cc.
{
  SPIEL_CHECK_LE(player, game_->GetNbPlayers());
  return acpcState_.spent[player];
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), player, and SPIEL_CHECK_LE.
DoAction()
void open_spiel::universal_poker::acpc_cpp::ACPCState::DoAction (const ACPCActionType actionType, const int32_t size)
Definition at line 221 of file acpc_game.cc.
{
  project_acpc_server::Action a = GetAction(actionType, size);
  SPIEL_CHECK_TRUE(project_acpc_server::isValidAction(game_->MutableGame(),
                                                      &acpcState_, false, &a));
  project_acpc_server::doAction(game_->MutableGame(), &a, &acpcState_);
}
References a, open_spiel::GetAction(), open_spiel::universal_poker::acpc_cpp::ACPCGame::MutableGame(), size, and SPIEL_CHECK_TRUE.
Referenced by open_spiel::universal_poker::UniversalPokerState::ApplyChoiceAction().
game()
const ACPCGame * open_spiel::universal_poker::acpc_cpp::ACPCState::game () const inline
Definition at line 146 of file acpc_game.h.
{ return game_; }
Referenced by open_spiel.python.policy.TabularPolicy::__copy__(), open_spiel.python.jax.cfr.jax_cfr.JaxCFR::average_policy(), open_spiel.python.mfg.algorithms.distribution.DistributionPolicy::evaluate(), open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::get_avg_policies(), open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::get_gap(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::get_payoffs_for_strategies(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::get_payoffs_for_strategies(), open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::get_policies(), open_spiel.python.jax.cfr.jax_cfr.JaxCFR::init(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::num_players(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::num_players(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::num_strategies(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::num_strategies(), open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::payoff_tensor(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::payoff_tensor(), open_spiel::universal_poker::UniversalPokerState::PotSize(), open_spiel.python.examples.chat_game_psro_example.PSRO::run(), open_spiel.python.rl_environment.Environment::set_state(), open_spiel.python.tests.policy_test.TabularTicTacToePolicyTest::test_call_for_state(), open_spiel.integration_tests.api_test.EnforceAPIOnFullTreeBase::test_constant_sum(), open_spiel.integration_tests.api_test.EnforceAPIOnFullTreeBase::test_current_player_infosets_no_overlap_between_players(), open_spiel.integration_tests.api_test.EnforceAPIOnFullTreeBase::test_game_is_perfect_recall(), open_spiel.integration_tests.api_test.EnforceAPIOnPartialTreeBase::test_no_invalid_public_observations(), open_spiel.integration_tests.api_test.EnforceAPIOnPartialTreeBase::test_observations_raises_error_on_invalid_player(), open_spiel.integration_tests.api_test.EnforceAPIOnPartialTreeBase::test_private_information_contents(), open_spiel.integration_tests.api_test.EnforceAPIOnPartialTreeBase::test_sequence_lengths(), open_spiel.python.policy.Policy::to_tabular(), and open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt::update_sequences().
GetRound()
int open_spiel::universal_poker::acpc_cpp::ACPCState::GetRound () const inline
Definition at line 144 of file acpc_game.h.
{ return acpcState_.round; }
Referenced by open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::InformationStateString(), open_spiel::universal_poker::UniversalPokerState::ObservationString(), SetHoleAndBoardCards(), and open_spiel::universal_poker::UniversalPokerState::ToString().
hole_cards()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCState::hole_cards (int player_index, int card_index) const inline
Definition at line 109 of file acpc_game.h.
{
    SPIEL_CHECK_LT(player_index, MAX_PLAYERS);
    SPIEL_CHECK_LT(card_index, MAX_HOLE_CARDS);
    return acpcState_.holeCards[player_index][card_index];
  }
References SPIEL_CHECK_LT.
IsFinished()
bool open_spiel::universal_poker::acpc_cpp::ACPCState::IsFinished () const inline
Definition at line 107 of file acpc_game.h.
{ return stateFinished(&acpcState_); }
Referenced by open_spiel::universal_poker::UniversalPokerState::IsTerminal(), and open_spiel::universal_poker::UniversalPokerState::LegalActions().
IsValidAction()
int open_spiel::universal_poker::acpc_cpp::ACPCState::IsValidAction (const ACPCActionType actionType, const int32_t size) const
Definition at line 229 of file acpc_game.cc.
{
  project_acpc_server::Action a = GetAction(actionType, size);
  return project_acpc_server::isValidAction(game_->MutableGame(), &acpcState_,
                                            false, &a);
}
References a, open_spiel::GetAction(), open_spiel::universal_poker::acpc_cpp::ACPCGame::MutableGame(), and size.
Referenced by open_spiel::universal_poker::UniversalPokerState::LegalActions().
MaxSpend()
uint32_t open_spiel::universal_poker::acpc_cpp::ACPCState::MaxSpend () const inline
Definition at line 108 of file acpc_game.h.
{ return acpcState_.maxSpent; }
Referenced by open_spiel::universal_poker::UniversalPokerState::InformationStateString(), and open_spiel::universal_poker::UniversalPokerState::ObservationString().
Money()
uint32_t open_spiel::universal_poker::acpc_cpp::ACPCState::Money (const uint8_t player) const
Definition at line 236 of file acpc_game.cc.
{
  SPIEL_CHECK_LE(player, game_->GetNbPlayers());
  return game_->StackSize(player) - acpcState_.spent[player];
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), player, SPIEL_CHECK_LE, and open_spiel::universal_poker::acpc_cpp::ACPCGame::StackSize().
Referenced by open_spiel::universal_poker::UniversalPokerState::InformationStateString(), and open_spiel::universal_poker::UniversalPokerState::ObservationString().
mutable_state()
RawACPCState * open_spiel::universal_poker::acpc_cpp::ACPCState::mutable_state () inline
Definition at line 148 of file acpc_game.h.
{ return &acpcState_; }
Referenced by open_spiel::universal_poker::UniversalPokerState::UniversalPokerState().
NumFolded()
uint8_t open_spiel::universal_poker::acpc_cpp::ACPCState::NumFolded () const
Definition at line 204 of file acpc_game.cc.
{
  return project_acpc_server::numFolded(game_->MutableGame(), &acpcState_);
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::MutableGame().
Referenced by open_spiel::universal_poker::UniversalPokerState::InformationStateString(), and open_spiel::universal_poker::UniversalPokerState::ObservationString().
RaiseIsValid()
int open_spiel::universal_poker::acpc_cpp::ACPCState::RaiseIsValid (int32_t * minSize, int32_t * maxSize) const
Definition at line 200 of file acpc_game.cc.
{
  return raiseIsValid(game_->MutableGame(), &acpcState_, minSize, maxSize);
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::MutableGame().
Referenced by open_spiel::universal_poker::UniversalPokerState::AllInSize(), and open_spiel::universal_poker::UniversalPokerState::LegalActions().
raw_state()
const RawACPCState & open_spiel::universal_poker::acpc_cpp::ACPCState::raw_state () const inline
Definition at line 147 of file acpc_game.h.
{ return acpcState_; }
Referenced by open_spiel::universal_poker::UniversalPokerState::PotSize().
SetHoleAndBoardCards()
void open_spiel::universal_poker::acpc_cpp::ACPCState::SetHoleAndBoardCards (uint8_t holeCards[10][3], uint8_t boardCards[7], uint8_t nbHoleCards[10], uint8_t nbBoardCards)
Definition at line 279 of file acpc_game.cc.
{
  for (int p = 0; p < game_->GetNbPlayers(); ++p) {
    SPIEL_CHECK_EQ(nbHoleCards[p], game_->GetNbHoleCardsRequired());
    for (int c = 0; c < nbHoleCards[p]; ++c) {
      acpcState_.holeCards[p][c] = holeCards[p][c];
    }
  }
  SPIEL_CHECK_EQ(nbBoardCards, game_->GetNbBoardCardsRequired(GetRound()));
  for (int c = 0; c < nbBoardCards; ++c) {
    acpcState_.boardCards[c] = boardCards[c];
  }
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbBoardCardsRequired(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbHoleCardsRequired(), open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), GetRound(), and SPIEL_CHECK_EQ.
SetPotSize()
void open_spiel::universal_poker::acpc_cpp::ACPCState::SetPotSize (int pot_size) inline
Definition at line 132 of file acpc_game.h.
{
    SPIEL_CHECK_GE(pot_size, 0);
    SPIEL_CHECK_LE(pot_size, game_->TotalMoney());
    SPIEL_CHECK_EQ(pot_size % game_->GetNbPlayers(), 0);
    const int num_players = game_->GetNbPlayers();
    for (int pl = 0; pl < num_players; ++pl) {
      acpcState_.spent[pl] = pot_size / num_players;
    }
  }
References open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and open_spiel::universal_poker::acpc_cpp::ACPCGame::TotalMoney().
Referenced by open_spiel::universal_poker::UniversalPokerState::UniversalPokerState().
ToString()
std::string open_spiel::universal_poker::acpc_cpp::ACPCState::ToString () const
Definition at line 179 of file acpc_game.cc.
{
  char buf[kStringBuffersize];
  project_acpc_server::printState(game_->MutableGame(), &acpcState_,
                                  kStringBuffersize, buf);
  std::ostringstream out;
  out << buf << std::endl << "Spent: [";
  for (int p = 0; p < game_->GetNbPlayers(); ++p) {
    out << "P" << p << ": " << acpcState_.spent[p] << "  ";
  }
  out << "]" << std::endl;
  return out.str();
}
References buf, open_spiel::universal_poker::acpc_cpp::ACPCGame::GetNbPlayers(), open_spiel::universal_poker::acpc_cpp::kStringBuffersize, open_spiel::universal_poker::acpc_cpp::ACPCGame::MutableGame(), and out.
Referenced by open_spiel::universal_poker::UniversalPokerState::ToString().
TotalSpent()
uint32_t open_spiel::universal_poker::acpc_cpp::ACPCState::TotalSpent () const
Definition at line 246 of file acpc_game.cc.
{
  return static_cast<uint32_t>(absl::c_accumulate(acpcState_.spent, 0));
}
References absl::c_accumulate().
ValueOfState()
double open_spiel::universal_poker::acpc_cpp::ACPCState::ValueOfState (const uint8_t player) const
Definition at line 195 of file acpc_game.cc.
{
  SPIEL_CHECK_TRUE(stateFinished(&acpcState_));
  return project_acpc_server::valueOfState(game_->MutableGame(), &acpcState_,
                                           player);
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::MutableGame(), player, and SPIEL_CHECK_TRUE.
The documentation for this class was generated from the following files:
open_spiel/games/universal_poker/acpc_cpp/acpc_game.h
open_spiel/games/universal_poker/acpc_cpp/acpc_game.cc