open spiel: open_spiel::phantom_go::PhantomGoBoard Class Reference
open_spiel::phantom_go::PhantomGoBoard Class Reference
#include <phantom_go_board.h>
Classes
class GroupIter
Public Member Functions
PhantomGoBoard (int board_size)
void Clear ()
std::array< int, 2 > GetStoneCount () const
std::string ObservationsToString () const
std::string ObservationToString (int player) const
std::string LastMoveInformationToString () const
bool LastMoveObservational () const
bool LastMoveCapture () const
std::array< GoColor, kMaxBoardSize *kMaxBoardSize > GetObservationByID (int player_id) const
int board_size () const
int pass_action () const
Action VirtualActionToAction (int virtual_action) const
int ActionToVirtualAction (Action action) const
GoColor PointColor (VirtualPoint p) const
bool IsEmpty (VirtualPoint p) const
bool IsInBoardArea (VirtualPoint p) const
bool IsLegalMove (VirtualPoint p, GoColor c) const
bool IsLegalMoveObserver (VirtualPoint p, GoColor c) const
bool PlayMove (VirtualPoint p, GoColor c)
VirtualPoint LastKoPoint () const
int PseudoLiberty (VirtualPoint p) const
bool InAtari (VirtualPoint p) const
VirtualPoint SingleLiberty (VirtualPoint p) const
int RealLiberty (VirtualPoint p) const
uint64_t HashValue () const
VirtualPoint ChainHead (VirtualPoint p) const
int ChainSize (VirtualPoint p) const
std::string ToString () const
GroupIter LibIter (VirtualPoint p) const
GroupIter OppIter (VirtualPoint p) const
Detailed Description
Definition at line 105 of file phantom_go_board.h.
Constructor & Destructor Documentation
PhantomGoBoard()
open_spiel::phantom_go::PhantomGoBoard::PhantomGoBoard (int board_size) explicit
Definition at line 265 of file phantom_go_board.cc.
    : board_size_(board_size), pass_action_(board_size * board_size) {
  if (board_size_ > 19) {
    SpielFatalError(
        absl::StrCat("The current Go implementation supports board size up to "
                     "19. Provided: ",
                     board_size));
  }
  Clear();
}
References board_size(), Clear(), open_spiel::SpielFatalError(), and absl::StrCat().
Member Function Documentation
ActionToVirtualAction()
int open_spiel::phantom_go::PhantomGoBoard::ActionToVirtualAction (Action action) const inline
Definition at line 127 of file phantom_go_board.h.
{
    return phantom_go::ActionToVirtualAction(action, board_size_);
  }
References action, and open_spiel::phantom_go::ActionToVirtualAction().
Referenced by open_spiel::phantom_go::PhantomGoState::ActionToString(), and open_spiel::phantom_go::PhantomGoState::DoApplyAction().
board_size()
int open_spiel::phantom_go::PhantomGoBoard::board_size () const inline
Definition at line 120 of file phantom_go_board.h.
{ return board_size_; }
Referenced by open_spiel::phantom_go::PhantomGoState::equalMetaposition(), IsInBoardArea(), open_spiel::phantom_go::PhantomGoState::LegalActions(), open_spiel::phantom_go::operator<<(), PhantomGoBoard(), and open_spiel::phantom_go::TrompTaylorScore().
ChainHead()
VirtualPoint open_spiel::phantom_go::PhantomGoBoard::ChainHead (VirtualPoint p) const inline
Definition at line 177 of file phantom_go_board.h.
{
    return board_[p].chain_head;
  }
Referenced by open_spiel::phantom_go::PhantomGoBoard::GroupIter::GroupIter(), and SingleLiberty().
ChainSize()
int open_spiel::phantom_go::PhantomGoBoard::ChainSize (VirtualPoint p) const inline
Definition at line 182 of file phantom_go_board.h.
{ return chain(p).num_stones; }
Clear()
void open_spiel::phantom_go::PhantomGoBoard::Clear ()
Definition at line 276 of file phantom_go_board.cc.
{
  zobrist_hash_ = 0;
  for (int i = 0; i < board_size_ * board_size_; i++) {
    observations_[(uint8_t)GoColor::kBlack][i] = GoColor::kEmpty;
    observations_[(uint8_t)GoColor::kWhite][i] = GoColor::kEmpty;
  }
  stone_count_ = {0, 0};
  last_move_valid = true;
  last_move_pass = false;
  last_move_captured = 0;
  for (int i = 0; i < board_.size(); ++i) {
    Vertex &v = board_[i];
    v.color = GoColor::kGuard;
    v.chain_head = static_cast<VirtualPoint>(i);
    v.chain_next = static_cast<VirtualPoint>(i);
    chains_[i].reset_border();
  }
  for (VirtualPoint p : BoardPoints(board_size_)) {
    board_[p].color = GoColor::kEmpty;
    chains_[p].reset();
  }
  for (VirtualPoint p : BoardPoints(board_size_)) {
    Neighbours(p, [this, p](VirtualPoint n) {
      if (IsEmpty(n)) chain(p).add_liberty(n);
    });
  }
  for (int i = 0; i < last_captures_.size(); ++i) {
    last_captures_[i] = kInvalidPoint;
  }
  last_ko_point_ = kInvalidPoint;
}
References open_spiel::phantom_go::BoardPoints(), i, IsEmpty(), open_spiel::phantom_go::kBlack, open_spiel::phantom_go::kEmpty, open_spiel::phantom_go::kGuard, open_spiel::phantom_go::kInvalidPoint, open_spiel::phantom_go::kWhite, and n.
Referenced by PhantomGoBoard().
GetObservationByID()
std::array< GoColor, kMaxBoardSize *kMaxBoardSize > open_spiel::phantom_go::PhantomGoBoard::GetObservationByID (int player_id) const
Definition at line 412 of file phantom_go_board.cc.
{
  return observations_[player_id];
}
Referenced by open_spiel::phantom_go::PhantomGoState::equalMetaposition().
GetStoneCount()
std::array< int, 2 > open_spiel::phantom_go::PhantomGoBoard::GetStoneCount () const inline
Definition at line 111 of file phantom_go_board.h.
{ return stone_count_; }
Referenced by open_spiel::phantom_go::PhantomGoState::equalMetaposition(), open_spiel::phantom_go::PhantomGoState::GetStoneCount(), and open_spiel::phantom_go::PhantomGoState::ToString().
HashValue()
uint64_t open_spiel::phantom_go::PhantomGoBoard::HashValue () const inline
Definition at line 173 of file phantom_go_board.h.
{ return zobrist_hash_; }
Referenced by open_spiel::phantom_go::PhantomGoState::DoApplyAction().
InAtari()
bool open_spiel::phantom_go::PhantomGoBoard::InAtari (VirtualPoint p) const inline
Definition at line 157 of file phantom_go_board.h.
{ return chain(p).in_atari(); }
IsEmpty()
bool open_spiel::phantom_go::PhantomGoBoard::IsEmpty (VirtualPoint p) const inline
Definition at line 133 of file phantom_go_board.h.
{
    return PointColor(p) == GoColor::kEmpty;
  }
References open_spiel::phantom_go::kEmpty, and PointColor().
Referenced by Clear(), IsLegalMoveObserver(), open_spiel::phantom_go::operator<<(), and SingleLiberty().
IsInBoardArea()
bool open_spiel::phantom_go::PhantomGoBoard::IsInBoardArea (VirtualPoint p) const
Definition at line 568 of file phantom_go_board.cc.
{
  auto rc = VirtualPointTo2DPoint(p);
  return rc.first >= 0 && rc.first < board_size() && rc.second >= 0 &&
         rc.second < board_size();
}
References board_size(), and open_spiel::phantom_go::VirtualPointTo2DPoint().
Referenced by IsLegalMoveObserver(), and SingleLiberty().
IsLegalMove()
bool open_spiel::phantom_go::PhantomGoBoard::IsLegalMove (VirtualPoint p, GoColor c) const
Definition at line 602 of file phantom_go_board.cc.
{
  if (observations_[(uint8_t)c][VirtualPointToBoardPoint(p, board_size_)] ==
      GoColor::kEmpty) {
    return true;
  }
  return false;
}
References open_spiel::phantom_go::kEmpty, and open_spiel::phantom_go::VirtualPointToBoardPoint().
Referenced by open_spiel::phantom_go::PhantomGoState::LegalActions().
IsLegalMoveObserver()
bool open_spiel::phantom_go::PhantomGoBoard::IsLegalMoveObserver (VirtualPoint p, GoColor c) const
Definition at line 574 of file phantom_go_board.cc.
{
  if (p == kVirtualPass) return true;
  if (!IsInBoardArea(p)) return false;
  if (!IsEmpty(p) || p == LastKoPoint()) return false;
  if (chain(p).num_pseudo_liberties > 0) return true;
  // For all checks below, the newly placed stone is completely surrounded by
  // enemy and friendly stones.
  // Allow to play if the placed stones connects to a group that still has at
  // least one other liberty after connecting.
  bool has_liberty = false;
  Neighbours(p, [this, c, &has_liberty](VirtualPoint n) {
    has_liberty |= (PointColor(n) == c && !chain(n).in_atari());
  });
  if (has_liberty) return true;
  // Allow to play if the placed stone will kill at least one group.
  bool kills_group = false;
  Neighbours(p, [this, c, &kills_group](VirtualPoint n) {
    kills_group |= (PointColor(n) == OppColor(c) && chain(n).in_atari());
  });
  if (kills_group) return true;
  return false;
}
References IsEmpty(), IsInBoardArea(), open_spiel::phantom_go::kVirtualPass, LastKoPoint(), n, open_spiel::phantom_go::OppColor(), and PointColor().
Referenced by PlayMove().
LastKoPoint()
VirtualPoint open_spiel::phantom_go::PhantomGoBoard::LastKoPoint () const inline
Definition at line 146 of file phantom_go_board.h.
{ return last_ko_point_; }
Referenced by IsLegalMoveObserver().
LastMoveCapture()
bool open_spiel::phantom_go::PhantomGoBoard::LastMoveCapture () const inline
Definition at line 116 of file phantom_go_board.h.
{ return last_move_captured > 0; }
LastMoveInformationToString()
std::string open_spiel::phantom_go::PhantomGoBoard::LastMoveInformationToString () const
Definition at line 667 of file phantom_go_board.cc.
{
  std::stringstream stream;
  if (last_move_valid) {
    stream << "Previous move was valid";
    if (last_move_pass) {
      stream << " and was a pass";
    }
    stream << "\n";
  } else {
    stream << "Previous move was observational\n";
  }
  if (last_move_captured > 0) {
    stream << "In previous move " << last_move_captured
           << " stones were captured\n";
  }
  return stream.str();
}
Referenced by ObservationsToString(), and open_spiel::phantom_go::PhantomGoState::ObservationString().
LastMoveObservational()
bool open_spiel::phantom_go::PhantomGoBoard::LastMoveObservational () const inline
Definition at line 115 of file phantom_go_board.h.
{ return !last_move_valid; }
LibIter()
GroupIter open_spiel::phantom_go::PhantomGoBoard::LibIter (VirtualPoint p) const inline
Definition at line 218 of file phantom_go_board.h.
{
    return GroupIter(this, p, GoColor::kEmpty);
  }
References open_spiel::phantom_go::kEmpty.
Referenced by RealLiberty().
ObservationsToString()
std::string open_spiel::phantom_go::PhantomGoBoard::ObservationsToString () const
Definition at line 416 of file phantom_go_board.cc.
{
  std::stringstream ss;
  ss << "\nObservation white:\n";
  ss << ObservationToString((uint8_t)GoColor::kWhite);
  ss << "\nObservation black:\n";
  ss << ObservationToString((uint8_t)GoColor::kBlack);
  ss << "\n";
  ss << LastMoveInformationToString();
  return ss.str();
}
References open_spiel::phantom_go::kBlack, open_spiel::phantom_go::kWhite, LastMoveInformationToString(), and ObservationToString().
Referenced by open_spiel::phantom_go::PhantomGoState::ToString().
ObservationToString()
std::string open_spiel::phantom_go::PhantomGoBoard::ObservationToString (int player) const
Definition at line 433 of file phantom_go_board.cc.
{
  std::stringstream ss;
  for (int x = board_size_ - 1; x >= 0; x--) {
    if (board_size_ - 1 >= 10 && x < 10) {
      ss << " ";
    }
    ss << " " << x + 1 << " ";
    for (int y = 0; y < board_size_; y++) {
      ss << GoColorToChar(observations_[player][x * board_size_ + y]);
    }
    ss << "\n";
  }
  ss << "   ";
  for (int i = 0; i < board_size_; i++) {
    char letter = 'A' + i;
    if (letter >= 'I') {
      letter++;
    }
    ss << letter;
  }
  ss << "\n";
  return ss.str();
}
References open_spiel::phantom_go::GoColorToChar(), i, player, x, and y.
Referenced by ObservationsToString(), and open_spiel::phantom_go::PhantomGoState::ObservationString().
OppIter()
GroupIter open_spiel::phantom_go::PhantomGoBoard::OppIter (VirtualPoint p) const inline
Definition at line 221 of file phantom_go_board.h.
{
    return GroupIter(this, p, OppColor(PointColor(p)));
  }
References open_spiel::phantom_go::OppColor(), and PointColor().
pass_action()
int open_spiel::phantom_go::PhantomGoBoard::pass_action () const inline
Definition at line 123 of file phantom_go_board.h.
{ return pass_action_; }
Referenced by open_spiel::phantom_go::PhantomGoState::DoApplyAction(), open_spiel::phantom_go::PhantomGoState::IsTerminal(), and open_spiel::phantom_go::PhantomGoState::LegalActions().
PlayMove()
bool open_spiel::phantom_go::PhantomGoBoard::PlayMove (VirtualPoint p, GoColor c)
Definition at line 316 of file phantom_go_board.cc.
{
  if (p == kVirtualPass) {
    last_ko_point_ = kInvalidPoint;
    last_move_captured = 0;
    last_move_pass = true;
    last_move_valid = true;
    return true;
  } else {
    last_move_pass = false;
  }
  observations_[(uint8_t)c][VirtualPointToBoardPoint(p, board_size_)] =
      board_[p].color;
  // playing illegal moves will occur during phantom go, it is even desired
  if (!IsLegalMoveObserver(p, c)) {
    last_move_captured = 0;
    last_move_valid = false;  // was a observational move
    return false;
  }
  last_move_valid = true;
  stone_count_[(uint8_t)c]++;
  // Preparation for ko checking.
  bool played_in_enemy_eye = true;
  Neighbours(p, [this, c, &played_in_enemy_eye](VirtualPoint n) {
    GoColor s = PointColor(n);
    if (s == c || s == GoColor::kEmpty) {
      played_in_enemy_eye = false;
    }
  });
  JoinChainsAround(p, c);
  SetStone(p, c);
  RemoveLibertyFromNeighbouringChains(p);
  int stones_captured = CaptureDeadChains(p, c);
  stone_count_[(uint8_t)OppColor(c)] -= stones_captured;
  last_move_captured = stones_captured;
  observations_[(uint8_t)c][VirtualPointToBoardPoint(p, board_size_)] = c;
  if (played_in_enemy_eye && stones_captured == 1) {
    last_ko_point_ = last_captures_[0];
  } else {
    last_ko_point_ = kInvalidPoint;
  }
  if (stones_captured != 0) {
    for (int point = 0; point < board_size_ * board_size_; point++) {
      VirtualPoint vpoint = VirtualPointFromBoardPoint(point, board_size_);
      if (observations_[(uint8_t)OppColor(c)][point] == OppColor(c) &&
          board_[vpoint].color == GoColor::kEmpty) {
        observations_[(uint8_t)GoColor::kBlack][point] = GoColor::kEmpty;
        observations_[(uint8_t)GoColor::kWhite][point] = GoColor::kEmpty;
      }
    }
  }
  SPIEL_CHECK_GT(chain(p).num_pseudo_liberties, 0);
  return true;
}
References IsLegalMoveObserver(), open_spiel::phantom_go::kBlack, open_spiel::phantom_go::kEmpty, open_spiel::phantom_go::kInvalidPoint, open_spiel::phantom_go::kVirtualPass, open_spiel::phantom_go::kWhite, n, open_spiel::phantom_go::OppColor(), PointColor(), SPIEL_CHECK_GT, open_spiel::phantom_go::VirtualPointFromBoardPoint(), and open_spiel::phantom_go::VirtualPointToBoardPoint().
Referenced by open_spiel::phantom_go::CreateBoard(), and open_spiel::phantom_go::PhantomGoState::DoApplyAction().
PointColor()
GoColor open_spiel::phantom_go::PhantomGoBoard::PointColor (VirtualPoint p) const inline
Definition at line 131 of file phantom_go_board.h.
{ return board_[p].color; }
Referenced by IsEmpty(), IsLegalMoveObserver(), open_spiel::phantom_go::NumSurroundedPoints(), open_spiel::phantom_go::operator<<(), OppIter(), PlayMove(), and open_spiel::phantom_go::TrompTaylorScore().
PseudoLiberty()
int open_spiel::phantom_go::PhantomGoBoard::PseudoLiberty (VirtualPoint p) const inline
Definition at line 151 of file phantom_go_board.h.
{
    return chain(p).num_pseudo_liberties == 0
               ? 0
               : (chain(p).in_atari() ? 1 : chain(p).num_pseudo_liberties);
  }
RealLiberty()
int open_spiel::phantom_go::PhantomGoBoard::RealLiberty (VirtualPoint p) const inline
Definition at line 165 of file phantom_go_board.h.
{
    int num_lib = 0;
    for (auto it = LibIter(p); it; ++it) {
      ++num_lib;
    }
    return num_lib;
  }
References LibIter().
SingleLiberty()
VirtualPoint open_spiel::phantom_go::PhantomGoBoard::SingleLiberty (VirtualPoint p) const
Definition at line 383 of file phantom_go_board.cc.
{
  VirtualPoint head = ChainHead(p);
  VirtualPoint liberty = chain(p).single_liberty();
  // Check it is really a liberty.
  SPIEL_CHECK_TRUE(IsInBoardArea(liberty));
  SPIEL_CHECK_TRUE(IsEmpty(liberty));
  // Make sure the liberty actually borders the group.
  for (auto n = Neighbours4(liberty); n; ++n) {
    if (ChainHead(*n) == head) return liberty;
  }
  SpielFatalError(
      absl::StrCat("liberty", liberty, " does not actually border group ", p));
}
References ChainHead(), IsEmpty(), IsInBoardArea(), n, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), and absl::StrCat().
ToString()
std::string open_spiel::phantom_go::PhantomGoBoard::ToString () const
Definition at line 662 of file phantom_go_board.cc.
{
  std::ostringstream stream;
  stream << *this;
  return stream.str();
}
Referenced by open_spiel::phantom_go::PhantomGoState::ToString().
VirtualActionToAction()
Action open_spiel::phantom_go::PhantomGoBoard::VirtualActionToAction (int virtual_action) const inline
Definition at line 124 of file phantom_go_board.h.
{
    return phantom_go::VirtualActionToAction(virtual_action, board_size_);
  }
References open_spiel::phantom_go::VirtualActionToAction().
Referenced by open_spiel::phantom_go::PhantomGoState::LegalActions().
The documentation for this class was generated from the following files:
open_spiel/games/phantom_go/phantom_go_board.h
open_spiel/games/phantom_go/phantom_go_board.cc