open spiel: open_spiel::bridge_uncontested_bidding::UncontestedBiddingState Class Reference
open_spiel::bridge_uncontested_bidding::UncontestedBiddingState Class Reference
#include <bridge_uncontested_bidding.h>
Public Member Functions
UncontestedBiddingState (std::shared_ptr< const Game > game, std::vector< Contract > reference_contracts, std::function< bool(const Deal &)> deal_filter, std::vector< Action > actions, int rng_seed, int num_redeals)
UncontestedBiddingState (std::shared_ptr< const Game > game, std::vector< Contract > reference_contracts, const Deal &deal, std::vector< Action > actions, int rng_seed, int num_redeals)
UncontestedBiddingState (const UncontestedBiddingState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string AuctionString () const
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string Serialize () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
virtual std::string ObservationString (Player player) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
void ScoreDeal ()
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 141 of file bridge_uncontested_bidding.h.
Constructor & Destructor Documentation
UncontestedBiddingState() [1/3]
open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::UncontestedBiddingState (std::shared_ptr< const Game > game, std::vector< Contract > reference_contracts, std::function< bool(const Deal &)> deal_filter, std::vector< Action > actions, int rng_seed, int num_redeals) inline
Definition at line 143 of file bridge_uncontested_bidding.h.
      : State(game),
        reference_contracts_(std::move(reference_contracts)),
        actions_(std::move(actions)),
        deal_filter_(deal_filter),
        rng_(rng_seed),
        num_redeals_(num_redeals),
        dealt_(false) {}
Referenced by Clone().
UncontestedBiddingState() [2/3]
open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::UncontestedBiddingState (std::shared_ptr< const Game > game, std::vector< Contract > reference_contracts, const Deal & deal, std::vector< Action > actions, int rng_seed, int num_redeals) inline
Definition at line 155 of file bridge_uncontested_bidding.h.
      : State(game),
        reference_contracts_(std::move(reference_contracts)),
        actions_(std::move(actions)),
        rng_(rng_seed),
        num_redeals_(num_redeals),
        deal_(deal),
        dealt_(true) {
    if (IsTerminal()) ScoreDeal();
  }
References IsTerminal(), and ScoreDeal().
UncontestedBiddingState() [3/3]
open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::UncontestedBiddingState (const UncontestedBiddingState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 109 of file bridge_uncontested_bidding.cc.
{
  if (player == kChancePlayerId) return "Deal";
  if (action_id == kPass) return "Pass";
  return absl::StrCat(
      Level(action_id),
      std::string(1, kDenominationChar[Denomination(action_id)]));
}
References open_spiel::bridge_uncontested_bidding::Denomination(), open_spiel::kChancePlayerId, open_spiel::bridge_uncontested_bidding::Level(), player, and absl::StrCat().
Referenced by AuctionString().
AuctionString()
std::string open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::AuctionString () const
Definition at line 174 of file bridge_uncontested_bidding.cc.
{
  std::string actions;
  for (const auto action : actions_) {
    if (!actions.empty()) actions.push_back('-');
    actions.append(ActionToString(0, action));
  }
  return actions;
}
References action, and ActionToString().
Referenced by InformationStateString(), and ToString().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 331 of file bridge_uncontested_bidding.cc.
          {
  return {{0, 1.0}};
}
Clone()
std::unique_ptr< State > open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 219 of file bridge_uncontested_bidding.cc.
{
  return std::unique_ptr<State>(new UncontestedBiddingState(*this));
}
References UncontestedBiddingState().
CurrentPlayer()
int open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 97 of file bridge_uncontested_bidding.cc.
{
  if (!dealt_) return kChancePlayerId;
  if (IsTerminal()) return kTerminalPlayerId;
  return actions_.size() % 2;
}
References IsTerminal(), open_spiel::kChancePlayerId, and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 319 of file bridge_uncontested_bidding.cc.
{
  if (dealt_) {
    actions_.push_back(action_id);
    if (IsTerminal()) ScoreDeal();
  } else {
    do {
      deal_.Shuffle(&rng_);
    } while (!deal_filter_(deal_));
    dealt_ = true;
  }
}
References IsTerminal(), ScoreDeal(), and open_spiel::bridge_uncontested_bidding::Deal::Shuffle().
InformationStateString()
std::string open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 183 of file bridge_uncontested_bidding.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (!dealt_) return "";
  return absl::StrCat(deal_.HandString(player * 13, (player + 1) * 13), " ",
                      AuctionString());
}
References AuctionString(), open_spiel::bridge_uncontested_bidding::Deal::HandString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
InformationStateTensor()
void open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 193 of file bridge_uncontested_bidding.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), kStateSize);
  std::fill(values.begin(), values.end(), 0.);
  auto ptr = values.begin();
  for (int i = kNumCardsPerHand * player; i < kNumCardsPerHand * (1 + player);
       ++i) {
    ptr[deal_.Card(i)] = 1.;
  }
  ptr += kNumCards;
  // What actions have been taken, and by whom
  for (int i = 0; i < actions_.size(); ++i) {
    ptr[actions_[i] * kNumPlayers + (i % kNumPlayers)] = 1;
  }
  ptr += kNumActions * kNumPlayers;
  // Which player we are
  ptr[player] = 1;
  ptr += kNumPlayers;
}
References open_spiel::bridge_uncontested_bidding::Deal::Card(), i, open_spiel::bridge_uncontested_bidding::kNumActions, open_spiel::bridge_uncontested_bidding::kNumCards, open_spiel::bridge_uncontested_bidding::kNumCardsPerHand, open_spiel::bridge_uncontested_bidding::kNumPlayers, open_spiel::bridge_uncontested_bidding::kStateSize, open_spiel::State::num_players_, player, ptr, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 158 of file bridge_uncontested_bidding.cc.
{
  return dealt_ && actions_.size() >= 2 && actions_.back() == kPass;
}
Referenced by CurrentPlayer(), DoApplyAction(), LegalActions(), Returns(), ToString(), and UncontestedBiddingState().
LegalActions()
std::vector< Action > open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 223 of file bridge_uncontested_bidding.cc.
{
  if (IsTerminal()) {
    return {};
  } else if (dealt_) {
    std::vector<Action> actions{kPass};
    const Action prev = actions_.empty() ? kPass : actions_.back();
    for (Action a = prev + 1; a < kNumActions; ++a) actions.push_back(a);
    return actions;
  } else {
    return {0};
  }
}
References a, IsTerminal(), and open_spiel::bridge_uncontested_bidding::kNumActions.
Returns()
std::vector< double > open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 162 of file bridge_uncontested_bidding.cc.
{
  if (!IsTerminal()) return {0, 0};
  double v = score_;
  if (reference_scores_.empty()) {
    return {v, v};
  } else {
    const double datum =
        *std::max_element(reference_scores_.begin(), reference_scores_.end());
    return {v, v - datum};
  }
}
References IsTerminal().
ScoreDeal()
void open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::ScoreDeal () protected
Definition at line 236 of file bridge_uncontested_bidding.cc.
{
  // If both Pass, the score is zero.
  const bool passed_out = (actions_.size() == 2);
  if (passed_out && reference_contracts_.empty()) {
    score_ = 0;
    return;
  }
  // Determine the final contract and declarer
  const Action bid = actions_[actions_.size() - 2];
  Contract contract{passed_out ? 0 : Level(bid),
                    passed_out ? kNoTrump : Denomination(bid), kUndoubled};
  for (int i = 0; i < actions_.size(); ++i) {
    if (actions_[i] > 0 && Denomination(actions_[i]) == contract.trumps) {
      contract.declarer = i % 2;
      break;
    }
  }
  // Populate East-West cards
  ddTableDeal dd_table_deal{};
  for (Player player = 0; player < kNumPlayers; ++player) {
    for (int i = kNumCardsPerHand * player; i < kNumCardsPerHand * (1 + player);
         ++i) {
      dd_table_deal.cards[player * 2][deal_.Suit(i)] += 1
                                                        << (2 + deal_.Rank(i));
    }
  }
  // Initialize scores to zero
  score_ = 0;
  reference_scores_.resize(reference_contracts_.size());
  std::fill(reference_scores_.begin(), reference_scores_.end(), 0);
  // For each redeal
  for (int ideal = 0; ideal < num_redeals_; ++ideal) {
    if (ideal > 0) deal_.Shuffle(&rng_, kNumCardsPerHand * 2, kNumCards);
    // Populate (reshuffled) North-South cards
    for (int opponent = 0; opponent < kNumPlayers; ++opponent) {
      std::fill(dd_table_deal.cards[1 + opponent * 2],
                dd_table_deal.cards[1 + opponent * 2] + 4, 0);
      for (int i = kNumCardsPerHand * (2 + opponent);
           i < kNumCardsPerHand * (3 + opponent); ++i) {
        dd_table_deal.cards[1 + opponent * 2][deal_.Suit(i)] +=
            1 << (2 + deal_.Rank(i));
      }
    }
    // Analyze the deal.
    DDS_EXTERNAL(SetMaxThreads)(0);
    struct ddTableResults results;
    const int return_code = DDS_EXTERNAL(CalcDDtable)(dd_table_deal, &results);
    // Check for errors.
    if (return_code != RETURN_NO_FAULT) {
      char error_message[80];
      DDS_EXTERNAL(ErrorMessage)(return_code, error_message);
      SpielFatalError(absl::StrCat("double_dummy_solver:", error_message));
    }
    // Compute the score and update the total.
    if (!passed_out) {
      const int declarer_tricks =
          results.resTable[contract.trumps][2 * contract.declarer];
      const int declarer_score =
          Score(contract, declarer_tricks, /*is_vulnerable=*/false);
      score_ += static_cast<double>(declarer_score) / num_redeals_;
    }
    // Compute the scores for reference contracts.
    for (int i = 0; i < reference_contracts_.size(); ++i) {
      const int declarer_tricks =
          results.resTable[reference_contracts_[i].trumps]
                          [2 * reference_contracts_[i].declarer];
      const int declarer_score = Score(reference_contracts_[i], declarer_tricks,
                                       /*is_vulnerable=*/false);
      reference_scores_[i] +=
          static_cast<double>(declarer_score) / num_redeals_;
    }
  }
}
References CalcDDtable(), ddTableDeal::cards, DDS_EXTERNAL, open_spiel::bridge::Contract::declarer, open_spiel::bridge_uncontested_bidding::Denomination(), ErrorMessage(), i, open_spiel::bridge_uncontested_bidding::kNumCards, open_spiel::bridge_uncontested_bidding::kNumCardsPerHand, open_spiel::bridge_uncontested_bidding::kNumPlayers, open_spiel::bridge_uncontested_bidding::Level(), player, open_spiel::bridge_uncontested_bidding::Deal::Rank(), ddTableResults::resTable, RETURN_NO_FAULT, SetMaxThreads(), open_spiel::bridge_uncontested_bidding::Deal::Shuffle(), open_spiel::SpielFatalError(), absl::StrCat(), and open_spiel::bridge_uncontested_bidding::Deal::Suit().
Referenced by DoApplyAction(), and UncontestedBiddingState().
Serialize()
std::string open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::Serialize () const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 182 of file bridge_uncontested_bidding.h.
{ return ToString(); }
References ToString().
ToString()
std::string open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 144 of file bridge_uncontested_bidding.cc.
{
  if (!dealt_) return "";
  std::string rv = absl::StrCat(deal_.HandString(0, 13), " ",
                                deal_.HandString(13, 26), " ", AuctionString());
  if (IsTerminal()) {
    absl::StrAppend(&rv, " Score:", score_);
    for (int i = 0; i < reference_contracts_.size(); ++i) {
      absl::StrAppend(&rv, " ", reference_contracts_[i].ToString(), ":",
                      reference_scores_[i]);
    }
  }
  return rv;
}
References AuctionString(), open_spiel::bridge_uncontested_bidding::Deal::HandString(), i, IsTerminal(), absl::StrAppend(), absl::StrCat(), and ToString().
Referenced by Serialize(), and ToString().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/bridge_uncontested_bidding.h
open_spiel/games/bridge/bridge_uncontested_bidding.cc