open spiel: absl::flags_internal::PrivateHandleAccessor Class Reference
absl::flags_internal::PrivateHandleAccessor Class Reference
#include <private_handle_accessor.h>
Static Public Member Functions
static FlagFastTypeId TypeId (const CommandLineFlag &flag)
static std::unique_ptr< FlagStateInterface > SaveState (CommandLineFlag &flag)
static bool IsSpecifiedOnCommandLine (const CommandLineFlag &flag)
static bool ValidateInputValue (const CommandLineFlag &flag, absl::string_view value)
static void CheckDefaultValueParsingRoundtrip (const CommandLineFlag &flag)
static bool ParseFrom (CommandLineFlag &flag, absl::string_view value, flags_internal::FlagSettingMode set_mode, flags_internal::ValueSource source, std::string &error)
Detailed Description
Definition at line 34 of file private_handle_accessor.h.
Member Function Documentation
CheckDefaultValueParsingRoundtrip()
void absl::flags_internal::PrivateHandleAccessor::CheckDefaultValueParsingRoundtrip (const CommandLineFlag & flag) static
Definition at line 49 of file private_handle_accessor.cc.
{
  flag.CheckDefaultValueParsingRoundtrip();
}
IsSpecifiedOnCommandLine()
bool absl::flags_internal::PrivateHandleAccessor::IsSpecifiedOnCommandLine (const CommandLineFlag & flag) static
Definition at line 39 of file private_handle_accessor.cc.
{
  return flag.IsSpecifiedOnCommandLine();
}
ParseFrom()
bool absl::flags_internal::PrivateHandleAccessor::ParseFrom (CommandLineFlag & flag, absl::string_view value, flags_internal::FlagSettingMode set_mode, flags_internal::ValueSource source, std::string & error) static
Definition at line 54 of file private_handle_accessor.cc.
{
  return flag.ParseFrom(value, set_mode, source, error);
}
References absl::CommandLineFlag::ParseFrom().
Referenced by absl::flags_internal::ParseCommandLineImpl().
SaveState()
std::unique_ptr< FlagStateInterface > absl::flags_internal::PrivateHandleAccessor::SaveState (CommandLineFlag & flag) static
Definition at line 34 of file private_handle_accessor.cc.
{
  return flag.SaveState();
}
Referenced by absl::flags_internal::FlagSaverImpl::SaveFromRegistry().
TypeId()
FlagFastTypeId absl::flags_internal::PrivateHandleAccessor::TypeId (const CommandLineFlag & flag) static
Definition at line 30 of file private_handle_accessor.cc.
{
  return flag.TypeId();
}
Referenced by absl::flags_internal::FlagRegistry::RegisterFlag().
ValidateInputValue()
bool absl::flags_internal::PrivateHandleAccessor::ValidateInputValue (const CommandLineFlag & flag, absl::string_view value) static
Definition at line 44 of file private_handle_accessor.cc.
{
  return flag.ValidateInputValue(value);
}
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/flags/internal/private_handle_accessor.h
open_spiel/abseil-cpp/absl/flags/internal/private_handle_accessor.cc