open spiel: absl::str_format_internal::ConvTag Class Reference
absl::str_format_internal::ConvTag Class Reference
#include <constexpr_parser.h>
Public Member Functions
constexpr ConvTag (FormatConversionChar conversion_char)
constexpr ConvTag (LengthMod length_mod)
constexpr ConvTag (Flags flags)
constexpr ConvTag ()
constexpr bool is_conv () const
constexpr bool is_length () const
constexpr bool is_flags () const
constexpr FormatConversionChar as_conv () const
constexpr LengthMod as_length () const
constexpr Flags as_flags () const
Detailed Description
Definition at line 83 of file constexpr_parser.h.
Constructor & Destructor Documentation
ConvTag() [1/4]
absl::str_format_internal::ConvTag::ConvTag (FormatConversionChar conversion_char) inline constexpr
Definition at line 85 of file constexpr_parser.h.
      : tag_(static_cast<uint8_t>(conversion_char)) {}
ConvTag() [2/4]
absl::str_format_internal::ConvTag::ConvTag (LengthMod length_mod) inline constexpr
Definition at line 87 of file constexpr_parser.h.
      : tag_(0x80 | static_cast<uint8_t>(length_mod)) {}
ConvTag() [3/4]
absl::str_format_internal::ConvTag::ConvTag (Flags flags) inline constexpr
Definition at line 89 of file constexpr_parser.h.
      : tag_(0xc0 | static_cast<uint8_t>(flags)) {}
ConvTag() [4/4]
absl::str_format_internal::ConvTag::ConvTag () inline constexpr
Definition at line 91 of file constexpr_parser.h.
: tag_(0xFF) {}
Member Function Documentation
as_conv()
FormatConversionChar absl::str_format_internal::ConvTag::as_conv () const inline constexpr
Definition at line 97 of file constexpr_parser.h.
{
    assert(is_conv());
    assert(!is_length());
    assert(!is_flags());
    return static_cast<FormatConversionChar>(tag_);
  }
References is_conv(), is_flags(), and is_length().
as_flags()
Flags absl::str_format_internal::ConvTag::as_flags () const inline constexpr
Definition at line 109 of file constexpr_parser.h.
{
    assert(!is_conv());
    assert(!is_length());
    assert(is_flags());
    return static_cast<Flags>(tag_ & 0x1F);
  }
References is_conv(), is_flags(), and is_length().
as_length()
LengthMod absl::str_format_internal::ConvTag::as_length () const inline constexpr
Definition at line 103 of file constexpr_parser.h.
{
    assert(!is_conv());
    assert(is_length());
    assert(!is_flags());
    return static_cast<LengthMod>(tag_ & 0x3F);
  }
References is_conv(), is_flags(), and is_length().
is_conv()
bool absl::str_format_internal::ConvTag::is_conv () const inline constexpr
Definition at line 93 of file constexpr_parser.h.
{ return (tag_ & 0x80) == 0; }
Referenced by as_conv(), as_flags(), and as_length().
is_flags()
bool absl::str_format_internal::ConvTag::is_flags () const inline constexpr
Definition at line 95 of file constexpr_parser.h.
{ return (tag_ & 0xE0) == 0xC0; }
Referenced by as_conv(), as_flags(), and as_length().
is_length()
bool absl::str_format_internal::ConvTag::is_length () const inline constexpr
Definition at line 94 of file constexpr_parser.h.
{ return (tag_ & 0xC0) == 0x80; }
Referenced by as_conv(), as_flags(), and as_length().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/str_format/constexpr_parser.h