open spiel: open_spiel::gin_rummy::GinRummyObserver Class Reference
open_spiel::gin_rummy::GinRummyObserver Class Reference
Public Member Functions
GinRummyObserver (IIGObservationType iig_obs_type)
void WriteTensor (const State &observed_state, int player, Allocator *allocator) const override
std::string StringFrom (const State &observed_state, int player) const override
Public Member Functions inherited from open_spiel::Observer
Observer (bool has_string, bool has_tensor)
bool HasString () const
bool HasTensor () const
virtual ~Observer ()=default
Additional Inherited Members
Protected Attributes inherited from open_spiel::Observer
bool has_string_
bool has_tensor_
Detailed Description
Definition at line 79 of file gin_rummy.cc.
Constructor & Destructor Documentation
GinRummyObserver()
open_spiel::gin_rummy::GinRummyObserver::GinRummyObserver (IIGObservationType iig_obs_type) inline explicit
Definition at line 81 of file gin_rummy.cc.
      : Observer(/*has_string=*/ObserverHasString(iig_obs_type),
                 /*has_tensor=*/ObserverHasTensor(iig_obs_type)),
        iig_obs_type_(iig_obs_type) {}
Member Function Documentation
StringFrom()
std::string open_spiel::gin_rummy::GinRummyObserver::StringFrom (const State & observed_state, int player) const inline override virtual
Implements open_spiel::Observer.
Definition at line 119 of file gin_rummy.cc.
{
    auto& state = open_spiel::down_cast<const GinRummyState&>(observed_state);
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, state.num_players_);
    if (iig_obs_type_.perfect_recall) {
      if (iig_obs_type_.public_info &&
          iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
        return state.aohs_[player].ToString();
      } else {
        SpielFatalError(
            "GinRummyObserver: string with perfect recall is implemented only"
            " for the (default) info state observation type.");
      }
    }
    std::string rv;
    absl::StrAppend(&rv, "\nKnock card: ", state.knock_card_);
    absl::StrAppend(&rv, "\nPrev upcard: ",
                    state.utils_.CardString(state.prev_upcard_));
    absl::StrAppend(&rv, "\nRepeated move: ", state.repeated_move_);
    absl::StrAppend(&rv, "\nCurrent player: ", state.cur_player_);
    absl::StrAppend(&rv, "\nPhase: ",
                    GinRummyState::kPhaseString[static_cast<int>(state.phase_)],
                    "\n");
    if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers ||
        (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer &&
        player == 0)) {
      absl::StrAppend(&rv, "\nPlayer0: Deadwood=", state.deadwood_[0]);
    } else {
      absl::StrAppend(&rv, "\nPlayer0:");
    }
    if (state.knocked_[1] && !state.layoffs_.empty()) {
      absl::StrAppend(&rv, "\nLayoffs: ");
      for (int card : state.layoffs_) {
        absl::StrAppend(&rv, state.utils_.CardString(card));
      }
    }
    if (!state.layed_melds_[0].empty()) {
      absl::StrAppend(&rv, "\nLayed melds:");
      for (int meld_id : state.layed_melds_[0]) {
        absl::StrAppend(&rv, " ");
        std::vector<int> meld = state.utils_.int_to_meld.at(meld_id);
        for (int card : meld) {
          absl::StrAppend(&rv, state.utils_.CardString(card));
        }
      }
    }
    if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers ||
        (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer &&
        player == 0)) {
      absl::StrAppend(&rv, "\n", state.utils_.HandToString(state.hands_[0]));
    } else {
      absl::StrAppend(&rv, "\n", state.utils_.HandToString(std::vector<int>()));
    }
    absl::StrAppend(&rv, "\nStock size: ", state.stock_size_);
    absl::StrAppend(&rv, "  Upcard: ", state.utils_.CardString(state.upcard_));
    absl::StrAppend(&rv, "\nDiscard pile: ");
    for (int card : state.discard_pile_) {
      absl::StrAppend(&rv, state.utils_.CardString(card));
    }
    if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers ||
        (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer &&
        player == 1)) {
      absl::StrAppend(&rv, "\n\nPlayer1: Deadwood=", state.deadwood_[1]);
    } else {
      absl::StrAppend(&rv, "\n\nPlayer1:");
    }
    if (state.knocked_[0] && !state.layoffs_.empty()) {
      absl::StrAppend(&rv, "\nLayoffs: ");
      for (int card : state.layoffs_) {
        absl::StrAppend(&rv, state.utils_.CardString(card));
      }
    }
    if (!state.layed_melds_[1].empty()) {
      absl::StrAppend(&rv, "\nLayed melds:");
      for (int meld_id : state.layed_melds_[1]) {
        absl::StrAppend(&rv, " ");
        std::vector<int> meld = state.utils_.int_to_meld.at(meld_id);
        for (int card : meld) {
          absl::StrAppend(&rv, state.utils_.CardString(card));
        }
      }
    }
    if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers ||
        (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer &&
        player == 1)) {
      absl::StrAppend(&rv, "\n", state.utils_.HandToString(state.hands_[1]));
    } else {
      absl::StrAppend(&rv, "\n", state.utils_.HandToString(std::vector<int>()));
    }
    return rv;
  }
References open_spiel::down_cast(), open_spiel::kAllPlayers, open_spiel::kSinglePlayer, open_spiel::IIGObservationType::perfect_recall, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), state, and absl::StrAppend().
WriteTensor()
void open_spiel::gin_rummy::GinRummyObserver::WriteTensor (const State & observed_state, int player, Allocator * allocator) const inline override virtual
Implements open_spiel::Observer.
Definition at line 87 of file gin_rummy.cc.
{
    auto& state = open_spiel::down_cast<const GinRummyState&>(observed_state);
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, state.num_players_);
    if (iig_obs_type_.perfect_recall) {
      SpielFatalError(
          "GinRummyObserver: tensor with perfect recall not implemented.");
    }
    // Observing player.
    WriteObservingPlayer(state, player, allocator);
    // Private hand(s).
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      WriteSinglePlayerHand(state, player, allocator);
    } else if (iig_obs_type_.private_info == PrivateInfoType::kAllPlayers) {
      WriteAllPlayerHands(state, allocator);
    }
    // Public information.
    if (iig_obs_type_.public_info) {
      WriteCurrentPlayer(state, allocator);
      WriteKnockCard(state, allocator);
      WriteUpcard(state, allocator);
      WriteDiscardPile(state, allocator);
      WriteStockSize(state, allocator);
      WriteLayedMelds(state, allocator);
    }
  }
References open_spiel::down_cast(), open_spiel::kAllPlayers, open_spiel::kSinglePlayer, open_spiel::IIGObservationType::perfect_recall, player, open_spiel::IIGObservationType::private_info, open_spiel::IIGObservationType::public_info, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and state.
The documentation for this class was generated from the following file:
open_spiel/games/gin_rummy/gin_rummy.cc