open spiel: open_spiel::dynamic_routing::MeanFieldRoutingGameState Class Reference
open_spiel::dynamic_routing::MeanFieldRoutingGameState Class Reference
#include <dynamic_routing.h>
Public Member Functions
Action GetLocationAsActionInt () const
Action GetDestinationAsActionInt () const
int CurrentTimeStamp () const
const Network * network () const
bool IsWaiting () const
Player CurrentPlayer () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ActionToString (Player player, Action action) const override
std::unique_ptr< State > Clone () const override
std::string ToString () const override
std::string Serialize () const override
std::string StateToString (std::string location, int time_step, Player player_id=PlayerId::kDefaultPlayerId, int waiting_time=0, std::string destination="", double ret=0) const
std::vector< std::string > DistributionSupport () override
void UpdateDistribution (const std::vector< double > &distribution) override
ActionsAndProbs ChanceOutcomes () const override
std::vector< Action > LegalActions () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual int MeanFieldPopulation () const
Static Public Member Functions
static std::unique_ptr< MeanFieldRoutingGameState > CreateNewInitialState (std::shared_ptr< const Game > game, double time_step_length, std::vector< OriginDestinationDemand > *od_demand, Network *network, bool perform_sanity_checks=true)
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Friends
class MeanFieldRoutingGame
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 73 of file dynamic_routing.h.
Member Function Documentation
ActionToString()
std::string open_spiel::dynamic_routing::MeanFieldRoutingGameState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 330 of file dynamic_routing.cc.
{
  SPIEL_CHECK_NE(player, PlayerId::kMeanFieldPlayerId);
  if (player == PlayerId::kChancePlayerId) {
    SPIEL_CHECK_TRUE(is_chance_init_);
    return absl::StrFormat("Vehicle is assigned to population %d", action);
  }
  if (perform_sanity_checks_) {
    SPIEL_CHECK_EQ(player, kDefaultPlayerId);
  }
  if (action == kNoPossibleAction) {
    return absl::StrFormat("Vehicle %d reach a sink node or its destination.",
                           player);
  }
  if (perform_sanity_checks_) {
    network_->AssertValidAction(action);
  }
  return absl::StrFormat("Vehicle %d would like to move to %s.", player,
                         network_->GetRoadSectionFromActionId(action));
}
References action, open_spiel::dynamic_routing::Network::AssertValidAction(), open_spiel::dynamic_routing::Network::GetRoadSectionFromActionId(), open_spiel::kChancePlayerId, open_spiel::kDefaultPlayerId, open_spiel::kMeanFieldPlayerId, open_spiel::dynamic_routing::kNoPossibleAction, player, SPIEL_CHECK_EQ, SPIEL_CHECK_NE, SPIEL_CHECK_TRUE, and absl::StrFormat().
ChanceOutcomes()
ActionsAndProbs open_spiel::dynamic_routing::MeanFieldRoutingGameState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 433 of file dynamic_routing.cc.
{
  SPIEL_CHECK_NE(current_player_id_, PlayerId::kMeanFieldPlayerId);
  if (perform_sanity_checks_) {
    SPIEL_CHECK_EQ(current_player_id_, PlayerId::kChancePlayerId);
    SPIEL_CHECK_TRUE(is_chance_init_);
  }
  return chance_outcomes_;
}
References open_spiel::kChancePlayerId, open_spiel::kMeanFieldPlayerId, SPIEL_CHECK_EQ, SPIEL_CHECK_NE, and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::dynamic_routing::MeanFieldRoutingGameState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 442 of file dynamic_routing.cc.
{
  return absl::make_unique<MeanFieldRoutingGameState>(*this);
}
CreateNewInitialState()
std::unique_ptr< MeanFieldRoutingGameState > open_spiel::dynamic_routing::MeanFieldRoutingGameState::CreateNewInitialState (std::shared_ptr< const Game > game, double time_step_length, std::vector< OriginDestinationDemand > * od_demand, Network * network, bool perform_sanity_checks = true) static
Definition at line 166 of file dynamic_routing.cc.
{
  return MeanFieldRoutingGameState::Create(
      game, time_step_length, od_demand, network, perform_sanity_checks,
      /* current_time_step= */ 0,
      /* player_id = */ open_spiel::PlayerId::kChancePlayerId,
      /* is_chance_init = */ true,
      /* is_terminal = */ false,
      /* vehicle_at_destination = */ false,
      /* vehicle_without_legal_action = */ false,
      /* waiting_time = */ kWaitingTimeNotAssigned,
      /* vehicle_final_travel_time = */ 0.0,
      /* vehicle_location = */ "",
      /* vehicle_destination = */ "");
}
References open_spiel::kChancePlayerId, open_spiel::dynamic_routing::kWaitingTimeNotAssigned, and network().
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGame::NewInitialState().
CurrentPlayer()
int open_spiel::dynamic_routing::MeanFieldRoutingGameState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 364 of file dynamic_routing.cc.
{
  return current_player_id_;
}
Referenced by LegalActions().
CurrentTimeStamp()
int open_spiel::dynamic_routing::MeanFieldRoutingGameState::CurrentTimeStamp () const
Definition at line 360 of file dynamic_routing.cc.
{
  return current_time_step_;
}
DistributionSupport()
std::vector< std::string > open_spiel::dynamic_routing::MeanFieldRoutingGameState::DistributionSupport () override virtual
Reimplemented from open_spiel::State.
Definition at line 382 of file dynamic_routing.cc.
{
  if (vehicle_without_legal_action_) {
    return {};
  }
  std::vector<std::string> dist;
  for (int waiting_time = kWaitingTimeNotAssigned;
       waiting_time < max_travel_time_; waiting_time++) {
    for (const auto& od : *(od_demand_)) {
      std::string destination = od.vehicle.destination;
      std::string value =
          StateToString(vehicle_location_, current_time_step_,
                        PlayerId::kMeanFieldPlayerId, waiting_time, destination,
                        /*ret = */ 0.0);
      dist.push_back(value);
    }
  }
  absl::btree_set<std::string> dist_set(dist.begin(), dist.end());
  SPIEL_CHECK_EQ(dist_set.size(), dist.size());
  return dist;
}
References open_spiel::kMeanFieldPlayerId, open_spiel::dynamic_routing::kWaitingTimeNotAssigned, absl::container_internal::btree_container< Tree >::size(), SPIEL_CHECK_EQ, and StateToString().
DoApplyAction()
void open_spiel::dynamic_routing::MeanFieldRoutingGameState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 274 of file dynamic_routing.cc.
{
  if (perform_sanity_checks_) {
    SPIEL_CHECK_TRUE(!IsTerminal());
    SPIEL_CHECK_NE(current_player_id_, PlayerId::kMeanFieldPlayerId);
  }
  switch (current_player_id_) {
    case PlayerId::kChancePlayerId: {
      current_player_id_ = PlayerId::kDefaultPlayerId;
      SPIEL_CHECK_EQ(is_chance_init_, true);
      auto od_demand = od_demand_->at(action);
      vehicle_destination_ = od_demand.vehicle.destination;
      vehicle_location_ = od_demand.vehicle.origin;
      waiting_time_ = static_cast<int>(od_demand.vehicle.departure_time /
                                       time_step_length_);
      is_chance_init_ = false;
      break;
    }
    case PlayerId::kDefaultPlayerId: {
      current_player_id_ = PlayerId::kMeanFieldPlayerId;
      if (!vehicle_without_legal_action_) {
        if (waiting_time_ > 0) {
          waiting_time_ -= 1;
        } else {
          if (perform_sanity_checks_) {
            network_->AssertValidAction(action, vehicle_location_);
          }
          vehicle_location_ = network_->GetRoadSectionFromActionId(action);
          if (vehicle_location_ == vehicle_destination_) {
            vehicle_final_travel_time_ = current_time_step_;
            vehicle_at_destination_ = true;
            vehicle_without_legal_action_ = true;
          } else if (network_->IsLocationASinkNode(vehicle_location_)) {
            vehicle_without_legal_action_ = true;
            vehicle_final_travel_time_ = -1 * GetGame()->MinUtility();
          } else {
            waiting_time_ = kWaitingTimeNotAssigned;
          }
        }
      }
      current_time_step_ += 1;
      break;
    }
    default:
      SpielFatalError(absl::StrCat("Unsupported Player ID in DoApplyAction(): ",
                                   current_player_id_));
  }
  if (current_time_step_ >= GetGame()->MaxGameLength()) {
    is_terminal_ = true;
    current_player_id_ = PlayerId::kTerminalPlayerId;
    if (!vehicle_at_destination_) {
      vehicle_final_travel_time_ = -1 * GetGame()->MinUtility();
    }
  }
}
References action, open_spiel::dynamic_routing::Network::AssertValidAction(), open_spiel::State::GetGame(), open_spiel::dynamic_routing::Network::GetRoadSectionFromActionId(), open_spiel::dynamic_routing::Network::IsLocationASinkNode(), IsTerminal(), open_spiel::kChancePlayerId, open_spiel::kDefaultPlayerId, open_spiel::kMeanFieldPlayerId, open_spiel::kTerminalPlayerId, open_spiel::dynamic_routing::kWaitingTimeNotAssigned, SPIEL_CHECK_EQ, SPIEL_CHECK_NE, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), and absl::StrCat().
GetDestinationAsActionInt()
Action open_spiel::dynamic_routing::MeanFieldRoutingGameState::GetDestinationAsActionInt () const
Definition at line 356 of file dynamic_routing.cc.
{
  return network_->GetRoadSectionAsInt(vehicle_destination_);
}
References open_spiel::dynamic_routing::Network::GetRoadSectionAsInt().
GetLocationAsActionInt()
Action open_spiel::dynamic_routing::MeanFieldRoutingGameState::GetLocationAsActionInt () const
Definition at line 352 of file dynamic_routing.cc.
{
  return network_->GetRoadSectionAsInt(vehicle_location_);
}
References open_spiel::dynamic_routing::Network::GetRoadSectionAsInt().
InformationStateString()
std::string open_spiel::dynamic_routing::MeanFieldRoutingGameState::InformationStateString (Player player) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 159 of file dynamic_routing.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, num_players_);
    return HistoryString();
  }
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::dynamic_routing::MeanFieldRoutingGameState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 368 of file dynamic_routing.cc.
{ return is_terminal_; }
Referenced by DoApplyAction(), and Returns().
IsWaiting()
bool open_spiel::dynamic_routing::MeanFieldRoutingGameState::IsWaiting () const
Definition at line 370 of file dynamic_routing.cc.
{ return waiting_time_ > 0; }
LegalActions()
std::vector< Action > open_spiel::dynamic_routing::MeanFieldRoutingGameState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 241 of file dynamic_routing.cc.
{
  if (is_terminal_) {
    return {};
  }
  SPIEL_CHECK_NE(CurrentPlayer(), kMeanFieldPlayerId);
  if (CurrentPlayer() == kChancePlayerId) {
    return LegalChanceOutcomes();
  }
  if (perform_sanity_checks_) {
    SPIEL_CHECK_EQ(CurrentPlayer(), kDefaultPlayerId);
  }
  if (waiting_time_ > 0) {
    return {kNoPossibleAction};
  }
  if (vehicle_without_legal_action_) {
    return {kNoPossibleAction};
  }
  std::string end_section_node = NodesFromRoadSection(vehicle_location_)[1];
  std::vector<std::string> successors =
      network_->GetSuccessors(end_section_node);
  if (perform_sanity_checks_) {
    SPIEL_CHECK_TRUE(!successors.empty());
  }
  std::vector<Action> actions;
  for (const auto& d : successors) {
    Action action = network_->GetActionIdFromMovement(end_section_node, d);
    network_->AssertValidAction(action);
    actions.push_back(action);
  }
  std::sort(actions.begin(), actions.end());
  return actions;
}
References action, open_spiel::dynamic_routing::Network::AssertValidAction(), CurrentPlayer(), open_spiel::dynamic_routing::Network::GetActionIdFromMovement(), open_spiel::dynamic_routing::Network::GetSuccessors(), open_spiel::kChancePlayerId, open_spiel::kDefaultPlayerId, open_spiel::kMeanFieldPlayerId, open_spiel::dynamic_routing::kNoPossibleAction, open_spiel::State::LegalChanceOutcomes(), open_spiel::dynamic_routing::NodesFromRoadSection(), SPIEL_CHECK_EQ, SPIEL_CHECK_NE, and SPIEL_CHECK_TRUE.
network()
const Network * open_spiel::dynamic_routing::MeanFieldRoutingGameState::network () const
Definition at line 372 of file dynamic_routing.cc.
{ return network_; }
Referenced by open_spiel.python.games.dynamic_routing.DynamicRoutingGame::__init__(), open_spiel.python.mfg.games.dynamic_routing.MeanFieldRoutingGame::__init__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver::_network_jit_apply(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver::_network_jit_apply_and_post_process(), CreateNewInitialState(), open_spiel.python.pytorch.ppo.PPO::get_action_and_value(), open_spiel.python.pytorch.ppo.PPOAtariAgent::get_action_and_value(), open_spiel.python.mfg.games.dynamic_routing.MeanFieldRoutingGame::get_road_section_as_int(), open_spiel.python.pytorch.ppo.PPO::get_value(), open_spiel.python.pytorch.ppo.PPOAtariAgent::get_value(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver::loss(), open_spiel.python.mfg.games.dynamic_routing.MeanFieldRoutingGame::make_py_observer(), open_spiel.python.games.dynamic_routing_utils_test.NetworkTest::test_adjacency_list_init(), open_spiel.python.games.dynamic_routing_utils_test.NetworkTest::test_get_action_id_with_wrong_nodes(), open_spiel.python.games.dynamic_routing_utils_test.NetworkTest::test_get_action_id_without_connected_nodes(), open_spiel.python.games.dynamic_routing_utils_test.NetworkTest::test_get_road_section_with_action_id(), open_spiel.python.games.dynamic_routing_utils_test.NetworkTest::test_get_successors_with_wrong_node(), open_spiel.python.games.dynamic_routing_utils_test.NetworkTest::test_is_location_at_sink_noded_with_wrong_arg(), open_spiel.python.games.dynamic_routing_utils_test.NetworkTest::test_is_location_at_sink_noded_with_wrong_road_section(), and open_spiel.python.games.dynamic_routing_utils_test.NetworkTest::test_is_location_at_sink_noded_with_wrong_road_section_2().
ObservationString()
std::string open_spiel::dynamic_routing::MeanFieldRoutingGameState::ObservationString (Player player) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 165 of file dynamic_routing.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, num_players_);
    return ToString();
  }
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
Returns()
std::vector< double > open_spiel::dynamic_routing::MeanFieldRoutingGameState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 374 of file dynamic_routing.cc.
{
  if (!IsTerminal()) {
    return std::vector<double>{0};
  }
  double ret = -vehicle_final_travel_time_ * time_step_length_;
  return std::vector<double>{ret};
}
References IsTerminal().
Referenced by ToString().
Serialize()
std::string open_spiel::dynamic_routing::MeanFieldRoutingGameState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 446 of file dynamic_routing.cc.
{
  return absl::StrCat(current_time_step_, ",", current_player_id_, ",",
                      is_chance_init_, ",", is_terminal_, ",",
                      vehicle_at_destination_, ",",
                      vehicle_without_legal_action_, ",", waiting_time_, ",",
                      vehicle_final_travel_time_, ",", vehicle_location_, ",",
                      vehicle_destination_);
}
References absl::StrCat().
StateToString()
std::string open_spiel::dynamic_routing::MeanFieldRoutingGameState::StateToString (std::string location, int time_step, Player player_id = PlayerId::kDefaultPlayerId, int waiting_time = 0, std::string destination = "", double ret = 0) const
Definition at line 212 of file dynamic_routing.cc.
{
  std::string time;
  if (destination.empty()) {
    destination = vehicle_destination_;
  }
  if (is_chance_init_) {
    return "initial chance node";
  }
  if (player_id == PlayerId::kDefaultPlayerId ||
      player_id == PlayerId::kTerminalPlayerId) {
    time = absl::StrCat(time_step);
  } else if (player_id == PlayerId::kMeanFieldPlayerId) {
    time = absl::StrFormat("%d_mean_field", time_step);
  } else if (player_id == PlayerId::kChancePlayerId) {
    time = absl::StrFormat("%d_chance", time_step);
  } else {
    SpielFatalError(
        "Player id should be DEFAULT_PLAYER_ID, MEAN_FIELD or CHANCE");
  }
  if (vehicle_final_travel_time_ != 0.0) {
    return absl::StrFormat("Arrived at %s, with arrival time %.2f, t=%s",
                           location, vehicle_final_travel_time_, time);
  }
  return absl::StrFormat("Location=%s, waiting time=%d, t=%s, destination=%s",
                         location, waiting_time, time, destination);
}
References open_spiel::kChancePlayerId, open_spiel::kDefaultPlayerId, open_spiel::kMeanFieldPlayerId, open_spiel::kTerminalPlayerId, open_spiel::SpielFatalError(), absl::StrCat(), and absl::StrFormat().
Referenced by DistributionSupport(), and ToString().
ToString()
std::string open_spiel::dynamic_routing::MeanFieldRoutingGameState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 455 of file dynamic_routing.cc.
{
  if (!vehicle_location_.empty()) {
    return StateToString(vehicle_location_, current_time_step_,
                         current_player_id_, waiting_time_,
                         vehicle_destination_, Returns()[0]);
  }
  SPIEL_CHECK_EQ(current_time_step_, 0);
  return "Before initial chance node.";
}
References Returns(), SPIEL_CHECK_EQ, and StateToString().
Referenced by ObservationString().
UpdateDistribution()
void open_spiel::dynamic_routing::MeanFieldRoutingGameState::UpdateDistribution (const std::vector< double > & distribution) override virtual
Reimplemented from open_spiel::State.
Definition at line 403 of file dynamic_routing.cc.
{
  if (current_player_id_ == PlayerId::kTerminalPlayerId) {
    return;
  }
  if (perform_sanity_checks_) {
    SPIEL_CHECK_EQ(current_player_id_, PlayerId::kMeanFieldPlayerId);
  }
  current_player_id_ = PlayerId::kDefaultPlayerId;
  if (!vehicle_without_legal_action_) {
    double normed_density_on_vehicle_link = 0;
    for (const double& d : distribution) {
      normed_density_on_vehicle_link += d;
    }
    if (perform_sanity_checks_) {
      SPIEL_CHECK_GE(normed_density_on_vehicle_link, 0);
      SPIEL_CHECK_LE(normed_density_on_vehicle_link, 1 + kEpsilon);
    }
    if (waiting_time_ == kWaitingTimeNotAssigned) {
      double volume = total_num_vehicle_ * normed_density_on_vehicle_link;
      waiting_time_ =
          static_cast<int>(network_->GetTravelTime(vehicle_location_, volume) /
                           time_step_length_) -
          1;
      waiting_time_ = std::max(0, waiting_time_);
    }
  }
}
References open_spiel::dynamic_routing::Network::GetTravelTime(), open_spiel::kDefaultPlayerId, open_spiel::kMeanFieldPlayerId, open_spiel::kTerminalPlayerId, open_spiel::dynamic_routing::kWaitingTimeNotAssigned, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Friends And Related Symbol Documentation
MeanFieldRoutingGame
friend class MeanFieldRoutingGame friend
Definition at line 244 of file dynamic_routing.h.
The documentation for this class was generated from the following files:
open_spiel/games/mfg/dynamic_routing.h
open_spiel/games/mfg/dynamic_routing.cc