open spiel: open_spiel::MisereState Class Reference
open_spiel::MisereState Class Reference
#include <misere.h>
Public Member Functions
MisereState (std::shared_ptr< const Game > game, std::unique_ptr< State > state)
MisereState (const MisereState &other)=default
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
Public Member Functions inherited from open_spiel::WrappedState
WrappedState (std::shared_ptr< const Game > game, std::unique_ptr< State > state)
WrappedState (const WrappedState &other)
Player CurrentPlayer () const override
std::vector< Action > LegalActions (Player player) const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
void UndoAction (Player player, Action action) override
ActionsAndProbs ChanceOutcomes () const override
std::vector< Action > LegalChanceOutcomes () const override
const State & GetWrappedState () const
std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::WrappedState
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &actions) override
Protected Attributes inherited from open_spiel::WrappedState
std::unique_ptr< State > state_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 35 of file misere.h.
Constructor & Destructor Documentation
MisereState() [1/2]
open_spiel::MisereState::MisereState (std::shared_ptr< const Game > game, std::unique_ptr< State > state) inline
Definition at line 37 of file misere.h.
      : WrappedState(game, std::move(state)) {}
Referenced by Clone().
MisereState() [2/2]
open_spiel::MisereState::MisereState (const MisereState & other) default
Member Function Documentation
Clone()
std::unique_ptr< State > open_spiel::MisereState::Clone () const inline override virtual
Implements open_spiel::WrappedState.
Definition at line 49 of file misere.h.
{
    return std::unique_ptr<State>(new MisereState(*this));
  }
References MisereState().
Returns()
std::vector< double > open_spiel::MisereState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 45 of file misere.h.
{
    return Negative(state_->Returns());
  }
References open_spiel::Negative(), and open_spiel::WrappedState::state_.
Rewards()
std::vector< double > open_spiel::MisereState::Rewards () const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 41 of file misere.h.
{
    return Negative(state_->Rewards());
  }
References open_spiel::Negative(), and open_spiel::WrappedState::state_.
The documentation for this class was generated from the following file:
open_spiel/game_transforms/misere.h