open spiel: open_spiel::bargaining::BargainingGame Class Reference
open_spiel::bargaining::BargainingGame Class Reference
#include <bargaining.h>
Public Member Functions
BargainingGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
std::string ActionToString (Player player, Action move_id) const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int NumPlayers () const override
double MaxUtility () const override
double MinUtility () const override
std::vector< int > ObservationTensorShape () const override
std::vector< int > InformationStateTensorShape () const override
int max_turns () const
double discount () const
double prob_end () const
Action ContinueOutcome () const
Action EndOutcome () const
const std::vector< Instance > & AllInstances () const
const std::vector< Offer > & AllOffers () const
const Instance & GetInstance (int num) const
const Offer & GetOffer (int num) const
std::pair< Offer, Action > GetOfferByQuantities (const std::vector< int > &quantities) const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 151 of file bargaining.h.
Constructor & Destructor Documentation
BargainingGame()
open_spiel::bargaining::BargainingGame::BargainingGame (const GameParameters & params) explicit
Definition at line 501 of file bargaining.cc.
    : Game(kGameType, params),
      max_turns_(ParameterValue<int>("max_turns", kDefaultMaxTurns)),
      discount_(ParameterValue<double>("discount", kDefaultDiscount)),
      prob_end_(ParameterValue<double>("prob_end", kDefaultProbEnd)) {
  std::string filename = ParameterValue<std::string>("instances_file", "");
  if (!filename.empty()) {
    ParseInstancesFile(filename);
  } else {
    ParseInstancesString(kDefaultInstancesString);
  }
  CreateOffers();
}
References open_spiel::bargaining::kDefaultInstancesString, and open_spiel::Game::ParameterValue().
Member Function Documentation
ActionToString()
std::string open_spiel::bargaining::BargainingGame::ActionToString (Player player, Action move_id) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 515 of file bargaining.cc.
{
  if (player == kChancePlayerId) {
    return absl::StrCat("Chance outcome ", move_id);
  } else if (move_id < all_offers_.size()) {
    return all_offers_[move_id].ToString();
  } else {
    SPIEL_CHECK_EQ(move_id, all_offers_.size());
    return "Agree";
  }
}
References open_spiel::kChancePlayerId, player, SPIEL_CHECK_EQ, and absl::StrCat().
Referenced by open_spiel::bargaining::BargainingState::ActionToString().
AllInstances()
const std::vector< Instance > & open_spiel::bargaining::BargainingGame::AllInstances () const inline
Definition at line 178 of file bargaining.h.
{ return all_instances_; }
Referenced by open_spiel::bargaining::BargainingState::ChanceOutcomes(), and open_spiel::bargaining::BargainingState::ResampleFromInfostate().
AllOffers()
const std::vector< Offer > & open_spiel::bargaining::BargainingGame::AllOffers () const inline
Definition at line 179 of file bargaining.h.
{ return all_offers_; }
Referenced by open_spiel::bargaining::BargainingState::AgreeAction(), open_spiel::bargaining::BargainingState::DoApplyAction(), and open_spiel::bargaining::BargainingState::LegalActions().
ContinueOutcome()
Action open_spiel::bargaining::BargainingGame::ContinueOutcome () const inline
Definition at line 175 of file bargaining.h.
{ return all_instances_.size(); }
Referenced by open_spiel::bargaining::BargainingState::ChanceOutcomes(), and open_spiel::bargaining::BargainingState::DoApplyAction().
discount()
double open_spiel::bargaining::BargainingGame::discount () const inline
Definition at line 172 of file bargaining.h.
{ return discount_; }
Referenced by open_spiel::bargaining::BargainingState::DoApplyAction(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::update(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.regmatch.Solver::update(), and open_spiel.python.algorithms.adidas_utils.solvers.symmetric.regmatch.Solver::update().
EndOutcome()
Action open_spiel::bargaining::BargainingGame::EndOutcome () const inline
Definition at line 176 of file bargaining.h.
{ return all_instances_.size() + 1; }
Referenced by open_spiel::bargaining::BargainingState::ChanceOutcomes(), and open_spiel::bargaining::BargainingState::DoApplyAction().
GetInstance()
const Instance & open_spiel::bargaining::BargainingGame::GetInstance (int num) const inline
Definition at line 180 of file bargaining.h.
{ return all_instances_[num]; }
References num.
Referenced by open_spiel::bargaining::BargainingState::DoApplyAction(), and open_spiel::bargaining::BargainingState::ResampleFromInfostate().
GetOffer()
const Offer & open_spiel::bargaining::BargainingGame::GetOffer (int num) const inline
Definition at line 181 of file bargaining.h.
{ return all_offers_[num]; }
References num.
GetOfferByQuantities()
std::pair< Offer, Action > open_spiel::bargaining::BargainingGame::GetOfferByQuantities (const std::vector< int > & quantities) const
Definition at line 532 of file bargaining.cc.
{
  for (int i = 0; i < all_offers_.size(); ++i) {
    if (quantities == all_offers_[i].quantities) {
      return {all_offers_[i], i};
    }
  }
  return {Offer(), kInvalidAction};
}
References i, and open_spiel::kInvalidAction.
InformationStateTensorShape()
std::vector< int > open_spiel::bargaining::BargainingGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 553 of file bargaining.cc.
{
  return {
      1 +                                       // Agreement reached?
      max_turns_ + 1 +                          // How many offers have happened
      (kPoolMaxNumItems + 1) * kNumItemTypes +  // Pool
      (kTotalValueAllItems + 1) * kNumItemTypes +          // My values
      max_turns_ * (kPoolMaxNumItems + 1) * kNumItemTypes  // Offers
  };
}
References open_spiel::bargaining::kNumItemTypes, open_spiel::bargaining::kPoolMaxNumItems, and open_spiel::bargaining::kTotalValueAllItems.
max_turns()
int open_spiel::bargaining::BargainingGame::max_turns () const inline
Definition at line 171 of file bargaining.h.
{ return max_turns_; }
Referenced by open_spiel::bargaining::BargainingState::InformationStateTensor(), open_spiel::bargaining::BargainingState::IsTerminal(), and open_spiel::bargaining::BargainingState::ObservationTensor().
MaxChanceNodesInHistory()
int open_spiel::bargaining::BargainingGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 163 of file bargaining.h.
{ return 1 + (max_turns_ - 2); }
MaxChanceOutcomes()
int open_spiel::bargaining::BargainingGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 159 of file bargaining.h.
{ return all_instances_.size() + 2; }
MaxGameLength()
int open_spiel::bargaining::BargainingGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 162 of file bargaining.h.
{ return max_turns_; }
MaxUtility()
double open_spiel::bargaining::BargainingGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 166 of file bargaining.h.
{ return kTotalValueAllItems; }
References open_spiel::bargaining::kTotalValueAllItems.
MinUtility()
double open_spiel::bargaining::BargainingGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 167 of file bargaining.h.
{ return 0; }
NewInitialState()
std::unique_ptr< State > open_spiel::bargaining::BargainingGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 156 of file bargaining.h.
{
    return std::unique_ptr<State>(new BargainingState(shared_from_this()));
  }
Referenced by open_spiel::bargaining::BargainingState::ResampleFromInfostate().
NumDistinctActions()
int open_spiel::bargaining::BargainingGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 527 of file bargaining.cc.
{
  // All offers + agree.
  return all_offers_.size() + 1;
}
NumPlayers()
int open_spiel::bargaining::BargainingGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 165 of file bargaining.h.
{ return kNumPlayers; }
References open_spiel::bargaining::kNumPlayers.
ObservationTensorShape()
std::vector< int > open_spiel::bargaining::BargainingGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 543 of file bargaining.cc.
{
  return {
      1 +                                       // Agreement reached?
      max_turns_ + 1 +                          // How many offers have happened
      (kPoolMaxNumItems + 1) * kNumItemTypes +  // Pool
      (kTotalValueAllItems + 1) * kNumItemTypes +  // My values
      (kPoolMaxNumItems + 1) * kNumItemTypes       // Most recent offer
  };
}
References open_spiel::bargaining::kNumItemTypes, open_spiel::bargaining::kPoolMaxNumItems, and open_spiel::bargaining::kTotalValueAllItems.
prob_end()
double open_spiel::bargaining::BargainingGame::prob_end () const inline
Definition at line 173 of file bargaining.h.
{ return prob_end_; }
Referenced by open_spiel::bargaining::BargainingState::ChanceOutcomes(), and open_spiel::bargaining::BargainingState::DoApplyAction().
The documentation for this class was generated from the following files:
open_spiel/games/bargaining/bargaining.h
open_spiel/games/bargaining/bargaining.cc