open spiel: open_spiel::ultimate_tic_tac_toe::UltimateTTTState Class Reference
open_spiel::ultimate_tic_tac_toe::UltimateTTTState Class Reference
#include <ultimate_tic_tac_toe.h>
Public Member Functions
UltimateTTTState (std::shared_ptr< const Game > game)
UltimateTTTState (const UltimateTTTState &other)
UltimateTTTState & operator= (const UltimateTTTState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action move) override
std::vector< Action > LegalActions () const override
void DoApplyAction (Action move) override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 40 of file ultimate_tic_tac_toe.h.
Constructor & Destructor Documentation
UltimateTTTState() [1/2]
open_spiel::ultimate_tic_tac_toe::UltimateTTTState::UltimateTTTState (std::shared_ptr< const Game > game)
Definition at line 135 of file ultimate_tic_tac_toe.cc.
    : State(game),
      ttt_game_(
          static_cast<const UltimateTTTGame*>(game.get())->TicTacToeGame()),
      current_state_(-1) {
  std::fill(meta_board_.begin(), meta_board_.end(), ttt::CellState::kEmpty);
  for (int i = 0; i < ttt::kNumCells; ++i) {
    local_states_[i] = ttt_game_->NewInitialState();
  }
}
References i, open_spiel::tic_tac_toe::kNumCells, and open_spiel::tic_tac_toe::TicTacToeGame::NewInitialState().
Referenced by Clone().
UltimateTTTState() [2/2]
open_spiel::ultimate_tic_tac_toe::UltimateTTTState::UltimateTTTState (const UltimateTTTState & other)
Definition at line 218 of file ultimate_tic_tac_toe.cc.
    : State(other),
      current_player_(other.current_player_),
      outcome_(other.outcome_),
      ttt_game_(other.ttt_game_),
      current_state_(other.current_state_) {
  for (int i = 0; i < ttt::kNumCells; ++i) {
    meta_board_[i] = other.meta_board_[i];
    local_states_[i] = other.local_states_[i]->Clone();
  }
}
References i, and open_spiel::tic_tac_toe::kNumCells.
Member Function Documentation
ActionToString()
std::string open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 124 of file ultimate_tic_tac_toe.cc.
{
  if (current_state_ < 0) {
    return absl::StrCat("Choose local board ", action_id);
  } else {
    return absl::StrCat(
        "Local board ", current_state_, ": ",
        local_states_[current_state_]->ActionToString(player, action_id));
  }
}
References ActionToString(), player, and absl::StrCat().
Referenced by ActionToString().
Clone()
std::unique_ptr< State > open_spiel::ultimate_tic_tac_toe::UltimateTTTState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 230 of file ultimate_tic_tac_toe.cc.
{
  return std::unique_ptr<State>(new UltimateTTTState(*this));
}
References UltimateTTTState().
CurrentPlayer()
Player open_spiel::ultimate_tic_tac_toe::UltimateTTTState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 47 of file ultimate_tic_tac_toe.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::ultimate_tic_tac_toe::UltimateTTTState::DoApplyAction (Action move) override virtual
Reimplemented from open_spiel::State.
Definition at line 67 of file ultimate_tic_tac_toe.cc.
{
  if (current_state_ < 0) {
    // Choosing a board.
    SPIEL_CHECK_GE(move, 0);
    SPIEL_CHECK_LT(move, ttt::kNumCells);
    current_state_ = move;
  } else {
    // Apply action to local state, then apply that move.
    SPIEL_CHECK_FALSE(local_states_[current_state_]->IsTerminal());
    local_states_[current_state_]->ApplyAction(move);
    // Check if it's terminal and mark the outcome in the meta-game.
    if (local_states_[current_state_]->IsTerminal()) {
      Player local_outcome = local_state(current_state_)->outcome();
      if (local_outcome < 0) {
        meta_board_[current_state_] = ttt::CellState::kEmpty;
      } else {
        meta_board_[current_state_] = ttt::PlayerToState(local_outcome);
      }
    }
    // Set the next potential local state.
    current_state_ = move;
    // Check for a win or no more moves in the meta-game.
    if (ttt::BoardHasLine(meta_board_, current_player_)) {
      outcome_ = current_player_;
    } else if (AllLocalStatesTerminal()) {
      outcome_ = kInvalidPlayer;  // draw.
    } else {
      // Does the next board done? If not, set current_state_ to less than 0 to
      // indicate that the next board is a choice.
      if (local_states_[current_state_]->IsTerminal()) {
        current_state_ = -1;
      }
      current_player_ = NextPlayerRoundRobin(current_player_, ttt::kNumPlayers);
      // Need to set the current player in the local board.
      if (current_state_ >= 0) {
        local_state(current_state_)->SetCurrentPlayer(current_player_);
      }
    }
  }
}
References open_spiel::tic_tac_toe::BoardHasLine(), IsTerminal(), open_spiel::kInvalidPlayer, open_spiel::tic_tac_toe::kNumCells, open_spiel::tic_tac_toe::kNumPlayers, open_spiel::NextPlayerRoundRobin(), open_spiel::tic_tac_toe::TicTacToeState::outcome(), open_spiel::tic_tac_toe::PlayerToState(), open_spiel::tic_tac_toe::TicTacToeState::SetCurrentPlayer(), SPIEL_CHECK_FALSE, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
InformationStateString()
std::string open_spiel::ultimate_tic_tac_toe::UltimateTTTState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 185 of file ultimate_tic_tac_toe.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::ultimate_tic_tac_toe::UltimateTTTState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 174 of file ultimate_tic_tac_toe.cc.
{ return outcome_ != kUnfinished; }
References open_spiel::ultimate_tic_tac_toe::kUnfinished.
Referenced by CurrentPlayer(), DoApplyAction(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::ultimate_tic_tac_toe::UltimateTTTState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 108 of file ultimate_tic_tac_toe.cc.
{
  if (IsTerminal()) return {};
  if (current_state_ < 0) {
    std::vector<Action> actions;
    // Choosing the next state to play: any one that is not finished.
    for (int i = 0; i < local_states_.size(); ++i) {
      if (!local_states_[i]->IsTerminal()) {
        actions.push_back(i);
      }
    }
    return actions;
  } else {
    return local_states_[current_state_]->LegalActions();
  }
}
References i, and IsTerminal().
ObservationString()
std::string open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 191 of file ultimate_tic_tac_toe.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 197 of file ultimate_tic_tac_toe.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // Treat `values` as a 3-d tensor: 3 x 9 x 9:
  //   - empty versus x versus o, then
  //   - local state index, then
  //   - then 3x3 position within the local board.
  TensorView<3> view(values, {ttt::kCellStates, ttt::kNumCells, ttt::kNumCells},
                     /*reset*/true);
  for (int state = 0; state < ttt::kNumCells; ++state) {
    for (int cell = 0; cell < ttt::kNumCells; ++cell) {
      view[{static_cast<int>(local_state(state)->BoardAt(cell)),
            state, cell}] = 1.0;
    }
  }
}
References open_spiel::tic_tac_toe::TicTacToeState::BoardAt(), open_spiel::tic_tac_toe::kCellStates, open_spiel::tic_tac_toe::kNumCells, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, state, and values.
operator=()
UltimateTTTState & open_spiel::ultimate_tic_tac_toe::UltimateTTTState::operator= (const UltimateTTTState &) default
Returns()
std::vector< double > open_spiel::ultimate_tic_tac_toe::UltimateTTTState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 176 of file ultimate_tic_tac_toe.cc.
{
  std::vector<double> returns = {0.0, 0.0};
  if (outcome_ >= 0) {
    returns[outcome_] = 1.0;
    returns[1 - outcome_] = -1.0;
  }
  return returns;
}
ToString()
std::string open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 146 of file ultimate_tic_tac_toe.cc.
{
  std::string str;
  const int rows = ttt::kNumRows * 3;
  const int cols = ttt::kNumCols * 3;
  int meta_row = 0;
  int meta_col = 0;
  for (int r = 0; r < rows; ++r) {
    meta_row = r / 3;
    int local_row = r % 3;
    for (int c = 0; c < cols; ++c) {
      meta_col = c / 3;
      int local_col = c % 3;
      int state_idx = meta_row * 3 + meta_col;
      SPIEL_CHECK_GE(state_idx, 0);
      SPIEL_CHECK_LT(state_idx, local_states_.size());
      absl::StrAppend(&str, ttt::StateToString(local_state(state_idx)->BoardAt(
                                local_row, local_col)));
      if (local_col == 2) {
        absl::StrAppend(&str, c == 8 ? "\n" : " ");
      }
      if (local_row == 2 && r < 8 && c == 8) {
        absl::StrAppend(&str, "\n");
      }
    }
  }
  return str;
}
References open_spiel::tic_tac_toe::kNumCols, open_spiel::tic_tac_toe::kNumRows, r, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::tic_tac_toe::StateToString(), and absl::StrAppend().
Referenced by ObservationString().
UndoAction()
void open_spiel::ultimate_tic_tac_toe::UltimateTTTState::UndoAction (Player player, Action move) override virtual
Reimplemented from open_spiel::State.
Definition at line 216 of file ultimate_tic_tac_toe.cc.
{}
The documentation for this class was generated from the following files:
open_spiel/games/ultimate_tic_tac_toe/ultimate_tic_tac_toe.h
open_spiel/games/ultimate_tic_tac_toe/ultimate_tic_tac_toe.cc