open spiel: open_spiel::gamut::GamutGenerator Class Reference
open_spiel::gamut::GamutGenerator Class Reference
#include <gamut.h>
Public Member Functions
GamutGenerator (const std::string &java_path, const std::string &jar_path, int tmpfile_seed=0)
GamutGenerator (const std::string &jar_path, int tmpfile_seed=0)
std::shared_ptr< const Game > GenerateGame (const std::string &cmdline_args)
std::shared_ptr< const Game > GenerateGame (const std::vector< std::string > &cmdline_args)
std::shared_ptr< const matrix_game::MatrixGame > GenerateMatrixGame (const std::vector< std::string > &cmdline_args)
std::shared_ptr< const tensor_game::TensorGame > GenerateTensorGame (const std::vector< std::string > &cmdline_args)
Detailed Description
Definition at line 35 of file gamut.h.
Constructor & Destructor Documentation
GamutGenerator() [1/2]
open_spiel::gamut::GamutGenerator::GamutGenerator (const std::string & java_path, const std::string & jar_path, int tmpfile_seed = 0)
Definition at line 41 of file gamut.cc.
    : java_path_(java_path),
      jar_path_(jar_path),
      rng_(tmpfile_seed == 0 ? std::random_device{}() : tmpfile_seed),
      rand_string_(kAlphaChars) {}
GamutGenerator() [2/2]
open_spiel::gamut::GamutGenerator::GamutGenerator (const std::string & jar_path, int tmpfile_seed = 0)
Definition at line 38 of file gamut.cc.
    : GamutGenerator(kDefaultJavaPath, jar_path, tmpfile_seed) {}
Member Function Documentation
GenerateGame() [1/2]
std::shared_ptr< const Game > open_spiel::gamut::GamutGenerator::GenerateGame (const std::string & cmdline_args)
Definition at line 48 of file gamut.cc.
{
  return GenerateGame(absl::StrSplit(cmdline_args, ' '));
}
References GenerateGame(), and absl::StrSplit().
Referenced by GenerateGame(), GenerateMatrixGame(), GenerateTensorGame(), and open_spiel::init_pyspiel_gamut().
GenerateGame() [2/2]
std::shared_ptr< const Game > open_spiel::gamut::GamutGenerator::GenerateGame (const std::vector< std::string > & cmdline_args)
Definition at line 69 of file gamut.cc.
{
  // Check that there's no -f and no -output in the command-line args. The get
  // added by this generator.
  for (const auto& arg : cmdline_args) {
    if (arg == "-f") {
      SpielFatalError("Do not use -f in the command-line arguments.");
    } else if (arg == "-output") {
      SpielFatalError("Do not use -output in the command-line arguments.");
    }
  }
  std::vector<std::string> arguments = cmdline_args;
  arguments.push_back("-output");
  arguments.push_back("GambitOutput");
  // Lock here to prevent concurrently writing / removal.
  std::shared_ptr<const Game> game;
  {
    absl::MutexLock lock(&generation_mutex_);
    // Get a temporary file and add it to the arguments.
    std::string tmp_filename = TmpFile();
    arguments.push_back("-f");
    arguments.push_back(tmp_filename);
    std::string full_cmd = absl::StrCat(java_path_, " -jar ", jar_path_, " ",
                                        absl::StrJoin(arguments, " "));
    int ret_code = system(full_cmd.c_str());
    SPIEL_CHECK_EQ(ret_code, 0);
    SPIEL_CHECK_TRUE(file::Exists(tmp_filename));
    game = LoadGame("nfg_game", {{"filename", GameParameter(tmp_filename)}});
    file::Remove(tmp_filename);
  }
  return game;
}
References arg, open_spiel::file::Exists(), open_spiel::LoadGame(), open_spiel::file::Remove(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), absl::StrCat(), and absl::StrJoin().
GenerateMatrixGame()
std::shared_ptr< const matrix_game::MatrixGame > open_spiel::gamut::GamutGenerator::GenerateMatrixGame (const std::vector< std::string > & cmdline_args)
Definition at line 105 of file gamut.cc.
{
  return std::dynamic_pointer_cast<const matrix_game::MatrixGame>(
      GenerateGame(cmdline_args));
}
References GenerateGame().
Referenced by open_spiel::init_pyspiel_gamut().
GenerateTensorGame()
std::shared_ptr< const tensor_game::TensorGame > open_spiel::gamut::GamutGenerator::GenerateTensorGame (const std::vector< std::string > & cmdline_args)
Definition at line 112 of file gamut.cc.
{
  return std::dynamic_pointer_cast<const tensor_game::TensorGame>(
      GenerateGame(cmdline_args));
}
References GenerateGame().
Referenced by open_spiel::init_pyspiel_gamut().
The documentation for this class was generated from the following files:
open_spiel/games/gamut/gamut.h
open_spiel/games/gamut/gamut.cc