open spiel: open_spiel::algorithms::blotto_fp::FictitiousPlayProcess Class Reference
open_spiel::algorithms::blotto_fp::FictitiousPlayProcess Class Reference
#include <fictitious_play.h>
Public Member Functions
FictitiousPlayProcess (std::shared_ptr< const Game > game, int seed, bool randomize_initial_policies)
void GetMarginalJointPolicy (TabularPolicy *policy, const std::vector< std::vector< double > > *weight_table=nullptr) const
void GetMarginalJointPolicyFromEmpirical (TabularPolicy *policy) const
void FullFPIteration ()
void SFPIteration (double lambda)
void SBRIteration (int num_base_samples, int num_candidates)
void IBRIteration ()
void MaxEntIBRIteration ()
void BRPIIteration (BaseSamplerType base_sampling, CandidatesSamplerType candidates_sampling, int num_base_samples, int num_candidates, int brpi_N)
TabularPolicy GetMarginalJointPolicy ()
TabularPolicy GetLatestPolicy () const
absl::Duration TotalTime () const
double NashConv () const
double CCEDist () const
Detailed Description
Definition at line 55 of file fictitious_play.h.
Constructor & Destructor Documentation
FictitiousPlayProcess()
open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::FictitiousPlayProcess (std::shared_ptr< const Game > game, int seed, bool randomize_initial_policies)
Definition at line 60 of file fictitious_play.cc.
    : rng_(seed),
      dist_(0.0, 1.0),
      game_(game),
      num_players_(game->NumPlayers()),
      num_actions_(game->NumDistinctActions()),
      iterations_(0),
      total_time_(absl::ZeroDuration()) {
  // Get the info states strings.
  infostate_strings_.reserve(num_players_);
  std::unique_ptr<State> state = game->NewInitialState();
  for (Player p = 0; p < num_players_; ++p) {
    SPIEL_CHECK_EQ(state->CurrentPlayer(), p);
    std::vector<Action> legal_actions = state->LegalActions();
    std::string infostate_str = state->InformationStateString();
    infostate_strings_.push_back(infostate_str);
    state->ApplyAction(legal_actions[0]);
  }
  SPIEL_CHECK_TRUE(state->IsTerminal());
  // Get number of joint actions
  num_joint_actions_ = 1;
  for (Player p = 0; p < num_players_; ++p) {
    num_joint_actions_ *= num_actions_;
  }
  // Set initial cumulative policies to uniform.
  if (randomize_initial_policies) {
    InitPoliciesRandom();
  } else {
    InitPolicies();
  }
  GetMarginalJointPolicy(&joint_policy_);
  CheckJointUtilitiesCache();
  // Make the best response computers (for full FP)
  for (int p = 0; p < num_players_; ++p) {
    best_response_computers_.push_back(std::unique_ptr<TabularBestResponse>(
        new TabularBestResponse(*game_, p, &joint_policy_)));
  }
}
References GetMarginalJointPolicy(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Member Function Documentation
BRPIIteration()
void open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::BRPIIteration (BaseSamplerType base_sampling, CandidatesSamplerType candidates_sampling, int num_base_samples, int num_candidates, int brpi_N)
Definition at line 765 of file fictitious_play.cc.
{
  absl::Time start = absl::Now();
  // Clear policy counts
  std::fill(current_joint_policy_counts_.begin(),
            current_joint_policy_counts_.end(), 0.0);
  // N trials
  for (int n = 0; n < brpi_N; ++n) {
    std::vector<Action> joint_action(num_players_, kInvalidAction);
    // Sample the base profiles: number by player
    std::vector<std::vector<Action>> base_samples =
        SampleBaseProfiles(base_sampling, num_base_samples);
    // Each player computes a sampled BR.
    for (Player p = 0; p < num_players_; ++p) {
      Action best_candidate = GetBestCandidate(p, base_samples, num_candidates,
                                               candidates_sampling);
      joint_action[p] = best_candidate;
    }
    current_joint_policy_counts_[JointActionToIndex(joint_action)] += 1.0;
    // End of trial.
  }
  // Apply the 1/N to the emprical estimate of the joint policy and add them to
  // the past policies.
  std::vector<ActionsAndProbs> policies(num_players_);
  for (int ja_idx = 0; ja_idx < num_joint_actions_; ++ja_idx) {
    if (current_joint_policy_counts_[ja_idx] > 0) {
      double weight = current_joint_policy_counts_[ja_idx] / brpi_N;
      std::vector<Action> joint_action = IndexToJointAction(ja_idx);
      for (Player p = 0; p < num_players_; ++p) {
        AddWeight(&policies[p], joint_action[p], weight);
      }
    }
  }
  past_policies_.push_back(policies);
  std::fill(cumulative_joint_policy_.begin(), cumulative_joint_policy_.end(),
            0.0);
  for (int ja_idx = 0; ja_idx < num_joint_actions_; ++ja_idx) {
    std::vector<Action> joint_action = IndexToJointAction(ja_idx);
    double joint_prob = 1.0;
    for (Player p = 0; p < num_players_ && joint_prob > 0; ++p) {
      double prob = std::max(0.0, GetProb(policies[p], joint_action[p]));
      if (prob == 0) {
        joint_prob = 0;
      } else {
        joint_prob *= prob;
      }
    }
    if (joint_prob > 0) {
      cumulative_joint_policy_[ja_idx] = joint_prob;
    }
  }
  iterations_++;
  total_time_ += absl::Now() - start;
}
References open_spiel::GetProb(), open_spiel::kInvalidAction, n, and absl::Now().
Referenced by main().
CCEDist()
double open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::CCEDist () const
Definition at line 391 of file fictitious_play.cc.
{
  double dist = 0;
  std::vector<double> max_deviation(num_players_, -10);
  std::vector<double> exp_values(num_players_, 0);
  NormalFormCorrelationDevice corr_dev = GetEmpiricalJointPolicy();
  // First compute expected values for everyone
  for (int ja_idx = 0; ja_idx < num_joint_actions_; ++ja_idx) {
    if (corr_dev[ja_idx].probability > 0) {
      for (Player p = 0; p < num_players_; ++p) {
        exp_values[p] +=
            corr_dev[ja_idx].probability * cached_joint_utilities_[p][ja_idx];
      }
    }
  }
  // Now for each player, find the maximal deviation
  for (Player p = 0; p < num_players_; ++p) {
    for (Action a = 0; a < num_actions_; ++a) {
      double action_value = 0;
      for (int ja_idx = 0; ja_idx < num_joint_actions_; ++ja_idx) {
        if (corr_dev[ja_idx].probability > 0) {
          // Player p is changing to choose a instead.
          std::vector<Action> joint_action = IndexToJointAction(ja_idx);
          joint_action[p] = a;
          int other_index = JointActionToIndex(joint_action);
          action_value += corr_dev[ja_idx].probability *
                          cached_joint_utilities_[p][other_index];
        }
      }
      if (action_value > max_deviation[p]) {
        max_deviation[p] = action_value;
      }
    }
  }
  for (Player p = 0; p < num_players_; ++p) {
    double delta = std::max(max_deviation[p] - exp_values[p], 0.0);
    SPIEL_CHECK_GE(delta, 0);
    dist += delta;
  }
  return dist;
}
References a, and SPIEL_CHECK_GE.
Referenced by main().
FullFPIteration()
void open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::FullFPIteration ()
Definition at line 543 of file fictitious_play.cc.
{
  absl::Time start = absl::Now();
  std::vector<Action> joint_action(num_players_, kInvalidAction);
  for (Player p = 0; p < num_players_; ++p) {
    // Action br_action = BestResponseAgainstEmpiricalMarginalizedPolicies(p);
    Action br_action = BestResponseAgainstEmpiricalJointPolicy(p);
    SPIEL_CHECK_TRUE(br_action != kInvalidAction);
    cumulative_policies_[p][br_action] += 1.0;
    joint_action[p] = br_action;
  }
  cumulative_joint_policy_[JointActionToIndex(joint_action)] += 1.0;
  iterations_++;
  total_time_ += absl::Now() - start;
}
References open_spiel::kInvalidAction, absl::Now(), and SPIEL_CHECK_TRUE.
Referenced by main().
GetLatestPolicy()
TabularPolicy open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::GetLatestPolicy () const
Definition at line 155 of file fictitious_play.cc.
{
  TabularPolicy policy;
  for (Player p = 0; p < num_players_; ++p) {
    double prob_sum = 0.0;
    for (Action a = 0; a < num_actions_; ++a) {
      double prob = std::max(GetProb(past_policies_.back()[p], a), 0.0);
      policy.SetProb(infostate_strings_[p], a, prob);
      prob_sum += prob;
    }
    SPIEL_CHECK_TRUE(Near(prob_sum, 1.0));
  }
  return policy;
}
References a, open_spiel::GetProb(), open_spiel::Near(), and SPIEL_CHECK_TRUE.
GetMarginalJointPolicy() [1/2]
TabularPolicy open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::GetMarginalJointPolicy () inline
Definition at line 81 of file fictitious_play.h.
{
    GetMarginalJointPolicy(&joint_policy_);
    return joint_policy_;
  }
References GetMarginalJointPolicy().
Referenced by FictitiousPlayProcess(), GetMarginalJointPolicy(), GetMarginalJointPolicyFromEmpirical(), IBRIteration(), and MaxEntIBRIteration().
GetMarginalJointPolicy() [2/2]
void open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::GetMarginalJointPolicy (TabularPolicy * policy, const std::vector< std::vector< double > > * weight_table = nullptr) const
Definition at line 105 of file fictitious_play.cc.
{
  if (weight_table == nullptr) {
    weight_table = &cumulative_policies_;
  }
  for (Player p = 0; p < num_players_; ++p) {
    double prob_sum = 0.0;
    double total_weight = std::accumulate((*weight_table)[p].begin(),
                                          (*weight_table)[p].end(), 0.0);
    for (Action a = 0; a < num_actions_; ++a) {
      double prob = (*weight_table)[p][a] / total_weight;
      SPIEL_CHECK_PROB(prob);
      policy->SetProb(infostate_strings_[p], a, prob);
      prob_sum += prob;
    }
    SPIEL_CHECK_TRUE(Near(prob_sum, 1.0));
  }
}
References a, begin, end, open_spiel::Near(), SPIEL_CHECK_PROB, and SPIEL_CHECK_TRUE.
GetMarginalJointPolicyFromEmpirical()
void open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::GetMarginalJointPolicyFromEmpirical (TabularPolicy * policy) const
Definition at line 128 of file fictitious_play.cc.
{
  std::vector<std::vector<double>> marginal_weights;
  marginal_weights.reserve(num_players_);
  for (Player p = 0; p < num_players_; ++p) {
    marginal_weights.push_back(std::vector<double>(num_actions_, 0));
  }
  NormalFormCorrelationDevice mu = GetEmpiricalJointPolicy();
  for (int ja_idx = 0; ja_idx < num_joint_actions_; ++ja_idx) {
    for (Player p = 0; p < num_players_; ++p) {
      marginal_weights[p][mu[ja_idx].actions[p]] += mu[ja_idx].probability;
    }
  }
  for (Player p = 0; p < num_players_; ++p) {
    double total_weight = std::accumulate(marginal_weights[p].begin(),
                                          marginal_weights[p].end(), 0.0);
    for (Action a = 0; a < num_actions_; ++a) {
      marginal_weights[p][a] /= total_weight;
    }
  }
  GetMarginalJointPolicy(policy, &marginal_weights);
}
References a, begin, end, and GetMarginalJointPolicy().
Referenced by NashConv().
IBRIteration()
void open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::IBRIteration ()
Definition at line 470 of file fictitious_play.cc.
{
  absl::Time start = absl::Now();
  // Compute the joint policy.
  GetMarginalJointPolicy(&joint_policy_);
  // Get each player's best response, and add it to the cumulative policy.
  std::vector<TabularPolicy> br_policies(num_players_);
  std::vector<Action> joint_action(num_players_, kInvalidAction);
  for (Player p = 0; p < num_players_; ++p) {
    best_response_computers_[p]->SetPolicy(&joint_policy_);
    br_policies[p] = best_response_computers_[p]->GetBestResponsePolicy();
    Action br_action =
        GetAction(br_policies[p].GetStatePolicy(infostate_strings_[p]));
    SPIEL_CHECK_TRUE(br_action != kInvalidAction);
    std::fill(cumulative_policies_[p].begin(), cumulative_policies_[p].end(),
              0);
    cumulative_policies_[p][br_action] = 1.0;
    joint_action[p] = br_action;
  }
  std::fill(cumulative_joint_policy_.begin(), cumulative_joint_policy_.end(),
            0.0);
  cumulative_joint_policy_[JointActionToIndex(joint_action)] = 1.0;
  iterations_++;
  total_time_ += absl::Now() - start;
}
References begin, end, open_spiel::GetAction(), GetMarginalJointPolicy(), open_spiel::kInvalidAction, absl::Now(), and SPIEL_CHECK_TRUE.
Referenced by main().
MaxEntIBRIteration()
void open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::MaxEntIBRIteration ()
Definition at line 501 of file fictitious_play.cc.
{
  absl::Time start = absl::Now();
  // Compute the joint policy.
  GetMarginalJointPolicy(&joint_policy_);
  // Get each player's best response, and add it to the cumulative policy.
  std::vector<TabularPolicy> br_policies(num_players_);
  std::vector<std::vector<double>> policies;
  policies.reserve(num_players_);
  for (Player p = 0; p < num_players_; ++p) {
    best_response_computers_[p]->SetPolicy(&joint_policy_);
    br_policies[p] = best_response_computers_[p]->GetBestResponsePolicy();
    std::vector<Action> br_actions =
        best_response_computers_[p]->BestResponseActions(infostate_strings_[p],
                                                         1e-10);
    SPIEL_CHECK_GT(br_actions.size(), 0);
    std::fill(cumulative_policies_[p].begin(), cumulative_policies_[p].end(),
              0);
    std::vector<double> br(num_actions_, 0);
    for (Action action : br_actions) {
      double prob = 1.0 / br_actions.size();
      cumulative_policies_[p][action] = prob;
      br[action] = prob;
    }
    policies.push_back(br);
  }
  // Update empirical cumulative dist with these mixed policies
  std::fill(cumulative_joint_policy_.begin(), cumulative_joint_policy_.end(),
            0.0);
  UpdateCumulativeJointPolicy(policies);
  iterations_++;
  total_time_ += absl::Now() - start;
}
References action, begin, end, GetMarginalJointPolicy(), absl::Now(), and SPIEL_CHECK_GT.
Referenced by main().
NashConv()
double open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::NashConv () const
Definition at line 437 of file fictitious_play.cc.
{
  TabularPolicy marginalized_policy;
  GetMarginalJointPolicyFromEmpirical(&marginalized_policy);
  return open_spiel::algorithms::NashConv(*game_, marginalized_policy);
  // TabularPolicy marginalized_policy;
  // GetMarginalJointPolicy(&marginalized_policy);
  // return open_spiel::algorithms::NashConv(*game_, marginalized_policy);
}
References GetMarginalJointPolicyFromEmpirical(), and open_spiel::algorithms::NashConv().
Referenced by main().
SBRIteration()
void open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::SBRIteration (int num_base_samples, int num_candidates)
Definition at line 592 of file fictitious_play.cc.
{
  absl::Time start = absl::Now();
  std::vector<Action> joint_action(num_players_, kInvalidAction);
  // Sample the base profiles: number by player
  std::vector<std::vector<Action>> base_samples;
  base_samples.reserve(num_base_samples);
  for (int i = 0; i < num_base_samples; ++i) {
    std::vector<Action> base_profile;
    base_profile.reserve(num_players_);
    int past_idx = static_cast<int>(dist_(rng_) * past_policies_.size());
    for (Player p = 0; p < num_players_; ++p) {
      base_profile.push_back(
          SampleAction(past_policies_[past_idx][p], dist_(rng_)).first);
    }
    base_samples.push_back(base_profile);
  }
  // Each player computes a sampled BR.
  for (Player p = 0; p < num_players_; ++p) {
    double max_return = -std::numeric_limits<double>::infinity();
    Action best_candidate = kInvalidAction;
    for (int i = 0; i < num_candidates; ++i) {
      Action sampled_candidate =
          absl::Uniform(rng_, 0u, static_cast<unsigned int>(num_actions_));
      // Compute the action's expectation.
      double return_sum = 0.0;
      for (const std::vector<Action>& base_joint_action : base_samples) {
        std::vector<Action> joint_action = base_joint_action;
        joint_action[p] = sampled_candidate;
        std::unique_ptr<State> state = game_->NewInitialState();
        // Turn-based simultaneous game, so must apply them in order.
        for (Player pp = 0; pp < num_players_; ++pp) {
          state->ApplyAction(joint_action[pp]);
        }
        return_sum += state->PlayerReturn(p);
      }
      if (return_sum / num_base_samples > max_return) {
        max_return = return_sum / num_base_samples;
        best_candidate = sampled_candidate;
      }
    }
    SPIEL_CHECK_TRUE(best_candidate != kInvalidAction);
    cumulative_policies_[p][best_candidate] += 1.0;
    joint_action[p] = best_candidate;
  }
  // Add to past policies
  std::vector<ActionsAndProbs> new_policy;
  new_policy.reserve(num_players_);
  for (Player p = 0; p < num_players_; ++p) {
    new_policy.push_back({{joint_action[p], 1.0}});
  }
  past_policies_.push_back(new_policy);
  cumulative_joint_policy_[JointActionToIndex(joint_action)] += 1.0;
  iterations_++;
  total_time_ += absl::Now() - start;
}
References i, open_spiel::kInvalidAction, absl::Now(), open_spiel::SampleAction(), SPIEL_CHECK_TRUE, state, and absl::Uniform().
Referenced by main().
SFPIteration()
void open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::SFPIteration (double lambda)
Definition at line 562 of file fictitious_play.cc.
{
  absl::Time start = absl::Now();
  std::vector<std::vector<double>> softmax_brs;
  softmax_brs.reserve(num_players_);
  for (Player p = 0; p < num_players_; ++p) {
    std::vector<double> values(num_actions_, 0);
    // BestResponseAgainstEmpiricalMarginalizedPolicies(p, &values);
    BestResponseAgainstEmpiricalJointPolicy(p, &values);
    std::vector<double> softmax_br = Softmax(values, lambda);
    softmax_brs.push_back(softmax_br);
  }
  for (Player p = 0; p < num_players_; ++p) {
    for (int i = 0; i < softmax_brs[p].size(); ++i) {
      cumulative_policies_[p][i] += softmax_brs[p][i];
    }
  }
  // Update empirical cumulative dist with these mixed policies
  UpdateCumulativeJointPolicy(softmax_brs);
  iterations_++;
  total_time_ += absl::Now() - start;
}
References i, absl::Now(), and values.
Referenced by main().
TotalTime()
absl::Duration open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::TotalTime () const inline
Definition at line 88 of file fictitious_play.h.
{ return total_time_; }
Referenced by main().
The documentation for this class was generated from the following files:
open_spiel/examples/sbr_blotto/fictitious_play.h
open_spiel/examples/sbr_blotto/fictitious_play.cc