open spiel: gamut_test.GamutGeneratorTest Class Reference
gamut_test.GamutGeneratorTest Class Reference
Public Member Functions
test_generate_game (self, game_str)
test_gamut_api (self)
Protected Member Functions
_gamut_generator (self)
Detailed Description
Definition at line 24 of file gamut_test.py.
Member Function Documentation
_gamut_generator()
gamut_test.GamutGeneratorTest._gamut_generator (self) protected
Definition at line 26 of file gamut_test.py.
  def _gamut_generator(self):
    return pyspiel.GamutGenerator(
        "gamut.jar"
    )
Referenced by gamut_test.GamutGeneratorTest.test_gamut_api(), and gamut_test.GamutGeneratorTest.test_generate_game().
test_gamut_api()
gamut_test.GamutGeneratorTest.test_gamut_api (self)
Definition at line 52 of file gamut_test.py.
  def test_gamut_api(self):
    generator = self._gamut_generator()
    # See the documentation at http://gamut.stanford.edu/ for the commands
    # needed to generate the various different games.
    # Using a string of arguments.
    game = generator.generate_game(
        "-g RandomGame -players 4 -normalize -min_payoff 0 "
        + "-max_payoff 150 -actions 2 4 5 7"
    )
    self.assertIsNotNone(game)
    # Using a list of arguments.
    game = generator.generate_game([
        "-g",
        "RandomGame",
        "-players",
        "4",
        "-normalize",
        "-min_payoff",
        "0",
        "-max_payoff",
        "150",
        "-actions",
        "2",
        "4",
        "5",
        "7",
    ])
    self.assertIsNotNone(game)
    # Using a list of arguments.
    matrix_game = generator.generate_matrix_game([
        "-g",
        "RandomGame",
        "-players",
        "2",
        "-normalize",
        "-min_payoff",
        "0",
        "-max_payoff",
        "150",
        "-actions",
        "10",
        "15",
    ])
    self.assertIsNotNone(matrix_game)
    print(matrix_game.new_initial_state())
    payoff_matrix = game_payoffs_array(matrix_game)
    print(payoff_matrix.shape)
    print(payoff_matrix)
    # Using a list of arguments.
    tensor_game = generator.generate_game([
        "-g",
        "RandomGame",
        "-players",
        "4",
        "-normalize",
        "-min_payoff",
        "0",
        "-max_payoff",
        "150",
        "-actions",
        "2",
        "4",
        "5",
        "7",
    ])
    self.assertIsNotNone(tensor_game)
    payoff_tensor = game_payoffs_array(tensor_game)
    print(payoff_tensor.shape)
References gamut_test.GamutGeneratorTest._gamut_generator().
test_generate_game()
gamut_test.GamutGeneratorTest.test_generate_game (self, game_str)
Definition at line 43 of file gamut_test.py.
  def test_generate_game(self, game_str):
    generator = self._gamut_generator()
    # Using a string of arguments.
    game = generator.generate_game(game_str)
    self.assertIsNotNone(game)
    payoff_tensor = game_payoffs_array(game)
    self.assertEqual(payoff_tensor.shape, (2, 4, 4))
References gamut_test.GamutGeneratorTest._gamut_generator().
The documentation for this class was generated from the following file:
open_spiel/games/gamut/gamut_test.py