open spiel: open_spiel::spades::SpadesState Class Reference
open_spiel::spades::SpadesState Class Reference
#include <spades.h>
Public Member Functions
SpadesState (std::shared_ptr< const Game > game, bool use_mercy_rule, int mercy_threshold, int win_threshold, int score_partnership_0, int score_partnership_1, int num_tricks)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void WriteObservationTensor (Player player, absl::Span< float > values) const
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string Serialize () const override
std::array< int, kNumPlayers > ContractIndexes () const
std::array< bool, kNumContracts > PossibleContracts () const
std::vector< double > PrivateObservationTensor (Player player) const
std::vector< double > PublicObservationTensor () const
int CurrentPhase () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 97 of file spades.h.
Constructor & Destructor Documentation
SpadesState()
open_spiel::spades::SpadesState::SpadesState (std::shared_ptr< const Game > game, bool use_mercy_rule, int mercy_threshold, int win_threshold, int score_partnership_0, int score_partnership_1, int num_tricks)
Definition at line 117 of file spades.cc.
    : State(game),
      use_mercy_rule_(use_mercy_rule),
      mercy_threshold_(mercy_threshold),
      win_threshold_(win_threshold),
      current_scores_{score_partnership_0, score_partnership_1},
      num_tricks_(num_tricks) {
  possible_contracts_.fill(true);
}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::spades::SpadesState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 130 of file spades.cc.
{
  return (action < kBiddingActionBase) ? CardString(action)
                                       : BidString(action - kBiddingActionBase);
}
References action, and open_spiel::spades::kBiddingActionBase.
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::spades::SpadesState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 463 of file spades.cc.
{
  std::vector<std::pair<Action, double>> outcomes;
  int num_cards_remaining = kNumCards - history_.size();
  outcomes.reserve(num_cards_remaining);
  const double p = 1.0 / static_cast<double>(num_cards_remaining);
  for (int card = 0; card < kNumCards; ++card) {
    if (!holder_[card].has_value()) outcomes.emplace_back(card, p);
  }
  return outcomes;
}
References open_spiel::State::history_, and open_spiel::spades::kNumCards.
Clone()
std::unique_ptr< State > open_spiel::spades::SpadesState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 111 of file spades.h.
{
    return std::unique_ptr<State>(new SpadesState(*this));
  }
References SpadesState().
ContractIndexes()
std::array< int, kNumPlayers > open_spiel::spades::SpadesState::ContractIndexes () const
Definition at line 597 of file spades.cc.
{
  SPIEL_CHECK_TRUE(phase_ == Phase::kPlay || phase_ == Phase::kGameOver);
  std::array<int, kNumPlayers> contract_indexes;
  for (int i = 0; i < kNumPlayers; ++i) {
    contract_indexes[i] = (i * kNumBids) + contracts_[i];
  }
  return contract_indexes;
}
References i, open_spiel::spades::kNumBids, open_spiel::spades::kNumPlayers, and SPIEL_CHECK_TRUE.
CurrentPhase()
int open_spiel::spades::SpadesState::CurrentPhase () const inline
Definition at line 134 of file spades.h.
{ return static_cast<int>(phase_); }
CurrentPlayer()
Player open_spiel::spades::SpadesState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 549 of file spades.cc.
{
  if (phase_ == Phase::kDeal) {
    return kChancePlayerId;
  } else if (phase_ == Phase::kGameOver) {
    return kTerminalPlayerId;
  } else {
    return current_player_;
  }
}
References open_spiel::kChancePlayerId, and open_spiel::kTerminalPlayerId.
Referenced by ObservationString().
DoApplyAction()
void open_spiel::spades::SpadesState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 474 of file spades.cc.
{
  switch (phase_) {
    case Phase::kDeal:
      return ApplyDealAction(action);
    case Phase::kAuction:
      return ApplyBiddingAction(action - kBiddingActionBase);
    case Phase::kPlay:
      return ApplyPlayAction(action);
    case Phase::kGameOver:
      SpielFatalError("Cannot act in terminal states");
  }
}
References action, open_spiel::spades::kBiddingActionBase, and open_spiel::SpielFatalError().
IsTerminal()
bool open_spiel::spades::SpadesState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 105 of file spades.h.
{ return phase_ == Phase::kGameOver; }
Referenced by ObservationString(), and ToString().
LegalActions()
std::vector< Action > open_spiel::spades::SpadesState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 390 of file spades.cc.
{
  switch (phase_) {
    case Phase::kDeal:
      return DealLegalActions();
    case Phase::kAuction:
      return BiddingLegalActions();
    case Phase::kPlay:
      return PlayLegalActions();
    default:
      return {};
  }
}
ObservationString()
std::string open_spiel::spades::SpadesState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 163 of file spades.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (IsTerminal()) return ToString();
  std::string rv = "";
  auto cards = FormatHand(player, /*mark_voids=*/true, holder_);
  for (int suit = kNumSuits - 1; suit >= 0; --suit)
    absl::StrAppend(&rv, cards[suit], "\n");
  if (history_.size() > kNumCards)
    absl::StrAppend(
        &rv, FormatAuction(/*trailing_query=*/phase_ == Phase::kAuction &&
                           player == CurrentPlayer()));
  if (num_cards_played_ > 0) absl::StrAppend(&rv, FormatPlay());
  return rv;
}
References CurrentPlayer(), open_spiel::spades::FormatHand(), open_spiel::State::history_, IsTerminal(), open_spiel::spades::kNumCards, open_spiel::spades::kNumSuits, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and ToString().
ObservationTensor()
void open_spiel::spades::SpadesState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 267 of file spades.cc.
{
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  WriteObservationTensor(player, values);
}
References open_spiel::State::game_, player, SPIEL_CHECK_EQ, values, and WriteObservationTensor().
PossibleContracts()
std::array< bool, kNumContracts > open_spiel::spades::SpadesState::PossibleContracts () const inline
Definition at line 123 of file spades.h.
{
    return possible_contracts_;
  }
PrivateObservationTensor()
std::vector< double > open_spiel::spades::SpadesState::PrivateObservationTensor (Player player) const
Definition at line 383 of file spades.cc.
{
  std::vector<double> rv(kNumCards);
  for (int i = 0; i < kNumCards; ++i)
    if (holder_[i] == player) rv[i] = 1;
  return rv;
}
References i, open_spiel::spades::kNumCards, and player.
PublicObservationTensor()
std::vector< double > open_spiel::spades::SpadesState::PublicObservationTensor () const
Definition at line 368 of file spades.cc.
{
  SPIEL_CHECK_TRUE(phase_ == Phase::kAuction);
  std::vector<double> rv(kPublicInfoTensorSize);
  auto ptr = rv.begin();
  // Bids made so far
  for (int i = 0; i < kNumPlayers; i++) {
    // If player has bid, mark it
    if (contracts_[i] >= 0) {
      ptr[contracts_[i]] = 1;
    }
    ptr += kNumBids;
  }
  return rv;
}
References i, open_spiel::spades::kNumBids, open_spiel::spades::kNumPlayers, open_spiel::spades::kPublicInfoTensorSize, ptr, and SPIEL_CHECK_TRUE.
Returns()
std::vector< double > open_spiel::spades::SpadesState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 106 of file spades.h.
{ return returns_; }
Serialize()
std::string open_spiel::spades::SpadesState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 587 of file spades.cc.
{
  std::string serialized = State::Serialize();
  return serialized;
}
References open_spiel::State::Serialize().
ToString()
std::string open_spiel::spades::SpadesState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 135 of file spades.cc.
{
  std::string rv = absl::StrCat(FormatDeal());
  if (history_.size() > kNumCards)
    absl::StrAppend(&rv, FormatAuction(/*trailing_query=*/false));
  if (num_cards_played_ > 0) absl::StrAppend(&rv, FormatPlay());
  if (IsTerminal()) absl::StrAppend(&rv, FormatResult());
  return rv;
}
References open_spiel::State::history_, IsTerminal(), open_spiel::spades::kNumCards, absl::StrAppend(), and absl::StrCat().
Referenced by ObservationString().
WriteObservationTensor()
void open_spiel::spades::SpadesState::WriteObservationTensor (Player player, absl::Span< float > values) const
Definition at line 273 of file spades.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::fill(values.begin(), values.end(), 0.0);
  if (phase_ == Phase::kDeal) return;
  auto ptr = values.begin();
  // Mark bidding or playing phase
  ptr[static_cast<int>(phase_) - 1] = 1;
  ptr += kPhaseInfoSize;
  if (num_cards_played_ > 0) {
    // Observation for play phase
    // Contracts
    for (int i = 0; i < kNumPlayers; i++) {
      ptr[contracts_[i]] = 1;
      ptr += kNumBids;
    }
    // Our remaining cards.
    for (int i = 0; i < kNumCards; ++i)
      if (holder_[i] == player) ptr[i] = 1;
    ptr += kNumCards;
    // Indexing into history for recent tricks.
    int current_trick = num_cards_played_ / kNumPlayers;
    int this_trick_cards_played = num_cards_played_ % kNumPlayers;
    int this_trick_start = history_.size() - this_trick_cards_played;
    // Current trick
    if (phase_ != Phase::kGameOver) {
      int leader = tricks_[current_trick].Leader();
      for (int i = 0; i < this_trick_cards_played; ++i) {
        int card = history_[this_trick_start + i].action;
        int relative_player = (i + leader + kNumPlayers - player) % kNumPlayers;
        ptr[relative_player * kNumCards + card] = 1;
      }
    }
    ptr += kNumPlayers * kNumCards;
    // Previous tricks
    for (int j = current_trick - 1;
         j >= std::max(0, current_trick - num_tricks_ + 1); --j) {
      int leader = tricks_[j].Leader();
      for (int i = 0; i < kNumPlayers; ++i) {
        int card =
            history_[this_trick_start - kNumPlayers * (current_trick - j) + i]
                .action;
        int relative_player = (i + leader + kNumPlayers - player) % kNumPlayers;
        ptr[relative_player * kNumCards + card] = 1;
      }
      ptr += kNumPlayers * kNumCards;
    }
    // Move pointer for future tricks to have a fixed size tensor
    if (num_tricks_ > current_trick + 1) {
      ptr += kNumPlayers * kNumCards * (num_tricks_ - current_trick - 1);
    }
    // Number of tricks taken by each side.
    for (int i = 0; i < kNumPlayers; i++) {
      ptr[num_player_tricks_[i]] = 1;
      ptr += kNumTricks;
    }
    int kPlayTensorSize = SpadesGame::GetPlayTensorSize(num_tricks_);
    SPIEL_CHECK_EQ(std::distance(values.begin(), ptr),
                   kPlayTensorSize + kPhaseInfoSize);
    SPIEL_CHECK_LE(std::distance(values.begin(), ptr), values.size());
  } else {
    // Observation for auction
    // Bids made so far
    for (int i = 0; i < kNumPlayers; i++) {
      // If player has bid, mark it
      if (contracts_[i] >= 0) {
        ptr[contracts_[i]] = 1;
      }
      ptr += kNumBids;
    }
    // Our cards.
    for (int i = 0; i < kNumCards; ++i)
      if (holder_[i] == player) ptr[i] = 1;
    ptr += kNumCards;
    SPIEL_CHECK_EQ(std::distance(values.begin(), ptr),
                   kAuctionTensorSize + kPhaseInfoSize);
    SPIEL_CHECK_LE(std::distance(values.begin(), ptr), values.size());
  }
}
References action, open_spiel::spades::SpadesGame::GetPlayTensorSize(), open_spiel::State::history_, i, open_spiel::spades::kAuctionTensorSize, open_spiel::spades::kNumBids, open_spiel::spades::kNumCards, open_spiel::spades::kNumPlayers, open_spiel::spades::kNumTricks, open_spiel::spades::kPhaseInfoSize, open_spiel::State::num_players_, player, ptr, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, and values.
Referenced by ObservationTensor().
The documentation for this class was generated from the following files:
open_spiel/games/spades/spades.h
open_spiel/games/spades/spades.cc