open spiel: open_spiel.python.algorithms.alpha_zero.model_test.ModelTest Class Reference
open_spiel.python.algorithms.alpha_zero.model_test.ModelTest Class Reference
Public Member Functions
test_model_learns_simple (self, model_type)
test_model_learns_optimal (self, model_type)
Detailed Description
Definition at line 55 of file model_test.py.
Member Function Documentation
test_model_learns_optimal()
open_spiel.python.algorithms.alpha_zero.model_test.ModelTest.test_model_learns_optimal (self, model_type)
Definition at line 97 of file model_test.py.
  def test_model_learns_optimal(self, model_type):
    game = pyspiel.load_game("tic_tac_toe")
    solve_game(game.new_initial_state())
    model = build_model(game, model_type)
    print("Num variables:", model.num_trainable_variables)
    model.print_trainable_variables()
    train_inputs = list(solved.values())
    print("states:", len(train_inputs))
    losses = []
    policy_loss_goal = 0.12
    value_loss_goal = 0.12
    for i in range(500):
      loss = model.update(train_inputs)
      print(i, loss)
      losses.append(loss)
      if loss.policy < policy_loss_goal and loss.value < value_loss_goal:
        break
    self.assertGreater(losses[0].policy, losses[-1].policy)
    self.assertGreater(losses[0].value, losses[-1].value)
    self.assertGreater(losses[0].total, losses[-1].total)
    self.assertLess(losses[-1].value, value_loss_goal)
    self.assertLess(losses[-1].policy, policy_loss_goal)
References open_spiel.python.algorithms.alpha_zero.model_test.build_model(), len, and open_spiel.python.algorithms.alpha_zero.model_test.solve_game().
test_model_learns_simple()
open_spiel.python.algorithms.alpha_zero.model_test.ModelTest.test_model_learns_simple (self, model_type)
Definition at line 58 of file model_test.py.
  def test_model_learns_simple(self, model_type):
    game = pyspiel.load_game("tic_tac_toe")
    model = build_model(game, model_type)
    print("Num variables:", model.num_trainable_variables)
    model.print_trainable_variables()
    train_inputs = []
    state = game.new_initial_state()
    while not state.is_terminal():
      obs = state.observation_tensor()
      act_mask = state.legal_actions_mask()
      action = state.legal_actions()[0]
      policy = np.zeros(len(act_mask), dtype=float)
      policy[action] = 1
      train_inputs.append(model_lib.TrainInput(obs, act_mask, policy, value=1))
      state.apply_action(action)
      value, policy = model.inference([obs], [act_mask])
      self.assertLen(policy, 1)
      self.assertLen(value, 1)
      self.assertLen(policy[0], game.num_distinct_actions())
      self.assertLen(value[0], 1)
    losses = []
    policy_loss_goal = 0.05
    value_loss_goal = 0.05
    for i in range(200):
      loss = model.update(train_inputs)
      print(i, loss)
      losses.append(loss)
      if loss.policy < policy_loss_goal and loss.value < value_loss_goal:
        break
    self.assertGreater(losses[0].total, losses[-1].total)
    self.assertGreater(losses[0].policy, losses[-1].policy)
    self.assertGreater(losses[0].value, losses[-1].value)
    self.assertLess(losses[-1].value, value_loss_goal)
    self.assertLess(losses[-1].policy, policy_loss_goal)
References open_spiel.python.algorithms.alpha_zero.model_test.build_model(), and len.
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/alpha_zero/model_test.py