open spiel: open_spiel.python.rl_agent_policy.RLAgentPolicy Class Reference
open_spiel.python.rl_agent_policy.RLAgentPolicy Class Reference
Public Member Functions
__init__ (self, game, rl_agent.AbstractAgent agent, int player_id, bool use_observation)
action_probabilities (self, state, player_id=None)
Public Member Functions inherited from open_spiel.python.policy.Policy
__call__ (self, state, player_id=None)
to_tabular (self, states=None)
Protected Attributes
_player_id
Protected Attributes inherited from open_spiel.python.rl_agent_policy.JointRLAgentPolicy
_agents
_obs
_use_observation
Additional Inherited Members
Public Attributes inherited from open_spiel.python.policy.Policy
game
player_ids
Detailed Description
A policy for a specific agent trained in an RL environment.
Definition at line 82 of file rl_agent_policy.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.rl_agent_policy.RLAgentPolicy.__init__ (self, game, rl_agent.AbstractAgent agent, int player_id, bool use_observation)
Initializes the RL agent policy.
Args:
  game: The game.
  agent: RL agent.
  player_id: ID of the player.
  use_observation: See JointRLAgentPolicy above.
Reimplemented from open_spiel.python.rl_agent_policy.JointRLAgentPolicy.
Definition at line 85 of file rl_agent_policy.py.
               use_observation: bool):
    """Initializes the RL agent policy.
    Args:
      game: The game.
      agent: RL agent.
      player_id: ID of the player.
      use_observation: See JointRLAgentPolicy above.
    """
    self._player_id = player_id
    super().__init__(game, {player_id: agent}, use_observation)
Member Function Documentation
action_probabilities()
open_spiel.python.rl_agent_policy.RLAgentPolicy.action_probabilities (self, state, player_id = None)
Returns a dictionary {action: prob} for all legal actions.
IMPORTANT: We assume the following properties hold:
- All probabilities are >=0 and sum to 1
- TLDR: Policy implementations should list the (action, prob) for all legal
  actions, but algorithms should not rely on this (yet).
  Details: Before May 2020, only legal actions were present in the mapping,
  but it did not have to be exhaustive: missing actions were considered to
  be associated to a zero probability.
  For example, a deterministic state-poliy was previously {action: 1.0}.
  Given this change of convention is new and hard to enforce, algorithms
  should not rely on the fact that all legal actions should be present.
Args:
  state: A `pyspiel.State` object.
  player_id: Optional, the player id for whom we want an action. Optional
    unless this is a simultaneous state at which multiple players can act.
Returns:
  A `dict` of `{action: probability}` for the specified player in the
  supplied state.
Reimplemented from open_spiel.python.rl_agent_policy.JointRLAgentPolicy.
Definition at line 98 of file rl_agent_policy.py.
  def action_probabilities(self, state, player_id=None):
    return super().action_probabilities(
        state, self._player_id if player_id is None else player_id)
References open_spiel.python.rl_agent_policy.RLAgentPolicy._player_id, and open_spiel.python.rl_agent_policy.RLAgentPolicy.action_probabilities().
Referenced by open_spiel.python.policy.Policy.__call__(), open_spiel.python.rl_agent_policy.RLAgentPolicy.action_probabilities(), and open_spiel.python.policy.Policy.to_tabular().
Member Data Documentation
_player_id
open_spiel.python.rl_agent_policy.RLAgentPolicy._player_id protected
Definition at line 95 of file rl_agent_policy.py.
Referenced by open_spiel.python.rl_agent_policy.RLAgentPolicy.action_probabilities().
The documentation for this class was generated from the following file:
open_spiel/python/rl_agent_policy.py