open spiel: open_spiel::algorithms::OutcomeSamplingMCCFRSolver Class Reference
open_spiel::algorithms::OutcomeSamplingMCCFRSolver Class Reference
#include <outcome_sampling_mccfr.h>
Public Member Functions
OutcomeSamplingMCCFRSolver (const Game &game, double epsilon=kDefaultEpsilon, int seed=-1)
OutcomeSamplingMCCFRSolver (const Game &game, std::shared_ptr< Policy > default_policy, double epsilon=kDefaultEpsilon, int seed=-1)
OutcomeSamplingMCCFRSolver (std::shared_ptr< const Game > game, std::shared_ptr< Policy > default_policy, double epsilon, std::mt19937 rng)
void RunIteration ()
void RunIteration (std::mt19937 *rng)
CFRInfoStateValuesTable & InfoStateValuesTable ()
std::shared_ptr< Policy > AveragePolicy () const
TabularPolicy TabularAveragePolicy () const
std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const
Static Public Attributes
static constexpr double kInitialTableValues = 0.000001
static constexpr double kDefaultEpsilon = 0.6
Detailed Description
Definition at line 40 of file outcome_sampling_mccfr.h.
Constructor & Destructor Documentation
OutcomeSamplingMCCFRSolver() [1/3]
open_spiel::algorithms::OutcomeSamplingMCCFRSolver::OutcomeSamplingMCCFRSolver (const Game & game, double epsilon = kDefaultEpsilon, int seed = -1)
Definition at line 39 of file outcome_sampling_mccfr.cc.
    : OutcomeSamplingMCCFRSolver(game, std::make_shared<UniformPolicy>(),
                                 epsilon, seed) {}
OutcomeSamplingMCCFRSolver() [2/3]
open_spiel::algorithms::OutcomeSamplingMCCFRSolver::OutcomeSamplingMCCFRSolver (const Game & game, std::shared_ptr< Policy > default_policy, double epsilon = kDefaultEpsilon, int seed = -1)
Definition at line 44 of file outcome_sampling_mccfr.cc.
    : OutcomeSamplingMCCFRSolver(
          game.shared_from_this(), default_policy, epsilon,
          std::mt19937(seed >= 0 ? seed : std::mt19937::default_seed)) {}
OutcomeSamplingMCCFRSolver() [3/3]
open_spiel::algorithms::OutcomeSamplingMCCFRSolver::OutcomeSamplingMCCFRSolver (std::shared_ptr< const Game > game, std::shared_ptr< Policy > default_policy, double epsilon, std::mt19937 rng)
Definition at line 51 of file outcome_sampling_mccfr.cc.
    : game_(game),
      epsilon_(epsilon),
      rng_(rng),
      dist_(0.0, 1.0),
      default_policy_(default_policy) {
  if (game_->GetType().dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError(
        "MCCFR requires sequential games. If you're trying to run it "
        "on a simultaneous (or normal-form) game, please first transform it "
        "using turn_based_simultaneous_game.");
  }
}
References open_spiel::GameType::kSequential, and open_spiel::SpielFatalError().
Member Function Documentation
AveragePolicy()
std::shared_ptr< Policy > open_spiel::algorithms::OutcomeSamplingMCCFRSolver::AveragePolicy () const inline
Definition at line 73 of file outcome_sampling_mccfr.h.
{
    return std::make_shared<CFRAveragePolicy>(info_states_, default_policy_);
  }
Referenced by open_spiel::init_pyspiel_policy().
InfoStateValuesTable()
CFRInfoStateValuesTable & open_spiel::algorithms::OutcomeSamplingMCCFRSolver::InfoStateValuesTable () inline
Definition at line 68 of file outcome_sampling_mccfr.h.
{ return info_states_; }
RunIteration() [1/2]
void open_spiel::algorithms::OutcomeSamplingMCCFRSolver::RunIteration () inline
Definition at line 63 of file outcome_sampling_mccfr.h.
{ RunIteration(&rng_); }
References RunIteration().
Referenced by main(), and RunIteration().
RunIteration() [2/2]
void open_spiel::algorithms::OutcomeSamplingMCCFRSolver::RunIteration (std::mt19937 * rng)
Definition at line 67 of file outcome_sampling_mccfr.cc.
{
  // for (Player update_player = Player{0}; update_player < game_->NumPlayers();
  // ++update_player) {
  for (Player p = Player{0}; p < game_->NumPlayers(); ++p) {
    std::unique_ptr<State> state = game_->NewInitialState();
    SampleEpisode(state.get(), p, rng, 1.0, 1.0, 1.0);
  }
}
References state.
Serialize()
std::string open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize (int double_precision = -1, std::string delimiter = "<~>") const
Definition at line 76 of file outcome_sampling_mccfr.cc.
{
  SPIEL_CHECK_GE(double_precision, -1);
  std::string str = "";
  // Meta section
  absl::StrAppend(&str,
                  "# Automatically generated by OpenSpiel "
                  "OutcomeSamplingMCCFRSolver::Serialize\n");
  absl::StrAppend(&str, kSerializeMetaSectionHeader, "\n");
  absl::StrAppend(&str, "Version: ", kSerializationVersion, "\n");
  absl::StrAppend(&str, "\n");
  // Game section
  absl::StrAppend(&str, kSerializeGameSectionHeader, "\n");
  absl::StrAppend(&str, game_->Serialize(), "\n");
  // Internal solver state section
  absl::StrAppend(&str, kSerializeSolverTypeSectionHeader, "\n");
  absl::StrAppend(&str, "OutcomeSamplingMCCFRSolver", "\n");
  absl::StrAppend(&str, kSerializeSolverSpecificStateSectionHeader, "\n");
  // RNG section
  absl::StrAppend(&str, kSerializeSolverRNGSectionHeader, "\n");
  std::ostringstream rng_stream;
  rng_stream << rng_;
  absl::StrAppend(&str, rng_stream.str(), "\n");
  // Epsilon section
  absl::StrAppend(&str, kSerializeSolverEpsilonSectionHeader, "\n");
  absl::StrAppend(&str, epsilon_, "\n");
  // Default policy section
  absl::StrAppend(&str, kSerializeSolverDefaultPolicySectionHeader, "\n");
  absl::StrAppend(&str, default_policy_->Serialize(double_precision, delimiter),
                  "\n");
  // Info state values table section
  absl::StrAppend(&str, kSerializeSolverValuesTableSectionHeader, "\n");
  SerializeCFRInfoStateValuesTable(info_states_, &str, double_precision,
                                   delimiter);
  return str;
}
References open_spiel::algorithms::kSerializationVersion, open_spiel::algorithms::kSerializeGameSectionHeader, open_spiel::algorithms::kSerializeMetaSectionHeader, open_spiel::algorithms::kSerializeSolverDefaultPolicySectionHeader, open_spiel::algorithms::kSerializeSolverEpsilonSectionHeader, open_spiel::algorithms::kSerializeSolverRNGSectionHeader, open_spiel::algorithms::kSerializeSolverSpecificStateSectionHeader, open_spiel::algorithms::kSerializeSolverTypeSectionHeader, open_spiel::algorithms::kSerializeSolverValuesTableSectionHeader, open_spiel::algorithms::SerializeCFRInfoStateValuesTable(), SPIEL_CHECK_GE, and absl::StrAppend().
TabularAveragePolicy()
TabularPolicy open_spiel::algorithms::OutcomeSamplingMCCFRSolver::TabularAveragePolicy () const inline
Definition at line 77 of file outcome_sampling_mccfr.h.
{
    CFRAveragePolicy policy(info_states_, nullptr);
    return TabularPolicy(*game_, policy);
  }
Referenced by main().
Member Data Documentation
kDefaultEpsilon
double open_spiel::algorithms::OutcomeSamplingMCCFRSolver::kDefaultEpsilon = 0.6 inline static constexpr
Definition at line 43 of file outcome_sampling_mccfr.h.
Referenced by open_spiel::init_pyspiel_policy().
kInitialTableValues
double open_spiel::algorithms::OutcomeSamplingMCCFRSolver::kInitialTableValues = 0.000001 inline static constexpr
Definition at line 42 of file outcome_sampling_mccfr.h.
The documentation for this class was generated from the following files:
open_spiel/algorithms/outcome_sampling_mccfr.h
open_spiel/algorithms/outcome_sampling_mccfr.cc