open spiel: open_spiel::chess::ChessBoard Class Reference
open_spiel::chess::ChessBoard Class Reference
#include <chess_board.h>
Public Types
using MoveYieldFn = std::function<bool(const Move&)>
Public Member Functions
ChessBoard (int board_size=kDefaultBoardSize, bool king_in_check_allowed=false, bool allow_pass_move=false)
const Piece & at (Square sq) const
void set_square (Square sq, Piece p)
const std::array< Piece, k2dMaxBoardSize > & pieces () const
Color ToPlay () const
void SetToPlay (Color c)
Square EpSquare () const
void SetEpSquare (Square sq)
int32_t IrreversibleMoveCounter () const
int32_t Movenumber () const
absl::optional< Square > MaybeCastlingRookSquare (Color side, CastlingDirection direction) const
bool CastlingRight (Color color, CastlingDirection dir) const
void SetCastlingRight (Color side, CastlingDirection direction, absl::optional< Square > maybe_rook_square)
Square FindRookForCastling (Color color, CastlingDirection dir) const
Square find (const Piece &piece) const
void GenerateLegalMoves (const MoveYieldFn &yield) const
void GenerateLegalMoves (const MoveYieldFn &yield, Color color) const
void GeneratePseudoLegalMoves (const MoveYieldFn &yield, Color color, PseudoLegalMoveSettings settings=PseudoLegalMoveSettings::kAcknowledgeEnemyPieces) const
void GenerateLegalPawnCaptures (const MoveYieldFn &yield, Color color) const
void GeneratePseudoLegalPawnCaptures (const MoveYieldFn &yield, Color color, PseudoLegalMoveSettings settings=PseudoLegalMoveSettings::kAcknowledgeEnemyPieces) const
bool HasLegalMoves () const
bool IsMoveLegal (const Move &tested_move) const
bool HasSufficientMaterial () const
absl::optional< Move > ParseMove (const std::string &move) const
absl::optional< Move > ParseSANMove (const std::string &move) const
absl::optional< Move > ParseLANMove (const std::string &move) const
void ApplyMove (const Move &move)
bool TestApplyMove (const Move &move)
bool InBoardArea (const Square &sq) const
bool IsEmpty (const Square &sq) const
bool IsEnemy (const Square &sq, Color our_color) const
bool IsFriendly (const Square &sq, Color our_color) const
bool IsEmptyOrEnemy (const Square &sq, Color our_color) const
bool IsPawnStartingRank (const Square &sq, Color our_color) const
bool IsPawnPromotionRank (const Square &sq) const
bool UnderAttack (const Square &sq, Color our_color) const
bool InCheck () const
int BoardSize () const
bool KingInCheckAllowed () const
bool AllowPassMove () const
uint64_t HashValue () const
std::string DebugString () const
std::string ToUnicodeString () const
std::string ToFEN () const
std::string ToDarkFEN (const ObservationTable &observability_table, Color color) const
bool IsBreachingMove (Move move) const
void BreachingMoveToCaptureMove (Move *move) const
Static Public Member Functions
static absl::optional< ChessBoard > BoardFromFEN (const std::string &fen, int board_size=8, bool king_in_check_allowed=false, bool allow_pass_move=false)
Detailed Description
Definition at line 255 of file chess_board.h.
Member Typedef Documentation
MoveYieldFn
using open_spiel::chess::ChessBoard::MoveYieldFn = std::function<bool(const Move&)>
Definition at line 304 of file chess_board.h.
Constructor & Destructor Documentation
ChessBoard()
open_spiel::chess::ChessBoard::ChessBoard (int board_size = kDefaultBoardSize, bool king_in_check_allowed = false, bool allow_pass_move = false)
Definition at line 345 of file chess_board.cc.
    : board_size_(board_size),
      king_in_check_allowed_(king_in_check_allowed),
      allow_pass_move_(allow_pass_move),
      to_play_(Color::kWhite),
      ep_square_(kInvalidSquare),
      irreversible_move_counter_(0),
      move_number_(1),
      zobrist_hash_(0) {
  board_.fill(kEmptyPiece);
}
Member Function Documentation
AllowPassMove()
bool open_spiel::chess::ChessBoard::AllowPassMove () const inline
Definition at line 426 of file chess_board.h.
{ return allow_pass_move_; }
Referenced by open_spiel::chess::ActionToMove().
ApplyMove()
void open_spiel::chess::ChessBoard::ApplyMove (const Move & move)
Definition at line 1030 of file chess_board.cc.
{
  // Skip applying a move if it's a pass.
  if (move == kPassMove) {
    if (to_play_ == Color::kBlack) ++move_number_;
    SetToPlay(OppColor(to_play_));
    SetEpSquare(chess::kInvalidSquare);
    return;
  }
  // Most moves are simple - we remove the moving piece from the original
  // square, and put it on the destination square, overwriting whatever was
  // there before, update the 50 move counter, and update castling rights.
  //
  // There are a few exceptions - castling, en passant, promotions, double pawn
  // pushes. They require special adjustments in addition to those things. We
  // do them after the basic apply move.
  Piece moving_piece = at(move.from);
  Piece destination_piece = at(move.to);
  // We have to do it in this order because in Chess960 the king can castle
  // in-place! That's the only possibility for move.from == move.to.
  set_square(move.from, kEmptyPiece);
  set_square(move.to, moving_piece);
  // Whether the move is irreversible for the purpose of the 50-moves rule. Note
  // that although castling (and losing castling rights) should be irreversible,
  // it is counted as reversible here.
  // Irreversible moves are pawn moves and captures. We don't have to make a
  // special case for en passant, since they are pawn moves anyways.
  bool irreversible = (moving_piece.type == PieceType::kPawn) ||
                      (destination_piece.type != PieceType::kEmpty);
  if (irreversible) {
    SetIrreversibleMoveCounter(0);
  } else {
    SetIrreversibleMoveCounter(IrreversibleMoveCounter() + 1);
  }
  // Castling rights can be lost in a few different ways -
  // 1. The king moves (loses both rights), including castling. We do this later
  //    since we still need the rook locations in case this is a castle.
  // 2. A rook moves (loses the right on that side).
  // 3. Captures an opponent rook (OPPONENT loses the right on that side).
  if (moving_piece.type == PieceType::kRook) {
    if (castling_rights_[ToInt(to_play_)].left_castle.has_value() &&
        *castling_rights_[ToInt(to_play_)].left_castle == move.from) {
      SetCastlingRight(to_play_, CastlingDirection::kLeft, absl::nullopt);
    } else if (castling_rights_[ToInt(to_play_)].right_castle.has_value() &&
               *castling_rights_[ToInt(to_play_)].right_castle == move.from) {
      SetCastlingRight(to_play_, CastlingDirection::kRight, absl::nullopt);
    }
  }
  if (destination_piece.type == PieceType::kRook) {
    if (castling_rights_[ToInt(OppColor(to_play_))].left_castle.has_value() &&
        *castling_rights_[ToInt(OppColor(to_play_))].left_castle == move.to) {
      SetCastlingRight(OppColor(to_play_), CastlingDirection::kLeft,
                       absl::nullopt);
    } else if (castling_rights_[ToInt(OppColor(to_play_))]
                   .right_castle.has_value() &&
               *castling_rights_[ToInt(OppColor(to_play_))].right_castle ==
                   move.to) {
      SetCastlingRight(OppColor(to_play_), CastlingDirection::kRight,
                       absl::nullopt);
    }
  }
  // Special cases that require adjustment -
  // 1. Castling
  if (move.is_castling) {
    SPIEL_CHECK_EQ(moving_piece.type, PieceType::kKing);
    // We can tell which side we are castling to using "to" square. This is true
    // even in chess960 (destination squares are same as in normal chess).
    // However, we have to be careful of the edge case where the king actually
    // doesn't move.
    int8_t y = to_play_ == Color::kWhite ? 0 : 7;
    if (move.to == Square{2, y}) {
      // left castle
      const auto &maybe_rook_sq = castling_rights_[ToInt(to_play_)].left_castle;
      SPIEL_CHECK_TRUE(maybe_rook_sq.has_value());
      set_square(*maybe_rook_sq, kEmptyPiece);
      set_square(Square{2, y}, Piece{to_play_, PieceType::kKing});
      set_square(Square{3, y}, Piece{to_play_, PieceType::kRook});
    } else if (move.to == Square{6, y}) {
      // right castle
      const auto &maybe_rook_sq =
          castling_rights_[ToInt(to_play_)].right_castle;
      SPIEL_CHECK_TRUE(maybe_rook_sq.has_value());
      set_square(*maybe_rook_sq, kEmptyPiece);
      set_square(Square{6, y}, Piece{to_play_, PieceType::kKing});
      set_square(Square{5, y}, Piece{to_play_, PieceType::kRook});
    } else {
      std::cerr << "Trying to castle but destination " << move.to.ToString()
                << " is not valid." << std::endl;
    }
  }
  if (moving_piece.type == PieceType::kKing) {
    SetCastlingRight(to_play_, CastlingDirection::kLeft, absl::nullopt);
    SetCastlingRight(to_play_, CastlingDirection::kRight, absl::nullopt);
  }
  // 2. En-passant
  if (moving_piece.type == PieceType::kPawn && move.from.x != move.to.x &&
      destination_piece.type == PieceType::kEmpty) {
    if (move.to != EpSquare()) {
      std::cerr << "We are trying to capture an empty square "
                << "with a pawn, but the square is not the en passant square:\n"
                << *this << "\n"
                << "Move: " << move.ToString() << std::endl;
      SpielFatalError("Trying to apply an invalid move");
    }
    Square captured_pawn_square = move.to;
    if (to_play_ == Color::kWhite) {
      --captured_pawn_square.y;
    } else {
      ++captured_pawn_square.y;
    }
    SPIEL_CHECK_EQ(at(captured_pawn_square),
                   (Piece{OppColor(to_play_), PieceType::kPawn}));
    set_square(captured_pawn_square, kEmptyPiece);
  }
  // 3. Promotions
  if (moving_piece.type == PieceType::kPawn && IsPawnPromotionRank(move.to)) {
    set_square(move.to, Piece{at(move.to).color, move.promotion_type});
  }
  // 4. Double push
  if (moving_piece.type == PieceType::kPawn &&
      abs(move.from.y - move.to.y) == 2) {
    SetEpSquare(Square{move.from.x,
                       static_cast<int8_t>((move.from.y + move.to.y) / 2)});
  } else {
    SetEpSquare(kInvalidSquare);
  }
  if (to_play_ == Color::kBlack) {
    ++move_number_;
  }
  SetToPlay(OppColor(to_play_));
}
References at(), EpSquare(), IrreversibleMoveCounter(), IsPawnPromotionRank(), open_spiel::chess::kBlack, open_spiel::chess::kEmpty, open_spiel::chess::kKing, open_spiel::chess::kLeft, open_spiel::chess::kPassMove, open_spiel::chess::kPawn, open_spiel::chess::kRight, open_spiel::chess::kRook, open_spiel::chess::kWhite, left_castle, open_spiel::chess::OppColor(), right_castle, set_square(), SetCastlingRight(), SetEpSquare(), SetToPlay(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), open_spiel::chess::ToInt(), open_spiel::chess::Piece::type, open_spiel::chess_common::Square::y, and y.
Referenced by open_spiel::chess::ChessState::DoApplyAction(), open_spiel::dark_chess::DarkChessState::DoApplyAction(), open_spiel::kriegspiel::KriegspielState::DoApplyAction(), open_spiel::rbc::RbcState::DoApplyAction(), open_spiel::kriegspiel::GeneratesUmpireMessage(), open_spiel::kriegspiel::GetUmpireMessage(), TestApplyMove(), open_spiel::chess::Move::ToSAN(), open_spiel::chess::ChessState::UndoAction(), open_spiel::dark_chess::DarkChessState::UndoAction(), open_spiel::kriegspiel::KriegspielState::UndoAction(), and open_spiel::rbc::RbcState::UndoAction().
at()
const Piece & open_spiel::chess::ChessBoard::at (Square sq) const inline
Definition at line 268 of file chess_board.h.
{ return board_[SquareToIndex_(sq)]; }
Referenced by open_spiel::chess::ActionToMove(), ApplyMove(), BreachingMoveToCaptureMove(), DebugString(), open_spiel::rbc::RbcState::DoApplyAction(), find(), GenerateLegalMoves(), GenerateLegalPawnCaptures(), GeneratePseudoLegalMoves(), GeneratePseudoLegalPawnCaptures(), open_spiel::kriegspiel::GeneratesUmpireMessage(), open_spiel::kriegspiel::GetUmpireMessage(), HasSufficientMaterial(), ParseSANMove(), set_square(), ToDarkFEN(), ToFEN(), open_spiel::chess::Move::ToSAN(), ToUnicodeString(), and UnderAttack().
BoardFromFEN()
absl::optional< ChessBoard > open_spiel::chess::ChessBoard::BoardFromFEN (const std::string & fen, int board_size = 8, bool king_in_check_allowed = false, bool allow_pass_move = false) static
Definition at line 358 of file chess_board.cc.
{
  /* An FEN string includes a board position, side to play, castling
   * rights, ep square, 50 moves clock, and full move number. In that order.
   *
   * Eg. start position is:
   * rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
   *
   * Board is described from rank 8 to rank 1, and files from a to h. Empty
   * squares are encoded as number of consecutive empty squares.
   *
   * Many FEN strings don't have the last two fields.
   */
  ChessBoard board(board_size, king_in_check_allowed, allow_pass_move);
  std::vector<std::string> fen_parts = absl::StrSplit(fen, ' ');
  if (fen_parts.size() != 6 && fen_parts.size() != 4) {
    std::cerr << "Invalid FEN: " << fen << std::endl;
    return absl::nullopt;
  }
  std::string &piece_configuration = fen_parts[0];
  std::string &side_to_move = fen_parts[1];
  std::string &castling_rights = fen_parts[2];
  std::string &ep_square = fen_parts[3];
  // These are defaults if the FEN string doesn't have these fields.
  std::string fifty_clock = "0";
  std::string move_number = "1";
  if (fen_parts.size() == 6) {
    fifty_clock = fen_parts[4];
    move_number = fen_parts[5];
  }
  std::vector<std::string> piece_config_by_rank =
      absl::StrSplit(piece_configuration, '/');
  for (int8_t current_y = board_size - 1; current_y >= 0; --current_y) {
    std::string &rank = piece_config_by_rank[board_size - current_y - 1];
    int8_t current_x = 0;
    for (char c : rank) {
      if (current_x >= board_size) {
        std::cerr << "Too many things on FEN rank: " << rank << std::endl;
        return absl::nullopt;
      }
      if (c >= '1' && c <= '8') {
        current_x += c - '0';
      } else {
        auto piece_type = PieceTypeFromChar(c);
        if (!piece_type) {
          std::cerr << "Invalid piece type in FEN: " << c << std::endl;
          return absl::nullopt;
        }
        Color color = isupper(c) ? Color::kWhite : Color::kBlack;
        board.set_square(Square{current_x, current_y},
                         Piece{color, *piece_type});
        ++current_x;
      }
    }
  }
  if (side_to_move == "b") {
    board.SetToPlay(Color::kBlack);
  } else if (side_to_move == "w") {
    board.SetToPlay(Color::kWhite);
  } else {
    std::cerr << "Invalid side to move in FEN: " << side_to_move << std::endl;
    return absl::nullopt;
  }
  // If we have a castling right, we look for a rook in that position. In
  // chess960 there must be a rook on either side of the king, but all 3 can
  // otherwise be in any square. If we find one rook on that side, that is used
  // as the castling square. If we find a rook on the end squares (as in
  // standard chess), we assume it's standard chess, and use that as the rook,
  // even if there are multiple rooks.
  // Note that this can create ambiguous chess960 positions, but we don't have
  // support for 960-specific FEN for yet.
  if (castling_rights.find('K') != std::string::npos) {  // NOLINT
    Square rook_sq =
        board.FindRookForCastling(Color::kWhite, CastlingDirection::kRight);
    board.SetCastlingRight(Color::kWhite, CastlingDirection::kRight, rook_sq);
  }
  if (castling_rights.find('Q') != std::string::npos) {  // NOLINT
    Square rook_sq =
        board.FindRookForCastling(Color::kWhite, CastlingDirection::kLeft);
    board.SetCastlingRight(Color::kWhite, CastlingDirection::kLeft, rook_sq);
  }
  if (castling_rights.find('k') != std::string::npos) {  // NOLINT
    Square rook_sq =
        board.FindRookForCastling(Color::kBlack, CastlingDirection::kRight);
    board.SetCastlingRight(Color::kBlack, CastlingDirection::kRight, rook_sq);
  }
  if (castling_rights.find('q') != std::string::npos) {  // NOLINT
    Square rook_sq =
        board.FindRookForCastling(Color::kBlack, CastlingDirection::kLeft);
    board.SetCastlingRight(Color::kBlack, CastlingDirection::kLeft, rook_sq);
  }
  if (ep_square != "-") {
    auto maybe_ep_square = SquareFromString(ep_square);
    if (!maybe_ep_square) {
      std::cerr << "Invalid en passant square in FEN: " << ep_square
                << std::endl;
      return absl::nullopt;
    }
    board.SetEpSquare(*maybe_ep_square);
  }
  board.SetIrreversibleMoveCounter(std::stoi(fifty_clock));
  board.SetMovenumber(std::stoi(move_number));
  return board;
}
References FindRookForCastling(), open_spiel::chess::kBlack, open_spiel::chess::kLeft, open_spiel::chess::kRight, open_spiel::chess::kWhite, open_spiel::chess::PieceTypeFromChar(), rank, set_square(), SetCastlingRight(), SetEpSquare(), SetToPlay(), open_spiel::chess::SquareFromString(), and absl::StrSplit().
Referenced by open_spiel::chess::ChessState::ChessState(), and open_spiel::chess::MakeDefaultBoard().
BoardSize()
int open_spiel::chess::ChessBoard::BoardSize () const inline
Definition at line 422 of file chess_board.h.
{ return board_size_; }
Referenced by open_spiel::chess::ActionToMove(), open_spiel::chess::ChessState::BoardSize(), open_spiel::dark_chess::DarkChessState::BoardSize(), open_spiel::rbc::RbcState::BoardSize(), and open_spiel::kriegspiel::GetCheckType().
BreachingMoveToCaptureMove()
void open_spiel::chess::ChessBoard::BreachingMoveToCaptureMove (Move * move) const
Definition at line 720 of file chess_board.cc.
{
  SPIEL_CHECK_TRUE(move);
  SPIEL_DCHECK_TRUE(IsBreachingMove(*move));
  int dx = move->to.x - move->from.x;
  int dy = move->to.y - move->from.y;
  SPIEL_DCHECK_TRUE(dx == 0 || dy == 0 || std::abs(dx) == std::abs(dy));
  // Cap values to [-1, 1] range to make a proper step size.
  dx = std::max(-1, dx);
  dx = std::min(1, dx);
  dy = std::max(-1, dy);
  dy = std::min(1, dy);
  const Offset step{static_cast<int8_t>(dx),
                    static_cast<int8_t>(dy)};
  Square sq;
  for (sq = move->from + step; sq != move->to; sq += step) {
    if (at(sq).type != PieceType::kEmpty) break;
  }
  move->to = sq;
}
References at(), IsBreachingMove(), open_spiel::chess::kEmpty, SPIEL_CHECK_TRUE, SPIEL_DCHECK_TRUE, and open_spiel::chess::Piece::type.
Referenced by open_spiel::rbc::RbcState::DoApplyAction().
CastlingRight()
bool open_spiel::chess::ChessBoard::CastlingRight (Color color, CastlingDirection dir) const inline
Definition at line 286 of file chess_board.h.
{
    return MaybeCastlingRookSquare(color, dir).has_value();
  }
References dir, and MaybeCastlingRookSquare().
Referenced by DebugString(), ToDarkFEN(), and ToFEN().
DebugString()
std::string open_spiel::chess::ChessBoard::DebugString () const
Definition at line 1256 of file chess_board.cc.
{
  std::string s;
  s = absl::StrCat("FEN: ", ToFEN(), "\n");
  absl::StrAppend(&s, "\n  ---------------------------------\n");
  for (int8_t y = board_size_ - 1; y >= 0; --y) {
    // Rank label.
    absl::StrAppend(&s, RankToString(y), " ");
    // Pieces on the rank.
    for (int8_t x = 0; x < board_size_; ++x) {
      Square sq{x, y};
      absl::StrAppend(&s, "| ", at(sq).ToString(), " ");
    }
    absl::StrAppend(&s, "|\n");
    absl::StrAppend(&s, "  ---------------------------------\n");
  }
  // File labels.
  absl::StrAppend(&s, "    ");
  for (int8_t x = 0; x < board_size_; ++x) {
    absl::StrAppend(&s, FileToString(x), "   ");
  }
  absl::StrAppend(&s, "\n");
  absl::StrAppend(&s, "To play: ", to_play_ == Color::kWhite ? "W" : "B", "\n");
  absl::StrAppend(&s, "En passant square: ", SquareToString(EpSquare()), "\n");
  absl::StrAppend(&s, "50-moves clock: ", IrreversibleMoveCounter(), "\n");
  absl::StrAppend(&s, "Move number: ", move_number_, "\n\n");
  absl::StrAppend(&s, "Castling rights:\n");
  absl::StrAppend(&s, "White left (queen-side): ",
                  CastlingRight(Color::kWhite, CastlingDirection::kLeft), "\n");
  if (CastlingRight(Color::kWhite, CastlingDirection::kLeft)) {
    absl::StrAppend(
        &s, "White left (queen-side) rook: ",
        MaybeCastlingRookSquare(Color::kWhite, CastlingDirection::kLeft)
            .value()
            .ToString(),
        "\n");
  }
  absl::StrAppend(&s, "White right (king-side): ",
                  CastlingRight(Color::kWhite, CastlingDirection::kRight),
                  "\n");
  if (CastlingRight(Color::kWhite, CastlingDirection::kRight)) {
    absl::StrAppend(
        &s, "White right (king-side) rook: ",
        MaybeCastlingRookSquare(Color::kWhite, CastlingDirection::kRight)
            .value()
            .ToString(),
        "\n");
  }
  absl::StrAppend(&s, "Black left (queen-side): ",
                  CastlingRight(Color::kBlack, CastlingDirection::kLeft), "\n");
  if (CastlingRight(Color::kBlack, CastlingDirection::kLeft)) {
    absl::StrAppend(
        &s, "Black left (queen-side) rook: ",
        MaybeCastlingRookSquare(Color::kBlack, CastlingDirection::kLeft)
            .value()
            .ToString(),
        "\n");
  }
  absl::StrAppend(&s, "Black right (king-side): ",
                  CastlingRight(Color::kBlack, CastlingDirection::kRight),
                  "\n");
  if (CastlingRight(Color::kBlack, CastlingDirection::kRight)) {
    absl::StrAppend(
        &s, "Black right (king-side) rook: ",
        MaybeCastlingRookSquare(Color::kBlack, CastlingDirection::kRight)
            .value()
            .ToString(),
        "\n");
  }
  absl::StrAppend(&s, "\n");
  return s;
}
References at(), CastlingRight(), EpSquare(), open_spiel::chess::FileToString(), IrreversibleMoveCounter(), open_spiel::chess::kBlack, open_spiel::chess::kLeft, open_spiel::chess::kRight, open_spiel::chess::kWhite, MaybeCastlingRookSquare(), open_spiel::chess::RankToString(), absl::StrAppend(), absl::StrCat(), ToFEN(), value, x, and y.
Referenced by open_spiel::chess::ChessState::DebugString(), and open_spiel::chess::operator<<().
EpSquare()
Square open_spiel::chess::ChessBoard::EpSquare () const inline
Definition at line 277 of file chess_board.h.
{ return ep_square_; }
Referenced by ApplyMove(), DebugString(), SetEpSquare(), ToDarkFEN(), and ToFEN().
find()
Square open_spiel::chess::ChessBoard::find (const Piece & piece) const
Definition at line 482 of file chess_board.cc.
{
  for (int8_t y = 0; y < board_size_; ++y) {
    for (int8_t x = 0; x < board_size_; ++x) {
      Square sq{x, y};
      if (at(sq) == piece) {
        return sq;
      }
    }
  }
  return kInvalidSquare;
}
References at(), x, and y.
Referenced by FindRookForCastling(), GenerateLegalMoves(), GenerateLegalPawnCaptures(), open_spiel::kriegspiel::GetCheckType(), InCheck(), and TestApplyMove().
FindRookForCastling()
Square open_spiel::chess::ChessBoard::FindRookForCastling (Color color, CastlingDirection dir) const
Definition at line 1799 of file chess_board.cc.
{
  Square my_king = find(Piece{color, PieceType::kKing});
  Piece rook_to_find{color, PieceType::kRook};
  int canonical_x = dir == CastlingDirection::kLeft ? 0 : (board_size_ - 1);
  Square canonical_sq = Square{static_cast<int8_t>(canonical_x), my_king.y};
  if (board_[SquareToIndex_(canonical_sq)] == rook_to_find) {
    return canonical_sq;
  } else {
    // Find all rooks.
    int x_offset = dir == CastlingDirection::kLeft ? -1 : 1;
    int x = my_king.x + x_offset;
    std::set<Square> rooks;
    while (x < board_size_ && x >= 0) {
      auto sq = Square{static_cast<int8_t>(x), my_king.y};
      auto index = SquareToIndex_(sq);
      if (board_[index] == rook_to_find) {
        rooks.insert(sq);
      }
      x += x_offset;
    }
    // Failing here means the FEN is either from chess960 or malformed (the FEN
    // says we have castling rights, but there is no rook on the canonical
    // square, and more than one rook in the castling direction). This provides
    // partial support for chess960, but not for loading a mid-game chess960
    // position where two rooks ended up on the same side, while there's still
    // castling right on that side (we can't determine which rook to castle
    // with then). Solving this will require implementing a chess960-specific
    // FEN format.
    SPIEL_CHECK_EQ(rooks.size(), 1);
    return *rooks.begin();
  }
}
References dir, find(), open_spiel::chess::kKing, open_spiel::chess::kLeft, open_spiel::chess::kRook, SPIEL_CHECK_EQ, open_spiel::chess_common::Square::x, x, and open_spiel::chess_common::Square::y.
Referenced by BoardFromFEN().
GenerateLegalMoves() [1/2]
void open_spiel::chess::ChessBoard::GenerateLegalMoves (const MoveYieldFn & yield) const inline
Definition at line 305 of file chess_board.h.
{
    GenerateLegalMoves(yield, to_play_);
  }
References GenerateLegalMoves().
Referenced by GenerateLegalMoves(), HasLegalMoves(), IsMoveLegal(), ParseLANMove(), ParseSANMove(), and open_spiel::chess::Move::ToSAN().
GenerateLegalMoves() [2/2]
void open_spiel::chess::ChessBoard::GenerateLegalMoves (const MoveYieldFn & yield, Color color) const
Definition at line 495 of file chess_board.cc.
{
  // We do not need to filter moves that would result for King to move / stay
  // in check, so we can yield all pseudo legal moves
  if (king_in_check_allowed_) {
    GeneratePseudoLegalMoves(yield, color);
  } else {
    auto king_square = find(Piece{color, PieceType::kKing});
    GeneratePseudoLegalMoves(
        [this, &king_square, &yield, color](const Move &move) {
          // See if the move is legal by applying, checking whether the king is
          // under attack, and undoing the move.
          // TODO: Optimize this.
          auto board_copy = *this;
          board_copy.ApplyMove(move);
          auto ks =
              at(move.from).type == PieceType::kKing ? move.to : king_square;
          if (board_copy.UnderAttack(ks, color)) {
            return true;
          } else {
            return yield(move);
          }
        },
        color);
  }
}
References at(), find(), GeneratePseudoLegalMoves(), open_spiel::chess::kKing, and open_spiel::chess::Piece::type.
GenerateLegalPawnCaptures()
void open_spiel::chess::ChessBoard::GenerateLegalPawnCaptures (const MoveYieldFn & yield, Color color) const
Definition at line 620 of file chess_board.cc.
{
  // We do not need to filter moves that would result for King to move / stay
  // in check, so we can yield all pseudo legal moves
  if (king_in_check_allowed_) {
    GeneratePseudoLegalPawnCaptures(yield, color);
  } else {
    auto king_square = find(Piece{color, PieceType::kKing});
    GeneratePseudoLegalPawnCaptures(
        [this, &king_square, &yield, color](const Move &move) {
          // See if the move is legal by applying, checking whether the king is
          // under attack, and undoing the move.
          // TODO: Optimize this.
          auto board_copy = *this;
          board_copy.ApplyMove(move);
          auto ks =
              at(move.from).type == PieceType::kKing ? move.to : king_square;
          if (board_copy.UnderAttack(ks, color)) {
            return true;
          } else {
            return yield(move);
          }
        },
        color);
  }
}
References at(), find(), GeneratePseudoLegalPawnCaptures(), open_spiel::chess::kKing, and open_spiel::chess::Piece::type.
Referenced by open_spiel::kriegspiel::GeneratesUmpireMessage(), and open_spiel::kriegspiel::GetUmpireMessage().
GeneratePseudoLegalMoves()
void open_spiel::chess::ChessBoard::GeneratePseudoLegalMoves (const MoveYieldFn & yield, Color color, PseudoLegalMoveSettings settings = PseudoLegalMoveSettings::kAcknowledgeEnemyPieces) const
Definition at line 525 of file chess_board.cc.
{
  bool generating = true;
#define YIELD(move)     \
  if (!yield(move)) {   \
    generating = false; \
  }
  if (allow_pass_move_) YIELD(kPassMove);
  for (int8_t y = 0; y < board_size_ && generating; ++y) {
    for (int8_t x = 0; x < board_size_ && generating; ++x) {
      Square sq{x, y};
      auto &piece = at(sq);
      if (piece.type != PieceType::kEmpty && piece.color == color) {
        switch (piece.type) {
          case PieceType::kKing:
            GenerateKingDestinations_(
                sq, color,
                [&yield, &piece, &sq, &generating](const Square &to) {
                  YIELD(Move(sq, to, piece));
                });
            GenerateCastlingDestinations_(
                sq, color, settings,
                [&yield, &piece, &sq, &generating](const Square &to) {
                  YIELD(Move(sq, to, piece, PieceType::kEmpty, true));
                });
            break;
          case PieceType::kQueen:
            GenerateQueenDestinations_(
                sq, color, settings,
                [&yield, &sq, &piece, &generating](const Square &to) {
                  YIELD(Move(sq, to, piece));
                });
            break;
          case PieceType::kRook:
            GenerateRookDestinations_(
                sq, color, settings,
                [&yield, &sq, &piece, &generating](const Square &to) {
                  YIELD(Move(sq, to, piece));
                });
            break;
          case PieceType::kBishop:
            GenerateBishopDestinations_(
                sq, color, settings,
                [&yield, &sq, &piece, &generating](const Square &to) {
                  YIELD(Move(sq, to, piece));
                });
            break;
          case PieceType::kKnight:
            GenerateKnightDestinations_(
                sq, color,
                [&yield, &sq, &piece, &generating](const Square &to) {
                  YIELD(Move(sq, to, piece));
                });
            break;
          case PieceType::kPawn:
            GeneratePawnDestinations_(
                sq, color, settings,
                [&yield, &sq, &piece, &generating, this](const Square &to) {
                  if (IsPawnPromotionRank(to)) {
                    YIELD(Move(sq, to, piece, PieceType::kQueen));
                    YIELD(Move(sq, to, piece, PieceType::kRook));
                    YIELD(Move(sq, to, piece, PieceType::kBishop));
                    YIELD(Move(sq, to, piece, PieceType::kKnight));
                  } else {
                    YIELD(Move(sq, to, piece));
                  }
                });
            GeneratePawnCaptureDestinations_(
                sq, color, settings, true, /* include enpassant */
                [&yield, &sq, &piece, &generating, this](const Square &to) {
                  if (IsPawnPromotionRank(to)) {
                    YIELD(Move(sq, to, piece, PieceType::kQueen));
                    YIELD(Move(sq, to, piece, PieceType::kRook));
                    YIELD(Move(sq, to, piece, PieceType::kBishop));
                    YIELD(Move(sq, to, piece, PieceType::kKnight));
                  } else {
                    YIELD(Move(sq, to, piece));
                  }
                });
            break;
          default:
            std::cerr << "Unknown piece type: " << static_cast<int>(piece.type)
                      << std::endl;
        }
      }
    }
  }
#undef YIELD
}
References at(), IsPawnPromotionRank(), open_spiel::chess::kBishop, open_spiel::chess::kEmpty, open_spiel::chess::kKing, open_spiel::chess::kKnight, open_spiel::chess::kPassMove, open_spiel::chess::kPawn, open_spiel::chess::kQueen, open_spiel::chess::kRook, to, x, y, and YIELD.
Referenced by GenerateLegalMoves(), and open_spiel::kriegspiel::GetCheckType().
GeneratePseudoLegalPawnCaptures()
void open_spiel::chess::ChessBoard::GeneratePseudoLegalPawnCaptures (const MoveYieldFn & yield, Color color, PseudoLegalMoveSettings settings = PseudoLegalMoveSettings::kAcknowledgeEnemyPieces) const
Definition at line 650 of file chess_board.cc.
{
  bool generating = true;
#define YIELD(move)     \
  if (!yield(move)) {   \
    generating = false; \
  }
  for (int8_t y = 0; y < board_size_ && generating; ++y) {
    for (int8_t x = 0; x < board_size_ && generating; ++x) {
      Square sq{x, y};
      auto &piece = at(sq);
      if (piece.type == PieceType::kPawn && piece.color == color) {
        GeneratePawnCaptureDestinations_(
            sq, color, settings, true, /* include enpassant */
            [&yield, &sq, &piece, &generating, this](const Square &to) {
              if (IsPawnPromotionRank(to)) {
                YIELD(Move(sq, to, piece, PieceType::kQueen));
                YIELD(Move(sq, to, piece, PieceType::kRook));
                YIELD(Move(sq, to, piece, PieceType::kBishop));
                YIELD(Move(sq, to, piece, PieceType::kKnight));
              } else {
                YIELD(Move(sq, to, piece));
              }
            });
      }
    }
  }
#undef YIELD
}
References at(), IsPawnPromotionRank(), open_spiel::chess::kBishop, open_spiel::chess::kKnight, open_spiel::chess::kPawn, open_spiel::chess::kQueen, open_spiel::chess::kRook, to, x, y, and YIELD.
Referenced by GenerateLegalPawnCaptures().
HashValue()
uint64_t open_spiel::chess::ChessBoard::HashValue () const inline
Definition at line 428 of file chess_board.h.
{ return zobrist_hash_; }
Referenced by open_spiel::chess::ChessState::ChessState(), open_spiel::chess::ChessState::ChessState(), open_spiel::dark_chess::DarkChessState::DarkChessState(), open_spiel::chess::ChessState::DoApplyAction(), open_spiel::dark_chess::DarkChessState::DoApplyAction(), open_spiel::kriegspiel::KriegspielState::DoApplyAction(), open_spiel::rbc::RbcState::DoApplyAction(), open_spiel::kriegspiel::KriegspielState::KriegspielState(), open_spiel::rbc::RbcState::RbcState(), open_spiel::chess::ChessState::UndoAction(), open_spiel::dark_chess::DarkChessState::UndoAction(), open_spiel::kriegspiel::KriegspielState::UndoAction(), and open_spiel::rbc::RbcState::UndoAction().
HasLegalMoves()
bool open_spiel::chess::ChessBoard::HasLegalMoves () const inline
Definition at line 321 of file chess_board.h.
{
    bool found = false;
    GenerateLegalMoves([&found](const Move&) {
      found = true;
      return false;  // We don't need any more moves.
    });
    return found;
  }
References GenerateLegalMoves().
HasSufficientMaterial()
bool open_spiel::chess::ChessBoard::HasSufficientMaterial () const
Definition at line 742 of file chess_board.cc.
{
  // Try to detect these 4 conditions.
  // 1. K vs K
  // 2. K+B vs K
  // 3. K+N vs K
  // 4. K+B* vs K+B* (all bishops on same coloured squares)
  // If king is allowed to move to/stay in check, any material is sufficient
  // material. If there is no material, then there is also no opponent king and
  // that means the game had already ended.
  if (king_in_check_allowed_) {
    return true;
  }
  // Indexed by colour.
  int knights[2] = {0, 0};
  int dark_bishops[2] = {0, 0};
  int light_bishops[2] = {0, 0};
  for (int8_t y = 0; y < board_size_; ++y) {
    for (int8_t x = 0; x < board_size_; ++x) {
      const auto &piece = at(Square{x, y});
      // If we have a queen, rook, or pawn, we have sufficient material.
      // This is early exit for almost all positions. We check rooks first
      // because they tend to appear on the corners of boards.
      if (piece.color != Color::kEmpty) {
        if (piece.type == PieceType::kRook || piece.type == PieceType::kPawn ||
            piece.type == PieceType::kQueen) {
          return true;
        }
        // We don't care about kings.
        if (piece.type == PieceType::kKing) {
          continue;
        }
        if (piece.type == PieceType::kKnight) {
          ++knights[static_cast<size_t>(piece.color)];
        }
        if (piece.type == PieceType::kBishop) {
          bool is_dark = ((x + y) % 2 == 0);
          if (is_dark) {
            ++dark_bishops[static_cast<size_t>(piece.color)];
          } else {
            ++light_bishops[static_cast<size_t>(piece.color)];
          }
        }
      }
    }
  }
  // Having two knights allows helpmate.
  if (knights[0] > 1 || knights[1] > 1) {
    return true;
  }
  if (knights[0] == 1) {
    // If we have anything else, mate is possible.
    if (light_bishops[0] > 0 || dark_bishops[0] > 0) {
      return true;
    } else {
      // If one side only has a knight, the other side must have something (#3).
      return knights[1] > 0 || dark_bishops[1] > 0 || light_bishops[1] > 0;
    }
  }
  if (knights[1] == 1) {
    // If we have anything else, mate is possible.
    if (light_bishops[1] > 0 || dark_bishops[1] > 0) {
      return true;
    } else {
      // If one side only has a knight, the other side must have something (#3).
      return knights[0] > 0 || dark_bishops[0] > 0 || light_bishops[0] > 0;
    }
  }
  // Now we only have bishops and kings. We must have two bishops on opposite
  // coloured squares (from either side) to not be a draw.
  // This covers #1, #2, and #4.
  bool dark_bishop_exists = (dark_bishops[0] + dark_bishops[1]) > 0;
  bool light_bishop_exists = (light_bishops[0] + light_bishops[1]) > 0;
  return dark_bishop_exists && light_bishop_exists;
}
References at(), open_spiel::chess::kBishop, open_spiel::chess::kEmpty, open_spiel::chess::kKing, open_spiel::chess::kKnight, open_spiel::chess::kPawn, open_spiel::chess::kQueen, open_spiel::chess::kRook, x, and y.
InBoardArea()
bool open_spiel::chess::ChessBoard::InBoardArea (const Square & sq) const inline
Definition at line 379 of file chess_board.h.
{
    return sq.x >= 0 && sq.x < board_size_ && sq.y >= 0 && sq.y < board_size_;
  }
References open_spiel::chess_common::Square::x, and open_spiel::chess_common::Square::y.
InCheck()
bool open_spiel::chess::ChessBoard::InCheck () const inline
Definition at line 418 of file chess_board.h.
                       {
    return UnderAttack(find(Piece{to_play_, PieceType::kKing}), to_play_);
  }
References find(), open_spiel::chess::kKing, and UnderAttack().
IrreversibleMoveCounter()
int32_t open_spiel::chess::ChessBoard::IrreversibleMoveCounter () const inline
Definition at line 280 of file chess_board.h.
{ return irreversible_move_counter_; }
Referenced by ApplyMove(), DebugString(), and ToDarkFEN().
IsBreachingMove()
bool open_spiel::chess::ChessBoard::IsBreachingMove (Move move) const
Definition at line 684 of file chess_board.cc.
{
  if (tested_move == kPassMove) return false;
  const Piece& piece = tested_move.piece;
  if (piece.type == PieceType::kEmpty) return false;
  if (piece.type == PieceType::kKnight) return false;
  if (piece.type == PieceType::kPawn) return false;
  // King never makes breaching moves: a castling that would be breaching
  // is considered an illegal move.
  if (piece.type == PieceType::kKing) return false;
  SPIEL_DCHECK_TRUE(piece.type == PieceType::kQueen ||
                    piece.type == PieceType::kRook ||
                    piece.type == PieceType::kBishop);
  // The move is not breaching, if it is generated with
  // PseudoLegalMoveSettings::kAcknowledgeEnemyPieces
  bool is_breaching = true;
  const auto check_breaching = [&](const Square &to) {
    if (to == tested_move.to) is_breaching = false;
  };
  // Queen moves are a combination of rook and bishop moves.
  if (piece.type == PieceType::kRook || piece.type == PieceType::kQueen) {
    GenerateRookDestinations_(tested_move.from, piece.color,
                              kAcknowledgeEnemyPieces, check_breaching);
  }
  if (piece.type == PieceType::kBishop || piece.type == PieceType::kQueen) {
    GenerateBishopDestinations_(tested_move.from, piece.color,
                                kAcknowledgeEnemyPieces, check_breaching);
  }
  return is_breaching;
}
References open_spiel::chess::Piece::color, open_spiel::chess::Move::from, open_spiel::chess::kAcknowledgeEnemyPieces, open_spiel::chess::kBishop, open_spiel::chess::kEmpty, open_spiel::chess::kKing, open_spiel::chess::kKnight, open_spiel::chess::kPassMove, open_spiel::chess::kPawn, open_spiel::chess::kQueen, open_spiel::chess::kRook, open_spiel::chess::Move::piece, SPIEL_DCHECK_TRUE, open_spiel::chess::Move::to, to, and open_spiel::chess::Piece::type.
Referenced by BreachingMoveToCaptureMove().
IsEmpty()
bool open_spiel::chess::ChessBoard::IsEmpty (const Square & sq) const inline
Definition at line 383 of file chess_board.h.
{
    const Piece& piece = board_[SquareToIndex_(sq)];
    return piece.type == PieceType::kEmpty;
  }
References open_spiel::chess::kEmpty, and open_spiel::chess::Piece::type.
IsEmptyOrEnemy()
bool open_spiel::chess::ChessBoard::IsEmptyOrEnemy (const Square & sq, Color our_color) const inline
Definition at line 398 of file chess_board.h.
{
    const Piece& piece = board_[SquareToIndex_(sq)];
    return piece.color != our_color;
  }
References open_spiel::chess::Piece::color.
IsEnemy()
bool open_spiel::chess::ChessBoard::IsEnemy (const Square & sq, Color our_color) const inline
Definition at line 388 of file chess_board.h.
{
    const Piece& piece = board_[SquareToIndex_(sq)];
    return piece.type != PieceType::kEmpty && piece.color != our_color;
  }
References open_spiel::chess::Piece::color, open_spiel::chess::kEmpty, and open_spiel::chess::Piece::type.
IsFriendly()
bool open_spiel::chess::ChessBoard::IsFriendly (const Square & sq, Color our_color) const inline
Definition at line 393 of file chess_board.h.
{
    const Piece& piece = board_[SquareToIndex_(sq)];
    return piece.color == our_color;
  }
References open_spiel::chess::Piece::color.
IsMoveLegal()
bool open_spiel::chess::ChessBoard::IsMoveLegal (const Move & tested_move) const inline
Definition at line 330 of file chess_board.h.
{
    bool found = false;
    GenerateLegalMoves([&found, &tested_move](const Move& found_move) {
      if (tested_move == found_move) {
        found = true;
        return false;  // We don't need any more moves.
      }
      return true;
    });
    return found;
  }
References GenerateLegalMoves().
Referenced by open_spiel::rbc::RbcState::DoApplyAction(), open_spiel::kriegspiel::GeneratesUmpireMessage(), and open_spiel::kriegspiel::GetUmpireMessage().
IsPawnPromotionRank()
bool open_spiel::chess::ChessBoard::IsPawnPromotionRank (const Square & sq) const inline
Definition at line 409 of file chess_board.h.
{
    // No need to test for color here because a pawn can't be on the "wrong"
    // promotion rank.
    return sq.y == 0 || sq.y == (board_size_ - 1);
  }
References open_spiel::chess_common::Square::y.
Referenced by ApplyMove(), GeneratePseudoLegalMoves(), and GeneratePseudoLegalPawnCaptures().
IsPawnStartingRank()
bool open_spiel::chess::ChessBoard::IsPawnStartingRank (const Square & sq, Color our_color) const inline
Definition at line 404 of file chess_board.h.
{
    return ((our_color == Color::kWhite && sq.y == 1) ||
            (our_color == Color::kBlack && sq.y == (board_size_ - 2)));
  }
References open_spiel::chess::kBlack, open_spiel::chess::kWhite, and open_spiel::chess_common::Square::y.
KingInCheckAllowed()
bool open_spiel::chess::ChessBoard::KingInCheckAllowed () const inline
Definition at line 424 of file chess_board.h.
{ return king_in_check_allowed_; }
Referenced by open_spiel::chess::Move::ToSAN().
MaybeCastlingRookSquare()
absl::optional< Square > open_spiel::chess::ChessBoard::MaybeCastlingRookSquare (Color side, CastlingDirection direction) const
Definition at line 1749 of file chess_board.cc.
{
  switch (direction) {
    case CastlingDirection::kLeft:
      return castling_rights_[ToInt(side)].left_castle;
    case CastlingDirection::kRight:
      return castling_rights_[ToInt(side)].right_castle;
    default:
      SpielFatalError("Unknown direction.");
      return Square{0, 0};
  }
}
References open_spiel::chess::kLeft, open_spiel::chess::kRight, open_spiel::SpielFatalError(), and open_spiel::chess::ToInt().
Referenced by CastlingRight(), DebugString(), and SetCastlingRight().
Movenumber()
int32_t open_spiel::chess::ChessBoard::Movenumber () const inline
Definition at line 281 of file chess_board.h.
{ return move_number_; }
ParseLANMove()
absl::optional< Move > open_spiel::chess::ChessBoard::ParseLANMove (const std::string & move) const
Definition at line 971 of file chess_board.cc.
{
  if (move.empty()) { return absl::nullopt; }
  // Long algebraic notation moves (of the variant we care about) are in one of
  // two forms -
  // "anan" (eg. "e2e4") or "anana" (eg. "f7f8q")
  if (move.size() == 4 || move.size() == 5) {
    if (move[0] < 'a' || move[0] >= ('a' + board_size_) || move[1] < '1' ||
        move[1] >= ('1' + board_size_) || move[2] < 'a' ||
        move[2] >= ('a' + board_size_) || move[3] < '1' ||
        move[3] >= ('1' + board_size_)) {
      return absl::nullopt;
    }
    if (move.size() == 5 && move[4] != 'q' && move[4] != 'r' &&
        move[4] != 'b' && move[4] != 'n') {
      return absl::nullopt;
    }
    auto from = SquareFromString(move.substr(0, 2));
    auto to = SquareFromString(std::string(absl::ClippedSubstr(move, 2, 2)));
    if (from && to) {
      absl::optional<PieceType> promotion_type;
      if (move.size() == 5) {
        promotion_type = PieceTypeFromChar(move[4]);
        if (!promotion_type) {
          std::cerr << "Invalid promotion type" << std::endl;
          return absl::nullopt;
        }
      }
      std::vector<Move> candidates;
      GenerateLegalMoves(
          [&to, &from, &promotion_type, &candidates](const Move &move) {
            if (move.from == *from && move.to == *to &&
                (!promotion_type || (move.promotion_type == *promotion_type))) {
              candidates.push_back(move);
            }
            return true;
          });
      if (candidates.empty()) {
        std::cerr << "Illegal move - " << move << " on " << ToUnicodeString()
                  << std::endl;
        return Move();
      } else if (candidates.size() > 1) {
        std::cerr << "Multiple matches (is promotion type missing?) - " << move
                  << std::endl;
        return Move();
      }
      return candidates[0];
    }
  } else {
    return absl::nullopt;
  }
  SpielFatalError("All conditionals failed; this is a bug.");
}
References absl::ClippedSubstr(), from, GenerateLegalMoves(), open_spiel::chess::PieceTypeFromChar(), open_spiel::SpielFatalError(), open_spiel::chess::SquareFromString(), to, and ToUnicodeString().
Referenced by ParseMove().
ParseMove()
absl::optional< Move > open_spiel::chess::ChessBoard::ParseMove (const std::string & move) const
Definition at line 827 of file chess_board.cc.
{
  // First see if they are in the long form -
  // "anan" (eg. "e2e4") or "anana" (eg. "f7f8q")
  // SAN moves will never have this form because an SAN move that starts with
  // a lowercase letter must be a pawn move, and pawn moves will never require
  // rank disambiguation (meaning the second character will never be a number).
  auto lan_move = ParseLANMove(move);
  if (lan_move) {
    return lan_move;
  }
  auto san_move = ParseSANMove(move);
  if (san_move) {
    return san_move;
  }
  return absl::nullopt;
}
References ParseLANMove(), and ParseSANMove().
Referenced by open_spiel::chess::ChessState::ParseMoveToAction().
ParseSANMove()
absl::optional< Move > open_spiel::chess::ChessBoard::ParseSANMove (const std::string & move) const
Definition at line 846 of file chess_board.cc.
{
  std::string move = move_str;
  if (move.empty()) return absl::nullopt;
  if (absl::StartsWith(move, "O-O-O")) {
    // Queenside / left castling.
    std::vector<Move> candidates;
    GenerateLegalMoves([&candidates](const Move &move) {
      if (move.is_castling && move.to.x == 2) {
        candidates.push_back(move);
      }
      return true;
    });
    if (candidates.size() == 1) return candidates[0];
    std::cerr << "Invalid O-O-O" << std::endl;
    return absl::nullopt;
  }
  if (absl::StartsWith(move, "O-O")) {
    // Kingside / right castling.
    std::vector<Move> candidates;
    GenerateLegalMoves([&candidates](const Move &move) {
      if (move.is_castling && move.to.x == 6) {
        candidates.push_back(move);
      }
      return true;
    });
    if (candidates.size() == 1) return candidates[0];
    std::cerr << "Invalid O-O" << std::endl;
    return absl::nullopt;
  }
  auto move_annotation = SplitAnnotations(move);
  move = move_annotation.first;
  if (move.empty()) { return absl::nullopt; }
  auto annotation = move_annotation.second;
  // A move starts with a single letter identifying the piece. This may be
  // omitted for pawns.
  PieceType piece_type = PieceType::kPawn;
  std::string pieces = "PNBRQK";
  if (pieces.find(move[0]) != std::string::npos) {  // NOLINT
    auto maybe_piece_type = PieceTypeFromChar(move[0]);
    if (!maybe_piece_type) {
      std::cerr << "Invalid piece type: " << move[0] << std::endl;
      return absl::nullopt;
    }
    piece_type = *maybe_piece_type;
    move = std::string(absl::ClippedSubstr(move, 1));
  }
  // A move always ends with the destination square.
  if (move.size() < 2) {
    std::cerr << "Missing destination square" << std::endl;
    return absl::nullopt;
  }
  auto destination = std::string(absl::ClippedSubstr(move, move.size() - 2));
  move = move.substr(0, move.size() - 2);
  auto dest_file = ParseFile(destination[0]);
  auto dest_rank = ParseRank(destination[1]);
  if (!dest_file || !dest_rank) {
    std::cerr << "Failed to parse destination square: " << destination
              << std::endl;
    return absl::nullopt;
  }
  Square destination_square{*dest_file, *dest_rank};
  // Captures are indicated by a 'x' immediately preceding the destination.
  // This is irrelevant for parsing, so we just drop it.
  if (!move.empty() && move[move.size() - 1] == 'x') {
    move = move.substr(0, move.size() - 1);
  }
  // If necessary, source rank and/or file are also included for
  // disambiguation.
  absl::optional<int8_t> source_file, source_rank;
  if (!move.empty()) {
    source_file = ParseFile(move[0]);
    if (source_file) {
      move = std::string(absl::ClippedSubstr(move, 1));
    }
  }
  if (!move.empty()) {
    source_rank = ParseRank(move[0]);
    if (source_rank) {
      move = std::string(absl::ClippedSubstr(move, 1));
    }
  }
  if (!move.empty()) { return absl::nullopt; }
  // Pawn promations are annotated with =Q to indicate the promotion type.
  absl::optional<PieceType> promotion_type;
  if (!annotation.empty() && annotation[0] == '=') {
    if (annotation.size() < 2) { return absl::nullopt; }
    auto maybe_piece = PieceTypeFromChar(annotation[1]);
    if (!maybe_piece) return absl::optional<Move>();
    promotion_type = maybe_piece;
  }
  std::vector<Move> candidates;
  GenerateLegalMoves([&candidates, destination_square, piece_type, source_file,
                      source_rank, promotion_type, this](const Move &move) {
    PieceType moving_piece_type = at(move.from).type;
    if (move.to == destination_square && moving_piece_type == piece_type &&
        (!source_file || move.from.x == *source_file) &&
        (!source_rank || move.from.y == *source_rank) &&
        (!promotion_type || move.promotion_type == *promotion_type)) {
      candidates.push_back(move);
    }
    return true;
  });
  if (candidates.size() == 1) return candidates[0];
  std::cerr << "expected exactly one matching move, got " << candidates.size()
            << std::endl;
  return absl::optional<Move>();
}
References at(), absl::ClippedSubstr(), GenerateLegalMoves(), open_spiel::chess::kPawn, open_spiel::chess::ParseFile(), open_spiel::chess::ParseRank(), pieces(), open_spiel::chess::PieceTypeFromChar(), open_spiel::chess::SplitAnnotations(), absl::StartsWith(), and open_spiel::chess::Piece::type.
Referenced by ParseMove().
pieces()
const std::array< Piece, k2dMaxBoardSize > & open_spiel::chess::ChessBoard::pieces () const inline
Definition at line 272 of file chess_board.h.
{ return board_; }
Referenced by ParseSANMove().
set_square()
void open_spiel::chess::ChessBoard::set_square (Square sq, Piece p)
Definition at line 1731 of file chess_board.cc.
{
  static const ZobristTableU64<k2dMaxBoardSize, 3, 7> kZobristValues(
      /*seed=*/2765481);
  // First, remove the current piece from the hash.
  auto position = SquareToIndex_(sq);
  auto current_piece = at(sq);
  zobrist_hash_ ^=
      kZobristValues[position][static_cast<int>(current_piece.color)]
                    [static_cast<int>(current_piece.type)];
  // Then add the new piece
  zobrist_hash_ ^= kZobristValues[position][static_cast<int>(piece.color)]
                                 [static_cast<int>(piece.type)];
  board_[position] = piece;
}
References at(), open_spiel::chess::Piece::color, and open_spiel::chess::Piece::type.
Referenced by ApplyMove(), and BoardFromFEN().
SetCastlingRight()
void open_spiel::chess::ChessBoard::SetCastlingRight (Color side, CastlingDirection direction, absl::optional< Square > maybe_rook_square)
Definition at line 1774 of file chess_board.cc.
{
  static const ZobristTableU64<2, 2, 2> kZobristValues(/*seed=*/876387212);
  // Remove old value from hash (note that we only use bool for castling rights,
  // since all states derived from the same game will have the same initial rook
  // squares).
  bool can_castle_before = MaybeCastlingRookSquare(side, direction).has_value();
  zobrist_hash_ ^=
      kZobristValues[ToInt(side)][ToInt(direction)][can_castle_before];
  // Then add the new value.
  bool can_castle_now = maybe_rook_square.has_value();
  zobrist_hash_ ^=
      kZobristValues[ToInt(side)][ToInt(direction)][can_castle_now];
  switch (direction) {
    case CastlingDirection::kLeft:
      castling_rights_[ToInt(side)].left_castle = maybe_rook_square;
      break;
    case CastlingDirection::kRight:
      castling_rights_[ToInt(side)].right_castle = maybe_rook_square;
      break;
  }
}
References absl::optional< T >::has_value(), open_spiel::chess::kLeft, open_spiel::chess::kRight, MaybeCastlingRookSquare(), and open_spiel::chess::ToInt().
Referenced by ApplyMove(), and BoardFromFEN().
SetEpSquare()
void open_spiel::chess::ChessBoard::SetEpSquare (Square sq)
Definition at line 1848 of file chess_board.cc.
{
  static const ZobristTableU64<kMaxBoardSize, kMaxBoardSize> kZobristValues(
      /*seed=*/837261);
  if (EpSquare() != kInvalidSquare) {
    // Remove en passant square if there was one.
    zobrist_hash_ ^= kZobristValues[EpSquare().x][EpSquare().y];
  }
  if (sq != kInvalidSquare) {
    zobrist_hash_ ^= kZobristValues[sq.x][sq.y];
  }
  ep_square_ = sq;
}
References EpSquare(), open_spiel::chess_common::Square::x, and open_spiel::chess_common::Square::y.
Referenced by ApplyMove(), and BoardFromFEN().
SetToPlay()
void open_spiel::chess::ChessBoard::SetToPlay (Color c)
Definition at line 1833 of file chess_board.cc.
{
  static const ZobristTableU64<2> kZobristValues(/*seed=*/284628);
  // Remove old color and add new to play.
  zobrist_hash_ ^= kZobristValues[ToInt(to_play_)];
  zobrist_hash_ ^= kZobristValues[ToInt(c)];
  to_play_ = c;
}
References open_spiel::chess::ToInt().
Referenced by ApplyMove(), and BoardFromFEN().
TestApplyMove()
bool open_spiel::chess::ChessBoard::TestApplyMove (const Move & move)
Definition at line 1174 of file chess_board.cc.
{
  Color color = to_play_;
  ApplyMove(move);
  return !UnderAttack(find(Piece{color, PieceType::kKing}), color);
}
References ApplyMove(), find(), open_spiel::chess::kKing, and UnderAttack().
ToDarkFEN()
std::string open_spiel::chess::ChessBoard::ToDarkFEN (const ObservationTable & observability_table, Color color) const
Definition at line 1645 of file chess_board.cc.
{
  std::string fen;
  // 1. encode the board.
  for (int8_t rank = board_size_ - 1; rank >= 0; --rank) {
    int num_empty = 0;
    for (int8_t file = 0; file < board_size_; ++file) {
      size_t index = SquareToIndex_(chess::Square{file, rank});
      if (!observability_table[index]) {
        if (num_empty > 0) {
          fen += std::to_string(num_empty);
          num_empty = 0;
        }
        fen.push_back('?');
      } else {
        const Piece &piece = at(chess::Square{file, rank});
        if (piece == chess::kEmptyPiece) {
          ++num_empty;
        } else {
          if (num_empty > 0) {
            fen += std::to_string(num_empty);
            num_empty = 0;
          }
          absl::StrAppend(&fen, piece.ToString());
        }
      }
    }
    if (num_empty > 0) {
      absl::StrAppend(&fen, num_empty);
    }
    if (rank > 0) {
      fen.push_back('/');
    }
  }
  // 2. color to play.
  absl::StrAppend(&fen, " ", ToPlay() == chess::Color::kWhite ? "w" : "b");
  // 3. by castling rights.
  absl::StrAppend(&fen, " ");
  std::string castling_rights;
  if (color == chess::Color::kWhite) {
    if (CastlingRight(chess::Color::kWhite, chess::CastlingDirection::kRight)) {
      castling_rights.push_back('K');
    }
    if (CastlingRight(chess::Color::kWhite, chess::CastlingDirection::kLeft)) {
      castling_rights.push_back('Q');
    }
  } else {
    if (CastlingRight(chess::Color::kBlack, chess::CastlingDirection::kRight)) {
      castling_rights.push_back('k');
    }
    if (CastlingRight(chess::Color::kBlack, chess::CastlingDirection::kLeft)) {
      castling_rights.push_back('q');
    }
  }
  absl::StrAppend(&fen, castling_rights.empty() ? "-" : castling_rights);
  // 4. en passant square
  std::string ep_square = "-";
  if (EpSquare() != kInvalidSquare) {
    int8_t reversed_y_direction = color == Color::kWhite ? -1 : 1;
    Square from = EpSquare() + Offset{1, reversed_y_direction};
    Piece piece = at(from);
    if (piece.color == color && piece.type == PieceType::kPawn) {
      ep_square = SquareToString(EpSquare());
    } else {
      from = EpSquare() + Offset{-1, reversed_y_direction};
      piece = at(from);
      if (piece.color == color && piece.type == PieceType::kPawn) {
        ep_square = SquareToString(EpSquare());
      }
    }
  }
  absl::StrAppend(&fen, " ", ep_square);
  // 5. half-move clock for 50-move rule
  absl::StrAppend(&fen, " ", IrreversibleMoveCounter());
  // 6. full-move clock
  absl::StrAppend(&fen, " ", move_number_);
  return fen;
}
References at(), CastlingRight(), open_spiel::chess::Piece::color, EpSquare(), from, IrreversibleMoveCounter(), open_spiel::chess::kBlack, open_spiel::chess::kLeft, open_spiel::chess::kPawn, open_spiel::chess::kRight, open_spiel::chess::kWhite, rank, absl::StrAppend(), ToPlay(), open_spiel::chess::Piece::ToString(), and open_spiel::chess::Piece::type.
ToFEN()
std::string open_spiel::chess::ChessBoard::ToFEN () const
Definition at line 1583 of file chess_board.cc.
{
  // Example FEN: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
  std::string fen;
  // 1. encode the board.
  for (int8_t rank = board_size_ - 1; rank >= 0; --rank) {
    int num_empty = 0;
    for (int8_t file = 0; file < board_size_; ++file) {
      auto piece = at(Square{file, rank});
      if (piece == kEmptyPiece) {
        ++num_empty;
      } else {
        if (num_empty > 0) {
          absl::StrAppend(&fen, num_empty);
          num_empty = 0;
        }
        absl::StrAppend(&fen, piece.ToString());
      }
    }
    if (num_empty > 0) {
      absl::StrAppend(&fen, num_empty);
    }
    if (rank > 0) {
      fen.push_back('/');
    }
  }
  // 2. color to play.
  absl::StrAppend(&fen, " ", to_play_ == Color::kWhite ? "w" : "b");
  // 3. by castling rights.
  absl::StrAppend(&fen, " ");
  std::string castling_rights;
  if (CastlingRight(Color::kWhite, CastlingDirection::kRight)) {
    castling_rights.push_back('K');
  }
  if (CastlingRight(Color::kWhite, CastlingDirection::kLeft)) {
    castling_rights.push_back('Q');
  }
  if (CastlingRight(Color::kBlack, CastlingDirection::kRight)) {
    castling_rights.push_back('k');
  }
  if (CastlingRight(Color::kBlack, CastlingDirection::kLeft)) {
    castling_rights.push_back('q');
  }
  absl::StrAppend(&fen, castling_rights.empty() ? "-" : castling_rights);
  // 4. en passant square
  absl::StrAppend(&fen, " ");
  absl::StrAppend(
      &fen, EpSquare() == kInvalidSquare ? "-" : SquareToString(EpSquare()));
  // 5. half-move clock for 50-move rule
  absl::StrAppend(&fen, " ", irreversible_move_counter_);
  // 6. full-move clock
  absl::StrAppend(&fen, " ", move_number_);
  return fen;
}
References at(), CastlingRight(), EpSquare(), open_spiel::chess::kBlack, open_spiel::chess::kLeft, open_spiel::chess::kRight, open_spiel::chess::kWhite, rank, and absl::StrAppend().
Referenced by DebugString(), open_spiel::chess::ChessState::Serialize(), open_spiel::chess::ChessState::ToString(), open_spiel::dark_chess::DarkChessState::ToString(), open_spiel::kriegspiel::KriegspielState::ToString(), and open_spiel::rbc::RbcState::ToString().
ToPlay()
Color open_spiel::chess::ChessBoard::ToPlay () const inline
Definition at line 274 of file chess_board.h.
{ return to_play_; }
Referenced by open_spiel::chess::ActionToMove(), open_spiel::kriegspiel::GeneratesUmpireMessage(), open_spiel::kriegspiel::GetCheckType(), open_spiel::kriegspiel::GetUmpireMessage(), and ToDarkFEN().
ToUnicodeString()
std::string open_spiel::chess::ChessBoard::ToUnicodeString () const
Definition at line 1566 of file chess_board.cc.
{
  std::string out = "\n";
  for (int8_t rank = board_size_ - 1; rank >= 0; --rank) {
    out += std::to_string(rank + 1);
    for (int8_t file = 0; file < board_size_; ++file) {
      out += at(Square{file, rank}).ToUnicode();
    }
    out += "\n";
  }
  out += ' ';
  for (int8_t file = 0; file < board_size_; ++file) {
    out += ('a' + file);
  }
  out += '\n';
  return out;
}
References at(), out, and rank.
Referenced by ParseLANMove().
UnderAttack()
bool open_spiel::chess::ChessBoard::UnderAttack (const Square & sq, Color our_color) const
Definition at line 1180 of file chess_board.cc.
{
  SPIEL_CHECK_NE(sq, kInvalidSquare);
  bool under_attack = false;
  Color opponent_color = OppColor(our_color);
  // We do this by pretending we are a piece of different types, and seeing if
  // we can attack opponent pieces. Eg. if we pretend we are a knight, and can
  // attack an opponent knight, that means the knight can also attack us.
  // King moves (this is possible because we use this function for checking
  // whether we are moving into check, and we can be trying to move the king
  // into a square attacked by opponent king).
  GenerateKingDestinations_(
      sq, our_color, [this, &under_attack, &opponent_color](const Square &to) {
        if (at(to) == Piece{opponent_color, PieceType::kKing}) {
          under_attack = true;
        }
      });
  if (under_attack) {
    return true;
  }
  // Rook moves (for rooks and queens)
  GenerateRookDestinations_(
      sq, our_color, PseudoLegalMoveSettings::kAcknowledgeEnemyPieces,
      [this, &under_attack, &opponent_color](const Square &to) {
        if ((at(to) == Piece{opponent_color, PieceType::kRook}) ||
            (at(to) == Piece{opponent_color, PieceType::kQueen})) {
          under_attack = true;
        }
      });
  if (under_attack) {
    return true;
  }
  // Bishop moves (for bishops and queens)
  GenerateBishopDestinations_(
      sq, our_color, PseudoLegalMoveSettings::kAcknowledgeEnemyPieces,
      [this, &under_attack, &opponent_color](const Square &to) {
        if ((at(to) == Piece{opponent_color, PieceType::kBishop}) ||
            (at(to) == Piece{opponent_color, PieceType::kQueen})) {
          under_attack = true;
        }
      });
  if (under_attack) {
    return true;
  }
  // Knight moves
  GenerateKnightDestinations_(
      sq, our_color, [this, &under_attack, &opponent_color](const Square &to) {
        if (at(to) == Piece{opponent_color, PieceType::kKnight}) {
          under_attack = true;
        }
      });
  if (under_attack) {
    return true;
  }
  // Pawn captures.
  GeneratePawnCaptureDestinations_(
      sq, our_color, PseudoLegalMoveSettings::kAcknowledgeEnemyPieces,
      false /* no ep */,
      [this, &under_attack, &opponent_color](const Square &to) {
        if (at(to) == Piece{opponent_color, PieceType::kPawn}) {
          under_attack = true;
        }
      });
  if (under_attack) {
    return true;
  }
  return false;
}
References at(), open_spiel::chess::kAcknowledgeEnemyPieces, open_spiel::chess::kBishop, open_spiel::chess::kKing, open_spiel::chess::kKnight, open_spiel::chess::kPawn, open_spiel::chess::kQueen, open_spiel::chess::kRook, open_spiel::chess::OppColor(), SPIEL_CHECK_NE, and to.
Referenced by InCheck(), and TestApplyMove().
Member Data Documentation
left_castle
absl::optional<Square> open_spiel::chess::ChessBoard::left_castle
Definition at line 553 of file chess_board.h.
Referenced by ApplyMove().
right_castle
absl::optional<Square> open_spiel::chess::ChessBoard::right_castle
Definition at line 554 of file chess_board.h.
Referenced by ApplyMove().
The documentation for this class was generated from the following files:
open_spiel/games/chess/chess_board.h
open_spiel/games/chess/chess_board.cc