open spiel: absl::cord_internal::InlineData Class Reference
absl::cord_internal::InlineData Class Reference
#include <cord_internal.h>
Public Types
enum DefaultInitType { kDefaultInit }
Public Member Functions
constexpr InlineData () noexcept
InlineData (DefaultInitType) noexcept
InlineData (CordRep *rep) noexcept
constexpr InlineData (absl::string_view sv, CordRep *rep) noexcept
constexpr InlineData (const InlineData &rhs) noexcept
InlineData & operator= (const InlineData &rhs) noexcept
constexpr void poison ()
constexpr void unpoison ()
constexpr void poison_this ()
bool is_empty () const
bool is_tree () const
bool is_profiled () const
CordzInfo * cordz_info () const
void set_cordz_info (CordzInfo *cordz_info)
void clear_cordz_info ()
const char * as_chars () const
char * as_chars ()
CordRep * as_tree () const
void set_inline_data (const char *data, size_t n)
void copy_max_inline_to (char *dst) const
void make_tree (CordRep *rep)
void set_tree (CordRep *rep)
size_t inline_size () const
void set_inline_size (size_t size)
int Compare (const InlineData &rhs) const
Static Public Member Functions
static bool is_either_profiled (const InlineData &data1, const InlineData &data2)
Static Public Attributes
static constexpr cordz_info_t kNullCordzInfo = LittleEndianByte(1)
static constexpr size_t kTagOffset = 0
Friends
bool operator== (const InlineData &lhs, const InlineData &rhs)
bool operator!= (const InlineData &lhs, const InlineData &rhs)
Detailed Description
Definition at line 504 of file cord_internal.h.
Member Enumeration Documentation
DefaultInitType
enum absl::cord_internal::InlineData::DefaultInitType
Enumerator
kDefaultInit
Definition at line 507 of file cord_internal.h.
{ kDefaultInit };
Constructor & Destructor Documentation
InlineData() [1/5]
absl::cord_internal::InlineData::InlineData () inline constexpr noexcept
Definition at line 527 of file cord_internal.h.
{ poison_this(); }
References poison_this().
InlineData() [2/5]
absl::cord_internal::InlineData::InlineData (DefaultInitType) inline explicit noexcept
Definition at line 529 of file cord_internal.h.
                                                : rep_(kDefaultInit) {
    poison_this();
  }
References poison_this().
InlineData() [3/5]
absl::cord_internal::InlineData::InlineData (CordRep * rep) inline explicit noexcept
Definition at line 533 of file cord_internal.h.
                                             : rep_(rep) {
    ABSL_ASSERT(rep != nullptr);
  }
References ABSL_ASSERT, and rep.
InlineData() [4/5]
absl::cord_internal::InlineData::InlineData (absl::string_view sv, CordRep * rep) inline constexpr noexcept
Definition at line 540 of file cord_internal.h.
      : rep_(rep ? Rep(rep) : Rep(sv)) {
    poison();
  }
References poison().
InlineData() [5/5]
absl::cord_internal::InlineData::InlineData (const InlineData & rhs) constexpr default noexcept
Member Function Documentation
as_chars() [1/2]
char * absl::cord_internal::InlineData::as_chars () inline
Definition at line 644 of file cord_internal.h.
{ return rep_.as_chars(); }
as_chars() [2/2]
const char * absl::cord_internal::InlineData::as_chars () const inline
Definition at line 624 of file cord_internal.h.
{
    assert(!is_tree());
    return rep_.as_chars();
  }
References is_tree().
Referenced by absl::Cord::Subcord().
as_tree()
CordRep * absl::cord_internal::InlineData::as_tree () const inline
Definition at line 648 of file cord_internal.h.
{
    assert(is_tree());
    return rep_.tree();
  }
References is_tree().
Referenced by absl::cord_internal::CordzInfo::TrackCord(), and absl::cord_internal::CordzInfo::TrackCord().
clear_cordz_info()
void absl::cord_internal::InlineData::clear_cordz_info () inline
Definition at line 617 of file cord_internal.h.
{
    assert(is_tree());
    rep_.set_cordz_info(kNullCordzInfo);
  }
References is_tree(), and kNullCordzInfo.
Compare()
int absl::cord_internal::InlineData::Compare (const InlineData & rhs) const inline
Definition at line 700 of file cord_internal.h.
{
    return Compare(rep_.SanitizerSafeCopy(), rhs.rep_.SanitizerSafeCopy());
  }
References Compare().
Referenced by Compare().
copy_max_inline_to()
void absl::cord_internal::InlineData::copy_max_inline_to (char * dst) const inline
Definition at line 661 of file cord_internal.h.
{
    assert(!is_tree());
    memcpy(dst, rep_.SanitizerSafeCopy().as_chars(), kMaxInline);
  }
References is_tree(), and absl::cord_internal::kMaxInline.
cordz_info()
CordzInfo * absl::cord_internal::InlineData::cordz_info () const inline
Definition at line 598 of file cord_internal.h.
{
    assert(is_tree());
    intptr_t info = static_cast<intptr_t>(absl::little_endian::ToHost64(
        static_cast<uint64_t>(rep_.cordz_info())));
    assert(info & 1);
    return reinterpret_cast<CordzInfo*>(info - 1);
  }
References is_tree().
Referenced by set_cordz_info(), and absl::cord_internal::CordzInfo::TrackCord().
inline_size()
size_t absl::cord_internal::InlineData::inline_size () const inline
Definition at line 683 of file cord_internal.h.
{ return rep_.inline_size(); }
is_either_profiled()
static bool absl::cord_internal::InlineData::is_either_profiled (const InlineData & data1, const InlineData & data2) inline static
Definition at line 588 of file cord_internal.h.
{
    assert(data1.is_tree() && data2.is_tree());
    return (data1.rep_.cordz_info() | data2.rep_.cordz_info()) !=
           kNullCordzInfo;
  }
References is_tree(), and kNullCordzInfo.
Referenced by absl::cord_internal::CordzInfo::MaybeTrackCord().
is_empty()
bool absl::cord_internal::InlineData::is_empty () const inline
Definition at line 573 of file cord_internal.h.
{ return rep_.tag() == 0; }
is_profiled()
bool absl::cord_internal::InlineData::is_profiled () const inline
Definition at line 580 of file cord_internal.h.
{
    assert(is_tree());
    return rep_.cordz_info() != kNullCordzInfo;
  }
References is_tree(), and kNullCordzInfo.
Referenced by absl::cord_internal::CordzInfo::TrackCord().
is_tree()
bool absl::cord_internal::InlineData::is_tree () const inline
Definition at line 576 of file cord_internal.h.
{ return (rep_.tag() & 1) != 0; }
Referenced by as_chars(), as_tree(), clear_cordz_info(), copy_max_inline_to(), cordz_info(), is_either_profiled(), is_profiled(), set_cordz_info(), set_tree(), absl::cord_internal::CordzInfo::TrackCord(), and absl::cord_internal::CordzInfo::TrackCord().
make_tree()
void absl::cord_internal::InlineData::make_tree (CordRep * rep) inline
Definition at line 668 of file cord_internal.h.
{
    unpoison();
    rep_.make_tree(rep);
  }
References rep, and unpoison().
operator=()
InlineData & absl::cord_internal::InlineData::operator= (const InlineData & rhs) inline default noexcept
poison()
void absl::cord_internal::InlineData::poison () constexpr
Definition at line 866 of file cord_internal.h.
{}
Referenced by InlineData(), set_inline_data(), and set_inline_size().
poison_this()
void absl::cord_internal::InlineData::poison_this () constexpr
Definition at line 864 of file cord_internal.h.
{}
Referenced by InlineData(), and InlineData().
set_cordz_info()
void absl::cord_internal::InlineData::set_cordz_info (CordzInfo * cordz_info) inline
Definition at line 609 of file cord_internal.h.
{
    assert(is_tree());
    uintptr_t info = reinterpret_cast<uintptr_t>(cordz_info) | 1;
    rep_.set_cordz_info(
        static_cast<cordz_info_t>(absl::little_endian::FromHost64(info)));
  }
References cordz_info(), and is_tree().
Referenced by absl::cord_internal::CordzInfo::TrackCord(), and absl::cord_internal::CordzInfo::TrackCord().
set_inline_data()
void absl::cord_internal::InlineData::set_inline_data (const char * data, size_t n) inline
Definition at line 653 of file cord_internal.h.
{
    ABSL_ASSERT(n <= kMaxInline);
    unpoison();
    rep_.set_tag(static_cast<int8_t>(n << 1));
    SmallMemmove<true>(rep_.as_chars(), data, n);
    poison();
  }
References ABSL_ASSERT, absl::cord_internal::kMaxInline, absl::n, poison(), absl::cord_internal::SmallMemmove(), and unpoison().
set_inline_size()
void absl::cord_internal::InlineData::set_inline_size (size_t size) inline
Definition at line 688 of file cord_internal.h.
{
    unpoison();
    rep_.set_inline_size(size);
    poison();
  }
References poison(), size, and unpoison().
set_tree()
void absl::cord_internal::InlineData::set_tree (CordRep * rep) inline
Definition at line 676 of file cord_internal.h.
{
    assert(is_tree());
    rep_.set_tree(rep);
  }
References is_tree(), and rep.
unpoison()
void absl::cord_internal::InlineData::unpoison () constexpr
Definition at line 865 of file cord_internal.h.
{}
Referenced by make_tree(), set_inline_data(), and set_inline_size().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const InlineData & lhs, const InlineData & rhs) friend
Definition at line 557 of file cord_internal.h.
{
    return !operator==(lhs, rhs);
  }
operator==
bool operator== (const InlineData & lhs, const InlineData & rhs) friend
Definition at line 548 of file cord_internal.h.
{
#ifdef ABSL_INTERNAL_CORD_HAVE_SANITIZER
    const Rep l = lhs.rep_.SanitizerSafeCopy();
    const Rep r = rhs.rep_.SanitizerSafeCopy();
    return memcmp(&l, &r, sizeof(l)) == 0;
#else
    return memcmp(&lhs, &rhs, sizeof(lhs)) == 0;
#endif
  }
Member Data Documentation
kNullCordzInfo
cordz_info_t absl::cord_internal::InlineData::kNullCordzInfo = LittleEndianByte(1) static constexpr
Definition at line 513 of file cord_internal.h.
Referenced by clear_cordz_info(), is_either_profiled(), and is_profiled().
kTagOffset
size_t absl::cord_internal::InlineData::kTagOffset = 0 static constexpr
Definition at line 518 of file cord_internal.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/cord_internal.h