open spiel: open_spiel::morpion_solitaire::MorpionState Class Reference
open_spiel::morpion_solitaire::MorpionState Class Reference
#include <morpion_solitaire.h>
Public Member Functions
MorpionState (const MorpionState &)=default
MorpionState (std::shared_ptr< const Game > game)
MorpionState & operator= (const MorpionState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
std::string ObservationString (Player player) const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
void UndoAction (Player player, Action move) override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void getAllValidMoves () const
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 96 of file morpion_solitaire.h.
Constructor & Destructor Documentation
MorpionState() [1/2]
open_spiel::morpion_solitaire::MorpionState::MorpionState (const MorpionState &) default
Referenced by Clone().
MorpionState() [2/2]
open_spiel::morpion_solitaire::MorpionState::MorpionState (std::shared_ptr< const Game > game) explicit
Definition at line 229 of file morpion_solitaire.cc.
                                                         : State(game) {
  // Initialize 4D starting points and find all possible lines on the board
  for (int i = 0; i < kNumRows; i++) {
    for (int j = 0; j < kNumCols; j++) {
      // Initialize starting points on board
      if ((i == 3 || i == 9) && j > 4 && j < 8) {
        board_[j + (i * kNumRows)] = 1;
      }
      if ((i == 4 || i == 8) && (j == 5 || j == 7)) {
        board_[j + (i * kNumRows)] = 1;
      }
      if ((i == 5 || i == 7) && ((j > 2 && j < 6) || (j > 6 && j < 10))) {
        board_[j + (i * kNumRows)] = 1;
      }
      if (i == 6 && ((j == 3) || (j == 9))) {
        board_[j + (i * kNumRows)] = 1;
      }
      // Get all possible lines on board (460)
      if (j + 3 < kNumCols) {
        all_lines_.emplace_back(Point(i, j), Point(i, j + 3));
      }
      if ((j + 3 < kNumCols) && (i + 3 < kNumRows)) {
        all_lines_.emplace_back(Point(i, j), Point(i + 3, j + 3));
      }
      if (i + 3 < kNumRows) {
        all_lines_.emplace_back(Point(i, j), Point(i + 3, j));
      }
      if ((j >= 3) && (i + 3 < kNumRows)) {
        all_lines_.emplace_back(Point(i, j), Point(i + 3, j - 3));
      }
    }
  }
  // For each line, store in a map of action # -> line object.
  for (Line& line : all_lines_) {
    action_map_[line.GetAction()] = &line;
  }
}
References i, open_spiel::morpion_solitaire::kNumCols, and open_spiel::morpion_solitaire::kNumRows.
Member Function Documentation
ActionToString()
std::string open_spiel::morpion_solitaire::MorpionState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 219 of file morpion_solitaire.cc.
{
  Line move = *action_map_.at(action_id);
  std::string action_str;
  for (Point p : move.GetAllPoints()) {
    absl::StrAppend(&action_str, p.ToString(), " ");
  }
  return action_str;
}
References absl::StrAppend().
Clone()
std::unique_ptr< State > open_spiel::morpion_solitaire::MorpionState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 343 of file morpion_solitaire.cc.
{
  return std::unique_ptr<State>(new MorpionState(*this));
}
References MorpionState().
CurrentPlayer()
Player open_spiel::morpion_solitaire::MorpionState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 105 of file morpion_solitaire.h.
{
    return IsTerminal() ? kTerminalPlayerId : kDefaultPlayerId;
  }
References IsTerminal(), open_spiel::kDefaultPlayerId, and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::morpion_solitaire::MorpionState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 192 of file morpion_solitaire.cc.
{
  Line newMove = *action_map_.at(move);
  Point newPoint;
  int pos;
  for (Point p : newMove.GetAllPoints()) {
    pos = p.y + (p.x * kNumRows);
    if (board_[pos] == 0) {
      board_[pos] = 1;
      newPoint = p;
      break;
    }
  }
  move_history_.emplace_back(newMove, newPoint);
  num_moves_ += 1;
  current_returns_ += 1;
}
References open_spiel::morpion_solitaire::Line::GetAllPoints(), and open_spiel::morpion_solitaire::kNumRows.
getAllValidMoves()
void open_spiel::morpion_solitaire::MorpionState::getAllValidMoves () const protected
Definition at line 268 of file morpion_solitaire.cc.
{
  current_valid_moves_.clear();
  for (Line l : all_lines_) {
    // Check that exactly one point is empty.
    int count = 0;
    for (Point p : l.GetAllPoints()) {
      if (board_[p.y + (p.x * kNumRows)] == 1) {
        count++;
      }
    }
    if (count != 3) {
      continue;
    }
    // Check that line does not overlap any existing moves / lines.
    bool overlaps = false;
    for (const std::pair<Line, Point>& m : move_history_) {
      overlaps = l.CheckOverlap(m.first);
      if (overlaps) {
        break;
      }
    }
    if (overlaps) {
      continue;
    }
    current_valid_moves_.push_back(l);
  }
}
Referenced by IsTerminal().
InformationStateString()
std::string open_spiel::morpion_solitaire::MorpionState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 311 of file morpion_solitaire.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::morpion_solitaire::MorpionState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 296 of file morpion_solitaire.cc.
{
  getAllValidMoves();
  return current_valid_moves_.empty();
}
References getAllValidMoves().
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::morpion_solitaire::MorpionState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 209 of file morpion_solitaire.cc.
{
  if (IsTerminal()) return {};
  std::vector<Action> moves;
  for (Line move : current_valid_moves_) {
    moves.push_back(move.GetAction());
  }
  sort(moves.begin(), moves.end());
  return moves;
}
References IsTerminal().
ObservationString()
std::string open_spiel::morpion_solitaire::MorpionState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 328 of file morpion_solitaire.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
operator=()
MorpionState & open_spiel::morpion_solitaire::MorpionState::operator= (const MorpionState &) default
Returns()
std::vector< double > open_spiel::morpion_solitaire::MorpionState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 309 of file morpion_solitaire.cc.
{ return {current_returns_}; }
Rewards()
std::vector< double > open_spiel::morpion_solitaire::MorpionState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 301 of file morpion_solitaire.cc.
{
  if (move_number_ == 0) {
    return {0.0};
  } else {
    return {1.0};
  }
}
References open_spiel::State::move_number_.
ToString()
std::string open_spiel::morpion_solitaire::MorpionState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 317 of file morpion_solitaire.cc.
{
  std::string str;
  for (int i = 0; i < kNumRows; i++) {
    for (int j = 0; j < kNumCols; j++) {
      absl::StrAppend(&str, board_[i * kNumRows + j]);
    }
    absl::StrAppend(&str, "\n");
  }
  return str;
}
References i, open_spiel::morpion_solitaire::kNumCols, open_spiel::morpion_solitaire::kNumRows, and absl::StrAppend().
Referenced by ObservationString().
UndoAction()
void open_spiel::morpion_solitaire::MorpionState::UndoAction (Player player, Action move) override virtual
Reimplemented from open_spiel::State.
Definition at line 334 of file morpion_solitaire.cc.
{
  std::pair<Line, Point> last_move = move_history_.back();
  board_[last_move.second.x * kNumRows + last_move.second.y] = 0;
  move_history_.pop_back();
  num_moves_ -= 1;
  history_.pop_back();
  --move_number_;
}
References open_spiel::State::history_, and open_spiel::State::move_number_.
The documentation for this class was generated from the following files:
open_spiel/games/morpion_solitaire/morpion_solitaire.h
open_spiel/games/morpion_solitaire/morpion_solitaire.cc