open spiel: open_spiel::GameRegisterer Class Reference
open_spiel::GameRegisterer Class Reference
#include <spiel.h>
Public Types
using CreateFunc
Public Member Functions
GameRegisterer (const GameType &game_type, CreateFunc creator)
Static Public Member Functions
static std::shared_ptr< const Game > CreateByName (const std::string &short_name, const GameParameters &params)
static std::vector< std::string > GamesWithKnownIssues ()
static std::vector< std::string > RegisteredNames ()
static std::vector< GameType > RegisteredGames ()
static bool IsValidName (const std::string &short_name)
static void RegisterGame (const GameType &game_type, CreateFunc creator)
Detailed Description
Definition at line 1049 of file spiel.h.
Member Typedef Documentation
CreateFunc
using open_spiel::GameRegisterer::CreateFunc
Initial value:
      std::function<std::shared_ptr<const Game>(const GameParameters& params)>
Definition at line 1051 of file spiel.h.
Constructor & Destructor Documentation
GameRegisterer()
open_spiel::GameRegisterer::GameRegisterer (const GameType & game_type, CreateFunc creator)
Definition at line 139 of file spiel.cc.
{
  RegisterGame(game_type, creator);
}
References RegisterGame().
Member Function Documentation
CreateByName()
std::shared_ptr< const Game > open_spiel::GameRegisterer::CreateByName (const std::string & short_name, const GameParameters & params) static
Definition at line 143 of file spiel.cc.
{
  // Check if it's a game with a known issue. If so, output a warning.
  if (absl::c_linear_search(GamesWithKnownIssues(), short_name)) {
    std::cerr << "Warning! This game has known issues. Please see the games "
              << "list on github or the code for details." << std::endl;
  }
  // Find the factory for this game and load it.
  auto iter = factories().find(short_name);
  if (iter == factories().end()) {
    SpielFatalError(absl::StrCat("Unknown game '", short_name,
                                 "'. Available games are:\n",
                                 absl::StrJoin(RegisteredNames(), "\n")));
  } else {
    ValidateParams(params, iter->second.first.parameter_specification);
    return (iter->second.second)(params);
  }
}
References GamesWithKnownIssues(), RegisteredNames(), and open_spiel::SpielFatalError().
Referenced by open_spiel::LoadGame(), and open_spiel::LoadGame().
GamesWithKnownIssues()
std::vector< std::string > open_spiel::GameRegisterer::GamesWithKnownIssues () static
Definition at line 172 of file spiel.cc.
{
  return {"quoridor", "rbc"};
}
Referenced by CreateByName().
IsValidName()
bool open_spiel::GameRegisterer::IsValidName (const std::string & short_name) static
Definition at line 184 of file spiel.cc.
{
  return factories().find(short_name) != factories().end();
}
Referenced by open_spiel::IsGameRegistered().
RegisteredGames()
std::vector< GameType > open_spiel::GameRegisterer::RegisteredGames () static
Definition at line 176 of file spiel.cc.
{
  std::vector<GameType> games;
  for (const auto& key_val : factories()) {
    games.push_back(key_val.second.first);
  }
  return games;
}
Referenced by open_spiel::RegisteredGameTypes().
RegisteredNames()
std::vector< std::string > open_spiel::GameRegisterer::RegisteredNames () static
Definition at line 164 of file spiel.cc.
{
  std::vector<std::string> names;
  for (const auto& key_val : factories()) {
    names.push_back(key_val.first);
  }
  return names;
}
Referenced by CreateByName(), and open_spiel::RegisteredGames().
RegisterGame()
void open_spiel::GameRegisterer::RegisterGame (const GameType & game_type, GameRegisterer::CreateFunc creator) static
Definition at line 188 of file spiel.cc.
{
  factories()[game_type.short_name] = std::make_pair(game_type, creator);
}
References open_spiel::GameType::short_name.
Referenced by GameRegisterer().
The documentation for this class was generated from the following files:
open_spiel/spiel.h
open_spiel/spiel.cc