open spiel: absl::time_internal::cctz::detail::civil_time< T > Class Template Reference
absl::time_internal::cctz::detail::civil_time< T > Class Template Reference
#include <civil_time_detail.h>
Public Types
template<typename U , typename S >
using preserves_data
Public Member Functions
CONSTEXPR_M civil_time (year_t y, diff_t m=1, diff_t d=1, diff_t hh=0, diff_t mm=0, diff_t ss=0) noexcept
CONSTEXPR_M civil_time () noexcept
civil_time (const civil_time &)=default
civil_time & operator= (const civil_time &)=default
template<typename U >
CONSTEXPR_M civil_time (const civil_time< U > &ct, preserves_data< T, U > *=nullptr) noexcept
template<typename U >
CONSTEXPR_M civil_time (const civil_time< U > &ct, preserves_data< U, T > *=nullptr) noexcept
CONSTEXPR_M year_t year () const noexcept
CONSTEXPR_M int month () const noexcept
CONSTEXPR_M int day () const noexcept
CONSTEXPR_M int hour () const noexcept
CONSTEXPR_M int minute () const noexcept
CONSTEXPR_M int second () const noexcept
CONSTEXPR_M civil_time & operator+= (diff_t n) noexcept
CONSTEXPR_M civil_time & operator-= (diff_t n) noexcept
CONSTEXPR_M civil_time & operator++ () noexcept
CONSTEXPR_M civil_time operator++ (int) noexcept
CONSTEXPR_M civil_time & operator-- () noexcept
CONSTEXPR_M civil_time operator-- (int) noexcept
Static Public Member Functions
static CONSTEXPR_F civil_time max ()
static CONSTEXPR_F civil_time min ()
Friends
template<typename U >
class civil_time
CONSTEXPR_F civil_time operator+ (civil_time a, diff_t n) noexcept
CONSTEXPR_F civil_time operator+ (diff_t n, civil_time a) noexcept
CONSTEXPR_F civil_time operator- (civil_time a, diff_t n) noexcept
CONSTEXPR_F diff_t operator- (civil_time lhs, civil_time rhs) noexcept
template<typename H >
H AbslHashValue (H h, civil_time a)
Detailed Description
template<typename T>
class absl::time_internal::cctz::detail::civil_time< T >
Definition at line 376 of file civil_time_detail.h.
Member Typedef Documentation
preserves_data
template<typename T > template<typename U , typename S > using absl::time_internal::cctz::detail::civil_time< T >::preserves_data
Initial value:
      typename std::enable_if<std::is_base_of<U, S>::value>::type
Definition at line 392 of file civil_time_detail.h.
Constructor & Destructor Documentation
civil_time() [1/5]
template<typename T > CONSTEXPR_M absl::time_internal::cctz::detail::civil_time< T >::civil_time (year_t y, diff_t m = 1, diff_t d = 1, diff_t hh = 0, diff_t mm = 0, diff_t ss = 0) inline explicit noexcept
Definition at line 378 of file civil_time_detail.h.
      : civil_time(impl::n_sec(y, m, d, hh, mm, ss)) {}
civil_time() [2/5]
template<typename T > CONSTEXPR_M absl::time_internal::cctz::detail::civil_time< T >::civil_time () inline noexcept
Definition at line 383 of file civil_time_detail.h.
: f_{1970, 1, 1, 0, 0, 0} {}
civil_time() [3/5]
template<typename T > absl::time_internal::cctz::detail::civil_time< T >::civil_time (const civil_time< T > &) default
civil_time() [4/5]
template<typename T > template<typename U > CONSTEXPR_M absl::time_internal::cctz::detail::civil_time< T >::civil_time (const civil_time< U > & ct, preserves_data< T, U > * = nullptr) inline noexcept
Definition at line 395 of file civil_time_detail.h.
      : civil_time(ct.f_) {}
civil_time() [5/5]
template<typename T > template<typename U > CONSTEXPR_M absl::time_internal::cctz::detail::civil_time< T >::civil_time (const civil_time< U > & ct, preserves_data< U, T > * = nullptr) inline explicit noexcept
Definition at line 399 of file civil_time_detail.h.
      : civil_time(ct.f_) {}
Member Function Documentation
day()
template<typename T > CONSTEXPR_M int absl::time_internal::cctz::detail::civil_time< T >::day () const inline noexcept
Definition at line 416 of file civil_time_detail.h.
{ return f_.d; }
References absl::time_internal::cctz::detail::fields::d.
Referenced by absl::ConvertDateTime(), absl::time_internal::cctz::detail::format(), absl::log_internal::FormatLogMessage(), absl::ABSL_NAMESPACE_BEGIN::FormatYearAnd(), absl::time_internal::cctz::detail::parse(), absl::time_internal::cctz::TEST(), absl::time_internal::cctz::TEST(), and absl::time_internal::cctz::TEST().
hour()
template<typename T > CONSTEXPR_M int absl::time_internal::cctz::detail::civil_time< T >::hour () const inline noexcept
Definition at line 417 of file civil_time_detail.h.
{ return f_.hh; }
References absl::time_internal::cctz::detail::fields::hh.
Referenced by absl::ConvertDateTime(), absl::time_internal::cctz::detail::format(), absl::log_internal::FormatLogMessage(), absl::ABSL_NAMESPACE_BEGIN::FormatYearAnd(), and absl::time_internal::cctz::TEST().
max()
template<typename T > static CONSTEXPR_F civil_time absl::time_internal::cctz::detail::civil_time< T >::max () inline static
Definition at line 404 of file civil_time_detail.h.
{
    const auto max_year = (std::numeric_limits<std::int_least64_t>::max)();
    return civil_time(max_year, 12, 31, 23, 59, 59);
  }
References absl::time_internal::cctz::detail::civil_time< T >::civil_time.
Referenced by absl::time_internal::cctz::TimeZoneLibC::BreakTime(), absl::time_internal::cctz::detail::parse(), and absl::time_internal::cctz::TEST().
min()
template<typename T > static CONSTEXPR_F civil_time absl::time_internal::cctz::detail::civil_time< T >::min () inline static
Definition at line 408 of file civil_time_detail.h.
{
    const auto min_year = (std::numeric_limits<std::int_least64_t>::min)();
    return civil_time(min_year, 1, 1, 0, 0, 0);
  }
References absl::time_internal::cctz::detail::civil_time< T >::civil_time.
Referenced by absl::time_internal::cctz::TimeZoneLibC::BreakTime(), absl::time_internal::cctz::detail::parse(), and absl::time_internal::cctz::TEST().
minute()
template<typename T > CONSTEXPR_M int absl::time_internal::cctz::detail::civil_time< T >::minute () const inline noexcept
Definition at line 418 of file civil_time_detail.h.
{ return f_.mm; }
References absl::time_internal::cctz::detail::fields::mm.
Referenced by absl::ConvertDateTime(), absl::time_internal::cctz::detail::format(), absl::log_internal::FormatLogMessage(), absl::ABSL_NAMESPACE_BEGIN::FormatYearAnd(), absl::time_internal::cctz::detail::operator<<(), and absl::time_internal::cctz::TEST().
month()
template<typename T > CONSTEXPR_M int absl::time_internal::cctz::detail::civil_time< T >::month () const inline noexcept
Definition at line 415 of file civil_time_detail.h.
{ return f_.m; }
References absl::time_internal::cctz::detail::fields::m.
Referenced by absl::ConvertDateTime(), absl::time_internal::cctz::detail::format(), absl::log_internal::FormatLogMessage(), absl::ABSL_NAMESPACE_BEGIN::FormatYearAnd(), absl::time_internal::cctz::detail::operator<<(), absl::time_internal::cctz::detail::parse(), absl::time_internal::cctz::TEST(), and absl::time_internal::cctz::TEST().
operator++() [1/2]
template<typename T > CONSTEXPR_M civil_time & absl::time_internal::cctz::detail::civil_time< T >::operator++ () inline noexcept
Definition at line 428 of file civil_time_detail.h.
{ return *this += 1; }
operator++() [2/2]
template<typename T > CONSTEXPR_M civil_time absl::time_internal::cctz::detail::civil_time< T >::operator++ (int) inline noexcept
Definition at line 429 of file civil_time_detail.h.
{
    const civil_time a = *this;
    ++*this;
    return a;
  }
References absl::a.
operator+=()
template<typename T > CONSTEXPR_M civil_time & absl::time_internal::cctz::detail::civil_time< T >::operator+= (diff_t n) inline noexcept
Definition at line 422 of file civil_time_detail.h.
{
    return *this = *this + n;
  }
References absl::n.
operator--() [1/2]
template<typename T > CONSTEXPR_M civil_time & absl::time_internal::cctz::detail::civil_time< T >::operator-- () inline noexcept
Definition at line 434 of file civil_time_detail.h.
{ return *this -= 1; }
operator--() [2/2]
template<typename T > CONSTEXPR_M civil_time absl::time_internal::cctz::detail::civil_time< T >::operator-- (int) inline noexcept
Definition at line 435 of file civil_time_detail.h.
{
    const civil_time a = *this;
    --*this;
    return a;
  }
References absl::a.
operator-=()
template<typename T > CONSTEXPR_M civil_time & absl::time_internal::cctz::detail::civil_time< T >::operator-= (diff_t n) inline noexcept
Definition at line 425 of file civil_time_detail.h.
{
    return *this = *this - n;
  }
References absl::n.
operator=()
template<typename T > civil_time & absl::time_internal::cctz::detail::civil_time< T >::operator= (const civil_time< T > &) default
second()
template<typename T > CONSTEXPR_M int absl::time_internal::cctz::detail::civil_time< T >::second () const inline noexcept
Definition at line 419 of file civil_time_detail.h.
{ return f_.ss; }
References absl::time_internal::cctz::detail::fields::ss.
Referenced by absl::ConvertDateTime(), absl::time_internal::cctz::detail::format(), absl::log_internal::FormatLogMessage(), absl::ABSL_NAMESPACE_BEGIN::FormatYearAnd(), and absl::time_internal::cctz::TEST().
year()
template<typename T > CONSTEXPR_M year_t absl::time_internal::cctz::detail::civil_time< T >::year () const inline noexcept
Definition at line 414 of file civil_time_detail.h.
{ return f_.y; }
References absl::time_internal::cctz::detail::fields::y.
Referenced by absl::ConvertDateTime(), absl::time_internal::cctz::detail::format(), absl::ABSL_NAMESPACE_BEGIN::FormatYearAnd(), absl::time_internal::cctz::TimeZoneInfo::MakeTime(), absl::time_internal::cctz::TimeZoneLibC::MakeTime(), absl::time_internal::cctz::detail::operator==(), absl::time_internal::cctz::TEST(), and absl::time_internal::cctz::TEST().
Friends And Related Symbol Documentation
AbslHashValue
template<typename T > template<typename H > H AbslHashValue (H h, civil_time< T > a) friend
Definition at line 458 of file civil_time_detail.h.
{
    return impl::AbslHashValueImpl(T{}, std::move(h), a.f_);
  }
civil_time
template<typename T > template<typename U > friend class civil_time friend
Definition at line 466 of file civil_time_detail.h.
Referenced by absl::time_internal::cctz::detail::civil_time< T >::max(), and absl::time_internal::cctz::detail::civil_time< T >::min().
operator+ [1/2]
template<typename T > CONSTEXPR_F civil_time operator+ (civil_time< T > a, diff_t n) friend
Definition at line 442 of file civil_time_detail.h.
{
    return civil_time(step(T{}, a.f_, n));
  }
operator+ [2/2]
template<typename T > CONSTEXPR_F civil_time operator+ (diff_t n, civil_time< T > a) friend
Definition at line 445 of file civil_time_detail.h.
{
    return a + n;
  }
operator- [1/2]
template<typename T > CONSTEXPR_F civil_time operator- (civil_time< T > a, diff_t n) friend
Definition at line 448 of file civil_time_detail.h.
{
    return n != (std::numeric_limits<diff_t>::min)()
               ? civil_time(step(T{}, a.f_, -n))
               : civil_time(step(T{}, step(T{}, a.f_, -(n + 1)), 1));
  }
operator- [2/2]
template<typename T > CONSTEXPR_F diff_t operator- (civil_time< T > lhs, civil_time< T > rhs) friend
Definition at line 453 of file civil_time_detail.h.
{
    return difference(T{}, lhs.f_, rhs.f_);
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/time/internal/cctz/include/cctz/civil_time_detail.h