open spiel: open_spiel::BotRegisterer Class Reference
open_spiel::BotRegisterer Class Reference
#include <spiel_bots.h>
Public Member Functions
BotRegisterer (const std::string &bot_name, std::unique_ptr< BotFactory > factory)
Static Public Member Functions
static std::unique_ptr< Bot > CreateByName (const std::string &bot_name, std::shared_ptr< const Game > game, Player player_id, const GameParameters &params)
static std::vector< std::string > BotsThatCanPlayGame (const Game &game, Player player_id)
static std::vector< std::string > BotsThatCanPlayGame (const Game &game)
static std::vector< std::string > RegisteredBots ()
static bool IsBotRegistered (const std::string &bot_name)
static void RegisterBot (const std::string &bot_name, std::unique_ptr< BotFactory > factory)
Detailed Description
Definition at line 214 of file spiel_bots.h.
Constructor & Destructor Documentation
BotRegisterer()
open_spiel::BotRegisterer::BotRegisterer (const std::string & bot_name, std::unique_ptr< BotFactory > factory)
Definition at line 282 of file spiel_bots.cc.
{
  RegisterBot(bot_name, std::move(factory));
}
References RegisterBot().
Member Function Documentation
BotsThatCanPlayGame() [1/2]
std::vector< std::string > open_spiel::BotRegisterer::BotsThatCanPlayGame (const Game & game) static
Definition at line 313 of file spiel_bots.cc.
{
  std::vector<std::string> bot_names;
  for (const auto& key_val : factories()) {
    bool can_play_for_all = true;
    for (int player_id = 0; player_id < game.NumPlayers(); ++player_id) {
      if (!key_val.second->CanPlayGame(game, player_id)) {
        can_play_for_all = false;
        break;
      }
    }
    if (can_play_for_all) bot_names.push_back(key_val.first);
  }
  return bot_names;
}
BotsThatCanPlayGame() [2/2]
std::vector< std::string > open_spiel::BotRegisterer::BotsThatCanPlayGame (const Game & game, Player player_id) static
Definition at line 302 of file spiel_bots.cc.
{
  std::vector<std::string> bot_names;
  for (const auto& key_val : factories()) {
    if (key_val.second->CanPlayGame(game, player_id)) {
      bot_names.push_back(key_val.first);
    }
  }
  return bot_names;
}
Referenced by open_spiel::BotsThatCanPlayGame(), and open_spiel::BotsThatCanPlayGame().
CreateByName()
std::unique_ptr< Bot > open_spiel::BotRegisterer::CreateByName (const std::string & bot_name, std::shared_ptr< const Game > game, Player player_id, const GameParameters & params) static
Definition at line 287 of file spiel_bots.cc.
{
  auto iter = factories().find(bot_name);
  if (iter == factories().end()) {
    SpielFatalError(absl::StrCat("Unknown bot '", bot_name,
                                 "'. Available bots are:\n",
                                 absl::StrJoin(RegisteredBots(), "\n")));
  } else {
    const std::unique_ptr<BotFactory>& factory = iter->second;
    return factory->Create(std::move(game), player_id, params);
  }
}
References end, RegisteredBots(), open_spiel::SpielFatalError(), absl::StrCat(), and absl::StrJoin().
Referenced by open_spiel::LoadBot().
IsBotRegistered()
bool open_spiel::BotRegisterer::IsBotRegistered (const std::string & bot_name) static
Definition at line 343 of file spiel_bots.cc.
{
  return factories().find(bot_name) != factories().end();
}
Referenced by open_spiel::IsBotRegistered().
RegisterBot()
void open_spiel::BotRegisterer::RegisterBot (const std::string & bot_name, std::unique_ptr< BotFactory > factory) static
Definition at line 328 of file spiel_bots.cc.
{
  factories()[bot_name] = std::move(factory);
}
Referenced by BotRegisterer().
RegisteredBots()
std::vector< std::string > open_spiel::BotRegisterer::RegisteredBots () static
Definition at line 333 of file spiel_bots.cc.
{
  std::vector<std::string> names;
  for (const auto& key_val : factories()) names.push_back(key_val.first);
  return names;
}
Referenced by CreateByName(), and open_spiel::RegisteredBots().
The documentation for this class was generated from the following files:
open_spiel/spiel_bots.h
open_spiel/spiel_bots.cc