open spiel: open_spiel::tiny_hanabi::TinyHanabiState Class Reference
open_spiel::tiny_hanabi::TinyHanabiState Class Reference
#include <tiny_hanabi.h>
Public Member Functions
TinyHanabiState (const TinyHanabiState &)=default
TinyHanabiState (std::shared_ptr< const Game > game, TinyHanabiPayoffMatrix payoff)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 104 of file tiny_hanabi.h.
Constructor & Destructor Documentation
TinyHanabiState() [1/2]
open_spiel::tiny_hanabi::TinyHanabiState::TinyHanabiState (const TinyHanabiState &) default
Referenced by Clone().
TinyHanabiState() [2/2]
open_spiel::tiny_hanabi::TinyHanabiState::TinyHanabiState (std::shared_ptr< const Game > game, TinyHanabiPayoffMatrix payoff) inline
Definition at line 107 of file tiny_hanabi.h.
      : State(game), payoff_(payoff) {}
Member Function Documentation
ActionToString()
std::string open_spiel::tiny_hanabi::TinyHanabiState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 106 of file tiny_hanabi.cc.
{
  if (player == kChancePlayerId)
    return absl::StrCat("d", action);
  else
    return absl::StrCat("p", player, "a", action);
}
References action, open_spiel::kChancePlayerId, player, and absl::StrCat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::tiny_hanabi::TinyHanabiState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 114 of file tiny_hanabi.cc.
{
  if (!IsChanceNode()) return {};
  std::vector<std::pair<Action, double>> outcomes;
  const int num_outcomes = payoff_.NumChance();
  const double p = 1.0 / num_outcomes;
  outcomes.reserve(num_outcomes);
  for (int i = 0; i < num_outcomes; ++i) outcomes.emplace_back(i, p);
  return outcomes;
}
References i, open_spiel::State::IsChanceNode(), and open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumChance().
Clone()
std::unique_ptr< State > open_spiel::tiny_hanabi::TinyHanabiState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 145 of file tiny_hanabi.cc.
{
  return std::unique_ptr<State>(new TinyHanabiState(*this));
}
References TinyHanabiState().
CurrentPlayer()
Player open_spiel::tiny_hanabi::TinyHanabiState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 99 of file tiny_hanabi.cc.
{
  const int history_size = history_.size();
  if (history_size < num_players_) return kChancePlayerId;
  if (history_size == 2 * num_players_) return kTerminalPlayerId;
  return history_size - num_players_;
}
References open_spiel::State::history_, open_spiel::kChancePlayerId, open_spiel::kTerminalPlayerId, and open_spiel::State::num_players_.
InformationStateString()
std::string open_spiel::tiny_hanabi::TinyHanabiState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 157 of file tiny_hanabi.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string rv = absl::StrCat("p", player);
  if (history_.size() > player)
    absl::StrAppend(&rv, ":d", history_[player].action);
  for (int i = payoff_.NumPlayers(); i < history_.size(); ++i) {
    absl::StrAppend(&rv, " p", i - payoff_.NumPlayers(), ":a",
                    history_[i].action);
  }
  return rv;
}
References action, open_spiel::State::history_, i, open_spiel::State::num_players_, open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumPlayers(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and absl::StrCat().
InformationStateTensor()
void open_spiel::tiny_hanabi::TinyHanabiState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 171 of file tiny_hanabi.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), payoff_.NumChance() + payoff_.NumActions() *
                                                          payoff_.NumPlayers());
  std::fill(values.begin(), values.end(), 0);
  if (history_.size() > player) values.at(history_[player].action) = 1;
  for (int i = payoff_.NumPlayers(); i < history_.size(); ++i) {
    values.at(payoff_.NumChance() +
              (i - payoff_.NumPlayers()) * payoff_.NumActions() +
              history_[i].action) = 1;
  }
}
References action, open_spiel::State::history_, i, open_spiel::State::num_players_, open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumActions(), open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumChance(), open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumPlayers(), player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::tiny_hanabi::TinyHanabiState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 136 of file tiny_hanabi.cc.
{
  return history_.size() == 2 * num_players_;
}
References open_spiel::State::history_, and open_spiel::State::num_players_.
Referenced by LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::tiny_hanabi::TinyHanabiState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 149 of file tiny_hanabi.cc.
{
  if (IsTerminal()) return {};
  std::vector<Action> actions(IsChanceNode() ? payoff_.NumChance()
                                             : payoff_.NumActions());
  std::iota(actions.begin(), actions.end(), 0);
  return actions;
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumActions(), and open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumChance().
ObservationString()
std::string open_spiel::tiny_hanabi::TinyHanabiState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 195 of file tiny_hanabi.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return InformationStateString(player);
}
References open_spiel::State::InformationStateString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
ObservationTensor()
void open_spiel::tiny_hanabi::TinyHanabiState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 187 of file tiny_hanabi.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  InformationStateTensor(player, values);
}
References open_spiel::State::InformationStateTensor(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::tiny_hanabi::TinyHanabiState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 140 of file tiny_hanabi.cc.
{
  const double value = IsTerminal() ? payoff_(history_) : 0.0;
  return std::vector<double>(payoff_.NumPlayers(), value);
}
References open_spiel::State::history_, IsTerminal(), and open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumPlayers().
ToString()
std::string open_spiel::tiny_hanabi::TinyHanabiState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 124 of file tiny_hanabi.cc.
{
  std::string rv;
  for (int i = 0; i < payoff_.NumPlayers() && i < history_.size(); ++i) {
    if (i != 0) absl::StrAppend(&rv, " ");
    absl::StrAppend(&rv, "p", i, ":d", history_[i].action);
  }
  for (int i = payoff_.NumPlayers(); i < history_.size(); ++i) {
    absl::StrAppend(&rv, " p", history_[i].player, ":a", history_[i].action);
  }
  return rv;
}
References action, open_spiel::State::history_, i, open_spiel::tiny_hanabi::TinyHanabiPayoffMatrix::NumPlayers(), player, and absl::StrAppend().
The documentation for this class was generated from the following files:
open_spiel/games/tiny_hanabi/tiny_hanabi.h
open_spiel/games/tiny_hanabi/tiny_hanabi.cc