open spiel: open_spiel::algorithms::InfostateNode Class Reference
open_spiel::algorithms::InfostateNode Class Reference final
#include <infostate_tree.h>
Public Member Functions
const InfostateTree & tree () const
InfostateNode * parent () const
int incoming_index () const
const InfostateNodeType & type () const
size_t depth () const
bool is_root_node () const
bool has_infostate_string () const
const std::string & infostate_string () const
InfostateNode * child_at (int i) const
int num_children () const
VecWithUniquePtrsIterator< InfostateNode > child_iterator () const
const SequenceId sequence_id () const
const SequenceId start_sequence_id () const
const SequenceId end_sequence_id () const
Range< SequenceId > AllSequenceIds () const
const DecisionId decision_id () const
const std::vector< Action > & legal_actions () const
bool is_leaf_node () const
double terminal_utility () const
double terminal_chance_reach_prob () const
size_t corresponding_states_size () const
const std::vector< std::unique_ptr< State > > & corresponding_states () const
const std::vector< double > & corresponding_chance_reach_probs () const
const std::vector< Action > & TerminalHistory () const
std::ostream & operator<< (std::ostream &os) const
std::string MakeCertificate () const
Friends
class InfostateTree
Detailed Description
Definition at line 472 of file infostate_tree.h.
Member Function Documentation
AllSequenceIds()
Range< SequenceId > open_spiel::algorithms::InfostateNode::AllSequenceIds () const inline
Definition at line 583 of file infostate_tree.h.
{
    return Range<SequenceId>(start_sequence_id_.id(), end_sequence_id_.id(),
                             &tree_);
  }
References open_spiel::algorithms::internal::NodeId< Self >::id().
Referenced by open_spiel::algorithms::InfostateTree::BestResponse(), and open_spiel::algorithms::CheckSum().
child_at()
InfostateNode * open_spiel::algorithms::InfostateNode::child_at (int i) const inline
Definition at line 564 of file infostate_tree.h.
{ return children_.at(i).get(); }
References i.
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalPolicy().
child_iterator()
VecWithUniquePtrsIterator< InfostateNode > open_spiel::algorithms::InfostateNode::child_iterator () const inline
Definition at line 566 of file infostate_tree.h.
{
    return VecWithUniquePtrsIterator<InfostateNode>(children_);
  }
Referenced by open_spiel::algorithms::InfostateTree::DecisionIdsWithParentSeq(), open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyCfValuesConstraints(), and open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyReachProbsConstraints().
corresponding_chance_reach_probs()
const std::vector< double > & open_spiel::algorithms::InfostateNode::corresponding_chance_reach_probs () const inline
Definition at line 616 of file infostate_tree.h.
{
    SPIEL_CHECK_TRUE(is_leaf_node());
    return corresponding_ch_reaches_;
  }
References is_leaf_node(), and SPIEL_CHECK_TRUE.
corresponding_states()
const std::vector< std::unique_ptr< State > > & open_spiel::algorithms::InfostateNode::corresponding_states () const inline
Definition at line 612 of file infostate_tree.h.
{
    SPIEL_CHECK_TRUE(is_leaf_node());
    return corresponding_states_;
  }
References is_leaf_node(), and SPIEL_CHECK_TRUE.
corresponding_states_size()
size_t open_spiel::algorithms::InfostateNode::corresponding_states_size () const inline
Definition at line 609 of file infostate_tree.h.
{
    return corresponding_states_.size();
  }
decision_id()
const DecisionId open_spiel::algorithms::InfostateNode::decision_id () const inline
Definition at line 589 of file infostate_tree.h.
{
    SPIEL_CHECK_EQ(type_, kDecisionInfostateNode);
    SPIEL_CHECK_FALSE(decision_id_.is_undefined());
    return decision_id_;
  }
References open_spiel::algorithms::internal::NodeId< Self >::is_undefined(), open_spiel::algorithms::kDecisionInfostateNode, SPIEL_CHECK_EQ, and SPIEL_CHECK_FALSE.
Referenced by open_spiel::algorithms::InfostateTree::DecisionIdForSequence(), and open_spiel::algorithms::InfostateTree::DecisionIdsWithParentSeq().
depth()
size_t open_spiel::algorithms::InfostateNode::depth () const inline
Definition at line 551 of file infostate_tree.h.
{ return depth_; }
end_sequence_id()
const SequenceId open_spiel::algorithms::InfostateNode::end_sequence_id () const inline
Definition at line 579 of file infostate_tree.h.
{
    SPIEL_CHECK_FALSE(end_sequence_id_.is_undefined());
    return end_sequence_id_;
  }
References open_spiel::algorithms::internal::NodeId< Self >::is_undefined(), and SPIEL_CHECK_FALSE.
Referenced by open_spiel::algorithms::InfostateTree::BestResponse(), and open_spiel::algorithms::InfostateTree::IsLeafSequence().
has_infostate_string()
bool open_spiel::algorithms::InfostateNode::has_infostate_string () const inline
Definition at line 553 of file infostate_tree.h.
{
    return infostate_string_ != kFillerInfostate &&
           infostate_string_ != kDummyRootNodeInfostate;
  }
References open_spiel::algorithms::kDummyRootNodeInfostate, and open_spiel::algorithms::kFillerInfostate.
Referenced by infostate_string().
incoming_index()
int open_spiel::algorithms::InfostateNode::incoming_index () const inline
Definition at line 549 of file infostate_tree.h.
{ return incoming_index_; }
infostate_string()
const std::string & open_spiel::algorithms::InfostateNode::infostate_string () const inline
Definition at line 557 of file infostate_tree.h.
{
    // Avoid working with empty infostate strings.
    SPIEL_DCHECK_TRUE(has_infostate_string());
    return infostate_string_;
  }
References has_infostate_string(), and SPIEL_DCHECK_TRUE.
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalPolicy().
is_leaf_node()
bool open_spiel::algorithms::InfostateNode::is_leaf_node () const inline
Definition at line 600 of file infostate_tree.h.
{ return children_.empty(); }
Referenced by corresponding_chance_reach_probs(), and corresponding_states().
is_root_node()
bool open_spiel::algorithms::InfostateNode::is_root_node () const inline
Definition at line 552 of file infostate_tree.h.
{ return !parent_; }
Referenced by open_spiel::algorithms::InfostateTree::DecisionForSequence(), open_spiel::algorithms::InfostateTree::DecisionIdForSequence(), and open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyRootConstraints().
legal_actions()
const std::vector< Action > & open_spiel::algorithms::InfostateNode::legal_actions () const inline
Definition at line 594 of file infostate_tree.h.
{
    SPIEL_CHECK_EQ(type_, kDecisionInfostateNode);
    return legal_actions_;
  }
References open_spiel::algorithms::kDecisionInfostateNode, and SPIEL_CHECK_EQ.
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalPolicy().
MakeCertificate()
std::string open_spiel::algorithms::InfostateNode::MakeCertificate () const
Definition at line 78 of file infostate_tree.cc.
{
  if (type_ == kTerminalInfostateNode) return "{}";
  std::vector<std::string> certificates;
  for (InfostateNode* child : child_iterator()) {
    certificates.push_back(child->MakeCertificate());
  }
  std::sort(certificates.begin(), certificates.end());
  std::string open, close;
  if (type_ == kDecisionInfostateNode) {
    open = "[";
    close = "]";
  } else if (type_ == kObservationInfostateNode) {
    open = "(";
    close = ")";
  }
  return absl::StrCat(
      open, absl::StrJoin(certificates.begin(), certificates.end(), ""), close);
}
References open_spiel::algorithms::kDecisionInfostateNode, open_spiel::algorithms::kObservationInfostateNode, open_spiel::algorithms::kTerminalInfostateNode, absl::StrCat(), and absl::StrJoin().
Referenced by open_spiel::algorithms::InfostateTree::operator<<().
num_children()
int open_spiel::algorithms::InfostateNode::num_children () const inline
Definition at line 565 of file infostate_tree.h.
{ return children_.size(); }
Referenced by open_spiel::algorithms::InfostateTree::BestResponseValue(), and open_spiel::algorithms::ortools::SequenceFormLpSpecification::OptimalPolicy().
operator<<()
std::ostream & open_spiel::algorithms::InfostateNode::operator<< (std::ostream & os) const
Definition at line 73 of file infostate_tree.cc.
{
  if (!parent_) return os << 'x';
  return os << parent_ << ',' << incoming_index_;
}
parent()
InfostateNode * open_spiel::algorithms::InfostateNode::parent () const inline
Definition at line 548 of file infostate_tree.h.
{ return parent_; }
sequence_id()
const SequenceId open_spiel::algorithms::InfostateNode::sequence_id () const inline
Definition at line 571 of file infostate_tree.h.
{
    SPIEL_CHECK_FALSE(sequence_id_.is_undefined());
    return sequence_id_;
  }
References open_spiel::algorithms::internal::NodeId< Self >::is_undefined(), and SPIEL_CHECK_FALSE.
Referenced by open_spiel::algorithms::InfostateTree::BestResponse(), open_spiel::algorithms::InfostateTree::DecisionIdsWithParentSeq(), and open_spiel::algorithms::InfostateTree::empty_sequence().
start_sequence_id()
const SequenceId open_spiel::algorithms::InfostateNode::start_sequence_id () const inline
Definition at line 575 of file infostate_tree.h.
{
    SPIEL_CHECK_FALSE(start_sequence_id_.is_undefined());
    return start_sequence_id_;
  }
References open_spiel::algorithms::internal::NodeId< Self >::is_undefined(), and SPIEL_CHECK_FALSE.
Referenced by open_spiel::algorithms::InfostateTree::BestResponse(), and open_spiel::algorithms::InfostateTree::IsLeafSequence().
terminal_chance_reach_prob()
double open_spiel::algorithms::InfostateNode::terminal_chance_reach_prob () const inline
Definition at line 605 of file infostate_tree.h.
{
    SPIEL_CHECK_EQ(type_, kTerminalInfostateNode);
    return terminal_chn_reach_prob_;
  }
References open_spiel::algorithms::kTerminalInfostateNode, and SPIEL_CHECK_EQ.
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyCfValuesConstraints().
terminal_utility()
double open_spiel::algorithms::InfostateNode::terminal_utility () const inline
Definition at line 601 of file infostate_tree.h.
{
    SPIEL_CHECK_EQ(type_, kTerminalInfostateNode);
    return terminal_utility_;
  }
References open_spiel::algorithms::kTerminalInfostateNode, and SPIEL_CHECK_EQ.
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyCfValuesConstraints().
TerminalHistory()
const std::vector< Action > & open_spiel::algorithms::InfostateNode::TerminalHistory () const inline
Definition at line 620 of file infostate_tree.h.
{
    SPIEL_DCHECK_EQ(type_, kTerminalInfostateNode);
    return terminal_history_;
  }
References open_spiel::algorithms::kTerminalInfostateNode, and SPIEL_DCHECK_EQ.
tree()
const InfostateTree & open_spiel::algorithms::InfostateNode::tree () const inline
Definition at line 547 of file infostate_tree.h.
{ return tree_; }
Referenced by open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyCfValuesConstraints().
type()
const InfostateNodeType & open_spiel::algorithms::InfostateNode::type () const inline
Definition at line 550 of file infostate_tree.h.
{ return type_; }
Referenced by open_spiel::algorithms::InfostateTree::BestResponseValue(), open_spiel::algorithms::InfostateTree::DecisionIdsWithParentSeq(), open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyCfValuesConstraints(), and open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyReachProbsConstraints().
Friends And Related Symbol Documentation
InfostateTree
friend class InfostateTree friend
Definition at line 543 of file infostate_tree.h.
The documentation for this class was generated from the following files:
open_spiel/algorithms/infostate_tree.h
open_spiel/algorithms/infostate_tree.cc