open spiel: open_spiel::battleship::BattleshipGame Class Reference
open_spiel::battleship::BattleshipGame Class Reference final
#include <battleship.h>
Public Member Functions
BattleshipGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
absl::optional< double > UtilitySum () const override
int MaxGameLength () const override
std::string ActionToString (Player player, Action action_id) const override
std::vector< int > InformationStateTensorShape () const override
Action SerializeShipPlacementAction (const CellAndDirection &cell_and_dir) const
Action SerializeShotAction (const Shot &shot) const
absl::variant< CellAndDirection, Shot > DeserializeAction (const Action action_id) const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual std::vector< int > ObservationTensorShape () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Public Attributes
BattleshipConfiguration conf
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 179 of file battleship.h.
Constructor & Destructor Documentation
BattleshipGame()
open_spiel::battleship::BattleshipGame::BattleshipGame (const GameParameters & params) explicit
Definition at line 825 of file battleship.cc.
    : Game(kGameType, params) {
  conf.board_width = ParameterValue<int>("board_width");
  SPIEL_CHECK_GE(conf.board_width, 0);
  SPIEL_CHECK_LE(conf.board_width, kMaxDimension);
  conf.board_height = ParameterValue<int>("board_height");
  SPIEL_CHECK_GE(conf.board_height, 0);
  SPIEL_CHECK_LE(conf.board_height, kMaxDimension);
  // NOTE: It is *very* important to clone ship_sizes and ship_values onto the
  //     stack, otherwise we would run into undefined behavior without
  //     warning, because ParameterValue() returns a temporary without
  //     storage, and absl::string_view would amount to a fat pointer to a
  //     temporary.
  const std::string ship_sizes_param_str =
      ParameterValue<std::string>("ship_sizes");
  const std::string ship_values_param_str =
      ParameterValue<std::string>("ship_values");
  // First, we check that the list starts with '[' and ends with ']'.
  absl::string_view ship_sizes_param =
      absl::StripAsciiWhitespace(ship_sizes_param_str);
  SPIEL_CHECK_TRUE(absl::ConsumePrefix(&ship_sizes_param, "["));
  SPIEL_CHECK_TRUE(absl::ConsumeSuffix(&ship_sizes_param, "]"));
  absl::string_view ship_values_param =
      absl::StripAsciiWhitespace(ship_values_param_str);
  SPIEL_CHECK_TRUE(absl::ConsumePrefix(&ship_values_param, "["));
  SPIEL_CHECK_TRUE(absl::ConsumeSuffix(&ship_values_param, "]"));
  const std::vector<absl::string_view> ship_sizes =
      absl::StrSplit(ship_sizes_param, ';');
  const std::vector<absl::string_view> ship_values =
      absl::StrSplit(ship_values_param, ';');
  SPIEL_CHECK_EQ(ship_sizes.size(), ship_values.size());
  for (size_t ship_index = 0; ship_index < ship_sizes.size(); ++ship_index) {
    Ship ship;
    ship.id = ship_index;
    SPIEL_CHECK_TRUE(absl::SimpleAtoi(ship_sizes.at(ship_index), &ship.length));
    SPIEL_CHECK_TRUE(absl::SimpleAtod(ship_values.at(ship_index), &ship.value));
    SPIEL_CHECK_TRUE(ship.length <= conf.board_width ||
                     ship.length <= conf.board_height);
    SPIEL_CHECK_GE(ship.value, 0.0);
    conf.ships.push_back(ship);
  }
  SPIEL_CHECK_GT(conf.ships.size(), 0);
  // XXX(gfarina): The next restriction is not really intrinsic in the game,
  //     but we need it to pretty print the board status in
  //     `ObservationString`, since we use ASCII letters (a-z) to identify the
  //     ships.
  SPIEL_CHECK_LE(conf.ships.size(), 26);
  std::vector<ShipPlacement> partial_placement;
  if (!ExistsFeasiblePlacement(conf, &partial_placement)) {
    SpielFatalError(
        "Battleship: it is NOT possible to fit all the ships on the "
        "board!");
  }
  conf.num_shots = ParameterValue<int>("num_shots");
  SPIEL_CHECK_GT(conf.num_shots, 0);
  conf.allow_repeated_shots = ParameterValue<bool>("allow_repeated_shots");
  if (!conf.allow_repeated_shots) {
    SPIEL_CHECK_LE(conf.num_shots, conf.board_width * conf.board_height);
  }
  conf.loss_multiplier = ParameterValue<double>("loss_multiplier");
  if (std::abs(conf.loss_multiplier - 1.0) < kFloatTolerance) {
    game_type_.utility = GameType::Utility::kZeroSum;
  }
}
References open_spiel::battleship::BattleshipConfiguration::allow_repeated_shots, open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, conf, absl::ConsumePrefix(), absl::ConsumeSuffix(), open_spiel::battleship::ExistsFeasiblePlacement(), open_spiel::Game::game_type_, open_spiel::battleship::Ship::id, open_spiel::kGameType, open_spiel::battleship::kMaxDimension, open_spiel::GameType::kZeroSum, open_spiel::battleship::Ship::length, open_spiel::battleship::BattleshipConfiguration::loss_multiplier, open_spiel::battleship::BattleshipConfiguration::num_shots, open_spiel::Game::ParameterValue(), open_spiel::battleship::BattleshipConfiguration::ships, absl::SimpleAtod(), absl::SimpleAtoi(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_GT, SPIEL_CHECK_LE, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), absl::StripAsciiWhitespace(), absl::StrSplit(), open_spiel::GameType::utility, and open_spiel::battleship::Ship::value.
Member Function Documentation
ActionToString()
std::string open_spiel::battleship::BattleshipGame::ActionToString (Player player, Action action_id) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 998 of file battleship.cc.
{
  SPIEL_DCHECK_TRUE(player == Player{0} || player == Player{1});
  const absl::variant<CellAndDirection, Shot> action =
      DeserializeAction(action_id);
  if (absl::holds_alternative<Shot>(action)) {
    const Shot& shot = absl::get<Shot>(action);
    return absl::StrCat("Pl", player, ": shoot at (", shot.row, ", ", shot.col,
                        ")");
  } else {
    SPIEL_DCHECK_TRUE(absl::holds_alternative<CellAndDirection>(action));
    const CellAndDirection& cell_and_dir = absl::get<CellAndDirection>(action);
    absl::string_view direction_str;
    if (cell_and_dir.direction == CellAndDirection::Direction::Horizontal) {
      direction_str = "horizontally";
    } else {
      SPIEL_DCHECK_EQ(cell_and_dir.direction,
                      CellAndDirection::Direction::Vertical);
      direction_str = "vertically";
    }
    return absl::StrCat("Pl", player, ": place ship ", direction_str,
                        " with top-left corner in (",
                        cell_and_dir.TopLeftCorner().row, ", ",
                        cell_and_dir.TopLeftCorner().col, ")");
  }
}
References action, open_spiel::battleship::Cell::col, DeserializeAction(), open_spiel::battleship::CellAndDirection::direction, absl::get(), absl::holds_alternative(), open_spiel::battleship::CellAndDirection::Horizontal, player, open_spiel::battleship::Cell::row, SPIEL_DCHECK_EQ, SPIEL_DCHECK_TRUE, absl::StrCat(), open_spiel::battleship::CellAndDirection::TopLeftCorner(), and open_spiel::battleship::CellAndDirection::Vertical.
DeserializeAction()
absl::variant< CellAndDirection, Shot > open_spiel::battleship::BattleshipGame::DeserializeAction (const Action action_id) const
Definition at line 1056 of file battleship.cc.
{
  SPIEL_CHECK_GE(action_id, 0);
  SPIEL_CHECK_LT(action_id, NumDistinctActions());
  if (action_id >= conf.board_width * conf.board_height) {
    // If we are here, the action_id represents a `CellAndDirection`.
    return DeserializeShipPlacementAction(action_id);
  } else {
    // Otherwise, the action_id is a `Shot`.
    return DeserializeShotAction(action_id);
  }
}
References open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, conf, NumDistinctActions(), SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Referenced by ActionToString().
InformationStateTensorShape()
std::vector< int > open_spiel::battleship::BattleshipGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 974 of file battleship.cc.
{
  // The information set is a sequence of placements followed by a
  // a sequence of shots.
  //
  // Each placement has:
  //   - two bits for one-hot horizontal/vertical
  //   - rows bits for one-hot row
  //   - cols bits for one-hot col
  const int bits_for_placement = conf.ships.size() *
      (2 + conf.board_height + conf.board_width);
  // Each shot has:
  //   - two bits for the one-hot player
  //   - three bits for one-hot W/H/S
  //   - rows bits for the one-hot row
  //   - cols bits for the one-hot col
  const int bits_for_shots = conf.num_shots * NumPlayers() *
      (2 + 3 + conf.board_height + conf.board_width);
  // 1 bit for terminal?, 2 bits each for observing player and current player
  return {1 + NumPlayers() + NumPlayers() +
          bits_for_placement + bits_for_shots};
}
References open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, conf, open_spiel::battleship::BattleshipConfiguration::num_shots, NumPlayers(), and open_spiel::battleship::BattleshipConfiguration::ships.
MaxChanceOutcomes()
int open_spiel::battleship::BattleshipGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 186 of file battleship.h.
{ return 0; }
MaxGameLength()
int open_spiel::battleship::BattleshipGame::MaxGameLength () const override virtual
Implements open_spiel::Game.
Definition at line 968 of file battleship.cc.
{
  // Each player has to place their ships, plus potentially as many turns as
  // the number of shots
  return 2 * (conf.ships.size() + conf.num_shots);
}
References conf, open_spiel::battleship::BattleshipConfiguration::num_shots, and open_spiel::battleship::BattleshipConfiguration::ships.
MaxUtility()
double open_spiel::battleship::BattleshipGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 937 of file battleship.cc.
{
  // The final payoff is a sum of values of ships we destroyed, minus sum of
  // our own destroyed ships multiplied by the loss multiplier.
  //
  // So, here we take the best possible case: we destroy all of the opponent's
  // ship and have none of ours sunk.
  //
  // Note: the implementation below is only correct if the ship values are >=
  // 0. That condition is checked at game construction time. However, we allow
  // for a negative loss_multiplier.
  double max_utility = 0.0;
  for (const Ship& ship : conf.ships) {
    SPIEL_DCHECK_GE(ship.value, 0.0);
    max_utility += ship.value;
  }
  if (conf.loss_multiplier < 0.0) {
    max_utility *= (1.0 - conf.loss_multiplier);
  }
  return max_utility;
}
References conf, open_spiel::battleship::BattleshipConfiguration::loss_multiplier, open_spiel::battleship::BattleshipConfiguration::ships, and SPIEL_DCHECK_GE.
MinUtility()
double open_spiel::battleship::BattleshipGame::MinUtility () const override virtual
Implements open_spiel::Game.
Definition at line 916 of file battleship.cc.
{
  // The final payoff is a sum of values of ships we destroyed, minus sum of
  // our own destroyed ships multiplied by the loss multiplier.
  //
  // So, here we take the worst possible case: we destroy no ship and all of
  // our ships are destroyed.
  //
  // Note: the implementation below is only correct if the ship values are >=
  // 0. That condition is checked at game construction time. However, we allow
  // for a negative loss_multiplier.
  double min_utility = 0.0;
  if (conf.loss_multiplier > 0.0) {
    for (const Ship& ship : conf.ships) {
      SPIEL_DCHECK_GE(ship.value, 0.0);
      min_utility -= conf.loss_multiplier * ship.value;
    }
  }
  return min_utility;
}
References conf, open_spiel::battleship::BattleshipConfiguration::loss_multiplier, open_spiel::battleship::BattleshipConfiguration::ships, and SPIEL_DCHECK_GE.
NewInitialState()
std::unique_ptr< State > open_spiel::battleship::BattleshipGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 910 of file battleship.cc.
{
  const auto ptr =
      std::dynamic_pointer_cast<const BattleshipGame>(shared_from_this());
  return std::make_unique<BattleshipState>(ptr);
}
References ptr.
NumDistinctActions()
int open_spiel::battleship::BattleshipGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 905 of file battleship.cc.
{
  // See comment about (de)serialization of actions in `BattleshipGame`.
  return 3 * conf.board_width * conf.board_height;
}
References open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, and conf.
Referenced by DeserializeAction().
NumPlayers()
int open_spiel::battleship::BattleshipGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 187 of file battleship.h.
{ return 2; }
Referenced by InformationStateTensorShape().
SerializeShipPlacementAction()
Action open_spiel::battleship::BattleshipGame::SerializeShipPlacementAction (const CellAndDirection & cell_and_dir) const
Definition at line 1028 of file battleship.cc.
{
  SPIEL_CHECK_GE(cell_and_dir.TopLeftCorner().row, 0);
  SPIEL_CHECK_GE(cell_and_dir.TopLeftCorner().col, 0);
  SPIEL_CHECK_LT(cell_and_dir.TopLeftCorner().row, conf.board_height);
  SPIEL_CHECK_LT(cell_and_dir.TopLeftCorner().col, conf.board_width);
  Action shift = 0;
  if (cell_and_dir.direction == CellAndDirection::Direction::Horizontal) {
    shift = conf.board_width * conf.board_height;
  } else {
    SPIEL_DCHECK_EQ(cell_and_dir.direction,
                    CellAndDirection::Direction::Vertical);
    shift = 2 * conf.board_width * conf.board_height;
  }
  return shift + SerializeShotAction(cell_and_dir.TopLeftCorner());
}
References open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, open_spiel::battleship::Cell::col, conf, open_spiel::battleship::CellAndDirection::direction, open_spiel::battleship::CellAndDirection::Horizontal, open_spiel::battleship::Cell::row, SerializeShotAction(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_DCHECK_EQ, open_spiel::battleship::CellAndDirection::TopLeftCorner(), and open_spiel::battleship::CellAndDirection::Vertical.
SerializeShotAction()
Action open_spiel::battleship::BattleshipGame::SerializeShotAction (const Shot & shot) const
Definition at line 1047 of file battleship.cc.
{
  SPIEL_CHECK_GE(shot.row, 0);
  SPIEL_CHECK_GE(shot.col, 0);
  SPIEL_CHECK_LT(shot.row, conf.board_height);
  SPIEL_CHECK_LT(shot.col, conf.board_width);
  return shot.row * conf.board_width + shot.col;
}
References open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, open_spiel::battleship::Cell::col, conf, open_spiel::battleship::Cell::row, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Referenced by SerializeShipPlacementAction().
UtilitySum()
absl::optional< double > open_spiel::battleship::BattleshipGame::UtilitySum () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 960 of file battleship.cc.
{
  if (std::abs(conf.loss_multiplier - 1.0) < kFloatTolerance) {
    return 0.0;
  } else {
    return absl::nullopt;
  }
}
References conf, and open_spiel::battleship::BattleshipConfiguration::loss_multiplier.
Member Data Documentation
conf
BattleshipConfiguration open_spiel::battleship::BattleshipGame::conf
Definition at line 230 of file battleship.h.
Referenced by BattleshipGame(), DeserializeAction(), InformationStateTensorShape(), MaxGameLength(), MaxUtility(), MinUtility(), NumDistinctActions(), SerializeShipPlacementAction(), SerializeShotAction(), and UtilitySum().
The documentation for this class was generated from the following files:
open_spiel/games/battleship/battleship.h
open_spiel/games/battleship/battleship.cc