open spiel: open_spiel::negotiation::NegotiationGame Class Reference
open_spiel::negotiation::NegotiationGame Class Reference
#include <negotiation.h>
Public Member Functions
NegotiationGame (const GameParameters &params)
NegotiationGame (const NegotiationGame &other)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int NumPlayers () const override
double MaxUtility () const override
double MinUtility () const override
std::vector< int > ObservationTensorShape () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
std::string GetRNGState () const
void SetRNGState (const std::string &rng_state) const
std::mt19937 * RNG () const
bool EnableProposals () const
bool EnableUtterances () const
int NumItems () const
int NumSymbols () const
int UtteranceDim () const
int NumDistinctUtterances () const
int NumDistinctProposals () const
const std::vector< Action > & LegalUtterances () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 157 of file negotiation.h.
Constructor & Destructor Documentation
NegotiationGame() [1/2]
open_spiel::negotiation::NegotiationGame::NegotiationGame (const GameParameters & params) explicit
Definition at line 500 of file negotiation.cc.
    : Game(kGameType, params),
      enable_proposals_(
          ParameterValue<bool>("enable_proposals", kDefaultEnableProposals)),
      enable_utterances_(
          ParameterValue<bool>("enable_utterances", kDefaultEnableUtterances)),
      num_items_(ParameterValue<int>("num_items", kDefaultNumItems)),
      num_symbols_(ParameterValue<int>("num_symbols", kDefaultNumSymbols)),
      utterance_dim_(
          ParameterValue<int>("utterance_dim", kDefaultUtteranceDim)),
      seed_(ParameterValue<int>("rng_seed", kDefaultSeed)),
      legal_utterances_({}),
      rng_(new std::mt19937(seed_ >= 0 ? seed_ : std::mt19937::default_seed)) {
  ConstructLegalUtterances();
}
NegotiationGame() [2/2]
open_spiel::negotiation::NegotiationGame::NegotiationGame (const NegotiationGame & other) explicit
Member Function Documentation
DeserializeState()
std::unique_ptr< State > open_spiel::negotiation::NegotiationGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 568 of file negotiation.cc.
{
  if (str == "chance") {
    return NewInitialState();
  } else {
    std::vector<std::string> lines = absl::StrSplit(str, '\n');
    std::unique_ptr<State> state = NewInitialState();
    SPIEL_CHECK_EQ(lines.size(), 5);
    NegotiationState& nstate = static_cast<NegotiationState&>(*state);
    // Take the chance action, but then reset the quantities. Make sure game's
    // RNG state is not advanced during deserialization so copy it beforehand
    // in order to be able to restore after the chance action.
    std::unique_ptr<std::mt19937> rng = std::make_unique<std::mt19937>(*rng_);
    nstate.ApplyAction(0);
    rng_ = std::move(rng);
    nstate.ItemPool().clear();
    nstate.AgentUtils().clear();
    // Max steps
    nstate.SetMaxSteps(std::stoi(lines[0]));
    // Item pool.
    std::vector<std::string> parts = absl::StrSplit(lines[1], ' ');
    for (const auto& part : parts) {
      nstate.ItemPool().push_back(std::stoi(part));
    }
    // Agent utilities.
    for (Player player : {0, 1}) {
      parts = absl::StrSplit(lines[2 + player], ' ');
      nstate.AgentUtils().push_back({});
      for (const auto& part : parts) {
        nstate.AgentUtils()[player].push_back(std::stoi(part));
      }
    }
    nstate.SetCurrentPlayer(0);
    // Actions.
    if (lines.size() == 5) {
      parts = absl::StrSplit(lines[4], ' ');
      // Skip the first one since it is the chance node.
      for (int i = 1; i < parts.size(); ++i) {
        Action action = static_cast<Action>(std::stoi(parts[i]));
        nstate.ApplyAction(action);
      }
    }
    return state;
  }
}
References action, open_spiel::negotiation::NegotiationState::AgentUtils(), open_spiel::State::ApplyAction(), i, open_spiel::negotiation::NegotiationState::ItemPool(), NewInitialState(), player, open_spiel::negotiation::NegotiationState::SetCurrentPlayer(), open_spiel::negotiation::NegotiationState::SetMaxSteps(), SPIEL_CHECK_EQ, state, and absl::StrSplit().
EnableProposals()
bool open_spiel::negotiation::NegotiationGame::EnableProposals () const inline
Definition at line 186 of file negotiation.h.
{ return enable_proposals_; }
EnableUtterances()
bool open_spiel::negotiation::NegotiationGame::EnableUtterances () const inline
Definition at line 187 of file negotiation.h.
{ return enable_utterances_; }
GetRNGState()
std::string open_spiel::negotiation::NegotiationGame::GetRNGState () const virtual
Reimplemented from open_spiel::Game.
Definition at line 614 of file negotiation.cc.
{
  std::ostringstream rng_stream;
  rng_stream << *rng_;
  return rng_stream.str();
}
LegalUtterances()
const std::vector< Action > & open_spiel::negotiation::NegotiationGame::LegalUtterances () const inline
Definition at line 195 of file negotiation.h.
{
    return legal_utterances_;
  }
Referenced by open_spiel::negotiation::NegotiationState::LegalActions().
MaxChanceNodesInHistory()
int open_spiel::negotiation::NegotiationGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 171 of file negotiation.h.
{ return MaxGameLength(); }
References MaxGameLength().
MaxChanceOutcomes()
int open_spiel::negotiation::NegotiationGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 166 of file negotiation.h.
{ return 1; }
MaxGameLength()
int open_spiel::negotiation::NegotiationGame::MaxGameLength () const override virtual
Implements open_spiel::Game.
Definition at line 525 of file negotiation.cc.
{
  if (enable_utterances_) {
    return 2 * kMaxSteps;  // Every step is two turns: proposal, then utterance.
  } else {
    return kMaxSteps;
  }
}
References open_spiel::negotiation::kMaxSteps.
Referenced by MaxChanceNodesInHistory().
MaxUtility()
double open_spiel::negotiation::NegotiationGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 174 of file negotiation.h.
{
    return kMaxQuantity * kMaxValue * num_items_;
  }
References open_spiel::negotiation::kMaxQuantity, and open_spiel::negotiation::kMaxValue.
Referenced by MinUtility().
MinUtility()
double open_spiel::negotiation::NegotiationGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 177 of file negotiation.h.
{ return -MaxUtility(); }
References MaxUtility().
NewInitialState()
std::unique_ptr< State > open_spiel::negotiation::NegotiationGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 163 of file negotiation.h.
{
    return std::unique_ptr<State>(new NegotiationState(shared_from_this()));
  }
Referenced by DeserializeState().
NumDistinctActions()
int open_spiel::negotiation::NegotiationGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 544 of file negotiation.cc.
{
  if (enable_utterances_) {
    return NumDistinctProposals() + NumDistinctUtterances();
  } else {
    // Proposals are always possible.
    return NumDistinctProposals();
  }
}
References NumDistinctProposals(), and NumDistinctUtterances().
NumDistinctProposals()
int open_spiel::negotiation::NegotiationGame::NumDistinctProposals () const
Definition at line 537 of file negotiation.cc.
{
  // Every slot can hold { 0, 1, ..., MaxQuantity }, and there is an extra
  // one at the end for the special "agreement reached" action.
  return static_cast<int>(std::pow(kMaxQuantity + 1, num_items_)) + 1;
}
References open_spiel::negotiation::kMaxQuantity.
Referenced by open_spiel::negotiation::NegotiationState::ActionToString(), open_spiel::negotiation::NegotiationState::DoApplyAction(), open_spiel::negotiation::NegotiationState::LegalActions(), and NumDistinctActions().
NumDistinctUtterances()
int open_spiel::negotiation::NegotiationGame::NumDistinctUtterances () const
Definition at line 533 of file negotiation.cc.
{
  return static_cast<int>(std::pow(num_symbols_, utterance_dim_));
}
Referenced by NumDistinctActions().
NumItems()
int open_spiel::negotiation::NegotiationGame::NumItems () const inline
Definition at line 188 of file negotiation.h.
{ return num_items_; }
NumPlayers()
int open_spiel::negotiation::NegotiationGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 173 of file negotiation.h.
{ return kNumPlayers; }
References open_spiel::negotiation::kNumPlayers.
NumSymbols()
int open_spiel::negotiation::NegotiationGame::NumSymbols () const inline
Definition at line 189 of file negotiation.h.
{ return num_symbols_; }
ObservationTensorShape()
std::vector< int > open_spiel::negotiation::NegotiationGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 174 of file negotiation.cc.
{
  return {kNumPlayers + 2 + 2 + (num_items_ * (kMaxQuantity + 1)) +
          (num_items_ * (kMaxValue + 1)) + (num_items_ * (kMaxQuantity + 1)) +
          (enable_utterances_ ? utterance_dim_ * num_symbols_ : 0)};
}
References open_spiel::negotiation::kMaxQuantity, open_spiel::negotiation::kMaxValue, and open_spiel::negotiation::kNumPlayers.
RNG()
std::mt19937 * open_spiel::negotiation::NegotiationGame::RNG () const inline
Definition at line 185 of file negotiation.h.
{ return rng_.get(); }
SetRNGState()
void open_spiel::negotiation::NegotiationGame::SetRNGState (const std::string & rng_state) const virtual
Reimplemented from open_spiel::Game.
Definition at line 620 of file negotiation.cc.
{
  if (rng_state.empty()) return;
  std::istringstream rng_stream(rng_state);
  rng_stream >> *rng_;
}
UtteranceDim()
int open_spiel::negotiation::NegotiationGame::UtteranceDim () const inline
Definition at line 190 of file negotiation.h.
{ return utterance_dim_; }
The documentation for this class was generated from the following files:
open_spiel/games/negotiation/negotiation.h
open_spiel/games/negotiation/negotiation.cc