open spiel: absl::synchronization_internal::Waiter Class Reference
absl::synchronization_internal::Waiter Class Reference
#include <waiter.h>
Public Member Functions
Waiter ()
Waiter (const Waiter &)=delete
Waiter & operator= (const Waiter &)=delete
bool Wait (KernelTimeout t)
void Post ()
void Poke ()
Static Public Member Functions
static Waiter * GetWaiter (base_internal::ThreadIdentity *identity)
Static Public Attributes
static constexpr int kIdlePeriods = 60
Detailed Description
Definition at line 65 of file waiter.h.
Constructor & Destructor Documentation
Waiter() [1/2]
absl::synchronization_internal::Waiter::Waiter ()
Definition at line 70 of file waiter.cc.
               {
  futex_.store(0, std::memory_order_relaxed);
}
Referenced by GetWaiter().
Waiter() [2/2]
absl::synchronization_internal::Waiter::Waiter (const Waiter &) delete
Member Function Documentation
GetWaiter()
static Waiter * absl::synchronization_internal::Waiter::GetWaiter (base_internal::ThreadIdentity * identity) inline static
Definition at line 88 of file waiter.h.
{
    static_assert(
        sizeof(Waiter) <= sizeof(base_internal::ThreadIdentity::WaiterState),
        "Insufficient space for Waiter");
    return reinterpret_cast<Waiter*>(identity->waiter_state.data);
  }
References absl::base_internal::ThreadIdentity::WaiterState::data, Waiter(), and absl::base_internal::ThreadIdentity::waiter_state.
Referenced by AbslInternalPerThreadSemPost(), AbslInternalPerThreadSemWait(), and absl::synchronization_internal::PerThreadSem::Tick().
operator=()
Waiter & absl::synchronization_internal::Waiter::operator= (const Waiter &) delete
Poke()
void absl::synchronization_internal::Waiter::Poke ()
Definition at line 114 of file waiter.cc.
                  {
  // Wake one thread waiting on the futex.
  const int err = Futex::Wake(&futex_, 1);
  if (ABSL_PREDICT_FALSE(err < 0)) {
    ABSL_RAW_LOG(FATAL, "Futex operation failed with error %d\n", err);
  }
}
References ABSL_PREDICT_FALSE, and ABSL_RAW_LOG.
Referenced by Post(), and absl::synchronization_internal::PerThreadSem::Tick().
Post()
void absl::synchronization_internal::Waiter::Post ()
Definition at line 107 of file waiter.cc.
                  {
  if (futex_.fetch_add(1, std::memory_order_release) == 0) {
    // We incremented from 0, need to wake a potential waiter.
    Poke();
  }
}
References Poke().
Referenced by AbslInternalPerThreadSemPost().
Wait()
bool absl::synchronization_internal::Waiter::Wait (KernelTimeout t)
Definition at line 74 of file waiter.cc.
{
  // Loop until we can atomically decrement futex from a positive
  // value, waiting on a futex while we believe it is zero.
  // Note that, since the thread ticker is just reset, we don't need to check
  // whether the thread is idle on the very first pass of the loop.
  bool first_pass = true;
  while (true) {
    int32_t x = futex_.load(std::memory_order_relaxed);
    while (x != 0) {
      if (!futex_.compare_exchange_weak(x, x - 1,
                                        std::memory_order_acquire,
                                        std::memory_order_relaxed)) {
        continue;  // Raced with someone, retry.
      }
      return true;  // Consumed a wakeup, we are done.
    }
    if (!first_pass) MaybeBecomeIdle();
    const int err = Futex::WaitUntil(&futex_, 0, t);
    if (err != 0) {
      if (err == -EINTR || err == -EWOULDBLOCK) {
        // Do nothing, the loop will retry.
      } else if (err == -ETIMEDOUT) {
        return false;
      } else {
        ABSL_RAW_LOG(FATAL, "Futex operation failed with error %d\n", err);
      }
    }
    first_pass = false;
  }
}
References ABSL_RAW_LOG, and absl::x.
Referenced by AbslInternalPerThreadSemWait().
Member Data Documentation
kIdlePeriods
int absl::synchronization_internal::Waiter::kIdlePeriods = 60 static constexpr
Definition at line 97 of file waiter.h.
Referenced by absl::synchronization_internal::PerThreadSem::Tick().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/synchronization/internal/waiter.h
open_spiel/abseil-cpp/absl/synchronization/internal/waiter.cc