open spiel: open_spiel::dots_and_boxes::DotsAndBoxesState Class Reference
open_spiel::dots_and_boxes::DotsAndBoxesState Class Reference
#include <dots_and_boxes.h>
Public Member Functions
DotsAndBoxesState (std::shared_ptr< const Game > game, int num_rows, int num_cols, bool utility_margin)
DotsAndBoxesState (std::shared_ptr< const Game > game, int num_rows, int num_cols, bool utility_margin, const std::string &dbn)
DotsAndBoxesState (const DotsAndBoxesState &)=default
DotsAndBoxesState & operator= (const DotsAndBoxesState &)=default
Player CurrentPlayer () const override
std::string DbnString () const
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
std::vector< Action > LegalActions () const override
Player outcome () const
std::string StateToStringV (CellState state, int row, int col) const
std::string StateToStringH (CellState state, int row, int col) const
std::string StateToStringP (CellState state, int row, int col) const
void SetCurrentPlayer (Player player)
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes
std::vector< CellState > v_
std::vector< CellState > h_
std::vector< CellState > p_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 99 of file dots_and_boxes.h.
Constructor & Destructor Documentation
DotsAndBoxesState() [1/3]
open_spiel::dots_and_boxes::DotsAndBoxesState::DotsAndBoxesState (std::shared_ptr< const Game > game, int num_rows, int num_cols, bool utility_margin)
Definition at line 386 of file dots_and_boxes.cc.
    : State(game),
      num_rows_(num_rows),
      num_cols_(num_cols),
      num_cells_((1 + num_rows) * (1 + num_cols)),
      utility_margin_(utility_margin) {
  SPIEL_CHECK_GE(num_rows_, 1);
  SPIEL_CHECK_GE(num_cols_, 1);
  h_.resize(num_cells_);
  v_.resize(num_cells_);
  p_.resize(num_cells_);
  std::fill(begin(h_), end(h_), CellState::kEmpty);
  std::fill(begin(v_), end(v_), CellState::kEmpty);
  std::fill(begin(p_), end(p_), CellState::kEmpty);
  std::fill(begin(points_), end(points_), 0);
}
References begin, end, h_, open_spiel::dots_and_boxes::kEmpty, p_, SPIEL_CHECK_GE, and v_.
Referenced by Clone().
DotsAndBoxesState() [2/3]
open_spiel::dots_and_boxes::DotsAndBoxesState::DotsAndBoxesState (std::shared_ptr< const Game > game, int num_rows, int num_cols, bool utility_margin, const std::string & dbn)
Definition at line 411 of file dots_and_boxes.cc.
    : State(game),
      num_rows_(num_rows),
      num_cols_(num_cols),
      num_cells_((1 + num_rows) * (1 + num_cols)),
      utility_margin_(utility_margin) {
  /* std::cout << "Init dots and boxes state with dbn\n"; */
  SPIEL_CHECK_GE(num_rows_, 1);
  /* SPIEL_CHECK_LE(num_rows_, 1000); */
  SPIEL_CHECK_GE(num_cols_, 1);
  /* SPIEL_CHECK_LE(num_cols_, 1000); */
  h_.resize(num_cells_);
  v_.resize(num_cells_);
  p_.resize(num_cells_);
  std::fill(begin(h_), end(h_), CellState::kEmpty);
  std::fill(begin(v_), end(v_), CellState::kEmpty);
  std::fill(begin(p_), end(p_), CellState::kEmpty);
  std::fill(begin(points_), end(points_), 0);
  int cell = 0;
  int idx = 0;
  for (int row = 0; row < num_rows_ + 1; ++row) {
    for (int col = 0; col < num_cols_; ++col) {
      if (dbn[idx] == '1') {
        h_[cell] = CellState::kSet;
        num_moves_++;
      }
      idx++;
      cell++;
    }
    cell++;
  }
  cell = 0;
  for (int row = 0; row < num_rows_; ++row) {
    for (int col = 0; col < num_cols_ + 1; ++col) {
      if (dbn[idx] == '1') {
        v_[cell] = CellState::kSet;
        num_moves_++;
      }
      idx++;
      cell++;
    }
  }
  int max_moves = (num_rows_ + 1) * num_cols_ + num_rows_ * (num_cols_ + 1);
  SPIEL_CHECK_LE(num_moves_, max_moves);
}
References begin, end, h_, open_spiel::dots_and_boxes::kEmpty, open_spiel::dots_and_boxes::kSet, p_, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and v_.
DotsAndBoxesState() [3/3]
open_spiel::dots_and_boxes::DotsAndBoxesState::DotsAndBoxesState (const DotsAndBoxesState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::dots_and_boxes::DotsAndBoxesState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 361 of file dots_and_boxes.cc.
{
  Move move(action_id, num_rows_, num_cols_);
  return absl::StrCat("P", StateToString(PlayerToState(player)), "(",
                      OrientationToString(move.GetOrientation()), ",",
                      move.GetRow(), ",", move.GetCol(), ")");
}
References open_spiel::dots_and_boxes::OrientationToString(), player, open_spiel::dots_and_boxes::PlayerToState(), open_spiel::dots_and_boxes::StateToString(), and absl::StrCat().
Clone()
std::unique_ptr< State > open_spiel::dots_and_boxes::DotsAndBoxesState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 563 of file dots_and_boxes.cc.
{
  return std::unique_ptr<State>(new DotsAndBoxesState(*this));
}
References DotsAndBoxesState().
CurrentPlayer()
Player open_spiel::dots_and_boxes::DotsAndBoxesState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 108 of file dots_and_boxes.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by DoApplyAction().
DbnString()
std::string open_spiel::dots_and_boxes::DotsAndBoxesState::DbnString () const
Definition at line 326 of file dots_and_boxes.cc.
{
  // A string representing which lines have been set.
  // This corresponds to an unscored state representation
  // (Barker and Korf 2012).
  // For a scored state, use the ObservationTensor function.
  std::string str;
  int cell = 0;
  int idx = 0;
  for (int row = 0; row < num_rows_ + 1; ++row) {
    for (int col = 0; col < num_cols_; ++col) {
      if (h_[cell] != CellState::kEmpty) {
        absl::StrAppend(&str, "1");
      } else {
        absl::StrAppend(&str, "0");
      }
      idx++;
      cell++;
    }
    cell++;
  }
  cell = 0;
  for (int row = 0; row < num_rows_; ++row) {
    for (int col = 0; col < num_cols_ + 1; ++col) {
      if (v_[cell] != CellState::kEmpty) {
        absl::StrAppend(&str, "1");
      } else {
        absl::StrAppend(&str, "0");
      }
      idx++;
      cell++;
    }
  }
  return str;
}
References h_, open_spiel::dots_and_boxes::kEmpty, absl::StrAppend(), and v_.
DoApplyAction()
void open_spiel::dots_and_boxes::DotsAndBoxesState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 224 of file dots_and_boxes.cc.
{
  Move move = Move(action, num_rows_, num_cols_);
  int cell = move.GetCell();
  bool won_cell = false;
  if (move.GetOrientation() == CellOrientation::kVertical) {
    SPIEL_CHECK_EQ(v_[cell], CellState::kEmpty);
    v_[cell] = PlayerToState(CurrentPlayer());
    // Left
    if (move.GetCol() > 0) {
      if (v_[move.GetCellLeft()] != CellState::kEmpty &&
          h_[move.GetCellLeft()] != CellState::kEmpty &&
          h_[move.GetCellBelowLeft()] != CellState::kEmpty) {
        won_cell = true;
        p_[move.GetCellLeft()] = PlayerToState(CurrentPlayer());
        points_[current_player_]++;
      }
    }
    // Right
    if (move.GetCol() < num_cols_) {
      if (v_[move.GetCellRight()] != CellState::kEmpty &&
          h_[move.GetCellBelow()] != CellState::kEmpty &&
          h_[cell] != CellState::kEmpty) {
        won_cell = true;
        p_[cell] = PlayerToState(CurrentPlayer());
        points_[current_player_]++;
      }
    }
  } else {  // move.GetOrientation() == kHorizontal
    SPIEL_CHECK_EQ(h_[cell], CellState::kEmpty);
    h_[cell] = PlayerToState(CurrentPlayer());
    // Above
    if (move.GetRow() > 0) {
      if (v_[move.GetCellAbove()] != CellState::kEmpty &&
          v_[move.GetCellAboveRight()] != CellState::kEmpty &&
          h_[move.GetCellAbove()] != CellState::kEmpty) {
        won_cell = true;
        p_[move.GetCellAbove()] = PlayerToState(CurrentPlayer());
        points_[current_player_]++;
      }
    }
    // Below
    if (move.GetRow() < num_rows_) {
      if (v_[cell] != CellState::kEmpty &&
          v_[move.GetCellRight()] != CellState::kEmpty &&
          h_[move.GetCellBelow()] != CellState::kEmpty) {
        won_cell = true;
        p_[cell] = PlayerToState(CurrentPlayer());
        points_[current_player_]++;
      }
    }
  }
  if (Wins(current_player_)) {
    outcome_ = current_player_;
  }
  if (!won_cell) {
    // If box is scored, current player keeps the turn
    current_player_ = 1 - current_player_;
  }
  num_moves_ += 1;
}
References action, CurrentPlayer(), h_, open_spiel::dots_and_boxes::kEmpty, open_spiel::dots_and_boxes::kVertical, p_, open_spiel::dots_and_boxes::PlayerToState(), SPIEL_CHECK_EQ, and v_.
InformationStateString()
std::string open_spiel::dots_and_boxes::DotsAndBoxesState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 513 of file dots_and_boxes.cc.
{
  // Cannot be used when starting from a non-empty initial state.
  // If the game is started from a non-empty initial state
  // there are no previous moves and thus the history is empty.
  // And moves cannot be inferred as different orderings can lead
  // to different scores for the players.
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::dots_and_boxes::DotsAndBoxesState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 489 of file dots_and_boxes.cc.
{
  return outcome_ != kInvalidPlayer || IsFull();
}
References open_spiel::kInvalidPlayer.
Referenced by CurrentPlayer(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::dots_and_boxes::DotsAndBoxesState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 290 of file dots_and_boxes.cc.
{
  if (IsTerminal()) return {};
  std::vector<Action> actions;
  int action = 0;
  Move move;
  move.SetRowsCols(num_rows_, num_cols_);
  int maxh = (num_rows_ + 1) * num_cols_;
  int maxv = num_rows_ * (num_cols_ + 1);
  // Horizontal lines
  for (int row = 0; row <= num_rows_; ++row) {
    for (int col = 0; col < num_cols_; ++col) {
      move.Set(row, col, CellOrientation::kHorizontal);
      if (h_[move.GetCell()] == CellState::kEmpty) {
        actions.push_back(action);
      } else {
      }
      action++;
    }
  }
  SPIEL_CHECK_EQ(action, maxh);
  // Vertical lines
  for (int row = 0; row < num_rows_; ++row) {
    for (int col = 0; col <= num_cols_; ++col) {
      move.Set(row, col, CellOrientation::kVertical);
      if (v_[move.GetCell()] == CellState::kEmpty) {
        actions.push_back(action);
      } else {
      }
      // std::cout << action << std::endl;
      action++;
    }
  }
  SPIEL_CHECK_EQ(action, maxh + maxv);
  return actions;
}
References action, h_, IsTerminal(), open_spiel::dots_and_boxes::kEmpty, open_spiel::dots_and_boxes::kHorizontal, open_spiel::dots_and_boxes::kVertical, SPIEL_CHECK_EQ, and v_.
ObservationString()
std::string open_spiel::dots_and_boxes::DotsAndBoxesState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 524 of file dots_and_boxes.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::dots_and_boxes::DotsAndBoxesState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 530 of file dots_and_boxes.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // Treat `values` as a 3-d tensor.
  TensorView<3> view(values,
                     {/*cellstates=*/3, num_cells_,
                      /*part of cell (h, v, p)=*/3},
                     true);
  for (int cell = 0; cell < num_cells_; ++cell) {
    view[{static_cast<int>(h_[cell]), cell, 0}] = 1.0;
    view[{static_cast<int>(v_[cell]), cell, 1}] = 1.0;
    view[{static_cast<int>(p_[cell]), cell, 2}] = 1.0;
  }
}
References h_, open_spiel::State::num_players_, p_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, v_, and values.
operator=()
DotsAndBoxesState & open_spiel::dots_and_boxes::DotsAndBoxesState::operator= (const DotsAndBoxesState &) default
outcome()
Player open_spiel::dots_and_boxes::DotsAndBoxesState::outcome () const inline
Definition at line 123 of file dots_and_boxes.h.
{ return outcome_; }
Referenced by open_spiel.python.examples.nego_nbs_example.Negotiation::__str__(), open_spiel.python.algorithms.mcts.SearchNode::puct_value(), open_spiel.python.algorithms.mcts.SearchNode::sort_key(), open_spiel.python.algorithms.mcts.SearchNode::to_str(), and open_spiel.python.algorithms.mcts.SearchNode::uct_value().
Returns()
std::vector< double > open_spiel::dots_and_boxes::DotsAndBoxesState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 493 of file dots_and_boxes.cc.
{
  if (utility_margin_) {
    if (IsTerminal()) {
      double margin = (double)(points_[0] - points_[1]);
      return {margin, -margin};
    } else {
      return {0.0, 0.0};
    }
  } else {
    if (Wins(Player{0})) {
      return {1.0, -1.0};
    } else if (Wins(Player{1})) {
      return {-1.0, 1.0};
    } else {
      // Game is not finished
      return {0.0, 0.0};
    }
  }
}
References IsTerminal().
SetCurrentPlayer()
void open_spiel::dots_and_boxes::DotsAndBoxesState::SetCurrentPlayer (Player player) inline
Definition at line 129 of file dots_and_boxes.h.
{ current_player_ = player; }
References player.
StateToStringH()
std::string open_spiel::dots_and_boxes::DotsAndBoxesState::StateToStringH (CellState state, int row, int col) const
Definition at line 567 of file dots_and_boxes.cc.
{
  if (row == 0 && col == 0) {
    if (state == CellState::kEmpty) {
      return " ";
    } else {
      return "";
    }
  }
  if (row == num_rows_ && col == 0) {
    if (state == CellState::kEmpty) {
      return " ";
    } else {
      return "";
    }
  }
  if (row == 0 && col == num_cols_) {
    return "";
  }
  if (row == num_rows_ && col == num_cols_) {
    return "";
  }
  if (col == num_cols_) {
    return "";
  }
  if (col == 0) {
    if (state == CellState::kEmpty) {
      return " ";
    } else {
      return "";
    }
  }
  if (row == 0) {
    if (state == CellState::kEmpty) {
      return " ";
    } else {
      return "";
    }
  }
  if (row == num_rows_) {
    if (state == CellState::kEmpty) {
      return " ";
    } else {
      return "";
    }
  }
  if (state == CellState::kEmpty) {
    return " ";
  } else {
    return "";
  }
}
References open_spiel::dots_and_boxes::kEmpty, and state.
Referenced by ToString().
StateToStringP()
std::string open_spiel::dots_and_boxes::DotsAndBoxesState::StateToStringP (CellState state, int row, int col) const
Definition at line 629 of file dots_and_boxes.cc.
{
  if (state == CellState::kEmpty) {
    return "   ";
  }
  if (state == CellState::kPlayer1) {
    return " 1 ";
  }
  if (state == CellState::kPlayer2) {
    return " 2 ";
  }
  return " x ";
}
References open_spiel::dots_and_boxes::kEmpty, open_spiel::dots_and_boxes::kPlayer1, open_spiel::dots_and_boxes::kPlayer2, and state.
Referenced by ToString().
StateToStringV()
std::string open_spiel::dots_and_boxes::DotsAndBoxesState::StateToStringV (CellState state, int row, int col) const
Definition at line 620 of file dots_and_boxes.cc.
{
  if (state == CellState::kEmpty) {
    return " ";  // "";
  } else {
    return "";
  }
}
References open_spiel::dots_and_boxes::kEmpty, and state.
Referenced by ToString().
ToString()
std::string open_spiel::dots_and_boxes::DotsAndBoxesState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 460 of file dots_and_boxes.cc.
{
  std::string str;
  int cell = 0;
  int cell_start = 0;
  for (int r = 0; r < num_rows_; ++r) {
    cell_start = cell;
    for (int c = 0; c <= num_cols_; ++c) {
      absl::StrAppend(&str, StateToStringH(h_[cell], r, c));
      cell++;
    }
    absl::StrAppend(&str, "\n");
    cell = cell_start;
    for (int c = 0; c < num_cols_; ++c) {
      absl::StrAppend(&str, StateToStringV(v_[cell], r, c));
      absl::StrAppend(&str, StateToStringP(p_[cell], r, c));
      cell++;
    }
    absl::StrAppend(&str, StateToStringV(v_[cell], r, num_cols_));
    cell++;
    absl::StrAppend(&str, "\n");
  }
  for (int c = 0; c <= num_cols_; ++c) {
    absl::StrAppend(&str, StateToStringH(h_[cell], num_rows_, c));
    cell++;
  }
  absl::StrAppend(&str, "\n");
  return str;
}
References h_, p_, r, StateToStringH(), StateToStringP(), StateToStringV(), absl::StrAppend(), and v_.
Referenced by ObservationString().
UndoAction()
void open_spiel::dots_and_boxes::DotsAndBoxesState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 547 of file dots_and_boxes.cc.
{
  Move move(action, num_rows_, num_cols_);
  int cell = move.GetCell();
  if (p_[cell] != CellState::kEmpty) {
    points_[current_player_]--;
  }
  h_[cell] = CellState::kEmpty;
  v_[cell] = CellState::kEmpty;
  p_[cell] = CellState::kEmpty;
  current_player_ = player;
  outcome_ = kInvalidPlayer;
  num_moves_ -= 1;
  history_.pop_back();
  --move_number_;
}
References action, h_, open_spiel::State::history_, open_spiel::dots_and_boxes::kEmpty, open_spiel::kInvalidPlayer, open_spiel::State::move_number_, p_, player, and v_.
Member Data Documentation
h_
std::vector<CellState> open_spiel::dots_and_boxes::DotsAndBoxesState::h_ protected
Definition at line 133 of file dots_and_boxes.h.
Referenced by DbnString(), DoApplyAction(), DotsAndBoxesState(), DotsAndBoxesState(), LegalActions(), ObservationTensor(), ToString(), and UndoAction().
p_
std::vector<CellState> open_spiel::dots_and_boxes::DotsAndBoxesState::p_ protected
Definition at line 134 of file dots_and_boxes.h.
Referenced by DoApplyAction(), DotsAndBoxesState(), DotsAndBoxesState(), ObservationTensor(), ToString(), and UndoAction().
v_
std::vector<CellState> open_spiel::dots_and_boxes::DotsAndBoxesState::v_ protected
Definition at line 132 of file dots_and_boxes.h.
Referenced by DbnString(), DoApplyAction(), DotsAndBoxesState(), DotsAndBoxesState(), LegalActions(), ObservationTensor(), ToString(), and UndoAction().
The documentation for this class was generated from the following files:
open_spiel/games/dots_and_boxes/dots_and_boxes.h
open_spiel/games/dots_and_boxes/dots_and_boxes.cc