open spiel: absl::strings_internal::BigUnsigned< max_words > Class Template Reference
absl::strings_internal::BigUnsigned< max_words > Class Template Reference
#include <charconv_bigint.h>
Public Member Functions
BigUnsigned ()
constexpr BigUnsigned (uint64_t v)
BigUnsigned (absl::string_view sv)
int ReadFloatMantissa (const ParsedFloat &fp, int significant_digits)
void ShiftLeft (int count)
void MultiplyBy (uint32_t v)
void MultiplyBy (uint64_t v)
void MultiplyByFiveToTheNth (int n)
void MultiplyByTenToTheNth (int n)
template<int M>
void MultiplyBy (const BigUnsigned< M > &other)
void SetToZero ()
uint32_t GetWord (int index) const
std::string ToString () const
int size () const
const uint32_t * words () const
Static Public Member Functions
static constexpr int Digits10 ()
static BigUnsigned FiveToTheNth (int n)
Detailed Description
template<int max_words>
class absl::strings_internal::BigUnsigned< max_words >
Definition at line 57 of file charconv_bigint.h.
Constructor & Destructor Documentation
BigUnsigned() [1/3]
template<int max_words> absl::strings_internal::BigUnsigned< max_words >::BigUnsigned () inline
Definition at line 62 of file charconv_bigint.h.
: size_(0), words_{} {}
BigUnsigned() [2/3]
template<int max_words> absl::strings_internal::BigUnsigned< max_words >::BigUnsigned (uint64_t v) inline explicit constexpr
Definition at line 63 of file charconv_bigint.h.
      : size_((v >> 32) ? 2 : v ? 1 : 0),
        words_{static_cast<uint32_t>(v & 0xffffffffu),
               static_cast<uint32_t>(v >> 32)} {}
BigUnsigned() [3/3]
template<int max_words> absl::strings_internal::BigUnsigned< max_words >::BigUnsigned (absl::string_view sv) inline explicit
Definition at line 71 of file charconv_bigint.h.
                                           : size_(0), words_{} {
    // Check for valid input, returning a 0 otherwise.  This is reasonable
    // behavior only because this constructor is for unit tests.
    if (std::find_if_not(sv.begin(), sv.end(), ascii_isdigit) != sv.end() ||
        sv.empty()) {
      return;
    }
    int exponent_adjust =
        ReadDigits(sv.data(), sv.data() + sv.size(), Digits10() + 1);
    if (exponent_adjust > 0) {
      MultiplyByTenToTheNth(exponent_adjust);
    }
  }
References absl::ascii_isdigit(), absl::string_view::begin(), absl::string_view::data(), absl::strings_internal::BigUnsigned< max_words >::Digits10(), absl::string_view::empty(), absl::string_view::end(), absl::strings_internal::BigUnsigned< max_words >::MultiplyByTenToTheNth(), and absl::string_view::size().
Member Function Documentation
Digits10()
template<int max_words> static constexpr int absl::strings_internal::BigUnsigned< max_words >::Digits10 () inline static constexpr
Definition at line 96 of file charconv_bigint.h.
{
    // 9975007/1035508 is very slightly less than log10(2**32).
    return static_cast<uint64_t>(max_words) * 9975007 / 1035508;
  }
Referenced by absl::strings_internal::BigUnsigned< max_words >::BigUnsigned().
FiveToTheNth()
template<int max_words> BigUnsigned< max_words > absl::strings_internal::BigUnsigned< max_words >::FiveToTheNth (int n) static
Definition at line 288 of file charconv_bigint.cc.
           {
  BigUnsigned answer(1u);
  // Seed from the table of large powers, if possible.
  bool first_pass = true;
  while (n >= kLargePowerOfFiveStep) {
    int big_power =
        std::min(n / kLargePowerOfFiveStep, kLargestPowerOfFiveIndex);
    if (first_pass) {
      // just copy, rather than multiplying by 1
      std::copy(
          LargePowerOfFiveData(big_power),
          LargePowerOfFiveData(big_power) + LargePowerOfFiveSize(big_power),
          answer.words_);
      answer.size_ = LargePowerOfFiveSize(big_power);
      first_pass = false;
    } else {
      answer.MultiplyBy(LargePowerOfFiveSize(big_power),
                        LargePowerOfFiveData(big_power));
    }
    n -= kLargePowerOfFiveStep * big_power;
  }
  answer.MultiplyByFiveToTheNth(n);
  return answer;
}
References absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), absl::strings_internal::BigUnsigned< max_words >::MultiplyByFiveToTheNth(), and absl::n.
Referenced by absl::ABSL_NAMESPACE_BEGIN::MustRoundUp(), and absl::strings_internal::TEST().
GetWord()
template<int max_words> uint32_t absl::strings_internal::BigUnsigned< max_words >::GetWord (int index) const inline
Definition at line 206 of file charconv_bigint.h.
{
    if (index < 0 || index >= size_) {
      return 0;
    }
    return words_[index];
  }
Referenced by absl::strings_internal::Compare(), and absl::strings_internal::operator==().
MultiplyBy() [1/3]
template<int max_words> template<int M> void absl::strings_internal::BigUnsigned< max_words >::MultiplyBy (const BigUnsigned< M > & other) inline
Definition at line 195 of file charconv_bigint.h.
{
    MultiplyBy(other.size(), other.words());
  }
References absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), absl::strings_internal::BigUnsigned< max_words >::size(), and absl::strings_internal::BigUnsigned< max_words >::words().
MultiplyBy() [2/3]
template<int max_words> void absl::strings_internal::BigUnsigned< max_words >::MultiplyBy (uint32_t v) inline
Definition at line 130 of file charconv_bigint.h.
{
    if (size_ == 0 || v == 1) {
      return;
    }
    if (v == 0) {
      SetToZero();
      return;
    }
    const uint64_t factor = v;
    uint64_t window = 0;
    for (int i = 0; i < size_; ++i) {
      window += factor * words_[i];
      words_[i] = window & 0xffffffff;
      window >>= 32;
    }
    // If carry bits remain and there's space for them, grow size_.
    if (window && size_ < max_words) {
      words_[size_] = window & 0xffffffff;
      ++size_;
    }
  }
References absl::i, absl::strings_internal::BigUnsigned< max_words >::SetToZero(), and absl::v.
Referenced by absl::strings_internal::BigUnsigned< max_words >::FiveToTheNth(), absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), absl::strings_internal::BigUnsigned< max_words >::MultiplyByFiveToTheNth(), absl::strings_internal::BigUnsigned< max_words >::MultiplyByTenToTheNth(), absl::ABSL_NAMESPACE_BEGIN::MustRoundUp(), absl::strings_internal::TEST(), absl::strings_internal::TEST(), absl::strings_internal::TEST(), and absl::strings_internal::TEST().
MultiplyBy() [3/3]
template<int max_words> void absl::strings_internal::BigUnsigned< max_words >::MultiplyBy (uint64_t v) inline
Definition at line 152 of file charconv_bigint.h.
{
    uint32_t words[2];
    words[0] = static_cast<uint32_t>(v);
    words[1] = static_cast<uint32_t>(v >> 32);
    if (words[1] == 0) {
      MultiplyBy(words[0]);
    } else {
      MultiplyBy(2, words);
    }
  }
References absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), absl::v, and absl::strings_internal::BigUnsigned< max_words >::words().
MultiplyByFiveToTheNth()
template<int max_words> void absl::strings_internal::BigUnsigned< max_words >::MultiplyByFiveToTheNth (int n) inline
Definition at line 164 of file charconv_bigint.h.
{
    while (n >= kMaxSmallPowerOfFive) {
      MultiplyBy(kFiveToNth[kMaxSmallPowerOfFive]);
      n -= kMaxSmallPowerOfFive;
    }
    if (n > 0) {
      MultiplyBy(kFiveToNth[n]);
    }
  }
References absl::strings_internal::kFiveToNth, absl::strings_internal::kMaxSmallPowerOfFive, absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), and absl::n.
Referenced by absl::strings_internal::BigUnsigned< max_words >::FiveToTheNth(), absl::strings_internal::BigUnsigned< max_words >::MultiplyByTenToTheNth(), absl::ABSL_NAMESPACE_BEGIN::MustRoundUp(), and absl::strings_internal::TEST().
MultiplyByTenToTheNth()
template<int max_words> void absl::strings_internal::BigUnsigned< max_words >::MultiplyByTenToTheNth (int n) inline
Definition at line 175 of file charconv_bigint.h.
{
    if (n > kMaxSmallPowerOfTen) {
      // For large n, raise to a power of 5, then shift left by the same amount.
      // (10**n == 5**n * 2**n.)  This requires fewer multiplications overall.
      MultiplyByFiveToTheNth(n);
      ShiftLeft(n);
    } else if (n > 0) {
      // We can do this more quickly for very small N by using a single
      // multiplication.
      MultiplyBy(kTenToNth[n]);
    }
  }
References absl::strings_internal::kMaxSmallPowerOfTen, absl::strings_internal::kTenToNth, absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), absl::strings_internal::BigUnsigned< max_words >::MultiplyByFiveToTheNth(), absl::n, and absl::strings_internal::BigUnsigned< max_words >::ShiftLeft().
Referenced by absl::strings_internal::BigUnsigned< max_words >::BigUnsigned(), and absl::strings_internal::TEST().
ReadFloatMantissa()
template<int max_words> int absl::strings_internal::BigUnsigned< max_words >::ReadFloatMantissa (const ParsedFloat & fp, int significant_digits)
Definition at line 171 of file charconv_bigint.cc.
{
  SetToZero();
  assert(fp.type == FloatType::kNumber);
  if (fp.subrange_begin == nullptr) {
    // We already exactly parsed the mantissa, so no more work is necessary.
    words_[0] = fp.mantissa & 0xffffffffu;
    words_[1] = fp.mantissa >> 32;
    if (words_[1]) {
      size_ = 2;
    } else if (words_[0]) {
      size_ = 1;
    }
    return fp.exponent;
  }
  int exponent_adjust =
      ReadDigits(fp.subrange_begin, fp.subrange_end, significant_digits);
  return fp.literal_exponent + exponent_adjust;
}
References absl::strings_internal::ParsedFloat::exponent, absl::strings_internal::kNumber, absl::strings_internal::ParsedFloat::literal_exponent, absl::strings_internal::ParsedFloat::mantissa, absl::strings_internal::ParsedFloat::subrange_begin, absl::strings_internal::ParsedFloat::subrange_end, and absl::strings_internal::ParsedFloat::type.
Referenced by absl::ABSL_NAMESPACE_BEGIN::MustRoundUp().
SetToZero()
template<int max_words> void absl::strings_internal::BigUnsigned< max_words >::SetToZero () inline
Definition at line 199 of file charconv_bigint.h.
                   {
    std::fill(words_, words_ + size_, 0u);
    size_ = 0;
  }
References absl::u.
Referenced by absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), and absl::strings_internal::BigUnsigned< max_words >::ShiftLeft().
ShiftLeft()
template<int max_words> void absl::strings_internal::BigUnsigned< max_words >::ShiftLeft (int count) inline
Definition at line 102 of file charconv_bigint.h.
{
    if (count > 0) {
      const int word_shift = count / 32;
      if (word_shift >= max_words) {
        SetToZero();
        return;
      }
      size_ = (std::min)(size_ + word_shift, max_words);
      count %= 32;
      if (count == 0) {
        std::copy_backward(words_, words_ + size_ - word_shift, words_ + size_);
      } else {
        for (int i = (std::min)(size_, max_words - 1); i > word_shift; --i) {
          words_[i] = (words_[i - word_shift] << count) |
                      (words_[i - word_shift - 1] >> (32 - count));
        }
        words_[word_shift] = words_[0] << count;
        // Grow size_ if necessary.
        if (size_ < max_words && words_[size_]) {
          ++size_;
        }
      }
      std::fill(words_, words_ + word_shift, 0u);
    }
  }
References absl::i, absl::strings_internal::BigUnsigned< max_words >::SetToZero(), and absl::u.
Referenced by absl::strings_internal::BigUnsigned< max_words >::MultiplyByTenToTheNth(), absl::ABSL_NAMESPACE_BEGIN::MustRoundUp(), absl::strings_internal::TEST(), and absl::strings_internal::TEST().
size()
template<int max_words> int absl::strings_internal::BigUnsigned< max_words >::size () const inline
Definition at line 217 of file charconv_bigint.h.
{ return size_; }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), absl::strings_internal::Compare(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), absl::strings_internal::operator==(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
ToString()
template<int max_words> std::string absl::strings_internal::BigUnsigned< max_words >::ToString () const
Definition at line 339 of file charconv_bigint.cc.
{
  BigUnsigned<max_words> copy = *this;
  std::string result;
  // Build result in reverse order
  while (copy.size() > 0) {
    uint32_t next_digit = copy.DivMod<10>();
    result.push_back('0' + static_cast<char>(next_digit));
  }
  if (result.empty()) {
    result.push_back('0');
  }
  std::reverse(result.begin(), result.end());
  return result;
}
words()
template<int max_words> const uint32_t * absl::strings_internal::BigUnsigned< max_words >::words () const inline
Definition at line 218 of file charconv_bigint.h.
{ return words_; }
Referenced by absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), and absl::strings_internal::BigUnsigned< max_words >::MultiplyBy().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/charconv_bigint.h
open_spiel/abseil-cpp/absl/strings/internal/charconv_bigint.cc