open spiel: absl::str_format_internal::UntypedFormatSpecImpl Class Reference
absl::str_format_internal::UntypedFormatSpecImpl Class Reference
#include <bind.h>
Public Member Functions
UntypedFormatSpecImpl ()=delete
UntypedFormatSpecImpl (string_view s)
UntypedFormatSpecImpl (const str_format_internal::ParsedFormatBase *pc)
bool has_parsed_conversion () const
string_view str () const
const str_format_internal::ParsedFormatBase * parsed_conversion () const
Static Public Member Functions
template<typename T >
static const UntypedFormatSpecImpl & Extract (const T &s)
Detailed Description
Definition at line 47 of file bind.h.
Constructor & Destructor Documentation
UntypedFormatSpecImpl() [1/3]
absl::str_format_internal::UntypedFormatSpecImpl::UntypedFormatSpecImpl () delete
UntypedFormatSpecImpl() [2/3]
absl::str_format_internal::UntypedFormatSpecImpl::UntypedFormatSpecImpl (string_view s) inline explicit
Definition at line 51 of file bind.h.
      : data_(s.data()), size_(s.size()) {}
UntypedFormatSpecImpl() [3/3]
absl::str_format_internal::UntypedFormatSpecImpl::UntypedFormatSpecImpl (const str_format_internal::ParsedFormatBase * pc) inline explicit
Definition at line 53 of file bind.h.
      : data_(pc), size_(~size_t{}) {}
Member Function Documentation
Extract()
template<typename T > static const UntypedFormatSpecImpl & absl::str_format_internal::UntypedFormatSpecImpl::Extract (const T & s) inline static
Definition at line 69 of file bind.h.
{
    return s.spec_;
  }
References absl::s.
Referenced by absl::Format(), absl::FormatUntyped(), absl::FPrintF(), absl::PrintF(), absl::SNPrintF(), absl::StrAppendFormat(), absl::StreamFormat(), absl::StrFormat(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), and absl::ABSL_NAMESPACE_BEGIN::TEST_F().
has_parsed_conversion()
bool absl::str_format_internal::UntypedFormatSpecImpl::has_parsed_conversion () const inline
Definition at line 57 of file bind.h.
{ return size_ == ~size_t{}; }
Referenced by parsed_conversion(), and str().
parsed_conversion()
const str_format_internal::ParsedFormatBase * absl::str_format_internal::UntypedFormatSpecImpl::parsed_conversion () const inline
Definition at line 63 of file bind.h.
{
    assert(has_parsed_conversion());
    return static_cast<const str_format_internal::ParsedFormatBase*>(data_);
  }
References has_parsed_conversion().
str()
string_view absl::str_format_internal::UntypedFormatSpecImpl::str () const inline
Definition at line 59 of file bind.h.
{
    assert(!has_parsed_conversion());
    return string_view(static_cast<const char*>(data_), size_);
  }
References has_parsed_conversion().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/str_format/bind.h