open spiel: open_spiel::y_game::YState Class Reference
open_spiel::y_game::YState Class Reference
#include <y.h>
Public Member Functions
YState (std::shared_ptr< const Game > game, int board_size, bool ansi_color_output=false)
YState (const YState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
int FindGroupLeader (int cell)
bool JoinGroups (int cell_a, int cell_b)
Move ActionToMove (Action action_id) const
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 93 of file y.h.
Constructor & Destructor Documentation
YState() [1/2]
open_spiel::y_game::YState::YState (std::shared_ptr< const Game > game, int board_size, bool ansi_color_output = false)
Definition at line 118 of file y.cc.
    : State(game),
      board_size_(board_size),
      neighbors(get_neighbors(board_size)),
      ansi_color_output_(ansi_color_output) {
  board_.resize(board_size * board_size);
  for (int i = 0; i < board_.size(); i++) {
    Move m = ActionToMove(i);
    board_[i] = Cell((m.OnBoard() ? kPlayerNone : kPlayerInvalid), i,
                     m.Edge(board_size));
  }
}
References ActionToMove(), open_spiel::y_game::Move::Edge(), i, open_spiel::y_game::kPlayerInvalid, open_spiel::y_game::kPlayerNone, and open_spiel::y_game::Move::OnBoard().
Referenced by Clone().
YState() [2/2]
open_spiel::y_game::YState::YState (const YState &) default
Member Function Documentation
ActionToMove()
Move open_spiel::y_game::YState::ActionToMove (Action action_id) const protected
Definition at line 132 of file y.cc.
{
  return Move(action_id % board_size_, action_id / board_size_, board_size_);
}
Referenced by ActionToString(), DoApplyAction(), and YState().
ActionToString()
std::string open_spiel::y_game::YState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 149 of file y.cc.
{
  return ActionToMove(action_id).ToString();
}
References ActionToMove(), and open_spiel::y_game::Move::ToString().
Clone()
std::unique_ptr< State > open_spiel::y_game::YState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 325 of file y.cc.
{
  return std::unique_ptr<State>(new YState(*this));
}
References YState().
CurrentPlayer()
Player open_spiel::y_game::YState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 124 of file y.h.
{
    return IsTerminal() ? kTerminalPlayerId : static_cast<int>(current_player_);
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::y_game::YState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 269 of file y.cc.
{
  SPIEL_CHECK_EQ(board_[action].player, kPlayerNone);
  SPIEL_CHECK_EQ(outcome_, kPlayerNone);
  Move move = ActionToMove(action);
  SPIEL_CHECK_TRUE(move.OnBoard());
  last_move_ = move;
  board_[move.xy].player = current_player_;
  moves_made_++;
  for (const Move& m : neighbors[move.xy]) {
    if (m.OnBoard() && current_player_ == board_[m.xy].player) {
      JoinGroups(move.xy, m.xy);
    }
  }
  if (board_[FindGroupLeader(move.xy)].edge == 0x7) {  // ie all 3 edges.
    outcome_ = current_player_;
  }
  current_player_ = (current_player_ == kPlayer1 ? kPlayer2 : kPlayer1);
}
References action, ActionToMove(), FindGroupLeader(), JoinGroups(), open_spiel::y_game::kPlayer1, open_spiel::y_game::kPlayer2, open_spiel::y_game::kPlayerNone, player, SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
FindGroupLeader()
int open_spiel::y_game::YState::FindGroupLeader (int cell) protected
Definition at line 293 of file y.cc.
{
  int parent = board_[cell].parent;
  if (parent != cell) {
    do {  // Follow the parent chain up to the group leader.
      parent = board_[parent].parent;
    } while (parent != board_[parent].parent);
    // Do path compression, but only the current one to avoid recursion.
    board_[cell].parent = parent;
  }
  return parent;
}
Referenced by DoApplyAction(), and JoinGroups().
InformationStateString()
std::string open_spiel::y_game::YState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 231 of file y.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::y_game::YState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 129 of file y.h.
{ return outcome_ != kPlayerNone; }
References open_spiel::y_game::kPlayerNone.
Referenced by CurrentPlayer(), and LegalActions().
JoinGroups()
bool open_spiel::y_game::YState::JoinGroups (int cell_a, int cell_b) protected
Definition at line 305 of file y.cc.
{
  int leader_a = FindGroupLeader(cell_a);
  int leader_b = FindGroupLeader(cell_b);
  if (leader_a == leader_b)  // Already the same group.
    return true;
  if (board_[leader_a].size < board_[leader_b].size) {
    // Force group a's subtree to be bigger.
    std::swap(leader_a, leader_b);
  }
  // Group b joins group a.
  board_[leader_b].parent = leader_a;
  board_[leader_a].size += board_[leader_b].size;
  board_[leader_a].edge |= board_[leader_b].edge;
  return false;
}
References FindGroupLeader(), and size.
Referenced by DoApplyAction().
LegalActions()
std::vector< Action > open_spiel::y_game::YState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 136 of file y.cc.
{
  // Can move in any empty cell.
  std::vector<Action> moves;
  if (IsTerminal()) return moves;
  moves.reserve(board_.size() - moves_made_);
  for (int cell = 0; cell < board_.size(); ++cell) {
    if (board_[cell].player == kPlayerNone) {
      moves.push_back(cell);
    }
  }
  return moves;
}
References IsTerminal(), open_spiel::y_game::kPlayerNone, and player.
ObservationString()
std::string open_spiel::y_game::YState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 237 of file y.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::y_game::YState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 256 of file y.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<2> view(values, {kCellStates, static_cast<int>(board_.size())},
                     true);
  for (int i = 0; i < board_.size(); ++i) {
    if (board_[i].player != kPlayerInvalid) {
      view[{PlayerRelative(board_[i].player, player), i}] = 1.0;
    }
  }
}
References i, open_spiel::y_game::kCellStates, open_spiel::y_game::kPlayerInvalid, open_spiel::State::num_players_, player, open_spiel::y_game::PlayerRelative(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::y_game::YState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 225 of file y.cc.
{
  if (outcome_ == kPlayer1) return {1, -1};
  if (outcome_ == kPlayer2) return {-1, 1};
  return {0, 0};  // Unfinished
}
References open_spiel::y_game::kPlayer1, and open_spiel::y_game::kPlayer2.
ToString()
std::string open_spiel::y_game::YState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 153 of file y.cc.
{
  // Generates something like:
  //  a b c d e f g h i j k
  // 1 O @ O O . @ @ O O @ O
  //  2 . O O . O @ @ . O O
  //   3 . O @ @ O @ O O @
  //    4 O O . @ . @ O O
  //     5 . . . @[@]@ O
  //      6 @ @ @ O O @
  //       7 @ . O @ O
  //        8 . @ @ O
  //         9 @ @ .
  //         10 O .
  //          11 @
  std::string white = "O";
  std::string black = "@";
  std::string empty = ".";
  std::string coord = "";
  std::string reset = "";
  if (ansi_color_output_) {
    std::string esc = "\033";
    reset = esc + "[0m";
    coord = esc + "[1;37m";  // bright white
    empty = reset + ".";
    white = esc + "[1;33m" + "@";  // bright yellow
    black = esc + "[1;34m" + "@";  // bright blue
  }
  std::ostringstream out;
  // Top x coords.
  out << ' ';
  for (int x = 0; x < board_size_; x++) {
    out << ' ' << coord << static_cast<char>('a' + x);
  }
  out << '\n';
  for (int y = 0; y < board_size_; y++) {
    out << std::string(y + ((y + 1) < 10), ' ');  // Leading space.
    out << coord << (y + 1);                      // Leading y coord.
    bool found_last = false;
    for (int x = 0; x < board_size_ - y; x++) {
      Move pos(x, y, board_size_);
      // Spacing and last-move highlight.
      if (found_last) {
        out << coord << ']';
        found_last = false;
      } else if (last_move_ == pos) {
        out << coord << '[';
        found_last = true;
      } else {
        out << ' ';
      }
      // Actual piece.
      Player p = board_[pos.xy].player;
      if (p == kPlayerNone) out << empty;
      if (p == kPlayer1) out << white;
      if (p == kPlayer2) out << black;
    }
    if (found_last) {
      out << coord << ']';
    }
    out << '\n';
  }
  out << reset;
  return out.str();
}
References open_spiel::y_game::kPlayer1, open_spiel::y_game::kPlayer2, open_spiel::y_game::kPlayerNone, out, x, and y.
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/y/y.h
open_spiel/games/y/y.cc