open spiel: absl::cordrep_testing::AutoUnref Class Reference
absl::cordrep_testing::AutoUnref Class Reference
#include <cord_rep_test_util.h>
Public Member Functions
~AutoUnref ()
template<typename CordRepType >
CordRepType * Add (CordRepType *rep)
template<typename CordRepType >
CordRepType * Ref (CordRepType *rep)
template<typename CordRepType >
CordRepType * RefIf (bool condition, CordRepType *rep)
Detailed Description
Definition at line 166 of file cord_rep_test_util.h.
Constructor & Destructor Documentation
~AutoUnref()
absl::cordrep_testing::AutoUnref::~AutoUnref () inline
Definition at line 168 of file cord_rep_test_util.h.
               {
    for (CordRep* rep : unrefs_) CordRep::Unref(rep);
  }
References rep, and absl::cord_internal::CordRep::Unref().
Member Function Documentation
Add()
template<typename CordRepType > CordRepType * absl::cordrep_testing::AutoUnref::Add (CordRepType * rep) inline
Definition at line 174 of file cord_rep_test_util.h.
{
    unrefs_.push_back(rep);
    return rep;
  }
References rep.
Ref()
template<typename CordRepType > CordRepType * absl::cordrep_testing::AutoUnref::Ref (CordRepType * rep) inline
Definition at line 182 of file cord_rep_test_util.h.
{
    unrefs_.push_back(CordRep::Ref(rep));
    return rep;
  }
References absl::cord_internal::CordRep::Ref(), and rep.
RefIf()
template<typename CordRepType > CordRepType * absl::cordrep_testing::AutoUnref::RefIf (bool condition, CordRepType * rep) inline
Definition at line 190 of file cord_rep_test_util.h.
{
    if (condition) unrefs_.push_back(CordRep::Ref(rep));
    return rep;
  }
References absl::cord_internal::CordRep::Ref(), and rep.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_test_util.h