open spiel: open_spiel::markov_soccer::MarkovSoccerState Class Reference
open_spiel::markov_soccer::MarkovSoccerState Class Reference
#include <markov_soccer.h>
Public Member Functions
MarkovSoccerState (std::shared_ptr< const Game > game, const Grid &grid)
MarkovSoccerState (const MarkovSoccerState &)=default
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
Player CurrentPlayer () const override
std::unique_ptr< State > Clone () const override
ActionsAndProbs ChanceOutcomes () const override
void Reset (int horizon)
std::vector< Action > LegalActions (Player player) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &moves) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 66 of file markov_soccer.h.
Constructor & Destructor Documentation
MarkovSoccerState() [1/2]
open_spiel::markov_soccer::MarkovSoccerState::MarkovSoccerState (std::shared_ptr< const Game > game, const Grid & grid) explicit
Definition at line 89 of file markov_soccer.cc.
    : SimMoveState(game), grid_(grid) {}
Referenced by Clone().
MarkovSoccerState() [2/2]
open_spiel::markov_soccer::MarkovSoccerState::MarkovSoccerState (const MarkovSoccerState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::markov_soccer::MarkovSoccerState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 93 of file markov_soccer.cc.
{
  if (player == kSimultaneousPlayerId)
    return FlatJointActionToString(action_id);
  SPIEL_CHECK_GE(action_id, 0);
  std::string result = "";
  if (player == kChancePlayerId) {
    SPIEL_CHECK_LT(action_id, game_->MaxChanceOutcomes());
    // Chance moves.
    if (action_id == kChanceInit0Action) {
      result = "(A's action first)";
    } else if (action_id == kChanceInit1Action) {
      result = "(B's action first)";
    } else {
      int ball_loc = action_id - kNumInitiativeChanceOutcomes;
      return absl::StrCat("(ball at ", grid_.ball_start_points[ball_loc].first,
                          ",", grid_.ball_start_points[ball_loc].second, ")");
    }
  } else {
    SPIEL_CHECK_LT(action_id, game_->NumDistinctActions());
    // Regular move actions.
    if (action_id == kUp) {
      result = "up";
    } else if (action_id == kDown) {
      result = "down";
    } else if (action_id == kLeft) {
      result = "left";
    } else if (action_id == kRight) {
      result = "right";
    } else if (action_id == kStand) {
      result = "stand";
    }
  }
  return result;
}
References open_spiel::markov_soccer::Grid::ball_start_points, open_spiel::SimMoveState::FlatJointActionToString(), open_spiel::State::game_, open_spiel::markov_soccer::kChanceInit0Action, open_spiel::markov_soccer::kChanceInit1Action, open_spiel::kChancePlayerId, open_spiel::markov_soccer::kNumInitiativeChanceOutcomes, open_spiel::kSimultaneousPlayerId, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::markov_soccer::MarkovSoccerState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 282 of file markov_soccer.cc.
          {
  SPIEL_CHECK_TRUE(IsChanceNode());
  if (total_moves_ == 0) {
    std::vector<std::pair<Action, double>> outcomes(
        grid_.ball_start_points.size(), {kInvalidAction, -1.0});
    const double unif_prob = 1.0 / outcomes.size();
    for (int i = 0; i < grid_.ball_start_points.size(); ++i) {
      outcomes[i] = {kNumInitiativeChanceOutcomes + i, unif_prob};
    }
    return outcomes;
  } else {
    return {
        std::pair<Action, double>(ToAction(ChanceOutcome::kChanceInit0), 0.5),
        std::pair<Action, double>(ToAction(ChanceOutcome::kChanceInit1), 0.5)};
  }
}
References open_spiel::markov_soccer::Grid::ball_start_points, i, open_spiel::State::IsChanceNode(), open_spiel::markov_soccer::kChanceInit0, open_spiel::markov_soccer::kChanceInit1, open_spiel::markov_soccer::kNumInitiativeChanceOutcomes, and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::markov_soccer::MarkovSoccerState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 378 of file markov_soccer.cc.
{
  return std::unique_ptr<State>(new MarkovSoccerState(*this));
}
References MarkovSoccerState().
CurrentPlayer()
Player open_spiel::markov_soccer::MarkovSoccerState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 83 of file markov_soccer.h.
{
    return IsTerminal() ? kTerminalPlayerId : cur_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::markov_soccer::MarkovSoccerState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 238 of file markov_soccer.cc.
{
  if (IsSimultaneousNode()) {
    ApplyFlatJointAction(action_id);
    return;
  }
  SPIEL_CHECK_TRUE(IsChanceNode());
  SPIEL_CHECK_GE(action_id, 0);
  SPIEL_CHECK_LT(action_id, game_->MaxChanceOutcomes());
  if (action_id == kChanceInit0Action) {
    ResolveMove(1, moves_[0]);
    ResolveMove(2, moves_[1]);
  } else if (action_id == kChanceInit1Action) {
    ResolveMove(2, moves_[1]);
    ResolveMove(1, moves_[0]);
  } else {
    int ball_loc = action_id - kNumInitiativeChanceOutcomes;
    SetField(grid_.ball_start_points[ball_loc].first,
             grid_.ball_start_points[ball_loc].second, 'O');
  }
  cur_player_ = kSimultaneousPlayerId;
  total_moves_++;
}
References open_spiel::SimMoveState::ApplyFlatJointAction(), open_spiel::markov_soccer::Grid::ball_start_points, open_spiel::State::game_, open_spiel::State::IsChanceNode(), open_spiel::State::IsSimultaneousNode(), open_spiel::markov_soccer::kChanceInit0Action, open_spiel::markov_soccer::kChanceInit1Action, open_spiel::markov_soccer::kNumInitiativeChanceOutcomes, open_spiel::kSimultaneousPlayerId, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and SPIEL_CHECK_TRUE.
DoApplyActions()
void open_spiel::markov_soccer::MarkovSoccerState::DoApplyActions (const std::vector< Action > & moves) override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 165 of file markov_soccer.cc.
{
  SPIEL_CHECK_EQ(moves.size(), 2);
  SPIEL_CHECK_EQ(cur_player_, kSimultaneousPlayerId);
  moves_[0] = moves[0];
  moves_[1] = moves[1];
  cur_player_ = kChancePlayerId;
}
References open_spiel::kChancePlayerId, open_spiel::kSimultaneousPlayerId, and SPIEL_CHECK_EQ.
IsTerminal()
bool open_spiel::markov_soccer::MarkovSoccerState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 314 of file markov_soccer.cc.
{
  return (total_moves_ >= horizon_ || winner_ != kInvalidPlayer);
}
References open_spiel::kInvalidPlayer.
Referenced by CurrentPlayer(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::markov_soccer::MarkovSoccerState::LegalActions (Player player) const override virtual
Implements open_spiel::SimMoveState.
Definition at line 263 of file markov_soccer.cc.
{
  if (IsTerminal()) return {};
  if (IsChanceNode()) {
    if (total_moves_ == 0) {
      std::vector<Action> outcomes(grid_.ball_start_points.size(),
                                   kInvalidAction);
      for (int i = 0; i < grid_.ball_start_points.size(); ++i) {
        outcomes[i] = kNumInitiativeChanceOutcomes + i;
      }
      return outcomes;
    } else {
      return {ToAction(ChanceOutcome::kChanceInit0),
              ToAction(ChanceOutcome::kChanceInit1)};
    }
  } else {
    return {kUp, kDown, kLeft, kRight, kStand};
  }
}
References open_spiel::markov_soccer::Grid::ball_start_points, i, open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::markov_soccer::kChanceInit0, open_spiel::markov_soccer::kChanceInit1, open_spiel::kInvalidAction, and open_spiel::markov_soccer::kNumInitiativeChanceOutcomes.
ObservationString()
std::string open_spiel::markov_soccer::MarkovSoccerState::ObservationString (Player player) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 76 of file markov_soccer.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, num_players_);
    return ToString();
  }
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::markov_soccer::MarkovSoccerState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 361 of file markov_soccer.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<3> view(values, {kCellStates, grid_.num_rows, grid_.num_cols},
                     true);
  for (int r = 0; r < grid_.num_rows; r++) {
    for (int c = 0; c < grid_.num_cols; c++) {
      int plane = observation_plane(r, c);
      SPIEL_CHECK_TRUE(plane >= 0 && plane < kCellStates);
      view[{plane, r, c}] = 1.0;
    }
  }
}
References open_spiel::markov_soccer::Grid::num_cols, open_spiel::State::num_players_, open_spiel::markov_soccer::Grid::num_rows, player, r, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, and values.
Reset()
void open_spiel::markov_soccer::MarkovSoccerState::Reset (int horizon)
Definition at line 153 of file markov_soccer.cc.
{
  horizon_ = horizon;
  field_.resize(grid_.num_rows * grid_.num_cols, '.');
  SetField(grid_.a_start.first, grid_.a_start.second, 'a');
  SetField(grid_.b_start.first, grid_.b_start.second, 'b');
  cur_player_ = kChancePlayerId;
  winner_ = kInvalidPlayer;
  total_moves_ = 0;
}
References open_spiel::markov_soccer::Grid::a_start, open_spiel::markov_soccer::Grid::b_start, open_spiel::kChancePlayerId, open_spiel::kInvalidPlayer, open_spiel::markov_soccer::Grid::num_cols, and open_spiel::markov_soccer::Grid::num_rows.
Returns()
std::vector< double > open_spiel::markov_soccer::MarkovSoccerState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 318 of file markov_soccer.cc.
{
  if (!IsTerminal()) {
    return {0.0, 0.0};
  }
  if (total_moves_ >= horizon_) {
    return {0.0, 0.0};
  } else {
    return (winner_ == 0) ? std::vector<double>{1.0, -1.0}
                          : std::vector<double>{-1.0, 1.0};
  }
}
References IsTerminal().
ToString()
std::string open_spiel::markov_soccer::MarkovSoccerState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 300 of file markov_soccer.cc.
{
  std::string result = "";
  for (int r = 0; r < grid_.num_rows; r++) {
    for (int c = 0; c < grid_.num_cols; c++) {
      result += field(r, c);
    }
    absl::StrAppend(&result, "\n");
  }
  if (IsChanceNode()) absl::StrAppend(&result, "Chance Node");
  return result;
}
References open_spiel::State::IsChanceNode(), open_spiel::markov_soccer::Grid::num_cols, open_spiel::markov_soccer::Grid::num_rows, r, and absl::StrAppend().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/markov_soccer/markov_soccer.h
open_spiel/games/markov_soccer/markov_soccer.cc