open spiel: absl::flags_internal::FlagImplPeer Class Reference
absl::flags_internal::FlagImplPeer Class Reference
#include <flag.h>
Static Public Member Functions
template<typename T , typename FlagType >
static T InvokeGet (const FlagType &flag)
template<typename FlagType , typename T >
static void InvokeSet (FlagType &flag, const T &v)
template<typename FlagType >
static const CommandLineFlag & InvokeReflect (const FlagType &f)
Detailed Description
Definition at line 698 of file flag.h.
Member Function Documentation
InvokeGet()
template<typename T , typename FlagType > static T absl::flags_internal::FlagImplPeer::InvokeGet (const FlagType & flag) inline static
Definition at line 701 of file flag.h.
{
    return flag.Get();
  }
Referenced by absl::GetFlag().
InvokeReflect()
template<typename FlagType > static const CommandLineFlag & absl::flags_internal::FlagImplPeer::InvokeReflect (const FlagType & f) inline static
Definition at line 709 of file flag.h.
{
    return f.Reflect();
  }
References absl::f.
Referenced by absl::GetFlagReflectionHandle().
InvokeSet()
template<typename FlagType , typename T > static void absl::flags_internal::FlagImplPeer::InvokeSet (FlagType & flag, const T & v) inline static
Definition at line 705 of file flag.h.
{
    flag.Set(v);
  }
References absl::v.
Referenced by absl::SetFlag(), and absl::SetFlag().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/flags/internal/flag.h