open spiel: absl::zipf_distribution< IntType >::param_type Class Reference
absl::zipf_distribution< IntType >::param_type Class Reference
#include <zipf_distribution.h>
Public Types
using distribution_type = zipf_distribution
Public Member Functions
param_type (result_type k=(std::numeric_limits< IntType >::max)(), double q=2.0, double v=1.0)
result_type k () const
double q () const
double v () const
Friends
class zipf_distribution
bool operator== (const param_type &a, const param_type &b)
bool operator!= (const param_type &a, const param_type &b)
Detailed Description
template<typename IntType = int>
class absl::zipf_distribution< IntType >::param_type
Definition at line 56 of file zipf_distribution.h.
Member Typedef Documentation
distribution_type
template<typename IntType = int> using absl::zipf_distribution< IntType >::param_type::distribution_type = zipf_distribution
Definition at line 58 of file zipf_distribution.h.
Constructor & Destructor Documentation
param_type()
template<typename IntType = int> absl::zipf_distribution< IntType >::param_type::param_type (result_type k = (std::numeric_limits<IntType>::max)(), double q = 2.0, double v = 1.0) explicit
Definition at line 150 of file zipf_distribution.h.
    : k_(k), q_(q), v_(v), one_minus_q_(1 - q) {
  assert(q > 1);
  assert(v > 0);
  assert(k > 0);
  one_minus_q_inv_ = 1 / one_minus_q_;
  // Setup for the ZRI algorithm (pg 17 of the paper).
  // Compute: h(i max) => h(k + 0.5)
  constexpr double kMax = 18446744073709549568.0;
  double kd = static_cast<double>(k);
  // TODO(absl-team): Determine if this check is needed, and if so, add a test
  // that fails for k > kMax
  if (kd > kMax) {
    // Ensure that our maximum value is capped to a value which will
    // round-trip back through double.
    kd = kMax;
  }
  hxm_ = h(kd + 0.5);
  // Compute: h(0)
  const bool use_precomputed = (v == 1.0 && q == 2.0);
  const double h0x5 = use_precomputed ? (-1.0 / 1.5)  // exp(-log(1.5))
                                      : h(0.5);
  const double elogv_q = (v_ == 1.0) ? 1 : pow_negative_q(v_);
  // h(0) = h(0.5) - exp(log(v) * -q)
  hx0_minus_hxm_ = (h0x5 - elogv_q) - hxm_;
  // And s
  s_ = use_precomputed ? 0.46153846153846123 : compute_s();
}
References absl::zipf_distribution< IntType >::param_type::k(), absl::zipf_distribution< IntType >::param_type::q(), and absl::zipf_distribution< IntType >::param_type::v().
Member Function Documentation
k()
template<typename IntType = int> result_type absl::zipf_distribution< IntType >::param_type::k () const inline
Definition at line 68 of file zipf_distribution.h.
{ return k_; }
Referenced by absl::zipf_distribution< IntType >::k(), and absl::zipf_distribution< IntType >::param_type::param_type().
q()
template<typename IntType = int> double absl::zipf_distribution< IntType >::param_type::q () const inline
Definition at line 69 of file zipf_distribution.h.
{ return q_; }
Referenced by absl::zipf_distribution< IntType >::param_type::param_type(), and absl::zipf_distribution< IntType >::q().
v()
template<typename IntType = int> double absl::zipf_distribution< IntType >::param_type::v () const inline
Definition at line 70 of file zipf_distribution.h.
{ return v_; }
Referenced by absl::zipf_distribution< IntType >::param_type::param_type(), and absl::zipf_distribution< IntType >::v().
Friends And Related Symbol Documentation
operator!=
template<typename IntType = int> bool operator!= (const param_type & a, const param_type & b) friend
Definition at line 75 of file zipf_distribution.h.
{
      return !(a == b);
    }
operator==
template<typename IntType = int> bool operator== (const param_type & a, const param_type & b) friend
Definition at line 72 of file zipf_distribution.h.
{
      return a.k_ == b.k_ && a.q_ == b.q_ && a.v_ == b.v_;
    }
zipf_distribution
template<typename IntType = int> friend class zipf_distribution friend
Definition at line 80 of file zipf_distribution.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/zipf_distribution.h