open spiel: TimeStatList Class Reference
TimeStatList Class Reference
#include <TimeStatList.h>
Public Member Functions
TimeStatList ()
~TimeStatList ()
void Reset ()
void Init (const string &tname, const unsigned len)
void Add (const unsigned pos, const TimeStat &add)
bool Used () const
string List () const
Detailed Description
Definition at line 21 of file TimeStatList.h.
Constructor & Destructor Documentation
TimeStatList()
TimeStatList::TimeStatList ()
Definition at line 18 of file TimeStatList.cpp.
{
  TimeStatList::Reset();
}
References Reset().
~TimeStatList()
TimeStatList::~TimeStatList ()
Definition at line 24 of file TimeStatList.cpp.
{
}
Member Function Documentation
Add()
void TimeStatList::Add (const unsigned pos, const TimeStat & add)
Definition at line 43 of file TimeStatList.cpp.
{
  list[pos] += add;
}
Init()
void TimeStatList::Init (const string & tname, const unsigned len)
Definition at line 34 of file TimeStatList.cpp.
{
  name = tname;
  list.resize(len);
}
References len.
List()
string TimeStatList::List () const
Definition at line 62 of file TimeStatList.cpp.
{
  if (! TimeStatList::Used())
    return "";
  stringstream ss;
  ss << name << "\n\n";
  ss << list[0].Header();
  TimeStat tsum;
  for (unsigned i = 0; i < list.size(); i++)
  {
    if (! list[i].Used())
      continue;
    tsum += list[i];
    ss << setw(5) << right << i << list[i].Line();
  }
  ss << setw(5) << right << "Avg" << tsum.Line() << "\n";
  return ss.str();
}
References i, TimeStat::Line(), and Used().
Reset()
void TimeStatList::Reset ()
Definition at line 29 of file TimeStatList.cpp.
{
}
Referenced by TimeStatList().
Used()
bool TimeStatList::Used () const
Definition at line 51 of file TimeStatList.cpp.
{
  for (unsigned i = 0; i < list.size(); i++)
  {
    if (list[i].Used())
      return true;
  }
  return false;
}
References i, and Used().
Referenced by List(), and Used().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/TimeStatList.h
open_spiel/games/bridge/double_dummy_solver/src/TimeStatList.cpp