open spiel: open_spiel::breakthrough::BreakthroughGame Class Reference
open_spiel::breakthrough::BreakthroughGame Class Reference
#include <breakthrough.h>
Public Member Functions
BreakthroughGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 92 of file breakthrough.h.
Constructor & Destructor Documentation
BreakthroughGame()
open_spiel::breakthrough::BreakthroughGame::BreakthroughGame (const GameParameters & params) explicit
Definition at line 383 of file breakthrough.cc.
    : Game(kGameType, params),
      rows_(ParameterValue<int>("rows")),
      cols_(ParameterValue<int>("columns")) {}
Member Function Documentation
DeserializeState()
std::unique_ptr< State > open_spiel::breakthrough::BreakthroughGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 402 of file breakthrough.cc.
{
  std::unique_ptr<State> state = NewInitialState();
  if (str.length() != rows_ * cols_) {
    SpielFatalError("Incorrect number of characters in string.");
    return std::unique_ptr<State>();
  }
  BreakthroughState* bstate = dynamic_cast<BreakthroughState*>(state.get());
  bstate->SetPieces(0, 0);
  bstate->SetPieces(1, 0);
  int i = 0;
  for (int r = 0; r < rows_; r++) {
    for (int c = 0; c < cols_; c++) {
      if (str.at(i) == 'b') {
        bstate->SetPieces(0, bstate->pieces(0) + 1);
        bstate->SetBoard(r, c, CellState::kBlack);
      } else if (str.at(i) == 'w') {
        bstate->SetPieces(1, bstate->pieces(1) + 1);
        bstate->SetBoard(r, c, CellState::kWhite);
      } else if (str.at(i) == '.') {
        bstate->SetBoard(r, c, CellState::kEmpty);
      } else {
        std::string error = "Invalid character in std::string: ";
        error += str.at(i);
        SpielFatalError(error);
        return std::unique_ptr<State>();
      }
      i++;
    }
  }
  return state;
}
References i, open_spiel::breakthrough::kBlack, open_spiel::breakthrough::kEmpty, open_spiel::breakthrough::kWhite, NewInitialState(), open_spiel::breakthrough::BreakthroughState::pieces(), r, open_spiel::breakthrough::BreakthroughState::SetBoard(), open_spiel::breakthrough::BreakthroughState::SetPieces(), open_spiel::SpielFatalError(), and state.
MaxGameLength()
int open_spiel::breakthrough::BreakthroughGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 113 of file breakthrough.h.
{
    return (2 * (2 * rows_ - 3) * cols_) + 1;
  }
MaxUtility()
double open_spiel::breakthrough::BreakthroughGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 103 of file breakthrough.h.
{ return 1; }
MinUtility()
double open_spiel::breakthrough::BreakthroughGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 101 of file breakthrough.h.
{ return -1; }
NewInitialState()
std::unique_ptr< State > open_spiel::breakthrough::BreakthroughGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 96 of file breakthrough.h.
{
    return std::unique_ptr<State>(
        new BreakthroughState(shared_from_this(), rows_, cols_));
  }
Referenced by DeserializeState().
NumDistinctActions()
int open_spiel::breakthrough::BreakthroughGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 388 of file breakthrough.cc.
{
  return rows_ * cols_ * kNumDirections * 2;
}
NumPlayers()
int open_spiel::breakthrough::BreakthroughGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 100 of file breakthrough.h.
{ return kNumPlayers; }
References open_spiel::breakthrough::kNumPlayers.
ObservationTensorShape()
std::vector< int > open_spiel::breakthrough::BreakthroughGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 104 of file breakthrough.h.
{
    return {kCellStates, rows_, cols_};
  }
References open_spiel::breakthrough::kCellStates.
UtilitySum()
absl::optional< double > open_spiel::breakthrough::BreakthroughGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 102 of file breakthrough.h.
{ return 0; }
The documentation for this class was generated from the following files:
open_spiel/games/breakthrough/breakthrough.h
open_spiel/games/breakthrough/breakthrough.cc