open spiel: open_spiel::PyBot< BotBase > Class Template Reference
open_spiel::PyBot< BotBase > Class Template Reference
#include <pybind11.h>
Public Member Functions
~PyBot () override=default
open_spiel::Action Step (const State &state) override
void Restart () override
bool ProvidesForceAction () override
void ForceAction (const State &state, Action action) override
void InformAction (const State &state, Player player_id, Action action) override
void InformActions (const State &state, const std::vector< Action > &actions) override
void RestartAt (const State &state) override
bool ProvidesPolicy () override
ActionsAndProbs GetPolicy (const State &state) override
std::pair< ActionsAndProbs, Action > StepWithPolicy (const State &state) override
bool IsClonable () const override
std::unique_ptr< Bot > Clone () override
Public Member Functions inherited from open_spiel::Bot
virtual ~Bot ()=default
Detailed Description
template<class BotBase = Bot>
class open_spiel::PyBot< BotBase >
Definition at line 91 of file pybind11.h.
Constructor & Destructor Documentation
~PyBot()
template<class BotBase = Bot> open_spiel::PyBot< BotBase >::~PyBot () override default
Member Function Documentation
Clone()
template<class BotBase = Bot> std::unique_ptr< Bot > open_spiel::PyBot< BotBase >::Clone () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 205 of file pybind11.h.
{
    using BotUniquePtr = std::unique_ptr<Bot>;
    PYBIND11_OVERLOAD_NAME(
        BotUniquePtr,  // Return type (must be a simple token for macro parser)
        BotBase,       // Parent class
        "clone",       // Name of function in Python
        Clone,         // Name of function in C++
    );
  }
References open_spiel::PyBot< BotBase >::Clone().
Referenced by open_spiel::PyBot< BotBase >::Clone().
ForceAction()
template<class BotBase = Bot> void open_spiel::PyBot< BotBase >::ForceAction (const State & state, Action action) inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 128 of file pybind11.h.
{
    PYBIND11_OVERLOAD_NAME(
        void,     // Return type (must be a simple token for macro parser)
        BotBase,  // Parent class
        "force_action",  // Name of function in Python
        ForceAction,     // Name of function in C++
        state,           // Arguments
        action);
  }
References action, open_spiel::PyBot< BotBase >::ForceAction(), and state.
Referenced by open_spiel::PyBot< BotBase >::ForceAction().
GetPolicy()
template<class BotBase = Bot> ActionsAndProbs open_spiel::PyBot< BotBase >::GetPolicy (const State & state) inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 176 of file pybind11.h.
{
    PYBIND11_OVERLOAD_NAME(ActionsAndProbs,  // Return type (must be a simple
                                             // token for macro parser)
                           BotBase,          // Parent class
                           "get_policy",     // Name of function in Python
                           GetPolicy,        // Name of function in C++
                           state);
  }
References open_spiel::PyBot< BotBase >::GetPolicy(), and state.
Referenced by open_spiel::PyBot< BotBase >::GetPolicy().
InformAction()
template<class BotBase = Bot> void open_spiel::PyBot< BotBase >::InformAction (const State & state, Player player_id, Action action) inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 137 of file pybind11.h.
{
    PYBIND11_OVERLOAD_NAME(
        void,     // Return type (must be a simple token for macro parser)
        BotBase,  // Parent class
        "inform_action",  // Name of function in Python
        InformAction,     // Name of function in C++
        state,            // Arguments
        player_id, action);
  }
References action, open_spiel::PyBot< BotBase >::InformAction(), and state.
Referenced by open_spiel::PyBot< BotBase >::InformAction().
InformActions()
template<class BotBase = Bot> void open_spiel::PyBot< BotBase >::InformActions (const State & state, const std::vector< Action > & actions) inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 147 of file pybind11.h.
{
    PYBIND11_OVERLOAD_NAME(
        void,     // Return type (must be a simple token for macro parser)
        BotBase,  // Parent class
        "inform_actions",  // Name of function in Python
        InformActions,     // Name of function in C++
        state,             // Arguments
        actions);
  }
References open_spiel::PyBot< BotBase >::InformActions(), and state.
Referenced by open_spiel::PyBot< BotBase >::InformActions().
IsClonable()
template<class BotBase = Bot> bool open_spiel::PyBot< BotBase >::IsClonable () const inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 196 of file pybind11.h.
{
    PYBIND11_OVERLOAD_NAME(
        bool,           // Return type (must be a simple token for macro parser)
        BotBase,        // Parent class
        "is_clonable",  // Name of function in Python
        IsClonable,     // Name of function in C++
    );
  }
References open_spiel::PyBot< BotBase >::IsClonable().
Referenced by open_spiel::PyBot< BotBase >::IsClonable().
ProvidesForceAction()
template<class BotBase = Bot> bool open_spiel::PyBot< BotBase >::ProvidesForceAction () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 119 of file pybind11.h.
{
    PYBIND11_OVERLOAD_NAME(
        bool,     // Return type (must be a simple token for macro parser)
        BotBase,  // Parent class
        "provides_force_action",  // Name of function in Python
        ProvidesForceAction,      // Name of function in C++
                                  // Arguments
    );
  }
References open_spiel::PyBot< BotBase >::ProvidesForceAction().
Referenced by open_spiel::PyBot< BotBase >::ProvidesForceAction().
ProvidesPolicy()
template<class BotBase = Bot> bool open_spiel::PyBot< BotBase >::ProvidesPolicy () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 167 of file pybind11.h.
{
    PYBIND11_OVERLOAD_NAME(
        bool,     // Return type (must be a simple token for macro parser)
        BotBase,  // Parent class
        "provides_policy",  // Name of function in Python
        ProvidesPolicy,     // Name of function in C++
                            // Arguments
    );
  }
References open_spiel::PyBot< BotBase >::ProvidesPolicy().
Referenced by open_spiel::PyBot< BotBase >::ProvidesPolicy().
Restart()
template<class BotBase = Bot> void open_spiel::PyBot< BotBase >::Restart () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 110 of file pybind11.h.
{
    PYBIND11_OVERLOAD_NAME(
        void,       // Return type (must be a simple token for macro parser)
        BotBase,    // Parent class
        "restart",  // Name of function in Python
        Restart,    // Name of function in C++
        // The trailing coma after Restart is necessary to say "No argument"
    );
  }
References open_spiel::PyBot< BotBase >::Restart().
Referenced by open_spiel::PyBot< BotBase >::Restart().
RestartAt()
template<class BotBase = Bot> void open_spiel::PyBot< BotBase >::RestartAt (const State & state) inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 158 of file pybind11.h.
{
    PYBIND11_OVERLOAD_NAME(
        void,          // Return type (must be a simple token for macro parser)
        BotBase,       // Parent class
        "restart_at",  // Name of function in Python
        RestartAt,     // Name of function in C++
        state          // Arguments
    );
  }
References open_spiel::PyBot< BotBase >::RestartAt(), and state.
Referenced by open_spiel::PyBot< BotBase >::RestartAt().
Step()
template<class BotBase = Bot> open_spiel::Action open_spiel::PyBot< BotBase >::Step (const State & state) inline override virtual
Implements open_spiel::Bot.
Definition at line 99 of file pybind11.h.
{
    PYBIND11_OVERLOAD_PURE_NAME(
        open_spiel::Action,  // Return type (must be simple token)
        BotBase,             // Parent class
        "step",              // Name of function in Python
        Step,                // Name of function in C++
        state                // Arguments
    );
  }
References state, and open_spiel::PyBot< BotBase >::Step().
Referenced by open_spiel::PyBot< BotBase >::Step().
StepWithPolicy()
template<class BotBase = Bot> std::pair< ActionsAndProbs, Action > open_spiel::PyBot< BotBase >::StepWithPolicy (const State & state) inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 184 of file pybind11.h.
{
    using step_retval_t = std::pair<ActionsAndProbs, open_spiel::Action>;
    PYBIND11_OVERLOAD_NAME(
        step_retval_t,  // Return type (must be a simple token for macro parser)
        BotBase,        // Parent class
        "step_with_policy",  // Name of function in Python
        StepWithPolicy,      // Name of function in C++
        state                // Arguments
    );
  }
References state, and open_spiel::PyBot< BotBase >::StepWithPolicy().
Referenced by open_spiel::PyBot< BotBase >::StepWithPolicy().
The documentation for this class was generated from the following file:
open_spiel/python/pybind11/pybind11.h