open spiel: open_spiel::baseT::baseTState Class Reference
open_spiel::baseT::baseTState Class Reference
#include <baseT.h>
Public Member Functions
baseTState (std::shared_ptr< const Game > game)
baseTState (const baseTState &)=default
virtual ~baseTState ()
virtual baseTState & operator= (const baseTState &)=default
virtual std::string ActionToString (Player player, Action action_id) const override
virtual Player CurrentPlayer () const override
virtual bool IsTerminal () const override
virtual std::vector< Action > LegalActions () const override
virtual std::vector< double > Returns () const
virtual std::string ToString () const override
virtual std::unique_ptr< State > Clone () const override
virtual std::string ObservationString (Player player) const override
virtual void set_next_unit_to_action ()
void deploy_unit (int player_id, bool is_alive, int shift_dstc, int atk_dstc, int vw_dstc, float hp, float power, UnitClass unit_class, MapCoord crd, std::string name)
UnitActionState CurrentUAS () const
PlayerActionState CurrentPAS () const
int CurrentUniqueUnitId () const
int CurrentUnitId () const
void SetNextUAS ()
void SetNextPAS ()
void SetNextPlayer ()
void ObservationTensorBaseT (Player player)
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
virtual void DoApplyAction (Action move) override
virtual int action_select_tile (int pn, int unit_id, MapCoord tg_crd, bool is_init)
virtual void scout (int pn, int unit_id, ObsRefCount o_r_c)
virtual void init_first (int max_u, int piece_tn, int last_mn, int supply_n, int land_channel_d, UnitSelectionOrder uso, MapCoord ms, UnitActionKind game_uak)
virtual std::string get_cell_observation_string (MapState state, MapCoord crd, int p) const
virtual std::string get_set_error (std::string log, bool is_save)
virtual MapCoord id_to_crd (Action a)
virtual Action crd_to_id (MapCoord crd)
int ObservationTensorBaseT_Land (Player player, int last_index)
virtual void set_next_unit_to_action_rand_all_p ()
virtual void set_next_unit_to_action_rand_per_p ()
Unit & get_unit_by_uniqueId (int unique_id)
virtual void ObservationTensor (Player player, absl::Span< float > values) const
void set_cell_and_obs (struct Cell_set_flags flags, struct Cell cell, struct MapCoord crd, int player_n, int8_t ref_c, struct scout_info sc_info)
void cells_to_obs ()
int is_watched_by_others (Player player, std::vector< int8_t > &being_observed_by)
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes
MapCoord map_size
MapState msn
std::vector< MapState > Map_history
int max_units
std::vector< int8_t > unit_id_count
int unique_unit_id_count
std::vector< std::vector< int8_t > > turn_unit_per_p_v
std::vector< int8_t > turn_unit_all_p_v
PlayerActionState current_pas
UnitSelectionOrder unit_selection_order
int ground_type_num
int land_info_channel_depth
int piece_type_n
std::vector< std::vector< std::vector< std::vector< std::vector< int8_t > > > > > obs_per_p_v
int obs_total_channel_depth
int last_move_len
std::vector< FP16 > supply_v
std::vector< P_UnitId > unique_id_to_player_id_v
enum UnitActionKind game_uak
std::unique_ptr< SocketServer > ipc_server
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 60 of file baseT.h.
Constructor & Destructor Documentation
baseTState() [1/2]
open_spiel::baseT::baseTState::baseTState (std::shared_ptr< const Game > game)
Definition at line 108 of file baseT.cc.
                                                         : State(game)
    {
    }
baseTState() [2/2]
open_spiel::baseT::baseTState::baseTState (const baseTState &) default
~baseTState()
open_spiel::baseT::baseTState::~baseTState () virtual
Definition at line 112 of file baseT.cc.
    {
    }
Member Function Documentation
action_select_tile()
int open_spiel::baseT::baseTState::action_select_tile (int pn, int unit_id, MapCoord tg_crd, bool is_init) protected virtual
msn.cells_v[mine.crd.z][mine.crd.y][mine.crd.x].occupying_unique_unit_id = UNone;
msn.cells_v[mine.crd.z][mine.crd.y][mine.crd.x].occupying_unit_id = mine.unit_id;
Definition at line 516 of file baseT.cc.
    {
      if (tg_crd.z < 0 || tg_crd.y < 0 || tg_crd.x < 0 ||
          tg_crd.z >= map_size.z || tg_crd.y >= map_size.y || tg_crd.x >= map_size.x)
      {
        get_set_error("tg_crd is out of boundary.", true);
        return -1;
      }
      Unit &mine = msn.units_v[pn][unit_id];
      if (msn.cells_v[tg_crd.z][tg_crd.y][tg_crd.x].occupying_player == PNone)
      { //
        if (msn.cells_v[tg_crd.z][tg_crd.y][tg_crd.x].ground_type != GT_CannotEnter)
        { //
          if (!is_init)
          {
            // 1.   .    .
            // msn.cells_v[mine.crd.z][mine.crd.y][mine.crd.x].occupying_player = PNone;
            // msn.cells_v[mine.crd.z][mine.crd.y][mine.crd.x].occupying_unit_id = UNone;
            set_cell_and_obs({0, 1, 1, 1, 0}, {GT_None, PNone, UNone, UNone, {}},
            {mine.crd.z, mine.crd.y, mine.crd.x}, -1, -1, {true, pn, unit_id, ObsRefDown});
            // 2.        obs ref_count
            //scout(pn, unit_id, ObsRefDown);
          }
          // 3.    .
          mine.crd = tg_crd;
          // msn.cells_v[mine.crd.z][mine.crd.y][mine.crd.x].occupying_player = mine.player;
          // msn.cells_v[mine.crd.z][mine.crd.y][mine.crd.x].occupying_unique_unit_id = mine.unique_unit_id;
          set_cell_and_obs({0, 1, 1, 1, 0}, {GT_None, mine.player, mine.unit_id, mine.unique_unit_id, {}},
                            {mine.crd.z, mine.crd.y, mine.crd.x}, -1, -1, {true, pn, unit_id, ObsRefUp});
          // 4.    .
          //scout(pn, unit_id, ObsRefUp);
          // 5.  obs      . TODO :      .
          mine.being_observed_by = msn.cells_v[mine.crd.z][mine.crd.y][mine.crd.x].being_observed_by;
        }
        else
        { //   . Model       .   .
          get_set_error("GroundType is CannotEnter", true);
          return -1;
        }
      }
      else
      { //
        if (msn.cells_v[tg_crd.z][tg_crd.y][tg_crd.x].occupying_player == pn)
        { //
          if (mine.unit_id == msn.cells_v[tg_crd.z][tg_crd.y][tg_crd.x].occupying_unit_id)
          { //    .
            return 0;
          }
          else
          {
            //      . Model       .   .
            get_set_error("There is already an unit. Cannot move", true);
            return -1;
          }
        }
        else
        { //
          if (msn.cells_v[tg_crd.z][tg_crd.y][tg_crd.x].being_observed_by[pn])
          { //
            int p_enemy = msn.cells_v[tg_crd.z][tg_crd.y][tg_crd.x].occupying_player;
            int uid_enemy = msn.cells_v[tg_crd.z][tg_crd.y][tg_crd.x].occupying_unit_id;
            if (msn.units_v[p_enemy][uid_enemy].being_observed_by[pn])
            { // &
              // .
              if (distance_between(tg_crd, mine.crd) > mine.atk_dstc) {
                //  .       .    .
                get_set_error("This Action should not been selected", true);
                return -1;
              } else {
                int attck_ret = attack(msn.units_v[p_enemy][uid_enemy], msn.units_v[pn][unit_id]);
              }
            }
            else
           {  //     .    .
              // TODO.   .         .
              //      .
              get_set_error("This log should not have been visible.", true);
              return -1;
            }
          }
          else
          { //    .       .
            //   .            .
            //        .    .
            get_set_error("This log should not have been visible.", true);
            return -1;
          }
        }
      }
      // 2.   .
      //    2-1. pn
      //    2-2. pn     .
      return 0;
    }
References open_spiel::baseT::Unit::atk_dstc, open_spiel::baseT::Unit::being_observed_by, open_spiel::baseT::MapState::cells_v, open_spiel::baseT::Unit::crd, get_set_error(), open_spiel::baseT::GT_CannotEnter, open_spiel::baseT::GT_None, map_size, msn, open_spiel::baseT::ObsRefDown, open_spiel::baseT::ObsRefUp, open_spiel::baseT::Unit::player, open_spiel::baseT::PNone, set_cell_and_obs(), open_spiel::baseT::Unit::unique_unit_id, open_spiel::baseT::Unit::unit_id, open_spiel::baseT::MapState::units_v, open_spiel::baseT::UNone, open_spiel::baseT::MapCoord::x, open_spiel::baseT::MapCoord::y, and open_spiel::baseT::MapCoord::z.
Referenced by deploy_unit().
ActionToString()
std::string open_spiel::baseT::baseTState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 116 of file baseT.cc.
    {
      return std::string("temp");
    }
cells_to_obs()
void open_spiel::baseT::baseTState::cells_to_obs () protected
Definition at line 821 of file baseT.cc.
    {
      // map cell   obs   .
      // cell(1x1)  obs(1xc)   .
      // cells_v[z][y][x] -> obs_per_p_v[p][z][y][x] = vector<int8>
      for (int z = 0; z < map_size.z; z++)
      {
        for (int y = 0; y < map_size.y; y++)
        {
          for (int x = 0; x < map_size.x; x++)
          {
            for (int p = 0; p < num_players_; p++)
            {
              //  vector<int8_t>    .
              set_obs_onehot_vector(obs_per_p_v[p][z][y][x], msn.cells_v[z][y][x], p);
            }
          }
        }
      }
    }
References open_spiel::baseT::MapState::cells_v, map_size, msn, open_spiel::State::num_players_, obs_per_p_v, open_spiel::baseT::MapCoord::x, x, open_spiel::baseT::MapCoord::y, y, and open_spiel::baseT::MapCoord::z.
Referenced by init_first().
Clone()
std::unique_ptr< State > open_spiel::baseT::baseTState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 227 of file baseT.cc.
    {
      // TODO
      return nullptr;
    }
crd_to_id()
Action open_spiel::baseT::baseTState::crd_to_id (MapCoord crd) protected virtual
Definition at line 244 of file baseT.cc.
    {
      int a = 0;
      a += crd.z * (map_size.x * map_size.y);
      a += crd.y * map_size.x;
      a += crd.x;
      return a;
    }
References a, map_size, open_spiel::baseT::MapCoord::x, open_spiel::baseT::MapCoord::y, and open_spiel::baseT::MapCoord::z.
CurrentPAS()
PlayerActionState open_spiel::baseT::baseTState::CurrentPAS () const
Definition at line 141 of file baseT.cc.
    {
      return current_pas;
    }
References current_pas.
CurrentPlayer()
Player open_spiel::baseT::baseTState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 121 of file baseT.cc.
    {
      // TODO
      return msn.current_player;
    }
References open_spiel::baseT::MapState::current_player, and msn.
Referenced by set_next_unit_to_action_rand_per_p().
CurrentUAS()
UnitActionState open_spiel::baseT::baseTState::CurrentUAS () const
Definition at line 127 of file baseT.cc.
    {
      return msn.current_uas;
    }
References open_spiel::baseT::MapState::current_uas, and msn.
CurrentUniqueUnitId()
int open_spiel::baseT::baseTState::CurrentUniqueUnitId () const
Definition at line 132 of file baseT.cc.
    {
      return msn.current_unique_unit_id;
    }
References open_spiel::baseT::MapState::current_unique_unit_id, and msn.
CurrentUnitId()
int open_spiel::baseT::baseTState::CurrentUnitId () const
Definition at line 137 of file baseT.cc.
    {
      return msn.current_player_unit_id;
    }
References open_spiel::baseT::MapState::current_player_unit_id, and msn.
deploy_unit()
void open_spiel::baseT::baseTState::deploy_unit (int player_id, bool is_alive, int shift_dstc, int atk_dstc, int vw_dstc, float hp, float power, UnitClass unit_class, MapCoord crd, std::string name)
Definition at line 700 of file baseT.cc.
    {
      std::vector<int8_t> empty_v(num_players_, 0);
      msn.units_v[player_id].push_back({player_id, is_alive, ++unit_id_count[player_id], ++unique_unit_id_count,
                                        shift_dstc, atk_dstc, vw_dstc, hp, power, unit_class, crd, empty_v, name});
      unique_id_to_player_id_v.push_back({unique_unit_id_count, player_id, unit_id_count[player_id]});
      action_select_tile(player_id, unit_id_count[player_id], crd, true);
    }
References action_select_tile(), msn, name, open_spiel::State::num_players_, power, unique_id_to_player_id_v, unique_unit_id_count, unit_id_count, and open_spiel::baseT::MapState::units_v.
Referenced by open_spiel::kbg::kbgState::init_unit().
DoApplyAction()
void open_spiel::baseT::baseTState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 331 of file baseT.cc.
    {
      // apply_action call this
      // STATE CHANGE WORK
    }
get_cell_observation_string()
std::string open_spiel::baseT::baseTState::get_cell_observation_string (MapState state, MapCoord crd, int p) const protected virtual
Definition at line 417 of file baseT.cc.
    {
      std::string cell_observed = "";
      //   .
      switch (s.cells_v[crd.z][crd.y][crd.x].ground_type)
      {
      case GT_Normal:
        cell_observed += "_";
        break;
      case GT_CannotEnter:
        cell_observed += "X";
        break;
      default:
        cell_observed += "E";
      }
      if (s.cells_v[crd.z][crd.y][crd.x].being_observed_by[p]) // p
      {
        if (s.cells_v[crd.z][crd.y][crd.x].occupying_player != PNone) //
        {
          cell_observed += std::to_string(s.cells_v[crd.z][crd.y][crd.x].occupying_player);
          cell_observed += std::to_string(s.cells_v[crd.z][crd.y][crd.x].occupying_unit_id);
        }
      }
      else //
      {
        cell_observed += "?";
      }
      //
      if (max_units < 10) // GPI = 3
      {
        cell_observed.insert(cell_observed.cend(), (3 - cell_observed.length()), ' ');
      }
      else if (max_units < 100)
      {
        cell_observed.insert(cell_observed.cend(), (4 - cell_observed.length()), ' ');
      }
      return cell_observed;
    }
References open_spiel::baseT::GT_CannotEnter, open_spiel::baseT::GT_Normal, max_units, open_spiel::baseT::PNone, open_spiel::baseT::MapCoord::x, open_spiel::baseT::MapCoord::y, and open_spiel::baseT::MapCoord::z.
Referenced by ObservationString().
get_set_error()
std::string open_spiel::baseT::baseTState::get_set_error (std::string log, bool is_save) protected virtual
Definition at line 618 of file baseT.cc.
    {
      static std::string last_log;
      if (is_save)
      {
        last_log = log;
      }
      else
      {
        return last_log;
      }
    }
References log.
Referenced by action_select_tile().
get_unit_by_uniqueId()
Unit & open_spiel::baseT::baseTState::get_unit_by_uniqueId (int unique_id) protected
Definition at line 323 of file baseT.cc.
    {
      int player_id = unique_id_to_player_id_v[unique_id].player_id;
      int unit_id = unique_id_to_player_id_v[unique_id].player_unit_id;
      return msn.units_v[player_id][unit_id];
    }
References msn, unique_id_to_player_id_v, and open_spiel::baseT::MapState::units_v.
Referenced by set_next_unit_to_action_rand_all_p(), and set_next_unit_to_action_rand_per_p().
id_to_crd()
MapCoord open_spiel::baseT::baseTState::id_to_crd (Action a) protected virtual
Definition at line 233 of file baseT.cc.
    {
      MapCoord r;
      int xy = (map_size.x * map_size.y);
      r.z = a / xy;
      r.y = (a % xy) / map_size.x;
      r.x = (a % xy) % map_size.x;
      return r;
    }
References a, map_size, r, open_spiel::baseT::MapCoord::x, xy, open_spiel::baseT::MapCoord::y, and open_spiel::baseT::MapCoord::z.
init_first()
void open_spiel::baseT::baseTState::init_first (int max_u, int piece_tn, int last_mn, int supply_n, int land_channel_d, UnitSelectionOrder uso, MapCoord ms, UnitActionKind game_uak) protected virtual
Definition at line 354 of file baseT.cc.
    {
      init_server();
      land_info_channel_depth = land_channel_d;
      max_units = max_u;
      piece_type_n = piece_tn;
      last_move_len = last_mn;
      unit_selection_order = uso;
      ground_type_num = sizeof(GroundType) - 1;
      game_uak = uak;
      // 1.
      map_size.x = ms.x;
      map_size.y = ms.y;
      map_size.z = ms.z;
      //       0 .
      unit_id_count.assign(num_players_, UNone);
      //
      unique_unit_id_count = -1;
      //         .
      std::vector<Unit> empty_units_v;
      msn.units_v.assign(num_players_, empty_units_v);
      //        .
      switch (unit_selection_order)
      {
      case USO_ALL_P_RAND:
      {
      }
      break;
      case USO_PER_P_RAND:
      {
        std::vector<int8_t> empty_id_v;
        turn_unit_per_p_v.assign(num_players_, empty_id_v);
        msn.current_player = 0;
      }
      break;
      }
      // P0
      msn.current_uas = UA_Act_0;
      current_pas = PA_Obs;
      init_cells();
      init_obs();
      cells_to_obs();
      //
      supply_v.assign(num_players_, supply_n);
      // P_UnitId empty_id = {-1,-1,-1};
      // unique_id_to_player_id_v.assign(max_units*num_players_, empty_id);
      init_map();
      init_unit();
    }
References cells_to_obs(), current_pas, open_spiel::baseT::MapState::current_player, open_spiel::baseT::MapState::current_uas, game_uak, ground_type_num, land_info_channel_depth, last_move_len, map_size, max_units, msn, open_spiel::State::num_players_, open_spiel::baseT::PA_Obs, piece_type_n, supply_v, turn_unit_per_p_v, open_spiel::baseT::UA_Act_0, unique_unit_id_count, unit_id_count, unit_selection_order, open_spiel::baseT::MapState::units_v, open_spiel::baseT::UNone, open_spiel::baseT::USO_ALL_P_RAND, open_spiel::baseT::USO_PER_P_RAND, open_spiel::baseT::MapCoord::x, open_spiel::baseT::MapCoord::y, and open_spiel::baseT::MapCoord::z.
Referenced by open_spiel::kbg::kbgState::kbgState().
is_watched_by_others()
int open_spiel::baseT::baseTState::is_watched_by_others (Player player, std::vector< int8_t > & being_observed_by) protected
Definition at line 631 of file baseT.cc.
    {
      int count = 0;
      for (int i = 0; i < being_observed_by.size(); i++)
      {
        if (i == player)
        {
          continue;
        }
        if (being_observed_by[i] > 0)
        {
          count++;
        }
      }
      return count;
    }
References i, and player.
IsTerminal()
bool open_spiel::baseT::baseTState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 203 of file baseT.cc.
    {
      // TODO
      return 0;
    }
LegalActions()
std::vector< Action > open_spiel::baseT::baseTState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 209 of file baseT.cc.
    {
      // TODO
      return {0};
    }
ObservationString()
std::string open_spiel::baseT::baseTState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 460 of file baseT.cc.
    {
      std::string board_string = "BoardString of P" + std::to_string(player) + "\n";
      std::string cell_string = "";
      // 1. print ground if not occupied
      // 2. print unit if occupied
      for (int z = 0; z < map_size.z; z++)
      {
        for (int y = 0; y < map_size.y; y++)
        {
          for (int x = 0; x < map_size.x; x++)
          {
            cell_string = get_cell_observation_string(msn, {z, y, x}, player);
            if (msn.cells_v[z][y][x].occupying_unique_unit_id == msn.current_unique_unit_id)
            {
              board_string += "\033[31m" + cell_string + "\033[0m";
            }
            else
            {
              board_string += cell_string;
            }
          } // x
          board_string += "\n";
        } // y
        board_string += "\n";
      } // z
      return board_string;
    }
References open_spiel::baseT::MapState::cells_v, open_spiel::baseT::MapState::current_unique_unit_id, get_cell_observation_string(), map_size, msn, player, open_spiel::baseT::MapCoord::x, x, open_spiel::baseT::MapCoord::y, y, and open_spiel::baseT::MapCoord::z.
ObservationTensor()
void open_spiel::baseT::baseTState::ObservationTensor (Player player, absl::Span< float > values) const protected virtual
Reimplemented from open_spiel::State.
Definition at line 712 of file baseT.cc.
    {
      // DeepNash.md
      // 0.  . channel = land_info_channel_depth
      // 1. Private Info. c = piece_type_n
      // 2. Op Public Info. c = piece_type_n
      // 3. My Public Info. c = piece_type_n
      // 4. last move. c = last_move_len
      // 5. draw ratio
    }
ObservationTensorBaseT()
void open_spiel::baseT::baseTState::ObservationTensorBaseT (Player player)
Definition at line 692 of file baseT.cc.
    {
      // std::fill(obs_v.begin(), obs_v.end(), 0);
      int index = 0;
      //
    }
ObservationTensorBaseT_Land()
int open_spiel::baseT::baseTState::ObservationTensorBaseT_Land (Player player, int last_index) protected
Definition at line 9 of file baseT_utils.cc.
    {
      return 0;
    }
operator=()
virtual baseTState & open_spiel::baseT::baseTState::operator= (const baseTState &) virtual default
Returns()
std::vector< double > open_spiel::baseT::baseTState::Returns () const virtual
Implements open_spiel::State.
Definition at line 215 of file baseT.cc.
    {
      // TODO
      return {0.0};
    }
scout()
void open_spiel::baseT::baseTState::scout (int pn, int unit_id, ObsRefCount o_r_c) protected virtual
Definition at line 651 of file baseT.cc.
    {
      // 1.   observed marking
      Unit &u = msn.units_v[pn][unit_id];
      // 1. pn  vw_dstc   .
      //   z,y  unit z,y   x   .
      //   .   .
      // z + y + x = u.vw_dstc
      #pragma omp parallel
      #pragma omp for
      for (int z = -u.vw_dstc; z <= u.vw_dstc; z++)
      {
        for (int y = -(u.vw_dstc - std::abs(z)); y <= (u.vw_dstc - std::abs(z)); y++)
        {
          for (int x = -(u.vw_dstc - std::abs(z) - std::abs(y)); x <= (u.vw_dstc - std::abs(z) - std::abs(y)); x++)
          {
            //printf("thread num %d \n", omp_get_thread_num());
            int tg_z = u.crd.z + z;
            int tg_y = u.crd.y + y;
            int tg_x = u.crd.x + x;
            //
            if (tg_z >= 0 && tg_z < map_size.z && tg_y >= 0 && tg_y < map_size.y && tg_x >= 0 && tg_x < map_size.x)
            {
              //   Obs Ref count
              // msn.cells_v[tg_z][tg_y][tg_x].being_observed_by[pn] += o_r_c;
              set_cell_and_obs({0, 0, 0, 0, 1}, {GT_None, 0, 0, 0, {}}, {tg_z, tg_y, tg_x}, pn, o_r_c, {false,-1,-1,ObsRefNone});
              //       obs
              if (msn.cells_v[tg_z][tg_y][tg_x].occupying_player != PNone)
              {
                msn.units_v[msn.cells_v[tg_z][tg_y][tg_x].occupying_player][msn.cells_v[tg_z][tg_y][tg_x].occupying_unit_id].being_observed_by = msn.cells_v[tg_z][tg_y][tg_x].being_observed_by;
              }
            }
          }
        }
      }
    }
References open_spiel::baseT::MapState::cells_v, open_spiel::baseT::GT_None, map_size, msn, open_spiel::baseT::ObsRefNone, open_spiel::baseT::PNone, set_cell_and_obs(), open_spiel::baseT::MapState::units_v, open_spiel::baseT::MapCoord::x, x, and y.
Referenced by set_cell_and_obs().
set_cell_and_obs()
void open_spiel::baseT::baseTState::set_cell_and_obs (struct Cell_set_flags flags, struct Cell cell, struct MapCoord crd, int player_n, int8_t ref_c, struct scout_info sc_info) protected
Definition at line 729 of file baseT.cc.
    {
      if (flags.is_gtype)
      {
        msn.cells_v[crd.z][crd.y][crd.x].ground_type = cell.ground_type;
      }
      if (flags.is_op)
      {
        msn.cells_v[crd.z][crd.y][crd.x].occupying_player = cell.occupying_player;
      }
      if (flags.is_oui)
      {
        msn.cells_v[crd.z][crd.y][crd.x].occupying_unit_id = cell.occupying_unit_id;
      }
      if (flags.is_ouui)
      {
        msn.cells_v[crd.z][crd.y][crd.x].occupying_unique_unit_id = cell.occupying_unique_unit_id;
      }
      if (flags.is_bob)
      {
        if (player_n != -1)
        {
          msn.cells_v[crd.z][crd.y][crd.x].being_observed_by[player_n] = ref_c;
        }
        else
        {
          msn.cells_v[crd.z][crd.y][crd.x].being_observed_by = cell.being_observed_by;
        }
      }
      if (sc_info.do_scout)
        scout(sc_info.p, sc_info.unit_id, sc_info.o_r_c);
      #pragma omp parallel
      #pragma omp for
      for (int p = 0; p < num_players_; p++) {
        set_obs_onehot_vector(obs_per_p_v[p][crd.z][crd.y][crd.x], msn.cells_v[crd.z][crd.y][crd.x], p);
      }
      // send
    }
References open_spiel::baseT::Cell::being_observed_by, open_spiel::baseT::MapState::cells_v, open_spiel::baseT::scout_info::do_scout, open_spiel::baseT::Cell::ground_type, msn, open_spiel::State::num_players_, open_spiel::baseT::scout_info::o_r_c, obs_per_p_v, open_spiel::baseT::Cell::occupying_player, open_spiel::baseT::Cell::occupying_unique_unit_id, open_spiel::baseT::Cell::occupying_unit_id, open_spiel::baseT::scout_info::p, scout(), open_spiel::baseT::scout_info::unit_id, open_spiel::baseT::MapCoord::x, open_spiel::baseT::MapCoord::y, and open_spiel::baseT::MapCoord::z.
Referenced by action_select_tile(), open_spiel::kbg::kbgState::init_map(), and scout().
set_next_unit_to_action()
void open_spiel::baseT::baseTState::set_next_unit_to_action () virtual
Definition at line 254 of file baseT.cc.
    {
      switch (unit_selection_order)
      {
      case USO_ALL_P_RAND:
        set_next_unit_to_action_rand_all_p();
        break;
      case USO_PER_P_RAND:
        set_next_unit_to_action_rand_per_p();
        break;
      default:
        return;
      }
      return;
    }
References set_next_unit_to_action_rand_all_p(), set_next_unit_to_action_rand_per_p(), unit_selection_order, open_spiel::baseT::USO_ALL_P_RAND, and open_spiel::baseT::USO_PER_P_RAND.
set_next_unit_to_action_rand_all_p()
void open_spiel::baseT::baseTState::set_next_unit_to_action_rand_all_p () protected virtual
Definition at line 271 of file baseT.cc.
    {
      if (turn_unit_all_p_v.size() == 0)
      {
        for (int i = 0; i < unique_unit_id_count + 1; i++)
        {
          if (get_unit_by_uniqueId(i).is_alive)
          { // unique_unit_id  unit
            turn_unit_all_p_v.push_back(i);
          }
        }
        std::random_device rd;
        std::mt19937 gen(rd());
        std::shuffle(turn_unit_all_p_v.begin(), turn_unit_all_p_v.end(), gen);
      }
      msn.current_unique_unit_id = turn_unit_all_p_v.back();
      turn_unit_all_p_v.pop_back();
      msn.current_player = get_unit_by_uniqueId(msn.current_unique_unit_id).player;
      msn.current_player_unit_id = get_unit_by_uniqueId(msn.current_unique_unit_id).unit_id;
      return;
    }
References open_spiel::baseT::MapState::current_player, open_spiel::baseT::MapState::current_player_unit_id, open_spiel::baseT::MapState::current_unique_unit_id, get_unit_by_uniqueId(), i, msn, open_spiel::baseT::Unit::player, turn_unit_all_p_v, unique_unit_id_count, and open_spiel::baseT::Unit::unit_id.
Referenced by set_next_unit_to_action().
set_next_unit_to_action_rand_per_p()
void open_spiel::baseT::baseTState::set_next_unit_to_action_rand_per_p () protected virtual
Definition at line 296 of file baseT.cc.
    {
      int p = CurrentPlayer();
      if (turn_unit_per_p_v[p].size() == 0)
      {
        #pragma omp parallel
        #pragma omp for
        for (int i = 0; i < max_units; i++)
        {
          if (msn.units_v[p][i].is_alive)
          {
            turn_unit_per_p_v[p].push_back(msn.units_v[p][i].unique_unit_id);
          }
        }
        std::random_device rd;
        std::mt19937 gen(rd());
        std::shuffle(turn_unit_per_p_v[p].begin(), turn_unit_per_p_v[p].end(), gen);
      }
      msn.current_unique_unit_id = turn_unit_per_p_v[p].back();
      turn_unit_per_p_v[p].pop_back();
      msn.current_player = get_unit_by_uniqueId(msn.current_unique_unit_id).player;
      msn.current_player_unit_id = get_unit_by_uniqueId(msn.current_unique_unit_id).unit_id;
      return;
    }
References begin, open_spiel::baseT::MapState::current_player, open_spiel::baseT::MapState::current_player_unit_id, open_spiel::baseT::MapState::current_unique_unit_id, CurrentPlayer(), end, get_unit_by_uniqueId(), i, max_units, msn, open_spiel::baseT::Unit::player, size, turn_unit_per_p_v, open_spiel::baseT::Unit::unit_id, and open_spiel::baseT::MapState::units_v.
Referenced by set_next_unit_to_action().
SetNextPAS()
void open_spiel::baseT::baseTState::SetNextPAS ()
Definition at line 178 of file baseT.cc.
    {
      switch (current_pas)
      {
      case PA_Obs:
        current_pas = PA_Think;
        break;
      case PA_Think:
        current_pas = PA_Action;
        break;
      case PA_Action:
        current_pas = PA_Obs;
        break;
      case PA_None:
        break;
      }
    }
References current_pas, open_spiel::baseT::PA_Action, open_spiel::baseT::PA_None, open_spiel::baseT::PA_Obs, and open_spiel::baseT::PA_Think.
SetNextPlayer()
void open_spiel::baseT::baseTState::SetNextPlayer ()
Definition at line 195 of file baseT.cc.
    {
      msn.current_player++;
      if (msn.current_player == num_players_)
        msn.current_player = 0;
    }
References open_spiel::baseT::MapState::current_player, msn, and open_spiel::State::num_players_.
SetNextUAS()
void open_spiel::baseT::baseTState::SetNextUAS ()
Definition at line 146 of file baseT.cc.
    {
      switch (game_uak)
      {
      case UA_Kind_1step:
        SetNextUAS_1step();
        break;
      case UA_Kind_2step:
        SetNextUAS_2step();
        break;
      }
    }
References game_uak, open_spiel::baseT::UA_Kind_1step, and open_spiel::baseT::UA_Kind_2step.
ToString()
std::string open_spiel::baseT::baseTState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 221 of file baseT.cc.
    {
      // TODO
      return std::string("temp");
    }
Member Data Documentation
current_pas
PlayerActionState open_spiel::baseT::baseTState::current_pas protected
Definition at line 121 of file baseT.h.
Referenced by CurrentPAS(), init_first(), and SetNextPAS().
game_uak
enum UnitActionKind open_spiel::baseT::baseTState::game_uak protected
Definition at line 133 of file baseT.h.
Referenced by init_first(), and SetNextUAS().
ground_type_num
int open_spiel::baseT::baseTState::ground_type_num protected
Definition at line 123 of file baseT.h.
Referenced by init_first().
ipc_server
std::unique_ptr<SocketServer> open_spiel::baseT::baseTState::ipc_server protected
Definition at line 136 of file baseT.h.
land_info_channel_depth
int open_spiel::baseT::baseTState::land_info_channel_depth protected
Definition at line 126 of file baseT.h.
Referenced by init_first().
last_move_len
int open_spiel::baseT::baseTState::last_move_len protected
Definition at line 130 of file baseT.h.
Referenced by init_first().
Map_history
std::vector<MapState> open_spiel::baseT::baseTState::Map_history protected
Definition at line 115 of file baseT.h.
map_size
MapCoord open_spiel::baseT::baseTState::map_size protected
Definition at line 113 of file baseT.h.
Referenced by action_select_tile(), cells_to_obs(), crd_to_id(), id_to_crd(), init_first(), ObservationString(), and scout().
max_units
int open_spiel::baseT::baseTState::max_units protected
Definition at line 116 of file baseT.h.
Referenced by get_cell_observation_string(), init_first(), and set_next_unit_to_action_rand_per_p().
msn
MapState open_spiel::baseT::baseTState::msn protected
Definition at line 114 of file baseT.h.
Referenced by action_select_tile(), cells_to_obs(), CurrentPlayer(), CurrentUAS(), CurrentUniqueUnitId(), CurrentUnitId(), deploy_unit(), get_unit_by_uniqueId(), init_first(), ObservationString(), scout(), set_cell_and_obs(), set_next_unit_to_action_rand_all_p(), set_next_unit_to_action_rand_per_p(), and SetNextPlayer().
obs_per_p_v
std::vector<std::vector<std::vector<std::vector<std::vector<int8_t> > > > > open_spiel::baseT::baseTState::obs_per_p_v protected
Definition at line 128 of file baseT.h.
Referenced by cells_to_obs(), and set_cell_and_obs().
obs_total_channel_depth
int open_spiel::baseT::baseTState::obs_total_channel_depth protected
Definition at line 129 of file baseT.h.
piece_type_n
int open_spiel::baseT::baseTState::piece_type_n protected
Definition at line 127 of file baseT.h.
Referenced by init_first().
supply_v
std::vector<FP16> open_spiel::baseT::baseTState::supply_v protected
Definition at line 131 of file baseT.h.
Referenced by init_first().
turn_unit_all_p_v
std::vector<int8_t> open_spiel::baseT::baseTState::turn_unit_all_p_v protected
Definition at line 120 of file baseT.h.
Referenced by set_next_unit_to_action_rand_all_p().
turn_unit_per_p_v
std::vector<std::vector<int8_t> > open_spiel::baseT::baseTState::turn_unit_per_p_v protected
Definition at line 119 of file baseT.h.
Referenced by init_first(), and set_next_unit_to_action_rand_per_p().
unique_id_to_player_id_v
std::vector<P_UnitId> open_spiel::baseT::baseTState::unique_id_to_player_id_v protected
Definition at line 132 of file baseT.h.
Referenced by deploy_unit(), and get_unit_by_uniqueId().
unique_unit_id_count
int open_spiel::baseT::baseTState::unique_unit_id_count protected
Definition at line 118 of file baseT.h.
Referenced by deploy_unit(), init_first(), and set_next_unit_to_action_rand_all_p().
unit_id_count
std::vector<int8_t> open_spiel::baseT::baseTState::unit_id_count protected
Definition at line 117 of file baseT.h.
Referenced by deploy_unit(), and init_first().
unit_selection_order
UnitSelectionOrder open_spiel::baseT::baseTState::unit_selection_order protected
Definition at line 122 of file baseT.h.
Referenced by init_first(), and set_next_unit_to_action().
The documentation for this class was generated from the following files:
open_spiel/games/SG/baseT.h
open_spiel/games/SG/baseT.cc
open_spiel/games/SG/baseT_utils.cc