open spiel: open_spiel.python.policy.UniformRandomPolicy Class Reference
open_spiel.python.policy.UniformRandomPolicy Class Reference
Public Member Functions
__init__ (self, game)
action_probabilities (self, state, player_id=None)
Public Member Functions inherited from open_spiel.python.policy.Policy
__call__ (self, state, player_id=None)
to_tabular (self, states=None)
Additional Inherited Members
Public Attributes inherited from open_spiel.python.policy.Policy
game
player_ids
Detailed Description
Policy where the action distribution is uniform over all legal actions.
This is computed as needed, so can be used for games where a tabular policy
would be unfeasibly large, but incurs a legal action computation every time.
Definition at line 400 of file policy.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.policy.UniformRandomPolicy.__init__ (self, game)
Initializes a uniform random policy for all players in the game.
Reimplemented from open_spiel.python.policy.Policy.
Definition at line 407 of file policy.py.
  def __init__(self, game):
    """Initializes a uniform random policy for all players in the game."""
    all_players = list(range(game.num_players()))
    super().__init__(game, all_players)
References open_spiel.python.policy.UniformRandomPolicy.__init__().
Referenced by open_spiel.python.policy.UniformRandomPolicy.__init__().
Member Function Documentation
action_probabilities()
open_spiel.python.policy.UniformRandomPolicy.action_probabilities (self, state, player_id = None)
Returns a uniform random policy for a player in a state.
Args:
  state: A `pyspiel.State` object.
  player_id: Optional, the player id for which we want an action. Optional
    unless this is a simultaneous state at which multiple players can act.
Returns:
  A `dict` of `{action: probability}` for the specified player in the
  supplied state. This will contain all legal actions, each with the same
  probability, equal to 1 / num_legal_actions.
Reimplemented from open_spiel.python.policy.Policy.
Definition at line 412 of file policy.py.
  def action_probabilities(self, state, player_id=None):
    """Returns a uniform random policy for a player in a state.
    Args:
      state: A `pyspiel.State` object.
      player_id: Optional, the player id for which we want an action. Optional
        unless this is a simultaneous state at which multiple players can act.
    Returns:
      A `dict` of `{action: probability}` for the specified player in the
      supplied state. This will contain all legal actions, each with the same
      probability, equal to 1 / num_legal_actions.
    """
    legal_actions = (
        state.legal_actions()
        if player_id is None else state.legal_actions(player_id))
    if not legal_actions:
      return {0: 1.0}
    probability = 1 / len(legal_actions)
    return {action: probability for action in legal_actions}
Referenced by open_spiel.python.policy.Policy.__call__(), and open_spiel.python.policy.Policy.to_tabular().
The documentation for this class was generated from the following file:
open_spiel/python/policy.py