open spiel: open_spiel::coordinated_mp::PenniesState Class Reference
open_spiel::coordinated_mp::PenniesState Class Reference
#include <coordinated_mp.h>
Public Member Functions
PenniesState (std::shared_ptr< const Game > game)
PenniesState (const PenniesState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action move) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
std::unique_ptr< State > Clone () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Friends
class PenniesObserver
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 43 of file coordinated_mp.h.
Constructor & Destructor Documentation
PenniesState() [1/2]
open_spiel::coordinated_mp::PenniesState::PenniesState (std::shared_ptr< const Game > game) explicit
Definition at line 120 of file coordinated_mp.cc.
: State(game) {}
PenniesState() [2/2]
open_spiel::coordinated_mp::PenniesState::PenniesState (const PenniesState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::coordinated_mp::PenniesState::ActionToString (Player player, Action move) const override virtual
Implements open_spiel::State.
Definition at line 164 of file coordinated_mp.cc.
{
  if (IsChanceNode()) {
    if (move == kTop) return "Top";
    if (move == kBottom) return "Bottom";
    SpielFatalError("Should not match");
  }
  if (move == kHeads) return "Heads";
  if (move == kTails) return "Tails";
  SpielFatalError("Should not match");
  return "Does not return";
}
References open_spiel::State::IsChanceNode(), open_spiel::coordinated_mp::kBottom, open_spiel::coordinated_mp::kHeads, open_spiel::coordinated_mp::kTails, open_spiel::coordinated_mp::kTop, and open_spiel::SpielFatalError().
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::coordinated_mp::PenniesState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 213 of file coordinated_mp.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  return {{kTop, 0.5}, {kBottom, 0.5}};
}
References open_spiel::State::IsChanceNode(), open_spiel::coordinated_mp::kBottom, open_spiel::coordinated_mp::kTop, and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::coordinated_mp::PenniesState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 209 of file coordinated_mp.cc.
{
  return absl::make_unique<PenniesState>(*this);
}
CurrentPlayer()
int open_spiel::coordinated_mp::PenniesState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 122 of file coordinated_mp.cc.
{
  if (actionA_ == kNoAction) {
    // When first player acts, these should not be set yet.
    SPIEL_CHECK_EQ(infoset_, kNoInfoset);
    SPIEL_CHECK_EQ(actionB_, kNoAction);
    return Player(0);
  }
  if (infoset_ == kNoInfoset) {
    // When chance player acts, second player shoud have no action.
    SPIEL_CHECK_EQ(actionB_, kNoAction);
    return kChancePlayerId;
  }
  if (actionB_ == kNoAction) {
    return Player(1);
  }
  SPIEL_CHECK_TRUE(IsTerminal());
  return kTerminalPlayerId;
}
References IsTerminal(), open_spiel::kChancePlayerId, open_spiel::coordinated_mp::kNoAction, open_spiel::coordinated_mp::kNoInfoset, open_spiel::kTerminalPlayerId, SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
Referenced by DoApplyAction().
DoApplyAction()
void open_spiel::coordinated_mp::PenniesState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 142 of file coordinated_mp.cc.
{
  switch (CurrentPlayer()) {
    case Player(0):
      actionA_ = static_cast<ActionType>(move);
      break;
    case Player(1):
      actionB_ = static_cast<ActionType>(move);
      break;
    case kChancePlayerId:
      infoset_ = static_cast<InfosetPosition>(move);
      break;
    default:
      SpielFatalError("Should not match");
  }
}
References CurrentPlayer(), open_spiel::kChancePlayerId, and open_spiel::SpielFatalError().
InformationStateString()
std::string open_spiel::coordinated_mp::PenniesState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 199 of file coordinated_mp.cc.
{
  const PenniesGame &game = open_spiel::down_cast<const PenniesGame &>(*game_);
  return game.info_state_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
IsTerminal()
bool open_spiel::coordinated_mp::PenniesState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 188 of file coordinated_mp.cc.
{
  return actionA_ != kNoAction && actionB_ != kNoAction &&
         infoset_ != kNoInfoset;
}
References open_spiel::coordinated_mp::kNoAction, and open_spiel::coordinated_mp::kNoInfoset.
Referenced by CurrentPlayer(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::coordinated_mp::PenniesState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 158 of file coordinated_mp.cc.
{
  if (IsTerminal()) return {};
  if (IsChanceNode()) return {InfosetPosition::kTop, InfosetPosition::kBottom};
  return {ActionType::kHeads, ActionType::kTails};
}
References open_spiel::State::IsChanceNode(), IsTerminal(), open_spiel::coordinated_mp::kBottom, open_spiel::coordinated_mp::kHeads, open_spiel::coordinated_mp::kTails, and open_spiel::coordinated_mp::kTop.
ObservationString()
std::string open_spiel::coordinated_mp::PenniesState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 204 of file coordinated_mp.cc.
{
  const PenniesGame &game = open_spiel::down_cast<const PenniesGame &>(*game_);
  return game.default_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
Returns()
std::vector< double > open_spiel::coordinated_mp::PenniesState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 193 of file coordinated_mp.cc.
{
  if (!IsTerminal()) return {0., 0.};
  const double matching = actionA_ == actionB_ ? 1. : -1.;
  return {matching * 1., matching * -1.};
}
References IsTerminal().
ToString()
std::string open_spiel::coordinated_mp::PenniesState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 177 of file coordinated_mp.cc.
{
  std::string str;
  if (actionA_ == kHeads) absl::StrAppend(&str, "H");
  if (actionA_ == kTails) absl::StrAppend(&str, "T");
  if (infoset_ == kTop) absl::StrAppend(&str, "T");
  if (infoset_ == kBottom) absl::StrAppend(&str, "B");
  if (actionB_ == kHeads) absl::StrAppend(&str, "H");
  if (actionB_ == kTails) absl::StrAppend(&str, "T");
  return str;
}
References open_spiel::coordinated_mp::kBottom, open_spiel::coordinated_mp::kHeads, open_spiel::coordinated_mp::kTails, open_spiel::coordinated_mp::kTop, and absl::StrAppend().
Friends And Related Symbol Documentation
PenniesObserver
friend class PenniesObserver friend
Definition at line 64 of file coordinated_mp.h.
The documentation for this class was generated from the following files:
open_spiel/games/coordinated_mp/coordinated_mp.h
open_spiel/games/coordinated_mp/coordinated_mp.cc