open spiel: open_spiel::phantom_go::PhantomGoObserver Class Reference
open_spiel::phantom_go::PhantomGoObserver Class Reference
Public Member Functions
PhantomGoObserver (IIGObservationType iig_obs_type)
void WriteTensor (const State &observed_state, int player, Allocator *allocator) const override
std::string StringFrom (const State &observed_state, int player) const override
Public Member Functions inherited from open_spiel::Observer
Observer (bool has_string, bool has_tensor)
bool HasString () const
bool HasTensor () const
virtual ~Observer ()=default
Additional Inherited Members
Protected Attributes inherited from open_spiel::Observer
bool has_string_
bool has_tensor_
Detailed Description
Definition at line 83 of file phantom_go.cc.
Constructor & Destructor Documentation
PhantomGoObserver()
open_spiel::phantom_go::PhantomGoObserver::PhantomGoObserver (IIGObservationType iig_obs_type) inline
Definition at line 85 of file phantom_go.cc.
      : Observer(/*has_string=*/true, /*has_tensor=*/true),
        iig_obs_type_(iig_obs_type) {}
Member Function Documentation
StringFrom()
std::string open_spiel::phantom_go::PhantomGoObserver::StringFrom (const State & observed_state, int player) const inline override virtual
Implements open_spiel::Observer.
Definition at line 149 of file phantom_go.cc.
{
    const PhantomGoState &state =
        open_spiel::down_cast<const PhantomGoState &>(observed_state);
    return state.ObservationString(player);
  }
References open_spiel::down_cast(), player, and state.
WriteTensor()
void open_spiel::phantom_go::PhantomGoObserver::WriteTensor (const State & observed_state, int player, Allocator * allocator) const inline override virtual
Implements open_spiel::Observer.
Definition at line 89 of file phantom_go.cc.
{
    const PhantomGoState &state =
        open_spiel::down_cast<const PhantomGoState &>(observed_state);
    const int totalBoardPoints =
        state.board().board_size() * state.board().board_size();
    {
      auto out = allocator->Get("stone-counts", {2});
      auto stoneCount = state.GetStoneCount();
      out.at(0) = stoneCount[0];
      out.at(1) = stoneCount[1];
    }
    if (iig_obs_type_.private_info == PrivateInfoType::kSinglePlayer) {
      {
        auto observation = state.board().GetObservationByID(player);
        auto out_empty =
            allocator->Get("player_observation_empty", {totalBoardPoints});
        auto out_white =
            allocator->Get("player_observation_white", {totalBoardPoints});
        auto out_black =
            allocator->Get("player_observation_black", {totalBoardPoints});
        auto out_komi = allocator->Get("komi", {totalBoardPoints});
        for (int i = 0; i < totalBoardPoints; i++) {
          switch (observation[i]) {
            case GoColor::kBlack:
              out_black.at(i) = true;
              out_white.at(i) = false;
              out_empty.at(i) = false;
              break;
            case GoColor::kWhite:
              out_black.at(i) = false;
              out_white.at(i) = true;
              out_empty.at(i) = false;
              break;
            case GoColor::kEmpty:
              out_black.at(i) = false;
              out_white.at(i) = false;
              out_empty.at(i) = true;
              break;
            default:
              SpielFatalError(absl::StrCat("Unhandled case: ", observation[i]));
          }
          if (state.CurrentPlayer() == (uint8_t)GoColor::kWhite) {
            out_komi.at(i) = 1;
          } else {
            out_komi.at(i) = 0;
          }
        }
      }
    }
  }
References open_spiel::SpanTensor::at(), open_spiel::down_cast(), open_spiel::Allocator::Get(), i, open_spiel::phantom_go::kBlack, open_spiel::phantom_go::kEmpty, open_spiel::kSinglePlayer, open_spiel::phantom_go::kWhite, out, player, open_spiel::IIGObservationType::private_info, open_spiel::SpielFatalError(), state, and absl::StrCat().
The documentation for this class was generated from the following file:
open_spiel/games/phantom_go/phantom_go.cc