open spiel: open_spiel::twixt::TwixTState Class Reference
open_spiel::twixt::TwixTState Class Reference
#include <twixt.h>
Public Member Functions
TwixTState (std::shared_ptr< const Game > game)
TwixTState (const TwixTState &)=default
TwixTState & operator= (const TwixTState &)=default
open_spiel::Player CurrentPlayer () const override
std::string ActionToString (open_spiel::Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (open_spiel::Player player) const override
std::string ObservationString (open_spiel::Player player) const override
void ObservationTensor (open_spiel::Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (open_spiel::Player, Action) override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 31 of file twixt.h.
Constructor & Destructor Documentation
TwixTState() [1/2]
open_spiel::twixt::TwixTState::TwixTState (std::shared_ptr< const Game > game) explicit
Definition at line 60 of file twixt.cc.
                                                     : State(game) {
  const TwixTGame &parent_game = static_cast<const TwixTGame &>(*game);
  board_ = Board(parent_game.board_size(), parent_game.ansi_color_output());
}
References open_spiel::twixt::TwixTGame::ansi_color_output(), and open_spiel::twixt::TwixTGame::board_size().
Referenced by Clone().
TwixTState() [2/2]
open_spiel::twixt::TwixTState::TwixTState (const TwixTState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::twixt::TwixTState::ActionToString (open_spiel::Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 65 of file twixt.cc.
{
  Position position = board_.ActionToPosition(action);
  std::string s = (player == kRedPlayer) ? "x" : "o";
  s += static_cast<int>('a') + position.x;
  s.append(std::to_string(board_.size() - position.y));
  return s;
}
References action, open_spiel::twixt::Board::ActionToPosition(), open_spiel::twixt::kRedPlayer, player, open_spiel::twixt::Board::size(), Position::x, and Position::y.
Clone()
std::unique_ptr< State > open_spiel::twixt::TwixTState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 80 of file twixt.h.
{
    return std::unique_ptr<State>(new TwixTState(*this));
  };
References TwixTState().
CurrentPlayer()
open_spiel::Player open_spiel::twixt::TwixTState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 38 of file twixt.h.
{ return current_player_; };
Referenced by DoApplyAction().
DoApplyAction()
void open_spiel::twixt::TwixTState::DoApplyAction (Action action) inline override protected virtual
Reimplemented from open_spiel::State.
Definition at line 92 of file twixt.h.
{
    const std::vector<Action> &v = LegalActions();
    if (std::find(v.begin(), v.end(), action) == v.end()) {
      SpielFatalError("Not a legal action: " + std::to_string(action));
    }
    board_.ApplyAction(CurrentPlayer(), action);
    if (board_.result() == kOpen) {
      set_current_player(1 - CurrentPlayer());
    } else {
      set_current_player(kTerminalPlayerId);
    }
  };
References action, open_spiel::twixt::Board::ApplyAction(), CurrentPlayer(), open_spiel::twixt::kOpen, open_spiel::kTerminalPlayerId, LegalActions(), open_spiel::twixt::Board::result(), and open_spiel::SpielFatalError().
InformationStateString()
std::string open_spiel::twixt::TwixTState::InformationStateString (open_spiel::Player player) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 65 of file twixt.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, kNumPlayers);
    return ToString();
  };
References open_spiel::twixt::kNumPlayers, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
IsTerminal()
bool open_spiel::twixt::TwixTState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 45 of file twixt.h.
{
    int result = board_.result();
    return (result == kRedWin || result == kBlueWin || result == kDraw);
  };
References open_spiel::twixt::kBlueWin, open_spiel::twixt::kDraw, open_spiel::twixt::kRedWin, and open_spiel::twixt::Board::result().
Referenced by LegalActions().
LegalActions()
std::vector< Action > open_spiel::twixt::TwixTState::LegalActions () const inline override virtual
Implements open_spiel::State.
Definition at line 86 of file twixt.h.
{
    if (IsTerminal()) return {};
    return board_.GetLegalActions(current_player_);
  };
References open_spiel::twixt::Board::GetLegalActions(), and IsTerminal().
Referenced by DoApplyAction().
ObservationString()
std::string open_spiel::twixt::TwixTState::ObservationString (open_spiel::Player player) const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 71 of file twixt.h.
{
    SPIEL_CHECK_GE(player, 0);
    SPIEL_CHECK_LT(player, kNumPlayers);
    return ToString();
  };
References open_spiel::twixt::kNumPlayers, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::twixt::TwixTState::ObservationTensor (open_spiel::Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 99 of file twixt.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, kNumPlayers);
  const int kPlaneOffset[2] = {0, kNumPlanes / 2};
  int size = board_.size();
  // 2 x 6 planes of size boardSize x (boardSize-2):
  // each plane excludes the endlines of the opponent
  // plane 0/6 is for the pegs
  // plane 1..4 / 7..10 is for the links NNE, ENE, ESE, SSE, resp.
  // plane 5/11 is pegs that have blocked neighbors
  TensorView<3> view(values, {kNumPlanes, board_.size(), board_.size() - 2},
                     true);
  for (int c = 0; c < size; c++) {
    for (int r = 0; r < size; r++) {
      Position position = {c, r};
      const Cell &cell = board_.GetConstCell(position);
      int color = cell.color();
      if (color == kRedColor) {
        // no turn
        SetPegAndLinksOnTensor(values, cell, kPlaneOffset[0], false, position);
      } else if (color == kBlueColor) {
        // 90 degr turn
        SetPegAndLinksOnTensor(values, cell, kPlaneOffset[1], true, position);
      }
    }
  }
}
References open_spiel::twixt::Cell::color(), open_spiel::twixt::Board::GetConstCell(), open_spiel::twixt::kBlueColor, open_spiel::twixt::kNumPlanes, open_spiel::twixt::kNumPlayers, open_spiel::twixt::kRedColor, player, r, open_spiel::twixt::Board::size(), size, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
operator=()
TwixTState & open_spiel::twixt::TwixTState::operator= (const TwixTState &) default
Returns()
std::vector< double > open_spiel::twixt::TwixTState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 50 of file twixt.h.
{
    double reward;
    int result = board_.result();
    if (result == kOpen || result == kDraw) {
      return {0.0, 0.0};
    } else {
      reward = 1.0;
      if (result == kRedWin) {
        return {reward, -reward};
      } else {
        return {-reward, reward};
      }
    }
  };
References open_spiel::twixt::kDraw, open_spiel::twixt::kOpen, open_spiel::twixt::kRedWin, and open_spiel::twixt::Board::result().
ToString()
std::string open_spiel::twixt::TwixTState::ToString () const inline override virtual
Implements open_spiel::State.
Definition at line 43 of file twixt.h.
{ return board_.ToString(); };
References open_spiel::twixt::Board::ToString().
Referenced by InformationStateString(), and ObservationString().
UndoAction()
void open_spiel::twixt::TwixTState::UndoAction (open_spiel::Player , Action) inline override virtual
Reimplemented from open_spiel::State.
Definition at line 84 of file twixt.h.
{};
The documentation for this class was generated from the following files:
open_spiel/games/twixt/twixt.h
open_spiel/games/twixt/twixt.cc