open spiel: open_spiel::RepeatedState Class Reference
open_spiel::RepeatedState Class Reference
#include <repeated_game.h>
Public Member Functions
RepeatedState (std::shared_ptr< const Game > game, std::shared_ptr< const Game > stage_game, int num_repetitions, int recall)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions (Player player) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyActions (const std::vector< Action > &actions) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyAction (Action action_id)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 40 of file repeated_game.h.
Constructor & Destructor Documentation
RepeatedState()
open_spiel::RepeatedState::RepeatedState (std::shared_ptr< const Game > game, std::shared_ptr< const Game > stage_game, int num_repetitions, int recall)
Definition at line 60 of file repeated_game.cc.
    : SimMoveState(game),
      stage_game_(stage_game),
      stage_game_state_(stage_game->NewInitialState()),
      num_repetitions_(num_repetitions),
      recall_(recall) {
  actions_history_.reserve(num_repetitions_);
  rewards_history_.reserve(num_repetitions_);
}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::RepeatedState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 217 of file repeated_game.cc.
{
  return stage_game_state_->ActionToString(player, action_id);
}
References player.
Clone()
std::unique_ptr< State > open_spiel::RepeatedState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 222 of file repeated_game.cc.
{
  return std::unique_ptr<State>(new RepeatedState(*this));
}
References RepeatedState().
CurrentPlayer()
Player open_spiel::RepeatedState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 46 of file repeated_game.h.
{
    return IsTerminal() ? kTerminalPlayerId : kSimultaneousPlayerId;
  }
References IsTerminal(), open_spiel::kSimultaneousPlayerId, and open_spiel::kTerminalPlayerId.
DoApplyActions()
void open_spiel::RepeatedState::DoApplyActions (const std::vector< Action > & actions) override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 73 of file repeated_game.cc.
{
  SPIEL_CHECK_EQ(actions.size(), num_players_);
  // Faster to clone the reference stage_game_state_ than call
  // game_->NewInitialState().
  std::unique_ptr<State> stage_game_state = stage_game_state_->Clone();
  stage_game_state->ApplyActions(actions);
  SPIEL_CHECK_TRUE(stage_game_state->IsTerminal());
  actions_history_.push_back(actions);
  rewards_history_.push_back(stage_game_state->Returns());
}
References open_spiel::State::num_players_, SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
InformationStateString()
std::string open_spiel::RepeatedState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 124 of file repeated_game.cc.
{
  std::string rv;
  if (actions_history_.empty()) return rv;
  for (int j = 0; j < actions_history_.size(); ++j) {
    for (int i = 0; i < num_players_; ++i) {
      absl::StrAppend(
          &rv, stage_game_state_->ActionToString(i, actions_history_[j][i]),
          " ");
    }
    absl::StrAppend(&rv, ";");
  }
  return rv;
}
References i, open_spiel::State::num_players_, and absl::StrAppend().
InformationStateTensor()
void open_spiel::RepeatedState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 158 of file repeated_game.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->InformationStateTensorSize());
  std::fill(values.begin(), values.end(), 0.0);
  if (actions_history_.empty()) return;
  auto ptr = values.begin();
  for (int j = 0; j < actions_history_.size(); ++j) {
    for (int i = 0; i < num_players_; ++i) {
      ptr[actions_history_[j][i]] = 1;
      ptr += stage_game_state_->LegalActions(i).size();
    }
  }
}
References open_spiel::State::game_, i, open_spiel::State::num_players_, player, ptr, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::RepeatedState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 105 of file repeated_game.cc.
{
  return actions_history_.size() == num_repetitions_;
}
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::RepeatedState::LegalActions (Player player) const override virtual
Implements open_spiel::SimMoveState.
Definition at line 212 of file repeated_game.cc.
{
  if (IsTerminal()) return {};
  return stage_game_state_->LegalActions(player);
}
References IsTerminal(), and player.
ObservationString()
std::string open_spiel::RepeatedState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 138 of file repeated_game.cc.
{
  std::string rv;
  if (actions_history_.empty()) { return rv; }
  // Starting from the back of the history, show each player's moves:
  for (int j = 0;
       j < recall_ && static_cast<int>(actions_history_.size()) - 1 - j >= 0;
       ++j) {
    int hist_idx = actions_history_.size() - 1 - j;
    SPIEL_CHECK_GE(hist_idx, 0);
    SPIEL_CHECK_LT(hist_idx, actions_history_.size());
    for (int i = 0; i < num_players_; ++i) {
      absl::StrAppend(&rv,
          stage_game_state_->ActionToString(i, actions_history_[hist_idx][i]),
          " ");
    }
  }
  return rv;
}
References i, open_spiel::State::num_players_, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrAppend().
ObservationTensor()
void open_spiel::RepeatedState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 176 of file repeated_game.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  std::fill(values.begin(), values.end(), 0.0);
  if (actions_history_.empty()) return;
  auto ptr = values.begin();
  // Starting from the back of the history, show each player's moves:
  for (int j = 0;
       j < recall_ && static_cast<int>(actions_history_.size()) - 1 - j >= 0;
       j++) {
    int hist_idx = static_cast<int>(actions_history_.size()) - 1 - j;
    SPIEL_CHECK_GE(hist_idx, 0);
    SPIEL_CHECK_LT(hist_idx, actions_history_.size());
    for (int i = 0; i < num_players_; ++i) {
      ptr[actions_history_[hist_idx][i]] = 1;
      ptr += stage_game_state_->LegalActions(i).size();
    }
  }
  SPIEL_CHECK_LE(ptr, values.end());
}
References open_spiel::State::game_, i, open_spiel::State::num_players_, player, ptr, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::RepeatedState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 114 of file repeated_game.cc.
{
  std::vector<double> returns(num_players_, 0.0);
  for (auto rewards : rewards_history_) {
    for (int i = 0; i < rewards.size(); ++i) {
      returns[i] += rewards[i];
    }
  }
  return returns;
}
References i, and open_spiel::State::num_players_.
Referenced by ToString().
Rewards()
std::vector< double > open_spiel::RepeatedState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 109 of file repeated_game.cc.
{
  return rewards_history_.empty() ? std::vector<double>(num_players_, 0.0)
                                  : rewards_history_.back();
}
References open_spiel::State::num_players_.
ToString()
std::string open_spiel::RepeatedState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 84 of file repeated_game.cc.
{
  std::string rv;
  for (int i = 0; i < actions_history_.size(); ++i) {
    absl::StrAppend(&rv, "Round ", i, ":\n");
    absl::StrAppend(&rv, "Actions: ");
    for (int j = 0; j < num_players_; ++j) {
      absl::StrAppend(
          &rv, stage_game_state_->ActionToString(j, actions_history_[i][j]),
          " ");
    }
    absl::StrAppend(&rv, "\n");
    absl::StrAppend(&rv, "Rewards: ");
    for (auto player_reward : rewards_history_[i])
      absl::StrAppend(&rv, player_reward, " ");
    absl::StrAppend(&rv, "\n");
  }
  absl::StrAppend(&rv, "Total Returns: ");
  for (auto player_return : Returns()) absl::StrAppend(&rv, player_return, " ");
  return rv;
}
References i, open_spiel::State::num_players_, Returns(), and absl::StrAppend().
The documentation for this class was generated from the following files:
open_spiel/game_transforms/repeated_game.h
open_spiel/game_transforms/repeated_game.cc