open spiel: open_spiel::quoridor::QuoridorState Class Reference
open_spiel::quoridor::QuoridorState Class Reference
#include <quoridor.h>
Classes
class SearchState
Public Member Functions
QuoridorState (std::shared_ptr< const Game > game, int board_size, int wall_count, bool ansi_color_output=false)
QuoridorState (const QuoridorState &)=default
void InitializePlayer (QuoridorPlayer)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
int NumCellStates () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Move ActionToMove (Action action_id) const
Move GetMove (int x, int y) const
bool IsWall (Move m) const
QuoridorPlayer GetPlayer (Move m) const
void SetPlayer (Move m, QuoridorPlayer p, Player old)
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 92 of file quoridor.h.
Constructor & Destructor Documentation
QuoridorState() [1/2]
open_spiel::quoridor::QuoridorState::QuoridorState (std::shared_ptr< const Game > game, int board_size, int wall_count, bool ansi_color_output = false)
Definition at line 151 of file quoridor.cc.
    : State(game),
      board_size_(board_size),
      board_diameter_(board_size * 2 - 1),
      ansi_color_output_(ansi_color_output),
      // See ActionToMove for explanation of the below
      base_for_relative_(2, 2, board_diameter_) {
  board_.resize(board_diameter_ * board_diameter_, kPlayerNone);
  players_.resize(num_players_);
  // Account for order of turns (order of play is clockwise)
  if (num_players_ == 2) {
    players_[0] = kPlayer1;
    players_[1] = kPlayer2;
  } else if (num_players_ == 3) {
    players_[0] = kPlayer1;
    players_[1] = kPlayer3;
    players_[2] = kPlayer2;
  } else if (num_players_ == 4) {
    players_[0] = kPlayer1;
    players_[1] = kPlayer3;
    players_[2] = kPlayer2;
    players_[3] = kPlayer4;
  }
  wall_count_.resize(num_players_);
  player_loc_.resize(num_players_);
  end_zone_.resize(num_players_);
  for (int i = 0; i < num_players_; ++i) {
    wall_count_[players_[i]] = wall_count;
    InitializePlayer(players_[i]);
  }
}
References i, InitializePlayer(), open_spiel::quoridor::kPlayer1, open_spiel::quoridor::kPlayer2, open_spiel::quoridor::kPlayer3, open_spiel::quoridor::kPlayer4, open_spiel::quoridor::kPlayerNone, and open_spiel::State::num_players_.
Referenced by Clone().
QuoridorState() [2/2]
open_spiel::quoridor::QuoridorState::QuoridorState (const QuoridorState &) default
Member Function Documentation
ActionToMove()
Move open_spiel::quoridor::QuoridorState::ActionToMove (Action action_id) const protected
Definition at line 220 of file quoridor.cc.
{
  Move move = GetMove(action_id % board_diameter_, action_id / board_diameter_);
  if (!move.IsWall()) {
    Move target = player_loc_[current_player_] + (move - base_for_relative_);
    if (GetPlayer(target) == kPlayerNone) {
      return target;
    } else {
      // Jumping over a player is inferred - it has the same action ID as just
      // stepping
      return player_loc_[current_player_] + ((move - base_for_relative_) * 2);
    }
  }
  return move;
}
References GetMove(), GetPlayer(), and open_spiel::quoridor::kPlayerNone.
Referenced by ActionToString(), and DoApplyAction().
ActionToString()
std::string open_spiel::quoridor::QuoridorState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 465 of file quoridor.cc.
{
  return ActionToMove(action_id).ToString();
}
References ActionToMove(), and open_spiel::quoridor::Move::ToString().
Clone()
std::unique_ptr< State > open_spiel::quoridor::QuoridorState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 659 of file quoridor.cc.
{
  return std::unique_ptr<State>(new QuoridorState(*this));
}
References QuoridorState().
CurrentPlayer()
Player open_spiel::quoridor::QuoridorState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 100 of file quoridor.h.
{
    return IsTerminal() ? kTerminalPlayerId : static_cast<int>(current_player_);
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::quoridor::QuoridorState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 614 of file quoridor.cc.
{
  Move move = ActionToMove(action);
  // If players is forced to pass it is valid to stay in place, on a field where
  // there is already a player
  if (board_[move.xy] != current_player_) {
    SPIEL_CHECK_EQ(board_[move.xy], kPlayerNone);
  }
  SPIEL_CHECK_EQ(outcome_, kPlayerNone);
  SPIEL_CHECK_TRUE(move.IsValid());
  if (move.IsWall()) {
    Offset offset = (move.IsHorizontalWall() ? Offset(1, 0) : Offset(0, 1));
    SetPlayer(move + offset * 0, kPlayerWall, kPlayerNone);
    SetPlayer(move + offset * 1, kPlayerWall, kPlayerNone);
    SetPlayer(move + offset * 2, kPlayerWall, kPlayerNone);
    wall_count_[current_player_] -= 1;
  } else {
    SetPlayer(player_loc_[current_player_], kPlayerNone, current_player_);
    SetPlayer(move, current_player_, kPlayerNone);
    player_loc_[current_player_] = move;
    int end_zone_coord;
    if (current_player_ == kPlayer1 || current_player_ == kPlayer2) {
      end_zone_coord = move.y;
    } else {
      end_zone_coord = move.x;
    }
    outcome_ = kPlayerNone;
    if (end_zone_coord == end_zone_[current_player_]) {
      outcome_ = current_player_;
    }
  }
  ++moves_made_;
  if (moves_made_ >= kMaxGameLengthFactor * board_size_ * board_size_) {
    outcome_ = kPlayerDraw;
  }
  current_player_index_ += 1;
  if (current_player_index_ == num_players_) current_player_index_ = 0;
  current_player_ = players_[current_player_index_];
}
References action, ActionToMove(), open_spiel::quoridor::kMaxGameLengthFactor, open_spiel::quoridor::kPlayer1, open_spiel::quoridor::kPlayer2, open_spiel::quoridor::kPlayerDraw, open_spiel::quoridor::kPlayerNone, open_spiel::quoridor::kPlayerWall, open_spiel::State::num_players_, SetPlayer(), SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
GetMove()
Move open_spiel::quoridor::QuoridorState::GetMove (int x, int y) const inline protected
Definition at line 121 of file quoridor.h.
{ return Move(x, y, board_diameter_); }
References x, and y.
Referenced by ActionToMove(), InitializePlayer(), LegalActions(), and ToString().
GetPlayer()
QuoridorPlayer open_spiel::quoridor::QuoridorState::GetPlayer (Move m) const inline protected
Definition at line 125 of file quoridor.h.
{
    return m.IsValid() ? board_[m.xy] : kPlayerWall;
  }
References open_spiel::quoridor::Move::IsValid(), open_spiel::quoridor::kPlayerWall, and open_spiel::quoridor::Move::xy.
Referenced by ActionToMove(), and ToString().
InformationStateString()
std::string open_spiel::quoridor::QuoridorState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 583 of file quoridor.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
InitializePlayer()
void open_spiel::quoridor::QuoridorState::InitializePlayer (QuoridorPlayer p)
Definition at line 184 of file quoridor.cc.
{
  int center_field = board_size_ - (board_size_ % 2);
  if (p == kPlayer1) {
    player_loc_[p] = GetMove(center_field, board_diameter_ - 1);
    SetPlayer(player_loc_[p], p, kPlayerNone);
    end_zone_[p] = 0;
    return;
  }
  if (p == kPlayer2) {
    player_loc_[p] = GetMove(center_field, 0);
    SetPlayer(player_loc_[p], kPlayer2, kPlayerNone);
    end_zone_[p] = board_diameter_ - 1;
    return;
  }
  if (p == kPlayer3) {
    player_loc_[p] = GetMove(0, center_field);
    SetPlayer(player_loc_[p], p, kPlayerNone);
    end_zone_[p] = board_diameter_ - 1;
    return;
  }
  if (p == kPlayer4) {
    player_loc_[p] = GetMove(board_diameter_ - 1, center_field);
    SetPlayer(player_loc_[p], p, kPlayerNone);
    end_zone_[p] = 0;
    return;
  }
}
References GetMove(), open_spiel::quoridor::kPlayer1, open_spiel::quoridor::kPlayer2, open_spiel::quoridor::kPlayer3, open_spiel::quoridor::kPlayer4, open_spiel::quoridor::kPlayerNone, and SetPlayer().
Referenced by QuoridorState().
IsTerminal()
bool open_spiel::quoridor::QuoridorState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 105 of file quoridor.h.
{ return outcome_ != kPlayerNone; }
References open_spiel::quoridor::kPlayerNone.
Referenced by CurrentPlayer(), and LegalActions().
IsWall()
bool open_spiel::quoridor::QuoridorState::IsWall (Move m) const inline protected
Definition at line 122 of file quoridor.h.
{
    return m.IsValid() ? board_[m.xy] == kPlayerWall : true;
  }
References open_spiel::quoridor::Move::IsValid(), open_spiel::quoridor::kPlayerWall, and open_spiel::quoridor::Move::xy.
LegalActions()
std::vector< Action > open_spiel::quoridor::QuoridorState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 235 of file quoridor.cc.
{
  std::vector<Action> moves;
  if (IsTerminal()) return moves;
  int max_moves =
      num_players_ > 2 ? 6 : 5;  // Max legal pawn moves, including jumps.
  if (wall_count_[current_player_] > 0) {
    max_moves += 2 * (board_size_ - 1) * (board_size_ - 1);  // Max wall moves.
  }
  moves.reserve(max_moves);
  // Pawn moves.
  Move cur = player_loc_[current_player_];
  AddActions(cur, Offset(1, 0), &moves);
  AddActions(cur, Offset(0, 1), &moves);
  AddActions(cur, Offset(-1, 0), &moves);
  AddActions(cur, Offset(0, -1), &moves);
  // Wall placements.
  if (wall_count_[current_player_] > 0) {
    SearchState search_state(board_diameter_);
    for (int i = 0; i < num_players_; ++i) {
      SearchShortestPath(players_[i], &search_state);
    }
    for (int y = 0; y < board_diameter_ - 2; y += 2) {
      for (int x = 0; x < board_diameter_ - 2; x += 2) {
        Move h = GetMove(x, y + 1);
        if (IsValidWall(h, &search_state)) {
          moves.push_back(h.xy);
        }
        Move v = GetMove(x + 1, y);
        if (IsValidWall(v, &search_state)) {
          moves.push_back(v.xy);
        }
      }
    }
  }
  // If no action is possible add 'pass' action to list of moves
  if (moves.empty()) {
    moves.push_back(cur.xy);
  }
  std::sort(moves.begin(), moves.end());
  return moves;
}
References GetMove(), i, IsTerminal(), open_spiel::State::num_players_, x, open_spiel::quoridor::Move::xy, and y.
NumCellStates()
int open_spiel::quoridor::QuoridorState::NumCellStates () const inline
Definition at line 113 of file quoridor.h.
{ return num_players_ + 1; }
References open_spiel::State::num_players_.
Referenced by ObservationTensor().
ObservationString()
std::string open_spiel::quoridor::QuoridorState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 589 of file quoridor.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::quoridor::QuoridorState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 595 of file quoridor.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<2> view(
      values, {NumCellStates() + num_players_, static_cast<int>(board_.size())},
      true);
  for (int i = 0; i < board_.size(); ++i) {
    if (board_[i] < NumCellStates()) {
      view[{static_cast<int>(board_[i]), i}] = 1.0;
    }
    for (int j = 0; j < num_players_; ++j) {
      view[{NumCellStates() + players_[j], i}] = wall_count_[players_[j]];
    }
  }
}
References i, open_spiel::State::num_players_, NumCellStates(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::quoridor::QuoridorState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 569 of file quoridor.cc.
{
  std::vector<double> res(num_players_, 0.0);
  for (int i = 0; i < num_players_; ++i) {
    if (outcome_ == players_[i]) {
      // If someone as won, set their reward to +1 and all the others to
      // -1 / (num_players - 1).
      std::fill(res.begin(), res.end(), -1.0 / (num_players_ - 1));
      res[i] = 1.0;
      break;
    }
  }
  return res;
}
References i, and open_spiel::State::num_players_.
SetPlayer()
void open_spiel::quoridor::QuoridorState::SetPlayer (Move m, QuoridorPlayer p, Player old) inline protected
Definition at line 128 of file quoridor.h.
{
    SPIEL_CHECK_TRUE(m.IsValid());
    SPIEL_CHECK_EQ(board_[m.xy], old);
    board_[m.xy] = p;
  }
References open_spiel::quoridor::Move::IsValid(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and open_spiel::quoridor::Move::xy.
Referenced by DoApplyAction(), and InitializePlayer().
ToString()
std::string open_spiel::quoridor::QuoridorState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 470 of file quoridor.cc.
{
  // Generates something like:
  // Board size: 5, walls: 0, 0
  //    a   b   c   d   e
  //  1 . | .   .   .   . 1
  //      +        ---+---
  //  2 . | . | .   .   . 2
  //          +
  //  3 .   . | O   @   . 3
  //   ---+---
  //  4 . | .   .   .   . 4
  //      +    ---+---
  //  5 . | .   .   .   . 5
  //    a   b   c   d   e
  std::string reset;
  std::array<std::string, 4> colors, coords;
  if (ansi_color_output_) {
    std::string esc = "\033";
    reset = esc + "[0m";
    coords[0] = esc + "[1;33m";
    coords[1] = esc + "[1;34m";
    coords[2] = esc + "[1;35m";
    coords[3] = esc + "[1;36m";
    colors[0] = esc + "[1;33m" + " O " + reset;
    colors[1] = esc + "[1;34m" + " @ " + reset;
    colors[2] = esc + "[1;35m" + " # " + reset;
    colors[3] = esc + "[1;36m" + " % " + reset;
  } else {
    std::string reset = "";
    coords[0] = "";
    coords[1] = "";
    coords[2] = "";
    coords[3] = "";
    colors[0] = " 0 ";
    colors[1] = " @ ";
    colors[2] = " # ";
    colors[3] = " % ";
  }
  std::ostringstream out;
  out << "Board size: " << board_size_ << ", walls: ";
  for (int i = 0; i < num_players_; ++i) {
    out << wall_count_[players_[i]];
    if (i < num_players_ - 1) out << ", ";
  }
  out << "\n";
  // Top x coords.
  for (int x = 0; x < board_size_; ++x) {
    out << "   " << coords[1] << static_cast<char>('a' + x);
  }
  out << reset << '\n';
  for (int y = 0; y < board_diameter_; ++y) {
    if (y % 2 == 0) {
      if (y / 2 + 1 < 10) out << " ";
      out << coords[2] << (y / 2 + 1) << reset;  // Leading y coord.
    } else {
      out << "  ";  // Wall lines.
    }
    for (int x = 0; x < board_diameter_; ++x) {
      QuoridorPlayer p = GetPlayer(GetMove(x, y));
      if (x % 2 == 0 && y % 2 == 0) {
        bool playerFound = false;
        for (int i = 0; i < num_players_; ++i) {
          if (p == players_[i]) {
            out << colors[players_[i]];
            playerFound = true;
          }
        }
        if (!playerFound) {
          out << " . ";
        }
      } else if (x % 2 == 1 && y % 2 == 1) {
        out << (p == kPlayerWall ? "+" : " ");
      } else if (x % 2 == 1) {
        out << (p == kPlayerWall ? "|" : " ");
      } else if (y % 2 == 1) {
        out << (p == kPlayerWall ? "---" : "   ");
      }
    }
    if (y % 2 == 0) {
      if (y / 2 + 1 < 10) out << " ";
      out << coords[3] << (y / 2 + 1) << reset;  // y coord on the right.
    } else {
      out << "  ";  // Wall lines.
    }
    out << '\n';
  }
  // Bottom x coords.
  for (int x = 0; x < board_size_; ++x) {
    out << "   " << coords[0] << static_cast<char>('a' + x);
  }
  out << reset << '\n';
  return out.str();
}
References GetMove(), GetPlayer(), i, open_spiel::quoridor::kPlayerWall, open_spiel::State::num_players_, out, x, and y.
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/quoridor/quoridor.h
open_spiel/games/quoridor/quoridor.cc