open spiel: open_spiel::GameParameter Class Reference
open_spiel::GameParameter Class Reference
#include <game_parameters.h>
Public Types
enum class Type {
kUnset = -1 , kInt , kDouble , kString ,
kBool , kGame
}
Public Member Functions
GameParameter (Type type=Type::kUnset, bool is_mandatory=false)
GameParameter (int value, bool is_mandatory=false)
GameParameter (double value, bool is_mandatory=false)
GameParameter (std::string value, bool is_mandatory=false)
GameParameter (const char *value, bool is_mandatory=false)
GameParameter (bool value, bool is_mandatory=false)
GameParameter (GameParameters value, bool is_mandatory=false)
bool has_int_value () const
bool has_double_value () const
bool has_string_value () const
bool has_bool_value () const
bool has_game_value () const
Type type () const
bool is_mandatory () const
std::string ToString () const
std::string ToReprString () const
std::string Serialize (const std::string &delimiter=kDefaultInternalDelimiter) const
int int_value () const
double double_value () const
const std::string & string_value () const
bool bool_value () const
const GameParameters & game_value () const
template<typename T >
T value () const
template<typename T >
T value_with_default (T default_value) const
bool operator== (const GameParameter &rhs) const
bool operator!= (const GameParameter &rhs) const
template<>
int value () const
template<>
double value () const
template<>
const std::string & value () const
template<>
std::string value () const
template<>
bool value () const
template<>
const GameParameters & value () const
template<>
GameParameters value () const
template<>
int value_with_default (int default_value) const
template<>
double value_with_default (double default_value) const
template<>
const std::string & value_with_default (const std::string &default_value) const
template<>
std::string value_with_default (std::string default_value) const
template<>
bool value_with_default (bool default_value) const
Detailed Description
Definition at line 46 of file game_parameters.h.
Member Enumeration Documentation
Type
enum class open_spiel::GameParameter::Type strong
Enumerator
kUnset
kInt
kDouble
kString
kBool
kGame
Definition at line 48 of file game_parameters.h.
{ kUnset = -1, kInt, kDouble, kString, kBool, kGame };
Constructor & Destructor Documentation
GameParameter() [1/7]
open_spiel::GameParameter::GameParameter (Type type = Type::kUnset, bool is_mandatory = false) inline explicit
Definition at line 50 of file game_parameters.h.
      : is_mandatory_(is_mandatory), type_(type) {}
GameParameter() [2/7]
open_spiel::GameParameter::GameParameter (int value, bool is_mandatory = false) inline explicit
Definition at line 53 of file game_parameters.h.
      : is_mandatory_(is_mandatory), int_value_(value), type_(Type::kInt) {}
GameParameter() [3/7]
open_spiel::GameParameter::GameParameter (double value, bool is_mandatory = false) inline explicit
Definition at line 56 of file game_parameters.h.
      : is_mandatory_(is_mandatory),
        double_value_(value),
        type_(Type::kDouble) {}
GameParameter() [4/7]
open_spiel::GameParameter::GameParameter (std::string value, bool is_mandatory = false) inline explicit
Definition at line 61 of file game_parameters.h.
      : is_mandatory_(is_mandatory),
        string_value_(value),
        type_(Type::kString) {}
GameParameter() [5/7]
open_spiel::GameParameter::GameParameter (const char * value, bool is_mandatory = false) inline explicit
Definition at line 75 of file game_parameters.h.
      : is_mandatory_(is_mandatory),
        string_value_(value),
        type_(Type::kString) {}
GameParameter() [6/7]
open_spiel::GameParameter::GameParameter (bool value, bool is_mandatory = false) inline explicit
Definition at line 80 of file game_parameters.h.
      : is_mandatory_(is_mandatory), bool_value_(value), type_(Type::kBool) {}
GameParameter() [7/7]
open_spiel::GameParameter::GameParameter (GameParameters value, bool is_mandatory = false) inline explicit
Definition at line 83 of file game_parameters.h.
      : is_mandatory_(is_mandatory),
        game_value_(std::move(value)),
        type_(Type::kGame) {}
Member Function Documentation
bool_value()
bool open_spiel::GameParameter::bool_value () const inline
Definition at line 126 of file game_parameters.h.
{
    SPIEL_CHECK_TRUE(type_ == Type::kBool);
    return bool_value_;
  }
References kBool, and SPIEL_CHECK_TRUE.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), operator==(), ToReprString(), ToString(), value(), and value_with_default().
double_value()
double open_spiel::GameParameter::double_value () const inline
Definition at line 116 of file game_parameters.h.
{
    SPIEL_CHECK_TRUE(type_ == Type::kDouble);
    return double_value_;
  }
References kDouble, and SPIEL_CHECK_TRUE.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), operator==(), ToReprString(), ToString(), value(), and value_with_default().
game_value()
const GameParameters & open_spiel::GameParameter::game_value () const inline
Definition at line 131 of file game_parameters.h.
{
    SPIEL_CHECK_TRUE(type_ == Type::kGame);
    return game_value_;
  }
References kGame, and SPIEL_CHECK_TRUE.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), operator==(), Serialize(), ToReprString(), ToString(), and value().
has_bool_value()
bool open_spiel::GameParameter::has_bool_value () const inline
Definition at line 92 of file game_parameters.h.
{ return type_ == Type::kBool; }
References kBool.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), operator==(), and value_with_default().
has_double_value()
bool open_spiel::GameParameter::has_double_value () const inline
Definition at line 90 of file game_parameters.h.
{ return type_ == Type::kDouble; }
References kDouble.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), operator==(), and value_with_default().
has_game_value()
bool open_spiel::GameParameter::has_game_value () const inline
Definition at line 93 of file game_parameters.h.
{ return type_ == Type::kGame; }
References kGame.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), and operator==().
has_int_value()
bool open_spiel::GameParameter::has_int_value () const inline
Definition at line 89 of file game_parameters.h.
{ return type_ == Type::kInt; }
References kInt.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), operator==(), and value_with_default().
has_string_value()
bool open_spiel::GameParameter::has_string_value () const inline
Definition at line 91 of file game_parameters.h.
{ return type_ == Type::kString; }
References kString.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), operator==(), value_with_default(), and value_with_default().
int_value()
int open_spiel::GameParameter::int_value () const inline
Definition at line 111 of file game_parameters.h.
{
    SPIEL_CHECK_TRUE(type_ == Type::kInt);
    return int_value_;
  }
References kInt, and SPIEL_CHECK_TRUE.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), operator==(), ToReprString(), ToString(), value(), and value_with_default().
is_mandatory()
bool open_spiel::GameParameter::is_mandatory () const inline
Definition at line 96 of file game_parameters.h.
{ return is_mandatory_; }
Referenced by define_julia_module(), and Serialize().
operator!=()
bool open_spiel::GameParameter::operator!= (const GameParameter & rhs) const inline
Definition at line 165 of file game_parameters.h.
{ return !(*this == rhs); }
operator==()
bool open_spiel::GameParameter::operator== (const GameParameter & rhs) const inline
Definition at line 146 of file game_parameters.h.
{
    switch (type_) {
      case Type::kInt:
        return rhs.has_int_value() && int_value_ == rhs.int_value();
      case Type::kDouble:
        return rhs.has_double_value() && double_value_ == rhs.double_value();
      case Type::kString:
        return rhs.has_string_value() && string_value_ == rhs.string_value();
      case Type::kBool:
        return rhs.has_bool_value() && bool_value_ == rhs.bool_value();
      case Type::kGame:
        return rhs.has_game_value() && game_value_ == rhs.game_value();
      case Type::kUnset:
        return rhs.type_ == Type::kUnset;
    }
    std::cerr << "Unrecognized parameter type in operator=="
              << ", returning false." << std::endl;
    return false;
  }
References bool_value(), double_value(), game_value(), has_bool_value(), has_double_value(), has_game_value(), has_int_value(), has_string_value(), int_value(), kBool, kDouble, kGame, kInt, kString, kUnset, and string_value().
Serialize()
std::string open_spiel::GameParameter::Serialize (const std::string & delimiter = kDefaultInternalDelimiter) const
Definition at line 77 of file game_parameters.cc.
{
  std::string val;
  switch (type_) {
    case Type::kString:
      val = absl::StrReplaceAll(ToString(), {{"\n", kSerializedNewline}});
      break;
    case Type::kGame:
      val = SerializeGameParameters(game_value());
      break;
    default:
      val = ToString();
  }
  return absl::StrCat(GameParameterTypeToString(type_), delimiter, val,
                      delimiter, is_mandatory() ? "true" : "false");
}
References game_value(), open_spiel::GameParameterTypeToString(), is_mandatory(), kGame, kString, open_spiel::SerializeGameParameters(), absl::StrCat(), absl::StrReplaceAll(), and ToString().
Referenced by open_spiel::SerializeGameParameters().
string_value()
const std::string & open_spiel::GameParameter::string_value () const inline
Definition at line 121 of file game_parameters.h.
{
    SPIEL_CHECK_TRUE(type_ == Type::kString);
    return string_value_;
  }
References kString, and SPIEL_CHECK_TRUE.
Referenced by pybind11::detail::type_caster< open_spiel::GameParameter >::cast(), operator==(), ToReprString(), ToString(), value(), value_with_default(), and value_with_default().
ToReprString()
std::string open_spiel::GameParameter::ToReprString () const
Definition at line 35 of file game_parameters.cc.
{
  switch (type_) {
    case Type::kInt:
      return absl::StrCat("GameParameter(int_value=", int_value(), ")");
    case Type::kDouble:
      return absl::StrCat("GameParameter(double_value=", double_value(), ")");
    case Type::kString:
      return absl::StrCat("GameParameter(string_value='", string_value(), "')");
    case Type::kBool:
      return absl::StrCat(
          "GameParameter(bool_value=", bool_value() ? "True" : "False", ")");
    case Type::kUnset:
      return absl::StrCat("GameParameter()");
    case Type::kGame:
      return absl::StrCat("GameParameter(game_value=",
                          GameParametersToString(game_value()));
    default:
      SpielFatalError("Unknown type.");
      return "This will never return.";
  }
}
References bool_value(), double_value(), game_value(), open_spiel::GameParametersToString(), int_value(), kBool, kDouble, kGame, kInt, kString, kUnset, open_spiel::SpielFatalError(), absl::StrCat(), and string_value().
Referenced by define_julia_module(), and open_spiel::Game::ParameterValue().
ToString()
std::string open_spiel::GameParameter::ToString () const
Definition at line 57 of file game_parameters.cc.
{
  switch (type_) {
    case Type::kInt:
      return absl::StrCat(int_value());
    case Type::kDouble:
      return FormatDouble(double_value());
    case Type::kString:
      return string_value();
    case Type::kBool:
      return bool_value() ? std::string("True") : std::string("False");
    case Type::kUnset:
      return absl::StrCat("unset");
    case Type::kGame:
      return GameParametersToString(game_value());
    default:
      SpielFatalError("Unknown type.");
      return "This will never return.";
  }
}
References bool_value(), double_value(), open_spiel::FormatDouble(), game_value(), open_spiel::GameParametersToString(), int_value(), kBool, kDouble, kGame, kInt, kString, kUnset, open_spiel::SpielFatalError(), absl::StrCat(), and string_value().
Referenced by define_julia_module(), and Serialize().
type()
Type open_spiel::GameParameter::type () const inline
Definition at line 94 of file game_parameters.h.
{ return type_; }
value() [1/8]
template<> int open_spiel::GameParameter::value () const
Definition at line 247 of file game_parameters.cc.
{
  return int_value();
}
References int_value().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [2/8]
template<> double open_spiel::GameParameter::value () const
Definition at line 251 of file game_parameters.cc.
{
  return double_value();
}
References double_value().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [3/8]
template<> const std::string & open_spiel::GameParameter::value () const
Definition at line 255 of file game_parameters.cc.
{
  return string_value();
}
References string_value().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [4/8]
template<> std::string open_spiel::GameParameter::value () const
Definition at line 259 of file game_parameters.cc.
{
  return string_value();
}
References string_value().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [5/8]
template<> bool open_spiel::GameParameter::value () const
Definition at line 263 of file game_parameters.cc.
{
  return bool_value();
}
References bool_value().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [6/8]
template<> const GameParameters & open_spiel::GameParameter::value () const
Definition at line 267 of file game_parameters.cc.
{
  return game_value();
}
References game_value().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [7/8]
template<> GameParameters open_spiel::GameParameter::value () const
Definition at line 271 of file game_parameters.cc.
{
  return game_value();
}
References game_value().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [8/8]
template<typename T > T open_spiel::GameParameter::value () const
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel::Game::ParameterValue(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value_with_default() [1/6]
template<> bool open_spiel::GameParameter::value_with_default (bool default_value) const
Definition at line 309 of file game_parameters.cc.
{
  if (has_bool_value()) {
    return bool_value();
  } else {
    return default_value;
  }
}
References bool_value(), and has_bool_value().
value_with_default() [2/6]
template<> const std::string & open_spiel::GameParameter::value_with_default (const std::string & default_value) const
Definition at line 292 of file game_parameters.cc.
{
  if (has_string_value()) {
    return string_value();
  } else {
    return default_value;
  }
}
References has_string_value(), and string_value().
value_with_default() [3/6]
template<> double open_spiel::GameParameter::value_with_default (double default_value) const
Definition at line 284 of file game_parameters.cc.
{
  if (has_double_value()) {
    return double_value();
  } else {
    return default_value;
  }
}
References double_value(), and has_double_value().
value_with_default() [4/6]
template<> int open_spiel::GameParameter::value_with_default (int default_value) const
Definition at line 276 of file game_parameters.cc.
{
  if (has_int_value()) {
    return int_value();
  } else {
    return default_value;
  }
}
References has_int_value(), and int_value().
value_with_default() [5/6]
template<> std::string open_spiel::GameParameter::value_with_default (std::string default_value) const
Definition at line 301 of file game_parameters.cc.
{
  if (has_string_value()) {
    return string_value();
  } else {
    return default_value;
  }
}
References has_string_value(), and string_value().
value_with_default() [6/6]
template<typename T > T open_spiel::GameParameter::value_with_default (T default_value) const
The documentation for this class was generated from the following files:
open_spiel/game_parameters.h
open_spiel/game_parameters.cc