open spiel: Moves Class Reference
Moves Class Reference
#include <Moves.h>
Public Member Functions
Moves ()
~Moves ()
void Init (const int tricks, const int relStartHand, const int initialRanks[], const int initialSuits[], const unsigned short rankInSuit[DDS_HANDS][DDS_SUITS], const int trump, const int leadHand)
void Reinit (const int tricks, const int leadHand)
int MoveGen0 (const int tricks, const pos &tpos, const moveType &bestMove, const moveType &bestMoveTT, const relRanksType thrp_rel[])
int MoveGen123 (const int tricks, const int relHand, const pos &tpos)
int GetLength (const int trick, const int relHand) const
void MakeSpecific (const moveType &mply, const int trick, const int relHand)
moveType const * MakeNext (const int trick, const int relHand, const unsigned short winRanks[DDS_SUITS])
moveType const * MakeNextSimple (const int trick, const int relHand)
void Step (const int tricks, const int relHand)
void Rewind (const int tricks, const int relHand)
void Purge (const int tricks, const int relHand, const moveType forbiddenMoves[])
void Reward (const int trick, const int relHand)
const trickDataType & GetTrickData (const int tricks)
void Sort (const int tricks, const int relHand)
string PrintMoves (const int trick, const int relHand) const
void RegisterHit (const int tricks, const int relHand)
string TrickToText (const int trick) const
void PrintTrickStats (ofstream &fout) const
void PrintTrickDetails (ofstream &fout) const
void PrintFunctionStats (ofstream &fout) const
Detailed Description
Definition at line 53 of file Moves.h.
Constructor & Destructor Documentation
Moves()
Moves::Moves ()
Definition at line 40 of file Moves.cpp.
{
  funcName[MG_NT0] = "NT0";
  funcName[MG_TRUMP0] = "Trump0";
  funcName[MG_NT_VOID1] = "NT_Void1";
  funcName[MG_TRUMP_VOID1] = "Trump_Void1";
  funcName[MG_NT_NOTVOID1] = "NT_Notvoid1";
  funcName[MG_TRUMP_NOTVOID1] = "Trump_Notvoid1";
  funcName[MG_NT_VOID2] = "NT_Void2";
  funcName[MG_TRUMP_VOID2] = "Trump_Void2";
  funcName[MG_NT_NOTVOID2] = "NT_Notvoid2";
  funcName[MG_TRUMP_NOTVOID2] = "Trump_Notvoid2";
  funcName[MG_NT_VOID3] = "NT_Void3";
  funcName[MG_TRUMP_VOID3] = "Trump_Void3";
  funcName[MG_COMB_NOTVOID3] = "Comb_Notvoid3";
  for (int t = 0; t < 13; t++)
  {
    for (int h = 0; h < DDS_HANDS; h++)
    {
      lastCall[t][h] = MG_SIZE;
      trickTable[t][h].count = 0;
      trickSuitTable[t][h].count = 0;
      trickDetailTable [t][h].nfuncs = 0;
      trickDetailSuitTable[t][h].nfuncs = 0;
      for (int i = 0; i < MG_SIZE; i++)
      {
        trickDetailTable [t][h].list[i].count = 0;
        trickDetailSuitTable[t][h].list[i].count = 0;
      }
    }
  }
  trickFuncTable.nfuncs = 0;
  trickFuncSuitTable.nfuncs = 0;
  for (int i = 0; i < MG_SIZE; i++)
  {
    trickFuncTable .list[i].count = 0;
    trickFuncSuitTable.list[i].count = 0;
  }
  WeightList[ 4] = &Moves::WeightAllocNTNotvoid1;
  WeightList[ 5] = &Moves::WeightAllocTrumpNotvoid1;
  WeightList[ 6] = &Moves::WeightAllocNTVoid1;
  WeightList[ 7] = &Moves::WeightAllocTrumpVoid1;
  WeightList[ 8] = &Moves::WeightAllocNTNotvoid2;
  WeightList[ 9] = &Moves::WeightAllocTrumpNotvoid2;
  WeightList[10] = &Moves::WeightAllocNTVoid2;
  WeightList[11] = &Moves::WeightAllocTrumpVoid2;
  WeightList[12] = &Moves::WeightAllocCombinedNotvoid3;
  WeightList[13] = &Moves::WeightAllocCombinedNotvoid3;
  WeightList[14] = &Moves::WeightAllocNTVoid3;
  WeightList[15] = &Moves::WeightAllocTrumpVoid3;
}
References DDS_HANDS, i, MG_COMB_NOTVOID3, MG_NT0, MG_NT_NOTVOID1, MG_NT_NOTVOID2, MG_NT_VOID1, MG_NT_VOID2, MG_NT_VOID3, MG_SIZE, MG_TRUMP0, MG_TRUMP_NOTVOID1, MG_TRUMP_NOTVOID2, MG_TRUMP_VOID1, MG_TRUMP_VOID2, and MG_TRUMP_VOID3.
~Moves()
Moves::~Moves ()
Definition at line 100 of file Moves.cpp.
{
}
Member Function Documentation
GetLength()
int Moves::GetLength (const int trick, const int relHand) const
Definition at line 1650 of file Moves.cpp.
{
  return moveList[trick][relHand].last + 1;
}
References movePlyType::last.
Referenced by SolveBoardInternal().
GetTrickData()
const trickDataType & Moves::GetTrickData (const int tricks)
Definition at line 1952 of file Moves.cpp.
{
  trickDataType& data = track[tricks].trickData;
  for (int s = 0; s < DDS_SUITS; s++)
    data.playCount[s] = 0;
  for (int relh = 0; relh < DDS_HANDS; relh++)
    data.playCount[ trackp->playSuits[relh] ]++;
  int sum = 0;
  for (int s = 0; s < DDS_SUITS; s++)
    sum += data.playCount[s];
  if (sum != 4)
  {
    cout << "Sum " << sum << " is not four" << endl;
    exit(1);
  }
  data.bestRank = trackp->move[3].rank;
  data.bestSuit = trackp->move[3].suit;
  data.bestSequence = trackp->move[3].sequence;
  data.relWinner = trackp->high[3];
  return data;
}
References data, DDS_HANDS, DDS_SUITS, trickDataType::playCount, extCard::rank, extCard::sequence, and extCard::suit.
Referenced by Make3(), and Make3Simple().
Init()
void Moves::Init (const int tricks, const int relStartHand, const int initialRanks[], const int initialSuits[], const unsigned short rankInSuit[DDS_HANDS][DDS_SUITS], const int trump, const int leadHand)
Definition at line 105 of file Moves.cpp.
{
  currTrick = tricks;
  trump = ourTrump;
  if (relStartHand == 0)
    track[tricks].leadHand = ourLeadHand;
  for (int m = 0; m < 13; m++)
  {
    for (int h = 0; h < DDS_HANDS; h++)
    {
      moveList[m][h].current = 0;
      moveList[m][h].last = 0;
    }
  }
  // 0x1ffff would be enough, but this is for compatibility.
  for (int s = 0; s < DDS_SUITS; s++)
    track[tricks].removedRanks[s] = 0xffff;
  for (int h = 0; h < DDS_HANDS; h++)
    for (int s = 0; s < DDS_SUITS; s++)
      track[tricks].removedRanks[s] ^= rankInSuit[h][s];
  for (int n = 0; n < relStartHand; n++)
  {
    int s = initialSuits[n];
    int r = initialRanks[n];
    track[tricks].removedRanks[s] ^= bitMapRank[r];
  }
}
References bitMapRank, movePlyType::current, DDS_HANDS, DDS_SUITS, movePlyType::last, n, and r.
Referenced by SolveBoardInternal().
MakeNext()
moveType const * Moves::MakeNext (const int trick, const int relHand, const unsigned short winRanks[DDS_SUITS])
Definition at line 1725 of file Moves.cpp.
{
  // Find moves that are >= ourWinRanks[suit], but allow one
  // "small" move per suit.
  int * lwp = track[trick].lowestWin[relHand];
  movePlyType& list = moveList[trick][relHand];
  trackp = &track[trick];
  moveType * currp = nullptr, * prevp;
  bool found = false;
  if (list.last == -1)
    return NULL;
  else if (list.current == 0)
  {
    currp = &list.move[0];
    found = true;
  }
  else
  {
    prevp = &list.move[ list.current - 1 ];
    if (lwp[ prevp->suit ] == 0)
    {
      int low = lowestRank[ ourWinRanks[prevp->suit] ];
      if (low == 0)
        low = 15;
      if (prevp->rank < low)
        lwp[ prevp->suit ] = low;
    }
    while (list.current <= list.last && ! found)
    {
      currp = &list.move[ list.current ];
      if (currp->rank >= lwp[ currp->suit ])
        found = true;
      else
        list.current++;
    }
    if (! found)
      return NULL;
  }
  if (relHand == 0)
  {
    trackp->move[0].suit = currp->suit;
    trackp->move[0].rank = currp->rank;
    trackp->move[0].sequence = currp->sequence;
    trackp->high[0] = 0;
    trackp->leadSuit = currp->suit;
  }
  else if (currp->suit == trackp->move[relHand - 1].suit)
  {
    if (currp->rank > trackp->move[relHand - 1].rank)
    {
      trackp->move[relHand].suit = currp->suit;
      trackp->move[relHand].rank = currp->rank;
      trackp->move[relHand].sequence = currp->sequence;
      trackp->high[relHand] = relHand;
    }
    else
    {
      trackp->move[relHand] = trackp->move[relHand - 1];
      trackp->high[relHand] = trackp->high[relHand - 1];
    }
  }
  else if (currp->suit == trump)
  {
    trackp->move[relHand].suit = currp->suit;
    trackp->move[relHand].rank = currp->rank;
    trackp->move[relHand].sequence = currp->sequence;
    trackp->high[relHand] = relHand;
  }
  else
  {
    trackp->move[relHand] = trackp->move[relHand - 1];
    trackp->high[relHand] = trackp->high[relHand - 1];
  }
  trackp->playSuits[relHand] = currp->suit;
  trackp->playRanks[relHand] = currp->rank;
  if (relHand == 3)
  {
    trackType& newt = track[trick - 1];
    newt.leadHand = (trackp->leadHand + trackp->high[3]) % 4;
    int r, s;
    for (s = 0; s < DDS_SUITS; s++)
      newt.removedRanks[s] = trackp->removedRanks[s];
    for (int h = 0; h < DDS_HANDS; h++)
    {
      r = trackp->playRanks[h];
      s = trackp->playSuits[h];
      newt.removedRanks[s] |= bitMapRank[r];
    }
  }
  list.current++;
  return currp;
}
References bitMapRank, movePlyType::current, DDS_HANDS, DDS_SUITS, movePlyType::last, lowestRank, movePlyType::move, r, extCard::rank, moveType::rank, extCard::sequence, moveType::sequence, extCard::suit, moveType::suit, and trump.
Referenced by ABsearch(), ABsearch0(), ABsearch1(), ABsearch2(), and ABsearch3().
MakeNextSimple()
moveType const * Moves::MakeNextSimple (const int trick, const int relHand)
Definition at line 1835 of file Moves.cpp.
{
  // Don't worry about small moves. Why not, actually?
  movePlyType& list = moveList[trick][relHand];
  if (list.current > list.last)
    return NULL;
  const moveType& curr = list.move[list.current];
  trackp = &track[trick];
  if (relHand == 0)
  {
    trackp->move[0].suit = curr.suit;
    trackp->move[0].rank = curr.rank;
    trackp->move[0].sequence = curr.sequence;
    trackp->high[0] = 0;
    trackp->leadSuit = curr.suit;
  }
  else if (curr.suit == trackp->move[relHand-1].suit)
  {
    if (curr.rank > trackp->move[relHand-1].rank)
    {
      trackp->move[relHand].suit = curr.suit;
      trackp->move[relHand].rank = curr.rank;
      trackp->move[relHand].sequence = curr.sequence;
      trackp->high[relHand] = relHand;
    }
    else
    {
      trackp->move[relHand] = trackp->move[relHand-1];
      trackp->high[relHand] = trackp->high[relHand-1];
    }
  }
  else if (curr.suit == trump)
  {
    trackp->move[relHand].suit = curr.suit;
    trackp->move[relHand].rank = curr.rank;
    trackp->move[relHand].sequence = curr.sequence;
    trackp->high[relHand] = relHand;
  }
  else
  {
    trackp->move[relHand] = trackp->move[relHand-1];
    trackp->high[relHand] = trackp->high[relHand-1];
  }
  trackp->playSuits[relHand] = curr.suit;
  trackp->playRanks[relHand] = curr.rank;
  if (relHand == 3)
  {
    track[trick-1].leadHand = (trackp->leadHand + trackp->high[3]) % 4;
  }
  list.current++;
  return &curr;
}
References movePlyType::current, movePlyType::last, movePlyType::move, extCard::rank, moveType::rank, extCard::sequence, moveType::sequence, extCard::suit, moveType::suit, and trump.
Referenced by SolveBoardInternal().
MakeSpecific()
void Moves::MakeSpecific (const moveType & mply, const int trick, const int relHand)
Definition at line 1658 of file Moves.cpp.
{
  trackp = &track[trick];
  if (relHand == 0)
  {
    trackp->move[0].suit = ourMply.suit;
    trackp->move[0].rank = ourMply.rank;
    trackp->move[0].sequence = ourMply.sequence;
    trackp->high[0] = 0;
    trackp->leadSuit = ourMply.suit;
  }
  else if (ourMply.suit == trackp->move[relHand - 1].suit)
  {
    if (ourMply.rank > trackp->move[relHand - 1].rank)
    {
      trackp->move[relHand].suit = ourMply.suit;
      trackp->move[relHand].rank = ourMply.rank;
      trackp->move[relHand].sequence = ourMply.sequence;
      trackp->high[relHand] = relHand;
    }
    else
    {
      trackp->move[relHand] = trackp->move[relHand - 1];
      trackp->high[relHand] = trackp->high[relHand - 1];
    }
  }
  else if (ourMply.suit == trump)
  {
    trackp->move[relHand].suit = ourMply.suit;
    trackp->move[relHand].rank = ourMply.rank;
    trackp->move[relHand].sequence = ourMply.sequence;
    trackp->high[relHand] = relHand;
  }
  else
  {
    trackp->move[relHand] = trackp->move[relHand - 1];
    trackp->high[relHand] = trackp->high[relHand - 1];
  }
  trackp->playSuits[relHand] = ourMply.suit;
  trackp->playRanks[relHand] = ourMply.rank;
  if (relHand == 3)
  {
    trackType * newp = &track[trick - 1];
    newp->leadHand = (trackp->leadHand + trackp->high[3]) % 4;
    int r, s;
    for (s = 0; s < DDS_SUITS; s++)
      newp->removedRanks[s] = trackp->removedRanks[s];
    for (int h = 0; h < DDS_HANDS; h++)
    {
      r = trackp->playRanks[h];
      s = trackp->playSuits[h];
      newp->removedRanks[s] |= bitMapRank[r];
    }
  }
}
References bitMapRank, DDS_HANDS, DDS_SUITS, r, extCard::rank, moveType::rank, extCard::sequence, moveType::sequence, extCard::suit, moveType::suit, and trump.
Referenced by AnalyseLaterBoard(), and SolveBoardInternal().
MoveGen0()
int Moves::MoveGen0 (const int tricks, const pos & tpos, const moveType & bestMove, const moveType & bestMoveTT, const relRanksType thrp_rel[])
Definition at line 156 of file Moves.cpp.
{
  trackp = &track[tricks];
  leadHand = trackp->leadHand;
  currHand = leadHand;
  currTrick = tricks;
  moveGroupType * mp;
  int removed, g, rank, seq;
  movePlyType& list = moveList[tricks][0];
  mply = list.move;
  for (int s = 0; s < DDS_SUITS; s++)
    trackp->lowestWin[0][s] = 0;
  numMoves = 0;
  bool ftest = ((trump != DDS_NOTRUMP) &&
                (tpos.winner[trump].rank != 0));
  for (suit = 0; suit < DDS_SUITS; suit++)
  {
    unsigned short ris = tpos.rankInSuit[leadHand][suit];
    if (ris == 0) continue;
    lastNumMoves = numMoves;
    mp = &groupData[ris];
    g = mp->lastGroup;
    removed = trackp->removedRanks[suit];
    while (g >= 0)
    {
      rank = mp->rank[g];
      seq = mp->sequence[g];
      while (g >= 1 && ((mp->gap[g] & removed) == mp->gap[g]))
        seq |= mp->fullseq[--g];
      mply[numMoves].sequence = seq;
      mply[numMoves].suit = suit;
      mply[numMoves].rank = rank;
      numMoves++;
      g--;
    }
    if (ftest)
      Moves::WeightAllocTrump0(tpos, bestMove, bestMoveTT, thrp_rel);
    else
      Moves::WeightAllocNT0(tpos, bestMove, bestMoveTT, thrp_rel);
  }
#ifdef DDS_MOVES
  if (ftest)
    MG_REGISTER(MG_TRUMP0, 0);
  else
    MG_REGISTER(MG_NT0, 0);
#endif
  list.current = 0;
  list.last = numMoves - 1;
  if (numMoves != 1)
    Moves::MergeSort();
  return numMoves;
}
References movePlyType::current, DDS_NOTRUMP, DDS_SUITS, moveGroupType::fullseq, moveGroupType::gap, groupData, movePlyType::last, moveGroupType::lastGroup, MG_NT0, MG_REGISTER, MG_TRUMP0, movePlyType::move, highCardType::rank, moveGroupType::rank, moveType::rank, rank, pos::rankInSuit, moveGroupType::sequence, moveType::sequence, moveType::suit, and pos::winner.
Referenced by ABsearch(), ABsearch0(), and SolveBoardInternal().
MoveGen123()
int Moves::MoveGen123 (const int tricks, const int relHand, const pos & tpos)
Definition at line 227 of file Moves.cpp.
{
  trackp = &track[tricks];
  leadHand = trackp->leadHand;
  currHand = handId(leadHand, handRel);
  currTrick = tricks;
  leadSuit = track[tricks].leadSuit;
  moveGroupType * mp;
  int removed, g, rank, seq;
  movePlyType& list = moveList[tricks][handRel];
  mply = list.move;
  for (int s = 0; s < DDS_SUITS; s++)
    trackp->lowestWin[handRel][s] = 0;
  numMoves = 0;
  WeightPtr WeightFnc;
  int findex;
  int ftest = ((trump != DDS_NOTRUMP) &&
               (tpos.winner[trump].rank != 0) ? 1 : 0);
  unsigned short ris = tpos.rankInSuit[currHand][leadSuit];
  if (ris != 0)
  {
    mp = &groupData[ris];
    g = mp->lastGroup;
    removed = trackp->removedRanks[leadSuit];
    while (g >= 0)
    {
      rank = mp->rank[g];
      seq = mp->sequence[g];
      while (g >= 1 && ((mp->gap[g] & removed) == mp->gap[g]))
        seq |= mp->fullseq[--g];
      mply[numMoves].sequence = seq;
      mply[numMoves].suit = leadSuit;
      mply[numMoves].rank = rank;
      numMoves++;
      g--;
    }
    findex = 4 * handRel + ftest;
#ifdef DDS_MOVES
    MG_REGISTER(RegisterList[findex], handRel);
#endif
    list.current = 0;
    list.last = numMoves - 1;
    if (numMoves == 1)
      return numMoves;
    (this->*WeightList[findex])(tpos);
    Moves::MergeSort();
    return numMoves;
  }
  findex = 4 * handRel + ftest + 2;
#ifdef DDS_MOVES
  MG_REGISTER(RegisterList[findex], handRel);
#endif
  WeightFnc = WeightList[findex];
  for (suit = 0; suit < DDS_SUITS; suit++)
  {
    ris = tpos.rankInSuit[currHand][suit];
    if (ris == 0) continue;
    lastNumMoves = numMoves;
    mp = &groupData[ris];
    g = mp->lastGroup;
    removed = trackp->removedRanks[suit];
    while (g >= 0)
    {
      rank = mp->rank[g];
      seq = mp->sequence[g];
      while (g >= 1 && ((mp->gap[g] & removed) == mp->gap[g]))
        seq |= mp->fullseq[--g];
      mply[numMoves].sequence = seq;
      mply[numMoves].suit = suit;
      mply[numMoves].rank = rank;
      numMoves++;
      g--;
    }
    (this->*WeightFnc)(tpos);
  }
  list.current = 0;
  list.last = numMoves - 1;
  if (numMoves != 1)
    Moves::MergeSort();
  return numMoves;
}
References movePlyType::current, DDS_NOTRUMP, DDS_SUITS, moveGroupType::fullseq, moveGroupType::gap, groupData, handId, movePlyType::last, moveGroupType::lastGroup, MG_REGISTER, movePlyType::move, highCardType::rank, moveGroupType::rank, moveType::rank, rank, pos::rankInSuit, RegisterList, moveGroupType::sequence, moveType::sequence, moveType::suit, and pos::winner.
Referenced by ABsearch1(), ABsearch2(), ABsearch3(), and SolveBoardInternal().
PrintFunctionStats()
void Moves::PrintFunctionStats (ofstream & fout) const
Definition at line 2543 of file Moves.cpp.
{
  fout << "Function statistics\n\n";
  fout << Moves::PrintFunctionTable(trickFuncTable);
  fout << "\n\nFunction statistics for winning suit\n\n";
  fout << Moves::PrintFunctionTable(trickFuncSuitTable);
  fout << "\n\n";
}
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().
PrintMoves()
string Moves::PrintMoves (const int trick, const int relHand) const
Definition at line 2256 of file Moves.cpp.
{
  const movePlyType& list = moveList[trick][relHand];
  const string st = "trick " + to_string(trick) +
    " relHand " + to_string(relHand) +
    " last " + to_string(list.last) +
    " current " + to_string(list.current) + "\n";
  return st + Moves::PrintMove(list);
}
References movePlyType::current, and movePlyType::last.
PrintTrickDetails()
void Moves::PrintTrickDetails (ofstream & fout) const
Definition at line 2514 of file Moves.cpp.
{
  fout << "Trick detail statistics\n\n";
  for (int t = 12; t >= 0; t--)
  {
    for (int h = 0; h < DDS_HANDS; h++)
    {
      fout << "Trick " << t << ", relative hand " << h << "\n";
      fout << Moves::PrintFunctionTable(trickDetailTable[t][h]) << "\n";
    }
  }
  fout << "Suit detail statistics\n\n";
  for (int t = 12; t >= 0; t--)
  {
    for (int h = 0; h < DDS_HANDS; h++)
    {
      fout << "Trick " << t << ", relative hand " << h << "\n";
      fout << Moves::PrintFunctionTable(trickDetailSuitTable[t][h]) <<
        "\n";
    }
  }
  fout << "\n\n";
}
References DDS_HANDS.
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().
PrintTrickStats()
void Moves::PrintTrickStats (ofstream & fout) const
Definition at line 2504 of file Moves.cpp.
{
  fout << "Overall statistics\n\n";
  fout << Moves::PrintTrickTable(trickTable);
  fout << "\n\nStatistics for winning suit\n\n";
  fout << Moves::PrintTrickTable(trickSuitTable) << "\n\n";
}
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().
Purge()
void Moves::Purge (const int tricks, const int relHand, const moveType forbiddenMoves[])
Definition at line 1915 of file Moves.cpp.
{
  movePlyType& ourMply = moveList[trick][ourLeadHand];
  for (int k = 1; k <= 13; k++)
  {
    int s = forbiddenMoves[k].suit;
    int rank = forbiddenMoves[k].rank;
    if (rank == 0) continue;
    for (int r = 0; r <= ourMply.last; r++)
    {
      if (s == ourMply.move[r].suit &&
          rank == ourMply.move[r].rank)
      {
        /* For the forbidden move r: */
        for (int n = r; n <= ourMply.last; n++)
          ourMply.move[n] = ourMply.move[n + 1];
        ourMply.last--;
      }
    }
  }
}
References movePlyType::last, movePlyType::move, n, r, moveType::rank, rank, and moveType::suit.
Referenced by ABsearch(), ABsearch1(), ABsearch2(), and ABsearch3().
RegisterHit()
void Moves::RegisterHit (const int tricks, const int relHand)
Definition at line 2341 of file Moves.cpp.
{
  const movePlyType& list = moveList[trick][relHand];
  const int findex = lastCall[trick][relHand];
  const int len = list.last + 1;
  if (findex == -1)
  {
    cout << "RegisterHit trick " << trick <<
      " relHand " << relHand << " findex -1" << endl;
    exit(1);
  }
  const int curr = list.current;
  if (curr < 1 || curr > len)
  {
    cout << "current out of bounds" << endl;
    exit(1);
  }
  const int moveSuit = list.move[curr-1].suit;
  int numSuit = 0;
  int numSeen = 0;
  for (int i = 0; i < len; i++)
  {
    if (list.move[i].suit == moveSuit)
    {
      numSuit++;
      if (i == curr - 1)
        numSeen = numSuit;
    }
  }
  // Now we know enough to update the statistics tables.
  trickTable[trick][relHand].count++;
  trickTable[trick][relHand].sumHits += curr;
  trickTable[trick][relHand].sumLengths += len;
  trickSuitTable[trick][relHand].count++;
  trickSuitTable[trick][relHand].sumHits += numSeen;
  trickSuitTable[trick][relHand].sumLengths += numSuit;
  Moves::UpdateStatsEntry(trickDetailTable[trick][relHand],
    findex, curr, len);
  Moves::UpdateStatsEntry(trickDetailSuitTable[trick][relHand],
    findex, numSeen, numSuit);
  Moves::UpdateStatsEntry(trickFuncTable,
    findex, curr, len);
  Moves::UpdateStatsEntry(trickFuncSuitTable,
    findex, numSeen, numSuit);
}
References movePlyType::current, i, movePlyType::last, len, movePlyType::move, and moveType::suit.
Referenced by ABsearch(), ABsearch0(), ABsearch1(), ABsearch2(), and ABsearch3().
Reinit()
void Moves::Reinit (const int tricks, const int leadHand)
Definition at line 148 of file Moves.cpp.
{
  track[tricks].leadHand = ourLeadHand;
}
Referenced by SolveSameBoard().
Reward()
void Moves::Reward (const int trick, const int relHand)
Definition at line 1943 of file Moves.cpp.
{
  moveList[tricks][relHand].
  move[ moveList[tricks][relHand].current - 1 ].weight += 100;
}
References movePlyType::current.
Rewind()
void Moves::Rewind (const int tricks, const int relHand)
Definition at line 1907 of file Moves.cpp.
{
  moveList[tricks][relHand].current = 0;
}
References movePlyType::current.
Referenced by SolveBoardInternal().
Sort()
void Moves::Sort (const int tricks, const int relHand)
Definition at line 1978 of file Moves.cpp.
{
  numMoves = moveList[tricks][relHand].last + 1;
  mply = moveList[tricks][relHand].move;
  Moves::MergeSort();
}
References movePlyType::last, and movePlyType::move.
Step()
void Moves::Step (const int tricks, const int relHand)
Definition at line 1899 of file Moves.cpp.
{
  moveList[tricks][relHand].current++;
}
References movePlyType::current.
TrickToText()
string Moves::TrickToText (const int trick) const
Definition at line 2271 of file Moves.cpp.
{
  const movePlyType& listp0 = moveList[trick][0];
  const movePlyType& listp1 = moveList[trick][1];
  const movePlyType& listp2 = moveList[trick][2];
  const movePlyType& listp3 = moveList[trick][3];
  stringstream ss;
  ss << setw(16) << left << "Last trick" <<
    cardHand[ track[trick].leadHand ] << ": " <<
    cardSuit[ listp0.move[listp0.current].suit ] <<
    cardRank[ listp0.move[listp0.current].rank ] << " - " <<
    cardSuit[ listp1.move[listp1.current].suit ] <<
    cardRank[ listp1.move[listp1.current].rank ] << " - " <<
    cardSuit[ listp2.move[listp2.current].suit ] <<
    cardRank[ listp2.move[listp2.current].rank ] << " - " <<
    cardSuit[ listp3.move[listp3.current].suit ] <<
    cardRank[ listp3.move[listp3.current].rank ] << "\n";
  return ss.str();
}
References cardHand, cardRank, cardSuit, movePlyType::current, movePlyType::move, moveType::rank, and moveType::suit.
Referenced by DumpStored().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/Moves.h
open_spiel/games/bridge/double_dummy_solver/src/Moves.cpp