open spiel: absl::optional< T > Class Template Reference
absl::optional< T > Class Template Reference
#include <optional.h>
Public Types
typedef T value_type
Public Member Functions
constexpr optional () noexcept
constexpr optional (nullopt_t) noexcept
optional (const optional &)=default
optional (optional &&)=default
template<typename InPlaceT , typename... Args, absl::enable_if_t< absl::conjunction< std::is_same< InPlaceT, in_place_t >, std::is_constructible< T, Args &&... > >::value > * = nullptr>
constexpr optional (InPlaceT, Args &&... args)
template<typename U , typename... Args, typename = typename std::enable_if<std::is_constructible< T, std::initializer_list<U>&, Args&&...>::value>::type>
constexpr optional (in_place_t, std::initializer_list< U > il, Args &&... args)
template<typename U = T, typename std::enable_if< absl::conjunction< absl::negation< std::is_same< in_place_t, typename std::decay< U >::type > >, absl::negation< std::is_same< optional< T >, typename std::decay< U >::type > >, std::is_convertible< U &&, T >, std::is_constructible< T, U && > >::value, bool >::type = false>
constexpr optional (U &&v)
template<typename U = T, typename std::enable_if< absl::conjunction< absl::negation< std::is_same< in_place_t, typename std::decay< U >::type > >, absl::negation< std::is_same< optional< T >, typename std::decay< U >::type > >, absl::negation< std::is_convertible< U &&, T > >, std::is_constructible< T, U && > >::value, bool >::type = false>
constexpr optional (U &&v)
template<typename U , typename std::enable_if< absl::conjunction< absl::negation< std::is_same< T, U > >, std::is_constructible< T, const U & >, absl::negation< optional_internal::is_constructible_convertible_from_optional< T, U > >, std::is_convertible< const U &, T > >::value, bool >::type = false>
optional (const optional< U > &rhs)
template<typename U , typename std::enable_if< absl::conjunction< absl::negation< std::is_same< T, U > >, std::is_constructible< T, const U & >, absl::negation< optional_internal::is_constructible_convertible_from_optional< T, U > >, absl::negation< std::is_convertible< const U &, T > > >::value, bool >::type = false>
optional (const optional< U > &rhs)
template<typename U , typename std::enable_if< absl::conjunction< absl::negation< std::is_same< T, U > >, std::is_constructible< T, U && >, absl::negation< optional_internal::is_constructible_convertible_from_optional< T, U > >, std::is_convertible< U &&, T > >::value, bool >::type = false>
optional (optional< U > &&rhs)
template<typename U , typename std::enable_if< absl::conjunction< absl::negation< std::is_same< T, U > >, std::is_constructible< T, U && >, absl::negation< optional_internal::is_constructible_convertible_from_optional< T, U > >, absl::negation< std::is_convertible< U &&, T > > >::value, bool >::type = false>
optional (optional< U > &&rhs)
~optional ()=default
optional & operator= (nullopt_t) noexcept
optional & operator= (const optional &src)=default
optional & operator= (optional &&src)=default
template<typename U = T, int & ..., typename = typename std::enable_if<absl::conjunction< absl::negation< std::is_same<optional<T>, typename std::decay<U>::type> >, absl::negation<absl::conjunction< std::is_scalar<T>, std::is_same<T, typename std::decay<U>::type> > >, std::is_constructible<T, U>, std::is_assignable<T&, U> >::value>::type>
optional & operator= (U &&v)
template<typename U , int & ..., typename = typename std::enable_if<absl::conjunction< absl::negation<std::is_same<T, U> >, std::is_constructible<T, const U&>, std::is_assignable<T&, const U&>, absl::negation< optional_internal:: is_constructible_convertible_assignable_from_optional< T, U> > >::value>::type>
optional & operator= (const optional< U > &rhs)
template<typename U , int & ..., typename = typename std::enable_if<absl::conjunction< absl::negation<std::is_same<T, U> >, std::is_constructible<T, U>, std::is_assignable<T&, U>, absl::negation< optional_internal:: is_constructible_convertible_assignable_from_optional< T, U> > >::value>::type>
optional & operator= (optional< U > &&rhs)
ABSL_ATTRIBUTE_REINITIALIZES void reset () noexcept
template<typename... Args, typename = typename std::enable_if< std::is_constructible<T, Args&&...>::value>::type>
T & emplace (Args &&... args)
template<typename U , typename... Args, typename = typename std::enable_if<std::is_constructible< T, std::initializer_list<U>&, Args&&...>::value>::type>
T & emplace (std::initializer_list< U > il, Args &&... args)
void swap (optional &rhs) noexcept(std::is_nothrow_move_constructible< T >::value &&type_traits_internal::IsNothrowSwappable< T >::value)
const T * operator-> () const
T * operator-> ()
constexpr const T & operator* () const &
T & operator* () &
constexpr const T && operator* () const &&
T && operator* () &&
constexpr operator bool () const noexcept
constexpr bool has_value () const noexcept
constexpr const T & value () const &
T & value () &
T && value () &&
constexpr const T && value () const &&
template<typename U >
constexpr T value_or (U &&v) const &
template<typename U >
T value_or (U &&v) &&
Detailed Description
template<typename T>
class absl::optional< T >
Definition at line 119 of file optional.h.
Member Typedef Documentation
value_type
template<typename T > typedef T absl::optional< T >::value_type
Definition at line 127 of file optional.h.
Constructor & Destructor Documentation
optional() [1/12]
template<typename T > absl::optional< T >::optional () inline constexpr noexcept
Definition at line 133 of file optional.h.
{}
optional() [2/12]
template<typename T > absl::optional< T >::optional (nullopt_t) inline constexpr noexcept
Definition at line 136 of file optional.h.
{}  // NOLINT(runtime/explicit)
optional() [3/12]
template<typename T > absl::optional< T >::optional (const optional< T > &) default
optional() [4/12]
template<typename T > absl::optional< T >::optional (optional< T > &&) default
optional() [5/12]
template<typename T > template<typename InPlaceT , typename... Args, absl::enable_if_t< absl::conjunction< std::is_same< InPlaceT, in_place_t >, std::is_constructible< T, Args &&... > >::value > * = nullptr> absl::optional< T >::optional (InPlaceT , Args &&... args) inline explicit constexpr
Definition at line 152 of file optional.h.
      : data_base(in_place_t(), absl::forward<Args>(args)...) {}
optional() [6/12]
template<typename T > template<typename U , typename... Args, typename = typename std::enable_if<std::is_constructible< T, std::initializer_list<U>&, Args&&...>::value>::type> absl::optional< T >::optional (in_place_t , std::initializer_list< U > il, Args &&... args) inline explicit constexpr
Definition at line 162 of file optional.h.
      : data_base(in_place_t(), il, absl::forward<Args>(args)...) {
  }
optional() [7/12]
template<typename T > template<typename U = T, typename std::enable_if< absl::conjunction< absl::negation< std::is_same< in_place_t, typename std::decay< U >::type > >, absl::negation< std::is_same< optional< T >, typename std::decay< U >::type > >, std::is_convertible< U &&, T >, std::is_constructible< T, U && > >::value, bool >::type = false> absl::optional< T >::optional (U && v) inline constexpr
Definition at line 178 of file optional.h.
: data_base(in_place_t(), absl::forward<U>(v)) {}
optional() [8/12]
template<typename T > template<typename U = T, typename std::enable_if< absl::conjunction< absl::negation< std::is_same< in_place_t, typename std::decay< U >::type > >, absl::negation< std::is_same< optional< T >, typename std::decay< U >::type > >, absl::negation< std::is_convertible< U &&, T > >, std::is_constructible< T, U && > >::value, bool >::type = false> absl::optional< T >::optional (U && v) inline explicit constexpr
Definition at line 191 of file optional.h.
      : data_base(in_place_t(), absl::forward<U>(v)) {}
optional() [9/12]
template<typename T > template<typename U , typename std::enable_if< absl::conjunction< absl::negation< std::is_same< T, U > >, std::is_constructible< T, const U & >, absl::negation< optional_internal::is_constructible_convertible_from_optional< T, U > >, std::is_convertible< const U &, T > >::value, bool >::type = false> absl::optional< T >::optional (const optional< U > & rhs) inline
Definition at line 205 of file optional.h.
{
    if (rhs) {
      this->construct(*rhs);
    }
  }
optional() [10/12]
template<typename T > template<typename U , typename std::enable_if< absl::conjunction< absl::negation< std::is_same< T, U > >, std::is_constructible< T, const U & >, absl::negation< optional_internal::is_constructible_convertible_from_optional< T, U > >, absl::negation< std::is_convertible< const U &, T > > >::value, bool >::type = false> absl::optional< T >::optional (const optional< U > & rhs) inline explicit
Definition at line 222 of file optional.h.
{
    if (rhs) {
      this->construct(*rhs);
    }
  }
optional() [11/12]
template<typename T > template<typename U , typename std::enable_if< absl::conjunction< absl::negation< std::is_same< T, U > >, std::is_constructible< T, U && >, absl::negation< optional_internal::is_constructible_convertible_from_optional< T, U > >, std::is_convertible< U &&, T > >::value, bool >::type = false> absl::optional< T >::optional (optional< U > && rhs) inline
Definition at line 239 of file optional.h.
{
    if (rhs) {
      this->construct(std::move(*rhs));
    }
  }
optional() [12/12]
template<typename T > template<typename U , typename std::enable_if< absl::conjunction< absl::negation< std::is_same< T, U > >, std::is_constructible< T, U && >, absl::negation< optional_internal::is_constructible_convertible_from_optional< T, U > >, absl::negation< std::is_convertible< U &&, T > > >::value, bool >::type = false> absl::optional< T >::optional (optional< U > && rhs) inline explicit
Definition at line 256 of file optional.h.
{
    if (rhs) {
      this->construct(std::move(*rhs));
    }
  }
~optional()
template<typename T > absl::optional< T >::~optional () default
Member Function Documentation
emplace() [1/2]
template<typename T > template<typename... Args, typename = typename std::enable_if< std::is_constructible<T, Args&&...>::value>::type> T & absl::optional< T >::emplace (Args &&... args) inline
Definition at line 360 of file optional.h.
{
    this->destruct();
    this->construct(std::forward<Args>(args)...);
    return reference();
  }
emplace() [2/2]
template<typename T > template<typename U , typename... Args, typename = typename std::enable_if<std::is_constructible< T, std::initializer_list<U>&, Args&&...>::value>::type> T & absl::optional< T >::emplace (std::initializer_list< U > il, Args &&... args) inline
Definition at line 380 of file optional.h.
{
    this->destruct();
    this->construct(il, std::forward<Args>(args)...);
    return reference();
  }
has_value()
template<typename T > bool absl::optional< T >::has_value () const inline constexpr noexcept
Definition at line 461 of file optional.h.
{ return this->engaged_; }
Referenced by absl::hash_internal::AbslHashValue(), pybind11::test::CheckOptional(), open_spiel::testing::CheckReturnsSum(), absl::Status::ErasePayload(), absl::Status::GetPayload(), absl::LogStreamer::LogStreamer(), open_spiel::PyGame::MakeObserver(), absl::LogStreamer::operator=(), open_spiel::bridge::BridgeState::ScoreByContract(), open_spiel::bridge::BridgeState::ScoreForContracts(), open_spiel::bridge::BridgeState::Serialize(), open_spiel::chess::ChessBoard::SetCastlingRight(), absl::Status::SetPayload(), open_spiel::gin_rummy::SimpleGinRummyBot::Step(), TEST_P(), TEST_P(), open_spiel::euchre::EuchreState::ToString(), open_spiel::universal_poker::UniversalPokerGame::UniversalPokerGame(), open_spiel::MisereGame::UtilitySum(), and absl::LogStreamer::~LogStreamer().
operator bool()
template<typename T > absl::optional< T >::operator bool () const inline explicit constexpr noexcept
Definition at line 455 of file optional.h.
{ return this->engaged_; }
operator*() [1/4]
template<typename T > T & absl::optional< T >::operator* () & inline
Definition at line 433 of file optional.h.
                   {
    ABSL_HARDENING_ASSERT(this->engaged_);
    return reference();
  }
References ABSL_HARDENING_ASSERT.
operator*() [2/4]
template<typename T > T && absl::optional< T >::operator* () && inline
Definition at line 440 of file optional.h.
                     {
    ABSL_HARDENING_ASSERT(this->engaged_);
    return std::move(reference());
  }
References ABSL_HARDENING_ASSERT.
operator*() [3/4]
template<typename T > const T & absl::optional< T >::operator* () const & inline constexpr
Definition at line 430 of file optional.h.
{
    return ABSL_HARDENING_ASSERT(this->engaged_), reference();
  }
References ABSL_HARDENING_ASSERT.
operator*() [4/4]
template<typename T > const T && absl::optional< T >::operator* () const && inline constexpr
Definition at line 437 of file optional.h.
{
    return ABSL_HARDENING_ASSERT(this->engaged_), absl::move(reference());
  }
References ABSL_HARDENING_ASSERT, and absl::move().
operator->() [1/2]
template<typename T > T * absl::optional< T >::operator-> () inline
Definition at line 421 of file optional.h.
                  {
    ABSL_HARDENING_ASSERT(this->engaged_);
    return std::addressof(this->data_);
  }
References ABSL_HARDENING_ASSERT.
operator->() [2/2]
template<typename T > const T * absl::optional< T >::operator-> () const inline
Definition at line 417 of file optional.h.
{
    ABSL_HARDENING_ASSERT(this->engaged_);
    return std::addressof(this->data_);
  }
References ABSL_HARDENING_ASSERT.
operator=() [1/6]
template<typename T > optional & absl::optional< T >::operator= (const optional< T > & src) default
operator=() [2/6]
template<typename T > template<typename U , int & ..., typename = typename std::enable_if<absl::conjunction< absl::negation<std::is_same<T, U> >, std::is_constructible<T, const U&>, std::is_assignable<T&, const U&>, absl::negation< optional_internal:: is_constructible_convertible_assignable_from_optional< T, U> > >::value>::type> optional & absl::optional< T >::operator= (const optional< U > & rhs) inline
Definition at line 310 of file optional.h.
{
    if (rhs) {
      this->assign(*rhs);
    } else {
      this->destruct();
    }
    return *this;
  }
operator=() [3/6]
template<typename T > optional & absl::optional< T >::operator= (nullopt_t) inline noexcept
Definition at line 273 of file optional.h.
{
    this->destruct();
    return *this;
  }
operator=() [4/6]
template<typename T > optional & absl::optional< T >::operator= (optional< T > && src) default
operator=() [5/6]
template<typename T > template<typename U , int & ..., typename = typename std::enable_if<absl::conjunction< absl::negation<std::is_same<T, U> >, std::is_constructible<T, U>, std::is_assignable<T&, U>, absl::negation< optional_internal:: is_constructible_convertible_assignable_from_optional< T, U> > >::value>::type> optional & absl::optional< T >::operator= (optional< U > && rhs) inline
Definition at line 328 of file optional.h.
{
    if (rhs) {
      this->assign(std::move(*rhs));
    } else {
      this->destruct();
    }
    return *this;
  }
operator=() [6/6]
template<typename T > template<typename U = T, int & ..., typename = typename std::enable_if<absl::conjunction< absl::negation< std::is_same<optional<T>, typename std::decay<U>::type> >, absl::negation<absl::conjunction< std::is_scalar<T>, std::is_same<T, typename std::decay<U>::type> > >, std::is_constructible<T, U>, std::is_assignable<T&, U> >::value>::type> optional & absl::optional< T >::operator= (U && v) inline
Definition at line 295 of file optional.h.
{
    this->assign(std::forward<U>(v));
    return *this;
  }
References absl::v.
reset()
template<typename T > ABSL_ATTRIBUTE_REINITIALIZES void absl::optional< T >::reset () inline noexcept
Definition at line 342 of file optional.h.
{ this->destruct(); }
Referenced by open_spiel.python.utils.stats.BasicStats::__init__(), open_spiel::chess::ChessState::DoApplyAction(), open_spiel::dark_chess::DarkChessState::DoApplyAction(), open_spiel::kriegspiel::KriegspielState::DoApplyAction(), open_spiel::rbc::RbcState::DoApplyAction(), open_spiel.python.algorithms.ismcts.ISMCTSBot::run_search(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
swap()
template<typename T > void absl::optional< T >::swap (optional< T > & rhs) inline noexcept
Definition at line 389 of file optional.h.
{
    if (*this) {
      if (rhs) {
        type_traits_internal::Swap(**this, *rhs);
      } else {
        rhs.construct(std::move(**this));
        this->destruct();
      }
    } else {
      if (rhs) {
        this->construct(std::move(*rhs));
        rhs.destruct();
      } else {
        // No effect (swap(disengaged, disengaged)).
      }
    }
  }
value() [1/4]
template<typename T > T & absl::optional< T >::value () & inline
Definition at line 480 of file optional.h.
               {
    return static_cast<bool>(*this)
               ? reference()
               : (optional_internal::throw_bad_optional_access(), reference());
  }
References absl::optional_internal::throw_bad_optional_access().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [2/4]
template<typename T > T && absl::optional< T >::value () && inline
Definition at line 485 of file optional.h.
                 {  // NOLINT(build/c++11)
    return std::move(
        static_cast<bool>(*this)
            ? reference()
            : (optional_internal::throw_bad_optional_access(), reference()));
  }
References absl::optional_internal::throw_bad_optional_access().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [3/4]
template<typename T > const T & absl::optional< T >::value () const & inline constexpr
Definition at line 475 of file optional.h.
{
    return static_cast<bool>(*this)
               ? reference()
               : (optional_internal::throw_bad_optional_access(), reference());
  }
References absl::optional_internal::throw_bad_optional_access().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), pybind11::test::CheckOptional(), absl::Status::ErasePayload(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), absl::Status::GetPayload(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel::Game::MakeBuiltInObserver(), open_spiel::PyGame::MakeObserver(), open_spiel::efg_game::EFGGame::MaxUtility(), open_spiel::efg_game::EFGGame::MinUtility(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), absl::Status::SetPayload(), open_spiel::euchre::EuchreState::ToString(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [4/4]
template<typename T > const T && absl::optional< T >::value () const && inline constexpr
Definition at line 491 of file optional.h.
                                       {  // NOLINT(build/c++11)
    return absl::move(
        static_cast<bool>(*this)
            ? reference()
            : (optional_internal::throw_bad_optional_access(), reference()));
  }
References absl::move(), and absl::optional_internal::throw_bad_optional_access().
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value_or() [1/2]
template<typename T > template<typename U > T absl::optional< T >::value_or (U && v) && inline
Definition at line 516 of file optional.h.
                       {  // NOLINT(build/c++11)
    static_assert(std::is_move_constructible<value_type>::value,
                  "optional<T>::value_or: T must be move constructible");
    static_assert(std::is_convertible<U&&, value_type>::value,
                  "optional<T>::value_or: U must be convertible to T");
    return static_cast<bool>(*this) ? std::move(**this)
                                    : static_cast<T>(std::forward<U>(v));
  }
References absl::v.
value_or() [2/2]
template<typename T > template<typename U > T absl::optional< T >::value_or (U && v) const & inline constexpr
Definition at line 506 of file optional.h.
{
    static_assert(std::is_copy_constructible<value_type>::value,
                  "optional<T>::value_or: T must be copy constructible");
    static_assert(std::is_convertible<U&&, value_type>::value,
                  "optional<T>::value_or: U must be convertible to T");
    return static_cast<bool>(*this)
               ? **this
               : static_cast<T>(absl::forward<U>(v));
  }
References absl::forward(), and absl::v.
Referenced by open_spiel::coordinated_mp::PenniesGame::MakeObserver(), open_spiel::dark_chess::DarkChessGame::MakeObserver(), open_spiel::gin_rummy::GinRummyGame::MakeObserver(), open_spiel::goofspiel::GoofspielGame::MakeObserver(), open_spiel::kriegspiel::KriegspielGame::MakeObserver(), open_spiel::kuhn_poker::KuhnGame::MakeObserver(), open_spiel::leduc_poker::LeducGame::MakeObserver(), open_spiel::rbc::RbcGame::MakeObserver(), open_spiel::RestrictedNashResponseGame::MakeObserver(), open_spiel::solitaire::SolitaireState::Sources(), open_spiel::solitaire::SolitaireState::Targets(), TEST_P(), and TEST_P().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/types/internal/optional.h
open_spiel/abseil-cpp/absl/types/optional.h