open spiel: open_spiel::cliff_walking::CliffWalkingState Class Reference
open_spiel::cliff_walking::CliffWalkingState Class Reference
#include <cliff_walking.h>
Public Member Functions
CliffWalkingState (std::shared_ptr< const Game > game)
CliffWalkingState (const CliffWalkingState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 77 of file cliff_walking.h.
Constructor & Destructor Documentation
CliffWalkingState() [1/2]
open_spiel::cliff_walking::CliffWalkingState::CliffWalkingState (std::shared_ptr< const Game > game)
Definition at line 59 of file cliff_walking.cc.
    : State(game) {
  const CliffWalkingGame& parent_game =
      static_cast<const CliffWalkingGame&>(*game);
  height_ = parent_game.Height();
  width_ = parent_game.Width();
  horizon_ = parent_game.MaxGameLength();
  player_row_ = parent_game.Height() - 1;
}
References open_spiel::cliff_walking::CliffWalkingGame::Height(), open_spiel::cliff_walking::CliffWalkingGame::MaxGameLength(), and open_spiel::cliff_walking::CliffWalkingGame::Width().
Referenced by Clone().
CliffWalkingState() [2/2]
open_spiel::cliff_walking::CliffWalkingState::CliffWalkingState (const CliffWalkingState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::cliff_walking::CliffWalkingState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 79 of file cliff_walking.cc.
{
  SPIEL_CHECK_EQ(player, 0);
  switch (action_id) {
    case RIGHT:
      return "RIGHT";
    case UP:
      return "UP";
    case LEFT:
      return "LEFT";
    case DOWN:
      return "DOWN";
    default:
      SpielFatalError("Out of range action");
  }
}
References player, SPIEL_CHECK_EQ, and open_spiel::SpielFatalError().
Clone()
std::unique_ptr< State > open_spiel::cliff_walking::CliffWalkingState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 162 of file cliff_walking.cc.
{
  return std::unique_ptr<State>(new CliffWalkingState(*this));
}
References CliffWalkingState().
CurrentPlayer()
int open_spiel::cliff_walking::CliffWalkingState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 69 of file cliff_walking.cc.
{
  if (IsTerminal()) return kTerminalPlayerId;
  return 0;
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::cliff_walking::CliffWalkingState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 166 of file cliff_walking.cc.
{
  switch (move) {
    case RIGHT:
      ++player_col_;
      break;
    case UP:
      --player_row_;
      break;
    case LEFT:
      --player_col_;
      break;
    case DOWN:
      ++player_row_;
      break;
    default:
      SpielFatalError("Unexpected action");
  }
  player_row_ = std::min(std::max(player_row_, 0), height_ - 1);
  player_col_ = std::min(std::max(player_col_, 0), width_ - 1);
  ++time_counter_;
}
References open_spiel::SpielFatalError().
InformationStateString()
std::string open_spiel::cliff_walking::CliffWalkingState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 131 of file cliff_walking.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
InformationStateTensor()
void open_spiel::cliff_walking::CliffWalkingState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 152 of file cliff_walking.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), kNumActions * horizon_);
  for (int i = 0; i < history_.size(); i++) {
    values[i * kNumActions + history_[i].action] = 1;
  }
}
References open_spiel::State::history_, i, open_spiel::cliff_walking::kNumActions, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::cliff_walking::CliffWalkingState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 115 of file cliff_walking.cc.
{
  return time_counter_ >= horizon_ || IsCliff(player_row_, player_col_) ||
         IsGoal(player_row_, player_col_);
}
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::cliff_walking::CliffWalkingState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 74 of file cliff_walking.cc.
{
  if (IsTerminal()) return {};
  return {RIGHT, UP, LEFT, DOWN};
}
References IsTerminal().
ObservationString()
std::string open_spiel::cliff_walking::CliffWalkingState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 137 of file cliff_walking.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::cliff_walking::CliffWalkingState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 143 of file cliff_walking.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), height_ * width_);
  std::fill(values.begin(), values.end(), 0.);
  values[player_row_ * width_ + player_col_] = 1.0;
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::cliff_walking::CliffWalkingState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 126 of file cliff_walking.cc.
{
  if (IsCliff(player_row_, player_col_)) return {-100.0 - time_counter_ + 1};
  return {time_counter_ * -1.0};
}
Rewards()
std::vector< double > open_spiel::cliff_walking::CliffWalkingState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 120 of file cliff_walking.cc.
{
  if (IsCliff(player_row_, player_col_)) return {-100.0};
  if (time_counter_ == 0) return {0.0};
  return {-1.0};
}
ToString()
std::string open_spiel::cliff_walking::CliffWalkingState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 96 of file cliff_walking.cc.
{
  std::string str;
  str.reserve(height_ * (width_ + 1));
  for (int r = 0; r < height_; ++r) {
    for (int c = 0; c < width_; ++c) {
      if (r == player_row_ && c == player_col_)
        str += 'P';
      else if (IsCliff(r, c))
        str += 'X';
      else if (IsGoal(r, c))
        str += 'G';
      else
        str += '.';
    }
    str += '\n';
  }
  return str;
}
References r.
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/cliff_walking/cliff_walking.h
open_spiel/games/cliff_walking/cliff_walking.cc