open spiel: absl::exponential_distribution< RealType >::param_type Class Reference
absl::exponential_distribution< RealType >::param_type Class Reference
#include <exponential_distribution.h>
Public Types
using distribution_type = exponential_distribution
Public Member Functions
param_type (result_type lambda=1)
result_type lambda () const
Friends
class exponential_distribution
bool operator== (const param_type &a, const param_type &b)
bool operator!= (const param_type &a, const param_type &b)
Detailed Description
template<typename RealType = double>
class absl::exponential_distribution< RealType >::param_type
Definition at line 40 of file exponential_distribution.h.
Member Typedef Documentation
distribution_type
template<typename RealType = double> using absl::exponential_distribution< RealType >::param_type::distribution_type = exponential_distribution
Definition at line 42 of file exponential_distribution.h.
Constructor & Destructor Documentation
param_type()
template<typename RealType = double> absl::exponential_distribution< RealType >::param_type::param_type (result_type lambda = 1) inline explicit
Definition at line 44 of file exponential_distribution.h.
                                                : lambda_(lambda) {
      assert(lambda > 0);
      neg_inv_lambda_ = -result_type(1) / lambda_;
    }
References absl::exponential_distribution< RealType >::param_type::lambda().
Member Function Documentation
lambda()
template<typename RealType = double> result_type absl::exponential_distribution< RealType >::param_type::lambda () const inline
Definition at line 49 of file exponential_distribution.h.
{ return lambda_; }
Referenced by absl::exponential_distribution< RealType >::lambda(), and absl::exponential_distribution< RealType >::param_type::param_type().
Friends And Related Symbol Documentation
exponential_distribution
template<typename RealType = double> friend class exponential_distribution friend
Definition at line 60 of file exponential_distribution.h.
operator!=
template<typename RealType = double> bool operator!= (const param_type & a, const param_type & b) friend
Definition at line 55 of file exponential_distribution.h.
{
      return !(a == b);
    }
operator==
template<typename RealType = double> bool operator== (const param_type & a, const param_type & b) friend
Definition at line 51 of file exponential_distribution.h.
{
      return a.lambda_ == b.lambda_;
    }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/random/exponential_distribution.h