open spiel: open_spiel::kriegspiel::KriegspielState Class Reference
open_spiel::kriegspiel::KriegspielState Class Reference
#include <kriegspiel.h>
Public Member Functions
KriegspielState (std::shared_ptr< const Game > game, int board_size, const std::string &fen, bool threefold_repetition, bool rule_50_move)
KriegspielState (const KriegspielState &)=default
KriegspielState & operator= (const KriegspielState &)=default
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Friends
class KriegspielObserver
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 122 of file kriegspiel.h.
Constructor & Destructor Documentation
KriegspielState() [1/2]
open_spiel::kriegspiel::KriegspielState::KriegspielState (std::shared_ptr< const Game > game, int board_size, const std::string & fen, bool threefold_repetition, bool rule_50_move)
Definition at line 514 of file kriegspiel.cc.
    : State(game),
      start_board_(*chess::ChessBoard::BoardFromFEN(fen, board_size, false)),
      current_board_(start_board_),
      threefold_repetition_(threefold_repetition),
      rule_50_move_(rule_50_move) {
  SPIEL_CHECK_TRUE(&current_board_);
  repetitions_[current_board_.HashValue()] = 1;
}
References open_spiel::chess::ChessBoard::HashValue(), and SPIEL_CHECK_TRUE.
KriegspielState() [2/2]
open_spiel::kriegspiel::KriegspielState::KriegspielState (const KriegspielState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::kriegspiel::KriegspielState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 577 of file kriegspiel.cc.
{
  chess::Move move = ActionToMove(action, Board());
  return move.ToLAN();
}
References action.
Clone()
std::unique_ptr< State > open_spiel::kriegspiel::KriegspielState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 601 of file kriegspiel.cc.
{
  return std::make_unique<KriegspielState>(*this);
}
CurrentPlayer()
Player open_spiel::kriegspiel::KriegspielState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 133 of file kriegspiel.h.
{
    return IsTerminal() ? kTerminalPlayerId : ColorToPlayer(Board().ToPlay());
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::kriegspiel::KriegspielState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 526 of file kriegspiel.cc.
{
  cached_legal_actions_.reset();
  chess::Move move = ActionToMove(action, Board());
  KriegspielUmpireMessage msg = GetUmpireMessage(Board(), move);
  move_msg_history_.emplace_back(move, msg);
  last_umpire_msg_ = msg;
  if (msg.illegal) {
    // If the move is illegal, the player is notified about it and can play
    // again
    illegal_tried_moves_.emplace_back(move);
    cached_legal_actions_.reset();
    return;
  }
  Board().ApplyMove(move);
  illegal_tried_moves_.clear();
  ++repetitions_[current_board_.HashValue()];
}
References action, open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::kriegspiel::GetUmpireMessage(), open_spiel::chess::ChessBoard::HashValue(), and absl::optional< T >::reset().
IsTerminal()
bool open_spiel::kriegspiel::KriegspielState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 140 of file kriegspiel.h.
{ return MaybeFinalReturns().has_value(); }
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::kriegspiel::KriegspielState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 571 of file kriegspiel.cc.
{
  MaybeGenerateLegalActions();
  if (IsTerminal()) return {};
  return *cached_legal_actions_;
}
References IsTerminal().
ObservationString()
std::string open_spiel::kriegspiel::KriegspielState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 589 of file kriegspiel.cc.
{
  const auto &game = open_spiel::down_cast<const KriegspielGame &>(*game_);
  return game.default_observer_->StringFrom(*this, player);
}
References open_spiel::down_cast(), open_spiel::State::game_, and player.
ObservationTensor()
void open_spiel::kriegspiel::KriegspielState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 594 of file kriegspiel.cc.
{
  ContiguousAllocator allocator(values);
  const auto &game = open_spiel::down_cast<const KriegspielGame &>(*game_);
  game.default_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
operator=()
KriegspielState & open_spiel::kriegspiel::KriegspielState::operator= (const KriegspielState &) default
Returns()
std::vector< double > open_spiel::kriegspiel::KriegspielState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 585 of file kriegspiel.cc.
{
  return MaybeFinalReturns().value_or(std::vector<double>{0., 0.});
}
ToString()
std::string open_spiel::kriegspiel::KriegspielState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 583 of file kriegspiel.cc.
{ return Board().ToFEN(); }
References open_spiel::chess::ChessBoard::ToFEN().
UndoAction()
void open_spiel::kriegspiel::KriegspielState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 605 of file kriegspiel.cc.
{
  // TODO: Make this fast by storing undo info in another stack.
  SPIEL_CHECK_GE(move_msg_history_.size(), 1);
  --repetitions_[current_board_.HashValue()];
  move_msg_history_.pop_back();
  history_.pop_back();
  current_board_ = start_board_;
  for (const std::pair<chess::Move, KriegspielUmpireMessage> &move_msg_pair :
       move_msg_history_) {
    current_board_.ApplyMove(move_msg_pair.first);
  }
}
References open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::chess::ChessBoard::HashValue(), open_spiel::State::history_, and SPIEL_CHECK_GE.
Friends And Related Symbol Documentation
KriegspielObserver
friend class KriegspielObserver friend
Definition at line 153 of file kriegspiel.h.
The documentation for this class was generated from the following files:
open_spiel/games/kriegspiel/kriegspiel.h
open_spiel/games/kriegspiel/kriegspiel.cc