open spiel: open_spiel::dark_hex::DarkHexState Class Reference
open_spiel::dark_hex::DarkHexState Class Reference
#include <dark_hex.h>
Public Member Functions
DarkHexState (std::shared_ptr< const Game > game, int num_cols, int num_rows, GameVersion game_version, ObservationType obs_type)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
std::string ViewToString (Player player) const
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 90 of file dark_hex.h.
Constructor & Destructor Documentation
DarkHexState()
open_spiel::dark_hex::DarkHexState::DarkHexState (std::shared_ptr< const Game > game, int num_cols, int num_rows, GameVersion game_version, ObservationType obs_type)
Definition at line 101 of file dark_hex.cc.
    : State(game),
      state_(game, num_cols, num_rows),
      obs_type_(obs_type),
      game_version_(game_version),
      num_cols_(num_cols),
      num_rows_(num_rows),
      num_cells_(num_cols * num_rows),
      bits_per_action_(num_cells_ + 1),
      longest_sequence_(num_cells_ * 2 - 1) {
  black_view_.resize(num_cols * num_rows, CellState::kEmpty);
  white_view_.resize(num_cols * num_rows, CellState::kEmpty);
}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::dark_hex::DarkHexState::ActionToString (Player player, Action action_id) const inline override virtual
Implements open_spiel::State.
Definition at line 97 of file dark_hex.h.
{
    return state_.ActionToString(player, action_id);
  }
References open_spiel::hex::HexState::ActionToString(), and player.
Clone()
std::unique_ptr< State > open_spiel::dark_hex::DarkHexState::Clone () const override virtual
Implements open_spiel::State.
Reimplemented in open_spiel::dark_hex::ImperfectRecallDarkHexState.
Definition at line 276 of file dark_hex.cc.
{
  return std::unique_ptr<State>(new DarkHexState(*this));
}
References DarkHexState().
CurrentPlayer()
Player open_spiel::dark_hex::DarkHexState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 95 of file dark_hex.h.
{ return state_.CurrentPlayer(); }
References open_spiel::hex::HexState::CurrentPlayer().
Referenced by DoApplyAction(), and LegalActions().
DoApplyAction()
void open_spiel::dark_hex::DarkHexState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 117 of file dark_hex.cc.
{
  Player cur_player = CurrentPlayer();  // current player
  auto& cur_view = (cur_player == 0 ? black_view_ : white_view_);
  // Either occupied or not
  if (game_version_ == GameVersion::kClassicalDarkHex) {
    if (state_.BoardAt(move) == CellState::kEmpty) {
      state_.ApplyAction(move);
    }
  } else {
    SPIEL_CHECK_EQ(game_version_, GameVersion::kAbruptDarkHex);
    if (state_.BoardAt(move) == CellState::kEmpty) {
      state_.ApplyAction(move);
    } else {
      // switch the current player
      state_.ChangePlayer();
    }
  }
  SPIEL_CHECK_EQ(cur_view[move], CellState::kEmpty);
  // Update the view - only using CellState::kBlack and CellState::kWhite
  if (state_.BoardAt(move) == CellState::kBlack ||
      state_.BoardAt(move) == CellState::kBlackNorth ||
      state_.BoardAt(move) == CellState::kBlackSouth) {
    cur_view[move] = CellState::kBlack;
  } else if (state_.BoardAt(move) == CellState::kWhite ||
             state_.BoardAt(move) == CellState::kWhiteEast ||
             state_.BoardAt(move) == CellState::kWhiteWest) {
    cur_view[move] = CellState::kWhite;
  } else if (state_.BoardAt(move) == CellState::kBlackWin ||
             state_.BoardAt(move) == CellState::kWhiteWin) {
    cur_view[move] = state_.BoardAt(move);
  } else {
    SPIEL_CHECK_TRUE(false);
  }
  action_sequence_.push_back(std::pair<int, Action>(cur_player, move));
}
References open_spiel::State::ApplyAction(), open_spiel::hex::HexState::BoardAt(), open_spiel::hex::HexState::ChangePlayer(), CurrentPlayer(), open_spiel::dark_hex::kAbruptDarkHex, open_spiel::dark_hex::kClassicalDarkHex, SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
InformationStateString()
std::string open_spiel::dark_hex::DarkHexState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Reimplemented in open_spiel::dark_hex::ImperfectRecallDarkHexState.
Definition at line 203 of file dark_hex.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string str;
  absl::StrAppend(&str, ViewToString(player), "\n");
  absl::StrAppend(&str, history_.size(), "\n");
  absl::StrAppend(&str, ActionSequenceToString(player));
  return str;
}
References open_spiel::State::history_, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and ViewToString().
InformationStateTensor()
void open_spiel::dark_hex::DarkHexState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 213 of file dark_hex.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  const auto& player_view = (player == 0 ? black_view_ : white_view_);
  SPIEL_CHECK_EQ(values.size(), num_cells_ * kCellStates +
                                    longest_sequence_ * (1 + bits_per_action_));
  std::fill(values.begin(), values.end(), 0.);
  for (int cell = 0; cell < num_cells_; ++cell) {
    values[cell * kCellStates +
           (static_cast<int>(player_view[cell]) - kMinValueCellState)] = 1.0;
  }
  // Encoding the sequence
  int offset = num_cells_ * kCellStates;
  for (const auto& player_with_action : action_sequence_) {
    if (player_with_action.first == player) {
      // Always include the observing player's actions.
      values[offset] = player_with_action.first;
      values[offset + 1 + player_with_action.second] = 1.0;
    } else if (obs_type_ == ObservationType::kRevealNumTurns) {
      // If the number of turns are revealed, then each of the other player's
      // actions will show up as unknowns. Here, num_cells_ is used to
      // encode "unknown".
      values[offset] = player_with_action.first;
      values[offset + 1 + num_cells_] = 1.0;
    } else {
      SPIEL_CHECK_EQ(obs_type_, ObservationType::kRevealNothing);
    }
    offset += (1 + bits_per_action_);
  }
}
References open_spiel::dark_hex::kRevealNothing, open_spiel::dark_hex::kRevealNumTurns, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::dark_hex::DarkHexState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 101 of file dark_hex.h.
{ return state_.IsTerminal(); }
References open_spiel::hex::HexState::IsTerminal().
Referenced by LegalActions().
LegalActions()
std::vector< Action > open_spiel::dark_hex::DarkHexState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 155 of file dark_hex.cc.
{
  if (IsTerminal()) return {};
  std::vector<Action> moves;
  const Player player = CurrentPlayer();
  const auto& cur_view = (player == 0 ? black_view_ : white_view_);
  for (Action move = 0; move < num_cells_; ++move) {
    if (cur_view[move] == CellState::kEmpty) {
      moves.push_back(move);
    }
  }
  return moves;
}
References CurrentPlayer(), IsTerminal(), and player.
ObservationString()
std::string open_spiel::dark_hex::DarkHexState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 248 of file dark_hex.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string observation = ViewToString(player);
  if (obs_type_ == ObservationType::kRevealNumTurns) {
    absl::StrAppend(&observation, "\nTotal turns: ", action_sequence_.size());
  }
  return observation;
}
References open_spiel::dark_hex::kRevealNumTurns, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), and ViewToString().
ObservationTensor()
void open_spiel::dark_hex::DarkHexState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 258 of file dark_hex.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), game_->ObservationTensorSize());
  std::fill(values.begin(), values.end(), 0.);
  const auto& player_view = (player == 0 ? black_view_ : white_view_);
  for (int cell = 0; cell < num_cells_; ++cell) {
    values[cell * kCellStates +
           (static_cast<int>(player_view[cell]) - kMinValueCellState)] = 1.0;
  }
  if (obs_type_ == ObservationType::kRevealNumTurns) {
    values[num_cells_ * kCellStates + action_sequence_.size()] = 1.0;
  }
}
References open_spiel::State::game_, open_spiel::dark_hex::kRevealNumTurns, open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::dark_hex::DarkHexState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 102 of file dark_hex.h.
{ return state_.Returns(); }
References open_spiel::hex::HexState::Returns().
ToString()
std::string open_spiel::dark_hex::DarkHexState::ToString () const inline override virtual
Implements open_spiel::State.
Definition at line 100 of file dark_hex.h.
{ return state_.ToString(); }
References open_spiel::hex::HexState::ToString().
ViewToString()
std::string open_spiel::dark_hex::DarkHexState::ViewToString (Player player) const protected
Definition at line 170 of file dark_hex.cc.
{
  const auto& cur_view = (player == 0 ? black_view_ : white_view_);
  std::string str;
  for (int r = 0; r < num_rows_; ++r) {
    for (int c = 0; c < num_cols_; ++c) {
      absl::StrAppend(&str, StateToString(cur_view[r * num_cols_ + c]));
    }
    if (r < (num_rows_ - 1)) {
      absl::StrAppend(&str, "\n");
    }
  }
  return str;
}
References player, r, StateToString(), and absl::StrAppend().
Referenced by InformationStateString(), open_spiel::dark_hex::ImperfectRecallDarkHexState::InformationStateString(), and ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/dark_hex/dark_hex.h
open_spiel/games/dark_hex/dark_hex.cc