open spiel: TimerGroup Class Reference
TimerGroup Class Reference
#include <TimerGroup.h>
Public Member Functions
TimerGroup ()
~TimerGroup ()
void Reset ()
void SetNames (const string &baseName)
void Start (const unsigned no)
void End (const unsigned no)
bool Used () const
void Differentiate ()
void Sum (Timer &sum) const
void operator-= (const TimerGroup &deduct)
string Header () const
string DetailHeader () const
string SumLine (const Timer &sumTotal) const
string TimerLines (const Timer &sumTotal) const
string DetailLines () const
string DashLine () const
Detailed Description
Definition at line 21 of file TimerGroup.h.
Constructor & Destructor Documentation
TimerGroup()
TimerGroup::TimerGroup ()
Definition at line 19 of file TimerGroup.cpp.
{
  TimerGroup::Reset();
}
References Reset().
~TimerGroup()
TimerGroup::~TimerGroup ()
Definition at line 25 of file TimerGroup.cpp.
{
}
Member Function Documentation
DashLine()
string TimerGroup::DashLine () const
Definition at line 173 of file TimerGroup.cpp.
{
  return string(69, '-') + "\n";
}
Referenced by TimerList::PrintStats().
DetailHeader()
string TimerGroup::DetailHeader () const
Definition at line 125 of file TimerGroup.cpp.
{
  stringstream ss;
  ss << setw(14) << left << "Name " <<
    setw(11) << right << "Number" <<
    setw(11) << "User ticks" <<
    setw(11) << "Avg" <<
    setw(11) << "System" <<
    setw(11) << "Avg ms" << "\n";
  return ss.str();
}
DetailLines()
string TimerGroup::DetailLines () const
Definition at line 160 of file TimerGroup.cpp.
{
  stringstream ss;
  for (unsigned i = 0; i < timers.size(); i++)
  {
    if (timers[i].Used())
      ss << timers[i].DetailLine();
  }
  return ss.str();
}
References i, and Used().
Differentiate()
void TimerGroup::Differentiate ()
Definition at line 85 of file TimerGroup.cpp.
{
  for (unsigned r = 0; r < timers.size()-1; r++)
  {
    unsigned i = timers.size() - 1 - r;
    timers[i] -= timers[i-1];
  }
}
References i, and r.
Referenced by TimerList::PrintStats().
End()
void TimerGroup::End (const unsigned no)
Definition at line 68 of file TimerGroup.cpp.
{
  timers[no].End();
}
Header()
string TimerGroup::Header () const
Definition at line 110 of file TimerGroup.cpp.
{
  stringstream ss;
  ss << setw(14) << left << "Name" <<
    setw(9) << right << "Count" <<
    setw(11) << "User" <<
    setw(7) << "Avg" <<
    setw(5) << "%" <<
    setw(11) << "Syst" <<
    setw(7) << "Avg" <<
    setw(5) << "%" << "\n";
  return ss.str();
}
Referenced by TimerList::PrintStats().
operator-=()
void TimerGroup::operator-= (const TimerGroup & deduct)
Definition at line 103 of file TimerGroup.cpp.
{
  for (unsigned i = 0; i < timers.size(); i++)
    timers[i] -= deduct.timers[i];
}
References i.
Reset()
void TimerGroup::Reset ()
Definition at line 30 of file TimerGroup.cpp.
{
  timers.resize(TIMER_DEPTH);
  for (unsigned i = 0; i < timers.size(); i++)
    timers[i].Reset();
}
References i, Reset(), and TIMER_DEPTH.
Referenced by Reset(), and TimerGroup().
SetNames()
void TimerGroup::SetNames (const string & baseName)
Definition at line 38 of file TimerGroup.cpp.
{
  string st;
  if (baseName == "AB")
  {
    // Special format emphasizing the card number within the trick.
    for (unsigned i = 0; i < timers.size(); i++)
    {
      st = baseName + to_string(i % 4) + " " + to_string(i);
      timers[i].SetName(st);
    }
  }
  else
  {
    for (unsigned i = 0; i < timers.size(); i++)
    {
      st = baseName + to_string(i);
      timers[i].SetName(st);
    }
  }
  bname = baseName;
}
References i.
Referenced by TimerList::PrintStats().
Start()
void TimerGroup::Start (const unsigned no)
Definition at line 62 of file TimerGroup.cpp.
{
  timers[no].Start();
}
Sum()
void TimerGroup::Sum (Timer & sum) const
Definition at line 95 of file TimerGroup.cpp.
{
  sum = timers[0];
  for (unsigned i = 1; i < timers.size(); i++)
    sum += timers[i];
}
References i.
Referenced by TimerList::PrintStats(), and SumLine().
SumLine()
string TimerGroup::SumLine (const Timer & sumTotal) const
Definition at line 138 of file TimerGroup.cpp.
{
  Timer ownSum;
  TimerGroup::Sum(ownSum);
  return ownSum.SumLine(sumTotal, bname);
}
References Sum(), and Timer::SumLine().
Referenced by TimerList::PrintStats().
TimerLines()
string TimerGroup::TimerLines (const Timer & sumTotal) const
Definition at line 147 of file TimerGroup.cpp.
{
  string st = "";
  for (unsigned r = 0; r < timers.size(); r++)
  {
    unsigned i = timers.size() - r - 1;
    if (timers[i].Used())
      st += timers[i].SumLine(sumTotal);
  }
  return st;
}
References i, r, and Used().
Referenced by TimerList::PrintStats().
Used()
bool TimerGroup::Used () const
Definition at line 74 of file TimerGroup.cpp.
{
  for (unsigned i = 0; i < timers.size(); i++)
  {
    if (timers[i].Used())
      return true;
  }
  return false;
}
References i, and Used().
Referenced by DetailLines(), TimerList::PrintStats(), TimerLines(), and Used().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/src/TimerGroup.h
open_spiel/games/bridge/double_dummy_solver/src/TimerGroup.cpp