open spiel: open_spiel::tiny_bridge::TinyBridgePlayState Class Reference
open_spiel::tiny_bridge::TinyBridgePlayState Class Reference
#include <tiny_bridge.h>
Public Member Functions
TinyBridgePlayState (std::shared_ptr< const Game > game, int trumps, Seat leader, std::array< Seat, kDeckSize > holder)
TinyBridgePlayState (const TinyBridgePlayState &)=default
Player CurrentPlayer () const override
Seat CurrentHand () const
std::string ActionToString (Player player, Action action_id) const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
std::string ToString () const override
std::vector< Action > LegalActions () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
virtual std::string ObservationString (Player player) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 190 of file tiny_bridge.h.
Constructor & Destructor Documentation
TinyBridgePlayState() [1/2]
open_spiel::tiny_bridge::TinyBridgePlayState::TinyBridgePlayState (std::shared_ptr< const Game > game, int trumps, Seat leader, std::array< Seat, kDeckSize > holder) inline
Definition at line 192 of file tiny_bridge.h.
      : State(std::move(game)),
        trumps_(trumps),
        leader_(leader),
        holder_(holder) {}
Referenced by Clone().
TinyBridgePlayState() [2/2]
open_spiel::tiny_bridge::TinyBridgePlayState::TinyBridgePlayState (const TinyBridgePlayState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::tiny_bridge::TinyBridgePlayState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 768 of file tiny_bridge.cc.
{
  return CardString(action_id);
}
Clone()
std::unique_ptr< State > open_spiel::tiny_bridge::TinyBridgePlayState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 789 of file tiny_bridge.cc.
{
  return std::unique_ptr<State>{new TinyBridgePlayState(*this)};
}
References TinyBridgePlayState().
CurrentHand()
Seat open_spiel::tiny_bridge::TinyBridgePlayState::CurrentHand () const
Definition at line 763 of file tiny_bridge.cc.
{
  return Seat(((actions_.size() < 4 ? leader_ : winner_[0]) + actions_.size()) %
              4);
}
Referenced by CurrentPlayer(), DoApplyAction(), and LegalActions().
CurrentPlayer()
Player open_spiel::tiny_bridge::TinyBridgePlayState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 200 of file tiny_bridge.h.
{ return CurrentHand() % 2; }
References CurrentHand().
DoApplyAction()
void open_spiel::tiny_bridge::TinyBridgePlayState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 721 of file tiny_bridge.cc.
{
  actions_.emplace_back(CurrentHand(), action);
  if (actions_.size() % 4 == 0) {
    Seat win_hand = actions_[actions_.size() - 4].first;
    int win_card = actions_[actions_.size() - 4].second;
    for (int i = actions_.size() - 3; i < actions_.size(); ++i) {
      Seat hand = actions_[i].first;
      int card = actions_[i].second;
      if (Suit(card) == Suit(win_card)) {
        if (Rank(card) > Rank(win_card)) {
          win_card = card;
          win_hand = hand;
        }
      } else if (Suit(card) == trumps_) {
        win_card = card;
        win_hand = hand;
      }
    }
    winner_[actions_.size() / 4 - 1] = win_hand;
  }
}
References action, CurrentHand(), and i.
IsTerminal()
bool open_spiel::tiny_bridge::TinyBridgePlayState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 773 of file tiny_bridge.cc.
{
  return actions_.size() == kDeckSize;
}
References open_spiel::tiny_bridge::kDeckSize.
Referenced by Returns().
LegalActions()
std::vector< Action > open_spiel::tiny_bridge::TinyBridgePlayState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 743 of file tiny_bridge.cc.
{
  std::vector<Action> actions;
  const int hand = CurrentHand();
  for (int i = 0; i < kDeckSize; ++i) {
    if (holder_[i] == hand &&
        (actions_.size() < 4 ||
         actions_[(4 + hand - leader_) % 4].second != i)) {
      actions.push_back(i);
    }
  }
  // Have to follow suit if we have two cards of different suits.
  if (!actions_.empty() && actions.size() == 2 &&
      Suit(actions[0]) != Suit(actions[1])) {
    return {Suit(actions[0]) == Suit(actions_[0].second) ? actions[0]
                                                         : actions[1]};
  } else {
    return actions;
  }
}
References CurrentHand(), i, and open_spiel::tiny_bridge::kDeckSize.
Returns()
std::vector< double > open_spiel::tiny_bridge::TinyBridgePlayState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 777 of file tiny_bridge.cc.
{
  if (!IsTerminal()) {
    return std::vector<double>(num_players_, 0.0);
  }
  std::vector<double> returns(num_players_);
  for (const int winner : winner_) {
    returns[winner & 1] += 1.0;
  }
  return returns;
}
References IsTerminal(), and open_spiel::State::num_players_.
ToString()
std::string open_spiel::tiny_bridge::TinyBridgePlayState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 799 of file tiny_bridge.cc.
{
  std::array<std::string, kNumSeats> hands;
  for (int i = 0; i < kDeckSize; ++i) {
    hands[holder_[i]].append(CardString(i));
  }
  std::string s;
  for (int i = 0; i < kNumSeats; ++i) {
    if (i > 0) s.push_back(' ');
    s.append(absl::StrCat(std::string(1, kSeatChar[i]), ":", hands[i]));
  }
  s.append(absl::StrCat(" Trumps: ", std::string(1, kSuitChar[trumps_]),
                        " Leader:", std::string(1, kSeatChar[leader_])));
  for (const auto& action : actions_) {
    s.append(absl::StrCat(" ", std::string(1, kSeatChar[action.first]), ":",
                          CardString(action.second)));
  }
  return s;
}
References action, i, open_spiel::tiny_bridge::kDeckSize, open_spiel::tiny_bridge::kNumSeats, and absl::StrCat().
UndoAction()
void open_spiel::tiny_bridge::TinyBridgePlayState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 793 of file tiny_bridge.cc.
{
  actions_.pop_back();
  history_.pop_back();
  --move_number_;
}
References open_spiel::State::history_, and open_spiel::State::move_number_.
The documentation for this class was generated from the following files:
open_spiel/games/tiny_bridge/tiny_bridge.h
open_spiel/games/tiny_bridge/tiny_bridge.cc