open spiel: open_spiel.python.algorithms.efr.EFRSolver Class Reference
open_spiel.python.algorithms.efr.EFRSolver Class Reference
Public Member Functions
__init__ (self, game, deviations_name)
Public Member Functions inherited from open_spiel.python.algorithms.efr._EFRSolver
evaluate_and_update_policy (self)
Public Member Functions inherited from open_spiel.python.algorithms.efr._EFRSolverBase
return_cumulative_regret (self)
current_policy (self)
average_policy (self)
Protected Member Functions
_regret_matching (self, legal_actions, info_set_node)
Protected Member Functions inherited from open_spiel.python.algorithms.efr._EFRSolverBase
_initialize_info_state_nodes (self, state, history, path_indices)
_update_current_policy (self, state, current_policy)
_compute_cumulative_immediate_regret_for_player (self, state, policies, reach_probabilities, player)
_get_infostate_policy (self, info_state_str)
Protected Attributes
_external_only
Protected Attributes inherited from open_spiel.python.algorithms.efr._EFRSolver
_root_node
_current_policy
Protected Attributes inherited from open_spiel.python.algorithms.efr._EFRSolverBase
_game
_num_players
_root_node
_current_policy
_average_policy
_deviation_gen
_info_state_nodes
_iteration
Detailed Description
Implements the EFR algorithm with several deviation types.
See: https://arxiv.org/abs/2102.06973
Definition at line 438 of file efr.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.algorithms.efr.EFRSolver.__init__ (self, game, deviations_name)
Initializer.
Args:
  game: The `pyspiel.Game` to run on.
  deviations_name: the name of the deviation type to use for
    accumulating regrets and calculating the strategy at the next timestep.
Deviation types implemented are "blind action", "informed action",
"blind cf", "informed counterfactual", "blind partial sequence",
"counterfactual partial sequence", "casual partial sequence",
"twice informed partial sequence", "single target behavioural".
See "Efficient Deviation Types and Learning for Hindsight Rationality in
Extensive-Form Games" by D. Morrill et al. 2021b
for the full definition of each type.
Reimplemented from open_spiel.python.algorithms.efr._EFRSolverBase.
Definition at line 444 of file efr.py.
  def __init__(self, game, deviations_name):
    """Initializer.
    Args:
      game: The `pyspiel.Game` to run on.
      deviations_name: the name of the deviation type to use for
        accumulating regrets and calculating the strategy at the next timestep.
    Deviation types implemented are "blind action", "informed action",
    "blind cf", "informed counterfactual", "blind partial sequence",
    "counterfactual partial sequence", "casual partial sequence",
    "twice informed partial sequence", "single target behavioural".
    See "Efficient Deviation Types and Learning for Hindsight Rationality in
    Extensive-Form Games" by D. Morrill et al. 2021b
    for the full definition of each type.
    """
    # external_only = True leads to a shortcut in the computation of the next
    # timesteps strategy from the regrets
    external_only = False
    deviation_sets = None  # pylint: disable=unused-variable
    if deviations_name in {"blind action"}:
      deviation_sets = return_blind_action
      external_only = True
    elif deviations_name in {"informed action"}:
      deviation_sets = return_informed_action
    elif deviations_name in {"blind cf", "blind counterfactual"}:
      deviation_sets = return_blind_cf
      external_only = True
    elif deviations_name in {"informed cf", "informed counterfactual"}:
      deviation_sets = return_informed_cf
    elif deviations_name in {"bps", "blind partial sequence"}:
      deviation_sets = return_blind_partial_sequence
      external_only = True
    elif deviations_name in {
        "cfps",
        "cf partial sequence",
        "counterfactual partial sequence",
    }:
      deviation_sets = return_cf_partial_sequence
    elif deviations_name in {"csps", "casual partial sequence"}:
      deviation_sets = return_cs_partial_sequence
    elif deviations_name in {"tips", "twice informed partial sequence"}:
      deviation_sets = return_twice_informed_partial_sequence
    elif deviations_name in {"bhv", "single target behavioural", "behavioural"}:
      deviation_sets = return_behavourial
    else:
      raise ValueError(
          "Unsupported Deviation Set Passed As                       "
          " Constructor Argument"
      )
    super(EFRSolver, self).__init__(game, deviation_sets)
    self._external_only = external_only
References open_spiel.python.algorithms.efr.EFRSolver.__init__().
Referenced by open_spiel.python.algorithms.efr.EFRSolver.__init__().
Member Function Documentation
_regret_matching()
open_spiel.python.algorithms.efr.EFRSolver._regret_matching (self, legal_actions, info_set_node) protected
Returns an info state policy.
The info state policy returned is the one obtained by applying
regret-matching function over all deviations and time selection functions.
Args:
  legal_actions: the list of legal actions at this state.
  info_set_node: the info state node to compute the policy for.
Returns:
  A dict of action -> prob for all legal actions.
Definition at line 500 of file efr.py.
  def _regret_matching(self, legal_actions, info_set_node):
    """Returns an info state policy.
    The info state policy returned is the one obtained by applying
    regret-matching function over all deviations and time selection functions.
    Args:
      legal_actions: the list of legal actions at this state.
      info_set_node: the info state node to compute the policy for.
    Returns:
      A dict of action -> prob for all legal actions.
    """
    z = sum(info_set_node.y_values.values())
    info_state_policy = {}
    # The fixed point solution can be directly obtained through the
    # weighted regret matrix if only external deviations are used.
    if self._external_only and z > 0:
      weighted_deviation_matrix = np.zeros(
          (len(legal_actions), len(legal_actions))
      )
      for dev in list(info_set_node.y_values.keys()):
        weighted_deviation_matrix += (
            info_set_node.y_values[dev] / z
        ) * dev.return_transform_matrix()
      new_strategy = weighted_deviation_matrix[:, 0]
      for index in range(len(legal_actions)):
        info_state_policy[legal_actions[index]] = new_strategy[index]
    # Full regret matching by finding the least squares solution to the
    # fixed point of the EFR regret matching function.
    # Last row of matrix and the column entry minimises the solution
    # towards a strategy.
    elif z > 0:
      num_actions = len(info_set_node.legal_actions)
      weighted_deviation_matrix = -np.eye(num_actions)
      for dev in list(info_set_node.y_values.keys()):
        weighted_deviation_matrix += (
            info_set_node.y_values[dev] / z
        ) * dev.return_transform_matrix()
      normalisation_row = np.ones(num_actions)
      weighted_deviation_matrix = np.vstack(
          [weighted_deviation_matrix, normalisation_row]
      )
      b = np.zeros(num_actions + 1)
      b[num_actions] = 1
      b = np.reshape(b, (num_actions + 1, 1))
      strategy = linalg.lstsq(weighted_deviation_matrix, b)[0]
      # Adopt same clipping strategy as paper author's code.
      strategy[np.where(strategy < 0)] = 0
      strategy[np.where(strategy > 1)] = 1
      strategy = strategy / sum(strategy)
      for index in range(len(strategy)):
        info_state_policy[info_set_node.legal_actions[index]] = strategy[index]
    # Use a uniform strategy as sum of all regrets is negative.
    else:
      for index in range(len(legal_actions)):
        info_state_policy[legal_actions[index]] = 1.0 / len(legal_actions)
    return info_state_policy
References open_spiel.python.algorithms.efr.EFRSolver._external_only, and len.
Referenced by open_spiel.python.algorithms.outcome_sampling_mccfr.OutcomeSamplingSolver._episode(), open_spiel.python.algorithms.external_sampling_mccfr.ExternalSamplingSolver._full_update_average(), open_spiel.python.algorithms.efr._EFRSolverBase._update_current_policy(), and open_spiel.python.algorithms.external_sampling_mccfr.ExternalSamplingSolver._update_regrets().
Member Data Documentation
_external_only
open_spiel.python.algorithms.efr.EFRSolver._external_only protected
Definition at line 498 of file efr.py.
Referenced by open_spiel.python.algorithms.efr.EFRSolver._regret_matching().
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/efr.py