open spiel: open_spiel::blotto::BlottoState Class Reference
open_spiel::blotto::BlottoState Class Reference
#include <blotto.h>
Public Member Functions
BlottoState (std::shared_ptr< const Game > game, int coins, int fields, const ActionMap *action_map, const std::vector< Action > *legal_actions_)
std::vector< Action > LegalActions (Player player) const override
std::string ActionToString (Player player, Action move_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
Public Member Functions inherited from open_spiel::NFGState
NFGState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const final
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
std::string ToString () const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyActions (const std::vector< Action > &actions) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyAction (Action action_id)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 45 of file blotto.h.
Constructor & Destructor Documentation
BlottoState()
open_spiel::blotto::BlottoState::BlottoState (std::shared_ptr< const Game > game, int coins, int fields, const ActionMap * action_map, const std::vector< Action > * legal_actions_)
Definition at line 58 of file blotto.cc.
    : NFGState(game),
      coins_(coins),
      fields_(fields),
      joint_action_({}),
      action_map_(action_map),
      legal_actions_(legal_actions),
      returns_({}) {}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::blotto::BlottoState::ActionToString (Player player, Action move_id) const override virtual
Implements open_spiel::State.
Definition at line 136 of file blotto.cc.
{
  return game_->ActionToString(player, move_id);
}
References open_spiel::State::game_, and player.
Referenced by ToString().
Clone()
std::unique_ptr< State > open_spiel::blotto::BlottoState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 156 of file blotto.cc.
{
  return std::unique_ptr<State>(new BlottoState(*this));
}
References BlottoState().
DoApplyActions()
void open_spiel::blotto::BlottoState::DoApplyActions (const std::vector< Action > & actions) override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 69 of file blotto.cc.
{
  joint_action_ = actions;
  // Now determine returns.
  returns_.resize(num_players_, 0);
  std::vector<int> scores(num_players_, 0);
  std::vector<std::vector<int>> player_actions;
  for (int f = 0; f < fields_; ++f) {
    int num_winners = 0;
    int winner = 0;
    int max_value = -1;
    for (auto p = Player{0}; p < num_players_; ++p) {
      // Get the expanded action if necessary.
      if (p >= player_actions.size()) {
        player_actions.push_back(action_map_->at(joint_action_[p]));
      }
      if (player_actions[p][f] > max_value) {
        num_winners = 1;
        winner = p;
        max_value = player_actions[p][f];
      } else if (player_actions[p][f] == max_value) {
        num_winners++;
      }
    }
    // Give the winner of this field one point. Draw if tied.
    if (num_winners == 1) {
      scores[winner]++;
    }
  }
  // Find the global winner(s).
  std::set<int> winners;
  int max_points = 0;
  for (auto p = Player{0}; p < num_players_; ++p) {
    if (scores[p] > max_points) {
      max_points = scores[p];
      winners = {p};
    } else if (scores[p] == max_points) {
      winners.insert(p);
    }
  }
  // Finally, assign returns. Each winner gets 1/num_winners, each loser gets
  // -1 / num_losers.
  for (auto p = Player{0}; p < num_players_; ++p) {
    if (winners.size() == num_players_) {
      // All players won same number of fields. Draw.
      returns_[p] = 0;
    } else if (winners.find(p) != winners.end()) {
      SPIEL_CHECK_GE(winners.size(), 1);
      returns_[p] = 1.0 / winners.size();
    } else {
      SPIEL_CHECK_GE(num_players_ - winners.size(), 1);
      returns_[p] = -1.0 / (num_players_ - winners.size());
    }
  }
}
References open_spiel::State::num_players_, and SPIEL_CHECK_GE.
IsTerminal()
bool open_spiel::blotto::BlottoState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 150 of file blotto.cc.
{ return !joint_action_.empty(); }
Referenced by LegalActions(), Returns(), and ToString().
LegalActions()
std::vector< Action > open_spiel::blotto::BlottoState::LegalActions (Player player) const override virtual
Implements open_spiel::SimMoveState.
Definition at line 131 of file blotto.cc.
{
  if (IsTerminal()) return {};
  return (*legal_actions_);
}
References IsTerminal().
Returns()
std::vector< double > open_spiel::blotto::BlottoState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 152 of file blotto.cc.
{
  return IsTerminal() ? returns_ : std::vector<double>(num_players_, 0.);
}
References IsTerminal(), and open_spiel::State::num_players_.
ToString()
std::string open_spiel::blotto::BlottoState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 140 of file blotto.cc.
{
  std::string str = "";
  absl::StrAppend(&str, "Terminal? ", IsTerminal(), "\n");
  for (int p = 0; p < joint_action_.size(); ++p) {
    absl::StrAppend(&str, "P", p,
                    " action: ", ActionToString(p, joint_action_[p]), "\n");
  }
  return str;
}
References ActionToString(), IsTerminal(), and absl::StrAppend().
The documentation for this class was generated from the following files:
open_spiel/games/blotto/blotto.h
open_spiel/games/blotto/blotto.cc