open spiel: absl::synchronization_internal::PerThreadSemTest Class Reference
absl::synchronization_internal::PerThreadSemTest Class Reference
Public Member Functions
void TestTiming (const char *msg, bool timeout)
Static Public Member Functions
static void TimingThread (ThreadData *t)
Static Protected Member Functions
static void Post (base_internal::ThreadIdentity *id)
static bool Wait (KernelTimeout t)
static bool Wait (absl::Time t)
static void Tick (base_internal::ThreadIdentity *identity)
Detailed Description
Definition at line 81 of file per_thread_sem_test.cc.
Member Function Documentation
Post()
static void absl::synchronization_internal::PerThreadSemTest::Post (base_internal::ThreadIdentity * id) inline static protected
Definition at line 128 of file per_thread_sem_test.cc.
{
    PerThreadSem::Post(id);
  }
Referenced by TestTiming(), and TimingThread().
TestTiming()
void absl::synchronization_internal::PerThreadSemTest::TestTiming (const char * msg, bool timeout) inline
Definition at line 92 of file per_thread_sem_test.cc.
{
    static const int kNumIterations = 100;
    ThreadData t;
    t.num_iterations = kNumIterations;
    t.timeout = timeout ?
        KernelTimeout(absl::Now() + absl::Seconds(10000))  // far in the future
        : KernelTimeout::Never();
    t.identity1 = GetOrCreateCurrentThreadIdentity();
    // We can't use the Thread class here because it uses the Mutex
    // class which will invoke PerThreadSem, so we use std::thread instead.
    std::thread partner_thread(std::bind(TimingThread, &t));
    // Wait for our partner thread to register their identity.
    t.identity2_written.Wait();
    int64_t min_cycles = std::numeric_limits<int64_t>::max();
    int64_t total_cycles = 0;
    for (int i = 0; i < kNumIterations; ++i) {
      absl::SleepFor(absl::Milliseconds(20));
      int64_t cycles = base_internal::CycleClock::Now();
      Post(t.identity2);
      Wait(t.timeout);
      cycles = base_internal::CycleClock::Now() - cycles;
      min_cycles = std::min(min_cycles, cycles);
      total_cycles += cycles;
    }
    std::string out = StrCat(
        msg, "min cycle count=", min_cycles, " avg cycle count=",
        absl::SixDigits(static_cast<double>(total_cycles) / kNumIterations));
    printf("%s\n", out.c_str());
    partner_thread.join();
  }
References absl::synchronization_internal::GetOrCreateCurrentThreadIdentity(), absl::i, absl::Milliseconds(), absl::msg, absl::synchronization_internal::KernelTimeout::Never(), absl::base_internal::CycleClock::Now(), absl::Now(), absl::out, Post(), absl::Seconds(), absl::SixDigits(), absl::SleepFor(), absl::StrCat(), TimingThread(), and Wait().
Tick()
static void absl::synchronization_internal::PerThreadSemTest::Tick (base_internal::ThreadIdentity * identity) inline static protected
Definition at line 140 of file per_thread_sem_test.cc.
{
    PerThreadSem::Tick(identity);
  }
References absl::synchronization_internal::PerThreadSem::Tick().
TimingThread()
static void absl::synchronization_internal::PerThreadSemTest::TimingThread (ThreadData * t) inline static
Definition at line 83 of file per_thread_sem_test.cc.
{
    t->identity2 = GetOrCreateCurrentThreadIdentity();
    t->identity2_written.Post();
    while (t->num_iterations--) {
      Wait(t->timeout);
      Post(t->identity1);
    }
  }
References absl::synchronization_internal::GetOrCreateCurrentThreadIdentity(), Post(), and Wait().
Referenced by TestTiming().
Wait() [1/2]
static bool absl::synchronization_internal::PerThreadSemTest::Wait (absl::Time t) inline static protected
Definition at line 136 of file per_thread_sem_test.cc.
{
    return Wait(KernelTimeout(t));
  }
References Wait().
Wait() [2/2]
static bool absl::synchronization_internal::PerThreadSemTest::Wait (KernelTimeout t) inline static protected
Definition at line 131 of file per_thread_sem_test.cc.
{
    return PerThreadSem::Wait(t);
  }
Referenced by TestTiming(), TimingThread(), and Wait().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/synchronization/internal/per_thread_sem_test.cc