open spiel: open_spiel::RepeatedGame Class Reference
open_spiel::RepeatedGame Class Reference
#include <repeated_game.h>
Public Member Functions
RepeatedGame (std::shared_ptr< const Game > stage_game, const GameParameters &params)
std::unique_ptr< State > NewInitialState () const override
int MaxGameLength () const override
int NumPlayers () const override
int NumDistinctActions () const override
double MinUtility () const override
double MaxUtility () const override
absl::optional< double > UtilitySum () const override
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
const Game * StageGame () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::SimMoveGame
SimMoveGame (GameType game_type, GameParameters game_parameters)
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 80 of file repeated_game.h.
Constructor & Destructor Documentation
RepeatedGame()
open_spiel::RepeatedGame::RepeatedGame (std::shared_ptr< const Game > stage_game, const GameParameters & params)
Definition at line 242 of file repeated_game.cc.
    : SimMoveGame(
          ConvertType(
              stage_game->GetType(),
              open_spiel::ParameterValue(
                  params, "enable_infostate",
                  absl::optional<bool>(kDefaultEnableInformationState))),
          params),
      stage_game_(stage_game),
      num_repetitions_(ParameterValue<int>("num_repetitions")),
      recall_(ParameterValue<int>("recall", kDefaultRecall)) {
  SPIEL_CHECK_GE(recall_, 1);
}
References SPIEL_CHECK_GE.
Member Function Documentation
InformationStateTensorShape()
std::vector< int > open_spiel::RepeatedGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 286 of file repeated_game.cc.
{
  int player_actions_size = 0;
  for (int i = 0; i < NumPlayers(); ++i) {
    player_actions_size +=
        stage_game_->NewInitialState()->LegalActions(i).size();
  }
  return {num_repetitions_ * player_actions_size};
}
References i, and NumPlayers().
MaxGameLength()
int open_spiel::RepeatedGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 85 of file repeated_game.h.
{ return num_repetitions_; }
MaxUtility()
double open_spiel::RepeatedGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 93 of file repeated_game.h.
{
    return stage_game_->MaxUtility() * num_repetitions_;
  }
MinUtility()
double open_spiel::RepeatedGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 90 of file repeated_game.h.
{
    return stage_game_->MinUtility() * num_repetitions_;
  }
NewInitialState()
std::unique_ptr< State > open_spiel::RepeatedGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 280 of file repeated_game.cc.
{
  return std::unique_ptr<State>(
      new RepeatedState(shared_from_this(), stage_game_,
                        num_repetitions_, recall_));
}
NumDistinctActions()
int open_spiel::RepeatedGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 87 of file repeated_game.h.
{
    return stage_game_->NumDistinctActions();
  }
NumPlayers()
int open_spiel::RepeatedGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 86 of file repeated_game.h.
{ return stage_game_->NumPlayers(); }
Referenced by InformationStateTensorShape(), and ObservationTensorShape().
ObservationTensorShape()
std::vector< int > open_spiel::RepeatedGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 295 of file repeated_game.cc.
{
  int size = 0;
  for (int i = 0; i < NumPlayers(); ++i)
    size += recall_ * stage_game_->NewInitialState()->LegalActions(i).size();
  return {size};
}
References i, NumPlayers(), and size.
StageGame()
const Game * open_spiel::RepeatedGame::StageGame () const inline
Definition at line 105 of file repeated_game.h.
{ return stage_game_.get(); }
UtilitySum()
absl::optional< double > open_spiel::RepeatedGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 96 of file repeated_game.h.
{
    auto per_stage_utility_sum = stage_game_->UtilitySum();
    return !per_stage_utility_sum.has_value()
               ? per_stage_utility_sum
               : per_stage_utility_sum.value() * num_repetitions_;
  }
The documentation for this class was generated from the following files:
open_spiel/game_transforms/repeated_game.h
open_spiel/game_transforms/repeated_game.cc