open spiel: absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P > Class Template Reference
absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P > Class Template Reference
#include <any_invocable.h>
Classes
struct IsCompatibleAnyInvocable
struct IsCompatibleAnyInvocable< AnyInvocable< Sig > >
Public Types
enum class TargetType : int { kPointer = 0 , kCompatibleAnyInvocable = 1 , kIncompatibleAnyInvocable = 2 , kOther = 3 }
using result_type = ReturnType
template<class T >
using HasTrivialRemoteStorage
Public Member Functions
CoreImpl () noexcept
template<class QualDecayedTRef , class F >
CoreImpl (TypedConversionConstruct< QualDecayedTRef >, F &&f)
template<class QualTRef , class... Args>
CoreImpl (absl::in_place_type_t< QualTRef >, Args &&... args)
CoreImpl (CoreImpl &&other) noexcept
CoreImpl & operator= (CoreImpl &&other) noexcept
~CoreImpl ()
bool HasValue () const
void Clear ()
template<int target_type, class QualDecayedTRef , class F , absl::enable_if_t< target_type==0, int > = 0>
void Initialize (F &&f)
template<int target_type, class QualDecayedTRef , class F , absl::enable_if_t< target_type==1, int > = 0>
void Initialize (F &&f)
template<int target_type, class QualDecayedTRef , class F , absl::enable_if_t< target_type==2, int > = 0>
void Initialize (F &&f)
template<int target_type, class QualDecayedTRef , class F , typename = absl::enable_if_t<target_type == 3>>
void Initialize (F &&f)
template<class QualTRef , class... Args, typename = absl::enable_if_t< IsStoredLocally<RemoveCVRef<QualTRef>>::value>>
void InitializeStorage (Args &&... args)
template<class QualTRef , class... Args, absl::enable_if_t<!IsStoredLocally< RemoveCVRef< QualTRef > >::value, int > = 0>
void InitializeStorage (Args &&... args)
template<class T , typename = absl::enable_if_t<std::is_trivially_copyable<T>::value>>
void InitializeLocalManager ()
template<class T , absl::enable_if_t<!std::is_trivially_copyable< T >::value, int > = 0>
void InitializeLocalManager ()
template<class T , class... Args, typename = absl::enable_if_t<HasTrivialRemoteStorage<T>::value>>
void InitializeRemoteManager (Args &&... args)
template<class T , class... Args, absl::enable_if_t<!HasTrivialRemoteStorage< T >::value, int > = 0>
void InitializeRemoteManager (Args &&... args)
Public Attributes
TypeErasedState state_
ManagerType * manager_
InvokerType< SigIsNoexcept, ReturnType, P... > * invoker_
Detailed Description
template<bool SigIsNoexcept, class ReturnType, class... P>
class absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >
Definition at line 428 of file any_invocable.h.
Member Typedef Documentation
HasTrivialRemoteStorage
template<bool SigIsNoexcept, class ReturnType , class... P> template<class T > using absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::HasTrivialRemoteStorage
Initial value:
      std::integral_constant<bool, std::is_trivially_destructible<T>::value &&
                                       alignof(T) <=
                                           ABSL_INTERNAL_DEFAULT_NEW_ALIGNMENT>
Definition at line 604 of file any_invocable.h.
result_type
template<bool SigIsNoexcept, class ReturnType , class... P> using absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::result_type = ReturnType
Definition at line 430 of file any_invocable.h.
Member Enumeration Documentation
TargetType
template<bool SigIsNoexcept, class ReturnType , class... P> enum class absl::internal_any_invocable::CoreImpl::TargetType : int strong
Enumerator
kPointer
kCompatibleAnyInvocable
kIncompatibleAnyInvocable
kOther
Definition at line 434 of file any_invocable.h.
                        : int {
    kPointer = 0,
    kCompatibleAnyInvocable = 1,
    kIncompatibleAnyInvocable = 2,
    kOther = 3,
  };
Constructor & Destructor Documentation
CoreImpl() [1/4]
template<bool SigIsNoexcept, class ReturnType , class... P> absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl () inline noexcept
Definition at line 432 of file any_invocable.h.
: manager_(EmptyManager), invoker_(nullptr) {}
CoreImpl() [2/4]
template<bool SigIsNoexcept, class ReturnType , class... P> template<class QualDecayedTRef , class F > absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl (TypedConversionConstruct< QualDecayedTRef > , F && f) inline explicit
Definition at line 445 of file any_invocable.h.
{
    using DecayedT = RemoveCVRef<QualDecayedTRef>;
    constexpr TargetType kTargetType =
        (std::is_pointer<DecayedT>::value ||
         std::is_member_pointer<DecayedT>::value)
            ? TargetType::kPointer
        : IsCompatibleAnyInvocable<DecayedT>::value
            ? TargetType::kCompatibleAnyInvocable
        : IsAnyInvocable<DecayedT>::value
            ? TargetType::kIncompatibleAnyInvocable
            : TargetType::kOther;
    // NOTE: We only use integers instead of enums as template parameters in
    // order to work around a bug on C++14 under MSVC 2017.
    // See b/236131881.
    Initialize<static_cast<int>(kTargetType), QualDecayedTRef>(
        std::forward<F>(f));
  }
References absl::f, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::kCompatibleAnyInvocable, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::kIncompatibleAnyInvocable, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::kOther, and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::kPointer.
CoreImpl() [3/4]
template<bool SigIsNoexcept, class ReturnType , class... P> template<class QualTRef , class... Args> absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl (absl::in_place_type_t< QualTRef > , Args &&... args) inline explicit
Definition at line 468 of file any_invocable.h.
{
    InitializeStorage<QualTRef>(std::forward<Args>(args)...);
  }
References absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage().
CoreImpl() [4/4]
template<bool SigIsNoexcept, class ReturnType , class... P> absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl (CoreImpl< SigIsNoexcept, ReturnType, P > && other) inline noexcept
Definition at line 472 of file any_invocable.h.
{
    other.manager_(FunctionToCall::relocate_from_to, &other.state_, &state_);
    manager_ = other.manager_;
    invoker_ = other.invoker_;
    other.manager_ = EmptyManager;
    other.invoker_ = nullptr;
  }
References absl::internal_any_invocable::EmptyManager(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_, absl::internal_any_invocable::relocate_from_to, and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::state_.
~CoreImpl()
template<bool SigIsNoexcept, class ReturnType , class... P> absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::~CoreImpl () inline
Definition at line 500 of file any_invocable.h.
{ manager_(FunctionToCall::dispose, &state_, &state_); }
References absl::internal_any_invocable::dispose, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_, and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::state_.
Member Function Documentation
Clear()
template<bool SigIsNoexcept, class ReturnType , class... P> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Clear () inline
Definition at line 506 of file any_invocable.h.
               {
    manager_(FunctionToCall::dispose, &state_, &state_);
    manager_ = EmptyManager;
    invoker_ = nullptr;
  }
References absl::internal_any_invocable::dispose, absl::internal_any_invocable::EmptyManager(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_, and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::state_.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::operator=().
HasValue()
template<bool SigIsNoexcept, class ReturnType , class... P> bool absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::HasValue () const inline
Definition at line 503 of file any_invocable.h.
{ return invoker_ != nullptr; }
References absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_.
Initialize() [1/4]
template<bool SigIsNoexcept, class ReturnType , class... P> template<int target_type, class QualDecayedTRef , class F , absl::enable_if_t< target_type==0, int > = 0> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize (F && f) inline
Definition at line 514 of file any_invocable.h.
{
// This condition handles types that decay into pointers, which includes
// function references. Since function references cannot be null, GCC warns
// against comparing their decayed form with nullptr.
// Since this is template-heavy code, we prefer to disable these warnings
// locally instead of adding yet another overload of this function.
#if !defined(__clang__) && defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wpragmas"
#pragma GCC diagnostic ignored "-Waddress"
#pragma GCC diagnostic ignored "-Wnonnull-compare"
#pragma GCC diagnostic push
#endif
    if (static_cast<RemoveCVRef<QualDecayedTRef>>(f) == nullptr) {
#if !defined(__clang__) && defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
      manager_ = EmptyManager;
      invoker_ = nullptr;
      return;
    }
    InitializeStorage<QualDecayedTRef>(std::forward<F>(f));
  }
References absl::internal_any_invocable::EmptyManager(), absl::f, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_, and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl().
Initialize() [2/4]
template<bool SigIsNoexcept, class ReturnType , class... P> template<int target_type, class QualDecayedTRef , class F , absl::enable_if_t< target_type==1, int > = 0> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize (F && f) inline
Definition at line 539 of file any_invocable.h.
{
    // In this case we can "steal the guts" of the other AnyInvocable.
    f.manager_(FunctionToCall::relocate_from_to, &f.state_, &state_);
    manager_ = f.manager_;
    invoker_ = f.invoker_;
    f.manager_ = EmptyManager;
    f.invoker_ = nullptr;
  }
References absl::internal_any_invocable::EmptyManager(), absl::f, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_, absl::internal_any_invocable::relocate_from_to, and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::state_.
Initialize() [3/4]
template<bool SigIsNoexcept, class ReturnType , class... P> template<int target_type, class QualDecayedTRef , class F , absl::enable_if_t< target_type==2, int > = 0> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize (F && f) inline
Definition at line 551 of file any_invocable.h.
{
    if (f.HasValue()) {
      InitializeStorage<QualDecayedTRef>(std::forward<F>(f));
    } else {
      manager_ = EmptyManager;
      invoker_ = nullptr;
    }
  }
References absl::internal_any_invocable::EmptyManager(), absl::f, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_, and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_.
Initialize() [4/4]
template<bool SigIsNoexcept, class ReturnType , class... P> template<int target_type, class QualDecayedTRef , class F , typename = absl::enable_if_t<target_type == 3>> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize (F && f) inline
Definition at line 562 of file any_invocable.h.
{
    InitializeStorage<QualDecayedTRef>(std::forward<F>(f));
  }
References absl::f, and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage().
InitializeLocalManager() [1/2]
template<bool SigIsNoexcept, class ReturnType , class... P> template<class T , typename = absl::enable_if_t<std::is_trivially_copyable<T>::value>> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeLocalManager () inline
Definition at line 593 of file any_invocable.h.
{
    manager_ = LocalManagerTrivial;
  }
References absl::internal_any_invocable::LocalManagerTrivial(), and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage().
InitializeLocalManager() [2/2]
template<bool SigIsNoexcept, class ReturnType , class... P> template<class T , absl::enable_if_t<!std::is_trivially_copyable< T >::value, int > = 0> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeLocalManager () inline
Definition at line 599 of file any_invocable.h.
{
    manager_ = LocalManagerNontrivial<T>;
  }
References absl::internal_any_invocable::LocalManagerNontrivial(), and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_.
InitializeRemoteManager() [1/2]
template<bool SigIsNoexcept, class ReturnType , class... P> template<class T , class... Args, typename = absl::enable_if_t<HasTrivialRemoteStorage<T>::value>> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeRemoteManager (Args &&... args) inline
Definition at line 611 of file any_invocable.h.
{
    // unique_ptr is used for exception-safety in case construction throws.
    std::unique_ptr<void, TrivialDeleter> uninitialized_target(
        ::operator new(sizeof(T)), TrivialDeleter(sizeof(T)));
    ::new (uninitialized_target.get()) T(std::forward<Args>(args)...);
    state_.remote.target = uninitialized_target.release();
    state_.remote.size = sizeof(T);
    manager_ = RemoteManagerTrivial;
  }
References absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_, absl::internal_any_invocable::TypeErasedState::remote, absl::internal_any_invocable::RemoteManagerTrivial(), absl::internal_any_invocable::TypeErasedState::size, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::state_, and absl::internal_any_invocable::TypeErasedState::target.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage().
InitializeRemoteManager() [2/2]
template<bool SigIsNoexcept, class ReturnType , class... P> template<class T , class... Args, absl::enable_if_t<!HasTrivialRemoteStorage< T >::value, int > = 0> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeRemoteManager (Args &&... args) inline
Definition at line 623 of file any_invocable.h.
{
    state_.remote.target = ::new T(std::forward<Args>(args)...);
    manager_ = RemoteManagerNontrivial<T>;
  }
References absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_, absl::internal_any_invocable::TypeErasedState::remote, absl::internal_any_invocable::RemoteManagerNontrivial(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::state_, and absl::internal_any_invocable::TypeErasedState::target.
InitializeStorage() [1/2]
template<bool SigIsNoexcept, class ReturnType , class... P> template<class QualTRef , class... Args, typename = absl::enable_if_t< IsStoredLocally<RemoveCVRef<QualTRef>>::value>> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage (Args &&... args) inline
Definition at line 570 of file any_invocable.h.
{
    using RawT = RemoveCVRef<QualTRef>;
    ::new (static_cast<void*>(&state_.storage))
        RawT(std::forward<Args>(args)...);
    invoker_ = LocalInvoker<SigIsNoexcept, ReturnType, QualTRef, P...>;
    // We can simplify our manager if we know the type is trivially copyable.
    InitializeLocalManager<RawT>();
  }
References absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeLocalManager(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_, absl::internal_any_invocable::LocalInvoker(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::state_, and absl::internal_any_invocable::TypeErasedState::storage.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl(), and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize().
InitializeStorage() [2/2]
template<bool SigIsNoexcept, class ReturnType , class... P> template<class QualTRef , class... Args, absl::enable_if_t<!IsStoredLocally< RemoveCVRef< QualTRef > >::value, int > = 0> void absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage (Args &&... args) inline
Definition at line 584 of file any_invocable.h.
{
    InitializeRemoteManager<RemoveCVRef<QualTRef>>(std::forward<Args>(args)...);
    // This is set after everything else in case an exception is thrown in an
    // earlier step of the initialization.
    invoker_ = RemoteInvoker<SigIsNoexcept, ReturnType, QualTRef, P...>;
  }
References absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeRemoteManager(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_, and absl::internal_any_invocable::RemoteInvoker().
operator=()
template<bool SigIsNoexcept, class ReturnType , class... P> CoreImpl & absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::operator= (CoreImpl< SigIsNoexcept, ReturnType, P > && other) inline noexcept
Definition at line 480 of file any_invocable.h.
{
    // Put the left-hand operand in an empty state.
    //
    // Note: A full reset that leaves us with an object that has its invariants
    // intact is necessary in order to handle self-move. This is required by
    // types that are used with certain operations of the standard library, such
    // as the default definition of std::swap when both operands target the same
    // object.
    Clear();
    // Perform the actual move/destory operation on the target function.
    other.manager_(FunctionToCall::relocate_from_to, &other.state_, &state_);
    manager_ = other.manager_;
    invoker_ = other.invoker_;
    other.manager_ = EmptyManager;
    other.invoker_ = nullptr;
    return *this;
  }
References absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Clear(), absl::internal_any_invocable::EmptyManager(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_, absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_, absl::internal_any_invocable::relocate_from_to, and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::state_.
Member Data Documentation
invoker_
template<bool SigIsNoexcept, class ReturnType , class... P> InvokerType<SigIsNoexcept, ReturnType, P...>* absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::invoker_
Definition at line 654 of file any_invocable.h.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Clear(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::HasValue(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage(), and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::operator=().
manager_
template<bool SigIsNoexcept, class ReturnType , class... P> ManagerType* absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::manager_
Definition at line 653 of file any_invocable.h.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Clear(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeLocalManager(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeRemoteManager(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::operator=(), and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::~CoreImpl().
state_
template<bool SigIsNoexcept, class ReturnType , class... P> TypeErasedState absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::state_
Definition at line 652 of file any_invocable.h.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Clear(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeRemoteManager(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::operator=(), and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::~CoreImpl().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/functional/internal/any_invocable.h