open spiel: absl::FormatConversionSpec Class Reference
absl::FormatConversionSpec Class Reference
#include <str_format.h>
Public Member Functions
bool is_basic () const
bool has_left_flag () const
bool has_show_pos_flag () const
bool has_sign_col_flag () const
bool has_alt_flag () const
bool has_zero_flag () const
FormatConversionChar conversion_char () const
int width () const
int precision () const
Detailed Description
Definition at line 696 of file str_format.h.
Member Function Documentation
conversion_char()
FormatConversionChar absl::FormatConversionSpec::conversion_char () const inline
Definition at line 744 of file str_format.h.
{
    return impl_.conversion_char();
  }
References absl::str_format_internal::FormatConversionSpecImpl::conversion_char().
has_alt_flag()
bool absl::FormatConversionSpec::has_alt_flag () const inline
Definition at line 732 of file str_format.h.
{ return impl_.has_alt_flag(); }
References absl::str_format_internal::FormatConversionSpecImpl::has_alt_flag().
has_left_flag()
bool absl::FormatConversionSpec::has_left_flag () const inline
Definition at line 709 of file str_format.h.
{ return impl_.has_left_flag(); }
References absl::str_format_internal::FormatConversionSpecImpl::has_left_flag().
has_show_pos_flag()
bool absl::FormatConversionSpec::has_show_pos_flag () const inline
Definition at line 717 of file str_format.h.
{ return impl_.has_show_pos_flag(); }
References absl::str_format_internal::FormatConversionSpecImpl::has_show_pos_flag().
has_sign_col_flag()
bool absl::FormatConversionSpec::has_sign_col_flag () const inline
Definition at line 724 of file str_format.h.
{ return impl_.has_sign_col_flag(); }
References absl::str_format_internal::FormatConversionSpecImpl::has_sign_col_flag().
has_zero_flag()
bool absl::FormatConversionSpec::has_zero_flag () const inline
Definition at line 739 of file str_format.h.
{ return impl_.has_zero_flag(); }
References absl::str_format_internal::FormatConversionSpecImpl::has_zero_flag().
is_basic()
bool absl::FormatConversionSpec::is_basic () const inline
Definition at line 702 of file str_format.h.
{ return impl_.is_basic(); }
References absl::str_format_internal::FormatConversionSpecImpl::is_basic().
precision()
int absl::FormatConversionSpec::precision () const inline
Definition at line 760 of file str_format.h.
{ return impl_.precision(); }
References absl::str_format_internal::FormatConversionSpecImpl::precision().
width()
int absl::FormatConversionSpec::width () const inline
Definition at line 753 of file str_format.h.
{ return impl_.width(); }
References absl::str_format_internal::FormatConversionSpecImpl::width().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/str_format.h