open spiel: TestTimer Class Reference
TestTimer Class Reference
#include <TestTimer.h>
Public Member Functions
TestTimer ()
~TestTimer ()
void reset ()
void setname (const string &s)
void start (const int number=1)
void end ()
void printRunning (const int reached, const int number)
void printBasic () const
void printHands () const
Detailed Description
Definition at line 22 of file TestTimer.h.
Constructor & Destructor Documentation
TestTimer()
TestTimer::TestTimer ()
Definition at line 20 of file TestTimer.cpp.
{
  TestTimer::reset();
}
References reset().
~TestTimer()
TestTimer::~TestTimer ()
Definition at line 26 of file TestTimer.cpp.
{
}
Member Function Documentation
end()
void TestTimer::end ()
Definition at line 55 of file TestTimer.cpp.
{
  time_point<Clock> user1 = Clock::now();
  clock_t sys1 = clock();
  chrono::duration<double, milli> d = user1 - user0;
  int tuser = static_cast<int>(1000. * d.count());
  userCum += tuser;
  sysCum += static_cast<int>((1000 * (sys1 - sys0)) /
    static_cast<double>(CLOCKS_PER_SEC));
}
Referenced by loop_calc(), loop_dealerpar(), loop_play(), and loop_solve().
printBasic()
void TestTimer::printBasic () const
Definition at line 87 of file TestTimer.cpp.
{
  if (count == 0)
    return;
  if (name != "")
    cout << setw(19) << left << "Timer name" << ": " << name << "\n";
  cout << setw(19) << left << "Number of calls" << ": " << count << "\n";
  if (userCum == 0)
    cout << setw(19) << left << "User time" << ": " << "zero" << "\n";
  else
  {
    cout << setw(19) << left << "User time/ticks" << ": " <<
      userCum << "\n";
    cout << setw(19) << left << "User per call" << ": " <<
      setprecision(2) << userCum / static_cast<float>(count) << "\n";
  }
  if (sysCum == 0)
    cout << setw(19) << left << "Sys time" << ": " << "zero" << "\n";
  else
  {
    cout << setw(19) << left << "Sys time/ticks" << ": " <<
      sysCum << "\n";
    cout << setw(19) << left << "Sys per call" << ": " <<
      setprecision(2) << sysCum / static_cast<float>(count) << "\n";
    cout << setw(19) << left << "Ratio" << ": " <<
      setprecision(2) << sysCum / static_cast<float>(userCum);
  }
  cout << endl;
}
printHands()
void TestTimer::printHands () const
Definition at line 122 of file TestTimer.cpp.
{
  if (name != "")
    cout << setw(21) << left << "Timer name" <<
      setw(12) << right << name << "\n";
  cout << setw(21) << left << "Number of hands" <<
    setw(12) << right << count << "\n";
  if (count == 0)
    return;
  if (userCum == 0)
    cout << setw(21) << left << "User time (ms)" <<
      setw(12) << right << "zero" << "\n";
  else
  {
    cout << setw(21) << left << "User time (ms)" <<
      setw(12) << right << fixed <<
        setprecision(0) << userCum / 1000. << "\n";
    cout << setw(21) << left << "Avg user time (ms)" <<
      setw(12) << right << fixed << setprecision(2) << userCum /
        static_cast<float>(1000. * count) << "\n";
  }
  if (sysCum == 0)
    cout << setw(21) << left << "Sys time" <<
      setw(12) << right << "zero" << "\n";
  else
  {
    cout << setw(21) << left << "Sys time (ms)" <<
      setw(12) << right << fixed << setprecision(0) << sysCum << "\n";
    cout << setw(21) << left << "Avg sys time (ms)" <<
      setw(12) << right << fixed << setprecision(2) << sysCum /
        static_cast<float>(count) << "\n";
    cout << setw(21) << left << "Ratio" <<
      setw(12) << right << fixed << setprecision(2) <<
      1000. * sysCum / static_cast<float>(userCum);
  }
  cout << endl;
}
Referenced by realMain().
printRunning()
void TestTimer::printRunning (const int reached, const int number)
Definition at line 69 of file TestTimer.cpp.
{
  if (count == 0)
    return;
  cout << setw(8) << reached << " (" <<
    setw(6) << setprecision(1) << right << fixed <<
      100. * reached /
        static_cast<float>(divisor) << "%)" <<
    setw(15) << right << fixed << setprecision(0) <<
      (userCum - userCumOld) / 1000. << endl;
  userCumOld = userCum;
}
Referenced by loop_calc(), loop_dealerpar(), loop_play(), and loop_solve().
reset()
void TestTimer::reset ()
Definition at line 31 of file TestTimer.cpp.
{
  name = "";
  count = 0;
  userCum = 0;
  userCumOld = 0;
  sysCum = 0;
}
Referenced by open_spiel.python.utils.stats.BasicStats::__init__(), realMain(), open_spiel.python.algorithms.ismcts.ISMCTSBot::run_search(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), open_spiel.python.vector_env.SyncVectorEnv::step(), and TestTimer().
setname()
void TestTimer::setname (const string & s)
Definition at line 41 of file TestTimer.cpp.
{
  name = s;
}
Referenced by realMain().
start()
void TestTimer::start (const int number = 1)
Definition at line 47 of file TestTimer.cpp.
{
  count += number;
  user0 = Clock::now();
  sys0 = clock();
}
Referenced by loop_calc(), loop_dealerpar(), loop_play(), and loop_solve().
The documentation for this class was generated from the following files:
open_spiel/games/bridge/double_dummy_solver/test/TestTimer.h
open_spiel/games/bridge/double_dummy_solver/test/TestTimer.cpp