open spiel: absl::cleanup_internal::Storage< Callback > Class Template Reference
absl::cleanup_internal::Storage< Callback > Class Template Reference
#include <cleanup.h>
Public Member Functions
Storage ()=delete
Storage (Callback callback)
Storage (Storage &&other)
Storage (const Storage &other)=delete
Storage & operator= (Storage &&other)=delete
Storage & operator= (const Storage &other)=delete
void * GetCallbackBuffer ()
Callback & GetCallback ()
bool IsCallbackEngaged () const
void DestroyCallback ()
void InvokeCallback () ABSL_NO_THREAD_SAFETY_ANALYSIS
Detailed Description
template<typename Callback>
class absl::cleanup_internal::Storage< Callback >
Definition at line 46 of file cleanup.h.
Constructor & Destructor Documentation
Storage() [1/4]
template<typename Callback > absl::cleanup_internal::Storage< Callback >::Storage () delete
Storage() [2/4]
template<typename Callback > absl::cleanup_internal::Storage< Callback >::Storage (Callback callback) inline explicit
Definition at line 50 of file cleanup.h.
{
    // Placement-new into a character buffer is used for eager destruction when
    // the cleanup is invoked or cancelled. To ensure this optimizes well, the
    // behavior is implemented locally instead of using an absl::optional.
    ::new (GetCallbackBuffer()) Callback(std::move(callback));
    is_callback_engaged_ = true;
  }
References absl::cleanup_internal::Storage< Callback >::GetCallbackBuffer().
Storage() [3/4]
template<typename Callback > absl::cleanup_internal::Storage< Callback >::Storage (Storage< Callback > && other) inline
Definition at line 58 of file cleanup.h.
{
    ABSL_HARDENING_ASSERT(other.IsCallbackEngaged());
    ::new (GetCallbackBuffer()) Callback(std::move(other.GetCallback()));
    is_callback_engaged_ = true;
    other.DestroyCallback();
  }
References ABSL_HARDENING_ASSERT, and absl::cleanup_internal::Storage< Callback >::GetCallbackBuffer().
Storage() [4/4]
template<typename Callback > absl::cleanup_internal::Storage< Callback >::Storage (const Storage< Callback > & other) delete
Member Function Documentation
DestroyCallback()
template<typename Callback > void absl::cleanup_internal::Storage< Callback >::DestroyCallback () inline
Definition at line 81 of file cleanup.h.
{
    is_callback_engaged_ = false;
    GetCallback().~Callback();
  }
References absl::cleanup_internal::Storage< Callback >::GetCallback().
GetCallback()
template<typename Callback > Callback & absl::cleanup_internal::Storage< Callback >::GetCallback () inline
Definition at line 75 of file cleanup.h.
{
    return *reinterpret_cast<Callback*>(GetCallbackBuffer());
  }
References absl::cleanup_internal::Storage< Callback >::GetCallbackBuffer().
Referenced by absl::cleanup_internal::Storage< Callback >::DestroyCallback(), and absl::cleanup_internal::Storage< Callback >::InvokeCallback().
GetCallbackBuffer()
template<typename Callback > void * absl::cleanup_internal::Storage< Callback >::GetCallbackBuffer () inline
Definition at line 73 of file cleanup.h.
{ return static_cast<void*>(+callback_buffer_); }
Referenced by absl::cleanup_internal::Storage< Callback >::GetCallback(), absl::cleanup_internal::Storage< Callback >::Storage(), and absl::cleanup_internal::Storage< Callback >::Storage().
InvokeCallback()
template<typename Callback > void absl::cleanup_internal::Storage< Callback >::InvokeCallback () inline
Definition at line 86 of file cleanup.h.
{
    std::move(GetCallback())();
  }
References absl::cleanup_internal::Storage< Callback >::GetCallback().
IsCallbackEngaged()
template<typename Callback > bool absl::cleanup_internal::Storage< Callback >::IsCallbackEngaged () const inline
Definition at line 79 of file cleanup.h.
{ return is_callback_engaged_; }
operator=() [1/2]
template<typename Callback > Storage & absl::cleanup_internal::Storage< Callback >::operator= (const Storage< Callback > & other) delete
operator=() [2/2]
template<typename Callback > Storage & absl::cleanup_internal::Storage< Callback >::operator= (Storage< Callback > && other) delete
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/cleanup/internal/cleanup.h