open spiel: absl::base_internal::SpinLock Class Reference
absl::base_internal::SpinLock Class Reference
#include <spinlock.h>
Public Member Functions
SpinLock ()
SpinLock (base_internal::SchedulingMode mode)
constexpr SpinLock (absl::ConstInitType, base_internal::SchedulingMode mode)
~SpinLock ()=default
void Lock () ABSL_EXCLUSIVE_LOCK_FUNCTION()
bool TryLock () ABSL_EXCLUSIVE_TRYLOCK_FUNCTION(true)
void Unlock () ABSL_UNLOCK_FUNCTION()
bool IsHeld () const
void AssertHeld () const ABSL_ASSERT_EXCLUSIVE_LOCK()
Static Protected Member Functions
static uint32_t EncodeWaitCycles (int64_t wait_start_time, int64_t wait_end_time)
static int64_t DecodeWaitCycles (uint32_t lock_value)
Friends
struct SpinLockTest
Detailed Description
Definition at line 48 of file spinlock.h.
Constructor & Destructor Documentation
SpinLock() [1/3]
absl::base_internal::SpinLock::SpinLock () inline
Definition at line 50 of file spinlock.h.
             : lockword_(kSpinLockCooperative) {
    ABSL_TSAN_MUTEX_CREATE(this, __tsan_mutex_not_static);
  }
References ABSL_TSAN_MUTEX_CREATE.
SpinLock() [2/3]
absl::base_internal::SpinLock::SpinLock (base_internal::SchedulingMode mode) explicit
Definition at line 80 of file spinlock.cc.
    : lockword_(IsCooperative(mode) ? kSpinLockCooperative : 0) {
  ABSL_TSAN_MUTEX_CREATE(this, __tsan_mutex_not_static);
}
References ABSL_TSAN_MUTEX_CREATE.
SpinLock() [3/3]
absl::base_internal::SpinLock::SpinLock (absl::ConstInitType , base_internal::SchedulingMode mode) inline constexpr
Definition at line 59 of file spinlock.h.
      : lockword_(IsCooperative(mode) ? kSpinLockCooperative : 0) {}
~SpinLock()
absl::base_internal::SpinLock::~SpinLock () default
Member Function Documentation
AssertHeld()
void absl::base_internal::SpinLock::AssertHeld () const inline
Definition at line 121 of file spinlock.h.
{
    if (!IsHeld()) {
      ABSL_RAW_LOG(FATAL, "thread should hold the lock on SpinLock");
    }
  }
References ABSL_RAW_LOG.
DecodeWaitCycles()
int64_t absl::base_internal::SpinLock::DecodeWaitCycles (uint32_t lock_value) static protected
Definition at line 223 of file spinlock.cc.
{
  // Cast to uint32_t first to ensure bits [63:32] are cleared.
  const int64_t scaled_wait_time =
      static_cast<uint32_t>(lock_value & kWaitTimeMask);
  return scaled_wait_time << (kProfileTimestampShift - kLockwordReservedShift);
}
Referenced by absl::base_internal::SpinLockTest::DecodeWaitCycles().
EncodeWaitCycles()
uint32_t absl::base_internal::SpinLock::EncodeWaitCycles (int64_t wait_start_time, int64_t wait_end_time) static protected
Definition at line 199 of file spinlock.cc.
{
  static const int64_t kMaxWaitTime =
      std::numeric_limits<uint32_t>::max() >> kLockwordReservedShift;
  int64_t scaled_wait_time =
      (wait_end_time - wait_start_time) >> kProfileTimestampShift;
  // Return a representation of the time spent waiting that can be stored in
  // the lock word's upper bits.
  uint32_t clamped = static_cast<uint32_t>(
      std::min(scaled_wait_time, kMaxWaitTime) << kLockwordReservedShift);
  if (clamped == 0) {
    return kSpinLockSleeper;  // Just wake waiters, but don't record contention.
  }
  // Bump up value if necessary to avoid returning kSpinLockSleeper.
  const uint32_t kMinWaitTime =
      kSpinLockSleeper + (1 << kLockwordReservedShift);
  if (clamped == kSpinLockSleeper) {
    return kMinWaitTime;
  }
  return clamped;
}
Referenced by absl::base_internal::SpinLockTest::EncodeWaitCycles().
IsHeld()
bool absl::base_internal::SpinLock::IsHeld () const inline
Definition at line 115 of file spinlock.h.
{
    return (lockword_.load(std::memory_order_relaxed) & kSpinLockHeld) != 0;
  }
Lock()
void absl::base_internal::SpinLock::Lock () inline
Definition at line 72 of file spinlock.h.
{
    ABSL_TSAN_MUTEX_PRE_LOCK(this, 0);
    if (!TryLockImpl()) {
      SlowLock();
    }
    ABSL_TSAN_MUTEX_POST_LOCK(this, 0, 0);
  }
References ABSL_TSAN_MUTEX_POST_LOCK, and ABSL_TSAN_MUTEX_PRE_LOCK.
Referenced by absl::Mutex::ForgetDeadlockInfo().
TryLock()
bool absl::base_internal::SpinLock::TryLock () inline
Definition at line 84 of file spinlock.h.
{
    ABSL_TSAN_MUTEX_PRE_LOCK(this, __tsan_mutex_try_lock);
    bool res = TryLockImpl();
    ABSL_TSAN_MUTEX_POST_LOCK(
        this, __tsan_mutex_try_lock | (res ? 0 : __tsan_mutex_try_lock_failed),
        0);
    return res;
  }
References ABSL_TSAN_MUTEX_POST_LOCK, and ABSL_TSAN_MUTEX_PRE_LOCK.
Unlock()
void absl::base_internal::SpinLock::Unlock () inline
Definition at line 94 of file spinlock.h.
{
    ABSL_TSAN_MUTEX_PRE_UNLOCK(this, 0);
    uint32_t lock_value = lockword_.load(std::memory_order_relaxed);
    lock_value = lockword_.exchange(lock_value & kSpinLockCooperative,
                                    std::memory_order_release);
    if ((lock_value & kSpinLockDisabledScheduling) != 0) {
      base_internal::SchedulingGuard::EnableRescheduling(true);
    }
    if ((lock_value & kWaitTimeMask) != 0) {
      // Collect contentionz profile info, and speed the wakeup of any waiter.
      // The wait_cycles value indicates how long this thread spent waiting
      // for the lock.
      SlowUnlock(lock_value);
    }
    ABSL_TSAN_MUTEX_POST_UNLOCK(this, 0);
  }
References ABSL_TSAN_MUTEX_POST_UNLOCK, and ABSL_TSAN_MUTEX_PRE_UNLOCK.
Referenced by absl::Mutex::ForgetDeadlockInfo().
Friends And Related Symbol Documentation
SpinLockTest
friend struct SpinLockTest friend
Definition at line 139 of file spinlock.h.
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/base/internal/spinlock.h
open_spiel/abseil-cpp/absl/base/internal/spinlock.cc