open spiel: open_spiel::backgammon::BackgammonGame Class Reference
open_spiel::backgammon::BackgammonGame Class Reference
#include <backgammon.h>
Public Member Functions
BackgammonGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
std::vector< int > ObservationTensorShape () const override
int NumCheckersPerPlayer () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 262 of file backgammon.h.
Constructor & Destructor Documentation
BackgammonGame()
open_spiel::backgammon::BackgammonGame::BackgammonGame (const GameParameters & params) explicit
Definition at line 1301 of file backgammon.cc.
    : Game(kGameType, params),
      scoring_type_(
          ParseScoringType(ParameterValue<std::string>("scoring_type"))),
      hyper_backgammon_(ParameterValue<bool>("hyper_backgammon")) {}
Member Function Documentation
MaxChanceNodesInHistory()
int open_spiel::backgammon::BackgammonGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 282 of file backgammon.h.
{ return MaxGameLength() + 1; }
References MaxGameLength().
MaxChanceOutcomes()
int open_spiel::backgammon::BackgammonGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 275 of file backgammon.h.
{ return 30; }
MaxGameLength()
int open_spiel::backgammon::BackgammonGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 278 of file backgammon.h.
{ return 1000; }
Referenced by MaxChanceNodesInHistory().
MaxUtility()
double open_spiel::backgammon::BackgammonGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 1307 of file backgammon.cc.
{
  if (hyper_backgammon_) {
    // We do not have the cube implemented, so Hyper-backgammon us currently
    // restricted to a win-loss game regardless of the scoring type.
    return 1;
  }
  switch (scoring_type_) {
    case ScoringType::kWinLossScoring:
      return 1;
    case ScoringType::kEnableGammons:
      return 2;
    case ScoringType::kFullScoring:
      return 3;
    default:
      SpielFatalError("Unknown scoring_type");
  }
}
References open_spiel::backgammon::kEnableGammons, open_spiel::backgammon::kFullScoring, open_spiel::backgammon::kWinLossScoring, and open_spiel::SpielFatalError().
Referenced by MinUtility().
MinUtility()
double open_spiel::backgammon::BackgammonGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 285 of file backgammon.h.
{ return -MaxUtility(); }
References MaxUtility().
NewInitialState()
std::unique_ptr< State > open_spiel::backgammon::BackgammonGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 268 of file backgammon.h.
{
    return std::unique_ptr<State>(new BackgammonState(
        shared_from_this(), scoring_type_, hyper_backgammon_));
  }
NumCheckersPerPlayer()
int open_spiel::backgammon::BackgammonGame::NumCheckersPerPlayer () const
Definition at line 1326 of file backgammon.cc.
{
  if (hyper_backgammon_) {
    return 3;
  } else {
    return kNumCheckersPerPlayer;
  }
}
References open_spiel::backgammon::kNumCheckersPerPlayer.
NumDistinctActions()
int open_spiel::backgammon::BackgammonGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 266 of file backgammon.h.
{ return kNumDistinctActions; }
References open_spiel::backgammon::kNumDistinctActions.
NumPlayers()
int open_spiel::backgammon::BackgammonGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 284 of file backgammon.h.
{ return 2; }
ObservationTensorShape()
std::vector< int > open_spiel::backgammon::BackgammonGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 289 of file backgammon.h.
{
    // Encode each point on the board as four doubles:
    // - One double for whether there is one checker or not (1 or 0).
    // - One double for whether there are two checkers or not (1 or 0).
    // - One double for whether there are three checkers or not (1 or 0).
    // - One double if there are more than 3 checkers, the number of checkers.
    //   more than three that are on that point.
    //
    // Return a vector encoding:
    // Every point listed for the current player.
    // Every point listed for the opponent.
    // One double for the number of checkers on the bar for the current player.
    // One double for the number of checkers scored for the current player.
    // One double for whether it's the current player's turn (1 or 0).
    // One double for the number of checkers on the bar for the opponent.
    // One double for the number of checkers scored for the opponent.
    // One double for whether it's the opponent's turn (1 or 0).
    // One double for the first dice's value.
    // One double for the second dice's value.
    return {kStateEncodingSize};
  }
References open_spiel::backgammon::kStateEncodingSize.
UtilitySum()
absl::optional< double > open_spiel::backgammon::BackgammonGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 286 of file backgammon.h.
{ return 0; }
The documentation for this class was generated from the following files:
open_spiel/games/backgammon/backgammon.h
open_spiel/games/backgammon/backgammon.cc