open spiel: open_spiel::algorithms::TabularSarsaSolver Class Reference
open_spiel::algorithms::TabularSarsaSolver Class Reference
#include <tabular_sarsa.h>
Public Member Functions
TabularSarsaSolver (std::shared_ptr< const Game > game)
TabularSarsaSolver (std::shared_ptr< const Game > game, double depth_limit, double epsilon, double learning_rate, double discount_factor, double lambda)
void RunIteration ()
const absl::flat_hash_map< std::pair< std::string, Action >, double > & GetQValueTable () const
Detailed Description
Definition at line 47 of file tabular_sarsa.h.
Constructor & Destructor Documentation
TabularSarsaSolver() [1/2]
open_spiel::algorithms::TabularSarsaSolver::TabularSarsaSolver (std::shared_ptr< const Game > game)
Definition at line 74 of file tabular_sarsa.cc.
    : game_(game),
      depth_limit_(kDefaultDepthLimit),
      epsilon_(kDefaultEpsilon),
      learning_rate_(kDefaultLearningRate),
      discount_factor_(kDefaultDiscountFactor),
      lambda_(kDefaultLambda) {
  SPIEL_CHECK_LE(lambda_, 1);
  SPIEL_CHECK_GE(lambda_, 0);
  // Currently only supports 1-player or 2-player zero sum games
  SPIEL_CHECK_TRUE(game_->NumPlayers() == 1 || game_->NumPlayers() == 2);
  if (game_->NumPlayers() == 2) {
    SPIEL_CHECK_EQ(game_->GetType().utility, GameType::Utility::kZeroSum);
  }
  // No support for simultaneous games (needs an LP solver). And so also must
  // be a perfect information game.
  SPIEL_CHECK_EQ(game_->GetType().dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(game_->GetType().information,
                 GameType::Information::kPerfectInformation);
}
References open_spiel::GameType::kPerfectInformation, open_spiel::GameType::kSequential, open_spiel::GameType::kZeroSum, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and SPIEL_CHECK_TRUE.
TabularSarsaSolver() [2/2]
open_spiel::algorithms::TabularSarsaSolver::TabularSarsaSolver (std::shared_ptr< const Game > game, double depth_limit, double epsilon, double learning_rate, double discount_factor, double lambda)
Definition at line 97 of file tabular_sarsa.cc.
    : game_(game),
      depth_limit_(depth_limit),
      epsilon_(epsilon),
      learning_rate_(learning_rate),
      discount_factor_(discount_factor),
      lambda_(lambda) {
  SPIEL_CHECK_LE(lambda_, 1);
  SPIEL_CHECK_GE(lambda_, 0);
  // Currently only supports 1-player or 2-player zero sum games
  SPIEL_CHECK_TRUE(game_->NumPlayers() == 1 || game_->NumPlayers() == 2);
  if (game_->NumPlayers() == 2) {
    SPIEL_CHECK_EQ(game_->GetType().utility, GameType::Utility::kZeroSum);
  }
  // No support for simultaneous games (needs an LP solver). And so also must
  // be a perfect information game.
  SPIEL_CHECK_EQ(game_->GetType().dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(game_->GetType().information,
                 GameType::Information::kPerfectInformation);
}
References open_spiel::GameType::kPerfectInformation, open_spiel::GameType::kSequential, open_spiel::GameType::kZeroSum, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and SPIEL_CHECK_TRUE.
Member Function Documentation
GetQValueTable()
const absl::flat_hash_map< std::pair< std::string, Action >, double > & open_spiel::algorithms::TabularSarsaSolver::GetQValueTable () const
Definition at line 124 of file tabular_sarsa.cc.
{
  return values_;
}
Referenced by SolveCatch(), SolveTicTacToe(), and SolveTicTacToeEligibilityTraces().
RunIteration()
void open_spiel::algorithms::TabularSarsaSolver::RunIteration ()
Definition at line 128 of file tabular_sarsa.cc.
{
  double min_utility = game_->MinUtility();
  // Choose start state
  std::unique_ptr<State> curr_state = game_->NewInitialState();
  SampleUntilNextStateOrTerminal(curr_state.get());
  Player player = curr_state->CurrentPlayer();
  // Sample action from the state using an epsilon-greedy policy
  Action curr_action =
      SampleActionFromEpsilonGreedyPolicy(*curr_state, min_utility);
  std::unique_ptr<State> next_state;
  SPIEL_CHECK_NE(curr_action, kInvalidAction);
  while (!curr_state->IsTerminal()) {
    player = curr_state->CurrentPlayer();
    next_state = curr_state->Child(curr_action);
    SampleUntilNextStateOrTerminal(next_state.get());
    const double reward = next_state->Rewards()[player];
    const Action next_action =
        next_state->IsTerminal()
            ? kInvalidAction
            : SampleActionFromEpsilonGreedyPolicy(*next_state, min_utility);
    // Update the new q value
    std::string key = curr_state->ToString();
    // Next q-value in perspective of player to play at curr_state (important
    // note: exploits property of two-player zero-sum). Define the value of
    // q(s', a') to be 0 if s' is terminal.
    const double future_value =
        next_state->IsTerminal()
            ? 0
            : values_[{next_state->ToString(), next_action}];
    const double next_q_value =
        (player != next_state->CurrentPlayer() ? -1 : 1) * future_value;
    double new_q_value = reward + discount_factor_ * next_q_value;
    double prev_q_val = values_[{key, curr_action}];
    if (lambda_ == 0) {
      // If lambda_ is equal to zero, run sarsa as usual. It's not necessary
      // to update eligibility traces.
      values_[{key, curr_action}] +=
          learning_rate_ * (new_q_value - prev_q_val);
    } else {
      double lambda =
          player != next_state->CurrentPlayer() ? -lambda_ : lambda_;
      eligibility_traces_[{key, curr_action}] += 1;
      for (const auto& q_cell : values_) {
        std::string state = q_cell.first.first;
        Action action = q_cell.first.second;
        values_[{state, action}] += learning_rate_ *
                                    (new_q_value - prev_q_val) *
                                    eligibility_traces_[{state, action}];
        eligibility_traces_[{state, action}] *= discount_factor_ * lambda;
      }
    }
    curr_state = std::move(next_state);
    curr_action = next_action;
  }
}
References action, key, open_spiel::kInvalidAction, player, SPIEL_CHECK_NE, and state.
Referenced by SolveCatch(), SolveTicTacToe(), and SolveTicTacToeEligibilityTraces().
The documentation for this class was generated from the following files:
open_spiel/algorithms/tabular_sarsa.h
open_spiel/algorithms/tabular_sarsa.cc