open spiel: open_spiel::tarok::TarokGame Class Reference
open_spiel::tarok::TarokGame Class Reference
#include <tarok.h>
Public Member Functions
TarokGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
std::unique_ptr< TarokState > NewInitialTarokState () const
int MaxChanceOutcomes () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
int MaxGameLength () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
std::string GetRNGState () const override
void SetRNGState (const std::string &rng_state) const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual std::vector< int > ObservationTensorShape () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Friends
class TarokState
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 49 of file tarok.h.
Constructor & Destructor Documentation
TarokGame()
open_spiel::tarok::TarokGame::TarokGame (const GameParameters & params) explicit
Definition at line 53 of file tarok.cc.
    : Game(kGameType, params),
      num_players_(ParameterValue<int>("players")),
      rng_(std::mt19937(ParameterValue<int>("rng_seed") == -1
                            ? std::time(0)
                            : ParameterValue<int>("rng_seed"))) {
  SPIEL_CHECK_GE(num_players_, kGameType.min_num_players);
  SPIEL_CHECK_LE(num_players_, kGameType.max_num_players);
}
References open_spiel::tarok::kGameType, open_spiel::GameType::max_num_players, open_spiel::GameType::min_num_players, SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Member Function Documentation
DeserializeState()
std::unique_ptr< State > open_spiel::tarok::TarokGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 94 of file tarok.cc.
{
  std::unique_ptr<TarokState> state = NewInitialTarokState();
  if (str.empty()) return state;
  std::vector<std::string> lines = absl::StrSplit(str, '\n');
  for (int i = 0; i < lines.size(); i++) {
    if (i == 0) {
      // chance node where we presisted the card dealing seed, see
      // TarokState::DoApplyActionInCardDealing for more info
      std::tie(state->talon_, state->players_cards_) =
          DealCards(num_players_, std::stoi(lines.at(i)));
      state->current_game_phase_ = GamePhase::kBidding;
      state->current_player_ = 1;
      state->AddPrivateCardsToInfoStates();
    } else {
      state->ApplyAction(std::stol(lines.at(i)));
    }
  }
  return state;
}
References open_spiel::tarok::DealCards(), i, open_spiel::tarok::kBidding, NewInitialTarokState(), state, and absl::StrSplit().
GetRNGState()
std::string open_spiel::tarok::TarokGame::GetRNGState () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 116 of file tarok.cc.
{
  std::ostringstream rng_stream;
  rng_stream << rng_;
  return rng_stream.str();
}
MaxChanceOutcomes()
int open_spiel::tarok::TarokGame::MaxChanceOutcomes () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 73 of file tarok.cc.
{
  // game is implicitly stochastic
  return 1;
}
MaxGameLength()
int open_spiel::tarok::TarokGame::MaxGameLength () const override virtual
Implements open_spiel::Game.
Definition at line 84 of file tarok.cc.
{
  if (num_players_ == 3) {
    // 17 actions + 16 cards each
    return 65;
  } else {
    // 24 actions + 12 cards each
    return 72;
  }
}
MaxUtility()
double open_spiel::tarok::TarokGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 82 of file tarok.cc.
{ return 500.0; }
MinUtility()
double open_spiel::tarok::TarokGame::MinUtility () const override virtual
Implements open_spiel::Game.
Definition at line 80 of file tarok.cc.
{ return -500.0; }
NewInitialState()
std::unique_ptr< State > open_spiel::tarok::TarokGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 65 of file tarok.cc.
{
  return NewInitialTarokState();
}
References NewInitialTarokState().
NewInitialTarokState()
std::unique_ptr< TarokState > open_spiel::tarok::TarokGame::NewInitialTarokState () const
Definition at line 69 of file tarok.cc.
{
  return std::make_unique<TarokState>(shared_from_this());
}
Referenced by DeserializeState(), and NewInitialState().
NumDistinctActions()
int open_spiel::tarok::TarokGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 63 of file tarok.cc.
{ return 54; }
NumPlayers()
int open_spiel::tarok::TarokGame::NumPlayers () const override virtual
Implements open_spiel::Game.
Definition at line 78 of file tarok.cc.
{ return num_players_; }
SetRNGState()
void open_spiel::tarok::TarokGame::SetRNGState (const std::string & rng_state) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 122 of file tarok.cc.
{
  if (rng_state.empty()) return;
  std::istringstream rng_stream(rng_state);
  rng_stream >> rng_;
}
Friends And Related Symbol Documentation
TarokState
friend class TarokState friend
Definition at line 68 of file tarok.h.
The documentation for this class was generated from the following files:
open_spiel/games/tarok/tarok.h
open_spiel/games/tarok/tarok.cc