open spiel: open_spiel::deep_sea::DeepSeaGame Class Reference
open_spiel::deep_sea::DeepSeaGame Class Reference
#include <deep_sea.h>
Public Member Functions
DeepSeaGame (const GameParameters &params)
std::unique_ptr< State > NewInitialState () const override
std::vector< int > ObservationTensorShape () const override
int NumDistinctActions () const override
int MaxChanceOutcomes () const override
int NumPlayers () const override
double MaxUtility () const override
double MinUtility () const override
int MaxGameLength () const override
double UnscaledMoveCost () const
std::vector< bool > ActionMapping () const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 93 of file deep_sea.h.
Constructor & Destructor Documentation
DeepSeaGame()
open_spiel::deep_sea::DeepSeaGame::DeepSeaGame (const GameParameters & params) explicit
Definition at line 186 of file deep_sea.cc.
    : Game(kGameType, params),
      size_(ParameterValue<int>("size")),
      unscaled_move_cost_(ParameterValue<double>("unscaled_move_cost")) {
  action_mapping_.resize(size_ * size_);
  if (ParameterValue<bool>("randomize_actions")) {
    std::seed_seq seq{ParameterValue<int>("seed")};
    std::mt19937 rng(seq);
    for (int i = 0; i < action_mapping_.size(); ++i) {
      action_mapping_[i] = absl::Uniform<int>(rng, 0, 2);
    }
  } else {
    std::fill(action_mapping_.begin(), action_mapping_.end(), true);
  }
}
References i, open_spiel::Game::ParameterValue(), and absl::Uniform().
Member Function Documentation
ActionMapping()
std::vector< bool > open_spiel::deep_sea::DeepSeaGame::ActionMapping () const inline
Definition at line 113 of file deep_sea.h.
{ return action_mapping_; }
Referenced by open_spiel::deep_sea::DeepSeaState::DeepSeaState().
MaxChanceOutcomes()
int open_spiel::deep_sea::DeepSeaGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 104 of file deep_sea.h.
{ return kNumActions; }
References open_spiel::deep_sea::kNumActions.
MaxGameLength()
int open_spiel::deep_sea::DeepSeaGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 108 of file deep_sea.h.
{ return size_; }
Referenced by open_spiel::deep_sea::DeepSeaState::DeepSeaState().
MaxUtility()
double open_spiel::deep_sea::DeepSeaGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 106 of file deep_sea.h.
{ return 1 - unscaled_move_cost_; }
MinUtility()
double open_spiel::deep_sea::DeepSeaGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 107 of file deep_sea.h.
{ return -unscaled_move_cost_; }
NewInitialState()
std::unique_ptr< State > open_spiel::deep_sea::DeepSeaGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 96 of file deep_sea.h.
{
    return std::unique_ptr<State>(new DeepSeaState(shared_from_this()));
  }
NumDistinctActions()
int open_spiel::deep_sea::DeepSeaGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 103 of file deep_sea.h.
{ return kNumActions; }
References open_spiel::deep_sea::kNumActions.
NumPlayers()
int open_spiel::deep_sea::DeepSeaGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 105 of file deep_sea.h.
{ return kNumPlayers; }
References open_spiel::deep_sea::kNumPlayers.
ObservationTensorShape()
std::vector< int > open_spiel::deep_sea::DeepSeaGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 99 of file deep_sea.h.
{
    return {size_, size_};
  }
UnscaledMoveCost()
double open_spiel::deep_sea::DeepSeaGame::UnscaledMoveCost () const inline
Definition at line 110 of file deep_sea.h.
{ return unscaled_move_cost_; }
Referenced by open_spiel::deep_sea::DeepSeaState::DeepSeaState().
The documentation for this class was generated from the following files:
open_spiel/games/deep_sea/deep_sea.h
open_spiel/games/deep_sea/deep_sea.cc