open spiel: open_spiel::amazons::AmazonsState Class Reference
open_spiel::amazons::AmazonsState Class Reference
#include <amazons.h>
Public Types
enum MoveState { amazon_select , destination_select , shot_select }
Public Member Functions
AmazonsState (std::shared_ptr< const Game > game)
AmazonsState (const AmazonsState &)=default
AmazonsState & operator= (const AmazonsState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
void SetState (int cur_player, MoveState move_state, const std::array< CellState, kNumCells > &board)
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action move) override
std::vector< Action > LegalActions () const override
CellState BoardAt (int cell) const
CellState BoardAt (int row, int column) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes
std::array< CellState, kNumCells > board_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 51 of file amazons.h.
Member Enumeration Documentation
MoveState
enum open_spiel::amazons::AmazonsState::MoveState
Enumerator
amazon_select
destination_select
shot_select
Definition at line 53 of file amazons.h.
{ amazon_select, destination_select, shot_select };
Constructor & Destructor Documentation
AmazonsState() [1/2]
open_spiel::amazons::AmazonsState::AmazonsState (std::shared_ptr< const Game > game)
Definition at line 391 of file amazons.cc.
                                                         : State(game) {
  std::fill(begin(board_), end(board_), CellState::kEmpty);
  switch (kNumRows) {
    case 6:
      board_[1] = board_[4] = board_[6] = board_[11] = CellState::kCross;
      board_[24] = board_[29] = board_[31] = board_[34] = CellState::kNought;
      break;
    case 8:
      board_[2] = board_[5] = board_[16] = board_[23] = CellState::kCross;
      board_[40] = board_[47] = board_[58] = board_[61] = CellState::kNought;
      break;
  }
}
References begin, board_, end, open_spiel::amazons::kCross, open_spiel::amazons::kEmpty, and open_spiel::amazons::kNought.
Referenced by Clone().
AmazonsState() [2/2]
open_spiel::amazons::AmazonsState::AmazonsState (const AmazonsState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::amazons::AmazonsState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 369 of file amazons.cc.
{
  std::string str = absl::StrCat("(", (action / kNumRows) + 1, ", ",
                                 (action % kNumRows) + 1, ")");
  switch (state_) {
    case amazon_select:
      return absl::StrCat(StateToString(PlayerToState(player)), " From ", str);
    case destination_select:
      return absl::StrCat(StateToString(PlayerToState(player)), " To ", str);
    case shot_select:
      return absl::StrCat(StateToString(PlayerToState(player)),
                          " Shoot:  ", str);
  }
  std::cerr << "Unhandled case in AmazonState::ActionToString, "
            << "returning empty string." << std::endl;
  return "";
}
References action, amazon_select, destination_select, player, open_spiel::amazons::PlayerToState(), shot_select, open_spiel::amazons::StateToString(), and absl::StrCat().
BoardAt() [1/2]
CellState open_spiel::amazons::AmazonsState::BoardAt (int cell) const inline
Definition at line 88 of file amazons.h.
{ return board_[cell]; }
References board_.
Referenced by ToString().
BoardAt() [2/2]
CellState open_spiel::amazons::AmazonsState::BoardAt (int row, int column) const inline
Definition at line 89 of file amazons.h.
{
    return board_[row * kNumCols + column];
  }
References board_.
Clone()
std::unique_ptr< State > open_spiel::amazons::AmazonsState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 462 of file amazons.cc.
{
  return std::unique_ptr<State>(new AmazonsState(*this));
}
References AmazonsState().
CurrentPlayer()
Player open_spiel::amazons::AmazonsState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 61 of file amazons.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Referenced by DoApplyAction(), and LegalActions().
DoApplyAction()
void open_spiel::amazons::AmazonsState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 271 of file amazons.cc.
{
  switch (state_) {
    case amazon_select: {
      SPIEL_CHECK_EQ(board_[action], PlayerToState(CurrentPlayer()));
      from_ = action;
      board_[from_] = CellState::kEmpty;
      state_ = destination_select;
    }
    break;
    case destination_select: {
      SPIEL_CHECK_EQ(board_[action], CellState::kEmpty);
      to_ = action;
      board_[to_] = PlayerToState(CurrentPlayer());
      state_ = shot_select;
      break;
    }
    case shot_select: {
      SPIEL_CHECK_EQ(board_[action], CellState::kEmpty);
      shoot_ = action;
      board_[shoot_] = CellState::kBlock;
      current_player_ = 1 - current_player_;
      state_ = amazon_select;
      // Check if game is over
      if (LegalActions().empty()) {
        // outcome  = winner
        outcome_ = 1 - current_player_;
      }
    }
    break;
  }
  ++num_moves_;
}
References action, amazon_select, board_, CurrentPlayer(), destination_select, open_spiel::amazons::kBlock, open_spiel::amazons::kEmpty, LegalActions(), open_spiel::amazons::PlayerToState(), shot_select, and SPIEL_CHECK_EQ.
InformationStateString()
std::string open_spiel::amazons::AmazonsState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 438 of file amazons.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::amazons::AmazonsState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 426 of file amazons.cc.
{ return outcome_ != kInvalidPlayer; }
References open_spiel::kInvalidPlayer.
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::amazons::AmazonsState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 337 of file amazons.cc.
{
  if (IsTerminal()) return {};
  std::vector<Action> actions;
  switch (state_) {
    case amazon_select:
      for (int i = 0; i < board_.size(); i++) {
        if (board_[i] == PlayerToState(CurrentPlayer())) {
          // check if the selected amazon has a possible move
          if (GetAllMoves(i).empty()) continue;
          actions.push_back(i);
        }
      }
      break;
    case destination_select:
      actions = GetAllMoves(from_);
      break;
    case shot_select:
      actions = GetAllMoves(to_);
      break;
  }
  sort(actions.begin(), actions.end());
  return actions;
}
References amazon_select, board_, CurrentPlayer(), destination_select, i, IsTerminal(), open_spiel::amazons::PlayerToState(), and shot_select.
Referenced by DoApplyAction().
ObservationString()
std::string open_spiel::amazons::AmazonsState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 444 of file amazons.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::amazons::AmazonsState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 450 of file amazons.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // Treat `values` as a 2-d tensor.
  TensorView<2> view(values, {kCellStates, kNumCells}, true);
  for (int cell = 0; cell < kNumCells; ++cell) {
    view[{static_cast<int>(board_[cell]), cell}] = 1.0;
  }
}
References board_, open_spiel::amazons::kCellStates, open_spiel::amazons::kNumCells, open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
operator=()
AmazonsState & open_spiel::amazons::AmazonsState::operator= (const AmazonsState &) default
Returns()
std::vector< double > open_spiel::amazons::AmazonsState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 428 of file amazons.cc.
{
  if (outcome_ == (Player{0})) {
    return {1.0, -1.0};
  } else if (outcome_ == (Player{1})) {
    return {-1.0, 1.0};
  } else {
    return {0.0, 0.0};
  }
}
SetState()
void open_spiel::amazons::AmazonsState::SetState (int cur_player, MoveState move_state, const std::array< CellState, kNumCells > & board)
Definition at line 406 of file amazons.cc.
{
  current_player_ = cur_player;
  state_ = move_state;
  board_ = board;
}
References board_.
ToString()
std::string open_spiel::amazons::AmazonsState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 413 of file amazons.cc.
{
  std::string str;
  for (int r = 0; r < kNumRows; ++r) {
    for (int c = 0; c < kNumCols; ++c) {
      absl::StrAppend(&str, StateToString(BoardAt(r, c)));
    }
    if (r < (kNumRows - 1)) {
      absl::StrAppend(&str, "\n");
    }
  }
  return str;
}
References BoardAt(), open_spiel::amazons::kNumCols, open_spiel::amazons::kNumRows, r, open_spiel::amazons::StateToString(), and absl::StrAppend().
Referenced by ObservationString().
UndoAction()
void open_spiel::amazons::AmazonsState::UndoAction (Player player, Action move) override virtual
Reimplemented from open_spiel::State.
Definition at line 306 of file amazons.cc.
{
  switch (state_) {
    case amazon_select: {
      shoot_ = move;
      board_[shoot_] = CellState::kEmpty;
      current_player_ = player;
      outcome_ = kInvalidPlayer;
      state_ = shot_select;
    }
    break;
    case destination_select: {
      from_ = move;
      board_[from_] = PlayerToState(player);
      state_ = amazon_select;
    }
    break;
    case shot_select: {
      to_ = move;
      board_[to_] = CellState::kEmpty;
      state_ = destination_select;
    }
    break;
  }
  --num_moves_;
  --move_number_;
  history_.pop_back();
}
References amazon_select, board_, destination_select, open_spiel::State::history_, open_spiel::amazons::kEmpty, open_spiel::kInvalidPlayer, open_spiel::State::move_number_, player, open_spiel::amazons::PlayerToState(), and shot_select.
Member Data Documentation
board_
std::array<CellState, kNumCells> open_spiel::amazons::AmazonsState::board_ protected
Definition at line 94 of file amazons.h.
Referenced by AmazonsState(), BoardAt(), BoardAt(), DoApplyAction(), LegalActions(), ObservationTensor(), SetState(), and UndoAction().
The documentation for this class was generated from the following files:
open_spiel/games/amazons/amazons.h
open_spiel/games/amazons/amazons.cc