open spiel: open_spiel::gin_rummy::SimpleGinRummyBot Class Reference
open_spiel::gin_rummy::SimpleGinRummyBot Class Reference
#include <simple_gin_rummy_bot.h>
Public Member Functions
SimpleGinRummyBot (GameParameters params, Player player_id)
void Restart () override
Action Step (const State &state) override
bool ProvidesPolicy () override
std::pair< ActionsAndProbs, Action > StepWithPolicy (const State &state) override
ActionsAndProbs GetPolicy (const State &state) override
bool IsClonable () const override
std::unique_ptr< Bot > Clone () override
SimpleGinRummyBot (const SimpleGinRummyBot &other)=default
Public Member Functions inherited from open_spiel::Bot
virtual ~Bot ()=default
virtual void InformAction (const State &state, Player player_id, Action action)
virtual void InformActions (const State &state, const std::vector< Action > &actions)
virtual void RestartAt (const State &state)
virtual bool ProvidesForceAction ()
virtual void ForceAction (const State &state, Action action)
Detailed Description
Definition at line 64 of file simple_gin_rummy_bot.h.
Constructor & Destructor Documentation
SimpleGinRummyBot() [1/2]
open_spiel::gin_rummy::SimpleGinRummyBot::SimpleGinRummyBot (GameParameters params, Player player_id)
Definition at line 28 of file simple_gin_rummy_bot.cc.
    : params_(std::move(params)),
      player_id_(player_id),
      hand_size_(params_["hand_size"].int_value()),
      utils_(params_["num_ranks"].int_value(), params_["num_suits"].int_value(),
             params_["hand_size"].int_value()) {}
SimpleGinRummyBot() [2/2]
open_spiel::gin_rummy::SimpleGinRummyBot::SimpleGinRummyBot (const SimpleGinRummyBot & other) default
Member Function Documentation
Clone()
std::unique_ptr< Bot > open_spiel::gin_rummy::SimpleGinRummyBot::Clone () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 77 of file simple_gin_rummy_bot.h.
{
    return std::make_unique<SimpleGinRummyBot>(*this);
  }
GetPolicy()
ActionsAndProbs open_spiel::gin_rummy::SimpleGinRummyBot::GetPolicy (const State & state) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 41 of file simple_gin_rummy_bot.cc.
{
  ActionsAndProbs policy;
  auto legal_actions = state.LegalActions(player_id_);
  auto chosen_action = Step(state);
  for (auto action : legal_actions)
    policy.emplace_back(action, action == chosen_action ? 1.0 : 0.0);
  return policy;
}
References action, state, and Step().
IsClonable()
bool open_spiel::gin_rummy::SimpleGinRummyBot::IsClonable () const inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 76 of file simple_gin_rummy_bot.h.
{ return true; }
ProvidesPolicy()
bool open_spiel::gin_rummy::SimpleGinRummyBot::ProvidesPolicy () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 71 of file simple_gin_rummy_bot.h.
{ return true; }
Restart()
void open_spiel::gin_rummy::SimpleGinRummyBot::Restart () override virtual
Reimplemented from open_spiel::Bot.
Definition at line 36 of file simple_gin_rummy_bot.cc.
{
  knocked_ = false;
  next_actions_ = {};
}
Step()
Action open_spiel::gin_rummy::SimpleGinRummyBot::Step (const State & state) override virtual
Implements open_spiel::Bot.
Definition at line 60 of file simple_gin_rummy_bot.cc.
{
  std::vector<float> observation;
  state.ObservationTensor(player_id_, &observation);
  std::vector<int> hand;
  std::vector<int> layed_melds;
  std::vector<int> discard_pile;
  absl::optional<int> upcard = absl::nullopt;
  int knock_card = 0;
  int stock_size = 0;
  // Decode observation tensor.
  int offset = 0;
  SPIEL_CHECK_TRUE(observation[player_id_] == 1);
  offset += kNumPlayers;
  // Player hand.
  if (player_id_ == 1) offset += kDefaultNumCards;
  for (int i = 0; i < kDefaultNumCards; ++i) {
    if (observation[offset + i] == 1) hand.push_back(i);
  }
  offset += kDefaultNumCards;
  if (player_id_ == 0) offset += kDefaultNumCards;
  // Current player.
  SPIEL_CHECK_EQ(observation[offset + player_id_], 1);
  offset += kNumPlayers;
  // Knock card.
  for (int i = 0; i < kDefaultKnockCard; ++i) {
    if (observation[offset + i] == 1) knock_card += 1;
  }
  offset += kDefaultKnockCard;
  // Upcard.
  for (int i = 0; i < kDefaultNumCards; ++i) {
    if (observation[offset + i] == 1) upcard = i;
  }
  offset += kDefaultNumCards;
  // Discard pile.
  for (int i = 0; i < kDefaultNumCards; ++i) {
    if (observation[offset + i] == 1) discard_pile.push_back(i);
  }
  offset += kDefaultNumCards;
  // Stock size.
  for (int i = 0; i < kDefaultNumCards; ++i) {
    if (observation[offset + i] == 1) stock_size += 1;
  }
  offset += kDefaultNumCards;
  // Layed melds. Player 0 looks at player 1's layed melds and vice versa.
  if (player_id_ == 0) offset += kNumMeldActions;
  for (int i = 0; i < kNumMeldActions; ++i) {
    if (observation[offset + i] == 1) {
      layed_melds.push_back(i);
      knocked_ = true;
    }
  }  // Completed decoding observation.
  auto legal_actions = state.LegalActions(player_id_);
  // Next actions must be legal, in order from back to front.
  if (!next_actions_.empty()) {
    Action action = next_actions_.back();
    if (std::find(legal_actions.begin(), legal_actions.end(), action) ==
        legal_actions.end()) {
      std::cerr << "Game state:" << std::endl;
      std::cerr << state.ToString() << std::endl;
      std::cerr << "Legal actions: " << legal_actions << std::endl;
      std::cerr << "Bot next actions: " << next_actions_ << std::endl;
      SpielFatalError("Previously determined next action is illegal.");
    }
    next_actions_.pop_back();
    return action;
  }
  // When knocking, bot decides how to lay the hand all at once and saves the
  // corresponding meld actions in next_actions_.
  if (knocked_) {
    if (!layed_melds.empty()) {
      // Opponent knocked.
      next_actions_.push_back(kPassAction);  // Bot never lays off.
      for (int meld_id : GetMelds(hand)) {
        next_actions_.push_back(kMeldActionBase + meld_id);
      }
      next_actions_.push_back(kPassAction);
    } else {
      next_actions_.push_back(kPassAction);
      std::vector<int> melds_to_lay = GetMelds(hand);
      for (int meld_id : melds_to_lay) {
        next_actions_.push_back(kMeldActionBase + meld_id);
      }
      int best_discard = GetDiscard(hand);
      next_actions_.push_back(best_discard);
    }
    Action action = next_actions_.back();
    SPIEL_CHECK_TRUE(std::find(legal_actions.begin(),
        legal_actions.end(), action) != legal_actions.end());
    next_actions_.pop_back();
    return action;
  } else if (!upcard.has_value()) {
    // MoveType kDiscard
    if (hand.size() != hand_size_ + 1) {
      std::cerr << "Game state:" << std::endl;
      std::cerr << state.ToString() << std::endl;
      std::cerr << "Bot hand:" << std::endl;
      std::cerr << utils_.HandToString(hand);
      SpielFatalError("Discarding with an insufficient number of cards.");
    }
    int deadwood = utils_.MinDeadwood(hand);
    if (deadwood <= knock_card && !knocked_) {
      knocked_ = true;
      return kKnockAction;
    } else {
      int best_discard = GetDiscard(hand);
      if (best_discard >= 0) {
        return best_discard;
      } else {
        return legal_actions[0];
      }
    }
  } else {
    // MoveType kDraw
    if (stock_size == kWallStockSize) {
      // Special rules apply when we've reached the wall.
      if (legal_actions.back() == kKnockAction) {
        knocked_ = true;
        return kKnockAction;
      } else {
        return kPassAction;
      }
    } else if (utils_.MinDeadwood(hand, upcard) <= knock_card ||
        !absl::c_linear_search(GetBestDeadwood(hand, upcard), upcard)) {
      // Draw upcard if doing so permits a knock, or if the upcard would not be
      // in the "best" deadwood (=> upcard would be in a "best" meld).
      return kDrawUpcardAction;
    } else {
      return legal_actions.back();  // Draw from stock or pass.
    }
  }
}
References action, absl::c_linear_search(), open_spiel::gin_rummy::GinRummyUtils::HandToString(), absl::optional< T >::has_value(), i, open_spiel::gin_rummy::kDefaultKnockCard, open_spiel::gin_rummy::kDefaultNumCards, open_spiel::gin_rummy::kDrawUpcardAction, open_spiel::gin_rummy::kKnockAction, open_spiel::gin_rummy::kMeldActionBase, open_spiel::gin_rummy::kNumMeldActions, open_spiel::gin_rummy::kNumPlayers, open_spiel::gin_rummy::kPassAction, open_spiel::gin_rummy::kWallStockSize, open_spiel::gin_rummy::GinRummyUtils::MinDeadwood(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), and state.
Referenced by GetPolicy(), and StepWithPolicy().
StepWithPolicy()
std::pair< ActionsAndProbs, Action > open_spiel::gin_rummy::SimpleGinRummyBot::StepWithPolicy (const State & state) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 50 of file simple_gin_rummy_bot.cc.
{
  ActionsAndProbs policy;
  auto legal_actions = state.LegalActions(player_id_);
  auto chosen_action = Step(state);
  for (auto action : legal_actions)
    policy.emplace_back(action, action == chosen_action ? 1.0 : 0.0);
  return {policy, chosen_action};
}
References action, state, and Step().
The documentation for this class was generated from the following files:
open_spiel/bots/gin_rummy/simple_gin_rummy_bot.h
open_spiel/bots/gin_rummy/simple_gin_rummy_bot.cc