open spiel: absl::any Class Reference
absl::any Class Reference
#include <any.h>
Classes
struct IsInPlaceType
struct IsInPlaceType< in_place_type_t< T > >
Public Member Functions
constexpr any () noexcept
any (const any &other)
any (any &&other) noexcept=default
template<typename T , typename VT = absl::decay_t<T>, absl::enable_if_t<!absl::disjunction< std::is_same< any, VT >, IsInPlaceType< VT >, absl::negation< std::is_copy_constructible< VT > > >::value > * = nullptr>
any (T &&value)
template<typename T , typename... Args, typename VT = absl::decay_t<T>, absl::enable_if_t< absl::conjunction< std::is_copy_constructible< VT >, std::is_constructible< VT, Args... > >::value > * = nullptr>
any (in_place_type_t< T >, Args &&... args)
template<typename T , typename U , typename... Args, typename VT = absl::decay_t<T>, absl::enable_if_t< absl::conjunction< std::is_copy_constructible< VT >, std::is_constructible< VT, std::initializer_list< U > &, Args... > >::value > * = nullptr>
any (in_place_type_t< T >, std::initializer_list< U > ilist, Args &&... args)
any & operator= (const any &rhs)
any & operator= (any &&rhs) noexcept
template<typename T , typename VT = absl::decay_t<T>, absl::enable_if_t< absl::conjunction< absl::negation< std::is_same< VT, any > >, std::is_copy_constructible< VT > >::value > * = nullptr>
any & operator= (T &&rhs)
template<typename T , typename... Args, typename VT = absl::decay_t<T>, absl::enable_if_t< std::is_copy_constructible< VT >::value &&std::is_constructible< VT, Args... >::value > * = nullptr>
VT & emplace (Args &&... args)
template<typename T , typename U , typename... Args, typename VT = absl::decay_t<T>, absl::enable_if_t< std::is_copy_constructible< VT >::value &&std::is_constructible< VT, std::initializer_list< U > &, Args... >::value > * = nullptr>
VT & emplace (std::initializer_list< U > ilist, Args &&... args)
void reset () noexcept
void swap (any &other) noexcept
bool has_value () const noexcept
Friends
template<typename ValueType >
ValueType any_cast (const any &operand)
template<typename ValueType >
ValueType any_cast (any &operand)
template<typename T >
const T * any_cast (const any *operand)
template<typename T >
T * any_cast (any *operand)
Detailed Description
Definition at line 189 of file any.h.
Constructor & Destructor Documentation
any() [1/6]
absl::any::any () constexpr default noexcept
Referenced by operator=(), and operator=().
any() [2/6]
absl::any::any (const any & other) inline
Definition at line 204 of file any.h.
      : obj_(other.has_value() ? other.obj_->Clone()
                               : std::unique_ptr<ObjInterface>()) {}
any() [3/6]
absl::any::any (any && other) default noexcept
any() [4/6]
template<typename T , typename VT = absl::decay_t<T>, absl::enable_if_t<!absl::disjunction< std::is_same< any, VT >, IsInPlaceType< VT >, absl::negation< std::is_copy_constructible< VT > > >::value > * = nullptr> absl::any::any (T && value) inline
Definition at line 223 of file any.h.
: obj_(new Obj<VT>(in_place, std::forward<T>(value))) {}
any() [5/6]
template<typename T , typename... Args, typename VT = absl::decay_t<T>, absl::enable_if_t< absl::conjunction< std::is_copy_constructible< VT >, std::is_constructible< VT, Args... > >::value > * = nullptr> absl::any::any (in_place_type_t< T > , Args &&... args) inline explicit
Definition at line 231 of file any.h.
      : obj_(new Obj<VT>(in_place, std::forward<Args>(args)...)) {}
any() [6/6]
template<typename T , typename U , typename... Args, typename VT = absl::decay_t<T>, absl::enable_if_t< absl::conjunction< std::is_copy_constructible< VT >, std::is_constructible< VT, std::initializer_list< U > &, Args... > >::value > * = nullptr> absl::any::any (in_place_type_t< T > , std::initializer_list< U > ilist, Args &&... args) inline explicit
Definition at line 244 of file any.h.
      : obj_(new Obj<VT>(in_place, ilist, std::forward<Args>(args)...)) {}
Member Function Documentation
emplace() [1/2]
template<typename T , typename... Args, typename VT = absl::decay_t<T>, absl::enable_if_t< std::is_copy_constructible< VT >::value &&std::is_constructible< VT, Args... >::value > * = nullptr> VT & absl::any::emplace (Args &&... args) inline
Definition at line 291 of file any.h.
{
    reset();  // NOTE: reset() is required here even in the world of exceptions.
    Obj<VT>* const object_ptr =
        new Obj<VT>(in_place, std::forward<Args>(args)...);
    obj_ = std::unique_ptr<ObjInterface>(object_ptr);
    return object_ptr->value;
  }
References reset().
emplace() [2/2]
template<typename T , typename U , typename... Args, typename VT = absl::decay_t<T>, absl::enable_if_t< std::is_copy_constructible< VT >::value &&std::is_constructible< VT, std::initializer_list< U > &, Args... >::value > * = nullptr> VT & absl::any::emplace (std::initializer_list< U > ilist, Args &&... args) inline
Definition at line 315 of file any.h.
{
    reset();  // NOTE: reset() is required here even in the world of exceptions.
    Obj<VT>* const object_ptr =
        new Obj<VT>(in_place, ilist, std::forward<Args>(args)...);
    obj_ = std::unique_ptr<ObjInterface>(object_ptr);
    return object_ptr->value;
  }
References reset().
has_value()
bool absl::any::has_value () const inline noexcept
Definition at line 340 of file any.h.
{ return obj_ != nullptr; }
operator=() [1/3]
any & absl::any::operator= (any && rhs) inline noexcept
Definition at line 259 of file any.h.
{
    any(std::move(rhs)).swap(*this);
    return *this;
  }
References any(), and swap().
operator=() [2/3]
any & absl::any::operator= (const any & rhs) inline
Definition at line 252 of file any.h.
{
    any(rhs).swap(*this);
    return *this;
  }
References any(), and swap().
operator=() [3/3]
template<typename T , typename VT = absl::decay_t<T>, absl::enable_if_t< absl::conjunction< absl::negation< std::is_same< VT, any > >, std::is_copy_constructible< VT > >::value > * = nullptr> any & absl::any::operator= (T && rhs) inline
Definition at line 269 of file any.h.
{
    any tmp(in_place_type_t<VT>(), std::forward<T>(rhs));
    tmp.swap(*this);
    return *this;
  }
References swap().
reset()
void absl::any::reset () inline noexcept
Definition at line 327 of file any.h.
{ obj_ = nullptr; }
Referenced by open_spiel.python.utils.stats.BasicStats::__init__(), emplace(), emplace(), open_spiel.python.algorithms.ismcts.ISMCTSBot::run_search(), open_spiel.python.environments.catch.Environment::step(), open_spiel.python.environments.cliff_walking.Environment::step(), and open_spiel.python.vector_env.SyncVectorEnv::step().
swap()
void absl::any::swap (any & other) inline noexcept
Definition at line 332 of file any.h.
{ obj_.swap(other.obj_); }
Referenced by operator=(), operator=(), and operator=().
Friends And Related Symbol Documentation
any_cast [1/4]
template<typename ValueType > ValueType any_cast (any & operand) friend
Definition at line 468 of file any.h.
                                 {  // NOLINT(runtime/references)
  using U = typename std::remove_cv<
      typename std::remove_reference<ValueType>::type>::type;
  static_assert(std::is_constructible<ValueType, U&>::value,
                "Invalid ValueType");
  auto* result = (any_cast<U>)(&operand);
  if (result == nullptr) {
    any_internal::ThrowBadAnyCast();
  }
  return static_cast<ValueType>(*result);
}
any_cast [2/4]
template<typename T > T * any_cast (any * operand) friend
Definition at line 503 of file any.h.
{
  using U =
      typename std::remove_cv<typename std::remove_reference<T>::type>::type;
  return operand && operand->GetObjTypeId() == any::IdForType<U>()
             ? std::addressof(
                   static_cast<any::Obj<U>*>(operand->obj_.get())->value)
             : nullptr;
}
any_cast [3/4]
template<typename ValueType > ValueType any_cast (const any & operand) friend
Definition at line 454 of file any.h.
{
  using U = typename std::remove_cv<
      typename std::remove_reference<ValueType>::type>::type;
  static_assert(std::is_constructible<ValueType, const U&>::value,
                "Invalid ValueType");
  auto* const result = (any_cast<U>)(&operand);
  if (result == nullptr) {
    any_internal::ThrowBadAnyCast();
  }
  return static_cast<ValueType>(*result);
}
any_cast [4/4]
template<typename T > const T * any_cast (const any * operand) friend
Definition at line 492 of file any.h.
{
  using U =
      typename std::remove_cv<typename std::remove_reference<T>::type>::type;
  return operand && operand->GetObjTypeId() == any::IdForType<U>()
             ? std::addressof(
                   static_cast<const any::Obj<U>*>(operand->obj_.get())->value)
             : nullptr;
}
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/types/any.h