open spiel: absl::internal_statusor::StatusOrData< T > Class Template Reference
absl::internal_statusor::StatusOrData< T > Class Template Reference
#include <statusor_internal.h>
Classes
struct Dummy
Public Member Functions
StatusOrData ()=delete
StatusOrData (const StatusOrData &other)
StatusOrData (StatusOrData &&other) noexcept
template<typename U >
StatusOrData (const StatusOrData< U > &other)
template<typename U >
StatusOrData (StatusOrData< U > &&other)
template<typename... Args>
StatusOrData (absl::in_place_t, Args &&... args)
StatusOrData (const T &value)
StatusOrData (T &&value)
template<typename U , absl::enable_if_t< std::is_constructible< absl::Status, U && >::value, int > = 0>
StatusOrData (U &&v)
StatusOrData & operator= (const StatusOrData &other)
StatusOrData & operator= (StatusOrData &&other)
~StatusOrData ()
template<typename U >
void Assign (U &&value)
template<typename U >
void AssignStatus (U &&v)
bool ok () const
Protected Member Functions
void Clear ()
void EnsureOk () const
void EnsureNotOk ()
template<typename... Arg>
void MakeValue (Arg &&... arg)
template<typename... Args>
void MakeStatus (Args &&... args)
Protected Attributes
union {
Status status_
};
union {
Dummy dummy_
T data_
};
Friends
template<typename U >
class StatusOrData
Detailed Description
template<typename T>
class absl::internal_statusor::StatusOrData< T >
Definition at line 154 of file statusor_internal.h.
Constructor & Destructor Documentation
StatusOrData() [1/9]
template<typename T > absl::internal_statusor::StatusOrData< T >::StatusOrData () delete
StatusOrData() [2/9]
template<typename T > absl::internal_statusor::StatusOrData< T >::StatusOrData (const StatusOrData< T > & other) inline
Definition at line 161 of file statusor_internal.h.
{
    if (other.ok()) {
      MakeValue(other.data_);
      MakeStatus();
    } else {
      MakeStatus(other.status_);
    }
  }
References absl::internal_statusor::StatusOrData< T >::data_, absl::internal_statusor::StatusOrData< T >::MakeStatus(), absl::internal_statusor::StatusOrData< T >::MakeValue(), absl::internal_statusor::StatusOrData< T >::ok(), and absl::internal_statusor::StatusOrData< T >::status_.
StatusOrData() [3/9]
template<typename T > absl::internal_statusor::StatusOrData< T >::StatusOrData (StatusOrData< T > && other) inline noexcept
Definition at line 170 of file statusor_internal.h.
{
    if (other.ok()) {
      MakeValue(std::move(other.data_));
      MakeStatus();
    } else {
      MakeStatus(std::move(other.status_));
    }
  }
References absl::internal_statusor::StatusOrData< T >::MakeStatus(), and absl::internal_statusor::StatusOrData< T >::MakeValue().
StatusOrData() [4/9]
template<typename T > template<typename U > absl::internal_statusor::StatusOrData< T >::StatusOrData (const StatusOrData< U > & other) inline explicit
Definition at line 180 of file statusor_internal.h.
{
    if (other.ok()) {
      MakeValue(other.data_);
      MakeStatus();
    } else {
      MakeStatus(other.status_);
    }
  }
References absl::internal_statusor::StatusOrData< T >::data_, absl::internal_statusor::StatusOrData< T >::MakeStatus(), absl::internal_statusor::StatusOrData< T >::MakeValue(), absl::internal_statusor::StatusOrData< T >::ok(), and absl::internal_statusor::StatusOrData< T >::status_.
StatusOrData() [5/9]
template<typename T > template<typename U > absl::internal_statusor::StatusOrData< T >::StatusOrData (StatusOrData< U > && other) inline explicit
Definition at line 190 of file statusor_internal.h.
{
    if (other.ok()) {
      MakeValue(std::move(other.data_));
      MakeStatus();
    } else {
      MakeStatus(std::move(other.status_));
    }
  }
References absl::internal_statusor::StatusOrData< T >::MakeStatus(), and absl::internal_statusor::StatusOrData< T >::MakeValue().
StatusOrData() [6/9]
template<typename T > template<typename... Args> absl::internal_statusor::StatusOrData< T >::StatusOrData (absl::in_place_t , Args &&... args) inline explicit
Definition at line 200 of file statusor_internal.h.
      : data_(std::forward<Args>(args)...) {
    MakeStatus();
  }
References absl::internal_statusor::StatusOrData< T >::MakeStatus().
StatusOrData() [7/9]
template<typename T > absl::internal_statusor::StatusOrData< T >::StatusOrData (const T & value) inline explicit
Definition at line 205 of file statusor_internal.h.
                                        : data_(value) {
    MakeStatus();
  }
References absl::internal_statusor::StatusOrData< T >::MakeStatus().
StatusOrData() [8/9]
template<typename T > absl::internal_statusor::StatusOrData< T >::StatusOrData (T && value) inline explicit
Definition at line 208 of file statusor_internal.h.
                                   : data_(std::move(value)) {
    MakeStatus();
  }
References absl::internal_statusor::StatusOrData< T >::MakeStatus().
StatusOrData() [9/9]
template<typename T > template<typename U , absl::enable_if_t< std::is_constructible< absl::Status, U && >::value, int > = 0> absl::internal_statusor::StatusOrData< T >::StatusOrData (U && v) inline explicit
Definition at line 215 of file statusor_internal.h.
                               : status_(std::forward<U>(v)) {
    EnsureNotOk();
  }
References absl::internal_statusor::StatusOrData< T >::EnsureNotOk().
~StatusOrData()
template<typename T > absl::internal_statusor::StatusOrData< T >::~StatusOrData () inline
Definition at line 237 of file statusor_internal.h.
                  {
    if (ok()) {
      status_.~Status();
      data_.~T();
    } else {
      status_.~Status();
    }
  }
References absl::internal_statusor::StatusOrData< T >::data_, absl::internal_statusor::StatusOrData< T >::ok(), absl::internal_statusor::StatusOrData< T >::status_, and absl::Status::~Status().
Member Function Documentation
Assign()
template<typename T > template<typename U > void absl::internal_statusor::StatusOrData< T >::Assign (U && value) inline
Definition at line 247 of file statusor_internal.h.
{
    if (ok()) {
      data_ = std::forward<U>(value);
    } else {
      MakeValue(std::forward<U>(value));
      status_ = OkStatus();
    }
  }
References absl::internal_statusor::StatusOrData< T >::data_, absl::internal_statusor::StatusOrData< T >::MakeValue(), absl::internal_statusor::StatusOrData< T >::ok(), absl::OkStatus(), and absl::internal_statusor::StatusOrData< T >::status_.
Referenced by absl::internal_statusor::StatusOrData< T >::operator=(), and absl::internal_statusor::StatusOrData< T >::operator=().
AssignStatus()
template<typename T > template<typename U > void absl::internal_statusor::StatusOrData< T >::AssignStatus (U && v) inline
Definition at line 257 of file statusor_internal.h.
{
    Clear();
    status_ = static_cast<absl::Status>(std::forward<U>(v));
    EnsureNotOk();
  }
References absl::internal_statusor::StatusOrData< T >::Clear(), absl::internal_statusor::StatusOrData< T >::EnsureNotOk(), absl::internal_statusor::StatusOrData< T >::status_, and absl::v.
Referenced by absl::internal_statusor::StatusOrData< T >::operator=(), and absl::internal_statusor::StatusOrData< T >::operator=().
Clear()
template<typename T > void absl::internal_statusor::StatusOrData< T >::Clear () inline protected
Definition at line 284 of file statusor_internal.h.
               {
    if (ok()) data_.~T();
  }
References absl::internal_statusor::StatusOrData< T >::data_, and absl::internal_statusor::StatusOrData< T >::ok().
Referenced by absl::internal_statusor::StatusOrData< T >::AssignStatus().
EnsureNotOk()
template<typename T > void absl::internal_statusor::StatusOrData< T >::EnsureNotOk () inline protected
Definition at line 292 of file statusor_internal.h.
                     {
    if (ABSL_PREDICT_FALSE(ok())) Helper::HandleInvalidStatusCtorArg(&status_);
  }
References ABSL_PREDICT_FALSE, absl::internal_statusor::Helper::HandleInvalidStatusCtorArg(), absl::internal_statusor::StatusOrData< T >::ok(), and absl::internal_statusor::StatusOrData< T >::status_.
Referenced by absl::internal_statusor::StatusOrData< T >::AssignStatus(), and absl::internal_statusor::StatusOrData< T >::StatusOrData().
EnsureOk()
template<typename T > void absl::internal_statusor::StatusOrData< T >::EnsureOk () const inline protected
Definition at line 288 of file statusor_internal.h.
{
    if (ABSL_PREDICT_FALSE(!ok())) Helper::Crash(status_);
  }
References ABSL_PREDICT_FALSE, absl::internal_statusor::Helper::Crash(), absl::internal_statusor::StatusOrData< T >::ok(), and absl::internal_statusor::StatusOrData< T >::status_.
MakeStatus()
template<typename T > template<typename... Args> void absl::internal_statusor::StatusOrData< T >::MakeStatus (Args &&... args) inline protected
Definition at line 306 of file statusor_internal.h.
{
    internal_statusor::PlacementNew<Status>(&status_,
                                            std::forward<Args>(args)...);
  }
References absl::internal_statusor::args, and absl::internal_statusor::StatusOrData< T >::status_.
Referenced by absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), and absl::internal_statusor::StatusOrData< T >::StatusOrData().
MakeValue()
template<typename T > template<typename... Arg> void absl::internal_statusor::StatusOrData< T >::MakeValue (Arg &&... arg) inline protected
Definition at line 299 of file statusor_internal.h.
{
    internal_statusor::PlacementNew<T>(&dummy_, std::forward<Arg>(arg)...);
  }
References arg, and absl::internal_statusor::StatusOrData< T >::dummy_.
Referenced by absl::internal_statusor::StatusOrData< T >::Assign(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), and absl::internal_statusor::StatusOrData< T >::StatusOrData().
ok()
template<typename T > bool absl::internal_statusor::StatusOrData< T >::ok () const inline
Definition at line 263 of file statusor_internal.h.
{ return status_.ok(); }
References absl::Status::ok(), and absl::internal_statusor::StatusOrData< T >::status_.
Referenced by absl::internal_statusor::StatusOrData< T >::Assign(), absl::internal_statusor::StatusOrData< T >::Clear(), absl::internal_statusor::StatusOrData< T >::EnsureNotOk(), absl::internal_statusor::StatusOrData< T >::EnsureOk(), absl::internal_statusor::StatusOrData< T >::operator=(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), and absl::internal_statusor::StatusOrData< T >::~StatusOrData().
operator=() [1/2]
template<typename T > StatusOrData & absl::internal_statusor::StatusOrData< T >::operator= (const StatusOrData< T > & other) inline
Definition at line 219 of file statusor_internal.h.
{
    if (this == &other) return *this;
    if (other.ok())
      Assign(other.data_);
    else
      AssignStatus(other.status_);
    return *this;
  }
References absl::internal_statusor::StatusOrData< T >::Assign(), absl::internal_statusor::StatusOrData< T >::AssignStatus(), absl::internal_statusor::StatusOrData< T >::data_, absl::internal_statusor::StatusOrData< T >::ok(), and absl::internal_statusor::StatusOrData< T >::status_.
operator=() [2/2]
template<typename T > StatusOrData & absl::internal_statusor::StatusOrData< T >::operator= (StatusOrData< T > && other) inline
Definition at line 228 of file statusor_internal.h.
{
    if (this == &other) return *this;
    if (other.ok())
      Assign(std::move(other.data_));
    else
      AssignStatus(std::move(other.status_));
    return *this;
  }
References absl::internal_statusor::StatusOrData< T >::Assign(), and absl::internal_statusor::StatusOrData< T >::AssignStatus().
Friends And Related Symbol Documentation
StatusOrData
template<typename T > template<typename U > friend class StatusOrData friend
Definition at line 156 of file statusor_internal.h.
Member Data Documentation
[union]
union { ... } absl::internal_statusor::StatusOrData< T >
[union]
union { ... } absl::internal_statusor::StatusOrData< T >
data_
template<typename T > T absl::internal_statusor::StatusOrData< T >::data_
Definition at line 281 of file statusor_internal.h.
Referenced by absl::internal_statusor::StatusOrData< T >::Assign(), absl::internal_statusor::StatusOrData< T >::Clear(), absl::internal_statusor::StatusOrData< T >::operator=(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), and absl::internal_statusor::StatusOrData< T >::~StatusOrData().
dummy_
template<typename T > Dummy absl::internal_statusor::StatusOrData< T >::dummy_
Definition at line 280 of file statusor_internal.h.
Referenced by absl::internal_statusor::StatusOrData< T >::MakeValue().
status_
template<typename T > Status absl::internal_statusor::StatusOrData< T >::status_
Definition at line 272 of file statusor_internal.h.
Referenced by absl::internal_statusor::StatusOrData< T >::Assign(), absl::internal_statusor::StatusOrData< T >::AssignStatus(), absl::internal_statusor::StatusOrData< T >::EnsureNotOk(), absl::internal_statusor::StatusOrData< T >::EnsureOk(), absl::internal_statusor::StatusOrData< T >::MakeStatus(), absl::internal_statusor::StatusOrData< T >::ok(), absl::internal_statusor::StatusOrData< T >::operator=(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), absl::internal_statusor::StatusOrData< T >::StatusOrData(), and absl::internal_statusor::StatusOrData< T >::~StatusOrData().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/status/internal/statusor_internal.h