open spiel: absl::ReaderMutexLock Class Reference
absl::ReaderMutexLock Class Reference
#include <mutex.h>
Public Member Functions
ReaderMutexLock (Mutex *mu) ABSL_SHARED_LOCK_FUNCTION(mu)
ReaderMutexLock (Mutex *mu, const Condition &cond) ABSL_SHARED_LOCK_FUNCTION(mu)
ReaderMutexLock (const ReaderMutexLock &)=delete
ReaderMutexLock (ReaderMutexLock &&)=delete
ReaderMutexLock & operator= (const ReaderMutexLock &)=delete
ReaderMutexLock & operator= (ReaderMutexLock &&)=delete
~ReaderMutexLock () ABSL_UNLOCK_FUNCTION()
Detailed Description
Definition at line 562 of file mutex.h.
Constructor & Destructor Documentation
ReaderMutexLock() [1/4]
absl::ReaderMutexLock::ReaderMutexLock (Mutex * mu) inline explicit
Definition at line 564 of file mutex.h.
                                                                    : mu_(mu) {
    mu->ReaderLock();
  }
References absl::Mutex::ReaderLock().
ReaderMutexLock() [2/4]
absl::ReaderMutexLock::ReaderMutexLock (Mutex * mu, const Condition & cond) inline explicit
Definition at line 568 of file mutex.h.
      : mu_(mu) {
    mu->ReaderLockWhen(cond);
  }
References absl::Mutex::ReaderLockWhen().
ReaderMutexLock() [3/4]
absl::ReaderMutexLock::ReaderMutexLock (const ReaderMutexLock &) delete
ReaderMutexLock() [4/4]
absl::ReaderMutexLock::ReaderMutexLock (ReaderMutexLock &&) delete
~ReaderMutexLock()
absl::ReaderMutexLock::~ReaderMutexLock () inline
Definition at line 579 of file mutex.h.
{ this->mu_->ReaderUnlock(); }
References absl::Mutex::ReaderUnlock().
Member Function Documentation
operator=() [1/2]
ReaderMutexLock & absl::ReaderMutexLock::operator= (const ReaderMutexLock &) delete
operator=() [2/2]
ReaderMutexLock & absl::ReaderMutexLock::operator= (ReaderMutexLock &&) delete
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/synchronization/mutex.h