open spiel: open_spiel::matrix_game::MatrixGame Class Reference
open_spiel::matrix_game::MatrixGame Class Reference
#include <matrix_game.h>
Public Member Functions
MatrixGame (GameType game_type, GameParameters game_parameters, std::vector< std::string > row_action_names, std::vector< std::string > col_action_names, std::vector< double > row_utilities, std::vector< double > col_utilities)
MatrixGame (GameType game_type, GameParameters game_parameters, std::vector< std::string > row_action_names, std::vector< std::string > col_action_names, const std::vector< std::vector< double > > row_utilities, const std::vector< std::vector< double > > col_utilities)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
absl::optional< double > UtilitySum () const override
std::string ActionToString (Player player, Action action) const override
int NumRows () const
int NumCols () const
double RowUtility (int row, int col) const
double ColUtility (int row, int col) const
double PlayerUtility (Player player, int row, int col) const
const std::vector< double > & RowUtilities () const
const std::vector< double > & ColUtilities () const
const std::vector< double > & PlayerUtilities (const Player player) const
const std::string & RowActionName (int row) const
const std::string & ColActionName (int col) const
std::vector< double > GetUtilities (const std::vector< Action > &joint_action) const override
double GetUtility (Player player, const std::vector< Action > &joint_action) const override
bool operator== (const Game &other_game) const override
bool ApproxEqual (const Game &other_game, double tolerance) const
Public Member Functions inherited from open_spiel::NormalFormGame
std::vector< int > InformationStateTensorShape () const override
std::vector< int > ObservationTensorShape () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
absl::optional< double > UtilitySum () const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::NormalFormGame
NormalFormGame (GameType game_type, GameParameters game_parameters)
Protected Member Functions inherited from open_spiel::SimMoveGame
SimMoveGame (GameType game_type, GameParameters game_parameters)
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 43 of file matrix_game.h.
Constructor & Destructor Documentation
MatrixGame() [1/2]
open_spiel::matrix_game::MatrixGame::MatrixGame (GameType game_type, GameParameters game_parameters, std::vector< std::string > row_action_names, std::vector< std::string > col_action_names, std::vector< double > row_utilities, std::vector< double > col_utilities) inline
Definition at line 45 of file matrix_game.h.
      : NormalFormGame(game_type, game_parameters),
        row_action_names_(row_action_names),
        col_action_names_(col_action_names),
        row_utilities_(row_utilities),
        col_utilities_(col_utilities) {}
MatrixGame() [2/2]
open_spiel::matrix_game::MatrixGame::MatrixGame (GameType game_type, GameParameters game_parameters, std::vector< std::string > row_action_names, std::vector< std::string > col_action_names, const std::vector< std::vector< double > > row_utilities, const std::vector< std::vector< double > > col_utilities) inline
Definition at line 56 of file matrix_game.h.
      : NormalFormGame(game_type, game_parameters),
        row_action_names_(row_action_names),
        col_action_names_(col_action_names),
        row_utilities_(FlattenMatrix(row_utilities)),
        col_utilities_(FlattenMatrix(col_utilities)) {}
Member Function Documentation
ActionToString()
std::string open_spiel::matrix_game::MatrixGame::ActionToString (Player player, Action action) const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 90 of file matrix_game.h.
{
    switch (player) {
      case 0: {
        SPIEL_CHECK_GE(action, 0);
        SPIEL_CHECK_LT(action, row_action_names_.size());
        return row_action_names_[action];
      }
      case 1: {
        SPIEL_CHECK_GE(action, 0);
        SPIEL_CHECK_LT(action, col_action_names_.size());
        return col_action_names_[action];
      }
      default:
        SpielFatalError("Unknown player");
    }
  }
References SPIEL_CHECK_GE, SPIEL_CHECK_LT, and open_spiel::SpielFatalError().
ApproxEqual()
bool open_spiel::matrix_game::MatrixGame::ApproxEqual (const Game & other_game, double tolerance) const inline
Definition at line 156 of file matrix_game.h.
{
    const auto& other = down_cast<const MatrixGame&>(other_game);
    return (row_action_names_.size() == other.row_action_names_.size() &&
            col_action_names_.size() == other.col_action_names_.size() &&
            AllNear(row_utilities_, other.row_utilities_, tolerance) &&
            AllNear(col_utilities_, other.col_utilities_, tolerance));
  }
References open_spiel::AllNear(), and open_spiel::down_cast().
ColActionName()
const std::string & open_spiel::matrix_game::MatrixGame::ColActionName (int col) const inline
Definition at line 133 of file matrix_game.h.
{
    return col_action_names_[col];
  }
Referenced by open_spiel::matrix_game::MatrixState::ActionToString().
ColUtilities()
const std::vector< double > & open_spiel::matrix_game::MatrixGame::ColUtilities () const inline
Definition at line 124 of file matrix_game.h.
{ return col_utilities_; }
ColUtility()
double open_spiel::matrix_game::MatrixGame::ColUtility (int row, int col) const inline
Definition at line 115 of file matrix_game.h.
{
    return col_utilities_[Index(row, col)];
  }
Referenced by open_spiel::matrix_game::MatrixState::Returns(), and open_spiel::matrix_game::MatrixState::ToString().
GetUtilities()
std::vector< double > open_spiel::matrix_game::MatrixGame::GetUtilities (const std::vector< Action > & joint_action) const inline override virtual
Reimplemented from open_spiel::NormalFormGame.
Definition at line 137 of file matrix_game.h.
                     {
    int index = Index(joint_action[0], joint_action[1]);
    return {row_utilities_[index], col_utilities_[index]};
  }
GetUtility()
double open_spiel::matrix_game::MatrixGame::GetUtility (Player player, const std::vector< Action > & joint_action) const inline override virtual
Reimplemented from open_spiel::NormalFormGame.
Definition at line 143 of file matrix_game.h.
                     {
    return PlayerUtility(player, joint_action[0], joint_action[1]);
  }
References PlayerUtility().
MaxUtility()
double open_spiel::matrix_game::MatrixGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 82 of file matrix_game.h.
{
    return std::max(
        *std::max_element(begin(row_utilities_), end(row_utilities_)),
        *std::max_element(begin(col_utilities_), end(col_utilities_)));
  }
MinUtility()
double open_spiel::matrix_game::MatrixGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 76 of file matrix_game.h.
{
    return std::min(
        *std::min_element(begin(row_utilities_), end(row_utilities_)),
        *std::min_element(begin(col_utilities_), end(col_utilities_)));
  }
NewInitialState()
std::unique_ptr< State > open_spiel::matrix_game::MatrixGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 118 of file matrix_game.cc.
{
  return std::unique_ptr<State>(new MatrixState(shared_from_this()));
}
NumCols()
int open_spiel::matrix_game::MatrixGame::NumCols () const inline
Definition at line 111 of file matrix_game.h.
{ return col_action_names_.size(); }
Referenced by open_spiel::matrix_game::MatrixState::DoApplyActions(), open_spiel::matrix_game::MatrixState::LegalActions(), NumDistinctActions(), and open_spiel::matrix_game::MatrixState::ToString().
NumDistinctActions()
int open_spiel::matrix_game::MatrixGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 68 of file matrix_game.h.
{
    return std::max(NumRows(), NumCols());
  }
References NumCols(), and NumRows().
NumPlayers()
int open_spiel::matrix_game::MatrixGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 74 of file matrix_game.h.
{ return 2; }
NumRows()
int open_spiel::matrix_game::MatrixGame::NumRows () const inline
Definition at line 110 of file matrix_game.h.
{ return row_action_names_.size(); }
Referenced by open_spiel::matrix_game::MatrixState::DoApplyActions(), open_spiel::matrix_game::MatrixState::LegalActions(), NumDistinctActions(), and open_spiel::matrix_game::MatrixState::ToString().
operator==()
bool open_spiel::matrix_game::MatrixGame::operator== (const Game & other_game) const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 148 of file matrix_game.h.
{
    const auto& other = down_cast<const MatrixGame&>(other_game);
    return (row_action_names_.size() == other.row_action_names_.size() &&
            col_action_names_.size() == other.col_action_names_.size() &&
            row_utilities_ == other.row_utilities_ &&
            col_utilities_ == other.col_utilities_);
  }
References open_spiel::down_cast().
PlayerUtilities()
const std::vector< double > & open_spiel::matrix_game::MatrixGame::PlayerUtilities (const Player player) const inline
Definition at line 125 of file matrix_game.h.
{
    SPIEL_CHECK_TRUE(player == Player{0} || player == Player{1});
    return (player == Player{0} ? row_utilities_ : col_utilities_);
  }
References SPIEL_CHECK_TRUE.
PlayerUtility()
double open_spiel::matrix_game::MatrixGame::PlayerUtility (Player player, int row, int col) const inline
Definition at line 118 of file matrix_game.h.
{
    SPIEL_CHECK_TRUE(player == Player{0} || player == Player{1});
    return (player == Player{0} ? row_utilities_[Index(row, col)]
                                : col_utilities_[Index(row, col)]);
  }
References SPIEL_CHECK_TRUE.
Referenced by GetUtility().
RowActionName()
const std::string & open_spiel::matrix_game::MatrixGame::RowActionName (int row) const inline
Definition at line 130 of file matrix_game.h.
{
    return row_action_names_[row];
  }
Referenced by open_spiel::matrix_game::MatrixState::ActionToString().
RowUtilities()
const std::vector< double > & open_spiel::matrix_game::MatrixGame::RowUtilities () const inline
Definition at line 123 of file matrix_game.h.
{ return row_utilities_; }
RowUtility()
double open_spiel::matrix_game::MatrixGame::RowUtility (int row, int col) const inline
Definition at line 112 of file matrix_game.h.
{
    return row_utilities_[Index(row, col)];
  }
Referenced by open_spiel::matrix_game::MatrixState::Returns(), and open_spiel::matrix_game::MatrixState::ToString().
UtilitySum()
absl::optional< double > open_spiel::matrix_game::MatrixGame::UtilitySum () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 213 of file matrix_game.cc.
{
  return GetUtilitySum(row_utilities_, col_utilities_);
}
The documentation for this class was generated from the following files:
open_spiel/matrix_game.h
open_spiel/matrix_game.cc