open spiel: open_spiel::nim::NimState Class Reference
open_spiel::nim::NimState Class Reference
#include <nim.h>
Public Member Functions
NimState (std::shared_ptr< const Game > game, int num_piles, std::vector< int > piles, bool is_misere, int max_num_per_pile)
NimState (const NimState &)=default
NimState & operator= (const NimState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action move) override
std::vector< Action > LegalActions () const override
Player outcome () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes
int num_piles_ = kDefaultNumPiles
std::vector< int > piles_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 44 of file nim.h.
Constructor & Destructor Documentation
NimState() [1/2]
open_spiel::nim::NimState::NimState (std::shared_ptr< const Game > game, int num_piles, std::vector< int > piles, bool is_misere, int max_num_per_pile) explicit
Definition at line 147 of file nim.cc.
    : State(game),
      num_piles_(num_piles),
      piles_(piles),
      is_misere_(is_misere),
      max_num_per_pile_(max_num_per_pile) {}
Referenced by Clone().
NimState() [2/2]
open_spiel::nim::NimState::NimState (const NimState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::nim::NimState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 141 of file nim.cc.
{
  std::pair<int, int> action = UnpackAction(action_id);
  int pile_idx = action.first, take = action.second;
  return absl::StrCat("pile:", pile_idx + 1, ", take:", take, ";");
}
References action, and absl::StrCat().
Clone()
std::unique_ptr< State > open_spiel::nim::NimState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 231 of file nim.cc.
{
  return std::unique_ptr<State>(new NimState(*this));
}
References NimState().
CurrentPlayer()
Player open_spiel::nim::NimState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 53 of file nim.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::nim::NimState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 111 of file nim.cc.
{
  SPIEL_CHECK_FALSE(IsTerminal());
  std::pair<int, int> action = UnpackAction(move);
  int pile_idx = action.first, take = action.second;
  SPIEL_CHECK_LT(pile_idx, piles_.size());
  SPIEL_CHECK_GT(take, 0);
  SPIEL_CHECK_LE(take, piles_[pile_idx]);
  piles_[pile_idx] -= take;
  if (IsEmpty()) {
    outcome_ = is_misere_ ? 1 - current_player_ : current_player_;
  }
  current_player_ = 1 - current_player_;
  num_moves_ += 1;
}
References action, IsTerminal(), piles_, SPIEL_CHECK_FALSE, SPIEL_CHECK_GT, SPIEL_CHECK_LE, and SPIEL_CHECK_LT.
InformationStateString()
std::string open_spiel::nim::NimState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 182 of file nim.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::nim::NimState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 168 of file nim.cc.
{
  return outcome_ != kInvalidPlayer || IsEmpty();
}
References open_spiel::kInvalidPlayer.
Referenced by CurrentPlayer(), DoApplyAction(), LegalActions(), and ObservationTensor().
LegalActions()
std::vector< Action > open_spiel::nim::NimState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 128 of file nim.cc.
{
  if (IsTerminal()) return {};
  std::vector<Action> moves;
  for (std::size_t pile_idx = 0; pile_idx < piles_.size(); pile_idx++) {
    // the player has to take at least one object from a pile
    for (int take = 1; take <= piles_[pile_idx]; take++) {
      moves.push_back((take - 1) * num_piles_ + (int)pile_idx);
    }
  }
  std::sort(moves.begin(), moves.end());
  return moves;
}
References IsTerminal(), num_piles_, and piles_.
ObservationString()
std::string open_spiel::nim::NimState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 188 of file nim.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::nim::NimState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 194 of file nim.cc.
{
  // [one-hot player] + [IsTerminal()] + [binary representation of num_piles] +
  // [binary representation of every pile]
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::fill(values.begin(), values.end(), 0);
  int offset = 0;
  values[current_player_] = 1;
  offset += 2;
  values[offset] = IsTerminal() ? 1 : 0;
  offset += 1;
  // num_piles (which is >= 1)
  values[offset + num_piles_ - 1] = 1;
  offset += num_piles_;
  for (std::size_t pile_idx = 0; pile_idx < piles_.size(); pile_idx++) {
    values[offset + piles_[pile_idx]] = 1;
    offset += max_num_per_pile_ + 1;
  }
  SPIEL_CHECK_EQ(offset, values.size());
}
References IsTerminal(), num_piles_, open_spiel::State::num_players_, piles_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
operator=()
NimState & open_spiel::nim::NimState::operator= (const NimState &) default
outcome()
Player open_spiel::nim::NimState::outcome () const inline
Definition at line 67 of file nim.h.
{ return outcome_; }
Referenced by open_spiel.python.examples.nego_nbs_example.Negotiation::__str__(), open_spiel.python.algorithms.mcts.SearchNode::puct_value(), open_spiel.python.algorithms.mcts.SearchNode::sort_key(), open_spiel.python.algorithms.mcts.SearchNode::to_str(), and open_spiel.python.algorithms.mcts.SearchNode::uct_value().
Returns()
std::vector< double > open_spiel::nim::NimState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 172 of file nim.cc.
{
  if (outcome_ == Player{0}) {
    return {1.0, -1.0};
  } else if (outcome_ == Player{1}) {
    return {-1.0, 1.0};
  } else {
    return {0.0, 0.0};
  }
}
ToString()
std::string open_spiel::nim::NimState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 156 of file nim.cc.
{
  std::string str;
  absl::StrAppend(&str, "(", current_player_, "): ");
  for (std::size_t pile_idx = 0; pile_idx < piles_.size(); pile_idx++) {
    absl::StrAppend(&str, piles_[pile_idx]);
    if (pile_idx != piles_.size() - 1) {
      absl::StrAppend(&str, " ");
    }
  }
  return str;
}
References piles_, and absl::StrAppend().
Referenced by ObservationString().
UndoAction()
void open_spiel::nim::NimState::UndoAction (Player player, Action move) override virtual
Reimplemented from open_spiel::State.
Definition at line 220 of file nim.cc.
{
  std::pair<int, int> action = UnpackAction(move);
  int pile_idx = action.first, take = action.second;
  piles_[pile_idx] += take;
  current_player_ = player;
  outcome_ = kInvalidPlayer;
  num_moves_ -= 1;
  history_.pop_back();
  --move_number_;
}
References action, open_spiel::State::history_, open_spiel::kInvalidPlayer, open_spiel::State::move_number_, piles_, and player.
Member Data Documentation
num_piles_
int open_spiel::nim::NimState::num_piles_ = kDefaultNumPiles protected
Definition at line 71 of file nim.h.
Referenced by LegalActions(), and ObservationTensor().
piles_
std::vector<int> open_spiel::nim::NimState::piles_ protected
Definition at line 72 of file nim.h.
Referenced by DoApplyAction(), LegalActions(), ObservationTensor(), ToString(), and UndoAction().
The documentation for this class was generated from the following files:
open_spiel/games/nim/nim.h
open_spiel/games/nim/nim.cc