open spiel: open_spiel::phantom_go::PhantomGoState Class Reference
open_spiel::phantom_go::PhantomGoState Class Reference
#include <phantom_go.h>
Public Member Functions
PhantomGoState (std::shared_ptr< const Game > game, int board_size, float komi, int handicap)
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::array< int, 2 > GetStoneCount () const
int GetMaxGameLenght () const
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::string ObservationString (int player) const override
void ObservationTensor (int player, absl::Span< float > values) const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
const PhantomGoBoard & board () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Static Public Member Functions
static bool equalMetaposition (const PhantomGoState &state1, const PhantomGoState &state2, int playerID)
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 76 of file phantom_go.h.
Constructor & Destructor Documentation
PhantomGoState()
open_spiel::phantom_go::PhantomGoState::PhantomGoState (std::shared_ptr< const Game > game, int board_size, float komi, int handicap)
Definition at line 161 of file phantom_go.cc.
    : State(std::move(game)),
      board_(board_size),
      komi_(komi),
      handicap_(handicap),
      max_game_length_(game_->MaxGameLength()),
      to_play_(GoColor::kBlack) {
  ResetBoard();
}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::phantom_go::PhantomGoState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 199 of file phantom_go.cc.
{
  return absl::StrCat(
      GoColorToString(static_cast<GoColor>(player)), " ",
      VirtualPointToString(board_.ActionToVirtualAction(action)));
}
References action, open_spiel::phantom_go::PhantomGoBoard::ActionToVirtualAction(), open_spiel::phantom_go::GoColorToString(), player, absl::StrCat(), and open_spiel::phantom_go::VirtualPointToString().
board()
const PhantomGoBoard & open_spiel::phantom_go::PhantomGoState::board () const inline
Definition at line 110 of file phantom_go.h.
{ return board_; }
Referenced by open_spiel.python.games.tic_tac_toe.TicTacToeState::__str__(), open_spiel.python.games.tic_tac_toe.TicTacToeState::_apply_action(), and open_spiel.python.games.tic_tac_toe.TicTacToeState::_legal_actions().
Clone()
std::unique_ptr< State > open_spiel::phantom_go::PhantomGoState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 266 of file phantom_go.cc.
{
  return std::unique_ptr<State>(new PhantomGoState(*this));
}
References PhantomGoState().
CurrentPlayer()
Player open_spiel::phantom_go::PhantomGoState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 82 of file phantom_go.h.
{
    return IsTerminal() ? kTerminalPlayerId : ColorToPlayer(to_play_);
  }
References open_spiel::phantom_go::ColorToPlayer(), IsTerminal(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::phantom_go::PhantomGoState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 281 of file phantom_go.cc.
{
  if (board_.PlayMove(board_.ActionToVirtualAction(action), to_play_)) {
    to_play_ = OppColor(to_play_);
    bool was_inserted = repetitions_.insert(board_.HashValue()).second;
    if (!was_inserted && action != board_.pass_action()) {
      // We have encountered this position before.
      superko_ = true;
    }
  }
}
References action, open_spiel::phantom_go::PhantomGoBoard::ActionToVirtualAction(), open_spiel::phantom_go::PhantomGoBoard::HashValue(), open_spiel::phantom_go::OppColor(), open_spiel::phantom_go::PhantomGoBoard::pass_action(), and open_spiel::phantom_go::PhantomGoBoard::PlayMove().
Referenced by UndoAction().
equalMetaposition()
bool open_spiel::phantom_go::PhantomGoState::equalMetaposition (const PhantomGoState & state1, const PhantomGoState & state2, int playerID) static
Definition at line 310 of file phantom_go.cc.
{
  if (state1.board_.board_size() != state2.board_.board_size()) {
    return false;
  }
  std::array<int, 2> stoneCount1 = state1.board_.GetStoneCount();
  std::array<int, 2> stoneCount2 = state2.board_.GetStoneCount();
  if (stoneCount1[0] != stoneCount2[0] || stoneCount1[1] != stoneCount2[1]) {
    return false;
  }
  int boardSize = state1.board_.board_size();
  auto observation1 = state1.board_.GetObservationByID(playerID);
  auto observation2 = state2.board_.GetObservationByID(playerID);
  for (int i = 0; i < boardSize * boardSize; i++) {
    if (observation1[i] != observation2[i]) {
      return false;
    }
  }
  if (state1.to_play_ != state2.to_play_) {
    return false;
  }
  return true;
}
References open_spiel::phantom_go::PhantomGoBoard::board_size(), open_spiel::phantom_go::PhantomGoBoard::GetObservationByID(), open_spiel::phantom_go::PhantomGoBoard::GetStoneCount(), and i.
GetMaxGameLenght()
int open_spiel::phantom_go::PhantomGoState::GetMaxGameLenght () const
Definition at line 341 of file phantom_go.cc.
{ return max_game_length_; }
GetStoneCount()
std::array< int, 2 > open_spiel::phantom_go::PhantomGoState::GetStoneCount () const
Definition at line 307 of file phantom_go.cc.
{
  return board_.GetStoneCount();
}
References open_spiel::phantom_go::PhantomGoBoard::GetStoneCount().
IsTerminal()
bool open_spiel::phantom_go::PhantomGoState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 231 of file phantom_go.cc.
{
  if (history_.size() < 2) return false;
  return (history_.size() >= max_game_length_) || superko_ ||
         (history_[history_.size() - 1].action == board_.pass_action() &&
          history_[history_.size() - 2].action == board_.pass_action());
}
References open_spiel::State::history_, and open_spiel::phantom_go::PhantomGoBoard::pass_action().
Referenced by CurrentPlayer(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::phantom_go::PhantomGoState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 187 of file phantom_go.cc.
{
  std::vector<Action> actions{};
  if (IsTerminal()) return actions;
  for (VirtualPoint p : BoardPoints(board_.board_size())) {
    if (board_.IsLegalMove(p, to_play_)) {
      actions.push_back(board_.VirtualActionToAction(p));
    }
  }
  actions.push_back(board_.pass_action());
  return actions;
}
References open_spiel::phantom_go::PhantomGoBoard::board_size(), open_spiel::phantom_go::BoardPoints(), open_spiel::phantom_go::PhantomGoBoard::IsLegalMove(), IsTerminal(), open_spiel::phantom_go::PhantomGoBoard::pass_action(), and open_spiel::phantom_go::PhantomGoBoard::VirtualActionToAction().
ObservationString()
std::string open_spiel::phantom_go::PhantomGoState::ObservationString (int player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 172 of file phantom_go.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return absl::StrCat(board_.ObservationToString(player),
                      board_.LastMoveInformationToString());
}
References open_spiel::phantom_go::PhantomGoBoard::LastMoveInformationToString(), open_spiel::State::num_players_, open_spiel::phantom_go::PhantomGoBoard::ObservationToString(), player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
ObservationTensor()
void open_spiel::phantom_go::PhantomGoState::ObservationTensor (int player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 179 of file phantom_go.cc.
{
  ContiguousAllocator allocator(values);
  const PhantomGoGame &game =
      open_spiel::down_cast<const PhantomGoGame &>(*game_);
  game.default_observer_->WriteTensor(*this, player, &allocator);
}
References open_spiel::down_cast(), open_spiel::State::game_, player, and values.
Returns()
std::vector< double > open_spiel::phantom_go::PhantomGoState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 238 of file phantom_go.cc.
{
  if (!IsTerminal()) return {0.0, 0.0};
  if (superko_) {
    // Superko rules (https://senseis.xmp.net/?Superko) are complex and vary
    // between rulesets.
    // For simplicity and because superkos are very rare, we just treat them as
    // a draw.
    return {DrawUtility(), DrawUtility()};
  }
  // Score with Tromp-Taylor.
  float black_score = TrompTaylorScore(board_, komi_, handicap_);
  std::vector<double> returns(phantom_go::NumPlayers());
  if (black_score > 0) {
    returns[ColorToPlayer(GoColor::kBlack)] = WinUtility();
    returns[ColorToPlayer(GoColor::kWhite)] = LossUtility();
  } else if (black_score < 0) {
    returns[ColorToPlayer(GoColor::kBlack)] = LossUtility();
    returns[ColorToPlayer(GoColor::kWhite)] = WinUtility();
  } else {
    returns[ColorToPlayer(GoColor::kBlack)] = DrawUtility();
    returns[ColorToPlayer(GoColor::kWhite)] = DrawUtility();
  }
  return returns;
}
References open_spiel::phantom_go::ColorToPlayer(), open_spiel::phantom_go::DrawUtility(), IsTerminal(), open_spiel::phantom_go::kBlack, open_spiel::phantom_go::kWhite, open_spiel::phantom_go::LossUtility(), open_spiel::phantom_go::NumPlayers(), open_spiel::phantom_go::TrompTaylorScore(), and open_spiel::phantom_go::WinUtility().
ToString()
std::string open_spiel::phantom_go::PhantomGoState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 221 of file phantom_go.cc.
{
  std::array<int, 2> stoneCount = board_.GetStoneCount();
  return absl::StrCat("GoState(komi=", komi_,
                      ", to_play=", GoColorToString(to_play_),
                      ", history.size()=", history_.size(), ", ",
                      "stones_count: w", stoneCount[1], " b", stoneCount[0],
                      ")\n", board_.ToString(), board_.ObservationsToString());
}
References open_spiel::phantom_go::PhantomGoBoard::GetStoneCount(), open_spiel::phantom_go::GoColorToString(), open_spiel::State::history_, open_spiel::phantom_go::PhantomGoBoard::ObservationsToString(), absl::StrCat(), and open_spiel::phantom_go::PhantomGoBoard::ToString().
UndoAction()
void open_spiel::phantom_go::PhantomGoState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 270 of file phantom_go.cc.
{
  // We don't have direct undo functionality, but copying the board and
  // replaying all actions is still pretty fast (> 1 million undos/second).
  history_.pop_back();
  --move_number_;
  ResetBoard();
  for (auto [_, action] : history_) {
    DoApplyAction(action);
  }
}
References action, DoApplyAction(), open_spiel::State::history_, and open_spiel::State::move_number_.
The documentation for this class was generated from the following files:
open_spiel/games/phantom_go/phantom_go.h
open_spiel/games/phantom_go/phantom_go.cc