open spiel: absl::strings_internal::SplitIterator< Splitter > Class Template Reference
absl::strings_internal::SplitIterator< Splitter > Class Template Reference
#include <str_split_internal.h>
Public Types
enum State { kInitState , kLastState , kEndState }
using iterator_category = std::input_iterator_tag
using value_type = absl::string_view
using difference_type = ptrdiff_t
using pointer = const value_type*
using reference = const value_type&
Public Member Functions
SplitIterator (State state, const Splitter *splitter)
bool at_end () const
reference operator* () const
pointer operator-> () const
SplitIterator & operator++ ()
SplitIterator operator++ (int)
Friends
bool operator== (const SplitIterator &a, const SplitIterator &b)
bool operator!= (const SplitIterator &a, const SplitIterator &b)
Detailed Description
template<typename Splitter>
class absl::strings_internal::SplitIterator< Splitter >
Definition at line 84 of file str_split_internal.h.
Member Typedef Documentation
difference_type
template<typename Splitter > using absl::strings_internal::SplitIterator< Splitter >::difference_type = ptrdiff_t
Definition at line 88 of file str_split_internal.h.
iterator_category
template<typename Splitter > using absl::strings_internal::SplitIterator< Splitter >::iterator_category = std::input_iterator_tag
Definition at line 86 of file str_split_internal.h.
pointer
template<typename Splitter > using absl::strings_internal::SplitIterator< Splitter >::pointer = const value_type*
Definition at line 89 of file str_split_internal.h.
reference
template<typename Splitter > using absl::strings_internal::SplitIterator< Splitter >::reference = const value_type&
Definition at line 90 of file str_split_internal.h.
value_type
template<typename Splitter > using absl::strings_internal::SplitIterator< Splitter >::value_type = absl::string_view
Definition at line 87 of file str_split_internal.h.
Member Enumeration Documentation
State
template<typename Splitter > enum absl::strings_internal::SplitIterator::State
Enumerator
kInitState
kLastState
kEndState
Definition at line 92 of file str_split_internal.h.
{ kInitState, kLastState, kEndState };
Constructor & Destructor Documentation
SplitIterator()
template<typename Splitter > absl::strings_internal::SplitIterator< Splitter >::SplitIterator (State state, const Splitter * splitter) inline
Definition at line 93 of file str_split_internal.h.
      : pos_(0),
        state_(state),
        splitter_(splitter),
        delimiter_(splitter->delimiter()),
        predicate_(splitter->predicate()) {
    // Hack to maintain backward compatibility. This one block makes it so an
    // empty absl::string_view whose .data() happens to be nullptr behaves
    // *differently* from an otherwise empty absl::string_view whose .data() is
    // not nullptr. This is an undesirable difference in general, but this
    // behavior is maintained to avoid breaking existing code that happens to
    // depend on this old behavior/bug. Perhaps it will be fixed one day. The
    // difference in behavior is as follows:
    //   Split(absl::string_view(""), '-');  // {""}
    //   Split(absl::string_view(), '-');    // {}
    if (splitter_->text().data() == nullptr) {
      state_ = kEndState;
      pos_ = splitter_->text().size();
      return;
    }
    if (state_ == kEndState) {
      pos_ = splitter_->text().size();
    } else {
      ++(*this);
    }
  }
References absl::string_view::data(), absl::strings_internal::SplitIterator< Splitter >::kEndState, absl::string_view::size(), and absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::text().
Member Function Documentation
at_end()
template<typename Splitter > bool absl::strings_internal::SplitIterator< Splitter >::at_end () const inline
Definition at line 121 of file str_split_internal.h.
{ return state_ == kEndState; }
References absl::strings_internal::SplitIterator< Splitter >::kEndState.
operator*()
template<typename Splitter > reference absl::strings_internal::SplitIterator< Splitter >::operator* () const inline
Definition at line 123 of file str_split_internal.h.
{ return curr_; }
operator++() [1/2]
template<typename Splitter > SplitIterator & absl::strings_internal::SplitIterator< Splitter >::operator++ () inline
Definition at line 126 of file str_split_internal.h.
{
    do {
      if (state_ == kLastState) {
        state_ = kEndState;
        return *this;
      }
      const absl::string_view text = splitter_->text();
      const absl::string_view d = delimiter_.Find(text, pos_);
      if (d.data() == text.data() + text.size()) state_ = kLastState;
      curr_ = text.substr(pos_,
                          static_cast<size_t>(d.data() - (text.data() + pos_)));
      pos_ += curr_.size() + d.size();
    } while (!predicate_(curr_));
    return *this;
  }
References absl::d, absl::strings_internal::SplitIterator< Splitter >::kEndState, absl::strings_internal::SplitIterator< Splitter >::kLastState, absl::string_view::size(), absl::string_view::substr(), and absl::strings_internal::Splitter< Delimiter, Predicate, StringType >::text().
operator++() [2/2]
template<typename Splitter > SplitIterator absl::strings_internal::SplitIterator< Splitter >::operator++ (int) inline
Definition at line 142 of file str_split_internal.h.
{
    SplitIterator old(*this);
    ++(*this);
    return old;
  }
operator->()
template<typename Splitter > pointer absl::strings_internal::SplitIterator< Splitter >::operator-> () const inline
Definition at line 124 of file str_split_internal.h.
{ return &curr_; }
Friends And Related Symbol Documentation
operator!=
template<typename Splitter > bool operator!= (const SplitIterator< Splitter > & a, const SplitIterator< Splitter > & b) friend
Definition at line 152 of file str_split_internal.h.
{
    return !(a == b);
  }
operator==
template<typename Splitter > bool operator== (const SplitIterator< Splitter > & a, const SplitIterator< Splitter > & b) friend
Definition at line 148 of file str_split_internal.h.
{
    return a.state_ == b.state_ && a.pos_ == b.pos_;
  }
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/str_split_internal.h