open spiel: open_spiel::lewis_signaling::LewisSignalingGame Class Reference
open_spiel::lewis_signaling::LewisSignalingGame Class Reference
#include <lewis_signaling.h>
Public Member Functions
LewisSignalingGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
int NumPlayers () const override
double MaxUtility () const override
double MinUtility () const override
std::vector< int > ObservationTensorShape () const override
std::vector< int > InformationStateTensorShape () const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 96 of file lewis_signaling.h.
Constructor & Destructor Documentation
LewisSignalingGame()
open_spiel::lewis_signaling::LewisSignalingGame::LewisSignalingGame (const GameParameters & params) explicit
Definition at line 254 of file lewis_signaling.cc.
    : Game(kGameType, params),
      num_states_(ParameterValue<int>("num_states", kDefaultNumStates)),
      num_messages_(ParameterValue<int>("num_messages", kDefaultNumMessages)) {
  std::string payoffs_string =
      ParameterValue<std::string>("payoffs", kDefaultPayoffs);
  std::vector<std::string> parts = absl::StrSplit(payoffs_string, ',');
  SPIEL_CHECK_EQ(parts.size(), num_states_ * num_states_);
  payoffs_.resize(parts.size());
  for (int i = 0; i < parts.size(); ++i) {
    bool success = absl::SimpleAtod(parts[i], &payoffs_[i]);
    SPIEL_CHECK_TRUE(success);
  }
  SPIEL_CHECK_LE(num_messages_, num_states_);
}
References i, open_spiel::lewis_signaling::kDefaultPayoffs, open_spiel::Game::ParameterValue(), absl::SimpleAtod(), SPIEL_CHECK_EQ, SPIEL_CHECK_LE, SPIEL_CHECK_TRUE, and absl::StrSplit().
Member Function Documentation
InformationStateTensorShape()
std::vector< int > open_spiel::lewis_signaling::LewisSignalingGame::InformationStateTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 119 of file lewis_signaling.h.
{
    return ObservationTensorShape();
  }
References ObservationTensorShape().
MaxChanceNodesInHistory()
int open_spiel::lewis_signaling::LewisSignalingGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 109 of file lewis_signaling.h.
{ return MaxGameLength(); }
References MaxGameLength().
MaxChanceOutcomes()
int open_spiel::lewis_signaling::LewisSignalingGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 105 of file lewis_signaling.h.
{ return num_states_; }
MaxGameLength()
int open_spiel::lewis_signaling::LewisSignalingGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 107 of file lewis_signaling.h.
{ return 2; }
Referenced by MaxChanceNodesInHistory().
MaxUtility()
double open_spiel::lewis_signaling::LewisSignalingGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 112 of file lewis_signaling.h.
{
    return *std::max_element(payoffs_.begin(), payoffs_.end());
  }
MinUtility()
double open_spiel::lewis_signaling::LewisSignalingGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 115 of file lewis_signaling.h.
{
    return *std::min_element(payoffs_.begin(), payoffs_.end());
  }
NewInitialState()
std::unique_ptr< State > open_spiel::lewis_signaling::LewisSignalingGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 101 of file lewis_signaling.h.
{
    return std::unique_ptr<State>(new LewisSignalingState(
        shared_from_this(), num_states_, num_messages_, payoffs_));
  }
NumDistinctActions()
int open_spiel::lewis_signaling::LewisSignalingGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 270 of file lewis_signaling.cc.
{ return num_states_; }
NumPlayers()
int open_spiel::lewis_signaling::LewisSignalingGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 111 of file lewis_signaling.h.
{ return kDefaultNumPlayers; }
References open_spiel::lewis_signaling::kDefaultNumPlayers.
ObservationTensorShape()
std::vector< int > open_spiel::lewis_signaling::LewisSignalingGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 272 of file lewis_signaling.cc.
{
  return {
      2 +          // one hot vector for whose turn it is
      1 +          // one bit to indicate whether the state is terminal
      num_states_  // one-hot vector for the state/message depending on the
                   // player
  };
}
Referenced by InformationStateTensorShape().
The documentation for this class was generated from the following files:
open_spiel/games/lewis_signaling/lewis_signaling.h
open_spiel/games/lewis_signaling/lewis_signaling.cc