open spiel: open_spiel.python.algorithms.rnad.rnad.RNaDSolver Class Reference
open_spiel.python.algorithms.rnad.rnad.RNaDSolver Class Reference
Public Member Functions
__init__ (self, RNaDConfig config)
init (self)
float loss (self, Params params, Params params_target, Params params_prev, Params params_prev_, TimeStep ts, float alpha, int learner_steps)
update_parameters (self, Params params, Params params_target, Params params_prev, Params params_prev_, Optimizer optimizer, Optimizer optimizer_target, TimeStep timestep, float alpha, int learner_steps, bool update_target_net)
__getstate__ (self)
__setstate__ (self, state)
step (self)
action_probabilities (self, pyspiel.State state, Any player_id=None)
actor_step (self, EnvStep env_step)
TimeStep collect_batch_trajectory (self)
Public Attributes
config
learner_steps
actor_steps
network
params
params_target
params_prev
params_prev_
optimizer
optimizer_target
Protected Member Functions
chex.PRNGKey _next_rng_key (self)
EnvStep _state_as_env_step (self, pyspiel.State state)
chex.Array _network_jit_apply_and_post_process (self, Params params, EnvStep env_step)
chex.Array _network_jit_apply (self, Params params, EnvStep env_step)
EnvStep _batch_of_states_as_env_step (self, Sequence[pyspiel.State] states)
State 마다 EnvStep 을 만들고 EnvStep 들을 하나의 EnvStep 으로 합친다.
Sequence[pyspiel.State] _batch_of_states_apply_action (self, Sequence[pyspiel.State] states, chex.Array actions)
pyspiel.State _play_chance (self, pyspiel.State state)
Protected Attributes
_rngkey
_np_rng
_game
_ex_state
_entropy_schedule
_loss_and_grad
Detailed Description
Implements a solver for the R-NaD Algorithm.
See https://arxiv.org/abs/2206.15378.
Define all networks. Derive losses & learning steps. Initialize the game
state and algorithmic variables.
Definition at line 716 of file rnad.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__init__ (self, RNaDConfig config)
Definition at line 725 of file rnad.py.
  def __init__(self, config: RNaDConfig):
    self.config = config
    # Learner and actor step counters.
    self.learner_steps = 0
    self.actor_steps = 0
    self.init()
Member Function Documentation
__getstate__()
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__ (self)
To serialize the agent.
Definition at line 905 of file rnad.py.
  def __getstate__(self):
    """To serialize the agent."""
    return dict(
        # RNaD config.
        config=self.config,
        # Learner and actor step counters.
        learner_steps=self.learner_steps,
        actor_steps=self.actor_steps,
        # The randomness keys.
        np_rng=self._np_rng.get_state(),
        rngkey=self._rngkey,
        # Network params.
        params=self.params,
        params_target=self.params_target,
        params_prev=self.params_prev,
        params_prev_=self.params_prev_,
        # Optimizer state.
        optimizer=self.optimizer.state,  # pytype: disable=attribute-error  # always-use-return-annotations
        optimizer_target=self.optimizer_target.state,  # pytype: disable=attribute-error  # always-use-return-annotations
    )
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._np_rng, open_spiel.python.algorithms.rnad.rnad.RNaDSolver._rngkey, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_steps, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.config, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.learner_steps, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer_target, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_prev, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_prev_, and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_target.
__setstate__()
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__ (self, state)
To deserialize the agent.
Definition at line 929 of file rnad.py.
  def __setstate__(self, state):
    """To deserialize the agent."""
    # RNaD config.
    self.config = state["config"]
    self.init()
    # Learner and actor step counters.
    self.learner_steps = state["learner_steps"]
    self.actor_steps = state["actor_steps"]
    # The randomness keys.
    self._np_rng.set_state(state["np_rng"])
    self._rngkey = state["rngkey"]
    # Network params.
    self.params = state["params"]
    self.params_target = state["params_target"]
    self.params_prev = state["params_prev"]
    self.params_prev_ = state["params_prev_"]
    # Optimizer state.
    self.optimizer.state = state["optimizer"]
    self.optimizer_target.state = state["optimizer_target"]
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._np_rng, open_spiel.python.algorithms.rnad.rnad.RNaDSolver._rngkey, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_steps, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.config, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.init(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.learner_steps, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer_target, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_prev, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_prev_, and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_target.
_batch_of_states_apply_action()
Sequence[pyspiel.State] open_spiel.python.algorithms.rnad.rnad.RNaDSolver._batch_of_states_apply_action (self, Sequence[pyspiel.State] states, chex.Array actions) protected
Apply a batch of `actions` to a parallel list of `states`.
Definition at line 1100 of file rnad.py.
      actions: chex.Array) -> Sequence[pyspiel.State]:
    """Apply a batch of `actions` to a parallel list of `states`."""
    for state, action in zip(states, list(actions)):
      if not state.is_terminal():
        self.actor_steps += 1
        state.apply_action(action)
        self._play_chance(state)
    return states
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._play_chance(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_steps.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.collect_batch_trajectory().
_batch_of_states_as_env_step()
EnvStep open_spiel.python.algorithms.rnad.rnad.RNaDSolver._batch_of_states_as_env_step (self, Sequence[pyspiel.State] states) protected
State 마다 EnvStep 을 만들고 EnvStep 들을 하나의 EnvStep 으로 합친다.
Definition at line 1092 of file rnad.py.
                                   states: Sequence[pyspiel.State]) -> EnvStep:
    envs = [self._state_as_env_step(state) for state in states]
    #[1,2,3] [4,5,6] 을 [[1,2,3,],[4,5,6]] 으로 쌓아 올린다.
    #여기서는 EnvStep 을 쌓아 올린거
    return jax.tree_util.tree_map(lambda *e: np.stack(e, axis=0), *envs)
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._state_as_env_step().
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.action_probabilities(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.collect_batch_trajectory().
_network_jit_apply()
chex.Array open_spiel.python.algorithms.rnad.rnad.RNaDSolver._network_jit_apply (self, Params params, EnvStep env_step) protected
Definition at line 1041 of file rnad.py.
  def _network_jit_apply(self, params: Params, env_step: EnvStep) -> chex.Array:
    pi, _, _, _ = self.network.apply(params, env_step)
    return pi
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver.network.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_step().
_network_jit_apply_and_post_process()
chex.Array open_spiel.python.algorithms.rnad.rnad.RNaDSolver._network_jit_apply_and_post_process (self, Params params, EnvStep env_step) protected
Definition at line 1034 of file rnad.py.
      self, params: Params, env_step: EnvStep) -> chex.Array:
    pi, _, _, _ = self.network.apply(params, env_step)
    pi = self.config.finetune.post_process_policy(pi, env_step.legal)
    return pi
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver.config, and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.network.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.action_probabilities().
_next_rng_key()
chex.PRNGKey open_spiel.python.algorithms.rnad.rnad.RNaDSolver._next_rng_key (self) protected
Get the next rng subkey from class rngkey.
Must *not* be called from under a jitted function!
Returns:
  A fresh rng_key.
Definition at line 977 of file rnad.py.
  def _next_rng_key(self) -> chex.PRNGKey:
    """Get the next rng subkey from class rngkey.
    Must *not* be called from under a jitted function!
    Returns:
      A fresh rng_key.
    """
    self._rngkey, subkey = jax.random.split(self._rngkey)
    return subkey
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._rngkey.
_play_chance()
pyspiel.State open_spiel.python.algorithms.rnad.rnad.RNaDSolver._play_chance (self, pyspiel.State state) protected
Plays the chance nodes until we end up at another type of node.
Args:
  state: to be updated until it does not correspond to a chance node.
Returns:
  The same input state object, but updated. The state is returned
  only for convenience, to allow chaining function calls.
Definition at line 1111 of file rnad.py.
  def _play_chance(self, state: pyspiel.State) -> pyspiel.State:
    """Plays the chance nodes until we end up at another type of node.
    Args:
      state: to be updated until it does not correspond to a chance node.
    Returns:
      The same input state object, but updated. The state is returned
      only for convenience, to allow chaining function calls.
    """
    while state.is_chance_node():
      chance_outcome, chance_proba = zip(*state.chance_outcomes())
      action = self._np_rng.choice(chance_outcome, p=chance_proba)
      state.apply_action(action)
    return state
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._np_rng.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver._batch_of_states_apply_action(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.collect_batch_trajectory().
_state_as_env_step()
EnvStep open_spiel.python.algorithms.rnad.rnad.RNaDSolver._state_as_env_step (self, pyspiel.State state) protected
Definition at line 989 of file rnad.py.
  def _state_as_env_step(self, state: pyspiel.State) -> EnvStep:
    # A terminal state must be communicated to players, however since
    # it's a terminal state things like the state_representation or
    # the set of legal actions are meaningless and only needed
    # for the sake of creating well a defined trajectory tensor.
    # Therefore the code below:
    # - extracts the rewards
    # - if the state is terminal, uses a dummy other state for other fields.
    rewards = np.array(state.returns(), dtype=np.float64)
    valid = not state.is_terminal()
    if not valid:
      state = self._ex_state
    if self.config.state_representation == StateRepresentation.OBSERVATION:
      obs = state.observation_tensor()
    elif self.config.state_representation == StateRepresentation.INFO_SET:
      obs = state.information_state_tensor()
    else:
      raise ValueError(
          f"Invalid StateRepresentation: {self.config.state_representation}.")
    # TODO(author16): clarify the story around rewards and valid.
    return EnvStep(
        obs=np.array(obs, dtype=np.float64),
        legal=np.array(state.legal_actions_mask(), dtype=np.int8),
        player_id=np.array(state.current_player(), dtype=np.float64),
        valid=np.array(valid, dtype=np.float64),
        rewards=rewards)
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._ex_state, and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.config.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver._batch_of_states_as_env_step().
action_probabilities()
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.action_probabilities (self, pyspiel.State state, Any player_id = None)
Returns action probabilities dict for a single batch.
Definition at line 1019 of file rnad.py.
                           player_id: Any = None):
    """Returns action probabilities dict for a single batch."""
    env_step = self._batch_of_states_as_env_step([state])
    probs = self._network_jit_apply_and_post_process(
        self.params_target, env_step)
    probs = jax.device_get(probs[0])  # Squeeze out the 1-element batch.
    return {
        action: probs[action]
        for action, valid in enumerate(jax.device_get(env_step.legal[0]))
        if valid
    }
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._batch_of_states_as_env_step(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver._network_jit_apply_and_post_process(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_target.
Referenced by open_spiel.python.policy.Policy.__call__(), and open_spiel.python.policy.Policy.to_tabular().
actor_step()
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_step (self, EnvStep env_step)
Definition at line 1045 of file rnad.py.
  def actor_step(self, env_step: EnvStep):
    pi = self._network_jit_apply(self.params, env_step)
    pi = np.asarray(pi).astype("float64")
    # TODO(author18): is this policy normalization really needed?
    pi = pi / np.sum(pi, axis=-1, keepdims=True)
    action = np.apply_along_axis(
        lambda x: self._np_rng.choice(range(pi.shape[1]), p=x), axis=-1, arr=pi)
    # TODO(author16): reapply the legal actions mask to bullet-proof sampling.
    action_oh = np.zeros(pi.shape, dtype="float64")
    action_oh[range(pi.shape[0]), action] = 1.0
    actor_step = ActorStep(policy=pi, action_oh=action_oh, rewards=())  # pytype: disable=wrong-arg-types  # numpy-scalars
    return action, actor_step
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._network_jit_apply(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver._np_rng, and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.collect_batch_trajectory().
collect_batch_trajectory()
TimeStep open_spiel.python.algorithms.rnad.rnad.RNaDSolver.collect_batch_trajectory (self)
Definition at line 1061 of file rnad.py.
  def collect_batch_trajectory(self) -> TimeStep:
    # 초기화하고 챈스상태 넘긴 상태를 배치사이즈 만큼 리스트로 만든다.
    states = [
        self._play_chance(self._game.new_initial_state())
        for _ in range(self.config.batch_size)
    ]
    timesteps = [] # 환경요소, 액터 선택,결과 담긴 timestep 준비
    # states 를 하나의 EnvStep(EnvStep 으로 이루어진 리스트) 으로 만든다.
    # EnvStep 의 리스트라고 해도 EnvStep 형으로 받아들이나 보다.
    env_step = self._batch_of_states_as_env_step(states)
    for _ in range(self.config.trajectory_max):
      prev_env_step = env_step
      a, actor_step = self.actor_step(env_step) # 현 상태에 맞는 액션 연산
      states = self._batch_of_states_apply_action(states, a) # 액션을 상태에 적용. 상태 전환.
      env_step = self._batch_of_states_as_env_step(states) # 결과 state 를 다시 envstep 으로 만듬
      timesteps.append(
          TimeStep(
              env=prev_env_step,
              actor=ActorStep(
                  action_oh=actor_step.action_oh,
                  policy=actor_step.policy,
                  rewards=env_step.rewards),
          )) # 결과물들 저장
    # Concatenate all the timesteps together to form a single rollout [T, B, ..]
    return jax.tree_util.tree_map(lambda *xs: np.stack(xs, axis=0), *timesteps)
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._batch_of_states_apply_action(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver._batch_of_states_as_env_step(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver._game, open_spiel.python.rl_environment.Environment._game, open_spiel.python.algorithms.rnad.rnad.RNaDSolver._play_chance(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_step(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.config.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step().
init()
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.init (self)
Initialize the network and losses.
Definition at line 734 of file rnad.py.
  def init(self):
    """Initialize the network and losses."""
    # The random facilities for jax and numpy.
    self._rngkey = jax.random.PRNGKey(self.config.seed)
    self._np_rng = np.random.RandomState(self.config.seed)
    # TODO(author16): serialize both above to get the fully deterministic behaviour.
    # Create a game and an example of a state.
    # 0. 게임 생성
    self._game = pyspiel.load_game(self.config.game_name)
    self._ex_state = self._play_chance(self._game.new_initial_state())
    # The network.
    def network(
        env_step: EnvStep
    ) -> Tuple[chex.Array, chex.Array, chex.Array, chex.Array]:
      # 1. 본체 몸통 망을 만들고
      mlp_torso = hk.nets.MLP(
          self.config.policy_network_layers, activate_final=True
      )
      # 2. 현재 obs 를 본체 몸통 망에 통과시키고
      torso = mlp_torso(env_step.obs)
      # 3. 액션 선택 정책 헤드를 만들고
      mlp_policy_head = hk.nets.MLP([self._game.num_distinct_actions()])
      # 4. 본체망 통과된 결과물을 헤드에 통과 시키고
      logit = mlp_policy_head(torso)
      # 5. 가치 정책 망 만들고
      mlp_policy_value = hk.nets.MLP([1])
      # 6. 본체망 통과된 결과물을 가치망에 통과시키고
      v = mlp_policy_value(torso)
      pi = _legal_policy(logit, env_step.legal)
      log_pi = legal_log_policy(logit, env_step.legal)
      return pi, v, log_pi, logit
    # 네트워크 생성
    self.network = hk.without_apply_rng(hk.transform(network))
    # The machinery related to updating parameters/learner.
    self._entropy_schedule = EntropySchedule(
        sizes=self.config.entropy_schedule_size,
        repeats=self.config.entropy_schedule_repeats)
    # def loss 함수 '값, 미분' 하는 함수 만든다.
    # 7. 손실 함수 생성
    self._loss_and_grad = jax.value_and_grad(self.loss, has_aux=False)
    # Create initial parameters.
    env_step = self._state_as_env_step(self._ex_state)
    key = self._next_rng_key()  # Make sure to use the same key for all.
    # 8. 하이쿠 순수 함수 초기화
    self.params = self.network.init(key, env_step)
    self.params_target = self.network.init(key, env_step)
    self.params_prev = self.network.init(key, env_step)
    self.params_prev_ = self.network.init(key, env_step)
    # Parameter optimizers.
    # 9. optimzer 생성
    self.optimizer = optax_optimizer(
        self.params,
        optax.chain(
            optax.scale_by_adam(eps_root=0.0, **self.config.adam,),
            optax.scale(-self.config.learning_rate),
            optax.clip(self.config.clip_gradient)
        )
    )
    self.optimizer_target = optax_optimizer(
        self.params_target, optax.sgd(self.config.target_network_avg))
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__().
loss()
float open_spiel.python.algorithms.rnad.rnad.RNaDSolver.loss (self, Params params, Params params_target, Params params_prev, Params params_prev_, TimeStep ts, float alpha, int learner_steps)
Definition at line 809 of file rnad.py.
           learner_steps: int) -> float:
    #self.network = transformed
    rollout = jax.vmap(self.network.apply, (None, 0), 0)
    pi, v, log_pi, logit = rollout(params, ts.env)
    policy_pprocessed = self.config.finetune(pi, ts.env.legal, learner_steps)
    _, v_target, _, _ = rollout(params_target, ts.env)
    _, _, log_pi_prev, _ = rollout(params_prev, ts.env)
    _, _, log_pi_prev_, _ = rollout(params_prev_, ts.env)
    # This line creates the reward transform log(pi(a|x)/pi_reg(a|x)).
    # For the stability reasons, reward changes smoothly between iterations.
    # The mixing between old and new reward transform is a convex combination
    # parametrised by alpha.
    log_policy_reg = log_pi - (alpha * log_pi_prev + (1 - alpha) * log_pi_prev_)
    v_target_list, has_played_list, v_trace_policy_target_list = [], [], []
    for player in range(self._game.num_players()):
      reward = ts.actor.rewards[:, :, player]  # [T, B, Player]
      v_target_, has_played, policy_target_ = v_trace(
          v_target,
          ts.env.valid,
          ts.env.player_id,
          ts.actor.policy,
          policy_pprocessed,
          log_policy_reg,
          _player_others(ts.env.player_id, ts.env.valid, player),
          ts.actor.action_oh,
          reward,
          player,
          lambda_=1.0,
          c=self.config.c_vtrace,
          rho=np.inf,
          eta=self.config.eta_reward_transform)
      v_target_list.append(v_target_)
      has_played_list.append(has_played)
      v_trace_policy_target_list.append(policy_target_)
    loss_v = get_loss_v([v] * self._game.num_players(), v_target_list,
                        has_played_list)
    is_vector = jnp.expand_dims(jnp.ones_like(ts.env.valid), axis=-1)
    importance_sampling_correction = [is_vector] * self._game.num_players()
    # Uses v-trace to define q-values for Nerd
    loss_nerd = get_loss_nerd(
        [logit] * self._game.num_players(), [pi] * self._game.num_players(),
        v_trace_policy_target_list,
        ts.env.valid,
        ts.env.player_id,
        ts.env.legal,
        importance_sampling_correction,
        clip=self.config.nerd.clip,
        threshold=self.config.nerd.beta)
    return loss_v + loss_nerd  # pytype: disable=bad-return-type  # numpy-scalars
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._game, open_spiel.python.rl_environment.Environment._game, open_spiel.python.algorithms.rnad.rnad._player_others(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.config, open_spiel.python.algorithms.rnad.rnad.get_loss_nerd(), open_spiel.python.algorithms.rnad.rnad.get_loss_v(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.network, and open_spiel.python.algorithms.rnad.rnad.v_trace().
step()
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step (self)
One step of the algorithm, that plays the game and improves params.
Definition at line 953 of file rnad.py.
  def step(self):
    """One step of the algorithm, that plays the game and improves params."""
    # 11. States 생성, 최대 게임기일이 만큼 루프돌며 액션적용 상태전환,
    # 기록을 만든 것.
    timestep = self.collect_batch_trajectory()
    # 2 네트워크 언제 업데이트 해야 할지. 학습 중 네트워크를 목표 네트워크로 옮기는 것.
    alpha, update_target_net = self._entropy_schedule(self.learner_steps)
    # 3
    (self.params, self.params_target, self.params_prev, self.params_prev_,
     self.optimizer, self.optimizer_target), logs = self.update_parameters(
         self.params, self.params_target, self.params_prev, self.params_prev_,
         self.optimizer, self.optimizer_target, timestep, alpha,
         self.learner_steps, update_target_net)
    self.learner_steps += 1
    logs.update({
        "actor_steps": self.actor_steps,
        "learner_steps": self.learner_steps,
    })
    return logs
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._entropy_schedule, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_steps, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.collect_batch_trajectory(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.learner_steps, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer_target, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_prev, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_prev_, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_target, and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.update_parameters().
update_parameters()
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.update_parameters (self, Params params, Params params_target, Params params_prev, Params params_prev_, Optimizer optimizer, Optimizer optimizer_target, TimeStep timestep, float alpha, int learner_steps, bool update_target_net)
A jitted pure-functional part of the `step`.
Definition at line 867 of file rnad.py.
      update_target_net: bool):
      # 손실함수 값, 미분값 구하기
    """A jitted pure-functional part of the `step`."""
    loss_val, grad = self._loss_and_grad(params, params_target, params_prev,
                                         params_prev_, timestep, alpha,
                                         learner_steps)
    # Update `params`` using the computed gradient.
    params = optimizer(params, grad)
    # Update `params_target` towards `params`.
    params_target = optimizer_target(
        params_target, tree.tree_map(lambda a, b: a - b, params_target, params))
    # Rolls forward the prev and prev_ params if update_target_net is 1.
    # pyformat: disable
    params_prev, params_prev_ = jax.lax.cond(
        update_target_net,
        lambda: (params_target, params_prev),
        lambda: (params_prev, params_prev_))
    # pyformat: enable
    logs = {
        "loss": loss_val,
    }
    return (params, params_target, params_prev, params_prev_, optimizer,
            optimizer_target), logs
References open_spiel.python.algorithms.rnad.rnad.RNaDSolver._loss_and_grad, open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer, and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer_target.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step().
Member Data Documentation
_entropy_schedule
open_spiel.python.algorithms.rnad.rnad.RNaDSolver._entropy_schedule protected
Definition at line 779 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step().
_ex_state
open_spiel.python.algorithms.rnad.rnad.RNaDSolver._ex_state protected
Definition at line 744 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver._state_as_env_step().
_game
open_spiel.python.algorithms.rnad.rnad.RNaDSolver._game protected
Definition at line 743 of file rnad.py.
Referenced by open_spiel.python.rl_environment.Environment.action_spec(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.collect_batch_trajectory(), open_spiel.python.rl_environment.Environment.game(), open_spiel.python.rl_environment.Environment.is_turn_based(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.loss(), open_spiel.python.rl_environment.Environment.max_game_length(), open_spiel.python.rl_environment.Environment.name(), open_spiel.python.rl_environment.Environment.num_players(), open_spiel.python.rl_environment.Environment.observation_spec(), open_spiel.python.rl_environment.Environment.reset(), and open_spiel.python.rl_environment.Environment.update_mfg_distribution().
_loss_and_grad
open_spiel.python.algorithms.rnad.rnad.RNaDSolver._loss_and_grad protected
Definition at line 785 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.update_parameters().
_np_rng
open_spiel.python.algorithms.rnad.rnad.RNaDSolver._np_rng protected
Definition at line 738 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver._play_chance(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_step().
_rngkey
open_spiel.python.algorithms.rnad.rnad.RNaDSolver._rngkey protected
Definition at line 737 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver._next_rng_key().
actor_steps
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_steps
Definition at line 730 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver._batch_of_states_apply_action(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step().
config
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.config
Definition at line 726 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver._network_jit_apply_and_post_process(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver._state_as_env_step(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.collect_batch_trajectory(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.loss().
learner_steps
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.learner_steps
Definition at line 729 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step().
network
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.network
Definition at line 776 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver._network_jit_apply(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver._network_jit_apply_and_post_process(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.loss().
optimizer
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer
Definition at line 798 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.update_parameters().
optimizer_target
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.optimizer_target
Definition at line 806 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.update_parameters().
params
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params
Definition at line 791 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.actor_step(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step().
params_prev
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_prev
Definition at line 793 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step().
params_prev_
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_prev_
Definition at line 794 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step().
params_target
open_spiel.python.algorithms.rnad.rnad.RNaDSolver.params_target
Definition at line 792 of file rnad.py.
Referenced by open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__getstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.__setstate__(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver.action_probabilities(), and open_spiel.python.algorithms.rnad.rnad.RNaDSolver.step().
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/rnad/rnad.py