open spiel: open_spiel::algorithms::CFRCurrentPolicy Class Reference
open_spiel::algorithms::CFRCurrentPolicy Class Reference
#include <cfr.h>
Public Member Functions
CFRCurrentPolicy (const CFRInfoStateValuesTable &info_states, std::shared_ptr< Policy > default_policy)
ActionsAndProbs GetStatePolicy (const State &state) const override
ActionsAndProbs GetStatePolicy (const State &state, Player player) const override
ActionsAndProbs GetStatePolicy (const std::string &info_state) const override
TabularPolicy AsTabular () const
Public Member Functions inherited from open_spiel::Policy
virtual ~Policy ()=default
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const State &state) const
virtual std::pair< std::vector< Action >, std::vector< double > > GetStatePolicyAsParallelVectors (const std::string &info_state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const State &state) const
virtual std::unordered_map< Action, double > GetStatePolicyAsMap (const std::string &info_state) const
virtual std::string Serialize (int double_precision=-1, std::string delimiter="<~>") const
Detailed Description
Definition at line 150 of file cfr.h.
Constructor & Destructor Documentation
CFRCurrentPolicy()
open_spiel::algorithms::CFRCurrentPolicy::CFRCurrentPolicy (const CFRInfoStateValuesTable & info_states, std::shared_ptr< Policy > default_policy)
Definition at line 138 of file cfr.cc.
    : info_states_(info_states), default_policy_(default_policy) {}
Member Function Documentation
AsTabular()
TabularPolicy open_spiel::algorithms::CFRCurrentPolicy::AsTabular () const
Definition at line 182 of file cfr.cc.
{
  TabularPolicy policy;
  for (const auto& infoset_and_entry : info_states_) {
    policy.SetStatePolicy(infoset_and_entry.first,
                          infoset_and_entry.second.GetCurrentPolicy());
  }
  return policy;
}
References open_spiel::TabularPolicy::SetStatePolicy().
GetStatePolicy() [1/3]
ActionsAndProbs open_spiel::algorithms::CFRCurrentPolicy::GetStatePolicy (const State & state) const inline override virtual
Reimplemented from open_spiel::Policy.
Reimplemented in open_spiel::algorithms::ExplorativeSamplingPolicy, and open_spiel::algorithms::TargetedPolicy.
Definition at line 157 of file cfr.h.
{
    return GetStatePolicy(state, state.CurrentPlayer());
  };
References GetStatePolicy(), and state.
Referenced by GetStatePolicy(), open_spiel::algorithms::ExplorativeSamplingPolicy::GetStatePolicy(), and open_spiel::algorithms::TargetedPolicy::GetStatePolicy().
GetStatePolicy() [2/3]
ActionsAndProbs open_spiel::algorithms::CFRCurrentPolicy::GetStatePolicy (const State & state, Player player) const override virtual
Reimplemented from open_spiel::Policy.
Definition at line 142 of file cfr.cc.
{
  auto entry = info_states_.find(state.InformationStateString(player));
  if (entry == info_states_.end()) {
    if (default_policy_) {
      return default_policy_->GetStatePolicy(state, player);
    } else {
      SpielFatalError("No policy found, and no default policy.");
    }
  }
  ActionsAndProbs actions_and_probs;
  return GetStatePolicyFromInformationStateValues(entry->second,
                                                  actions_and_probs);
}
References actions_and_probs, player, open_spiel::SpielFatalError(), and state.
GetStatePolicy() [3/3]
ActionsAndProbs open_spiel::algorithms::CFRCurrentPolicy::GetStatePolicy (const std::string & info_state) const override virtual
Reimplemented from open_spiel::Policy.
Reimplemented in open_spiel::algorithms::ExplorativeSamplingPolicy.
Definition at line 157 of file cfr.cc.
{
  auto entry = info_states_.find(info_state);
  if (entry == info_states_.end()) {
    if (default_policy_) {
      return default_policy_->GetStatePolicy(info_state);
    } else {
      SpielFatalError("No policy found, and no default policy.");
    }
  }
  ActionsAndProbs actions_and_probs;
  GetStatePolicyFromInformationStateValues(entry->second, actions_and_probs);
  return actions_and_probs;
}
References actions_and_probs, and open_spiel::SpielFatalError().
The documentation for this class was generated from the following files:
open_spiel/algorithms/cfr.h
open_spiel/algorithms/cfr.cc