open spiel: open_spiel::go::GoGame Class Reference
open_spiel::go::GoGame Class Reference
#include <go.h>
Public Member Functions
GoGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
std::vector< int > ObservationTensorShape () const override
TensorLayout ObservationTensorLayout () const override
int NumPlayers () const override
double MinUtility () const override
absl::optional< double > UtilitySum () const override
double MaxUtility () const override
int MaxGameLength () const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
virtual int MaxChanceOutcomes () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 127 of file go.h.
Constructor & Destructor Documentation
GoGame()
open_spiel::go::GoGame::GoGame (const GameParameters & params) explicit
Definition at line 235 of file go.cc.
    : Game(kGameType, params),
      komi_(ParameterValue<double>("komi")),
      board_size_(ParameterValue<int>("board_size")),
      handicap_(ParameterValue<int>("handicap")),
      max_game_length_(ParameterValue<int>(
          "max_game_length", DefaultMaxGameLength(board_size_))) {}
Member Function Documentation
MaxGameLength()
int open_spiel::go::GoGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 158 of file go.h.
{ return max_game_length_; }
MaxUtility()
double open_spiel::go::GoGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 156 of file go.h.
{ return WinUtility(); }
References open_spiel::go::WinUtility().
MinUtility()
double open_spiel::go::GoGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 152 of file go.h.
{ return LossUtility(); }
References open_spiel::go::LossUtility().
NewInitialState()
std::unique_ptr< State > open_spiel::go::GoGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 135 of file go.h.
{
    return std::unique_ptr<State>(
        new GoState(shared_from_this(), board_size_, komi_, handicap_));
  }
NumDistinctActions()
int open_spiel::go::GoGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 131 of file go.h.
{
    return go::NumDistinctActions(board_size_);
  }
References open_spiel::go::NumDistinctActions().
NumPlayers()
int open_spiel::go::GoGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 150 of file go.h.
{ return go::NumPlayers(); }
References open_spiel::go::NumPlayers().
ObservationTensorLayout()
TensorLayout open_spiel::go::GoGame::ObservationTensorLayout () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 146 of file go.h.
{
    return TensorLayout::kCHW;
  }
References open_spiel::kCHW.
ObservationTensorShape()
std::vector< int > open_spiel::go::GoGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 140 of file go.h.
{
    // Planes: black, white, empty, and a bias plane indicating komi (whether
    // white is to play).
    return {CellStates() + 1, board_size_, board_size_};
  }
References open_spiel::go::CellStates().
UtilitySum()
absl::optional< double > open_spiel::go::GoGame::UtilitySum () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 153 of file go.h.
{
    return LossUtility() + WinUtility();
  }
References open_spiel::go::LossUtility(), and open_spiel::go::WinUtility().
The documentation for this class was generated from the following files:
open_spiel/games/go/go.h
open_spiel/games/go/go.cc