open spiel: open_spiel::efg_game::EFGState Class Reference
open_spiel::efg_game::EFGState Class Reference
#include <efg_game.h>
Public Member Functions
EFGState (std::shared_ptr< const Game > game, const Node *root)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
void UndoAction (Player player, Action action) override
std::vector< Action > LegalActions () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 83 of file efg_game.h.
Constructor & Destructor Documentation
EFGState()
open_spiel::efg_game::EFGState::EFGState (std::shared_ptr< const Game > game, const Node * root) explicit
Definition at line 97 of file efg_game.cc.
    : State(game), cur_node_(root) {}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::efg_game::EFGState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 113 of file efg_game.cc.
{
  int action_idx = ActionIdx(action);
  SPIEL_CHECK_GE(action_idx, 0);
  SPIEL_CHECK_LT(action_idx, cur_node_->actions.size());
  return cur_node_->actions[action_idx];
}
References action, open_spiel::efg_game::Node::actions, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::efg_game::EFGState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 230 of file efg_game.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  SPIEL_CHECK_TRUE(cur_node_->type == NodeType::kChance);
  std::vector<std::pair<Action, double>> outcomes(cur_node_->children.size());
  for (int i = 0; i < cur_node_->children.size(); ++i) {
    outcomes[i].first = cur_node_->action_ids[i];
    outcomes[i].second = cur_node_->probs[i];
  }
  return outcomes;
}
References open_spiel::efg_game::Node::action_ids, open_spiel::efg_game::Node::children, i, open_spiel::State::IsChanceNode(), open_spiel::efg_game::kChance, open_spiel::efg_game::Node::probs, SPIEL_CHECK_TRUE, and open_spiel::efg_game::Node::type.
Clone()
std::unique_ptr< State > open_spiel::efg_game::EFGState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 191 of file efg_game.cc.
{
  return std::unique_ptr<State>(new EFGState(*this));
}
References EFGState().
CurrentPlayer()
Player open_spiel::efg_game::EFGState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 100 of file efg_game.cc.
{
  if (cur_node_->type == NodeType::kChance) {
    return kChancePlayerId;
  } else if (cur_node_->type == NodeType::kTerminal) {
    return kTerminalPlayerId;
  } else {
    // Gambit player numbers are between 1 and num_players
    SPIEL_CHECK_GE(cur_node_->player_number, 1);
    SPIEL_CHECK_LE(cur_node_->player_number, num_players_);
    return cur_node_->player_number - 1;
  }
}
References open_spiel::efg_game::kChance, open_spiel::kChancePlayerId, open_spiel::efg_game::kTerminal, open_spiel::kTerminalPlayerId, open_spiel::State::num_players_, open_spiel::efg_game::Node::player_number, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and open_spiel::efg_game::Node::type.
DoApplyAction()
void open_spiel::efg_game::EFGState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 211 of file efg_game.cc.
{
  // Actions in these games are just indices into the legal actions.
  SPIEL_CHECK_FALSE(cur_node_->type == NodeType::kTerminal);
  SPIEL_CHECK_GE(action, 0);
  if (IsChanceNode()) {
    SPIEL_CHECK_LT(action, game_->MaxChanceOutcomes());
  } else {
    SPIEL_CHECK_LT(action, game_->NumDistinctActions());
  }
  int action_idx = ActionIdx(action);
  SPIEL_CHECK_NE(action_idx, -1);
  SPIEL_CHECK_FALSE(cur_node_->children[action_idx] == nullptr);
  cur_node_ = cur_node_->children[action_idx];
}
References action, open_spiel::efg_game::Node::children, open_spiel::State::game_, open_spiel::State::IsChanceNode(), open_spiel::efg_game::kTerminal, SPIEL_CHECK_FALSE, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_NE, and open_spiel::efg_game::Node::type.
InformationStateString()
std::string open_spiel::efg_game::EFGState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 137 of file efg_game.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // The information set number has to uniquely identify the infoset, whereas
  // the names are optional. But the numbers are unique per player, so must
  // add the player number.
  return EFGInformationStateString(cur_node_->player_number - 1, player,
                                   cur_node_->infoset_number,
                                   cur_node_->infoset_name);
}
References open_spiel::efg_game::Node::infoset_name, open_spiel::efg_game::Node::infoset_number, open_spiel::State::num_players_, player, open_spiel::efg_game::Node::player_number, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
InformationStateTensor()
void open_spiel::efg_game::EFGState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 148 of file efg_game.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::fill(values.begin(), values.end(), 0.0);
  int offset = 0;
  int index = 0;
  // Current player, or terminal.
  if (cur_node_->type == NodeType::kTerminal) {
    index = offset + num_players_;
  } else {
    index = offset + cur_node_->player_number - 1;
  }
  SPIEL_CHECK_GE(index, 0);
  SPIEL_CHECK_LT(index, values.size());
  values[index] = 1.0;
  offset += num_players_ + 1;
  // Observing player.
  index = offset + player;
  SPIEL_CHECK_GE(index, 0);
  SPIEL_CHECK_LT(index, values.size());
  values[index] = 1.0;
  offset += num_players_;
  // Infostate number.
  index = offset + cur_node_->infoset_number - 1;
  SPIEL_CHECK_GE(index, 0);
  SPIEL_CHECK_LT(index, values.size());
  values[index] = 1.0;
  offset += static_cast<const EFGGame*>(game_.get())->NumInfoStates(player);
  SPIEL_CHECK_LE(offset, values.size());
}
References open_spiel::State::game_, open_spiel::efg_game::Node::infoset_number, open_spiel::efg_game::kTerminal, open_spiel::State::num_players_, player, open_spiel::efg_game::Node::player_number, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, open_spiel::efg_game::Node::type, and values.
IsTerminal()
bool open_spiel::efg_game::EFGState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 124 of file efg_game.cc.
{
  return cur_node_->type == NodeType::kTerminal;
}
References open_spiel::efg_game::kTerminal, and open_spiel::efg_game::Node::type.
LegalActions()
std::vector< Action > open_spiel::efg_game::EFGState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 226 of file efg_game.cc.
{
  return cur_node_->action_ids;
}
References open_spiel::efg_game::Node::action_ids.
ObservationString()
std::string open_spiel::efg_game::EFGState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 184 of file efg_game.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return absl::StrCat(cur_node_->player_number - 1, "-", player, "-",
                      cur_node_->infoset_number, "-", cur_node_->infoset_name);
}
References open_spiel::efg_game::Node::infoset_name, open_spiel::efg_game::Node::infoset_number, open_spiel::State::num_players_, player, open_spiel::efg_game::Node::player_number, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
Returns()
std::vector< double > open_spiel::efg_game::EFGState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 128 of file efg_game.cc.
{
  if (cur_node_->type == NodeType::kTerminal) {
    SPIEL_CHECK_EQ(cur_node_->payoffs.size(), num_players_);
    return cur_node_->payoffs;
  } else {
    return std::vector<double>(num_players_, 0);
  }
}
References open_spiel::efg_game::kTerminal, open_spiel::State::num_players_, open_spiel::efg_game::Node::payoffs, SPIEL_CHECK_EQ, and open_spiel::efg_game::Node::type.
ToString()
std::string open_spiel::efg_game::EFGState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 120 of file efg_game.cc.
{
  return absl::StrCat(cur_node_->id, ": ", NodeToString(cur_node_));
}
References open_spiel::efg_game::Node::id, and absl::StrCat().
UndoAction()
void open_spiel::efg_game::EFGState::UndoAction (Player player, Action action) override virtual
Reimplemented from open_spiel::State.
Definition at line 195 of file efg_game.cc.
{
  SPIEL_CHECK_TRUE(cur_node_->parent != nullptr);
  cur_node_ = cur_node_->parent;
}
References open_spiel::efg_game::Node::parent, and SPIEL_CHECK_TRUE.
The documentation for this class was generated from the following files:
open_spiel/games/efg_game/efg_game.h
open_spiel/games/efg_game/efg_game.cc