open spiel: open_spiel::tarok::TarokState Class Reference
open_spiel::tarok::TarokState Class Reference
#include <tarok.h>
Public Member Functions
TarokState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const override
bool IsTerminal () const override
GamePhase CurrentGamePhase () const
std::vector< Action > PlayerCards (Player player) const
ContractName SelectedContractName () const
std::vector< Action > Talon () const
std::vector< std::vector< Action > > TalonSets () const
std::vector< Action > TrickCards () const
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string CardActionToString (Action action_id) const
ActionsAndProbs ChanceOutcomes () const override
std::vector< double > Returns () const override
std::vector< int > CapturedMondPenalties () const
std::vector< int > ScoresWithoutCapturedMondPenalties () const
std::string InformationStateString (Player player) const override
std::string ToString () const override
std::string Serialize () const override
std::unique_ptr< State > Clone () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
virtual std::string ObservationString (Player player) const
std::string ObservationString () const
virtual void ObservationTensor (Player player, absl::Span< float > values) const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Friends
class TarokGame
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 89 of file tarok.h.
Constructor & Destructor Documentation
TarokState()
open_spiel::tarok::TarokState::TarokState (std::shared_ptr< const Game > game) explicit
Definition at line 131 of file tarok.cc.
    : State(game),
      tarok_parent_game_(std::static_pointer_cast<const TarokGame>(game)) {
  players_bids_.reserve(num_players_);
  players_bids_.insert(players_bids_.end(), num_players_, kInvalidBidAction);
  players_collected_cards_.reserve(num_players_);
  players_collected_cards_.insert(players_collected_cards_.end(), num_players_,
                                  std::vector<Action>());
  players_info_states_.reserve(num_players_);
  players_info_states_.insert(players_info_states_.end(), num_players_, "");
}
References open_spiel::tarok::kInvalidBidAction, and open_spiel::State::num_players_.
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::tarok::TarokState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 427 of file tarok.cc.
{
  switch (current_game_phase_) {
    case GamePhase::kCardDealing:
      // return a dummy action due to implicit stochasticity
      return "Deal";
    case GamePhase::kBidding:
      if (action_id == 0) return "Pass";
      return ContractNameToString(
          tarok_parent_game_->contracts_.at(action_id - 1).name);
    case GamePhase::kKingCalling:
    case GamePhase::kTricksPlaying:
      return CardActionToString(action_id);
    case GamePhase::kTalonExchange:
      if (talon_.size() == 6) return absl::StrCat("Talon set ", action_id + 1);
      return CardActionToString(action_id);
    case GamePhase::kFinished:
      return "";
  }
}
References CardActionToString(), open_spiel::tarok::ContractNameToString(), open_spiel::tarok::kBidding, open_spiel::tarok::kCardDealing, open_spiel::tarok::kFinished, open_spiel::tarok::kKingCalling, open_spiel::tarok::kTalonExchange, open_spiel::tarok::kTricksPlaying, and absl::StrCat().
CapturedMondPenalties()
std::vector< int > open_spiel::tarok::TarokState::CapturedMondPenalties () const
Definition at line 755 of file tarok.cc.
{
  std::vector<int> penalties(num_players_, 0);
  if (captured_mond_player_ != kInvalidPlayer)
    penalties.at(captured_mond_player_) = -20;
  return penalties;
}
References open_spiel::kInvalidPlayer, and open_spiel::State::num_players_.
Referenced by open_spiel::init_pyspiel_games_tarok(), and Returns().
CardActionToString()
std::string open_spiel::tarok::TarokState::CardActionToString (Action action_id) const
Definition at line 447 of file tarok.cc.
{
  return ActionToCard(action_id).ToString();
}
References open_spiel::tarok::Card::ToString().
Referenced by ActionToString(), and open_spiel::init_pyspiel_games_tarok().
ChanceOutcomes()
ActionsAndProbs open_spiel::tarok::TarokState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 451 of file tarok.cc.
{
  if (current_game_phase_ == GamePhase::kCardDealing) {
    // return a dummy action with probability 1 due to implicit stochasticity
    return {{0, 1.0}};
  }
  return {};
}
References open_spiel::tarok::kCardDealing.
Clone()
std::unique_ptr< State > open_spiel::tarok::TarokState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 980 of file tarok.cc.
{
  return std::unique_ptr<State>(new TarokState(*this));
}
References TarokState().
CurrentGamePhase()
GamePhase open_spiel::tarok::TarokState::CurrentGamePhase () const
Definition at line 158 of file tarok.cc.
{ return current_game_phase_; }
Referenced by open_spiel::init_pyspiel_games_tarok(), and ToString().
CurrentPlayer()
Player open_spiel::tarok::TarokState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 143 of file tarok.cc.
{
  switch (current_game_phase_) {
    case GamePhase::kCardDealing:
      return kChancePlayerId;
    case GamePhase::kFinished:
      return kTerminalPlayerId;
    default:
      return current_player_;
  }
}
References open_spiel::tarok::kCardDealing, open_spiel::kChancePlayerId, open_spiel::tarok::kFinished, and open_spiel::kTerminalPlayerId.
Referenced by ToString().
DoApplyAction()
void open_spiel::tarok::TarokState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 459 of file tarok.cc.
{
  if (!ActionInActions(action_id, LegalActions())) {
    SpielFatalError(absl::StrCat("Action ", action_id,
                                 " is not valid in the current state."));
  }
  switch (current_game_phase_) {
    case GamePhase::kCardDealing:
      DoApplyActionInCardDealing();
      break;
    case GamePhase::kBidding:
      DoApplyActionInBidding(action_id);
      break;
    case GamePhase::kKingCalling:
      DoApplyActionInKingCalling(action_id);
      break;
    case GamePhase::kTalonExchange:
      DoApplyActionInTalonExchange(action_id);
      break;
    case GamePhase::kTricksPlaying:
      DoApplyActionInTricksPlaying(action_id);
      break;
    case GamePhase::kFinished:
      SpielFatalError("Calling DoApplyAction in a terminal state.");
  }
}
References open_spiel::tarok::kBidding, open_spiel::tarok::kCardDealing, open_spiel::tarok::kFinished, open_spiel::tarok::kKingCalling, open_spiel::tarok::kTalonExchange, open_spiel::tarok::kTricksPlaying, LegalActions(), open_spiel::SpielFatalError(), and absl::StrCat().
InformationStateString()
std::string open_spiel::tarok::TarokState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 933 of file tarok.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return players_info_states_.at(player);
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::tarok::TarokState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 154 of file tarok.cc.
{
  return current_game_phase_ == GamePhase::kFinished;
}
References open_spiel::tarok::kFinished.
Referenced by Returns(), and ScoresWithoutCapturedMondPenalties().
LegalActions()
std::vector< Action > open_spiel::tarok::TarokState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 193 of file tarok.cc.
{
  // all card actions are encoded as 0, 1, ..., 52, 53 and correspond to card
  // indices wrt. tarok_parent_game_->card_deck_, card actions are returned:
  //   - in the king calling phase
  //   - by LegalActionsInTalonExchange() after the talon set is selected (i.e.
  //     when discarding the cards)
  //   - by LegalActionsInTricksPlaying()
  switch (current_game_phase_) {
    case GamePhase::kCardDealing:
      // return a dummy action due to implicit stochasticity
      return {0};
    case GamePhase::kBidding:
      return LegalActionsInBidding();
    case GamePhase::kKingCalling:
      return {kKingOfHeartsAction, kKingOfDiamondsAction, kKingOfSpadesAction,
              kKingOfClubsAction};
    case GamePhase::kTalonExchange:
      return LegalActionsInTalonExchange();
    case GamePhase::kTricksPlaying:
      return LegalActionsInTricksPlaying();
    case GamePhase::kFinished:
      return {};
  }
}
References open_spiel::tarok::kBidding, open_spiel::tarok::kCardDealing, open_spiel::tarok::kFinished, open_spiel::tarok::kKingCalling, open_spiel::tarok::kKingOfClubsAction, open_spiel::tarok::kKingOfDiamondsAction, open_spiel::tarok::kKingOfHeartsAction, open_spiel::tarok::kKingOfSpadesAction, open_spiel::tarok::kTalonExchange, and open_spiel::tarok::kTricksPlaying.
Referenced by DoApplyAction().
PlayerCards()
std::vector< Action > open_spiel::tarok::TarokState::PlayerCards (Player player) const
Definition at line 160 of file tarok.cc.
{
  if (current_game_phase_ == GamePhase::kCardDealing) return {};
  return players_cards_.at(player);
}
References open_spiel::tarok::kCardDealing, and player.
Referenced by open_spiel::init_pyspiel_games_tarok(), and ToString().
Returns()
std::vector< double > open_spiel::tarok::TarokState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 743 of file tarok.cc.
{
  std::vector<double> returns(num_players_, 0.0);
  if (!IsTerminal()) return returns;
  std::vector<int> penalties = CapturedMondPenalties();
  std::vector<int> scores = ScoresWithoutCapturedMondPenalties();
  for (int i = 0; i < num_players_; i++) {
    returns.at(i) = penalties.at(i) + scores.at(i);
  }
  return returns;
}
References CapturedMondPenalties(), i, IsTerminal(), open_spiel::State::num_players_, and ScoresWithoutCapturedMondPenalties().
ScoresWithoutCapturedMondPenalties()
std::vector< int > open_spiel::tarok::TarokState::ScoresWithoutCapturedMondPenalties () const
Definition at line 762 of file tarok.cc.
{
  if (!IsTerminal()) return std::vector<int>(num_players_, 0);
  if (selected_contract_->name == ContractName::kKlop) {
    return ScoresInKlop();
  } else if (selected_contract_->NeedsTalonExchange()) {
    return ScoresInNormalContracts();
  } else {
    // beggar and above
    return ScoresInHigherContracts();
  }
}
References IsTerminal(), open_spiel::tarok::kKlop, open_spiel::tarok::Contract::name, open_spiel::tarok::Contract::NeedsTalonExchange(), and open_spiel::State::num_players_.
Referenced by open_spiel::init_pyspiel_games_tarok(), and Returns().
SelectedContractName()
ContractName open_spiel::tarok::TarokState::SelectedContractName () const
Definition at line 165 of file tarok.cc.
{
  if (current_game_phase_ == GamePhase::kCardDealing ||
      current_game_phase_ == GamePhase::kBidding) {
    return ContractName::kNotSelected;
  }
  return selected_contract_->name;
}
References open_spiel::tarok::kBidding, open_spiel::tarok::kCardDealing, open_spiel::tarok::kNotSelected, and open_spiel::tarok::Contract::name.
Referenced by open_spiel::init_pyspiel_games_tarok(), and ToString().
Serialize()
std::string open_spiel::tarok::TarokState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 971 of file tarok.cc.
{
  if (current_game_phase_ == GamePhase::kCardDealing) return "";
  // replace the dummy stochastic action with the seed that was used
  // for dealing the cards
  std::vector<Action> history = History();
  history.front() = card_dealing_seed_;
  return absl::StrJoin(history, "\n");
}
References open_spiel::State::History(), open_spiel::tarok::kCardDealing, and absl::StrJoin().
Talon()
std::vector< Action > open_spiel::tarok::TarokState::Talon () const
Definition at line 173 of file tarok.cc.
{ return talon_; }
Referenced by open_spiel::init_pyspiel_games_tarok().
TalonSets()
std::vector< std::vector< Action > > open_spiel::tarok::TarokState::TalonSets () const
Definition at line 175 of file tarok.cc.
{
  if (current_game_phase_ != GamePhase::kTalonExchange) return {};
  int num_talon_sets = talon_.size() / selected_contract_->num_talon_exchanges;
  std::vector<std::vector<Action>> talon_sets;
  talon_sets.reserve(num_talon_sets);
  auto begin = talon_.begin();
  for (int i = 0; i < num_talon_sets; i++) {
    talon_sets.push_back(std::vector<Action>(
        begin, begin + selected_contract_->num_talon_exchanges));
    std::advance(begin, selected_contract_->num_talon_exchanges);
  }
  return talon_sets;
}
References i, open_spiel::tarok::kTalonExchange, and open_spiel::tarok::Contract::num_talon_exchanges.
Referenced by open_spiel::init_pyspiel_games_tarok(), and ToString().
ToString()
std::string open_spiel::tarok::TarokState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 939 of file tarok.cc.
{
  std::string str = "";
  GamePhase current_game_phase = CurrentGamePhase();
  absl::StrAppend(&str, "Game phase: ", GamePhaseToString(current_game_phase),
                  "\n");
  absl::StrAppend(&str, "Selected contract: ",
                  ContractNameToString(SelectedContractName()), "\n");
  Player current_player = CurrentPlayer();
  absl::StrAppend(&str, "Current player: ", current_player, "\n");
  if (current_game_phase != GamePhase::kCardDealing &&
      current_game_phase != GamePhase::kFinished) {
    absl::StrAppend(&str, "Player cards: ",
                    absl::StrJoin(PlayerCards(current_player), ","), "\n");
  }
  if (current_game_phase == GamePhase::kTalonExchange) {
    auto talon_sets = TalonSets();
    std::vector<std::string> talon_sets_strings;
    talon_sets_strings.reserve(talon_sets.size());
    for (auto const& set : talon_sets) {
      talon_sets_strings.push_back(absl::StrJoin(set, ","));
    }
    absl::StrAppend(
        &str, "Talon sets: ", absl::StrJoin(talon_sets_strings, ";"), "\n");
  } else if (current_game_phase == GamePhase::kTricksPlaying) {
    absl::StrAppend(&str, "Trick cards: ", absl::StrJoin(TrickCards(), ","),
                    "\n");
  }
  return str;
}
References open_spiel::tarok::ContractNameToString(), CurrentGamePhase(), CurrentPlayer(), open_spiel::tarok::GamePhaseToString(), open_spiel::tarok::kCardDealing, open_spiel::tarok::kFinished, open_spiel::tarok::kTalonExchange, open_spiel::tarok::kTricksPlaying, PlayerCards(), SelectedContractName(), absl::StrAppend(), absl::StrJoin(), TalonSets(), and TrickCards().
TrickCards()
std::vector< Action > open_spiel::tarok::TarokState::TrickCards () const
Definition at line 191 of file tarok.cc.
{ return trick_cards_; }
Referenced by open_spiel::init_pyspiel_games_tarok(), and ToString().
Friends And Related Symbol Documentation
TarokGame
friend class TarokGame friend
Definition at line 138 of file tarok.h.
The documentation for this class was generated from the following files:
open_spiel/games/tarok/tarok.h
open_spiel/games/tarok/tarok.cc