open spiel: absl::CordBuffer Class Reference
absl::CordBuffer Class Reference
#include <cord_buffer.h>
Public Member Functions
CordBuffer ()=default
~CordBuffer ()
CordBuffer (CordBuffer &&rhs) noexcept
CordBuffer & operator= (CordBuffer &&) noexcept
CordBuffer (const CordBuffer &)=delete
CordBuffer & operator= (const CordBuffer &)=delete
absl::Span< char > available ()
absl::Span< char > available_up_to (size_t size)
char * data ()
const char * data () const
size_t length () const
size_t capacity () const
void IncreaseLengthBy (size_t n)
void SetLength (size_t length)
Static Public Member Functions
static constexpr size_t MaximumPayload ()
static constexpr size_t MaximumPayload (size_t block_size)
static CordBuffer CreateWithDefaultLimit (size_t capacity)
static CordBuffer CreateWithCustomLimit (size_t block_size, size_t capacity)
Static Public Attributes
static constexpr size_t kDefaultLimit = cord_internal::kMaxFlatLength
static constexpr size_t kCustomLimit = 64U << 10
Friends
class Cord
class CordBufferTestPeer
Detailed Description
Definition at line 105 of file cord_buffer.h.
Constructor & Destructor Documentation
CordBuffer() [1/3]
absl::CordBuffer::CordBuffer () default
Referenced by CreateWithDefaultLimit().
~CordBuffer()
absl::CordBuffer::~CordBuffer () inline
Definition at line 513 of file cord_buffer.h.
{
  if (!rep_.is_short()) {
    cord_internal::CordRepFlat::Delete(rep_.rep());
  }
}
References absl::cord_internal::CordRepFlat::Delete().
CordBuffer() [2/3]
absl::CordBuffer::CordBuffer (CordBuffer && rhs) inline noexcept
Definition at line 519 of file cord_buffer.h.
                                                       : rep_(rhs.rep_) {
  rhs.rep_.set_short_length(0);
}
CordBuffer() [3/3]
absl::CordBuffer::CordBuffer (const CordBuffer &) delete
Member Function Documentation
available()
absl::Span< char > absl::CordBuffer::available () inline
Definition at line 530 of file cord_buffer.h.
{
  return rep_.is_short() ? rep_.short_available() : rep_.long_available();
}
Referenced by available_up_to().
available_up_to()
absl::Span< char > absl::CordBuffer::available_up_to (size_t size) inline
Definition at line 534 of file cord_buffer.h.
{
  return available().subspan(0, size);
}
References available(), size, and absl::Span< T >::subspan().
capacity()
size_t absl::CordBuffer::capacity () const inline
Definition at line 546 of file cord_buffer.h.
{
  return rep_.is_short() ? Rep::kInlineCapacity : rep_.rep()->Capacity();
}
References absl::cord_internal::CordRepFlat::Capacity().
Referenced by CreateWithCustomLimit(), CreateWithDefaultLimit(), IncreaseLengthBy(), SetLength(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
CreateWithCustomLimit()
CordBuffer absl::CordBuffer::CreateWithCustomLimit (size_t block_size, size_t capacity) inline static
Definition at line 508 of file cord_buffer.h.
{
  return CreateWithCustomLimitImpl(block_size, capacity);
}
References capacity().
Referenced by absl::Cord::GetCustomAppendBuffer().
CreateWithDefaultLimit()
CordBuffer absl::CordBuffer::CreateWithDefaultLimit (size_t capacity) inline static
Definition at line 468 of file cord_buffer.h.
{
  if (capacity > Rep::kInlineCapacity) {
    auto* rep = cord_internal::CordRepFlat::New(capacity);
    rep->length = 0;
    return CordBuffer(rep);
  }
  return CordBuffer();
}
References capacity(), CordBuffer(), absl::cord_internal::CordRepFlat::New(), and rep.
Referenced by absl::Cord::GetAppendBuffer(), absl::Cord::GetCustomAppendBuffer(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
data() [1/2]
char * absl::CordBuffer::data () inline
Definition at line 538 of file cord_buffer.h.
{
  return rep_.is_short() ? rep_.data() : rep_.rep()->Data();
}
References absl::cord_internal::CordRepFlat::Data().
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), operator=(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
data() [2/2]
const char * absl::CordBuffer::data () const inline
Definition at line 542 of file cord_buffer.h.
{
  return rep_.is_short() ? rep_.data() : rep_.rep()->Data();
}
References absl::cord_internal::CordRepFlat::Data().
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__bool__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::__len__(), open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::sample().
IncreaseLengthBy()
void absl::CordBuffer::IncreaseLengthBy (size_t n) inline
Definition at line 563 of file cord_buffer.h.
{
  ABSL_HARDENING_ASSERT(n <= capacity() && length() + n <= capacity());
  if (rep_.is_short()) {
    rep_.add_short_length(n);
  } else {
    rep_.rep()->length += n;
  }
}
References ABSL_HARDENING_ASSERT, capacity(), absl::cord_internal::CordRep::length, length(), and absl::n.
length()
size_t absl::CordBuffer::length () const inline
Definition at line 550 of file cord_buffer.h.
{
  return rep_.is_short() ? rep_.short_length() : rep_.rep()->length;
}
References absl::cord_internal::CordRep::length.
Referenced by absl::Cord::Append(), IncreaseLengthBy(), operator=(), absl::Cord::Prepend(), SetLength(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
MaximumPayload() [1/2]
size_t absl::CordBuffer::MaximumPayload () inline static constexpr
Definition at line 458 of file cord_buffer.h.
{
  return cord_internal::kMaxFlatLength;
}
Referenced by CordAppendBufferTest::maximum_payload().
MaximumPayload() [2/2]
size_t absl::CordBuffer::MaximumPayload (size_t block_size) inline static constexpr
Definition at line 462 of file cord_buffer.h.
{
  // TODO(absl-team): Use std::min when C++11 support is dropped.
  return (kCustomLimit < block_size ? kCustomLimit : block_size) -
         cord_internal::kFlatOverhead;
}
References kCustomLimit.
operator=() [1/2]
CordBuffer & absl::CordBuffer::operator= (const CordBuffer &) delete
References data(), length(), absl::n, and rep.
operator=() [2/2]
CordBuffer & absl::CordBuffer::operator= (CordBuffer && rhs) inline noexcept
Definition at line 523 of file cord_buffer.h.
{
  if (!rep_.is_short()) cord_internal::CordRepFlat::Delete(rep_.rep());
  rep_ = rhs.rep_;
  rhs.rep_.set_short_length(0);
  return *this;
}
References absl::cord_internal::CordRepFlat::Delete().
SetLength()
void absl::CordBuffer::SetLength (size_t length) inline
Definition at line 554 of file cord_buffer.h.
{
  ABSL_HARDENING_ASSERT(length <= capacity());
  if (rep_.is_short()) {
    rep_.set_short_length(length);
  } else {
    rep_.rep()->length = length;
  }
}
References ABSL_HARDENING_ASSERT, capacity(), absl::cord_internal::CordRep::length, and length().
Referenced by TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), TEST_P(), and TEST_P().
Friends And Related Symbol Documentation
Cord
friend class Cord friend
Definition at line 454 of file cord_buffer.h.
CordBufferTestPeer
friend class CordBufferTestPeer friend
Definition at line 455 of file cord_buffer.h.
Member Data Documentation
kCustomLimit
size_t absl::CordBuffer::kCustomLimit = 64U << 10 static constexpr
Definition at line 118 of file cord_buffer.h.
Referenced by CordAppendBufferTest::limit(), and MaximumPayload().
kDefaultLimit
size_t absl::CordBuffer::kDefaultLimit = cord_internal::kMaxFlatLength static constexpr
Definition at line 111 of file cord_buffer.h.
Referenced by CordAppendBufferTest::limit().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/cord_buffer.h