open spiel: open_spiel.python.policy.FirstActionPolicy Class Reference
open_spiel.python.policy.FirstActionPolicy Class Reference
Public Member Functions
__init__ (self, game)
action_probabilities (self, state, player_id=None)
Public Member Functions inherited from open_spiel.python.policy.Policy
__call__ (self, state, player_id=None)
to_tabular (self, states=None)
Additional Inherited Members
Public Attributes inherited from open_spiel.python.policy.Policy
game
player_ids
Detailed Description
A policy that always takes the lowest-numbered legal action.
Definition at line 434 of file policy.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.policy.FirstActionPolicy.__init__ (self, game)
Initializes a policy.
Args:
  game: the game for which this policy applies
  player_ids: list of player ids for which this policy applies; each should
    be in the range 0..game.num_players()-1.
Reimplemented from open_spiel.python.policy.Policy.
Definition at line 437 of file policy.py.
  def __init__(self, game):
    all_players = list(range(game.num_players()))
    super().__init__(game, all_players)
References open_spiel.python.policy.FirstActionPolicy.__init__().
Referenced by open_spiel.python.policy.FirstActionPolicy.__init__().
Member Function Documentation
action_probabilities()
open_spiel.python.policy.FirstActionPolicy.action_probabilities (self, state, player_id = None)
Returns a dictionary {action: prob} for all legal actions.
IMPORTANT: We assume the following properties hold:
- All probabilities are >=0 and sum to 1
- TLDR: Policy implementations should list the (action, prob) for all legal
  actions, but algorithms should not rely on this (yet).
  Details: Before May 2020, only legal actions were present in the mapping,
  but it did not have to be exhaustive: missing actions were considered to
  be associated to a zero probability.
  For example, a deterministic state-poliy was previously {action: 1.0}.
  Given this change of convention is new and hard to enforce, algorithms
  should not rely on the fact that all legal actions should be present.
Args:
  state: A `pyspiel.State` object.
  player_id: Optional, the player id for whom we want an action. Optional
    unless this is a simultaneous state at which multiple players can act.
Returns:
  A `dict` of `{action: probability}` for the specified player in the
  supplied state.
Reimplemented from open_spiel.python.policy.Policy.
Definition at line 441 of file policy.py.
  def action_probabilities(self, state, player_id=None):
    legal_actions = (
        state.legal_actions()
        if player_id is None else state.legal_actions(player_id))
    if not legal_actions:
      return {0: 1.0}
    min_action = min(legal_actions)
    return {
        action: 1.0 if action == min_action else 0.0 for action in legal_actions
    }
Referenced by open_spiel.python.policy.Policy.__call__(), and open_spiel.python.policy.Policy.to_tabular().
The documentation for this class was generated from the following file:
open_spiel/python/policy.py