open spiel: open_spiel::quoridor::QuoridorState::SearchState Class Reference
open_spiel::quoridor::QuoridorState::SearchState Class Reference
Public Member Functions
SearchState (int board_diameter)
bool IsEmpty () const
void ClearSearchQueue ()
bool Push (int dist, Move move)
Move Pop ()
void ResetSearchQueue ()
void ResetDists ()
void SetDist (Move move, int dist)
int GetDist (Move move) const
void SetOnShortestPath (Move move)
bool IsOnShortestPath (Move move) const
Static Public Member Functions
static constexpr int UndefinedDistance ()
Detailed Description
Definition at line 74 of file quoridor.cc.
Constructor & Destructor Documentation
SearchState()
open_spiel::quoridor::QuoridorState::SearchState::SearchState (int board_diameter) inline explicit
Definition at line 87 of file quoridor.cc.
{
    int size = board_diameter * board_diameter;
    mark_.resize(size, false);
    on_shortest_path_.resize(size, false);
    distance_.resize(size, UndefinedDistance());
    queue_.reserve(size);
  }
References size, and UndefinedDistance().
Member Function Documentation
ClearSearchQueue()
void open_spiel::quoridor::QuoridorState::SearchState::ClearSearchQueue () inline
Definition at line 97 of file quoridor.cc.
{ queue_.clear(); }
GetDist()
int open_spiel::quoridor::QuoridorState::SearchState::GetDist (Move move) const inline
Definition at line 125 of file quoridor.cc.
{ return distance_[move.xy]; }
IsEmpty()
bool open_spiel::quoridor::QuoridorState::SearchState::IsEmpty () const inline
Definition at line 95 of file quoridor.cc.
{ return queue_.empty(); }
IsOnShortestPath()
bool open_spiel::quoridor::QuoridorState::SearchState::IsOnShortestPath (Move move) const inline
Definition at line 127 of file quoridor.cc.
{ return on_shortest_path_[move.xy]; }
Pop()
Move open_spiel::quoridor::QuoridorState::SearchState::Pop () inline
Definition at line 109 of file quoridor.cc.
             {
    Move move = queue_.top().second;
    queue_.pop();
    return move;
  }
Push()
bool open_spiel::quoridor::QuoridorState::SearchState::Push (int dist, Move move) inline
Definition at line 99 of file quoridor.cc.
{
    if (mark_[move.xy] == false) {
      mark_[move.xy] = true;
      queue_.emplace(dist, move);
      return true;
    } else {
      return false;
    }
  }
ResetDists()
void open_spiel::quoridor::QuoridorState::SearchState::ResetDists () inline
Definition at line 120 of file quoridor.cc.
                    {
    std::fill(distance_.begin(), distance_.end(), UndefinedDistance());
  }
References UndefinedDistance().
ResetSearchQueue()
void open_spiel::quoridor::QuoridorState::SearchState::ResetSearchQueue () inline
Definition at line 115 of file quoridor.cc.
{
    std::fill(mark_.begin(), mark_.end(), false);
    queue_.clear();
  }
SetDist()
void open_spiel::quoridor::QuoridorState::SearchState::SetDist (Move move, int dist) inline
Definition at line 124 of file quoridor.cc.
{ distance_[move.xy] = dist; }
SetOnShortestPath()
void open_spiel::quoridor::QuoridorState::SearchState::SetOnShortestPath (Move move) inline
Definition at line 126 of file quoridor.cc.
{ on_shortest_path_[move.xy] = true; }
UndefinedDistance()
static constexpr int open_spiel::quoridor::QuoridorState::SearchState::UndefinedDistance () inline static constexpr
Definition at line 129 of file quoridor.cc.
{ return -1; }
Referenced by ResetDists(), and SearchState().
The documentation for this class was generated from the following file:
open_spiel/games/quoridor/quoridor.cc