open spiel: absl::flags_internal::FlagRegistry Class Reference
absl::flags_internal::FlagRegistry Class Reference
Public Member Functions
FlagRegistry ()=default
~FlagRegistry ()=default
void RegisterFlag (CommandLineFlag &flag, const char *filename)
void Lock () ABSL_EXCLUSIVE_LOCK_FUNCTION(lock_)
void Unlock () ABSL_UNLOCK_FUNCTION(lock_)
CommandLineFlag * FindFlag (absl::string_view name)
Static Public Member Functions
static FlagRegistry & GlobalRegistry ()
Friends
class flags_internal::FlagSaverImpl
void ForEachFlag (std::function< void(CommandLineFlag &)> visitor)
void FinalizeRegistry ()
Detailed Description
Definition at line 47 of file reflection.cc.
Constructor & Destructor Documentation
FlagRegistry()
absl::flags_internal::FlagRegistry::FlagRegistry () default
Referenced by GlobalRegistry().
~FlagRegistry()
absl::flags_internal::FlagRegistry::~FlagRegistry () default
Member Function Documentation
FindFlag()
CommandLineFlag * absl::flags_internal::FlagRegistry::FindFlag (absl::string_view name)
Definition at line 98 of file reflection.cc.
{
  if (finalized_flags_.load(std::memory_order_acquire)) {
    // We could save some gcus here if we make `Name()` be non-virtual.
    // We could move the `const char*` name to the base class.
    auto it = std::partition_point(
        flat_flags_.begin(), flat_flags_.end(),
        [=](CommandLineFlag* f) { return f->Name() < name; });
    if (it != flat_flags_.end() && (*it)->Name() == name) return *it;
  }
  FlagRegistryLock frl(*this);
  auto it = flags_.find(name);
  return it != flags_.end() ? it->second : nullptr;
}
References absl::f, and name.
Referenced by absl::FindCommandLineFlag().
GlobalRegistry()
FlagRegistry & absl::flags_internal::FlagRegistry::GlobalRegistry () static
Definition at line 171 of file reflection.cc.
{
  static FlagRegistry* global_registry = new FlagRegistry;
  return *global_registry;
}
References FlagRegistry().
Referenced by absl::FindCommandLineFlag(), absl::flags_internal::RegisterCommandLineFlag(), and absl::flags_internal::Retire().
Lock()
void absl::flags_internal::FlagRegistry::Lock () inline
Definition at line 55 of file reflection.cc.
{ lock_.Lock(); }
RegisterFlag()
void absl::flags_internal::FlagRegistry::RegisterFlag (CommandLineFlag & flag, const char * filename)
Definition at line 113 of file reflection.cc.
{
  if (filename != nullptr &&
      flag.Filename() != GetUsageConfig().normalize_filename(filename)) {
    flags_internal::ReportUsageError(
        absl::StrCat(
            "Inconsistency between flag object and registration for flag '",
            flag.Name(),
            "', likely due to duplicate flags or an ODR violation. Relevant "
            "files: ",
            flag.Filename(), " and ", filename),
        true);
    std::exit(1);
  }
  FlagRegistryLock registry_lock(*this);
  std::pair<FlagIterator, bool> ins =
      flags_.insert(FlagMap::value_type(flag.Name(), &flag));
  if (ins.second == false) {  // means the name was already in the map
    CommandLineFlag& old_flag = *ins.first->second;
    if (flag.IsRetired() != old_flag.IsRetired()) {
      // All registrations must agree on the 'retired' flag.
      flags_internal::ReportUsageError(
          absl::StrCat(
              "Retired flag '", flag.Name(), "' was defined normally in file '",
              (flag.IsRetired() ? old_flag.Filename() : flag.Filename()), "'."),
          true);
    } else if (flags_internal::PrivateHandleAccessor::TypeId(flag) !=
               flags_internal::PrivateHandleAccessor::TypeId(old_flag)) {
      flags_internal::ReportUsageError(
          absl::StrCat("Flag '", flag.Name(),
                       "' was defined more than once but with "
                       "differing types. Defined in files '",
                       old_flag.Filename(), "' and '", flag.Filename(), "'."),
          true);
    } else if (old_flag.IsRetired()) {
      return;
    } else if (old_flag.Filename() != flag.Filename()) {
      flags_internal::ReportUsageError(
          absl::StrCat("Flag '", flag.Name(),
                       "' was defined more than once (in files '",
                       old_flag.Filename(), "' and '", flag.Filename(), "')."),
          true);
    } else {
      flags_internal::ReportUsageError(
          absl::StrCat(
              "Something is wrong with flag '", flag.Name(), "' in file '",
              flag.Filename(), "'. One possibility: file '", flag.Filename(),
              "' is being linked both statically and dynamically into this "
              "executable. e.g. some files listed as srcs to a test and also "
              "listed as srcs of some shared lib deps of the same test."),
          true);
    }
    // All cases above are fatal, except for the retired flags.
    std::exit(1);
  }
}
References absl::CommandLineFlag::Filename(), absl::flags_internal::GetUsageConfig(), absl::CommandLineFlag::IsRetired(), absl::CommandLineFlag::Name(), absl::flags_internal::ReportUsageError(), absl::StrCat(), and absl::flags_internal::PrivateHandleAccessor::TypeId().
Referenced by absl::flags_internal::RegisterCommandLineFlag(), and absl::flags_internal::Retire().
Unlock()
void absl::flags_internal::FlagRegistry::Unlock () inline
Definition at line 56 of file reflection.cc.
{ lock_.Unlock(); }
Friends And Related Symbol Documentation
FinalizeRegistry
void FinalizeRegistry () friend
Definition at line 196 of file reflection.cc.
{
  auto& registry = FlagRegistry::GlobalRegistry();
  FlagRegistryLock frl(registry);
  if (registry.finalized_flags_.load(std::memory_order_relaxed)) {
    // Was already finalized. Ignore the second time.
    return;
  }
  registry.flat_flags_.reserve(registry.flags_.size());
  for (const auto& f : registry.flags_) {
    registry.flat_flags_.push_back(f.second);
  }
  std::sort(std::begin(registry.flat_flags_), std::end(registry.flat_flags_),
            [](const CommandLineFlag* lhs, const CommandLineFlag* rhs) {
              return lhs->Name() < rhs->Name();
            });
  registry.flags_.clear();
  registry.finalized_flags_.store(true, std::memory_order_release);
}
flags_internal::FlagSaverImpl
friend class flags_internal::FlagSaverImpl friend
Definition at line 65 of file reflection.cc.
ForEachFlag
void ForEachFlag (std::function< void(CommandLineFlag &)> visitor) friend
Definition at line 178 of file reflection.cc.
{
  FlagRegistry& registry = FlagRegistry::GlobalRegistry();
  if (registry.finalized_flags_.load(std::memory_order_acquire)) {
    for (const auto& i : registry.flat_flags_) visitor(*i);
  }
  FlagRegistryLock frl(registry);
  for (const auto& i : registry.flags_) visitor(*i.second);
}
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/flags/reflection.cc