open spiel: open_spiel::first_sealed_auction::FPSBAState Class Reference
open_spiel::first_sealed_auction::FPSBAState Class Reference
#include <first_sealed_auction.h>
Public Member Functions
FPSBAState (std::shared_ptr< const Game > game)
FPSBAState (const FPSBAState &other)=default
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
ActionsAndProbs ChanceOutcomes () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 46 of file first_sealed_auction.h.
Constructor & Destructor Documentation
FPSBAState() [1/2]
open_spiel::first_sealed_auction::FPSBAState::FPSBAState (std::shared_ptr< const Game > game)
Definition at line 59 of file first_sealed_auction.cc.
    : State(game), max_value_(game->NumDistinctActions()) {}
Referenced by Clone().
FPSBAState() [2/2]
open_spiel::first_sealed_auction::FPSBAState::FPSBAState (const FPSBAState & other) default
Member Function Documentation
ActionToString()
std::string open_spiel::first_sealed_auction::FPSBAState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 97 of file first_sealed_auction.cc.
{
  if (player != kChancePlayerId) {
    return absl::StrCat("Player ", player, " bid: ", action_id);
  } else if (valuations_.size() < num_players_) {
    return absl::StrCat("Player ", valuations_.size(), " value: ", action_id);
  } else {
    return absl::StrCat("Chose winner ", action_id);
  }
}
References open_spiel::kChancePlayerId, open_spiel::State::num_players_, player, and absl::StrCat().
ChanceOutcomes()
ActionsAndProbs open_spiel::first_sealed_auction::FPSBAState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 188 of file first_sealed_auction.cc.
{
  ActionsAndProbs valuesAndProbs;
  if (valuations_.size() < num_players_) {
    for (int i = 1; i <= max_value_; i++) {
      valuesAndProbs.push_back(std::make_pair(i, 1. / max_value_));
    }
  } else if (bids_.size() == num_players_ && winner_ == kInvalidPlayer) {
    int max_bid = *std::max_element(bids_.begin(), bids_.end());
    int num_tie = std::count(bids_.begin(), bids_.end(), max_bid);
    for (auto player = Player{0}; player < num_players_; player++) {
      if (bids_[player] == max_bid) {
        valuesAndProbs.push_back(std::make_pair(player, 1. / num_tie));
      }
    }
  } else {
    SpielFatalError("This isn't a chance node");
  }
  return valuesAndProbs;
}
References i, open_spiel::kInvalidPlayer, open_spiel::State::num_players_, player, and open_spiel::SpielFatalError().
Clone()
std::unique_ptr< State > open_spiel::first_sealed_auction::FPSBAState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 123 of file first_sealed_auction.cc.
{
  return std::unique_ptr<State>(new FPSBAState(*this));
}
References FPSBAState().
CurrentPlayer()
int open_spiel::first_sealed_auction::FPSBAState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 62 of file first_sealed_auction.cc.
{
  if (valuations_.size() < num_players_) return kChancePlayerId;
  if (bids_.size() < num_players_) return bids_.size();
  if (winner_ == kInvalidPlayer) return kChancePlayerId;
  return kTerminalPlayerId;
}
References open_spiel::kChancePlayerId, open_spiel::kInvalidPlayer, open_spiel::kTerminalPlayerId, and open_spiel::State::num_players_.
DoApplyAction()
void open_spiel::first_sealed_auction::FPSBAState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 127 of file first_sealed_auction.cc.
{
  if (valuations_.size() < num_players_) {
    valuations_.push_back(action_id);
  } else if (bids_.size() < num_players_) {
    bids_.push_back(action_id);
  } else if (winner_ == kInvalidPlayer) {
    winner_ = action_id;
  } else {
    SpielFatalError(
        absl::StrCat("Can't apply action in terminal state: ", action_id));
  }
}
References open_spiel::kInvalidPlayer, open_spiel::State::num_players_, open_spiel::SpielFatalError(), and absl::StrCat().
InformationStateString()
std::string open_spiel::first_sealed_auction::FPSBAState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 140 of file first_sealed_auction.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (valuations_.size() <= player) return absl::StrCat("p", player);
  if (bids_.size() <= player)
    return absl::StrCat("p", player, " val ", valuations_[player]);
  return absl::StrCat("p", player, " val ", valuations_[player], " bid ",
                      bids_[player]);
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
InformationStateTensor()
void open_spiel::first_sealed_auction::FPSBAState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 150 of file first_sealed_auction.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), 2 * max_value_ + num_players_);
  std::fill(values.begin(), values.end(), 0);
  auto cursor = values.begin();
  cursor[player] = 1;
  cursor += num_players_;
  if (valuations_.size() > player) {
    cursor[valuations_[player] - 1] = 1;
  }
  cursor += max_value_;
  if (bids_.size() > player) {
    cursor[bids_[player]] = 1;
  }
  cursor += max_value_;
  SPIEL_CHECK_EQ(cursor - values.begin(), values.size());
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::first_sealed_auction::FPSBAState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 113 of file first_sealed_auction.cc.
{ return winner_ != kInvalidPlayer; }
References open_spiel::kInvalidPlayer.
LegalActions()
std::vector< Action > open_spiel::first_sealed_auction::FPSBAState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 80 of file first_sealed_auction.cc.
{
  if (valuations_.size() < num_players_) {
    std::vector<Action> values(max_value_);
    std::iota(values.begin(), values.end(), 1);
    return values;
  }
  if (bids_.size() < num_players_) {
    std::vector<Action> bids(valuations_[bids_.size()]);
    std::iota(bids.begin(), bids.end(), 0);
    return bids;
  }
  if (winner_ == kInvalidPlayer) {
    return EligibleWinners();
  }
  return {};
}
References open_spiel::kInvalidPlayer, open_spiel::State::num_players_, and values.
ObservationString()
std::string open_spiel::first_sealed_auction::FPSBAState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 170 of file first_sealed_auction.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  if (valuations_.size() <= player) return "";
  return absl::StrCat(valuations_[player]);
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrCat().
ObservationTensor()
void open_spiel::first_sealed_auction::FPSBAState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 177 of file first_sealed_auction.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), max_value_);
  std::fill(values.begin(), values.end(), 0);
  if (valuations_.size() > player) {
    values[valuations_[player] - 1] = 1;
  }
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::first_sealed_auction::FPSBAState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 115 of file first_sealed_auction.cc.
{
  std::vector<double> returns(num_players_);
  if (winner_ != kInvalidPlayer) {
    returns[winner_] = valuations_[winner_] - bids_[winner_];
  }
  return returns;
}
References open_spiel::kInvalidPlayer, and open_spiel::State::num_players_.
ToString()
std::string open_spiel::first_sealed_auction::FPSBAState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 107 of file first_sealed_auction.cc.
{
  return absl::StrCat(
      absl::StrJoin(valuations_, ","), ";", absl::StrJoin(bids_, ","),
      winner_ == kInvalidPlayer ? "" : absl::StrCat(";", winner_));
}
References open_spiel::kInvalidPlayer, absl::StrCat(), and absl::StrJoin().
The documentation for this class was generated from the following files:
open_spiel/games/first_sealed_auction/first_sealed_auction.h
open_spiel/games/first_sealed_auction/first_sealed_auction.cc