open spiel: open_spiel.python.observation._Observation Class Reference
open_spiel.python.observation._Observation Class Reference
Public Member Functions
__init__ (self, game, observer)
set_from (self, state, player)
string_from (self, state, player)
compress (self)
decompress (self, compressed_observation)
Public Attributes
dict
tensor
Protected Attributes
_observation
Detailed Description
Contains an observation from a game.
Definition at line 63 of file observation.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.observation._Observation.__init__ (self, game, observer)
Definition at line 66 of file observation.py.
  def __init__(self, game, observer):
    self._observation = pyspiel._Observation(game, observer)
    self.dict = {}
    if self._observation.has_tensor():
      self.tensor = np.frombuffer(self._observation, np.float32)
      offset = 0
      for tensor_info in self._observation.tensors_info():
        size = np.prod(tensor_info.shape, dtype=np.int64)
        values = self.tensor[offset:offset + size].reshape(tensor_info.shape)
        self.dict[tensor_info.name] = values
        offset += size
    else:
      self.tensor = None
Member Function Documentation
compress()
open_spiel.python.observation._Observation.compress (self)
Definition at line 87 of file observation.py.
  def compress(self):
    return self._observation.compress()
References open_spiel.python.observation._Observation._observation, and open_spiel.python.observation._Observation.compress().
Referenced by open_spiel.python.observation._Observation.compress().
decompress()
open_spiel.python.observation._Observation.decompress (self, compressed_observation)
Definition at line 90 of file observation.py.
  def decompress(self, compressed_observation):
    self._observation.decompress(compressed_observation)
References open_spiel.python.observation._Observation._observation, and open_spiel.python.observation._Observation.decompress().
Referenced by open_spiel.python.observation._Observation.decompress().
set_from()
open_spiel.python.observation._Observation.set_from (self, state, player)
Definition at line 80 of file observation.py.
  def set_from(self, state, player):
    self._observation.set_from(state, player)
References open_spiel.python.observation._Observation._observation, and open_spiel.python.observation._Observation.set_from().
Referenced by open_spiel.python.observation._Observation.set_from().
string_from()
open_spiel.python.observation._Observation.string_from (self, state, player)
Definition at line 83 of file observation.py.
  def string_from(self, state, player):
    return (self._observation.string_from(state, player)
            if self._observation.has_string() else None)
References open_spiel.python.observation._Observation._observation, and open_spiel.python.observation._Observation.string_from().
Referenced by open_spiel.python.observation._Observation.string_from().
Member Data Documentation
_observation
open_spiel.python.observation._Observation._observation protected
Definition at line 67 of file observation.py.
Referenced by open_spiel.python.observation._Observation.compress(), open_spiel.python.observation._Observation.decompress(), open_spiel.python.observation._Observation.set_from(), and open_spiel.python.observation._Observation.string_from().
dict
open_spiel.python.observation._Observation.dict
Definition at line 68 of file observation.py.
tensor
open_spiel.python.observation._Observation.tensor
Definition at line 70 of file observation.py.
The documentation for this class was generated from the following file:
open_spiel/python/observation.py