open spiel: absl::time_internal::cctz::time_zone::Impl Class Reference
absl::time_internal::cctz::time_zone::Impl Class Reference
#include <time_zone_impl.h>
Public Member Functions
const std::string & Name () const
time_zone::absolute_lookup BreakTime (const time_point< seconds > &tp) const
time_zone::civil_lookup MakeTime (const civil_second &cs) const
bool NextTransition (const time_point< seconds > &tp, time_zone::civil_transition *trans) const
bool PrevTransition (const time_point< seconds > &tp, time_zone::civil_transition *trans) const
std::string Version () const
std::string Description () const
Static Public Member Functions
static time_zone UTC ()
static bool LoadTimeZone (const std::string &name, time_zone *tz)
static void ClearTimeZoneMapTestOnly ()
Detailed Description
Definition at line 33 of file time_zone_impl.h.
Member Function Documentation
BreakTime()
time_zone::absolute_lookup absl::time_internal::cctz::time_zone::Impl::BreakTime (const time_point< seconds > & tp) const inline
Definition at line 53 of file time_zone_impl.h.
{
    return zone_->BreakTime(tp);
  }
Referenced by absl::time_internal::cctz::time_zone::lookup().
ClearTimeZoneMapTestOnly()
void absl::time_internal::cctz::time_zone::Impl::ClearTimeZoneMapTestOnly () static
Definition at line 87 of file time_zone_impl.cc.
{
  std::lock_guard<std::mutex> lock(TimeZoneMutex());
  if (time_zone_map != nullptr) {
    // Existing time_zone::Impl* entries are in the wild, so we can't delete
    // them. Instead, we move them to a private container, where they are
    // logically unreachable but not "leaked".  Future requests will result
    // in reloading the data.
    static auto* cleared = new std::deque<const time_zone::Impl*>;
    for (const auto& element : *time_zone_map) {
      cleared->push_back(element.second);
    }
    time_zone_map->clear();
  }
}
Description()
std::string absl::time_internal::cctz::time_zone::Impl::Description () const inline
Definition at line 78 of file time_zone_impl.h.
{ return zone_->Description(); }
Referenced by absl::time_internal::cctz::time_zone::description().
LoadTimeZone()
bool absl::time_internal::cctz::time_zone::Impl::LoadTimeZone (const std::string & name, time_zone * tz) static
Definition at line 51 of file time_zone_impl.cc.
{
  const Impl* const utc_impl = UTCImpl();
  // Check for UTC (which is never a key in time_zone_map).
  auto offset = seconds::zero();
  if (FixedOffsetFromName(name, &offset) && offset == seconds::zero()) {
    *tz = time_zone(utc_impl);
    return true;
  }
  // Check whether the time zone has already been loaded.
  {
    std::lock_guard<std::mutex> lock(TimeZoneMutex());
    if (time_zone_map != nullptr) {
      TimeZoneImplByName::const_iterator itr = time_zone_map->find(name);
      if (itr != time_zone_map->end()) {
        *tz = time_zone(itr->second);
        return itr->second != utc_impl;
      }
    }
  }
  // Load the new time zone (outside the lock).
  std::unique_ptr<const Impl> new_impl(new Impl(name));
  // Add the new time zone to the map.
  std::lock_guard<std::mutex> lock(TimeZoneMutex());
  if (time_zone_map == nullptr) time_zone_map = new TimeZoneImplByName;
  const Impl*& impl = (*time_zone_map)[name];
  if (impl == nullptr) {  // this thread won any load race
    impl = new_impl->zone_ ? new_impl.release() : utc_impl;
  }
  *tz = time_zone(impl);
  return impl != utc_impl;
}
References absl::time_internal::cctz::FixedOffsetFromName(), absl::time_internal::cctz::time_zone::name(), and absl::time_internal::cctz::time_zone::time_zone().
Referenced by absl::time_internal::cctz::load_time_zone().
MakeTime()
time_zone::civil_lookup absl::time_internal::cctz::time_zone::Impl::MakeTime (const civil_second & cs) const inline
Definition at line 60 of file time_zone_impl.h.
{
    return zone_->MakeTime(cs);
  }
Referenced by absl::time_internal::cctz::time_zone::lookup().
Name()
const std::string & absl::time_internal::cctz::time_zone::Impl::Name () const inline
Definition at line 47 of file time_zone_impl.h.
{
    // TODO: It would nice if the zoneinfo data included the zone name.
    return name_;
  }
Referenced by absl::time_internal::cctz::time_zone::name().
NextTransition()
bool absl::time_internal::cctz::time_zone::Impl::NextTransition (const time_point< seconds > & tp, time_zone::civil_transition * trans) const inline
Definition at line 65 of file time_zone_impl.h.
{
    return zone_->NextTransition(tp, trans);
  }
Referenced by absl::time_internal::cctz::time_zone::next_transition().
PrevTransition()
bool absl::time_internal::cctz::time_zone::Impl::PrevTransition (const time_point< seconds > & tp, time_zone::civil_transition * trans) const inline
Definition at line 69 of file time_zone_impl.h.
{
    return zone_->PrevTransition(tp, trans);
  }
Referenced by absl::time_internal::cctz::time_zone::prev_transition().
UTC()
time_zone absl::time_internal::cctz::time_zone::Impl::UTC () static
Definition at line 49 of file time_zone_impl.cc.
{ return time_zone(UTCImpl()); }
References absl::time_internal::cctz::time_zone::time_zone().
Referenced by absl::time_internal::cctz::utc_time_zone().
Version()
std::string absl::time_internal::cctz::time_zone::Impl::Version () const inline
Definition at line 75 of file time_zone_impl.h.
{ return zone_->Version(); }
Referenced by absl::time_internal::cctz::time_zone::version().
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.h
open_spiel/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc