open spiel: open_spiel::catch_::CatchState Class Reference
open_spiel::catch_::CatchState Class Reference
#include <catch.h>
Public Member Functions
CatchState (std::shared_ptr< const Game > game)
CatchState (const CatchState &)=default
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
ActionsAndProbs ChanceOutcomes () const override
CellState BoardAt (int row, int column) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
virtual std::string InformationStateString (Player player) const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action move) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 62 of file catch.h.
Constructor & Destructor Documentation
CatchState() [1/2]
open_spiel::catch_::CatchState::CatchState (std::shared_ptr< const Game > game)
Definition at line 70 of file catch.cc.
                                                     : State(game) {
  const CatchGame& parent_game = static_cast<const CatchGame&>(*game);
  num_rows_ = parent_game.NumRows();
  num_columns_ = parent_game.NumColumns();
}
References open_spiel::catch_::CatchGame::NumColumns(), and open_spiel::catch_::CatchGame::NumRows().
Referenced by Clone().
CatchState() [2/2]
open_spiel::catch_::CatchState::CatchState (const CatchState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::catch_::CatchState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 111 of file catch.cc.
{
  if (player == kChancePlayerId)
    return absl::StrCat("Initialized ball to ", action_id);
  SPIEL_CHECK_EQ(player, 0);
  switch (action_id) {
    case 0:
      return "LEFT";
    case 1:
      return "STAY";
    case 2:
      return "RIGHT";
    default:
      SpielFatalError("Out of range action");
  }
}
References open_spiel::kChancePlayerId, player, SPIEL_CHECK_EQ, open_spiel::SpielFatalError(), and absl::StrCat().
BoardAt()
CellState open_spiel::catch_::CatchState::BoardAt (int row, int column) const
Definition at line 103 of file catch.cc.
{
  if (row == num_rows_ - 1 && column == paddle_col_)
    return CellState::kPaddle;
  else if (row == ball_row_ && column == ball_col_)
    return CellState::kBall;
  return CellState::kEmpty;
}
References open_spiel::catch_::kBall, open_spiel::catch_::kEmpty, and open_spiel::catch_::kPaddle.
Referenced by ToString().
ChanceOutcomes()
ActionsAndProbs open_spiel::catch_::CatchState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 93 of file catch.cc.
{
  SPIEL_CHECK_TRUE(!initialized_);
  ActionsAndProbs action_and_probs;
  action_and_probs.reserve(num_columns_);
  for (int c = 0; c < num_columns_; c++) {
    action_and_probs.emplace_back(c, 1. / num_columns_);
  }
  return action_and_probs;
}
References SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::catch_::CatchState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 170 of file catch.cc.
{
  return std::unique_ptr<State>(new CatchState(*this));
}
References CatchState().
CurrentPlayer()
int open_spiel::catch_::CatchState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 76 of file catch.cc.
{
  if (!initialized_) return kChancePlayerId;
  if (IsTerminal()) return kTerminalPlayerId;
  return 0;
}
References IsTerminal(), open_spiel::kChancePlayerId, and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::catch_::CatchState::DoApplyAction (Action move) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 174 of file catch.cc.
{
  if (!initialized_) {
    initialized_ = true;
    ball_col_ = move;
    ball_row_ = 0;
    paddle_col_ = num_columns_ / 2;
  } else {
    ball_row_++;
    int direction = move - 1;
    paddle_col_ =
        std::min(std::max(paddle_col_ + direction, 0), num_columns_ - 1);
  }
}
IsTerminal()
bool open_spiel::catch_::CatchState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 138 of file catch.cc.
{
  return initialized_ && ball_row_ >= num_rows_ - 1;
}
Referenced by CurrentPlayer(), LegalActions(), and Returns().
LegalActions()
std::vector< Action > open_spiel::catch_::CatchState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 82 of file catch.cc.
{
  if (IsTerminal()) return {};
  if (initialized_) {
    return {0, 1, 2};  // Left, stay, right.
  }
  std::vector<Action> moves;
  moves.reserve(num_columns_);
  for (int i = 0; i < num_columns_; i++) moves.push_back(i);
  return moves;
}
References i, and IsTerminal().
ObservationString()
std::string open_spiel::catch_::CatchState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 152 of file catch.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::catch_::CatchState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 158 of file catch.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  TensorView<2> view(values, {num_rows_, num_columns_}, true);
  if (initialized_) {
    view[{ball_row_, ball_col_}] = 1.0;
    view[{num_rows_ - 1, paddle_col_}] = 1.0;
  }
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::catch_::CatchState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 142 of file catch.cc.
{
  if (!IsTerminal()) {
    return {0.0};
  } else if (ball_col_ == paddle_col_) {
    return {1.0};
  } else {
    return {-1.0};
  }
}
References IsTerminal().
ToString()
std::string open_spiel::catch_::CatchState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 127 of file catch.cc.
{
  std::string str;
  for (int r = 0; r < num_rows_; ++r) {
    for (int c = 0; c < num_columns_; ++c) {
      absl::StrAppend(&str, StateToString(BoardAt(r, c)));
    }
    absl::StrAppend(&str, "\n");
  }
  return str;
}
References BoardAt(), r, StateToString(), and absl::StrAppend().
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/catch/catch.h
open_spiel/games/catch/catch.cc