open spiel: absl::container_internal::btree_node< Params > Class Template Reference
absl::container_internal::btree_node< Params > Class Template Reference
#include <btree.h>
Public Types
using params_type = Params
using key_type = typename Params::key_type
using value_type = typename Params::value_type
using pointer = typename Params::pointer
using const_pointer = typename Params::const_pointer
using reference = typename Params::reference
using const_reference = typename Params::const_reference
using key_compare = typename Params::key_compare
using size_type = typename Params::size_type
using difference_type = typename Params::difference_type
using use_linear_search
Public Member Functions
~btree_node ()=default
btree_node (btree_node const &)=delete
btree_node & operator= (btree_node const &)=delete
bool is_leaf () const
bool is_internal () const
field_type position () const
field_type start () const
field_type finish () const
field_type count () const
field_type max_count () const
btree_node * parent () const
bool is_root () const
void make_root ()
uint32_t * get_root_generation () const
uint32_t generation () const
void set_generation (uint32_t generation)
void next_generation ()
const key_type & key (size_type i) const
reference value (size_type i)
const_reference value (size_type i) const
btree_node * child (field_type i) const
btree_node * start_child () const
btree_node *& mutable_child (field_type i)
void clear_child (field_type i)
void set_child (field_type i, btree_node *c)
void init_child (field_type i, btree_node *c)
template<typename K >
SearchResult< size_type, is_key_compare_to::value > lower_bound (const K &k, const key_compare &comp) const
template<typename K >
size_type upper_bound (const K &k, const key_compare &comp) const
template<typename K , typename Compare >
SearchResult< size_type, btree_is_key_compare_to< Compare, key_type >::value > linear_search (const K &k, const Compare &comp) const
template<typename K , typename Compare >
SearchResult< size_type, btree_is_key_compare_to< Compare, key_type >::value > binary_search (const K &k, const Compare &comp) const
template<typename K , typename Compare >
SearchResult< size_type, false > linear_search_impl (const K &k, size_type s, const size_type e, const Compare &comp, std::false_type) const
template<typename K , typename Compare >
SearchResult< size_type, true > linear_search_impl (const K &k, size_type s, const size_type e, const Compare &comp, std::true_type) const
template<typename K , typename Compare >
SearchResult< size_type, false > binary_search_impl (const K &k, size_type s, size_type e, const Compare &comp, std::false_type) const
template<typename K , typename CompareTo >
SearchResult< size_type, true > binary_search_impl (const K &k, size_type s, size_type e, const CompareTo &comp, std::true_type) const
template<typename... Args>
void emplace_value (field_type i, allocator_type *alloc, Args &&...args)
void remove_values (field_type i, field_type to_erase, allocator_type *alloc)
void rebalance_right_to_left (field_type to_move, btree_node *right, allocator_type *alloc)
void rebalance_left_to_right (field_type to_move, btree_node *right, allocator_type *alloc)
void split (int insert_position, btree_node *dest, allocator_type *alloc)
void merge (btree_node *src, allocator_type *alloc)
void init_leaf (field_type max_count, btree_node *parent)
void init_internal (btree_node *parent)
Static Public Member Functions
static constexpr size_type Alignment ()
static void deallocate (const size_type size, btree_node *node, allocator_type *alloc)
static void clear_and_delete (btree_node *node, allocator_type *alloc)
Protected Member Functions
btree_node ()=default
Friends
template<typename P >
class btree
template<typename N , typename R , typename P >
class btree_iterator
class BtreeNodePeer
struct btree_access
Detailed Description
template<typename Params>
class absl::container_internal::btree_node< Params >
Definition at line 491 of file btree.h.
Member Typedef Documentation
const_pointer
template<typename Params > using absl::container_internal::btree_node< Params >::const_pointer = typename Params::const_pointer
Definition at line 503 of file btree.h.
const_reference
template<typename Params > using absl::container_internal::btree_node< Params >::const_reference = typename Params::const_reference
Definition at line 505 of file btree.h.
difference_type
template<typename Params > using absl::container_internal::btree_node< Params >::difference_type = typename Params::difference_type
Definition at line 508 of file btree.h.
key_compare
template<typename Params > using absl::container_internal::btree_node< Params >::key_compare = typename Params::key_compare
Definition at line 506 of file btree.h.
key_type
template<typename Params > using absl::container_internal::btree_node< Params >::key_type = typename Params::key_type
Definition at line 500 of file btree.h.
params_type
template<typename Params > using absl::container_internal::btree_node< Params >::params_type = Params
Definition at line 499 of file btree.h.
pointer
template<typename Params > using absl::container_internal::btree_node< Params >::pointer = typename Params::pointer
Definition at line 502 of file btree.h.
reference
template<typename Params > using absl::container_internal::btree_node< Params >::reference = typename Params::reference
Definition at line 504 of file btree.h.
size_type
template<typename Params > using absl::container_internal::btree_node< Params >::size_type = typename Params::size_type
Definition at line 507 of file btree.h.
use_linear_search
template<typename Params > using absl::container_internal::btree_node< Params >::use_linear_search
Initial value:
 std::integral_constant<
      bool, has_linear_node_search_preference<original_key_compare>::value
                ? prefers_linear_node_search<original_key_compare>::value
            : has_linear_node_search_preference<key_type>::value
                ? prefers_linear_node_search<key_type>::value
                : std::is_arithmetic<key_type>::value &&
                      (std::is_same<std::less<key_type>,
                                    original_key_compare>::value ||
                       std::is_same<std::greater<key_type>,
                                    original_key_compare>::value)>
Definition at line 517 of file btree.h.
value_type
template<typename Params > using absl::container_internal::btree_node< Params >::value_type = typename Params::value_type
Definition at line 501 of file btree.h.
Constructor & Destructor Documentation
~btree_node()
template<typename Params > absl::container_internal::btree_node< Params >::~btree_node () default
btree_node() [1/2]
template<typename Params > absl::container_internal::btree_node< Params >::btree_node (btree_node< Params > const &) delete
btree_node() [2/2]
template<typename Params > absl::container_internal::btree_node< Params >::btree_node () protected default
Member Function Documentation
Alignment()
template<typename Params > static constexpr size_type absl::container_internal::btree_node< Params >::Alignment () inline static constexpr
Definition at line 576 of file btree.h.
{
    static_assert(LeafLayout(1).Alignment() == InternalLayout().Alignment(),
                  "Alignment of all nodes must be equal.");
    return InternalLayout().Alignment();
  }
binary_search()
template<typename Params > template<typename K , typename Compare > SearchResult< size_type, btree_is_key_compare_to< Compare, key_type >::value > absl::container_internal::btree_node< Params >::binary_search (const K & k, const Compare & comp) const inline
Definition at line 800 of file btree.h.
{
    return binary_search_impl(k, start(), finish(), comp,
                              btree_is_key_compare_to<Compare, key_type>());
  }
binary_search_impl() [1/2]
template<typename Params > template<typename K , typename Compare > SearchResult< size_type, false > absl::container_internal::btree_node< Params >::binary_search_impl (const K & k, size_type s, size_type e, const Compare & comp, std::false_type) const inline
Definition at line 841 of file btree.h.
{
    while (s != e) {
      const size_type mid = (s + e) >> 1;
      if (comp(key(mid), k)) {
        s = mid + 1;
      } else {
        e = mid;
      }
    }
    return SearchResult<size_type, false>{s};
  }
binary_search_impl() [2/2]
template<typename Params > template<typename K , typename CompareTo > SearchResult< size_type, true > absl::container_internal::btree_node< Params >::binary_search_impl (const K & k, size_type s, size_type e, const CompareTo & comp, std::true_type) const inline
Definition at line 858 of file btree.h.
{
    if (params_type::template can_have_multiple_equivalent_keys<K>()) {
      MatchKind exact_match = MatchKind::kNe;
      while (s != e) {
        const size_type mid = (s + e) >> 1;
        const absl::weak_ordering c = comp(key(mid), k);
        if (c < 0) {
          s = mid + 1;
        } else {
          e = mid;
          if (c == 0) {
            // Need to return the first value whose key is not less than k,
            // which requires continuing the binary search if there could be
            // multiple equivalent keys.
            exact_match = MatchKind::kEq;
          }
        }
      }
      return {s, exact_match};
    } else {  // Can't have multiple equivalent keys.
      while (s != e) {
        const size_type mid = (s + e) >> 1;
        const absl::weak_ordering c = comp(key(mid), k);
        if (c < 0) {
          s = mid + 1;
        } else if (c > 0) {
          e = mid;
        } else {
          return {mid, MatchKind::kEq};
        }
      }
      return {s, MatchKind::kNe};
    }
  }
child()
template<typename Params > btree_node * absl::container_internal::btree_node< Params >::child (field_type i) const inline
Definition at line 760 of file btree.h.
{ return GetField<4>()[i]; }
clear_and_delete()
template<typename P > void absl::container_internal::btree_node< P >::clear_and_delete (btree_node< Params > * node, allocator_type * alloc) static
Definition at line 1980 of file btree.h.
{
  if (node->is_leaf()) {
    node->value_destroy_n(node->start(), node->count(), alloc);
    deallocate(LeafSize(node->max_count()), node, alloc);
    return;
  }
  if (node->count() == 0) {
    deallocate(InternalSize(), node, alloc);
    return;
  }
  // The parent of the root of the subtree we are deleting.
  btree_node *delete_root_parent = node->parent();
  // Navigate to the leftmost leaf under node, and then delete upwards.
  while (node->is_internal()) node = node->start_child();
#ifdef ABSL_BTREE_ENABLE_GENERATIONS
  // When generations are enabled, we delete the leftmost leaf last in case it's
  // the parent of the root and we need to check whether it's a leaf before we
  // can update the root's generation.
  // TODO(ezb): if we change btree_node::is_root to check a bool inside the node
  // instead of checking whether the parent is a leaf, we can remove this logic.
  btree_node *leftmost_leaf = node;
#endif
  // Use `size_type` because `pos` needs to be able to hold `kNodeSlots+1`,
  // which isn't guaranteed to be a valid `field_type`.
  size_type pos = node->position();
  btree_node *parent = node->parent();
  for (;;) {
    // In each iteration of the next loop, we delete one leaf node and go right.
    assert(pos <= parent->finish());
    do {
      node = parent->child(static_cast<field_type>(pos));
      if (node->is_internal()) {
        // Navigate to the leftmost leaf under node.
        while (node->is_internal()) node = node->start_child();
        pos = node->position();
        parent = node->parent();
      }
      node->value_destroy_n(node->start(), node->count(), alloc);
#ifdef ABSL_BTREE_ENABLE_GENERATIONS
      if (leftmost_leaf != node)
#endif
        deallocate(LeafSize(node->max_count()), node, alloc);
      ++pos;
    } while (pos <= parent->finish());
    // Once we've deleted all children of parent, delete parent and go up/right.
    assert(pos > parent->finish());
    do {
      node = parent;
      pos = node->position();
      parent = node->parent();
      node->value_destroy_n(node->start(), node->count(), alloc);
      deallocate(InternalSize(), node, alloc);
      if (parent == delete_root_parent) {
#ifdef ABSL_BTREE_ENABLE_GENERATIONS
        deallocate(LeafSize(leftmost_leaf->max_count()), leftmost_leaf, alloc);
#endif
        return;
      }
      ++pos;
    } while (pos > parent->finish());
  }
}
clear_child()
template<typename Params > void absl::container_internal::btree_node< Params >::clear_child (field_type i) inline
Definition at line 763 of file btree.h.
{
    absl::container_internal::SanitizerPoisonObject(&mutable_child(i));
  }
count()
template<typename Params > field_type absl::container_internal::btree_node< Params >::count () const inline
Definition at line 705 of file btree.h.
{
    assert(finish() >= start());
    return finish() - start();
  }
Referenced by open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_add_to_queue_count_weighted(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_lcb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_ucb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_ucb_standard_factor(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::compute_total_steps(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::delta(), and open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::update_mean_and_count().
deallocate()
template<typename Params > static void absl::container_internal::btree_node< Params >::deallocate (const size_type size, btree_node< Params > * node, allocator_type * alloc) inline static
Definition at line 938 of file btree.h.
{
    absl::container_internal::SanitizerUnpoisonMemoryRegion(node, size);
    absl::container_internal::Deallocate<Alignment()>(alloc, node, size);
  }
emplace_value()
template<typename P > template<typename... Args> void absl::container_internal::btree_node< P >::emplace_value (field_type i, allocator_type * alloc, Args &&... args) inline
Definition at line 1779 of file btree.h.
{
  assert(i >= start());
  assert(i <= finish());
  // Shift old values to create space for new value and then construct it in
  // place.
  if (i < finish()) {
    transfer_n_backward(finish() - i, /*dest_i=*/i + 1, /*src_i=*/i, this,
                        alloc);
  }
  value_init(static_cast<field_type>(i), alloc, std::forward<Args>(args)...);
  set_finish(finish() + 1);
  if (is_internal() && finish() > i + 1) {
    for (field_type j = finish(); j > i + 1; --j) {
      set_child(j, child(j - 1));
    }
    clear_child(i + 1);
  }
}
finish()
template<typename Params > field_type absl::container_internal::btree_node< Params >::finish () const inline
Definition at line 702 of file btree.h.
{ return GetField<2>()[2]; }
generation()
template<typename Params > uint32_t absl::container_internal::btree_node< Params >::generation () const inline
Definition at line 739 of file btree.h.
{
    return params_type::kEnableGenerations ? *get_root_generation() : 0;
  }
get_root_generation()
template<typename Params > uint32_t * absl::container_internal::btree_node< Params >::get_root_generation () const inline
Definition at line 731 of file btree.h.
{
    assert(params_type::kEnableGenerations);
    const btree_node *curr = this;
    for (; !curr->is_root(); curr = curr->parent()) continue;
    return const_cast<uint32_t *>(&curr->GetField<1>()[0]);
  }
init_child()
template<typename Params > void absl::container_internal::btree_node< Params >::init_child (field_type i, btree_node< Params > * c) inline
Definition at line 771 of file btree.h.
{
    set_child(i, c);
    c->set_parent(this);
  }
init_internal()
template<typename Params > void absl::container_internal::btree_node< Params >::init_internal (btree_node< Params > * parent) inline
Definition at line 929 of file btree.h.
{
    init_leaf(kNodeSlots, parent);
    // Set `max_count` to a sentinel value to indicate that this node is
    // internal.
    set_max_count(kInternalNodeMaxCount);
    absl::container_internal::SanitizerPoisonMemoryRegion(
        &mutable_child(start()), (kNodeSlots + 1) * sizeof(btree_node *));
  }
init_leaf()
template<typename Params > void absl::container_internal::btree_node< Params >::init_leaf (field_type max_count, btree_node< Params > * parent) inline
Definition at line 919 of file btree.h.
{
    set_generation(0);
    set_parent(parent);
    set_position(0);
    set_start(0);
    set_finish(0);
    set_max_count(max_count);
    absl::container_internal::SanitizerPoisonMemoryRegion(
        start_slot(), max_count * sizeof(slot_type));
  }
is_internal()
template<typename Params > bool absl::container_internal::btree_node< Params >::is_internal () const inline
Definition at line 689 of file btree.h.
{ return !is_leaf(); }
is_leaf()
template<typename Params > bool absl::container_internal::btree_node< Params >::is_leaf () const inline
Definition at line 686 of file btree.h.
{ return GetField<2>()[3] != kInternalNodeMaxCount; }
is_root()
template<typename Params > bool absl::container_internal::btree_node< Params >::is_root () const inline
Definition at line 723 of file btree.h.
{ return parent()->is_leaf(); }
key()
template<typename Params > const key_type & absl::container_internal::btree_node< Params >::key (size_type i) const inline
Definition at line 753 of file btree.h.
{ return params_type::key(slot(i)); }
linear_search()
template<typename Params > template<typename K , typename Compare > SearchResult< size_type, btree_is_key_compare_to< Compare, key_type >::value > absl::container_internal::btree_node< Params >::linear_search (const K & k, const Compare & comp) const inline
Definition at line 793 of file btree.h.
{
    return linear_search_impl(k, start(), finish(), comp,
                              btree_is_key_compare_to<Compare, key_type>());
  }
linear_search_impl() [1/2]
template<typename Params > template<typename K , typename Compare > SearchResult< size_type, false > absl::container_internal::btree_node< Params >::linear_search_impl (const K & k, size_type s, const size_type e, const Compare & comp, std::false_type) const inline
Definition at line 808 of file btree.h.
{
    while (s < e) {
      if (!comp(key(s), k)) {
        break;
      }
      ++s;
    }
    return SearchResult<size_type, false>{s};
  }
linear_search_impl() [2/2]
template<typename Params > template<typename K , typename Compare > SearchResult< size_type, true > absl::container_internal::btree_node< Params >::linear_search_impl (const K & k, size_type s, const size_type e, const Compare & comp, std::true_type) const inline
Definition at line 823 of file btree.h.
{
    while (s < e) {
      const absl::weak_ordering c = comp(key(s), k);
      if (c == 0) {
        return {s, MatchKind::kEq};
      } else if (c > 0) {
        break;
      }
      ++s;
    }
    return {s, MatchKind::kNe};
  }
lower_bound()
template<typename Params > template<typename K > SearchResult< size_type, is_key_compare_to::value > absl::container_internal::btree_node< Params >::lower_bound (const K & k, const key_compare & comp) const inline
Definition at line 778 of file btree.h.
{
    return use_linear_search::value ? linear_search(k, comp)
                                    : binary_search(k, comp);
  }
make_root()
template<typename Params > void absl::container_internal::btree_node< Params >::make_root () inline
Definition at line 724 of file btree.h.
                   {
    assert(parent()->is_root());
    set_generation(parent()->generation());
    set_parent(parent()->parent());
  }
max_count()
template<typename Params > field_type absl::container_internal::btree_node< Params >::max_count () const inline
Definition at line 709 of file btree.h.
{
    // Internal nodes have max_count==kInternalNodeMaxCount.
    // Leaf nodes have max_count in [1, kNodeSlots].
    const field_type max_count = GetField<2>()[3];
    return max_count == field_type{kInternalNodeMaxCount}
               ? field_type{kNodeSlots}
               : max_count;
  }
merge()
template<typename P > void absl::container_internal::btree_node< P >::merge (btree_node< Params > * src, allocator_type * alloc)
Definition at line 1952 of file btree.h.
{
  assert(parent() == src->parent());
  assert(position() + 1 == src->position());
  // Move the delimiting value to the left node.
  value_init(finish(), alloc, parent()->slot(position()));
  // Move the values from the right to the left node.
  transfer_n(src->count(), finish() + 1, src->start(), src, alloc);
  if (is_internal()) {
    // Move the child pointers from the right to the left node.
    for (field_type i = src->start(), j = finish() + 1; i <= src->finish();
         ++i, ++j) {
      init_child(j, src->child(i));
      src->clear_child(i);
    }
  }
  // Fixup `finish` on the src and dest nodes.
  set_finish(start() + 1 + count() + src->count());
  src->set_finish(src->start());
  // Remove the value on the parent node and delete the src node.
  parent()->remove_values(position(), /*to_erase=*/1, alloc);
}
mutable_child()
template<typename Params > btree_node *& absl::container_internal::btree_node< Params >::mutable_child (field_type i) inline
Definition at line 762 of file btree.h.
{ return GetField<4>()[i]; }
next_generation()
template<typename Params > void absl::container_internal::btree_node< Params >::next_generation () inline
Definition at line 748 of file btree.h.
{
    if (params_type::kEnableGenerations) ++*get_root_generation();
  }
operator=()
template<typename Params > btree_node & absl::container_internal::btree_node< Params >::operator= (btree_node< Params > const &) delete
parent()
template<typename Params > btree_node * absl::container_internal::btree_node< Params >::parent () const inline
Definition at line 719 of file btree.h.
{ return *GetField<0>(); }
position()
template<typename Params > field_type absl::container_internal::btree_node< Params >::position () const inline
Definition at line 692 of file btree.h.
{ return GetField<2>()[0]; }
rebalance_left_to_right()
template<typename P > void absl::container_internal::btree_node< P >::rebalance_left_to_right (field_type to_move, btree_node< Params > * right, allocator_type * alloc)
Definition at line 1866 of file btree.h.
{
  assert(parent() == right->parent());
  assert(position() + 1 == right->position());
  assert(count() >= right->count());
  assert(to_move >= 1);
  assert(to_move <= count());
  // Values in the right node are shifted to the right to make room for the
  // new to_move values. Then, the delimiting value in the parent and the
  // other (to_move - 1) values in the left node are moved into the right node.
  // Lastly, a new delimiting value is moved from the left node into the
  // parent, and the remaining empty left node entries are destroyed.
  // 1) Shift existing values in the right node to their correct positions.
  right->transfer_n_backward(right->count(), right->start() + to_move,
                             right->start(), right, alloc);
  // 2) Move the delimiting value in the parent to the right node.
  right->transfer(right->start() + to_move - 1, position(), parent(), alloc);
  // 3) Move the (to_move - 1) values from the left node to the right node.
  right->transfer_n(to_move - 1, right->start(), finish() - (to_move - 1), this,
                    alloc);
  // 4) Move the new delimiting value to the parent from the left node.
  parent()->transfer(position(), finish() - to_move, this, alloc);
  if (is_internal()) {
    // Move the child pointers from the left to the right node.
    for (field_type i = right->finish() + 1; i > right->start(); --i) {
      right->init_child(i - 1 + to_move, right->child(i - 1));
      right->clear_child(i - 1);
    }
    for (field_type i = 1; i <= to_move; ++i) {
      right->init_child(i - 1, child(finish() - to_move + i));
      clear_child(finish() - to_move + i);
    }
  }
  // Fixup the counts on the left and right nodes.
  set_finish(finish() - to_move);
  right->set_finish(right->finish() + to_move);
}
rebalance_right_to_left()
template<typename P > void absl::container_internal::btree_node< P >::rebalance_right_to_left (field_type to_move, btree_node< Params > * right, allocator_type * alloc)
Definition at line 1826 of file btree.h.
{
  assert(parent() == right->parent());
  assert(position() + 1 == right->position());
  assert(right->count() >= count());
  assert(to_move >= 1);
  assert(to_move <= right->count());
  // 1) Move the delimiting value in the parent to the left node.
  transfer(finish(), position(), parent(), alloc);
  // 2) Move the (to_move - 1) values from the right node to the left node.
  transfer_n(to_move - 1, finish() + 1, right->start(), right, alloc);
  // 3) Move the new delimiting value to the parent from the right node.
  parent()->transfer(position(), right->start() + to_move - 1, right, alloc);
  // 4) Shift the values in the right node to their correct positions.
  right->transfer_n(right->count() - to_move, right->start(),
                    right->start() + to_move, right, alloc);
  if (is_internal()) {
    // Move the child pointers from the right to the left node.
    for (field_type i = 0; i < to_move; ++i) {
      init_child(finish() + i + 1, right->child(i));
    }
    for (field_type i = right->start(); i <= right->finish() - to_move; ++i) {
      assert(i + to_move <= right->max_count());
      right->init_child(i, right->child(i + to_move));
      right->clear_child(i + to_move);
    }
  }
  // Fixup `finish` on the left and right nodes.
  set_finish(finish() + to_move);
  right->set_finish(right->finish() - to_move);
}
remove_values()
template<typename P > void absl::container_internal::btree_node< P >::remove_values (field_type i, field_type to_erase, allocator_type * alloc) inline
Definition at line 1802 of file btree.h.
{
  // Transfer values after the removed range into their new places.
  value_destroy_n(i, to_erase, alloc);
  const field_type orig_finish = finish();
  const field_type src_i = i + to_erase;
  transfer_n(orig_finish - src_i, i, src_i, this, alloc);
  if (is_internal()) {
    // Delete all children between begin and end.
    for (field_type j = 0; j < to_erase; ++j) {
      clear_and_delete(child(i + j + 1), alloc);
    }
    // Rotate children after end into new positions.
    for (field_type j = i + to_erase + 1; j <= orig_finish; ++j) {
      set_child(j - to_erase, child(j));
      clear_child(j);
    }
  }
  set_finish(orig_finish - to_erase);
}
set_child()
template<typename Params > void absl::container_internal::btree_node< Params >::set_child (field_type i, btree_node< Params > * c) inline
Definition at line 766 of file btree.h.
{
    absl::container_internal::SanitizerUnpoisonObject(&mutable_child(i));
    mutable_child(i) = c;
    c->set_position(i);
  }
set_generation()
template<typename Params > void absl::container_internal::btree_node< Params >::set_generation (uint32_t generation) inline
Definition at line 744 of file btree.h.
{
    if (params_type::kEnableGenerations) GetField<1>()[0] = generation;
  }
split()
template<typename P > void absl::container_internal::btree_node< P >::split (int insert_position, btree_node< Params > * dest, allocator_type * alloc)
Definition at line 1913 of file btree.h.
{
  assert(dest->count() == 0);
  assert(max_count() == kNodeSlots);
  // We bias the split based on the position being inserted. If we're
  // inserting at the beginning of the left node then bias the split to put
  // more values on the right node. If we're inserting at the end of the
  // right node then bias the split to put more values on the left node.
  if (insert_position == start()) {
    dest->set_finish(dest->start() + finish() - 1);
  } else if (insert_position == kNodeSlots) {
    dest->set_finish(dest->start());
  } else {
    dest->set_finish(dest->start() + count() / 2);
  }
  set_finish(finish() - dest->count());
  assert(count() >= 1);
  // Move values from the left sibling to the right sibling.
  dest->transfer_n(dest->count(), dest->start(), finish(), this, alloc);
  // The split key is the largest value in the left sibling.
  --mutable_finish();
  parent()->emplace_value(position(), alloc, finish_slot());
  value_destroy(finish(), alloc);
  parent()->init_child(position() + 1, dest);
  if (is_internal()) {
    for (field_type i = dest->start(), j = finish() + 1; i <= dest->finish();
         ++i, ++j) {
      assert(child(j) != nullptr);
      dest->init_child(i, child(j));
      clear_child(j);
    }
  }
}
start()
template<typename Params > field_type absl::container_internal::btree_node< Params >::start () const inline
Definition at line 695 of file btree.h.
{
    // TODO(ezb): when floating storage is implemented, return GetField<2>()[1];
    assert(GetField<2>()[1] == 0);
    return 0;
  }
start_child()
template<typename Params > btree_node * absl::container_internal::btree_node< Params >::start_child () const inline
Definition at line 761 of file btree.h.
{ return child(start()); }
upper_bound()
template<typename Params > template<typename K > size_type absl::container_internal::btree_node< Params >::upper_bound (const K & k, const key_compare & comp) const inline
Definition at line 785 of file btree.h.
{
    auto upper_compare = upper_bound_adapter<key_compare>(comp);
    return use_linear_search::value ? linear_search(k, upper_compare).value
                                    : binary_search(k, upper_compare).value;
  }
value() [1/2]
template<typename Params > reference absl::container_internal::btree_node< Params >::value (size_type i) inline
Definition at line 754 of file btree.h.
{ return params_type::element(slot(i)); }
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
value() [2/2]
template<typename Params > const_reference absl::container_internal::btree_node< Params >::value (size_type i) const inline
Definition at line 755 of file btree.h.
{
    return params_type::element(slot(i));
  }
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
Friends And Related Symbol Documentation
btree
template<typename Params > template<typename P > friend class btree friend
Definition at line 1013 of file btree.h.
btree_access
template<typename Params > friend struct btree_access friend
Definition at line 1017 of file btree.h.
btree_iterator
template<typename Params > template<typename N , typename R , typename P > friend class btree_iterator friend
Definition at line 1015 of file btree.h.
BtreeNodePeer
template<typename Params > friend class BtreeNodePeer friend
Definition at line 1016 of file btree.h.
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/btree.h