open spiel: open_spiel.python.policy.TabularPolicy Class Reference
open_spiel.python.policy.TabularPolicy Class Reference
Public Member Functions
__init__ (self, game, players=None, to_string=lambda s:s.history_str(), states=None)
action_probabilities (self, state, player_id=None)
state_index (self, state)
policy_for_key (self, key)
to_dict (self)
__copy__ (self, copy_action_probability_array=True)
copy_with_noise (self, alpha=0.0, beta=0.0, random_state=np.random.RandomState())
Public Member Functions inherited from open_spiel.python.policy.Policy
__call__ (self, state, player_id=None)
to_tabular (self, states=None)
Public Attributes
game_type
state_lookup
states_per_player
states
state_in
legal_actions_mask
action_probability_array
Public Attributes inherited from open_spiel.python.policy.Policy
game
player_ids
Protected Member Functions
_state_key (self, state, player)
Detailed Description
Policy implementation where the policy is in explicit tabular form.
In addition to implementing the `Policy` interface, this class exposes
details of the policy representation for easy manipulation.
The states are guaranteed to be grouped by player, which can simplify
code for users of this class, i.e. `action_probability_array` contains
states for player 0 first, followed by states for player 1, etc.
The policy uses `state.information_state_string` as the keys if available,
otherwise `state.observation_string`.
Usages:
- Set `policy(info_state, action)`:
```
tabular_policy = TabularPolicy(game)
info_state_str = state.information_state_string(<optional player>)
state_policy = tabular_policy.policy_for_key(info_state_str)
state_policy[action] = <value>
```
- Set `policy(info_state)`:
```
tabular_policy = TabularPolicy(game)
info_state_str = state.information_state_string(<optional player>)
state_policy = tabular_policy.policy_for_key(info_state_str)
state_policy[:] = <list or numpy.array>
```
Attributes:
  action_probability_array: array of shape `(num_states, num_actions)`, where
    `action_probability_array[s, a]` is the probability of choosing action `a`
    when at state `s`.
  state_lookup: `dict` mapping state key string to index into the
    `tabular_policy` array. If information state strings overlap, e.g. for
    different players or if the information state string has imperfect recall,
    then those states will be mapped to the same policy.
  legal_actions_mask: array of shape `(num_states, num_actions)`, each row
    representing which of the possible actions in the game are valid in this
    particular state, containing 1 for valid actions, 0 for invalid actions.
  states_per_player: A `list` per player of the state key strings at which
    they have a decision to make.
  states: A `list` of the states as ordered in the `action_probability_array`.
  state_in: array of shape `(num_states, state_vector_size)` containing the
    normalised vector representation of each information state. Populated only
    for games which support information_state_tensor(), and is None otherwise.
  game_type: The game attributes as returned by `Game::GetType`; used to
    determine whether to use information state or observation as the key in
    the tabular policy.
Definition at line 178 of file policy.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.policy.TabularPolicy.__init__ (self, game, players = None, to_string = lambda s: s.history_str(), states = None)
Initializes a uniform random policy for all players in the game.
Reimplemented from open_spiel.python.policy.Policy.
Definition at line 230 of file policy.py.
               states=None):
    """Initializes a uniform random policy for all players in the game."""
    players = sorted(players or range(game.num_players()))
    super().__init__(game, players)
    self.game_type = game.get_type()
    # Get all states in the game at which players have to make decisions unless
    # they are explicitly specified.
    states = states or get_all_states.get_all_states(
        game,
        depth_limit=-1,
        include_terminals=False,
        include_chance_states=False,
        include_mean_field_states=False,
        to_string=to_string)
    # Assemble legal actions for every valid (state, player) pair, keyed by
    # information state string.
    self.state_lookup = {}
    self.states_per_player = [[] for _ in range(game.num_players())]
    self.states = []
    legal_actions_list = []
    state_in_list = []
    for player in players:
      # States are ordered by their history.
      for _, state in sorted(states.items(), key=lambda pair: pair[0]):
        if state.is_simultaneous_node() or player == state.current_player():
          legal_actions = state.legal_actions_mask(player)
          if any(legal_actions):
            key = self._state_key(state, player)
            if key not in self.state_lookup:
              state_index = len(legal_actions_list)
              self.state_lookup[key] = state_index
              legal_actions_list.append(legal_actions)
              self.states_per_player[player].append(key)
              self.states.append(state)
              if self.game_type.provides_information_state_tensor:
                state_in_list.append(state.information_state_tensor(player))
              elif self.game_type.provides_observation_tensor:
                state_in_list.append(state.observation_tensor(player))
    # Put legal action masks in a numpy array and create the uniform random
    # policy.
    self.state_in = None
    if state_in_list:
      self.state_in = np.array(state_in_list)
    self.legal_actions_mask = np.array(legal_actions_list)
    self.action_probability_array = (
        self.legal_actions_mask /
        np.sum(self.legal_actions_mask, axis=-1, keepdims=True))
References open_spiel.python.policy.TabularPolicy.__init__().
Referenced by open_spiel.python.policy.TabularPolicy.__init__().
Member Function Documentation
__copy__()
open_spiel.python.policy.TabularPolicy.__copy__ (self, copy_action_probability_array = True)
Returns a shallow copy of self.
Most class attributes will be pointers to the copied object's attributes,
and therefore altering them could lead to unexpected behavioural changes.
Only action_probability_array is expected to be modified.
Args:
  copy_action_probability_array: Whether to also include
    action_probability_array in the copy operation.
Returns:
  Copy.
Definition at line 341 of file policy.py.
  def __copy__(self, copy_action_probability_array=True):
    """Returns a shallow copy of self.
    Most class attributes will be pointers to the copied object's attributes,
    and therefore altering them could lead to unexpected behavioural changes.
    Only action_probability_array is expected to be modified.
    Args:
      copy_action_probability_array: Whether to also include
        action_probability_array in the copy operation.
    Returns:
      Copy.
    """
    result = TabularPolicy.__new__(TabularPolicy)
    result.state_lookup = self.state_lookup
    result.game_type = self.game_type
    result.legal_actions_mask = self.legal_actions_mask
    result.state_in = self.state_in
    result.state_lookup = self.state_lookup
    result.states_per_player = self.states_per_player
    result.states = self.states
    result.game = self.game
    result.player_ids = self.player_ids
    if copy_action_probability_array:
      result.action_probability_array = np.copy(self.action_probability_array)
    return result
References open_spiel.python.policy.TabularPolicy.action_probability_array, open_spiel.python.policy.Policy.game, open_spiel.python.rl_environment.Environment.game(), open_spiel.python.policy.TabularPolicy.game_type, open_spiel.python.policy.TabularPolicy.legal_actions_mask, open_spiel.python.policy.Policy.player_ids, open_spiel.python.policy.TabularPolicy.state_in, open_spiel.python.policy.TabularPolicy.state_lookup, open_spiel.python.policy.TabularPolicy.states, and open_spiel.python.policy.TabularPolicy.states_per_player.
Referenced by open_spiel.python.policy.TabularPolicy.copy_with_noise().
_state_key()
open_spiel.python.policy.TabularPolicy._state_key (self, state, player) protected
Returns the key to use to look up this (state, player) pair.
Definition at line 285 of file policy.py.
  def _state_key(self, state, player):
    """Returns the key to use to look up this (state, player) pair."""
    if self.game_type.provides_information_state_string:
      if player is None:
        return state.information_state_string()
      return state.information_state_string(player)
    if self.game_type.provides_observation_string:
      if player is None:
        return state.observation_string()
      return state.observation_string(player)
    return str(state)
References open_spiel.python.policy.TabularPolicy.game_type.
Referenced by open_spiel.python.policy.TabularPolicy.action_probabilities(), and open_spiel.python.policy.TabularPolicy.state_index().
action_probabilities()
open_spiel.python.policy.TabularPolicy.action_probabilities (self, state, player_id = None)
Returns an {action: probability} dict, covering all legal actions.
Reimplemented from open_spiel.python.policy.Policy.
Definition at line 297 of file policy.py.
  def action_probabilities(self, state, player_id=None):
    """Returns an {action: probability} dict, covering all legal actions."""
    legal_actions = (
        state.legal_actions()
        if player_id is None else state.legal_actions(player_id))
    if not legal_actions:
      return {0: 1.0}
    probability = self.policy_for_key(self._state_key(state, player_id))
    return {action: probability[action] for action in legal_actions}
References open_spiel.python.policy.TabularPolicy._state_key(), and open_spiel.python.policy.TabularPolicy.policy_for_key().
Referenced by open_spiel.python.policy.Policy.__call__(), and open_spiel.python.policy.Policy.to_tabular().
copy_with_noise()
open_spiel.python.policy.TabularPolicy.copy_with_noise (self, alpha = 0.0, beta = 0.0, random_state = np.random.RandomState())
Returns a copy of this policy perturbed with noise.
Generates a new random distribution using a softmax on normal random
variables with temperature beta, and mixes it with the old distribution
using 1-alpha * old_distribution + alpha * random_distribution.
Args:
  alpha: Parameter characterizing the mixture amount between new and old
    distributions. Between 0 and 1.
    alpha = 0: keep old table.
    alpha = 1: keep random table.
  beta: Temperature of the softmax. Makes for more extreme policies.
  random_state: A numpy `RandomState` object. If not provided, a shared
    random state will be used.
Returns:
  Perturbed copy.
Definition at line 369 of file policy.py.
                      random_state=np.random.RandomState()):
    """Returns a copy of this policy perturbed with noise.
    Generates a new random distribution using a softmax on normal random
    variables with temperature beta, and mixes it with the old distribution
    using 1-alpha * old_distribution + alpha * random_distribution.
    Args:
      alpha: Parameter characterizing the mixture amount between new and old
        distributions. Between 0 and 1.
        alpha = 0: keep old table.
        alpha = 1: keep random table.
      beta: Temperature of the softmax. Makes for more extreme policies.
      random_state: A numpy `RandomState` object. If not provided, a shared
        random state will be used.
    Returns:
      Perturbed copy.
    """
    copied_instance = self.__copy__(False)
    probability_array = self.action_probability_array
    noise_mask = random_state.normal(size=probability_array.shape)
    noise_mask = np.exp(beta * noise_mask) * self.legal_actions_mask
    noise_mask = noise_mask / (np.sum(noise_mask, axis=1).reshape(-1, 1))
    copied_instance.action_probability_array = (
        1 - alpha) * probability_array + alpha * noise_mask
    return copied_instance
References open_spiel.python.policy.TabularPolicy.__copy__(), open_spiel.python.policy.TabularPolicy.action_probability_array, and open_spiel.python.policy.TabularPolicy.legal_actions_mask.
policy_for_key()
open_spiel.python.policy.TabularPolicy.policy_for_key (self, key)
Returns the policy as a vector given a state key string.
Args:
  key: A key for the specified state.
Returns:
  A vector of probabilities, one per action. This is a slice of the
  backing policy array, and so slice or index assignment will update the
  policy. For example:
  ```
  tabular_policy.policy_for_key(s)[:] = [0.1, 0.5, 0.4]
  ```
Definition at line 311 of file policy.py.
  def policy_for_key(self, key):
    """Returns the policy as a vector given a state key string.
    Args:
      key: A key for the specified state.
    Returns:
      A vector of probabilities, one per action. This is a slice of the
      backing policy array, and so slice or index assignment will update the
      policy. For example:
      ```
      tabular_policy.policy_for_key(s)[:] = [0.1, 0.5, 0.4]
      ```
    """
    return self.action_probability_array[self.state_lookup[key]]
References open_spiel.python.policy.TabularPolicy.action_probability_array, and open_spiel.python.policy.TabularPolicy.state_lookup.
Referenced by open_spiel.python.policy.TabularPolicy.action_probabilities().
state_index()
open_spiel.python.policy.TabularPolicy.state_index (self, state)
Returns the index in the TabularPolicy associated to `state`.
Definition at line 307 of file policy.py.
  def state_index(self, state):
    """Returns the index in the TabularPolicy associated to `state`."""
    return self.state_lookup[self._state_key(state, state.current_player())]
References open_spiel.python.policy.TabularPolicy._state_key(), and open_spiel.python.policy.TabularPolicy.state_lookup.
to_dict()
open_spiel.python.policy.TabularPolicy.to_dict (self)
Returns a single dictionary representing the tabular policy.
Returns:
  A dictionary of string keys to lists of (action, prob) pairs.
Definition at line 327 of file policy.py.
  def to_dict(self):
    """Returns a single dictionary representing the tabular policy.
    Returns:
      A dictionary of string keys to lists of (action, prob) pairs.
    """
    policy_dict = {}
    num_actions = self.action_probability_array.shape[1]
    for infostate_key, index in self.state_lookup.items():
      probs = self.action_probability_array[index]
      actions_and_probs = [(a, probs[a]) for a in range(num_actions)]
      policy_dict[infostate_key] = actions_and_probs
    return policy_dict
References open_spiel.python.policy.TabularPolicy.action_probability_array, and open_spiel.python.policy.TabularPolicy.state_lookup.
Member Data Documentation
action_probability_array
open_spiel.python.policy.TabularPolicy.action_probability_array
Definition at line 281 of file policy.py.
Referenced by open_spiel.python.policy.TabularPolicy.__copy__(), open_spiel.python.policy.TabularPolicy.copy_with_noise(), open_spiel.python.policy.TabularPolicy.policy_for_key(), and open_spiel.python.policy.TabularPolicy.to_dict().
game_type
open_spiel.python.policy.TabularPolicy.game_type
Definition at line 238 of file policy.py.
Referenced by open_spiel.python.policy.TabularPolicy.__copy__(), and open_spiel.python.policy.TabularPolicy._state_key().
legal_actions_mask
open_spiel.python.policy.TabularPolicy.legal_actions_mask
Definition at line 280 of file policy.py.
Referenced by open_spiel.python.policy.TabularPolicy.__copy__(), and open_spiel.python.policy.TabularPolicy.copy_with_noise().
state_in
open_spiel.python.policy.TabularPolicy.state_in
Definition at line 277 of file policy.py.
Referenced by open_spiel.python.policy.TabularPolicy.__copy__().
state_lookup
open_spiel.python.policy.TabularPolicy.state_lookup
Definition at line 252 of file policy.py.
Referenced by open_spiel.python.policy.TabularPolicy.__copy__(), open_spiel.python.policy.TabularPolicy.policy_for_key(), open_spiel.python.policy.TabularPolicy.state_index(), and open_spiel.python.policy.TabularPolicy.to_dict().
states
open_spiel.python.policy.TabularPolicy.states
Definition at line 254 of file policy.py.
Referenced by open_spiel.python.policy.TabularPolicy.__copy__().
states_per_player
open_spiel.python.policy.TabularPolicy.states_per_player
Definition at line 253 of file policy.py.
Referenced by open_spiel.python.policy.TabularPolicy.__copy__().
The documentation for this class was generated from the following file:
open_spiel/python/policy.py