open spiel: open_spiel::crowd_modelling_2d::CrowdModelling2dGame Class Reference
open_spiel::crowd_modelling_2d::CrowdModelling2dGame Class Reference
#include <crowd_modelling_2d.h>
Public Member Functions
CrowdModelling2dGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
int MaxGameLength () const override
int MaxChanceNodesInHistory () const override
std::vector< int > ObservationTensorShape () const override
int MaxChanceOutcomes () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 174 of file crowd_modelling_2d.h.
Constructor & Destructor Documentation
CrowdModelling2dGame()
open_spiel::crowd_modelling_2d::CrowdModelling2dGame::CrowdModelling2dGame (const GameParameters & params) explicit
Definition at line 506 of file crowd_modelling_2d.cc.
    : Game(kGameType, params),
      size_(ParameterValue<int>("size", kDefaultSize)),
      horizon_(ParameterValue<int>("horizon", kDefaultHorizon)),
      only_distribution_reward_(ParameterValue<bool>(
          "only_distribution_reward", kDefaultOnlyDistributionReward)),
      forbidden_states_(ParameterValue<std::string>("forbidden_states",
                                                    kDefaultForbiddenStates)),
      initial_distribution_(ParameterValue<std::string>(
          "initial_distribution", kDefaultInitialDistribution)),
      initial_distribution_value_(ParameterValue<std::string>(
          "initial_distribution_value", kDefaultInitialDistributionValue)),
      positional_reward_(ParameterValue<std::string>("positional_reward",
                                                     kDefaultPositionalReward)),
      positional_reward_value_(ParameterValue<std::string>(
          "positional_reward_value", kDefaultPositionalRewardValue)),
      with_congestion_(
          ParameterValue<bool>("with_congestion", kDefaultWithCongestion)),
      noise_intensity_(
          ParameterValue<double>("noise_intensity", kDefaultNoiseIntensity)),
      crowd_aversion_coef_(ParameterValue<double>("crowd_aversion_coef",
                                                  kDefaultCrowdAversionCoef)) {}
Member Function Documentation
DeserializeState()
std::unique_ptr< State > open_spiel::crowd_modelling_2d::CrowdModelling2dGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 534 of file crowd_modelling_2d.cc.
{
  std::vector<std::string> lines = absl::StrSplit(str, '\n');
  if (lines.size() != 2) {
    SpielFatalError(absl::StrCat("Expected 2 lines in serialized state, got: ",
                                 lines.size()));
  }
  Player current_player;
  int is_chance_init, x, y, t, last_action;
  double return_value;
  std::vector<double> distribution;
  std::vector<std::string> properties = absl::StrSplit(lines[0], ',');
  if (properties.size() != 7) {
    SpielFatalError(
        absl::StrCat("Expected 7 properties for serialized state, got: ",
                     properties.size()));
  }
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[0], &current_player));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[1], &is_chance_init));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[2], &x));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[3], &y));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[4], &t));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[5], &last_action));
  SPIEL_CHECK_TRUE(absl::SimpleAtod(properties[6], &return_value));
  std::vector<std::string> serialized_distrib = absl::StrSplit(lines[1], ',');
  distribution.reserve(serialized_distrib.size());
  for (std::string& v : serialized_distrib) {
    double parsed_weight;
    SPIEL_CHECK_TRUE(absl::SimpleAtod(v, &parsed_weight));
    distribution.push_back(parsed_weight);
  }
  return absl::make_unique<CrowdModelling2dState>(
      shared_from_this(), size_, horizon_, only_distribution_reward_,
      forbidden_states_, initial_distribution_, initial_distribution_value_,
      positional_reward_, positional_reward_value_, current_player,
      is_chance_init, x, y, t, last_action, return_value, distribution,
      with_congestion_, noise_intensity_, crowd_aversion_coef_);
}
References absl::SimpleAtod(), absl::SimpleAtoi(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), absl::StrCat(), absl::StrSplit(), x, and y.
MaxChanceNodesInHistory()
int open_spiel::crowd_modelling_2d::CrowdModelling2dGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 193 of file crowd_modelling_2d.h.
{
    // + 1 to account for the initial extra chance node.
    return horizon_ + 1;
  }
MaxChanceOutcomes()
int open_spiel::crowd_modelling_2d::CrowdModelling2dGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 198 of file crowd_modelling_2d.h.
{
    return std::max(size_ * size_, kNumChanceActions);
  }
References open_spiel::crowd_modelling_2d::kNumChanceActions.
MaxGameLength()
int open_spiel::crowd_modelling_2d::CrowdModelling2dGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 192 of file crowd_modelling_2d.h.
{ return horizon_; }
MaxUtility()
double open_spiel::crowd_modelling_2d::CrowdModelling2dGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 189 of file crowd_modelling_2d.h.
{
    return std::numeric_limits<double>::infinity();
  }
MinUtility()
double open_spiel::crowd_modelling_2d::CrowdModelling2dGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 186 of file crowd_modelling_2d.h.
{
    return -std::numeric_limits<double>::infinity();
  }
NewInitialState()
std::unique_ptr< State > open_spiel::crowd_modelling_2d::CrowdModelling2dGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 178 of file crowd_modelling_2d.h.
{
    return absl::make_unique<CrowdModelling2dState>(
        shared_from_this(), size_, horizon_, only_distribution_reward_,
        forbidden_states_, initial_distribution_, initial_distribution_value_,
        positional_reward_, positional_reward_value_, with_congestion_,
        noise_intensity_, crowd_aversion_coef_);
  }
NumDistinctActions()
int open_spiel::crowd_modelling_2d::CrowdModelling2dGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 177 of file crowd_modelling_2d.h.
{ return kNumActions; }
References open_spiel::crowd_modelling_2d::kNumActions.
NumPlayers()
int open_spiel::crowd_modelling_2d::CrowdModelling2dGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 185 of file crowd_modelling_2d.h.
{ return kNumPlayers; }
References open_spiel::crowd_modelling_2d::kNumPlayers.
ObservationTensorShape()
std::vector< int > open_spiel::crowd_modelling_2d::CrowdModelling2dGame::ObservationTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 529 of file crowd_modelling_2d.cc.
{
  // +1 to allow for t_ == horizon.
  return {2 * ParameterValue<int>("size") + ParameterValue<int>("horizon") + 1};
}
References open_spiel::Game::ParameterValue().
The documentation for this class was generated from the following files:
open_spiel/games/mfg/crowd_modelling_2d.h
open_spiel/games/mfg/crowd_modelling_2d.cc