open spiel: absl::Duration Class Reference
absl::Duration Class Reference
#include <time.h>
Public Member Functions
constexpr Duration ()
constexpr Duration (const Duration &d)=default
Duration & operator= (const Duration &d)=default
Duration & operator+= (Duration d)
Duration & operator-= (Duration d)
Duration & operator*= (int64_t r)
Duration & operator*= (double r)
Duration & operator/= (int64_t r)
Duration & operator/= (double r)
Duration & operator%= (Duration rhs)
template<typename T , time_internal::EnableIfIntegral< T > = 0>
Duration & operator*= (T r)
template<typename T , time_internal::EnableIfIntegral< T > = 0>
Duration & operator/= (T r)
template<typename T , time_internal::EnableIfFloat< T > = 0>
Duration & operator*= (T r)
template<typename T , time_internal::EnableIfFloat< T > = 0>
Duration & operator/= (T r)
Friends
template<typename H >
H AbslHashValue (H h, Duration d)
constexpr int64_t time_internal::GetRepHi (Duration d)
constexpr uint32_t time_internal::GetRepLo (Duration d)
constexpr Duration time_internal::MakeDuration (int64_t hi, uint32_t lo)
Detailed Description
Definition at line 165 of file time.h.
Constructor & Destructor Documentation
Duration() [1/2]
absl::Duration::Duration () inline constexpr
Definition at line 168 of file time.h.
: rep_hi_(0), rep_lo_(0) {}  // zero-length duration
Duration() [2/2]
absl::Duration::Duration (const Duration & d) constexpr default
Member Function Documentation
operator%=()
Duration & absl::Duration::operator%= (Duration rhs)
Definition at line 479 of file duration.cc.
{
  time_internal::IDivDuration(false, *this, rhs, this);
  return *this;
}
References absl::time_internal::IDivDuration().
operator*=() [1/4]
Duration & absl::Duration::operator*= (double r)
Definition at line 455 of file duration.cc.
{
  if (time_internal::IsInfiniteDuration(*this) || !IsFinite(r)) {
    const bool is_neg = (std::signbit(r) != 0) != (rep_hi_ < 0);
    return *this = is_neg ? -InfiniteDuration() : InfiniteDuration();
  }
  return *this = ScaleDouble<std::multiplies>(*this, r);
}
References absl::InfiniteDuration(), absl::time_internal::IsInfiniteDuration(), and r.
operator*=() [2/4]
Duration & absl::Duration::operator*= (int64_t r)
Definition at line 447 of file duration.cc.
{
  if (time_internal::IsInfiniteDuration(*this)) {
    const bool is_neg = (r < 0) != (rep_hi_ < 0);
    return *this = is_neg ? -InfiniteDuration() : InfiniteDuration();
  }
  return *this = ScaleFixed<SafeMultiply>(*this, r);
}
References absl::InfiniteDuration(), absl::time_internal::IsInfiniteDuration(), and r.
operator*=() [3/4]
template<typename T , time_internal::EnableIfIntegral< T > = 0> Duration & absl::Duration::operator*= (T r) inline
Definition at line 192 of file time.h.
{
    int64_t x = r;
    return *this *= x;
  }
References r, and absl::x.
operator*=() [4/4]
template<typename T , time_internal::EnableIfFloat< T > = 0> Duration & absl::Duration::operator*= (T r) inline
Definition at line 204 of file time.h.
{
    double x = r;
    return *this *= x;
  }
References r, and absl::x.
operator+=()
Duration & absl::Duration::operator+= (Duration d)
Definition at line 407 of file duration.cc.
{
  if (time_internal::IsInfiniteDuration(*this)) return *this;
  if (time_internal::IsInfiniteDuration(rhs)) return *this = rhs;
  const int64_t orig_rep_hi = rep_hi_;
  rep_hi_ =
      DecodeTwosComp(EncodeTwosComp(rep_hi_) + EncodeTwosComp(rhs.rep_hi_));
  if (rep_lo_ >= kTicksPerSecond - rhs.rep_lo_) {
    rep_hi_ = DecodeTwosComp(EncodeTwosComp(rep_hi_) + 1);
    rep_lo_ -= kTicksPerSecond;
  }
  rep_lo_ += rhs.rep_lo_;
  if (rhs.rep_hi_ < 0 ? rep_hi_ > orig_rep_hi : rep_hi_ < orig_rep_hi) {
    return *this = rhs.rep_hi_ < 0 ? -InfiniteDuration() : InfiniteDuration();
  }
  return *this;
}
References absl::InfiniteDuration(), and absl::time_internal::IsInfiniteDuration().
operator-=()
Duration & absl::Duration::operator-= (Duration d)
Definition at line 424 of file duration.cc.
{
  if (time_internal::IsInfiniteDuration(*this)) return *this;
  if (time_internal::IsInfiniteDuration(rhs)) {
    return *this = rhs.rep_hi_ >= 0 ? -InfiniteDuration() : InfiniteDuration();
  }
  const int64_t orig_rep_hi = rep_hi_;
  rep_hi_ =
      DecodeTwosComp(EncodeTwosComp(rep_hi_) - EncodeTwosComp(rhs.rep_hi_));
  if (rep_lo_ < rhs.rep_lo_) {
    rep_hi_ = DecodeTwosComp(EncodeTwosComp(rep_hi_) - 1);
    rep_lo_ += kTicksPerSecond;
  }
  rep_lo_ -= rhs.rep_lo_;
  if (rhs.rep_hi_ < 0 ? rep_hi_ < orig_rep_hi : rep_hi_ > orig_rep_hi) {
    return *this = rhs.rep_hi_ >= 0 ? -InfiniteDuration() : InfiniteDuration();
  }
  return *this;
}
References absl::InfiniteDuration(), and absl::time_internal::IsInfiniteDuration().
operator/=() [1/4]
Duration & absl::Duration::operator/= (double r)
Definition at line 471 of file duration.cc.
{
  if (time_internal::IsInfiniteDuration(*this) || !IsValidDivisor(r)) {
    const bool is_neg = (std::signbit(r) != 0) != (rep_hi_ < 0);
    return *this = is_neg ? -InfiniteDuration() : InfiniteDuration();
  }
  return *this = ScaleDouble<std::divides>(*this, r);
}
References absl::InfiniteDuration(), absl::time_internal::IsInfiniteDuration(), and r.
operator/=() [2/4]
Duration & absl::Duration::operator/= (int64_t r)
Definition at line 463 of file duration.cc.
{
  if (time_internal::IsInfiniteDuration(*this) || r == 0) {
    const bool is_neg = (r < 0) != (rep_hi_ < 0);
    return *this = is_neg ? -InfiniteDuration() : InfiniteDuration();
  }
  return *this = ScaleFixed<std::divides>(*this, r);
}
References absl::InfiniteDuration(), absl::time_internal::IsInfiniteDuration(), and r.
operator/=() [3/4]
template<typename T , time_internal::EnableIfIntegral< T > = 0> Duration & absl::Duration::operator/= (T r) inline
Definition at line 198 of file time.h.
{
    int64_t x = r;
    return *this /= x;
  }
References r, and absl::x.
operator/=() [4/4]
template<typename T , time_internal::EnableIfFloat< T > = 0> Duration & absl::Duration::operator/= (T r) inline
Definition at line 210 of file time.h.
{
    double x = r;
    return *this /= x;
  }
References r, and absl::x.
operator=()
Duration & absl::Duration::operator= (const Duration & d) default
Friends And Related Symbol Documentation
AbslHashValue
template<typename H > H AbslHashValue (H h, Duration d) friend
Definition at line 216 of file time.h.
{
    return H::combine(std::move(h), d.rep_hi_, d.rep_lo_);
  }
time_internal::GetRepHi
int64_t time_internal::GetRepHi (Duration d) friend
time_internal::GetRepLo
uint32_t time_internal::GetRepLo (Duration d) friend
time_internal::MakeDuration
Duration time_internal::MakeDuration (int64_t hi, uint32_t lo) friend
The documentation for this class was generated from the following files:
open_spiel/abseil-cpp/absl/time/time.h
open_spiel/abseil-cpp/absl/time/duration.cc