open spiel: open_spiel::TensorView< Rank > Class Template Reference
open_spiel::TensorView< Rank > Class Template Reference
#include <tensor_view.h>
Public Member Functions
constexpr TensorView (absl::Span< float > values, const std::array< int, Rank > &shape, bool reset)
constexpr int size () const
void clear ()
constexpr int index (const std::array< int, Rank > &args) const
constexpr float & operator[] (const std::array< int, Rank > &args)
constexpr const float & operator[] (const std::array< int, Rank > &args) const
constexpr int rank () const
constexpr const std::array< int, Rank > shape () const
constexpr int shape (int i) const
Detailed Description
template<int Rank>
class open_spiel::TensorView< Rank >
Definition at line 32 of file tensor_view.h.
Constructor & Destructor Documentation
TensorView()
template<int Rank> open_spiel::TensorView< Rank >::TensorView (absl::Span< float > values, const std::array< int, Rank > & shape, bool reset) inline constexpr
Definition at line 34 of file tensor_view.h.
      : values_(values), shape_(shape) {
    SPIEL_CHECK_EQ(size(), values_.size());
    if (reset) std::fill(values.begin(), values.end(), 0);
  }
References absl::Span< T >::size(), open_spiel::TensorView< Rank >::size(), SPIEL_CHECK_EQ, and values.
Member Function Documentation
clear()
template<int Rank> void open_spiel::TensorView< Rank >::clear () inline
Definition at line 46 of file tensor_view.h.
{ std::fill(values_.begin(), values_.end(), 0.0); }
References absl::Span< T >::begin(), and absl::Span< T >::end().
index()
template<int Rank> int open_spiel::TensorView< Rank >::index (const std::array< int, Rank > & args) const inline constexpr
Definition at line 48 of file tensor_view.h.
{
    int ind = 0;
    for (int i = 0; i < Rank; ++i) {
      ind = ind * shape_[i] + args[i];
    }
    return ind;
  }
References i.
Referenced by open_spiel.python.egt.visualization.SimplexStreamMask::__getitem__(), open_spiel.python.egt.visualization.SimplexStreamMask::__setitem__(), open_spiel::TensorView< Rank >::operator[](), and open_spiel::TensorView< Rank >::operator[]().
operator[]() [1/2]
template<int Rank> float & open_spiel::TensorView< Rank >::operator[] (const std::array< int, Rank > & args) inline constexpr
Definition at line 56 of file tensor_view.h.
{
    return values_[index(args)];
  }
References open_spiel::TensorView< Rank >::index().
operator[]() [2/2]
template<int Rank> const float & open_spiel::TensorView< Rank >::operator[] (const std::array< int, Rank > & args) const inline constexpr
Definition at line 59 of file tensor_view.h.
{
    return values_[index(args)];
  }
References open_spiel::TensorView< Rank >::index().
rank()
template<int Rank> int open_spiel::TensorView< Rank >::rank () const inline constexpr
Definition at line 63 of file tensor_view.h.
{ return Rank; }
shape() [1/2]
template<int Rank> const std::array< int, Rank > open_spiel::TensorView< Rank >::shape () const inline constexpr
Definition at line 64 of file tensor_view.h.
{ return shape_; }
shape() [2/2]
template<int Rank> int open_spiel::TensorView< Rank >::shape (int i) const inline constexpr
Definition at line 65 of file tensor_view.h.
{ return shape_[i]; }
References i.
size()
template<int Rank> int open_spiel::TensorView< Rank >::size () const inline constexpr
Definition at line 41 of file tensor_view.h.
{
    return std::accumulate(shape_.begin(), shape_.end(), 1,
                           std::multiplies<int>());
  }
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel::TensorView< Rank >::TensorView(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
The documentation for this class was generated from the following file:
open_spiel/utils/tensor_view.h