open spiel: open_spiel::algorithms::ISMCTSBot Class Reference
open_spiel::algorithms::ISMCTSBot Class Reference
#include <is_mcts.h>
Public Member Functions
ISMCTSBot (int seed, std::shared_ptr< Evaluator > evaluator, double uct_c, int max_simulations, int max_world_samples, ISMCTSFinalPolicyType final_policy_type, bool use_observation_string, bool allow_inconsistent_action_sets)
ISMCTSBot (int seed, std::shared_ptr< Evaluator > evaluator, double uct_c, int max_simulations)
Action Step (const State &state) override
bool ProvidesPolicy () override
ActionsAndProbs GetPolicy (const State &state) override
std::pair< ActionsAndProbs, Action > StepWithPolicy (const State &state) override
ActionsAndProbs RunSearch (const State &state)
void Restart () override
void RestartAt (const State &state) override
void SetResampler (InfostateResampler cb)
Public Member Functions inherited from open_spiel::Bot
virtual ~Bot ()=default
virtual void InformAction (const State &state, Player player_id, Action action)
virtual void InformActions (const State &state, const std::vector< Action > &actions)
virtual bool ProvidesForceAction ()
virtual void ForceAction (const State &state, Action action)
virtual bool IsClonable () const
virtual std::unique_ptr< Bot > Clone ()
Detailed Description
Definition at line 63 of file is_mcts.h.
Constructor & Destructor Documentation
ISMCTSBot() [1/2]
open_spiel::algorithms::ISMCTSBot::ISMCTSBot (int seed, std::shared_ptr< Evaluator > evaluator, double uct_c, int max_simulations, int max_world_samples, ISMCTSFinalPolicyType final_policy_type, bool use_observation_string, bool allow_inconsistent_action_sets)
Definition at line 32 of file is_mcts.cc.
    : rng_(seed),
      evaluator_(evaluator),
      uct_c_(uct_c),
      max_simulations_(max_simulations),
      max_world_samples_(max_world_samples),
      final_policy_type_(final_policy_type),
      use_observation_string_(use_observation_string),
      allow_inconsistent_action_sets_(allow_inconsistent_action_sets) {}
ISMCTSBot() [2/2]
open_spiel::algorithms::ISMCTSBot::ISMCTSBot (int seed, std::shared_ptr< Evaluator > evaluator, double uct_c, int max_simulations) inline
Definition at line 83 of file is_mcts.h.
      : ISMCTSBot(seed, evaluator, uct_c, max_simulations,
                  kUnlimitedNumWorldSamples,
                  ISMCTSFinalPolicyType::kNormalizedVisitCount, false, false) {}
Member Function Documentation
GetPolicy()
ActionsAndProbs open_spiel::algorithms::ISMCTSBot::GetPolicy (const State & state) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 103 of file is_mcts.cc.
{
  return RunSearch(state);
}
References RunSearch(), and state.
Referenced by open_spiel::init_pyspiel_bots(), and StepWithPolicy().
ProvidesPolicy()
bool open_spiel::algorithms::ISMCTSBot::ProvidesPolicy () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 91 of file is_mcts.h.
{ return true; }
Restart()
void open_spiel::algorithms::ISMCTSBot::Restart () inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 99 of file is_mcts.h.
{}
Referenced by open_spiel::init_pyspiel_bots().
RestartAt()
void open_spiel::algorithms::ISMCTSBot::RestartAt (const State & state) inline override virtual
Reimplemented from open_spiel::Bot.
Definition at line 100 of file is_mcts.h.
{}
Referenced by open_spiel::init_pyspiel_bots().
RunSearch()
ActionsAndProbs open_spiel::algorithms::ISMCTSBot::RunSearch (const State & state)
Definition at line 62 of file is_mcts.cc.
{
  Reset();
  SPIEL_CHECK_EQ(state.GetGame()->GetType().dynamics,
                 GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(state.GetGame()->GetType().information,
                 GameType::Information::kImperfectInformation);
  // Optimization in case of single legal action, and support for games which
  // do not support ResampleFromInfostate in certain specific (single action)
  // states.
  std::vector<Action> legal_actions = state.LegalActions();
  if (legal_actions.size() == 1) return {{legal_actions[0], 1.0}};
  root_node_ = CreateNewNode(state);
  SPIEL_CHECK_TRUE(root_node_ != nullptr);
  auto root_infostate_key = GetStateKey(state);
  for (int sim = 0; sim < max_simulations_; ++sim) {
    std::unique_ptr<State> sampled_root_state = SampleRootState(state);
    SPIEL_CHECK_TRUE(root_infostate_key == GetStateKey(*sampled_root_state));
    SPIEL_CHECK_TRUE(sampled_root_state != nullptr);
    RunSimulation(sampled_root_state.get());
  }
  if (allow_inconsistent_action_sets_) {
    // Filter illegals for this state.
    std::vector<Action> legal_actions = state.LegalActions();
    ISMCTSNode temp_node = FilterIllegals(root_node_, legal_actions);
    SPIEL_CHECK_GT(temp_node.total_visits, 0);
    return GetFinalPolicy(state, &temp_node);
  } else {
    return GetFinalPolicy(state, root_node_);
  }
}
References open_spiel::GameType::kImperfectInformation, open_spiel::GameType::kSequential, SPIEL_CHECK_EQ, SPIEL_CHECK_GT, SPIEL_CHECK_TRUE, state, and open_spiel::algorithms::ISMCTSNode::total_visits.
Referenced by GetPolicy(), and Step().
SetResampler()
void open_spiel::algorithms::ISMCTSBot::SetResampler (InfostateResampler cb) inline
Definition at line 102 of file is_mcts.h.
{ resampler_cb_ = cb; }
Step()
Action open_spiel::algorithms::ISMCTSBot::Step (const State & state) override virtual
Implements open_spiel::Bot.
Definition at line 98 of file is_mcts.cc.
{
  ActionsAndProbs policy = RunSearch(state);
  return SampleAction(policy, RandomNumber()).first;
}
References RunSearch(), open_spiel::SampleAction(), and state.
Referenced by open_spiel::init_pyspiel_bots().
StepWithPolicy()
std::pair< ActionsAndProbs, Action > open_spiel::algorithms::ISMCTSBot::StepWithPolicy (const State & state) override virtual
Reimplemented from open_spiel::Bot.
Definition at line 107 of file is_mcts.cc.
{
  ActionsAndProbs policy = GetPolicy(state);
  Action sampled_action = SampleAction(policy, RandomNumber()).first;
  return {policy, sampled_action};
}
References GetPolicy(), open_spiel::SampleAction(), and state.
Referenced by open_spiel::init_pyspiel_bots().
The documentation for this class was generated from the following files:
open_spiel/algorithms/is_mcts.h
open_spiel/algorithms/is_mcts.cc