open spiel: open_spiel::battleship::CellAndDirection Class Reference
open_spiel::battleship::CellAndDirection Class Reference
#include <battleship_types.h>
Public Types
enum Direction { Horizontal = 0 , Vertical = 1 }
Public Member Functions
CellAndDirection (const Direction direction, const Cell &tl_corner)
Cell TopLeftCorner () const
Public Attributes
Direction direction
Protected Attributes
Cell tl_corner_
Detailed Description
Definition at line 49 of file battleship_types.h.
Member Enumeration Documentation
Direction
enum open_spiel::battleship::CellAndDirection::Direction
Enumerator
Horizontal
Vertical
Definition at line 51 of file battleship_types.h.
{ Horizontal = 0, Vertical = 1 };
Constructor & Destructor Documentation
CellAndDirection()
open_spiel::battleship::CellAndDirection::CellAndDirection (const Direction direction, const Cell & tl_corner)
Definition at line 108 of file battleship_types.cc.
    : direction(direction), tl_corner_(tl_corner) {
  SPIEL_CHECK_GE(tl_corner.row, 0);
  SPIEL_CHECK_GE(tl_corner.col, 0);
}
References open_spiel::battleship::Cell::col, open_spiel::battleship::Cell::row, and SPIEL_CHECK_GE.
Member Function Documentation
TopLeftCorner()
Cell open_spiel::battleship::CellAndDirection::TopLeftCorner () const inline
Definition at line 54 of file battleship_types.h.
{ return tl_corner_; }
References tl_corner_.
Referenced by open_spiel::battleship::BattleshipGame::ActionToString(), open_spiel::battleship::BattleshipState::DoApplyAction(), open_spiel::battleship::BattleshipState::InformationStateTensor(), open_spiel::battleship::ShipPlacement::IsWithinBounds(), open_spiel::battleship::ShipPlacement::OverlapsWith(), open_spiel::battleship::BattleshipState::OwnBoardString(), open_spiel::battleship::BattleshipGame::SerializeShipPlacementAction(), and open_spiel::battleship::BattleshipState::ShotsBoardString().
Member Data Documentation
direction
Direction open_spiel::battleship::CellAndDirection::direction
Definition at line 55 of file battleship_types.h.
Referenced by open_spiel::battleship::BattleshipGame::ActionToString(), open_spiel::battleship::ShipPlacement::BottomRightCorner(), open_spiel::battleship::ShipPlacement::CoversCell(), open_spiel::battleship::BattleshipState::DoApplyAction(), open_spiel::battleship::BattleshipState::InformationStateTensor(), open_spiel::battleship::BattleshipState::OwnBoardString(), open_spiel::battleship::BattleshipGame::SerializeShipPlacementAction(), open_spiel::battleship::BattleshipState::ShotsBoardString(), and open_spiel::battleship::ShipPlacement::ToString().
tl_corner_
Cell open_spiel::battleship::CellAndDirection::tl_corner_ protected
Definition at line 58 of file battleship_types.h.
Referenced by open_spiel::battleship::ShipPlacement::BottomRightCorner(), open_spiel::battleship::ShipPlacement::CoversCell(), TopLeftCorner(), and open_spiel::battleship::ShipPlacement::ToString().
The documentation for this class was generated from the following files:
open_spiel/games/battleship/battleship_types.h
open_spiel/games/battleship/battleship_types.cc