open spiel: open_spiel::matrix_game::MatrixState Class Reference
open_spiel::matrix_game::MatrixState Class Reference
#include <matrix_game.h>
Public Member Functions
MatrixState (std::shared_ptr< const Game > game)
MatrixState (const MatrixState &)=default
std::vector< Action > LegalActions (Player player) const override
std::string ToString () const override
std::string ActionToString (Player player, Action action_id) const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
Public Member Functions inherited from open_spiel::NFGState
NFGState (std::shared_ptr< const Game > game)
Player CurrentPlayer () const final
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
std::string ToString () const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
Public Member Functions inherited from open_spiel::SimMoveState
SimMoveState (std::shared_ptr< const Game > game)
SimMoveState (const SimMoveState &)=default
std::vector< Action > LegalActions () const override
void ApplyAction (Action action) override
std::vector< Action > FlatJointActionToActions (Action flat_action) const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyActions (const std::vector< Action > &moves) override
Protected Member Functions inherited from open_spiel::SimMoveState
std::string FlatJointActionToString (Action flat_action) const
std::vector< Action > LegalFlatJointActions () const
void ApplyFlatJointAction (Action flat_action)
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyAction (Action action_id)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 172 of file matrix_game.h.
Constructor & Destructor Documentation
MatrixState() [1/2]
open_spiel::matrix_game::MatrixState::MatrixState (std::shared_ptr< const Game > game) explicit
Definition at line 88 of file matrix_game.cc.
    : NFGState(game),
      matrix_game_(static_cast<const MatrixGame*>(game.get())) {}
Referenced by Clone().
MatrixState() [2/2]
open_spiel::matrix_game::MatrixState::MatrixState (const MatrixState &) explicit default
Member Function Documentation
ActionToString()
std::string open_spiel::matrix_game::MatrixState::ActionToString (Player player, Action action_id) const inline override virtual
Implements open_spiel::State.
Definition at line 191 of file matrix_game.h.
{
    if (player == kSimultaneousPlayerId)
      return FlatJointActionToString(action_id);
    else if (player == kRowPlayer)
      return matrix_game_->RowActionName(action_id);
    else
      return matrix_game_->ColActionName(action_id);
  }
References open_spiel::matrix_game::MatrixGame::ColActionName(), open_spiel::SimMoveState::FlatJointActionToString(), open_spiel::matrix_game::kRowPlayer, open_spiel::kSimultaneousPlayerId, player, and open_spiel::matrix_game::MatrixGame::RowActionName().
Referenced by ToString().
Clone()
std::unique_ptr< State > open_spiel::matrix_game::MatrixState::Clone () const inline override virtual
Implements open_spiel::State.
Definition at line 211 of file matrix_game.h.
{
    return std::unique_ptr<State>(new MatrixState(*this));
  }
References MatrixState().
DoApplyActions()
void open_spiel::matrix_game::MatrixState::DoApplyActions (const std::vector< Action > & moves) inline override protected virtual
Implements open_spiel::SimMoveState.
Definition at line 216 of file matrix_game.h.
{
    SPIEL_CHECK_EQ(moves.size(), 2);
    SPIEL_CHECK_GE(moves[kRowPlayer], 0);
    SPIEL_CHECK_LT(moves[kRowPlayer], matrix_game_->NumRows());
    SPIEL_CHECK_GE(moves[kColPlayer], 0);
    SPIEL_CHECK_LT(moves[kColPlayer], matrix_game_->NumCols());
    joint_move_ = moves;
  }
References open_spiel::matrix_game::kColPlayer, open_spiel::matrix_game::kRowPlayer, open_spiel::matrix_game::MatrixGame::NumCols(), open_spiel::matrix_game::MatrixGame::NumRows(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::matrix_game::MatrixState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 200 of file matrix_game.h.
{ return !joint_move_.empty(); }
Referenced by LegalActions(), Returns(), and ToString().
LegalActions()
std::vector< Action > open_spiel::matrix_game::MatrixState::LegalActions (Player player) const inline override virtual
Implements open_spiel::SimMoveState.
Definition at line 177 of file matrix_game.h.
{
    if (IsTerminal()) return {};
    if (player == kSimultaneousPlayerId) {
      return LegalFlatJointActions();
    } else {
      std::vector<Action> moves(player == kRowPlayer ? matrix_game_->NumRows()
                                                     : matrix_game_->NumCols());
      std::iota(moves.begin(), moves.end(), 0);  // fill with values 0...n-1
      return moves;
    }
  }
References IsTerminal(), open_spiel::matrix_game::kRowPlayer, open_spiel::kSimultaneousPlayerId, open_spiel::SimMoveState::LegalFlatJointActions(), open_spiel::matrix_game::MatrixGame::NumCols(), open_spiel::matrix_game::MatrixGame::NumRows(), and player.
Returns()
std::vector< double > open_spiel::matrix_game::MatrixState::Returns () const inline override virtual
Implements open_spiel::State.
Definition at line 202 of file matrix_game.h.
{
    if (IsTerminal()) {
      return {matrix_game_->RowUtility(joint_move_[0], joint_move_[1]),
              matrix_game_->ColUtility(joint_move_[0], joint_move_[1])};
    } else {
      return {0, 0};
    }
  }
References open_spiel::matrix_game::MatrixGame::ColUtility(), IsTerminal(), and open_spiel::matrix_game::MatrixGame::RowUtility().
Referenced by ToString().
ToString()
std::string open_spiel::matrix_game::MatrixState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 92 of file matrix_game.cc.
{
  std::string result = "";
  absl::StrAppend(&result, "Terminal? ", IsTerminal() ? "true" : "false", "\n");
  if (IsTerminal()) {
    absl::StrAppend(&result, "History: ", HistoryString(), "\n");
    absl::StrAppend(&result, "Returns: ", absl::StrJoin(Returns(), ","), "\n");
  }
  absl::StrAppend(&result, "Row actions: ");
  for (auto move : LegalActions(0)) {
    absl::StrAppend(&result, ActionToString(0, move), " ");
  }
  absl::StrAppend(&result, "\nCol actions: ");
  for (auto move : LegalActions(1)) {
    absl::StrAppend(&result, ActionToString(1, move), " ");
  }
  absl::StrAppend(&result, "\nUtility matrix:\n");
  for (int r = 0; r < matrix_game_->NumRows(); r++) {
    for (int c = 0; c < matrix_game_->NumCols(); c++) {
      absl::StrAppend(&result, matrix_game_->RowUtility(r, c), ",",
                      matrix_game_->ColUtility(r, c), " ");
    }
    absl::StrAppend(&result, "\n");
  }
  return result;
}
References ActionToString(), open_spiel::matrix_game::MatrixGame::ColUtility(), open_spiel::State::HistoryString(), IsTerminal(), open_spiel::SimMoveState::LegalActions(), open_spiel::matrix_game::MatrixGame::NumCols(), open_spiel::matrix_game::MatrixGame::NumRows(), r, Returns(), open_spiel::matrix_game::MatrixGame::RowUtility(), absl::StrAppend(), and absl::StrJoin().
The documentation for this class was generated from the following files:
open_spiel/matrix_game.h
open_spiel/matrix_game.cc