open spiel: open_spiel::liars_dice::LiarsDiceState Class Reference
open_spiel::liars_dice::LiarsDiceState Class Reference
#include <liars_dice.h>
Public Member Functions
LiarsDiceState (std::shared_ptr< const Game > game, int total_num_dice, int max_dice_per_player, const std::vector< int > &num_dice)
LiarsDiceState (const LiarsDiceState &)=default
void Reset (const GameParameters &params)
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< std::pair< Action, double > > ChanceOutcomes () const override
std::vector< Action > LegalActions () const override
const int dice_sides () const
Player calling_player () const
int dice_outcome (Player player, int index) const
int last_bid () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
virtual std::string ObservationString (Player player) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action_id) override
std::pair< int, int > UnrankBid (int bid) const
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Protected Attributes
std::vector< std::vector< int > > dice_outcomes_
std::vector< int > bidseq_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 57 of file liars_dice.h.
Constructor & Destructor Documentation
LiarsDiceState() [1/2]
open_spiel::liars_dice::LiarsDiceState::LiarsDiceState (std::shared_ptr< const Game > game, int total_num_dice, int max_dice_per_player, const std::vector< int > & num_dice) explicit
Definition at line 112 of file liars_dice.cc.
    : State(game),
      dice_outcomes_(),
      bidseq_(),
      cur_player_(kChancePlayerId),  // chance starts
      cur_roller_(0),                // first player starts rolling
      winner_(kInvalidPlayer),
      loser_(kInvalidPlayer),
      current_bid_(kInvalidBid),
      total_num_dice_(total_num_dice),
      total_moves_(0),
      calling_player_(0),
      bidding_player_(0),
      max_dice_per_player_(max_dice_per_player),
      num_dice_(num_dice),
      num_dice_rolled_(game->NumPlayers(), 0),
      bidseq_str_() {
  for (int const& num_dices : num_dice_) {
    std::vector<int> initial_outcomes(num_dices, kInvalidOutcome);
    dice_outcomes_.push_back(initial_outcomes);
  }
}
References dice_outcomes_.
Referenced by Clone().
LiarsDiceState() [2/2]
open_spiel::liars_dice::LiarsDiceState::LiarsDiceState (const LiarsDiceState &) default
Member Function Documentation
ActionToString()
std::string open_spiel::liars_dice::LiarsDiceState::ActionToString (Player player, Action action_id) const override virtual
Implements open_spiel::State.
Definition at line 137 of file liars_dice.cc.
{
  if (player != kChancePlayerId) {
    if (action_id == total_num_dice_ * dice_sides()) {
      return "Liar";
    } else {
      const std::pair<int, int> bid = UnrankBid(action_id);
      return absl::StrCat(bid.first, "-", bid.second);
    }
  }
  return absl::StrCat("Roll ", action_id + 1);
}
References dice_sides(), open_spiel::kChancePlayerId, player, absl::StrCat(), and UnrankBid().
calling_player()
Player open_spiel::liars_dice::LiarsDiceState::calling_player () const inline
Definition at line 82 of file liars_dice.h.
{ return calling_player_; }
ChanceOutcomes()
std::vector< std::pair< Action, double > > open_spiel::liars_dice::LiarsDiceState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 264 of file liars_dice.cc.
{
  SPIEL_CHECK_TRUE(IsChanceNode());
  std::vector<std::pair<Action, double>> outcomes;
  // A chance node is a single die roll.
  outcomes.reserve(dice_sides());
  for (int i = 0; i < dice_sides(); i++) {
    outcomes.emplace_back(i, 1.0 / dice_sides());
  }
  return outcomes;
}
References dice_sides(), i, open_spiel::State::IsChanceNode(), and SPIEL_CHECK_TRUE.
Clone()
std::unique_ptr< State > open_spiel::liars_dice::LiarsDiceState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 421 of file liars_dice.cc.
{
  return std::unique_ptr<State>(new LiarsDiceState(*this));
}
References LiarsDiceState().
CurrentPlayer()
int open_spiel::liars_dice::LiarsDiceState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 150 of file liars_dice.cc.
{
  if (IsTerminal()) {
    return kTerminalPlayerId;
  } else {
    return cur_player_;
  }
}
References IsTerminal(), and open_spiel::kTerminalPlayerId.
dice_outcome()
int open_spiel::liars_dice::LiarsDiceState::dice_outcome (Player player, int index) const inline
Definition at line 83 of file liars_dice.h.
{
    return dice_outcomes_[player][index];
  }
References dice_outcomes_, and player.
dice_sides()
const int open_spiel::liars_dice::LiarsDiceState::dice_sides () const
Definition at line 185 of file liars_dice.cc.
{
  return UnwrapGame(game_.get())->dice_sides();
}
References open_spiel::State::game_.
Referenced by ActionToString(), ChanceOutcomes(), DoApplyAction(), open_spiel::liars_dice::ImperfectRecallLiarsDiceState::InformationStateString(), InformationStateString(), InformationStateTensor(), last_bid(), LegalActions(), ObservationTensor(), ToString(), and UnrankBid().
DoApplyAction()
void open_spiel::liars_dice::LiarsDiceState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 193 of file liars_dice.cc.
{
  if (IsChanceNode()) {
    // Fill the next die roll for the current roller.
    SPIEL_CHECK_GE(cur_roller_, 0);
    SPIEL_CHECK_LT(cur_roller_, num_players_);
    SPIEL_CHECK_LT(num_dice_rolled_[cur_roller_], num_dice_[cur_roller_]);
    int slot = num_dice_rolled_[cur_roller_];
    // Assign the roll.
    dice_outcomes_[cur_roller_][slot] = action + 1;
    num_dice_rolled_[cur_roller_]++;
    // Check to see if we must change the roller.
    if (num_dice_rolled_[cur_roller_] == num_dice_[cur_roller_]) {
      cur_roller_++;
      if (cur_roller_ >= num_players_) {
        // Time to start playing!
        cur_player_ = 0;
        // Sort all players' rolls
        for (auto p = Player{0}; p < num_players_; p++) {
          std::sort(dice_outcomes_[p].begin(), dice_outcomes_[p].end());
        }
      }
    }
  } else {
    // Check for legal actions.
    if (!bidseq_.empty() && action <= bidseq_.back()) {
      SpielFatalError(absl::StrCat("Illegal action. ", action,
                                   " should be strictly higher than ",
                                   bidseq_.back()));
    }
    if (action == total_num_dice_ * dice_sides()) {
      // This was the calling bid, game is over.
      bidseq_.push_back(action);
      calling_player_ = cur_player_;
      ResolveWinner();
    } else {
      // Up the bid and move to the next player.
      bidseq_.push_back(action);
      current_bid_ = action;
      bidding_player_ = cur_player_;
      cur_player_ = NextPlayerRoundRobin(cur_player_, num_players_);
    }
    total_moves_++;
  }
}
References action, begin, bidseq_, dice_outcomes_, dice_sides(), end, open_spiel::State::IsChanceNode(), open_spiel::NextPlayerRoundRobin(), open_spiel::State::num_players_, SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::SpielFatalError(), and absl::StrCat().
InformationStateString()
std::string open_spiel::liars_dice::LiarsDiceState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 278 of file liars_dice.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  std::string result = absl::StrJoin(dice_outcomes_[player], "");
  for (int b = 0; b < bidseq_.size(); b++) {
    if (bidseq_[b] == total_num_dice_ * dice_sides()) {
      absl::StrAppend(&result, " Liar");
    } else {
      const std::pair<int, int> bid = UnrankBid(bidseq_[b]);
      absl::StrAppend(&result, " ", bid.first, "-", bid.second);
    }
  }
  return result;
}
References b, bidseq_, dice_outcomes_, dice_sides(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, absl::StrAppend(), absl::StrJoin(), and UnrankBid().
InformationStateTensor()
void open_spiel::liars_dice::LiarsDiceState::InformationStateTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 336 of file liars_dice.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // One-hot encoding for player number.
  // One-hot encoding for each die (max_dice_per_player_ * sides).
  // One slot(bit) for each legal bid.
  // One slot(bit) for calling liar. (Necessary because observations and
  // information states need to be defined at terminals)
  int offset = 0;
  std::fill(values.begin(), values.end(), 0.);
  SPIEL_CHECK_EQ(values.size(), num_players_ +
                                    (max_dice_per_player_ * dice_sides()) +
                                    (total_num_dice_ * dice_sides()) + 1);
  values[player] = 1;
  offset += num_players_;
  int my_num_dice = num_dice_[player];
  for (int d = 0; d < my_num_dice; d++) {
    int outcome = dice_outcomes_[player][d];
    if (outcome != kInvalidOutcome) {
      SPIEL_CHECK_GE(outcome, 1);
      SPIEL_CHECK_LE(outcome, dice_sides());
      values[offset + (outcome - 1)] = 1;
    }
    offset += dice_sides();
  }
  // Skip to bidding part. If current player has fewer dice than the other
  // players, all the remaining entries are 0 for those dice.
  offset = num_players_ + max_dice_per_player_ * dice_sides();
  for (int b = 0; b < bidseq_.size(); b++) {
    SPIEL_CHECK_GE(bidseq_[b], 0);
    SPIEL_CHECK_LE(bidseq_[b], total_num_dice_ * dice_sides());
    values[offset + bidseq_[b]] = 1;
  }
}
References b, bidseq_, dice_outcomes_, dice_sides(), open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, and values.
IsTerminal()
bool open_spiel::liars_dice::LiarsDiceState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 320 of file liars_dice.cc.
{ return winner_ != kInvalidPlayer; }
References open_spiel::kInvalidPlayer.
Referenced by CurrentPlayer(), and LegalActions().
last_bid()
int open_spiel::liars_dice::LiarsDiceState::last_bid () const inline
Definition at line 86 of file liars_dice.h.
                       {
    if (bidseq_.back() == total_num_dice_ * dice_sides()) {
      return bidseq_[bidseq_.size() - 2];
    } else {
      return bidseq_.back();
    }
  }
References bidseq_, and dice_sides().
LegalActions()
std::vector< Action > open_spiel::liars_dice::LiarsDiceState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 242 of file liars_dice.cc.
{
  if (IsTerminal()) return {};
  // A chance node is a single die roll.
  if (IsChanceNode()) {
    return LegalChanceOutcomes();
  }
  std::vector<Action> actions;
  // Any move higher than the current bid is allowed. (Bids start at 0)
  for (int b = current_bid_ + 1; b < total_num_dice_ * dice_sides(); b++) {
    actions.push_back(b);
  }
  // Calling Liar is only available if at least one move has been made.
  if (total_moves_ > 0) {
    actions.push_back(total_num_dice_ * dice_sides());
  }
  return actions;
}
References b, dice_sides(), open_spiel::State::IsChanceNode(), IsTerminal(), and open_spiel::State::LegalChanceOutcomes().
ObservationTensor()
void open_spiel::liars_dice::LiarsDiceState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 377 of file liars_dice.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  // One-hot encoding for player number.
  // One-hot encoding for each die (max_dice_per_player_ * sides).
  // One slot(bit) for the two last legal bid.
  // One slot(bit) for calling liar. (Necessary because observations and
  // information states need to be defined at terminals)
  int offset = 0;
  std::fill(values.begin(), values.end(), 0.);
  SPIEL_CHECK_EQ(values.size(), num_players_ +
                                    (max_dice_per_player_ * dice_sides()) +
                                    (total_num_dice_ * dice_sides()) + 1);
  values[player] = 1;
  offset += num_players_;
  int my_num_dice = num_dice_[player];
  for (int d = 0; d < my_num_dice; d++) {
    int outcome = dice_outcomes_[player][d];
    if (outcome != kInvalidOutcome) {
      SPIEL_CHECK_GE(outcome, 1);
      SPIEL_CHECK_LE(outcome, dice_sides());
      values[offset + (outcome - 1)] = 1;
    }
    offset += dice_sides();
  }
  // Skip to bidding part. If current player has fewer dice than the other
  // players, all the remaining entries are 0 for those dice.
  offset = num_players_ + max_dice_per_player_ * dice_sides();
  // We only show the num_players_ last bids
  int size_bid = bidseq_.size();
  int bid_offset = std::max(0, size_bid - num_players_);
  for (int b = bid_offset; b < size_bid; b++) {
    SPIEL_CHECK_GE(bidseq_[b], 0);
    SPIEL_CHECK_LE(bidseq_[b], total_num_dice_ * dice_sides());
    values[offset + bidseq_[b]] = 1;
  }
}
References b, bidseq_, dice_outcomes_, dice_sides(), open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, and values.
Reset()
void open_spiel::liars_dice::LiarsDiceState::Reset (const GameParameters & params)
Returns()
std::vector< double > open_spiel::liars_dice::LiarsDiceState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 322 of file liars_dice.cc.
{
  std::vector<double> returns(num_players_, 0.0);
  if (winner_ != kInvalidPlayer) {
    returns[winner_] = 1.0;
  }
  if (loser_ != kInvalidPlayer) {
    returns[loser_] = -1.0;
  }
  return returns;
}
References open_spiel::kInvalidPlayer, and open_spiel::State::num_players_.
ToString()
std::string open_spiel::liars_dice::LiarsDiceState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 294 of file liars_dice.cc.
{
  std::string result = "";
  for (auto p = Player{0}; p < num_players_; p++) {
    if (p != 0) absl::StrAppend(&result, " ");
    for (int d = 0; d < num_dice_[p]; d++) {
      absl::StrAppend(&result, dice_outcomes_[p][d]);
    }
  }
  if (IsChanceNode()) {
    return absl::StrCat(result, " - chance node, current roller is player ",
                        cur_roller_);
  }
  for (int b = 0; b < bidseq_.size(); b++) {
    if (bidseq_[b] == total_num_dice_ * dice_sides()) {
      absl::StrAppend(&result, " Liar");
    } else {
      const std::pair<int, int> bid = UnrankBid(bidseq_[b]);
      absl::StrAppend(&result, " ", bid.first, "-", bid.second);
    }
  }
  return result;
}
References b, bidseq_, dice_outcomes_, dice_sides(), open_spiel::State::IsChanceNode(), open_spiel::State::num_players_, absl::StrAppend(), absl::StrCat(), and UnrankBid().
UnrankBid()
std::pair< int, int > open_spiel::liars_dice::LiarsDiceState::UnrankBid (int bid) const protected
Definition at line 425 of file liars_dice.cc.
{
  std::pair<int, int> bid;
  SPIEL_CHECK_NE(bidnum, kInvalidBid);
  SPIEL_CHECK_GE(bidnum, 0);
  SPIEL_CHECK_LT(bidnum, dice_sides() * total_num_dice_);
  if (bidding_rule() == BiddingRule::kResetFace) {
    // Bids have the form <quantity>-<face>
    //
    // So, in a two-player game where each die has 6 faces, we have
    //
    // Bid ID    Quantity   Face
    // 0         1          1
    // 1         1          2
    // ...
    // 5         1          6
    // 6         2          1
    // ...
    // 11        2          6
    //
    // Bid ID #dice * #num faces encodes the special "liar" action.
    // The quantity occupies the higher bits, so it can be extracted using an
    // integer division operation.
    bid.first = bidnum / dice_sides() + 1;
    // The face occupies the lower bits, so it can be extraced using a modulo
    // operation.
    bid.second = 1 + (bidnum % dice_sides());
  } else {
    SPIEL_CHECK_EQ(bidding_rule(), BiddingRule::kResetQuantity);
    // Bids have the form <face>-<quantity>
    //
    // So, in a two-player game where each die has 6 faces, we have
    //
    // Bid ID    Quantity   Face
    // 0         1          1
    // 1         2          1
    // 2         1          2
    // 3         2          2
    // ...
    // 9         2          5
    // 10        1          6
    // 11        2          6
    //
    // Bid ID #dice * #num faces encodes the special "liar" action.
    //
    // This particular encoding scheme allows for very cheap comparison of bids:
    // a bid is stronger if it is encoded to a higher ID.
    // The quantity occupies the lower bits, so it can be extracted using a
    // modulo operation.
    bid.first = 1 + (bidnum % total_num_dice_);
    // The face occupies the higher bits, so it can be extracted using an
    // integer division.
    bid.second = bidnum / total_num_dice_ + 1;
  }
  SPIEL_CHECK_GE(bid.first, 1);
  // It doesn't make sense to bid more dice than the number of dice in the game.
  SPIEL_CHECK_LE(bid.first, total_num_dice_);
  SPIEL_CHECK_GE(bid.second, 1);
  // It doesn't make sense to bid a face that does not exist.
  SPIEL_CHECK_LE(bid.second, dice_sides());
  return bid;
}
References dice_sides(), open_spiel::liars_dice::kResetFace, open_spiel::liars_dice::kResetQuantity, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, and SPIEL_CHECK_NE.
Referenced by ActionToString(), open_spiel::liars_dice::ImperfectRecallLiarsDiceState::InformationStateString(), InformationStateString(), and ToString().
Member Data Documentation
bidseq_
std::vector<int> open_spiel::liars_dice::LiarsDiceState::bidseq_ protected
Definition at line 106 of file liars_dice.h.
Referenced by DoApplyAction(), open_spiel::liars_dice::ImperfectRecallLiarsDiceState::InformationStateString(), InformationStateString(), InformationStateTensor(), last_bid(), ObservationTensor(), and ToString().
dice_outcomes_
std::vector<std::vector<int> > open_spiel::liars_dice::LiarsDiceState::dice_outcomes_ protected
Definition at line 103 of file liars_dice.h.
Referenced by dice_outcome(), DoApplyAction(), open_spiel::liars_dice::ImperfectRecallLiarsDiceState::InformationStateString(), InformationStateString(), InformationStateTensor(), LiarsDiceState(), ObservationTensor(), and ToString().
The documentation for this class was generated from the following files:
open_spiel/games/liars_dice/liars_dice.h
open_spiel/games/liars_dice/liars_dice.cc