open spiel: open_spiel::garnet::GarnetState Class Reference
open_spiel::garnet::GarnetState Class Reference
#include <garnet.h>
Public Member Functions
GarnetState (std::shared_ptr< const Game > game, int size, int horizon, int seed, int num_action, int num_chance_action, double sparsity_factor, double eta)
GarnetState (std::shared_ptr< const Game > game, int size, int horizon, int seed, int num_action, int num_chance_action, double sparsity_factor, double eta, Player current_player, bool is_chance_init, int x, int t, int last_action, double return_value, const std::vector< double > &distribution)
double GetTransitionProba (int x, int action, int chance_action) const
int GetTransition (int x, int action, int chance_action) const
double GetReward (int x, int action) const
Player CurrentPlayer () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalActions () const override
ActionsAndProbs ChanceOutcomes () const override
std::vector< std::string > DistributionSupport () override
void UpdateDistribution (const std::vector< double > &distribution) override
std::vector< double > Distribution () const
std::string Serialize () const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 58 of file garnet.h.
Constructor & Destructor Documentation
GarnetState() [1/2]
open_spiel::garnet::GarnetState::GarnetState (std::shared_ptr< const Game > game, int size, int horizon, int seed, int num_action, int num_chance_action, double sparsity_factor, double eta)
Definition at line 90 of file garnet.cc.
    : State(game),
      size_(size),
      horizon_(horizon),
      seed_(seed),
      num_action_(num_action),
      num_chance_action_(num_chance_action),
      sparsity_factor_(sparsity_factor),
      eta_(eta),
      distribution_(size_, 1. / size_) {
  std::mt19937 rng(seed_);
  double normalization;
  double proba;
  double cdf_proba;
  for (int i = 0; i < size; ++i) {
    for (int j = 0; j < num_action; ++j) {
      double r_sparse = absl::Uniform<double>(rng, 0.0, 1.0);
      if (r_sparse < sparsity_factor_) {
        garnet_reward_.push_back(absl::Uniform<double>(rng, 0.0, 1.0));
      } else {
        garnet_reward_.push_back(0.0);
      }
      normalization = 0;
      std::vector<double> cdf;
      cdf.push_back(0.0);
      cdf.push_back(1.0);
      for (int kk = 0; kk < num_chance_action - 1; ++kk) {
        cdf_proba = absl::Uniform<double>(rng, 0.0, 1.0);
        cdf.push_back(cdf_proba);
      }
      std::sort(cdf.begin(), cdf.end());
      for (int k = 0; k < num_chance_action; ++k) {
        proba = cdf[k+1]-cdf[k];
        normalization += proba;
        garnet_transition_proba_unnormalized_.push_back(proba);
        garnet_transition_.push_back(absl::Uniform<int>(rng, 0, size));
      }
      garnet_transition_proba_normalization_.push_back(normalization);
    }
  }
}
References i, size, and absl::Uniform().
Referenced by Clone().
GarnetState() [2/2]
open_spiel::garnet::GarnetState::GarnetState (std::shared_ptr< const Game > game, int size, int horizon, int seed, int num_action, int num_chance_action, double sparsity_factor, double eta, Player current_player, bool is_chance_init, int x, int t, int last_action, double return_value, const std::vector< double > & distribution)
Definition at line 136 of file garnet.cc.
    : State(game),
      size_(size),
      horizon_(horizon),
      seed_(seed),
      num_action_(num_action),
      num_chance_action_(num_chance_action),
      sparsity_factor_(sparsity_factor),
      eta_(eta),
      current_player_(current_player),
      is_chance_init_(is_chance_init),
      x_(x),
      t_(t),
      last_action_(last_action),
      return_value_(return_value),
      distribution_(distribution) {
  std::mt19937 rng(seed_);
  double normalization;
  double proba;
  for (int i = 0; i < size; ++i) {
    for (int j = 0; j < num_action; ++j) {
      double r_sparse = absl::Uniform<double>(rng, 0.0, 1.0);
      if (r_sparse < sparsity_factor_) {
        garnet_reward_.push_back(absl::Uniform<double>(rng, 0.0, 1.0));
      } else {
        garnet_reward_.push_back(0.0);
      }
      normalization = 0;
      for (int k = 0; k < num_chance_action; ++k) {
        proba = absl::Uniform<double>(rng, 0.0, 1.0);
        normalization += proba;
        garnet_transition_proba_unnormalized_.push_back(proba);
        garnet_transition_.push_back(absl::Uniform<int>(rng, 0, size));
      }
      garnet_transition_proba_normalization_.push_back(normalization);
    }
  }
}
References i, size, and absl::Uniform().
Member Function Documentation
ActionToString()
std::string open_spiel::garnet::GarnetState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 248 of file garnet.cc.
{
  if (IsChanceNode() && is_chance_init_) {
    return absl::Substitute("init_state=$0", action);
  }
  return std::to_string(action);
}
References action, open_spiel::State::IsChanceNode(), and absl::Substitute().
ChanceOutcomes()
ActionsAndProbs open_spiel::garnet::GarnetState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 210 of file garnet.cc.
{
  if (is_chance_init_) {
    ActionsAndProbs outcomes;
    for (int i = 0; i < size_; ++i) {
      outcomes.push_back({i, 1. / size_});
    }
    return outcomes;
  }
  ActionsAndProbs outcomes;
  double proba;
  for (int i = 0; i < num_chance_action_; ++i) {
    proba = GetTransitionProba(x_, last_action_, i);
    outcomes.push_back({i, proba});
  }
  return outcomes;
}
References GetTransitionProba(), and i.
Clone()
std::unique_ptr< State > open_spiel::garnet::GarnetState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 321 of file garnet.cc.
{
  return std::unique_ptr<State>(new GarnetState(*this));
}
References GarnetState().
CurrentPlayer()
Player open_spiel::garnet::GarnetState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 73 of file garnet.h.
{
    return IsTerminal() ? kTerminalPlayerId : current_player_;
  }
References IsTerminal(), and open_spiel::kTerminalPlayerId.
Distribution()
std::vector< double > open_spiel::garnet::GarnetState::Distribution () const inline
Definition at line 91 of file garnet.h.
{ return distribution_; }
DistributionSupport()
std::vector< std::string > open_spiel::garnet::GarnetState::DistributionSupport () override virtual
Reimplemented from open_spiel::State.
Definition at line 255 of file garnet.cc.
{
  std::vector<std::string> support;
  support.reserve(size_);
  for (int x = 0; x < size_; ++x) {
    support.push_back(
        StateToString(x, t_, last_action_, kMeanFieldPlayerId, false));
  }
  return support;
}
References open_spiel::kMeanFieldPlayerId, StateToString(), and x.
DoApplyAction()
void open_spiel::garnet::GarnetState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 227 of file garnet.cc.
{
  SPIEL_CHECK_NE(current_player_, kMeanFieldPlayerId);
  return_value_ += Rewards()[0];
  if (is_chance_init_) {
    SPIEL_CHECK_GE(action, 0);
    SPIEL_CHECK_LT(action, size_);
    SPIEL_CHECK_EQ(current_player_, kChancePlayerId);
    x_ = action;
    is_chance_init_ = false;
    current_player_ = 0;
  } else if (current_player_ == kChancePlayerId) {
    x_ = GetTransition(x_, last_action_, action);
    ++t_;
    current_player_ = kMeanFieldPlayerId;
  } else {
    SPIEL_CHECK_EQ(current_player_, 0);
    last_action_ = action;
    current_player_ = kChancePlayerId;
  }
}
References action, GetTransition(), open_spiel::kChancePlayerId, open_spiel::kMeanFieldPlayerId, Rewards(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and SPIEL_CHECK_NE.
GetReward()
double open_spiel::garnet::GarnetState::GetReward (int x, int action) const
Definition at line 193 of file garnet.cc.
{
  return garnet_reward_[x + size_ * action];
}
References action, and x.
Referenced by Rewards().
GetTransition()
int open_spiel::garnet::GarnetState::GetTransition (int x, int action, int chance_action) const
Definition at line 188 of file garnet.cc.
{
  return garnet_transition_[num_chance_action_ * (x + size_ * action) +
                            chance_action];
}
References action, and x.
Referenced by DoApplyAction().
GetTransitionProba()
double open_spiel::garnet::GarnetState::GetTransitionProba (int x, int action, int chance_action) const
Definition at line 180 of file garnet.cc.
{
  return (garnet_transition_proba_unnormalized_[num_chance_action_ *
                                                    (x + size_ * action) +
                                                chance_action] /
          garnet_transition_proba_normalization_[x + size_ * action]);
}
References action, and x.
Referenced by ChanceOutcomes().
InformationStateString()
std::string open_spiel::garnet::GarnetState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 291 of file garnet.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return StateToString(x_, t_, last_action_, current_player_, is_chance_init_);
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and StateToString().
IsTerminal()
bool open_spiel::garnet::GarnetState::IsTerminal () const override virtual
Implements open_spiel::State.
Definition at line 272 of file garnet.cc.
{ return t_ >= horizon_; }
Referenced by CurrentPlayer(), and LegalActions().
LegalActions()
std::vector< Action > open_spiel::garnet::GarnetState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 197 of file garnet.cc.
{
  if (IsTerminal()) return {};
  if (IsChanceNode()) return LegalChanceOutcomes();
  if (IsMeanFieldNode()) return {};
  SPIEL_CHECK_TRUE(IsPlayerNode());
  std::vector<Action> outcomes;
  outcomes.reserve(num_action_);
  for (int i = 0; i < num_action_; ++i) {
    outcomes.push_back(i);
  }
  return outcomes;
}
References i, open_spiel::State::IsChanceNode(), open_spiel::State::IsMeanFieldNode(), open_spiel::State::IsPlayerNode(), IsTerminal(), open_spiel::State::LegalChanceOutcomes(), and SPIEL_CHECK_TRUE.
ObservationString()
std::string open_spiel::garnet::GarnetState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 297 of file garnet.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::garnet::GarnetState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 303 of file garnet.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  SPIEL_CHECK_EQ(values.size(), size_ + horizon_ + 1);
  SPIEL_CHECK_LT(x_, size_);
  SPIEL_CHECK_GE(t_, 0);
  // Allow t_ == horizon_.
  SPIEL_CHECK_LE(t_, horizon_);
  std::fill(values.begin(), values.end(), 0.);
  if (x_ >= 0) {
    values[x_] = 1.;
  }
  // x_ equals -1 for the initial (blank) state, don't set any
  // position bit in that case.
  values[size_ + t_] = 1.;
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::garnet::GarnetState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 283 of file garnet.cc.
{
  return {return_value_ + Rewards()[0]};
}
References Rewards().
Rewards()
std::vector< double > open_spiel::garnet::GarnetState::Rewards () const override virtual
Reimplemented from open_spiel::State.
Definition at line 274 of file garnet.cc.
{
  if (current_player_ != 0) {
    return {0.};
  }
  double r_x = GetReward(x_, last_action_);
  double r_mu = -std::log(distribution_[x_] + kEpsilon);
  return {r_x + eta_ * r_mu};
}
References GetReward().
Referenced by DoApplyAction(), and Returns().
Serialize()
std::string open_spiel::garnet::GarnetState::Serialize () const override virtual
Reimplemented from open_spiel::State.
Definition at line 325 of file garnet.cc.
{
  std::string out =
      absl::StrCat(current_player_, ",", is_chance_init_, ",", x_, ",", t_, ",",
                   last_action_, ",", return_value_, "\n");
  absl::StrAppend(&out, absl::StrJoin(distribution_, ","));
  return out;
}
References out, absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
ToString()
std::string open_spiel::garnet::GarnetState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 287 of file garnet.cc.
{
  return StateToString(x_, t_, last_action_, current_player_, is_chance_init_);
}
References StateToString().
Referenced by ObservationString().
UpdateDistribution()
void open_spiel::garnet::GarnetState::UpdateDistribution (const std::vector< double > & distribution) override virtual
Reimplemented from open_spiel::State.
Definition at line 265 of file garnet.cc.
{
  SPIEL_CHECK_EQ(current_player_, kMeanFieldPlayerId);
  SPIEL_CHECK_EQ(distribution.size(), size_);
  distribution_ = distribution;
  current_player_ = kDefaultPlayerId;
}
References open_spiel::kDefaultPlayerId, open_spiel::kMeanFieldPlayerId, and SPIEL_CHECK_EQ.
The documentation for this class was generated from the following files:
open_spiel/games/mfg/garnet.h
open_spiel/games/mfg/garnet.cc