open spiel: open_spiel::euchre::Trick Class Reference
open_spiel::euchre::Trick Class Reference
#include <euchre.h>
Public Member Functions
Trick ()
Trick (Player leader, Suit trump_suit, int card)
void Play (Player player, int card)
int WinningCard () const
Suit LedSuit () const
Suit TrumpSuit () const
bool TrumpPlayed () const
Player Leader () const
Player Winner () const
std::vector< int > Cards () const
Detailed Description
Definition at line 103 of file euchre.h.
Constructor & Destructor Documentation
Trick() [1/2]
open_spiel::euchre::Trick::Trick () inline
Definition at line 105 of file euchre.h.
: Trick{kInvalidPlayer, Suit::kInvalidSuit, kInvalidAction} {}
Trick() [2/2]
open_spiel::euchre::Trick::Trick (Player leader, Suit trump_suit, int card)
Definition at line 683 of file euchre.cc.
    : winning_card_(card),
      led_suit_(CardSuit(card, trump_suit)),
      trump_suit_(trump_suit),
      trump_played_(trump_suit != Suit::kInvalidSuit &&
                    trump_suit == led_suit_),
      leader_(leader),
      winning_player_(leader),
      cards_{card} {}
Member Function Documentation
Cards()
std::vector< int > open_spiel::euchre::Trick::Cards () const inline
Definition at line 114 of file euchre.h.
{ return cards_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
Leader()
Player open_spiel::euchre::Trick::Leader () const inline
Definition at line 112 of file euchre.h.
{ return leader_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
LedSuit()
Suit open_spiel::euchre::Trick::LedSuit () const inline
Definition at line 109 of file euchre.h.
{ return led_suit_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
Play()
void open_spiel::euchre::Trick::Play (Player player, int card)
Definition at line 694 of file euchre.cc.
{
  cards_.push_back(card);
  bool new_winner = false;
  if (winning_player_ == kInvalidPlayer) new_winner = true;
  if (CardSuit(card, trump_suit_) == trump_suit_) {
    trump_played_ = true;
    if (CardSuit(winning_card_, trump_suit_) == trump_suit_) {
      if (CardRank(card, trump_suit_) > CardRank(winning_card_, trump_suit_)) {
        new_winner = true;
      }
    } else {
      new_winner = true;
    }
  } else {
    if (CardSuit(winning_card_, trump_suit_) != trump_suit_ &&
        CardSuit(winning_card_, trump_suit_) == CardSuit(card, trump_suit_) &&
        CardRank(card, trump_suit_) > CardRank(winning_card_, trump_suit_)) {
      new_winner = true;
    }
  }
  if (new_winner) {
    winning_card_ = card;
    winning_player_ = player;
  }
}
References open_spiel::euchre::CardRank(), open_spiel::euchre::CardSuit(), open_spiel::kInvalidPlayer, and player.
TrumpPlayed()
bool open_spiel::euchre::Trick::TrumpPlayed () const inline
Definition at line 111 of file euchre.h.
{ return trump_played_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
TrumpSuit()
Suit open_spiel::euchre::Trick::TrumpSuit () const inline
Definition at line 110 of file euchre.h.
{ return trump_suit_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
Winner()
Player open_spiel::euchre::Trick::Winner () const inline
Definition at line 113 of file euchre.h.
{ return winning_player_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
WinningCard()
int open_spiel::euchre::Trick::WinningCard () const inline
Definition at line 108 of file euchre.h.
{ return winning_card_; }
Referenced by open_spiel::init_pyspiel_games_euchre().
The documentation for this class was generated from the following files:
open_spiel/games/euchre/euchre.h
open_spiel/games/euchre/euchre.cc