open spiel: open_spiel::algorithms::HistoryTree Class Reference
open_spiel::algorithms::HistoryTree Class Reference
#include <history_tree.h>
Public Member Functions
HistoryTree (std::unique_ptr< State > state, Player player_id)
HistoryNode * Root ()
HistoryNode * GetByHistory (const std::string &history)
HistoryNode * GetByHistory (const State &state)
std::vector< std::string > GetHistories ()
Action NumHistories ()
Detailed Description
Definition at line 85 of file history_tree.h.
Constructor & Destructor Documentation
HistoryTree()
open_spiel::algorithms::HistoryTree::HistoryTree (std::unique_ptr< State > state, Player player_id)
Definition at line 155 of file history_tree.cc.
{
  root_ =
      RecursivelyBuildGameTree(std::move(state), player_id, &state_to_node_);
}
References state.
Member Function Documentation
GetByHistory() [1/2]
HistoryNode * open_spiel::algorithms::HistoryTree::GetByHistory (const State & state) inline
Definition at line 95 of file history_tree.h.
{
    return GetByHistory(state.HistoryString());
  }
References GetByHistory(), and state.
GetByHistory() [2/2]
HistoryNode * open_spiel::algorithms::HistoryTree::GetByHistory (const std::string & history)
Definition at line 139 of file history_tree.cc.
{
  auto it = state_to_node_.find(history);
  if (it == state_to_node_.end()) {
    SpielFatalError(absl::StrCat("Node is null for history: '", history, "'"));
  }
  return it->second;
}
References open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::algorithms::GetAllInfoSets(), GetByHistory(), and open_spiel::algorithms::TabularBestResponse::Value().
GetHistories()
std::vector< std::string > open_spiel::algorithms::HistoryTree::GetHistories ()
Definition at line 147 of file history_tree.cc.
{
  std::vector<std::string> histories;
  histories.reserve(state_to_node_.size());
  for (const auto& [history, _] : state_to_node_) histories.push_back(history);
  return histories;
}
NumHistories()
Action open_spiel::algorithms::HistoryTree::NumHistories () inline
Definition at line 102 of file history_tree.h.
{ return state_to_node_.size(); }
Root()
HistoryNode * open_spiel::algorithms::HistoryTree::Root () inline
Definition at line 92 of file history_tree.h.
{ return root_.get(); }
The documentation for this class was generated from the following files:
open_spiel/algorithms/history_tree.h
open_spiel/algorithms/history_tree.cc