open spiel: open_spiel::algorithms::EFCEState Class Reference
open_spiel::algorithms::EFCEState Class Reference
#include <efce.h>
Public Member Functions
EFCEState (std::shared_ptr< const Game > game, std::unique_ptr< State > state, CorrDistConfig config, const CorrelationDevice &mu)
std::unique_ptr< State > Clone () const override
std::vector< Action > LegalChanceOutcomes () const override
Player CurrentPlayer () const override
ActionsAndProbs ChanceOutcomes () const override
std::vector< Action > LegalActions () const override
std::string InformationStateString (Player player) const override
std::string ToString () const
bool HasDefected (Player player) const
Public Member Functions inherited from open_spiel::WrappedState
WrappedState (std::shared_ptr< const Game > game, std::unique_ptr< State > state)
WrappedState (const WrappedState &other)
Player CurrentPlayer () const override
std::vector< Action > LegalActions (Player player) const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action_id) const override
std::string ToString () const override
bool IsTerminal () const override
std::vector< double > Rewards () const override
std::vector< double > Returns () const override
std::string InformationStateString (Player player) const override
void InformationStateTensor (Player player, absl::Span< float > values) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
void UndoAction (Player player, Action action) override
ActionsAndProbs ChanceOutcomes () const override
std::vector< Action > LegalChanceOutcomes () const override
const State & GetWrappedState () const
std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const override
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
Action CurRecommendation () const
void DoApplyAction (Action action_id) override
Protected Member Functions inherited from open_spiel::WrappedState
void DoApplyAction (Action action_id) override
void DoApplyActions (const std::vector< Action > &actions) override
Additional Inherited Members
Protected Attributes inherited from open_spiel::WrappedState
std::unique_ptr< State > state_
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 53 of file efce.h.
Constructor & Destructor Documentation
EFCEState()
open_spiel::algorithms::EFCEState::EFCEState (std::shared_ptr< const Game > game, std::unique_ptr< State > state, CorrDistConfig config, const CorrelationDevice & mu)
Definition at line 23 of file efce.cc.
    : WrappedState(game, std::move(state)),
      config_(config),
      mu_(mu),
      rec_index_(-1),
      defected_(game->NumPlayers(), 0),
      recommendation_seq_(game->NumPlayers(), std::vector<Action>({})) {}
Member Function Documentation
ChanceOutcomes()
ActionsAndProbs open_spiel::algorithms::EFCEState::ChanceOutcomes () const override virtual
Reimplemented from open_spiel::State.
Definition at line 42 of file efce.cc.
{
  if (rec_index_ < 0) {
    ActionsAndProbs outcomes;
    for (int i = 0; i < mu_.size(); ++i) {
      outcomes.push_back({i, mu_[i].first});
    }
    return outcomes;
  } else {
    return state_->ChanceOutcomes();
  }
}
References i, and open_spiel::WrappedState::state_.
Clone()
std::unique_ptr< State > open_spiel::algorithms::EFCEState::Clone () const inline override virtual
Implements open_spiel::WrappedState.
Definition at line 58 of file efce.h.
{
    return std::make_unique<EFCEState>(*this);
  }
CurRecommendation()
Action open_spiel::algorithms::EFCEState::CurRecommendation () const protected
Definition at line 97 of file efce.cc.
{
  SPIEL_CHECK_GE(rec_index_, 0);
  SPIEL_CHECK_LT(rec_index_, mu_.size());
  ActionsAndProbs actions_and_probs =
      mu_[rec_index_].second.GetStatePolicy(state_->InformationStateString());
  Action rec_action = GetAction(actions_and_probs);
  SPIEL_CHECK_TRUE(rec_action != kInvalidAction);
  return rec_action;
}
References actions_and_probs, open_spiel::GetAction(), open_spiel::kInvalidAction, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, and open_spiel::WrappedState::state_.
Referenced by DoApplyAction(), and InformationStateString().
CurrentPlayer()
Player open_spiel::algorithms::EFCEState::CurrentPlayer () const override virtual
Implements open_spiel::State.
Definition at line 33 of file efce.cc.
{
  // Only override this in the first chance actions.
  if (rec_index_ < 0) {
    return kChancePlayerId;
  } else {
    return state_->CurrentPlayer();
  }
}
References open_spiel::kChancePlayerId, and open_spiel::WrappedState::state_.
Referenced by DoApplyAction(), and ToString().
DoApplyAction()
void open_spiel::algorithms::EFCEState::DoApplyAction (Action action_id) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 107 of file efce.cc.
{
  if (rec_index_ < 0) {
    // Pick the joint policy which will provide recommendations.
    rec_index_ = action_id;
    SPIEL_CHECK_GE(rec_index_, 0);
    SPIEL_CHECK_LT(rec_index_, mu_.size());
  } else if (state_->IsChanceNode()) {
    // Regular chance node
    state_->ApplyAction(action_id);
  } else {
    // Check for defection at this point.
    const Action recommendation = CurRecommendation();
    Player cur_player = CurrentPlayer();
    SPIEL_CHECK_GE(cur_player, 0);
    SPIEL_CHECK_LT(cur_player, game_->NumPlayers());
    // If they have defected, don't add to the sequence
    if (!HasDefected(cur_player)) {
      recommendation_seq_[cur_player].push_back(recommendation);
      // If they chose an action other than the recommendation, they have now
      // defected.
      if (action_id != recommendation) {
        defected_[cur_player] = 1;
      }
    }
    state_->ApplyAction(action_id);
  }
}
References CurRecommendation(), CurrentPlayer(), open_spiel::State::game_, HasDefected(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, and open_spiel::WrappedState::state_.
HasDefected()
bool open_spiel::algorithms::EFCEState::HasDefected (Player player) const
Definition at line 91 of file efce.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, game_->NumPlayers());
  return defected_[player] == 1;
}
References open_spiel::State::game_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Referenced by DoApplyAction(), and InformationStateString().
InformationStateString()
std::string open_spiel::algorithms::EFCEState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 66 of file efce.cc.
{
  // should look like <infoset string> <delimiter> <recommendation sequence,
  // (including current recommendation)>
  SPIEL_CHECK_FALSE(IsChanceNode());
  std::string rec_str = absl::StrJoin(recommendation_seq_[player], ",");
  if (!HasDefected(player)) {
    absl::StrAppend(&rec_str, ",", CurRecommendation());
  }
  std::string infoset_str = state_->InformationStateString(player);
  SPIEL_CHECK_EQ(infoset_str.find(config_.recommendation_delimiter),
                 std::string::npos);
  return absl::StrCat(infoset_str, config_.recommendation_delimiter, rec_str);
}
References CurRecommendation(), HasDefected(), open_spiel::State::IsChanceNode(), player, open_spiel::algorithms::CorrDistConfig::recommendation_delimiter, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, open_spiel::WrappedState::state_, absl::StrAppend(), absl::StrCat(), and absl::StrJoin().
LegalActions()
std::vector< Action > open_spiel::algorithms::EFCEState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 54 of file efce.cc.
{
  SPIEL_CHECK_FALSE(IsSimultaneousNode());
  if (IsTerminal()) {
    return {};
  } else if (IsChanceNode()) {
    return LegalChanceOutcomes();
  }
  return state_->LegalActions();
}
References open_spiel::State::IsChanceNode(), open_spiel::State::IsSimultaneousNode(), open_spiel::WrappedState::IsTerminal(), LegalChanceOutcomes(), SPIEL_CHECK_FALSE, and open_spiel::WrappedState::state_.
LegalChanceOutcomes()
std::vector< Action > open_spiel::algorithms::EFCEState::LegalChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::State.
Definition at line 65 of file efce.h.
{
    return State::LegalChanceOutcomes();
  }
References open_spiel::State::LegalChanceOutcomes().
Referenced by LegalActions().
ToString()
std::string open_spiel::algorithms::EFCEState::ToString () const virtual
Implements open_spiel::State.
Definition at line 80 of file efce.cc.
{
  std::string state_str = absl::StrFormat(
      "%s\nCur player: %i\nRec index %i\nDefected %s", state_->ToString(),
      CurrentPlayer(), rec_index_, absl::StrJoin(defected_, " "));
  for (Player p = 0; p < state_->NumPlayers(); ++p) {
    absl::StrAppend(&state_str, "\nPlayer ", p, " recommendation seq: ",
                    absl::StrJoin(recommendation_seq_[p], ","));
  }
  return state_str;
}
References CurrentPlayer(), open_spiel::WrappedState::state_, absl::StrAppend(), absl::StrFormat(), and absl::StrJoin().
The documentation for this class was generated from the following files:
open_spiel/algorithms/corr_dist/efce.h
open_spiel/algorithms/corr_dist/efce.cc