open spiel: open_spiel::cursor_go::CursorGoState Class Reference
open_spiel::cursor_go::CursorGoState Class Reference
#include <cursor_go.h>
Public Member Functions
CursorGoState (std::shared_ptr< const Game > game, int board_size, float komi, int handicap, int max_cursor_moves)
Player CurrentPlayer () const override
std::vector< Action > LegalActions () const override
std::string ActionToString (Player player, Action action) const override
std::string ToString () const override
bool IsTerminal () const override
std::string InformationStateString (Player player) const override
std::string ObservationString (Player player) const override
void ObservationTensor (Player player, absl::Span< float > values) const override
std::vector< double > Returns () const override
std::unique_ptr< State > Clone () const override
const GoBoard & board () const
Public Member Functions inherited from open_spiel::State
virtual ~State ()=default
State (std::shared_ptr< const Game > game)
State (const State &)=default
virtual void ApplyAction (Action action_id)
virtual void ApplyActionWithLegalityCheck (Action action_id)
virtual std::vector< Action > LegalActions (Player player) const
std::vector< int > LegalActionsMask (Player player) const
std::vector< int > LegalActionsMask () const
std::string ActionToString (Action action_id) const
virtual Action StringToAction (Player player, const std::string &action_str) const
Action StringToAction (const std::string &action_str) const
virtual bool operator== (const State &other) const
virtual std::vector< double > Rewards () const
virtual double PlayerReward (Player player) const
virtual double PlayerReturn (Player player) const
virtual bool IsChanceNode () const
virtual bool IsMeanFieldNode () const
virtual bool IsPlayerNode () const
bool IsSimultaneousNode () const
bool IsPlayerActing (Player player) const
std::vector< Action > History () const
const std::vector< PlayerAction > & FullHistory () const
std::string HistoryString () const
int MoveNumber () const
bool IsInitialState () const
std::string InformationStateString () const
virtual void InformationStateTensor (Player player, absl::Span< float > values) const
std::vector< float > InformationStateTensor (Player player) const
std::vector< float > InformationStateTensor () const
virtual void InformationStateTensor (Player player, std::vector< float > *values) const
std::string ObservationString () const
std::vector< float > ObservationTensor (Player player) const
std::vector< float > ObservationTensor () const
void ObservationTensor (Player player, std::vector< float > *values) const
std::unique_ptr< State > Child (Action action) const
virtual void UndoAction (Player player, Action action)
void ApplyActions (const std::vector< Action > &actions)
void ApplyActionsWithLegalityChecks (const std::vector< Action > &actions)
int NumDistinctActions () const
int NumPlayers () const
std::shared_ptr< const Game > GetGame () const
virtual ActionsAndProbs ChanceOutcomes () const
virtual std::vector< Action > LegalChanceOutcomes () const
StateType GetType () const
virtual std::string Serialize () const
virtual std::unique_ptr< State > ResampleFromInfostate (int player_id, std::function< double()> rng) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate (int player_id) const
virtual std::unique_ptr< HistoryDistribution > GetHistoriesConsistentWithInfostate () const
virtual std::vector< Action > ActionsConsistentWithInformationFrom (Action action) const
virtual std::vector< std::string > DistributionSupport ()
virtual void UpdateDistribution (const std::vector< double > &distribution)
virtual int MeanFieldPopulation () const
Protected Member Functions
void DoApplyAction (Action action) override
Protected Member Functions inherited from open_spiel::State
virtual void DoApplyActions (const std::vector< Action > &actions)
Additional Inherited Members
Protected Attributes inherited from open_spiel::State
const std::shared_ptr< const Game > game_
const int num_distinct_actions_
const int num_players_
std::vector< PlayerAction > history_
int move_number_
Detailed Description
Definition at line 82 of file cursor_go.h.
Constructor & Destructor Documentation
CursorGoState()
open_spiel::cursor_go::CursorGoState::CursorGoState (std::shared_ptr< const Game > game, int board_size, float komi, int handicap, int max_cursor_moves)
Definition at line 91 of file cursor_go.cc.
    : State(game),
      board_(board_size),
      komi_(komi),
      handicap_(handicap),
      max_cursor_moves_(max_cursor_moves),
      to_play_(GoColor::kBlack) {
  ResetBoard();
}
Referenced by Clone().
Member Function Documentation
ActionToString()
std::string open_spiel::cursor_go::CursorGoState::ActionToString (Player player, Action action) const override virtual
Implements open_spiel::State.
Definition at line 164 of file cursor_go.cc.
{
  static constexpr std::array<absl::string_view, kNumDistinctActions>
      kActionNames{"Up", "Down", "Left", "Right", "Place Stone", "Pass"};
  if (action < 0 || action >= kActionNames.size()) {
    return absl::StrFormat("invalid action %d", action);
  }
  return std::string(kActionNames[action]);
}
References action, and absl::StrFormat().
board()
const GoBoard & open_spiel::cursor_go::CursorGoState::board () const inline
Definition at line 109 of file cursor_go.h.
{ return board_; }
Referenced by open_spiel.python.games.tic_tac_toe.TicTacToeState::__str__(), open_spiel.python.games.tic_tac_toe.TicTacToeState::_apply_action(), and open_spiel.python.games.tic_tac_toe.TicTacToeState::_legal_actions().
Clone()
std::unique_ptr< State > open_spiel::cursor_go::CursorGoState::Clone () const override virtual
Implements open_spiel::State.
Definition at line 215 of file cursor_go.cc.
{
  return std::unique_ptr<State>(new CursorGoState(*this));
}
References CursorGoState().
CurrentPlayer()
Player open_spiel::cursor_go::CursorGoState::CurrentPlayer () const inline override virtual
Implements open_spiel::State.
Definition at line 88 of file cursor_go.h.
{
    return is_terminal_ ? kTerminalPlayerId : ColorToPlayer(to_play_);
  }
References open_spiel::cursor_go::ColorToPlayer(), and open_spiel::kTerminalPlayerId.
DoApplyAction()
void open_spiel::cursor_go::CursorGoState::DoApplyAction (Action action) override protected virtual
Reimplemented from open_spiel::State.
Definition at line 219 of file cursor_go.cc.
{
  if (action == kActionPlaceStone || action == kActionPass) {
    VirtualPoint point =
        (action == kActionPass)
            ? go::kVirtualPass
            : VirtualPointFrom2DPoint(cursor_[ColorToPlayer(to_play_)]);
    SPIEL_CHECK_TRUE(board_.PlayMove(point, to_play_));
    is_terminal_ = last_move_was_pass_ && (action == kActionPass);
    last_move_was_pass_ = (action == kActionPass);
    to_play_ = OppColor(to_play_);
    cursor_moves_count_ = 0;
    bool was_inserted = repetitions_.insert(board_.HashValue()).second;
    if (!was_inserted && action == kActionPlaceStone) {
      // We have encountered this position before.
      superko_ = true;
    }
  } else {
    switch (action) {
      case kActionUp:
        cursor_[ColorToPlayer(to_play_)].first++;
        break;
      case kActionDown:
        cursor_[ColorToPlayer(to_play_)].first--;
        break;
      case kActionLeft:
        cursor_[ColorToPlayer(to_play_)].second--;
        break;
      case kActionRight:
        cursor_[ColorToPlayer(to_play_)].second++;
        break;
      default:
        SpielFatalError(absl::StrCat("Invalid action ", action));
    }
    ++cursor_moves_count_;
  }
}
References action, open_spiel::cursor_go::ColorToPlayer(), open_spiel::go::GoBoard::HashValue(), open_spiel::cursor_go::kActionDown, open_spiel::cursor_go::kActionLeft, open_spiel::cursor_go::kActionPass, open_spiel::cursor_go::kActionPlaceStone, open_spiel::cursor_go::kActionRight, open_spiel::cursor_go::kActionUp, open_spiel::go::kVirtualPass, open_spiel::go::GoBoard::PlayMove(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), and absl::StrCat().
InformationStateString()
std::string open_spiel::cursor_go::CursorGoState::InformationStateString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 102 of file cursor_go.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return HistoryString();
}
References open_spiel::State::HistoryString(), open_spiel::State::num_players_, player, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
IsTerminal()
bool open_spiel::cursor_go::CursorGoState::IsTerminal () const inline override virtual
Implements open_spiel::State.
Definition at line 95 of file cursor_go.h.
{ return is_terminal_; }
LegalActions()
std::vector< Action > open_spiel::cursor_go::CursorGoState::LegalActions () const override virtual
Implements open_spiel::State.
Definition at line 147 of file cursor_go.cc.
{
  std::vector<Action> actions{};
  if (is_terminal_) return actions;
  const auto cursor = cursor_[ColorToPlayer(to_play_)];
  if (cursor_moves_count_ < max_cursor_moves_) {
    const auto [row, col] = cursor;
    if (row < board_.board_size() - 1) actions.push_back(kActionUp);
    if (row > 0) actions.push_back(kActionDown);
    if (col > 0) actions.push_back(kActionLeft);
    if (col < board_.board_size() - 1) actions.push_back(kActionRight);
  }
  if (board_.IsLegalMove(VirtualPointFrom2DPoint(cursor), to_play_))
    actions.push_back(kActionPlaceStone);
  actions.push_back(kActionPass);
  return actions;
}
References open_spiel::go::GoBoard::board_size(), open_spiel::cursor_go::ColorToPlayer(), open_spiel::go::GoBoard::IsLegalMove(), open_spiel::cursor_go::kActionDown, open_spiel::cursor_go::kActionLeft, open_spiel::cursor_go::kActionPass, open_spiel::cursor_go::kActionPlaceStone, open_spiel::cursor_go::kActionRight, and open_spiel::cursor_go::kActionUp.
ObservationString()
std::string open_spiel::cursor_go::CursorGoState::ObservationString (Player player) const override virtual
Reimplemented from open_spiel::State.
Definition at line 108 of file cursor_go.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  return ToString();
}
References open_spiel::State::num_players_, player, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and ToString().
ObservationTensor()
void open_spiel::cursor_go::CursorGoState::ObservationTensor (Player player, absl::Span< float > values) const override virtual
Reimplemented from open_spiel::State.
Definition at line 114 of file cursor_go.cc.
{
  SPIEL_CHECK_GE(player, 0);
  SPIEL_CHECK_LT(player, num_players_);
  int num_cells = board_.board_size() * board_.board_size();
  SPIEL_CHECK_EQ(values.size(), num_cells * (kCellStates + 3));
  std::fill(values.begin(), values.end(), 0.);
  // Add planes: black, white, empty.
  int cell = 0;
  for (VirtualPoint p : BoardPoints(board_.board_size())) {
    int color_val = static_cast<int>(board_.PointColor(p));
    values[num_cells * color_val + cell] = 1.0;
    ++cell;
  }
  SPIEL_CHECK_EQ(cell, num_cells);
  // Fourth plane for cursor position.
  const auto [row, col] = cursor_[ColorToPlayer(to_play_)];
  const int cursor_cell = row * board_.board_size() + col;
  values[num_cells * kCellStates + cursor_cell] = 1.0;
  // Add a fifth binary plane for komi (whether white is to play).
  std::fill(values.begin() + ((1 + kCellStates) * num_cells),
            values.begin() + ((2 + kCellStates) * num_cells),
            (to_play_ == GoColor::kWhite ? 1.0 : 0.0));
  // Add a sixth binary plane for the number of cursor moves.
  std::fill(values.begin() + ((2 + kCellStates) * num_cells), values.end(),
            static_cast<float>(cursor_moves_count_) / max_cursor_moves_);
}
References open_spiel::go::GoBoard::board_size(), open_spiel::cursor_go::ColorToPlayer(), open_spiel::State::num_players_, player, open_spiel::go::GoBoard::PointColor(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and values.
Returns()
std::vector< double > open_spiel::cursor_go::CursorGoState::Returns () const override virtual
Implements open_spiel::State.
Definition at line 187 of file cursor_go.cc.
{
  if (!is_terminal_) return {0.0, 0.0};
  if (superko_) {
    // Superko rules (https://senseis.xmp.net/?Superko) are complex and vary
    // between rulesets.
    // For simplicity and because superkos are very rare, we just treat them as
    // a draw.
    return {kDrawUtility, kDrawUtility};
  }
  // Score with Tromp-Taylor.
  float black_score = TrompTaylorScore(board_, komi_, handicap_);
  std::vector<double> returns(kNumPlayers);
  if (black_score > 0) {
    returns[ColorToPlayer(GoColor::kBlack)] = kWinUtility;
    returns[ColorToPlayer(GoColor::kWhite)] = kLossUtility;
  } else if (black_score < 0) {
    returns[ColorToPlayer(GoColor::kBlack)] = kLossUtility;
    returns[ColorToPlayer(GoColor::kWhite)] = kWinUtility;
  } else {
    returns[ColorToPlayer(GoColor::kBlack)] = kDrawUtility;
    returns[ColorToPlayer(GoColor::kWhite)] = kDrawUtility;
  }
  return returns;
}
References open_spiel::cursor_go::ColorToPlayer(), open_spiel::cursor_go::kDrawUtility, open_spiel::cursor_go::kLossUtility, open_spiel::cursor_go::kNumPlayers, and open_spiel::cursor_go::kWinUtility.
ToString()
std::string open_spiel::cursor_go::CursorGoState::ToString () const override virtual
Implements open_spiel::State.
Definition at line 173 of file cursor_go.cc.
{
  std::stringstream ss;
  ss << "CursorGoState(komi=" << komi_;
  if (!is_terminal_) ss << ", to_play=" << GoColorToString(to_play_);
  ss << ", history.size()=" << history_.size();
  if (!is_terminal_) ss << ", cursor_moves_count=" << cursor_moves_count_;
  ss << ")\n" << board_;
  if (!is_terminal_)
    ss << "\nCursor: "
       << VirtualPointToString(
              VirtualPointFrom2DPoint(cursor_[ColorToPlayer(to_play_)]));
  return ss.str();
}
References open_spiel::cursor_go::ColorToPlayer(), and open_spiel::State::history_.
Referenced by ObservationString().
The documentation for this class was generated from the following files:
open_spiel/games/cursor_go/cursor_go.h
open_spiel/games/cursor_go/cursor_go.cc