open spiel: absl::inlined_vector_internal::AllocationTransaction< A > Class Template Reference
absl::inlined_vector_internal::AllocationTransaction< A > Class Template Reference
#include <inlined_vector.h>
Public Member Functions
AllocationTransaction (A &allocator)
~AllocationTransaction ()
AllocationTransaction (const AllocationTransaction &)=delete
void operator= (const AllocationTransaction &)=delete
A & GetAllocator ()
Pointer< A > & GetData ()
SizeType< A > & GetCapacity ()
bool DidAllocate ()
Pointer< A > Allocate (SizeType< A > requested_capacity)
ABSL_MUST_USE_RESULT Allocation< A > Release () &&
Detailed Description
template<typename A>
class absl::inlined_vector_internal::AllocationTransaction< A >
Definition at line 222 of file inlined_vector.h.
Constructor & Destructor Documentation
AllocationTransaction() [1/2]
template<typename A > absl::inlined_vector_internal::AllocationTransaction< A >::AllocationTransaction (A & allocator) inline explicit
Definition at line 224 of file inlined_vector.h.
      : allocator_data_(allocator, nullptr), capacity_(0) {}
~AllocationTransaction()
template<typename A > absl::inlined_vector_internal::AllocationTransaction< A >::~AllocationTransaction () inline
Definition at line 227 of file inlined_vector.h.
{
    if (DidAllocate()) {
      MallocAdapter<A>::Deallocate(GetAllocator(), GetData(), GetCapacity());
    }
  }
References absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned >::Deallocate(), absl::inlined_vector_internal::AllocationTransaction< A >::DidAllocate(), absl::inlined_vector_internal::AllocationTransaction< A >::GetAllocator(), absl::inlined_vector_internal::AllocationTransaction< A >::GetCapacity(), and absl::inlined_vector_internal::AllocationTransaction< A >::GetData().
AllocationTransaction() [2/2]
template<typename A > absl::inlined_vector_internal::AllocationTransaction< A >::AllocationTransaction (const AllocationTransaction< A > &) delete
Member Function Documentation
Allocate()
template<typename A > Pointer< A > absl::inlined_vector_internal::AllocationTransaction< A >::Allocate (SizeType< A > requested_capacity) inline
Definition at line 242 of file inlined_vector.h.
{
    Allocation<A> result =
        MallocAdapter<A>::Allocate(GetAllocator(), requested_capacity);
    GetData() = result.data;
    GetCapacity() = result.capacity;
    return result.data;
  }
References absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned >::Allocate(), absl::inlined_vector_internal::Allocation< A >::capacity, absl::inlined_vector_internal::Allocation< A >::data, absl::inlined_vector_internal::AllocationTransaction< A >::GetAllocator(), absl::inlined_vector_internal::AllocationTransaction< A >::GetCapacity(), and absl::inlined_vector_internal::AllocationTransaction< A >::GetData().
Referenced by absl::inlined_vector_internal::Storage< T, N, A >::Assign(), absl::inlined_vector_internal::Storage< T, N, A >::EmplaceBackSlow(), absl::inlined_vector_internal::Storage< T, N, A >::Insert(), absl::inlined_vector_internal::Storage< T, N, A >::Reserve(), absl::inlined_vector_internal::Storage< T, N, A >::Resize(), and absl::inlined_vector_internal::Storage< T, N, A >::ShrinkToFit().
DidAllocate()
template<typename A > bool absl::inlined_vector_internal::AllocationTransaction< A >::DidAllocate () inline
Definition at line 240 of file inlined_vector.h.
{ return GetData() != nullptr; }
References absl::inlined_vector_internal::AllocationTransaction< A >::GetData().
Referenced by absl::inlined_vector_internal::Storage< T, N, A >::Assign(), absl::inlined_vector_internal::Storage< T, N, A >::ShrinkToFit(), and absl::inlined_vector_internal::AllocationTransaction< A >::~AllocationTransaction().
GetAllocator()
template<typename A > A & absl::inlined_vector_internal::AllocationTransaction< A >::GetAllocator () inline
Definition at line 236 of file inlined_vector.h.
{ return allocator_data_.template get<0>(); }
References absl::get().
Referenced by absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), and absl::inlined_vector_internal::AllocationTransaction< A >::~AllocationTransaction().
GetCapacity()
template<typename A > SizeType< A > & absl::inlined_vector_internal::AllocationTransaction< A >::GetCapacity () inline
Definition at line 238 of file inlined_vector.h.
{ return capacity_; }
Referenced by absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), absl::inlined_vector_internal::AllocationTransaction< A >::Release(), absl::inlined_vector_internal::Storage< T, N, A >::ShrinkToFit(), and absl::inlined_vector_internal::AllocationTransaction< A >::~AllocationTransaction().
GetData()
template<typename A > Pointer< A > & absl::inlined_vector_internal::AllocationTransaction< A >::GetData () inline
Definition at line 237 of file inlined_vector.h.
{ return allocator_data_.template get<1>(); }
References absl::get().
Referenced by absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), absl::inlined_vector_internal::AllocationTransaction< A >::DidAllocate(), absl::inlined_vector_internal::Storage< T, N, A >::EmplaceBackSlow(), absl::inlined_vector_internal::AllocationTransaction< A >::Release(), and absl::inlined_vector_internal::AllocationTransaction< A >::~AllocationTransaction().
operator=()
template<typename A > void absl::inlined_vector_internal::AllocationTransaction< A >::operator= (const AllocationTransaction< A > &) delete
Release()
template<typename A > ABSL_MUST_USE_RESULT Allocation< A > absl::inlined_vector_internal::AllocationTransaction< A >::Release () && inline
Definition at line 250 of file inlined_vector.h.
{
    Allocation<A> result = {GetData(), GetCapacity()};
    Reset();
    return result;
  }
References absl::inlined_vector_internal::AllocationTransaction< A >::GetCapacity(), and absl::inlined_vector_internal::AllocationTransaction< A >::GetData().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/inlined_vector.h