open spiel: open_spiel.python.algorithms.mcts_test.MctsBotTest Class Reference
open_spiel.python.algorithms.mcts_test.MctsBotTest Class Reference
Public Member Functions
assertTTTStateStr (self, state, expected)
test_can_play_tic_tac_toe (self)
test_can_play_both_sides (self)
test_can_play_single_player (self)
test_throws_on_simultaneous_game (self)
test_can_play_three_player_stochastic_games (self)
test_solve_draw (self)
test_solve_loss (self)
test_solve_win (self)
assertBestChild (self, choice, children)
test_choose_most_visited_when_not_solved (self)
test_choose_win_over_most_visited (self)
test_choose_best_over_good (self)
test_choose_bad_over_worst (self)
test_choose_positive_reward_over_promising (self)
test_choose_most_visited_over_loss (self)
test_choose_most_visited_over_draw (self)
test_choose_uncertainty_over_most_visited_loss (self)
test_choose_slowest_loss (self)
Detailed Description
Definition at line 60 of file mcts_test.py.
Member Function Documentation
assertBestChild()
open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild (self, choice, children)
Definition at line 151 of file mcts_test.py.
  def assertBestChild(self, choice, children):
    # If this causes flakiness, the key in `SearchNode.best_child` is bad.
    random.shuffle(children)
    root = make_node(-1, children=children)
    self.assertEqual(root.best_child().action, choice)
References open_spiel.python.algorithms.mcts_test.make_node().
Referenced by open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_bad_over_worst(), open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_best_over_good(), open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_most_visited_over_draw(), open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_most_visited_over_loss(), open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_most_visited_when_not_solved(), open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_positive_reward_over_promising(), open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_slowest_loss(), open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_uncertainty_over_most_visited_loss(), and open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_win_over_most_visited().
assertTTTStateStr()
open_spiel.python.algorithms.mcts_test.MctsBotTest.assertTTTStateStr (self, state, expected)
Definition at line 62 of file mcts_test.py.
  def assertTTTStateStr(self, state, expected):
    expected = expected.replace(" ", "").strip()
    self.assertEqual(str(state), expected)
Referenced by open_spiel.python.algorithms.mcts_test.MctsBotTest.test_solve_draw(), open_spiel.python.algorithms.mcts_test.MctsBotTest.test_solve_loss(), and open_spiel.python.algorithms.mcts_test.MctsBotTest.test_solve_win().
test_can_play_both_sides()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_can_play_both_sides (self)
Definition at line 77 of file mcts_test.py.
  def test_can_play_both_sides(self):
    game = pyspiel.load_game("tic_tac_toe")
    bot = mcts.MCTSBot(game, UCT_C, max_simulations=100,
                       evaluator=mcts.RandomRolloutEvaluator(n_rollouts=20))
    bots = [bot, bot]
    v = evaluate_bots.evaluate_bots(game.new_initial_state(), bots, np.random)
    self.assertEqual(v[0] + v[1], 0)
test_can_play_single_player()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_can_play_single_player (self)
Definition at line 85 of file mcts_test.py.
  def test_can_play_single_player(self):
    game = pyspiel.load_game("catch")
    max_simulations = 100
    evaluator = mcts.RandomRolloutEvaluator(n_rollouts=20)
    bots = [mcts.MCTSBot(game, UCT_C, max_simulations, evaluator)]
    v = evaluate_bots.evaluate_bots(game.new_initial_state(), bots, np.random)
    self.assertGreater(v[0], 0)
test_can_play_three_player_stochastic_games()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_can_play_three_player_stochastic_games (self)
Definition at line 99 of file mcts_test.py.
  def test_can_play_three_player_stochastic_games(self):
    game = pyspiel.load_game("pig(players=3,winscore=20,horizon=30)")
    max_simulations = 100
    evaluator = mcts.RandomRolloutEvaluator(n_rollouts=5)
    bots = [
        mcts.MCTSBot(game, UCT_C, max_simulations, evaluator),
        mcts.MCTSBot(game, UCT_C, max_simulations, evaluator),
        mcts.MCTSBot(game, UCT_C, max_simulations, evaluator),
    ]
    v = evaluate_bots.evaluate_bots(game.new_initial_state(), bots, np.random)
    self.assertEqual(sum(v), 0)
test_can_play_tic_tac_toe()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_can_play_tic_tac_toe (self)
Definition at line 66 of file mcts_test.py.
  def test_can_play_tic_tac_toe(self):
    game = pyspiel.load_game("tic_tac_toe")
    max_simulations = 100
    evaluator = mcts.RandomRolloutEvaluator(n_rollouts=20)
    bots = [
        mcts.MCTSBot(game, UCT_C, max_simulations, evaluator),
        mcts.MCTSBot(game, UCT_C, max_simulations, evaluator),
    ]
    v = evaluate_bots.evaluate_bots(game.new_initial_state(), bots, np.random)
    self.assertEqual(v[0] + v[1], 0)
test_choose_bad_over_worst()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_bad_over_worst (self)
Definition at line 175 of file mcts_test.py.
  def test_choose_bad_over_worst(self):
    self.assertBestChild(0, [
        make_node(0, explore_count=50, total_reward=30, outcome=[-0.5]),
        make_node(1, explore_count=40, total_reward=40, outcome=[-0.8]),
    ])
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild(), and open_spiel.python.algorithms.mcts_test.make_node().
test_choose_best_over_good()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_best_over_good (self)
Definition at line 169 of file mcts_test.py.
  def test_choose_best_over_good(self):
    self.assertBestChild(1, [
        make_node(0, explore_count=50, total_reward=30, outcome=[0.5]),
        make_node(1, explore_count=40, total_reward=40, outcome=[0.8]),
    ])
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild(), and open_spiel.python.algorithms.mcts_test.make_node().
test_choose_most_visited_over_draw()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_most_visited_over_draw (self)
Definition at line 196 of file mcts_test.py.
  def test_choose_most_visited_over_draw(self):
    self.assertBestChild(0, [
        make_node(0, explore_count=50, total_reward=30),
        make_node(1, explore_count=40, total_reward=40, outcome=[0]),
    ])
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild(), and open_spiel.python.algorithms.mcts_test.make_node().
test_choose_most_visited_over_loss()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_most_visited_over_loss (self)
Definition at line 190 of file mcts_test.py.
  def test_choose_most_visited_over_loss(self):
    self.assertBestChild(0, [
        make_node(0, explore_count=50, total_reward=30),
        make_node(1, explore_count=40, total_reward=40, outcome=[-1]),
    ])
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild(), and open_spiel.python.algorithms.mcts_test.make_node().
test_choose_most_visited_when_not_solved()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_most_visited_when_not_solved (self)
Definition at line 157 of file mcts_test.py.
  def test_choose_most_visited_when_not_solved(self):
    self.assertBestChild(0, [
        make_node(0, explore_count=50, total_reward=30),
        make_node(1, explore_count=40, total_reward=40),
    ])
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild(), and open_spiel.python.algorithms.mcts_test.make_node().
test_choose_positive_reward_over_promising()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_positive_reward_over_promising (self)
Definition at line 181 of file mcts_test.py.
  def test_choose_positive_reward_over_promising(self):
    self.assertBestChild(
        1,
        [
            make_node(0, explore_count=50, total_reward=40),  # more promising
            make_node(1, explore_count=10, total_reward=1, outcome=[0.1
                                                                   ]),  # solved
        ])
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild(), and open_spiel.python.algorithms.mcts_test.make_node().
test_choose_slowest_loss()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_slowest_loss (self)
Definition at line 208 of file mcts_test.py.
  def test_choose_slowest_loss(self):
    self.assertBestChild(1, [
        make_node(0, explore_count=50, total_reward=10, outcome=[-1]),
        make_node(1, explore_count=60, total_reward=15, outcome=[-1]),
    ])
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild(), and open_spiel.python.algorithms.mcts_test.make_node().
test_choose_uncertainty_over_most_visited_loss()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_uncertainty_over_most_visited_loss (self)
Definition at line 202 of file mcts_test.py.
  def test_choose_uncertainty_over_most_visited_loss(self):
    self.assertBestChild(1, [
        make_node(0, explore_count=50, total_reward=30, outcome=[-1]),
        make_node(1, explore_count=40, total_reward=40),
    ])
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild(), and open_spiel.python.algorithms.mcts_test.make_node().
test_choose_win_over_most_visited()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_choose_win_over_most_visited (self)
Definition at line 163 of file mcts_test.py.
  def test_choose_win_over_most_visited(self):
    self.assertBestChild(1, [
        make_node(0, explore_count=50, total_reward=30),
        make_node(1, explore_count=40, total_reward=40, outcome=[1]),
    ])
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertBestChild(), and open_spiel.python.algorithms.mcts_test.make_node().
test_solve_draw()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_solve_draw (self)
Definition at line 111 of file mcts_test.py.
  def test_solve_draw(self):
    root, state = search_tic_tac_toe_state("x(1,1) o(0,0) x(2,2)")
    self.assertTTTStateStr(state, """
        o..
        .x.
        ..x
    """)
    self.assertEqual(root.outcome[root.player], 0)
    for c in root.children:
      self.assertLessEqual(c.outcome[c.player], 0)  # No winning moves.
    best = root.best_child()
    self.assertEqual(best.outcome[best.player], 0)
    self.assertIn(
        state.action_to_string(best.player, best.action),
        ("o(0,2)", "o(2,0)"))  # All others lose.
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertTTTStateStr(), and open_spiel.python.algorithms.mcts_test.search_tic_tac_toe_state().
test_solve_loss()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_solve_loss (self)
Definition at line 128 of file mcts_test.py.
  def test_solve_loss(self):
    root, state = search_tic_tac_toe_state("x(1,1) o(0,0) x(2,2) o(0,1) x(0,2)")
    self.assertTTTStateStr(state, """
        oox
        .x.
        ..x
    """)
    self.assertEqual(root.outcome[root.player], -1)
    for c in root.children:
      self.assertEqual(c.outcome[c.player], -1)  # All losses.
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertTTTStateStr(), and open_spiel.python.algorithms.mcts_test.search_tic_tac_toe_state().
test_solve_win()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_solve_win (self)
Definition at line 139 of file mcts_test.py.
  def test_solve_win(self):
    root, state = search_tic_tac_toe_state("x(0,1) o(2,2)")
    self.assertTTTStateStr(state, """
        .x.
        ...
        ..o
    """)
    self.assertEqual(root.outcome[root.player], 1)
    best = root.best_child()
    self.assertEqual(best.outcome[best.player], 1)
    self.assertEqual(state.action_to_string(best.player, best.action), "x(0,2)")
References open_spiel.python.algorithms.mcts_test.MctsBotTest.assertTTTStateStr(), and open_spiel.python.algorithms.mcts_test.search_tic_tac_toe_state().
test_throws_on_simultaneous_game()
open_spiel.python.algorithms.mcts_test.MctsBotTest.test_throws_on_simultaneous_game (self)
Definition at line 93 of file mcts_test.py.
  def test_throws_on_simultaneous_game(self):
    game = pyspiel.load_game("matrix_mp")
    evaluator = mcts.RandomRolloutEvaluator(n_rollouts=20)
    with self.assertRaises(ValueError):
      mcts.MCTSBot(game, UCT_C, max_simulations=100, evaluator=evaluator)
The documentation for this class was generated from the following file:
open_spiel/python/algorithms/mcts_test.py