open spiel: absl::cord_internal::CordzUpdateTracker Class Reference
absl::cord_internal::CordzUpdateTracker Class Reference
#include <cordz_update_tracker.h>
Public Types
enum MethodIdentifier {
kUnknown , kAppendCord , kAppendCordBuffer , kAppendExternalMemory ,
kAppendString , kAssignCord , kAssignString , kClear ,
kConstructorCord , kConstructorString , kCordReader , kFlatten ,
kGetAppendBuffer , kGetAppendRegion , kMakeCordFromExternal , kMoveAppendCord ,
kMoveAssignCord , kMovePrependCord , kPrependCord , kPrependCordBuffer ,
kPrependString , kRemovePrefix , kRemoveSuffix , kSetExpectedChecksum ,
kSubCord , kNumMethods
}
Public Member Functions
constexpr CordzUpdateTracker () noexcept
CordzUpdateTracker (const CordzUpdateTracker &rhs) noexcept
CordzUpdateTracker & operator= (const CordzUpdateTracker &rhs) noexcept
int64_t Value (MethodIdentifier method) const
void LossyAdd (MethodIdentifier method, int64_t n=1)
void LossyAdd (const CordzUpdateTracker &src)
Detailed Description
Definition at line 37 of file cordz_update_tracker.h.
Member Enumeration Documentation
MethodIdentifier
enum absl::cord_internal::CordzUpdateTracker::MethodIdentifier
Enumerator
kUnknown
kAppendCord
kAppendCordBuffer
kAppendExternalMemory
kAppendString
kAssignCord
kAssignString
kClear
kConstructorCord
kConstructorString
kCordReader
kFlatten
kGetAppendBuffer
kGetAppendRegion
kMakeCordFromExternal
kMoveAppendCord
kMoveAssignCord
kMovePrependCord
kPrependCord
kPrependCordBuffer
kPrependString
kRemovePrefix
kRemoveSuffix
kSetExpectedChecksum
kSubCord
kNumMethods
Definition at line 40 of file cordz_update_tracker.h.
{
    kUnknown,
    kAppendCord,
    kAppendCordBuffer,
    kAppendExternalMemory,
    kAppendString,
    kAssignCord,
    kAssignString,
    kClear,
    kConstructorCord,
    kConstructorString,
    kCordReader,
    kFlatten,
    kGetAppendBuffer,
    kGetAppendRegion,
    kMakeCordFromExternal,
    kMoveAppendCord,
    kMoveAssignCord,
    kMovePrependCord,
    kPrependCord,
    kPrependCordBuffer,
    kPrependString,
    kRemovePrefix,
    kRemoveSuffix,
    kSetExpectedChecksum,
    kSubCord,
    // kNumMethods defines the number of entries: must be the last entry.
    kNumMethods,
  };
Constructor & Destructor Documentation
CordzUpdateTracker() [1/2]
absl::cord_internal::CordzUpdateTracker::CordzUpdateTracker () inline constexpr noexcept
Definition at line 72 of file cordz_update_tracker.h.
: values_{} {}
CordzUpdateTracker() [2/2]
absl::cord_internal::CordzUpdateTracker::CordzUpdateTracker (const CordzUpdateTracker & rhs) inline noexcept
Definition at line 75 of file cordz_update_tracker.h.
{ *this = rhs; }
Member Function Documentation
LossyAdd() [1/2]
void absl::cord_internal::CordzUpdateTracker::LossyAdd (const CordzUpdateTracker & src) inline
Definition at line 99 of file cordz_update_tracker.h.
{
    for (int i = 0; i < kNumMethods; ++i) {
      MethodIdentifier method = static_cast<MethodIdentifier>(i);
      if (int64_t value = src.Value(method)) {
        LossyAdd(method, value);
      }
    }
  }
References absl::i, kNumMethods, LossyAdd(), and Value().
LossyAdd() [2/2]
void absl::cord_internal::CordzUpdateTracker::LossyAdd (MethodIdentifier method, int64_t n = 1) inline
Definition at line 92 of file cordz_update_tracker.h.
{
    auto& value = values_[method];
    value.store(value.load(std::memory_order_relaxed) + n,
                std::memory_order_relaxed);
  }
References absl::n.
Referenced by LossyAdd().
operator=()
CordzUpdateTracker & absl::cord_internal::CordzUpdateTracker::operator= (const CordzUpdateTracker & rhs) inline noexcept
Definition at line 78 of file cordz_update_tracker.h.
{
    for (int i = 0; i < kNumMethods; ++i) {
      values_[i].store(rhs.values_[i].load(std::memory_order_relaxed),
                       std::memory_order_relaxed);
    }
    return *this;
  }
References absl::i, and kNumMethods.
Value()
int64_t absl::cord_internal::CordzUpdateTracker::Value (MethodIdentifier method) const inline
Definition at line 87 of file cordz_update_tracker.h.
{
    return values_[method].load(std::memory_order_relaxed);
  }
Referenced by LossyAdd(), absl::MATCHER_P(), and absl::MATCHER_P2().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/cordz_update_tracker.h