open spiel: absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc > Class Template Reference
absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc > Class Template Reference
#include <raw_hash_set.h>
Classes
class const_iterator
class constructor
class iterator
Public Types
using init_type = typename PolicyTraits::init_type
using key_type = typename PolicyTraits::key_type
using slot_type = typename PolicyTraits::slot_type
using allocator_type = Alloc
using size_type = size_t
using difference_type = ptrdiff_t
using hasher = Hash
using key_equal = Eq
using policy_type = Policy
using value_type = typename PolicyTraits::value_type
using reference = value_type&
using const_reference = const value_type&
using pointer
using const_pointer
template<class K >
using key_arg = typename KeyArgImpl::template type<K, key_type>
using node_type = node_handle<Policy, hash_policy_traits<Policy>, Alloc>
using insert_return_type = InsertReturnType<iterator, node_type>
Public Member Functions
raw_hash_set () noexcept(std::is_nothrow_default_constructible< hasher >::value &&std::is_nothrow_default_constructible< key_equal >::value &&std::is_nothrow_default_constructible< allocator_type >::value)
ABSL_ATTRIBUTE_NOINLINE raw_hash_set (size_t bucket_count, const hasher &hash=hasher(), const key_equal &eq=key_equal(), const allocator_type &alloc=allocator_type())
raw_hash_set (size_t bucket_count, const hasher &hash, const allocator_type &alloc)
raw_hash_set (size_t bucket_count, const allocator_type &alloc)
raw_hash_set (const allocator_type &alloc)
template<class InputIter >
raw_hash_set (InputIter first, InputIter last, size_t bucket_count=0, const hasher &hash=hasher(), const key_equal &eq=key_equal(), const allocator_type &alloc=allocator_type())
template<class InputIter >
raw_hash_set (InputIter first, InputIter last, size_t bucket_count, const hasher &hash, const allocator_type &alloc)
template<class InputIter >
raw_hash_set (InputIter first, InputIter last, size_t bucket_count, const allocator_type &alloc)
template<class InputIter >
raw_hash_set (InputIter first, InputIter last, const allocator_type &alloc)
template<class T , RequiresNotInit< T > = 0, RequiresInsertable< T > = 0>
raw_hash_set (std::initializer_list< T > init, size_t bucket_count=0, const hasher &hash=hasher(), const key_equal &eq=key_equal(), const allocator_type &alloc=allocator_type())
raw_hash_set (std::initializer_list< init_type > init, size_t bucket_count=0, const hasher &hash=hasher(), const key_equal &eq=key_equal(), const allocator_type &alloc=allocator_type())
template<class T , RequiresNotInit< T > = 0, RequiresInsertable< T > = 0>
raw_hash_set (std::initializer_list< T > init, size_t bucket_count, const hasher &hash, const allocator_type &alloc)
raw_hash_set (std::initializer_list< init_type > init, size_t bucket_count, const hasher &hash, const allocator_type &alloc)
template<class T , RequiresNotInit< T > = 0, RequiresInsertable< T > = 0>
raw_hash_set (std::initializer_list< T > init, size_t bucket_count, const allocator_type &alloc)
raw_hash_set (std::initializer_list< init_type > init, size_t bucket_count, const allocator_type &alloc)
template<class T , RequiresNotInit< T > = 0, RequiresInsertable< T > = 0>
raw_hash_set (std::initializer_list< T > init, const allocator_type &alloc)
raw_hash_set (std::initializer_list< init_type > init, const allocator_type &alloc)
raw_hash_set (const raw_hash_set &that)
raw_hash_set (const raw_hash_set &that, const allocator_type &a)
ABSL_ATTRIBUTE_NOINLINE raw_hash_set (raw_hash_set &&that) noexcept(std::is_nothrow_copy_constructible< hasher >::value &&std::is_nothrow_copy_constructible< key_equal >::value &&std::is_nothrow_copy_constructible< allocator_type >::value)
raw_hash_set (raw_hash_set &&that, const allocator_type &a)
raw_hash_set & operator= (const raw_hash_set &that)
raw_hash_set & operator= (raw_hash_set &&that) noexcept(absl::allocator_traits< allocator_type >::is_always_equal::value &&std::is_nothrow_move_assignable< hasher >::value &&std::is_nothrow_move_assignable< key_equal >::value)
~raw_hash_set ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
bool empty () const
size_t size () const
size_t capacity () const
size_t max_size () const
ABSL_ATTRIBUTE_REINITIALIZES void clear ()
void destroy_slots ()
template<class T , RequiresInsertable< T > = 0, class T2 = T, typename std::enable_if< IsDecomposable< T2 >::value, int >::type = 0, T * = nullptr>
std::pair< iterator, bool > insert (T &&value)
template<class T , RequiresInsertable< T > = 0, typename std::enable_if< IsDecomposable< const T & >::value, int >::type = 0>
std::pair< iterator, bool > insert (const T &value)
std::pair< iterator, bool > insert (init_type &&value)
template<class T , RequiresInsertable< T > = 0, class T2 = T, typename std::enable_if< IsDecomposable< T2 >::value, int >::type = 0, T * = nullptr>
iterator insert (const_iterator, T &&value)
template<class T , RequiresInsertable< T > = 0, typename std::enable_if< IsDecomposable< const T & >::value, int >::type = 0>
iterator insert (const_iterator, const T &value)
iterator insert (const_iterator, init_type &&value)
template<class InputIt >
void insert (InputIt first, InputIt last)
template<class T , RequiresNotInit< T > = 0, RequiresInsertable< const T & > = 0>
void insert (std::initializer_list< T > ilist)
void insert (std::initializer_list< init_type > ilist)
insert_return_type insert (node_type &&node)
iterator insert (const_iterator, node_type &&node)
template<class... Args, typename std::enable_if< IsDecomposable< Args... >::value, int >::type = 0>
std::pair< iterator, bool > emplace (Args &&... args)
template<class... Args, typename std::enable_if< !IsDecomposable< Args... >::value, int >::type = 0>
std::pair< iterator, bool > emplace (Args &&... args)
template<class... Args>
iterator emplace_hint (const_iterator, Args &&... args)
template<class K = key_type, class F >
iterator lazy_emplace (const key_arg< K > &key, F &&f)
template<class K = key_type>
size_type erase (const key_arg< K > &key)
void erase (const_iterator cit)
void erase (iterator it)
iterator erase (const_iterator first, const_iterator last)
template<typename H , typename E >
void merge (raw_hash_set< Policy, H, E, Alloc > &src)
template<typename H , typename E >
void merge (raw_hash_set< Policy, H, E, Alloc > &&src)
node_type extract (const_iterator position)
template<class K = key_type, typename std::enable_if<!std::is_same< K, iterator >::value, int >::type = 0>
node_type extract (const key_arg< K > &key)
void swap (raw_hash_set &that) noexcept(IsNoThrowSwappable< hasher >() &&IsNoThrowSwappable< key_equal >() &&IsNoThrowSwappable< allocator_type >(typename AllocTraits::propagate_on_container_swap{}))
void rehash (size_t n)
void reserve (size_t n)
template<class K = key_type>
size_t count (const key_arg< K > &key) const
template<class K = key_type>
void prefetch (const key_arg< K > &key) const
template<class K = key_type>
iterator find (const key_arg< K > &key, size_t hash)
template<class K = key_type>
iterator find (const key_arg< K > &key)
template<class K = key_type>
const_iterator find (const key_arg< K > &key, size_t hash) const
template<class K = key_type>
const_iterator find (const key_arg< K > &key) const
template<class K = key_type>
bool contains (const key_arg< K > &key) const
template<class K = key_type>
std::pair< iterator, iterator > equal_range (const key_arg< K > &key)
template<class K = key_type>
std::pair< const_iterator, const_iterator > equal_range (const key_arg< K > &key) const
size_t bucket_count () const
float load_factor () const
float max_load_factor () const
void max_load_factor (float)
hasher hash_function () const
key_equal key_eq () const
allocator_type get_allocator () const
Protected Member Functions
template<class K >
std::pair< size_t, bool > find_or_prepare_insert (const K &key)
size_t prepare_insert (size_t hash) ABSL_ATTRIBUTE_NOINLINE
template<class... Args>
void emplace_at (size_t i, Args &&... args)
iterator iterator_at (size_t i)
const_iterator iterator_at (size_t i) const
Friends
template<class Container , typename Enabler >
struct absl::container_internal::hashtable_debug_internal::HashtableDebugAccess
struct RawHashSetTestOnlyAccess
bool operator== (const raw_hash_set &a, const raw_hash_set &b)
bool operator!= (const raw_hash_set &a, const raw_hash_set &b)
template<typename H >
std::enable_if< H::templateis_hashable< value_type >::value, H >::type AbslHashValue (H h, const raw_hash_set &s)
void swap (raw_hash_set &a, raw_hash_set &b) noexcept(noexcept(a.swap(b)))
Detailed Description
template<class Policy, class Hash, class Eq, class Alloc>
class absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >
Definition at line 1327 of file raw_hash_set.h.
Member Typedef Documentation
allocator_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::allocator_type = Alloc
Definition at line 1338 of file raw_hash_set.h.
const_pointer
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::const_pointer
Initial value:
 typename absl::allocator_traits<
      allocator_type>::template rebind_traits<value_type>::const_pointer
Definition at line 1349 of file raw_hash_set.h.
const_reference
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::const_reference = const value_type&
Definition at line 1346 of file raw_hash_set.h.
difference_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::difference_type = ptrdiff_t
Definition at line 1340 of file raw_hash_set.h.
hasher
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::hasher = Hash
Definition at line 1341 of file raw_hash_set.h.
init_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::init_type = typename PolicyTraits::init_type
Definition at line 1333 of file raw_hash_set.h.
insert_return_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert_return_type = InsertReturnType<iterator, node_type>
Definition at line 1535 of file raw_hash_set.h.
key_arg
template<class Policy , class Hash , class Eq , class Alloc > template<class K > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::key_arg = typename KeyArgImpl::template type<K, key_type>
Definition at line 1357 of file raw_hash_set.h.
key_equal
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::key_equal = Eq
Definition at line 1342 of file raw_hash_set.h.
key_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::key_type = typename PolicyTraits::key_type
Definition at line 1334 of file raw_hash_set.h.
node_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::node_type = node_handle<Policy, hash_policy_traits<Policy>, Alloc>
Definition at line 1534 of file raw_hash_set.h.
pointer
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::pointer
Initial value:
 typename absl::allocator_traits<
      allocator_type>::template rebind_traits<value_type>::pointer
Definition at line 1347 of file raw_hash_set.h.
policy_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::policy_type = Policy
Definition at line 1343 of file raw_hash_set.h.
reference
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::reference = value_type&
Definition at line 1345 of file raw_hash_set.h.
size_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::size_type = size_t
Definition at line 1339 of file raw_hash_set.h.
slot_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::slot_type = typename PolicyTraits::slot_type
Definition at line 1337 of file raw_hash_set.h.
value_type
template<class Policy , class Hash , class Eq , class Alloc > using absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::value_type = typename PolicyTraits::value_type
Definition at line 1344 of file raw_hash_set.h.
Constructor & Destructor Documentation
raw_hash_set() [1/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set () inline noexcept
Definition at line 1539 of file raw_hash_set.h.
                                                                        {}
raw_hash_set() [2/21]
template<class Policy , class Hash , class Eq , class Alloc > ABSL_ATTRIBUTE_NOINLINE absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (size_t bucket_count, const hasher & hash = hasher(), const key_equal & eq = key_equal(), const allocator_type & alloc = allocator_type()) inline explicit
Definition at line 1544 of file raw_hash_set.h.
      : settings_(CommonFields{}, hash, eq, alloc) {
    if (bucket_count) {
      common().capacity_ = NormalizeCapacity(bucket_count);
      initialize_slots();
    }
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::bucket_count(), absl::container_internal::CommonFields::capacity_, and absl::container_internal::NormalizeCapacity().
raw_hash_set() [3/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (size_t bucket_count, const hasher & hash, const allocator_type & alloc) inline
Definition at line 1555 of file raw_hash_set.h.
      : raw_hash_set(bucket_count, hash, key_equal(), alloc) {}
raw_hash_set() [4/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (size_t bucket_count, const allocator_type & alloc) inline
Definition at line 1559 of file raw_hash_set.h.
      : raw_hash_set(bucket_count, hasher(), key_equal(), alloc) {}
raw_hash_set() [5/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (const allocator_type & alloc) inline explicit
Definition at line 1562 of file raw_hash_set.h.
      : raw_hash_set(0, hasher(), key_equal(), alloc) {}
raw_hash_set() [6/21]
template<class Policy , class Hash , class Eq , class Alloc > template<class InputIter > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (InputIter first, InputIter last, size_t bucket_count = 0, const hasher & hash = hasher(), const key_equal & eq = key_equal(), const allocator_type & alloc = allocator_type()) inline
Definition at line 1566 of file raw_hash_set.h.
      : raw_hash_set(SelectBucketCountForIterRange(first, last, bucket_count),
                     hash, eq, alloc) {
    insert(first, last);
  }
References first, and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
raw_hash_set() [7/21]
template<class Policy , class Hash , class Eq , class Alloc > template<class InputIter > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (InputIter first, InputIter last, size_t bucket_count, const hasher & hash, const allocator_type & alloc) inline
Definition at line 1575 of file raw_hash_set.h.
      : raw_hash_set(first, last, bucket_count, hash, key_equal(), alloc) {}
raw_hash_set() [8/21]
template<class Policy , class Hash , class Eq , class Alloc > template<class InputIter > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (InputIter first, InputIter last, size_t bucket_count, const allocator_type & alloc) inline
Definition at line 1580 of file raw_hash_set.h.
      : raw_hash_set(first, last, bucket_count, hasher(), key_equal(), alloc) {}
raw_hash_set() [9/21]
template<class Policy , class Hash , class Eq , class Alloc > template<class InputIter > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (InputIter first, InputIter last, const allocator_type & alloc) inline
Definition at line 1585 of file raw_hash_set.h.
      : raw_hash_set(first, last, 0, hasher(), key_equal(), alloc) {}
raw_hash_set() [10/21]
template<class Policy , class Hash , class Eq , class Alloc > template<class T , RequiresNotInit< T > = 0, RequiresInsertable< T > = 0> absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (std::initializer_list< T > init, size_t bucket_count = 0, const hasher & hash = hasher(), const key_equal & eq = key_equal(), const allocator_type & alloc = allocator_type()) inline
Definition at line 1610 of file raw_hash_set.h.
      : raw_hash_set(init.begin(), init.end(), bucket_count, hash, eq, alloc) {}
raw_hash_set() [11/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (std::initializer_list< init_type > init, size_t bucket_count = 0, const hasher & hash = hasher(), const key_equal & eq = key_equal(), const allocator_type & alloc = allocator_type()) inline
Definition at line 1615 of file raw_hash_set.h.
      : raw_hash_set(init.begin(), init.end(), bucket_count, hash, eq, alloc) {}
raw_hash_set() [12/21]
template<class Policy , class Hash , class Eq , class Alloc > template<class T , RequiresNotInit< T > = 0, RequiresInsertable< T > = 0> absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (std::initializer_list< T > init, size_t bucket_count, const hasher & hash, const allocator_type & alloc) inline
Definition at line 1621 of file raw_hash_set.h.
      : raw_hash_set(init, bucket_count, hash, key_equal(), alloc) {}
raw_hash_set() [13/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (std::initializer_list< init_type > init, size_t bucket_count, const hasher & hash, const allocator_type & alloc) inline
Definition at line 1625 of file raw_hash_set.h.
      : raw_hash_set(init, bucket_count, hash, key_equal(), alloc) {}
raw_hash_set() [14/21]
template<class Policy , class Hash , class Eq , class Alloc > template<class T , RequiresNotInit< T > = 0, RequiresInsertable< T > = 0> absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (std::initializer_list< T > init, size_t bucket_count, const allocator_type & alloc) inline
Definition at line 1630 of file raw_hash_set.h.
      : raw_hash_set(init, bucket_count, hasher(), key_equal(), alloc) {}
raw_hash_set() [15/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (std::initializer_list< init_type > init, size_t bucket_count, const allocator_type & alloc) inline
Definition at line 1634 of file raw_hash_set.h.
      : raw_hash_set(init, bucket_count, hasher(), key_equal(), alloc) {}
raw_hash_set() [16/21]
template<class Policy , class Hash , class Eq , class Alloc > template<class T , RequiresNotInit< T > = 0, RequiresInsertable< T > = 0> absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (std::initializer_list< T > init, const allocator_type & alloc) inline
Definition at line 1639 of file raw_hash_set.h.
      : raw_hash_set(init, 0, hasher(), key_equal(), alloc) {}
raw_hash_set() [17/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (std::initializer_list< init_type > init, const allocator_type & alloc) inline
Definition at line 1642 of file raw_hash_set.h.
      : raw_hash_set(init, 0, hasher(), key_equal(), alloc) {}
raw_hash_set() [18/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (const raw_hash_set< Policy, Hash, Eq, Alloc > & that) inline
Definition at line 1646 of file raw_hash_set.h.
      : raw_hash_set(that, AllocTraits::select_on_container_copy_construction(
                               that.alloc_ref())) {}
raw_hash_set() [19/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (const raw_hash_set< Policy, Hash, Eq, Alloc > & that, const allocator_type & a) inline
Definition at line 1650 of file raw_hash_set.h.
      : raw_hash_set(0, that.hash_ref(), that.eq_ref(), a) {
    reserve(that.size());
    // Because the table is guaranteed to be empty, we can do something faster
    // than a full `insert`.
    for (const auto& v : that) {
      const size_t hash = PolicyTraits::apply(HashElement{hash_ref()}, v);
      auto target = find_first_non_full_outofline(common(), hash);
      SetCtrl(common(), target.offset, H2(hash), sizeof(slot_type));
      emplace_at(target.offset, v);
      common().maybe_increment_generation_on_insert();
      infoz().RecordInsert(hash, target.probe_length);
    }
    common().size_ = that.size();
    growth_left() -= that.size();
  }
References absl::container_internal::hash_policy_traits< Policy, class >::apply(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace_at(), absl::container_internal::find_first_non_full_outofline(), absl::container_internal::H2(), hash, absl::container_internal::CommonFieldsGenerationInfoDisabled::maybe_increment_generation_on_insert(), absl::container_internal::HashtablezInfoHandle::RecordInsert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::reserve(), absl::container_internal::SetCtrl(), absl::container_internal::CommonFields::size_, and absl::v.
raw_hash_set() [20/21]
template<class Policy , class Hash , class Eq , class Alloc > ABSL_ATTRIBUTE_NOINLINE absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (raw_hash_set< Policy, Hash, Eq, Alloc > && that) inline noexcept
Definition at line 1667 of file raw_hash_set.h.
      :  // Hash, equality and allocator are copied instead of moved because
         // `that` must be left valid. If Hash is std::function<Key>, moving it
         // would create a nullptr functor that cannot be called.
        settings_(absl::exchange(that.common(), CommonFields{}),
                  that.hash_ref(), that.eq_ref(), that.alloc_ref()) {}
raw_hash_set() [21/21]
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set (raw_hash_set< Policy, Hash, Eq, Alloc > && that, const allocator_type & a) inline
Definition at line 1677 of file raw_hash_set.h.
      : settings_(CommonFields{}, that.hash_ref(), that.eq_ref(), a) {
    if (a == that.alloc_ref()) {
      std::swap(common(), that.common());
    } else {
      reserve(that.size());
      // Note: this will copy elements of dense_set and unordered_set instead of
      // moving them. This can be fixed if it ever becomes an issue.
      for (auto& elem : that) insert(std::move(elem));
    }
  }
References absl::a, absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::reserve().
~raw_hash_set()
template<class Policy , class Hash , class Eq , class Alloc > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::~raw_hash_set () inline
Definition at line 1710 of file raw_hash_set.h.
                  {
    const size_t cap = capacity();
    if (!cap) return;
    destroy_slots();
    // Unpoison before returning the memory to the allocator.
    SanitizerUnpoisonMemoryRegion(slot_array(), sizeof(slot_type) * cap);
    Deallocate<alignof(slot_type)>(
        &alloc_ref(), control(),
        AllocSize(cap, sizeof(slot_type), alignof(slot_type)));
    infoz().Unregister();
  }
References absl::container_internal::AllocSize(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity(), absl::container_internal::Deallocate(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::destroy_slots(), absl::container_internal::SanitizerUnpoisonMemoryRegion(), and absl::container_internal::HashtablezInfoHandle::Unregister().
Member Function Documentation
begin() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::begin () inline
Definition at line 1724 of file raw_hash_set.h.
                   {
    auto it = iterator_at(0);
    it.skip_empty_or_deleted();
    return it;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator_at().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::begin(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::cbegin().
begin() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > const_iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::begin () const inline
Definition at line 1731 of file raw_hash_set.h.
{
    return const_cast<raw_hash_set*>(this)->begin();
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::begin().
bucket_count()
template<class Policy , class Hash , class Eq , class Alloc > size_t absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::bucket_count () const inline
Definition at line 2188 of file raw_hash_set.h.
{ return capacity(); }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set().
capacity()
template<class Policy , class Hash , class Eq , class Alloc > size_t absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity () const inline
Definition at line 1740 of file raw_hash_set.h.
{ return common().capacity_; }
References absl::container_internal::CommonFields::capacity_.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::bucket_count(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::clear(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::destroy_slots(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find_or_prepare_insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::load_factor(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::rehash(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::~raw_hash_set().
cbegin()
template<class Policy , class Hash , class Eq , class Alloc > const_iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::cbegin () const inline
Definition at line 1735 of file raw_hash_set.h.
{ return begin(); }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::begin().
cend()
template<class Policy , class Hash , class Eq , class Alloc > const_iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::cend () const inline
Definition at line 1736 of file raw_hash_set.h.
{ return end(); }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end().
clear()
template<class Policy , class Hash , class Eq , class Alloc > ABSL_ATTRIBUTE_REINITIALIZES void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::clear () inline
Definition at line 1743 of file raw_hash_set.h.
{
    // Iterating over this container is O(bucket_count()). When bucket_count()
    // is much greater than size(), iteration becomes prohibitively expensive.
    // For clear() it is more important to reuse the allocated array when the
    // container is small because allocation takes comparatively long time
    // compared to destruction of the elements of the container. So we pick the
    // largest bucket_count() threshold for which iteration is still fast and
    // past that we simply deallocate the array.
    const size_t cap = capacity();
    if (cap == 0) {
      // Already guaranteed to be empty; so nothing to do.
    } else {
      destroy_slots();
      ClearBackingArray(common(), GetPolicyFunctions(),
                        /*reuse=*/cap < 128);
    }
    common().set_reserved_growth(0);
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity(), absl::container_internal::ClearBackingArray(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::destroy_slots(), and absl::container_internal::CommonFieldsGenerationInfoDisabled::set_reserved_growth().
contains()
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> bool absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::contains (const key_arg< K > & key) const inline
Definition at line 2170 of file raw_hash_set.h.
{
    return find(key) != end();
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and key.
Referenced by open_spiel::universal_poker::UniformRestrictedActions::GetStatePolicy(), and open_spiel::dynamic_routing::Network::IsLocationASinkNode().
count()
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> size_t absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::count (const key_arg< K > & key) const inline
Definition at line 2107 of file raw_hash_set.h.
{
    return find(key) == end() ? 0 : 1;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and key.
Referenced by open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_add_to_queue_count_weighted(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_lcb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_ucb(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::_ucb_standard_factor(), open_spiel::algorithms::HistoryNode::AddChild(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::compute_total_steps(), open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::delta(), and open_spiel.python.algorithms.response_graph_ucb.ResponseGraphUCB::update_mean_and_count().
destroy_slots()
template<class Policy , class Hash , class Eq , class Alloc > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::destroy_slots () inline
Definition at line 1762 of file raw_hash_set.h.
{
    const size_t cap = capacity();
    const ctrl_t* ctrl = control();
    slot_type* slot = slot_array();
    for (size_t i = 0; i != cap; ++i) {
      if (IsFull(ctrl[i])) {
        PolicyTraits::destroy(&alloc_ref(), slot + i);
      }
    }
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity(), absl::container_internal::common_policy_traits< Policy, class >::destroy(), absl::i, and absl::container_internal::IsFull().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::clear(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::~raw_hash_set().
emplace() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > template<class... Args, typename std::enable_if< IsDecomposable< Args... >::value, int >::type = 0> std::pair< iterator, bool > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace (Args &&... args) inline
Definition at line 1885 of file raw_hash_set.h.
{
    return PolicyTraits::apply(EmplaceDecomposable{*this},
                               std::forward<Args>(args)...);
  }
References absl::container_internal::hash_policy_traits< Policy, class >::apply().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace_hint(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
emplace() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > template<class... Args, typename std::enable_if< !IsDecomposable< Args... >::value, int >::type = 0> std::pair< iterator, bool > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace (Args &&... args) inline
Definition at line 1895 of file raw_hash_set.h.
{
    alignas(slot_type) unsigned char raw[sizeof(slot_type)];
    slot_type* slot = reinterpret_cast<slot_type*>(&raw);
    PolicyTraits::construct(&alloc_ref(), slot, std::forward<Args>(args)...);
    const auto& elem = PolicyTraits::element(slot);
    return PolicyTraits::apply(InsertSlot<true>{*this, std::move(*slot)}, elem);
  }
References absl::container_internal::hash_policy_traits< Policy, class >::apply(), absl::container_internal::common_policy_traits< Policy, class >::construct(), and absl::container_internal::common_policy_traits< Policy, class >::element().
emplace_at()
template<class Policy , class Hash , class Eq , class Alloc > template<class... Args> void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace_at (size_t i, Args &&... args) inline protected
Definition at line 2501 of file raw_hash_set.h.
{
    PolicyTraits::construct(&alloc_ref(), slot_array() + i,
                            std::forward<Args>(args)...);
    assert(PolicyTraits::apply(FindElement{*this}, *iterator_at(i)) ==
               iterator_at(i) &&
           "constructed value does not match the lookup key");
  }
References absl::container_internal::hash_policy_traits< Policy, class >::apply(), absl::container_internal::common_policy_traits< Policy, class >::construct(), absl::i, and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator_at().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set().
emplace_hint()
template<class Policy , class Hash , class Eq , class Alloc > template<class... Args> iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace_hint (const_iterator , Args &&... args) inline
Definition at line 1905 of file raw_hash_set.h.
{
    return emplace(std::forward<Args>(args)...).first;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace().
empty()
template<class Policy , class Hash , class Eq , class Alloc > bool absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::empty () const inline
Definition at line 1738 of file raw_hash_set.h.
{ return !size(); }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::size().
end() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end () inline
Definition at line 1729 of file raw_hash_set.h.
{ return iterator(common().generation_ptr()); }
Referenced by absl::container_internal::raw_hash_map< Policy, Hash, Eq, Alloc >::at(), absl::container_internal::raw_hash_map< Policy, Hash, Eq, Alloc >::at(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::cend(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::contains(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::count(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::equal_range(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::equal_range(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::extract(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
end() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > const_iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end () const inline
Definition at line 1734 of file raw_hash_set.h.
{ return iterator(common().generation_ptr()); }
equal_range() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> std::pair< iterator, iterator > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::equal_range (const key_arg< K > & key) inline
Definition at line 2175 of file raw_hash_set.h.
{
    auto it = find(key);
    if (it != end()) return {it, std::next(it)};
    return {it, it};
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and key.
equal_range() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> std::pair< const_iterator, const_iterator > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::equal_range (const key_arg< K > & key) const inline
Definition at line 2181 of file raw_hash_set.h.
{
    auto it = find(key);
    if (it != end()) return {it, std::next(it)};
    return {it, it};
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and key.
erase() [1/4]
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> size_type absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase (const key_arg< K > & key) inline
Definition at line 1975 of file raw_hash_set.h.
{
    auto it = find(key);
    if (it == end()) return 0;
    erase(it);
    return 1;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and key.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase().
erase() [2/4]
template<class Policy , class Hash , class Eq , class Alloc > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase (const_iterator cit) inline
Definition at line 1995 of file raw_hash_set.h.
{ erase(cit.inner_); }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase().
erase() [3/4]
template<class Policy , class Hash , class Eq , class Alloc > iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase (const_iterator first, const_iterator last) inline
Definition at line 2006 of file raw_hash_set.h.
{
    while (first != last) {
      erase(first++);
    }
    return last.inner_;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase(), and first.
erase() [4/4]
template<class Policy , class Hash , class Eq , class Alloc > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase (iterator it) inline
Definition at line 1999 of file raw_hash_set.h.
{
    ABSL_INTERNAL_ASSERT_IS_FULL(it.ctrl_, it.generation(), it.generation_ptr(),
                                 "erase()");
    PolicyTraits::destroy(&alloc_ref(), it.slot_);
    erase_meta_only(it);
  }
References ABSL_INTERNAL_ASSERT_IS_FULL, absl::container_internal::common_policy_traits< Policy, class >::destroy(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::slot_.
extract() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type, typename std::enable_if<!std::is_same< K, iterator >::value, int >::type = 0> node_type absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::extract (const key_arg< K > & key) inline
Definition at line 2047 of file raw_hash_set.h.
{
    auto it = find(key);
    return it == end() ? node_type() : extract(const_iterator{it});
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::extract(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and key.
extract() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > node_type absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::extract (const_iterator position) inline
Definition at line 2034 of file raw_hash_set.h.
{
    ABSL_INTERNAL_ASSERT_IS_FULL(position.inner_.ctrl_,
                                 position.inner_.generation(),
                                 position.inner_.generation_ptr(), "extract()");
    auto node =
        CommonAccess::Transfer<node_type>(alloc_ref(), position.inner_.slot_);
    erase_meta_only(position);
    return node;
  }
References ABSL_INTERNAL_ASSERT_IS_FULL, absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::slot_, and absl::container_internal::CommonAccess::Transfer().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::extract().
find() [1/4]
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find (const key_arg< K > & key) inline
Definition at line 2154 of file raw_hash_set.h.
{
    prefetch_heap_block();
    return find(key, hash_ref()(key));
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and key.
find() [2/4]
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> const_iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find (const key_arg< K > & key) const inline
Definition at line 2164 of file raw_hash_set.h.
{
    prefetch_heap_block();
    return find(key, hash_ref()(key));
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and key.
find() [3/4]
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find (const key_arg< K > & key, size_t hash) inline
Definition at line 2136 of file raw_hash_set.h.
{
    auto seq = probe(common(), hash);
    slot_type* slot_ptr = slot_array();
    const ctrl_t* ctrl = control();
    while (true) {
      Group g{ctrl + seq.offset()};
      for (uint32_t i : g.Match(H2(hash))) {
        if (ABSL_PREDICT_TRUE(PolicyTraits::apply(
                EqualElement<K>{key, eq_ref()},
                PolicyTraits::element(slot_ptr + seq.offset(i)))))
          return iterator_at(seq.offset(i));
      }
      if (ABSL_PREDICT_TRUE(g.MaskEmpty())) return end();
      seq.next();
      assert(seq.index() <= capacity() && "full table!");
    }
  }
References ABSL_PREDICT_TRUE, absl::container_internal::hash_policy_traits< Policy, class >::apply(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity(), absl::container_internal::common_policy_traits< Policy, class >::element(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end(), absl::g, absl::container_internal::H2(), hash, absl::i, absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator_at(), key, and absl::container_internal::probe().
Referenced by absl::container_internal::raw_hash_map< Policy, Hash, Eq, Alloc >::at(), absl::container_internal::raw_hash_map< Policy, Hash, Eq, Alloc >::at(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::contains(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::count(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::equal_range(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::equal_range(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::extract(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find().
find() [4/4]
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> const_iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find (const key_arg< K > & key, size_t hash) const inline
Definition at line 2160 of file raw_hash_set.h.
{
    return const_cast<raw_hash_set*>(this)->find(key, hash);
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), hash, and key.
find_or_prepare_insert()
template<class Policy , class Hash , class Eq , class Alloc > template<class K > std::pair< size_t, bool > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find_or_prepare_insert (const K & key) inline protected
Definition at line 2445 of file raw_hash_set.h.
{
    prefetch_heap_block();
    auto hash = hash_ref()(key);
    auto seq = probe(common(), hash);
    const ctrl_t* ctrl = control();
    while (true) {
      Group g{ctrl + seq.offset()};
      for (uint32_t i : g.Match(H2(hash))) {
        if (ABSL_PREDICT_TRUE(PolicyTraits::apply(
                EqualElement<K>{key, eq_ref()},
                PolicyTraits::element(slot_array() + seq.offset(i)))))
          return {seq.offset(i), false};
      }
      if (ABSL_PREDICT_TRUE(g.MaskEmpty())) break;
      seq.next();
      assert(seq.index() <= capacity() && "full table!");
    }
    return {prepare_insert(hash), true};
  }
References ABSL_PREDICT_TRUE, absl::container_internal::hash_policy_traits< Policy, class >::apply(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity(), absl::container_internal::common_policy_traits< Policy, class >::element(), absl::g, absl::container_internal::H2(), hash, absl::i, key, absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert(), and absl::container_internal::probe().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::lazy_emplace().
get_allocator()
template<class Policy , class Hash , class Eq , class Alloc > allocator_type absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::get_allocator () const inline
Definition at line 2199 of file raw_hash_set.h.
{ return alloc_ref(); }
hash_function()
template<class Policy , class Hash , class Eq , class Alloc > hasher absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::hash_function () const inline
Definition at line 2197 of file raw_hash_set.h.
{ return hash_ref(); }
insert() [1/11]
template<class Policy , class Hash , class Eq , class Alloc > template<class T , RequiresInsertable< T > = 0, typename std::enable_if< IsDecomposable< const T & >::value, int >::type = 0> std::pair< iterator, bool > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (const T & value) inline
Definition at line 1804 of file raw_hash_set.h.
{
    return emplace(value);
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [2/11]
template<class Policy , class Hash , class Eq , class Alloc > template<class T , RequiresInsertable< T > = 0, typename std::enable_if< IsDecomposable< const T & >::value, int >::type = 0> iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (const_iterator , const T & value) inline
Definition at line 1832 of file raw_hash_set.h.
{
    return insert(value).first;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [3/11]
template<class Policy , class Hash , class Eq , class Alloc > iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (const_iterator , init_type && value) inline
Definition at line 1836 of file raw_hash_set.h.
{
    return insert(std::move(value)).first;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [4/11]
template<class Policy , class Hash , class Eq , class Alloc > iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (const_iterator , node_type && node) inline
Definition at line 1868 of file raw_hash_set.h.
{
    auto res = insert(std::move(node));
    node = std::move(res.node);
    return res.position;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [5/11]
template<class Policy , class Hash , class Eq , class Alloc > template<class T , RequiresInsertable< T > = 0, class T2 = T, typename std::enable_if< IsDecomposable< T2 >::value, int >::type = 0, T * = nullptr> iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (const_iterator , T && value) inline
Definition at line 1822 of file raw_hash_set.h.
{
    return insert(std::forward<T>(value)).first;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [6/11]
template<class Policy , class Hash , class Eq , class Alloc > std::pair< iterator, bool > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (init_type && value) inline
Definition at line 1813 of file raw_hash_set.h.
{
    return emplace(std::move(value));
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [7/11]
template<class Policy , class Hash , class Eq , class Alloc > template<class InputIt > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (InputIt first, InputIt last) inline
Definition at line 1841 of file raw_hash_set.h.
{
    for (; first != last; ++first) emplace(*first);
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace(), and first.
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [8/11]
template<class Policy , class Hash , class Eq , class Alloc > insert_return_type absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (node_type && node) inline
Definition at line 1854 of file raw_hash_set.h.
{
    if (!node) return {end(), false, node_type()};
    const auto& elem = PolicyTraits::element(CommonAccess::GetSlot(node));
    auto res = PolicyTraits::apply(
        InsertSlot<false>{*this, std::move(*CommonAccess::GetSlot(node))},
        elem);
    if (res.second) {
      CommonAccess::Reset(&node);
      return {res.first, true, node_type()};
    } else {
      return {res.first, false, std::move(node)};
    }
  }
References absl::container_internal::hash_policy_traits< Policy, class >::apply(), absl::container_internal::common_policy_traits< Policy, class >::element(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::end(), absl::container_internal::CommonAccess::GetSlot(), and absl::container_internal::CommonAccess::Reset().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [9/11]
template<class Policy , class Hash , class Eq , class Alloc > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (std::initializer_list< init_type > ilist) inline
Definition at line 1850 of file raw_hash_set.h.
{
    insert(ilist.begin(), ilist.end());
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [10/11]
template<class Policy , class Hash , class Eq , class Alloc > template<class T , RequiresNotInit< T > = 0, RequiresInsertable< const T & > = 0> void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (std::initializer_list< T > ilist) inline
Definition at line 1846 of file raw_hash_set.h.
{
    insert(ilist.begin(), ilist.end());
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
Referenced by open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), and open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all().
insert() [11/11]
template<class Policy , class Hash , class Eq , class Alloc > template<class T , RequiresInsertable< T > = 0, class T2 = T, typename std::enable_if< IsDecomposable< T2 >::value, int >::type = 0, T * = nullptr> std::pair< iterator, bool > absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert (T && value) inline
Definition at line 1783 of file raw_hash_set.h.
{
    return emplace(std::forward<T>(value));
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace().
Referenced by open_spiel::testing::CheckActionStringsAreUniqueForPlayer(), FlatHashSet(), absl::container_internal::GenerateNumbersWithSeed(), open_spiel::algorithms::HistoryNode::HistoryNode(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert_all(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert_all(), main(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set().
iterator_at() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator_at (size_t i) inline protected
Definition at line 2510 of file raw_hash_set.h.
{
    return {control() + i, slot_array() + i, common().generation_ptr()};
  }
References absl::container_internal::CommonFieldsGenerationInfoDisabled::generation_ptr(), and absl::i.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::begin(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace_at(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::lazy_emplace().
iterator_at() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > const_iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator_at (size_t i) const inline protected
Definition at line 2513 of file raw_hash_set.h.
{
    return {control() + i, slot_array() + i, common().generation_ptr()};
  }
References absl::container_internal::CommonFieldsGenerationInfoDisabled::generation_ptr(), and absl::i.
key_eq()
template<class Policy , class Hash , class Eq , class Alloc > key_equal absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::key_eq () const inline
Definition at line 2198 of file raw_hash_set.h.
{ return eq_ref(); }
lazy_emplace()
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type, class F > iterator absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::lazy_emplace (const key_arg< K > & key, F && f) inline
Definition at line 1955 of file raw_hash_set.h.
{
    auto res = find_or_prepare_insert(key);
    if (res.second) {
      slot_type* slot = slot_array() + res.first;
      std::forward<F>(f)(constructor(&alloc_ref(), &slot));
      assert(!slot);
    }
    return iterator_at(res.first);
  }
References absl::f, absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find_or_prepare_insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator_at(), and key.
load_factor()
template<class Policy , class Hash , class Eq , class Alloc > float absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::load_factor () const inline
Definition at line 2189 of file raw_hash_set.h.
{
    return capacity() ? static_cast<double>(size()) / capacity() : 0.0;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::size().
max_load_factor() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > float absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::max_load_factor () const inline
Definition at line 2192 of file raw_hash_set.h.
{ return 1.0f; }
max_load_factor() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::max_load_factor (float) inline
Definition at line 2193 of file raw_hash_set.h.
{
    // Does nothing.
  }
max_size()
template<class Policy , class Hash , class Eq , class Alloc > size_t absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::max_size () const inline
Definition at line 1741 of file raw_hash_set.h.
{ return (std::numeric_limits<size_t>::max)(); }
Referenced by open_spiel.python.algorithms.alpha_zero.alpha_zero.Buffer::extend(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
merge() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > template<typename H , typename E > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::merge (raw_hash_set< Policy, H, E, Alloc > && src) inline
Definition at line 2030 of file raw_hash_set.h.
{
    merge(src);
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::merge().
merge() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > template<typename H , typename E > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::merge (raw_hash_set< Policy, H, E, Alloc > & src) inline
Definition at line 2016 of file raw_hash_set.h.
                                                     {  // NOLINT
    assert(this != &src);
    for (auto it = src.begin(), e = src.end(); it != e;) {
      auto next = std::next(it);
      if (PolicyTraits::apply(InsertSlot<false>{*this, std::move(*it.slot_)},
                              PolicyTraits::element(it.slot_))
              .second) {
        src.erase_meta_only(it);
      }
      it = next;
    }
  }
References absl::container_internal::hash_policy_traits< Policy, class >::apply(), absl::e, absl::container_internal::common_policy_traits< Policy, class >::element(), and next.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::merge().
operator=() [1/2]
template<class Policy , class Hash , class Eq , class Alloc > raw_hash_set & absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::operator= (const raw_hash_set< Policy, Hash, Eq, Alloc > & that) inline
Definition at line 1689 of file raw_hash_set.h.
{
    raw_hash_set tmp(that,
                     AllocTraits::propagate_on_container_copy_assignment::value
                         ? that.alloc_ref()
                         : alloc_ref());
    swap(tmp);
    return *this;
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::swap.
operator=() [2/2]
template<class Policy , class Hash , class Eq , class Alloc > raw_hash_set & absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::operator= (raw_hash_set< Policy, Hash, Eq, Alloc > && that) inline noexcept
Definition at line 1698 of file raw_hash_set.h.
{
    // TODO(sbenza): We should only use the operations from the noexcept clause
    // to make sure we actually adhere to that contract.
    // NOLINTNEXTLINE: not returning *this for performance.
    return move_assign(
        std::move(that),
        typename AllocTraits::propagate_on_container_move_assignment());
  }
prefetch()
template<class Policy , class Hash , class Eq , class Alloc > template<class K = key_type> void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prefetch (const key_arg< K > & key) const inline
Definition at line 2117 of file raw_hash_set.h.
{
    (void)key;
    // Avoid probing if we won't be able to prefetch the addresses received.
#ifdef ABSL_INTERNAL_HAVE_PREFETCH
    prefetch_heap_block();
    auto seq = probe(common(), hash_ref()(key));
    base_internal::PrefetchT0(control() + seq.offset());
    base_internal::PrefetchT0(slot_array() + seq.offset());
#endif  // ABSL_INTERNAL_HAVE_PREFETCH
  }
References key, absl::base_internal::PrefetchT0(), and absl::container_internal::probe().
prepare_insert()
template<class Policy , class Hash , class Eq , class Alloc > size_t absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert (size_t hash) inline protected
Definition at line 2469 of file raw_hash_set.h.
{
    const bool rehash_for_bug_detection =
        common().should_rehash_for_bug_detection_on_insert();
    if (rehash_for_bug_detection) {
      // Move to a different heap allocation in order to detect bugs.
      const size_t cap = capacity();
      resize(growth_left() > 0 ? cap : NextCapacity(cap));
    }
    auto target = find_first_non_full(common(), hash);
    if (!rehash_for_bug_detection &&
        ABSL_PREDICT_FALSE(growth_left() == 0 &&
                           !IsDeleted(control()[target.offset]))) {
      rehash_and_grow_if_necessary();
      target = find_first_non_full(common(), hash);
    }
    ++common().size_;
    growth_left() -= IsEmpty(control()[target.offset]);
    SetCtrl(common(), target.offset, H2(hash), sizeof(slot_type));
    common().maybe_increment_generation_on_insert();
    infoz().RecordInsert(hash, target.probe_length);
    return target.offset;
  }
References ABSL_PREDICT_FALSE, absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity(), absl::container_internal::find_first_non_full(), absl::container_internal::H2(), hash, absl::container_internal::IsDeleted(), absl::container_internal::IsEmpty(), absl::container_internal::CommonFieldsGenerationInfoDisabled::maybe_increment_generation_on_insert(), absl::container_internal::NextCapacity(), absl::container_internal::HashtablezInfoHandle::RecordInsert(), absl::container_internal::SetCtrl(), absl::container_internal::CommonFieldsGenerationInfoDisabled::should_rehash_for_bug_detection_on_insert(), and absl::container_internal::CommonFields::size_.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find_or_prepare_insert().
rehash()
template<class Policy , class Hash , class Eq , class Alloc > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::rehash (size_t n) inline
Definition at line 2064 of file raw_hash_set.h.
{
    if (n == 0 && capacity() == 0) return;
    if (n == 0 && size() == 0) {
      ClearBackingArray(common(), GetPolicyFunctions(),
                        /*reuse=*/false);
      return;
    }
    // bitor is a faster way of doing `max` here. We will round up to the next
    // power-of-2-minus-1, so bitor is good enough.
    auto m = NormalizeCapacity(n | GrowthToLowerboundCapacity(size()));
    // n == 0 unconditionally rehashes as per the standard.
    if (n == 0 || m > capacity()) {
      resize(m);
      // This is after resize, to ensure that we have completed the allocation
      // and have potentially sampled the hashtable.
      infoz().RecordReservation(n);
    }
  }
References absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::capacity(), absl::container_internal::ClearBackingArray(), absl::container_internal::GrowthToLowerboundCapacity(), absl::n, absl::container_internal::NormalizeCapacity(), absl::container_internal::HashtablezInfoHandle::RecordReservation(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::size().
reserve()
template<class Policy , class Hash , class Eq , class Alloc > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::reserve (size_t n) inline
Definition at line 2085 of file raw_hash_set.h.
{
    if (n > size() + growth_left()) {
      size_t m = GrowthToLowerboundCapacity(n);
      resize(NormalizeCapacity(m));
      // This is after resize, to ensure that we have completed the allocation
      // and have potentially sampled the hashtable.
      infoz().RecordReservation(n);
    }
    common().reset_reserved_growth(n);
  }
References absl::container_internal::GrowthToLowerboundCapacity(), absl::n, absl::container_internal::NormalizeCapacity(), absl::container_internal::HashtablezInfoHandle::RecordReservation(), absl::container_internal::CommonFields::reset_reserved_growth(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::size().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set().
size()
template<class Policy , class Hash , class Eq , class Alloc > size_t absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::size () const inline
Definition at line 1739 of file raw_hash_set.h.
{ return common().size_; }
References absl::container_internal::CommonFields::size_.
Referenced by open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_apply_action(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_apply_action(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_apply_action(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_apply_action(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_rewards(), open_spiel::algorithms::HistoryNode::AddChild(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_average(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::distribution_support(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::empty(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::get_state_proba(), open_spiel::universal_poker::UniformRestrictedActions::GetStatePolicy(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::insert(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::load_factor(), main(), open_spiel.python.algorithms.rcfr.ReservoirBuffer::num_available_spaces(), open_spiel.python.pytorch.rcfr.ReservoirBuffer::num_available_spaces(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::rehash(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::reserve(), open_spiel.python.mfg.games.crowd_avoidance.Observer::set_from(), open_spiel.python.mfg.games.crowd_modelling.Observer::set_from(), open_spiel.python.mfg.games.linear_quadratic.Observer::set_from(), open_spiel.python.mfg.games.periodic_aversion.Observer::set_from(), open_spiel.python.mfg.games.predator_prey.Observer::set_from(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_pos(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_pos(), and open_spiel.python.utils.lru_cache.CacheInfo::usage().
swap()
template<class Policy , class Hash , class Eq , class Alloc > void absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::swap (raw_hash_set< Policy, Hash, Eq, Alloc > & that) inline noexcept
Definition at line 2052 of file raw_hash_set.h.
                                                         {})) {
    using std::swap;
    swap(common(), that.common());
    swap(hash_ref(), that.hash_ref());
    swap(eq_ref(), that.eq_ref());
    SwapAlloc(alloc_ref(), that.alloc_ref(),
              typename AllocTraits::propagate_on_container_swap{});
  }
Friends And Related Symbol Documentation
absl::container_internal::hashtable_debug_internal::HashtableDebugAccess
template<class Policy , class Hash , class Eq , class Alloc > template<class Container , typename Enabler > friend struct absl::container_internal::hashtable_debug_internal::HashtableDebugAccess friend
Definition at line 2230 of file raw_hash_set.h.
AbslHashValue
template<class Policy , class Hash , class Eq , class Alloc > template<typename H > std::enable_if< H::templateis_hashable< value_type >::value, H >::type AbslHashValue (H h, const raw_hash_set< Policy, Hash, Eq, Alloc > & s) friend
Definition at line 2218 of file raw_hash_set.h.
{
    return H::combine(H::combine_unordered(std::move(h), s.begin(), s.end()),
                      s.size());
  }
operator!=
template<class Policy , class Hash , class Eq , class Alloc > bool operator!= (const raw_hash_set< Policy, Hash, Eq, Alloc > & a, const raw_hash_set< Policy, Hash, Eq, Alloc > & b) friend
Definition at line 2211 of file raw_hash_set.h.
{
    return !(a == b);
  }
operator==
template<class Policy , class Hash , class Eq , class Alloc > bool operator== (const raw_hash_set< Policy, Hash, Eq, Alloc > & a, const raw_hash_set< Policy, Hash, Eq, Alloc > & b) friend
Definition at line 2201 of file raw_hash_set.h.
{
    if (a.size() != b.size()) return false;
    const raw_hash_set* outer = &a;
    const raw_hash_set* inner = &b;
    if (outer->capacity() > inner->capacity()) std::swap(outer, inner);
    for (const value_type& elem : *outer)
      if (!inner->has_element(elem)) return false;
    return true;
  }
RawHashSetTestOnlyAccess
template<class Policy , class Hash , class Eq , class Alloc > friend struct RawHashSetTestOnlyAccess friend
Definition at line 2518 of file raw_hash_set.h.
swap
template<class Policy , class Hash , class Eq , class Alloc > void swap (raw_hash_set< Policy, Hash, Eq, Alloc > & a, raw_hash_set< Policy, Hash, Eq, Alloc > & b) friend
Definition at line 2223 of file raw_hash_set.h.
{
    a.swap(b);
  }
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::operator=().
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/raw_hash_set.h