open spiel: open_spiel::dynamic_routing::MeanFieldRoutingGame Class Reference
open_spiel::dynamic_routing::MeanFieldRoutingGame Class Reference
#include <dynamic_routing.h>
Public Member Functions
MeanFieldRoutingGame (const GameParameters &params)
int MaxChanceNodesInHistory () const override
int NumDistinctActions () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
int MaxGameLength () const override
int MaxChanceOutcomes () const override
bool perform_sanity_checks () const
std::unique_ptr< State > NewInitialState () const override
std::vector< int > ObservationTensorShape () const override
std::unique_ptr< State > DeserializeState (const std::string &str) const override
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual std::vector< int > InformationStateTensorShape () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
virtual std::string ActionToString (Player player, Action action_id) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 254 of file dynamic_routing.h.
Constructor & Destructor Documentation
MeanFieldRoutingGame()
open_spiel::dynamic_routing::MeanFieldRoutingGame::MeanFieldRoutingGame (const GameParameters & params) explicit
Definition at line 77 of file dynamic_routing.cc.
    : Game(kGameType, params) {
  // Maps data name from string to the enum.
  const absl::flat_hash_map<std::string, DynamicRoutingDataName>
      data_name_string_to_enum = {{"line", DynamicRoutingDataName::kLine},
                                  {"braess", DynamicRoutingDataName::kBraess}};
  int max_num_time_step =
      ParameterValue<int>("max_num_time_step", kDefaultMaxTimeStep);
  SPIEL_CHECK_NE(max_num_time_step, 0);
  time_step_length_ =
      ParameterValue<double>("time_step_length", kDefaultTimeStepLength);
  network_name_ = ParameterValue<std::string>("network", kDefaultNetworkName);
  SPIEL_CHECK_NE(network_name_, "");
  perform_sanity_checks_ = ParameterValue<bool>("perform_sanity_checks", true);
  std::unique_ptr<DynamicRoutingData> data =
      DynamicRoutingData::Create(data_name_string_to_enum.at(network_name_));
  network_ = std::move(data->network_);
  od_demand_ = std::move(data->od_demand_);
  network_->CheckListOfOdDemandIsCorrect(od_demand_.get());
  game_info_.num_distinct_actions = network_->num_actions();
  game_info_.max_chance_outcomes = static_cast<int>(od_demand_->size());
  game_info_.num_players = kNumPlayers;
  game_info_.min_utility = static_cast<double>(-max_num_time_step - 1);
  game_info_.max_utility = 0;
  game_info_.max_game_length = max_num_time_step;
}
References open_spiel::dynamic_routing::DynamicRoutingData::Create(), open_spiel::dynamic_routing::kBraess, open_spiel::dynamic_routing::kDefaultMaxTimeStep, open_spiel::dynamic_routing::kDefaultNetworkName, open_spiel::dynamic_routing::kDefaultTimeStepLength, open_spiel::dynamic_routing::kLine, open_spiel::dynamic_routing::kNumPlayers, open_spiel::GameInfo::max_chance_outcomes, open_spiel::GameInfo::max_game_length, open_spiel::GameInfo::max_utility, open_spiel::GameInfo::min_utility, open_spiel::GameInfo::num_distinct_actions, open_spiel::GameInfo::num_players, open_spiel::Game::ParameterValue(), and SPIEL_CHECK_NE.
Member Function Documentation
DeserializeState()
std::unique_ptr< State > open_spiel::dynamic_routing::MeanFieldRoutingGame::DeserializeState (const std::string & str) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 105 of file dynamic_routing.cc.
{
  std::vector<std::string> properties = absl::StrSplit(str, ',');
  if (properties.size() != 10) {
    SpielFatalError(
        absl::StrCat("Expected 10 properties for serialized state, got: ",
                     properties.size()));
  }
  int current_time_step;
  open_spiel::PlayerId player_id;
  bool is_chance_init, is_terminal, vehicle_at_destination,
      vehicle_without_legal_action;
  int waiting_time;
  double vehicle_final_travel_time;
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[0], &current_time_step));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[1], &player_id));
  SPIEL_CHECK_TRUE(absl::SimpleAtob(properties[2], &is_chance_init));
  SPIEL_CHECK_TRUE(absl::SimpleAtob(properties[3], &is_terminal));
  SPIEL_CHECK_TRUE(absl::SimpleAtob(properties[4], &vehicle_at_destination));
  SPIEL_CHECK_TRUE(
      absl::SimpleAtob(properties[5], &vehicle_without_legal_action));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(properties[6], &waiting_time));
  SPIEL_CHECK_TRUE(absl::SimpleAtod(properties[7], &vehicle_final_travel_time));
  std::string vehicle_location(properties[8]),
      vehicle_destination(properties[9]);
  return MeanFieldRoutingGameState::Create(
      shared_from_this(), time_step_length_, od_demand_.get(), network_.get(),
      perform_sanity_checks_, current_time_step, player_id, is_chance_init,
      is_terminal, vehicle_at_destination, vehicle_without_legal_action,
      waiting_time, vehicle_final_travel_time, vehicle_location,
      vehicle_destination);
}
References absl::SimpleAtob(), absl::SimpleAtod(), absl::SimpleAtoi(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), absl::StrCat(), and absl::StrSplit().
MaxChanceNodesInHistory()
int open_spiel::dynamic_routing::MeanFieldRoutingGame::MaxChanceNodesInHistory () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 263 of file dynamic_routing.h.
{ return 1; }
MaxChanceOutcomes()
int open_spiel::dynamic_routing::MeanFieldRoutingGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 288 of file dynamic_routing.h.
{
    return game_info_.max_chance_outcomes;
  }
References open_spiel::GameInfo::max_chance_outcomes.
MaxGameLength()
int open_spiel::dynamic_routing::MeanFieldRoutingGame::MaxGameLength () const inline override virtual
Implements open_spiel::Game.
Definition at line 285 of file dynamic_routing.h.
{ return game_info_.max_game_length; }
References open_spiel::GameInfo::max_game_length.
Referenced by ObservationTensorShape().
MaxUtility()
double open_spiel::dynamic_routing::MeanFieldRoutingGame::MaxUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 283 of file dynamic_routing.h.
{ return game_info_.max_utility; }
References open_spiel::GameInfo::max_utility.
MinUtility()
double open_spiel::dynamic_routing::MeanFieldRoutingGame::MinUtility () const inline override virtual
Implements open_spiel::Game.
Definition at line 278 of file dynamic_routing.h.
{
    SPIEL_CHECK_EQ(game_info_.min_utility, -1 * game_info_.max_game_length - 1);
    return game_info_.min_utility;
  }
References open_spiel::GameInfo::max_game_length, open_spiel::GameInfo::min_utility, and SPIEL_CHECK_EQ.
NewInitialState()
std::unique_ptr< State > open_spiel::dynamic_routing::MeanFieldRoutingGame::NewInitialState () const inline override virtual
Implements open_spiel::Game.
Definition at line 296 of file dynamic_routing.h.
{
    return MeanFieldRoutingGameState::CreateNewInitialState(
        shared_from_this(), time_step_length_, od_demand_.get(), network_.get(),
        perform_sanity_checks_);
  }
References open_spiel::dynamic_routing::MeanFieldRoutingGameState::CreateNewInitialState().
NumDistinctActions()
int open_spiel::dynamic_routing::MeanFieldRoutingGame::NumDistinctActions () const inline override virtual
Implements open_spiel::Game.
Definition at line 267 of file dynamic_routing.h.
{
    return game_info_.num_distinct_actions;
  }
References open_spiel::GameInfo::num_distinct_actions.
NumPlayers()
int open_spiel::dynamic_routing::MeanFieldRoutingGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 272 of file dynamic_routing.h.
{
    SPIEL_CHECK_EQ(game_info_.num_players, 1);
    return game_info_.num_players;
  }
References open_spiel::GameInfo::num_players, and SPIEL_CHECK_EQ.
ObservationTensorShape()
std::vector< int > open_spiel::dynamic_routing::MeanFieldRoutingGame::ObservationTensorShape () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 303 of file dynamic_routing.h.
{
    int num_locations = network_->num_actions();
    int max_num_time_step = MaxGameLength();
    return {num_locations * 2 + max_num_time_step + 1 + 1};
  }
References MaxGameLength().
perform_sanity_checks()
bool open_spiel::dynamic_routing::MeanFieldRoutingGame::perform_sanity_checks () const inline
Definition at line 293 of file dynamic_routing.h.
{ return perform_sanity_checks_; }
The documentation for this class was generated from the following files:
open_spiel/games/mfg/dynamic_routing.h
open_spiel/games/mfg/dynamic_routing.cc