open spiel: absl::container_internal::HashSetIteratorGenerationInfoDisabled Class Reference
absl::container_internal::HashSetIteratorGenerationInfoDisabled Class Reference
#include <raw_hash_set.h>
Public Member Functions
HashSetIteratorGenerationInfoDisabled ()=default
HashSetIteratorGenerationInfoDisabled (const GenerationType *)
GenerationType generation () const
void reset_generation ()
const GenerationType * generation_ptr () const
void set_generation_ptr (const GenerationType *)
Detailed Description
Definition at line 851 of file raw_hash_set.h.
Constructor & Destructor Documentation
HashSetIteratorGenerationInfoDisabled() [1/2]
absl::container_internal::HashSetIteratorGenerationInfoDisabled::HashSetIteratorGenerationInfoDisabled () default
HashSetIteratorGenerationInfoDisabled() [2/2]
absl::container_internal::HashSetIteratorGenerationInfoDisabled::HashSetIteratorGenerationInfoDisabled (const GenerationType *) inline explicit
Definition at line 854 of file raw_hash_set.h.
{}
Member Function Documentation
generation()
GenerationType absl::container_internal::HashSetIteratorGenerationInfoDisabled::generation () const inline
Definition at line 856 of file raw_hash_set.h.
{ return 0; }
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator*(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator++(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator->().
generation_ptr()
const GenerationType * absl::container_internal::HashSetIteratorGenerationInfoDisabled::generation_ptr () const inline
Definition at line 858 of file raw_hash_set.h.
{ return nullptr; }
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator*(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator++(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator->().
reset_generation()
void absl::container_internal::HashSetIteratorGenerationInfoDisabled::reset_generation () inline
Definition at line 857 of file raw_hash_set.h.
{}
set_generation_ptr()
void absl::container_internal::HashSetIteratorGenerationInfoDisabled::set_generation_ptr (const GenerationType *) inline
Definition at line 859 of file raw_hash_set.h.
{}
The documentation for this class was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/raw_hash_set.h