open spiel: open_spiel::sheriff::SheriffGame Class Reference
open_spiel::sheriff::SheriffGame Class Reference final
#include <sheriff.h>
Classes
struct SheriffGameConfiguration
Public Member Functions
SheriffGame (const GameParameters &params)
int NumDistinctActions () const override
std::unique_ptr< State > NewInitialState () const override
int MaxChanceOutcomes () const override
int NumPlayers () const override
double MinUtility () const override
double MaxUtility () const override
int MaxGameLength () const override
std::string ActionToString (Player player, Action action_id) const override
std::vector< int > InformationStateTensorShape () const override
uint32_t num_rounds () const
uint32_t max_items () const
uint32_t max_bribe () const
Action SerializeItemPlacementAction (uint32_t num_illegal_items) const
Action SerializeBribe (uint32_t bribe) const
Action SerializeInspectionFeedback (bool feedback) const
uint32_t DeserializeItemPlacementAction (Action action_id) const
uint32_t DeserializeBribe (Action action_id) const
bool DeserializeInspectionFeedback (Action action_id) const
Public Member Functions inherited from open_spiel::Game
virtual ~Game ()=default
Game (const Game &)=delete
Game & operator= (const Game &)=delete
virtual std::unique_ptr< State > NewInitialState (const std::string &str) const
virtual std::vector< std::unique_ptr< State > > NewInitialStates () const
GameParameters GetParameters () const
const GameType & GetType () const
virtual absl::optional< double > UtilitySum () const
virtual TensorLayout InformationStateTensorLayout () const
int InformationStateTensorSize () const
virtual std::vector< int > ObservationTensorShape () const
virtual TensorLayout ObservationTensorLayout () const
int ObservationTensorSize () const
virtual std::vector< int > PolicyTensorShape () const
virtual std::unique_ptr< State > DeserializeState (const std::string &str) const
virtual int MaxChanceNodesInHistory () const
virtual int MaxMoveNumber () const
virtual int MaxHistoryLength () const
std::string Serialize () const
std::string ToString () const
virtual bool operator== (const Game &other) const
virtual std::string GetRNGState () const
virtual void SetRNGState (const std::string &rng_state) const
virtual std::shared_ptr< Observer > MakeObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeRegisteredObserver (absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params) const
std::shared_ptr< Observer > MakeBuiltInObserver (absl::optional< IIGObservationType > iig_obs_type) const
virtual std::unique_ptr< State > NewInitialStateForPopulation (int population) const
Public Attributes
struct open_spiel::sheriff::SheriffGame::SheriffGameConfiguration conf
Additional Inherited Members
Protected Member Functions inherited from open_spiel::Game
Game (GameType game_type, GameParameters game_parameters)
template<typename T >
T ParameterValue (const std::string &key, absl::optional< T > default_value=absl::nullopt) const
GameParameters defaulted_parameters_ ABSL_GUARDED_BY (mutex_defaulted_parameters_)
Protected Attributes inherited from open_spiel::Game
GameType game_type_
GameParameters game_parameters_
absl::Mutex mutex_defaulted_parameters_
Detailed Description
Definition at line 130 of file sheriff.h.
Constructor & Destructor Documentation
SheriffGame()
open_spiel::sheriff::SheriffGame::SheriffGame (const GameParameters & params) explicit
Definition at line 338 of file sheriff.cc.
    : Game(kGameType, params) {
  conf.item_penalty = ParameterValue<double>("item_penalty");
  SPIEL_CHECK_GE(conf.item_penalty, 0.0);
  conf.item_value = ParameterValue<double>("item_value");
  SPIEL_CHECK_GE(conf.item_value, 0.0);
  conf.sheriff_penalty = ParameterValue<double>("sheriff_penalty");
  SPIEL_CHECK_GE(conf.sheriff_penalty, 0.0);
  conf.max_bribe = ParameterValue<int>("max_bribe");
  SPIEL_CHECK_GE(conf.max_bribe, 0);
  conf.max_items = ParameterValue<int>("max_items");
  SPIEL_CHECK_GE(conf.max_items, 1);
  conf.num_rounds = ParameterValue<int>("num_rounds");
  SPIEL_CHECK_GE(conf.num_rounds, 1);
}
References conf, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::item_penalty, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::item_value, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_bribe, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::num_rounds, open_spiel::Game::ParameterValue(), open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::sheriff_penalty, and SPIEL_CHECK_GE.
Member Function Documentation
ActionToString()
std::string open_spiel::sheriff::SheriffGame::ActionToString (Player player, Action action_id) const override virtual
Reimplemented from open_spiel::Game.
Definition at line 383 of file sheriff.cc.
{
  std::string action_string;
  if (action_id < 2) {
    SPIEL_CHECK_EQ(player, kSheriff);
    const bool feedback = DeserializeInspectionFeedback(action_id);
    if (!feedback) {
      action_string = "InspectionFeedback(will_inspect=False)";
    } else {
      action_string = "InspectionFeedback(will_inspect=True)";
    }
  } else if (action_id < 3 + conf.max_items) {
    SPIEL_CHECK_EQ(player, kSmuggler);
    const uint32_t num_illegal_items =
        DeserializeItemPlacementAction(action_id);
    absl::StrAppend(&action_string, "PlaceIllegalItems(num=", num_illegal_items,
                    ")");
  } else {
    SPIEL_CHECK_EQ(player, kSmuggler);
    const uint32_t bribe = DeserializeBribe(action_id);
    absl::StrAppend(&action_string, "Bribe(amount=", bribe, ")");
  }
  return action_string;
}
References conf, DeserializeBribe(), DeserializeInspectionFeedback(), DeserializeItemPlacementAction(), open_spiel::sheriff::kSheriff, open_spiel::sheriff::kSmuggler, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, player, SPIEL_CHECK_EQ, and absl::StrAppend().
DeserializeBribe()
uint32_t open_spiel::sheriff::SheriffGame::DeserializeBribe (Action action_id) const
Definition at line 438 of file sheriff.cc.
{
  SPIEL_CHECK_GE(action_id, 3 + conf.max_items);
  SPIEL_CHECK_LE(action_id, 3 + conf.max_items + conf.max_bribe);
  return action_id - 3 - conf.max_items;
}
References conf, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_bribe, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Referenced by ActionToString().
DeserializeInspectionFeedback()
bool open_spiel::sheriff::SheriffGame::DeserializeInspectionFeedback (Action action_id) const
Definition at line 445 of file sheriff.cc.
{
  SPIEL_CHECK_TRUE(action_id == 0 || action_id == 1);
  if (action_id == 0) {
    return false;
  } else {
    return true;
  }
}
References SPIEL_CHECK_TRUE.
Referenced by ActionToString().
DeserializeItemPlacementAction()
uint32_t open_spiel::sheriff::SheriffGame::DeserializeItemPlacementAction (Action action_id) const
Definition at line 430 of file sheriff.cc.
{
  SPIEL_CHECK_GE(action_id, 2);
  SPIEL_CHECK_LE(action_id, 2 + conf.max_items);
  return action_id - 2;
}
References conf, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Referenced by ActionToString().
InformationStateTensorShape()
std::vector< int > open_spiel::sheriff::SheriffGame::InformationStateTensorShape () const override virtual
Reimplemented from open_spiel::Game.
Definition at line 227 of file sheriff.cc.
{
  return {
    2 +                                      // Whose turn?
    2 +                                      // Who is observing?
    static_cast<int>(conf.num_rounds) + 1 +  // Move number (0 to rounds)
    static_cast<int>(conf.max_items) + 1 +   // Number of items (0 to max)
    // Each round, a bribe in { 0, 1, ...,  max_bribe } plus one bit for yes/no
    static_cast<int>(conf.num_rounds) *
        (static_cast<int>(conf.max_bribe) + 1 + 1)
  };
}
References conf, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_bribe, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, and open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::num_rounds.
max_bribe()
uint32_t open_spiel::sheriff::SheriffGame::max_bribe () const inline
Definition at line 148 of file sheriff.h.
{ return conf.max_bribe; }
References conf, and open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_bribe.
max_items()
uint32_t open_spiel::sheriff::SheriffGame::max_items () const inline
Definition at line 147 of file sheriff.h.
{ return conf.max_items; }
References conf, and open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items.
MaxChanceOutcomes()
int open_spiel::sheriff::SheriffGame::MaxChanceOutcomes () const inline override virtual
Reimplemented from open_spiel::Game.
Definition at line 137 of file sheriff.h.
{ return 0; }
MaxGameLength()
int open_spiel::sheriff::SheriffGame::MaxGameLength () const override virtual
Implements open_spiel::Game.
Definition at line 381 of file sheriff.cc.
{ return 2 * conf.num_rounds + 1; }
References conf, and open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::num_rounds.
MaxUtility()
double open_spiel::sheriff::SheriffGame::MaxUtility () const override virtual
Implements open_spiel::Game.
Definition at line 375 of file sheriff.cc.
{
  return std::max({conf.sheriff_penalty, static_cast<double>(conf.max_bribe),
                   static_cast<double>(conf.max_items) * conf.item_value,
                   static_cast<double>(conf.max_items) * conf.item_penalty});
}
References conf, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::item_penalty, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::item_value, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_bribe, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, and open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::sheriff_penalty.
MinUtility()
double open_spiel::sheriff::SheriffGame::MinUtility () const override virtual
Implements open_spiel::Game.
Definition at line 369 of file sheriff.cc.
{
  return std::min({-static_cast<double>(conf.max_items) * conf.item_penalty,
                   -static_cast<double>(conf.max_bribe),
                   -conf.sheriff_penalty});
}
References conf, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::item_penalty, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_bribe, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, and open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::sheriff_penalty.
NewInitialState()
std::unique_ptr< State > open_spiel::sheriff::SheriffGame::NewInitialState () const override virtual
Implements open_spiel::Game.
Definition at line 363 of file sheriff.cc.
{
  const auto ptr =
      std::dynamic_pointer_cast<const SheriffGame>(shared_from_this());
  return std::make_unique<SheriffState>(ptr);
}
References ptr.
num_rounds()
uint32_t open_spiel::sheriff::SheriffGame::num_rounds () const inline
Definition at line 146 of file sheriff.h.
{ return conf.num_rounds; }
References conf, and open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::num_rounds.
NumDistinctActions()
int open_spiel::sheriff::SheriffGame::NumDistinctActions () const override virtual
Implements open_spiel::Game.
Definition at line 359 of file sheriff.cc.
{
  return 4 + conf.max_items + conf.max_bribe;
}
References conf, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_bribe, and open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items.
NumPlayers()
int open_spiel::sheriff::SheriffGame::NumPlayers () const inline override virtual
Implements open_spiel::Game.
Definition at line 138 of file sheriff.h.
{ return 2; }
SerializeBribe()
Action open_spiel::sheriff::SheriffGame::SerializeBribe (uint32_t bribe) const
Definition at line 417 of file sheriff.cc.
{
  SPIEL_CHECK_LE(bribe, conf.max_bribe);
  return 3 + conf.max_items + bribe;
}
References conf, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_bribe, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, and SPIEL_CHECK_LE.
SerializeInspectionFeedback()
Action open_spiel::sheriff::SheriffGame::SerializeInspectionFeedback (bool feedback) const
Definition at line 422 of file sheriff.cc.
{
  if (!feedback) {
    return 0;
  } else {
    return 1;
  }
}
SerializeItemPlacementAction()
Action open_spiel::sheriff::SheriffGame::SerializeItemPlacementAction (uint32_t num_illegal_items) const
Definition at line 411 of file sheriff.cc.
{
  SPIEL_CHECK_LE(num_illegal_items, conf.max_items);
  return 2 + num_illegal_items;
}
References conf, open_spiel::sheriff::SheriffGame::SheriffGameConfiguration::max_items, and SPIEL_CHECK_LE.
Member Data Documentation
conf
struct open_spiel::sheriff::SheriffGame::SheriffGameConfiguration open_spiel::sheriff::SheriffGame::conf
Referenced by ActionToString(), DeserializeBribe(), DeserializeItemPlacementAction(), InformationStateTensorShape(), max_bribe(), max_items(), MaxGameLength(), MaxUtility(), MinUtility(), num_rounds(), NumDistinctActions(), SerializeBribe(), SerializeItemPlacementAction(), and SheriffGame().
The documentation for this class was generated from the following files:
open_spiel/games/sheriff/sheriff.h
open_spiel/games/sheriff/sheriff.cc