open spiel: open_spiel/games/colored_trails/colored_trails_board_generator.cc File Reference
colored_trails_board_generator.cc File Reference
#include <random>
#include <string>
#include "open_spiel/abseil-cpp/absl/flags/flag.h"
#include "open_spiel/abseil-cpp/absl/flags/parse.h"
#include "open_spiel/abseil-cpp/absl/random/distributions.h"
#include "open_spiel/games/colored_trails/colored_trails.h"
#include "open_spiel/utils/file.h"
#include "open_spiel/utils/init.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
namespace open_spiel::colored_trails
Functions
ABSL_FLAG (int, seed, 0, "Seed to use")
ABSL_FLAG (int, num_boards, 10000, "Number of boards to generate.")
ABSL_FLAG (std::string, filename, "/tmp/boards.txt", "File to save boards to.")
int main (int argc, char **argv)
Function Documentation
ABSL_FLAG() [1/3]
ABSL_FLAG (int , num_boards , 10000 , "Number of boards to generate.")
ABSL_FLAG() [2/3]
ABSL_FLAG (int , seed , 0 , "Seed to use")
ABSL_FLAG() [3/3]
ABSL_FLAG (std::string , filename , "/tmp/boards.txt" , "File to save boards to.")
main()
int main (int argc, char ** argv)
Definition at line 112 of file colored_trails_board_generator.cc.
{
  open_spiel::Init("", &argc, &argv, false);
  absl::ParseCommandLine(argc, argv);
  open_spiel::colored_trails::GenerateBoards(absl::GetFlag(FLAGS_num_boards));
}
References absl::GetFlag(), open_spiel::Init(), and absl::ParseCommandLine().