open spiel: open_spiel/abseil-cpp/absl/strings/cord_test.cc File Reference
cord_test.cc File Reference
#include "absl/strings/cord.h"
#include <algorithm>
#include <climits>
#include <cstdio>
#include <iterator>
#include <map>
#include <numeric>
#include <random>
#include <sstream>
#include <type_traits>
#include <utility>
#include <vector>
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "absl/base/config.h"
#include "absl/base/internal/endian.h"
#include "absl/base/internal/raw_logging.h"
#include "absl/base/macros.h"
#include "absl/container/fixed_array.h"
#include "absl/hash/hash.h"
#include "absl/random/random.h"
#include "absl/strings/cord_test_helpers.h"
#include "absl/strings/cordz_test_helpers.h"
#include "absl/strings/match.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/str_format.h"
#include "absl/strings/string_view.h"
Classes
class absl::CordTestPeer
class CordTest
class CordAppendBufferTest
class AfterExitCordTester
struct CordLeaker
struct ShortView
struct LongView
Namespaces
namespace absl
Typedefs
typedef std::mt19937_64 RandomEngine
Functions
INSTANTIATE_TEST_SUITE_P (WithParam, CordTest, testing::Values(0, 1), CordTest::ToString)
TEST (CordRepFlat, AllFlatCapacities)
TEST (CordRepFlat, MaxFlatSize)
TEST (CordRepFlat, MaxLargeFlatSize)
TEST (CordRepFlat, AllFlatSizes)
TEST_P (CordTest, AllFlatSizes)
TEST_P (CordTest, GigabyteCordFromExternal)
TEST_P (CordTest, Assignment)
TEST_P (CordTest, StartsEndsWith)
TEST_P (CordTest, Subcord)
TEST_P (CordTest, Swap)
TEST_P (CordTest, CopyToString)
TEST_P (CordTest, AppendEmptyBuffer)
TEST_P (CordTest, AppendEmptyBufferToFlat)
TEST_P (CordTest, AppendEmptyBufferToTree)
TEST_P (CordTest, AppendSmallBuffer)
TEST_P (CordTest, AppendAndPrependBufferArePrecise)
TEST_P (CordTest, PrependSmallBuffer)
TEST_P (CordTest, AppendLargeBuffer)
TEST_P (CordTest, PrependLargeBuffer)
INSTANTIATE_TEST_SUITE_P (WithParam, CordAppendBufferTest, testing::Bool(), CordAppendBufferTest::ToString)
TEST_P (CordAppendBufferTest, GetAppendBufferOnEmptyCord)
TEST_P (CordAppendBufferTest, GetAppendBufferOnInlinedCord)
TEST_P (CordAppendBufferTest, GetAppendBufferOnInlinedCordCapacityCloseToMax)
TEST_P (CordAppendBufferTest, GetAppendBufferOnFlat)
TEST_P (CordAppendBufferTest, GetAppendBufferOnFlatWithoutMinCapacity)
TEST_P (CordAppendBufferTest, GetAppendBufferOnTree)
TEST_P (CordAppendBufferTest, GetAppendBufferOnTreeWithoutMinCapacity)
TEST_P (CordAppendBufferTest, GetAppendBufferOnSubstring)
TEST_P (CordAppendBufferTest, GetAppendBufferOnSharedCord)
TEST_P (CordTest, TryFlatEmpty)
TEST_P (CordTest, TryFlatFlat)
TEST_P (CordTest, TryFlatSubstrInlined)
TEST_P (CordTest, TryFlatSubstrFlat)
TEST_P (CordTest, TryFlatConcat)
TEST_P (CordTest, TryFlatExternal)
TEST_P (CordTest, TryFlatSubstrExternal)
TEST_P (CordTest, TryFlatCommonlyAssumedInvariants)
TEST_P (CordTest, Flatten)
TEST_P (CordTest, MultipleLengths)
TEST_P (CordTest, Concat_Append)
TEST_P (CordTest, DiabolicalGrowth)
TEST_P (CordTest, HugeCord)
TEST_P (CordTest, AppendSelf)
TEST_P (CordTest, MakeFragmentedCordFromInitializerList)
TEST_P (CordTest, MakeFragmentedCordFromVector)
TEST_P (CordTest, CordChunkIteratorTraits)
TEST_P (CordTest, CordChunkIteratorOperations)
TEST_P (CordTest, AdvanceAndReadOnDataEdge)
TEST_P (CordTest, AdvanceAndReadOnSubstringDataEdge)
TEST_P (CordTest, CharIteratorTraits)
TEST_P (CordTest, CharIteratorOperations)
TEST_P (CordTest, CharIteratorAdvanceAndRead)
TEST_P (CordTest, StreamingOutput)
TEST_P (CordTest, ForEachChunk)
TEST_P (CordTest, SmallBufferAssignFromOwnData)
TEST_P (CordTest, Format)
TEST_P (CordTest, Hardening)
TEST_P (CordTest, BtreeHostileSplitInsertJoin)
template<typename Str >
void TestConstinitConstructor (Str)
constexpr int SimpleStrlen (const char *p)
TEST_P (CordTest, ConstinitConstructor)
TEST_P (CordTest, ExpectedChecksum)
TEST_P (CordTest, ChecksummedEmptyCord)
Variables
bool my_unique_true_boolean = true
Typedef Documentation
RandomEngine
typedef std::mt19937_64 RandomEngine
Definition at line 49 of file cord_test.cc.
Function Documentation
INSTANTIATE_TEST_SUITE_P() [1/2]
INSTANTIATE_TEST_SUITE_P (WithParam , CordAppendBufferTest , testing::Bool() , CordAppendBufferTest::ToString)
INSTANTIATE_TEST_SUITE_P() [2/2]
INSTANTIATE_TEST_SUITE_P (WithParam , CordTest , testing::Values(0, 1) , CordTest::ToString)
SimpleStrlen()
int SimpleStrlen (const char * p) constexpr
Definition at line 2619 of file cord_test.cc.
{
  return *p ? 1 + SimpleStrlen(p + 1) : 0;
}
References SimpleStrlen().
Referenced by LongView::operator()(), ShortView::operator()(), and SimpleStrlen().
TEST() [1/4]
TEST (CordRepFlat , AllFlatCapacities)
Definition at line 258 of file cord_test.cc.
{
  // Explicitly and redundantly assert built-in min/max limits
  static_assert(absl::cord_internal::kFlatOverhead < 32, "");
  static_assert(absl::cord_internal::kMinFlatSize == 32, "");
  static_assert(absl::cord_internal::kMaxLargeFlatSize == 256 << 10, "");
  EXPECT_EQ(absl::cord_internal::TagToAllocatedSize(FLAT), 32);
  EXPECT_EQ(absl::cord_internal::TagToAllocatedSize(MAX_FLAT_TAG), 256 << 10);
  // Verify all tags to map perfectly back and forth, and
  // that sizes are monotonically increasing.
  size_t last_size = 0;
  for (int tag = FLAT; tag <= MAX_FLAT_TAG; ++tag) {
    size_t size = absl::cord_internal::TagToAllocatedSize(tag);
    ASSERT_GT(size, last_size);
    ASSERT_EQ(absl::cord_internal::TagToAllocatedSize(tag), size);
    last_size = size;
  }
  // All flat size from 32 - 512 are 8 byte granularity
  for (size_t size = 32; size <= 512; size += 8) {
    ASSERT_EQ(absl::cord_internal::RoundUpForTag(size), size);
    uint8_t tag = absl::cord_internal::AllocatedSizeToTag(size);
    ASSERT_EQ(absl::cord_internal::TagToAllocatedSize(tag), size);
  }
  // All flat sizes from 512 - 8192 are 64 byte granularity
  for (size_t size = 512; size <= 8192; size += 64) {
    ASSERT_EQ(absl::cord_internal::RoundUpForTag(size), size);
    uint8_t tag = absl::cord_internal::AllocatedSizeToTag(size);
    ASSERT_EQ(absl::cord_internal::TagToAllocatedSize(tag), size);
  }
  // All flat sizes from 8KB to 256KB are 4KB granularity
  for (size_t size = 8192; size <= 256 * 1024; size += 4 * 1024) {
    ASSERT_EQ(absl::cord_internal::RoundUpForTag(size), size);
    uint8_t tag = absl::cord_internal::AllocatedSizeToTag(size);
    ASSERT_EQ(absl::cord_internal::TagToAllocatedSize(tag), size);
  }
}
References absl::cord_internal::AllocatedSizeToTag(), absl::cord_internal::RoundUpForTag(), size, and absl::cord_internal::TagToAllocatedSize().
TEST() [2/4]
TEST (CordRepFlat , AllFlatSizes)
Definition at line 315 of file cord_test.cc.
{
  const size_t kMaxSize = 256 * 1024;
  for (size_t size = 32; size <= kMaxSize; size *=2) {
    const size_t length = size - kFlatOverhead - 1;
    CordRepFlat* flat = CordRepFlat::New(CordRepFlat::Large(), length);
    EXPECT_GE(flat->Capacity(), length);
    memset(flat->Data(), 0xCD, flat->Capacity());
    CordRep::Unref(flat);
  }
}
References absl::cord_internal::CordRepFlat::Capacity(), absl::cord_internal::CordRepFlat::Data(), absl::cord_internal::CordRepFlat::New(), size, and absl::cord_internal::CordRep::Unref().
TEST() [3/4]
TEST (CordRepFlat , MaxFlatSize)
Definition at line 298 of file cord_test.cc.
{
  CordRepFlat* flat = CordRepFlat::New(kMaxFlatLength);
  EXPECT_EQ(flat->Capacity(), kMaxFlatLength);
  CordRep::Unref(flat);
  flat = CordRepFlat::New(kMaxFlatLength * 4);
  EXPECT_EQ(flat->Capacity(), kMaxFlatLength);
  CordRep::Unref(flat);
}
References absl::cord_internal::CordRepFlat::Capacity(), absl::cord_internal::CordRepFlat::New(), and absl::cord_internal::CordRep::Unref().
TEST() [4/4]
TEST (CordRepFlat , MaxLargeFlatSize)
Definition at line 308 of file cord_test.cc.
{
  const size_t size = 256 * 1024 - kFlatOverhead;
  CordRepFlat* flat = CordRepFlat::New(CordRepFlat::Large(), size);
  EXPECT_GE(flat->Capacity(), size);
  CordRep::Unref(flat);
}
References absl::cord_internal::CordRepFlat::Capacity(), absl::cord_internal::CordRepFlat::New(), size, and absl::cord_internal::CordRep::Unref().
TEST_P() [1/56]
TEST_P (CordAppendBufferTest , GetAppendBufferOnEmptyCord)
Definition at line 765 of file cord_test.cc.
{
  absl::Cord cord;
  absl::CordBuffer buffer = GetAppendBuffer(cord, 1000);
  EXPECT_GE(buffer.capacity(), 1000);
  EXPECT_EQ(buffer.length(), 0);
}
References absl::CordBuffer::capacity(), and absl::CordBuffer::length().
TEST_P() [2/56]
TEST_P (CordAppendBufferTest , GetAppendBufferOnFlat)
Definition at line 800 of file cord_test.cc.
{
  // Create a cord with a single flat and extra capacity
  absl::Cord cord;
  absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(500);
  const size_t expected_capacity = buffer.capacity();
  buffer.SetLength(3);
  memcpy(buffer.data(), "Abc", 3);
  cord.Append(std::move(buffer));
  buffer = GetAppendBuffer(cord, 6);
  EXPECT_EQ(buffer.capacity(), expected_capacity);
  EXPECT_EQ(buffer.length(), 3);
  EXPECT_EQ(absl::string_view(buffer.data(), buffer.length()), "Abc");
  EXPECT_TRUE(cord.empty());
}
References absl::Cord::Append(), absl::CordBuffer::capacity(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), absl::Cord::empty(), absl::CordBuffer::length(), and absl::CordBuffer::SetLength().
TEST_P() [3/56]
TEST_P (CordAppendBufferTest , GetAppendBufferOnFlatWithoutMinCapacity)
Definition at line 816 of file cord_test.cc.
{
  // Create a cord with a single flat and extra capacity
  absl::Cord cord;
  absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(500);
  buffer.SetLength(30);
  memset(buffer.data(), 'x', 30);
  cord.Append(std::move(buffer));
  buffer = GetAppendBuffer(cord, 1000, 900);
  EXPECT_GE(buffer.capacity(), 1000);
  EXPECT_EQ(buffer.length(), 0);
  EXPECT_EQ(cord, std::string(30, 'x'));
}
References absl::Cord::Append(), absl::CordBuffer::capacity(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), absl::CordBuffer::length(), and absl::CordBuffer::SetLength().
TEST_P() [4/56]
TEST_P (CordAppendBufferTest , GetAppendBufferOnInlinedCord)
Definition at line 772 of file cord_test.cc.
{
  static constexpr int kInlinedSize = sizeof(absl::CordBuffer) - 1;
  for (int size : {6, kInlinedSize - 3, kInlinedSize - 2, 1000}) {
    absl::Cord cord("Abc");
    absl::CordBuffer buffer = GetAppendBuffer(cord, size, 1);
    EXPECT_GE(buffer.capacity(), 3 + size);
    EXPECT_EQ(buffer.length(), 3);
    EXPECT_EQ(absl::string_view(buffer.data(), buffer.length()), "Abc");
    EXPECT_TRUE(cord.empty());
  }
}
References absl::CordBuffer::capacity(), absl::CordBuffer::data(), absl::Cord::empty(), absl::CordBuffer::length(), and size.
TEST_P() [5/56]
TEST_P (CordAppendBufferTest , GetAppendBufferOnInlinedCordCapacityCloseToMax)
Definition at line 784 of file cord_test.cc.
{
  // Cover the use case where we have a non empty inlined cord with some size
  // 'n', and ask for something like 'uint64_max - k', assuming internal logic
  // could overflow on 'uint64_max - k + size', and return a valid, but
  // inefficiently smaller buffer if it would provide is the max allowed size.
  for (size_t dist_from_max = 0; dist_from_max <= 4; ++dist_from_max) {
    absl::Cord cord("Abc");
    size_t size = std::numeric_limits<size_t>::max() - dist_from_max;
    absl::CordBuffer buffer = GetAppendBuffer(cord, size, 1);
    EXPECT_GE(buffer.capacity(), maximum_payload());
    EXPECT_EQ(buffer.length(), 3);
    EXPECT_EQ(absl::string_view(buffer.data(), buffer.length()), "Abc");
    EXPECT_TRUE(cord.empty());
  }
}
References absl::CordBuffer::capacity(), absl::CordBuffer::data(), absl::Cord::empty(), absl::CordBuffer::length(), and size.
TEST_P() [6/56]
TEST_P (CordAppendBufferTest , GetAppendBufferOnSharedCord)
Definition at line 882 of file cord_test.cc.
{
  // Create a shared cord with a single flat and extra capacity
  absl::Cord cord;
  absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(500);
  buffer.SetLength(3);
  memcpy(buffer.data(), "Abc", 3);
  cord.Append(std::move(buffer));
  absl::Cord shared_cord = cord;
  // Deny on flat
  buffer = GetAppendBuffer(cord, 6);
  EXPECT_EQ(buffer.length(), 0);
  EXPECT_EQ(cord, "Abc");
  buffer = absl::CordBuffer::CreateWithDefaultLimit(500);
  buffer.SetLength(3);
  memcpy(buffer.data(), "def", 3);
  cord.Append(std::move(buffer));
  shared_cord = cord;
  // Deny on tree
  buffer = GetAppendBuffer(cord, 6);
  EXPECT_EQ(buffer.length(), 0);
  EXPECT_EQ(cord, "Abcdef");
}
References absl::Cord::Append(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), absl::CordBuffer::length(), and absl::CordBuffer::SetLength().
TEST_P() [7/56]
TEST_P (CordAppendBufferTest , GetAppendBufferOnSubstring)
Definition at line 867 of file cord_test.cc.
{
  // Create a large cord with a single flat and some extra capacity
  absl::Cord cord;
  absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(500);
  buffer.SetLength(450);
  memset(buffer.data(), 'x', 450);
  cord.Append(std::move(buffer));
  cord.RemovePrefix(1);
  // Deny on substring
  buffer = GetAppendBuffer(cord, 6);
  EXPECT_EQ(buffer.length(), 0);
  EXPECT_EQ(cord, std::string(449, 'x'));
}
References absl::Cord::Append(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), absl::CordBuffer::length(), absl::Cord::RemovePrefix(), and absl::CordBuffer::SetLength().
TEST_P() [8/56]
TEST_P (CordAppendBufferTest , GetAppendBufferOnTree)
Definition at line 830 of file cord_test.cc.
{
  RandomEngine rng;
  for (int num_flats : {2, 3, 100}) {
    // Create a cord with `num_flats` flats and extra capacity
    absl::Cord cord;
    std::string prefix;
    std::string last;
    for (int i = 0; i < num_flats - 1; ++i) {
      prefix += last;
      last = RandomLowercaseString(&rng, 10);
      absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(500);
      buffer.SetLength(10);
      memcpy(buffer.data(), last.data(), 10);
      cord.Append(std::move(buffer));
    }
    absl::CordBuffer buffer = GetAppendBuffer(cord, 6);
    EXPECT_GE(buffer.capacity(), 500);
    EXPECT_EQ(buffer.length(), 10);
    EXPECT_EQ(absl::string_view(buffer.data(), buffer.length()), last);
    EXPECT_EQ(cord, prefix);
  }
}
References absl::Cord::Append(), absl::CordBuffer::capacity(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), i, absl::CordBuffer::length(), and absl::CordBuffer::SetLength().
TEST_P() [9/56]
TEST_P (CordAppendBufferTest , GetAppendBufferOnTreeWithoutMinCapacity)
Definition at line 853 of file cord_test.cc.
{
  absl::Cord cord;
  for (int i = 0; i < 2; ++i) {
    absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(500);
    buffer.SetLength(3);
    memcpy(buffer.data(), i ? "def" : "Abc", 3);
    cord.Append(std::move(buffer));
  }
  absl::CordBuffer buffer = GetAppendBuffer(cord, 1000, 900);
  EXPECT_GE(buffer.capacity(), 1000);
  EXPECT_EQ(buffer.length(), 0);
  EXPECT_EQ(cord, "Abcdef");
}
References absl::Cord::Append(), absl::CordBuffer::capacity(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), i, absl::CordBuffer::length(), and absl::CordBuffer::SetLength().
TEST_P() [10/56]
TEST_P (CordTest , AdvanceAndReadOnDataEdge)
Definition at line 2171 of file cord_test.cc.
{
  RandomEngine rng(GTEST_FLAG_GET(random_seed));
  const std::string data = RandomLowercaseString(&rng, 2000);
  for (bool as_flat : {true, false}) {
    SCOPED_TRACE(as_flat ? "Flat" : "External");
    absl::Cord cord =
        as_flat ? absl::Cord(data)
                : absl::MakeCordFromExternal(data, [](absl::string_view) {});
    auto it = cord.Chars().begin();
#if !defined(NDEBUG) || ABSL_OPTION_HARDENED
    EXPECT_DEATH_IF_SUPPORTED(cord.AdvanceAndRead(&it, 2001), ".*");
#endif
    it = cord.Chars().begin();
    absl::Cord frag = cord.AdvanceAndRead(&it, 2000);
    EXPECT_EQ(frag, data);
    EXPECT_TRUE(it == cord.Chars().end());
    it = cord.Chars().begin();
    frag = cord.AdvanceAndRead(&it, 200);
    EXPECT_EQ(frag, data.substr(0, 200));
    EXPECT_FALSE(it == cord.Chars().end());
    frag = cord.AdvanceAndRead(&it, 1500);
    EXPECT_EQ(frag, data.substr(200, 1500));
    EXPECT_FALSE(it == cord.Chars().end());
    frag = cord.AdvanceAndRead(&it, 300);
    EXPECT_EQ(frag, data.substr(1700, 300));
    EXPECT_TRUE(it == cord.Chars().end());
  }
}
References absl::Cord::AdvanceAndRead(), absl::Cord::CharRange::begin(), absl::Cord::Chars(), and absl::MakeCordFromExternal().
TEST_P() [11/56]
TEST_P (CordTest , AdvanceAndReadOnSubstringDataEdge)
Definition at line 2205 of file cord_test.cc.
{
  RandomEngine rng(GTEST_FLAG_GET(random_seed));
  const std::string data = RandomLowercaseString(&rng, 2500);
  for (bool as_flat : {true, false}) {
    SCOPED_TRACE(as_flat ? "Flat" : "External");
    absl::Cord cord =
        as_flat ? absl::Cord(data)
                : absl::MakeCordFromExternal(data, [](absl::string_view) {});
    cord = cord.Subcord(200, 2000);
    const std::string substr = data.substr(200, 2000);
    auto it = cord.Chars().begin();
#if !defined(NDEBUG) || ABSL_OPTION_HARDENED
    EXPECT_DEATH_IF_SUPPORTED(cord.AdvanceAndRead(&it, 2001), ".*");
#endif
    it = cord.Chars().begin();
    absl::Cord frag = cord.AdvanceAndRead(&it, 2000);
    EXPECT_EQ(frag, substr);
    EXPECT_TRUE(it == cord.Chars().end());
    it = cord.Chars().begin();
    frag = cord.AdvanceAndRead(&it, 200);
    EXPECT_EQ(frag, substr.substr(0, 200));
    EXPECT_FALSE(it == cord.Chars().end());
    frag = cord.AdvanceAndRead(&it, 1500);
    EXPECT_EQ(frag, substr.substr(200, 1500));
    EXPECT_FALSE(it == cord.Chars().end());
    frag = cord.AdvanceAndRead(&it, 300);
    EXPECT_EQ(frag, substr.substr(1700, 300));
    EXPECT_TRUE(it == cord.Chars().end());
  }
}
References absl::Cord::AdvanceAndRead(), absl::Cord::CharRange::begin(), absl::Cord::Chars(), absl::MakeCordFromExternal(), and absl::Cord::Subcord().
TEST_P() [12/56]
TEST_P (CordTest , AllFlatSizes)
Definition at line 326 of file cord_test.cc.
{
  using absl::strings_internal::CordTestAccess;
  for (size_t s = 0; s < CordTestAccess::MaxFlatLength(); s++) {
    // Make a string of length s.
    std::string src;
    while (src.size() < s) {
      src.push_back('a' + (src.size() % 26));
    }
    absl::Cord dst(src);
    MaybeHarden(dst);
    EXPECT_EQ(std::string(dst), src) << s;
  }
}
TEST_P() [13/56]
TEST_P (CordTest , AppendAndPrependBufferArePrecise)
Definition at line 638 of file cord_test.cc.
{
  // Create a cord large enough to force 40KB flats.
  std::string test_data(absl::cord_internal::kMaxFlatLength * 10, 'x');
  absl::Cord cord1(test_data);
  absl::Cord cord2(test_data);
  const size_t size1 = cord1.EstimatedMemoryUsage();
  const size_t size2 = cord2.EstimatedMemoryUsage();
  absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(3);
  memcpy(buffer.data(), "Abc", 3);
  buffer.SetLength(3);
  cord1.Append(std::move(buffer));
  buffer = absl::CordBuffer::CreateWithDefaultLimit(3);
  memcpy(buffer.data(), "Abc", 3);
  buffer.SetLength(3);
  cord2.Prepend(std::move(buffer));
#ifndef NDEBUG
  // Allow 32 bytes new CordRepFlat, and 128 bytes for 'glue nodes'
  constexpr size_t kMaxDelta = 128 + 32;
#else
  // Allow 256 bytes extra for 'allocation debug overhead'
  constexpr size_t kMaxDelta = 128 + 32 + 256;
#endif
  EXPECT_LE(cord1.EstimatedMemoryUsage() - size1, kMaxDelta);
  EXPECT_LE(cord2.EstimatedMemoryUsage() - size2, kMaxDelta);
  EXPECT_EQ(cord1, absl::StrCat(test_data, "Abc"));
  EXPECT_EQ(cord2, absl::StrCat("Abc", test_data));
}
References absl::Cord::Append(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), absl::Cord::EstimatedMemoryUsage(), absl::Cord::Prepend(), absl::CordBuffer::SetLength(), and absl::StrCat().
TEST_P() [14/56]
TEST_P (CordTest , AppendEmptyBuffer)
Definition at line 599 of file cord_test.cc.
{
  absl::Cord cord;
  cord.Append(absl::CordBuffer());
  cord.Append(absl::CordBuffer::CreateWithDefaultLimit(2000));
}
References absl::Cord::Append(), and absl::CordBuffer::CreateWithDefaultLimit().
TEST_P() [15/56]
TEST_P (CordTest , AppendEmptyBufferToFlat)
Definition at line 605 of file cord_test.cc.
{
  absl::Cord cord(std::string(2000, 'x'));
  cord.Append(absl::CordBuffer());
  cord.Append(absl::CordBuffer::CreateWithDefaultLimit(2000));
}
References absl::Cord::Append(), and absl::CordBuffer::CreateWithDefaultLimit().
TEST_P() [16/56]
TEST_P (CordTest , AppendEmptyBufferToTree)
Definition at line 611 of file cord_test.cc.
{
  absl::Cord cord(std::string(2000, 'x'));
  cord.Append(std::string(2000, 'y'));
  cord.Append(absl::CordBuffer());
  cord.Append(absl::CordBuffer::CreateWithDefaultLimit(2000));
}
References absl::Cord::Append(), and absl::CordBuffer::CreateWithDefaultLimit().
TEST_P() [17/56]
TEST_P (CordTest , AppendLargeBuffer)
Definition at line 691 of file cord_test.cc.
{
  absl::Cord cord;
  std::string s1(700, '1');
  absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(s1.size());
  memcpy(buffer.data(), s1.data(), s1.size());
  buffer.SetLength(s1.size());
  cord.Append(std::move(buffer));
  EXPECT_EQ(buffer.length(), 0);    // NOLINT
  EXPECT_GT(buffer.capacity(), 0);  // NOLINT
  std::string s2(1000, '2');
  buffer = absl::CordBuffer::CreateWithDefaultLimit(s2.size());
  memcpy(buffer.data(), s2.data(), s2.size());
  buffer.SetLength(s2.size());
  cord.Append(std::move(buffer));
  EXPECT_EQ(buffer.length(), 0);    // NOLINT
  EXPECT_GT(buffer.capacity(), 0);  // NOLINT
  EXPECT_THAT(cord.Chunks(), ::testing::ElementsAre(s1, s2));
}
References absl::Cord::Append(), absl::CordBuffer::capacity(), absl::Cord::Chunks(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), absl::CordBuffer::length(), and absl::CordBuffer::SetLength().
TEST_P() [18/56]
TEST_P (CordTest , AppendSelf)
Definition at line 1990 of file cord_test.cc.
{
  // Test the empty case.
  absl::Cord empty;
  MaybeHarden(empty);
  empty.Append(empty);
  ASSERT_EQ(empty, "");
  // We run the test until data is ~16K
  // This guarantees it covers small, medium and large data.
  std::string control_data = "Abc";
  absl::Cord data(control_data);
  while (control_data.length() < 0x4000) {
    MaybeHarden(data);
    data.Append(data);
    control_data.append(control_data);
    ASSERT_EQ(control_data, data);
  }
}
References absl::Cord::Append(), and data.
TEST_P() [19/56]
TEST_P (CordTest , AppendSmallBuffer)
Definition at line 618 of file cord_test.cc.
{
  absl::Cord cord;
  absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(3);
  ASSERT_THAT(buffer.capacity(), ::testing::Le(15));
  memcpy(buffer.data(), "Abc", 3);
  buffer.SetLength(3);
  cord.Append(std::move(buffer));
  EXPECT_EQ(buffer.length(), 0);    // NOLINT
  EXPECT_GT(buffer.capacity(), 0);  // NOLINT
  buffer = absl::CordBuffer::CreateWithDefaultLimit(3);
  memcpy(buffer.data(), "defgh", 5);
  buffer.SetLength(5);
  cord.Append(std::move(buffer));
  EXPECT_EQ(buffer.length(), 0);    // NOLINT
  EXPECT_GT(buffer.capacity(), 0);  // NOLINT
  EXPECT_THAT(cord.Chunks(), ::testing::ElementsAre("Abcdefgh"));
}
References absl::Cord::Append(), absl::CordBuffer::capacity(), absl::Cord::Chunks(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), absl::CordBuffer::length(), and absl::CordBuffer::SetLength().
TEST_P() [20/56]
TEST_P (CordTest , Assignment)
Definition at line 395 of file cord_test.cc.
{
  absl::Cord x(absl::string_view("hi there"));
  absl::Cord y(x);
  MaybeHarden(y);
  ASSERT_EQ(x.ExpectedChecksum(), absl::nullopt);
  ASSERT_EQ(std::string(x), "hi there");
  ASSERT_EQ(std::string(y), "hi there");
  ASSERT_TRUE(x == y);
  ASSERT_TRUE(x <= y);
  ASSERT_TRUE(y <= x);
  x = absl::string_view("foo");
  ASSERT_EQ(std::string(x), "foo");
  ASSERT_EQ(std::string(y), "hi there");
  ASSERT_TRUE(x < y);
  ASSERT_TRUE(y > x);
  ASSERT_TRUE(x != y);
  ASSERT_TRUE(x <= y);
  ASSERT_TRUE(y >= x);
  x = "foo";
  ASSERT_EQ(x, "foo");
  // Test that going from inline rep to tree we don't leak memory.
  std::vector<std::pair<absl::string_view, absl::string_view>>
      test_string_pairs = {{"hi there", "foo"},
                           {"loooooong coooooord", "short cord"},
                           {"short cord", "loooooong coooooord"},
                           {"loooooong coooooord1", "loooooong coooooord2"}};
  for (std::pair<absl::string_view, absl::string_view> test_strings :
       test_string_pairs) {
    absl::Cord tmp(test_strings.first);
    absl::Cord z(std::move(tmp));
    ASSERT_EQ(std::string(z), test_strings.first);
    tmp = test_strings.second;
    z = std::move(tmp);
    ASSERT_EQ(std::string(z), test_strings.second);
  }
  {
    // Test that self-move assignment doesn't crash/leak.
    // Do not write such code!
    absl::Cord my_small_cord("foo");
    absl::Cord my_big_cord("loooooong coooooord");
    // Bypass clang's warning on self move-assignment.
    absl::Cord* my_small_alias =
        my_unique_true_boolean ? &my_small_cord : &my_big_cord;
    absl::Cord* my_big_alias =
        !my_unique_true_boolean ? &my_small_cord : &my_big_cord;
    *my_small_alias = std::move(my_small_cord);
    *my_big_alias = std::move(my_big_cord);
    // my_small_cord and my_big_cord are in an unspecified but valid
    // state, and will be correctly destroyed here.
  }
}
References my_unique_true_boolean, x, and y.
TEST_P() [21/56]
TEST_P (CordTest , BtreeHostileSplitInsertJoin)
Definition at line 2508 of file cord_test.cc.
{
  absl::BitGen bitgen;
  // Start with about 1GB of data
  std::string data(1 << 10, 'x');
  absl::Cord buffer(data);
  absl::Cord cord;
  for (int i = 0; i < 1000000; ++i) {
    cord.Append(buffer);
  }
  for (int j = 0; j < 1000; ++j) {
    MaybeHarden(cord);
    size_t offset = absl::Uniform(bitgen, 0u, cord.size());
    size_t length = absl::Uniform(bitgen, 100u, data.size());
    if (cord.size() == offset) {
      cord.Append(absl::string_view(data.data(), length));
    } else {
      absl::Cord suffix;
      if (offset + length < cord.size()) {
        suffix = cord;
        suffix.RemovePrefix(offset + length);
      }
      if (cord.size() > offset) {
        cord.RemoveSuffix(cord.size() - offset);
      }
      cord.Append(absl::string_view(data.data(), length));
      if (!suffix.empty()) {
        cord.Append(suffix);
      }
    }
  }
}
References absl::Cord::Append(), data, absl::Cord::empty(), i, absl::Cord::RemovePrefix(), absl::Cord::RemoveSuffix(), absl::Cord::size(), and absl::Uniform().
TEST_P() [22/56]
TEST_P (CordTest , CharIteratorAdvanceAndRead)
Definition at line 2386 of file cord_test.cc.
{
  // Create a Cord holding 6 flats of 2500 bytes each, and then iterate over it
  // reading 150, 1500, 2500 and 3000 bytes. This will result in all possible
  // partial, full and straddled read combinations including reads below
  // kMaxBytesToCopy. b/197776822 surfaced a bug for a specific partial, small
  // read 'at end' on Cord which caused a failure on attempting to read past the
  // end in CordRepBtreeReader which was not covered by any existing test.
  constexpr int kBlocks = 6;
  constexpr size_t kBlockSize = 2500;
  constexpr size_t kChunkSize1 = 1500;
  constexpr size_t kChunkSize2 = 2500;
  constexpr size_t kChunkSize3 = 3000;
  constexpr size_t kChunkSize4 = 150;
  RandomEngine rng;
  std::string data = RandomLowercaseString(&rng, kBlocks * kBlockSize);
  absl::Cord cord;
  for (int i = 0; i < kBlocks; ++i) {
    const std::string block = data.substr(i * kBlockSize, kBlockSize);
    cord.Append(absl::Cord(block));
  }
  MaybeHarden(cord);
  for (size_t chunk_size :
       {kChunkSize1, kChunkSize2, kChunkSize3, kChunkSize4}) {
    absl::Cord::CharIterator it = cord.char_begin();
    size_t offset = 0;
    while (offset < data.length()) {
      const size_t n = std::min<size_t>(data.length() - offset, chunk_size);
      absl::Cord chunk = cord.AdvanceAndRead(&it, n);
      ASSERT_EQ(chunk.size(), n);
      ASSERT_EQ(chunk.Compare(data.substr(offset, n)), 0);
      offset += n;
    }
  }
}
References absl::Cord::AdvanceAndRead(), absl::Cord::Append(), absl::Cord::char_begin(), absl::Cord::Compare(), i, n, and absl::Cord::size().
TEST_P() [23/56]
TEST_P (CordTest , CharIteratorOperations)
Definition at line 2351 of file cord_test.cc.
{
  absl::Cord empty_cord;
  VerifyCharIterator(empty_cord);
  absl::Cord small_buffer_cord("small cord");
  MaybeHarden(small_buffer_cord);
  VerifyCharIterator(small_buffer_cord);
  absl::Cord flat_node_cord("larger than small buffer optimization");
  MaybeHarden(flat_node_cord);
  VerifyCharIterator(flat_node_cord);
  VerifyCharIterator(MaybeHardened(
      absl::MakeFragmentedCord({"a ", "small ", "fragmented ", "cord ", "for ",
                                "testing ", "character ", "iteration."})));
  absl::Cord reused_nodes_cord("ghi");
  reused_nodes_cord.Prepend(absl::Cord("def"));
  reused_nodes_cord.Prepend(absl::Cord("abc"));
  for (int i = 0; i < 4; ++i) {
    reused_nodes_cord.Prepend(reused_nodes_cord);
    MaybeHarden(reused_nodes_cord);
    VerifyCharIterator(reused_nodes_cord);
  }
  RandomEngine rng(GTEST_FLAG_GET(random_seed));
  absl::Cord flat_cord(RandomLowercaseString(&rng, 256));
  absl::Cord subcords;
  for (int i = 0; i < 4; ++i) {
    subcords.Prepend(flat_cord.Subcord(16 * i, 128));
    MaybeHarden(subcords);
  }
  VerifyCharIterator(subcords);
}
References i, absl::MakeFragmentedCord(), absl::Cord::Prepend(), and absl::Cord::Subcord().
TEST_P() [24/56]
TEST_P (CordTest , CharIteratorTraits)
Definition at line 2242 of file cord_test.cc.
{
  static_assert(std::is_copy_constructible<absl::Cord::CharIterator>::value,
                "");
  static_assert(std::is_copy_assignable<absl::Cord::CharIterator>::value, "");
  // Move semantics to satisfy swappable via std::swap
  static_assert(std::is_move_constructible<absl::Cord::CharIterator>::value,
                "");
  static_assert(std::is_move_assignable<absl::Cord::CharIterator>::value, "");
  static_assert(
      std::is_same<
          std::iterator_traits<absl::Cord::CharIterator>::iterator_category,
          std::input_iterator_tag>::value,
      "");
  static_assert(
      std::is_same<std::iterator_traits<absl::Cord::CharIterator>::value_type,
                   char>::value,
      "");
  static_assert(
      std::is_same<
          std::iterator_traits<absl::Cord::CharIterator>::difference_type,
          ptrdiff_t>::value,
      "");
  static_assert(
      std::is_same<std::iterator_traits<absl::Cord::CharIterator>::pointer,
                   const char*>::value,
      "");
  static_assert(
      std::is_same<std::iterator_traits<absl::Cord::CharIterator>::reference,
                   const char&>::value,
      "");
}
References value.
TEST_P() [25/56]
TEST_P (CordTest , ChecksummedEmptyCord)
Definition at line 2967 of file cord_test.cc.
{
  absl::Cord c1;
  EXPECT_FALSE(c1.ExpectedChecksum().has_value());
  // Setting an expected checksum works.
  c1.SetExpectedChecksum(12345);
  EXPECT_EQ(c1.ExpectedChecksum().value_or(0), 12345);
  EXPECT_EQ(c1, "");
  EXPECT_TRUE(c1.empty());
  // Test that setting an expected checksum again doesn't crash or leak memory.
  c1.SetExpectedChecksum(12345);
  EXPECT_EQ(c1.ExpectedChecksum().value_or(0), 12345);
  EXPECT_EQ(c1, "");
  EXPECT_TRUE(c1.empty());
  // CRC persists through copies, assignments, and moves:
  absl::Cord c1_copy_construct = c1;
  EXPECT_EQ(c1_copy_construct.ExpectedChecksum().value_or(0), 12345);
  absl::Cord c1_copy_assign;
  c1_copy_assign = c1;
  EXPECT_EQ(c1_copy_assign.ExpectedChecksum().value_or(0), 12345);
  absl::Cord c1_move(std::move(c1_copy_assign));
  EXPECT_EQ(c1_move.ExpectedChecksum().value_or(0), 12345);
  EXPECT_EQ(c1.ExpectedChecksum().value_or(0), 12345);
  // A CRC Cord compares equal to its non-CRC value.
  EXPECT_EQ(c1, absl::Cord());
  for (const CordMutator& mutator : cord_mutators) {
    SCOPED_TRACE(mutator.Name());
    // Exercise mutating an empty checksummed cord to catch crashes and exercise
    // memory sanitizers.
    absl::Cord c2;
    c2.SetExpectedChecksum(24680);
    mutator.Mutate(c2);
    if (c2.empty()) {
      // Not a mutation
      continue;
    }
    EXPECT_EQ(c2.ExpectedChecksum(), absl::nullopt);
    if (mutator.CanUndo()) {
      mutator.Undo(c2);
    }
  }
  absl::Cord c3;
  c3.SetExpectedChecksum(999);
  const absl::Cord& cc3 = c3;
  // Test that all cord reading operations function in the face of an
  // expected checksum.
  EXPECT_TRUE(cc3.StartsWith(""));
  EXPECT_TRUE(cc3.EndsWith(""));
  EXPECT_TRUE(cc3.empty());
  EXPECT_EQ(cc3, "");
  EXPECT_EQ(cc3, absl::Cord());
  EXPECT_EQ(cc3.size(), 0);
  EXPECT_EQ(cc3.Compare(absl::Cord()), 0);
  EXPECT_EQ(cc3.Compare(c1), 0);
  EXPECT_EQ(cc3.Compare(cc3), 0);
  EXPECT_EQ(cc3.Compare(""), 0);
  EXPECT_EQ(cc3.Compare("wxyz"), -1);
  EXPECT_EQ(cc3.Compare(absl::Cord("wxyz")), -1);
  EXPECT_EQ(absl::Cord("wxyz").Compare(cc3), 1);
  EXPECT_EQ(std::string(cc3), "");
  std::string dest;
  absl::CopyCordToString(cc3, &dest);
  EXPECT_EQ(dest, "");
  for (absl::string_view chunk : cc3.Chunks()) {  // NOLINT(unreachable loop)
    static_cast<void>(chunk);
    GTEST_FAIL() << "no chunks expected";
  }
  EXPECT_TRUE(cc3.chunk_begin() == cc3.chunk_end());
  for (char ch : cc3.Chars()) {  // NOLINT(unreachable loop)
    static_cast<void>(ch);
    GTEST_FAIL() << "no chars expected";
  }
  EXPECT_TRUE(cc3.char_begin() == cc3.char_end());
  EXPECT_EQ(cc3.TryFlat(), "");
  EXPECT_EQ(absl::HashOf(c3), absl::HashOf(absl::Cord()));
  EXPECT_EQ(absl::HashOf(c3), absl::HashOf(absl::string_view()));
}
References absl::Cord::char_begin(), absl::Cord::char_end(), absl::Cord::Chars(), absl::Cord::chunk_begin(), absl::Cord::chunk_end(), absl::Cord::Chunks(), absl::Cord::Compare(), absl::CopyCordToString(), absl::Cord::empty(), absl::Cord::EndsWith(), absl::Cord::ExpectedChecksum(), absl::optional< T >::has_value(), absl::HashOf(), absl::Cord::SetExpectedChecksum(), absl::Cord::size(), absl::Cord::StartsWith(), absl::Cord::TryFlat(), and absl::optional< T >::value_or().
TEST_P() [26/56]
TEST_P (CordTest , Concat_Append)
Definition at line 1907 of file cord_test.cc.
{
  // Create a rep of type CONCAT
  absl::Cord s1("foobarbarbarbarbar");
  MaybeHarden(s1);
  s1.Append("abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg");
  size_t size = s1.size();
  // Create a copy of s1 and append to it.
  absl::Cord s2 = s1;
  MaybeHarden(s2);
  s2.Append("x");
  // 7465150 modifies s1 when it shouldn't.
  EXPECT_EQ(s1.size(), size);
  EXPECT_EQ(s2.size(), size + 1);
}
References absl::Cord::Append(), absl::Cord::size(), and size.
TEST_P() [27/56]
TEST_P (CordTest , ConstinitConstructor)
Definition at line 2637 of file cord_test.cc.
{
  TestConstinitConstructor(
      absl::strings_internal::MakeStringConstant(ShortView{}));
  TestConstinitConstructor(
      absl::strings_internal::MakeStringConstant(LongView{}));
}
References absl::strings_internal::MakeStringConstant(), and TestConstinitConstructor().
TEST_P() [28/56]
TEST_P (CordTest , CopyToString)
Definition at line 591 of file cord_test.cc.
{
  VerifyCopyToString(absl::Cord());  // empty cords cannot carry CRCs
  VerifyCopyToString(MaybeHardened(absl::Cord("small cord")));
  VerifyCopyToString(MaybeHardened(
      absl::MakeFragmentedCord({"fragmented ", "cord ", "to ", "test ",
                                "copying ", "to ", "a ", "string."})));
}
References absl::MakeFragmentedCord().
TEST_P() [29/56]
TEST_P (CordTest , CordChunkIteratorOperations)
Definition at line 2134 of file cord_test.cc.
{
  absl::Cord empty_cord;
  VerifyChunkIterator(empty_cord, 0);
  absl::Cord small_buffer_cord("small cord");
  MaybeHarden(small_buffer_cord);
  VerifyChunkIterator(small_buffer_cord, 1);
  absl::Cord flat_node_cord("larger than small buffer optimization");
  MaybeHarden(flat_node_cord);
  VerifyChunkIterator(flat_node_cord, 1);
  VerifyChunkIterator(MaybeHardened(absl::MakeFragmentedCord(
                          {"a ", "small ", "fragmented ", "cord ", "for ",
                           "testing ", "chunk ", "iterations."})),
                      8);
  absl::Cord reused_nodes_cord(std::string(40, 'c'));
  reused_nodes_cord.Prepend(absl::Cord(std::string(40, 'b')));
  MaybeHarden(reused_nodes_cord);
  reused_nodes_cord.Prepend(absl::Cord(std::string(40, 'a')));
  size_t expected_chunks = 3;
  for (int i = 0; i < 8; ++i) {
    reused_nodes_cord.Prepend(reused_nodes_cord);
    MaybeHarden(reused_nodes_cord);
    expected_chunks *= 2;
    VerifyChunkIterator(reused_nodes_cord, expected_chunks);
  }
  RandomEngine rng(GTEST_FLAG_GET(random_seed));
  absl::Cord flat_cord(RandomLowercaseString(&rng, 256));
  absl::Cord subcords;
  for (int i = 0; i < 128; ++i) subcords.Prepend(flat_cord.Subcord(i, 128));
  VerifyChunkIterator(subcords, 128);
}
References i, absl::MakeFragmentedCord(), absl::Cord::Prepend(), and absl::Cord::Subcord().
TEST_P() [30/56]
TEST_P (CordTest , CordChunkIteratorTraits)
Definition at line 2053 of file cord_test.cc.
{
  static_assert(std::is_copy_constructible<absl::Cord::ChunkIterator>::value,
                "");
  static_assert(std::is_copy_assignable<absl::Cord::ChunkIterator>::value, "");
  // Move semantics to satisfy swappable via std::swap
  static_assert(std::is_move_constructible<absl::Cord::ChunkIterator>::value,
                "");
  static_assert(std::is_move_assignable<absl::Cord::ChunkIterator>::value, "");
  static_assert(
      std::is_same<
          std::iterator_traits<absl::Cord::ChunkIterator>::iterator_category,
          std::input_iterator_tag>::value,
      "");
  static_assert(
      std::is_same<std::iterator_traits<absl::Cord::ChunkIterator>::value_type,
                   absl::string_view>::value,
      "");
  static_assert(
      std::is_same<
          std::iterator_traits<absl::Cord::ChunkIterator>::difference_type,
          ptrdiff_t>::value,
      "");
  static_assert(
      std::is_same<std::iterator_traits<absl::Cord::ChunkIterator>::pointer,
                   const absl::string_view*>::value,
      "");
  static_assert(
      std::is_same<std::iterator_traits<absl::Cord::ChunkIterator>::reference,
                   absl::string_view>::value,
      "");
}
References value.
TEST_P() [31/56]
TEST_P (CordTest , DiabolicalGrowth)
Definition at line 1924 of file cord_test.cc.
{
  // This test exercises a diabolical Append(<one char>) on a cord, making the
  // cord shared before each Append call resulting in a terribly fragmented
  // resulting cord.
  // TODO(b/183983616): Apply some minimum compaction when copying a shared
  // source cord into a mutable copy for updates in CordRepRing.
  RandomEngine rng(GTEST_FLAG_GET(random_seed));
  const std::string expected = RandomLowercaseString(&rng, 5000);
  absl::Cord cord;
  for (char c : expected) {
    absl::Cord shared(cord);
    cord.Append(absl::string_view(&c, 1));
    MaybeHarden(cord);
  }
  std::string value;
  absl::CopyCordToString(cord, &value);
  EXPECT_EQ(value, expected);
  ABSL_RAW_LOG(INFO, "Diabolical size allocated = %zu",
               cord.EstimatedMemoryUsage());
}
References ABSL_RAW_LOG, absl::Cord::Append(), absl::CopyCordToString(), absl::Cord::EstimatedMemoryUsage(), INFO, and value.
TEST_P() [32/56]
TEST_P (CordTest , ExpectedChecksum)
Definition at line 2837 of file cord_test.cc.
{
  for (const PopulatedCordFactory& factory : cord_factories) {
    SCOPED_TRACE(factory.Name());
    for (bool shared : {false, true}) {
      SCOPED_TRACE(shared);
      absl::Cord shared_cord_source = factory.Generate();
      auto make_instance = [=] {
        return shared ? shared_cord_source : factory.Generate();
      };
      const absl::Cord base_value = factory.Generate();
      const std::string base_value_as_string(factory.Generate().Flatten());
      absl::Cord c1 = make_instance();
      EXPECT_FALSE(c1.ExpectedChecksum().has_value());
      // Setting an expected checksum works, and retains the cord's bytes
      c1.SetExpectedChecksum(12345);
      EXPECT_EQ(c1.ExpectedChecksum().value_or(0), 12345);
      EXPECT_EQ(c1, base_value);
      // Test that setting an expected checksum again doesn't crash or leak
      // memory.
      c1.SetExpectedChecksum(12345);
      EXPECT_EQ(c1.ExpectedChecksum().value_or(0), 12345);
      EXPECT_EQ(c1, base_value);
      // CRC persists through copies, assignments, and moves:
      absl::Cord c1_copy_construct = c1;
      EXPECT_EQ(c1_copy_construct.ExpectedChecksum().value_or(0), 12345);
      absl::Cord c1_copy_assign;
      c1_copy_assign = c1;
      EXPECT_EQ(c1_copy_assign.ExpectedChecksum().value_or(0), 12345);
      absl::Cord c1_move(std::move(c1_copy_assign));
      EXPECT_EQ(c1_move.ExpectedChecksum().value_or(0), 12345);
      EXPECT_EQ(c1.ExpectedChecksum().value_or(0), 12345);
      // A CRC Cord compares equal to its non-CRC value.
      EXPECT_EQ(c1, make_instance());
      for (const CordMutator& mutator : cord_mutators) {
        SCOPED_TRACE(mutator.Name());
        // Test that mutating a cord removes its stored checksum
        absl::Cord c2 = make_instance();
        c2.SetExpectedChecksum(24680);
        mutator.Mutate(c2);
        if (c1 == c2) {
          // Not a mutation (for example, appending the empty string).
          // Whether the checksum is removed is not defined.
          continue;
        }
        EXPECT_EQ(c2.ExpectedChecksum(), absl::nullopt);
        if (mutator.CanUndo()) {
          // Undoing an operation should not restore the checksum
          mutator.Undo(c2);
          EXPECT_EQ(c2, base_value);
          EXPECT_EQ(c2.ExpectedChecksum(), absl::nullopt);
        }
      }
      absl::Cord c3 = make_instance();
      c3.SetExpectedChecksum(999);
      const absl::Cord& cc3 = c3;
      // Test that all cord reading operations function in the face of an
      // expected checksum.
      // Test data precondition
      ASSERT_TRUE(cc3.StartsWith("abcde"));
      EXPECT_EQ(cc3.size(), base_value_as_string.size());
      EXPECT_FALSE(cc3.empty());
      EXPECT_EQ(cc3.Compare(base_value), 0);
      EXPECT_EQ(cc3.Compare(base_value_as_string), 0);
      EXPECT_EQ(cc3.Compare("wxyz"), -1);
      EXPECT_EQ(cc3.Compare(absl::Cord("wxyz")), -1);
      EXPECT_EQ(cc3.Compare("aaaa"), 1);
      EXPECT_EQ(cc3.Compare(absl::Cord("aaaa")), 1);
      EXPECT_EQ(absl::Cord("wxyz").Compare(cc3), 1);
      EXPECT_EQ(absl::Cord("aaaa").Compare(cc3), -1);
      EXPECT_TRUE(cc3.StartsWith("abcd"));
      EXPECT_EQ(std::string(cc3), base_value_as_string);
      std::string dest;
      absl::CopyCordToString(cc3, &dest);
      EXPECT_EQ(dest, base_value_as_string);
      bool first_pass = true;
      for (absl::string_view chunk : cc3.Chunks()) {
        if (first_pass) {
          EXPECT_TRUE(absl::StartsWith(chunk, "abcde"));
        }
        first_pass = false;
      }
      first_pass = true;
      for (char ch : cc3.Chars()) {
        if (first_pass) {
          EXPECT_EQ(ch, 'a');
        }
        first_pass = false;
      }
      EXPECT_TRUE(absl::StartsWith(*cc3.chunk_begin(), "abcde"));
      EXPECT_EQ(*cc3.char_begin(), 'a');
      auto char_it = cc3.char_begin();
      absl::Cord::Advance(&char_it, 2);
      EXPECT_EQ(absl::Cord::AdvanceAndRead(&char_it, 2), "cd");
      EXPECT_EQ(*char_it, 'e');
      char_it = cc3.char_begin();
      absl::Cord::Advance(&char_it, 2);
      EXPECT_TRUE(absl::StartsWith(absl::Cord::ChunkRemaining(char_it), "cde"));
      EXPECT_EQ(cc3[0], 'a');
      EXPECT_EQ(cc3[4], 'e');
      EXPECT_EQ(absl::HashOf(cc3), absl::HashOf(base_value));
      EXPECT_EQ(absl::HashOf(cc3), absl::HashOf(base_value_as_string));
    }
  }
}
References absl::Cord::Advance(), absl::Cord::AdvanceAndRead(), absl::Cord::char_begin(), absl::Cord::Chars(), absl::Cord::chunk_begin(), absl::Cord::ChunkRemaining(), absl::Cord::Chunks(), absl::Cord::Compare(), absl::CopyCordToString(), absl::Cord::empty(), absl::Cord::ExpectedChecksum(), absl::optional< T >::has_value(), absl::HashOf(), absl::Cord::SetExpectedChecksum(), absl::Cord::size(), absl::Cord::StartsWith(), absl::StartsWith(), and absl::optional< T >::value_or().
TEST_P() [33/56]
TEST_P (CordTest , Flatten)
Definition at line 1009 of file cord_test.cc.
{
  VerifyFlatten(absl::Cord());
  VerifyFlatten(MaybeHardened(absl::Cord("small cord")));
  VerifyFlatten(
      MaybeHardened(absl::Cord("larger than small buffer optimization")));
  VerifyFlatten(MaybeHardened(
      absl::MakeFragmentedCord({"small ", "fragmented ", "cord"})));
  // Test with a cord that is longer than the largest flat buffer
  RandomEngine rng(GTEST_FLAG_GET(random_seed));
  VerifyFlatten(MaybeHardened(absl::Cord(RandomLowercaseString(&rng, 8192))));
}
References absl::MakeFragmentedCord().
TEST_P() [34/56]
TEST_P (CordTest , ForEachChunk)
Definition at line 2432 of file cord_test.cc.
{
  for (int num_elements : {1, 10, 200}) {
    SCOPED_TRACE(num_elements);
    std::vector<std::string> cord_chunks;
    for (int i = 0; i < num_elements; ++i) {
      cord_chunks.push_back(absl::StrCat("[", i, "]"));
    }
    absl::Cord c = absl::MakeFragmentedCord(cord_chunks);
    MaybeHarden(c);
    std::vector<std::string> iterated_chunks;
    absl::CordTestPeer::ForEachChunk(c,
                                     [&iterated_chunks](absl::string_view sv) {
                                       iterated_chunks.emplace_back(sv);
                                     });
    EXPECT_EQ(iterated_chunks, cord_chunks);
  }
}
References absl::CordTestPeer::ForEachChunk(), i, absl::MakeFragmentedCord(), and absl::StrCat().
TEST_P() [35/56]
TEST_P (CordTest , Format)
Definition at line 2467 of file cord_test.cc.
{
  absl::Cord c;
  absl::Format(&c, "There were %04d little %s.", 3, "pigs");
  EXPECT_EQ(c, "There were 0003 little pigs.");
  MaybeHarden(c);
  absl::Format(&c, "And %-3llx bad wolf!", 1);
  MaybeHarden(c);
  EXPECT_EQ(c, "There were 0003 little pigs.And 1   bad wolf!");
}
References absl::Format().
TEST_P() [36/56]
TEST_P (CordTest , GigabyteCordFromExternal)
Definition at line 345 of file cord_test.cc.
{
  const size_t one_gig = 1024U * 1024U * 1024U;
  size_t max_size = 2 * one_gig;
  if (sizeof(max_size) > 4) max_size = 128 * one_gig;
  size_t length = 128 * 1024;
  char* data = new char[length];
  absl::Cord from = absl::MakeCordFromExternal(
      absl::string_view(data, length),
      [](absl::string_view sv) { delete[] sv.data(); });
  // This loop may seem odd due to its combination of exponential doubling of
  // size and incremental size increases.  We do it incrementally to be sure the
  // Cord will need rebalancing and will exercise code that, in the past, has
  // caused crashes in production.  We grow exponentially so that the code will
  // execute in a reasonable amount of time.
  absl::Cord c;
  c.Append(from);
  while (c.size() < max_size) {
    c.Append(c);
    c.Append(from);
    c.Append(from);
    c.Append(from);
    c.Append(from);
    MaybeHarden(c);
  }
  for (int i = 0; i < 1024; ++i) {
    c.Append(from);
  }
  ABSL_RAW_LOG(INFO, "Made a Cord with %zu bytes!", c.size());
  // Note: on a 32-bit build, this comes out to   2,818,048,000 bytes.
  // Note: on a 64-bit build, this comes out to 171,932,385,280 bytes.
}
References ABSL_RAW_LOG, absl::string_view::data(), from, i, INFO, and absl::MakeCordFromExternal().
TEST_P() [37/56]
TEST_P (CordTest , Hardening)
Definition at line 2477 of file cord_test.cc.
{
  absl::Cord cord("hello");
  MaybeHarden(cord);
  // These statement should abort the program in all builds modes.
  EXPECT_DEATH_IF_SUPPORTED(cord.RemovePrefix(6), "");
  EXPECT_DEATH_IF_SUPPORTED(cord.RemoveSuffix(6), "");
  bool test_hardening = false;
  ABSL_HARDENING_ASSERT([&]() {
    // This only runs when ABSL_HARDENING_ASSERT is active.
    test_hardening = true;
    return true;
  }());
  if (!test_hardening) return;
  EXPECT_DEATH_IF_SUPPORTED(cord[5], "");
  EXPECT_DEATH_IF_SUPPORTED(*cord.chunk_end(), "");
  EXPECT_DEATH_IF_SUPPORTED(static_cast<void>(cord.chunk_end()->empty()), "");
  EXPECT_DEATH_IF_SUPPORTED(++cord.chunk_end(), "");
}
References ABSL_HARDENING_ASSERT, absl::Cord::chunk_end(), absl::string_view::empty(), absl::Cord::RemovePrefix(), and absl::Cord::RemoveSuffix().
TEST_P() [38/56]
TEST_P (CordTest , HugeCord)
Definition at line 1979 of file cord_test.cc.
{
  absl::Cord cord = MakeHuge("huge cord");
  MaybeHarden(cord);
  const size_t acceptable_delta =
      100 + (UseCrc() ? sizeof(absl::cord_internal::CordRepCrc) : 0);
  EXPECT_LE(cord.size(), cord.EstimatedMemoryUsage());
  EXPECT_GE(cord.size() + acceptable_delta, cord.EstimatedMemoryUsage());
}
References absl::Cord::EstimatedMemoryUsage(), and absl::Cord::size().
TEST_P() [39/56]
TEST_P (CordTest , MakeFragmentedCordFromInitializerList)
Definition at line 2009 of file cord_test.cc.
{
  absl::Cord fragmented =
      absl::MakeFragmentedCord({"A ", "fragmented ", "Cord"});
  MaybeHarden(fragmented);
  EXPECT_EQ("A fragmented Cord", fragmented);
  auto chunk_it = fragmented.chunk_begin();
  ASSERT_TRUE(chunk_it != fragmented.chunk_end());
  EXPECT_EQ("A ", *chunk_it);
  ASSERT_TRUE(++chunk_it != fragmented.chunk_end());
  EXPECT_EQ("fragmented ", *chunk_it);
  ASSERT_TRUE(++chunk_it != fragmented.chunk_end());
  EXPECT_EQ("Cord", *chunk_it);
  ASSERT_TRUE(++chunk_it == fragmented.chunk_end());
}
References absl::Cord::chunk_begin(), absl::Cord::chunk_end(), and absl::MakeFragmentedCord().
TEST_P() [40/56]
TEST_P (CordTest , MakeFragmentedCordFromVector)
Definition at line 2031 of file cord_test.cc.
{
  std::vector<absl::string_view> chunks = {"A ", "fragmented ", "Cord"};
  absl::Cord fragmented = absl::MakeFragmentedCord(chunks);
  MaybeHarden(fragmented);
  EXPECT_EQ("A fragmented Cord", fragmented);
  auto chunk_it = fragmented.chunk_begin();
  ASSERT_TRUE(chunk_it != fragmented.chunk_end());
  EXPECT_EQ("A ", *chunk_it);
  ASSERT_TRUE(++chunk_it != fragmented.chunk_end());
  EXPECT_EQ("fragmented ", *chunk_it);
  ASSERT_TRUE(++chunk_it != fragmented.chunk_end());
  EXPECT_EQ("Cord", *chunk_it);
  ASSERT_TRUE(++chunk_it == fragmented.chunk_end());
}
References absl::Cord::chunk_begin(), absl::Cord::chunk_end(), and absl::MakeFragmentedCord().
TEST_P() [41/56]
TEST_P (CordTest , MultipleLengths)
Definition at line 1065 of file cord_test.cc.
{
  TestData d;
  for (size_t i = 0; i < d.size(); i++) {
    std::string a = d.data(i);
    {  // Construct from Cord
      absl::Cord tmp(a);
      absl::Cord x(tmp);
      MaybeHarden(x);
      EXPECT_EQ(a, std::string(x)) << "'" << a << "'";
    }
    {  // Construct from absl::string_view
      absl::Cord x(a);
      MaybeHarden(x);
      EXPECT_EQ(a, std::string(x)) << "'" << a << "'";
    }
    {  // Append cord to self
      absl::Cord self(a);
      MaybeHarden(self);
      self.Append(self);
      EXPECT_EQ(a + a, std::string(self)) << "'" << a << "' + '" << a << "'";
    }
    {  // Prepend cord to self
      absl::Cord self(a);
      MaybeHarden(self);
      self.Prepend(self);
      EXPECT_EQ(a + a, std::string(self)) << "'" << a << "' + '" << a << "'";
    }
    // Try to append/prepend others
    for (size_t j = 0; j < d.size(); j++) {
      std::string b = d.data(j);
      {  // CopyFrom Cord
        absl::Cord x(a);
        absl::Cord y(b);
        MaybeHarden(x);
        x = y;
        EXPECT_EQ(b, std::string(x)) << "'" << a << "' + '" << b << "'";
      }
      {  // CopyFrom absl::string_view
        absl::Cord x(a);
        MaybeHarden(x);
        x = b;
        EXPECT_EQ(b, std::string(x)) << "'" << a << "' + '" << b << "'";
      }
      {  // Cord::Append(Cord)
        absl::Cord x(a);
        absl::Cord y(b);
        MaybeHarden(x);
        x.Append(y);
        EXPECT_EQ(a + b, std::string(x)) << "'" << a << "' + '" << b << "'";
      }
      {  // Cord::Append(absl::string_view)
        absl::Cord x(a);
        MaybeHarden(x);
        x.Append(b);
        EXPECT_EQ(a + b, std::string(x)) << "'" << a << "' + '" << b << "'";
      }
      {  // Cord::Prepend(Cord)
        absl::Cord x(a);
        absl::Cord y(b);
        MaybeHarden(x);
        x.Prepend(y);
        EXPECT_EQ(b + a, std::string(x)) << "'" << b << "' + '" << a << "'";
      }
      {  // Cord::Prepend(absl::string_view)
        absl::Cord x(a);
        MaybeHarden(x);
        x.Prepend(b);
        EXPECT_EQ(b + a, std::string(x)) << "'" << b << "' + '" << a << "'";
      }
    }
  }
}
References a, absl::Cord::Append(), b, i, absl::Cord::Prepend(), x, and y.
TEST_P() [42/56]
TEST_P (CordTest , PrependLargeBuffer)
Definition at line 713 of file cord_test.cc.
{
  absl::Cord cord;
  std::string s1(700, '1');
  absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(s1.size());
  memcpy(buffer.data(), s1.data(), s1.size());
  buffer.SetLength(s1.size());
  cord.Prepend(std::move(buffer));
  EXPECT_EQ(buffer.length(), 0);    // NOLINT
  EXPECT_GT(buffer.capacity(), 0);  // NOLINT
  std::string s2(1000, '2');
  buffer = absl::CordBuffer::CreateWithDefaultLimit(s2.size());
  memcpy(buffer.data(), s2.data(), s2.size());
  buffer.SetLength(s2.size());
  cord.Prepend(std::move(buffer));
  EXPECT_EQ(buffer.length(), 0);    // NOLINT
  EXPECT_GT(buffer.capacity(), 0);  // NOLINT
  EXPECT_THAT(cord.Chunks(), ::testing::ElementsAre(s2, s1));
}
References absl::CordBuffer::capacity(), absl::Cord::Chunks(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), absl::CordBuffer::length(), absl::Cord::Prepend(), and absl::CordBuffer::SetLength().
TEST_P() [43/56]
TEST_P (CordTest , PrependSmallBuffer)
Definition at line 671 of file cord_test.cc.
{
  absl::Cord cord;
  absl::CordBuffer buffer = absl::CordBuffer::CreateWithDefaultLimit(3);
  ASSERT_THAT(buffer.capacity(), ::testing::Le(15));
  memcpy(buffer.data(), "Abc", 3);
  buffer.SetLength(3);
  cord.Prepend(std::move(buffer));
  EXPECT_EQ(buffer.length(), 0);    // NOLINT
  EXPECT_GT(buffer.capacity(), 0);  // NOLINT
  buffer = absl::CordBuffer::CreateWithDefaultLimit(3);
  memcpy(buffer.data(), "defgh", 5);
  buffer.SetLength(5);
  cord.Prepend(std::move(buffer));
  EXPECT_EQ(buffer.length(), 0);    // NOLINT
  EXPECT_GT(buffer.capacity(), 0);  // NOLINT
  EXPECT_THAT(cord.Chunks(), ::testing::ElementsAre("defghAbc"));
}
References absl::CordBuffer::capacity(), absl::Cord::Chunks(), absl::CordBuffer::CreateWithDefaultLimit(), absl::CordBuffer::data(), absl::CordBuffer::length(), absl::Cord::Prepend(), and absl::CordBuffer::SetLength().
TEST_P() [44/56]
TEST_P (CordTest , SmallBufferAssignFromOwnData)
Definition at line 2451 of file cord_test.cc.
{
  constexpr size_t kMaxInline = 15;
  std::string contents = "small buff cord";
  EXPECT_EQ(contents.size(), kMaxInline);
  for (size_t pos = 0; pos < contents.size(); ++pos) {
    for (size_t count = contents.size() - pos; count > 0; --count) {
      absl::Cord c(contents);
      MaybeHarden(c);
      absl::string_view flat = c.Flatten();
      c = flat.substr(pos, count);
      EXPECT_EQ(c, contents.substr(pos, count))
          << "pos = " << pos << "; count = " << count;
    }
  }
}
References absl::string_view::substr().
TEST_P() [45/56]
TEST_P (CordTest , StartsEndsWith)
Definition at line 451 of file cord_test.cc.
{
  absl::Cord x(absl::string_view("abcde"));
  MaybeHarden(x);
  absl::Cord empty("");
  ASSERT_TRUE(x.StartsWith(absl::Cord("abcde")));
  ASSERT_TRUE(x.StartsWith(absl::Cord("abc")));
  ASSERT_TRUE(x.StartsWith(absl::Cord("")));
  ASSERT_TRUE(empty.StartsWith(absl::Cord("")));
  ASSERT_TRUE(x.EndsWith(absl::Cord("abcde")));
  ASSERT_TRUE(x.EndsWith(absl::Cord("cde")));
  ASSERT_TRUE(x.EndsWith(absl::Cord("")));
  ASSERT_TRUE(empty.EndsWith(absl::Cord("")));
  ASSERT_TRUE(!x.StartsWith(absl::Cord("xyz")));
  ASSERT_TRUE(!empty.StartsWith(absl::Cord("xyz")));
  ASSERT_TRUE(!x.EndsWith(absl::Cord("xyz")));
  ASSERT_TRUE(!empty.EndsWith(absl::Cord("xyz")));
  ASSERT_TRUE(x.StartsWith("abcde"));
  ASSERT_TRUE(x.StartsWith("abc"));
  ASSERT_TRUE(x.StartsWith(""));
  ASSERT_TRUE(empty.StartsWith(""));
  ASSERT_TRUE(x.EndsWith("abcde"));
  ASSERT_TRUE(x.EndsWith("cde"));
  ASSERT_TRUE(x.EndsWith(""));
  ASSERT_TRUE(empty.EndsWith(""));
  ASSERT_TRUE(!x.StartsWith("xyz"));
  ASSERT_TRUE(!empty.StartsWith("xyz"));
  ASSERT_TRUE(!x.EndsWith("xyz"));
  ASSERT_TRUE(!empty.EndsWith("xyz"));
}
References absl::Cord::EndsWith(), absl::Cord::StartsWith(), and x.
TEST_P() [46/56]
TEST_P (CordTest , StreamingOutput)
Definition at line 2423 of file cord_test.cc.
{
  absl::Cord c =
      absl::MakeFragmentedCord({"A ", "small ", "fragmented ", "Cord", "."});
  MaybeHarden(c);
  std::stringstream output;
  output << c;
  EXPECT_EQ("A small fragmented Cord.", output.str());
}
References absl::MakeFragmentedCord().
TEST_P() [47/56]
TEST_P (CordTest , Subcord)
Definition at line 485 of file cord_test.cc.
{
  RandomEngine rng(GTEST_FLAG_GET(random_seed));
  const std::string s = RandomLowercaseString(&rng, 1024);
  absl::Cord a;
  AppendWithFragments(s, &rng, &a);
  MaybeHarden(a);
  ASSERT_EQ(s, std::string(a));
  // Check subcords of a, from a variety of interesting points.
  std::set<size_t> positions;
  for (int i = 0; i <= 32; ++i) {
    positions.insert(i);
    positions.insert(i * 32 - 1);
    positions.insert(i * 32);
    positions.insert(i * 32 + 1);
    positions.insert(a.size() - i);
  }
  positions.insert(237);
  positions.insert(732);
  for (size_t pos : positions) {
    if (pos > a.size()) continue;
    for (size_t end_pos : positions) {
      if (end_pos < pos || end_pos > a.size()) continue;
      absl::Cord sa = a.Subcord(pos, end_pos - pos);
      ASSERT_EQ(absl::string_view(s).substr(pos, end_pos - pos),
                std::string(sa))
          << a;
      if (pos != 0 || end_pos != a.size()) {
        ASSERT_EQ(sa.ExpectedChecksum(), absl::nullopt);
      }
    }
  }
  // Do the same thing for an inline cord.
  const std::string sh = "short";
  absl::Cord c(sh);
  for (size_t pos = 0; pos <= sh.size(); ++pos) {
    for (size_t n = 0; n <= sh.size() - pos; ++n) {
      absl::Cord sc = c.Subcord(pos, n);
      ASSERT_EQ(sh.substr(pos, n), std::string(sc)) << c;
    }
  }
  // Check subcords of subcords.
  absl::Cord sa = a.Subcord(0, a.size());
  std::string ss = s.substr(0, s.size());
  while (sa.size() > 1) {
    sa = sa.Subcord(1, sa.size() - 2);
    ss = ss.substr(1, ss.size() - 2);
    ASSERT_EQ(ss, std::string(sa)) << a;
    if (HasFailure()) break;  // halt cascade
  }
  // It is OK to ask for too much.
  sa = a.Subcord(0, a.size() + 1);
  EXPECT_EQ(s, std::string(sa));
  // It is OK to ask for something beyond the end.
  sa = a.Subcord(a.size() + 1, 0);
  EXPECT_TRUE(sa.empty());
  sa = a.Subcord(a.size() + 1, 1);
  EXPECT_TRUE(sa.empty());
}
References a, absl::Cord::empty(), absl::Cord::ExpectedChecksum(), i, n, absl::Cord::size(), and absl::Cord::Subcord().
TEST_P() [48/56]
TEST_P (CordTest , Swap)
Definition at line 550 of file cord_test.cc.
                       {
  absl::string_view a("Dexter");
  absl::string_view b("Mandark");
  absl::Cord x(a);
  absl::Cord y(b);
  MaybeHarden(x);
  swap(x, y);
  if (UseCrc()) {
    ASSERT_EQ(x.ExpectedChecksum(), absl::nullopt);
    ASSERT_EQ(y.ExpectedChecksum(), 1);
  }
  ASSERT_EQ(x, absl::Cord(b));
  ASSERT_EQ(y, absl::Cord(a));
  x.swap(y);
  if (UseCrc()) {
    ASSERT_EQ(x.ExpectedChecksum(), 1);
    ASSERT_EQ(y.ExpectedChecksum(), absl::nullopt);
  }
  ASSERT_EQ(x, absl::Cord(a));
  ASSERT_EQ(y, absl::Cord(b));
}
References a, b, x, and y.
TEST_P() [49/56]
TEST_P (CordTest , TryFlatCommonlyAssumedInvariants)
Definition at line 952 of file cord_test.cc.
{
  // The behavior tested below is not part of the API contract of Cord, but it's
  // something we intend to be true in our current implementation.  This test
  // exists to detect and prevent accidental breakage of the implementation.
  absl::string_view fragments[] = {"A fragmented test",
                                   " cord",
                                   " to test subcords",
                                   " of ",
                                   "a",
                                   " cord for",
                                   " each chunk "
                                   "returned by the ",
                                   "iterator"};
  absl::Cord c = absl::MakeFragmentedCord(fragments);
  MaybeHarden(c);
  int fragment = 0;
  int offset = 0;
  absl::Cord::CharIterator itc = c.char_begin();
  for (absl::string_view sv : c.Chunks()) {
    absl::string_view expected = fragments[fragment];
    absl::Cord subcord1 = c.Subcord(offset, sv.length());
    absl::Cord subcord2 = absl::Cord::AdvanceAndRead(&itc, sv.size());
    EXPECT_EQ(subcord1.TryFlat(), expected);
    EXPECT_EQ(subcord2.TryFlat(), expected);
    ++fragment;
    offset += sv.length();
  }
}
References absl::Cord::AdvanceAndRead(), absl::MakeFragmentedCord(), and absl::Cord::TryFlat().
TEST_P() [50/56]
TEST_P (CordTest , TryFlatConcat)
Definition at line 933 of file cord_test.cc.
{
  absl::Cord c = absl::MakeFragmentedCord({"hel", "lo"});
  MaybeHarden(c);
  EXPECT_EQ(c.TryFlat(), absl::nullopt);
}
References absl::MakeFragmentedCord().
TEST_P() [51/56]
TEST_P (CordTest , TryFlatEmpty)
Definition at line 908 of file cord_test.cc.
{
  absl::Cord c;
  EXPECT_EQ(c.TryFlat(), "");
}
TEST_P() [52/56]
TEST_P (CordTest , TryFlatExternal)
Definition at line 939 of file cord_test.cc.
{
  absl::Cord c = absl::MakeCordFromExternal("hell", [](absl::string_view) {});
  MaybeHarden(c);
  EXPECT_EQ(c.TryFlat(), "hell");
}
References absl::MakeCordFromExternal().
TEST_P() [53/56]
TEST_P (CordTest , TryFlatFlat)
Definition at line 913 of file cord_test.cc.
{
  absl::Cord c("hello");
  MaybeHarden(c);
  EXPECT_EQ(c.TryFlat(), "hello");
}
TEST_P() [54/56]
TEST_P (CordTest , TryFlatSubstrExternal)
Definition at line 945 of file cord_test.cc.
{
  absl::Cord c = absl::MakeCordFromExternal("hell", [](absl::string_view) {});
  absl::Cord sub = absl::CordTestPeer::MakeSubstring(c, 1, c.size() - 1);
  MaybeHarden(sub);
  EXPECT_EQ(sub.TryFlat(), "ell");
}
References absl::MakeCordFromExternal(), and absl::CordTestPeer::MakeSubstring().
TEST_P() [55/56]
TEST_P (CordTest , TryFlatSubstrFlat)
Definition at line 926 of file cord_test.cc.
{
  absl::Cord c("longer than 15 bytes");
  absl::Cord sub = absl::CordTestPeer::MakeSubstring(c, 1, c.size() - 1);
  MaybeHarden(sub);
  EXPECT_EQ(sub.TryFlat(), "onger than 15 bytes");
}
References absl::CordTestPeer::MakeSubstring(), and absl::Cord::TryFlat().
TEST_P() [56/56]
TEST_P (CordTest , TryFlatSubstrInlined)
Definition at line 919 of file cord_test.cc.
{
  absl::Cord c("hello");
  c.RemovePrefix(1);
  MaybeHarden(c);
  EXPECT_EQ(c.TryFlat(), "ello");
}
TestConstinitConstructor()
template<typename Str > void TestConstinitConstructor (Str)
Definition at line 2578 of file cord_test.cc.
{
  const auto expected = Str::value;
  // Defined before `cord` to be destroyed after it.
  static AfterExitCordTester exit_tester;  // NOLINT
  ABSL_CONST_INIT static CordLeaker cord_leaker(Str{});  // NOLINT
  // cord_leaker is static, so this reference will remain valid through the end
  // of program execution.
  static absl::Cord& cord = cord_leaker.cord;
  static bool init_exit_tester = exit_tester.Set(&cord, expected);
  (void)init_exit_tester;
  EXPECT_EQ(cord, expected);
  // Copy the object and test the copy, and the original.
  {
    absl::Cord copy = cord;
    EXPECT_EQ(copy, expected);
  }
  // The original still works
  EXPECT_EQ(cord, expected);
  // Try making adding more structure to the tree.
  {
    absl::Cord copy = cord;
    std::string expected_copy(expected);
    for (int i = 0; i < 10; ++i) {
      copy.Append(cord);
      absl::StrAppend(&expected_copy, expected);
      EXPECT_EQ(copy, expected_copy);
    }
  }
  // Make sure we are using the right branch during constant evaluation.
  EXPECT_EQ(absl::CordTestPeer::IsTree(cord), cord.size() >= 16);
  for (int i = 0; i < 10; ++i) {
    // Make a few more Cords from the same global rep.
    // This tests what happens when the refcount for it gets below 1.
    EXPECT_EQ(expected, absl::Cord(Str{}));
  }
}
References ABSL_CONST_INIT, i, absl::CordTestPeer::IsTree(), AfterExitCordTester::Set(), and absl::StrAppend().
Referenced by TEST_P().
Variable Documentation
my_unique_true_boolean
bool my_unique_true_boolean = true
Definition at line 393 of file cord_test.cc.
Referenced by TEST_P().