open spiel: open_spiel/games/dou_dizhu/dou_dizhu_utils_test.cc File Reference
dou_dizhu_utils_test.cc File Reference
#include "open_spiel/games/dou_dizhu/dou_dizhu_utils.h"
#include <cstring>
#include <iostream>
#include "open_spiel/abseil-cpp/absl/strings/str_format.h"
#include "open_spiel/abseil-cpp/absl/strings/string_view.h"
#include "open_spiel/abseil-cpp/absl/types/optional.h"
#include "open_spiel/spiel.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
namespace open_spiel::dou_dizhu
Functions
void open_spiel::dou_dizhu::SingleRankHandTest ()
void open_spiel::dou_dizhu::ChainOnlyHandTest ()
void open_spiel::dou_dizhu::SingleTrioCombHandTest ()
void open_spiel::dou_dizhu::AirplaneCombHandTest ()
int main ()
Function Documentation
main()
int main ()
Definition at line 168 of file dou_dizhu_utils_test.cc.
           {
  open_spiel::dou_dizhu::SingleRankHandTest();
  open_spiel::dou_dizhu::ChainOnlyHandTest();
  open_spiel::dou_dizhu::SingleTrioCombHandTest();
  open_spiel::dou_dizhu::AirplaneCombHandTest();
}
References open_spiel::dou_dizhu::AirplaneCombHandTest(), open_spiel::dou_dizhu::ChainOnlyHandTest(), open_spiel::dou_dizhu::SingleRankHandTest(), and open_spiel::dou_dizhu::SingleTrioCombHandTest().