open spiel: open_spiel/games/bridge/double_dummy_solver/test/dtest.cpp File Reference
dtest.cpp File Reference
#include <iostream>
#include "../include/dll.h"
#include "testcommon.h"
#include "args.h"
#include "cst.h"
Functions
int main (int argc, char *argv[])
Variables
OptionsType options
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 23 of file dtest.cpp.
{
  ReadArgs(argc, argv);
  if (options.threading != DTEST_THREADING_DEFAULT)
    SetThreading(static_cast<int>(options.threading));
  SetResources(options.memoryMB, options.numThreads);
  DDSInfo info;
  GetDDSInfo(&info);
  cout << info.systemString << endl;
  realMain(argc, argv);
  exit(0);
}
References DTEST_THREADING_DEFAULT, GetDDSInfo(), OptionsType::memoryMB, OptionsType::numThreads, options, ReadArgs(), realMain(), SetResources(), SetThreading(), and OptionsType::threading.
Variable Documentation
options
OptionsType options
Definition at line 20 of file dtest.cpp.
Referenced by main().