open spiel: open_spiel/games/bridge/double_dummy_solver/src/dump.cpp File Reference
dump.cpp File Reference
#include <iostream>
#include <iomanip>
#include <sstream>
#include <fstream>
#include "dump.h"
Functions
string PrintSuit (const unsigned short suitCode)
string PrintSuit (const unsigned short suitCode, const char leastWin)
string PrintDeal (const unsigned short ranks[][DDS_SUITS], const int spacing)
string RankToDiagrams (const unsigned short ranks[DDS_HANDS][DDS_SUITS], const nodeCardsType &node)
string WinnersToText (const unsigned short winRanks[])
string NodeToText (const nodeCardsType &node)
string FullNodeToText (const nodeCardsType &node)
string PosToText (const pos &tpos, const int target, const int depth)
string TopMove (const bool val, const moveType &bestMove)
string DumpTopHeader (const ThreadData &thrd, const int tricks, const int lower, const int upper, const int printMode)
int DumpInput (const int errCode, const deal &dl, const int target, const int solutions, const int mode)
void DumpRetrieved (ofstream &fout, const pos &tpos, const nodeCardsType &node, const int target, const int depth)
void DumpStored (ofstream &fout, const pos &tpos, const Moves &moves, const nodeCardsType &node, const int target, const int depth)
void DumpTopLevel (ofstream &fout, const ThreadData &thrd, const int tricks, const int lower, const int upper, const int printMode)
Function Documentation
DumpInput()
int DumpInput (const int errCode, const deal & dl, const int target, const int solutions, const int mode)
Definition at line 265 of file dump.cpp.
{
  ofstream fout;
  fout.open("dump.txt");
  fout << "Error code=" << errCode << "\n\n";
  fout << "Deal data:\n";
  fout << "trump=";
  if (dl.trump == DDS_NOTRUMP)
    fout << "N\n";
  else
    fout << cardSuit[dl.trump] << "\n";
  fout << "first=" << cardHand[dl.first] << "\n";
  unsigned short ranks[4][4];
  for (int k = 0; k <= 2; k++)
    if (dl.currentTrickRank[k] != 0)
    {
      fout << "index=" << k <<
        " currentTrickSuit=" << cardSuit[dl.currentTrickSuit[k]] <<
        " currentTrickRank= " << cardRank[dl.currentTrickRank[k]] << "\n";
    }
  for (int h = 0; h < DDS_HANDS; h++)
    for (int s = 0; s < DDS_SUITS; s++)
    {
      fout << "index1=" << h << " index2=" << s <<
        " remainCards=" << dl.remainCards[h][s] << "\n";
      ranks[h][s] = static_cast<unsigned short>
                    (dl.remainCards[h][s] >> 2);
    }
  fout << "\ntarget=" << target << "\n";
  fout << "solutions=" << solutions << "\n";
  fout << "mode=" << mode << "\n\n\n";
  fout << PrintDeal(ranks, 8);
  fout.close();
  return 0;
}
References cardHand, cardRank, cardSuit, deal::currentTrickRank, deal::currentTrickSuit, DDS_HANDS, DDS_NOTRUMP, DDS_SUITS, deal::first, PrintDeal(), deal::remainCards, and deal::trump.
Referenced by BoardRangeChecks(), and BoardValueChecks().
DumpRetrieved()
void DumpRetrieved (ofstream & fout, const pos & tpos, const nodeCardsType & node, const int target, const int depth)
Definition at line 314 of file dump.cpp.
{
  fout << "Retrieved entry\n";
  fout << string(15, '-') << "\n";
  fout << PosToText(tpos, target, depth) << "\n";
  fout << FullNodeToText(node) << "\n";
  fout << RankToDiagrams(tpos.rankInSuit, node) << "\n";
}
References FullNodeToText(), PosToText(), pos::rankInSuit, and RankToDiagrams().
Referenced by ABsearch0().
DumpStored()
void DumpStored (ofstream & fout, const pos & tpos, const Moves & moves, const nodeCardsType & node, const int target, const int depth)
Definition at line 329 of file dump.cpp.
{
  fout << "Stored entry\n";
  fout << string(12, '-') << "\n";
  fout << PosToText(tpos, target, depth) << "\n";
  fout << NodeToText(node);
  fout << moves.TrickToText((depth >> 2) + 1) << "\n";
  fout << PrintDeal(tpos.rankInSuit, 16);
}
References NodeToText(), PosToText(), PrintDeal(), pos::rankInSuit, and Moves::TrickToText().
Referenced by ABsearch0().
DumpTopHeader()
string DumpTopHeader (const ThreadData & thrd, const int tricks, const int lower, const int upper, const int printMode)
Definition at line 218 of file dump.cpp.
{
  string stext;
  if (printMode == 0)
  {
    // Trying just one target.
    stext = "Single target " + to_string(tricks) + ", " + "achieved";
  }
  else if (printMode == 1)
  {
    // Looking for best score.
    stext = "Loop target " + to_string(tricks) + ", " +
      "bounds " + to_string(lower) + " .. " + to_string(upper) + ", " +
      TopMove(thrd.val, thrd.bestMove[thrd.iniDepth]) + "";
  }
  else if (printMode == 2)
  {
    // Looking for other moves with best score.
    stext = "Loop for cards with score " + to_string(tricks) + ", " +
      TopMove(thrd.val, thrd.bestMove[thrd.iniDepth]);
  }
  return stext + "\n" + string(stext.size(), '-') + "\n";
}
References ThreadData::bestMove, ThreadData::iniDepth, TopMove(), and ThreadData::val.
Referenced by DumpTopLevel().
DumpTopLevel()
void DumpTopLevel (ofstream & fout, const ThreadData & thrd, const int tricks, const int lower, const int upper, const int printMode)
Definition at line 346 of file dump.cpp.
{
  const pos& tpos = thrd.lookAheadPos;
  fout << DumpTopHeader(thrd, tricks, lower, upper, printMode) << "\n";
  fout << PrintDeal(tpos.rankInSuit, 16);
  fout << WinnersToText(tpos.winRanks[thrd.iniDepth]) << "\n";
  fout << thrd.nodes << " AB nodes, " <<
    thrd.trickNodes << " trick nodes\n\n";
}
References DumpTopHeader(), ThreadData::iniDepth, ThreadData::lookAheadPos, ThreadData::nodes, PrintDeal(), pos::rankInSuit, ThreadData::trickNodes, WinnersToText(), and pos::winRanks.
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().
FullNodeToText()
string FullNodeToText (const nodeCardsType & node)
Definition at line 185 of file dump.cpp.
{
  stringstream ss;
  vector<int> v(DDS_SUITS);
  for (unsigned i = 0; i < DDS_SUITS; i++)
    v[i] = 15 - static_cast<int>(node.leastWin[i]);
  ss << setw(16) << left << "Lowest used" <<
    cardSuit[0] << cardRank[v[0]] << ", " <<
    cardSuit[1] << cardRank[v[1]] << ", " <<
    cardSuit[2] << cardRank[v[2]] << ", " <<
    cardSuit[3] << cardRank[v[3]] << "\n";
  return NodeToText(node) + ss.str();
}
References cardRank, cardSuit, DDS_SUITS, i, nodeCardsType::leastWin, and NodeToText().
Referenced by DumpRetrieved().
NodeToText()
string NodeToText (const nodeCardsType & node)
Definition at line 167 of file dump.cpp.
{
  stringstream ss;
  ss << setw(16) << left << "Address" <<
    static_cast<void const *>(&node) << "\n";
  ss << setw(16) << left << "Bounds" <<
    static_cast<int>(node.lbound) << " to " <<
    static_cast<int>(node.ubound) << " tricks\n";
  ss << setw(16) << left << "Best move" <<
    cardSuit[ static_cast<int>(node.bestMoveSuit) ] <<
    cardRank[ static_cast<int>(node.bestMoveRank) ] << "\n";
  return ss.str();
}
References nodeCardsType::bestMoveRank, nodeCardsType::bestMoveSuit, cardRank, cardSuit, nodeCardsType::lbound, and nodeCardsType::ubound.
Referenced by DumpStored(), and FullNodeToText().
PosToText()
string PosToText (const pos & tpos, const int target, const int depth)
Definition at line 203 of file dump.cpp.
{
  stringstream ss;
  ss << setw(16) << left << "Target" << target << "\n";
  ss << setw(16) << "Depth" << depth << "\n";
  ss << setw(16) << "tricksMAX" << tpos.tricksMAX << "\n";
  ss << setw(16) << "First hand" << cardHand[tpos.first[depth]] << "\n";
  ss << setw(16) << "Next first" << cardHand[tpos.first[depth - 1]] << "\n";
  return ss.str();
}
References cardHand, pos::first, and pos::tricksMAX.
Referenced by DumpRetrieved(), and DumpStored().
PrintDeal()
string PrintDeal (const unsigned short ranks[][DDS_SUITS], const int spacing)
Definition at line 89 of file dump.cpp.
{
  stringstream ss;
  for (int s = 0; s < DDS_SUITS; s++)
  {
    ss << setw(spacing) << "" <<
      cardSuit[s] << " " <<
      PrintSuit(ranks[0][s]) << "\n";
  }
  for (int s = 0; s < DDS_SUITS; s++)
  {
    ss << cardSuit[s] << " " <<
      setw(2*spacing - 2) << left << PrintSuit(ranks[3][s]) <<
      cardSuit[s] << " " <<
      PrintSuit(ranks[1][s]) << "\n";
  }
  for (int s = 0; s < DDS_SUITS; s++)
  {
    ss << setw(spacing) << "" <<
      cardSuit[s] << " " <<
      PrintSuit(ranks[2][s]) << "\n";
  }
  return ss.str() + "\n";
}
References cardSuit, DDS_SUITS, and PrintSuit().
Referenced by DumpInput(), DumpStored(), and DumpTopLevel().
PrintSuit() [1/2]
string PrintSuit (const unsigned short suitCode)
Definition at line 54 of file dump.cpp.
{
  if (! suitCode)
    return "--";
  string st;
  for (int r = 14; r >= 2; r--)
    if ((suitCode & bitMapRank[r]))
      st += static_cast<char>(cardRank[r]);
  return st;
}
References bitMapRank, cardRank, and r.
Referenced by PrintDeal(), RankToDiagrams(), and WinnersToText().
PrintSuit() [2/2]
string PrintSuit (const unsigned short suitCode, const char leastWin)
Definition at line 67 of file dump.cpp.
{
  if (! suitCode)
    return "--";
  string st;
  for (int r = 14; r >= 2; r--)
  {
    if ((suitCode & bitMapRank[r]))
    {
      if (r >= 15 - leastWin)
        st += static_cast<char>(cardRank[r]);
      else
        st += "x";
    }
  }
  return st;
}
References bitMapRank, cardRank, and r.
RankToDiagrams()
string RankToDiagrams (const unsigned short ranks[DDS_HANDS][DDS_SUITS], const nodeCardsType & node)
Definition at line 120 of file dump.cpp.
{
  stringstream ss;
  for (int s = 0; s < DDS_SUITS; s++)
  {
    ss << setw(12) << left <<
      (s == 0 ? "Sought" : "") <<
      cardSuit[s] << " " << setw(20) << PrintSuit(ranks[0][s]) << "|    " <<
      setw(12) << (s == 0 ? "Found" : "") <<
      cardSuit[s] << " " <<
        PrintSuit(ranks[0][s], node.leastWin[s]) << "\n";
  }
  for (int s = 0; s < DDS_SUITS; s++)
  {
    ss <<
      cardSuit[s] << " " << setw(22) << left << PrintSuit(ranks[3][s]) <<
      cardSuit[s] << " " << setw(8) << PrintSuit(ranks[1][s]) << "|    " <<
      cardSuit[s] << " " <<
        setw(22) << PrintSuit(ranks[3][s], node.leastWin[s]) <<
      cardSuit[s] << " " <<
        PrintSuit(ranks[1][s], node.leastWin[s]) << "\n";
  }
  for (int s = 0; s < DDS_SUITS; s++)
  {
    ss << setw(12) << left << "" <<
      cardSuit[s] << " " << setw(20) << PrintSuit(ranks[0][s]) << "|    " <<
      setw(12) << "" << cardSuit[s] << " " <<
      PrintSuit(ranks[0][s], node.leastWin[s]) << "\n";
  }
  return ss.str();
}
References cardSuit, DDS_SUITS, nodeCardsType::leastWin, and PrintSuit().
Referenced by DumpRetrieved().
TopMove()
string TopMove (const bool val, const moveType & bestMove)
Definition at line 248 of file dump.cpp.
{
  if (val)
  {
    stringstream ss;
    ss << "achieved with move " <<
      cardSuit[ bestMove.suit ] <<
      cardRank[ bestMove.rank ];
    return ss.str();
  }
  else
    return "failed";
}
References cardRank, cardSuit, moveType::rank, and moveType::suit.
Referenced by DumpTopHeader().
WinnersToText()
string WinnersToText (const unsigned short winRanks[])
Definition at line 157 of file dump.cpp.
{
  stringstream ss;
  for (int s = 0; s < DDS_SUITS; s++)
    ss << cardSuit[s] << " " << PrintSuit(ourWinRanks[s]) << "\n";
  return ss.str();
}
References cardSuit, DDS_SUITS, and PrintSuit().
Referenced by DumpTopLevel().