open spiel: open_spiel/games/bridge/double_dummy_solver/src/dump.h File Reference
dump.h File Reference
#include "dds.h"
#include "Moves.h"
#include "Memory.h"
Functions
int DumpInput (const int errCode, const deal &dl, const int target, const int solutions, const int mode)
void DumpTopLevel (ofstream &fout, const ThreadData &thrd, const int tricks, const int lower, const int upper, const int printMode)
void DumpRetrieved (ofstream &fout, const pos &tpos, const nodeCardsType &node, const int target, const int depth)
void DumpStored (ofstream &fout, const pos &tpos, const Moves &moves, const nodeCardsType &node, const int target, const int depth)
Function Documentation
DumpInput()
int DumpInput (const int errCode, const deal & dl, const int target, const int solutions, const int mode)
Definition at line 265 of file dump.cpp.
{
  ofstream fout;
  fout.open("dump.txt");
  fout << "Error code=" << errCode << "\n\n";
  fout << "Deal data:\n";
  fout << "trump=";
  if (dl.trump == DDS_NOTRUMP)
    fout << "N\n";
  else
    fout << cardSuit[dl.trump] << "\n";
  fout << "first=" << cardHand[dl.first] << "\n";
  unsigned short ranks[4][4];
  for (int k = 0; k <= 2; k++)
    if (dl.currentTrickRank[k] != 0)
    {
      fout << "index=" << k <<
        " currentTrickSuit=" << cardSuit[dl.currentTrickSuit[k]] <<
        " currentTrickRank= " << cardRank[dl.currentTrickRank[k]] << "\n";
    }
  for (int h = 0; h < DDS_HANDS; h++)
    for (int s = 0; s < DDS_SUITS; s++)
    {
      fout << "index1=" << h << " index2=" << s <<
        " remainCards=" << dl.remainCards[h][s] << "\n";
      ranks[h][s] = static_cast<unsigned short>
                    (dl.remainCards[h][s] >> 2);
    }
  fout << "\ntarget=" << target << "\n";
  fout << "solutions=" << solutions << "\n";
  fout << "mode=" << mode << "\n\n\n";
  fout << PrintDeal(ranks, 8);
  fout.close();
  return 0;
}
References cardHand, cardRank, cardSuit, deal::currentTrickRank, deal::currentTrickSuit, DDS_HANDS, DDS_NOTRUMP, DDS_SUITS, deal::first, PrintDeal(), deal::remainCards, and deal::trump.
Referenced by BoardRangeChecks(), and BoardValueChecks().
DumpRetrieved()
void DumpRetrieved (ofstream & fout, const pos & tpos, const nodeCardsType & node, const int target, const int depth)
Definition at line 314 of file dump.cpp.
{
  fout << "Retrieved entry\n";
  fout << string(15, '-') << "\n";
  fout << PosToText(tpos, target, depth) << "\n";
  fout << FullNodeToText(node) << "\n";
  fout << RankToDiagrams(tpos.rankInSuit, node) << "\n";
}
References FullNodeToText(), PosToText(), pos::rankInSuit, and RankToDiagrams().
Referenced by ABsearch0().
DumpStored()
void DumpStored (ofstream & fout, const pos & tpos, const Moves & moves, const nodeCardsType & node, const int target, const int depth)
Definition at line 329 of file dump.cpp.
{
  fout << "Stored entry\n";
  fout << string(12, '-') << "\n";
  fout << PosToText(tpos, target, depth) << "\n";
  fout << NodeToText(node);
  fout << moves.TrickToText((depth >> 2) + 1) << "\n";
  fout << PrintDeal(tpos.rankInSuit, 16);
}
References NodeToText(), PosToText(), PrintDeal(), pos::rankInSuit, and Moves::TrickToText().
Referenced by ABsearch0().
DumpTopLevel()
void DumpTopLevel (ofstream & fout, const ThreadData & thrd, const int tricks, const int lower, const int upper, const int printMode)
Definition at line 346 of file dump.cpp.
{
  const pos& tpos = thrd.lookAheadPos;
  fout << DumpTopHeader(thrd, tricks, lower, upper, printMode) << "\n";
  fout << PrintDeal(tpos.rankInSuit, 16);
  fout << WinnersToText(tpos.winRanks[thrd.iniDepth]) << "\n";
  fout << thrd.nodes << " AB nodes, " <<
    thrd.trickNodes << " trick nodes\n\n";
}
References DumpTopHeader(), ThreadData::iniDepth, ThreadData::lookAheadPos, ThreadData::nodes, PrintDeal(), pos::rankInSuit, ThreadData::trickNodes, WinnersToText(), and pos::winRanks.
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().