open spiel: open_spiel/games/bridge/double_dummy_solver/examples/Par.cpp File Reference
Par.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/dll.h"
#include "hands.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 21 of file Par.cpp.
{
  ddTableResults DDtable;
  parResults pres;
  int res;
  char line[80];
  bool match;
#if defined(__linux) || defined(__APPLE__)
  SetMaxThreads(0);
#endif
  for (int handno = 0; handno < 3; handno++)
  {
    SetTable(&DDtable, handno);
    res = Par(&DDtable, &pres, vul[handno]);
    if (res != RETURN_NO_FAULT)
    {
      ErrorMessage(res, line);
      printf("DDS error: %s\n", line);
    }
    match = ComparePar(&pres, handno);
    printf("Par, hand %d: %s\n\n",
           handno + 1, (match ? "OK" : "ERROR"));
    PrintTable(&DDtable);
    PrintPar(&pres);
  }
}
References ComparePar(), DDtable, ErrorMessage(), Par(), PrintPar(), PrintTable(), RETURN_NO_FAULT, SetMaxThreads(), SetTable(), and vul.