open spiel: open_spiel/games/bridge/double_dummy_solver/examples/DealerPar.cpp File Reference
DealerPar.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/dll.h"
#include "hands.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 21 of file DealerPar.cpp.
{
  ddTableResults DDtable;
  parResultsDealer pres;
  int res;
  char line[80];
  bool match;
#if defined(__linux) || defined(__APPLE__)
  SetMaxThreads(0);
#endif
  for (int handno = 0; handno < 3; handno++)
  {
    SetTable(&DDtable, handno);
    res = DealerPar(&DDtable, &pres, dealer[handno], vul[handno]);
    if (res != RETURN_NO_FAULT)
    {
      ErrorMessage(res, line);
      printf("DDS error: %s\n", line);
    }
    match = CompareDealerPar(&pres, handno);
    printf("DealerPar, hand %d: %s\n\n",
           handno + 1, (match ? "OK" : "ERROR"));
    PrintTable(&DDtable);
    PrintDealerPar(&pres);
  }
}
References CompareDealerPar(), DDtable, dealer, DealerPar(), ErrorMessage(), PrintDealerPar(), PrintTable(), RETURN_NO_FAULT, SetMaxThreads(), SetTable(), and vul.