open spiel: open_spiel/abseil-cpp/absl/log/flags.cc File Reference
flags.cc File Reference
#include "absl/log/internal/flags.h"
#include <stddef.h>
#include <algorithm>
#include <cstdlib>
#include <string>
#include "absl/base/attributes.h"
#include "absl/base/config.h"
#include "absl/base/log_severity.h"
#include "absl/flags/flag.h"
#include "absl/flags/marshalling.h"
#include "absl/log/globals.h"
#include "absl/log/internal/config.h"
#include "absl/strings/numbers.h"
#include "absl/strings/string_view.h"
Namespaces
namespace absl
namespace absl::log_internal
Functions
ABSL_FLAG (int, stderrthreshold, static_cast< int >(absl::log_internal::StderrThresholdDefault()), "Log messages at or above this threshold level are copied to stderr.") .OnUpdate([]
ABSL_FLAG (int, minloglevel, static_cast< int >(absl::LogSeverityAtLeast::kInfo), "Messages logged at a lower level than this don't actually " "get logged anywhere") .OnUpdate([]
ABSL_FLAG (std::string, log_backtrace_at, "", "Emit a backtrace when logging at file:linenum.") .OnUpdate([]
ABSL_FLAG (bool, log_prefix, true, "Prepend the log prefix to the start of each log line") .OnUpdate([]
Function Documentation
ABSL_FLAG() [1/4]
ABSL_FLAG (bool , log_prefix , true , "Prepend the log prefix to the start of each log line")
Definition at line 108 of file flags.cc.
                 {
      absl::log_internal::RawEnableLogPrefix(absl::GetFlag(FLAGS_log_prefix));
    });
References absl::GetFlag(), and absl::log_internal::RawEnableLogPrefix().
ABSL_FLAG() [2/4]
ABSL_FLAG (int , minloglevel , static_cast< int > absl::LogSeverityAtLeast::kInfo, "Messages logged at a lower level than this don't actually " "get logged anywhere")
Definition at line 79 of file flags.cc.
                 {
      absl::log_internal::RawSetMinLogLevel(
          static_cast<absl::LogSeverityAtLeast>(
              absl::GetFlag(FLAGS_minloglevel)));
    });
References absl::GetFlag(), and absl::log_internal::RawSetMinLogLevel().
ABSL_FLAG() [3/4]
ABSL_FLAG (int , stderrthreshold , static_cast< int > absl::log_internal::StderrThresholdDefault(), "Log messages at or above this threshold level are copied to stderr.")
Definition at line 70 of file flags.cc.
                 {
      absl::log_internal::RawSetStderrThreshold(
          static_cast<absl::LogSeverityAtLeast>(
              absl::GetFlag(FLAGS_stderrthreshold)));
    });
References absl::GetFlag(), and absl::log_internal::RawSetStderrThreshold().
ABSL_FLAG() [4/4]
ABSL_FLAG (std::string , log_backtrace_at , "" , "Emit a backtrace when logging at file:linenum.")
Definition at line 88 of file flags.cc.
                                                :linenum.")
    .OnUpdate([] {
      const std::string log_backtrace_at =
          absl::GetFlag(FLAGS_log_backtrace_at);
      if (log_backtrace_at.empty()) return;
      const size_t last_colon = log_backtrace_at.rfind(':');
      if (last_colon == log_backtrace_at.npos) return;
      const absl::string_view file =
          absl::string_view(log_backtrace_at).substr(0, last_colon);
      int line;
      if (absl::SimpleAtoi(
              absl::string_view(log_backtrace_at).substr(last_colon + 1),
              &line)) {
        absl::SetLogBacktraceLocation(file, line);
      }
    });
References absl::GetFlag(), absl::SetLogBacktraceLocation(), absl::SimpleAtoi(), and absl::string_view::substr().