open spiel: open_spiel/games/bridge/double_dummy_solver/test/parse.h File Reference
parse.h File Reference
#include "../include/dll.h"
Functions
bool read_file (const string &fname, int &number, bool &GIBmode, int **dealer_list, int **vul_list, dealPBN **deal_list, futureTricks **fut_list, ddTableResults **table_list, parResults **par_list, parResultsDealer **dealerpar_list, playTracePBN **play_list, solvedPlay **trace_list)
Function Documentation
read_file()
bool read_file (const string & fname, int & number, bool & GIBmode, int ** dealer_list, int ** vul_list, dealPBN ** deal_list, futureTricks ** fut_list, ddTableResults ** table_list, parResults ** par_list, parResultsDealer ** dealerpar_list, playTracePBN ** play_list, solvedPlay ** trace_list)
Definition at line 98 of file parse.cpp.
{
  ifstream fin;
  fin.open(fname);
  string line;
  if (! getline(fin, line))
  {
    cout << "First line bad: '" << line << "'" << endl;
    return false;
  }
  vector<string> list;
  list.clear();
  splitIntoWords(line, list);
  if (list.size() == 2 && get_head_element(list[0], "NUMBER"))
  {
    // Hopefully a txt-style file.
    if (! str2int(list[1], number))
    {
      cout << "Not a number of hands: '" << list[1] << "'" << endl;
      return false;
    }
    else if (number <= 0 || number > 100000)
    {
      cout << "Suspect number of hands: " << number << endl;
      return false;
    }
  }
  else if (! parseable_GIB(line))
  {
    cout << "Not a GIB-style start: '" << line << "'" << endl;
    return false;
  }
  else
  {
    // Count the lines, then start over.
    GIBmode = 1;
    number = 1;
    while (1)
    {
      if (! getline(fin, line))
        break;
      number++;
    }
    fin.close();
    fin.open(fname);
  }
  // Make enough room for the hands.
  const size_t number_t = static_cast<size_t>(number);
  if ((*dealer_list = static_cast<int *>
      (calloc(number_t, sizeof(int)))) == NULL)
    return false;
  if ((*vul_list = static_cast<int *>
      (calloc(number_t, sizeof(int)))) == NULL)
    return false;
  if ((*deal_list = static_cast<dealPBN *>
      (calloc(number_t, sizeof(dealPBN)))) == NULL)
    return false;
  if ((*fut_list = static_cast<futureTricks *>
      (calloc(number_t, sizeof(futureTricks)))) == NULL)
    return false;
  if ((*table_list = static_cast<ddTableResults *>
      (calloc(number_t, sizeof(ddTableResults)))) == NULL)
    return false;
  if ((*par_list = static_cast<parResults *>
      (calloc(number_t, sizeof(parResults)))) == NULL)
    return false;
  if ((*dealerpar_list = static_cast<parResultsDealer *>
      (calloc(number_t, sizeof(parResultsDealer)))) == NULL)
    return false;
  if ((*play_list = static_cast<playTracePBN *>
      (calloc(number_t, sizeof(playTracePBN)))) == NULL)
    return false;
  if ((*trace_list = static_cast<solvedPlay *>
      (calloc(number_t, sizeof(solvedPlay)))) == NULL)
    return false;
  if (GIBmode)
  {
    for (int n = 0; n < number; n++)
    {
      if (! getline(fin, line))
      {
        cout << "Expected GIB line " << n << endl;
        return false;
      }
      if (! parse_GIB(line, &(*deal_list)[n], &(*table_list)[n]))
        return false;
    }
  }
  else
  {
    for (int n = 0; n < number; n++)
    {
      if (! get_any_line(fin, list, "PBN", n))
        return false;
      if (! parse_PBN(list, (*dealer_list)[n],
          (*vul_list)[n], &(*deal_list)[n]))
        return false;
      if (! get_any_line(fin, list, "FUT", n))
        return false;
      if (! parse_FUT(list, &(*fut_list)[n]))
        return false;
      if (! get_any_line(fin, list, "TABLE", n))
        return false;
      if (! parse_TABLE(list, &(*table_list)[n]))
        return false;
      if (! get_any_line(fin, list, "PAR", n))
        return false;
      if (! parse_PAR(list, &(*par_list)[n]))
        return false;
      if (! get_any_line(fin, list, "DEALERPAR", n))
        return false;
      if (! parse_DEALERPAR(list, &(*dealerpar_list)[n]))
        return false;
      if (! get_any_line(fin, list, "PLAY", n))
        return false;
      if (! parse_PLAY(list, &(*play_list)[n]))
        return false;
      if (! get_any_line(fin, list, "TRACE", n))
        return false;
      if (! parse_TRACE(list, &(*trace_list)[n]))
        return false;
    }
  }
  fin.close();
  return true;
}
References get_any_line(), get_head_element(), n, parse_DEALERPAR(), parse_FUT(), parse_GIB(), parse_PAR(), parse_PBN(), parse_PLAY(), parse_TABLE(), parse_TRACE(), parseable_GIB(), splitIntoWords(), and str2int().
Referenced by realMain().