open spiel: open_spiel/games/universal_poker/logic/gamedef_test.cc File Reference
gamedef_test.cc File Reference
#include "open_spiel/games/universal_poker/logic/gamedef.h"
#include <iostream>
#include <string>
#include "open_spiel/abseil-cpp/absl/strings/match.h"
#include "open_spiel/abseil-cpp/absl/strings/string_view.h"
#include "open_spiel/spiel_utils.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
namespace open_spiel::universal_poker
namespace open_spiel::universal_poker::logic
Functions
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersEasyCase ()
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersNormalizesKeyOnlyLines ()
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersMultiRoundValueEdgeCase ()
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersRemovesUnneededLines ()
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersNormalizesCapitalization ()
int main (int argc, char **argv)
Variables
const char open_spiel::universal_poker::logic::kSimpleHeadsupLimitPokerACPCGamedef []
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 171 of file gamedef_test.cc.
{
  open_spiel::universal_poker::logic::
      TestGamedefToOpenSpielParametersEasyCase();
  open_spiel::universal_poker::logic::
      TestGamedefToOpenSpielParametersNormalizesKeyOnlyLines();
  open_spiel::universal_poker::logic::
      TestGamedefToOpenSpielParametersMultiRoundValueEdgeCase();
  open_spiel::universal_poker::logic::
      TestGamedefToOpenSpielParametersRemovesUnneededLines();
  open_spiel::universal_poker::logic::
      TestGamedefToOpenSpielParametersNormalizesCapitalization();
}
References open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersEasyCase(), open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersMultiRoundValueEdgeCase(), open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersNormalizesCapitalization(), open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersNormalizesKeyOnlyLines(), and open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersRemovesUnneededLines().