open spiel: open_spiel/games/bridge/double_dummy_solver/test/compare.h File Reference
compare.h File Reference
#include "../include/dll.h"
Functions
bool compare_PBN (const dealPBN &dl1, const dealPBN &dl2)
bool compare_FUT (const futureTricks &fut1, const futureTricks &fut2)
bool compare_TABLE (const ddTableResults &table1, const ddTableResults &table2)
bool compare_PAR (const parResults &par1, const parResults &par2)
bool compare_DEALERPAR (const parResultsDealer &par1, const parResultsDealer &par2)
bool compare_TRACE (const solvedPlay &trace1, const solvedPlay &trace2)
Function Documentation
compare_DEALERPAR()
bool compare_DEALERPAR (const parResultsDealer & par1, const parResultsDealer & par2)
Definition at line 89 of file compare.cpp.
{
  if (par1.score != par2.score)
    return false;
  for (int i = 0; i < par1.number; i++)
    if (strcmp(par1.contracts[i], par2.contracts[i]))
      return false;
  return true;
}
References parResultsDealer::contracts, i, parResultsDealer::number, and parResultsDealer::score.
Referenced by loop_dealerpar().
compare_FUT()
bool compare_FUT (const futureTricks & fut1, const futureTricks & fut2)
Definition at line 34 of file compare.cpp.
{
  if (fut1.cards != fut2.cards)
    return false;
  for (int i = 0; i < fut1.cards; i++)
  {
    if (fut1.suit[i] != fut2.suit[i])
      return false;
    if (fut1.rank[i] != fut2.rank[i])
      return false;
    if (fut1.equals[i] != fut2.equals[i])
      return false;
    if (fut1.score[i] != fut2.score[i])
      return false;
  }
  return true;
}
References futureTricks::cards, futureTricks::equals, i, futureTricks::rank, futureTricks::score, and futureTricks::suit.
Referenced by loop_solve().
compare_PAR()
bool compare_PAR (const parResults & par1, const parResults & par2)
Definition at line 72 of file compare.cpp.
{
  if (strcmp(par1.parScore[0], par2.parScore[0]))
    return false;
  if (strcmp(par1.parScore[1], par2.parScore[1]))
    return false;
  if (strcmp(par1.parContractsString[0], par2.parContractsString[0]))
    return false;
  if (strcmp(par1.parContractsString[1], par2.parContractsString[1]))
    return false;
  return true;
}
References parResults::parContractsString, and parResults::parScore.
Referenced by loop_par().
compare_PBN()
bool compare_PBN (const dealPBN & dl1, const dealPBN & dl2)
Definition at line 19 of file compare.cpp.
{
  if (dl1.trump != dl2.trump)
    return false;
  if (dl1.first != dl2.first)
    return false;
  if (strcmp(dl1.remainCards, dl2.remainCards))
    return false;
  return true;
}
References dealPBN::first, dealPBN::remainCards, and dealPBN::trump.
compare_TABLE()
bool compare_TABLE (const ddTableResults & table1, const ddTableResults & table2)
Definition at line 57 of file compare.cpp.
{
  for (int suit = 0; suit < DDS_SUITS; suit++)
  {
    for (int pl = 0; pl < DDS_HANDS; pl++)
      if (table1.resTable[suit][pl] != table2.resTable[suit][pl])
        return false;
  }
  return true;
}
References DDS_HANDS, DDS_SUITS, and ddTableResults::resTable.
Referenced by loop_calc().
compare_TRACE()
bool compare_TRACE (const solvedPlay & trace1, const solvedPlay & trace2)
Definition at line 104 of file compare.cpp.
{
  // In a buglet, Trace returned trace1 == -3 if there is
  // no input at all (trace2 is then 0).
  if (trace1.number != trace2.number && trace2.number > 0)
    return false;
  // Once that was fixed, the input file had length 0, not 1.
  if (trace1.number == 1 && trace2.number == 0)
    return true;
  for (int i = 0; i < trace1.number; i++)
  {
    if (trace1.tricks[i] != trace2.tricks[i])
      return false;
  }
  return true;
}
References i, solvedPlay::number, and solvedPlay::tricks.
Referenced by loop_play().