open spiel: open_spiel/games/bridge/double_dummy_solver/src/Init.h File Reference
Init.h File Reference
#include "dds.h"
#include "Memory.h"
Functions
void SetDeal (ThreadData *thrp)
void SetDealTables (ThreadData *thrp)
void InitWinners (const deal &dl, pos &posPoint, ThreadData const *thrp)
void ResetBestMoves (ThreadData *thrp)
double ThreadMemoryUsed ()
void CloseDebugFiles ()
Function Documentation
CloseDebugFiles()
void CloseDebugFiles ()
Definition at line 399 of file Init.cpp.
{
  for (unsigned thrId = 0; thrId < sysdep.NumThreads(); thrId++)
  {
    ThreadData * thrp = memory.GetPtr(thrId);
    UNUSED(thrp); // To avoid compiler warning
#ifdef DDS_TOP_LEVEL
    thrp->fileTopLevel.Close();
#endif
#ifdef DDS_AB_STATS
    thrp->fileABstats.Close();
#endif
#ifdef DDS_AB_HITS
    thrp->fileRetrieved.Close();
    thrp->fileStored.Close();
#endif
#ifdef DDS_TT_STATS
    thrp->fileTTstats.Close();
#endif
#ifdef DDS_TIMING
    thrp->fileTimerList.Close();
#endif
#ifdef DDS_MOVES
    thrp->fileMoves.Close();
#endif
  }
}
References Memory::GetPtr(), memory, System::NumThreads(), sysdep, and UNUSED.
InitWinners()
void InitWinners (const deal & dl, pos & posPoint, ThreadData const * thrp)
Definition at line 547 of file Init.cpp.
{
  int hand, suit, rank;
  unsigned short int startMovesBitMap[DDS_HANDS][DDS_SUITS];
  for (int h = 0; h < DDS_HANDS; h++)
    for (int s = 0; s < DDS_SUITS; s++)
      startMovesBitMap[h][s] = 0;
  for (int k = 0; k < posPoint.handRelFirst; k++)
  {
    hand = handId(dl.first, k);
    suit = dl.currentTrickSuit[k];
    rank = dl.currentTrickRank[k];
    startMovesBitMap[hand][suit] |= bitMapRank[rank];
  }
  int aggr;
  for (int s = 0; s < DDS_SUITS; s++)
  {
    aggr = 0;
    for (int h = 0; h < DDS_HANDS; h++)
      aggr |= startMovesBitMap[h][s] | thrp->suit[h][s];
    posPoint.winner[s].rank = thrp->rel[aggr].absRank[1][s].rank;
    posPoint.winner[s].hand = thrp->rel[aggr].absRank[1][s].hand;
    posPoint.secondBest[s].rank = thrp->rel[aggr].absRank[2][s].rank;
    posPoint.secondBest[s].hand = thrp->rel[aggr].absRank[2][s].hand;
  }
}
References relRanksType::absRank, bitMapRank, deal::currentTrickRank, deal::currentTrickSuit, DDS_HANDS, DDS_SUITS, deal::first, absRankType::hand, highCardType::hand, handId, pos::handRelFirst, absRankType::rank, highCardType::rank, rank, ThreadData::rel, pos::secondBest, ThreadData::suit, and pos::winner.
Referenced by SolveBoardInternal().
ResetBestMoves()
void ResetBestMoves (ThreadData * thrp)
Definition at line 582 of file Init.cpp.
{
  for (int d = 0; d <= 49; d++)
  {
    thrp->bestMove [d].rank = 0;
    thrp->bestMoveTT[d].rank = 0;
  }
  thrp->memUsed = thrp->transTable->MemoryInUse() +
                  ThreadMemoryUsed();
#ifdef DDS_AB_STATS
  thrp->ABStats.Reset();
#endif
}
References ThreadData::bestMove, ThreadData::bestMoveTT, TransTable::MemoryInUse(), ThreadData::memUsed, moveType::rank, ThreadMemoryUsed(), and ThreadData::transTable.
Referenced by AnalyseLaterBoard(), SolveBoardInternal(), and SolveSameBoard().
SetDeal()
void SetDeal (ThreadData * thrp)
Definition at line 434 of file Init.cpp.
{
  /* Initialization of the rel structure is inspired by
     a solution given by Thomas Andrews */
  for (int s = 0; s < DDS_SUITS; s++)
  {
    thrp->lookAheadPos.aggr[s] = 0;
    for (int h = 0; h < DDS_HANDS; h++)
    {
      thrp->lookAheadPos.rankInSuit[h][s] = thrp->suit[h][s];
      thrp->lookAheadPos.aggr[s] |= thrp->suit[h][s];
    }
  }
  for (int s = 0; s < DDS_SUITS; s++)
  {
    for (int h = 0; h < DDS_HANDS; h++)
      thrp->lookAheadPos.length[h][s] = static_cast<unsigned char>(
        counttable[thrp->lookAheadPos.rankInSuit[h][s]]);
  }
  // Clubs are implicit, for a given trick number.
  for (int h = 0; h < DDS_HANDS; h++)
  {
    thrp->lookAheadPos.handDist[h] =
      static_cast<long long>(
        (thrp->lookAheadPos.length[h][0] << 8) |
        (thrp->lookAheadPos.length[h][1] << 4) |
        (thrp->lookAheadPos.length[h][2] ));
  }
}
References pos::aggr, counttable, DDS_HANDS, DDS_SUITS, pos::handDist, pos::length, ThreadData::lookAheadPos, pos::rankInSuit, and ThreadData::suit.
Referenced by SolveBoardInternal().
SetDealTables()
void SetDealTables (ThreadData * thrp)
Definition at line 469 of file Init.cpp.
{
  unsigned int topBitRank = 1;
  unsigned int topBitNo = 2;
  // Initialization of the rel structure is inspired by
  // a solution given by Thomas Andrews.
  // rel[aggr].absRank[absolute rank][suit].hand is the hand
  // (N = 0, E = 1 etc.) which holds the absolute rank in
  // the suit characterized by aggr.
  // rel[aggr].absRank[absolute rank][suit].rank is the
  // relative rank of that card.
  for (int s = 0; s < DDS_SUITS; s++)
  {
    for (int ord = 1; ord <= 13; ord++)
    {
      thrp->rel[0].absRank[ord][s].hand = -1;
      thrp->rel[0].absRank[ord][s].rank = 0;
    }
  }
  // handLookup[suit][absolute rank] is the hand (N = 0 etc.)
  // holding the absolute rank in suit.
  int handLookup[DDS_SUITS][15];
  for (int s = 0; s < DDS_SUITS; s++)
  {
    for (int r = 14; r >= 2; r--)
    {
      handLookup[s][r] = 0;
      for (int h = 0; h < DDS_HANDS; h++)
      {
        if (thrp->suit[h][s] & bitMapRank[r])
        {
          handLookup[s][r] = h;
          break;
        }
      }
    }
  }
  thrp->transTable->Init(handLookup);
  relRanksType * relp;
  for (unsigned int aggr = 1; aggr < 8192; aggr++)
  {
    if (aggr >= (topBitRank << 1))
    {
      /* Next top bit */
      topBitRank <<= 1;
      topBitNo++;
    }
    thrp->rel[aggr] = thrp->rel[aggr ^ topBitRank];
    relp = &thrp->rel[aggr];
    int weight = counttable[aggr];
    for (int c = weight; c >= 2; c--)
    {
      for (int s = 0; s < DDS_SUITS; s++)
      {
        relp->absRank[c][s].hand = relp->absRank[c - 1][s].hand;
        relp->absRank[c][s].rank = relp->absRank[c - 1][s].rank;
      }
    }
    for (int s = 0; s < DDS_SUITS; s++)
    {
      relp->absRank[1][s].hand =
        static_cast<char>(handLookup[s][topBitNo]);
      relp->absRank[1][s].rank = static_cast<char>(topBitNo);
    }
  }
}
References relRanksType::absRank, bitMapRank, counttable, DDS_HANDS, DDS_SUITS, absRankType::hand, TransTable::Init(), r, absRankType::rank, ThreadData::rel, ThreadData::suit, and ThreadData::transTable.
Referenced by SolveBoardInternal().
ThreadMemoryUsed()
double ThreadMemoryUsed ()
Definition at line 620 of file Init.cpp.
{
  // TODO:  Only needed because SolverIF wants to set it. Avoid?
  double memUsed =
    8192 * sizeof(relRanksType)
    / static_cast<double>(1024.);
  return memUsed;
}
Referenced by AnalyseLaterBoard(), ResetBestMoves(), SolveBoardInternal(), and SolveSameBoard().