open spiel: open_spiel/go/go_open_spiel.cc File Reference
go_open_spiel.cc File Reference
#include "go_open_spiel.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <memory>
#include <string>
#include "open_spiel/abseil-cpp/absl/algorithm/container.h"
#include "open_spiel/spiel.h"
Functions
void Test ()
void * LoadGame (const char *name)
void DeleteGame (void *game_ptr)
char * GameShortName (const void *game_ptr)
char * GameLongName (const void *game_ptr)
void * GameNewInitialState (const void *game_ptr)
int GameNumPlayers (const void *game_ptr)
int GameMaxGameLength (const void *game_ptr)
int GameNumDistinctActions (const void *game_ptr)
void DeleteState (void *state_ptr)
void * StateClone (const void *state_ptr)
char * StateToString (const void *state_ptr)
int StateNumLegalActions (const void *state_ptr)
int StateNumDistinctActions (const void *state_ptr)
void StateFillLegalActions (const void *state_ptr, void *array_ptr)
void StateFillLegalActionsMask (const void *state_ptr, void *array_ptr)
int StateSizeObservation (const void *state_ptr)
void StateFillObservation (const void *state_ptr, void *array_ptr)
int StateSizeChanceOutcomes (const void *state_ptr)
void StateFillChanceOutcomes (const void *state_ptr, void *action_ptr, void *proba_ptr)
void StateFillObservationPlayer (const void *state_ptr, void *array_ptr, int player)
int StateSizeInformationState (const void *state_ptr)
void StateFillInformationState (const void *state_ptr, void *array_ptr)
void StateFillInformationStatePlayer (const void *state_ptr, void *array_ptr, int player)
int StateIsTerminal (const void *state_ptr)
int StateIsChanceNode (const void *state_ptr)
int StateCurrentPlayer (const void *state_ptr)
char * StateActionToString (const void *state_ptr, int player, int action)
void StateApplyAction (void *state_ptr, int action)
double StatePlayerReturn (const void *state_ptr, int player)
Function Documentation
DeleteGame()
void DeleteGame (void * game_ptr)
Definition at line 48 of file go_open_spiel.cc.
{
  GamePointerHolder* game = reinterpret_cast<GamePointerHolder*>(game_ptr);
  delete game;
}
DeleteState()
void DeleteState (void * state_ptr)
Definition at line 93 of file go_open_spiel.cc.
{
  State* state = reinterpret_cast<State*>(state_ptr);
  delete state;
}
References state.
GameLongName()
char * GameLongName (const void * game_ptr)
Definition at line 60 of file go_open_spiel.cc.
{
  std::shared_ptr<const Game> game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr;
  std::string long_name = game->GetType().long_name;
  return strdup(long_name.c_str());
}
References ptr.
GameMaxGameLength()
int GameMaxGameLength (const void * game_ptr)
Definition at line 81 of file go_open_spiel.cc.
{
  std::shared_ptr<const Game> game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr;
  return game->MaxGameLength();
}
References ptr.
GameNewInitialState()
void * GameNewInitialState (const void * game_ptr)
Definition at line 67 of file go_open_spiel.cc.
{
  std::shared_ptr<const Game> game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr;
  std::unique_ptr<State> state = game->NewInitialState();
  void* state_ptr = reinterpret_cast<void*>(state.release());
  return state_ptr;
}
References ptr, and state.
GameNumDistinctActions()
int GameNumDistinctActions (const void * game_ptr)
Definition at line 87 of file go_open_spiel.cc.
{
  std::shared_ptr<const Game> game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr;
  return game->NumDistinctActions();
}
References ptr.
GameNumPlayers()
int GameNumPlayers (const void * game_ptr)
Definition at line 75 of file go_open_spiel.cc.
{
  std::shared_ptr<const Game> game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr;
  return game->NumPlayers();
}
References ptr.
GameShortName()
char * GameShortName (const void * game_ptr)
Definition at line 53 of file go_open_spiel.cc.
{
  std::shared_ptr<const Game> game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr;
  std::string short_name = game->GetType().short_name;
  return strdup(short_name.c_str());
}
References ptr.
LoadGame()
void * LoadGame (const char * name)
Definition at line 43 of file go_open_spiel.cc.
{
  return reinterpret_cast<void*>(
      new GamePointerHolder{open_spiel::LoadGame(name)});
}
References open_spiel::LoadGame(), and name.
Referenced by main().
StateActionToString()
char * StateActionToString (const void * state_ptr, int player, int action)
Definition at line 211 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::string action_str = state->ActionToString(player, action);
  return strdup(action_str.c_str());
}
References action, open_spiel::State::ActionToString(), player, and state.
StateApplyAction()
void StateApplyAction (void * state_ptr, int action)
Definition at line 217 of file go_open_spiel.cc.
{
  State* state = reinterpret_cast<State*>(state_ptr);
  state->ApplyAction(action);
}
References action, open_spiel::State::ApplyAction(), and state.
StateClone()
void * StateClone (const void * state_ptr)
Definition at line 98 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::unique_ptr<State> state_copy = state->Clone();
  return reinterpret_cast<void*>(state_copy.release());
}
References open_spiel::State::Clone(), and state.
StateCurrentPlayer()
int StateCurrentPlayer (const void * state_ptr)
Definition at line 206 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->CurrentPlayer();
}
References open_spiel::State::CurrentPlayer(), and state.
StateFillChanceOutcomes()
void StateFillChanceOutcomes (const void * state_ptr, void * action_ptr, void * proba_ptr)
Definition at line 149 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  int* action_array = reinterpret_cast<int*>(action_ptr);
  double* proba_array = reinterpret_cast<double*>(proba_ptr);
  std::vector<std::pair<open_spiel::Action, double>> outcomes =
      state->ChanceOutcomes();
  std::pair<open_spiel::Action, double> outcome;
  for (int i = 0; i < outcomes.size(); ++i) {
    outcome = outcomes[i];
    action_array[i] = outcome.first;
    proba_array[i] = outcome.second;
  }
}
References open_spiel::State::ChanceOutcomes(), i, and state.
StateFillInformationState()
void StateFillInformationState (const void * state_ptr, void * array_ptr)
Definition at line 179 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  double* information_state_array = reinterpret_cast<double*>(array_ptr);
  std::vector<float> information_state = state->InformationStateTensor();
  for (int i = 0; i < information_state.size(); ++i) {
    information_state_array[i] = information_state[i];
  }
}
References i, open_spiel::State::InformationStateTensor(), and state.
StateFillInformationStatePlayer()
void StateFillInformationStatePlayer (const void * state_ptr, void * array_ptr, int player)
Definition at line 188 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  double* information_state_array = reinterpret_cast<double*>(array_ptr);
  std::vector<float> information_state = state->InformationStateTensor(player);
  absl::c_copy(information_state, information_state_array);
}
References absl::c_copy(), open_spiel::State::InformationStateTensor(), player, and state.
StateFillLegalActions()
void StateFillLegalActions (const void * state_ptr, void * array_ptr)
Definition at line 120 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  int* legal_actions_array = reinterpret_cast<int*>(array_ptr);
  absl::c_copy(state->LegalActions(), legal_actions_array);
}
References absl::c_copy(), and state.
StateFillLegalActionsMask()
void StateFillLegalActionsMask (const void * state_ptr, void * array_ptr)
Definition at line 126 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  int* legal_actions_mask_array = reinterpret_cast<int*>(array_ptr);
  std::vector<int> legal_actions_mask = state->LegalActionsMask();
  absl::c_copy(state->LegalActionsMask(), legal_actions_mask_array);
}
References absl::c_copy(), open_spiel::State::LegalActionsMask(), and state.
StateFillObservation()
void StateFillObservation (const void * state_ptr, void * array_ptr)
Definition at line 138 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  double* observation_array = reinterpret_cast<double*>(array_ptr);
  absl::c_copy(state->ObservationTensor(), observation_array);
}
References absl::c_copy(), and state.
StateFillObservationPlayer()
void StateFillObservationPlayer (const void * state_ptr, void * array_ptr, int player)
Definition at line 164 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  double* observation_array = reinterpret_cast<double*>(array_ptr);
  std::vector<float> observation = state->ObservationTensor(player);
  for (int i = 0; i < observation.size(); ++i) {
    observation_array[i] = observation[i];
  }
}
References i, open_spiel::State::ObservationTensor(), player, and state.
StateIsChanceNode()
int StateIsChanceNode (const void * state_ptr)
Definition at line 201 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->IsChanceNode() ? 1 : 0;
}
References open_spiel::State::IsChanceNode(), and state.
StateIsTerminal()
int StateIsTerminal (const void * state_ptr)
Definition at line 196 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->IsTerminal() ? 1 : 0;
}
References open_spiel::State::IsTerminal(), and state.
StateNumDistinctActions()
int StateNumDistinctActions (const void * state_ptr)
Definition at line 115 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->NumDistinctActions();
}
References open_spiel::State::NumDistinctActions(), and state.
StateNumLegalActions()
int StateNumLegalActions (const void * state_ptr)
Definition at line 110 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->LegalActions().size();
}
References open_spiel::State::LegalActions(), and state.
StatePlayerReturn()
double StatePlayerReturn (const void * state_ptr, int player)
Definition at line 222 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->PlayerReturn(player);
}
References player, open_spiel::State::PlayerReturn(), and state.
StateSizeChanceOutcomes()
int StateSizeChanceOutcomes (const void * state_ptr)
Definition at line 144 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->ChanceOutcomes().size();
}
References open_spiel::State::ChanceOutcomes(), and state.
StateSizeInformationState()
int StateSizeInformationState (const void * state_ptr)
Definition at line 174 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->GetGame()->InformationStateTensorSize();
}
References open_spiel::State::GetGame(), and state.
StateSizeObservation()
int StateSizeObservation (const void * state_ptr)
Definition at line 133 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->GetGame()->ObservationTensorSize();
}
References open_spiel::State::GetGame(), and state.
StateToString()
char * StateToString (const void * state_ptr)
Definition at line 104 of file go_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::string state_str = state->ToString();
  return strdup(state_str.c_str());
}
References state, and open_spiel::State::ToString().
Referenced by open_spiel::connect_four::ConnectFourState::ActionToString(), open_spiel::crowd_modelling::CrowdModellingState::DistributionSupport(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::DistributionSupport(), open_spiel::garnet::GarnetState::DistributionSupport(), open_spiel::garnet::GarnetState::InformationStateString(), open_spiel::catch_::CatchState::ToString(), open_spiel::checkers::CheckersState::ToString(), open_spiel::clobber::ClobberState::ToString(), open_spiel::connect_four::ConnectFourState::ToString(), open_spiel::crowd_modelling::CrowdModellingState::ToString(), open_spiel::crowd_modelling_2d::CrowdModelling2dState::ToString(), open_spiel::garnet::GarnetState::ToString(), open_spiel::othello::OthelloState::ToString(), open_spiel::dark_hex::DarkHexState::ViewToString(), and open_spiel::phantom_ttt::PhantomTTTState::ViewToString().
Test()
void Test ()
Definition at line 40 of file go_open_spiel.cc.
{ std::cout << "Testing, testing, 1 2 3!" << std::endl; }