open spiel: open_spiel/abseil-cpp/absl/container/internal/hash_policy_traits_test.cc File Reference
hash_policy_traits_test.cc File Reference
#include "absl/container/internal/hash_policy_traits.h"
#include <functional>
#include <memory>
#include <new>
#include "gmock/gmock.h"
#include "gtest/gtest.h"
Namespaces
namespace absl
namespace absl::container_internal
Variable Documentation
a
int a = 53
Definition at line 61 of file hash_policy_traits_test.cc.
alloc
std::allocator<int> alloc
Definition at line 60 of file hash_policy_traits_test.cc.
apply
MockFunction<int(int)> apply
Definition at line 62 of file hash_policy_traits_test.cc.
Referenced by open_spiel.python.mfg.algorithms.munchausen_deep_mirror_descent.MunchausenDQN::_get_action_probs(), open_spiel.python.jax.deep_cfr.DeepCFRSolver::_get_jitted_matched_regrets(), open_spiel.python.jax.dqn.DQN::_loss(), open_spiel.python.mfg.algorithms.munchausen_deep_mirror_descent.MunchausenDQN::_loss(), open_spiel.python.jax.deep_cfr.DeepCFRSolver::_loss_adv(), open_spiel.python.jax.nfsp.NFSP::_loss_avg(), open_spiel.python.mfg.algorithms.average_network_fictitious_play.AveragePolicy::_loss_avg(), open_spiel.python.jax.deep_cfr.DeepCFRSolver::_loss_policy(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver::_network_jit_apply(), open_spiel.python.algorithms.rnad.rnad.RNaDSolver::_network_jit_apply_and_post_process(), open_spiel.python.jax.opponent_shaping.OpponentShapingAgent::_store_time_step(), open_spiel.python.jax.deep_cfr.DeepCFRSolver::action_probabilities(), define_julia_module(), open_spiel.python.jax.opponent_shaping.OpponentShapingAgent::get_policy(), and open_spiel.python.jax.opponent_shaping.OpponentShapingAgent::get_value_fn().