open spiel: open_spiel/games/bridge/double_dummy_solver/test/itest.cpp File Reference
itest.cpp File Reference
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include "../include/dll.h"
#include "testcommon.h"
#include "args.h"
#include "cst.h"
Functions
int main (int argc, char *argv[])
Variables
OptionsType options
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 25 of file itest.cpp.
{
  ReadArgs(argc, argv);
  if (options.threading != DTEST_THREADING_DEFAULT)
    SetThreading(static_cast<int>(options.threading));
  SetResources(options.memoryMB, options.numThreads);
  DDSInfo info;
  GetDDSInfo(&info);
  cout << info.systemString << endl;
  realMain(argc, argv);
#ifdef DDS_SCHEDULER
  scheduler.PrintTiming();
#endif
  FreeMemory();
  exit(0);
}
References DTEST_THREADING_DEFAULT, FreeMemory(), GetDDSInfo(), OptionsType::memoryMB, OptionsType::numThreads, options, ReadArgs(), realMain(), scheduler, SetResources(), SetThreading(), and OptionsType::threading.
Variable Documentation
options
OptionsType options
Definition at line 22 of file itest.cpp.
Referenced by absl::c_find_first_of(), absl::c_find_first_of(), absl::InstallFailureSignalHandler(), main(), open_spiel::uci::MakeUCIBot(), PrintOptions(), ReadArgs(), realMain(), SetDefaults(), and open_spiel::uci::UCIBot::UCIBot().