open spiel: open_spiel/games/kuhn_poker/kuhn_poker_test.cc File Reference
kuhn_poker_test.cc File Reference
#include "open_spiel/games/kuhn_poker/kuhn_poker.h"
#include "open_spiel/algorithms/get_all_states.h"
#include "open_spiel/policy.h"
#include "open_spiel/spiel_utils.h"
#include "open_spiel/tests/basic_tests.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
namespace open_spiel::kuhn_poker
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 70 of file kuhn_poker_test.cc.
{
  open_spiel::kuhn_poker::BasicKuhnTests();
  open_spiel::kuhn_poker::CountStates();
  open_spiel::kuhn_poker::PolicyTest();
  open_spiel::testing::CheckChanceOutcomes(*open_spiel::LoadGame(
      "kuhn_poker", {{"players", open_spiel::GameParameter(3)}}));
  open_spiel::testing::RandomSimTest(*open_spiel::LoadGame("kuhn_poker"),
                                     /*num_sims=*/10);
  open_spiel::testing::ResampleInfostateTest(
      *open_spiel::LoadGame("kuhn_poker"),
      /*num_sims=*/10);
}
References open_spiel::testing::CheckChanceOutcomes(), open_spiel::LoadGame(), open_spiel::testing::RandomSimTest(), and open_spiel::testing::ResampleInfostateTest().