open spiel: absl::variant_internal Namespace Reference
absl::variant_internal Namespace Reference
Classes
struct AccessedType
struct AccessedType< SimpleArray< T, Size > >
struct AppendToIndexSequence
struct AppendToIndexSequence< index_sequence< Is... >, J >
struct ConversionVisitor
struct FlattenIndices
struct FlattenIndices< HeadSize, TailSize... >
struct FlattenIndices<>
struct GiveQualsTo
struct GiveQualsTo< const T &&, U >
struct GiveQualsTo< const T &, U >
struct GiveQualsTo< T &&, U >
struct GiveQualsTo< T &, U >
struct GiveQualsTo< volatile const T &&, U >
struct GiveQualsTo< volatile const T &, U >
struct GiveQualsTo< volatile T &&, U >
struct GiveQualsTo< volatile T &, U >
struct ImaginaryFun
struct ImaginaryFun< variant< H, T... >, I >
struct ImaginaryFun< variant<>, I >
struct IndexOfConstructedType
struct IndexOfConstructedType< Variant, T, void_t< decltype(ImaginaryFun< Variant >::Run(std::declval< T >(), {}))> >
struct IndexOfImpl
struct IndexOfImpl< Expected >
struct IndexOfImpl< Expected, Expected, Tail... >
struct IndexOfImpl< Expected, Head, Tail... >
struct IndexOfMeta
struct IsNeitherSelfNorInPlace
struct IsNeitherSelfNorInPlace< Self, in_place_index_t< I > >
struct IsNeitherSelfNorInPlace< Self, in_place_type_t< T > >
struct IsNeitherSelfNorInPlace< Self, Self >
struct MakeVisitationMatrix
struct MakeVisitationMatrix< ReturnType, FunctionObject, index_sequence< HeadEndIndex, TailEndIndices... >, index_sequence< BoundIndices... > >
struct MakeVisitationMatrix< ReturnType, FunctionObject, index_sequence<>, index_sequence< BoundIndices... > >
struct MakeVisitationMatrixImpl
struct MakeVisitationMatrixImpl< ReturnType, FunctionObject, EndIndices, index_sequence< CurrIndices... >, BoundIndices >
struct NoMatch
struct NumCasesOfSwitch
struct NumCasesOfSwitch< HeadNumAlternatives, TailNumAlternatives... >
struct NumCasesOfSwitch<>
struct PickCaseImpl
struct PickCaseImpl< true >
struct ReachableSwitchCase
struct SimpleArray
struct UnambiguousIndexOf
struct UnambiguousIndexOf< variant< Alts... >, T >
struct UnambiguousIndexOfImpl
struct UnambiguousIndexOfImpl< variant< Head, Tail... >, Head, CurrIndex >
struct UnambiguousIndexOfImpl< variant< Head, Tail... >, T, CurrIndex >
struct UnambiguousIndexOfImpl< variant<>, T, CurrIndex >
struct UnflattenIndex
struct UnflattenIndex< I, 0, HeadSize, TailSize... >
struct UnreachableSwitchCase
struct VariantAccessResultImpl
struct VariantAccessResultImpl< I, const Variantemplate< T... > & >
struct VariantAccessResultImpl< I, const Variantemplate< T... > && >
struct VariantAccessResultImpl< I, Variantemplate< T... > & >
struct VariantAccessResultImpl< I, Variantemplate< T... > && >
struct VariantAlternativeSfinae
struct VariantAlternativeSfinae< 0, variant< T0, Ts... > >
struct VariantAlternativeSfinae< I, variant< T0, Tn... > >
struct VariantCoreAccess
class VariantStateBase
struct VisitIndices
struct VisitIndices< EndIndex >
struct VisitIndicesFallback
struct VisitIndicesResultImpl
struct VisitIndicesSwitch
struct VisitIndicesVariadic
struct VisitIndicesVariadicImpl
struct VisitIndicesVariadicImpl< absl::index_sequence< N... >, EndIndices... >
Typedefs
template<std::size_t I, class T >
using VariantAlternativeSfinaeT = typename VariantAlternativeSfinae<I, T>::type
template<class T , class U >
using GiveQualsToT = typename GiveQualsTo<T, U>::type
template<std::size_t I>
using SizeT = std::integral_constant<std::size_t, I>
using NPos = SizeT<variant_npos>
template<std::size_t I, class Variant >
using VariantAccessResult
template<class T >
using AccessedTypeT = typename AccessedType<T>::type
template<class T >
using AlwaysZero = SizeT<0>
template<class Op , class... Vs>
using VisitIndicesResultT = typename VisitIndicesResultImpl<Op, Vs...>::type
template<typename Is , std::size_t J>
using AppendToIndexSequenceT = typename AppendToIndexSequence<Is, J>::type
template<class Op , std::size_t I, std::size_t EndIndex>
using PickCase = typename PickCaseImpl<(I < EndIndex)>::template Apply<Op, I>
template<class Expected , class... Types>
using IndexOf = typename IndexOfMeta<Expected, Types...>::type
template<class T , std::size_t >
using UnambiguousTypeOfImpl = T
template<class Variant , class T >
using UnambiguousTypeOfT
Functions
void ThrowBadVariantAccess ()
void Rethrow ()
template<class T >
constexpr T AccessSimpleArray (const T &value)
template<class T , std::size_t Size, class... SizeT>
constexpr AccessedTypeT< T > AccessSimpleArray (const SimpleArray< T, Size > &table, std::size_t head_index, SizeT... tail_indices)
template<class ReturnType , class FunctionObject , std::size_t... Indices>
constexpr ReturnType call_with_indices (FunctionObject &&function)
ABSL_INTERNAL_INLINE_CONSTEXPR (std::size_t, MaxUnrolledVisitCases, 33)
template<class ReturnType >
ReturnType TypedThrowBadVariantAccess ()
template<class Self , std::size_t I>
VariantAccessResult< I, Self > AccessUnion (Self &&self, SizeT< I >)
template<class T >
void DeducedDestroy (T &self)
Typedef Documentation
AccessedTypeT
template<class T > using absl::variant_internal::AccessedTypeT = typename AccessedType<T>::type
Definition at line 176 of file variant.h.
AlwaysZero
template<class T > using absl::variant_internal::AlwaysZero = SizeT<0>
Definition at line 197 of file variant.h.
AppendToIndexSequenceT
template<typename Is , std::size_t J> using absl::variant_internal::AppendToIndexSequenceT = typename AppendToIndexSequence<Is, J>::type
Definition at line 234 of file variant.h.
GiveQualsToT
template<class T , class U > using absl::variant_internal::GiveQualsToT = typename GiveQualsTo<T, U>::type
Definition at line 123 of file variant.h.
IndexOf
template<class Expected , class... Types> using absl::variant_internal::IndexOf = typename IndexOfMeta<Expected, Types...>::type
Definition at line 788 of file variant.h.
NPos
using absl::variant_internal::NPos = SizeT<variant_npos>
Definition at line 129 of file variant.h.
PickCase
template<class Op , std::size_t I, std::size_t EndIndex> using absl::variant_internal::PickCase = typename PickCaseImpl<(I < EndIndex)>::template Apply<Op, I>
Definition at line 325 of file variant.h.
SizeT
template<std::size_t I> using absl::variant_internal::SizeT = std::integral_constant<std::size_t, I>
Definition at line 127 of file variant.h.
UnambiguousTypeOfImpl
template<class T , std::size_t > using absl::variant_internal::UnambiguousTypeOfImpl = T
Definition at line 825 of file variant.h.
UnambiguousTypeOfT
template<class Variant , class T > using absl::variant_internal::UnambiguousTypeOfT
Initial value:
    UnambiguousTypeOfImpl<T, UnambiguousIndexOf<Variant, T>::value>
Definition at line 828 of file variant.h.
VariantAccessResult
template<std::size_t I, class Variant > using absl::variant_internal::VariantAccessResult
Initial value:
    typename VariantAccessResultImpl<I, Variant&&>::type
Definition at line 160 of file variant.h.
VariantAlternativeSfinaeT
template<std::size_t I, class T > using absl::variant_internal::VariantAlternativeSfinaeT = typename VariantAlternativeSfinae<I, T>::type
Definition at line 76 of file variant.h.
VisitIndicesResultT
template<class Op , class... Vs> using absl::variant_internal::VisitIndicesResultT = typename VisitIndicesResultImpl<Op, Vs...>::type
Definition at line 205 of file variant.h.
Function Documentation
ABSL_INTERNAL_INLINE_CONSTEXPR()
absl::variant_internal::ABSL_INTERNAL_INLINE_CONSTEXPR (std::size_t , MaxUnrolledVisitCases , 33)
AccessSimpleArray() [1/2]
template<class T , std::size_t Size, class... SizeT> AccessedTypeT< T > absl::variant_internal::AccessSimpleArray (const SimpleArray< T, Size > & table, std::size_t head_index, SizeT... tail_indices) constexpr
Definition at line 189 of file variant.h.
{
  return AccessSimpleArray(table.value[head_index], tail_indices...);
}
References AccessSimpleArray(), and absl::variant_internal::SimpleArray< T, Size >::value.
AccessSimpleArray() [2/2]
template<class T > T absl::variant_internal::AccessSimpleArray (const T & value) constexpr
Definition at line 184 of file variant.h.
{
  return value;
}
References value.
Referenced by AccessSimpleArray(), and absl::variant_internal::VisitIndicesFallback< EndIndices >::Run().
AccessUnion()
template<class Self , std::size_t I> VariantAccessResult< I, Self > absl::variant_internal::AccessUnion (Self && self, SizeT< I >) inline
Definition at line 548 of file variant.h.
{
  return reinterpret_cast<VariantAccessResult<I, Self>>(self);
}
call_with_indices()
template<class ReturnType , class FunctionObject , std::size_t... Indices> ReturnType absl::variant_internal::call_with_indices (FunctionObject && function) constexpr
Definition at line 212 of file variant.h.
{
  static_assert(
      std::is_same<ReturnType, decltype(std::declval<FunctionObject>()(
                                   SizeT<Indices>()...))>::value,
      "Not all visitation overloads have the same return type.");
  return absl::forward<FunctionObject>(function)(SizeT<Indices>()...);
}
References absl::forward().
Referenced by absl::variant_internal::MakeVisitationMatrix< ReturnType, FunctionObject, index_sequence<>, index_sequence< BoundIndices... > >::Run().
DeducedDestroy()
template<class T > void absl::variant_internal::DeducedDestroy (T & self)
Definition at line 557 of file variant.h.
                             {  // NOLINT
  self.~T();
}
Rethrow()
ABSL_DLL void absl::variant_internal::Rethrow ()
Definition at line 49 of file bad_variant_access.cc.
               {
#ifdef ABSL_HAVE_EXCEPTIONS
  throw;
#else
  ABSL_RAW_LOG(FATAL,
               "Internal error in absl::variant implementation. Attempted to "
               "rethrow an exception when building with exceptions disabled.");
  abort();  // TODO(calabrese) Remove once RAW_LOG FATAL is noreturn.
#endif
}
References ABSL_RAW_LOG.
ThrowBadVariantAccess()
ABSL_DLL void absl::variant_internal::ThrowBadVariantAccess ()
Definition at line 40 of file bad_variant_access.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  throw bad_variant_access();
#else
  ABSL_RAW_LOG(FATAL, "Bad variant access");
  abort();  // TODO(calabrese) Remove once RAW_LOG FATAL is noreturn.
#endif
}
References ABSL_RAW_LOG.
Referenced by TypedThrowBadVariantAccess().
TypedThrowBadVariantAccess()
template<class ReturnType > ReturnType absl::variant_internal::TypedThrowBadVariantAccess ()
Definition at line 328 of file variant.h.
{
  absl::variant_internal::ThrowBadVariantAccess();
}
References ThrowBadVariantAccess().