open spiel: absl::debugging_internal Namespace Reference
absl::debugging_internal Namespace Reference
Classes
struct AbbrevPair
struct ParseState
struct State
Typedefs
typedef bool(* ParseFunc) (State *)
typedef void OutputWriter(const char *, void *)
typedef void(* SymbolizeUrlEmitter) (void *const stack[], int depth, OutputWriter *writer, void *writer_arg)
Functions
const char * FailureSignalToString (int signo)
bool AddressIsReadable (const void *)
bool Demangle (const char *mangled, char *out, size_t out_size)
void RegisterDebugStackTraceHook (SymbolizeUrlEmitter hook)
SymbolizeUrlEmitter GetDebugStackTraceHook ()
void * GetProgramCounter (void *const vuc)
void DumpPCAndFrameSizesAndStackTrace (void *const pc, void *const stack[], int frame_sizes[], int depth, int min_dropped_frames, bool symbolize_stacktrace, OutputWriter *writer, void *writer_arg)
ABSL_ATTRIBUTE_NOINLINE void DumpStackTrace (int min_dropped_frames, int max_num_frames, bool symbolize_stacktrace, OutputWriter *writer, void *writer_arg)
bool StackTraceWorksForTest ()
Typedef Documentation
OutputWriter
typedef void absl::debugging_internal::OutputWriter(const char *, void *)
Definition at line 28 of file examine_stack.h.
ParseFunc
typedef bool(* absl::debugging_internal::ParseFunc) (State *)
Definition at line 338 of file demangle.cc.
SymbolizeUrlEmitter
typedef void(* absl::debugging_internal::SymbolizeUrlEmitter) (void *const stack[], int depth, OutputWriter *writer, void *writer_arg)
Definition at line 33 of file examine_stack.h.
Function Documentation
AddressIsReadable()
bool absl::debugging_internal::AddressIsReadable (const void *)
Definition at line 27 of file address_is_readable.cc.
{ return true; }
Demangle()
bool absl::debugging_internal::Demangle (const char * mangled, char * out, size_t out_size)
Definition at line 1979 of file demangle.cc.
{
  State state;
  InitState(&state, mangled, out, out_size);
  return ParseTopLevelMangledName(&state) && !Overflowed(&state) &&
         state.parse_state.out_cur_idx > 0;
}
References absl::out, absl::out_size, and state.
DumpPCAndFrameSizesAndStackTrace()
void absl::debugging_internal::DumpPCAndFrameSizesAndStackTrace (void *const pc, void *const stack[], int frame_sizes[], int depth, int min_dropped_frames, bool symbolize_stacktrace, OutputWriter * writer, void * writer_arg)
Definition at line 236 of file examine_stack.cc.
{
  if (pc != nullptr) {
    // We don't know the stack frame size for PC, use 0.
    if (symbolize_stacktrace) {
      DumpPCAndFrameSizeAndSymbol(writer, writer_arg, pc, pc, 0, "PC: ");
    } else {
      DumpPCAndFrameSize(writer, writer_arg, pc, 0, "PC: ");
    }
  }
  for (int i = 0; i < depth; i++) {
    if (symbolize_stacktrace) {
      // Pass the previous address of pc as the symbol address because pc is a
      // return address, and an overrun may occur when the function ends with a
      // call to a function annotated noreturn (e.g. CHECK). Note that we don't
      // do this for pc above, as the adjustment is only correct for return
      // addresses.
      DumpPCAndFrameSizeAndSymbol(writer, writer_arg, stack[i],
                                  reinterpret_cast<char*>(stack[i]) - 1,
                                  frame_sizes[i], "    ");
    } else {
      DumpPCAndFrameSize(writer, writer_arg, stack[i], frame_sizes[i], "    ");
    }
  }
  if (min_dropped_frames > 0) {
    char buf[100];
    snprintf(buf, sizeof(buf), "    @ ... and at least %d more frames\n",
             min_dropped_frames);
    writer(buf, writer_arg);
  }
}
References buf, absl::i, and stack.
DumpStackTrace()
void absl::debugging_internal::DumpStackTrace (int min_dropped_frames, int max_num_frames, bool symbolize_stacktrace, OutputWriter * writer, void * writer_arg)
Definition at line 274 of file examine_stack.cc.
{
  // Print stack trace
  void* stack_buf[kDefaultDumpStackFramesLimit];
  void** stack = stack_buf;
  int num_stack = kDefaultDumpStackFramesLimit;
  size_t allocated_bytes = 0;
  if (num_stack >= max_num_frames) {
    // User requested fewer frames than we already have space for.
    num_stack = max_num_frames;
  } else {
    const size_t needed_bytes =
        static_cast<size_t>(max_num_frames) * sizeof(stack[0]);
    void* p = Allocate(needed_bytes);
    if (p != nullptr) {  // We got the space.
      num_stack = max_num_frames;
      stack = reinterpret_cast<void**>(p);
      allocated_bytes = needed_bytes;
    }
  }
  int depth = absl::GetStackTrace(stack, num_stack, min_dropped_frames + 1);
  for (int i = 0; i < depth; i++) {
    if (symbolize_stacktrace) {
      DumpPCAndSymbol(writer, writer_arg, stack[static_cast<size_t>(i)],
                      "    ");
    } else {
      DumpPC(writer, writer_arg, stack[static_cast<size_t>(i)], "    ");
    }
  }
  auto hook = GetDebugStackTraceHook();
  if (hook != nullptr) {
    (*hook)(stack, depth, writer, writer_arg);
  }
  if (allocated_bytes != 0) Deallocate(stack, allocated_bytes);
}
References GetDebugStackTraceHook(), absl::GetStackTrace(), absl::i, absl::p, and stack.
FailureSignalToString()
const char * absl::debugging_internal::FailureSignalToString (int signo)
Definition at line 121 of file failure_signal_handler.cc.
{
  for (const auto& it : failure_signal_data) {
    if (it.signo == signo) {
      return it.as_string;
    }
  }
  return "";
}
GetDebugStackTraceHook()
SymbolizeUrlEmitter absl::debugging_internal::GetDebugStackTraceHook ()
Definition at line 149 of file examine_stack.cc.
{ return debug_stack_trace_hook; }
Referenced by DumpStackTrace().
GetProgramCounter()
void * absl::debugging_internal::GetProgramCounter (void *const vuc)
Definition at line 154 of file examine_stack.cc.
{
#ifdef __linux__
  if (vuc != nullptr) {
    ucontext_t* context = reinterpret_cast<ucontext_t*>(vuc);
#if defined(__aarch64__)
    return reinterpret_cast<void*>(context->uc_mcontext.pc);
#elif defined(__alpha__)
    return reinterpret_cast<void*>(context->uc_mcontext.sc_pc);
#elif defined(__arm__)
    return reinterpret_cast<void*>(context->uc_mcontext.arm_pc);
#elif defined(__hppa__)
    return reinterpret_cast<void*>(context->uc_mcontext.sc_iaoq[0]);
#elif defined(__i386__)
    if (14 < ABSL_ARRAYSIZE(context->uc_mcontext.gregs))
      return reinterpret_cast<void*>(context->uc_mcontext.gregs[14]);
#elif defined(__ia64__)
    return reinterpret_cast<void*>(context->uc_mcontext.sc_ip);
#elif defined(__m68k__)
    return reinterpret_cast<void*>(context->uc_mcontext.gregs[16]);
#elif defined(__mips__)
    return reinterpret_cast<void*>(context->uc_mcontext.pc);
#elif defined(__powerpc64__)
    return reinterpret_cast<void*>(context->uc_mcontext.gp_regs[32]);
#elif defined(__powerpc__)
    return reinterpret_cast<void*>(context->uc_mcontext.uc_regs->gregs[32]);
#elif defined(__riscv)
    return reinterpret_cast<void*>(context->uc_mcontext.__gregs[REG_PC]);
#elif defined(__s390__) && !defined(__s390x__)
    return reinterpret_cast<void*>(context->uc_mcontext.psw.addr & 0x7fffffff);
#elif defined(__s390__) && defined(__s390x__)
    return reinterpret_cast<void*>(context->uc_mcontext.psw.addr);
#elif defined(__sh__)
    return reinterpret_cast<void*>(context->uc_mcontext.pc);
#elif defined(__sparc__) && !defined(__arch64__)
    return reinterpret_cast<void*>(context->uc_mcontext.gregs[19]);
#elif defined(__sparc__) && defined(__arch64__)
    return reinterpret_cast<void*>(context->uc_mcontext.mc_gregs[19]);
#elif defined(__x86_64__)
    if (16 < ABSL_ARRAYSIZE(context->uc_mcontext.gregs))
      return reinterpret_cast<void*>(context->uc_mcontext.gregs[16]);
#elif defined(__e2k__)
    return reinterpret_cast<void*>(context->uc_mcontext.cr0_hi);
#elif defined(__loongarch__)
    return reinterpret_cast<void*>(context->uc_mcontext.__pc);
#else
#error "Undefined Architecture."
#endif
  }
#elif defined(__APPLE__)
  if (vuc != nullptr) {
    ucontext_t* signal_ucontext = reinterpret_cast<ucontext_t*>(vuc);
#if defined(__aarch64__)
    return reinterpret_cast<void*>(
        __darwin_arm_thread_state64_get_pc(signal_ucontext->uc_mcontext->__ss));
#elif defined(__arm__)
#if __DARWIN_UNIX03
    return reinterpret_cast<void*>(signal_ucontext->uc_mcontext->__ss.__pc);
#else
    return reinterpret_cast<void*>(signal_ucontext->uc_mcontext->ss.pc);
#endif
#elif defined(__i386__)
#if __DARWIN_UNIX03
    return reinterpret_cast<void*>(signal_ucontext->uc_mcontext->__ss.__eip);
#else
    return reinterpret_cast<void*>(signal_ucontext->uc_mcontext->ss.eip);
#endif
#elif defined(__x86_64__)
#if __DARWIN_UNIX03
    return reinterpret_cast<void*>(signal_ucontext->uc_mcontext->__ss.__rip);
#else
    return reinterpret_cast<void*>(signal_ucontext->uc_mcontext->ss.rip);
#endif
#endif
  }
#elif defined(__akaros__)
  auto* ctx = reinterpret_cast<struct user_context*>(vuc);
  return reinterpret_cast<void*>(get_user_ctx_pc(ctx));
#endif
  static_cast<void>(vuc);
  return nullptr;
}
References ABSL_ARRAYSIZE.
RegisterDebugStackTraceHook()
void absl::debugging_internal::RegisterDebugStackTraceHook (SymbolizeUrlEmitter hook)
Definition at line 145 of file examine_stack.cc.
{
  debug_stack_trace_hook = hook;
}
StackTraceWorksForTest()
bool absl::debugging_internal::StackTraceWorksForTest () extern