open spiel: open_spiel::algorithms::torch_az Namespace Reference
open_spiel::algorithms::torch_az Namespace Reference
Classes
struct AlphaZeroConfig
class DeviceManager
class EvalResults
class MLPBlockImpl
class MLPOutputBlockImpl
struct ModelConfig
class ModelImpl
struct ResInputBlockConfig
class ResInputBlockImpl
struct ResOutputBlockConfig
class ResOutputBlockImpl
struct ResTorsoBlockConfig
class ResTorsoBlockImpl
struct StartInfo
struct Trajectory
class VPNetEvaluator
class VPNetModel
Functions
StartInfo StartInfoFromLearnerJson (const std::string &path)
Trajectory PlayGame (Logger *logger, int game_num, const open_spiel::Game &game, std::vector< std::unique_ptr< MCTSBot > > *bots, std::mt19937 *rng, double temperature, int temperature_drop, double cutoff_value, bool verbose=false)
std::unique_ptr< MCTSBot > InitAZBot (const AlphaZeroConfig &config, const open_spiel::Game &game, std::shared_ptr< Evaluator > evaluator, bool evaluation)
void actor (const open_spiel::Game &game, const AlphaZeroConfig &config, int num, ThreadedQueue< Trajectory > *trajectory_queue, std::shared_ptr< VPNetEvaluator > vp_eval, StopToken *stop)
void evaluator (const open_spiel::Game &game, const AlphaZeroConfig &config, int num, EvalResults *results, std::shared_ptr< VPNetEvaluator > vp_eval, StopToken *stop)
void learner (const open_spiel::Game &game, const AlphaZeroConfig &config, DeviceManager *device_manager, std::shared_ptr< VPNetEvaluator > eval, ThreadedQueue< Trajectory > *trajectory_queue, EvalResults *eval_results, StopToken *stop, const StartInfo &start_info)
bool AlphaZero (AlphaZeroConfig config, StopToken *stop, bool resuming)
std::istream & operator>> (std::istream &stream, ModelConfig &config)
std::ostream & operator<< (std::ostream &stream, const ModelConfig &config)
TORCH_MODULE (ResInputBlock)
TORCH_MODULE (ResTorsoBlock)
TORCH_MODULE (ResOutputBlock)
TORCH_MODULE (MLPBlock)
TORCH_MODULE (MLPOutputBlock)
TORCH_MODULE (Model)
bool SaveModelConfig (const std::string &path, const std::string &filename, const ModelConfig &net_config)
ModelConfig LoadModelConfig (const std::string &path, const std::string &filename)
std::string TorchDeviceName (const std::string &device)
bool CreateGraphDef (const Game &game, double learning_rate, double weight_decay, const std::string &path, const std::string &filename, std::string nn_model, int nn_width, int nn_depth, bool verbose)
Function Documentation
actor()
void open_spiel::algorithms::torch_az::actor (const open_spiel::Game & game, const AlphaZeroConfig & config, int num, ThreadedQueue< Trajectory > * trajectory_queue, std::shared_ptr< VPNetEvaluator > vp_eval, StopToken * stop)
Definition at line 179 of file alpha_zero.cc.
{
  std::unique_ptr<Logger> logger;
  if (num < 20) {  // Limit the number of open files.
    logger.reset(new FileLogger(config.path, absl::StrCat("actor-", num)));
  } else {
    logger.reset(new NoopLogger());
  }
  std::mt19937 rng(absl::ToUnixNanos(absl::Now()));
  absl::uniform_real_distribution<double> dist(0.0, 1.0);
  std::vector<std::unique_ptr<MCTSBot>> bots;
  bots.reserve(2);
  for (int player = 0; player < 2; player++) {
    bots.push_back(InitAZBot(config, game, vp_eval, false));
  }
  for (int game_num = 1; !stop->StopRequested(); ++game_num) {
    double cutoff =
        (dist(rng) < config.cutoff_probability ? config.cutoff_value
                                               : game.MaxUtility() + 1);
    if (!trajectory_queue->Push(
            PlayGame(logger.get(), game_num, game, &bots, &rng,
                     config.temperature, config.temperature_drop, cutoff),
            absl::Seconds(10))) {
      logger->Print("Failed to push a trajectory after 10 seconds.");
    }
  }
  logger->Print("Got a quit.");
}
References open_spiel::algorithms::torch_az::AlphaZeroConfig::cutoff_probability, open_spiel::algorithms::torch_az::AlphaZeroConfig::cutoff_value, InitAZBot(), absl::Now(), num, open_spiel::algorithms::torch_az::AlphaZeroConfig::path, player, PlayGame(), open_spiel::ThreadedQueue< T >::Push(), absl::Seconds(), open_spiel::StopToken::StopRequested(), absl::StrCat(), open_spiel::algorithms::torch_az::AlphaZeroConfig::temperature, open_spiel::algorithms::torch_az::AlphaZeroConfig::temperature_drop, and absl::ToUnixNanos().
Referenced by AlphaZero().
AlphaZero()
bool open_spiel::algorithms::torch_az::AlphaZero (AlphaZeroConfig config, StopToken * stop, bool resuming)
Definition at line 496 of file alpha_zero.cc.
{
  std::shared_ptr<const open_spiel::Game> game =
      open_spiel::LoadGame(config.game);
  open_spiel::GameType game_type = game->GetType();
  if (game->NumPlayers() != 2)
    open_spiel::SpielFatalError("AlphaZero can only handle 2-player games.");
  if (game_type.reward_model != open_spiel::GameType::RewardModel::kTerminal)
    open_spiel::SpielFatalError("Game must have terminal rewards.");
  if (game_type.dynamics != open_spiel::GameType::Dynamics::kSequential)
    open_spiel::SpielFatalError("Game must have sequential turns.");
  file::Mkdirs(config.path);
  if (!file::IsDirectory(config.path)) {
    std::cerr << config.path << " is not a directory." << std::endl;
    return false;
  }
  std::cout << "Logging directory: " << config.path << std::endl;
  if (config.graph_def.empty()) {
    config.graph_def = "vpnet.pb";
    std::string model_path = absl::StrCat(config.path, "/", config.graph_def);
    if (file::Exists(model_path)) {
      std::cout << "Overwriting existing model: " << model_path << std::endl;
    } else {
      std::cout << "Creating model: " << model_path << std::endl;
    }
    SPIEL_CHECK_TRUE(CreateGraphDef(
        *game, config.learning_rate, config.weight_decay, config.path,
        config.graph_def, config.nn_model, config.nn_width, config.nn_depth));
  } else {
    std::string model_path = absl::StrCat(config.path, "/", config.graph_def);
    if (file::Exists(model_path)) {
      std::cout << "Using existing model: " << model_path << std::endl;
    } else {
      std::cout << "Model not found: " << model_path << std::endl;
    }
  }
  std::cout << "Playing game: " << config.game << std::endl;
  config.inference_batch_size = std::max(
      1,
      std::min(config.inference_batch_size, config.actors + config.evaluators));
  config.inference_threads =
      std::max(1, std::min(config.inference_threads,
                           (1 + config.actors + config.evaluators) / 2));
  {
    file::File fd(config.path + "/config.json", "w");
    fd.Write(json::ToString(config.ToJson(), true) + "\n");
  }
  StartInfo start_info = {/*start_time=*/absl::Now(),
                          /*start_step=*/1,
                          /*model_checkpoint_step=*/0,
                          /*total_trajectories=*/0};
  if (resuming) {
    start_info = StartInfoFromLearnerJson(config.path);
  }
  DeviceManager device_manager;
  for (const absl::string_view& device : absl::StrSplit(config.devices, ',')) {
    device_manager.AddDevice(
        VPNetModel(*game, config.path, config.graph_def, std::string(device)));
  }
  if (device_manager.Count() == 0) {
    std::cerr << "No devices specified?" << std::endl;
    return false;
  }
  // The explicit_learning option should only be used when multiple
  // devices are available (so that inference can continue while
  // also undergoing learning).
  if (device_manager.Count() <= 1 && config.explicit_learning) {
    std::cerr << "Explicit learning can only be used with multiple devices."
              << std::endl;
    return false;
  }
  std::cerr << "Loading model from step " << start_info.model_checkpoint_step
            << std::endl;
  {  // Make sure they're all in sync.
    if (!resuming) {
      device_manager.Get(0)->SaveCheckpoint(start_info.model_checkpoint_step);
    }
    for (int i = 0; i < device_manager.Count(); ++i) {
      device_manager.Get(0, i)->LoadCheckpoint(
          start_info.model_checkpoint_step);
    }
  }
  auto eval = std::make_shared<VPNetEvaluator>(
      &device_manager, config.inference_batch_size, config.inference_threads,
      config.inference_cache, (config.actors + config.evaluators) / 16);
  ThreadedQueue<Trajectory> trajectory_queue(config.replay_buffer_size /
                                             config.replay_buffer_reuse);
  EvalResults eval_results(config.eval_levels, config.evaluation_window);
  std::vector<Thread> actors;
  actors.reserve(config.actors);
  for (int i = 0; i < config.actors; ++i) {
    actors.emplace_back(
        [&, i]() { actor(*game, config, i, &trajectory_queue, eval, stop); });
  }
  std::vector<Thread> evaluators;
  evaluators.reserve(config.evaluators);
  for (int i = 0; i < config.evaluators; ++i) {
    evaluators.emplace_back(
        [&, i]() { evaluator(*game, config, i, &eval_results, eval, stop); });
  }
  learner(*game, config, &device_manager, eval, &trajectory_queue,
          &eval_results, stop, start_info);
  if (!stop->StopRequested()) {
    stop->Stop();
  }
  // Empty the queue so that the actors can exit.
  trajectory_queue.BlockNewValues();
  trajectory_queue.Clear();
  std::cout << "Joining all the threads." << std::endl;
  for (auto& t : actors) {
    t.join();
  }
  for (auto& t : evaluators) {
    t.join();
  }
  std::cout << "Exiting cleanly." << std::endl;
  return true;
}
References actor(), open_spiel::algorithms::torch_az::AlphaZeroConfig::actors, open_spiel::algorithms::torch_az::DeviceManager::AddDevice(), open_spiel::ThreadedQueue< T >::BlockNewValues(), open_spiel::ThreadedQueue< T >::Clear(), open_spiel::algorithms::torch_az::DeviceManager::Count(), CreateGraphDef(), open_spiel::algorithms::torch_az::AlphaZeroConfig::devices, open_spiel::GameType::dynamics, open_spiel::algorithms::torch_az::AlphaZeroConfig::eval_levels, open_spiel::algorithms::torch_az::AlphaZeroConfig::evaluation_window, evaluator(), open_spiel::algorithms::torch_az::AlphaZeroConfig::evaluators, open_spiel::file::Exists(), open_spiel::algorithms::torch_az::AlphaZeroConfig::explicit_learning, open_spiel::algorithms::torch_az::AlphaZeroConfig::game, open_spiel::algorithms::torch_az::DeviceManager::Get(), open_spiel::algorithms::torch_az::AlphaZeroConfig::graph_def, i, open_spiel::algorithms::torch_az::AlphaZeroConfig::inference_batch_size, open_spiel::algorithms::torch_az::AlphaZeroConfig::inference_cache, open_spiel::algorithms::torch_az::AlphaZeroConfig::inference_threads, open_spiel::file::IsDirectory(), open_spiel::GameType::kSequential, open_spiel::GameType::kTerminal, learner(), open_spiel::algorithms::torch_az::AlphaZeroConfig::learning_rate, open_spiel::algorithms::torch_az::VPNetModel::LoadCheckpoint(), open_spiel::LoadGame(), open_spiel::file::Mkdirs(), open_spiel::algorithms::torch_az::StartInfo::model_checkpoint_step, open_spiel::algorithms::torch_az::AlphaZeroConfig::nn_depth, open_spiel::algorithms::torch_az::AlphaZeroConfig::nn_model, open_spiel::algorithms::torch_az::AlphaZeroConfig::nn_width, absl::Now(), open_spiel::algorithms::torch_az::AlphaZeroConfig::path, open_spiel::algorithms::torch_az::AlphaZeroConfig::replay_buffer_reuse, open_spiel::algorithms::torch_az::AlphaZeroConfig::replay_buffer_size, open_spiel::GameType::reward_model, open_spiel::algorithms::torch_az::VPNetModel::SaveCheckpoint(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), StartInfoFromLearnerJson(), open_spiel::StopToken::Stop(), open_spiel::StopToken::StopRequested(), absl::StrCat(), absl::StrSplit(), open_spiel::algorithms::torch_az::AlphaZeroConfig::ToJson(), open_spiel::json::ToString(), open_spiel::algorithms::torch_az::AlphaZeroConfig::weight_decay, and open_spiel::file::File::Write().
CreateGraphDef()
bool open_spiel::algorithms::torch_az::CreateGraphDef (const Game & game, double learning_rate, double weight_decay, const std::string & path, const std::string & filename, std::string nn_model, int nn_width, int nn_depth, bool verbose)
Definition at line 95 of file vpnet.cc.
{
  ModelConfig net_config = {
      /*observation_tensor_shape=*/game.ObservationTensorShape(),
      /*number_of_actions=*/game.NumDistinctActions(),
      /*nn_depth=*/nn_depth,
      /*nn_width=*/nn_width,
      /*learning_rate=*/learning_rate,
      /*weight_decay=*/weight_decay,
      /*nn_model=*/nn_model};
  return SaveModelConfig(path, filename, net_config);
}
References SaveModelConfig().
Referenced by AlphaZero().
evaluator()
void open_spiel::algorithms::torch_az::evaluator (const open_spiel::Game & game, const AlphaZeroConfig & config, int num, EvalResults * results, std::shared_ptr< VPNetEvaluator > vp_eval, StopToken * stop)
Definition at line 256 of file alpha_zero.cc.
{
  FileLogger logger(config.path, absl::StrCat("evaluator-", num));
  std::mt19937 rng;
  auto rand_evaluator = std::make_shared<RandomRolloutEvaluator>(1, num);
  for (int game_num = 1; !stop->StopRequested(); ++game_num) {
    auto [difficulty, first] = results->Next();
    int az_player = first ? 0 : 1;
    int rand_max_simulations =
        config.max_simulations * std::pow(10, difficulty / 2.0);
    std::vector<std::unique_ptr<MCTSBot>> bots;
    bots.reserve(2);
    bots.push_back(InitAZBot(config, game, vp_eval, true));
    bots.push_back(std::make_unique<MCTSBot>(
        game, rand_evaluator, config.uct_c, rand_max_simulations,
        /*max_memory_mb=*/1000,
        /*solve=*/true,
        /*seed=*/num * 1000 + game_num,
        /*verbose=*/false, ChildSelectionPolicy::UCT,
        /*dirichlet_alpha=*/0,
        /*dirichlet_epsilon=*/0,
        /*dont_return_chance_node=*/true));
    if (az_player == 1) {
      std::swap(bots[0], bots[1]);
    }
    logger.Print("Running MCTS with %d simulations", rand_max_simulations);
    Trajectory trajectory = PlayGame(
        &logger, game_num, game, &bots, &rng, /*temperature=*/1,
        /*temperature_drop=*/0, /*cutoff_value=*/game.MaxUtility() + 1);
    results->Add(difficulty, trajectory.returns[az_player]);
    logger.Print("Game %d: AZ: %5.2f, MCTS: %5.2f, MCTS-sims: %d, length: %d",
                 game_num, trajectory.returns[az_player],
                 trajectory.returns[1 - az_player], rand_max_simulations,
                 trajectory.states.size());
  }
  logger.Print("Got a quit.");
}
References open_spiel::algorithms::torch_az::EvalResults::Add(), first, InitAZBot(), open_spiel::algorithms::torch_az::AlphaZeroConfig::max_simulations, open_spiel::algorithms::torch_az::EvalResults::Next(), num, open_spiel::algorithms::torch_az::AlphaZeroConfig::path, PlayGame(), open_spiel::FileLogger::Print(), open_spiel::algorithms::torch_az::Trajectory::returns, open_spiel::algorithms::torch_az::Trajectory::states, open_spiel::StopToken::StopRequested(), absl::StrCat(), open_spiel::algorithms::UCT, and open_spiel::algorithms::torch_az::AlphaZeroConfig::uct_c.
Referenced by AlphaZero().
InitAZBot()
std::unique_ptr< MCTSBot > open_spiel::algorithms::torch_az::InitAZBot (const AlphaZeroConfig & config, const open_spiel::Game & game, std::shared_ptr< Evaluator > evaluator, bool evaluation)
Definition at line 163 of file alpha_zero.cc.
{
  return std::make_unique<MCTSBot>(
      game, std::move(evaluator), config.uct_c, config.max_simulations,
      /*max_memory_mb=*/10,
      /*solve=*/false,
      /*seed=*/0,
      /*verbose=*/false, ChildSelectionPolicy::PUCT,
      evaluation ? 0 : config.policy_alpha,
      evaluation ? 0 : config.policy_epsilon,
      /*dont_return_chance_node*/ true);
}
References open_spiel::algorithms::torch_az::AlphaZeroConfig::max_simulations, open_spiel::algorithms::torch_az::AlphaZeroConfig::policy_alpha, open_spiel::algorithms::torch_az::AlphaZeroConfig::policy_epsilon, open_spiel::algorithms::PUCT, and open_spiel::algorithms::torch_az::AlphaZeroConfig::uct_c.
Referenced by actor(), and evaluator().
learner()
void open_spiel::algorithms::torch_az::learner (const open_spiel::Game & game, const AlphaZeroConfig & config, DeviceManager * device_manager, std::shared_ptr< VPNetEvaluator > eval, ThreadedQueue< Trajectory > * trajectory_queue, EvalResults * eval_results, StopToken * stop, const StartInfo & start_info)
Definition at line 298 of file alpha_zero.cc.
{
  FileLogger logger(config.path, "learner", "a");
  DataLoggerJsonLines data_logger(
      config.path, "learner", true, "a", start_info.start_time);
  std::mt19937 rng;
  int device_id = 0;  // Do not change, the first device is the learner.
  logger.Print("Running the learner on device %d: %s", device_id,
               device_manager->Get(0, device_id)->Device());
  SerializableCircularBuffer<VPNetModel::TrainInputs> replay_buffer(
      config.replay_buffer_size);
  if (start_info.start_step > 1) {
    replay_buffer.LoadBuffer(config.path + "/replay_buffer.data");
  }
  int learn_rate = config.replay_buffer_size / config.replay_buffer_reuse;
  int64_t total_trajectories = start_info.total_trajectories;
  const int stage_count = 7;
  std::vector<open_spiel::BasicStats> value_accuracies(stage_count);
  std::vector<open_spiel::BasicStats> value_predictions(stage_count);
  open_spiel::BasicStats game_lengths;
  open_spiel::HistogramNumbered game_lengths_hist(game.MaxGameLength() + 1);
  open_spiel::HistogramNamed outcomes({"Player1", "Player2", "Draw"});
  // Actor threads have likely been contributing for a while, so put `last` in
  // the past to avoid a giant spike on the first step.
  absl::Time last = absl::Now() - absl::Seconds(60);
  for (int step = start_info.start_step;
       !stop->StopRequested() &&
           (config.max_steps == 0 || step <= config.max_steps);
       ++step) {
    outcomes.Reset();
    game_lengths.Reset();
    game_lengths_hist.Reset();
    for (auto& value_accuracy : value_accuracies) {
      value_accuracy.Reset();
    }
    for (auto& value_prediction : value_predictions) {
      value_prediction.Reset();
    }
    // Collect trajectories
    int queue_size = trajectory_queue->Size();
    int num_states = 0;
    int num_trajectories = 0;
    while (!stop->StopRequested() && num_states < learn_rate) {
      absl::optional<Trajectory> trajectory = trajectory_queue->Pop();
      if (trajectory) {
        num_trajectories += 1;
        total_trajectories += 1;
        game_lengths.Add(trajectory->states.size());
        game_lengths_hist.Add(trajectory->states.size());
        double p1_outcome = trajectory->returns[0];
        outcomes.Add(p1_outcome > 0 ? 0 : (p1_outcome < 0 ? 1 : 2));
        for (const Trajectory::State& state : trajectory->states) {
          replay_buffer.Add(VPNetModel::TrainInputs{state.legal_actions,
                                                    state.observation,
                                                    state.policy, p1_outcome});
          num_states += 1;
        }
        for (int stage = 0; stage < stage_count; ++stage) {
          // Scale for the length of the game
          int index = (trajectory->states.size() - 1) *
                      static_cast<double>(stage) / (stage_count - 1);
          const Trajectory::State& s = trajectory->states[index];
          value_accuracies[stage].Add(
              (s.value >= 0) == (trajectory->returns[s.current_player] >= 0));
          value_predictions[stage].Add(abs(s.value));
        }
      }
    }
    absl::Time now = absl::Now();
    double seconds = absl::ToDoubleSeconds(now - last);
    logger.Print("Step: %d", step);
    logger.Print(
        "Collected %5d states from %3d games, %.1f states/s; "
        "%.1f states/(s*actor), game length: %.1f",
        num_states, num_trajectories, num_states / seconds,
        num_states / (config.actors * seconds),
        static_cast<double>(num_states) / num_trajectories);
    logger.Print("Queue size: %d. Buffer size: %d. States seen: %d", queue_size,
                 replay_buffer.Size(), replay_buffer.TotalAdded());
    if (stop->StopRequested()) {
      break;
    }
    last = now;
    replay_buffer.SaveBuffer(config.path + "/replay_buffer.data");
    VPNetModel::LossInfo losses;
    {  // Extra scope to return the device for use for inference asap.
      DeviceManager::DeviceLoan learn_model =
          device_manager->Get(config.train_batch_size, device_id);
      // Let the device manager know that the first device is now
      // off-limits for inference and should only be used for learning
      // (if config.explicit_learning == true).
      device_manager->SetLearning(config.explicit_learning);
      // Learn from them.
      for (int i = 0; i < replay_buffer.Size() / config.train_batch_size; i++) {
        losses += learn_model->Learn(
            replay_buffer.Sample(&rng, config.train_batch_size));
      }
      // The device manager can now once again use the first device for
      // inference (if it could not before).
      device_manager->SetLearning(false);
    }
    // Always save a checkpoint, either for keeping or for loading the weights
    // to the other sessions. It only allows numbers, so use -1 as "latest".
    std::string checkpoint_path = device_manager->Get(0, device_id)
        ->SaveCheckpoint(VPNetModel::kMostRecentCheckpointStep);
    if (step % config.checkpoint_freq == 0) {
      device_manager->Get(0, device_id)->SaveCheckpoint(step);
    }
    if (device_manager->Count() > 0) {
      for (int i = 0; i < device_manager->Count(); ++i) {
        if (i != device_id) {
          device_manager->Get(0, i)->LoadCheckpoint(checkpoint_path);
        }
      }
    }
    logger.Print("Checkpoint saved: %s", checkpoint_path);
    DataLogger::Record record = {
        {"step", step},
        {"total_states", replay_buffer.TotalAdded()},
        {"states_per_s", num_states / seconds},
        {"states_per_s_actor", num_states / (config.actors * seconds)},
        {"total_trajectories", total_trajectories},
        {"trajectories_per_s", num_trajectories / seconds},
        {"queue_size", queue_size},
        {"game_length", game_lengths.ToJson()},
        {"game_length_hist", game_lengths_hist.ToJson()},
        {"outcomes", outcomes.ToJson()},
        {"value_accuracy",
         json::TransformToArray(value_accuracies,
                                [](auto v) { return v.ToJson(); })},
        {"value_prediction",
         json::TransformToArray(value_predictions,
                                [](auto v) { return v.ToJson(); })},
        {"eval", json::Object({
                     {"count", eval_results->EvalCount()},
                     {"results", json::CastToArray(eval_results->AvgResults())},
                 })},
        {"batch_size", eval->BatchSizeStats().ToJson()},
        {"batch_size_hist", eval->BatchSizeHistogram().ToJson()},
        {"loss", json::Object({
                     {"policy", losses.Policy()},
                     {"value", losses.Value()},
                     {"l2reg", losses.L2()},
                     {"sum", losses.Total()},
                 })},
    };
    eval->ResetBatchSizeStats();
    logger.Print("Losses: policy: %.4f, value: %.4f, l2: %.4f, sum: %.4f",
                 losses.Policy(), losses.Value(), losses.L2(), losses.Total());
    LRUCacheInfo cache_info = eval->CacheInfo();
    if (cache_info.size > 0) {
      logger.Print(absl::StrFormat(
          "Cache size: %d/%d: %.1f%%, hits: %d, misses: %d, hit rate: %.3f%%",
          cache_info.size, cache_info.max_size, 100.0 * cache_info.Usage(),
          cache_info.hits, cache_info.misses, 100.0 * cache_info.HitRate()));
      eval->ClearCache();
    }
    record.emplace("cache",
                   json::Object({
                       {"size", cache_info.size},
                       {"max_size", cache_info.max_size},
                       {"usage", cache_info.Usage()},
                       {"requests", cache_info.Total()},
                       {"requests_per_s", cache_info.Total() / seconds},
                       {"hits", cache_info.hits},
                       {"misses", cache_info.misses},
                       {"misses_per_s", cache_info.misses / seconds},
                       {"hit_rate", cache_info.HitRate()},
                   }));
    data_logger.Write(record);
    logger.Print("");
  }
}
References open_spiel::algorithms::torch_az::AlphaZeroConfig::actors, open_spiel::BasicStats::Add(), open_spiel::CircularBuffer< T >::Add(), open_spiel::HistogramNumbered::Add(), open_spiel::algorithms::torch_az::EvalResults::AvgResults(), open_spiel::json::CastToArray(), open_spiel::algorithms::torch_az::AlphaZeroConfig::checkpoint_freq, open_spiel::algorithms::torch_az::DeviceManager::Count(), open_spiel::algorithms::torch_az::VPNetModel::Device(), open_spiel::algorithms::torch_az::EvalResults::EvalCount(), open_spiel::algorithms::torch_az::AlphaZeroConfig::explicit_learning, open_spiel::algorithms::torch_az::DeviceManager::Get(), open_spiel::LRUCacheInfo::HitRate(), open_spiel::LRUCacheInfo::hits, i, open_spiel::algorithms::torch_az::VPNetModel::kMostRecentCheckpointStep, open_spiel::algorithms::torch_az::VPNetModel::LossInfo::L2(), open_spiel::algorithms::torch_az::VPNetModel::Learn(), open_spiel::algorithms::torch_az::VPNetModel::TrainInputs::legal_actions, open_spiel::SerializableCircularBuffer< T >::LoadBuffer(), open_spiel::algorithms::torch_az::VPNetModel::LoadCheckpoint(), open_spiel::LRUCacheInfo::max_size, open_spiel::algorithms::torch_az::AlphaZeroConfig::max_steps, open_spiel::LRUCacheInfo::misses, absl::Now(), open_spiel::algorithms::torch_az::AlphaZeroConfig::path, open_spiel::algorithms::torch_az::VPNetModel::LossInfo::Policy(), open_spiel::ThreadedQueue< T >::Pop(), open_spiel::FileLogger::Print(), open_spiel::algorithms::torch_az::AlphaZeroConfig::replay_buffer_reuse, open_spiel::algorithms::torch_az::AlphaZeroConfig::replay_buffer_size, open_spiel::BasicStats::Reset(), open_spiel::HistogramNumbered::Reset(), open_spiel::CircularBuffer< T >::Sample(), open_spiel::SerializableCircularBuffer< T >::SaveBuffer(), open_spiel::algorithms::torch_az::VPNetModel::SaveCheckpoint(), absl::Seconds(), open_spiel::algorithms::torch_az::DeviceManager::SetLearning(), open_spiel::CircularBuffer< T >::Size(), open_spiel::ThreadedQueue< T >::Size(), open_spiel::LRUCacheInfo::size, open_spiel::algorithms::torch_az::StartInfo::start_step, open_spiel::algorithms::torch_az::StartInfo::start_time, state, open_spiel::StopToken::StopRequested(), absl::StrFormat(), absl::ToDoubleSeconds(), open_spiel::BasicStats::ToJson(), open_spiel::HistogramNumbered::ToJson(), open_spiel::algorithms::torch_az::VPNetModel::LossInfo::Total(), open_spiel::LRUCacheInfo::Total(), open_spiel::algorithms::torch_az::StartInfo::total_trajectories, open_spiel::CircularBuffer< T >::TotalAdded(), open_spiel::algorithms::torch_az::AlphaZeroConfig::train_batch_size, open_spiel::json::TransformToArray(), open_spiel::LRUCacheInfo::Usage(), and open_spiel::algorithms::torch_az::VPNetModel::LossInfo::Value().
Referenced by AlphaZero().
LoadModelConfig()
ModelConfig open_spiel::algorithms::torch_az::LoadModelConfig (const std::string & path, const std::string & filename)
Definition at line 66 of file vpnet.cc.
{
  std::ifstream file;
  file.open(absl::StrCat(path, "/", filename));
  ModelConfig net_config;
  file >> net_config;
  file.close();
  return net_config;
}
References absl::StrCat().
operator<<()
std::ostream & open_spiel::algorithms::torch_az::operator<< (std::ostream & stream, const ModelConfig & config)
Definition at line 41 of file model.cc.
{
  stream << config.observation_tensor_shape[0] << " "
         << config.observation_tensor_shape[1] << " "
         << config.observation_tensor_shape[2] << " "
         << config.number_of_actions << " " << config.nn_depth << " "
         << config.nn_width << " " << config.learning_rate << " "
         << config.weight_decay << " " << config.nn_model;
  return stream;
}
References open_spiel::algorithms::torch_az::ModelConfig::learning_rate, open_spiel::algorithms::torch_az::ModelConfig::nn_depth, open_spiel::algorithms::torch_az::ModelConfig::nn_model, open_spiel::algorithms::torch_az::ModelConfig::nn_width, open_spiel::algorithms::torch_az::ModelConfig::number_of_actions, open_spiel::algorithms::torch_az::ModelConfig::observation_tensor_shape, and open_spiel::algorithms::torch_az::ModelConfig::weight_decay.
operator>>()
std::istream & open_spiel::algorithms::torch_az::operator>> (std::istream & stream, ModelConfig & config)
Definition at line 27 of file model.cc.
{
  int channels;
  int height;
  int width;
  stream >> channels >> height >> width >> config.number_of_actions >>
      config.nn_depth >> config.nn_width >> config.learning_rate >>
      config.weight_decay >> config.nn_model;
  config.observation_tensor_shape = {channels, height, width};
  return stream;
}
References open_spiel::algorithms::torch_az::ModelConfig::learning_rate, open_spiel::algorithms::torch_az::ModelConfig::nn_depth, open_spiel::algorithms::torch_az::ModelConfig::nn_model, open_spiel::algorithms::torch_az::ModelConfig::nn_width, open_spiel::algorithms::torch_az::ModelConfig::number_of_actions, open_spiel::algorithms::torch_az::ModelConfig::observation_tensor_shape, and open_spiel::algorithms::torch_az::ModelConfig::weight_decay.
PlayGame()
Trajectory open_spiel::algorithms::torch_az::PlayGame (Logger * logger, int game_num, const open_spiel::Game & game, std::vector< std::unique_ptr< MCTSBot > > * bots, std::mt19937 * rng, double temperature, int temperature_drop, double cutoff_value, bool verbose = false)
Definition at line 104 of file alpha_zero.cc.
{
  std::unique_ptr<open_spiel::State> state = game.NewInitialState();
  std::vector<std::string> history;
  Trajectory trajectory;
  while (true) {
    if (state->IsChanceNode()) {
      open_spiel::ActionsAndProbs outcomes = state->ChanceOutcomes();
      open_spiel::Action action =
          open_spiel::SampleAction(outcomes, *rng).first;
      state->ApplyAction(action);
    } else {
      open_spiel::Player player = state->CurrentPlayer();
      std::unique_ptr<SearchNode> root = (*bots)[player]->MCTSearch(*state);
      open_spiel::ActionsAndProbs policy;
      policy.reserve(root->children.size());
      for (const SearchNode& c : root->children) {
        policy.emplace_back(c.action,
                            std::pow(c.explore_count, 1.0 / temperature));
      }
      NormalizePolicy(&policy);
      open_spiel::Action action;
      if (history.size() >= temperature_drop) {
        action = root->BestChild().action;
      } else {
        action = open_spiel::SampleAction(policy, *rng).first;
      }
      double root_value = root->total_reward / root->explore_count;
      trajectory.states.push_back(Trajectory::State{
          state->ObservationTensor(), player, state->LegalActions(), action,
          std::move(policy), root_value});
      std::string action_str = state->ActionToString(player, action);
      history.push_back(action_str);
      state->ApplyAction(action);
      if (verbose) {
        logger->Print("Player: %d, action: %s", player, action_str);
      }
      if (state->IsTerminal()) {
        trajectory.returns = state->Returns();
        break;
      } else if (std::abs(root_value) > cutoff_value) {
        trajectory.returns.resize(2);
        trajectory.returns[player] = root_value;
        trajectory.returns[1 - player] = -root_value;
        break;
      }
    }
  }
  logger->Print("Game %d: Returns: %s; Actions: %s", game_num,
                absl::StrJoin(trajectory.returns, " "),
                absl::StrJoin(history, " "));
  return trajectory;
}
References action, open_spiel::NormalizePolicy(), player, open_spiel::Logger::Print(), open_spiel::algorithms::torch_az::Trajectory::returns, open_spiel::SampleAction(), state, open_spiel::algorithms::torch_az::Trajectory::states, and absl::StrJoin().
Referenced by actor(), and evaluator().
SaveModelConfig()
bool open_spiel::algorithms::torch_az::SaveModelConfig (const std::string & path, const std::string & filename, const ModelConfig & net_config)
Definition at line 45 of file vpnet.cc.
{
  std::ofstream file;
  file.open(absl::StrCat(path, "/", filename));
  if (!file) {
    return false;
  } else {
    file << net_config;
  }
  file.close();
  return true;
}
References absl::StrCat().
Referenced by CreateGraphDef().
StartInfoFromLearnerJson()
StartInfo open_spiel::algorithms::torch_az::StartInfoFromLearnerJson (const std::string & path)
Definition at line 62 of file alpha_zero.cc.
{
  StartInfo start_info;
  file::File learner_file(path + "/learner.jsonl", "r");
  std::vector<std::string> learner_lines = absl::StrSplit(
      learner_file.ReadContents(), "\n");
  std::string last_learner_line;
  // Get the last non-empty line in learner.jsonl.
  for (int i = learner_lines.size() - 1; i >= 0; i--) {
    if (!learner_lines[i].empty()) {
      last_learner_line = learner_lines[i];
      break;
    }
  }
  json::Object last_learner_json = json::FromString(
      last_learner_line).value().GetObject();
  start_info.start_time = absl::Now() - absl::Seconds(
      last_learner_json["time_rel"].GetDouble());
  start_info.start_step = last_learner_json["step"].GetInt() + 1;
  start_info.model_checkpoint_step = VPNetModel::kMostRecentCheckpointStep;
  start_info.total_trajectories =
      last_learner_json["total_trajectories"].GetInt();
  return start_info;
}
References open_spiel::json::FromString(), i, open_spiel::algorithms::torch_az::VPNetModel::kMostRecentCheckpointStep, open_spiel::algorithms::torch_az::StartInfo::model_checkpoint_step, absl::Now(), open_spiel::file::File::ReadContents(), absl::Seconds(), open_spiel::algorithms::torch_az::StartInfo::start_step, open_spiel::algorithms::torch_az::StartInfo::start_time, absl::StrSplit(), and open_spiel::algorithms::torch_az::StartInfo::total_trajectories.
Referenced by AlphaZero().
TORCH_MODULE() [1/6]
open_spiel::algorithms::torch_az::TORCH_MODULE (MLPBlock)
TORCH_MODULE() [2/6]
open_spiel::algorithms::torch_az::TORCH_MODULE (MLPOutputBlock)
TORCH_MODULE() [3/6]
open_spiel::algorithms::torch_az::TORCH_MODULE (Model)
TORCH_MODULE() [4/6]
open_spiel::algorithms::torch_az::TORCH_MODULE (ResInputBlock)
TORCH_MODULE() [5/6]
open_spiel::algorithms::torch_az::TORCH_MODULE (ResOutputBlock)
TORCH_MODULE() [6/6]
open_spiel::algorithms::torch_az::TORCH_MODULE (ResTorsoBlock)
TorchDeviceName()
std::string open_spiel::algorithms::torch_az::TorchDeviceName (const std::string & device)
Definition at line 88 of file vpnet.cc.
{
  if (device[0] == '/') {
    return device.substr(1);
  }
  return device;
}