open spiel: absl::memory_internal Namespace Reference
absl::memory_internal Namespace Reference
Classes
struct ExtractOr
struct ExtractOr< Extract, Obj, Default, void_t< Extract< Obj > > >
Typedefs
template<template< typename > class Extract, typename Obj , typename Default >
using ExtractOrT = typename ExtractOr<Extract, Obj, Default, void>::type
template<typename Alloc >
using GetIsNothrow = typename Alloc::is_nothrow
Functions
template<typename Allocator , typename Iterator , typename... Args>
void ConstructRange (Allocator &alloc, Iterator first, Iterator last, const Args &... args)
template<typename Allocator , typename Iterator , typename InputIterator >
void CopyRange (Allocator &alloc, Iterator destination, InputIterator first, InputIterator last)
Typedef Documentation
ExtractOrT
template<template< typename > class Extract, typename Obj , typename Default > using absl::memory_internal::ExtractOrT = typename ExtractOr<Extract, Obj, Default, void>::type
Definition at line 196 of file memory.h.
GetIsNothrow
template<typename Alloc > using absl::memory_internal::GetIsNothrow = typename Alloc::is_nothrow
Definition at line 201 of file memory.h.
Function Documentation
ConstructRange()
template<typename Allocator , typename Iterator , typename... Args> void absl::memory_internal::ConstructRange (Allocator & alloc, Iterator first, Iterator last, const Args &... args)
Definition at line 239 of file memory.h.
{
  for (Iterator cur = first; cur != last; ++cur) {
    ABSL_INTERNAL_TRY {
      std::allocator_traits<Allocator>::construct(alloc, std::addressof(*cur),
                                                  args...);
    }
    ABSL_INTERNAL_CATCH_ANY {
      while (cur != first) {
        --cur;
        std::allocator_traits<Allocator>::destroy(alloc, std::addressof(*cur));
      }
      ABSL_INTERNAL_RETHROW;
    }
  }
}
References ABSL_INTERNAL_CATCH_ANY, ABSL_INTERNAL_RETHROW, ABSL_INTERNAL_TRY, alloc, and first.
Referenced by absl::FixedArray< T, N, A >::FixedArray(), and absl::FixedArray< T, N, A >::FixedArray().
CopyRange()
template<typename Allocator , typename Iterator , typename InputIterator > void absl::memory_internal::CopyRange (Allocator & alloc, Iterator destination, InputIterator first, InputIterator last)
Definition at line 257 of file memory.h.
{
  for (Iterator cur = destination; first != last;
       static_cast<void>(++cur), static_cast<void>(++first)) {
    ABSL_INTERNAL_TRY {
      std::allocator_traits<Allocator>::construct(alloc, std::addressof(*cur),
                                                  *first);
    }
    ABSL_INTERNAL_CATCH_ANY {
      while (cur != destination) {
        --cur;
        std::allocator_traits<Allocator>::destroy(alloc, std::addressof(*cur));
      }
      ABSL_INTERNAL_RETHROW;
    }
  }
}
References ABSL_INTERNAL_CATCH_ANY, ABSL_INTERNAL_RETHROW, ABSL_INTERNAL_TRY, alloc, and first.
Referenced by absl::FixedArray< T, N, A >::FixedArray().