open spiel: absl::crc_internal Namespace Reference
absl::crc_internal Namespace Reference
Classes
class CRC
class CRC32
class CrcCordState
class CRCImpl
class CrcMemcpy
class CrcMemcpyEngine
class CrcNonTemporalMemcpyAVXEngine
class CrcNonTemporalMemcpyEngine
class FallbackCrcMemcpyEngine
Enumerations
enum class CpuType {
kUnknown , kIntelHaswell , kAmdRome , kAmdNaples ,
kAmdMilan , kIntelCascadelakeXeon , kIntelSkylakeXeon , kIntelBroadwell ,
kIntelSkylake , kIntelIvybridge , kIntelSandybridge , kIntelWestmere ,
kArmNeoverseN1
}
Functions
crc32c_t UnextendCrc32cByZeroes (crc32c_t initial_crc, size_t length)
crc32c_t ExtendCrc32cInternal (crc32c_t initial_crc, absl::string_view buf_to_add)
CpuType GetCpuType ()
bool SupportsArmCRC32PMULL ()
bool ExtendCrc32cInline (uint32_t *crc, const char *p, size_t n)
template<typename T >
T MaskOfLength (int len)
template<typename T >
T RotateRight (T in, int width, int r)
template<int alignment>
const uint8_t * RoundUp (const uint8_t *p)
CRCImpl * TryNewCRC32AcceleratedX86ARMCombined ()
std::vector< std::unique_ptr< CRCImpl > > NewCRC32AcceleratedX86ARMCombinedAll ()
crc32c_t Crc32CAndCopy (void *__restrict dst, const void *__restrict src, std::size_t length, crc32c_t initial_crc=crc32c_t{0}, bool non_temporal=false)
void * non_temporal_store_memcpy (void *__restrict dst, const void *__restrict src, size_t len)
void * non_temporal_store_memcpy_avx (void *__restrict dst, const void *__restrict src, size_t len)
Variables
constexpr int kPrefetchHorizon = ABSL_CACHELINE_SIZE * 4
constexpr int kPrefetchHorizonMedium = ABSL_CACHELINE_SIZE * 1
constexpr uint64_t kScrambleHi
constexpr uint64_t kScrambleLo
constexpr size_t kCacheLineSize = ABSL_CACHELINE_SIZE
Enumeration Type Documentation
CpuType
enum class absl::crc_internal::CpuType strong
Enumerator
kUnknown
kIntelHaswell
kAmdRome
kAmdNaples
kAmdMilan
kIntelCascadelakeXeon
kIntelSkylakeXeon
kIntelBroadwell
kIntelSkylake
kIntelIvybridge
kIntelSandybridge
kIntelWestmere
kArmNeoverseN1
Definition at line 26 of file cpu_detect.h.
                   {
  kUnknown,
  kIntelHaswell,
  kAmdRome,
  kAmdNaples,
  kAmdMilan,
  kIntelCascadelakeXeon,
  kIntelSkylakeXeon,
  kIntelBroadwell,
  kIntelSkylake,
  kIntelIvybridge,
  kIntelSandybridge,
  kIntelWestmere,
  kArmNeoverseN1,
};
Function Documentation
Crc32CAndCopy()
crc32c_t absl::crc_internal::Crc32CAndCopy (void *__restrict dst, const void *__restrict src, std::size_t length, crc32c_t initial_crc = crc32c_t{0}, bool non_temporal = false) inline
Definition at line 108 of file crc_memcpy.h.
                                                             {0},
                              bool non_temporal = false) {
  return CrcMemcpy::CrcAndCopy(dst, src, length, initial_crc, non_temporal);
}
Referenced by absl::MemcpyCrc32c().
ExtendCrc32cInline()
bool absl::crc_internal::ExtendCrc32cInline (uint32_t * crc, const char * p, size_t n) inline
Definition at line 31 of file crc32c_inline.h.
{
#if defined(ABSL_CRC_INTERNAL_HAVE_ARM_SIMD) || \
    defined(ABSL_CRC_INTERNAL_HAVE_X86_SIMD)
  constexpr uint32_t kCrc32Xor = 0xffffffffU;
  *crc ^= kCrc32Xor;
  if (n & 1) {
    *crc = CRC32_u8(*crc, static_cast<uint8_t>(*p));
    n--;
    p++;
  }
  if (n & 2) {
    *crc = CRC32_u16(*crc, absl::little_endian::Load16(p));
    n -= 2;
    p += 2;
  }
  if (n & 4) {
    *crc = CRC32_u32(*crc, absl::little_endian::Load32(p));
    n -= 4;
    p += 4;
  }
  while (n) {
    *crc = CRC32_u64(*crc, absl::little_endian::Load64(p));
    n -= 8;
    p += 8;
  }
  *crc ^= kCrc32Xor;
  return true;
#else
  // No hardware support, signal the need to fallback.
  static_cast<void>(crc);
  static_cast<void>(p);
  static_cast<void>(n);
  return false;
#endif  // defined(ABSL_CRC_INTERNAL_HAVE_ARM_SIMD) ||
        // defined(ABSL_CRC_INTERNAL_HAVE_X86_SIMD)
}
References absl::little_endian::Load16(), absl::little_endian::Load32(), absl::little_endian::Load64(), absl::n, and absl::p.
Referenced by absl::ExtendCrc32c().
ExtendCrc32cInternal()
crc32c_t absl::crc_internal::ExtendCrc32cInternal (crc32c_t initial_crc, absl::string_view buf_to_add)
Definition at line 48 of file crc32c.cc.
{
  uint32_t crc = static_cast<uint32_t>(initial_crc) ^ kCRC32Xor;
  CrcEngine()->Extend(&crc, buf_to_add.data(), buf_to_add.size());
  return static_cast<crc32c_t>(crc ^ kCRC32Xor);
}
References absl::string_view::data(), and absl::string_view::size().
Referenced by absl::ExtendCrc32c().
GetCpuType()
CpuType absl::crc_internal::GetCpuType ()
Definition at line 248 of file cpu_detect.cc.
{ return CpuType::kUnknown; }
References kUnknown.
MaskOfLength()
template<typename T > T absl::crc_internal::MaskOfLength (int len)
Definition at line 145 of file crc_internal.h.
{
  // shift 2 by len-1 rather than 1 by len because shifts of wordsize
  // are undefined.
  return (T(2) << (len - 1)) - 1;
}
References len.
Referenced by RotateRight(), absl::crc_internal::CRC32::Scramble(), and absl::crc_internal::CRC32::Unscramble().
NewCRC32AcceleratedX86ARMCombinedAll()
std::vector< std::unique_ptr< CRCImpl > > absl::crc_internal::NewCRC32AcceleratedX86ARMCombinedAll ()
Definition at line 714 of file crc_x86_arm_combined.cc.
{
  return std::vector<std::unique_ptr<CRCImpl>>();
}
non_temporal_store_memcpy()
void * absl::crc_internal::non_temporal_store_memcpy (void *__restrict dst, const void *__restrict src, size_t len) inline
Definition at line 61 of file non_temporal_memcpy.h.
{
#if defined(__SSE3__) || defined(__aarch64__) || \
    (defined(_MSC_VER) && defined(__AVX__))
  // This implementation requires SSE3.
  // MSVC cannot target SSE3 directly, but when MSVC targets AVX,
  // SSE3 support is implied.
  uint8_t *d = reinterpret_cast<uint8_t *>(dst);
  const uint8_t *s = reinterpret_cast<const uint8_t *>(src);
  // memcpy() the misaligned header. At the end of this if block, <d> is
  // aligned to a 64-byte cacheline boundary or <len> == 0.
  if (reinterpret_cast<uintptr_t>(d) & (kCacheLineSize - 1)) {
    uintptr_t bytes_before_alignment_boundary =
        kCacheLineSize -
        (reinterpret_cast<uintptr_t>(d) & (kCacheLineSize - 1));
    size_t header_len = (std::min)(bytes_before_alignment_boundary, len);
    assert(bytes_before_alignment_boundary < kCacheLineSize);
    memcpy(d, s, header_len);
    d += header_len;
    s += header_len;
    len -= header_len;
  }
  if (len >= kCacheLineSize) {
    _mm_sfence();
    __m128i *dst_cacheline = reinterpret_cast<__m128i *>(d);
    const __m128i *src_cacheline = reinterpret_cast<const __m128i *>(s);
    constexpr int kOpsPerCacheLine = kCacheLineSize / sizeof(__m128i);
    size_t loops = len / kCacheLineSize;
    while (len >= kCacheLineSize) {
      __m128i temp1, temp2, temp3, temp4;
      temp1 = _mm_lddqu_si128(src_cacheline + 0);
      temp2 = _mm_lddqu_si128(src_cacheline + 1);
      temp3 = _mm_lddqu_si128(src_cacheline + 2);
      temp4 = _mm_lddqu_si128(src_cacheline + 3);
      _mm_stream_si128(dst_cacheline + 0, temp1);
      _mm_stream_si128(dst_cacheline + 1, temp2);
      _mm_stream_si128(dst_cacheline + 2, temp3);
      _mm_stream_si128(dst_cacheline + 3, temp4);
      src_cacheline += kOpsPerCacheLine;
      dst_cacheline += kOpsPerCacheLine;
      len -= kCacheLineSize;
    }
    d += loops * kCacheLineSize;
    s += loops * kCacheLineSize;
    _mm_sfence();
  }
  // memcpy the tail.
  if (len) {
    memcpy(d, s, len);
  }
  return dst;
#else
  // Fallback to regular memcpy.
  return memcpy(dst, src, len);
#endif  // __SSE3__ || __aarch64__ || (_MSC_VER && __AVX__)
}
References absl::d, kCacheLineSize, len, and absl::s.
Referenced by absl::crc_internal::CrcNonTemporalMemcpyEngine::Compute().
non_temporal_store_memcpy_avx()
void * absl::crc_internal::non_temporal_store_memcpy_avx (void *__restrict dst, const void *__restrict src, size_t len) inline
Definition at line 122 of file non_temporal_memcpy.h.
{
#ifdef __AVX__
  uint8_t *d = reinterpret_cast<uint8_t *>(dst);
  const uint8_t *s = reinterpret_cast<const uint8_t *>(src);
  // memcpy() the misaligned header. At the end of this if block, <d> is
  // aligned to a 64-byte cacheline boundary or <len> == 0.
  if (reinterpret_cast<uintptr_t>(d) & (kCacheLineSize - 1)) {
    uintptr_t bytes_before_alignment_boundary =
        kCacheLineSize -
        (reinterpret_cast<uintptr_t>(d) & (kCacheLineSize - 1));
    size_t header_len = (std::min)(bytes_before_alignment_boundary, len);
    assert(bytes_before_alignment_boundary < kCacheLineSize);
    memcpy(d, s, header_len);
    d += header_len;
    s += header_len;
    len -= header_len;
  }
  if (len >= kCacheLineSize) {
    _mm_sfence();
    __m256i *dst_cacheline = reinterpret_cast<__m256i *>(d);
    const __m256i *src_cacheline = reinterpret_cast<const __m256i *>(s);
    constexpr int kOpsPerCacheLine = kCacheLineSize / sizeof(__m256i);
    size_t loops = len / kCacheLineSize;
    while (len >= kCacheLineSize) {
      __m256i temp1, temp2;
      temp1 = _mm256_lddqu_si256(src_cacheline + 0);
      temp2 = _mm256_lddqu_si256(src_cacheline + 1);
      _mm256_stream_si256(dst_cacheline + 0, temp1);
      _mm256_stream_si256(dst_cacheline + 1, temp2);
      src_cacheline += kOpsPerCacheLine;
      dst_cacheline += kOpsPerCacheLine;
      len -= kCacheLineSize;
    }
    d += loops * kCacheLineSize;
    s += loops * kCacheLineSize;
    _mm_sfence();
  }
  // memcpy the tail.
  if (len) {
    memcpy(d, s, len);
  }
  return dst;
#else
  // Fallback to regular memcpy when AVX is not available.
  return memcpy(dst, src, len);
#endif  // __AVX__
}
References absl::d, kCacheLineSize, len, and absl::s.
Referenced by absl::crc_internal::CrcNonTemporalMemcpyAVXEngine::Compute().
RotateRight()
template<typename T > T absl::crc_internal::RotateRight (T in, int width, int r)
Definition at line 154 of file crc_internal.h.
{
  return (in << (width - r)) | ((in >> r) & MaskOfLength<T>(width - r));
}
References in, MaskOfLength(), and r.
Referenced by absl::crc_internal::CRC32::Scramble(), and absl::crc_internal::CRC32::Unscramble().
RoundUp()
template<int alignment> const uint8_t * absl::crc_internal::RoundUp (const uint8_t * p)
Definition at line 161 of file crc_internal.h.
{
  static_assert((alignment & (alignment - 1)) == 0, "alignment is not 2^n");
  constexpr uintptr_t mask = alignment - 1;
  const uintptr_t as_uintptr = reinterpret_cast<uintptr_t>(p);
  return reinterpret_cast<const uint8_t*>((as_uintptr + mask) & ~mask);
}
References absl::p.
Referenced by absl::crc_internal::CRC32::Extend().
SupportsArmCRC32PMULL()
bool absl::crc_internal::SupportsArmCRC32PMULL ()
Definition at line 250 of file cpu_detect.cc.
{ return false; }
TryNewCRC32AcceleratedX86ARMCombined()
CRCImpl * absl::crc_internal::TryNewCRC32AcceleratedX86ARMCombined ()
Definition at line 719 of file crc_x86_arm_combined.cc.
{ return nullptr; }
Referenced by absl::crc_internal::CRCImpl::NewInternal().
UnextendCrc32cByZeroes()
crc32c_t absl::crc_internal::UnextendCrc32cByZeroes (crc32c_t initial_crc, size_t length)
Definition at line 40 of file crc32c.cc.
{
  uint32_t crc = static_cast<uint32_t>(initial_crc) ^ kCRC32Xor;
  CrcEngine()->UnextendByZeroes(&crc, length);
  return static_cast<crc32c_t>(crc ^ kCRC32Xor);
}
Variable Documentation
kCacheLineSize
size_t absl::crc_internal::kCacheLineSize = ABSL_CACHELINE_SIZE constexpr
Definition at line 58 of file non_temporal_memcpy.h.
Referenced by non_temporal_store_memcpy(), and non_temporal_store_memcpy_avx().
kPrefetchHorizon
int absl::crc_internal::kPrefetchHorizon = ABSL_CACHELINE_SIZE * 4 constexpr
Definition at line 31 of file crc_internal.h.
Referenced by absl::crc_internal::CRC32::Extend().
kPrefetchHorizonMedium
int absl::crc_internal::kPrefetchHorizonMedium = ABSL_CACHELINE_SIZE * 1 constexpr
Definition at line 33 of file crc_internal.h.
kScrambleHi
uint64_t absl::crc_internal::kScrambleHi constexpr
Initial value:
= (static_cast<uint64_t>(0x4f1bbcdcU) << 32) |
                                 static_cast<uint64_t>(0xbfa53e0aU)
Definition at line 58 of file crc_internal.h.
kScrambleLo
uint64_t absl::crc_internal::kScrambleLo constexpr
Initial value:
= (static_cast<uint64_t>(0xf9ce6030U) << 32) |
                                 static_cast<uint64_t>(0x2e76e41bU)
Definition at line 60 of file crc_internal.h.
Referenced by absl::crc_internal::CRC32::Scramble(), and absl::crc_internal::CRC32::Unscramble().