open spiel: open_spiel.python.examples.game_tree_traversal_example Namespace Reference
open_spiel.python.examples.game_tree_traversal_example Namespace Reference
Classes
class GameStats
Functions
traverse_game_tree (pyspiel.Game game, pyspiel.State state, GameStats game_stats)
main (_)
Variables
_GAME_STRING
Detailed Description
Example to traverse an entire game tree.
Function Documentation
main()
open_spiel.python.examples.game_tree_traversal_example.main (_)
Definition at line 76 of file game_tree_traversal_example.py.
def main(_):
  game = pyspiel.load_game(_GAME_STRING.value)
  game_stats = GameStats()
  state = game.new_initial_state()
  traverse_game_tree(game, state, game_stats)
  print(game_stats)
  # for info_state_string in game_stats.info_state_dict:
  #   print(info_state_string)
  #   # print(game_stats.info_state_dict[info_state_string])  # legal actions
References open_spiel.python.examples.game_tree_traversal_example.traverse_game_tree().
traverse_game_tree()
open_spiel.python.examples.game_tree_traversal_example.traverse_game_tree (pyspiel.Game game, pyspiel.State state, GameStats game_stats)
Traverses the game tree, collecting information about the game.
Definition at line 44 of file game_tree_traversal_example.py.
                       game_stats: GameStats):
  """Traverses the game tree, collecting information about the game."""
  if state.is_terminal():
    game_stats.num_terminals += 1
  elif state.is_chance_node():
    game_stats.num_chance_nodes += 1
    for outcome in state.legal_actions():
      child = state.child(outcome)
      traverse_game_tree(game, child, game_stats)
  elif state.is_simultaneous_node():
    game_stats.num_simultaneous_nodes += 1
    # Using joint actions for convenience. Can use legal_actions(player) to
    # and state.apply_actions when walking over individual players
    for joint_action in state.legal_actions():
      child = state.child(joint_action)
      traverse_game_tree(game, child, game_stats)
  else:
    game_stats.num_decision_nodes += 1
    legal_actions = state.legal_actions()
    if game.get_type().provides_information_state_string:
      game_stats.info_state_dict[
          state.information_state_string()] = legal_actions
    for action in state.legal_actions():
      # print(f"Decision node: \n {state}")
      # print(f"Taking action {action} ({state.action_to_string(action)}")
      child = state.child(action)
      traverse_game_tree(game, child, game_stats)
References open_spiel.python.examples.game_tree_traversal_example.traverse_game_tree().
Referenced by open_spiel.python.examples.game_tree_traversal_example.main(), and open_spiel.python.examples.game_tree_traversal_example.traverse_game_tree().
Variable Documentation
_GAME_STRING
open_spiel.python.examples.game_tree_traversal_example._GAME_STRING protected
Initial value:
=  flags.DEFINE_string(
    "game_string", "tic_tac_toe", "Name of the game"
)
Definition at line 23 of file game_tree_traversal_example.py.