open spiel: open_spiel::cursor_go Namespace Reference
open_spiel::cursor_go Namespace Reference
Classes
class CursorGoGame
class CursorGoState
Enumerations
enum CursorGoAction : Action {
kActionUp , kActionDown , kActionLeft , kActionRight ,
kActionPlaceStone , kActionPass
}
Functions
int MaxGameLength (int board_size)
int ColorToPlayer (GoColor c)
Variables
constexpr int kNumPlayers = 2
constexpr double kLossUtility = -1
constexpr double kWinUtility = 1
constexpr int kCellStates = 3
constexpr double kDrawUtility = 0
constexpr int kNumDistinctActions = kActionPass + 1
Enumeration Type Documentation
CursorGoAction
enum open_spiel::cursor_go::CursorGoAction : Action
Enumerator
kActionUp
kActionDown
kActionLeft
kActionRight
kActionPlaceStone
kActionPass
Definition at line 50 of file cursor_go.h.
                    : Action {
  kActionUp,
  kActionDown,
  kActionLeft,
  kActionRight,
  kActionPlaceStone,
  kActionPass
};
Function Documentation
ColorToPlayer()
int open_spiel::cursor_go::ColorToPlayer (GoColor c) inline
Definition at line 79 of file cursor_go.h.
{ return static_cast<int>(c); }
Referenced by open_spiel::cursor_go::CursorGoState::CurrentPlayer(), open_spiel::cursor_go::CursorGoState::DoApplyAction(), open_spiel::cursor_go::CursorGoState::LegalActions(), open_spiel::cursor_go::CursorGoState::ObservationTensor(), open_spiel::cursor_go::CursorGoState::Returns(), and open_spiel::cursor_go::CursorGoState::ToString().
MaxGameLength()
int open_spiel::cursor_go::MaxGameLength (int board_size) inline
Definition at line 77 of file cursor_go.h.
{ return board_size * board_size * 2; }
Referenced by open_spiel::cursor_go::CursorGoGame::MaxGameLength().
Variable Documentation
kCellStates
int open_spiel::cursor_go::kCellStates = 3 inline constexpr
Definition at line 63 of file cursor_go.h.
kDrawUtility
double open_spiel::cursor_go::kDrawUtility = 0 inline constexpr
Definition at line 67 of file cursor_go.h.
Referenced by open_spiel::cursor_go::CursorGoState::Returns().
kLossUtility
double open_spiel::cursor_go::kLossUtility = -1 inline constexpr
Definition at line 61 of file cursor_go.h.
Referenced by open_spiel::cursor_go::CursorGoGame::MinUtility(), open_spiel::cursor_go::CursorGoState::Returns(), and open_spiel::cursor_go::CursorGoGame::UtilitySum().
kNumDistinctActions
int open_spiel::cursor_go::kNumDistinctActions = kActionPass + 1 inline constexpr
Definition at line 70 of file cursor_go.h.
Referenced by open_spiel::cursor_go::CursorGoGame::NumDistinctActions().
kNumPlayers
int open_spiel::cursor_go::kNumPlayers = 2 inline constexpr
Definition at line 60 of file cursor_go.h.
Referenced by open_spiel::cursor_go::CursorGoGame::NumPlayers(), and open_spiel::cursor_go::CursorGoState::Returns().
kWinUtility
double open_spiel::cursor_go::kWinUtility = 1 inline constexpr
Definition at line 62 of file cursor_go.h.
Referenced by open_spiel::cursor_go::CursorGoGame::MaxUtility(), open_spiel::cursor_go::CursorGoState::Returns(), and open_spiel::cursor_go::CursorGoGame::UtilitySum().