open spiel: open_spiel::battleship Namespace Reference
open_spiel::battleship Namespace Reference
Classes
struct BattleshipConfiguration
class BattleshipGame
class BattleshipState
struct Cell
class CellAndDirection
struct GameMove
struct Ship
class ShipPlacement
Typedefs
using Shot = Cell
Functions
std::shared_ptr< const Game > Factory (const GameParameters &params)
REGISTER_SPIEL_GAME (kGameType, Factory)
RegisterSingleTensorObserver single_tensor (kGameType.short_name)
bool ExistsFeasiblePlacement (const BattleshipConfiguration &conf, std::vector< ShipPlacement > *partial_placement)
Variables
const GameType kGameType
constexpr int kMaxDimension = 10
constexpr int kDefaultBoardWidth = 10
constexpr int kDefaultBoardHeight = 10
constexpr const char * kDefaultShipSizes = "[2;3;3;4;5]"
constexpr const char * kDefaultShipValues = "[1.0;1.0;1.0;1.0;1.0]"
constexpr int kDefaultNumShots = 50
constexpr bool kDefaultAllowRepeatedShots = true
constexpr double kDefaultLossMultiplier = 1.0
Typedef Documentation
Shot
using open_spiel::battleship::Shot = Cell
Definition at line 41 of file battleship_types.h.
Function Documentation
ExistsFeasiblePlacement()
bool open_spiel::battleship::ExistsFeasiblePlacement (const BattleshipConfiguration & conf, std::vector< ShipPlacement > * partial_placement)
Definition at line 34 of file battleship_types.cc.
{
  // Debug-time check of preconditions.
  SPIEL_DCHECK_LE(partial_placement->size(), conf.ships.size());
  SPIEL_DCHECK_FALSE(IsOverlappingPlacement(*partial_placement));
  for (int index = 0; index < partial_placement->size(); ++index) {
    const ShipPlacement& placement = partial_placement->at(index);
    SPIEL_CHECK_EQ(placement.ship.id, conf.ships.at(index).id);
    SPIEL_CHECK_TRUE(
        placement.IsWithinBounds(conf.board_width, conf.board_height));
  }
  if (partial_placement->size() == conf.ships.size()) {
    // All ships have been placed. The placement is valid because of the
    // precondition.
    return true;
  } else {
    // We try to place the next ship in the board. We start by trying to place
    // the ship horizontally.
    //
    // Because of the precondition, partial_placement is a placement of a prefix
    // of the ships in conf.ships. Hence, the next ship that needs to be placed
    // is simply:
    const Ship& ship = conf.ships.at(partial_placement->size());
    // -- Horizontal placement.
    for (int row = 0; row < conf.board_height; ++row) {
      for (int col = 0; col < conf.board_width - ship.length + 1; ++col) {
        // First, we append the placement of the next ship to the partial
        // placement vector.
        partial_placement->push_back({ShipPlacement::Direction::Horizontal,
                                      /* ship = */ ship,
                                      /* tl_corner = */ Cell{row, col}});
        if (!IsOverlappingPlacement(*partial_placement) &&
            ExistsFeasiblePlacement(conf, partial_placement)) {
          // The new partial placement led to a solution. We honor the
          // postcondition and early-return sucess.
          partial_placement->pop_back();
          return true;
        } else {
          // The new partial placement does not lead to a solution. We remove
          // the placement and continue with the next placement.
          partial_placement->pop_back();
        }
      }
    }
    // -- Vertical placement.
    for (int row = 0; row < conf.board_height - ship.length + 1; ++row) {
      for (int col = 0; col < conf.board_width; ++col) {
        // First, we append the placement of the next ship to the partial
        // placement vector.
        partial_placement->push_back({ShipPlacement::Direction::Vertical,
                                      /* ship = */ ship,
                                      /* tl_corner = */ Cell{row, col}});
        if (!IsOverlappingPlacement(*partial_placement) &&
            ExistsFeasiblePlacement(conf, partial_placement)) {
          // The new partial placement led to a solution. We honor the
          // postcondition and early-return sucess.
          partial_placement->pop_back();
          return true;
        } else {
          // The new partial placement does not lead to a solution. We remove
          // the placement and continue with the next placement.
          partial_placement->pop_back();
        }
      }
    }
  }
  return false;
}
References open_spiel::battleship::BattleshipConfiguration::board_height, open_spiel::battleship::BattleshipConfiguration::board_width, ExistsFeasiblePlacement(), open_spiel::battleship::Ship::id, open_spiel::battleship::ShipPlacement::IsWithinBounds(), open_spiel::battleship::Ship::length, open_spiel::battleship::ShipPlacement::ship, open_spiel::battleship::BattleshipConfiguration::ships, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, SPIEL_DCHECK_FALSE, and SPIEL_DCHECK_LE.
Referenced by open_spiel::battleship::BattleshipGame::BattleshipGame(), ExistsFeasiblePlacement(), and open_spiel::battleship::BattleshipState::LegalActions().
Factory()
std::shared_ptr< const Game > open_spiel::battleship::Factory (const GameParameters & params)
Definition at line 818 of file battleship.cc.
{
  return std::make_shared<const BattleshipGame>(params);
}
References open_spiel::Factory().
REGISTER_SPIEL_GAME()
open_spiel::battleship::REGISTER_SPIEL_GAME (kGameType , Factory)
single_tensor()
RegisterSingleTensorObserver open_spiel::battleship::single_tensor (kGameType. short_name)
References open_spiel::kGameType, and single_tensor().
Referenced by single_tensor().
Variable Documentation
kDefaultAllowRepeatedShots
bool open_spiel::battleship::kDefaultAllowRepeatedShots = true inline constexpr
Definition at line 176 of file battleship.h.
kDefaultBoardHeight
int open_spiel::battleship::kDefaultBoardHeight = 10 inline constexpr
Definition at line 172 of file battleship.h.
kDefaultBoardWidth
int open_spiel::battleship::kDefaultBoardWidth = 10 inline constexpr
Definition at line 171 of file battleship.h.
kDefaultLossMultiplier
double open_spiel::battleship::kDefaultLossMultiplier = 1.0 inline constexpr
Definition at line 177 of file battleship.h.
kDefaultNumShots
int open_spiel::battleship::kDefaultNumShots = 50 inline constexpr
Definition at line 175 of file battleship.h.
kDefaultShipSizes
const char* open_spiel::battleship::kDefaultShipSizes = "[2;3;3;4;5]" inline constexpr
Definition at line 173 of file battleship.h.
kDefaultShipValues
const char* open_spiel::battleship::kDefaultShipValues = "[1.0;1.0;1.0;1.0;1.0]" inline constexpr
Definition at line 174 of file battleship.h.
kGameType
const GameType open_spiel::battleship::kGameType
Initial value:
{
     "battleship",
     "Battleship",
    GameType::Dynamics::kSequential,
    GameType::ChanceMode::kDeterministic,
    GameType::Information::kImperfectInformation,
    GameType::Utility::kGeneralSum,
    GameType::RewardModel::kTerminal,
     2,
     2,
     true,
     true,
     true,
     false,
    {{"board_width", GameParameter(kDefaultBoardWidth)},
     {"board_height", GameParameter(kDefaultBoardHeight)},
     {"ship_sizes", GameParameter(kDefaultShipSizes)},
     {"ship_values", GameParameter(kDefaultShipValues)},
     {"num_shots", GameParameter(kDefaultNumShots)},
     {"allow_repeated_shots", GameParameter(kDefaultAllowRepeatedShots)},
     {"loss_multiplier", GameParameter(kDefaultLossMultiplier)}}}
Definition at line 793 of file battleship.cc.
{
    /* short_name = */ "battleship",
    /* long_name = */ "Battleship",
    GameType::Dynamics::kSequential,
    GameType::ChanceMode::kDeterministic,
    GameType::Information::kImperfectInformation,
    GameType::Utility::kGeneralSum,
    GameType::RewardModel::kTerminal,
    /* max_num_players = */ 2,
    /* min_num_players = */ 2,
    /* provides_information_state_string = */ true,
    /* provides_information_state_tensor = */ true,
    /* provides_observation_string = */ true,
    /* provides_observation_tensor = */ false,
    /* parameter_specification = */
    {{"board_width", GameParameter(kDefaultBoardWidth)},
     {"board_height", GameParameter(kDefaultBoardHeight)},
     {"ship_sizes", GameParameter(kDefaultShipSizes)},
     {"ship_values", GameParameter(kDefaultShipValues)},
     {"num_shots", GameParameter(kDefaultNumShots)},
     {"allow_repeated_shots", GameParameter(kDefaultAllowRepeatedShots)},
     {"loss_multiplier", GameParameter(kDefaultLossMultiplier)}}};
kMaxDimension
int open_spiel::battleship::kMaxDimension = 10 constexpr
Definition at line 816 of file battleship.cc.
Referenced by open_spiel::battleship::BattleshipGame::BattleshipGame().