open spiel: absl::container_internal::internal_layout::adl_barrier Namespace Reference
absl::container_internal::internal_layout::adl_barrier Namespace Reference
Functions
template<class Needle , class... Ts>
constexpr size_t Find (Needle, Needle, Ts...)
template<class Needle , class T , class... Ts>
constexpr size_t Find (Needle, T, Ts...)
constexpr bool IsPow2 (size_t n)
constexpr size_t Align (size_t n, size_t m)
constexpr size_t Min (size_t a, size_t b)
constexpr size_t Max (size_t a)
template<class... Ts>
constexpr size_t Max (size_t a, size_t b, Ts... rest)
template<class T >
std::string TypeName ()
Function Documentation
Align()
size_t absl::container_internal::internal_layout::adl_barrier::Align (size_t n, size_t m) constexpr
Definition at line 283 of file layout.h.
{ return (n + m - 1) & ~(m - 1); }
References absl::n.
Referenced by absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Offset().
Find() [1/2]
template<class Needle , class... Ts> size_t absl::container_internal::internal_layout::adl_barrier::Find (Needle , Needle , Ts...) constexpr
Definition at line 269 of file layout.h.
{
  static_assert(!Contains<Needle, Ts...>(), "Duplicate element type");
  return 0;
}
Referenced by Find().
Find() [2/2]
template<class Needle , class T , class... Ts> size_t absl::container_internal::internal_layout::adl_barrier::Find (Needle , T , Ts...) constexpr
Definition at line 275 of file layout.h.
{
  return adl_barrier::Find(Needle(), Ts()...) + 1;
}
References Find().
IsPow2()
bool absl::container_internal::internal_layout::adl_barrier::IsPow2 (size_t n) constexpr
Definition at line 279 of file layout.h.
{ return !(n & (n - 1)); }
References absl::n.
Max() [1/2]
size_t absl::container_internal::internal_layout::adl_barrier::Max (size_t a) constexpr
Definition at line 287 of file layout.h.
{ return a; }
References absl::a.
Referenced by absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::Alignment(), and Max().
Max() [2/2]
template<class... Ts> size_t absl::container_internal::internal_layout::adl_barrier::Max (size_t a, size_t b, Ts... rest) constexpr
Definition at line 290 of file layout.h.
{
  return adl_barrier::Max(b < a ? a : b, rest...);
}
References absl::a, b, and Max().
Min()
size_t absl::container_internal::internal_layout::adl_barrier::Min (size_t a, size_t b) constexpr
Definition at line 285 of file layout.h.
{ return b < a ? b : a; }
References absl::a, and b.
TypeName()
template<class T > std::string absl::container_internal::internal_layout::adl_barrier::TypeName ()
Definition at line 295 of file layout.h.
                     {
  std::string out;
  int status = 0;
  char* demangled = nullptr;
#ifdef ABSL_INTERNAL_HAS_CXA_DEMANGLE
  demangled = abi::__cxa_demangle(typeid(T).name(), nullptr, nullptr, &status);
#endif
  if (status == 0 && demangled != nullptr) {  // Demangling succeeded.
    absl::StrAppend(&out, "<", demangled, ">");
    free(demangled);
  } else {
#if defined(__GXX_RTTI) || defined(_CPPRTTI)
    absl::StrAppend(&out, "<", typeid(T).name(), ">");
#endif
  }
  return out;
}
References name, absl::out, and absl::StrAppend().
Referenced by absl::container_internal::internal_layout::LayoutImpl< std::tuple< Elements... >, absl::index_sequence< SizeSeq... >, absl::index_sequence< OffsetSeq... > >::DebugString().