open spiel: absl::strings_internal Namespace Reference
absl::strings_internal Namespace Reference
Classes
struct AlphaNumBuffer
struct AlphaNumFormatterImpl
struct AppendUninitializedTraits
struct AppendUninitializedTraits< string_type, absl::void_t< decltype(std::declval< string_type & >() .__append_default_init(237))> >
struct base64_testcase
class BigUnsigned
class Charmap
class ConvertibleToStringView
class CordTestAccess
struct DefaultFormatter
struct DefaultFormatter< absl::string_view >
struct DefaultFormatter< char * >
struct DefaultFormatter< const char * >
struct DefaultFormatter< std::string >
struct DefaultFormatter< std::unique_ptr< ValueType > >
struct DefaultFormatter< ValueType * >
class DereferenceFormatterImpl
struct HasAbslStringify
struct HasAbslStringify< T, std::enable_if_t< std::is_void< decltype(AbslStringify(std::declval< strings_internal::UnimplementedSink & >(), std::declval< const T & >()))>::value > >
struct HasConstIterator
struct HasConstIterator< T, absl::void_t< typename T::const_iterator > >
struct HasEmplace
struct HasEmplace< T, absl::void_t< decltype(std::declval< T >().emplace())> >
struct HasMappedType
struct HasMappedType< T, absl::void_t< typename T::mapped_type > >
struct HasValueType
struct HasValueType< T, absl::void_t< typename T::value_type > >
struct IsArrayImpl
struct IsArrayImpl< A< T, N > >
struct IsBaseOfArrayImpl
struct IsBaseOfArrayImpl< A< T, N > >
struct IsBaseOfBitsetImpl
struct IsBaseOfBitsetImpl< B< N > >
struct IsBaseOfSpecializationImpl
struct IsBaseOfSpecializationImpl< C, T, absl::void_t< typename C::key_type, typename C::hasher, typename C::key_equal, typename C::allocator_type > >
struct IsBaseOfSpecializationImpl< C, T, absl::void_t< typename C::key_type, typename C::key_compare, typename C::allocator_type > >
struct IsBaseOfSpecializationImpl< C, T, absl::void_t< typename C::key_type, typename C::mapped_type, typename C::hasher, typename C::key_equal, typename C::allocator_type > >
struct IsBaseOfSpecializationImpl< C, T, absl::void_t< typename C::key_type, typename C::mapped_type, typename C::key_compare, typename C::allocator_type > >
struct IsBaseOfSpecializationImpl< C, T, absl::void_t< typename C::value_type, typename C::allocator_type > >
struct IsBaseOfSTLContainer
struct IsBitsetImpl
struct IsBitsetImpl< B< N > >
struct IsConvertibleToArrayImpl
struct IsConvertibleToArrayImpl< A< T, N > >
struct IsConvertibleToBitsetImpl
struct IsConvertibleToBitsetImpl< B< N > >
struct IsConvertibleToSpecializationImpl
struct IsConvertibleToSpecializationImpl< C, T, absl::void_t< typename C::key_type, typename C::hasher, typename C::key_equal, typename C::allocator_type > >
struct IsConvertibleToSpecializationImpl< C, T, absl::void_t< typename C::key_type, typename C::key_compare, typename C::allocator_type > >
struct IsConvertibleToSpecializationImpl< C, T, absl::void_t< typename C::key_type, typename C::mapped_type, typename C::hasher, typename C::key_equal, typename C::allocator_type > >
struct IsConvertibleToSpecializationImpl< C, T, absl::void_t< typename C::key_type, typename C::mapped_type, typename C::key_compare, typename C::allocator_type > >
struct IsConvertibleToSpecializationImpl< C, T, absl::void_t< typename C::value_type, typename C::allocator_type > >
struct IsConvertibleToSTLContainer
struct IsInitializerList
struct IsSpecializationImpl
struct IsSpecializationImpl< T< Args... >, T >
struct IsSTLContainer
struct IsStrictlyBaseOfAndConvertibleToSTLContainer
struct JoinTupleLoop
struct JoinTupleLoop< N, N >
class MaxSplitsImpl
struct NoFormatter
class OStringStream
class PairFormatterImpl
struct ParsedFloat
struct ResizeUninitializedTraits
struct ResizeUninitializedTraits< string_type, absl::void_t< decltype(std::declval< string_type & >() .__resize_default_init(237))> >
struct SelectDelimiter
struct SelectDelimiter< absl::string_view >
struct SelectDelimiter< char * >
struct SelectDelimiter< char >
struct SelectDelimiter< const char * >
struct SelectDelimiter< std::string >
class SplitIterator
class Splitter
struct SplitterIsConvertibleTo
struct SplitterIsConvertibleToImpl
struct SplitterIsConvertibleToImpl< C, true, false >
struct SplitterIsConvertibleToImpl< C, true, true >
class StreamFormatterImpl
struct StringConstant
class StringifySink
struct uint32_test_case
struct uint64_test_case
class UnimplementedSink
struct ViableSubstitution
Typedefs
template<typename C , template< typename... > class T>
using IsSpecialization = IsSpecializationImpl<absl::decay_t<C>, T>
template<typename C >
using IsArray = IsArrayImpl<absl::decay_t<C>>
template<typename C >
using IsBitset = IsBitsetImpl<absl::decay_t<C>>
template<typename C , template< typename... > class T>
using IsBaseOfSpecialization = IsBaseOfSpecializationImpl<absl::decay_t<C>, T>
template<typename C >
using IsBaseOfArray = IsBaseOfArrayImpl<absl::decay_t<C>>
template<typename C >
using IsBaseOfBitset = IsBaseOfBitsetImpl<absl::decay_t<C>>
template<typename C , template< typename... > class T>
using IsConvertibleToSpecialization
template<typename C >
using IsConvertibleToArray = IsConvertibleToArrayImpl<absl::decay_t<C>>
template<typename C >
using IsConvertibleToBitset = IsConvertibleToBitsetImpl<absl::decay_t<C>>
using FixedMapping
Enumerations
enum class FloatType { kNumber , kInfinity , kNan }
enum { kMaxEncodedUTF8Size = 4 }
Functions
constexpr Charmap UpperCharmap ()
constexpr Charmap LowerCharmap ()
constexpr Charmap DigitCharmap ()
constexpr Charmap AlphaCharmap ()
constexpr Charmap AlnumCharmap ()
constexpr Charmap XDigitCharmap ()
constexpr Charmap PrintCharmap ()
constexpr Charmap SpaceCharmap ()
constexpr Charmap CntrlCharmap ()
constexpr Charmap BlankCharmap ()
constexpr Charmap GraphCharmap ()
constexpr Charmap PunctCharmap ()
template<int N, int M>
int Compare (const BigUnsigned< N > &lhs, const BigUnsigned< M > &rhs)
template<int N, int M>
bool operator== (const BigUnsigned< N > &lhs, const BigUnsigned< M > &rhs)
template<int N, int M>
bool operator!= (const BigUnsigned< N > &lhs, const BigUnsigned< M > &rhs)
template<int N, int M>
bool operator< (const BigUnsigned< N > &lhs, const BigUnsigned< M > &rhs)
template<int N, int M>
bool operator> (const BigUnsigned< N > &lhs, const BigUnsigned< M > &rhs)
template<int N, int M>
bool operator<= (const BigUnsigned< N > &lhs, const BigUnsigned< M > &rhs)
template<int N, int M>
bool operator>= (const BigUnsigned< N > &lhs, const BigUnsigned< M > &rhs)
template<int N>
std::ostream & operator<< (std::ostream &os, const BigUnsigned< N > &num)
TEST (BigUnsigned, ShiftLeft)
TEST (BigUnsigned, MultiplyByUint32)
TEST (BigUnsigned, MultiplyByBigUnsigned)
TEST (BigUnsigned, MultiplyByOverflow)
TEST (BigUnsigned, FiveToTheNth)
TEST (BigUnsigned, TenToTheNth)
template<int base>
strings_internal::ParsedFloat ParseFloat (const char *begin, const char *end, chars_format format_flags)
template ParsedFloat ParseFloat< 10 > (const char *begin, const char *end, chars_format format_flags)
template ParsedFloat ParseFloat< 16 > (const char *begin, const char *end, chars_format format_flags)
template<int base>
ParsedFloat ParseFloat (const char *begin, const char *end, absl::chars_format format_flags)
uint8_t CappedDamerauLevenshteinDistance (absl::string_view s1, absl::string_view s2, uint8_t cutoff)
size_t CalculateBase64EscapedLenInternal (size_t input_len, bool do_padding)
size_t Base64EscapeInternal (const unsigned char *src, size_t szsrc, char *dest, size_t szdest, const char *base64, bool do_padding)
template<typename String >
void Base64EscapeInternal (const unsigned char *src, size_t szsrc, String *dest, bool do_padding, const char *base64_chars)
const std::array< base64_testcase, 5 > & base64_strings ()
int memcasecmp (const char *s1, const char *s2, size_t len)
char * memdup (const char *s, size_t slen)
char * memrchr (const char *s, int c, size_t slen)
size_t memspn (const char *s, size_t slen, const char *accept)
size_t memcspn (const char *s, size_t slen, const char *reject)
char * mempbrk (const char *s, size_t slen, const char *accept)
const char * memmatch (const char *phaystack, size_t haylen, const char *pneedle, size_t neelen)
char * memcat (char *dest, size_t destlen, const char *src, size_t srclen)
template<bool case_sensitive>
const char * int_memmatch (const char *haystack, size_t haylen, const char *needle, size_t neelen)
const char * memstr (const char *phaystack, size_t haylen, const char *pneedle)
const char * memcasestr (const char *phaystack, size_t haylen, const char *pneedle)
const char * memmem (const char *phaystack, size_t haylen, const char *pneedle, size_t needlelen)
const char * memcasemem (const char *phaystack, size_t haylen, const char *pneedle, size_t needlelen)
template<typename IntType >
bool Itoa (IntType value, int base, std::string *destination)
const std::array< uint32_test_case, 27 > & strtouint32_test_cases ()
const std::array< uint64_test_case, 34 > & strtouint64_test_cases ()
double Pow10 (int exp)
template<typename string_type >
constexpr bool STLStringSupportsNontrashingResize (string_type *)
template<typename string_type , typename = void>
void STLStringResizeUninitialized (string_type *s, size_t new_size)
template<typename string_type >
void STLStringReserveAmortized (string_type *s, size_t new_size)
template<typename string_type >
void STLStringResizeUninitializedAmortized (string_type *s, size_t new_size)
template<typename Iterator , typename Formatter >
std::string JoinAlgorithm (Iterator start, Iterator end, absl::string_view s, Formatter &&f)
template<typename Iterator , typename = typename std::enable_if<std::is_convertible< typename std::iterator_traits<Iterator>::iterator_category, std::forward_iterator_tag>::value>::type>
std::string JoinAlgorithm (Iterator start, Iterator end, absl::string_view s, NoFormatter)
template<typename... T, typename Formatter >
std::string JoinAlgorithm (const std::tuple< T... > &tup, absl::string_view sep, Formatter &&fmt)
template<typename Iterator >
std::string JoinRange (Iterator first, Iterator last, absl::string_view separator)
template<typename Range , typename Formatter >
std::string JoinRange (const Range &range, absl::string_view separator, Formatter &&fmt)
template<typename Range >
std::string JoinRange (const Range &range, absl::string_view separator)
std::false_type IsInitializerListDispatch (...)
template<typename T >
std::true_type IsInitializerListDispatch (std::initializer_list< T > *)
template<typename T >
constexpr StringConstant< T > MakeStringConstant (T)
template<typename T >
string_view ExtractStringification (StringifySink &sink, const T &v)
size_t EncodeUTF8Char (char *buffer, char32_t utf8_char)
std::string CatPieces (std::initializer_list< absl::string_view > pieces)
void AppendPieces (std::string *dest, std::initializer_list< absl::string_view > pieces)
int ApplySubstitutions (absl::string_view s, std::vector< strings_internal::ViableSubstitution > *subs_ptr, std::string *result_ptr)
template<typename StrToStrMapping >
std::vector< ViableSubstitution > FindSubstitutions (absl::string_view s, const StrToStrMapping &replacements)
int ApplySubstitutions (absl::string_view s, std::vector< ViableSubstitution > *subs_ptr, std::string *result_ptr)
Variables
ABSL_DLL const uint32_t kFiveToNth [14]
ABSL_DLL const uint32_t kTenToNth [10]
constexpr int kMaxSmallPowerOfFive = 13
constexpr int kMaxSmallPowerOfTen = 9
ABSL_CONST_INIT const char kBase64Chars []
Typedef Documentation
FixedMapping
using absl::strings_internal::FixedMapping
Initial value:
    std::initializer_list<std::pair<absl::string_view, absl::string_view>>
Definition at line 23 of file str_replace.cc.
IsArray
template<typename C > using absl::strings_internal::IsArray = IsArrayImpl<absl::decay_t<C>>
Definition at line 58 of file stl_type_traits.h.
IsBaseOfArray
template<typename C > using absl::strings_internal::IsBaseOfArray = IsBaseOfArrayImpl<absl::decay_t<C>>
Definition at line 134 of file stl_type_traits.h.
IsBaseOfBitset
template<typename C > using absl::strings_internal::IsBaseOfBitset = IsBaseOfBitsetImpl<absl::decay_t<C>>
Definition at line 141 of file stl_type_traits.h.
IsBaseOfSpecialization
template<typename C , template< typename... > class T> using absl::strings_internal::IsBaseOfSpecialization = IsBaseOfSpecializationImpl<absl::decay_t<C>, T>
Definition at line 126 of file stl_type_traits.h.
IsBitset
template<typename C > using absl::strings_internal::IsBitset = IsBitsetImpl<absl::decay_t<C>>
Definition at line 65 of file stl_type_traits.h.
IsConvertibleToArray
template<typename C > using absl::strings_internal::IsConvertibleToArray = IsConvertibleToArrayImpl<absl::decay_t<C>>
Definition at line 212 of file stl_type_traits.h.
IsConvertibleToBitset
template<typename C > using absl::strings_internal::IsConvertibleToBitset = IsConvertibleToBitsetImpl<absl::decay_t<C>>
Definition at line 220 of file stl_type_traits.h.
IsConvertibleToSpecialization
template<typename C , template< typename... > class T> using absl::strings_internal::IsConvertibleToSpecialization
Initial value:
    IsConvertibleToSpecializationImpl<absl::decay_t<C>, T>
Definition at line 203 of file stl_type_traits.h.
IsSpecialization
template<typename C , template< typename... > class T> using absl::strings_internal::IsSpecialization = IsSpecializationImpl<absl::decay_t<C>, T>
Definition at line 51 of file stl_type_traits.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kMaxEncodedUTF8Size
Definition at line 43 of file utf8.h.
{ kMaxEncodedUTF8Size = 4 };
FloatType
enum class absl::strings_internal::FloatType strong
Enumerator
kNumber
kInfinity
kNan
Definition at line 28 of file charconv_parse.h.
{ kNumber, kInfinity, kNan };
Function Documentation
AlnumCharmap()
Charmap absl::strings_internal::AlnumCharmap () constexpr
Definition at line 141 of file char_map.h.
{ return DigitCharmap() | AlphaCharmap(); }
References AlphaCharmap(), and DigitCharmap().
AlphaCharmap()
Charmap absl::strings_internal::AlphaCharmap () constexpr
Definition at line 140 of file char_map.h.
{ return LowerCharmap() | UpperCharmap(); }
References LowerCharmap(), and UpperCharmap().
Referenced by AlnumCharmap().
AppendPieces()
void absl::strings_internal::AppendPieces (std::string * dest, std::initializer_list< absl::string_view > pieces)
Definition at line 172 of file str_cat.cc.
{
  size_t old_size = dest->size();
  size_t total_size = old_size;
  for (absl::string_view piece : pieces) {
    ASSERT_NO_OVERLAP(*dest, piece);
    total_size += piece.size();
  }
  strings_internal::STLStringResizeUninitializedAmortized(dest, total_size);
  char* const begin = &(*dest)[0];
  char* out = begin + old_size;
  for (absl::string_view piece : pieces) {
    const size_t this_size = piece.size();
    if (this_size != 0) {
      memcpy(out, piece.data(), this_size);
      out += this_size;
    }
  }
  assert(out == begin + dest->size());
}
References ASSERT_NO_OVERLAP, absl::out, and STLStringResizeUninitializedAmortized().
Referenced by absl::StrAppend().
ApplySubstitutions() [1/2]
int absl::strings_internal::ApplySubstitutions (absl::string_view s, std::vector< strings_internal::ViableSubstitution > * subs_ptr, std::string * result_ptr)
Definition at line 29 of file str_replace.cc.
{
  auto& subs = *subs_ptr;
  int substitutions = 0;
  size_t pos = 0;
  while (!subs.empty()) {
    auto& sub = subs.back();
    if (sub.offset >= pos) {
      if (pos <= s.size()) {
        StrAppend(result_ptr, s.substr(pos, sub.offset - pos), sub.replacement);
      }
      pos = sub.offset + sub.old.size();
      substitutions += 1;
    }
    sub.offset = s.find(sub.old, pos);
    if (sub.offset == s.npos) {
      subs.pop_back();
    } else {
      // Insertion sort to ensure the last ViableSubstitution continues to be
      // before all the others.
      size_t index = subs.size();
      while (--index && subs[index - 1].OccursBefore(subs[index])) {
        std::swap(subs[index], subs[index - 1]);
      }
    }
  }
  result_ptr->append(s.data() + pos, s.size() - pos);
  return substitutions;
}
References absl::s, and absl::StrAppend().
Referenced by absl::StrReplaceAll(), and absl::StrReplaceAll().
ApplySubstitutions() [2/2]
int absl::strings_internal::ApplySubstitutions (absl::string_view s, std::vector< ViableSubstitution > * subs_ptr, std::string * result_ptr)
base64_strings()
const std::array< base64_testcase, 5 > & absl::strings_internal::base64_strings () inline
Definition at line 33 of file escaping_test_common.h.
{
  static const std::array<base64_testcase, 5> testcase{{
      // Some google quotes
      // Cyphertext created with "uuencode (GNU sharutils) 4.6.3"
      // (Note that we're testing the websafe encoding, though, so if
      // you add messages, be sure to run "tr -- '+/' '-_'" on the output)
      { "I was always good at math and science, and I never realized "
        "that was unusual or somehow undesirable. So one of the things "
        "I care a lot about is helping to remove that stigma, "
        "to show girls that you can be feminine, you can like the things "
        "that girls like, but you can also be really good at technology. "
        "You can be really good at building things."
        " - Marissa Meyer, Newsweek, 2010-12-22" "\n",
        "SSB3YXMgYWx3YXlzIGdvb2QgYXQgbWF0aCBhbmQgc2NpZW5jZSwgYW5kIEkg"
        "bmV2ZXIgcmVhbGl6ZWQgdGhhdCB3YXMgdW51c3VhbCBvciBzb21laG93IHVu"
        "ZGVzaXJhYmxlLiBTbyBvbmUgb2YgdGhlIHRoaW5ncyBJIGNhcmUgYSBsb3Qg"
        "YWJvdXQgaXMgaGVscGluZyB0byByZW1vdmUgdGhhdCBzdGlnbWEsIHRvIHNo"
        "b3cgZ2lybHMgdGhhdCB5b3UgY2FuIGJlIGZlbWluaW5lLCB5b3UgY2FuIGxp"
        "a2UgdGhlIHRoaW5ncyB0aGF0IGdpcmxzIGxpa2UsIGJ1dCB5b3UgY2FuIGFs"
        "c28gYmUgcmVhbGx5IGdvb2QgYXQgdGVjaG5vbG9neS4gWW91IGNhbiBiZSBy"
        "ZWFsbHkgZ29vZCBhdCBidWlsZGluZyB0aGluZ3MuIC0gTWFyaXNzYSBNZXll"
        "ciwgTmV3c3dlZWssIDIwMTAtMTItMjIK" },
      { "Typical first year for a new cluster: "
        "~0.5 overheating "
        "~1 PDU failure "
        "~1 rack-move "
        "~1 network rewiring "
        "~20 rack failures "
        "~5 racks go wonky "
        "~8 network maintenances "
        "~12 router reloads "
        "~3 router failures "
        "~dozens of minor 30-second blips for dns "
        "~1000 individual machine failures "
        "~thousands of hard drive failures "
        "slow disks, bad memory, misconfigured machines, flaky machines, etc."
        " - Jeff Dean, The Joys of Real Hardware" "\n",
        "VHlwaWNhbCBmaXJzdCB5ZWFyIGZvciBhIG5ldyBjbHVzdGVyOiB-MC41IG92"
        "ZXJoZWF0aW5nIH4xIFBEVSBmYWlsdXJlIH4xIHJhY2stbW92ZSB-MSBuZXR3"
        "b3JrIHJld2lyaW5nIH4yMCByYWNrIGZhaWx1cmVzIH41IHJhY2tzIGdvIHdv"
        "bmt5IH44IG5ldHdvcmsgbWFpbnRlbmFuY2VzIH4xMiByb3V0ZXIgcmVsb2Fk"
        "cyB-MyByb3V0ZXIgZmFpbHVyZXMgfmRvemVucyBvZiBtaW5vciAzMC1zZWNv"
        "bmQgYmxpcHMgZm9yIGRucyB-MTAwMCBpbmRpdmlkdWFsIG1hY2hpbmUgZmFp"
        "bHVyZXMgfnRob3VzYW5kcyBvZiBoYXJkIGRyaXZlIGZhaWx1cmVzIHNsb3cg"
        "ZGlza3MsIGJhZCBtZW1vcnksIG1pc2NvbmZpZ3VyZWQgbWFjaGluZXMsIGZs"
        "YWt5IG1hY2hpbmVzLCBldGMuIC0gSmVmZiBEZWFuLCBUaGUgSm95cyBvZiBS"
        "ZWFsIEhhcmR3YXJlCg" },
      { "I'm the head of the webspam team at Google.  "
        "That means that if you type your name into Google and get porn back, "
        "it's my fault. Unless you're a porn star, in which case porn is a "
        "completely reasonable response."
        " - Matt Cutts, Google Plus" "\n",
        "SSdtIHRoZSBoZWFkIG9mIHRoZSB3ZWJzcGFtIHRlYW0gYXQgR29vZ2xlLiAg"
        "VGhhdCBtZWFucyB0aGF0IGlmIHlvdSB0eXBlIHlvdXIgbmFtZSBpbnRvIEdv"
        "b2dsZSBhbmQgZ2V0IHBvcm4gYmFjaywgaXQncyBteSBmYXVsdC4gVW5sZXNz"
        "IHlvdSdyZSBhIHBvcm4gc3RhciwgaW4gd2hpY2ggY2FzZSBwb3JuIGlzIGEg"
        "Y29tcGxldGVseSByZWFzb25hYmxlIHJlc3BvbnNlLiAtIE1hdHQgQ3V0dHMs"
        "IEdvb2dsZSBQbHVzCg" },
      { "It will still be a long time before machines approach human "
        "intelligence. "
        "But luckily, machines don't actually have to be intelligent; "
        "they just have to fake it. Access to a wealth of information, "
        "combined with a rudimentary decision-making capacity, "
        "can often be almost as useful. Of course, the results are better yet "
        "when coupled with intelligence. A reference librarian with access to "
        "a good search engine is a formidable tool."
        " - Craig Silverstein, Siemens Pictures of the Future, Spring 2004"
        "\n",
        "SXQgd2lsbCBzdGlsbCBiZSBhIGxvbmcgdGltZSBiZWZvcmUgbWFjaGluZXMg"
        "YXBwcm9hY2ggaHVtYW4gaW50ZWxsaWdlbmNlLiBCdXQgbHVja2lseSwgbWFj"
        "aGluZXMgZG9uJ3QgYWN0dWFsbHkgaGF2ZSB0byBiZSBpbnRlbGxpZ2VudDsg"
        "dGhleSBqdXN0IGhhdmUgdG8gZmFrZSBpdC4gQWNjZXNzIHRvIGEgd2VhbHRo"
        "IG9mIGluZm9ybWF0aW9uLCBjb21iaW5lZCB3aXRoIGEgcnVkaW1lbnRhcnkg"
        "ZGVjaXNpb24tbWFraW5nIGNhcGFjaXR5LCBjYW4gb2Z0ZW4gYmUgYWxtb3N0"
        "IGFzIHVzZWZ1bC4gT2YgY291cnNlLCB0aGUgcmVzdWx0cyBhcmUgYmV0dGVy"
        "IHlldCB3aGVuIGNvdXBsZWQgd2l0aCBpbnRlbGxpZ2VuY2UuIEEgcmVmZXJl"
        "bmNlIGxpYnJhcmlhbiB3aXRoIGFjY2VzcyB0byBhIGdvb2Qgc2VhcmNoIGVu"
        "Z2luZSBpcyBhIGZvcm1pZGFibGUgdG9vbC4gLSBDcmFpZyBTaWx2ZXJzdGVp"
        "biwgU2llbWVucyBQaWN0dXJlcyBvZiB0aGUgRnV0dXJlLCBTcHJpbmcgMjAw"
        "NAo" },
      // Degenerate edge case
      { "",
        "" },
  }};
  return testcase;
}
Base64EscapeInternal() [1/2]
size_t absl::strings_internal::Base64EscapeInternal (const unsigned char * src, size_t szsrc, char * dest, size_t szdest, const char * base64, bool do_padding)
Definition at line 65 of file escaping.cc.
{
  static const char kPad64 = '=';
  if (szsrc * 4 > szdest * 3) return 0;
  char* cur_dest = dest;
  const unsigned char* cur_src = src;
  char* const limit_dest = dest + szdest;
  const unsigned char* const limit_src = src + szsrc;
  // (from https://tools.ietf.org/html/rfc3548)
  // Special processing is performed if fewer than 24 bits are available
  // at the end of the data being encoded.  A full encoding quantum is
  // always completed at the end of a quantity.  When fewer than 24 input
  // bits are available in an input group, zero bits are added (on the
  // right) to form an integral number of 6-bit groups.
  //
  // If do_padding is true, padding at the end of the data is performed. This
  // output padding uses the '=' character.
  // Three bytes of data encodes to four characters of cyphertext.
  // So we can pump through three-byte chunks atomically.
  if (szsrc >= 3) {                    // "limit_src - 3" is UB if szsrc < 3.
    while (cur_src < limit_src - 3) {  // While we have >= 32 bits.
      uint32_t in = absl::big_endian::Load32(cur_src) >> 8;
      cur_dest[0] = base64[in >> 18];
      in &= 0x3FFFF;
      cur_dest[1] = base64[in >> 12];
      in &= 0xFFF;
      cur_dest[2] = base64[in >> 6];
      in &= 0x3F;
      cur_dest[3] = base64[in];
      cur_dest += 4;
      cur_src += 3;
    }
  }
  // To save time, we didn't update szdest or szsrc in the loop.  So do it now.
  szdest = static_cast<size_t>(limit_dest - cur_dest);
  szsrc = static_cast<size_t>(limit_src - cur_src);
  /* now deal with the tail (<=3 bytes) */
  switch (szsrc) {
    case 0:
      // Nothing left; nothing more to do.
      break;
    case 1: {
      // One byte left: this encodes to two characters, and (optionally)
      // two pad characters to round out the four-character cypherblock.
      if (szdest < 2) return 0;
      uint32_t in = cur_src[0];
      cur_dest[0] = base64[in >> 2];
      in &= 0x3;
      cur_dest[1] = base64[in << 4];
      cur_dest += 2;
      szdest -= 2;
      if (do_padding) {
        if (szdest < 2) return 0;
        cur_dest[0] = kPad64;
        cur_dest[1] = kPad64;
        cur_dest += 2;
        szdest -= 2;
      }
      break;
    }
    case 2: {
      // Two bytes left: this encodes to three characters, and (optionally)
      // one pad character to round out the four-character cypherblock.
      if (szdest < 3) return 0;
      uint32_t in = absl::big_endian::Load16(cur_src);
      cur_dest[0] = base64[in >> 10];
      in &= 0x3FF;
      cur_dest[1] = base64[in >> 4];
      in &= 0x00F;
      cur_dest[2] = base64[in << 2];
      cur_dest += 3;
      szdest -= 3;
      if (do_padding) {
        if (szdest < 1) return 0;
        cur_dest[0] = kPad64;
        cur_dest += 1;
        szdest -= 1;
      }
      break;
    }
    case 3: {
      // Three bytes left: same as in the big loop above.  We can't do this in
      // the loop because the loop above always reads 4 bytes, and the fourth
      // byte is past the end of the input.
      if (szdest < 4) return 0;
      uint32_t in =
          (uint32_t{cur_src[0]} << 16) + absl::big_endian::Load16(cur_src + 1);
      cur_dest[0] = base64[in >> 18];
      in &= 0x3FFFF;
      cur_dest[1] = base64[in >> 12];
      in &= 0xFFF;
      cur_dest[2] = base64[in >> 6];
      in &= 0x3F;
      cur_dest[3] = base64[in];
      cur_dest += 4;
      szdest -= 4;
      break;
    }
    default:
      // Should not be reached: blocks of 4 bytes are handled
      // in the while loop before this switch statement.
      ABSL_RAW_LOG(FATAL, "Logic problem? szsrc = %zu", szsrc);
      break;
  }
  return static_cast<size_t>(cur_dest - dest);
}
References ABSL_RAW_LOG, in, absl::big_endian::Load16(), and absl::big_endian::Load32().
Referenced by absl::Base64Escape(), absl::Base64Escape(), Base64EscapeInternal(), absl::WebSafeBase64Escape(), and absl::WebSafeBase64Escape().
Base64EscapeInternal() [2/2]
template<typename String > void absl::strings_internal::Base64EscapeInternal (const unsigned char * src, size_t szsrc, String * dest, bool do_padding, const char * base64_chars)
Definition at line 40 of file escaping.h.
{
  const size_t calc_escaped_size =
      CalculateBase64EscapedLenInternal(szsrc, do_padding);
  STLStringResizeUninitialized(dest, calc_escaped_size);
  const size_t escaped_len = Base64EscapeInternal(
      src, szsrc, &(*dest)[0], dest->size(), base64_chars, do_padding);
  assert(calc_escaped_size == escaped_len);
  dest->erase(escaped_len);
}
References Base64EscapeInternal(), CalculateBase64EscapedLenInternal(), and STLStringResizeUninitialized().
BlankCharmap()
Charmap absl::strings_internal::BlankCharmap () constexpr
Definition at line 150 of file char_map.h.
{ return Charmap::FromString("\t "); }
References absl::strings_internal::Charmap::FromString().
CalculateBase64EscapedLenInternal()
size_t absl::strings_internal::CalculateBase64EscapedLenInternal (size_t input_len, bool do_padding)
Definition at line 27 of file escaping.cc.
{
  // Base64 encodes three bytes of input at a time. If the input is not
  // divisible by three, we pad as appropriate.
  //
  // Base64 encodes each three bytes of input into four bytes of output.
  size_t len = (input_len / 3) * 4;
  // Since all base 64 input is an integral number of octets, only the following
  // cases can arise:
  if (input_len % 3 == 0) {
    // (from https://tools.ietf.org/html/rfc3548)
    // (1) the final quantum of encoding input is an integral multiple of 24
    // bits; here, the final unit of encoded output will be an integral
    // multiple of 4 characters with no "=" padding,
  } else if (input_len % 3 == 1) {
    // (from https://tools.ietf.org/html/rfc3548)
    // (2) the final quantum of encoding input is exactly 8 bits; here, the
    // final unit of encoded output will be two characters followed by two
    // "=" padding characters, or
    len += 2;
    if (do_padding) {
      len += 2;
    }
  } else {  // (input_len % 3 == 2)
    // (from https://tools.ietf.org/html/rfc3548)
    // (3) the final quantum of encoding input is exactly 16 bits; here, the
    // final unit of encoded output will be three characters followed by one
    // "=" padding character.
    len += 3;
    if (do_padding) {
      len += 1;
    }
  }
  assert(len >= input_len);  // make sure we didn't overflow
  return len;
}
References len.
Referenced by Base64EscapeInternal().
CappedDamerauLevenshteinDistance()
uint8_t absl::strings_internal::CappedDamerauLevenshteinDistance (absl::string_view s1, absl::string_view s2, uint8_t cutoff)
Definition at line 34 of file damerau_levenshtein_distance.cc.
{
  const uint8_t MAX_SIZE = 100;
  const uint8_t _cutoff = std::min(MAX_SIZE, cutoff);
  const uint8_t cutoff_plus_1 = static_cast<uint8_t>(_cutoff + 1);
  if (s1.size() > s2.size()) std::swap(s1, s2);
  if (s1.size() + _cutoff < s2.size() || s2.size() > MAX_SIZE)
    return cutoff_plus_1;
  if (s1.empty())
    return static_cast<uint8_t>(s2.size());
  // Lower diagonal bound: y = x - lower_diag
  const uint8_t lower_diag =
      _cutoff - static_cast<uint8_t>(s2.size() - s1.size());
  // Upper diagonal bound: y = x + upper_diag
  const uint8_t upper_diag = _cutoff;
  // d[i][j] is the number of edits required to convert s1[0, i] to s2[0, j]
  std::array<std::array<uint8_t, MAX_SIZE + 2>, MAX_SIZE + 2> d;
  std::iota(d[0].begin(), d[0].begin() + upper_diag + 1, 0);
  d[0][cutoff_plus_1] = cutoff_plus_1;
  for (size_t i = 1; i <= s1.size(); ++i) {
    // Deduce begin of relevant window.
    size_t j_begin = 1;
    if (i > lower_diag) {
      j_begin = i - lower_diag;
      d[i][j_begin - 1] = cutoff_plus_1;
    } else {
      d[i][0] = static_cast<uint8_t>(i);
    }
    // Deduce end of relevant window.
    size_t j_end = i + upper_diag;
    if (j_end > s2.size()) {
      j_end = s2.size();
    } else {
      d[i][j_end + 1] = cutoff_plus_1;
    }
    for (size_t j = j_begin; j <= j_end; ++j) {
      const uint8_t deletion_distance = d[i - 1][j] + 1;
      const uint8_t insertion_distance = d[i][j - 1] + 1;
      const uint8_t mismatched_tail_cost = s1[i - 1] == s2[j - 1] ? 0 : 1;
      const uint8_t mismatch_distance = d[i - 1][j - 1] + mismatched_tail_cost;
      uint8_t transposition_distance = _cutoff + 1;
      if (i > 1 && j > 1 && s1[i - 1] == s2[j - 2] && s1[i - 2] == s2[j - 1])
        transposition_distance = d[i - 2][j - 2] + 1;
      d[i][j] = std::min({cutoff_plus_1, deletion_distance, insertion_distance,
                          mismatch_distance, transposition_distance});
    }
  }
  return d[s1.size()][s2.size()];
}
References begin, absl::d, absl::string_view::empty(), absl::i, and absl::string_view::size().
Referenced by absl::flags_internal::GetMisspellingHints().
CatPieces()
std::string absl::strings_internal::CatPieces (std::initializer_list< absl::string_view > pieces)
Definition at line 144 of file str_cat.cc.
{
  std::string result;
  size_t total_size = 0;
  for (absl::string_view piece : pieces) total_size += piece.size();
  strings_internal::STLStringResizeUninitialized(&result, total_size);
  char* const begin = &result[0];
  char* out = begin;
  for (absl::string_view piece : pieces) {
    const size_t this_size = piece.size();
    if (this_size != 0) {
      memcpy(out, piece.data(), this_size);
      out += this_size;
    }
  }
  assert(out == begin + result.size());
  return result;
}
References begin, absl::out, and STLStringResizeUninitialized().
Referenced by absl::StrCat().
CntrlCharmap()
Charmap absl::strings_internal::CntrlCharmap () constexpr
Definition at line 147 of file char_map.h.
{
  return Charmap::Range(0, 0x7f) & ~PrintCharmap();
}
References absl::strings_internal::Charmap::Range().
Compare()
template<int N, int M> int absl::strings_internal::Compare (const BigUnsigned< N > & lhs, const BigUnsigned< M > & rhs)
Definition at line 353 of file charconv_bigint.h.
{
  int limit = (std::max)(lhs.size(), rhs.size());
  for (int i = limit - 1; i >= 0; --i) {
    const uint32_t lhs_word = lhs.GetWord(i);
    const uint32_t rhs_word = rhs.GetWord(i);
    if (lhs_word < rhs_word) {
      return -1;
    } else if (lhs_word > rhs_word) {
      return 1;
    }
  }
  return 0;
}
References absl::strings_internal::BigUnsigned< max_words >::GetWord(), absl::i, and absl::strings_internal::BigUnsigned< max_words >::size().
Referenced by operator<().
DigitCharmap()
Charmap absl::strings_internal::DigitCharmap () constexpr
Definition at line 139 of file char_map.h.
{ return Charmap::Range('0', '9'); }
References absl::strings_internal::Charmap::Range().
Referenced by AlnumCharmap(), and XDigitCharmap().
EncodeUTF8Char()
size_t absl::strings_internal::EncodeUTF8Char (char * buffer, char32_t utf8_char)
Definition at line 23 of file utf8.cc.
{
  if (utf8_char <= 0x7F) {
    *buffer = static_cast<char>(utf8_char);
    return 1;
  } else if (utf8_char <= 0x7FF) {
    buffer[1] = static_cast<char>(0x80 | (utf8_char & 0x3F));
    utf8_char >>= 6;
    buffer[0] = static_cast<char>(0xC0 | utf8_char);
    return 2;
  } else if (utf8_char <= 0xFFFF) {
    buffer[2] = static_cast<char>(0x80 | (utf8_char & 0x3F));
    utf8_char >>= 6;
    buffer[1] = static_cast<char>(0x80 | (utf8_char & 0x3F));
    utf8_char >>= 6;
    buffer[0] = static_cast<char>(0xE0 | utf8_char);
    return 3;
  } else {
    buffer[3] = static_cast<char>(0x80 | (utf8_char & 0x3F));
    utf8_char >>= 6;
    buffer[2] = static_cast<char>(0x80 | (utf8_char & 0x3F));
    utf8_char >>= 6;
    buffer[1] = static_cast<char>(0x80 | (utf8_char & 0x3F));
    utf8_char >>= 6;
    buffer[0] = static_cast<char>(0xF0 | utf8_char);
    return 4;
  }
}
Referenced by absl::ABSL_NAMESPACE_BEGIN::CUnescapeInternal().
ExtractStringification()
template<typename T > string_view absl::strings_internal::ExtractStringification (StringifySink & sink, const T & v)
Definition at line 47 of file stringify_sink.h.
{
  AbslStringify(sink, v);
  return sink.buffer_;
}
FindSubstitutions()
template<typename StrToStrMapping > std::vector< ViableSubstitution > absl::strings_internal::FindSubstitutions (absl::string_view s, const StrToStrMapping & replacements)
Definition at line 158 of file str_replace.h.
{
  std::vector<ViableSubstitution> subs;
  subs.reserve(replacements.size());
  for (const auto& rep : replacements) {
    using std::get;
    absl::string_view old(get<0>(rep));
    size_t pos = s.find(old);
    if (pos == s.npos) continue;
    // Ignore attempts to replace "". This condition is almost never true,
    // but above condition is frequently true. That's why we test for this
    // now and not before.
    if (old.empty()) continue;
    subs.emplace_back(old, get<1>(rep), pos);
    // Insertion sort to ensure the last ViableSubstitution comes before
    // all the others.
    size_t index = subs.size();
    while (--index && subs[index - 1].OccursBefore(subs[index])) {
      std::swap(subs[index], subs[index - 1]);
    }
  }
  return subs;
}
References absl::string_view::empty(), rep, and absl::s.
Referenced by absl::StrReplaceAll(), and absl::StrReplaceAll().
GraphCharmap()
Charmap absl::strings_internal::GraphCharmap () constexpr
Definition at line 151 of file char_map.h.
{ return PrintCharmap() & ~SpaceCharmap(); }
References PrintCharmap().
Referenced by PunctCharmap().
int_memmatch()
template<bool case_sensitive> const char * absl::strings_internal::int_memmatch (const char * haystack, size_t haylen, const char * needle, size_t neelen)
Definition at line 89 of file memutil.h.
{
  if (0 == neelen) {
    return haystack;  // even if haylen is 0
  }
  const char* hayend = haystack + haylen;
  const char* needlestart = needle;
  const char* needleend = needlestart + neelen;
  for (; haystack < hayend; ++haystack) {
    char hay = case_sensitive
                   ? *haystack
                   : absl::ascii_tolower(static_cast<unsigned char>(*haystack));
    char nee = case_sensitive
                   ? *needle
                   : absl::ascii_tolower(static_cast<unsigned char>(*needle));
    if (hay == nee) {
      if (++needle == needleend) {
        return haystack + 1 - neelen;
      }
    } else if (needle != needlestart) {
      // must back up haystack in case a prefix matched (find "aab" in "aaab")
      haystack -= needle - needlestart;  // for loop will advance one more
      needle = needlestart;
    }
  }
  return nullptr;
}
References absl::ascii_tolower().
Referenced by memcasemem(), memcasestr(), memmem(), and memstr().
IsInitializerListDispatch() [1/2]
std::false_type absl::strings_internal::IsInitializerListDispatch (...)
IsInitializerListDispatch() [2/2]
template<typename T > std::true_type absl::strings_internal::IsInitializerListDispatch (std::initializer_list< T > *)
Itoa()
template<typename IntType > bool absl::strings_internal::Itoa (IntType value, int base, std::string * destination) inline
Definition at line 33 of file numbers_test_common.h.
{
  destination->clear();
  if (base <= 1 || base > 36) {
    return false;
  }
  if (value == 0) {
    destination->push_back('0');
    return true;
  }
  bool negative = value < 0;
  while (value != 0) {
    const IntType next_value = value / base;
    // Can't use std::abs here because of problems when IntType is unsigned.
    int remainder =
        static_cast<int>(value > next_value * base ? value - next_value * base
                                                   : next_value * base - value);
    char c = remainder < 10 ? '0' + remainder : 'A' + remainder - 10;
    destination->insert(0, 1, c);
    value = next_value;
  }
  if (negative) {
    destination->insert(0, 1, '-');
  }
  return true;
}
References absl::c, and value.
JoinAlgorithm() [1/3]
template<typename... T, typename Formatter > std::string absl::strings_internal::JoinAlgorithm (const std::tuple< T... > & tup, absl::string_view sep, Formatter && fmt)
Definition at line 282 of file str_join_internal.h.
{
  std::string result;
  JoinTupleLoop<0, sizeof...(T)>()(&result, tup, sep, fmt);
  return result;
}
JoinAlgorithm() [2/3]
template<typename Iterator , typename Formatter > std::string absl::strings_internal::JoinAlgorithm (Iterator start, Iterator end, absl::string_view s, Formatter && f)
Definition at line 196 of file str_join_internal.h.
{
  std::string result;
  absl::string_view sep("");
  for (Iterator it = start; it != end; ++it) {
    result.append(sep.data(), sep.size());
    f(&result, *it);
    sep = s;
  }
  return result;
}
References absl::string_view::data(), end, absl::f, absl::s, and absl::string_view::size().
Referenced by JoinRange(), JoinRange(), absl::StrJoin(), absl::StrJoin(), and absl::StrJoin().
JoinAlgorithm() [3/3]
template<typename Iterator , typename = typename std::enable_if<std::is_convertible< typename std::iterator_traits<Iterator>::iterator_category, std::forward_iterator_tag>::value>::type> std::string absl::strings_internal::JoinAlgorithm (Iterator start, Iterator end, absl::string_view s, NoFormatter)
Definition at line 227 of file str_join_internal.h.
{
  std::string result;
  if (start != end) {
    // Sums size
    auto&& start_value = *start;
    size_t result_size = start_value.size();
    for (Iterator it = start; ++it != end;) {
      result_size += s.size();
      result_size += (*it).size();
    }
    if (result_size > 0) {
      STLStringResizeUninitialized(&result, result_size);
      // Joins strings
      char* result_buf = &*result.begin();
      memcpy(result_buf, start_value.data(), start_value.size());
      result_buf += start_value.size();
      for (Iterator it = start; ++it != end;) {
        memcpy(result_buf, s.data(), s.size());
        result_buf += s.size();
        auto&& value = *it;
        memcpy(result_buf, value.data(), value.size());
        result_buf += value.size();
      }
    }
  }
  return result;
}
References end, absl::s, and STLStringResizeUninitialized().
JoinRange() [1/3]
template<typename Range > std::string absl::strings_internal::JoinRange (const Range & range, absl::string_view separator)
Definition at line 307 of file str_join_internal.h.
{
  using std::begin;
  using std::end;
  return JoinRange(begin(range), end(range), separator);
}
References begin, end, and JoinRange().
JoinRange() [2/3]
template<typename Range , typename Formatter > std::string absl::strings_internal::JoinRange (const Range & range, absl::string_view separator, Formatter && fmt)
Definition at line 299 of file str_join_internal.h.
{
  using std::begin;
  using std::end;
  return JoinAlgorithm(begin(range), end(range), separator, fmt);
}
References begin, end, and JoinAlgorithm().
JoinRange() [3/3]
template<typename Iterator > std::string absl::strings_internal::JoinRange (Iterator first, Iterator last, absl::string_view separator)
Definition at line 290 of file str_join_internal.h.
{
  // No formatter was explicitly given, so a default must be chosen.
  typedef typename std::iterator_traits<Iterator>::value_type ValueType;
  typedef typename DefaultFormatter<ValueType>::Type Formatter;
  return JoinAlgorithm(first, last, separator, Formatter());
}
References first, and JoinAlgorithm().
Referenced by JoinRange(), absl::StrJoin(), absl::StrJoin(), absl::StrJoin(), absl::StrJoin(), and absl::StrJoin().
LowerCharmap()
Charmap absl::strings_internal::LowerCharmap () constexpr
Definition at line 138 of file char_map.h.
{ return Charmap::Range('a', 'z'); }
References absl::strings_internal::Charmap::Range().
Referenced by AlphaCharmap().
MakeStringConstant()
template<typename T > StringConstant< T > absl::strings_internal::MakeStringConstant (T) constexpr
Definition at line 64 of file string_constant.h.
{
  return {};
}
Referenced by TEST_P().
memcasecmp()
int absl::strings_internal::memcasecmp (const char * s1, const char * s2, size_t len)
Definition at line 23 of file memutil.cc.
{
  const unsigned char* us1 = reinterpret_cast<const unsigned char*>(s1);
  const unsigned char* us2 = reinterpret_cast<const unsigned char*>(s2);
  for (size_t i = 0; i < len; i++) {
    const int diff =
        int{static_cast<unsigned char>(absl::ascii_tolower(us1[i]))} -
        int{static_cast<unsigned char>(absl::ascii_tolower(us2[i]))};
    if (diff != 0) return diff;
  }
  return 0;
}
References absl::ascii_tolower(), absl::i, and len.
Referenced by absl::EqualsIgnoreCase(), and absl::ABSL_NAMESPACE_BEGIN::ParseInfinityOrNan().
memcasemem()
const char * absl::strings_internal::memcasemem (const char * phaystack, size_t haylen, const char * pneedle, size_t needlelen) inline
Definition at line 134 of file memutil.h.
{
  return int_memmatch<false>(phaystack, haylen, pneedle, needlelen);
}
References int_memmatch().
memcasestr()
const char * absl::strings_internal::memcasestr (const char * phaystack, size_t haylen, const char * pneedle) inline
Definition at line 124 of file memutil.h.
{
  return int_memmatch<false>(phaystack, haylen, pneedle, strlen(pneedle));
}
References int_memmatch().
memcat()
char * absl::strings_internal::memcat (char * dest, size_t destlen, const char * src, size_t srclen) inline
Definition at line 75 of file memutil.h.
{
  return reinterpret_cast<char*>(memcpy(dest + destlen, src, srclen));
}
memcspn()
size_t absl::strings_internal::memcspn (const char * s, size_t slen, const char * reject)
Definition at line 64 of file memutil.cc.
{
  const char* p = s;
  const char* spanp;
  char c, sc;
  while (slen-- != 0) {
    c = *p++;
    for (spanp = reject; (sc = *spanp++) != '\0';)
      if (sc == c)
        return static_cast<size_t>(p - 1 - s);
  }
  return static_cast<size_t>(p - s);
}
References absl::c, absl::p, reject, and absl::s.
memdup()
char * absl::strings_internal::memdup (const char * s, size_t slen)
Definition at line 36 of file memutil.cc.
{
  void* copy;
  if ((copy = malloc(slen)) == nullptr) return nullptr;
  memcpy(copy, s, slen);
  return reinterpret_cast<char*>(copy);
}
References absl::s.
memmatch()
const char * absl::strings_internal::memmatch (const char * phaystack, size_t haylen, const char * pneedle, size_t neelen)
Definition at line 91 of file memutil.cc.
{
  if (0 == neelen) {
    return phaystack;  // even if haylen is 0
  }
  if (haylen < neelen) return nullptr;
  const char* match;
  const char* hayend = phaystack + haylen - neelen + 1;
  // A static cast is used here to work around the fact that memchr returns
  // a void* on Posix-compliant systems and const void* on Windows.
  while (
      (match = static_cast<const char*>(memchr(
           phaystack, pneedle[0], static_cast<size_t>(hayend - phaystack))))) {
    if (memcmp(match, pneedle, neelen) == 0)
      return match;
    else
      phaystack = match + 1;
  }
  return nullptr;
}
Referenced by absl::string_view::find().
memmem()
const char * absl::strings_internal::memmem (const char * phaystack, size_t haylen, const char * pneedle, size_t needlelen) inline
Definition at line 129 of file memutil.h.
{
  return int_memmatch<true>(phaystack, haylen, pneedle, needlelen);
}
References int_memmatch().
mempbrk()
char * absl::strings_internal::mempbrk (const char * s, size_t slen, const char * accept)
Definition at line 78 of file memutil.cc.
{
  const char* scanp;
  int sc;
  for (; slen; ++s, --slen) {
    for (scanp = accept; (sc = *scanp++) != '\0';)
      if (sc == *s) return const_cast<char*>(s);
  }
  return nullptr;
}
References absl::s.
memrchr()
char * absl::strings_internal::memrchr (const char * s, int c, size_t slen)
Definition at line 43 of file memutil.cc.
{
  for (const char* e = s + slen - 1; e >= s; e--) {
    if (*e == c) return const_cast<char*>(e);
  }
  return nullptr;
}
References absl::c, absl::e, and absl::s.
memspn()
size_t absl::strings_internal::memspn (const char * s, size_t slen, const char * accept)
Definition at line 50 of file memutil.cc.
{
  const char* p = s;
  const char* spanp;
  char c, sc;
cont:
  c = *p++;
  if (slen-- == 0)
    return static_cast<size_t>(p - 1 - s);
  for (spanp = accept; (sc = *spanp++) != '\0';)
    if (sc == c) goto cont;
  return static_cast<size_t>(p - 1 - s);
}
References absl::c, absl::p, and absl::s.
memstr()
const char * absl::strings_internal::memstr (const char * phaystack, size_t haylen, const char * pneedle) inline
Definition at line 119 of file memutil.h.
{
  return int_memmatch<true>(phaystack, haylen, pneedle, strlen(pneedle));
}
References int_memmatch().
operator!=()
template<int N, int M> bool absl::strings_internal::operator!= (const BigUnsigned< N > & lhs, const BigUnsigned< M > & rhs)
Definition at line 379 of file charconv_bigint.h.
{
  return !(lhs == rhs);
}
operator<()
template<int N, int M> bool absl::strings_internal::operator< (const BigUnsigned< N > & lhs, const BigUnsigned< M > & rhs)
Definition at line 384 of file charconv_bigint.h.
{
  return Compare(lhs, rhs) == -1;
}
References Compare().
operator<<()
template<int N> std::ostream & absl::strings_internal::operator<< (std::ostream & os, const BigUnsigned< N > & num)
Definition at line 403 of file charconv_bigint.h.
{
  return os << num.ToString();
}
References num.
operator<=()
template<int N, int M> bool absl::strings_internal::operator<= (const BigUnsigned< N > & lhs, const BigUnsigned< M > & rhs)
Definition at line 393 of file charconv_bigint.h.
{
  return !(rhs < lhs);
}
operator==()
template<int N, int M> bool absl::strings_internal::operator== (const BigUnsigned< N > & lhs, const BigUnsigned< M > & rhs)
Definition at line 368 of file charconv_bigint.h.
{
  int limit = (std::max)(lhs.size(), rhs.size());
  for (int i = 0; i < limit; ++i) {
    if (lhs.GetWord(i) != rhs.GetWord(i)) {
      return false;
    }
  }
  return true;
}
References absl::strings_internal::BigUnsigned< max_words >::GetWord(), absl::i, and absl::strings_internal::BigUnsigned< max_words >::size().
operator>()
template<int N, int M> bool absl::strings_internal::operator> (const BigUnsigned< N > & lhs, const BigUnsigned< M > & rhs)
Definition at line 389 of file charconv_bigint.h.
{
  return rhs < lhs;
}
operator>=()
template<int N, int M> bool absl::strings_internal::operator>= (const BigUnsigned< N > & lhs, const BigUnsigned< M > & rhs)
Definition at line 397 of file charconv_bigint.h.
{
  return !(lhs < rhs);
}
ParseFloat() [1/2]
template<int base> ParsedFloat absl::strings_internal::ParseFloat (const char * begin, const char * end, absl::chars_format format_flags)
Definition at line 355 of file charconv_parse.cc.
{
  strings_internal::ParsedFloat result;
  // Exit early if we're given an empty range.
  if (begin == end) return result;
  // Handle the infinity and NaN cases.
  if (ParseInfinityOrNan(begin, end, &result)) {
    return result;
  }
  const char* const mantissa_begin = begin;
  while (begin < end && *begin == '0') {
    ++begin;  // skip leading zeros
  }
  uint64_t mantissa = 0;
  int exponent_adjustment = 0;
  bool mantissa_is_inexact = false;
  int pre_decimal_digits = ConsumeDigits<base>(
      begin, end, MantissaDigitsMax<base>(), &mantissa, &mantissa_is_inexact);
  begin += pre_decimal_digits;
  int digits_left;
  if (pre_decimal_digits >= DigitLimit<base>()) {
    // refuse to parse pathological inputs
    return result;
  } else if (pre_decimal_digits > MantissaDigitsMax<base>()) {
    // We dropped some non-fraction digits on the floor.  Adjust our exponent
    // to compensate.
    exponent_adjustment =
        static_cast<int>(pre_decimal_digits - MantissaDigitsMax<base>());
    digits_left = 0;
  } else {
    digits_left =
        static_cast<int>(MantissaDigitsMax<base>() - pre_decimal_digits);
  }
  if (begin < end && *begin == '.') {
    ++begin;
    if (mantissa == 0) {
      // If we haven't seen any nonzero digits yet, keep skipping zeros.  We
      // have to adjust the exponent to reflect the changed place value.
      const char* begin_zeros = begin;
      while (begin < end && *begin == '0') {
        ++begin;
      }
      int zeros_skipped = static_cast<int>(begin - begin_zeros);
      if (zeros_skipped >= DigitLimit<base>()) {
        // refuse to parse pathological inputs
        return result;
      }
      exponent_adjustment -= static_cast<int>(zeros_skipped);
    }
    int post_decimal_digits = ConsumeDigits<base>(
        begin, end, digits_left, &mantissa, &mantissa_is_inexact);
    begin += post_decimal_digits;
    // Since `mantissa` is an integer, each significant digit we read after
    // the decimal point requires an adjustment to the exponent. "1.23e0" will
    // be stored as `mantissa` == 123 and `exponent` == -2 (that is,
    // "123e-2").
    if (post_decimal_digits >= DigitLimit<base>()) {
      // refuse to parse pathological inputs
      return result;
    } else if (post_decimal_digits > digits_left) {
      exponent_adjustment -= digits_left;
    } else {
      exponent_adjustment -= post_decimal_digits;
    }
  }
  // If we've found no mantissa whatsoever, this isn't a number.
  if (mantissa_begin == begin) {
    return result;
  }
  // A bare "." doesn't count as a mantissa either.
  if (begin - mantissa_begin == 1 && *mantissa_begin == '.') {
    return result;
  }
  if (mantissa_is_inexact) {
    // We dropped significant digits on the floor.  Handle this appropriately.
    if (base == 10) {
      // If we truncated significant decimal digits, store the full range of the
      // mantissa for future big integer math for exact rounding.
      result.subrange_begin = mantissa_begin;
      result.subrange_end = begin;
    } else if (base == 16) {
      // If we truncated hex digits, reflect this fact by setting the low
      // ("sticky") bit.  This allows for correct rounding in all cases.
      mantissa |= 1;
    }
  }
  result.mantissa = mantissa;
  const char* const exponent_begin = begin;
  result.literal_exponent = 0;
  bool found_exponent = false;
  if (AllowExponent(format_flags) && begin < end &&
      IsExponentCharacter<base>(*begin)) {
    bool negative_exponent = false;
    ++begin;
    if (begin < end && *begin == '-') {
      negative_exponent = true;
      ++begin;
    } else if (begin < end && *begin == '+') {
      ++begin;
    }
    const char* const exponent_digits_begin = begin;
    // Exponent is always expressed in decimal, even for hexadecimal floats.
    begin += ConsumeDigits<10>(begin, end, kDecimalExponentDigitsMax,
                               &result.literal_exponent, nullptr);
    if (begin == exponent_digits_begin) {
      // there were no digits where we expected an exponent.  We failed to read
      // an exponent and should not consume the 'e' after all.  Rewind 'begin'.
      found_exponent = false;
      begin = exponent_begin;
    } else {
      found_exponent = true;
      if (negative_exponent) {
        result.literal_exponent = -result.literal_exponent;
      }
    }
  }
  if (!found_exponent && RequireExponent(format_flags)) {
    // Provided flags required an exponent, but none was found.  This results
    // in a failure to scan.
    return result;
  }
  // Success!
  result.type = strings_internal::FloatType::kNumber;
  if (result.mantissa > 0) {
    result.exponent = result.literal_exponent +
                      (DigitMagnitude<base>() * exponent_adjustment);
  } else {
    result.exponent = 0;
  }
  result.end = begin;
  return result;
}
References begin, absl::strings_internal::ParsedFloat::end, absl::strings_internal::ParsedFloat::exponent, kNumber, absl::strings_internal::ParsedFloat::literal_exponent, absl::strings_internal::ParsedFloat::mantissa, mantissa, absl::strings_internal::ParsedFloat::subrange_begin, absl::strings_internal::ParsedFloat::subrange_end, and absl::strings_internal::ParsedFloat::type.
ParseFloat() [2/2]
template<int base> strings_internal::ParsedFloat absl::strings_internal::ParseFloat (const char * begin, const char * end, chars_format format_flags)
Definition at line 355 of file charconv_parse.cc.
{
  strings_internal::ParsedFloat result;
  // Exit early if we're given an empty range.
  if (begin == end) return result;
  // Handle the infinity and NaN cases.
  if (ParseInfinityOrNan(begin, end, &result)) {
    return result;
  }
  const char* const mantissa_begin = begin;
  while (begin < end && *begin == '0') {
    ++begin;  // skip leading zeros
  }
  uint64_t mantissa = 0;
  int exponent_adjustment = 0;
  bool mantissa_is_inexact = false;
  int pre_decimal_digits = ConsumeDigits<base>(
      begin, end, MantissaDigitsMax<base>(), &mantissa, &mantissa_is_inexact);
  begin += pre_decimal_digits;
  int digits_left;
  if (pre_decimal_digits >= DigitLimit<base>()) {
    // refuse to parse pathological inputs
    return result;
  } else if (pre_decimal_digits > MantissaDigitsMax<base>()) {
    // We dropped some non-fraction digits on the floor.  Adjust our exponent
    // to compensate.
    exponent_adjustment =
        static_cast<int>(pre_decimal_digits - MantissaDigitsMax<base>());
    digits_left = 0;
  } else {
    digits_left =
        static_cast<int>(MantissaDigitsMax<base>() - pre_decimal_digits);
  }
  if (begin < end && *begin == '.') {
    ++begin;
    if (mantissa == 0) {
      // If we haven't seen any nonzero digits yet, keep skipping zeros.  We
      // have to adjust the exponent to reflect the changed place value.
      const char* begin_zeros = begin;
      while (begin < end && *begin == '0') {
        ++begin;
      }
      int zeros_skipped = static_cast<int>(begin - begin_zeros);
      if (zeros_skipped >= DigitLimit<base>()) {
        // refuse to parse pathological inputs
        return result;
      }
      exponent_adjustment -= static_cast<int>(zeros_skipped);
    }
    int post_decimal_digits = ConsumeDigits<base>(
        begin, end, digits_left, &mantissa, &mantissa_is_inexact);
    begin += post_decimal_digits;
    // Since `mantissa` is an integer, each significant digit we read after
    // the decimal point requires an adjustment to the exponent. "1.23e0" will
    // be stored as `mantissa` == 123 and `exponent` == -2 (that is,
    // "123e-2").
    if (post_decimal_digits >= DigitLimit<base>()) {
      // refuse to parse pathological inputs
      return result;
    } else if (post_decimal_digits > digits_left) {
      exponent_adjustment -= digits_left;
    } else {
      exponent_adjustment -= post_decimal_digits;
    }
  }
  // If we've found no mantissa whatsoever, this isn't a number.
  if (mantissa_begin == begin) {
    return result;
  }
  // A bare "." doesn't count as a mantissa either.
  if (begin - mantissa_begin == 1 && *mantissa_begin == '.') {
    return result;
  }
  if (mantissa_is_inexact) {
    // We dropped significant digits on the floor.  Handle this appropriately.
    if (base == 10) {
      // If we truncated significant decimal digits, store the full range of the
      // mantissa for future big integer math for exact rounding.
      result.subrange_begin = mantissa_begin;
      result.subrange_end = begin;
    } else if (base == 16) {
      // If we truncated hex digits, reflect this fact by setting the low
      // ("sticky") bit.  This allows for correct rounding in all cases.
      mantissa |= 1;
    }
  }
  result.mantissa = mantissa;
  const char* const exponent_begin = begin;
  result.literal_exponent = 0;
  bool found_exponent = false;
  if (AllowExponent(format_flags) && begin < end &&
      IsExponentCharacter<base>(*begin)) {
    bool negative_exponent = false;
    ++begin;
    if (begin < end && *begin == '-') {
      negative_exponent = true;
      ++begin;
    } else if (begin < end && *begin == '+') {
      ++begin;
    }
    const char* const exponent_digits_begin = begin;
    // Exponent is always expressed in decimal, even for hexadecimal floats.
    begin += ConsumeDigits<10>(begin, end, kDecimalExponentDigitsMax,
                               &result.literal_exponent, nullptr);
    if (begin == exponent_digits_begin) {
      // there were no digits where we expected an exponent.  We failed to read
      // an exponent and should not consume the 'e' after all.  Rewind 'begin'.
      found_exponent = false;
      begin = exponent_begin;
    } else {
      found_exponent = true;
      if (negative_exponent) {
        result.literal_exponent = -result.literal_exponent;
      }
    }
  }
  if (!found_exponent && RequireExponent(format_flags)) {
    // Provided flags required an exponent, but none was found.  This results
    // in a failure to scan.
    return result;
  }
  // Success!
  result.type = strings_internal::FloatType::kNumber;
  if (result.mantissa > 0) {
    result.exponent = result.literal_exponent +
                      (DigitMagnitude<base>() * exponent_adjustment);
  } else {
    result.exponent = 0;
  }
  result.end = begin;
  return result;
}
References begin, absl::strings_internal::ParsedFloat::end, absl::strings_internal::ParsedFloat::exponent, kNumber, absl::strings_internal::ParsedFloat::literal_exponent, absl::strings_internal::ParsedFloat::mantissa, mantissa, absl::strings_internal::ParsedFloat::subrange_begin, absl::strings_internal::ParsedFloat::subrange_end, and absl::strings_internal::ParsedFloat::type.
ParseFloat< 10 >()
template ParsedFloat absl::strings_internal::ParseFloat< 10 > (const char * begin, const char * end, chars_format format_flags)
Referenced by absl::ABSL_NAMESPACE_BEGIN::FromCharsImpl().
ParseFloat< 16 >()
template ParsedFloat absl::strings_internal::ParseFloat< 16 > (const char * begin, const char * end, chars_format format_flags)
Referenced by absl::ABSL_NAMESPACE_BEGIN::FromCharsImpl().
Pow10()
double absl::strings_internal::Pow10 (int exp)
Definition at line 110 of file pow10_helper.cc.
                      {
  if (exp < -324) {
    return 0.0;
  } else if (exp > 308) {
    return INFINITY;
  } else {
    return kPowersOfTen[exp + 324];
  }
}
PrintCharmap()
Charmap absl::strings_internal::PrintCharmap () constexpr
Definition at line 145 of file char_map.h.
{ return Charmap::Range(0x20, 0x7e); }
References absl::strings_internal::Charmap::Range().
Referenced by GraphCharmap().
PunctCharmap()
Charmap absl::strings_internal::PunctCharmap () constexpr
Definition at line 152 of file char_map.h.
{ return GraphCharmap() & ~AlnumCharmap(); }
References GraphCharmap().
SpaceCharmap()
Charmap absl::strings_internal::SpaceCharmap () constexpr
Definition at line 146 of file char_map.h.
{ return Charmap::FromString("\t\n\v\f\r "); }
References absl::strings_internal::Charmap::FromString().
STLStringReserveAmortized()
template<typename string_type > void absl::strings_internal::STLStringReserveAmortized (string_type * s, size_t new_size)
Definition at line 75 of file resize_uninitialized.h.
{
  const size_t cap = s->capacity();
  if (new_size > cap) {
    // Make sure to always grow by at least a factor of 2x.
    s->reserve((std::max)(new_size, 2 * cap));
  }
}
References absl::s.
STLStringResizeUninitialized()
template<typename string_type , typename = void> void absl::strings_internal::STLStringResizeUninitialized (string_type * s, size_t new_size) inline
Definition at line 67 of file resize_uninitialized.h.
{
  ResizeUninitializedTraits<string_type>::Resize(s, new_size);
}
References absl::strings_internal::ResizeUninitializedTraits< string_type, typename >::Resize(), and absl::s.
Referenced by Base64EscapeInternal(), absl::ABSL_NAMESPACE_BEGIN::Base64UnescapeInternal(), absl::BytesToHexString(), CatPieces(), absl::ABSL_NAMESPACE_BEGIN::CEscapeAndAppendInternal(), absl::ABSL_NAMESPACE_BEGIN::CUnescapeInternal(), absl::HexStringToBytes(), JoinAlgorithm(), absl::StrCat(), absl::StrCat(), and absl::StrCat().
STLStringResizeUninitializedAmortized()
template<typename string_type > void absl::strings_internal::STLStringResizeUninitializedAmortized (string_type * s, size_t new_size)
Definition at line 106 of file resize_uninitialized.h.
{
  const size_t size = s->size();
  if (new_size > size) {
    AppendUninitializedTraits<string_type>::Append(s, new_size - size);
  } else {
    s->erase(new_size);
  }
}
References absl::strings_internal::AppendUninitializedTraits< string_type, typename >::Append(), absl::s, and size.
Referenced by AppendPieces(), absl::StrAppend(), absl::StrAppend(), absl::StrAppend(), and absl::substitute_internal::SubstituteAndAppendArray().
STLStringSupportsNontrashingResize()
template<typename string_type > bool absl::strings_internal::STLStringSupportsNontrashingResize (string_type *) inline constexpr
Definition at line 58 of file resize_uninitialized.h.
{
  return ResizeUninitializedTraits<string_type>::HasMember::value;
}
strtouint32_test_cases()
const std::array< uint32_test_case, 27 > & absl::strings_internal::strtouint32_test_cases () inline
Definition at line 69 of file numbers_test_common.h.
{
  static const std::array<uint32_test_case, 27> test_cases{{
      {"0xffffffff", true, 16, (std::numeric_limits<uint32_t>::max)()},
      {"0x34234324", true, 16, 0x34234324},
      {"34234324", true, 16, 0x34234324},
      {"0", true, 16, 0},
      {" \t\n 0xffffffff", true, 16, (std::numeric_limits<uint32_t>::max)()},
      {" \f\v 46", true, 10, 46},  // must accept weird whitespace
      {" \t\n 72717222", true, 8, 072717222},
      {" \t\n 072717222", true, 8, 072717222},
      {" \t\n 072717228", false, 8, 07271722},
      {"0", true, 0, 0},
      // Base-10 version.
      {"34234324", true, 0, 34234324},
      {"4294967295", true, 0, (std::numeric_limits<uint32_t>::max)()},
      {"34234324 \n\t", true, 10, 34234324},
      // Unusual base
      {"0", true, 3, 0},
      {"2", true, 3, 2},
      {"11", true, 3, 4},
      // Invalid uints.
      {"", false, 0, 0},
      {"  ", false, 0, 0},
      {"abc", false, 0, 0},  // would be valid hex, but prefix is missing
      {"34234324a", false, 0, 34234324},
      {"34234.3", false, 0, 34234},
      {"-1", false, 0, 0},
      {"   -123", false, 0, 0},
      {" \t\n -123", false, 0, 0},
      // Out of bounds.
      {"4294967296", false, 0, (std::numeric_limits<uint32_t>::max)()},
      {"0x100000000", false, 0, (std::numeric_limits<uint32_t>::max)()},
      {nullptr, false, 0, 0},
  }};
  return test_cases;
}
strtouint64_test_cases()
const std::array< uint64_test_case, 34 > & absl::strings_internal::strtouint64_test_cases () inline
Definition at line 117 of file numbers_test_common.h.
{
  static const std::array<uint64_test_case, 34> test_cases{{
      {"0x3423432448783446", true, 16, int64_t{0x3423432448783446}},
      {"3423432448783446", true, 16, int64_t{0x3423432448783446}},
      {"0", true, 16, 0},
      {"000", true, 0, 0},
      {"0", true, 0, 0},
      {" \t\n 0xffffffffffffffff", true, 16,
       (std::numeric_limits<uint64_t>::max)()},
      {"012345670123456701234", true, 8, int64_t{012345670123456701234}},
      {"12345670123456701234", true, 8, int64_t{012345670123456701234}},
      {"12845670123456701234", false, 8, 0},
      // Base-10 version.
      {"34234324487834466", true, 0, int64_t{34234324487834466}},
      {" \t\n 18446744073709551615", true, 0,
       (std::numeric_limits<uint64_t>::max)()},
      {"34234324487834466 \n\t ", true, 0, int64_t{34234324487834466}},
      {" \f\v 46", true, 10, 46},  // must accept weird whitespace
      // Unusual base
      {"0", true, 3, 0},
      {"2", true, 3, 2},
      {"11", true, 3, 4},
      {"0", true, 0, 0},
      // Invalid uints.
      {"", false, 0, 0},
      {"  ", false, 0, 0},
      {"abc", false, 0, 0},
      {"34234324487834466a", false, 0, 0},
      {"34234487834466.3", false, 0, 0},
      {"-1", false, 0, 0},
      {"   -123", false, 0, 0},
      {" \t\n -123", false, 0, 0},
      // Out of bounds.
      {"18446744073709551616", false, 10, 0},
      {"18446744073709551616", false, 0, 0},
      {"0x10000000000000000", false, 16,
       (std::numeric_limits<uint64_t>::max)()},
      {"0X10000000000000000", false, 16,
       (std::numeric_limits<uint64_t>::max)()},  // 0X versus 0x.
      {"0x10000000000000000", false, 0, (std::numeric_limits<uint64_t>::max)()},
      {"0X10000000000000000", false, 0,
       (std::numeric_limits<uint64_t>::max)()},  // 0X versus 0x.
      {"0x1234", true, 16, 0x1234},
      // Base-10 string version.
      {"1234", true, 0, 1234},
      {nullptr, false, 0, 0},
  }};
  return test_cases;
}
TEST() [1/6]
absl::strings_internal::TEST (BigUnsigned , FiveToTheNth)
Definition at line 202 of file charconv_bigint_test.cc.
{
  {
    // Sanity check that MultiplyByFiveToTheNth gives consistent answers, up to
    // and including overflow.
    for (int i = 0; i < 1160; ++i) {
      SCOPED_TRACE(i);
      BigUnsigned<84> value_1(123u);
      BigUnsigned<84> value_2(123u);
      value_1.MultiplyByFiveToTheNth(i);
      for (int j = 0; j < i; j++) {
        value_2.MultiplyBy(5u);
      }
      EXPECT_EQ(value_1, value_2);
    }
  }
  {
    // Check that the faster, table-lookup-based static method returns the same
    // result that multiplying in-place would return, up to and including
    // overflow.
    for (int i = 0; i < 1160; ++i) {
      SCOPED_TRACE(i);
      BigUnsigned<84> value_1(1u);
      value_1.MultiplyByFiveToTheNth(i);
      BigUnsigned<84> value_2 = BigUnsigned<84>::FiveToTheNth(i);
      EXPECT_EQ(value_1, value_2);
    }
  }
}
References absl::strings_internal::BigUnsigned< max_words >::FiveToTheNth(), absl::i, absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), and absl::strings_internal::BigUnsigned< max_words >::MultiplyByFiveToTheNth().
TEST() [2/6]
absl::strings_internal::TEST (BigUnsigned , MultiplyByBigUnsigned)
Definition at line 141 of file charconv_bigint_test.cc.
{
  {
    // Put the terms of factorial_200 into two bigints, and multiply them
    // together.
    const BigUnsigned<84> factorial_200(
        "7886578673647905035523632139321850622951359776871732632947425332443594"
        "4996340334292030428401198462390417721213891963883025764279024263710506"
        "1926624952829931113462857270763317237396988943922445621451664240254033"
        "2918641312274282948532775242424075739032403212574055795686602260319041"
        "7032406235170085879617892222278962370389737472000000000000000000000000"
        "0000000000000000000000000");
    BigUnsigned<84> evens(1u);
    BigUnsigned<84> odds(1u);
    for (uint32_t i = 1; i < 200; i += 2) {
      odds.MultiplyBy(i);
      evens.MultiplyBy(i + 1);
    }
    evens.MultiplyBy(odds);
    EXPECT_EQ(evens, factorial_200);
  }
  {
    // Multiply various powers of 10 together.
    for (int a = 0 ; a < 700; a += 25) {
      SCOPED_TRACE(a);
      BigUnsigned<84> a_value("3" + std::string(a, '0'));
      for (int b = 0; b < (700 - a); b += 25) {
        SCOPED_TRACE(b);
        BigUnsigned<84> b_value("2" + std::string(b, '0'));
        BigUnsigned<84> expected_product("6" + std::string(a + b, '0'));
        b_value.MultiplyBy(a_value);
        EXPECT_EQ(b_value, expected_product);
      }
    }
  }
}
References absl::a, b, absl::i, and absl::strings_internal::BigUnsigned< max_words >::MultiplyBy().
TEST() [3/6]
absl::strings_internal::TEST (BigUnsigned , MultiplyByOverflow)
Definition at line 177 of file charconv_bigint_test.cc.
{
  {
    // Check that multiplcation overflow predictably truncates.
    // A big int with all bits on.
    BigUnsigned<4> all_bits_on("340282366920938463463374607431768211455");
    // Modulo 2**128, this is equal to -1.  Therefore the square of this,
    // modulo 2**128, should be 1.
    all_bits_on.MultiplyBy(all_bits_on);
    EXPECT_EQ(all_bits_on, BigUnsigned<4>(1u));
  }
  {
    // Try multiplying a large bigint by 2**50, and compare the result to
    // shifting.
    BigUnsigned<4> value_1("12345678901234567890123456789012345678");
    BigUnsigned<4> value_2("12345678901234567890123456789012345678");
    BigUnsigned<4> two_to_fiftieth(1u);
    two_to_fiftieth.ShiftLeft(50);
    value_1.ShiftLeft(50);
    value_2.MultiplyBy(two_to_fiftieth);
    EXPECT_EQ(value_1, value_2);
  }
}
References absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), and absl::strings_internal::BigUnsigned< max_words >::ShiftLeft().
TEST() [4/6]
absl::strings_internal::TEST (BigUnsigned , MultiplyByUint32)
Definition at line 129 of file charconv_bigint_test.cc.
{
  const BigUnsigned<84> factorial_100(
      "933262154439441526816992388562667004907159682643816214685929638952175999"
      "932299156089414639761565182862536979208272237582511852109168640000000000"
      "00000000000000");
  BigUnsigned<84> a(1u);
  for (uint32_t i = 1; i <= 100; ++i) {
    a.MultiplyBy(i);
  }
  EXPECT_EQ(a, BigUnsigned<84>(factorial_100));
}
References absl::a, and absl::i.
TEST() [5/6]
absl::strings_internal::TEST (BigUnsigned , ShiftLeft)
Definition at line 25 of file charconv_bigint_test.cc.
{
  {
    // Check that 3 * 2**100 is calculated correctly
    BigUnsigned<4> num(3u);
    num.ShiftLeft(100);
    EXPECT_EQ(num, BigUnsigned<4>("3802951800684688204490109616128"));
  }
  {
    // Test that overflow is truncated properly.
    // 15 is 4 bits long, and BigUnsigned<4> is a 128-bit bigint.
    // Shifting left by 125 bits should truncate off the high bit, so that
    //   15 << 125 == 7 << 125
    // after truncation.
    BigUnsigned<4> a(15u);
    BigUnsigned<4> b(7u);
    BigUnsigned<4> c(3u);
    a.ShiftLeft(125);
    b.ShiftLeft(125);
    c.ShiftLeft(125);
    EXPECT_EQ(a, b);
    EXPECT_NE(a, c);
  }
  {
    // Same test, larger bigint:
    BigUnsigned<84> a(15u);
    BigUnsigned<84> b(7u);
    BigUnsigned<84> c(3u);
    a.ShiftLeft(84 * 32 - 3);
    b.ShiftLeft(84 * 32 - 3);
    c.ShiftLeft(84 * 32 - 3);
    EXPECT_EQ(a, b);
    EXPECT_NE(a, c);
  }
  {
    // Check that incrementally shifting has the same result as doing it all at
    // once (attempting to capture corner cases.)
    const std::string seed = "1234567890123456789012345678901234567890";
    BigUnsigned<84> a(seed);
    for (int i = 1; i <= 84 * 32; ++i) {
      a.ShiftLeft(1);
      BigUnsigned<84> b(seed);
      b.ShiftLeft(i);
      EXPECT_EQ(a, b);
    }
    // And we should have fully rotated all bits off by now:
    EXPECT_EQ(a, BigUnsigned<84>(0u));
  }
  {
    // Bit shifting large and small numbers by large and small offsets.
    // Intended to exercise bounds-checking corner on ShiftLeft() (directly
    // and under asan).
    // 2**(32*84)-1
    const BigUnsigned<84> all_bits_one(
        "1474444211396924248063325089479706787923460402125687709454567433186613"
        "6228083464060749874845919674257665016359189106695900028098437021384227"
        "3285029708032466536084583113729486015826557532750465299832071590813090"
        "2011853039837649252477307070509704043541368002938784757296893793903797"
        "8180292336310543540677175225040919704702800559606097685920595947397024"
        "8303316808753252115729411497720357971050627997031988036134171378490368"
        "6008000778741115399296162550786288457245180872759047016734959330367829"
        "5235612397427686310674725251378116268607113017720538636924549612987647"
        "5767411074510311386444547332882472126067840027882117834454260409440463"
        "9345147252664893456053258463203120637089916304618696601333953616715125"
        "2115882482473279040772264257431663818610405673876655957323083702713344"
        "4201105427930770976052393421467136557055");
    const BigUnsigned<84> zero(0u);
    const BigUnsigned<84> one(1u);
    // in bounds shifts
    for (int i = 1; i < 84*32; ++i) {
      // shifting all_bits_one to the left should result in a smaller number,
      // since the high bits rotate off and the low bits are replaced with
      // zeroes.
      BigUnsigned<84> big_shifted = all_bits_one;
      big_shifted.ShiftLeft(i);
      EXPECT_GT(all_bits_one, big_shifted);
      // Shifting 1 to the left should instead result in a larger number.
      BigUnsigned<84> small_shifted = one;
      small_shifted.ShiftLeft(i);
      EXPECT_LT(one, small_shifted);
    }
    // Shifting by zero or a negative number has no effect
    for (int no_op_shift : {0, -1, -84 * 32, std::numeric_limits<int>::min()}) {
      BigUnsigned<84> big_shifted = all_bits_one;
      big_shifted.ShiftLeft(no_op_shift);
      EXPECT_EQ(all_bits_one, big_shifted);
      BigUnsigned<84> small_shifted = one;
      big_shifted.ShiftLeft(no_op_shift);
      EXPECT_EQ(one, small_shifted);
    }
    // Shifting by an amount greater than the number of bits should result in
    // zero.
    for (int out_of_bounds_shift :
         {84 * 32, 84 * 32 + 1, std::numeric_limits<int>::max()}) {
      BigUnsigned<84> big_shifted = all_bits_one;
      big_shifted.ShiftLeft(out_of_bounds_shift);
      EXPECT_EQ(zero, big_shifted);
      BigUnsigned<84> small_shifted = one;
      small_shifted.ShiftLeft(out_of_bounds_shift);
      EXPECT_EQ(zero, small_shifted);
    }
  }
}
References absl::a, b, absl::c, absl::i, num, absl::strings_internal::BigUnsigned< max_words >::ShiftLeft(), and absl::u.
TEST() [6/6]
absl::strings_internal::TEST (BigUnsigned , TenToTheNth)
Definition at line 231 of file charconv_bigint_test.cc.
{
  {
    // Sanity check MultiplyByTenToTheNth.
    for (int i = 0; i < 800; ++i) {
      SCOPED_TRACE(i);
      BigUnsigned<84> value_1(123u);
      BigUnsigned<84> value_2(123u);
      value_1.MultiplyByTenToTheNth(i);
      for (int j = 0; j < i; j++) {
        value_2.MultiplyBy(10u);
      }
      EXPECT_EQ(value_1, value_2);
    }
  }
  {
    // Alternate testing approach, taking advantage of the decimal parser.
    for (int i = 0; i < 200; ++i) {
      SCOPED_TRACE(i);
      BigUnsigned<84> value_1(135u);
      value_1.MultiplyByTenToTheNth(i);
      BigUnsigned<84> value_2("135" + std::string(i, '0'));
      EXPECT_EQ(value_1, value_2);
    }
  }
}
References absl::i, absl::strings_internal::BigUnsigned< max_words >::MultiplyBy(), and absl::strings_internal::BigUnsigned< max_words >::MultiplyByTenToTheNth().
UpperCharmap()
Charmap absl::strings_internal::UpperCharmap () constexpr
Definition at line 137 of file char_map.h.
{ return Charmap::Range('A', 'Z'); }
References absl::strings_internal::Charmap::Range().
Referenced by AlphaCharmap().
XDigitCharmap()
Charmap absl::strings_internal::XDigitCharmap () constexpr
Definition at line 142 of file char_map.h.
{
  return DigitCharmap() | Charmap::Range('A', 'F') | Charmap::Range('a', 'f');
}
References DigitCharmap(), and absl::strings_internal::Charmap::Range().
Variable Documentation
kBase64Chars
ABSL_CONST_INIT const char absl::strings_internal::kBase64Chars
Initial value:
=
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
Definition at line 24 of file escaping.cc.
Referenced by absl::Base64Escape(), and absl::Base64Escape().
kFiveToNth
ABSL_DLL const uint32_t absl::strings_internal::kFiveToNth
Initial value:
= {
    1,     5,      25,      125,     625,      3125,      15625,
    78125, 390625, 1953125, 9765625, 48828125, 244140625, 1220703125,
}
Definition at line 161 of file charconv_bigint.cc.
{
    1,     5,      25,      125,     625,      3125,      15625,
    78125, 390625, 1953125, 9765625, 48828125, 244140625, 1220703125,
};
Referenced by absl::strings_internal::BigUnsigned< max_words >::MultiplyByFiveToTheNth().
kMaxSmallPowerOfFive
int absl::strings_internal::kMaxSmallPowerOfFive = 13 constexpr
Definition at line 33 of file charconv_bigint.h.
Referenced by absl::strings_internal::BigUnsigned< max_words >::MultiplyByFiveToTheNth().
kMaxSmallPowerOfTen
int absl::strings_internal::kMaxSmallPowerOfTen = 9 constexpr
Definition at line 35 of file charconv_bigint.h.
Referenced by absl::strings_internal::BigUnsigned< max_words >::MultiplyByTenToTheNth().
kTenToNth
ABSL_DLL const uint32_t absl::strings_internal::kTenToNth
Initial value:
= {
    1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000,
}
Definition at line 166 of file charconv_bigint.cc.
{
    1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000,
};
Referenced by absl::strings_internal::BigUnsigned< max_words >::MultiplyByTenToTheNth().