open spiel: open_spiel::matrix_game Namespace Reference
open_spiel::matrix_game Namespace Reference
Classes
class MatrixGame
class MatrixState
Functions
std::vector< double > FlattenMatrix (const std::vector< std::vector< double > > &matrix_rows)
std::shared_ptr< const MatrixGame > CreateMatrixGame (const std::vector< std::vector< double > > &row_player_utils, const std::vector< std::vector< double > > &col_player_utils)
std::shared_ptr< const MatrixGame > CreateMatrixGame (const std::string &short_name, const std::string &long_name, const std::vector< std::string > &row_names, const std::vector< std::string > &col_names, const std::vector< std::vector< double > > &row_player_utils, const std::vector< std::vector< double > > &col_player_utils)
std::shared_ptr< const MatrixGame > CreateMatrixGame (const std::string &short_name, const std::string &long_name, const std::vector< std::string > &row_names, const std::vector< std::string > &col_names, const std::vector< double > &flat_row_utils, const std::vector< double > &flat_col_utils)
Variables
constexpr int kRowPlayer = 0
constexpr int kColPlayer = 1
Function Documentation
CreateMatrixGame() [1/3]
std::shared_ptr< const MatrixGame > open_spiel::matrix_game::CreateMatrixGame (const std::string & short_name, const std::string & long_name, const std::vector< std::string > & row_names, const std::vector< std::string > & col_names, const std::vector< double > & flat_row_utils, const std::vector< double > & flat_col_utils)
Definition at line 183 of file matrix_game.cc.
{
  // Detect the utility type from the utilities.
  GameType::Utility utility = GetUtilityType(flat_row_utils, flat_col_utils);
  GameType game_type{
      /*short_name=*/short_name,
      /*long_name=*/long_name,
      GameType::Dynamics::kSimultaneous,
      GameType::ChanceMode::kDeterministic,
      GameType::Information::kOneShot,
      utility,
      GameType::RewardModel::kTerminal,
      /*max_num_players=*/2,
      /*min_num_players=*/2,
      /*provides_information_state_string=*/true,
      /*provides_information_state_tensor=*/true,
      /*provides_observation_string=*/true,
      /*provides_observation_tensor=*/true,
      /*parameter_specification=*/{}  // no parameters
  };
  return std::shared_ptr<const MatrixGame>(new MatrixGame(
      game_type, {}, row_names, col_names, flat_row_utils, flat_col_utils));
}
References open_spiel::GameType::kDeterministic, open_spiel::GameType::kOneShot, open_spiel::GameType::kSimultaneous, and open_spiel::GameType::kTerminal.
CreateMatrixGame() [2/3]
std::shared_ptr< const MatrixGame > open_spiel::matrix_game::CreateMatrixGame (const std::string & short_name, const std::string & long_name, const std::vector< std::string > & row_names, const std::vector< std::string > & col_names, const std::vector< std::vector< double > > & row_player_utils, const std::vector< std::vector< double > > & col_player_utils)
Definition at line 167 of file matrix_game.cc.
{
  int rows = row_names.size();
  int columns = col_names.size();
  std::vector<double> flat_row_utils = FlattenMatrix(row_player_utils);
  std::vector<double> flat_col_utils = FlattenMatrix(col_player_utils);
  SPIEL_CHECK_EQ(flat_row_utils.size(), rows * columns);
  SPIEL_CHECK_EQ(flat_col_utils.size(), rows * columns);
  return CreateMatrixGame(short_name, long_name, row_names, col_names,
                          flat_row_utils, flat_col_utils);
}
References CreateMatrixGame(), FlattenMatrix(), and SPIEL_CHECK_EQ.
CreateMatrixGame() [3/3]
std::shared_ptr< const MatrixGame > open_spiel::matrix_game::CreateMatrixGame (const std::vector< std::vector< double > > & row_player_utils, const std::vector< std::vector< double > > & col_player_utils)
Definition at line 147 of file matrix_game.cc.
{
  SPIEL_CHECK_GT(row_player_utils.size(), 0);
  int num_rows = row_player_utils.size();
  int num_columns = row_player_utils[0].size();
  std::vector<std::string> row_names(num_rows);
  std::vector<std::string> col_names(num_columns);
  for (int i = 0; i < num_rows; ++i) {
    row_names[i] = absl::StrCat("row", i);
  }
  for (int i = 0; i < num_columns; ++i) {
    col_names[i] = absl::StrCat("col", i);
  }
  return CreateMatrixGame("short_name", "Long Name", row_names, col_names,
                          row_player_utils, col_player_utils);
}
References CreateMatrixGame(), and SPIEL_CHECK_GT.
Referenced by open_spiel::tensor_game::TensorGame::AsMatrixGame(), CreateMatrixGame(), and CreateMatrixGame().
FlattenMatrix()
std::vector< double > open_spiel::matrix_game::FlattenMatrix (const std::vector< std::vector< double > > & matrix_rows)
Definition at line 122 of file matrix_game.cc.
{
  std::vector<double> utilities;
  int total_size = 0;
  int row_size = -1;
  int i = 0;
  for (int r = 0; r < matrix_rows.size(); ++r) {
    if (row_size < 0) {
      row_size = matrix_rows[r].size();
    }
    SPIEL_CHECK_GT(row_size, 0);
    SPIEL_CHECK_EQ(row_size, matrix_rows[r].size());
    total_size += row_size;
    utilities.resize(total_size, 0);
    for (int c = 0; c < matrix_rows[r].size(); ++c) {
      utilities[i] = matrix_rows[r][c];
      ++i;
    }
  }
  return utilities;
}
References SPIEL_CHECK_EQ, and SPIEL_CHECK_GT.
Referenced by CreateMatrixGame().
Variable Documentation
kColPlayer
int open_spiel::matrix_game::kColPlayer = 1 inline constexpr
Definition at line 35 of file matrix_game.h.
Referenced by open_spiel::matrix_game::MatrixState::DoApplyActions().
kRowPlayer
int open_spiel::matrix_game::kRowPlayer = 0 inline constexpr
Definition at line 34 of file matrix_game.h.
Referenced by open_spiel::matrix_game::MatrixState::ActionToString(), open_spiel::matrix_game::MatrixState::DoApplyActions(), and open_spiel::matrix_game::MatrixState::LegalActions().