open spiel: absl::utility_internal Namespace Reference
absl::utility_internal Namespace Reference
Classes
struct Extend
struct Extend< integer_sequence< T, Ints... >, SeqSize, 0 >
struct Extend< integer_sequence< T, Ints... >, SeqSize, 1 >
struct Gen
struct Gen< T, 0 >
struct InPlaceIndexTag
struct InPlaceTypeTag
Functions
template<typename Functor , typename Tuple , std::size_t... Indexes>
auto apply_helper (Functor &&functor, Tuple &&t, index_sequence< Indexes... >) -> decltype(absl::base_internal::invoke(absl::forward< Functor >(functor), std::get< Indexes >(absl::forward< Tuple >(t))...))
template<typename T , typename Tuple , size_t... I>
T make_from_tuple_impl (Tuple &&tup, absl::index_sequence< I... >)
Function Documentation
apply_helper()
template<typename Functor , typename Tuple , std::size_t... Indexes> auto absl::utility_internal::apply_helper (Functor && functor, Tuple && t, index_sequence< Indexes... >) -> decltype(absl::base_internal::invoke(absl::forward<Functor>(functor), std::get<Indexes>(absl::forward<Tuple>(t))...))
Definition at line 238 of file utility.h.
{
  return absl::base_internal::invoke(
      absl::forward<Functor>(functor),
      std::get<Indexes>(absl::forward<Tuple>(t))...);
}
References absl::forward(), and absl::base_internal::invoke().
make_from_tuple_impl()
template<typename T , typename Tuple , size_t... I> T absl::utility_internal::make_from_tuple_impl (Tuple && tup, absl::index_sequence< I... >)
Definition at line 322 of file utility.h.
{
  return T(std::get<I>(std::forward<Tuple>(tup))...);
}
Referenced by absl::make_from_tuple().