open spiel: utils Namespace Reference
utils Namespace Reference
Classes
class NFSPPolicies
class PathBCDEResponse
class PathBCEResponse
class PathBDEResponse
class PurePolicyResponse
class RandomPolicyDeviation
Functions
create_games (origin, destination, num_vehicles, graph, max_time_step, time_step_length=1.0, departure_time=None)
create_braess_network (capacity)
create_augmented_braess_network (capacity)
create_series_parallel_network (num_network_in_series, time_step_length=1, capacity=1)
plot_network_n_player_game (dynamic_routing_utils.Network g, vehicle_locations=None)
plot_network_mean_field_game (dynamic_routing_utils.Network g, distribution=None, scaling=1)
evolve_n_player_simultaneous_game (game, policy, graph)
evolve_n_player_sequential_game (seq_game, policy, graph, debug=False)
evolve_mean_field_game (mfg_game, policy, graph, scaling=1, frequency_printing=1)
uniform_policy_n_player (seq_game)
first_action_policy_n_player (seq_game)
ficticious_play (seq_game, number_of_iterations, compute_metrics=False)
counterfactual_regret_minimization (seq_game, number_of_iterations, compute_metrics=False)
external_sampling_monte_carlo_counterfactual_regret_minimization (seq_game, number_of_iterations, compute_metrics=False)
neural_ficticious_self_play (seq_game, num_epoch, sess, compute_metrics=False)
mean_field_uniform_policy (mfg_game, number_of_iterations, compute_metrics=False)
mean_field_fictitious_play (mfg_game, number_of_iterations, compute_metrics=False)
online_mirror_descent (mfg_game, number_of_iterations, compute_metrics=False, return_policy=False, md_p=None)
get_results_n_player_sequential_game (seq_game, policy)
get_list_results_n_player_game (seq_game, policy, num_sample=10)
get_average_results_n_player_game (seq_game, policy, num_sample=10)
get_results_n_player_simultaneous_game (game, policy)
get_list_results_n_player_simulataneous_game (game, policy, num_sample=10)
get_expected_value (seq_game, policy, num_sample, player=0)
compute_regret_policy (game, policy, num_random_policy_tested=10, num_sample=100)
get_expected_value_sim_game (game, policy, num_sample, player=0)
compute_regret_policy_random_noise_sim_game (game, policy, num_random_policy_tested=10, num_sample=100)
compute_regret_policy_against_pure_policy_sim_game (game, policy, compute_true_value=False, num_sample=100)
online_mirror_descent_sioux_falls (mfg_game, number_of_iterations, md_p=None)
meta_loss (opt_params, net_apply, payoff, steps)
get_batched_input (List[jax.Array] input_list, List[InfostateNode] infostate_list, List[List[int]] illegal_action_list, int batch_size)
np.ndarray mask (np.ndarray cfvalues, List[InfostateNode] infoset, int num_actions, int batch_size)
filter_terminal_infostates (InfostateMapping infostates_map)
jax.Array get_network_output (ApplyFn net_apply, Params net_params, np.ndarray net_input, List[int] illegal_actions, hk.PRNGSequence key)
List[jax.Array] get_network_output_batched (ApplyFn net_apply, Params net_params, np.ndarray net_input, List[List[int]] all_illegal_actions, hk.PRNGSequence key)
float meta_loss (Params net_params, np.ndarray cfvalues, ApplyFn net_apply, int steps, int num_all_actions, List[InfostateNode] infosets, InfostateMapping infostate_map, int batch_size, hk.PRNGSequence key, bool use_infostate_representation=True)
Variables
FLAGS = flags.FLAGS
Detailed Description
Utils function for routing game experiment.
Utility functions for meta learning for regret minimization.
Utility functions for meta-cfr algorithm.
Function Documentation
compute_regret_policy()
utils.compute_regret_policy (game, policy, num_random_policy_tested = 10, num_sample = 100)
Definition at line 960 of file utils.py.
                          num_sample=100):
  time_tick = time.time()
  expected_value_policy = get_expected_value(game, policy, num_sample)
  worse_regret = 0
  for _ in range(num_random_policy_tested):
    noisy_n_policy = noisy_policy.NoisyPolicy(policy, player_id=0, alpha=1)
    expected_value_noise = get_expected_value(
        game, noisy_n_policy, num_sample, player=0)
    approximate_regret = expected_value_noise - expected_value_policy
    worse_regret = max(worse_regret, approximate_regret)
  return worse_regret, time.time() - time_tick
References get_expected_value().
compute_regret_policy_against_pure_policy_sim_game()
utils.compute_regret_policy_against_pure_policy_sim_game (game, policy, compute_true_value = False, num_sample = 100)
Definition at line 1065 of file utils.py.
                                                       num_sample=100):
  time_tick = time.time()
  if compute_true_value:
    expected_value_policy = expected_game_score.policy_value(
        game.new_initial_state(), policy)[0]
  else:
    expected_value_policy = get_expected_value_sim_game(game, policy,
                                                        num_sample)
  worse_regret = 0
  policies = [
      PathBCEResponse(game, policy, 0),
      PathBCDEResponse(game, policy, 0),
      PathBDEResponse(game, policy, 0)
  ]
  for deviation_policy in policies:
    if compute_true_value:
      expected_value_noise = expected_game_score.policy_value(
          game.new_initial_state(), deviation_policy)[0]
    else:
      expected_value_noise = get_expected_value_sim_game(
          game, deviation_policy, num_sample, player=0)
    approximate_regret = expected_value_noise - expected_value_policy
    worse_regret = max(worse_regret, approximate_regret)
  return worse_regret, time.time() - time_tick
References get_expected_value_sim_game().
compute_regret_policy_random_noise_sim_game()
utils.compute_regret_policy_random_noise_sim_game (game, policy, num_random_policy_tested = 10, num_sample = 100)
Definition at line 989 of file utils.py.
                                                num_sample=100):
  time_tick = time.time()
  expected_value_policy = get_expected_value_sim_game(game, policy, num_sample)
  worse_regret = 0
  for _ in range(num_random_policy_tested):
    noisy_n_policy = noisy_policy.NoisyPolicy(policy, player_id=0, alpha=1)
    expected_value_noise = get_expected_value_sim_game(
        game, noisy_n_policy, num_sample, player=0)
    approximate_regret = expected_value_noise - expected_value_policy
    worse_regret = max(worse_regret, approximate_regret)
  return worse_regret, time.time() - time_tick
References get_expected_value_sim_game().
counterfactual_regret_minimization()
utils.counterfactual_regret_minimization (seq_game, number_of_iterations, compute_metrics = False)
Definition at line 670 of file utils.py.
                                       compute_metrics=False):
  # freq_iteration_printing = number_of_iterations // 10
  cfr_solver = cfr.CFRSolver(seq_game)
  tick_time = time.time()
  # print("CFRSolver initialized.")
  for _ in range(number_of_iterations):
    cfr_solver.evaluate_and_update_policy()
    # if i % freq_iteration_printing == 0:
    #   print(f"Iteration {i}")
  timing = time.time() - tick_time
  # print("Finish.")
  if compute_metrics:
    nash_conv = exploitability.nash_conv(seq_game, cfr_solver.average_policy())
    return timing, cfr_solver.average_policy(), nash_conv
  return timing, cfr_solver.average_policy()
create_augmented_braess_network()
utils.create_augmented_braess_network (capacity)
Definition at line 183 of file utils.py.
def create_augmented_braess_network(capacity):
  graph_dict = {
      "A": {
          "connection": {
              "B": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 0
              }
          },
          "location": [0, 0]
      },
      "B": {
          "connection": {
              "C": {
                  "a": 1.0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 1.0
              },
              "D": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 2.0
              }
          },
          "location": [1, 0]
      },
      "C": {
          "connection": {
              "D": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 0.25
              },
              "E": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 2.0
              }
          },
          "location": [2, 1]
      },
      "D": {
          "connection": {
              "E": {
                  "a": 1,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 1.0
              },
              "G": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 0.0
              }
          },
          "location": [2, -1]
      },
      "E": {
          "connection": {
              "F": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 0.0
              }
          },
          "location": [3, 0]
      },
      "F": {
          "connection": {},
          "location": [4, 0]
      },
      "G": {
          "connection": {},
          "location": [3, -1]
      }
  }
  adjacency_list = {
      key: list(value["connection"].keys())
      for key, value in graph_dict.items()
  }
  bpr_a_coefficient = {}
  bpr_b_coefficient = {}
  capacity = {}
  free_flow_travel_time = {}
  for o_node, value_dict in graph_dict.items():
    for d_node, section_dict in value_dict["connection"].items():
      road_section = dynamic_routing_utils._road_section_from_nodes(
          origin=o_node, destination=d_node)
      bpr_a_coefficient[road_section] = section_dict["a"]
      bpr_b_coefficient[road_section] = section_dict["b"]
      capacity[road_section] = section_dict["capacity"]
      free_flow_travel_time[road_section] = section_dict[
          "free_flow_travel_time"]
  node_position = {key: value["location"] for key, value in graph_dict.items()}
  return dynamic_routing_utils.Network(
      adjacency_list,
      node_position=node_position,
      bpr_a_coefficient=bpr_a_coefficient,
      bpr_b_coefficient=bpr_b_coefficient,
      capacity=capacity,
      free_flow_travel_time=free_flow_travel_time)
References keys.
create_braess_network()
utils.create_braess_network (capacity)
Definition at line 82 of file utils.py.
def create_braess_network(capacity):
  graph_dict = {
      "A": {
          "connection": {
              "B": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 0
              }
          },
          "location": [0, 0]
      },
      "B": {
          "connection": {
              "C": {
                  "a": 1.0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 1.0
              },
              "D": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 2.0
              }
          },
          "location": [1, 0]
      },
      "C": {
          "connection": {
              "D": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 0.25
              },
              "E": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 2.0
              }
          },
          "location": [2, 1]
      },
      "D": {
          "connection": {
              "E": {
                  "a": 1,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 1.0
              }
          },
          "location": [2, -1]
      },
      "E": {
          "connection": {
              "F": {
                  "a": 0,
                  "b": 1.0,
                  "capacity": capacity,
                  "free_flow_travel_time": 0.0
              }
          },
          "location": [3, 0]
      },
      "F": {
          "connection": {},
          "location": [4, 0]
      }
  }
  adjacency_list = {
      key: list(value["connection"].keys())
      for key, value in graph_dict.items()
  }
  bpr_a_coefficient = {}
  bpr_b_coefficient = {}
  capacity = {}
  free_flow_travel_time = {}
  for o_node, value_dict in graph_dict.items():
    for d_node, section_dict in value_dict["connection"].items():
      road_section = dynamic_routing_utils._road_section_from_nodes(
          origin=o_node, destination=d_node)
      bpr_a_coefficient[road_section] = section_dict["a"]
      bpr_b_coefficient[road_section] = section_dict["b"]
      capacity[road_section] = section_dict["capacity"]
      free_flow_travel_time[road_section] = section_dict[
          "free_flow_travel_time"]
  node_position = {key: value["location"] for key, value in graph_dict.items()}
  return dynamic_routing_utils.Network(
      adjacency_list,
      node_position=node_position,
      bpr_a_coefficient=bpr_a_coefficient,
      bpr_b_coefficient=bpr_b_coefficient,
      capacity=capacity,
      free_flow_travel_time=free_flow_travel_time)
References keys.
create_games()
utils.create_games (origin, destination, num_vehicles, graph, max_time_step, time_step_length = 1.0, departure_time = None)
Definition at line 47 of file utils.py.
                 departure_time=None):
  if departure_time is not None:
    raise NotImplementedError("To do.")
  list_of_vehicles = [
      dynamic_routing_utils.Vehicle(origin, destination)
      for _ in range(num_vehicles)
  ]
  game = dynamic_routing.DynamicRoutingGame(
      {
          "max_num_time_step": max_time_step,
          "time_step_length": time_step_length
      },
      network=graph,
      vehicles=list_of_vehicles)
  seq_game = pyspiel.convert_to_turn_based(game)
  od_demand = [
      dynamic_routing_utils.OriginDestinationDemand(origin, destination, 0,
                                                    num_vehicles)
  ]
  mfg_game = mean_field_routing_game.MeanFieldRoutingGame(
      {
          "max_num_time_step": max_time_step,
          "time_step_length": time_step_length
      },
      network=graph,
      od_demand=od_demand)
  return game, seq_game, mfg_game
create_series_parallel_network()
utils.create_series_parallel_network (num_network_in_series, time_step_length = 1, capacity = 1)
Definition at line 294 of file utils.py.
                                   capacity=1):
  i = 0
  origin = "A_0->B_0"
  graph_dict = {}
  while i < num_network_in_series:
    tt_up = random.random() + time_step_length
    tt_down = random.random() + time_step_length
    graph_dict.update({
        f"A_{i}": {
            "connection": {
                f"B_{i}": {
                    "a": 0,
                    "b": 1.0,
                    "capacity": capacity,
                    "free_flow_travel_time": time_step_length
                }
            },
            "location": [0 + 3 * i, 0]
        },
        f"B_{i}": {
            "connection": {
                f"C_{i}": {
                    "a": 1.0,
                    "b": 1.0,
                    "capacity": capacity,
                    "free_flow_travel_time": tt_up
                },
                f"D_{i}": {
                    "a": 1.0,
                    "b": 1.0,
                    "capacity": capacity,
                    "free_flow_travel_time": tt_down
                }
            },
            "location": [1 + 3 * i, 0]
        },
        f"C_{i}": {
            "connection": {
                f"A_{i+1}": {
                    "a": 0,
                    "b": 1.0,
                    "capacity": capacity,
                    "free_flow_travel_time": time_step_length
                }
            },
            "location": [2 + 3 * i, 1]
        },
        f"D_{i}": {
            "connection": {
                f"A_{i+1}": {
                    "a": 0,
                    "b": 1.0,
                    "capacity": capacity,
                    "free_flow_travel_time": time_step_length
                }
            },
            "location": [2 + 3 * i, -1]
        }
    })
    i += 1
  graph_dict[f"A_{i}"] = {
      "connection": {
          "END": {
              "a": 0,
              "b": 1.0,
              "capacity": capacity,
              "free_flow_travel_time": time_step_length
          }
      },
      "location": [0 + 3 * i, 0]
  }
  graph_dict["END"] = {"connection": {}, "location": [1 + 3 * i, 0]}
  time_horizon = int(3.0 * (num_network_in_series + 1) / time_step_length)
  destination = f"A_{i}->END"
  adjacency_list = {
      key: list(value["connection"].keys())
      for key, value in graph_dict.items()
  }
  bpr_a_coefficient = {}
  bpr_b_coefficient = {}
  capacity = {}
  free_flow_travel_time = {}
  for o_node, value_dict in graph_dict.items():
    for d_node, section_dict in value_dict["connection"].items():
      road_section = dynamic_routing_utils._road_section_from_nodes(
          origin=o_node, destination=d_node)
      bpr_a_coefficient[road_section] = section_dict["a"]
      bpr_b_coefficient[road_section] = section_dict["b"]
      capacity[road_section] = section_dict["capacity"]
      free_flow_travel_time[road_section] = section_dict[
          "free_flow_travel_time"]
  node_position = {key: value["location"] for key, value in graph_dict.items()}
  return dynamic_routing_utils.Network(
      adjacency_list,
      node_position=node_position,
      bpr_a_coefficient=bpr_a_coefficient,
      bpr_b_coefficient=bpr_b_coefficient,
      capacity=capacity,
      free_flow_travel_time=free_flow_travel_time
  ), origin, destination, time_horizon
References keys.
evolve_mean_field_game()
utils.evolve_mean_field_game (mfg_game, policy, graph, scaling = 1, frequency_printing = 1)
Definition at line 563 of file utils.py.
                           frequency_printing=1):
  distribution_mfg = distribution_module.DistributionPolicy(mfg_game, policy)
  root_state = mfg_game.new_initial_state()
  listing_states = [root_state]
  # plot_network_mean_field_game(graph, {origin: 1})
  i = 0
  while not listing_states[0].is_terminal() and not all(
      state._vehicle_without_legal_action for state in listing_states):  # pylint:disable=protected-access
    assert abs(sum(map(distribution_mfg.value, listing_states)) - 1) < 1e-4, (
        f"{list(map(distribution_mfg.value, listing_states))}")
    new_listing_states = []
    list_of_state_seen = set()
    # In case chance node:
    if listing_states[0].current_player() == pyspiel.PlayerId.CHANCE:
      for mfg_state in listing_states:
        for action, _ in mfg_state.chance_outcomes():
          new_mfg_state = mfg_state.child(action)
          # Do not append twice the same file.
          if str(new_mfg_state) not in list_of_state_seen:
            new_listing_states.append(new_mfg_state)
          list_of_state_seen.add(str(new_mfg_state))
      current_distribution = {}
      for mfg_state in new_listing_states:
        location = mfg_state._vehicle_location  # pylint:disable=protected-access
        if location not in current_distribution:
          current_distribution[location] = 0
        current_distribution[location] += distribution_mfg.value(mfg_state)
      plot_network_mean_field_game(graph, current_distribution, scaling=scaling)
    # In case mean field node:
    elif listing_states[0].current_player() == pyspiel.PlayerId.MEAN_FIELD:
      for mfg_state in listing_states:
        dist_to_register = mfg_state.distribution_support()
        def get_probability_for_state(str_state):
          try:
            return distribution_mfg.value_str(str_state)
          except ValueError:
            return 0
        dist = [
            get_probability_for_state(str_state)
            for str_state in dist_to_register
        ]
        new_mfg_state = mfg_state.clone()
        new_mfg_state.update_distribution(dist)
        # Do not append twice the same file.
        if str(new_mfg_state) not in list_of_state_seen:
          new_listing_states.append(new_mfg_state)
        list_of_state_seen.add(str(new_mfg_state))
    # In case action node:
    else:
      assert (listing_states[0].current_player() ==
              pyspiel.PlayerId.DEFAULT_PLAYER_ID), "The player id should be 0"
      for mfg_state in listing_states:
        for action, _ in policy.action_probabilities(mfg_state).items():
          new_mfg_state = mfg_state.child(action)
          # Do not append twice the same file.
          if str(new_mfg_state) not in list_of_state_seen:
            new_listing_states.append(new_mfg_state)
          list_of_state_seen.add(str(new_mfg_state))
      current_distribution = {}
      for mfg_state in new_listing_states:
        location = mfg_state._vehicle_location  # pylint:disable=protected-access
        if location not in current_distribution:
          current_distribution[location] = 0
        current_distribution[location] += distribution_mfg.value(mfg_state)
      assert abs(sum(current_distribution.values()) - 1) < 1e-4, (
          f"{current_distribution}")
      i += 1
      if i % frequency_printing == 0:
        plot_network_mean_field_game(
            graph, current_distribution, scaling=scaling)
    listing_states = new_listing_states
References plot_network_mean_field_game().
evolve_n_player_sequential_game()
utils.evolve_n_player_sequential_game (seq_game, policy, graph, debug = False)
Definition at line 509 of file utils.py.
def evolve_n_player_sequential_game(seq_game, policy, graph, debug=False):
  state = seq_game.new_initial_state()
  while not state.is_terminal():
    legal_actions = state.legal_actions()
    if state.is_chance_node():
      # Sample a chance event outcome.
      outcomes_with_probs = state.chance_outcomes()
      action_list, prob_list = zip(*outcomes_with_probs)
      action = np.random.choice(action_list, p=prob_list)
      if debug:
        print("------------ Change node ------------")
        print(
            (f"Possible chance actions: {outcomes_with_probs}, the one taken: "
             f"{action}."))
      state.apply_action(action)
    else:
      if debug:
        print("------------ Sequential action node ------------")
        print(state.information_state_tensor())
        print(state.observation_tensor())
        print(state.information_state_string())
      if policy is not None:
        state_policy = policy(state)
        vehicle_location = [
            s.replace("'", "")
            for s in str(state).split("[")[1].split("]")[0].split(", ")
        ]
        if debug:
          print((f"Policy for player {state.current_player()} at location "
                 f"{vehicle_location[state.current_player()]}: ") +
                str([(str(graph.get_road_section_from_action_id(k)) +
                      f"with probability {v}")
                     for k, v in state_policy.items()]))
        assert set(state_policy) == set(legal_actions)
        action = random.choices(legal_actions,
                                [state_policy[a] for a in legal_actions])
        assert len(action) == 1
        action = action[0]
      else:
        action = random.choice(legal_actions)
      state.apply_action(action)
      vehicle_location = [
          s.replace("'", "")
          for s in str(state).split("[")[1].split("]")[0].split(", ")
      ]
      if debug:
        print(vehicle_location)
      plot_network_n_player_game(
          graph,
          [graph.return_position_of_road_section(x) for x in vehicle_location])
  if debug:
    print(f"Travel times: {[-x for x in state.returns()]}")
References len, and plot_network_n_player_game().
evolve_n_player_simultaneous_game()
utils.evolve_n_player_simultaneous_game (game, policy, graph)
Definition at line 476 of file utils.py.
def evolve_n_player_simultaneous_game(game, policy, graph):
  state = game.new_initial_state()
  i = 0
  while not state.is_terminal():
    i += 1
    if state.is_chance_node():
      # Sample a chance event outcome.
      outcomes_with_probs = state.chance_outcomes()
      action_list, prob_list = zip(*outcomes_with_probs)
      action = np.random.choice(action_list, p=prob_list)
      state.apply_action(action)
    elif state.is_simultaneous_node():
      # Simultaneous node: sample actions for all players.
      chosen_actions = []
      for i in range(game.num_players()):
        legal_actions = state.legal_actions(i)
        state_policy = policy(state, i)
        assert len(legal_actions) == len(state_policy), (
            f"{legal_actions} not same length than {state_policy}")
        chosen_actions.append(
            random.choices(legal_actions,
                           [state_policy[a] for a in legal_actions])[0])
      state.apply_actions(chosen_actions)
    else:
      raise ValueError(
          "State should either be simultaneous node or change node.")
    plot_network_n_player_game(graph, [
        graph.return_position_of_road_section(x)
        for x in state.get_current_vehicle_locations()
    ])
  print(f"Travel times: {[-x for x in state.returns()]}")
References len, and plot_network_n_player_game().
external_sampling_monte_carlo_counterfactual_regret_minimization()
utils.external_sampling_monte_carlo_counterfactual_regret_minimization (seq_game, number_of_iterations, compute_metrics = False)
Definition at line 689 of file utils.py.
    seq_game, number_of_iterations, compute_metrics=False):
  cfr_solver = external_mccfr.ExternalSamplingSolver(
      seq_game, external_mccfr.AverageType.SIMPLE)
  tick_time = time.time()
  # print("CFRSolver initialized.")
  for _ in range(number_of_iterations):
    cfr_solver.iteration()
  timing = time.time() - tick_time
  # print("Finish.")
  if compute_metrics:
    nash_conv = exploitability.nash_conv(seq_game, cfr_solver.average_policy())
    return timing, cfr_solver.average_policy(), nash_conv
  return timing, cfr_solver.average_policy()
ficticious_play()
utils.ficticious_play (seq_game, number_of_iterations, compute_metrics = False)
Definition at line 653 of file utils.py.
def ficticious_play(seq_game, number_of_iterations, compute_metrics=False):
  xfp_solver = fictitious_play.XFPSolver(seq_game)
  tick_time = time.time()
  for _ in range(number_of_iterations):
    xfp_solver.iteration()
  timing = time.time() - tick_time
  # print('done')
  # average_policies = xfp_solver.average_policy_tables()
  tabular_policy = policy_module.TabularPolicy(seq_game)
  if compute_metrics:
    nash_conv = exploitability.nash_conv(seq_game, xfp_solver.average_policy())
    average_policy_values = expected_game_score.policy_value(
        seq_game.new_initial_state(), [tabular_policy])
    return timing, tabular_policy, nash_conv, average_policy_values
  return timing, tabular_policy
filter_terminal_infostates()
utils.filter_terminal_infostates (InfostateMapping infostates_map)
Filter out terminal infostate_node values.
Definition at line 87 of file utils.py.
def filter_terminal_infostates(infostates_map: InfostateMapping):
  """Filter out terminal infostate_node values."""
  return {
      infostate_string: infostate_node
      for infostate_string, infostate_node in infostates_map.items()
      if not infostate_node.is_terminal()
  }
Referenced by meta_learning.cfr_br_meta_data(), and meta_learning.MetaCFRRegretAgent.get_num_infostates().
first_action_policy_n_player()
utils.first_action_policy_n_player (seq_game)
Definition at line 649 of file utils.py.
def first_action_policy_n_player(seq_game):
  return policy_module.FirstActionPolicy(seq_game)
get_average_results_n_player_game()
utils.get_average_results_n_player_game (seq_game, policy, num_sample = 10)
Definition at line 908 of file utils.py.
def get_average_results_n_player_game(seq_game, policy, num_sample=10):
  result_array = get_list_results_n_player_game(seq_game, policy, num_sample)
  return sum([sum(i) / len(i) for i in zip(*result_array)]) / len(result_array)
References get_list_results_n_player_game(), and len.
get_batched_input()
utils.get_batched_input (List[jax.Array] input_list, List[InfostateNode] infostate_list, List[List[int]] illegal_action_list, int batch_size)
Returns list of function arguments extended to be consistent with batch size.
Args:
  input_list: List of DeviceArrays.
  infostate_list: List of information state nodes.
  illegal_action_list: List of List of illegal actions. Each internal list
    contains illegal actions in each information state.
  batch_size: Batch size.
Returns:
  input_list, infostate_list, and illegal_action_list with a size consistent
  with batch size (the size of returned arrays are multipliers of batch size).
Definition at line 30 of file utils.py.
                      illegal_action_list: List[List[int]], batch_size: int):
  """Returns list of function arguments extended to be consistent with batch size.
  Args:
    input_list: List of DeviceArrays.
    infostate_list: List of information state nodes.
    illegal_action_list: List of List of illegal actions. Each internal list
      contains illegal actions in each information state.
    batch_size: Batch size.
  Returns:
    input_list, infostate_list, and illegal_action_list with a size consistent
    with batch size (the size of returned arrays are multipliers of batch size).
  """
  items_to_sample = batch_size * (int(len(input_list) / batch_size) +
                                  1) - len(input_list)
  idx_sample = np.random.choice(len(input_list), items_to_sample)
  input_zip = np.array(
      list(zip(input_list, infostate_list, illegal_action_list)),
      dtype=object)
  input_lst_sample = input_zip[idx_sample]
  input_sample, infostate_sample, illegal_action_sample = zip(*input_lst_sample)
  input_list.extend(list(input_sample))
  infostate_list.extend(list(infostate_sample))
  illegal_action_list.extend(list(illegal_action_sample))
  return input_list, infostate_list, illegal_action_list
References len.
Referenced by meta_learning.compute_next_policy().
get_expected_value()
utils.get_expected_value (seq_game, policy, num_sample, player = 0)
Definition at line 948 of file utils.py.
def get_expected_value(seq_game, policy, num_sample, player=0):
  results = get_list_results_n_player_game(
      seq_game, policy, num_sample=num_sample)
  expected_value = sum(x[player] for x in results) / num_sample
  # num_vehicle = len(results[0])
  # error_bar = abs(sum([x[1] for x in results]) - sum(
  # [x[2] for x in results])) / num_sample_trajectories
  # expected_value_policy = sum(sum(x[i] for x in results) for i in range(
  # 1, BRAESS_NUM_VEHICLES)) / ((BRAESS_NUM_VEHICLES-1)*num_sample_trajectories)
  return expected_value
References get_list_results_n_player_game().
Referenced by compute_regret_policy().
get_expected_value_sim_game()
utils.get_expected_value_sim_game (game, policy, num_sample, player = 0)
Definition at line 976 of file utils.py.
def get_expected_value_sim_game(game, policy, num_sample, player=0):
  results = get_list_results_n_player_simulataneous_game(
      game, policy, num_sample=num_sample)
  assert len(results) == num_sample
  expected_value = sum(x[player] for x in results) / num_sample
  # num_vehicle = len(results[0])
  # error_bar = abs(sum([x[1] for x in results]) - sum(
  # [x[2] for x in results])) / num_sample_trajectories
  # expected_value_policy = sum(sum(x[i] for x in results) for i in range(
  # 1, BRAESS_NUM_VEHICLES)) / ((BRAESS_NUM_VEHICLES-1)*num_sample_trajectories)
  return expected_value
References get_list_results_n_player_simulataneous_game(), and len.
Referenced by compute_regret_policy_against_pure_policy_sim_game(), and compute_regret_policy_random_noise_sim_game().
get_list_results_n_player_game()
utils.get_list_results_n_player_game (seq_game, policy, num_sample = 10)
Definition at line 901 of file utils.py.
def get_list_results_n_player_game(seq_game, policy, num_sample=10):
  return [
      get_results_n_player_sequential_game(seq_game, policy)
      for _ in range(num_sample)
  ]
References get_results_n_player_sequential_game().
Referenced by get_average_results_n_player_game(), and get_expected_value().
get_list_results_n_player_simulataneous_game()
utils.get_list_results_n_player_simulataneous_game (game, policy, num_sample = 10)
Definition at line 941 of file utils.py.
def get_list_results_n_player_simulataneous_game(game, policy, num_sample=10):
  return [
      get_results_n_player_simultaneous_game(game, policy)
      for _ in range(num_sample)
  ]
References get_results_n_player_simultaneous_game().
Referenced by get_expected_value_sim_game().
get_network_output()
jax.Array utils.get_network_output (ApplyFn net_apply, Params net_params, np.ndarray net_input, List[int] illegal_actions, hk.PRNGSequence key)
Returns policy generated as output of model.
Args:
  net_apply: Haiku apply function.
  net_params: Haiku network parameters.
  net_input: Input of the model.
  illegal_actions: List of illegal actions we use to mask the model output.
  key: Pseudo random number.
Returns:
  Policy generated by model. Model output is filtered to mask illegal actions.
Definition at line 96 of file utils.py.
                       key: hk.PRNGSequence) -> jax.Array:
  """Returns policy generated as output of model.
  Args:
    net_apply: Haiku apply function.
    net_params: Haiku network parameters.
    net_input: Input of the model.
    illegal_actions: List of illegal actions we use to mask the model output.
    key: Pseudo random number.
  Returns:
    Policy generated by model. Model output is filtered to mask illegal actions.
  """
  net_output = jax.jit(net_apply)(net_params, key, net_input)
  if illegal_actions:
    net_output = jnp.delete(net_output, np.array(illegal_actions))
  return jax.nn.softmax(net_output)
get_network_output_batched()
List[jax.Array] utils.get_network_output_batched (ApplyFn net_apply, Params net_params, np.ndarray net_input, List[List[int]] all_illegal_actions, hk.PRNGSequence key)
Returns policy of batched input generated as output of model.
Args:
  net_apply: Haiku apply function.
  net_params: Haiku network parameters.
  net_input: Input of the model.
  all_illegal_actions: Nested list of illegal actions we use to mask the model
    output. Length of outer list is equal to the batch size.
  key: Pseudo random number.
Returns:
  List of policies generated by model. Model output is filtered to mask
  illegal actions. Length of the returned list is equal to batch size.
Definition at line 119 of file utils.py.
    key: hk.PRNGSequence) -> List[jax.Array]:
  """Returns policy of batched input generated as output of model.
  Args:
    net_apply: Haiku apply function.
    net_params: Haiku network parameters.
    net_input: Input of the model.
    all_illegal_actions: Nested list of illegal actions we use to mask the model
      output. Length of outer list is equal to the batch size.
    key: Pseudo random number.
  Returns:
    List of policies generated by model. Model output is filtered to mask
    illegal actions. Length of the returned list is equal to batch size.
  """
  net_output_batched = net_apply(net_params, next(key), net_input)
  batch_policies = []
  for i, illegal_actions in enumerate(all_illegal_actions):
    net_output = net_output_batched[i]
    if illegal_actions:
      net_output = jnp.expand_dims(
          jnp.delete(net_output, jnp.array(illegal_actions)), axis=0)
    batch_policies.append(jax.nn.softmax(net_output))
  return batch_policies
@functools.partial(jax.jit, static_argnums=(2, 3, 4, 5, 7, 9))
References next.
Referenced by meta_learning.compute_next_policy().
get_results_n_player_sequential_game()
utils.get_results_n_player_sequential_game (seq_game, policy)
Definition at line 882 of file utils.py.
def get_results_n_player_sequential_game(seq_game, policy):
  state = seq_game.new_initial_state()
  while not state.is_terminal():
    legal_actions = state.legal_actions()
    if state.is_chance_node():
      outcomes_with_probs = state.chance_outcomes()
      action_list, prob_list = zip(*outcomes_with_probs)
      action = np.random.choice(action_list, p=prob_list)
    else:
      state_policy = policy(state)
      assert set(state_policy) == set(legal_actions)
      action = random.choices(legal_actions,
                              [state_policy[a] for a in legal_actions])
      assert len(action) == 1
      action = action[0]
    state.apply_action(action)
  return state.returns()
References len.
Referenced by get_list_results_n_player_game().
get_results_n_player_simultaneous_game()
utils.get_results_n_player_simultaneous_game (game, policy)
Definition at line 913 of file utils.py.
def get_results_n_player_simultaneous_game(game, policy):
  state = game.new_initial_state()
  i = 0
  while not state.is_terminal():
    i += 1
    if state.is_chance_node():
      # Sample a chance event outcome.
      outcomes_with_probs = state.chance_outcomes()
      action_list, prob_list = zip(*outcomes_with_probs)
      action = np.random.choice(action_list, p=prob_list)
      state.apply_action(action)
    elif state.is_simultaneous_node():
      # Simultaneous node: sample actions for all players.
      chosen_actions = []
      for i in range(game.num_players()):
        legal_actions = state.legal_actions(i)
        state_policy = policy(state, player_id=i)
        assert abs(sum([state_policy[a] for a in legal_actions]) - 1) < 1e-4
        chosen_actions.append(
            random.choices(legal_actions,
                           [state_policy[a] for a in legal_actions])[0])
      state.apply_actions(chosen_actions)
    else:
      raise ValueError(
          "State should either be simultaneous node or change node.")
  return state.returns()
Referenced by get_list_results_n_player_simulataneous_game().
mask()
np.ndarray utils.mask (np.ndarray cfvalues, List[InfostateNode] infoset, int num_actions, int batch_size)
Returns counterfactual values of legal actions and put 0 for illegal ones.
Args:
  cfvalues: Numpy array of counterfactual values.
  infoset: List of information states.
  num_actions: Number of possible actions to take.
  batch_size: Batch size.
Returns:
  Masked counterfactual values. The counterfactual values of legal actions are
  kept as passed to this function and for illegal actions, we consider 0
  counterfactual value.
Definition at line 61 of file utils.py.
         batch_size: int) -> np.ndarray:
  """Returns counterfactual values of legal actions and put 0 for illegal ones.
  Args:
    cfvalues: Numpy array of counterfactual values.
    infoset: List of information states.
    num_actions: Number of possible actions to take.
    batch_size: Batch size.
  Returns:
    Masked counterfactual values. The counterfactual values of legal actions are
    kept as passed to this function and for illegal actions, we consider 0
    counterfactual value.
  """
  legal_actions = [[infoset[i].world_state.state.legal_actions()] *
                   cfvalues.shape[1] for i in range(batch_size)]
  masked_cfvalues = np.zeros(shape=[batch_size, cfvalues.shape[1], num_actions])
  for i in range(cfvalues.shape[0]):
    for j in range(cfvalues.shape[1]):
      np.put(masked_cfvalues[i][j], legal_actions[i][j], cfvalues[i][j])
  return np.stack(masked_cfvalues)
mean_field_fictitious_play()
utils.mean_field_fictitious_play (mfg_game, number_of_iterations, compute_metrics = False)
Definition at line 819 of file utils.py.
                               compute_metrics=False):
  fp = mean_field_fictitious_play_module.FictitiousPlay(mfg_game)
  tick_time = time.time()
  for _ in range(number_of_iterations):
    fp.iteration()
  timing = time.time() - tick_time
  fp_policy = fp.get_policy()
  # print('learning done')
  if compute_metrics:
    distribution_mfg = distribution_module.DistributionPolicy(
        mfg_game, fp_policy)
    # print('distribution done')
    policy_value_ = policy_value.PolicyValue(mfg_game, distribution_mfg,
                                             fp_policy).value(
                                                 mfg_game.new_initial_state())
    nash_conv_fp = nash_conv_module.NashConv(mfg_game, fp_policy)
    return timing, fp_policy, nash_conv_fp, policy_value_
  return timing, fp_policy
mean_field_uniform_policy()
utils.mean_field_uniform_policy (mfg_game, number_of_iterations, compute_metrics = False)
Definition at line 804 of file utils.py.
                              compute_metrics=False):
  del number_of_iterations
  uniform_policy = policy_module.UniformRandomPolicy(mfg_game)
  if compute_metrics:
    distribution_mfg = distribution_module.DistributionPolicy(
        mfg_game, uniform_policy)
    policy_value_ = policy_value.PolicyValue(mfg_game, distribution_mfg,
                                             uniform_policy).value(
                                                 mfg_game.new_initial_state())
    return uniform_policy, policy_value_
  return uniform_policy
meta_loss() [1/2]
utils.meta_loss (opt_params, net_apply, payoff, steps)
Returns the meta learning loss value.
Args:
  opt_params: Optimizer parameters.
  net_apply: Apply function.
  payoff: Payoff matrix.
  steps: Number of steps.
Returns:
  Accumulated loss value over number of steps.
Definition at line 25 of file utils.py.
def meta_loss(opt_params, net_apply, payoff, steps):
  """Returns the meta learning loss value.
  Args:
    opt_params: Optimizer parameters.
    net_apply: Apply function.
    payoff: Payoff matrix.
    steps: Number of steps.
  Returns:
    Accumulated loss value over number of steps.
  """
  regret_sum_x = np.zeros(shape=[FLAGS.batch_size, 1, FLAGS.num_actions])
  regret_sum_y = np.zeros(shape=[FLAGS.batch_size, 1, FLAGS.num_actions])
  total_loss = 0
  step = 0
  @jax.jit
  def scan_body(carry, x):
    nonlocal regret_sum_x
    nonlocal regret_sum_y
    regret_sum_x, regret_sum_y, current_step, total_loss = carry
    x = net_apply(opt_params, None, regret_sum_x / (current_step + 1))
    y = net_apply(opt_params, None, regret_sum_y / (current_step + 1))
    strategy_x = jax.nn.softmax(x)
    strategy_y = jnp.transpose(jax.nn.softmax(y), [0, 2, 1])
    values_x = jnp.matmul(payoff, strategy_y)  # val_x = payoff * st_y
    values_y = -jnp.matmul(strategy_x, payoff)  # val_y = -1 * payoff * st_x
    value_x = jnp.matmul(jnp.matmul(strategy_x, payoff), strategy_y)
    value_y = -value_x
    curren_regret_x = values_x - value_x
    curren_regret_y = values_y - value_y
    curren_regret_x = jnp.transpose(curren_regret_x, [0, 2, 1])
    regret_sum_x += curren_regret_x
    regret_sum_y += curren_regret_y
    current_loss = jnp.mean(jnp.max(
        jax.numpy.concatenate([curren_regret_x, curren_regret_y], axis=2),
        axis=[1, 2]), axis=-1)
    total_loss += current_loss
    current_step += 1
    return (regret_sum_x, regret_sum_y, current_step, total_loss), None
  (regret_sum_x, regret_sum_y, step, total_loss), _ = jax.lax.scan(
      scan_body,
      (regret_sum_x, regret_sum_y, step, total_loss),
      None,
      length=steps,
  )
  return total_loss
meta_loss() [2/2]
float utils.meta_loss (Params net_params, np.ndarray cfvalues, ApplyFn net_apply, int steps, int num_all_actions, List[InfostateNode] infosets, InfostateMapping infostate_map, int batch_size, hk.PRNGSequence key, bool use_infostate_representation = True)
Meta learning loss function.
Args:
  net_params: Network parameters.
  cfvalues: Counterfactual values.
  net_apply: Haiku apply function.
  steps: Number of unrolling steps.
  num_all_actions: Number of actions.
  infosets: List of information states.
  infostate_map: Mapping from information state string to information state
    node.
  batch_size: Batch size.
  key: Pseudo random number.
  use_infostate_representation: Boolean value indicating if information state
    representation is used as part of input.
Returns:
  Mean meta learning loss value.
Definition at line 151 of file utils.py.
              use_infostate_representation: bool = True) -> float:
  """Meta learning loss function.
  Args:
    net_params: Network parameters.
    cfvalues: Counterfactual values.
    net_apply: Haiku apply function.
    steps: Number of unrolling steps.
    num_all_actions: Number of actions.
    infosets: List of information states.
    infostate_map: Mapping from information state string to information state
      node.
    batch_size: Batch size.
    key: Pseudo random number.
    use_infostate_representation: Boolean value indicating if information state
      representation is used as part of input.
  Returns:
    Mean meta learning loss value.
  """
  regret_sum = np.zeros(shape=[batch_size, 1, num_all_actions])
  total_loss = 0
  step = 0
  infostate_str_one_hot = jnp.expand_dims(
      jnp.array([
          jax.nn.one_hot(infostate_map[infoset.infostate_string],
                         len(infostate_map)) for infoset in infosets
      ]),
      axis=1)
  def scan_body(carry, x):
    del x  # Unused
    regret_sum, current_step, total_loss = carry
    average_regret = regret_sum / (current_step + 1)
    if use_infostate_representation:
      net_input = jnp.concatenate((average_regret, infostate_str_one_hot),
                                  axis=-1)
    else:
      net_input = average_regret
    next_step_x = jax.jit(net_apply)(net_params, key, net_input)
    strategy = jax.nn.softmax(next_step_x)
    value = jnp.matmul(
        jnp.array(cfvalues), jnp.transpose(strategy, axes=[0, 2, 1]))
    curren_regret = jnp.array(cfvalues) - value
    regret_sum += jnp.expand_dims(jnp.mean(curren_regret, axis=1), axis=1)
    current_loss = jnp.mean(
        jnp.max(
            jax.numpy.concatenate(
                [regret_sum,
                 jnp.zeros(shape=[batch_size, 1, 1])],
                axis=-1),
            axis=-1))
    total_loss += current_loss
    current_step += 1
    return (regret_sum, current_step, total_loss), None
  (regret_sum, step, total_loss), _ = jax.lax.scan(
      scan_body, (regret_sum, step, total_loss), None, length=steps)
  return total_loss
References len.
neural_ficticious_self_play()
utils.neural_ficticious_self_play (seq_game, num_epoch, sess, compute_metrics = False)
Definition at line 739 of file utils.py.
                                compute_metrics=False):
  env = rl_environment.Environment(seq_game)
  # Parameters from the game.
  num_players = env.num_players
  num_actions = env.action_spec()["num_actions"]
  info_state_size = env.observation_spec()["info_state"][0]
  # Parameters for the algorithm.
  hidden_layers_sizes = [int(l) for l in [128]]
  kwargs = {
      "replay_buffer_capacity": int(2e5),
      "reservoir_buffer_capacity": int(2e6),
      "min_buffer_size_to_learn": 1000,
      "anticipatory_param": 0.1,
      "batch_size": 128,
      "learn_every": 64,
      "rl_learning_rate": 0.01,
      "sl_learning_rate": 0.01,
      "optimizer_str": "sgd",
      "loss_str": "mse",
      "update_target_network_every": 19200,
      "discount_factor": 1.0,
      "epsilon_decay_duration": int(20e6),
      "epsilon_start": 0.06,
      "epsilon_end": 0.001,
  }
  # freq_epoch_printing = num_epoch // 10
  agents = [
      nfsp.NFSP(sess, idx, info_state_size, num_actions, hidden_layers_sizes,
                **kwargs) for idx in range(num_players)
  ]
  joint_avg_policy = NFSPPolicies(env, agents, nfsp.MODE.average_policy)
  sess.run(tf.global_variables_initializer())
  # print("TF initialized.")
  tick_time = time.time()
  for _ in range(num_epoch):
    # if ep % freq_epoch_printing == 0:
    #   print(f"Iteration {ep}")
    time_step = env.reset()
    while not time_step.last():
      player_id = time_step.observations["current_player"]
      agent_output = agents[player_id].step(time_step)
      action_list = [agent_output.action]
      time_step = env.step(action_list)
    # Episode is over, step all agents with final info state.
    for agent in agents:
      agent.step(time_step)
  timing = time.time() - tick_time
  # print("Finish.")
  if compute_metrics:
    tabular_policy = joint_avg_policy.TabularPolicy(seq_game)
    average_policy_values = expected_game_score.policy_value(
        seq_game.new_initial_state(), [tabular_policy])
    nash_conv = exploitability.nash_conv(env.game, joint_avg_policy)
    return timing, joint_avg_policy, average_policy_values, nash_conv
  return timing, joint_avg_policy
online_mirror_descent()
utils.online_mirror_descent (mfg_game, number_of_iterations, compute_metrics = False, return_policy = False, md_p = None)
Definition at line 841 of file utils.py.
                          md_p=None):
  md = md_p if md_p else mirror_descent.MirrorDescent(mfg_game)
  tick_time = time.time()
  for _ in range(number_of_iterations):
    md.iteration()
  timing = time.time() - tick_time
  md_policy = md.get_policy()
  if compute_metrics:
    distribution_mfg = distribution_module.DistributionPolicy(
        mfg_game, md_policy)
    # print('distribution done')
    policy_value_ = policy_value.PolicyValue(mfg_game, distribution_mfg,
                                             md_policy).value(
                                                 mfg_game.new_initial_state())
    nash_conv_md = nash_conv_module.NashConv(mfg_game, md_policy)
    if return_policy:
      return timing, md_policy, nash_conv_md, policy_value_, md
    return timing, md_policy, nash_conv_md, policy_value_
  return timing, md_policy
online_mirror_descent_sioux_falls()
utils.online_mirror_descent_sioux_falls (mfg_game, number_of_iterations, md_p = None)
Definition at line 1094 of file utils.py.
                                      md_p=None):
  nash_conv_dict = {}
  md = md_p if md_p else mirror_descent.MirrorDescent(mfg_game)
  tick_time = time.time()
  for i in range(number_of_iterations):
    md.iteration()
    md_policy = md.get_policy()
    nash_conv_md = nash_conv_module.NashConv(mfg_game, md_policy)
    nash_conv_dict[i] = nash_conv_md.nash_conv()
    print((f"Iteration {i}, Nash conv: {nash_conv_md.nash_conv()}, "
           "time: {time.time() - tick_time}"))
  timing = time.time() - tick_time
  md_policy = md.get_policy()
  distribution_mfg = distribution_module.DistributionPolicy(mfg_game, md_policy)
  policy_value_ = policy_value.PolicyValue(
      mfg_game, distribution_mfg, md_policy).value(mfg_game.new_initial_state())
  nash_conv_md = nash_conv_module.NashConv(mfg_game, md_policy)
  return timing, md_policy, nash_conv_md, policy_value_, md, nash_conv_dict
plot_network_mean_field_game()
utils.plot_network_mean_field_game (dynamic_routing_utils.Network g, distribution = None, scaling = 1)
Plot the network.
Args:
  g: network to plot
  distribution: the distribution.
  scaling: scaling factor. for plot rendering.
Definition at line 438 of file utils.py.
                                 scaling=1):
  """Plot the network.
  Args:
    g: network to plot
    distribution: the distribution.
    scaling: scaling factor. for plot rendering.
  """
  _, ax = plt.subplots()
  o_xs, o_ys, d_xs, d_ys = g.return_list_for_matplotlib_quiver()
  ax.quiver(
      o_xs,
      o_ys,
      np.subtract(d_xs, o_xs),
      np.subtract(d_ys, o_ys),
      color="b",
      angles="xy",
      scale_units="xy",
      scale=1)
  ax.set_xlim([
      np.min(np.concatenate((o_xs, d_xs))) - 0.5,
      np.max(np.concatenate((o_xs, d_xs))) + 0.5
  ])
  ax.set_ylim([
      np.min(np.concatenate((o_ys, d_ys))) - 0.5,
      np.max(np.concatenate((o_ys, d_ys))) + 0.5
  ])
  if distribution is not None:
    for x, prob_of_position in distribution.items():
      point = g.return_position_of_road_section(x)
      width = 0.3 * scaling * prob_of_position
      circle = plt.Circle(point, width, color="r")
      ax.add_patch(circle)
Referenced by evolve_mean_field_game().
plot_network_n_player_game()
utils.plot_network_n_player_game (dynamic_routing_utils.Network g, vehicle_locations = None)
Plot the network.
Args:
  g: network to plot
  vehicle_locations: vehicle location
Definition at line 398 of file utils.py.
                               vehicle_locations=None):
  """Plot the network.
  Args:
    g: network to plot
    vehicle_locations: vehicle location
  """
  _, ax = plt.subplots()
  o_xs, o_ys, d_xs, d_ys = g.return_list_for_matplotlib_quiver()
  ax.quiver(
      o_xs,
      o_ys,
      np.subtract(d_xs, o_xs),
      np.subtract(d_ys, o_ys),
      color="b",
      angles="xy",
      scale_units="xy",
      scale=1)
  ax.set_xlim([
      np.min(np.concatenate((o_xs, d_xs))) - 0.5,
      np.max(np.concatenate((o_xs, d_xs))) + 0.5
  ])
  ax.set_ylim([
      np.min(np.concatenate((o_ys, d_ys))) - 0.5,
      np.max(np.concatenate((o_ys, d_ys))) + 0.5
  ])
  if vehicle_locations is not None:
    num_vehicle = len(vehicle_locations)
    dict_location = {}
    for vehicle_location in vehicle_locations:
      if vehicle_location not in dict_location:
        dict_location[vehicle_location] = 0.0
      dict_location[vehicle_location] += 0.3 / num_vehicle
    for point, width in dict_location.items():
      circle = plt.Circle(point, width, color="r")
      ax.add_patch(circle)
References len.
Referenced by evolve_n_player_sequential_game(), and evolve_n_player_simultaneous_game().
uniform_policy_n_player()
utils.uniform_policy_n_player (seq_game)
Definition at line 645 of file utils.py.
def uniform_policy_n_player(seq_game):
  return policy_module.UniformRandomPolicy(seq_game)
Variable Documentation
FLAGS
utils.FLAGS = flags.FLAGS
Definition at line 22 of file utils.py.