open spiel: absl::types_internal Namespace Reference
absl::types_internal Namespace Reference
Classes
struct Always
class Archetype
class Archetype< Prof, typename std::enable_if< PropertiesOfT< Prof >::move_constructible_support !=move_constructible::maybe &&PropertiesOfT< Prof >::move_assignable_support==move_assignable::maybe &&PropertiesOfT< Prof >::destructible_support !=destructible::maybe >::type >
class Archetype< Prof, typename std::enable_if< PropertiesOfT< Prof >::move_constructible_support !=move_constructible::maybe &&PropertiesOfT< Prof >::move_assignable_support==move_assignable::maybe &&PropertiesOfT< Prof >::destructible_support==destructible::maybe >::type >
class Archetype< Prof, typename std::enable_if< PropertiesOfT< Prof >::move_constructible_support==move_constructible::maybe &&PropertiesOfT< Prof >::move_assignable_support !=move_assignable::maybe &&PropertiesOfT< Prof >::destructible_support !=destructible::maybe >::type >
class Archetype< Prof, typename std::enable_if< PropertiesOfT< Prof >::move_constructible_support==move_constructible::maybe &&PropertiesOfT< Prof >::move_assignable_support !=move_assignable::maybe &&PropertiesOfT< Prof >::destructible_support==destructible::maybe >::type >
class Archetype< Prof, typename std::enable_if< PropertiesOfT< Prof >::move_constructible_support==move_constructible::maybe &&PropertiesOfT< Prof >::move_assignable_support==move_assignable::maybe &&PropertiesOfT< Prof >::destructible_support !=destructible::maybe >::type >
class Archetype< Prof, typename std::enable_if< PropertiesOfT< Prof >::move_constructible_support==move_constructible::maybe &&PropertiesOfT< Prof >::move_assignable_support==move_assignable::maybe &&PropertiesOfT< Prof >::destructible_support==destructible::maybe >::type >
struct ArchetypeCopyAssign
struct ArchetypeCopyAssign< DefaultConstructibleValue, MoveConstructibleValue, CopyConstructibleValue, MoveAssignableValue, copy_assignable::maybe >
struct ArchetypeCopyAssign< DefaultConstructibleValue, MoveConstructibleValue, CopyConstructibleValue, MoveAssignableValue, copy_assignable::trivial >
struct ArchetypeCopyConstructor
struct ArchetypeCopyConstructor< DefaultConstructibleValue, MoveConstructibleValue, copy_constructible::maybe >
struct ArchetypeCopyConstructor< DefaultConstructibleValue, MoveConstructibleValue, copy_constructible::trivial >
struct ArchetypeDestructor
struct ArchetypeDestructor< DefaultConstructibleValue, MoveConstructibleValue, CopyConstructibleValue, MoveAssignableValue, CopyAssignableValue, destructible::trivial >
struct ArchetypeMoveAssign
struct ArchetypeMoveAssign< DefaultConstructibleValue, MoveConstructibleValue, CopyConstructibleValue, move_assignable::trivial >
struct ArchetypeMoveConstructor
struct ArchetypeMoveConstructor< DefaultConstructibleValue, move_constructible::trivial >
struct ArchetypeStateBase
struct ArchetypeStateBase< default_constructible::maybe >
struct ArchetypeStateBase< default_constructible::trivial >
struct AreEquivalenceClassesOfTheSameType
struct AreEquivalenceClassesOfTheSameType< EquivalenceClassType< Funs... > >
struct AreEquivalenceClassesOfTheSameType< EquivalenceClassType< HeadHeadFun, TailHeadFuns... >, EquivalenceClassType< HeadNextFun, TailNextFuns... >, TailEqClasses... >
struct AreEquivalenceClassesOfTheSameType< EquivalenceClassType< HeadHeadFun, TailHeadFuns... >, EquivalenceClassType<>, TailEqClasses... >
struct AreEquivalenceClassesOfTheSameType< EquivalenceClassType<>, EquivalenceClassType< HeadNextFun, TailNextFuns... >, TailEqClasses... >
struct AreEquivalenceClassesOfTheSameType< EquivalenceClassType<>, EquivalenceClassType<>, TailEqClasses... >
struct AreEquivalenceClassesOfTheSameType<>
struct AreGeneratorsWithTheSameReturnType
struct AreGeneratorsWithTheSameReturnTypeImpl
struct AreGeneratorsWithTheSameReturnTypeImpl< typename std::enable_if< absl::conjunction< std::is_same< ResultOfGeneratorT< Head >, ResultOfGeneratorT< Tail > >... >::value >::type, Head, Tail... >
struct AreGeneratorsWithTheSameReturnTypeImpl< void >
struct CombineProfiles
struct CombineProfiles<>
struct CombineProfilesImpl
class ConformanceErrors
struct ConformanceProfile
struct conservative_hashable_support_of
struct conservative_hashable_support_of< T, CheckHashability::no >
struct conservative_hashable_support_of< T, CheckHashability::yes >
struct EnabledHash
struct EquivalenceClassMaker
struct EquivalenceClassType
struct ExceptionalBool
struct ExpectBiggerGeneratorThan
struct ExpectBiggerGeneratorThanComparisons
struct ExpectBiggerGeneratorThanEqClasses
struct ExpectBiggerGeneratorThanEqClassesComparisons
struct ExpectConformanceOf
struct ExpectConsistency
struct ExpectCopyAssign
struct ExpectCopyConstructOneGenerator
struct ExpectDefaultConstructWithCopyAssign
struct ExpectDefaultConstructWithDestruct
struct ExpectDefaultConstructWithMoveAssign
struct ExpectEquivalenceClass
struct ExpectEquivalenceClassComparison
struct ExpectEquivalenceClassComparisons
struct ExpectEquivalenceClassConsistency
struct ExpectHashable
struct ExpectModels
struct ExpectMoveAssign
struct ExpectMoveConstructOneGenerator
struct ExpectOrderedEquivalenceClasses
struct ExpectOrderedEquivalenceClassesComparisons
struct ExpectSameHash
struct ExpectSelfComparison
struct ExpectSelfCopyAssign
struct ExpectSelfMoveAssign
struct ExpectSelfSwap
struct ExpectSwap
struct ForEachParameterFun
struct ForEveryTwoImpl
struct GeneratorType
struct GivenDeclaration
struct If
struct If< false >
struct If< true >
struct IsArchetype
struct IsArchetype< Archetype< Prof > >
struct IsEquivalenceClass
struct IsEquivalenceClass< EquivalenceClassType< Head, Tail... > >
struct IsEquivalenceClass< EquivalenceClassType<> >
struct IsNothrowOpable
struct IsNothrowOpableImpl
struct IsNothrowOpableImpl< T, Op, absl::enable_if_t< Op< T >::value > >
struct IsNullaryCallable
struct IsNullaryCallableImpl
struct IsNullaryCallableImpl< Fun, absl::void_t< decltype(std::declval< const Fun & >()())> >
struct IsOpable
struct IsOpableImpl
struct IsOpableImpl< T, Op, absl::void_t< Op< T > > >
struct IsProfile
struct IsProfileImpl
struct IsProfileImpl< T, absl::void_t< PropertiesOfT< T > > >
struct IsProfileOrProfileRange
struct IsProfileOrProfileRange< StrictProfileRange< StrictnessDomain, LogicalProf, MinProf, MaxProf > >
struct MakeArchetypeState
struct MakeStrictProfileRange
struct MakeStrictProfileRange< StrictnessDomain, ProfileRange< LogicalProf, MinProf, MaxProf > >
struct MinimalCheckableProfile
struct MinimalProfiles
struct NoError
struct NothrowBool
struct OrderedEquivalenceClasses
struct PoisonedHash
struct ProfileRange
struct ProfileRangeOf
struct ProfileRangeOf< StrictProfileRange< StrictnessDomain, LogicalProf, MinProf, MaxProf > >
struct ProfileRangeOfImpl
struct ProfileRangeOfImpl< T, absl::void_t< PropertiesOfT< T > > >
struct PropertiesOf
struct PropertiesOfArchetype
struct PropertiesOfArchetype< Archetype< Prof > >
struct PropertiesOfImpl
struct PropertiesOfImpl< T, absl::void_t< typename T::profile_alias_of > >
struct PropertiesOfImpl< T, absl::void_t< typename T::properties > >
struct RegularityDomain
struct ResultOfGenerator
struct ResultOfGenerator< GeneratorType< Fun > >
struct StrictProfileRange
struct StrongProfileTypedef
struct SyntacticConformanceProfileOf
Typedefs
template<template< class... > class Receiver>
using ExpandBasicProfiles
template<template< class... > class Receiver>
using ExpandBasicEquatableProfiles
template<template< class... > class Receiver>
using ExpandBasicComparableProfiles
template<template< class... > class Receiver>
using ExpandBasicHashableProfiles
template<template< class... > class Receiver>
using ExpandBasicDefaultConstructibleProfiles
template<template< class... > class Receiver>
using ExpandSupportedProfiles
template<class Archetype >
using PropertiesOfArchetypeT = typename PropertiesOfArchetype<Archetype>::type
using ArchetypeState = std::size_t
template<default_constructible DefaultConstructibleValue, move_constructible MoveConstructibleValue, copy_constructible CopyConstructibleValue, move_assignable MoveAssignableValue, copy_assignable CopyAssignableValue, destructible DestructibleValue>
using ArchetypeSpecialMembersBase
template<class T >
using PropertiesOfT = typename PropertiesOf<T>::type
template<class T >
using AlwaysFalse = std::false_type
template<class StrictnessDomain , class ProfOrRange >
using MakeStrictProfileRangeT
using MostStrictProfile
template<class LogicalProf , class MinProf = LogicalProf>
using LooseProfileRange
template<class Prof >
using MakeLooseProfileRangeT = Prof
template<class T >
using ProfileRangeOfT = typename ProfileRangeOf<T>::type
template<class T >
using LogicalProfileOfT = typename ProfileRangeOfT<T>::logical_profile
template<class T >
using MinProfileOfT = typename ProfileRangeOfT<T>::min_profile
template<class T >
using MaxProfileOfT = typename ProfileRangeOfT<T>::max_profile
template<class T >
using ExpectConformanceOfType = ExpectConformanceOf<true, T>
template<class T >
using ExpectNonconformanceOfType
template<class Fun >
using ResultOfGeneratorT = typename ResultOfGenerator<GeneratorType<Fun>>::type
Enumerations
enum class function_support { maybe , yes , nothrow , trivial }
enum class hashable { maybe , yes }
enum class CheckHashability { no , yes }
Functions
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialDefaultConstructor, ConformanceProfile< default_constructible::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowDefaultConstructor, ConformanceProfile< default_constructible::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasDefaultConstructor, ConformanceProfile< default_constructible::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialMoveConstructor, ConformanceProfile< default_constructible::maybe, move_constructible::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowMoveConstructor, ConformanceProfile< default_constructible::maybe, move_constructible::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasMoveConstructor, ConformanceProfile< default_constructible::maybe, move_constructible::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialCopyConstructor, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowCopyConstructor, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasCopyConstructor, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialMoveAssign, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowMoveAssign, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasMoveAssign, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialCopyAssign, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowCopyAssign, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasCopyAssign, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialDestructor, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowDestructor, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasDestructor, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowEquality, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasEquality, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowInequality, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasInequality, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowLessThan, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasLessThan, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowLessEqual, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasLessEqual, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowGreaterEqual, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasGreaterEqual, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowGreaterThan, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasGreaterThan, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowSwap, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::maybe, swappable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasSwap, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::maybe, swappable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasStdHashSpecialization, ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::maybe, swappable::maybe, hashable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (Equatable, CombineProfiles< HasEqualityProfile, HasInequalityProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (Comparable, CombineProfiles< EquatableProfile, HasLessThanProfile, HasLessEqualProfile, HasGreaterEqualProfile, HasGreaterThanProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (NothrowEquatable, CombineProfiles< HasNothrowEqualityProfile, HasNothrowInequalityProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (NothrowComparable, CombineProfiles< NothrowEquatableProfile, HasNothrowLessThanProfile, HasNothrowLessEqualProfile, HasNothrowGreaterEqualProfile, HasNothrowGreaterThanProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (Value, CombineProfiles< HasNothrowMoveConstructorProfile, HasCopyConstructorProfile, HasNothrowMoveAssignProfile, HasCopyAssignProfile, HasNothrowDestructorProfile, HasNothrowSwapProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (EquatableValue, CombineProfiles< EquatableProfile, ValueProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableValue, CombineProfiles< ComparableProfile, ValueProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (DefaultConstructibleValue, CombineProfiles< HasDefaultConstructorProfile, ValueProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (NothrowMoveConstructible, CombineProfiles< HasNothrowMoveConstructorProfile, HasNothrowDestructorProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (EquatableNothrowMoveConstructible, CombineProfiles< EquatableProfile, NothrowMoveConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableNothrowMoveConstructible, CombineProfiles< ComparableProfile, NothrowMoveConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (DefaultConstructibleNothrowMoveConstructible, CombineProfiles< HasDefaultConstructorProfile, NothrowMoveConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (CopyConstructible, CombineProfiles< HasNothrowMoveConstructorProfile, HasCopyConstructorProfile, HasNothrowDestructorProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (EquatableCopyConstructible, CombineProfiles< EquatableProfile, CopyConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableCopyConstructible, CombineProfiles< ComparableProfile, CopyConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (DefaultConstructibleCopyConstructible, CombineProfiles< HasDefaultConstructorProfile, CopyConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (NothrowMovable, CombineProfiles< HasNothrowMoveConstructorProfile, HasNothrowMoveAssignProfile, HasNothrowDestructorProfile, HasNothrowSwapProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (EquatableNothrowMovable, CombineProfiles< EquatableProfile, NothrowMovableProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableNothrowMovable, CombineProfiles< ComparableProfile, NothrowMovableProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (DefaultConstructibleNothrowMovable, CombineProfiles< HasDefaultConstructorProfile, NothrowMovableProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (TrivialSpecialMemberFunctions, CombineProfiles< HasTrivialDefaultConstructorProfile, HasTrivialMoveConstructorProfile, HasTrivialCopyConstructorProfile, HasTrivialMoveAssignProfile, HasTrivialCopyAssignProfile, HasTrivialDestructorProfile, HasNothrowSwapProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (TriviallyComplete, CombineProfiles< TrivialSpecialMemberFunctionsProfile, ComparableProfile, HasStdHashSpecializationProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HashableNothrowMoveConstructible, CombineProfiles< HasStdHashSpecializationProfile, NothrowMoveConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HashableCopyConstructible, CombineProfiles< HasStdHashSpecializationProfile, CopyConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HashableNothrowMovable, CombineProfiles< HasStdHashSpecializationProfile, NothrowMovableProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HashableValue, CombineProfiles< HasStdHashSpecializationProfile, ValueProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableHashableValue, CombineProfiles< HashableValueProfile, ComparableProfile >)
template<class Arch >
Arch MakeArchetype (ArchetypeState state)
template<class Prof , class T >
constexpr bool ShouldDeleteConstructor ()
template<class Prof , class T >
constexpr bool ShouldDeleteAssign ()
template<class Prof , absl::enable_if_t<!PropertiesOfT< Prof >::is_swappable, int > = 0>
void swap (Archetype< Prof > &, Archetype< Prof > &)=delete
ABSL_TYPES_INTERNAL_OP (equality_comparable,==)
ABSL_TYPES_INTERNAL_OP (inequality_comparable, !=)
ABSL_TYPES_INTERNAL_OP (less_than_comparable,<)
ABSL_TYPES_INTERNAL_OP (less_equal_comparable,<=)
ABSL_TYPES_INTERNAL_OP (greater_equal_comparable, >=)
ABSL_TYPES_INTERNAL_OP (greater_than_comparable, >)
template<typename Enum >
constexpr absl::underlying_type_t< Enum > UnderlyingValue (Enum value)
constexpr const char * PessimisticPropertyDescription (function_support v)
std::string ExpectedFunctionKindList (function_support min, function_support max)
template<class Enum >
void ExpectModelOfImpl (ConformanceErrors *errors, Enum min_support, Enum max_support, Enum kind)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for default construction", default_constructible)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for move construction", move_constructible)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for copy construction", copy_constructible)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for move assignment", move_assignable)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for copy assignment", copy_assignable)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for destruction", destructible)
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ("support for ==", equality_comparable)
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ("support for <=", less_equal_comparable)
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ("support for >=", greater_equal_comparable)
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ("support for >", greater_than_comparable)
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ("support for swap", swappable)
constexpr const char * PropertyName (hashable v)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (DefaultConstructible, default_constructible)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (MoveConstructible, move_constructible)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (CopyConstructible, copy_constructible)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (MoveAssignable, move_assignable)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (CopyAssignable, copy_assignable)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (Destructible, destructible)
void BoolFunction (bool) noexcept
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (EqualityComparable, equality_comparable,==)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (InequalityComparable, inequality_comparable, !=)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (LessThanComparable, less_than_comparable,<)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (LessEqualComparable, less_equal_comparable,<=)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (GreaterEqualComparable, greater_equal_comparable, >=)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (GreaterThanComparable, greater_than_comparable, >)
template<class T >
constexpr swappable swappable_support_of ()
template<class T , class MinProf , class MaxProf >
void ExpectModelOfSwappable (ConformanceErrors *errors)
template<class T >
constexpr hashable hashable_support_of ()
template<class T , class MinProf , class MaxProf >
void ExpectModelOfHashable (ConformanceErrors *errors)
template<class H >
constexpr H MinEnum (H head)
template<class H , class N , class... T>
constexpr H MinEnum (H head, N next, T... tail)
template<class H >
constexpr H MaxEnum (H head)
template<class H , class N , class... T>
constexpr H MaxEnum (H head, N next, T... tail)
constexpr bool constexpr_instantiation_when_unevaluated ()
constexpr bool poisoned_hash_fails_instantiation ()
template<class Fun , absl::enable_if_t< IsNullaryCallable< Fun >::value > ** = nullptr>
GeneratorType< Fun > Generator (Fun fun, const char *description)
template<class... Funs, absl::enable_if_t< AreGeneratorsWithTheSameReturnType< Funs... >::value > ** = nullptr>
EquivalenceClassType< Funs... > EquivalenceClass (GeneratorType< Funs >... funs)
template<class... Decls>
std::string PrepareGivenContext (const Decls &... decls)
ABSL_INTERNAL_EXPECT_OP (Eq,==)
ABSL_INTERNAL_EXPECT_OP (Ne, !=)
ABSL_INTERNAL_EXPECT_OP (Lt,<)
ABSL_INTERNAL_EXPECT_OP (Le,<=)
ABSL_INTERNAL_EXPECT_OP (Ge, >=)
ABSL_INTERNAL_EXPECT_OP (Gt, >)
template<class T , class Prof >
void ExpectOneWayEquality (ConformanceErrors *errors, absl::string_view test_name, absl::string_view context, const T &lhs, const T &rhs, absl::string_view lhs_name, absl::string_view rhs_name)
template<class T , class Prof >
void ExpectEquality (ConformanceErrors *errors, absl::string_view test_name, absl::string_view context, const T &lhs, const T &rhs, absl::string_view lhs_name, absl::string_view rhs_name)
template<class T , class Prof >
void ExpectOrdered (ConformanceErrors *errors, absl::string_view context, const T &small, const T &big, absl::string_view small_name, absl::string_view big_name)
template<class T , class LogicalProf , class MinProf , class MaxProf , class... EqClasses>
ConformanceErrors ExpectRegularityImpl (OrderedEquivalenceClasses< EqClasses... > vals)
template<class T >
absl::string_view NameOfImpl ()
template<class T >
std::string NameOf ()
template<class Fun , class... Cases>
void ForEachParameter (const Fun &fun, const Cases &... cases)
template<class Fun , class Tup >
void ForEachTupleElement (const Fun &fun, const Tup &tup)
template<class Fun , class... T>
void ForEveryTwo (const Fun &fun, std::tuple< T... > args)
template<class Container >
void InsertEach (Container *cont)
template<class Container , class H , class... T>
void InsertEach (Container *cont, H &&head, T &&... tail)
Typedef Documentation
AlwaysFalse
template<class T > using absl::types_internal::AlwaysFalse = std::false_type
Definition at line 367 of file conformance_profile.h.
ArchetypeSpecialMembersBase
template<default_constructible DefaultConstructibleValue, move_constructible MoveConstructibleValue, copy_constructible CopyConstructibleValue, move_assignable MoveAssignableValue, copy_assignable CopyAssignableValue, destructible DestructibleValue> using absl::types_internal::ArchetypeSpecialMembersBase
Initial value:
 ArchetypeDestructor<
    DefaultConstructibleValue,
    MoveConstructibleValue != move_constructible::maybe
        ? MoveConstructibleValue
        : move_constructible::nothrow,
    CopyConstructibleValue,
    MoveAssignableValue != move_assignable::maybe ? MoveAssignableValue
                                                  : move_assignable::nothrow,
    CopyAssignableValue,
    DestructibleValue != destructible::maybe ? DestructibleValue
                                             : destructible::nothrow>
Definition at line 401 of file conformance_archetype.h.
ArchetypeState
using absl::types_internal::ArchetypeState = std::size_t
Definition at line 79 of file conformance_archetype.h.
ExpandBasicComparableProfiles
template<template< class... > class Receiver> using absl::types_internal::ExpandBasicComparableProfiles
Initial value:
    Receiver<ComparableNothrowMoveConstructibleProfile,
             ComparableCopyConstructibleProfile,
             ComparableNothrowMovableProfile, ComparableValueProfile>
Definition at line 402 of file conformance_aliases.h.
ExpandBasicDefaultConstructibleProfiles
template<template< class... > class Receiver> using absl::types_internal::ExpandBasicDefaultConstructibleProfiles
Initial value:
    Receiver<DefaultConstructibleNothrowMoveConstructibleProfile,
             DefaultConstructibleCopyConstructibleProfile,
             DefaultConstructibleNothrowMovableProfile,
             DefaultConstructibleValueProfile>
Definition at line 416 of file conformance_aliases.h.
ExpandBasicEquatableProfiles
template<template< class... > class Receiver> using absl::types_internal::ExpandBasicEquatableProfiles
Initial value:
    Receiver<EquatableNothrowMoveConstructibleProfile,
             EquatableCopyConstructibleProfile, EquatableNothrowMovableProfile,
             EquatableValueProfile>
Definition at line 395 of file conformance_aliases.h.
ExpandBasicHashableProfiles
template<template< class... > class Receiver> using absl::types_internal::ExpandBasicHashableProfiles
Initial value:
    Receiver<HashableNothrowMoveConstructibleProfile,
             HashableCopyConstructibleProfile, HashableNothrowMovableProfile,
             HashableValueProfile>
Definition at line 409 of file conformance_aliases.h.
ExpandBasicProfiles
template<template< class... > class Receiver> using absl::types_internal::ExpandBasicProfiles
Initial value:
    Receiver<NothrowMoveConstructibleProfile, CopyConstructibleProfile,
             NothrowMovableProfile, ValueProfile>
Definition at line 389 of file conformance_aliases.h.
ExpandSupportedProfiles
template<template< class... > class Receiver> using absl::types_internal::ExpandSupportedProfiles
Initial value:
 Receiver<
    NothrowMoveConstructibleProfile, CopyConstructibleProfile,
    NothrowMovableProfile, ValueProfile,
    EquatableNothrowMoveConstructibleProfile, EquatableCopyConstructibleProfile,
    EquatableNothrowMovableProfile, EquatableValueProfile,
    ComparableNothrowMoveConstructibleProfile,
    ComparableCopyConstructibleProfile, ComparableNothrowMovableProfile,
    ComparableValueProfile, DefaultConstructibleNothrowMoveConstructibleProfile,
    DefaultConstructibleCopyConstructibleProfile,
    DefaultConstructibleNothrowMovableProfile, DefaultConstructibleValueProfile,
    HashableNothrowMoveConstructibleProfile, HashableCopyConstructibleProfile,
    HashableNothrowMovableProfile, HashableValueProfile>
Definition at line 424 of file conformance_aliases.h.
ExpectConformanceOfType
template<class T > using absl::types_internal::ExpectConformanceOfType = ExpectConformanceOf<true, T>
Definition at line 1271 of file conformance_testing.h.
ExpectNonconformanceOfType
template<class T > using absl::types_internal::ExpectNonconformanceOfType
Initial value:
    ExpectConformanceOf<false, T>
Definition at line 1274 of file conformance_testing.h.
LogicalProfileOfT
template<class T > using absl::types_internal::LogicalProfileOfT = typename ProfileRangeOfT<T>::logical_profile
Definition at line 1123 of file conformance_testing.h.
LooseProfileRange
template<class LogicalProf , class MinProf = LogicalProf> using absl::types_internal::LooseProfileRange
Initial value:
 StrictProfileRange<RegularityDomain, LogicalProf,
                                             MinProf, MostStrictProfile>
Definition at line 1085 of file conformance_testing.h.
MakeLooseProfileRangeT
template<class Prof > using absl::types_internal::MakeLooseProfileRangeT = Prof
Definition at line 1089 of file conformance_testing.h.
MakeStrictProfileRangeT
template<class StrictnessDomain , class ProfOrRange > using absl::types_internal::MakeStrictProfileRangeT
Initial value:
    typename MakeStrictProfileRange<StrictnessDomain, ProfOrRange>::type
Definition at line 1073 of file conformance_testing.h.
MaxProfileOfT
template<class T > using absl::types_internal::MaxProfileOfT = typename ProfileRangeOfT<T>::max_profile
Definition at line 1131 of file conformance_testing.h.
MinProfileOfT
template<class T > using absl::types_internal::MinProfileOfT = typename ProfileRangeOfT<T>::min_profile
Definition at line 1127 of file conformance_testing.h.
MostStrictProfile
using absl::types_internal::MostStrictProfile
Initial value:
    CombineProfiles<TriviallyCompleteProfile, NothrowComparableProfile>
Definition at line 1079 of file conformance_testing.h.
ProfileRangeOfT
template<class T > using absl::types_internal::ProfileRangeOfT = typename ProfileRangeOf<T>::type
Definition at line 1117 of file conformance_testing.h.
PropertiesOfArchetypeT
template<class Archetype > using absl::types_internal::PropertiesOfArchetypeT = typename PropertiesOfArchetype<Archetype>::type
Definition at line 65 of file conformance_archetype.h.
PropertiesOfT
template<class T > using absl::types_internal::PropertiesOfT = typename PropertiesOf<T>::type
Definition at line 257 of file conformance_profile.h.
ResultOfGeneratorT
template<class Fun > using absl::types_internal::ResultOfGeneratorT = typename ResultOfGenerator<GeneratorType<Fun>>::type
Definition at line 178 of file conformance_testing_helpers.h.
Enumeration Type Documentation
CheckHashability
enum class absl::types_internal::CheckHashability strong
Enumerator
no
yes
Definition at line 661 of file conformance_profile.h.
{ no, yes };
function_support
enum class absl::types_internal::function_support strong
Enumerator
maybe
yes
nothrow
trivial
Definition at line 264 of file conformance_profile.h.
{ maybe, yes, nothrow, trivial };
hashable
enum class absl::types_internal::hashable strong
Enumerator
maybe
yes
Definition at line 360 of file conformance_profile.h.
{ maybe, yes };
Function Documentation
ABSL_INTERNAL_EXPECT_OP() [1/6]
absl::types_internal::ABSL_INTERNAL_EXPECT_OP (Eq)
ABSL_INTERNAL_EXPECT_OP() [2/6]
absl::types_internal::ABSL_INTERNAL_EXPECT_OP (Ge , >=)
ABSL_INTERNAL_EXPECT_OP() [3/6]
absl::types_internal::ABSL_INTERNAL_EXPECT_OP (Gt)
ABSL_INTERNAL_EXPECT_OP() [4/6]
absl::types_internal::ABSL_INTERNAL_EXPECT_OP (Le , <=)
ABSL_INTERNAL_EXPECT_OP() [5/6]
absl::types_internal::ABSL_INTERNAL_EXPECT_OP (Lt)
ABSL_INTERNAL_EXPECT_OP() [6/6]
absl::types_internal::ABSL_INTERNAL_EXPECT_OP (Ne , !)
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM() [1/5]
absl::types_internal::ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ("support for <=" , less_equal_comparable)
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM() [2/5]
absl::types_internal::ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ()
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM() [3/5]
absl::types_internal::ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ("support for, " , greater_than_comparable)
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM() [4/5]
absl::types_internal::ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ("support for >=" , greater_equal_comparable)
ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM() [5/5]
absl::types_internal::ABSL_INTERNAL_INTRINSIC_FUNCTION_ENUM ("support for swap" , swappable)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON() [1/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (EqualityComparable , equality_comparable)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON() [2/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (GreaterEqualComparable , greater_equal_comparable , >=)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON() [3/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (GreaterThanComparable , greater_than_comparable)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON() [4/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (InequalityComparable , inequality_comparable , !)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON() [5/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (LessEqualComparable , less_equal_comparable , <=)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON() [6/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_COMPARISON (LessThanComparable , less_than_comparable)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER() [1/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (CopyAssignable , copy_assignable)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER() [2/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (CopyConstructible , copy_constructible)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER() [3/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (DefaultConstructible , default_constructible)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER() [4/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (Destructible , destructible)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER() [5/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (MoveAssignable , move_assignable)
ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER() [6/6]
absl::types_internal::ABSL_INTERNAL_PESSIMISTIC_MODEL_OF_SPECIAL_MEMBER (MoveConstructible , move_constructible)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [1/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (Comparable , CombineProfiles< EquatableProfile, HasLessThanProfile, HasLessEqualProfile, HasGreaterEqualProfile, HasGreaterThanProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [2/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableCopyConstructible , CombineProfiles< ComparableProfile, CopyConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [3/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableHashableValue , CombineProfiles< HashableValueProfile, ComparableProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [4/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableNothrowMovable , CombineProfiles< ComparableProfile, NothrowMovableProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [5/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableNothrowMoveConstructible , CombineProfiles< ComparableProfile, NothrowMoveConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [6/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (ComparableValue , CombineProfiles< ComparableProfile, ValueProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [7/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (CopyConstructible , CombineProfiles< HasNothrowMoveConstructorProfile, HasCopyConstructorProfile, HasNothrowDestructorProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [8/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (DefaultConstructibleCopyConstructible , CombineProfiles< HasDefaultConstructorProfile, CopyConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [9/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (DefaultConstructibleNothrowMovable , CombineProfiles< HasDefaultConstructorProfile, NothrowMovableProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [10/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (DefaultConstructibleNothrowMoveConstructible , CombineProfiles< HasDefaultConstructorProfile, NothrowMoveConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [11/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (DefaultConstructibleValue , CombineProfiles< HasDefaultConstructorProfile, ValueProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [12/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (Equatable , CombineProfiles< HasEqualityProfile, HasInequalityProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [13/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (EquatableCopyConstructible , CombineProfiles< EquatableProfile, CopyConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [14/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (EquatableNothrowMovable , CombineProfiles< EquatableProfile, NothrowMovableProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [15/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (EquatableNothrowMoveConstructible , CombineProfiles< EquatableProfile, NothrowMoveConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [16/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (EquatableValue , CombineProfiles< EquatableProfile, ValueProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [17/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasCopyAssign , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [18/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasCopyConstructor , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [19/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasDefaultConstructor , ConformanceProfile< default_constructible::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [20/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasDestructor , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [21/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasEquality , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [22/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasGreaterEqual , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [23/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasGreaterThan , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [24/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HashableCopyConstructible , CombineProfiles< HasStdHashSpecializationProfile, CopyConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [25/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HashableNothrowMovable , CombineProfiles< HasStdHashSpecializationProfile, NothrowMovableProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [26/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HashableNothrowMoveConstructible , CombineProfiles< HasStdHashSpecializationProfile, NothrowMoveConstructibleProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [27/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HashableValue , CombineProfiles< HasStdHashSpecializationProfile, ValueProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [28/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasInequality , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [29/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasLessEqual , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [30/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasLessThan , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [31/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasMoveAssign , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [32/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasMoveConstructor , ConformanceProfile< default_constructible::maybe, move_constructible::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [33/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowCopyAssign , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [34/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowCopyConstructor , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [35/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowDefaultConstructor , ConformanceProfile< default_constructible::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [36/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowDestructor , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [37/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowEquality , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [38/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowGreaterEqual , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [39/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowGreaterThan , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [40/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowInequality , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [41/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowLessEqual , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [42/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowLessThan , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [43/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowMoveAssign , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [44/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowMoveConstructor , ConformanceProfile< default_constructible::maybe, move_constructible::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [45/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasNothrowSwap , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::maybe, swappable::nothrow >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [46/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasStdHashSpecialization , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::maybe, swappable::maybe, hashable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [47/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasSwap , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::maybe, equality_comparable::maybe, inequality_comparable::maybe, less_than_comparable::maybe, less_equal_comparable::maybe, greater_equal_comparable::maybe, greater_than_comparable::maybe, swappable::yes >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [48/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialCopyAssign , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [49/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialCopyConstructor , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [50/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialDefaultConstructor , ConformanceProfile< default_constructible::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [51/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialDestructor , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::maybe, copy_assignable::maybe, destructible::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [52/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialMoveAssign , ConformanceProfile< default_constructible::maybe, move_constructible::maybe, copy_constructible::maybe, move_assignable::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [53/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (HasTrivialMoveConstructor , ConformanceProfile< default_constructible::maybe, move_constructible::trivial >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [54/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (NothrowComparable , CombineProfiles< NothrowEquatableProfile, HasNothrowLessThanProfile, HasNothrowLessEqualProfile, HasNothrowGreaterEqualProfile, HasNothrowGreaterThanProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [55/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (NothrowEquatable , CombineProfiles< HasNothrowEqualityProfile, HasNothrowInequalityProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [56/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (NothrowMovable , CombineProfiles< HasNothrowMoveConstructorProfile, HasNothrowMoveAssignProfile, HasNothrowDestructorProfile, HasNothrowSwapProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [57/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (NothrowMoveConstructible , CombineProfiles< HasNothrowMoveConstructorProfile, HasNothrowDestructorProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [58/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (TriviallyComplete , CombineProfiles< TrivialSpecialMemberFunctionsProfile, ComparableProfile, HasStdHashSpecializationProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [59/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (TrivialSpecialMemberFunctions , CombineProfiles< HasTrivialDefaultConstructorProfile, HasTrivialMoveConstructorProfile, HasTrivialCopyConstructorProfile, HasTrivialMoveAssignProfile, HasTrivialCopyAssignProfile, HasTrivialDestructorProfile, HasNothrowSwapProfile >)
ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS() [60/60]
absl::types_internal::ABSL_INTERNAL_PROFILE_AND_ARCHETYPE_ALIAS (Value , CombineProfiles< HasNothrowMoveConstructorProfile, HasCopyConstructorProfile, HasNothrowMoveAssignProfile, HasCopyAssignProfile, HasNothrowDestructorProfile, HasNothrowSwapProfile >)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM() [1/6]
absl::types_internal::ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for copy assignment" , copy_assignable)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM() [2/6]
absl::types_internal::ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for copy construction" , copy_constructible)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM() [3/6]
absl::types_internal::ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for default construction" , default_constructible)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM() [4/6]
absl::types_internal::ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for destruction" , destructible)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM() [5/6]
absl::types_internal::ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for move assignment" , move_assignable)
ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM() [6/6]
absl::types_internal::ABSL_INTERNAL_SPECIAL_MEMBER_FUNCTION_ENUM ("support for move construction" , move_constructible)
ABSL_TYPES_INTERNAL_OP() [1/6]
absl::types_internal::ABSL_TYPES_INTERNAL_OP (equality_comparable)
ABSL_TYPES_INTERNAL_OP() [2/6]
absl::types_internal::ABSL_TYPES_INTERNAL_OP (greater_equal_comparable , >=)
ABSL_TYPES_INTERNAL_OP() [3/6]
absl::types_internal::ABSL_TYPES_INTERNAL_OP (greater_than_comparable)
ABSL_TYPES_INTERNAL_OP() [4/6]
absl::types_internal::ABSL_TYPES_INTERNAL_OP (inequality_comparable , !)
ABSL_TYPES_INTERNAL_OP() [5/6]
absl::types_internal::ABSL_TYPES_INTERNAL_OP (less_equal_comparable , <=)
ABSL_TYPES_INTERNAL_OP() [6/6]
absl::types_internal::ABSL_TYPES_INTERNAL_OP (less_than_comparable)
BoolFunction()
void absl::types_internal::BoolFunction (bool) noexcept
constexpr_instantiation_when_unevaluated()
bool absl::types_internal::constexpr_instantiation_when_unevaluated () constexpr
Definition at line 58 of file conformance_testing.h.
{
#if defined(__apple_build_version__)  // TODO(calabrese) Make more specific
  return true;
#elif defined(__clang__)
  return __clang_major__ < 4;
#elif defined(__GNUC__)
  // TODO(calabrese) Figure out why gcc 7 fails (seems like a different bug)
  return __GNUC__ < 5 || (__GNUC__ == 5 && __GNUC_MINOR__ < 2) || __GNUC__ >= 7;
#else
  return false;
#endif
}
Referenced by ExpectRegularityImpl().
EquivalenceClass()
template<class... Funs, absl::enable_if_t< AreGeneratorsWithTheSameReturnType< Funs... >::value > ** = nullptr> EquivalenceClassType< Funs... > absl::types_internal::EquivalenceClass (GeneratorType< Funs >... funs)
Definition at line 114 of file conformance_testing.h.
{
  return {std::make_tuple(absl::move(funs)...)};
}
References absl::move().
Referenced by absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::dont_class_directly_stateful_initializer(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::equivalence_class(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::initializer().
ExpectedFunctionKindList()
std::string absl::types_internal::ExpectedFunctionKindList (function_support min, function_support max) inline
Definition at line 277 of file conformance_profile.h.
{
  if (min == max) {
    std::string result =
        absl::StrCat("Expected:\n  ",
                     PessimisticPropertyDescription(
                         static_cast<function_support>(UnderlyingValue(min))),
                     "\n");
    return result;
  }
  std::string result = "Expected one of:\n";
  for (auto curr_support = UnderlyingValue(min);
       curr_support <= UnderlyingValue(max); ++curr_support) {
    absl::StrAppend(&result, "  ",
                    PessimisticPropertyDescription(
                        static_cast<function_support>(curr_support)),
                    "\n");
  }
  return result;
}
References PessimisticPropertyDescription(), absl::StrAppend(), absl::StrCat(), and UnderlyingValue().
Referenced by ExpectModelOfImpl().
ExpectEquality()
template<class T , class Prof > void absl::types_internal::ExpectEquality (ConformanceErrors * errors, absl::string_view test_name, absl::string_view context, const T & lhs, const T & rhs, absl::string_view lhs_name, absl::string_view rhs_name)
Definition at line 285 of file conformance_testing.h.
{
  (ExpectOneWayEquality<T, Prof>)(errors, test_name, context, lhs, rhs,
                                  lhs_name, rhs_name);
  (ExpectOneWayEquality<T, Prof>)(errors, test_name, context, rhs, lhs,
                                  rhs_name, lhs_name);
}
References ExpectOneWayEquality().
Referenced by absl::types_internal::ExpectCopyAssign< T, Prof >::operator()(), absl::types_internal::ExpectCopyConstructOneGenerator< T, Prof >::operator()(), absl::types_internal::ExpectDefaultConstructWithCopyAssign< T, Prof >::operator()(), absl::types_internal::ExpectDefaultConstructWithMoveAssign< T, Prof >::operator()(), absl::types_internal::ExpectEquivalenceClassComparison< T, Prof >::operator()(), absl::types_internal::ExpectMoveAssign< T, Prof >::operator()(), absl::types_internal::ExpectMoveConstructOneGenerator< T, Prof >::operator()(), absl::types_internal::ExpectSelfCopyAssign< T, Prof >::operator()(), absl::types_internal::ExpectSelfMoveAssign< T, Prof >::operator()(), absl::types_internal::ExpectSelfSwap< T, Prof >::operator()(), and absl::types_internal::ExpectSwap< T, Prof >::operator()().
ExpectModelOfHashable()
template<class T , class MinProf , class MaxProf > void absl::types_internal::ExpectModelOfHashable (ConformanceErrors * errors)
Definition at line 536 of file conformance_profile.h.
{
  (ExpectModelOfImpl)(errors, PropertiesOfT<MinProf>::hashable_support,
                      PropertiesOfT<MaxProf>::hashable_support,
                      hashable_support_of<T>());
}
References ExpectModelOfImpl(), and hashable_support_of().
Referenced by absl::types_internal::ExpectHashable< T, MinProf, MaxProf >::operator()().
ExpectModelOfImpl()
template<class Enum > void absl::types_internal::ExpectModelOfImpl (ConformanceErrors * errors, Enum min_support, Enum max_support, Enum kind)
Definition at line 301 of file conformance_profile.h.
{
  const auto kind_value = UnderlyingValue(kind);
  const auto min_support_value = UnderlyingValue(min_support);
  const auto max_support_value = UnderlyingValue(max_support);
  if (!(kind_value >= min_support_value && kind_value <= max_support_value)) {
    errors->addTestFailure(
        PropertyName(kind), "**Failed property expectation**\n\n",
        ExpectedFunctionKindList(
            static_cast<function_support>(min_support_value),
            static_cast<function_support>(max_support_value)),
        '\n', "Actual:\n  ",
        PessimisticPropertyDescription(
            static_cast<function_support>(kind_value)));
  } else {
    errors->addTestSuccess(PropertyName(kind));
  }
}
References absl::types_internal::ConformanceErrors::addTestFailure(), absl::types_internal::ConformanceErrors::addTestSuccess(), ExpectedFunctionKindList(), PessimisticPropertyDescription(), PropertyName(), and UnderlyingValue().
Referenced by ExpectModelOfHashable(), and ExpectModelOfSwappable().
ExpectModelOfSwappable()
template<class T , class MinProf , class MaxProf > void absl::types_internal::ExpectModelOfSwappable (ConformanceErrors * errors)
Definition at line 518 of file conformance_profile.h.
{
  (ExpectModelOfImpl)(errors, PropertiesOfT<MinProf>::swappable_support,
                      PropertiesOfT<MaxProf>::swappable_support,
                      swappable_support_of<T>());
}
References ExpectModelOfImpl(), and swappable_support_of().
Referenced by absl::types_internal::ExpectModels< T, MinProf, MaxProf >::operator()().
ExpectOneWayEquality()
template<class T , class Prof > void absl::types_internal::ExpectOneWayEquality (ConformanceErrors * errors, absl::string_view test_name, absl::string_view context, const T & lhs, const T & rhs, absl::string_view lhs_name, absl::string_view rhs_name)
Definition at line 253 of file conformance_testing.h.
{
  If<PropertiesOfT<Prof>::is_equality_comparable>::Invoke(
      ExpectEq{errors}, test_name, context, lhs, rhs, lhs_name, rhs_name);
  If<PropertiesOfT<Prof>::is_inequality_comparable>::Invoke(
      ExpectNotNe{errors}, test_name, context, lhs, rhs, lhs_name, rhs_name);
  If<PropertiesOfT<Prof>::is_less_than_comparable>::Invoke(
      ExpectNotLt{errors}, test_name, context, lhs, rhs, lhs_name, rhs_name);
  If<PropertiesOfT<Prof>::is_less_equal_comparable>::Invoke(
      ExpectLe{errors}, test_name, context, lhs, rhs, lhs_name, rhs_name);
  If<PropertiesOfT<Prof>::is_greater_equal_comparable>::Invoke(
      ExpectGe{errors}, test_name, context, lhs, rhs, lhs_name, rhs_name);
  If<PropertiesOfT<Prof>::is_greater_than_comparable>::Invoke(
      ExpectNotGt{errors}, test_name, context, lhs, rhs, lhs_name, rhs_name);
  If<PropertiesOfT<Prof>::is_hashable>::Invoke(
      ExpectSameHash{errors}, test_name, context, lhs, rhs, lhs_name, rhs_name);
}
Referenced by ExpectEquality(), and absl::types_internal::ExpectSelfComparison< T, Prof >::operator()().
ExpectOrdered()
template<class T , class Prof > void absl::types_internal::ExpectOrdered (ConformanceErrors * errors, absl::string_view context, const T & small, const T & big, absl::string_view small_name, absl::string_view big_name)
Definition at line 663 of file conformance_testing.h.
{
  const absl::string_view test_name = "Comparison";
  If<PropertiesOfT<Prof>::is_equality_comparable>::Invoke(
      ExpectNotEq{errors}, test_name, context, small, big, small_name,
      big_name);
  If<PropertiesOfT<Prof>::is_equality_comparable>::Invoke(
      ExpectNotEq{errors}, test_name, context, big, small, big_name,
      small_name);
  If<PropertiesOfT<Prof>::is_inequality_comparable>::Invoke(
      ExpectNe{errors}, test_name, context, small, big, small_name, big_name);
  If<PropertiesOfT<Prof>::is_inequality_comparable>::Invoke(
      ExpectNe{errors}, test_name, context, big, small, big_name, small_name);
  If<PropertiesOfT<Prof>::is_less_than_comparable>::Invoke(
      ExpectLt{errors}, test_name, context, small, big, small_name, big_name);
  If<PropertiesOfT<Prof>::is_less_than_comparable>::Invoke(
      ExpectNotLt{errors}, test_name, context, big, small, big_name,
      small_name);
  If<PropertiesOfT<Prof>::is_less_equal_comparable>::Invoke(
      ExpectLe{errors}, test_name, context, small, big, small_name, big_name);
  If<PropertiesOfT<Prof>::is_less_equal_comparable>::Invoke(
      ExpectNotLe{errors}, test_name, context, big, small, big_name,
      small_name);
  If<PropertiesOfT<Prof>::is_greater_equal_comparable>::Invoke(
      ExpectNotGe{errors}, test_name, context, small, big, small_name,
      big_name);
  If<PropertiesOfT<Prof>::is_greater_equal_comparable>::Invoke(
      ExpectGe{errors}, test_name, context, big, small, big_name, small_name);
  If<PropertiesOfT<Prof>::is_greater_than_comparable>::Invoke(
      ExpectNotGt{errors}, test_name, context, small, big, small_name,
      big_name);
  If<PropertiesOfT<Prof>::is_greater_than_comparable>::Invoke(
      ExpectGt{errors}, test_name, context, big, small, big_name, small_name);
}
Referenced by absl::types_internal::ExpectBiggerGeneratorThanComparisons< T, Prof, SmallGenerator >::operator()().
ExpectRegularityImpl()
template<class T , class LogicalProf , class MinProf , class MaxProf , class... EqClasses> ConformanceErrors absl::types_internal::ExpectRegularityImpl (OrderedEquivalenceClasses< EqClasses... > vals)
Definition at line 957 of file conformance_testing.h.
{
  ConformanceErrors errors((NameOf<T>()));
  If<!constexpr_instantiation_when_unevaluated()>::Invoke(
      ExpectModels<T, MinProf, MaxProf>(), &errors);
  using minimal_profile = typename absl::conditional_t<
      constexpr_instantiation_when_unevaluated(), Always<LogicalProf>,
      MinimalCheckableProfile<LogicalProf, T>>::type;
  If<PropertiesOfT<minimal_profile>::is_default_constructible>::Invoke(
      ExpectDefaultConstructWithDestruct<T>{&errors});
  // Perform all comparison checks first, since later checks depend on their
  // correctness.
  //
  // Check all of the comparisons for all values in the same equivalence
  // class (equal with respect to comparison operators and hash the same).
  (ForEachTupleElement)(
      ExpectEquivalenceClassComparisons<T, minimal_profile>{&errors},
      vals.eq_classes);
  // Check all of the comparisons for each combination of values that are in
  // different equivalence classes (not equal with respect to comparison
  // operators).
  absl::apply(
      ExpectOrderedEquivalenceClassesComparisons<T, minimal_profile>{&errors},
      vals.eq_classes);
  //
  // Perform remaining checks, relying on comparisons.
  // TODO(calabrese) short circuit if any comparisons above failed.
  (ForEachTupleElement)(ExpectEquivalenceClass<T, minimal_profile>{&errors},
                        vals.eq_classes);
  absl::apply(ExpectOrderedEquivalenceClasses<T, minimal_profile>{&errors},
              vals.eq_classes);
  return errors;
}
References absl::apply(), constexpr_instantiation_when_unevaluated(), ForEachTupleElement(), and NameOf().
Referenced by absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_loose_profile(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_strict_profile().
ForEachParameter()
template<class Fun , class... Cases> void absl::types_internal::ForEachParameter (const Fun & fun, const Cases &... cases)
Definition at line 276 of file conformance_testing_helpers.h.
{
  const std::initializer_list<bool> results = {
      (static_cast<void>(fun(cases)), true)...};
  (void)results;
}
Referenced by absl::types_internal::ForEachParameterFun< Fun >::operator()().
ForEachTupleElement()
template<class Fun , class Tup > void absl::types_internal::ForEachTupleElement (const Fun & fun, const Tup & tup)
Definition at line 296 of file conformance_testing_helpers.h.
{
  absl::apply(ForEachParameterFun<Fun>{fun}, tup);
}
References absl::apply().
Referenced by ExpectRegularityImpl(), ForEveryTwo(), absl::types_internal::ExpectBiggerGeneratorThanEqClasses< T, Prof, SmallGenerator >::operator()(), absl::types_internal::ExpectBiggerGeneratorThanEqClassesComparisons< T, Prof, SmallGenerator >::operator()(), absl::types_internal::ExpectEquivalenceClass< T, Prof >::operator()(), absl::types_internal::ExpectEquivalenceClassComparisons< T, Prof >::operator()(), absl::types_internal::ExpectOrderedEquivalenceClasses< T, Prof >::Impl< BigEqClasses >::operator()(), absl::types_internal::ExpectOrderedEquivalenceClasses< T, Prof >::operator()(), absl::types_internal::ExpectOrderedEquivalenceClassesComparisons< T, Prof >::Impl< BigEqClasses >::operator()(), absl::types_internal::ExpectOrderedEquivalenceClassesComparisons< T, Prof >::operator()(), and absl::types_internal::ForEveryTwoImpl< Fun, T >::operator()().
ForEveryTwo()
template<class Fun , class... T> void absl::types_internal::ForEveryTwo (const Fun & fun, std::tuple< T... > args)
Definition at line 327 of file conformance_testing_helpers.h.
{
  (ForEachTupleElement)(ForEveryTwoImpl<Fun, T...>{fun, args}, args);
}
References ForEachTupleElement().
Referenced by absl::types_internal::ExpectEquivalenceClass< T, Prof >::operator()(), and absl::types_internal::ExpectEquivalenceClassComparisons< T, Prof >::operator()().
Generator()
template<class Fun , absl::enable_if_t< IsNullaryCallable< Fun >::value > ** = nullptr> GeneratorType< Fun > absl::types_internal::Generator (Fun fun, const char * description)
Definition at line 96 of file conformance_testing.h.
{
  return GeneratorType<Fun>{absl::move(fun), description};
}
References absl::move().
hashable_support_of()
template<class T > hashable absl::types_internal::hashable_support_of () constexpr
Definition at line 530 of file conformance_profile.h.
{
  return type_traits_internal::IsHashable<T>::value ? hashable::yes
                                                    : hashable::maybe;
}
References maybe, and yes.
Referenced by ExpectModelOfHashable(), and absl::types_internal::conservative_hashable_support_of< T, CheckHashability::yes >::Invoke().
InsertEach() [1/2]
template<class Container > void absl::types_internal::InsertEach (Container * cont)
Definition at line 337 of file conformance_testing_helpers.h.
{
}
Referenced by absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::due_to(), and InsertEach().
InsertEach() [2/2]
template<class Container , class H , class... T> void absl::types_internal::InsertEach (Container * cont, H && head, T &&... tail)
Definition at line 341 of file conformance_testing_helpers.h.
{
  cont->insert(head);
  (InsertEach)(cont, tail...);
}
References InsertEach().
MakeArchetype()
template<class Arch > Arch absl::types_internal::MakeArchetype (ArchetypeState state) noexcept
Definition at line 415 of file conformance_archetype.h.
{
  static_assert(IsArchetype<Arch>::value,
                "The explicit template argument to MakeArchetype is required "
                "to be an Archetype.");
  return Arch(MakeArchetypeState(), state);
}
MaxEnum() [1/2]
template<class H > H absl::types_internal::MaxEnum (H head) constexpr
Definition at line 819 of file conformance_profile.h.
{
  return head;
}
Referenced by MaxEnum().
MaxEnum() [2/2]
template<class H , class N , class... T> H absl::types_internal::MaxEnum (H head, N next, T... tail) constexpr
Definition at line 824 of file conformance_profile.h.
{
  return (UnderlyingValue)(next) < (UnderlyingValue)(head)
             ? (MaxEnum)(head, tail...)
             : (MaxEnum)(next, tail...);
}
References MaxEnum(), next, and UnderlyingValue().
MinEnum() [1/2]
template<class H > H absl::types_internal::MinEnum (H head) constexpr
Definition at line 745 of file conformance_profile.h.
{
  return head;
}
Referenced by MinEnum().
MinEnum() [2/2]
template<class H , class N , class... T> H absl::types_internal::MinEnum (H head, N next, T... tail) constexpr
Definition at line 750 of file conformance_profile.h.
{
  return (UnderlyingValue)(head) < (UnderlyingValue)(next)
             ? (MinEnum)(head, tail...)
             : (MinEnum)(next, tail...);
}
References MinEnum(), next, and UnderlyingValue().
NameOf()
template<class T > std::string absl::types_internal::NameOf ()
Definition at line 81 of file conformance_testing_helpers.h.
                   {
  static const absl::string_view result = NameOfImpl<T>();
  return std::string(result);
}
References NameOfImpl().
Referenced by ExpectRegularityImpl().
NameOfImpl()
template<class T > absl::string_view absl::types_internal::NameOfImpl ()
Definition at line 55 of file conformance_testing_helpers.h.
{
// TODO(calabrese) Investigate using debugging:internal_demangle as a fallback.
#if ABSL_TYPES_INTERNAL_HAS_CXA_DEMANGLE
  int status = 0;
  char* demangled_name = nullptr;
  demangled_name =
      abi::__cxa_demangle(typeid(T).name(), nullptr, nullptr, &status);
  if (status == 0 && demangled_name != nullptr) {
    return demangled_name;
  } else {
    return typeid(T).name();
  }
#else
  return typeid(T).name();
#endif
  // NOTE: We intentionally leak demangled_name so that it remains valid
  // throughout the remainder of the program.
}
References name.
Referenced by NameOf().
PessimisticPropertyDescription()
const char * absl::types_internal::PessimisticPropertyDescription (function_support v) constexpr
Definition at line 266 of file conformance_profile.h.
{
  return v == function_support::maybe
             ? "no"
             : v == function_support::yes
                   ? "yes, potentially throwing"
                   : v == function_support::nothrow ? "yes, nothrow"
                                                    : "yes, trivial";
}
References maybe, nothrow, absl::v, and yes.
Referenced by ExpectedFunctionKindList(), and ExpectModelOfImpl().
poisoned_hash_fails_instantiation()
bool absl::types_internal::poisoned_hash_fails_instantiation () constexpr
Definition at line 73 of file conformance_testing.h.
{
#if defined(_MSC_VER) && !defined(_LIBCPP_VERSION)
  return _MSC_VER < 1914;
#else
  return false;
#endif
}
Referenced by absl::types_internal::ExpectModels< T, MinProf, MaxProf >::operator()().
PrepareGivenContext()
template<class... Decls> std::string absl::types_internal::PrepareGivenContext (const Decls &... decls)
Definition at line 149 of file conformance_testing.h.
{
  const std::size_t width = (std::max)({decls.name.size()...});
  return absl::StrCat("Given:\n", decls.outputDeclaration(width)..., "\n");
}
References absl::StrCat().
Referenced by absl::types_internal::ExpectBiggerGeneratorThanComparisons< T, Prof, SmallGenerator >::operator()(), absl::types_internal::ExpectCopyAssign< T, Prof >::operator()(), absl::types_internal::ExpectCopyConstructOneGenerator< T, Prof >::operator()(), absl::types_internal::ExpectDefaultConstructWithCopyAssign< T, Prof >::operator()(), absl::types_internal::ExpectDefaultConstructWithMoveAssign< T, Prof >::operator()(), absl::types_internal::ExpectEquivalenceClassComparison< T, Prof >::operator()(), absl::types_internal::ExpectMoveAssign< T, Prof >::operator()(), absl::types_internal::ExpectMoveConstructOneGenerator< T, Prof >::operator()(), absl::types_internal::ExpectSelfComparison< T, Prof >::operator()(), absl::types_internal::ExpectSelfCopyAssign< T, Prof >::operator()(), absl::types_internal::ExpectSelfMoveAssign< T, Prof >::operator()(), absl::types_internal::ExpectSelfSwap< T, Prof >::operator()(), and absl::types_internal::ExpectSwap< T, Prof >::operator()().
PropertyName()
const char * absl::types_internal::PropertyName (hashable v) constexpr
Definition at line 362 of file conformance_profile.h.
{
  return "support for std::hash";
}
Referenced by ExpectModelOfImpl().
ShouldDeleteAssign()
template<class Prof , class T > bool absl::types_internal::ShouldDeleteAssign () constexpr
Definition at line 443 of file conformance_archetype.h.
{
  return !(
      (PropertiesOfT<Prof>::move_assignable_support != move_assignable::maybe &&
       std::is_same<T, Archetype<Prof>>::value) ||
      (PropertiesOfT<Prof>::copy_assignable_support != copy_assignable::maybe &&
       (std::is_same<T, const Archetype<Prof>&>::value ||
        std::is_same<T, Archetype<Prof>&>::value ||
        std::is_same<T, const Archetype<Prof>>::value)));
}
References value.
ShouldDeleteConstructor()
template<class Prof , class T > bool absl::types_internal::ShouldDeleteConstructor () constexpr
Definition at line 427 of file conformance_archetype.h.
{
  return !((PropertiesOfT<Prof>::move_constructible_support !=
                move_constructible::maybe &&
            std::is_same<T, Archetype<Prof>>::value) ||
           (PropertiesOfT<Prof>::copy_constructible_support !=
                copy_constructible::maybe &&
            (std::is_same<T, const Archetype<Prof>&>::value ||
             std::is_same<T, Archetype<Prof>&>::value ||
             std::is_same<T, const Archetype<Prof>>::value)));
}
References value.
swap()
template<class Prof , absl::enable_if_t<!PropertiesOfT< Prof >::is_swappable, int > = 0> void absl::types_internal::swap (Archetype< Prof > & lhs, Archetype< Prof > & rhs) delete noexcept
Definition at line 857 of file conformance_archetype.h.
{
  std::swap(lhs.archetype_state, rhs.archetype_state);
}
swappable_support_of()
template<class T > swappable absl::types_internal::swappable_support_of () constexpr
Definition at line 509 of file conformance_profile.h.
{
  return type_traits_internal::IsSwappable<T>::value
             ? type_traits_internal::IsNothrowSwappable<T>::value
                   ? swappable::nothrow
                   : swappable::yes
             : swappable::maybe;
}
Referenced by ExpectModelOfSwappable().
UnderlyingValue()
template<typename Enum > absl::underlying_type_t< Enum > absl::types_internal::UnderlyingValue (Enum value) constexpr
Definition at line 61 of file conformance_profile.h.
{
  return static_cast<absl::underlying_type_t<Enum>>(value);
}
References value.
Referenced by ExpectedFunctionKindList(), ExpectModelOfImpl(), MaxEnum(), and MinEnum().