open spiel: open_spiel::algorithms Namespace Reference
open_spiel::algorithms Namespace Reference
Namespaces
namespace blotto_fp
namespace internal
namespace ortools
namespace torch_az
namespace torch_dqn
Classes
class AFCCEGame
class AFCCEState
class AFCCETabularPolicy
class AFCEGame
class AFCEState
class AFCETabularPolicy
struct BatchedTrajectory
class CCEGame
class CCEState
class CCETabularPolicy
class CEGame
class CEState
class CETabularPolicy
class CFRAveragePolicy
class CFRBRSolver
class CFRCurrentPolicy
struct CFRInfoStateValues
class CFRPlusSolver
class CFRSolver
class CFRSolverBase
struct ChildInfo
class CorrDevBuilder
struct CorrDistConfig
struct CorrDistInfo
class DecisionId
class DecisionVector
class DeterministicTabularPolicy
class EFCCEGame
class EFCCEState
class EFCCETabularPolicy
class EFCEGame
class EFCEState
class EFCETabularPolicy
class Evaluator
class ExplorativeSamplingPolicy
class ExternalSamplingMCCFRSolver
class FSICFRGraph
struct FSICFRNode
class FSICFRSolver
class HistoryNode
class HistoryTree
class InfostateNode
class InfostateTree
class ISMCTSBot
struct ISMCTSNode
class LeafId
class LeafVector
struct LegalsWithIndex
class MCTSBot
class MDP
class MDPNode
struct NormalFormJointPolicyWithProb
struct OnlineStats
class OOSAlgorithm
class OutcomeSamplingMCCFRSolver
struct PartiallyDeserializedCFRSolver
struct PlayerNodeOutcome
class RandomRolloutEvaluator
class Range
class RangeIterator
struct SearchNode
class SequenceId
class TabularBestResponse
class TabularBestResponseMDP
struct TabularBestResponseMDPInfo
class TabularQLearningSolver
class TabularSarsaSolver
struct TakeAction
class TargetedPolicy
class TrajectoryRecorder
class TreeplexVector
class VecWithUniquePtrsIterator
Typedefs
using CFRInfoStateValuesTable
using CorrelationDevice = std::vector<std::pair<double, TabularPolicy>>
using NormalFormCorrelationDevice = std::vector<NormalFormJointPolicyWithProb>
using SfStrategy = TreeplexVector<double>
using ISMCTSStateKey = std::pair<Player, std::string>
using InfostateResampler
using ProbDistribution = std::vector<double>
using OOSInfoStateValuesTable = CFRInfoStateValuesTable
Enumerations
enum class AverageType { kSimple , kFull }
enum InfostateNodeType { kDecisionInfostateNode , kObservationInfostateNode , kTerminalInfostateNode }
enum class ISMCTSFinalPolicyType { kNormalizedVisitCount , kMaxVisitCount , kMaxValue }
enum class ChildSelectionPolicy { UCT , PUCT }
enum Targeting { kDoNotUseTargeting , kInfoStateTargeting , kPublicStateTargeting }
Functions
CFRInfoStateValues DeserializeCFRInfoStateValues (absl::string_view serialized)
void SerializeCFRInfoStateValuesTable (const CFRInfoStateValuesTable &info_states, std::string *result, int double_precision, std::string delimiter)
void DeserializeCFRInfoStateValuesTable (absl::string_view serialized, CFRInfoStateValuesTable *result, std::string delimiter)
std::unique_ptr< CFRSolver > DeserializeCFRSolver (const std::string &serialized, std::string delimiter)
std::unique_ptr< CFRPlusSolver > DeserializeCFRPlusSolver (const std::string &serialized, std::string delimiter)
PartiallyDeserializedCFRSolver PartiallyDeserializeCFRSolver (const std::string &serialized)
std::unique_ptr< CFRBRSolver > DeserializeCFRBRSolver (const std::string &serialized, std::string delimiter)
CorrelationDevice SampledDeterminizeCorrDev (const CorrelationDevice &corr_dev, int num_samples_per_policy)
CorrelationDevice DeterminizeCorrDev (const CorrelationDevice &corr_dev)
CorrelationDevice UniformCorrelationDevice (std::vector< TabularPolicy > &policies)
std::string ToString (const CorrelationDevice &corr_dev)
std::vector< double > ExpectedValues (const Game &game, const CorrelationDevice &mu)
std::vector< double > ExpectedValues (const Game &game, const NormalFormCorrelationDevice &mu)
double EFCEDist (const Game &game, CorrDistConfig config, const CorrelationDevice &mu)
double EFCCEDist (const Game &game, CorrDistConfig config, const CorrelationDevice &mu)
double AFCEDist (const Game &game, CorrDistConfig config, const CorrelationDevice &mu)
double AFCCEDist (const Game &game, CorrDistConfig config, const CorrelationDevice &mu)
double CEDist (const Game &game, const NormalFormCorrelationDevice &mu)
double CCEDist (const Game &game, const NormalFormCorrelationDevice &mu)
CorrDistInfo CCEDist (const Game &game, const CorrelationDevice &mu, int player, const float prob_cut_threshold, const float action_value_tolerance)
CorrDistInfo CCEDist (const Game &game, const CorrelationDevice &mu, const float prob_cut_threshold, const float action_value_tolerance)
CorrDistInfo CEDist (const Game &game, const CorrelationDevice &mu, const float action_value_tolerance)
int64_t NumDeterministicPolicies (const Game &game, Player player)
std::vector< double > ExpectedReturns (const State &state, const std::vector< const Policy * > &policies, int depth_limit, bool use_infostate_get_policy, float prob_cut_threshold)
std::vector< double > ExpectedReturns (const State &state, const Policy &joint_policy, int depth_limit, bool use_infostate_get_policy, float prob_cut_threshold)
std::vector< double > ExpectedReturnsOfDeterministicPoliciesFromSeeds (const State &state, const std::vector< int > &policy_seeds)
std::vector< double > ExpectedReturnsOfDeterministicPoliciesFromSeeds (const State &state, const std::vector< int > &policy_seeds, const std::vector< const Policy * > &policies)
std::unique_ptr< ExternalSamplingMCCFRSolver > DeserializeExternalSamplingMCCFRSolver (const std::string &serialized, std::string delimiter)
std::vector< std::unique_ptr< State > > GetAllHistories (const Game &game, int depth_limit, bool include_terminals, bool include_chance_states)
std::vector< std::vector< std::string > > GetAllInformationStates (const Game &game, int depth_limit)
std::map< std::string, std::unique_ptr< State > > GetAllStates (const Game &game, int depth_limit, bool include_terminals, bool include_chance_states, bool stop_at_duplicates)
std::unordered_map< std::string, std::vector< Action > > GetLegalActionsMap (const Game &game, int depth_limit, Player player)
ActionsAndProbs GetSuccessorsWithProbs (const State &state, Player best_responder, const Policy *policy)
std::vector< std::pair< std::unique_ptr< State >, double > > DecisionNodes (const State &parent_state, Player best_responder, const Policy *policy)
absl::flat_hash_map< std::string, std::vector< std::pair< HistoryNode *, double > > > GetAllInfoSets (std::unique_ptr< State > state, Player best_responder, const Policy *policy, HistoryTree *tree)
std::shared_ptr< InfostateTree > MakeInfostateTree (const Game &game, Player acting_player, int max_move_limit=1000)
std::shared_ptr< InfostateTree > MakeInfostateTree (const std::vector< InfostateNode * > &start_nodes, int max_move_ahead_limit)
std::shared_ptr< InfostateTree > MakeInfostateTree (const std::vector< const InfostateNode * > &start_nodes, int max_move_ahead_limit=1000)
std::shared_ptr< InfostateTree > MakeInfostateTree (const std::vector< const State * > &start_states, const std::vector< double > &chance_reach_probs, std::shared_ptr< Observer > infostate_observer, Player acting_player, int max_move_ahead_limit=1000)
bool CheckSum (const SfStrategy &strategy, SequenceId id, double expected_sum)
bool IsValidSfStrategy (const SfStrategy &strategy)
std::shared_ptr< const MatrixGame > LoadMatrixGame (const std::string &name)
std::shared_ptr< const MatrixGame > AsMatrixGame (const Game *game)
std::shared_ptr< const MatrixGame > AsMatrixGame (const NormalFormGame *game)
std::shared_ptr< const MatrixGame > ExtensiveToMatrixGame (const Game &game)
std::pair< std::vector< double >, Action > MaxNSearch (const Game &game, const State *state, std::function< double(const State &, Player player)> value_function, int depth_limit)
int MemoryUsedMb (int nodes)
std::vector< double > dirichlet_noise (int count, double alpha, std::mt19937 *rng)
std::pair< double, Action > AlphaBetaSearch (const Game &game, const State *state, std::function< double(const State &)> value_function, int depth_limit, Player maximizing_player, bool use_undo)
std::pair< double, Action > ExpectiminimaxSearch (const Game &game, const State *state, std::function< double(const State &)> value_function, int depth_limit, Player maximizing_player)
bool IsValidProbDistribution (const ActionsAndProbs &probs)
bool IsPositiveProbDistribution (const ActionsAndProbs &probs)
std::ostream & operator<< (std::ostream &os, const OnlineStats &stats)
std::unique_ptr< OutcomeSamplingMCCFRSolver > DeserializeOutcomeSamplingMCCFRSolver (const std::string &serialized, std::string delimiter)
absl::flat_hash_map< std::string, double > PolicyIteration (const Game &game, int depth_limit, double threshold)
std::unique_ptr< open_spiel::HistoryDistribution > CloneBeliefs (const open_spiel::HistoryDistribution &beliefs)
HistoryDistribution GetStateDistribution (const State &state, const Policy &opponent_policy)
std::unique_ptr< HistoryDistribution > UpdateIncrementalStateDistribution (const State &state, const Policy &opponent_policy, int player_id, std::unique_ptr< HistoryDistribution > previous)
std::string PrintBeliefs (const HistoryDistribution &beliefs, int player_id)
bool CheckBeliefs (const State &ground_truth_state, const HistoryDistribution &beliefs, int player_id)
double Exploitability (const Game &game, const Policy &policy)
double Exploitability (const Game &game, const std::unordered_map< std::string, ActionsAndProbs > &policy)
double NashConv (const Game &game, const Policy &policy)
double NashConv (const Game &game, const Policy &policy, bool use_state_get_policy)
double NashConv (const Game &game, const std::unordered_map< std::string, ActionsAndProbs > &policy)
std::shared_ptr< const TensorGame > LoadTensorGame (const std::string &name)
std::shared_ptr< const TensorGame > AsTensorGame (const Game *game)
std::shared_ptr< const TensorGame > AsTensorGame (const NormalFormGame *game)
BatchedTrajectory RecordBatchedTrajectory (const Game &game, const std::vector< TabularPolicy > &policies, const State &initial_state, const std::unordered_map< std::string, int > &state_to_index, int batch_size, bool include_full_observations, std::mt19937 *rng_ptr, int max_unroll_length)
BatchedTrajectory RecordTrajectory (const Game &game, const std::vector< TabularPolicy > &policies, const State &initial_state, const std::unordered_map< std::string, int > &state_to_index, bool include_full_observations, std::mt19937 *rng)
BatchedTrajectory RecordBatchedTrajectory (const Game &game, const std::vector< TabularPolicy > &policies, const std::unordered_map< std::string, int > &state_to_index, int batch_size, bool include_full_observations, std::mt19937 *rng_ptr, int max_unroll_length)
BatchedTrajectory RecordBatchedTrajectory (const Game &game, const std::vector< TabularPolicy > &policies, const std::unordered_map< std::string, int > &state_to_index, int batch_size, bool include_full_observations, int seed, int max_unroll_length)
BatchedTrajectory RecordTrajectory (const Game &game, const std::vector< TabularPolicy > &policies, const std::unordered_map< std::string, int > &state_to_index, bool include_full_observations, std::mt19937 *rng_ptr)
std::map< std::string, double > ValueIteration (const Game &game, int depth_limit, double threshold)
Variables
constexpr const int kSerializationVersion = 1
constexpr const char * kSerializeMetaSectionHeader = "[Meta]"
constexpr const char * kSerializeGameSectionHeader = "[Game]"
constexpr const char * kSerializeSolverTypeSectionHeader = "[SolverType]"
constexpr const char * kSerializeSolverSpecificStateSectionHeader
constexpr const char * kSerializeSolverValuesTableSectionHeader
constexpr const char * kSerializeSolverRNGSectionHeader = "[SolverRNG]"
constexpr const char * kSerializeSolverAverageTypeSectionHeader
constexpr const char * kSerializeSolverDefaultPolicySectionHeader
constexpr const int kNumPlayers = 2
constexpr const char * kDummyRootNodeInfostate = "(root)"
constexpr const char * kFillerInfostate = "(fill)"
constexpr SequenceId kUndefinedSequenceId = SequenceId()
constexpr DecisionId kUndefinedDecisionId = DecisionId()
constexpr LeafId kUndefinedLeafId = LeafId()
constexpr double kTieTolerance = 0.00001
constexpr int kUnexpandedVisitCount = -1
constexpr int kUnlimitedNumWorldSamples = -1
int MIN_GC_LIMIT = 5
constexpr double kBannedAction = -0.
constexpr double kDefaultBiasing = 0.6
constexpr double kDefaultExploration = 0.5
constexpr ActionObservationHistory * kNoActionObsTargetSpecified = nullptr
constexpr PublicObservationHistory * kNoPublicObsTargetSpecified = nullptr
constexpr const char * kSerializeSolverEpsilonSectionHeader = "[SolverEpsilon]"
Typedef Documentation
CFRInfoStateValuesTable
using open_spiel::algorithms::CFRInfoStateValuesTable
Initial value:
    std::unordered_map<std::string, CFRInfoStateValues>
Definition at line 103 of file cfr.h.
CorrelationDevice
using open_spiel::algorithms::CorrelationDevice = std::vector<std::pair<double, TabularPolicy>>
Definition at line 74 of file corr_dist.h.
InfostateResampler
using open_spiel::algorithms::InfostateResampler
Initial value:
 std::function<std::unique_ptr<State>(
    const State& state, Player pl, std::function<double()> rng)>
Definition at line 60 of file is_mcts.h.
ISMCTSStateKey
using open_spiel::algorithms::ISMCTSStateKey = std::pair<Player, std::string>
Definition at line 41 of file is_mcts.h.
NormalFormCorrelationDevice
using open_spiel::algorithms::NormalFormCorrelationDevice = std::vector<NormalFormJointPolicyWithProb>
Definition at line 93 of file corr_dist.h.
OOSInfoStateValuesTable
using open_spiel::algorithms::OOSInfoStateValuesTable = CFRInfoStateValuesTable
Definition at line 134 of file oos.h.
ProbDistribution
using open_spiel::algorithms::ProbDistribution = std::vector<double>
Definition at line 131 of file oos.h.
SfStrategy
using open_spiel::algorithms::SfStrategy = TreeplexVector<double>
Definition at line 223 of file infostate_tree.h.
Enumeration Type Documentation
AverageType
enum class open_spiel::algorithms::AverageType strong
Enumerator
kSimple
kFull
Definition at line 52 of file external_sampling_mccfr.h.
                       {
  kSimple,
  kFull,
};
ChildSelectionPolicy
enum class open_spiel::algorithms::ChildSelectionPolicy strong
Enumerator
UCT
PUCT
Definition at line 74 of file mcts.h.
{
  UCT,
  PUCT,
};
InfostateNodeType
enum open_spiel::algorithms::InfostateNodeType
Enumerator
kDecisionInfostateNode
kObservationInfostateNode
kTerminalInfostateNode
Definition at line 81 of file infostate_tree.h.
                       {
  kDecisionInfostateNode,
  kObservationInfostateNode,
  kTerminalInfostateNode
};
ISMCTSFinalPolicyType
enum class open_spiel::algorithms::ISMCTSFinalPolicyType strong
Enumerator
kNormalizedVisitCount
kMaxVisitCount
kMaxValue
Definition at line 43 of file is_mcts.h.
{
  kNormalizedVisitCount,
  kMaxVisitCount,
  kMaxValue,
};
Targeting
enum open_spiel::algorithms::Targeting
Enumerator
kDoNotUseTargeting
kInfoStateTargeting
kPublicStateTargeting
Definition at line 115 of file oos.h.
               {
  kDoNotUseTargeting,
  // Target samples to the current information state.
  // More precisely, target the current Action-Observation history (AOH),
  // which coincides with the notion of information states on the player
  // states.
  kInfoStateTargeting,
  // Target samples to the current public state.
  // More precisely, target the current Public-Observation history (POH).
  kPublicStateTargeting,
};
Function Documentation
AFCCEDist()
double open_spiel::algorithms::AFCCEDist (const Game & game, CorrDistConfig config, const CorrelationDevice & mu)
Definition at line 210 of file corr_dist.cc.
{
  // Check that the config matches what is supported.
  SPIEL_CHECK_TRUE(config.deterministic);
  // Check for proper probability distribution.
  CheckCorrelationDeviceProbDist(mu);
  auto afcce_game =
      std::make_shared<AFCCEGame>(game.shared_from_this(), config, mu);
  // Note that the policies are already inside the game via the correlation
  // device, mu. So this is a simple wrapper policy that simply follows the
  // recommendations.
  AFCCETabularPolicy policy(afcce_game->FollowAction(),
                            afcce_game->DefectAction());
  return NashConv(*afcce_game, policy, true);
}
References open_spiel::algorithms::CorrDistConfig::deterministic, NashConv(), and SPIEL_CHECK_TRUE.
AFCEDist()
double open_spiel::algorithms::AFCEDist (const Game & game, CorrDistConfig config, const CorrelationDevice & mu)
Definition at line 192 of file corr_dist.cc.
{
  // Check that the config matches what is supported.
  SPIEL_CHECK_TRUE(config.deterministic);
  // Check for proper probability distribution.
  CheckCorrelationDeviceProbDist(mu);
  auto afce_game =
      std::make_shared<AFCEGame>(game.shared_from_this(), config, mu);
  // Note that the policies are already inside the game via the correlation
  // device, mu. So this is a simple wrapper policy that simply follows the
  // recommendations.
  AFCETabularPolicy policy(config);
  return NashConv(*afce_game, policy, true);
}
References open_spiel::algorithms::CorrDistConfig::deterministic, NashConv(), and SPIEL_CHECK_TRUE.
AlphaBetaSearch()
std::pair< double, Action > open_spiel::algorithms::AlphaBetaSearch (const Game & game, const State * state, std::function< double(const State &)> value_function, int depth_limit, Player maximizing_player, bool use_undo)
Definition at line 222 of file minimax.cc.
{
  SPIEL_CHECK_LE(game.NumPlayers(), 2);
  // Check to ensure the correct setup intended for this algorithm.
  // Note: do no check perfect vs. imperfect information to support use of
  // minimax as a subroutine of PIMC.
  GameType game_info = game.GetType();
  SPIEL_CHECK_EQ(game_info.chance_mode, GameType::ChanceMode::kDeterministic);
  SPIEL_CHECK_EQ(game_info.dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(game_info.utility, GameType::Utility::kZeroSum);
  SPIEL_CHECK_EQ(game_info.reward_model, GameType::RewardModel::kTerminal);
  std::unique_ptr<State> search_root;
  if (state == nullptr) {
    search_root = game.NewInitialState();
  } else {
    search_root = state->Clone();
  }
  if (maximizing_player == kInvalidPlayer) {
    maximizing_player = search_root->CurrentPlayer();
  }
  double infinity = std::numeric_limits<double>::infinity();
  Action best_action = kInvalidAction;
  double value = _alpha_beta(
      search_root.get(), /*depth=*/depth_limit, /*alpha=*/-infinity,
      /*beta=*/infinity, value_function, maximizing_player, &best_action,
      use_undo);
  return {value, best_action};
}
References open_spiel::GameType::chance_mode, open_spiel::GameType::dynamics, open_spiel::GameType::kDeterministic, open_spiel::kInvalidAction, open_spiel::kInvalidPlayer, open_spiel::GameType::kSequential, open_spiel::GameType::kTerminal, open_spiel::GameType::kZeroSum, open_spiel::GameType::reward_model, SPIEL_CHECK_EQ, SPIEL_CHECK_LE, state, open_spiel::GameType::utility, and value.
Referenced by open_spiel::tiny_bridge::Score_p0().
AsMatrixGame() [1/2]
std::shared_ptr< const matrix_game::MatrixGame > open_spiel::algorithms::AsMatrixGame (const Game * game)
Definition at line 46 of file matrix_game_utils.cc.
{
  const NormalFormGame* nfg = dynamic_cast<const NormalFormGame*>(game);
  SPIEL_CHECK_TRUE(nfg != nullptr);
  return AsMatrixGame(nfg);
}
References AsMatrixGame(), and SPIEL_CHECK_TRUE.
Referenced by AsMatrixGame(), and LoadMatrixGame().
AsMatrixGame() [2/2]
std::shared_ptr< const matrix_game::MatrixGame > open_spiel::algorithms::AsMatrixGame (const NormalFormGame * game)
Definition at line 52 of file matrix_game_utils.cc.
{
  SPIEL_CHECK_EQ(game->NumPlayers(), 2);
  std::unique_ptr<State> initial_state = game->NewInitialState();
  std::vector<std::vector<Action>> legal_actions = {
      initial_state->LegalActions(0), initial_state->LegalActions(1)};
  std::vector<std::string> row_names;
  std::vector<std::string> col_names;
  std::vector<double> row_utils;
  std::vector<double> col_utils;
  int num_rows = legal_actions[0].size();
  int num_cols = legal_actions[1].size();
  GameType type = game->GetType();
  type.min_num_players = 2;
  type.max_num_players = 2;
  for (int r = 0; r < num_rows; ++r) {
    Action row_action = legal_actions[0][r];
    row_names.push_back(initial_state->ActionToString(0, row_action));
    for (int c = 0; c < num_cols; ++c) {
      Action col_action = legal_actions[1][c];
      if (col_names.size() < num_cols) {
        col_names.push_back(initial_state->ActionToString(1, col_action));
      }
      std::unique_ptr<State> clone = initial_state->Clone();
      clone->ApplyActions({row_action, col_action});
      SPIEL_CHECK_TRUE(clone->IsTerminal());
      std::vector<double> returns = clone->Returns();
      SPIEL_CHECK_EQ(returns.size(), 2);
      row_utils.push_back(returns[0]);
      col_utils.push_back(returns[1]);
    }
  }
  return std::shared_ptr<MatrixGame>(
      new MatrixGame(type, {}, row_names, col_names, row_utils, col_utils));
}
References open_spiel::GameType::max_num_players, open_spiel::GameType::min_num_players, r, SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
AsTensorGame() [1/2]
std::shared_ptr< const tensor_game::TensorGame > open_spiel::algorithms::AsTensorGame (const Game * game)
Definition at line 43 of file tensor_game_utils.cc.
{
  const NormalFormGame* nfg = dynamic_cast<const NormalFormGame*>(game);
  SPIEL_CHECK_TRUE(nfg);
  return AsTensorGame(nfg);
}
References AsTensorGame(), and SPIEL_CHECK_TRUE.
Referenced by AsTensorGame(), and LoadTensorGame().
AsTensorGame() [2/2]
std::shared_ptr< const tensor_game::TensorGame > open_spiel::algorithms::AsTensorGame (const NormalFormGame * game)
Definition at line 49 of file tensor_game_utils.cc.
{
  const int num_players = game->NumPlayers();
  std::unique_ptr<State> initial_state = game->NewInitialState();
  std::vector<std::vector<Action>> legal_actions(num_players);
  std::vector<std::vector<std::string>> action_names(num_players);
  for (Player player = 0; player < num_players; ++player) {
    legal_actions[player] = initial_state->LegalActions(player);
    for (const Action& action : legal_actions[player]) {
      action_names[player].push_back(
          initial_state->ActionToString(player, action));
    }
  }
  std::vector<std::vector<double>> utils(num_players);
  GameType type = game->GetType();
  type.min_num_players = num_players;
  type.max_num_players = num_players;
  std::vector<Action> actions(num_players);
  bool last_entry;
  do {
    std::unique_ptr<State> clone = initial_state->Clone();
    clone->ApplyActions(actions);
    SPIEL_CHECK_TRUE(clone->IsTerminal());
    std::vector<double> returns = clone->Returns();
    SPIEL_CHECK_EQ(returns.size(), num_players);
    for (Player player = 0; player < num_players; ++player) {
      utils[player].push_back(returns[player]);
    }
    last_entry = true;
    for (Player player = num_players - 1; player >= 0; --player) {
      if (++actions[player] < legal_actions[player].size()) {
        last_entry = false;
        break;
      } else {
        actions[player] = 0;
      }
    }
  } while (!last_entry);
  return std::shared_ptr<TensorGame>(
      new TensorGame(type, {}, action_names, utils));
}
References action, open_spiel::GameType::max_num_players, open_spiel::GameType::min_num_players, player, size, SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
CCEDist() [1/3]
CorrDistInfo open_spiel::algorithms::CCEDist (const Game & game, const CorrelationDevice & mu, const float prob_cut_threshold, const float action_value_tolerance)
Definition at line 290 of file corr_dist.cc.
{
  // Check for proper probability distribution.
  CheckCorrelationDeviceProbDist(mu);
  CorrDistConfig config;
  auto cce_game =
      std::make_shared<CCEGame>(game.shared_from_this(), config, mu);
  CorrDistInfo dist_info{0.0,
                         std::vector<double>(game.NumPlayers(), 0),
                         std::vector<double>(game.NumPlayers(), 0),
                         std::vector<double>(game.NumPlayers(), 0),
                         std::vector<TabularPolicy>(game.NumPlayers()),
                         {}};
  // Note: cannot simply call NashConv here as in the other examples. Because
  // this auxiliary game does not have the "follow" action, it is possible that
  // a best response against the correlated distribution is *negative* (i.e.
  // the best deterministic policy is not as good as simply following the
  // correlated recommendations), but the NashConv function has a check that the
  // incentive is >= zero, so it would fail.
  CCETabularPolicy policy;
  std::unique_ptr<State> root = cce_game->NewInitialState();
  for (auto p = Player{0}; p < cce_game->NumPlayers(); ++p) {
    TabularBestResponse best_response(*cce_game, p, &policy, prob_cut_threshold,
                                      action_value_tolerance);
    dist_info.best_response_values[p] = best_response.Value(*root);
    dist_info.best_response_policies[p] = best_response.GetBestResponsePolicy();
  }
  dist_info.on_policy_values = ExpectedReturns(*root, policy, -1, false);
  SPIEL_CHECK_EQ(dist_info.best_response_values.size(),
                 dist_info.on_policy_values.size());
  for (auto p = Player{0}; p < cce_game->NumPlayers(); ++p) {
    // For reasons indicated in comment at the top of this funciton, we have
    // max(0, ...) here.
    dist_info.deviation_incentives[p] = std::max(
        0.0, dist_info.best_response_values[p] - dist_info.on_policy_values[p]);
    dist_info.dist_value += dist_info.deviation_incentives[p];
  }
  return dist_info;
}
References ExpectedReturns(), and SPIEL_CHECK_EQ.
CCEDist() [2/3]
CorrDistInfo open_spiel::algorithms::CCEDist (const Game & game, const CorrelationDevice & mu, int player, const float prob_cut_threshold, const float action_value_tolerance)
Definition at line 257 of file corr_dist.cc.
{
  // Check for proper probability distribution.
  CheckCorrelationDeviceProbDist(mu);
  CorrDistConfig config;
  auto cce_game =
      std::make_shared<CCEGame>(game.shared_from_this(), config, mu);
  CorrDistInfo dist_info{
      0.0,
      std::vector<double>(1, std::numeric_limits<double>::quiet_NaN()),
      std::vector<double>(1, 0),
      std::vector<double>(1, 0),
      std::vector<TabularPolicy>(1),
      {}};
  CCETabularPolicy policy;
  std::unique_ptr<State> root = cce_game->NewInitialState();
  TabularBestResponse best_response(*cce_game, player, &policy,
                                    prob_cut_threshold, action_value_tolerance);
  // Do not populate on policy values to save unnecessary computation.
  // dist_info.on_policy_values[0] = ExpectedReturns(
  //     *root, policy, -1, false)[player];
  dist_info.best_response_values[0] = best_response.Value(*root);
  dist_info.best_response_policies[0] = best_response.GetBestResponsePolicy();
  dist_info.deviation_incentives[0] = std::max(
      0.0, dist_info.best_response_values[0] - dist_info.on_policy_values[0]);
  dist_info.dist_value += dist_info.deviation_incentives[0];
  return dist_info;
}
References player.
CCEDist() [3/3]
double open_spiel::algorithms::CCEDist (const Game & game, const NormalFormCorrelationDevice & mu)
Definition at line 243 of file corr_dist.cc.
{
  if (game.GetType().information == GameType::Information::kOneShot) {
    std::shared_ptr<const Game> actual_game = ConvertToTurnBased(game);
    CorrelationDevice converted_mu = ConvertCorrelationDevice(*actual_game, mu);
    CorrDistConfig config;
    return EFCCEDist(*actual_game, config, converted_mu);
  } else {
    SPIEL_CHECK_EQ(game.GetType().dynamics, GameType::Dynamics::kSequential);
    CorrelationDevice converted_mu = ConvertCorrelationDevice(game, mu);
    CorrDistConfig config;
    return EFCCEDist(game, config, converted_mu);
  }
}
References open_spiel::ConvertToTurnBased(), EFCCEDist(), open_spiel::GameType::kOneShot, open_spiel::GameType::kSequential, and SPIEL_CHECK_EQ.
Referenced by open_spiel::init_pyspiel_algorithms_corr_dist().
CEDist() [1/2]
CorrDistInfo open_spiel::algorithms::CEDist (const Game & game, const CorrelationDevice & mu, const float action_value_tolerance)
Definition at line 335 of file corr_dist.cc.
{
  // Check for proper probability distribution.
  CheckCorrelationDeviceProbDist(mu);
  CorrDistConfig config;
  auto ce_game = std::make_shared<CEGame>(game.shared_from_this(), config, mu);
  CorrDistInfo dist_info{
      0.0,
      std::vector<double>(game.NumPlayers(), 0),
      std::vector<double>(game.NumPlayers(), 0),
      std::vector<double>(game.NumPlayers(), 0),
      {},
      std::vector<std::vector<TabularPolicy>>(game.NumPlayers())};
  CETabularPolicy policy(config);
  // For similar reasons as in CCEDist, we must manually do NashConv.
  std::unique_ptr<State> root = ce_game->NewInitialState();
  for (auto p = Player{0}; p < ce_game->NumPlayers(); ++p) {
    TabularBestResponse best_response(*ce_game, p, &policy, -1.0,
                                      action_value_tolerance);
    dist_info.best_response_values[p] = best_response.Value(*root);
    // This policy has all of the conditional ones built in. We have to extract
    // one per signal by mapping back the info states.
    TabularPolicy big_br_policy = best_response.GetBestResponsePolicy();
    absl::flat_hash_map<int, TabularPolicy> extracted_policies;
    for (const auto& infostate_and_probs : big_br_policy.PolicyTable()) {
      std::string full_info_state = infostate_and_probs.first;
      const size_t idx = full_info_state.find(config.recommendation_delimiter);
      SPIEL_CHECK_NE(idx, std::string::npos);
      std::vector<std::string> parts =
          absl::StrSplit(full_info_state, config.recommendation_delimiter);
      SPIEL_CHECK_EQ(parts.size(), 2);
      int signal = -1;
      SPIEL_CHECK_TRUE(absl::SimpleAtoi(parts[1], &signal));
      SPIEL_CHECK_GE(signal, 0);
      extracted_policies[signal].SetStatePolicy(parts[0],
                                                infostate_and_probs.second);
    }
    for (const auto& signal_and_policy : extracted_policies) {
      dist_info.conditional_best_response_policies[p].push_back(
          signal_and_policy.second);
    }
  }
  dist_info.on_policy_values = ExpectedReturns(*root, policy, -1, false);
  SPIEL_CHECK_EQ(dist_info.best_response_values.size(),
                 dist_info.on_policy_values.size());
  for (auto p = Player{0}; p < ce_game->NumPlayers(); ++p) {
    // For reasons indicated in comment at the top of this funciton, we have
    // max(0, ...) here.
    dist_info.deviation_incentives[p] = std::max(
        0.0, dist_info.best_response_values[p] - dist_info.on_policy_values[p]);
    dist_info.dist_value += dist_info.deviation_incentives[p];
  }
  return dist_info;
}
References ExpectedReturns(), open_spiel::TabularPolicy::PolicyTable(), open_spiel::algorithms::CorrDistConfig::recommendation_delimiter, absl::SimpleAtoi(), SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_NE, SPIEL_CHECK_TRUE, and absl::StrSplit().
CEDist() [2/2]
double open_spiel::algorithms::CEDist (const Game & game, const NormalFormCorrelationDevice & mu)
Definition at line 229 of file corr_dist.cc.
{
  if (game.GetType().information == GameType::Information::kOneShot) {
    std::shared_ptr<const Game> actual_game = ConvertToTurnBased(game);
    CorrelationDevice converted_mu = ConvertCorrelationDevice(*actual_game, mu);
    CorrDistConfig config;
    return EFCEDist(*actual_game, config, converted_mu);
  } else {
    SPIEL_CHECK_EQ(game.GetType().dynamics, GameType::Dynamics::kSequential);
    CorrelationDevice converted_mu = ConvertCorrelationDevice(game, mu);
    CorrDistConfig config;
    return EFCEDist(game, config, converted_mu);
  }
}
References open_spiel::ConvertToTurnBased(), EFCEDist(), open_spiel::GameType::kOneShot, open_spiel::GameType::kSequential, and SPIEL_CHECK_EQ.
Referenced by open_spiel::init_pyspiel_algorithms_corr_dist().
CheckBeliefs()
bool open_spiel::algorithms::CheckBeliefs (const State & ground_truth_state, const HistoryDistribution & beliefs, int player_id)
Definition at line 332 of file state_distribution.cc.
{
  const std::string infostate =
      ground_truth_state.InformationStateString(player_id);
  for (int i = 0; i < beliefs.first.size(); ++i) {
    if (Near(beliefs.second[i], 0.0, 1e-5)) {
      continue;
    }
    SPIEL_CHECK_EQ(infostate,
                   beliefs.first[i]->InformationStateString(player_id));
    SPIEL_CHECK_EQ(ground_truth_state.FullHistory().size(),
                   beliefs.first[i]->FullHistory().size());
    SPIEL_CHECK_EQ(ground_truth_state.IsTerminal(),
                   beliefs.first[i]->IsTerminal());
  }
  return true;
}
References open_spiel::State::FullHistory(), i, open_spiel::State::InformationStateString(), open_spiel::State::IsTerminal(), open_spiel::Near(), and SPIEL_CHECK_EQ.
Referenced by UpdateIncrementalStateDistribution().
CheckSum()
bool open_spiel::algorithms::CheckSum (const SfStrategy & strategy, SequenceId id, double expected_sum)
Definition at line 695 of file infostate_tree.cc.
{
  if (fabs(strategy[id] - expected_sum) > 1e-13) {
    return false;
  }
  const InfostateTree* tree = strategy.tree();
  if (tree->IsLeafSequence(id)) {
    return true;
  }
  double actual_sum = 0.;
  const InfostateNode* node = tree->observation_infostate(id);
  for (SequenceId sub_seq : node->AllSequenceIds()) {
    actual_sum += strategy[sub_seq];
  }
  if (fabs(actual_sum - expected_sum) > 1e-13) {
    return false;
  }
  for (SequenceId sub_seq : node->AllSequenceIds()) {
    if (!CheckSum(strategy, sub_seq, strategy[sub_seq])) {
      return false;
    }
  }
  return true;
}
References open_spiel::algorithms::InfostateNode::AllSequenceIds(), CheckSum(), open_spiel::algorithms::InfostateTree::IsLeafSequence(), open_spiel::algorithms::InfostateTree::observation_infostate(), and open_spiel::algorithms::internal::TreeVector< T, Id >::tree().
Referenced by CheckSum(), and IsValidSfStrategy().
CloneBeliefs()
std::unique_ptr< open_spiel::HistoryDistribution > open_spiel::algorithms::CloneBeliefs (const open_spiel::HistoryDistribution & beliefs)
Definition at line 132 of file state_distribution.cc.
{
  auto beliefs_copy = absl::make_unique<open_spiel::HistoryDistribution>();
  for (int i = 0; i < beliefs.first.size(); ++i) {
    beliefs_copy->first.push_back(beliefs.first[i]->Clone());
    beliefs_copy->second.push_back(beliefs.second[i]);
  }
  return beliefs_copy;
}
References i.
DecisionNodes()
std::vector< std::pair< std::unique_ptr< State >, double > > open_spiel::algorithms::DecisionNodes (const State & parent_state, Player best_responder, const Policy * policy)
Definition at line 187 of file history_tree.cc.
{
  // If the state is terminal, then there are no more decisions to be made,
  // so we're done.
  if (parent_state.IsTerminal()) return {};
  std::vector<std::pair<std::unique_ptr<State>, double>> states_and_probs;
  // We only consider states where the best_responder is making a decision.
  if (parent_state.CurrentPlayer() == best_responder) {
    states_and_probs.push_back({parent_state.Clone(), 1.});
  }
  ActionsAndProbs actions_and_probs =
      GetSuccessorsWithProbs(parent_state, best_responder, policy);
  for (open_spiel::Action action : parent_state.LegalActions()) {
    std::unique_ptr<State> child = parent_state.Child(action);
    // We recurse here to get the correct probabilities for all children.
    // This could probably be done in a cleaner, more performant way, but as
    // this is only done once, at the start of the exploitability calculation,
    // this is fine for now.
    std::vector<std::pair<std::unique_ptr<State>, double>> children =
        DecisionNodes(*child, best_responder, policy);
    const double policy_prob = GetProb(actions_and_probs, action);
    SPIEL_CHECK_PROB_TOLERANCE(policy_prob, ProbabilityDefaultTolerance());
    for (auto& [state, prob] : children) {
      states_and_probs.push_back(
          {std::move(state),
           // We weight the child probabilities by the probability of taking
           // the action that would lead to them.
           policy_prob * prob});
    }
  }
  return states_and_probs;
}
References action, actions_and_probs, open_spiel::State::Child(), open_spiel::State::Clone(), open_spiel::State::CurrentPlayer(), DecisionNodes(), open_spiel::GetProb(), GetSuccessorsWithProbs(), open_spiel::State::IsTerminal(), open_spiel::State::LegalActions(), open_spiel::ProbabilityDefaultTolerance(), SPIEL_CHECK_PROB_TOLERANCE, and state.
Referenced by DecisionNodes(), and GetAllInfoSets().
DeserializeCFRBRSolver()
std::unique_ptr< CFRBRSolver > open_spiel::algorithms::DeserializeCFRBRSolver (const std::string & serialized, std::string delimiter)
Definition at line 84 of file cfr_br.cc.
{
  auto partial = PartiallyDeserializeCFRSolver(serialized);
  SPIEL_CHECK_EQ(partial.solver_type, "CFRBRSolver");
  auto solver = std::make_unique<CFRBRSolver>(
      partial.game, std::stoi(partial.solver_specific_state));
  DeserializeCFRInfoStateValuesTable(partial.serialized_cfr_values_table,
                                     &solver->InfoStateValuesTable(),
                                     delimiter);
  return solver;
}
References DeserializeCFRInfoStateValuesTable(), PartiallyDeserializeCFRSolver(), and SPIEL_CHECK_EQ.
Referenced by open_spiel::init_pyspiel_policy().
DeserializeCFRInfoStateValues()
CFRInfoStateValues open_spiel::algorithms::DeserializeCFRInfoStateValues (absl::string_view serialized)
Definition at line 534 of file cfr.cc.
{
  CFRInfoStateValues res = CFRInfoStateValues();
  if (serialized.empty()) return res;
  std::vector<std::vector<absl::string_view>> str_values;
  str_values.reserve(4);
  for (absl::string_view sv : absl::StrSplit(serialized, ';')) {
    str_values.push_back(absl::StrSplit(sv, ','));
  }
  int num_elements = str_values.at(0).size();
  res.legal_actions.reserve(num_elements);
  res.cumulative_regrets.reserve(num_elements);
  res.cumulative_policy.reserve(num_elements);
  res.current_policy.reserve(num_elements);
  // Insert the actual values
  int la_value;
  double cumu_regret_value, cumu_policy_value, curr_policy_value;
  for (int i = 0; i < num_elements; i++) {
    SPIEL_CHECK_TRUE(absl::SimpleAtoi(str_values.at(0).at(i), &la_value));
    absl::from_chars(
        str_values.at(1).at(i).data(),
        str_values.at(1).at(i).data() + str_values.at(1).at(i).size(),
        cumu_regret_value);
    absl::from_chars(
        str_values.at(2).at(i).data(),
        str_values.at(2).at(i).data() + str_values.at(2).at(i).size(),
        cumu_policy_value);
    absl::from_chars(
        str_values.at(3).at(i).data(),
        str_values.at(3).at(i).data() + str_values.at(3).at(i).size(),
        curr_policy_value);
    res.legal_actions.push_back(la_value);
    res.cumulative_regrets.push_back(cumu_regret_value);
    res.cumulative_policy.push_back(cumu_policy_value);
    res.current_policy.push_back(curr_policy_value);
  }
  return res;
}
References open_spiel::algorithms::CFRInfoStateValues::cumulative_policy, open_spiel::algorithms::CFRInfoStateValues::cumulative_regrets, open_spiel::algorithms::CFRInfoStateValues::current_policy, absl::string_view::empty(), absl::from_chars(), i, open_spiel::algorithms::CFRInfoStateValues::legal_actions, absl::SimpleAtoi(), SPIEL_CHECK_TRUE, and absl::StrSplit().
Referenced by DeserializeCFRInfoStateValuesTable().
DeserializeCFRInfoStateValuesTable()
void open_spiel::algorithms::DeserializeCFRInfoStateValuesTable (absl::string_view serialized, CFRInfoStateValuesTable * result, std::string delimiter)
Definition at line 663 of file cfr.cc.
{
  if (serialized.empty()) return;
  std::vector<absl::string_view> splits = absl::StrSplit(serialized, delimiter);
  for (int i = 0; i < splits.size(); i += 2) {
    result->insert({std::string(splits.at(i)),
                    DeserializeCFRInfoStateValues(splits.at(i + 1))});
  }
}
References DeserializeCFRInfoStateValues(), absl::string_view::empty(), i, and absl::StrSplit().
Referenced by DeserializeCFRBRSolver(), DeserializeCFRPlusSolver(), DeserializeCFRSolver(), DeserializeExternalSamplingMCCFRSolver(), and DeserializeOutcomeSamplingMCCFRSolver().
DeserializeCFRPlusSolver()
std::unique_ptr< CFRPlusSolver > open_spiel::algorithms::DeserializeCFRPlusSolver (const std::string & serialized, std::string delimiter)
Definition at line 711 of file cfr.cc.
{
  auto partial = PartiallyDeserializeCFRSolver(serialized);
  SPIEL_CHECK_EQ(partial.solver_type, "CFRPlusSolver");
  auto solver = std::make_unique<CFRPlusSolver>(
      partial.game, std::stoi(partial.solver_specific_state));
  DeserializeCFRInfoStateValuesTable(partial.serialized_cfr_values_table,
                                     &solver->InfoStateValuesTable(),
                                     delimiter);
  return solver;
}
References DeserializeCFRInfoStateValuesTable(), PartiallyDeserializeCFRSolver(), and SPIEL_CHECK_EQ.
Referenced by open_spiel::init_pyspiel_policy().
DeserializeCFRSolver()
std::unique_ptr< CFRSolver > open_spiel::algorithms::DeserializeCFRSolver (const std::string & serialized, std::string delimiter)
Definition at line 699 of file cfr.cc.
{
  auto partial = PartiallyDeserializeCFRSolver(serialized);
  SPIEL_CHECK_EQ(partial.solver_type, "CFRSolver");
  auto solver = std::make_unique<CFRSolver>(
      partial.game, std::stoi(partial.solver_specific_state));
  DeserializeCFRInfoStateValuesTable(partial.serialized_cfr_values_table,
                                     &solver->InfoStateValuesTable(),
                                     delimiter);
  return solver;
}
References DeserializeCFRInfoStateValuesTable(), PartiallyDeserializeCFRSolver(), and SPIEL_CHECK_EQ.
Referenced by open_spiel::init_pyspiel_policy().
DeserializeExternalSamplingMCCFRSolver()
std::unique_ptr< ExternalSamplingMCCFRSolver > open_spiel::algorithms::DeserializeExternalSamplingMCCFRSolver (const std::string & serialized, std::string delimiter)
Definition at line 234 of file external_sampling_mccfr.cc.
{
  auto partial = PartiallyDeserializeCFRSolver(serialized);
  SPIEL_CHECK_EQ(partial.solver_type, "ExternalSamplingMCCFRSolver");
  enum Section {
    kInvalid = -1,
    kRNG = 0,
    kAverageType = 1,
    kDefaultPolicy = 2
  };
  std::array<std::string, 3> section_strings = {"", "", ""};
  Section current_section = kInvalid;
  std::vector<absl::string_view> lines =
      absl::StrSplit(partial.solver_specific_state, '\n');
  for (int i = 0; i < lines.size(); i++) {
    if (lines[i] == kSerializeSolverRNGSectionHeader) {
      SPIEL_CHECK_EQ(current_section, kInvalid);
      current_section = kRNG;
    } else if (lines[i] == kSerializeSolverAverageTypeSectionHeader) {
      SPIEL_CHECK_EQ(current_section, kRNG);
      current_section = kAverageType;
    } else if (lines[i] == kSerializeSolverDefaultPolicySectionHeader) {
      SPIEL_CHECK_EQ(current_section, kAverageType);
      current_section = kDefaultPolicy;
    } else {
      SPIEL_CHECK_NE(current_section, kInvalid);
      absl::StrAppend(&section_strings[current_section], lines[i], "\n");
    }
  }
  // Remove trailing newline characters
  for (int i = 0; i < section_strings.size(); i++) {
    section_strings[i].erase(section_strings[i].length() - 1);
  }
  // Do the actual deserialization for all internal state values
  std::unique_ptr<std::mt19937> rng = std::make_unique<std::mt19937>();
  std::istringstream rng_stream(section_strings[kRNG]);
  rng_stream >> *rng;
  AverageType average_type;
  if (section_strings[kAverageType] == "FullAverageType")
    average_type = AverageType::kFull;
  else if (section_strings[kAverageType] == "SimpleAverageType")
    average_type = AverageType::kSimple;
  auto solver = std::make_unique<ExternalSamplingMCCFRSolver>(
      partial.game, DeserializePolicy(section_strings[kDefaultPolicy]),
      std::move(rng), average_type);
  DeserializeCFRInfoStateValuesTable(partial.serialized_cfr_values_table,
                                     &solver->InfoStateValuesTable(),
                                     delimiter);
  return solver;
}
References DeserializeCFRInfoStateValuesTable(), open_spiel::DeserializePolicy(), i, kFull, kSerializeSolverAverageTypeSectionHeader, kSerializeSolverDefaultPolicySectionHeader, kSerializeSolverRNGSectionHeader, kSimple, PartiallyDeserializeCFRSolver(), SPIEL_CHECK_EQ, SPIEL_CHECK_NE, absl::StrAppend(), and absl::StrSplit().
Referenced by open_spiel::init_pyspiel_policy().
DeserializeOutcomeSamplingMCCFRSolver()
std::unique_ptr< OutcomeSamplingMCCFRSolver > open_spiel::algorithms::DeserializeOutcomeSamplingMCCFRSolver (const std::string & serialized, std::string delimiter)
Definition at line 245 of file outcome_sampling_mccfr.cc.
{
  auto partial = PartiallyDeserializeCFRSolver(serialized);
  SPIEL_CHECK_EQ(partial.solver_type, "OutcomeSamplingMCCFRSolver");
  enum Section { kInvalid = -1, kRNG = 0, kEpsilon = 1, kDefaultPolicy = 2 };
  std::array<std::string, 3> section_strings = {"", "", ""};
  Section current_section = kInvalid;
  std::vector<absl::string_view> lines =
      absl::StrSplit(partial.solver_specific_state, '\n');
  for (int i = 0; i < lines.size(); i++) {
    if (lines[i] == kSerializeSolverRNGSectionHeader) {
      SPIEL_CHECK_EQ(current_section, kInvalid);
      current_section = kRNG;
    } else if (lines[i] == kSerializeSolverEpsilonSectionHeader) {
      SPIEL_CHECK_EQ(current_section, kRNG);
      current_section = kEpsilon;
    } else if (lines[i] == kSerializeSolverDefaultPolicySectionHeader) {
      SPIEL_CHECK_EQ(current_section, kEpsilon);
      current_section = kDefaultPolicy;
    } else {
      SPIEL_CHECK_NE(current_section, kInvalid);
      absl::StrAppend(&section_strings[current_section], lines[i], "\n");
    }
  }
  // Remove trailing newline characters
  for (int i = 0; i < section_strings.size(); i++) {
    section_strings[i].erase(section_strings[i].length() - 1);
  }
  // Do the actual deserialization for all internal state values
  std::mt19937 rng = std::mt19937();
  std::istringstream rng_stream(section_strings[kRNG]);
  rng_stream >> rng;
  // First scalar is epsilon, second is update_player
  std::string epsilon = section_strings[kEpsilon];
  auto solver = std::make_unique<OutcomeSamplingMCCFRSolver>(
      partial.game, DeserializePolicy(section_strings[kDefaultPolicy]),
      std::stod(epsilon), rng);
  DeserializeCFRInfoStateValuesTable(partial.serialized_cfr_values_table,
                                     &solver->InfoStateValuesTable(),
                                     delimiter);
  return solver;
}
References DeserializeCFRInfoStateValuesTable(), open_spiel::DeserializePolicy(), i, kSerializeSolverDefaultPolicySectionHeader, kSerializeSolverEpsilonSectionHeader, kSerializeSolverRNGSectionHeader, PartiallyDeserializeCFRSolver(), SPIEL_CHECK_EQ, SPIEL_CHECK_NE, absl::StrAppend(), and absl::StrSplit().
Referenced by open_spiel::init_pyspiel_policy().
DeterminizeCorrDev()
CorrelationDevice open_spiel::algorithms::DeterminizeCorrDev (const CorrelationDevice & corr_dev)
Definition at line 118 of file corr_dev_builder.cc.
{
  CorrDevBuilder cdb;
  for (const std::pair<double, TabularPolicy>& item : corr_dev) {
    cdb.AddMixedJointPolicy(item.second, item.first);
  }
  return cdb.GetCorrelationDevice();
}
References open_spiel::algorithms::CorrDevBuilder::AddMixedJointPolicy(), and open_spiel::algorithms::CorrDevBuilder::GetCorrelationDevice().
Referenced by open_spiel::init_pyspiel_algorithms_corr_dist().
dirichlet_noise()
std::vector< double > open_spiel::algorithms::dirichlet_noise (int count, double alpha, std::mt19937 * rng)
Definition at line 187 of file mcts.cc.
{
  std::vector<double> noise;
  noise.reserve(count);
  std::gamma_distribution<double> gamma(alpha, 1.0);
  for (int i = 0; i < count; ++i) {
    noise.emplace_back(gamma(*rng));
  }
  double sum = absl::c_accumulate(noise, 0.0);
  for (double& v : noise) {
    v /= sum;
  }
  return noise;
}
References absl::c_accumulate(), and i.
EFCCEDist()
double open_spiel::algorithms::EFCCEDist (const Game & game, CorrDistConfig config, const CorrelationDevice & mu)
Definition at line 173 of file corr_dist.cc.
{
  // Check that the config matches what is supported.
  SPIEL_CHECK_TRUE(config.deterministic);
  // Check for proper probability distribution.
  CheckCorrelationDeviceProbDist(mu);
  auto efcce_game =
      std::make_shared<EFCCEGame>(game.shared_from_this(), config, mu);
  // Note that the policies are already inside the game via the correlation
  // device, mu. So this is a simple wrapper policy that simply follows the
  // recommendations.
  EFCCETabularPolicy policy(efcce_game->FollowAction(),
                            efcce_game->DefectAction());
  return NashConv(*efcce_game, policy, true);
}
References open_spiel::algorithms::CorrDistConfig::deterministic, NashConv(), and SPIEL_CHECK_TRUE.
Referenced by CCEDist().
EFCEDist()
double open_spiel::algorithms::EFCEDist (const Game & game, CorrDistConfig config, const CorrelationDevice & mu)
Definition at line 155 of file corr_dist.cc.
{
  // Check that the config matches what is supported.
  SPIEL_CHECK_TRUE(config.deterministic);
  // Check for proper probability distribution.
  CheckCorrelationDeviceProbDist(mu);
  auto efce_game =
      std::make_shared<EFCEGame>(game.shared_from_this(), config, mu);
  // Note that the policies are already inside the game via the correlation
  // device, mu. So this is a simple wrapper policy that simply follows the
  // recommendations.
  EFCETabularPolicy policy(config);
  return NashConv(*efce_game, policy, true);
}
References open_spiel::algorithms::CorrDistConfig::deterministic, NashConv(), and SPIEL_CHECK_TRUE.
Referenced by CEDist().
ExpectedReturns() [1/2]
std::vector< double > open_spiel::algorithms::ExpectedReturns (const State & state, const Policy & joint_policy, int depth_limit, bool use_infostate_get_policy, float prob_cut_threshold)
Definition at line 322 of file expected_returns.cc.
{
  if (use_infostate_get_policy) {
    return ExpectedReturnsImpl(
        state,
        [&joint_policy](Player player, const std::string& info_state) {
          return joint_policy.GetStatePolicy(info_state);
        },
        depth_limit,
        prob_cut_threshold);
  } else {
    return ExpectedReturnsImpl(
        state,
        [&joint_policy](Player player, const State& state) {
          return joint_policy.GetStatePolicy(state, player);
        },
        depth_limit,
        prob_cut_threshold);
  }
}
References open_spiel::Policy::GetStatePolicy(), player, and state.
ExpectedReturns() [2/2]
std::vector< double > open_spiel::algorithms::ExpectedReturns (const State & state, const std::vector< const Policy * > & policies, int depth_limit, bool use_infostate_get_policy, float prob_cut_threshold)
Definition at line 298 of file expected_returns.cc.
{
  if (use_infostate_get_policy) {
    return ExpectedReturnsImpl(
        state,
        [&policies](Player player, const std::string& info_state) {
          return policies[player]->GetStatePolicy(info_state);
        },
        depth_limit,
        prob_cut_threshold);
  } else {
    return ExpectedReturnsImpl(
        state,
        [&policies](Player player, const State& state) {
          return policies[player]->GetStatePolicy(state, player);
        },
        depth_limit,
        prob_cut_threshold);
  }
}
References player, and state.
Referenced by CCEDist(), CEDist(), define_julia_module(), ExpectedValues(), ExtensiveToMatrixGame(), open_spiel::ExtensiveToTensorGame(), open_spiel::init_pyspiel_policy(), NashConv(), and open_spiel::algorithms::TabularBestResponseMDP::NashConv().
ExpectedReturnsOfDeterministicPoliciesFromSeeds() [1/2]
std::vector< double > open_spiel::algorithms::ExpectedReturnsOfDeterministicPoliciesFromSeeds (const State & state, const std::vector< int > & policy_seeds)
Definition at line 346 of file expected_returns.cc.
{
  const std::vector<const Policy*>& policies = {};
  SPIEL_CHECK_EQ(policy_seeds.size(), state.NumPlayers());
  return ExpectedReturnsOfDeterministicPoliciesFromSeedsImpl(
      state, policy_seeds, policies);
}
References SPIEL_CHECK_EQ, and state.
ExpectedReturnsOfDeterministicPoliciesFromSeeds() [2/2]
std::vector< double > open_spiel::algorithms::ExpectedReturnsOfDeterministicPoliciesFromSeeds (const State & state, const std::vector< int > & policy_seeds, const std::vector< const Policy * > & policies)
Definition at line 354 of file expected_returns.cc.
{
  SPIEL_CHECK_EQ(policy_seeds.size(), state.NumPlayers());
  return ExpectedReturnsOfDeterministicPoliciesFromSeedsImpl(
      state, policy_seeds, policies);
}
References SPIEL_CHECK_EQ, and state.
ExpectedValues() [1/2]
std::vector< double > open_spiel::algorithms::ExpectedValues (const Game & game, const CorrelationDevice & mu)
Definition at line 128 of file corr_dist.cc.
{
  CheckCorrelationDeviceProbDist(mu);
  std::vector<double> values(game.NumPlayers(), 0);
  for (const std::pair<double, TabularPolicy>& item : mu) {
    std::vector<double> item_values =
        ExpectedReturns(*game.NewInitialState(), item.second, -1, false);
    for (Player p = 0; p < game.NumPlayers(); ++p) {
      values[p] += item.first * item_values[p];
    }
  }
  return values;
}
References ExpectedReturns(), and values.
Referenced by ExpectedValues().
ExpectedValues() [2/2]
std::vector< double > open_spiel::algorithms::ExpectedValues (const Game & game, const NormalFormCorrelationDevice & mu)
Definition at line 142 of file corr_dist.cc.
{
  if (game.GetType().information == GameType::Information::kOneShot) {
    std::shared_ptr<const Game> actual_game = ConvertToTurnBased(game);
    CorrelationDevice converted_mu = ConvertCorrelationDevice(*actual_game, mu);
    return ExpectedValues(*actual_game, converted_mu);
  } else {
    SPIEL_CHECK_EQ(game.GetType().dynamics, GameType::Dynamics::kSequential);
    CorrelationDevice converted_mu = ConvertCorrelationDevice(game, mu);
    return ExpectedValues(game, converted_mu);
  }
}
References open_spiel::ConvertToTurnBased(), ExpectedValues(), open_spiel::GameType::kOneShot, open_spiel::GameType::kSequential, and SPIEL_CHECK_EQ.
ExpectiminimaxSearch()
std::pair< double, Action > open_spiel::algorithms::ExpectiminimaxSearch (const Game & game, const State * state, std::function< double(const State &)> value_function, int depth_limit, Player maximizing_player)
Definition at line 258 of file minimax.cc.
{
  SPIEL_CHECK_LE(game.NumPlayers(), 2);
  GameType game_info = game.GetType();
  SPIEL_CHECK_EQ(game_info.chance_mode,
                 GameType::ChanceMode::kExplicitStochastic);
  SPIEL_CHECK_EQ(game_info.information,
                 GameType::Information::kPerfectInformation);
  SPIEL_CHECK_EQ(game_info.dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(game_info.utility, GameType::Utility::kZeroSum);
  SPIEL_CHECK_EQ(game_info.reward_model, GameType::RewardModel::kTerminal);
  std::unique_ptr<State> search_root;
  if (state == nullptr) {
    search_root = game.NewInitialState();
  } else {
    search_root = state->Clone();
  }
  if (maximizing_player == kInvalidPlayer) {
    SPIEL_CHECK_FALSE(search_root->IsChanceNode());
    maximizing_player = search_root->CurrentPlayer();
  }
  Action best_action = kInvalidAction;
  double value =
      _expectiminimax(search_root.get(), /*depth=*/depth_limit, value_function,
                      maximizing_player, &best_action);
  return {value, best_action};
}
References open_spiel::GameType::chance_mode, open_spiel::GameType::dynamics, open_spiel::GameType::information, open_spiel::GameType::kExplicitStochastic, open_spiel::kInvalidAction, open_spiel::kInvalidPlayer, open_spiel::GameType::kPerfectInformation, open_spiel::GameType::kSequential, open_spiel::GameType::kTerminal, open_spiel::GameType::kZeroSum, open_spiel::GameType::reward_model, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_LE, state, open_spiel::GameType::utility, and value.
Exploitability() [1/2]
double open_spiel::algorithms::Exploitability (const Game & game, const Policy & policy)
Definition at line 30 of file tabular_exploitability.cc.
{
  GameType game_type = game.GetType();
  if (game_type.dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError("The game must be turn-based.");
  }
  if (game_type.utility != GameType::Utility::kZeroSum &&
      game_type.utility != GameType::Utility::kConstantSum) {
    SpielFatalError("The game must have zero- or constant-sum utility.");
  }
  std::unique_ptr<State> root = game.NewInitialState();
  double nash_conv = 0;
  for (auto i = Player{0}; i < game.NumPlayers(); ++i) {
    TabularBestResponse best_response(game, i, &policy);
    nash_conv += best_response.Value(*root);
  }
  return (nash_conv - *game.UtilitySum()) / game.NumPlayers();
}
References open_spiel::GameType::dynamics, i, open_spiel::GameType::kConstantSum, open_spiel::GameType::kSequential, open_spiel::GameType::kZeroSum, open_spiel::SpielFatalError(), and open_spiel::GameType::utility.
Referenced by define_julia_module(), Exploitability(), and main().
Exploitability() [2/2]
double open_spiel::algorithms::Exploitability (const Game & game, const std::unordered_map< std::string, ActionsAndProbs > & policy)
Definition at line 49 of file tabular_exploitability.cc.
{
  TabularPolicy tabular_policy(policy);
  return Exploitability(game, tabular_policy);
}
References Exploitability().
ExtensiveToMatrixGame()
std::shared_ptr< const matrix_game::MatrixGame > open_spiel::algorithms::ExtensiveToMatrixGame (const Game & game)
Definition at line 94 of file matrix_game_utils.cc.
{
  SPIEL_CHECK_EQ(game.NumPlayers(), 2);
  std::vector<std::string> row_names;
  std::vector<std::string> col_names;
  std::vector<std::vector<double>> row_player_utils;
  std::vector<std::vector<double>> col_player_utils;
  GameType type = game.GetType();
  std::vector<DeterministicTabularPolicy> policies = {
      DeterministicTabularPolicy(game, 0), DeterministicTabularPolicy(game, 1)};
  bool first_row = true;
  do {
    policies[1].ResetDefaultPolicy();
    row_names.push_back(policies[0].ToString(" --- "));
    std::vector<double> row_utils;
    std::vector<double> col_utils;
    do {
      if (first_row) {
        col_names.push_back(policies[1].ToString(" --- "));
      }
      std::unique_ptr<State> state = game.NewInitialState();
      std::vector<double> returns =
          ExpectedReturns(*state, {&policies[0], &policies[1]}, -1);
      row_utils.push_back(returns[0]);
      col_utils.push_back(returns[1]);
    } while (policies[1].NextPolicy());
    first_row = false;
    row_player_utils.push_back(row_utils);
    col_player_utils.push_back(col_utils);
  } while (policies[0].NextPolicy());
  return matrix_game::CreateMatrixGame(type.short_name, type.long_name,
                                       row_names, col_names, row_player_utils,
                                       col_player_utils);
}
References open_spiel::matrix_game::CreateMatrixGame(), ExpectedReturns(), open_spiel::GameType::long_name, open_spiel::algorithms::DeterministicTabularPolicy::ResetDefaultPolicy(), open_spiel::GameType::short_name, SPIEL_CHECK_EQ, state, and ToString().
Referenced by define_julia_module().
GetAllHistories()
std::vector< std::unique_ptr< State > > open_spiel::algorithms::GetAllHistories (const Game & game, int depth_limit, bool include_terminals, bool include_chance_states)
Definition at line 57 of file get_all_histories.cc.
{
  // Get the root state.
  std::unique_ptr<State> state = game.NewInitialState();
  std::vector<std::unique_ptr<State>> all_histories;
  // Then, do a recursive tree walk to fill up the vector.
  GetSubgameHistories(state.get(), &all_histories, depth_limit, 0,
                      include_terminals, include_chance_states);
  if (all_histories.empty()) {
    SpielFatalError("GetSubgameHistories returned 0 histories!");
  }
  return all_histories;
}
References open_spiel::SpielFatalError(), and state.
Referenced by main().
GetAllInformationStates()
std::vector< std::vector< std::string > > open_spiel::algorithms::GetAllInformationStates (const Game & game, int depth_limit)
Definition at line 53 of file get_all_infostates.cc.
{
  // Get the root state.
  std::unique_ptr<State> state = game.NewInitialState();
  std::vector<std::vector<std::string>> all_infostates(game.NumPlayers());
  // Then, do a recursive tree walk to fill up the vector.
  GetSubgameInformationStates(state.get(), &all_infostates, depth_limit, 0);
  // Remove duplicates by sorting the info states and calling std::unique.
  for (Player p = 0; p < all_infostates.size(); ++p) {
    absl::c_sort(all_infostates[p]);
    auto last = std::unique(all_infostates[p].begin(), all_infostates[p].end());
    all_infostates[p].erase(last, all_infostates[p].end());
  }
  return all_infostates;
}
References begin, absl::c_sort(), end, and state.
Referenced by open_spiel::algorithms::CEGame::CEGame().
GetAllInfoSets()
absl::flat_hash_map< std::string, std::vector< std::pair< HistoryNode *, double > > > open_spiel::algorithms::GetAllInfoSets (std::unique_ptr< State > state, Player best_responder, const Policy * policy, HistoryTree * tree)
Definition at line 223 of file history_tree.cc.
{
  absl::flat_hash_map<std::string, std::vector<std::pair<HistoryNode*, double>>>
      infosets;
  // We only need decision nodes, as there's no decision to be made at chance
  // nodes (we randomly sample from the different outcomes there).
  std::vector<std::pair<std::unique_ptr<State>, double>> states_and_probs =
      DecisionNodes(*state, best_responder, policy);
  infosets.reserve(states_and_probs.size());
  for (const auto& [state, prob] : states_and_probs) {
    // We look at each decision from the perspective of the best_responder.
    std::string infostate = state->InformationStateString(best_responder);
    infosets[infostate].push_back({tree->GetByHistory(*state), prob});
  }
  return infosets;
}
References DecisionNodes(), open_spiel::algorithms::HistoryTree::GetByHistory(), and state.
Referenced by open_spiel::algorithms::TabularBestResponse::SetPolicy().
GetAllStates()
std::map< std::string, std::unique_ptr< State > > open_spiel::algorithms::GetAllStates (const Game & game, int depth_limit, bool include_terminals, bool include_chance_states, bool stop_at_duplicates)
Definition at line 73 of file get_all_states.cc.
{
  // Get the root state.
  std::unique_ptr<State> state = game.NewInitialState();
  std::map<std::string, std::unique_ptr<State>> all_states;
  // Then, do a recursive tree walk to fill up the map.
  GetSubgameStates(state.get(), &all_states, depth_limit, 0, include_terminals,
                   include_chance_states, stop_at_duplicates);
  if (all_states.empty()) {
    SpielFatalError("GetSubgameStates returned 0 states!");
  }
  return all_states;
}
References open_spiel::SpielFatalError(), and state.
Referenced by open_spiel::coin_game::GetAllStatesTest(), main(), PolicyIteration(), and ValueIteration().
GetLegalActionsMap()
std::unordered_map< std::string, std::vector< Action > > open_spiel::algorithms::GetLegalActionsMap (const Game & game, int depth_limit, Player player)
Definition at line 69 of file get_legal_actions_map.cc.
{
  std::unordered_map<std::string, std::vector<Action>> map;
  std::unique_ptr<State> initial_state = game.NewInitialState();
  FillMap(*initial_state, &map, depth_limit, 0, player);
  return map;
}
References player.
Referenced by NumDeterministicPolicies().
GetStateDistribution()
HistoryDistribution open_spiel::algorithms::GetStateDistribution (const State & state, const Policy & opponent_policy)
Definition at line 142 of file state_distribution.cc.
{
  std::shared_ptr<const Game> game = state.GetGame();
  GameType game_type = game->GetType();
  if (game_type.information == GameType::Information::kPerfectInformation) {
    HistoryDistribution dist;
    // We can't use brace initialization here as it triggers the copy ctor.
    dist.first.push_back(state.Clone());
    dist.second.push_back(1.);
    return dist;
  }
  SPIEL_CHECK_EQ(game_type.information,
                 GameType::Information::kImperfectInformation);
  SPIEL_CHECK_EQ(game_type.dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_NE(game_type.chance_mode,
                 GameType::ChanceMode::kSampledStochastic);
  SPIEL_CHECK_FALSE(state.IsChanceNode());
  SPIEL_CHECK_FALSE(state.IsTerminal());
  Player player = state.CurrentPlayer();
  std::string info_state_string = state.InformationStateString();
  // Generate the (info state, action) map for the current player using
  // the state's history.
  absl::btree_map<std::string, Action> infostate_action_map;
  std::vector<Action> history = state.History();
  std::unique_ptr<State> tmp_state = game->NewInitialState();
  for (Action action : history) {
    if (tmp_state->CurrentPlayer() == player) {
      infostate_action_map[tmp_state->InformationStateString()] = action;
    }
    tmp_state->ApplyAction(action);
  }
  // Add the current one to this list with an invalid action so that the
  // information state is included.
  infostate_action_map[info_state_string] = kInvalidAction;
  // Should get to the exact same state by re-applying the history.
  SPIEL_CHECK_EQ(tmp_state->ToString(), state.ToString());
  // Now, do a breadth-first search of all the candidate histories, removing
  // them whenever their (infostate, action) is not contained in the map above.
  // The search finishes when all the information states of the states in
  // the list have been found. We use two lists: final_states contains the ones
  // that have been found, while states are the current candidates.
  std::vector<std::unique_ptr<State>> final_states;
  std::vector<double> final_probs;
  std::vector<std::unique_ptr<State>> states;
  std::vector<double> probs;
  states.push_back(game->NewInitialState());
  probs.push_back(1.0);
  while (!states.empty()) {
    for (int idx = 0; idx < states.size();) {
      if (states[idx]->IsTerminal()) {
        // Terminal cannot be a valid history in an information state, so stop
        // considering this line.
      } else if (states[idx]->IsChanceNode()) {
        // At chance nodes, just add all the children and delete the state.
        for (std::pair<Action, double> action_and_prob :
             states[idx]->ChanceOutcomes()) {
          states.push_back(states[idx]->Child(action_and_prob.first));
          probs.push_back(probs[idx] * action_and_prob.second);
        }
      } else if (states[idx]->CurrentPlayer() != player) {
        // At opponent nodes, similar to chance nodes but get the probability
        // from the policy instead.
        std::string opp_infostate_str = states[idx]->InformationStateString();
        ActionsAndProbs state_policy =
            opponent_policy.GetStatePolicy(*states[idx]);
        for (Action action : states[idx]->LegalActions()) {
          double action_prob = GetProb(state_policy, action);
          states.push_back(states[idx]->Child(action));
          probs.push_back(probs[idx] * action_prob);
        }
      } else if (states[idx]->CurrentPlayer() == player) {
        std::string my_infostate_str = states[idx]->InformationStateString();
        // First check if this state is in the target information state. If
        // add it to the final set and don't check for expansion.
        if (my_infostate_str == info_state_string) {
          final_states.push_back(states[idx]->Clone());
          final_probs.push_back(probs[idx]);
        } else {
          // Check for expansion of this candidate. To expand this candidate,
          // the (infostate, action) pair must be contained in the map.
          auto iter = infostate_action_map.find(my_infostate_str);
          if (iter != infostate_action_map.end() && iter->second) {
            states.push_back(states[idx]->Child(iter->second));
            probs.push_back(probs[idx]);
          }
        }
      } else {
        SpielFatalError(
            absl::StrCat("Unknown player: ", states[idx]->CurrentPlayer()));
      }
      // Delete entries at the index i. Rather than call erase, which would
      // shift everything, simply swap with the last element and call
      // pop_back(), which can be done in constant time.
      std::swap(states[idx], states.back());
      std::swap(probs[idx], probs.back());
      states.pop_back();
      probs.pop_back();
      // Do not increment the counter index here because the current one points
      // to a valid state that was just expanded.
    }
  }
  // Now normalize the probs
  Normalize(absl::MakeSpan(final_probs));
  HistoryDistribution dist = {std::move(final_states), std::move(final_probs)};
  // Note: We do not call CheckBeliefs here as the beliefs are _wrong_ until we
  // perform the filter step.
  return dist;
}
References action, open_spiel::GameType::chance_mode, open_spiel::GameType::dynamics, open_spiel::GetProb(), open_spiel::Policy::GetStatePolicy(), open_spiel::GameType::information, open_spiel::GameType::kImperfectInformation, open_spiel::kInvalidAction, open_spiel::GameType::kPerfectInformation, open_spiel::GameType::kSampledStochastic, open_spiel::GameType::kSequential, absl::MakeSpan(), open_spiel::Normalize(), player, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_NE, open_spiel::SpielFatalError(), state, and absl::StrCat().
Referenced by UpdateIncrementalStateDistribution().
GetSuccessorsWithProbs()
ActionsAndProbs open_spiel::algorithms::GetSuccessorsWithProbs (const State & state, Player best_responder, const Policy * policy)
Definition at line 160 of file history_tree.cc.
{
  if (state.CurrentPlayer() == best_responder) {
    ActionsAndProbs state_policy;
    for (const auto& legal_action : state.LegalActions()) {
      // Counterfactual reach probabilities exclude the player's
      // actions, hence return probability 1.0 for every action.
      state_policy.push_back({legal_action, 1.});
    }
    return state_policy;
  } else if (state.IsChanceNode()) {
    return state.ChanceOutcomes();
  } else {
    // Finally, we look at the policy we are finding a best response to, and
    // get our probabilities from there.
    auto state_policy = policy->GetStatePolicy(state);
    if (state_policy.empty()) {
      SpielFatalError(state.InformationStateString() + " not found in policy.");
    }
    return state_policy;
  }
}
References open_spiel::SpielFatalError(), and state.
Referenced by DecisionNodes().
IsPositiveProbDistribution()
bool open_spiel::algorithms::IsPositiveProbDistribution (const ActionsAndProbs & probs)
Definition at line 40 of file oos.cc.
{
  double sum_probs = 0;
  for (const auto& [action, prob] : probs) {
    if (prob <= 0) return false;
    if (prob > 1) return false;
    sum_probs += prob;
  }
  return abs(sum_probs - 1.0) < 1e-10;
}
References action.
Referenced by open_spiel::algorithms::OOSAlgorithm::SelectAction().
IsValidProbDistribution()
bool open_spiel::algorithms::IsValidProbDistribution (const ActionsAndProbs & probs)
Definition at line 30 of file oos.cc.
{
  double sum_probs = 0;
  for (const auto& [action, prob] : probs) {
    if (prob < 0) return false;
    if (prob > 1) return false;
    sum_probs += prob;
  }
  return abs(sum_probs - 1.0) < 1e-10;
}
References action.
Referenced by open_spiel::algorithms::OOSAlgorithm::SelectAction().
IsValidSfStrategy()
bool open_spiel::algorithms::IsValidSfStrategy (const SfStrategy & strategy)
Definition at line 722 of file infostate_tree.cc.
{
  return CheckSum(strategy, strategy.tree()->empty_sequence(), 1.);
}
References CheckSum(), open_spiel::algorithms::InfostateTree::empty_sequence(), and open_spiel::algorithms::internal::TreeVector< T, Id >::tree().
Referenced by open_spiel::algorithms::InfostateTree::BestResponse().
LoadMatrixGame()
std::shared_ptr< const matrix_game::MatrixGame > open_spiel::algorithms::LoadMatrixGame (const std::string & name)
Definition at line 29 of file matrix_game_utils.cc.
{
  std::shared_ptr<const Game> game = LoadGame(name);
  // Make sure it is indeed a matrix game.
  const MatrixGame* matrix_game = dynamic_cast<const MatrixGame*>(game.get());
  if (matrix_game == nullptr) {
    // If it is not already a matrix game, check if it is a 2-player NFG.
    // If so, convert it.
    const NormalFormGame* nfg = dynamic_cast<const NormalFormGame*>(game.get());
    if (nfg != nullptr && nfg->NumPlayers() == 2) {
      return AsMatrixGame(nfg);
    } else {
      SpielFatalError(absl::StrCat("Cannot load ", name, " as a matrix game."));
    }
  }
  return std::static_pointer_cast<const MatrixGame>(game);
}
References AsMatrixGame(), open_spiel::LoadGame(), name, open_spiel::Game::NumPlayers(), open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by define_julia_module().
LoadTensorGame()
std::shared_ptr< const tensor_game::TensorGame > open_spiel::algorithms::LoadTensorGame (const std::string & name)
Definition at line 26 of file tensor_game_utils.cc.
{
  std::shared_ptr<const Game> game = LoadGame(name);
  // Make sure it is indeed a tensor game.
  const TensorGame* tensor_game = dynamic_cast<const TensorGame*>(game.get());
  if (tensor_game == nullptr) {
    // If it is not already a tensor game, check if it is an NFG.
    // If so, convert it.
    const NormalFormGame* nfg = dynamic_cast<const NormalFormGame*>(game.get());
    if (nfg != nullptr) {
      return AsTensorGame(nfg);
    } else {
      SpielFatalError(absl::StrCat("Cannot load ", name, " as a tensor game."));
    }
  }
  return std::static_pointer_cast<const TensorGame>(game);
}
References AsTensorGame(), open_spiel::LoadGame(), name, open_spiel::SpielFatalError(), and absl::StrCat().
MakeInfostateTree() [1/4]
std::shared_ptr< InfostateTree > open_spiel::algorithms::MakeInfostateTree (const Game & game, Player acting_player, int max_move_limit = 1000)
Definition at line 410 of file infostate_tree.cc.
{
  // Uses new instead of make_shared, because shared_ptr is not a friend and
  // can't call private constructors.
  return std::shared_ptr<InfostateTree>(new InfostateTree(
      {game.NewInitialState().get()}, /*chance_reach_probs=*/{1.},
      game.MakeObserver(kInfoStateObsType, {}), acting_player, max_move_limit));
}
Referenced by MakeInfostateTree(), and open_spiel::algorithms::ortools::SequenceFormLpSpecification::SequenceFormLpSpecification().
MakeInfostateTree() [2/4]
std::shared_ptr< InfostateTree > open_spiel::algorithms::MakeInfostateTree (const std::vector< const InfostateNode * > & start_nodes, int max_move_ahead_limit = 1000)
Definition at line 427 of file infostate_tree.cc.
{
  SPIEL_CHECK_FALSE(start_nodes.empty());
  const InfostateNode* some_node = start_nodes[0];
  const InfostateTree& originating_tree = some_node->tree();
  SPIEL_DCHECK_TRUE([&]() {
    for (const InfostateNode* node : start_nodes) {
      if (!node) return false;
      if (!node->is_leaf_node()) return false;
      if (node->depth() != some_node->depth()) return false;
      if (&node->tree() != &originating_tree) return false;
    }
    return true;
  }());
  // We reserve a larger number of states, as infostate nodes typically contain
  // a large number of States. (8 is an arbitrary choice though).
  std::vector<const State*> start_states;
  start_states.reserve(start_nodes.size() * 8);
  std::vector<double> chance_reach_probs;
  chance_reach_probs.reserve(start_nodes.size() * 8);
  for (const InfostateNode* node : start_nodes) {
    for (int i = 0; i < node->corresponding_states_size(); ++i) {
      start_states.push_back(node->corresponding_states()[i].get());
      chance_reach_probs.push_back(node->corresponding_chance_reach_probs()[i]);
    }
  }
  // Uses new instead of make_shared, because shared_ptr is not a friend and
  // can't call private constructors.
  return std::shared_ptr<InfostateTree>(new InfostateTree(
      start_states, chance_reach_probs, originating_tree.infostate_observer_,
      originating_tree.acting_player_, max_move_ahead_limit));
}
MakeInfostateTree() [3/4]
std::shared_ptr< InfostateTree > open_spiel::algorithms::MakeInfostateTree (const std::vector< const State * > & start_states, const std::vector< double > & chance_reach_probs, std::shared_ptr< Observer > infostate_observer, Player acting_player, int max_move_ahead_limit = 1000)
Definition at line 464 of file infostate_tree.cc.
{
  return std::shared_ptr<InfostateTree>(
      new InfostateTree(start_states, chance_reach_probs, infostate_observer,
                        acting_player, max_move_ahead_limit));
}
MakeInfostateTree() [4/4]
std::shared_ptr< InfostateTree > open_spiel::algorithms::MakeInfostateTree (const std::vector< InfostateNode * > & start_nodes, int max_move_ahead_limit)
Definition at line 420 of file infostate_tree.cc.
{
  std::vector<const InfostateNode*> const_nodes(start_nodes.begin(),
                                                start_nodes.end());
  return MakeInfostateTree(const_nodes, max_move_ahead_limit);
}
References MakeInfostateTree().
MaxNSearch()
std::pair< std::vector< double >, Action > open_spiel::algorithms::MaxNSearch (const Game & game, const State * state, std::function< double(const State &, Player player)> value_function, int depth_limit)
Definition at line 92 of file maxn.cc.
                     {
  GameType game_info = game.GetType();
  SPIEL_CHECK_TRUE(
      game_info.chance_mode == GameType::ChanceMode::kDeterministic ||
      game_info.chance_mode == GameType::ChanceMode::kExplicitStochastic);
  // Do not check perfect information. Used by PIMC.
  SPIEL_CHECK_EQ(game_info.dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(game_info.reward_model, GameType::RewardModel::kTerminal);
  std::unique_ptr<State> search_root;
  if (state == nullptr) {
    search_root = game.NewInitialState();
  } else {
    search_root = state->Clone();
  }
  SPIEL_CHECK_FALSE(search_root->IsChanceNode());
  Action best_action = kInvalidAction;
  std::vector<double> values = _maxn(search_root.get(), /*depth=*/depth_limit,
                                     value_function, &best_action);
  return {values, best_action};
}
References open_spiel::GameType::chance_mode, open_spiel::GameType::dynamics, open_spiel::GameType::kDeterministic, open_spiel::GameType::kExplicitStochastic, open_spiel::kInvalidAction, open_spiel::GameType::kSequential, open_spiel::GameType::kTerminal, open_spiel::GameType::reward_model, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_TRUE, state, and values.
MemoryUsedMb()
int open_spiel::algorithms::MemoryUsedMb (int nodes)
Definition at line 39 of file mcts.cc.
{
  return nodes * sizeof(SearchNode) / (1 << 20);
}
Referenced by open_spiel::algorithms::MCTSBot::MCTSearch(), and open_spiel::algorithms::MCTSBot::Step().
NashConv() [1/3]
double open_spiel::algorithms::NashConv (const Game & game, const Policy & policy)
Definition at line 56 of file tabular_exploitability.cc.
{
  return NashConv(game, policy, false);
}
References NashConv().
Referenced by AFCCEDist(), AFCEDist(), define_julia_module(), EFCCEDist(), EFCEDist(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::NashConv(), NashConv(), and NashConv().
NashConv() [2/3]
double open_spiel::algorithms::NashConv (const Game & game, const Policy & policy, bool use_state_get_policy)
Definition at line 60 of file tabular_exploitability.cc.
{
  GameType game_type = game.GetType();
  if (game_type.dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError("The game must be turn-based.");
  }
  std::unique_ptr<State> root = game.NewInitialState();
  std::vector<double> best_response_values(game.NumPlayers());
  for (auto p = Player{0}; p < game.NumPlayers(); ++p) {
    TabularBestResponse best_response(game, p, &policy);
    best_response_values[p] = best_response.Value(*root);
  }
  std::vector<double> on_policy_values =
      ExpectedReturns(*root, policy, -1, !use_state_get_policy);
  SPIEL_CHECK_EQ(best_response_values.size(), on_policy_values.size());
  double nash_conv = 0;
  for (auto p = Player{0}; p < game.NumPlayers(); ++p) {
    double deviation_incentive = best_response_values[p] - on_policy_values[p];
    if (deviation_incentive < -FloatingPointDefaultTolerance()) {
      SpielFatalError(
          absl::StrCat("Negative Nash deviation incentive for player ", p, ": ",
                       deviation_incentive, ". Does you game have imperfect ",
                       "recall, or does State::ToString() not distinguish ",
                       "between unique states?"));
    }
    nash_conv += deviation_incentive;
  }
  return nash_conv;
}
References open_spiel::GameType::dynamics, ExpectedReturns(), open_spiel::FloatingPointDefaultTolerance(), open_spiel::GameType::kSequential, SPIEL_CHECK_EQ, open_spiel::SpielFatalError(), and absl::StrCat().
NashConv() [3/3]
double open_spiel::algorithms::NashConv (const Game & game, const std::unordered_map< std::string, ActionsAndProbs > & policy)
Definition at line 91 of file tabular_exploitability.cc.
{
  TabularPolicy tabular_policy(policy);
  return NashConv(game, tabular_policy);
}
References NashConv().
NumDeterministicPolicies()
int64_t open_spiel::algorithms::NumDeterministicPolicies (const Game & game, Player player)
Definition at line 25 of file deterministic_policy.cc.
{
  int64_t num_policies = 1;
  std::unordered_map<std::string, std::vector<Action>> legal_actions_map =
      GetLegalActionsMap(game, -1, player);
  for (const auto& infostate_str_actions : legal_actions_map) {
    int64_t num_actions = infostate_str_actions.second.size();
    SPIEL_CHECK_GT(num_actions, 0);
    // Check for integer overflow.
    if (num_policies > INT64_MAX / num_actions) {
      return -1;
    }
    num_policies *= num_actions;
  }
  return num_policies;
}
References GetLegalActionsMap(), player, and SPIEL_CHECK_GT.
Referenced by open_spiel::init_pyspiel_policy().
operator<<()
std::ostream & open_spiel::algorithms::operator<< (std::ostream & os, const OnlineStats & stats)
Definition at line 221 of file oos.cc.
{
  return os << stats.ToString();
}
PartiallyDeserializeCFRSolver()
PartiallyDeserializedCFRSolver open_spiel::algorithms::PartiallyDeserializeCFRSolver (const std::string & serialized)
Definition at line 723 of file cfr.cc.
{
  // We don't copy the CFR values table section due to potential large size.
  enum Section {
    kInvalid = -1,
    kMeta = 0,
    kGame = 1,
    kSolverType = 2,
    kSolverSpecificState = 3
  };
  std::array<std::string, 4> section_strings = {"", "", "", ""};
  Section current_section = kInvalid;
  std::vector<absl::string_view> lines = absl::StrSplit(serialized, '\n');
  for (int i = 0; i < lines.size(); i++) {
    if (lines[i].length() == 0 || lines[i].at(0) == '#') {
      // Skip comments and blank lines
    } else if (lines[i] == kSerializeMetaSectionHeader) {
      SPIEL_CHECK_EQ(current_section, kInvalid);
      current_section = kMeta;
    } else if (lines[i] == kSerializeGameSectionHeader) {
      SPIEL_CHECK_EQ(current_section, kMeta);
      current_section = kGame;
    } else if (lines[i] == kSerializeSolverTypeSectionHeader) {
      SPIEL_CHECK_EQ(current_section, kGame);
      current_section = kSolverType;
    } else if (lines[i] == kSerializeSolverSpecificStateSectionHeader) {
      SPIEL_CHECK_EQ(current_section, kSolverType);
      current_section = kSolverSpecificState;
    } else if (lines[i] == kSerializeSolverValuesTableSectionHeader) {
      SPIEL_CHECK_EQ(current_section, kSolverSpecificState);
      break;
    } else {
      SPIEL_CHECK_NE(current_section, kInvalid);
      if (current_section == kSolverSpecificState) {
        absl::StrAppend(&section_strings[current_section], lines[i], "\n");
      } else {
        absl::StrAppend(&section_strings[current_section], lines[i]);
      }
    }
  }
  // We currently just ignore the meta section.
  // In order to avod copying the CFR values table data we rather split it again
  // and obtain a single string_view that can be deserialized later using the
  // DeserializeCFRInfoStateValuesTable method.
  std::pair<absl::string_view, absl::string_view> other_and_values_table_data =
      absl::StrSplit(
          serialized,
          absl::StrCat(kSerializeSolverValuesTableSectionHeader, "\n"));
  return PartiallyDeserializedCFRSolver(DeserializeGame(section_strings[kGame]),
                                        section_strings[kSolverType],
                                        section_strings[kSolverSpecificState],
                                        other_and_values_table_data.second);
}
References open_spiel::DeserializeGame(), i, kSerializeGameSectionHeader, kSerializeMetaSectionHeader, kSerializeSolverSpecificStateSectionHeader, kSerializeSolverTypeSectionHeader, kSerializeSolverValuesTableSectionHeader, SPIEL_CHECK_EQ, SPIEL_CHECK_NE, absl::StrAppend(), absl::StrCat(), and absl::StrSplit().
Referenced by DeserializeCFRBRSolver(), DeserializeCFRPlusSolver(), DeserializeCFRSolver(), DeserializeExternalSamplingMCCFRSolver(), and DeserializeOutcomeSamplingMCCFRSolver().
PolicyIteration()
absl::flat_hash_map< std::string, double > open_spiel::algorithms::PolicyIteration (const Game & game, int depth_limit, double threshold)
Definition at line 129 of file policy_iteration.cc.
{
  // Currently only supports 1-player or 2-player zero sum games
  SPIEL_CHECK_TRUE(game.NumPlayers() == 1 || game.NumPlayers() == 2);
  if (game.NumPlayers() == 2) {
    SPIEL_CHECK_EQ(game.GetType().utility, GameType::Utility::kZeroSum);
  }
  // No support for simultaneous games (needs an LP solver). And so also must
  // be a perfect information game.
  SPIEL_CHECK_EQ(game.GetType().dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(game.GetType().information,
                 GameType::Information::kPerfectInformation);
  std::map<std::string, std::unique_ptr<State>> states =
      GetAllStates(game, depth_limit, /*include_terminals=*/true,
                   /*include_chance_states=*/false);
  absl::flat_hash_map<std::string, MDPState> mdp_state_nodes;
  InitializeMaps(states, &mdp_state_nodes);
  bool policy_stable;
  do {
    // Policy evaluation done in place
    double error;
    do {
      error = 0;
      for (const auto& kv : states) {
        const std::string& key = kv.first;
        if (kv.second->IsTerminal()) continue;
        // Evaluate the state value function
        Action curr_optimal_action = mdp_state_nodes.at(key).optimal_action;
        double value = QValue(mdp_state_nodes, kv.second, curr_optimal_action);
        double* stored_value = &mdp_state_nodes.at(key).value;
        error = std::max(std::abs(*stored_value - value), error);
        *stored_value = value;
      }
    } while (error > threshold);
    // Policy improvement
    double min_utility = game.MinUtility();
    double max_utility = game.MaxUtility();
    policy_stable = true;
    for (const auto& kv : states) {
      const std::string& key = kv.first;
      if (kv.second->IsTerminal()) continue;
      Player player = kv.second->CurrentPlayer();
      // Choose the action with the highest possible action value function
      Action curr_optimal_action = GetBestAction(
          mdp_state_nodes, kv.second, player, min_utility, max_utility);
      double curr_value =
          QValue(mdp_state_nodes, kv.second, curr_optimal_action);
      double* stored_value = &mdp_state_nodes.at(key).value;
      Action* stored_optimal_action = &mdp_state_nodes.at(key).optimal_action;
      if (std::abs(*stored_value - curr_value) > threshold) {
        policy_stable = false;
        *stored_optimal_action = curr_optimal_action;
      }
    }
  } while (!policy_stable);
  absl::flat_hash_map<std::string, double> values;
  for (const auto& kv : states) {
    std::string state_string = kv.first;
    values[state_string] = mdp_state_nodes[state_string].value;
  }
  return values;
}
References GetAllStates(), key, open_spiel::GameType::kPerfectInformation, open_spiel::GameType::kSequential, open_spiel::GameType::kZeroSum, player, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, value, and values.
Referenced by main().
PrintBeliefs()
std::string open_spiel::algorithms::PrintBeliefs (const HistoryDistribution & beliefs, int player_id)
Definition at line 317 of file state_distribution.cc.
{
  const int num_states = beliefs.first.size();
  SPIEL_CHECK_EQ(num_states, beliefs.second.size());
  std::string str;
  for (int i = 0; i < num_states; ++i) {
    absl::StrAppend(
        &str,
        absl::StrFormat("(%s, %f)",
                        beliefs.first[i]->InformationStateString(player_id),
                        beliefs.second[i]));
    if (i < num_states - 1) absl::StrAppend(&str, "\n");
  }
  return str;
}
References i, SPIEL_CHECK_EQ, absl::StrAppend(), and absl::StrFormat().
RecordBatchedTrajectory() [1/3]
BatchedTrajectory open_spiel::algorithms::RecordBatchedTrajectory (const Game & game, const std::vector< TabularPolicy > & policies, const State & initial_state, const std::unordered_map< std::string, int > & state_to_index, int batch_size, bool include_full_observations, std::mt19937 * rng_ptr, int max_unroll_length)
Definition at line 113 of file trajectories.cc.
{
  SPIEL_CHECK_GT(batch_size, 0);
  if (state_to_index.empty()) SPIEL_CHECK_TRUE(include_full_observations);
  BatchedTrajectory batched_trajectory(batch_size);
  // TODO(author1): Replace this with a multi-threaded version.
  for (int i = 0; i < batch_size; ++i) {
    BatchedTrajectory trajectory =
        RecordTrajectory(game, policies, initial_state, state_to_index,
                         include_full_observations, rng_ptr);
    SPIEL_CHECK_FALSE(trajectory.rewards[0].empty());
    batched_trajectory.MoveTrajectory(i, &trajectory);
  }
  batched_trajectory.ResizeFields(max_unroll_length);
  return batched_trajectory;
}
References i, open_spiel::algorithms::BatchedTrajectory::MoveTrajectory(), RecordTrajectory(), open_spiel::algorithms::BatchedTrajectory::ResizeFields(), open_spiel::algorithms::BatchedTrajectory::rewards, SPIEL_CHECK_FALSE, SPIEL_CHECK_GT, and SPIEL_CHECK_TRUE.
Referenced by define_julia_module(), open_spiel::init_pyspiel_algorithms_trajectories(), open_spiel::algorithms::TrajectoryRecorder::RecordBatch(), RecordBatchedTrajectory(), and RecordBatchedTrajectory().
RecordBatchedTrajectory() [2/3]
BatchedTrajectory open_spiel::algorithms::RecordBatchedTrajectory (const Game & game, const std::vector< TabularPolicy > & policies, const std::unordered_map< std::string, int > & state_to_index, int batch_size, bool include_full_observations, int seed, int max_unroll_length)
Definition at line 213 of file trajectories.cc.
{
  std::mt19937 rng(seed);
  return RecordBatchedTrajectory(game, policies, state_to_index, batch_size,
                                 include_full_observations, &rng,
                                 max_unroll_length);
}
References RecordBatchedTrajectory().
RecordBatchedTrajectory() [3/3]
BatchedTrajectory open_spiel::algorithms::RecordBatchedTrajectory (const Game & game, const std::vector< TabularPolicy > & policies, const std::unordered_map< std::string, int > & state_to_index, int batch_size, bool include_full_observations, std::mt19937 * rng_ptr, int max_unroll_length)
Definition at line 201 of file trajectories.cc.
{
  if (state_to_index.empty()) SPIEL_CHECK_TRUE(include_full_observations);
  std::unique_ptr<State> state = game.NewInitialState();
  return RecordBatchedTrajectory(game, policies, *state, state_to_index,
                                 batch_size, include_full_observations, rng_ptr,
                                 max_unroll_length);
}
References RecordBatchedTrajectory(), SPIEL_CHECK_TRUE, and state.
RecordTrajectory() [1/2]
BatchedTrajectory open_spiel::algorithms::RecordTrajectory (const Game & game, const std::vector< TabularPolicy > & policies, const State & initial_state, const std::unordered_map< std::string, int > & state_to_index, bool include_full_observations, std::mt19937 * rng)
Definition at line 134 of file trajectories.cc.
{
  if (state_to_index.empty()) SPIEL_CHECK_TRUE(include_full_observations);
  BatchedTrajectory trajectory(/*batch_size=*/1);
  std::unique_ptr<open_spiel::State> state = initial_state.Clone();
  bool find_index = !state_to_index.empty();
  while (!state->IsTerminal()) {
    Action action = kInvalidAction;
    if (state->IsChanceNode()) {
      action = open_spiel::SampleAction(
                   state->ChanceOutcomes(),
                   std::uniform_real_distribution<double>(0.0, 1.0)(*rng))
                   .first;
    } else if (state->IsSimultaneousNode()) {
      open_spiel::SpielFatalError(
          "We do not support games with simultaneous actions.");
    } else {
      // Then we're at a decision node.
      trajectory.legal_actions[0].push_back(state->LegalActionsMask());
      if (find_index) {
        auto it = state_to_index.find(StateKey(game, *state));
        SPIEL_CHECK_TRUE(it != state_to_index.end());
        trajectory.state_indices[0].push_back(it->second);
      } else {
        trajectory.observations[0].push_back(state->InformationStateTensor());
      }
      ActionsAndProbs policy =
          policies.at(state->CurrentPlayer())
              .GetStatePolicy(state->InformationStateString());
      if (policy.size() > state->LegalActions().size()) {
        std::string policy_str = "";
        for (const auto& item : policy) {
          absl::StrAppend(&policy_str, "(", item.first, ",", item.second, ") ");
        }
        SpielFatalError(absl::StrCat(
            "There are more actions than legal actions from ",
            typeid(policies.at(state->CurrentPlayer())).name(),
            "\n Legal actions are: ", absl::StrJoin(state->LegalActions(), " "),
            " \n Available probabilities were:", policy_str));
      }
      std::vector<double> probs(game.NumDistinctActions(), 0.);
      for (const std::pair<Action, double>& pair : policy) {
        probs[pair.first] = pair.second;
      }
      trajectory.player_policies[0].push_back(probs);
      trajectory.player_ids[0].push_back(state->CurrentPlayer());
      action = SampleAction(policy, *rng).first;
      trajectory.actions[0].push_back(action);
    }
    SPIEL_CHECK_NE(action, kInvalidAction);
    state->ApplyAction(action);
  }
  trajectory.valid[0] = std::vector<int>(trajectory.actions[0].size(), true);
  trajectory.rewards[0] = state->Returns();
  trajectory.next_is_terminal[0].resize(trajectory.actions[0].size(), false);
  trajectory.next_is_terminal[0][trajectory.next_is_terminal[0].size() - 1] =
      true;
  // We arbitrarily set max_trajectory_length based on the actions field. All
  // the fields should have the same length.
  trajectory.max_trajectory_length = trajectory.actions[0].size();
  return trajectory;
}
References action, open_spiel::algorithms::BatchedTrajectory::actions, open_spiel::State::Clone(), open_spiel::kInvalidAction, open_spiel::algorithms::BatchedTrajectory::legal_actions, open_spiel::algorithms::BatchedTrajectory::max_trajectory_length, open_spiel::algorithms::BatchedTrajectory::next_is_terminal, open_spiel::algorithms::BatchedTrajectory::observations, pair, open_spiel::algorithms::BatchedTrajectory::player_ids, open_spiel::algorithms::BatchedTrajectory::player_policies, open_spiel::algorithms::BatchedTrajectory::rewards, open_spiel::SampleAction(), SPIEL_CHECK_NE, SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), state, open_spiel::algorithms::BatchedTrajectory::state_indices, absl::StrAppend(), absl::StrCat(), absl::StrJoin(), and open_spiel::algorithms::BatchedTrajectory::valid.
Referenced by RecordBatchedTrajectory(), and RecordTrajectory().
RecordTrajectory() [2/2]
BatchedTrajectory open_spiel::algorithms::RecordTrajectory (const Game & game, const std::vector< TabularPolicy > & policies, const std::unordered_map< std::string, int > & state_to_index, bool include_full_observations, std::mt19937 * rng_ptr)
Definition at line 223 of file trajectories.cc.
{
  if (state_to_index.empty()) SPIEL_CHECK_TRUE(include_full_observations);
  std::unique_ptr<State> state = game.NewInitialState();
  return RecordTrajectory(game, policies, *state, state_to_index,
                          include_full_observations, rng_ptr);
}
References RecordTrajectory(), SPIEL_CHECK_TRUE, and state.
SampledDeterminizeCorrDev()
CorrelationDevice open_spiel::algorithms::SampledDeterminizeCorrDev (const CorrelationDevice & corr_dev, int num_samples_per_policy)
Definition at line 109 of file corr_dev_builder.cc.
{
  CorrDevBuilder cdb;
  for (const std::pair<double, TabularPolicy>& item : corr_dev) {
    cdb.AddSampledJointPolicy(item.second, num_samples_per_policy, item.first);
  }
  return cdb.GetCorrelationDevice();
}
References open_spiel::algorithms::CorrDevBuilder::AddSampledJointPolicy(), and open_spiel::algorithms::CorrDevBuilder::GetCorrelationDevice().
Referenced by open_spiel::init_pyspiel_algorithms_corr_dist().
SerializeCFRInfoStateValuesTable()
void open_spiel::algorithms::SerializeCFRInfoStateValuesTable (const CFRInfoStateValuesTable & info_states, std::string * result, int double_precision, std::string delimiter)
Definition at line 639 of file cfr.cc.
{
  if (delimiter == "," || delimiter == ";") {
    // The two delimiters are used for de/serialization of CFRInfoStateValues
    SpielFatalError(
        "Please select a different delimiter,"
        "invalid values are \",\" and \";\".");
  }
  if (info_states.empty()) return;
  for (auto const& [info_state, values] : info_states) {
    if (info_state.find(delimiter) != std::string::npos) {
      SpielFatalError(absl::StrCat(
          "Info state contains delimiter \"", delimiter,
          "\", please fix the info state or select a different delimiter."));
    }
    absl::StrAppend(result, info_state, delimiter,
                    values.Serialize(double_precision), delimiter);
  }
  // Remove the trailing delimiter
  result->erase(result->length() - delimiter.length());
}
References open_spiel::SpielFatalError(), absl::StrAppend(), absl::StrCat(), and values.
Referenced by open_spiel::algorithms::CFRSolverBase::Serialize(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
ToString()
std::string open_spiel::algorithms::ToString (const CorrelationDevice & corr_dev)
Definition at line 118 of file corr_dist.cc.
{
  std::string corr_dev_str;
  for (const auto& prob_and_policy : corr_dev) {
    absl::StrAppend(&corr_dev_str, "Prob: ", prob_and_policy.first, "\n");
    absl::StrAppend(&corr_dev_str, prob_and_policy.second.ToStringSorted(),
                    "\n");
  }
  return corr_dev_str;
}
References absl::StrAppend().
Referenced by ExtensiveToMatrixGame().
UniformCorrelationDevice()
CorrelationDevice open_spiel::algorithms::UniformCorrelationDevice (std::vector< TabularPolicy > & policies)
Definition at line 107 of file corr_dist.cc.
{
  CorrelationDevice mu;
  mu.reserve(policies.size());
  for (const TabularPolicy& policy : policies) {
    mu.push_back({1.0 / policies.size(), policy});
  }
  return mu;
}
Referenced by open_spiel::init_pyspiel_algorithms_corr_dist().
UpdateIncrementalStateDistribution()
std::unique_ptr< HistoryDistribution > open_spiel::algorithms::UpdateIncrementalStateDistribution (const State & state, const Policy & opponent_policy, int player_id, std::unique_ptr< HistoryDistribution > previous)
Definition at line 260 of file state_distribution.cc.
{
  std::unique_ptr<HistoryDistribution> dist;
  if (previous) {
    dist = std::move(previous);
  }
  // If we don't have a previous set of beliefs, create it.
  if (!dist || dist->first.empty()) {
    // This allows for games to special case this scenario. It only works if
    // this is only called at the first decision node after chance nodes. We
    // leave it to the caller to verify this is the case.
    dist = state.GetHistoriesConsistentWithInfostate();
    // If the game didn't implement GetHistoriesConsistentWithInfostate, then
    // this is empty, otherwise, we're good.
    if (!dist || dist->first.empty()) {
      // If the previous pair is empty, then we have to do a BFS to find all
      // relevant nodes:
      dist = absl::make_unique<HistoryDistribution>(
          GetStateDistribution(state, opponent_policy));
    }
  }
  // Now, we verify that the beliefs match the current infostate.
  const std::vector<State::PlayerAction>& history = state.FullHistory();
  int belief_history_size = GetBeliefHistorySize(*dist);
  std::unique_ptr<State> new_state = state.GetGame()->NewInitialState();
  for (int i = 0; i < belief_history_size; ++i) {
    new_state->ApplyAction(history[i].action);
  }
  SPIEL_DCHECK_TRUE(CheckBeliefs(*new_state, *dist, player_id));
  while (belief_history_size < history.size()) {
    dist = AdvanceBeliefHistoryOneAction(std::move(dist),
                                         history[belief_history_size].action,
                                         player_id, opponent_policy);
    new_state->ApplyAction(history[belief_history_size].action);
    dist = FilterOutBeliefs(*new_state, std::move(dist), player_id);
    SPIEL_CHECK_FALSE(dist->first.empty());
    if (!new_state->IsChanceNode()) {
      SPIEL_DCHECK_TRUE(CheckBeliefs(*new_state, *dist, player_id));
    }
    const int new_belief_history_size = GetBeliefHistorySize(*dist);
    SPIEL_CHECK_LT(belief_history_size, new_belief_history_size);
    belief_history_size = new_belief_history_size;
  }
  SPIEL_CHECK_EQ(belief_history_size, history.size());
  SPIEL_CHECK_EQ(new_state->FullHistory(), state.FullHistory());
  dist = FilterOutBeliefs(state, std::move(dist), player_id);
  SPIEL_CHECK_FALSE(dist->first.empty());
  // We only normalize after filtering out invalid infostates.
  Normalize(absl::MakeSpan(dist->second));
  SPIEL_DCHECK_TRUE(CheckBeliefs(state, *dist, player_id));
  return dist;
}
References action, CheckBeliefs(), GetStateDistribution(), i, absl::MakeSpan(), open_spiel::Normalize(), SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_LT, SPIEL_DCHECK_TRUE, and state.
ValueIteration()
std::map< std::string, double > open_spiel::algorithms::ValueIteration (const Game & game, int depth_limit, double threshold)
Definition at line 73 of file value_iteration.cc.
{
  using state_action = std::pair<std::string, Action>;
  using state_prob = std::pair<std::string, double>;
  // Currently only supports 1-player or 2-player zero sum games
  SPIEL_CHECK_TRUE(game.NumPlayers() == 1 || game.NumPlayers() == 2);
  if (game.NumPlayers() == 2) {
    SPIEL_CHECK_EQ(game.GetType().utility, GameType::Utility::kZeroSum);
  }
  // No support for simultaneous games (needs an LP solver). And so also must
  // be a perfect information game.
  SPIEL_CHECK_EQ(game.GetType().dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(game.GetType().information,
                 GameType::Information::kPerfectInformation);
  auto states = GetAllStates(game, depth_limit, /*include_terminals=*/true,
                             /*include_chance_states=*/false,
                             /*stop_at_duplicates*/true);
  std::map<std::string, double> values;
  std::map<state_action, std::vector<state_prob>> transitions;
  InitializeMaps(states, &values, &transitions);
  double error;
  double min_utility = game.MinUtility();
  double max_utility = game.MaxUtility();
  do {
    error = 0;
    for (const auto& kv : states) {
      auto key = kv.first;
      if (kv.second->IsTerminal()) continue;
      auto player = kv.second->CurrentPlayer();
      // Initialize value to be the minimum utility if current player
      // is the maximizing player (i.e. player 0), and to maximum utility
      // if current player is the minimizing player (i.e. player 1).
      double value = (player == Player{0}) ? min_utility : max_utility;
      for (auto action : kv.second->LegalActions()) {
        auto possibilities = transitions[std::make_pair(key, action)];
        double q_value = 0;
        for (const auto& outcome : possibilities) {
          q_value += outcome.second * values[outcome.first];
        }
        // Player 0 is maximizing the value (which is w.r.t. player 0)
        // Player 1 is minimizing the value
        if (player == Player{0})
          value = std::max(value, q_value);
        else
          value = std::min(value, q_value);
      }
      double* stored_value = &values[key];
      error = std::max(std::abs(*stored_value - value), error);
      *stored_value = value;
    }
  } while (error > threshold);
  return values;
}
References action, GetAllStates(), key, open_spiel::GameType::kPerfectInformation, open_spiel::GameType::kSequential, open_spiel::GameType::kZeroSum, player, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, transitions, value, and values.
Referenced by main().
Variable Documentation
kBannedAction
double open_spiel::algorithms::kBannedAction = -0. constexpr
Definition at line 101 of file oos.cc.
Referenced by open_spiel::algorithms::TargetedPolicy::GetStatePolicy().
kDefaultBiasing
double open_spiel::algorithms::kDefaultBiasing = 0.6 constexpr
Definition at line 129 of file oos.h.
kDefaultExploration
double open_spiel::algorithms::kDefaultExploration = 0.5 constexpr
Definition at line 130 of file oos.h.
kDummyRootNodeInfostate
const char* open_spiel::algorithms::kDummyRootNodeInfostate = "(root)" constexpr
Definition at line 94 of file infostate_tree.h.
Referenced by open_spiel::algorithms::InfostateNode::has_infostate_string().
kFillerInfostate
const char* open_spiel::algorithms::kFillerInfostate = "(fill)" constexpr
Definition at line 99 of file infostate_tree.h.
Referenced by open_spiel::algorithms::InfostateNode::has_infostate_string().
kNoActionObsTargetSpecified
ActionObservationHistory* open_spiel::algorithms::kNoActionObsTargetSpecified = nullptr constexpr
Definition at line 179 of file oos.h.
Referenced by open_spiel::algorithms::TargetedPolicy::IsTargetHit(), and open_spiel::algorithms::TargetedPolicy::NoTargeting().
kNoPublicObsTargetSpecified
PublicObservationHistory* open_spiel::algorithms::kNoPublicObsTargetSpecified = nullptr constexpr
Definition at line 180 of file oos.h.
Referenced by open_spiel::algorithms::TargetedPolicy::IsTargetHit(), and open_spiel::algorithms::TargetedPolicy::NoTargeting().
kNumPlayers
const int open_spiel::algorithms::kNumPlayers = 2 constexpr
Definition at line 26 of file fsicfr.cc.
kSerializationVersion
const int open_spiel::algorithms::kSerializationVersion = 1 constexpr
Definition at line 34 of file cfr.cc.
Referenced by open_spiel::algorithms::CFRSolverBase::Serialize(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
kSerializeGameSectionHeader
const char* open_spiel::algorithms::kSerializeGameSectionHeader = "[Game]" constexpr
Definition at line 34 of file cfr.h.
Referenced by PartiallyDeserializeCFRSolver(), open_spiel::algorithms::CFRSolverBase::Serialize(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
kSerializeMetaSectionHeader
const char* open_spiel::algorithms::kSerializeMetaSectionHeader = "[Meta]" constexpr
Definition at line 33 of file cfr.h.
Referenced by PartiallyDeserializeCFRSolver(), open_spiel::algorithms::CFRSolverBase::Serialize(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
kSerializeSolverAverageTypeSectionHeader
const char* open_spiel::algorithms::kSerializeSolverAverageTypeSectionHeader constexpr
Initial value:
=
    "[SolverAverageType]"
Definition at line 35 of file external_sampling_mccfr.cc.
Referenced by DeserializeExternalSamplingMCCFRSolver(), and open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize().
kSerializeSolverDefaultPolicySectionHeader
const char * open_spiel::algorithms::kSerializeSolverDefaultPolicySectionHeader constexpr
Initial value:
=
    "[SolverDefaultPolicy]"
Definition at line 37 of file external_sampling_mccfr.cc.
Referenced by DeserializeExternalSamplingMCCFRSolver(), DeserializeOutcomeSamplingMCCFRSolver(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
kSerializeSolverEpsilonSectionHeader
const char* open_spiel::algorithms::kSerializeSolverEpsilonSectionHeader = "[SolverEpsilon]" constexpr
Definition at line 35 of file outcome_sampling_mccfr.cc.
Referenced by DeserializeOutcomeSamplingMCCFRSolver(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
kSerializeSolverRNGSectionHeader
const char * open_spiel::algorithms::kSerializeSolverRNGSectionHeader = "[SolverRNG]" constexpr
Definition at line 34 of file external_sampling_mccfr.cc.
Referenced by DeserializeExternalSamplingMCCFRSolver(), DeserializeOutcomeSamplingMCCFRSolver(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
kSerializeSolverSpecificStateSectionHeader
const char* open_spiel::algorithms::kSerializeSolverSpecificStateSectionHeader constexpr
Initial value:
=
    "[SolverSpecificState]"
Definition at line 36 of file cfr.h.
Referenced by PartiallyDeserializeCFRSolver(), open_spiel::algorithms::CFRSolverBase::Serialize(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
kSerializeSolverTypeSectionHeader
const char* open_spiel::algorithms::kSerializeSolverTypeSectionHeader = "[SolverType]" constexpr
Definition at line 35 of file cfr.h.
Referenced by PartiallyDeserializeCFRSolver(), open_spiel::algorithms::CFRSolverBase::Serialize(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
kSerializeSolverValuesTableSectionHeader
const char* open_spiel::algorithms::kSerializeSolverValuesTableSectionHeader constexpr
Initial value:
=
    "[SolverValuesTable]"
Definition at line 38 of file cfr.h.
Referenced by PartiallyDeserializeCFRSolver(), open_spiel::algorithms::CFRSolverBase::Serialize(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::Serialize(), and open_spiel::algorithms::OutcomeSamplingMCCFRSolver::Serialize().
kTieTolerance
double open_spiel::algorithms::kTieTolerance = 0.00001 constexpr
Definition at line 29 of file is_mcts.cc.
kUndefinedDecisionId
DecisionId open_spiel::algorithms::kUndefinedDecisionId = DecisionId() constexpr
Definition at line 202 of file infostate_tree.h.
Referenced by open_spiel::algorithms::InfostateTree::DecisionIdFromInfostateString().
kUndefinedLeafId
LeafId open_spiel::algorithms::kUndefinedLeafId = LeafId() constexpr
Definition at line 213 of file infostate_tree.h.
kUndefinedSequenceId
SequenceId open_spiel::algorithms::kUndefinedSequenceId = SequenceId() constexpr
Definition at line 194 of file infostate_tree.h.
kUnexpandedVisitCount
int open_spiel::algorithms::kUnexpandedVisitCount = -1 constexpr
Definition at line 30 of file is_mcts.cc.
kUnlimitedNumWorldSamples
int open_spiel::algorithms::kUnlimitedNumWorldSamples = -1 inline constexpr
Definition at line 36 of file is_mcts.h.
Referenced by open_spiel::init_pyspiel_bots().
MIN_GC_LIMIT
int open_spiel::algorithms::MIN_GC_LIMIT = 5
Definition at line 37 of file mcts.cc.
Referenced by open_spiel::algorithms::MCTSBot::MCTSearch().