open spiel: open_spiel::kriegspiel Namespace Reference
open_spiel::kriegspiel Namespace Reference
Classes
class KriegspielGame
class KriegspielObserver
class KriegspielState
struct KriegspielUmpireMessage
Enumerations
enum KriegspielCaptureType { kNoCapture = 0 , kPawn = 1 , kPiece = 2 }
enum KriegspielCheckType {
kNoCheck = 0 , kFile = 1 , kRank = 2 , kLongDiagonal = 3 ,
kShortDiagonal = 4 , kKnight = 5
}
Functions
std::string CaptureTypeToString (KriegspielCaptureType capture_type)
std::string CheckTypeToString (KriegspielCheckType check_type)
std::pair< KriegspielCheckType, KriegspielCheckType > GetCheckType (const chess::ChessBoard &board)
KriegspielUmpireMessage GetUmpireMessage (const chess::ChessBoard &chess_board, const chess::Move &move)
bool GeneratesUmpireMessage (const chess::ChessBoard &chess_board, const chess::Move &move, const KriegspielUmpireMessage &orig_msg)
Variables
constexpr int kNumPlayers = 2
constexpr double kLossUtility = -1
constexpr double kDrawUtility = 0
constexpr double kWinUtility = 1
constexpr int kNumDistinctActions = 4672
constexpr int kMaxGameLength = 17695
Enumeration Type Documentation
KriegspielCaptureType
enum open_spiel::kriegspiel::KriegspielCaptureType
Enumerator
kNoCapture
kPawn
kPiece
Definition at line 74 of file kriegspiel.h.
{ kNoCapture = 0, kPawn = 1, kPiece = 2 };
KriegspielCheckType
enum open_spiel::kriegspiel::KriegspielCheckType
Enumerator
kNoCheck
kFile
kRank
kLongDiagonal
kShortDiagonal
kKnight
Definition at line 78 of file kriegspiel.h.
{
  kNoCheck = 0,
  kFile = 1,
  kRank = 2,
  kLongDiagonal = 3,
  kShortDiagonal = 4,
  kKnight = 5
};
Function Documentation
CaptureTypeToString()
std::string open_spiel::kriegspiel::CaptureTypeToString (KriegspielCaptureType capture_type)
Definition at line 315 of file kriegspiel.cc.
{
  if (capture_type == KriegspielCaptureType::kNoCapture) {
    return "No Piece";
  }
  if (capture_type == KriegspielCaptureType::kPawn) {
    return "Pawn";
  }
  return "Piece";
}
References kNoCapture, and kPawn.
Referenced by open_spiel::kriegspiel::KriegspielUmpireMessage::ToString().
CheckTypeToString()
std::string open_spiel::kriegspiel::CheckTypeToString (KriegspielCheckType check_type)
Definition at line 325 of file kriegspiel.cc.
{
  switch (check_type) {
    case KriegspielCheckType::kFile:
      return "File";
    case KriegspielCheckType::kRank:
      return "Rank";
    case KriegspielCheckType::kLongDiagonal:
      return "Long-diagonal";
    case KriegspielCheckType::kShortDiagonal:
      return "Short-diagonal";
    case KriegspielCheckType::kKnight:
      return "Knight";
    default:
      SpielFatalError("kNoCheck does not have a string representation");
  }
}
References kFile, kKnight, kLongDiagonal, kRank, kShortDiagonal, and open_spiel::SpielFatalError().
Referenced by open_spiel::kriegspiel::KriegspielUmpireMessage::ToString().
GeneratesUmpireMessage()
bool open_spiel::kriegspiel::GeneratesUmpireMessage (const chess::ChessBoard & chess_board, const chess::Move & move, const KriegspielUmpireMessage & orig_msg)
Definition at line 462 of file kriegspiel.cc.
{
  if (!chess_board.IsMoveLegal(move)) {
    // If the move is illegal, the player is notified about it and can play
    // again
    return orig_msg.illegal;
  }
  chess::PieceType capture_type = chess_board.at(move.to).type;
  switch (capture_type) {
    case chess::PieceType::kEmpty:
      if (orig_msg.capture_type != KriegspielCaptureType::kNoCapture) {
        return false;
      }
      break;
    case chess::PieceType::kPawn:
      if (orig_msg.capture_type != KriegspielCaptureType::kPawn) {
        return false;
      }
      break;
    default:
      if (orig_msg.capture_type != KriegspielCaptureType::kPiece) {
        return false;
      }
  }
  // todo optimize when undo is optimized
  chess::ChessBoard board_copy = chess_board;
  board_copy.ApplyMove(move);
  if (orig_msg.check_types != GetCheckType(board_copy)) {
    return false;
  }
  int pawnTries = 0;
  board_copy.GenerateLegalPawnCaptures(
      [&pawnTries](const chess::Move &move) {
        pawnTries++;
        return true;
      },
      board_copy.ToPlay());
  if (orig_msg.pawn_tries != pawnTries) {
    return false;
  }
  if (orig_msg.to_move != board_copy.ToPlay()) {
    return false;
  }
  return true;
}
References open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::chess::ChessBoard::at(), open_spiel::kriegspiel::KriegspielUmpireMessage::capture_type, open_spiel::kriegspiel::KriegspielUmpireMessage::check_types, open_spiel::chess::ChessBoard::GenerateLegalPawnCaptures(), GetCheckType(), open_spiel::kriegspiel::KriegspielUmpireMessage::illegal, open_spiel::chess::ChessBoard::IsMoveLegal(), open_spiel::chess::kEmpty, kNoCapture, open_spiel::chess::kPawn, kPawn, kPiece, open_spiel::kriegspiel::KriegspielUmpireMessage::pawn_tries, open_spiel::kriegspiel::KriegspielUmpireMessage::to_move, open_spiel::chess::ChessBoard::ToPlay(), and open_spiel::chess::Piece::type.
GetCheckType()
std::pair< KriegspielCheckType, KriegspielCheckType > open_spiel::kriegspiel::GetCheckType (const chess::ChessBoard & board)
Definition at line 342 of file kriegspiel.cc.
{
  chess::Square king_sq =
      board.find(chess::Piece{board.ToPlay(), chess::PieceType::kKing});
  std::pair<KriegspielCheckType, KriegspielCheckType> check_type_pair = {
      KriegspielCheckType::kNoCheck, KriegspielCheckType::kNoCheck};
  board.GeneratePseudoLegalMoves(
      [&king_sq, &check_type_pair, &board](const chess::Move &move) {
        if (move.to != king_sq) {
          return true;
        }
        KriegspielCheckType check_type;
        if (move.piece.type == chess::PieceType::kKnight)
          check_type = KriegspielCheckType::kKnight;
        else if (move.from.x == move.to.x)
          check_type = KriegspielCheckType::kFile;
        else if (move.from.y == move.to.y)
          check_type = KriegspielCheckType::kRank;
        else if (chess::IsLongDiagonal(move.from, move.to, board.BoardSize()))
          check_type = KriegspielCheckType::kLongDiagonal;
        else
          check_type = KriegspielCheckType::kShortDiagonal;
        if (check_type_pair.first != KriegspielCheckType::kNoCheck) {
          // There cannot be more than two checks at the same time
          check_type_pair.second = check_type;
          return false;
        } else {
          check_type_pair.first = check_type;
        }
        return true;
      },
      board.ToPlay(), chess::PseudoLegalMoveSettings::kAcknowledgeEnemyPieces);
  return check_type_pair;
}
References open_spiel::chess::ChessBoard::BoardSize(), open_spiel::chess::ChessBoard::find(), open_spiel::chess::ChessBoard::GeneratePseudoLegalMoves(), open_spiel::chess::IsLongDiagonal(), open_spiel::chess::kAcknowledgeEnemyPieces, kFile, open_spiel::chess::kKing, open_spiel::chess::kKnight, kKnight, kLongDiagonal, kNoCheck, kRank, kShortDiagonal, and open_spiel::chess::ChessBoard::ToPlay().
Referenced by GeneratesUmpireMessage(), and GetUmpireMessage().
GetUmpireMessage()
KriegspielUmpireMessage open_spiel::kriegspiel::GetUmpireMessage (const chess::ChessBoard & chess_board, const chess::Move & move)
Definition at line 416 of file kriegspiel.cc.
{
  KriegspielUmpireMessage msg{};
  if (!chess_board.IsMoveLegal(move)) {
    // If the move is illegal, the player is notified about it and can play
    // again
    msg.illegal = true;
    msg.to_move = chess_board.ToPlay();
    return msg;
  }
  msg.illegal = false;
  chess::PieceType capture_type = chess_board.at(move.to).type;
  switch (capture_type) {
    case chess::PieceType::kEmpty:
      msg.capture_type = KriegspielCaptureType::kNoCapture;
      msg.square = chess::kInvalidSquare;
      break;
    case chess::PieceType::kPawn:
      msg.capture_type = KriegspielCaptureType::kPawn;
      msg.square = move.to;
      break;
    default:
      msg.capture_type = KriegspielCaptureType::kPiece;
      msg.square = move.to;
  }
  // todo optimze when undo is optimized
  chess::ChessBoard board_copy = chess_board;
  board_copy.ApplyMove(move);
  msg.check_types = GetCheckType(board_copy);
  int pawnTries = 0;
  board_copy.GenerateLegalPawnCaptures(
      [&pawnTries](const chess::Move &move) {
        pawnTries++;
        return true;
      },
      board_copy.ToPlay());
  msg.pawn_tries = pawnTries;
  msg.to_move = board_copy.ToPlay();
  return msg;
}
References open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::chess::ChessBoard::at(), open_spiel::chess::ChessBoard::GenerateLegalPawnCaptures(), GetCheckType(), open_spiel::chess::ChessBoard::IsMoveLegal(), open_spiel::chess::kEmpty, kNoCapture, open_spiel::chess::kPawn, kPawn, kPiece, open_spiel::chess::ChessBoard::ToPlay(), and open_spiel::chess::Piece::type.
Referenced by open_spiel::kriegspiel::KriegspielState::DoApplyAction().
Variable Documentation
kDrawUtility
double open_spiel::kriegspiel::kDrawUtility = 0 inline constexpr
Definition at line 63 of file kriegspiel.h.
Referenced by open_spiel::kriegspiel::KriegspielGame::UtilitySum().
kLossUtility
double open_spiel::kriegspiel::kLossUtility = -1 inline constexpr
Definition at line 62 of file kriegspiel.h.
Referenced by open_spiel::kriegspiel::KriegspielGame::MinUtility().
kMaxGameLength
int open_spiel::kriegspiel::kMaxGameLength = 17695 inline constexpr
Definition at line 72 of file kriegspiel.h.
Referenced by open_spiel::kriegspiel::KriegspielGame::MaxGameLength().
kNumDistinctActions
int open_spiel::kriegspiel::kNumDistinctActions = 4672 inline constexpr
Definition at line 67 of file kriegspiel.h.
Referenced by open_spiel::kriegspiel::KriegspielGame::NumDistinctActions().
kNumPlayers
int open_spiel::kriegspiel::kNumPlayers = 2 inline constexpr
Definition at line 61 of file kriegspiel.h.
Referenced by open_spiel::kriegspiel::KriegspielGame::NumPlayers().
kWinUtility
double open_spiel::kriegspiel::kWinUtility = 1 inline constexpr
Definition at line 64 of file kriegspiel.h.
Referenced by open_spiel::kriegspiel::KriegspielGame::MaxUtility().