open spiel: open_spiel::dynamic_routing Namespace Reference
open_spiel::dynamic_routing Namespace Reference
Classes
class DynamicRoutingData
class MeanFieldRoutingGame
class MeanFieldRoutingGameState
class Network
struct OriginDestinationDemand
struct Vehicle
Enumerations
enum class DynamicRoutingDataName { kLine , kBraess }
Functions
std::string RoadSectionFromNodes (absl::string_view origin, absl::string_view destination)
std::vector< std::string > NodesFromRoadSection (std::string road_section)
Variables
constexpr int kNoPossibleAction = 0
constexpr int kNumPlayers = 1
constexpr int kWaitingTimeNotAssigned = -1
constexpr double kDefaultTimeStepLength = 1.0
constexpr int kDefaultMaxTimeStep = 10
constexpr const char * kDefaultNetworkName = "braess"
Enumeration Type Documentation
DynamicRoutingDataName
enum class open_spiel::dynamic_routing::DynamicRoutingDataName strong
Enumerator
kLine
kBraess
Definition at line 27 of file dynamic_routing_data.h.
{ kLine, kBraess };
Function Documentation
NodesFromRoadSection()
std::vector< std::string > open_spiel::dynamic_routing::NodesFromRoadSection (std::string road_section)
Definition at line 68 of file dynamic_routing_utils.cc.
{
  return absl::StrSplit(road_section, "->");
}
References absl::StrSplit().
Referenced by open_spiel::dynamic_routing::Network::AssertValidAction(), open_spiel::dynamic_routing::Network::GetRoadSectionAsInt(), and open_spiel::dynamic_routing::MeanFieldRoutingGameState::LegalActions().
RoadSectionFromNodes()
std::string open_spiel::dynamic_routing::RoadSectionFromNodes (absl::string_view origin, absl::string_view destination)
Definition at line 63 of file dynamic_routing_utils.cc.
{
  return absl::StrCat(origin, "->", destination);
}
References absl::StrCat().
Referenced by open_spiel::dynamic_routing::Network::GetActionIdFromMovement().
Variable Documentation
kDefaultMaxTimeStep
int open_spiel::dynamic_routing::kDefaultMaxTimeStep = 10 inline constexpr
Definition at line 66 of file dynamic_routing.h.
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGame::MeanFieldRoutingGame().
kDefaultNetworkName
const char* open_spiel::dynamic_routing::kDefaultNetworkName = "braess" inline constexpr
Definition at line 67 of file dynamic_routing.h.
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGame::MeanFieldRoutingGame().
kDefaultTimeStepLength
double open_spiel::dynamic_routing::kDefaultTimeStepLength = 1.0 inline constexpr
Definition at line 64 of file dynamic_routing.h.
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGame::MeanFieldRoutingGame().
kNoPossibleAction
int open_spiel::dynamic_routing::kNoPossibleAction = 0 inline constexpr
Definition at line 38 of file dynamic_routing_utils.h.
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGameState::ActionToString(), and open_spiel::dynamic_routing::MeanFieldRoutingGameState::LegalActions().
kNumPlayers
int open_spiel::dynamic_routing::kNumPlayers = 1 inline constexpr
Definition at line 55 of file dynamic_routing.h.
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGame::MeanFieldRoutingGame().
kWaitingTimeNotAssigned
int open_spiel::dynamic_routing::kWaitingTimeNotAssigned = -1 inline constexpr
Definition at line 61 of file dynamic_routing.h.
Referenced by open_spiel::dynamic_routing::MeanFieldRoutingGameState::CreateNewInitialState(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::DistributionSupport(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::DoApplyAction(), and open_spiel::dynamic_routing::MeanFieldRoutingGameState::UpdateDistribution().