open spiel: absl::container_internal::hash_internal Namespace Reference
absl::container_internal::hash_internal Namespace Reference
Namespaces
namespace generator_internal
Classes
struct Generator
struct Generator< absl::string_view >
struct Generator< Enum >
struct Generator< EnumClass >
struct Generator< NonStandardLayout >
struct Generator< std::pair< K, V > >
struct Generator< std::string >
struct Generator< std::tuple< Ts... > >
struct Generator< std::unique_ptr< T > >
struct Generator< T, typename std::enable_if< std::is_integral< T >::value >::type >
struct Generator< U, absl::void_t< decltype(std::declval< U & >().key()), decltype(std::declval< U & >().value())> >
struct UniqueGenerator
Typedefs
template<class Container >
using GeneratedType
Enumerations
enum Enum { kEnumEmpty , kEnumDeleted }
enum class EnumClass : uint64_t { kEmpty , kDeleted }
Functions
std::mt19937_64 * GetSharedRng ()
std::ostream & operator<< (std::ostream &o, const EnumClass &ec)
Typedef Documentation
GeneratedType
template<class Container > using absl::container_internal::hash_internal::GeneratedType
Initial value:
 decltype(
    std::declval<const Generator<
        typename std::conditional<generator_internal::IsMap<Container>::value,
                                  typename Container::value_type,
                                  typename Container::key_type>::type>&>()())
Definition at line 152 of file hash_generator_testing.h.
Enumeration Type Documentation
Enum
enum absl::container_internal::hash_internal::Enum
Enumerator
kEnumEmpty
kEnumDeleted
Definition at line 53 of file hash_generator_testing.h.
          {
  kEnumEmpty,
  kEnumDeleted,
};
EnumClass
enum class absl::container_internal::hash_internal::EnumClass : uint64_t strong
Enumerator
kEmpty
kDeleted
Definition at line 58 of file hash_generator_testing.h.
                     : uint64_t {
  kEmpty,
  kDeleted,
};
Function Documentation
GetSharedRng()
std::mt19937_64 * absl::container_internal::hash_internal::GetSharedRng ()
Definition at line 43 of file hash_generator_testing.cc.
{
  static auto* rng = [] {
    RandomDeviceSeedSeq seed_seq;
    return new std::mt19937_64(seed_seq);
  }();
  return rng;
}
Referenced by absl::container_internal::hash_internal::Generator< Enum >::operator()(), absl::container_internal::hash_internal::Generator< EnumClass >::operator()(), and absl::container_internal::hash_internal::Generator< T, typename std::enable_if< std::is_integral< T >::value >::type >::operator()().
operator<<()
std::ostream & absl::container_internal::hash_internal::operator<< (std::ostream & o, const EnumClass & ec) inline
Definition at line 63 of file hash_generator_testing.h.
{
  return o << static_cast<uint64_t>(ec);
}
References absl::o.