open spiel: open_spiel.python.algorithms.alpha_zero.model_test Namespace Reference
open_spiel.python.algorithms.alpha_zero.model_test Namespace Reference
Classes
class ModelTest
Functions
solve_game (state)
build_model (game, model_type)
Variables
dict solved = {}
Detailed Description
Tests for open_spiel.python.algorithms.alpha_zero.model.
Function Documentation
build_model()
open_spiel.python.algorithms.alpha_zero.model_test.build_model (game, model_type)
Definition at line 49 of file model_test.py.
def build_model(game, model_type):
  return model_lib.Model.build_model(
      model_type, game.observation_tensor_shape(), game.num_distinct_actions(),
      nn_width=32, nn_depth=2, weight_decay=1e-4, learning_rate=0.01, path=None)
Referenced by open_spiel.python.algorithms.alpha_zero.model_test.ModelTest.test_model_learns_optimal(), and open_spiel.python.algorithms.alpha_zero.model_test.ModelTest.test_model_learns_simple().
solve_game()
open_spiel.python.algorithms.alpha_zero.model_test.solve_game (state)
Definition at line 28 of file model_test.py.
def solve_game(state):
  state_str = str(state)
  if state_str in solved:
    return solved[state_str].value
  if state.is_terminal():
    return state.returns()[0]
  max_player = state.current_player() == 0
  obs = state.observation_tensor()
  act_mask = np.array(state.legal_actions_mask())
  values = np.full(act_mask.shape, -2 if max_player else 2)
  for action in state.legal_actions():
    values[action] = solve_game(state.child(action))
  value = values.max() if max_player else values.min()
  best_actions = np.where((values == value) & act_mask)
  policy = np.zeros_like(act_mask)
  policy[best_actions[0][0]] = 1  # Choose the first for a deterministic policy.
  solved[state_str] = model_lib.TrainInput(obs, act_mask, policy, value)
  return value
References open_spiel.python.algorithms.alpha_zero.model_test.solve_game().
Referenced by open_spiel.python.algorithms.alpha_zero.model_test.solve_game(), and open_spiel.python.algorithms.alpha_zero.model_test.ModelTest.test_model_learns_optimal().
Variable Documentation
solved
dict open_spiel.python.algorithms.alpha_zero.model_test.solved = {}
Definition at line 25 of file model_test.py.