open spiel: open_spiel.python.algorithms.response_graph_ucb_utils Namespace Reference
open_spiel.python.algorithms.response_graph_ucb_utils Namespace Reference
Classes
class BernoulliGameSampler
class ZeroSumBernoulliGameSampler
Functions
get_method_tuple_acronym (method_tuple)
get_method_tuple_linespecs (method)
get_method_acronym (method)
digraph_edge_hamming_dist (g1, g2)
get_payoffs_bernoulli_game (size=(2, 2, 2))
get_soccer_data ()
get_kuhn_poker_data (num_players=4, iterations=3)
get_game_for_sampler (game_name)
plot_timeseries (ax, id_ax, data, xticks, xlabel='', ylabel='', label='', logx=False, logy=False, zorder=10, linespecs=None)
Detailed Description
Utility functions for ResponseGraphUCB.
Function Documentation
digraph_edge_hamming_dist()
open_spiel.python.algorithms.response_graph_ucb_utils.digraph_edge_hamming_dist (g1, g2)
Returns number of directed edge mismatches between digraphs g1 and g2.
Definition at line 90 of file response_graph_ucb_utils.py.
def digraph_edge_hamming_dist(g1, g2):
  """Returns number of directed edge mismatches between digraphs g1 and g2."""
  dist = 0
  for e1 in g1.edges:
    if e1 not in g2.edges:
      dist += 1
  return dist
get_game_for_sampler()
open_spiel.python.algorithms.response_graph_ucb_utils.get_game_for_sampler (game_name)
Returns pre-processed game data for ResponseGraphUCB examples.
Definition at line 200 of file response_graph_ucb_utils.py.
def get_game_for_sampler(game_name):
  """Returns pre-processed game data for ResponseGraphUCB examples."""
  # pylint: disable=invalid-name
  if game_name == 'bernoulli':
    M = get_payoffs_bernoulli_game()
    strategy_spaces = [2, 2]
    G = ZeroSumBernoulliGameSampler(
        strategy_spaces, means=M, payoff_bounds=[-1., 1.])
  elif game_name == 'soccer':
    M = get_soccer_data()
    M = M * 2. - 1  # Convert to zero-sum
    strategy_spaces = np.shape(M)
    M = np.asarray([M, M.T])
    G = ZeroSumBernoulliGameSampler(strategy_spaces, means=M,
                                    payoff_bounds=[np.min(M), np.max(M)])
  elif game_name in ['kuhn_poker_2p', 'kuhn_poker_3p', 'kuhn_poker_4p']:
    if '2p' in game_name:
      num_players = 2
    elif '3p' in game_name:
      num_players = 3
    elif '4p' in game_name:
      num_players = 4
    M = get_kuhn_poker_data(num_players, iterations=2)  # pylint: disable=invalid-name
    strategy_spaces = egt_utils.get_num_strats_per_population(M, False)
    G = BernoulliGameSampler(
        strategy_spaces, means=M, payoff_bounds=[np.min(M), np.max(M)])
  else:
    raise ValueError('Game', game_name, 'not implemented!')
  # pylint: enable=invalid-name
  return G
References open_spiel.python.algorithms.response_graph_ucb_utils.get_kuhn_poker_data(), open_spiel.python.algorithms.response_graph_ucb_utils.get_payoffs_bernoulli_game(), and open_spiel.python.algorithms.response_graph_ucb_utils.get_soccer_data().
get_kuhn_poker_data()
open_spiel.python.algorithms.response_graph_ucb_utils.get_kuhn_poker_data (num_players = 4, iterations = 3)
Returns the kuhn poker data for the number of players specified.
Definition at line 178 of file response_graph_ucb_utils.py.
def get_kuhn_poker_data(num_players=4, iterations=3):
  """Returns the kuhn poker data for the number of players specified."""
  game = pyspiel.load_game('kuhn_poker', {'players': num_players})
  xfp_solver = fictitious_play.XFPSolver(game, save_oracles=True)
  for _ in range(iterations):
    xfp_solver.iteration()
  # Results are seed-dependent, so show some interesting cases
  if num_players == 2:
    meta_games = xfp_solver.get_empirical_metagame(100, seed=1)
  elif num_players == 3:
    meta_games = xfp_solver.get_empirical_metagame(100, seed=5)
  elif num_players == 4:
    meta_games = xfp_solver.get_empirical_metagame(100, seed=2)
  # Metagame utility matrices for each player
  payoff_tables = []
  for i in range(num_players):
    payoff_tables.append(meta_games[i])
  return payoff_tables
Referenced by open_spiel.python.algorithms.response_graph_ucb_utils.get_game_for_sampler().
get_method_acronym()
open_spiel.python.algorithms.response_graph_ucb_utils.get_method_acronym (method)
Gets pretty acronym for specified ResponseGraphUCB method.
Definition at line 66 of file response_graph_ucb_utils.py.
def get_method_acronym(method):
  """Gets pretty acronym for specified ResponseGraphUCB method."""
  if method == 'uniform-exhaustive':
    return r'$\mathcal{S}$: UE'
  elif method == 'uniform':
    return r'$\mathcal{S}$: U'
  elif method == 'valence-weighted':
    return r'$\mathcal{S}$: VW'
  elif method == 'count-weighted':
    return r'$\mathcal{S}$: CW'
  elif method == 'ucb-standard':
    return r'$\mathcal{C}(\delta)$: UCB'
  elif method == 'ucb-standard-relaxed':
    return r'$\mathcal{C}(\delta)$: R-UCB'
  elif method == 'clopper-pearson-ucb':
    return r'$\mathcal{C}(\delta)$: CP-UCB'
  elif method == 'clopper-pearson-ucb-relaxed':
    return r'$\mathcal{C}(\delta)$: R-CP-UCB'
  elif method == 'fixedbudget-uniform':
    return r'$\mathcal{S}$: U, $\mathcal{C}(\delta)$: FB'
  else:
    raise ValueError('Unknown sampler method: {}!'.format(method))
Referenced by open_spiel.python.algorithms.response_graph_ucb_utils.get_method_tuple_acronym().
get_method_tuple_acronym()
open_spiel.python.algorithms.response_graph_ucb_utils.get_method_tuple_acronym (method_tuple)
Returns pretty acronym for specified ResponseGraphUCB method tuple.
Definition at line 29 of file response_graph_ucb_utils.py.
def get_method_tuple_acronym(method_tuple):
  """Returns pretty acronym for specified ResponseGraphUCB method tuple."""
  if isinstance(method_tuple, tuple):
    acronyms = [get_method_acronym(m) for m in method_tuple]
    return ', '.join(acronyms)
  else:
    return get_method_acronym(method_tuple)
References open_spiel.python.algorithms.response_graph_ucb_utils.get_method_acronym().
get_method_tuple_linespecs()
open_spiel.python.algorithms.response_graph_ucb_utils.get_method_tuple_linespecs (method)
Gets plot linespecs for the specified ResponseGraphUCB method.
Definition at line 38 of file response_graph_ucb_utils.py.
def get_method_tuple_linespecs(method):
  """Gets plot linespecs for the specified ResponseGraphUCB method."""
  sampling_strats = [
      'uniform-exhaustive', 'uniform', 'valence-weighted', 'count-weighted'
  ]
  conf_methods = ['ucb-standard', 'clopper-pearson-ucb']
  method_to_id_map = dict(
      (m, i)
      for i, m in enumerate(itertools.product(sampling_strats, conf_methods)))
  # Create palette
  num_colors = len(method_to_id_map.keys())
  colors = plt.get_cmap('Set1', num_colors).colors
  # Spec out the linestyle
  base_method = (method[0], method[1].replace('-relaxed', '')
                )  # Method name without -relaxed suffix
  linespecs = {
      'color': colors[method_to_id_map[base_method]]
  }  # Use base method for color (ignoring relaxed vs non-relaxed)
  if 'relaxed' in method[1]:  # Use actual method for linestyle
    linespecs['linestyle'] = 'dashed'
  else:
    linespecs['linestyle'] = 'solid'
  return linespecs
References len.
get_payoffs_bernoulli_game()
open_spiel.python.algorithms.response_graph_ucb_utils.get_payoffs_bernoulli_game (size = (2, 2, 2))
Gets randomly-generated zero-sum symmetric two-player game.
Definition at line 156 of file response_graph_ucb_utils.py.
def get_payoffs_bernoulli_game(size=(2, 2, 2)):
  """Gets randomly-generated zero-sum symmetric two-player game."""
  too_close = True
  while too_close:
    M = np.random.uniform(-1, 1, size=size)  # pylint: disable=invalid-name
    M[0, :, :] = 0.5 * (M[0, :, :] - M[0, :, :].T)
    M[1, :, :] = -M[0, :, :]
    if np.abs(M[0, 0, 1]) < 0.1:
      too_close = True
    else:
      too_close = False
  return M
Referenced by open_spiel.python.algorithms.response_graph_ucb_utils.get_game_for_sampler().
get_soccer_data()
open_spiel.python.algorithms.response_graph_ucb_utils.get_soccer_data ()
Returns the payoffs and strategy labels for MuJoCo soccer experiments.
Definition at line 170 of file response_graph_ucb_utils.py.
def get_soccer_data():
  """Returns the payoffs and strategy labels for MuJoCo soccer experiments."""
  payoff_file = file_utils.find_file(
      'open_spiel/data/paper_data/response_graph_ucb/soccer.txt', 2)
  payoffs = np.loadtxt(payoff_file)
  return payoffs
Referenced by open_spiel.python.algorithms.response_graph_ucb_utils.get_game_for_sampler().
plot_timeseries()
open_spiel.python.algorithms.response_graph_ucb_utils.plot_timeseries (ax, id_ax, data, xticks, xlabel = '', ylabel = '', label = '', logx = False, logy = False, zorder = 10, linespecs = None)
Plots timeseries data with error bars.
Definition at line 232 of file response_graph_ucb_utils.py.
                    linespecs=None):
  """Plots timeseries data with error bars."""
  if logx:
    ax[id_ax].set_xscale('log')
  if logy:
    ax[id_ax].set_yscale('log')
  if linespecs:
    kwargs = {'color': linespecs['color']}
  else:
    kwargs = {}
  # Seaborn's bootstrapped confidence intervals were used in the original paper
  se = scipy.stats.sem(data, axis=0)
  ax[id_ax].fill_between(xticks, data.mean(0)-se, data.mean(0)+se,
                         zorder=zorder, alpha=0.2, **kwargs)
  ax[id_ax].plot(xticks, data.mean(0), label=label, zorder=zorder, **kwargs)
  # There may be multiple lines on the current axis, some from previous calls to
  # plot_timeseries, so reference just the latest
  if linespecs:
    ax[id_ax].get_lines()[-1].set_dashes([5, 5])
    ax[id_ax].get_lines()[-1].set_linestyle(linespecs['linestyle'])
  ax[id_ax].set(xlabel=xlabel, ylabel=ylabel)
  ax[id_ax].set_axisbelow(True)
  ax[id_ax].grid(True)
  for _, spine in ax[id_ax].spines.items():
    spine.set_zorder(-1)