open spiel: absl::container_internal Namespace Reference
absl::container_internal Namespace Reference
Namespaces
namespace example
namespace hash_internal
namespace hash_testing_internal
namespace hashtable_debug_internal
namespace internal_compressed_tuple
namespace internal_layout
namespace memory_internal
Classes
struct Aligned
struct AlignedType
struct Alloc
class base_checker
class BitMask
class btree
struct btree_access
class btree_container
class btree_iterator
class btree_iterator_generation_info_disabled
class btree_iterator_generation_info_enabled
class btree_map_container
class btree_multimap_container
class btree_multiset_container
class btree_node
class btree_set_container
class BtreeNodePeer
struct BtreeTestOnlyCheckedCompareOptOutBase
struct checked_compare_base
struct checked_compare_base< Compare, false >
struct common_params
struct common_policy_traits
struct CommonAccess
class CommonFields
class CommonFieldsGenerationInfoDisabled
class CommonFieldsGenerationInfoEnabled
class CompressedTuple
class CompressedTuple<>
class ConstructorTest
class CountingAllocator
struct EraseFirst
struct FindInfo
struct FlatHashMapPolicy
struct FlatHashSetPolicy
struct Generator
struct Generator< absl::Time >
struct Generator< Cord >
struct Generator< std::pair< T, U > >
struct Generator< std::string >
struct GroupPortableImpl
struct has_linear_node_search_preference
struct has_linear_node_search_preference< T, absl::void_t< typename T::absl_btree_prefer_linear_node_search > >
struct hash_policy_traits
struct HashEq
struct HashEq< absl::Cord >
struct HashEq< absl::string_view >
struct HashEq< std::shared_ptr< T > >
struct HashEq< std::string >
struct HashEq< std::unique_ptr< T, D > >
struct HashEq< T * >
class HashSetIteratorGenerationInfoDisabled
class HashSetIteratorGenerationInfoEnabled
struct HashtableDebugProbeSummary
struct HashtablezInfo
class HashtablezInfoHandle
class HashtablezInfoHandlePeer
struct InsertReturnType
struct is_std_unordered_map
struct is_std_unordered_map< std::unordered_map< T... > >
struct is_std_unordered_set
struct is_std_unordered_set< std::unordered_set< T... > >
struct is_unique_ptr
struct is_unique_ptr< std::unique_ptr< Type > >
struct IsDecomposable
struct IsDecomposable< absl::void_t< decltype(Policy::apply(RequireUsableKey< typename Policy::key_type, Hash, Eq >(), std::declval< Ts >()...))>, Policy, Hash, Eq, Ts... >
struct IsTransparent
struct IsTransparent< T, absl::void_t< typename T::is_transparent > >
struct key_compare_adapter
struct key_compare_adapter< std::greater< absl::Cord >, absl::Cord >
struct key_compare_adapter< std::greater< absl::string_view >, absl::string_view >
struct key_compare_adapter< std::greater< std::string >, std::string >
struct key_compare_adapter< std::less< absl::Cord >, absl::Cord >
struct key_compare_adapter< std::less< absl::string_view >, absl::string_view >
struct key_compare_adapter< std::less< std::string >, std::string >
struct KeyArg
struct KeyArg< false >
struct KeyOfValue
struct KeyOfValue< K, K >
class Layout
class LookupTest
struct map_params
struct map_slot_policy
union map_slot_type
class map_value_compare
class MembersTest
class ModifiersTest
class node_handle
class node_handle< Policy, PolicyTraits, Alloc, absl::void_t< typename Policy::mapped_type > >
class node_handle_base
struct node_slot_policy
class NodeHashMapPolicy
struct NodeHashSetPolicy
class NonIterableBitMask
struct NonStandardLayout
struct PolicyFunctions
struct prefers_linear_node_search
struct prefers_linear_node_search< T, absl::void_t< typename T::absl_btree_prefer_linear_node_search > >
class probe_seq
class raw_hash_map
class raw_hash_set
struct RawHashSetTestOnlyAccess
struct remove_pair_const
struct remove_pair_const< std::pair< T, U > >
struct RequireUsableKey
struct SamplingState
struct SearchResult
struct SearchResult< V, false >
struct set_params
struct set_slot_policy
struct StatefulTestingEqual
struct StatefulTestingHash
struct StringBtreeDefaultGreater
struct StringBtreeDefaultLess
struct StringEq
struct StringHash
struct StringHashEq
class Tracked
class UniquePtrModifiersTest
struct upper_bound_adapter
Typedefs
template<typename Compare , typename T , typename U >
using compare_result_t = absl::result_of_t<const Compare(const T &, const U &)>
template<typename Compare , typename T >
using btree_is_key_compare_to
using btree_iterator_generation_info = btree_iterator_generation_info_disabled
template<class T >
using hash_default_hash = typename container_internal::HashEq<T>::Hash
template<class T >
using hash_default_eq = typename container_internal::HashEq<T>::Eq
using HashtablezSampler
using HashtablezConfigListener = void (*)()
using GenerationType = uint8_t
using h2_t = uint8_t
using Group = GroupPortableImpl
using CommonFieldsGenerationInfo = CommonFieldsGenerationInfoDisabled
using HashSetIteratorGenerationInfo = HashSetIteratorGenerationInfoDisabled
using has_cxx14_std_apis = std::false_type
template<typename T >
using expect_cxx14_apis
using has_alloc_std_constructors = std::false_type
template<typename T >
using expect_alloc_constructors
template<class V >
using IfNotVoid = typename std::enable_if<!std::is_void<V>::value, V>::type
Enumerations
enum class MatchKind : uint8_t { kEq , kNe }
enum class ctrl_t : int8_t { kEmpty = -128 , kDeleted = -2 , kSentinel = -1 }
Functions
char * GenerateDigits (char buf[16], unsigned val, unsigned maxval)
std::vector< int > GenerateNumbersWithSeed (int n, int maxval, int seed)
template<typename V >
std::vector< V > GenerateValuesWithSeed (int n, int maxval, int seed)
template<typename Compare , typename Key >
constexpr bool compare_has_valid_result_type ()
template<typename Node >
bool AreNodesFromSameContainer (const Node *node_a, const Node *node_b)
template<size_t Alignment, class Alloc >
void * Allocate (Alloc *alloc, size_t n)
template<size_t Alignment, class Alloc >
void Deallocate (Alloc *alloc, void *p, size_t n)
template<class Alloc , class T , class Tuple >
void ConstructFromTuple (Alloc *alloc, T *ptr, Tuple &&t)
template<class T , class Tuple , class F >
decltype(std::declval< F >()(std::declval< T >())) WithConstructed (Tuple &&t, F &&f)
std::pair< std::tuple<>, std::tuple<> > PairArgs ()
template<class F , class S >
std::pair< std::tuple< F && >, std::tuple< S && > > PairArgs (F &&f, S &&s)
template<class F , class S >
std::pair< std::tuple< const F & >, std::tuple< const S & > > PairArgs (const std::pair< F, S > &p)
template<class F , class S >
std::pair< std::tuple< F && >, std::tuple< S && > > PairArgs (std::pair< F, S > &&p)
template<class F , class S >
auto PairArgs (std::piecewise_construct_t, F &&f, S &&s) -> decltype(std::make_pair(memory_internal::TupleRef(std::forward< F >(f)), memory_internal::TupleRef(std::forward< S >(s))))
template<class F , class... Args>
auto DecomposePair (F &&f, Args &&... args) -> decltype(memory_internal::DecomposePairImpl(std::forward< F >(f), PairArgs(std::forward< Args >(args)...)))
template<class F , class Arg >
decltype(std::declval< F >()(std::declval< const Arg & >(), std::declval< Arg >())) DecomposeValue (F &&f, Arg &&arg)
void SanitizerPoisonMemoryRegion (const void *m, size_t s)
void SanitizerUnpoisonMemoryRegion (const void *m, size_t s)
template<typename T >
void SanitizerPoisonObject (const T *object)
template<typename T >
void SanitizerUnpoisonObject (const T *object)
template<class Map >
auto items (const Map &m) -> std::vector< std::pair< typename Map::key_type, typename Map::mapped_type > >
template<class Set >
auto keys (const Set &s) -> std::vector< typename std::decay< typename Set::key_type >::type >
template<typename C >
size_t GetHashtableDebugNumProbes (const C &c, const typename C::key_type &key)
template<typename C >
std::vector< size_t > GetHashtableDebugNumProbesHistogram (const C &container)
template<typename C >
HashtableDebugProbeSummary GetHashtableDebugProbeSummary (const C &container)
template<typename C >
size_t AllocatedByteSize (const C &c)
template<typename C >
size_t LowerBoundAllocatedByteSize (size_t num_elements)
HashtablezSampler & GlobalHashtablezSampler ()
HashtablezInfo * SampleSlow (SamplingState &next_sample, size_t inline_element_size)
void UnsampleSlow (HashtablezInfo *info)
void RecordRehashSlow (HashtablezInfo *info, size_t total_probe_length)
void RecordReservationSlow (HashtablezInfo *info, size_t target_capacity)
void RecordClearedReservationSlow (HashtablezInfo *info)
void RecordStorageChangedSlow (HashtablezInfo *info, size_t size, size_t capacity)
void RecordInsertSlow (HashtablezInfo *info, size_t hash, size_t distance_from_desired)
void RecordEraseSlow (HashtablezInfo *info)
void SetHashtablezConfigListener (HashtablezConfigListener l)
bool IsHashtablezEnabled ()
void SetHashtablezEnabled (bool enabled)
void SetHashtablezEnabledInternal (bool enabled)
int32_t GetHashtablezSampleParameter ()
void SetHashtablezSampleParameter (int32_t rate)
void SetHashtablezSampleParameterInternal (int32_t rate)
size_t GetHashtablezMaxSamples ()
void SetHashtablezMaxSamples (size_t max)
void SetHashtablezMaxSamplesInternal (size_t max)
HashtablezInfoHandle Sample (size_t inline_element_size ABSL_ATTRIBUTE_UNUSED)
bool ABSL_INTERNAL_C_SYMBOL AbslContainerInternalSampleEverything ()
size_t RandomSeed ()
bool ShouldInsertBackwards (size_t hash, const ctrl_t *ctrl)
void ConvertDeletedToEmptyAndFullToDeleted (ctrl_t *ctrl, size_t capacity)
template FindInfo find_first_non_full (const CommonFields &, size_t)
FindInfo find_first_non_full_outofline (const CommonFields &common, size_t hash)
void DropDeletesWithoutResize (CommonFields &common, const PolicyFunctions &policy, void *tmp_space)
void EraseMetaOnly (CommonFields &c, ctrl_t *it, size_t slot_size)
void ClearBackingArray (CommonFields &c, const PolicyFunctions &policy, bool reuse)
constexpr bool SwisstableGenerationsEnabled ()
constexpr size_t NumGenerationBytes ()
template<typename AllocType >
void SwapAlloc (AllocType &lhs, AllocType &rhs, std::true_type)
template<typename AllocType >
void SwapAlloc (AllocType &, AllocType &, std::false_type)
template<class T >
constexpr bool IsNoThrowSwappable (std::true_type={})
template<class T >
constexpr bool IsNoThrowSwappable (std::false_type)
template<typename T >
uint32_t TrailingZeros (T x)
ctrl_t * EmptyGroup ()
GenerationType * EmptyGeneration ()
size_t PerTableSalt (const ctrl_t *ctrl)
size_t H1 (size_t hash, const ctrl_t *ctrl)
h2_t H2 (size_t hash)
bool IsEmpty (ctrl_t c)
bool IsFull (ctrl_t c)
bool IsDeleted (ctrl_t c)
bool IsEmptyOrDeleted (ctrl_t c)
constexpr size_t NumClonedBytes ()
bool IsValidCapacity (size_t n)
size_t NextCapacity (size_t n)
size_t NormalizeCapacity (size_t n)
size_t CapacityToGrowth (size_t capacity)
size_t GrowthToLowerboundCapacity (size_t growth)
template<class InputIter >
size_t SelectBucketCountForIterRange (InputIter first, InputIter last, size_t bucket_count)
void AssertIsValidForComparison (const ctrl_t *ctrl, GenerationType generation, const GenerationType *generation_ptr)
bool AreItersFromSameContainer (const ctrl_t *ctrl_a, const ctrl_t *ctrl_b, const void *const &slot_a, const void *const &slot_b)
void AssertSameContainer (const ctrl_t *ctrl_a, const ctrl_t *ctrl_b, const void *const &slot_a, const void *const &slot_b)
bool is_small (size_t capacity)
probe_seq< Group::kWidth > probe (const CommonFields &common, size_t hash)
template<typename = void>
FindInfo find_first_non_full (const CommonFields &common, size_t hash)
void ResetGrowthLeft (CommonFields &common)
void ResetCtrl (CommonFields &common, size_t slot_size)
void SetCtrl (const CommonFields &common, size_t i, ctrl_t h, size_t slot_size)
void SetCtrl (const CommonFields &common, size_t i, h2_t h, size_t slot_size)
size_t GenerationOffset (size_t capacity)
size_t SlotOffset (size_t capacity, size_t slot_align)
size_t AllocSize (size_t capacity, size_t slot_size, size_t slot_align)
template<typename Alloc , size_t SizeOfSlot, size_t AlignOfSlot>
ABSL_ATTRIBUTE_NOINLINE void InitializeSlots (CommonFields &c, Alloc alloc)
template<size_t AlignOfSlot>
ABSL_ATTRIBUTE_NOINLINE void DeallocateStandard (void *, const PolicyFunctions &policy, ctrl_t *ctrl, void *slot_array, size_t n)
template<size_t SizeOfSlot>
ABSL_ATTRIBUTE_NOINLINE void TransferRelocatable (void *, void *dst, void *src)
template<typename P , typename H , typename E , typename A , typename Predicate >
raw_hash_set< P, H, E, A >::size_type EraseIf (Predicate &pred, raw_hash_set< P, H, E, A > *c)
TYPED_TEST_SUITE_P (ConstructorTest)
TYPED_TEST_P (ConstructorTest, NoArgs)
TYPED_TEST_P (ConstructorTest, BucketCount)
TYPED_TEST_P (ConstructorTest, BucketCountHash)
TYPED_TEST_P (ConstructorTest, BucketCountHashEqual)
TYPED_TEST_P (ConstructorTest, BucketCountHashEqualAlloc)
template<typename TypeParam >
void BucketCountAllocTest (std::false_type)
template<typename TypeParam >
void BucketCountAllocTest (std::true_type)
TYPED_TEST_P (ConstructorTest, BucketCountAlloc)
template<typename TypeParam >
void BucketCountHashAllocTest (std::false_type)
template<typename TypeParam >
void BucketCountHashAllocTest (std::true_type)
TYPED_TEST_P (ConstructorTest, BucketCountHashAlloc)
template<typename TypeParam >
void AllocTest (std::false_type)
template<typename TypeParam >
void AllocTest (std::true_type)
TYPED_TEST_P (ConstructorTest, Alloc)
TYPED_TEST_P (ConstructorTest, InputIteratorBucketHashEqualAlloc)
template<typename TypeParam >
void InputIteratorBucketAllocTest (std::false_type)
template<typename TypeParam >
void InputIteratorBucketAllocTest (std::true_type)
TYPED_TEST_P (ConstructorTest, InputIteratorBucketAlloc)
template<typename TypeParam >
void InputIteratorBucketHashAllocTest (std::false_type)
template<typename TypeParam >
void InputIteratorBucketHashAllocTest (std::true_type)
TYPED_TEST_P (ConstructorTest, InputIteratorBucketHashAlloc)
TYPED_TEST_P (ConstructorTest, CopyConstructor)
template<typename TypeParam >
void CopyConstructorAllocTest (std::false_type)
template<typename TypeParam >
void CopyConstructorAllocTest (std::true_type)
TYPED_TEST_P (ConstructorTest, CopyConstructorAlloc)
TYPED_TEST_P (ConstructorTest, MoveConstructor)
template<typename TypeParam >
void MoveConstructorAllocTest (std::false_type)
template<typename TypeParam >
void MoveConstructorAllocTest (std::true_type)
TYPED_TEST_P (ConstructorTest, MoveConstructorAlloc)
TYPED_TEST_P (ConstructorTest, InitializerListBucketHashEqualAlloc)
template<typename TypeParam >
void InitializerListBucketAllocTest (std::false_type)
template<typename TypeParam >
void InitializerListBucketAllocTest (std::true_type)
TYPED_TEST_P (ConstructorTest, InitializerListBucketAlloc)
template<typename TypeParam >
void InitializerListBucketHashAllocTest (std::false_type)
template<typename TypeParam >
void InitializerListBucketHashAllocTest (std::true_type)
TYPED_TEST_P (ConstructorTest, InitializerListBucketHashAlloc)
TYPED_TEST_P (ConstructorTest, Assignment)
TYPED_TEST_P (ConstructorTest, MoveAssignment)
TYPED_TEST_P (ConstructorTest, AssignmentFromInitializerList)
TYPED_TEST_P (ConstructorTest, AssignmentOverwritesExisting)
TYPED_TEST_P (ConstructorTest, MoveAssignmentOverwritesExisting)
TYPED_TEST_P (ConstructorTest, AssignmentFromInitializerListOverwritesExisting)
TYPED_TEST_P (ConstructorTest, AssignmentOnSelf)
REGISTER_TYPED_TEST_SUITE_P (ConstructorTest, NoArgs, BucketCount, BucketCountHash, BucketCountHashEqual, BucketCountHashEqualAlloc, BucketCountAlloc, BucketCountHashAlloc, Alloc, InputIteratorBucketHashEqualAlloc, InputIteratorBucketAlloc, InputIteratorBucketHashAlloc, CopyConstructor, CopyConstructorAlloc, MoveConstructor, MoveConstructorAlloc, InitializerListBucketHashEqualAlloc, InitializerListBucketAlloc, InitializerListBucketHashAlloc, Assignment, MoveAssignment, AssignmentFromInitializerList, AssignmentOverwritesExisting, MoveAssignmentOverwritesExisting, AssignmentFromInitializerListOverwritesExisting, AssignmentOnSelf)
TYPED_TEST_SUITE_P (LookupTest)
TYPED_TEST_P (LookupTest, At)
TYPED_TEST_P (LookupTest, OperatorBracket)
TYPED_TEST_P (LookupTest, Count)
TYPED_TEST_P (LookupTest, Find)
TYPED_TEST_P (LookupTest, EqualRange)
REGISTER_TYPED_TEST_SUITE_P (LookupTest, At, OperatorBracket, Count, Find, EqualRange)
TYPED_TEST_SUITE_P (MembersTest)
template<typename T >
void UseType ()
TYPED_TEST_P (MembersTest, Typedefs)
TYPED_TEST_P (MembersTest, SimpleFunctions)
TYPED_TEST_P (MembersTest, BeginEnd)
REGISTER_TYPED_TEST_SUITE_P (MembersTest, Typedefs, SimpleFunctions, BeginEnd)
TYPED_TEST_SUITE_P (ModifiersTest)
TYPED_TEST_P (ModifiersTest, Clear)
TYPED_TEST_P (ModifiersTest, Insert)
TYPED_TEST_P (ModifiersTest, InsertHint)
TYPED_TEST_P (ModifiersTest, InsertRange)
TYPED_TEST_P (ModifiersTest, InsertWithinCapacity)
TYPED_TEST_P (ModifiersTest, InsertRangeWithinCapacity)
TYPED_TEST_P (ModifiersTest, InsertOrAssign)
TYPED_TEST_P (ModifiersTest, InsertOrAssignHint)
TYPED_TEST_P (ModifiersTest, Emplace)
TYPED_TEST_P (ModifiersTest, EmplaceHint)
TYPED_TEST_P (ModifiersTest, TryEmplace)
TYPED_TEST_P (ModifiersTest, TryEmplaceHint)
TYPED_TEST_P (ModifiersTest, Erase)
TYPED_TEST_P (ModifiersTest, EraseRange)
TYPED_TEST_P (ModifiersTest, EraseKey)
TYPED_TEST_P (ModifiersTest, Swap)
REGISTER_TYPED_TEST_SUITE_P (ModifiersTest, Clear, Insert, InsertHint, InsertRange, InsertWithinCapacity, InsertRangeWithinCapacity, InsertOrAssign, InsertOrAssignHint, Emplace, EmplaceHint, TryEmplace, TryEmplaceHint, Erase, EraseRange, EraseKey, Swap)
GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST (UniquePtrModifiersTest)
TYPED_TEST_SUITE_P (UniquePtrModifiersTest)
TYPED_TEST_P (UniquePtrModifiersTest, TryEmplace)
REGISTER_TYPED_TEST_SUITE_P (UniquePtrModifiersTest, TryEmplace)
TYPED_TEST_P (ConstructorTest, CopyAssignment)
REGISTER_TYPED_TEST_SUITE_P (ConstructorTest, NoArgs, BucketCount, BucketCountHash, BucketCountHashEqual, BucketCountHashEqualAlloc, BucketCountAlloc, BucketCountHashAlloc, Alloc, InputIteratorBucketHashEqualAlloc, InputIteratorBucketAlloc, InputIteratorBucketHashAlloc, CopyConstructor, CopyConstructorAlloc, MoveConstructor, MoveConstructorAlloc, InitializerListBucketHashEqualAlloc, InitializerListBucketAlloc, InitializerListBucketHashAlloc, CopyAssignment, MoveAssignment, AssignmentFromInitializerList, AssignmentOverwritesExisting, MoveAssignmentOverwritesExisting, AssignmentFromInitializerListOverwritesExisting, AssignmentOnSelf)
REGISTER_TYPED_TEST_SUITE_P (LookupTest, Count, Find, EqualRange)
REGISTER_TYPED_TEST_SUITE_P (ModifiersTest, Clear, Insert, InsertHint, InsertRange, InsertWithinCapacity, InsertRangeWithinCapacity, Emplace, EmplaceHint, Erase, EraseRange, EraseKey, Swap)
Variables
ABSL_CONST_INIT ABSL_DLL const ctrl_t kEmptyGroup [17]
Typedef Documentation
btree_is_key_compare_to
template<typename Compare , typename T > using absl::container_internal::btree_is_key_compare_to
Initial value:
    std::is_convertible<compare_result_t<Compare, T, T>, absl::weak_ordering>
Definition at line 95 of file btree.h.
btree_iterator_generation_info
using absl::container_internal::btree_iterator_generation_info = btree_iterator_generation_info_disabled
Definition at line 1070 of file btree.h.
CommonFieldsGenerationInfo
using absl::container_internal::CommonFieldsGenerationInfo = CommonFieldsGenerationInfoDisabled
Definition at line 866 of file raw_hash_set.h.
compare_result_t
template<typename Compare , typename T , typename U > using absl::container_internal::compare_result_t = absl::result_of_t<const Compare(const T &, const U &)>
Definition at line 90 of file btree.h.
expect_alloc_constructors
template<typename T > using absl::container_internal::expect_alloc_constructors
Initial value:
    absl::disjunction<absl::negation<is_std_unordered_map<T>>,
                      has_alloc_std_constructors>
Definition at line 151 of file unordered_map_constructor_test.h.
expect_cxx14_apis
template<typename T > using absl::container_internal::expect_cxx14_apis
Initial value:
    absl::disjunction<absl::negation<is_std_unordered_map<T>>,
                      has_cxx14_std_apis>
Definition at line 101 of file unordered_map_constructor_test.h.
GenerationType
using absl::container_internal::GenerationType = uint8_t
Definition at line 236 of file raw_hash_set.h.
Group
using absl::container_internal::Group = GroupPortableImpl
Definition at line 749 of file raw_hash_set.h.
h2_t
using absl::container_internal::h2_t = uint8_t
Definition at line 427 of file raw_hash_set.h.
has_alloc_std_constructors
typedef std::false_type absl::container_internal::has_alloc_std_constructors = std::false_type
Definition at line 147 of file unordered_map_constructor_test.h.
has_cxx14_std_apis
typedef std::false_type absl::container_internal::has_cxx14_std_apis = std::false_type
Definition at line 97 of file unordered_map_constructor_test.h.
hash_default_eq
template<class T > using absl::container_internal::hash_default_eq = typename container_internal::HashEq<T>::Eq
Definition at line 157 of file hash_function_defaults.h.
hash_default_hash
template<class T > using absl::container_internal::hash_default_hash = typename container_internal::HashEq<T>::Hash
Definition at line 150 of file hash_function_defaults.h.
HashSetIteratorGenerationInfo
using absl::container_internal::HashSetIteratorGenerationInfo = HashSetIteratorGenerationInfoDisabled
Definition at line 867 of file raw_hash_set.h.
HashtablezConfigListener
using absl::container_internal::HashtablezConfigListener = void (*)()
Definition at line 238 of file hashtablez_sampler.h.
HashtablezSampler
using absl::container_internal::HashtablezSampler
Initial value:
    ::absl::profiling_internal::SampleRecorder<HashtablezInfo>
Definition at line 232 of file hashtablez_sampler.h.
IfNotVoid
template<class V > using absl::container_internal::IfNotVoid = typename std::enable_if<!std::is_void<V>::value, V>::type
Definition at line 220 of file unordered_map_modifiers_test.h.
Enumeration Type Documentation
ctrl_t
enum class absl::container_internal::ctrl_t : int8_t strong
Enumerator
kEmpty
kDeleted
kSentinel
Definition at line 446 of file raw_hash_set.h.
                  : int8_t {
  kEmpty = -128,   // 0b10000000
  kDeleted = -2,   // 0b11111110
  kSentinel = -1,  // 0b11111111
};
MatchKind
enum class absl::container_internal::MatchKind : uint8_t strong
Enumerator
kEq
kNe
Definition at line 461 of file btree.h.
: uint8_t { kEq, kNe };
Function Documentation
AbslContainerInternalSampleEverything()
ABSL_ATTRIBUTE_WEAK bool ABSL_INTERNAL_C_SYMBOL absl::container_internal::AbslContainerInternalSampleEverything ()
Definition at line 24 of file hashtablez_sampler_force_weak_definition.cc.
{
  return false;
}
Allocate()
template<size_t Alignment, class Alloc > void * absl::container_internal::Allocate (Alloc * alloc, size_t n)
Definition at line 55 of file container_memory.h.
{
  static_assert(Alignment > 0, "");
  assert(n && "n must be positive");
  using M = AlignedType<Alignment>;
  using A = typename absl::allocator_traits<Alloc>::template rebind_alloc<M>;
  using AT = typename absl::allocator_traits<Alloc>::template rebind_traits<M>;
  // On macOS, "mem_alloc" is a #define with one argument defined in
  // rpc/types.h, so we can't name the variable "mem_alloc" and initialize it
  // with the "foo(bar)" syntax.
  A my_mem_alloc(*alloc);
  void* p = AT::allocate(my_mem_alloc, (n + sizeof(M) - 1) / sizeof(M));
  assert(reinterpret_cast<uintptr_t>(p) % Alignment == 0 &&
         "allocator does not respect alignment");
  return p;
}
References alloc, Allocate(), n, and absl::p.
Referenced by Allocate(), and InitializeSlots().
AllocatedByteSize()
template<typename C > size_t absl::container_internal::AllocatedByteSize (const C & c)
Definition at line 93 of file hashtable_debug.h.
{
  return absl::container_internal::hashtable_debug_internal::
      HashtableDebugAccess<C>::AllocatedByteSize(c);
}
References absl::c.
AllocSize()
size_t absl::container_internal::AllocSize (size_t capacity, size_t slot_size, size_t slot_align) inline
Definition at line 1217 of file raw_hash_set.h.
{
  return SlotOffset(capacity, slot_align) + capacity * slot_size;
}
References SlotOffset().
Referenced by absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::AllocatedByteSize(), DeallocateStandard(), InitializeSlots(), absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::LowerBoundAllocatedByteSize(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::~raw_hash_set().
AllocTest() [1/2]
template<typename TypeParam > void absl::container_internal::AllocTest (std::false_type)
Definition at line 156 of file unordered_map_constructor_test.h.
{}
Referenced by TYPED_TEST_P().
AllocTest() [2/2]
template<typename TypeParam > void absl::container_internal::AllocTest (std::true_type)
Definition at line 159 of file unordered_map_constructor_test.h.
{
  using A = typename TypeParam::allocator_type;
  A alloc(0);
  TypeParam m(alloc);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_TRUE(m.empty());
  EXPECT_THAT(m, ::testing::UnorderedElementsAre());
}
References alloc.
AreItersFromSameContainer()
bool absl::container_internal::AreItersFromSameContainer (const ctrl_t * ctrl_a, const ctrl_t * ctrl_b, const void *const & slot_a, const void *const & slot_b) inline
Definition at line 1059 of file raw_hash_set.h.
{
  // If either control byte is null, then we can't tell.
  if (ctrl_a == nullptr || ctrl_b == nullptr) return true;
  const void* low_slot = slot_a;
  const void* hi_slot = slot_b;
  if (ctrl_a > ctrl_b) {
    std::swap(ctrl_a, ctrl_b);
    std::swap(low_slot, hi_slot);
  }
  return ctrl_b < low_slot && low_slot <= hi_slot;
}
Referenced by AssertSameContainer().
AreNodesFromSameContainer()
template<typename Node > bool absl::container_internal::AreNodesFromSameContainer (const Node * node_a, const Node * node_b)
Definition at line 1021 of file btree.h.
{
  // If either node is null, then give up on checking whether they're from the
  // same container. (If exactly one is null, then we'll trigger the
  // default-constructed assert in Equals.)
  if (node_a == nullptr || node_b == nullptr) return true;
  while (!node_a->is_root()) node_a = node_a->parent();
  while (!node_b->is_root()) node_b = node_b->parent();
  return node_a == node_b;
}
AssertIsValidForComparison()
void absl::container_internal::AssertIsValidForComparison (const ctrl_t * ctrl, GenerationType generation, const GenerationType * generation_ptr) inline
Definition at line 1042 of file raw_hash_set.h.
{
  ABSL_HARDENING_ASSERT((ctrl == nullptr || IsFull(*ctrl)) &&
                        "Invalid iterator comparison. The element might have "
                        "been erased or the table might have rehashed.");
  if (SwisstableGenerationsEnabled() && generation != *generation_ptr) {
    ABSL_INTERNAL_LOG(FATAL,
                      "Invalid iterator comparison. The table could have "
                      "rehashed since this iterator was initialized.");
  }
}
References ABSL_HARDENING_ASSERT, ABSL_INTERNAL_LOG, IsFull(), and SwisstableGenerationsEnabled().
AssertSameContainer()
void absl::container_internal::AssertSameContainer (const ctrl_t * ctrl_a, const ctrl_t * ctrl_b, const void *const & slot_a, const void *const & slot_b) inline
Definition at line 1080 of file raw_hash_set.h.
{
  ABSL_HARDENING_ASSERT(
      AreItersFromSameContainer(ctrl_a, ctrl_b, slot_a, slot_b) &&
      "Invalid iterator comparison. The iterators may be from different "
      "containers or the container might have rehashed.");
}
References ABSL_HARDENING_ASSERT, and AreItersFromSameContainer().
BucketCountAllocTest() [1/2]
template<typename TypeParam > void absl::container_internal::BucketCountAllocTest (std::false_type)
Definition at line 106 of file unordered_map_constructor_test.h.
{}
Referenced by TYPED_TEST_P().
BucketCountAllocTest() [2/2]
template<typename TypeParam > void absl::container_internal::BucketCountAllocTest (std::true_type)
Definition at line 109 of file unordered_map_constructor_test.h.
{
  using A = typename TypeParam::allocator_type;
  A alloc(0);
  TypeParam m(123, alloc);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_TRUE(m.empty());
  EXPECT_THAT(m, ::testing::UnorderedElementsAre());
  EXPECT_GE(m.bucket_count(), 123);
}
References alloc.
BucketCountHashAllocTest() [1/2]
template<typename TypeParam > void absl::container_internal::BucketCountHashAllocTest (std::false_type)
Definition at line 124 of file unordered_map_constructor_test.h.
{}
Referenced by TYPED_TEST_P().
BucketCountHashAllocTest() [2/2]
template<typename TypeParam > void absl::container_internal::BucketCountHashAllocTest (std::true_type)
Definition at line 127 of file unordered_map_constructor_test.h.
{
  using H = typename TypeParam::hasher;
  using A = typename TypeParam::allocator_type;
  H hasher;
  A alloc(0);
  TypeParam m(123, hasher, alloc);
  EXPECT_EQ(m.hash_function(), hasher);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_TRUE(m.empty());
  EXPECT_THAT(m, ::testing::UnorderedElementsAre());
  EXPECT_GE(m.bucket_count(), 123);
}
References alloc, and hasher.
CapacityToGrowth()
size_t absl::container_internal::CapacityToGrowth (size_t capacity) inline
Definition at line 984 of file raw_hash_set.h.
{
  assert(IsValidCapacity(capacity));
  // `capacity*7/8`
  if (Group::kWidth == 8 && capacity == 7) {
    // x-x/8 does not work when x==7.
    return 6;
  }
  return capacity - capacity / 8;
}
References IsValidCapacity(), and absl::container_internal::GroupPortableImpl::kWidth.
Referenced by ResetGrowthLeft().
ClearBackingArray()
void absl::container_internal::ClearBackingArray (CommonFields & c, const PolicyFunctions & policy, bool reuse)
Definition at line 200 of file raw_hash_set.cc.
{
  c.size_ = 0;
  if (reuse) {
    ResetCtrl(c, policy.slot_size);
    c.infoz().RecordStorageChanged(0, c.capacity_);
  } else {
    void* set = &c;
    (*policy.dealloc)(set, policy, c.control_, c.slots_, c.capacity_);
    c.control_ = EmptyGroup();
    c.set_generation_ptr(EmptyGeneration());
    c.slots_ = nullptr;
    c.capacity_ = 0;
    c.growth_left() = 0;
    c.infoz().RecordClearedReservation();
    assert(c.size_ == 0);
    c.infoz().RecordStorageChanged(0, 0);
  }
}
References absl::c, EmptyGeneration(), EmptyGroup(), and ResetCtrl().
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::clear(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::rehash().
compare_has_valid_result_type()
template<typename Compare , typename Key > bool absl::container_internal::compare_has_valid_result_type () constexpr
Definition at line 333 of file btree.h.
{
  using compare_result_type = compare_result_t<Compare, Key, Key>;
  return std::is_same<compare_result_type, bool>::value ||
         std::is_convertible<compare_result_type, absl::weak_ordering>::value;
}
ConstructFromTuple()
template<class Alloc , class T , class Tuple > void absl::container_internal::ConstructFromTuple (Alloc * alloc, T * ptr, Tuple && t)
Definition at line 149 of file container_memory.h.
{
  memory_internal::ConstructFromTupleImpl(
      alloc, ptr, std::forward<Tuple>(t),
      absl::make_index_sequence<
          std::tuple_size<typename std::decay<Tuple>::type>::value>());
}
References alloc, ConstructFromTuple(), and ptr.
Referenced by ConstructFromTuple().
ConvertDeletedToEmptyAndFullToDeleted()
void absl::container_internal::ConvertDeletedToEmptyAndFullToDeleted (ctrl_t * ctrl, size_t capacity)
Definition at line 60 of file raw_hash_set.cc.
{
  assert(ctrl[capacity] == ctrl_t::kSentinel);
  assert(IsValidCapacity(capacity));
  for (ctrl_t* pos = ctrl; pos < ctrl + capacity; pos += Group::kWidth) {
    Group{pos}.ConvertSpecialToEmptyAndFullToDeleted(pos);
  }
  // Copy the cloned ctrl bytes.
  std::memcpy(ctrl + capacity + 1, ctrl, NumClonedBytes());
  ctrl[capacity] = ctrl_t::kSentinel;
}
References IsValidCapacity(), kSentinel, absl::container_internal::GroupPortableImpl::kWidth, and NumClonedBytes().
Referenced by DropDeletesWithoutResize().
CopyConstructorAllocTest() [1/2]
template<typename TypeParam > void absl::container_internal::CopyConstructorAllocTest (std::false_type)
Definition at line 255 of file unordered_map_constructor_test.h.
{}
Referenced by TYPED_TEST_P().
CopyConstructorAllocTest() [2/2]
template<typename TypeParam > void absl::container_internal::CopyConstructorAllocTest (std::true_type)
Definition at line 258 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  hash_internal::UniqueGenerator<T> gen;
  TypeParam m(123, hasher, equal, alloc);
  for (size_t i = 0; i != 10; ++i) m.insert(gen());
  TypeParam n(m, A(11));
  EXPECT_EQ(m.hash_function(), n.hash_function());
  EXPECT_EQ(m.key_eq(), n.key_eq());
  EXPECT_NE(m.get_allocator(), n.get_allocator());
  EXPECT_EQ(m, n);
}
References absl::A, alloc, absl::E, absl::equal(), hasher, absl::i, and absl::n.
Deallocate()
template<size_t Alignment, class Alloc > void absl::container_internal::Deallocate (Alloc * alloc, void * p, size_t n)
Definition at line 74 of file container_memory.h.
{
  static_assert(Alignment > 0, "");
  assert(n && "n must be positive");
  using M = AlignedType<Alignment>;
  using A = typename absl::allocator_traits<Alloc>::template rebind_alloc<M>;
  using AT = typename absl::allocator_traits<Alloc>::template rebind_traits<M>;
  // On macOS, "mem_alloc" is a #define with one argument defined in
  // rpc/types.h, so we can't name the variable "mem_alloc" and initialize it
  // with the "foo(bar)" syntax.
  A my_mem_alloc(*alloc);
  AT::deallocate(my_mem_alloc, static_cast<M*>(p),
                 (n + sizeof(M) - 1) / sizeof(M));
}
References alloc, Deallocate(), n, and absl::p.
Referenced by Deallocate(), DeallocateStandard(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::~raw_hash_set().
DeallocateStandard()
template<size_t AlignOfSlot> ABSL_ATTRIBUTE_NOINLINE void absl::container_internal::DeallocateStandard (void * , const PolicyFunctions & policy, ctrl_t * ctrl, void * slot_array, size_t n)
Definition at line 1282 of file raw_hash_set.h.
{
  // Unpoison before returning the memory to the allocator.
  SanitizerUnpoisonMemoryRegion(slot_array, policy.slot_size * n);
  std::allocator<char> alloc;
  Deallocate<AlignOfSlot>(&alloc, ctrl,
                          AllocSize(n, policy.slot_size, AlignOfSlot));
}
References alloc, AllocSize(), Deallocate(), absl::n, and SanitizerUnpoisonMemoryRegion().
DecomposePair()
template<class F , class... Args> auto absl::container_internal::DecomposePair (F && f, Args &&... args) -> decltype(memory_internal::DecomposePairImpl(std::forward<F>(f), PairArgs(std::forward<Args>(args)...)))
Definition at line 204 of file container_memory.h.
{
  return memory_internal::DecomposePairImpl(
      std::forward<F>(f), PairArgs(std::forward<Args>(args)...));
}
References DecomposePair(), absl::f, and PairArgs().
Referenced by absl::container_internal::FlatHashMapPolicy< K, V >::apply(), absl::container_internal::NodeHashMapPolicy< Key, Value >::apply(), and DecomposePair().
DecomposeValue()
template<class F , class Arg > decltype(std::declval< F >()(std::declval< const Arg & >(), std::declval< Arg >())) absl::container_internal::DecomposeValue (F && f, Arg && arg)
Definition at line 214 of file container_memory.h.
{
  const auto& key = arg;
  return std::forward<F>(f)(key, std::forward<Arg>(arg));
}
References arg, DecomposeValue(), absl::f, and key.
Referenced by absl::container_internal::FlatHashSetPolicy< T >::apply(), absl::container_internal::NodeHashSetPolicy< T >::apply(), and DecomposeValue().
DropDeletesWithoutResize()
void absl::container_internal::DropDeletesWithoutResize (CommonFields & common, const PolicyFunctions & policy, void * tmp_space)
Definition at line 97 of file raw_hash_set.cc.
{
  void* set = &common;
  void* slot_array = common.slots_;
  const size_t capacity = common.capacity_;
  assert(IsValidCapacity(capacity));
  assert(!is_small(capacity));
  // Algorithm:
  // - mark all DELETED slots as EMPTY
  // - mark all FULL slots as DELETED
  // - for each slot marked as DELETED
  //     hash = Hash(element)
  //     target = find_first_non_full(hash)
  //     if target is in the same group
  //       mark slot as FULL
  //     else if target is EMPTY
  //       transfer element to target
  //       mark slot as EMPTY
  //       mark target as FULL
  //     else if target is DELETED
  //       swap current element with target element
  //       mark target as FULL
  //       repeat procedure for current slot with moved from element (target)
  ctrl_t* ctrl = common.control_;
  ConvertDeletedToEmptyAndFullToDeleted(ctrl, capacity);
  auto hasher = policy.hash_slot;
  auto transfer = policy.transfer;
  const size_t slot_size = policy.slot_size;
  size_t total_probe_length = 0;
  void* slot_ptr = SlotAddress(slot_array, 0, slot_size);
  for (size_t i = 0; i != capacity;
       ++i, slot_ptr = NextSlot(slot_ptr, slot_size)) {
    assert(slot_ptr == SlotAddress(slot_array, i, slot_size));
    if (!IsDeleted(ctrl[i])) continue;
    const size_t hash = (*hasher)(set, slot_ptr);
    const FindInfo target = find_first_non_full(common, hash);
    const size_t new_i = target.offset;
    total_probe_length += target.probe_length;
    // Verify if the old and new i fall within the same group wrt the hash.
    // If they do, we don't need to move the object as it falls already in the
    // best probe we can.
    const size_t probe_offset = probe(common, hash).offset();
    const auto probe_index = [probe_offset, capacity](size_t pos) {
      return ((pos - probe_offset) & capacity) / Group::kWidth;
    };
    // Element doesn't move.
    if (ABSL_PREDICT_TRUE(probe_index(new_i) == probe_index(i))) {
      SetCtrl(common, i, H2(hash), slot_size);
      continue;
    }
    void* new_slot_ptr = SlotAddress(slot_array, new_i, slot_size);
    if (IsEmpty(ctrl[new_i])) {
      // Transfer element to the empty spot.
      // SetCtrl poisons/unpoisons the slots so we have to call it at the
      // right time.
      SetCtrl(common, new_i, H2(hash), slot_size);
      (*transfer)(set, new_slot_ptr, slot_ptr);
      SetCtrl(common, i, ctrl_t::kEmpty, slot_size);
    } else {
      assert(IsDeleted(ctrl[new_i]));
      SetCtrl(common, new_i, H2(hash), slot_size);
      // Until we are done rehashing, DELETED marks previously FULL slots.
      // Swap i and new_i elements.
      (*transfer)(set, tmp_space, new_slot_ptr);
      (*transfer)(set, new_slot_ptr, slot_ptr);
      (*transfer)(set, slot_ptr, tmp_space);
      // repeat the processing of the ith slot
      --i;
      slot_ptr = PrevSlot(slot_ptr, slot_size);
    }
  }
  ResetGrowthLeft(common);
  common.infoz().RecordRehash(total_probe_length);
}
References ABSL_PREDICT_TRUE, absl::container_internal::CommonFields::capacity_, absl::container_internal::CommonFields::control_, ConvertDeletedToEmptyAndFullToDeleted(), find_first_non_full(), H2(), hash, hasher, absl::i, absl::container_internal::CommonFields::infoz(), is_small(), IsDeleted(), IsEmpty(), IsValidCapacity(), kEmpty, absl::container_internal::GroupPortableImpl::kWidth, probe(), absl::container_internal::HashtablezInfoHandle::RecordRehash(), ResetGrowthLeft(), SetCtrl(), and absl::container_internal::CommonFields::slots_.
EmptyGeneration()
GenerationType * absl::container_internal::EmptyGeneration () inline
Definition at line 489 of file raw_hash_set.h.
{
  return reinterpret_cast<GenerationType*>(EmptyGroup() + 16);
}
References EmptyGroup().
Referenced by ClearBackingArray(), and absl::container_internal::CommonFieldsGenerationInfoEnabled::CommonFieldsGenerationInfoEnabled().
EmptyGroup()
ctrl_t * absl::container_internal::EmptyGroup () inline
Definition at line 481 of file raw_hash_set.h.
{
  // Const must be cast away here; no uses of this function will actually write
  // to it, because it is only used for empty tables.
  return const_cast<ctrl_t*>(kEmptyGroup);
}
References kEmptyGroup.
Referenced by ClearBackingArray(), absl::container_internal::CommonFields::CommonFields(), and EmptyGeneration().
EraseIf()
template<typename P , typename H , typename E , typename A , typename Predicate > raw_hash_set< P, H, E, A >::size_type absl::container_internal::EraseIf (Predicate & pred, raw_hash_set< P, H, E, A > * c)
Definition at line 2604 of file raw_hash_set.h.
{
  const auto initial_size = c->size();
  for (auto it = c->begin(), last = c->end(); it != last;) {
    if (pred(*it)) {
      c->erase(it++);
    } else {
      ++it;
    }
  }
  return initial_size - c->size();
}
References absl::c.
Referenced by absl::erase_if(), absl::erase_if(), absl::erase_if(), and absl::erase_if().
EraseMetaOnly()
void absl::container_internal::EraseMetaOnly (CommonFields & c, ctrl_t * it, size_t slot_size)
Definition at line 178 of file raw_hash_set.cc.
{
  assert(IsFull(*it) && "erasing a dangling iterator");
  --c.size_;
  const auto index = static_cast<size_t>(it - c.control_);
  const size_t index_before = (index - Group::kWidth) & c.capacity_;
  const auto empty_after = Group(it).MaskEmpty();
  const auto empty_before = Group(c.control_ + index_before).MaskEmpty();
  // We count how many consecutive non empties we have to the right and to the
  // left of `it`. If the sum is >= kWidth then there is at least one probe
  // window that might have seen a full group.
  bool was_never_full = empty_before && empty_after &&
                        static_cast<size_t>(empty_after.TrailingZeros()) +
                                empty_before.LeadingZeros() <
                            Group::kWidth;
  SetCtrl(c, index, was_never_full ? ctrl_t::kEmpty : ctrl_t::kDeleted,
          slot_size);
  c.growth_left() += (was_never_full ? 1 : 0);
  c.infoz().RecordErase();
}
References absl::c, IsFull(), kDeleted, kEmpty, absl::container_internal::GroupPortableImpl::kWidth, absl::container_internal::GroupPortableImpl::MaskEmpty(), and SetCtrl().
find_first_non_full() [1/2]
template FindInfo absl::container_internal::find_first_non_full (const CommonFields & , size_t)
Referenced by DropDeletesWithoutResize(), find_first_non_full_outofline(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert().
find_first_non_full() [2/2]
template<typename = void> FindInfo absl::container_internal::find_first_non_full (const CommonFields & common, size_t hash) inline
Definition at line 1123 of file raw_hash_set.h.
{
  auto seq = probe(common, hash);
  const ctrl_t* ctrl = common.control_;
  while (true) {
    Group g{ctrl + seq.offset()};
    auto mask = g.MaskEmptyOrDeleted();
    if (mask) {
#if !defined(NDEBUG)
      // We want to add entropy even when ASLR is not enabled.
      // In debug build we will randomly insert in either the front or back of
      // the group.
      // TODO(kfm,sbenza): revisit after we do unconditional mixing
      if (!is_small(common.capacity_) && ShouldInsertBackwards(hash, ctrl)) {
        return {seq.offset(mask.HighestBitSet()), seq.index()};
      }
#endif
      return {seq.offset(mask.LowestBitSet()), seq.index()};
    }
    seq.next();
    assert(seq.index() <= common.capacity_ && "full table!");
  }
}
References absl::container_internal::CommonFields::capacity_, absl::container_internal::CommonFields::control_, absl::g, hash, is_small(), probe(), and ShouldInsertBackwards().
find_first_non_full_outofline()
FindInfo absl::container_internal::find_first_non_full_outofline (const CommonFields & common, size_t hash)
Definition at line 73 of file raw_hash_set.cc.
{
  return find_first_non_full(common, hash);
}
References find_first_non_full(), and hash.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set().
GenerateDigits()
char * absl::container_internal::GenerateDigits (char buf[16], unsigned val, unsigned maxval) inline
Definition at line 64 of file btree_test.h.
{
  assert(val <= maxval);
  constexpr unsigned kBase = 64;  // avoid integer division.
  unsigned p = 15;
  buf[p--] = 0;
  while (maxval > 0) {
    buf[p--] = ' ' + (val % kBase);
    val /= kBase;
    maxval /= kBase;
  }
  return buf + p + 1;
}
References buf, and absl::p.
Referenced by absl::container_internal::Generator< Cord >::operator()(), and absl::container_internal::Generator< std::string >::operator()().
GenerateNumbersWithSeed()
std::vector< int > absl::container_internal::GenerateNumbersWithSeed (int n, int maxval, int seed) inline
Definition at line 126 of file btree_test.h.
{
  // NOTE: Some tests rely on generated numbers not changing between test runs.
  // We use std::minstd_rand0 because it is well-defined, but don't use
  // std::uniform_int_distribution because platforms use different algorithms.
  std::minstd_rand0 rng(seed);
  std::vector<int> values;
  absl::flat_hash_set<int> unique_values;
  if (values.size() < n) {
    for (int i = values.size(); i < n; i++) {
      int value;
      do {
        value = static_cast<int>(rng()) % (maxval + 1);
      } while (!unique_values.insert(value).second);
      values.push_back(value);
    }
  }
  return values;
}
References absl::i, absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::n, value, and values.
Referenced by GenerateValuesWithSeed().
GenerateValuesWithSeed()
template<typename V > std::vector< V > absl::container_internal::GenerateValuesWithSeed (int n, int maxval, int seed)
Definition at line 149 of file btree_test.h.
{
  const std::vector<int> nums = GenerateNumbersWithSeed(n, maxval, seed);
  Generator<V> gen(maxval);
  std::vector<V> vec;
  vec.reserve(n);
  for (int i = 0; i < n; i++) {
    vec.push_back(gen(nums[i]));
  }
  return vec;
}
References GenerateNumbersWithSeed(), absl::i, and absl::n.
GenerationOffset()
size_t absl::container_internal::GenerationOffset (size_t capacity) inline
Definition at line 1200 of file raw_hash_set.h.
{
  assert(IsValidCapacity(capacity));
  const size_t num_control_bytes = capacity + 1 + NumClonedBytes();
  return num_control_bytes;
}
References IsValidCapacity(), and NumClonedBytes().
Referenced by InitializeSlots().
GetHashtableDebugNumProbes()
template<typename C > size_t absl::container_internal::GetHashtableDebugNumProbes (const C & c, const typename C::key_type & key)
Definition at line 49 of file hashtable_debug.h.
{
  return absl::container_internal::hashtable_debug_internal::
      HashtableDebugAccess<C>::GetNumProbes(c, key);
}
References absl::c, absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Container, Enabler >::GetNumProbes(), and key.
Referenced by GetHashtableDebugNumProbesHistogram().
GetHashtableDebugNumProbesHistogram()
template<typename C > std::vector< size_t > absl::container_internal::GetHashtableDebugNumProbesHistogram (const C & container)
Definition at line 58 of file hashtable_debug.h.
{
  std::vector<size_t> v;
  for (auto it = container.begin(); it != container.end(); ++it) {
    size_t num_probes = GetHashtableDebugNumProbes(
        container,
        absl::container_internal::hashtable_debug_internal::GetKey<C>(*it, 0));
    v.resize((std::max)(v.size(), num_probes + 1));
    v[num_probes]++;
  }
  return v;
}
References GetHashtableDebugNumProbes(), absl::container_internal::hashtable_debug_internal::GetKey(), and absl::v.
Referenced by GetHashtableDebugProbeSummary().
GetHashtableDebugProbeSummary()
template<typename C > HashtableDebugProbeSummary absl::container_internal::GetHashtableDebugProbeSummary (const C & container)
Definition at line 79 of file hashtable_debug.h.
{
  auto probes = GetHashtableDebugNumProbesHistogram(container);
  HashtableDebugProbeSummary summary = {};
  for (size_t i = 0; i < probes.size(); ++i) {
    summary.total_elements += probes[i];
    summary.total_num_probes += probes[i] * i;
  }
  summary.mean = 1.0 * summary.total_num_probes / summary.total_elements;
  return summary;
}
References GetHashtableDebugNumProbesHistogram(), absl::i, and absl::container_internal::HashtableDebugProbeSummary::total_elements.
GetHashtablezMaxSamples()
size_t absl::container_internal::GetHashtablezMaxSamples ()
Definition at line 264 of file hashtablez_sampler.cc.
{
  return GlobalHashtablezSampler().GetMaxSamples();
}
References absl::profiling_internal::SampleRecorder< T >::GetMaxSamples(), and GlobalHashtablezSampler().
GetHashtablezSampleParameter()
int32_t absl::container_internal::GetHashtablezSampleParameter ()
Definition at line 246 of file hashtablez_sampler.cc.
{
  return g_hashtablez_sample_parameter.load(std::memory_order_acquire);
}
GlobalHashtablezSampler()
HashtablezSampler & absl::container_internal::GlobalHashtablezSampler ()
Definition at line 64 of file hashtablez_sampler.cc.
{
  static auto* sampler = new HashtablezSampler();
  return *sampler;
}
Referenced by GetHashtablezMaxSamples(), SampleSlow(), SetHashtablezMaxSamplesInternal(), and UnsampleSlow().
GrowthToLowerboundCapacity()
size_t absl::container_internal::GrowthToLowerboundCapacity (size_t growth) inline
Definition at line 999 of file raw_hash_set.h.
{
  // `growth*8/7`
  if (Group::kWidth == 8 && growth == 7) {
    // x+(x-1)/7 does not work when x==7.
    return 8;
  }
  return growth + static_cast<size_t>((static_cast<int64_t>(growth) - 1) / 7);
}
References absl::container_internal::GroupPortableImpl::kWidth.
Referenced by absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::LowerBoundAllocatedByteSize(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::rehash(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::reserve(), and SelectBucketCountForIterRange().
GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST()
absl::container_internal::GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST (UniquePtrModifiersTest)
H1()
size_t absl::container_internal::H1 (size_t hash, const ctrl_t * ctrl) inline
Definition at line 509 of file raw_hash_set.h.
{
  return (hash >> 7) ^ PerTableSalt(ctrl);
}
References hash, and PerTableSalt().
Referenced by probe(), and ShouldInsertBackwards().
H2()
h2_t absl::container_internal::H2 (size_t hash) inline
Definition at line 516 of file raw_hash_set.h.
{ return hash & 0x7F; }
References hash.
Referenced by DropDeletesWithoutResize(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find_or_prepare_insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set().
InitializerListBucketAllocTest() [1/2]
template<typename TypeParam > void absl::container_internal::InitializerListBucketAllocTest (std::false_type)
Definition at line 349 of file unordered_map_constructor_test.h.
{}
Referenced by TYPED_TEST_P().
InitializerListBucketAllocTest() [2/2]
template<typename TypeParam > void absl::container_internal::InitializerListBucketAllocTest (std::true_type)
Definition at line 352 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using A = typename TypeParam::allocator_type;
  hash_internal::UniqueGenerator<T> gen;
  std::initializer_list<T> values = {gen(), gen(), gen(), gen(), gen()};
  A alloc(0);
  TypeParam m(values, 123, alloc);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  EXPECT_GE(m.bucket_count(), 123);
}
References alloc, items(), and values.
InitializerListBucketHashAllocTest() [1/2]
template<typename TypeParam > void absl::container_internal::InitializerListBucketHashAllocTest (std::false_type)
Definition at line 369 of file unordered_map_constructor_test.h.
{}
Referenced by TYPED_TEST_P().
InitializerListBucketHashAllocTest() [2/2]
template<typename TypeParam > void absl::container_internal::InitializerListBucketHashAllocTest (std::true_type)
Definition at line 372 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using A = typename TypeParam::allocator_type;
  H hasher;
  A alloc(0);
  hash_internal::UniqueGenerator<T> gen;
  std::initializer_list<T> values = {gen(), gen(), gen(), gen(), gen()};
  TypeParam m(values, 123, hasher, alloc);
  EXPECT_EQ(m.hash_function(), hasher);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  EXPECT_GE(m.bucket_count(), 123);
}
References alloc, hasher, items(), and values.
InitializeSlots()
template<typename Alloc , size_t SizeOfSlot, size_t AlignOfSlot> ABSL_ATTRIBUTE_NOINLINE void absl::container_internal::InitializeSlots (CommonFields & c, Alloc alloc)
Definition at line 1222 of file raw_hash_set.h.
{
  assert(c.capacity_);
  // Folks with custom allocators often make unwarranted assumptions about the
  // behavior of their classes vis-a-vis trivial destructability and what
  // calls they will or won't make.  Avoid sampling for people with custom
  // allocators to get us out of this mess.  This is not a hard guarantee but
  // a workaround while we plan the exact guarantee we want to provide.
  const size_t sample_size =
      (std::is_same<Alloc, std::allocator<char>>::value && c.slots_ == nullptr)
          ? SizeOfSlot
          : 0;
  const size_t cap = c.capacity_;
  char* mem = static_cast<char*>(
      Allocate<AlignOfSlot>(&alloc, AllocSize(cap, SizeOfSlot, AlignOfSlot)));
  const GenerationType old_generation = c.generation();
  c.set_generation_ptr(
      reinterpret_cast<GenerationType*>(mem + GenerationOffset(cap)));
  c.set_generation(old_generation + 1);
  c.control_ = reinterpret_cast<ctrl_t*>(mem);
  c.slots_ = mem + SlotOffset(cap, AlignOfSlot);
  ResetCtrl(c, SizeOfSlot);
  if (sample_size) {
    c.infoz() = Sample(sample_size);
  }
  c.infoz().RecordStorageChanged(c.size_, cap);
}
References alloc, Allocate(), AllocSize(), absl::c, GenerationOffset(), ResetCtrl(), Sample(), and SlotOffset().
InputIteratorBucketAllocTest() [1/2]
template<typename TypeParam > void absl::container_internal::InputIteratorBucketAllocTest (std::false_type)
Definition at line 192 of file unordered_map_constructor_test.h.
{}
Referenced by TYPED_TEST_P().
InputIteratorBucketAllocTest() [2/2]
template<typename TypeParam > void absl::container_internal::InputIteratorBucketAllocTest (std::true_type)
Definition at line 195 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using A = typename TypeParam::allocator_type;
  A alloc(0);
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::UniqueGenerator<T>());
  TypeParam m(values.begin(), values.end(), 123, alloc);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  EXPECT_GE(m.bucket_count(), 123);
}
References alloc, items(), and values.
InputIteratorBucketHashAllocTest() [1/2]
template<typename TypeParam > void absl::container_internal::InputIteratorBucketHashAllocTest (std::false_type)
Definition at line 213 of file unordered_map_constructor_test.h.
{}
Referenced by TYPED_TEST_P().
InputIteratorBucketHashAllocTest() [2/2]
template<typename TypeParam > void absl::container_internal::InputIteratorBucketHashAllocTest (std::true_type)
Definition at line 216 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using A = typename TypeParam::allocator_type;
  H hasher;
  A alloc(0);
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::UniqueGenerator<T>());
  TypeParam m(values.begin(), values.end(), 123, hasher, alloc);
  EXPECT_EQ(m.hash_function(), hasher);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  EXPECT_GE(m.bucket_count(), 123);
}
References alloc, hasher, items(), and values.
is_small()
bool absl::container_internal::is_small (size_t capacity) inline
Definition at line 1106 of file raw_hash_set.h.
{ return capacity < Group::kWidth - 1; }
References absl::container_internal::GroupPortableImpl::kWidth.
Referenced by DropDeletesWithoutResize(), and find_first_non_full().
IsDeleted()
bool absl::container_internal::IsDeleted (ctrl_t c) inline
Definition at line 521 of file raw_hash_set.h.
{ return c == ctrl_t::kDeleted; }
References absl::c, and kDeleted.
Referenced by DropDeletesWithoutResize(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert().
IsEmpty()
bool absl::container_internal::IsEmpty (ctrl_t c) inline
Definition at line 519 of file raw_hash_set.h.
{ return c == ctrl_t::kEmpty; }
References absl::c, and kEmpty.
Referenced by DropDeletesWithoutResize(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert().
IsEmptyOrDeleted()
bool absl::container_internal::IsEmptyOrDeleted (ctrl_t c) inline
Definition at line 522 of file raw_hash_set.h.
{ return c < ctrl_t::kSentinel; }
References absl::c, and kSentinel.
IsFull()
bool absl::container_internal::IsFull (ctrl_t c) inline
Definition at line 520 of file raw_hash_set.h.
{ return c >= static_cast<ctrl_t>(0); }
References absl::c.
Referenced by AssertIsValidForComparison(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::destroy_slots(), EraseMetaOnly(), and SetCtrl().
IsHashtablezEnabled()
bool absl::container_internal::IsHashtablezEnabled ()
Definition at line 233 of file hashtablez_sampler.cc.
{
  return g_hashtablez_enabled.load(std::memory_order_acquire);
}
IsNoThrowSwappable() [1/2]
template<class T > bool absl::container_internal::IsNoThrowSwappable (std::false_type) constexpr
Definition at line 334 of file raw_hash_set.h.
{
  return false;
}
IsNoThrowSwappable() [2/2]
template<class T > bool absl::container_internal::IsNoThrowSwappable (std::true_type = {}) constexpr
Definition at line 329 of file raw_hash_set.h.
                                                 {} /* is_swappable */) {
  using std::swap;
  return noexcept(swap(std::declval<T&>(), std::declval<T&>()));
}
IsValidCapacity()
bool absl::container_internal::IsValidCapacity (size_t n) inline
Definition at line 951 of file raw_hash_set.h.
{ return ((n + 1) & n) == 0 && n > 0; }
References absl::n.
Referenced by CapacityToGrowth(), ConvertDeletedToEmptyAndFullToDeleted(), DropDeletesWithoutResize(), GenerationOffset(), NextCapacity(), and SlotOffset().
items()
template<class Map > auto absl::container_internal::items (const Map & m) -> std::vector< std::pair<typename Map::key_type, typename Map::mapped_type>>
Definition at line 147 of file hash_policy_testing.h.
{
  using std::get;
  std::vector<std::pair<typename Map::key_type, typename Map::mapped_type>> res;
  res.reserve(m.size());
  for (const auto& v : m) res.emplace_back(get<0>(v), get<1>(v));
  return res;
}
References absl::get(), and absl::v.
Referenced by InitializerListBucketAllocTest(), InitializerListBucketHashAllocTest(), InputIteratorBucketAllocTest(), InputIteratorBucketHashAllocTest(), TYPED_TEST_P(), TYPED_TEST_P(), TYPED_TEST_P(), TYPED_TEST_P(), TYPED_TEST_P(), TYPED_TEST_P(), TYPED_TEST_P(), TYPED_TEST_P(), TYPED_TEST_P(), TYPED_TEST_P(), and TYPED_TEST_P().
keys()
template<class Set > auto absl::container_internal::keys (const Set & s) -> std::vector<typename std::decay<typename Set::key_type>::type>
Definition at line 157 of file hash_policy_testing.h.
{
  std::vector<typename std::decay<typename Set::key_type>::type> res;
  res.reserve(s.size());
  for (const auto& v : s) res.emplace_back(v);
  return res;
}
References absl::s, and absl::v.
LowerBoundAllocatedByteSize()
template<typename C > size_t absl::container_internal::LowerBoundAllocatedByteSize (size_t num_elements)
Definition at line 101 of file hashtable_debug.h.
{
  return absl::container_internal::hashtable_debug_internal::
      HashtableDebugAccess<C>::LowerBoundAllocatedByteSize(num_elements);
}
MoveConstructorAllocTest() [1/2]
template<typename TypeParam > void absl::container_internal::MoveConstructorAllocTest (std::false_type)
Definition at line 302 of file unordered_map_constructor_test.h.
{}
Referenced by TYPED_TEST_P().
MoveConstructorAllocTest() [2/2]
template<typename TypeParam > void absl::container_internal::MoveConstructorAllocTest (std::true_type)
Definition at line 305 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  hash_internal::UniqueGenerator<T> gen;
  TypeParam m(123, hasher, equal, alloc);
  for (size_t i = 0; i != 10; ++i) m.insert(gen());
  TypeParam t(m);
  TypeParam n(std::move(t), A(1));
  EXPECT_EQ(m.hash_function(), n.hash_function());
  EXPECT_EQ(m.key_eq(), n.key_eq());
  EXPECT_NE(m.get_allocator(), n.get_allocator());
  EXPECT_EQ(m, n);
}
References absl::A, alloc, absl::E, absl::equal(), hasher, absl::i, and absl::n.
NextCapacity()
size_t absl::container_internal::NextCapacity (size_t n) inline
Definition at line 954 of file raw_hash_set.h.
{
  assert(IsValidCapacity(n) || n == 0);
  return n * 2 + 1;
}
References IsValidCapacity(), and absl::n.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert().
NormalizeCapacity()
size_t absl::container_internal::NormalizeCapacity (size_t n) inline
Definition at line 970 of file raw_hash_set.h.
{
  return n ? ~size_t{} >> countl_zero(n) : 1;
}
References absl::countl_zero(), and absl::n.
Referenced by absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::LowerBoundAllocatedByteSize(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::rehash(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::reserve().
NumClonedBytes()
size_t absl::container_internal::NumClonedBytes () constexpr
Definition at line 943 of file raw_hash_set.h.
{ return Group::kWidth - 1; }
References absl::container_internal::GroupPortableImpl::kWidth.
Referenced by ConvertDeletedToEmptyAndFullToDeleted(), GenerationOffset(), ResetCtrl(), SetCtrl(), and SlotOffset().
NumGenerationBytes()
size_t absl::container_internal::NumGenerationBytes () constexpr
Definition at line 243 of file raw_hash_set.h.
{ return 0; }
Referenced by SlotOffset().
PairArgs() [1/5]
std::pair< std::tuple<>, std::tuple<> > absl::container_internal::PairArgs () inline
Definition at line 179 of file container_memory.h.
{ return {}; }
References PairArgs().
Referenced by DecomposePair(), PairArgs(), PairArgs(), PairArgs(), PairArgs(), and PairArgs().
PairArgs() [2/5]
template<class F , class S > std::pair< std::tuple< const F & >, std::tuple< const S & > > absl::container_internal::PairArgs (const std::pair< F, S > & p)
Definition at line 186 of file container_memory.h.
{
  return PairArgs(p.first, p.second);
}
References absl::p, and PairArgs().
PairArgs() [3/5]
template<class F , class S > std::pair< std::tuple< F && >, std::tuple< S && > > absl::container_internal::PairArgs (F && f, S && s)
Definition at line 181 of file container_memory.h.
{
  return {std::piecewise_construct, std::forward_as_tuple(std::forward<F>(f)),
          std::forward_as_tuple(std::forward<S>(s))};
}
References absl::f, PairArgs(), and absl::s.
PairArgs() [4/5]
template<class F , class S > std::pair< std::tuple< F && >, std::tuple< S && > > absl::container_internal::PairArgs (std::pair< F, S > && p)
Definition at line 191 of file container_memory.h.
{
  return PairArgs(std::forward<F>(p.first), std::forward<S>(p.second));
}
References absl::p, and PairArgs().
PairArgs() [5/5]
template<class F , class S > auto absl::container_internal::PairArgs (std::piecewise_construct_t , F && f, S && s) -> decltype(std::make_pair(memory_internal::TupleRef(std::forward<F>(f)), memory_internal::TupleRef(std::forward<S>(s))))
Definition at line 195 of file container_memory.h.
{
  return std::make_pair(memory_internal::TupleRef(std::forward<F>(f)),
                        memory_internal::TupleRef(std::forward<S>(s)));
}
References absl::f, PairArgs(), and absl::s.
PerTableSalt()
size_t absl::container_internal::PerTableSalt (const ctrl_t * ctrl) inline
Definition at line 502 of file raw_hash_set.h.
{
  // The low bits of the pointer have little or no entropy because of
  // alignment. We shift the pointer to try to use higher entropy bits. A
  // good number seems to be 12 bits, because that aligns with page size.
  return reinterpret_cast<uintptr_t>(ctrl) >> 12;
}
Referenced by H1().
probe()
probe_seq< Group::kWidth > absl::container_internal::probe (const CommonFields & common, size_t hash) inline
Definition at line 1109 of file raw_hash_set.h.
{
  const ctrl_t* ctrl = common.control_;
  const size_t capacity = common.capacity_;
  return probe_seq<Group::kWidth>(H1(hash, ctrl), capacity);
}
References absl::container_internal::CommonFields::capacity_, absl::container_internal::CommonFields::control_, H1(), and hash.
Referenced by DropDeletesWithoutResize(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), find_first_non_full(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find_or_prepare_insert(), absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::GetNumProbes(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prefetch().
RandomSeed()
size_t absl::container_internal::RandomSeed () inline
Definition at line 43 of file raw_hash_set.cc.
{
#ifdef ABSL_HAVE_THREAD_LOCAL
  static thread_local size_t counter = 0;
  size_t value = ++counter;
#else   // ABSL_HAVE_THREAD_LOCAL
  static std::atomic<size_t> counter(0);
  size_t value = counter.fetch_add(1, std::memory_order_relaxed);
#endif  // ABSL_HAVE_THREAD_LOCAL
  return value ^ static_cast<size_t>(reinterpret_cast<uintptr_t>(&counter));
}
References counter.
Referenced by ShouldInsertBackwards().
RecordClearedReservationSlow()
void absl::container_internal::RecordClearedReservationSlow (HashtablezInfo * info)
Definition at line 184 of file hashtablez_sampler.cc.
{
  info->max_reserve.store(0, std::memory_order_relaxed);
}
RecordEraseSlow()
void absl::container_internal::RecordEraseSlow (HashtablezInfo * info)
Definition at line 221 of file hashtablez_sampler.cc.
{
  info->size.fetch_sub(1, std::memory_order_relaxed);
  // There is only one concurrent writer, so `load` then `store` is sufficient
  // instead of using `fetch_add`.
  info->num_erases.store(1 + info->num_erases.load(std::memory_order_relaxed),
                         std::memory_order_relaxed);
}
RecordInsertSlow()
void absl::container_internal::RecordInsertSlow (HashtablezInfo * info, size_t hash, size_t distance_from_desired)
Definition at line 199 of file hashtablez_sampler.cc.
{
  // SwissTables probe in groups of 16, so scale this to count items probes and
  // not offset from desired.
  size_t probe_length = distance_from_desired;
#ifdef ABSL_INTERNAL_HAVE_SSE2
  probe_length /= 16;
#else
  probe_length /= 8;
#endif
  info->hashes_bitwise_and.fetch_and(hash, std::memory_order_relaxed);
  info->hashes_bitwise_or.fetch_or(hash, std::memory_order_relaxed);
  info->hashes_bitwise_xor.fetch_xor(hash, std::memory_order_relaxed);
  info->max_probe_length.store(
      std::max(info->max_probe_length.load(std::memory_order_relaxed),
               probe_length),
      std::memory_order_relaxed);
  info->total_probe_length.fetch_add(probe_length, std::memory_order_relaxed);
  info->size.fetch_add(1, std::memory_order_relaxed);
}
References hash.
RecordRehashSlow()
void absl::container_internal::RecordRehashSlow (HashtablezInfo * info, size_t total_probe_length)
Definition at line 162 of file hashtablez_sampler.cc.
{
#ifdef ABSL_INTERNAL_HAVE_SSE2
  total_probe_length /= 16;
#else
  total_probe_length /= 8;
#endif
  info->total_probe_length.store(total_probe_length, std::memory_order_relaxed);
  info->num_erases.store(0, std::memory_order_relaxed);
  // There is only one concurrent writer, so `load` then `store` is sufficient
  // instead of using `fetch_add`.
  info->num_rehashes.store(
      1 + info->num_rehashes.load(std::memory_order_relaxed),
      std::memory_order_relaxed);
}
RecordReservationSlow()
void absl::container_internal::RecordReservationSlow (HashtablezInfo * info, size_t target_capacity)
Definition at line 177 of file hashtablez_sampler.cc.
{
  info->max_reserve.store(
      (std::max)(info->max_reserve.load(std::memory_order_relaxed),
                 target_capacity),
      std::memory_order_relaxed);
}
RecordStorageChangedSlow()
void absl::container_internal::RecordStorageChangedSlow (HashtablezInfo * info, size_t size, size_t capacity)
Definition at line 188 of file hashtablez_sampler.cc.
{
  info->size.store(size, std::memory_order_relaxed);
  info->capacity.store(capacity, std::memory_order_relaxed);
  if (size == 0) {
    // This is a clear, reset the total/num_erases too.
    info->total_probe_length.store(0, std::memory_order_relaxed);
    info->num_erases.store(0, std::memory_order_relaxed);
  }
}
References size.
REGISTER_TYPED_TEST_SUITE_P() [1/8]
absl::container_internal::REGISTER_TYPED_TEST_SUITE_P (ConstructorTest , NoArgs , BucketCount , BucketCountHash , BucketCountHashEqual , BucketCountHashEqualAlloc , BucketCountAlloc , BucketCountHashAlloc , Alloc , InputIteratorBucketHashEqualAlloc , InputIteratorBucketAlloc , InputIteratorBucketHashAlloc , CopyConstructor , CopyConstructorAlloc , MoveConstructor , MoveConstructorAlloc , InitializerListBucketHashEqualAlloc , InitializerListBucketAlloc , InitializerListBucketHashAlloc , Assignment , MoveAssignment , AssignmentFromInitializerList , AssignmentOverwritesExisting , MoveAssignmentOverwritesExisting , AssignmentFromInitializerListOverwritesExisting , AssignmentOnSelf)
REGISTER_TYPED_TEST_SUITE_P() [2/8]
absl::container_internal::REGISTER_TYPED_TEST_SUITE_P (ConstructorTest , NoArgs , BucketCount , BucketCountHash , BucketCountHashEqual , BucketCountHashEqualAlloc , BucketCountAlloc , BucketCountHashAlloc , Alloc , InputIteratorBucketHashEqualAlloc , InputIteratorBucketAlloc , InputIteratorBucketHashAlloc , CopyConstructor , CopyConstructorAlloc , MoveConstructor , MoveConstructorAlloc , InitializerListBucketHashEqualAlloc , InitializerListBucketAlloc , InitializerListBucketHashAlloc , CopyAssignment , MoveAssignment , AssignmentFromInitializerList , AssignmentOverwritesExisting , MoveAssignmentOverwritesExisting , AssignmentFromInitializerListOverwritesExisting , AssignmentOnSelf)
REGISTER_TYPED_TEST_SUITE_P() [3/8]
absl::container_internal::REGISTER_TYPED_TEST_SUITE_P (LookupTest , At , OperatorBracket , Count , Find , EqualRange)
REGISTER_TYPED_TEST_SUITE_P() [4/8]
absl::container_internal::REGISTER_TYPED_TEST_SUITE_P (LookupTest , Count , Find , EqualRange)
REGISTER_TYPED_TEST_SUITE_P() [5/8]
absl::container_internal::REGISTER_TYPED_TEST_SUITE_P (MembersTest , Typedefs , SimpleFunctions , BeginEnd)
REGISTER_TYPED_TEST_SUITE_P() [6/8]
absl::container_internal::REGISTER_TYPED_TEST_SUITE_P (ModifiersTest , Clear , Insert , InsertHint , InsertRange , InsertWithinCapacity , InsertRangeWithinCapacity , Emplace , EmplaceHint , Erase , EraseRange , EraseKey , Swap)
REGISTER_TYPED_TEST_SUITE_P() [7/8]
absl::container_internal::REGISTER_TYPED_TEST_SUITE_P (ModifiersTest , Clear , Insert , InsertHint , InsertRange , InsertWithinCapacity , InsertRangeWithinCapacity , InsertOrAssign , InsertOrAssignHint , Emplace , EmplaceHint , TryEmplace , TryEmplaceHint , Erase , EraseRange , EraseKey , Swap)
REGISTER_TYPED_TEST_SUITE_P() [8/8]
absl::container_internal::REGISTER_TYPED_TEST_SUITE_P (UniquePtrModifiersTest , TryEmplace)
ResetCtrl()
void absl::container_internal::ResetCtrl (CommonFields & common, size_t slot_size) inline
Definition at line 1161 of file raw_hash_set.h.
{
  const size_t capacity = common.capacity_;
  ctrl_t* ctrl = common.control_;
  std::memset(ctrl, static_cast<int8_t>(ctrl_t::kEmpty),
              capacity + 1 + NumClonedBytes());
  ctrl[capacity] = ctrl_t::kSentinel;
  SanitizerPoisonMemoryRegion(common.slots_, slot_size * capacity);
  ResetGrowthLeft(common);
}
References absl::container_internal::CommonFields::capacity_, absl::container_internal::CommonFields::control_, kEmpty, kSentinel, NumClonedBytes(), ResetGrowthLeft(), SanitizerPoisonMemoryRegion(), and absl::container_internal::CommonFields::slots_.
Referenced by ClearBackingArray(), and InitializeSlots().
ResetGrowthLeft()
void absl::container_internal::ResetGrowthLeft (CommonFields & common) inline
Definition at line 1155 of file raw_hash_set.h.
{
  common.growth_left() = CapacityToGrowth(common.capacity_) - common.size_;
}
References absl::container_internal::CommonFields::capacity_, CapacityToGrowth(), absl::container_internal::CommonFields::growth_left(), and absl::container_internal::CommonFields::size_.
Referenced by DropDeletesWithoutResize(), and ResetCtrl().
Sample()
HashtablezInfoHandle absl::container_internal::Sample (size_t inline_element_size ABSL_ATTRIBUTE_UNUSED) inline
Definition at line 219 of file hashtablez_sampler.h.
{
#if defined(ABSL_INTERNAL_HASHTABLEZ_SAMPLE)
  if (ABSL_PREDICT_TRUE(--global_next_sample.next_sample > 0)) {
    return HashtablezInfoHandle(nullptr);
  }
  return HashtablezInfoHandle(
      SampleSlow(global_next_sample, inline_element_size));
#else
  return HashtablezInfoHandle(nullptr);
#endif  // !ABSL_PER_THREAD_TLS
}
References ABSL_PREDICT_TRUE, and SampleSlow().
Referenced by InitializeSlots().
SampleSlow()
HashtablezInfo * absl::container_internal::SampleSlow (SamplingState & next_sample, size_t inline_element_size)
Definition at line 115 of file hashtablez_sampler.cc.
{
  if (ABSL_PREDICT_FALSE(ShouldForceSampling())) {
    next_sample.next_sample = 1;
    const int64_t old_stride = exchange(next_sample.sample_stride, 1);
    HashtablezInfo* result =
        GlobalHashtablezSampler().Register(old_stride, inline_element_size);
    return result;
  }
#if !defined(ABSL_INTERNAL_HASHTABLEZ_SAMPLE)
  next_sample = {
      std::numeric_limits<int64_t>::max(),
      std::numeric_limits<int64_t>::max(),
  };
  return nullptr;
#else
  bool first = next_sample.next_sample < 0;
  const int64_t next_stride = g_exponential_biased_generator.GetStride(
      g_hashtablez_sample_parameter.load(std::memory_order_relaxed));
  next_sample.next_sample = next_stride;
  const int64_t old_stride = exchange(next_sample.sample_stride, next_stride);
  // Small values of interval are equivalent to just sampling next time.
  ABSL_ASSERT(next_stride >= 1);
  // g_hashtablez_enabled can be dynamically flipped, we need to set a threshold
  // low enough that we will start sampling in a reasonable time, so we just use
  // the default sampling rate.
  if (!g_hashtablez_enabled.load(std::memory_order_relaxed)) return nullptr;
  // We will only be negative on our first count, so we should just retry in
  // that case.
  if (first) {
    if (ABSL_PREDICT_TRUE(--next_sample.next_sample > 0)) return nullptr;
    return SampleSlow(next_sample, inline_element_size);
  }
  return GlobalHashtablezSampler().Register(old_stride, inline_element_size);
#endif
}
References ABSL_ASSERT, ABSL_PREDICT_FALSE, ABSL_PREDICT_TRUE, absl::exchange(), first, GlobalHashtablezSampler(), absl::container_internal::SamplingState::next_sample, absl::profiling_internal::SampleRecorder< T >::Register(), absl::container_internal::SamplingState::sample_stride, and SampleSlow().
Referenced by Sample(), and SampleSlow().
SanitizerPoisonMemoryRegion()
void absl::container_internal::SanitizerPoisonMemoryRegion (const void * m, size_t s) inline
Definition at line 220 of file container_memory.h.
{
#ifdef ABSL_HAVE_ADDRESS_SANITIZER
  ASAN_POISON_MEMORY_REGION(m, s);
#endif
#ifdef ABSL_HAVE_MEMORY_SANITIZER
  __msan_poison(m, s);
#endif
  (void)m;
  (void)s;
}
References absl::s, and SanitizerPoisonMemoryRegion().
Referenced by ResetCtrl(), SanitizerPoisonMemoryRegion(), SanitizerPoisonObject(), and SetCtrl().
SanitizerPoisonObject()
template<typename T > void absl::container_internal::SanitizerPoisonObject (const T * object) inline
Definition at line 243 of file container_memory.h.
{
  SanitizerPoisonMemoryRegion(object, sizeof(T));
}
References SanitizerPoisonMemoryRegion(), and SanitizerPoisonObject().
Referenced by SanitizerPoisonObject().
SanitizerUnpoisonMemoryRegion()
void absl::container_internal::SanitizerUnpoisonMemoryRegion (const void * m, size_t s) inline
Definition at line 231 of file container_memory.h.
{
#ifdef ABSL_HAVE_ADDRESS_SANITIZER
  ASAN_UNPOISON_MEMORY_REGION(m, s);
#endif
#ifdef ABSL_HAVE_MEMORY_SANITIZER
  __msan_unpoison(m, s);
#endif
  (void)m;
  (void)s;
}
References absl::s, and SanitizerUnpoisonMemoryRegion().
Referenced by DeallocateStandard(), SanitizerUnpoisonMemoryRegion(), SanitizerUnpoisonObject(), SetCtrl(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::~raw_hash_set().
SanitizerUnpoisonObject()
template<typename T > void absl::container_internal::SanitizerUnpoisonObject (const T * object) inline
Definition at line 248 of file container_memory.h.
{
  SanitizerUnpoisonMemoryRegion(object, sizeof(T));
}
References SanitizerUnpoisonMemoryRegion(), and SanitizerUnpoisonObject().
Referenced by SanitizerUnpoisonObject().
SelectBucketCountForIterRange()
template<class InputIter > size_t absl::container_internal::SelectBucketCountForIterRange (InputIter first, InputIter last, size_t bucket_count)
Definition at line 1009 of file raw_hash_set.h.
{
  if (bucket_count != 0) {
    return bucket_count;
  }
  using InputIterCategory =
      typename std::iterator_traits<InputIter>::iterator_category;
  if (std::is_base_of<std::random_access_iterator_tag,
                      InputIterCategory>::value) {
    return GrowthToLowerboundCapacity(
        static_cast<size_t>(std::distance(first, last)));
  }
  return 0;
}
References first, and GrowthToLowerboundCapacity().
SetCtrl() [1/2]
void absl::container_internal::SetCtrl (const CommonFields & common, size_t i, ctrl_t h, size_t slot_size) inline
Definition at line 1175 of file raw_hash_set.h.
{
  const size_t capacity = common.capacity_;
  assert(i < capacity);
  auto* slot_i = static_cast<const char*>(common.slots_) + i * slot_size;
  if (IsFull(h)) {
    SanitizerUnpoisonMemoryRegion(slot_i, slot_size);
  } else {
    SanitizerPoisonMemoryRegion(slot_i, slot_size);
  }
  ctrl_t* ctrl = common.control_;
  ctrl[i] = h;
  ctrl[((i - NumClonedBytes()) & capacity) + (NumClonedBytes() & capacity)] = h;
}
References absl::container_internal::CommonFields::capacity_, absl::container_internal::CommonFields::control_, absl::i, IsFull(), NumClonedBytes(), SanitizerPoisonMemoryRegion(), SanitizerUnpoisonMemoryRegion(), and absl::container_internal::CommonFields::slots_.
Referenced by DropDeletesWithoutResize(), EraseMetaOnly(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prepare_insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set(), and SetCtrl().
SetCtrl() [2/2]
void absl::container_internal::SetCtrl (const CommonFields & common, size_t i, h2_t h, size_t slot_size) inline
Definition at line 1193 of file raw_hash_set.h.
{
  SetCtrl(common, i, static_cast<ctrl_t>(h), slot_size);
}
References absl::i, and SetCtrl().
SetHashtablezConfigListener()
void absl::container_internal::SetHashtablezConfigListener (HashtablezConfigListener l)
Definition at line 229 of file hashtablez_sampler.cc.
{
  g_hashtablez_config_listener.store(l, std::memory_order_release);
}
SetHashtablezEnabled()
void absl::container_internal::SetHashtablezEnabled (bool enabled)
Definition at line 237 of file hashtablez_sampler.cc.
{
  SetHashtablezEnabledInternal(enabled);
  TriggerHashtablezConfigListener();
}
References SetHashtablezEnabledInternal().
SetHashtablezEnabledInternal()
void absl::container_internal::SetHashtablezEnabledInternal (bool enabled)
Definition at line 242 of file hashtablez_sampler.cc.
{
  g_hashtablez_enabled.store(enabled, std::memory_order_release);
}
Referenced by SetHashtablezEnabled().
SetHashtablezMaxSamples()
void absl::container_internal::SetHashtablezMaxSamples (size_t max)
Definition at line 268 of file hashtablez_sampler.cc.
{
  SetHashtablezMaxSamplesInternal(max);
  TriggerHashtablezConfigListener();
}
References SetHashtablezMaxSamplesInternal().
SetHashtablezMaxSamplesInternal()
void absl::container_internal::SetHashtablezMaxSamplesInternal (size_t max)
Definition at line 273 of file hashtablez_sampler.cc.
{
  if (max > 0) {
    GlobalHashtablezSampler().SetMaxSamples(max);
  } else {
    ABSL_RAW_LOG(ERROR, "Invalid hashtablez max samples: 0");
  }
}
References ABSL_RAW_LOG, GlobalHashtablezSampler(), and absl::profiling_internal::SampleRecorder< T >::SetMaxSamples().
Referenced by SetHashtablezMaxSamples().
SetHashtablezSampleParameter()
void absl::container_internal::SetHashtablezSampleParameter (int32_t rate)
Definition at line 250 of file hashtablez_sampler.cc.
{
  SetHashtablezSampleParameterInternal(rate);
  TriggerHashtablezConfigListener();
}
References SetHashtablezSampleParameterInternal().
SetHashtablezSampleParameterInternal()
void absl::container_internal::SetHashtablezSampleParameterInternal (int32_t rate)
Definition at line 255 of file hashtablez_sampler.cc.
{
  if (rate > 0) {
    g_hashtablez_sample_parameter.store(rate, std::memory_order_release);
  } else {
    ABSL_RAW_LOG(ERROR, "Invalid hashtablez sample rate: %lld",
                 static_cast<long long>(rate));  // NOLINT(runtime/int)
  }
}
References ABSL_RAW_LOG.
Referenced by SetHashtablezSampleParameter().
ShouldInsertBackwards()
bool absl::container_internal::ShouldInsertBackwards (size_t hash, const ctrl_t * ctrl)
Definition at line 54 of file raw_hash_set.cc.
{
  // To avoid problems with weak hashes and single bit tests, we use % 13.
  // TODO(kfm,sbenza): revisit after we do unconditional mixing
  return (H1(hash, ctrl) ^ RandomSeed()) % 13 > 6;
}
References H1(), hash, and RandomSeed().
Referenced by find_first_non_full().
SlotOffset()
size_t absl::container_internal::SlotOffset (size_t capacity, size_t slot_align) inline
Definition at line 1208 of file raw_hash_set.h.
{
  assert(IsValidCapacity(capacity));
  const size_t num_control_bytes = capacity + 1 + NumClonedBytes();
  return (num_control_bytes + NumGenerationBytes() + slot_align - 1) &
         (~slot_align + 1);
}
References IsValidCapacity(), NumClonedBytes(), and NumGenerationBytes().
Referenced by AllocSize(), and InitializeSlots().
SwapAlloc() [1/2]
template<typename AllocType > void absl::container_internal::SwapAlloc (AllocType & , AllocType & , std::false_type)
Definition at line 253 of file raw_hash_set.h.
                                {}
SwapAlloc() [2/2]
template<typename AllocType > void absl::container_internal::SwapAlloc (AllocType & lhs, AllocType & rhs, std::true_type)
Definition at line 247 of file raw_hash_set.h.
{
  using std::swap;
  swap(lhs, rhs);
}
References absl::swap().
SwisstableGenerationsEnabled()
bool absl::container_internal::SwisstableGenerationsEnabled () constexpr
Definition at line 242 of file raw_hash_set.h.
{ return false; }
Referenced by AssertIsValidForComparison().
TrailingZeros()
template<typename T > uint32_t absl::container_internal::TrailingZeros (T x)
Definition at line 339 of file raw_hash_set.h.
{
  ABSL_ASSUME(x != 0);
  return static_cast<uint32_t>(countr_zero(x));
}
References ABSL_ASSUME, absl::countr_zero(), and absl::x.
Referenced by absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::LowestBitSet(), and absl::container_internal::NonIterableBitMask< T, SignificantBits, Shift >::TrailingZeros().
TransferRelocatable()
template<size_t SizeOfSlot> ABSL_ATTRIBUTE_NOINLINE void absl::container_internal::TransferRelocatable (void * , void * dst, void * src)
Definition at line 1298 of file raw_hash_set.h.
{
  memcpy(dst, src, SizeOfSlot);
}
TYPED_TEST_P() [1/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , Alloc)
Definition at line 168 of file unordered_map_constructor_test.h.
{
  AllocTest<TypeParam>(expect_alloc_constructors<TypeParam>());
}
References AllocTest().
TYPED_TEST_P() [2/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , Assignment)
Definition at line 391 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  hash_internal::UniqueGenerator<T> gen;
  TypeParam m({gen(), gen(), gen()}, 123, hasher, equal, alloc);
  TypeParam n;
  n = m;
  EXPECT_EQ(m.hash_function(), n.hash_function());
  EXPECT_EQ(m.key_eq(), n.key_eq());
  EXPECT_EQ(m, n);
}
References alloc, absl::E, absl::equal(), hasher, and absl::n.
TYPED_TEST_P() [3/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , AssignmentFromInitializerList)
Definition at line 429 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  hash_internal::UniqueGenerator<T> gen;
  std::initializer_list<T> values = {gen(), gen(), gen(), gen(), gen()};
  TypeParam m;
  m = values;
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
}
References items(), and values.
TYPED_TEST_P() [4/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , AssignmentFromInitializerListOverwritesExisting)
Definition at line 457 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  hash_internal::UniqueGenerator<T> gen;
  std::initializer_list<T> values = {gen(), gen(), gen(), gen(), gen()};
  TypeParam m;
  m = values;
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
}
References items(), and values.
TYPED_TEST_P() [5/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , AssignmentOnSelf)
Definition at line 466 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  hash_internal::UniqueGenerator<T> gen;
  std::initializer_list<T> values = {gen(), gen(), gen(), gen(), gen()};
  TypeParam m(values);
  m = *&m;  // Avoid -Wself-assign
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
}
References items(), and values.
TYPED_TEST_P() [6/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , AssignmentOverwritesExisting)
Definition at line 438 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  hash_internal::UniqueGenerator<T> gen;
  TypeParam m({gen(), gen(), gen()});
  TypeParam n({gen()});
  n = m;
  EXPECT_EQ(m, n);
}
References absl::n.
TYPED_TEST_P() [7/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , BucketCount)
Definition at line 42 of file unordered_map_constructor_test.h.
{
  TypeParam m(123);
  EXPECT_TRUE(m.empty());
  EXPECT_THAT(m, ::testing::UnorderedElementsAre());
  EXPECT_GE(m.bucket_count(), 123);
}
TYPED_TEST_P() [8/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , BucketCountAlloc)
Definition at line 119 of file unordered_map_constructor_test.h.
{
  BucketCountAllocTest<TypeParam>(expect_cxx14_apis<TypeParam>());
}
References BucketCountAllocTest().
TYPED_TEST_P() [9/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , BucketCountHash)
Definition at line 49 of file unordered_map_constructor_test.h.
{
  using H = typename TypeParam::hasher;
  H hasher;
  TypeParam m(123, hasher);
  EXPECT_EQ(m.hash_function(), hasher);
  EXPECT_TRUE(m.empty());
  EXPECT_THAT(m, ::testing::UnorderedElementsAre());
  EXPECT_GE(m.bucket_count(), 123);
}
References hasher.
TYPED_TEST_P() [10/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , BucketCountHashAlloc)
Definition at line 140 of file unordered_map_constructor_test.h.
{
  BucketCountHashAllocTest<TypeParam>(expect_cxx14_apis<TypeParam>());
}
References BucketCountHashAllocTest().
TYPED_TEST_P() [11/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , BucketCountHashEqual)
Definition at line 59 of file unordered_map_constructor_test.h.
{
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  H hasher;
  E equal;
  TypeParam m(123, hasher, equal);
  EXPECT_EQ(m.hash_function(), hasher);
  EXPECT_EQ(m.key_eq(), equal);
  EXPECT_TRUE(m.empty());
  EXPECT_THAT(m, ::testing::UnorderedElementsAre());
  EXPECT_GE(m.bucket_count(), 123);
}
References absl::E, absl::equal(), and hasher.
TYPED_TEST_P() [12/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , BucketCountHashEqualAlloc)
Definition at line 72 of file unordered_map_constructor_test.h.
{
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  TypeParam m(123, hasher, equal, alloc);
  EXPECT_EQ(m.hash_function(), hasher);
  EXPECT_EQ(m.key_eq(), equal);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_TRUE(m.empty());
  EXPECT_THAT(m, ::testing::UnorderedElementsAre());
  EXPECT_GE(m.bucket_count(), 123);
}
References alloc, absl::E, absl::equal(), and hasher.
TYPED_TEST_P() [13/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , CopyAssignment)
Definition at line 397 of file unordered_set_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  hash_internal::Generator<T> gen;
  TypeParam m({gen(), gen(), gen()}, 123, hasher, equal, alloc);
  TypeParam n;
  n = m;
  EXPECT_EQ(m.hash_function(), n.hash_function());
  EXPECT_EQ(m.key_eq(), n.key_eq());
  EXPECT_EQ(m, n);
}
References alloc, absl::E, absl::equal(), hasher, and absl::n.
TYPED_TEST_P() [14/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , CopyConstructor)
Definition at line 236 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  hash_internal::UniqueGenerator<T> gen;
  TypeParam m(123, hasher, equal, alloc);
  for (size_t i = 0; i != 10; ++i) m.insert(gen());
  TypeParam n(m);
  EXPECT_EQ(m.hash_function(), n.hash_function());
  EXPECT_EQ(m.key_eq(), n.key_eq());
  EXPECT_EQ(m.get_allocator(), n.get_allocator());
  EXPECT_EQ(m, n);
}
References alloc, absl::E, absl::equal(), hasher, absl::i, and absl::n.
TYPED_TEST_P() [15/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , CopyConstructorAlloc)
Definition at line 276 of file unordered_map_constructor_test.h.
{
  CopyConstructorAllocTest<TypeParam>(expect_alloc_constructors<TypeParam>());
}
References CopyConstructorAllocTest().
TYPED_TEST_P() [16/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , InitializerListBucketAlloc)
Definition at line 364 of file unordered_map_constructor_test.h.
{
  InitializerListBucketAllocTest<TypeParam>(expect_cxx14_apis<TypeParam>());
}
References InitializerListBucketAllocTest().
TYPED_TEST_P() [17/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , InitializerListBucketHashAlloc)
Definition at line 387 of file unordered_map_constructor_test.h.
{
  InitializerListBucketHashAllocTest<TypeParam>(expect_cxx14_apis<TypeParam>());
}
References InitializerListBucketHashAllocTest().
TYPED_TEST_P() [18/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , InitializerListBucketHashEqualAlloc)
Definition at line 330 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  hash_internal::UniqueGenerator<T> gen;
  std::initializer_list<T> values = {gen(), gen(), gen(), gen(), gen()};
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  TypeParam m(values, 123, hasher, equal, alloc);
  EXPECT_EQ(m.hash_function(), hasher);
  EXPECT_EQ(m.key_eq(), equal);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  EXPECT_GE(m.bucket_count(), 123);
}
References alloc, absl::E, absl::equal(), hasher, items(), and values.
TYPED_TEST_P() [19/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , InputIteratorBucketAlloc)
Definition at line 208 of file unordered_map_constructor_test.h.
{
  InputIteratorBucketAllocTest<TypeParam>(expect_cxx14_apis<TypeParam>());
}
References InputIteratorBucketAllocTest().
TYPED_TEST_P() [20/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , InputIteratorBucketHashAlloc)
Definition at line 232 of file unordered_map_constructor_test.h.
{
  InputIteratorBucketHashAllocTest<TypeParam>(expect_cxx14_apis<TypeParam>());
}
References InputIteratorBucketHashAllocTest().
TYPED_TEST_P() [21/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , InputIteratorBucketHashEqualAlloc)
Definition at line 172 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::UniqueGenerator<T>());
  TypeParam m(values.begin(), values.end(), 123, hasher, equal, alloc);
  EXPECT_EQ(m.hash_function(), hasher);
  EXPECT_EQ(m.key_eq(), equal);
  EXPECT_EQ(m.get_allocator(), alloc);
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  EXPECT_GE(m.bucket_count(), 123);
}
References alloc, absl::E, absl::equal(), hasher, items(), and values.
TYPED_TEST_P() [22/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , MoveAssignment)
Definition at line 411 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  hash_internal::UniqueGenerator<T> gen;
  TypeParam m({gen(), gen(), gen()}, 123, hasher, equal, alloc);
  TypeParam t(m);
  TypeParam n;
  n = std::move(t);
  EXPECT_EQ(m.hash_function(), n.hash_function());
  EXPECT_EQ(m.key_eq(), n.key_eq());
  EXPECT_EQ(m, n);
}
References alloc, absl::E, absl::equal(), hasher, and absl::n.
TYPED_TEST_P() [23/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , MoveAssignmentOverwritesExisting)
Definition at line 447 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  hash_internal::UniqueGenerator<T> gen;
  TypeParam m({gen(), gen(), gen()});
  TypeParam t(m);
  TypeParam n({gen()});
  n = std::move(t);
  EXPECT_EQ(m, n);
}
References absl::n.
TYPED_TEST_P() [24/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , MoveConstructor)
Definition at line 282 of file unordered_map_constructor_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using H = typename TypeParam::hasher;
  using E = typename TypeParam::key_equal;
  using A = typename TypeParam::allocator_type;
  H hasher;
  E equal;
  A alloc(0);
  hash_internal::UniqueGenerator<T> gen;
  TypeParam m(123, hasher, equal, alloc);
  for (size_t i = 0; i != 10; ++i) m.insert(gen());
  TypeParam t(m);
  TypeParam n(std::move(t));
  EXPECT_EQ(m.hash_function(), n.hash_function());
  EXPECT_EQ(m.key_eq(), n.key_eq());
  EXPECT_EQ(m.get_allocator(), n.get_allocator());
  EXPECT_EQ(m, n);
}
References alloc, absl::E, absl::equal(), hasher, absl::i, and absl::n.
TYPED_TEST_P() [25/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , MoveConstructorAlloc)
Definition at line 324 of file unordered_map_constructor_test.h.
{
  MoveConstructorAllocTest<TypeParam>(expect_alloc_constructors<TypeParam>());
}
References MoveConstructorAllocTest().
TYPED_TEST_P() [26/51]
absl::container_internal::TYPED_TEST_P (ConstructorTest , NoArgs)
Definition at line 36 of file unordered_map_constructor_test.h.
{
  TypeParam m;
  EXPECT_TRUE(m.empty());
  EXPECT_THAT(m, ::testing::UnorderedElementsAre());
}
TYPED_TEST_P() [27/51]
absl::container_internal::TYPED_TEST_P (LookupTest , At)
Definition at line 32 of file unordered_map_lookup_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m(values.begin(), values.end());
  for (const auto& p : values) {
    const auto& val = m.at(p.first);
    EXPECT_EQ(p.second, val) << ::testing::PrintToString(p.first);
  }
}
References absl::p, and values.
TYPED_TEST_P() [28/51]
absl::container_internal::TYPED_TEST_P (LookupTest , Count)
Definition at line 60 of file unordered_map_lookup_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m;
  for (const auto& p : values)
    EXPECT_EQ(0, m.count(p.first)) << ::testing::PrintToString(p.first);
  m.insert(values.begin(), values.end());
  for (const auto& p : values)
    EXPECT_EQ(1, m.count(p.first)) << ::testing::PrintToString(p.first);
}
References absl::p, and values.
TYPED_TEST_P() [29/51]
absl::container_internal::TYPED_TEST_P (LookupTest , EqualRange)
Definition at line 91 of file unordered_map_lookup_test.h.
{
  using std::get;
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m;
  for (const auto& p : values) {
    auto r = m.equal_range(p.first);
    ASSERT_EQ(0, std::distance(r.first, r.second));
  }
  m.insert(values.begin(), values.end());
  for (const auto& p : values) {
    auto r = m.equal_range(p.first);
    ASSERT_EQ(1, std::distance(r.first, r.second));
    EXPECT_EQ(p.second, get<1>(*r.first)) << ::testing::PrintToString(p.first);
  }
}
References absl::p, r, and values.
TYPED_TEST_P() [30/51]
absl::container_internal::TYPED_TEST_P (LookupTest , Find)
Definition at line 73 of file unordered_map_lookup_test.h.
{
  using std::get;
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m;
  for (const auto& p : values)
    EXPECT_TRUE(m.end() == m.find(p.first))
        << ::testing::PrintToString(p.first);
  m.insert(values.begin(), values.end());
  for (const auto& p : values) {
    auto it = m.find(p.first);
    EXPECT_TRUE(m.end() != it) << ::testing::PrintToString(p.first);
    EXPECT_EQ(p.second, get<1>(*it)) << ::testing::PrintToString(p.first);
  }
}
References absl::p, and values.
TYPED_TEST_P() [31/51]
absl::container_internal::TYPED_TEST_P (LookupTest , OperatorBracket)
Definition at line 44 of file unordered_map_lookup_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using V = typename TypeParam::mapped_type;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m;
  for (const auto& p : values) {
    auto& val = m[p.first];
    EXPECT_EQ(V(), val) << ::testing::PrintToString(p.first);
    val = p.second;
  }
  for (const auto& p : values)
    EXPECT_EQ(p.second, m[p.first]) << ::testing::PrintToString(p.first);
}
References absl::p, and values.
TYPED_TEST_P() [32/51]
absl::container_internal::TYPED_TEST_P (MembersTest , BeginEnd)
Definition at line 73 of file unordered_map_members_test.h.
{
  TypeParam t = {typename TypeParam::value_type{}};
  EXPECT_EQ(t.begin(), t.cbegin());
  EXPECT_EQ(t.end(), t.cend());
  EXPECT_NE(t.begin(), t.end());
  EXPECT_NE(t.cbegin(), t.cend());
}
TYPED_TEST_P() [33/51]
absl::container_internal::TYPED_TEST_P (MembersTest , SimpleFunctions)
Definition at line 69 of file unordered_map_members_test.h.
{
  EXPECT_GT(TypeParam().max_size(), 0);
}
TYPED_TEST_P() [34/51]
absl::container_internal::TYPED_TEST_P (MembersTest , Typedefs)
Definition at line 35 of file unordered_map_members_test.h.
{
  EXPECT_TRUE((std::is_same<std::pair<const typename TypeParam::key_type,
                                      typename TypeParam::mapped_type>,
                            typename TypeParam::value_type>()));
  EXPECT_TRUE((absl::conjunction<
               absl::negation<std::is_signed<typename TypeParam::size_type>>,
               std::is_integral<typename TypeParam::size_type>>()));
  EXPECT_TRUE((absl::conjunction<
               std::is_signed<typename TypeParam::difference_type>,
               std::is_integral<typename TypeParam::difference_type>>()));
  EXPECT_TRUE((std::is_convertible<
               decltype(std::declval<const typename TypeParam::hasher&>()(
                   std::declval<const typename TypeParam::key_type&>())),
               size_t>()));
  EXPECT_TRUE((std::is_convertible<
               decltype(std::declval<const typename TypeParam::key_equal&>()(
                   std::declval<const typename TypeParam::key_type&>(),
                   std::declval<const typename TypeParam::key_type&>())),
               bool>()));
  EXPECT_TRUE((std::is_same<typename TypeParam::allocator_type::value_type,
                            typename TypeParam::value_type>()));
  EXPECT_TRUE((std::is_same<typename TypeParam::value_type&,
                            typename TypeParam::reference>()));
  EXPECT_TRUE((std::is_same<const typename TypeParam::value_type&,
                            typename TypeParam::const_reference>()));
  EXPECT_TRUE((std::is_same<typename std::allocator_traits<
                                typename TypeParam::allocator_type>::pointer,
                            typename TypeParam::pointer>()));
  EXPECT_TRUE(
      (std::is_same<typename std::allocator_traits<
                        typename TypeParam::allocator_type>::const_pointer,
                    typename TypeParam::const_pointer>()));
}
TYPED_TEST_P() [35/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , Clear)
Definition at line 34 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m(values.begin(), values.end());
  ASSERT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  m.clear();
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAre());
  EXPECT_TRUE(m.empty());
}
References items(), and values.
TYPED_TEST_P() [36/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , Emplace)
Definition at line 155 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using V = typename TypeParam::mapped_type;
  T val = hash_internal::Generator<T>()();
  TypeParam m;
  // TODO(alkis): We need a way to run emplace in a more meaningful way. Perhaps
  // with test traits/policy.
  auto p = m.emplace(val);
  EXPECT_TRUE(p.second);
  EXPECT_EQ(val, *p.first);
  T val2 = {val.first, hash_internal::Generator<V>()()};
  p = m.emplace(val2);
  EXPECT_FALSE(p.second);
  EXPECT_EQ(val, *p.first);
}
References absl::p.
TYPED_TEST_P() [37/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , EmplaceHint)
Definition at line 171 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using V = typename TypeParam::mapped_type;
  T val = hash_internal::Generator<T>()();
  TypeParam m;
  // TODO(alkis): We need a way to run emplace in a more meaningful way. Perhaps
  // with test traits/policy.
  auto it = m.emplace_hint(m.end(), val);
  EXPECT_EQ(val, *it);
  T val2 = {val.first, hash_internal::Generator<V>()()};
  it = m.emplace_hint(it, val2);
  EXPECT_EQ(val, *it);
}
TYPED_TEST_P() [38/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , Erase)
Definition at line 238 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using std::get;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m(values.begin(), values.end());
  ASSERT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  auto& first = *m.begin();
  std::vector<T> values2;
  for (const auto& val : values)
    if (get<0>(val) != get<0>(first)) values2.push_back(val);
  auto it = EraseFirst()(&m, 0);
  ASSERT_TRUE(it != m.end());
  EXPECT_EQ(1, std::count(values2.begin(), values2.end(), *it));
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values2.begin(),
                                                             values2.end()));
}
References first, absl::get(), items(), and values.
TYPED_TEST_P() [39/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , EraseKey)
Definition at line 269 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m(values.begin(), values.end());
  ASSERT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  EXPECT_EQ(1, m.erase(values[0].first));
  EXPECT_EQ(0, std::count(m.begin(), m.end(), values[0]));
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAreArray(values.begin() + 1,
                                                             values.end()));
}
References items(), and values.
TYPED_TEST_P() [40/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , EraseRange)
Definition at line 257 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m(values.begin(), values.end());
  ASSERT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
  auto it = m.erase(m.begin(), m.end());
  EXPECT_THAT(items(m), ::testing::UnorderedElementsAre());
  EXPECT_TRUE(it == m.end());
}
References items(), and values.
TYPED_TEST_P() [41/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , Insert)
Definition at line 46 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using V = typename TypeParam::mapped_type;
  T val = hash_internal::Generator<T>()();
  TypeParam m;
  auto p = m.insert(val);
  EXPECT_TRUE(p.second);
  EXPECT_EQ(val, *p.first);
  T val2 = {val.first, hash_internal::Generator<V>()()};
  p = m.insert(val2);
  EXPECT_FALSE(p.second);
  EXPECT_EQ(val, *p.first);
}
References absl::p.
TYPED_TEST_P() [42/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , InsertHint)
Definition at line 60 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using V = typename TypeParam::mapped_type;
  T val = hash_internal::Generator<T>()();
  TypeParam m;
  auto it = m.insert(m.end(), val);
  EXPECT_TRUE(it != m.end());
  EXPECT_EQ(val, *it);
  T val2 = {val.first, hash_internal::Generator<V>()()};
  it = m.insert(it, val2);
  EXPECT_TRUE(it != m.end());
  EXPECT_EQ(val, *it);
}
TYPED_TEST_P() [43/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , InsertOrAssign)
Definition at line 116 of file unordered_map_modifiers_test.h.
{
#ifdef UNORDERED_MAP_CXX17
  using std::get;
  using K = typename TypeParam::key_type;
  using V = typename TypeParam::mapped_type;
  K k = hash_internal::Generator<K>()();
  V val = hash_internal::Generator<V>()();
  TypeParam m;
  auto p = m.insert_or_assign(k, val);
  EXPECT_TRUE(p.second);
  EXPECT_EQ(k, get<0>(*p.first));
  EXPECT_EQ(val, get<1>(*p.first));
  V val2 = hash_internal::Generator<V>()();
  p = m.insert_or_assign(k, val2);
  EXPECT_FALSE(p.second);
  EXPECT_EQ(k, get<0>(*p.first));
  EXPECT_EQ(val2, get<1>(*p.first));
#endif
}
References absl::p.
TYPED_TEST_P() [44/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , InsertOrAssignHint)
Definition at line 136 of file unordered_map_modifiers_test.h.
{
#ifdef UNORDERED_MAP_CXX17
  using std::get;
  using K = typename TypeParam::key_type;
  using V = typename TypeParam::mapped_type;
  K k = hash_internal::Generator<K>()();
  V val = hash_internal::Generator<V>()();
  TypeParam m;
  auto it = m.insert_or_assign(m.end(), k, val);
  EXPECT_TRUE(it != m.end());
  EXPECT_EQ(k, get<0>(*it));
  EXPECT_EQ(val, get<1>(*it));
  V val2 = hash_internal::Generator<V>()();
  it = m.insert_or_assign(it, k, val2);
  EXPECT_EQ(k, get<0>(*it));
  EXPECT_EQ(val2, get<1>(*it));
#endif
}
TYPED_TEST_P() [45/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , InsertRange)
Definition at line 74 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> values;
  std::generate_n(std::back_inserter(values), 10,
                  hash_internal::Generator<T>());
  TypeParam m;
  m.insert(values.begin(), values.end());
  ASSERT_THAT(items(m), ::testing::UnorderedElementsAreArray(values));
}
References items(), and values.
TYPED_TEST_P() [46/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , InsertRangeWithinCapacity)
Definition at line 98 of file unordered_map_modifiers_test.h.
{
#if !defined(__GLIBCXX__)
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> base_values;
  std::generate_n(std::back_inserter(base_values), 10,
                  hash_internal::Generator<T>());
  std::vector<T> values;
  while (values.size() != 100) {
    std::copy_n(base_values.begin(), 10, std::back_inserter(values));
  }
  TypeParam m;
  m.reserve(10);
  const size_t original_capacity = m.bucket_count();
  m.insert(values.begin(), values.end());
  EXPECT_EQ(m.bucket_count(), original_capacity);
#endif
}
References values.
TYPED_TEST_P() [47/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , InsertWithinCapacity)
Definition at line 84 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  using V = typename TypeParam::mapped_type;
  T val = hash_internal::Generator<T>()();
  TypeParam m;
  m.reserve(10);
  const size_t original_capacity = m.bucket_count();
  m.insert(val);
  EXPECT_EQ(m.bucket_count(), original_capacity);
  T val2 = {val.first, hash_internal::Generator<V>()()};
  m.insert(val2);
  EXPECT_EQ(m.bucket_count(), original_capacity);
}
TYPED_TEST_P() [48/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , Swap)
Definition at line 282 of file unordered_map_modifiers_test.h.
{
  using T = hash_internal::GeneratedType<TypeParam>;
  std::vector<T> v1;
  std::vector<T> v2;
  std::generate_n(std::back_inserter(v1), 5, hash_internal::Generator<T>());
  std::generate_n(std::back_inserter(v2), 5, hash_internal::Generator<T>());
  TypeParam m1(v1.begin(), v1.end());
  TypeParam m2(v2.begin(), v2.end());
  EXPECT_THAT(items(m1), ::testing::UnorderedElementsAreArray(v1));
  EXPECT_THAT(items(m2), ::testing::UnorderedElementsAreArray(v2));
  m1.swap(m2);
  EXPECT_THAT(items(m1), ::testing::UnorderedElementsAreArray(v2));
  EXPECT_THAT(items(m2), ::testing::UnorderedElementsAreArray(v1));
}
References items().
TYPED_TEST_P() [49/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , TryEmplace)
Definition at line 185 of file unordered_map_modifiers_test.h.
{
#ifdef UNORDERED_MAP_CXX17
  using T = hash_internal::GeneratedType<TypeParam>;
  using V = typename TypeParam::mapped_type;
  T val = hash_internal::Generator<T>()();
  TypeParam m;
  // TODO(alkis): We need a way to run emplace in a more meaningful way. Perhaps
  // with test traits/policy.
  auto p = m.try_emplace(val.first, val.second);
  EXPECT_TRUE(p.second);
  EXPECT_EQ(val, *p.first);
  T val2 = {val.first, hash_internal::Generator<V>()()};
  p = m.try_emplace(val2.first, val2.second);
  EXPECT_FALSE(p.second);
  EXPECT_EQ(val, *p.first);
#endif
}
References absl::p.
TYPED_TEST_P() [50/51]
absl::container_internal::TYPED_TEST_P (ModifiersTest , TryEmplaceHint)
Definition at line 203 of file unordered_map_modifiers_test.h.
{
#ifdef UNORDERED_MAP_CXX17
  using T = hash_internal::GeneratedType<TypeParam>;
  using V = typename TypeParam::mapped_type;
  T val = hash_internal::Generator<T>()();
  TypeParam m;
  // TODO(alkis): We need a way to run emplace in a more meaningful way. Perhaps
  // with test traits/policy.
  auto it = m.try_emplace(m.end(), val.first, val.second);
  EXPECT_EQ(val, *it);
  T val2 = {val.first, hash_internal::Generator<V>()()};
  it = m.try_emplace(it, val2.first, val2.second);
  EXPECT_EQ(val, *it);
#endif
}
TYPED_TEST_P() [51/51]
absl::container_internal::TYPED_TEST_P (UniquePtrModifiersTest , TryEmplace)
Definition at line 329 of file unordered_map_modifiers_test.h.
{
#ifdef UNORDERED_MAP_CXX17
  using T = hash_internal::GeneratedType<TypeParam>;
  using V = typename TypeParam::mapped_type;
  T val = hash_internal::Generator<T>()();
  TypeParam m;
  auto p = m.try_emplace(val.first, std::move(val.second));
  EXPECT_TRUE(p.second);
  // A moved from std::unique_ptr is guaranteed to be nullptr.
  EXPECT_EQ(val.second, nullptr);
  T val2 = {val.first, hash_internal::Generator<V>()()};
  p = m.try_emplace(val2.first, std::move(val2.second));
  EXPECT_FALSE(p.second);
  EXPECT_NE(val2.second, nullptr);
#endif
}
References absl::p.
TYPED_TEST_SUITE_P() [1/5]
absl::container_internal::TYPED_TEST_SUITE_P (ConstructorTest)
TYPED_TEST_SUITE_P() [2/5]
absl::container_internal::TYPED_TEST_SUITE_P (LookupTest)
TYPED_TEST_SUITE_P() [3/5]
absl::container_internal::TYPED_TEST_SUITE_P (MembersTest)
TYPED_TEST_SUITE_P() [4/5]
absl::container_internal::TYPED_TEST_SUITE_P (ModifiersTest)
TYPED_TEST_SUITE_P() [5/5]
absl::container_internal::TYPED_TEST_SUITE_P (UniquePtrModifiersTest)
UnsampleSlow()
void absl::container_internal::UnsampleSlow (HashtablezInfo * info)
Definition at line 158 of file hashtablez_sampler.cc.
{
  GlobalHashtablezSampler().Unregister(info);
}
References GlobalHashtablezSampler(), and absl::profiling_internal::SampleRecorder< T >::Unregister().
UseType()
template<typename T > void absl::container_internal::UseType ()
Definition at line 33 of file unordered_map_members_test.h.
{}
WithConstructed()
template<class T , class Tuple , class F > decltype(std::declval< F >()(std::declval< T >())) absl::container_internal::WithConstructed (Tuple && t, F && f)
Definition at line 159 of file container_memory.h.
                      {
  return memory_internal::WithConstructedImpl<T>(
      std::forward<Tuple>(t),
      absl::make_index_sequence<
          std::tuple_size<typename std::decay<Tuple>::type>::value>(),
      std::forward<F>(f));
}
References absl::f, and WithConstructed().
Referenced by WithConstructed().
Variable Documentation
kEmptyGroup
ABSL_DLL const ctrl_t absl::container_internal::kEmptyGroup
Initial value:
= {
    ctrl_t::kSentinel, ctrl_t::kEmpty, ctrl_t::kEmpty, ctrl_t::kEmpty,
    ctrl_t::kEmpty,    ctrl_t::kEmpty, ctrl_t::kEmpty, ctrl_t::kEmpty,
    ctrl_t::kEmpty,    ctrl_t::kEmpty, ctrl_t::kEmpty, ctrl_t::kEmpty,
    ctrl_t::kEmpty,    ctrl_t::kEmpty, ctrl_t::kEmpty, ctrl_t::kEmpty,
    static_cast<ctrl_t>(0)}
Definition at line 31 of file raw_hash_set.cc.
{
    ctrl_t::kSentinel, ctrl_t::kEmpty, ctrl_t::kEmpty, ctrl_t::kEmpty,
    ctrl_t::kEmpty,    ctrl_t::kEmpty, ctrl_t::kEmpty, ctrl_t::kEmpty,
    ctrl_t::kEmpty,    ctrl_t::kEmpty, ctrl_t::kEmpty, ctrl_t::kEmpty,
    ctrl_t::kEmpty,    ctrl_t::kEmpty, ctrl_t::kEmpty, ctrl_t::kEmpty,
    static_cast<ctrl_t>(0)};
Referenced by EmptyGroup().