open spiel: pybind11::google Namespace Reference
pybind11::google Namespace Reference
Namespaces
namespace internal
Classes
struct NoThrowStatus
class StatusNotOk
Functions
module_ ImportStatusModule (bool bypass_regular_import)
template<typename StatusType >
NoThrowStatus< StatusType > DoNotThrowStatus (StatusType status)
template<typename StatusType , typename... Args>
std::function< NoThrowStatus< StatusType >(Args...)> DoNotThrowStatus (std::function< StatusType(Args...)> f)
template<typename StatusType , typename... Args>
std::function< NoThrowStatus< StatusType >(Args...)> DoNotThrowStatus (StatusType(*f)(Args...))
template<typename StatusType , typename Class , typename... Args>
std::function< NoThrowStatus< StatusType >(Class *, Args...)> DoNotThrowStatus (StatusType(Class::*f)(Args...))
template<typename StatusType , typename Class , typename... Args>
std::function< NoThrowStatus< StatusType >(const Class *, Args...)> DoNotThrowStatus (StatusType(Class::*f)(Args...) const)
PYBIND11_MODULE (status, m)
Function Documentation
DoNotThrowStatus() [1/5]
template<typename StatusType > NoThrowStatus< StatusType > pybind11::google::DoNotThrowStatus (StatusType status)
Definition at line 26 of file no_throw_status.h.
{
  return NoThrowStatus<StatusType>(std::forward<StatusType>(status));
}
Referenced by pybind11::test::PYBIND11_MODULE(), pybind11::google::internal::RegisterStatusBindings(), pybind11::test::ReturnFailureStatusOrManualCast(), and pybind11::test::ReturnStatusManualCast().
DoNotThrowStatus() [2/5]
template<typename StatusType , typename... Args> std::function< NoThrowStatus< StatusType >(Args...)> pybind11::google::DoNotThrowStatus (StatusType(* f)(Args...))
Definition at line 40 of file no_throw_status.h.
{
  return [f](Args&&... args) {
    return NoThrowStatus<StatusType>(
        std::forward<StatusType>(f(std::forward<Args>(args)...)));
  };
}
DoNotThrowStatus() [3/5]
template<typename StatusType , typename Class , typename... Args> std::function< NoThrowStatus< StatusType >(const Class *, Args...)> pybind11::google::DoNotThrowStatus (StatusType(Class::* f)(Args...) const)
Definition at line 57 of file no_throw_status.h.
{
  return [f](const Class* c, Args&&... args) {
    return NoThrowStatus<StatusType>(
        std::forward<StatusType>((c->*f)(std::forward<Args>(args)...)));
  };
}
DoNotThrowStatus() [4/5]
template<typename StatusType , typename Class , typename... Args> std::function< NoThrowStatus< StatusType >(Class *, Args...)> pybind11::google::DoNotThrowStatus (StatusType(Class::* f)(Args...))
Definition at line 48 of file no_throw_status.h.
{
  return [f](Class* c, Args&&... args) {
    return NoThrowStatus<StatusType>(
        std::forward<StatusType>((c->*f)(std::forward<Args>(args)...)));
  };
}
DoNotThrowStatus() [5/5]
template<typename StatusType , typename... Args> std::function< NoThrowStatus< StatusType >(Args...)> pybind11::google::DoNotThrowStatus (std::function< StatusType(Args...)> f)
Definition at line 32 of file no_throw_status.h.
{
  return [f = std::move(f)](Args&&... args) {
    return NoThrowStatus<StatusType>(
        std::forward<StatusType>(f(std::forward<Args>(args)...)));
  };
}
ImportStatusModule()
module_ pybind11::google::ImportStatusModule (bool bypass_regular_import)
Definition at line 12 of file import_status_module.cc.
{
  if (!PyGILState_Check()) {
    pybind11_fail("ImportStatusModule() PyGILState_Check() failure.");
  }
  if (bypass_regular_import) {
    auto m = reinterpret_borrow<module_>(PyImport_AddModule(
        PYBIND11_TOSTRING(PYBIND11_ABSEIL_STATUS_MODULE_PATH)));
    if (!internal::IsStatusModuleImported()) {
      internal::RegisterStatusBindings(m);
    }
    // else no-op because bindings are already loaded.
    return m;
  }
  return module_::import(PYBIND11_TOSTRING(PYBIND11_ABSEIL_STATUS_MODULE_PATH));
}
References pybind11::google::internal::IsStatusModuleImported(), PYBIND11_ABSEIL_STATUS_MODULE_PATH, and pybind11::google::internal::RegisterStatusBindings().
Referenced by pybind11::test::PYBIND11_MODULE().
PYBIND11_MODULE()
pybind11::google::PYBIND11_MODULE (status , m)
Definition at line 8 of file status.cc.
{ internal::RegisterStatusBindings(m); }
References pybind11::google::internal::RegisterStatusBindings().