open spiel: open_spiel.python.examples.ppo_example Namespace Reference
open_spiel.python.examples.ppo_example Namespace Reference
Functions
setup_logging ()
make_single_atari_env (gym_id, seed, idx, capture_video, run_name, use_episodic_life_env=True)
make_single_env (game_name, seed)
main (_)
Variables
FLAGS = flags.FLAGS
Detailed Description
An example of use of PPO.
Note: code adapted (with permission) from
https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/ppo.py and
https://github.com/vwxyzjn/ppo-implementation-details/blob/main/ppo_atari.py
Function Documentation
main()
open_spiel.python.examples.ppo_example.main (_)
Definition at line 145 of file ppo_example.py.
def main(_):
  setup_logging()
  batch_size = int(FLAGS.num_envs * FLAGS.num_steps)
  if FLAGS.game_name == "atari":
    # pylint: disable=unused-import
    # pylint: disable=g-import-not-at-top
    import open_spiel.python.games.atari
  current_day = datetime.now().strftime("%d")
  current_month_text = datetime.now().strftime("%h")
  run_name = f"{FLAGS.game_name}__{FLAGS.exp_name}__"
  if FLAGS.game_name == "atari":
    run_name += f"{FLAGS.gym_id}__"
  run_name += f"{FLAGS.seed}__{current_month_text}__{current_day}__{int(time.time())}"
  writer = SummaryWriter(f"runs/{run_name}")
  writer.add_text(
      "hyperparameters",
      "|param|value|\n|-|-|\n%s" %
      ("\n".join([f"|{key}|{value}|" for key, value in vars(FLAGS).items()])),
  )
  random.seed(FLAGS.seed)
  np.random.seed(FLAGS.seed)
  torch.manual_seed(FLAGS.seed)
  torch.backends.cudnn.deterministic = FLAGS.torch_deterministic
  device = torch.device(
      "cuda" if torch.cuda.is_available() and FLAGS.cuda else "cpu")
  logging.info("Using device: %s", str(device))
  if FLAGS.game_name == "atari":
    envs = SyncVectorEnv([
        make_single_atari_env(FLAGS.gym_id, FLAGS.seed + i, i, False,
                              run_name)() for i in range(FLAGS.num_envs)
    ])
    agent_fn = PPOAtariAgent
  else:
    envs = SyncVectorEnv([
        make_single_env(FLAGS.game_name, FLAGS.seed + i)()
        for i in range(FLAGS.num_envs)
    ])
    agent_fn = PPOAgent
  game = envs.envs[0]._game  # pylint: disable=protected-access
  info_state_shape = game.observation_tensor_shape()
  num_updates = FLAGS.total_timesteps // batch_size
  agent = PPO(
      input_shape=info_state_shape,
      num_actions=game.num_distinct_actions(),
      num_players=game.num_players(),
      player_id=0,
      num_envs=FLAGS.num_envs,
      steps_per_batch=FLAGS.num_steps,
      num_minibatches=FLAGS.num_minibatches,
      update_epochs=FLAGS.update_epochs,
      learning_rate=FLAGS.learning_rate,
      gae=FLAGS.gae,
      gamma=FLAGS.gamma,
      gae_lambda=FLAGS.gae_lambda,
      normalize_advantages=FLAGS.norm_adv,
      clip_coef=FLAGS.clip_coef,
      clip_vloss=FLAGS.clip_vloss,
      entropy_coef=FLAGS.ent_coef,
      value_coef=FLAGS.vf_coef,
      max_grad_norm=FLAGS.max_grad_norm,
      target_kl=FLAGS.target_kl,
      device=device,
      writer=writer,
      agent_fn=agent_fn,
  )
  n_reward_window = 50
  recent_rewards = collections.deque(maxlen=n_reward_window)
  time_step = envs.reset()
  for update in range(num_updates):
    for _ in range(FLAGS.num_steps):
      agent_output = agent.step(time_step)
      time_step, reward, done, unreset_time_steps = envs.step(
          agent_output, reset_if_done=True)
      if FLAGS.game_name == "atari":
        # Get around the fact that
        # stable_baselines3.common.atari_wrappers.EpisodicLifeEnv will modify
        # rewards at the LIFE and not GAME level by only counting
        # rewards of finished episodes
        for ts in unreset_time_steps:
          info = ts.observations.get("info")
          if info and "episode" in info:
            real_reward = info["episode"]["r"]
            writer.add_scalar("charts/player_0_training_returns", real_reward,
                              agent.total_steps_done)
            recent_rewards.append(real_reward)
      else:
        for ts in unreset_time_steps:
          if ts.last():
            real_reward = ts.rewards[0]
            writer.add_scalar("charts/player_0_training_returns", real_reward,
                              agent.total_steps_done)
            recent_rewards.append(real_reward)
      agent.post_step(reward, done)
    if FLAGS.anneal_lr:
      agent.anneal_learning_rate(update, num_updates)
    agent.learn(time_step)
    if update % FLAGS.eval_every == 0:
      logging.info("-" * 80)
      logging.info("Step %s", agent.total_steps_done)
      logging.info("Summary of past %i rewards\n %s",
                   n_reward_window,
                   pd.Series(recent_rewards).describe())
  writer.close()
  logging.info("All done. Have a pleasant day :)")
References open_spiel.python.examples.ppo_example.make_single_atari_env(), open_spiel.python.examples.ppo_example.make_single_env(), and open_spiel.python.examples.ppo_example.setup_logging().
make_single_atari_env()
open_spiel.python.examples.ppo_example.make_single_atari_env (gym_id, seed, idx, capture_video, run_name, use_episodic_life_env = True)
Make the single-agent Atari environment.
Definition at line 110 of file ppo_example.py.
                          use_episodic_life_env=True):
  """Make the single-agent Atari environment."""
  def gen_env():
    game = pyspiel.load_game(
        "atari", {
            "gym_id": gym_id,
            "seed": seed,
            "idx": idx,
            "capture_video": capture_video,
            "run_name": run_name,
            "use_episodic_life_env": use_episodic_life_env
        })
    return Environment(
        game,
        chance_event_sampler=ChanceEventSampler(seed=seed),
        observation_type=ObservationType.OBSERVATION)
  return gen_env
Referenced by open_spiel.python.examples.ppo_example.main().
make_single_env()
open_spiel.python.examples.ppo_example.make_single_env (game_name, seed)
Definition at line 136 of file ppo_example.py.
def make_single_env(game_name, seed):
  def gen_env():
    game = pyspiel.load_game(game_name)
    return Environment(game, chance_event_sampler=ChanceEventSampler(seed=seed))
  return gen_env
Referenced by open_spiel.python.examples.ppo_example.main().
setup_logging()
open_spiel.python.examples.ppo_example.setup_logging ()
Definition at line 98 of file ppo_example.py.
def setup_logging():
  root = logging.getLogger()
  root.setLevel(logging.DEBUG)
  handler = logging.StreamHandler(sys.stdout)
  handler.setLevel(logging.DEBUG)
  formatter = logging.Formatter(
      "%(asctime)s - %(name)s - %(levelname)s - %(message)s")
  handler.setFormatter(formatter)
  root.addHandler(handler)
Referenced by open_spiel.python.examples.ppo_example.main().
Variable Documentation
FLAGS
open_spiel.python.examples.ppo_example.FLAGS = flags.FLAGS
Definition at line 47 of file ppo_example.py.