open spiel: open_spiel::solitaire Namespace Reference
open_spiel::solitaire Namespace Reference
Classes
class Card
class Foundation
class Move
class Pile
class SolitaireGame
class SolitaireState
class Tableau
class Waste
Enumerations
enum class SuitType {
kNone = 0 , kSpades , kHearts , kClubs ,
kDiamonds , kHidden
}
enum class RankType {
kNone = 0 , kA , k2 , k3 ,
k4 , k5 , k6 , k7 ,
k8 , k9 , kT , kJ ,
kQ , kK , kHidden
}
enum class LocationType {
kDeck = 0 , kWaste = 1 , kFoundation = 2 , kTableau = 3 ,
kMissing = 4
}
enum class PileID {
kWaste = 0 , kSpades = 1 , kHearts = 2 , kClubs = 3 ,
kDiamonds = 4 , k1stTableau = 5 , k2ndTableau = 6 , k3rdTableau = 7 ,
k4thTableau = 8 , k5thTableau = 9 , k6thTableau = 10 , k7thTableau = 11 ,
kMissing = 12
}
Functions
std::vector< SuitType > GetOppositeSuits (const SuitType &suit)
int GetCardIndex (RankType rank, SuitType suit)
int GetMaxSize (LocationType location)
Variables
std::hash< std::string > hasher
constexpr int kDefaultPlayers = 1
constexpr int kDefaultDepthLimit = 150
constexpr bool kDefaultIsColored = false
constexpr int kHiddenCard = 99
Enumeration Type Documentation
LocationType
enum class open_spiel::solitaire::LocationType strong
Enumerator
kDeck
kWaste
kFoundation
kTableau
kMissing
Definition at line 78 of file solitaire.h.
{
  kDeck = 0,
  kWaste = 1,
  kFoundation = 2,
  kTableau = 3,
  kMissing = 4,
};
PileID
enum class open_spiel::solitaire::PileID strong
Enumerator
kWaste
kSpades
kHearts
kClubs
kDiamonds
k1stTableau
k2ndTableau
k3rdTableau
k4thTableau
k5thTableau
k6thTableau
k7thTableau
kMissing
Definition at line 86 of file solitaire.h.
                  {
  kWaste = 0,
  kSpades = 1,
  kHearts = 2,
  kClubs = 3,
  kDiamonds = 4,
  k1stTableau = 5,
  k2ndTableau = 6,
  k3rdTableau = 7,
  k4thTableau = 8,
  k5thTableau = 9,
  k6thTableau = 10,
  k7thTableau = 11,
  kMissing = 12
};
RankType
enum class open_spiel::solitaire::RankType strong
Enumerator
kNone
kA
k2
k3
k4
k5
k6
k7
k8
k9
kT
kJ
kQ
kK
kHidden
Definition at line 60 of file solitaire.h.
                    {
  kNone = 0,
  kA,
  k2,
  k3,
  k4,
  k5,
  k6,
  k7,
  k8,
  k9,
  kT,
  kJ,
  kQ,
  kK,
  kHidden,
};
SuitType
enum class open_spiel::solitaire::SuitType strong
Enumerator
kNone
kSpades
kHearts
kClubs
kDiamonds
kHidden
Definition at line 51 of file solitaire.h.
                    {
  kNone = 0,
  kSpades,
  kHearts,
  kClubs,
  kDiamonds,
  kHidden,
};
Function Documentation
GetCardIndex()
int open_spiel::solitaire::GetCardIndex (RankType rank, SuitType suit)
Definition at line 200 of file solitaire.cc.
{
  /* Using a given rank and/or suit, gets an integer representing the index
   * of the card. */
  if (rank == RankType::kHidden || suit == SuitType::kHidden) {
    // Handles hidden_ cards_
    return kHiddenCard;
  } else if (rank == RankType::kNone) {
    // Handles special cards_
    if (suit == SuitType::kNone) {
      // Handles empty tableau cards_
      return kEmptyTableauCard;
    } else {
      // Handles empty foundation cards
      switch (suit) {
        case SuitType::kSpades: {
          return kEmptySpadeCard;
        }
        case SuitType::kHearts: {
          return kEmptyHeartCard;
        }
        case SuitType::kClubs: {
          return kEmptyClubCard;
        }
        case SuitType::kDiamonds: {
          return kEmptyDiamondCard;
        }
        default: {
          SpielFatalError("Failed to get card index_");
        }
      }
    }
  } else {
    // Handles ordinary cards (e.g. 0-13 -> spades, 14-26 -> hearts, etc.)
    return (static_cast<int>(suit) - 1) * kNumRanks + static_cast<int>(rank);
  }
}
References kClubs, kDiamonds, kHearts, kHidden, kHiddenCard, kNone, kSpades, rank, and open_spiel::SpielFatalError().
Referenced by open_spiel::solitaire::Card::GetIndex().
GetMaxSize()
int open_spiel::solitaire::GetMaxSize (LocationType location)
Definition at line 238 of file solitaire.cc.
{
  if (location >= LocationType::kDeck && location <= LocationType::kWaste) {
    // Cards can only be removed from the waste_&  there are 24 cards_ in it
    // at the start of the game
    return kMaxSizeWaste;
  } else if (location == LocationType::kFoundation) {
    // There are 13 cards_ in a suit_
    return kMaxSizeFoundation;
  } else if (location == LocationType::kTableau) {
    // There are a maximum of 6 hidden cards and 13 non-hidden cards in a
    // tableau (1 for each rank)
    return kMaxSizeTableau;
  } else {
    return 0;
  }
}
References kDeck, kFoundation, kTableau, and kWaste.
GetOppositeSuits()
std::vector< SuitType > open_spiel::solitaire::GetOppositeSuits (const SuitType & suit)
Definition at line 167 of file solitaire.cc.
{
  /* Just returns a vector of the suits of opposite color. For red suits
   * (SuitType::kHearts and SuitType::kDiamonds), this returns the black suits
   * (SuitType::kSpades and SuitType::kClubs). For a black suit_, this returns
   * the red suits. The last `SuitType` would be `SuitType::kNone` which should
   * only occur with empty tableau cards or hidden cards. Empty tableau
   * cards should accept any suit, but hidden cards are the opposite; they
   * shouldn't accept any. There isn't really a use case for calling this
   * function with the suit of a hidden card though. */
  switch (suit) {
    case SuitType::kSpades: {
      return {SuitType::kHearts, SuitType::kDiamonds};
    }
    case SuitType::kHearts: {
      return {SuitType::kSpades, SuitType::kClubs};
    }
    case SuitType::kClubs: {
      return {SuitType::kHearts, SuitType::kDiamonds};
    }
    case SuitType::kDiamonds: {
      return {SuitType::kSpades, SuitType::kClubs};
    }
    case SuitType::kNone: {
      return {SuitType::kSpades, SuitType::kHearts, SuitType::kClubs,
              SuitType::kDiamonds};
    }
    default: {
      SpielFatalError("suit is not in (s, h, c, d)");
    }
  }
}
References kClubs, kDiamonds, kHearts, kNone, kSpades, and open_spiel::SpielFatalError().
Referenced by open_spiel::solitaire::Card::LegalChildren(), and open_spiel::solitaire::Move::Move().
Variable Documentation
hasher
std::hash<std::string> open_spiel::solitaire::hasher
Definition at line 255 of file solitaire.cc.
Referenced by open_spiel::solitaire::SolitaireState::DoApplyAction(), and open_spiel::solitaire::SolitaireState::LegalActions().
kDefaultDepthLimit
int open_spiel::solitaire::kDefaultDepthLimit = 150 inline constexpr
Definition at line 42 of file solitaire.h.
kDefaultIsColored
bool open_spiel::solitaire::kDefaultIsColored = false inline constexpr
Definition at line 43 of file solitaire.h.
kDefaultPlayers
int open_spiel::solitaire::kDefaultPlayers = 1 inline constexpr
Definition at line 41 of file solitaire.h.
kHiddenCard
int open_spiel::solitaire::kHiddenCard = 99 inline constexpr
Definition at line 47 of file solitaire.h.
Referenced by open_spiel::solitaire::Card::Card(), GetCardIndex(), and open_spiel::solitaire::Card::GetIndex().