open spiel: absl::span_internal Namespace Reference
absl::span_internal Namespace Reference
Classes
struct ElementType
struct ElementType< T(&)[N]>
struct IsView
struct IsView< T, absl::void_t< decltype(span_internal::GetData(std::declval< const T & >()))>, absl::void_t< decltype(span_internal::GetData(std::declval< T & >()))> >
Typedefs
template<typename C >
using HasSize
template<typename T , typename C >
using HasData
template<typename C >
using ElementT = typename ElementType<C>::type
template<typename T >
using EnableIfMutable
template<typename From , typename To >
using EnableIfConvertibleTo
template<typename T >
using EnableIfIsView = std::enable_if_t<IsView<T>::value, int>
template<typename T >
using EnableIfNotIsView = std::enable_if_t<!IsView<T>::value, int>
Functions
template<typename C >
constexpr auto GetDataImpl (C &c, char) noexcept -> decltype(c.data())
char * GetDataImpl (std::string &s, int) noexcept
template<typename C >
constexpr auto GetData (C &c) noexcept -> decltype(GetDataImpl(c, 0))
template<template< typename > class SpanT, typename T >
bool EqualImpl (SpanT< T > a, SpanT< T > b)
template<template< typename > class SpanT, typename T >
bool LessThanImpl (SpanT< T > a, SpanT< T > b)
Typedef Documentation
ElementT
template<typename C > using absl::span_internal::ElementT = typename ElementType<C>::type
Definition at line 82 of file span.h.
EnableIfConvertibleTo
template<typename From , typename To > using absl::span_internal::EnableIfConvertibleTo
Initial value:
    typename std::enable_if<std::is_convertible<From, To>::value>::type
Definition at line 103 of file span.h.
EnableIfIsView
template<typename T > using absl::span_internal::EnableIfIsView = std::enable_if_t<IsView<T>::value, int>
Definition at line 130 of file span.h.
EnableIfMutable
template<typename T > using absl::span_internal::EnableIfMutable
Initial value:
    typename std::enable_if<!std::is_const<T>::value, int>::type
Definition at line 85 of file span.h.
EnableIfNotIsView
template<typename T > using absl::span_internal::EnableIfNotIsView = std::enable_if_t<!IsView<T>::value, int>
Definition at line 133 of file span.h.
HasData
template<typename T , typename C > using absl::span_internal::HasData
Initial value:
    std::is_convertible<absl::decay_t<decltype(GetData(std::declval<C&>()))>*,
                        T* const*>
Definition at line 66 of file span.h.
HasSize
template<typename C > using absl::span_internal::HasSize
Initial value:
    std::is_integral<absl::decay_t<decltype(std::declval<C&>().size())>>
Definition at line 56 of file span.h.
Function Documentation
EqualImpl()
template<template< typename > class SpanT, typename T > bool absl::span_internal::EqualImpl (SpanT< T > a, SpanT< T > b)
Definition at line 89 of file span.h.
{
  static_assert(std::is_const<T>::value, "");
  return absl::equal(a.begin(), a.end(), b.begin(), b.end());
}
References absl::a, b, and absl::equal().
Referenced by absl::operator==(), absl::operator==(), and absl::operator==().
GetData()
template<typename C > auto absl::span_internal::GetData (C & c) -> decltype(GetDataImpl(c, 0)) constexpr noexcept
Definition at line 49 of file span.h.
{
  return GetDataImpl(c, 0);
}
References absl::c, and GetDataImpl().
Referenced by absl::MakeSpan().
GetDataImpl() [1/2]
template<typename C > auto absl::span_internal::GetDataImpl (C & c, char) -> decltype(c.data()) constexpr noexcept
Definition at line 37 of file span.h.
{
  return c.data();
}
References absl::c.
Referenced by GetData().
GetDataImpl() [2/2]
char * absl::span_internal::GetDataImpl (std::string & s, int) inline noexcept
Definition at line 43 of file span.h.
{
  return &s[0];
}
References absl::s.
LessThanImpl()
template<template< typename > class SpanT, typename T > bool absl::span_internal::LessThanImpl (SpanT< T > a, SpanT< T > b)
Definition at line 95 of file span.h.
{
  // We can't use value_type since that is remove_cv_t<T>, so we go the long way
  // around.
  static_assert(std::is_const<T>::value, "");
  return std::lexicographical_compare(a.begin(), a.end(), b.begin(), b.end());
}
References absl::a, and b.
Referenced by absl::operator<(), absl::operator<(), and absl::operator<().