open spiel: absl::functional_internal Namespace Reference
absl::functional_internal Namespace Reference
Classes
struct ForwardT
class FrontBinder
union VoidPtr
Typedefs
template<class F , class... BoundArgs>
using bind_front_t = FrontBinder<decay_t<F>, absl::decay_t<BoundArgs>...>
template<typename R , typename... Args>
using Invoker = R (*)(VoidPtr, typename ForwardT<Args>::type...)
template<bool C>
using EnableIf = typename ::std::enable_if<C, int>::type
Functions
template<class R , class Tuple , size_t... Idx, class... Args>
R Apply (Tuple &&bound, absl::index_sequence< Idx... >, Args &&... free)
template<typename T >
constexpr bool PassByValue ()
template<typename Obj , typename R , typename... Args>
R InvokeObject (VoidPtr ptr, typename ForwardT< Args >::type... args)
template<typename Fun , typename R , typename... Args>
R InvokeFunction (VoidPtr ptr, typename ForwardT< Args >::type... args)
template<typename Sig >
void AssertNonNull (const std::function< Sig > &f)
template<typename F >
void AssertNonNull (const F &)
template<typename F , typename C >
void AssertNonNull (F C::*f)
Typedef Documentation
bind_front_t
template<class F , class... BoundArgs> using absl::functional_internal::bind_front_t = FrontBinder<decay_t<F>, absl::decay_t<BoundArgs>...>
Definition at line 89 of file front_binder.h.
EnableIf
template<bool C> using absl::functional_internal::EnableIf = typename ::std::enable_if<C, int>::type
Definition at line 100 of file function_ref.h.
Invoker
template<typename R , typename... Args> using absl::functional_internal::Invoker = R (*)(VoidPtr, typename ForwardT<Args>::type...)
Definition at line 63 of file function_ref.h.
Function Documentation
Apply()
template<class R , class Tuple , size_t... Idx, class... Args> R absl::functional_internal::Apply (Tuple && bound, absl::index_sequence< Idx... > , Args &&... free)
Definition at line 35 of file front_binder.h.
{
  return base_internal::invoke(
      absl::forward<Tuple>(bound).template get<Idx>()...,
      absl::forward<Args>(free)...);
}
References absl::forward(), and absl::base_internal::invoke().
Referenced by absl::functional_internal::FrontBinder< F, BoundArgs >::operator()(), absl::functional_internal::FrontBinder< F, BoundArgs >::operator()(), absl::functional_internal::FrontBinder< F, BoundArgs >::operator()(), and absl::functional_internal::FrontBinder< F, BoundArgs >::operator()().
AssertNonNull() [1/3]
template<typename F > void absl::functional_internal::AssertNonNull (const F &)
Definition at line 91 of file function_ref.h.
{}
AssertNonNull() [2/3]
template<typename Sig > void absl::functional_internal::AssertNonNull (const std::function< Sig > & f)
Definition at line 85 of file function_ref.h.
{
  assert(f != nullptr);
  (void)f;
}
References absl::f.
Referenced by absl::FunctionRef< R(Args...)>::FunctionRef().
AssertNonNull() [3/3]
template<typename F , typename C > void absl::functional_internal::AssertNonNull (F C::* f)
Definition at line 94 of file function_ref.h.
{
  assert(f != nullptr);
  (void)f;
}
References absl::f.
InvokeFunction()
template<typename Fun , typename R , typename... Args> R absl::functional_internal::InvokeFunction (VoidPtr ptr, typename ForwardT< Args >::type... args)
Definition at line 78 of file function_ref.h.
{
  auto f = reinterpret_cast<Fun>(ptr.fun);
  return static_cast<R>(
      absl::base_internal::invoke(f, std::forward<Args>(args)...));
}
References absl::f, absl::base_internal::invoke(), and ptr.
InvokeObject()
template<typename Obj , typename R , typename... Args> R absl::functional_internal::InvokeObject (VoidPtr ptr, typename ForwardT< Args >::type... args)
Definition at line 71 of file function_ref.h.
{
  auto o = static_cast<const Obj*>(ptr.obj);
  return static_cast<R>(
      absl::base_internal::invoke(*o, std::forward<Args>(args)...));
}
References absl::base_internal::invoke(), absl::o, and ptr.
PassByValue()
template<typename T > bool absl::functional_internal::PassByValue () constexpr
Definition at line 44 of file function_ref.h.
{
  return !std::is_lvalue_reference<T>::value &&
         absl::is_trivially_copy_constructible<T>::value &&
         absl::is_trivially_copy_assignable<
             typename std::remove_cv<T>::type>::value &&
         std::is_trivially_destructible<T>::value &&
         sizeof(T) <= 2 * sizeof(void*);
}