open spiel: absl::int128_internal Namespace Reference
absl::int128_internal Namespace Reference
Functions
constexpr uint128 AddResult (uint128 result, uint128 lhs)
constexpr uint128 SubstructResult (uint128 result, uint128 lhs, uint128 rhs)
constexpr int64_t BitCastToSigned (uint64_t v)
Function Documentation
AddResult()
uint128 absl::int128_internal::AddResult (uint128 result, uint128 lhs) constexpr
Definition at line 933 of file int128.h.
{
  // check for carry
  return (Uint128Low64(result) < Uint128Low64(lhs))
             ? MakeUint128(Uint128High64(result) + 1, Uint128Low64(result))
             : result;
}
References absl::MakeUint128(), absl::Uint128High64(), and absl::Uint128Low64().
Referenced by absl::operator+().
BitCastToSigned()
int64_t absl::int128_internal::BitCastToSigned (uint64_t v) constexpr
Definition at line 1142 of file int128.h.
{
  // Casting an unsigned integer to a signed integer of the same
  // width is implementation defined behavior if the source value would not fit
  // in the destination type. We step around it with a roundtrip bitwise not
  // operation to make sure this function remains constexpr. Clang, GCC, and
  // MSVC optimize this to a no-op on x86-64.
  return v & (uint64_t{1} << 63) ? ~static_cast<int64_t>(~v)
                                 : static_cast<int64_t>(v);
}
References absl::v.
Referenced by absl::operator%(), and absl::operator/().
SubstructResult()
uint128 absl::int128_internal::SubstructResult (uint128 result, uint128 lhs, uint128 rhs) constexpr
Definition at line 956 of file int128.h.
{
  // check for carry
  return (Uint128Low64(lhs) < Uint128Low64(rhs))
             ? MakeUint128(Uint128High64(result) - 1, Uint128Low64(result))
             : result;
}
References absl::MakeUint128(), absl::Uint128High64(), and absl::Uint128Low64().
Referenced by absl::operator-().