open spiel: open_spiel::kuhn_poker Namespace Reference
open_spiel::kuhn_poker Namespace Reference
Classes
class KuhnGame
class KuhnObserver
class KuhnState
Enumerations
enum ActionType { kPass = 0 , kBet = 1 }
Functions
TabularPolicy GetAlwaysPassPolicy (const Game &game)
TabularPolicy GetAlwaysBetPolicy (const Game &game)
TabularPolicy GetOptimalPolicy (double alpha)
Variables
constexpr const int kNumInfoStatesP0 = 6
constexpr const int kNumInfoStatesP1 = 6
Enumeration Type Documentation
ActionType
enum open_spiel::kuhn_poker::ActionType
Enumerator
kPass
kBet
Definition at line 45 of file kuhn_poker.h.
{ kPass = 0, kBet = 1 };
Function Documentation
GetAlwaysBetPolicy()
TabularPolicy open_spiel::kuhn_poker::GetAlwaysBetPolicy (const Game & game)
Definition at line 445 of file kuhn_poker.cc.
{
  SPIEL_CHECK_TRUE(
      dynamic_cast<KuhnGame*>(const_cast<Game*>(&game)) != nullptr);
  return GetPrefActionPolicy(game, {ActionType::kBet});
}
References open_spiel::GetPrefActionPolicy(), kBet, and SPIEL_CHECK_TRUE.
GetAlwaysPassPolicy()
TabularPolicy open_spiel::kuhn_poker::GetAlwaysPassPolicy (const Game & game)
Definition at line 439 of file kuhn_poker.cc.
{
  SPIEL_CHECK_TRUE(
      dynamic_cast<KuhnGame*>(const_cast<Game*>(&game)) != nullptr);
  return GetPrefActionPolicy(game, {ActionType::kPass});
}
References open_spiel::GetPrefActionPolicy(), kPass, and SPIEL_CHECK_TRUE.
GetOptimalPolicy()
TabularPolicy open_spiel::kuhn_poker::GetOptimalPolicy (double alpha)
Definition at line 451 of file kuhn_poker.cc.
{
  SPIEL_CHECK_GE(alpha, 0.);
  SPIEL_CHECK_LE(alpha, 1. / 3);
  const double three_alpha = 3 * alpha;
  std::unordered_map<std::string, ActionsAndProbs> policy;
  // All infostates have two actions: Pass (0) and Bet (1).
  // Player 0
  policy["0"] = {{0, 1 - alpha}, {1, alpha}};
  policy["0pb"] = {{0, 1}, {1, 0}};
  policy["1"] = {{0, 1}, {1, 0}};
  policy["1pb"] = {{0, 2. / 3. - alpha}, {1, 1. / 3. + alpha}};
  policy["2"] = {{0, 1 - three_alpha}, {1, three_alpha}};
  policy["2pb"] = {{0, 0}, {1, 1}};
  // Player 1
  policy["0p"] = {{0, 2. / 3.}, {1, 1. / 3.}};
  policy["0b"] = {{0, 1}, {1, 0}};
  policy["1p"] = {{0, 1}, {1, 0}};
  policy["1b"] = {{0, 2. / 3.}, {1, 1. / 3.}};
  policy["2p"] = {{0, 0}, {1, 1}};
  policy["2b"] = {{0, 0}, {1, 1}};
  return TabularPolicy(policy);
}
References SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Referenced by main().
Variable Documentation
kNumInfoStatesP0
const int open_spiel::kuhn_poker::kNumInfoStatesP0 = 6 inline constexpr
Definition at line 42 of file kuhn_poker.h.
kNumInfoStatesP1
const int open_spiel::kuhn_poker::kNumInfoStatesP1 = 6 inline constexpr
Definition at line 43 of file kuhn_poker.h.