open spiel: open_spiel.python.algorithms.sequence_form_utils Namespace Reference
open_spiel.python.algorithms.sequence_form_utils Namespace Reference
Functions
_get_isa_key (info_state, action)
_get_action_from_key (isa_key)
_get_infostate_from_key (isa_key)
is_root (key)
construct_vars (game)
uniform_random_seq (game, infoset_actions_to_seq)
_construct_vars (state, infosets, infoset_actions_to_seq, infoset_action_maps, infoset_parent_map, chance_reach, parent_is_keys, parent_isa_keys, payoff_dict, infoset_actions_children)
_construct_numpy_vars (payoff_dict, infoset_actions_to_seq)
sequence_to_policy (sequences, game, infoset_actions_to_seq, infoset_action_maps)
policy_to_sequence (game, policies, infoset_actions_to_seq)
_policy_to_sequence (state, policies, sequences, infoset_actions_to_seq, parent_seq_val)
Variables
str _DELIMITER = " -=- "
list _EMPTY_INFOSET_KEYS = ["***EMPTY_INFOSET_P0***", "***EMPTY_INFOSET_P1***"]
list _EMPTY_INFOSET_ACTION_KEYS
Detailed Description
Useful sequence form functions used in the MMD implementation.
Function Documentation
_construct_numpy_vars()
open_spiel.python.algorithms.sequence_form_utils._construct_numpy_vars (payoff_dict, infoset_actions_to_seq) protected
Convert sequence form payoff dict to numpy array.
Args:
    payoff_dict: a dict that maps ((infostate, action), (infostate, action))
      to the chance weighted reward.
    infoset_actions_to_seq: a list of dicts, one per player, that maps a
      string of (infostate, action) pair to an id.
Returns:
    A numpy array corresponding to the chance weighted rewards
    i.e. the sequence form payoff matrix.
Definition at line 215 of file sequence_form_utils.py.
def _construct_numpy_vars(payoff_dict, infoset_actions_to_seq):
  """Convert sequence form payoff dict to numpy array.
  Args:
      payoff_dict: a dict that maps ((infostate, action), (infostate, action))
        to the chance weighted reward.
      infoset_actions_to_seq: a list of dicts, one per player, that maps a
        string of (infostate, action) pair to an id.
  Returns:
      A numpy array corresponding to the chance weighted rewards
      i.e. the sequence form payoff matrix.
  """
  sequence_sizes = (len(infoset_actions_to_seq[0]),
                    len(infoset_actions_to_seq[1]))
  payoff_mat = np.zeros(sequence_sizes)
  for p1_sequence, i in infoset_actions_to_seq[0].items():
    for p2_sequence, j in infoset_actions_to_seq[1].items():
      payoff_mat[i, j] = payoff_dict.get((p1_sequence, p2_sequence), 0)
  return payoff_mat
References len.
Referenced by open_spiel.python.algorithms.sequence_form_utils.construct_vars().
_construct_vars()
open_spiel.python.algorithms.sequence_form_utils._construct_vars (state, infosets, infoset_actions_to_seq, infoset_action_maps, infoset_parent_map, chance_reach, parent_is_keys, parent_isa_keys, payoff_dict, infoset_actions_children) protected
Recursively builds maps and the sequence form payoff matrix.
Args:
    state: pyspiel (OpenSpiel) state
    infosets: a list of dicts, one per player, that maps infostate to an id.
      The dicts are filled by this function and should initially only
      contain root values.
    infoset_actions_to_seq: a list of dicts, one per player, that maps a
      string of (infostate, action) pair to an id. The dicts are filled by
      this function and should inirially only contain the root values.
    infoset_action_maps: a list of dicts, one per player, that maps each
      info_state to a list of (infostate, action) string.
    infoset_parent_map: a list of dicts, one per player, that maps each
      info_state to an (infostate, action) string.
    chance_reach: the contribution of chance's reach probability (should
      start at 1).
    parent_is_keys: a list of parent information state keys for this state
    parent_isa_keys: a list of parent (infostate, action) keys
    payoff_dict: a dict that maps ((infostate, action), (infostate, action))
      to the chance weighted reward
    infoset_actions_children: a list of dicts, one for each player, mapping
      (infostate, action) keys to reachable infostates for each player
Definition at line 126 of file sequence_form_utils.py.
                    infoset_actions_children):
  """Recursively builds maps and the sequence form payoff matrix.
  Args:
      state: pyspiel (OpenSpiel) state
      infosets: a list of dicts, one per player, that maps infostate to an id.
        The dicts are filled by this function and should initially only
        contain root values.
      infoset_actions_to_seq: a list of dicts, one per player, that maps a
        string of (infostate, action) pair to an id. The dicts are filled by
        this function and should inirially only contain the root values.
      infoset_action_maps: a list of dicts, one per player, that maps each
        info_state to a list of (infostate, action) string.
      infoset_parent_map: a list of dicts, one per player, that maps each
        info_state to an (infostate, action) string.
      chance_reach: the contribution of chance's reach probability (should
        start at 1).
      parent_is_keys: a list of parent information state keys for this state
      parent_isa_keys: a list of parent (infostate, action) keys
      payoff_dict: a dict that maps ((infostate, action), (infostate, action))
        to the chance weighted reward
      infoset_actions_children: a list of dicts, one for each player, mapping
        (infostate, action) keys to reachable infostates for each player
  """
  if state.is_terminal():
    returns = state.returns()
    matrix_index = (parent_isa_keys[0], parent_isa_keys[1])
    payoff_dict.setdefault(matrix_index, 0)
    # note the payoff matrix A is for the min max problem x.T @ A y
    # where x is player 0 in openspiel
    payoff_dict[matrix_index] += -returns[0] * chance_reach
    return
  if state.is_chance_node():
    for action, prob in state.chance_outcomes():
      new_state = state.child(action)
      _construct_vars(new_state, infosets, infoset_actions_to_seq,
                      infoset_action_maps, infoset_parent_map,
                      prob * chance_reach, parent_is_keys, parent_isa_keys,
                      payoff_dict, infoset_actions_children)
    return
  player = state.current_player()
  info_state = state.information_state_string(player)
  legal_actions = state.legal_actions(player)
  # Add to the infostate maps
  if info_state not in infosets[player]:
    infosets[player][info_state] = len(infosets[player])
  if info_state not in infoset_action_maps[player]:
    infoset_action_maps[player][info_state] = []
  # Add to infoset to parent infoset action map
  if info_state not in infoset_parent_map[player]:
    infoset_parent_map[player][info_state] = parent_isa_keys[player]
  # add as child to parent
  if parent_isa_keys[player] in infoset_actions_children[player]:
    if info_state not in infoset_actions_children[player][
        parent_isa_keys[player]]:
      infoset_actions_children[player][parent_isa_keys[player]].append(
          info_state)
  else:
    infoset_actions_children[player][parent_isa_keys[player]] = [info_state]
  new_parent_is_keys = parent_is_keys[:]
  new_parent_is_keys[player] = info_state
  for action in legal_actions:
    isa_key = _get_isa_key(info_state, action)
    if isa_key not in infoset_actions_to_seq[player]:
      infoset_actions_to_seq[player][isa_key] = len(
          infoset_actions_to_seq[player])
    if isa_key not in infoset_action_maps[player][info_state]:
      infoset_action_maps[player][info_state].append(isa_key)
    new_parent_isa_keys = parent_isa_keys[:]
    new_parent_isa_keys[player] = isa_key
    new_state = state.child(action)
    _construct_vars(new_state, infosets, infoset_actions_to_seq,
                    infoset_action_maps, infoset_parent_map, chance_reach,
                    new_parent_is_keys, new_parent_isa_keys, payoff_dict,
                    infoset_actions_children)
References open_spiel.python.algorithms.sequence_form_utils._construct_vars(), open_spiel.python.algorithms.sequence_form_utils._get_isa_key(), and len.
Referenced by open_spiel.python.algorithms.sequence_form_utils._construct_vars(), and open_spiel.python.algorithms.sequence_form_utils.construct_vars().
_get_action_from_key()
open_spiel.python.algorithms.sequence_form_utils._get_action_from_key (isa_key) protected
Definition at line 32 of file sequence_form_utils.py.
def _get_action_from_key(isa_key):
  _, action_str = isa_key.split(_DELIMITER)
  return int(action_str)
_get_infostate_from_key()
open_spiel.python.algorithms.sequence_form_utils._get_infostate_from_key (isa_key) protected
Definition at line 37 of file sequence_form_utils.py.
def _get_infostate_from_key(isa_key):
  assert not is_root(isa_key), "Cannot use this method for root nodes."
  infostate, _ = isa_key.split(_DELIMITER)
  return infostate
_get_isa_key()
open_spiel.python.algorithms.sequence_form_utils._get_isa_key (info_state, action) protected
Definition at line 28 of file sequence_form_utils.py.
def _get_isa_key(info_state, action):
  return info_state + _DELIMITER + str(action)
Referenced by open_spiel.python.algorithms.sequence_form_utils._construct_vars(), and open_spiel.python.algorithms.sequence_form_utils._policy_to_sequence().
_policy_to_sequence()
open_spiel.python.algorithms.sequence_form_utils._policy_to_sequence (state, policies, sequences, infoset_actions_to_seq, parent_seq_val) protected
Converts a TabularPolicy object to its equivalent sequence form.
This method modifies the sequences inplace and should not be called directly.
Args:
    state: an openspiel state.
    policies: a TabularPolicy object.
    sequences: list of numpy arrays to be modified.
    infoset_actions_to_seq: a list of dicts, one per player, that maps a
      string of (infostate, action) pair to an id.
    parent_seq_val: list of parent sequence values, this method should be
      called with initial value of [1,1].
Definition at line 303 of file sequence_form_utils.py.
                        parent_seq_val):
  """Converts a TabularPolicy object to its equivalent sequence form.
  This method modifies the sequences inplace and should not be called directly.
  Args:
      state: an openspiel state.
      policies: a TabularPolicy object.
      sequences: list of numpy arrays to be modified.
      infoset_actions_to_seq: a list of dicts, one per player, that maps a
        string of (infostate, action) pair to an id.
      parent_seq_val: list of parent sequence values, this method should be
        called with initial value of [1,1].
  """
  if state.is_terminal():
    return
  if state.is_chance_node():
    for action, _ in state.chance_outcomes():
      new_state = state.child(action)
      _policy_to_sequence(new_state, policies, sequences,
                          infoset_actions_to_seq, parent_seq_val)
    return
  player = state.current_player()
  info_state = state.information_state_string(player)
  legal_actions = state.legal_actions(player)
  state_policy = policies.policy_for_key(info_state)
  for action in legal_actions:
    isa_key = _get_isa_key(info_state, action)
    # update sequence form
    sequences[player][infoset_actions_to_seq[player]
                      [isa_key]] = parent_seq_val[player] * state_policy[action]
    new_parent_seq_val = parent_seq_val[:]
    new_parent_seq_val[player] = sequences[player][
        infoset_actions_to_seq[player][isa_key]]
    new_state = state.child(action)
    _policy_to_sequence(new_state, policies, sequences, infoset_actions_to_seq,
                        new_parent_seq_val)
References open_spiel.python.algorithms.sequence_form_utils._get_isa_key(), and open_spiel.python.algorithms.sequence_form_utils._policy_to_sequence().
Referenced by open_spiel.python.algorithms.sequence_form_utils._policy_to_sequence(), open_spiel.python.algorithms.sequence_form_utils.policy_to_sequence(), and open_spiel.python.algorithms.sequence_form_utils.uniform_random_seq().
construct_vars()
open_spiel.python.algorithms.sequence_form_utils.construct_vars (game)
Construct useful sequence from variables from game.
Args:
    game: The spiel game to solve (must be zero-sum, sequential, and have
      chance node of deterministic or explicit stochastic).
Returns:
    An 8 tuple of sequence form variables from _construct_vars by
    recursively
    traversing the game tree.
Definition at line 47 of file sequence_form_utils.py.
def construct_vars(game):
  """Construct useful sequence from variables from game.
  Args:
      game: The spiel game to solve (must be zero-sum, sequential, and have
        chance node of deterministic or explicit stochastic).
  Returns:
      An 8 tuple of sequence form variables from _construct_vars by
      recursively
      traversing the game tree.
  """
  initial_state = game.new_initial_state()
  # initialize variables
  infosets = [{_EMPTY_INFOSET_KEYS[0]: 0}, {_EMPTY_INFOSET_KEYS[1]: 0}]
  infoset_actions_to_seq = [{
      _EMPTY_INFOSET_ACTION_KEYS[0]: 0
  }, {
      _EMPTY_INFOSET_ACTION_KEYS[1]: 0
  }]
  infoset_action_maps = [{
      _EMPTY_INFOSET_KEYS[0]: [_EMPTY_INFOSET_ACTION_KEYS[0]]
  }, {
      _EMPTY_INFOSET_KEYS[1]: [_EMPTY_INFOSET_ACTION_KEYS[1]]
  }]
  # infoset_action_maps = [{}, {}]
  payoff_dict = dict()
  infoset_parent_map = [{
      _EMPTY_INFOSET_ACTION_KEYS[0]: None
  }, {
      _EMPTY_INFOSET_ACTION_KEYS[1]: None
  }]
  infoset_actions_children = [{
      _EMPTY_INFOSET_ACTION_KEYS[0]: []
  }, {
      _EMPTY_INFOSET_ACTION_KEYS[1]: []
  }]
  _construct_vars(initial_state, infosets, infoset_actions_to_seq,
                  infoset_action_maps, infoset_parent_map, 1.0,
                  _EMPTY_INFOSET_KEYS[:], _EMPTY_INFOSET_ACTION_KEYS[:],
                  payoff_dict, infoset_actions_children)
  payoff_mat = _construct_numpy_vars(payoff_dict, infoset_actions_to_seq)
  return (infosets, infoset_actions_to_seq,
          infoset_action_maps, infoset_parent_map,
          payoff_mat, infoset_actions_children)
References open_spiel.python.algorithms.sequence_form_utils._construct_numpy_vars(), and open_spiel.python.algorithms.sequence_form_utils._construct_vars().
is_root()
open_spiel.python.algorithms.sequence_form_utils.is_root (key)
Definition at line 43 of file sequence_form_utils.py.
def is_root(key):
  return True if key in _EMPTY_INFOSET_KEYS + _EMPTY_INFOSET_ACTION_KEYS else False
policy_to_sequence()
open_spiel.python.algorithms.sequence_form_utils.policy_to_sequence (game, policies, infoset_actions_to_seq)
Converts a TabularPolicy object for a two-player game.
The converted policy is its realization-equivalent sequence form one.
Args:
    game: a two-player open spiel game.
    policies: a TabularPolicy object.
    infoset_actions_to_seq: a list of dicts, one per player, that maps a
      string of (infostate, action) pair to an id.
Returns:
    A list of numpy arrays, one for each player.
Definition at line 279 of file sequence_form_utils.py.
def policy_to_sequence(game, policies, infoset_actions_to_seq):
  """Converts a TabularPolicy object for a two-player game.
  The converted policy is its realization-equivalent sequence form one.
  Args:
      game: a two-player open spiel game.
      policies: a TabularPolicy object.
      infoset_actions_to_seq: a list of dicts, one per player, that maps a
        string of (infostate, action) pair to an id.
  Returns:
      A list of numpy arrays, one for each player.
  """
  initial_state = game.new_initial_state()
  sequences = [
      np.ones(len(infoset_actions_to_seq[0])),
      np.ones(len(infoset_actions_to_seq[1]))
  ]
  _policy_to_sequence(initial_state, policies, sequences,
                      infoset_actions_to_seq, [1, 1])
  return sequences
References open_spiel.python.algorithms.sequence_form_utils._policy_to_sequence(), and len.
sequence_to_policy()
open_spiel.python.algorithms.sequence_form_utils.sequence_to_policy (sequences, game, infoset_actions_to_seq, infoset_action_maps)
Convert sequence form policies to the realization-equivalent tabular ones.
Args:
    sequences: list of two sequence form policies, one for each player.
    game: a spiel game with two players.
    infoset_actions_to_seq: a list of dicts, one per player, that maps a
      string of (infostate, action) pair to an id.
    infoset_action_maps: a list of dicts, one per player, that maps each
      info_state to a list of (infostate, action) string.
Returns:
    A TabularPolicy object.
Definition at line 238 of file sequence_form_utils.py.
                       infoset_action_maps):
  """Convert sequence form policies to the realization-equivalent tabular ones.
  Args:
      sequences: list of two sequence form policies, one for each player.
      game: a spiel game with two players.
      infoset_actions_to_seq: a list of dicts, one per player, that maps a
        string of (infostate, action) pair to an id.
      infoset_action_maps: a list of dicts, one per player, that maps each
        info_state to a list of (infostate, action) string.
  Returns:
      A TabularPolicy object.
  """
  policies = policy.TabularPolicy(game)
  for player in range(2):
    for info_state in infoset_action_maps[player]:
      if is_root(info_state):
        continue
      state_policy = policies.policy_for_key(info_state)
      total_weight = 0
      num_actions = 0
      for isa_key in infoset_action_maps[player][info_state]:
        total_weight += sequences[player][infoset_actions_to_seq[player]
                                          [isa_key]]
        num_actions += 1
      unif_pr = 1.0 / num_actions
      for isa_key in infoset_action_maps[player][info_state]:
        rel_weight = sequences[player][infoset_actions_to_seq[player][isa_key]]
        _, action_str = isa_key.split(_DELIMITER)
        action = int(action_str)
        pr_action = rel_weight / total_weight if total_weight > 0 else unif_pr
        state_policy[action] = pr_action
  return policies
uniform_random_seq()
open_spiel.python.algorithms.sequence_form_utils.uniform_random_seq (game, infoset_actions_to_seq)
Generate uniform random sequence.
The sequence generated is equivalent to a uniform random tabular policy.
Args:
    game: the spiel game to solve (must be zero-sum, sequential, and have
      chance mode of deterministic or explicit stochastic).
    infoset_actions_to_seq: a list of dicts, one per player, that maps a
      string of (infostate, action) pair to an id.
Returns:
    A list of NumPy arrays, one for each player.
Definition at line 101 of file sequence_form_utils.py.
def uniform_random_seq(game, infoset_actions_to_seq):
  """Generate uniform random sequence.
  The sequence generated is equivalent to a uniform random tabular policy.
  Args:
      game: the spiel game to solve (must be zero-sum, sequential, and have
        chance mode of deterministic or explicit stochastic).
      infoset_actions_to_seq: a list of dicts, one per player, that maps a
        string of (infostate, action) pair to an id.
  Returns:
      A list of NumPy arrays, one for each player.
  """
  policies = policy.TabularPolicy(game)
  initial_state = game.new_initial_state()
  sequences = [
      np.ones(len(infoset_actions_to_seq[0])),
      np.ones(len(infoset_actions_to_seq[1]))
  ]
  _policy_to_sequence(initial_state, policies, sequences,
                      infoset_actions_to_seq, [1, 1])
  return sequences
References open_spiel.python.algorithms.sequence_form_utils._policy_to_sequence(), and len.
Variable Documentation
_DELIMITER
str open_spiel.python.algorithms.sequence_form_utils._DELIMITER = " -=- " protected
Definition at line 21 of file sequence_form_utils.py.
_EMPTY_INFOSET_ACTION_KEYS
list open_spiel.python.algorithms.sequence_form_utils._EMPTY_INFOSET_ACTION_KEYS protected
Initial value:
=  [
    "***EMPTY_INFOSET_ACTION_P0***", "***EMPTY_INFOSET_ACTION_P1***"
]
Definition at line 23 of file sequence_form_utils.py.
_EMPTY_INFOSET_KEYS
list open_spiel.python.algorithms.sequence_form_utils._EMPTY_INFOSET_KEYS = ["***EMPTY_INFOSET_P0***", "***EMPTY_INFOSET_P1***"] protected
Definition at line 22 of file sequence_form_utils.py.