open spiel: open_spiel.python.algorithms.cfr Namespace Reference
open_spiel.python.algorithms.cfr Namespace Reference
Classes
class _CFRSolver
class _CFRSolverBase
class _InfoStateNode
class CFRPlusSolver
class CFRSolver
Functions
_apply_regret_matching_plus_reset (info_state_nodes)
_update_current_policy (current_policy, info_state_nodes)
_update_average_policy (average_policy, info_state_nodes)
_regret_matching (cumulative_regrets, legal_actions)
Detailed Description
Python implementation of the counterfactual regret minimization algorithm.
One iteration of CFR consists of:
1) Compute current strategy from regrets (e.g. using Regret Matching).
2) Compute values using the current strategy
3) Compute regrets from these values
The average policy is what converges to a Nash Equilibrium.
Function Documentation
_apply_regret_matching_plus_reset()
open_spiel.python.algorithms.cfr._apply_regret_matching_plus_reset (info_state_nodes) protected
Resets negative cumulative regrets to 0.
Regret Matching+ corresponds to the following cumulative regrets update:
cumulative_regrets = max(cumulative_regrets + regrets, 0)
This must be done at the level of the information set, and thus cannot be
done during the tree traversal (which is done on histories). It is thus
performed as an additional step.
This function is a module level function to be reused by both CFRSolver and
CFRBRSolver.
Args:
  info_state_nodes: A dictionary {`info_state_str` -> `_InfoStateNode`}.
Definition at line 47 of file cfr.py.
def _apply_regret_matching_plus_reset(info_state_nodes):
  """Resets negative cumulative regrets to 0.
  Regret Matching+ corresponds to the following cumulative regrets update:
  cumulative_regrets = max(cumulative_regrets + regrets, 0)
  This must be done at the level of the information set, and thus cannot be
  done during the tree traversal (which is done on histories). It is thus
  performed as an additional step.
  This function is a module level function to be reused by both CFRSolver and
  CFRBRSolver.
  Args:
    info_state_nodes: A dictionary {`info_state_str` -> `_InfoStateNode`}.
  """
  for info_state_node in info_state_nodes.values():
    action_to_cum_regret = info_state_node.cumulative_regret
    for action, cumulative_regret in action_to_cum_regret.items():
      if cumulative_regret < 0:
        action_to_cum_regret[action] = 0
_regret_matching()
open_spiel.python.algorithms.cfr._regret_matching (cumulative_regrets, legal_actions) protected
Returns an info state policy by applying regret-matching.
Args:
  cumulative_regrets: A {action: cumulative_regret} dictionary.
  legal_actions: the list of legal actions at this state.
Returns:
  A dict of action -> prob for all legal actions.
Definition at line 349 of file cfr.py.
def _regret_matching(cumulative_regrets, legal_actions):
  """Returns an info state policy by applying regret-matching.
  Args:
    cumulative_regrets: A {action: cumulative_regret} dictionary.
    legal_actions: the list of legal actions at this state.
  Returns:
    A dict of action -> prob for all legal actions.
  """
  regrets = cumulative_regrets.values()
  sum_positive_regrets = sum((regret for regret in regrets if regret > 0))
  info_state_policy = {}
  if sum_positive_regrets > 0:
    for action in legal_actions:
      positive_action_regret = max(0.0, cumulative_regrets[action])
      info_state_policy[action] = (
          positive_action_regret / sum_positive_regrets)
  else:
    for action in legal_actions:
      info_state_policy[action] = 1.0 / len(legal_actions)
  return info_state_policy
References len.
Referenced by open_spiel.python.algorithms.cfr._update_current_policy().
_update_average_policy()
open_spiel.python.algorithms.cfr._update_average_policy (average_policy, info_state_nodes) protected
Updates in place `average_policy` to the average of all policies iterated.
This function is a module level function to be reused by both CFRSolver and
CFRBRSolver.
Args:
  average_policy: A `policy.TabularPolicy` to be updated in-place.
  info_state_nodes: A dictionary {`info_state_str` -> `_InfoStateNode`}.
Definition at line 89 of file cfr.py.
def _update_average_policy(average_policy, info_state_nodes):
  """Updates in place `average_policy` to the average of all policies iterated.
  This function is a module level function to be reused by both CFRSolver and
  CFRBRSolver.
  Args:
    average_policy: A `policy.TabularPolicy` to be updated in-place.
    info_state_nodes: A dictionary {`info_state_str` -> `_InfoStateNode`}.
  """
  for info_state, info_state_node in info_state_nodes.items():
    info_state_policies_sum = info_state_node.cumulative_policy
    state_policy = average_policy.policy_for_key(info_state)
    probabilities_sum = sum(info_state_policies_sum.values())
    if probabilities_sum == 0:
      num_actions = len(info_state_node.legal_actions)
      for action in info_state_node.legal_actions:
        state_policy[action] = 1 / num_actions
    else:
      for action, action_prob_sum in info_state_policies_sum.items():
        state_policy[action] = action_prob_sum / probabilities_sum
References len.
Referenced by open_spiel.python.algorithms.cfr._CFRSolverBase.average_policy().
_update_current_policy()
open_spiel.python.algorithms.cfr._update_current_policy (current_policy, info_state_nodes) protected
Updates in place `current_policy` from the cumulative regrets.
This function is a module level function to be reused by both CFRSolver and
CFRBRSolver.
Args:
  current_policy: A `policy.TabularPolicy` to be updated in-place.
  info_state_nodes: A dictionary {`info_state_str` -> `_InfoStateNode`}.
Definition at line 70 of file cfr.py.
def _update_current_policy(current_policy, info_state_nodes):
  """Updates in place `current_policy` from the cumulative regrets.
  This function is a module level function to be reused by both CFRSolver and
  CFRBRSolver.
  Args:
    current_policy: A `policy.TabularPolicy` to be updated in-place.
    info_state_nodes: A dictionary {`info_state_str` -> `_InfoStateNode`}.
  """
  for info_state, info_state_node in info_state_nodes.items():
    state_policy = current_policy.policy_for_key(info_state)
    for action, value in _regret_matching(
        info_state_node.cumulative_regret,
        info_state_node.legal_actions).items():
      state_policy[action] = value
References open_spiel.python.algorithms.cfr._regret_matching().