open spiel: open_spiel.python.tests.policy_test Namespace Reference
open_spiel.python.tests.policy_test Namespace Reference
Classes
class ChildTest
class CommonTest
class DerivedPolicyTest
class JointActionProbTest
class MergeTabularPoliciesTest
class TabularPolicyTest
class TabularRockPaperScissorsPolicyTest
class TabularTicTacToePolicyTest
class UniformRandomPolicyTest
Functions
test_policy_on_game (self, game, policy_object, player=-1)
Variables
int SEED = 187461917
list _TIC_TAC_TOE_STATES
_LEDUC_POKER = pyspiel.load_game("leduc_poker")
Detailed Description
Tests for open_spiel.python.policy.
Function Documentation
test_policy_on_game()
open_spiel.python.tests.policy_test.test_policy_on_game (self, game, policy_object, player = -1)
Checks the policy conforms to the conventions.
Checks the Policy.action_probabilities contains only legal actions (but not
necessarily all).
Checks that the probabilities are positive and sum to 1.
Args:
  self: The Test class. This methid targets as being used as a utility
    function to test policies.
  game: A `pyspiel.Game`, same as the one used in the policy.
  policy_object: A `policy.Policy` object on `game`. to test.
  player: Restrict testing policy to a player.
Definition at line 141 of file policy_test.py.
def test_policy_on_game(self, game, policy_object, player=-1):
  """Checks the policy conforms to the conventions.
  Checks the Policy.action_probabilities contains only legal actions (but not
  necessarily all).
  Checks that the probabilities are positive and sum to 1.
  Args:
    self: The Test class. This methid targets as being used as a utility
      function to test policies.
    game: A `pyspiel.Game`, same as the one used in the policy.
    policy_object: A `policy.Policy` object on `game`. to test.
    player: Restrict testing policy to a player.
  """
  all_states = get_all_states.get_all_states(
      game,
      depth_limit=-1,
      include_terminals=False,
      include_chance_states=False,
      to_string=lambda s: s.information_state_string())
  for state in all_states.values():
    legal_actions = set(state.legal_actions())
    action_probabilities = policy_object.action_probabilities(state)
    for action in action_probabilities.keys():
      # We want a clearer error message to be able to debug.
      actions_missing = set(legal_actions) - set(action_probabilities.keys())
      illegal_actions = set(action_probabilities.keys()) - set(legal_actions)
      self.assertIn(
          action,
          legal_actions,
          msg="The action {} is present in the policy but is not a legal "
          "actions (these are {})\n"
          "Legal actions missing from policy: {}\n"
          "Illegal actions present in policy: {}".format(
              action, legal_actions, actions_missing, illegal_actions))
    sum_ = 0
    for prob in action_probabilities.values():
      sum_ += prob
      self.assertGreaterEqual(prob, 0)
    if player < 0 or state.current_player() == player:
      self.assertAlmostEqual(1, sum_)
    else:
      self.assertAlmostEqual(0, sum_)
Referenced by open_spiel.python.tests.policy_test.CommonTest.test_cpp_player_policies_on_leduc(), open_spiel.python.tests.policy_test.CommonTest.test_cpp_policies_on_leduc(), and open_spiel.python.tests.policy_test.CommonTest.test_policy_on_leduc().
Variable Documentation
_LEDUC_POKER
open_spiel.python.tests.policy_test._LEDUC_POKER = pyspiel.load_game("leduc_poker") protected
Definition at line 190 of file policy_test.py.
_TIC_TAC_TOE_STATES
list open_spiel.python.tests.policy_test._TIC_TAC_TOE_STATES protected
Initial value:
=  [
    {
        # ...
        # xoo
        # ..x
        "state": "3, 4, 8, 5",
        "legal_actions": (0, 1, 2, 6, 7)
    },
    {
        # xo.
        # oxx
        # o..
        "state": "4, 1, 0, 3, 5, 6",
        "legal_actions": (2, 7, 8)
    },
    {
        # ...
        # ...
        # ...
        "state": "",
        "legal_actions": (0, 1, 2, 3, 4, 5, 6, 7, 8)
    }
]
Definition at line 29 of file policy_test.py.
SEED
int open_spiel.python.tests.policy_test.SEED = 187461917
Definition at line 27 of file policy_test.py.