open spiel: open_spiel::crowd_modelling_2d Namespace Reference
open_spiel::crowd_modelling_2d Namespace Reference
Classes
class CrowdModelling2dGame
class CrowdModelling2dState
Functions
std::vector< absl::string_view > ProcessStringParam (const std::string &string_param_str, int max_size)
Variables
constexpr int kNumPlayers = 1
constexpr int kDefaultHorizon = 10
constexpr int kDefaultSize = 10
constexpr int kNumActions = 5
constexpr int kNumChanceActions = 5
constexpr bool kDefaultOnlyDistributionReward = false
constexpr bool kDefaultWithCongestion = false
constexpr double kDefaultNoiseIntensity = 1.0
constexpr double kDefaultCrowdAversionCoef = 1.0
constexpr const char * kDefaultForbiddenStates = "[]"
constexpr const char * kDefaultInitialDistribution = "[]"
constexpr const char * kDefaultInitialDistributionValue = "[]"
constexpr const char * kDefaultPositionalReward = "[]"
constexpr const char * kDefaultPositionalRewardValue = "[]"
constexpr int kNeutralAction = 2
Function Documentation
ProcessStringParam()
std::vector< absl::string_view > open_spiel::crowd_modelling_2d::ProcessStringParam (const std::string & string_param_str, int max_size)
Definition at line 37 of file crowd_modelling_2d.cc.
{
  // ProcessStringParam takes a parameter string and split it is a sequence of
  // substring. Example:
  // "" -> {}
  // "[0|0;0|1]" -> {"0|0", "0|1"}
  // "[0.5;0.5]" -> {"0.5", "0.5"}
  absl::string_view string_param = absl::StripAsciiWhitespace(string_param_str);
  SPIEL_CHECK_TRUE(absl::ConsumePrefix(&string_param, "["));
  SPIEL_CHECK_TRUE(absl::ConsumeSuffix(&string_param, "]"));
  std::vector<absl::string_view> split_string_list;
  if (!string_param.empty()) {
    split_string_list = absl::StrSplit(string_param, ';');
  }
  SPIEL_CHECK_GE(split_string_list.size(), 0);
  SPIEL_CHECK_LE(split_string_list.size(), max_size * max_size);
  return split_string_list;
}
References absl::ConsumePrefix(), absl::ConsumeSuffix(), absl::string_view::empty(), SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_TRUE, absl::StripAsciiWhitespace(), and absl::StrSplit().
Referenced by open_spiel::crowd_modelling_2d::CrowdModelling2dState::CrowdModelling2dState().
Variable Documentation
kDefaultCrowdAversionCoef
double open_spiel::crowd_modelling_2d::kDefaultCrowdAversionCoef = 1.0 inline constexpr
Definition at line 52 of file crowd_modelling_2d.h.
kDefaultForbiddenStates
const char* open_spiel::crowd_modelling_2d::kDefaultForbiddenStates = "[]" inline constexpr
Definition at line 55 of file crowd_modelling_2d.h.
kDefaultHorizon
int open_spiel::crowd_modelling_2d::kDefaultHorizon = 10 inline constexpr
Definition at line 42 of file crowd_modelling_2d.h.
kDefaultInitialDistribution
const char* open_spiel::crowd_modelling_2d::kDefaultInitialDistribution = "[]" inline constexpr
Definition at line 57 of file crowd_modelling_2d.h.
kDefaultInitialDistributionValue
const char* open_spiel::crowd_modelling_2d::kDefaultInitialDistributionValue = "[]" inline constexpr
Definition at line 59 of file crowd_modelling_2d.h.
kDefaultNoiseIntensity
double open_spiel::crowd_modelling_2d::kDefaultNoiseIntensity = 1.0 inline constexpr
Definition at line 51 of file crowd_modelling_2d.h.
kDefaultOnlyDistributionReward
bool open_spiel::crowd_modelling_2d::kDefaultOnlyDistributionReward = false inline constexpr
Definition at line 46 of file crowd_modelling_2d.h.
kDefaultPositionalReward
const char* open_spiel::crowd_modelling_2d::kDefaultPositionalReward = "[]" inline constexpr
Definition at line 61 of file crowd_modelling_2d.h.
kDefaultPositionalRewardValue
const char* open_spiel::crowd_modelling_2d::kDefaultPositionalRewardValue = "[]" inline constexpr
Definition at line 63 of file crowd_modelling_2d.h.
kDefaultSize
int open_spiel::crowd_modelling_2d::kDefaultSize = 10 inline constexpr
Definition at line 43 of file crowd_modelling_2d.h.
kDefaultWithCongestion
bool open_spiel::crowd_modelling_2d::kDefaultWithCongestion = false inline constexpr
Definition at line 47 of file crowd_modelling_2d.h.
kNeutralAction
int open_spiel::crowd_modelling_2d::kNeutralAction = 2 inline constexpr
Definition at line 66 of file crowd_modelling_2d.h.
Referenced by open_spiel::crowd_modelling_2d::CrowdModelling2dState::ChanceOutcomes().
kNumActions
int open_spiel::crowd_modelling_2d::kNumActions = 5 inline constexpr
Definition at line 44 of file crowd_modelling_2d.h.
Referenced by open_spiel::crowd_modelling_2d::CrowdModelling2dState::LegalPlayerActions(), and open_spiel::crowd_modelling_2d::CrowdModelling2dGame::NumDistinctActions().
kNumChanceActions
int open_spiel::crowd_modelling_2d::kNumChanceActions = 5 inline constexpr
Definition at line 45 of file crowd_modelling_2d.h.
Referenced by open_spiel::crowd_modelling_2d::CrowdModelling2dGame::MaxChanceOutcomes().
kNumPlayers
int open_spiel::crowd_modelling_2d::kNumPlayers = 1 inline constexpr
Definition at line 41 of file crowd_modelling_2d.h.
Referenced by open_spiel::crowd_modelling_2d::CrowdModelling2dGame::NumPlayers().