open spiel: open_spiel.python.pytorch.losses.rl_losses Namespace Reference
open_spiel.python.pytorch.losses.rl_losses Namespace Reference
Classes
class BatchA2CLoss
class BatchNeuRDLoss
class BatchQPGLoss
class BatchRMLoss
class BatchRPGLoss
Functions
_assert_rank_and_shape_compatibility (tensors, rank)
thresholded (logits, regrets, threshold=2.0)
compute_baseline (policy, action_values)
compute_regrets (policy_logits, action_values)
compute_advantages (policy_logits, action_values, use_relu=False, threshold_fn=None)
compute_a2c_loss (policy_logits, actions, advantages)
compute_entropy (policy_logits)
Detailed Description
Reinforcement learning loss functions.
All the loss functions implemented here compute the loss for the policy (actor).
The critic loss functions are typically regression loss are omitted for their
simplicity.
For the batch QPG, RM and RPG loss, please refer to the paper:
https://papers.nips.cc/paper/7602-actor-critic-policy-optimization-in-partially-observable-multiagent-environments.pdf
The BatchA2C loss uses code from the `TRFL` library:
https://github.com/deepmind/trfl/blob/master/trfl/discrete_policy_gradient_ops.py
Function Documentation
_assert_rank_and_shape_compatibility()
open_spiel.python.pytorch.losses.rl_losses._assert_rank_and_shape_compatibility (tensors, rank) protected
Definition at line 32 of file rl_losses.py.
def _assert_rank_and_shape_compatibility(tensors, rank):
  if not tensors:
    raise ValueError("List of tensors cannot be empty")
  tmp_shape = tensors[0].shape
  for tensor in tensors:
    if tensor.ndim != rank:
      raise ValueError("Shape %s must have rank %d" % (tensor.ndim, rank))
    if tensor.shape != tmp_shape:
      raise ValueError("Shapes %s and %s are not compatible" %
                       (tensor.shape, tmp_shape))
Referenced by open_spiel.python.pytorch.losses.rl_losses.BatchA2CLoss.loss(), open_spiel.python.pytorch.losses.rl_losses.BatchNeuRDLoss.loss(), open_spiel.python.pytorch.losses.rl_losses.BatchQPGLoss.loss(), open_spiel.python.pytorch.losses.rl_losses.BatchRMLoss.loss(), and open_spiel.python.pytorch.losses.rl_losses.BatchRPGLoss.loss().
compute_a2c_loss()
open_spiel.python.pytorch.losses.rl_losses.compute_a2c_loss (policy_logits, actions, advantages)
Definition at line 101 of file rl_losses.py.
def compute_a2c_loss(policy_logits, actions, advantages):
  cross_entropy = F.cross_entropy(policy_logits, actions, reduction="none")
  advantages = advantages.detach()
  if advantages.ndim != cross_entropy.ndim:
    raise ValueError("Shapes %s and %s are not compatible" %
                     (advantages.ndim, cross_entropy.ndim))
  return torch.mul(cross_entropy, advantages)
Referenced by open_spiel.python.pytorch.losses.rl_losses.BatchA2CLoss.loss().
compute_advantages()
open_spiel.python.pytorch.losses.rl_losses.compute_advantages (policy_logits, action_values, use_relu = False, threshold_fn = None)
Compute advantages using pi and Q.
Definition at line 74 of file rl_losses.py.
                       threshold_fn=None):
  """Compute advantages using pi and Q."""
  # Compute advantage.
  policy = F.softmax(policy_logits, dim=1)
  # Avoid computing gradients for action_values.
  action_values = action_values.detach()
  baseline = compute_baseline(policy, action_values)
  advantages = action_values - torch.unsqueeze(baseline, 1)
  if use_relu:
    advantages = F.relu(advantages)
  if threshold_fn:
    # Compute thresholded advanteges weighted by policy logits for NeuRD.
    policy_logits = policy_logits - policy_logits.mean(-1, keepdim=True)
    advantages = threshold_fn(policy_logits, advantages)
    policy_advantages = -torch.mul(policy_logits, advantages.detach())
  else:
    # Compute advantage weighted by policy.
    policy_advantages = -torch.mul(policy, advantages.detach())
  return torch.sum(policy_advantages, dim=1)
References open_spiel.python.pytorch.losses.rl_losses.compute_baseline().
Referenced by open_spiel.python.pytorch.losses.rl_losses.BatchNeuRDLoss.loss(), open_spiel.python.pytorch.losses.rl_losses.BatchQPGLoss.loss(), and open_spiel.python.pytorch.losses.rl_losses.BatchRMLoss.loss().
compute_baseline()
open_spiel.python.pytorch.losses.rl_losses.compute_baseline (policy, action_values)
Definition at line 54 of file rl_losses.py.
def compute_baseline(policy, action_values):
  # V = pi * Q, backprop through pi but not Q.
  return torch.sum(torch.mul(policy, action_values.detach()), dim=1)
Referenced by open_spiel.python.pytorch.losses.rl_losses.compute_advantages(), and open_spiel.python.pytorch.losses.rl_losses.compute_regrets().
compute_entropy()
open_spiel.python.pytorch.losses.rl_losses.compute_entropy (policy_logits)
Definition at line 110 of file rl_losses.py.
def compute_entropy(policy_logits):
  return torch.sum(
      -F.softmax(policy_logits, dim=1) * F.log_softmax(policy_logits, dim=1),
      dim=-1)
Referenced by open_spiel.python.pytorch.losses.rl_losses.BatchA2CLoss.loss(), open_spiel.python.pytorch.losses.rl_losses.BatchNeuRDLoss.loss(), open_spiel.python.pytorch.losses.rl_losses.BatchQPGLoss.loss(), open_spiel.python.pytorch.losses.rl_losses.BatchRMLoss.loss(), and open_spiel.python.pytorch.losses.rl_losses.BatchRPGLoss.loss().
compute_regrets()
open_spiel.python.pytorch.losses.rl_losses.compute_regrets (policy_logits, action_values)
Compute regrets using pi and Q.
Definition at line 59 of file rl_losses.py.
def compute_regrets(policy_logits, action_values):
  """Compute regrets using pi and Q."""
  # Compute regret.
  policy = F.softmax(policy_logits, dim=1)
  # Avoid computing gradients for action_values.
  action_values = action_values.detach()
  baseline = compute_baseline(policy, action_values)
  regrets = torch.sum(
      F.relu(action_values - torch.unsqueeze(baseline, 1)), dim=1)
  return regrets
References open_spiel.python.pytorch.losses.rl_losses.compute_baseline().
Referenced by open_spiel.python.pytorch.losses.rl_losses.BatchRPGLoss.loss().
thresholded()
open_spiel.python.pytorch.losses.rl_losses.thresholded (logits, regrets, threshold = 2.0)
Zeros out `regrets` where `logits` are too negative or too large.
Definition at line 45 of file rl_losses.py.
def thresholded(logits, regrets, threshold=2.0):
  """Zeros out `regrets` where `logits` are too negative or too large."""
  can_decrease = logits.gt(-threshold).float()
  can_increase = logits.lt(threshold).float()
  regrets_negative = regrets.clamp(max=0.0)
  regrets_positive = regrets.clamp(min=0.0)
  return can_decrease * regrets_negative + can_increase * regrets_positive