open spiel: open_spiel.python.algorithms.projected_replicator_dynamics Namespace Reference
open_spiel.python.algorithms.projected_replicator_dynamics Namespace Reference
Functions
_partial_multi_dot (player_payoff_tensor, strategies, index_avoided)
_project_distribution (updated_strategy, gamma)
_approx_simplex_projection (updated_strategy, gamma=0.0)
_simplex_projection (updated_strategy, gamma=0.0)
_projected_replicator_dynamics_step (payoff_tensors, strategies, dt, gamma, use_approx=False)
projected_replicator_dynamics (payoff_tensors, prd_initial_strategies=None, prd_iterations=int(1e5), prd_dt=1e-3, prd_gamma=1e-6, average_over_last_n_strategies=None, use_approx=False, **unused_kwargs)
Detailed Description
Projected Replicator Dynamics Algorithm.
This is an N-player implementation of the Projected Replicator Dynamics
algorithm described in Lanctot et al., 2017: https://arxiv.org/abs/1711.00832.
Function Documentation
_approx_simplex_projection()
open_spiel.python.algorithms.projected_replicator_dynamics._approx_simplex_projection (updated_strategy, gamma = 0.0) protected
Approximately projects the distribution in updated_x to have minimal probabilities.
Minimal probabilities are set as gamma, and the probabilities are then
renormalized to sum to 1.
Args:
  updated_strategy: New distribution value after being updated by update rule.
  gamma: minimal probability value when divided by number of actions.
Returns:
  Projected distribution.
Definition at line 74 of file projected_replicator_dynamics.py.
def _approx_simplex_projection(updated_strategy, gamma=0.0):
  """Approximately projects the distribution in updated_x to have minimal probabilities.
  Minimal probabilities are set as gamma, and the probabilities are then
  renormalized to sum to 1.
  Args:
    updated_strategy: New distribution value after being updated by update rule.
    gamma: minimal probability value when divided by number of actions.
  Returns:
    Projected distribution.
  """
  # Epsilon approximation of L2-norm projection onto the Delta_gamma space.
  updated_strategy[updated_strategy < gamma] = gamma
  updated_strategy = updated_strategy / np.sum(updated_strategy)
  return updated_strategy
Referenced by open_spiel.python.algorithms.projected_replicator_dynamics._projected_replicator_dynamics_step().
_partial_multi_dot()
open_spiel.python.algorithms.projected_replicator_dynamics._partial_multi_dot (player_payoff_tensor, strategies, index_avoided) protected
Computes a generalized dot product avoiding one dimension.
This is used to directly get the expected return of a given action, given
other players' strategies, for the player indexed by index_avoided.
Note that the numpy.dot function is used to compute this product, as it ended
up being (Slightly) faster in performance tests than np.tensordot. Using the
reduce function proved slower for both np.dot and np.tensordot.
Args:
  player_payoff_tensor: payoff tensor for player[index_avoided], of dimension
    (dim(vector[0]), dim(vector[1]), ..., dim(vector[-1])).
  strategies: Meta strategy probabilities for each player.
  index_avoided: Player for which we do not compute the dot product.
Returns:
  Vector of expected returns for each action of player [the player indexed by
    index_avoided].
Definition at line 26 of file projected_replicator_dynamics.py.
def _partial_multi_dot(player_payoff_tensor, strategies, index_avoided):
  """Computes a generalized dot product avoiding one dimension.
  This is used to directly get the expected return of a given action, given
  other players' strategies, for the player indexed by index_avoided.
  Note that the numpy.dot function is used to compute this product, as it ended
  up being (Slightly) faster in performance tests than np.tensordot. Using the
  reduce function proved slower for both np.dot and np.tensordot.
  Args:
    player_payoff_tensor: payoff tensor for player[index_avoided], of dimension
      (dim(vector[0]), dim(vector[1]), ..., dim(vector[-1])).
    strategies: Meta strategy probabilities for each player.
    index_avoided: Player for which we do not compute the dot product.
  Returns:
    Vector of expected returns for each action of player [the player indexed by
      index_avoided].
  """
  new_axis_order = [index_avoided] + [
      i for i in range(len(strategies)) if (i != index_avoided)
  ]
  accumulator = np.transpose(player_payoff_tensor, new_axis_order)
  for i in range(len(strategies) - 1, -1, -1):
    if i != index_avoided:
      accumulator = np.dot(accumulator, strategies[i])
  return accumulator
References len.
Referenced by open_spiel.python.algorithms.projected_replicator_dynamics._projected_replicator_dynamics_step().
_project_distribution()
open_spiel.python.algorithms.projected_replicator_dynamics._project_distribution (updated_strategy, gamma) protected
Projects the distribution in updated_x to have minimal probabilities.
Minimal probabilities are set as gamma, and the probabilities are then
renormalized to sum to 1.
Args:
  updated_strategy: New distribution value after being updated by update rule.
  gamma: minimal probability value when divided by number of actions.
Returns:
  Projected distribution.
Definition at line 55 of file projected_replicator_dynamics.py.
def _project_distribution(updated_strategy, gamma):
  """Projects the distribution in updated_x to have minimal probabilities.
  Minimal probabilities are set as gamma, and the probabilities are then
  renormalized to sum to 1.
  Args:
    updated_strategy: New distribution value after being updated by update rule.
    gamma: minimal probability value when divided by number of actions.
  Returns:
    Projected distribution.
  """
  # Epsilon approximation of L2-norm projection onto the Delta_gamma space.
  updated_strategy[updated_strategy < gamma] = gamma
  updated_strategy = updated_strategy / np.sum(updated_strategy)
  return updated_strategy
_projected_replicator_dynamics_step()
open_spiel.python.algorithms.projected_replicator_dynamics._projected_replicator_dynamics_step (payoff_tensors, strategies, dt, gamma, use_approx = False) protected
Does one step of the projected replicator dynamics algorithm.
Args:
  payoff_tensors: List of payoff tensors for each player.
  strategies: List of the strategies used by each player.
  dt: Update amplitude term.
  gamma: Minimum exploratory probability term.
  use_approx: use approximate simplex projection.
Returns:
  A list of updated strategies for each player.
Definition at line 122 of file projected_replicator_dynamics.py.
                                        use_approx=False):
  """Does one step of the projected replicator dynamics algorithm.
  Args:
    payoff_tensors: List of payoff tensors for each player.
    strategies: List of the strategies used by each player.
    dt: Update amplitude term.
    gamma: Minimum exploratory probability term.
    use_approx: use approximate simplex projection.
  Returns:
    A list of updated strategies for each player.
  """
  # TODO(author4): Investigate whether this update could be fully vectorized.
  new_strategies = []
  for player in range(len(payoff_tensors)):
    current_payoff_tensor = payoff_tensors[player]
    current_strategy = strategies[player]
    values_per_strategy = _partial_multi_dot(current_payoff_tensor, strategies,
                                             player)
    average_return = np.dot(values_per_strategy, current_strategy)
    delta = current_strategy * (values_per_strategy - average_return)
    updated_strategy = current_strategy + dt * delta
    updated_strategy = (
        _approx_simplex_projection(updated_strategy, gamma) if use_approx
        else _simplex_projection(updated_strategy, gamma))
    new_strategies.append(updated_strategy)
  return new_strategies
References open_spiel.python.algorithms.projected_replicator_dynamics._approx_simplex_projection(), open_spiel.python.algorithms.projected_replicator_dynamics._partial_multi_dot(), and len.
Referenced by open_spiel.python.algorithms.projected_replicator_dynamics.projected_replicator_dynamics().
_simplex_projection()
open_spiel.python.algorithms.projected_replicator_dynamics._simplex_projection (updated_strategy, gamma = 0.0) protected
Project updated_strategy on the closest point in L2-norm on gamma-simplex.
Based on: https://eng.ucmerced.edu/people/wwang5/papers/SimplexProj.pdf
Args:
  updated_strategy: New distribution value after being updated by update rule.
  gamma: minimal probability value when divided by number of actions.
Returns:
  Projected distribution
Algorithm description:
It aims to find a scalar lam to be substracted by each dimension of v
with the restriction that the resulted quantity should lie in [gamma, 1]
until the resulted vector summed up to 1
Example: [0.4, 0.7, 0.6], 0.2 -- > find lam=0.25
          --> [max(0.4-0.25, 0.2), max(0.7-0.25, 0.2), max(0.6-0.25, 0.2)]
          --> [0.2,  0.45, 0.35]
Definition at line 93 of file projected_replicator_dynamics.py.
def _simplex_projection(updated_strategy, gamma=0.0):
  """Project updated_strategy on the closest point in L2-norm on gamma-simplex.
  Based on: https://eng.ucmerced.edu/people/wwang5/papers/SimplexProj.pdf
  Args:
    updated_strategy: New distribution value after being updated by update rule.
    gamma: minimal probability value when divided by number of actions.
  Returns:
    Projected distribution
  Algorithm description:
  It aims to find a scalar lam to be substracted by each dimension of v
  with the restriction that the resulted quantity should lie in [gamma, 1]
  until the resulted vector summed up to 1
  Example: [0.4, 0.7, 0.6], 0.2 -- > find lam=0.25
            --> [max(0.4-0.25, 0.2), max(0.7-0.25, 0.2), max(0.6-0.25, 0.2)]
            --> [0.2,  0.45, 0.35]
  """
  n = len(updated_strategy)
  idx = np.arange(1, n + 1)
  u = np.sort(updated_strategy)[::-1]
  u_tmp = (1 - np.cumsum(u) - (n - idx) * gamma) / idx
  rho = np.searchsorted(u + u_tmp <= gamma, True)
  return np.maximum(updated_strategy + u_tmp[rho - 1], gamma)
References len.
projected_replicator_dynamics()
open_spiel.python.algorithms.projected_replicator_dynamics.projected_replicator_dynamics (payoff_tensors, prd_initial_strategies = None, prd_iterations = int(1e5), prd_dt = 1e-3, prd_gamma = 1e-6, average_over_last_n_strategies = None, use_approx = False, ** unused_kwargs)
The Projected Replicator Dynamics algorithm.
Args:
  payoff_tensors: List of payoff tensors for each player.
  prd_initial_strategies: Initial list of the strategies used by each player,
    if any. Could be used to speed up the search by providing a good initial
    solution.
  prd_iterations: Number of algorithmic steps to take before returning an
    answer.
  prd_dt: Update amplitude term.
  prd_gamma: Minimum exploratory probability term.
  average_over_last_n_strategies: Running average window size for average
    policy computation. If None, use the whole trajectory.
  use_approx: use the approximate simplex projection.
  **unused_kwargs: Convenient way of exposing an API compatible with other
    methods with possibly different arguments.
Returns:
  PRD-computed strategies.
Definition at line 156 of file projected_replicator_dynamics.py.
                                  **unused_kwargs):
  """The Projected Replicator Dynamics algorithm.
  Args:
    payoff_tensors: List of payoff tensors for each player.
    prd_initial_strategies: Initial list of the strategies used by each player,
      if any. Could be used to speed up the search by providing a good initial
      solution.
    prd_iterations: Number of algorithmic steps to take before returning an
      answer.
    prd_dt: Update amplitude term.
    prd_gamma: Minimum exploratory probability term.
    average_over_last_n_strategies: Running average window size for average
      policy computation. If None, use the whole trajectory.
    use_approx: use the approximate simplex projection.
    **unused_kwargs: Convenient way of exposing an API compatible with other
      methods with possibly different arguments.
  Returns:
    PRD-computed strategies.
  """
  number_players = len(payoff_tensors)
  # Number of actions available to each player.
  action_space_shapes = payoff_tensors[0].shape
  # If no initial starting position is given, start with uniform probabilities.
  new_strategies = prd_initial_strategies or [
      np.ones(action_space_shapes[k]) / action_space_shapes[k]
      for k in range(number_players)
  ]
  averager = nfg_utils.StrategyAverager(number_players, action_space_shapes,
                                        average_over_last_n_strategies)
  averager.append(new_strategies)
  for _ in range(prd_iterations):
    new_strategies = _projected_replicator_dynamics_step(
        payoff_tensors, new_strategies, prd_dt, prd_gamma, use_approx)
    averager.append(new_strategies)
  return averager.average_strategies()
References open_spiel.python.algorithms.projected_replicator_dynamics._projected_replicator_dynamics_step(), and len.