open spiel: open_spiel.python.bots.bluechip_bridge Namespace Reference
open_spiel.python.bots.bluechip_bridge Namespace Reference
Classes
class BlueChipBridgeBot
Functions
_bid_to_action (action_str)
_play_to_action (action_str)
_action_to_string (action)
_expect_regex (controller, regex)
_expect (controller, expected)
_hand_string (cards)
_connect (controller, seat)
_new_deal (controller, seat, hand, board)
Variables
str GAME_STR = "bridge(use_double_dummy_result=False)"
str _CONNECT = 'Connecting "(?P<client_name>.*)" as ANYPL using protocol version 18'
tuple _PLAYER_ACTION
tuple _READY_FOR_OTHER
str _READY_FOR_TEAMS = "{seat} ready for teams"
str _READY_TO_START = "{seat} ready to start"
str _READY_FOR_DEAL = "{seat} ready for deal"
str _READY_FOR_CARDS = "{seat} ready for cards"
str _READY_FOR_BID = "{seat} ready for {other}'s bid"
str _SEATED = '{seat} ("{client_name}") seated'
str _TEAMS = 'Teams: N/S "north-south" E/W "east-west"'
str _START_BOARD = "start of board"
str _DEAL = "Board number {board}. Dealer NORTH. Neither vulnerable."
str _CARDS = "{seat}'s cards: {hand}"
str _OTHER_PLAYER_ACTION = "{player} {action}"
str _PLAYER_TO_LEAD = "{seat} to lead"
str _DUMMY_CARDS = "Dummy's cards: {}"
list _SEATS = ["NORTH", "EAST", "SOUTH", "WEST"]
list _TRUMP_SUIT = ["C", "D", "H", "S", "NT"]
_NUMBER_TRUMP_SUITS = len(_TRUMP_SUIT)
list _SUIT = _TRUMP_SUIT[:4]
_NUMBER_SUITS = len(_SUIT)
list _RANKS = ["2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K", "A"]
list _LSUIT = [x.lower() for x in _SUIT]
list _LRANKS = [x.lower() for x in _RANKS]
int _ACTION_PASS = 52
int _ACTION_DBL = 53
int _ACTION_RDBL = 54
int _ACTION_BID = 55
Detailed Description
Wraps third-party bridge bots to make them usable in OpenSpiel.
This code enables OpenSpiel interoperation for bots which implement the BlueChip
bridge protocol. This is widely used, e.g. in the World computer bridge
championships. For a rough outline of the protocol, see:
http://www.bluechipbridge.co.uk/protocol.htm
No formal specification is available. This implementation has been verified
to work correctly with WBridge5.
This bot controls a single player in the full game of bridge, including both the
bidding and play phase. It chooses its actions by invoking an external bot which
plays the full game of bridge. This means that each time the bot is asked for an
action, it sends up to three actions (one for each other player) to the external
bridge bot, and obtains an action in return.
Function Documentation
_action_to_string()
open_spiel.python.bots.bluechip_bridge._action_to_string (action) protected
Converts OpenSpiel action id (an integer) to a BlueChip action string.
Args:
  action: an integer action id corresponding to a bid.
Returns:
  A string in BlueChip format, e.g. 'PASSES' or 'bids 1H', or 'plays ck'.
Definition at line 116 of file bluechip_bridge.py.
def _action_to_string(action):
  """Converts OpenSpiel action id (an integer) to a BlueChip action string.
  Args:
    action: an integer action id corresponding to a bid.
  Returns:
    A string in BlueChip format, e.g. 'PASSES' or 'bids 1H', or 'plays ck'.
  """
  if action == _ACTION_PASS:
    return "PASSES"
  elif action == _ACTION_DBL:
    return "DOUBLES"
  elif action == _ACTION_RDBL:
    return "REDOUBLES"
  elif action >= _ACTION_BID:
    level = str((action - _ACTION_BID) // _NUMBER_TRUMP_SUITS + 1)
    trumps = _TRUMP_SUIT[(action - _ACTION_BID) % _NUMBER_TRUMP_SUITS]
    return "bids " + level + trumps
  else:
    rank = action // _NUMBER_SUITS
    suit = action % _NUMBER_SUITS
    return "plays " + _LRANKS[rank] + _LSUIT[suit]
Referenced by open_spiel.python.bots.bluechip_bridge.BlueChipBridgeBot._update_for_state().
_bid_to_action()
open_spiel.python.bots.bluechip_bridge._bid_to_action (action_str) protected
Returns an OpenSpiel action id (an integer) from a BlueChip bid string.
Definition at line 102 of file bluechip_bridge.py.
def _bid_to_action(action_str):
  """Returns an OpenSpiel action id (an integer) from a BlueChip bid string."""
  level = int(action_str[0])
  trumps = _TRUMP_SUIT.index(action_str[1:])
  return _ACTION_BID + (level - 1) * _NUMBER_TRUMP_SUITS + trumps
Referenced by open_spiel.python.bots.bluechip_bridge.BlueChipBridgeBot.step().
_connect()
open_spiel.python.bots.bluechip_bridge._connect (controller, seat) protected
Performs the initial handshake with a BlueChip bot.
Definition at line 175 of file bluechip_bridge.py.
def _connect(controller, seat):
  """Performs the initial handshake with a BlueChip bot."""
  client_name = _expect_regex(controller, _CONNECT)["client_name"]
  controller.send_line(_SEATED.format(seat=seat, client_name=client_name))
  _expect(controller, _READY_FOR_TEAMS.format(seat=seat))
  controller.send_line(_TEAMS)
  _expect(controller, _READY_TO_START.format(seat=seat))
References open_spiel.python.bots.bluechip_bridge._expect(), and open_spiel.python.bots.bluechip_bridge._expect_regex().
Referenced by open_spiel.python.bots.bluechip_bridge.BlueChipBridgeBot.inform_state().
_expect()
open_spiel.python.bots.bluechip_bridge._expect (controller, expected) protected
Reads a line from the controller, checks it matches expected line exactly.
Definition at line 151 of file bluechip_bridge.py.
def _expect(controller, expected):
  """Reads a line from the controller, checks it matches expected line exactly."""
  line = controller.read_line()
  if expected != line:
    raise ValueError("Received '{}' but expected '{}'".format(line, expected))
Referenced by open_spiel.python.bots.bluechip_bridge._connect(), and open_spiel.python.bots.bluechip_bridge._new_deal().
_expect_regex()
open_spiel.python.bots.bluechip_bridge._expect_regex (controller, regex) protected
Reads a line from the controller, parses it using the regular expression.
Definition at line 141 of file bluechip_bridge.py.
def _expect_regex(controller, regex):
  """Reads a line from the controller, parses it using the regular expression."""
  line = controller.read_line()
  match = re.match(regex, line)
  if not match:
    raise ValueError("Received '{}' which does not match regex '{}'".format(
        line, regex))
  return match.groupdict()
Referenced by open_spiel.python.bots.bluechip_bridge._connect(), open_spiel.python.bots.bluechip_bridge.BlueChipBridgeBot._update_for_state(), and open_spiel.python.bots.bluechip_bridge.BlueChipBridgeBot.step().
_hand_string()
open_spiel.python.bots.bluechip_bridge._hand_string (cards) protected
Returns the hand of the to-play player in the state in BlueChip format.
Definition at line 158 of file bluechip_bridge.py.
def _hand_string(cards):
  """Returns the hand of the to-play player in the state in BlueChip format."""
  if len(cards) != 13:
    raise ValueError("Must have 13 cards")
  suits = [[] for _ in range(4)]
  for card in reversed(sorted(cards)):
    suit = card % 4
    rank = card // 4
    suits[suit].append(_RANKS[rank])
  for i in range(4):
    if suits[i]:
      suits[i] = _TRUMP_SUIT[i] + " " + " ".join(suits[i]) + "."
    else:
      suits[i] = _TRUMP_SUIT[i] + " -."
  return " ".join(suits)
References len.
Referenced by open_spiel.python.bots.bluechip_bridge.BlueChipBridgeBot._update_for_state().
_new_deal()
open_spiel.python.bots.bluechip_bridge._new_deal (controller, seat, hand, board) protected
Informs a BlueChip bots that there is a new deal.
Definition at line 184 of file bluechip_bridge.py.
def _new_deal(controller, seat, hand, board):
  """Informs a BlueChip bots that there is a new deal."""
  controller.send_line(_START_BOARD)
  _expect(controller, _READY_FOR_DEAL.format(seat=seat))
  controller.send_line(_DEAL.format(board=board))
  _expect(controller, _READY_FOR_CARDS.format(seat=seat))
  controller.send_line(_CARDS.format(seat=seat, hand=hand))
References open_spiel.python.bots.bluechip_bridge._expect().
Referenced by open_spiel.python.bots.bluechip_bridge.BlueChipBridgeBot._update_for_state().
_play_to_action()
open_spiel.python.bots.bluechip_bridge._play_to_action (action_str) protected
Returns an OpenSpiel action id (an integer) from a BlueChip card string.
Definition at line 109 of file bluechip_bridge.py.
def _play_to_action(action_str):
  """Returns an OpenSpiel action id (an integer) from a BlueChip card string."""
  rank = _LRANKS.index(action_str[0])
  suit = _LSUIT.index(action_str[1])
  return rank * _NUMBER_SUITS + suit
Referenced by open_spiel.python.bots.bluechip_bridge.BlueChipBridgeBot.step().
Variable Documentation
_ACTION_BID
int open_spiel.python.bots.bluechip_bridge._ACTION_BID = 55 protected
Definition at line 99 of file bluechip_bridge.py.
_ACTION_DBL
int open_spiel.python.bots.bluechip_bridge._ACTION_DBL = 53 protected
Definition at line 97 of file bluechip_bridge.py.
_ACTION_PASS
int open_spiel.python.bots.bluechip_bridge._ACTION_PASS = 52 protected
Definition at line 96 of file bluechip_bridge.py.
_ACTION_RDBL
int open_spiel.python.bots.bluechip_bridge._ACTION_RDBL = 54 protected
Definition at line 98 of file bluechip_bridge.py.
_CARDS
str open_spiel.python.bots.bluechip_bridge._CARDS = "{seat}'s cards: {hand}" protected
Definition at line 80 of file bluechip_bridge.py.
_CONNECT
str open_spiel.python.bots.bluechip_bridge._CONNECT = 'Connecting "(?P<client_name>.*)" as ANYPL using protocol version 18' protected
Definition at line 59 of file bluechip_bridge.py.
_DEAL
str open_spiel.python.bots.bluechip_bridge._DEAL = "Board number {board}. Dealer NORTH. Neither vulnerable." protected
Definition at line 79 of file bluechip_bridge.py.
_DUMMY_CARDS
str open_spiel.python.bots.bluechip_bridge._DUMMY_CARDS = "Dummy's cards: {}" protected
Definition at line 83 of file bluechip_bridge.py.
_LRANKS
list open_spiel.python.bots.bluechip_bridge._LRANKS = [x.lower() for x in _RANKS] protected
Definition at line 93 of file bluechip_bridge.py.
_LSUIT
list open_spiel.python.bots.bluechip_bridge._LSUIT = [x.lower() for x in _SUIT] protected
Definition at line 92 of file bluechip_bridge.py.
_NUMBER_SUITS
open_spiel.python.bots.bluechip_bridge._NUMBER_SUITS = len(_SUIT) protected
Definition at line 90 of file bluechip_bridge.py.
_NUMBER_TRUMP_SUITS
open_spiel.python.bots.bluechip_bridge._NUMBER_TRUMP_SUITS = len(_TRUMP_SUIT) protected
Definition at line 88 of file bluechip_bridge.py.
_OTHER_PLAYER_ACTION
str open_spiel.python.bots.bluechip_bridge._OTHER_PLAYER_ACTION = "{player} {action}" protected
Definition at line 81 of file bluechip_bridge.py.
_PLAYER_ACTION
tuple open_spiel.python.bots.bluechip_bridge._PLAYER_ACTION protected
Initial value:
=  ("(?P<seat>NORTH|SOUTH|EAST|WEST) "
                  "((?P<pass>PASSES)|(?P<dbl>DOUBLES)|(?P<rdbl>REDOUBLES)|bids "
                  "(?P<bid>[^ ]*)|(plays (?P<play>[23456789tjqka][cdhs])))"
                  "(?P<alert> Alert.)?")
Definition at line 60 of file bluechip_bridge.py.
_PLAYER_TO_LEAD
str open_spiel.python.bots.bluechip_bridge._PLAYER_TO_LEAD = "{seat} to lead" protected
Definition at line 82 of file bluechip_bridge.py.
_RANKS
list open_spiel.python.bots.bluechip_bridge._RANKS = ["2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K", "A"] protected
Definition at line 91 of file bluechip_bridge.py.
_READY_FOR_BID
str open_spiel.python.bots.bluechip_bridge._READY_FOR_BID = "{seat} ready for {other}'s bid" protected
Definition at line 73 of file bluechip_bridge.py.
_READY_FOR_CARDS
str open_spiel.python.bots.bluechip_bridge._READY_FOR_CARDS = "{seat} ready for cards" protected
Definition at line 72 of file bluechip_bridge.py.
_READY_FOR_DEAL
str open_spiel.python.bots.bluechip_bridge._READY_FOR_DEAL = "{seat} ready for deal" protected
Definition at line 71 of file bluechip_bridge.py.
_READY_FOR_OTHER
tuple open_spiel.python.bots.bluechip_bridge._READY_FOR_OTHER protected
Initial value:
=  ("{seat} ready for "
                    "(((?P<other>[^']*)'s ((bid)|(card to trick \\d+)))"
                    "|(?P<dummy>dummy))")
Definition at line 64 of file bluechip_bridge.py.
_READY_FOR_TEAMS
str open_spiel.python.bots.bluechip_bridge._READY_FOR_TEAMS = "{seat} ready for teams" protected
Definition at line 69 of file bluechip_bridge.py.
_READY_TO_START
str open_spiel.python.bots.bluechip_bridge._READY_TO_START = "{seat} ready to start" protected
Definition at line 70 of file bluechip_bridge.py.
_SEATED
str open_spiel.python.bots.bluechip_bridge._SEATED = '{seat} ("{client_name}") seated' protected
Definition at line 76 of file bluechip_bridge.py.
_SEATS
list open_spiel.python.bots.bluechip_bridge._SEATS = ["NORTH", "EAST", "SOUTH", "WEST"] protected
Definition at line 86 of file bluechip_bridge.py.
_START_BOARD
str open_spiel.python.bots.bluechip_bridge._START_BOARD = "start of board" protected
Definition at line 78 of file bluechip_bridge.py.
_SUIT
list open_spiel.python.bots.bluechip_bridge._SUIT = _TRUMP_SUIT[:4] protected
Definition at line 89 of file bluechip_bridge.py.
_TEAMS
str open_spiel.python.bots.bluechip_bridge._TEAMS = 'Teams: N/S "north-south" E/W "east-west"' protected
Definition at line 77 of file bluechip_bridge.py.
_TRUMP_SUIT
list open_spiel.python.bots.bluechip_bridge._TRUMP_SUIT = ["C", "D", "H", "S", "NT"] protected
Definition at line 87 of file bluechip_bridge.py.
GAME_STR
str open_spiel.python.bots.bluechip_bridge.GAME_STR = "bridge(use_double_dummy_result=False)"
Definition at line 56 of file bluechip_bridge.py.