open spiel: absl::cordrep_testing Namespace Reference
absl::cordrep_testing Namespace Reference
Classes
class AutoUnref
Functions
cord_internal::CordRepSubstring * MakeSubstring (size_t start, size_t len, cord_internal::CordRep *rep)
cord_internal::CordRepFlat * MakeFlat (absl::string_view value)
cord_internal::CordRepExternal * MakeExternal (absl::string_view s)
std::string CreateRandomString (size_t n)
std::vector< cord_internal::CordRep * > CreateFlatsFromString (absl::string_view data, size_t chunk_size)
cord_internal::CordRepBtree * CordRepBtreeFromFlats (absl::Span< cord_internal::CordRep *const > flats)
template<typename Fn >
void CordVisitReps (cord_internal::CordRep *rep, Fn &&fn)
template<typename Predicate >
std::vector< cord_internal::CordRep * > CordCollectRepsIf (Predicate &&predicate, cord_internal::CordRep *rep)
std::vector< cord_internal::CordRep * > CordCollectReps (cord_internal::CordRep *rep)
void CordToString (cord_internal::CordRep *rep, std::string &s)
std::string CordToString (cord_internal::CordRep *rep)
Function Documentation
CordCollectReps()
std::vector< cord_internal::CordRep * > absl::cordrep_testing::CordCollectReps (cord_internal::CordRep * rep) inline
Definition at line 130 of file cord_rep_test_util.h.
{
  std::vector<cord_internal::CordRep*> reps;
  auto fn = [&reps](cord_internal::CordRep* rep) { reps.push_back(rep); };
  CordVisitReps(rep, fn);
  return reps;
}
References CordVisitReps(), and rep.
CordCollectRepsIf()
template<typename Predicate > std::vector< cord_internal::CordRep * > absl::cordrep_testing::CordCollectRepsIf (Predicate && predicate, cord_internal::CordRep * rep) inline
Definition at line 121 of file cord_rep_test_util.h.
{
  std::vector<cord_internal::CordRep*> reps;
  CordVisitReps(rep, [&reps, &predicate](cord_internal::CordRep* rep) {
    if (predicate(rep)) reps.push_back(rep);
  });
  return reps;
}
References CordVisitReps(), and rep.
CordRepBtreeFromFlats()
cord_internal::CordRepBtree * absl::cordrep_testing::CordRepBtreeFromFlats (absl::Span< cord_internal::CordRep *const > flats) inline
Definition at line 96 of file cord_rep_test_util.h.
{
  assert(!flats.empty());
  auto* node = cord_internal::CordRepBtree::Create(flats[0]);
  for (size_t i = 1; i < flats.size(); ++i) {
    node = cord_internal::CordRepBtree::Append(node, flats[i]);
  }
  return node;
}
References absl::cord_internal::CordRepBtree::Append(), absl::cord_internal::CordRepBtree::Create(), absl::Span< T >::empty(), absl::i, and absl::Span< T >::size().
CordToString() [1/2]
std::string absl::cordrep_testing::CordToString (cord_internal::CordRep * rep) inline
Definition at line 158 of file cord_rep_test_util.h.
{
  std::string s;
  s.reserve(rep->length);
  CordToString(rep, s);
  return s;
}
References CordToString(), rep, and absl::s.
CordToString() [2/2]
void absl::cordrep_testing::CordToString (cord_internal::CordRep * rep, std::string & s) inline
Definition at line 138 of file cord_rep_test_util.h.
{
  size_t offset = 0;
  size_t length = rep->length;
  while (rep->tag == cord_internal::SUBSTRING) {
    offset += rep->substring()->start;
    rep = rep->substring()->child;
  }
  if (rep->tag == cord_internal::BTREE) {
    for (cord_internal::CordRep* edge : rep->btree()->Edges()) {
      CordToString(edge, s);
    }
  } else if (rep->tag >= cord_internal::FLAT) {
    s.append(rep->flat()->Data() + offset, length);
  } else if (rep->tag == cord_internal::EXTERNAL) {
    s.append(rep->external()->base + offset, length);
  } else {
    ABSL_RAW_LOG(FATAL, "Unsupported tag %d", rep->tag);
  }
}
References ABSL_RAW_LOG, absl::cord_internal::BTREE, CordToString(), absl::cord_internal::EXTERNAL, absl::cord_internal::FLAT, rep, absl::s, and absl::cord_internal::SUBSTRING.
Referenced by CordToString(), and CordToString().
CordVisitReps()
template<typename Fn > void absl::cordrep_testing::CordVisitReps (cord_internal::CordRep * rep, Fn && fn) inline
Definition at line 107 of file cord_rep_test_util.h.
{
  fn(rep);
  while (rep->tag == cord_internal::SUBSTRING) {
    rep = rep->substring()->child;
    fn(rep);
  }
  if (rep->tag == cord_internal::BTREE) {
    for (cord_internal::CordRep* edge : rep->btree()->Edges()) {
      CordVisitReps(edge, fn);
    }
  }
}
References absl::cord_internal::BTREE, CordVisitReps(), rep, and absl::cord_internal::SUBSTRING.
Referenced by CordCollectReps(), CordCollectRepsIf(), and CordVisitReps().
CreateFlatsFromString()
std::vector< cord_internal::CordRep * > absl::cordrep_testing::CreateFlatsFromString (absl::string_view data, size_t chunk_size) inline
Definition at line 86 of file cord_rep_test_util.h.
{
  assert(chunk_size > 0);
  std::vector<cord_internal::CordRep*> flats;
  for (absl::string_view s = data; !s.empty(); s.remove_prefix(chunk_size)) {
    flats.push_back(MakeFlat(s.substr(0, chunk_size)));
  }
  return flats;
}
References absl::string_view::empty(), MakeFlat(), and absl::s.
CreateRandomString()
std::string absl::cordrep_testing::CreateRandomString (size_t n) inline
Definition at line 69 of file cord_rep_test_util.h.
{
  absl::string_view data =
      "abcdefghijklmnopqrstuvwxyz"
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      "0123456789~!@#$%^&*()_+=-<>?:\"{}[]|";
  std::minstd_rand rnd;
  std::uniform_int_distribution<size_t> dist(0, data.size() - 1);
  std::string s(n, ' ');
  for (size_t i = 0; i < n; ++i) {
    s[i] = data[dist(rnd)];
  }
  return s;
}
References absl::i, absl::n, and absl::s.
MakeExternal()
cord_internal::CordRepExternal * absl::cordrep_testing::MakeExternal (absl::string_view s) inline
Definition at line 54 of file cord_rep_test_util.h.
{
  struct Rep : public cord_internal::CordRepExternal {
    std::string s;
    explicit Rep(absl::string_view sv) : s(sv) {
      this->tag = cord_internal::EXTERNAL;
      this->base = s.data();
      this->length = s.length();
      this->releaser_invoker = [](cord_internal::CordRepExternal* self) {
        delete static_cast<Rep*>(self);
      };
    }
  };
  return new Rep(s);
}
References absl::s.
MakeFlat()
cord_internal::CordRepFlat * absl::cordrep_testing::MakeFlat (absl::string_view value) inline
Definition at line 45 of file cord_rep_test_util.h.
{
  assert(value.length() <= cord_internal::kMaxFlatLength);
  auto* flat = cord_internal::CordRepFlat::New(value.length());
  flat->length = value.length();
  memcpy(flat->Data(), value.data(), value.length());
  return flat;
}
References absl::cord_internal::CordRepFlat::New().
Referenced by CreateFlatsFromString().
MakeSubstring()
cord_internal::CordRepSubstring * absl::cordrep_testing::MakeSubstring (size_t start, size_t len, cord_internal::CordRep * rep) inline
Definition at line 35 of file cord_rep_test_util.h.
{
  auto* sub = new cord_internal::CordRepSubstring;
  sub->tag = cord_internal::SUBSTRING;
  sub->start = start;
  sub->length = len <= 0 ? rep->length - start + len : len;
  sub->child = rep;
  return sub;
}
References len, rep, absl::cord_internal::SUBSTRING, and absl::cord_internal::CordRep::tag.