open spiel: open_spiel::coin_game Namespace Reference
open_spiel::coin_game Namespace Reference
Classes
class CoinGame
class CoinState
struct Setup
Typedefs
using Location = std::pair<int, int>
Enumerations
enum struct GamePhase { kAssignPreferences = 0 , kDeployPlayers = 1 , kDeployCoins = 2 , kPlay = 3 }
Functions
void BasicCoinGameTests ()
void GetAllStatesTest ()
Variables
constexpr int kDefaultPlayers = 2
constexpr int kDefaultRows = 8
constexpr int kDefaultColumns = 8
constexpr int kDefaultExtraCoinColors = 1
constexpr int kDefaultCoinsPerColor = 4
constexpr int kDefaultEpisodeLength = 20
Typedef Documentation
Location
using open_spiel::coin_game::Location = std::pair<int, int>
Definition at line 49 of file coin_game.h.
Enumeration Type Documentation
GamePhase
enum struct open_spiel::coin_game::GamePhase strong
Enumerator
kAssignPreferences
kDeployPlayers
kDeployCoins
kPlay
Definition at line 52 of file coin_game.h.
                      {
  kAssignPreferences = 0,
  kDeployPlayers = 1,
  kDeployCoins = 2,
  kPlay = 3
};
Function Documentation
BasicCoinGameTests()
void open_spiel::coin_game::BasicCoinGameTests ()
Definition at line 23 of file coin_game_test.cc.
{
  testing::LoadGameTest("coin_game");
  testing::RandomSimTest(*LoadGame("coin_game"), 10);
  testing::RandomSimTest(
      *LoadGame("coin_game",
                {
                    {"players", GameParameter(3)},
                    {"rows", GameParameter(7)},
                    {"columns", GameParameter(10)},
                    {"num_extra_coin_colors", GameParameter(2)},
                    {"episode_length", GameParameter(100)},
                    {"num_coins_per_color", GameParameter(2)},
                }),
      10);
}
References open_spiel::LoadGame(), open_spiel::testing::LoadGameTest(), and open_spiel::testing::RandomSimTest().
Referenced by main().
GetAllStatesTest()
void open_spiel::coin_game::GetAllStatesTest ()
Definition at line 39 of file coin_game_test.cc.
{
  // Getting all states (on a small game) can find corner case bugs.
  const std::shared_ptr<const Game> game =
      LoadGame("coin_game", {{"players", GameParameter(2)},
                             {"rows", GameParameter(2)},
                             {"columns", GameParameter(3)},
                             {"num_extra_coin_colors", GameParameter(0)},
                             {"episode_length", GameParameter(2)},
                             {"num_coins_per_color", GameParameter(2)}});
  auto states = algorithms::GetAllStates(*game,
                                         /*depth_limit=*/-1,
                                         /*include_terminals=*/true,
                                         /*include_chance_states=*/false);
  SPIEL_CHECK_EQ(states.size(), 4296);
}
References open_spiel::algorithms::GetAllStates(), open_spiel::LoadGame(), and SPIEL_CHECK_EQ.
Referenced by main().
Variable Documentation
kDefaultCoinsPerColor
int open_spiel::coin_game::kDefaultCoinsPerColor = 4 constexpr
Definition at line 29 of file coin_game.cc.
kDefaultColumns
int open_spiel::coin_game::kDefaultColumns = 8 constexpr
Definition at line 27 of file coin_game.cc.
kDefaultEpisodeLength
int open_spiel::coin_game::kDefaultEpisodeLength = 20 constexpr
Definition at line 30 of file coin_game.cc.
kDefaultExtraCoinColors
int open_spiel::coin_game::kDefaultExtraCoinColors = 1 constexpr
Definition at line 28 of file coin_game.cc.
kDefaultPlayers
int open_spiel::coin_game::kDefaultPlayers = 2 constexpr
Definition at line 25 of file coin_game.cc.
kDefaultRows
int open_spiel::coin_game::kDefaultRows = 8 constexpr
Definition at line 26 of file coin_game.cc.