open spiel: open_spiel::json Namespace Reference
open_spiel::json Namespace Reference
Classes
class Null
class Value
Typedefs
using Array = std::vector<Value>
using Object = std::map<std::string, Value>
Functions
std::string ToString (const Array &array, bool wrap, int indent)
std::string ToString (const Object &obj, bool wrap, int indent)
std::string ToString (const Value &value, bool wrap, int indent)
std::ostream & operator<< (std::ostream &os, const Null &n)
std::ostream & operator<< (std::ostream &os, const Array &a)
std::ostream & operator<< (std::ostream &os, const Object &o)
std::ostream & operator<< (std::ostream &os, const Value &v)
absl::optional< Value > FromString (absl::string_view str)
template<typename T >
Array CastToArray (std::vector< T > vec)
template<typename T , typename Fn >
Array TransformToArray (std::vector< T > vec, Fn fn)
Typedef Documentation
Array
using open_spiel::json::Array = std::vector<Value>
Definition at line 39 of file json.h.
Object
using open_spiel::json::Object = std::map<std::string, Value>
Definition at line 40 of file json.h.
Function Documentation
CastToArray()
template<typename T > Array open_spiel::json::CastToArray (std::vector< T > vec)
Definition at line 127 of file json.h.
{
  Array out;
  out.reserve(vec.size());
  for (const T& val : vec) {
    out.emplace_back(val);
  }
  return out;
}
References out.
Referenced by open_spiel::algorithms::torch_az::learner(), open_spiel::HistogramNamed::ToJson(), and open_spiel::HistogramNumbered::ToJson().
FromString()
absl::optional< Value > open_spiel::json::FromString (absl::string_view str)
Definition at line 336 of file json.cc.
{
  return ParseValue(&str);
}
Referenced by main(), and open_spiel::algorithms::torch_az::StartInfoFromLearnerJson().
operator<<() [1/4]
std::ostream & open_spiel::json::operator<< (std::ostream & os, const Array & a)
Definition at line 324 of file json.cc.
{
  return os << ToString(a);
}
References a, and ToString().
operator<<() [2/4]
std::ostream & open_spiel::json::operator<< (std::ostream & os, const Null & n)
Definition at line 320 of file json.cc.
{
  return os << ToString(n);
}
References n, and ToString().
operator<<() [3/4]
std::ostream & open_spiel::json::operator<< (std::ostream & os, const Object & o)
Definition at line 328 of file json.cc.
{
  return os << ToString(o);
}
References o, and ToString().
operator<<() [4/4]
std::ostream & open_spiel::json::operator<< (std::ostream & os, const Value & v)
Definition at line 332 of file json.cc.
{
  return os << ToString(v);
}
References ToString().
ToString() [1/3]
std::string open_spiel::json::ToString (const Array & array, bool wrap, int indent)
Definition at line 246 of file json.cc.
{
  std::string out = "[";
  bool first = true;
  for (const Value& v : array) {
    if (!first) {
      absl::StrAppend(&out, ",");
    }
    if (wrap) {
      absl::StrAppend(&out, "\n", std::string(indent + 2, ' '));
    } else if (!first) {
      absl::StrAppend(&out, " ");
    }
    first = false;
    absl::StrAppend(&out, json::ToString(v, wrap, indent + 2));
  }
  if (wrap) {
    absl::StrAppend(&out, "\n", std::string(indent, ' '));
  }
  absl::StrAppend(&out, "]");
  return out;
}
References first, out, absl::StrAppend(), and ToString().
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), operator<<(), operator<<(), operator<<(), operator<<(), ToString(), ToString(), ToString(), and open_spiel::DataLoggerJsonLines::Write().
ToString() [2/3]
std::string open_spiel::json::ToString (const Object & obj, bool wrap, int indent)
Definition at line 268 of file json.cc.
{
  std::string out = "{";
  bool first = true;
  for (const auto& [key, value] : obj) {
    if (!first) {
      absl::StrAppend(&out, ",");
    }
    if (wrap) {
      absl::StrAppend(&out, "\n", std::string(indent + 2, ' '));
    } else if (!first) {
      absl::StrAppend(&out, " ");
    }
    first = false;
    absl::StrAppend(&out, "\"", Escape(key), "\": ",
                    json::ToString(value, wrap, indent + 2));
  }
  if (wrap) {
    absl::StrAppend(&out, "\n", std::string(indent, ' '));
  }
  absl::StrAppend(&out, "}");
  return out;
}
References first, key, out, absl::StrAppend(), and ToString().
ToString() [3/3]
std::string open_spiel::json::ToString (const Value & value, bool wrap, int indent)
Definition at line 292 of file json.cc.
{
  if (value.IsNull()) {
    return "null";
  } else if (value.IsBool()) {
    return (value.GetBool() ? "true" : "false");
  } else if (value.IsInt()) {
    return std::to_string(value.GetInt());
  } else if (value.IsDouble()) {
    double v = value.GetDouble();
    if (std::isfinite(v)) {
      return std::to_string(v);
    } else {
      // It'd be nice to show an error with a path, but at least this is
      // debuggable by looking at the json. Crashing doesn't tell you where
      // the problem is.
      return absl::StrCat("\"", std::to_string(v), "\"");
    }
  } else if (value.IsString()) {
    return absl::StrCat("\"", Escape(value.GetString()), "\"");
  } else if (value.IsArray()) {
    return ToString(value.GetArray(), wrap, indent);
  } else if (value.IsObject()) {
    return ToString(value.GetObject(), wrap, indent);
  } else {
    SpielFatalError("json::ToString is missing a type.");
  }
}
References open_spiel::SpielFatalError(), absl::StrCat(), and ToString().
TransformToArray()
template<typename T , typename Fn > Array open_spiel::json::TransformToArray (std::vector< T > vec, Fn fn)
Definition at line 139 of file json.h.
{
  Array out;
  out.reserve(vec.size());
  for (const T& val : vec) {
    out.emplace_back(fn(val));
  }
  return out;
}
References out.
Referenced by open_spiel::algorithms::torch_az::learner().