open spiel: open_spiel::tarok Namespace Reference
open_spiel::tarok Namespace Reference
Classes
struct Card
struct Contract
class TarokGame
class TarokState
Typedefs
using DealtCards
using TrickWinnerAndAction = std::tuple<Player, Action>
using CollectedCardsPerTeam
Enumerations
enum class CardSuit {
kHearts , kDiamonds , kSpades , kClubs ,
kTaroks
}
enum class ContractName {
kKlop , kThree , kTwo , kOne ,
kSoloThree , kSoloTwo , kSoloOne , kBeggar ,
kSoloWithout , kOpenBeggar , kColourValatWithout , kValatWithout ,
kNotSelected
}
enum class GamePhase {
kCardDealing , kBidding , kKingCalling , kTalonExchange ,
kTricksPlaying , kFinished
}
Functions
const std::array< Card, 54 > InitializeCardDeck ()
DealtCards DealCards (int num_players, int seed)
void Shuffle (std::vector< Action > *actions, std::mt19937 &&rng)
int CardPoints (const std::vector< Action > &actions, const std::array< Card, 54 > &deck)
const std::array< Contract, 12 > InitializeContracts ()
std::ostream & operator<< (std::ostream &os, const ContractName &contract_name)
std::string ContractNameToString (const ContractName &contract_name)
std::shared_ptr< const Game > Factory (const GameParameters &params)
REGISTER_SPIEL_GAME (kGameType, Factory)
RegisterSingleTensorObserver single_tensor (kGameType.short_name)
std::ostream & operator<< (std::ostream &os, const GamePhase &game_phase)
std::string GamePhaseToString (const GamePhase &game_phase)
std::shared_ptr< const TarokGame > NewTarokGame (const GameParameters &params)
std::unique_ptr< TarokState > StateAfterActions (const GameParameters &params, const std::vector< Action > &actions)
bool AllActionsInOtherActions (const std::vector< Action > &actions, const std::vector< Action > &other_actions)
Action CardLongNameToAction (const std::string &long_name)
std::vector< Action > CardLongNamesToActions (const std::vector< std::string > &long_names)
template<typename T >
bool AllEq (const std::vector< T > &xs0, const std::vector< T > &xs1)
void BasicGameTests ()
void CardDeckShufflingSeedTest ()
void DealtCardsSizeTest (int num_players)
void DealtCardsContentTest (int num_players)
void PlayersCardsSortedTest ()
void CountCardsTest ()
void CardDealingPhaseTest ()
void BiddingPhase3PlayersTest1 ()
void BiddingPhase3PlayersTest2 ()
void BiddingPhase3PlayersTest3 ()
void BiddingPhase3PlayersTest4 ()
void BiddingPhase4PlayersTest1 ()
void BiddingPhase4PlayersTest2 ()
void BiddingPhase4PlayersTest3 ()
void BiddingPhase4PlayersTest4 ()
void BiddingPhase4PlayersTest5 ()
void TalonExchangePhaseTest1 ()
void TalonExchangePhaseTest2 ()
void TalonExchangePhaseTest3 ()
void TalonExchangePhaseTest4 ()
void TalonExchangePhaseTest5 ()
void TalonExchangePhaseTest6 ()
void TalonExchangePhaseTest7 ()
void TalonExchangePhaseTest8 ()
void TricksPlayingPhaseTest1 ()
void TricksPlayingPhaseTest2 ()
void TricksPlayingPhaseTest3 ()
void TricksPlayingPhaseTest4 ()
void TricksPlayingPhaseTest5 ()
void TricksPlayingPhaseTest6 ()
void TricksPlayingPhaseTest7 ()
void CapturedMondTest1 ()
void CapturedMondTest2 ()
void CapturedMondTest3 ()
void CapturedMondTest4 ()
void CapturedMondTest5 ()
void CapturedMondTest6 ()
void CapturedMondTest7 ()
void CapturedMondTest8 ()
void CapturedMondTest9 ()
Variables
constexpr int kPagatAction = 0
constexpr int kMondAction = 20
constexpr int kSkisAction = 21
constexpr int kKingOfHeartsAction = 29
constexpr int kKingOfDiamondsAction = 37
constexpr int kKingOfSpadesAction = 45
constexpr int kKingOfClubsAction = 53
constexpr int kInvalidBidAction = -1
constexpr int kBidPassAction = 0
constexpr int kBidKlopAction = 1
constexpr int kBidThreeAction = 2
constexpr int kBidSoloThreeAction = 5
constexpr int kBidSoloOneAction = 7
const GameType kGameType
constexpr int kDefaultNumPLayers = 3
constexpr int kDefaultSeed = -1
constexpr int kDealCardsAction = 0
constexpr int kBidTwoAction = 3
constexpr int kBidOneAction = 4
constexpr int kBidSoloTwoAction = 6
constexpr int kBidBeggarAction = 8
constexpr int kBidSoloWithoutAction = 9
constexpr int kBidOpenBeggarAction = 10
constexpr int kBidColourValatAction = 11
constexpr int kBidValatWithoutAction = 12
const std::array< Card, 54 > card_deck = InitializeCardDeck()
Typedef Documentation
CollectedCardsPerTeam
using open_spiel::tarok::CollectedCardsPerTeam
Initial value:
    std::tuple<std::vector<Action>, std::vector<Action>>
Definition at line 85 of file tarok.h.
DealtCards
using open_spiel::tarok::DealtCards
Initial value:
    std::tuple<std::vector<Action>, std::vector<std::vector<Action>>>
Definition at line 56 of file cards.h.
TrickWinnerAndAction
using open_spiel::tarok::TrickWinnerAndAction = std::tuple<Player, Action>
Definition at line 84 of file tarok.h.
Enumeration Type Documentation
CardSuit
enum class open_spiel::tarok::CardSuit strong
Enumerator
kHearts
kDiamonds
kSpades
kClubs
kTaroks
Definition at line 38 of file cards.h.
{ kHearts, kDiamonds, kSpades, kClubs, kTaroks };
ContractName
enum class open_spiel::tarok::ContractName strong
Enumerator
kKlop
kThree
kTwo
kOne
kSoloThree
kSoloTwo
kSoloOne
kBeggar
kSoloWithout
kOpenBeggar
kColourValatWithout
kValatWithout
kNotSelected
Definition at line 36 of file contracts.h.
{
  kKlop,
  kThree,
  kTwo,
  kOne,
  kSoloThree,
  kSoloTwo,
  kSoloOne,
  kBeggar,
  kSoloWithout,
  kOpenBeggar,
  kColourValatWithout,
  kValatWithout,
  kNotSelected
};
GamePhase
enum class open_spiel::tarok::GamePhase strong
Enumerator
kCardDealing
kBidding
kKingCalling
kTalonExchange
kTricksPlaying
kFinished
Definition at line 37 of file tarok.h.
                     {
  kCardDealing,
  kBidding,
  kKingCalling,
  kTalonExchange,
  kTricksPlaying,
  kFinished
};
Function Documentation
AllActionsInOtherActions()
bool open_spiel::tarok::AllActionsInOtherActions (const std::vector< Action > & actions, const std::vector< Action > & other_actions)
Definition at line 49 of file tarok_test.cc.
{
  for (auto const& action : actions) {
    if (std::find(other_actions.begin(), other_actions.end(), action) ==
        other_actions.end()) {
      return false;
    }
  }
  return true;
}
References action.
Referenced by TalonExchangePhaseTest1(), TalonExchangePhaseTest2(), TalonExchangePhaseTest3(), TalonExchangePhaseTest4(), TalonExchangePhaseTest5(), and TalonExchangePhaseTest6().
AllEq()
template<typename T > bool open_spiel::tarok::AllEq (const std::vector< T > & xs0, const std::vector< T > & xs1)
Definition at line 79 of file tarok_test.cc.
{
  if (xs0.size() != xs1.size()) return false;
  for (int i = 0; i < xs0.size(); i++) {
    if (xs0.at(i) != xs1.at(i)) return false;
  }
  return true;
}
References i.
Referenced by BiddingPhase3PlayersTest1(), BiddingPhase3PlayersTest2(), BiddingPhase3PlayersTest3(), BiddingPhase3PlayersTest4(), BiddingPhase4PlayersTest1(), BiddingPhase4PlayersTest2(), BiddingPhase4PlayersTest3(), BiddingPhase4PlayersTest4(), BiddingPhase4PlayersTest5(), CapturedMondTest1(), CapturedMondTest2(), CapturedMondTest3(), CapturedMondTest4(), CapturedMondTest5(), CapturedMondTest6(), CapturedMondTest7(), CapturedMondTest8(), CapturedMondTest9(), CardDealingPhaseTest(), TalonExchangePhaseTest1(), TalonExchangePhaseTest2(), TalonExchangePhaseTest3(), TalonExchangePhaseTest4(), TalonExchangePhaseTest5(), TalonExchangePhaseTest6(), TricksPlayingPhaseTest1(), TricksPlayingPhaseTest2(), TricksPlayingPhaseTest3(), TricksPlayingPhaseTest4(), TricksPlayingPhaseTest5(), TricksPlayingPhaseTest6(), and TricksPlayingPhaseTest7().
BasicGameTests()
void open_spiel::tarok::BasicGameTests ()
Definition at line 88 of file tarok_test.cc.
                      {
  testing::LoadGameTest("tarok");
  testing::ChanceOutcomesTest(*LoadGame("tarok"));
  testing::RandomSimTest(*LoadGame("tarok"), 100);
}
References open_spiel::testing::ChanceOutcomesTest(), open_spiel::LoadGame(), open_spiel::testing::LoadGameTest(), and open_spiel::testing::RandomSimTest().
Referenced by main().
BiddingPhase3PlayersTest1()
void open_spiel::tarok::BiddingPhase3PlayersTest1 ()
Definition at line 202 of file tarok_test.cc.
{
  // scenario: all players pass
  auto game = NewTarokGame(GameParameters());
  auto state = game->NewInitialTarokState();
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidKlopAction, kBidThreeAction, kBidTwoAction, kBidOneAction,
             kBidBeggarAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidKlopAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kKlop);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
}
References AllEq(), BiddingPhase3PlayersTest1(), kBidKlopAction, kBidPassAction, kDealCardsAction, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by BiddingPhase3PlayersTest1(), and main().
BiddingPhase3PlayersTest2()
void open_spiel::tarok::BiddingPhase3PlayersTest2 ()
Definition at line 239 of file tarok_test.cc.
{
  // scenario: forehand passes, player 1 eventually bids beggar, player 2 bids
  // beggar
  auto game = NewTarokGame(GameParameters());
  auto state = game->NewInitialTarokState();
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidTwoAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidPassAction, kBidOneAction, kBidBeggarAction, kBidSoloWithoutAction,
       kBidOpenBeggarAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidBeggarAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidPassAction, kBidBeggarAction, kBidSoloWithoutAction,
       kBidOpenBeggarAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidPassAction, kBidBeggarAction, kBidSoloWithoutAction,
       kBidOpenBeggarAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidBeggarAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidBeggarAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidBeggarAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kBeggar);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
}
References AllEq(), BiddingPhase3PlayersTest2(), kBidBeggarAction, kBidPassAction, kBidTwoAction, kDealCardsAction, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by BiddingPhase3PlayersTest2(), and main().
BiddingPhase3PlayersTest3()
void open_spiel::tarok::BiddingPhase3PlayersTest3 ()
Definition at line 296 of file tarok_test.cc.
{
  // scenario: forehand passes, player 1 bids beggar, player 2 bids solo without
  auto game = NewTarokGame(GameParameters());
  auto state = game->NewInitialTarokState();
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidBeggarAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidSoloWithoutAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(),
                         {kBidSoloWithoutAction, kBidOpenBeggarAction,
                          kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidSoloWithoutAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kSoloWithout);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
}
References AllEq(), BiddingPhase3PlayersTest3(), kBidBeggarAction, kBidPassAction, kBidSoloWithoutAction, kDealCardsAction, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by BiddingPhase3PlayersTest3(), and main().
BiddingPhase3PlayersTest4()
void open_spiel::tarok::BiddingPhase3PlayersTest4 ()
Definition at line 344 of file tarok_test.cc.
{
  // scenario: forehand bids valat without, others are forced to pass, todo: we
  // could check this case in DoApplyActionInBidding and simply finish the
  // bidding phase early
  auto game = NewTarokGame(GameParameters());
  auto state = game->NewInitialTarokState();
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidTwoAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidPassAction, kBidOneAction, kBidBeggarAction, kBidSoloWithoutAction,
       kBidOpenBeggarAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidOneAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidPassAction, kBidOneAction, kBidBeggarAction, kBidSoloWithoutAction,
       kBidOpenBeggarAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidValatWithoutAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {kBidPassAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {kBidPassAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {kBidValatWithoutAction}));
  state->ApplyAction(kBidValatWithoutAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kValatWithout);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
}
References AllEq(), BiddingPhase3PlayersTest4(), kBidOneAction, kBidPassAction, kBidTwoAction, kBidValatWithoutAction, kDealCardsAction, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by BiddingPhase3PlayersTest4(), and main().
BiddingPhase4PlayersTest1()
void open_spiel::tarok::BiddingPhase4PlayersTest1 ()
Definition at line 393 of file tarok_test.cc.
{
  // scenario: all players pass
  auto game = NewTarokGame(GameParameters({{"players", GameParameter(4)}}));
  auto state = game->NewInitialTarokState();
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidSoloThreeAction,
             kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidSoloThreeAction,
             kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidSoloThreeAction,
             kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidKlopAction, kBidThreeAction, kBidTwoAction, kBidOneAction,
             kBidSoloThreeAction, kBidSoloTwoAction, kBidSoloOneAction,
             kBidBeggarAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidKlopAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kKlop);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
}
References AllEq(), BiddingPhase4PlayersTest1(), kBidKlopAction, kBidPassAction, kDealCardsAction, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by BiddingPhase4PlayersTest1(), and main().
BiddingPhase4PlayersTest2()
void open_spiel::tarok::BiddingPhase4PlayersTest2 ()
Definition at line 442 of file tarok_test.cc.
{
  // scenario: forehand bids one, player 2 bids one, others pass
  auto game = NewTarokGame(GameParameters({{"players", GameParameter(4)}}));
  auto state = game->NewInitialTarokState();
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidSoloThreeAction,
             kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidSoloThreeAction,
             kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidOneAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidPassAction, kBidSoloThreeAction, kBidSoloTwoAction,
       kBidSoloOneAction, kBidBeggarAction, kBidSoloWithoutAction,
       kBidOpenBeggarAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidPassAction, kBidOneAction, kBidSoloThreeAction, kBidSoloTwoAction,
       kBidSoloOneAction, kBidBeggarAction, kBidSoloWithoutAction,
       kBidOpenBeggarAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidOneAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidPassAction, kBidSoloThreeAction, kBidSoloTwoAction,
       kBidSoloOneAction, kBidBeggarAction, kBidSoloWithoutAction,
       kBidOpenBeggarAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidOneAction, kBidSoloThreeAction, kBidSoloTwoAction, kBidSoloOneAction,
       kBidBeggarAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
       kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidOneAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kKingCalling);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
}
References AllEq(), BiddingPhase4PlayersTest2(), kBidOneAction, kBidPassAction, kDealCardsAction, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by BiddingPhase4PlayersTest2(), and main().
BiddingPhase4PlayersTest3()
void open_spiel::tarok::BiddingPhase4PlayersTest3 ()
Definition at line 505 of file tarok_test.cc.
{
  // scenario: player 1 bids solo three, player 3 eventually bids solo one,
  // others pass
  auto game = NewTarokGame(GameParameters({{"players", GameParameter(4)}}));
  auto state = game->NewInitialTarokState();
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidSoloThreeAction,
             kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidSoloThreeAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidSoloTwoAction, kBidSoloOneAction,
             kBidBeggarAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidSoloTwoAction, kBidSoloOneAction,
             kBidBeggarAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidSoloTwoAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidSoloTwoAction, kBidSoloOneAction,
             kBidBeggarAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidSoloTwoAction, kBidSoloOneAction,
             kBidBeggarAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidSoloOneAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kSoloOne);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
}
References AllEq(), BiddingPhase4PlayersTest3(), kBidPassAction, kBidSoloOneAction, kBidSoloThreeAction, kBidSoloTwoAction, kDealCardsAction, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by BiddingPhase4PlayersTest3(), and main().
BiddingPhase4PlayersTest4()
void open_spiel::tarok::BiddingPhase4PlayersTest4 ()
Definition at line 568 of file tarok_test.cc.
{
  // scenario: player 2 bids beggar, others pass
  auto game = NewTarokGame(GameParameters({{"players", GameParameter(4)}}));
  auto state = game->NewInitialTarokState();
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidSoloThreeAction,
             kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidSoloThreeAction,
             kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidBeggarAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(
      state->LegalActions(),
      {kBidPassAction, kBidBeggarAction, kBidSoloWithoutAction,
       kBidOpenBeggarAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidBeggarAction, kBidSoloWithoutAction, kBidOpenBeggarAction,
             kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidBeggarAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kBeggar);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
}
References AllEq(), BiddingPhase4PlayersTest4(), kBidBeggarAction, kBidPassAction, kDealCardsAction, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by BiddingPhase4PlayersTest4(), and main().
BiddingPhase4PlayersTest5()
void open_spiel::tarok::BiddingPhase4PlayersTest5 ()
Definition at line 620 of file tarok_test.cc.
{
  // scenario: forehand passes, player 1 bids open beggar, player 2 bids colour
  // valat without, player 3 bids valat without
  auto game = NewTarokGame(GameParameters({{"players", GameParameter(4)}}));
  auto state = game->NewInitialTarokState();
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidTwoAction, kBidOneAction, kBidSoloThreeAction,
             kBidSoloTwoAction, kBidSoloOneAction, kBidBeggarAction,
             kBidSoloWithoutAction, kBidOpenBeggarAction, kBidColourValatAction,
             kBidValatWithoutAction}));
  state->ApplyAction(kBidOpenBeggarAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {kBidPassAction, kBidColourValatAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidColourValatAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(), {kBidPassAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidValatWithoutAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(), {kBidPassAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(), {kBidPassAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(), {kBidPassAction, kBidValatWithoutAction}));
  state->ApplyAction(kBidPassAction);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {kBidValatWithoutAction}));
  state->ApplyAction(kBidValatWithoutAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kValatWithout);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
}
References AllEq(), BiddingPhase4PlayersTest5(), kBidColourValatAction, kBidOpenBeggarAction, kBidPassAction, kBidValatWithoutAction, kDealCardsAction, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by BiddingPhase4PlayersTest5(), and main().
CapturedMondTest1()
void open_spiel::tarok::CapturedMondTest1 ()
Definition at line 1215 of file tarok_test.cc.
{
  // mond captured by skis
  auto state = StateAfterActions(
      GameParameters({{"rng_seed", GameParameter(634317)}}),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidOneAction, 0, 49});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  // play mond
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  state->ApplyAction(CardLongNameToAction("Mond"));
  // play skis
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  state->ApplyAction(CardLongNameToAction("Skis"));
  // play low tarok
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  state->ApplyAction(CardLongNameToAction("VI"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {-20, 0, 0}));
}
References AllEq(), CapturedMondTest1(), CardLongNameToAction(), kBidOneAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, and StateAfterActions().
Referenced by CapturedMondTest1(), and main().
CapturedMondTest2()
void open_spiel::tarok::CapturedMondTest2 ()
Definition at line 1237 of file tarok_test.cc.
{
  // mond captured by pagat (emperor trick)
  auto state = StateAfterActions(
      GameParameters({{"rng_seed", GameParameter(634317)}}),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidOneAction, 0, 49});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  // play mond
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  state->ApplyAction(CardLongNameToAction("Mond"));
  // play skis
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  state->ApplyAction(CardLongNameToAction("Skis"));
  // play pagat
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  state->ApplyAction(CardLongNameToAction("Pagat"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {-20, 0, 0}));
}
References AllEq(), CapturedMondTest2(), CardLongNameToAction(), kBidOneAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, and StateAfterActions().
Referenced by CapturedMondTest2(), and main().
CapturedMondTest3()
void open_spiel::tarok::CapturedMondTest3 ()
Definition at line 1259 of file tarok_test.cc.
{
  // mond taken from talon
  auto state = StateAfterActions(
      GameParameters({{"rng_seed", GameParameter(497200)}}),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidOneAction, 3, 49});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {0, 0, 0}));
}
References AllEq(), CapturedMondTest3(), kBidOneAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, and StateAfterActions().
Referenced by CapturedMondTest3(), and main().
CapturedMondTest4()
void open_spiel::tarok::CapturedMondTest4 ()
Definition at line 1271 of file tarok_test.cc.
{
  // mond left in talon
  auto state = StateAfterActions(
      GameParameters({{"rng_seed", GameParameter(497200)}}),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidOneAction, 0, 49});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {-20, 0, 0}));
}
References AllEq(), CapturedMondTest4(), kBidOneAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, and StateAfterActions().
Referenced by CapturedMondTest4(), and main().
CapturedMondTest5()
void open_spiel::tarok::CapturedMondTest5 ()
Definition at line 1283 of file tarok_test.cc.
{
  // mond left in talon but won with a called king
  auto state = StateAfterActions(
      GameParameters(
          {{"players", GameParameter(4)}, {"rng_seed", GameParameter(297029)}}),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidPassAction,
       kBidOneAction, kKingOfSpadesAction, 2, 49});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  // play the called king and win the trick
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {-20, 0, 0, 0}));
  state->ApplyAction(CardLongNameToAction("King of Spades"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  state->ApplyAction(CardLongNameToAction("Queen of Spades"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  state->ApplyAction(CardLongNameToAction("8 of Spades"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 3);
  state->ApplyAction(CardLongNameToAction("7 of Spades"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {0, 0, 0, 0}));
}
References AllEq(), CapturedMondTest5(), CardLongNameToAction(), kBidOneAction, kBidPassAction, kDealCardsAction, kKingOfSpadesAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, and StateAfterActions().
Referenced by CapturedMondTest5(), and main().
CapturedMondTest6()
void open_spiel::tarok::CapturedMondTest6 ()
Definition at line 1309 of file tarok_test.cc.
{
  // mond captured by ally should also be penalized
  auto state =
      StateAfterActions(GameParameters({{"rng_seed", GameParameter(634317)}}),
                        {kDealCardsAction, kBidPassAction, kBidOneAction,
                         kBidPassAction, kBidOneAction, 0, 22});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  // play mond
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  state->ApplyAction(CardLongNameToAction("Mond"));
  // play skis
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  state->ApplyAction(CardLongNameToAction("Skis"));
  // play low tarok
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  state->ApplyAction(CardLongNameToAction("VI"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {-20, 0, 0}));
}
References AllEq(), CapturedMondTest6(), CardLongNameToAction(), kBidOneAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, and StateAfterActions().
Referenced by CapturedMondTest6(), and main().
CapturedMondTest7()
void open_spiel::tarok::CapturedMondTest7 ()
Definition at line 1332 of file tarok_test.cc.
{
  // mond captured in klop should not be penalized
  auto state = StateAfterActions(
      GameParameters({{"rng_seed", GameParameter(634317)}}),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidKlopAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kKlop);
  // play mond
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  state->ApplyAction(CardLongNameToAction("Mond"));
  // play skis
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  state->ApplyAction(CardLongNameToAction("Skis"));
  // play pagat
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  state->ApplyAction(CardLongNameToAction("Pagat"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {0, 0, 0}));
}
References AllEq(), CapturedMondTest7(), CardLongNameToAction(), kBidKlopAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, and StateAfterActions().
Referenced by CapturedMondTest7(), and main().
CapturedMondTest8()
void open_spiel::tarok::CapturedMondTest8 ()
Definition at line 1354 of file tarok_test.cc.
{
  // mond captured in bagger should not be penalized
  auto state = StateAfterActions(
      GameParameters({{"rng_seed", GameParameter(634317)}}),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidBeggarAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kBeggar);
  // play mond
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  state->ApplyAction(CardLongNameToAction("Mond"));
  // play skis
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  state->ApplyAction(CardLongNameToAction("Skis"));
  // play pagat
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  state->ApplyAction(CardLongNameToAction("Pagat"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {0, 0, 0}));
}
References AllEq(), CapturedMondTest8(), CardLongNameToAction(), kBidBeggarAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, and StateAfterActions().
Referenced by CapturedMondTest8(), and main().
CapturedMondTest9()
void open_spiel::tarok::CapturedMondTest9 ()
Definition at line 1376 of file tarok_test.cc.
{
  // mond captured in open bagger should not be penalized
  auto state = StateAfterActions(
      GameParameters({{"rng_seed", GameParameter(634317)}}),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidOpenBeggarAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOpenBeggar);
  // play mond
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  state->ApplyAction(CardLongNameToAction("Mond"));
  // play skis
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  state->ApplyAction(CardLongNameToAction("Skis"));
  // play pagat
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  state->ApplyAction(CardLongNameToAction("Pagat"));
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->CapturedMondPenalties(), {0, 0, 0}));
}
References AllEq(), CapturedMondTest9(), CardLongNameToAction(), kBidOpenBeggarAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, and StateAfterActions().
Referenced by CapturedMondTest9(), and main().
CardDealingPhaseTest()
void open_spiel::tarok::CardDealingPhaseTest ()
Definition at line 171 of file tarok_test.cc.
{
  auto game = NewTarokGame(GameParameters());
  auto state = game->NewInitialTarokState();
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kCardDealing);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), kChancePlayerId);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  SPIEL_CHECK_TRUE(state->TalonSets().empty());
  for (int i = 0; i < game->NumPlayers(); i++) {
    SPIEL_CHECK_TRUE(state->PlayerCards(i).empty());
  }
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {0}));
  SPIEL_CHECK_TRUE(AllEq(state->ChanceOutcomes(), {{0, 1.0}}));
  // deal the cards
  state->ApplyAction(kDealCardsAction);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kBidding);
  SPIEL_CHECK_NE(state->CurrentPlayer(), kChancePlayerId);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kNotSelected);
  // talon sets are only visible in the talon exchange phase
  SPIEL_CHECK_TRUE(state->TalonSets().empty());
  SPIEL_CHECK_EQ(state->Talon().size(), 6);
  for (int i = 0; i < game->NumPlayers(); i++) {
    SPIEL_CHECK_FALSE(state->PlayerCards(i).empty());
  }
  SPIEL_CHECK_TRUE(state->ChanceOutcomes().empty());
}
References AllEq(), i, kCardDealing, open_spiel::kChancePlayerId, kNotSelected, NewTarokGame(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by main().
CardDeckShufflingSeedTest()
void open_spiel::tarok::CardDeckShufflingSeedTest ()
Definition at line 95 of file tarok_test.cc.
{
  auto game = NewTarokGame(GameParameters({{"rng_seed", GameParameter(0)}}));
  // subsequent shuffles within the same game should be different
  auto state1 = game->NewInitialTarokState();
  state1->ApplyAction(0);
  auto state2 = game->NewInitialTarokState();
  state2->ApplyAction(0);
  SPIEL_CHECK_NE(state1->PlayerCards(0), state2->PlayerCards(0));
  game = NewTarokGame(GameParameters({{"rng_seed", GameParameter(0)}}));
  // shuffles should be the same when recreating a game with the same seed
  auto state3 = game->NewInitialTarokState();
  state3->ApplyAction(0);
  auto state4 = game->NewInitialTarokState();
  state4->ApplyAction(0);
  SPIEL_CHECK_EQ(state1->PlayerCards(0), state3->PlayerCards(0));
  SPIEL_CHECK_EQ(state2->PlayerCards(0), state4->PlayerCards(0));
}
References NewTarokGame(), SPIEL_CHECK_EQ, and SPIEL_CHECK_NE.
Referenced by main().
CardLongNamesToActions()
std::vector< Action > open_spiel::tarok::CardLongNamesToActions (const std::vector< std::string > & long_names)
Definition at line 68 of file tarok_test.cc.
{
  std::vector<Action> actions;
  actions.reserve(long_names.size());
  for (auto const long_name : long_names) {
    actions.push_back(CardLongNameToAction(long_name));
  }
  return actions;
}
References CardLongNameToAction().
Referenced by CountCardsTest().
CardLongNameToAction()
Action open_spiel::tarok::CardLongNameToAction (const std::string & long_name)
Definition at line 60 of file tarok_test.cc.
{
  for (int i = 0; i < card_deck.size(); i++) {
    if (card_deck.at(i).long_name == long_name) return i;
  }
  SpielFatalError("Invalid long_name!");
  return -1;
}
References card_deck, i, and open_spiel::SpielFatalError().
Referenced by CapturedMondTest1(), CapturedMondTest2(), CapturedMondTest5(), CapturedMondTest6(), CapturedMondTest7(), CapturedMondTest8(), CapturedMondTest9(), and CardLongNamesToActions().
CardPoints()
int open_spiel::tarok::CardPoints (const std::vector< Action > & actions, const std::array< Card, 54 > & deck)
Definition at line 131 of file cards.cc.
{
  // counting is done in batches of three (for every batch we sum up points from
  // three cards and subtract 2 points, if the last batch has less than three
  // cards we subtract 1 point), mathematically, this is equevalent to
  // subtracting 2/3 from each card
  float points = 0;
  for (auto const& action : actions) {
    points += deck.at(action).points;
  }
  points -= actions.size() * 0.666f;
  return static_cast<int>(round(points));
}
References action.
Referenced by CountCardsTest().
ContractNameToString()
std::string open_spiel::tarok::ContractNameToString (const ContractName & contract_name)
Definition at line 53 of file contracts.cc.
{
  switch (contract_name) {
    case ContractName::kKlop:
      return "Klop";
    case ContractName::kThree:
      return "Three";
    case ContractName::kTwo:
      return "Two";
    case ContractName::kOne:
      return "One";
    case ContractName::kSoloThree:
      return "Solo three";
    case ContractName::kSoloTwo:
      return "Solo two";
    case ContractName::kSoloOne:
      return "Solo one";
    case ContractName::kBeggar:
      return "Beggar";
    case ContractName::kSoloWithout:
      return "Solo without";
    case ContractName::kOpenBeggar:
      return "Open beggar";
    case ContractName::kColourValatWithout:
      return "Colour valat without";
    case ContractName::kValatWithout:
      return "Valat without";
    case ContractName::kNotSelected:
      return "Not selected";
  }
}
References kBeggar, kColourValatWithout, kKlop, kNotSelected, kOne, kOpenBeggar, kSoloOne, kSoloThree, kSoloTwo, kSoloWithout, kThree, kTwo, and kValatWithout.
Referenced by open_spiel::tarok::TarokState::ActionToString(), operator<<(), and open_spiel::tarok::TarokState::ToString().
CountCardsTest()
void open_spiel::tarok::CountCardsTest ()
Definition at line 148 of file tarok_test.cc.
                      {
  std::vector<Action> all_card_actions(54);
  std::iota(all_card_actions.begin(), all_card_actions.end(), 0);
  SPIEL_CHECK_EQ(CardPoints(all_card_actions, card_deck), 70);
  SPIEL_CHECK_EQ(CardPoints({}, card_deck), 0);
  SPIEL_CHECK_EQ(CardPoints(CardLongNamesToActions({"II"}), card_deck), 0);
  SPIEL_CHECK_EQ(CardPoints(CardLongNamesToActions({"II", "III"}), card_deck),
                 1);
  SPIEL_CHECK_EQ(CardPoints(CardLongNamesToActions({"Mond"}), card_deck), 4);
  std::vector<std::string> cards{"Mond", "Jack of Diamonds"};
  SPIEL_CHECK_EQ(CardPoints(CardLongNamesToActions(cards), card_deck), 6);
  cards = {"XIV", "Mond", "Jack of Diamonds"};
  SPIEL_CHECK_EQ(CardPoints(CardLongNamesToActions(cards), card_deck), 6);
  cards = {"XIV", "Mond", "Jack of Diamonds", "Queen of Diamonds"};
  SPIEL_CHECK_EQ(CardPoints(CardLongNamesToActions(cards), card_deck), 9);
  cards = {"II", "Jack of Clubs", "Queen of Clubs", "Mond", "King of Clubs"};
  SPIEL_CHECK_EQ(CardPoints(CardLongNamesToActions(cards), card_deck), 14);
}
References card_deck, CardLongNamesToActions(), CardPoints(), and SPIEL_CHECK_EQ.
Referenced by main().
DealCards()
DealtCards open_spiel::tarok::DealCards (int num_players, int seed)
Definition at line 96 of file cards.cc.
{
  std::vector<Action> cards(54);
  std::iota(cards.begin(), cards.end(), 0);
  Shuffle(&cards, std::mt19937(seed));
  // first six cards are talon
  auto begin = cards.begin();
  auto end = begin + 6;
  std::vector<Action> talon(begin, end);
  // deal the rest of the cards to players
  int num_cards_per_player = 48 / num_players;
  std::vector<std::vector<Action>> players_cards;
  players_cards.reserve(num_players);
  std::advance(begin, 6);
  for (int i = 0; i < num_players; i++) {
    std::advance(end, num_cards_per_player);
    std::vector<Action> player_cards(begin, end);
    // player's cards are sorted since legal actions need to be returned in
    // ascending order
    std::sort(player_cards.begin(), player_cards.end());
    players_cards.push_back(player_cards);
    std::advance(begin, num_cards_per_player);
  }
  return {talon, players_cards};
}
References i, and Shuffle().
Referenced by DealtCardsContentTest(), DealtCardsSizeTest(), open_spiel::tarok::TarokGame::DeserializeState(), and PlayersCardsSortedTest().
DealtCardsContentTest()
void open_spiel::tarok::DealtCardsContentTest (int num_players)
Definition at line 124 of file tarok_test.cc.
{
  // 3 players
  auto [talon, players_cards] = DealCards(num_players, 42);
  // flatten and sort all the dealt cards
  std::vector<int> all_dealt_cards(talon.begin(), talon.end());
  for (auto const& player_cards : players_cards) {
    all_dealt_cards.insert(all_dealt_cards.end(), player_cards.begin(),
                           player_cards.end());
  }
  std::sort(all_dealt_cards.begin(), all_dealt_cards.end());
  // check the actual content
  for (int i = 0; i < 54; i++) {
    SPIEL_CHECK_EQ(all_dealt_cards.at(i), i);
  }
}
References DealCards(), i, and SPIEL_CHECK_EQ.
Referenced by main().
DealtCardsSizeTest()
void open_spiel::tarok::DealtCardsSizeTest (int num_players)
Definition at line 115 of file tarok_test.cc.
{
  auto [talon, players_cards] = DealCards(num_players, 42);
  SPIEL_CHECK_EQ(talon.size(), 6);
  int num_cards_per_player = 48 / num_players;
  for (auto const& player_cards : players_cards) {
    SPIEL_CHECK_EQ(player_cards.size(), num_cards_per_player);
  }
}
References DealCards(), and SPIEL_CHECK_EQ.
Referenced by main().
Factory()
std::shared_ptr< const Game > open_spiel::tarok::Factory (const GameParameters & params)
Definition at line 44 of file tarok.cc.
{
  return std::shared_ptr<const Game>(new TarokGame(params));
}
GamePhaseToString()
std::string open_spiel::tarok::GamePhaseToString (const GamePhase & game_phase)
Definition at line 1020 of file tarok.cc.
{
  switch (game_phase) {
    case GamePhase::kCardDealing:
      return "Card dealing";
    case GamePhase::kBidding:
      return "Bidding";
    case GamePhase::kKingCalling:
      return "King calling";
    case GamePhase::kTalonExchange:
      return "Talon exchange";
    case GamePhase::kTricksPlaying:
      return "Tricks playing";
    case GamePhase::kFinished:
      return "Finished";
  }
}
References kBidding, kCardDealing, kFinished, kKingCalling, kTalonExchange, and kTricksPlaying.
Referenced by operator<<(), and open_spiel::tarok::TarokState::ToString().
InitializeCardDeck()
const std::array< Card, 54 > open_spiel::tarok::InitializeCardDeck ()
Definition at line 34 of file cards.cc.
{
  return {// taroks
          Card(CardSuit::kTaroks, 8, 5, "T1", "Pagat"),
          Card(CardSuit::kTaroks, 9, 1, "T2", "II"),
          Card(CardSuit::kTaroks, 10, 1, "T3", "III"),
          Card(CardSuit::kTaroks, 11, 1, "T4", "IIII"),
          Card(CardSuit::kTaroks, 12, 1, "T5", "V"),
          Card(CardSuit::kTaroks, 13, 1, "T6", "VI"),
          Card(CardSuit::kTaroks, 14, 1, "T7", "VII"),
          Card(CardSuit::kTaroks, 15, 1, "T8", "VIII"),
          Card(CardSuit::kTaroks, 16, 1, "T9", "IX"),
          Card(CardSuit::kTaroks, 17, 1, "T10", "X"),
          Card(CardSuit::kTaroks, 18, 1, "T11", "XI"),
          Card(CardSuit::kTaroks, 19, 1, "T12", "XII"),
          Card(CardSuit::kTaroks, 20, 1, "T13", "XIII"),
          Card(CardSuit::kTaroks, 21, 1, "T14", "XIV"),
          Card(CardSuit::kTaroks, 22, 1, "T15", "XV"),
          Card(CardSuit::kTaroks, 23, 1, "T16", "XVI"),
          Card(CardSuit::kTaroks, 24, 1, "T17", "XVII"),
          Card(CardSuit::kTaroks, 25, 1, "T18", "XVIII"),
          Card(CardSuit::kTaroks, 26, 1, "T19", "XIX"),
          Card(CardSuit::kTaroks, 27, 1, "T20", "XX"),
          Card(CardSuit::kTaroks, 28, 5, "T21", "Mond"),
          Card(CardSuit::kTaroks, 29, 5, "T22", "Skis"),
          // hearts
          Card(CardSuit::kHearts, 0, 1, "H4", "4 of Hearts"),
          Card(CardSuit::kHearts, 1, 1, "H3", "3 of Hearts"),
          Card(CardSuit::kHearts, 2, 1, "H2", "2 of Hearts"),
          Card(CardSuit::kHearts, 3, 1, "H1", "1 of Hearts"),
          Card(CardSuit::kHearts, 4, 2, "HJ", "Jack of Hearts"),
          Card(CardSuit::kHearts, 5, 3, "HKN", "Knight of Hearts"),
          Card(CardSuit::kHearts, 6, 4, "HQ", "Queen of Hearts"),
          Card(CardSuit::kHearts, 7, 5, "HKI", "King of Hearts"),
          // diamonds
          Card(CardSuit::kDiamonds, 0, 1, "D4", "4 of Diamonds"),
          Card(CardSuit::kDiamonds, 1, 1, "D3", "3 of Diamonds"),
          Card(CardSuit::kDiamonds, 2, 1, "D2", "2 of Diamonds"),
          Card(CardSuit::kDiamonds, 3, 1, "D1", "1 of Diamonds"),
          Card(CardSuit::kDiamonds, 4, 2, "DJ", "Jack of Diamonds"),
          Card(CardSuit::kDiamonds, 5, 3, "DKN", "Knight of Diamonds"),
          Card(CardSuit::kDiamonds, 6, 4, "DQ", "Queen of Diamonds"),
          Card(CardSuit::kDiamonds, 7, 5, "DKI", "King of Diamonds"),
          // spades
          Card(CardSuit::kSpades, 0, 1, "S7", "7 of Spades"),
          Card(CardSuit::kSpades, 1, 1, "S8", "8 of Spades"),
          Card(CardSuit::kSpades, 2, 1, "S9", "9 of Spades"),
          Card(CardSuit::kSpades, 3, 1, "S10", "10 of Spades"),
          Card(CardSuit::kSpades, 4, 2, "SJ", "Jack of Spades"),
          Card(CardSuit::kSpades, 5, 3, "SKN", "Knight of Spades"),
          Card(CardSuit::kSpades, 6, 4, "SQ", "Queen of Spades"),
          Card(CardSuit::kSpades, 7, 5, "SKI", "King of Spades"),
          // clubs
          Card(CardSuit::kClubs, 0, 1, "C7", "7 of Clubs"),
          Card(CardSuit::kClubs, 1, 1, "C8", "8 of Clubs"),
          Card(CardSuit::kClubs, 2, 1, "C9", "9 of Clubs"),
          Card(CardSuit::kClubs, 3, 1, "C10", "10 of Clubs"),
          Card(CardSuit::kClubs, 4, 2, "CJ", "Jack of Clubs"),
          Card(CardSuit::kClubs, 5, 3, "CKN", "Knight of Clubs"),
          Card(CardSuit::kClubs, 6, 4, "CQ", "Queen of Clubs"),
          Card(CardSuit::kClubs, 7, 5, "CKI", "King of Clubs")};
}
References kClubs, kDiamonds, kHearts, kSpades, and kTaroks.
InitializeContracts()
const std::array< Contract, 12 > open_spiel::tarok::InitializeContracts ()
Definition at line 32 of file contracts.cc.
{
  return {
      Contract(ContractName::kKlop, 70, 0, false, false, true),
      Contract(ContractName::kThree, 10, 3, true, false, false),
      Contract(ContractName::kTwo, 20, 2, true, false, false),
      Contract(ContractName::kOne, 30, 1, true, false, false),
      Contract(ContractName::kSoloThree, 40, 3, false, false, false),
      Contract(ContractName::kSoloTwo, 50, 2, false, false, false),
      Contract(ContractName::kSoloOne, 60, 1, false, false, false),
      Contract(ContractName::kBeggar, 70, 0, false, true, true),
      Contract(ContractName::kSoloWithout, 80, 0, false, true, false),
      Contract(ContractName::kOpenBeggar, 90, 0, false, true, true),
      Contract(ContractName::kColourValatWithout, 125, 0, false, true, false),
      Contract(ContractName::kValatWithout, 500, 0, false, true, false)};
}
References kBeggar, kColourValatWithout, kKlop, kOne, kOpenBeggar, kSoloOne, kSoloThree, kSoloTwo, kSoloWithout, kThree, kTwo, and kValatWithout.
NewTarokGame()
std::shared_ptr< const TarokGame > open_spiel::tarok::NewTarokGame (const GameParameters & params)
Definition at line 36 of file tarok_test.cc.
{
  return std::static_pointer_cast<const TarokGame>(LoadGame("tarok", params));
}
References open_spiel::LoadGame().
Referenced by BiddingPhase3PlayersTest1(), BiddingPhase3PlayersTest2(), BiddingPhase3PlayersTest3(), BiddingPhase3PlayersTest4(), BiddingPhase4PlayersTest1(), BiddingPhase4PlayersTest2(), BiddingPhase4PlayersTest3(), BiddingPhase4PlayersTest4(), BiddingPhase4PlayersTest5(), CardDealingPhaseTest(), CardDeckShufflingSeedTest(), and StateAfterActions().
operator<<() [1/2]
std::ostream & open_spiel::tarok::operator<< (std::ostream & os, const ContractName & contract_name)
Definition at line 48 of file contracts.cc.
{
  os << ContractNameToString(contract_name);
  return os;
}
References ContractNameToString().
operator<<() [2/2]
std::ostream & open_spiel::tarok::operator<< (std::ostream & os, const GamePhase & game_phase)
Definition at line 1015 of file tarok.cc.
{
  os << GamePhaseToString(game_phase);
  return os;
}
References GamePhaseToString().
PlayersCardsSortedTest()
void open_spiel::tarok::PlayersCardsSortedTest ()
Definition at line 141 of file tarok_test.cc.
{
  auto [talon, players_cards] = DealCards(3, 42);
  for (auto const& player_cards : players_cards) {
    SPIEL_CHECK_TRUE(std::is_sorted(player_cards.begin(), player_cards.end()));
  }
}
References DealCards(), and SPIEL_CHECK_TRUE.
Referenced by main().
REGISTER_SPIEL_GAME()
open_spiel::tarok::REGISTER_SPIEL_GAME (kGameType , Factory)
Shuffle()
void open_spiel::tarok::Shuffle (std::vector< Action > * actions, std::mt19937 && rng)
Definition at line 125 of file cards.cc.
{
  for (int i = actions->size() - 1; i > 0; i--) {
    std::swap(actions->at(i), actions->at(rng() % (i + 1)));
  }
}
References i.
Referenced by DealCards().
single_tensor()
RegisterSingleTensorObserver open_spiel::tarok::single_tensor (kGameType. short_name)
StateAfterActions()
std::unique_ptr< TarokState > open_spiel::tarok::StateAfterActions (const GameParameters & params, const std::vector< Action > & actions)
Definition at line 40 of file tarok_test.cc.
{
  auto state = NewTarokGame(params)->NewInitialTarokState();
  for (auto const& action : actions) {
    state->ApplyAction(action);
  }
  return state;
}
References action, NewTarokGame(), and state.
Referenced by CapturedMondTest1(), CapturedMondTest2(), CapturedMondTest3(), CapturedMondTest4(), CapturedMondTest5(), CapturedMondTest6(), CapturedMondTest7(), CapturedMondTest8(), CapturedMondTest9(), TalonExchangePhaseTest1(), TalonExchangePhaseTest2(), TalonExchangePhaseTest3(), TalonExchangePhaseTest4(), TalonExchangePhaseTest5(), TalonExchangePhaseTest6(), TalonExchangePhaseTest7(), TalonExchangePhaseTest8(), TricksPlayingPhaseTest1(), TricksPlayingPhaseTest2(), TricksPlayingPhaseTest3(), TricksPlayingPhaseTest4(), TricksPlayingPhaseTest5(), TricksPlayingPhaseTest6(), and TricksPlayingPhaseTest7().
TalonExchangePhaseTest1()
void open_spiel::tarok::TalonExchangePhaseTest1 ()
Definition at line 674 of file tarok_test.cc.
{
  // 3 talon exchanges, select the first set
  auto state = StateAfterActions(
      GameParameters(),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidThreeAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kThree);
  auto talon_initial = state->TalonSets();
  SPIEL_CHECK_EQ(talon_initial.size(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {0, 1}));
  for (auto const& talon_set : talon_initial) {
    SPIEL_CHECK_EQ(talon_set.size(), 3);
  }
  // select the first set
  state->ApplyAction(0);
  auto talon_end = state->TalonSets();
  SPIEL_CHECK_EQ(talon_end.size(), 1);
  SPIEL_CHECK_EQ(talon_initial.at(1), talon_end.at(0));
  SPIEL_CHECK_TRUE(AllActionsInOtherActions(
      talon_initial.at(0), state->PlayerCards(state->CurrentPlayer())));
  // discard the first three cards
  auto legal_actions = state->LegalActions();
  for (int i = 0; i < 3; i++) {
    state->ApplyAction(legal_actions.at(i));
    SPIEL_CHECK_FALSE(AllActionsInOtherActions(
        {legal_actions.at(i)}, state->PlayerCards(state->CurrentPlayer())));
  }
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
}
References AllActionsInOtherActions(), AllEq(), i, kBidPassAction, kBidThreeAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TalonExchangePhaseTest1().
Referenced by main(), and TalonExchangePhaseTest1().
TalonExchangePhaseTest2()
void open_spiel::tarok::TalonExchangePhaseTest2 ()
Definition at line 706 of file tarok_test.cc.
{
  // 3 talon exchanges, select the second set
  auto state = StateAfterActions(
      GameParameters(),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidThreeAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kThree);
  auto talon_initial = state->TalonSets();
  SPIEL_CHECK_EQ(talon_initial.size(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {0, 1}));
  for (auto const& talon_set : talon_initial) {
    SPIEL_CHECK_EQ(talon_set.size(), 3);
  }
  // select the second set
  state->ApplyAction(1);
  auto talon_end = state->TalonSets();
  SPIEL_CHECK_EQ(talon_end.size(), 1);
  SPIEL_CHECK_EQ(talon_initial.at(0), talon_end.at(0));
  SPIEL_CHECK_TRUE(AllActionsInOtherActions(
      talon_initial.at(1), state->PlayerCards(state->CurrentPlayer())));
  // discard the first three cards
  auto legal_actions = state->LegalActions();
  for (int i = 0; i < 3; i++) {
    state->ApplyAction(legal_actions.at(i));
    SPIEL_CHECK_FALSE(AllActionsInOtherActions(
        {legal_actions.at(i)}, state->PlayerCards(state->CurrentPlayer())));
  }
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
}
References AllActionsInOtherActions(), AllEq(), i, kBidPassAction, kBidThreeAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TalonExchangePhaseTest2().
Referenced by main(), and TalonExchangePhaseTest2().
TalonExchangePhaseTest3()
void open_spiel::tarok::TalonExchangePhaseTest3 ()
Definition at line 738 of file tarok_test.cc.
{
  // 2 talon exchanges, select the middle set
  auto state = StateAfterActions(
      GameParameters(),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidTwoAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kTwo);
  auto talon_initial = state->TalonSets();
  SPIEL_CHECK_EQ(talon_initial.size(), 3);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {0, 1, 2}));
  for (auto const& talon_set : talon_initial) {
    SPIEL_CHECK_EQ(talon_set.size(), 2);
  }
  // select the middle set
  state->ApplyAction(1);
  auto talon_end = state->TalonSets();
  SPIEL_CHECK_EQ(talon_end.size(), 2);
  SPIEL_CHECK_EQ(talon_initial.at(0), talon_end.at(0));
  SPIEL_CHECK_EQ(talon_initial.at(2), talon_end.at(1));
  SPIEL_CHECK_TRUE(AllActionsInOtherActions(
      talon_initial.at(1), state->PlayerCards(state->CurrentPlayer())));
  // discard the first two cards
  auto legal_actions = state->LegalActions();
  for (int i = 0; i < 2; i++) {
    state->ApplyAction(legal_actions.at(i));
    SPIEL_CHECK_FALSE(AllActionsInOtherActions(
        {legal_actions.at(i)}, state->PlayerCards(state->CurrentPlayer())));
  }
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
}
References AllActionsInOtherActions(), AllEq(), i, kBidPassAction, kBidTwoAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TalonExchangePhaseTest3().
Referenced by main(), and TalonExchangePhaseTest3().
TalonExchangePhaseTest4()
void open_spiel::tarok::TalonExchangePhaseTest4 ()
Definition at line 771 of file tarok_test.cc.
{
  // 1 talon exchange, select the first set
  auto state = StateAfterActions(
      GameParameters(),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidOneAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  auto talon_initial = state->TalonSets();
  SPIEL_CHECK_EQ(talon_initial.size(), 6);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {0, 1, 2, 3, 4, 5}));
  for (auto const& talon_set : talon_initial) {
    SPIEL_CHECK_EQ(talon_set.size(), 1);
  }
  // select the first set
  state->ApplyAction(0);
  auto talon_end = state->TalonSets();
  SPIEL_CHECK_EQ(talon_end.size(), 5);
  for (int i = 1; i < 6; i++) {
    SPIEL_CHECK_EQ(talon_initial.at(i), talon_end.at(i - 1));
  }
  SPIEL_CHECK_TRUE(AllActionsInOtherActions(
      talon_initial.at(0), state->PlayerCards(state->CurrentPlayer())));
  // discard the last card
  auto legal_actions = state->LegalActions();
  state->ApplyAction(legal_actions.at(legal_actions.size() - 1));
  SPIEL_CHECK_FALSE(
      AllActionsInOtherActions({legal_actions.at(legal_actions.size() - 1)},
                               state->PlayerCards(state->CurrentPlayer())));
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
}
References AllActionsInOtherActions(), AllEq(), i, kBidOneAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TalonExchangePhaseTest4().
Referenced by main(), and TalonExchangePhaseTest4().
TalonExchangePhaseTest5()
void open_spiel::tarok::TalonExchangePhaseTest5 ()
Definition at line 804 of file tarok_test.cc.
{
  // 1 talon exchange, select the fourth set
  auto state = StateAfterActions(
      GameParameters(),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidOneAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  auto talon_initial = state->TalonSets();
  SPIEL_CHECK_EQ(talon_initial.size(), 6);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {0, 1, 2, 3, 4, 5}));
  for (auto const& talon_set : talon_initial) {
    SPIEL_CHECK_EQ(talon_set.size(), 1);
  }
  // select the fourth set
  state->ApplyAction(3);
  auto talon_end = state->TalonSets();
  SPIEL_CHECK_EQ(talon_end.size(), 5);
  for (int i = 0; i < 5; i++) {
    if (i < 3)
      SPIEL_CHECK_EQ(talon_initial.at(i), talon_end.at(i));
    else
      SPIEL_CHECK_EQ(talon_initial.at(i + 1), talon_end.at(i));
  }
  SPIEL_CHECK_TRUE(AllActionsInOtherActions(
      talon_initial.at(3), state->PlayerCards(state->CurrentPlayer())));
  // discard the second card
  auto legal_actions = state->LegalActions();
  state->ApplyAction(legal_actions.at(1));
  SPIEL_CHECK_FALSE(AllActionsInOtherActions(
      {legal_actions.at(1)}, state->PlayerCards(state->CurrentPlayer())));
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
}
References AllActionsInOtherActions(), AllEq(), i, kBidOneAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TalonExchangePhaseTest5().
Referenced by main(), and TalonExchangePhaseTest5().
TalonExchangePhaseTest6()
void open_spiel::tarok::TalonExchangePhaseTest6 ()
Definition at line 839 of file tarok_test.cc.
{
  // 1 talon exchange, select the last set
  auto state = StateAfterActions(
      GameParameters(),
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidOneAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  auto talon_initial = state->TalonSets();
  SPIEL_CHECK_EQ(talon_initial.size(), 6);
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {0, 1, 2, 3, 4, 5}));
  for (auto const& talon_set : talon_initial) {
    SPIEL_CHECK_EQ(talon_set.size(), 1);
  }
  // select the last set
  state->ApplyAction(5);
  auto talon_end = state->TalonSets();
  SPIEL_CHECK_EQ(talon_end.size(), 5);
  for (int i = 0; i < 5; i++) {
    SPIEL_CHECK_EQ(talon_initial.at(i), talon_end.at(i));
  }
  SPIEL_CHECK_TRUE(AllActionsInOtherActions(
      talon_initial.at(5), state->PlayerCards(state->CurrentPlayer())));
  // discard the first card
  auto legal_actions = state->LegalActions();
  state->ApplyAction(legal_actions.at(0));
  SPIEL_CHECK_FALSE(AllActionsInOtherActions(
      {legal_actions.at(0)}, state->PlayerCards(state->CurrentPlayer())));
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
}
References AllActionsInOtherActions(), AllEq(), i, kBidOneAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TalonExchangePhaseTest6().
Referenced by main(), and TalonExchangePhaseTest6().
TalonExchangePhaseTest7()
void open_spiel::tarok::TalonExchangePhaseTest7 ()
Definition at line 871 of file tarok_test.cc.
{
  // check that taroks and kings cannot be exchanged
  auto state =
      StateAfterActions(GameParameters({{"rng_seed", GameParameter(42)}}),
                        {kDealCardsAction, kBidPassAction, kBidOneAction,
                         kBidPassAction, kBidOneAction, 1});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kOne);
  // check taroks and kings are not in legal actions
  for (auto const& action : state->LegalActions()) {
    const Card& card = card_deck.at(action);
    SPIEL_CHECK_TRUE(card.suit != CardSuit::kTaroks);
    SPIEL_CHECK_NE(card.points, 5);
  }
}
References action, card_deck, kBidOneAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_NE, SPIEL_CHECK_TRUE, state, StateAfterActions(), card::suit, and TalonExchangePhaseTest7().
Referenced by main(), and TalonExchangePhaseTest7().
TalonExchangePhaseTest8()
void open_spiel::tarok::TalonExchangePhaseTest8 ()
Definition at line 888 of file tarok_test.cc.
{
  // check that tarok can be exchanged if player has no other choice
  auto state =
      StateAfterActions(GameParameters({{"players", GameParameter(4)},
                                        {"rng_seed", GameParameter(141750)}}),
                        {kDealCardsAction, kBidPassAction, kBidPassAction,
                         kBidPassAction, kBidSoloTwoAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kSoloTwo);
  // select first set from talon
  state->ApplyAction(0);
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  // first the player must exchange non-tarok or non-king card
  // check taroks and kings are not in legal actions
  for (auto const& action : state->LegalActions()) {
    const Card& card = card_deck.at(action);
    SPIEL_CHECK_TRUE(card.suit != CardSuit::kTaroks);
    SPIEL_CHECK_NE(card.points, 5);
  }
  state->ApplyAction(state->LegalActions().at(0));
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTalonExchange);
  // at this point the player has only taroks and kings in his hand but still
  // needs to exchange one card
  // check only taroks (no trula or kings) are in legal actions
  for (auto const& action : state->LegalActions()) {
    const Card& card = card_deck.at(action);
    SPIEL_CHECK_TRUE(card.suit == CardSuit::kTaroks);
    SPIEL_CHECK_NE(card.points, 5);
  }
  state->ApplyAction(state->LegalActions().at(0));
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
}
References action, card_deck, kBidPassAction, kBidSoloTwoAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_NE, SPIEL_CHECK_TRUE, state, StateAfterActions(), card::suit, and TalonExchangePhaseTest8().
Referenced by main(), and TalonExchangePhaseTest8().
TricksPlayingPhaseTest1()
void open_spiel::tarok::TricksPlayingPhaseTest1 ()
Definition at line 950 of file tarok_test.cc.
{
  // check forced pagat in klop
  auto state = StateAfterActions(
      kTricksPlayingGameParams,
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidKlopAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kKlop);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {1, 3, 4, 7, 10, 18, 20, 26, 27,
                                                 30, 39, 42, 45, 49, 50, 51}));
  state->ApplyAction(20);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {20}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {21}));
  state->ApplyAction(21);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {20, 21}));
  // pagat is forced
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {0}));
  state->ApplyAction(0);
  // pagat won the trick
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
}
References AllEq(), kBidKlopAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TricksPlayingPhaseTest1().
Referenced by main(), and TricksPlayingPhaseTest1().
TricksPlayingPhaseTest2()
void open_spiel::tarok::TricksPlayingPhaseTest2 ()
Definition at line 979 of file tarok_test.cc.
{
  // check pagat not a legal action in klop when following and all taroks lower
  auto state = StateAfterActions(
      kTricksPlayingGameParams,
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidKlopAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kKlop);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {1, 3, 4, 7, 10, 18, 20, 26, 27,
                                                 30, 39, 42, 45, 49, 50, 51}));
  state->ApplyAction(18);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {18}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {19, 21}));
  state->ApplyAction(21);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {18, 21}));
  // pagat not available but all other taroks available
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {5, 8, 9, 14, 15, 16, 17}));
  state->ApplyAction(17);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
}
References AllEq(), kBidKlopAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TricksPlayingPhaseTest2().
Referenced by main(), and TricksPlayingPhaseTest2().
TricksPlayingPhaseTest3()
void open_spiel::tarok::TricksPlayingPhaseTest3 ()
Definition at line 1007 of file tarok_test.cc.
{
  // check pagat not a legal action in klop when opening
  auto state = StateAfterActions(
      kTricksPlayingGameParams,
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidKlopAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kKlop);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {1, 3, 4, 7, 10, 18, 20, 26, 27,
                                                 30, 39, 42, 45, 49, 50, 51}));
  state->ApplyAction(4);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {4}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {6, 11, 12, 13, 19, 21}));
  state->ApplyAction(6);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {4, 6}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {8, 9, 14, 15, 16, 17}));
  state->ApplyAction(8);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {5, 9, 14, 15, 16, 17, 22, 32,
                                                 33, 34, 40, 41, 48, 53}));
}
References AllEq(), kBidKlopAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TricksPlayingPhaseTest3().
Referenced by main(), and TricksPlayingPhaseTest3().
TricksPlayingPhaseTest4()
void open_spiel::tarok::TricksPlayingPhaseTest4 ()
Definition at line 1037 of file tarok_test.cc.
{
  // check legal non-tarok cards in klop
  auto state = StateAfterActions(
      kTricksPlayingGameParams,
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidKlopAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kKlop);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {1, 3, 4, 7, 10, 18, 20, 26, 27,
                                                 30, 39, 42, 45, 49, 50, 51}));
  state->ApplyAction(42);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {42}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {43}));
  state->ApplyAction(43);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {42, 43}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {40, 41}));
  state->ApplyAction(41);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
}
References AllEq(), kBidKlopAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TricksPlayingPhaseTest4().
Referenced by main(), and TricksPlayingPhaseTest4().
TricksPlayingPhaseTest5()
void open_spiel::tarok::TricksPlayingPhaseTest5 ()
Definition at line 1064 of file tarok_test.cc.
{
  // check scenarios where no card has to be beaten in klop
  auto state = StateAfterActions(
      kTricksPlayingGameParams,
      {kDealCardsAction, kBidPassAction, kBidPassAction, kBidKlopAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kKlop);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {1, 3, 4, 7, 10, 18, 20, 26, 27,
                                                 30, 39, 42, 45, 49, 50, 51}));
  state->ApplyAction(30);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {30}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {31, 35, 36, 37}));
  state->ApplyAction(37);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {30, 37}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {32, 33, 34}));
  state->ApplyAction(34);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {2, 6, 11, 12, 13, 19, 21, 25,
                                                 31, 35, 36, 38, 43, 47, 52}));
  state->ApplyAction(52);
  state->ApplyAction(53);
  state->ApplyAction(51);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(),
                         {5, 8, 9, 14, 15, 16, 17, 22, 32, 33, 40, 41, 48}));
  state->ApplyAction(32);
  // can't follow suit, i.e. forced to play tarok
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {32}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {1, 3, 4, 7, 10, 18, 20}));
  state->ApplyAction(1);
  // doesn't have to beat the opening card due to the second card being tarok
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {32, 1}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {31, 35, 36}));
  state->ApplyAction(36);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
}
References AllEq(), kBidKlopAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TricksPlayingPhaseTest5().
Referenced by main(), and TricksPlayingPhaseTest5().
TricksPlayingPhaseTest6()
void open_spiel::tarok::TricksPlayingPhaseTest6 ()
Definition at line 1118 of file tarok_test.cc.
{
  // check taroks don't win in colour valat
  auto state = StateAfterActions(
      kTricksPlayingGameParams,
      {kDealCardsAction, kBidColourValatAction, kBidPassAction, kBidPassAction,
       kBidColourValatAction});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(),
                 ContractName::kColourValatWithout);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(
      AllEq(state->LegalActions(),
            {2, 6, 11, 12, 13, 19, 21, 25, 31, 35, 36, 37, 38, 43, 47, 52}));
  state->ApplyAction(35);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {35}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {32, 33, 34}));
  state->ApplyAction(32);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {35, 32}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {30}));
  state->ApplyAction(30);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {2, 6, 11, 12, 13, 19, 21, 25,
                                                 31, 36, 37, 38, 43, 47, 52}));
  state->ApplyAction(37);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {37}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {33, 34}));
  state->ApplyAction(33);
  // can't follow suit, i.e. forced to play tarok
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {37, 33}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {1, 3, 4, 7, 10, 18, 20}));
  state->ApplyAction(1);
  // tarok didn't win the trick
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
}
References AllEq(), kBidColourValatAction, kBidPassAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TricksPlayingPhaseTest6().
Referenced by main(), and TricksPlayingPhaseTest6().
TricksPlayingPhaseTest7()
void open_spiel::tarok::TricksPlayingPhaseTest7 ()
Definition at line 1167 of file tarok_test.cc.
{
  // check positive contracts scenarios
  auto state =
      StateAfterActions(kTricksPlayingGameParams,
                        {kDealCardsAction, kBidPassAction, kBidTwoAction,
                         kBidPassAction, kBidTwoAction, 0, 40, 41});
  SPIEL_CHECK_EQ(state->CurrentGamePhase(), GamePhase::kTricksPlaying);
  SPIEL_CHECK_EQ(state->SelectedContractName(), ContractName::kTwo);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {1, 3, 4, 7, 10, 18, 20, 26, 27,
                                                 30, 39, 42, 45, 49, 50, 51}));
  state->ApplyAction(30);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {30}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {31, 35, 36, 37}));
  state->ApplyAction(31);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {30, 31}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {32, 33, 34}));
  state->ApplyAction(32);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 2);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {0, 5, 8, 9, 14, 15, 16, 17, 22,
                                                 24, 28, 33, 34, 48, 53}));
  state->ApplyAction(33);
  // can't follow suit, i.e. forced to play tarok
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {33}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {1, 3, 4, 7, 10, 18, 20}));
  state->ApplyAction(18);
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 1);
  SPIEL_CHECK_TRUE(AllEq(state->TrickCards(), {33, 18}));
  SPIEL_CHECK_TRUE(AllEq(state->LegalActions(), {35, 36, 37}));
  state->ApplyAction(37);
  // tarok won the trick
  SPIEL_CHECK_EQ(state->CurrentPlayer(), 0);
  SPIEL_CHECK_TRUE(state->TrickCards().empty());
}
References AllEq(), kBidPassAction, kBidTwoAction, kDealCardsAction, SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, state, StateAfterActions(), and TricksPlayingPhaseTest7().
Referenced by main(), and TricksPlayingPhaseTest7().
Variable Documentation
card_deck
const std::array<Card, 54> open_spiel::tarok::card_deck = InitializeCardDeck()
Definition at line 33 of file tarok_test.cc.
Referenced by CardLongNameToAction(), CountCardsTest(), TalonExchangePhaseTest7(), and TalonExchangePhaseTest8().
kBidBeggarAction
int open_spiel::tarok::kBidBeggarAction = 8 constexpr
Definition at line 27 of file tarok_test.cc.
Referenced by BiddingPhase3PlayersTest2(), BiddingPhase3PlayersTest3(), BiddingPhase4PlayersTest4(), and CapturedMondTest8().
kBidColourValatAction
int open_spiel::tarok::kBidColourValatAction = 11 constexpr
Definition at line 30 of file tarok_test.cc.
Referenced by BiddingPhase4PlayersTest5(), and TricksPlayingPhaseTest6().
kBidKlopAction
int open_spiel::tarok::kBidKlopAction = 1 inline constexpr
Definition at line 31 of file contracts.h.
Referenced by BiddingPhase3PlayersTest1(), BiddingPhase4PlayersTest1(), CapturedMondTest7(), TricksPlayingPhaseTest1(), TricksPlayingPhaseTest2(), TricksPlayingPhaseTest3(), TricksPlayingPhaseTest4(), and TricksPlayingPhaseTest5().
kBidOneAction
int open_spiel::tarok::kBidOneAction = 4 constexpr
Definition at line 25 of file tarok_test.cc.
Referenced by BiddingPhase3PlayersTest4(), BiddingPhase4PlayersTest2(), CapturedMondTest1(), CapturedMondTest2(), CapturedMondTest3(), CapturedMondTest4(), CapturedMondTest5(), CapturedMondTest6(), TalonExchangePhaseTest4(), TalonExchangePhaseTest5(), TalonExchangePhaseTest6(), and TalonExchangePhaseTest7().
kBidOpenBeggarAction
int open_spiel::tarok::kBidOpenBeggarAction = 10 constexpr
Definition at line 29 of file tarok_test.cc.
Referenced by BiddingPhase4PlayersTest5(), and CapturedMondTest9().
kBidPassAction
int open_spiel::tarok::kBidPassAction = 0 inline constexpr
Definition at line 30 of file contracts.h.
Referenced by BiddingPhase3PlayersTest1(), BiddingPhase3PlayersTest2(), BiddingPhase3PlayersTest3(), BiddingPhase3PlayersTest4(), BiddingPhase4PlayersTest1(), BiddingPhase4PlayersTest2(), BiddingPhase4PlayersTest3(), BiddingPhase4PlayersTest4(), BiddingPhase4PlayersTest5(), CapturedMondTest1(), CapturedMondTest2(), CapturedMondTest3(), CapturedMondTest4(), CapturedMondTest5(), CapturedMondTest6(), CapturedMondTest7(), CapturedMondTest8(), CapturedMondTest9(), TalonExchangePhaseTest1(), TalonExchangePhaseTest2(), TalonExchangePhaseTest3(), TalonExchangePhaseTest4(), TalonExchangePhaseTest5(), TalonExchangePhaseTest6(), TalonExchangePhaseTest7(), TalonExchangePhaseTest8(), TricksPlayingPhaseTest1(), TricksPlayingPhaseTest2(), TricksPlayingPhaseTest3(), TricksPlayingPhaseTest4(), TricksPlayingPhaseTest5(), TricksPlayingPhaseTest6(), and TricksPlayingPhaseTest7().
kBidSoloOneAction
int open_spiel::tarok::kBidSoloOneAction = 7 inline constexpr
Definition at line 34 of file contracts.h.
Referenced by BiddingPhase4PlayersTest3().
kBidSoloThreeAction
int open_spiel::tarok::kBidSoloThreeAction = 5 inline constexpr
Definition at line 33 of file contracts.h.
Referenced by BiddingPhase4PlayersTest3().
kBidSoloTwoAction
int open_spiel::tarok::kBidSoloTwoAction = 6 constexpr
Definition at line 26 of file tarok_test.cc.
Referenced by BiddingPhase4PlayersTest3(), and TalonExchangePhaseTest8().
kBidSoloWithoutAction
int open_spiel::tarok::kBidSoloWithoutAction = 9 constexpr
Definition at line 28 of file tarok_test.cc.
Referenced by BiddingPhase3PlayersTest3().
kBidThreeAction
int open_spiel::tarok::kBidThreeAction = 2 inline constexpr
Definition at line 32 of file contracts.h.
Referenced by TalonExchangePhaseTest1(), and TalonExchangePhaseTest2().
kBidTwoAction
int open_spiel::tarok::kBidTwoAction = 3 constexpr
Definition at line 24 of file tarok_test.cc.
Referenced by BiddingPhase3PlayersTest2(), BiddingPhase3PlayersTest4(), TalonExchangePhaseTest3(), and TricksPlayingPhaseTest7().
kBidValatWithoutAction
int open_spiel::tarok::kBidValatWithoutAction = 12 constexpr
Definition at line 31 of file tarok_test.cc.
Referenced by BiddingPhase3PlayersTest4(), and BiddingPhase4PlayersTest5().
kDealCardsAction
int open_spiel::tarok::kDealCardsAction = 0 constexpr
Definition at line 23 of file tarok_test.cc.
Referenced by BiddingPhase3PlayersTest1(), BiddingPhase3PlayersTest2(), BiddingPhase3PlayersTest3(), BiddingPhase3PlayersTest4(), BiddingPhase4PlayersTest1(), BiddingPhase4PlayersTest2(), BiddingPhase4PlayersTest3(), BiddingPhase4PlayersTest4(), BiddingPhase4PlayersTest5(), CapturedMondTest1(), CapturedMondTest2(), CapturedMondTest3(), CapturedMondTest4(), CapturedMondTest5(), CapturedMondTest6(), CapturedMondTest7(), CapturedMondTest8(), CapturedMondTest9(), TalonExchangePhaseTest1(), TalonExchangePhaseTest2(), TalonExchangePhaseTest3(), TalonExchangePhaseTest4(), TalonExchangePhaseTest5(), TalonExchangePhaseTest6(), TalonExchangePhaseTest7(), TalonExchangePhaseTest8(), TricksPlayingPhaseTest1(), TricksPlayingPhaseTest2(), TricksPlayingPhaseTest3(), TricksPlayingPhaseTest4(), TricksPlayingPhaseTest5(), TricksPlayingPhaseTest6(), and TricksPlayingPhaseTest7().
kDefaultNumPLayers
int open_spiel::tarok::kDefaultNumPLayers = 3 inline constexpr
Definition at line 33 of file tarok.h.
kDefaultSeed
int open_spiel::tarok::kDefaultSeed = -1 inline constexpr
Definition at line 35 of file tarok.h.
kGameType
const GameType open_spiel::tarok::kGameType
Initial value:
{"tarok",
                         "Slovenian Tarok",
                         GameType::Dynamics::kSequential,
                         GameType::ChanceMode::kSampledStochastic,
                         GameType::Information::kImperfectInformation,
                         GameType::Utility::kGeneralSum,
                         GameType::RewardModel::kTerminal,
                         4,
                         3,
                         true,
                         false,
                         false,
                         false,
                         {{"players", GameParameter(kDefaultNumPLayers)},
                          {"rng_seed", GameParameter(kDefaultSeed)}}}
Definition at line 27 of file tarok.cc.
                        {"tarok",            // short_name
                         "Slovenian Tarok",  // long_name
                         GameType::Dynamics::kSequential,
                         GameType::ChanceMode::kSampledStochastic,
                         GameType::Information::kImperfectInformation,
                         GameType::Utility::kGeneralSum,
                         GameType::RewardModel::kTerminal,
                         4,      // max_num_players
                         3,      // min_num_players
                         true,   // provides_information_state_string
                         false,  // provides_information_state_tensor
                         false,  // provides_observation_string
                         false,  // provides_observation_tensor
                         // parameter_specification
                         {{"players", GameParameter(kDefaultNumPLayers)},
                          {"rng_seed", GameParameter(kDefaultSeed)}}};
Referenced by open_spiel::tarok::TarokGame::TarokGame().
kInvalidBidAction
int open_spiel::tarok::kInvalidBidAction = -1 inline constexpr
Definition at line 29 of file contracts.h.
Referenced by open_spiel::tarok::TarokState::TarokState().
kKingOfClubsAction
int open_spiel::tarok::kKingOfClubsAction = 53 inline constexpr
Definition at line 36 of file cards.h.
Referenced by open_spiel::tarok::TarokState::LegalActions().
kKingOfDiamondsAction
int open_spiel::tarok::kKingOfDiamondsAction = 37 inline constexpr
Definition at line 34 of file cards.h.
Referenced by open_spiel::tarok::TarokState::LegalActions().
kKingOfHeartsAction
int open_spiel::tarok::kKingOfHeartsAction = 29 inline constexpr
Definition at line 33 of file cards.h.
Referenced by open_spiel::tarok::TarokState::LegalActions().
kKingOfSpadesAction
int open_spiel::tarok::kKingOfSpadesAction = 45 inline constexpr
Definition at line 35 of file cards.h.
Referenced by CapturedMondTest5(), and open_spiel::tarok::TarokState::LegalActions().
kMondAction
int open_spiel::tarok::kMondAction = 20 inline constexpr
Definition at line 31 of file cards.h.
kPagatAction
int open_spiel::tarok::kPagatAction = 0 inline constexpr
Definition at line 30 of file cards.h.
kSkisAction
int open_spiel::tarok::kSkisAction = 21 inline constexpr
Definition at line 32 of file cards.h.