open spiel: open_spiel.python.algorithms.lp_solver Namespace Reference
open_spiel.python.algorithms.lp_solver Namespace Reference
Classes
class _Constraint
class _Variable
class LinearProgram
Functions
solve_zero_sum_matrix_game (game)
is_dominated (action, game_or_payoffs, player, mode=DOMINANCE_STRICT, tol=1e-7, return_mixture=False)
_pure_dominated_from_advantages (advantages, mode, tol=1e-7)
iterated_dominance (game_or_payoffs, mode, tol=1e-7)
Variables
int OBJ_MAX = 1
int OBJ_MIN = 2
int CONS_TYPE_LEQ = 3
int CONS_TYPE_GEQ = 4
int CONS_TYPE_EQ = 5
int DOMINANCE_STRICT = 1
int DOMINANCE_VERY_WEAK = 2
int DOMINANCE_WEAK = 3
Detailed Description
LP Solver for two-player zero-sum games.
Function Documentation
_pure_dominated_from_advantages()
open_spiel.python.algorithms.lp_solver._pure_dominated_from_advantages (advantages, mode, tol = 1e-7) protected
Definition at line 425 of file lp_solver.py.
def _pure_dominated_from_advantages(advantages, mode, tol=1e-7):
  if mode == DOMINANCE_STRICT:
    return (advantages > tol).all(1)
  if mode == DOMINANCE_WEAK:
    return (advantages >= -tol).all(1) & (advantages.sum(1) > tol)
  if mode == DOMINANCE_VERY_WEAK:
    return (advantages >= -tol).all(1)
Referenced by open_spiel.python.algorithms.lp_solver.iterated_dominance().
is_dominated()
open_spiel.python.algorithms.lp_solver.is_dominated (action, game_or_payoffs, player, mode = DOMINANCE_STRICT, tol = 1e-7, return_mixture = False)
Determines whether a pure strategy is dominated by any mixture strategies.
Args:
  action: index of an action for `player`
  game_or_payoffs: either a pyspiel matrix- or normal-form game, or a payoff
    tensor for `player` with ndim == number of players
  player: index of the player (an integer)
  mode: dominance criterion: strict, weak, or very weak
  tol: tolerance
  return_mixture: whether to return the dominating strategy if one exists
Returns:
  If `return_mixture`:
    a dominating mixture strategy if one exists, or `None`.
    the strategy is provided as a 1D numpy array of mixture weights.
  Otherwise: True if a dominating strategy exists, False otherwise.
Definition at line 327 of file lp_solver.py.
                 return_mixture=False):
  """Determines whether a pure strategy is dominated by any mixture strategies.
  Args:
    action: index of an action for `player`
    game_or_payoffs: either a pyspiel matrix- or normal-form game, or a payoff
      tensor for `player` with ndim == number of players
    player: index of the player (an integer)
    mode: dominance criterion: strict, weak, or very weak
    tol: tolerance
    return_mixture: whether to return the dominating strategy if one exists
  Returns:
    If `return_mixture`:
      a dominating mixture strategy if one exists, or `None`.
      the strategy is provided as a 1D numpy array of mixture weights.
    Otherwise: True if a dominating strategy exists, False otherwise.
  """
  # For more detail, please refer to Sec 4.5.2 of Shoham & Leyton-Brown, 2009:
  # Multiagent Systems: Algorithmic, Game-Theoretic, and Logical Foundations
  # http://www.masfoundations.org/mas.pdf
  assert mode in (DOMINANCE_STRICT, DOMINANCE_VERY_WEAK, DOMINANCE_WEAK)
  payoffs = utils.game_payoffs_array(game_or_payoffs)[player] if isinstance(
      game_or_payoffs, pyspiel.NormalFormGame) else np.asfarray(game_or_payoffs)
  # Reshape payoffs so rows correspond to `player` and cols to the joint action
  # of all other players
  payoffs = np.moveaxis(payoffs, player, 0)
  payoffs = payoffs.reshape((payoffs.shape[0], -1))
  num_rows, num_cols = payoffs.shape
  cvxopt.solvers.options["show_progress"] = False
  cvxopt.solvers.options["maxtol"] = tol
  cvxopt.solvers.options["feastol"] = tol
  lp = LinearProgram(OBJ_MAX)
  # One var for every row probability, fixed to 0 if inactive
  for r in range(num_rows):
    if r == action:
      lp.add_or_reuse_variable(r, lb=0, ub=0)
    else:
      lp.add_or_reuse_variable(r, lb=0)
  # For the strict LP we normalize the payoffs to be strictly positive
  if mode == DOMINANCE_STRICT:
    to_subtract = payoffs.min() - 1
  else:
    to_subtract = 0
    # For non-strict LPs the probabilities must sum to 1
    lp.add_or_reuse_constraint(num_cols, CONS_TYPE_EQ)
    lp.set_cons_rhs(num_cols, 1)
    for r in range(num_rows):
      if r != action:
        lp.set_cons_coeff(num_cols, r, 1)
  # The main dominance constraint
  for c in range(num_cols):
    lp.add_or_reuse_constraint(c, CONS_TYPE_GEQ)
    lp.set_cons_rhs(c, payoffs[action, c] - to_subtract)
    for r in range(num_rows):
      if r != action:
        lp.set_cons_coeff(c, r, payoffs[r, c] - to_subtract)
  if mode == DOMINANCE_STRICT:
    # Minimize sum of probabilities
    for r in range(num_rows):
      if r != action:
        lp.set_obj_coeff(r, -1)
    mixture = lp.solve()
    if mixture is not None and np.sum(mixture) < 1 - tol:
      mixture = np.squeeze(mixture, 1) / np.sum(mixture)
    else:
      mixture = None
  if mode == DOMINANCE_VERY_WEAK:
    # Check feasibility
    mixture = lp.solve()
    if mixture is not None:
      mixture = np.squeeze(mixture, 1)
  if mode == DOMINANCE_WEAK:
    # Check feasibility and whether there's any advantage
    for r in range(num_rows):
      lp.set_obj_coeff(r, payoffs[r].sum())
    mixture = lp.solve()
    if mixture is not None:
      mixture = np.squeeze(mixture, 1)
      if (np.dot(mixture, payoffs) - payoffs[action]).sum() <= tol:
        mixture = None
  return mixture if return_mixture else (mixture is not None)
Referenced by open_spiel.python.algorithms.lp_solver.iterated_dominance().
iterated_dominance()
open_spiel.python.algorithms.lp_solver.iterated_dominance (game_or_payoffs, mode, tol = 1e-7)
Reduces a strategy space using iterated dominance.
See: http://www.smallparty.com/yoram/classes/principles/nash.pdf
Args:
  game_or_payoffs: either a pyspiel matrix- or normal-form game, or a payoff
    tensor of dimension `num_players` + 1. First dimension is the player,
    followed by the actions of all players, e.g. a 3x3 game (2 players) has
    dimension [2,3,3].
  mode: DOMINANCE_STRICT, DOMINANCE_WEAK, or DOMINANCE_VERY_WEAK
  tol: tolerance
Returns:
  A tuple (`reduced_game`, `live_actions`).
  * if `game_or_payoffs` is an instance of `pyspiel.MatrixGame`, so is
    `reduced_game`; otherwise `reduced_game` is a payoff tensor.
  * `live_actions` is a tuple of length `num_players`, where
    `live_actions[player]` is a boolean vector of shape `num_actions`;
     `live_actions[player][action]` is `True` if `action` wasn't dominated for
     `player`.
Definition at line 434 of file lp_solver.py.
def iterated_dominance(game_or_payoffs, mode, tol=1e-7):
  """Reduces a strategy space using iterated dominance.
  See: http://www.smallparty.com/yoram/classes/principles/nash.pdf
  Args:
    game_or_payoffs: either a pyspiel matrix- or normal-form game, or a payoff
      tensor of dimension `num_players` + 1. First dimension is the player,
      followed by the actions of all players, e.g. a 3x3 game (2 players) has
      dimension [2,3,3].
    mode: DOMINANCE_STRICT, DOMINANCE_WEAK, or DOMINANCE_VERY_WEAK
    tol: tolerance
  Returns:
    A tuple (`reduced_game`, `live_actions`).
    * if `game_or_payoffs` is an instance of `pyspiel.MatrixGame`, so is
      `reduced_game`; otherwise `reduced_game` is a payoff tensor.
    * `live_actions` is a tuple of length `num_players`, where
      `live_actions[player]` is a boolean vector of shape `num_actions`;
       `live_actions[player][action]` is `True` if `action` wasn't dominated for
       `player`.
  """
  payoffs = utils.game_payoffs_array(game_or_payoffs) if isinstance(
      game_or_payoffs, pyspiel.NormalFormGame) else np.asfarray(game_or_payoffs)
  live_actions = [
      np.ones(num_actions, bool) for num_actions in payoffs.shape[1:]
  ]
  progress = True
  while progress:
    progress = False
    # trying faster method first
    for method in ("pure", "mixed"):
      if progress:
        continue
      for player, live in enumerate(live_actions):
        if live.sum() == 1:
          # one action is dominant
          continue
        # discarding all dominated opponent actions
        payoffs_live = payoffs[player]
        for opponent in range(payoffs.shape[0]):
          if opponent != player:
            payoffs_live = payoffs_live.compress(live_actions[opponent],
                                                 opponent)
        # reshaping to (player_actions, joint_opponent_actions)
        payoffs_live = np.moveaxis(payoffs_live, player, 0)
        payoffs_live = payoffs_live.reshape((payoffs_live.shape[0], -1))
        for action in range(live.size):
          if not live[action]:
            continue
          if method == "pure":
            # mark all actions that `action` dominates
            advantage = payoffs_live[action] - payoffs_live
            dominated = _pure_dominated_from_advantages(advantage, mode, tol)
            dominated[action] = False
            dominated &= live
            if dominated.any():
              progress = True
              live &= ~dominated
              if live.sum() == 1:
                break
          if method == "mixed":
            # test if `action` is dominated by a mixed policy
            mixture = is_dominated(
                live[:action].sum(),
                payoffs_live[live],
                0,
                mode,
                tol,
                return_mixture=True)
            if mixture is None:
              continue
            # if it is, mark any other actions dominated by that policy
            progress = True
            advantage = mixture.dot(payoffs_live[live]) - payoffs_live[live]
            dominated = _pure_dominated_from_advantages(advantage, mode, tol)
            dominated[mixture > tol] = False
            assert dominated[live[:action].sum()]
            live.put(live.nonzero()[0], ~dominated)
            if live.sum() == 1:
              break
  for player, live in enumerate(live_actions):
    payoffs = payoffs.compress(live, player + 1)
  if isinstance(game_or_payoffs, pyspiel.MatrixGame):
    return pyspiel.MatrixGame(game_or_payoffs.get_type(),
                              game_or_payoffs.get_parameters(), [
                                  game_or_payoffs.row_action_name(action)
                                  for action in live_actions[0].nonzero()[0]
                              ], [
                                  game_or_payoffs.col_action_name(action)
                                  for action in live_actions[1].nonzero()[0]
                              ], *payoffs), live_actions
  else:
    return payoffs, live_actions
# TODO(author5): add a function for sequential games using sequence-form LPs.
References open_spiel.python.algorithms.lp_solver._pure_dominated_from_advantages(), and open_spiel.python.algorithms.lp_solver.is_dominated().
solve_zero_sum_matrix_game()
open_spiel.python.algorithms.lp_solver.solve_zero_sum_matrix_game (game)
Solves a matrix game by using linear programming.
Args:
  game: a pyspiel MatrixGame
Returns:
  A 4-tuple containing:
    - p0_sol (array-like): probability distribution over row actions
    - p1_sol (array-like): probability distribution over column actions
    - p0_sol_value, expected value to the first player
    - p1_sol_value, expected value to the second player
Definition at line 248 of file lp_solver.py.
def solve_zero_sum_matrix_game(game):
  """Solves a matrix game by using linear programming.
  Args:
    game: a pyspiel MatrixGame
  Returns:
    A 4-tuple containing:
      - p0_sol (array-like): probability distribution over row actions
      - p1_sol (array-like): probability distribution over column actions
      - p0_sol_value, expected value to the first player
      - p1_sol_value, expected value to the second player
  """
  # Solving a game for player i (e.g. row player) requires finding a mixed
  # policy over player i's pure strategies (actions) such that a value of the
  # mixed strategy against every opponent pure strategy is maximized.
  #
  # For more detail, please refer to Sec 4.1 of Shoham & Leyton-Brown, 2009:
  # Multiagent Systems: Algorithmic, Game-Theoretic, and Logical Foundations
  # http://www.masfoundations.org/mas.pdf
  #
  # For the row player the LP looks like:
  #    max V
  #     st. sigma_a1 \dot col_0 >= V
  #         sigma_a2 \dot col_1 >= V
  #              .
  #              .
  #         sigma_am \cot col_n >= V
  #         for all i, sigma_ai >= 0
  #         sigma \dot 1 = 1
  assert isinstance(game, pyspiel.MatrixGame)
  assert game.get_type().information == pyspiel.GameType.Information.ONE_SHOT
  assert game.get_type().utility == pyspiel.GameType.Utility.ZERO_SUM
  num_rows = game.num_rows()
  num_cols = game.num_cols()
  cvxopt.solvers.options["show_progress"] = False
  # First, do the row player (player 0).
  lp0 = LinearProgram(OBJ_MAX)
  for r in range(num_rows):  # one var per action / pure strategy
    lp0.add_or_reuse_variable(r, lb=0)
  lp0.add_or_reuse_variable(num_rows)  # V
  lp0.set_obj_coeff(num_rows, 1.0)  # max V
  for c in range(num_cols):
    lp0.add_or_reuse_constraint(c, CONS_TYPE_GEQ)
    for r in range(num_rows):
      lp0.set_cons_coeff(c, r, game.player_utility(0, r, c))
    lp0.set_cons_coeff(c, num_rows, -1.0)  # -V >= 0
  lp0.add_or_reuse_constraint(num_cols + 1, CONS_TYPE_EQ)
  lp0.set_cons_rhs(num_cols + 1, 1.0)
  for r in range(num_rows):
    lp0.set_cons_coeff(num_cols + 1, r, 1.0)
  sol = lp0.solve()
  p0_sol = sol[:-1]
  p0_sol_val = sol[-1]
  # Now, the column player (player 1).
  lp1 = LinearProgram(OBJ_MAX)
  for c in range(num_cols):  # one var per action / pure strategy
    lp1.add_or_reuse_variable(c, lb=0)
  lp1.add_or_reuse_variable(num_cols)  # V
  lp1.set_obj_coeff(num_cols, 1)  # max V
  for r in range(num_rows):
    lp1.add_or_reuse_constraint(r, CONS_TYPE_GEQ)
    for c in range(num_cols):
      lp1.set_cons_coeff(r, c, game.player_utility(1, r, c))
    lp1.set_cons_coeff(r, num_cols, -1.0)  # -V >= 0
  lp1.add_or_reuse_constraint(num_rows + 1, CONS_TYPE_EQ)
  lp1.set_cons_rhs(num_rows + 1, 1.0)
  for c in range(num_cols):
    lp1.set_cons_coeff(num_rows + 1, c, 1.0)
  sol = lp1.solve()
  p1_sol = sol[:-1]
  p1_sol_val = sol[-1]
  return p0_sol, p1_sol, p0_sol_val, p1_sol_val
Variable Documentation
CONS_TYPE_EQ
int open_spiel.python.algorithms.lp_solver.CONS_TYPE_EQ = 5
Definition at line 28 of file lp_solver.py.
CONS_TYPE_GEQ
int open_spiel.python.algorithms.lp_solver.CONS_TYPE_GEQ = 4
Definition at line 27 of file lp_solver.py.
CONS_TYPE_LEQ
int open_spiel.python.algorithms.lp_solver.CONS_TYPE_LEQ = 3
Definition at line 26 of file lp_solver.py.
DOMINANCE_STRICT
int open_spiel.python.algorithms.lp_solver.DOMINANCE_STRICT = 1
Definition at line 31 of file lp_solver.py.
DOMINANCE_VERY_WEAK
int open_spiel.python.algorithms.lp_solver.DOMINANCE_VERY_WEAK = 2
Definition at line 32 of file lp_solver.py.
DOMINANCE_WEAK
int open_spiel.python.algorithms.lp_solver.DOMINANCE_WEAK = 3
Definition at line 33 of file lp_solver.py.
OBJ_MAX
int open_spiel.python.algorithms.lp_solver.OBJ_MAX = 1
Definition at line 24 of file lp_solver.py.
OBJ_MIN
int open_spiel.python.algorithms.lp_solver.OBJ_MIN = 2
Definition at line 25 of file lp_solver.py.