open spiel: open_spiel::tiny_bridge Namespace Reference
open_spiel::tiny_bridge Namespace Reference
Classes
class TinyBridgeAuctionState
class TinyBridgeGame2p
class TinyBridgeGame4p
class TinyBridgePlayGame
class TinyBridgePlayState
Typedefs
using ScoringTable
Enumerations
enum Call {
kPass = 0 , k1H , k1S , k1NT ,
k2H , k2S , k2NT , kDouble ,
kRedouble
}
enum Seat {
kInvalidSeat = -1 , kWest = 0 , kNorth = 1 , kEast = 2 ,
kSouth = 3
}
Functions
std::string HandString (Action outcome)
std::string SeatString (Seat seat)
int Score_p0 (std::array< Seat, kDeckSize > holder, const TinyBridgeAuctionState::AuctionState &state)
double Score_2p_ (Action hand0, Action hand1, const TinyBridgeAuctionState::AuctionState &state)
ScoringTable MakeScores ()
double Score_2p (Action hand0, Action hand1, const TinyBridgeAuctionState::AuctionState &state)
bool IsConsistent (Action hand0, Action hand1)
Variables
constexpr int kNumBids = 6
constexpr int kNumActions2p = 1 + kNumBids
constexpr int kNumActions4p = 3 + kNumBids
constexpr int kNumRanks = 4
constexpr int kNumSuits = 2
constexpr int kDeckSize = kNumRanks * kNumSuits
constexpr int kNumSeats = 4
constexpr int kNumTricks = kDeckSize / kNumSeats
constexpr int kNumAbstractHands = 12
constexpr int kNumPrivates = (kDeckSize * (kDeckSize - 1)) / 2
constexpr std::array< const char *, kNumActions4p > kActionStr
Typedef Documentation
ScoringTable
using open_spiel::tiny_bridge::ScoringTable
Initial value:
 std::array<
    std::array<std::array<std::array<double, 2>, kNumActions2p>, kNumPrivates>,
    kNumPrivates>
Definition at line 367 of file tiny_bridge.cc.
Enumeration Type Documentation
Call
enum open_spiel::tiny_bridge::Call
Enumerator
kPass
k1H
k1S
k1NT
k2H
k2S
k2NT
kDouble
kRedouble
Definition at line 65 of file tiny_bridge.h.
{ kPass = 0, k1H, k1S, k1NT, k2H, k2S, k2NT, kDouble, kRedouble };
Seat
enum open_spiel::tiny_bridge::Seat
Enumerator
kInvalidSeat
kWest
kNorth
kEast
kSouth
Definition at line 77 of file tiny_bridge.h.
{ kInvalidSeat = -1, kWest = 0, kNorth = 1, kEast = 2, kSouth = 3 };
Function Documentation
HandString()
std::string open_spiel::tiny_bridge::HandString (Action outcome)
Definition at line 257 of file tiny_bridge.cc.
{
  auto cards = ChanceOutcomeToCards(outcome);
  return absl::StrCat(CardString(cards.first), CardString(cards.second));
}
References absl::StrCat().
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::ActionToString(), and open_spiel::tiny_bridge::TinyBridgeAuctionState::PlayerHandString().
IsConsistent()
bool open_spiel::tiny_bridge::IsConsistent (Action hand0, Action hand1)
Definition at line 818 of file tiny_bridge.cc.
{
  auto cards0 = ChanceOutcomeToCards(hand0);
  auto cards1 = ChanceOutcomeToCards(hand1);
  return cards0.first != cards1.first && cards0.second != cards1.second &&
         cards0.first != cards1.second && cards0.second != cards1.first;
}
Referenced by MakeScores().
MakeScores()
ScoringTable open_spiel::tiny_bridge::MakeScores ()
Definition at line 404 of file tiny_bridge.cc.
{
  ScoringTable scores;
  for (int hand0 = 0; hand0 < kNumPrivates; ++hand0) {
    for (int hand1 = 0; hand1 < kNumPrivates; ++hand1) {
      if (!IsConsistent(hand0, hand1)) continue;
      for (int contract = k1H; contract < kNumActions2p; ++contract) {
        for (Seat last_bidder : {kWest, kEast}) {
          scores[hand0][hand1][contract][last_bidder / 2] =
              Score_2p_(hand0, hand1,
                        {contract, last_bidder, kInvalidSeat, kInvalidSeat});
        }
      }
    }
  }
  return scores;
}
References IsConsistent(), k1H, kEast, kInvalidSeat, kNumActions2p, kNumPrivates, kWest, and Score_2p_().
Referenced by Score_2p().
Score_2p()
double open_spiel::tiny_bridge::Score_2p (Action hand0, Action hand1, const TinyBridgeAuctionState::AuctionState & state)
Definition at line 421 of file tiny_bridge.cc.
{
  if (state.last_bid == kPass) return 0;
  static const ScoringTable scoring_table = MakeScores();
  const double score =
      scoring_table[hand0][hand1][state.last_bid][state.last_bidder / 2];
  return score;
}
References kPass, MakeScores(), and state.
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::DoApplyAction().
Score_2p_()
double open_spiel::tiny_bridge::Score_2p_ (Action hand0, Action hand1, const TinyBridgeAuctionState::AuctionState & state)
Definition at line 372 of file tiny_bridge.cc.
{
  if (state.last_bid == kPass) return 0;
  const double freq = 1. / 6;
  double utility_p0 = 0;
  std::array<Seat, kDeckSize> holders_2p;
  std::fill(holders_2p.begin(), holders_2p.end(), kInvalidSeat);
  const auto cards0 = ChanceOutcomeToCards(hand0);
  holders_2p[cards0.first] = kWest;
  holders_2p[cards0.second] = kWest;
  const auto cards1 = ChanceOutcomeToCards(hand1);
  holders_2p[cards1.first] = kEast;
  holders_2p[cards1.second] = kEast;
  std::array<Seat, kDeckSize> holders_4p;
  for (int n0 = 0; n0 < 3; ++n0) {
    for (int n1 = n0 + 1; n1 < 4; ++n1) {
      int n = 0;
      for (int i = 0; i < kDeckSize; ++i) {
        if (holders_2p[i] == kInvalidSeat) {
          holders_4p[i] = (n == n0 || n == n1) ? kNorth : kSouth;
          ++n;
        } else {
          holders_4p[i] = holders_2p[i];
        }
      }
      utility_p0 += Score_p0(holders_4p, state) * freq;
    }
  }
  return utility_p0;
}
References i, kDeckSize, kEast, kInvalidSeat, kNorth, kPass, kSouth, kWest, n, Score_p0(), and state.
Referenced by MakeScores().
Score_p0()
int open_spiel::tiny_bridge::Score_p0 (std::array< Seat, kDeckSize > holder, const TinyBridgeAuctionState::AuctionState & state)
Definition at line 348 of file tiny_bridge.cc.
{
  if (state.last_bid == Call::kPass) return 0;
  std::shared_ptr<Game> game(new TinyBridgePlayGame({}));
  int trumps = (state.last_bid - 1) % 3;
  Seat leader = Seat((state.last_bidder + 3) % 4);
  Seat decl = Seat(state.last_bidder % 2);
  TinyBridgePlayState play{game, trumps, leader, holder};
  const double tricks =
      algorithms::AlphaBetaSearch(*game, &play, nullptr, -1, decl).first;
  SPIEL_CHECK_GE(tricks, 0);
  SPIEL_CHECK_LE(tricks, kNumTricks);
  const int declarer_score =
      Score(state.last_bid, tricks, state.doubler != kInvalidSeat,
            state.redoubler != kInvalidSeat, trumps);
  return (decl == 0) ? declarer_score : -declarer_score;
}
References open_spiel::algorithms::AlphaBetaSearch(), kInvalidSeat, kNumTricks, kPass, play, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and state.
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::DoApplyAction(), and Score_2p_().
SeatString()
std::string open_spiel::tiny_bridge::SeatString (Seat seat)
Definition at line 262 of file tiny_bridge.cc.
{ return std::string(1, kSeatChar[seat]); }
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::DealString().
Variable Documentation
kActionStr
std::array<const char*, kNumActions4p> open_spiel::tiny_bridge::kActionStr inline constexpr
Initial value:
{
    "Pass", "1H", "1S", "1NT", "2H", "2S", "2NT", "Dbl", "RDbl"}
Definition at line 75 of file tiny_bridge.h.
{
    "Pass", "1H", "1S", "1NT", "2H", "2S", "2NT", "Dbl", "RDbl"};
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::ActionToString().
kDeckSize
int open_spiel::tiny_bridge::kDeckSize = kNumRanks * kNumSuits inline constexpr
Definition at line 68 of file tiny_bridge.h.
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::ChanceOutcomes(), open_spiel::tiny_bridge::TinyBridgeAuctionState::InformationStateTensor(), open_spiel::tiny_bridge::TinyBridgeGame2p::InformationStateTensorShape(), open_spiel::tiny_bridge::TinyBridgeGame4p::InformationStateTensorShape(), open_spiel::tiny_bridge::TinyBridgePlayState::IsTerminal(), open_spiel::tiny_bridge::TinyBridgePlayState::LegalActions(), open_spiel::tiny_bridge::TinyBridgePlayGame::NumDistinctActions(), open_spiel::tiny_bridge::TinyBridgeAuctionState::ObservationTensor(), open_spiel::tiny_bridge::TinyBridgeGame2p::ObservationTensorShape(), open_spiel::tiny_bridge::TinyBridgeGame4p::ObservationTensorShape(), Score_2p_(), and open_spiel::tiny_bridge::TinyBridgePlayState::ToString().
kNumAbstractHands
int open_spiel::tiny_bridge::kNumAbstractHands = 12 inline constexpr
Definition at line 71 of file tiny_bridge.h.
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::InformationStateTensor(), open_spiel::tiny_bridge::TinyBridgeGame2p::InformationStateTensorShape(), open_spiel::tiny_bridge::TinyBridgeAuctionState::ObservationTensor(), and open_spiel::tiny_bridge::TinyBridgeGame2p::ObservationTensorShape().
kNumActions2p
int open_spiel::tiny_bridge::kNumActions2p = 1 + kNumBids inline constexpr
Definition at line 63 of file tiny_bridge.h.
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::InformationStateTensor(), open_spiel::tiny_bridge::TinyBridgeGame2p::InformationStateTensorShape(), MakeScores(), open_spiel::tiny_bridge::TinyBridgeGame2p::NumDistinctActions(), open_spiel::tiny_bridge::TinyBridgeAuctionState::ObservationTensor(), and open_spiel::tiny_bridge::TinyBridgeGame2p::ObservationTensorShape().
kNumActions4p
int open_spiel::tiny_bridge::kNumActions4p = 3 + kNumBids inline constexpr
Definition at line 64 of file tiny_bridge.h.
Referenced by open_spiel::tiny_bridge::TinyBridgeGame4p::NumDistinctActions().
kNumBids
int open_spiel::tiny_bridge::kNumBids = 6 inline constexpr
Definition at line 62 of file tiny_bridge.h.
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::InformationStateTensor(), open_spiel::tiny_bridge::TinyBridgeGame4p::InformationStateTensorShape(), open_spiel::tiny_bridge::TinyBridgeAuctionState::ObservationTensor(), and open_spiel::tiny_bridge::TinyBridgeGame4p::ObservationTensorShape().
kNumPrivates
int open_spiel::tiny_bridge::kNumPrivates = (kDeckSize * (kDeckSize - 1)) / 2 inline constexpr
Definition at line 74 of file tiny_bridge.h.
Referenced by MakeScores(), open_spiel::tiny_bridge::TinyBridgeGame2p::MaxChanceOutcomes(), and open_spiel::tiny_bridge::TinyBridgeGame4p::MaxChanceOutcomes().
kNumRanks
int open_spiel::tiny_bridge::kNumRanks = 4 inline constexpr
Definition at line 66 of file tiny_bridge.h.
kNumSeats
int open_spiel::tiny_bridge::kNumSeats = 4 inline constexpr
Definition at line 69 of file tiny_bridge.h.
Referenced by open_spiel::tiny_bridge::TinyBridgeAuctionState::ObservationTensor(), and open_spiel::tiny_bridge::TinyBridgePlayState::ToString().
kNumSuits
int open_spiel::tiny_bridge::kNumSuits = 2 inline constexpr
Definition at line 67 of file tiny_bridge.h.
kNumTricks
int open_spiel::tiny_bridge::kNumTricks = kDeckSize / kNumSeats inline constexpr
Definition at line 70 of file tiny_bridge.h.
Referenced by open_spiel::tiny_bridge::TinyBridgePlayGame::MaxUtility(), open_spiel::tiny_bridge::TinyBridgePlayGame::NewInitialState(), and Score_p0().