open spiel: open_spiel::skat Namespace Reference
open_spiel::skat Namespace Reference
Classes
class SkatGame
class SkatState
class Trick
Enumerations
enum SkatGameType {
kUnknownGame = 0 , kPass = 0 , kDiamondsTrump = 1 , kHeartsTrump = 2 ,
kSpadesTrump = 3 , kClubsTrump = 4 , kGrand = 5 , kNullGame = 6
}
enum Suit { kDiamonds = 0 , kHearts = 1 , kSpades = 2 , kClubs = 3 }
enum Rank {
kSeven = 0 , kEight = 1 , kNine = 2 , kQueen = 3 ,
kKing = 4 , kTen = 5 , kAce = 6 , kJack = 7
}
enum CardLocation {
kDeck = 0 , kHand0 = 1 , kHand1 = 2 , kHand2 = 3 ,
kSkat = 4 , kTrick = 5
}
enum Phase {
kDeal = 0 , kBidding = 1 , kDiscardCards = 2 , kPlay = 3 ,
kGameOver = 4
}
Functions
Suit CardSuit (int card)
Rank CardRank (int card)
std::string ToCardSymbol (int card)
std::string SuitToString (Suit suit)
std::string RankToString (Rank rank)
std::string PhaseToString (Phase phase)
int CardValue (int card)
std::string CardToString (int card)
std::string CardsToString (const std::vector< int > &cards)
std::string SkatGameTypeToString (SkatGameType trump_game)
CardLocation PlayerToLocation (int player)
template<typename It >
std::vector< int > GetCardsFromMultiHot (It multi_hot)
template<typename It >
int GetIntFromOneHot (It one_hot, int num_values)
Variables
const std::vector< std::string > kCardSymbols
constexpr int kNumRanks = 8
constexpr int kNumSuits = 4
constexpr int kNumCards = kNumRanks * kNumSuits
constexpr int kNumPlayers = 3
constexpr int kNumCardsInSkat = 2
constexpr int kNumGameTypes = 7
constexpr int kNumTricks = (kNumCards - kNumCardsInSkat) / kNumPlayers
constexpr int kBiddingActionBase = kNumCards
constexpr int kNumBiddingActions = kNumGameTypes
constexpr int kNumActions = kNumCards + kNumBiddingActions
constexpr char kEmptyCardSymbol [] = "ðŸ‚ "
constexpr int kObservationTensorSize
Enumeration Type Documentation
CardLocation
enum open_spiel::skat::CardLocation
Enumerator
kDeck
kHand0
kHand1
kHand2
kSkat
kTrick
Definition at line 93 of file skat.h.
                 {
  kDeck = 0,
  kHand0 = 1,
  kHand1 = 2,
  kHand2 = 3,
  kSkat = 4,
  kTrick = 5
};
Phase
enum open_spiel::skat::Phase
Enumerator
kDeal
kBidding
kDiscardCards
kPlay
kGameOver
Definition at line 101 of file skat.h.
           {
  kDeal = 0,
  kBidding = 1,
  kDiscardCards = 2,
  kPlay = 3,
  kGameOver = 4};
Rank
enum open_spiel::skat::Rank
Enumerator
kSeven
kEight
kNine
kQueen
kKing
kTen
kAce
kJack
Definition at line 83 of file skat.h.
          {
  kSeven = 0,
  kEight = 1,
  kNine = 2,
  kQueen = 3,
  kKing = 4,
  kTen = 5,
  kAce = 6,
  kJack = 7
};
SkatGameType
enum open_spiel::skat::SkatGameType
Enumerator
kUnknownGame
kPass
kDiamondsTrump
kHeartsTrump
kSpadesTrump
kClubsTrump
kGrand
kNullGame
Definition at line 72 of file skat.h.
                  {
  kUnknownGame = 0,
  kPass = 0,
  kDiamondsTrump = 1,
  kHeartsTrump = 2,
  kSpadesTrump = 3,
  kClubsTrump = 4,
  kGrand = 5,
  kNullGame = 6
};
Suit
enum open_spiel::skat::Suit
Enumerator
kDiamonds
kHearts
kSpades
kClubs
Definition at line 82 of file skat.h.
{kDiamonds = 0, kHearts = 1, kSpades = 2, kClubs = 3};
Function Documentation
CardRank()
Rank open_spiel::skat::CardRank (int card)
Definition at line 59 of file skat.cc.
{
  return static_cast<Rank>(card % 8);
}
Referenced by CardToString(), and CardValue().
CardsToString()
std::string open_spiel::skat::CardsToString (const std::vector< int > & cards)
Definition at line 153 of file skat.cc.
{
  std::string result = "";
  for (auto& card : cards) {
    absl::StrAppendFormat(&result, "%s ", ToCardSymbol(card));
  }
  return result;
}
References absl::StrAppendFormat(), and ToCardSymbol().
Referenced by open_spiel::skat::SkatState::ObservationString().
CardSuit()
Suit open_spiel::skat::CardSuit (int card)
Definition at line 55 of file skat.cc.
{
  return static_cast<Suit>(card / 8);
}
Referenced by CardToString().
CardToString()
std::string open_spiel::skat::CardToString (int card)
Definition at line 149 of file skat.cc.
{
  return SuitToString(CardSuit(card)) + RankToString(CardRank(card));
}
References CardRank(), CardSuit(), RankToString(), and SuitToString().
Referenced by open_spiel::skat::SkatState::ActionToString().
CardValue()
int open_spiel::skat::CardValue (int card)
Definition at line 132 of file skat.cc.
{
  switch (CardRank(card)) {
    case kQueen:
      return 3;
    case kKing:
      return 4;
    case kTen:
      return 10;
    case kAce:
      return 11;
    case kJack:
      return 2;
    default:
      return 0;  // Seven, eight and nine.
  }
}
References CardRank(), kAce, kJack, kKing, kQueen, and kTen.
Referenced by open_spiel::skat::Trick::Points().
GetCardsFromMultiHot()
template<typename It > std::vector< int > open_spiel::skat::GetCardsFromMultiHot (It multi_hot)
Definition at line 712 of file skat.cc.
{
  std::vector<int> cards;
  for (int i = 0; i < kNumCards; i++) {
    if (multi_hot[i]) cards.push_back(i);
  }
  return cards;
}
References i, and kNumCards.
Referenced by open_spiel::skat::SkatState::ObservationString().
GetIntFromOneHot()
template<typename It > int open_spiel::skat::GetIntFromOneHot (It one_hot, int num_values)
Definition at line 721 of file skat.cc.
{
  for (int i = 0; i < num_values; i++) {
    if (one_hot[i]) return i;
  }
  return -1;
}
References i.
Referenced by open_spiel::skat::SkatState::ObservationString().
PhaseToString()
std::string open_spiel::skat::PhaseToString (Phase phase)
Definition at line 115 of file skat.cc.
{
  switch (phase) {
    case kDeal:
      return "dealing";
    case kBidding:
      return "bidding";
    case kDiscardCards:
      return "discarding cards";
    case kPlay:
      return "playing";
    case kGameOver:
      return "game over";
    default:
      return "error";
  }
}
References kBidding, kDeal, kDiscardCards, kGameOver, and kPlay.
Referenced by open_spiel::skat::SkatState::ObservationString(), and open_spiel::skat::SkatState::ToString().
PlayerToLocation()
CardLocation open_spiel::skat::PlayerToLocation (int player)
Definition at line 183 of file skat.cc.
{
  switch (player) {
    case 0:
      return kHand0;
    case 1:
      return kHand1;
    case 2:
      return kHand2;
    default:
      return kDeck;
  }
}
References kDeck, kHand0, kHand1, kHand2, and player.
Referenced by open_spiel::skat::SkatState::ObservationTensor().
RankToString()
std::string open_spiel::skat::RankToString (Rank rank)
Definition at line 92 of file skat.cc.
{
  switch (rank) {
    case kSeven:
      return "7";
    case kEight:
      return "8";
    case kNine:
      return "9";
    case kQueen:
      return "Q";
    case kKing:
      return "K";
    case kTen:
      return "T";
    case kAce:
      return "A";
    case kJack:
      return "J";
    default:
      return "error";
  }
}
References kAce, kEight, kJack, kKing, kNine, kQueen, kSeven, kTen, and rank.
Referenced by CardToString().
SkatGameTypeToString()
std::string open_spiel::skat::SkatGameTypeToString (SkatGameType trump_game)
Definition at line 162 of file skat.cc.
{
  switch (trump_game) {
    case kUnknownGame:
      return "unknown/pass";
    case kDiamondsTrump:
      return "diamonds";
    case kHeartsTrump:
      return "hearts";
    case kSpadesTrump:
      return "spades";
    case kClubsTrump:
      return "clubs";
    case kGrand:
      return "grand";
    case kNullGame:
      return "null";
    default:
      return "error";
  }
}
References kClubsTrump, kDiamondsTrump, kGrand, kHeartsTrump, kNullGame, kSpadesTrump, and kUnknownGame.
Referenced by open_spiel::skat::SkatState::ActionToString(), open_spiel::skat::SkatState::ObservationString(), and open_spiel::skat::SkatState::ToString().
SuitToString()
std::string open_spiel::skat::SuitToString (Suit suit)
Definition at line 77 of file skat.cc.
{
  switch (suit) {
    case kDiamonds:
      return "D";
    case kHearts:
      return "H";
    case kSpades:
      return "S";
    case kClubs:
      return "C";
    default:
      return "error";
  }
}
References kClubs, kDiamonds, kHearts, and kSpades.
Referenced by CardToString().
ToCardSymbol()
std::string open_spiel::skat::ToCardSymbol (int card)
Definition at line 69 of file skat.cc.
{
  if (card >= 0) {
    return kCardSymbols.at(card);
  } else {
    return kEmptyCardSymbol;
  }
}
References kCardSymbols, and kEmptyCardSymbol.
Referenced by CardsToString(), open_spiel::skat::SkatState::ObservationString(), and open_spiel::skat::Trick::ToString().
Variable Documentation
kBiddingActionBase
int open_spiel::skat::kBiddingActionBase = kNumCards inline constexpr
Definition at line 54 of file skat.h.
Referenced by open_spiel::skat::SkatState::ActionToString(), and open_spiel::skat::SkatState::DoApplyAction().
kCardSymbols
const std::vector<std::string> open_spiel::skat::kCardSymbols
Initial value:
= {
  "ðŸƒ‡", "ðŸƒˆ", "ðŸƒ‰", "ðŸƒ", "ðŸƒŽ", "ðŸƒŠ", "ðŸƒ", "ðŸƒ‹",
  "ðŸ‚·", "ðŸ‚¸", "ðŸ‚¹", "ðŸ‚½", "ðŸ‚¾", "ðŸ‚º", "ðŸ‚±", "ðŸ‚»",
  "ðŸ‚§", "ðŸ‚¨", "ðŸ‚©", "ðŸ‚­", "ðŸ‚®", "ðŸ‚ª", "ðŸ‚¡", "ðŸ‚«",
  "ðŸƒ—", "ðŸƒ˜", "ðŸƒ™", "ðŸƒ", "ðŸƒž", "ðŸƒš", "ðŸƒ‘", "ðŸƒ›"}
Definition at line 62 of file skat.cc.
{
  "ðŸƒ‡", "ðŸƒˆ", "ðŸƒ‰", "ðŸƒ", "ðŸƒŽ", "ðŸƒŠ", "ðŸƒ", "ðŸƒ‹",
  "ðŸ‚·", "ðŸ‚¸", "ðŸ‚¹", "ðŸ‚½", "ðŸ‚¾", "ðŸ‚º", "ðŸ‚±", "ðŸ‚»",
  "ðŸ‚§", "ðŸ‚¨", "ðŸ‚©", "ðŸ‚­", "ðŸ‚®", "ðŸ‚ª", "ðŸ‚¡", "ðŸ‚«",
  "ðŸƒ—", "ðŸƒ˜", "ðŸƒ™", "ðŸƒ", "ðŸƒž", "ðŸƒš", "ðŸƒ‘", "ðŸƒ›"};
Referenced by ToCardSymbol().
kEmptyCardSymbol
char open_spiel::skat::kEmptyCardSymbol[] = "ðŸ‚ " inline constexpr
Definition at line 57 of file skat.h.
Referenced by ToCardSymbol(), and open_spiel::skat::Trick::ToString().
kNumActions
int open_spiel::skat::kNumActions = kNumCards + kNumBiddingActions inline constexpr
Definition at line 56 of file skat.h.
Referenced by open_spiel::skat::SkatGame::NumDistinctActions().
kNumBiddingActions
int open_spiel::skat::kNumBiddingActions = kNumGameTypes inline constexpr
Definition at line 55 of file skat.h.
kNumCards
int open_spiel::skat::kNumCards = kNumRanks * kNumSuits inline constexpr
Definition at line 49 of file skat.h.
Referenced by open_spiel::skat::SkatState::ChanceOutcomes(), GetCardsFromMultiHot(), open_spiel::skat::SkatGame::MaxChanceOutcomes(), open_spiel::skat::SkatGame::MaxGameLength(), open_spiel::skat::SkatState::ObservationString(), open_spiel::skat::SkatState::ObservationTensor(), and open_spiel::skat::Trick::ToString().
kNumCardsInSkat
int open_spiel::skat::kNumCardsInSkat = 2 inline constexpr
Definition at line 51 of file skat.h.
kNumGameTypes
int open_spiel::skat::kNumGameTypes = 7 inline constexpr
Definition at line 52 of file skat.h.
Referenced by open_spiel::skat::SkatState::ObservationString(), and open_spiel::skat::SkatState::ObservationTensor().
kNumPlayers
int open_spiel::skat::kNumPlayers = 3 inline constexpr
Definition at line 50 of file skat.h.
Referenced by open_spiel::skat::SkatGame::MaxGameLength(), open_spiel::skat::SkatGame::NumPlayers(), open_spiel::skat::SkatState::ObservationString(), open_spiel::skat::SkatState::ObservationTensor(), open_spiel::skat::Trick::PlayCard(), and open_spiel::skat::Trick::PlayerAtPosition().
kNumRanks
int open_spiel::skat::kNumRanks = 8 inline constexpr
Definition at line 47 of file skat.h.
kNumSuits
int open_spiel::skat::kNumSuits = 4 inline constexpr
Definition at line 48 of file skat.h.
kNumTricks
int open_spiel::skat::kNumTricks = (kNumCards - kNumCardsInSkat) / kNumPlayers inline constexpr
Definition at line 53 of file skat.h.
kObservationTensorSize
int open_spiel::skat::kObservationTensorSize inline constexpr
Initial value:
=
    kNumPlayers
    + 3
    + kNumCards
    + kNumPlayers * kNumGameTypes
    + kNumPlayers
    + kNumCards
    + kNumGameTypes
    + kNumPlayers
    + kNumPlayers * kNumCards
    + kNumPlayers
    + kNumPlayers * kNumCards
Definition at line 59 of file skat.h.
Referenced by open_spiel::skat::SkatGame::ObservationTensorShape().