open spiel: absl::container_internal::hashtable_debug_internal Namespace Reference
absl::container_internal::hashtable_debug_internal Namespace Reference
Classes
struct HashtableDebugAccess
struct HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >
Functions
template<typename T , typename = typename T::mapped_type>
auto GetKey (const typename T::value_type &pair, int) -> decltype(get< 0 >(pair))
template<typename T >
const T::key_type & GetKey (const typename T::key_type &key, char)
Function Documentation
GetKey() [1/2]
template<typename T > const T::key_type & absl::container_internal::hashtable_debug_internal::GetKey (const typename T::key_type & key, char)
Definition at line 42 of file hashtable_debug_hooks.h.
{
  return key;
}
References key.
GetKey() [2/2]
template<typename T , typename = typename T::mapped_type> auto absl::container_internal::hashtable_debug_internal::GetKey (const typename T::value_type & pair, int) -> decltype(get<0>(pair))
Definition at line 36 of file hashtable_debug_hooks.h.
{
  return get<0>(pair);
}
References absl::get(), and pair.
Referenced by absl::container_internal::GetHashtableDebugNumProbesHistogram(), and absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Container, Enabler >::GetNumProbes().