open spiel: absl::compare_internal Namespace Reference
absl::compare_internal Namespace Reference
Classes
struct Fail
struct OnlyLiteralZero
struct partial_ordering_base
struct strong_equality_base
struct strong_ordering_base
struct weak_equality_base
struct weak_ordering_base
Typedefs
using value_type = int8_t
Enumerations
enum class eq : value_type { equal = 0 , equivalent = equal , nonequal = 1 , nonequivalent = nonequal }
enum class ord : value_type { less = -1 , greater = 1 }
enum class ncmp : value_type { unordered = -127 }
Functions
template<typename BoolT , absl::enable_if_t< std::is_same< bool, BoolT >::value, int > = 0>
constexpr bool compare_result_as_less_than (const BoolT r)
constexpr bool compare_result_as_less_than (const absl::weak_ordering r)
template<typename Compare , typename K , typename LK >
constexpr bool do_less_than_comparison (const Compare &compare, const K &x, const LK &y)
template<typename Int , absl::enable_if_t< std::is_same< int, Int >::value, int > = 0>
constexpr absl::weak_ordering compare_result_as_ordering (const Int c)
constexpr absl::weak_ordering compare_result_as_ordering (const absl::weak_ordering c)
template<typename Compare , typename K , typename LK , absl::enable_if_t<!std::is_same< bool, absl::result_of_t< Compare(const K &, const LK &)> >::value, int > = 0>
constexpr absl::weak_ordering do_three_way_comparison (const Compare &compare, const K &x, const LK &y)
Typedef Documentation
value_type
using absl::compare_internal::value_type = int8_t
Definition at line 45 of file compare.h.
Enumeration Type Documentation
eq
enum class absl::compare_internal::eq : value_type strong
Enumerator
equal
equivalent
nonequal
nonequivalent
Definition at line 72 of file compare.h.
              : value_type {
  equal = 0,
  equivalent = equal,
  nonequal = 1,
  nonequivalent = nonequal,
};
ncmp
enum class absl::compare_internal::ncmp : value_type strong
Enumerator
unordered
Definition at line 81 of file compare.h.
: value_type { unordered = -127 };
ord
enum class absl::compare_internal::ord : value_type strong
Enumerator
less
greater
Definition at line 79 of file compare.h.
: value_type { less = -1, greater = 1 };
Function Documentation
compare_result_as_less_than() [1/2]
bool absl::compare_internal::compare_result_as_less_than (const absl::weak_ordering r) constexpr
Definition at line 550 of file compare.h.
{
  return r < 0;
}
References r.
compare_result_as_less_than() [2/2]
template<typename BoolT , absl::enable_if_t< std::is_same< bool, BoolT >::value, int > = 0> bool absl::compare_internal::compare_result_as_less_than (const BoolT r) constexpr
Definition at line 549 of file compare.h.
{ return r; }
References r.
Referenced by do_less_than_comparison(), and absl::ABSL_NAMESPACE_BEGIN::TEST().
compare_result_as_ordering() [1/2]
absl::weak_ordering absl::compare_internal::compare_result_as_ordering (const absl::weak_ordering c) constexpr
Definition at line 570 of file compare.h.
{
  return c;
}
References absl::c.
compare_result_as_ordering() [2/2]
template<typename Int , absl::enable_if_t< std::is_same< int, Int >::value, int > = 0> absl::weak_ordering absl::compare_internal::compare_result_as_ordering (const Int c) constexpr
Definition at line 565 of file compare.h.
{
  return c < 0 ? absl::weak_ordering::less
               : c == 0 ? absl::weak_ordering::equivalent
                        : absl::weak_ordering::greater;
}
References absl::c.
Referenced by do_three_way_comparison(), absl::container_internal::StringBtreeDefaultGreater::operator()(), absl::container_internal::StringBtreeDefaultGreater::operator()(), absl::container_internal::StringBtreeDefaultGreater::operator()(), absl::container_internal::StringBtreeDefaultGreater::operator()(), absl::container_internal::StringBtreeDefaultLess::operator()(), absl::container_internal::StringBtreeDefaultLess::operator()(), absl::container_internal::StringBtreeDefaultLess::operator()(), absl::container_internal::StringBtreeDefaultLess::operator()(), and absl::ABSL_NAMESPACE_BEGIN::TEST().
do_less_than_comparison()
template<typename Compare , typename K , typename LK > bool absl::compare_internal::do_less_than_comparison (const Compare & compare, const K & x, const LK & y) constexpr
Definition at line 555 of file compare.h.
{
  return compare_result_as_less_than(compare(x, y));
}
References compare_result_as_less_than(), absl::x, and y.
Referenced by absl::ABSL_NAMESPACE_BEGIN::TEST().
do_three_way_comparison()
template<typename Compare , typename K , typename LK , absl::enable_if_t<!std::is_same< bool, absl::result_of_t< Compare(const K &, const LK &)> >::value, int > = 0> absl::weak_ordering absl::compare_internal::do_three_way_comparison (const Compare & compare, const K & x, const LK & y) constexpr
Definition at line 580 of file compare.h.
{
  return compare_result_as_ordering(compare(x, y));
}
References compare_result_as_ordering(), absl::x, and y.
Referenced by absl::ABSL_NAMESPACE_BEGIN::TEST().