open spiel: open_spiel::chess Namespace Reference
open_spiel::chess Namespace Reference
Classes
class ChessBoard
class ChessGame
class ChessState
struct Move
struct Piece
Typedefs
template<std::size_t... Dims>
using ZobristTableU64 = chess_common::ZobristTable<uint64_t, Dims...>
using ObservationTable = std::array<bool, k2dMaxBoardSize>
Enumerations
enum class Color : int8_t { kBlack = 0 , kWhite = 1 , kEmpty = 2 }
enum class CastlingDirection { kLeft , kRight }
enum class PieceType : int8_t {
kEmpty = 0 , kKing = 1 , kQueen = 2 , kRook = 3 ,
kBishop = 4 , kKnight = 5 , kPawn = 6
}
enum PseudoLegalMoveSettings { kAcknowledgeEnemyPieces , kBreachEnemyPieces }
Functions
int EncodeMove (const Square &from_square, int destination_index, int board_size, int num_actions_destinations)
int8_t ReflectRank (Color to_play, int board_size, int8_t rank)
Color PlayerToColor (Player p)
Action MoveToAction (const Move &move, int board_size)
std::pair< Square, int > ActionToDestination (int action, int board_size, int num_actions_destinations)
Move ActionToMove (const Action &action, const ChessBoard &board)
constexpr int NumPlayers ()
constexpr double LossUtility ()
constexpr double DrawUtility ()
constexpr double WinUtility ()
constexpr int NumDistinctActions ()
constexpr int MaxGameLength ()
const std::vector< int > & ObservationTensorShape ()
int ColorToPlayer (Color c)
int OtherPlayer (Player player)
uint8_t GetField (Action action, int offset, int length)
void SetField (int offset, int length, uint8_t value, Action *action)
uint8_t SquareToIndex (const Square &square, int board_size)
Square IndexToSquare (uint8_t index, int board_size)
bool IsMoveCharacter (char c)
std::pair< std::string, std::string > SplitAnnotations (const std::string &move)
std::string ColorToString (Color c)
absl::optional< PieceType > PieceTypeFromChar (char c)
std::string PieceTypeToString (PieceType p, bool uppercase)
absl::optional< Square > SquareFromString (const std::string &s)
bool IsLongDiagonal (const chess::Square &from_sq, const chess::Square &to_sq, int board_size)
int ToInt (CastlingDirection direction)
ChessBoard MakeDefaultBoard ()
std::string DefaultFen (int board_size)
int ToInt (Color color)
Color OppColor (Color color)
std::ostream & operator<< (std::ostream &stream, Color c)
std::ostream & operator<< (std::ostream &stream, const Piece &p)
absl::optional< int8_t > ParseRank (char c)
absl::optional< int8_t > ParseFile (char c)
std::string RankToString (int8_t rank)
std::string FileToString (int8_t file)
std::ostream & operator<< (std::ostream &stream, const Move &m)
std::ostream & operator<< (std::ostream &stream, const ChessBoard &board)
std::ostream & operator<< (std::ostream &stream, const PieceType &pt)
Variables
constexpr std::array< PieceType, 3 > kUnderPromotionIndexToType
constexpr std::array< Offset, 3 > kUnderPromotionDirectionToOffset
constexpr int kNumUnderPromotions
constexpr int kNumActionDestinations = 73
constexpr std::array< Offset, 8 > kKnightOffsets
constexpr int kMaxBoardSize = 8
constexpr int kDefaultBoardSize = 8
constexpr int k2dMaxBoardSize = kMaxBoardSize * kMaxBoardSize
const std::string kDefaultStandardFEN
const std::string kDefaultSmallFEN = "r1kr/pppp/PPPP/R1KR w - - 0 1"
constexpr open_spiel::Action kPassAction = 0
const chess::Move kPassMove
Typedef Documentation
ObservationTable
using open_spiel::chess::ObservationTable = std::array<bool, k2dMaxBoardSize>
Definition at line 234 of file chess_board.h.
ZobristTableU64
template<std::size_t... Dims> using open_spiel::chess::ZobristTableU64 = chess_common::ZobristTable<uint64_t, Dims...>
Definition at line 40 of file chess_board.h.
Enumeration Type Documentation
CastlingDirection
enum class open_spiel::chess::CastlingDirection strong
Enumerator
kLeft
kRight
Definition at line 56 of file chess_board.h.
{ kLeft, kRight };
Color
enum class open_spiel::chess::Color : int8_t strong
Enumerator
kBlack
kWhite
kEmpty
Definition at line 42 of file chess_board.h.
: int8_t { kBlack = 0, kWhite = 1, kEmpty = 2 };
PieceType
enum class open_spiel::chess::PieceType : int8_t strong
Enumerator
kEmpty
kKing
kQueen
kRook
kBishop
kKnight
kPawn
Definition at line 60 of file chess_board.h.
                     : int8_t {
  kEmpty = 0,
  kKing = 1,
  kQueen = 2,
  kRook = 3,
  kBishop = 4,
  kKnight = 5,
  kPawn = 6
};
PseudoLegalMoveSettings
enum open_spiel::chess::PseudoLegalMoveSettings
Enumerator
kAcknowledgeEnemyPieces
kBreachEnemyPieces
Definition at line 237 of file chess_board.h.
{
  // Standard legal moves (do not allow to move past enemy pieces).
  kAcknowledgeEnemyPieces,
  // Pseudo-legal moves, where a piece can move anywhere (according to the rules
  // for that piece), except if it was blocked from doing so by other player's
  // pieces. This is used in games, where the player may not know the position
  // of an enemy piece (like Kriegspiel or RBC) and it can try to move past the
  // enemy (for example a rook can try to move the other side of the board, even
  // if it is in fact blocked by an unseen opponent's pawn).
  kBreachEnemyPieces,
};
Function Documentation
ActionToDestination()
std::pair< Square, int > open_spiel::chess::ActionToDestination (int action, int board_size, int num_actions_destinations)
Definition at line 225 of file chess.cc.
{
  const int xy = action / num_actions_destinations;
  SPIEL_CHECK_GE(xy, 0);
  SPIEL_CHECK_LT(xy, board_size * board_size);
  const int8_t x = xy / board_size;
  const int8_t y = xy % board_size;
  const int destination_index = action % num_actions_destinations;
  SPIEL_CHECK_GE(destination_index, 0);
  SPIEL_CHECK_LT(destination_index, num_actions_destinations);
  return {Square{x, y}, destination_index};
}
References action, SPIEL_CHECK_GE, SPIEL_CHECK_LT, x, xy, and y.
Referenced by ActionToMove().
ActionToMove()
Move open_spiel::chess::ActionToMove (const Action & action, const ChessBoard & board)
Definition at line 238 of file chess.cc.
{
  SPIEL_CHECK_GE(action, 0);
  SPIEL_CHECK_LT(action, NumDistinctActions());
  // Some chess variants (e.g. RBC) allow pass moves.
  if (board.AllowPassMove() && action == kPassAction) {
    return kPassMove;
  }
  // The encoded action represents an action encoded from color's perspective.
  Color color = board.ToPlay();
  int board_size = board.BoardSize();
  PieceType promotion_type = PieceType::kEmpty;
  bool is_castling = false;
  auto [from_square, destination_index] =
      ActionToDestination(action, kMaxBoardSize, kNumActionDestinations);
  SPIEL_CHECK_LT(destination_index, kNumActionDestinations);
  bool is_under_promotion = destination_index < kNumUnderPromotions;
  Offset offset;
  if (is_under_promotion) {
    int promotion_index = destination_index / 3;
    int direction_index = destination_index % 3;
    promotion_type = kUnderPromotionIndexToType[promotion_index];
    offset = kUnderPromotionDirectionToOffset[direction_index];
  } else {
    destination_index -= kNumUnderPromotions;
    offset = DestinationIndexToOffset(destination_index, kKnightOffsets,
                                      kMaxBoardSize);
  }
  Square to_square = from_square + offset;
  from_square.y = ReflectRank(color, board_size, from_square.y);
  to_square.y = ReflectRank(color, board_size, to_square.y);
  // This uses the current state to infer the piece type.
  Piece piece = {board.ToPlay(), board.at(from_square).type};
  // Check for queen promotion.
  if (!is_under_promotion && piece.type == PieceType::kPawn &&
      ReflectRank(color, board_size, from_square.y) == board_size - 2 &&
      ReflectRank(color, board_size, to_square.y) == board_size - 1) {
    promotion_type = PieceType::kQueen;
  }
  // Check for castling which is defined here just as king moves horizontally
  // by 2 spaces.
  // TODO(b/149092677): Chess no longer supports chess960. Distinguish between
  // left/right castle.
  if (piece.type == PieceType::kKing && std::abs(offset.x_offset) == 2) {
    is_castling = true;
  }
  Move move(from_square, to_square, piece, promotion_type, is_castling);
  return move;
}
References action, ActionToDestination(), open_spiel::chess::ChessBoard::AllowPassMove(), open_spiel::chess::ChessBoard::at(), open_spiel::chess::ChessBoard::BoardSize(), kEmpty, kKing, kKnightOffsets, kMaxBoardSize, kNumActionDestinations, kNumUnderPromotions, kPassAction, kPassMove, kPawn, kQueen, kUnderPromotionDirectionToOffset, kUnderPromotionIndexToType, NumDistinctActions(), ReflectRank(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, open_spiel::chess::ChessBoard::ToPlay(), open_spiel::chess::Piece::type, open_spiel::chess_common::Offset::x_offset, and open_spiel::chess_common::Square::y.
Referenced by open_spiel::chess::ChessState::ActionToString(), open_spiel::chess::ChessState::DoApplyAction(), and open_spiel::uci::UCIBot::InformAction().
ColorToPlayer()
int open_spiel::chess::ColorToPlayer (Color c) inline
Definition at line 60 of file chess.h.
{
  if (c == Color::kBlack) {
    return 0;
  } else if (c == Color::kWhite) {
    return 1;
  } else {
    SpielFatalError("Unknown color");
  }
}
References kBlack, kWhite, and open_spiel::SpielFatalError().
Referenced by open_spiel::chess::ChessState::CurrentPlayer(), and open_spiel::chess::ChessState::ObservationTensor().
ColorToString()
std::string open_spiel::chess::ColorToString (Color c)
Definition at line 53 of file chess_board.cc.
{
  switch (c) {
    case Color::kBlack:
      return "black";
    case Color::kWhite:
      return "white";
    case Color::kEmpty:
      return "empty";
    default:
      SpielFatalError(absl::StrCat("Unknown color: ", c));
      return "This will never return.";
  }
}
References kBlack, kEmpty, kWhite, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by operator<<(), open_spiel::kriegspiel::KriegspielUmpireMessage::ToString(), open_spiel::dark_chess::DarkChessObserver::WriteTensor(), open_spiel::kriegspiel::KriegspielObserver::WriteTensor(), and open_spiel::rbc::RbcObserver::WriteTensor().
DefaultFen()
std::string open_spiel::chess::DefaultFen (int board_size)
Definition at line 1869 of file chess_board.cc.
{
  if (board_size == 8)
    return chess::kDefaultStandardFEN;
  else if (board_size == 4)
    return chess::kDefaultSmallFEN;
  else
    SpielFatalError(
        "Only board sizes 4 and 8 have their default chessboards. "
        "For other sizes, you have to pass your own FEN.");
}
References kDefaultSmallFEN, kDefaultStandardFEN, and open_spiel::SpielFatalError().
DrawUtility()
double open_spiel::chess::DrawUtility () inline constexpr
Definition at line 41 of file chess.h.
{ return 0; }
Referenced by open_spiel::chess::ChessGame::UtilitySum().
EncodeMove()
int open_spiel::chess::EncodeMove (const Square & from_square, int destination_index, int board_size, int num_actions_destinations)
Definition at line 141 of file chess.cc.
{
  return (from_square.x * board_size + from_square.y) *
             num_actions_destinations +
         destination_index;
}
References open_spiel::chess_common::Square::x, and open_spiel::chess_common::Square::y.
Referenced by MoveToAction().
FileToString()
std::string open_spiel::chess::FileToString (int8_t file) inline
Definition at line 124 of file chess_board.h.
{
  return std::string(1, 'a' + file);
}
Referenced by open_spiel::chess::ChessBoard::DebugString(), and open_spiel::chess::Move::ToSAN().
GetField()
uint8_t open_spiel::chess::GetField (Action action, int offset, int length) inline
Definition at line 81 of file chess.h.
{
  return (action >> offset) & ((1ULL << length) - 1);
}
References action.
IndexToSquare()
Square open_spiel::chess::IndexToSquare (uint8_t index, int board_size) inline
Definition at line 101 of file chess.h.
{
  return Square{static_cast<int8_t>(index % board_size),
                static_cast<int8_t>(index / board_size)};
}
Referenced by open_spiel::rbc::RbcState::ActionToString().
IsLongDiagonal()
bool open_spiel::chess::IsLongDiagonal (const chess::Square & from_sq, const chess::Square & to_sq, int board_size)
Definition at line 174 of file chess_board.cc.
{
  if (from_sq == to_sq) {
    return false;
  }
  int half_board_size = board_size / 2;
  if ((to_sq.y < half_board_size && to_sq.x < half_board_size) ||
      (to_sq.y >= half_board_size && to_sq.x >= half_board_size)) {
    return from_sq.y - to_sq.y == from_sq.x - to_sq.x;
  } else {
    return from_sq.y - to_sq.y == to_sq.x - from_sq.x;
  }
}
References open_spiel::chess_common::Square::x, and open_spiel::chess_common::Square::y.
Referenced by open_spiel::kriegspiel::GetCheckType().
IsMoveCharacter()
bool open_spiel::chess::IsMoveCharacter (char c)
Definition at line 39 of file chess_board.cc.
{
  return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
         (c >= '0' && c <= '9');
}
Referenced by SplitAnnotations().
LossUtility()
double open_spiel::chess::LossUtility () inline constexpr
Definition at line 40 of file chess.h.
{ return -1; }
Referenced by open_spiel::chess::ChessGame::MinUtility().
MakeDefaultBoard()
ChessBoard open_spiel::chess::MakeDefaultBoard ()
Definition at line 1863 of file chess_board.cc.
{
  auto maybe_board = ChessBoard::BoardFromFEN(kDefaultStandardFEN);
  SPIEL_CHECK_TRUE(maybe_board);
  return *maybe_board;
}
References open_spiel::chess::ChessBoard::BoardFromFEN(), kDefaultStandardFEN, and SPIEL_CHECK_TRUE.
MaxGameLength()
int open_spiel::chess::MaxGameLength () inline constexpr
Definition at line 47 of file chess.h.
{ return 17695; }
Referenced by open_spiel::chess::ChessGame::MaxGameLength(), open_spiel::dark_chess::DarkChessGame::MaxGameLength(), and open_spiel::rbc::RbcGame::MaxGameLength().
MoveToAction()
Action open_spiel::chess::MoveToAction (const Move & move, int board_size)
Definition at line 157 of file chess.cc.
{
  // Special-case for pass move.
  if (move == kPassMove) return kPassAction;
  Color color = move.piece.color;
  // We rotate the move to be from player p's perspective.
  Move player_move(move);
  // Rotate move to be from player p's perspective.
  player_move.from.y = ReflectRank(color, board_size, player_move.from.y);
  player_move.to.y = ReflectRank(color, board_size, player_move.to.y);
  // For each starting square, we enumerate 73 actions:
  // - 9 possible underpromotions
  // - 56 queen moves
  // - 8 knight moves
  // In total, this results in 64 * 73 = 4672 indices.
  // This is the union of all possible moves, by reducing this to the number of
  // moves actually available from each starting square this could still be
  // reduced a little to 1816 indices.
  int starting_index =
      EncodeMove(player_move.from, 0, kMaxBoardSize, kNumActionDestinations);
  int8_t x_diff = player_move.to.x - player_move.from.x;
  int8_t y_diff = player_move.to.y - player_move.from.y;
  Offset offset{x_diff, y_diff};
  bool is_under_promotion = move.promotion_type != PieceType::kEmpty &&
                            move.promotion_type != PieceType::kQueen;
  if (is_under_promotion) {
    // We have to indicate underpromotions as special moves, because in terms of
    // from/to they are identical to queen promotions.
    // For a given starting square, an underpromotion can have 3 possible
    // destination squares (straight, left diagonal, right diagonal) and 3
    // possible piece types.
    SPIEL_CHECK_EQ(move.piece.type, PieceType::kPawn);
    SPIEL_CHECK_TRUE((move.piece.color == color &&
                      player_move.from.y == board_size - 2 &&
                      player_move.to.y == board_size - 1) ||
                     (move.piece.color == OppColor(color) &&
                      player_move.from.y == 1 && player_move.to.y == 0));
    int promotion_index;
    {
      auto itr = absl::c_find(kUnderPromotionIndexToType, move.promotion_type);
      SPIEL_CHECK_TRUE(itr != kUnderPromotionIndexToType.end());
      promotion_index = std::distance(kUnderPromotionIndexToType.begin(), itr);
    }
    int direction_index;
    {
      auto itr = absl::c_find_if(
          kUnderPromotionDirectionToOffset,
          [offset](Offset o) { return o.x_offset == offset.x_offset; });
      SPIEL_CHECK_TRUE(itr != kUnderPromotionDirectionToOffset.end());
      direction_index =
          std::distance(kUnderPromotionDirectionToOffset.begin(), itr);
    }
    return starting_index +
           kUnderPromotionDirectionToOffset.size() * promotion_index +
           direction_index;
  } else {
    // For the normal moves, we simply encode starting and destination square.
    int destination_index =
        OffsetToDestinationIndex(offset, kKnightOffsets, kMaxBoardSize);
    SPIEL_CHECK_TRUE(destination_index >= 0 && destination_index < 64);
    return starting_index + kNumUnderPromotions + destination_index;
  }
}
References absl::c_find(), absl::c_find_if(), EncodeMove(), open_spiel::chess::Move::from, kEmpty, kKnightOffsets, kMaxBoardSize, kNumActionDestinations, kNumUnderPromotions, kPassAction, kPassMove, kPawn, kQueen, kUnderPromotionDirectionToOffset, kUnderPromotionIndexToType, o, OppColor(), ReflectRank(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, open_spiel::chess::Move::to, open_spiel::chess_common::Square::x, and open_spiel::chess_common::Square::y.
Referenced by open_spiel::chess::ChessState::ParseMoveToAction(), and open_spiel::uci::UCIBot::Step().
NumDistinctActions()
int open_spiel::chess::NumDistinctActions () inline constexpr
Definition at line 44 of file chess.h.
{ return 4672; }
Referenced by ActionToMove(), open_spiel::chess::ChessGame::NumDistinctActions(), open_spiel::dark_chess::DarkChessGame::NumDistinctActions(), and open_spiel::rbc::RbcGame::NumDistinctActions().
NumPlayers()
int open_spiel::chess::NumPlayers () inline constexpr
Definition at line 39 of file chess.h.
{ return 2; }
Referenced by open_spiel::chess::ChessGame::NumPlayers(), open_spiel::dark_chess::DarkChessGame::NumPlayers(), open_spiel::rbc::RbcGame::NumPlayers(), open_spiel::dark_chess::DarkChessObserver::WriteTensor(), open_spiel::kriegspiel::KriegspielObserver::WriteTensor(), and open_spiel::rbc::RbcObserver::WriteTensor().
ObservationTensorShape()
const std::vector< int > & open_spiel::chess::ObservationTensorShape () inline
Definition at line 49 of file chess.h.
{
  static std::vector<int> shape{
      13 /* piece types * colours + empty */ + 1 /* repetition count */ +
          1 /* side to move */ + 1 /* irreversible move counter */ +
          4 /* castling rights */,
      kMaxBoardSize, kMaxBoardSize};
  return shape;
}
References kMaxBoardSize.
Referenced by open_spiel::chess::ChessGame::ObservationTensorShape().
operator<<() [1/5]
std::ostream & open_spiel::chess::operator<< (std::ostream & stream, Color c) inline
Definition at line 52 of file chess_board.h.
{
  return stream << ColorToString(c);
}
References ColorToString().
operator<<() [2/5]
std::ostream & open_spiel::chess::operator<< (std::ostream & stream, const ChessBoard & board) inline
Definition at line 560 of file chess_board.h.
{
  return stream << board.DebugString();
}
References open_spiel::chess::ChessBoard::DebugString().
operator<<() [3/5]
std::ostream & open_spiel::chess::operator<< (std::ostream & stream, const Move & m) inline
Definition at line 219 of file chess_board.h.
{
  return stream << m.ToString();
}
References open_spiel::chess::Move::ToString().
operator<<() [4/5]
std::ostream & open_spiel::chess::operator<< (std::ostream & stream, const Piece & p) inline
Definition at line 104 of file chess_board.h.
{
  return stream << p.ToString();
}
operator<<() [5/5]
std::ostream & open_spiel::chess::operator<< (std::ostream & stream, const PieceType & pt) inline
Definition at line 564 of file chess_board.h.
{
  return stream << PieceTypeToString(pt);
}
References PieceTypeToString().
OppColor()
Color open_spiel::chess::OppColor (Color color) inline
Definition at line 46 of file chess_board.h.
{
  return color == Color::kWhite ? Color::kBlack : Color::kWhite;
}
References kBlack, and kWhite.
Referenced by open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::rbc::RbcState::DoApplyAction(), MoveToAction(), and open_spiel::chess::ChessBoard::UnderAttack().
OtherPlayer()
int open_spiel::chess::OtherPlayer (Player player) inline
Definition at line 70 of file chess.h.
{ return player == Player{0} ? 1 : 0; }
References player.
ParseFile()
absl::optional< int8_t > open_spiel::chess::ParseFile (char c) inline
Definition at line 113 of file chess_board.h.
{
  if (c >= 'a' && c <= 'h') return c - 'a';
  return absl::nullopt;
}
Referenced by open_spiel::chess::ChessBoard::ParseSANMove(), and SquareFromString().
ParseRank()
absl::optional< int8_t > open_spiel::chess::ParseRank (char c) inline
Definition at line 108 of file chess_board.h.
{
  if (c >= '1' && c <= '8') return c - '1';
  return absl::nullopt;
}
Referenced by open_spiel::chess::ChessBoard::ParseSANMove(), and SquareFromString().
PieceTypeFromChar()
absl::optional< PieceType > open_spiel::chess::PieceTypeFromChar (char c)
Definition at line 67 of file chess_board.cc.
{
  switch (toupper(c)) {
    case 'P':
      return PieceType::kPawn;
    case 'N':
      return PieceType::kKnight;
    case 'B':
      return PieceType::kBishop;
    case 'R':
      return PieceType::kRook;
    case 'Q':
      return PieceType::kQueen;
    case 'K':
      return PieceType::kKing;
    default:
      std::cerr << "Invalid piece type: " << c << std::endl;
      return absl::nullopt;
  }
}
References kBishop, kKing, kKnight, kPawn, kQueen, and kRook.
Referenced by open_spiel::chess::ChessBoard::BoardFromFEN(), open_spiel::chess::ChessBoard::ParseLANMove(), and open_spiel::chess::ChessBoard::ParseSANMove().
PieceTypeToString()
std::string open_spiel::chess::PieceTypeToString (PieceType p, bool uppercase)
Definition at line 87 of file chess_board.cc.
{
  switch (p) {
    case PieceType::kEmpty:
      return " ";
    case PieceType::kPawn:
      return uppercase ? "P" : "p";
    case PieceType::kKnight:
      return uppercase ? "N" : "n";
    case PieceType::kBishop:
      return uppercase ? "B" : "b";
    case PieceType::kRook:
      return uppercase ? "R" : "r";
    case PieceType::kQueen:
      return uppercase ? "Q" : "q";
    case PieceType::kKing:
      return uppercase ? "K" : "k";
    default:
      SpielFatalError("Unknown piece.");
      return "This will never return.";
  }
}
References kBishop, kEmpty, kKing, kKnight, kPawn, kQueen, kRook, and open_spiel::SpielFatalError().
Referenced by operator<<(), open_spiel::chess::Move::ToLAN(), open_spiel::chess::Move::ToSAN(), open_spiel::chess::Move::ToString(), and open_spiel::chess::Piece::ToString().
PlayerToColor()
Color open_spiel::chess::PlayerToColor (Player p)
Definition at line 152 of file chess.cc.
{
  SPIEL_CHECK_NE(p, kInvalidPlayer);
  return static_cast<Color>(p);
}
References open_spiel::kInvalidPlayer, and SPIEL_CHECK_NE.
Referenced by open_spiel::dark_chess::DarkChessObserver::StringFrom(), open_spiel::dark_chess::DarkChessObserver::WriteTensor(), open_spiel::kriegspiel::KriegspielObserver::WriteTensor(), and open_spiel::rbc::RbcObserver::WriteTensor().
RankToString()
std::string open_spiel::chess::RankToString (int8_t rank) inline
Definition at line 119 of file chess_board.h.
{
  return std::string(1, '1' + rank);
}
References rank.
Referenced by open_spiel::chess::ChessBoard::DebugString(), and open_spiel::chess::Move::ToSAN().
ReflectRank()
int8_t open_spiel::chess::ReflectRank (Color to_play, int board_size, int8_t rank)
Definition at line 148 of file chess.cc.
{
  return to_play == Color::kBlack ? board_size - 1 - rank : rank;
}
References kBlack, and rank.
Referenced by ActionToMove(), and MoveToAction().
SetField()
void open_spiel::chess::SetField (int offset, int length, uint8_t value, Action * action) inline
Definition at line 87 of file chess.h.
{
  uint32_t mask = ((1ULL << length) - 1) << offset;
  *action &= ~mask;
  *action |= static_cast<Action>(value) << offset;
}
References action, and value.
SplitAnnotations()
std::pair< std::string, std::string > open_spiel::chess::SplitAnnotations (const std::string & move)
Definition at line 44 of file chess_board.cc.
{
  for (int i = 0; i < move.size(); ++i) {
    if (!IsMoveCharacter(move[i])) {
      return {move.substr(0, i), std::string(absl::ClippedSubstr(move, i))};
    }
  }
  return {move, ""};
}
References absl::ClippedSubstr(), i, and IsMoveCharacter().
Referenced by open_spiel::chess::ChessBoard::ParseSANMove().
SquareFromString()
absl::optional< Square > open_spiel::chess::SquareFromString (const std::string & s)
Definition at line 165 of file chess_board.cc.
{
  if (s.size() != 2) return kInvalidSquare;
  auto file = ParseFile(s[0]);
  auto rank = ParseRank(s[1]);
  if (file && rank) return Square{*file, *rank};
  return absl::nullopt;
}
References ParseFile(), ParseRank(), and rank.
Referenced by open_spiel::chess::ChessBoard::BoardFromFEN(), and open_spiel::chess::ChessBoard::ParseLANMove().
SquareToIndex()
uint8_t open_spiel::chess::SquareToIndex (const Square & square, int board_size) inline
Definition at line 95 of file chess.h.
{
  return square.y * board_size + square.x;
}
References open_spiel::chess_common::Square::x, and open_spiel::chess_common::Square::y.
ToInt() [1/2]
int open_spiel::chess::ToInt (CastlingDirection direction)
Definition at line 1762 of file chess_board.cc.
{
  switch (direction) {
    case CastlingDirection::kLeft:
      return 0;
    case CastlingDirection::kRight:
      return 1;
    default:
      SpielFatalError("Unknown direction.");
      return 0;
  }
}
References kLeft, kRight, and open_spiel::SpielFatalError().
Referenced by open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::chess::ChessBoard::MaybeCastlingRookSquare(), open_spiel::chess::ChessBoard::SetCastlingRight(), and open_spiel::chess::ChessBoard::SetToPlay().
ToInt() [2/2]
int open_spiel::chess::ToInt (Color color) inline
Definition at line 44 of file chess_board.h.
{ return color == Color::kWhite ? 1 : 0; }
References kWhite.
WinUtility()
double open_spiel::chess::WinUtility () inline constexpr
Definition at line 42 of file chess.h.
{ return 1; }
Referenced by open_spiel::chess::ChessGame::MaxUtility().
Variable Documentation
k2dMaxBoardSize
int open_spiel::chess::k2dMaxBoardSize = kMaxBoardSize * kMaxBoardSize inline constexpr
Definition at line 229 of file chess_board.h.
kDefaultBoardSize
int open_spiel::chess::kDefaultBoardSize = 8 inline constexpr
Definition at line 228 of file chess_board.h.
kDefaultSmallFEN
const std::string open_spiel::chess::kDefaultSmallFEN = "r1kr/pppp/PPPP/R1KR w - - 0 1" inline
Definition at line 232 of file chess_board.h.
Referenced by DefaultFen().
kDefaultStandardFEN
const std::string open_spiel::chess::kDefaultStandardFEN inline
Initial value:
=
    "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
Definition at line 230 of file chess_board.h.
Referenced by DefaultFen(), and MakeDefaultBoard().
kKnightOffsets
std::array<Offset, 8> open_spiel::chess::kKnightOffsets inline constexpr
Initial value:
= {
    {{-2, -1}, {-2, 1}, {-1, -2}, {-1, 2}, {2, -1}, {2, 1}, {1, -2}, {1, 2}}}
Definition at line 129 of file chess_board.h.
{
    {{-2, -1}, {-2, 1}, {-1, -2}, {-1, 2}, {2, -1}, {2, 1}, {1, -2}, {1, 2}}};
Referenced by ActionToMove(), and MoveToAction().
kMaxBoardSize
int open_spiel::chess::kMaxBoardSize = 8 inline constexpr
Definition at line 227 of file chess_board.h.
Referenced by ActionToMove(), MoveToAction(), and ObservationTensorShape().
kNumActionDestinations
int open_spiel::chess::kNumActionDestinations = 73 inline constexpr
Definition at line 109 of file chess.h.
Referenced by ActionToMove(), and MoveToAction().
kNumUnderPromotions
int open_spiel::chess::kNumUnderPromotions inline constexpr
Initial value:
=
    kUnderPromotionIndexToType.size() * kUnderPromotionDirectionToOffset.size()
Definition at line 76 of file chess.h.
Referenced by ActionToMove(), and MoveToAction().
kPassAction
open_spiel::Action open_spiel::chess::kPassAction = 0 inline constexpr
Definition at line 250 of file chess_board.h.
Referenced by ActionToMove(), open_spiel::rbc::RbcState::ActionToString(), and MoveToAction().
kPassMove
const chess::Move open_spiel::chess::kPassMove inline
Initial value:
=
    Move(Square{-1, -1}, Square{-1, -1},
         Piece{Color::kEmpty, PieceType::kEmpty})
Definition at line 251 of file chess_board.h.
Referenced by ActionToMove(), open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::rbc::RbcState::DoApplyAction(), open_spiel::chess::ChessBoard::GeneratePseudoLegalMoves(), open_spiel::chess::ChessBoard::IsBreachingMove(), and MoveToAction().
kUnderPromotionDirectionToOffset
std::array<Offset, 3> open_spiel::chess::kUnderPromotionDirectionToOffset inline constexpr
Initial value:
= {
    {{0, 1}, {1, 1}, {-1, 1}}}
Definition at line 74 of file chess.h.
{
    {{0, 1}, {1, 1}, {-1, 1}}};
Referenced by ActionToMove(), and MoveToAction().
kUnderPromotionIndexToType
std::array<PieceType, 3> open_spiel::chess::kUnderPromotionIndexToType inline constexpr
Initial value:
= {
    PieceType::kRook, PieceType::kBishop, PieceType::kKnight}
Definition at line 72 of file chess.h.
{
    PieceType::kRook, PieceType::kBishop, PieceType::kKnight};
Referenced by ActionToMove(), and MoveToAction().