open spiel: absl::time_internal Namespace Reference
absl::time_internal Namespace Reference
Namespaces
namespace cctz
namespace cctz_extension
Classes
struct day_tag
struct hour_tag
struct minute_tag
struct month_tag
struct second_tag
struct year_tag
Typedefs
template<typename T >
using EnableIfIntegral
template<typename T >
using EnableIfFloat
Functions
std::ostream & operator<< (std::ostream &os, CivilYear y)
bool AbslParseFlag (string_view s, CivilSecond *c, std::string *)
std::string AbslUnparseFlag (CivilSecond c)
int64_t IDivDuration (bool satq, const Duration num, const Duration den, Duration *rem)
TimeZone LoadTimeZone (const std::string &name)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Time FromUnixDuration (Duration d)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration ToUnixDuration (Time t)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr int64_t GetRepHi (Duration d)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr uint32_t GetRepLo (Duration d)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration MakeDuration (int64_t hi, uint32_t lo)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration MakeDuration (int64_t hi, int64_t lo)
ABSL_ATTRIBUTE_CONST_FUNCTION Duration MakePosDoubleDuration (double n)
template<std::intmax_t N>
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration FromInt64 (int64_t v, std::ratio< 1, N >)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration FromInt64 (int64_t v, std::ratio< 60 >)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration FromInt64 (int64_t v, std::ratio< 3600 >)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration MakeNormalizedDuration (int64_t sec, int64_t ticks)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr bool IsInfiniteDuration (Duration d)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration OppositeInfinity (Duration d)
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr int64_t NegateAndSubtractOne (int64_t n)
template<typename T >
constexpr auto IsValidRep64 (int) -> decltype(int64_t{std::declval< T >()}==0)
template<typename T >
constexpr auto IsValidRep64 (char) -> bool
template<typename Rep , typename Period >
ABSL_ATTRIBUTE_PURE_FUNCTION constexpr Duration FromChrono (const std::chrono::duration< Rep, Period > &d)
template<typename Ratio >
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t ToInt64 (Duration d, Ratio)
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t ToInt64 (Duration d, std::nano)
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t ToInt64 (Duration d, std::micro)
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t ToInt64 (Duration d, std::milli)
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t ToInt64 (Duration d, std::ratio< 1 >)
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t ToInt64 (Duration d, std::ratio< 60 >)
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t ToInt64 (Duration d, std::ratio< 3600 >)
template<typename T >
ABSL_ATTRIBUTE_CONST_FUNCTION T ToChronoDuration (Duration d)
Variables
constexpr int64_t kTicksPerNanosecond = 4
constexpr int64_t kTicksPerSecond = 1000 * 1000 * 1000 * kTicksPerNanosecond
Typedef Documentation
EnableIfFloat
template<typename T > using absl::time_internal::EnableIfFloat
Initial value:
    typename std::enable_if<std::is_floating_point<T>::value, int>::type
Definition at line 123 of file time.h.
EnableIfIntegral
template<typename T > using absl::time_internal::EnableIfIntegral
Initial value:
 typename std::enable_if<
    std::is_integral<T>::value || std::is_enum<T>::value, int>::type
Definition at line 120 of file time.h.
Function Documentation
AbslParseFlag()
bool absl::time_internal::AbslParseFlag (string_view s, CivilSecond * c, std::string *)
Definition at line 171 of file civil_time.cc.
{
  return ParseLenientCivilTime(s, c);
}
References absl::c, absl::ParseLenientCivilTime(), and absl::s.
AbslUnparseFlag()
std::string absl::time_internal::AbslUnparseFlag (CivilSecond c)
Definition at line 189 of file civil_time.cc.
{ return FormatCivilTime(c); }
References absl::c, and absl::FormatCivilTime().
FromChrono()
template<typename Rep , typename Period > ABSL_ATTRIBUTE_PURE_FUNCTION constexpr Duration absl::time_internal::FromChrono (const std::chrono::duration< Rep, Period > & d) constexpr
Definition at line 1569 of file time.h.
{
  static_assert(IsValidRep64<Rep>(0), "duration::rep is invalid");
  return FromInt64(int64_t{d.count()}, Period{});
}
References absl::d, FromInt64(), and IsValidRep64().
Referenced by absl::FromChrono(), absl::FromChrono(), absl::FromChrono(), absl::FromChrono(), absl::FromChrono(), absl::FromChrono(), and absl::FromChrono().
FromInt64() [1/3]
template<std::intmax_t N> ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration absl::time_internal::FromInt64 (int64_t v, std::ratio< 1, N >) constexpr
Definition at line 1534 of file time.h.
{
  static_assert(0 < N && N <= 1000 * 1000 * 1000, "Unsupported ratio");
  // Subsecond ratios cannot overflow.
  return MakeNormalizedDuration(
      v / N, v % N * kTicksPerNanosecond * 1000 * 1000 * 1000 / N);
}
References MakeNormalizedDuration(), and absl::v.
Referenced by FromChrono(), absl::Hours(), absl::Microseconds(), absl::Milliseconds(), absl::Minutes(), absl::Nanoseconds(), and absl::Seconds().
FromInt64() [2/3]
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration absl::time_internal::FromInt64 (int64_t v, std::ratio< 3600 >) constexpr
Definition at line 1548 of file time.h.
{
  return (v <= (std::numeric_limits<int64_t>::max)() / 3600 &&
          v >= (std::numeric_limits<int64_t>::min)() / 3600)
             ? MakeDuration(v * 3600)
             : v > 0 ? InfiniteDuration() : -InfiniteDuration();
}
References absl::InfiniteDuration(), MakeDuration(), and absl::v.
FromInt64() [3/3]
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration absl::time_internal::FromInt64 (int64_t v, std::ratio< 60 >) constexpr
Definition at line 1541 of file time.h.
{
  return (v <= (std::numeric_limits<int64_t>::max)() / 60 &&
          v >= (std::numeric_limits<int64_t>::min)() / 60)
             ? MakeDuration(v * 60)
             : v > 0 ? InfiniteDuration() : -InfiniteDuration();
}
References absl::InfiniteDuration(), MakeDuration(), and absl::v.
FromUnixDuration()
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Time absl::time_internal::FromUnixDuration (Duration d) constexpr
Definition at line 1526 of file time.h.
{
  return Time(d);
}
References absl::d.
Referenced by absl::FromChrono(), absl::FromTimeT(), absl::FromUDate(), absl::FromUnixMicros(), absl::FromUnixMillis(), absl::FromUnixNanos(), absl::FromUnixSeconds(), absl::ABSL_NAMESPACE_BEGIN::MakeTimeWithOverflow(), absl::Now(), absl::TimeFromTimespec(), and absl::TimeFromTimeval().
GetRepHi()
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr int64_t absl::time_internal::GetRepHi (Duration d) constexpr
Definition at line 1493 of file time.h.
{
  return d.rep_hi_;
}
References absl::d.
Referenced by absl::TimeZone::At(), absl::FDivDuration(), absl::ABSL_NAMESPACE_BEGIN::IDivFastPath(), absl::Time::In(), absl::ABSL_NAMESPACE_BEGIN::MakeU128Ticks(), absl::operator-(), absl::operator<(), absl::operator==(), OppositeInfinity(), absl::ABSL_NAMESPACE_BEGIN::ScaleDouble(), absl::ABSL_NAMESPACE_BEGIN::ScaleFixed(), absl::ToInt64Hours(), absl::ToInt64Microseconds(), absl::ToInt64Milliseconds(), absl::ToInt64Minutes(), absl::ToInt64Nanoseconds(), absl::ToInt64Seconds(), absl::ToTimespec(), absl::ToTimespec(), absl::ToUnixMicros(), absl::ToUnixMillis(), absl::ToUnixNanos(), and absl::ToUnixSeconds().
GetRepLo()
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr uint32_t absl::time_internal::GetRepLo (Duration d) constexpr
Definition at line 1496 of file time.h.
{
  return d.rep_lo_;
}
References absl::d.
Referenced by absl::TimeZone::At(), absl::FDivDuration(), absl::ABSL_NAMESPACE_BEGIN::IDivFastPath(), absl::Time::In(), IsInfiniteDuration(), absl::ABSL_NAMESPACE_BEGIN::MakeU128Ticks(), absl::operator-(), absl::operator<(), absl::operator==(), absl::ABSL_NAMESPACE_BEGIN::SafeAddRepHi(), absl::ABSL_NAMESPACE_BEGIN::ScaleDouble(), absl::ToInt64Hours(), absl::ToInt64Microseconds(), absl::ToInt64Milliseconds(), absl::ToInt64Minutes(), absl::ToInt64Nanoseconds(), absl::ToInt64Seconds(), absl::ToTimespec(), absl::ToTimespec(), absl::ToUnixMicros(), absl::ToUnixMillis(), and absl::ToUnixNanos().
IDivDuration()
int64_t absl::time_internal::IDivDuration (bool satq, const Duration num, const Duration den, Duration * rem)
Definition at line 358 of file duration.cc.
{
  int64_t q = 0;
  if (IDivFastPath(num, den, &q, rem)) {
    return q;
  }
  const bool num_neg = num < ZeroDuration();
  const bool den_neg = den < ZeroDuration();
  const bool quotient_neg = num_neg != den_neg;
  if (time_internal::IsInfiniteDuration(num) || den == ZeroDuration()) {
    *rem = num_neg ? -InfiniteDuration() : InfiniteDuration();
    return quotient_neg ? kint64min : kint64max;
  }
  if (time_internal::IsInfiniteDuration(den)) {
    *rem = num;
    return 0;
  }
  const uint128 a = MakeU128Ticks(num);
  const uint128 b = MakeU128Ticks(den);
  uint128 quotient128 = a / b;
  if (satq) {
    // Limits the quotient to the range of int64_t.
    if (quotient128 > uint128(static_cast<uint64_t>(kint64max))) {
      quotient128 = quotient_neg ? uint128(static_cast<uint64_t>(kint64min))
                                 : uint128(static_cast<uint64_t>(kint64max));
    }
  }
  const uint128 remainder128 = a - quotient128 * b;
  *rem = MakeDurationFromU128(remainder128, num_neg);
  if (!quotient_neg || quotient128 == 0) {
    return Uint128Low64(quotient128) & kint64max;
  }
  // The quotient needs to be negated, but we need to carefully handle
  // quotient128s with the top bit on.
  return -static_cast<int64_t>(Uint128Low64(quotient128 - 1) & kint64max) - 1;
}
References absl::a, b, absl::InfiniteDuration(), IsInfiniteDuration(), num, absl::Uint128Low64(), and absl::ZeroDuration().
Referenced by absl::IDivDuration(), absl::Duration::operator%=(), and absl::operator/().
IsInfiniteDuration()
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr bool absl::time_internal::IsInfiniteDuration (Duration d) constexpr
Definition at line 1501 of file time.h.
{
  return GetRepLo(d) == ~uint32_t{0};
}
References absl::d, and GetRepLo().
Referenced by absl::FDivDuration(), IDivDuration(), absl::ABSL_NAMESPACE_BEGIN::IDivFastPath(), absl::Duration::operator*=(), absl::Duration::operator*=(), absl::Duration::operator+=(), absl::operator-(), absl::Duration::operator-=(), absl::Duration::operator/=(), absl::Duration::operator/=(), ToChronoDuration(), absl::ToInt64Hours(), absl::ToInt64Minutes(), absl::ToInt64Seconds(), absl::ToTimespec(), and absl::ToTimespec().
IsValidRep64() [1/2]
template<typename T > auto absl::time_internal::IsValidRep64 (char) -> bool constexpr
Definition at line 1563 of file time.h.
{
  return false;
}
IsValidRep64() [2/2]
template<typename T > auto absl::time_internal::IsValidRep64 (int) -> decltype(int64_t{std::declval<T>()} = constexpr pure virtual
Definition at line 1559 of file time.h.
                                                    {std::declval<T>()} == 0) {
  return true;
}
Referenced by FromChrono(), and ToChronoDuration().
LoadTimeZone()
absl::TimeZone absl::time_internal::LoadTimeZone (const std::string & name)
Definition at line 24 of file test_util.cc.
{
  TimeZone tz;
  ABSL_RAW_CHECK(LoadTimeZone(name, &tz), name.c_str());
  return tz;
}
References ABSL_RAW_CHECK, LoadTimeZone(), and name.
Referenced by LoadTimeZone().
MakeDuration() [1/2]
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration absl::time_internal::MakeDuration (int64_t hi, int64_t lo) constexpr
Definition at line 1465 of file time.h.
{
  return MakeDuration(hi, static_cast<uint32_t>(lo));
}
References MakeDuration().
MakeDuration() [2/2]
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration absl::time_internal::MakeDuration (int64_t hi, uint32_t lo = 0) constexpr
Definition at line 1460 of file time.h.
{
  return Duration(hi, lo);
}
Referenced by absl::TimeZone::At(), absl::DurationFromTimespec(), absl::DurationFromTimeval(), FromInt64(), FromInt64(), absl::ABSL_NAMESPACE_BEGIN::IDivFastPath(), absl::Time::In(), absl::InfiniteDuration(), MakeDuration(), absl::ABSL_NAMESPACE_BEGIN::MakeDurationFromU128(), MakeNormalizedDuration(), MakePosDoubleDuration(), absl::ABSL_NAMESPACE_BEGIN::MakeTimeWithOverflow(), absl::Now(), absl::operator-(), OppositeInfinity(), absl::ABSL_NAMESPACE_BEGIN::SafeAddRepHi(), and absl::ABSL_NAMESPACE_BEGIN::ScaleDouble().
MakeNormalizedDuration()
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration absl::time_internal::MakeNormalizedDuration (int64_t sec, int64_t ticks) constexpr
Definition at line 1486 of file time.h.
{
  return (ticks < 0) ? MakeDuration(sec - 1, ticks + kTicksPerSecond)
                     : MakeDuration(sec, ticks);
}
References MakeDuration(), and sec.
Referenced by FromInt64().
MakePosDoubleDuration()
ABSL_ATTRIBUTE_CONST_FUNCTION Duration absl::time_internal::MakePosDoubleDuration (double n) inline
Definition at line 1473 of file time.h.
{
  const int64_t int_secs = static_cast<int64_t>(n);
  const uint32_t ticks = static_cast<uint32_t>(
      std::round((n - static_cast<double>(int_secs)) * kTicksPerSecond));
  return ticks < kTicksPerSecond
             ? MakeDuration(int_secs, ticks)
             : MakeDuration(int_secs + 1, ticks - kTicksPerSecond);
}
References MakeDuration(), and absl::n.
Referenced by absl::Seconds().
NegateAndSubtractOne()
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr int64_t absl::time_internal::NegateAndSubtractOne (int64_t n) constexpr
Definition at line 1515 of file time.h.
               {
  // Note: Good compilers will optimize this expression to ~n when using
  // a two's-complement representation (which is required for int64_t).
  return (n < 0) ? -(n + 1) : (-n) - 1;
}
References absl::n.
Referenced by absl::operator-().
operator<<()
std::ostream & absl::time_internal::operator<< (std::ostream & os, CivilYear y)
Definition at line 152 of file civil_time.cc.
{
  return os << FormatCivilTime(y);
}
References absl::FormatCivilTime(), and y.
OppositeInfinity()
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration absl::time_internal::OppositeInfinity (Duration d) constexpr
Definition at line 1507 of file time.h.
{
  return GetRepHi(d) < 0
             ? MakeDuration((std::numeric_limits<int64_t>::max)(), ~uint32_t{0})
             : MakeDuration((std::numeric_limits<int64_t>::min)(),
                            ~uint32_t{0});
}
References absl::d, GetRepHi(), and MakeDuration().
Referenced by absl::operator-().
ToChronoDuration()
template<typename T > ABSL_ATTRIBUTE_CONST_FUNCTION T absl::time_internal::ToChronoDuration (Duration d)
Definition at line 1606 of file time.h.
{
  using Rep = typename T::rep;
  using Period = typename T::period;
  static_assert(IsValidRep64<Rep>(0), "duration::rep is invalid");
  if (time_internal::IsInfiniteDuration(d))
    return d < ZeroDuration() ? (T::min)() : (T::max)();
  const auto v = ToInt64(d, Period{});
  if (v > (std::numeric_limits<Rep>::max)()) return (T::max)();
  if (v < (std::numeric_limits<Rep>::min)()) return (T::min)();
  return T{v};
}
References absl::d, IsInfiniteDuration(), IsValidRep64(), ToInt64(), absl::v, and absl::ZeroDuration().
Referenced by absl::ToChronoHours(), absl::ToChronoMicroseconds(), absl::ToChronoMilliseconds(), absl::ToChronoMinutes(), absl::ToChronoNanoseconds(), absl::ToChronoSeconds(), and absl::ToChronoTime().
ToInt64() [1/7]
template<typename Ratio > ABSL_ATTRIBUTE_CONST_FUNCTION int64_t absl::time_internal::ToInt64 (Duration d, Ratio)
Definition at line 1576 of file time.h.
{
  // Note: This may be used on MSVC, which may have a system_clock period of
  // std::ratio<1, 10 * 1000 * 1000>
  return ToInt64Seconds(d * Ratio::den / Ratio::num);
}
References absl::d, and absl::ToInt64Seconds().
Referenced by ToChronoDuration().
ToInt64() [2/7]
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t absl::time_internal::ToInt64 (Duration d, std::micro) inline
Definition at line 1585 of file time.h.
{
  return ToInt64Microseconds(d);
}
References absl::d, and absl::ToInt64Microseconds().
ToInt64() [3/7]
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t absl::time_internal::ToInt64 (Duration d, std::milli) inline
Definition at line 1588 of file time.h.
{
  return ToInt64Milliseconds(d);
}
References absl::d, and absl::ToInt64Milliseconds().
ToInt64() [4/7]
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t absl::time_internal::ToInt64 (Duration d, std::nano) inline
Definition at line 1582 of file time.h.
{
  return ToInt64Nanoseconds(d);
}
References absl::d, and absl::ToInt64Nanoseconds().
ToInt64() [5/7]
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t absl::time_internal::ToInt64 (Duration d, std::ratio< 1 >) inline
Definition at line 1591 of file time.h.
{
  return ToInt64Seconds(d);
}
References absl::d, and absl::ToInt64Seconds().
ToInt64() [6/7]
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t absl::time_internal::ToInt64 (Duration d, std::ratio< 3600 >) inline
Definition at line 1599 of file time.h.
{
  return ToInt64Hours(d);
}
References absl::d, and absl::ToInt64Hours().
ToInt64() [7/7]
ABSL_ATTRIBUTE_CONST_FUNCTION int64_t absl::time_internal::ToInt64 (Duration d, std::ratio< 60 >) inline
Definition at line 1595 of file time.h.
{
  return ToInt64Minutes(d);
}
References absl::d, and absl::ToInt64Minutes().
ToUnixDuration()
ABSL_ATTRIBUTE_CONST_FUNCTION constexpr Duration absl::time_internal::ToUnixDuration (Time t) constexpr
Definition at line 1529 of file time.h.
{
  return t.rep_;
}
Referenced by absl::TimeZone::At(), absl::ToChronoTime(), absl::ToTimespec(), absl::ToUDate(), absl::ToUnixMicros(), absl::ToUnixMillis(), absl::ToUnixNanos(), and absl::ToUnixSeconds().
Variable Documentation
kTicksPerNanosecond
int64_t absl::time_internal::kTicksPerNanosecond = 4 constexpr
Definition at line 110 of file time.h.
kTicksPerSecond
int64_t absl::time_internal::kTicksPerSecond = 1000 * 1000 * 1000 * kTicksPerNanosecond constexpr
Definition at line 111 of file time.h.
Referenced by absl::operator-().