open spiel: open_spiel.python.algorithms.fictitious_play Namespace Reference
open_spiel.python.algorithms.fictitious_play Namespace Reference
Classes
class JointPolicy
class XFPSolver
Functions
_uniform_policy (state)
_callable_tabular_policy (tabular_policy)
_full_best_response_policy (br_infoset_dict)
_policy_dict_at_state (callable_policy, state)
Detailed Description
Implementations of classical fictitious play.
See https://en.wikipedia.org/wiki/Fictitious_play.
Function Documentation
_callable_tabular_policy()
open_spiel.python.algorithms.fictitious_play._callable_tabular_policy (tabular_policy) protected
Turns a tabular policy into a callable.
Args:
  tabular_policy: A dictionary mapping information state key to a dictionary
    of action probabilities (action -> prob).
Returns:
  A function `state` -> list of (action, prob)
Definition at line 34 of file fictitious_play.py.
def _callable_tabular_policy(tabular_policy):
  """Turns a tabular policy into a callable.
  Args:
    tabular_policy: A dictionary mapping information state key to a dictionary
      of action probabilities (action -> prob).
  Returns:
    A function `state` -> list of (action, prob)
  """
  def wrap(state):
    infostate_key = state.information_state_string(state.current_player())
    assert infostate_key in tabular_policy
    ap_list = []
    for action in state.legal_actions():
      assert action in tabular_policy[infostate_key]
      ap_list.append((action, tabular_policy[infostate_key][action]))
    return ap_list
  return wrap
Referenced by open_spiel.python.algorithms.fictitious_play.XFPSolver.update_average_policies().
_full_best_response_policy()
open_spiel.python.algorithms.fictitious_play._full_best_response_policy (br_infoset_dict) protected
Turns a dictionary of best response action selections into a full policy.
Args:
  br_infoset_dict: A dictionary mapping information state to a best response
    action.
Returns:
  A function `state` -> list of (action, prob)
Definition at line 75 of file fictitious_play.py.
def _full_best_response_policy(br_infoset_dict):
  """Turns a dictionary of best response action selections into a full policy.
  Args:
    br_infoset_dict: A dictionary mapping information state to a best response
      action.
  Returns:
    A function `state` -> list of (action, prob)
  """
  def wrap(state):
    infostate_key = state.information_state_string(state.current_player())
    br_action = br_infoset_dict[infostate_key]
    ap_list = []
    for action in state.legal_actions():
      ap_list.append((action, 1.0 if action == br_action else 0.0))
    return ap_list
  return wrap
Referenced by open_spiel.python.algorithms.fictitious_play.XFPSolver.compute_best_responses().
_policy_dict_at_state()
open_spiel.python.algorithms.fictitious_play._policy_dict_at_state (callable_policy, state) protected
Turns a policy function into a dictionary at a specific state.
Args:
  callable_policy: A function from `state` -> lis of (action, prob),
  state: the specific state to extract the policy from.
Returns:
  A dictionary of action -> prob at this state.
Definition at line 97 of file fictitious_play.py.
def _policy_dict_at_state(callable_policy, state):
  """Turns a policy function into a dictionary at a specific state.
  Args:
    callable_policy: A function from `state` -> lis of (action, prob),
    state: the specific state to extract the policy from.
  Returns:
    A dictionary of action -> prob at this state.
  """
  infostate_policy_list = callable_policy(state)
  infostate_policy = {}
  for ap in infostate_policy_list:
    infostate_policy[ap[0]] = ap[1]
  return infostate_policy
Referenced by open_spiel.python.algorithms.fictitious_play.XFPSolver._recursively_update_average_policies(), and open_spiel.python.algorithms.fictitious_play.XFPSolver.sample_episode().
_uniform_policy()
open_spiel.python.algorithms.fictitious_play._uniform_policy (state) protected
Definition at line 29 of file fictitious_play.py.
def _uniform_policy(state):
  legal_actions = state.legal_actions()
  return [(action, 1.0 / len(legal_actions)) for action in legal_actions]
References len.