open spiel: pybind11::detail Namespace Reference
pybind11::detail Namespace Reference
Classes
struct absl_civil_time_caster
struct is_absl_span
struct is_absl_span< absl::Span< T > >
struct NoThrowStatusType
struct NoThrowStatusType< absl::StatusOr< PayloadType > >
struct type_caster< absl::btree_map< Key, Value, Compare, Alloc > >
struct type_caster< absl::CivilDay >
struct type_caster< absl::CivilHour >
struct type_caster< absl::CivilMinute >
struct type_caster< absl::CivilMonth >
struct type_caster< absl::CivilSecond >
struct type_caster< absl::CivilYear >
struct type_caster< absl::Cord >
struct type_caster< absl::Duration >
struct type_caster< absl::flat_hash_map< Key, Value, Hash, Equal, Alloc > >
struct type_caster< absl::flat_hash_set< Key, Hash, Equal, Alloc > >
struct type_caster< absl::nullopt_t >
struct type_caster< absl::optional< T > >
struct type_caster< absl::Span< T > >
struct type_caster< absl::Status >
struct type_caster< absl::StatusOr< PayloadType > >
struct type_caster< absl::string_view >
struct type_caster< absl::Time >
struct type_caster< absl::TimeZone >
struct type_caster< absl::variant< Ts... > >
struct type_caster< google::NoThrowStatus< StatusType > >
struct type_caster< open_spiel::GameParameter >
Functions
int64_t GetInt64Attr (handle src, const char *name)
absl::TimeZone GetTimeZone (handle src)
template<typename T , typename std::enable_if< std::is_arithmetic< T >::value, bool >::type = true>
std::tuple< bool, absl::Span< T > > LoadSpanFromBuffer (handle src)
template<typename T , typename std::enable_if<!std::is_arithmetic< T >::value, bool >::type = true>
constexpr std::tuple< bool, absl::Span< T > > LoadSpanFromBuffer (handle src)
Function Documentation
GetInt64Attr()
int64_t pybind11::detail::GetInt64Attr (handle src, const char * name) inline
Definition at line 58 of file absl_casters.h.
{
  return src.attr(name).cast<int64_t>();
}
References name.
Referenced by pybind11::detail::absl_civil_time_caster< CivilTimeType >::load(), pybind11::detail::type_caster< absl::Duration >::load(), and pybind11::detail::type_caster< absl::Time >::load().
GetTimeZone()
absl::TimeZone pybind11::detail::GetTimeZone (handle src) inline
Definition at line 64 of file absl_casters.h.
{
  if (!hasattr(src, "tzinfo")) {
    // datetime.date objects lack this property, so assume local.
    return absl::LocalTimeZone();
  }
  object tzinfo = src.attr("tzinfo");
  if (tzinfo.is_none()) {
    // non-tz aware datetime, again assume local time.
    return absl::LocalTimeZone();
  }
  object utc_offset = tzinfo.attr("utcoffset")(src);
  if (utc_offset.is_none()) {
    return absl::LocalTimeZone();
  }
  int64_t offset_seconds =
      std::lround(utc_offset.attr("total_seconds")().cast<double>());
  return absl::FixedTimeZone(offset_seconds);
}
References absl::FixedTimeZone(), and absl::LocalTimeZone().
Referenced by pybind11::detail::type_caster< absl::Time >::load().
LoadSpanFromBuffer() [1/2]
template<typename T , typename std::enable_if< std::is_arithmetic< T >::value, bool >::type = true> std::tuple< bool, absl::Span< T > > pybind11::detail::LoadSpanFromBuffer (handle src)
Definition at line 276 of file absl_casters.h.
{
  Py_buffer view;
  int flags = PyBUF_STRIDES | PyBUF_FORMAT;
  if (!std::is_const<T>::value) flags |= PyBUF_WRITABLE;
  if (PyObject_GetBuffer(src.ptr(), &view, flags) == 0) {
    auto cleanup = absl::MakeCleanup([&view] { PyBuffer_Release(&view); });
    if (view.ndim == 1 && view.strides[0] == sizeof(T) &&
        view.format[0] == format_descriptor<T>::c) {
      return {true, absl::MakeSpan(static_cast<T*>(view.buf), view.shape[0])};
    }
  } else {
    // Clear the buffer error (failure is reported in the return value).
    PyErr_Clear();
  }
  return {false, absl::Span<T>()};
}
References absl::MakeCleanup(), and absl::MakeSpan().
LoadSpanFromBuffer() [2/2]
template<typename T , typename std::enable_if<!std::is_arithmetic< T >::value, bool >::type = true> std::tuple< bool, absl::Span< T > > pybind11::detail::LoadSpanFromBuffer (handle src) constexpr
Definition at line 295 of file absl_casters.h.
{
  return {false, absl::Span<T>()};
}