open spiel: absl::substitute_internal Namespace Reference
absl::substitute_internal Namespace Reference
Classes
class Arg
Functions
void SubstituteAndAppendArray (std::string *output, absl::string_view format, const absl::string_view *args_array, size_t num_args)
Function Documentation
SubstituteAndAppendArray()
void absl::substitute_internal::SubstituteAndAppendArray (std::string * output, absl::string_view format, const absl::string_view * args_array, size_t num_args)
Definition at line 29 of file substitute.cc.
{
  // Determine total size needed.
  size_t size = 0;
  for (size_t i = 0; i < format.size(); i++) {
    if (format[i] == '$') {
      if (i + 1 >= format.size()) {
#ifndef NDEBUG
        ABSL_RAW_LOG(FATAL,
                     "Invalid absl::Substitute() format string: \"%s\".",
                     absl::CEscape(format).c_str());
#endif
        return;
      } else if (absl::ascii_isdigit(
                     static_cast<unsigned char>(format[i + 1]))) {
        int index = format[i + 1] - '0';
        if (static_cast<size_t>(index) >= num_args) {
#ifndef NDEBUG
          ABSL_RAW_LOG(
              FATAL,
              "Invalid absl::Substitute() format string: asked for \"$"
              "%d\", but only %d args were given.  Full format string was: "
              "\"%s\".",
              index, static_cast<int>(num_args), absl::CEscape(format).c_str());
#endif
          return;
        }
        size += args_array[index].size();
        ++i;  // Skip next char.
      } else if (format[i + 1] == '$') {
        ++size;
        ++i;  // Skip next char.
      } else {
#ifndef NDEBUG
        ABSL_RAW_LOG(FATAL,
                     "Invalid absl::Substitute() format string: \"%s\".",
                     absl::CEscape(format).c_str());
#endif
        return;
      }
    } else {
      ++size;
    }
  }
  if (size == 0) return;
  // Build the string.
  size_t original_size = output->size();
  strings_internal::STLStringResizeUninitializedAmortized(output,
                                                          original_size + size);
  char* target = &(*output)[original_size];
  for (size_t i = 0; i < format.size(); i++) {
    if (format[i] == '$') {
      if (absl::ascii_isdigit(static_cast<unsigned char>(format[i + 1]))) {
        const absl::string_view src = args_array[format[i + 1] - '0'];
        target = std::copy(src.begin(), src.end(), target);
        ++i;  // Skip next char.
      } else if (format[i + 1] == '$') {
        *target++ = '$';
        ++i;  // Skip next char.
      }
    } else {
      *target++ = format[i];
    }
  }
  assert(target == output->data() + output->size());
}
References ABSL_RAW_LOG, absl::ascii_isdigit(), absl::string_view::begin(), absl::CEscape(), absl::string_view::end(), absl::i, absl::string_view::size(), size, and absl::strings_internal::STLStringResizeUninitializedAmortized().
Referenced by absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), absl::SubstituteAndAppend(), and absl::SubstituteAndAppend().