open spiel: evaluation Namespace Reference
evaluation Namespace Reference
Functions
compute_best_response_strategy (utility)
compute_values_against_best_response (strategy, payoff)
evaluate_against_best_response (agent, payoff_batch, steps_count)
compute_regrets (payoff_batch, strategy_x, strategy_y)
evaluate_in_selfplay (agent_x, agent_y, payoff_batch, steps_count)
CFRBREvaluation (agent, world_state)
Variables
FLAGS = flags.FLAGS
Detailed Description
Evaluation.
Evaluation of a CFR best response agent given the world state.
Function Documentation
CFRBREvaluation()
evaluation.CFRBREvaluation (agent, world_state)
Definition at line 21 of file evaluation.py.
def CFRBREvaluation(agent, world_state):
  return agent.next_policy(world_state)
Referenced by main.main().
compute_best_response_strategy()
evaluation.compute_best_response_strategy (utility)
Definition at line 26 of file evaluation.py.
def compute_best_response_strategy(utility):
  actions_count = utility.shape[-1]
  opponent_action = jnp.argmin(utility, axis=-1)
  opponent_strategy = jax.nn.one_hot(opponent_action, actions_count)
  return opponent_strategy
@jax.jit
Referenced by compute_values_against_best_response().
compute_regrets()
evaluation.compute_regrets (payoff_batch, strategy_x, strategy_y)
Definition at line 62 of file evaluation.py.
def compute_regrets(payoff_batch, strategy_x, strategy_y):
  values_y = -jnp.matmul(strategy_x, payoff_batch)
  values_x = jnp.transpose(
      jnp.matmul(payoff_batch, jnp.transpose(strategy_y, [0, 2, 1])), [0, 2, 1])
  value_x = jnp.matmul(
      jnp.matmul(strategy_x, payoff_batch),
      jnp.transpose(strategy_y, [0, 2, 1]))
  value_y = -value_x
  regrets_x = values_x - value_x
  regrets_y = values_y - value_y
  return regrets_x, regrets_y
Referenced by evaluate_in_selfplay().
compute_values_against_best_response()
evaluation.compute_values_against_best_response (strategy, payoff)
Definition at line 34 of file evaluation.py.
def compute_values_against_best_response(strategy, payoff):
  utility = jnp.matmul(strategy, payoff)
  br_strategy = compute_best_response_strategy(utility)
  return jnp.matmul(payoff, jnp.transpose(br_strategy))
References compute_best_response_strategy().
evaluate_against_best_response()
evaluation.evaluate_against_best_response (agent, payoff_batch, steps_count)
Evaluation against best response agent.
Args:
  agent: Agent model.
  payoff_batch: Payoff matrix.
  steps_count: Number of steps.
Definition at line 40 of file evaluation.py.
def evaluate_against_best_response(agent, payoff_batch, steps_count):
  """Evaluation against best response agent.
  Args:
    agent: Agent model.
    payoff_batch: Payoff matrix.
    steps_count: Number of steps.
  """
  current_policy = agent.initial_policy()
  values = jax.vmap(compute_values_against_best_response)(current_policy,
                                                          payoff_batch)
  for step in range(steps_count):
    current_policy = agent.next_policy(values)
    values = jax.vmap(compute_values_against_best_response)(current_policy,
                                                            payoff_batch)
    values = jnp.transpose(values, [0, 1, 2])
    value = jnp.matmul(current_policy, values)
    for i in range(value.shape[0]):
      print(step, np.mean(np.asarray(value[i])))
evaluate_in_selfplay()
evaluation.evaluate_in_selfplay (agent_x, agent_y, payoff_batch, steps_count)
Evalute in selfplay.
Args:
  agent_x: First agent.
  agent_y: Second agent.
  payoff_batch: Payoff matrix.
  steps_count: Number of steps.
Definition at line 75 of file evaluation.py.
def evaluate_in_selfplay(agent_x, agent_y, payoff_batch, steps_count):
  """Evalute in selfplay.
  Args:
    agent_x: First agent.
    agent_y: Second agent.
    payoff_batch: Payoff matrix.
    steps_count: Number of steps.
  """
  payoff_batch_size = payoff_batch.shape[0]
  regret_sum_x = np.zeros(shape=[payoff_batch_size, 1, FLAGS.num_actions])
  regret_sum_y = np.zeros(shape=[payoff_batch_size, 1, FLAGS.num_actions])
  strategy_x = agent_x.initial_policy()
  strategy_y = agent_y.initial_policy()
  regrets_x, regrets_y = compute_regrets(payoff_batch, strategy_x, strategy_y)
  regret_sum_x += regrets_x
  regret_sum_y += regrets_y
  for s in range(steps_count):
    values_y = -jnp.matmul(strategy_x, payoff_batch)
    values_x = jnp.transpose(
        jnp.matmul(payoff_batch, jnp.transpose(strategy_y, [0, 2, 1])),
        [0, 2, 1])
    values_x = jnp.transpose(values_x, [0, 2, 1])
    values_y = jnp.transpose(values_y, [0, 2, 1])
    strategy_x = agent_x.next_policy(values_x)
    strategy_y = agent_y.next_policy(values_y)
    regrets_x, regrets_y = compute_regrets(payoff_batch, strategy_x, strategy_y)
    regret_sum_x += regrets_x
    regret_sum_y += regrets_y
    print(
        jnp.mean(
            jnp.max(
                jnp.concatenate([regret_sum_x, regret_sum_y], axis=2),
                axis=[1, 2]) / (s + 1)))
References compute_regrets().
Referenced by main.selfplay_main().
Variable Documentation
FLAGS
evaluation.FLAGS = flags.FLAGS
Definition at line 22 of file evaluation.py.