open spiel: open_spiel::dots_and_boxes Namespace Reference
open_spiel::dots_and_boxes Namespace Reference
Classes
class DotsAndBoxesGame
class DotsAndBoxesState
class Move
Enumerations
enum class CellState { kEmpty , kPlayer1 , kPlayer2 , kSet }
enum class CellOrientation { kHorizontal , kVertical }
Functions
CellState PlayerToState (Player player)
std::string StateToString (CellState state)
std::string OrientationToString (CellOrientation orientation)
std::ostream & operator<< (std::ostream &stream, const CellState &state)
Variables
constexpr int kNumPlayers = 2
constexpr int kDefaultNumRows = 2
constexpr int kDefaultNumCols = 2
constexpr int kMaskSize = 10
constexpr int kMask = (1 << kMaskSize) - 1
constexpr bool kDefaultUtilityMargin = false
Enumeration Type Documentation
CellOrientation
enum class open_spiel::dots_and_boxes::CellOrientation strong
Enumerator
kHorizontal
kVertical
Definition at line 59 of file dots_and_boxes.h.
{
  kHorizontal,  // = 0
  kVertical,    // = 1
};
CellState
enum class open_spiel::dots_and_boxes::CellState strong
Enumerator
kEmpty
kPlayer1
kPlayer2
kSet
Definition at line 52 of file dots_and_boxes.h.
                     {
  kEmpty,    // Not set
  kPlayer1,  // Set by player 1
  kPlayer2,  // Set by player 2
  kSet       // Set by default start state
};
Function Documentation
operator<<()
std::ostream & open_spiel::dots_and_boxes::operator<< (std::ostream & stream, const CellState & state) inline
Definition at line 188 of file dots_and_boxes.h.
{
  return stream << StateToString(state);
}
References state, and StateToString().
OrientationToString()
std::string open_spiel::dots_and_boxes::OrientationToString (CellOrientation orientation)
Definition at line 91 of file dots_and_boxes.cc.
{
  switch (orientation) {
    case CellOrientation::kHorizontal:
      return "h";
    case CellOrientation::kVertical:
      return "v";
    default:
      SpielFatalError("Unknown orientation.");
  }
}
References kHorizontal, kVertical, and open_spiel::SpielFatalError().
Referenced by open_spiel::dots_and_boxes::DotsAndBoxesState::ActionToString().
PlayerToState()
CellState open_spiel::dots_and_boxes::PlayerToState (Player player)
Definition at line 66 of file dots_and_boxes.cc.
{
  switch (player) {
    case 0:
      return CellState::kPlayer1;
    case 1:
      return CellState::kPlayer2;
    default:
      SpielFatalError(absl::StrCat("Invalid player id ", player));
      return CellState::kEmpty;
  }
}
References kEmpty, kPlayer1, kPlayer2, player, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::dots_and_boxes::DotsAndBoxesState::ActionToString(), and open_spiel::dots_and_boxes::DotsAndBoxesState::DoApplyAction().
StateToString()
std::string open_spiel::dots_and_boxes::StateToString (CellState state)
Definition at line 78 of file dots_and_boxes.cc.
{
  switch (state) {
    case CellState::kEmpty:
      return ".";
    case CellState::kPlayer1:
      return "1";
    case CellState::kPlayer2:
      return "2";
    default:
      SpielFatalError("Unknown state.");
  }
}
References kEmpty, kPlayer1, kPlayer2, open_spiel::SpielFatalError(), and state.
Referenced by open_spiel::dots_and_boxes::DotsAndBoxesState::ActionToString(), and operator<<().
Variable Documentation
kDefaultNumCols
int open_spiel::dots_and_boxes::kDefaultNumCols = 2 inline constexpr
Definition at line 46 of file dots_and_boxes.h.
kDefaultNumRows
int open_spiel::dots_and_boxes::kDefaultNumRows = 2 inline constexpr
Definition at line 45 of file dots_and_boxes.h.
kDefaultUtilityMargin
bool open_spiel::dots_and_boxes::kDefaultUtilityMargin = false inline constexpr
Definition at line 49 of file dots_and_boxes.h.
kMask
int open_spiel::dots_and_boxes::kMask = (1 << kMaskSize) - 1 inline constexpr
Definition at line 48 of file dots_and_boxes.h.
kMaskSize
int open_spiel::dots_and_boxes::kMaskSize = 10 inline constexpr
Definition at line 47 of file dots_and_boxes.h.
kNumPlayers
int open_spiel::dots_and_boxes::kNumPlayers = 2 inline constexpr
Definition at line 44 of file dots_and_boxes.h.
Referenced by open_spiel::dots_and_boxes::DotsAndBoxesGame::NumPlayers().