open spiel: absl_test Namespace Reference
absl_test Namespace Reference
Classes
class AbslBTreeMapTest
class AbslCordTest
class AbslFlatHashMapTest
class AbslFlatHashSetTest
class AbslNumericSpanTest
class AbslObjectSpanTest
class AbslOptionalTest
class AbslStringViewTest
class AbslTimeTest
class AbslVariantTest
Functions
make_read_only_numpy_array ()
make_srided_numpy_array (stride)
make_native_list_of_objects ()
make_opaque_list_of_objects ()
make_list_of_objects_parameters ()
Detailed Description
Tests for absl pybind11 casters.
Function Documentation
make_list_of_objects_parameters()
absl_test.make_list_of_objects_parameters ()
Definition at line 303 of file absl_test.py.
def make_list_of_objects_parameters():
  return (('native_list', make_native_list_of_objects()),
          ('opaque_list', make_opaque_list_of_objects()))
References make_native_list_of_objects(), and make_opaque_list_of_objects().
make_native_list_of_objects()
absl_test.make_native_list_of_objects ()
Definition at line 295 of file absl_test.py.
def make_native_list_of_objects():
  return [absl_example.ObjectForSpan(3), absl_example.ObjectForSpan(5)]
Referenced by make_list_of_objects_parameters(), make_opaque_list_of_objects(), absl_test.AbslObjectSpanTest.test_fill_object_span_no_convert_fails_from_native_list(), and absl_test.AbslObjectSpanTest.test_pass_object_span_no_convert_fails_from_native_list().
make_opaque_list_of_objects()
absl_test.make_opaque_list_of_objects ()
Definition at line 299 of file absl_test.py.
def make_opaque_list_of_objects():
  return absl_example.ObjectVector(make_native_list_of_objects())
References make_native_list_of_objects().
Referenced by make_list_of_objects_parameters(), absl_test.AbslObjectSpanTest.test_fill_object_span_no_convert_from_opaque_list(), and absl_test.AbslObjectSpanTest.test_pass_object_span_no_convert_from_opaque_list().
make_read_only_numpy_array()
absl_test.make_read_only_numpy_array ()
Definition at line 217 of file absl_test.py.
def make_read_only_numpy_array():
  values = np.zeros(5, dtype=np.int32)
  values.flags.writeable = False
  return values
Referenced by absl_test.AbslNumericSpanTest.test_fill_span_from_numpy().
make_srided_numpy_array()
absl_test.make_srided_numpy_array (stride)
Definition at line 223 of file absl_test.py.
def make_srided_numpy_array(stride):
  return np.zeros(10, dtype=np.int32)[::stride]
Referenced by absl_test.AbslNumericSpanTest.test_fill_span_from_numpy().