open spiel: open_spiel.python.examples.independent_tabular_qlearning Namespace Reference
open_spiel.python.examples.independent_tabular_qlearning Namespace Reference
Functions
eval_agents (env, agents, num_episodes)
create_epsilon_schedule (sched_str)
main (_)
Variables
FLAGS = flags.FLAGS
Detailed Description
Tabular Q-Learner self-play example.
Two Q-Learning agents are trained by playing against each other.
Function Documentation
create_epsilon_schedule()
open_spiel.python.examples.independent_tabular_qlearning.create_epsilon_schedule (sched_str)
Creates an epsilon schedule from the string as desribed in the flags.
Definition at line 59 of file independent_tabular_qlearning.py.
def create_epsilon_schedule(sched_str):
  """Creates an epsilon schedule from the string as desribed in the flags."""
  values = FLAGS.epsilon_schedule.split(",")
  if values[0] == "linear":
    assert len(values) == 4
    return rl_tools.LinearSchedule(
        float(values[1]), float(values[2]), int(values[3]))
  elif values[0] == "constant":
    assert len(values) == 2
    return rl_tools.ConstantSchedule(float(values[1]))
  else:
    print("Unrecognized schedule string: {}".format(sched_str))
    sys.exit()
References len.
Referenced by open_spiel.python.examples.independent_tabular_qlearning.main().
eval_agents()
open_spiel.python.examples.independent_tabular_qlearning.eval_agents (env, agents, num_episodes)
Evaluate the agents, returning a numpy array of average returns.
Definition at line 44 of file independent_tabular_qlearning.py.
def eval_agents(env, agents, num_episodes):
  """Evaluate the agents, returning a numpy array of average returns."""
  rewards = np.array([0] * env.num_players, dtype=np.float64)
  for _ in range(num_episodes):
    time_step = env.reset()
    while not time_step.last():
      player_id = time_step.observations["current_player"]
      agent_output = agents[player_id].step(time_step, is_evaluation=True)
      time_step = env.step([agent_output.action])
    for i in range(env.num_players):
      rewards[i] += time_step.rewards[i]
  rewards /= num_episodes
  return rewards
Referenced by open_spiel.python.examples.independent_tabular_qlearning.main().
main()
open_spiel.python.examples.independent_tabular_qlearning.main (_)
Definition at line 74 of file independent_tabular_qlearning.py.
def main(_):
  env = rl_environment.Environment(FLAGS.game)
  num_players = env.num_players
  num_actions = env.action_spec()["num_actions"]
  agents = []
  if FLAGS.epsilon_schedule is not None:
    for idx in range(num_players):
      agents.append(
          tabular_qlearner.QLearner(
              player_id=idx,
              num_actions=num_actions,
              epsilon_schedule=create_epsilon_schedule(FLAGS.epsilon_schedule)))
  else:
    agents = [
        tabular_qlearner.QLearner(player_id=idx, num_actions=num_actions)
        for idx in range(num_players)
    ]
  # 1. Train the agents
  training_episodes = FLAGS.num_train_episodes
  for cur_episode in range(training_episodes):
    if cur_episode % int(FLAGS.eval_freq) == 0:
      avg_rewards = eval_agents(env, agents, FLAGS.num_eval_episodes)
      print("Training episodes: {}, Avg rewards: {}".format(
          cur_episode, avg_rewards))
    time_step = env.reset()
    while not time_step.last():
      player_id = time_step.observations["current_player"]
      agent_output = agents[player_id].step(time_step)
      time_step = env.step([agent_output.action])
    # Episode is over, step all agents with final info state.
    for agent in agents:
      agent.step(time_step)
References open_spiel.python.examples.independent_tabular_qlearning.create_epsilon_schedule(), and open_spiel.python.examples.independent_tabular_qlearning.eval_agents().
Variable Documentation
FLAGS
open_spiel.python.examples.independent_tabular_qlearning.FLAGS = flags.FLAGS
Definition at line 29 of file independent_tabular_qlearning.py.