open spiel: absl_log_internal Namespace Reference
absl_log_internal Namespace Reference
Classes
class BasicLogTest
class ComparableType
class UnusedVariableWarningCompileTest
Enumerations
enum { CASE_A , CASE_B }
Functions
TEST (CHECKTest, TestLogicExpressions)
TEST (CHECKTest, TestPlacementsInCompoundStatements)
TEST (CHECKTest, TestBoolConvertible)
template<int a, int b>
constexpr int sum ()
TEST (CHECKTest, TestPassingMacroExpansion)
TEST (CHECKTest, TestBinaryChecksWithPrimitives)
TEST (CHECKTest, TestBinaryChecksWithEnumValues)
TEST (CHECKTest, TestBinaryChecksWithNullptr)
TEST (CHECKTest, TestSTREQ)
TEST (CHECKTest, TestComparisonPlacementsInCompoundStatements)
TEST (CHECKTest, TestDCHECK)
TEST (CHECKTest, TestQCHECK)
TEST (CHECKTest, TestQCHECKPlacementsInCompoundStatements)
TEST (CHECKTest, TestUserDefinedCompOp)
TEST (CHECKTest, TestCheckInMethod)
TEST (CHECKDeathTest, TestUserDefinedStreaming)
std::string ThresholdName (testing::TestParamInfo< absl::LogSeverityAtLeast > severity)
INSTANTIATE_TEST_SUITE_P (WithParam, BasicLogTest, testing::Values(absl::LogSeverityAtLeast::kInfo, absl::LogSeverityAtLeast::kWarning, absl::LogSeverityAtLeast::kError, absl::LogSeverityAtLeast::kFatal, absl::LogSeverityAtLeast::kInfinity), ThresholdName)
TEST_P (BasicLogTest, Info)
TEST_P (BasicLogTest, Warning)
TEST_P (BasicLogTest, Error)
TEST_P (BasicLogTest, Level)
TEST_P (BasicLogTest, LevelClampsNegativeValues)
TEST_P (BasicLogTest, LevelClampsLargeValues)
TEST (ErrnoPreservationTest, InSeverityExpression)
TEST (ErrnoPreservationTest, InStreamedExpression)
TEST (ErrnoPreservationTest, AfterStatement)
Variables
auto *test_env ABSL_ATTRIBUTE_UNUSED
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CASE_A
CASE_B
Definition at line 243 of file check_test_impl.h.
{ CASE_A, CASE_B };
Function Documentation
INSTANTIATE_TEST_SUITE_P()
absl_log_internal::INSTANTIATE_TEST_SUITE_P (WithParam , BasicLogTest , testing::Values(absl::LogSeverityAtLeast::kInfo, absl::LogSeverityAtLeast::kWarning, absl::LogSeverityAtLeast::kError, absl::LogSeverityAtLeast::kFatal, absl::LogSeverityAtLeast::kInfinity) , ThresholdName)
sum()
template<int a, int b> int absl_log_internal::sum () constexpr
Definition at line 125 of file check_test_impl.h.
                    {
  return a + b;
}
References a, and b.
TEST() [1/18]
absl_log_internal::TEST (CHECKDeathTest , TestUserDefinedStreaming)
Definition at line 514 of file check_test_impl.h.
{
  ComparableType v1{1};
  ComparableType v2{2};
  EXPECT_DEATH(
      ABSL_TEST_CHECK_EQ(v1, v2),
      HasSubstr(
          "Check failed: v1 == v2 (ComparableType{1} vs. ComparableType{2})"));
}
References ABSL_TEST_CHECK_EQ.
TEST() [2/18]
absl_log_internal::TEST (CHECKTest , TestBinaryChecksWithEnumValues)
Definition at line 245 of file check_test_impl.h.
{
  // Tests using CHECK*() on anonymous enums.
  ABSL_TEST_CHECK_EQ(CASE_A, CASE_A);
  ABSL_TEST_CHECK_NE(CASE_A, CASE_B);
  ABSL_TEST_CHECK_GE(CASE_A, CASE_A);
  ABSL_TEST_CHECK_GE(CASE_B, CASE_A);
  ABSL_TEST_CHECK_LE(CASE_A, CASE_A);
  ABSL_TEST_CHECK_LE(CASE_A, CASE_B);
  ABSL_TEST_CHECK_GT(CASE_B, CASE_A);
  ABSL_TEST_CHECK_LT(CASE_A, CASE_B);
}
References ABSL_TEST_CHECK_EQ, ABSL_TEST_CHECK_GE, ABSL_TEST_CHECK_GT, ABSL_TEST_CHECK_LE, ABSL_TEST_CHECK_LT, ABSL_TEST_CHECK_NE, CASE_A, and CASE_B.
TEST() [3/18]
absl_log_internal::TEST (CHECKTest , TestBinaryChecksWithNullptr)
Definition at line 257 of file check_test_impl.h.
{
  const void* p_null = nullptr;
  const void* p_not_null = &p_null;
  ABSL_TEST_CHECK_EQ(p_null, nullptr);
  ABSL_TEST_CHECK_EQ(nullptr, p_null);
  ABSL_TEST_CHECK_NE(p_not_null, nullptr);
  ABSL_TEST_CHECK_NE(nullptr, p_not_null);
}
References ABSL_TEST_CHECK_EQ, and ABSL_TEST_CHECK_NE.
TEST() [4/18]
absl_log_internal::TEST (CHECKTest , TestBinaryChecksWithPrimitives)
Definition at line 231 of file check_test_impl.h.
{
  ABSL_TEST_CHECK_EQ(1, 1);
  ABSL_TEST_CHECK_NE(1, 2);
  ABSL_TEST_CHECK_GE(1, 1);
  ABSL_TEST_CHECK_GE(2, 1);
  ABSL_TEST_CHECK_LE(1, 1);
  ABSL_TEST_CHECK_LE(1, 2);
  ABSL_TEST_CHECK_GT(2, 1);
  ABSL_TEST_CHECK_LT(1, 2);
}
References ABSL_TEST_CHECK_EQ, ABSL_TEST_CHECK_GE, ABSL_TEST_CHECK_GT, ABSL_TEST_CHECK_LE, ABSL_TEST_CHECK_LT, and ABSL_TEST_CHECK_NE.
TEST() [5/18]
absl_log_internal::TEST (CHECKTest , TestBoolConvertible)
Definition at line 99 of file check_test_impl.h.
{
  struct Tester {
  } tester;
  ABSL_TEST_CHECK([&]() { return &tester; }());
}
References ABSL_TEST_CHECK.
TEST() [6/18]
absl_log_internal::TEST (CHECKTest , TestCheckInMethod)
Definition at line 509 of file check_test_impl.h.
{
  ComparableType v{1};
  v.MethodWithCheck(1);
}
TEST() [7/18]
absl_log_internal::TEST (CHECKTest , TestComparisonPlacementsInCompoundStatements)
Definition at line 332 of file check_test_impl.h.
{
  // check placement inside if/else clauses
  if (true) ABSL_TEST_CHECK_EQ(1, 1);
  if (true) ABSL_TEST_CHECK_STREQ("c", "c");
  if (false)
    ;  // NOLINT
  else
    ABSL_TEST_CHECK_LE(0, 1);
  if (false)
    ;  // NOLINT
  else
    ABSL_TEST_CHECK_STRNE("a", "b");
  switch (0)
  case 0:
    ABSL_TEST_CHECK_NE(1, 0);
  switch (0)
  case 0:
    ABSL_TEST_CHECK_STRCASEEQ("A", "a");
#if ABSL_INTERNAL_CPLUSPLUS_LANG >= 201703L
  constexpr auto var = [](int i) {
    ABSL_TEST_CHECK_GT(i, 0);
    return i + 1;
  }(global_var);
  (void)var;
  // CHECK_STR... checks are not supported in constexpr routines.
  // constexpr auto var2 = [](int i) {
  //  ABSL_TEST_CHECK_STRNE("c", "d");
  //  return i + 1;
  // }(global_var);
#if defined(__GNUC__)
  int var3 = (({ ABSL_TEST_CHECK_LE(1, 2); }), global_var < 10) ? 1 : 0;
  (void)var3;
  int var4 = (({ ABSL_TEST_CHECK_STREQ("a", "a"); }), global_var < 10) ? 1 : 0;
  (void)var4;
#endif  // __GNUC__
#endif  // ABSL_INTERNAL_CPLUSPLUS_LANG
}
References ABSL_TEST_CHECK_EQ, ABSL_TEST_CHECK_GT, ABSL_TEST_CHECK_LE, ABSL_TEST_CHECK_NE, ABSL_TEST_CHECK_STRCASEEQ, ABSL_TEST_CHECK_STREQ, ABSL_TEST_CHECK_STRNE, and i.
TEST() [8/18]
absl_log_internal::TEST (CHECKTest , TestDCHECK)
Definition at line 378 of file check_test_impl.h.
{
#ifdef NDEBUG
  ABSL_TEST_DCHECK(1 == 2) << " DCHECK's shouldn't be compiled in normal mode";
#endif
  ABSL_TEST_DCHECK(1 == 1);  // NOLINT(readability/check)
  ABSL_TEST_DCHECK_EQ(1, 1);
  ABSL_TEST_DCHECK_NE(1, 2);
  ABSL_TEST_DCHECK_GE(1, 1);
  ABSL_TEST_DCHECK_GE(2, 1);
  ABSL_TEST_DCHECK_LE(1, 1);
  ABSL_TEST_DCHECK_LE(1, 2);
  ABSL_TEST_DCHECK_GT(2, 1);
  ABSL_TEST_DCHECK_LT(1, 2);
  // Test DCHECK on std::nullptr_t
  const void* p_null = nullptr;
  const void* p_not_null = &p_null;
  ABSL_TEST_DCHECK_EQ(p_null, nullptr);
  ABSL_TEST_DCHECK_EQ(nullptr, p_null);
  ABSL_TEST_DCHECK_NE(p_not_null, nullptr);
  ABSL_TEST_DCHECK_NE(nullptr, p_not_null);
}
References ABSL_TEST_DCHECK, ABSL_TEST_DCHECK_EQ, ABSL_TEST_DCHECK_GE, ABSL_TEST_DCHECK_GT, ABSL_TEST_DCHECK_LE, ABSL_TEST_DCHECK_LT, and ABSL_TEST_DCHECK_NE.
TEST() [9/18]
absl_log_internal::TEST (CHECKTest , TestLogicExpressions)
Definition at line 59 of file check_test_impl.h.
{
  int i = 5;
  ABSL_TEST_CHECK(i > 0 && i < 10);
  ABSL_TEST_CHECK(i < 0 || i > 3);
}
References ABSL_TEST_CHECK, and i.
TEST() [10/18]
absl_log_internal::TEST (CHECKTest , TestPassingMacroExpansion)
Definition at line 133 of file check_test_impl.h.
{
  ABSL_TEST_CHECK(IDENTITY(true));
  ABSL_TEST_CHECK_EQ(TEMPLATE_SUM(MACRO_ONE, 2), 3);
  ABSL_TEST_CHECK_STREQ(CONCAT("x", "y"), "xy");
}
References ABSL_TEST_CHECK, ABSL_TEST_CHECK_EQ, ABSL_TEST_CHECK_STREQ, CONCAT, IDENTITY, MACRO_ONE, and TEMPLATE_SUM.
TEST() [11/18]
absl_log_internal::TEST (CHECKTest , TestPlacementsInCompoundStatements)
Definition at line 77 of file check_test_impl.h.
{
  // check placement inside if/else clauses
  if (true) ABSL_TEST_CHECK(true);
  if (false)
    ;  // NOLINT
  else
    ABSL_TEST_CHECK(true);
  switch (0)
  case 0:
    ABSL_TEST_CHECK(true);  // NOLINT
#if ABSL_INTERNAL_CPLUSPLUS_LANG >= 201703L
  constexpr auto var = [](int i) {
    ABSL_TEST_CHECK(i > 0);  // NOLINT
    return i + 1;
  }(global_var);
  (void)var;
#endif  // ABSL_INTERNAL_CPLUSPLUS_LANG
}
References ABSL_TEST_CHECK, and i.
TEST() [12/18]
absl_log_internal::TEST (CHECKTest , TestQCHECK)
Definition at line 401 of file check_test_impl.h.
{
  // The tests that QCHECK does the same as CHECK
  ABSL_TEST_QCHECK(1 == 1);  // NOLINT(readability/check)
  ABSL_TEST_QCHECK_EQ(1, 1);
  ABSL_TEST_QCHECK_NE(1, 2);
  ABSL_TEST_QCHECK_GE(1, 1);
  ABSL_TEST_QCHECK_GE(2, 1);
  ABSL_TEST_QCHECK_LE(1, 1);
  ABSL_TEST_QCHECK_LE(1, 2);
  ABSL_TEST_QCHECK_GT(2, 1);
  ABSL_TEST_QCHECK_LT(1, 2);
  // Tests using QCHECK*() on anonymous enums.
  ABSL_TEST_QCHECK_EQ(CASE_A, CASE_A);
  ABSL_TEST_QCHECK_NE(CASE_A, CASE_B);
  ABSL_TEST_QCHECK_GE(CASE_A, CASE_A);
  ABSL_TEST_QCHECK_GE(CASE_B, CASE_A);
  ABSL_TEST_QCHECK_LE(CASE_A, CASE_A);
  ABSL_TEST_QCHECK_LE(CASE_A, CASE_B);
  ABSL_TEST_QCHECK_GT(CASE_B, CASE_A);
  ABSL_TEST_QCHECK_LT(CASE_A, CASE_B);
}
References ABSL_TEST_QCHECK, ABSL_TEST_QCHECK_EQ, ABSL_TEST_QCHECK_GE, ABSL_TEST_QCHECK_GT, ABSL_TEST_QCHECK_LE, ABSL_TEST_QCHECK_LT, ABSL_TEST_QCHECK_NE, CASE_A, and CASE_B.
TEST() [13/18]
absl_log_internal::TEST (CHECKTest , TestQCHECKPlacementsInCompoundStatements)
Definition at line 424 of file check_test_impl.h.
{
  // check placement inside if/else clauses
  if (true) ABSL_TEST_QCHECK(true);
  if (false)
    ;  // NOLINT
  else
    ABSL_TEST_QCHECK(true);
  if (false)
    ;  // NOLINT
  else
    ABSL_TEST_QCHECK(true);
  switch (0)
  case 0:
    ABSL_TEST_QCHECK(true);
#if ABSL_INTERNAL_CPLUSPLUS_LANG >= 201703L
  constexpr auto var = [](int i) {
    ABSL_TEST_QCHECK(i > 0);  // NOLINT
    return i + 1;
  }(global_var);
  (void)var;
#if defined(__GNUC__)
  int var2 = (({ ABSL_TEST_CHECK_LE(1, 2); }), global_var < 10) ? 1 : 0;
  (void)var2;
#endif  // __GNUC__
#endif  // ABSL_INTERNAL_CPLUSPLUS_LANG
}
References ABSL_TEST_CHECK_LE, ABSL_TEST_QCHECK, and i.
TEST() [14/18]
absl_log_internal::TEST (CHECKTest , TestSTREQ)
Definition at line 318 of file check_test_impl.h.
{
  ABSL_TEST_CHECK_STREQ("this", "this");
  ABSL_TEST_CHECK_STREQ(nullptr, nullptr);
  ABSL_TEST_CHECK_STRCASEEQ("this", "tHiS");
  ABSL_TEST_CHECK_STRCASEEQ(nullptr, nullptr);
  ABSL_TEST_CHECK_STRNE("this", "tHiS");
  ABSL_TEST_CHECK_STRNE("this", nullptr);
  ABSL_TEST_CHECK_STRCASENE("this", "that");
  ABSL_TEST_CHECK_STRCASENE(nullptr, "that");
  ABSL_TEST_CHECK_STREQ((std::string("a") + "b").c_str(), "ab");
  ABSL_TEST_CHECK_STREQ(std::string("test").c_str(),
                        (std::string("te") + std::string("st")).c_str());
}
References ABSL_TEST_CHECK_STRCASEEQ, ABSL_TEST_CHECK_STRCASENE, ABSL_TEST_CHECK_STREQ, and ABSL_TEST_CHECK_STRNE.
TEST() [15/18]
absl_log_internal::TEST (CHECKTest , TestUserDefinedCompOp)
Definition at line 500 of file check_test_impl.h.
{
  ABSL_TEST_CHECK_EQ(ComparableType{0}, ComparableType{0});
  ABSL_TEST_CHECK_NE(ComparableType{1}, ComparableType{2});
  ABSL_TEST_CHECK_LT(ComparableType{1}, ComparableType{2});
  ABSL_TEST_CHECK_LE(ComparableType{1}, ComparableType{2});
  ABSL_TEST_CHECK_GT(ComparableType{2}, ComparableType{1});
  ABSL_TEST_CHECK_GE(ComparableType{2}, ComparableType{2});
}
References ABSL_TEST_CHECK_EQ, ABSL_TEST_CHECK_GE, ABSL_TEST_CHECK_GT, ABSL_TEST_CHECK_LE, ABSL_TEST_CHECK_LT, and ABSL_TEST_CHECK_NE.
TEST() [16/18]
absl_log_internal::TEST (ErrnoPreservationTest , AfterStatement)
Definition at line 426 of file log_basic_test_impl.h.
{
  errno = 77;
  ABSL_TEST_LOG(INFO);
  const int saved_errno = errno;
  EXPECT_THAT(saved_errno, Eq(77));
}
References ABSL_TEST_LOG, and INFO.
TEST() [17/18]
absl_log_internal::TEST (ErrnoPreservationTest , InSeverityExpression)
Definition at line 407 of file log_basic_test_impl.h.
{
  errno = 77;
  int saved_errno;
  ABSL_TEST_LOG(LEVEL((saved_errno = errno, absl::LogSeverity::kInfo)));
  EXPECT_THAT(saved_errno, Eq(77));
}
References ABSL_TEST_LOG, and absl::kInfo.
TEST() [18/18]
absl_log_internal::TEST (ErrnoPreservationTest , InStreamedExpression)
Definition at line 414 of file log_basic_test_impl.h.
{
  if (!LoggingEnabledAt(absl::LogSeverity::kInfo)) {
    GTEST_SKIP() << "This test cases required INFO log to be enabled";
    return;
  }
  errno = 77;
  int saved_errno = 0;
  ABSL_TEST_LOG(INFO) << (saved_errno = errno, "hello world");
  EXPECT_THAT(saved_errno, Eq(77));
}
References ABSL_TEST_LOG, INFO, and absl::kInfo.
TEST_P() [1/6]
absl_log_internal::TEST_P (BasicLogTest , Error)
Definition at line 143 of file log_basic_test_impl.h.
{
  absl::log_internal::ScopedMinLogLevel scoped_min_log_level(GetParam());
  absl::ScopedMockLog test_sink(absl::MockLogDefault::kDisallowUnexpected);
  const int log_line = __LINE__ + 1;
  auto do_log = [] { ABSL_TEST_LOG(ERROR) << "hello world"; };
  if (LoggingEnabledAt(absl::LogSeverity::kError)) {
    EXPECT_CALL(
        test_sink,
        Send(AllOf(SourceFilename(Eq(__FILE__)),
                   SourceBasename(Eq("log_basic_test_impl.h")),
                   SourceLine(Eq(log_line)), Prefix(IsTrue()),
                   LogSeverity(Eq(absl::LogSeverity::kError)),
                   TimestampInMatchWindow(),
                   ThreadID(Eq(absl::base_internal::GetTID())),
                   TextMessage(Eq("hello world")),
                   Verbosity(Eq(absl::LogEntry::kNoVerbosityLevel)),
                   ENCODED_MESSAGE(EqualsProto(R"pb(value {
                                                      literal: "hello world"
                                                    })pb")),
                   Stacktrace(IsEmpty()))));
  }
  test_sink.StartCapturingLogs();
  do_log();
}
References ABSL_TEST_LOG, ENCODED_MESSAGE, absl::base_internal::GetTID(), absl::kDisallowUnexpected, absl::kError, absl::LogEntry::kNoVerbosityLevel, and absl::ScopedMockLog::StartCapturingLogs().
TEST_P() [2/6]
absl_log_internal::TEST_P (BasicLogTest , Info)
Definition at line 85 of file log_basic_test_impl.h.
{
  absl::log_internal::ScopedMinLogLevel scoped_min_log_level(GetParam());
  absl::ScopedMockLog test_sink(absl::MockLogDefault::kDisallowUnexpected);
  const int log_line = __LINE__ + 1;
  auto do_log = [] { ABSL_TEST_LOG(INFO) << "hello world"; };
  if (LoggingEnabledAt(absl::LogSeverity::kInfo)) {
    EXPECT_CALL(
        test_sink,
        Send(AllOf(SourceFilename(Eq(__FILE__)),
                   SourceBasename(Eq("log_basic_test_impl.h")),
                   SourceLine(Eq(log_line)), Prefix(IsTrue()),
                   LogSeverity(Eq(absl::LogSeverity::kInfo)),
                   TimestampInMatchWindow(),
                   ThreadID(Eq(absl::base_internal::GetTID())),
                   TextMessage(Eq("hello world")),
                   Verbosity(Eq(absl::LogEntry::kNoVerbosityLevel)),
                   ENCODED_MESSAGE(EqualsProto(R"pb(value {
                                                      literal: "hello world"
                                                    })pb")),
                   Stacktrace(IsEmpty()))));
  }
  test_sink.StartCapturingLogs();
  do_log();
}
References ABSL_TEST_LOG, ENCODED_MESSAGE, absl::base_internal::GetTID(), INFO, absl::kDisallowUnexpected, absl::kInfo, absl::LogEntry::kNoVerbosityLevel, and absl::ScopedMockLog::StartCapturingLogs().
TEST_P() [3/6]
absl_log_internal::TEST_P (BasicLogTest , Level)
Definition at line 280 of file log_basic_test_impl.h.
{
  absl::log_internal::ScopedMinLogLevel scoped_min_log_level(GetParam());
  for (auto severity : {absl::LogSeverity::kInfo, absl::LogSeverity::kWarning,
                        absl::LogSeverity::kError}) {
    absl::ScopedMockLog test_sink(absl::MockLogDefault::kDisallowUnexpected);
    const int log_line = __LINE__ + 2;
    auto do_log = [severity] {
      ABSL_TEST_LOG(LEVEL(severity)) << "hello world";
    };
    if (LoggingEnabledAt(severity)) {
      EXPECT_CALL(
          test_sink,
          Send(AllOf(SourceFilename(Eq(__FILE__)),
                     SourceBasename(Eq("log_basic_test_impl.h")),
                     SourceLine(Eq(log_line)), Prefix(IsTrue()),
                     LogSeverity(Eq(severity)), TimestampInMatchWindow(),
                     ThreadID(Eq(absl::base_internal::GetTID())),
                     TextMessage(Eq("hello world")),
                     Verbosity(Eq(absl::LogEntry::kNoVerbosityLevel)),
                     ENCODED_MESSAGE(EqualsProto(R"pb(value {
                                                        literal: "hello world"
                                                      })pb")),
                     Stacktrace(IsEmpty()))));
    }
    test_sink.StartCapturingLogs();
    do_log();
  }
}
References ABSL_TEST_LOG, ENCODED_MESSAGE, absl::base_internal::GetTID(), absl::kDisallowUnexpected, absl::kError, absl::kInfo, absl::LogEntry::kNoVerbosityLevel, absl::kWarning, and absl::ScopedMockLog::StartCapturingLogs().
TEST_P() [4/6]
absl_log_internal::TEST_P (BasicLogTest , LevelClampsLargeValues)
Definition at line 390 of file log_basic_test_impl.h.
{
  absl::log_internal::ScopedMinLogLevel scoped_min_log_level(GetParam());
  if (!LoggingEnabledAt(absl::LogSeverity::kError)) {
    GTEST_SKIP() << "This test cases required ERROR log to be enabled";
    return;
  }
  absl::ScopedMockLog test_sink(absl::MockLogDefault::kDisallowUnexpected);
  EXPECT_CALL(test_sink, Send(LogSeverity(Eq(absl::LogSeverity::kError))));
  test_sink.StartCapturingLogs();
  ABSL_TEST_LOG(LEVEL(static_cast<int>(absl::LogSeverity::kFatal) + 1))
      << "hello world";
}
References ABSL_TEST_LOG, absl::kDisallowUnexpected, absl::kError, absl::kFatal, and absl::ScopedMockLog::StartCapturingLogs().
TEST_P() [5/6]
absl_log_internal::TEST_P (BasicLogTest , LevelClampsNegativeValues)
Definition at line 374 of file log_basic_test_impl.h.
{
  absl::log_internal::ScopedMinLogLevel scoped_min_log_level(GetParam());
  if (!LoggingEnabledAt(absl::LogSeverity::kInfo)) {
    GTEST_SKIP() << "This test cases required INFO log to be enabled";
    return;
  }
  absl::ScopedMockLog test_sink(absl::MockLogDefault::kDisallowUnexpected);
  EXPECT_CALL(test_sink, Send(LogSeverity(Eq(absl::LogSeverity::kInfo))));
  test_sink.StartCapturingLogs();
  ABSL_TEST_LOG(LEVEL(-1)) << "hello world";
}
References ABSL_TEST_LOG, absl::kDisallowUnexpected, absl::kInfo, and absl::ScopedMockLog::StartCapturingLogs().
TEST_P() [6/6]
absl_log_internal::TEST_P (BasicLogTest , Warning)
Definition at line 114 of file log_basic_test_impl.h.
{
  absl::log_internal::ScopedMinLogLevel scoped_min_log_level(GetParam());
  absl::ScopedMockLog test_sink(absl::MockLogDefault::kDisallowUnexpected);
  const int log_line = __LINE__ + 1;
  auto do_log = [] { ABSL_TEST_LOG(WARNING) << "hello world"; };
  if (LoggingEnabledAt(absl::LogSeverity::kWarning)) {
    EXPECT_CALL(
        test_sink,
        Send(AllOf(SourceFilename(Eq(__FILE__)),
                   SourceBasename(Eq("log_basic_test_impl.h")),
                   SourceLine(Eq(log_line)), Prefix(IsTrue()),
                   LogSeverity(Eq(absl::LogSeverity::kWarning)),
                   TimestampInMatchWindow(),
                   ThreadID(Eq(absl::base_internal::GetTID())),
                   TextMessage(Eq("hello world")),
                   Verbosity(Eq(absl::LogEntry::kNoVerbosityLevel)),
                   ENCODED_MESSAGE(EqualsProto(R"pb(value {
                                                      literal: "hello world"
                                                    })pb")),
                   Stacktrace(IsEmpty()))));
  }
  test_sink.StartCapturingLogs();
  do_log();
}
References ABSL_TEST_LOG, ENCODED_MESSAGE, absl::base_internal::GetTID(), absl::kDisallowUnexpected, absl::LogEntry::kNoVerbosityLevel, absl::kWarning, and absl::ScopedMockLog::StartCapturingLogs().
ThresholdName()
std::string absl_log_internal::ThresholdName (testing::TestParamInfo< absl::LogSeverityAtLeast > severity)
Definition at line 69 of file log_basic_test_impl.h.
{
  std::stringstream ostr;
  ostr << severity.param;
  return ostr.str().substr(
      severity.param == absl::LogSeverityAtLeast::kInfinity ? 0 : 2);
}
References absl::kInfinity.
Variable Documentation
ABSL_ATTRIBUTE_UNUSED
auto* test_env absl_log_internal::ABSL_ATTRIBUTE_UNUSED
Initial value:
= ::testing::AddGlobalTestEnvironment(
    new absl::log_internal::LogTestEnvironment)
Definition at line 43 of file check_test_impl.h.