open spiel: absl::time_internal::cctz::detail::impl Namespace Reference
absl::time_internal::cctz::detail::impl Namespace Reference
Functions
CONSTEXPR_F bool is_leap_year (year_t y) noexcept
CONSTEXPR_F int year_index (year_t y, month_t m) noexcept
CONSTEXPR_F int days_per_century (int yi) noexcept
CONSTEXPR_F int days_per_4years (int yi) noexcept
CONSTEXPR_F int days_per_year (year_t y, month_t m) noexcept
CONSTEXPR_F int days_per_month (year_t y, month_t m) noexcept
CONSTEXPR_F fields n_day (year_t y, month_t m, diff_t d, diff_t cd, hour_t hh, minute_t mm, second_t ss) noexcept
CONSTEXPR_F fields n_mon (year_t y, diff_t m, diff_t d, diff_t cd, hour_t hh, minute_t mm, second_t ss) noexcept
CONSTEXPR_F fields n_hour (year_t y, diff_t m, diff_t d, diff_t cd, diff_t hh, minute_t mm, second_t ss) noexcept
CONSTEXPR_F fields n_min (year_t y, diff_t m, diff_t d, diff_t hh, diff_t ch, diff_t mm, second_t ss) noexcept
CONSTEXPR_F fields n_sec (year_t y, diff_t m, diff_t d, diff_t hh, diff_t mm, diff_t ss) noexcept
CONSTEXPR_F diff_t scale_add (diff_t v, diff_t f, diff_t a) noexcept
CONSTEXPR_F diff_t ymd_ord (year_t y, month_t m, day_t d) noexcept
CONSTEXPR_F diff_t day_difference (year_t y1, month_t m1, day_t d1, year_t y2, month_t m2, day_t d2) noexcept
template<typename H >
H AbslHashValueImpl (second_tag, H h, fields f)
template<typename H >
H AbslHashValueImpl (minute_tag, H h, fields f)
template<typename H >
H AbslHashValueImpl (hour_tag, H h, fields f)
template<typename H >
H AbslHashValueImpl (day_tag, H h, fields f)
template<typename H >
H AbslHashValueImpl (month_tag, H h, fields f)
template<typename H >
H AbslHashValueImpl (year_tag, H h, fields f)
Function Documentation
AbslHashValueImpl() [1/6]
template<typename H > H absl::time_internal::cctz::detail::impl::AbslHashValueImpl (day_tag , H h, fields f)
Definition at line 359 of file civil_time_detail.h.
{
  return H::combine(std::move(h), f.y, f.m, f.d);
}
References absl::f.
AbslHashValueImpl() [2/6]
template<typename H > H absl::time_internal::cctz::detail::impl::AbslHashValueImpl (hour_tag , H h, fields f)
Definition at line 355 of file civil_time_detail.h.
{
  return H::combine(std::move(h), f.y, f.m, f.d, f.hh);
}
References absl::f.
AbslHashValueImpl() [3/6]
template<typename H > H absl::time_internal::cctz::detail::impl::AbslHashValueImpl (minute_tag , H h, fields f)
Definition at line 351 of file civil_time_detail.h.
{
  return H::combine(std::move(h), f.y, f.m, f.d, f.hh, f.mm);
}
References absl::f.
AbslHashValueImpl() [4/6]
template<typename H > H absl::time_internal::cctz::detail::impl::AbslHashValueImpl (month_tag , H h, fields f)
Definition at line 363 of file civil_time_detail.h.
{
  return H::combine(std::move(h), f.y, f.m);
}
References absl::f.
AbslHashValueImpl() [5/6]
template<typename H > H absl::time_internal::cctz::detail::impl::AbslHashValueImpl (second_tag , H h, fields f)
Definition at line 347 of file civil_time_detail.h.
{
  return H::combine(std::move(h), f.y, f.m, f.d, f.hh, f.mm, f.ss);
}
References absl::f.
AbslHashValueImpl() [6/6]
template<typename H > H absl::time_internal::cctz::detail::impl::AbslHashValueImpl (year_tag , H h, fields f)
Definition at line 367 of file civil_time_detail.h.
{
  return H::combine(std::move(h), f.y);
}
References absl::f.
day_difference()
CONSTEXPR_F diff_t absl::time_internal::cctz::detail::impl::day_difference (year_t y1, month_t m1, day_t d1, year_t y2, month_t m2, day_t d2) noexcept
Definition at line 284 of file civil_time_detail.h.
{
  const diff_t a_c4_off = y1 % 400;
  const diff_t b_c4_off = y2 % 400;
  diff_t c4_diff = (y1 - a_c4_off) - (y2 - b_c4_off);
  diff_t delta = ymd_ord(a_c4_off, m1, d1) - ymd_ord(b_c4_off, m2, d2);
  if (c4_diff > 0 && delta < 0) {
    delta += 2 * 146097;
    c4_diff -= 2 * 400;
  } else if (c4_diff < 0 && delta > 0) {
    delta -= 2 * 146097;
    c4_diff += 2 * 400;
  }
  return (c4_diff / 400 * 146097) + delta;
}
References ymd_ord().
Referenced by absl::time_internal::cctz::detail::difference().
days_per_4years()
CONSTEXPR_F int absl::time_internal::cctz::detail::impl::days_per_4years (int yi) noexcept
Definition at line 93 of file civil_time_detail.h.
{
  return 1460 + (yi == 0 || yi > 300 || (yi - 1) % 100 < 96);
}
Referenced by n_day().
days_per_century()
CONSTEXPR_F int absl::time_internal::cctz::detail::impl::days_per_century (int yi) noexcept
Definition at line 90 of file civil_time_detail.h.
{
  return 36524 + (yi == 0 || yi > 300);
}
Referenced by n_day().
days_per_month()
CONSTEXPR_F int absl::time_internal::cctz::detail::impl::days_per_month (year_t y, month_t m) noexcept
Definition at line 99 of file civil_time_detail.h.
{
  CONSTEXPR_D int k_days_per_month[1 + 12] = {
      -1, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31  // non leap year
  };
  return k_days_per_month[m] + (m == 2 && is_leap_year(y));
}
References CONSTEXPR_D, is_leap_year(), and y.
Referenced by n_day().
days_per_year()
CONSTEXPR_F int absl::time_internal::cctz::detail::impl::days_per_year (year_t y, month_t m) noexcept
Definition at line 96 of file civil_time_detail.h.
{
  return is_leap_year(y + (m > 2)) ? 366 : 365;
}
References is_leap_year(), and y.
Referenced by n_day().
is_leap_year()
CONSTEXPR_F bool absl::time_internal::cctz::detail::impl::is_leap_year (year_t y) noexcept
Definition at line 83 of file civil_time_detail.h.
{
  return y % 4 == 0 && (y % 100 != 0 || y % 400 == 0);
}
References y.
Referenced by days_per_month(), days_per_year(), and absl::time_internal::cctz::detail::get_yearday().
n_day()
CONSTEXPR_F fields absl::time_internal::cctz::detail::impl::n_day (year_t y, month_t m, diff_t d, diff_t cd, hour_t hh, minute_t mm, second_t ss) noexcept
Definition at line 106 of file civil_time_detail.h.
{
  year_t ey = y % 400;
  const year_t oey = ey;
  ey += (cd / 146097) * 400;
  cd %= 146097;
  if (cd < 0) {
    ey -= 400;
    cd += 146097;
  }
  ey += (d / 146097) * 400;
  d = d % 146097 + cd;
  if (d > 0) {
    if (d > 146097) {
      ey += 400;
      d -= 146097;
    }
  } else {
    if (d > -365) {
      // We often hit the previous year when stepping a civil time backwards,
      // so special case it to avoid counting up by 100/4/1-year chunks.
      ey -= 1;
      d += days_per_year(ey, m);
    } else {
      ey -= 400;
      d += 146097;
    }
  }
  if (d > 365) {
    int yi = year_index(ey, m);  // Index into Gregorian 400 year cycle.
    for (;;) {
      int n = days_per_century(yi);
      if (d <= n) break;
      d -= n;
      ey += 100;
      yi += 100;
      if (yi >= 400) yi -= 400;
    }
    for (;;) {
      int n = days_per_4years(yi);
      if (d <= n) break;
      d -= n;
      ey += 4;
      yi += 4;
      if (yi >= 400) yi -= 400;
    }
    for (;;) {
      int n = days_per_year(ey, m);
      if (d <= n) break;
      d -= n;
      ++ey;
    }
  }
  if (d > 28) {
    for (;;) {
      int n = days_per_month(ey, m);
      if (d <= n) break;
      d -= n;
      if (++m > 12) {
        ++ey;
        m = 1;
      }
    }
  }
  return fields(y + (ey - oey), m, static_cast<day_t>(d), hh, mm, ss);
}
References absl::d, days_per_4years(), days_per_century(), days_per_month(), days_per_year(), absl::n, y, and year_index().
Referenced by n_mon(), and absl::time_internal::cctz::detail::step().
n_hour()
CONSTEXPR_F fields absl::time_internal::cctz::detail::impl::n_hour (year_t y, diff_t m, diff_t d, diff_t cd, diff_t hh, minute_t mm, second_t ss) noexcept
Definition at line 184 of file civil_time_detail.h.
{
  cd += hh / 24;
  hh %= 24;
  if (hh < 0) {
    cd -= 1;
    hh += 24;
  }
  return n_mon(y, m, d, cd, static_cast<hour_t>(hh), mm, ss);
}
References absl::d, n_mon(), and y.
Referenced by n_min(), n_sec(), and absl::time_internal::cctz::detail::step().
n_min()
CONSTEXPR_F fields absl::time_internal::cctz::detail::impl::n_min (year_t y, diff_t m, diff_t d, diff_t hh, diff_t ch, diff_t mm, second_t ss) noexcept
Definition at line 194 of file civil_time_detail.h.
{
  ch += mm / 60;
  mm %= 60;
  if (mm < 0) {
    ch -= 1;
    mm += 60;
  }
  return n_hour(y, m, d, hh / 24 + ch / 24, hh % 24 + ch % 24,
                static_cast<minute_t>(mm), ss);
}
References absl::d, n_hour(), and y.
Referenced by n_sec(), and absl::time_internal::cctz::detail::step().
n_mon()
CONSTEXPR_F fields absl::time_internal::cctz::detail::impl::n_mon (year_t y, diff_t m, diff_t d, diff_t cd, hour_t hh, minute_t mm, second_t ss) noexcept
Definition at line 172 of file civil_time_detail.h.
{
  if (m != 12) {
    y += m / 12;
    m %= 12;
    if (m <= 0) {
      y -= 1;
      m += 12;
    }
  }
  return n_day(y, static_cast<month_t>(m), d, cd, hh, mm, ss);
}
References absl::d, n_day(), and y.
Referenced by n_hour(), n_sec(), and absl::time_internal::cctz::detail::step().
n_sec()
CONSTEXPR_F fields absl::time_internal::cctz::detail::impl::n_sec (year_t y, diff_t m, diff_t d, diff_t hh, diff_t mm, diff_t ss) noexcept
Definition at line 205 of file civil_time_detail.h.
{
  // Optimization for when (non-constexpr) fields are already normalized.
  if (0 <= ss && ss < 60) {
    const second_t nss = static_cast<second_t>(ss);
    if (0 <= mm && mm < 60) {
      const minute_t nmm = static_cast<minute_t>(mm);
      if (0 <= hh && hh < 24) {
        const hour_t nhh = static_cast<hour_t>(hh);
        if (1 <= d && d <= 28 && 1 <= m && m <= 12) {
          const day_t nd = static_cast<day_t>(d);
          const month_t nm = static_cast<month_t>(m);
          return fields(y, nm, nd, nhh, nmm, nss);
        }
        return n_mon(y, m, d, 0, nhh, nmm, nss);
      }
      return n_hour(y, m, d, hh / 24, hh % 24, nmm, nss);
    }
    return n_min(y, m, d, hh, mm / 60, mm % 60, nss);
  }
  diff_t cm = ss / 60;
  ss %= 60;
  if (ss < 0) {
    cm -= 1;
    ss += 60;
  }
  return n_min(y, m, d, hh, mm / 60 + cm / 60, mm % 60 + cm % 60,
               static_cast<second_t>(ss));
}
References absl::d, n_hour(), n_min(), n_mon(), and y.
Referenced by absl::time_internal::cctz::detail::step().
scale_add()
CONSTEXPR_F diff_t absl::time_internal::cctz::detail::impl::scale_add (diff_t v, diff_t f, diff_t a) noexcept
Definition at line 264 of file civil_time_detail.h.
{
  return (v < 0) ? ((v + 1) * f + a) - f : ((v - 1) * f + a) + f;
}
References absl::a, absl::f, and absl::v.
Referenced by absl::time_internal::cctz::detail::difference(), absl::time_internal::cctz::detail::difference(), absl::time_internal::cctz::detail::difference(), and absl::time_internal::cctz::detail::difference().
year_index()
CONSTEXPR_F int absl::time_internal::cctz::detail::impl::year_index (year_t y, month_t m) noexcept
Definition at line 86 of file civil_time_detail.h.
{
  const int yi = static_cast<int>((y + (m > 2)) % 400);
  return yi < 0 ? yi + 400 : yi;
}
References y.
Referenced by n_day().
ymd_ord()
CONSTEXPR_F diff_t absl::time_internal::cctz::detail::impl::ymd_ord (year_t y, month_t m, day_t d) noexcept
Definition at line 270 of file civil_time_detail.h.
{
  const diff_t eyear = (m <= 2) ? y - 1 : y;
  const diff_t era = (eyear >= 0 ? eyear : eyear - 399) / 400;
  const diff_t yoe = eyear - era * 400;
  const diff_t doy = (153 * (m + (m > 2 ? -3 : 9)) + 2) / 5 + d - 1;
  const diff_t doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
  return era * 146097 + doe - 719468;
}
References absl::d, and y.
Referenced by day_difference().