open spiel: absl::random_internal_nanobenchmark Namespace Reference
absl::random_internal_nanobenchmark Namespace Reference
Namespaces
namespace platform
namespace robust_statistics
namespace timer
Classes
struct Params
struct Result
Typedefs
using FuncInput = size_t
using FuncOutput = uint64_t
using Func = FuncOutput (*)(const void*, FuncInput)
Functions
void PinThreadToCPU (int cpu)
double InvariantTicksPerSecond ()
size_t MeasureImpl (const Func func, const void *arg, const size_t num_skip, const InputVec &unique, const InputVec &full, const Params &p, Result *results)
size_t Measure (const Func func, const void *arg, const FuncInput *inputs, const size_t num_inputs, Result *results, const Params &p)
Typedef Documentation
Func
using absl::random_internal_nanobenchmark::Func = FuncOutput (*)(const void*, FuncInput)
Definition at line 68 of file nanobenchmark.h.
FuncInput
using absl::random_internal_nanobenchmark::FuncInput = size_t
Definition at line 60 of file nanobenchmark.h.
FuncOutput
using absl::random_internal_nanobenchmark::FuncOutput = uint64_t
Definition at line 63 of file nanobenchmark.h.
Function Documentation
InvariantTicksPerSecond()
double absl::random_internal_nanobenchmark::InvariantTicksPerSecond ()
Definition at line 727 of file nanobenchmark.cc.
{
#if defined(ABSL_ARCH_PPC)
  return __ppc_get_timebase_freq();
#elif defined(ABSL_ARCH_X86_64)
  // We assume the TSC is invariant; it is on all recent Intel/AMD CPUs.
  return platform::NominalClockRate();
#else
  // Fall back to clock_gettime nanoseconds.
  return 1E9;
#endif
}
Measure()
size_t absl::random_internal_nanobenchmark::Measure (const Func func, const void * arg, const FuncInput * inputs, const size_t num_inputs, Result * results, const Params & p)
Definition at line 780 of file nanobenchmark.cc.
{
  ABSL_RAW_CHECK(num_inputs != 0, "No inputs");
  const InputVec unique = UniqueInputs(inputs, num_inputs);
  const size_t num_skip = NumSkip(func, arg, unique, p);  // never 0
  if (num_skip == 0) return 0;  // NumSkip already printed error message
  const InputVec full =
      ReplicateInputs(inputs, num_inputs, unique.size(), num_skip, p);
  // MeasureImpl may fail up to p.max_measure_retries times.
  for (size_t i = 0; i < p.max_measure_retries; i++) {
    auto result = MeasureImpl(func, arg, num_skip, unique, full, p, results);
    if (result != 0) {
      return result;
    }
  }
  // All retries failed. (Unusual)
  return 0;
}
References ABSL_RAW_CHECK, arg, absl::i, Measure(), MeasureImpl(), and absl::p.
Referenced by Measure().
MeasureImpl()
size_t absl::random_internal_nanobenchmark::MeasureImpl (const Func func, const void * arg, const size_t num_skip, const InputVec & unique, const InputVec & full, const Params & p, Result * results)
Definition at line 739 of file nanobenchmark.cc.
{
  const float mul = 1.0f / static_cast<int>(num_skip);
  InputVec subset(full.size() - num_skip);
  const Ticks overhead = Overhead(arg, &full, p);
  const Ticks overhead_skip = Overhead(arg, &subset, p);
  if (overhead < overhead_skip) {
    ABSL_RAW_LOG(WARNING, "Measurement failed: overhead %u < %u\n", overhead,
                 overhead_skip);
    return 0;
  }
  if (p.verbose) {
    ABSL_RAW_LOG(INFO, "#inputs=%5zu,%5zu overhead=%5u,%5u\n", full.size(),
                 subset.size(), overhead, overhead_skip);
  }
  double max_rel_mad = 0.0;
  const Ticks total = TotalDuration(func, arg, &full, p, &max_rel_mad);
  for (size_t i = 0; i < unique.size(); ++i) {
    FillSubset(full, unique[i], num_skip, &subset);
    const Ticks total_skip = TotalDuration(func, arg, &subset, p, &max_rel_mad);
    if (total < total_skip) {
      ABSL_RAW_LOG(WARNING, "Measurement failed: total %u < %u\n", total,
                   total_skip);
      return 0;
    }
    const Ticks duration = (total - overhead) - (total_skip - overhead_skip);
    results[i].input = unique[i];
    results[i].ticks = duration * mul;
    results[i].variability = max_rel_mad;
  }
  return unique.size();
}
References ABSL_RAW_LOG, arg, absl::i, INFO, absl::random_internal_nanobenchmark::Result::input, MeasureImpl(), absl::p, absl::random_internal_nanobenchmark::Result::ticks, total, and absl::random_internal_nanobenchmark::Result::variability.
Referenced by Measure(), and MeasureImpl().
PinThreadToCPU()
void absl::random_internal_nanobenchmark::PinThreadToCPU (int cpu)
Definition at line 691 of file nanobenchmark.cc.
{
  // We might migrate to another CPU before pinning below, but at least cpu
  // will be one of the CPUs on which this thread ran.
#if defined(ABSL_OS_WIN)
  if (cpu < 0) {
    cpu = static_cast<int>(GetCurrentProcessorNumber());
    ABSL_RAW_CHECK(cpu >= 0, "PinThreadToCPU detect failed");
    if (cpu >= 64) {
      // NOTE: On wine, at least, GetCurrentProcessorNumber() sometimes returns
      // a value > 64, which is out of range. When this happens, log a message
      // and don't set a cpu affinity.
      ABSL_RAW_LOG(ERROR, "Invalid CPU number: %d", cpu);
      return;
    }
  } else if (cpu >= 64) {
    // User specified an explicit CPU affinity > the valid range.
    ABSL_RAW_LOG(FATAL, "Invalid CPU number: %d", cpu);
  }
  const DWORD_PTR prev = SetThreadAffinityMask(GetCurrentThread(), 1ULL << cpu);
  ABSL_RAW_CHECK(prev != 0, "SetAffinity failed");
#elif defined(ABSL_OS_LINUX) && !defined(ABSL_OS_ANDROID)
  if (cpu < 0) {
    cpu = sched_getcpu();
    ABSL_RAW_CHECK(cpu >= 0, "PinThreadToCPU detect failed");
  }
  const pid_t pid = 0;  // current thread
  cpu_set_t set;
  CPU_ZERO(&set);
  CPU_SET(cpu, &set);
  const int err = sched_setaffinity(pid, sizeof(set), &set);
  ABSL_RAW_CHECK(err == 0, "SetAffinity failed");
#endif
}
References ABSL_RAW_CHECK, and ABSL_RAW_LOG.