open spiel: absl::flags_internal Namespace Reference
absl::flags_internal Namespace Reference
Classes
struct BestHints
struct DynValueDeleter
struct EmptyBraces
struct FixedCharArray
class Flag
struct FlagCallback
struct FlagDefaultArg
union FlagDefaultSrc
struct FlagHelpArg
union FlagHelpMsg
class FlagImpl
class FlagImplPeer
struct FlagOneWordValue
class FlagRegistrar
struct FlagRegistrarEmpty
class FlagRegistry
class FlagSaverImpl
class FlagState
class FlagStateInterface
struct FlagValue
struct FlagValue< T, FlagValueStorageKind::kAlignedBuffer >
struct FlagValue< T, FlagValueStorageKind::kOneWordAtomic >
struct FlagValue< T, FlagValueStorageKind::kSequenceLocked >
struct FlagValue< T, FlagValueStorageKind::kValueAndInitBit >
struct FlagValueAndInitBit
class PrivateHandleAccessor
class RetiredFlag
class SequenceLock
Typedefs
using FlagFastTypeId = absl::base_internal::FastTypeIdType
using FlagOpFn = void* (*)(FlagOp, const void*, void*, void*)
using HelpGenFunc = std::string (*)()
using FlagDfltGenFunc = void (*)(void*)
template<typename T >
using FlagUseValueAndInitBitStorage
template<typename T >
using FlagUseOneWordStorage
template<class T >
using FlagUseSequenceLockStorage
using FlagCallbackFunc = void (*)()
using FlagKindFilter = std::function<bool (absl::string_view)>
Enumerations
enum FlagSettingMode { SET_FLAGS_VALUE , SET_FLAG_IF_DEFAULT , SET_FLAGS_DEFAULT }
enum ValueSource { kCommandLine , kProgrammaticChange }
enum class FlagOp {
kAlloc , kDelete , kCopy , kCopyConstruct ,
kSizeof , kFastTypeId , kRuntimeTypeId , kParse ,
kUnparse , kValueOffset
}
enum class FlagHelpKind : uint8_t { kLiteral = 0 , kGenFunc = 1 }
enum class FlagDefaultKind : uint8_t { kDynamicValue = 0 , kGenFunc = 1 , kOneWord = 2 }
enum class FlagValueStorageKind : uint8_t { kValueAndInitBit = 0 , kOneWordAtomic = 1 , kSequenceLocked = 2 , kAlignedBuffer = 3 }
enum class ArgvListAction { kRemoveParsedArgs , kKeepParsedArgs }
enum class UsageFlagsAction { kHandleUsage , kIgnoreUsage }
enum class OnUndefinedFlag { kIgnoreUndefined , kReportUndefined , kAbortIfUndefined }
enum class HelpFormat { kHumanReadable }
enum class HelpMode {
kNone , kImportant , kShort , kFull ,
kPackage , kMatch , kVersion , kOnlyCheckArgs
}
Functions
template<typename T >
void * FlagOps (FlagOp op, const void *v1, void *v2, void *v3)
void * Alloc (FlagOpFn op)
void Delete (FlagOpFn op, void *obj)
void Copy (FlagOpFn op, const void *src, void *dst)
void CopyConstruct (FlagOpFn op, const void *src, void *dst)
void * Clone (FlagOpFn op, const void *obj)
bool Parse (FlagOpFn op, absl::string_view text, void *dst, std::string *error)
std::string Unparse (FlagOpFn op, const void *val)
size_t Sizeof (FlagOpFn op)
FlagFastTypeId FastTypeId (FlagOpFn op)
const std::type_info * RuntimeTypeId (FlagOpFn op)
ptrdiff_t ValueOffset (FlagOpFn op)
template<typename T >
const std::type_info * GenRuntimeTypeId ()
template<typename Gen , size_t N = Gen::Value().size()>
constexpr FixedCharArray< N+1 > HelpStringAsArray (int)
template<typename Gen >
constexpr std::false_type HelpStringAsArray (char)
template<typename Gen , size_t N>
constexpr FlagHelpArg HelpArg (const FixedCharArray< N > &value)
template<typename Gen >
constexpr FlagHelpArg HelpArg (std::false_type)
template<typename T >
constexpr T InitDefaultValue (T t)
template<typename T >
constexpr T InitDefaultValue (EmptyBraces)
template<typename ValueT , typename GenT , typename std::enable_if< std::is_integral< ValueT >::value, int >::type = ((void)GenT{}, 0)>
constexpr FlagDefaultArg DefaultArg (int)
template<typename ValueT , typename GenT >
constexpr FlagDefaultArg DefaultArg (char)
constexpr int64_t UninitializedFlagValue ()
std::vector< char * > ParseCommandLineImpl (int argc, char *argv[], ArgvListAction arg_list_act, UsageFlagsAction usage_flag_act, OnUndefinedFlag on_undef_flag)
bool WasPresentOnCommandLine (absl::string_view flag_name)
std::vector< std::string > GetMisspellingHints (absl::string_view flag)
absl::string_view Basename (absl::string_view filename)
absl::string_view Package (absl::string_view filename)
std::string ProgramInvocationName ()
std::string ShortProgramInvocationName ()
void SetProgramInvocationName (absl::string_view prog_name_str)
void ForEachFlag (std::function< void(CommandLineFlag &)> visitor)
bool RegisterCommandLineFlag (CommandLineFlag &, const char *filename)
void FinalizeRegistry ()
void Retire (const char *name, FlagFastTypeId type_id, char *buf)
constexpr size_t AlignUp (size_t x, size_t align)
void FlagHelp (std::ostream &out, const CommandLineFlag &flag, HelpFormat format)
void FlagsHelp (std::ostream &out, absl::string_view filter, HelpFormat format, absl::string_view program_usage_message)
int HandleUsageFlags (std::ostream &out, absl::string_view program_usage_message)
std::string GetFlagsHelpMatchSubstr ()
void SetFlagsHelpMatchSubstr (absl::string_view substr)
HelpMode GetFlagsHelpMode ()
void SetFlagsHelpMode (HelpMode mode)
HelpFormat GetFlagsHelpFormat ()
void SetFlagsHelpFormat (HelpFormat format)
bool DeduceUsageFlags (absl::string_view name, absl::string_view value)
bool AbslParseFlag (absl::string_view text, bool *dst, std::string *)
template<typename IntType >
bool ParseFlagImpl (absl::string_view text, IntType &dst)
bool AbslParseFlag (absl::string_view text, short *dst, std::string *)
bool AbslParseFlag (absl::string_view text, unsigned short *dst, std::string *)
bool AbslParseFlag (absl::string_view text, int *dst, std::string *)
bool AbslParseFlag (absl::string_view text, unsigned int *dst, std::string *)
bool AbslParseFlag (absl::string_view text, long *dst, std::string *)
bool AbslParseFlag (absl::string_view text, unsigned long *dst, std::string *)
bool AbslParseFlag (absl::string_view text, long long *dst, std::string *)
bool AbslParseFlag (absl::string_view text, unsigned long long *dst, std::string *)
bool AbslParseFlag (absl::string_view text, float *dst, std::string *)
bool AbslParseFlag (absl::string_view text, double *dst, std::string *)
bool AbslParseFlag (absl::string_view text, std::string *dst, std::string *)
bool AbslParseFlag (absl::string_view text, std::vector< std::string > *dst, std::string *)
std::string Unparse (bool v)
std::string Unparse (short v)
std::string Unparse (unsigned short v)
std::string Unparse (int v)
std::string Unparse (unsigned int v)
std::string Unparse (long v)
std::string Unparse (unsigned long v)
std::string Unparse (long long v)
std::string Unparse (unsigned long long v)
template<typename T >
std::string UnparseFloatingPointVal (T v)
std::string Unparse (float v)
std::string Unparse (double v)
std::string AbslUnparseFlag (absl::string_view v)
std::string AbslUnparseFlag (const std::vector< std::string > &v)
template<typename T >
bool AbslParseFlag (absl::string_view text, absl::optional< T > *f, std::string *err)
template<typename T >
bool InvokeParseFlag (absl::string_view input, T *dst, std::string *err)
template<typename T >
std::string AbslUnparseFlag (const absl::optional< T > &f)
template<typename T >
std::string Unparse (const T &v)
FlagsUsageConfig GetUsageConfig ()
void ReportUsageError (absl::string_view msg, bool is_fatal)
Variables
const char kStrippedFlagHelp [] = "\001\002\003\004 (unknown) \004\003\002\001"
constexpr size_t kRetiredFlagObjSize = 3 * sizeof(void*)
constexpr size_t kRetiredFlagObjAlignment = alignof(void*)
Typedef Documentation
FlagCallbackFunc
using absl::flags_internal::FlagCallbackFunc = void (*)()
Definition at line 412 of file flag.h.
FlagDfltGenFunc
using absl::flags_internal::FlagDfltGenFunc = void (*)(void*)
Definition at line 249 of file flag.h.
FlagFastTypeId
using absl::flags_internal::FlagFastTypeId = absl::base_internal::FastTypeIdType
Definition at line 31 of file commandlineflag.h.
FlagKindFilter
using absl::flags_internal::FlagKindFilter = std::function<bool (absl::string_view)>
Definition at line 61 of file usage_config.h.
FlagOpFn
using absl::flags_internal::FlagOpFn = void* (*)(FlagOp, const void*, void*, void*)
Definition at line 95 of file flag.h.
FlagUseOneWordStorage
template<typename T > using absl::flags_internal::FlagUseOneWordStorage
Initial value:
 std::integral_constant<
    bool, absl::type_traits_internal::is_trivially_copyable<T>::value &&
              (sizeof(T) <= 8)>
Definition at line 316 of file flag.h.
FlagUseSequenceLockStorage
template<class T > using absl::flags_internal::FlagUseSequenceLockStorage
Initial value:
 std::integral_constant<
    bool, absl::type_traits_internal::is_trivially_copyable<T>::value &&
              (sizeof(T) > 8)>
Definition at line 321 of file flag.h.
FlagUseValueAndInitBitStorage
template<typename T > using absl::flags_internal::FlagUseValueAndInitBitStorage
Initial value:
 std::integral_constant<
    bool, absl::type_traits_internal::is_trivially_copyable<T>::value &&
              std::is_default_constructible<T>::value && (sizeof(T) < 8)>
Definition at line 311 of file flag.h.
HelpGenFunc
using absl::flags_internal::HelpGenFunc = std::string (*)()
Definition at line 179 of file flag.h.
Enumeration Type Documentation
ArgvListAction
enum class absl::flags_internal::ArgvListAction strong
Enumerator
kRemoveParsedArgs
kKeepParsedArgs
Definition at line 35 of file parse.h.
{ kRemoveParsedArgs, kKeepParsedArgs };
FlagDefaultKind
enum class absl::flags_internal::FlagDefaultKind : uint8_t strong
Enumerator
kDynamicValue
kGenFunc
kOneWord
Definition at line 265 of file flag.h.
                           : uint8_t {
  kDynamicValue = 0,
  kGenFunc = 1,
  kOneWord = 2  // for default values UP to one word in size
};
FlagHelpKind
enum class absl::flags_internal::FlagHelpKind : uint8_t strong
Enumerator
kLiteral
kGenFunc
Definition at line 211 of file flag.h.
: uint8_t { kLiteral = 0, kGenFunc = 1 };
FlagOp
enum class absl::flags_internal::FlagOp strong
Enumerator
kAlloc
kDelete
kCopy
kCopyConstruct
kSizeof
kFastTypeId
kRuntimeTypeId
kParse
kUnparse
kValueOffset
Definition at line 83 of file flag.h.
                  {
  kAlloc,
  kDelete,
  kCopy,
  kCopyConstruct,
  kSizeof,
  kFastTypeId,
  kRuntimeTypeId,
  kParse,
  kUnparse,
  kValueOffset,
};
FlagSettingMode
enum absl::flags_internal::FlagSettingMode
Enumerator
SET_FLAGS_VALUE
SET_FLAG_IF_DEFAULT
SET_FLAGS_DEFAULT
Definition at line 34 of file commandlineflag.h.
                     {
  // update the flag's value unconditionally (can call this multiple times).
  SET_FLAGS_VALUE,
  // update the flag's value, but *only if* it has not yet been updated
  // with SET_FLAGS_VALUE, SET_FLAG_IF_DEFAULT, or "FLAGS_xxx = nondef".
  SET_FLAG_IF_DEFAULT,
  // set the flag's default value to this.  If the flag has not been updated
  // yet (via SET_FLAGS_VALUE, SET_FLAG_IF_DEFAULT, or "FLAGS_xxx = nondef")
  // change the flag's current value to the new default value as well.
  SET_FLAGS_DEFAULT
};
FlagValueStorageKind
enum class absl::flags_internal::FlagValueStorageKind : uint8_t strong
Enumerator
kValueAndInitBit
kOneWordAtomic
kSequenceLocked
kAlignedBuffer
Definition at line 325 of file flag.h.
                                : uint8_t {
  kValueAndInitBit = 0,
  kOneWordAtomic = 1,
  kSequenceLocked = 2,
  kAlignedBuffer = 3,
};
HelpFormat
enum class absl::flags_internal::HelpFormat strong
Enumerator
kHumanReadable
Definition at line 35 of file usage.h.
                      {
  kHumanReadable,
};
HelpMode
enum class absl::flags_internal::HelpMode strong
Enumerator
kNone
kImportant
kShort
kFull
kPackage
kMatch
kVersion
kOnlyCheckArgs
Definition at line 72 of file usage.h.
                    {
  kNone,
  kImportant,
  kShort,
  kFull,
  kPackage,
  kMatch,
  kVersion,
  kOnlyCheckArgs
};
OnUndefinedFlag
enum class absl::flags_internal::OnUndefinedFlag strong
Enumerator
kIgnoreUndefined
kReportUndefined
kAbortIfUndefined
Definition at line 37 of file parse.h.
{
  kIgnoreUndefined,
  kReportUndefined,
  kAbortIfUndefined
};
UsageFlagsAction
enum class absl::flags_internal::UsageFlagsAction strong
Enumerator
kHandleUsage
kIgnoreUsage
Definition at line 36 of file parse.h.
{ kHandleUsage, kIgnoreUsage };
ValueSource
enum absl::flags_internal::ValueSource
Enumerator
kCommandLine
kProgrammaticChange
Definition at line 47 of file commandlineflag.h.
                 {
  // Flag is being set by value specified on a command line.
  kCommandLine,
  // Flag is being set by value specified in the code.
  kProgrammaticChange,
};
Function Documentation
AbslParseFlag() [1/14]
template<typename T > bool absl::flags_internal::AbslParseFlag (absl::string_view text, absl::optional< T > * f, std::string * err)
Definition at line 242 of file marshalling.h.
{
  if (text.empty()) {
    *f = absl::nullopt;
    return true;
  }
  T value;
  if (!absl::ParseFlag(text, &value, err)) return false;
  *f = std::move(value);
  return true;
}
References absl::f, absl::ParseFlag(), and value.
AbslParseFlag() [2/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, bool * dst, std::string *)
Definition at line 45 of file marshalling.cc.
{
  const char* kTrue[] = {"1", "t", "true", "y", "yes"};
  const char* kFalse[] = {"0", "f", "false", "n", "no"};
  static_assert(sizeof(kTrue) == sizeof(kFalse), "true_false_equal");
  text = absl::StripAsciiWhitespace(text);
  for (size_t i = 0; i < ABSL_ARRAYSIZE(kTrue); ++i) {
    if (absl::EqualsIgnoreCase(text, kTrue[i])) {
      *dst = true;
      return true;
    } else if (absl::EqualsIgnoreCase(text, kFalse[i])) {
      *dst = false;
      return true;
    }
  }
  return false;  // didn't match a legal input
}
References ABSL_ARRAYSIZE, absl::EqualsIgnoreCase(), absl::i, and absl::StripAsciiWhitespace().
Referenced by InvokeParseFlag().
AbslParseFlag() [3/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, double * dst, std::string *)
Definition at line 135 of file marshalling.cc.
{
  return absl::SimpleAtod(text, dst);
}
References absl::SimpleAtod().
AbslParseFlag() [4/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, float * dst, std::string *)
Definition at line 131 of file marshalling.cc.
{
  return absl::SimpleAtof(text, dst);
}
References absl::SimpleAtof().
AbslParseFlag() [5/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, int * dst, std::string *)
Definition at line 103 of file marshalling.cc.
{
  return ParseFlagImpl(text, *dst);
}
References ParseFlagImpl().
AbslParseFlag() [6/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, long * dst, std::string *)
Definition at line 111 of file marshalling.cc.
{
  return ParseFlagImpl(text, *dst);
}
References ParseFlagImpl().
AbslParseFlag() [7/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, long long * dst, std::string *)
Definition at line 119 of file marshalling.cc.
{
  return ParseFlagImpl(text, *dst);
}
References ParseFlagImpl().
AbslParseFlag() [8/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, short * dst, std::string *)
Definition at line 84 of file marshalling.cc.
{
  int val;
  if (!ParseFlagImpl(text, val)) return false;
  if (static_cast<short>(val) != val)  // worked, but number out of range
    return false;
  *dst = static_cast<short>(val);
  return true;
}
References ParseFlagImpl().
AbslParseFlag() [9/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, std::string * dst, std::string *)
Definition at line 142 of file marshalling.cc.
{
  dst->assign(text.data(), text.size());
  return true;
}
AbslParseFlag() [10/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, std::vector< std::string > * dst, std::string *)
Definition at line 150 of file marshalling.cc.
{
  // An empty flag value corresponds to an empty vector, not a vector
  // with a single, empty std::string.
  if (text.empty()) {
    dst->clear();
    return true;
  }
  *dst = absl::StrSplit(text, ',', absl::AllowEmpty());
  return true;
}
References absl::StrSplit().
AbslParseFlag() [11/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, unsigned int * dst, std::string *)
Definition at line 107 of file marshalling.cc.
{
  return ParseFlagImpl(text, *dst);
}
References ParseFlagImpl().
AbslParseFlag() [12/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, unsigned long * dst, std::string *)
Definition at line 115 of file marshalling.cc.
{
  return ParseFlagImpl(text, *dst);
}
References ParseFlagImpl().
AbslParseFlag() [13/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, unsigned long long * dst, std::string *)
Definition at line 123 of file marshalling.cc.
{
  return ParseFlagImpl(text, *dst);
}
References ParseFlagImpl().
AbslParseFlag() [14/14]
bool absl::flags_internal::AbslParseFlag (absl::string_view text, unsigned short * dst, std::string *)
Definition at line 93 of file marshalling.cc.
{
  unsigned int val;
  if (!ParseFlagImpl(text, val)) return false;
  if (static_cast<unsigned short>(val) !=
      val)  // worked, but number out of range
    return false;
  *dst = static_cast<unsigned short>(val);
  return true;
}
References ParseFlagImpl().
AbslUnparseFlag() [1/3]
std::string absl::flags_internal::AbslUnparseFlag (absl::string_view v)
Definition at line 195 of file marshalling.cc.
{ return std::string(v); }
References absl::v.
Referenced by Unparse().
AbslUnparseFlag() [2/3]
template<typename T > std::string absl::flags_internal::AbslUnparseFlag (const absl::optional< T > & f)
Definition at line 285 of file marshalling.h.
{
  return f.has_value() ? absl::UnparseFlag(*f) : "";
}
References absl::f, and absl::UnparseFlag().
AbslUnparseFlag() [3/3]
std::string absl::flags_internal::AbslUnparseFlag (const std::vector< std::string > & v)
Definition at line 196 of file marshalling.cc.
{
  return absl::StrJoin(v, ",");
}
References absl::StrJoin(), and absl::v.
AlignUp()
size_t absl::flags_internal::AlignUp (size_t x, size_t align) inline constexpr
Definition at line 33 of file sequence_lock.h.
{
  return align * ((x + align - 1) / align);
}
References absl::x.
Alloc()
void * absl::flags_internal::Alloc (FlagOpFn op) inline
Definition at line 102 of file flag.h.
{
  return op(FlagOp::kAlloc, nullptr, nullptr, nullptr);
}
References kAlloc.
Referenced by Clone().
Basename()
absl::string_view absl::flags_internal::Basename (absl::string_view filename) inline
Definition at line 34 of file path_util.h.
{
  auto last_slash_pos = filename.find_last_of("/\\");
  return last_slash_pos == absl::string_view::npos
             ? filename
             : filename.substr(last_slash_pos + 1);
}
References absl::string_view::find_last_of(), absl::string_view::npos, and absl::string_view::substr().
Referenced by ShortProgramInvocationName().
Clone()
void * absl::flags_internal::Clone (FlagOpFn op, const void * obj) inline
Definition at line 119 of file flag.h.
{
  void* res = flags_internal::Alloc(op);
  flags_internal::CopyConstruct(op, obj, res);
  return res;
}
References Alloc(), and CopyConstruct().
Referenced by absl::flags_internal::FlagImpl::Write().
Copy()
void absl::flags_internal::Copy (FlagOpFn op, const void * src, void * dst) inline
Definition at line 110 of file flag.h.
{
  op(FlagOp::kCopy, src, dst, nullptr);
}
References kCopy.
CopyConstruct()
void absl::flags_internal::CopyConstruct (FlagOpFn op, const void * src, void * dst) inline
Definition at line 115 of file flag.h.
{
  op(FlagOp::kCopyConstruct, src, dst, nullptr);
}
References kCopyConstruct.
Referenced by Clone(), and absl::flags_internal::FlagImpl::Read().
DeduceUsageFlags()
bool absl::flags_internal::DeduceUsageFlags (absl::string_view name, absl::string_view value)
Definition at line 469 of file usage.cc.
{
  if (absl::ConsumePrefix(&name, "help")) {
    if (name.empty()) {
      if (value.empty()) {
        SetFlagsHelpMode(HelpMode::kImportant);
      } else {
        SetFlagsHelpMode(HelpMode::kMatch);
        SetFlagsHelpMatchSubstr(value);
      }
      return true;
    }
    if (name == "match") {
      SetFlagsHelpMode(HelpMode::kMatch);
      SetFlagsHelpMatchSubstr(value);
      return true;
    }
    if (name == "on") {
      SetFlagsHelpMode(HelpMode::kMatch);
      SetFlagsHelpMatchSubstr(absl::StrCat("/", value, "."));
      return true;
    }
    if (name == "full") {
      SetFlagsHelpMode(HelpMode::kFull);
      return true;
    }
    if (name == "short") {
      SetFlagsHelpMode(HelpMode::kShort);
      return true;
    }
    if (name == "package") {
      SetFlagsHelpMode(HelpMode::kPackage);
      return true;
    }
    return false;
  }
  if (name == "version") {
    SetFlagsHelpMode(HelpMode::kVersion);
    return true;
  }
  if (name == "only_check_args") {
    SetFlagsHelpMode(HelpMode::kOnlyCheckArgs);
    return true;
  }
  return false;
}
References absl::ConsumePrefix(), kFull, kImportant, kMatch, kOnlyCheckArgs, kPackage, kShort, kVersion, name, SetFlagsHelpMatchSubstr(), SetFlagsHelpMode(), and absl::StrCat().
Referenced by ParseCommandLineImpl().
DefaultArg() [1/2]
template<typename ValueT , typename GenT > FlagDefaultArg absl::flags_internal::DefaultArg (char) constexpr
Definition at line 299 of file flag.h.
{
  return {FlagDefaultSrc(&GenT::Gen), FlagDefaultKind::kGenFunc};
}
References kGenFunc.
DefaultArg() [2/2]
template<typename ValueT , typename GenT , typename std::enable_if< std::is_integral< ValueT >::value, int >::type = ((void)GenT{}, 0)> FlagDefaultArg absl::flags_internal::DefaultArg (int) constexpr
Definition at line 294 of file flag.h.
{
  return {FlagDefaultSrc(GenT{}.value), FlagDefaultKind::kOneWord};
}
References kOneWord.
Delete()
void absl::flags_internal::Delete (FlagOpFn op, void * obj) inline
Definition at line 106 of file flag.h.
{
  op(FlagOp::kDelete, nullptr, obj, nullptr);
}
References kDelete.
Referenced by absl::flags_internal::DynValueDeleter::operator()(), and absl::flags_internal::FlagState::~FlagState().
FastTypeId()
FlagFastTypeId absl::flags_internal::FastTypeId (FlagOpFn op) inline
Definition at line 143 of file flag.h.
{
  return reinterpret_cast<FlagFastTypeId>(
      op(FlagOp::kFastTypeId, nullptr, nullptr, nullptr));
}
References kFastTypeId.
Referenced by absl::flags_internal::FlagImpl::AssertValidType(), and absl::flags_internal::FlagImpl::Write().
FinalizeRegistry()
void absl::flags_internal::FinalizeRegistry ()
Definition at line 196 of file reflection.cc.
{
  auto& registry = FlagRegistry::GlobalRegistry();
  FlagRegistryLock frl(registry);
  if (registry.finalized_flags_.load(std::memory_order_relaxed)) {
    // Was already finalized. Ignore the second time.
    return;
  }
  registry.flat_flags_.reserve(registry.flags_.size());
  for (const auto& f : registry.flags_) {
    registry.flat_flags_.push_back(f.second);
  }
  std::sort(std::begin(registry.flat_flags_), std::end(registry.flat_flags_),
            [](const CommandLineFlag* lhs, const CommandLineFlag* rhs) {
              return lhs->Name() < rhs->Name();
            });
  registry.flags_.clear();
  registry.finalized_flags_.store(true, std::memory_order_release);
}
Referenced by ParseCommandLineImpl().
FlagHelp()
void absl::flags_internal::FlagHelp (std::ostream & out, const CommandLineFlag & flag, HelpFormat format)
Definition at line 337 of file usage.cc.
{
  if (format == HelpFormat::kHumanReadable)
    flags_internal::FlagHelpHumanReadable(flag, out);
}
References kHumanReadable, and absl::out.
FlagOps()
template<typename T > void * absl::flags_internal::FlagOps (FlagOp op, const void * v1, void * v2, void * v3)
Definition at line 717 of file flag.h.
{
  switch (op) {
    case FlagOp::kAlloc: {
      std::allocator<T> alloc;
      return std::allocator_traits<std::allocator<T>>::allocate(alloc, 1);
    }
    case FlagOp::kDelete: {
      T* p = static_cast<T*>(v2);
      p->~T();
      std::allocator<T> alloc;
      std::allocator_traits<std::allocator<T>>::deallocate(alloc, p, 1);
      return nullptr;
    }
    case FlagOp::kCopy:
      *static_cast<T*>(v2) = *static_cast<const T*>(v1);
      return nullptr;
    case FlagOp::kCopyConstruct:
      new (v2) T(*static_cast<const T*>(v1));
      return nullptr;
    case FlagOp::kSizeof:
      return reinterpret_cast<void*>(static_cast<uintptr_t>(sizeof(T)));
    case FlagOp::kFastTypeId:
      return const_cast<void*>(base_internal::FastTypeId<T>());
    case FlagOp::kRuntimeTypeId:
      return const_cast<std::type_info*>(GenRuntimeTypeId<T>());
    case FlagOp::kParse: {
      // Initialize the temporary instance of type T based on current value in
      // destination (which is going to be flag's default value).
      T temp(*static_cast<T*>(v2));
      if (!absl::ParseFlag<T>(*static_cast<const absl::string_view*>(v1), &temp,
                              static_cast<std::string*>(v3))) {
        return nullptr;
      }
      *static_cast<T*>(v2) = std::move(temp);
      return v2;
    }
    case FlagOp::kUnparse:
      *static_cast<std::string*>(v2) =
          absl::UnparseFlag<T>(*static_cast<const T*>(v1));
      return nullptr;
    case FlagOp::kValueOffset: {
      // Round sizeof(FlagImp) to a multiple of alignof(FlagValue<T>) to get the
      // offset of the data.
      size_t round_to = alignof(FlagValue<T>);
      size_t offset =
          (sizeof(FlagImpl) + round_to - 1) / round_to * round_to;
      return reinterpret_cast<void*>(offset);
    }
  }
  return nullptr;
}
References alloc, absl::base_internal::FastTypeId(), absl::flags_internal::FlagImpl::FlagImpl(), GenRuntimeTypeId(), kAlloc, kCopy, kCopyConstruct, kDelete, kFastTypeId, kParse, kRuntimeTypeId, kSizeof, kUnparse, kValueOffset, absl::p, absl::ParseFlag(), and absl::UnparseFlag().
FlagsHelp()
void absl::flags_internal::FlagsHelp (std::ostream & out, absl::string_view filter, HelpFormat format, absl::string_view program_usage_message)
Definition at line 346 of file usage.cc.
{
  flags_internal::FlagKindFilter filter_cb = [&](absl::string_view filename) {
    return filter.empty() || absl::StrContains(filename, filter);
  };
  flags_internal::FlagsHelpImpl(out, filter_cb, format, program_usage_message);
}
References absl::string_view::empty(), absl::out, and absl::StrContains().
Referenced by HandleUsageFlags().
ForEachFlag()
void absl::flags_internal::ForEachFlag (std::function< void(CommandLineFlag &)> visitor)
Definition at line 178 of file reflection.cc.
{
  FlagRegistry& registry = FlagRegistry::GlobalRegistry();
  if (registry.finalized_flags_.load(std::memory_order_acquire)) {
    for (const auto& i : registry.flat_flags_) visitor(*i);
  }
  FlagRegistryLock frl(registry);
  for (const auto& i : registry.flags_) visitor(*i.second);
}
Referenced by absl::GetAllFlags(), GetMisspellingHints(), and absl::flags_internal::FlagSaverImpl::SaveFromRegistry().
GenRuntimeTypeId()
template<typename T > const std::type_info * absl::flags_internal::GenRuntimeTypeId () inline
Definition at line 165 of file flag.h.
{
#ifdef ABSL_INTERNAL_HAS_RTTI
  return &typeid(T);
#else
  return nullptr;
#endif
}
Referenced by FlagOps().
GetFlagsHelpFormat()
HelpFormat absl::flags_internal::GetFlagsHelpFormat ()
Definition at line 456 of file usage.cc.
{
  absl::MutexLock l(&help_attributes_guard);
  return help_format;
}
Referenced by HandleUsageFlags().
GetFlagsHelpMatchSubstr()
std::string absl::flags_internal::GetFlagsHelpMatchSubstr ()
Definition at line 434 of file usage.cc.
{
  absl::MutexLock l(&help_attributes_guard);
  if (match_substr == nullptr) return "";
  return *match_substr;
}
Referenced by HandleUsageFlags().
GetFlagsHelpMode()
HelpMode absl::flags_internal::GetFlagsHelpMode ()
Definition at line 446 of file usage.cc.
{
  absl::MutexLock l(&help_attributes_guard);
  return help_mode;
}
Referenced by HandleUsageFlags().
GetMisspellingHints()
std::vector< std::string > absl::flags_internal::GetMisspellingHints (absl::string_view flag)
Definition at line 637 of file parse.cc.
{
  const size_t maxCutoff = std::min(flag.size() / 2 + 1, kMaxDistance);
  auto undefok = absl::GetFlag(FLAGS_undefok);
  BestHints best_hints(static_cast<uint8_t>(maxCutoff));
  absl::flags_internal::ForEachFlag([&](const CommandLineFlag& f) {
    if (best_hints.hints.size() >= kMaxHints) return;
    uint8_t distance = strings_internal::CappedDamerauLevenshteinDistance(
        flag, f.Name(), best_hints.best_distance);
    best_hints.AddHint(f.Name(), distance);
    // For boolean flags, also calculate distance to the negated form.
    if (f.IsOfType<bool>()) {
      const std::string negated_flag = absl::StrCat("no", f.Name());
      distance = strings_internal::CappedDamerauLevenshteinDistance(
          flag, negated_flag, best_hints.best_distance);
      best_hints.AddHint(negated_flag, distance);
    }
  });
  // Finally calculate distance to flags in "undefok".
  absl::c_for_each(undefok, [&](const absl::string_view f) {
    if (best_hints.hints.size() >= kMaxHints) return;
    uint8_t distance = strings_internal::CappedDamerauLevenshteinDistance(
        flag, f, best_hints.best_distance);
    best_hints.AddHint(absl::StrCat(f, " (undefok)"), distance);
  });
  return best_hints.hints;
}
References absl::flags_internal::BestHints::AddHint(), absl::flags_internal::BestHints::best_distance, absl::c_for_each(), absl::strings_internal::CappedDamerauLevenshteinDistance(), absl::f, ForEachFlag(), absl::GetFlag(), absl::flags_internal::BestHints::hints, absl::string_view::size(), and absl::StrCat().
Referenced by ParseCommandLineImpl().
GetUsageConfig()
FlagsUsageConfig absl::flags_internal::GetUsageConfig ()
Definition at line 113 of file usage_config.cc.
{
  absl::MutexLock l(&custom_usage_config_guard);
  if (custom_usage_config) return *custom_usage_config;
  FlagsUsageConfig default_config;
  default_config.contains_helpshort_flags = &ContainsHelpshortFlags;
  default_config.contains_help_flags = &ContainsHelppackageFlags;
  default_config.contains_helppackage_flags = &ContainsHelppackageFlags;
  default_config.version_string = &VersionString;
  default_config.normalize_filename = &NormalizeFilename;
  return default_config;
}
References absl::FlagsUsageConfig::contains_help_flags, absl::FlagsUsageConfig::contains_helppackage_flags, absl::FlagsUsageConfig::contains_helpshort_flags, absl::FlagsUsageConfig::normalize_filename, and absl::FlagsUsageConfig::version_string.
Referenced by HandleUsageFlags(), and absl::flags_internal::FlagRegistry::RegisterFlag().
HandleUsageFlags()
int absl::flags_internal::HandleUsageFlags (std::ostream & out, absl::string_view program_usage_message)
Definition at line 357 of file usage.cc.
{
  switch (GetFlagsHelpMode()) {
    case HelpMode::kNone:
      break;
    case HelpMode::kImportant:
      flags_internal::FlagsHelpImpl(
          out, flags_internal::GetUsageConfig().contains_help_flags,
          GetFlagsHelpFormat(), program_usage_message);
      return 1;
    case HelpMode::kShort:
      flags_internal::FlagsHelpImpl(
          out, flags_internal::GetUsageConfig().contains_helpshort_flags,
          GetFlagsHelpFormat(), program_usage_message);
      return 1;
    case HelpMode::kFull:
      flags_internal::FlagsHelp(out, "", GetFlagsHelpFormat(),
                                program_usage_message);
      return 1;
    case HelpMode::kPackage:
      flags_internal::FlagsHelpImpl(
          out, flags_internal::GetUsageConfig().contains_helppackage_flags,
          GetFlagsHelpFormat(), program_usage_message);
      return 1;
    case HelpMode::kMatch: {
      std::string substr = GetFlagsHelpMatchSubstr();
      if (substr.empty()) {
        // show all options
        flags_internal::FlagsHelp(out, substr, GetFlagsHelpFormat(),
                                  program_usage_message);
      } else {
        auto filter_cb = [&substr](const absl::CommandLineFlag& flag) {
          if (absl::StrContains(flag.Name(), substr)) return true;
          if (absl::StrContains(flag.Filename(), substr)) return true;
          if (absl::StrContains(flag.Help(), substr)) return true;
          return false;
        };
        flags_internal::FlagsHelpImpl(
            out, filter_cb, HelpFormat::kHumanReadable, program_usage_message);
      }
      return 1;
    }
    case HelpMode::kVersion:
      if (flags_internal::GetUsageConfig().version_string)
        out << flags_internal::GetUsageConfig().version_string();
      // Unlike help, we may be asking for version in a script, so return 0
      return 0;
    case HelpMode::kOnlyCheckArgs:
      return 0;
  }
  return -1;
}
References FlagsHelp(), GetFlagsHelpFormat(), GetFlagsHelpMatchSubstr(), GetFlagsHelpMode(), GetUsageConfig(), kFull, kHumanReadable, kImportant, kMatch, kNone, kOnlyCheckArgs, kPackage, kShort, kVersion, absl::out, absl::StrContains(), and absl::FlagsUsageConfig::version_string.
Referenced by ParseCommandLineImpl().
HelpArg() [1/2]
template<typename Gen , size_t N> FlagHelpArg absl::flags_internal::HelpArg (const FixedCharArray< N > & value) constexpr
Definition at line 235 of file flag.h.
{
  return {FlagHelpMsg(value.value), FlagHelpKind::kLiteral};
}
References kLiteral.
HelpArg() [2/2]
template<typename Gen > FlagHelpArg absl::flags_internal::HelpArg (std::false_type) constexpr
Definition at line 240 of file flag.h.
{
  return {FlagHelpMsg(&Gen::NonConst), FlagHelpKind::kGenFunc};
}
References kGenFunc.
HelpStringAsArray() [1/2]
template<typename Gen > std::false_type absl::flags_internal::HelpStringAsArray (char) constexpr
Definition at line 199 of file flag.h.
{
  return std::false_type{};
}
HelpStringAsArray() [2/2]
template<typename Gen , size_t N = Gen::Value().size()> FixedCharArray< N+1 > absl::flags_internal::HelpStringAsArray (int) constexpr
Definition at line 193 of file flag.h.
{
  return FixedCharArray<N + 1>::FromLiteralString(
      Gen::Value(), absl::make_index_sequence<N>{});
}
References absl::flags_internal::FixedCharArray< N >::FromLiteralString().
InitDefaultValue() [1/2]
template<typename T > T absl::flags_internal::InitDefaultValue (EmptyBraces) constexpr
Definition at line 287 of file flag.h.
{
  return T{};
}
InitDefaultValue() [2/2]
template<typename T > T absl::flags_internal::InitDefaultValue (T t) constexpr
Definition at line 282 of file flag.h.
{
  return t;
}
InvokeParseFlag()
template<typename T > bool absl::flags_internal::InvokeParseFlag (absl::string_view input, T * dst, std::string * err)
Definition at line 272 of file marshalling.h.
{
  // Comment on next line provides a good compiler error message if T
  // does not have AbslParseFlag(absl::string_view, T*, std::string*).
  return AbslParseFlag(input, dst, err);  // Is T missing AbslParseFlag?
}
References AbslParseFlag().
Referenced by absl::ParseFlag().
Package()
absl::string_view absl::flags_internal::Package (absl::string_view filename) inline
Definition at line 50 of file path_util.h.
{
  auto last_slash_pos = filename.find_last_of("/\\");
  return last_slash_pos == absl::string_view::npos
             ? absl::string_view()
             : filename.substr(0, last_slash_pos + 1);
}
References absl::string_view::find_last_of(), absl::string_view::npos, and absl::string_view::substr().
Parse()
bool absl::flags_internal::Parse (FlagOpFn op, absl::string_view text, void * dst, std::string * error) inline
Definition at line 125 of file flag.h.
{
  return op(FlagOp::kParse, &text, dst, error) != nullptr;
}
References kParse.
Referenced by absl::flags_internal::FlagImpl::Write().
ParseCommandLineImpl()
std::vector< char * > absl::flags_internal::ParseCommandLineImpl (int argc, char * argv[], ArgvListAction arg_list_act, UsageFlagsAction usage_flag_act, OnUndefinedFlag on_undef_flag)
Definition at line 666 of file parse.cc.
{
  ABSL_INTERNAL_CHECK(argc > 0, "Missing argv[0]");
  // Once parsing has started we will not have more flag registrations.
  // If we did, they would be missing during parsing, which is a problem on
  // itself.
  flags_internal::FinalizeRegistry();
  // This routine does not return anything since we abort on failure.
  CheckDefaultValuesParsingRoundtrip();
  std::vector<std::string> flagfile_value;
  std::vector<ArgsList> input_args;
  input_args.push_back(ArgsList(argc, argv));
  std::vector<char*> output_args;
  std::vector<char*> positional_args;
  output_args.reserve(static_cast<size_t>(argc));
  // This is the list of undefined flags. The element of the list is the pair
  // consisting of boolean indicating if flag came from command line (vs from
  // some flag file we've read) and flag name.
  // TODO(rogeeff): Eliminate the first element in the pair after cleanup.
  std::vector<std::pair<bool, std::string>> undefined_flag_names;
  // Set program invocation name if it is not set before.
  if (ProgramInvocationName() == "UNKNOWN") {
    flags_internal::SetProgramInvocationName(argv[0]);
  }
  output_args.push_back(argv[0]);
  absl::MutexLock l(&specified_flags_guard);
  if (specified_flags == nullptr) {
    specified_flags = new std::vector<const CommandLineFlag*>;
  } else {
    specified_flags->clear();
  }
  // Iterate through the list of the input arguments. First level are arguments
  // originated from argc/argv. Following levels are arguments originated from
  // recursive parsing of flagfile(s).
  bool success = true;
  while (!input_args.empty()) {
    // 10. First we process the built-in generator flags.
    success &= HandleGeneratorFlags(input_args, flagfile_value);
    // 30. Select top-most (most recent) arguments list. If it is empty drop it
    // and re-try.
    ArgsList& curr_list = input_args.back();
    curr_list.PopFront();
    if (curr_list.Size() == 0) {
      input_args.pop_back();
      continue;
    }
    // 40. Pick up the front remaining argument in the current list. If current
    // stack of argument lists contains only one element - we are processing an
    // argument from the original argv.
    absl::string_view arg(curr_list.Front());
    bool arg_from_argv = input_args.size() == 1;
    // 50. If argument does not start with - or is just "-" - this is
    // positional argument.
    if (!absl::ConsumePrefix(&arg, "-") || arg.empty()) {
      ABSL_INTERNAL_CHECK(arg_from_argv,
                          "Flagfile cannot contain positional argument");
      positional_args.push_back(argv[curr_list.FrontIndex()]);
      continue;
    }
    if (arg_from_argv && (arg_list_act == ArgvListAction::kKeepParsedArgs)) {
      output_args.push_back(argv[curr_list.FrontIndex()]);
    }
    // 60. Split the current argument on '=' to figure out the argument
    // name and value. If flag name is empty it means we've got "--". value
    // can be empty either if there were no '=' in argument string at all or
    // an argument looked like "--foo=". In a latter case is_empty_value is
    // true.
    absl::string_view flag_name;
    absl::string_view value;
    bool is_empty_value = false;
    std::tie(flag_name, value, is_empty_value) = SplitNameAndValue(arg);
    // 70. "--" alone means what it does for GNU: stop flags parsing. We do
    // not support positional arguments in flagfiles, so we just drop them.
    if (flag_name.empty()) {
      ABSL_INTERNAL_CHECK(arg_from_argv,
                          "Flagfile cannot contain positional argument");
      curr_list.PopFront();
      break;
    }
    // 80. Locate the flag based on flag name. Handle both --foo and --nofoo
    CommandLineFlag* flag = nullptr;
    bool is_negative = false;
    std::tie(flag, is_negative) = LocateFlag(flag_name);
    if (flag == nullptr) {
      // Usage flags are not modeled as Abseil flags. Locate them separately.
      if (flags_internal::DeduceUsageFlags(flag_name, value)) {
        continue;
      }
      if (on_undef_flag != OnUndefinedFlag::kIgnoreUndefined) {
        undefined_flag_names.emplace_back(arg_from_argv,
                                          std::string(flag_name));
      }
      continue;
    }
    // 90. Deduce flag's value (from this or next argument)
    auto curr_index = curr_list.FrontIndex();
    bool value_success = true;
    std::tie(value_success, value) =
        DeduceFlagValue(*flag, value, is_negative, is_empty_value, &curr_list);
    success &= value_success;
    // If above call consumed an argument, it was a standalone value
    if (arg_from_argv && (arg_list_act == ArgvListAction::kKeepParsedArgs) &&
        (curr_index != curr_list.FrontIndex())) {
      output_args.push_back(argv[curr_list.FrontIndex()]);
    }
    // 100. Set the located flag to a new new value, unless it is retired.
    // Setting retired flag fails, but we ignoring it here while also reporting
    // access to retired flag.
    std::string error;
    if (!flags_internal::PrivateHandleAccessor::ParseFrom(
            *flag, value, SET_FLAGS_VALUE, kCommandLine, error)) {
      if (flag->IsRetired()) continue;
      flags_internal::ReportUsageError(error, true);
      success = false;
    } else {
      specified_flags->push_back(flag);
    }
  }
  for (const auto& flag_name : undefined_flag_names) {
    if (CanIgnoreUndefinedFlag(flag_name.second)) continue;
    // Verify if flag_name has the "no" already removed
    std::vector<std::string> flags;
    if (flag_name.first) flags = GetMisspellingHints(flag_name.second);
    if (flags.empty()) {
      flags_internal::ReportUsageError(
          absl::StrCat("Unknown command line flag '", flag_name.second, "'"),
          true);
    } else {
      flags_internal::ReportUsageError(
          absl::StrCat("Unknown command line flag '", flag_name.second,
                       "'. Did you mean: ", absl::StrJoin(flags, ", "), " ?"),
          true);
    }
    success = false;
  }
#if ABSL_FLAGS_STRIP_NAMES
  if (!success) {
    flags_internal::ReportUsageError(
        "NOTE: command line flags are disabled in this build", true);
  }
#endif
  if (!success) {
    flags_internal::HandleUsageFlags(std::cout,
                                     ProgramUsageMessage());
    std::exit(1);
  }
  if (usage_flag_act == UsageFlagsAction::kHandleUsage) {
    int exit_code = flags_internal::HandleUsageFlags(
        std::cout, ProgramUsageMessage());
    if (exit_code != -1) {
      std::exit(exit_code);
    }
  }
  ResetGeneratorFlags(flagfile_value);
  // Reinstate positional args which were intermixed with flags in the arguments
  // list.
  for (auto arg : positional_args) {
    output_args.push_back(arg);
  }
  // All the remaining arguments are positional.
  if (!input_args.empty()) {
    for (size_t arg_index = input_args.back().FrontIndex();
         arg_index < static_cast<size_t>(argc); ++arg_index) {
      output_args.push_back(argv[arg_index]);
    }
  }
  // Trim and sort the vector.
  specified_flags->shrink_to_fit();
  std::sort(specified_flags->begin(), specified_flags->end(),
            SpecifiedFlagsCompare{});
  return output_args;
}
References ABSL_INTERNAL_CHECK, arg, absl::ConsumePrefix(), DeduceUsageFlags(), absl::string_view::empty(), FinalizeRegistry(), absl::flags, GetMisspellingHints(), HandleUsageFlags(), absl::CommandLineFlag::IsRetired(), kCommandLine, kHandleUsage, kIgnoreUndefined, kKeepParsedArgs, absl::flags_internal::PrivateHandleAccessor::ParseFrom(), ProgramInvocationName(), absl::ProgramUsageMessage(), ReportUsageError(), SET_FLAGS_VALUE, SetProgramInvocationName(), absl::StrCat(), absl::StrJoin(), and value.
Referenced by absl::ParseCommandLine().
ParseFlagImpl()
template<typename IntType > bool absl::flags_internal::ParseFlagImpl (absl::string_view text, IntType & dst) inline
Definition at line 77 of file marshalling.cc.
{
  text = absl::StripAsciiWhitespace(text);
  return absl::numbers_internal::safe_strtoi_base(text, &dst,
                                                  NumericBase(text));
}
References absl::numbers_internal::safe_strtoi_base(), and absl::StripAsciiWhitespace().
Referenced by AbslParseFlag(), AbslParseFlag(), AbslParseFlag(), AbslParseFlag(), AbslParseFlag(), AbslParseFlag(), AbslParseFlag(), and AbslParseFlag().
ProgramInvocationName()
std::string absl::flags_internal::ProgramInvocationName ()
Definition at line 36 of file program_name.cc.
{
  absl::MutexLock l(&program_name_guard);
  return program_name ? *program_name : "UNKNOWN";
}
Referenced by ParseCommandLineImpl().
RegisterCommandLineFlag()
bool absl::flags_internal::RegisterCommandLineFlag (CommandLineFlag & flag, const char * filename)
Definition at line 191 of file reflection.cc.
{
  FlagRegistry::GlobalRegistry().RegisterFlag(flag, filename);
  return true;
}
References absl::flags_internal::FlagRegistry::GlobalRegistry(), and absl::flags_internal::FlagRegistry::RegisterFlag().
ReportUsageError()
void absl::flags_internal::ReportUsageError (absl::string_view msg, bool is_fatal)
Definition at line 128 of file usage_config.cc.
{
  std::cerr << "ERROR: " << msg << std::endl;
  if (is_fatal) {
    ABSL_INTERNAL_C_SYMBOL(AbslInternalReportFatalUsageError)(msg);
  }
}
References ABSL_INTERNAL_C_SYMBOL, AbslInternalReportFatalUsageError(), and absl::msg.
Referenced by ParseCommandLineImpl(), and absl::flags_internal::FlagRegistry::RegisterFlag().
Retire()
void absl::flags_internal::Retire (const char * name, FlagFastTypeId type_id, char * buf)
Definition at line 281 of file reflection.cc.
{
  static_assert(sizeof(RetiredFlagObj) == kRetiredFlagObjSize, "");
  static_assert(alignof(RetiredFlagObj) == kRetiredFlagObjAlignment, "");
  auto* flag = ::new (static_cast<void*>(buf))
      flags_internal::RetiredFlagObj(name, type_id);
  FlagRegistry::GlobalRegistry().RegisterFlag(*flag, nullptr);
}
References buf, absl::flags_internal::FlagRegistry::GlobalRegistry(), kRetiredFlagObjAlignment, kRetiredFlagObjSize, name, and absl::flags_internal::FlagRegistry::RegisterFlag().
Referenced by absl::flags_internal::RetiredFlag< T >::Retire().
RuntimeTypeId()
const std::type_info * absl::flags_internal::RuntimeTypeId (FlagOpFn op) inline
Definition at line 148 of file flag.h.
{
  return reinterpret_cast<const std::type_info*>(
      op(FlagOp::kRuntimeTypeId, nullptr, nullptr, nullptr));
}
References kRuntimeTypeId.
Referenced by absl::flags_internal::FlagImpl::AssertValidType().
SetFlagsHelpFormat()
void absl::flags_internal::SetFlagsHelpFormat (HelpFormat format)
Definition at line 461 of file usage.cc.
{
  absl::MutexLock l(&help_attributes_guard);
  help_format = format;
}
SetFlagsHelpMatchSubstr()
void absl::flags_internal::SetFlagsHelpMatchSubstr (absl::string_view substr)
Definition at line 440 of file usage.cc.
{
  absl::MutexLock l(&help_attributes_guard);
  if (match_substr == nullptr) match_substr = new std::string;
  match_substr->assign(substr.data(), substr.size());
}
References absl::string_view::data(), and absl::string_view::size().
Referenced by DeduceUsageFlags().
SetFlagsHelpMode()
void absl::flags_internal::SetFlagsHelpMode (HelpMode mode)
Definition at line 451 of file usage.cc.
{
  absl::MutexLock l(&help_attributes_guard);
  help_mode = mode;
}
Referenced by DeduceUsageFlags().
SetProgramInvocationName()
void absl::flags_internal::SetProgramInvocationName (absl::string_view prog_name_str)
Definition at line 49 of file program_name.cc.
{
  absl::MutexLock l(&program_name_guard);
  if (!program_name)
    program_name = new std::string(prog_name_str);
  else
    program_name->assign(prog_name_str.data(), prog_name_str.size());
}
References absl::string_view::data(), and absl::string_view::size().
Referenced by main(), and ParseCommandLineImpl().
ShortProgramInvocationName()
std::string absl::flags_internal::ShortProgramInvocationName ()
Definition at line 42 of file program_name.cc.
{
  absl::MutexLock l(&program_name_guard);
  return program_name ? std::string(flags_internal::Basename(*program_name))
                      : "UNKNOWN";
}
References Basename().
Sizeof()
size_t absl::flags_internal::Sizeof (FlagOpFn op) inline
Definition at line 136 of file flag.h.
{
  // This sequence of casts reverses the sequence from
  // `flags_internal::FlagOps()`
  return static_cast<size_t>(reinterpret_cast<intptr_t>(
      op(FlagOp::kSizeof, nullptr, nullptr, nullptr)));
}
References kSizeof.
Referenced by absl::flags_internal::FlagImpl::Read().
UninitializedFlagValue()
int64_t absl::flags_internal::UninitializedFlagValue () constexpr
Definition at line 306 of file flag.h.
{
  return static_cast<int64_t>(0xababababababababll);
}
Referenced by absl::flags_internal::FlagValue< T, FlagValueStorageKind::kOneWordAtomic >::Get().
Unparse() [1/13]
std::string absl::flags_internal::Unparse (bool v)
Definition at line 165 of file marshalling.cc.
{ return v ? "true" : "false"; }
References absl::v.
Unparse() [2/13]
template<typename T > std::string absl::flags_internal::Unparse (const T & v)
Definition at line 297 of file marshalling.h.
{
  // Comment on next line provides a good compiler error message if T does not
  // have UnparseFlag.
  return AbslUnparseFlag(v);  // Is T missing AbslUnparseFlag?
}
References AbslUnparseFlag(), and absl::v.
Unparse() [3/13]
std::string absl::flags_internal::Unparse (double v)
Definition at line 194 of file marshalling.cc.
{ return UnparseFloatingPointVal(v); }
References UnparseFloatingPointVal(), and absl::v.
Unparse() [4/13]
std::string absl::flags_internal::Unparse (FlagOpFn op, const void * val) inline
Definition at line 130 of file flag.h.
{
  std::string result;
  op(FlagOp::kUnparse, val, &result, nullptr);
  return result;
}
References kUnparse.
Referenced by absl::UnparseFlag(), and absl::flags_internal::FlagImpl::Write().
Unparse() [5/13]
std::string absl::flags_internal::Unparse (float v)
Definition at line 193 of file marshalling.cc.
{ return UnparseFloatingPointVal(v); }
References UnparseFloatingPointVal(), and absl::v.
Unparse() [6/13]
std::string absl::flags_internal::Unparse (int v)
Definition at line 168 of file marshalling.cc.
{ return absl::StrCat(v); }
References absl::StrCat(), and absl::v.
Unparse() [7/13]
std::string absl::flags_internal::Unparse (long long v)
Definition at line 172 of file marshalling.cc.
{ return absl::StrCat(v); }
References absl::StrCat(), and absl::v.
Unparse() [8/13]
std::string absl::flags_internal::Unparse (long v)
Definition at line 170 of file marshalling.cc.
{ return absl::StrCat(v); }
References absl::StrCat(), and absl::v.
Unparse() [9/13]
std::string absl::flags_internal::Unparse (short v)
Definition at line 166 of file marshalling.cc.
{ return absl::StrCat(v); }
References absl::StrCat(), and absl::v.
Unparse() [10/13]
std::string absl::flags_internal::Unparse (unsigned int v)
Definition at line 169 of file marshalling.cc.
{ return absl::StrCat(v); }
References absl::StrCat(), and absl::v.
Unparse() [11/13]
std::string absl::flags_internal::Unparse (unsigned long long v)
Definition at line 173 of file marshalling.cc.
{ return absl::StrCat(v); }
References absl::StrCat(), and absl::v.
Unparse() [12/13]
std::string absl::flags_internal::Unparse (unsigned long v)
Definition at line 171 of file marshalling.cc.
{ return absl::StrCat(v); }
References absl::StrCat(), and absl::v.
Unparse() [13/13]
std::string absl::flags_internal::Unparse (unsigned short v)
Definition at line 167 of file marshalling.cc.
{ return absl::StrCat(v); }
References absl::StrCat(), and absl::v.
UnparseFloatingPointVal()
template<typename T > std::string absl::flags_internal::UnparseFloatingPointVal (T v)
Definition at line 175 of file marshalling.cc.
{
  // digits10 is guaranteed to roundtrip correctly in string -> value -> string
  // conversions, but may not be enough to represent all the values correctly.
  std::string digit10_str =
      absl::StrFormat("%.*g", std::numeric_limits<T>::digits10, v);
  if (std::isnan(v) || std::isinf(v)) return digit10_str;
  T roundtrip_val = 0;
  std::string err;
  if (absl::ParseFlag(digit10_str, &roundtrip_val, &err) &&
      roundtrip_val == v) {
    return digit10_str;
  }
  // max_digits10 is the number of base-10 digits that are necessary to uniquely
  // represent all distinct values.
  return absl::StrFormat("%.*g", std::numeric_limits<T>::max_digits10, v);
}
References absl::ParseFlag(), absl::StrFormat(), and absl::v.
Referenced by Unparse(), and Unparse().
ValueOffset()
ptrdiff_t absl::flags_internal::ValueOffset (FlagOpFn op) inline
Definition at line 156 of file flag.h.
{
  // This sequence of casts reverses the sequence from
  // `flags_internal::FlagOps()`
  return static_cast<ptrdiff_t>(reinterpret_cast<intptr_t>(
      op(FlagOp::kValueOffset, nullptr, nullptr, nullptr)));
}
References kValueOffset.
WasPresentOnCommandLine()
bool absl::flags_internal::WasPresentOnCommandLine (absl::string_view flag_name)
Definition at line 606 of file parse.cc.
{
  absl::MutexLock l(&specified_flags_guard);
  ABSL_INTERNAL_CHECK(specified_flags != nullptr,
                      "ParseCommandLine is not invoked yet");
  return std::binary_search(specified_flags->begin(), specified_flags->end(),
                            flag_name, SpecifiedFlagsCompare{});
}
References ABSL_INTERNAL_CHECK.
Variable Documentation
kRetiredFlagObjAlignment
size_t absl::flags_internal::kRetiredFlagObjAlignment = alignof(void*) constexpr
Definition at line 79 of file registry.h.
Referenced by Retire().
kRetiredFlagObjSize
size_t absl::flags_internal::kRetiredFlagObjSize = 3 * sizeof(void*) constexpr
Definition at line 78 of file registry.h.
Referenced by Retire().
kStrippedFlagHelp
const char absl::flags_internal::kStrippedFlagHelp = "\001\002\003\004 (unknown) \004\003\002\001"
Definition at line 51 of file flag.cc.