open spiel: open_spiel.python.examples.play_tarok_game Namespace Reference
open_spiel.python.examples.play_tarok_game Namespace Reference
Functions
play_tarok_game ()
print_info (unused_game, state)
print_talon_exchange_info (state)
print_tricks_playing_info (state)
Detailed Description
Plays a round of Tarok with actions from user input.
Function Documentation
play_tarok_game()
open_spiel.python.examples.play_tarok_game.play_tarok_game ()
Definition at line 20 of file play_tarok_game.py.
def play_tarok_game():
  game = pyspiel.load_game("tarok(players=3)")
  state = game.new_initial_state()
  while not state.is_terminal():
    print_info(game, state)
    state.apply_action(int(input("Enter action: ")))
    print("-" * 70, "\n")
  print(state.current_game_phase())
  print("Players' scores: {}".format(state.rewards()))
References open_spiel.python.examples.play_tarok_game.print_info().
Referenced by open_spiel.python.examples.play_tarok_game.print_tricks_playing_info().
print_info()
open_spiel.python.examples.play_tarok_game.print_info (unused_game, state)
Print information about the game state.
Definition at line 31 of file play_tarok_game.py.
def print_info(unused_game, state):
  """Print information about the game state."""
  print("Game phase: {}".format(state.current_game_phase()))
  print("Selected contract: {}".format(state.selected_contract()))
  print("Current player: {}".format(state.current_player()))
  player_cards = state.player_cards(state.current_player())
  action_names = [state.card_action_to_string(a) for a in player_cards]
  print("\nPlayer cards: {}".format(
      list(zip(action_names, player_cards))))
  if state.current_game_phase() == pyspiel.TarokGamePhase.TALON_EXCHANGE:
    print_talon_exchange_info(state)
  elif state.current_game_phase() == pyspiel.TarokGamePhase.TRICKS_PLAYING:
    print_tricks_playing_info(state)
  else:
    print()
  legal_actions = state.legal_actions()
  action_names = [state.action_to_string(a) for a in state.legal_actions()]
  print("Legal actions: {}\n".format(
      list(zip(action_names, legal_actions))))
References open_spiel.python.examples.play_tarok_game.print_talon_exchange_info(), and open_spiel.python.examples.play_tarok_game.print_tricks_playing_info().
Referenced by open_spiel.python.examples.play_tarok_game.play_tarok_game().
print_talon_exchange_info()
open_spiel.python.examples.play_tarok_game.print_talon_exchange_info (state)
Definition at line 54 of file play_tarok_game.py.
def print_talon_exchange_info(state):
  talon = [[state.card_action_to_string(x) for x in talon_set]
           for talon_set in state.talon_sets()]
  print("\nTalon: {}\n".format(talon))
Referenced by open_spiel.python.examples.play_tarok_game.print_info().
print_tricks_playing_info()
open_spiel.python.examples.play_tarok_game.print_tricks_playing_info (state)
Definition at line 60 of file play_tarok_game.py.
def print_tricks_playing_info(state):
  trick_cards = state.trick_cards()
  action_names = [state.card_action_to_string(a) for a in trick_cards]
  print("\nTrick cards: {}\n".format(
      list(zip(action_names, trick_cards))))
References open_spiel.python.examples.play_tarok_game.play_tarok_game().
Referenced by open_spiel.python.examples.play_tarok_game.print_info().