open spiel: open_spiel Namespace Reference
open_spiel Namespace Reference
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
Namespaces
namespace add_noise
namespace algorithms
namespace amazons
namespace bach_or_stravinsky
namespace backgammon
namespace bargaining
namespace baseT
namespace battleship
namespace biased_rock_paper_scissors
namespace blackjack
namespace blotto
namespace breakthrough
namespace bridge
namespace bridge_uncontested_bidding
namespace catch_
namespace checkers
namespace chess
namespace chess_common
namespace chicken_dare
namespace cliff_walking
namespace clobber
namespace coin_game
namespace colored_trails
namespace connect_four
namespace coop_box_pushing
namespace coop_to_1p
namespace coordinated_mp
namespace coordination
namespace crazy_eights
namespace crowd_modelling
namespace crowd_modelling_2d
namespace cursor_go
namespace dark_chess
namespace dark_hex
namespace deep_sea
namespace dots_and_boxes
namespace dou_dizhu
namespace dynamic_routing
namespace efg_game
namespace euchre
namespace file
namespace first_sealed_auction
namespace gamut
namespace garnet
namespace gin_rummy
namespace go
namespace goofspiel
namespace hanabi
namespace havannah
namespace hearts
namespace hex
namespace integration_tests
namespace internal
namespace json
namespace kbg
namespace kriegspiel
namespace kuhn_poker
namespace laser_tag
namespace leduc_poker
namespace lewis_signaling
namespace liars_dice
namespace maedn
namespace mancala
namespace markov_soccer
namespace matching_pennies
namespace matching_pennies_3p
namespace matrix_game
namespace misere
namespace morpion_solitaire
namespace negotiation
namespace nfg_game
namespace nim
namespace nine_mens_morris
namespace oh_hell
namespace oshi_zumo
namespace othello
namespace oware
namespace pathfinding
namespace pentago
namespace phantom_go
namespace phantom_ttt
namespace pig
namespace prisoners_dilemma
namespace python
namespace quoridor
namespace rbc
namespace rock_paper_scissors
namespace rock_paper_scissors_water
namespace roshambo
namespace shapleys_game
namespace sheriff
namespace skat
namespace solitaire
namespace spades
namespace stag_hunt
namespace start_at
namespace stones_and_gems
namespace tarok
namespace tensor_game
namespace testing
namespace tic_tac_toe
namespace tiny_bridge
namespace tiny_hanabi
namespace trade_comm
namespace twenty_forty_eight
namespace twixt
namespace uci
namespace ultimate_tic_tac_toe
namespace universal_poker
namespace y_game
namespace zerosum
Classes
class ActionObservationHistory
struct ActionView
class Allocator
class BasicStats
struct BinaryCompress
class Bot
class BotFactory
class BotRegisterer
class CircularBuffer
class ContiguousAllocator
class DataLogger
class DataLoggerJsonLines
class DataLoggerNoop
class EFGWriter
class FileLogger
class FirstActionPolicy
struct FixedActions
class FixedActionsIterator
struct FlatJointActions
class FlatJointActionsIterator
class Game
struct GameInfo
class GameParameter
class GameRegisterer
struct GameType
struct HexDoubleFormatter
class HistogramNamed
class HistogramNumbered
class HumanBot
struct IIGObservationType
class Logger
class LRUCache
struct LRUCacheInfo
class MisereGame
class MisereState
class NFGState
struct NoCompress
class NoopLogger
class NormalFormGame
class Observation
class Observer
class ObserverRegisterer
class PartialTabularPolicy
class PIMCBot
class Policy
class PreferredActionPolicy
class PublicObservationHistory
class PyBot
class PyGame
class PyObserver
class PyPolicy
class PyState
class Random
class RandomFixedSequence
class RandomMT
class RegisterSingleTensorObserver
class RepeatedGame
class RepeatedState
class RestrictedNashResponseGame
class RestrictedNashResponseObserver
class RestrictedNashResponseState
class SamplerFromRng
class SerializableCircularBuffer
class SimMoveGame
class SimMoveState
struct SimpleDoubleFormatter
class SpanTensor
class SpanTensorInfo
class StartAtTransformationGame
class StartAtTransformationState
class State
class StopToken
class TabularPolicy
class TensorView
class Thread
class ThreadedQueue
class TrackingVectorAllocator
class TurnBasedSimultaneousGame
class TurnBasedSimultaneousState
class UniformPolicy
class UniformProbabilitySampler
class WrappedGame
class WrappedState
class ZeroSumGame
class ZeroSumState
Typedefs
using GameParameters = std::map<std::string, GameParameter>
using ObservationParams = GameParameters
using ActionsAndProbs = std::vector<std::pair<Action, double>>
using HistoryDistribution
using Player = int
using Action = int64_t
using ErrorHandler = void (*)(const std::string&)
Enumerations
enum { kFixedAction = 0 , kFreeAction = 1 }
enum CompressionScheme : char { kCompressionNone , kCompressionBinary }
enum class PrivateInfoType { kNone , kSinglePlayer , kAllPlayers }
enum PlayerId {
kDefaultPlayerId = 0 , kChancePlayerId = -1 , kSimultaneousPlayerId = -2 , kInvalidPlayer = -3 ,
kTerminalPlayerId = -4 , kMeanFieldPlayerId = -5
}
enum class StateType { kTerminal , kChance , kDecision , kMeanField }
enum class TensorLayout { kHWC , kCHW }
Functions
std::vector< std::vector< Action > > CollectActions (const State &state)
std::vector< double > EvaluateBots (State *state, const std::vector< Bot * > &bots, int seed)
std::vector< double > EvaluateBots (const Game &game, const std::vector< Bot * > &bots, int seed)
std::vector< double > EvaluateBots (const Game &game, const std::vector< Bot * > &bots)
const std::string GameToNFGString (const Game &game)
std::ostream & operator<< (std::ostream &os, const ActionObservationHistory &aoh)
std::ostream & operator<< (std::ostream &os, const PublicObservationHistory &poh)
void init_pyspiel_xinxin (::pybind11::module &m)
std::string HunlGameString (const std::string &betting_abstraction)
std::string HulhGameString (const std::string &betting_abstraction)
std::string TurnBasedGoofspielGameString (int num_cards)
int RandomSimulation (std::mt19937 *rng, const Game &game, bool verbose)
void RandomSimBenchmark (const std::string &game_def, int num_sims, bool verbose)
GameParameter DeserializeGameParameter (const std::string &data, const std::string &delimiter)
std::string SerializeGameParameters (const GameParameters &game_params, const std::string &name_delimiter, const std::string &parameter_delimeter)
GameParameters DeserializeGameParameters (const std::string &data, const std::string &name_delimiter, const std::string &parameter_delimeter)
std::string GameParametersToString (const GameParameters &game_params)
GameParameter GameParameterFromString (const std::string &str)
GameParameters GameParametersFromString (const std::string &game_string)
std::string GameParameterTypeToString (const GameParameter::Type &type)
bool IsParameterSpecified (const GameParameters &table, const std::string &key)
template<typename T >
T ParameterValue (const GameParameters &params, const std::string &key, absl::optional< T > default_value=absl::nullopt)
void WriteAndLoadGame (std::string game_name)
std::vector< double > Negative (std::vector< double > &&vector)
std::shared_ptr< const Game > Factory (const GameParameters &params)
REGISTER_SPIEL_GAME (kGameType, Factory)
std::shared_ptr< const TensorGame > ExtensiveToTensorGame (const Game &game)
std::shared_ptr< const Game > CreateRepeatedGame (const Game &stage_game, const GameParameters &params)
std::shared_ptr< const Game > CreateRepeatedGame (const std::string &stage_game_name, const GameParameters &params)
std::shared_ptr< const Game > ConvertToRNR (const Game &game, Player fixed_player, double p, std::shared_ptr< Policy > fixed_policy)
std::vector< Action > HistoryFromString (const std::string &str)
std::unique_ptr< State > StateFromHistory (std::shared_ptr< const Game > game, const std::vector< Action > &history)
std::shared_ptr< const Game > ConvertToTurnBased (const Game &game)
std::shared_ptr< const Game > LoadGameAsTurnBased (const std::string &name)
std::shared_ptr< const Game > LoadGameAsTurnBased (const std::string &name, const GameParameters &params)
std::vector< double > SubtractMean (std::vector< double > &&vec)
void init_pyspiel_gamut (::pybind11::module &m)
std::shared_ptr< Observer > MakeSingleTensorObserver (const Game &game, absl::optional< IIGObservationType > iig_obs_type, const GameParameters &params)
std::vector< float > TensorFromObserver (const State &state, const Observer &observer)
std::vector< int > ObserverTensorShape (const State &state, const Observer &observer)
void SetProb (ActionsAndProbs *actions_and_probs, Action action, double prob)
double GetProb (const ActionsAndProbs &action_and_probs, Action action)
Action GetAction (const ActionsAndProbs &action_and_probs)
ActionsAndProbs ToDeterministicPolicy (const ActionsAndProbs &actions_and_probs, Action action)
bool StatePoliciesEqual (const ActionsAndProbs &state_policy1, const ActionsAndProbs &state_policy2, double float_tolerance)
ActionsAndProbs GetDeterministicPolicy (const std::vector< Action > &legal_actions, Action action)
ActionsAndProbs UniformStatePolicy (const std::vector< Action > &actions)
ActionsAndProbs UniformStatePolicy (const State &state)
ActionsAndProbs UniformStatePolicy (const State &state, Player player)
ActionsAndProbs FirstActionStatePolicy (const State &state)
ActionsAndProbs FirstActionStatePolicy (const State &state, Player player)
std::unique_ptr< Policy > DeserializePolicy (const std::string &serialized, std::string delimiter)
std::unique_ptr< TabularPolicy > DeserializeTabularPolicy (const std::string &serialized, std::string delimiter)
TabularPolicy GetEmptyTabularPolicy (const Game &game, bool initialize_to_uniform, Player player)
TabularPolicy GetUniformPolicy (const Game &game)
template<typename RandomNumberDistribution >
TabularPolicy SamplePolicy (const Game &game, int seed, RandomNumberDistribution &dist, Player player)
TabularPolicy GetRandomPolicy (const Game &game, int seed, Player player)
TabularPolicy GetFlatDirichletPolicy (const Game &game, int seed, Player player)
TabularPolicy GetRandomDeterministicPolicy (const Game &game, int seed, Player player)
TabularPolicy GetFirstActionPolicy (const Game &game)
TabularPolicy ToTabularPolicy (const Game &game, const Policy *policy)
TabularPolicy GetPrefActionPolicy (const Game &game, const std::vector< Action > &pref_actions)
std::string PrintPolicy (const ActionsAndProbs &policy)
TabularPolicy ToJointTabularPolicy (const std::vector< TabularPolicy > &policies, bool check_no_overlap)
void init_pyspiel_algorithms_corr_dist (py::module &m)
void init_pyspiel_algorithms_corr_dist (::pybind11::module &m)
void init_pyspiel_algorithms_trajectories (py::module &m)
void init_pyspiel_algorithms_trajectories (::pybind11::module &m)
void init_pyspiel_bots (py::module &m)
void init_pyspiel_bots (::pybind11::module &m)
void init_pyspiel_game_transforms (py::module &m)
void init_pyspiel_game_transforms (::pybind11::module &m)
void init_pyspiel_games_backgammon (::pybind11::module &m)
void init_pyspiel_games_bargaining (::pybind11::module &m)
void init_pyspiel_games_bridge (py::module &m)
void init_pyspiel_games_bridge (::pybind11::module &m)
void init_pyspiel_games_chess (::pybind11::module &m)
void init_pyspiel_games_colored_trails (::pybind11::module &m)
void init_pyspiel_games_dots_and_boxes (::pybind11::module &m)
void init_pyspiel_games_euchre (py::module &m)
void init_pyspiel_games_euchre (::pybind11::module &m)
void init_pyspiel_games_gin_rummy (py::module &m)
void init_pyspiel_games_gin_rummy (::pybind11::module &m)
void init_pyspiel_games_kuhn_poker (::pybind11::module &m)
void init_pyspiel_games_leduc_poker (::pybind11::module &m)
void init_pyspiel_games_negotiation (::pybind11::module &m)
void init_pyspiel_games_tarok (py::module &m)
void init_pyspiel_games_tarok (::pybind11::module &m)
void init_pyspiel_games_tiny_bridge (::pybind11::module &m)
void init_pyspiel_games_trade_comm (::pybind11::module &m)
void init_pyspiel_games_universal_poker (::pybind11::module &m)
void init_pyspiel_observer (py::module &m)
void init_pyspiel_observer (::pybind11::module &m)
void init_pyspiel_policy (py::module &m)
void init_pyspiel_policy (::pybind11::module &m)
void RegisterPyGame (const GameType &game_type, py::function creator)
py::dict PyDict (const State &state)
py::dict decode_dict (const absl::string_view str)
std::string encode_dict (py::dict dict)
void init_pyspiel_utils (py::module &m)
void init_pyspiel_utils (::pybind11::module &m)
std::ostream & operator<< (std::ostream &os, const StateType &type)
bool IsGameRegistered (const std::string &short_name)
std::vector< std::string > RegisteredGames ()
std::vector< GameType > RegisteredGameTypes ()
std::shared_ptr< const Game > DeserializeGame (const std::string &serialized)
std::shared_ptr< const Game > LoadGame (const std::string &game_string)
std::shared_ptr< const Game > LoadGame (const std::string &short_name, const GameParameters &params)
std::shared_ptr< const Game > LoadGame (GameParameters params)
void NormalizePolicy (ActionsAndProbs *policy)
std::pair< Action, double > SampleAction (const ActionsAndProbs &outcomes, absl::BitGenRef rng)
std::pair< Action, double > SampleAction (const ActionsAndProbs &outcomes, double z)
std::string SerializeGameAndState (const Game &game, const State &state)
std::pair< std::shared_ptr< const Game >, std::unique_ptr< State > > DeserializeGameAndState (const std::string &serialized_state)
std::ostream & operator<< (std::ostream &stream, GameType::Dynamics value)
std::istream & operator>> (std::istream &stream, GameType::Dynamics &var)
std::ostream & operator<< (std::ostream &stream, GameType::ChanceMode value)
std::ostream & operator<< (std::ostream &stream, const State &state)
std::istream & operator>> (std::istream &stream, GameType::ChanceMode &var)
std::ostream & operator<< (std::ostream &stream, GameType::Information value)
std::istream & operator>> (std::istream &stream, GameType::Information &var)
std::ostream & operator<< (std::ostream &stream, GameType::Utility value)
std::istream & operator>> (std::istream &stream, GameType::Utility &var)
std::ostream & operator<< (std::ostream &stream, GameType::RewardModel value)
std::istream & operator>> (std::istream &stream, GameType::RewardModel &var)
std::string GameTypeToString (const GameType &game_type)
GameType GameTypeFromString (const std::string &game_type_str)
std::ostream & operator<< (std::ostream &os, const State::PlayerAction &action)
std::vector< std::string > ActionsToStrings (const State &state, const std::vector< Action > &actions)
std::string ActionsToString (const State &state, const std::vector< Action > &actions)
void SpielFatalErrorWithStateInfo (const std::string &error_msg, const Game &game, const State &state)
std::pair< std::shared_ptr< const Game >, std::unique_ptr< State > > BuildStateFromHistoryString (const std::string &game_string, const std::string &history, int max_steps)
std::unique_ptr< Bot > MakeUniformRandomBot (Player player_id, int seed)
std::unique_ptr< Bot > MakePolicyBot (int seed, std::shared_ptr< Policy > policy)
std::unique_ptr< Bot > MakePolicyBot (const Game &game, Player player_id, int seed, std::shared_ptr< Policy > policy)
std::unique_ptr< Bot > MakeFixedActionPreferenceBot (Player player_id, const std::vector< Action > &actions)
std::unique_ptr< Bot > MakeStatefulRandomBot (const Game &game, Player player_id, int seed)
std::vector< std::string > RegisteredBots ()
bool IsBotRegistered (const std::string &bot_name)
std::unique_ptr< Bot > LoadBot (const std::string &bot_name, const std::shared_ptr< const Game > &game, Player player_id)
std::unique_ptr< Bot > LoadBot (const std::string &bot_name, const std::shared_ptr< const Game > &game, Player player_id, const GameParameters &params)
std::vector< std::string > BotsThatCanPlayGame (const Game &game, Player player_id)
std::vector< std::string > BotsThatCanPlayGame (const Game &game)
int NextPlayerRoundRobin (Player player, int nplayers)
int PreviousPlayerRoundRobin (Player player, int nplayers)
Action RankActionMixedBase (const std::vector< int > &bases, const std::vector< int > &digits)
std::vector< int > UnrankActionMixedBase (Action action, const std::vector< int > &bases)
absl::optional< std::string > FindFile (const std::string &filename, int levels)
std::string FormatDouble (double value)
void SpielDefaultErrorHandler (const std::string &error_msg)
void SetErrorHandler (ErrorHandler new_error_handler)
void SpielFatalError (const std::string &error_msg)
std::ostream & operator<< (std::ostream &stream, const absl::nullopt_t &v)
void Normalize (absl::Span< double > weights)
std::string BoolToStr (bool b)
template<class A , class B >
std::string VectorOfPairsToString (std::vector< std::pair< A, B > > &vec, const std::string &delimiter, const std::string &pair_delimiter)
bool StrContainsIgnoreCase (const std::string &haystack, const std::string &needle)
template<typename T >
std::ostream & operator<< (std::ostream &stream, const std::unique_ptr< T > &v)
template<typename T , typename U >
std::ostream & operator<< (std::ostream &stream, const std::pair< T, U > &v)
template<typename T >
std::ostream & operator<< (std::ostream &stream, const std::vector< T > &v)
template<typename T , std::size_t N>
std::ostream & operator<< (std::ostream &stream, const std::array< T, N > &v)
template<typename T >
std::ostream & operator<< (std::ostream &stream, const absl::optional< T > &v)
template<typename T >
std::ostream & operator<< (std::ostream &stream, absl::Span< T > v)
constexpr float FloatingPointDefaultTolerance ()
constexpr float ProbabilityDefaultTolerance ()
template<class A , class B >
std::string VectorOfPairsToString (const std::vector< std::pair< A, B > > &vec, const std::string &delimiter, const std::string &pair_delimiter)
template<typename T >
bool Near (T a, T b)
template<typename T >
bool Near (T a, T b, T epsilon)
template<typename T >
bool AllNear (const std::vector< T > &vector1, const std::vector< T > &vector2, T epsilon)
template<typename To , typename From >
To down_cast (From *f)
template<typename To , typename From >
To down_cast (From &f)
bool NextPowerSetMask (std::vector< bool > *bs)
std::vector< std::vector< int > > GenerateMasks (std::vector< int > &values, int k, std::vector< int > &permutation_stack)
int Factorial (int n)
template<typename T >
std::vector< std::vector< T > > Permutations (std::vector< T > v)
template<typename T >
std::vector< std::vector< T > > SubsetsOfSize (const std::vector< T > &v, int k)
template<typename T >
std::vector< std::vector< T > > PowerSet (const std::vector< T > &v)
template<typename T >
std::vector< std::vector< T > > VariationsWithoutRepetition (const std::vector< T > &v, int k)
template<typename T >
std::vector< T > UnrankPermutation (const std::vector< T > &v, int k)
template<typename InputSequence1 , typename InputSequence2 , typename ZippedOutputIterator >
void Zip (const InputSequence1 &first1, const InputSequence1 &last1, const InputSequence2 &first2, ZippedOutputIterator &output)
void Init (const char *usage, int *argc, char ***argv, bool remove_flags)
bool RunPython (const std::string &python_command, const std::string &module, const std::vector< std::string > &args)
bool RunPython (const std::string &module, const std::vector< std::string > &args)
void LogUsage ()
Variables
constexpr const char * kDefaultNameDelimiter = "="
constexpr const char * kDefaultParameterDelimiter = "|||"
constexpr const char * kDefaultInternalDelimiter = "***"
const GameType kGameType
constexpr Player kDefaultFixedPlayer = 0
constexpr double kDefaultP = 0.5
constexpr int kNumHeaderBytes = 1
constexpr IIGObservationType kDefaultObsType
constexpr IIGObservationType kInfoStateObsType
constexpr IIGObservationType kPublicObsType
constexpr IIGObservationType kPublicStateObsType
constexpr IIGObservationType kPrivateObsType
constexpr const absl::string_view kTagHistory = "history="
constexpr const absl::string_view kTagMoveNumber = "move_number="
constexpr const absl::string_view kTagDict = "__dict__="
constexpr Action kInvalidAction = -1
ErrorHandler error_handler = SpielDefaultErrorHandler
constexpr const char * kDefaultPythonCommand = "python3"
Detailed Description
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
Typedef Documentation
Action
using open_spiel.Action = int64_t
Definition at line 133 of file spiel_utils.h.
ActionsAndProbs
using open_spiel.ActionsAndProbs = std::vector<std::pair<Action, double>>
Definition at line 198 of file spiel.h.
ErrorHandler
using open_spiel.ErrorHandler = void (*)(const std::string&)
Definition at line 355 of file spiel_utils.h.
GameParameters
using open_spiel.GameParameters = std::map<std::string, GameParameter>
Definition at line 37 of file game_parameters.h.
HistoryDistribution
using open_spiel.HistoryDistribution
Initial value:
    std::pair<std::vector<std::unique_ptr<State>>, std::vector<double>>
Definition at line 202 of file spiel.h.
ObservationParams
using open_spiel.ObservationParams = GameParameters
Definition at line 64 of file observer.h.
Player
using open_spiel.Player = int
Definition at line 132 of file spiel_utils.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kFixedAction
kFreeAction
Definition at line 36 of file restricted_nash_response.h.
{ kFixedAction = 0, kFreeAction = 1 };
CompressionScheme
enum open_spiel::CompressionScheme : char
Enumerator
kCompressionNone
kCompressionBinary
Definition at line 246 of file observer.cc.
                       : char {
  kCompressionNone,   // We weren't able to compress the data.
  kCompressionBinary  // Data is binary (all elements zero or one).
};
PlayerId
enum open_spiel::PlayerId
Enumerator
kDefaultPlayerId
kChancePlayerId
kSimultaneousPlayerId
kInvalidPlayer
kTerminalPlayerId
kMeanFieldPlayerId
Definition at line 24 of file spiel_globals.h.
              {
  // Player 0 is always valid, and is used in single-player games.
  kDefaultPlayerId = 0,
  // The fixed player id for chance/nature.
  kChancePlayerId = -1,
  // What is returned as a player id when the game is simultaneous.
  kSimultaneousPlayerId = -2,
  // Invalid player.
  kInvalidPlayer = -3,
  // What is returned as the player id on terminal nodes.
  kTerminalPlayerId = -4,
  // player id of a mean field node
  kMeanFieldPlayerId = -5
};
PrivateInfoType
enum class open_spiel::PrivateInfoType strong
Enumerator
kNone
kSinglePlayer
kAllPlayers
Definition at line 213 of file observer.h.
{
  kNone,          // No private information.
  kSinglePlayer,  // Private information for the observing player only (i.e.
                  // the player passed to WriteTensor / StringFrom).
  kAllPlayers     // Private information for all players.
};
StateType
enum class open_spiel::StateType strong
Enumerator
kTerminal
kChance
kDecision
kMeanField
Definition at line 42 of file spiel_globals.h.
                     {
  kTerminal,   // If the state is terminal.
  kChance,     // If the player to act equals kChanceId.
  kDecision,   // If a player other than kChanceId (and kMeanField) is acting.
  // The Mean Field state. We expect that logic external to the game will update
  // the state distribution in each game state. See details in
  // games/mfg/README.md.
  kMeanField,
};
TensorLayout
enum class open_spiel::TensorLayout strong
Enumerator
kHWC
kCHW
Definition at line 56 of file spiel_globals.h.
{
  kHWC,  // indexes are in the order (height, width, channels)
  kCHW,  // indexes are in the order (channels, height, width)
};
Function Documentation
ActionsToString()
std::string open_spiel::ActionsToString (const State & state, const std::vector< Action > & actions)
Definition at line 836 of file spiel.cc.
{
  return absl::StrCat(
      "[", absl::StrJoin(ActionsToStrings(state, actions), ", "), "]");
}
References ActionsToStrings(), state, absl::StrCat(), and absl::StrJoin().
ActionsToStrings()
std::vector< std::string > open_spiel::ActionsToStrings (const State & state, const std::vector< Action > & actions)
Definition at line 828 of file spiel.cc.
{
  std::vector<std::string> out;
  out.reserve(actions.size());
  for (Action action : actions) out.push_back(state.ActionToString(action));
  return out;
}
References action, out, and state.
Referenced by ActionsToString().
AllNear()
template<typename T > bool open_spiel::AllNear (const std::vector< T > & vector1, const std::vector< T > & vector2, T epsilon)
Definition at line 200 of file spiel_utils.h.
{
  if (vector1.size() != vector2.size()) {
    return false;
  }
  for (int i = 0; i < vector1.size(); ++i) {
    if (!Near(vector1[i], vector2[i], epsilon)) {
      return false;
    }
  }
  return true;
}
References i, and Near().
Referenced by open_spiel::matrix_game::MatrixGame::ApproxEqual(), and open_spiel::tensor_game::TensorGame::ApproxEqual().
BoolToStr()
std::string open_spiel::BoolToStr (bool b)
Definition at line 153 of file spiel_utils.cc.
{ return b ? "true" : "false"; }
References b.
BotsThatCanPlayGame() [1/2]
std::vector< std::string > open_spiel::BotsThatCanPlayGame (const Game & game)
Definition at line 379 of file spiel_bots.cc.
{
  return BotRegisterer::BotsThatCanPlayGame(game);
}
References open_spiel::BotRegisterer::BotsThatCanPlayGame().
BotsThatCanPlayGame() [2/2]
std::vector< std::string > open_spiel::BotsThatCanPlayGame (const Game & game, Player player_id)
Definition at line 374 of file spiel_bots.cc.
{
  return BotRegisterer::BotsThatCanPlayGame(game, player_id);
}
References open_spiel::BotRegisterer::BotsThatCanPlayGame().
Referenced by init_pyspiel_bots().
BuildStateFromHistoryString()
std::pair< std::shared_ptr< const Game >, std::unique_ptr< State > > open_spiel::BuildStateFromHistoryString (const std::string & game_string, const std::string & history, int max_steps)
Definition at line 851 of file spiel.cc.
                   {
  std::pair<std::shared_ptr<const Game>, std::unique_ptr<State>> game_and_state;
  game_and_state.first = LoadGame(game_string);
  game_and_state.second = game_and_state.first->NewInitialState();
  std::string history_copy(absl::StripAsciiWhitespace(history));
  if (history_copy[0] == '[') {
    history_copy = history_copy.substr(1);
  }
  if (history_copy[history_copy.length() - 1] == ']') {
    history_copy = history_copy.substr(0, history_copy.length() - 1);
  }
  std::vector<Action> legal_actions;
  State* state = game_and_state.second.get();
  int steps = 0;
  std::vector<std::string> parts = absl::StrSplit(history_copy, ',');
  for (const std::string& part : parts) {
    if (max_steps > 0 && steps >= max_steps) {
      break;
    }
    Action action;
    bool atoi_ret = absl::SimpleAtoi(absl::StripAsciiWhitespace(part), &action);
    if (!atoi_ret) {
      SpielFatalError(absl::StrCat("Problem parsing action: ", part));
    }
    legal_actions = state->LegalActions();
    if (absl::c_find(legal_actions, action) == legal_actions.end()) {
      SpielFatalError(absl::StrCat("Illegal move detected!\nState:\n",
                                   state->ToString(), "\nAction: ", action,
                                   " (", state->ActionToString(action), ")\n",
                                   "History: ", state->HistoryString()));
    }
    state->ApplyAction(action);
    steps++;
  }
  return game_and_state;
}
References action, absl::c_find(), LoadGame(), absl::SimpleAtoi(), SpielFatalError(), state, absl::StrCat(), absl::StripAsciiWhitespace(), and absl::StrSplit().
CollectActions()
std::vector< std::vector< Action > > open_spiel::CollectActions (const State & state)
Definition at line 24 of file action_view.cc.
{
  std::vector<std::vector<Action>> legal_actions;
  if (state.IsSimultaneousNode()) {
    legal_actions = std::vector<std::vector<Action>>(state.NumPlayers());
    for (int i = 0; i < state.NumPlayers(); ++i) {
      legal_actions[i] = state.LegalActions(i);
    }
  } else {
    legal_actions = std::vector<std::vector<Action>>{state.LegalActions()};
  }
  return legal_actions;
}
References i, and state.
ConvertToRNR()
std::shared_ptr< const Game > open_spiel::ConvertToRNR (const Game & game, Player fixed_player, double p, std::shared_ptr< Policy > fixed_policy)
Definition at line 339 of file restricted_nash_response.cc.
{
  return std::shared_ptr<const RestrictedNashResponseGame>(
      new RestrictedNashResponseGame(game.shared_from_this(), fixed_player, p,
                                     fixed_policy));
}
ConvertToTurnBased()
std::shared_ptr< const Game > open_spiel::ConvertToTurnBased (const Game & game)
Definition at line 282 of file turn_based_simultaneous_game.cc.
{
  SPIEL_CHECK_EQ(game.GetType().dynamics, GameType::Dynamics::kSimultaneous);
  return std::shared_ptr<const TurnBasedSimultaneousGame>(
      new TurnBasedSimultaneousGame(game.shared_from_this()));
}
References open_spiel::GameType::kSimultaneous, and SPIEL_CHECK_EQ.
Referenced by open_spiel::algorithms::CCEDist(), open_spiel::algorithms::CEDist(), define_julia_module(), open_spiel::algorithms::ExpectedValues(), init_pyspiel_game_transforms(), LoadGameAsTurnBased(), and LoadGameAsTurnBased().
CreateRepeatedGame() [1/2]
std::shared_ptr< const Game > open_spiel::CreateRepeatedGame (const Game & stage_game, const GameParameters & params)
Definition at line 257 of file repeated_game.cc.
{
  // The stage game must be a deterministic normal-form (one-shot) game.
  SPIEL_CHECK_EQ(stage_game.MaxGameLength(), 1);
  SPIEL_CHECK_EQ(stage_game.GetType().dynamics,
                 GameType::Dynamics::kSimultaneous);
  SPIEL_CHECK_EQ(stage_game.GetType().chance_mode,
                 GameType::ChanceMode::kDeterministic);
  return std::make_shared<const RepeatedGame>(stage_game.shared_from_this(),
                                              params);
}
References open_spiel::GameType::chance_mode, open_spiel::GameType::dynamics, open_spiel::Game::GetType(), open_spiel::GameType::kDeterministic, open_spiel::GameType::kSimultaneous, open_spiel::Game::MaxGameLength(), and SPIEL_CHECK_EQ.
Referenced by CreateRepeatedGame(), and init_pyspiel_game_transforms().
CreateRepeatedGame() [2/2]
std::shared_ptr< const Game > open_spiel::CreateRepeatedGame (const std::string & stage_game_name, const GameParameters & params)
Definition at line 269 of file repeated_game.cc.
{
  auto game = LoadGame(stage_game_name);
  // The stage game must be a deterministic normal-form (one-shot) game.
  SPIEL_CHECK_EQ(game->MaxGameLength(), 1);
  SPIEL_CHECK_EQ(game->GetType().dynamics, GameType::Dynamics::kSimultaneous);
  SPIEL_CHECK_EQ(game->GetType().chance_mode,
                 GameType::ChanceMode::kDeterministic);
  return CreateRepeatedGame(*game, params);
}
References CreateRepeatedGame(), open_spiel::GameType::kDeterministic, open_spiel::GameType::kSimultaneous, LoadGame(), and SPIEL_CHECK_EQ.
decode_dict()
py::dict open_spiel::decode_dict (const absl::string_view str)
Definition at line 313 of file python_games.cc.
{
  std::string bytes;
  SPIEL_CHECK_TRUE(absl::Base64Unescape(str, &bytes));
  py::function pickle_loads = py::module::import("pickle").attr("loads");
  return pickle_loads(py::bytes(bytes));
}
References absl::Base64Unescape(), and SPIEL_CHECK_TRUE.
Referenced by open_spiel::PyState::Deserialize().
DeserializeGame()
std::shared_ptr< const Game > open_spiel::DeserializeGame (const std::string & serialized)
Definition at line 205 of file spiel.cc.
{
  std::pair<std::string, std::string> game_and_rng_state =
      absl::StrSplit(serialized, kSerializeGameRNGStateSectionHeader);
  // Remove the trailing "\n" from the game section.
  if (!game_and_rng_state.first.empty() &&
      game_and_rng_state.first.back() == '\n') {
    game_and_rng_state.first.pop_back();
  }
  std::shared_ptr<const Game> game = LoadGame(game_and_rng_state.first);
  if (!game_and_rng_state.second.empty()) {
    // Game is implicitly stochastic.
    // Remove the trailing "\n" from the RNG state section.
    if (game_and_rng_state.second.back() == '\n') {
      game_and_rng_state.second.pop_back();
    }
    game->SetRNGState(game_and_rng_state.second);
  }
  return game;
}
References LoadGame(), and absl::StrSplit().
Referenced by DeserializeGameAndState(), and open_spiel::algorithms::PartiallyDeserializeCFRSolver().
DeserializeGameAndState()
std::pair< std::shared_ptr< const Game >, std::unique_ptr< State > > open_spiel::DeserializeGameAndState (const std::string & serialized_state)
Definition at line 467 of file spiel.cc.
{
  std::vector<std::string> lines = absl::StrSplit(serialized_state, '\n');
  enum Section { kInvalid = -1, kMeta = 0, kGame = 1, kState = 2 };
  std::vector<std::string> section_strings = {"", "", ""};
  Section cur_section = kInvalid;
  for (int i = 0; i < lines.size(); ++i) {
    if (lines[i].empty() || lines[i].at(0) == '#') {
      // Skip comments and blank lines.
    } else if (lines[i] == kSerializeMetaSectionHeader) {
      SPIEL_CHECK_EQ(cur_section, kInvalid);
      cur_section = kMeta;
    } else if (lines[i] == kSerializeGameSectionHeader) {
      SPIEL_CHECK_EQ(cur_section, kMeta);
      cur_section = kGame;
    } else if (lines[i] == kSerializeStateSectionHeader) {
      SPIEL_CHECK_EQ(cur_section, kGame);
      cur_section = kState;
    } else {
      SPIEL_CHECK_NE(cur_section, kInvalid);
      absl::StrAppend(&section_strings[cur_section], lines[i], "\n");
    }
  }
  // Remove the trailing "\n" from the game and state sections.
  if (!section_strings[kGame].empty() &&
      section_strings[kGame].back() == '\n') {
    section_strings[kGame].pop_back();
  }
  if (!section_strings[kState].empty() &&
      section_strings[kState].back() == '\n') {
    section_strings[kState].pop_back();
  }
  // We currently just ignore the meta section.
  std::shared_ptr<const Game> game = DeserializeGame(section_strings[kGame]);
  std::unique_ptr<State> state =
      game->DeserializeState(section_strings[kState]);
  return std::pair<std::shared_ptr<const Game>, std::unique_ptr<State>>(
      game, std::move(state));
}
References DeserializeGame(), i, SPIEL_CHECK_EQ, SPIEL_CHECK_NE, state, absl::StrAppend(), and absl::StrSplit().
Referenced by define_julia_module(), init_pyspiel_games_bridge(), init_pyspiel_games_euchre(), init_pyspiel_games_gin_rummy(), init_pyspiel_games_tarok(), and open_spiel::testing::TestSerializeDeserialize().
DeserializeGameParameter()
GameParameter open_spiel::DeserializeGameParameter (const std::string & data, const std::string & delimiter)
Definition at line 93 of file game_parameters.cc.
{
  std::vector<std::string> parts = absl::StrSplit(data, delimiter);
  SPIEL_CHECK_EQ(parts.size(), 3);
  bool mandatory = (parts[2] == "True" || parts[2] == "true");
  if (parts[0] == "kUnset") {
    return GameParameter(GameParameter::Type::kUnset, mandatory);
  } else if (parts[0] == "kInt") {
    int value;
    SPIEL_CHECK_TRUE(absl::SimpleAtoi(parts[1], &value));
    return GameParameter(value, mandatory);
  } else if (parts[0] == "kDouble") {
    double value;
    SPIEL_CHECK_TRUE(absl::SimpleAtod(parts[1], &value));
    return GameParameter(value, mandatory);
  } else if (parts[0] == "kString") {
    return GameParameter(
        absl::StrReplaceAll(parts[1], {{kSerializedNewline, "\n"}}), mandatory);
  } else if (parts[0] == "kBool") {
    return GameParameter(parts[1] == "True" || parts[1] == "true", mandatory);
  } else if (parts[0] == "kGame") {
    return GameParameter(DeserializeGameParameters(parts[1]), mandatory);
  } else {
    SpielFatalError(absl::StrCat("Unrecognized type: ", parts[0]));
  }
}
References DeserializeGameParameters(), open_spiel::GameParameter::kUnset, absl::SimpleAtod(), absl::SimpleAtoi(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, SpielFatalError(), absl::StrCat(), absl::StrReplaceAll(), absl::StrSplit(), and value.
Referenced by DeserializeGameParameters().
DeserializeGameParameters()
GameParameters open_spiel::DeserializeGameParameters (const std::string & data, const std::string & name_delimiter, const std::string & parameter_delimeter)
Definition at line 136 of file game_parameters.cc.
{
  GameParameters game_params;
  std::vector<std::string> parts = absl::StrSplit(data, parameter_delimeter);
  for (const auto& part : parts) {
    if (!part.empty()) {
      std::pair<std::string, std::string> pair =
          absl::StrSplit(part, name_delimiter);
      game_params.insert(std::pair<std::string, GameParameter>(
          pair.first, DeserializeGameParameter(pair.second)));
    }
  }
  return game_params;
}
References DeserializeGameParameter(), pair, and absl::StrSplit().
Referenced by DeserializeGameParameter(), and GameTypeFromString().
DeserializePolicy()
std::unique_ptr< Policy > open_spiel::DeserializePolicy (const std::string & serialized, std::string delimiter)
Definition at line 140 of file policy.cc.
{
  // Classs identity is the very first line, see Policy::Serialize
  // for more info.
  std::pair<std::string, absl::string_view> cls_and_content =
      absl::StrSplit(serialized, absl::MaxSplits(':', 1));
  std::string class_identity = cls_and_content.first;
  if (class_identity == "TabularPolicy") {
    return DeserializeTabularPolicy(serialized, delimiter);
  } else if (class_identity == "UniformPolicy") {
    return std::make_unique<UniformPolicy>();
  } else {
    SpielFatalError(absl::StrCat("Deserialization of ", class_identity,
                                 " is not supported."));
  }
}
References DeserializeTabularPolicy(), absl::MaxSplits(), SpielFatalError(), absl::StrCat(), and absl::StrSplit().
Referenced by open_spiel::algorithms::DeserializeExternalSamplingMCCFRSolver(), and open_spiel::algorithms::DeserializeOutcomeSamplingMCCFRSolver().
DeserializeTabularPolicy()
std::unique_ptr< TabularPolicy > open_spiel::DeserializeTabularPolicy (const std::string & serialized, std::string delimiter)
Definition at line 161 of file policy.cc.
{
  // Classs identity is the very first line, see Policy::Serialize
  // for more info.
  std::pair<std::string, absl::string_view> cls_and_content =
      absl::StrSplit(serialized, absl::MaxSplits(':', 1));
  SPIEL_CHECK_EQ(cls_and_content.first, "TabularPolicy");
  std::unique_ptr<TabularPolicy> res = std::make_unique<TabularPolicy>();
  if (cls_and_content.second.empty()) return res;
  std::vector<absl::string_view> splits =
      absl::StrSplit(cls_and_content.second, delimiter);
  // Insert the actual values
  Action action;
  double prob;
  for (int i = 0; i < splits.size(); i += 2) {
    std::vector<absl::string_view> policy_values =
        absl::StrSplit(splits.at(i + 1), ',');
    ActionsAndProbs res_policy;
    res_policy.reserve(policy_values.size());
    for (absl::string_view policy_value : policy_values) {
      std::pair<absl::string_view, absl::string_view> action_and_prob =
          absl::StrSplit(policy_value, '=');
      SPIEL_CHECK_TRUE(absl::SimpleAtoi(action_and_prob.first, &action));
      absl::from_chars(
          action_and_prob.second.data(),
          action_and_prob.second.data() + action_and_prob.second.size(), prob);
      res_policy.push_back({action, prob});
    }
    res->SetStatePolicy(std::string(splits.at(i)), res_policy);
  }
  return res;
}
References action, absl::from_chars(), i, absl::MaxSplits(), absl::SimpleAtoi(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and absl::StrSplit().
Referenced by DeserializePolicy().
down_cast() [1/2]
template<typename To , typename From > To open_spiel::down_cast (From & f) inline
Definition at line 412 of file spiel_utils.h.
{
  typedef typename std::remove_reference<To>::type* ToAsPointer;
#if !defined(NDEBUG)
  if (dynamic_cast<ToAsPointer>(&f) == nullptr) {
    std::string from = typeid(From).name();
    std::string to = typeid(From).name();
    SpielFatalError(
        absl::StrCat("Cast failure: could not cast a reference from '", from,
                     "' to '", to, "'"));
  }
#endif
  return *static_cast<ToAsPointer>(&f);
}
References from, name, SpielFatalError(), absl::StrCat(), and to.
down_cast() [2/2]
template<typename To , typename From > To open_spiel::down_cast (From * f) inline
Definition at line 397 of file spiel_utils.h.
{
#if !defined(NDEBUG)
  if (f != nullptr && dynamic_cast<To>(f) == nullptr) {
    std::string from = typeid(From).name();
    std::string to = typeid(From).name();
    SpielFatalError(
        absl::StrCat("Cast failure: could not cast a pointer from '", from,
                     "' to '", to, "'"));
  }
#endif
  return static_cast<To>(f);
}
References from, name, SpielFatalError(), absl::StrCat(), and to.
Referenced by open_spiel::matrix_game::MatrixGame::ApproxEqual(), open_spiel::tensor_game::TensorGame::ApproxEqual(), open_spiel::PyState::Clone(), open_spiel::PyGame::DeserializeState(), open_spiel::rbc::RbcState::game(), open_spiel::uci::UCIBot::InformAction(), open_spiel::algorithms::CEState::InformationStateString(), open_spiel::coordinated_mp::PenniesState::InformationStateString(), open_spiel::gin_rummy::GinRummyState::InformationStateString(), open_spiel::goofspiel::GoofspielState::InformationStateString(), open_spiel::kuhn_poker::KuhnState::InformationStateString(), open_spiel::leduc_poker::LeducState::InformationStateString(), open_spiel::liars_dice::ImperfectRecallLiarsDiceState::InformationStateString(), open_spiel::PyState::InformationStateString(), open_spiel::RestrictedNashResponseState::InformationStateString(), open_spiel::goofspiel::GoofspielState::InformationStateTensor(), open_spiel::kuhn_poker::KuhnState::InformationStateTensor(), open_spiel::leduc_poker::LeducState::InformationStateTensor(), open_spiel::PyState::InformationStateTensor(), open_spiel::RestrictedNashResponseState::InformationStateTensor(), open_spiel::sheriff::SheriffState::InformationStateTensor(), main(), open_spiel::coordinated_mp::PenniesState::ObservationString(), open_spiel::dark_chess::DarkChessState::ObservationString(), open_spiel::gin_rummy::GinRummyState::ObservationString(), open_spiel::goofspiel::GoofspielState::ObservationString(), open_spiel::kriegspiel::KriegspielState::ObservationString(), open_spiel::kuhn_poker::KuhnState::ObservationString(), open_spiel::leduc_poker::LeducState::ObservationString(), open_spiel::PyState::ObservationString(), open_spiel::rbc::RbcState::ObservationString(), open_spiel::RestrictedNashResponseState::ObservationString(), open_spiel::dark_chess::DarkChessState::ObservationTensor(), open_spiel::gin_rummy::GinRummyState::ObservationTensor(), open_spiel::goofspiel::GoofspielState::ObservationTensor(), open_spiel::kriegspiel::KriegspielState::ObservationTensor(), open_spiel::kuhn_poker::KuhnState::ObservationTensor(), open_spiel::leduc_poker::LeducState::ObservationTensor(), open_spiel::phantom_go::PhantomGoState::ObservationTensor(), open_spiel::PyState::ObservationTensor(), open_spiel::rbc::RbcState::ObservationTensor(), open_spiel::RestrictedNashResponseState::ObservationTensor(), open_spiel::matrix_game::MatrixGame::operator==(), open_spiel::tensor_game::TensorGame::operator==(), open_spiel::uci::RandomUciBot(), open_spiel::uci::UCIBot::RestartAt(), open_spiel::add_noise::AddNoiseState::Returns(), open_spiel::StartAtTransformationState::StartAtTransformationState(), open_spiel::uci::UCIBot::Step(), open_spiel::coordinated_mp::PenniesObserver::StringFrom(), open_spiel::dark_chess::DarkChessObserver::StringFrom(), open_spiel::gin_rummy::GinRummyObserver::StringFrom(), open_spiel::goofspiel::GoofspielObserver::StringFrom(), open_spiel::kriegspiel::KriegspielObserver::StringFrom(), open_spiel::kuhn_poker::KuhnObserver::StringFrom(), open_spiel::leduc_poker::LeducObserver::StringFrom(), open_spiel::phantom_go::PhantomGoObserver::StringFrom(), open_spiel::PyObserver::StringFrom(), open_spiel::rbc::RbcObserver::StringFrom(), open_spiel::RestrictedNashResponseObserver::StringFrom(), open_spiel::dark_chess::DarkChessObserver::WriteTensor(), open_spiel::gin_rummy::GinRummyObserver::WriteTensor(), open_spiel::goofspiel::GoofspielObserver::WriteTensor(), open_spiel::kriegspiel::KriegspielObserver::WriteTensor(), open_spiel::kuhn_poker::KuhnObserver::WriteTensor(), open_spiel::leduc_poker::LeducObserver::WriteTensor(), open_spiel::phantom_go::PhantomGoObserver::WriteTensor(), open_spiel::PyObserver::WriteTensor(), open_spiel::rbc::RbcObserver::WriteTensor(), and open_spiel::RestrictedNashResponseObserver::WriteTensor().
encode_dict()
std::string open_spiel::encode_dict (py::dict dict)
Definition at line 320 of file python_games.cc.
{
  py::function pickle_dumps = py::module::import("pickle").attr("dumps");
  py::bytes bytes = pickle_dumps(dict);
  return absl::Base64Escape(std::string(bytes));
}
References absl::Base64Escape().
Referenced by open_spiel::PyState::Serialize().
EvaluateBots() [1/3]
std::vector< double > open_spiel::EvaluateBots (const Game & game, const std::vector< Bot * > & bots)
Definition at line 74 of file evaluate_bots.cc.
{
  absl::Duration time_gap = absl::Now() - absl::UnixEpoch();
  std::mt19937 rng(absl::ToInt64Nanoseconds(time_gap));
  const int seed = absl::Uniform<int>(rng, std::numeric_limits<int>::min(),
                                      std::numeric_limits<int>::max());
  return EvaluateBots(game, bots, seed);
}
References EvaluateBots(), absl::Now(), absl::ToInt64Nanoseconds(), absl::Uniform(), and absl::UnixEpoch().
EvaluateBots() [2/3]
std::vector< double > open_spiel::EvaluateBots (const Game & game, const std::vector< Bot * > & bots, int seed)
Definition at line 68 of file evaluate_bots.cc.
{
  std::unique_ptr<State> state = game.NewInitialState();
  return EvaluateBots(state.get(), bots, seed);
}
References EvaluateBots(), and state.
EvaluateBots() [3/3]
std::vector< double > open_spiel::EvaluateBots (State * state, const std::vector< Bot * > & bots, int seed)
Definition at line 28 of file evaluate_bots.cc.
{
  const int num_players = bots.size();
  std::mt19937 rng(seed);
  std::vector<Action> joint_actions(bots.size());
  if (state->History().empty()) {
    for (auto bot : bots) bot->Restart();
  } else {
    for (auto bot : bots) bot->RestartAt(*state);
  }
  while (!state->IsTerminal()) {
    if (state->IsChanceNode()) {
      Action action = SampleAction(state->ChanceOutcomes(), rng).first;
      for (auto bot : bots) bot->InformAction(*state, kChancePlayerId, action);
      state->ApplyAction(action);
    } else if (state->IsSimultaneousNode()) {
      for (Player p = 0; p < num_players; ++p) {
        if (state->LegalActions(p).empty()) {
          joint_actions[p] = kInvalidAction;
        } else {
          joint_actions[p] = bots[p]->Step(*state);
        }
      }
      state->ApplyActions(joint_actions);
    } else {
      Player current_player = state->CurrentPlayer();
      Action action = bots[current_player]->Step(*state);
      for (Player p = 0; p < num_players; ++p) {
        if (p != current_player) {
          bots[p]->InformAction(*state, current_player, action);
        }
      }
      state->ApplyAction(action);
    }
  }
  // Return terminal utility.
  return state->Returns();
}
References action, kChancePlayerId, kInvalidAction, SampleAction(), and state.
Referenced by define_julia_module(), EvaluateBots(), EvaluateBots(), and init_pyspiel_bots().
ExtensiveToTensorGame()
std::shared_ptr< const tensor_game::TensorGame > open_spiel::ExtensiveToTensorGame (const Game & game)
Definition at line 54 of file normal_form_extensive_game.cc.
{
  std::vector<std::vector<std::string>> action_names(game.NumPlayers());
  GameType type = game.GetType();
  std::vector<algorithms::DeterministicTabularPolicy> policies;
  for (Player player = 0; player < game.NumPlayers(); ++player) {
    algorithms::DeterministicTabularPolicy policy(game, player);
    do {
      action_names[player].push_back(policy.ToString(/*delimiter=*/" --- "));
    } while (policy.NextPolicy());
    policy.ResetDefaultPolicy();
    policies.push_back(policy);
  }
  std::vector<const Policy*> policy_ptrs(policies.size());
    for (Player player = 0; player < game.NumPlayers(); ++player) {
      policy_ptrs[player] = &policies[player];
    }
  const std::unique_ptr<State> initial_state = game.NewInitialState();
  std::vector<std::vector<double>> utils(game.NumPlayers());
  bool last_entry;
  do {
    std::vector<double> returns = algorithms::ExpectedReturns(
        *initial_state, policy_ptrs, /*depth_limit=*/-1);
    for (Player player = 0; player < game.NumPlayers(); ++player) {
      utils[player].push_back(returns[player]);
    }
    last_entry = true;
    for (auto policy = policies.rbegin(); policy != policies.rend(); ++policy) {
      if (policy->NextPolicy()) {
        last_entry = false;
        break;
      } else {
        policy->ResetDefaultPolicy();
      }
    }
  } while (!last_entry);
  return tensor_game::CreateTensorGame(kGameType.short_name,
                                       "Normal-form " + type.long_name,
                                       action_names, utils);
}
References open_spiel::tensor_game::CreateTensorGame(), open_spiel::algorithms::ExpectedReturns(), kGameType, open_spiel::GameType::long_name, player, and open_spiel::GameType::short_name.
Referenced by Factory(), and init_pyspiel_game_transforms().
Factorial()
int open_spiel::Factorial (int n)
Definition at line 56 of file combinatorics.cc.
{ return n <= 1 ? 1 : n * Factorial(n - 1); }
References Factorial(), and n.
Referenced by open_spiel::pathfinding::PathfindingState::ChanceOutcomes(), Factorial(), open_spiel::pathfinding::PathfindingGame::MaxChanceOutcomes(), and UnrankPermutation().
Factory()
std::shared_ptr< const Game > open_spiel::Factory (const GameParameters & params)
Definition at line 48 of file normal_form_extensive_game.cc.
{
  return ExtensiveToTensorGame(*LoadGame(params.at("game").game_value()));
}
References ExtensiveToTensorGame(), and LoadGame().
Referenced by open_spiel::battleship::Factory().
FindFile()
absl::optional< std::string > open_spiel::FindFile (const std::string & filename, int levels)
Definition at line 81 of file spiel_utils.cc.
{
  std::string candidate_filename = filename;
  for (int i = 0; i <= levels; ++i) {
    if (i == 0) {
      std::ifstream file(candidate_filename.c_str());
      if (file.good()) {
        return candidate_filename;
      }
    } else {
      candidate_filename = "../" + candidate_filename;
      std::ifstream file(candidate_filename.c_str());
      if (file.good()) {
        return candidate_filename;
      }
    }
  }
  return absl::nullopt;
}
References i, and levels.
FirstActionStatePolicy() [1/2]
ActionsAndProbs open_spiel::FirstActionStatePolicy (const State & state)
Definition at line 126 of file policy.cc.
{
  return FirstActionStatePolicy(state, state.CurrentPlayer());
}
References FirstActionStatePolicy(), and state.
Referenced by FirstActionStatePolicy(), and open_spiel::FirstActionPolicy::GetStatePolicy().
FirstActionStatePolicy() [2/2]
ActionsAndProbs open_spiel::FirstActionStatePolicy (const State & state, Player player)
Definition at line 130 of file policy.cc.
{
  ActionsAndProbs actions_and_probs;
  std::vector<Action> legal_actions = state.LegalActions(player);
  actions_and_probs.reserve(legal_actions.size());
  for (int i = 0; i < legal_actions.size(); ++i) {
    actions_and_probs.push_back({legal_actions[i], i == 0 ? 1.0 : 0.0});
  }
  return actions_and_probs;
}
References actions_and_probs, i, player, and state.
FloatingPointDefaultTolerance()
float open_spiel::FloatingPointDefaultTolerance () inline constexpr
Definition at line 136 of file spiel_utils.h.
{ return 1e-6; }
Referenced by open_spiel::pathfinding::PathfindingGame::MinUtility(), open_spiel::algorithms::NashConv(), and Near().
FormatDouble()
std::string open_spiel::FormatDouble (double value)
Definition at line 100 of file spiel_utils.cc.
{
  // We cannot use StrCat as that would default to exponential notation
  // sometimes. For example, the default format of 10^-9 is the string
  // "1e-9". For that reason, we use StrFormat with %f explicitly, and add
  // the .0 if necessary (to clarify that it's a double value).
  std::string double_str = absl::StrFormat("%.15f", value);
  size_t idx = double_str.find('.');
  if (double_str.find('.') == std::string::npos) {  // NOLINT
    absl::StrAppend(&double_str, ".0");
  } else {
    // Remove the extra trailing zeros, if there are any.
    while (double_str.length() > idx + 2 && double_str.back() == '0') {
      double_str.pop_back();
    }
  }
  return double_str;
}
References absl::StrAppend(), and absl::StrFormat().
Referenced by open_spiel::GameParameter::ToString().
GameParameterFromString()
GameParameter open_spiel::GameParameterFromString (const std::string & str)
Definition at line 172 of file game_parameters.cc.
{
  if (str == "True" || str == "true") {
    return GameParameter(true);
  } else if (str == "False" || str == "false") {
    return GameParameter(false);
  } else if (str.find_first_not_of("+-0123456789") == std::string::npos) {
    int value;
    bool success = absl::SimpleAtoi(str, &value);
    SPIEL_CHECK_TRUE(success);
    return GameParameter(value);
  } else if (str.find_first_not_of("+-0123456789.") == std::string::npos) {
    double value;
    bool success = absl::SimpleAtod(str, &value);
    SPIEL_CHECK_TRUE(success);
    return GameParameter(value);
  } else if (str.back() == ')') {
    return GameParameter(GameParametersFromString(str));
  } else {
    return GameParameter(str);
  }
}
References GameParametersFromString(), absl::SimpleAtod(), absl::SimpleAtoi(), SPIEL_CHECK_TRUE, and value.
Referenced by GameParametersFromString().
GameParametersFromString()
GameParameters open_spiel::GameParametersFromString (const std::string & game_string)
Definition at line 194 of file game_parameters.cc.
{
  GameParameters params;
  if (game_string.empty()) return params;
  int first_paren = game_string.find('(');
  if (first_paren == std::string::npos) {
    params["name"] = GameParameter(game_string);
    return params;
  }
  params["name"] = GameParameter(game_string.substr(0, first_paren));
  int start = first_paren + 1;
  int parens = 1;
  int equals = -1;
  for (int i = start; i < game_string.length(); ++i) {
    if (game_string[i] == '(') {
      ++parens;
    } else if (game_string[i] == ')') {
      --parens;
    } else if (game_string[i] == '=' && parens == 1) {
      equals = i;
    }
    if ((game_string[i] == ',' && parens == 1) ||
        (game_string[i] == ')' && parens == 0 && i > start + 1)) {
      params[game_string.substr(start, equals - start)] =
          GameParameterFromString(
              game_string.substr(equals + 1, i - equals - 1));
      start = i + 1;
      equals = -1;
    }
  }
  if (parens > 0) SpielFatalError("Missing closing bracket ')'.");
  return params;
}
References GameParameterFromString(), i, and SpielFatalError().
Referenced by GameParameterFromString(), LoadBot(), and LoadGame().
GameParametersToString()
std::string open_spiel::GameParametersToString (const GameParameters & game_params)
Definition at line 153 of file game_parameters.cc.
{
  std::string str;
  if (game_params.empty()) return "";
  if (game_params.count("name")) str = game_params.at("name").string_value();
  str.push_back('(');
  bool first = true;
  for (const auto& key_val : game_params) {
    if (key_val.first != "name") {
      if (!first) str.push_back(',');
      str.append(key_val.first);
      str.append("=");
      str.append(key_val.second.ToString());
      first = false;
    }
  }
  str.push_back(')');
  return str;
}
References first.
Referenced by LoadGame(), open_spiel::GameParameter::ToReprString(), open_spiel::Game::ToString(), and open_spiel::GameParameter::ToString().
GameParameterTypeToString()
std::string open_spiel::GameParameterTypeToString (const GameParameter::Type & type)
Definition at line 227 of file game_parameters.cc.
{
  switch (type) {
    case GameParameter::Type::kUnset:
      return "kUnset";
    case GameParameter::Type::kInt:
      return "kInt";
    case GameParameter::Type::kDouble:
      return "kDouble";
    case GameParameter::Type::kString:
      return "kString";
    case GameParameter::Type::kBool:
      return "kBool";
    case GameParameter::Type::kGame:
      return "kGame";
    default:
      SpielFatalError("Invalid GameParameter");
  }
}
References open_spiel::GameParameter::kBool, open_spiel::GameParameter::kDouble, open_spiel::GameParameter::kGame, open_spiel::GameParameter::kInt, open_spiel::GameParameter::kString, open_spiel::GameParameter::kUnset, and SpielFatalError().
Referenced by open_spiel::GameParameter::Serialize().
GameToNFGString()
const std::string open_spiel::GameToNFGString (const Game & game)
Definition at line 27 of file nfg_writer.cc.
{
  // NFG 1 R "Selten (IJGT, 75), Figure 2, normal form"
  // { "Player 1" "Player 2" } { 3 2 }
  // 1 1 0 2 0 2 1 1 0 3 2 0
  const auto* nfg = dynamic_cast<const NormalFormGame*>(&game);
  if (nfg == nullptr) {
    SpielFatalError("Must be a normal-form game");
  }
  int num_players = nfg->NumPlayers();
  std::vector<std::vector<Action>> legal_actions(num_players);
  std::unique_ptr<State> initial_state = nfg->NewInitialState();
  for (Player player = 0; player < num_players; ++player) {
    legal_actions[player] = initial_state->LegalActions(player);
  }
  // Line 1.
  std::string nfg_text =
      absl::StrCat("NFG 1 R \"OpenSpiel export of ", nfg->ToString(), "\"\n");
  // Line 2.
  absl::StrAppend(&nfg_text, "{");
  for (Player p = 0; p < num_players; ++p) {
    absl::StrAppend(&nfg_text, " \"Player ", p, "\"");
  }
  absl::StrAppend(&nfg_text, " } {");
  for (Player p = 0; p < num_players; ++p) {
    absl::StrAppend(&nfg_text, " ", legal_actions[p].size());
  }
  absl::StrAppend(&nfg_text, " }\n\n");
  // Now the payoffs.
  for (auto flat_joint_action : initial_state->LegalActions()) {
    std::vector<double> returns =
        initial_state->Child(flat_joint_action)->Returns();
    for (Player p = 0; p < returns.size(); ++p) {
      absl::StrAppendFormat(&nfg_text, "%.15g ", returns[p]);
    }
    absl::StripAsciiWhitespace(&nfg_text);
    absl::StrAppend(&nfg_text, "\n");
  }
  return nfg_text;
}
References player, size, SpielFatalError(), absl::StrAppend(), absl::StrAppendFormat(), absl::StrCat(), and absl::StripAsciiWhitespace().
GameTypeFromString()
GameType open_spiel::GameTypeFromString (const std::string & game_type_str)
Definition at line 723 of file spiel.cc.
{
  absl::btree_map<std::string, std::string> game_type_values;
  std::vector<std::string> parts = absl::StrSplit(game_type_str, '\n');
  SPIEL_CHECK_EQ(parts.size(), 15);
  for (const auto& part : parts) {
    std::pair<std::string, std::string> pair =
        absl::StrSplit(part, absl::MaxSplits(": ", 1));
    game_type_values.insert(pair);
  }
  GameType game_type = GameType();
  game_type.short_name = game_type_values.at("short_name");
  game_type.long_name = game_type_values.at("long_name");
  std::istringstream(game_type_values.at("dynamics")) >> game_type.dynamics;
  std::istringstream(game_type_values.at("chance_mode")) >>
      game_type.chance_mode;
  std::istringstream(game_type_values.at("information")) >>
      game_type.information;
  std::istringstream(game_type_values.at("utility")) >> game_type.utility;
  std::istringstream(game_type_values.at("reward_model")) >>
      game_type.reward_model;
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(game_type_values.at("max_num_players"),
                                    &(game_type.max_num_players)));
  SPIEL_CHECK_TRUE(absl::SimpleAtoi(game_type_values.at("min_num_players"),
                                    &(game_type.min_num_players)));
  game_type.provides_information_state_string =
      game_type_values.at("provides_information_state_string") == "true";
  game_type.provides_information_state_tensor =
      game_type_values.at("provides_information_state_tensor") == "true";
  game_type.provides_observation_string =
      game_type_values.at("provides_observation_string") == "true";
  game_type.provides_observation_tensor =
      game_type_values.at("provides_observation_tensor") == "true";
  game_type.provides_factored_observation_string =
      game_type_values.at("provides_factored_observation_string") == "true";
  game_type.parameter_specification =
      DeserializeGameParameters(game_type_values.at("parameter_specification"));
  return game_type;
}
References open_spiel::GameType::chance_mode, DeserializeGameParameters(), open_spiel::GameType::dynamics, open_spiel::GameType::information, open_spiel::GameType::long_name, open_spiel::GameType::max_num_players, absl::MaxSplits(), open_spiel::GameType::min_num_players, pair, open_spiel::GameType::parameter_specification, open_spiel::GameType::provides_factored_observation_string, open_spiel::GameType::provides_information_state_string, open_spiel::GameType::provides_information_state_tensor, open_spiel::GameType::provides_observation_string, open_spiel::GameType::provides_observation_tensor, open_spiel::GameType::reward_model, open_spiel::GameType::short_name, absl::SimpleAtoi(), SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, absl::StrSplit(), and open_spiel::GameType::utility.
GameTypeToString()
std::string open_spiel::GameTypeToString (const GameType & game_type)
Definition at line 670 of file spiel.cc.
{
  std::string str = "";
  absl::StrAppend(&str, "short_name: ", game_type.short_name, "\n");
  absl::StrAppend(&str, "long_name: ", game_type.long_name, "\n");
  absl::StrAppend(&str, "dynamics: ",
                  open_spiel::internal::SpielStrCat(game_type.dynamics), "\n");
  absl::StrAppend(&str, "chance_mode: ",
                  open_spiel::internal::SpielStrCat(game_type.chance_mode),
                  "\n");
  absl::StrAppend(&str, "information: ",
                  open_spiel::internal::SpielStrCat(game_type.information),
                  "\n");
  absl::StrAppend(&str, "utility: ",
                  open_spiel::internal::SpielStrCat(game_type.utility), "\n");
  absl::StrAppend(&str, "reward_model: ",
                  open_spiel::internal::SpielStrCat(game_type.reward_model),
                  "\n");
  absl::StrAppend(&str, "max_num_players: ", game_type.max_num_players, "\n");
  absl::StrAppend(&str, "min_num_players: ", game_type.min_num_players, "\n");
  absl::StrAppend(
      &str, "provides_information_state_string: ",
      game_type.provides_information_state_string ? "true" : "false", "\n");
  absl::StrAppend(
      &str, "provides_information_state_tensor: ",
      game_type.provides_information_state_tensor ? "true" : "false", "\n");
  absl::StrAppend(&str, "provides_observation_string: ",
                  game_type.provides_observation_string ? "true" : "false",
                  "\n");
  absl::StrAppend(&str, "provides_observation_tensor: ",
                  game_type.provides_observation_tensor ? "true" : "false",
                  "\n");
  absl::StrAppend(
      &str, "provides_factored_observation_string: ",
      game_type.provides_factored_observation_string ? "true" : "false", "\n");
  // Check that there are no newlines in the serialized params.
  std::string serialized_params =
      SerializeGameParameters(game_type.parameter_specification);
  SPIEL_CHECK_TRUE(!absl::StrContains(serialized_params, "\n"));
  absl::StrAppend(&str, "parameter_specification: ", serialized_params);
  return str;
}
References open_spiel::GameType::chance_mode, open_spiel::GameType::dynamics, open_spiel::GameType::information, open_spiel::GameType::long_name, open_spiel::GameType::max_num_players, open_spiel::GameType::min_num_players, open_spiel::GameType::parameter_specification, open_spiel::GameType::provides_factored_observation_string, open_spiel::GameType::provides_information_state_string, open_spiel::GameType::provides_information_state_tensor, open_spiel::GameType::provides_observation_string, open_spiel::GameType::provides_observation_tensor, open_spiel::GameType::reward_model, SerializeGameParameters(), open_spiel::GameType::short_name, SPIEL_CHECK_TRUE, open_spiel::internal::SpielStrCat(), absl::StrAppend(), absl::StrContains(), and open_spiel::GameType::utility.
GenerateMasks()
std::vector< std::vector< int > > open_spiel::GenerateMasks (std::vector< int > & values, int k, std::vector< int > & permutation_stack)
Definition at line 36 of file combinatorics.cc.
{
  if (k == permutation_stack.size()) {
    return {permutation_stack};
  }
  std::vector<std::vector<int>> vs;
  auto end_valid = values.size() - permutation_stack.size();
  permutation_stack.push_back(0);
  for (int i = 0; i < end_valid; ++i) {
    permutation_stack.back() = values[i];
    std::swap(values[i], values[end_valid - 1]);
    auto child_vs = GenerateMasks(values, k, permutation_stack);
    vs.insert(vs.begin(), child_vs.begin(), child_vs.end());
    std::swap(values[i], values[end_valid - 1]);
  }
  permutation_stack.pop_back();
  return vs;
}
References GenerateMasks(), i, and values.
Referenced by GenerateMasks(), and VariationsWithoutRepetition().
GetAction()
Action open_spiel::GetAction (const ActionsAndProbs & action_and_probs)
Definition at line 60 of file policy.cc.
{
  for (const auto& iter : action_and_probs) {
    if (iter.second == 1.0) {
      return iter.first;
    }
  }
  return kInvalidAction;
}
References kInvalidAction.
Referenced by open_spiel::algorithms::AFCCEState::CurRecommendation(), open_spiel::algorithms::AFCEState::CurRecommendation(), open_spiel::algorithms::EFCCEState::CurRecommendation(), open_spiel::algorithms::EFCEState::CurRecommendation(), open_spiel::universal_poker::acpc_cpp::ACPCState::DoAction(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::IBRIteration(), and open_spiel::universal_poker::acpc_cpp::ACPCState::IsValidAction().
GetDeterministicPolicy()
ActionsAndProbs open_spiel::GetDeterministicPolicy (const std::vector< Action > & legal_actions, Action action)
Definition at line 100 of file policy.cc.
{
  ActionsAndProbs new_policy;
  new_policy.reserve(legal_actions.size());
  for (Action legal_action : legal_actions) {
    new_policy.push_back({legal_action, legal_action == action ? 1.0 : 0.0});
  }
  return new_policy;
}
References action.
Referenced by open_spiel::PreferredActionPolicy::GetStatePolicy().
GetEmptyTabularPolicy()
TabularPolicy open_spiel::GetEmptyTabularPolicy (const Game & game, bool initialize_to_uniform, Player player)
Definition at line 275 of file policy.cc.
{
  std::unordered_map<std::string, ActionsAndProbs> policy;
  if (game.GetType().dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError("Game is not sequential.");
    return TabularPolicy(policy);
  }
  std::list<std::unique_ptr<State>> to_visit;
  to_visit.push_back(game.NewInitialState());
  while (!to_visit.empty()) {
    std::unique_ptr<State> state = std::move(to_visit.back());
    to_visit.pop_back();
    if (state->IsTerminal()) {
      continue;
    }
    if (state->IsChanceNode()) {
      for (const auto& outcome_and_prob : state->ChanceOutcomes()) {
        to_visit.emplace_back(state->Child(outcome_and_prob.first));
      }
    } else {
      ActionsAndProbs infostate_policy;
      std::vector<Action> legal_actions = state->LegalActions();
      const int num_legal_actions = legal_actions.size();
      SPIEL_CHECK_GT(num_legal_actions, 0.);
      for (Action action : legal_actions) {
        to_visit.push_back(state->Child(action));
      }
      if (player < 0 || state->IsPlayerActing(player)) {
        double action_probability = 1.;
        if (initialize_to_uniform) {
          action_probability = 1. / num_legal_actions;
        }
        ActionsAndProbs infostate_policy;
        infostate_policy.reserve(num_legal_actions);
        for (Action action : legal_actions) {
          infostate_policy.push_back({action, action_probability});
        }
        if (infostate_policy.empty()) {
          SpielFatalError("State has zero legal actions.");
        }
        policy.insert({state->InformationStateString(), infostate_policy});
      }
    }
  }
  return TabularPolicy(policy);
}
References action, open_spiel::GameType::kSequential, player, SPIEL_CHECK_GT, SpielFatalError(), and state.
Referenced by define_julia_module(), GetUniformPolicy(), and SamplePolicy().
GetFirstActionPolicy()
TabularPolicy open_spiel::GetFirstActionPolicy (const Game & game)
Definition at line 432 of file policy.cc.
{
  std::unordered_map<std::string, ActionsAndProbs> policy;
  if (game.GetType().dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError("Game is not sequential.");
    return TabularPolicy(policy);
  }
  std::vector<std::unique_ptr<State>> to_visit;
  to_visit.push_back(game.NewInitialState());
  while (!to_visit.empty()) {
    std::unique_ptr<State> state = std::move(to_visit.back());
    to_visit.pop_back();
    if (state->IsTerminal()) {
      continue;
    }
    if (state->IsChanceNode()) {
      for (const auto& outcome_and_prob : state->ChanceOutcomes()) {
        to_visit.emplace_back(state->Child(outcome_and_prob.first));
      }
    } else {
      ActionsAndProbs infostate_policy;
      std::vector<Action> legal_actions = state->LegalActions();
      const int num_legal_actions = legal_actions.size();
      SPIEL_CHECK_GT(num_legal_actions, 0.);
      bool first_legal_action_found = false;
      infostate_policy.reserve(num_legal_actions);
      for (Action action : legal_actions) {
        to_visit.push_back(state->Child(action));
        if (!first_legal_action_found) {
          first_legal_action_found = true;
          infostate_policy.push_back({action, 1.});
        } else {
          infostate_policy.push_back({action, 0.});
        }
      }
      if (infostate_policy.empty()) {
        SpielFatalError("State has zero legal actions.");
      }
      policy[state->InformationStateString()] = std::move(infostate_policy);
    }
  }
  return TabularPolicy(policy);
}
References action, open_spiel::GameType::kSequential, SPIEL_CHECK_GT, SpielFatalError(), and state.
Referenced by define_julia_module(), and main().
GetFlatDirichletPolicy()
TabularPolicy open_spiel::GetFlatDirichletPolicy (const Game & game, int seed, Player player)
Definition at line 370 of file policy.cc.
{
  std::gamma_distribution<double> dist(1.0, 1.0);
  return SamplePolicy(game, seed, dist, player);
}
References player, and SamplePolicy().
Referenced by init_pyspiel_policy().
GetPrefActionPolicy()
TabularPolicy open_spiel::GetPrefActionPolicy (const Game & game, const std::vector< Action > & pref_actions)
Definition at line 520 of file policy.cc.
{
  PreferredActionPolicy policy(pref_actions);
  return ToTabularPolicy(game, &policy);
}
References ToTabularPolicy().
Referenced by open_spiel::kuhn_poker::GetAlwaysBetPolicy(), open_spiel::leduc_poker::GetAlwaysCallPolicy(), open_spiel::leduc_poker::GetAlwaysFoldPolicy(), open_spiel::kuhn_poker::GetAlwaysPassPolicy(), and open_spiel::leduc_poker::GetAlwaysRaisePolicy().
GetProb()
double open_spiel::GetProb (const ActionsAndProbs & action_and_probs, Action action)
Definition at line 51 of file policy.cc.
{
  auto it = absl::c_find_if(action_and_probs,
                            [&action](const std::pair<Action, double>& p) {
                              return p.first == action;
                            });
  if (it == action_and_probs.end()) return -1.;
  return it->second;
}
References action, and absl::c_find_if().
Referenced by open_spiel::algorithms::CorrDevBuilder::AddMixedJointPolicy(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::BRPIIteration(), open_spiel::algorithms::DecisionNodes(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::GetLatestPolicy(), open_spiel::algorithms::GetStateDistribution(), and open_spiel::algorithms::OOSAlgorithm::SelectAction().
GetRandomDeterministicPolicy()
TabularPolicy open_spiel::GetRandomDeterministicPolicy (const Game & game, int seed, Player player)
Definition at line 376 of file policy.cc.
{
  std::mt19937 gen(seed);
  absl::node_hash_map<int, std::uniform_int_distribution<int>> dists;
  std::unordered_map<std::string, ActionsAndProbs> policy;
  if (game.GetType().dynamics != GameType::Dynamics::kSequential) {
    SpielFatalError("Game is not sequential.");
    return TabularPolicy(policy);
  }
  const GameType::Information information = game.GetType().information;
  std::list<std::unique_ptr<State>> to_visit;
  to_visit.push_back(game.NewInitialState());
  while (!to_visit.empty()) {
    std::unique_ptr<State> state = std::move(to_visit.back());
    to_visit.pop_back();
    if (state->IsTerminal()) {
      continue;
    } else if (state->IsChanceNode()) {
      for (const auto& outcome_and_prob : state->ChanceOutcomes()) {
        to_visit.emplace_back(state->Child(outcome_and_prob.first));
      }
    } else if (player < 0 || state->IsPlayerActing(player)) {
      std::vector<Action> legal_actions = state->LegalActions();
      const int num_legal_actions = legal_actions.size();
      SPIEL_CHECK_GT(num_legal_actions, 0.);
      if (dists.count(num_legal_actions) == 0) {
        std::uniform_int_distribution<int> dist(0, num_legal_actions - 1);
        dists.insert({num_legal_actions, std::move(dist)});
      }
      const int legal_action_index = dists[num_legal_actions](gen);
      SPIEL_CHECK_GE(legal_action_index, 0);
      SPIEL_CHECK_LT(legal_action_index, num_legal_actions);
      const int action = legal_actions[legal_action_index];
      ActionsAndProbs infostate_policy;
      infostate_policy.reserve(1);
      infostate_policy.push_back({action, 1.0});
      policy.insert({state->InformationStateString(), infostate_policy});
      if (information == GameType::Information::kPerfectInformation) {
        to_visit.push_back(state->Child(action));
      } else {
        for (Action action : legal_actions) {
          to_visit.push_back(state->Child(action));
        }
      }
    } else {
      std::vector<Action> legal_actions = state->LegalActions();
      const int num_legal_actions = legal_actions.size();
      SPIEL_CHECK_GT(num_legal_actions, 0.);
      for (Action action : legal_actions) {
        to_visit.push_back(state->Child(action));
      }
    }
  }
  return TabularPolicy(policy);
}
References action, open_spiel::GameType::kPerfectInformation, open_spiel::GameType::kSequential, player, SPIEL_CHECK_GE, SPIEL_CHECK_GT, SPIEL_CHECK_LT, SpielFatalError(), and state.
Referenced by init_pyspiel_policy().
GetRandomPolicy()
TabularPolicy open_spiel::GetRandomPolicy (const Game & game, int seed, Player player)
Definition at line 365 of file policy.cc.
{
  std::uniform_real_distribution<double> dist(0, 1);
  return SamplePolicy(game, seed, dist, player);
}
References player, and SamplePolicy().
Referenced by define_julia_module(), and init_pyspiel_policy().
GetUniformPolicy()
TabularPolicy open_spiel::GetUniformPolicy (const Game & game)
Definition at line 323 of file policy.cc.
{
  return GetEmptyTabularPolicy(game, /*initialize_to_uniform=*/true);
}
References GetEmptyTabularPolicy().
Referenced by define_julia_module(), init_pyspiel_policy(), and main().
HistoryFromString()
std::vector< Action > open_spiel::HistoryFromString (const std::string & str)
Definition at line 63 of file start_at.cc.
{
  std::vector<Action> history;
  if (str.empty()) return history;  // Identity transformation.
  std::vector<absl::string_view> str_actions =
      absl::StrSplit(str, kActionSeparator);
  for (const auto& str_action : str_actions) {
    Action a;
    if (!absl::SimpleAtoi(str_action, &a)) {
      SpielFatalError(
          absl::StrCat("Error when parsing the action: ", str_action));
    }
    history.push_back(a);
  }
  return history;
}
References a, absl::SimpleAtoi(), SpielFatalError(), absl::StrCat(), and absl::StrSplit().
HulhGameString()
std::string open_spiel::HulhGameString (const std::string & betting_abstraction)
Definition at line 32 of file canonical_game_strings.cc.
{
  return absl::StrFormat(
      "universal_poker(betting=limit,numPlayers=2,numRounds=4,blind=10 5,"
      "firstPlayer=2 1,numSuits=4,numRanks=13,numHoleCards=2,numBoardCards=0 3 "
      "1 1,raiseSize=10 10 20 20,maxRaises=3 4 4 4,bettingAbstraction=%s)",
      betting_abstraction);
}
References absl::StrFormat().
HunlGameString()
std::string open_spiel::HunlGameString (const std::string & betting_abstraction)
Definition at line 23 of file canonical_game_strings.cc.
{
  return absl::StrFormat(
      "universal_poker(betting=nolimit,numPlayers=2,numRounds=4,blind=100 50,"
      "firstPlayer=2 1 1 "
      "1,numSuits=4,numRanks=13,numHoleCards=2,numBoardCards=0 3 "
      "1 1,stack=20000 20000,bettingAbstraction=%s)",
      betting_abstraction);
}
References absl::StrFormat().
Init()
void open_spiel::Init (const char * usage, int * argc, char *** argv, bool remove_flags)
Definition at line 20 of file init.cc.
{
}
Referenced by main().
init_pyspiel_algorithms_corr_dist() [1/2]
void open_spiel::init_pyspiel_algorithms_corr_dist (::pybind11::module & m)
init_pyspiel_algorithms_corr_dist() [2/2]
void open_spiel::init_pyspiel_algorithms_corr_dist (py::module & m)
Definition at line 32 of file algorithms_corr_dist.cc.
{
  m.def("uniform_correlation_device",
        &open_spiel::algorithms::UniformCorrelationDevice,
        "Returns a uniform correlation device over a set of joint policies.");
  m.def("sampled_determinize_corr_dev",
        &open_spiel::algorithms::SampledDeterminizeCorrDev,
        "Returns a correlation device over deterministic policies sampled from "
        "a correlation device.");
  m.def("determinize_corr_dev", &open_spiel::algorithms::DeterminizeCorrDev,
        "Returns an exact correlation device over deterministic policies "
        "equivalent to this correlation device. Warning: very costly!");
  py::class_<CorrDistInfo> corr_dist_info(m, "CorrDistInfo");
  corr_dist_info.def_readonly("dist_value", &CorrDistInfo::dist_value)
      .def_readonly("on_policy_values", &CorrDistInfo::on_policy_values)
      .def_readonly("best_response_values", &CorrDistInfo::best_response_values)
      .def_readonly("deviation_incentives", &CorrDistInfo::deviation_incentives)
      .def_readonly("best_response_policies",
                    &CorrDistInfo::best_response_policies)
      .def_readonly("conditional_best_response_policies",
                    &CorrDistInfo::conditional_best_response_policies);
  py::class_<CorrDevBuilder> corr_dev_builder(m, "CorrDevBuilder");
  corr_dev_builder.def(py::init<int>(), py::arg("seed") = 0)
      .def("add_deterministic_joint_policy",
           &CorrDevBuilder::AddDeterminsticJointPolicy,
           py::arg("policy"), py::arg("weight") = 1.0)
      .def("add_sampled_joint_policy",
           &CorrDevBuilder::AddSampledJointPolicy,
           py::arg("policy"), py::arg("num_samples"), py::arg("weight") = 1.0)
      .def("add_mixed_joint_policy",
            &CorrDevBuilder::AddMixedJointPolicy,
            py::arg("policy"),
            py::arg("weight") = 1.0)
      .def("get_correlation_device", &CorrDevBuilder::GetCorrelationDevice);
  m.def(
      "cce_dist",
      [](std::shared_ptr<const Game> game,
         const CorrelationDevice& correlation_device, int player,
         float prob_cut_threshold, const float action_value_tolerance) {
        return algorithms::CCEDist(*game, correlation_device, player,
                                   prob_cut_threshold, action_value_tolerance);
      },
      "Returns a player's distance to a coarse-correlated equilibrium.",
      py::arg("game"), py::arg("correlation_device"), py::arg("player"),
      py::arg("prob_cut_threshold") = -1.0,
      py::arg("action_value_tolerance") = -1.0);
  m.def(
      "cce_dist",
      [](std::shared_ptr<const Game> game,
         const CorrelationDevice& correlation_device, float prob_cut_threshold,
         const float action_value_tolerance) {
        return algorithms::CCEDist(*game, correlation_device,
                                   prob_cut_threshold, action_value_tolerance);
      },
      "Returns the distance to a coarse-correlated equilibrium.",
      py::arg("game"), py::arg("correlation_device"),
      py::arg("prob_cut_threshold") = -1.0,
      py::arg("action_value_tolerance") = false);
  m.def(
      "ce_dist",
      [](std::shared_ptr<const Game> game,
         const CorrelationDevice& correlation_device,
         const float action_value_tolerance) {
        return algorithms::CEDist(*game, correlation_device,
                                  action_value_tolerance);
      },
      "Returns the distance to a correlated equilibrium.", py::arg("game"),
      py::arg("correlation_device"), py::arg("action_value_tolerance") = -1.0);
  // TODO(author5): expose the rest of the functions.
}
References open_spiel::algorithms::CorrDevBuilder::AddDeterminsticJointPolicy(), open_spiel::algorithms::CorrDevBuilder::AddMixedJointPolicy(), open_spiel::algorithms::CorrDevBuilder::AddSampledJointPolicy(), open_spiel::algorithms::CorrDistInfo::best_response_policies, open_spiel::algorithms::CorrDistInfo::best_response_values, open_spiel::algorithms::CCEDist(), open_spiel::algorithms::CEDist(), open_spiel::algorithms::CorrDistInfo::conditional_best_response_policies, open_spiel::algorithms::DeterminizeCorrDev(), open_spiel::algorithms::CorrDistInfo::deviation_incentives, open_spiel::algorithms::CorrDistInfo::dist_value, open_spiel::algorithms::CorrDevBuilder::GetCorrelationDevice(), open_spiel::algorithms::CorrDistInfo::on_policy_values, player, open_spiel::algorithms::SampledDeterminizeCorrDev(), and open_spiel::algorithms::UniformCorrelationDevice().
init_pyspiel_algorithms_trajectories() [1/2]
void open_spiel::init_pyspiel_algorithms_trajectories (::pybind11::module & m)
init_pyspiel_algorithms_trajectories() [2/2]
void open_spiel::init_pyspiel_algorithms_trajectories (py::module & m)
Definition at line 25 of file algorithms_trajectories.cc.
{
  py::class_<open_spiel::algorithms::BatchedTrajectory>(m, "BatchedTrajectory")
      .def(py::init<int>())
      .def_readwrite("observations",
                     &open_spiel::algorithms::BatchedTrajectory::observations)
      .def_readwrite("state_indices",
                     &open_spiel::algorithms::BatchedTrajectory::state_indices)
      .def_readwrite("legal_actions",
                     &open_spiel::algorithms::BatchedTrajectory::legal_actions)
      .def_readwrite("actions",
                     &open_spiel::algorithms::BatchedTrajectory::actions)
      .def_readwrite(
          "player_policies",
          &open_spiel::algorithms::BatchedTrajectory::player_policies)
      .def_readwrite("player_ids",
                     &open_spiel::algorithms::BatchedTrajectory::player_ids)
      .def_readwrite("rewards",
                     &open_spiel::algorithms::BatchedTrajectory::rewards)
      .def_readwrite("valid", &open_spiel::algorithms::BatchedTrajectory::valid)
      .def_readwrite(
          "next_is_terminal",
          &open_spiel::algorithms::BatchedTrajectory::next_is_terminal)
      .def_readwrite("batch_size",
                     &open_spiel::algorithms::BatchedTrajectory::batch_size)
      .def_readwrite(
          "max_trajectory_length",
          &open_spiel::algorithms::BatchedTrajectory::max_trajectory_length)
      .def("resize_fields",
           &open_spiel::algorithms::BatchedTrajectory::ResizeFields);
  m.def(
      "record_batched_trajectories",
      [](std::shared_ptr<const Game> game,
         const std::vector<TabularPolicy>& policies,
         const std::unordered_map<std::string, int>& state_to_index,
         int batch_size, bool include_full_observations, int seed,
         int max_unroll_length) {
        return open_spiel::algorithms::RecordBatchedTrajectory(
            *game, policies, state_to_index, batch_size,
            include_full_observations, seed, max_unroll_length);
      },
      "Records a batch of trajectories.");
  py::class_<open_spiel::algorithms::TrajectoryRecorder>(m,
                                                         "TrajectoryRecorder")
      .def(py::init(
          [](std::shared_ptr<const Game> game,
             const std::unordered_map<std::string, int>& state_to_index,
             int seed) {
            return new algorithms::TrajectoryRecorder(*game, state_to_index,
                                                      seed);
          }))
      .def("record_batch",
           &open_spiel::algorithms::TrajectoryRecorder::RecordBatch);
}
References open_spiel::algorithms::BatchedTrajectory::actions, open_spiel::algorithms::BatchedTrajectory::batch_size, open_spiel::algorithms::BatchedTrajectory::legal_actions, open_spiel::algorithms::BatchedTrajectory::max_trajectory_length, open_spiel::algorithms::BatchedTrajectory::next_is_terminal, open_spiel::algorithms::BatchedTrajectory::observations, open_spiel::algorithms::BatchedTrajectory::player_ids, open_spiel::algorithms::BatchedTrajectory::player_policies, open_spiel::algorithms::TrajectoryRecorder::RecordBatch(), open_spiel::algorithms::RecordBatchedTrajectory(), open_spiel::algorithms::BatchedTrajectory::ResizeFields(), open_spiel::algorithms::BatchedTrajectory::rewards, open_spiel::algorithms::BatchedTrajectory::state_indices, and open_spiel::algorithms::BatchedTrajectory::valid.
init_pyspiel_bots() [1/2]
void open_spiel::init_pyspiel_bots (::pybind11::module & m)
init_pyspiel_bots() [2/2]
void open_spiel::init_pyspiel_bots (py::module & m)
Definition at line 54 of file bots.cc.
{
  py::classh<Bot, PyBot<Bot>> bot(m, "Bot");
  bot.def(py::init<>())
      .def("step", &Bot::Step)
      .def("restart", &Bot::Restart)
      .def("restart_at", &Bot::RestartAt)
      .def("provides_force_action", &Bot::ProvidesForceAction)
      .def("force_action", &Bot::ForceAction)
      .def("inform_action", &Bot::InformAction)
      .def("inform_actions", &Bot::InformActions)
      .def("provides_policy", &Bot::ProvidesPolicy)
      .def("get_policy", &Bot::GetPolicy)
      .def("step_with_policy", &Bot::StepWithPolicy)
      .def("is_clonable", &Bot::IsClonable)
      .def("clone", &Bot::Clone);
  m.def(
      "load_bot",
      py::overload_cast<const std::string&, const std::shared_ptr<const Game>&,
                        Player>(&open_spiel::LoadBot),
      py::arg("bot_name"), py::arg("game"), py::arg("player"),
      "Returns a new bot object for the specified bot name using default "
      "parameters");
  m.def(
      "load_bot",
      py::overload_cast<const std::string&, const std::shared_ptr<const Game>&,
                        Player, const GameParameters&>(&open_spiel::LoadBot),
      py::arg("bot_name"), py::arg("game"), py::arg("player"),
      py::arg("params"),
      "Returns a new bot object for the specified bot name using given "
      "parameters");
  m.def("is_bot_registered", &IsBotRegistered,
        "Checks if a bot under the given name is registered.");
  m.def("registered_bots", &RegisteredBots,
        "Returns a list of registered bot names.");
  m.def(
      "bots_that_can_play_game",
      [](std::shared_ptr<const Game> game, int player) {
        return BotsThatCanPlayGame(*game, player);
      },
      py::arg("game"), py::arg("player"),
      "Returns a list of bot names that can play specified game for the "
      "given player.");
  m.def(
      "bots_that_can_play_game",
      [](std::shared_ptr<const Game> game) {
        return BotsThatCanPlayGame(*game);
      },
      py::arg("game"),
      "Returns a list of bot names that can play specified game for any "
      "player.");
  py::class_<algorithms::Evaluator,
             std::shared_ptr<algorithms::Evaluator>> mcts_evaluator(
                 m, "Evaluator");
  py::class_<algorithms::RandomRolloutEvaluator,
             algorithms::Evaluator,
             std::shared_ptr<algorithms::RandomRolloutEvaluator>>(
                 m, "RandomRolloutEvaluator")
      .def(py::init<int, int>(), py::arg("n_rollouts"), py::arg("seed"));
  py::enum_<algorithms::ChildSelectionPolicy>(m, "ChildSelectionPolicy")
      .value("UCT", algorithms::ChildSelectionPolicy::UCT)
      .value("PUCT", algorithms::ChildSelectionPolicy::PUCT);
  py::class_<SearchNode> search_node(m, "SearchNode");
  search_node.def_readonly("action", &SearchNode::action)
      .def_readonly("prior", &SearchNode::prior)
      .def_readonly("player", &SearchNode::player)
      .def_readonly("explore_count", &SearchNode::explore_count)
      .def_readonly("total_reward", &SearchNode::total_reward)
      .def_readonly("outcome", &SearchNode::outcome)
      .def_readonly("children", &SearchNode::children)
      .def("best_child", &SearchNode::BestChild)
      .def("to_string", &SearchNode::ToString)
      .def("children_str", &SearchNode::ChildrenStr);
  py::classh<algorithms::MCTSBot, Bot>(m, "MCTSBot")
      .def(
          py::init([](std::shared_ptr<const Game> game,
                      std::shared_ptr<Evaluator> evaluator, double uct_c,
                      int max_simulations, int64_t max_memory_mb, bool solve,
                      int seed, bool verbose,
                      algorithms::ChildSelectionPolicy child_selection_policy) {
            return new algorithms::MCTSBot(
                *game, evaluator, uct_c, max_simulations, max_memory_mb, solve,
                seed, verbose, child_selection_policy);
          }),
          py::arg("game"), py::arg("evaluator"), py::arg("uct_c"),
          py::arg("max_simulations"), py::arg("max_memory_mb"),
          py::arg("solve"), py::arg("seed"), py::arg("verbose"),
          py::arg("child_selection_policy") =
              algorithms::ChildSelectionPolicy::UCT)
      .def("step", &algorithms::MCTSBot::Step)
      .def("mcts_search", &algorithms::MCTSBot::MCTSearch);
  py::enum_<algorithms::ISMCTSFinalPolicyType>(m, "ISMCTSFinalPolicyType")
      .value("NORMALIZED_VISIT_COUNT",
             algorithms::ISMCTSFinalPolicyType::kNormalizedVisitCount)
      .value("MAX_VISIT_COUNT",
             algorithms::ISMCTSFinalPolicyType::kMaxVisitCount)
      .value("MAX_VALUE", algorithms::ISMCTSFinalPolicyType::kMaxValue);
  py::classh<algorithms::ISMCTSBot, Bot>(m, "ISMCTSBot")
      .def(py::init<int, std::shared_ptr<Evaluator>, double, int, int,
                    algorithms::ISMCTSFinalPolicyType, bool, bool>(),
           py::arg("seed"), py::arg("evaluator"), py::arg("uct_c"),
           py::arg("max_simulations"),
           py::arg("max_world_samples") = algorithms::kUnlimitedNumWorldSamples,
           py::arg("final_policy_type") =
               algorithms::ISMCTSFinalPolicyType::kNormalizedVisitCount,
           py::arg("use_observation_string") = false,
           py::arg("allow_inconsistent_action_sets") = false)
      .def("step", &algorithms::ISMCTSBot::Step)
      .def("provides_policy", &algorithms::MCTSBot::ProvidesPolicy)
      .def("get_policy", &algorithms::ISMCTSBot::GetPolicy)
      .def("step_with_policy", &algorithms::ISMCTSBot::StepWithPolicy)
      .def("restart", &algorithms::ISMCTSBot::Restart)
      .def("restart_at", &algorithms::ISMCTSBot::RestartAt);
  m.def("evaluate_bots",
        py::overload_cast<State*, const std::vector<Bot*>&, int>(
            open_spiel::EvaluateBots),
        py::arg("state"), py::arg("bots"), py::arg("seed"),
        "Plays a single game with the given bots and returns the final "
        "utilities.");
  m.def("make_uniform_random_bot", open_spiel::MakeUniformRandomBot,
        "A uniform random bot, for test purposes.");
  m.def("make_stateful_random_bot", open_spiel::MakeStatefulRandomBot,
        "A stateful random bot, for test purposes.");
  m.def(
      "make_policy_bot",
      [](std::shared_ptr<const Game> game, Player player_id, int seed,
         std::shared_ptr<Policy> policy) {
        return MakePolicyBot(*game, player_id, seed, policy);
      },
      "A bot that samples from a policy.");
  py::enum_<open_spiel::uci::SearchLimitType>(m, "SearchLimitType")
      .value("MOVETIME", open_spiel::uci::SearchLimitType::kMoveTime)
      .value("NODES", open_spiel::uci::SearchLimitType::kNodes)
      .value("DEPTH", open_spiel::uci::SearchLimitType::kDepth)
      .export_values();
#ifndef _WIN32
  m.def("make_uci_bot", open_spiel::uci::MakeUCIBot,
        py::arg("bot_binary_path"), py::arg("search_limit_value"),
        py::arg("ponder"), py::arg("options"),
        py::arg("search_limit_type") =
            open_spiel::uci::SearchLimitType::kMoveTime,
        "Bot that can play chess using UCI chess engine.");
#endif
#if OPEN_SPIEL_BUILD_WITH_ROSHAMBO
  m.attr("ROSHAMBO_NUM_THROWS") = py::int_(open_spiel::roshambo::kNumThrows);
  m.attr("ROSHAMBO_NUM_BOTS") = py::int_(open_spiel::roshambo::kNumBots);
  // no arguments; returns vector of strings
  m.def("roshambo_bot_names", open_spiel::roshambo::RoshamboBotNames);
  // args: player_int (int), bot name (string), num throws (int), returns bot
  m.def("make_roshambo_bot", open_spiel::roshambo::MakeRoshamboBot,
        py::arg("player_id"), py::arg("bot_name"),
        py::arg("num_throws") = open_spiel::roshambo::kNumThrows);
#endif
  m.def(
      "make_simple_gin_rummy_bot",
      [](const GameParameters& params,
         int player_id) -> std::unique_ptr<open_spiel::Bot> {
        return std::make_unique<gin_rummy::SimpleGinRummyBot>(params,
                                                              player_id);
      },
      py::arg("params"), py::arg("player_id"));
}
References BotsThatCanPlayGame(), open_spiel::Bot::Clone(), EvaluateBots(), open_spiel::Bot::ForceAction(), open_spiel::algorithms::ISMCTSBot::GetPolicy(), open_spiel::Bot::GetPolicy(), open_spiel::Bot::InformAction(), open_spiel::Bot::InformActions(), IsBotRegistered(), open_spiel::Bot::IsClonable(), open_spiel::uci::kDepth, open_spiel::algorithms::kMaxValue, open_spiel::algorithms::kMaxVisitCount, open_spiel::uci::kMoveTime, open_spiel::uci::kNodes, open_spiel::algorithms::kNormalizedVisitCount, open_spiel::roshambo::kNumBots, open_spiel::roshambo::kNumThrows, open_spiel::algorithms::kUnlimitedNumWorldSamples, LoadBot(), MakePolicyBot(), open_spiel::roshambo::MakeRoshamboBot(), MakeStatefulRandomBot(), open_spiel::uci::MakeUCIBot(), MakeUniformRandomBot(), open_spiel::algorithms::MCTSBot::MCTSearch(), player, open_spiel::Bot::ProvidesForceAction(), open_spiel::Bot::ProvidesPolicy(), open_spiel::algorithms::PUCT, RegisteredBots(), open_spiel::algorithms::ISMCTSBot::Restart(), open_spiel::Bot::Restart(), open_spiel::algorithms::ISMCTSBot::RestartAt(), open_spiel::Bot::RestartAt(), open_spiel::roshambo::RoshamboBotNames(), open_spiel::algorithms::ISMCTSBot::Step(), open_spiel::algorithms::MCTSBot::Step(), open_spiel::Bot::Step(), open_spiel::algorithms::ISMCTSBot::StepWithPolicy(), open_spiel::Bot::StepWithPolicy(), and open_spiel::algorithms::UCT.
init_pyspiel_game_transforms() [1/2]
void open_spiel::init_pyspiel_game_transforms (::pybind11::module & m)
init_pyspiel_game_transforms() [2/2]
void open_spiel::init_pyspiel_game_transforms (py::module & m)
Definition at line 29 of file game_transforms.cc.
{
  m.def("load_game_as_turn_based",
        py::overload_cast<const std::string&>(&LoadGameAsTurnBased),
        "Converts a simultaneous game into an turn-based game with infosets.");
  m.def("load_game_as_turn_based",
        py::overload_cast<const std::string&, const GameParameters&>(
            &LoadGameAsTurnBased),
        "Converts a simultaneous game into an turn-based game with infosets.");
  m.def("extensive_to_tensor_game", ExtensiveToTensorGame,
        "Converts an extensive-game to its equivalent tensor game, "
        "which is exponentially larger. Use only with small games.");
  m.def(
      "convert_to_turn_based",
      [](std::shared_ptr<const Game> game) {
        return ConvertToTurnBased(*game);
      },
      "Returns a turn-based version of the given game.");
  m.def(
      "create_repeated_game",
      [](std::shared_ptr<const Game> game, const GameParameters& params) {
        return CreateRepeatedGame(*game, params);
      },
      "Creates a repeated game from a stage game.");
  m.def("create_repeated_game",
        py::overload_cast<const std::string&, const GameParameters&>(
            &CreateRepeatedGame),
        "Creates a repeated game from a stage game.");
}
References ConvertToTurnBased(), CreateRepeatedGame(), ExtensiveToTensorGame(), and LoadGameAsTurnBased().
init_pyspiel_games_backgammon()
void open_spiel::init_pyspiel_games_backgammon (::pybind11::module & m)
init_pyspiel_games_bargaining()
void open_spiel::init_pyspiel_games_bargaining (::pybind11::module & m)
init_pyspiel_games_bridge() [1/2]
void open_spiel::init_pyspiel_games_bridge (::pybind11::module & m)
init_pyspiel_games_bridge() [2/2]
void open_spiel::init_pyspiel_games_bridge (py::module & m)
Definition at line 32 of file games_bridge.cc.
{
  py::classh<BridgeState, State>(m, "BridgeState")
      .def("contract_index", &BridgeState::ContractIndex)
      .def("possible_contracts", &BridgeState::PossibleContracts)
      .def("score_by_contract", &BridgeState::ScoreByContract)
      .def("score_for_contracts", &BridgeState::ScoreForContracts)
      .def("current_phase", &BridgeState::CurrentPhase)
      .def("write_observation_tensor",
           [](const BridgeState& state,
              py::array_t<float, py::array::c_style> array) {
             py::buffer_info buf = array.request();
             SPIEL_CHECK_EQ(buf.ndim, 1);
             SPIEL_CHECK_EQ(buf.strides.front(), buf.itemsize);
             state.WriteObservationTensor(
                 state.CurrentPlayer(),
                 absl::MakeSpan(static_cast<float*>(buf.ptr),
                                buf.shape.front()));
           })
      .def("private_observation_tensor", &BridgeState::PrivateObservationTensor)
      .def("public_observation_tensor", &BridgeState::PublicObservationTensor)
      // Pickle support
      .def(py::pickle(
          [](const BridgeState& state) {  // __getstate__
            return SerializeGameAndState(*state.GetGame(), state);
          },
          [](const std::string& data) {  // __setstate__
            std::pair<std::shared_ptr<const Game>, std::unique_ptr<State>>
                game_and_state = DeserializeGameAndState(data);
            return dynamic_cast<BridgeState*>(game_and_state.second.release());
          }));
  py::classh<BridgeGame, Game>(m, "BridgeGame")
      .def("num_possible_contracts", &BridgeGame::NumPossibleContracts)
      .def("contract_string", &BridgeGame::ContractString)
      .def("private_observation_tensor_size",
           &BridgeGame::PrivateObservationTensorSize)
      .def("public_observation_tensor_size",
           &BridgeGame::PublicObservationTensorSize)
      // Pickle support
      .def(py::pickle(
          [](std::shared_ptr<const BridgeGame> game) {  // __getstate__
            return game->ToString();
          },
          [](const std::string& data) {  // __setstate__
            return std::dynamic_pointer_cast<BridgeGame>(
                std::const_pointer_cast<Game>(LoadGame(data)));
          }));
}
References buf, open_spiel::bridge::BridgeState::ContractIndex(), open_spiel::bridge::BridgeGame::ContractString(), open_spiel::bridge::BridgeState::CurrentPhase(), data, DeserializeGameAndState(), LoadGame(), absl::MakeSpan(), open_spiel::bridge::BridgeGame::NumPossibleContracts(), open_spiel::bridge::BridgeState::PossibleContracts(), open_spiel::bridge::BridgeState::PrivateObservationTensor(), open_spiel::bridge::BridgeGame::PrivateObservationTensorSize(), open_spiel::bridge::BridgeState::PublicObservationTensor(), open_spiel::bridge::BridgeGame::PublicObservationTensorSize(), open_spiel::bridge::BridgeState::ScoreByContract(), open_spiel::bridge::BridgeState::ScoreForContracts(), SerializeGameAndState(), SPIEL_CHECK_EQ, and state.
init_pyspiel_games_chess()
void open_spiel::init_pyspiel_games_chess (::pybind11::module & m)
init_pyspiel_games_colored_trails()
void open_spiel::init_pyspiel_games_colored_trails (::pybind11::module & m)
init_pyspiel_games_dots_and_boxes()
void open_spiel::init_pyspiel_games_dots_and_boxes (::pybind11::module & m)
init_pyspiel_games_euchre() [1/2]
void open_spiel::init_pyspiel_games_euchre (::pybind11::module & m)
init_pyspiel_games_euchre() [2/2]
void open_spiel::init_pyspiel_games_euchre (py::module & m)
Definition at line 37 of file games_euchre.cc.
{
  py::module_ euchre = m.def_submodule("euchre");
  euchre.attr("JACK_RANK") = py::int_(euchre::kJackRank);
  euchre.attr("NUM_SUITS") = py::int_(euchre::kNumSuits);
  euchre.attr("NUM_CARDS_PER_SUIT") = py::int_(euchre::kNumCardsPerSuit);
  euchre.attr("NUM_CARDS") = py::int_(euchre::kNumCards);
  euchre.attr("PASS_ACTION") = py::int_(euchre::kPassAction);
  euchre.attr("CLUBS_TRUMP_ACTION") = py::int_(euchre::kClubsTrumpAction);
  euchre.attr("DIAMONDS_TRUMP_ACTION") = py::int_(euchre::kDiamondsTrumpAction);
  euchre.attr("HEARTS_TRUMP_ACTION") = py::int_(euchre::kHeartsTrumpAction);
  euchre.attr("SPADES_TRUMP_ACTION") = py::int_(euchre::kSpadesTrumpAction);
  euchre.attr("GO_ALONE_ACTION") = py::int_(euchre::kGoAloneAction);
  euchre.attr("PLAY_WITH_PARTNER_ACTION") = py::int_(
      euchre::kPlayWithPartnerAction);
  euchre.attr("MAX_BIDS") = py::int_(euchre::kMaxBids);
  euchre.attr("NUM_TRICKS") = py::int_(euchre::kNumTricks);
  euchre.attr("FULL_HAND_SIZE") = py::int_(euchre::kFullHandSize);
  euchre.def("card_string", euchre::CardString);
  euchre.def("card_rank", py::overload_cast<int>(euchre::CardRank));
  euchre.def("card_rank",
             py::overload_cast<int, euchre::Suit>(euchre::CardRank));
  euchre.def("card_suit", py::overload_cast<int>(euchre::CardSuit));
  euchre.def("card_suit",
             py::overload_cast<int, euchre::Suit>(euchre::CardSuit));
  py::enum_<euchre::Suit>(euchre, "Suit")
    .value("INVALID_SUIT", euchre::Suit::kInvalidSuit)
    .value("CLUBS", euchre::Suit::kClubs)
    .value("DIAMONDS", euchre::Suit::kDiamonds)
    .value("HEARTS", euchre::Suit::kHearts)
    .value("SPADES", euchre::Suit::kSpades)
    .export_values();
  py::enum_<euchre::Phase>(euchre, "Phase")
      .value("DEALER_SELECTION", euchre::Phase::kDealerSelection)
      .value("DEAL", euchre::Phase::kDeal)
      .value("BIDDING", euchre::Phase::kBidding)
      .value("DISCARD", euchre::Phase::kDiscard)
      .value("GO_ALONE", euchre::Phase::kGoAlone)
      .value("PLAY", euchre::Phase::kPlay)
      .value("GAME_OVER", euchre::Phase::kGameOver)
      .export_values();
  py::classh<EuchreState, State> state_class(euchre, "EuchreState");
  state_class
      .def("num_cards_dealt", &EuchreState::NumCardsDealt)
      .def("num_cards_played", &EuchreState::NumCardsPlayed)
      .def("num_passes", &EuchreState::NumPasses)
      .def("upcard", &EuchreState::Upcard)
      .def("discard", &EuchreState::Discard)
      .def("trump_suit", &EuchreState::TrumpSuit)
      .def("left_bower", &EuchreState::LeftBower)
      .def("right_bower", &EuchreState::RightBower)
      .def("declarer", &EuchreState::Declarer)
      .def("declarer_partner", &EuchreState::DeclarerPartner)
      .def("first_defender", &EuchreState::FirstDefender)
      .def("second_defender", &EuchreState::SecondDefender)
      .def("declarer_go_alone", &EuchreState::DeclarerGoAlone)
      .def("lone_defender", &EuchreState::LoneDefender)
      .def("active_players", &EuchreState::ActivePlayers)
      .def("dealer", &EuchreState::Dealer)
      .def("current_phase", &EuchreState::CurrentPhase)
      .def("current_trick_index", &EuchreState::CurrentTrickIndex)
      .def("current_trick",
           py::overload_cast<>(&EuchreState::CurrentTrick, py::const_))
      .def("card_holder", &EuchreState::CardHolder)
      .def("tricks", &EuchreState::Tricks)
      // Pickle support
      .def(py::pickle(
          [](const EuchreState& state) {  // __getstate__
            return SerializeGameAndState(*state.GetGame(), state);
          },
          [](const std::string& data) {  // __setstate__
            std::pair<std::shared_ptr<const Game>, std::unique_ptr<State>>
                game_and_state = DeserializeGameAndState(data);
            return dynamic_cast<EuchreState*>(game_and_state.second.release());
          }));
  py::class_<euchre::Trick>(state_class, "Trick")
      .def("winning_card", &euchre::Trick::WinningCard)
      .def("led_suit", &euchre::Trick::LedSuit)
      .def("trump_suit", &euchre::Trick::TrumpSuit)
      .def("trump_played", &euchre::Trick::TrumpPlayed)
      .def("leader", &euchre::Trick::Leader)
      .def("winner", &euchre::Trick::Winner)
      .def("cards", &euchre::Trick::Cards);
  py::classh<EuchreGame, Game>(m, "EuchreGame")
      // Pickle support
      .def(py::pickle(
          [](std::shared_ptr<const EuchreGame> game) {  // __getstate__
            return game->ToString();
          },
          [](const std::string& data) {  // __setstate__
            return std::dynamic_pointer_cast<EuchreGame>(
                std::const_pointer_cast<Game>(LoadGame(data)));
          }));
}
References open_spiel::euchre::EuchreState::ActivePlayers(), open_spiel::euchre::EuchreState::CardHolder(), open_spiel::euchre::CardRank(), open_spiel::euchre::Trick::Cards(), open_spiel::euchre::CardString(), open_spiel::euchre::CardSuit(), open_spiel::euchre::EuchreState::CurrentPhase(), open_spiel::euchre::EuchreState::CurrentTrick(), open_spiel::euchre::EuchreState::CurrentTrickIndex(), data, open_spiel::euchre::EuchreState::Dealer(), open_spiel::euchre::EuchreState::Declarer(), open_spiel::euchre::EuchreState::DeclarerGoAlone(), open_spiel::euchre::EuchreState::DeclarerPartner(), DeserializeGameAndState(), open_spiel::euchre::EuchreState::Discard(), open_spiel::euchre::EuchreState::FirstDefender(), open_spiel::euchre::kBidding, open_spiel::euchre::kClubs, open_spiel::euchre::kClubsTrumpAction, open_spiel::euchre::kDeal, open_spiel::euchre::kDealerSelection, open_spiel::euchre::kDiamonds, open_spiel::euchre::kDiamondsTrumpAction, open_spiel::euchre::kDiscard, open_spiel::euchre::kFullHandSize, open_spiel::euchre::kGameOver, open_spiel::euchre::kGoAlone, open_spiel::euchre::kGoAloneAction, open_spiel::euchre::kHearts, open_spiel::euchre::kHeartsTrumpAction, open_spiel::euchre::kInvalidSuit, open_spiel::euchre::kJackRank, open_spiel::euchre::kMaxBids, open_spiel::euchre::kNumCards, open_spiel::euchre::kNumCardsPerSuit, open_spiel::euchre::kNumSuits, open_spiel::euchre::kNumTricks, open_spiel::euchre::kPassAction, open_spiel::euchre::kPlay, open_spiel::euchre::kPlayWithPartnerAction, open_spiel::euchre::kSpades, open_spiel::euchre::kSpadesTrumpAction, open_spiel::euchre::Trick::Leader(), open_spiel::euchre::Trick::LedSuit(), open_spiel::euchre::EuchreState::LeftBower(), LoadGame(), open_spiel::euchre::EuchreState::LoneDefender(), open_spiel::euchre::EuchreState::NumCardsDealt(), open_spiel::euchre::EuchreState::NumCardsPlayed(), open_spiel::euchre::EuchreState::NumPasses(), open_spiel::euchre::EuchreState::RightBower(), open_spiel::euchre::EuchreState::SecondDefender(), SerializeGameAndState(), state, open_spiel::euchre::EuchreState::Tricks(), open_spiel::euchre::Trick::TrumpPlayed(), open_spiel::euchre::EuchreState::TrumpSuit(), open_spiel::euchre::Trick::TrumpSuit(), open_spiel::euchre::EuchreState::Upcard(), open_spiel::euchre::Trick::Winner(), and open_spiel::euchre::Trick::WinningCard().
init_pyspiel_games_gin_rummy() [1/2]
void open_spiel::init_pyspiel_games_gin_rummy (::pybind11::module & m)
init_pyspiel_games_gin_rummy() [2/2]
void open_spiel::init_pyspiel_games_gin_rummy (py::module & m)
Definition at line 40 of file games_gin_rummy.cc.
{
  py::module_ gin_rummy = m.def_submodule("gin_rummy");
  gin_rummy.attr("DEFAULT_NUM_RANKS") = py::int_(gin_rummy::kDefaultNumRanks);
  gin_rummy.attr("DEFAULT_NUM_SUITS") = py::int_(gin_rummy::kDefaultNumSuits);
  gin_rummy.attr("DEFAULT_NUM_CARDS") = py::int_(gin_rummy::kDefaultNumCards);
  gin_rummy.attr("NUM_PLAYERS") = py::int_(gin_rummy::kNumPlayers);
  gin_rummy.attr("MAX_POSSIBLE_DEADWOOD") = py::int_(
      gin_rummy::kMaxPossibleDeadwood);
  gin_rummy.attr("MAX_NUM_DRAW_UPCARD_ACTIONS") = py::int_(
      gin_rummy::kMaxNumDrawUpcardActions);
  gin_rummy.attr("DEFAULT_HAND_SIZE") = py::int_(gin_rummy::kDefaultHandSize);
  gin_rummy.attr("WALL_STOCK_SIZE") = py::int_(gin_rummy::kWallStockSize);
  gin_rummy.attr("DEFAULT_KNOCK_CARD") = py::int_(gin_rummy::kDefaultKnockCard);
  gin_rummy.attr("DEFAULT_GIN_BONUS") = py::int_(gin_rummy::kDefaultGinBonus);
  gin_rummy.attr("DEFAULT_UNDERCUT_BONUS") = py::int_(
      gin_rummy::kDefaultUndercutBonus);
  gin_rummy.attr("DRAW_UPCARD_ACTION") = py::int_(gin_rummy::kDrawUpcardAction);
  gin_rummy.attr("DRAW_STOCK_ACTION") = py::int_(gin_rummy::kDrawStockAction);
  gin_rummy.attr("PASS_ACTION") = py::int_(gin_rummy::kPassAction);
  gin_rummy.attr("KNOCK_ACTION") = py::int_(gin_rummy::kKnockAction);
  gin_rummy.attr("MELD_ACTION_BASE") = py::int_(gin_rummy::kMeldActionBase);
  gin_rummy.attr("NUM_MELD_ACTIONS") = py::int_(gin_rummy::kNumMeldActions);
  gin_rummy.attr("NUM_DISTINCT_ACTIONS") = py::int_(
      gin_rummy::kNumDistinctActions);
  gin_rummy.attr("OBSERVATION_TENSOR_SIZE") = py::int_(
      gin_rummy::kObservationTensorSize);
  py::enum_<gin_rummy::Phase>(gin_rummy, "Phase")
      .value("DEAL", gin_rummy::Phase::kDeal)
      .value("FIRST_UPCARD", gin_rummy::Phase::kFirstUpcard)
      .value("DRAW", gin_rummy::Phase::kDraw)
      .value("DISCARD", gin_rummy::Phase::kDiscard)
      .value("KNOCK", gin_rummy::Phase::kKnock)
      .value("LAYOFF", gin_rummy::Phase::kLayoff)
      .value("WALL", gin_rummy::Phase::kWall)
      .value("GAME_OVER", gin_rummy::Phase::kGameOver)
      .export_values();
  py::classh<GinRummyState, State> state_class(gin_rummy, "GinRummyState");
  state_class
      .def("current_phase", &GinRummyState::CurrentPhase)
      .def("current_player", &GinRummyState::CurrentPlayer)
      .def("finished_layoffs", &GinRummyState::FinishedLayoffs)
      .def("upcard", &GinRummyState::Upcard)
      .def("stock_size", &GinRummyState::StockSize)
      .def("hands", &GinRummyState::Hands)
      .def("discard_pile", &GinRummyState::DiscardPile)
      .def("deadwood", &GinRummyState::Deadwood)
      .def("knocked", &GinRummyState::Knocked)
      .def("pass_on_first_upcard", &GinRummyState::PassOnFirstUpcard)
      .def("layed_melds", &GinRummyState::LayedMelds)
      .def("layoffs", &GinRummyState::Layoffs)
      // Pickle support
      .def(py::pickle(
          [](const GinRummyState& state) {  // __getstate__
            return SerializeGameAndState(*state.GetGame(), state);
          },
          [](const std::string& data) {  // __setstate__
            std::pair<std::shared_ptr<const Game>, std::unique_ptr<State>>
                game_and_state = DeserializeGameAndState(data);
            return dynamic_cast<GinRummyState*>(
                game_and_state.second.release());
          }));
  py::classh<GinRummyGame, Game>(m, "GinRummyGame")
      .def("oklahoma", &GinRummyGame::Oklahoma)
      .def("knock_card", &GinRummyGame::KnockCard)
      // Pickle support
      .def(py::pickle(
          [](std::shared_ptr<const GinRummyGame> game) {  // __getstate__
            return game->ToString();
          },
          [](const std::string& data) {  // __setstate__
            return std::dynamic_pointer_cast<GinRummyGame>(
                std::const_pointer_cast<Game>(LoadGame(data)));
          }));
  py::class_<GinRummyUtils>(gin_rummy, "GinRummyUtils")
      .def(py::init<int, int, int>())
      .def("card_string", &GinRummyUtils::CardString)
      .def("hand_to_string", &GinRummyUtils::HandToString)
      .def("card_int", &GinRummyUtils::CardInt)
      .def("card_ints_to_card_strings", &GinRummyUtils::CardIntsToCardStrings)
      .def("card_strings_to_card_ints", &GinRummyUtils::CardStringsToCardInts)
      .def("card_value", &GinRummyUtils::CardValue)
      .def("total_card_value",
           py::overload_cast<const gin_rummy::VecInt &>(
               &GinRummyUtils::TotalCardValue, py::const_))
      .def("total_card_value",
           py::overload_cast<const gin_rummy::VecVecInt &>(
               &GinRummyUtils::TotalCardValue, py::const_))
      .def("card_rank", &GinRummyUtils::CardRank)
      .def("card_suit", &GinRummyUtils::CardSuit)
      .def("is_consecutive", &GinRummyUtils::IsConsecutive)
      .def("is_rank_meld", &GinRummyUtils::IsRankMeld)
      .def("is_suit_meld", &GinRummyUtils::IsSuitMeld)
      .def("rank_melds", &GinRummyUtils::RankMelds)
      .def("suit_melds", &GinRummyUtils::SuitMelds)
      .def("all_melds", &GinRummyUtils::AllMelds)
      .def("all_meld_groups", &GinRummyUtils::AllMeldGroups)
      .def("best_meld_group", &GinRummyUtils::BestMeldGroup)
      .def("min_deadwood",
           py::overload_cast<gin_rummy::VecInt, absl::optional<int>>(
               &GinRummyUtils::MinDeadwood, py::const_))
      .def("min_deadwood",
           py::overload_cast<const gin_rummy::VecInt &>(
               &GinRummyUtils::MinDeadwood, py::const_))
      .def("rank_meld_layoff", &GinRummyUtils::RankMeldLayoff)
      .def("suit_meld_layoffs", &GinRummyUtils::SuitMeldLayoffs)
      .def("legal_melds", &GinRummyUtils::LegalMelds)
      .def("legal_discards", &GinRummyUtils::LegalDiscards)
      .def("all_layoffs", &GinRummyUtils::AllLayoffs)
      .def_readonly("int_to_meld", &GinRummyUtils::int_to_meld)
      .def("meld_to_int", &GinRummyUtils::MeldToInt);
}
References open_spiel::gin_rummy::GinRummyUtils::AllLayoffs(), open_spiel::gin_rummy::GinRummyUtils::AllMeldGroups(), open_spiel::gin_rummy::GinRummyUtils::AllMelds(), open_spiel::gin_rummy::GinRummyUtils::BestMeldGroup(), open_spiel::gin_rummy::GinRummyUtils::CardInt(), open_spiel::gin_rummy::GinRummyUtils::CardIntsToCardStrings(), open_spiel::gin_rummy::GinRummyUtils::CardRank(), open_spiel::gin_rummy::GinRummyUtils::CardString(), open_spiel::gin_rummy::GinRummyUtils::CardStringsToCardInts(), open_spiel::gin_rummy::GinRummyUtils::CardSuit(), open_spiel::gin_rummy::GinRummyUtils::CardValue(), open_spiel::gin_rummy::GinRummyState::CurrentPhase(), open_spiel::gin_rummy::GinRummyState::CurrentPlayer(), data, open_spiel::gin_rummy::GinRummyState::Deadwood(), DeserializeGameAndState(), open_spiel::gin_rummy::GinRummyState::DiscardPile(), open_spiel::gin_rummy::GinRummyState::FinishedLayoffs(), open_spiel::gin_rummy::GinRummyState::Hands(), open_spiel::gin_rummy::GinRummyUtils::HandToString(), open_spiel::gin_rummy::GinRummyUtils::int_to_meld, open_spiel::gin_rummy::GinRummyUtils::IsConsecutive(), open_spiel::gin_rummy::GinRummyUtils::IsRankMeld(), open_spiel::gin_rummy::GinRummyUtils::IsSuitMeld(), open_spiel::gin_rummy::kDeal, open_spiel::gin_rummy::kDefaultGinBonus, open_spiel::gin_rummy::kDefaultHandSize, open_spiel::gin_rummy::kDefaultKnockCard, open_spiel::gin_rummy::kDefaultNumCards, open_spiel::gin_rummy::kDefaultNumRanks, open_spiel::gin_rummy::kDefaultNumSuits, open_spiel::gin_rummy::kDefaultUndercutBonus, open_spiel::gin_rummy::kDiscard, open_spiel::gin_rummy::kDraw, open_spiel::gin_rummy::kDrawStockAction, open_spiel::gin_rummy::kDrawUpcardAction, open_spiel::gin_rummy::kFirstUpcard, open_spiel::gin_rummy::kGameOver, open_spiel::gin_rummy::kKnock, open_spiel::gin_rummy::kKnockAction, open_spiel::gin_rummy::kLayoff, open_spiel::gin_rummy::kMaxNumDrawUpcardActions, open_spiel::gin_rummy::kMaxPossibleDeadwood, open_spiel::gin_rummy::kMeldActionBase, open_spiel::gin_rummy::GinRummyGame::KnockCard(), open_spiel::gin_rummy::GinRummyState::Knocked(), open_spiel::gin_rummy::kNumDistinctActions, open_spiel::gin_rummy::kNumMeldActions, open_spiel::gin_rummy::kNumPlayers, open_spiel::gin_rummy::kObservationTensorSize, open_spiel::gin_rummy::kPassAction, open_spiel::gin_rummy::kWall, open_spiel::gin_rummy::kWallStockSize, open_spiel::gin_rummy::GinRummyState::LayedMelds(), open_spiel::gin_rummy::GinRummyState::Layoffs(), open_spiel::gin_rummy::GinRummyUtils::LegalDiscards(), open_spiel::gin_rummy::GinRummyUtils::LegalMelds(), LoadGame(), open_spiel::gin_rummy::GinRummyUtils::MeldToInt(), open_spiel::gin_rummy::GinRummyUtils::MinDeadwood(), open_spiel::gin_rummy::GinRummyGame::Oklahoma(), open_spiel::gin_rummy::GinRummyState::PassOnFirstUpcard(), open_spiel::gin_rummy::GinRummyUtils::RankMeldLayoff(), open_spiel::gin_rummy::GinRummyUtils::RankMelds(), SerializeGameAndState(), state, open_spiel::gin_rummy::GinRummyState::StockSize(), open_spiel::gin_rummy::GinRummyUtils::SuitMeldLayoffs(), open_spiel::gin_rummy::GinRummyUtils::SuitMelds(), open_spiel::gin_rummy::GinRummyUtils::TotalCardValue(), and open_spiel::gin_rummy::GinRummyState::Upcard().
init_pyspiel_games_kuhn_poker()
void open_spiel::init_pyspiel_games_kuhn_poker (::pybind11::module & m)
init_pyspiel_games_leduc_poker()
void open_spiel::init_pyspiel_games_leduc_poker (::pybind11::module & m)
init_pyspiel_games_negotiation()
void open_spiel::init_pyspiel_games_negotiation (::pybind11::module & m)
init_pyspiel_games_tarok() [1/2]
void open_spiel::init_pyspiel_games_tarok (::pybind11::module & m)
init_pyspiel_games_tarok() [2/2]
void open_spiel::init_pyspiel_games_tarok (py::module & m)
Definition at line 25 of file games_tarok.cc.
{
  // state object
  py::classh<TarokState, State> tarok_state(m, "TarokState");
  tarok_state.def("card_action_to_string",
                  &TarokState::CardActionToString);
  tarok_state.def("current_game_phase", &TarokState::CurrentGamePhase);
  tarok_state.def("player_cards", &TarokState::PlayerCards);
  tarok_state.def("selected_contract",
                  &TarokState::SelectedContractName);
  tarok_state.def("talon", &TarokState::Talon);
  tarok_state.def("talon_sets", &TarokState::TalonSets);
  tarok_state.def("trick_cards", &TarokState::TrickCards);
  tarok_state.def("captured_mond_penalties",
                  &TarokState::CapturedMondPenalties);
  tarok_state.def("scores_without_captured_mond_penalties",
                  &TarokState::ScoresWithoutCapturedMondPenalties);
  tarok_state.def(py::pickle(
      [](const TarokState& state) {  // __getstate__
        return SerializeGameAndState(*state.GetGame(), state);
      },
          [](const std::string& data) {  // __setstate__
            std::pair<std::shared_ptr<const Game>, std::unique_ptr<State>>
                game_and_state = DeserializeGameAndState(data);
            return dynamic_cast<TarokState*>(game_and_state.second.release());
          }));
  // game phase object
  py::enum_<tarok::GamePhase> game_phase(m, "TarokGamePhase");
  game_phase.value("CARD_DEALING", tarok::GamePhase::kCardDealing);
  game_phase.value("BIDDING", tarok::GamePhase::kBidding);
  game_phase.value("KING_CALLING", tarok::GamePhase::kKingCalling);
  game_phase.value("TALON_EXCHANGE", tarok::GamePhase::kTalonExchange);
  game_phase.value("TRICKS_PLAYING", tarok::GamePhase::kTricksPlaying);
  game_phase.value("FINISHED", tarok::GamePhase::kFinished);
  // contract name object
  py::enum_<tarok::ContractName> contract(m, "TarokContract");
  contract.value("KLOP", tarok::ContractName::kKlop);
  contract.value("THREE", tarok::ContractName::kThree);
  contract.value("TWO", tarok::ContractName::kTwo);
  contract.value("ONE", tarok::ContractName::kOne);
  contract.value("SOLO_THREE", tarok::ContractName::kSoloThree);
  contract.value("SOLO_TWO", tarok::ContractName::kSoloTwo);
  contract.value("SOLO_ONE", tarok::ContractName::kSoloOne);
  contract.value("BEGGAR", tarok::ContractName::kBeggar);
  contract.value("SOLO_WITHOUT", tarok::ContractName::kSoloWithout);
  contract.value("OPEN_BEGGAR", tarok::ContractName::kOpenBeggar);
  contract.value("COLOUR_VALAT_WITHOUT",
                 tarok::ContractName::kColourValatWithout);
  contract.value("VALAT_WITHOUT", tarok::ContractName::kValatWithout);
  contract.value("NOT_SELECTED", tarok::ContractName::kNotSelected);
}
References open_spiel::tarok::TarokState::CapturedMondPenalties(), open_spiel::tarok::TarokState::CardActionToString(), open_spiel::tarok::TarokState::CurrentGamePhase(), data, DeserializeGameAndState(), open_spiel::tarok::kBeggar, open_spiel::tarok::kBidding, open_spiel::tarok::kCardDealing, open_spiel::tarok::kColourValatWithout, open_spiel::tarok::kFinished, open_spiel::tarok::kKingCalling, open_spiel::tarok::kKlop, open_spiel::tarok::kNotSelected, open_spiel::tarok::kOne, open_spiel::tarok::kOpenBeggar, open_spiel::tarok::kSoloOne, open_spiel::tarok::kSoloThree, open_spiel::tarok::kSoloTwo, open_spiel::tarok::kSoloWithout, open_spiel::tarok::kTalonExchange, open_spiel::tarok::kThree, open_spiel::tarok::kTricksPlaying, open_spiel::tarok::kTwo, open_spiel::tarok::kValatWithout, open_spiel::tarok::TarokState::PlayerCards(), open_spiel::tarok::TarokState::ScoresWithoutCapturedMondPenalties(), open_spiel::tarok::TarokState::SelectedContractName(), SerializeGameAndState(), state, open_spiel::tarok::TarokState::Talon(), open_spiel::tarok::TarokState::TalonSets(), and open_spiel::tarok::TarokState::TrickCards().
init_pyspiel_games_tiny_bridge()
void open_spiel::init_pyspiel_games_tiny_bridge (::pybind11::module & m)
init_pyspiel_games_trade_comm()
void open_spiel::init_pyspiel_games_trade_comm (::pybind11::module & m)
init_pyspiel_games_universal_poker()
void open_spiel::init_pyspiel_games_universal_poker (::pybind11::module & m)
init_pyspiel_gamut()
void open_spiel::init_pyspiel_gamut (::pybind11::module & m)
Definition at line 22 of file gamut_pybind11.cc.
{
  py::class_<gamut::GamutGenerator> gamut_generator(m, "GamutGenerator");
  gamut_generator.def(py::init<std::string>())
      .def(py::init<std::string, std::string>())
      .def("generate_game", py::overload_cast<const std::string&>(
                                &gamut::GamutGenerator::GenerateGame))
      .def("generate_game", py::overload_cast<const std::vector<std::string>&>(
                                &gamut::GamutGenerator::GenerateGame))
      .def("generate_matrix_game", &gamut::GamutGenerator::GenerateMatrixGame)
      .def("generate_tensor_game", &gamut::GamutGenerator::GenerateTensorGame);
}
References open_spiel::gamut::GamutGenerator::GenerateGame(), open_spiel::gamut::GamutGenerator::GenerateMatrixGame(), and open_spiel::gamut::GamutGenerator::GenerateTensorGame().
init_pyspiel_observer() [1/2]
void open_spiel::init_pyspiel_observer (::pybind11::module & m)
init_pyspiel_observer() [2/2]
void open_spiel::init_pyspiel_observer (py::module & m)
Definition at line 27 of file observer.cc.
{
  // C++ Observer, intended only for the Python Observation class, not
  // for general Python code.
  py::class_<Observer, std::shared_ptr<Observer>>(m, "Observer")
      .def("__str__", [](const Observer& self) { return "Observer()"; });
  py::class_<SpanTensorInfo>(m, "SpanTensorInfo")
      .def_property_readonly(
          "name", [](const SpanTensorInfo& info) { return info.name(); })
      .def_property_readonly(
          "shape",
          [](const SpanTensorInfo& info) { return info.vector_shape(); })
      .def("__str__", &SpanTensorInfo::DebugString);
  py::class_<SpanTensor>(m, "SpanTensor")
      .def_property_readonly(
          "name", [](const SpanTensor& tensor) { return tensor.info().name(); })
      .def_property_readonly(
          "shape",
          [](const SpanTensor& tensor) { return tensor.info().vector_shape(); })
      .def_property_readonly("data",
                             [](const SpanTensor& tensor) {
                               // absl::Span requires pybind11_abseil which
                               // open spiel forbids. Thus copy the data
                               // and expose a vector through pybind.
                               std::vector<float> data(tensor.data().begin(),
                                                       tensor.data().end());
                               return data;
                             })
      .def("__str__", &SpanTensor::DebugString);
  // C++ Observation, intended only for the Python Observation class, not
  // for general Python code.
  py::class_<Observation>(m, "_Observation", py::buffer_protocol())
      .def(py::init([](std::shared_ptr<const Game> game,
                       std::shared_ptr<Observer> observer) {
             return new Observation(*game, observer);
           }),
           py::arg("game"), py::arg("observer"))
      .def("tensors", &Observation::tensors)
      .def("tensors_info", &Observation::tensors_info)
      .def("string_from", &Observation::StringFrom)
      .def("set_from", &Observation::SetFrom)
      .def("has_string", &Observation::HasString)
      .def("has_tensor", &Observation::HasTensor)
      .def("compress",
           [](const Observation& self) { return py::bytes(self.Compress()); })
      .def("decompress", &Observation::Decompress)
      .def_buffer([](Observation& buffer_observer) -> py::buffer_info {
        return py::buffer_info(
            buffer_observer.Tensor().data(),         // Pointer to buffer
            sizeof(float),                           // Size of one scalar
            py::format_descriptor<float>::format(),  // Format descriptor
            1,                                       // Num dimensions
            {buffer_observer.Tensor().size()},       // Dimensions
            {sizeof(float)}                          // Stride
        );
      });
}
References absl::Span< T >::begin(), absl::Span< T >::data(), data, open_spiel::SpanTensor::data(), open_spiel::SpanTensor::DebugString(), open_spiel::SpanTensorInfo::DebugString(), open_spiel::Observation::Decompress(), absl::Span< T >::end(), open_spiel::Observation::HasString(), open_spiel::Observation::HasTensor(), open_spiel::SpanTensor::info(), name, open_spiel::Observation::SetFrom(), open_spiel::Observation::StringFrom(), open_spiel::Observation::Tensor(), open_spiel::Observation::tensors(), and open_spiel::Observation::tensors_info().
init_pyspiel_policy() [1/2]
void open_spiel::init_pyspiel_policy (::pybind11::module & m)
init_pyspiel_policy() [2/2]
void open_spiel::init_pyspiel_policy (py::module & m)
Definition at line 51 of file policy.cc.
{
  py::classh<Policy, PyPolicy> policy(m, "Policy");
  policy.def(py::init<>())
      .def("action_probabilities",
           py::overload_cast<const State&>(&Policy::GetStatePolicyAsMap,
                                           py::const_),
           py::arg("state"),
           "Returns a dictionary mapping actions to probabilities for the "
           "policy at the given "
           "state.")
      .def("action_probabilities",
           py::overload_cast<const std::string&>(&Policy::GetStatePolicyAsMap,
                                                 py::const_),
           py::arg("info_state"),
           "Returns a dictionary mapping actions to probabilities for the "
           "policy at the given "
           "information state.")
      .def("get_state_policy",
           py::overload_cast<const State&>(&Policy::GetStatePolicy, py::const_),
           py::arg("state"),
           "Returns a list of (action, prob) pairs for the policy at the given "
           "state.")
      .def("get_state_policy",
           py::overload_cast<const State&, Player>(&Policy::GetStatePolicy,
                                                   py::const_),
           py::arg("state"), py::arg("player"),
           "Returns a list of (action, prob) pairs for the policy for the "
           "specified player at the "
           "given state.")
      .def("get_state_policy",
           py::overload_cast<const std::string&>(&Policy::GetStatePolicy,
                                                 py::const_),
           py::arg("info_state"),
           "Returns a list of (action, prob) pairs for the policy at the given "
           "info state.")
      .def("get_state_policy_as_parallel_vectors",
           py::overload_cast<const State&>(
               &Policy::GetStatePolicyAsParallelVectors, py::const_),
           py::arg("state"),
           "Returns a pair of parallel vectors (actions, probs) for the policy "
           "at the given state.")
      .def("get_state_policy_as_parallel_vectors",
           py::overload_cast<const std::string&>(
               &Policy::GetStatePolicyAsParallelVectors, py::const_),
           py::arg("info_state"),
           "Returns a pair of parallel vectors (actions, probs) for the policy "
           "at the given "
           "information state.")
      .def("serialize", &Policy::Serialize, py::arg("double_precision") = -1,
           py::arg("delimiter") = "<~>", "Serializes the policy to a string.");
  auto ptt = m.def_submodule(
      "_policy_trampoline_testing",
      "Internal test functions for calling policy member functions.");
  ptt.def("call_action_probabilities",
          [](const Policy& policy, const State& state) {
            return policy.GetStatePolicyAsMap(state);
          });
  ptt.def("call_action_probabilities",
          [](const Policy& policy, const std::string& info_state) {
            return policy.GetStatePolicyAsMap(info_state);
          });
  ptt.def("call_get_state_policy",
          [](const Policy& policy, const State& state) {
            return policy.GetStatePolicy(state);
          });
  ptt.def("call_get_state_policy",
          [](const Policy& policy, const State& state, Player player) {
            return policy.GetStatePolicy(state, player);
          });
  ptt.def("call_get_state_policy",
          [](const Policy& policy, const std::string& info_state) {
            return policy.GetStatePolicy(info_state);
          });
  ptt.def("call_get_state_policy_as_parallel_vectors",
          [](const Policy& policy, const State& state) {
            return policy.GetStatePolicyAsParallelVectors(state);
          });
  ptt.def("call_get_state_policy_as_parallel_vectors",
          [](const Policy& policy, const std::string& info_state) {
            return policy.GetStatePolicyAsParallelVectors(info_state);
          });
  ptt.def("call_serialize", [](const Policy& policy, int precision,
                               const std::string& delimiter = "<~>") {
    return policy.Serialize(precision, delimiter);
  });
  py::class_<TabularBestResponse>(m, "TabularBestResponse")
      .def(py::init<const open_spiel::Game&, int,
                    const std::unordered_map<std::string,
                                             open_spiel::ActionsAndProbs>&>())
      .def(py::init<const open_spiel::Game&, int, const open_spiel::Policy*>())
      .def(py::init<
           const open_spiel::Game&, int,
           const std::unordered_map<std::string, open_spiel::ActionsAndProbs>&,
           const float, const float>())
      .def(py::init<const open_spiel::Game&, int, const open_spiel::Policy*,
                    const float, const float>())
      .def("value",
           py::overload_cast<const std::string&>(&TabularBestResponse::Value))
      .def("value_from_state", py::overload_cast<const open_spiel::State&>(
                                   &TabularBestResponse::Value))
      .def("get_best_response_policy",
           &TabularBestResponse::GetBestResponsePolicy)
      .def("get_best_response_actions",
           &TabularBestResponse::GetBestResponseActions)
      .def("set_policy", py::overload_cast<const std::unordered_map<
                             std::string, open_spiel::ActionsAndProbs>&>(
                             &TabularBestResponse::SetPolicy))
      .def("set_policy",
           py::overload_cast<const Policy*>(&TabularBestResponse::SetPolicy));
  // A tabular policy represented internally as a map. Note that this
  // implementation is not directly compatible with the Python TabularPolicy
  // implementation; the latter is implemented as a table of size
  // [num_states, num_actions], while this is implemented as a map. It is
  // non-trivial to convert between the two, but we have a function that does so
  // in the open_spiel/python/policy.py file.
  py::classh<TabularPolicy, Policy>(m, "TabularPolicy")
      .def(py::init<const std::unordered_map<std::string, ActionsAndProbs>&>())
      .def("__str__", &TabularPolicy::ToString)
      .def("__repr__", &TabularPolicy::ToString)
      .def("__len__", &TabularPolicy::size)
      .def("get_state_policy", &TabularPolicy::GetStatePolicy)
      .def("policy_table",
           py::overload_cast<>(&TabularPolicy::PolicyTable))
      .def("size", &TabularPolicy::size)
      .def("to_string", &TabularPolicy::ToString);
  py::classh<open_spiel::PartialTabularPolicy, open_spiel::Policy>(
      m, "PartialTabularPolicy")
      .def(py::init<>())
      .def(py::init<const std::unordered_map<std::string, ActionsAndProbs>&>())
      .def(py::init<const std::unordered_map<std::string, ActionsAndProbs>&,
                    std::shared_ptr<Policy>>())
      .def("get_state_policy",
           (ActionsAndProbs(open_spiel::Policy::*)(const State&) const) &
               open_spiel::PartialTabularPolicy::GetStatePolicy)
      .def(
          "get_state_policy",
          (ActionsAndProbs(open_spiel::Policy::*)(const State&, Player) const) &
              open_spiel::PartialTabularPolicy::GetStatePolicy)
      .def("get_state_policy",
           (ActionsAndProbs(open_spiel::Policy::*)(const std::string&) const) &
               open_spiel::PartialTabularPolicy::GetStatePolicy)
      .def("set_prob", &open_spiel::PartialTabularPolicy::SetProb)
      .def("set_state_policy",
           &open_spiel::PartialTabularPolicy::SetStatePolicy)
      .def("policy_table",
           py::overload_cast<>(&open_spiel::PartialTabularPolicy::PolicyTable));
  m.def("GetRandomPolicy", &open_spiel::GetRandomPolicy,
      py::arg("game"), py::arg("seed"), py::arg("player") = -1);
  m.def("GetFlatDirichletPolicy", &open_spiel::GetFlatDirichletPolicy,
      py::arg("game"), py::arg("seed"), py::arg("player") = -1);
  m.def("GetRandomDeterministicPolicy",
      &open_spiel::GetRandomDeterministicPolicy,
      py::arg("game"), py::arg("seed"), py::arg("player") = -1);
  m.def("UniformRandomPolicy", &open_spiel::GetUniformPolicy);
  py::classh<open_spiel::UniformPolicy, open_spiel::Policy>(m, "UniformPolicy")
      .def(py::init<>())
      .def("get_state_policy", &open_spiel::UniformPolicy::GetStatePolicy);
  py::classh<open_spiel::PreferredActionPolicy, open_spiel::Policy>(
      m, "PreferredActionPolicy")
      .def(py::init<const std::vector<Action>&>())
      .def("get_state_policy",
           &open_spiel::PreferredActionPolicy::GetStatePolicy);
  py::class_<open_spiel::algorithms::CFRSolver>(m, "CFRSolver")
      .def(py::init([](std::shared_ptr<const Game> game) {
        return new algorithms::CFRSolver(*game);
      }))
      .def("evaluate_and_update_policy",
           &open_spiel::algorithms::CFRSolver::EvaluateAndUpdatePolicy)
      .def("current_policy", &open_spiel::algorithms::CFRSolver::CurrentPolicy)
      .def("average_policy", &open_spiel::algorithms::CFRSolver::AveragePolicy)
      .def("tabular_average_policy",
           &open_spiel::algorithms::CFRSolver::TabularAveragePolicy)
      .def("tabular_current_policy",
           &open_spiel::algorithms::CFRSolver::TabularCurrentPolicy)
      .def(py::pickle(
          [](const open_spiel::algorithms::CFRSolver& solver) {  // __getstate__
            return solver.Serialize();
          },
          [](const std::string& serialized) {  // __setstate__
            return open_spiel::algorithms::DeserializeCFRSolver(serialized);
          }));
  py::class_<open_spiel::algorithms::CFRPlusSolver>(m, "CFRPlusSolver")
      .def(py::init([](std::shared_ptr<const Game> game) {
        return new algorithms::CFRPlusSolver(*game);
      }))
      .def("evaluate_and_update_policy",
           &open_spiel::algorithms::CFRPlusSolver::EvaluateAndUpdatePolicy)
      .def("current_policy", &open_spiel::algorithms::CFRSolver::CurrentPolicy)
      .def("average_policy",
           &open_spiel::algorithms::CFRPlusSolver::AveragePolicy)
      .def("tabular_average_policy",
           &open_spiel::algorithms::CFRPlusSolver::TabularAveragePolicy)
      .def(py::pickle(
          [](const open_spiel::algorithms::CFRPlusSolver&
                 solver) {  // __getstate__
            return solver.Serialize();
          },
          [](const std::string& serialized) {  // __setstate__
            return open_spiel::algorithms::DeserializeCFRPlusSolver(serialized);
          }));
  py::class_<open_spiel::algorithms::CFRBRSolver>(m, "CFRBRSolver")
      .def(py::init([](std::shared_ptr<const Game> game) {
        return new algorithms::CFRBRSolver(*game);
      }))
      .def("evaluate_and_update_policy",
           &open_spiel::algorithms::CFRPlusSolver::EvaluateAndUpdatePolicy)
      .def("current_policy", &open_spiel::algorithms::CFRSolver::CurrentPolicy)
      .def("average_policy",
           &open_spiel::algorithms::CFRPlusSolver::AveragePolicy)
      .def(py::pickle(
          [](const open_spiel::algorithms::CFRBRSolver&
                 solver) {  // __getstate__
            return solver.Serialize();
          },
          [](const std::string& serialized) {  // __setstate__
            return open_spiel::algorithms::DeserializeCFRBRSolver(serialized);
          }));
  py::enum_<open_spiel::algorithms::AverageType>(m, "MCCFRAverageType")
      .value("SIMPLE", open_spiel::algorithms::AverageType::kSimple)
      .value("FULL", open_spiel::algorithms::AverageType::kFull);
  py::class_<open_spiel::algorithms::ExternalSamplingMCCFRSolver>(
      m, "ExternalSamplingMCCFRSolver")
      .def(py::init([](std::shared_ptr<const Game> game, int seed,
                       algorithms::AverageType average_type) {
             return new algorithms::ExternalSamplingMCCFRSolver(*game, seed,
                                                                average_type);
           }),
           py::arg("game"), py::arg("seed") = 0,
           py::arg("avg_type") = open_spiel::algorithms::AverageType::kSimple)
      .def("run_iteration",
           py::overload_cast<>(&open_spiel::algorithms::
                                   ExternalSamplingMCCFRSolver::RunIteration))
      .def("average_policy",
           &open_spiel::algorithms::ExternalSamplingMCCFRSolver::AveragePolicy)
      .def(py::pickle(
          [](const open_spiel::algorithms::ExternalSamplingMCCFRSolver&
                 solver) {  // __getstate__
            return solver.Serialize();
          },
          [](const std::string& serialized) {  // __setstate__
            return open_spiel::algorithms::
                DeserializeExternalSamplingMCCFRSolver(serialized);
          }));
  py::class_<open_spiel::algorithms::OutcomeSamplingMCCFRSolver>(
      m, "OutcomeSamplingMCCFRSolver")
      .def(py::init(
               [](std::shared_ptr<const Game> game, double epsilon, int seed) {
                 return new algorithms::OutcomeSamplingMCCFRSolver(
                     *game, epsilon, seed);
               }),
           py::arg("game"),
           py::arg("epsilon") = open_spiel::algorithms::
               OutcomeSamplingMCCFRSolver::kDefaultEpsilon,
           py::arg("seed") = -1)
      .def("run_iteration",
           py::overload_cast<>(&open_spiel::algorithms::
                                   OutcomeSamplingMCCFRSolver::RunIteration))
      .def("average_policy",
           &open_spiel::algorithms::OutcomeSamplingMCCFRSolver::AveragePolicy)
      .def(py::pickle(
          [](const open_spiel::algorithms::OutcomeSamplingMCCFRSolver&
                 solver) {  // __getstate__
            return solver.Serialize();
          },
          [](const std::string& serialized) {  // __setstate__
            return open_spiel::algorithms::
                DeserializeOutcomeSamplingMCCFRSolver(serialized);
          }));
  py::class_<TabularBestResponseMDPInfo>(m, "TabularBestResponseMDPInfo")
      .def_readonly("br_values", &TabularBestResponseMDPInfo::br_values)
      .def_readonly("br_policies", &TabularBestResponseMDPInfo::br_policies)
      .def_readonly("on_policy_values",
                    &TabularBestResponseMDPInfo::on_policy_values)
      .def_readonly("deviation_incentives",
                    &TabularBestResponseMDPInfo::deviation_incentives)
      .def_readonly("nash_conv", &TabularBestResponseMDPInfo::nash_conv)
      .def_readonly("exploitability",
                    &TabularBestResponseMDPInfo::exploitability);
  py::class_<TabularBestResponseMDP>(m, "TabularBestResponseMDP")
      .def(py::init<const open_spiel::Game&, const open_spiel::Policy&>())
      .def("compute_best_responses",  // Takes no arguments.
           &TabularBestResponseMDP::ComputeBestResponses)
      .def("compute_best_response",  // Takes one argument: Player max_player.
           &TabularBestResponseMDP::ComputeBestResponse, py::arg("max_player"))
      .def("nash_conv", &TabularBestResponseMDP::NashConv)
      .def("exploitability", &TabularBestResponseMDP::Exploitability);
  m.def(
      "expected_returns",
      py::overload_cast<const State&, const std::vector<const Policy*>&, int,
                        bool, float>(&open_spiel::algorithms::ExpectedReturns),
      "Computes the undiscounted expected returns from a depth-limited "
      "search.",
      py::arg("state"), py::arg("policies"), py::arg("depth_limit"),
      py::arg("use_infostate_get_policy"), py::arg("prob_cut_threshold") = 0.0);
  m.def("expected_returns",
        py::overload_cast<const State&, const Policy&, int, bool, float>(
            &open_spiel::algorithms::ExpectedReturns),
        "Computes the undiscounted expected returns from a depth-limited "
        "search.",
        py::arg("state"), py::arg("joint_policy"), py::arg("depth_limit"),
        py::arg("use_infostate_get_policy"),
        py::arg("prob_cut_threshold") = 0.0);
  m.def("expected_returns_of_deterministic_policies_from_seeds",
        py::overload_cast<const State&, const std::vector<int>&>(
            &open_spiel::algorithms::
                ExpectedReturnsOfDeterministicPoliciesFromSeeds),
        py::call_guard<py::gil_scoped_release>(),
        "Computes the undiscounted expected returns from seeds.",
        py::arg("state"), py::arg("policy_seeds"));
  m.def("expected_returns_of_deterministic_policies_from_seeds",
        py::overload_cast<const State&, const std::vector<int>&,
                          const std::vector<const Policy*>&>(
            &open_spiel::algorithms::
                ExpectedReturnsOfDeterministicPoliciesFromSeeds),
        py::call_guard<py::gil_scoped_release>(),
        "Computes the expected returns from seeds and policies.",
        py::arg("state"), py::arg("policy_seeds"), py::arg("policies"));
  m.def(
      "exploitability",
      [](std::shared_ptr<const Game> game, const Policy& policy) {
        return Exploitability(*game, policy);
      },
      "Returns the sum of the utility that a best responder wins when when "
      "playing against 1) the player 0 policy contained in `policy` and 2) "
      "the player 1 policy contained in `policy`."
      "This only works for two player, zero- or constant-sum sequential "
      "games, and raises a SpielFatalError if an incompatible game is passed "
      "to it.");
  m.def(
      "exploitability",
      [](std::shared_ptr<const Game> game,
         const std::unordered_map<std::string, ActionsAndProbs>& policy) {
        return Exploitability(*game, policy);
      },
      "Returns the sum of the utility that a best responder wins when when "
      "playing against 1) the player 0 policy contained in `policy` and 2) "
      "the player 1 policy contained in `policy`."
      "This only works for two player, zero- or constant-sum sequential "
      "games, and raises a SpielFatalError if an incompatible game is passed "
      "to it.");
  m.def(
      "nash_conv",
      [](std::shared_ptr<const Game> game, const Policy& policy,
         bool use_state_get_policy) {
        return NashConv(*game, policy, use_state_get_policy);
      },
      "Calculates a measure of how far the given policy is from a Nash "
      "equilibrium by returning the sum of the improvements in the value "
      "that each player could obtain by unilaterally changing their strategy "
      "while the opposing player maintains their current strategy (which "
      "for a Nash equilibrium, this value is 0). The third parameter is to "
      "indicate whether to use the Policy::GetStatePolicy(const State&) "
      "instead of Policy::GetStatePolicy(const std::string& info_state) for "
      "computation of the on-policy expected values.",
      py::arg("game"), py::arg("policy"),
      py::arg("use_state_get_policy") = false);
  m.def(
      "nash_conv",
      [](std::shared_ptr<const Game> game,
         const std::unordered_map<std::string, ActionsAndProbs>& policy) {
        return NashConv(*game, policy);
      },
      "Calculates a measure of how far the given policy is from a Nash "
      "equilibrium by returning the sum of the improvements in the value "
      "that each player could obtain by unilaterally changing their strategy "
      "while the opposing player maintains their current strategy (which "
      "for a Nash equilibrium, this value is 0).");
  m.def("num_deterministic_policies",
        &open_spiel::algorithms::NumDeterministicPolicies,
        "Returns number of determinstic policies in this game for a player, "
        "or -1 if there are more than 2^64 - 1 policies.");
  m.def("to_joint_tabular_policy", &open_spiel::ToJointTabularPolicy,
        "Returns a merged tabular policy from a list of TabularPolicy. The "
        "second argument is a bool which, if true, checks that there is no "
        "overlap among all the policies.");
}
References open_spiel::algorithms::CFRSolverBase::AveragePolicy(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::AveragePolicy(), open_spiel::algorithms::OutcomeSamplingMCCFRSolver::AveragePolicy(), open_spiel::algorithms::CFRSolverBase::CurrentPolicy(), open_spiel::algorithms::DeserializeCFRBRSolver(), open_spiel::algorithms::DeserializeCFRPlusSolver(), open_spiel::algorithms::DeserializeCFRSolver(), open_spiel::algorithms::DeserializeExternalSamplingMCCFRSolver(), open_spiel::algorithms::DeserializeOutcomeSamplingMCCFRSolver(), open_spiel::algorithms::CFRSolverBase::EvaluateAndUpdatePolicy(), open_spiel::algorithms::ExpectedReturns(), GetFlatDirichletPolicy(), GetRandomDeterministicPolicy(), GetRandomPolicy(), open_spiel::PartialTabularPolicy::GetStatePolicy(), open_spiel::Policy::GetStatePolicy(), open_spiel::PreferredActionPolicy::GetStatePolicy(), open_spiel::TabularPolicy::GetStatePolicy(), open_spiel::UniformPolicy::GetStatePolicy(), open_spiel::Policy::GetStatePolicyAsMap(), open_spiel::Policy::GetStatePolicyAsParallelVectors(), GetUniformPolicy(), open_spiel::algorithms::OutcomeSamplingMCCFRSolver::kDefaultEpsilon, open_spiel::algorithms::kFull, open_spiel::algorithms::kSimple, open_spiel::algorithms::NumDeterministicPolicies(), player, open_spiel::TabularPolicy::PolicyTable(), precision, open_spiel::algorithms::CFRSolverBase::Serialize(), open_spiel::Policy::Serialize(), open_spiel::TabularPolicy::SetProb(), open_spiel::TabularPolicy::SetStatePolicy(), open_spiel::TabularPolicy::size(), state, open_spiel::algorithms::CFRSolverBase::TabularAveragePolicy(), open_spiel::algorithms::CFRSolverBase::TabularCurrentPolicy(), ToJointTabularPolicy(), and open_spiel::TabularPolicy::ToString().
init_pyspiel_utils() [1/2]
void open_spiel::init_pyspiel_utils (::pybind11::module & m)
init_pyspiel_utils() [2/2]
void open_spiel::init_pyspiel_utils (py::module & m)
Definition at line 23 of file utils.cc.
{
  // read_contents_from_file(string filename, string mode)
  m.def("read_contents_from_file", file::ReadContentsFromFile,
        "Read the entire contents of a file.");
  // write_contents_to_file(string filename, string mode, string contents)
  m.def("write_contents_to_file", open_spiel::file::WriteContentsToFile,
        "Write the contents of the string to the specified filename.");
}
References open_spiel::file::ReadContentsFromFile(), and open_spiel::file::WriteContentsToFile().
init_pyspiel_xinxin()
void open_spiel::init_pyspiel_xinxin (::pybind11::module & m)
Definition at line 23 of file xinxin_pybind11.cc.
{
  m.def("make_xinxin_bot", open_spiel::hearts::MakeXinxinBot, py::arg("params"),
        py::arg("uct_num_runs") = 50, py::arg("uct_c_val") = 0.4,
        py::arg("iimc_num_worlds") = 20, py::arg("use_threads") = true,
        "Make the XinXin bot.");
}
References open_spiel::hearts::MakeXinxinBot().
IsBotRegistered()
bool open_spiel::IsBotRegistered (const std::string & bot_name)
Definition at line 347 of file spiel_bots.cc.
{
  return BotRegisterer::IsBotRegistered(bot_name);
}
References open_spiel::BotRegisterer::IsBotRegistered().
Referenced by init_pyspiel_bots().
IsGameRegistered()
bool open_spiel::IsGameRegistered (const std::string & short_name)
Definition at line 193 of file spiel.cc.
{
  return GameRegisterer::IsValidName(short_name);
}
References open_spiel::GameRegisterer::IsValidName().
IsParameterSpecified()
bool open_spiel::IsParameterSpecified (const GameParameters & table, const std::string & key) inline
Definition at line 202 of file game_parameters.h.
{
  return table.find(key) != table.end();
}
References key.
Referenced by open_spiel::liars_dice::LiarsDiceGame::LiarsDiceGame().
LoadBot() [1/2]
std::unique_ptr< Bot > open_spiel::LoadBot (const std::string & bot_name, const std::shared_ptr< const Game > & game, Player player_id)
Definition at line 351 of file spiel_bots.cc.
{
  GameParameters params = GameParametersFromString(bot_name);
  // We use the "name" parameter, as that is the "short_name", which is what we
  // want. Otherwise, this will use the "long name", which includes the config.
  // e.g. if the bot_name is "my_bot(parameter=value)", then we want the
  // bot_name here to be "my_bot", not "my_bot(parameter=value)".
  return LoadBot(params["name"].string_value(), game, player_id, params);
}
References GameParametersFromString(), and LoadBot().
Referenced by init_pyspiel_bots(), and LoadBot().
LoadBot() [2/2]
std::unique_ptr< Bot > open_spiel::LoadBot (const std::string & bot_name, const std::shared_ptr< const Game > & game, Player player_id, const GameParameters & params)
Definition at line 363 of file spiel_bots.cc.
{
  std::unique_ptr<Bot> result =
      BotRegisterer::CreateByName(bot_name, game, player_id, params);
  if (result == nullptr) {
    SpielFatalError(absl::StrCat("Unable to create bot: ", bot_name));
  }
  return result;
}
References open_spiel::BotRegisterer::CreateByName(), SpielFatalError(), and absl::StrCat().
LoadGame() [1/3]
std::shared_ptr< const Game > open_spiel::LoadGame (const std::string & game_string)
Definition at line 227 of file spiel.cc.
{
  return LoadGame(GameParametersFromString(game_string));
}
References GameParametersFromString(), and LoadGame().
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), open_spiel::coin_game::BasicCoinGameTests(), open_spiel::tarok::BasicGameTests(), BuildStateFromHistoryString(), CreateRepeatedGame(), define_julia_module(), DeserializeGame(), Factory(), open_spiel::gamut::GamutGenerator::GenerateGame(), open_spiel::coin_game::GetAllStatesTest(), init_pyspiel_games_bridge(), init_pyspiel_games_euchre(), init_pyspiel_games_gin_rummy(), LoadGame(), LoadGame(), LoadGameAsTurnBased(), LoadGameAsTurnBased(), LoadGameFromParameters(), open_spiel::testing::LoadGameTest(), open_spiel::algorithms::LoadMatrixGame(), open_spiel::algorithms::LoadTensorGame(), open_spiel::universal_poker::LoadUniversalPokerGameFromACPCGamedef(), main(), open_spiel::universal_poker::MakeRandomSubgame(), open_spiel::tarok::NewTarokGame(), RandomSimBenchmark(), open_spiel::uci::RandomUciBot(), SolveCatch(), SolveTicTacToe(), SolveTicTacToeEligibilityTraces(), and WriteAndLoadGame().
LoadGame() [2/3]
std::shared_ptr< const Game > open_spiel::LoadGame (const std::string & short_name, const GameParameters & params)
Definition at line 231 of file spiel.cc.
{
  std::shared_ptr<const Game> result =
      GameRegisterer::CreateByName(short_name, params);
  if (result == nullptr) {
    SpielFatalError(absl::StrCat("Unable to create game: ", short_name));
  }
  return result;
}
References open_spiel::GameRegisterer::CreateByName(), SpielFatalError(), and absl::StrCat().
LoadGame() [3/3]
std::shared_ptr< const Game > open_spiel::LoadGame (GameParameters params)
Definition at line 241 of file spiel.cc.
{
  auto it = params.find("name");
  if (it == params.end()) {
    SpielFatalError(absl::StrCat("No 'name' parameter in params: ",
                                 GameParametersToString(params)));
  }
  std::string name = it->second.string_value();
  params.erase(it);
  std::shared_ptr<const Game> result =
      GameRegisterer::CreateByName(name, params);
  if (result == nullptr) {
    SpielFatalError(absl::StrCat("Unable to create game: ", name));
  }
  LogUsage();
  return result;
}
References open_spiel::GameRegisterer::CreateByName(), GameParametersToString(), LogUsage(), name, SpielFatalError(), and absl::StrCat().
LoadGameAsTurnBased() [1/2]
std::shared_ptr< const Game > open_spiel::LoadGameAsTurnBased (const std::string & name)
Definition at line 288 of file turn_based_simultaneous_game.cc.
{
  auto game = LoadGame(name);
  if (game->GetType().dynamics == GameType::Dynamics::kSimultaneous) {
    return ConvertToTurnBased(*game);
  } else {
    return game;
  }
}
References ConvertToTurnBased(), open_spiel::GameType::kSimultaneous, LoadGame(), and name.
Referenced by define_julia_module(), and init_pyspiel_game_transforms().
LoadGameAsTurnBased() [2/2]
std::shared_ptr< const Game > open_spiel::LoadGameAsTurnBased (const std::string & name, const GameParameters & params)
Definition at line 297 of file turn_based_simultaneous_game.cc.
{
  auto game = LoadGame(name, params);
  if (game->GetType().dynamics == GameType::Dynamics::kSimultaneous) {
    return ConvertToTurnBased(*game);
  } else {
    return game;
  }
}
References ConvertToTurnBased(), open_spiel::GameType::kSimultaneous, LoadGame(), and name.
LogUsage()
void open_spiel::LogUsage ()
Definition at line 20 of file usage_logging.cc.
                {
}
Referenced by LoadGame().
MakeFixedActionPreferenceBot()
std::unique_ptr< Bot > open_spiel::MakeFixedActionPreferenceBot (Player player_id, const std::vector< Action > & actions)
Definition at line 240 of file spiel_bots.cc.
{
  return std::make_unique<FixedActionPreferenceBot>(player_id, actions);
}
MakePolicyBot() [1/2]
std::unique_ptr< Bot > open_spiel::MakePolicyBot (const Game & game, Player player_id, int seed, std::shared_ptr< Policy > policy)
Definition at line 234 of file spiel_bots.cc.
{
  return MakePolicyBot(seed, std::move(policy));
}
References MakePolicyBot().
MakePolicyBot() [2/2]
std::unique_ptr< Bot > open_spiel::MakePolicyBot (int seed, std::shared_ptr< Policy > policy)
Definition at line 231 of file spiel_bots.cc.
{
  return std::make_unique<PolicyBot>(seed, std::move(policy));
}
Referenced by init_pyspiel_bots(), and MakePolicyBot().
MakeSingleTensorObserver()
std::shared_ptr< Observer > open_spiel::MakeSingleTensorObserver (const Game & game, absl::optional< IIGObservationType > iig_obs_type, const GameParameters & params)
Definition at line 347 of file observer.cc.
{
  return std::shared_ptr<Observer>(game.MakeBuiltInObserver(iig_obs_type));
}
Referenced by open_spiel::RegisterSingleTensorObserver::RegisterSingleTensorObserver().
MakeStatefulRandomBot()
std::unique_ptr< Bot > open_spiel::MakeStatefulRandomBot (const Game & game, Player player_id, int seed)
Definition at line 277 of file spiel_bots.cc.
{
  return std::make_unique<StatefulRandomBot>(game, player_id, seed);
}
Referenced by init_pyspiel_bots().
MakeUniformRandomBot()
std::unique_ptr< Bot > open_spiel::MakeUniformRandomBot (Player player_id, int seed)
Definition at line 201 of file spiel_bots.cc.
{
  return std::make_unique<UniformRandomBot>(player_id, seed);
}
Referenced by init_pyspiel_bots(), InitBot(), InitBot(), and InitBot().
Near() [1/2]
template<typename T > bool open_spiel::Near (T a, T b)
Definition at line 185 of file spiel_utils.h.
                    {
  static_assert(std::is_floating_point<T>::value,
                "Near() is only for floating point args.");
  return fabs(a - b) <= FloatingPointDefaultTolerance();
}
References a, b, and FloatingPointDefaultTolerance().
Referenced by open_spiel::algorithms::CorrDevBuilder::AddMixedJointPolicy(), AllNear(), open_spiel::algorithms::CheckBeliefs(), open_spiel::testing::CheckReturnsSum(), open_spiel::algorithms::CorrDevBuilder::GetCorrelationDevice(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::GetLatestPolicy(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::GetMarginalJointPolicy(), open_spiel::testing::RandomSimulation(), and StatePoliciesEqual().
Near() [2/2]
template<typename T > bool open_spiel::Near (T a, T b, T epsilon)
Definition at line 193 of file spiel_utils.h.
{
  static_assert(std::is_floating_point<T>::value,
                "Near() is only for floating point args.");
  return fabs(a - b) <= epsilon;
}
References a, and b.
Negative()
std::vector< double > open_spiel::Negative (std::vector< double > && vector) inline
Definition at line 29 of file misere.h.
{
  std::vector<double> neg = std::move(vector);
  for (auto& item : neg) item = -item;
  return neg;
}
Referenced by open_spiel::MisereState::Returns(), and open_spiel::MisereState::Rewards().
NextPlayerRoundRobin()
int open_spiel::NextPlayerRoundRobin (Player player, int nplayers)
Definition at line 32 of file spiel_utils.cc.
{
  if (player + 1 < nplayers) {
    return player + 1;
  } else {
    return 0;
  }
}
References player.
Referenced by open_spiel::breakthrough::BreakthroughState::DoApplyAction(), open_spiel::liars_dice::LiarsDiceState::DoApplyAction(), open_spiel::pig::PigState::DoApplyAction(), open_spiel::trade_comm::TradeCommState::DoApplyAction(), and open_spiel::ultimate_tic_tac_toe::UltimateTTTState::DoApplyAction().
NextPowerSetMask()
bool open_spiel::NextPowerSetMask (std::vector< bool > * bs)
Definition at line 26 of file combinatorics.cc.
{
  for (std::size_t i = 0; i != bs->size(); ++i) {
    (*bs)[i] = !(*bs)[i];
    if ((*bs)[i]) {
      return true;
    }
  }
  return false;  // overflow
}
References i.
Referenced by PowerSet().
Normalize()
void open_spiel::Normalize (absl::Span< double > weights)
Definition at line 143 of file spiel_utils.cc.
{
  SPIEL_CHECK_FALSE(weights.empty());
  const double normalizer = absl::c_accumulate(weights, 0.);
  SPIEL_CHECK_FALSE(std::isnan(normalizer));
  const double uniform_prob = 1.0 / weights.size();
  absl::c_for_each(weights, [&](double& w) {
    w = (normalizer == 0.0 ? uniform_prob : w / normalizer);
  });
}
References absl::c_accumulate(), absl::c_for_each(), absl::Span< T >::empty(), absl::Span< T >::size(), and SPIEL_CHECK_FALSE.
Referenced by open_spiel::algorithms::GetStateDistribution(), and open_spiel::algorithms::UpdateIncrementalStateDistribution().
NormalizePolicy()
void open_spiel::NormalizePolicy (ActionsAndProbs * policy)
Definition at line 264 of file spiel.cc.
{
  const double sum = absl::c_accumulate(
      *policy, 0.0, [](double a, auto& b) { return a + b.second; });
  absl::c_for_each(*policy, [sum](auto& o) { o.second /= sum; });
}
References a, b, absl::c_accumulate(), absl::c_for_each(), and o.
Referenced by open_spiel::universal_poker::UniformRestrictedActions::GetStatePolicy(), and open_spiel::algorithms::torch_az::PlayGame().
ObserverTensorShape()
std::vector< int > open_spiel::ObserverTensorShape (const State & state, const Observer & observer)
Definition at line 380 of file observer.cc.
{
  TrackingVectorAllocator allocator;
  observer.WriteTensor(state, /*player=*/0, &allocator);
  if (allocator.tensors_info().size() == 1) {
    return allocator.tensors_info().front().vector_shape();
  } else {
    return {static_cast<int>(allocator.data().size())};
  }
}
References open_spiel::TrackingVectorAllocator::data(), state, open_spiel::TrackingVectorAllocator::tensors_info(), and open_spiel::Observer::WriteTensor().
Referenced by open_spiel::kriegspiel::KriegspielGame::ObservationTensorShape().
operator<<() [1/17]
std::ostream & open_spiel::operator<< (std::ostream & os, const ActionObservationHistory & aoh)
Definition at line 318 of file observation_history.cc.
{
  return os << aoh.ToString();
}
References open_spiel::ActionObservationHistory::ToString().
operator<<() [2/17]
std::ostream & open_spiel::operator<< (std::ostream & os, const PublicObservationHistory & poh)
Definition at line 323 of file observation_history.cc.
{
  return os << poh.ToString();
}
References open_spiel::PublicObservationHistory::ToString().
operator<<() [3/17]
std::ostream & open_spiel::operator<< (std::ostream & os, const State::PlayerAction & action)
Definition at line 822 of file spiel.cc.
{
  os << absl::StreamFormat("PlayerAction(player=%i,action=%i)", action.player,
                           action.action);
  return os;
}
References action, and absl::StreamFormat().
operator<<() [4/17]
std::ostream & open_spiel::operator<< (std::ostream & os, const StateType & type)
Definition at line 96 of file spiel.cc.
{
  switch (type) {
    case StateType::kMeanField: {
      os << "MEAN_FIELD";
      break;
    }
    case StateType::kChance: {
      os << "CHANCE";
      break;
    }
    case StateType::kDecision: {
      os << "DECISION";
      break;
    }
    case StateType::kTerminal: {
      os << "TERMINAL";
      break;
    }
  }
  return os;
}
References kChance, kDecision, kMeanField, and kTerminal.
operator<<() [5/17]
template<typename T > std::ostream & open_spiel::operator<< (std::ostream & stream, absl::Span< T > v)
Definition at line 65 of file spiel_utils.h.
{
  stream << "[";
  for (const auto& element : v) {
    stream << element << " ";
  }
  stream << "]";
  return stream;
}
operator<<() [6/17]
std::ostream & open_spiel::operator<< (std::ostream & stream, const absl::nullopt_t & v)
Definition at line 139 of file spiel_utils.cc.
{
  return stream << "(nullopt)";
}
operator<<() [7/17]
template<typename T > std::ostream & open_spiel::operator<< (std::ostream & stream, const absl::optional< T > & v)
Definition at line 91 of file spiel_utils.h.
{
  return stream << *v;
}
operator<<() [8/17]
std::ostream & open_spiel::operator<< (std::ostream & stream, const State & state)
Definition at line 552 of file spiel.cc.
{
  return stream << state.ToString();
}
References state.
operator<<() [9/17]
template<typename T , std::size_t N> std::ostream & open_spiel::operator<< (std::ostream & stream, const std::array< T, N > & v)
Definition at line 78 of file spiel_utils.h.
{
  stream << "[";
  for (const auto& element : v) {
    stream << element << " ";
  }
  stream << "]";
  return stream;
}
operator<<() [10/17]
template<typename T , typename U > std::ostream & open_spiel::operator<< (std::ostream & stream, const std::pair< T, U > & v)
Definition at line 95 of file spiel_utils.h.
{
  stream << "(" << v.first << "," << v.second << ")";
  return stream;
}
operator<<() [11/17]
template<typename T > std::ostream & open_spiel::operator<< (std::ostream & stream, const std::unique_ptr< T > & v)
Definition at line 87 of file spiel_utils.h.
{
  return stream << *v;
}
operator<<() [12/17]
template<typename T > std::ostream & open_spiel::operator<< (std::ostream & stream, const std::vector< T > & v)
Definition at line 74 of file spiel_utils.h.
{
  return stream << absl::MakeSpan(v);
}
References absl::MakeSpan().
operator<<() [13/17]
std::ostream & open_spiel::operator<< (std::ostream & stream, GameType::ChanceMode value)
Definition at line 539 of file spiel.cc.
{
  switch (value) {
    case GameType::ChanceMode::kDeterministic:
      return stream << "Deterministic";
    case GameType::ChanceMode::kExplicitStochastic:
      return stream << "ExplicitStochastic";
    case GameType::ChanceMode::kSampledStochastic:
      return stream << "SampledStochastic";
    default:
      SpielFatalError("Unknown mode.");
  }
}
References open_spiel::GameType::kDeterministic, open_spiel::GameType::kExplicitStochastic, open_spiel::GameType::kSampledStochastic, and SpielFatalError().
operator<<() [14/17]
std::ostream & open_spiel::operator<< (std::ostream & stream, GameType::Dynamics value)
Definition at line 511 of file spiel.cc.
{
  switch (value) {
    case GameType::Dynamics::kSimultaneous:
      return stream << "Simultaneous";
    case GameType::Dynamics::kSequential:
      return stream << "Sequential";
    case GameType::Dynamics::kMeanField:
      return stream << "MeanField";
    default:
      SpielFatalError(absl::StrCat("Unknown dynamics: ", value));
  }
}
References open_spiel::GameType::kMeanField, open_spiel::GameType::kSequential, open_spiel::GameType::kSimultaneous, SpielFatalError(), and absl::StrCat().
operator<<() [15/17]
std::ostream & open_spiel::operator<< (std::ostream & stream, GameType::Information value)
Definition at line 571 of file spiel.cc.
{
  switch (value) {
    case GameType::Information::kOneShot:
      return stream << "OneShot";
    case GameType::Information::kPerfectInformation:
      return stream << "PerfectInformation";
    case GameType::Information::kImperfectInformation:
      return stream << "ImperfectInformation";
    default:
      SpielFatalError("Unknown value.");
  }
}
References open_spiel::GameType::kImperfectInformation, open_spiel::GameType::kOneShot, open_spiel::GameType::kPerfectInformation, and SpielFatalError().
operator<<() [16/17]
std::ostream & open_spiel::operator<< (std::ostream & stream, GameType::RewardModel value)
Definition at line 631 of file spiel.cc.
{
  switch (value) {
    case GameType::RewardModel::kRewards:
      return stream << "Rewards";
    case GameType::RewardModel::kTerminal:
      return stream << "Terminal";
    default:
      SpielFatalError("Unknown value.");
  }
}
References open_spiel::GameType::kRewards, open_spiel::GameType::kTerminal, and SpielFatalError().
operator<<() [17/17]
std::ostream & open_spiel::operator<< (std::ostream & stream, GameType::Utility value)
Definition at line 599 of file spiel.cc.
{
  switch (value) {
    case GameType::Utility::kZeroSum:
      return stream << "ZeroSum";
    case GameType::Utility::kConstantSum:
      return stream << "ConstantSum";
    case GameType::Utility::kGeneralSum:
      return stream << "GeneralSum";
    case GameType::Utility::kIdentical:
      return stream << "Identical";
    default:
      SpielFatalError("Unknown value.");
  }
}
References open_spiel::GameType::kConstantSum, open_spiel::GameType::kGeneralSum, open_spiel::GameType::kIdentical, open_spiel::GameType::kZeroSum, and SpielFatalError().
operator>>() [1/5]
std::istream & open_spiel::operator>> (std::istream & stream, GameType::ChanceMode & var)
Definition at line 556 of file spiel.cc.
{
  std::string str;
  stream >> str;
  if (str == "Deterministic") {
    var = GameType::ChanceMode::kDeterministic;
  } else if (str == "ExplicitStochastic") {
    var = GameType::ChanceMode::kExplicitStochastic;
  } else if (str == "SampledStochastic") {
    var = GameType::ChanceMode::kSampledStochastic;
  } else {
    SpielFatalError(absl::StrCat("Unknown chance mode ", str, "."));
  }
  return stream;
}
References open_spiel::GameType::kDeterministic, open_spiel::GameType::kExplicitStochastic, open_spiel::GameType::kSampledStochastic, SpielFatalError(), and absl::StrCat().
operator>>() [2/5]
std::istream & open_spiel::operator>> (std::istream & stream, GameType::Dynamics & var)
Definition at line 524 of file spiel.cc.
{
  std::string str;
  stream >> str;
  if (str == "Simultaneous") {
    var = GameType::Dynamics::kSimultaneous;
  } else if (str == "Sequential") {
    var = GameType::Dynamics::kSequential;
  } else if (str == "MeanField") {
    var = GameType::Dynamics::kMeanField;
  } else {
    SpielFatalError(absl::StrCat("Unknown dynamics ", str, "."));
  }
  return stream;
}
References open_spiel::GameType::kMeanField, open_spiel::GameType::kSequential, open_spiel::GameType::kSimultaneous, SpielFatalError(), and absl::StrCat().
operator>>() [3/5]
std::istream & open_spiel::operator>> (std::istream & stream, GameType::Information & var)
Definition at line 584 of file spiel.cc.
{
  std::string str;
  stream >> str;
  if (str == "OneShot") {
    var = GameType::Information::kOneShot;
  } else if (str == "PerfectInformation") {
    var = GameType::Information::kPerfectInformation;
  } else if (str == "ImperfectInformation") {
    var = GameType::Information::kImperfectInformation;
  } else {
    SpielFatalError(absl::StrCat("Unknown information ", str, "."));
  }
  return stream;
}
References open_spiel::GameType::kImperfectInformation, open_spiel::GameType::kOneShot, open_spiel::GameType::kPerfectInformation, SpielFatalError(), and absl::StrCat().
operator>>() [4/5]
std::istream & open_spiel::operator>> (std::istream & stream, GameType::RewardModel & var)
Definition at line 642 of file spiel.cc.
{
  std::string str;
  stream >> str;
  if (str == "Rewards") {
    var = GameType::RewardModel::kRewards;
  } else if (str == "Terminal") {
    var = GameType::RewardModel::kTerminal;
  } else {
    SpielFatalError(absl::StrCat("Unknown reward model ", str, "."));
  }
  return stream;
}
References open_spiel::GameType::kRewards, open_spiel::GameType::kTerminal, SpielFatalError(), and absl::StrCat().
operator>>() [5/5]
std::istream & open_spiel::operator>> (std::istream & stream, GameType::Utility & var)
Definition at line 614 of file spiel.cc.
{
  std::string str;
  stream >> str;
  if (str == "ZeroSum") {
    var = GameType::Utility::kZeroSum;
  } else if (str == "ConstantSum") {
    var = GameType::Utility::kConstantSum;
  } else if (str == "GeneralSum") {
    var = GameType::Utility::kGeneralSum;
  } else if (str == "Identical") {
    var = GameType::Utility::kIdentical;
  } else {
    SpielFatalError(absl::StrCat("Unknown utility ", str, "."));
  }
  return stream;
}
References open_spiel::GameType::kConstantSum, open_spiel::GameType::kGeneralSum, open_spiel::GameType::kIdentical, open_spiel::GameType::kZeroSum, SpielFatalError(), and absl::StrCat().
ParameterValue()
template<typename T > T open_spiel::ParameterValue (const GameParameters & params, const std::string & key, absl::optional< T > default_value = absl::nullopt)
Definition at line 208 of file game_parameters.h.
{
  auto iter = params.find(key);
  if (iter == params.end()) {
    if (!default_value.has_value()) {
      SpielFatalError(absl::StrCat("Cannot find parameter and no default "
                                   "value passed for key: ", key));
    }
    return *default_value;
  } else {
    return iter->second.value<T>();
  }
}
References key, SpielFatalError(), and absl::StrCat().
Permutations()
template<typename T > std::vector< std::vector< T > > open_spiel::Permutations (std::vector< T > v)
Definition at line 35 of file combinatorics.h.
{
  std::vector<std::vector<T>> vs;
  int perm_size = 1;
  for (int i = 2; i <= v.size(); ++i) perm_size *= i;
  vs.reserve(perm_size);
  std::sort(v.begin(), v.end());
  do {
    vs.push_back(v);
  } while (std::next_permutation(v.begin(), v.end()));
  return vs;
}
References i.
PowerSet()
template<typename T > std::vector< std::vector< T > > open_spiel::PowerSet (const std::vector< T > & v)
Definition at line 77 of file combinatorics.h.
{
  std::vector<bool> bitset(v.size());
  std::vector<std::vector<T>> vs;
  do {
    std::vector<T> x;
    for (std::size_t i = 0; i != v.size(); ++i) {
      if (bitset[i]) {
        x.push_back(v[i]);
      }
    }
    vs.push_back(x);
  } while (NextPowerSetMask(&bitset));
  return vs;
}
References i, NextPowerSetMask(), and x.
PreviousPlayerRoundRobin()
int open_spiel::PreviousPlayerRoundRobin (Player player, int nplayers)
Definition at line 41 of file spiel_utils.cc.
{
  if (player - 1 >= 0) {
    return player - 1;
  } else {
    return nplayers - 1;
  }
}
References player.
Referenced by open_spiel::breakthrough::BreakthroughState::UndoAction().
PrintPolicy()
std::string open_spiel::PrintPolicy (const ActionsAndProbs & policy)
Definition at line 526 of file policy.cc.
{
  std::string policy_string;
  for (auto [a, p] : policy) {
    absl::StrAppend(&policy_string, absl::StrFormat("(%i, %f), ", a, p));
  }
  return policy_string;
}
References a, absl::StrAppend(), and absl::StrFormat().
ProbabilityDefaultTolerance()
float open_spiel::ProbabilityDefaultTolerance () inline constexpr
Definition at line 139 of file spiel_utils.h.
{ return 1e-9; }
Referenced by open_spiel::algorithms::HistoryNode::AddChild(), open_spiel::algorithms::DecisionNodes(), and open_spiel::algorithms::HistoryNode::GetChild().
PyDict()
py::dict open_spiel::PyDict (const State & state)
Definition at line 295 of file python_games.cc.
{
  py::object obj = py::cast(&state);
  if (py::hasattr(obj, "__dict__")) {
    return obj.attr("__dict__");
  } else {
    return py::dict();
  }
}
References state.
Referenced by open_spiel::PyState::Clone(), and open_spiel::PyState::Serialize().
RandomSimBenchmark()
void open_spiel::RandomSimBenchmark (const std::string & game_def, int num_sims, bool verbose)
Definition at line 120 of file benchmark_game.cc.
{
  std::mt19937 rng;
  std::cout << absl::StrFormat("Benchmark: game: %s, num_sims: %d. ", game_def,
                               num_sims);
  auto game = LoadGame(game_def);
  absl::Time start = absl::Now();
  int num_moves = 0;
  for (int sim = 0; sim < num_sims; ++sim) {
    num_moves += RandomSimulation(&rng, *game, verbose);
  }
  absl::Time end = absl::Now();
  double seconds = absl::ToDoubleSeconds(end - start);
  std::cout << absl::StrFormat(
                   "Finished %d moves in %.1f ms: %.1f sim/s, %.1f moves/s",
                   num_moves, seconds * 1000, num_sims / seconds,
                   num_moves / seconds)
            << std::endl;
}
References LoadGame(), absl::Now(), RandomSimulation(), absl::StrFormat(), and absl::ToDoubleSeconds().
Referenced by main().
RandomSimulation()
int open_spiel::RandomSimulation (std::mt19937 * rng, const Game & game, bool verbose)
Definition at line 32 of file benchmark_game.cc.
{
  std::unique_ptr<State> state = game.NewInitialState();
  if (verbose) {
    std::cout << "Initial state:" << std::endl
              << "State:" << std::endl
              << state->ToString() << std::endl;
  }
  bool provides_info_state_tensor =
      game.GetType().provides_information_state_tensor;
  bool provides_observations_tensor =
      game.GetType().provides_observation_tensor;
  std::vector<float> obs;
  if (provides_info_state_tensor) {
    obs = std::vector<float>(game.InformationStateTensorSize());
  } else if (provides_observations_tensor) {
    obs = std::vector<float>(game.ObservationTensorSize());
  }
  int game_length = 0;
  while (!state->IsTerminal()) {
    if (provides_info_state_tensor && state->CurrentPlayer() >= 0) {
      state->InformationStateTensor(state->CurrentPlayer(),
                                    absl::MakeSpan(obs));
    } else if (provides_observations_tensor && state->CurrentPlayer() >= 0) {
      state->ObservationTensor(state->CurrentPlayer(), absl::MakeSpan(obs));
    }
    ++game_length;
    if (state->IsChanceNode()) {
      std::vector<std::pair<Action, double>> outcomes = state->ChanceOutcomes();
      Action action;
      if (game.GetType().chance_mode ==
          GameType::ChanceMode::kSampledStochastic) {
        action = outcomes.front().first;
      } else {
        // Explicit chance node; sample one according to underlying
        // distribution.
        action = SampleAction(outcomes, *rng).first;
      }
      if (verbose) {
        std::cout << "Sampled outcome: "
                  << state->ActionToString(kChancePlayerId, action)
                  << std::endl;
      }
      state->ApplyAction(action);
    } else if (state->CurrentPlayer() == kSimultaneousPlayerId) {
      // Sample an action for each player
      std::vector<Action> joint_action;
      for (int p = 0; p < game.NumPlayers(); p++) {
        std::vector<Action> actions;
        actions = state->LegalActions(p);
        Action action = 0;
        if (!actions.empty()) {
          std::uniform_int_distribution<int> dis(0, actions.size() - 1);
          action = actions[dis(*rng)];
        }
        joint_action.push_back(action);
        if (verbose) {
          std::cout << "Player " << p
                    << " chose action:" << state->ActionToString(p, action)
                    << std::endl;
        }
      }
      state->ApplyActions(joint_action);
    } else {
      // Sample an action uniformly.
      std::vector<Action> actions = state->LegalActions();
      std::uniform_int_distribution<int> dis(0, actions.size() - 1);
      Action action = actions[dis(*rng)];
      if (verbose) {
        int p = state->CurrentPlayer();
        std::cout << "Player " << p
                  << " chose action: " << state->ActionToString(p, action)
                  << std::endl;
      }
      state->ApplyAction(action);
    }
    if (verbose) {
      std::cout << "State: " << std::endl << state->ToString() << std::endl;
      std::cout << "Observation: " << obs << std::endl;
    }
  }
  return game_length;
}
References action, kChancePlayerId, open_spiel::GameType::kSampledStochastic, kSimultaneousPlayerId, absl::MakeSpan(), SampleAction(), and state.
Referenced by RandomSimBenchmark().
RankActionMixedBase()
Action open_spiel::RankActionMixedBase (const std::vector< int > & bases, const std::vector< int > & digits)
Definition at line 50 of file spiel_utils.cc.
{
  SPIEL_CHECK_EQ(bases.size(), digits.size());
  SPIEL_CHECK_GT(digits.size(), 0);
  Action action = 0;
  int one_plus_max = 1;
  for (int i = digits.size() - 1; i >= 0; --i) {
    SPIEL_CHECK_GE(digits[i], 0);
    SPIEL_CHECK_LT(digits[i], bases[i]);
    SPIEL_CHECK_GT(bases[i], 1);
    action += digits[i] * one_plus_max;
    one_plus_max *= bases[i];
    SPIEL_CHECK_LT(action, one_plus_max);
  }
  return action;
}
References action, i, SPIEL_CHECK_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_GT, and SPIEL_CHECK_LT.
Referenced by open_spiel::checkers::CheckersState::CheckersActionToSpielAction(), open_spiel::breakthrough::BreakthroughState::LegalActions(), and open_spiel::clobber::ClobberState::LegalActions().
REGISTER_SPIEL_GAME()
open_spiel::REGISTER_SPIEL_GAME (kGameType , Factory)
RegisteredBots()
std::vector< std::string > open_spiel::RegisteredBots ()
Definition at line 339 of file spiel_bots.cc.
{
  return BotRegisterer::RegisteredBots();
}
References open_spiel::BotRegisterer::RegisteredBots().
Referenced by init_pyspiel_bots().
RegisteredGames()
std::vector< std::string > open_spiel::RegisteredGames ()
Definition at line 197 of file spiel.cc.
{
  return GameRegisterer::RegisteredNames();
}
References open_spiel::GameRegisterer::RegisteredNames().
Referenced by main().
RegisteredGameTypes()
std::vector< GameType > open_spiel::RegisteredGameTypes ()
Definition at line 201 of file spiel.cc.
{
  return GameRegisterer::RegisteredGames();
}
References open_spiel::GameRegisterer::RegisteredGames().
RegisterPyGame()
void open_spiel::RegisterPyGame (const GameType & game_type, py::function creator)
Definition at line 160 of file python_games.cc.
{
  GameRegisterer::RegisterGame(
      game_type, [game_type, creator](const GameParameters& game_parameters) {
        py::dict params = py::cast(game_parameters);
        for (const auto& [k, v] : game_type.parameter_specification) {
          if (game_parameters.count(k) == 0) {
            params[pybind11::str(k)] = v;
          }
        }
        auto py_game = creator(params);
        return py::cast<std::shared_ptr<Game>>(py_game);
      });
}
References open_spiel::GameType::parameter_specification, and open_spiel::GameRegisterer::RegisterGame().
RunPython() [1/2]
bool open_spiel::RunPython (const std::string & module, const std::vector< std::string > & args)
Definition at line 31 of file run_python.cc.
{
  return RunPython(kDefaultPythonCommand, module, args);
}
References kDefaultPythonCommand, and RunPython().
RunPython() [2/2]
bool open_spiel::RunPython (const std::string & python_command, const std::string & module, const std::vector< std::string > & args)
Definition at line 22 of file run_python.cc.
{
  // If this fails, make sure your PYTHONPATH environment variable is correct.
  return 0 == std::system(absl::StrCat(
      python_command, " -m ", module, " ", absl::StrJoin(args, " ")).c_str());
}
References absl::StrCat(), and absl::StrJoin().
Referenced by RunPython().
SampleAction() [1/2]
std::pair< Action, double > open_spiel::SampleAction (const ActionsAndProbs & outcomes, absl::BitGenRef rng)
Definition at line 270 of file spiel.cc.
{
  return SampleAction(outcomes, absl::Uniform(rng, 0.0, 1.0));
}
References SampleAction(), and absl::Uniform().
Referenced by open_spiel::algorithms::CorrDevBuilder::AddSampledJointPolicy(), open_spiel::algorithms::RandomRolloutEvaluator::Evaluate(), EvaluateBots(), open_spiel::algorithms::OOSAlgorithm::IncrementallyBuildTree(), main(), open_spiel::algorithms::torch_az::PlayGame(), PlayGame(), PlayGame(), RandomSimulation(), open_spiel::testing::RandomSimulation(), open_spiel::algorithms::RecordTrajectory(), open_spiel::hearts::HeartsState::ResampleFromInfostate(), open_spiel::kuhn_poker::KuhnState::ResampleFromInfostate(), open_spiel::leduc_poker::LeducState::ResampleFromInfostate(), open_spiel::oh_hell::OhHellState::ResampleFromInfostate(), open_spiel::algorithms::torch_dqn::RunEpisodes(), SampleAction(), open_spiel::algorithms::SearchNode::SampleFromPrior(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::SBRIteration(), open_spiel::algorithms::OOSAlgorithm::SelectAction(), open_spiel::algorithms::ISMCTSBot::Step(), open_spiel::algorithms::ISMCTSBot::StepWithPolicy(), open_spiel::testing::TestPoliciesCanPlay(), and open_spiel::testing::TestPoliciesCanPlay().
SampleAction() [2/2]
std::pair< Action, double > open_spiel::SampleAction (const ActionsAndProbs & outcomes, double z)
Definition at line 274 of file spiel.cc.
{
  SPIEL_CHECK_GE(z, 0);
  SPIEL_CHECK_LT(z, 1);
  // Special case for one-item lists.
  if (outcomes.size() == 1) {
    SPIEL_CHECK_FLOAT_EQ(outcomes[0].second, 1.0);
    return outcomes[0];
  }
  // First do a check that this is indeed a proper discrete distribution.
  double sum = 0;
  for (const std::pair<Action, double>& outcome : outcomes) {
    double prob = outcome.second;
    SPIEL_CHECK_PROB(prob);
    sum += prob;
  }
  SPIEL_CHECK_FLOAT_EQ(sum, 1.0);
  // Now sample an outcome.
  sum = 0;
  for (const std::pair<Action, double>& outcome : outcomes) {
    double prob = outcome.second;
    if (sum <= z && z < (sum + prob)) {
      return outcome;
    }
    sum += prob;
  }
  // If we get here, something has gone wrong
  std::cerr << "Chance sampling failed; outcomes:" << std::endl;
  for (const std::pair<Action, double>& outcome : outcomes) {
    std::cerr << outcome.first << "  " << outcome.second << std::endl;
  }
  SpielFatalError(
      absl::StrCat("Internal error: failed to sample an outcome; z=", z));
}
References SPIEL_CHECK_FLOAT_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LT, SPIEL_CHECK_PROB, SpielFatalError(), and absl::StrCat().
SamplePolicy()
template<typename RandomNumberDistribution > TabularPolicy open_spiel::SamplePolicy (const Game & game, int seed, RandomNumberDistribution & dist, Player player)
Definition at line 328 of file policy.cc.
{
  std::mt19937 gen(seed);
  TabularPolicy policy = GetEmptyTabularPolicy(game, false, player);
  std::unordered_map<std::string, ActionsAndProbs>& policy_table =
      policy.PolicyTable();
  for (auto& kv : policy_table) {
    ActionsAndProbs state_policy;
    if (kv.second.empty()) {
      SpielFatalError("State has zero legal actions.");
    }
    state_policy.reserve(kv.second.size());
    double sum = 0;
    double prob;
    for (const auto& action_and_prob : kv.second) {
      // We multiply the original probability by a random number greater than
      // 0. We then normalize. This has the effect of randomly permuting the
      // policy but all illegal actions still have zero probability.
      prob = dist(gen) * action_and_prob.second;
      sum += prob;
      state_policy.push_back({action_and_prob.first, prob});
    }
    // We normalize the policy to ensure it sums to 1.
    for (auto& action_and_prob : state_policy) {
      action_and_prob.second /= sum;
    }
    // This is included as a sanity check.
    double normalized_sum = 0;
    for (auto& action_and_prob : state_policy) {
      normalized_sum += action_and_prob.second;
    }
    SPIEL_CHECK_FLOAT_EQ(normalized_sum, 1.0);
    kv.second = state_policy;
  }
  return policy;
}
References GetEmptyTabularPolicy(), player, SPIEL_CHECK_FLOAT_EQ, and SpielFatalError().
Referenced by GetFlatDirichletPolicy(), and GetRandomPolicy().
SerializeGameAndState()
std::string open_spiel::SerializeGameAndState (const Game & game, const State & state)
Definition at line 444 of file spiel.cc.
{
  std::string str = "";
  // Meta section.
  absl::StrAppend(&str,
                  "# Automatically generated by OpenSpiel "
                  "SerializeGameAndState\n");
  absl::StrAppend(&str, kSerializeMetaSectionHeader, "\n");
  absl::StrAppend(&str, "Version: ", kSerializationVersion, "\n");
  absl::StrAppend(&str, "\n");
  // Game section.
  absl::StrAppend(&str, kSerializeGameSectionHeader, "\n");
  absl::StrAppend(&str, game.Serialize(), "\n");
  // State section.
  absl::StrAppend(&str, kSerializeStateSectionHeader, "\n");
  absl::StrAppend(&str, state.Serialize(), "\n");
  return str;
}
References state, and absl::StrAppend().
Referenced by define_julia_module(), init_pyspiel_games_bridge(), init_pyspiel_games_euchre(), init_pyspiel_games_gin_rummy(), init_pyspiel_games_tarok(), SpielFatalErrorWithStateInfo(), and open_spiel::testing::TestSerializeDeserialize().
SerializeGameParameters()
std::string open_spiel::SerializeGameParameters (const GameParameters & game_params, const std::string & name_delimiter, const std::string & parameter_delimeter)
Definition at line 120 of file game_parameters.cc.
{
  std::list<std::string> serialized_params;
  for (const auto& key_val : game_params) {
    std::string name = key_val.first;
    GameParameter parameter = key_val.second;
    serialized_params.push_back(
        absl::StrCat(name, name_delimiter, parameter.Serialize()));
  }
  return absl::StrJoin(serialized_params, parameter_delimeter);
}
References name, open_spiel::GameParameter::Serialize(), absl::StrCat(), and absl::StrJoin().
Referenced by GameTypeToString(), and open_spiel::GameParameter::Serialize().
SetErrorHandler()
void open_spiel::SetErrorHandler (ErrorHandler new_error_handler)
Definition at line 128 of file spiel_utils.cc.
{
  error_handler = new_error_handler;
}
References error_handler.
SetProb()
void open_spiel::SetProb (ActionsAndProbs * actions_and_probs, Action action, double prob)
Definition at line 41 of file policy.cc.
{
  for (auto& iter : *actions_and_probs) {
    if (iter.first == action) {
      iter.second = prob;
      return;
    }
  }
  actions_and_probs->push_back({action, prob});
}
References action, and actions_and_probs.
Referenced by open_spiel::TabularPolicy::SetProb(), and open_spiel::algorithms::MDP::Solve().
SpielDefaultErrorHandler()
void open_spiel::SpielDefaultErrorHandler (const std::string & error_msg)
Definition at line 119 of file spiel_utils.cc.
{
  std::cerr << "Spiel Fatal Error: " << error_msg << std::endl
            << std::endl
            << std::flush;
  std::exit(1);
}
SpielFatalError()
void open_spiel::SpielFatalError (const std::string & error_msg)
Definition at line 132 of file spiel_utils.cc.
{
  error_handler(error_msg);
  // The error handler should not return. If it does, we will abort the process.
  std::cerr << "Error handler failure - exiting" << std::endl;
  std::exit(1);
}
References error_handler.
Referenced by open_spiel::universal_poker::ACPCActionToOpenSpielAction(), open_spiel::State::ActionsConsistentWithInformationFrom(), open_spiel::dou_dizhu::ActionToHand(), open_spiel::catch_::CatchState::ActionToString(), open_spiel::cliff_walking::CliffWalkingState::ActionToString(), open_spiel::coin_game::CoinState::ActionToString(), open_spiel::colored_trails::ColoredTrailsState::ActionToString(), open_spiel::coordinated_mp::PenniesState::ActionToString(), open_spiel::crazy_eights::CrazyEightsState::ActionToString(), open_spiel::dou_dizhu::DouDizhuState::ActionToString(), open_spiel::gin_rummy::GinRummyState::ActionToString(), open_spiel::lewis_signaling::LewisSignalingState::ActionToString(), open_spiel::matching_pennies_3p::MatchingPennies3pState::ActionToString(), open_spiel::matrix_game::MatrixGame::ActionToString(), open_spiel::pathfinding::PathfindingGame::ActionToString(), open_spiel::stones_and_gems::StonesNGemsState::ActionToString(), open_spiel::universal_poker::UniversalPokerState::ActionToString(), open_spiel::algorithms::HistoryNode::AddChild(), open_spiel::dou_dizhu::AirplaneCombHandToActionId(), open_spiel::algorithms::torch_az::AlphaZero(), open_spiel::State::ApplyActionsWithLegalityChecks(), open_spiel::State::ApplyActionWithLegalityCheck(), open_spiel::universal_poker::UniversalPokerState::ApplyChoiceAction(), open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::battleship::BattleshipGame::BattleshipGame(), open_spiel::algorithms::TabularBestResponse::BestResponseAction(), open_spiel::algorithms::TabularBestResponse::BestResponseActions(), open_spiel::go::BoardPoints(), open_spiel::phantom_go::BoardPoints(), BuildStateFromHistoryString(), open_spiel::tarok::CardLongNameToAction(), open_spiel::dou_dizhu::CardToSuit(), open_spiel::algorithms::CEGame::CEGame(), open_spiel::algorithms::CFRSolverBase::CFRSolverBase(), open_spiel::algorithms::CFRSolverBase::CFRSolverBase(), open_spiel::dou_dizhu::ChainOnlyHandToActionId(), open_spiel::coin_game::CoinState::ChanceOutcomes(), open_spiel::first_sealed_auction::FPSBAState::ChanceOutcomes(), open_spiel::State::ChanceOutcomes(), open_spiel::testing::CheckChanceOutcomes(), open_spiel::kriegspiel::CheckTypeToString(), open_spiel::Bot::Clone(), open_spiel::chess::ColorToPlayer(), open_spiel::chess::ColorToString(), open_spiel::dynamic_routing::DynamicRoutingData::Create(), open_spiel::go::CreateBoard(), open_spiel::phantom_go::CreateBoard(), open_spiel::BotRegisterer::CreateByName(), open_spiel::GameRegisterer::CreateByName(), open_spiel::ObserverRegisterer::CreateByName(), open_spiel::backgammon::CurPlayerToString(), open_spiel::maedn::CurPlayerToString(), open_spiel::blackjack::BlackjackState::DealCardToPlayer(), open_spiel::Observation::Decompress(), open_spiel::chess::DefaultFen(), DeserializeGameParameter(), DeserializePolicy(), open_spiel::breakthrough::BreakthroughGame::DeserializeState(), open_spiel::crowd_modelling::CrowdModellingGame::DeserializeState(), open_spiel::crowd_modelling_2d::CrowdModelling2dGame::DeserializeState(), open_spiel::dynamic_routing::MeanFieldRoutingGame::DeserializeState(), open_spiel::garnet::GarnetGame::DeserializeState(), open_spiel::stones_and_gems::StonesNGemsGame::DeserializeState(), open_spiel::State::DistributionSupport(), open_spiel::bridge::BridgeState::DoApplyAction(), open_spiel::cliff_walking::CliffWalkingState::DoApplyAction(), open_spiel::coop_box_pushing::CoopBoxPushingState::DoApplyAction(), open_spiel::coordinated_mp::PenniesState::DoApplyAction(), open_spiel::crazy_eights::CrazyEightsState::DoApplyAction(), open_spiel::cursor_go::CursorGoState::DoApplyAction(), open_spiel::dou_dizhu::DouDizhuState::DoApplyAction(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::DoApplyAction(), open_spiel::euchre::EuchreState::DoApplyAction(), open_spiel::first_sealed_auction::FPSBAState::DoApplyAction(), open_spiel::gin_rummy::GinRummyState::DoApplyAction(), open_spiel::hanabi::OpenSpielHanabiState::DoApplyAction(), open_spiel::hearts::HeartsState::DoApplyAction(), open_spiel::leduc_poker::LeducState::DoApplyAction(), open_spiel::lewis_signaling::LewisSignalingState::DoApplyAction(), open_spiel::liars_dice::LiarsDiceState::DoApplyAction(), open_spiel::oh_hell::OhHellState::DoApplyAction(), open_spiel::pig::PigState::DoApplyAction(), open_spiel::skat::SkatState::DoApplyAction(), open_spiel::spades::SpadesState::DoApplyAction(), open_spiel::State::DoApplyAction(), open_spiel::tarok::TarokState::DoApplyAction(), open_spiel::twixt::TwixTState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::State::DoApplyActions(), down_cast(), down_cast(), open_spiel::algorithms::Exploitability(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::ExternalSamplingMCCFRSolver(), open_spiel::Bot::ForceAction(), open_spiel::universal_poker::logic::GamedefToOpenSpielParameters(), GameParametersFromString(), GameParameterTypeToString(), GameToNFGString(), open_spiel::gamut::GamutGenerator::GenerateGame(), open_spiel::json::Value::get_const_ref(), open_spiel::json::Value::get_ref(), open_spiel::json::Value::get_val(), open_spiel::morpion_solitaire::Line::GetAction(), open_spiel::algorithms::CFRInfoStateValues::GetActionIndex(), open_spiel::dou_dizhu::GetAirplaneCombParams(), open_spiel::dou_dizhu::GetAirplanePairActionBase(), open_spiel::dou_dizhu::GetAirplaneSoloActionBase(), open_spiel::algorithms::GetAllHistories(), open_spiel::algorithms::GetAllStates(), GetBaseSamplerType(), open_spiel::algorithms::TabularBestResponse::GetBestResponseActions(), open_spiel::algorithms::HistoryTree::GetByHistory(), GetCandidatesSamplerType(), open_spiel::solitaire::GetCardIndex(), open_spiel::dou_dizhu::GetChainOnlyActionBase(), open_spiel::dou_dizhu::GetChainOnlyMinLength(), open_spiel::algorithms::HistoryNode::GetChild(), GetEmptyTabularPolicy(), GetFirstActionPolicy(), open_spiel::efg_game::EFGGame::GetInformationStateStringByName(), open_spiel::efg_game::EFGGame::GetInformationStateStringByNumber(), open_spiel::dou_dizhu::GetNumCardsPerRank(), open_spiel::dou_dizhu::GetNumKickersAirplanePairComb(), open_spiel::dou_dizhu::GetNumKickersAirplaneSoloComb(), open_spiel::solitaire::GetOppositeSuits(), open_spiel::solitaire::SolitaireState::GetPile(), open_spiel::solitaire::SolitaireState::GetPile(), open_spiel::Bot::GetPolicy(), GetRandomDeterministicPolicy(), open_spiel::Game::GetRNGState(), open_spiel::dou_dizhu::GetSingleRankActionBase(), open_spiel::dou_dizhu::GetSingleTrioCombParams(), open_spiel::algorithms::GetStateDistribution(), open_spiel::algorithms::AFCCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::AFCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::CCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::CETabularPolicy::GetStatePolicy(), open_spiel::algorithms::CFRAveragePolicy::GetStatePolicy(), open_spiel::algorithms::CFRAveragePolicy::GetStatePolicy(), open_spiel::algorithms::CFRCurrentPolicy::GetStatePolicy(), open_spiel::algorithms::CFRCurrentPolicy::GetStatePolicy(), open_spiel::algorithms::EFCCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::EFCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::ExplorativeSamplingPolicy::GetStatePolicy(), open_spiel::algorithms::TargetedPolicy::GetStatePolicy(), open_spiel::Policy::GetStatePolicy(), open_spiel::PreferredActionPolicy::GetStatePolicy(), open_spiel::algorithms::GetSuccessorsWithProbs(), open_spiel::backgammon::BackgammonState::GetToPos(), open_spiel::dou_dizhu::GetTrioCombActionBase(), open_spiel::dou_dizhu::GetTrioCombKickerType(), open_spiel::twenty_forty_eight::GetVector(), open_spiel::go::GoBoard::GoBoard(), open_spiel::phantom_go::GoColorToChar(), open_spiel::go::GoColorToString(), open_spiel::phantom_go::GoColorToString(), HistoryFromString(), open_spiel::algorithms::OOSAlgorithm::IncrementallyBuildTree(), open_spiel::colored_trails::ColoredTrailsState::InformationStateString(), open_spiel::State::InformationStateString(), open_spiel::battleship::BattleshipState::InformationStateTensor(), open_spiel::State::InformationStateTensor(), open_spiel::Game::InformationStateTensorShape(), InitBot(), InitBot(), InitBot(), open_spiel::algorithms::OOSAlgorithm::Iteration(), open_spiel::coin_game::CoinState::LegalActions(), open_spiel::lewis_signaling::LewisSignalingState::LegalActions(), open_spiel::PyState::LegalActions(), open_spiel::trade_comm::TradeCommState::LegalActions(), open_spiel::solitaire::Card::LegalChildren(), open_spiel::morpion_solitaire::Line::Line(), LoadBot(), open_spiel::SerializableCircularBuffer< T >::LoadBuffer(), LoadGame(), LoadGame(), open_spiel::algorithms::LoadMatrixGame(), open_spiel::algorithms::LoadTensorGame(), main(), open_spiel::dark_chess::DarkChessGame::MakeObserver(), open_spiel::gin_rummy::GinRummyGame::MakeObserver(), open_spiel::kriegspiel::KriegspielGame::MakeObserver(), open_spiel::PyGame::MakeObserver(), open_spiel::rbc::RbcGame::MakeObserver(), open_spiel::Game::MakeRegisteredObserver(), open_spiel::Game::MaxChanceNodesInHistory(), open_spiel::universal_poker::UniversalPokerGame::MaxGameLength(), open_spiel::Game::MaxHistoryLength(), open_spiel::backgammon::BackgammonGame::MaxUtility(), open_spiel::goofspiel::GoofspielGame::MaxUtility(), open_spiel::chess::ChessBoard::MaybeCastlingRookSquare(), open_spiel::algorithms::MCTSBot::MCTSBot(), open_spiel::State::MeanFieldPopulation(), open_spiel::gin_rummy::GinRummyUtils::MeldToInt(), open_spiel::goofspiel::GoofspielGame::MinUtility(), open_spiel::solitaire::Move::Move(), open_spiel::algorithms::NashConv(), open_spiel::Game::NewInitialState(), open_spiel::Game::NewInitialStateForPopulation(), open_spiel::othello::Move::Next(), open_spiel::coop_box_pushing::CoopBoxPushingState::ObservationString(), open_spiel::lewis_signaling::LewisSignalingState::ObservationString(), open_spiel::State::ObservationString(), open_spiel::lewis_signaling::LewisSignalingState::ObservationTensor(), open_spiel::State::ObservationTensor(), open_spiel::dark_hex::DarkHexGame::ObservationTensorShape(), open_spiel::Game::ObservationTensorShape(), open_spiel::phantom_ttt::PhantomTTTGame::ObservationTensorShape(), open_spiel::SamplerFromRng::operator()(), open_spiel::breakthrough::operator<<(), open_spiel::checkers::operator<<(), open_spiel::clobber::operator<<(), open_spiel::connect_four::operator<<(), open_spiel::dark_hex::operator<<(), open_spiel::dark_hex::operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), open_spiel::phantom_ttt::operator<<(), operator>>(), operator>>(), operator>>(), operator>>(), operator>>(), open_spiel::go::OppColor(), open_spiel::phantom_go::OppColor(), open_spiel::dots_and_boxes::OrientationToString(), open_spiel::algorithms::OutcomeSamplingMCCFRSolver::OutcomeSamplingMCCFRSolver(), open_spiel::Game::ParameterValue(), ParameterValue(), open_spiel::stones_and_gems::StonesNGemsGame::ParseGrid(), open_spiel::chess::ChessBoard::ParseLANMove(), open_spiel::universal_poker::UniversalPokerGame::parseParameters(), open_spiel::backgammon::ParseScoringType(), open_spiel::phantom_go::PhantomGoBoard::PhantomGoBoard(), open_spiel::phantom_ttt::PhantomTTTGame::PhantomTTTGame(), open_spiel::chess::PieceTypeToString(), open_spiel::connect_four::PlayerRelative(), open_spiel::havannah::PlayerRelative(), open_spiel::pentago::PlayerRelative(), open_spiel::y_game::PlayerRelative(), open_spiel::amazons::PlayerToState(), open_spiel::dots_and_boxes::PlayerToState(), open_spiel::hex::PlayerToState(), open_spiel::nine_mens_morris::PlayerToState(), open_spiel::tic_tac_toe::PlayerToState(), open_spiel::nine_mens_morris::PlayerToStr(), PlayGame(), PlayGame(), open_spiel::go::GoBoard::PlayMove(), open_spiel::quoridor::QuoridorGame::QuoridorGame(), open_spiel::dou_dizhu::RankString(), open_spiel::uci::UCIBot::Read(), open_spiel::algorithms::RecordTrajectory(), open_spiel::ObserverRegisterer::RegisterObserver(), open_spiel::State::ResampleFromInfostate(), open_spiel::Bot::RestartAt(), open_spiel::hearts::XinxinBot::RestartAt(), open_spiel::goofspiel::GoofspielState::Returns(), open_spiel::solitaire::Pile::Reveal(), open_spiel::roshambo::RoshamboBot::RoshamboBot(), SampleAction(), open_spiel::algorithms::CFRInfoStateValues::SampleActionIndex(), SamplePolicy(), open_spiel::bridge_uncontested_bidding::UncontestedBiddingState::ScoreDeal(), open_spiel::bridge::BridgeState::ScoreForContracts(), open_spiel::dou_dizhu::SearchForLegalActions(), open_spiel::Policy::Serialize(), open_spiel::PreferredActionPolicy::Serialize(), open_spiel::TabularPolicy::Serialize(), open_spiel::algorithms::SerializeCFRInfoStateValuesTable(), open_spiel::algorithms::CFRSolverBase::SerializeThisType(), open_spiel::Game::SetRNGState(), open_spiel::go::GoBoard::SingleLiberty(), open_spiel::phantom_go::PhantomGoBoard::SingleLiberty(), open_spiel::dou_dizhu::SingleTrioCombHandToActionId(), open_spiel::solitaire::Pile::Sources(), open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyCfValuesConstraints(), open_spiel::algorithms::ortools::SequenceFormLpSpecification::SpecifyReachProbsConstraints(), SpielFatalErrorWithStateInfo(), open_spiel::nine_mens_morris::StateToChar(), open_spiel::nine_mens_morris::StateToPlayer(), open_spiel::amazons::StateToString(), open_spiel::dots_and_boxes::StateToString(), open_spiel::dynamic_routing::MeanFieldRoutingGameState::StateToString(), open_spiel::hex::StateToString(), open_spiel::tic_tac_toe::StateToString(), open_spiel::gin_rummy::SimpleGinRummyBot::Step(), open_spiel::uci::UCIBot::Step(), open_spiel::Bot::StepWithPolicy(), open_spiel::dark_chess::DarkChessObserver::StringFrom(), open_spiel::gin_rummy::GinRummyObserver::StringFrom(), open_spiel::kriegspiel::KriegspielObserver::StringFrom(), open_spiel::rbc::RbcObserver::StringFrom(), open_spiel::State::StringToAction(), open_spiel::algorithms::TabularBestResponse::TabularBestResponse(), open_spiel::algorithms::TabularBestResponse::TabularBestResponse(), open_spiel::solitaire::Pile::Targets(), open_spiel::chess::ToInt(), open_spiel::GameParameter::ToReprString(), open_spiel::GameParameter::ToString(), open_spiel::json::ToString(), open_spiel::lewis_signaling::LewisSignalingState::ToString(), open_spiel::chess::Piece::ToUnicode(), open_spiel::go::TrompTaylorScore(), open_spiel::phantom_go::TrompTaylorScore(), open_spiel::twixt::TwixTGame::TwixTGame(), open_spiel::uci::UCIBot::UCIBot(), open_spiel::State::UndoAction(), open_spiel::universal_poker::UniversalPokerGame::UniversalPokerGame(), open_spiel::State::UpdateDistribution(), open_spiel::algorithms::TabularBestResponse::Value(), open_spiel::uci::UCIBot::Write(), open_spiel::coordinated_mp::PenniesObserver::WriteTensor(), open_spiel::dark_chess::DarkChessObserver::WriteTensor(), open_spiel::gin_rummy::GinRummyObserver::WriteTensor(), open_spiel::kriegspiel::KriegspielObserver::WriteTensor(), open_spiel::phantom_go::PhantomGoObserver::WriteTensor(), open_spiel::rbc::RbcObserver::WriteTensor(), and open_spiel::hearts::XinxinBot::XinxinRules().
SpielFatalErrorWithStateInfo()
void open_spiel::SpielFatalErrorWithStateInfo (const std::string & error_msg, const Game & game, const State & state)
Definition at line 842 of file spiel.cc.
{
  // A fatal error wrapper designed to return useful debugging information.
  const std::string& info = SerializeGameAndState(game, state);
  SpielFatalError(absl::StrCat(error_msg, "Serialized state:\n", info));
}
References SerializeGameAndState(), SpielFatalError(), state, and absl::StrCat().
Referenced by open_spiel::colored_trails::ColoredTrailsState::DoApplyAction().
StateFromHistory()
std::unique_ptr< State > open_spiel::StateFromHistory (std::shared_ptr< const Game > game, const std::vector< Action > & history)
Definition at line 80 of file start_at.cc.
{
  std::unique_ptr<State> state = game->NewInitialState();
  for (const Action& a : history) state->ApplyAction(a);
  return state;
}
References a, and state.
StatePoliciesEqual()
bool open_spiel::StatePoliciesEqual (const ActionsAndProbs & state_policy1, const ActionsAndProbs & state_policy2, double float_tolerance)
Definition at line 79 of file policy.cc.
{
  if (state_policy1.size() != state_policy2.size()) {
    return false;
  }
  for (int i = 0; i < state_policy1.size(); ++i) {
    if (state_policy1[i].first != state_policy2[i].first) {
      return false;
    }
    if (!Near(state_policy1[i].second, state_policy2[i].second,
              float_tolerance)) {
      return false;
    }
  }
  return true;
}
References first, i, and Near().
StrContainsIgnoreCase()
bool open_spiel::StrContainsIgnoreCase (const std::string & haystack, const std::string & needle)
Definition at line 170 of file spiel_utils.cc.
{
  std::string haystack_copy = haystack;
  std::string needle_copy = needle;
  for (int i = 0; i < haystack_copy.size(); ++i) {
    haystack_copy[i] = std::tolower(haystack_copy[i]);
  }
  for (int i = 0; i < needle_copy.size(); ++i) {
    needle_copy[i] = std::tolower(needle_copy[i]);
  }
  return (haystack_copy.find(needle_copy) != std::string::npos);
}
References i.
Referenced by open_spiel::universal_poker::logic::GamedefToOpenSpielParameters(), open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersNormalizesKeyOnlyLines(), and open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersRemovesUnneededLines().
SubsetsOfSize()
template<typename T > std::vector< std::vector< T > > open_spiel::SubsetsOfSize (const std::vector< T > & v, int k)
Definition at line 51 of file combinatorics.h.
{
  SPIEL_CHECK_LE(k, v.size());
  SPIEL_CHECK_GE(k, 0);
  std::vector<bool> bitset(v.size() - k, 0);
  bitset.resize(v.size(), 1);
  std::vector<std::vector<T>> vs;
  do {
    std::vector<T> x;
    x.reserve(k);
    for (std::size_t i = 0; i != v.size(); ++i) {
      if (bitset[i]) {
        x.push_back(v[i]);
      }
    }
    vs.push_back(x);
  } while (std::next_permutation(bitset.begin(), bitset.end()));
  return vs;
}
References i, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and x.
SubtractMean()
std::vector< double > open_spiel::SubtractMean (std::vector< double > && vec) inline
Definition at line 28 of file zerosum.h.
{
  double mean = std::accumulate(vec.begin(), vec.end(), 0.0) / vec.size();
  std::vector<double> result = std::move(vec);
  for (auto& item : result) item -= mean;
  return result;
}
Referenced by open_spiel::ZeroSumState::Returns(), and open_spiel::ZeroSumState::Rewards().
TensorFromObserver()
std::vector< float > open_spiel::TensorFromObserver (const State & state, const Observer & observer)
Definition at line 373 of file observer.cc.
{
  TrackingVectorAllocator allocator;
  observer.WriteTensor(state, /*player=*/state.CurrentPlayer(), &allocator);
  return std::move(allocator.data());
}
References open_spiel::TrackingVectorAllocator::data(), state, and open_spiel::Observer::WriteTensor().
ToDeterministicPolicy()
ActionsAndProbs open_spiel::ToDeterministicPolicy (const ActionsAndProbs & actions_and_probs, Action action)
Definition at line 69 of file policy.cc.
{
  ActionsAndProbs new_policy;
  new_policy.reserve(actions_and_probs.size());
  for (const auto& iter : actions_and_probs) {
    new_policy.push_back({iter.first, iter.first == action ? 1.0 : 0.0});
  }
  return new_policy;
}
References action, and actions_and_probs.
Referenced by open_spiel::algorithms::CorrDevBuilder::AddMixedJointPolicy(), and open_spiel::algorithms::CorrDevBuilder::AddSampledJointPolicy().
ToJointTabularPolicy()
TabularPolicy open_spiel::ToJointTabularPolicy (const std::vector< TabularPolicy > & policies, bool check_no_overlap)
Definition at line 534 of file policy.cc.
{
  TabularPolicy joint_policy;
  for (const TabularPolicy& policy : policies) {
    if (check_no_overlap) {
      for (const auto& key_and_val : policy.PolicyTable()) {
        SPIEL_CHECK_TRUE(joint_policy.PolicyTable().find(key_and_val.first) ==
                         joint_policy.PolicyTable().end());
      }
    }
    joint_policy.ImportPolicy(policy);
  }
  return joint_policy;
}
References open_spiel::TabularPolicy::ImportPolicy(), open_spiel::TabularPolicy::PolicyTable(), and SPIEL_CHECK_TRUE.
Referenced by init_pyspiel_policy().
ToTabularPolicy()
TabularPolicy open_spiel::ToTabularPolicy (const Game & game, const Policy * policy)
Definition at line 488 of file policy.cc.
{
  TabularPolicy tabular_policy;
  std::vector<std::unique_ptr<State>> to_visit;
  to_visit.push_back(game.NewInitialState());
  for (int idx = 0; idx < to_visit.size(); ++idx) {
    const State* state = to_visit[idx].get();
    if (state->IsTerminal()) {
      continue;
    }
    if (!state->IsChanceNode()) {
      std::vector<Player> players(game.NumPlayers());
      if (state->IsSimultaneousNode()) {
        absl::c_iota(players, 0);
      } else {
        players = {state->CurrentPlayer()};
      }
      for (Player player : players) {
        ActionsAndProbs state_policy = policy->GetStatePolicy(*state);
        tabular_policy.SetStatePolicy(state->InformationStateString(player),
                                      state_policy);
      }
    }
    for (Action action : state->LegalActions()) {
      to_visit.push_back(state->Child(action));
    }
  }
  return tabular_policy;
}
References action, absl::c_iota(), player, open_spiel::TabularPolicy::SetStatePolicy(), and state.
Referenced by GetPrefActionPolicy().
TurnBasedGoofspielGameString()
std::string open_spiel::TurnBasedGoofspielGameString (int num_cards)
Definition at line 40 of file canonical_game_strings.cc.
{
  return absl::StrFormat(
      "turn_based_simultaneous_game(game=goofspiel("
      "imp_info=true,num_cards=%i,players=2,"
      "points_order=descending,returns_type=win_loss))",
      num_cards);
}
References absl::StrFormat().
UniformStatePolicy() [1/3]
ActionsAndProbs open_spiel::UniformStatePolicy (const State & state)
Definition at line 118 of file policy.cc.
{
  return UniformStatePolicy(state.LegalActions());
}
References state, and UniformStatePolicy().
UniformStatePolicy() [2/3]
ActionsAndProbs open_spiel::UniformStatePolicy (const State & state, Player player)
Definition at line 122 of file policy.cc.
{
  return UniformStatePolicy(state.LegalActions(player));
}
References player, state, and UniformStatePolicy().
UniformStatePolicy() [3/3]
ActionsAndProbs open_spiel::UniformStatePolicy (const std::vector< Action > & actions)
Definition at line 110 of file policy.cc.
{
  ActionsAndProbs actions_and_probs;
  absl::c_for_each(actions, [&actions_and_probs, &actions](Action a) {
    actions_and_probs.push_back({a, 1. / static_cast<double>(actions.size())});
  });
  return actions_and_probs;
}
References a, actions_and_probs, and absl::c_for_each().
Referenced by open_spiel::algorithms::AFCCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::AFCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::EFCCETabularPolicy::GetStatePolicy(), open_spiel::algorithms::EFCETabularPolicy::GetStatePolicy(), open_spiel::UniformPolicy::GetStatePolicy(), open_spiel::algorithms::OOSAlgorithm::IncrementallyBuildTree(), UniformStatePolicy(), and UniformStatePolicy().
UnrankActionMixedBase()
std::vector< int > open_spiel::UnrankActionMixedBase (Action action, const std::vector< int > & bases)
Definition at line 69 of file spiel_utils.cc.
{
  std::vector<int> digits(bases.size());
  for (int i = digits.size() - 1; i >= 0; --i) {
    SPIEL_CHECK_GT(bases[i], 1);
    digits[i] = action % bases[i];
    action /= bases[i];
  }
  SPIEL_CHECK_EQ(action, 0);
  return digits;
}
References action, i, SPIEL_CHECK_EQ, and SPIEL_CHECK_GT.
Referenced by open_spiel::breakthrough::BreakthroughState::ActionToString(), open_spiel::clobber::ClobberState::ActionToString(), open_spiel::breakthrough::BreakthroughState::DoApplyAction(), open_spiel::clobber::ClobberState::DoApplyAction(), open_spiel::universal_poker::UniversalPokerState::DoApplyAction(), open_spiel::checkers::CheckersState::SpielActionToCheckersAction(), open_spiel::breakthrough::BreakthroughState::UndoAction(), and open_spiel::clobber::ClobberState::UndoAction().
UnrankPermutation()
template<typename T > std::vector< T > open_spiel::UnrankPermutation (const std::vector< T > & v, int k)
Definition at line 139 of file combinatorics.h.
{
  int n = v.size();
  std::vector<bool> used(v.size(), false);
  std::vector<T> perm(v.size());
  for (int i = 1; i <= n; ++i) {
    int divisor = Factorial(n - i);
    int digit_idx = k / divisor;
    int j = 0, l = 0;
    for (; j < n; ++j) {
      if (used[j]) {
        continue;
      }
      if (l == digit_idx) {
        break;
      }
      ++l;
    }
    perm[i - 1] = v[j];
    used[j] = true;
    k -= digit_idx * divisor;
  }
  return perm;
}
References Factorial(), i, and n.
Referenced by open_spiel::pathfinding::PathfindingState::DoApplyAction().
VariationsWithoutRepetition()
template<typename T > std::vector< std::vector< T > > open_spiel::VariationsWithoutRepetition (const std::vector< T > & v, int k)
Definition at line 102 of file combinatorics.h.
{
  SPIEL_CHECK_LE(k, v.size());
  SPIEL_CHECK_GE(k, 0);
  // Generate masks -- avoid copying of T, as that might
  // be more expensive than juggling integers.
  std::vector<int> current_permutation;
  std::vector<int> rng(v.size());
  std::iota(rng.begin(), rng.end(), 0);
  auto masks = GenerateMasks(rng, k, current_permutation);
  // Apply the masks.
  std::vector<std::vector<T>> vs;
  for (auto& mask : masks) {
    std::vector<T> x;
    for (auto& i : mask) {
      x.push_back(v[i]);
    }
    vs.push_back(x);
  }
  return vs;
}
References GenerateMasks(), i, SPIEL_CHECK_GE, SPIEL_CHECK_LE, and x.
VectorOfPairsToString() [1/2]
template<class A , class B > std::string open_spiel::VectorOfPairsToString (const std::vector< std::pair< A, B > > & vec, const std::string & delimiter, const std::string & pair_delimiter)
VectorOfPairsToString() [2/2]
template<class A , class B > std::string open_spiel::VectorOfPairsToString (std::vector< std::pair< A, B > > & vec, const std::string & delimiter, const std::string & pair_delimiter)
Definition at line 156 of file spiel_utils.cc.
{
  std::string str;
  for (int i = 0; i < vec.size(); ++i) {
    absl::StrAppend(&str, vec[i].first, pair_delimiter, vec[i].second);
    if (i != vec.size() - 1) {
      absl::StrAppend(&str, delimiter);
    }
  }
  return str;
}
References first, i, and absl::StrAppend().
WriteAndLoadGame()
void open_spiel::WriteAndLoadGame (std::string game_name)
Definition at line 30 of file efg_writer_test.cc.
{
  std::string filename =
      absl::StrCat(file::GetTmpDir(), "/open_spiel_test_", game_name, ".efg");
  std::shared_ptr<const Game> base_game = LoadGame(game_name);
  EFGWriter(*base_game, filename).Write();
  std::shared_ptr<const Game> efg_game =
      LoadGame("efg_game", {{"filename", GameParameter(filename)}});
  SPIEL_CHECK_TRUE(efg_game != nullptr);
  GameType base_game_type = base_game->GetType();
  GameType efg_game_type = efg_game->GetType();
  SPIEL_CHECK_EQ(efg_game_type.dynamics, GameType::Dynamics::kSequential);
  SPIEL_CHECK_EQ(efg_game_type.information, base_game_type.information);
  SPIEL_CHECK_EQ(efg_game_type.utility, base_game_type.utility);
  SPIEL_CHECK_EQ(efg_game_type.chance_mode, base_game_type.chance_mode);
  SPIEL_CHECK_EQ(efg_game->NumDistinctActions(),
                 base_game->NumDistinctActions());
  // TODO(author11) More comprehensive tests that the games are the same.
  testing::RandomSimTestNoSerialize(*efg_game, 100);
  SPIEL_CHECK_TRUE(file::Exists(filename));
  SPIEL_CHECK_TRUE(file::Remove(filename));
  SPIEL_CHECK_FALSE(file::Remove(filename));  // Already gone
  SPIEL_CHECK_FALSE(file::Exists(filename));
}
References open_spiel::GameType::chance_mode, open_spiel::GameType::dynamics, open_spiel::file::Exists(), open_spiel::file::GetTmpDir(), open_spiel::GameType::information, open_spiel::GameType::kSequential, LoadGame(), open_spiel::testing::RandomSimTestNoSerialize(), open_spiel::file::Remove(), SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_TRUE, absl::StrCat(), open_spiel::GameType::utility, and open_spiel::EFGWriter::Write().
Referenced by main().
Zip()
template<typename InputSequence1 , typename InputSequence2 , typename ZippedOutputIterator > void open_spiel::Zip (const InputSequence1 & first1, const InputSequence1 & last1, const InputSequence2 & first2, ZippedOutputIterator & output)
Definition at line 32 of file functional.h.
{
  std::transform(
      first1, last1, first2, std::back_inserter(output),
      [](const auto& a, const auto& b) { return std::make_pair(a, b); });
}
References a, and b.
Variable Documentation
error_handler
ErrorHandler open_spiel.error_handler = SpielDefaultErrorHandler
Definition at line 126 of file spiel_utils.cc.
Referenced by SetErrorHandler(), and SpielFatalError().
kDefaultFixedPlayer
Player open_spiel.kDefaultFixedPlayer = 0 constexpr
Definition at line 33 of file restricted_nash_response.h.
kDefaultInternalDelimiter
const char* open_spiel.kDefaultInternalDelimiter = "***" inline constexpr
Definition at line 44 of file game_parameters.h.
kDefaultNameDelimiter
const char* open_spiel.kDefaultNameDelimiter = "=" inline constexpr
Definition at line 42 of file game_parameters.h.
kDefaultObsType
IIGObservationType open_spiel.kDefaultObsType inline constexpr
Initial value:
{
    true,
    false,
    PrivateInfoType::kSinglePlayer}
Definition at line 288 of file observer.h.
{
    /*public_info*/true,
    /*perfect_recall*/false,
    /*private_info*/PrivateInfoType::kSinglePlayer};
Referenced by open_spiel::dark_chess::DarkChessGame::DarkChessGame(), open_spiel::PyGame::default_observer(), open_spiel::gin_rummy::GinRummyGame::GinRummyGame(), open_spiel::goofspiel::GoofspielGame::GoofspielGame(), open_spiel::kriegspiel::KriegspielGame::KriegspielGame(), open_spiel::kuhn_poker::KuhnGame::KuhnGame(), open_spiel::leduc_poker::LeducGame::LeducGame(), open_spiel::Game::MakeBuiltInObserver(), open_spiel::coordinated_mp::PenniesGame::MakeObserver(), open_spiel::dark_chess::DarkChessGame::MakeObserver(), open_spiel::gin_rummy::GinRummyGame::MakeObserver(), open_spiel::goofspiel::GoofspielGame::MakeObserver(), open_spiel::kriegspiel::KriegspielGame::MakeObserver(), open_spiel::kuhn_poker::KuhnGame::MakeObserver(), open_spiel::leduc_poker::LeducGame::MakeObserver(), open_spiel::rbc::RbcGame::MakeObserver(), open_spiel::RestrictedNashResponseGame::MakeObserver(), open_spiel::coordinated_mp::PenniesGame::PenniesGame(), open_spiel::phantom_go::PhantomGoGame::PhantomGoGame(), open_spiel::rbc::RbcGame::RbcGame(), and open_spiel::RestrictedNashResponseGame::RestrictedNashResponseGame().
kDefaultP
double open_spiel.kDefaultP = 0.5 constexpr
Definition at line 34 of file restricted_nash_response.h.
kDefaultParameterDelimiter
const char* open_spiel.kDefaultParameterDelimiter = "|||" inline constexpr
Definition at line 43 of file game_parameters.h.
kDefaultPythonCommand
const char* open_spiel.kDefaultPythonCommand = "python3" inline constexpr
Definition at line 23 of file run_python.h.
Referenced by RunPython().
kGameType
const GameType open_spiel.kGameType
Initial value:
{
    "normal_form_extensive_game",
    "Normal-Form Version of an Extensive Game",
    GameType::Dynamics::kSimultaneous,
    GameType::ChanceMode::kDeterministic,
    GameType::Information::kOneShot,
    GameType::Utility::kGeneralSum,
    GameType::RewardModel::kTerminal,
    100,
    1,
    true,
    true,
    true,
    true,
    {{"game",
      GameParameter(GameParameter::Type::kGame, true)}},
    false}
Definition at line 30 of file normal_form_extensive_game.cc.
{
    /*short_name=*/"normal_form_extensive_game",
    /*long_name=*/"Normal-Form Version of an Extensive Game",
    GameType::Dynamics::kSimultaneous,
    GameType::ChanceMode::kDeterministic,
    GameType::Information::kOneShot,
    GameType::Utility::kGeneralSum,
    GameType::RewardModel::kTerminal,
    /*max_num_players=*/100,
    /*min_num_players=*/1,
    /*provides_information_state_string=*/true,
    /*provides_information_state_tensor=*/true,
    /*provides_observation_string=*/true,
    /*provides_observation_tensor=*/true,
    {{"game",
      GameParameter(GameParameter::Type::kGame, /*is_mandatory=*/true)}},
    /*default_loadable=*/false};
Referenced by open_spiel::battleship::BattleshipGame::BattleshipGame(), ExtensiveToTensorGame(), open_spiel::kuhn_poker::KuhnGame::KuhnGame(), open_spiel::leduc_poker::LeducGame::LeducGame(), open_spiel::liars_dice::LiarsDiceGame::LiarsDiceGame(), open_spiel::maedn::MaednGame::MaednGame(), and open_spiel::battleship::single_tensor().
kInfoStateObsType
IIGObservationType open_spiel.kInfoStateObsType inline constexpr
Initial value:
{
    true,
    true,
    PrivateInfoType::kSinglePlayer}
Definition at line 295 of file observer.h.
{
    /*public_info*/true,
    /*perfect_recall*/true,
    /*private_info*/PrivateInfoType::kSinglePlayer};
Referenced by open_spiel::gin_rummy::GinRummyGame::GinRummyGame(), open_spiel::goofspiel::GoofspielGame::GoofspielGame(), open_spiel::PyGame::info_state_observer(), open_spiel::kuhn_poker::KuhnGame::KuhnGame(), open_spiel::leduc_poker::LeducGame::LeducGame(), open_spiel::Game::MakeBuiltInObserver(), open_spiel::coordinated_mp::PenniesGame::PenniesGame(), and open_spiel::RestrictedNashResponseGame::RestrictedNashResponseGame().
kInvalidAction
Action open_spiel.kInvalidAction = -1 inline constexpr
Definition at line 40 of file spiel_globals.h.
Referenced by open_spiel::universal_poker::ACPCActionToOpenSpielAction(), open_spiel::dou_dizhu::AirplaneCombHandTest(), open_spiel::algorithms::AlphaBetaSearch(), open_spiel::State::ApplyAction(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::BRPIIteration(), open_spiel::dou_dizhu::ChainOnlyHandTest(), open_spiel::algorithms::AFCCEState::CurRecommendation(), open_spiel::algorithms::AFCEState::CurRecommendation(), open_spiel::algorithms::EFCCEState::CurRecommendation(), open_spiel::algorithms::EFCEState::CurRecommendation(), define_julia_module(), open_spiel::algorithms::AFCCEState::DoApplyAction(), EvaluateBots(), open_spiel::algorithms::ExpectiminimaxSearch(), open_spiel::SimMoveState::FlatJointActionToActions(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::FullFPIteration(), GetAction(), GetAction(), open_spiel::dou_dizhu::GetAirplaneCombParams(), open_spiel::bargaining::BargainingGame::GetOfferByQuantities(), GetOptimalAction(), open_spiel::algorithms::GetStateDistribution(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::IBRIteration(), open_spiel::algorithms::OOSAlgorithm::IncrementallyBuildTree(), open_spiel::euchre::EuchreState::InformationStateTensor(), open_spiel::markov_soccer::MarkovSoccerState::LegalActions(), open_spiel::algorithms::MaxNSearch(), open_spiel::algorithms::MCTSBot::MCTSearch(), open_spiel::coop_to_1p::CoopTo1pState::ObservationTensor(), open_spiel::leduc_poker::LeducState::padded_betting_sequence(), open_spiel::chess::ChessState::ParseMoveToAction(), PlayGame(), open_spiel::algorithms::RecordTrajectory(), open_spiel::hearts::HeartsState::ResampleFromInfostate(), open_spiel::oh_hell::OhHellState::ResampleFromInfostate(), open_spiel::algorithms::TabularSarsaSolver::RunIteration(), open_spiel::algorithms::blotto_fp::FictitiousPlayProcess::SBRIteration(), open_spiel::dou_dizhu::SearchAirplaneCombActions(), open_spiel::dou_dizhu::SearchChainOnlyActions(), open_spiel::dou_dizhu::SearchForLegalActions(), open_spiel::dou_dizhu::SearchSingleRankActions(), open_spiel::dou_dizhu::SearchSingleTrioCombActions(), open_spiel::dou_dizhu::SingleRankHandTest(), open_spiel::dou_dizhu::SingleTrioCombHandTest(), open_spiel::algorithms::MDP::Solve(), open_spiel::algorithms::torch_dqn::DQN::Step(), open_spiel::algorithms::torch_dqn::RandomAgent::Step(), open_spiel::HumanBot::Step(), open_spiel::algorithms::SearchNode::ToString(), open_spiel::crazy_eights::CrazyEightsState::ToString(), and open_spiel::euchre::EuchreState::ToString().
kNumHeaderBytes
int open_spiel.kNumHeaderBytes = 1 constexpr
Definition at line 250 of file observer.cc.
Referenced by open_spiel::BinaryCompress::Compress(), open_spiel::NoCompress::Compress(), open_spiel::BinaryCompress::Decompress(), and open_spiel::NoCompress::Decompress().
kPrivateObsType
IIGObservationType open_spiel.kPrivateObsType inline constexpr
Initial value:
{
    false,
    false,
    PrivateInfoType::kSinglePlayer}
Definition at line 313 of file observer.h.
{
    /*public_info*/false,
    /*perfect_recall*/false,
    /*private_info*/PrivateInfoType::kSinglePlayer};
kPublicObsType
IIGObservationType open_spiel.kPublicObsType inline constexpr
Initial value:
{
    true,
    false,
    PrivateInfoType::kNone}
Definition at line 301 of file observer.h.
{
    /*public_info*/true,
    /*perfect_recall*/false,
    /*private_info*/PrivateInfoType::kNone};
kPublicStateObsType
IIGObservationType open_spiel.kPublicStateObsType inline constexpr
Initial value:
{
    true,
    true,
    PrivateInfoType::kNone}
Definition at line 307 of file observer.h.
{
    /*public_info*/true,
    /*perfect_recall*/true,
    /*private_info*/PrivateInfoType::kNone};
kTagDict
const absl::string_view open_spiel.kTagDict = "__dict__=" inline constexpr
Definition at line 328 of file python_games.cc.
Referenced by open_spiel::PyState::Deserialize(), and open_spiel::PyState::Serialize().
kTagHistory
const absl::string_view open_spiel.kTagHistory = "history=" inline constexpr
Definition at line 326 of file python_games.cc.
Referenced by open_spiel::PyState::Deserialize(), and open_spiel::PyState::Serialize().
kTagMoveNumber
const absl::string_view open_spiel.kTagMoveNumber = "move_number=" inline constexpr
Definition at line 327 of file python_games.cc.
Referenced by open_spiel::PyState::Deserialize(), and open_spiel::PyState::Serialize().