open spiel: open_spiel::uci Namespace Reference
open_spiel::uci Namespace Reference
Classes
class UCIBot
Typedefs
using Options = std::map<std::string, std::string>
Enumerations
enum class SearchLimitType { kMoveTime , kNodes , kDepth , kMate }
Functions
void RandomUciBot ()
std::unique_ptr< Bot > MakeUCIBot (const std::string &bot_binary_path, int search_limit_value, bool ponder, const Options &options, SearchLimitType search_limit_type)
Typedef Documentation
Options
using open_spiel::uci::Options = std::map<std::string, std::string>
Definition at line 37 of file uci_bot.h.
Enumeration Type Documentation
SearchLimitType
enum class open_spiel::uci::SearchLimitType strong
Enumerator
kMoveTime
kNodes
kDepth
kMate
Definition at line 39 of file uci_bot.h.
{
  kMoveTime,
  kNodes,
  kDepth,
  kMate,
};
Function Documentation
MakeUCIBot()
std::unique_ptr< Bot > open_spiel::uci::MakeUCIBot (const std::string & bot_binary_path, int search_limit_value, bool ponder = false, const Options & options = {}, SearchLimitType search_limit_type = SearchLimitType::kMoveTime)
Parameters
bot_binary_path Path to the uci engine executable that is going to be run in a new process.
move_time Time limit per move in millis. Right now chess lacks any kind of time control so it is needed to provide at least this. Without any time control, the uci engine behaviour is undefined (e.g. Ethereal searches to depth 1, but Stockfish searches until explicitly stopped)
ponder Boolean indicating whether this bot should make the uci engine ponder (think even when it's opponent's turn). In some engines, this should be accompanied with an options (see param options) so that the engine can adapt time control.
options Additional options to set in the engine. There might be different options available for each engine.
Returns
unique_ptr to a UCIBot
Definition at line 305 of file uci_bot.cc.
{
  return std::make_unique<UCIBot>(bot_binary_path, search_limit_value, ponder,
                                  options, search_limit_type);
}
References options.
Referenced by open_spiel::init_pyspiel_bots().
RandomUciBot()
void open_spiel::uci::RandomUciBot ()
Definition at line 34 of file random_uci_bot.cc.
                    {
  int seed = absl::GetFlag(FLAGS_seed);
  std::mt19937 rng(seed);
  std::unique_ptr<State> state;
  chess::ChessState* chess_state = nullptr;
  std::shared_ptr<const Game> game = LoadGame("chess");
  for (std::string line; std::getline(std::cin, line);) {
    if (line == "uci") {
      std::cout << "uciok" << std::endl;
    } else if (line == "isready") {
      std::cout << "readyok" << std::endl;
    } else if (line == "ucinewgame") {
      state = game->NewInitialState();
      chess_state = down_cast<chess::ChessState*>(state.get());
    } else if (absl::StartsWith(line, "position fen ")) {
      // This command has following syntax:
      // position fen <FEN> moves <MOVES>
      std::vector<std::string> tokens = absl::StrSplit(line, ' ');
      // Build up the <FEN> which can contain spaces.
      std::stringstream fen;
      int pos = 2;
      bool has_moves = false;
      while (pos < tokens.size()) {
        if (tokens[pos] == "moves") {
          has_moves = true;
          break;
        }
        if (pos > 2) fen << ' ';
        fen << tokens[pos];
        ++pos;
      }
      state = game->NewInitialState(fen.str());
      chess_state = down_cast<chess::ChessState*>(state.get());
      if (has_moves) {
        while (pos < tokens.size()) {
          Action action = chess_state->ParseMoveToAction(tokens[pos]);
          state->ApplyAction(action);
          ++pos;
        }
      }
    } else if (absl::StartsWith(line, "go movetime ")) {
      std::vector<Action> legal_actions = state->LegalActions();
      int index = absl::Uniform<int>(rng, 0, legal_actions.size());
      Action action = legal_actions[index];
      chess::Move move = ActionToMove(action, chess_state->Board());
      std::cout << "bestmove " << move.ToLAN() << std::endl;
    } else if (line == "quit") {
      return;
    } else {
      std::cout << "Unrecognized command: " << line << std::endl;
    }
  }
}
References action, open_spiel::chess::ChessState::Board(), open_spiel::down_cast(), absl::GetFlag(), open_spiel::LoadGame(), open_spiel::chess::ChessState::ParseMoveToAction(), absl::StartsWith(), state, absl::StrSplit(), and absl::Uniform().
Referenced by main().