open spiel: open_spiel.python.examples.bridge_wb5 Namespace Reference
open_spiel.python.examples.bridge_wb5 Namespace Reference
Classes
class _WBridge5Client
Functions
net_fn (x)
load_model ()
ai_action (state, net, params)
_run_once (state, bots, net, params)
main (argv)
controller_factory ()
Variables
FLAGS = flags.FLAGS
int NUM_ACTIONS = 38
int MIN_ACTION = 52
Detailed Description
Two BlueChip bridge bots agains simplest open_spiel (take the first possible action).
The bot_cmd FLAG should contain a command-line to launch an external bot, e.g.
`Wbridge5 Autoconnect {port}`.
Function Documentation
_run_once()
open_spiel.python.examples.bridge_wb5._run_once (state, bots, net, params) protected
Plays bots with each other, returns terminal utility for each player.
Definition at line 89 of file bridge_wb5.py.
def _run_once(state, bots, net, params):
  """Plays bots with each other, returns terminal utility for each player."""
  for bot in bots:
    bot.restart()
  while not state.is_terminal():
    if state.is_chance_node():
      outcomes, probs = zip(*state.chance_outcomes())
      state.apply_action(np.random.choice(outcomes, p=probs))
    else:
      if FLAGS.sleep:
        time.sleep(FLAGS.sleep)  # wait for the human to see how it goes
      if state.current_player() % 2 == 1:
        # Have simplest play for now
        action = state.legal_actions()[0]
        if action > 51:
          # TODO(ed2k) extend beyond just bidding
          action = ai_action(state, net, params)
        state.apply_action(action)
      else:
        result = bots[state.current_player() // 2].step(state)
        state.apply_action(result)
  return state
References open_spiel.python.examples.bridge_wb5.ai_action().
Referenced by open_spiel.python.examples.bridge_wb5.main().
ai_action()
open_spiel.python.examples.bridge_wb5.ai_action (state, net, params)
Definition at line 81 of file bridge_wb5.py.
def ai_action(state, net, params):
  observation = np.array(state.observation_tensor(), np.float32)
  policy = np.exp(net.apply(params, observation))
  probs_actions = [(p, a + MIN_ACTION) for a, p in enumerate(policy)]
  pred = max(probs_actions)[1]
  return pred
Referenced by open_spiel.python.examples.bridge_wb5._run_once().
controller_factory()
open_spiel.python.examples.bridge_wb5.controller_factory ()
Implements bluechip_bridge.BlueChipBridgeBot.
Definition at line 137 of file bridge_wb5.py.
def controller_factory():
  """Implements bluechip_bridge.BlueChipBridgeBot."""
  client = _WBridge5Client(FLAGS.bot_cmd)
  client.start()
  return client
load_model()
open_spiel.python.examples.bridge_wb5.load_model ()
Definition at line 74 of file bridge_wb5.py.
def load_model():
  net = hk.without_apply_rng(hk.transform(net_fn))
  params = pickle.load(
      open(os.path.join(FLAGS.params_path, "params-snapshot.pkl"), "rb"))
  return net, params
Referenced by open_spiel.python.examples.bridge_wb5.main().
main()
open_spiel.python.examples.bridge_wb5.main (argv)
Definition at line 113 of file bridge_wb5.py.
def main(argv):
  if len(argv) > 1:
    raise app.UsageError("Too many command-line arguments.")
  game = pyspiel.load_game("bridge(use_double_dummy_result=false)")
  net, params = load_model()
  bots = [
      bluechip_bridge.BlueChipBridgeBot(game, 0, controller_factory),
      bluechip_bridge.BlueChipBridgeBot(game, 2, controller_factory)
  ]
  results = []
  for i_deal in range(FLAGS.num_deals):
    state = _run_once(game.new_initial_state(), bots, net, params)
    print("Deal #{}; final state:\n{}".format(i_deal, state))
    results.append(state.returns())
  stats = np.array(results)
  mean = np.mean(stats, axis=0)
  stderr = np.std(stats, axis=0, ddof=1) / np.sqrt(FLAGS.num_deals)
  print(u"Absolute score: {:+.1f}\u00b1{:.1f}".format(mean[0], stderr[0]))
  print(u"Relative score: {:+.1f}\u00b1{:.1f}".format(mean[1], stderr[1]))
References open_spiel.python.examples.bridge_wb5._run_once(), len, and open_spiel.python.examples.bridge_wb5.load_model().
net_fn()
open_spiel.python.examples.bridge_wb5.net_fn (x)
Haiku module for our network.
Definition at line 57 of file bridge_wb5.py.
def net_fn(x):
  """Haiku module for our network."""
  net = hk.Sequential([
      hk.Linear(1024),
      jax.nn.relu,
      hk.Linear(1024),
      jax.nn.relu,
      hk.Linear(1024),
      jax.nn.relu,
      hk.Linear(1024),
      jax.nn.relu,
      hk.Linear(NUM_ACTIONS),
      jax.nn.log_softmax,
  ])
  return net(x)
Variable Documentation
FLAGS
open_spiel.python.examples.bridge_wb5.FLAGS = flags.FLAGS
Definition at line 40 of file bridge_wb5.py.
MIN_ACTION
int open_spiel.python.examples.bridge_wb5.MIN_ACTION = 52
Definition at line 54 of file bridge_wb5.py.
NUM_ACTIONS
int open_spiel.python.examples.bridge_wb5.NUM_ACTIONS = 38
Definition at line 53 of file bridge_wb5.py.