open spiel: open_spiel.integration_tests.api_test Namespace Reference
open_spiel.integration_tests.api_test Namespace Reference
Classes
class EnforceAPIOnFullTreeBase
class EnforceAPIOnPartialTreeBase
class Relation
Functions
_assert_properties_recursive (state, assert_functions)
_assert_is_perfect_recall (game)
_assert_is_perfect_recall_recursive (state, current_history, infostate_player_to_history)
_create_test_case_classes ()
load_tests (loader, tests, pattern)
main (_)
Variables
FLAGS = flags.FLAGS
_ALL_GAMES = pyspiel.registered_games()
_GAMES_TO_TEST = set([g.short_name for g in _ALL_GAMES if g.default_loadable])
list _GAMES_NOT_UNDER_TEST
_GAMES_TO_OMIT_LEGAL_ACTIONS_CHECK = set(["bridge_uncontested_bidding"])
list _GAMES_FULL_TREE_TRAVERSAL_TESTS
list _GAMES_FULL_TREE_TRAVERSAL_TESTS_NAMES
dict TOTAL_NUM_STATES
dict PERFECT_RECALL_NUM_STATES
Detailed Description
Tests for open_spiel.integration_tests.api.
Function Documentation
_assert_is_perfect_recall()
open_spiel.integration_tests.api_test._assert_is_perfect_recall (game) protected
Raises an AssertionError if the game is not perfect recall.
We are willing to ensure the following property (perfect recall):
- define X_i(h) be the sequence of information states and actions from the
  start of the game observed by player i (i.e. excluding the states and
  actions taken by the opponents unless those actions are included in player
  i's information state), along h but not including the state at h:
     X_i(h) = (s_1, a_1), (s_2, a_2), ... , (s_{t-1}, a_{t-1})
  then player i has perfect recall in this game iff: forall s in S_i,
  forall h1, h2 in s X_i(h1) == X_i(h2). Here, we check that the game has
  perfect recall if this is true for all players i (excluding chance).
  For more detail and context, see page 11 of
  http://mlanctot.info/files/papers/PhD_Thesis_MarcLanctot.pdf
In particular, note that:
- we want to check that holds both for
  + `std::string information_state_string(current_player)`
  + `information_state_tensor`.
- we check that currently only from the point of view of the current
  player at the information state (i.e. we compare
  `prev_state.information_state_string(current_player)` but not
  `prev_state.information_state_string(opponent_player)`
The strategy is the following: we traverse the full tree (of states, not
infostates), and make sure for each node that the history we get for
the infostate associated to that node, that is is unique with respect to
the infostate.
Args:
  game: A Spiel game to check.
Returns:
  The internal cache mapping (infostate_str, player_id) to a list of one
  history leading to this infostate.
Definition at line 451 of file api_test.py.
def _assert_is_perfect_recall(game):
  """Raises an AssertionError if the game is not perfect recall.
  We are willing to ensure the following property (perfect recall):
  - define X_i(h) be the sequence of information states and actions from the
    start of the game observed by player i (i.e. excluding the states and
    actions taken by the opponents unless those actions are included in player
    i's information state), along h but not including the state at h:
       X_i(h) = (s_1, a_1), (s_2, a_2), ... , (s_{t-1}, a_{t-1})
    then player i has perfect recall in this game iff: forall s in S_i,
    forall h1, h2 in s X_i(h1) == X_i(h2). Here, we check that the game has
    perfect recall if this is true for all players i (excluding chance).
    For more detail and context, see page 11 of
    http://mlanctot.info/files/papers/PhD_Thesis_MarcLanctot.pdf
  In particular, note that:
  - we want to check that holds both for
    + `std::string information_state_string(current_player)`
    + `information_state_tensor`.
  - we check that currently only from the point of view of the current
    player at the information state (i.e. we compare
    `prev_state.information_state_string(current_player)` but not
    `prev_state.information_state_string(opponent_player)`
  The strategy is the following: we traverse the full tree (of states, not
  infostates), and make sure for each node that the history we get for
  the infostate associated to that node, that is is unique with respect to
  the infostate.
  Args:
    game: A Spiel game to check.
  Returns:
    The internal cache mapping (infostate_str, player_id) to a list of one
    history leading to this infostate.
  """
  game_info = game.get_type()
  if game_info.dynamics != pyspiel.GameType.Dynamics.SEQUENTIAL:
    raise ValueError("The game is expected to be sequential")
  infostate_player_to_history = {}
  _assert_is_perfect_recall_recursive(
      game.new_initial_state(),
      current_history=[],
      infostate_player_to_history=infostate_player_to_history)
  return infostate_player_to_history
References open_spiel.integration_tests.api_test._assert_is_perfect_recall_recursive().
Referenced by open_spiel.integration_tests.api_test.EnforceAPIOnFullTreeBase.test_game_is_perfect_recall().
_assert_is_perfect_recall_recursive()
open_spiel.integration_tests.api_test._assert_is_perfect_recall_recursive (state, current_history, infostate_player_to_history) protected
Raises an AssertionError if the game is not perfect recall.
The strategy is the following: we traverse the full tree (of states, not
infostates), and make sure for each node that the history we get for
the infostate associated to that node, that is is unique with respect to
the infostate.
Args:
  state: The current state during the recursive tree traversal.
  current_history: The current list of strictly preceding `SpielState` objects
    that lead to the current `state` (excluded).
  infostate_player_to_history: A dictionnary mapping (infostate string
    representation, current_player) to the list of one instance of actual
    predecessor nodes.
Definition at line 501 of file api_test.py.
                                        infostate_player_to_history):
  """Raises an AssertionError if the game is not perfect recall.
  The strategy is the following: we traverse the full tree (of states, not
  infostates), and make sure for each node that the history we get for
  the infostate associated to that node, that is is unique with respect to
  the infostate.
  Args:
    state: The current state during the recursive tree traversal.
    current_history: The current list of strictly preceding `SpielState` objects
      that lead to the current `state` (excluded).
    infostate_player_to_history: A dictionnary mapping (infostate string
      representation, current_player) to the list of one instance of actual
      predecessor nodes.
  """
  if not state.is_chance_node() and not state.is_terminal():
    current_player = state.current_player()
    infostate_str = state.information_state_string(current_player)
    key = (infostate_str, current_player)
    if key not in infostate_player_to_history:
      # First time we see the node.
      infostate_player_to_history[key] = list(current_history)
    else:
      previous_history = infostate_player_to_history[key]
      if len(previous_history) != len(current_history):
        raise AssertionError("We found 2 history leading to the same state:\n"
                             "State: {!r}\n"
                             "InfoState str: {}\n"
                             "First history ({} states): {!r}\n"
                             "Second history ({} states): {!r}\n".format(
                                 state.history(), infostate_str,
                                 len(previous_history),
                                 "|".join([str(sa) for sa in previous_history]),
                                 len(current_history),
                                 "|".join([str(sa) for sa in current_history])))
      # Check for `information_state`
      # pylint: disable=g-complex-comprehension
      expected_infosets_history = [(s.information_state_string(current_player),
                                    a)
                                   for s, a in previous_history
                                   if s.current_player() == current_player]
      # pylint: disable=g-complex-comprehension
      infosets_history = [(s.information_state_string(current_player), a)
                          for s, a in current_history
                          if s.current_player() == current_player]
      if expected_infosets_history != infosets_history:
        # pyformat: disable
        raise AssertionError("We found 2 history leading to the same state:\n"
                             "history: {!r}\n"
                             "info_state str: {}\n"
                             "**First history ({} states)**\n"
                             "states: {!r}\n"
                             "info_sets: {!r}\n"
                             "**Second history ({} states)**\n"
                             "Second info_state history: {!r}\n"
                             "Second history: {!r}\n".format(
                                 state.history(),
                                 infostate_str,
                                 len(previous_history),
                                 "|".join([str(sa) for sa in previous_history]),
                                 expected_infosets_history,
                                 len(current_history), infosets_history,
                                 "|".join([str(sa) for sa in current_history])))
        # pyformat: enable
      # Check for `information_state_tensor`
      expected_infosets_history = [
          (s.information_state_tensor(s.current_player()), a)
          for s, a in previous_history
          if s.current_player() == current_player
      ]
      infosets_history = [(s.information_state_tensor(s.current_player()), a)
                          for s, a in current_history
                          if s.current_player() == current_player]
      if infosets_history != expected_infosets_history:
        raise ValueError("The history as tensor in the same infoset "
                         "are different:\n"
                         "History: {!r}\n".format(state.history()))
  # Recursion
  # TODO(author2): We often use a `give me the next node` function and we
  # probably want a utility method for that, which works for all games.
  if state.is_terminal():
    return
  else:
    for action in state.legal_actions():
      state_for_search = state.child(action)
      _assert_is_perfect_recall_recursive(
          state_for_search,
          current_history=current_history + [(state, action)],
          infostate_player_to_history=infostate_player_to_history)
References open_spiel.integration_tests.api_test._assert_is_perfect_recall_recursive(), and len.
Referenced by open_spiel.integration_tests.api_test._assert_is_perfect_recall(), and open_spiel.integration_tests.api_test._assert_is_perfect_recall_recursive().
_assert_properties_recursive()
open_spiel.integration_tests.api_test._assert_properties_recursive (state, assert_functions) protected
Definition at line 431 of file api_test.py.
def _assert_properties_recursive(state, assert_functions):
  for assert_function in assert_functions:
    assert_function(state)
  # Recursion
  # TODO(author2): We often use a `give me the next node` function and we
  # probably want a utility method for that, which works for all games.
  if state.is_terminal():
    return
  elif state.is_chance_node():
    for action, unused_prob in state.chance_outcomes():
      state_for_search = state.child(action)
      _assert_properties_recursive(state_for_search, assert_functions)
  else:
    for action in state.legal_actions():
      state_for_search = state.child(action)
      _assert_properties_recursive(state_for_search, assert_functions)
References open_spiel.integration_tests.api_test._assert_properties_recursive().
Referenced by open_spiel.integration_tests.api_test._assert_properties_recursive().
_create_test_case_classes()
open_spiel.integration_tests.api_test._create_test_case_classes () protected
Yields one Testing class per game to test.
Definition at line 603 of file api_test.py.
def _create_test_case_classes():
  """Yields one Testing class per game to test."""
  for game_name, game_string in _GAMES_FULL_TREE_TRAVERSAL_TESTS:
    if not re.match(FLAGS.test_only_games, game_string):
      continue
    game = pyspiel.load_game(game_string)
    new_class = type("EnforceAPIFullTree_{}_Test".format(game_name),
                     (EnforceAPIOnFullTreeBase,), {})
    new_class.game_name = game_name
    new_class.game = game
    yield new_class
  for game_name in _GAMES_TO_TEST:
    if not re.match(FLAGS.test_only_games, game_name):
      continue
    game = pyspiel.load_game(game_name)
    new_class = type("EnforceAPIPartialTree_{}_Test".format(game_name),
                     (EnforceAPIOnPartialTreeBase,), {})
    new_class.game_name = game_name
    new_class.game = game
    yield new_class
Referenced by open_spiel.integration_tests.api_test.load_tests().
load_tests()
open_spiel.integration_tests.api_test.load_tests (loader, tests, pattern)
Returns Dynamically created TestSuite.
This creates one TestCase per game to test.
See https://docs.python.org/2/library/unittest.html#load-tests-protocol.
Definition at line 626 of file api_test.py.
def load_tests(loader, tests, pattern):  # pylint: disable=invalid-name,g-doc-args
  """Returns Dynamically created TestSuite.
  This creates one TestCase per game to test.
  See https://docs.python.org/2/library/unittest.html#load-tests-protocol.
  """
  del pattern
  tests = tuple(
      loader.loadTestsFromTestCase(test_case_class)
      for test_case_class in _create_test_case_classes())
  return unittest.TestSuite(tests=tests)
References open_spiel.integration_tests.api_test._create_test_case_classes().
main()
open_spiel.integration_tests.api_test.main (_)
Definition at line 640 of file api_test.py.
def main(_):
  absltest.main()
Variable Documentation
_ALL_GAMES
open_spiel.integration_tests.api_test._ALL_GAMES = pyspiel.registered_games() protected
Definition at line 38 of file api_test.py.
_GAMES_FULL_TREE_TRAVERSAL_TESTS
list open_spiel.integration_tests.api_test._GAMES_FULL_TREE_TRAVERSAL_TESTS protected
Initial value:
=  [
    ("cliff_walking", "cliff_walking(horizon=7)"),
    ("kuhn_poker", "kuhn_poker"),
    ("leduc_poker", "leduc_poker"),
    ("iigoofspiel4", ("turn_based_simultaneous_game(game=goofspiel("
                      "imp_info=True,num_cards=4,points_order=descending))")),
    ("kuhn_poker3p", "kuhn_poker(players=3)"),
    ("first_sealed_auction", "first_sealed_auction(max_value=2)"),
    ("tiny_hanabi", "tiny_hanabi"),
    ("nf_auction", ("turn_based_simultaneous_game(game="
                    "normal_form_extensive_game(game="
                    "first_sealed_auction(max_value=3)))")),
    # Disabled by default - big games, slow tests.
    # Uncomment to check the games if you modify them.
    # ("liars_dice", "liars_dice"),
    # ("tiny_bridge_2p", "tiny_bridge_2p"),
]
Definition at line 50 of file api_test.py.
_GAMES_FULL_TREE_TRAVERSAL_TESTS_NAMES
list open_spiel.integration_tests.api_test._GAMES_FULL_TREE_TRAVERSAL_TESTS_NAMES protected
Initial value:
=  [
    g[1] for g in _GAMES_FULL_TREE_TRAVERSAL_TESTS
]
Definition at line 68 of file api_test.py.
_GAMES_NOT_UNDER_TEST
list open_spiel.integration_tests.api_test._GAMES_NOT_UNDER_TEST protected
Initial value:
=  [
    g.short_name for g in _ALL_GAMES if not g.default_loadable
]
Definition at line 42 of file api_test.py.
_GAMES_TO_OMIT_LEGAL_ACTIONS_CHECK
open_spiel.integration_tests.api_test._GAMES_TO_OMIT_LEGAL_ACTIONS_CHECK = set(["bridge_uncontested_bidding"]) protected
Definition at line 46 of file api_test.py.
_GAMES_TO_TEST
open_spiel.integration_tests.api_test._GAMES_TO_TEST = set([g.short_name for g in _ALL_GAMES if g.default_loadable]) protected
Definition at line 40 of file api_test.py.
FLAGS
open_spiel.integration_tests.api_test.FLAGS = flags.FLAGS
Definition at line 34 of file api_test.py.
PERFECT_RECALL_NUM_STATES
dict open_spiel.integration_tests.api_test.PERFECT_RECALL_NUM_STATES
Initial value:
=  {
    "cliff_walking": 2119,
    "kuhn_poker": 12,
    "leduc_poker": 936,
    "liars_dice": 24576,
    "iigoofspiel4": 162,
    "kuhn_poker3p": 48,
    "first_sealed_auction": 4,
    "tiny_bridge_2p": 3584,
    "tiny_hanabi": 8,
    "nf_auction": 2,
}
Definition at line 88 of file api_test.py.
TOTAL_NUM_STATES
dict open_spiel.integration_tests.api_test.TOTAL_NUM_STATES
Initial value:
=  {
    # This maps the game name to (chance, playable, terminal)
    "cliff_walking": (0, 2119, 6358),
    "kuhn_poker": (4, 24, 30),
    "leduc_poker": (157, 3780, 5520),
    "liars_dice": (7, 147456, 147420),
    "iigoofspiel4": (0, 501, 576),
    "kuhn_poker3p": (17, 288, 312),
    "first_sealed_auction": (12, 10, 14),
    "tiny_bridge_2p": (29, 53760, 53340),
    "tiny_hanabi": (3, 16, 36),
    "nf_auction": (0, 7, 36),
}
Definition at line 72 of file api_test.py.