open spiel: absl::container_internal::memory_internal Namespace Reference
absl::container_internal::memory_internal Namespace Reference
Classes
struct IsLayoutCompatible
struct OffsetOf
struct OffsetOf< Pair, typename std::is_standard_layout< Pair >::type >
struct WithConstructedImplF
Functions
template<class Alloc , class T , class Tuple , size_t... I>
void ConstructFromTupleImpl (Alloc *alloc, T *ptr, Tuple &&t, absl::index_sequence< I... >)
template<class T , class Tuple , size_t... Is, class F >
decltype(std::declval< F >()(std::declval< T >())) WithConstructedImpl (Tuple &&t, absl::index_sequence< Is... >, F &&f)
template<class T , size_t... Is>
auto TupleRefImpl (T &&t, absl::index_sequence< Is... >) -> decltype(std::forward_as_tuple(std::get< Is >(std::forward< T >(t))...))
template<class T >
auto TupleRef (T &&t) -> decltype(TupleRefImpl(std::forward< T >(t), absl::make_index_sequence< std::tuple_size< typename std::decay< T >::type >::value >()))
template<class F , class K , class V >
decltype(std::declval< F >()(std::declval< const K & >(), std::piecewise_construct, std::declval< std::tuple< K > >(), std::declval< V >())) DecomposePairImpl (F &&f, std::pair< std::tuple< K >, V > p)
Function Documentation
ConstructFromTupleImpl()
template<class Alloc , class T , class Tuple , size_t... I> void absl::container_internal::memory_internal::ConstructFromTupleImpl (Alloc * alloc, T * ptr, Tuple && t, absl::index_sequence< I... >)
Definition at line 93 of file container_memory.h.
{
  absl::allocator_traits<Alloc>::construct(
      *alloc, ptr, std::get<I>(std::forward<Tuple>(t))...);
}
References alloc, ConstructFromTupleImpl(), and ptr.
Referenced by ConstructFromTupleImpl().
DecomposePairImpl()
template<class F , class K , class V > decltype(std::declval< F >()(std::declval< const K & >(), std::piecewise_construct, std::declval< std::tuple< K > >(), std::declval< V >())) absl::container_internal::memory_internal::DecomposePairImpl (F && f, std::pair< std::tuple< K >, V > p)
Definition at line 138 of file container_memory.h.
{
  const auto& key = std::get<0>(p.first);
  return std::forward<F>(f)(key, std::piecewise_construct, std::move(p.first),
                            std::move(p.second));
}
References DecomposePairImpl(), absl::f, key, and absl::p.
Referenced by DecomposePairImpl().
TupleRef()
template<class T > auto absl::container_internal::memory_internal::TupleRef (T && t) -> decltype(TupleRefImpl(std::forward<T>(t), absl::make_index_sequence< std::tuple_size<typename std::decay<T>::type>::value>()))
Definition at line 125 of file container_memory.h.
{
  return TupleRefImpl(
      std::forward<T>(t),
      absl::make_index_sequence<
          std::tuple_size<typename std::decay<T>::type>::value>());
}
References TupleRef(), and TupleRefImpl().
Referenced by TupleRef().
TupleRefImpl()
template<class T , size_t... Is> auto absl::container_internal::memory_internal::TupleRefImpl (T && t, absl::index_sequence< Is... >) -> decltype(std::forward_as_tuple(std::get<Is>(std::forward<T>(t))...))
Definition at line 117 of file container_memory.h.
{
  return std::forward_as_tuple(std::get<Is>(std::forward<T>(t))...);
}
References TupleRefImpl().
Referenced by TupleRef(), and TupleRefImpl().
WithConstructedImpl()
template<class T , class Tuple , size_t... Is, class F > decltype(std::declval< F >()(std::declval< T >())) absl::container_internal::memory_internal::WithConstructedImpl (Tuple && t, absl::index_sequence< Is... > , F && f)
Definition at line 110 of file container_memory.h.
{
  return WithConstructedImplF<T, F>{std::forward<F>(f)}(
      std::get<Is>(std::forward<Tuple>(t))...);
}
References absl::f, and WithConstructedImpl().
Referenced by WithConstructedImpl().