open spiel: absl::cord_internal Namespace Reference
absl::cord_internal Namespace Reference
Classes
struct ConstInitExternalStorage
struct CordRep
class CordRepBtree
class CordRepBtreeNavigator
class CordRepBtreeReader
class CordRepBtreeTestPeer
struct CordRepCrc
struct CordRepExternal
struct CordRepExternalImpl
struct CordRepFlat
class CordRepRing
class CordRepRingReader
struct CordRepSubstring
class CordzHandle
class CordzInfo
class CordzSampleToken
class CordzSnapshot
struct CordzStatistics
class CordzUpdateScope
class CordzUpdateTracker
class InlineData
struct Rank0
struct Rank1
class RefcountAndFlags
Typedefs
using ExternalReleaserInvoker = void (*)(CordRepExternal*)
using cordz_info_t = int64_t
using ReadResult = CordRepBtreeNavigator::ReadResult
using ConsumeFn = FunctionRef<void(CordRep*, size_t, size_t)>
Enumerations
enum CordFeatureDefaults { kCordEnableRingBufferDefault = false , kCordShallowSubcordsDefault = false }
enum Constants { kInlinedVectorSize = 47 , kMaxBytesToCopy = 511 }
enum CordRepKind {
UNUSED_0 = 0 , SUBSTRING = 1 , CRC = 2 , BTREE = 3 ,
RING = 4 , EXTERNAL = 5 , FLAT = 6 , MAX_FLAT_TAG = 248
}
enum { kMaxInline = 15 }
Functions
void InitializeCordRepExternal (absl::string_view data, CordRepExternal *rep)
template<typename Releaser >
CordRep * NewExternalRep (absl::string_view data, Releaser &&releaser)
CordRep * NewExternalRep (absl::string_view data, void(&releaser)(absl::string_view))
size_t GetEstimatedMemoryUsage (const CordRep *rep)
size_t GetEstimatedFairShareMemoryUsage (const CordRep *rep)
bool IsDataEdge (const CordRep *edge)
absl::string_view EdgeData (const CordRep *edge)
ABSL_CONST_INIT std::atomic< bool > cord_ring_buffer_enabled (kCordEnableRingBufferDefault)
ABSL_CONST_INIT std::atomic< bool > shallow_subcords_enabled (kCordShallowSubcordsDefault)
ABSL_CONST_INIT std::atomic< bool > cord_btree_exhaustive_validation (false)
void LogFatalNodeType (CordRep *rep)
void enable_cord_ring_buffer (bool enable)
void enable_shallow_subcords (bool enable)
template<bool nullify_tail = false>
void SmallMemmove (char *dst, const char *src, size_t n)
template<typename Releaser , typename = ::absl::base_internal::invoke_result_t< Releaser, absl::string_view>>
void InvokeReleaser (Rank0, Releaser &&releaser, absl::string_view data)
template<typename Releaser , typename = ::absl::base_internal::invoke_result_t<Releaser>>
void InvokeReleaser (Rank1, Releaser &&releaser, absl::string_view)
constexpr char GetOrNull (absl::string_view data, size_t pos)
template<>
void CordRepBtree::Add< CordRepBtree::kBack > (CordRep *rep)
template<>
void CordRepBtree::Add< CordRepBtree::kBack > (absl::Span< CordRep *const > edges)
template<>
void CordRepBtree::Add< CordRepBtree::kFront > (CordRep *rep)
template<>
void CordRepBtree::Add< CordRepBtree::kFront > (absl::Span< CordRep *const > edges)
template CordRepBtree * CordRepBtree::AddCordRep< CordRepBtree::kBack > (CordRepBtree *tree, CordRep *rep)
template CordRepBtree * CordRepBtree::AddCordRep< CordRepBtree::kFront > (CordRepBtree *tree, CordRep *rep)
void Consume (CordRep *rep, ConsumeFn consume_fn)
void ReverseConsume (CordRep *rep, ConsumeFn consume_fn)
CordRep * RemoveCrcNode (CordRep *rep)
CordRep * SkipCrcNode (CordRep *rep)
const CordRep * SkipCrcNode (const CordRep *rep)
constexpr uint8_t AllocatedSizeToTagUnchecked (size_t size)
constexpr size_t TagToAllocatedSize (uint8_t tag)
constexpr size_t RoundUp (size_t n, size_t m)
size_t RoundUpForTag (size_t size)
uint8_t AllocatedSizeToTag (size_t size)
constexpr size_t TagToLength (uint8_t tag)
std::ostream & operator<< (std::ostream &s, const CordRepRing &rep)
int32_t get_cordz_mean_interval ()
void set_cordz_mean_interval (int32_t mean_interval)
bool cordz_should_profile ()
void cordz_set_next_sample_for_testing (int64_t)
void PrintTo (const CordzStatistics &stats, std::ostream *s)
bool operator== (const CordzSampleToken::Iterator &lhs, const CordzSampleToken::Iterator &rhs)
bool operator!= (const CordzSampleToken::Iterator &lhs, const CordzSampleToken::Iterator &rhs)
Variables
std::atomic< bool > cord_ring_buffer_enabled
std::atomic< bool > shallow_subcords_enabled
std::atomic< bool > cord_btree_exhaustive_validation
Typedef Documentation
ConsumeFn
using absl::cord_internal::ConsumeFn = FunctionRef<void(CordRep*, size_t, size_t)>
Definition at line 30 of file cord_rep_consume.h.
cordz_info_t
using absl::cord_internal::cordz_info_t = int64_t
Definition at line 486 of file cord_internal.h.
ExternalReleaserInvoker
using absl::cord_internal::ExternalReleaserInvoker = void (*)(CordRepExternal*)
Definition at line 359 of file cord_internal.h.
ReadResult
using absl::cord_internal::ReadResult = CordRepBtreeNavigator::ReadResult
Definition at line 27 of file cord_rep_btree_navigator.cc.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kMaxInline
Definition at line 474 of file cord_internal.h.
     {
  kMaxInline = 15,
};
Constants
enum absl::cord_internal::Constants
Enumerator
kInlinedVectorSize
kMaxBytesToCopy
Definition at line 86 of file cord_internal.h.
               {
  // The inlined size to use with absl::InlinedVector.
  //
  // Note: The InlinedVectors in this file (and in cord.h) do not need to use
  // the same value for their inlined size. The fact that they do is historical.
  // It may be desirable for each to use a different inlined size optimized for
  // that InlinedVector's usage.
  //
  // TODO(jgm): Benchmark to see if there's a more optimal value than 47 for
  // the inlined vector size (47 exists for backward compatibility).
  kInlinedVectorSize = 47,
  // Prefer copying blocks of at most this size, otherwise reference count.
  kMaxBytesToCopy = 511
};
CordFeatureDefaults
enum absl::cord_internal::CordFeatureDefaults
Enumerator
kCordEnableRingBufferDefault
kCordShallowSubcordsDefault
Definition at line 64 of file cord_internal.h.
{
  kCordEnableRingBufferDefault = false,
  kCordShallowSubcordsDefault = false
};
CordRepKind
enum absl::cord_internal::CordRepKind
Enumerator
UNUSED_0
SUBSTRING
CRC
BTREE
RING
EXTERNAL
FLAT
MAX_FLAT_TAG
Definition at line 229 of file cord_internal.h.
                 {
  UNUSED_0 = 0,
  SUBSTRING = 1,
  CRC = 2,
  BTREE = 3,
  RING = 4,
  EXTERNAL = 5,
  // We have different tags for different sized flat arrays,
  // starting with FLAT, and limited to MAX_FLAT_TAG. The below values map to an
  // allocated range of 32 bytes to 256 KB. The current granularity is:
  // - 8 byte granularity for flat sizes in [32 - 512]
  // - 64 byte granularity for flat sizes in (512 - 8KiB]
  // - 4KiB byte granularity for flat sizes in (8KiB, 256 KiB]
  // If a new tag is needed in the future, then 'FLAT' and 'MAX_FLAT_TAG' should
  // be adjusted as well as the Tag <---> Size mapping logic so that FLAT still
  // represents the minimum flat allocation size. (32 bytes as of now).
  FLAT = 6,
  MAX_FLAT_TAG = 248
};
Function Documentation
AllocatedSizeToTag()
uint8_t absl::cord_internal::AllocatedSizeToTag (size_t size) inline
Definition at line 92 of file cord_rep_flat.h.
{
  const uint8_t tag = AllocatedSizeToTagUnchecked(size);
  assert(tag <= MAX_FLAT_TAG);
  return tag;
}
References AllocatedSizeToTagUnchecked(), MAX_FLAT_TAG, and size.
Referenced by absl::cord_internal::CordRepFlat::NewImpl(), and TEST().
AllocatedSizeToTagUnchecked()
uint8_t absl::cord_internal::AllocatedSizeToTagUnchecked (size_t size) constexpr
Definition at line 55 of file cord_rep_flat.h.
{
  return static_cast<uint8_t>(size <= 512 ? kTagBase + size / 8
                              : size <= 8192
                                  ? kTagBase + 512 / 8 + size / 64 - 512 / 64
                                  : kTagBase + 512 / 8 + ((8192 - 512) / 64) +
                                        size / 4096 - 8192 / 4096);
}
References size.
Referenced by AllocatedSizeToTag().
Consume()
void absl::cord_internal::Consume (CordRep * rep, ConsumeFn consume_fn)
Definition at line 45 of file cord_rep_consume.cc.
{
  size_t offset = 0;
  size_t length = rep->length;
  if (rep->tag == SUBSTRING) {
    offset += rep->substring()->start;
    rep = ClipSubstring(rep->substring());
  }
  consume_fn(rep, offset, length);
}
References absl::cord_internal::CordRep::length, rep, absl::cord_internal::CordRepSubstring::start, SUBSTRING, absl::cord_internal::CordRep::substring(), and absl::cord_internal::CordRep::tag.
Referenced by ReverseConsume().
cord_btree_exhaustive_validation()
ABSL_CONST_INIT std::atomic< bool > absl::cord_internal::cord_btree_exhaustive_validation (false)
cord_ring_buffer_enabled()
ABSL_CONST_INIT std::atomic< bool > absl::cord_internal::cord_ring_buffer_enabled (kCordEnableRingBufferDefault)
CordRepBtree::Add< CordRepBtree::kBack >() [1/2]
template<> void absl::cord_internal::CordRepBtree::Add< CordRepBtree::kBack > (absl::Span< CordRep *const > edges) inline
Definition at line 766 of file cord_rep_btree.h.
{
  AlignBegin();
  size_t new_end = end();
  for (CordRep* edge : edges) edges_[new_end++] = edge;
  set_end(new_end);
}
References end.
CordRepBtree::Add< CordRepBtree::kBack >() [2/2]
template<> void absl::cord_internal::CordRepBtree::Add< CordRepBtree::kBack > (CordRep * rep) inline
Definition at line 760 of file cord_rep_btree.h.
{
  AlignBegin();
  edges_[fetch_add_end(1)] = rep;
}
References rep.
CordRepBtree::Add< CordRepBtree::kFront >() [1/2]
template<> void absl::cord_internal::CordRepBtree::Add< CordRepBtree::kFront > (absl::Span< CordRep *const > edges) inline
Definition at line 781 of file cord_rep_btree.h.
{
  AlignEnd();
  size_t new_begin = begin() - edges.size();
  set_begin(new_begin);
  for (CordRep* edge : edges) edges_[new_begin++] = edge;
}
References begin, and absl::Span< T >::size().
CordRepBtree::Add< CordRepBtree::kFront >() [2/2]
template<> void absl::cord_internal::CordRepBtree::Add< CordRepBtree::kFront > (CordRep * rep) inline
Definition at line 775 of file cord_rep_btree.h.
{
  AlignEnd();
  edges_[sub_fetch_begin(1)] = rep;
}
References rep.
CordRepBtree::AddCordRep< CordRepBtree::kBack >()
template CordRepBtree * absl::cord_internal::CordRepBtree::AddCordRep< CordRepBtree::kBack > (CordRepBtree * tree, CordRep * rep) extern
CordRepBtree::AddCordRep< CordRepBtree::kFront >()
template CordRepBtree * absl::cord_internal::CordRepBtree::AddCordRep< CordRepBtree::kFront > (CordRepBtree * tree, CordRep * rep) extern
cordz_set_next_sample_for_testing()
void absl::cord_internal::cordz_set_next_sample_for_testing (int64_t) inline
Definition at line 69 of file cordz_functions.h.
{}
Referenced by absl::CordzSamplingIntervalHelper::CordzSamplingIntervalHelper(), and absl::CordzSamplingIntervalHelper::~CordzSamplingIntervalHelper().
cordz_should_profile()
bool absl::cord_internal::cordz_should_profile () inline
Definition at line 68 of file cordz_functions.h.
{ return false; }
Referenced by absl::cord_internal::CordzInfo::MaybeTrackCord().
EdgeData()
absl::string_view absl::cord_internal::EdgeData (const CordRep * edge) inline
Definition at line 45 of file cord_data_edge.h.
{
  assert(IsDataEdge(edge));
  size_t offset = 0;
  const size_t length = edge->length;
  if (edge->IsSubstring()) {
    offset = edge->substring()->start;
    edge = edge->substring()->child;
  }
  return edge->tag >= FLAT
             ? absl::string_view{edge->flat()->Data() + offset, length}
             : absl::string_view{edge->external()->base + offset, length};
}
References absl::cord_internal::CordRepExternal::base, absl::cord_internal::CordRepSubstring::child, absl::cord_internal::CordRepFlat::Data(), absl::cord_internal::CordRep::external(), FLAT, absl::cord_internal::CordRep::flat(), IsDataEdge(), absl::cord_internal::CordRep::IsSubstring(), absl::cord_internal::CordRep::length, absl::cord_internal::CordRepSubstring::start, absl::cord_internal::CordRep::substring(), and absl::cord_internal::CordRep::tag.
Referenced by absl::cord_internal::CordRepBtree::Data(), absl::cord_internal::CordRepBtreeReader::Init(), absl::cord_internal::CordRepBtree::IsFlat(), absl::cord_internal::CordRepBtreeReader::Next(), absl::cord_internal::CordRepBtreeReader::Read(), absl::cord_internal::CordRepBtreeReader::Seek(), and absl::cord_internal::CordRepBtreeReader::Skip().
enable_cord_ring_buffer()
void absl::cord_internal::enable_cord_ring_buffer (bool enable) inline
Definition at line 78 of file cord_internal.h.
{
  cord_ring_buffer_enabled.store(enable, std::memory_order_relaxed);
}
References cord_ring_buffer_enabled.
enable_shallow_subcords()
void absl::cord_internal::enable_shallow_subcords (bool enable) inline
Definition at line 82 of file cord_internal.h.
{
  shallow_subcords_enabled.store(enable, std::memory_order_relaxed);
}
References shallow_subcords_enabled.
get_cordz_mean_interval()
int32_t absl::cord_internal::get_cordz_mean_interval ()
Definition at line 86 of file cordz_functions.cc.
{
  return g_cordz_mean_interval.load(std::memory_order_acquire);
}
GetEstimatedFairShareMemoryUsage()
size_t absl::cord_internal::GetEstimatedFairShareMemoryUsage (const CordRep * rep)
Definition at line 182 of file cord_analysis.cc.
{
  return GetEstimatedUsage<Mode::kFairShare>(rep);
}
References rep.
Referenced by absl::Cord::EstimatedMemoryUsage().
GetEstimatedMemoryUsage()
size_t absl::cord_internal::GetEstimatedMemoryUsage (const CordRep * rep)
Definition at line 178 of file cord_analysis.cc.
{
  return GetEstimatedUsage<Mode::kTotal>(rep);
}
References rep.
Referenced by absl::Cord::EstimatedMemoryUsage().
GetOrNull()
char absl::cord_internal::GetOrNull (absl::string_view data, size_t pos) constexpr
Definition at line 478 of file cord_internal.h.
{
  return pos < data.size() ? data[pos] : '\0';
}
InitializeCordRepExternal()
void absl::cord_internal::InitializeCordRepExternal (absl::string_view data, CordRepExternal * rep)
Definition at line 123 of file cord.cc.
{
  assert(!data.empty());
  rep->length = data.size();
  rep->tag = EXTERNAL;
  rep->base = data.data();
  VerifyTree(rep);
}
References EXTERNAL, absl::cord_internal::CordRep::length, rep, and absl::cord_internal::CordRep::tag.
Referenced by NewExternalRep().
InvokeReleaser() [1/2]
template<typename Releaser , typename = ::absl::base_internal::invoke_result_t< Releaser, absl::string_view>> void absl::cord_internal::InvokeReleaser (Rank0 , Releaser && releaser, absl::string_view data)
Definition at line 384 of file cord_internal.h.
{
  ::absl::base_internal::invoke(std::forward<Releaser>(releaser), data);
}
References absl::base_internal::invoke().
Referenced by absl::cord_internal::CordRepExternalImpl< Releaser >::~CordRepExternalImpl().
InvokeReleaser() [2/2]
template<typename Releaser , typename = ::absl::base_internal::invoke_result_t<Releaser>> void absl::cord_internal::InvokeReleaser (Rank1 , Releaser && releaser, absl::string_view)
Definition at line 390 of file cord_internal.h.
{
  ::absl::base_internal::invoke(std::forward<Releaser>(releaser));
}
References absl::base_internal::invoke().
IsDataEdge()
bool absl::cord_internal::IsDataEdge (const CordRep * edge) inline
Definition at line 32 of file cord_data_edge.h.
{
  assert(edge != nullptr);
  // The fast path is that `edge` is an EXTERNAL or FLAT node, making the below
  // if a single, well predicted branch. We then repeat the FLAT or EXTERNAL
  // check in the slow path of the SUBSTRING check to optimize for the hot path.
  if (edge->tag == EXTERNAL || edge->tag >= FLAT) return true;
  if (edge->tag == SUBSTRING) edge = edge->substring()->child;
  return edge->tag == EXTERNAL || edge->tag >= FLAT;
}
References absl::cord_internal::CordRepSubstring::child, EXTERNAL, FLAT, SUBSTRING, absl::cord_internal::CordRep::substring(), and absl::cord_internal::CordRep::tag.
Referenced by absl::cord_internal::CordRepBtree::Append(), absl::cord_internal::CordRepBtree::Create(), EdgeData(), absl::cord_internal::CordRepBtree::IsValid(), and absl::cord_internal::CordRepBtree::Prepend().
LogFatalNodeType()
ABSL_ATTRIBUTE_NORETURN void absl::cord_internal::LogFatalNodeType (CordRep * rep)
Definition at line 38 of file cord_internal.cc.
{
  ABSL_INTERNAL_LOG(FATAL, absl::StrCat("Unexpected node type: ",
                                        static_cast<int>(rep->tag)));
}
References ABSL_INTERNAL_LOG, rep, absl::StrCat(), and absl::cord_internal::CordRep::tag.
Referenced by absl::cord_internal::CordRepSubstring::Create().
NewExternalRep() [1/2]
template<typename Releaser > CordRep * absl::cord_internal::NewExternalRep (absl::string_view data, Releaser && releaser)
Definition at line 1033 of file cord.h.
{
  assert(!data.empty());
  using ReleaserType = absl::decay_t<Releaser>;
  CordRepExternal* rep = new CordRepExternalImpl<ReleaserType>(
      std::forward<Releaser>(releaser), 0);
  InitializeCordRepExternal(data, rep);
  return rep;
}
References InitializeCordRepExternal(), and rep.
Referenced by NewExternalRep().
NewExternalRep() [2/2]
CordRep * absl::cord_internal::NewExternalRep (absl::string_view data, void(&)(absl::string_view) releaser) inline
Definition at line 1045 of file cord.h.
{
  return NewExternalRep(data, &releaser);
}
References NewExternalRep().
operator!=()
bool absl::cord_internal::operator!= (const CordzSampleToken::Iterator & lhs, const CordzSampleToken::Iterator & rhs)
Definition at line 44 of file cordz_sample_token.cc.
{
  return !(lhs == rhs);
}
operator<<()
std::ostream & absl::cord_internal::operator<< (std::ostream & s, const CordRepRing & rep)
Definition at line 81 of file cord_rep_ring.cc.
{
  // Note: 'pos' values are defined as size_t (for overflow reasons), but that
  // prints really awkward for small prepended values such as -5. ssize_t is not
  // portable (POSIX), so we use ptrdiff_t instead to cast to signed values.
  s << "  CordRepRing(" << &rep << ", length = " << rep.length
    << ", head = " << rep.head_ << ", tail = " << rep.tail_
    << ", cap = " << rep.capacity_ << ", rc = " << rep.refcount.Get()
    << ", begin_pos_ = " << static_cast<ptrdiff_t>(rep.begin_pos_) << ") {\n";
  CordRepRing::index_type head = rep.head();
  do {
    CordRep* child = rep.entry_child(head);
    s << " entry[" << head << "] length = " << rep.entry_length(head)
      << ", child " << child << ", clen = " << child->length
      << ", tag = " << static_cast<int>(child->tag)
      << ", rc = " << child->refcount.Get()
      << ", offset = " << rep.entry_data_offset(head)
      << ", end_pos = " << static_cast<ptrdiff_t>(rep.entry_end_pos(head))
      << "\n";
    head = rep.advance(head);
  } while (head != rep.tail());
  return s << "}\n";
}
operator==()
bool absl::cord_internal::operator== (const CordzSampleToken::Iterator & lhs, const CordzSampleToken::Iterator & rhs)
Definition at line 38 of file cordz_sample_token.cc.
{
  return lhs.current_ == rhs.current_ &&
         (lhs.current_ == nullptr || lhs.token_ == rhs.token_);
}
PrintTo()
void absl::cord_internal::PrintTo (const CordzStatistics & stats, std::ostream * s) inline
Definition at line 42 of file cordz_info_statistics_test.cc.
{
  if (s) *s << "CordzStatistics{...}";
}
References absl::s.
RemoveCrcNode()
CordRep * absl::cord_internal::RemoveCrcNode (CordRep * rep) inline
Definition at line 54 of file cord_rep_crc.h.
{
  assert(rep != nullptr);
  if (ABSL_PREDICT_FALSE(rep->IsCrc())) {
    CordRep* child = rep->crc()->child;
    if (rep->refcount.IsOne()) {
      delete rep->crc();
    } else {
      CordRep::Ref(child);
      CordRep::Unref(rep);
    }
    return child;
  }
  return rep;
}
References ABSL_PREDICT_FALSE, absl::cord_internal::CordRepCrc::child, absl::cord_internal::CordRep::crc(), absl::cord_internal::CordRep::IsCrc(), absl::cord_internal::RefcountAndFlags::IsOne(), absl::cord_internal::CordRep::Ref(), absl::cord_internal::CordRep::refcount, rep, and absl::cord_internal::CordRep::Unref().
Referenced by absl::Cord::Prepend(), absl::Cord::RemovePrefix(), and absl::Cord::RemoveSuffix().
ReverseConsume()
void absl::cord_internal::ReverseConsume (CordRep * rep, ConsumeFn consume_fn)
Definition at line 56 of file cord_rep_consume.cc.
{
  return Consume(rep, std::move(consume_fn));
}
References Consume(), and rep.
RoundUp()
size_t absl::cord_internal::RoundUp (size_t n, size_t m) constexpr
Definition at line 78 of file cord_rep_flat.h.
{
  return (n + m - 1) & (0 - m);
}
References absl::n.
Referenced by RoundUpForTag().
RoundUpForTag()
size_t absl::cord_internal::RoundUpForTag (size_t size) inline
Definition at line 84 of file cord_rep_flat.h.
{
  return RoundUp(size, (size <= 512) ? 8 : (size <= 8192 ? 64 : 4096));
}
References RoundUp(), and size.
Referenced by absl::cord_internal::CordRepFlat::NewImpl(), and TEST().
set_cordz_mean_interval()
void absl::cord_internal::set_cordz_mean_interval (int32_t mean_interval)
Definition at line 90 of file cordz_functions.cc.
{
  g_cordz_mean_interval.store(mean_interval, std::memory_order_release);
}
Referenced by absl::CordzSamplingIntervalHelper::CordzSamplingIntervalHelper(), and absl::CordzSamplingIntervalHelper::~CordzSamplingIntervalHelper().
shallow_subcords_enabled()
ABSL_CONST_INIT std::atomic< bool > absl::cord_internal::shallow_subcords_enabled (kCordShallowSubcordsDefault)
SkipCrcNode() [1/2]
const CordRep * absl::cord_internal::SkipCrcNode (const CordRep * rep) inline
Definition at line 80 of file cord_rep_crc.h.
{
  assert(rep != nullptr);
  if (ABSL_PREDICT_FALSE(rep->IsCrc())) {
    return rep->crc()->child;
  } else {
    return rep;
  }
}
References ABSL_PREDICT_FALSE, absl::cord_internal::CordRepCrc::child, absl::cord_internal::CordRep::crc(), absl::cord_internal::CordRep::IsCrc(), and rep.
SkipCrcNode() [2/2]
CordRep * absl::cord_internal::SkipCrcNode (CordRep * rep) inline
Definition at line 71 of file cord_rep_crc.h.
{
  assert(rep != nullptr);
  if (ABSL_PREDICT_FALSE(rep->IsCrc())) {
    return rep->crc()->child;
  } else {
    return rep;
  }
}
References ABSL_PREDICT_FALSE, absl::cord_internal::CordRepCrc::child, absl::cord_internal::CordRep::crc(), absl::cord_internal::CordRep::IsCrc(), and rep.
Referenced by absl::CordTestPeer::MakeSubstring(), absl::Cord::operator[](), and absl::Cord::Subcord().
SmallMemmove()
template<bool nullify_tail = false> void absl::cord_internal::SmallMemmove (char * dst, const char * src, size_t n) inline
Definition at line 109 of file cord_internal.h.
{
  if (n >= 8) {
    assert(n <= 15);
    uint64_t buf1;
    uint64_t buf2;
    memcpy(&buf1, src, 8);
    memcpy(&buf2, src + n - 8, 8);
    if (nullify_tail) {
      memset(dst + 7, 0, 8);
    }
    memcpy(dst, &buf1, 8);
    memcpy(dst + n - 8, &buf2, 8);
  } else if (n >= 4) {
    uint32_t buf1;
    uint32_t buf2;
    memcpy(&buf1, src, 4);
    memcpy(&buf2, src + n - 4, 4);
    if (nullify_tail) {
      memset(dst + 4, 0, 4);
      memset(dst + 7, 0, 8);
    }
    memcpy(dst, &buf1, 4);
    memcpy(dst + n - 4, &buf2, 4);
  } else {
    if (n != 0) {
      dst[0] = src[0];
      dst[n / 2] = src[n / 2];
      dst[n - 1] = src[n - 1];
    }
    if (nullify_tail) {
      memset(dst + 7, 0, 8);
      memset(dst + n, 0, 8);
    }
  }
}
References absl::n.
Referenced by absl::cord_internal::InlineData::set_inline_data(), and absl::Cord::Subcord().
TagToAllocatedSize()
size_t absl::cord_internal::TagToAllocatedSize (uint8_t tag) constexpr
Definition at line 64 of file cord_rep_flat.h.
{
  return (tag <= kTagBase + 512 / 8) ? tag * 8 - kTagBase * 8
         : (tag <= kTagBase + (512 / 8) + ((8192 - 512) / 64))
             ? 512 + tag * 64 - kTagBase * 64 - 512 / 8 * 64
             : 8192 + tag * 4096 - kTagBase * 4096 -
                   ((512 / 8) + ((8192 - 512) / 64)) * 4096;
}
Referenced by absl::cord_internal::CordRepFlat::AllocatedSize(), absl::cord_internal::CordRepFlat::Delete(), TagToLength(), and TEST().
TagToLength()
size_t absl::cord_internal::TagToLength (uint8_t tag) constexpr
Definition at line 99 of file cord_rep_flat.h.
{
  return TagToAllocatedSize(tag) - kFlatOverhead;
}
References TagToAllocatedSize().
Referenced by absl::cord_internal::CordRepFlat::Capacity().
Variable Documentation
cord_btree_exhaustive_validation
std::atomic<bool> absl::cord_internal::cord_btree_exhaustive_validation extern
cord_ring_buffer_enabled
std::atomic<bool> absl::cord_internal::cord_ring_buffer_enabled extern
Referenced by enable_cord_ring_buffer().
shallow_subcords_enabled
std::atomic<bool> absl::cord_internal::shallow_subcords_enabled extern
Referenced by enable_shallow_subcords().