open spiel: absl::log_internal Namespace Reference
absl::log_internal Namespace Reference
Namespaces
namespace detect_specialization
Classes
class AsLiteralImpl
class CheckOpMessageBuilder
class LogEntryTestPeer
class LogEveryNSecState
class LogEveryNState
class LogEveryPow2State
class LogFirstNState
class LogMessage
class LogMessageFatal
class LogMessageQuietlyFatal
class LogTestEnvironment
struct NullGuard
struct NullGuard< char * >
struct NullGuard< const char * >
struct NullGuard< const signed char * >
struct NullGuard< const unsigned char * >
struct NullGuard< signed char * >
struct NullGuard< std::nullptr_t >
struct NullGuard< unsigned char * >
class NullStream
class NullStreamFatal
class NullStreamMaybeFatal
class ProtoField
class ScopedMinLogLevel
class StringifySink
class Voidify
struct WriteEntryToStderr
struct WriteToStderr
struct WriteToStderrWithFilename
Typedefs
using LoggingGlobalsListener = void (*)()
template<typename T >
using CheckOpStreamType = decltype(detect_specialization::Detect<T>(0))
using Tid = pid_t
Enumerations
enum class PrefixFormat { kNotRaw , kRaw }
enum class WireType : uint64_t { kVarint = 0 , k64Bit = 1 , kLengthDelimited = 2 , k32Bit = 5 }
Functions
void DieBecauseNull (const char *file, int line, const char *exprtext)
template<typename T >
ABSL_MUST_USE_RESULT T DieIfNull (const char *file, int line, const char *exprtext, T &&t)
void RawSetMinLogLevel (absl::LogSeverityAtLeast severity)
void RawSetStderrThreshold (absl::LogSeverityAtLeast severity)
void RawEnableLogPrefix (bool on_off)
void SetLoggingGlobalsListener (LoggingGlobalsListener l)
bool ShouldLogBacktraceAt (absl::string_view file, int line)
size_t AppendTruncated (absl::string_view src, absl::Span< char > &dst)
size_t AppendTruncated (char c, size_t n, absl::Span< char > &dst)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (bool)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (int64_t)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (uint64_t)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (float)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (double)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (char)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (unsigned char)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const std::string &)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const absl::string_view &)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const char *)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const signed char *)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const unsigned char *)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const void *)
void MakeCheckOpValueString (std::ostream &os, const char v)
void MakeCheckOpValueString (std::ostream &os, const signed char v)
void MakeCheckOpValueString (std::ostream &os, const unsigned char v)
void MakeCheckOpValueString (std::ostream &os, const void *p)
const absl::Status * AsStatus (const absl::Status &s)
template<typename T >
const absl::Status * AsStatus (const absl::StatusOr< T > &s)
template<typename T >
void MakeCheckOpValueString (std::ostream &os, const T &v)
template<typename T1 , typename T2 >
ABSL_ATTRIBUTE_RETURNS_NONNULL std::string * MakeCheckOpString (T1 v1, T2 v2, const char *exprtext) ABSL_ATTRIBUTE_NOINLINE
template<typename T1 , typename T2 >
std::string * MakeCheckOpString (T1 v1, T2 v2, const char *exprtext)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (bool)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (int64_t)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (uint64_t)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (float)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (double)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (char)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (unsigned char)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const std::string &)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const absl::string_view &)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const char *)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const signed char *)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const unsigned char *)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const void *)
std::string * CheckstrcmptrueImpl (const char *s1, const char *s2, const char *exprtext)
std::string * CheckstrcmpfalseImpl (const char *s1, const char *s2, const char *exprtext)
std::string * CheckstrcasecmptrueImpl (const char *s1, const char *s2, const char *exprtext)
std::string * CheckstrcasecmpfalseImpl (const char *s1, const char *s2, const char *exprtext)
template<typename T >
constexpr const T & GetReferenceableValue (const T &t)
constexpr char GetReferenceableValue (char t)
constexpr unsigned char GetReferenceableValue (unsigned char t)
constexpr signed char GetReferenceableValue (signed char t)
constexpr short GetReferenceableValue (short t)
constexpr unsigned short GetReferenceableValue (unsigned short t)
constexpr int GetReferenceableValue (int t)
unsigned int GetReferenceableValue (unsigned int t)
constexpr long GetReferenceableValue (long t)
constexpr unsigned long GetReferenceableValue (unsigned long t)
constexpr long long GetReferenceableValue (long long t)
constexpr unsigned long long GetReferenceableValue (unsigned long long t)
ABSL_ATTRIBUTE_NORETURN void AbortQuietly ()
ABSL_ATTRIBUTE_NORETURN void ExitQuietly ()
bool IsInitialized ()
void SetInitialized ()
void WriteToStderr (absl::string_view message, absl::LogSeverity severity)
void SetTimeZone (absl::TimeZone tz)
const absl::TimeZone * TimeZone ()
bool ShouldSymbolizeLogStackTrace ()
void EnableSymbolizeLogStackTrace (bool on_off)
int MaxFramesInLogStackTrace ()
void SetMaxFramesInLogStackTrace (int max_num_frames)
bool ExitOnDFatal ()
void SetExitOnDFatal (bool on_off)
bool SuppressSigabortTrace ()
bool SetSuppressSigabortTrace (bool on_off)
std::string FormatLogMessage (absl::LogSeverity severity, absl::CivilSecond civil_second, absl::Duration subsecond, log_internal::Tid tid, absl::string_view basename, int line, PrefixFormat format, absl::string_view message)
size_t FormatLogPrefix (absl::LogSeverity severity, absl::Time timestamp, log_internal::Tid tid, absl::string_view basename, int line, PrefixFormat format, absl::Span< char > &buf)
bool ThreadIsLoggingToLogSink ()
void LogToSinks (const absl::LogEntry &entry, absl::Span< absl::LogSink * > extra_sinks, bool extra_sinks_only)
void AddLogSink (absl::LogSink *sink)
void RemoveLogSink (absl::LogSink *sink)
void FlushLogSinks ()
template<typename T >
NullStream & operator<< (NullStream &str, const T &)
NullStream & operator<< (NullStream &str, std::ostream &(*)(std::ostream &os))
NullStream & operator<< (NullStream &str, std::ios_base &(*)(std::ios_base &os))
bool EncodeVarint (uint64_t tag, uint64_t value, absl::Span< char > *buf)
bool Encode64Bit (uint64_t tag, uint64_t value, absl::Span< char > *buf)
bool Encode32Bit (uint64_t tag, uint32_t value, absl::Span< char > *buf)
bool EncodeBytes (uint64_t tag, absl::Span< const char > value, absl::Span< char > *buf)
bool EncodeBytesTruncate (uint64_t tag, absl::Span< const char > value, absl::Span< char > *buf)
ABSL_MUST_USE_RESULT absl::Span< char > EncodeMessageStart (uint64_t tag, uint64_t max_size, absl::Span< char > *buf)
void EncodeMessageLength (absl::Span< char > msg, const absl::Span< char > *buf)
bool EncodeVarint (uint64_t tag, int64_t value, absl::Span< char > *buf)
bool EncodeVarint (uint64_t tag, uint32_t value, absl::Span< char > *buf)
bool EncodeVarint (uint64_t tag, int32_t value, absl::Span< char > *buf)
bool EncodeVarintZigZag (uint64_t tag, int64_t value, absl::Span< char > *buf)
bool Encode64Bit (uint64_t tag, int64_t value, absl::Span< char > *buf)
bool Encode64Bit (uint64_t tag, uint32_t value, absl::Span< char > *buf)
bool Encode64Bit (uint64_t tag, int32_t value, absl::Span< char > *buf)
bool EncodeDouble (uint64_t tag, double value, absl::Span< char > *buf)
bool Encode32Bit (uint64_t tag, int32_t value, absl::Span< char > *buf)
bool EncodeFloat (uint64_t tag, float value, absl::Span< char > *buf)
bool EncodeString (uint64_t tag, absl::string_view value, absl::Span< char > *buf)
bool EncodeStringTruncate (uint64_t tag, absl::string_view value, absl::Span< char > *buf)
constexpr size_t VarintSize (uint64_t value)
constexpr size_t MinVarintSize ()
constexpr size_t MaxVarintSize ()
constexpr uint64_t MaxVarintForSize (size_t size)
constexpr size_t BufferSizeFor ()
template<typename... T>
constexpr size_t BufferSizeFor (WireType type, T... tail)
WriteEntryToStderr DeathTestExpectedLogging ()
WriteEntryToStderr DeathTestUnexpectedLogging ()
bool LoggingEnabledAt (absl::LogSeverity severity)
Matcher< absl::string_view > AsString (const Matcher< const std::string & > &str_matcher)
Matcher< const absl::LogEntry & > SourceFilename (const Matcher< absl::string_view > &source_filename)
Matcher< const absl::LogEntry & > SourceBasename (const Matcher< absl::string_view > &source_basename)
Matcher< const absl::LogEntry & > SourceLine (const Matcher< int > &source_line)
Matcher< const absl::LogEntry & > Prefix (const Matcher< bool > &prefix)
Matcher< const absl::LogEntry & > LogSeverity (const Matcher< absl::LogSeverity > &log_severity)
Matcher< const absl::LogEntry & > Timestamp (const Matcher< absl::Time > &timestamp)
Matcher< const absl::LogEntry & > TimestampInMatchWindow ()
Matcher< const absl::LogEntry & > ThreadID (const Matcher< absl::LogEntry::tid_t > &tid)
Matcher< const absl::LogEntry & > TextMessageWithPrefixAndNewline (const Matcher< absl::string_view > &text_message_with_prefix_and_newline)
Matcher< const absl::LogEntry & > TextMessageWithPrefix (const Matcher< absl::string_view > &text_message_with_prefix)
Matcher< const absl::LogEntry & > TextMessage (const Matcher< absl::string_view > &text_message)
Matcher< const absl::LogEntry & > TextPrefix (const Matcher< absl::string_view > &text_prefix)
Matcher< const absl::LogEntry & > RawEncodedMessage (const Matcher< absl::string_view > &raw_encoded_message)
Matcher< const absl::LogEntry & > Verbosity (const Matcher< int > &verbosity)
Matcher< const absl::LogEntry & > Stacktrace (const Matcher< absl::string_view > &stacktrace)
Matcher< absl::string_view > MatchesOstream (const std::ostringstream &stream)
Matcher< const std::string & > DeathTestValidateExpectations ()
::testing::Matcher< absl::string_view > AsString (const ::testing::Matcher< const std::string & > &str_matcher)
::testing::Matcher< const absl::LogEntry & > SourceFilename (const ::testing::Matcher< absl::string_view > &source_filename)
::testing::Matcher< const absl::LogEntry & > SourceBasename (const ::testing::Matcher< absl::string_view > &source_basename)
::testing::Matcher< const absl::LogEntry & > SourceLine (const ::testing::Matcher< int > &source_line)
::testing::Matcher< const absl::LogEntry & > Prefix (const ::testing::Matcher< bool > &prefix)
::testing::Matcher< const absl::LogEntry & > LogSeverity (const ::testing::Matcher< absl::LogSeverity > &log_severity)
::testing::Matcher< const absl::LogEntry & > Timestamp (const ::testing::Matcher< absl::Time > &timestamp)
::testing::Matcher< const absl::LogEntry & > ThreadID (const ::testing::Matcher< absl::LogEntry::tid_t > &)
::testing::Matcher< const absl::LogEntry & > TextMessageWithPrefixAndNewline (const ::testing::Matcher< absl::string_view > &text_message_with_prefix_and_newline)
::testing::Matcher< const absl::LogEntry & > TextMessageWithPrefix (const ::testing::Matcher< absl::string_view > &text_message_with_prefix)
::testing::Matcher< const absl::LogEntry & > TextMessage (const ::testing::Matcher< absl::string_view > &text_message)
::testing::Matcher< const absl::LogEntry & > TextPrefix (const ::testing::Matcher< absl::string_view > &text_prefix)
::testing::Matcher< const absl::LogEntry & > Verbosity (const ::testing::Matcher< int > &verbosity)
::testing::Matcher< const absl::LogEntry & > Stacktrace (const ::testing::Matcher< absl::string_view > &stacktrace)
::testing::Matcher< const absl::LogEntry & > RawEncodedMessage (const ::testing::Matcher< absl::string_view > &raw_encoded_message)
Variables
constexpr int kLogMessageBufferSize = 15000
ABSL_DLL ABSL_CONST_INIT const std::array< char, 7 > kCharNull
ABSL_DLL ABSL_CONST_INIT const std::array< signed char, 7 > kSignedCharNull
ABSL_DLL ABSL_CONST_INIT const std::array< unsigned char, 7 > kUnsignedCharNull
constexpr auto kAbslMinLogLevel
Typedef Documentation
CheckOpStreamType
template<typename T > using absl::log_internal::CheckOpStreamType = decltype(detect_specialization::Detect<T>(0))
Definition at line 283 of file check_op.h.
LoggingGlobalsListener
using absl::log_internal::LoggingGlobalsListener = void (*)()
Definition at line 150 of file globals.h.
Tid
using absl::log_internal::Tid = pid_t
Definition at line 38 of file config.h.
Enumeration Type Documentation
PrefixFormat
enum class absl::log_internal::PrefixFormat strong
Enumerator
kNotRaw
kRaw
Definition at line 41 of file log_format.h.
{
  kNotRaw,
  kRaw,
};
WireType
enum class absl::log_internal::WireType : uint64_t strong
Enumerator
kVarint
k64Bit
kLengthDelimited
k32Bit
Definition at line 181 of file proto.h.
                    : uint64_t {
  kVarint = 0,
  k64Bit = 1,
  kLengthDelimited = 2,
  k32Bit = 5,
};
Function Documentation
AbortQuietly()
ABSL_ATTRIBUTE_NORETURN void absl::log_internal::AbortQuietly () inline
Definition at line 216 of file conditions.h.
{ abort(); }
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [1/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (bool)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [2/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (char)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [3/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const absl::string_view &)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [4/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const char *)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [5/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const signed char *)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [6/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const std::string &)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [7/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const unsigned char *)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [8/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (const void *)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [9/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (double)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [10/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (float)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [11/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (int64_t)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [12/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (uint64_t)
ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN() [13/13]
absl::log_internal::ABSL_LOG_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING_EXTERN (unsigned char)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [1/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (bool)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [2/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (char)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [3/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const absl::string_view &)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [4/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const char *)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [5/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const signed char *)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [6/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const std::string &)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [7/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const unsigned char *)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [8/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (const void *)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [9/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (double)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [10/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (float)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [11/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (int64_t)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [12/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (uint64_t)
ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING() [13/13]
absl::log_internal::ABSL_LOGGING_INTERNAL_DEFINE_MAKE_CHECK_OP_STRING (unsigned char)
AddLogSink()
void absl::log_internal::AddLogSink (absl::LogSink * sink)
Definition at line 284 of file log_sink_set.cc.
{
  log_internal::GlobalSinks().AddLogSink(sink);
}
References sink.
Referenced by absl::AddLogSink().
AppendTruncated() [1/2]
size_t absl::log_internal::AppendTruncated (absl::string_view src, absl::Span< char > & dst) inline
Definition at line 30 of file append_truncated.h.
{
  if (src.size() > dst.size()) src = src.substr(0, dst.size());
  memcpy(dst.data(), src.data(), src.size());
  dst.remove_prefix(src.size());
  return src.size();
}
References absl::Span< T >::data(), absl::string_view::data(), absl::Span< T >::remove_prefix(), absl::Span< T >::size(), absl::string_view::size(), and absl::string_view::substr().
Referenced by FormatLogPrefix(), and absl::log_internal::LogEntryTestPeer::LogEntryTestPeer().
AppendTruncated() [2/2]
size_t absl::log_internal::AppendTruncated (char c, size_t n, absl::Span< char > & dst) inline
Definition at line 37 of file append_truncated.h.
{
  if (n > dst.size()) n = dst.size();
  memset(dst.data(), c, n);
  dst.remove_prefix(n);
  return n;
}
References absl::c, absl::Span< T >::data(), absl::n, absl::Span< T >::remove_prefix(), and absl::Span< T >::size().
AsStatus() [1/2]
const absl::Status * absl::log_internal::AsStatus (const absl::Status & s) inline
Definition at line 164 of file check_op.h.
{ return &s; }
References absl::s.
AsStatus() [2/2]
template<typename T > const absl::Status * absl::log_internal::AsStatus (const absl::StatusOr< T > & s)
Definition at line 166 of file check_op.h.
{
  return &s.status();
}
References absl::s.
AsString() [1/2]
::testing::Matcher< absl::string_view > absl::log_internal::AsString (const ::testing::Matcher< const std::string & > & str_matcher)
AsString() [2/2]
Matcher< absl::string_view > absl::log_internal::AsString (const Matcher< const std::string & > & str_matcher)
Definition at line 97 of file test_matchers.cc.
{
  return MakeMatcher(new AsStringImpl(str_matcher));
}
BufferSizeFor() [1/2]
size_t absl::log_internal::BufferSizeFor () constexpr
Definition at line 210 of file proto.h.
{ return 0; }
Referenced by BufferSizeFor().
BufferSizeFor() [2/2]
template<typename... T> size_t absl::log_internal::BufferSizeFor (WireType type, T... tail) constexpr
Definition at line 212 of file proto.h.
{
  // tag_type + data + ...
  return MaxVarintSize() +
         (type == WireType::kVarint ? MaxVarintSize() :              //
              type == WireType::k64Bit ? 8 :                         //
                  type == WireType::k32Bit ? 4 : MaxVarintSize()) +  //
         BufferSizeFor(tail...);
}
References BufferSizeFor(), k32Bit, k64Bit, kVarint, and MaxVarintSize().
CheckstrcasecmpfalseImpl()
std::string * absl::log_internal::CheckstrcasecmpfalseImpl (const char * s1, const char * s2, const char * exprtext)
CheckstrcasecmptrueImpl()
std::string * absl::log_internal::CheckstrcasecmptrueImpl (const char * s1, const char * s2, const char * exprtext)
CheckstrcmpfalseImpl()
std::string * absl::log_internal::CheckstrcmpfalseImpl (const char * s1, const char * s2, const char * exprtext)
CheckstrcmptrueImpl()
std::string * absl::log_internal::CheckstrcmptrueImpl (const char * s1, const char * s2, const char * exprtext)
DeathTestExpectedLogging()
WriteEntryToStderr absl::log_internal::DeathTestExpectedLogging () inline
Definition at line 76 of file test_actions.h.
{
  return WriteEntryToStderr{"Mock received expected entry:"};
}
DeathTestUnexpectedLogging()
WriteEntryToStderr absl::log_internal::DeathTestUnexpectedLogging () inline
Definition at line 82 of file test_actions.h.
{
  return WriteEntryToStderr{"Mock received unexpected entry:"};
}
DeathTestValidateExpectations()
testing::Matcher< const std::string & > absl::log_internal::DeathTestValidateExpectations ()
Definition at line 203 of file test_matchers.cc.
{
  if (log_internal::LoggingEnabledAt(absl::LogSeverity::kFatal)) {
    return Matcher<const std::string&>(
        AllOf(HasSubstr("Mock received expected entry"),
              Not(HasSubstr("Mock received unexpected entry"))));
  }
  // If `FATAL` logging is disabled, neither message should have been written.
  return Matcher<const std::string&>(
      AllOf(Not(HasSubstr("Mock received expected entry")),
            Not(HasSubstr("Mock received unexpected entry"))));
}
References absl::kFatal, and LoggingEnabledAt().
DieBecauseNull()
ABSL_ATTRIBUTE_NORETURN ABSL_ATTRIBUTE_NOINLINE void absl::log_internal::DieBecauseNull (const char * file, int line, const char * exprtext)
Definition at line 25 of file die_if_null.cc.
{
  LOG(FATAL).AtLocation(file, line)
      << absl::StrCat("Check failed: '", exprtext, "' Must be non-null");
}
References LOG, and absl::StrCat().
Referenced by DieIfNull().
DieIfNull()
template<typename T > ABSL_MUST_USE_RESULT T absl::log_internal::DieIfNull (const char * file, int line, const char * exprtext, T && t)
Definition at line 63 of file die_if_null.h.
{
  if (ABSL_PREDICT_FALSE(t == nullptr)) {
    // Call a non-inline helper function for a small code size improvement.
    DieBecauseNull(file, line, exprtext);
  }
  return std::forward<T>(t);
}
References ABSL_PREDICT_FALSE, and DieBecauseNull().
EnableSymbolizeLogStackTrace()
void absl::log_internal::EnableSymbolizeLogStackTrace (bool on_off)
Definition at line 97 of file globals.cc.
{
  symbolize_stack_trace.store(on_off, std::memory_order_release);
}
Encode32Bit() [1/2]
bool absl::log_internal::Encode32Bit (uint64_t tag, int32_t value, absl::Span< char > * buf) inline
Definition at line 119 of file proto.h.
{
  return Encode32Bit(tag, static_cast<uint32_t>(value), buf);
}
References buf, and Encode32Bit().
Encode32Bit() [2/2]
bool absl::log_internal::Encode32Bit (uint64_t tag, uint32_t value, absl::Span< char > * buf)
Definition at line 72 of file proto.cc.
{
  const uint64_t tag_type = MakeTagType(tag, WireType::k32Bit);
  const size_t tag_type_size = VarintSize(tag_type);
  if (tag_type_size + sizeof(value) > buf->size()) {
    buf->remove_suffix(buf->size());
    return false;
  }
  EncodeRawVarint(tag_type, tag_type_size, buf);
  for (size_t s = 0; s < sizeof(value); s++) {
    (*buf)[s] = static_cast<char>(value & 0xff);
    value >>= 8;
  }
  buf->remove_prefix(sizeof(value));
  return true;
}
References buf, k32Bit, absl::s, value, and VarintSize().
Referenced by Encode32Bit(), and EncodeFloat().
Encode64Bit() [1/4]
bool absl::log_internal::Encode64Bit (uint64_t tag, int32_t value, absl::Span< char > * buf) inline
Definition at line 104 of file proto.h.
{
  return Encode64Bit(tag, static_cast<uint64_t>(value), buf);
}
References buf, and Encode64Bit().
Encode64Bit() [2/4]
bool absl::log_internal::Encode64Bit (uint64_t tag, int64_t value, absl::Span< char > * buf) inline
Definition at line 98 of file proto.h.
{
  return Encode64Bit(tag, static_cast<uint64_t>(value), buf);
}
References buf, and Encode64Bit().
Encode64Bit() [3/4]
bool absl::log_internal::Encode64Bit (uint64_t tag, uint32_t value, absl::Span< char > * buf) inline
Definition at line 101 of file proto.h.
{
  return Encode64Bit(tag, static_cast<uint64_t>(value), buf);
}
References buf, and Encode64Bit().
Encode64Bit() [4/4]
bool absl::log_internal::Encode64Bit (uint64_t tag, uint64_t value, absl::Span< char > * buf)
Definition at line 56 of file proto.cc.
{
  const uint64_t tag_type = MakeTagType(tag, WireType::k64Bit);
  const size_t tag_type_size = VarintSize(tag_type);
  if (tag_type_size + sizeof(value) > buf->size()) {
    buf->remove_suffix(buf->size());
    return false;
  }
  EncodeRawVarint(tag_type, tag_type_size, buf);
  for (size_t s = 0; s < sizeof(value); s++) {
    (*buf)[s] = static_cast<char>(value & 0xff);
    value >>= 8;
  }
  buf->remove_prefix(sizeof(value));
  return true;
}
References buf, k64Bit, absl::s, value, and VarintSize().
Referenced by Encode64Bit(), Encode64Bit(), Encode64Bit(), and EncodeDouble().
EncodeBytes()
bool absl::log_internal::EncodeBytes (uint64_t tag, absl::Span< const char > value, absl::Span< char > * buf)
Definition at line 88 of file proto.cc.
{
  const uint64_t tag_type = MakeTagType(tag, WireType::kLengthDelimited);
  const size_t tag_type_size = VarintSize(tag_type);
  uint64_t length = value.size();
  const size_t length_size = VarintSize(length);
  if (tag_type_size + length_size + value.size() > buf->size()) {
    buf->remove_suffix(buf->size());
    return false;
  }
  EncodeRawVarint(tag_type, tag_type_size, buf);
  EncodeRawVarint(length, length_size, buf);
  memcpy(buf->data(), value.data(), value.size());
  buf->remove_prefix(value.size());
  return true;
}
References buf, kLengthDelimited, and VarintSize().
Referenced by EncodeString().
EncodeBytesTruncate()
bool absl::log_internal::EncodeBytesTruncate (uint64_t tag, absl::Span< const char > value, absl::Span< char > * buf)
Definition at line 105 of file proto.cc.
{
  const uint64_t tag_type = MakeTagType(tag, WireType::kLengthDelimited);
  const size_t tag_type_size = VarintSize(tag_type);
  uint64_t length = value.size();
  const size_t length_size =
      VarintSize(std::min<uint64_t>(length, buf->size()));
  if (tag_type_size + length_size <= buf->size() &&
      tag_type_size + length_size + value.size() > buf->size()) {
    value.remove_suffix(tag_type_size + length_size + value.size() -
                        buf->size());
    length = value.size();
  }
  if (tag_type_size + length_size + value.size() > buf->size()) {
    buf->remove_suffix(buf->size());
    return false;
  }
  EncodeRawVarint(tag_type, tag_type_size, buf);
  EncodeRawVarint(length, length_size, buf);
  memcpy(buf->data(), value.data(), value.size());
  buf->remove_prefix(value.size());
  return true;
}
References buf, kLengthDelimited, size, and VarintSize().
Referenced by EncodeStringTruncate().
EncodeDouble()
bool absl::log_internal::EncodeDouble (uint64_t tag, double value, absl::Span< char > * buf) inline
Definition at line 111 of file proto.h.
{
  return Encode64Bit(tag, absl::bit_cast<uint64_t>(value), buf);
}
References absl::bit_cast(), buf, and Encode64Bit().
EncodeFloat()
bool absl::log_internal::EncodeFloat (uint64_t tag, float value, absl::Span< char > * buf) inline
Definition at line 126 of file proto.h.
{
  return Encode32Bit(tag, absl::bit_cast<uint32_t>(value), buf);
}
References absl::bit_cast(), buf, and Encode32Bit().
EncodeMessageLength()
void absl::log_internal::EncodeMessageLength (absl::Span< char > msg, const absl::Span< char > * buf)
Definition at line 145 of file proto.cc.
{
  if (!msg.data()) return;
  assert(buf->data() >= msg.data());
  if (buf->data() < msg.data()) return;
  EncodeRawVarint(
      static_cast<uint64_t>(buf->data() - (msg.data() + msg.size())),
      msg.size(), &msg);
}
References buf, and absl::msg.
EncodeMessageStart()
ABSL_MUST_USE_RESULT absl::Span< char > absl::log_internal::EncodeMessageStart (uint64_t tag, uint64_t max_size, absl::Span< char > * buf)
Definition at line 129 of file proto.cc.
{
  const uint64_t tag_type = MakeTagType(tag, WireType::kLengthDelimited);
  const size_t tag_type_size = VarintSize(tag_type);
  max_size = std::min<uint64_t>(max_size, buf->size());
  const size_t length_size = VarintSize(max_size);
  if (tag_type_size + length_size > buf->size()) {
    buf->remove_suffix(buf->size());
    return absl::Span<char>();
  }
  EncodeRawVarint(tag_type, tag_type_size, buf);
  const absl::Span<char> ret = buf->subspan(0, length_size);
  EncodeRawVarint(0, length_size, buf);
  return ret;
}
References buf, kLengthDelimited, absl::Span< T >::subspan(), and VarintSize().
EncodeString()
bool absl::log_internal::EncodeString (uint64_t tag, absl::string_view value, absl::Span< char > * buf) inline
Definition at line 149 of file proto.h.
{
  return EncodeBytes(tag, value, buf);
}
References buf, and EncodeBytes().
EncodeStringTruncate()
bool absl::log_internal::EncodeStringTruncate (uint64_t tag, absl::string_view value, absl::Span< char > * buf) inline
Definition at line 159 of file proto.h.
{
  return EncodeBytesTruncate(tag, value, buf);
}
References buf, and EncodeBytesTruncate().
EncodeVarint() [1/4]
bool absl::log_internal::EncodeVarint (uint64_t tag, int32_t value, absl::Span< char > * buf) inline
Definition at line 79 of file proto.h.
{
  return EncodeVarint(tag, static_cast<uint64_t>(value), buf);
}
References buf, and EncodeVarint().
EncodeVarint() [2/4]
bool absl::log_internal::EncodeVarint (uint64_t tag, int64_t value, absl::Span< char > * buf) inline
Definition at line 73 of file proto.h.
{
  return EncodeVarint(tag, static_cast<uint64_t>(value), buf);
}
References buf, and EncodeVarint().
EncodeVarint() [3/4]
bool absl::log_internal::EncodeVarint (uint64_t tag, uint32_t value, absl::Span< char > * buf) inline
Definition at line 76 of file proto.h.
{
  return EncodeVarint(tag, static_cast<uint64_t>(value), buf);
}
References buf, and EncodeVarint().
EncodeVarint() [4/4]
bool absl::log_internal::EncodeVarint (uint64_t tag, uint64_t value, absl::Span< char > * buf)
Definition at line 43 of file proto.cc.
{
  const uint64_t tag_type = MakeTagType(tag, WireType::kVarint);
  const size_t tag_type_size = VarintSize(tag_type);
  const size_t value_size = VarintSize(value);
  if (tag_type_size + value_size > buf->size()) {
    buf->remove_suffix(buf->size());
    return false;
  }
  EncodeRawVarint(tag_type, tag_type_size, buf);
  EncodeRawVarint(value, value_size, buf);
  return true;
}
References buf, kVarint, and VarintSize().
Referenced by EncodeVarint(), EncodeVarint(), EncodeVarint(), and EncodeVarintZigZag().
EncodeVarintZigZag()
bool absl::log_internal::EncodeVarintZigZag (uint64_t tag, int64_t value, absl::Span< char > * buf) inline
Definition at line 87 of file proto.h.
{
  if (value < 0)
    return EncodeVarint(tag, 2 * static_cast<uint64_t>(-(value + 1)) + 1, buf);
  return EncodeVarint(tag, 2 * static_cast<uint64_t>(value), buf);
}
References buf, and EncodeVarint().
ExitOnDFatal()
bool absl::log_internal::ExitOnDFatal ()
Definition at line 109 of file globals.cc.
{ return exit_on_dfatal.load(std::memory_order_acquire); }
Referenced by absl::log_internal::LogMessage::Flush().
ExitQuietly()
ABSL_ATTRIBUTE_NORETURN void absl::log_internal::ExitQuietly () inline
Definition at line 217 of file conditions.h.
{ _exit(1); }
FlushLogSinks()
void absl::log_internal::FlushLogSinks ()
Definition at line 292 of file log_sink_set.cc.
{ log_internal::GlobalSinks().FlushLogSinks(); }
Referenced by absl::FlushLogSinks().
FormatLogMessage()
std::string absl::log_internal::FormatLogMessage (absl::LogSeverity severity, absl::CivilSecond civil_second, absl::Duration subsecond, log_internal::Tid tid, absl::string_view basename, int line, PrefixFormat format, absl::string_view message)
Definition at line 168 of file log_format.cc.
{
  return absl::StrFormat(
      "%c%02d%02d %02d:%02d:%02d.%06d %7d %s:%d] %s%s",
      absl::LogSeverityName(severity)[0], civil_second.month(),
      civil_second.day(), civil_second.hour(), civil_second.minute(),
      civil_second.second(), absl::ToInt64Microseconds(subsecond), tid,
      basename, line, format == PrefixFormat::kRaw ? "RAW: " : "", message);
}
References absl::time_internal::cctz::detail::civil_time< T >::day(), absl::time_internal::cctz::detail::civil_time< T >::hour(), kRaw, absl::LogSeverityName(), absl::time_internal::cctz::detail::civil_time< T >::minute(), absl::time_internal::cctz::detail::civil_time< T >::month(), absl::time_internal::cctz::detail::civil_time< T >::second(), absl::StrFormat(), and absl::ToInt64Microseconds().
Referenced by absl::log_internal::LogEntryTestPeer::FormatLogMessage().
FormatLogPrefix()
size_t absl::log_internal::FormatLogPrefix (absl::LogSeverity severity, absl::Time timestamp, log_internal::Tid tid, absl::string_view basename, int line, PrefixFormat format, absl::Span< char > & buf)
Definition at line 190 of file log_format.cc.
{
  auto prefix_size = FormatBoundedFields(severity, timestamp, tid, buf);
  prefix_size += log_internal::AppendTruncated(basename, buf);
  prefix_size += FormatLineNumber(line, buf);
  if (format == PrefixFormat::kRaw)
    prefix_size += log_internal::AppendTruncated("RAW: ", buf);
  return prefix_size;
}
References AppendTruncated(), buf, and kRaw.
Referenced by absl::log_internal::LogMessage::LogMessageData::FinalizeEncodingAndFormat(), absl::log_internal::LogEntryTestPeer::FormatPrefixIntoSizedBuffer(), and absl::log_internal::LogEntryTestPeer::LogEntryTestPeer().
GetReferenceableValue() [1/12]
char absl::log_internal::GetReferenceableValue (char t) inline constexpr
Definition at line 363 of file check_op.h.
{ return t; }
GetReferenceableValue() [2/12]
template<typename T > const T & absl::log_internal::GetReferenceableValue (const T & t) inline constexpr
Definition at line 360 of file check_op.h.
{
  return t;
}
GetReferenceableValue() [3/12]
int absl::log_internal::GetReferenceableValue (int t) inline constexpr
Definition at line 373 of file check_op.h.
{ return t; }
GetReferenceableValue() [4/12]
long long absl::log_internal::GetReferenceableValue (long long t) inline constexpr
Definition at line 380 of file check_op.h.
                                                              {  // NOLINT
  return t;
}
GetReferenceableValue() [5/12]
long absl::log_internal::GetReferenceableValue (long t) inline constexpr
Definition at line 375 of file check_op.h.
{ return t; }  // NOLINT
GetReferenceableValue() [6/12]
short absl::log_internal::GetReferenceableValue (short t) inline constexpr
Definition at line 368 of file check_op.h.
{ return t; }  // NOLINT
GetReferenceableValue() [7/12]
signed char absl::log_internal::GetReferenceableValue (signed char t) inline constexpr
Definition at line 367 of file check_op.h.
{ return t; }
GetReferenceableValue() [8/12]
unsigned char absl::log_internal::GetReferenceableValue (unsigned char t) inline constexpr
Definition at line 364 of file check_op.h.
{
  return t;
}
GetReferenceableValue() [9/12]
unsigned int absl::log_internal::GetReferenceableValue (unsigned int t) inline
Definition at line 374 of file check_op.h.
{ return t; }
GetReferenceableValue() [10/12]
unsigned long long absl::log_internal::GetReferenceableValue (unsigned long long t) inline constexpr
Definition at line 383 of file check_op.h.
                          {                                 // NOLINT
  return t;
}
GetReferenceableValue() [11/12]
unsigned long absl::log_internal::GetReferenceableValue (unsigned long t) inline constexpr
Definition at line 376 of file check_op.h.
                     {                                             // NOLINT
  return t;
}
GetReferenceableValue() [12/12]
unsigned short absl::log_internal::GetReferenceableValue (unsigned short t) inline constexpr
Definition at line 369 of file check_op.h.
                      {                                              // NOLINT
  return t;
}
IsInitialized()
bool absl::log_internal::IsInitialized ()
Definition at line 49 of file globals.cc.
                     {
  return logging_initialized.load(std::memory_order_acquire);
}
Referenced by absl::log_internal::LogTestEnvironment::SetUp().
LoggingEnabledAt()
bool absl::log_internal::LoggingEnabledAt (absl::LogSeverity severity)
Definition at line 34 of file test_helpers.cc.
{
  return severity >= kAbslMinLogLevel && severity >= absl::MinLogLevel();
}
References absl::MinLogLevel().
Referenced by DeathTestValidateExpectations().
LogSeverity() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::LogSeverity (const ::testing::Matcher< absl::LogSeverity > & log_severity)
LogSeverity() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::LogSeverity (const Matcher< absl::LogSeverity > & log_severity)
Definition at line 124 of file test_matchers.cc.
{
  return Property("log_severity", &absl::LogEntry::log_severity, log_severity);
}
References absl::LogEntry::log_severity().
LogToSinks()
void absl::log_internal::LogToSinks (const absl::LogEntry & entry, absl::Span< absl::LogSink * > extra_sinks, bool extra_sinks_only)
Definition at line 279 of file log_sink_set.cc.
{
  log_internal::GlobalSinks().LogToSinks(entry, extra_sinks, extra_sinks_only);
}
MakeCheckOpString() [1/2]
template<typename T1 , typename T2 > std::string * absl::log_internal::MakeCheckOpString (T1 v1, T2 v2, const char * exprtext)
Definition at line 291 of file check_op.h.
{
  CheckOpMessageBuilder comb(exprtext);
  MakeCheckOpValueString(comb.ForVar1(), v1);
  MakeCheckOpValueString(comb.ForVar2(), v2);
  return comb.NewString();
}
References absl::log_internal::CheckOpMessageBuilder::ForVar1(), absl::log_internal::CheckOpMessageBuilder::ForVar2(), MakeCheckOpValueString(), and absl::log_internal::CheckOpMessageBuilder::NewString().
MakeCheckOpString() [2/2]
template<typename T1 , typename T2 > ABSL_ATTRIBUTE_RETURNS_NONNULL std::string * absl::log_internal::MakeCheckOpString (T1 v1, T2 v2, const char * exprtext)
Definition at line 291 of file check_op.h.
{
  CheckOpMessageBuilder comb(exprtext);
  MakeCheckOpValueString(comb.ForVar1(), v1);
  MakeCheckOpValueString(comb.ForVar2(), v2);
  return comb.NewString();
}
References absl::log_internal::CheckOpMessageBuilder::ForVar1(), absl::log_internal::CheckOpMessageBuilder::ForVar2(), MakeCheckOpValueString(), and absl::log_internal::CheckOpMessageBuilder::NewString().
MakeCheckOpValueString() [1/5]
void absl::log_internal::MakeCheckOpValueString (std::ostream & os, const char v)
Definition at line 66 of file check_op.cc.
{
  if (v >= 32 && v <= 126) {
    os << "'" << v << "'";
  } else {
    os << "char value " << int{v};
  }
}
References absl::v.
Referenced by MakeCheckOpString().
MakeCheckOpValueString() [2/5]
void absl::log_internal::MakeCheckOpValueString (std::ostream & os, const signed char v)
Definition at line 74 of file check_op.cc.
{
  if (v >= 32 && v <= 126) {
    os << "'" << v << "'";
  } else {
    os << "signed char value " << int{v};
  }
}
References absl::v.
MakeCheckOpValueString() [3/5]
template<typename T > void absl::log_internal::MakeCheckOpValueString (std::ostream & os, const T & v) inline
Definition at line 191 of file check_op.h.
{
  os << log_internal::NullGuard<T>::Guard(v);
}
References absl::v.
MakeCheckOpValueString() [4/5]
void absl::log_internal::MakeCheckOpValueString (std::ostream & os, const unsigned char v)
Definition at line 82 of file check_op.cc.
{
  if (v >= 32 && v <= 126) {
    os << "'" << v << "'";
  } else {
    os << "unsigned char value " << int{v};
  }
}
References absl::v.
MakeCheckOpValueString() [5/5]
void absl::log_internal::MakeCheckOpValueString (std::ostream & os, const void * p)
Definition at line 90 of file check_op.cc.
{
  if (p == nullptr) {
    os << "(null)";
  } else {
    os << p;
  }
}
References absl::p.
MatchesOstream()
testing::Matcher< absl::string_view > absl::log_internal::MatchesOstream (const std::ostringstream & stream)
Definition at line 192 of file test_matchers.cc.
{
  return MakeMatcher(new MatchesOstreamImpl(stream.str()));
}
MaxFramesInLogStackTrace()
int absl::log_internal::MaxFramesInLogStackTrace ()
Definition at line 101 of file globals.cc.
{
  return max_frames_in_stack_trace.load(std::memory_order_acquire);
}
MaxVarintForSize()
uint64_t absl::log_internal::MaxVarintForSize (size_t size) constexpr
Definition at line 198 of file proto.h.
{
  return size >= 10 ? (std::numeric_limits<uint64_t>::max)()
                    : (static_cast<uint64_t>(1) << size * 7) - 1;
}
References size.
MaxVarintSize()
size_t absl::log_internal::MaxVarintSize () constexpr
Definition at line 194 of file proto.h.
{
  return VarintSize((std::numeric_limits<uint64_t>::max)());
}
References VarintSize().
Referenced by BufferSizeFor().
MinVarintSize()
size_t absl::log_internal::MinVarintSize () constexpr
Definition at line 191 of file proto.h.
{
  return VarintSize((std::numeric_limits<uint64_t>::min)());
}
References VarintSize().
operator<<() [1/3]
template<typename T > NullStream & absl::log_internal::operator<< (NullStream & str, const T &) inline
Definition at line 84 of file nullstream.h.
{
  return str;
}
operator<<() [2/3]
NullStream & absl::log_internal::operator<< (NullStream & str, std::ios_base & *)(std::ios_base &os) inline
Definition at line 91 of file nullstream.h.
{
  return str;
}
operator<<() [3/3]
NullStream & absl::log_internal::operator<< (NullStream & str, std::ostream & *)(std::ostream &os) inline
Definition at line 87 of file nullstream.h.
{
  return str;
}
Prefix() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::Prefix (const ::testing::Matcher< bool > & prefix)
Prefix() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::Prefix (const Matcher< bool > & prefix)
Definition at line 119 of file test_matchers.cc.
{
  return Property("prefix", &absl::LogEntry::prefix, prefix);
}
References absl::LogEntry::prefix().
RawEnableLogPrefix()
void absl::log_internal::RawEnableLogPrefix (bool on_off)
Definition at line 71 of file globals.cc.
{
  prepend_log_prefix.store(on_off, std::memory_order_release);
}
Referenced by ABSL_FLAG(), and absl::EnableLogPrefix().
RawEncodedMessage() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::RawEncodedMessage (const ::testing::Matcher< absl::string_view > & raw_encoded_message)
RawEncodedMessage() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::RawEncodedMessage (const Matcher< absl::string_view > & raw_encoded_message)
Definition at line 176 of file test_matchers.cc.
{
  return Property("encoded_message", &absl::LogEntry::encoded_message,
                  raw_encoded_message);
}
References absl::LogEntry::encoded_message().
RawSetMinLogLevel()
void absl::log_internal::RawSetMinLogLevel (absl::LogSeverityAtLeast severity)
Definition at line 63 of file globals.cc.
{
  min_log_level.store(static_cast<int>(severity), std::memory_order_release);
}
Referenced by ABSL_FLAG(), and absl::SetMinLogLevel().
RawSetStderrThreshold()
void absl::log_internal::RawSetStderrThreshold (absl::LogSeverityAtLeast severity)
Definition at line 67 of file globals.cc.
{
  stderrthreshold.store(static_cast<int>(severity), std::memory_order_release);
}
Referenced by ABSL_FLAG(), and absl::SetStderrThreshold().
RemoveLogSink()
void absl::log_internal::RemoveLogSink (absl::LogSink * sink)
Definition at line 288 of file log_sink_set.cc.
{
  log_internal::GlobalSinks().RemoveLogSink(sink);
}
References sink.
Referenced by absl::RemoveLogSink().
SetExitOnDFatal()
void absl::log_internal::SetExitOnDFatal (bool on_off)
Definition at line 111 of file globals.cc.
{
  exit_on_dfatal.store(on_off, std::memory_order_release);
}
SetInitialized()
void absl::log_internal::SetInitialized ()
Definition at line 53 of file globals.cc.
                      {
  logging_initialized.store(true, std::memory_order_release);
}
Referenced by absl::InitializeLog().
SetLoggingGlobalsListener()
void absl::log_internal::SetLoggingGlobalsListener (LoggingGlobalsListener l)
Definition at line 75 of file globals.cc.
{
  logging_globals_listener.Store(l);
}
SetMaxFramesInLogStackTrace()
void absl::log_internal::SetMaxFramesInLogStackTrace (int max_num_frames)
Definition at line 105 of file globals.cc.
{
  max_frames_in_stack_trace.store(max_num_frames, std::memory_order_release);
}
SetSuppressSigabortTrace()
bool absl::log_internal::SetSuppressSigabortTrace (bool on_off)
Definition at line 119 of file globals.cc.
{
  return suppress_sigabort_trace.exchange(on_off);
}
Referenced by absl::log_internal::LogMessage::FailWithoutStackTrace().
SetTimeZone()
void absl::log_internal::SetTimeZone (absl::TimeZone tz)
Definition at line 77 of file globals.cc.
{
  absl::TimeZone* expected = nullptr;
  absl::TimeZone* new_tz = new absl::TimeZone(tz);
  // timezone_ptr can only be set once, otherwise new_tz is leaked.
  if (!timezone_ptr.compare_exchange_strong(expected, new_tz,
                                            std::memory_order_release,
                                            std::memory_order_relaxed)) {
    ABSL_RAW_LOG(FATAL,
                 "absl::log_internal::SetTimeZone() has already been called");
  }
}
References ABSL_RAW_LOG.
Referenced by absl::InitializeLog().
ShouldLogBacktraceAt()
ABSL_MUST_USE_RESULT bool absl::log_internal::ShouldLogBacktraceAt (absl::string_view file, int line)
Definition at line 124 of file globals.cc.
{
  const size_t flag_hash =
      log_backtrace_at_hash.load(std::memory_order_acquire);
  return flag_hash != 0 && flag_hash == HashSiteForLogBacktraceAt(file, line);
}
ShouldSymbolizeLogStackTrace()
bool absl::log_internal::ShouldSymbolizeLogStackTrace ()
Definition at line 93 of file globals.cc.
{
  return symbolize_stack_trace.load(std::memory_order_acquire);
}
SourceBasename() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::SourceBasename (const ::testing::Matcher< absl::string_view > & source_basename)
SourceBasename() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::SourceBasename (const Matcher< absl::string_view > & source_basename)
Definition at line 108 of file test_matchers.cc.
{
  return Property("source_basename", &absl::LogEntry::source_basename,
                  source_basename);
}
References absl::LogEntry::source_basename().
SourceFilename() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::SourceFilename (const ::testing::Matcher< absl::string_view > & source_filename)
SourceFilename() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::SourceFilename (const Matcher< absl::string_view > & source_filename)
Definition at line 102 of file test_matchers.cc.
{
  return Property("source_filename", &absl::LogEntry::source_filename,
                  source_filename);
}
References absl::LogEntry::source_filename().
SourceLine() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::SourceLine (const ::testing::Matcher< int > & source_line)
SourceLine() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::SourceLine (const Matcher< int > & source_line)
Definition at line 114 of file test_matchers.cc.
{
  return Property("source_line", &absl::LogEntry::source_line, source_line);
}
References absl::LogEntry::source_line().
Stacktrace() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::Stacktrace (const ::testing::Matcher< absl::string_view > & stacktrace)
Stacktrace() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::Stacktrace (const Matcher< absl::string_view > & stacktrace)
Definition at line 187 of file test_matchers.cc.
{
  return Property("stacktrace", &absl::LogEntry::stacktrace, stacktrace);
}
References absl::LogEntry::stacktrace().
SuppressSigabortTrace()
bool absl::log_internal::SuppressSigabortTrace ()
Definition at line 115 of file globals.cc.
{
  return suppress_sigabort_trace.load(std::memory_order_acquire);
}
TextMessage() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::TextMessage (const ::testing::Matcher< absl::string_view > & text_message)
TextMessage() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::TextMessage (const Matcher< absl::string_view > & text_message)
Definition at line 161 of file test_matchers.cc.
{
  return Property("text_message", &absl::LogEntry::text_message, text_message);
}
References absl::LogEntry::text_message().
TextMessageWithPrefix() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::TextMessageWithPrefix (const ::testing::Matcher< absl::string_view > & text_message_with_prefix)
TextMessageWithPrefix() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::TextMessageWithPrefix (const Matcher< absl::string_view > & text_message_with_prefix)
Definition at line 154 of file test_matchers.cc.
{
  return Property("text_message_with_prefix",
                  &absl::LogEntry::text_message_with_prefix,
                  text_message_with_prefix);
}
References absl::LogEntry::text_message_with_prefix().
TextMessageWithPrefixAndNewline() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::TextMessageWithPrefixAndNewline (const ::testing::Matcher< absl::string_view > & text_message_with_prefix_and_newline)
TextMessageWithPrefixAndNewline() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::TextMessageWithPrefixAndNewline (const Matcher< absl::string_view > & text_message_with_prefix_and_newline)
Definition at line 146 of file test_matchers.cc.
{
  return Property("text_message_with_prefix_and_newline",
                  &absl::LogEntry::text_message_with_prefix_and_newline,
                  text_message_with_prefix_and_newline);
}
References absl::LogEntry::text_message_with_prefix_and_newline().
TextPrefix() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::TextPrefix (const ::testing::Matcher< absl::string_view > & text_prefix)
TextPrefix() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::TextPrefix (const Matcher< absl::string_view > & text_prefix)
Definition at line 166 of file test_matchers.cc.
{
  return ResultOf(
      [](const absl::LogEntry& entry) {
        absl::string_view msg = entry.text_message_with_prefix();
        msg.remove_suffix(entry.text_message().size());
        return msg;
      },
      text_prefix);
}
References absl::msg, absl::string_view::remove_suffix(), absl::string_view::size(), absl::LogEntry::text_message(), and absl::LogEntry::text_message_with_prefix().
ThreadID() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::ThreadID (const ::testing::Matcher< absl::LogEntry::tid_t > &)
ThreadID() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::ThreadID (const Matcher< absl::LogEntry::tid_t > & tid)
Definition at line 141 of file test_matchers.cc.
{
  return Property("tid", &absl::LogEntry::tid, tid);
}
References absl::LogEntry::tid().
ThreadIsLoggingToLogSink()
bool absl::log_internal::ThreadIsLoggingToLogSink ()
Definition at line 277 of file log_sink_set.cc.
{ return ThreadIsLoggingStatus(); }
Referenced by absl::log_internal::LogMessage::LogMessageData::FinalizeEncodingAndFormat().
Timestamp() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::Timestamp (const ::testing::Matcher< absl::Time > & timestamp)
Timestamp() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::Timestamp (const Matcher< absl::Time > & timestamp)
Definition at line 129 of file test_matchers.cc.
{
  return Property("timestamp", &absl::LogEntry::timestamp, timestamp);
}
References absl::LogEntry::timestamp().
TimestampInMatchWindow()
testing::Matcher< const absl::LogEntry & > absl::log_internal::TimestampInMatchWindow ()
Definition at line 134 of file test_matchers.cc.
{
  return Property("timestamp", &absl::LogEntry::timestamp,
                  AllOf(Ge(absl::Now()), Truly([](absl::Time arg) {
                          return arg <= absl::Now();
                        })));
}
References arg, absl::Now(), and absl::LogEntry::timestamp().
TimeZone()
const absl::TimeZone * absl::log_internal::TimeZone ()
Definition at line 89 of file globals.cc.
{
  return timezone_ptr.load(std::memory_order_acquire);
}
VarintSize()
size_t absl::log_internal::VarintSize (uint64_t value) constexpr
Definition at line 188 of file proto.h.
{
  return value < 128 ? 1 : 1 + VarintSize(value >> 7);
}
References VarintSize().
Referenced by Encode32Bit(), Encode64Bit(), EncodeBytes(), EncodeBytesTruncate(), EncodeMessageStart(), EncodeVarint(), MaxVarintSize(), MinVarintSize(), and VarintSize().
Verbosity() [1/2]
::testing::Matcher< const absl::LogEntry & > absl::log_internal::Verbosity (const ::testing::Matcher< int > & verbosity)
Verbosity() [2/2]
Matcher< const absl::LogEntry & > absl::log_internal::Verbosity (const Matcher< int > & verbosity)
Definition at line 182 of file test_matchers.cc.
{
  return Property("verbosity", &absl::LogEntry::verbosity, verbosity);
}
References absl::LogEntry::verbosity().
WriteToStderr()
void absl::log_internal::WriteToStderr (absl::string_view message, absl::LogSeverity severity)
Definition at line 57 of file globals.cc.
{
  // Avoid using std::cerr from this module since we may get called during
  // exit code, and cerr may be partially or fully destroyed by then.
  std::fwrite(message.data(), message.size(), 1, stderr);
#if defined(_WIN64) || defined(_WIN32) || defined(_WIN16)
  // C99 requires stderr to not be fully-buffered by default (7.19.3.7), but
  // MS CRT buffers it anyway, so we must `fflush` to ensure the string hits
  // the console/file before the program dies (and takes the libc buffers
  // with it).
  // https://docs.microsoft.com/en-us/cpp/c-runtime-library/stream-i-o
  if (severity >= absl::LogSeverity::kWarning) {
    std::fflush(stderr);
  }
#else
  // Avoid unused parameter warning in this branch.
  (void)severity;
#endif
}
References absl::string_view::data(), absl::kWarning, and absl::string_view::size().
Variable Documentation
kAbslMinLogLevel
auto absl::log_internal::kAbslMinLogLevel constexpr
Initial value:
=
    absl::LogSeverityAtLeast::kInfo
Definition at line 34 of file test_helpers.h.
kCharNull
ABSL_DLL ABSL_CONST_INIT const std::array< char, 7 > absl::log_internal::kCharNull
Initial value:
{
    {'(', 'n', 'u', 'l', 'l', ')', '\0'}}
Definition at line 26 of file nullguard.cc.
{
    {'(', 'n', 'u', 'l', 'l', ')', '\0'}};
Referenced by absl::log_internal::NullGuard< char * >::Guard(), absl::log_internal::NullGuard< const char * >::Guard(), and absl::log_internal::NullGuard< std::nullptr_t >::Guard().
kLogMessageBufferSize
int absl::log_internal::kLogMessageBufferSize = 15000 constexpr
Definition at line 50 of file log_message.h.
kSignedCharNull
ABSL_DLL ABSL_CONST_INIT const std::array< signed char, 7 > absl::log_internal::kSignedCharNull
Initial value:
{
    {'(', 'n', 'u', 'l', 'l', ')', '\0'}}
Definition at line 28 of file nullguard.cc.
{
    {'(', 'n', 'u', 'l', 'l', ')', '\0'}};
Referenced by absl::log_internal::NullGuard< const signed char * >::Guard(), and absl::log_internal::NullGuard< signed char * >::Guard().
kUnsignedCharNull
ABSL_DLL ABSL_CONST_INIT const std::array< unsigned char, 7 > absl::log_internal::kUnsignedCharNull
Initial value:
{
    {'(', 'n', 'u', 'l', 'l', ')', '\0'}}
Definition at line 30 of file nullguard.cc.
{
    {'(', 'n', 'u', 'l', 'l', ')', '\0'}};
Referenced by absl::log_internal::NullGuard< const unsigned char * >::Guard(), and absl::log_internal::NullGuard< unsigned char * >::Guard().