open spiel: open_spiel::go Namespace Reference
open_spiel::go Namespace Reference
Classes
class GoBoard
class GoGame
class GoState
class Neighbours4
Typedefs
using VirtualPoint = uint16_t
Enumerations
enum class GoColor : uint8_t { kBlack = 0 , kWhite = 1 , kEmpty = 2 , kGuard = 3 }
Functions
constexpr int NumPlayers ()
constexpr double LossUtility ()
constexpr double WinUtility ()
constexpr int CellStates ()
constexpr double DrawUtility ()
int NumDistinctActions (int board_size)
int DefaultMaxGameLength (int board_size)
int ColorToPlayer (GoColor c)
GoColor PlayerToColor (Player p)
std::pair< int, int > VirtualPointTo2DPoint (VirtualPoint p)
VirtualPoint VirtualPointFrom2DPoint (std::pair< int, int > row_col)
Action VirtualActionToAction (int virtual_action, int board_size)
int ActionToVirtualAction (Action action, int board_size)
const std::vector< VirtualPoint > & BoardPoints (int board_size)
GoColor OppColor (GoColor c)
std::ostream & operator<< (std::ostream &os, GoColor c)
std::string GoColorToString (GoColor c)
std::ostream & operator<< (std::ostream &os, VirtualPoint p)
std::string VirtualPointToString (VirtualPoint p)
VirtualPoint MakePoint (std::string s)
std::ostream & operator<< (std::ostream &os, const GoBoard &board)
int NumSurroundedPoints (const GoBoard &board, const VirtualPoint p, std::array< bool, kVirtualBoardPoints > *marked, bool *reached_black, bool *reached_white)
float TrompTaylorScore (const GoBoard &board, float komi, int handicap)
GoBoard CreateBoard (const std::string &initial_stones)
std::string GoActionToString (Action action, int board_size)
Variables
constexpr int kMaxBoardSize = 19
constexpr int kVirtualBoardSize = kMaxBoardSize + 2
constexpr int kVirtualBoardPoints
constexpr VirtualPoint kInvalidPoint = 0
constexpr VirtualPoint kVirtualPass = kVirtualBoardPoints + 1
Typedef Documentation
VirtualPoint
using open_spiel::go::VirtualPoint = uint16_t
Definition at line 52 of file go_board.h.
Enumeration Type Documentation
GoColor
enum class open_spiel::go::GoColor : uint8_t strong
Enumerator
kBlack
kWhite
kEmpty
kGuard
Definition at line 28 of file go_board.h.
: uint8_t { kBlack = 0, kWhite = 1, kEmpty = 2, kGuard = 3 };
Function Documentation
ActionToVirtualAction()
int open_spiel::go::ActionToVirtualAction (Action action, int board_size)
Definition at line 142 of file go_board.cc.
{
  if (action == board_size * board_size) return kVirtualPass;
  int row = action / board_size;
  int column = action % board_size;
  return (row + 1) * kVirtualBoardSize + (column + 1);
}
References action, kVirtualBoardSize, and kVirtualPass.
Referenced by open_spiel::go::GoBoard::ActionToVirtualAction(), and GoActionToString().
BoardPoints()
const std::vector< VirtualPoint > & open_spiel::go::BoardPoints (int board_size)
Definition at line 149 of file go_board.cc.
{
#define CASE_GET_POINTS(n) \
  case n:                  \
    return GetBoardPoints<n>()
  switch (board_size) {
    CASE_GET_POINTS(2);
    CASE_GET_POINTS(3);
    CASE_GET_POINTS(4);
    CASE_GET_POINTS(5);
    CASE_GET_POINTS(6);
    CASE_GET_POINTS(7);
    CASE_GET_POINTS(8);
    CASE_GET_POINTS(9);
    CASE_GET_POINTS(10);
    CASE_GET_POINTS(11);
    CASE_GET_POINTS(12);
    CASE_GET_POINTS(13);
    CASE_GET_POINTS(14);
    CASE_GET_POINTS(15);
    CASE_GET_POINTS(16);
    CASE_GET_POINTS(17);
    CASE_GET_POINTS(18);
    CASE_GET_POINTS(19);
    default:
      SpielFatalError("unsupported board size");
  }
#undef CASE_GET_POINTS
}
References CASE_GET_POINTS, and open_spiel::SpielFatalError().
Referenced by open_spiel::go::GoBoard::Clear(), open_spiel::go::GoState::LegalActions(), open_spiel::go::GoState::ObservationTensor(), operator<<(), and TrompTaylorScore().
CellStates()
int open_spiel::go::CellStates () inline constexpr
Definition at line 45 of file go.h.
{ return 3; }  // Black, white, empty.
Referenced by open_spiel::go::GoState::ObservationTensor(), and open_spiel::go::GoGame::ObservationTensorShape().
ColorToPlayer()
int open_spiel::go::ColorToPlayer (GoColor c) inline
Definition at line 63 of file go.h.
{ return static_cast<int>(c); }
Referenced by open_spiel::go::GoState::CurrentPlayer(), and open_spiel::go::GoState::Returns().
CreateBoard()
GoBoard open_spiel::go::CreateBoard (const std::string & initial_stones)
Definition at line 676 of file go_board.cc.
{
  GoBoard board(19);
  int row = 0;
  for (const auto& line : absl::StrSplit(initial_stones, '\n')) {
    int col = 0;
    bool stones_started = false;
    for (const auto& c : line) {
      if (c == ' ') {
        if (stones_started) {
          SpielFatalError(
              "Whitespace is only allowed at the start of "
              "the line. To represent empty intersections, "
              "use +");
        }
        continue;
      } else if (c == 'X') {
        stones_started = true;
        SPIEL_CHECK_TRUE(board.PlayMove(VirtualPointFrom2DPoint({row, col}),
                                        GoColor::kBlack));
      } else if (c == 'O') {
        stones_started = true;
        SPIEL_CHECK_TRUE(board.PlayMove(VirtualPointFrom2DPoint({row, col}),
                                        GoColor::kWhite));
      }
      col++;
    }
    row++;
  }
  return board;
}
References kBlack, kWhite, open_spiel::go::GoBoard::PlayMove(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), and absl::StrSplit().
DefaultMaxGameLength()
int open_spiel::go::DefaultMaxGameLength (int board_size) inline
Definition at line 59 of file go.h.
{
  return board_size * board_size * 2;
}
DrawUtility()
double open_spiel::go::DrawUtility () inline constexpr
Definition at line 49 of file go.h.
{ return 0; }
Referenced by open_spiel::go::GoState::Returns().
GoActionToString()
std::string open_spiel::go::GoActionToString (Action action, int board_size) inline
Definition at line 77 of file go_board.h.
{
  return VirtualPointToString(ActionToVirtualAction(action, board_size));
}
References action, ActionToVirtualAction(), and VirtualPointToString().
GoColorToString()
std::string open_spiel::go::GoColorToString (GoColor c)
Definition at line 199 of file go_board.cc.
{
  switch (c) {
    case GoColor::kBlack:
      return "B";
    case GoColor::kWhite:
      return "W";
    case GoColor::kEmpty:
      return "EMPTY";
    case GoColor::kGuard:
      return "GUARD";
    default:
      SpielFatalError(
          absl::StrCat("Unknown color ", c, " in GoColorToString."));
      return "This will never return.";
  }
}
References kBlack, kEmpty, kGuard, kWhite, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::go::GoState::ActionToString(), operator<<(), open_spiel::go::GoBoard::PlayMove(), and open_spiel::go::GoState::ToString().
LossUtility()
double open_spiel::go::LossUtility () inline constexpr
Definition at line 43 of file go.h.
{ return -1; }
Referenced by open_spiel::go::GoGame::MinUtility(), open_spiel::go::GoState::Returns(), and open_spiel::go::GoGame::UtilitySum().
MakePoint()
VirtualPoint open_spiel::go::MakePoint (std::string s)
Definition at line 235 of file go_board.cc.
{
  std::transform(s.begin(), s.end(), s.begin(), ::tolower);
  if (s == "pass") return kVirtualPass;
  if (s.size() < 2 || s.size() > 3) return kInvalidPoint;
  int col = s[0] < 'i' ? s[0] - 'a' : s[0] - 'a' - 1;
  int row = s[1] - '0';
  if (s.size() == 3) {
    row *= 10;
    row += s[2] - '0';
  }
  return VirtualPointFrom2DPoint({row - 1, col});
}
References kInvalidPoint, kVirtualPass, and VirtualPointFrom2DPoint().
NumDistinctActions()
int open_spiel::go::NumDistinctActions (int board_size) inline
Definition at line 52 of file go.h.
{
  return board_size * board_size + 1;
}
Referenced by open_spiel::go::GoGame::NumDistinctActions().
NumPlayers()
int open_spiel::go::NumPlayers () inline constexpr
Definition at line 42 of file go.h.
{ return 2; }
Referenced by open_spiel::go::GoGame::NumPlayers(), and open_spiel::go::GoState::Returns().
NumSurroundedPoints()
int open_spiel::go::NumSurroundedPoints (const GoBoard & board, const VirtualPoint p, std::array< bool, kVirtualBoardPoints > * marked, bool * reached_black, bool * reached_white)
Definition at line 603 of file go_board.cc.
{
  if ((*marked)[p]) return 0;
  (*marked)[p] = true;
  int num_points = 1;
  Neighbours(p, [&board, &num_points, marked, reached_black,
                 reached_white](VirtualPoint n) {
    switch (board.PointColor(n)) {
      case GoColor::kBlack:
        *reached_black = true;
        break;
      case GoColor::kWhite:
        *reached_white = true;
        break;
      case GoColor::kEmpty:
        num_points +=
            NumSurroundedPoints(board, n, marked, reached_black, reached_white);
        break;
      case GoColor::kGuard:
        // Ignore the border.
        break;
    }
  });
  return num_points;
}
References n, and open_spiel::go::GoBoard::PointColor().
Referenced by TrompTaylorScore().
operator<<() [1/3]
std::ostream & open_spiel::go::operator<< (std::ostream & os, const GoBoard & board)
Definition at line 557 of file go_board.cc.
{
  os << "\n";
  for (int row = board.board_size() - 1; row >= 0; --row) {
    os << std::setw(2) << std::setfill(' ') << (row + 1) << " ";
    for (int col = 0; col < board.board_size(); ++col) {
      os << GoColorToChar(
          board.PointColor(VirtualPointFrom2DPoint({row, col})));
    }
    os << std::endl;
  }
  std::string columns = "ABCDEFGHJKLMNOPQRST";
  os << "   " << columns.substr(0, board.board_size()) << std::endl;
  // Encode the stones and print a URL that can be used to view the board.
  std::string encoded;
  for (VirtualPoint p : BoardPoints(board.board_size())) {
    if (!board.IsEmpty(p)) {
      encoded += MoveAsAscii(p, board.PointColor(p));
    }
  }
  // TODO(author9): Make this a public URL.
  // os << "http://jumper/goboard/" << encoded << "&size=" << board.board_size()
  //    << std::endl;
  return os;
}
References open_spiel::go::GoBoard::board_size(), BoardPoints(), open_spiel::go::GoBoard::IsEmpty(), and open_spiel::go::GoBoard::PointColor().
operator<<() [2/3]
std::ostream & open_spiel::go::operator<< (std::ostream & os, GoColor c)
Definition at line 195 of file go_board.cc.
{
  return os << GoColorToString(c);
}
References GoColorToString().
operator<<() [3/3]
std::ostream & open_spiel::go::operator<< (std::ostream & os, VirtualPoint p)
Definition at line 216 of file go_board.cc.
{
  return os << VirtualPointToString(p);
}
References VirtualPointToString().
OppColor()
GoColor open_spiel::go::OppColor (GoColor c)
Definition at line 180 of file go_board.cc.
{
  switch (c) {
    case GoColor::kBlack:
      return GoColor::kWhite;
    case GoColor::kWhite:
      return GoColor::kBlack;
    case GoColor::kEmpty:
    case GoColor::kGuard:
      return c;
    default:
      SpielFatalError(absl::StrCat("Unknown color ", c, " in OppColor."));
      return c;
  }
}
References kBlack, kEmpty, kGuard, kWhite, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::go::GoState::DoApplyAction(), open_spiel::go::GoBoard::IsLegalMove(), and open_spiel::go::GoBoard::OppIter().
PlayerToColor()
GoColor open_spiel::go::PlayerToColor (Player p) inline
Definition at line 64 of file go.h.
{ return static_cast<GoColor>(p); }
TrompTaylorScore()
float open_spiel::go::TrompTaylorScore (const GoBoard & board, float komi, int handicap)
Definition at line 632 of file go_board.cc.
{
  // The delta of how many points on the board black and white have occupied,
  // from black's point of view, i.e. Black points - White points.
  int occupied_delta = 0;
  // We need to keep track of which empty points we've already counted as part
  // of a larger territory.
  std::array<bool, kVirtualBoardPoints> marked;
  marked.fill(false);
  for (VirtualPoint p : BoardPoints(board.board_size())) {
    switch (board.PointColor(p)) {
      case GoColor::kBlack:
        ++occupied_delta;
        break;
      case GoColor::kWhite:
        --occupied_delta;
        break;
      case GoColor::kEmpty: {
        if (marked[p]) continue;
        // If some empty points are surrounded entirely by one player, they
        // count as that player's territory.
        bool reached_black = false, reached_white = false;
        int n = NumSurroundedPoints(board, p, &marked, &reached_black,
                                    &reached_white);
        if (reached_black && !reached_white) {
          occupied_delta += n;
        } else if (!reached_black && reached_white) {
          occupied_delta -= n;
        }
        break;
      }
      case GoColor::kGuard:
        SpielFatalError("unexpected color");
    }
  }
  float score = occupied_delta - komi;
  if (handicap >= 2) {
    score -= handicap;
  }
  return score;
}
References open_spiel::go::GoBoard::board_size(), BoardPoints(), kBlack, kEmpty, kGuard, kWhite, n, NumSurroundedPoints(), open_spiel::go::GoBoard::PointColor(), and open_spiel::SpielFatalError().
Referenced by open_spiel::go::GoState::Returns().
VirtualActionToAction()
Action open_spiel::go::VirtualActionToAction (int virtual_action, int board_size)
Definition at line 135 of file go_board.cc.
{
  if (virtual_action == kVirtualPass) return board_size * board_size;
  const int virtual_row = static_cast<int>(virtual_action) / kVirtualBoardSize;
  const int virtual_col = static_cast<int>(virtual_action) % kVirtualBoardSize;
  return board_size * (virtual_row - 1) + (virtual_col - 1);
}
References kVirtualBoardSize, and kVirtualPass.
Referenced by open_spiel::go::GoBoard::VirtualActionToAction().
VirtualPointFrom2DPoint()
VirtualPoint open_spiel::go::VirtualPointFrom2DPoint (std::pair< int, int > row_col)
Definition at line 127 of file go_board.cc.
{
  return static_cast<VirtualPoint>((row_col.first + 1) * kVirtualBoardSize +
                                   row_col.second + 1);
}
References kVirtualBoardSize.
Referenced by MakePoint().
VirtualPointTo2DPoint()
std::pair< int, int > open_spiel::go::VirtualPointTo2DPoint (VirtualPoint p)
Definition at line 119 of file go_board.cc.
{
  if (p == kInvalidPoint || p == kVirtualPass) return std::make_pair(-1, -1);
  const int row = static_cast<int>(p) / kVirtualBoardSize;
  const int col = static_cast<int>(p) % kVirtualBoardSize;
  return std::make_pair(row - 1, col - 1);
}
References kInvalidPoint, kVirtualBoardSize, and kVirtualPass.
Referenced by open_spiel::go::GoBoard::IsInBoardArea(), and VirtualPointToString().
VirtualPointToString()
std::string open_spiel::go::VirtualPointToString (VirtualPoint p)
Definition at line 220 of file go_board.cc.
{
  switch (p) {
    case kInvalidPoint:
      return "INVALID_POINT";
    case kVirtualPass:
      return "PASS";
    default: {
      auto row_col = VirtualPointTo2DPoint(p);
      char col = 'a' + row_col.second;
      if (col >= 'i') ++col;  // Go / SGF labeling skips 'i'.
      return absl::StrCat(std::string(1, col), row_col.first + 1);
    }
  }
}
References kInvalidPoint, kVirtualPass, absl::StrCat(), and VirtualPointTo2DPoint().
Referenced by open_spiel::go::GoState::ActionToString(), GoActionToString(), operator<<(), and open_spiel::go::GoBoard::PlayMove().
WinUtility()
double open_spiel::go::WinUtility () inline constexpr
Definition at line 44 of file go.h.
{ return 1; }
Referenced by open_spiel::go::GoGame::MaxUtility(), open_spiel::go::GoState::Returns(), and open_spiel::go::GoGame::UtilitySum().
Variable Documentation
kInvalidPoint
VirtualPoint open_spiel::go::kInvalidPoint = 0 inline constexpr
Definition at line 54 of file go_board.h.
Referenced by open_spiel::go::GoBoard::Clear(), MakePoint(), open_spiel::go::GoBoard::PlayMove(), VirtualPointTo2DPoint(), and VirtualPointToString().
kMaxBoardSize
int open_spiel::go::kMaxBoardSize = 19 inline constexpr
Definition at line 47 of file go_board.h.
kVirtualBoardPoints
int open_spiel::go::kVirtualBoardPoints inline constexpr
Initial value:
=
    kVirtualBoardSize * kVirtualBoardSize
Definition at line 49 of file go_board.h.
kVirtualBoardSize
int open_spiel::go::kVirtualBoardSize = kMaxBoardSize + 2 inline constexpr
Definition at line 48 of file go_board.h.
Referenced by ActionToVirtualAction(), VirtualActionToAction(), VirtualPointFrom2DPoint(), and VirtualPointTo2DPoint().
kVirtualPass
VirtualPoint open_spiel::go::kVirtualPass = kVirtualBoardPoints + 1 inline constexpr
Definition at line 55 of file go_board.h.
Referenced by ActionToVirtualAction(), open_spiel::cursor_go::CursorGoState::DoApplyAction(), open_spiel::go::GoBoard::IsLegalMove(), MakePoint(), open_spiel::go::GoBoard::PlayMove(), VirtualActionToAction(), VirtualPointTo2DPoint(), and VirtualPointToString().