open spiel: absl::optional_internal Namespace Reference
absl::optional_internal Namespace Reference
Classes
struct assign_copy_traits
struct ctor_copy_traits
struct empty_struct
struct init_t
struct is_constructible_convertible_assignable_from_optional
struct is_constructible_convertible_from_optional
class optional_assign_base
class optional_assign_base< copy_traits::copyable >
class optional_assign_base< copy_traits::movable >
class optional_assign_base< copy_traits::non_movable >
class optional_ctor_base
class optional_ctor_base< copy_traits::copyable >
class optional_ctor_base< copy_traits::movable >
class optional_ctor_base< copy_traits::non_movable >
class optional_data
class optional_data< T, false >
class optional_data< T, true >
class optional_data_base
class optional_data_dtor_base
class optional_data_dtor_base< T, true >
struct optional_hash_base
struct optional_hash_base< T, decltype(std::hash< absl::remove_const_t< T > >()(std::declval< absl::remove_const_t< T > >()))>
Enumerations
enum class copy_traits { copyable = 0 , movable = 1 , non_movable = 2 }
Functions
void throw_bad_optional_access ()
bool convertible_to_bool (bool)
Enumeration Type Documentation
copy_traits
enum class absl::optional_internal::copy_traits strong
Enumerator
copyable
movable
non_movable
Definition at line 253 of file optional.h.
{ copyable = 0, movable = 1, non_movable = 2 };
Function Documentation
convertible_to_bool()
bool absl::optional_internal::convertible_to_bool (bool)
throw_bad_optional_access()
ABSL_DLL void absl::optional_internal::throw_bad_optional_access ()
Definition at line 35 of file bad_optional_access.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  throw bad_optional_access();
#else
  ABSL_RAW_LOG(FATAL, "Bad optional access");
  abort();
#endif
}
References ABSL_RAW_LOG.
Referenced by absl::optional< T >::value(), absl::optional< T >::value(), absl::optional< T >::value(), and absl::optional< T >::value().