open spiel: open_spiel::internal Namespace Reference
open_spiel::internal Namespace Reference
Functions
template<typename Out , typename T >
void SpielStrOut (Out &out, const T &arg)
template<typename Out , typename T , typename... Args>
void SpielStrOut (Out &out, const T &arg1, Args &&... args)
template<typename... Args>
std::string SpielStrCat (Args &&... args)
Function Documentation
SpielStrCat()
template<typename... Args> std::string open_spiel::internal::SpielStrCat (Args &&... args)
Definition at line 124 of file spiel_utils.h.
{
  std::ostringstream out;
  SpielStrOut(out, std::forward<Args>(args)...);
  return out.str();
}
References out, and SpielStrOut().
Referenced by open_spiel::GameTypeToString().
SpielStrOut() [1/2]
template<typename Out , typename T > void open_spiel::internal::SpielStrOut (Out & out, const T & arg)
Definition at line 105 of file spiel_utils.h.
{
  out << arg;
}
References arg, and out.
Referenced by SpielStrCat(), and SpielStrOut().
SpielStrOut() [2/2]
template<typename Out , typename T , typename... Args> void open_spiel::internal::SpielStrOut (Out & out, const T & arg1, Args &&... args)
Definition at line 110 of file spiel_utils.h.
{
  out << arg1;
  SpielStrOut(out, std::forward<Args>(args)...);
}
References out, and SpielStrOut().