open spiel: open_spiel.python.games.tic_tac_toe Namespace Reference
open_spiel.python.games.tic_tac_toe Namespace Reference
Classes
class BoardObserver
class TicTacToeGame
class TicTacToeState
Functions
_line_value (line)
_line_exists (board)
_coord (move)
_board_to_string (board)
Variables
int _NUM_PLAYERS = 2
int _NUM_ROWS = 3
int _NUM_COLS = 3
int _NUM_CELLS = _NUM_ROWS * _NUM_COLS
_GAME_TYPE
_GAME_INFO
Detailed Description
Tic tac toe (noughts and crosses), implemented in Python.
This is a demonstration of implementing a deterministic perfect-information
game in Python.
Python games are significantly slower than C++, but it may still be suitable
for prototyping or for small games.
It is possible to run C++ algorithms on Python-implemented games. This is likely
to have good performance if the algorithm simply extracts a game tree and then
works with that (e.g. CFR algorithms). It is likely to be poor if the algorithm
relies on processing and updating states as it goes, e.g., MCTS.
Function Documentation
_board_to_string()
open_spiel.python.games.tic_tac_toe._board_to_string (board) protected
Returns a string representation of the board.
Definition at line 189 of file tic_tac_toe.py.
def _board_to_string(board):
  """Returns a string representation of the board."""
  return "\n".join("".join(row) for row in board)
# Register the game with the OpenSpiel library
Referenced by open_spiel.python.games.tic_tac_toe.TicTacToeState.__str__(), and open_spiel.python.games.tic_tac_toe.BoardObserver.string_from().
_coord()
open_spiel.python.games.tic_tac_toe._coord (move) protected
Returns (row, col) from an action id.
Definition at line 184 of file tic_tac_toe.py.
def _coord(move):
  """Returns (row, col) from an action id."""
  return (move // _NUM_COLS, move % _NUM_COLS)
Referenced by open_spiel.python.games.tic_tac_toe.TicTacToeState._action_to_string(), open_spiel.python.games.tic_tac_toe.TicTacToeState._apply_action(), and open_spiel.python.games.tic_tac_toe.TicTacToeState._legal_actions().
_line_exists()
open_spiel.python.games.tic_tac_toe._line_exists (board) protected
Checks if a line exists, returns "x" or "o" if so, and None otherwise.
Definition at line 175 of file tic_tac_toe.py.
def _line_exists(board):
  """Checks if a line exists, returns "x" or "o" if so, and None otherwise."""
  return (_line_value(board[0]) or _line_value(board[1]) or
          _line_value(board[2]) or _line_value(board[:, 0]) or
          _line_value(board[:, 1]) or _line_value(board[:, 2]) or
          _line_value(board.diagonal()) or
          _line_value(np.fliplr(board).diagonal()))
References open_spiel.python.games.tic_tac_toe._line_value().
Referenced by open_spiel.python.games.tic_tac_toe.TicTacToeState._apply_action().
_line_value()
open_spiel.python.games.tic_tac_toe._line_value (line) protected
Checks a possible line, returning the winning symbol if any.
Definition at line 169 of file tic_tac_toe.py.
def _line_value(line):
  """Checks a possible line, returning the winning symbol if any."""
  if all(line == "x") or all(line == "o"):
    return line[0]
Referenced by open_spiel.python.games.tic_tac_toe._line_exists().
Variable Documentation
_GAME_INFO
open_spiel.python.games.tic_tac_toe._GAME_INFO protected
Initial value:
=  pyspiel.GameInfo(
    num_distinct_actions=_NUM_CELLS,
    max_chance_outcomes=0,
    num_players=2,
    min_utility=-1.0,
    max_utility=1.0,
    utility_sum=0.0,
    max_game_length=_NUM_CELLS)
Definition at line 54 of file tic_tac_toe.py.
_GAME_TYPE
open_spiel.python.games.tic_tac_toe._GAME_TYPE protected
Initial value:
=  pyspiel.GameType(
    short_name="python_tic_tac_toe",
    long_name="Python Tic-Tac-Toe",
    dynamics=pyspiel.GameType.Dynamics.SEQUENTIAL,
    chance_mode=pyspiel.GameType.ChanceMode.DETERMINISTIC,
    information=pyspiel.GameType.Information.PERFECT_INFORMATION,
    utility=pyspiel.GameType.Utility.ZERO_SUM,
    reward_model=pyspiel.GameType.RewardModel.TERMINAL,
    max_num_players=_NUM_PLAYERS,
    min_num_players=_NUM_PLAYERS,
    provides_information_state_string=True,
    provides_information_state_tensor=False,
    provides_observation_string=True,
    provides_observation_tensor=True,
    parameter_specification={})
Definition at line 39 of file tic_tac_toe.py.
_NUM_CELLS
int open_spiel.python.games.tic_tac_toe._NUM_CELLS = _NUM_ROWS * _NUM_COLS protected
Definition at line 38 of file tic_tac_toe.py.
_NUM_COLS
int open_spiel.python.games.tic_tac_toe._NUM_COLS = 3 protected
Definition at line 37 of file tic_tac_toe.py.
_NUM_PLAYERS
int open_spiel.python.games.tic_tac_toe._NUM_PLAYERS = 2 protected
Definition at line 35 of file tic_tac_toe.py.
_NUM_ROWS
int open_spiel.python.games.tic_tac_toe._NUM_ROWS = 3 protected
Definition at line 36 of file tic_tac_toe.py.