open spiel: pybind11::google::internal Namespace Reference
pybind11::google::internal Namespace Reference
Functions
bool IsStatusModuleImported ()
void CheckStatusModuleImported ()
void RegisterStatusBindings (module m)
Function Documentation
CheckStatusModuleImported()
void pybind11::google::internal::CheckStatusModuleImported () inline
Definition at line 19 of file check_status_module_imported.h.
{
#ifndef NDEBUG
  if (!IsStatusModuleImported())
    throw type_error(
        "Status module has not been imported. Did you call ::pybind11::google"
        "::ImportStatusModule() in your PYBIND11_MODULE definition?");
#endif
}
References IsStatusModuleImported().
IsStatusModuleImported()
bool pybind11::google::internal::IsStatusModuleImported () inline
Definition at line 13 of file check_status_module_imported.h.
{
  return detail::get_type_info(typeid(absl::Status));
}
Referenced by CheckStatusModuleImported(), and pybind11::google::ImportStatusModule().
RegisterStatusBindings()
void pybind11::google::internal::RegisterStatusBindings (module m)
Definition at line 110 of file register_status_bindings.cc.
{
  enum_<absl::StatusCode>(m, "StatusCode")
      .value("OK", absl::StatusCode::kOk)
      .value("CANCELLED", absl::StatusCode::kCancelled)
      .value("UNKNOWN", absl::StatusCode::kUnknown)
      .value("INVALID_ARGUMENT", absl::StatusCode::kInvalidArgument)
      .value("DEADLINE_EXCEEDED", absl::StatusCode::kDeadlineExceeded)
      .value("NOT_FOUND", absl::StatusCode::kNotFound)
      .value("ALREADY_EXISTS", absl::StatusCode::kAlreadyExists)
      .value("PERMISSION_DENIED", absl::StatusCode::kPermissionDenied)
      .value("RESOURCE_EXHAUSTED", absl::StatusCode::kResourceExhausted)
      .value("FAILED_PRECONDITION", absl::StatusCode::kFailedPrecondition)
      .value("ABORTED", absl::StatusCode::kAborted)
      .value("OUT_OF_RANGE", absl::StatusCode::kOutOfRange)
      .value("UNIMPLEMENTED", absl::StatusCode::kUnimplemented)
      .value("INTERNAL", absl::StatusCode::kInternal)
      .value("UNAVAILABLE", absl::StatusCode::kUnavailable)
      .value("DATA_LOSS", absl::StatusCode::kDataLoss)
      .value("UNAUTHENTICATED", absl::StatusCode::kUnauthenticated);
  class_<absl::Status>(m, "Status")
      .def(init())
      .def(init<absl::StatusCode, std::string>())
      .def("ok", &absl::Status::ok)
      .def("code", &absl::Status::code)
      .def("code_int", [](const absl::Status& self) {
          return static_cast<int>(self.code());
      })
      .def("message", &absl::Status::message)
      .def(
          "update",
          (void (absl::Status::*)(const absl::Status &)) & absl::Status::Update,
          arg("other"))
      .def("to_string", [](const absl::Status& s) { return s.ToString(); })
      .def("__repr__", [](const absl::Status& s) { return s.ToString(); })
      .def_static("OkStatus", DoNotThrowStatus(&absl::OkStatus))
      .def("raw_code", &absl::Status::raw_code)
      .def("CanonicalCode", [](const absl::Status& self) {
          return static_cast<int>(self.code());
      })
      .def("error_message", &absl::Status::message)
      .def("IgnoreError", &absl::Status::IgnoreError);
  m.def("is_ok", &IsOk, arg("status_or"),
        "Returns false only if passed a non-ok status; otherwise returns true. "
        "This can be used on the return value of a function which returns a "
        "StatusOr without raising an exception. The .ok() method cannot be "
        "used in this case because an ok status is never returned; instead, a "
        "non-status object is returned, which doesn't have a .ok() method.");
  // Return canonical errors.
  def_status_factory(m, "aborted_error", WrapAbortedError);
  def_status_factory(m, "already_exists_error", WrapAlreadyExistsError);
  def_status_factory(m, "cancelled_error", WrapCancelledError);
  def_status_factory(m, "data_loss_error", WrapDataLossError);
  def_status_factory(m, "deadline_exceeded_error", WrapDeadlineExceededError);
  def_status_factory(m, "failed_precondition_error",
                     WrapFailedPreconditionError);
  def_status_factory(m, "internal_error", WrapInternalError);
  def_status_factory(m, "invalid_argument_error", WrapInvalidArgumentError);
  def_status_factory(m, "not_found_error", WrapNotFoundError);
  def_status_factory(m, "out_of_range_error", WrapOutOfRangeError);
  def_status_factory(m, "permission_denied_error", WrapPermissionDeniedError);
  def_status_factory(m, "resource_exhausted_error", WrapResourceExhaustedError);
  def_status_factory(m, "unauthenticated_error", WrapUnauthenticatedError);
  def_status_factory(m, "unavailable_error", WrapUnavailableError);
  def_status_factory(m, "unimplemented_error", WrapUnimplementedError);
  def_status_factory(m, "unknown_error", WrapUnknownError);
  // Generate the Python exception type.
  static exception<StatusNotOk> PyStatusNotOk(m, "StatusNotOk");
  // Register a custom handler which converts a C++ StatusNotOk to a
  // PyStatusNotOk.
  register_exception_translator([](std::exception_ptr p) {
    try {
      if (p) std::rethrow_exception(p);
    } catch (const StatusNotOk& e) {
      PyErr_SetObject(PyStatusNotOk.ptr(),
                      BuildStatusNotOk(PyStatusNotOk, e).ptr());
    }
  });
  m.def("BuildStatusNotOk", [](int code, const std::string& msg) {
    return BuildStatusNotOk(
        PyStatusNotOk,
        StatusNotOk(absl::Status(static_cast<absl::StatusCode>(code), msg)));
  });
}
References arg, absl::Status::code(), pybind11::google::DoNotThrowStatus(), absl::Status::IgnoreError(), absl::kAborted, absl::kAlreadyExists, absl::kCancelled, absl::kDataLoss, absl::kDeadlineExceeded, absl::kFailedPrecondition, absl::kInternal, absl::kInvalidArgument, absl::kNotFound, absl::kOk, absl::kOutOfRange, absl::kPermissionDenied, absl::kResourceExhausted, absl::kUnauthenticated, absl::kUnavailable, absl::kUnimplemented, absl::kUnknown, absl::Status::message(), absl::Status::ok(), absl::OkStatus(), ptr, absl::Status::raw_code(), and absl::Status::Update().
Referenced by pybind11::google::ImportStatusModule(), and pybind11::google::PYBIND11_MODULE().