open spiel: absl::str_format_internal Namespace Reference
absl::str_format_internal Namespace Reference
Classes
struct ArgConvertResult
class BoundConversion
class BufferRawSink
class ConvTag
struct ConvTagHolder
class ExtendedParsedFormat
class FILERawSink
class FormatArgImpl
struct FormatArgImplFriend
struct FormatConversionCharInternal
struct FormatConversionCharSetInternal
class FormatConversionSpecImpl
struct FormatConversionSpecImplFriend
struct FormatCountCaptureHelper
class FormatRawSinkImpl
class FormatSinkImpl
class FormatSpecTemplate
struct HasUserDefinedConvert
struct HasUserDefinedConvert< T, void_t< decltype(AbslFormatConvert(std::declval< const T & >(), std::declval< const FormatConversionSpec & >(), std::declval< FormatSink * >()))> >
struct MakeDependent
class ParsedFormatBase
class Streamable
class StreamedWrapper
struct UnboundConversion
class UntypedFormatSpecImpl
struct VoidPtr
Typedefs
using IntegralConvertResult
using FloatingConvertResult
using CharConvertResult
using StringConvertResult
Enumerations
enum class LengthMod : std::uint8_t {
h , hh , l , ll ,
L , j , z , t ,
q , none
}
enum class Flags : uint8_t {
kBasic = 0 , kLeft = 1 << 0 , kShowPos = 1 << 1 , kSignCol = 1 << 2 ,
kAlt = 1 << 3 , kZero = 1 << 4 , kNonBasic = 1 << 5
}
Functions
bool ConvertBoolArg (bool v, FormatSinkImpl *sink)
template<typename T >
bool ConvertIntArg (T v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< char > (char v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< signed char > (signed char v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< unsigned char > (unsigned char v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< short > (short v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< unsigned short > (unsigned short v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< int > (int v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< unsigned int > (unsigned int v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< long > (long v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< unsigned long > (unsigned long v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< long long > (long long v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template bool ConvertIntArg< unsigned long long > (unsigned long long v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
StringConvertResult FormatConvertImpl (const std::string &v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
StringConvertResult FormatConvertImpl (string_view v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
ArgConvertResult< FormatConversionCharSetUnion(FormatConversionCharSetInternal::s, FormatConversionCharSetInternal::p)> FormatConvertImpl (const char *v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
ArgConvertResult< FormatConversionCharSetInternal::p > FormatConvertImpl (VoidPtr v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
FloatingConvertResult FormatConvertImpl (float v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
FloatingConvertResult FormatConvertImpl (double v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
FloatingConvertResult FormatConvertImpl (long double v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
CharConvertResult FormatConvertImpl (char v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
CharConvertResult FormatConvertImpl (signed char v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
CharConvertResult FormatConvertImpl (unsigned char v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (short v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (unsigned short v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (int v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (unsigned v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (long v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (unsigned long v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (long long v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (unsigned long long v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (absl::int128 v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
IntegralConvertResult FormatConvertImpl (absl::uint128 v, const FormatConversionSpecImpl conv, FormatSinkImpl *sink)
ABSL_INTERNAL_FORMAT_DISPATCH_OVERLOADS_EXPAND_ ()
void AbslFormatConvert ()
void AbslStringify ()
template<typename T >
auto FormatConvertImpl (const T &v, FormatConversionSpecImpl conv, FormatSinkImpl *sink) -> decltype(AbslFormatConvert(v, std::declval< const FormatConversionSpec & >(), std::declval< FormatSink * >()))
template<FormatConversionCharSet C>
constexpr FormatConversionCharSet ExtractCharSet (FormatConvertResult< C >)
template<FormatConversionCharSet C>
constexpr FormatConversionCharSet ExtractCharSet (ArgConvertResult< C >)
template<class AbslCord , typename std::enable_if< std::is_same< AbslCord, absl::Cord >::value >::type * = nullptr>
StringConvertResult FormatConvertImpl (const AbslCord &value, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template<typename T , enable_if_t< std::is_same< T, bool >::value, int > = 0>
IntegralConvertResult FormatConvertImpl (T v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template<typename T >
std::enable_if< std::is_enum< T >::value &&!HasUserDefinedConvert< T >::value &&!strings_internal::HasAbslStringify< T >::value, IntegralConvertResult >::type FormatConvertImpl (T v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template<typename T >
StringConvertResult FormatConvertImpl (const StreamedWrapper< T > &v, FormatConversionSpecImpl conv, FormatSinkImpl *out)
template<class T = int>
ArgConvertResult< FormatConversionCharSetInternal::n > FormatConvertImpl (const FormatCountCapture &v, FormatConversionSpecImpl conv, FormatSinkImpl *sink)
template<typename Arg >
constexpr FormatConversionCharSet ArgumentToConv ()
ABSL_INTERNAL_FORMAT_DISPATCH_OVERLOADS_EXPAND_ (extern)
bool BindWithPack (const UnboundConversion *props, absl::Span< const FormatArgImpl > pack, BoundConversion *bound)
std::string Summarize (const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
bool FormatUntyped (FormatRawSinkImpl raw_sink, const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
std::string & AppendPack (std::string *out, const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
std::string FormatPack (const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
int FprintF (std::FILE *output, const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
int SnprintF (char *output, size_t size, const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
constexpr ConvTag GetTagForChar (char c)
constexpr bool CheckFastPathSetting (const UnboundConversion &conv)
constexpr int ParseDigits (char &c, const char *&pos, const char *const end)
template<bool is_positional>
constexpr const char * ConsumeConversion (const char *pos, const char *const end, UnboundConversion *conv, int *next_arg)
constexpr const char * ConsumeUnboundConversion (const char *p, const char *end, UnboundConversion *conv, int *next_arg)
std::string FlagsToString (Flags v)
constexpr Flags operator| (Flags a, Flags b)
constexpr bool FlagsContains (Flags haystack, Flags needle)
std::ostream & operator<< (std::ostream &os, Flags v)
FormatConversionChar FormatConversionCharFromChar (char c)
bool FormatConversionCharIsUpper (FormatConversionChar c)
bool FormatConversionCharIsFloat (FormatConversionChar c)
char FormatConversionCharToChar (FormatConversionChar c)
std::ostream & operator<< (std::ostream &os, FormatConversionChar v)
constexpr FormatConversionCharSet FormatConversionCharSetUnion (FormatConversionCharSet a)
template<typename... CharSet>
constexpr FormatConversionCharSet FormatConversionCharSetUnion (FormatConversionCharSet a, CharSet... rest)
constexpr uint64_t FormatConversionCharToConvInt (FormatConversionChar c)
constexpr uint64_t FormatConversionCharToConvInt (char conv)
constexpr FormatConversionCharSet FormatConversionCharToConvValue (char conv)
constexpr FormatConversionCharSet operator| (FormatConversionCharSet a, FormatConversionCharSet b)
constexpr FormatConversionCharSet ToFormatConversionCharSet (char c)
constexpr FormatConversionCharSet ToFormatConversionCharSet (FormatConversionCharSet c)
template<typename T >
void ToFormatConversionCharSet (T)=delete
constexpr bool Contains (FormatConversionCharSet set, char c)
constexpr bool Contains (FormatConversionCharSet set, FormatConversionCharSet c)
constexpr bool Contains (FormatConversionCharSet set, FormatConversionChar c)
size_t Excess (size_t used, size_t capacity)
bool ConvertFloatImpl (long double v, const FormatConversionSpecImpl &conv, FormatSinkImpl *sink)
bool ConvertFloatImpl (float v, const FormatConversionSpecImpl &conv, FormatSinkImpl *sink)
bool ConvertFloatImpl (double v, const FormatConversionSpecImpl &conv, FormatSinkImpl *sink)
void AbslFormatFlush (std::string *out, string_view s)
void AbslFormatFlush (std::ostream *out, string_view s)
void AbslFormatFlush (FILERawSink *sink, string_view v)
void AbslFormatFlush (BufferRawSink *sink, string_view v)
template<typename T >
auto InvokeFlush (T *out, string_view s) -> decltype(AbslFormatFlush(out, s))
ABSL_ATTRIBUTE_NOINLINE const char * ConsumeUnboundConversionNoInline (const char *p, const char *end, UnboundConversion *conv, int *next_arg)
std::string LengthModToString (LengthMod v)
template<typename Consumer >
bool ParseFormatString (string_view src, Consumer consumer)
constexpr bool EnsureConstexpr (string_view s)
Typedef Documentation
CharConvertResult
using absl::str_format_internal::CharConvertResult
Initial value:
 ArgConvertResult<FormatConversionCharSetUnion(
    FormatConversionCharSetInternal::c,
    FormatConversionCharSetInternal::kNumeric,
    FormatConversionCharSetInternal::kStar)>
Definition at line 64 of file arg.h.
FloatingConvertResult
using absl::str_format_internal::FloatingConvertResult
Initial value:
 ArgConvertResult<FormatConversionCharSetUnion(
    FormatConversionCharSetInternal::kFloating,
    FormatConversionCharSetInternal::v)>
Definition at line 61 of file arg.h.
IntegralConvertResult
using absl::str_format_internal::IntegralConvertResult
Initial value:
 ArgConvertResult<FormatConversionCharSetUnion(
    FormatConversionCharSetInternal::c,
    FormatConversionCharSetInternal::kNumeric,
    FormatConversionCharSetInternal::kStar,
    FormatConversionCharSetInternal::v)>
Definition at line 56 of file arg.h.
StringConvertResult
using absl::str_format_internal::StringConvertResult
Initial value:
 ArgConvertResult<FormatConversionCharSetUnion(
    FormatConversionCharSetInternal::s, FormatConversionCharSetInternal::v)>
Definition at line 205 of file arg.h.
Enumeration Type Documentation
Flags
enum class absl::str_format_internal::Flags : uint8_t strong
Enumerator
kBasic
kLeft
kShowPos
kSignCol
kAlt
kZero
kNonBasic
Definition at line 134 of file extension.h.
                 : uint8_t {
  kBasic = 0,
  kLeft = 1 << 0,
  kShowPos = 1 << 1,
  kSignCol = 1 << 2,
  kAlt = 1 << 3,
  kZero = 1 << 4,
  // This is not a real flag. It just exists to turn off kBasic when no other
  // flags are set. This is for when width/precision are specified.
  kNonBasic = 1 << 5,
};
LengthMod
enum class absl::str_format_internal::LengthMod : std::uint8_t strong
Enumerator
h
hh
l
ll
L
j
z
t
q
none
Definition at line 29 of file constexpr_parser.h.
: std::uint8_t { h, hh, l, ll, L, j, z, t, q, none };
Function Documentation
ABSL_INTERNAL_FORMAT_DISPATCH_OVERLOADS_EXPAND_() [1/2]
absl::str_format_internal::ABSL_INTERNAL_FORMAT_DISPATCH_OVERLOADS_EXPAND_ ()
ABSL_INTERNAL_FORMAT_DISPATCH_OVERLOADS_EXPAND_() [2/2]
absl::str_format_internal::ABSL_INTERNAL_FORMAT_DISPATCH_OVERLOADS_EXPAND_ (extern)
AbslFormatConvert()
void absl::str_format_internal::AbslFormatConvert ()
Referenced by FormatConvertImpl().
AbslFormatFlush() [1/4]
void absl::str_format_internal::AbslFormatFlush (BufferRawSink * sink, string_view v) inline
Definition at line 82 of file output.h.
{
  sink->Write(v);
}
References sink, and absl::v.
AbslFormatFlush() [2/4]
void absl::str_format_internal::AbslFormatFlush (FILERawSink * sink, string_view v) inline
Definition at line 78 of file output.h.
{
  sink->Write(v);
}
References sink, and absl::v.
AbslFormatFlush() [3/4]
void absl::str_format_internal::AbslFormatFlush (std::ostream * out, string_view s) inline
Definition at line 74 of file output.h.
{
  out->write(s.data(), static_cast<std::streamsize>(s.size()));
}
References absl::out, and absl::s.
AbslFormatFlush() [4/4]
void absl::str_format_internal::AbslFormatFlush (std::string * out, string_view s) inline
Definition at line 71 of file output.h.
{
  out->append(s.data(), s.size());
}
References absl::out, and absl::s.
Referenced by InvokeFlush().
AbslStringify()
void absl::str_format_internal::AbslStringify ()
AppendPack()
std::string & absl::str_format_internal::AppendPack (std::string * out, const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
Definition at line 209 of file bind.cc.
{
  size_t orig = out->size();
  if (ABSL_PREDICT_FALSE(!FormatUntyped(out, format, args))) {
    out->erase(orig);
  }
  return *out;
}
References ABSL_PREDICT_FALSE, FormatUntyped(), and absl::out.
Referenced by absl::StrAppendFormat(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), and absl::ABSL_NAMESPACE_BEGIN::TEST_F().
ArgumentToConv()
template<typename Arg > FormatConversionCharSet absl::str_format_internal::ArgumentToConv () constexpr
Definition at line 398 of file arg.h.
{
  using ConvResult = decltype(str_format_internal::FormatConvertImpl(
      std::declval<const Arg&>(),
      std::declval<const FormatConversionSpecImpl&>(),
      std::declval<FormatSinkImpl*>()));
  return absl::str_format_internal::ExtractCharSet(ConvResult{});
}
References ExtractCharSet(), and FormatConvertImpl().
BindWithPack()
bool absl::str_format_internal::BindWithPack (const UnboundConversion * props, absl::Span< const FormatArgImpl > pack, BoundConversion * bound)
Definition at line 175 of file bind.cc.
{
  return ArgContext(pack).Bind(props, bound);
}
CheckFastPathSetting()
bool absl::str_format_internal::CheckFastPathSetting (const UnboundConversion & conv) constexpr
Definition at line 172 of file constexpr_parser.h.
{
  bool width_precision_needed =
      conv.width.value() >= 0 || conv.precision.value() >= 0;
  if (width_precision_needed && conv.flags == Flags::kBasic) {
#if defined(__clang__)
    // Some compilers complain about this in constexpr even when not executed,
    // so only enable the error dump in clang.
    fprintf(stderr,
            "basic=%d left=%d show_pos=%d sign_col=%d alt=%d zero=%d "
            "width=%d precision=%d\n",
            conv.flags == Flags::kBasic ? 1 : 0,
            FlagsContains(conv.flags, Flags::kLeft) ? 1 : 0,
            FlagsContains(conv.flags, Flags::kShowPos) ? 1 : 0,
            FlagsContains(conv.flags, Flags::kSignCol) ? 1 : 0,
            FlagsContains(conv.flags, Flags::kAlt) ? 1 : 0,
            FlagsContains(conv.flags, Flags::kZero) ? 1 : 0, conv.width.value(),
            conv.precision.value());
#endif  // defined(__clang__)
    return false;
  }
  return true;
}
References conv, FlagsContains(), kAlt, kBasic, kLeft, kShowPos, kSignCol, kZero, absl::str_format_internal::FormatConversionSpecImpl::precision(), and absl::str_format_internal::FormatConversionSpecImpl::width().
Referenced by ConsumeConversion().
ConsumeConversion()
template<bool is_positional> const char * absl::str_format_internal::ConsumeConversion (const char * pos, const char *const end, UnboundConversion * conv, int * next_arg) constexpr
Definition at line 213 of file constexpr_parser.h.
{
  const char* const original_pos = pos;
  char c = 0;
  // Read the next char into `c` and update `pos`. Returns false if there are
  // no more chars to read.
#define ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR()          \
  do {                                                  \
    if (ABSL_PREDICT_FALSE(pos == end)) return nullptr; \
    c = *pos++;                                         \
  } while (0)
  if (is_positional) {
    ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
    if (ABSL_PREDICT_FALSE(c < '1' || c > '9')) return nullptr;
    conv->arg_position = ParseDigits(c, pos, end);
    assert(conv->arg_position > 0);
    if (ABSL_PREDICT_FALSE(c != '$')) return nullptr;
  }
  ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
  // We should start with the basic flag on.
  assert(conv->flags == Flags::kBasic);
  // Any non alpha character makes this conversion not basic.
  // This includes flags (-+ #0), width (1-9, *) or precision (.).
  // All conversion characters and length modifiers are alpha characters.
  if (c < 'A') {
    while (c <= '0') {
      auto tag = GetTagForChar(c);
      if (tag.is_flags()) {
        conv->flags = conv->flags | tag.as_flags();
        ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
      } else {
        break;
      }
    }
    if (c <= '9') {
      if (c >= '0') {
        int maybe_width = ParseDigits(c, pos, end);
        if (!is_positional && c == '$') {
          if (ABSL_PREDICT_FALSE(*next_arg != 0)) return nullptr;
          // Positional conversion.
          *next_arg = -1;
          return ConsumeConversion<true>(original_pos, end, conv, next_arg);
        }
        conv->flags = conv->flags | Flags::kNonBasic;
        conv->width.set_value(maybe_width);
      } else if (c == '*') {
        conv->flags = conv->flags | Flags::kNonBasic;
        ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
        if (is_positional) {
          if (ABSL_PREDICT_FALSE(c < '1' || c > '9')) return nullptr;
          conv->width.set_from_arg(ParseDigits(c, pos, end));
          if (ABSL_PREDICT_FALSE(c != '$')) return nullptr;
          ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
        } else {
          conv->width.set_from_arg(++*next_arg);
        }
      }
    }
    if (c == '.') {
      conv->flags = conv->flags | Flags::kNonBasic;
      ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
      if ('0' <= c && c <= '9') {
        conv->precision.set_value(ParseDigits(c, pos, end));
      } else if (c == '*') {
        ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
        if (is_positional) {
          if (ABSL_PREDICT_FALSE(c < '1' || c > '9')) return nullptr;
          conv->precision.set_from_arg(ParseDigits(c, pos, end));
          if (c != '$') return nullptr;
          ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
        } else {
          conv->precision.set_from_arg(++*next_arg);
        }
      } else {
        conv->precision.set_value(0);
      }
    }
  }
  auto tag = GetTagForChar(c);
  if (ABSL_PREDICT_FALSE(c == 'v' && conv->flags != Flags::kBasic)) {
    return nullptr;
  }
  if (ABSL_PREDICT_FALSE(!tag.is_conv())) {
    if (ABSL_PREDICT_FALSE(!tag.is_length())) return nullptr;
    // It is a length modifier.
    using str_format_internal::LengthMod;
    LengthMod length_mod = tag.as_length();
    ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
    if (c == 'h' && length_mod == LengthMod::h) {
      conv->length_mod = LengthMod::hh;
      ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
    } else if (c == 'l' && length_mod == LengthMod::l) {
      conv->length_mod = LengthMod::ll;
      ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR();
    } else {
      conv->length_mod = length_mod;
    }
    tag = GetTagForChar(c);
    if (ABSL_PREDICT_FALSE(c == 'v')) return nullptr;
    if (ABSL_PREDICT_FALSE(!tag.is_conv())) return nullptr;
  }
  assert(CheckFastPathSetting(*conv));
  (void)(&CheckFastPathSetting);
  conv->conv = tag.as_conv();
  if (!is_positional) conv->arg_position = ++*next_arg;
  return pos;
}
References ABSL_FORMAT_PARSER_INTERNAL_GET_CHAR, ABSL_PREDICT_FALSE, absl::c, CheckFastPathSetting(), ConsumeConversion(), conv, GetTagForChar(), h, hh, kBasic, kNonBasic, l, ll, ParseDigits(), absl::str_format_internal::FormatConversionSpecImpl::precision(), and absl::str_format_internal::FormatConversionSpecImpl::width().
Referenced by ConsumeConversion(), and ConsumeUnboundConversion().
ConsumeUnboundConversion()
const char * absl::str_format_internal::ConsumeUnboundConversion (const char * p, const char * end, UnboundConversion * conv, int * next_arg) constexpr
Definition at line 340 of file constexpr_parser.h.
{
  if (*next_arg < 0) return ConsumeConversion<true>(p, end, conv, next_arg);
  return ConsumeConversion<false>(p, end, conv, next_arg);
}
References ConsumeConversion(), conv, and absl::p.
Referenced by ConsumeUnboundConversionNoInline().
ConsumeUnboundConversionNoInline()
const char * absl::str_format_internal::ConsumeUnboundConversionNoInline (const char * p, const char * end, UnboundConversion * conv, int * next_arg)
Definition at line 37 of file parser.cc.
{
  return ConsumeUnboundConversion(p, end, conv, next_arg);
}
References ConsumeUnboundConversion(), conv, and absl::p.
Referenced by ParseFormatString().
Contains() [1/3]
bool absl::str_format_internal::Contains (FormatConversionCharSet set, char c) constexpr
Definition at line 423 of file extension.h.
{
  return (static_cast<uint64_t>(set) &
          static_cast<uint64_t>(FormatConversionCharToConvValue(c))) != 0;
}
References absl::c, and FormatConversionCharToConvValue().
Contains() [2/3]
bool absl::str_format_internal::Contains (FormatConversionCharSet set, FormatConversionChar c) constexpr
Definition at line 436 of file extension.h.
{
  return (static_cast<uint64_t>(set) & FormatConversionCharToConvInt(c)) != 0;
}
References absl::c, and FormatConversionCharToConvInt().
Contains() [3/3]
bool absl::str_format_internal::Contains (FormatConversionCharSet set, FormatConversionCharSet c) constexpr
Definition at line 429 of file extension.h.
{
  return (static_cast<uint64_t>(set) & static_cast<uint64_t>(c)) ==
         static_cast<uint64_t>(c);
}
References absl::c.
ConvertBoolArg()
bool absl::str_format_internal::ConvertBoolArg (bool v, FormatSinkImpl * sink)
Definition at line 321 of file arg.cc.
{
  if (v) {
    sink->Append("true");
  } else {
    sink->Append("false");
  }
  return true;
}
References absl::str_format_internal::FormatSinkImpl::Append(), sink, and absl::v.
Referenced by FormatConvertImpl().
ConvertFloatImpl() [1/3]
bool absl::str_format_internal::ConvertFloatImpl (double v, const FormatConversionSpecImpl & conv, FormatSinkImpl * sink)
Definition at line 1450 of file float_conversion.cc.
{
  return FloatToSink(v, conv, sink);
}
References conv, sink, and absl::v.
ConvertFloatImpl() [2/3]
bool absl::str_format_internal::ConvertFloatImpl (float v, const FormatConversionSpecImpl & conv, FormatSinkImpl * sink)
Definition at line 1445 of file float_conversion.cc.
{
  return FloatToSink(static_cast<double>(v), conv, sink);
}
References conv, sink, and absl::v.
ConvertFloatImpl() [3/3]
bool absl::str_format_internal::ConvertFloatImpl (long double v, const FormatConversionSpecImpl & conv, FormatSinkImpl * sink)
Definition at line 1434 of file float_conversion.cc.
{
  if (IsDoubleDouble()) {
    // This is the `double-double` representation of `long double`. We do not
    // handle it natively. Fallback to snprintf.
    return FallbackToSnprintf(v, conv, sink);
  }
  return FloatToSink(v, conv, sink);
}
References conv, sink, and absl::v.
Referenced by ConvertIntArg().
ConvertIntArg()
template<typename T > bool absl::str_format_internal::ConvertIntArg (T v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 331 of file arg.cc.
{
  using U = typename MakeUnsigned<T>::type;
  IntDigits as_digits;
  if (conv.conversion_char() == FormatConversionCharInternal::v) {
    conv.set_conversion_char(ConvertV(T{}));
  }
  // This odd casting is due to a bug in -Wswitch behavior in gcc49 which causes
  // it to complain about a switch/case type mismatch, even though both are
  // FormatConverionChar.  Likely this is because at this point
  // FormatConversionChar is declared, but not defined.
  switch (static_cast<uint8_t>(conv.conversion_char())) {
    case static_cast<uint8_t>(FormatConversionCharInternal::c):
      return ConvertCharImpl(static_cast<char>(v), conv, sink);
    case static_cast<uint8_t>(FormatConversionCharInternal::o):
      as_digits.PrintAsOct(static_cast<U>(v));
      break;
    case static_cast<uint8_t>(FormatConversionCharInternal::x):
      as_digits.PrintAsHexLower(static_cast<U>(v));
      break;
    case static_cast<uint8_t>(FormatConversionCharInternal::X):
      as_digits.PrintAsHexUpper(static_cast<U>(v));
      break;
    case static_cast<uint8_t>(FormatConversionCharInternal::u):
      as_digits.PrintAsDec(static_cast<U>(v));
      break;
    case static_cast<uint8_t>(FormatConversionCharInternal::d):
    case static_cast<uint8_t>(FormatConversionCharInternal::i):
      as_digits.PrintAsDec(v);
      break;
    case static_cast<uint8_t>(FormatConversionCharInternal::a):
    case static_cast<uint8_t>(FormatConversionCharInternal::e):
    case static_cast<uint8_t>(FormatConversionCharInternal::f):
    case static_cast<uint8_t>(FormatConversionCharInternal::g):
    case static_cast<uint8_t>(FormatConversionCharInternal::A):
    case static_cast<uint8_t>(FormatConversionCharInternal::E):
    case static_cast<uint8_t>(FormatConversionCharInternal::F):
    case static_cast<uint8_t>(FormatConversionCharInternal::G):
      return ConvertFloatImpl(static_cast<double>(v), conv, sink);
    default:
      ABSL_ASSUME(false);
  }
  if (conv.is_basic()) {
    sink->Append(as_digits.with_neg_and_zero());
    return true;
  }
  return ConvertIntImplInnerSlow(as_digits, conv, sink);
}
References ABSL_ASSUME, absl::str_format_internal::FormatSinkImpl::Append(), conv, absl::str_format_internal::FormatConversionSpecImpl::conversion_char(), ConvertFloatImpl(), absl::str_format_internal::FormatConversionSpecImpl::is_basic(), absl::str_format_internal::FormatConversionSpecImpl::set_conversion_char(), sink, and absl::v.
Referenced by FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), FormatConvertImpl(), and FormatConvertImpl().
ConvertIntArg< char >()
template bool absl::str_format_internal::ConvertIntArg< char > (char v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< int >()
template bool absl::str_format_internal::ConvertIntArg< int > (int v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< long >()
template bool absl::str_format_internal::ConvertIntArg< long > (long v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< long long >()
template bool absl::str_format_internal::ConvertIntArg< long long > (long long v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< short >()
template bool absl::str_format_internal::ConvertIntArg< short > (short v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< signed char >()
template bool absl::str_format_internal::ConvertIntArg< signed char > (signed char v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< unsigned char >()
template bool absl::str_format_internal::ConvertIntArg< unsigned char > (unsigned char v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< unsigned int >()
template bool absl::str_format_internal::ConvertIntArg< unsigned int > (unsigned int v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< unsigned long >()
template bool absl::str_format_internal::ConvertIntArg< unsigned long > (unsigned long v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< unsigned long long >()
template bool absl::str_format_internal::ConvertIntArg< unsigned long long > (unsigned long long v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
ConvertIntArg< unsigned short >()
template bool absl::str_format_internal::ConvertIntArg< unsigned short > (unsigned short v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
EnsureConstexpr()
bool absl::str_format_internal::EnsureConstexpr (string_view s) constexpr
Definition at line 115 of file parser.h.
{
  return s.empty() || s[0] == s[0];
}
References absl::s.
Excess()
size_t absl::str_format_internal::Excess (size_t used, size_t capacity) inline
Definition at line 441 of file extension.h.
{
  return used < capacity ? capacity - used : 0;
}
Referenced by FormatConvertImpl(), and absl::str_format_internal::FormatSinkImpl::PutPaddedString().
ExtractCharSet() [1/2]
template<FormatConversionCharSet C> FormatConversionCharSet absl::str_format_internal::ExtractCharSet (ArgConvertResult< C >) constexpr
Definition at line 201 of file arg.h.
{
  return C;
}
References C.
ExtractCharSet() [2/2]
template<FormatConversionCharSet C> FormatConversionCharSet absl::str_format_internal::ExtractCharSet (FormatConvertResult< C >) constexpr
Definition at line 196 of file arg.h.
{
  return C;
}
References C.
Referenced by ArgumentToConv().
FlagsContains()
bool absl::str_format_internal::FlagsContains (Flags haystack, Flags needle) constexpr
Definition at line 150 of file extension.h.
{
  return (static_cast<uint8_t>(haystack) & static_cast<uint8_t>(needle)) ==
         static_cast<uint8_t>(needle);
}
Referenced by CheckFastPathSetting(), FlagsToString(), absl::str_format_internal::FormatConversionSpecImpl::has_alt_flag(), absl::str_format_internal::FormatConversionSpecImpl::has_left_flag(), absl::str_format_internal::FormatConversionSpecImpl::has_show_pos_flag(), absl::str_format_internal::FormatConversionSpecImpl::has_sign_col_flag(), and absl::str_format_internal::FormatConversionSpecImpl::has_zero_flag().
FlagsToString()
std::string absl::str_format_internal::FlagsToString (Flags v)
Definition at line 26 of file extension.cc.
{
  std::string s;
  s.append(FlagsContains(v, Flags::kLeft) ? "-" : "");
  s.append(FlagsContains(v, Flags::kShowPos) ? "+" : "");
  s.append(FlagsContains(v, Flags::kSignCol) ? " " : "");
  s.append(FlagsContains(v, Flags::kAlt) ? "#" : "");
  s.append(FlagsContains(v, Flags::kZero) ? "0" : "");
  return s;
}
References FlagsContains(), kAlt, kLeft, kShowPos, kSignCol, kZero, absl::s, and absl::v.
Referenced by absl::str_format_internal::FormatConversionSpecImplFriend::FlagsToString(), and operator<<().
FormatConversionCharFromChar()
FormatConversionChar absl::str_format_internal::FormatConversionCharFromChar (char c) inline
Definition at line 209 of file extension.h.
{
  switch (c) {
#define ABSL_INTERNAL_X_VAL(id) \
  case #id[0]:                  \
    return FormatConversionCharInternal::id;
    ABSL_INTERNAL_CONVERSION_CHARS_EXPAND_(ABSL_INTERNAL_X_VAL, )
#undef ABSL_INTERNAL_X_VAL
  }
  return FormatConversionCharInternal::kNone;
}
References ABSL_INTERNAL_CONVERSION_CHARS_EXPAND_, ABSL_INTERNAL_X_VAL, absl::c, and absl::str_format_internal::FormatConversionCharInternal::kNone.
FormatConversionCharIsFloat()
bool absl::str_format_internal::FormatConversionCharIsFloat (FormatConversionChar c) inline
Definition at line 232 of file extension.h.
{
  if (c == FormatConversionCharInternal::a ||
      c == FormatConversionCharInternal::e ||
      c == FormatConversionCharInternal::f ||
      c == FormatConversionCharInternal::g ||
      c == FormatConversionCharInternal::A ||
      c == FormatConversionCharInternal::E ||
      c == FormatConversionCharInternal::F ||
      c == FormatConversionCharInternal::G) {
    return true;
  } else {
    return false;
  }
}
References absl::c.
FormatConversionCharIsUpper()
bool absl::str_format_internal::FormatConversionCharIsUpper (FormatConversionChar c) inline
Definition at line 220 of file extension.h.
{
  if (c == FormatConversionCharInternal::X ||
      c == FormatConversionCharInternal::F ||
      c == FormatConversionCharInternal::E ||
      c == FormatConversionCharInternal::G ||
      c == FormatConversionCharInternal::A) {
    return true;
  } else {
    return false;
  }
}
References absl::c.
FormatConversionCharSetUnion() [1/2]
FormatConversionCharSet absl::str_format_internal::FormatConversionCharSetUnion (FormatConversionCharSet a) constexpr
Definition at line 341 of file extension.h.
{
  return a;
}
References absl::a.
Referenced by FormatConversionCharSetUnion(), and operator|().
FormatConversionCharSetUnion() [2/2]
template<typename... CharSet> FormatConversionCharSet absl::str_format_internal::FormatConversionCharSetUnion (FormatConversionCharSet a, CharSet... rest) constexpr
Definition at line 347 of file extension.h.
{
  return static_cast<FormatConversionCharSet>(
      static_cast<uint64_t>(a) |
      static_cast<uint64_t>(FormatConversionCharSetUnion(rest...)));
}
References absl::a, and FormatConversionCharSetUnion().
FormatConversionCharToChar()
char absl::str_format_internal::FormatConversionCharToChar (FormatConversionChar c) inline
Definition at line 247 of file extension.h.
{
  if (c == FormatConversionCharInternal::kNone) {
    return '\0';
#define ABSL_INTERNAL_X_VAL(e)                       \
  } else if (c == FormatConversionCharInternal::e) { \
    return #e[0];
#define ABSL_INTERNAL_X_SEP
  ABSL_INTERNAL_CONVERSION_CHARS_EXPAND_(ABSL_INTERNAL_X_VAL,
                                         ABSL_INTERNAL_X_SEP)
  } else {
    return '\0';
  }
#undef ABSL_INTERNAL_X_VAL
#undef ABSL_INTERNAL_X_SEP
}
References ABSL_INTERNAL_CONVERSION_CHARS_EXPAND_, ABSL_INTERNAL_X_SEP, ABSL_INTERNAL_X_VAL, absl::c, and absl::str_format_internal::FormatConversionCharInternal::kNone.
Referenced by operator<<().
FormatConversionCharToConvInt() [1/2]
uint64_t absl::str_format_internal::FormatConversionCharToConvInt (char conv) constexpr
Definition at line 358 of file extension.h.
{
  return
#define ABSL_INTERNAL_CHAR_SET_CASE(c)                                 \
  conv == #c[0]                                                        \
      ? FormatConversionCharToConvInt(FormatConversionCharInternal::c) \
      :
      ABSL_INTERNAL_CONVERSION_CHARS_EXPAND_(ABSL_INTERNAL_CHAR_SET_CASE, )
#undef ABSL_INTERNAL_CHAR_SET_CASE
                  conv == '*'
          ? 1
          : 0;
}
References ABSL_INTERNAL_CHAR_SET_CASE, ABSL_INTERNAL_CONVERSION_CHARS_EXPAND_, and conv.
FormatConversionCharToConvInt() [2/2]
uint64_t absl::str_format_internal::FormatConversionCharToConvInt (FormatConversionChar c) constexpr
Definition at line 354 of file extension.h.
{
  return uint64_t{1} << (1 + static_cast<uint8_t>(c));
}
References absl::c.
Referenced by Contains(), and FormatConversionCharToConvValue().
FormatConversionCharToConvValue()
FormatConversionCharSet absl::str_format_internal::FormatConversionCharToConvValue (char conv) constexpr
Definition at line 371 of file extension.h.
{
  return static_cast<FormatConversionCharSet>(
      FormatConversionCharToConvInt(conv));
}
References conv, and FormatConversionCharToConvInt().
Referenced by Contains(), and ToFormatConversionCharSet().
FormatConvertImpl() [1/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (absl::int128 v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 537 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [2/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (absl::uint128 v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 542 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [3/26]
CharConvertResult absl::str_format_internal::FormatConvertImpl (char v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 481 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [4/26]
template<class AbslCord , typename std::enable_if< std::is_same< AbslCord, absl::Cord >::value >::type * = nullptr> StringConvertResult absl::str_format_internal::FormatConvertImpl (const AbslCord & value, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 232 of file arg.h.
{
  bool is_left = conv.has_left_flag();
  size_t space_remaining = 0;
  int width = conv.width();
  if (width >= 0) space_remaining = static_cast<size_t>(width);
  size_t to_write = value.size();
  int precision = conv.precision();
  if (precision >= 0)
    to_write = (std::min)(to_write, static_cast<size_t>(precision));
  space_remaining = Excess(to_write, space_remaining);
  if (space_remaining > 0 && !is_left) sink->Append(space_remaining, ' ');
  for (string_view piece : value.Chunks()) {
    if (piece.size() > to_write) {
      piece.remove_suffix(piece.size() - to_write);
      to_write = 0;
    } else {
      to_write -= piece.size();
    }
    sink->Append(piece);
    if (to_write == 0) {
      break;
    }
  }
  if (space_remaining > 0 && is_left) sink->Append(space_remaining, ' ');
  return {true};
}
References absl::str_format_internal::FormatSinkImpl::Append(), conv, Excess(), absl::str_format_internal::FormatConversionSpecImpl::has_left_flag(), absl::str_format_internal::FormatConversionSpecImpl::precision(), precision, sink, and absl::str_format_internal::FormatConversionSpecImpl::width().
FormatConvertImpl() [5/26]
ArgConvertResult< FormatConversionCharSetUnion(FormatConversionCharSetInternal::s, FormatConversionCharSetInternal::p)> absl::str_format_internal::FormatConvertImpl (const char * v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 435 of file arg.cc.
{
  if (conv.conversion_char() == FormatConversionCharInternal::p)
    return {FormatConvertImpl(VoidPtr(v), conv, sink).value};
  size_t len;
  if (v == nullptr) {
    len = 0;
  } else if (conv.precision() < 0) {
    len = std::strlen(v);
  } else {
    // If precision is set, we look for the NUL-terminator on the valid range.
    len = static_cast<size_t>(std::find(v, v + conv.precision(), '\0') - v);
  }
  return {ConvertStringArg(string_view(v, len), conv, sink)};
}
References conv, absl::str_format_internal::FormatConversionSpecImpl::conversion_char(), FormatConvertImpl(), len, absl::str_format_internal::FormatConversionSpecImpl::precision(), sink, absl::v, and absl::str_format_internal::ArgConvertResult< C >::value.
FormatConvertImpl() [6/26]
template<class T = int> ArgConvertResult< FormatConversionCharSetInternal::n > absl::str_format_internal::FormatConvertImpl (const FormatCountCapture & v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 369 of file arg.h.
{
  return FormatCountCaptureHelper::ConvertHelper(v, conv, sink);
}
References conv, absl::str_format_internal::FormatCountCaptureHelper::ConvertHelper(), sink, and absl::v.
FormatConvertImpl() [7/26]
StringConvertResult absl::str_format_internal::FormatConvertImpl (const std::string & v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 421 of file arg.cc.
{
  return {ConvertStringArg(v, conv, sink)};
}
References conv, sink, and absl::v.
Referenced by ArgumentToConv(), FormatConvertImpl(), FormatConvertImpl(), and FormatConvertImpl().
FormatConvertImpl() [8/26]
template<typename T > StringConvertResult absl::str_format_internal::FormatConvertImpl (const StreamedWrapper< T > & v, FormatConversionSpecImpl conv, FormatSinkImpl * out)
Definition at line 341 of file arg.h.
{
  std::ostringstream oss;
  oss << v.v_;
  if (!oss) return {false};
  return str_format_internal::FormatConvertImpl(oss.str(), conv, out);
}
References conv, FormatConvertImpl(), absl::out, and absl::v.
FormatConvertImpl() [9/26]
template<typename T > auto absl::str_format_internal::FormatConvertImpl (const T & v, FormatConversionSpecImpl conv, FormatSinkImpl * sink) -> decltype(AbslFormatConvert(v, std::declval<const FormatConversionSpec&>(), std::declval<FormatSink*>()))
Definition at line 124 of file arg.h.
{
  using FormatConversionSpecT =
      absl::enable_if_t<sizeof(const T& (*)()) != 0, FormatConversionSpec>;
  using FormatSinkT =
      absl::enable_if_t<sizeof(const T& (*)()) != 0, FormatSink>;
  auto fcs = conv.Wrap<FormatConversionSpecT>();
  auto fs = sink->Wrap<FormatSinkT>();
  return AbslFormatConvert(v, fcs, &fs);
}
References AbslFormatConvert(), conv, sink, absl::v, absl::str_format_internal::FormatConversionSpecImpl::Wrap(), and absl::str_format_internal::FormatSinkImpl::Wrap().
FormatConvertImpl() [10/26]
FloatingConvertResult absl::str_format_internal::FormatConvertImpl (double v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 469 of file arg.cc.
{
  return {ConvertFloatArg(v, conv, sink)};
}
References conv, sink, and absl::v.
FormatConvertImpl() [11/26]
FloatingConvertResult absl::str_format_internal::FormatConvertImpl (float v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 464 of file arg.cc.
{
  return {ConvertFloatArg(v, conv, sink)};
}
References conv, sink, and absl::v.
FormatConvertImpl() [12/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (int v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 507 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [13/26]
FloatingConvertResult absl::str_format_internal::FormatConvertImpl (long double v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 474 of file arg.cc.
{
  return {ConvertFloatArg(v, conv, sink)};
}
References conv, sink, and absl::v.
FormatConvertImpl() [14/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (long long v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 527 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [15/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (long v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 517 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [16/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (short v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 497 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [17/26]
CharConvertResult absl::str_format_internal::FormatConvertImpl (signed char v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 485 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [18/26]
StringConvertResult absl::str_format_internal::FormatConvertImpl (string_view v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 427 of file arg.cc.
{
  return {ConvertStringArg(v, conv, sink)};
}
References conv, sink, and absl::v.
FormatConvertImpl() [19/26]
template<typename T , enable_if_t< std::is_same< T, bool >::value, int > = 0> IntegralConvertResult absl::str_format_internal::FormatConvertImpl (T v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 322 of file arg.h.
{
  if (conv.conversion_char() == FormatConversionCharInternal::v) {
    return {ConvertBoolArg(v, sink)};
  }
  return FormatConvertImpl(static_cast<int>(v), conv, sink);
}
References conv, absl::str_format_internal::FormatConversionSpecImpl::conversion_char(), ConvertBoolArg(), FormatConvertImpl(), sink, and absl::v.
FormatConvertImpl() [20/26]
template<typename T > std::enable_if< std::is_enum< T >::value &&!HasUserDefinedConvert< T >::value &&!strings_internal::HasAbslStringify< T >::value, IntegralConvertResult >::type absl::str_format_internal::FormatConvertImpl (T v, FormatConversionSpecImpl conv, FormatSinkImpl * sink)
FormatConvertImpl() [21/26]
CharConvertResult absl::str_format_internal::FormatConvertImpl (unsigned char v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 490 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [22/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (unsigned long long v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 532 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [23/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (unsigned long v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 522 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [24/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (unsigned short v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 502 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [25/26]
IntegralConvertResult absl::str_format_internal::FormatConvertImpl (unsigned v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 512 of file arg.cc.
{
  return {ConvertIntArg(v, conv, sink)};
}
References conv, ConvertIntArg(), sink, and absl::v.
FormatConvertImpl() [26/26]
ArgConvertResult< FormatConversionCharSetInternal::p > absl::str_format_internal::FormatConvertImpl (VoidPtr v, const FormatConversionSpecImpl conv, FormatSinkImpl * sink)
Definition at line 452 of file arg.cc.
{
  if (!v.value) {
    sink->Append("(nil)");
    return {true};
  }
  IntDigits as_digits;
  as_digits.PrintAsHexLower(v.value);
  return {ConvertIntImplInnerSlow(as_digits, conv, sink)};
}
References absl::str_format_internal::FormatSinkImpl::Append(), conv, sink, and absl::v.
FormatPack()
std::string absl::str_format_internal::FormatPack (const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
Definition at line 218 of file bind.cc.
{
  std::string out;
  if (ABSL_PREDICT_FALSE(!FormatUntyped(&out, format, args))) {
    out.clear();
  }
  return out;
}
References ABSL_PREDICT_FALSE, FormatUntyped(), and absl::out.
Referenced by absl::StrFormat(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), absl::ABSL_NAMESPACE_BEGIN::TEST_F(), and absl::ABSL_NAMESPACE_BEGIN::TEST_F().
FormatUntyped()
bool absl::str_format_internal::FormatUntyped (FormatRawSinkImpl raw_sink, const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
Definition at line 196 of file bind.cc.
{
  FormatSinkImpl sink(raw_sink);
  using Converter = DefaultConverter;
  return ConvertAll(format, args, Converter(&sink));
}
References sink.
Referenced by AppendPack(), absl::Format(), FormatPack(), absl::FormatUntyped(), FprintF(), absl::str_format_internal::Streamable::Print(), SnprintF(), and absl::ABSL_NAMESPACE_BEGIN::TEST_F().
FprintF()
int absl::str_format_internal::FprintF (std::FILE * output, const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
Definition at line 227 of file bind.cc.
{
  FILERawSink sink(output);
  if (!FormatUntyped(&sink, format, args)) {
    errno = EINVAL;
    return -1;
  }
  if (sink.error()) {
    errno = sink.error();
    return -1;
  }
  if (sink.count() > static_cast<size_t>(std::numeric_limits<int>::max())) {
    errno = EFBIG;
    return -1;
  }
  return static_cast<int>(sink.count());
}
References FormatUntyped(), and sink.
Referenced by absl::FPrintF(), and absl::PrintF().
GetTagForChar()
ConvTag absl::str_format_internal::GetTagForChar (char c) constexpr
Definition at line 168 of file constexpr_parser.h.
{
  return ConvTagHolder::value[static_cast<unsigned char>(c)];
}
References absl::c, and absl::str_format_internal::ConvTagHolder::value.
Referenced by ConsumeConversion(), and ParseFormatString().
InvokeFlush()
template<typename T > auto absl::str_format_internal::InvokeFlush (T * out, string_view s) -> decltype(AbslFormatFlush(out, s))
Definition at line 89 of file output.h.
{
  AbslFormatFlush(out, s);
}
References AbslFormatFlush(), absl::out, and absl::s.
Referenced by absl::ABSL_NAMESPACE_BEGIN::TEST(), absl::ABSL_NAMESPACE_BEGIN::TEST(), absl::ABSL_NAMESPACE_BEGIN::TEST(), and absl::ABSL_NAMESPACE_BEGIN::TEST().
LengthModToString()
std::string absl::str_format_internal::LengthModToString (LengthMod v)
Definition at line 42 of file parser.cc.
{
  switch (v) {
    case LengthMod::h:
      return "h";
    case LengthMod::hh:
      return "hh";
    case LengthMod::l:
      return "l";
    case LengthMod::ll:
      return "ll";
    case LengthMod::L:
      return "L";
    case LengthMod::j:
      return "j";
    case LengthMod::z:
      return "z";
    case LengthMod::t:
      return "t";
    case LengthMod::q:
      return "q";
    case LengthMod::none:
      return "";
  }
  return "";
}
References h, hh, j, L, l, ll, none, q, t, absl::v, and z.
operator<<() [1/2]
std::ostream & absl::str_format_internal::operator<< (std::ostream & os, Flags v) inline
Definition at line 157 of file extension.h.
{
  return os << FlagsToString(v);
}
References FlagsToString(), and absl::v.
operator<<() [2/2]
std::ostream & absl::str_format_internal::operator<< (std::ostream & os, FormatConversionChar v) inline
Definition at line 266 of file extension.h.
{
  char c = FormatConversionCharToChar(v);
  if (!c) c = '?';
  return os << c;
}
References absl::c, FormatConversionCharToChar(), and absl::v.
operator|() [1/2]
Flags absl::str_format_internal::operator| (Flags a, Flags b) constexpr
Definition at line 146 of file extension.h.
{
  return static_cast<Flags>(static_cast<uint8_t>(a) | static_cast<uint8_t>(b));
}
References absl::a, and b.
operator|() [2/2]
FormatConversionCharSet absl::str_format_internal::operator| (FormatConversionCharSet a, FormatConversionCharSet b) constexpr
Definition at line 401 of file extension.h.
{
  return FormatConversionCharSetUnion(a, b);
}
References absl::a, b, and FormatConversionCharSetUnion().
ParseDigits()
int absl::str_format_internal::ParseDigits (char & c, const char *& pos, const char *const end) constexpr
Definition at line 195 of file constexpr_parser.h.
{
  int digits = c - '0';
  // We do not want to overflow `digits` so we consume at most digits10
  // digits. If there are more digits the parsing will fail later on when the
  // digit doesn't match the expected characters.
  int num_digits = std::numeric_limits<int>::digits10;
  for (;;) {
    if (ABSL_PREDICT_FALSE(pos == end)) break;
    c = *pos++;
    if ('0' > c || c > '9') break;
    --num_digits;
    if (ABSL_PREDICT_FALSE(!num_digits)) break;
    digits = 10 * digits + c - '0';
  }
  return digits;
}
References ABSL_PREDICT_FALSE, and absl::c.
Referenced by ConsumeConversion().
ParseFormatString()
template<typename Consumer > bool absl::str_format_internal::ParseFormatString (string_view src, Consumer consumer)
Definition at line 56 of file parser.h.
{
  int next_arg = 0;
  const char* p = src.data();
  const char* const end = p + src.size();
  while (p != end) {
    const char* percent =
        static_cast<const char*>(memchr(p, '%', static_cast<size_t>(end - p)));
    if (!percent) {
      // We found the last substring.
      return consumer.Append(string_view(p, static_cast<size_t>(end - p)));
    }
    // We found a percent, so push the text run then process the percent.
    if (ABSL_PREDICT_FALSE(!consumer.Append(
            string_view(p, static_cast<size_t>(percent - p))))) {
      return false;
    }
    if (ABSL_PREDICT_FALSE(percent + 1 >= end)) return false;
    auto tag = GetTagForChar(percent[1]);
    if (tag.is_conv()) {
      if (ABSL_PREDICT_FALSE(next_arg < 0)) {
        // This indicates an error in the format string.
        // The only way to get `next_arg < 0` here is to have a positional
        // argument first which sets next_arg to -1 and then a non-positional
        // argument.
        return false;
      }
      p = percent + 2;
      // Keep this case separate from the one below.
      // ConvertOne is more efficient when the compiler can see that the `basic`
      // flag is set.
      UnboundConversion conv;
      conv.conv = tag.as_conv();
      conv.arg_position = ++next_arg;
      if (ABSL_PREDICT_FALSE(
              !consumer.ConvertOne(conv, string_view(percent + 1, 1)))) {
        return false;
      }
    } else if (percent[1] != '%') {
      UnboundConversion conv;
      p = ConsumeUnboundConversionNoInline(percent + 1, end, &conv, &next_arg);
      if (ABSL_PREDICT_FALSE(p == nullptr)) return false;
      if (ABSL_PREDICT_FALSE(!consumer.ConvertOne(
              conv, string_view(percent + 1,
                                static_cast<size_t>(p - (percent + 1)))))) {
        return false;
      }
    } else {
      if (ABSL_PREDICT_FALSE(!consumer.Append("%"))) return false;
      p = percent + 2;
      continue;
    }
  }
  return true;
}
References ABSL_PREDICT_FALSE, ConsumeUnboundConversionNoInline(), conv, absl::string_view::data(), GetTagForChar(), absl::p, and absl::string_view::size().
Referenced by absl::str_format_internal::ParsedFormatBase::ParsedFormatBase().
SnprintF()
int absl::str_format_internal::SnprintF (char * output, size_t size, const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
Definition at line 245 of file bind.cc.
{
  BufferRawSink sink(output, size ? size - 1 : 0);
  if (!FormatUntyped(&sink, format, args)) {
    errno = EINVAL;
    return -1;
  }
  size_t total = sink.total_written();
  if (size) output[std::min(total, size - 1)] = 0;
  return static_cast<int>(total);
}
References FormatUntyped(), sink, size, total, and absl::str_format_internal::BufferRawSink::total_written().
Referenced by absl::SNPrintF().
Summarize()
std::string absl::str_format_internal::Summarize (const UntypedFormatSpecImpl format, absl::Span< const FormatArgImpl > args)
Definition at line 181 of file bind.cc.
{
  typedef SummarizingConverter Converter;
  std::string out;
  {
    // inner block to destroy sink before returning out. It ensures a last
    // flush.
    FormatSinkImpl sink(&out);
    if (!ConvertAll(format, args, Converter(&sink))) {
      return "";
    }
  }
  return out;
}
References absl::out, and sink.
ToFormatConversionCharSet() [1/3]
FormatConversionCharSet absl::str_format_internal::ToFormatConversionCharSet (char c) constexpr
Definition at line 408 of file extension.h.
{
  return static_cast<FormatConversionCharSet>(
      FormatConversionCharToConvValue(c));
}
References absl::c, and FormatConversionCharToConvValue().
ToFormatConversionCharSet() [2/3]
FormatConversionCharSet absl::str_format_internal::ToFormatConversionCharSet (FormatConversionCharSet c) constexpr
Definition at line 414 of file extension.h.
{
  return c;
}
References absl::c.
ToFormatConversionCharSet() [3/3]
template<typename T > void absl::str_format_internal::ToFormatConversionCharSet (T) delete