open spiel: open_spiel::rbc Namespace Reference
open_spiel::rbc Namespace Reference
Classes
class RbcGame
class RbcObserver
class RbcState
Enumerations
enum class MovePhase { kSensing , kMoving }
Functions
constexpr int NumPlayers ()
constexpr double LossUtility ()
constexpr double DrawUtility ()
constexpr double WinUtility ()
constexpr int NumDistinctActions ()
constexpr int MaxGameLength ()
Variables
constexpr int kSenseLocationNonSpecified = -1
Enumeration Type Documentation
MovePhase
enum class open_spiel::rbc::MovePhase strong
Enumerator
kSensing
kMoving
Definition at line 126 of file rbc.h.
                     {
  kSensing,  // First sense.
  kMoving,   // Then make a regular move.
};
Function Documentation
DrawUtility()
double open_spiel::rbc::DrawUtility () inline constexpr
Definition at line 113 of file rbc.h.
{ return 0; }
Referenced by open_spiel::rbc::RbcGame::UtilitySum().
LossUtility()
double open_spiel::rbc::LossUtility () inline constexpr
Definition at line 112 of file rbc.h.
{ return -1; }
Referenced by open_spiel::rbc::RbcGame::MinUtility().
MaxGameLength()
int open_spiel::rbc::MaxGameLength () inline constexpr
Definition at line 120 of file rbc.h.
{ return 17695; }
NumDistinctActions()
int open_spiel::rbc::NumDistinctActions () inline constexpr
Definition at line 117 of file rbc.h.
{ return 4672; }
NumPlayers()
int open_spiel::rbc::NumPlayers () inline constexpr
Definition at line 111 of file rbc.h.
{ return 2; }
WinUtility()
double open_spiel::rbc::WinUtility () inline constexpr
Definition at line 114 of file rbc.h.
{ return 1; }
Referenced by open_spiel::rbc::RbcGame::MaxUtility().
Variable Documentation
kSenseLocationNonSpecified
int open_spiel::rbc::kSenseLocationNonSpecified = -1 constexpr
Definition at line 132 of file rbc.h.