open spiel: absl::synchronization_internal Namespace Reference
absl::synchronization_internal Namespace Reference
Classes
struct Edge
class GraphCycles
class GraphCyclesTest
struct GraphId
class KernelTimeout
class PerThreadSem
class PerThreadSemTest
class SimpleSemaphore
struct ThreadData
class ThreadPool
class Waiter
Typedefs
using Nodes = std::vector<int>
using Edges = std::vector<Edge>
using RandomEngine = std::mt19937_64
typedef std::map< int, GraphId > IdMap
Functions
int MutexDelay (int32_t c, int mode)
void OneTimeInitThreadIdentity (base_internal::ThreadIdentity *identity)
base_internal::ThreadIdentity * CreateThreadIdentity ()
base_internal::ThreadIdentity * GetOrCreateCurrentThreadIdentity ()
GraphId InvalidGraphId ()
TEST (GraphCycles, RandomizedTest)
TEST_F (GraphCyclesTest, NoCycle)
TEST_F (GraphCyclesTest, SimpleCycle)
TEST_F (GraphCyclesTest, IndirectCycle)
TEST_F (GraphCyclesTest, LongPath)
TEST_F (GraphCyclesTest, RemoveNode)
TEST_F (GraphCyclesTest, ManyEdges)
Typedef Documentation
Edges
using absl::synchronization_internal::Edges = std::vector<Edge>
Definition at line 39 of file graphcycles_test.cc.
IdMap
typedef std::map<int, GraphId> absl::synchronization_internal::IdMap
Definition at line 43 of file graphcycles_test.cc.
Nodes
using absl::synchronization_internal::Nodes = std::vector<int>
Definition at line 34 of file graphcycles_test.cc.
RandomEngine
using absl::synchronization_internal::RandomEngine = std::mt19937_64
Definition at line 40 of file graphcycles_test.cc.
Function Documentation
CreateThreadIdentity()
base_internal::ThreadIdentity * absl::synchronization_internal::CreateThreadIdentity ()
Definition at line 132 of file create_thread_identity.cc.
{
  base_internal::ThreadIdentity* identity = NewThreadIdentity();
  // Associate the value with the current thread, and attach our destructor.
  base_internal::SetCurrentThreadIdentity(identity, ReclaimThreadIdentity);
  return identity;
}
References absl::base_internal::SetCurrentThreadIdentity().
Referenced by GetOrCreateCurrentThreadIdentity().
GetOrCreateCurrentThreadIdentity()
base_internal::ThreadIdentity * absl::synchronization_internal::GetOrCreateCurrentThreadIdentity () inline
Definition at line 43 of file create_thread_identity.h.
{
  base_internal::ThreadIdentity* identity =
      base_internal::CurrentThreadIdentityIfPresent();
  if (ABSL_PREDICT_FALSE(identity == nullptr)) {
    return CreateThreadIdentity();
  }
  return identity;
}
References ABSL_PREDICT_FALSE, CreateThreadIdentity(), and absl::base_internal::CurrentThreadIdentityIfPresent().
Referenced by AbslInternalPerThreadSemWait(), absl::synchronization_internal::PerThreadSem::GetThreadBlockedCounter(), absl::synchronization_internal::PerThreadSem::SetThreadBlockedCounter(), absl::synchronization_internal::PerThreadSemTest::TestTiming(), and absl::synchronization_internal::PerThreadSemTest::TimingThread().
InvalidGraphId()
GraphId absl::synchronization_internal::InvalidGraphId () inline
Definition at line 58 of file graphcycles.h.
{
  return GraphId{0};
}
Referenced by TEST().
MutexDelay()
int absl::synchronization_internal::MutexDelay (int32_t c, int mode)
Definition at line 186 of file mutex.cc.
{
  const int32_t limit = GetMutexGlobals().mutex_sleep_spins[mode];
  const absl::Duration sleep_time = GetMutexGlobals().mutex_sleep_time;
  if (c < limit) {
    // Spin.
    c++;
  } else {
    SchedulingGuard::ScopedEnable enable_rescheduling;
    ABSL_TSAN_MUTEX_PRE_DIVERT(nullptr, 0);
    if (c == limit) {
      // Yield once.
      ABSL_INTERNAL_C_SYMBOL(AbslInternalMutexYield)();
      c++;
    } else {
      // Then wait.
      absl::SleepFor(sleep_time);
      c = 0;
    }
    ABSL_TSAN_MUTEX_POST_DIVERT(nullptr, 0);
  }
  return c;
}
References ABSL_INTERNAL_C_SYMBOL, ABSL_TSAN_MUTEX_POST_DIVERT, ABSL_TSAN_MUTEX_PRE_DIVERT, AbslInternalMutexYield(), absl::c, MutexDelay(), and absl::SleepFor().
Referenced by MutexDelay().
OneTimeInitThreadIdentity()
void absl::synchronization_internal::OneTimeInitThreadIdentity (base_internal::ThreadIdentity * identity)
Definition at line 72 of file create_thread_identity.cc.
{
  PerThreadSem::Init(identity);
}
TEST()
absl::synchronization_internal::TEST (GraphCycles , RandomizedTest)
Definition at line 191 of file graphcycles_test.cc.
{
  int next_node = 0;
  Nodes nodes;
  Edges edges;   // from, to
  IdMap id;
  GraphCycles graph_cycles;
  static const int kMaxNodes = 7;  // use <= 7 nodes to keep test short
  static const int kDataOffset = 17;  // an offset to the node-specific data
  int n = 100000;
  int op = 0;
  RandomEngine rng(testing::UnitTest::GetInstance()->random_seed());
  std::uniform_int_distribution<int> uniform(0, 5);
  auto ptr = [](intptr_t i) {
    return reinterpret_cast<void*>(i + kDataOffset);
  };
  for (int iter = 0; iter != n; iter++) {
    for (const auto &node : nodes) {
      ASSERT_EQ(graph_cycles.Ptr(Get(id, node)), ptr(node)) << " node " << node;
    }
    CheckEdges(&nodes, &edges, id, &graph_cycles);
    CheckTransitiveClosure(&nodes, &edges, id, &graph_cycles);
    op = uniform(rng);
    switch (op) {
    case 0:     // Add a node
      if (nodes.size() < kMaxNodes) {
        int new_node = next_node++;
        GraphId new_gnode = graph_cycles.GetId(ptr(new_node));
        ASSERT_NE(new_gnode, InvalidGraphId());
        id[new_node] = new_gnode;
        ASSERT_EQ(ptr(new_node), graph_cycles.Ptr(new_gnode));
        nodes.push_back(new_node);
      }
      break;
    case 1:    // Remove a node
      if (nodes.size() > 0) {
        int node_index = RandomNode(&rng, &nodes);
        int node = nodes[node_index];
        nodes[node_index] = nodes.back();
        nodes.pop_back();
        graph_cycles.RemoveNode(ptr(node));
        ASSERT_EQ(graph_cycles.Ptr(Get(id, node)), nullptr);
        id.erase(node);
        int i = 0;
        while (i != edges.size()) {
          if (edges[i].from == node || edges[i].to == node) {
            edges[i] = edges.back();
            edges.pop_back();
          } else {
            i++;
          }
        }
      }
      break;
    case 2:   // Add an edge
      if (nodes.size() > 0) {
        int from = RandomNode(&rng, &nodes);
        int to = RandomNode(&rng, &nodes);
        if (EdgeIndex(&edges, nodes[from], nodes[to]) == -1) {
          if (graph_cycles.InsertEdge(id[nodes[from]], id[nodes[to]])) {
            Edge new_edge;
            new_edge.from = nodes[from];
            new_edge.to = nodes[to];
            edges.push_back(new_edge);
          } else {
            std::unordered_set<int> seen;
            ASSERT_TRUE(IsReachable(&edges, nodes[to], nodes[from], &seen))
                << "Edge " << nodes[to] << "->" << nodes[from];
          }
        }
      }
      break;
    case 3:    // Remove an edge
      if (edges.size() > 0) {
        int i = RandomEdge(&rng, &edges);
        int from = edges[i].from;
        int to = edges[i].to;
        ASSERT_EQ(i, EdgeIndex(&edges, from, to));
        edges[i] = edges.back();
        edges.pop_back();
        ASSERT_EQ(-1, EdgeIndex(&edges, from, to));
        graph_cycles.RemoveEdge(id[from], id[to]);
      }
      break;
    case 4:   // Check a path
      if (nodes.size() > 0) {
        int from = RandomNode(&rng, &nodes);
        int to = RandomNode(&rng, &nodes);
        GraphId path[2*kMaxNodes];
        int path_len = graph_cycles.FindPath(id[nodes[from]], id[nodes[to]],
                                             ABSL_ARRAYSIZE(path), path);
        std::unordered_set<int> seen;
        bool reachable = IsReachable(&edges, nodes[from], nodes[to], &seen);
        bool gc_reachable =
            graph_cycles.IsReachable(Get(id, nodes[from]), Get(id, nodes[to]));
        ASSERT_EQ(path_len != 0, reachable);
        ASSERT_EQ(path_len != 0, gc_reachable);
        // In the following line, we add one because a node can appear
        // twice, if the path is from that node to itself, perhaps via
        // every other node.
        ASSERT_LE(path_len, kMaxNodes + 1);
        if (path_len != 0) {
          ASSERT_EQ(id[nodes[from]], path[0]);
          ASSERT_EQ(id[nodes[to]], path[path_len-1]);
          for (int i = 1; i < path_len; i++) {
            ASSERT_TRUE(graph_cycles.HasEdge(path[i-1], path[i]));
          }
        }
      }
      break;
    case 5:  // Check invariants
      CheckInvariants(graph_cycles);
      break;
    default:
      ABSL_RAW_LOG(FATAL, "op %d", op);
    }
    // Very rarely, test graph expansion by adding then removing many nodes.
    std::bernoulli_distribution one_in_1024(1.0 / 1024);
    if (one_in_1024(rng)) {
      CheckEdges(&nodes, &edges, id, &graph_cycles);
      CheckTransitiveClosure(&nodes, &edges, id, &graph_cycles);
      for (int i = 0; i != 256; i++) {
        int new_node = next_node++;
        GraphId new_gnode = graph_cycles.GetId(ptr(new_node));
        ASSERT_NE(InvalidGraphId(), new_gnode);
        id[new_node] = new_gnode;
        ASSERT_EQ(ptr(new_node), graph_cycles.Ptr(new_gnode));
        for (const auto &node : nodes) {
          ASSERT_NE(node, new_node);
        }
        nodes.push_back(new_node);
      }
      for (int i = 0; i != 256; i++) {
        ASSERT_GT(nodes.size(), 0);
        int node_index = RandomNode(&rng, &nodes);
        int node = nodes[node_index];
        nodes[node_index] = nodes.back();
        nodes.pop_back();
        graph_cycles.RemoveNode(ptr(node));
        id.erase(node);
        int j = 0;
        while (j != edges.size()) {
          if (edges[j].from == node || edges[j].to == node) {
            edges[j] = edges.back();
            edges.pop_back();
          } else {
            j++;
          }
        }
      }
      CheckInvariants(graph_cycles);
    }
  }
}
References ABSL_ARRAYSIZE, ABSL_RAW_LOG, absl::synchronization_internal::GraphCycles::FindPath(), absl::synchronization_internal::Edge::from, from, absl::synchronization_internal::GraphCycles::GetId(), absl::synchronization_internal::GraphCycles::HasEdge(), absl::i, absl::synchronization_internal::GraphCycles::InsertEdge(), InvalidGraphId(), absl::synchronization_internal::GraphCycles::IsReachable(), absl::n, absl::synchronization_internal::GraphCycles::Ptr(), ptr, absl::synchronization_internal::GraphCycles::RemoveEdge(), absl::synchronization_internal::GraphCycles::RemoveNode(), absl::synchronization_internal::Edge::to, and to.
TEST_F() [1/6]
absl::synchronization_internal::TEST_F (GraphCyclesTest , IndirectCycle)
Definition at line 418 of file graphcycles_test.cc.
{
  AddMultiples();
  EXPECT_TRUE(AddEdge(16, 9));
  CheckInvariants(g_);
  EXPECT_FALSE(AddEdge(9, 2));
  EXPECT_EQ("2 4 8 16 9", Path(2, 9));
  CheckInvariants(g_);
}
TEST_F() [2/6]
absl::synchronization_internal::TEST_F (GraphCyclesTest , LongPath)
Definition at line 427 of file graphcycles_test.cc.
{
  ASSERT_TRUE(AddEdge(2, 4));
  ASSERT_TRUE(AddEdge(4, 6));
  ASSERT_TRUE(AddEdge(6, 8));
  ASSERT_TRUE(AddEdge(8, 10));
  ASSERT_TRUE(AddEdge(10, 12));
  ASSERT_FALSE(AddEdge(12, 2));
  EXPECT_EQ("2 4 6 8 10 ...", Path(2, 12));
  CheckInvariants(g_);
}
TEST_F() [3/6]
absl::synchronization_internal::TEST_F (GraphCyclesTest , ManyEdges)
Definition at line 448 of file graphcycles_test.cc.
{
  const int N = 50;
  for (int i = 0; i < N; i++) {
    for (int j = 1; j < N; j++) {
      ASSERT_TRUE(AddEdge(i, i+j));
    }
  }
  CheckInvariants(g_);
  ASSERT_TRUE(AddEdge(2*N-1, 0));
  CheckInvariants(g_);
  ASSERT_FALSE(AddEdge(10, 9));
  CheckInvariants(g_);
}
References absl::i.
TEST_F() [4/6]
absl::synchronization_internal::TEST_F (GraphCyclesTest , NoCycle)
Definition at line 406 of file graphcycles_test.cc.
{
  AddMultiples();
  CheckInvariants(g_);
}
TEST_F() [5/6]
absl::synchronization_internal::TEST_F (GraphCyclesTest , RemoveNode)
Definition at line 438 of file graphcycles_test.cc.
{
  ASSERT_TRUE(AddEdge(1, 2));
  ASSERT_TRUE(AddEdge(2, 3));
  ASSERT_TRUE(AddEdge(3, 4));
  ASSERT_TRUE(AddEdge(4, 5));
  g_.RemoveNode(g_.Ptr(id_[3]));
  id_.erase(3);
  ASSERT_TRUE(AddEdge(5, 1));
}
TEST_F() [6/6]
absl::synchronization_internal::TEST_F (GraphCyclesTest , SimpleCycle)
Definition at line 411 of file graphcycles_test.cc.
{
  AddMultiples();
  EXPECT_FALSE(AddEdge(8, 4));
  EXPECT_EQ("4 8", Path(4, 8));
  CheckInvariants(g_);
}