open spiel: open_spiel.python.mfg.algorithms.mf_psro Namespace Reference
open_spiel.python.mfg.algorithms.mf_psro Namespace Reference
Classes
class MeanFieldPSRO
Functions
dict_equal (dic1, dic2)
equal_policies (pol1, pol2, all_states)
filter_policies (policies, new_policies, all_states)
Detailed Description
Mean-Field PSRO.
As implemented in Muller et al., 2021, https://arxiv.org/abs/2111.08350
Function Documentation
dict_equal()
open_spiel.python.mfg.algorithms.mf_psro.dict_equal (dic1, dic2)
Definition at line 27 of file mf_psro.py.
def dict_equal(dic1, dic2):
  return all([dic1[a] == dic2[a] for a in dic1]) and all(
      [dic1[a] == dic2[a] for a in dic2]
  )
Referenced by open_spiel.python.mfg.algorithms.mf_psro.equal_policies().
equal_policies()
open_spiel.python.mfg.algorithms.mf_psro.equal_policies (pol1, pol2, all_states)
Definition at line 33 of file mf_psro.py.
def equal_policies(pol1, pol2, all_states):
  assert isinstance(pol1, greedy_policy.GreedyPolicy)
  equal = True
  for state_key in all_states:
    state = all_states[state_key]
    try:
      equal = equal and dict_equal(pol1(state), pol2(state))
    except KeyError:
      equal = False
    except ValueError:
      continue
  return equal
References open_spiel.python.mfg.algorithms.mf_psro.dict_equal().
Referenced by open_spiel.python.mfg.algorithms.mf_psro.filter_policies().
filter_policies()
open_spiel.python.mfg.algorithms.mf_psro.filter_policies (policies, new_policies, all_states)
Definition at line 47 of file mf_psro.py.
def filter_policies(policies, new_policies, all_states):
  all_policies = policies
  no_novelty = True
  for new_policy in new_policies:
    if all([
        not equal_policies(new_policy, policy, all_states)
        for policy in all_policies
    ]):
      all_policies.append(new_policy)
      no_novelty = False
  return all_policies, no_novelty
References open_spiel.python.mfg.algorithms.mf_psro.equal_policies().
Referenced by open_spiel.python.mfg.algorithms.mf_psro.MeanFieldPSRO.step().