open spiel: open_spiel::dou_dizhu Namespace Reference
open_spiel::dou_dizhu Namespace Reference
Classes
struct ChainOnlyHandParams
class DouDizhuGame
class DouDizhuState
struct SingleRankHandParams
class Trick
struct TrioCombParams
Enumerations
enum class Phase { kDeal , kAuction , kPlay , kGameOver }
enum KickerType { kSolo = 1 , kPair }
Functions
std::array< std::string, kNumRanks > FormatHand (int player, bool mark_voids, const std::array< std::array< int, kNumRanks >, kNumPlayers > &deal)
int CardToRank (int card)
int CardToSuit (int card)
std::string RankString (int rank)
std::string CardString (int card)
std::string FormatSingleHand (absl::Span< const int > hand)
std::string FormatAirplaneCombHand (int action)
int GetNumCardsPerRank (int action)
int GetSingleRankActionBase (int num_cards_same_rank=1)
SingleRankHandParams GetSingleRankHandParams (int action)
std::array< int, kNumRanks > SingleRankHand (int action)
int SingleRankHandToActionId (absl::Span< const int > hand)
void SearchSingleRankActions (std::vector< Action > *actions, absl::Span< const int > hand, int prev_action=kInvalidAction)
int GetChainOnlyActionBase (int num_cards_same_rank=1)
int GetChainOnlyMinLength (int num_cards_same_rank=1)
ChainOnlyHandParams GetChainOnlyHandParams (int action)
std::array< int, kNumRanks > ChainOnlyHand (int action)
int ChainOnlyHandToActionId (absl::Span< const int > hand)
void SearchChainOnlyActions (std::vector< Action > *actions, absl::Span< const int > hand, int prev_action=kInvalidAction)
int GetTrioCombActionBase (int action)
KickerType GetTrioCombKickerType (int action)
TrioCombParams GetSingleTrioCombParams (int action)
int GetNumKickersAirplaneSoloComb (int chain_length)
int GetAirplaneSoloActionBase (int chain_length)
int GetNumKickersAirplanePairComb (int chain_length)
int GetAirplanePairActionBase (int chain_length)
TrioCombParams GetAirplaneCombParams (int action)
std::array< int, kNumRanks > SingleTrioCombHand (int action)
int SingleTrioCombHandToActionId (absl::Span< const int > hand)
void SearchSingleTrioCombActions (std::vector< Action > *actions, absl::Span< const int > hand, int prev_action=kInvalidAction)
bool dfs_airplane_kicker (int chain_length, int depth, int target_count, int &count, int max_search_rank, absl::Span< int > used_rank, absl::Span< int > ans_hand, KickerType kicker_type)
std::array< int, kNumRanks > AirplaneCombHand (int action)
int AirplaneCombHandToActionId (absl::Span< const int > hand, int chain_head, KickerType kicker_type)
void dfs_add_all_airplane_kickers (int chain_head, int chain_length, int depth, int max_search_rank, absl::Span< int > used_rank, absl::Span< const int > ans_hand, std::vector< Action > *action_ids, KickerType kicker_type)
void SearchAirplaneCombActions (std::vector< Action > *actions, absl::Span< const int > hand, int prev_action=kInvalidAction)
std::array< int, kNumRanks > ActionToHand (int action)
void SearchForLegalActions (std::vector< Action > *legal_actions, absl::Span< const int > hand, int prev_action)
void SingleRankHandTest ()
void ChainOnlyHandTest ()
void SingleTrioCombHandTest ()
void AirplaneCombHandTest ()
Variables
constexpr int kNumPlayers = 3
constexpr int kNumCards = 54
constexpr int kNumBids = 3
constexpr int kNumCardsPerSuit = 13
constexpr int kMaxAuctionLength = 9
constexpr int kMaxUtility = kNumBids * 16384
constexpr int kMinUtility = -kNumBids * 8192
constexpr int kNumRanks = kNumCardsPerSuit + 2
constexpr int kNumCardsLeftOver = 3
constexpr int kNumSuits = 4
constexpr int kObservationTensorSize
constexpr int kDealingActionBase = kNumCards - kNumCardsLeftOver
constexpr int kBiddingActionBase = 0
constexpr int kPass = kBiddingActionBase
constexpr int kPlayActionBase = kBiddingActionBase + 1 + kNumBids
constexpr int kSoloChainMinLength = 5
constexpr int kSoloChainActionBase = kPlayActionBase + 15
constexpr int kPairActionBase = kSoloChainActionBase + 36
constexpr int kPairChainMinLength = 3
constexpr int kPairChainActionBase = kPairActionBase + 13
constexpr int kTrioActionBase = kPairChainActionBase + 52
constexpr int kTrioWithSoloActionBase = kTrioActionBase + 13
constexpr int kTrioWithPairActionBase = kTrioWithSoloActionBase + 182
constexpr int kAirplaneMinLength = 2
constexpr int kAirplaneActionBase = kTrioWithPairActionBase + 156
constexpr int kAirplaneWithSoloMinLength = 2
constexpr int kAirplaneWithSoloActionBase = kAirplaneActionBase + 45
constexpr int kAirplaneWithPairMinLength = 2
constexpr int kAirplaneWithPairActionBase
constexpr int kBombActionBase = kAirplaneWithPairActionBase + 2939
constexpr int kRocketActionBase = kBombActionBase + 13
constexpr int kNumKickersAirplaneSoloCombChainOfLengthTwo = 88
constexpr int kNumKickersAirplaneSoloCombChainOfLengthThree = 330
constexpr int kNumKickersAirplaneSoloCombChainOfLengthFour = 816
constexpr int kNumKickersAirplaneSoloCombChainOfLengthFive = 1372
constexpr int kNumKickersAirplanePairCombChainOfLengthTwo = 55
constexpr int kNumKickersAirplanePairCombChainOfLengthThree = 120
constexpr int kNumKickersAirplanePairCombChainOfLengthFour = 126
constexpr char kRankChar [] = "3456789TJQKA2"
constexpr char kSuitChar [] = "CDHS"
Enumeration Type Documentation
KickerType
enum open_spiel::dou_dizhu::KickerType
Enumerator
kSolo
kPair
Definition at line 104 of file dou_dizhu_utils.h.
{ kSolo = 1, kPair };
Phase
enum class open_spiel::dou_dizhu::Phase strong
Enumerator
kDeal
kAuction
kPlay
kGameOver
Definition at line 24 of file dou_dizhu_utils.h.
{ kDeal, kAuction, kPlay, kGameOver };
Function Documentation
ActionToHand()
std::array< int, kNumRanks > open_spiel::dou_dizhu::ActionToHand (int action)
Definition at line 848 of file dou_dizhu_utils.cc.
{
  std::array<int, kNumRanks> hand{};
  if ((action >= kPlayActionBase && action < kSoloChainActionBase) ||
      (action >= kPairActionBase && action < kPairChainActionBase) ||
      (action >= kTrioActionBase && action < kTrioWithSoloActionBase) ||
      (action >= kBombActionBase && action < kRocketActionBase)) {
    hand = SingleRankHand(action);
  } else if ((action >= kSoloChainActionBase && action < kPairActionBase) ||
             (action >= kPairChainActionBase && action < kTrioActionBase) ||
             (action >= kAirplaneActionBase &&
              action < kAirplaneWithSoloActionBase)) {
    hand = ChainOnlyHand(action);
  } else if (action >= kTrioWithSoloActionBase &&
             action < kAirplaneActionBase) {
    hand = SingleTrioCombHand(action);
  } else if (action >= kAirplaneWithSoloActionBase &&
             action < kBombActionBase) {
    hand = AirplaneCombHand(action);
  } else if (action == kRocketActionBase) {
    hand[kNumRanks - 1] = hand[kNumRanks - 2] = 1;
  } else {
    SpielFatalError("Non valid Action Ids");
  }
  return hand;
}
References action, AirplaneCombHand(), ChainOnlyHand(), kAirplaneActionBase, kAirplaneWithSoloActionBase, kBombActionBase, kNumRanks, kPairActionBase, kPairChainActionBase, kPlayActionBase, kRocketActionBase, kSoloChainActionBase, kTrioActionBase, kTrioWithSoloActionBase, SingleRankHand(), SingleTrioCombHand(), and open_spiel::SpielFatalError().
Referenced by open_spiel::dou_dizhu::DouDizhuState::ActionToString(), and FormatAirplaneCombHand().
AirplaneCombHand()
std::array< int, kNumRanks > open_spiel::dou_dizhu::AirplaneCombHand (int action)
Definition at line 682 of file dou_dizhu_utils.cc.
{
  std::array<int, kNumRanks> hand{};
  std::array<int, kNumRanks> used_rank{};
  SPIEL_CHECK_GE(action, kAirplaneWithSoloActionBase);
  SPIEL_CHECK_LT(action, kBombActionBase);
  TrioCombParams params = GetAirplaneCombParams(action);
  for (int i = 0; i < params.chain_length; ++i) {
    hand[params.chain_head + i] = used_rank[params.chain_head + i] = 3;
  }
  const int kicker_steps = params.kicker_id;
  int count = 0;
  bool found = dfs_airplane_kicker(params.chain_length, 0, kicker_steps, count,
                                   kNumRanks - 1, absl::MakeSpan(used_rank),
                                   absl::MakeSpan(hand), params.kicker_type);
  SPIEL_CHECK_TRUE(found);
  return hand;
}
References action, open_spiel::dou_dizhu::TrioCombParams::chain_head, open_spiel::dou_dizhu::TrioCombParams::chain_length, dfs_airplane_kicker(), GetAirplaneCombParams(), i, kAirplaneWithSoloActionBase, kBombActionBase, open_spiel::dou_dizhu::TrioCombParams::kicker_id, open_spiel::dou_dizhu::TrioCombParams::kicker_type, kNumRanks, absl::MakeSpan(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, and SPIEL_CHECK_TRUE.
Referenced by ActionToHand(), and AirplaneCombHandTest().
AirplaneCombHandTest()
void open_spiel::dou_dizhu::AirplaneCombHandTest ()
Definition at line 126 of file dou_dizhu_utils_test.cc.
{
  // 888999TTTJJJQQQ-7772(CJ)
  std::array<int, kNumRanks> hand1 = {0, 0, 0, 0, 3, 3, 3, 3,
                                      3, 3, 0, 0, 1, 0, 1};
  int action_id1 = AirplaneCombHandToActionId(hand1, /*chain_head=*/5,
                                              /*kicker_type=*/kSolo);
  SPIEL_CHECK_EQ(FormatSingleHand(AirplaneCombHand(action_id1)),
                 "777888999TTTJJJQQQ2(CJ)");
  // TTTJJJQQQKKK-33445522
  std::array<int, kNumRanks> hand2 = {2, 2, 2, 0, 0, 0, 0, 3,
                                      3, 3, 3, 0, 2, 0, 0};
  int action_id2 = AirplaneCombHandToActionId(hand2, /*chain_head=*/7,
                                              /*kicker_type=*/kPair);
  SPIEL_CHECK_EQ(FormatSingleHand(AirplaneCombHand(action_id2)),
                 "334455TTTJJJQQQKKK22");
  // 667899TTTJJJJQQQKKKAAA222(BWJ)(CJ)
  std::array<int, kNumRanks> current_hand = {0, 0, 0, 2, 1, 1, 2, 3,
                                             4, 3, 3, 3, 3, 1, 1};
  std::vector<Action> actions1, actions2, actions3;
  SearchAirplaneCombActions(&actions1, current_hand,
                            /*prev_action=*/action_id1);
  // C(7, 5) - C(5, 3) + 3*(C(6, 3) - C(4, 1)) + C(3, 2) * 5 + 2 + C(6, 2) - 1 =
  // 90
  SPIEL_CHECK_EQ(static_cast<int>(actions1.size()), 90);
  // The only hand that is greater than TTTJJJQQQKKK-33445522 is
  // JJJQQQKKKAAA-6699TT22
  SearchAirplaneCombActions(&actions2, current_hand,
                            /*prev_action=*/action_id2);
  SPIEL_CHECK_EQ(static_cast<int>(actions2.size()), 1);
  SearchAirplaneCombActions(&actions3, current_hand,
                            /*prev_action=*/kInvalidAction);
  SPIEL_CHECK_EQ(static_cast<int>(actions3.size()), 1052);
}
References AirplaneCombHand(), AirplaneCombHandToActionId(), FormatSingleHand(), open_spiel::kInvalidAction, kPair, kSolo, SearchAirplaneCombActions(), and SPIEL_CHECK_EQ.
Referenced by main().
AirplaneCombHandToActionId()
int open_spiel::dou_dizhu::AirplaneCombHandToActionId (absl::Span< const int > hand, int chain_head, KickerType kicker_type)
Definition at line 702 of file dou_dizhu_utils.cc.
{
  int chain_length = 0;
  bool chain_begun = false;
  std::vector<int> kickers;
  for (int rank = 0; rank < kNumRanks; ++rank) {
    SPIEL_CHECK_LT(hand[rank], kNumSuits);
    if (!hand[rank]) continue;
    if (!chain_begun && rank != chain_head) {
      if (kicker_type == kSolo) {
        for (int i = 0; i < hand[rank]; ++i) {
          kickers.push_back(rank);
        }
      } else {
        SPIEL_CHECK_EQ(hand[rank], 2);
        kickers.push_back(rank);
      }
    } else if (rank == chain_head) {
      SPIEL_CHECK_EQ(hand[rank], 3);
      chain_begun = true;
      chain_length++;
    } else if (chain_begun && hand[rank] == 3) {
      chain_length++;
    } else if (chain_begun && hand[rank] != 3) {
      chain_begun = false;
      if (kicker_type == kSolo) {
        for (int i = 0; i < hand[rank]; ++i) kickers.push_back(rank);
      } else {
        SPIEL_CHECK_EQ(hand[rank], 2);
        kickers.push_back(rank);
      }
    }
  }
  // handle case where 333444555666 and chain_head=3
  // in this case, the above linear scan algorithm will view 3-4-5-6 as the
  // chain where 6s should be the kickers
  if (chain_length - 1 == static_cast<int>(kickers.size()) + 3) {
    chain_length--;
    for (int i = 0; i < 3; ++i) kickers.push_back(chain_head + chain_length);
  }
  SPIEL_CHECK_EQ(chain_length, static_cast<int>(kickers.size()));
  if (chain_head + chain_length - 1 >= kNumRanks - 3)
    SpielFatalError("2s, Joker cannot be in a chain");
  int action_base;
  if (kicker_type == kSolo)
    action_base = GetAirplaneSoloActionBase(chain_length) +
                  chain_head * GetNumKickersAirplaneSoloComb(chain_length);
  else
    action_base = GetAirplanePairActionBase(chain_length) +
                  chain_head * GetNumKickersAirplanePairComb(chain_length);
  int count = 0;
  std::array<int, kNumRanks> used_rank{};
  for (int i = 0; i < chain_length; ++i) used_rank[chain_head + i] = 3;
  std::array<int, kNumRanks> hand_copy{};
  for (int i = 0; i < kNumRanks; ++i) hand_copy[i] = hand[i];
  bool found = dfs_airplane_kicker(chain_length, 0, -1, count, kNumRanks - 1,
                                   absl::MakeSpan(used_rank),
                                   absl::MakeSpan(hand_copy), kicker_type);
  SPIEL_CHECK_TRUE(found);
  return action_base + count;
}
References dfs_airplane_kicker(), GetAirplanePairActionBase(), GetAirplaneSoloActionBase(), GetNumKickersAirplanePairComb(), GetNumKickersAirplaneSoloComb(), i, kNumRanks, kNumSuits, kSolo, absl::MakeSpan(), rank, SPIEL_CHECK_EQ, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, and open_spiel::SpielFatalError().
Referenced by AirplaneCombHandTest(), and dfs_add_all_airplane_kickers().
CardString()
std::string open_spiel::dou_dizhu::CardString (int card)
Definition at line 48 of file dou_dizhu_utils.cc.
{
  int rank = CardToRank(card);
  if (rank >= kNumRanks - 2) {
    return RankString(rank);
  } else {
    int suit = CardToSuit(card);
    SPIEL_CHECK_GE(suit, 0);
    SPIEL_CHECK_LT(suit, kNumSuits);
    return absl::StrFormat("%c%c", kSuitChar[suit], kRankChar[rank]);
  }
}
References CardToRank(), CardToSuit(), kNumRanks, kNumSuits, kRankChar, kSuitChar, rank, RankString(), SPIEL_CHECK_GE, SPIEL_CHECK_LT, and absl::StrFormat().
Referenced by open_spiel::dou_dizhu::DouDizhuState::ActionToString().
CardToRank()
int open_spiel::dou_dizhu::CardToRank (int card)
Definition at line 23 of file dou_dizhu_utils.cc.
{
  if (card == kNumCards - 2 || card == kNumCards - 1) {
    return card - kNumCards + kNumRanks;
  }
  return card % (kNumRanks - 2);
}
References kNumCards, and kNumRanks.
Referenced by CardString().
CardToSuit()
int open_spiel::dou_dizhu::CardToSuit (int card)
Definition at line 30 of file dou_dizhu_utils.cc.
{
  if (card == kNumCards - 2 || card == kNumCards - 1) {
    SpielFatalError("No Suit defined for Jokers");
  }
  return card / (kNumRanks - 2);
}
References kNumCards, kNumRanks, and open_spiel::SpielFatalError().
Referenced by CardString().
ChainOnlyHand()
std::array< int, kNumRanks > open_spiel::dou_dizhu::ChainOnlyHand (int action)
Definition at line 254 of file dou_dizhu_utils.cc.
{
  std::array<int, kNumRanks> hand{};
  ChainOnlyHandParams params = GetChainOnlyHandParams(action);
  for (int i = 0; i < params.chain_length; ++i) {
    hand[params.chain_head + i] = params.num_cards_per_rank;
  }
  return hand;
}
References action, open_spiel::dou_dizhu::ChainOnlyHandParams::chain_head, open_spiel::dou_dizhu::ChainOnlyHandParams::chain_length, GetChainOnlyHandParams(), i, and open_spiel::dou_dizhu::ChainOnlyHandParams::num_cards_per_rank.
Referenced by ActionToHand(), and ChainOnlyHandTest().
ChainOnlyHandTest()
void open_spiel::dou_dizhu::ChainOnlyHandTest ()
Definition at line 57 of file dou_dizhu_utils_test.cc.
{
  std::array<int, kNumRanks> hand1 = {0, 0, 0, 3, 3, 3};
  int action_id1 = ChainOnlyHandToActionId(hand1);
  SPIEL_CHECK_EQ(FormatSingleHand(ChainOnlyHand(action_id1)), "666777888");
  std::array<int, kNumRanks> hand2 = {2, 2, 2, 2, 2, 2, 2, 2, 2};
  int action_id2 = ChainOnlyHandToActionId(hand2);
  SPIEL_CHECK_EQ(FormatSingleHand(ChainOnlyHand(action_id2)),
                 "33445566778899TTJJ");
  // 5566777888999TTTJJQQKKAA22(BWJ)(CJ)
  std::array<int, kNumRanks> current_hand = {0, 0, 2, 2, 3, 3, 3, 3,
                                             2, 2, 2, 2, 2, 1, 1};
  std::vector<Action> actions1, actions2, actions3;
  SearchChainOnlyActions(&actions1, current_hand, /*prev_action=*/action_id1);
  // The only hands greater than 666777888 are 777888999 and 888999TTT
  SPIEL_CHECK_EQ(static_cast<int>(actions1.size()), 2);
  SearchChainOnlyActions(&actions2, current_hand, /*prev_action=*/action_id2);
  // The only hands greater than 334455....TTJJ are 5566....QQKK and
  // 6677.....KKAA
  SPIEL_CHECK_EQ(static_cast<int>(actions2.size()), 2);
  SearchChainOnlyActions(&actions3, current_hand,
                         /*prev_action=*/kInvalidAction);
  SPIEL_CHECK_EQ(static_cast<int>(actions3.size()), 63);
}
References ChainOnlyHand(), ChainOnlyHandToActionId(), FormatSingleHand(), open_spiel::kInvalidAction, SearchChainOnlyActions(), and SPIEL_CHECK_EQ.
Referenced by main().
ChainOnlyHandToActionId()
int open_spiel::dou_dizhu::ChainOnlyHandToActionId (absl::Span< const int > hand)
Definition at line 263 of file dou_dizhu_utils.cc.
{
  int chain_head = -1;
  int chain_length = 0;
  int chain_counter = 0;
  int num_cards_same_rank = 0;
  bool chain_stopped = true;
  if (hand[kNumRanks - 3] || hand[kNumRanks - 2] || hand[kNumRanks - 1])
    SpielFatalError("2s and Jokers cannot be in a chain");
  for (int rank = 0; rank < kNumRanks - 3; ++rank) {
    if (hand[rank] == 0) {
      chain_stopped = true;
    } else {
      if (chain_stopped) {
        chain_head = rank;
        num_cards_same_rank = hand[rank];
        chain_length = 1;
        chain_counter++;
        chain_stopped = false;
      } else if (hand[rank] != num_cards_same_rank) {
        SpielFatalError("Invalid pattern");
      } else {
        chain_length++;
      }
    }
  }
  SPIEL_CHECK_EQ(chain_counter, 1);
  const int min_length = GetChainOnlyMinLength(num_cards_same_rank);
  const int action_base = GetChainOnlyActionBase(num_cards_same_rank);
  if (chain_length < min_length)
    SpielFatalError(absl::StrFormat("The length of chain should be at least %d",
                                    min_length));
  int action = action_base;
  for (int length = min_length; length < chain_length; ++length)
    action += kNumRanks - length - 2;
  action += chain_head;
  return action;
}
References action, GetChainOnlyActionBase(), GetChainOnlyMinLength(), kNumRanks, rank, SPIEL_CHECK_EQ, open_spiel::SpielFatalError(), and absl::StrFormat().
Referenced by ChainOnlyHandTest(), and SearchChainOnlyActions().
dfs_add_all_airplane_kickers()
void open_spiel::dou_dizhu::dfs_add_all_airplane_kickers (int chain_head, int chain_length, int depth, int max_search_rank, absl::Span< int > used_rank, absl::Span< const int > ans_hand, std::vector< Action > * action_ids, KickerType kicker_type)
Definition at line 771 of file dou_dizhu_utils.cc.
{
  if (chain_length == depth) {
    std::array<int, kNumRanks> final_hand{};
    for (int i = 0; i < kNumRanks; ++i) final_hand[i] = used_rank[i];
    action_ids->push_back(static_cast<Action>(
        AirplaneCombHandToActionId(final_hand, chain_head, kicker_type)));
  } else {
    for (int rank = 0; rank <= max_search_rank; ++rank) {
      if (rank >= chain_head && rank <= chain_head + chain_length - 1) continue;
      SPIEL_CHECK_NE(used_rank[rank], kNumSuits);
      if (used_rank[rank] == 3) continue;
      if (kicker_type == kPair) {
        SPIEL_CHECK_NE(used_rank[rank], 1);
        if (used_rank[rank] == 2) continue;
      }
      if (rank == kNumRanks - 1 || rank == kNumRanks - 2) {
        if (kicker_type == kPair) continue;
        if (used_rank[rank]) continue;
        if (used_rank[2 * kNumRanks - 3 - rank]) continue;
      }
      int num_use_cards = kicker_type == kSolo ? 1 : 2;
      if (ans_hand[rank] < num_use_cards + used_rank[rank]) continue;
      used_rank[rank] += num_use_cards;
      dfs_add_all_airplane_kickers(chain_head, chain_length, depth + 1, rank,
                                   used_rank, ans_hand, action_ids,
                                   kicker_type);
      used_rank[rank] -= num_use_cards;
    }
  }
}
References AirplaneCombHandToActionId(), dfs_add_all_airplane_kickers(), i, kNumRanks, kNumSuits, kPair, kSolo, rank, and SPIEL_CHECK_NE.
Referenced by dfs_add_all_airplane_kickers(), and SearchAirplaneCombActions().
dfs_airplane_kicker()
bool open_spiel::dou_dizhu::dfs_airplane_kicker (int chain_length, int depth, int target_count, int & count, int max_search_rank, absl::Span< int > used_rank, absl::Span< int > ans_hand, KickerType kicker_type)
Definition at line 642 of file dou_dizhu_utils.cc.
{
  if (chain_length == depth) {
    if (target_count == -1) {
      bool found = true;
      for (int rank = 0; rank < kNumRanks; ++rank)
        found = found & (used_rank[rank] == ans_hand[rank]);
      if (found) return true;
    } else if (target_count == count) {
      for (int rank = 0; rank < kNumRanks; ++rank)
        ans_hand[rank] = used_rank[rank];
      return true;
    }
    count++;
  } else {
    for (int rank = 0; rank <= max_search_rank; ++rank) {
      SPIEL_CHECK_NE(used_rank[rank], kNumSuits);
      if (used_rank[rank] == 3) continue;
      if (kicker_type == kPair) {
        SPIEL_CHECK_NE(used_rank[rank], 1);
        if (used_rank[rank] == 2) continue;
      }
      if (rank == kNumRanks - 1 || rank == kNumRanks - 2) {
        if (kicker_type == kPair) continue;
        if (used_rank[rank]) continue;
        // Rocket cannot be kickers
        if (used_rank[2 * kNumRanks - 3 - rank]) continue;
      }
      used_rank[rank] += kicker_type == kSolo ? 1 : 2;
      if (dfs_airplane_kicker(chain_length, depth + 1, target_count, count,
                              rank, used_rank, ans_hand, kicker_type))
        return true;
      used_rank[rank] -= kicker_type == kSolo ? 1 : 2;
    }
  }
  return false;
}
References dfs_airplane_kicker(), kNumRanks, kNumSuits, kPair, kSolo, rank, and SPIEL_CHECK_NE.
Referenced by AirplaneCombHand(), AirplaneCombHandToActionId(), and dfs_airplane_kicker().
FormatAirplaneCombHand()
std::string open_spiel::dou_dizhu::FormatAirplaneCombHand (int action)
Definition at line 70 of file dou_dizhu_utils.cc.
{
  TrioCombParams params = GetAirplaneCombParams(action);
  std::array<int, kNumRanks> hand = ActionToHand(action);
  std::string airplane_comb_str;
  // specify which is chain
  for (int rank = params.chain_head;
       rank < params.chain_head + params.chain_length; ++rank) {
    for (int i = 0; i < 3; ++i)
      absl::StrAppend(&airplane_comb_str, RankString(rank));
  }
  absl::StrAppend(&airplane_comb_str, "-");
  // kickers
  for (int rank = 0; rank < kNumRanks; ++rank) {
    if (rank >= params.chain_head &&
        rank < params.chain_head + params.chain_length)
      continue;
    if (!hand[rank]) continue;
    for (int i = 0; i < hand[rank]; ++i)
      absl::StrAppend(&airplane_comb_str, RankString(rank));
  }
  return airplane_comb_str;
}
References action, ActionToHand(), open_spiel::dou_dizhu::TrioCombParams::chain_head, open_spiel::dou_dizhu::TrioCombParams::chain_length, GetAirplaneCombParams(), i, kNumRanks, rank, RankString(), and absl::StrAppend().
Referenced by open_spiel::dou_dizhu::DouDizhuState::ActionToString().
FormatHand()
std::array< std::string, kNumRanks > open_spiel::dou_dizhu::FormatHand (int player, bool mark_voids, const std::array< std::array< int, kNumRanks >, kNumPlayers > & deal)
Definition at line 130 of file dou_dizhu.cc.
{
  std::array<std::string, kNumRanks> cards{};
  for (int rank = 0; rank < kNumRanks - 2; ++rank) {
    bool is_void = true;
    for (int i = 0; i < deal[player][rank]; ++i) {
      cards[rank].push_back(kRankChar[rank]);
      is_void = false;
    }
    if (is_void && mark_voids) absl::StrAppend(&cards[rank], "none");
  }
  if (deal[player][kNumRanks - 2])
    absl::StrAppend(&cards[kNumRanks - 2], "(BWJ)");
  else if (mark_voids)
    absl::StrAppend(&cards[kNumRanks - 2], "none");
  if (deal[player][kNumRanks - 1])
    absl::StrAppend(&cards[kNumRanks - 1], "(CJ)");
  else if (mark_voids)
    absl::StrAppend(&cards[kNumRanks - 1], "none");
  return cards;
}
References i, kNumRanks, kRankChar, player, rank, and absl::StrAppend().
FormatSingleHand()
std::string open_spiel::dou_dizhu::FormatSingleHand (absl::Span< const int > hand)
Definition at line 60 of file dou_dizhu_utils.cc.
{
  std::string hand_format;
  for (int rank = 0; rank < kNumRanks; ++rank) {
    for (int i = 0; i < hand[rank]; ++i)
      absl::StrAppend(&hand_format, RankString(rank));
  }
  return hand_format;
}
References i, kNumRanks, rank, RankString(), and absl::StrAppend().
Referenced by open_spiel::dou_dizhu::DouDizhuState::ActionToString(), AirplaneCombHandTest(), ChainOnlyHandTest(), open_spiel::dou_dizhu::DouDizhuState::ObservationString(), SingleRankHandTest(), and SingleTrioCombHandTest().
GetAirplaneCombParams()
TrioCombParams open_spiel::dou_dizhu::GetAirplaneCombParams (int action)
Definition at line 500 of file dou_dizhu_utils.cc.
{
  if (action < kAirplaneWithSoloActionBase || action >= kBombActionBase)
    SpielFatalError("Must be airplane pattern");
  int action_base = kInvalidAction;
  KickerType kicker_type;
  SPIEL_CHECK_GE(action, kAirplaneWithSoloActionBase);
  SPIEL_CHECK_LT(action, kBombActionBase);
  int start_length = 2, end_length, end_base;
  int (*GetActionBaseFunc)(int), (*GetKickersNumFunc)(int);
  if (kAirplaneWithSoloActionBase <= action &&
      action < kAirplaneWithPairActionBase) {
    kicker_type = kSolo;
    GetActionBaseFunc = &GetAirplaneSoloActionBase;
    GetKickersNumFunc = &GetNumKickersAirplaneSoloComb;
    end_length = 5;
    end_base = kAirplaneWithPairActionBase;
  } else {
    kicker_type = kPair;
    GetActionBaseFunc = &GetAirplanePairActionBase;
    GetKickersNumFunc = &GetNumKickersAirplanePairComb;
    end_length = 4;
    end_base = kBombActionBase;
  }
  int chain_length;
  // label the action Ids in increasing length of chain
  for (chain_length = start_length; chain_length <= end_length;
       ++chain_length) {
    int start_base = GetActionBaseFunc(chain_length);
    int next_base = chain_length == end_length
                        ? end_base
                        : GetActionBaseFunc(chain_length + 1);
    if (start_base <= action && action < next_base) {
      action_base = start_base;
      break;
    }
  }
  const int hand_id = (action - action_base);
  const int num_kickers = GetKickersNumFunc(chain_length);
  const int chain_head = hand_id / num_kickers;
  const int kicker_steps = hand_id % num_kickers;
  SPIEL_CHECK_FALSE(action_base == kInvalidAction);
  return TrioCombParams(chain_head, chain_length, kicker_type, kicker_steps);
}
References action, GetAirplanePairActionBase(), GetAirplaneSoloActionBase(), GetNumKickersAirplanePairComb(), GetNumKickersAirplaneSoloComb(), kAirplaneWithPairActionBase, kAirplaneWithSoloActionBase, kBombActionBase, open_spiel::kInvalidAction, kPair, kSolo, SPIEL_CHECK_FALSE, SPIEL_CHECK_GE, SPIEL_CHECK_LT, and open_spiel::SpielFatalError().
Referenced by AirplaneCombHand(), FormatAirplaneCombHand(), and SearchAirplaneCombActions().
GetAirplanePairActionBase()
int open_spiel::dou_dizhu::GetAirplanePairActionBase (int chain_length)
Definition at line 479 of file dou_dizhu_utils.cc.
{
  int action_base;
  switch (chain_length) {
    case 2:
      action_base = kAirplaneWithPairActionBase;
      break;
    case 3:
      action_base = kAirplaneWithPairActionBase + 605;
      break;
    case 4:
      action_base = kAirplaneWithPairActionBase + 1805;
      break;
    default:
      SpielFatalError("The chain length for aiplane+Pair must be within 2-4");
      break;
  }
  return action_base;
}
References kAirplaneWithPairActionBase, and open_spiel::SpielFatalError().
Referenced by AirplaneCombHandToActionId(), and GetAirplaneCombParams().
GetAirplaneSoloActionBase()
int open_spiel::dou_dizhu::GetAirplaneSoloActionBase (int chain_length)
Definition at line 431 of file dou_dizhu_utils.cc.
{
  int action_base;
  switch (chain_length) {
    case 2:
      action_base = kAirplaneWithSoloActionBase;
      break;
    case 3:
      action_base = kAirplaneWithSoloActionBase + 968;
      break;
    case 4:
      action_base = kAirplaneWithSoloActionBase + 4268;
      break;
    case 5:
      action_base = kAirplaneWithSoloActionBase + 11612;
      break;
    default:
      SpielFatalError("The chain length for aiplane+solo must be within 2-5");
      break;
  }
  return action_base;
}
References kAirplaneWithSoloActionBase, and open_spiel::SpielFatalError().
Referenced by AirplaneCombHandToActionId(), and GetAirplaneCombParams().
GetChainOnlyActionBase()
int open_spiel::dou_dizhu::GetChainOnlyActionBase (int num_cards_same_rank = 1)
Definition at line 200 of file dou_dizhu_utils.cc.
{
  int action_base;
  switch (num_cards_same_rank) {
    case 1:
      action_base = kSoloChainActionBase;
      break;
    case 2:
      action_base = kPairChainActionBase;
      break;
    case 3:
      action_base = kAirplaneActionBase;
      break;
    default:
      SpielFatalError("The number of cards of the same rank is wrong (chain).");
  }
  return action_base;
}
References kAirplaneActionBase, kPairChainActionBase, kSoloChainActionBase, and open_spiel::SpielFatalError().
Referenced by ChainOnlyHandToActionId(), and GetChainOnlyHandParams().
GetChainOnlyHandParams()
ChainOnlyHandParams open_spiel::dou_dizhu::GetChainOnlyHandParams (int action)
Definition at line 236 of file dou_dizhu_utils.cc.
{
  const int num_cards_same_rank = GetNumCardsPerRank(action);
  const int action_base = GetChainOnlyActionBase(num_cards_same_rank);
  const int min_length = GetChainOnlyMinLength(num_cards_same_rank);
  SPIEL_CHECK_GE(action, action_base);
  const int hand_id = action - action_base;
  int chain_length = min_length;
  int base = 0;
  // we label the action Ids by increasing length of the chain
  for (chain_length = min_length; chain_length <= kNumRanks; ++chain_length) {
    int num_chains = kNumRanks - chain_length - 2;
    if (base <= hand_id && hand_id < base + num_chains) break;
    base += num_chains;
  }
  const int chain_head = hand_id - base;
  return ChainOnlyHandParams(chain_head, num_cards_same_rank, chain_length);
}
References action, GetChainOnlyActionBase(), GetChainOnlyMinLength(), GetNumCardsPerRank(), kNumRanks, and SPIEL_CHECK_GE.
Referenced by ChainOnlyHand(), and SearchChainOnlyActions().
GetChainOnlyMinLength()
int open_spiel::dou_dizhu::GetChainOnlyMinLength (int num_cards_same_rank = 1)
Definition at line 218 of file dou_dizhu_utils.cc.
{
  int chain_length;
  switch (num_cards_same_rank) {
    case 1:
      chain_length = kSoloChainMinLength;
      break;
    case 2:
      chain_length = kPairChainMinLength;
      break;
    case 3:
      chain_length = kAirplaneMinLength;
      break;
    default:
      SpielFatalError("The number of cards of the same rank is wrong (chain).");
  }
  return chain_length;
}
References kAirplaneMinLength, kPairChainMinLength, kSoloChainMinLength, and open_spiel::SpielFatalError().
Referenced by ChainOnlyHandToActionId(), GetChainOnlyHandParams(), and SearchChainOnlyActions().
GetNumCardsPerRank()
int open_spiel::dou_dizhu::GetNumCardsPerRank (int action)
Definition at line 94 of file dou_dizhu_utils.cc.
{
  int num_cards;
  if (action >= kPlayActionBase && action < kPairActionBase) {
    num_cards = 1;
  } else if (action >= kPairActionBase && action < kTrioActionBase) {
    num_cards = 2;
  } else if ((action >= kTrioActionBase && action < kTrioWithSoloActionBase) ||
             (action >= kAirplaneActionBase &&
              action < kAirplaneWithSoloActionBase)) {
    num_cards = 3;
  } else if (action >= kBombActionBase && action < kRocketActionBase) {
    num_cards = 4;
  } else {
    SpielFatalError("Invalid action ID");
  }
  return num_cards;
}
References action, kAirplaneActionBase, kAirplaneWithSoloActionBase, kBombActionBase, kPairActionBase, kPlayActionBase, kRocketActionBase, kTrioActionBase, kTrioWithSoloActionBase, and open_spiel::SpielFatalError().
Referenced by GetChainOnlyHandParams(), and GetSingleRankHandParams().
GetNumKickersAirplanePairComb()
int open_spiel::dou_dizhu::GetNumKickersAirplanePairComb (int chain_length)
Definition at line 457 of file dou_dizhu_utils.cc.
{
  int num_comb;
  switch (chain_length) {
    case 2:
      num_comb = kNumKickersAirplanePairCombChainOfLengthTwo;
      break;
    case 3:
      num_comb = kNumKickersAirplanePairCombChainOfLengthThree;
      break;
    case 4:
      num_comb = kNumKickersAirplanePairCombChainOfLengthFour;
      break;
    default:
      SpielFatalError("The chain length for aiplane+Pair must be within 2-4");
      break;
  }
  return num_comb;
}
References kNumKickersAirplanePairCombChainOfLengthFour, kNumKickersAirplanePairCombChainOfLengthThree, kNumKickersAirplanePairCombChainOfLengthTwo, and open_spiel::SpielFatalError().
Referenced by AirplaneCombHandToActionId(), and GetAirplaneCombParams().
GetNumKickersAirplaneSoloComb()
int open_spiel::dou_dizhu::GetNumKickersAirplaneSoloComb (int chain_length)
Definition at line 405 of file dou_dizhu_utils.cc.
{
  int num_comb;
  switch (chain_length) {
    case 2:
      num_comb = kNumKickersAirplaneSoloCombChainOfLengthTwo;
      break;
    case 3:
      num_comb = kNumKickersAirplaneSoloCombChainOfLengthThree;
      break;
    case 4:
      num_comb = kNumKickersAirplaneSoloCombChainOfLengthFour;
      break;
    case 5:
      num_comb = kNumKickersAirplaneSoloCombChainOfLengthFive;
      break;
    default:
      SpielFatalError("The chain length for aiplane+solo must be within 2-5");
      break;
  }
  return num_comb;
}
References kNumKickersAirplaneSoloCombChainOfLengthFive, kNumKickersAirplaneSoloCombChainOfLengthFour, kNumKickersAirplaneSoloCombChainOfLengthThree, kNumKickersAirplaneSoloCombChainOfLengthTwo, and open_spiel::SpielFatalError().
Referenced by AirplaneCombHandToActionId(), and GetAirplaneCombParams().
GetSingleRankActionBase()
int open_spiel::dou_dizhu::GetSingleRankActionBase (int num_cards_same_rank = 1)
Definition at line 113 of file dou_dizhu_utils.cc.
{
  int action_base;
  switch (num_cards_same_rank) {
    case 1:
      action_base = kPlayActionBase;
      break;
    case 2:
      action_base = kPairActionBase;
      break;
    case 3:
      action_base = kTrioActionBase;
      break;
    case 4:
      action_base = kBombActionBase;
      break;
    default:
      SpielFatalError(
          "The number of cards of the same rank is wrong (single rank).");
  }
  return action_base;
}
References kBombActionBase, kPairActionBase, kPlayActionBase, kTrioActionBase, and open_spiel::SpielFatalError().
Referenced by GetSingleRankHandParams(), and SingleRankHandToActionId().
GetSingleRankHandParams()
SingleRankHandParams open_spiel::dou_dizhu::GetSingleRankHandParams (int action)
Definition at line 135 of file dou_dizhu_utils.cc.
{
  const int num_cards = GetNumCardsPerRank(action);
  const int action_base = GetSingleRankActionBase(num_cards);
  SPIEL_CHECK_GE(action, action_base);
  return SingleRankHandParams(action - action_base, num_cards);
}
References action, GetNumCardsPerRank(), GetSingleRankActionBase(), and SPIEL_CHECK_GE.
Referenced by SearchSingleRankActions(), and SingleRankHand().
GetSingleTrioCombParams()
TrioCombParams open_spiel::dou_dizhu::GetSingleTrioCombParams (int action)
Definition at line 391 of file dou_dizhu_utils.cc.
{
  if (action < kTrioWithSoloActionBase || action >= kAirplaneActionBase)
    SpielFatalError("Must be single trio pattern");
  const int action_base = GetTrioCombActionBase(action);
  const KickerType kicker_type = GetTrioCombKickerType(action);
  const int hand_id = (action - action_base);
  const int num_kickers = kicker_type == kSolo ? kNumRanks - 1 : kNumRanks - 3;
  const int head = hand_id / num_kickers;
  const int kicker_steps = hand_id % num_kickers;
  return TrioCombParams(head, 1, kicker_type, kicker_steps);
}
References action, GetTrioCombActionBase(), GetTrioCombKickerType(), kAirplaneActionBase, kNumRanks, kSolo, and open_spiel::SpielFatalError().
Referenced by SearchSingleTrioCombActions(), and SingleTrioCombHand().
GetTrioCombActionBase()
int open_spiel::dou_dizhu::GetTrioCombActionBase (int action)
Definition at line 352 of file dou_dizhu_utils.cc.
{
  int action_base;
  if (kTrioWithSoloActionBase <= action && action < kTrioWithPairActionBase) {
    action_base = kTrioWithSoloActionBase;
  } else if (kTrioWithPairActionBase <= action &&
             action < kAirplaneActionBase) {
    action_base = kTrioWithPairActionBase;
  } else if (kAirplaneWithSoloActionBase <= action &&
             action < kAirplaneWithPairActionBase) {
    action_base = kAirplaneWithSoloActionBase;
  } else if (kAirplaneWithPairActionBase <= action &&
             action < kBombActionBase) {
    action_base = kAirplaneWithPairActionBase;
  } else {
    SpielFatalError("Invalid action Ids");
  }
  return action_base;
}
References action, kAirplaneActionBase, kAirplaneWithPairActionBase, kAirplaneWithSoloActionBase, kBombActionBase, kTrioWithPairActionBase, kTrioWithSoloActionBase, and open_spiel::SpielFatalError().
Referenced by GetSingleTrioCombParams().
GetTrioCombKickerType()
KickerType open_spiel::dou_dizhu::GetTrioCombKickerType (int action)
Definition at line 371 of file dou_dizhu_utils.cc.
{
  KickerType kicker_type;
  if (kTrioWithSoloActionBase <= action && action < kTrioWithPairActionBase) {
    kicker_type = kSolo;
  } else if (kTrioWithPairActionBase <= action &&
             action < kAirplaneActionBase) {
    kicker_type = kPair;
  } else if (kAirplaneWithSoloActionBase <= action &&
             action < kAirplaneWithPairActionBase) {
    kicker_type = kSolo;
  } else if (kAirplaneWithPairActionBase <= action &&
             action < kBombActionBase) {
    kicker_type = kPair;
  } else {
    SpielFatalError("Invalid action Ids");
  }
  return kicker_type;
}
References action, kAirplaneActionBase, kAirplaneWithPairActionBase, kAirplaneWithSoloActionBase, kBombActionBase, kPair, kSolo, kTrioWithPairActionBase, kTrioWithSoloActionBase, and open_spiel::SpielFatalError().
Referenced by GetSingleTrioCombParams().
RankString()
std::string open_spiel::dou_dizhu::RankString (int rank)
Definition at line 37 of file dou_dizhu_utils.cc.
{
  if (rank < kNumRanks - 2)
    return std::string(1, kRankChar[rank]);
  else if (rank == kNumRanks - 2)
    return "(BWJ)";
  else if (rank == kNumRanks - 1)
    return "(CJ)";
  else
    SpielFatalError("Non valid rank");
}
References kNumRanks, kRankChar, rank, and open_spiel::SpielFatalError().
Referenced by CardString(), FormatAirplaneCombHand(), and FormatSingleHand().
SearchAirplaneCombActions()
void open_spiel::dou_dizhu::SearchAirplaneCombActions (std::vector< Action > * actions, absl::Span< const int > hand, int prev_action = kInvalidAction)
Definition at line 807 of file dou_dizhu_utils.cc.
{
  TrioCombParams prev_action_params;
  int start_rank;
  if (prev_action == kInvalidAction) {
    start_rank = 0;
  } else {
    prev_action_params = GetAirplaneCombParams(prev_action);
    start_rank = prev_action_params.chain_head + 1;
  }
  for (int chain_head = start_rank; chain_head < kNumRanks - 4; ++chain_head) {
    if (hand[chain_head] < 3) continue;
    int num_cards = hand[chain_head];
    for (int chain_length = 2; chain_head + chain_length - 1 < kNumRanks - 3;
         ++chain_length) {
      int chain_tail = chain_head + chain_length - 1;
      num_cards = std::min(num_cards, hand[chain_tail]);
      if (num_cards < 3) break;
      std::vector<KickerType> all_kicker_types;
      if (prev_action != kInvalidAction) {
        if (chain_length > prev_action_params.chain_length) break;
        if (chain_length == prev_action_params.chain_length) {
          all_kicker_types.push_back(prev_action_params.kicker_type);
        }
      } else {
        all_kicker_types.push_back(kSolo);
        all_kicker_types.push_back(kPair);
      }
      for (auto kicker_type : all_kicker_types) {
        std::array<int, kNumRanks> used_hand{};
        for (int i = 0; i < chain_length; ++i) used_hand[chain_head + i] = 3;
        dfs_add_all_airplane_kickers(chain_head, chain_length, 0, kNumRanks - 1,
                                     absl::MakeSpan(used_hand),
                                     absl::MakeSpan(hand), actions,
                                     kicker_type);
      }
    }
  }
}
References open_spiel::dou_dizhu::TrioCombParams::chain_head, open_spiel::dou_dizhu::TrioCombParams::chain_length, dfs_add_all_airplane_kickers(), GetAirplaneCombParams(), i, open_spiel::dou_dizhu::TrioCombParams::kicker_type, open_spiel::kInvalidAction, kNumRanks, kPair, kSolo, and absl::MakeSpan().
Referenced by AirplaneCombHandTest(), and SearchForLegalActions().
SearchChainOnlyActions()
void open_spiel::dou_dizhu::SearchChainOnlyActions (std::vector< Action > * actions, absl::Span< const int > hand, int prev_action = kInvalidAction)
Definition at line 305 of file dou_dizhu_utils.cc.
{
  ChainOnlyHandParams prev_action_params;
  int start_rank;
  if (prev_action == kInvalidAction) {
    start_rank = 0;
  } else {
    prev_action_params = GetChainOnlyHandParams(prev_action);
    start_rank = prev_action_params.chain_head + 1;
  }
  for (int chain_head = start_rank; chain_head < kNumRanks - 4; ++chain_head) {
    if (!hand[chain_head] || hand[chain_head] == kNumSuits) continue;
    int num_cards = hand[chain_head];
    // 2-s and Jokers cannot be in chain
    for (int chain_length = 2; chain_head + chain_length - 1 < kNumRanks - 3;
         ++chain_length) {
      int chain_tail = chain_head + chain_length - 1;
      num_cards = std::min(num_cards, hand[chain_tail]);
      if (!num_cards) break;
      std::vector<int> all_nums;
      if (prev_action != kInvalidAction) {
        if (num_cards < prev_action_params.num_cards_per_rank) break;
        if (chain_length > prev_action_params.chain_length) break;
        if (chain_length == prev_action_params.chain_length) {
          all_nums.push_back(prev_action_params.num_cards_per_rank);
        }
      } else {
        for (int n = 1; n <= num_cards; ++n) {
          all_nums.push_back(n);
        }
      }
      for (auto n : all_nums) {
        const int min_length = GetChainOnlyMinLength(n);
        if (chain_length >= min_length) {
          std::array<int, kNumRanks> used_rank{};
          for (int i = 0; i < chain_length; ++i) used_rank[chain_head + i] = n;
          actions->push_back(ChainOnlyHandToActionId(used_rank));
        }
      }
    }
  }
}
References open_spiel::dou_dizhu::ChainOnlyHandParams::chain_head, open_spiel::dou_dizhu::ChainOnlyHandParams::chain_length, ChainOnlyHandToActionId(), GetChainOnlyHandParams(), GetChainOnlyMinLength(), i, open_spiel::kInvalidAction, kNumRanks, kNumSuits, n, and open_spiel::dou_dizhu::ChainOnlyHandParams::num_cards_per_rank.
Referenced by ChainOnlyHandTest(), and SearchForLegalActions().
SearchForLegalActions()
void open_spiel::dou_dizhu::SearchForLegalActions (std::vector< Action > * legal_actions, absl::Span< const int > hand, int prev_action)
Definition at line 874 of file dou_dizhu_utils.cc.
{
  if (hand[kNumRanks - 2] && hand[kNumRanks - 1])
    legal_actions->push_back(kRocketActionBase);
  if (prev_action == kInvalidAction) {
    // search for all possible actions
    SearchSingleRankActions(legal_actions, hand, prev_action);
    SearchChainOnlyActions(legal_actions, hand, prev_action);
    SearchSingleTrioCombActions(legal_actions, hand, prev_action);
    SearchAirplaneCombActions(legal_actions, hand, prev_action);
  } else if (prev_action >= kBombActionBase &&
             prev_action < kRocketActionBase) {
    // if previous action is a bomb, then only higher bomb or rocket can be
    // played
    SearchSingleRankActions(legal_actions, hand, prev_action);
  } else {
    // check for bombs
    for (int rank = 0; rank < kNumRanks - 2; ++rank) {
      if (hand[rank] == kNumSuits) {
        std::array<int, kNumRanks> used_rank{};
        used_rank[rank] = kNumSuits;
        legal_actions->push_back(SingleRankHandToActionId(used_rank));
      }
    }
    // then search within each category
    if ((prev_action >= kPlayActionBase &&
         prev_action < kSoloChainActionBase) ||
        (prev_action >= kPairActionBase &&
         prev_action < kPairChainActionBase) ||
        (prev_action >= kTrioActionBase &&
         prev_action < kTrioWithSoloActionBase)) {
      SearchSingleRankActions(legal_actions, hand, prev_action);
    } else if ((prev_action >= kSoloChainActionBase &&
                prev_action < kPairActionBase) ||
               (prev_action >= kPairChainActionBase &&
                prev_action < kTrioActionBase) ||
               (prev_action >= kAirplaneActionBase &&
                prev_action < kAirplaneWithSoloActionBase)) {
      SearchChainOnlyActions(legal_actions, hand, prev_action);
    } else if (prev_action >= kTrioWithSoloActionBase &&
               prev_action < kAirplaneActionBase) {
      SearchSingleTrioCombActions(legal_actions, hand, prev_action);
    } else if (prev_action >= kAirplaneWithSoloActionBase &&
               prev_action < kBombActionBase) {
      SearchAirplaneCombActions(legal_actions, hand, prev_action);
    } else if (prev_action == kRocketActionBase) {
    } else {
      SpielFatalError("Previous actions invalid");
    }
  }
}
References kAirplaneActionBase, kAirplaneWithSoloActionBase, kBombActionBase, open_spiel::kInvalidAction, kNumRanks, kNumSuits, kPairActionBase, kPairChainActionBase, kPlayActionBase, kRocketActionBase, kSoloChainActionBase, kTrioActionBase, kTrioWithSoloActionBase, rank, SearchAirplaneCombActions(), SearchChainOnlyActions(), SearchSingleRankActions(), SearchSingleTrioCombActions(), SingleRankHandToActionId(), and open_spiel::SpielFatalError().
SearchSingleRankActions()
void open_spiel::dou_dizhu::SearchSingleRankActions (std::vector< Action > * actions, absl::Span< const int > hand, int prev_action = kInvalidAction)
Definition at line 170 of file dou_dizhu_utils.cc.
{
  std::array<int, kNumRanks> used_hands{};
  SingleRankHandParams prev_action_params;
  int start_rank;
  if (prev_action == kInvalidAction) {
    start_rank = 0;
  } else {
    prev_action_params = GetSingleRankHandParams(prev_action);
    start_rank = prev_action_params.rank + 1;
  }
  for (int rank = start_rank; rank < kNumRanks; ++rank) {
    SPIEL_CHECK_LE(hand[rank], kNumSuits);
    SPIEL_CHECK_GE(hand[rank], 0);
    if (rank == kNumRanks - 2 || rank == kNumRanks - 1)
      SPIEL_CHECK_LE(hand[rank], 1);
    if (prev_action == kInvalidAction) {
      for (int i = 0; i < hand[rank]; ++i) {
        used_hands[rank]++;
        actions->push_back(SingleRankHandToActionId(used_hands));
      }
    } else if (hand[rank] >= prev_action_params.num_cards) {
      used_hands[rank] = prev_action_params.num_cards;
      actions->push_back(SingleRankHandToActionId(used_hands));
    }
    used_hands[rank] = 0;
  }
}
References GetSingleRankHandParams(), i, open_spiel::kInvalidAction, kNumRanks, kNumSuits, open_spiel::dou_dizhu::SingleRankHandParams::num_cards, open_spiel::dou_dizhu::SingleRankHandParams::rank, rank, SingleRankHandToActionId(), SPIEL_CHECK_GE, and SPIEL_CHECK_LE.
Referenced by SearchForLegalActions(), and SingleRankHandTest().
SearchSingleTrioCombActions()
void open_spiel::dou_dizhu::SearchSingleTrioCombActions (std::vector< Action > * actions, absl::Span< const int > hand, int prev_action = kInvalidAction)
Definition at line 603 of file dou_dizhu_utils.cc.
{
  TrioCombParams prev_action_params;
  int start_rank;
  if (prev_action == kInvalidAction) {
    start_rank = 0;
  } else {
    prev_action_params = GetSingleTrioCombParams(prev_action);
    start_rank = prev_action_params.chain_head + 1;
  }
  // enumerate possible trio
  for (int rank = start_rank; rank < kNumRanks - 2; ++rank) {
    if (hand[rank] < 3) continue;
    for (int kicker = 0; kicker < kNumRanks; ++kicker) {
      if (!hand[kicker] || kicker == rank) continue;
      std::vector<KickerType> all_kicker_types;
      if (prev_action != kInvalidAction) {
        if (hand[kicker] >= prev_action_params.kicker_type)
          all_kicker_types.push_back(prev_action_params.kicker_type);
      } else {
        for (int i = 1; i <= std::min(hand[kicker], 2); ++i)
          all_kicker_types.push_back(static_cast<KickerType>(i));
      }
      for (auto n : all_kicker_types) {
        std::array<int, kNumRanks> used_hand{};
        used_hand[rank] = 3;
        used_hand[kicker] = static_cast<int>(n);
        actions->push_back(SingleTrioCombHandToActionId(used_hand));
      }
    }
  }
}
References open_spiel::dou_dizhu::TrioCombParams::chain_head, GetSingleTrioCombParams(), i, open_spiel::dou_dizhu::TrioCombParams::kicker_type, open_spiel::kInvalidAction, kNumRanks, n, rank, and SingleTrioCombHandToActionId().
Referenced by SearchForLegalActions(), and SingleTrioCombHandTest().
SingleRankHand()
std::array< int, kNumRanks > open_spiel::dou_dizhu::SingleRankHand (int action)
Definition at line 142 of file dou_dizhu_utils.cc.
{
  std::array<int, kNumRanks> hand{};
  SingleRankHandParams params = GetSingleRankHandParams(action);
  hand[params.rank] = params.num_cards;
  return hand;
}
References action, GetSingleRankHandParams(), open_spiel::dou_dizhu::SingleRankHandParams::num_cards, and open_spiel::dou_dizhu::SingleRankHandParams::rank.
Referenced by ActionToHand(), and SingleRankHandTest().
SingleRankHandTest()
void open_spiel::dou_dizhu::SingleRankHandTest ()
Definition at line 28 of file dou_dizhu_utils_test.cc.
{
  std::array<int, kNumRanks> hand1{}, hand2{};
  hand1[6] = 3;
  int action_id1 = SingleRankHandToActionId(hand1);
  SPIEL_CHECK_EQ(FormatSingleHand(SingleRankHand(action_id1)), "999");
  hand2[13] = 1;
  int action_id2 = SingleRankHandToActionId(hand2);
  SPIEL_CHECK_EQ(FormatSingleHand(SingleRankHand(action_id2)), "(BWJ)");
  // 558999TJJJJKKK
  std::array<int, kNumRanks> current_hand = {0, 0, 2, 0, 0, 1, 3, 1, 4, 0, 3};
  std::vector<Action> actions1, actions2, actions3;
  // The only hands that are greater than 999 are JJJ and KKK
  SearchSingleRankActions(&actions1, current_hand, /*prev_action=*/action_id1);
  SPIEL_CHECK_EQ(static_cast<int>(actions1.size()), 2);
  // No hands greater than BWJ
  SearchSingleRankActions(&actions2, current_hand, /*prev_action=*/action_id2);
  SPIEL_CHECK_EQ(static_cast<int>(actions2.size()), 0);
  // 6 solos + 4 pairs + 3 trios + 1 bomb = 14
  SearchSingleRankActions(&actions3, current_hand,
                          /*prev_action=*/kInvalidAction);
  SPIEL_CHECK_EQ(static_cast<int>(actions3.size()), 14);
}
References FormatSingleHand(), open_spiel::kInvalidAction, SearchSingleRankActions(), SingleRankHand(), SingleRankHandToActionId(), and SPIEL_CHECK_EQ.
Referenced by main().
SingleRankHandToActionId()
int open_spiel::dou_dizhu::SingleRankHandToActionId (absl::Span< const int > hand)
Definition at line 150 of file dou_dizhu_utils.cc.
{
  int the_rank;
  int counter = 0;
  for (int rank = 0; rank < kNumRanks; ++rank) {
    if (hand[rank] != 0) {
      the_rank = rank;
      counter++;
    }
  }
  SPIEL_CHECK_EQ(counter, 1);
  const int num_cards_same_rank = hand[the_rank];
  int action = GetSingleRankActionBase(num_cards_same_rank);
  action += the_rank;
  return action;
}
References action, counter, GetSingleRankActionBase(), kNumRanks, rank, and SPIEL_CHECK_EQ.
Referenced by SearchForLegalActions(), SearchSingleRankActions(), and SingleRankHandTest().
SingleTrioCombHand()
std::array< int, kNumRanks > open_spiel::dou_dizhu::SingleTrioCombHand (int action)
Definition at line 547 of file dou_dizhu_utils.cc.
{
  std::array<int, kNumRanks> hand{};
  TrioCombParams params = GetSingleTrioCombParams(action);
  hand[params.chain_head] = 3;
  const int kicker_steps = params.kicker_id;
  int kicker_rank, counter = 0;
  for (kicker_rank = 0; kicker_rank < kNumRanks; ++kicker_rank) {
    // kicker cannot be the same rank as trio
    if (kicker_rank == params.chain_head) continue;
    if (counter++ == kicker_steps) break;
  }
  hand[kicker_rank] = (params.kicker_type == kSolo ? 1 : 2);
  return hand;
}
References action, open_spiel::dou_dizhu::TrioCombParams::chain_head, counter, GetSingleTrioCombParams(), open_spiel::dou_dizhu::TrioCombParams::kicker_id, open_spiel::dou_dizhu::TrioCombParams::kicker_type, kNumRanks, and kSolo.
Referenced by ActionToHand(), and SingleTrioCombHandTest().
SingleTrioCombHandTest()
void open_spiel::dou_dizhu::SingleTrioCombHandTest ()
Definition at line 90 of file dou_dizhu_utils_test.cc.
{
  std::array<int, kNumRanks> hand1{}, hand2{};
  // 999-(CJ)
  hand1[6] = 3;
  hand1[14] = 1;
  int action_id1 = SingleTrioCombHandToActionId(hand1);
  SPIEL_CHECK_EQ(FormatSingleHand(SingleTrioCombHand(action_id1)), "999(CJ)");
  // 333-22
  hand2[12] = 2;
  hand2[0] = 3;
  int action_id2 = SingleTrioCombHandToActionId(hand2);
  SPIEL_CHECK_EQ(FormatSingleHand(SingleTrioCombHand(action_id2)), "33322");
  // 666777TTTQQQ222(BWJ)(CJ)
  std::array<int, kNumRanks> current_hand = {0, 0, 0, 3, 3, 0, 0, 3,
                                             0, 3, 0, 0, 3, 1, 1};
  std::vector<Action> actions1, actions2, actions3;
  // The hands that are greater than 333222 uses trios 666, 777, TTT, QQQ, 222
  // And we just enuemerate all possible pairs
  SearchSingleTrioCombActions(&actions1, current_hand,
                              /*prev_action=*/action_id1);
  SPIEL_CHECK_EQ(static_cast<int>(actions1.size()), 18);
  SearchSingleTrioCombActions(&actions2, current_hand,
                              /*prev_action=*/action_id2);
  SPIEL_CHECK_EQ(static_cast<int>(actions2.size()), 20);
  SearchSingleTrioCombActions(&actions3, current_hand, kInvalidAction);
  SPIEL_CHECK_EQ(static_cast<int>(actions3.size()), 50);
}
References FormatSingleHand(), open_spiel::kInvalidAction, SearchSingleTrioCombActions(), SingleTrioCombHand(), SingleTrioCombHandToActionId(), and SPIEL_CHECK_EQ.
Referenced by main().
SingleTrioCombHandToActionId()
int open_spiel::dou_dizhu::SingleTrioCombHandToActionId (absl::Span< const int > hand)
Definition at line 566 of file dou_dizhu_utils.cc.
{
  int trio_rank, kicker_rank;
  int trio_counter = 0, kicker_counter = 0;
  for (int rank = 0; rank < kNumRanks; ++rank) {
    if (hand[rank] == 3) {
      trio_counter++;
      trio_rank = rank;
    } else if (hand[rank] == 1 || hand[rank] == 2) {
      kicker_counter++;
      kicker_rank = rank;
    } else if (hand[rank] == 4) {
      SpielFatalError("There cannot be a bomb");
    }
  }
  SPIEL_CHECK_EQ(trio_counter, 1);
  SPIEL_CHECK_EQ(kicker_counter, 1);
  int action;
  if (hand[kicker_rank] == 1)
    action = kTrioWithSoloActionBase;
  else
    action = kTrioWithPairActionBase;
  // one of the rank had already been taken by the trio
  if (hand[kicker_rank] == 1)
    action += trio_rank * (kNumRanks - 1);
  else
    action += trio_rank * (kNumRanks - 3);  // the jokers cannot be the pair
  int kicker_steps = 0;
  for (int rank = 0; rank < kNumRanks; ++rank) {
    if (rank == trio_rank) continue;
    if (rank == kicker_rank) break;
    kicker_steps++;
  }
  action += kicker_steps;
  return action;
}
References action, kNumRanks, kTrioWithPairActionBase, kTrioWithSoloActionBase, rank, SPIEL_CHECK_EQ, and open_spiel::SpielFatalError().
Referenced by SearchSingleTrioCombActions(), and SingleTrioCombHandTest().
Variable Documentation
kAirplaneActionBase
int open_spiel::dou_dizhu::kAirplaneActionBase = kTrioWithPairActionBase + 156 inline constexpr
Definition at line 79 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), GetChainOnlyActionBase(), GetNumCardsPerRank(), GetSingleTrioCombParams(), GetTrioCombActionBase(), GetTrioCombKickerType(), and SearchForLegalActions().
kAirplaneMinLength
int open_spiel::dou_dizhu::kAirplaneMinLength = 2 inline constexpr
Definition at line 78 of file dou_dizhu_utils.h.
Referenced by GetChainOnlyMinLength().
kAirplaneWithPairActionBase
int open_spiel::dou_dizhu::kAirplaneWithPairActionBase inline constexpr
Initial value:
=
    kAirplaneWithSoloActionBase + 22588
Definition at line 85 of file dou_dizhu_utils.h.
Referenced by GetAirplaneCombParams(), GetAirplanePairActionBase(), GetTrioCombActionBase(), and GetTrioCombKickerType().
kAirplaneWithPairMinLength
int open_spiel::dou_dizhu::kAirplaneWithPairMinLength = 2 inline constexpr
Definition at line 84 of file dou_dizhu_utils.h.
kAirplaneWithSoloActionBase
int open_spiel::dou_dizhu::kAirplaneWithSoloActionBase = kAirplaneActionBase + 45 inline constexpr
Definition at line 82 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), open_spiel::dou_dizhu::DouDizhuState::ActionToString(), AirplaneCombHand(), GetAirplaneCombParams(), GetAirplaneSoloActionBase(), GetNumCardsPerRank(), GetTrioCombActionBase(), GetTrioCombKickerType(), and SearchForLegalActions().
kAirplaneWithSoloMinLength
int open_spiel::dou_dizhu::kAirplaneWithSoloMinLength = 2 inline constexpr
Definition at line 81 of file dou_dizhu_utils.h.
kBiddingActionBase
int open_spiel::dou_dizhu::kBiddingActionBase = 0 inline constexpr
Definition at line 58 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuState::ActionToString().
kBombActionBase
int open_spiel::dou_dizhu::kBombActionBase = kAirplaneWithPairActionBase + 2939 inline constexpr
Definition at line 88 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), open_spiel::dou_dizhu::DouDizhuState::ActionToString(), AirplaneCombHand(), GetAirplaneCombParams(), GetNumCardsPerRank(), GetSingleRankActionBase(), GetTrioCombActionBase(), GetTrioCombKickerType(), and SearchForLegalActions().
kDealingActionBase
int open_spiel::dou_dizhu::kDealingActionBase = kNumCards - kNumCardsLeftOver inline constexpr
Definition at line 56 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuState::ActionToString(), open_spiel::dou_dizhu::DouDizhuState::ChanceOutcomes(), and open_spiel::dou_dizhu::DouDizhuGame::MaxChanceOutcomes().
kMaxAuctionLength
int open_spiel::dou_dizhu::kMaxAuctionLength = 9 inline constexpr
Definition at line 34 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuGame::MaxGameLength().
kMaxUtility
int open_spiel::dou_dizhu::kMaxUtility = kNumBids * 16384 inline constexpr
Definition at line 38 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuGame::MaxUtility().
kMinUtility
int open_spiel::dou_dizhu::kMinUtility = -kNumBids * 8192 inline constexpr
Definition at line 39 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuGame::MinUtility().
kNumBids
int open_spiel::dou_dizhu::kNumBids = 3 inline constexpr
Definition at line 29 of file dou_dizhu_utils.h.
kNumCards
int open_spiel::dou_dizhu::kNumCards = 54 inline constexpr
Definition at line 27 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuState::ActionToString(), CardToRank(), CardToSuit(), open_spiel::dou_dizhu::DouDizhuState::ChanceOutcomes(), open_spiel::dou_dizhu::DouDizhuGame::MaxChanceOutcomes(), open_spiel::dou_dizhu::DouDizhuGame::MaxGameLength(), and open_spiel::dou_dizhu::DouDizhuState::ToString().
kNumCardsLeftOver
int open_spiel::dou_dizhu::kNumCardsLeftOver = 3 inline constexpr
Definition at line 44 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuState::ToString().
kNumCardsPerSuit
int open_spiel::dou_dizhu::kNumCardsPerSuit = 13 inline constexpr
Definition at line 30 of file dou_dizhu_utils.h.
kNumKickersAirplanePairCombChainOfLengthFour
int open_spiel::dou_dizhu::kNumKickersAirplanePairCombChainOfLengthFour = 126 inline constexpr
Definition at line 98 of file dou_dizhu_utils.h.
Referenced by GetNumKickersAirplanePairComb().
kNumKickersAirplanePairCombChainOfLengthThree
int open_spiel::dou_dizhu::kNumKickersAirplanePairCombChainOfLengthThree = 120 inline constexpr
Definition at line 97 of file dou_dizhu_utils.h.
Referenced by GetNumKickersAirplanePairComb().
kNumKickersAirplanePairCombChainOfLengthTwo
int open_spiel::dou_dizhu::kNumKickersAirplanePairCombChainOfLengthTwo = 55 inline constexpr
Definition at line 96 of file dou_dizhu_utils.h.
Referenced by GetNumKickersAirplanePairComb().
kNumKickersAirplaneSoloCombChainOfLengthFive
int open_spiel::dou_dizhu::kNumKickersAirplaneSoloCombChainOfLengthFive = 1372 inline constexpr
Definition at line 94 of file dou_dizhu_utils.h.
Referenced by GetNumKickersAirplaneSoloComb().
kNumKickersAirplaneSoloCombChainOfLengthFour
int open_spiel::dou_dizhu::kNumKickersAirplaneSoloCombChainOfLengthFour = 816 inline constexpr
Definition at line 93 of file dou_dizhu_utils.h.
Referenced by GetNumKickersAirplaneSoloComb().
kNumKickersAirplaneSoloCombChainOfLengthThree
int open_spiel::dou_dizhu::kNumKickersAirplaneSoloCombChainOfLengthThree = 330 inline constexpr
Definition at line 92 of file dou_dizhu_utils.h.
Referenced by GetNumKickersAirplaneSoloComb().
kNumKickersAirplaneSoloCombChainOfLengthTwo
int open_spiel::dou_dizhu::kNumKickersAirplaneSoloCombChainOfLengthTwo = 88 inline constexpr
Definition at line 91 of file dou_dizhu_utils.h.
Referenced by GetNumKickersAirplaneSoloComb().
kNumPlayers
int open_spiel::dou_dizhu::kNumPlayers = 3 inline constexpr
Definition at line 26 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuGame::MaxGameLength(), open_spiel::dou_dizhu::DouDizhuGame::NumPlayers(), open_spiel::dou_dizhu::DouDizhuState::ObservationString(), and open_spiel::dou_dizhu::DouDizhuState::WriteObservationTensor().
kNumRanks
int open_spiel::dou_dizhu::kNumRanks = kNumCardsPerSuit + 2 inline constexpr
Definition at line 42 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), AirplaneCombHand(), AirplaneCombHandToActionId(), CardString(), CardToRank(), CardToSuit(), ChainOnlyHandToActionId(), dfs_add_all_airplane_kickers(), dfs_airplane_kicker(), FormatAirplaneCombHand(), FormatHand(), FormatSingleHand(), GetChainOnlyHandParams(), GetSingleTrioCombParams(), RankString(), SearchAirplaneCombActions(), SearchChainOnlyActions(), SearchForLegalActions(), SearchSingleRankActions(), SearchSingleTrioCombActions(), SingleRankHandToActionId(), SingleTrioCombHand(), SingleTrioCombHandToActionId(), and open_spiel::dou_dizhu::DouDizhuState::WriteObservationTensor().
kNumSuits
int open_spiel::dou_dizhu::kNumSuits = 4 inline constexpr
Definition at line 46 of file dou_dizhu_utils.h.
Referenced by AirplaneCombHandToActionId(), CardString(), dfs_add_all_airplane_kickers(), dfs_airplane_kicker(), SearchChainOnlyActions(), SearchForLegalActions(), SearchSingleRankActions(), and open_spiel::dou_dizhu::DouDizhuState::WriteObservationTensor().
kObservationTensorSize
int open_spiel::dou_dizhu::kObservationTensorSize inline constexpr
Initial value:
=
    2 * ((kNumRanks - 2) * (kNumSuits + 1) + 2 * 2) + kNumPlayers +
    kNumPlayers + kNumRanks
Definition at line 52 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuGame::ObservationTensorShape().
kPairActionBase
int open_spiel::dou_dizhu::kPairActionBase = kSoloChainActionBase + 36 inline constexpr
Definition at line 67 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), GetNumCardsPerRank(), GetSingleRankActionBase(), and SearchForLegalActions().
kPairChainActionBase
int open_spiel::dou_dizhu::kPairChainActionBase = kPairActionBase + 13 inline constexpr
Definition at line 70 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), GetChainOnlyActionBase(), and SearchForLegalActions().
kPairChainMinLength
int open_spiel::dou_dizhu::kPairChainMinLength = 3 inline constexpr
Definition at line 69 of file dou_dizhu_utils.h.
Referenced by GetChainOnlyMinLength().
kPass
int open_spiel::dou_dizhu::kPass = kBiddingActionBase inline constexpr
Definition at line 60 of file dou_dizhu_utils.h.
Referenced by open_spiel::dou_dizhu::DouDizhuState::ActionToString().
kPlayActionBase
int open_spiel::dou_dizhu::kPlayActionBase = kBiddingActionBase + 1 + kNumBids inline constexpr
Definition at line 62 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), open_spiel::dou_dizhu::DouDizhuState::ActionToString(), GetNumCardsPerRank(), GetSingleRankActionBase(), and SearchForLegalActions().
kRankChar
char open_spiel::dou_dizhu::kRankChar[] = "3456789TJQKA2" constexpr
Definition at line 100 of file dou_dizhu_utils.h.
Referenced by CardString(), FormatHand(), and RankString().
kRocketActionBase
int open_spiel::dou_dizhu::kRocketActionBase = kBombActionBase + 13 inline constexpr
Definition at line 89 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), open_spiel::dou_dizhu::DouDizhuState::ActionToString(), GetNumCardsPerRank(), open_spiel::dou_dizhu::DouDizhuGame::NumDistinctActions(), and SearchForLegalActions().
kSoloChainActionBase
int open_spiel::dou_dizhu::kSoloChainActionBase = kPlayActionBase + 15 inline constexpr
Definition at line 65 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), GetChainOnlyActionBase(), and SearchForLegalActions().
kSoloChainMinLength
int open_spiel::dou_dizhu::kSoloChainMinLength = 5 inline constexpr
Definition at line 64 of file dou_dizhu_utils.h.
Referenced by GetChainOnlyMinLength().
kSuitChar
char open_spiel::dou_dizhu::kSuitChar[] = "CDHS" constexpr
Definition at line 102 of file dou_dizhu_utils.h.
Referenced by CardString().
kTrioActionBase
int open_spiel::dou_dizhu::kTrioActionBase = kPairChainActionBase + 52 inline constexpr
Definition at line 72 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), GetNumCardsPerRank(), GetSingleRankActionBase(), and SearchForLegalActions().
kTrioWithPairActionBase
int open_spiel::dou_dizhu::kTrioWithPairActionBase = kTrioWithSoloActionBase + 182 inline constexpr
Definition at line 76 of file dou_dizhu_utils.h.
Referenced by GetTrioCombActionBase(), GetTrioCombKickerType(), and SingleTrioCombHandToActionId().
kTrioWithSoloActionBase
int open_spiel::dou_dizhu::kTrioWithSoloActionBase = kTrioActionBase + 13 inline constexpr
Definition at line 74 of file dou_dizhu_utils.h.
Referenced by ActionToHand(), GetNumCardsPerRank(), GetTrioCombActionBase(), GetTrioCombKickerType(), SearchForLegalActions(), and SingleTrioCombHandToActionId().