open spiel: open_spiel::testing Namespace Reference
open_spiel::testing Namespace Reference
Typedefs
using TabularPolicyGenerator = std::function<TabularPolicy(const Game&)>
Functions
void DefaultStateChecker (const State &state)
void LoadGameTest (const std::string &game_name)
void NoChanceOutcomesTest (const Game &game)
void ChanceOutcomesTest (const Game &game)
void TestUndo (std::unique_ptr< State > state, const std::vector< HistoryItem > &history)
void TestSerializeDeserialize (const Game &game, const State *state)
void TestHistoryContainsActions (const Game &game, const std::vector< HistoryItem > &history)
void CheckReturnsSum (const Game &game, const State &state)
void CheckObservables (const Game &game, const State &state, Observation *observation)
void CheckActionStringsAreUniqueForPlayer (const Game &game, State &state, Player player)
void CheckActionStringsAreUnique (const Game &game, State &state)
std::vector< double > RandomDistribution (int num_states, std::mt19937 *rng)
void RandomSimulation (std::mt19937 *rng, const Game &game, bool undo, bool serialize, bool verbose, bool mask_test, std::shared_ptr< Observer > observer, std::function< void(const State &)> state_checker_fn, int mean_field_population=-1)
void RandomSimTest (const Game &game, int num_sims, bool serialize, bool verbose, bool mask_test, const std::function< void(const State &)> &state_checker_fn, int mean_field_population, std::shared_ptr< Observer > observer)
void RandomSimTestWithUndo (const Game &game, int num_sims)
void RandomSimTestNoSerialize (const Game &game, int num_sims)
void RandomSimTestCustomObserver (const Game &game, const std::shared_ptr< Observer > observer)
std::string ChanceOutcomeStr (const ActionsAndProbs &chance_outcomes)
void CheckChanceOutcomes (const State &state)
void CheckChanceOutcomes (const Game &game)
void ResampleInfostateTest (const Game &game, int num_sims)
void TestPoliciesCanPlay (TabularPolicyGenerator policy_generator, const Game &game, int numSims)
void TestPoliciesCanPlay (const Policy &policy, const Game &game, int numSims)
void TestEveryInfostateInPolicy (TabularPolicyGenerator policy_generator, const Game &game)
void CheckLegalActionsAreSorted (const Game &game, State &state)
void ConsolePlayTest (const Game &game, const State *start_state, const std::vector< Action > *start_history, const std::unordered_map< Player, std::unique_ptr< Bot > > *bots)
Variables
constexpr int kDefaultNumSimsForPolicyTests = 10
Typedef Documentation
TabularPolicyGenerator
using open_spiel::testing::TabularPolicyGenerator = std::function<TabularPolicy(const Game&)>
Definition at line 77 of file basic_tests.h.
Function Documentation
ChanceOutcomesTest()
void open_spiel::testing::ChanceOutcomesTest (const Game & game)
Definition at line 148 of file basic_tests.cc.
{
  std::cout << "ChanceOutcomesTest, game = " << game.GetType().short_name
            << std::endl;
  int max_outcomes = game.MaxChanceOutcomes();
  SPIEL_CHECK_GT(max_outcomes, 0);
}
References SPIEL_CHECK_GT.
Referenced by open_spiel::tarok::BasicGameTests().
ChanceOutcomeStr()
std::string open_spiel::testing::ChanceOutcomeStr (const ActionsAndProbs & chance_outcomes)
Definition at line 582 of file basic_tests.cc.
{
  std::string str;
  for (auto outcome : chance_outcomes) {
    if (!str.empty()) str.append(", ");
    absl::StrAppend(&str, "(", outcome.first, ", ", outcome.second, ")");
  }
  return str;
}
References absl::StrAppend().
Referenced by CheckChanceOutcomes().
CheckActionStringsAreUnique()
void open_spiel::testing::CheckActionStringsAreUnique (const Game & game, State & state)
Definition at line 272 of file basic_tests.cc.
{
  if (state.IsTerminal() || state.IsMeanFieldNode()) return;
  if (state.IsSimultaneousNode()) {
    for (int player = 0; player < game.NumPlayers(); ++player) {
      CheckActionStringsAreUniqueForPlayer(game, state, player);
    }
  } else{
    // Also works for chance node.
    CheckActionStringsAreUniqueForPlayer(game, state, state.CurrentPlayer());
  }
}
References CheckActionStringsAreUniqueForPlayer(), player, and state.
Referenced by RandomSimulation().
CheckActionStringsAreUniqueForPlayer()
void open_spiel::testing::CheckActionStringsAreUniqueForPlayer (const Game & game, State & state, Player player)
Definition at line 259 of file basic_tests.cc.
{
  absl::flat_hash_set<std::string> action_strings;
  for (Action action : state.LegalActions(player)) {
    const auto action_str = state.ActionToString(player, action);
    const auto& [unused, was_inserted] = action_strings.insert(action_str);
    SPIEL_CHECK_TRUE_WSI(
        was_inserted,
        absl::StrCat("Duplicate action string '", action_str, "' in state"),
        game, state);
  }
}
References action, absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), player, SPIEL_CHECK_TRUE_WSI, state, and absl::StrCat().
Referenced by CheckActionStringsAreUnique().
CheckChanceOutcomes() [1/2]
void open_spiel::testing::CheckChanceOutcomes (const Game & game)
Definition at line 659 of file basic_tests.cc.
{
  CheckChanceOutcomes(*game.NewInitialState());
}
References CheckChanceOutcomes().
CheckChanceOutcomes() [2/2]
void open_spiel::testing::CheckChanceOutcomes (const State & state)
Definition at line 598 of file basic_tests.cc.
{
  if (state.IsTerminal()) return;
  if (state.IsChanceNode()) {
    auto legal_actions = state.LegalActions(kChancePlayerId);
    auto default_legal_actions = state.LegalActions();
    if (legal_actions != default_legal_actions) {
      SpielFatalError(absl::StrCat(
          "Legalactions() and LegalActions(kChancePlayerId) do not give the "
          "same result:",
          "\nLegalActions():                ",
          absl::StrJoin(default_legal_actions, ", "),
          "\nLegalActions(kChancePlayerId): ",
          absl::StrJoin(legal_actions, ", ")));
    }
    absl::btree_set<Action> legal_action_set(legal_actions.begin(),
                                             legal_actions.end());
    auto chance_outcomes = state.ChanceOutcomes();
    std::vector<Action> chance_outcome_actions;
    double sum = 0;
    for (const auto& [action, prob] : chance_outcomes) {
      chance_outcome_actions.push_back(action);
      if (legal_action_set.count(action) == 0) {
        SpielFatalError(absl::StrCat("LegalActions()=[",
                                     absl::StrJoin(legal_actions, ", "),
                                     "] inconsistent with ChanceOutcomes()=",
                                     ChanceOutcomeStr(chance_outcomes), "."));
      }
      if (prob <= 0. || prob > 1) {
        SpielFatalError(absl::StrCat(
            "Invalid probability for outcome: P(", action, ")=", prob,
            "; all outcomes=", ChanceOutcomeStr(chance_outcomes)));
      }
      sum += prob;
    }
    absl::btree_set<Action> chance_outcome_actions_set(
        chance_outcome_actions.begin(), chance_outcome_actions.end());
    if (chance_outcome_actions.size() != chance_outcome_actions_set.size()) {
      std::sort(chance_outcome_actions.begin(), chance_outcome_actions.end());
      SpielFatalError(absl::StrCat(
          "There are some duplicate actions in ChanceOutcomes\n. There are: ",
          chance_outcome_actions_set.size(), " unique legal actions over ",
          chance_outcome_actions.size(),
          " chance outcome actions.\n Sorted legal actions:\n",
          absl::StrJoin(chance_outcome_actions, ", ")));
    }
    constexpr double eps = 1e-5;
    if (sum < 1 - eps || sum > 1 + eps) {
      SpielFatalError(
          absl::StrCat("Invalid probabilities; sum=", sum,
                       "; all outcomes=", ChanceOutcomeStr(chance_outcomes)));
    }
  }
  // Handles chance nodes, player nodes, including simultaneous nodes if
  // supported.
  for (auto action : state.LegalActions()) {
    auto next_state = state.Child(action);
    CheckChanceOutcomes(*next_state);
  }
}
References action, ChanceOutcomeStr(), CheckChanceOutcomes(), absl::container_internal::btree_container< Tree >::count(), open_spiel::kChancePlayerId, absl::container_internal::btree_container< Tree >::size(), open_spiel::SpielFatalError(), state, absl::StrCat(), and absl::StrJoin().
Referenced by CheckChanceOutcomes(), CheckChanceOutcomes(), and main().
CheckLegalActionsAreSorted()
void open_spiel::testing::CheckLegalActionsAreSorted (const Game & game, State & state)
Definition at line 742 of file basic_tests.cc.
{
  if (state.IsChanceNode()) return;
  for (int player = 0; player < game.NumPlayers(); ++player) {
    auto actions = state.LegalActions(player);
    for (int i = 1; i < actions.size(); ++i) {
      SPIEL_CHECK_LT(actions[i - 1], actions[i]);
    }
  }
}
References i, player, SPIEL_CHECK_LT, and state.
Referenced by RandomSimulation().
CheckObservables()
void open_spiel::testing::CheckObservables (const Game & game, const State & state, Observation * observation)
Definition at line 228 of file basic_tests.cc.
                       {
  for (auto p = Player{0}; p < game.NumPlayers(); ++p) {
    if (game.GetType().provides_information_state_tensor) {
      std::vector<float> tensor = state.InformationStateTensor(p);
      for (float val : tensor) SPIEL_CHECK_TRUE(std::isfinite(val));
      SPIEL_CHECK_EQ(tensor.size(), game.InformationStateTensorSize());
    }
    if (game.GetType().provides_observation_tensor) {
      std::vector<float> tensor = state.ObservationTensor(p);
      for (float val : tensor) SPIEL_CHECK_TRUE(std::isfinite(val));
      SPIEL_CHECK_EQ(tensor.size(), game.ObservationTensorSize());
    }
    if (game.GetType().provides_information_state_string) {
      // Checking it does not raise errors.
      state.InformationStateString(p);
    }
    if (game.GetType().provides_observation_string) {
      // Checking it does not have errors.
      state.ObservationString(p);
    }
    if (observation != nullptr) {
      if (observation->HasString()) observation->StringFrom(state, p);
      if (observation->HasTensor()) observation->SetFrom(state, p);
    }
  }
}
References SPIEL_CHECK_EQ, SPIEL_CHECK_TRUE, and state.
Referenced by RandomSimulation().
CheckReturnsSum()
void open_spiel::testing::CheckReturnsSum (const Game & game, const State & state)
Definition at line 187 of file basic_tests.cc.
{
  std::vector<double> returns = state.Returns();
  double rsum = std::accumulate(returns.begin(), returns.end(), 0.0);
  absl::optional<double> utility_sum = game.UtilitySum();
  switch (game.GetType().utility) {
    case GameType::Utility::kZeroSum: {
      SPIEL_CHECK_EQ(utility_sum, 0.0);
      SPIEL_CHECK_TRUE(Near(rsum, 0.0, kRewardEpsilon));
      break;
    }
    case GameType::Utility::kConstantSum: {
      SPIEL_CHECK_TRUE(utility_sum.has_value());
      SPIEL_CHECK_FLOAT_NEAR(rsum, *utility_sum, kRewardEpsilon);
      break;
    }
    case GameType::Utility::kIdentical: {
      SPIEL_CHECK_FALSE(utility_sum.has_value());
      for (int i = 1; i < returns.size(); ++i) {
        SPIEL_CHECK_TRUE(Near(returns[i], returns[i - 1], kRewardEpsilon));
      }
      break;
    }
    case GameType::Utility::kGeneralSum: {
      SPIEL_CHECK_FALSE(utility_sum.has_value());
    }
  }
}
References absl::optional< T >::has_value(), i, open_spiel::GameType::kConstantSum, open_spiel::GameType::kGeneralSum, open_spiel::GameType::kIdentical, open_spiel::GameType::kZeroSum, open_spiel::Near(), SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_FLOAT_NEAR, SPIEL_CHECK_TRUE, and state.
Referenced by RandomSimulation().
ConsolePlayTest()
void open_spiel::testing::ConsolePlayTest (const Game & game, const State * start_state, const std::vector< Action > * start_history, const std::unordered_map< Player, std::unique_ptr< Bot > > * bots)
Definition at line 66 of file console_play_test.cc.
{
  // Sampled stochastic and simultaneous move games are not yet supported.
  GameType type = game.GetType();
  SPIEL_CHECK_NE(type.chance_mode, GameType::ChanceMode::kSampledStochastic);
  SPIEL_CHECK_NE(type.dynamics, GameType::Dynamics::kSimultaneous);
  std::unique_ptr<State> state;
  if (start_state != nullptr) {
    state = start_state->Clone();
  } else {
    state = game.NewInitialState();
    if (start_history != nullptr) {
      for (Action action : *start_history) {
        state->ApplyAction(action);
      }
    }
  }
  bool applied_action = true;
  std::unique_ptr<State> new_state;
  while (true) {
    if (applied_action) {
      std::cout << state->ToString() << std::endl << std::endl;
    }
    applied_action = false;
    Player player = state->CurrentPlayer();
    std::vector<Action> legal_actions = state->LegalActions();
    if (state->IsTerminal()) {
      std::cout << "Warning! State is terminal. Returns: ";
      for (Player p = 0; p < game.NumPlayers(); ++p) {
        std::cout << state->PlayerReturn(p) << " ";
      }
      std::cout << std::endl;
    }
    if (bots != nullptr && bots->at(player) != nullptr) {
      Action action = bots->at(player)->Step(*state);
      std::cout << "Bot chose action: " << state->ActionToString(player, action)
                << std::endl;
      state->ApplyAction(action);
      applied_action = true;
    } else {
      std::cout << "[Enter move, or press enter for help menu]> ";
      std::string line = "";
      std::getline(std::cin, line);
      absl::StripAsciiWhitespace(&line);
      if (line.empty()) {
        PrintHelpMenu();
      } else if (line == "#b") {
        Action last_action = state->History().back();
        new_state = game.NewInitialState();
        std::vector<Action> history = state->History();
        for (int i = 0; i < history.size() - 1; ++i) {
          new_state->ApplyAction(history[i]);
        }
        state = std::move(new_state);
        std::cout << "Popped action: " << last_action << std::endl;
        applied_action = true;
      } else if (line == "#q") {
        return;
      } else if (ParseCommand(line, game, state.get(), legal_actions)) {
        // Do nothing, was already handled.
      } else {
        Action action;
        bool valid_integer = absl::SimpleAtoi(line, &action);
        if (valid_integer) {
          auto iter = absl::c_find(legal_actions, action);
          SPIEL_CHECK_TRUE(iter != legal_actions.end());
          state->ApplyAction(action);
          applied_action = true;
        } else {
          // Search for the move string.
          for (Action action : legal_actions) {
            if (line == state->ActionToString(player, action)) {
              state->ApplyAction(action);
              applied_action = true;
              break;
            }
          }
        }
      }
    }
  }
  std::cout << "Terminal state:" << std::endl
            << std::endl
            << state->ToString() << std::endl;
  std::cout << "Returns: ";
  std::vector<double> returns = state->Returns();
  for (Player p = 0; p < game.NumPlayers(); ++p) {
    std::cout << returns[p] << " ";
  }
  std::cout << std::endl;
}
References action, absl::c_find(), open_spiel::GameType::chance_mode, open_spiel::State::Clone(), open_spiel::GameType::dynamics, i, open_spiel::GameType::kSampledStochastic, open_spiel::GameType::kSimultaneous, player, absl::SimpleAtoi(), SPIEL_CHECK_NE, SPIEL_CHECK_TRUE, state, and absl::StripAsciiWhitespace().
DefaultStateChecker()
void open_spiel::testing::DefaultStateChecker (const State & state)
Definition at line 133 of file basic_tests.cc.
{}
Referenced by RandomSimTestCustomObserver(), RandomSimTestNoSerialize(), and RandomSimTestWithUndo().
LoadGameTest()
void open_spiel::testing::LoadGameTest (const std::string & game_name)
Definition at line 136 of file basic_tests.cc.
{
  std::shared_ptr<const Game> game = LoadGame(game_name);
  SPIEL_CHECK_TRUE(game != nullptr);
}
References open_spiel::LoadGame(), and SPIEL_CHECK_TRUE.
Referenced by open_spiel::coin_game::BasicCoinGameTests(), open_spiel::tarok::BasicGameTests(), and main().
NoChanceOutcomesTest()
void open_spiel::testing::NoChanceOutcomesTest (const Game & game)
Definition at line 141 of file basic_tests.cc.
{
  std::cout << "NoChanceOutcomesTest, game = " << game.GetType().short_name
            << std::endl;
  int max_outcomes = game.MaxChanceOutcomes();
  SPIEL_CHECK_EQ(max_outcomes, 0);
}
References SPIEL_CHECK_EQ.
RandomDistribution()
std::vector< double > open_spiel::testing::RandomDistribution (int num_states, std::mt19937 * rng)
Definition at line 285 of file basic_tests.cc.
{
  std::uniform_real_distribution<double> rand(0, 1);
  std::vector<double> distrib;
  distrib.reserve(num_states);
  for (int i = 0; i < num_states; ++i) {
    distrib.push_back(rand(*rng));
  }
  double sum = std::accumulate(distrib.begin(), distrib.end(), 0.);
  for (int i = 0; i < num_states; ++i) {
    distrib[i] /= sum;
  }
  return distrib;
}
References i.
Referenced by RandomSimulation().
RandomSimTest()
void open_spiel::testing::RandomSimTest (const Game & game, int num_sims, bool serialize, bool verbose, bool mask_test, const std::function< void(const State &)> & state_checker_fn, int mean_field_population, std::shared_ptr< Observer > observer)
Definition at line 534 of file basic_tests.cc.
{
  std::mt19937 rng;
  if (verbose) {
    std::cout << "\nRandomSimTest, game = " << game.GetType().short_name
              << ", num_sims = " << num_sims << std::endl;
  }
  for (int sim = 0; sim < num_sims; ++sim) {
    RandomSimulation(&rng, game, /*undo=*/false, /*serialize=*/serialize,
                     verbose, mask_test, observer, state_checker_fn,
                     mean_field_population);
  }
}
References RandomSimulation().
Referenced by open_spiel::coin_game::BasicCoinGameTests(), open_spiel::tarok::BasicGameTests(), and main().
RandomSimTestCustomObserver()
void open_spiel::testing::RandomSimTestCustomObserver (const Game & game, const std::shared_ptr< Observer > observer)
Definition at line 573 of file basic_tests.cc.
{
  std::mt19937 rng;
  RandomSimulation(&rng, game, /*undo=*/false, /*serialize=*/false,
                   /*verbose=*/false, /*mask_test=*/true, observer,
                   &DefaultStateChecker);
}
References DefaultStateChecker(), and RandomSimulation().
RandomSimTestNoSerialize()
void open_spiel::testing::RandomSimTestNoSerialize (const Game & game, int num_sims)
Definition at line 562 of file basic_tests.cc.
{
  std::mt19937 rng;
  std::cout << "RandomSimTestNoSerialize, game = " << game.GetType().short_name
            << ", num_sims = " << num_sims << std::endl;
  for (int sim = 0; sim < num_sims; ++sim) {
    RandomSimulation(&rng, game, /*undo=*/false, /*serialize=*/false,
                     /*verbose=*/true, /*mask_test=*/true, nullptr,
                     &DefaultStateChecker);
  }
}
References DefaultStateChecker(), and RandomSimulation().
Referenced by open_spiel::WriteAndLoadGame().
RandomSimTestWithUndo()
void open_spiel::testing::RandomSimTestWithUndo (const Game & game, int num_sims)
Definition at line 551 of file basic_tests.cc.
{
  std::mt19937 rng;
  std::cout << "RandomSimTestWithUndo, game = " << game.GetType().short_name
            << ", num_sims = " << num_sims << std::endl;
  for (int sim = 0; sim < num_sims; ++sim) {
    RandomSimulation(&rng, game, /*undo=*/true, /*serialize=*/true,
                     /*verbose=*/true, /*mask_test=*/true, nullptr,
                     &DefaultStateChecker);
  }
}
References DefaultStateChecker(), and RandomSimulation().
RandomSimulation()
void open_spiel::testing::RandomSimulation (std::mt19937 * rng, const Game & game, bool undo, bool serialize, bool verbose, bool mask_test, std::shared_ptr< Observer > observer, std::function< void(const State &)> state_checker_fn, int mean_field_population = -1)
Definition at line 299 of file basic_tests.cc.
{
  std::unique_ptr<Observation> observation =
      observer == nullptr ? nullptr
                          : std::make_unique<Observation>(game, observer);
  std::vector<HistoryItem> history;
  std::vector<double> episode_returns(game.NumPlayers(), 0);
  int infostate_vector_size = game.GetType().provides_information_state_tensor
                                  ? game.InformationStateTensorSize()
                                  : 0;
  if (verbose) {
    std::cout << "Information state vector size: " << infostate_vector_size
              << std::endl;
  }
  int observation_vector_size = game.GetType().provides_observation_tensor
                                    ? game.ObservationTensorSize()
                                    : 0;
  if (verbose) {
    std::cout << "Observation vector size: " << observation_vector_size
              << std::endl;
  }
  SPIEL_CHECK_TRUE(game.MinUtility() < game.MaxUtility());
  if (verbose) {
    std::cout << "Utility range: " << game.MinUtility() << " "
              << game.MaxUtility() << std::endl;
    std::cout << "Starting new game.." << std::endl;
  }
  std::unique_ptr<open_spiel::State> state;
  if (mean_field_population == -1) {
    state = game.NewInitialState();
  } else {
    state = game.NewInitialStateForPopulation(mean_field_population);
  }
  if (verbose) {
    std::cout << "Initial state:" << std::endl;
    std::cout << "State:" << std::endl << state->ToString() << std::endl;
  }
  int game_length = 0;
  int num_moves = 0;
  while (!state->IsTerminal()) {
    state_checker_fn(*state);
    if (verbose) {
      std::cout << "player " << state->CurrentPlayer() << std::endl;
    }
    LegalActionsIsEmptyForOtherPlayers(game, *state);
    CheckLegalActionsAreSorted(game, *state);
    CheckActionStringsAreUnique(game, *state);
    // Test cloning the state.
    std::unique_ptr<open_spiel::State> state_copy = state->Clone();
    SPIEL_CHECK_EQ(state->ToString(), state_copy->ToString());
    SPIEL_CHECK_EQ(state->History(), state_copy->History());
    if (game.GetType().dynamics == GameType::Dynamics::kMeanField) {
      SPIEL_CHECK_LT(state->MoveNumber(), game.MaxMoveNumber());
      SPIEL_CHECK_EQ(state->MoveNumber(), num_moves);
    }
    if (serialize && (history.size() < 10 || IsPowerOfTwo(history.size()))) {
      TestSerializeDeserialize(game, state.get());
    }
    if (state->IsChanceNode()) {
      if (mask_test) LegalActionsMaskTest(game, *state, kChancePlayerId,
                                          state->LegalActions());
      // Chance node; sample one according to underlying distribution
      std::vector<std::pair<Action, double>> outcomes = state->ChanceOutcomes();
      auto [action, prob] = open_spiel::SampleAction(outcomes, *rng);
      if (verbose) {
        std::cout << "sampled outcome: "
                  << state->ActionToString(kChancePlayerId, action)
                  << " with prob " << prob
                  << std::endl;
      }
      history.emplace_back(state->Clone(), kChancePlayerId, action);
      state->ApplyAction(action);
      if (undo && (history.size() < 10 || IsPowerOfTwo(history.size()))) {
        TestUndo(state->Clone(), history);
      }
      num_moves++;
    } else if (state->CurrentPlayer() == open_spiel::kSimultaneousPlayerId) {
      std::vector<double> rewards = state->Rewards();
      std::vector<double> returns = state->Returns();
      SPIEL_CHECK_EQ(rewards.size(), game.NumPlayers());
      SPIEL_CHECK_EQ(returns.size(), game.NumPlayers());
      for (auto p = Player{0}; p < game.NumPlayers(); ++p) {
        episode_returns[p] += rewards[p];
      }
      if (verbose) {
        std::cout << "Rewards: " << absl::StrJoin(rewards, " ") << std::endl;
        std::cout << "Returns: " << absl::StrJoin(returns, " ") << std::endl;
        std::cout << "Sum Rewards: " << absl::StrJoin(episode_returns, " ")
                  << std::endl;
      }
      for (auto p = Player{0}; p < game.NumPlayers(); ++p) {
        SPIEL_CHECK_TRUE(Near(episode_returns[p], returns[p], kRewardEpsilon));
      }
      // Players choose simultaneously.
      std::vector<Action> joint_action;
      // Sample an action for each player
      for (auto p = Player{0}; p < game.NumPlayers(); p++) {
        std::vector<Action> actions = state->LegalActions(p);
        Action action = 0;
        if (!actions.empty()) {
          if (mask_test) LegalActionsMaskTest(game, *state, p, actions);
          std::uniform_int_distribution<int> dis(0, actions.size() - 1);
          action = actions[dis(*rng)];
        }
        joint_action.push_back(action);
        if (p == 0) {
          history.emplace_back(state->Clone(), kInvalidHistoryPlayer, action);
        } else {
          history.emplace_back(nullptr, kInvalidHistoryPlayer, action);
        }
        if (verbose) {
          std::cout << "player " << p << " chose "
                    << state->ActionToString(p, action) << std::endl;
        }
        CheckObservables(game, *state, observation.get());
      }
      ApplyActionTestClone(game, state.get(), joint_action);
      game_length++;
    } else if (state->CurrentPlayer() == open_spiel::kMeanFieldPlayerId) {
      auto support = state->DistributionSupport();
      state->UpdateDistribution(RandomDistribution(support.size(), rng));
    } else {
      std::vector<double> rewards = state->Rewards();
      std::vector<double> returns = state->Returns();
      SPIEL_CHECK_EQ(rewards.size(), game.NumPlayers());
      SPIEL_CHECK_EQ(returns.size(), game.NumPlayers());
      for (auto p = Player{0}; p < game.NumPlayers(); ++p) {
        episode_returns[p] += rewards[p];
      }
      if (verbose) {
        std::cout << "Rewards: " << absl::StrJoin(rewards, " ") << std::endl;
        std::cout << "Returns: " << absl::StrJoin(returns, " ") << std::endl;
        std::cout << "Sum Rewards: " << absl::StrJoin(episode_returns, " ")
                  << std::endl;
      }
      for (auto p = Player{0}; p < game.NumPlayers(); ++p) {
        SPIEL_CHECK_TRUE(Near(episode_returns[p], returns[p], kRewardEpsilon));
      }
      // Decision node.
      Player player = state->CurrentPlayer();
      CheckObservables(game, *state, observation.get());
      // Sample an action uniformly.
      std::vector<Action> actions = state->LegalActions();
      if (mask_test) LegalActionsMaskTest(game, *state, state->CurrentPlayer(),
                                          actions);
      if (state->IsTerminal())
        SPIEL_CHECK_TRUE(actions.empty());
      else
        SPIEL_CHECK_FALSE(actions.empty());
      std::uniform_int_distribution<int> dis(0, actions.size() - 1);
      Action action = actions[dis(*rng)];
      if (verbose) {
        std::cout << "chose action: " << action << " ("
                  << state->ActionToString(player, action) << ")" << std::endl;
      }
      history.emplace_back(state->Clone(), player, action);
      ApplyActionTestClone(game, state.get(), action);
      game_length++;
      num_moves++;
      if (undo && (history.size() < 10 || IsPowerOfTwo(history.size()))) {
        TestUndo(state->Clone(), history);
      }
    }
    if (verbose) {
      std::cout << "State: " << std::endl << state->ToString() << std::endl;
    }
  }
  state_checker_fn(*state);
  SPIEL_CHECK_LE(game_length, game.MaxGameLength());
  if (verbose) {
    std::cout << "Reached a terminal state!" << std::endl;
  }
  SPIEL_CHECK_EQ(state->CurrentPlayer(), kTerminalPlayerId);
  std::vector<double> rewards = state->Rewards();
  if (verbose) {
    std::cout << "Rewards: " << absl::StrJoin(rewards, " ") << std::endl;
  }
  history.emplace_back(state->Clone(), kTerminalPlayerId,
                       kInvalidHistoryAction);
  TestHistoryContainsActions(game, history);
  // Check the information state of the terminal, too. This is commonly needed,
  // for example, as a final observation in an RL environment.
  CheckObservables(game, *state, observation.get());
  // Check that the returns satisfy the constraints based on the game type.
  CheckReturnsSum(game, *state);
  // Now, check each individual return is within bounds.
  auto returns = state->Returns();
  SPIEL_CHECK_EQ(returns.size(), game.NumPlayers());
  for (Player player = 0; player < game.NumPlayers(); player++) {
    double final_return = returns[player];
    SPIEL_CHECK_FLOAT_EQ(final_return, state->PlayerReturn(player));
    SPIEL_CHECK_GE(final_return, game.MinUtility());
    SPIEL_CHECK_LE(final_return, game.MaxUtility());
    if (verbose) {
      std::cout << "Final return to player " << player << " is " << final_return
                << std::endl;
    }
    episode_returns[player] += rewards[player];
    SPIEL_CHECK_TRUE(Near(episode_returns[player], final_return));
  }
}
References action, CheckActionStringsAreUnique(), CheckLegalActionsAreSorted(), CheckObservables(), CheckReturnsSum(), open_spiel::kChancePlayerId, open_spiel::GameType::kMeanField, open_spiel::kMeanFieldPlayerId, open_spiel::kSimultaneousPlayerId, open_spiel::kTerminalPlayerId, open_spiel::Near(), player, RandomDistribution(), open_spiel::SampleAction(), SPIEL_CHECK_EQ, SPIEL_CHECK_FALSE, SPIEL_CHECK_FLOAT_EQ, SPIEL_CHECK_GE, SPIEL_CHECK_LE, SPIEL_CHECK_LT, SPIEL_CHECK_TRUE, state, absl::StrJoin(), TestHistoryContainsActions(), TestSerializeDeserialize(), and TestUndo().
Referenced by RandomSimTest(), RandomSimTestCustomObserver(), RandomSimTestNoSerialize(), and RandomSimTestWithUndo().
ResampleInfostateTest()
void open_spiel::testing::ResampleInfostateTest (const Game & game, int num_sims)
Definition at line 664 of file basic_tests.cc.
{
  std::mt19937 rng;
  UniformProbabilitySampler sampler;
  for (int i = 0; i < num_sims; ++i) {
    std::unique_ptr<State> state = game.NewInitialState();
    while (!state->IsTerminal()) {
      if (!state->IsChanceNode()) {
        for (int p = 0; p < state->NumPlayers(); ++p) {
          std::unique_ptr<State> other_state =
              state->ResampleFromInfostate(p, sampler);
          SPIEL_CHECK_EQ(state->InformationStateString(p),
                         other_state->InformationStateString(p));
          SPIEL_CHECK_EQ(state->InformationStateTensor(p),
                         other_state->InformationStateTensor(p));
          SPIEL_CHECK_EQ(state->CurrentPlayer(), other_state->CurrentPlayer());
        }
      }
      std::vector<Action> actions = state->LegalActions();
      std::uniform_int_distribution<int> dis(0, actions.size() - 1);
      Action action = actions[dis(rng)];
      state->ApplyAction(action);
    }
  }
}
References action, i, SPIEL_CHECK_EQ, and state.
Referenced by main().
TestEveryInfostateInPolicy()
void open_spiel::testing::TestEveryInfostateInPolicy (TabularPolicyGenerator policy_generator, const Game & game)
Definition at line 723 of file basic_tests.cc.
{
  TabularPolicy policy = policy_generator(game);
  std::vector<std::unique_ptr<State>> to_visit;
  to_visit.push_back(game.NewInitialState());
  while (!to_visit.empty()) {
    std::unique_ptr<State> state = std::move(to_visit.back());
    to_visit.pop_back();
    for (Action action : state->LegalActions()) {
      to_visit.push_back(state->Child(action));
    }
    if (!state->IsChanceNode() && !state->IsTerminal()) {
      SPIEL_CHECK_EQ(
          policy.GetStatePolicy(state->InformationStateString()).size(),
          state->LegalActions().size());
    }
  }
}
References action, SPIEL_CHECK_EQ, and state.
TestHistoryContainsActions()
void open_spiel::testing::TestHistoryContainsActions (const Game & game, const std::vector< HistoryItem > & history)
Definition at line 176 of file basic_tests.cc.
{
  std::vector<Action> actions = {};
  for (const auto& history_item : history) {
    if (history_item.state != nullptr) {
      SPIEL_CHECK_EQ(history_item.state->History(), actions);
    }
    actions.push_back(history_item.action);
  }
}
References SPIEL_CHECK_EQ.
Referenced by RandomSimulation().
TestPoliciesCanPlay() [1/2]
void open_spiel::testing::TestPoliciesCanPlay (const Policy & policy, const Game & game, int numSims)
Definition at line 707 of file basic_tests.cc.
{
  std::mt19937 rng(0);
  for (int i = 0; i < numSims; ++i) {
    std::unique_ptr<State> state = game.NewInitialState();
    while (!state->IsTerminal()) {
      ActionsAndProbs outcomes;
      if (state->IsChanceNode()) {
        outcomes = state->ChanceOutcomes();
      } else {
        outcomes = policy.GetStatePolicy(*state);
      }
      state->ApplyAction(open_spiel::SampleAction(outcomes, rng).first);
    }
  }
}
References first, i, open_spiel::SampleAction(), and state.
TestPoliciesCanPlay() [2/2]
void open_spiel::testing::TestPoliciesCanPlay (TabularPolicyGenerator policy_generator, const Game & game, int numSims)
Definition at line 689 of file basic_tests.cc.
{
  TabularPolicy policy = policy_generator(game);
  std::mt19937 rng(0);
  for (int i = 0; i < numSims; ++i) {
    std::unique_ptr<State> state = game.NewInitialState();
    while (!state->IsTerminal()) {
      ActionsAndProbs outcomes;
      if (state->IsChanceNode()) {
        outcomes = state->ChanceOutcomes();
      } else {
        outcomes = policy.GetStatePolicy(state->InformationStateString());
      }
      state->ApplyAction(open_spiel::SampleAction(outcomes, rng).first);
    }
  }
}
References first, i, open_spiel::SampleAction(), and state.
TestSerializeDeserialize()
void open_spiel::testing::TestSerializeDeserialize (const Game & game, const State * state)
Definition at line 168 of file basic_tests.cc.
{
  const std::string& ser_str = SerializeGameAndState(game, *state);
  std::pair<std::shared_ptr<const Game>, std::unique_ptr<State>>
      game_and_state = DeserializeGameAndState(ser_str);
  SPIEL_CHECK_EQ(game.ToString(), game_and_state.first->ToString());
  SPIEL_CHECK_EQ(state->ToString(), game_and_state.second->ToString());
}
References open_spiel::DeserializeGameAndState(), open_spiel::SerializeGameAndState(), SPIEL_CHECK_EQ, and state.
Referenced by RandomSimulation().
TestUndo()
void open_spiel::testing::TestUndo (std::unique_ptr< State > state, const std::vector< HistoryItem > & history)
Definition at line 155 of file basic_tests.cc.
{
  // TODO(author2): We can just check each UndoAction.
  for (auto prev = history.rbegin(); prev != history.rend(); ++prev) {
    state->UndoAction(prev->player, prev->action);
    SPIEL_CHECK_EQ(state->ToString(), prev->state->ToString());
    // We also check that UndoActions correctly updates history_.
    SPIEL_CHECK_EQ(state->History(), prev->state->History());
    // And correctly updates move_number_.
    SPIEL_CHECK_EQ(state->MoveNumber(), prev->state->MoveNumber());
  }
}
References SPIEL_CHECK_EQ, and state.
Referenced by RandomSimulation().
Variable Documentation
kDefaultNumSimsForPolicyTests
int open_spiel::testing::kDefaultNumSimsForPolicyTests = 10 constexpr
Definition at line 28 of file basic_tests.h.