open spiel: open_spiel::dark_chess Namespace Reference
open_spiel::dark_chess Namespace Reference
Classes
class DarkChessGame
class DarkChessObserver
class DarkChessState
Functions
constexpr int NumPlayers ()
constexpr double LossUtility ()
constexpr double DrawUtility ()
constexpr double WinUtility ()
constexpr int NumDistinctActions ()
constexpr int MaxGameLength ()
Function Documentation
DrawUtility()
double open_spiel::dark_chess::DrawUtility () inline constexpr
Definition at line 48 of file dark_chess.h.
{ return 0; }
Referenced by open_spiel::dark_chess::DarkChessGame::UtilitySum().
LossUtility()
double open_spiel::dark_chess::LossUtility () inline constexpr
Definition at line 47 of file dark_chess.h.
{ return -1; }
Referenced by open_spiel::dark_chess::DarkChessGame::MinUtility().
MaxGameLength()
int open_spiel::dark_chess::MaxGameLength () inline constexpr
Definition at line 55 of file dark_chess.h.
{ return 17695; }
NumDistinctActions()
int open_spiel::dark_chess::NumDistinctActions () inline constexpr
Definition at line 52 of file dark_chess.h.
{ return 4672; }
NumPlayers()
int open_spiel::dark_chess::NumPlayers () inline constexpr
Definition at line 46 of file dark_chess.h.
{ return 2; }
WinUtility()
double open_spiel::dark_chess::WinUtility () inline constexpr
Definition at line 49 of file dark_chess.h.
{ return 1; }
Referenced by open_spiel::dark_chess::DarkChessGame::MaxUtility().