open spiel: main Namespace Reference
main Namespace Reference
Functions
selfplay_main (argv)
None main (Sequence[str] argv)
Variables
FLAGS = flags.FLAGS
Detailed Description
Main file to train and evaluate meta-regret and regret matching agents.
Main file to train and evaluate meta-cfr agent, cfr and cfr-plus.
Function Documentation
main()
None main.main (Sequence[str] argv)
Definition at line 35 of file main.py.
def main(argv: Sequence[str]) -> None:
  del argv
  config = {"players": FLAGS.players}
  random_seeds_eval = np.random.choice(
      np.array(list(range(1000))), size=FLAGS.random_seed_size, replace=False)
  # Train a meta-cfr agent
  meta_cfr_agent = meta_learning.MetaCFRRegretAgent(
      training_epochs=1,
      meta_learner_training_epochs=FLAGS.meta_learner_training_epochs,
      game_name=FLAGS.game,
      game_config=config,
      perturbation=FLAGS.perturbation,
      seed=FLAGS.random_seed,
      model_type=FLAGS.model_type,
      best_response=True)
  meta_cfr_agent.train()
  cfr_vals = np.zeros((FLAGS.meta_learner_training_epochs,))
  cfr_plus_vals = np.zeros((FLAGS.meta_learner_training_epochs,))
  for seed in list(random_seeds_eval):
    # Evaluate a meta-cfr agent
    world_state = openspiel_api.WorldState(
        FLAGS.game, config, perturbation=True, random_seed=seed)
    meta_cfr_vals = evaluation.CFRBREvaluation(meta_cfr_agent, world_state)
    # Evaluate a cfr plus agent
    game_tree = game_tree_utils.build_game_tree(
        openspiel_api.WorldState(
            FLAGS.game,
            config,
            perturbation=FLAGS.perturbation,
            random_seed=seed))
    _, cfr_plus_vals = cfr.compute_cfr_plus_values(
        game_tree, FLAGS.meta_learner_training_epochs)
    # Evaluate a cfr agent
    game_tree = game_tree_utils.build_game_tree(
        openspiel_api.WorldState(
            FLAGS.game,
            config,
            perturbation=FLAGS.perturbation,
            random_seed=seed))
    _, cfr_vals = cfr.compute_cfr_values(
        game_tree, FLAGS.meta_learner_training_epochs)
  print("Evaluation seed:", random_seeds_eval)
  print("Meta_cfr agent:", meta_cfr_vals)
  print("cfr_plus agent:", cfr_plus_vals)
  print("cfr agent:", cfr_vals)
References game_tree_utils.build_game_tree(), evaluation.CFRBREvaluation(), cfr.compute_cfr_plus_values(), and cfr.compute_cfr_values().
selfplay_main()
main.selfplay_main (argv)
Self play.
Definition at line 44 of file main.py.
def selfplay_main(argv):
  """Self play."""
  del argv
  np.random.seed(FLAGS.seed)
  # rock-paper-scissor
  base_matrix = np.array([[[0, -1, 1], [1, 0, -1], [-1, 1, 0]]] *
                         FLAGS.batch_size)
  dataset = matrix_dataset.Dataset(
      base_matrix=base_matrix,
      num_training_batches=FLAGS.num_batches,
      minval=FLAGS.min_val,
      maxval=FLAGS.max_val)
  data_loader = dataset.get_training_batch()
  eval_payoff_batch = dataset.get_eval_batch()
  mr_agent = meta_selfplay_agent.MetaSelfplayAgent(
      repeats=FLAGS.repeats,
      training_epochs=FLAGS.evaluation_steps,
      data_loader=data_loader)
  mr_agent.train()
  mr_agent2 = meta_selfplay_agent.MetaSelfplayAgent(
      repeats=FLAGS.repeats,
      training_epochs=FLAGS.evaluation_steps,
      data_loader=data_loader)
  mr_agent2.train()
  rm_agent = regret_matching_agent.RegretMatchingAgent(
      num_actions=FLAGS.num_actions, data_loader=data_loader)
  rm_agent.train()
  rm_agent2 = regret_matching_agent.RegretMatchingAgent(
      num_actions=FLAGS.num_actions, data_loader=data_loader)
  rm_agent2.train()
  print("Regret matching")
  evaluation.evaluate_in_selfplay(
      agent_x=rm_agent,
      agent_y=rm_agent2,
      payoff_batch=eval_payoff_batch,
      steps_count=FLAGS.evaluation_steps)
  print("Meta regret matching")
  evaluation.evaluate_in_selfplay(
      agent_x=mr_agent,
      agent_y=mr_agent2,
      payoff_batch=eval_payoff_batch,
      steps_count=FLAGS.evaluation_steps)
References evaluation.evaluate_in_selfplay().
Variable Documentation
FLAGS
main.FLAGS = flags.FLAGS
Definition at line 27 of file main.py.