open spiel: open_spiel.python.mfg.algorithms.bandit_regret Namespace Reference
open_spiel.python.mfg.algorithms.bandit_regret Namespace Reference
Classes
class Hedge
class PolynomialWeightAlgorithm
class RegretMinimizer
Functions
get_proba_constraints_positivity (nus)
get_proba_constraint_sum_eq (nus)
compress_internal_weights (nus, regrets)
compress_external_weights (nus, regrets, lbd=0.0)
power_method (w_nus)
polynomial_weight_update (weights, rewards, eta)
Detailed Description
Mean-Field Bandit Regret Minimizers from Muller et al.
Function Documentation
compress_external_weights()
open_spiel.python.mfg.algorithms.bandit_regret.compress_external_weights (nus, regrets, lbd = 0.0)
Compress internal weights.
Via optimization, identify which regret timesteps are useful and which aren't
for external regret.
Args:
  nus: Distribution per timestep.
  regrets: Regret value per timestep and action.
  lbd: Sparsity penalty.
Returns:
  Weights over nus which can be used to average the no-regret distribution.
Definition at line 86 of file bandit_regret.py.
def compress_external_weights(nus, regrets, lbd=0.0):
  """Compress internal weights.
  Via optimization, identify which regret timesteps are useful and which aren't
  for external regret.
  Args:
    nus: Distribution per timestep.
    regrets: Regret value per timestep and action.
    lbd: Sparsity penalty.
  Returns:
    Weights over nus which can be used to average the no-regret distribution.
  """
  def get_c(nus):
    return np.concatenate((np.array([1.0]), np.zeros(nus.shape[0])))
  def get_max_constraints(nus, regrets, lbd):
    A = np.zeros((regrets.shape[1], 1 + nus.shape[0]))
    A[:, 0] = -1.0
    A[:, 1:] = np.transpose(
        regrets
        - np.sum(regrets * nus, axis=1).reshape(-1, 1)
        - lbd * np.abs(regrets)
    )
    return A, np.zeros(A.shape[0])
  def get_a_ub(nus, regrets, lbd):
    Amax, bmax = get_max_constraints(nus, regrets, lbd)
    Apos, bpos = get_proba_constraints_positivity(nus)
    return np.concatenate((Amax, Apos), axis=0), np.concatenate(
        (bmax, bpos), axis=0
    )
  c = get_c(nus)
  A_ub, b_ub = get_a_ub(nus, regrets, lbd)
  A_eq, b_eq = get_proba_constraint_sum_eq(nus)
  res = scipy.optimize.linprog(
      c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, options={"tol": 1e-10}
  )
  new_weights = res.x
  return new_weights[1:]
# Faster than using scipy.linalg.eig.
References open_spiel.python.mfg.algorithms.bandit_regret.get_proba_constraint_sum_eq(), and open_spiel.python.mfg.algorithms.bandit_regret.get_proba_constraints_positivity().
Referenced by open_spiel.python.mfg.algorithms.bandit_regret.PolynomialWeightAlgorithm.get_post_compression_regret_and_weights().
compress_internal_weights()
open_spiel.python.mfg.algorithms.bandit_regret.compress_internal_weights (nus, regrets)
Compress internal weights.
Via optimization, identify which regret timesteps are useful and which aren't
for internal regret.
Args:
  nus: Distribution per timestep.
  regrets: Regret value per timestep and action.
Returns:
  Weights over nus which can be used to average the no-regret distribution.
Definition at line 40 of file bandit_regret.py.
def compress_internal_weights(nus, regrets):
  """Compress internal weights.
  Via optimization, identify which regret timesteps are useful and which aren't
  for internal regret.
  Args:
    nus: Distribution per timestep.
    regrets: Regret value per timestep and action.
  Returns:
    Weights over nus which can be used to average the no-regret distribution.
  """
  def get_c(nus):
    return np.concatenate((np.array([1.0]), np.zeros(nus.shape[0])))
  def get_max_constraint(regrets):
    regrets = np.transpose(np.array(regrets), axes=[0, 2, 1])
    regrets = regrets.reshape(-1, regrets.shape[-1])
    A = np.zeros((regrets.shape[0], 1 + regrets.shape[1]))
    A[:, 1:] = regrets
    A[:, 0] = -1.0
    b = np.zeros(A.shape[0])
    return A, b
  def get_a_ub(nus, regrets):
    Amax, bmax = get_max_constraint(regrets)
    Apos, bpos = get_proba_constraints_positivity(nus)
    return np.concatenate((Amax, Apos), axis=0), np.concatenate(
        (bmax, bpos), axis=0
    )
  c = get_c(nus)
  A_ub, b_ub = get_a_ub(nus, regrets)
  A_eq, b_eq = get_proba_constraint_sum_eq(nus)
  res = scipy.optimize.linprog(
      c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, options={"tol": 1e-10}
  )
  new_weights = res.x
  return new_weights[1:]
References open_spiel.python.mfg.algorithms.bandit_regret.get_proba_constraint_sum_eq(), and open_spiel.python.mfg.algorithms.bandit_regret.get_proba_constraints_positivity().
Referenced by open_spiel.python.mfg.algorithms.bandit_regret.PolynomialWeightAlgorithm.get_post_compression_regret_and_weights().
get_proba_constraint_sum_eq()
open_spiel.python.mfg.algorithms.bandit_regret.get_proba_constraint_sum_eq (nus)
Definition at line 34 of file bandit_regret.py.
def get_proba_constraint_sum_eq(nus):
  A = np.ones((1, 1 + nus.shape[0]))
  A[0, 0] = 0.0
  return A, np.array([1.0])
Referenced by open_spiel.python.mfg.algorithms.bandit_regret.compress_external_weights(), and open_spiel.python.mfg.algorithms.bandit_regret.compress_internal_weights().
get_proba_constraints_positivity()
open_spiel.python.mfg.algorithms.bandit_regret.get_proba_constraints_positivity (nus)
Definition at line 28 of file bandit_regret.py.
def get_proba_constraints_positivity(nus):
  A = np.zeros((nus.shape[0], 1 + nus.shape[0]))
  A[:, 1:] = -np.eye(nus.shape[0])
  return A, np.zeros(A.shape[0])
Referenced by open_spiel.python.mfg.algorithms.bandit_regret.compress_external_weights(), and open_spiel.python.mfg.algorithms.bandit_regret.compress_internal_weights().
polynomial_weight_update()
open_spiel.python.mfg.algorithms.bandit_regret.polynomial_weight_update (weights, rewards, eta)
Definition at line 253 of file bandit_regret.py.
def polynomial_weight_update(weights, rewards, eta):
  return weights * (1 + eta * rewards)
power_method()
open_spiel.python.mfg.algorithms.bandit_regret.power_method (w_nus)
Quick implementation of the power method.
Args:
  w_nus:
Returns:
  Highest eigenvalue of the system.
Raises:
  ValueError: when the power method did not converge after 10.000 trials.
Definition at line 134 of file bandit_regret.py.
def power_method(w_nus):
  """Quick implementation of the power method.
  Args:
    w_nus:
  Returns:
    Highest eigenvalue of the system.
  Raises:
    ValueError: when the power method did not converge after 10.000 trials.
  """
  p = np.ones(len(w_nus))
  pprime = np.dot(p, w_nus)
  n_trials = 10000
  i = 0
  while np.sum(np.abs(pprime - p)) > 1e-8 and i < n_trials:
    p = pprime
    pprime = np.dot(p, w_nus)
    pprime[pprime < 0] = 0.0
    pprime /= np.sum(pprime)
    i += 1
  if np.sum(np.abs(pprime - p)) > 1e-8 and i >= n_trials:
    raise ValueError(
        "Power method did not converge after {} trials.".format(n_trials)
    )
  p[p < 0] = 0.0
  return p / np.sum(p)
References len.
Referenced by open_spiel.python.mfg.algorithms.bandit_regret.PolynomialWeightAlgorithm.compute_p().