open spiel: open_spiel::colored_trails Namespace Reference
open_spiel::colored_trails Namespace Reference
Classes
struct Board
class ChipComboIterator
class ColoredTrailsGame
class ColoredTrailsState
struct Trade
struct TradeInfo
Functions
bool CheckBoard (const Board &board)
bool CheckBoardForProposer (const Board &board, Player proposer)
char ColorToChar (int color)
int CharToColor (char c)
std::string ComboToString (const std::vector< int > &combo)
std::vector< int > ComboStringToCombo (const std::string &combo_str, int num_colors)
void InitTradeInfo (TradeInfo *trade_info, int num_colors)
std::pair< int, bool > Score (Player player, const Board &board)
void ParseBoardsFile (std::vector< Board > *boards, const std::string &filename, int num_colors, int board_size, int num_players)
void ParseBoardsString (std::vector< Board > *boards, const std::string &boards_string, int num_colors, int board_size, int num_players)
Variables
constexpr int kResponderId = 2
constexpr int kDefaultNumPlayers = 3
constexpr int kDefaultNumColors = 5
constexpr int kDefaultBoardSize = 4
constexpr int kNumChipsLowerBound = 3
constexpr int kNumChipsUpperBound = 8
constexpr int kLeftoverChipScore = 10
constexpr int kFlagPenaltyPerCell = -25
constexpr int kDefaultTradeDistanceUpperBound
constexpr int kBaseScoreEpsilon = 20
constexpr const char * kDefaultBoardsString
Function Documentation
CharToColor()
int open_spiel::colored_trails::CharToColor (char c)
Definition at line 145 of file colored_trails_utils.cc.
{ return static_cast<int>(c - 'A'); }
Referenced by ComboStringToCombo(), and open_spiel::colored_trails::Board::ParseFromLine().
CheckBoard()
bool open_spiel::colored_trails::CheckBoard (const Board & board)
Definition at line 776 of file colored_trails.cc.
{
  std::vector<int> base_scores(board.num_players);
  int min_score = board.size * 100;
  int max_score = board.size * -100;
  for (Player player = 0; player < board.num_players; ++player) {
    std::pair<int, bool> score_and_solved = Score(player, board);
    if (score_and_solved.second) {
      // Cannot be solvable without negotiation.
      return false;
    }
    base_scores[player] = score_and_solved.first;
    min_score = std::min(min_score, base_scores[player]);
    max_score = std::max(max_score, base_scores[player]);
  }
  if (max_score - min_score > kBaseScoreEpsilon) {
    return false;
  }
  // Now check that there exist two trades:
  // - one between player 0 and 2, such that both can reach the goal
  // - one between player 1 and 2, such that both can reach the goal
  for (int proposer : {0, 1}) {
    bool found_trade = false;
    ChipComboIterator iter1(board.chips[proposer]);
    while (!found_trade && !iter1.IsFinished()) {
      std::vector<int> combo1 = iter1.Next();
      ChipComboIterator iter2(board.chips[2]);
      while (!found_trade && !iter2.IsFinished()) {
        std::vector<int> combo2 = iter2.Next();
        // Do the trade and check if both can reach the goal.
        Board board_copy = board;
        Trade trade(combo1, combo2);
        board_copy.ApplyTrade({proposer, 2}, trade);
        std::pair<int, bool> prop_score_and_goal = Score(proposer, board_copy);
        if (prop_score_and_goal.second) {
          std::pair<int, bool> rec_score_and_goal = Score(2, board_copy);
          if (rec_score_and_goal.second) {
            found_trade = true;
          }
        }
      }
    }
    if (!found_trade) {
      return false;
    }
  }
  return true;
}
References open_spiel::colored_trails::Board::ApplyTrade(), open_spiel::colored_trails::Board::chips, open_spiel::colored_trails::ChipComboIterator::IsFinished(), kBaseScoreEpsilon, open_spiel::colored_trails::ChipComboIterator::Next(), open_spiel::colored_trails::Board::num_players, player, Score(), and open_spiel::colored_trails::Board::size.
CheckBoardForProposer()
bool open_spiel::colored_trails::CheckBoardForProposer (const Board & board, Player proposer)
Definition at line 828 of file colored_trails.cc.
{
  std::vector<int> base_scores(board.num_players);
  int min_score = board.size * 100;
  int max_score = board.size * -100;
  std::pair<int, bool> score_and_solved = Score(proposer, board);
  if (score_and_solved.second) {
    // Cannot be solvable without negotiation.
    return false;
  }
  base_scores[proposer] = score_and_solved.first;
  min_score = std::min(min_score, base_scores[proposer]);
  max_score = std::max(max_score, base_scores[proposer]);
  if (max_score - min_score > kBaseScoreEpsilon) {
    return false;
  }
  // Now check that there exist two trades:
  bool found_trade = false;
  ChipComboIterator iter1(board.chips[proposer]);
  while (!found_trade && !iter1.IsFinished()) {
    std::vector<int> combo1 = iter1.Next();
    ChipComboIterator iter2(board.chips[2]);
    while (!found_trade && !iter2.IsFinished()) {
      std::vector<int> combo2 = iter2.Next();
      // Do the trade and check if both can reach the goal.
      Board board_copy = board;
      Trade trade(combo1, combo2);
      board_copy.ApplyTrade({proposer, 2}, trade);
      std::pair<int, bool> prop_score_and_goal = Score(proposer, board_copy);
      if (prop_score_and_goal.second) {
        std::pair<int, bool> rec_score_and_goal = Score(2, board_copy);
        if (rec_score_and_goal.second) {
          found_trade = true;
        }
      }
    }
  }
  if (!found_trade) {
    return false;
  }
  return true;
}
References open_spiel::colored_trails::Board::ApplyTrade(), open_spiel::colored_trails::Board::chips, open_spiel::colored_trails::ChipComboIterator::IsFinished(), kBaseScoreEpsilon, open_spiel::colored_trails::ChipComboIterator::Next(), open_spiel::colored_trails::Board::num_players, Score(), and open_spiel::colored_trails::Board::size.
Referenced by open_spiel::colored_trails::ColoredTrailsGame::SampleRandomBoardCompletion().
ColorToChar()
char open_spiel::colored_trails::ColorToChar (int color)
Definition at line 143 of file colored_trails_utils.cc.
{ return static_cast<char>('A' + color); }
Referenced by ComboToString(), open_spiel::colored_trails::Board::PrettyBoardString(), and open_spiel::colored_trails::Board::ToString().
ComboStringToCombo()
std::vector< int > open_spiel::colored_trails::ComboStringToCombo (const std::string & combo_str, int num_colors)
Definition at line 123 of file colored_trails_utils.cc.
{
  std::vector<int> combo(num_colors, 0);
  for (int i = 0; i < combo_str.length(); ++i) {
    int color = CharToColor(combo_str[i]);
    combo[color]++;
  }
  return combo;
}
References CharToColor(), and i.
ComboToString()
std::string open_spiel::colored_trails::ComboToString (const std::vector< int > & combo)
Definition at line 133 of file colored_trails_utils.cc.
{
  std::string combo_str;
  for (int i = 0; i < combo.size(); ++i) {
    for (int k = 0; k < combo[i]; ++k) {
      combo_str.push_back(ColorToChar(i));
    }
  }
  return combo_str;
}
References ColorToChar(), and i.
Referenced by open_spiel::colored_trails::ColoredTrailsState::InformationStateString(), open_spiel::colored_trails::ColoredTrailsGame::SampleRandomBoardCompletion(), open_spiel::colored_trails::Board::ToString(), open_spiel::colored_trails::ColoredTrailsState::ToString(), and open_spiel::colored_trails::Trade::ToString().
InitTradeInfo()
void open_spiel::colored_trails::InitTradeInfo (TradeInfo * trade_info, int num_colors)
Definition at line 147 of file colored_trails_utils.cc.
{
  InitChipCombosRec(trade_info, num_colors, "");
  for (int i = 0; i < trade_info->chip_combinations.size(); ++i) {
    for (int j = 0; j < trade_info->chip_combinations.size(); ++j) {
      Trade candidate(trade_info->chip_combinations[i],
                      trade_info->chip_combinations[j]);
      bool valid = candidate.reduce();
      if (!valid) {
        continue;
      }
      std::string candidate_str = candidate.ToString();
      if (trade_info->trade_str_to_id.find(candidate_str) ==
          trade_info->trade_str_to_id.end()) {
        // std::cout << "Valid trade: " << candidate_str << std::endl;
        trade_info->possible_trades.push_back(
            std::make_unique<Trade>(candidate));
        trade_info->trade_str_to_id[candidate_str] =
            trade_info->possible_trades.size() - 1;
      }
    }
  }
}
References open_spiel::colored_trails::TradeInfo::chip_combinations, i, open_spiel::colored_trails::TradeInfo::possible_trades, open_spiel::colored_trails::Trade::reduce(), open_spiel::colored_trails::Trade::ToString(), and open_spiel::colored_trails::TradeInfo::trade_str_to_id.
Referenced by open_spiel::colored_trails::ColoredTrailsGame::ColoredTrailsGame().
ParseBoardsFile()
void open_spiel::colored_trails::ParseBoardsFile (std::vector< Board > * boards, const std::string & filename, int num_colors, int board_size, int num_players)
Definition at line 192 of file colored_trails_utils.cc.
{
  open_spiel::file::File infile(filename, "r");
  std::string contents = infile.ReadContents();
  ParseBoardsString(boards, contents, num_colors, board_size, num_players);
}
References ParseBoardsString(), and open_spiel::file::File::ReadContents().
Referenced by open_spiel::colored_trails::ColoredTrailsGame::ColoredTrailsGame().
ParseBoardsString()
void open_spiel::colored_trails::ParseBoardsString (std::vector< Board > * boards, const std::string & boards_string, int num_colors, int board_size, int num_players)
Definition at line 178 of file colored_trails_utils.cc.
{
  std::vector<std::string> lines = absl::StrSplit(boards_string, '\n');
  SPIEL_CHECK_GT(lines.size(), 1);
  for (const std::string& line : lines) {
    if (!line.empty()) {
      Board board(board_size, num_colors, num_players);
      board.ParseFromLine(line);
      boards->push_back(board);
    }
  }
}
References open_spiel::colored_trails::Board::ParseFromLine(), SPIEL_CHECK_GT, and absl::StrSplit().
Referenced by open_spiel::colored_trails::ColoredTrailsGame::ColoredTrailsGame(), and ParseBoardsFile().
Score()
std::pair< int, bool > open_spiel::colored_trails::Score (Player player, const Board & board)
Definition at line 172 of file colored_trails_utils.cc.
{
  bool solved = false;
  int score = ScoreRec(player, board, &solved);
  return std::make_pair(score, solved);
}
References player.
Referenced by CheckBoard(), CheckBoardForProposer(), and open_spiel::colored_trails::ColoredTrailsState::DoApplyAction().
Variable Documentation
kBaseScoreEpsilon
int open_spiel::colored_trails::kBaseScoreEpsilon = 20 constexpr
Definition at line 69 of file colored_trails.h.
Referenced by CheckBoard(), and CheckBoardForProposer().
kDefaultBoardSize
int open_spiel::colored_trails::kDefaultBoardSize = 4 constexpr
Definition at line 54 of file colored_trails.h.
kDefaultBoardsString
const char* open_spiel::colored_trails::kDefaultBoardsString constexpr
Initial value:
=
    "4 5 3 DEADCACCADBDBECC BCD BDDDD AAABCC 4 5 15 12\n"
    "4 5 3 CCADBEEAEDDDDACD ACCD AABC ABBCDDE 14 7 8 11\n"
    "4 5 3 ECBBDECECEECBDCE ABBEEE BCDE ACCCEE 3 10 13 0\n"
    "4 5 3 EBBEABDCAAAEDABD AAABE AAB BBDDDE 6 14 7 12\n"
    "4 5 3 BEBBAADEBBCABABD AACDE ACCDE BBBDDDE 5 1 15 9\n"
    "4 5 3 BACBBEAADBDCECAE ABCCCDD BCDDEE ACCCEEE 0 7 5 13\n"
    "4 5 3 EBCCDDBAEADEEDDE CCD ABDD ACEE 5 7 0 8\n"
    "4 5 3 BCDACCACBDCBDDDB BBCCCE AAABCCEE AAADD 1 12 8 10\n"
    "4 5 3 EEEAEBDBEDCEDBCE ABCCDE DDD BEEE 8 7 10 2\n"
    "4 5 3 EBBEEBEECBECDADB BBCCDDDD AACCDD BEEE 5 14 15 11\n"
Definition at line 76 of file colored_trails.h.
Referenced by open_spiel::colored_trails::ColoredTrailsGame::ColoredTrailsGame().
kDefaultNumColors
int open_spiel::colored_trails::kDefaultNumColors = 5 constexpr
Definition at line 53 of file colored_trails.h.
kDefaultNumPlayers
int open_spiel::colored_trails::kDefaultNumPlayers = 3 constexpr
Definition at line 52 of file colored_trails.h.
Referenced by open_spiel::colored_trails::ColoredTrailsGame::ColoredTrailsGame().
kDefaultTradeDistanceUpperBound
int open_spiel::colored_trails::kDefaultTradeDistanceUpperBound constexpr
Initial value:
=
    kDefaultNumColors * kNumChipsUpperBound
Definition at line 65 of file colored_trails.h.
Referenced by open_spiel::colored_trails::Trade::DistanceTo(), and open_spiel::colored_trails::ColoredTrailsState::SetChipsAndTradeProposal().
kFlagPenaltyPerCell
int open_spiel::colored_trails::kFlagPenaltyPerCell = -25 constexpr
Definition at line 62 of file colored_trails.h.
Referenced by open_spiel::colored_trails::ColoredTrailsGame::MinUtility().
kLeftoverChipScore
int open_spiel::colored_trails::kLeftoverChipScore = 10 constexpr
Definition at line 61 of file colored_trails.h.
Referenced by open_spiel::colored_trails::ColoredTrailsGame::MaxUtility().
kNumChipsLowerBound
int open_spiel::colored_trails::kNumChipsLowerBound = 3 constexpr
Definition at line 58 of file colored_trails.h.
kNumChipsUpperBound
int open_spiel::colored_trails::kNumChipsUpperBound = 8 constexpr
Definition at line 59 of file colored_trails.h.
Referenced by open_spiel::colored_trails::ColoredTrailsGame::MaxUtility().
kResponderId
int open_spiel::colored_trails::kResponderId = 2 constexpr
Definition at line 50 of file colored_trails.h.
Referenced by open_spiel::colored_trails::ColoredTrailsState::ActionToString(), open_spiel::colored_trails::ColoredTrailsState::DoApplyAction(), open_spiel::colored_trails::ColoredTrailsState::InformationStateString(), open_spiel::colored_trails::ColoredTrailsState::InformationStateTensor(), open_spiel::colored_trails::ColoredTrailsState::LegalActions(), open_spiel::colored_trails::ColoredTrailsGame::SampleRandomBoardCompletion(), and open_spiel::colored_trails::ColoredTrailsState::SetChipsAndTradeProposal().