open spiel: open_spiel::hex Namespace Reference
open_spiel::hex Namespace Reference
Classes
class HexGame
class HexState
Enumerations
enum class CellState {
kEmpty = 0 , kWhiteWest = -3 , kWhiteEast = -2 , kWhiteWin = -4 ,
kWhite = -1 , kBlackNorth = 3 , kBlackSouth = 2 , kBlackWin = 4 ,
kBlack = 1
}
Functions
CellState PlayerToState (Player player)
std::string StateToString (CellState state)
std::ostream & operator<< (std::ostream &stream, const CellState &state)
Variables
constexpr int kNumPlayers = 2
constexpr int kDefaultBoardSize = 11
constexpr int kMaxNeighbours
constexpr int kCellStates = 1 + 4 * kNumPlayers
constexpr int kMinValueCellState = -4
Enumeration Type Documentation
CellState
enum class open_spiel::hex::CellState strong
Enumerator
kEmpty
kWhiteWest
kWhiteEast
kWhiteWin
kWhite
kBlackNorth
kBlackSouth
kBlackWin
kBlack
Definition at line 53 of file hex.h.
                     {
  kEmpty = 0,
  kWhiteWest = -3,
  kWhiteEast = -2,
  kWhiteWin = -4,
  kWhite = -1,  // White and not edge connected
  kBlackNorth = 3,
  kBlackSouth = 2,
  kBlackWin = 4,
  kBlack = 1,  // Black and not edge connected
};
Function Documentation
operator<<()
std::ostream & open_spiel::hex::operator<< (std::ostream & stream, const CellState & state) inline
Definition at line 129 of file hex.h.
{
  return stream << StateToString(state);
}
References state, and StateToString().
PlayerToState()
CellState open_spiel::hex::PlayerToState (Player player)
Definition at line 59 of file hex.cc.
{
  switch (player) {
    case 0:
      return CellState::kBlack;
    case 1:
      return CellState::kWhite;
    default:
      SpielFatalError(absl::StrCat("Invalid player id ", player));
      return CellState::kEmpty;
  }
}
References kBlack, kEmpty, kWhite, player, open_spiel::SpielFatalError(), and absl::StrCat().
StateToString()
std::string open_spiel::hex::StateToString (CellState state)
Definition at line 136 of file hex.cc.
{
  switch (state) {
    case CellState::kEmpty:
      return ".";
    case CellState::kWhite:
      return "o";
    case CellState::kWhiteWin:
      return "O";
    case CellState::kWhiteWest:
      return "p";
    case CellState::kWhiteEast:
      return "q";
    case CellState::kBlack:
      return "x";
    case CellState::kBlackWin:
      return "X";
    case CellState::kBlackNorth:
      return "y";
    case CellState::kBlackSouth:
      return "z";
    default:
      SpielFatalError("Unknown state.");
      return "This will never return.";
  }
}
References kBlack, kBlackNorth, kBlackSouth, kBlackWin, kEmpty, kWhite, kWhiteEast, kWhiteWest, kWhiteWin, open_spiel::SpielFatalError(), and state.
Referenced by open_spiel::hex::HexState::ActionToString(), operator<<(), and open_spiel::hex::HexState::ToString().
Variable Documentation
kCellStates
int open_spiel::hex::kCellStates = 1 + 4 * kNumPlayers inline constexpr
Definition at line 42 of file hex.h.
Referenced by open_spiel::hex::HexState::ObservationTensor(), and open_spiel::hex::HexGame::ObservationTensorShape().
kDefaultBoardSize
int open_spiel::hex::kDefaultBoardSize = 11 inline constexpr
Definition at line 39 of file hex.h.
kMaxNeighbours
int open_spiel::hex::kMaxNeighbours inline constexpr
Initial value:
=
    6
Definition at line 40 of file hex.h.
kMinValueCellState
int open_spiel::hex::kMinValueCellState = -4 inline constexpr
Definition at line 43 of file hex.h.
kNumPlayers
int open_spiel::hex::kNumPlayers = 2 inline constexpr
Definition at line 38 of file hex.h.
Referenced by open_spiel::hex::HexGame::NumPlayers().