open spiel: open_spiel::file Namespace Reference
open_spiel::file Namespace Reference
Classes
class File
Functions
std::string ReadContentsFromFile (const std::string &filename, const std::string &mode)
void WriteContentsToFile (const std::string &filename, const std::string &mode, const std::string &contents)
bool Exists (const std::string &path)
bool IsDirectory (const std::string &path)
bool Mkdir (const std::string &path, int mode)
bool Mkdirs (const std::string &path, int mode)
bool Remove (const std::string &path)
std::string GetEnv (const std::string &key, const std::string &default_value)
std::string GetTmpDir ()
Function Documentation
Exists()
bool open_spiel::file::Exists (const std::string & path)
Definition at line 100 of file file.cc.
{
  struct stat info;
  return stat(path.c_str(), &info) == 0;
}
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), open_spiel::gamut::GamutGenerator::GenerateGame(), main(), and open_spiel::WriteAndLoadGame().
GetEnv()
std::string open_spiel::file::GetEnv (const std::string & key, const std::string & default_value)
Definition at line 142 of file file.cc.
{
  char* val = std::getenv(key.c_str());
  return ((val != nullptr) ? std::string(val) : default_value);
}
References key.
Referenced by GetTmpDir().
GetTmpDir()
std::string open_spiel::file::GetTmpDir ()
Definition at line 147 of file file.cc.
{ return GetEnv("TMPDIR", "/tmp"); }
References GetEnv().
Referenced by open_spiel::WriteAndLoadGame().
IsDirectory()
bool open_spiel::file::IsDirectory (const std::string & path)
Definition at line 105 of file file.cc.
{
  struct stat info;
  return stat(path.c_str(), &info) == 0 && info.st_mode & S_IFDIR;
}
Referenced by open_spiel::algorithms::torch_az::AlphaZero(), and Remove().
Mkdir()
bool open_spiel::file::Mkdir (const std::string & path, int mode)
Definition at line 110 of file file.cc.
{
  return mkdir(path.c_str(), mode) == 0;
}
Referenced by main(), and Mkdirs().
Mkdirs()
bool open_spiel::file::Mkdirs (const std::string & path, int mode)
Definition at line 114 of file file.cc.
{
  struct stat info;
  size_t pos = 0;
  while (pos != std::string::npos) {
    pos = path.find_first_of("\\/", pos + 1);
    std::string sub_path = path.substr(0, pos);
    if (stat(sub_path.c_str(), &info) == 0) {
      if (info.st_mode & S_IFDIR) {
        continue;  // directory already exists
      } else {
        return false;  // is a file?
      }
    }
    if (!Mkdir(sub_path, mode)) {
      return false;  // permission error?
    }
  }
  return true;
}
References Mkdir().
Referenced by open_spiel::algorithms::torch_az::AlphaZero().
ReadContentsFromFile()
std::string open_spiel::file::ReadContentsFromFile (const std::string & filename, const std::string & mode)
Definition at line 88 of file file.cc.
{
  File f(filename, mode);
  return f.ReadContents();
}
Referenced by open_spiel::init_pyspiel_utils().
Remove()
bool open_spiel::file::Remove (const std::string & path)
Definition at line 134 of file file.cc.
{
  if (IsDirectory(path)) {
    return rmdir(path.c_str()) == 0;
  } else {
    return unlink(path.c_str()) == 0;
  }
}
References IsDirectory().
Referenced by open_spiel::gamut::GamutGenerator::GenerateGame(), and open_spiel::WriteAndLoadGame().
WriteContentsToFile()
void open_spiel::file::WriteContentsToFile (const std::string & filename, const std::string & mode, const std::string & contents)
Definition at line 94 of file file.cc.
{
  File f(filename, mode);
  f.Write(contents);
}
Referenced by open_spiel::init_pyspiel_utils().