open spiel: open_spiel::nine_mens_morris Namespace Reference
open_spiel::nine_mens_morris Namespace Reference
Classes
class NineMensMorrisGame
class NineMensMorrisState
Typedefs
using Mill = std::array<int, 3>
Enumerations
enum class CellState { kEmpty , kWhite , kBlack }
Functions
CellState PlayerToState (Player player)
const char * PlayerToStr (Player player)
char StateToChar (CellState state)
Player StateToPlayer (CellState state)
Action ToMoveAction (int source, int dest)
void FromMoveAction (Action action, int *source, int *dest)
Variables
constexpr int kNumPlayers = 2
constexpr int kNumMen = 9
constexpr int kNumPoints = 24
constexpr int kCellStates = 1 + kNumPlayers
constexpr int kMaxNumTurns = 200
constexpr int kObservationSize = 7
Typedef Documentation
Mill
using open_spiel::nine_mens_morris::Mill = std::array<int, 3>
Definition at line 49 of file nine_mens_morris.h.
Enumeration Type Documentation
CellState
enum class open_spiel::nine_mens_morris::CellState strong
Enumerator
kEmpty
kWhite
kBlack
Definition at line 43 of file nine_mens_morris.h.
                     {
  kEmpty,
  kWhite,  // W
  kBlack,  // B
};
Function Documentation
FromMoveAction()
void open_spiel::nine_mens_morris::FromMoveAction (Action action, int * source, int * dest)
Definition at line 163 of file nine_mens_morris.cc.
{
  action -= kNumPoints;
  *source = action / kNumPoints;
  *dest = action % kNumPoints;
}
References action, and kNumPoints.
Referenced by open_spiel::nine_mens_morris::NineMensMorrisGame::ActionToString(), and open_spiel::nine_mens_morris::NineMensMorrisState::DoApplyAction().
PlayerToState()
CellState open_spiel::nine_mens_morris::PlayerToState (Player player)
Definition at line 109 of file nine_mens_morris.cc.
{
  switch (player) {
    case 0:
      return CellState::kWhite;
    case 1:
      return CellState::kBlack;
    default:
      SpielFatalError(absl::StrCat("Invalid player id ", player));
      return CellState::kEmpty;
  }
}
References kBlack, kEmpty, kWhite, player, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::nine_mens_morris::NineMensMorrisState::DoApplyAction().
PlayerToStr()
const char * open_spiel::nine_mens_morris::PlayerToStr (Player player)
Definition at line 121 of file nine_mens_morris.cc.
{
  switch (player) {
    case 0:
      return "W";
    case 1:
      return "B";
    default:
      SpielFatalError(absl::StrCat("Invalid player id ", player));
      return "";
  }
}
References player, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::nine_mens_morris::NineMensMorrisState::ToString().
StateToChar()
char open_spiel::nine_mens_morris::StateToChar (CellState state)
Definition at line 133 of file nine_mens_morris.cc.
{
  switch (state) {
    case CellState::kEmpty:
      return '.';
    case CellState::kWhite:
      return 'W';
    case CellState::kBlack:
      return 'B';
    default:
      SpielFatalError("Unknown state.");
  }
}
References kBlack, kEmpty, kWhite, open_spiel::SpielFatalError(), and state.
Referenced by open_spiel::nine_mens_morris::NineMensMorrisState::ToString().
StateToPlayer()
Player open_spiel::nine_mens_morris::StateToPlayer (CellState state)
Definition at line 146 of file nine_mens_morris.cc.
{
  switch (state) {
    case CellState::kEmpty:
      return kInvalidPlayer;
    case CellState::kWhite:
      return 0;
    case CellState::kBlack:
      return 1;
    default:
      SpielFatalError("Unknown state.");
  }
}
References kBlack, kEmpty, open_spiel::kInvalidPlayer, kWhite, open_spiel::SpielFatalError(), and state.
Referenced by open_spiel::nine_mens_morris::NineMensMorrisState::DoApplyAction().
ToMoveAction()
Action open_spiel::nine_mens_morris::ToMoveAction (int source, int dest)
Definition at line 159 of file nine_mens_morris.cc.
{
  return kNumPoints + (source * kNumPoints + dest);
}
References kNumPoints.
Variable Documentation
kCellStates
int open_spiel::nine_mens_morris::kCellStates = 1 + kNumPlayers inline constexpr
Definition at line 38 of file nine_mens_morris.h.
kMaxNumTurns
int open_spiel::nine_mens_morris::kMaxNumTurns = 200 inline constexpr
Definition at line 39 of file nine_mens_morris.h.
Referenced by open_spiel::nine_mens_morris::NineMensMorrisState::IsTerminal(), and open_spiel::nine_mens_morris::NineMensMorrisGame::MaxGameLength().
kNumMen
int open_spiel::nine_mens_morris::kNumMen = 9 inline constexpr
Definition at line 36 of file nine_mens_morris.h.
Referenced by open_spiel::nine_mens_morris::NineMensMorrisGame::MaxGameLength().
kNumPlayers
int open_spiel::nine_mens_morris::kNumPlayers = 2 inline constexpr
Definition at line 35 of file nine_mens_morris.h.
Referenced by open_spiel::nine_mens_morris::NineMensMorrisGame::NumPlayers().
kNumPoints
int open_spiel::nine_mens_morris::kNumPoints = 24 inline constexpr
Definition at line 37 of file nine_mens_morris.h.
Referenced by open_spiel::nine_mens_morris::NineMensMorrisGame::ActionToString(), open_spiel::nine_mens_morris::NineMensMorrisState::DoApplyAction(), FromMoveAction(), open_spiel::nine_mens_morris::NineMensMorrisGame::NumDistinctActions(), ToMoveAction(), and open_spiel::nine_mens_morris::NineMensMorrisState::ToString().
kObservationSize
int open_spiel::nine_mens_morris::kObservationSize = 7 inline constexpr
Definition at line 40 of file nine_mens_morris.h.
Referenced by open_spiel::nine_mens_morris::NineMensMorrisState::ObservationTensor(), and open_spiel::nine_mens_morris::NineMensMorrisGame::ObservationTensorShape().