open spiel: open_spiel.python.algorithms.efr Namespace Reference
open_spiel.python.algorithms.efr Namespace Reference
Classes
class _EFRSolver
class _EFRSolverBase
class _InfoStateNode
class EFRSolver
class LocalDeviationWithTimeSelection
class LocalSwapTransform
Functions
_update_average_policy (average_policy, info_state_nodes)
strat_dict_to_array (strategy_dictionary)
array_to_strat_dict (strategy_array, legal_actions)
create_probs_from_index (indices, current_policy)
return_blind_action (num_actions, history, _)
return_informed_action (num_actions, history, _)
return_blind_cf (num_actions, history, _)
return_informed_cf (num_actions, history, _)
return_blind_partial_sequence (num_actions, history, _)
return_cf_partial_sequence (num_actions, history, _)
return_cs_partial_sequence (num_actions, history, prior_legal_actions)
return_cs_partial_sequence_orginal (num_actions, history, prior_legal_actions)
return_twice_informed_partial_sequence (num_actions, history, prior_legal_actions)
generate_all_action_permutations (current_stem, remaining_actions)
return_behavourial (num_actions, history, prior_legal_actions)
return_all_non_identity_internal_deviations (num_actions, possible_prior_weights, prior_memory_actions)
return_all_internal_modified_deviations (num_actions, possible_prior_weights, possible_prior_memory_actions, prior_memory_actions)
return_all_external_deviations (num_actions, possible_prior_weights, prior_memory_actions)
return_all_external_modified_deviations (num_actions, possible_prior_weights, possible_prior_memory_actions, prior_memory_actions)
return_identity_deviation (num_actions, possible_prior_weights, prior_memory_actions)
Detailed Description
Python implementation of the extensive-form regret minimization algorithm.
See: "Efficient Deviation Types and Learning
      for Hindsight Rationality in Extensive-Form Games",
      Morrill et al. 2021b,
      https://arxiv.org/abs/2102.06973
One iteration of EFR consists of:
1) Compute current strategy from regrets (e.g. using Regret Matching).
2) Compute values using the current strategy
3) Compute regrets from these values
The average policy converges to a Nash Equilibrium
rather than the current policy.
Function Documentation
_update_average_policy()
open_spiel.python.algorithms.efr._update_average_policy (average_policy, info_state_nodes) protected
Updates in place `average_policy` to the average of all policies iterated.
This function is a module level function to be reused by both CFRSolver and
CFRBRSolver.
Args:
  average_policy: A `policy.TabularPolicy` to be updated in-place.
  info_state_nodes: A dictionary {`info_state_str` -> `_InfoStateNode`}.
Definition at line 567 of file efr.py.
def _update_average_policy(average_policy, info_state_nodes):
  """Updates in place `average_policy` to the average of all policies iterated.
  This function is a module level function to be reused by both CFRSolver and
  CFRBRSolver.
  Args:
    average_policy: A `policy.TabularPolicy` to be updated in-place.
    info_state_nodes: A dictionary {`info_state_str` -> `_InfoStateNode`}.
  """
  for info_state, info_state_node in info_state_nodes.items():
    info_state_policies_sum = info_state_node.cumulative_policy
    state_policy = average_policy.policy_for_key(info_state)
    probabilities_sum = sum(info_state_policies_sum.values())
    if probabilities_sum == 0:
      num_actions = len(info_state_node.legal_actions)
      for action in info_state_node.legal_actions:
        state_policy[action] = 1 / num_actions
    else:
      for action, action_prob_sum in info_state_policies_sum.items():
        state_policy[action] = action_prob_sum / probabilities_sum
References len.
Referenced by open_spiel.python.algorithms.efr._EFRSolverBase.average_policy().
array_to_strat_dict()
open_spiel.python.algorithms.efr.array_to_strat_dict (strategy_array, legal_actions)
A helper function to convert a strategy.
Converts a strategy array to an action -> prob value dictionary.
Args:
  strategy_array: an array with the ith action's value at the i-1th index.
  legal_actions: the list of all legal actions at the current state.
Returns:
  strategy_dictionary: a dictionary action -> prob value.
Definition at line 608 of file efr.py.
def array_to_strat_dict(strategy_array, legal_actions):
  """A helper function to convert a strategy.
  Converts a strategy array to an action -> prob value dictionary.
  Args:
    strategy_array: an array with the ith action's value at the i-1th index.
    legal_actions: the list of all legal actions at the current state.
  Returns:
    strategy_dictionary: a dictionary action -> prob value.
  """
  strategy_dictionary = {}
  for action in legal_actions:
    strategy_dictionary[action] = strategy_array[action]
  return strategy_dictionary
Referenced by open_spiel.python.algorithms.efr.create_probs_from_index().
create_probs_from_index()
open_spiel.python.algorithms.efr.create_probs_from_index (indices, current_policy)
Definition at line 626 of file efr.py.
def create_probs_from_index(indices, current_policy):
  path_to_state = []
  if indices is None or not indices:
    return []
  for index in indices:
    strat_dict = array_to_strat_dict(
        current_policy.action_probability_array[index[1]], index[0]
    )
    path_to_state.append(strat_dict)
  return path_to_state
# Deviation set definitions
References open_spiel.python.algorithms.efr.array_to_strat_dict().
Referenced by open_spiel.python.algorithms.efr._EFRSolverBase._compute_cumulative_immediate_regret_for_player(), and open_spiel.python.algorithms.efr._EFRSolverBase._update_current_policy().
generate_all_action_permutations()
open_spiel.python.algorithms.efr.generate_all_action_permutations (current_stem, remaining_actions)
Return a List of all possible game continuations.
Return a List of all possible game continuations playing on from the
current stem and with playing from the set of remaining actions.
`current_stem` = "" generates all possible playthroughs from the current
information state.
Args:
   current_stem: the prior sequence of actions to be completed by the
     remaining actions
   remaining_actions: a 2d array of [subsequent states]x[possible actions]
Returns:
   An array with each element being the current stem joined with a possible
   permuation of remaining actions
Definition at line 909 of file efr.py.
def generate_all_action_permutations(current_stem, remaining_actions):
  """Return a List of all possible game continuations.
  Return a List of all possible game continuations playing on from the
  current stem and with playing from the set of remaining actions.
  `current_stem` = "" generates all possible playthroughs from the current
  information state.
  Args:
     current_stem: the prior sequence of actions to be completed by the
       remaining actions
     remaining_actions: a 2d array of [subsequent states]x[possible actions]
  Returns:
     An array with each element being the current stem joined with a possible
     permuation of remaining actions
  """
  if not remaining_actions:
    return [np.array(current_stem)]
  else:
    next_actions = remaining_actions[0]
    permutations = []
    for action in next_actions:
      next_stem = current_stem.copy()
      next_stem.append(action)
      next_remaining_actions = remaining_actions[1:]
      prev_permutations = generate_all_action_permutations(
          next_stem, next_remaining_actions
      )
      for i in prev_permutations:
        permutations.append(i)
    return permutations
References open_spiel.python.algorithms.efr.generate_all_action_permutations().
Referenced by open_spiel.python.algorithms.efr.generate_all_action_permutations(), and open_spiel.python.algorithms.efr.return_behavourial().
return_all_external_deviations()
open_spiel.python.algorithms.efr.return_all_external_deviations (num_actions, possible_prior_weights, prior_memory_actions)
Returns all external deviations.
Definition at line 1205 of file efr.py.
):
  """Returns all external deviations."""
  deviations = []
  for prior_actions_weight in possible_prior_weights:
    for target in range(num_actions):
      deviations.append(
          LocalDeviationWithTimeSelection(
              target,
              target,
              num_actions,
              prior_actions_weight,
              prior_memory_actions,
              True,
          )
      )
  return deviations
# Modify last action as required
Referenced by open_spiel.python.algorithms.efr.return_blind_action(), open_spiel.python.algorithms.efr.return_blind_cf(), and open_spiel.python.algorithms.efr.return_blind_partial_sequence().
return_all_external_modified_deviations()
open_spiel.python.algorithms.efr.return_all_external_modified_deviations (num_actions, possible_prior_weights, possible_prior_memory_actions, prior_memory_actions)
Returns all external deviations with modified memory actions.
Definition at line 1226 of file efr.py.
):
  """Returns all external deviations with modified memory actions."""
  deviations = []
  for prior_actions_weight in possible_prior_weights:
    try:
      modification_index = np.where(prior_actions_weight == 0)[0][0]
    except IndexError:
      modification_index = 0
    if modification_index == len(prior_memory_actions):
      for target in range(num_actions):
        deviations.append(
            LocalDeviationWithTimeSelection(
                target,
                target,
                num_actions,
                prior_actions_weight,
                prior_memory_actions,
                True,
            )
        )
    else:
      previous_action = prior_memory_actions[modification_index]
      for alt_action in possible_prior_memory_actions[modification_index]:
        prior_memory_actions[modification_index] = alt_action
        for target in range(num_actions):
          deviations.append(
              LocalDeviationWithTimeSelection(
                  target,
                  target,
                  num_actions,
                  prior_actions_weight,
                  prior_memory_actions.copy(),
                  True,
              )
          )
        prior_memory_actions[modification_index] = previous_action
  return deviations
References len.
Referenced by open_spiel.python.algorithms.efr.return_cs_partial_sequence(), and open_spiel.python.algorithms.efr.return_cs_partial_sequence_orginal().
return_all_internal_modified_deviations()
open_spiel.python.algorithms.efr.return_all_internal_modified_deviations (num_actions, possible_prior_weights, possible_prior_memory_actions, prior_memory_actions)
Returns all internal deviations with modified memory actions.
Definition at line 1157 of file efr.py.
):
  """Returns all internal deviations with modified memory actions."""
  deviations = []
  for prior_actions_weight in possible_prior_weights:
    try:
      modification_index = np.where(prior_actions_weight == 0)[0][0]
    except IndexError:
      modification_index = 0
    if modification_index == len(prior_memory_actions):
      for target in range(num_actions):
        for source in range(num_actions):
          if source != target:
            deviations.append(
                LocalDeviationWithTimeSelection(
                    target,
                    source,
                    num_actions,
                    prior_actions_weight,
                    prior_memory_actions,
                    False,
                )
            )
    else:
      previous_action = prior_memory_actions[modification_index]
      for alt_action in possible_prior_memory_actions[modification_index]:
        prior_memory_actions[modification_index] = alt_action
        for target in range(num_actions):
          for source in range(num_actions):
            if source != target:
              deviations.append(
                  LocalDeviationWithTimeSelection(
                      target,
                      source,
                      num_actions,
                      prior_actions_weight,
                      prior_memory_actions.copy(),
                      False,
                  )
              )
        prior_memory_actions[modification_index] = previous_action
  return deviations
References len.
Referenced by open_spiel.python.algorithms.efr.return_twice_informed_partial_sequence().
return_all_non_identity_internal_deviations()
open_spiel.python.algorithms.efr.return_all_non_identity_internal_deviations (num_actions, possible_prior_weights, prior_memory_actions)
Returns all non-identity internal deviations.
Definition at line 1135 of file efr.py.
):
  """Returns all non-identity internal deviations."""
  deviations = []
  for prior_actions_weight in possible_prior_weights:
    for target in range(num_actions):
      for source in range(num_actions):
        if source != target:
          deviations.append(
              LocalDeviationWithTimeSelection(
                  target,
                  source,
                  num_actions,
                  prior_actions_weight,
                  prior_memory_actions,
                  False,
              )
          )
  return deviations
Referenced by open_spiel.python.algorithms.efr.return_behavourial(), open_spiel.python.algorithms.efr.return_cf_partial_sequence(), open_spiel.python.algorithms.efr.return_informed_action(), and open_spiel.python.algorithms.efr.return_informed_cf().
return_behavourial()
open_spiel.python.algorithms.efr.return_behavourial (num_actions, history, prior_legal_actions)
Returns an array of all single target behavioural deviations.
The target behavioural deviations are with respect to an information set.
Args:
  num_actions: the integer of all actions that can be taken at that
    information set
  history: an array containing the prior actions played by the `player` to
    reach the information set.
  prior_legal_actions: a 2d array containing the legal actions for each
    preceeding state.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent
  all (single target) behaviourial deviations that are realizable at the
  information set.
Definition at line 943 of file efr.py.
def return_behavourial(num_actions, history, prior_legal_actions):
  """Returns an array of all single target behavioural deviations.
  The target behavioural deviations are with respect to an information set.
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set
    history: an array containing the prior actions played by the `player` to
      reach the information set.
    prior_legal_actions: a 2d array containing the legal actions for each
      preceeding state.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent
    all (single target) behaviourial deviations that are realizable at the
    information set.
  """
  deviations = []
  if not history:
    internal = return_all_non_identity_internal_deviations(
        num_actions, [None], history
    )
    for i in internal:
      deviations.append(i)
  else:
    for deviation_info in range(len(history)):
      prior_possible_memory_actions = generate_all_action_permutations(
          [], prior_legal_actions[: deviation_info + 1]
      )
      memory_weights = np.concatenate(
          (np.ones(deviation_info), np.zeros(len(history) - deviation_info))
      )
      for prior_memory_actions in prior_possible_memory_actions:
        prior_memory_actions = np.concatenate((
            prior_memory_actions,
            np.zeros(len(history) - len(prior_memory_actions)),
        ))
        for _ in range(len(history) - len(prior_memory_actions)):
          prior_memory_actions.append(0)
        prior_memory_actions_cp = prior_memory_actions.copy()
        internal = return_all_non_identity_internal_deviations(
            num_actions, [memory_weights], prior_memory_actions_cp
        )
        for i in internal:
          deviations.append(i)
  return deviations
References open_spiel.python.algorithms.efr.generate_all_action_permutations(), len, and open_spiel.python.algorithms.efr.return_all_non_identity_internal_deviations().
return_blind_action()
open_spiel.python.algorithms.efr.return_blind_action (num_actions, history, _)
Returns an array of all Blind Action deviations.
Returns an array of all Blind Action deviations. with respect to an with
respect to an information set.
Args:
  num_actions: the integer of all actions that can be taken at that
    information set.
  history: an array containing the prior actions played by the `player` to
    reach the information set.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent all
  Blind Action deviations that are realizable at the information set.
Definition at line 639 of file efr.py.
def return_blind_action(num_actions, history, _):
  """Returns an array of all Blind Action deviations.
  Returns an array of all Blind Action deviations. with respect to an with
  respect to an information set.
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set.
    history: an array containing the prior actions played by the `player` to
      reach the information set.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent all
    Blind Action deviations that are realizable at the information set.
  """
  memory_weights = [np.full(len(history), 1)]
  prior_actions_in_memory = history
  return return_all_external_deviations(
      num_actions, memory_weights, prior_actions_in_memory
  )
References len, and open_spiel.python.algorithms.efr.return_all_external_deviations().
Referenced by open_spiel.python.algorithms.efr.return_cs_partial_sequence().
return_blind_cf()
open_spiel.python.algorithms.efr.return_blind_cf (num_actions, history, _)
Returns an array of all Blind Counterfactual deviations.
Returns an array of all Blind Counterfactual deviations with respect to an
information set.
Note: EFR using only Blind Counterfactual deviations is equivalent
to vanilla Counterfactual Regret Minimisation (CFR).
Args:
  num_actions: the integer of all actions that can be taken at that
    information set.
  history: an array containing the prior actions played by the `player` to
    reach the information set.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent all
  Blind CF deviations that are realizable at the information set.
Definition at line 685 of file efr.py.
def return_blind_cf(num_actions, history, _):
  """Returns an array of all Blind Counterfactual deviations.
  Returns an array of all Blind Counterfactual deviations with respect to an
  information set.
  Note: EFR using only Blind Counterfactual deviations is equivalent
  to vanilla Counterfactual Regret Minimisation (CFR).
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set.
    history: an array containing the prior actions played by the `player` to
      reach the information set.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent all
    Blind CF deviations that are realizable at the information set.
  """
  memory_weights = [None]
  prior_actions_in_memory = np.zeros(len(history))
  return return_all_external_deviations(
      num_actions, memory_weights, prior_actions_in_memory
  )
References len, and open_spiel.python.algorithms.efr.return_all_external_deviations().
Referenced by open_spiel.python.algorithms.efr.return_cs_partial_sequence().
return_blind_partial_sequence()
open_spiel.python.algorithms.efr.return_blind_partial_sequence (num_actions, history, _)
Returns an array of all Blind Partial Sequence deviations (BPS).
Returns an array of all Blind Partial Sequence deviations (BPS) with respect
to an information set.
Args:
  num_actions: the integer of all actions that can be taken at that
    information set.
  history: an array containing the prior actions played by the `player` to
    reach the information set.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent all
  BPS deviations that are realizable at the information set.
Definition at line 733 of file efr.py.
def return_blind_partial_sequence(num_actions, history, _):
  """Returns an array of all Blind Partial Sequence deviations (BPS).
  Returns an array of all Blind Partial Sequence deviations (BPS) with respect
  to an information set.
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set.
    history: an array containing the prior actions played by the `player` to
      reach the information set.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent all
    BPS deviations that are realizable at the information set.
  """
  prior_actions_in_memory = history
  memory_weights = [None]
  if history:
    memory_weights.append(np.ones(len(history)))
  for i in range(len(history)):
    possible_memory_weight = np.zeros(len(history))
    possible_memory_weight[0:i] = np.full(i, 1.0)
    memory_weights.append(possible_memory_weight)
  return return_all_external_deviations(
      num_actions, memory_weights, prior_actions_in_memory
  )
References len, and open_spiel.python.algorithms.efr.return_all_external_deviations().
return_cf_partial_sequence()
open_spiel.python.algorithms.efr.return_cf_partial_sequence (num_actions, history, _)
Returns an array of all Counterfactual Partial Sequence deviations (CFPS).
Returns an array of all Counterfactual Partial Sequence deviations (CFPS)
with respect to an information set.
Args:
  num_actions: the integer of all actions that can be taken at that
    information set.
  history: an array containing the prior actions played by the `player` to
    reach the information set.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent
  all CFPS deviations that are realizable at the information set.
Definition at line 762 of file efr.py.
def return_cf_partial_sequence(num_actions, history, _):
  """Returns an array of all Counterfactual Partial Sequence deviations (CFPS).
  Returns an array of all Counterfactual Partial Sequence deviations (CFPS)
  with respect to an information set.
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set.
    history: an array containing the prior actions played by the `player` to
      reach the information set.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent
    all CFPS deviations that are realizable at the information set.
  """
  prior_actions_in_memory = history
  memory_weights = [None]
  if history:
    memory_weights.append(np.ones(len(history)))
  for i in range(len(history)):
    possible_memory_weight = np.zeros(len(history))
    possible_memory_weight[0:i] = np.full(i, 1.0)
    memory_weights.append(possible_memory_weight)
  return return_all_non_identity_internal_deviations(
      num_actions, memory_weights, prior_actions_in_memory
  )
References len, and open_spiel.python.algorithms.efr.return_all_non_identity_internal_deviations().
return_cs_partial_sequence()
open_spiel.python.algorithms.efr.return_cs_partial_sequence (num_actions, history, prior_legal_actions)
Returns an array of all Casual Partial Sequence deviations.
Returns an array of all Casual Partial Sequence deviations with respect to
an information set.
Args:
  num_actions: the integer of all actions that can be taken at that
    information set
  history: an array containing the prior actions played by the `player` to
    reach the information set.
  prior_legal_actions: a 2d array containing the legal actions for each
    preceeding state.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent all
  Casual Partial Sequence deviations that are realizable at the
  information set.
Definition at line 791 of file efr.py.
def return_cs_partial_sequence(num_actions, history, prior_legal_actions):
  """Returns an array of all Casual Partial Sequence deviations.
  Returns an array of all Casual Partial Sequence deviations with respect to
  an information set.
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set
    history: an array containing the prior actions played by the `player` to
      reach the information set.
    prior_legal_actions: a 2d array containing the legal actions for each
      preceeding state.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent all
    Casual Partial Sequence deviations that are realizable at the
    information set.
  """
  prior_actions_in_memory = history
  external_memory_weights = [None]
  for i in range(len(history)):
    possible_memory_weight = np.zeros(len(history))
    possible_memory_weight[0:i] = np.full(i, 1.0)
    external_memory_weights.append(possible_memory_weight)
  external = return_all_external_modified_deviations(
      num_actions,
      external_memory_weights,
      prior_legal_actions,
      prior_actions_in_memory,
  )
  internal = return_blind_action(num_actions, history, None)
  cf_ext = return_informed_cf(num_actions, history, None)
  cf_int = return_blind_cf(num_actions, history, None)
  return np.concatenate((external, internal, cf_ext, cf_int))
References len, open_spiel.python.algorithms.efr.return_all_external_modified_deviations(), open_spiel.python.algorithms.efr.return_blind_action(), open_spiel.python.algorithms.efr.return_blind_cf(), and open_spiel.python.algorithms.efr.return_informed_cf().
return_cs_partial_sequence_orginal()
open_spiel.python.algorithms.efr.return_cs_partial_sequence_orginal (num_actions, history, prior_legal_actions)
Returns an array of all Casual Partial Sequence deviations.
Returns an array of all Casual Partial Sequence deviations with respect to
an information set.
Args:
  num_actions: the integer of all actions that can be taken at that
    information set
  history: an array containing the prior actions played by the `player` to
    reach the information set.
  prior_legal_actions: a 2d array containing the legal actions for each
    preceeding state.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent all
  Casual Partial Sequence deviations that are realizable at the
  information set.
Definition at line 832 of file efr.py.
):
  """Returns an array of all Casual Partial Sequence deviations.
  Returns an array of all Casual Partial Sequence deviations with respect to
  an information set.
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set
    history: an array containing the prior actions played by the `player` to
      reach the information set.
    prior_legal_actions: a 2d array containing the legal actions for each
      preceeding state.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent all
    Casual Partial Sequence deviations that are realizable at the
    information set.
  """
  prior_actions_in_memory = history
  external_memory_weights = [None]
  for i in range(len(history)):
    possible_memory_weight = np.zeros(len(history))
    possible_memory_weight[0:i] = np.full(i, 1.0)
    external_memory_weights.append(possible_memory_weight)
  external = return_all_external_modified_deviations(
      num_actions,
      external_memory_weights,
      prior_legal_actions,
      prior_actions_in_memory,
  )
  internal = return_informed_action(num_actions, history, None)
  cf_ext = return_informed_cf(num_actions, history, None)
  return np.concatenate((external, internal, cf_ext))
References len, open_spiel.python.algorithms.efr.return_all_external_modified_deviations(), open_spiel.python.algorithms.efr.return_informed_action(), and open_spiel.python.algorithms.efr.return_informed_cf().
return_identity_deviation()
open_spiel.python.algorithms.efr.return_identity_deviation (num_actions, possible_prior_weights, prior_memory_actions)
Definition at line 1270 of file efr.py.
):
  deviations = []
  for prior_actions_weight in possible_prior_weights:
    deviations.append(
        LocalDeviationWithTimeSelection(
            0, 0, num_actions, prior_actions_weight, prior_memory_actions, False
        )
    )
  return deviations
# A swap transformation given by the matrix_transform for an information state.
# Of actions_num size.
return_informed_action()
open_spiel.python.algorithms.efr.return_informed_action (num_actions, history, _)
Returns an array of all Informed Action deviations.
Returns an array of all Informed Action deviations with respect to an
information set.
Args:
  num_actions: the integer of all actions that can be taken at that
    information set.
  history: an array containing the prior actions played by the `player` to
    reach the information set.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent all
  Informed Action deviations that are realizable at the information set.
Definition at line 662 of file efr.py.
def return_informed_action(num_actions, history, _):
  """Returns an array of all Informed Action deviations.
  Returns an array of all Informed Action deviations with respect to an
  information set.
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set.
    history: an array containing the prior actions played by the `player` to
      reach the information set.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent all
    Informed Action deviations that are realizable at the information set.
  """
  memory_weights = [np.full(len(history), 1)]
  prior_actions_in_memory = history
  return return_all_non_identity_internal_deviations(
      num_actions, memory_weights, prior_actions_in_memory
  )
References len, and open_spiel.python.algorithms.efr.return_all_non_identity_internal_deviations().
Referenced by open_spiel.python.algorithms.efr.return_cs_partial_sequence_orginal().
return_informed_cf()
open_spiel.python.algorithms.efr.return_informed_cf (num_actions, history, _)
Returns an array of all Informed Counterfactual deviations.
Returns an array of all Informed Counterfactual deviations with respect with
respect to an information set.
Args:
  num_actions: the integer of all actions that can be taken at that
    information set.
  history: an array containing the prior actions played by the `player` to
    reach the information set.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent all
  Informed CF deviations that are realizable at the information set.
Definition at line 710 of file efr.py.
def return_informed_cf(num_actions, history, _):
  """Returns an array of all Informed Counterfactual deviations.
  Returns an array of all Informed Counterfactual deviations with respect with
  respect to an information set.
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set.
    history: an array containing the prior actions played by the `player` to
      reach the information set.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent all
    Informed CF deviations that are realizable at the information set.
  """
  memory_weights = [None]
  prior_actions_in_memory = np.zeros(len(history))
  return return_all_non_identity_internal_deviations(
      num_actions, memory_weights, prior_actions_in_memory
  )
References len, and open_spiel.python.algorithms.efr.return_all_non_identity_internal_deviations().
Referenced by open_spiel.python.algorithms.efr.return_cs_partial_sequence(), open_spiel.python.algorithms.efr.return_cs_partial_sequence_orginal(), and open_spiel.python.algorithms.efr.return_twice_informed_partial_sequence().
return_twice_informed_partial_sequence()
open_spiel.python.algorithms.efr.return_twice_informed_partial_sequence (num_actions, history, prior_legal_actions)
Returns an array of all Twice Informed Partial Sequence (TIPS) deviations.
Returns an array of all Twice Informed Partial Sequence (TIPS) deviations
with respect to an information set.
Args:
  num_actions: the integer of all actions that can be taken at that
    information set
  history: an array containing the prior actions played by the `player` to
    reach the information set.
  prior_legal_actions: a 2d array containing the legal actions for each
    preceeding state.
Returns:
  an array of LocalDeviationWithTimeSelection objects that represent
  all TIPS deviations that are realizable at theinformation set.
Definition at line 873 of file efr.py.
):
  """Returns an array of all Twice Informed Partial Sequence (TIPS) deviations.
  Returns an array of all Twice Informed Partial Sequence (TIPS) deviations
  with respect to an information set.
  Args:
    num_actions: the integer of all actions that can be taken at that
      information set
    history: an array containing the prior actions played by the `player` to
      reach the information set.
    prior_legal_actions: a 2d array containing the legal actions for each
      preceeding state.
  Returns:
    an array of LocalDeviationWithTimeSelection objects that represent
    all TIPS deviations that are realizable at theinformation set.
  """
  prior_actions_in_memory = history
  memory_weights = [None]
  for i in range(len(history)):
    possible_memory_weight = np.zeros(len(history))
    possible_memory_weight[0:i] = np.full(i, 1.0)
    memory_weights.append(possible_memory_weight)
  internal = return_all_internal_modified_deviations(
      num_actions, memory_weights, prior_legal_actions, prior_actions_in_memory
  )
  cf_int = return_informed_cf(num_actions, history, None)
  return np.concatenate((internal, cf_int))
References len, open_spiel.python.algorithms.efr.return_all_internal_modified_deviations(), and open_spiel.python.algorithms.efr.return_informed_cf().
strat_dict_to_array()
open_spiel.python.algorithms.efr.strat_dict_to_array (strategy_dictionary)
A helper function to convert the strategy dictionary mapping.
Conversion applies action -> prob value to an array.
Args:
  strategy_dictionary: a dictionary action -> prob value.
Returns:
  strategy_array: an array with the ith action's value at the i-1th index.
Definition at line 590 of file efr.py.
def strat_dict_to_array(strategy_dictionary):
  """A helper function to convert the strategy dictionary mapping.
  Conversion applies action -> prob value to an array.
  Args:
    strategy_dictionary: a dictionary action -> prob value.
  Returns:
    strategy_array: an array with the ith action's value at the i-1th index.
  """
  actions = list(strategy_dictionary.keys())
  strategy_array = np.zeros((len(actions), 1))
  for action in range(len(actions)):
    strategy_array[action][0] = strategy_dictionary[actions[action]]
  return strategy_array
References len.
Referenced by open_spiel.python.algorithms.efr._EFRSolverBase._compute_cumulative_immediate_regret_for_player().