open spiel: open_spiel::universal_poker::logic Namespace Reference
open_spiel::universal_poker::logic Namespace Reference
Classes
class CardSet
Functions
uint64_t bit_twiddle_permute (uint64_t v)
void BasicCardSetTests ()
std::string GamedefToOpenSpielParameters (const std::string &acpc_gamedef)
void TestGamedefToOpenSpielParametersEasyCase ()
void TestGamedefToOpenSpielParametersNormalizesKeyOnlyLines ()
void TestGamedefToOpenSpielParametersMultiRoundValueEdgeCase ()
void TestGamedefToOpenSpielParametersRemovesUnneededLines ()
void TestGamedefToOpenSpielParametersNormalizesCapitalization ()
Variables
constexpr int kMaxSuits = 4
constexpr char kGamedef [] = "gamedef"
constexpr char kEndGamedef [] = "end gamedef"
const char kSimpleHeadsupLimitPokerACPCGamedef []
Function Documentation
BasicCardSetTests()
void open_spiel::universal_poker::logic::BasicCardSetTests ()
Definition at line 23 of file card_set_test.cc.
{
  CardSet cs("AhKsQhJhTh");
  std::cout << "CardSet: " << cs.ToString() << std::endl;
  for (auto card : cs.ToCardArray()) {
    std::cout << "Card: " << card << std::endl;
  }
  std::cout << "Rank: " << cs.RankCards() << std::endl;
  std::cout << "Count Cards: " << cs.NumCards() << std::endl;
  CardSet deck(4, 13);
  std::cout << "CardSet: " << deck.ToString() << std::endl;
  std::cout << "Rank: " << deck.RankCards() << std::endl;
  std::cout << "Count Cards: " << deck.NumCards() << std::endl;
  for (auto combo : deck.SampleCards(3)) {
    std::cout << "CardSet: " << combo.ToString() << std::endl;
  }
  for (auto combo : deck.SampleCards(1)) {
    std::cout << "CardSet: " << combo.ToString() << std::endl;
  }
}
References open_spiel::universal_poker::logic::CardSet::NumCards(), open_spiel::universal_poker::logic::CardSet::RankCards(), open_spiel::universal_poker::logic::CardSet::SampleCards(), open_spiel::universal_poker::logic::CardSet::ToCardArray(), and open_spiel::universal_poker::logic::CardSet::ToString().
Referenced by main().
bit_twiddle_permute()
uint64_t open_spiel::universal_poker::logic::bit_twiddle_permute (uint64_t v)
Definition at line 37 of file card_set.cc.
{
  uint64_t t = v | (v - 1);
  uint64_t u = ((~t & -~t) - 1);
  int shift = __builtin_ctzl(v) + 1;
  // Shifting by 64 bits or more is undefined behaviour, so we must avoid it.
  // See for example: http://c0x.coding-guidelines.com/6.5.7.html (1185).
  u = (shift < 64) ? (u >> shift) : 0;
  uint64_t w = (t + 1) | u;
  return w;
}
Referenced by open_spiel::universal_poker::DistributeHands(), and open_spiel::universal_poker::logic::CardSet::SampleCards().
GamedefToOpenSpielParameters()
std::string open_spiel::universal_poker::logic::GamedefToOpenSpielParameters (const std::string & acpc_gamedef)
Definition at line 36 of file gamedef.cc.
{
  if (acpc_gamedef.empty()) {
    SpielFatalError("Input ACPC gamedef was empty.");
  }
  if (!StrContainsIgnoreCase(acpc_gamedef, kGamedef)) {
    SpielFatalError(absl::StrCat("ACPC gamedef does not contain 'GAMEDEF': ",
                                 acpc_gamedef));
  }
  // Check the GAMEDEF/END GAMEDEF statements are valid and not something like
  // e.g. 'GAMEDEFfoo' or 'SPEND GAMEDEF'.
  //
  // GAMEDEF either is the very first line, in which case it should be followed
  // by an "\n", or it is not, in which case it should be both followed by an
  // "\n" AND also prefixed by another "\n".
  if (!absl::StartsWithIgnoreCase(acpc_gamedef, absl::StrCat(kGamedef, "\n")) &&
      !StrContainsIgnoreCase(acpc_gamedef,
                                   absl::StrCat("\n", kGamedef, "\n"))) {
    SpielFatalError(
        absl::StrCat("ACPC gamedef does not have 'GAMEDEF' on its own line "
                     "(please remove any trailing or prefixed characters, "
                     "including whitespace):",
                     acpc_gamedef));
  }
  // END GAMEDEF either is the very last line, in which case it should be
  // prefixed by an "\n", or it is not, in which case it should be both prefixed
  // by an "\n" AND also followed by another "\n".
  if (!StrContainsIgnoreCase(acpc_gamedef, kEndGamedef)) {
    SpielFatalError(absl::StrCat(
        "ACPC gamedef does not contain 'END GAMEDEF': ", acpc_gamedef));
  }
  if (!absl::EndsWithIgnoreCase(acpc_gamedef,
                                absl::StrCat("\n", kEndGamedef)) &&
      !StrContainsIgnoreCase(acpc_gamedef,
                             absl::StrCat("\n", kEndGamedef, "\n"))) {
    SpielFatalError(
        absl::StrCat("ACPC gamedef does not have an 'END GAMEDEF' on its own "
                     "line (please remove any trailing or prefixed characters, "
                     "including whitespace):",
                     acpc_gamedef));
  }
  // As per definition of gamedef -> "case is ignored". So we will normalize to
  // lowercase initially / when initially processing it. (Note: we will have to
  // 'correct' the capitalization for all our keys down below at the end. Since
  // OpenSpiel itself *does* care about capitalization, unlike the official ACPC
  // gamedef definition.)
  std::string gamedef_normalized =
      absl::AsciiStrToLower(absl::StripAsciiWhitespace(acpc_gamedef));
  std::vector<std::string> open_spiel_state_args = {};
  // Gamedef's definition states that: "Empty lines or lines with '#' as the
  // very first character will be ignored". (Note that this means we do NOT want
  // to treat '#' like code comments, which normally take affect even in the
  // middle of a line.)
  // Additionally, we want to skip doing anything for the 'gamedef' and
  // 'end gamedef' lines (now that we've verified they appear in it somewhere)
  // because they're not needed for the Open Spiel game state.
  const auto is_useful_line = [](absl::string_view line) {
    return !line.empty() && line[0] != '#' && line != kGamedef &&
           line != kEndGamedef;
  };
  std::vector<std::string> lines = absl::StrSplit(gamedef_normalized, '\n');
  for (const auto& line : lines) {
    // Skip lines that are not useful.
    if (!is_useful_line(line)) { continue; }
    // EDGE CASE: we should only see exactly one of either 'limit' or 'nolimit',
    // and it should be on its own line. TLDR it's like 'END GAMEDEF' in that
    // it's atypical / has no '=' in it, which would interfere with our
    // processing below. (Hence why we're immediately taking care of it here.)
    if ((line == "limit") || (line == "nolimit")) {
      open_spiel_state_args.push_back(absl::StrCat("betting=", line));
      continue;
    }
    // else line must be of the following form: key[ ]=[ ]val1[ val2 val3 ...]
    if (!absl::StrContains(line, '=')) {
      SpielFatalError(
          absl::StrCat("Gamedef line is missing its '=' character: ", line));
    }
    std::vector<std::string> key_and_values = absl::StrSplit(line, '=');
    if (key_and_values.size() != 2) {
      SpielFatalError(
          absl::StrCat("Gamedef line has wrong number of components: ", line));
    }
    auto key = std::string(absl::StripAsciiWhitespace(key_and_values[0]));
    // Note that "values" is plural on purpose - it has potentially multiple,
    // space-separated things in it!
    auto values = std::string(absl::StripAsciiWhitespace(key_and_values[1]));
    // EDGE CASE:
    // There's a bug with a downstream serializer that gets confused and errors
    // if it receives a single value in places that can potentially be multiple
    // values, e.g. firstPlayer value '1' vs '1 1' (regardless of the actual
    // number of players / betting rounds / etc).
    //
    // With the exception of the 'blind' input, there is typically no meaningful
    // difference between the value appearing a single time, vs the same exact
    // value appearing twice (separated by a space). So, as a workaround we
    // manually convert the former form to the latter.
    //
    // Yes, this is hacky. But it's also the most durable option we have until
    // we can go fix the downstream issue :)
    const std::set<std::string> optionally_multi_round_parameters = {
        "firstplayer", "raisesize", "maxraises", "numboardcards", "stack"};
    if (optionally_multi_round_parameters.find(key) !=
        optionally_multi_round_parameters.end() && !values.empty() &&
        !absl::StrContains(values, " ")) {
      // Note: "values" is a single integer if in this section (hence why we're
      // having this problem to begin with; see above for more details).
      // Note: this line has a potentially multi-round value defined in terms of
      // single round. Transforming the value into another that is equivalent,
      // but defined multi-round, to prevent downstream deserializer errors.;
      values = absl::StrCat(values, " ", values);
      // Transformed value into another that is equivalent, but defined as
      // multi-round
    }
    open_spiel_state_args.push_back(absl::StrCat(key, "=", values));
  }
  std::string lowercase_open_spiel_game_state = absl::StrCat(
      "universal_poker(", absl::StrJoin(open_spiel_state_args, ","), ")");
  // See below - unlike the input ACPC gamedef (where casing is ignored),
  // OpenSpiel will actually error at runtime if the arg keys aren't capitalized
  // in the exact way it expects.
  // (Note: deliberately including things like e.g. bettingAbstraction that are
  // not actually valid params for the ACPC gamedef to avoid future bugs).
  static const char* const kPossibleGameStateKeysCapitalized[] = {
      "betting",       "bettingAbstraction",
      "blind",         "boardCards",
      "firstPlayer",   "gamedef",
      "handReaches",   "maxRaises",
      "numBoardCards", "numHoleCards",
      "numPlayers",    "numRanks",
      "numRounds",     "numSuits",
      "potSize",       "raiseSize",
      "stack",
  };
  std::vector<std::pair<std::string, std::string>> replacements = {};
  for (const std::string& capitalized_key : kPossibleGameStateKeysCapitalized) {
    std::string lowercase_key = absl::AsciiStrToLower(capitalized_key);
    if (capitalized_key == lowercase_key) {
      continue;
    }
    // Regardless of order, at this point we know each parameter either is at
    // the start - and following an open paren - or is comma-separated from
    // the preceding parameter. Hence we can look for a preceding "(" or ",".
    replacements.push_back(std::make_pair(absl::StrCat("(", lowercase_key),
                                          absl::StrCat("(", capitalized_key)));
    replacements.push_back(std::make_pair(absl::StrCat(",", lowercase_key),
                                          absl::StrCat(",", capitalized_key)));
  }
  return absl::StrReplaceAll(lowercase_open_spiel_game_state, replacements);
}
References absl::AsciiStrToLower(), absl::EndsWithIgnoreCase(), kEndGamedef, key, kGamedef, open_spiel::SpielFatalError(), absl::StartsWithIgnoreCase(), absl::StrCat(), absl::StrContains(), open_spiel::StrContainsIgnoreCase(), absl::StripAsciiWhitespace(), absl::StrJoin(), absl::StrReplaceAll(), absl::StrSplit(), and values.
Referenced by open_spiel::universal_poker::LoadUniversalPokerGameFromACPCGamedef(), TestGamedefToOpenSpielParametersEasyCase(), TestGamedefToOpenSpielParametersMultiRoundValueEdgeCase(), TestGamedefToOpenSpielParametersNormalizesCapitalization(), TestGamedefToOpenSpielParametersNormalizesKeyOnlyLines(), and TestGamedefToOpenSpielParametersRemovesUnneededLines().
TestGamedefToOpenSpielParametersEasyCase()
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersEasyCase ()
Definition at line 45 of file gamedef_test.cc.
{
  std::cout << "acpc gamedef:\n"
            << kSimpleHeadsupLimitPokerACPCGamedef << "\n"
            << std::endl;
  std::cout << "OpenSpiel gamestate:\n"
            << GamedefToOpenSpielParameters(kSimpleHeadsupLimitPokerACPCGamedef)
            << "\n"
            << std::endl;
}
References GamedefToOpenSpielParameters(), and kSimpleHeadsupLimitPokerACPCGamedef.
Referenced by main().
TestGamedefToOpenSpielParametersMultiRoundValueEdgeCase()
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersMultiRoundValueEdgeCase ()
Definition at line 74 of file gamedef_test.cc.
{
  std::string acpc_gamedef = R""""(
GAMEDEF
limit
numPlayers = 1
numRounds = 1
blind = 5
raiseSize = 10
firstPlayer = 1
maxRaises = 2
numSuits = 4
numRanks = 5
numHoleCards = 1
numBoardCards = 2
stack = 100
END GAMEDEF)"""";
  std::string open_spiel_game_state =
      GamedefToOpenSpielParameters(acpc_gamedef);
  SPIEL_CHECK_TRUE(
      absl::StrContains(open_spiel_game_state, ",firstPlayer=1 1,"));
  SPIEL_CHECK_TRUE(
      absl::StrContains(open_spiel_game_state, ",raiseSize=10 10,"));
  SPIEL_CHECK_TRUE(absl::StrContains(open_spiel_game_state, ",maxRaises=2 2,"));
  SPIEL_CHECK_TRUE(absl::StrContains(open_spiel_game_state, ",stack=100 100)"));
}
References GamedefToOpenSpielParameters(), SPIEL_CHECK_TRUE, and absl::StrContains().
Referenced by main().
TestGamedefToOpenSpielParametersNormalizesCapitalization()
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersNormalizesCapitalization ()
Definition at line 137 of file gamedef_test.cc.
{
  std::string acpc_gamedef = R""""(
gameDEF
limit
numplayers = 2
numrounds = 1
blind = 5 10
raisesize = 10 10 20
MAXRAISES = 2 2 3
NUMSUITS = 4
NUMRANKS = 5
nUmHoLeCARds = 1
numBoardCARDS = 0 2 1
end GameDef
)"""";
  std::string open_spiel_game_state =
      GamedefToOpenSpielParameters(acpc_gamedef);
  SPIEL_CHECK_TRUE(absl::StrContains(open_spiel_game_state, ",numPlayers=2,"));
  SPIEL_CHECK_TRUE(absl::StrContains(open_spiel_game_state, ",numRounds=1,"));
  SPIEL_CHECK_TRUE(absl::StrContains(open_spiel_game_state, ",blind=5 10,"));
  SPIEL_CHECK_TRUE(
      absl::StrContains(open_spiel_game_state, ",raiseSize=10 10 20,"));
  SPIEL_CHECK_TRUE(absl::StrContains(open_spiel_game_state, ",numSuits=4,"));
  SPIEL_CHECK_TRUE(absl::StrContains(open_spiel_game_state, ",numRanks=5,"));
  SPIEL_CHECK_TRUE(
      absl::StrContains(open_spiel_game_state, ",numHoleCards=1,"));
}
References GamedefToOpenSpielParameters(), SPIEL_CHECK_TRUE, and absl::StrContains().
Referenced by main().
TestGamedefToOpenSpielParametersNormalizesKeyOnlyLines()
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersNormalizesKeyOnlyLines ()
Definition at line 56 of file gamedef_test.cc.
{
  std::string open_spiel_game_state =
      GamedefToOpenSpielParameters(kSimpleHeadsupLimitPokerACPCGamedef);
  SPIEL_CHECK_TRUE(absl::StrContains(open_spiel_game_state, "betting=limit,"));
  SPIEL_CHECK_FALSE(
      StrContainsIgnoreCase(open_spiel_game_state, "end gamedef"));
  SPIEL_CHECK_FALSE(
      StrContainsIgnoreCase(open_spiel_game_state, "gamedef"));
  SPIEL_CHECK_FALSE(
      StrContainsIgnoreCase(open_spiel_game_state, "nolimit"));
}
References GamedefToOpenSpielParameters(), kSimpleHeadsupLimitPokerACPCGamedef, SPIEL_CHECK_FALSE, SPIEL_CHECK_TRUE, absl::StrContains(), and open_spiel::StrContainsIgnoreCase().
Referenced by main().
TestGamedefToOpenSpielParametersRemovesUnneededLines()
void open_spiel::universal_poker::logic::TestGamedefToOpenSpielParametersRemovesUnneededLines ()
Definition at line 101 of file gamedef_test.cc.
{
  std::string acpc_gamedef = R""""(
# COMMENT THAT SHOULD BE IGNORED
gameDEF
limit
numplayers = 2
numrounds = 1
# ANOTHER COMMENT
blind = 5 10
raisesize = 10 10 20
# Empty lines are also ignored!
MAXRAISES = 2 2 3
NUMSUITS = 4
NUMRANKS = 5
nUmHoLeCARds = 1
numBoardCARDS = 0 2 1
end GameDef
# hasta la vista
)"""";
  std::string open_spiel_game_state =
      GamedefToOpenSpielParameters(acpc_gamedef);
  SPIEL_CHECK_FALSE(absl::StrContains(open_spiel_game_state, "COMMENT"));
  SPIEL_CHECK_FALSE(absl::StrContains(open_spiel_game_state, "EMPTY"));
  SPIEL_CHECK_FALSE(absl::StrContains(open_spiel_game_state, "#"));
  SPIEL_CHECK_FALSE(absl::StrContains(open_spiel_game_state, "\n"));
  SPIEL_CHECK_FALSE(
      StrContainsIgnoreCase(open_spiel_game_state, "end gamedef"));
  SPIEL_CHECK_FALSE(
      StrContainsIgnoreCase(open_spiel_game_state, "gamedef"));
}
References GamedefToOpenSpielParameters(), SPIEL_CHECK_FALSE, absl::StrContains(), and open_spiel::StrContainsIgnoreCase().
Referenced by main().
Variable Documentation
kEndGamedef
char open_spiel::universal_poker::logic::kEndGamedef[] = "end gamedef" constexpr
Definition at line 34 of file gamedef.cc.
Referenced by GamedefToOpenSpielParameters().
kGamedef
char open_spiel::universal_poker::logic::kGamedef[] = "gamedef" constexpr
Definition at line 33 of file gamedef.cc.
Referenced by GamedefToOpenSpielParameters().
kMaxSuits
int open_spiel::universal_poker::logic::kMaxSuits = 4 constexpr
Definition at line 26 of file card_set.h.
kSimpleHeadsupLimitPokerACPCGamedef
const char open_spiel::universal_poker::logic::kSimpleHeadsupLimitPokerACPCGamedef[]
Initial value:
=
    R""""(
GAMEDEF
limit
numPlayers = 2
numRounds = 1
blind = 5 10
raiseSize = 10 10 20
firstPlayer = 1
maxRaises = 2 2 3
numSuits = 4
numRanks = 5
numHoleCards = 1
numBoardCards = 0 2 1
END GAMEDEF)""""
Definition at line 28 of file gamedef_test.cc.
Referenced by TestGamedefToOpenSpielParametersEasyCase(), and TestGamedefToOpenSpielParametersNormalizesKeyOnlyLines().