open spiel: absl::random_internal Namespace Reference
absl::random_internal Namespace Reference
Classes
struct DistributionCaller
struct DistributionMoments
class ExplicitSeedSeq
class FastUniformBits
class gaussian_distribution_base
struct GenerateNegativeTag
struct GeneratePositiveTag
struct GenerateSignedTag
struct is_salted_seed_seq
struct is_salted_seed_seq< T, typename std::enable_if< std::is_same< T, SaltedSeedSeq< typename T::inner_sequence_type > >::value >::type >
struct is_urbg
struct is_urbg< URBG, absl::enable_if_t< std::is_same< typename URBG::result_type, typename std::decay< decltype((URBG::min)())>::type >::value >, absl::enable_if_t< std::is_same< typename URBG::result_type, typename std::decay< decltype((URBG::max)())>::type >::value >, absl::enable_if_t< std::is_same< typename URBG::result_type, typename std::decay< decltype(std::declval< URBG >()())>::type >::value > >
class is_widening_convertible
struct IsIntegral
struct IsIntegral< absl::int128 >
struct IsIntegral< absl::uint128 >
class istream_state_saver
struct IsUnsigned
struct IsUnsigned< absl::int128 >
struct IsUnsigned< absl::uint128 >
struct make_unsigned_bits
struct MakeUnsigned
struct MakeUnsigned< absl::int128 >
struct MakeUnsigned< absl::uint128 >
class MockHelpers
struct MockOverloadSet
struct MockOverloadSet< DistrT, FirstSig, Rest... >
struct MockOverloadSet< DistrT, Sig >
struct MockSingleOverload
struct MockSingleOverload< DistrT, Ret(Arg, MockingBitGen &, Args...)>
struct MockSingleOverload< DistrT, Ret(MockingBitGen &, Args...)>
class NonsecureURBGBase
class null_state_saver
class ostream_state_saver
class pcg128_params
class pcg64_params
class pcg_engine
struct pcg_xsh_rr_64_32
struct pcg_xsl_rr_128_64
class PoolURBG
class Randen
class randen_engine
class RandenHwAes
class RandenPool
class RandenPoolSeedSeq
class RandenSlow
struct RandenTraits
struct RejectionLoopTag
class SaltedSeedSeq
class sequence_urbg
struct SimplifiedLoopTag
struct stream_format_type
struct stream_precision_helper
struct stream_precision_helper< double >
struct stream_precision_helper< float >
struct stream_precision_helper< long double >
struct stream_u128_helper
struct stream_u128_helper< absl::uint128 >
class TableGenerator
struct TagTypeCompare
struct U256
struct UniformDistributionWrapper
struct unsigned_bits
struct unsigned_bits< 128 >
struct unsigned_bits< 16 >
struct unsigned_bits< 256 >
struct unsigned_bits< 32 >
struct unsigned_bits< 64 >
struct unsigned_bits< 8 >
struct wide_multiply
struct wide_multiply< uint128 >
Typedefs
using pcg64_2018_engine
using pcg32_2018_engine
template<typename A , typename B >
using uniform_inferred_return_t
template<typename NumType >
using UniformDistribution
Functions
std::vector< std::pair< double, size_t > > InitDiscreteDistribution (std::vector< double > *probabilities)
double ChiSquareValue (int dof, double p)
double ChiSquarePValue (double chi_square, int dof)
template<typename Iterator >
double ChiSquareWithExpected (Iterator begin, Iterator end, double expected)
template<typename Iterator , typename Expected >
double ChiSquare (Iterator it, Iterator end, Expected eit, Expected eend)
DistributionMoments ComputeDistributionMoments (absl::Span< const double > data_points)
std::ostream & operator<< (std::ostream &os, const DistributionMoments &moments)
double InverseNormalSurvival (double x)
bool Near (absl::string_view msg, double actual, double expected, double bound)
double beta (double p, double q)
double erfinv (double x)
double BetaIncomplete (const double x, const double p, const double q)
double BetaIncompleteInv (const double p, const double q, const double alpha)
double RequiredSuccessProbability (const double p_fail, const int num_trials)
double ZScore (double expected_mean, const DistributionMoments &moments)
double MaxErrorTolerance (double acceptance_probability)
template<typename UIntType >
constexpr bool IsPowerOfTwoOrZero (UIntType n)
template<typename URBG >
constexpr URBG::result_type RangeSize ()
template<typename UIntType >
constexpr UIntType IntegerLog2 (UIntType n)
template<typename URBG >
constexpr size_t NumBits ()
template<typename UIntType >
constexpr UIntType MaskFromShift (size_t n)
int IntLog2Floor (uint64_t n)
int IntLog2Ceil (uint64_t n)
double StirlingLogFactorial (double n)
template<typename RealType , typename SignedTag = GeneratePositiveTag, bool IncludeZero = true>
RealType GenerateRealFromBits (uint64_t bits, int exp_bias=0)
template<typename CharT , typename Traits >
ostream_state_saver< std::basic_ostream< CharT, Traits > > make_ostream_state_saver (std::basic_ostream< CharT, Traits > &os, std::ios_base::fmtflags flags=std::ios_base::dec|std::ios_base::left|std::ios_base::scientific)
template<typename T >
absl::enable_if_t<!std::is_base_of< std::ios_base, T >::value, null_state_saver< T > > make_ostream_state_saver (T &is, std::ios_base::fmtflags flags=std::ios_base::dec)
template<typename CharT , typename Traits >
istream_state_saver< std::basic_istream< CharT, Traits > > make_istream_state_saver (std::basic_istream< CharT, Traits > &is, std::ios_base::fmtflags flags=std::ios_base::dec|std::ios_base::scientific|std::ios_base::skipws)
template<typename T >
absl::enable_if_t<!std::is_base_of< std::ios_base, T >::value, null_state_saver< T > > make_istream_state_saver (T &is, std::ios_base::fmtflags flags=std::ios_base::dec)
template<typename FloatType , typename IStream >
FloatType read_floating_point (IStream &is)
bool CPUSupportsRandenHwAes ()
bool HasRandenHwAesImplementation ()
template<typename SSeq , typename EnableIf = absl::enable_if_t<is_salted_seed_seq<SSeq>::value>>
SSeq MakeSaltedSeedSeq (SSeq &&seq)
template<typename SSeq , typename EnableIf = absl::enable_if_t<!is_salted_seed_seq<SSeq>::value>>
SaltedSeedSeq< typename std::decay< SSeq >::type > MakeSaltedSeedSeq (SSeq &&seq)
bool ReadSeedMaterialFromOSEntropy (absl::Span< uint32_t > values)
void MixIntoSeedMaterial (absl::Span< const uint32_t > sequence, absl::Span< uint32_t > seed_material)
absl::optional< uint32_t > GetSaltMaterial ()
constexpr size_t SeedBitsToBlocks (size_t seed_size)
template<typename URBG >
ABSL_MUST_USE_RESULT bool ReadSeedMaterialFromURBG (URBG *urbg, absl::Span< uint32_t > values)
template<typename T >
int BitWidth (T v)
template<typename T >
constexpr bool operator== (TagTypeCompare< T >, TagTypeCompare< T >)
template<typename T >
constexpr bool operator!= (TagTypeCompare< T >, TagTypeCompare< T >)
template<typename IntType , typename Tag >
absl::enable_if_t< absl::conjunction< IsIntegral< IntType >, absl::disjunction< std::is_same< Tag, IntervalOpenClosedTag >, std::is_same< Tag, IntervalOpenOpenTag > > >::value, IntType > uniform_lower_bound (Tag, IntType a, IntType)
template<typename FloatType , typename Tag >
absl::enable_if_t< absl::conjunction< std::is_floating_point< FloatType >, absl::disjunction< std::is_same< Tag, IntervalOpenClosedTag >, std::is_same< Tag, IntervalOpenOpenTag > > >::value, FloatType > uniform_lower_bound (Tag, FloatType a, FloatType b)
template<typename NumType , typename Tag >
absl::enable_if_t< absl::disjunction< std::is_same< Tag, IntervalClosedClosedTag >, std::is_same< Tag, IntervalClosedOpenTag > >::value, NumType > uniform_lower_bound (Tag, NumType a, NumType)
template<typename IntType , typename Tag >
absl::enable_if_t< absl::conjunction< IsIntegral< IntType >, absl::disjunction< std::is_same< Tag, IntervalClosedOpenTag >, std::is_same< Tag, IntervalOpenOpenTag > > >::value, IntType > uniform_upper_bound (Tag, IntType, IntType b)
template<typename FloatType , typename Tag >
absl::enable_if_t< absl::conjunction< std::is_floating_point< FloatType >, absl::disjunction< std::is_same< Tag, IntervalClosedOpenTag >, std::is_same< Tag, IntervalOpenOpenTag > > >::value, FloatType > uniform_upper_bound (Tag, FloatType, FloatType b)
template<typename IntType , typename Tag >
absl::enable_if_t< absl::conjunction< IsIntegral< IntType >, absl::disjunction< std::is_same< Tag, IntervalClosedClosedTag >, std::is_same< Tag, IntervalOpenClosedTag > > >::value, IntType > uniform_upper_bound (Tag, IntType, IntType b)
template<typename FloatType , typename Tag >
absl::enable_if_t< absl::conjunction< std::is_floating_point< FloatType >, absl::disjunction< std::is_same< Tag, IntervalClosedClosedTag >, std::is_same< Tag, IntervalOpenClosedTag > > >::value, FloatType > uniform_upper_bound (Tag, FloatType, FloatType b)
template<typename FloatType >
absl::enable_if_t< std::is_floating_point< FloatType >::value, bool > is_uniform_range_valid (FloatType a, FloatType b)
template<typename IntType >
absl::enable_if_t< IsIntegral< IntType >::value, bool > is_uniform_range_valid (IntType a, IntType b)
U256 MultiplyU128ToU256 (uint128 a, uint128 b)
void ThrowSeedGenException ()
Variables
constexpr const char kChiSquared [] = "chi-squared"
const unsigned char kRandenRoundKeysBE [kKeyBytes]
const unsigned char kRandenRoundKeys [kKeyBytes]
constexpr size_t kEntropyBitsNeeded = 256
constexpr size_t kEntropyBlocksNeeded
Typedef Documentation
pcg32_2018_engine
using absl::random_internal::pcg32_2018_engine
Initial value:
 pcg_engine<
    random_internal::pcg64_params<0x5851f42d4c957f2dull, 0x14057b7ef767814full>,
    random_internal::pcg_xsh_rr_64_32>
Definition at line 279 of file pcg_engine.h.
pcg64_2018_engine
using absl::random_internal::pcg64_2018_engine
Initial value:
 pcg_engine<
    random_internal::pcg128_params<0x2360ed051fc65da4ull, 0x4385df649fccf645ull,
                                   0x5851f42d4c957f2d, 0x14057b7ef767814f>,
    random_internal::pcg_xsl_rr_128_64>
Definition at line 272 of file pcg_engine.h.
uniform_inferred_return_t
template<typename A , typename B > using absl::random_internal::uniform_inferred_return_t
Initial value:
    absl::enable_if_t<absl::disjunction<is_widening_convertible<A, B>,
                                        is_widening_convertible<B, A>>::value,
                      typename std::conditional<
                          is_widening_convertible<A, B>::value, B, A>::type>
Definition at line 78 of file uniform_helper.h.
UniformDistribution
template<typename NumType > using absl::random_internal::UniformDistribution
Initial value:
    typename std::conditional<IsIntegral<NumType>::value,
                              absl::uniform_int_distribution<NumType>,
                              absl::uniform_real_distribution<NumType>>::type
Definition at line 212 of file uniform_helper.h.
Function Documentation
beta()
double absl::random_internal::beta (double p, double q)
Definition at line 102 of file distribution_test_util.cc.
{
  // Beta(x, y) = Gamma(x) * Gamma(y) / Gamma(x+y)
  double lbeta = std::lgamma(p) + std::lgamma(q) - std::lgamma(p + q);
  return std::exp(lbeta);
}
References absl::p.
Referenced by BetaIncomplete(), and BetaIncompleteInv().
BetaIncomplete()
double absl::random_internal::BetaIncomplete (const double x, const double p, const double q)
Definition at line 367 of file distribution_test_util.cc.
{
  // Error cases.
  if (p < 0 || q < 0 || x < 0 || x > 1.0) {
    return std::numeric_limits<double>::infinity();
  }
  if (x == 0 || x == 1) {
    return x;
  }
  // ln(Beta(p, q))
  double beta = std::lgamma(p) + std::lgamma(q) - std::lgamma(p + q);
  return BetaIncompleteImpl(x, p, q, beta);
}
References beta(), absl::p, and absl::x.
BetaIncompleteInv()
double absl::random_internal::BetaIncompleteInv (const double p, const double q, const double alpha)
Definition at line 380 of file distribution_test_util.cc.
{
  // Error cases.
  if (p < 0 || q < 0 || alpha < 0 || alpha > 1.0) {
    return std::numeric_limits<double>::infinity();
  }
  if (alpha == 0 || alpha == 1) {
    return alpha;
  }
  // ln(Beta(p, q))
  double beta = std::lgamma(p) + std::lgamma(q) - std::lgamma(p + q);
  return BetaIncompleteInvImpl(p, q, beta, alpha);
}
References beta(), and absl::p.
BitWidth()
template<typename T > int absl::random_internal::BitWidth (T v)
Definition at line 133 of file traits.h.
                  {
  // Workaround for bit_width not supporting int128.
  // Don't hardcode `64` to make sure this code does not trigger compiler
  // warnings in smaller types.
  constexpr int half_bits = sizeof(T) * 8 / 2;
  if (sizeof(T) == 16 && (v >> half_bits) != 0) {
    return bit_width(static_cast<uint64_t>(v >> half_bits)) + half_bits;
  } else {
    return bit_width(static_cast<uint64_t>(v));
  }
}
References absl::bit_width(), and absl::v.
Referenced by absl::log_uniform_int_distribution< IntType >::param_type::param_type().
ChiSquare()
template<typename Iterator , typename Expected > double absl::random_internal::ChiSquare (Iterator it, Iterator end, Expected eit, Expected eend)
Definition at line 56 of file chi_square.h.
{
  double chi_square = 0;
  for (; it != end && eit != eend; ++it, ++eit) {
    if (*it > 0) {
      assert(*eit > 0);
    }
    double e = static_cast<double>(*eit);
    double d = static_cast<double>(*it - *eit);
    if (d != 0) {
      assert(e > 0);
      chi_square += (d * d) / e;
    }
  }
  assert(it == end && eit == eend);
  return chi_square;
}
References absl::d, and absl::e.
ChiSquarePValue()
double absl::random_internal::ChiSquarePValue (double chi_square, int dof)
Definition at line 157 of file chi_square.cc.
{
  static constexpr double kLogSqrtPi =
      0.5723649429247000870717135;  // Log[Sqrt[Pi]]
  static constexpr double kInverseSqrtPi =
      0.5641895835477562869480795;  // 1/(Sqrt[Pi])
  // For large degrees of freedom, use the normal approximation by
  //     Wilson, E. B. and Hilferty, M. M. (1931)
  // Via Wikipedia:
  //   By the Central Limit Theorem, because the chi-square distribution is the
  //   sum of k independent random variables with finite mean and variance, it
  //   converges to a normal distribution for large k.
  if (dof > kLargeDOF) {
    // Re-scale everything.
    const double chi_square_scaled = std::pow(chi_square / dof, 1.0 / 3);
    const double mean = 1 - 2.0 / (9 * dof);
    const double variance = 2.0 / (9 * dof);
    // If variance is 0, this method cannot be used.
    if (variance != 0) {
      const double z = (chi_square_scaled - mean) / std::sqrt(variance);
      if (z > 0) {
        return normal_survival(z);
      } else if (z < 0) {
        return 1.0 - normal_survival(-z);
      } else {
        return 0.5;
      }
    }
  }
  // The chi square function is >= 0 for any degrees of freedom.
  // In other words, probability that the chi square function >= 0 is 1.
  if (chi_square <= 0.0) return 1.0;
  // If the degrees of freedom is zero, the chi square function is always 0 by
  // definition. In other words, the probability that the chi square function
  // is > 0 is zero (chi square values <= 0 have been filtered above).
  if (dof < 1) return 0;
  auto capped_exp = [](double x) { return x < -20 ? 0.0 : std::exp(x); };
  static constexpr double kBigX = 20;
  double a = 0.5 * chi_square;
  const bool even = !(dof & 1);  // True if dof is an even number.
  const double y = capped_exp(-a);
  double s = even ? y : (2.0 * POZ(-std::sqrt(chi_square)));
  if (dof <= 2) {
    return s;
  }
  chi_square = 0.5 * (dof - 1.0);
  double z = (even ? 1.0 : 0.5);
  if (a > kBigX) {
    double e = (even ? 0.0 : kLogSqrtPi);
    double c = std::log(a);
    while (z <= chi_square) {
      e = std::log(z) + e;
      s += capped_exp(c * z - a - e);
      z += 1.0;
    }
    return s;
  }
  double e = (even ? 1.0 : (kInverseSqrtPi / std::sqrt(a)));
  double c = 0.0;
  while (z <= chi_square) {
    e = e * (a / z);
    c = c + e;
    z += 1.0;
  }
  return c * y + s;
}
References absl::a, absl::c, absl::e, absl::s, absl::x, and y.
Referenced by ChiSquareValue().
ChiSquareValue()
double absl::random_internal::ChiSquareValue (int dof, double p)
Definition at line 106 of file chi_square.cc.
{
  static constexpr double kChiEpsilon =
      0.000001;  // Accuracy of the approximation.
  static constexpr double kChiMax =
      99999.0;  // Maximum chi-squared value.
  const double p_value = 1.0 - p;
  if (dof < 1 || p_value > 1.0) {
    return 0.0;
  }
  if (dof > kLargeDOF) {
    // For large degrees of freedom, use the normal approximation by
    //     Wilson, E. B. and Hilferty, M. M. (1931)
    //                     chi^2 - mean
    //                Z = --------------
    //                        stddev
    const double z = InverseNormalSurvival(p_value);
    const double mean = 1 - 2.0 / (9 * dof);
    const double variance = 2.0 / (9 * dof);
    // Cannot use this method if the variance is 0.
    if (variance != 0) {
      double term = z * std::sqrt(variance) + mean;
      return dof * (term * term * term);
    }
  }
  if (p_value <= 0.0) return kChiMax;
  // Otherwise search for the p value by bisection
  double min_chisq = 0.0;
  double max_chisq = kChiMax;
  double current = dof / std::sqrt(p_value);
  while ((max_chisq - min_chisq) > kChiEpsilon) {
    if (ChiSquarePValue(current, dof) < p_value) {
      max_chisq = current;
    } else {
      min_chisq = current;
    }
    current = (max_chisq + min_chisq) * 0.5;
  }
  return current;
}
References ChiSquarePValue(), InverseNormalSurvival(), and absl::p.
ChiSquareWithExpected()
template<typename Iterator > double absl::random_internal::ChiSquareWithExpected (Iterator begin, Iterator end, double expected)
Definition at line 40 of file chi_square.h.
{
  // Compute the sum and the number of buckets.
  assert(expected >= 10);  // require at least 10 samples per bucket.
  double chi_square = 0;
  for (auto it = begin; it != end; it++) {
    double d = static_cast<double>(*it) - expected;
    chi_square += d * d;
  }
  chi_square = chi_square / expected;
  return chi_square;
}
References absl::d, and end.
ComputeDistributionMoments()
DistributionMoments absl::random_internal::ComputeDistributionMoments (absl::Span< const double > data_points)
Definition at line 39 of file distribution_test_util.cc.
{
  DistributionMoments result;
  // Compute m1
  for (double x : data_points) {
    result.n++;
    result.mean += x;
  }
  result.mean /= static_cast<double>(result.n);
  // Compute m2, m3, m4
  for (double x : data_points) {
    double v = x - result.mean;
    result.variance += v * v;
    result.skewness += v * v * v;
    result.kurtosis += v * v * v * v;
  }
  result.variance /= static_cast<double>(result.n - 1);
  result.skewness /= static_cast<double>(result.n);
  result.skewness /= std::pow(result.variance, 1.5);
  result.kurtosis /= static_cast<double>(result.n);
  result.kurtosis /= std::pow(result.variance, 2.0);
  return result;
  // When validating the min/max count, the following confidence intervals may
  // be of use:
  // 3.291 * stddev = 99.9% CI
  // 2.576 * stddev = 99% CI
  // 1.96 * stddev  = 95% CI
  // 1.65 * stddev  = 90% CI
}
References absl::random_internal::DistributionMoments::kurtosis, absl::random_internal::DistributionMoments::mean, absl::random_internal::DistributionMoments::n, absl::random_internal::DistributionMoments::skewness, absl::v, absl::random_internal::DistributionMoments::variance, and absl::x.
CPUSupportsRandenHwAes()
bool absl::random_internal::CPUSupportsRandenHwAes ()
Definition at line 131 of file randen_detect.cc.
{
#if defined(ABSL_INTERNAL_USE_X86_CPUID)
  // 1. For x86: Use CPUID to detect the required AES instruction set.
  int regs[4];
  __cpuid(reinterpret_cast<int*>(regs), 1);
  return regs[2] & (1 << 25);  // AES
#elif defined(ABSL_INTERNAL_USE_GETAUXVAL)
  // 2. Use getauxval() to read the hardware bits and determine
  // cpu capabilities.
#define AT_HWCAP 16
#define AT_HWCAP2 26
#if defined(ABSL_ARCH_PPC)
  // For Power / PPC: Expect that the cpu supports VCRYPTO
  // See https://members.openpowerfoundation.org/document/dl/576
  // VCRYPTO should be present in POWER8 >= 2.07.
  // Uses Linux kernel constants from arch/powerpc/include/uapi/asm/cputable.h
  static const uint32_t kVCRYPTO = 0x02000000;
  const uint32_t hwcap = GetAuxval(AT_HWCAP2);
  return (hwcap & kVCRYPTO) != 0;
#elif defined(ABSL_ARCH_ARM)
  // For ARM: Require crypto+neon
  // http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0500f/CIHBIBBA.html
  // Uses Linux kernel constants from arch/arm64/include/asm/hwcap.h
  static const uint32_t kNEON = 1 << 12;
  uint32_t hwcap = GetAuxval(AT_HWCAP);
  if ((hwcap & kNEON) == 0) {
    return false;
  }
  // And use it again to detect AES.
  static const uint32_t kAES = 1 << 0;
  const uint32_t hwcap2 = GetAuxval(AT_HWCAP2);
  return (hwcap2 & kAES) != 0;
#elif defined(ABSL_ARCH_AARCH64)
  // For AARCH64: Require crypto+neon
  // http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0500f/CIHBIBBA.html
  static const uint32_t kNEON = 1 << 1;
  static const uint32_t kAES = 1 << 3;
  const uint32_t hwcap = GetAuxval(AT_HWCAP);
  return ((hwcap & kNEON) != 0) && ((hwcap & kAES) != 0);
#endif
#else  // ABSL_INTERNAL_USE_GETAUXVAL
  // 3. By default, assume that the compiler default.
  return ABSL_HAVE_ACCELERATED_AES ? true : false;
#endif
  // NOTE: There are some other techniques that may be worth trying:
  //
  // * Use an environment variable: ABSL_RANDOM_USE_HWAES
  //
  // * Rely on compiler-generated target-based dispatch.
  // Using x86/gcc it might look something like this:
  //
  // int __attribute__((target("aes"))) HasAes() { return 1; }
  // int __attribute__((target("default"))) HasAes() { return 0; }
  //
  // This does not work on all architecture/compiler combinations.
  //
  // * On Linux consider reading /proc/cpuinfo and/or /proc/self/auxv.
  // These files have lines which are easy to parse; for ARM/AARCH64 it is quite
  // easy to find the Features: line and extract aes / neon. Likewise for
  // PPC.
  //
  // * Fork a process and test for SIGILL:
  //
  // * Many architectures have instructions to read the ISA. Unfortunately
  //   most of those require that the code is running in ring 0 /
  //   protected-mode.
  //
  //   There are several examples. e.g. Valgrind detects PPC ISA 2.07:
  //   https://github.com/lu-zero/valgrind/blob/master/none/tests/ppc64/test_isa_2_07_part1.c
  //
  //   MRS <Xt>, ID_AA64ISAR0_EL1 ; Read ID_AA64ISAR0_EL1 into Xt
  //
  //   uint64_t val;
  //   __asm __volatile("mrs %0, id_aa64isar0_el1" :"=&r" (val));
  //
  // * Use a CPUID-style heuristic database.
  //
  // * On Apple (__APPLE__), AES is available on Arm v8.
  //   https://stackoverflow.com/questions/45637888/how-to-determine-armv8-features-at-runtime-on-ios
}
References ABSL_HAVE_ACCELERATED_AES.
Referenced by main().
erfinv()
double absl::random_internal::erfinv (double x)
Definition at line 110 of file distribution_test_util.cc.
{
#if !defined(__EMSCRIPTEN__)
  using std::fma;
#endif
  double w = 0.0;
  double p = 0.0;
  w = -std::log((1.0 - x) * (1.0 + x));
  if (w < 6.250000) {
    w = w - 3.125000;
    p = -3.6444120640178196996e-21;
    p = fma(p, w, -1.685059138182016589e-19);
    p = fma(p, w, 1.2858480715256400167e-18);
    p = fma(p, w, 1.115787767802518096e-17);
    p = fma(p, w, -1.333171662854620906e-16);
    p = fma(p, w, 2.0972767875968561637e-17);
    p = fma(p, w, 6.6376381343583238325e-15);
    p = fma(p, w, -4.0545662729752068639e-14);
    p = fma(p, w, -8.1519341976054721522e-14);
    p = fma(p, w, 2.6335093153082322977e-12);
    p = fma(p, w, -1.2975133253453532498e-11);
    p = fma(p, w, -5.4154120542946279317e-11);
    p = fma(p, w, 1.051212273321532285e-09);
    p = fma(p, w, -4.1126339803469836976e-09);
    p = fma(p, w, -2.9070369957882005086e-08);
    p = fma(p, w, 4.2347877827932403518e-07);
    p = fma(p, w, -1.3654692000834678645e-06);
    p = fma(p, w, -1.3882523362786468719e-05);
    p = fma(p, w, 0.0001867342080340571352);
    p = fma(p, w, -0.00074070253416626697512);
    p = fma(p, w, -0.0060336708714301490533);
    p = fma(p, w, 0.24015818242558961693);
    p = fma(p, w, 1.6536545626831027356);
  } else if (w < 16.000000) {
    w = std::sqrt(w) - 3.250000;
    p = 2.2137376921775787049e-09;
    p = fma(p, w, 9.0756561938885390979e-08);
    p = fma(p, w, -2.7517406297064545428e-07);
    p = fma(p, w, 1.8239629214389227755e-08);
    p = fma(p, w, 1.5027403968909827627e-06);
    p = fma(p, w, -4.013867526981545969e-06);
    p = fma(p, w, 2.9234449089955446044e-06);
    p = fma(p, w, 1.2475304481671778723e-05);
    p = fma(p, w, -4.7318229009055733981e-05);
    p = fma(p, w, 6.8284851459573175448e-05);
    p = fma(p, w, 2.4031110387097893999e-05);
    p = fma(p, w, -0.0003550375203628474796);
    p = fma(p, w, 0.00095328937973738049703);
    p = fma(p, w, -0.0016882755560235047313);
    p = fma(p, w, 0.0024914420961078508066);
    p = fma(p, w, -0.0037512085075692412107);
    p = fma(p, w, 0.005370914553590063617);
    p = fma(p, w, 1.0052589676941592334);
    p = fma(p, w, 3.0838856104922207635);
  } else {
    w = std::sqrt(w) - 5.000000;
    p = -2.7109920616438573243e-11;
    p = fma(p, w, -2.5556418169965252055e-10);
    p = fma(p, w, 1.5076572693500548083e-09);
    p = fma(p, w, -3.7894654401267369937e-09);
    p = fma(p, w, 7.6157012080783393804e-09);
    p = fma(p, w, -1.4960026627149240478e-08);
    p = fma(p, w, 2.9147953450901080826e-08);
    p = fma(p, w, -6.7711997758452339498e-08);
    p = fma(p, w, 2.2900482228026654717e-07);
    p = fma(p, w, -9.9298272942317002539e-07);
    p = fma(p, w, 4.5260625972231537039e-06);
    p = fma(p, w, -1.9681778105531670567e-05);
    p = fma(p, w, 7.5995277030017761139e-05);
    p = fma(p, w, -0.00021503011930044477347);
    p = fma(p, w, -0.00013871931833623122026);
    p = fma(p, w, 1.0103004648645343977);
    p = fma(p, w, 4.8499064014085844221);
  }
  return p * x;
}
References absl::p, and absl::x.
Referenced by InverseNormalSurvival().
GenerateRealFromBits()
template<typename RealType , typename SignedTag = GeneratePositiveTag, bool IncludeZero = true> RealType absl::random_internal::GenerateRealFromBits (uint64_t bits, int exp_bias = 0) inline
Definition at line 70 of file generate_real.h.
{
  using real_type = RealType;
  using uint_type = absl::conditional_t<std::is_same<real_type, float>::value,
                                        uint32_t, uint64_t>;
  static_assert(
      (std::is_same<double, real_type>::value ||
       std::is_same<float, real_type>::value),
      "GenerateRealFromBits must be parameterized by either float or double.");
  static_assert(sizeof(uint_type) == sizeof(real_type),
                "Mismatched unsinged and real types.");
  static_assert((std::numeric_limits<real_type>::is_iec559 &&
                 std::numeric_limits<real_type>::radix == 2),
                "RealType representation is not IEEE 754 binary.");
  static_assert((std::is_same<SignedTag, GeneratePositiveTag>::value ||
                 std::is_same<SignedTag, GenerateNegativeTag>::value ||
                 std::is_same<SignedTag, GenerateSignedTag>::value),
                "");
  static constexpr int kExp = std::numeric_limits<real_type>::digits - 1;
  static constexpr uint_type kMask = (static_cast<uint_type>(1) << kExp) - 1u;
  static constexpr int kUintBits = sizeof(uint_type) * 8;
  int exp = exp_bias + int{std::numeric_limits<real_type>::max_exponent - 2};
  // Determine the sign bit.
  // Depending on the SignedTag, this may use the left-most bit
  // or it may be a constant value.
  uint_type sign = std::is_same<SignedTag, GenerateNegativeTag>::value
                       ? (static_cast<uint_type>(1) << (kUintBits - 1))
                       : 0;
  if (std::is_same<SignedTag, GenerateSignedTag>::value) {
    if (std::is_same<uint_type, uint64_t>::value) {
      sign = bits & uint64_t{0x8000000000000000};
    }
    if (std::is_same<uint_type, uint32_t>::value) {
      const uint64_t tmp = bits & uint64_t{0x8000000000000000};
      sign = static_cast<uint32_t>(tmp >> 32);
    }
    // adjust the bits and the exponent to account for removing
    // the leading bit.
    bits = bits & uint64_t{0x7FFFFFFFFFFFFFFF};
    exp++;
  }
  if (IncludeZero) {
    if (bits == 0u) return 0;
  }
  // Number of leading zeros is mapped to the exponent: 2^-clz
  // bits is 0..01xxxxxx. After shifting, we're left with 1xxx...0..0
  int clz = countl_zero(bits);
  bits <<= (IncludeZero ? clz : (clz & 63));  // remove 0-bits.
  exp -= clz;                                 // set the exponent.
  bits >>= (63 - kExp);
  // Construct the 32-bit or 64-bit IEEE 754 floating-point value from
  // the individual fields: sign, exp, mantissa(bits).
  uint_type val = sign | (static_cast<uint_type>(exp) << kExp) |
                  (static_cast<uint_type>(bits) & kMask);
  // bit_cast to the output-type
  real_type result;
  memcpy(static_cast<void*>(&result), static_cast<const void*>(&val),
         sizeof(result));
  return result;
}
References absl::countl_zero(), and absl::u.
Referenced by absl::exponential_distribution< RealType >::operator()(), absl::poisson_distribution< IntType >::operator()(), absl::uniform_real_distribution< RealType >::operator()(), and absl::random_internal::gaussian_distribution_base::zignor().
GetSaltMaterial()
absl::optional< uint32_t > absl::random_internal::GetSaltMaterial ()
Definition at line 248 of file seed_material.cc.
{
  // Salt must be common for all generators within the same process so read it
  // only once and store in static variable.
  static const auto salt_material = []() -> absl::optional<uint32_t> {
    uint32_t salt_value = 0;
    if (random_internal::ReadSeedMaterialFromOSEntropy(
            MakeSpan(&salt_value, 1))) {
      return salt_value;
    }
    return absl::nullopt;
  }();
  return salt_material;
}
References absl::MakeSpan(), and ReadSeedMaterialFromOSEntropy().
HasRandenHwAesImplementation()
bool absl::random_internal::HasRandenHwAesImplementation ()
Definition at line 54 of file randen_hwaes.cc.
{ return false; }
Referenced by main().
InitDiscreteDistribution()
std::vector< std::pair< double, size_t > > absl::random_internal::InitDiscreteDistribution (std::vector< double > * probabilities)
Definition at line 23 of file discrete_distribution.cc.
{
  // The empty-case should already be handled by the constructor.
  assert(probabilities);
  assert(!probabilities->empty());
  // Step 1. Normalize the input probabilities to 1.0.
  double sum = std::accumulate(std::begin(*probabilities),
                               std::end(*probabilities), 0.0);
  if (std::fabs(sum - 1.0) > 1e-6) {
    // Scale `probabilities` only when the sum is too far from 1.0.  Scaling
    // unconditionally will alter the probabilities slightly.
    for (double& item : *probabilities) {
      item = item / sum;
    }
  }
  // Step 2. At this point `probabilities` is set to the conditional
  // probabilities of each element which sum to 1.0, to within reasonable error.
  // These values are used to construct the proportional probability tables for
  // the selection phases of Walker's Aliasing algorithm.
  //
  // To construct the table, pick an element which is under-full (i.e., an
  // element for which `(*probabilities)[i] < 1.0/n`), and pair it with an
  // element which is over-full (i.e., an element for which
  // `(*probabilities)[i] > 1.0/n`). The smaller value can always be retired.
  // The larger may still be greater than 1.0/n, or may now be less than 1.0/n,
  // and put back onto the appropriate collection.
  const size_t n = probabilities->size();
  std::vector<std::pair<double, size_t>> q;
  q.reserve(n);
  std::vector<size_t> over;
  std::vector<size_t> under;
  size_t idx = 0;
  for (const double item : *probabilities) {
    assert(item >= 0);
    const double v = item * n;
    q.emplace_back(v, 0);
    if (v < 1.0) {
      under.push_back(idx++);
    } else {
      over.push_back(idx++);
    }
  }
  while (!over.empty() && !under.empty()) {
    auto lo = under.back();
    under.pop_back();
    auto hi = over.back();
    over.pop_back();
    q[lo].second = hi;
    const double r = q[hi].first - (1.0 - q[lo].first);
    q[hi].first = r;
    if (r < 1.0) {
      under.push_back(hi);
    } else {
      over.push_back(hi);
    }
  }
  // Due to rounding errors, there may be un-paired elements in either
  // collection; these should all be values near 1.0.  For these values, set `q`
  // to 1.0 and set the alternate to the identity.
  for (auto i : over) {
    q[i] = {1.0, i};
  }
  for (auto i : under) {
    q[i] = {1.0, i};
  }
  return q;
}
References absl::e, absl::i, absl::n, r, and absl::v.
IntegerLog2()
template<typename UIntType > UIntType absl::random_internal::IntegerLog2 (UIntType n) constexpr
Definition at line 52 of file fast_uniform_bits.h.
{
  return (n <= 1) ? 0 : 1 + IntegerLog2(n >> 1);
}
References IntegerLog2(), and absl::n.
Referenced by IntegerLog2(), and NumBits().
IntLog2Ceil()
int absl::random_internal::IntLog2Ceil (uint64_t n) inline
Definition at line 39 of file fastmath.h.
{
  return (n <= 1) ? 0 : (64 - countl_zero(n - 1));
}
References absl::countl_zero(), and absl::n.
IntLog2Floor()
int absl::random_internal::IntLog2Floor (uint64_t n) inline
Definition at line 36 of file fastmath.h.
{
  return (n <= 1) ? 0 : (63 - countl_zero(n));
}
References absl::countl_zero(), and absl::n.
InverseNormalSurvival()
double absl::random_internal::InverseNormalSurvival (double x)
Definition at line 80 of file distribution_test_util.cc.
{
  // inv_sf(u) = -sqrt(2) * erfinv(2u-1)
  static constexpr double kSqrt2 = 1.4142135623730950488;
  return -kSqrt2 * absl::random_internal::erfinv(2 * x - 1.0);
}
References erfinv(), and absl::x.
Referenced by ChiSquareValue(), and MaxErrorTolerance().
is_uniform_range_valid() [1/2]
template<typename FloatType > absl::enable_if_t< std::is_floating_point< FloatType >::value, bool > absl::random_internal::is_uniform_range_valid (FloatType a, FloatType b)
Definition at line 199 of file uniform_helper.h.
{
  return a <= b && std::isfinite(b - a);
}
References absl::a, and b.
Referenced by absl::Uniform(), absl::Uniform(), absl::Uniform(), and absl::Uniform().
is_uniform_range_valid() [2/2]
template<typename IntType > absl::enable_if_t< IsIntegral< IntType >::value, bool > absl::random_internal::is_uniform_range_valid (IntType a, IntType b)
Definition at line 205 of file uniform_helper.h.
{
  return a <= b;
}
References absl::a, and b.
IsPowerOfTwoOrZero()
template<typename UIntType > bool absl::random_internal::IsPowerOfTwoOrZero (UIntType n) constexpr
Definition at line 33 of file fast_uniform_bits.h.
{
  return (n == 0) || ((n & (n - 1)) == 0);
}
References absl::n.
make_istream_state_saver() [1/2]
template<typename CharT , typename Traits > istream_state_saver< std::basic_istream< CharT, Traits > > absl::random_internal::make_istream_state_saver (std::basic_istream< CharT, Traits > & is, std::ios_base::fmtflags flags = std::ios_base::dec | std::ios_base::scientific | std::ios_base::skipws)
Definition at line 149 of file iostream_state_saver.h.
{
  using result_type = istream_state_saver<std::basic_istream<CharT, Traits>>;
  return result_type(is, flags);
}
Referenced by absl::operator>>(), absl::operator>>(), absl::operator>>(), absl::operator>>(), absl::operator>>(), absl::operator>>(), absl::operator>>(), absl::operator>>(), absl::operator>>(), and absl::operator>>().
make_istream_state_saver() [2/2]
template<typename T > absl::enable_if_t<!std::is_base_of< std::ios_base, T >::value, null_state_saver< T > > absl::random_internal::make_istream_state_saver (T & is, std::ios_base::fmtflags flags = std::ios_base::dec)
Definition at line 161 of file iostream_state_saver.h.
{
  using result_type = null_state_saver<T>;
  return result_type(is, flags);
}
make_ostream_state_saver() [1/2]
template<typename CharT , typename Traits > ostream_state_saver< std::basic_ostream< CharT, Traits > > absl::random_internal::make_ostream_state_saver (std::basic_ostream< CharT, Traits > & os, std::ios_base::fmtflags flags = std::ios_base::dec | std::ios_base::left | std::ios_base::scientific)
Definition at line 82 of file iostream_state_saver.h.
{
  using result_type = ostream_state_saver<std::basic_ostream<CharT, Traits>>;
  return result_type(os, flags, os.widen(' '));
}
make_ostream_state_saver() [2/2]
template<typename T > absl::enable_if_t<!std::is_base_of< std::ios_base, T >::value, null_state_saver< T > > absl::random_internal::make_ostream_state_saver (T & is, std::ios_base::fmtflags flags = std::ios_base::dec)
Definition at line 96 of file iostream_state_saver.h.
{
  std::cerr << "null_state_saver";
  using result_type = null_state_saver<T>;
  return result_type(is, flags);
}
MakeSaltedSeedSeq() [1/2]
template<typename SSeq , typename EnableIf = absl::enable_if_t<is_salted_seed_seq<SSeq>::value>> SSeq absl::random_internal::MakeSaltedSeedSeq (SSeq && seq)
Definition at line 145 of file salted_seed_seq.h.
{
  return SSeq(std::forward<SSeq>(seq));
}
MakeSaltedSeedSeq() [2/2]
template<typename SSeq , typename EnableIf = absl::enable_if_t<!is_salted_seed_seq<SSeq>::value>> SaltedSeedSeq< typename std::decay< SSeq >::type > absl::random_internal::MakeSaltedSeedSeq (SSeq && seq)
Definition at line 152 of file salted_seed_seq.h.
{
  using sseq_type = typename std::decay<SSeq>::type;
  using result_type = typename sseq_type::result_type;
  absl::InlinedVector<result_type, 8> data;
  seq.param(std::back_inserter(data));
  return SaltedSeedSeq<sseq_type>(data.begin(), data.end());
}
References data.
MaskFromShift()
template<typename UIntType > UIntType absl::random_internal::MaskFromShift (size_t n) constexpr
Definition at line 68 of file fast_uniform_bits.h.
{
  return ((n % std::numeric_limits<UIntType>::digits) == 0)
             ? ~UIntType{0}
             : (UIntType{1} << n) - UIntType{1};
}
References absl::n.
MaxErrorTolerance()
double absl::random_internal::MaxErrorTolerance (double acceptance_probability)
Definition at line 409 of file distribution_test_util.cc.
{
  double one_sided_pvalue = 0.5 * (1.0 - acceptance_probability);
  const double max_err = InverseNormalSurvival(one_sided_pvalue);
  ABSL_ASSERT(max_err > 0);
  return max_err;
}
References ABSL_ASSERT, and InverseNormalSurvival().
MixIntoSeedMaterial()
void absl::random_internal::MixIntoSeedMaterial (absl::Span< const uint32_t > sequence, absl::Span< uint32_t > seed_material)
Definition at line 216 of file seed_material.cc.
{
  // Algorithm is based on code available at
  // https://gist.github.com/imneme/540829265469e673d045
  constexpr uint32_t kInitVal = 0x43b0d7e5;
  constexpr uint32_t kHashMul = 0x931e8875;
  constexpr uint32_t kMixMulL = 0xca01f9dd;
  constexpr uint32_t kMixMulR = 0x4973f715;
  constexpr uint32_t kShiftSize = sizeof(uint32_t) * 8 / 2;
  uint32_t hash_const = kInitVal;
  auto hash = [&](uint32_t value) {
    value ^= hash_const;
    hash_const *= kHashMul;
    value *= hash_const;
    value ^= value >> kShiftSize;
    return value;
  };
  auto mix = [&](uint32_t x, uint32_t y) {
    uint32_t result = kMixMulL * x - kMixMulR * y;
    result ^= result >> kShiftSize;
    return result;
  };
  for (const auto& seq_val : sequence) {
    for (auto& elem : seed_material) {
      elem = mix(elem, hash(seq_val));
    }
  }
}
References hash, value, absl::x, and y.
MultiplyU128ToU256()
U256 absl::random_internal::MultiplyU128ToU256 (uint128 a, uint128 b) inline
Definition at line 58 of file wide_multiply.h.
{
  const uint128 a00 = static_cast<uint64_t>(a);
  const uint128 a64 = a >> 64;
  const uint128 b00 = static_cast<uint64_t>(b);
  const uint128 b64 = b >> 64;
  const uint128 c00 = a00 * b00;
  const uint128 c64a = a00 * b64;
  const uint128 c64b = a64 * b00;
  const uint128 c128 = a64 * b64;
  const uint64_t carry =
      static_cast<uint64_t>(((c00 >> 64) + static_cast<uint64_t>(c64a) +
                             static_cast<uint64_t>(c64b)) >>
                            64);
  return {c128 + (c64a >> 64) + (c64b >> 64) + carry,
          c00 + (c64a << 64) + (c64b << 64)};
}
References absl::a, and b.
Referenced by absl::random_internal::wide_multiply< uint128 >::multiply().
Near()
bool absl::random_internal::Near (absl::string_view msg, double actual, double expected, double bound)
Definition at line 86 of file distribution_test_util.cc.
{
  assert(bound > 0.0);
  double delta = fabs(expected - actual);
  if (delta < bound) {
    return true;
  }
  std::string formatted = absl::StrCat(
      msg, " actual=", actual, " expected=", expected, " err=", delta / bound);
  ABSL_RAW_LOG(INFO, "%s", formatted.c_str());
  return false;
}
References ABSL_RAW_LOG, INFO, absl::msg, and absl::StrCat().
NumBits()
template<typename URBG > size_t absl::random_internal::NumBits () constexpr
Definition at line 59 of file fast_uniform_bits.h.
{
  return RangeSize<URBG>() == 0
             ? std::numeric_limits<typename URBG::result_type>::digits
             : IntegerLog2(RangeSize<URBG>());
}
References IntegerLog2(), and RangeSize().
operator!=()
template<typename T > bool absl::random_internal::operator!= (TagTypeCompare< T > , TagTypeCompare< T >) constexpr
Definition at line 48 of file uniform_helper.h.
{
  return false;
}
operator<<()
std::ostream & absl::random_internal::operator<< (std::ostream & os, const DistributionMoments & moments)
Definition at line 74 of file distribution_test_util.cc.
{
  return os << absl::StrFormat("mean=%f, stddev=%f, skewness=%f, kurtosis=%f",
                               moments.mean, std::sqrt(moments.variance),
                               moments.skewness, moments.kurtosis);
}
References absl::random_internal::DistributionMoments::kurtosis, absl::random_internal::DistributionMoments::mean, absl::random_internal::DistributionMoments::skewness, absl::StrFormat(), and absl::random_internal::DistributionMoments::variance.
operator==()
template<typename T > bool absl::random_internal::operator== (TagTypeCompare< T > , TagTypeCompare< T >) constexpr
Definition at line 43 of file uniform_helper.h.
{
  // Tags are mono-states. They always compare equal.
  return true;
}
RangeSize()
template<typename URBG > URBG::result_type absl::random_internal::RangeSize () constexpr
Definition at line 41 of file fast_uniform_bits.h.
{
  using result_type = typename URBG::result_type;
  static_assert((URBG::max)() != (URBG::min)(), "URBG range cannot be 0.");
  return ((URBG::max)() == (std::numeric_limits<result_type>::max)() &&
          (URBG::min)() == std::numeric_limits<result_type>::lowest())
             ? result_type{0}
             : ((URBG::max)() - (URBG::min)() + result_type{1});
}
Referenced by NumBits().
read_floating_point()
template<typename FloatType , typename IStream > FloatType absl::random_internal::read_floating_point (IStream & is) inline
Definition at line 222 of file iostream_state_saver.h.
{
  static_assert(std::is_floating_point<FloatType>::value, "");
  FloatType dest;
  is >> dest;
  // Parsing a double value may report a subnormal value as an error
  // despite being able to represent it.
  // See https://stackoverflow.com/q/52410931/3286653
  // It may also report an underflow when parsing DOUBLE_MIN as an
  // ERANGE error, as the parsed value may be smaller than DOUBLE_MIN
  // and rounded up.
  // See: https://stackoverflow.com/q/42005462
  if (is.fail() &&
      (std::fabs(dest) == (std::numeric_limits<FloatType>::min)() ||
       std::fpclassify(dest) == FP_SUBNORMAL)) {
    is.clear(is.rdstate() & (~std::ios_base::failbit));
  }
  return dest;
}
Referenced by absl::operator>>(), absl::operator>>(), absl::operator>>(), absl::operator>>(), absl::operator>>(), absl::operator>>(), and absl::operator>>().
ReadSeedMaterialFromOSEntropy()
ABSL_MUST_USE_RESULT bool absl::random_internal::ReadSeedMaterialFromOSEntropy (absl::Span< uint32_t > values)
Definition at line 205 of file seed_material.cc.
{
  assert(values.data() != nullptr);
  if (values.data() == nullptr) {
    return false;
  }
  if (values.empty()) {
    return true;
  }
  return ReadSeedMaterialFromOSEntropyImpl(values);
}
References values.
Referenced by GetSaltMaterial().
ReadSeedMaterialFromURBG()
template<typename URBG > ABSL_MUST_USE_RESULT bool absl::random_internal::ReadSeedMaterialFromURBG (URBG * urbg, absl::Span< uint32_t > values)
Definition at line 68 of file seed_material.h.
{
  random_internal::FastUniformBits<uint32_t> distr;
  assert(urbg != nullptr && values.data() != nullptr);
  if (urbg == nullptr || values.data() == nullptr) {
    return false;
  }
  for (uint32_t& seed_value : values) {
    seed_value = distr(*urbg);
  }
  return true;
}
References values.
Referenced by absl::CreateSeedSeqFrom().
RequiredSuccessProbability()
double absl::random_internal::RequiredSuccessProbability (const double p_fail, const int num_trials)
Definition at line 397 of file distribution_test_util.cc.
{
  double p = std::exp(std::log(1.0 - p_fail) / static_cast<double>(num_trials));
  ABSL_ASSERT(p > 0);
  return p;
}
References ABSL_ASSERT, and absl::p.
SeedBitsToBlocks()
size_t absl::random_internal::SeedBitsToBlocks (size_t seed_size) constexpr
Definition at line 35 of file seed_material.h.
{
  return (seed_size + 31) / 32;
}
StirlingLogFactorial()
double absl::random_internal::StirlingLogFactorial (double n) inline
Definition at line 43 of file fastmath.h.
{
  assert(n >= 1);
  // Using Stirling's approximation.
  constexpr double kLog2PI = 1.83787706640934548356;
  const double logn = std::log(n);
  const double ninv = 1.0 / static_cast<double>(n);
  return n * logn - n + 0.5 * (kLog2PI + logn) + (1.0 / 12.0) * ninv -
         (1.0 / 360.0) * ninv * ninv * ninv;
}
References absl::n.
Referenced by absl::poisson_distribution< IntType >::operator()(), and absl::poisson_distribution< IntType >::param_type::param_type().
ThrowSeedGenException()
void absl::random_internal::ThrowSeedGenException ()
Definition at line 35 of file seed_gen_exception.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  throw absl::SeedGenException();
#else
  std::cerr << kExceptionMessage << std::endl;
  std::terminate();
#endif
}
Referenced by absl::CreateSeedSeqFrom().
uniform_lower_bound() [1/3]
template<typename FloatType , typename Tag > absl::enable_if_t< absl::conjunction< std::is_floating_point< FloatType >, absl::disjunction< std::is_same< Tag, IntervalOpenClosedTag >, std::is_same< Tag, IntervalOpenOpenTag > > >::value, FloatType > absl::random_internal::uniform_lower_bound (Tag , FloatType a, FloatType b)
Definition at line 118 of file uniform_helper.h.
{
  return std::nextafter(a, b);
}
References absl::a, and b.
uniform_lower_bound() [2/3]
template<typename IntType , typename Tag > absl::enable_if_t< absl::conjunction< IsIntegral< IntType >, absl::disjunction< std::is_same< Tag, IntervalOpenClosedTag >, std::is_same< Tag, IntervalOpenOpenTag > > >::value, IntType > absl::random_internal::uniform_lower_bound (Tag , IntType a, IntType)
Definition at line 107 of file uniform_helper.h.
{
  return a < (std::numeric_limits<IntType>::max)() ? (a + 1) : a;
}
References absl::a.
Referenced by absl::Uniform(), absl::Uniform(), absl::Uniform(), and absl::Uniform().
uniform_lower_bound() [3/3]
template<typename NumType , typename Tag > absl::enable_if_t< absl::disjunction< std::is_same< Tag, IntervalClosedClosedTag >, std::is_same< Tag, IntervalClosedOpenTag > >::value, NumType > absl::random_internal::uniform_lower_bound (Tag , NumType a, NumType)
Definition at line 127 of file uniform_helper.h.
{
  return a;
}
References absl::a.
uniform_upper_bound() [1/4]
template<typename FloatType , typename Tag > absl::enable_if_t< absl::conjunction< std::is_floating_point< FloatType >, absl::disjunction< std::is_same< Tag, IntervalClosedOpenTag >, std::is_same< Tag, IntervalOpenOpenTag > > >::value, FloatType > absl::random_internal::uniform_upper_bound (Tag , FloatType , FloatType b)
Definition at line 149 of file uniform_helper.h.
{
  return b;
}
References b.
uniform_upper_bound() [2/4]
template<typename FloatType , typename Tag > absl::enable_if_t< absl::conjunction< std::is_floating_point< FloatType >, absl::disjunction< std::is_same< Tag, IntervalClosedClosedTag >, std::is_same< Tag, IntervalOpenClosedTag > > >::value, FloatType > absl::random_internal::uniform_upper_bound (Tag , FloatType , FloatType b)
Definition at line 171 of file uniform_helper.h.
{
  return std::nextafter(b, (std::numeric_limits<FloatType>::max)());
}
References b.
uniform_upper_bound() [3/4]
template<typename IntType , typename Tag > absl::enable_if_t< absl::conjunction< IsIntegral< IntType >, absl::disjunction< std::is_same< Tag, IntervalClosedOpenTag >, std::is_same< Tag, IntervalOpenOpenTag > > >::value, IntType > absl::random_internal::uniform_upper_bound (Tag , IntType , IntType b)
Definition at line 138 of file uniform_helper.h.
{
  return b > (std::numeric_limits<IntType>::min)() ? (b - 1) : b;
}
References b.
Referenced by absl::Uniform(), absl::Uniform(), absl::Uniform(), and absl::Uniform().
uniform_upper_bound() [4/4]
template<typename IntType , typename Tag > absl::enable_if_t< absl::conjunction< IsIntegral< IntType >, absl::disjunction< std::is_same< Tag, IntervalClosedClosedTag >, std::is_same< Tag, IntervalOpenClosedTag > > >::value, IntType > absl::random_internal::uniform_upper_bound (Tag , IntType , IntType b)
Definition at line 160 of file uniform_helper.h.
{
  return b;
}
References b.
ZScore()
double absl::random_internal::ZScore (double expected_mean, const DistributionMoments & moments)
Definition at line 403 of file distribution_test_util.cc.
{
  return (moments.mean - expected_mean) /
         (std::sqrt(moments.variance) /
          std::sqrt(static_cast<double>(moments.n)));
}
References absl::random_internal::DistributionMoments::mean, absl::random_internal::DistributionMoments::n, and absl::random_internal::DistributionMoments::variance.
Variable Documentation
kChiSquared
const char absl::random_internal::kChiSquared[] = "chi-squared" constexpr
Definition at line 35 of file chi_square.h.
kEntropyBitsNeeded
size_t absl::random_internal::kEntropyBitsNeeded = 256 constexpr
Definition at line 41 of file seed_material.h.
kEntropyBlocksNeeded
size_t absl::random_internal::kEntropyBlocksNeeded constexpr
Initial value:
=
    random_internal::SeedBitsToBlocks(kEntropyBitsNeeded)
Definition at line 45 of file seed_material.h.
Referenced by absl::CreateSeedSeqFrom().
kRandenRoundKeys
const unsigned char absl::random_internal::kRandenRoundKeys
Definition at line 275 of file randen_round_keys.cc.
{
    0x44, 0x73, 0x70, 0x03, 0x2E, 0x8A, 0x19, 0x13, 0xD3, 0x08, 0xA3, 0x85,
    0x88, 0x6A, 0x3F, 0x24, 0x89, 0x6C, 0x4E, 0xEC, 0x98, 0xFA, 0x2E, 0x08,
    0xD0, 0x31, 0x9F, 0x29, 0x22, 0x38, 0x09, 0xA4, 0x6C, 0x0C, 0xE9, 0x34,
    0xCF, 0x66, 0x54, 0xBE, 0x77, 0x13, 0xD0, 0x38, 0xE6, 0x21, 0x28, 0x45,
    0x17, 0x09, 0x47, 0xB5, 0xB5, 0xD5, 0x84, 0x3F, 0xDD, 0x50, 0x7C, 0xC9,
    0xB7, 0x29, 0xAC, 0xC0, 0xAC, 0xB5, 0xDF, 0x98, 0xA6, 0x0B, 0x31, 0xD1,
    0x1B, 0xFB, 0x79, 0x89, 0xD9, 0xD5, 0x16, 0x92, 0x96, 0x7E, 0x26, 0x6A,
    0xED, 0xAF, 0xE1, 0xB8, 0xB7, 0xDF, 0x1A, 0xD0, 0xDB, 0x72, 0xFD, 0x2F,
    0xF7, 0x6C, 0x91, 0xB3, 0x47, 0x99, 0xA1, 0x24, 0x99, 0x7F, 0x2C, 0xF1,
    0x45, 0x90, 0x7C, 0xBA, 0x69, 0x4E, 0x57, 0x71, 0xD8, 0x20, 0x69, 0x63,
    0x16, 0xFC, 0x8E, 0x85, 0xE2, 0xF2, 0x01, 0x08, 0x58, 0xB6, 0x8E, 0x72,
    0x8F, 0x74, 0x95, 0x0D, 0x7E, 0x3D, 0x93, 0xF4, 0xA3, 0xFE, 0x58, 0xA4,
    0xB5, 0x59, 0x5A, 0xC2, 0x1D, 0xA4, 0x54, 0x7B, 0xEE, 0x4A, 0x15, 0x82,
    0x58, 0xCD, 0x8B, 0x71, 0xF0, 0x85, 0x60, 0x28, 0x23, 0xB0, 0xD1, 0xC5,
    0x13, 0x60, 0xF2, 0x2A, 0x39, 0xD5, 0x30, 0x9C, 0x0E, 0x18, 0x3A, 0x60,
    0xB0, 0xDC, 0x79, 0x8E, 0xEF, 0x38, 0xDB, 0xB8, 0x18, 0x79, 0x41, 0xCA,
    0x27, 0x4B, 0x31, 0xBD, 0xC1, 0x77, 0x15, 0xD7, 0x3E, 0x8A, 0x1E, 0xB0,
    0x8B, 0x0E, 0x9E, 0x6C, 0x94, 0xAB, 0x55, 0xAA, 0xF3, 0x25, 0x55, 0xE6,
    0x60, 0x5C, 0x60, 0x55, 0xDA, 0x2F, 0xAF, 0x78, 0xB6, 0x10, 0xAB, 0x2A,
    0x6A, 0x39, 0xCA, 0x55, 0x40, 0x14, 0xE8, 0x63, 0x62, 0x98, 0x48, 0x57,
    0x93, 0xE9, 0x72, 0x7C, 0xAF, 0x86, 0x54, 0xA1, 0xCE, 0xE8, 0x41, 0x11,
    0x34, 0x5C, 0xCC, 0xB4, 0xF6, 0x31, 0x18, 0x74, 0x5D, 0xC5, 0xA9, 0x2B,
    0x2A, 0xBC, 0x6F, 0x63, 0x11, 0x14, 0xEE, 0xB3, 0x5C, 0xCF, 0x24, 0x6C,
    0x33, 0xBA, 0xD6, 0xAF, 0x1E, 0x93, 0x87, 0x9B, 0x16, 0x3E, 0x5C, 0xCE,
    0xAF, 0xB9, 0x4B, 0x6B, 0x98, 0x48, 0x8F, 0x3B, 0x77, 0x86, 0x95, 0x28,
    0x81, 0x53, 0x32, 0x7A, 0x91, 0xA9, 0x21, 0xFB, 0xCC, 0x09, 0xD8, 0x61,
    0x93, 0x21, 0x28, 0x66, 0x1B, 0xE8, 0xBF, 0xC4, 0xB1, 0x75, 0x85, 0xE9,
    0x5D, 0x5D, 0x84, 0xEF, 0x32, 0x80, 0xEC, 0x5D, 0x60, 0xAC, 0x7C, 0x48,
    0xC5, 0xAC, 0x96, 0xD3, 0x81, 0x3E, 0x89, 0x23, 0x88, 0x1B, 0x65, 0xEB,
    0x02, 0x23, 0x26, 0xDC, 0x04, 0x20, 0x84, 0xA4, 0x82, 0x44, 0x0B, 0x2E,
    0x39, 0x42, 0xF4, 0x83, 0xF3, 0x6F, 0x6D, 0x0F, 0x9A, 0x6C, 0xE9, 0xF6,
    0x42, 0x68, 0xC6, 0x21, 0x5E, 0x9B, 0x1F, 0x9E, 0x4A, 0xF0, 0xC8, 0x69,
    0x68, 0x2F, 0x54, 0xD8, 0xD2, 0xA0, 0x51, 0x6A, 0xF0, 0x88, 0xD3, 0xAB,
    0x61, 0x9C, 0x0C, 0x67, 0xE4, 0x3B, 0x7A, 0x13, 0x6C, 0x0B, 0xEF, 0x6E,
    0xA3, 0x33, 0x51, 0xAB, 0x28, 0xA7, 0x0F, 0x96, 0x76, 0x01, 0xAF, 0x39,
    0x1D, 0x65, 0xF1, 0xA1, 0x98, 0x2A, 0xFB, 0x7E, 0x50, 0xF0, 0x3B, 0xBA,
    0xB4, 0x9F, 0x6F, 0x45, 0x19, 0x86, 0xEE, 0x8C, 0x88, 0x0E, 0x43, 0x82,
    0x3E, 0x59, 0xCA, 0x66, 0x73, 0x20, 0xC1, 0x85, 0xD8, 0x75, 0x6F, 0xE0,
    0xBE, 0x5E, 0x8B, 0x3B, 0xC3, 0xA5, 0x84, 0x7D, 0x06, 0x77, 0x3F, 0x36,
    0x62, 0xAA, 0xD3, 0x4E, 0xA6, 0x6A, 0xC1, 0x56, 0x9F, 0x44, 0x1A, 0x40,
    0x48, 0x12, 0x0A, 0xD0, 0x24, 0xD7, 0xD0, 0x37, 0x3D, 0x02, 0x9B, 0x42,
    0x72, 0xDF, 0xFE, 0x1B, 0x7B, 0x1B, 0x99, 0x80, 0xC9, 0x72, 0x53, 0x07,
    0x9B, 0xC0, 0xF1, 0x49, 0xD3, 0xEA, 0x0F, 0xDB, 0x3B, 0x4C, 0x79, 0xB6,
    0x1A, 0x50, 0xFE, 0xE3, 0xF7, 0xDE, 0xE8, 0xF6, 0xD8, 0x79, 0xD4, 0x25,
    0xC4, 0x60, 0x9F, 0x40, 0xB6, 0x4F, 0xA9, 0xC1, 0xBA, 0x06, 0xC0, 0x04,
    0xBD, 0xE0, 0x6C, 0x97, 0xB5, 0x53, 0x6C, 0x3E, 0xAF, 0x6F, 0xFB, 0x68,
    0x63, 0x24, 0x6A, 0x19, 0xC2, 0x9E, 0x5C, 0x5E, 0x2C, 0x95, 0x30, 0x9B,
    0x1F, 0x51, 0xFC, 0x6D, 0x6F, 0xEC, 0x52, 0x3B, 0xEB, 0xB2, 0x39, 0x13,
    0xFD, 0x4A, 0x33, 0xDE, 0x04, 0xD0, 0xE3, 0xBE, 0x09, 0xBD, 0x5E, 0xAF,
    0x44, 0x45, 0x81, 0xCC, 0x0F, 0x74, 0xC8, 0x45, 0x57, 0xA8, 0xCB, 0xC0,
    0xB3, 0x4B, 0x2E, 0x19, 0x07, 0x28, 0x0F, 0x66, 0x0A, 0x32, 0x60, 0x1A,
    0xBD, 0xC0, 0x79, 0x55, 0xDB, 0xFB, 0xD3, 0xB9, 0x39, 0x5F, 0x0B, 0xD2,
    0xCC, 0xA3, 0x1F, 0xFB, 0xFE, 0x25, 0x9F, 0x67, 0x79, 0x72, 0x2C, 0x40,
    0xC6, 0x00, 0xA1, 0xD6, 0x15, 0x6B, 0x61, 0xFD, 0xDF, 0x16, 0x75, 0x3C,
    0xF8, 0x22, 0x32, 0xDB, 0xF8, 0xE9, 0xA5, 0x8E, 0x60, 0x87, 0x23, 0xFD,
    0xFA, 0xB5, 0x3D, 0x32, 0xAB, 0x52, 0x05, 0xAD, 0xC8, 0x1E, 0x50, 0x2F,
    0xA0, 0x8C, 0x6F, 0xCA, 0xBB, 0x57, 0x5C, 0x9E, 0x82, 0xDF, 0x00, 0x3E,
    0x48, 0x7B, 0x31, 0x53, 0xC3, 0xFF, 0x7E, 0x28, 0xF6, 0xA8, 0x42, 0xD5,
    0xDB, 0x69, 0x17, 0xDF, 0x2E, 0x56, 0x87, 0x1A, 0xC8, 0x58, 0xCA, 0xBB,
    0xB0, 0x27, 0x5B, 0x69, 0x73, 0x55, 0x4F, 0x8C, 0xC6, 0x32, 0x67, 0xAC,
    0xB8, 0x83, 0x21, 0xFD, 0x98, 0x3D, 0xFA, 0x10, 0xA0, 0x11, 0xF0, 0xB8,
    0x5D, 0xA3, 0xFF, 0xE1, 0x65, 0x45, 0xF8, 0xB6, 0x79, 0xE4, 0x53, 0x9A,
    0x5B, 0xD3, 0xD1, 0x2D, 0x6C, 0xB5, 0xFC, 0x4A, 0x33, 0x7E, 0xCB, 0xA4,
    0xDA, 0xF2, 0xDD, 0xE1, 0x90, 0x97, 0xFB, 0x4B, 0xBC, 0x49, 0x8E, 0xD2,
    0x01, 0x4C, 0x77, 0x36, 0xDA, 0xCA, 0x20, 0xEF, 0xE8, 0xC6, 0xE4, 0xCE,
    0x41, 0x13, 0xFB, 0x62, 0x98, 0x91, 0x90, 0xAE, 0x4D, 0xDA, 0xDB, 0x95,
    0xB4, 0x1F, 0xF1, 0x2B, 0xFE, 0x9E, 0x7E, 0xD0, 0xE0, 0x25, 0xC7, 0xAF,
    0xD0, 0xD1, 0x8E, 0xD0, 0xA0, 0xD5, 0x93, 0x6B, 0x71, 0x8E, 0xAD, 0xEA,
    0x64, 0x2B, 0x12, 0xF2, 0xFB, 0xE2, 0xF6, 0x8F, 0xB7, 0x94, 0x75, 0x8E,
    0x2F, 0x5B, 0x3C, 0x8E, 0x1C, 0xC3, 0x8F, 0x68, 0xA0, 0x5E, 0xAD, 0x4F,
    0x1C, 0xF0, 0x0D, 0x90, 0x12, 0xB8, 0x88, 0x88, 0x77, 0x17, 0x0E, 0xBE,
    0x18, 0x22, 0x2F, 0x2F, 0xAD, 0xC1, 0xA8, 0xB3, 0x91, 0xF1, 0xCF, 0xD1,
    0xE8, 0x74, 0x6F, 0xB5, 0x0F, 0xCC, 0xA0, 0xE5, 0xA1, 0x1F, 0x02, 0x8B,
    0xFE, 0x2D, 0x75, 0xEA, 0xB7, 0xE0, 0x13, 0xFD, 0xE0, 0x4F, 0xA8, 0xB4,
    0x99, 0xE2, 0x89, 0xCE, 0xD6, 0xF3, 0xAC, 0x18, 0x05, 0x77, 0x95, 0x80,
    0x66, 0xA2, 0x5F, 0x16, 0xD9, 0xA8, 0xAD, 0xD2, 0x81, 0x3B, 0xC4, 0x7C,
    0x86, 0xFA, 0xB5, 0x77, 0x65, 0x20, 0xAD, 0xE6, 0x77, 0x14, 0x1A, 0x21,
    0x14, 0x73, 0xCC, 0x93, 0xA0, 0x89, 0x3E, 0x7B, 0x0C, 0xAF, 0xCD, 0xEB,
    0xCF, 0x35, 0x9D, 0xFB, 0xF5, 0x42, 0x54, 0xC7, 0x5E, 0xB3, 0x71, 0x20,
    0x2D, 0x0E, 0x25, 0x00, 0x49, 0x7E, 0x1E, 0xAE, 0xD3, 0x1B, 0x41, 0xD6,
    0x1E, 0xB9, 0x09, 0xF0, 0x9B, 0x36, 0x64, 0x24, 0xAF, 0xE0, 0xB8, 0x57,
    0xBB, 0x00, 0x68, 0x22, 0x7F, 0x53, 0x5A, 0xD9, 0x89, 0x43, 0xC1, 0x78,
    0xAA, 0xA6, 0xDF, 0x59, 0x1D, 0x91, 0x63, 0x55, 0xA9, 0xCF, 0x95, 0x62,
    0x76, 0x03, 0x26, 0x83, 0xC5, 0xB9, 0xE5, 0x02, 0xA2, 0x5B, 0x7D, 0x20,
    0x4A, 0xA9, 0x14, 0x7B, 0xCA, 0x2D, 0x47, 0xB3, 0x41, 0x4A, 0x73, 0x4E,
    0x68, 0x19, 0xC8, 0x11, 0xE4, 0xC6, 0x9B, 0xBC, 0x3F, 0x57, 0x0F, 0xD6,
    0x15, 0x29, 0x53, 0x9A, 0x52, 0x00, 0x51, 0x1B, 0x1F, 0xE9, 0x1B, 0x57,
    0xB5, 0x6F, 0xBA, 0x08, 0x00, 0x74, 0xE6, 0x81, 0x76, 0xA4, 0x60, 0x2B,
    0xB6, 0xF9, 0xB9, 0xE7, 0x21, 0x65, 0x63, 0xB6, 0x15, 0xD9, 0x0D, 0x2A,
    0x6B, 0xEC, 0x96, 0xF2, 0xA1, 0x8F, 0x9F, 0xA9, 0x5D, 0x2D, 0xB0, 0x53,
    0x64, 0x56, 0x85, 0xC5, 0x2E, 0x05, 0x34, 0xFF, 0x44, 0x29, 0xB3, 0xB5,
    0xE9, 0x70, 0x7A, 0x4B, 0x6A, 0x07, 0x85, 0x6E, 0x99, 0x47, 0xBA, 0x08,
    0x7D, 0xDF, 0xA7, 0x49, 0xB0, 0xA6, 0x6E, 0xAD, 0x23, 0x26, 0x19, 0xC4,
    0x2E, 0x09, 0x75, 0xDB, 0xFF, 0x18, 0x9A, 0x69, 0x71, 0x8C, 0xAA, 0xEC,
    0x66, 0xB2, 0xED, 0x8F, 0xB8, 0x60, 0xEE, 0x9C, 0x29, 0x4C, 0x09, 0x75,
    0xA5, 0x02, 0x36, 0x19, 0xE1, 0x9E, 0xB1, 0xC2, 0x6C, 0x52, 0x64, 0x56,
    0x65, 0x9D, 0x42, 0x5B, 0x9A, 0x98, 0x54, 0x3F, 0x3E, 0x3A, 0x18, 0xE4,
    0x40, 0x13, 0x59, 0xA0, 0xF5, 0x30, 0xE8, 0xEF, 0x07, 0x9C, 0xD2, 0xA1,
    0xD6, 0x3F, 0xF7, 0x99, 0xD6, 0xE4, 0x8F, 0x6B, 0x26, 0xEB, 0x70, 0x84,
    0x86, 0x20, 0xDD, 0x4C, 0xC1, 0x5D, 0x25, 0xF0, 0xE6, 0x38, 0x2D, 0x4D,
    0xC9, 0xEF, 0xBA, 0x3E, 0x3F, 0x6B, 0x68, 0x09, 0x5E, 0xCC, 0x1E, 0x02,
    0xC6, 0xE9, 0x82, 0x63, 0x86, 0xE2, 0xA0, 0x52, 0x84, 0x35, 0x7F, 0x68,
    0xA1, 0x70, 0x6A, 0x6B, 0x14, 0x18, 0x97, 0x3C, 0x5C, 0xAE, 0xDE, 0x7F,
    0x1C, 0x84, 0x07, 0x3E, 0x37, 0x07, 0x50, 0xAA, 0x05, 0x53, 0x9C, 0xB7,
    0x0D, 0x0C, 0x50, 0xF0, 0x37, 0xDA, 0x3A, 0xB0, 0xB8, 0xF2, 0x16, 0x57,
    0xEC, 0x44, 0x7D, 0x8E, 0xB2, 0x74, 0xB5, 0x3C, 0x1A, 0xF5, 0x0C, 0xAE,
    0xFF, 0xB3, 0x00, 0x02, 0x04, 0x1F, 0x1C, 0xF0, 0xF6, 0x2F, 0xA9, 0x7C,
    0xF9, 0x13, 0x91, 0xD1, 0xBD, 0x21, 0x09, 0xDC, 0x58, 0x7A, 0x83, 0x25,
    0xDC, 0xDA, 0xC2, 0x37, 0x81, 0xE5, 0xE5, 0x3A, 0x01, 0x47, 0xF5, 0x22,
    0x73, 0x47, 0x32, 0x94, 0x0E, 0x03, 0xD0, 0x0F, 0x46, 0x61, 0x44, 0xA9,
    0xA7, 0xDD, 0xF3, 0x9A, 0x34, 0x76, 0xB5, 0xC8, 0x2F, 0x0E, 0xEA, 0x3B,
    0x99, 0xCD, 0x38, 0xE2, 0x41, 0x1E, 0x75, 0xA4, 0x3E, 0xC7, 0xC8, 0xEC,
    0x08, 0xB9, 0x6D, 0x4F, 0x38, 0x8B, 0x54, 0x4E, 0x31, 0xB3, 0x3E, 0x18,
    0xA1, 0xBB, 0x80, 0x32, 0x79, 0x7C, 0x97, 0x24, 0x90, 0x12, 0xB8, 0x2C,
    0xBF, 0x04, 0x0A, 0xF6, 0x03, 0x0D, 0x42, 0x6F, 0x10, 0x08, 0x93, 0xD9,
    0x1F, 0x77, 0x9A, 0xDE, 0xAF, 0x89, 0xAF, 0xBC, 0x72, 0xB0, 0x79, 0x56,
    0x24, 0x71, 0x6B, 0x2E, 0x1F, 0x72, 0x12, 0x55, 0x2E, 0x3F, 0xCF, 0xDC,
    0x12, 0xAE, 0x8B, 0xB3, 0x17, 0xDA, 0x08, 0x74, 0x18, 0x47, 0x58, 0x7A,
    0x87, 0xCD, 0x84, 0x9F, 0xE6, 0xDD, 0x1A, 0x50, 0xFA, 0x1D, 0x85, 0xDB,
    0x3A, 0xEC, 0x7A, 0xEC, 0x8C, 0x7D, 0x4B, 0xE9, 0xBC, 0x9A, 0x9F, 0xBC,
    0x08, 0xD8, 0x15, 0x32, 0x47, 0x18, 0x1C, 0xEF, 0xD2, 0xC3, 0x64, 0xC4,
    0x66, 0x43, 0x09, 0x63, 0x51, 0xC4, 0x65, 0x2A, 0x43, 0x4D, 0xA1, 0x12,
    0x16, 0xBA, 0xC2, 0x24, 0x37, 0x3B, 0x43, 0xDD, 0x55, 0x4E, 0x31, 0x10,
    0x9E, 0xF8, 0xDF, 0x71, 0xDD, 0xE4, 0x3A, 0x13, 0x02, 0x00, 0x94, 0x50,
    0x6B, 0xC7, 0xA3, 0xD7, 0xF1, 0x56, 0x35, 0x04, 0x9B, 0x19, 0x11, 0x5F,
    0xD6, 0x77, 0xAC, 0x81, 0xFA, 0xFB, 0xF1, 0x97, 0xED, 0xE6, 0x8F, 0xF2,
    0x09, 0xA5, 0x24, 0x59, 0x3B, 0x18, 0x11, 0x3C, 0xB1, 0x6F, 0xE9, 0xEA,
    0x70, 0x45, 0xE3, 0x86, 0x6E, 0x3C, 0x15, 0x1E, 0x2C, 0xBF, 0xBA, 0x9E,
    0xFA, 0x06, 0x3D, 0x4E, 0x1C, 0xE7, 0x1F, 0x77, 0xB3, 0x2A, 0x3E, 0x5A,
    0x0A, 0x5E, 0x0E, 0x86, 0x25, 0xC8, 0x66, 0x52, 0xD6, 0x89, 0x3E, 0x80,
    0x0F, 0x1D, 0xE7, 0x99, 0xB9, 0xDC, 0x65, 0x29, 0x78, 0xEA, 0xE2, 0x94,
    0xBA, 0x0E, 0x15, 0xC6, 0x6A, 0xB3, 0x10, 0x9C, 0x78, 0xC9, 0x4C, 0x2E,
    0x3D, 0x2B, 0x1D, 0x36, 0xA7, 0x4E, 0xF7, 0xF2, 0xF4, 0x2D, 0x0A, 0x1E,
    0x53, 0x3C, 0xFC, 0xA6, 0xB6, 0x12, 0x13, 0xF7, 0x08, 0xA7, 0x23, 0x52,
    0x60, 0x79, 0xC2, 0x19, 0x0F, 0x26, 0x39, 0x19, 0x83, 0xC8, 0x7B, 0xA6,
    0x95, 0x45, 0xBC, 0xE3, 0x66, 0x1F, 0xC3, 0xEA, 0x6E, 0xFE, 0xAD, 0xEB,
    0xA5, 0x5A, 0x6C, 0xBE, 0xEF, 0xDD, 0x32, 0xC3, 0x28, 0xFF, 0x8C, 0x01,
    0xD1, 0x37, 0x7F, 0xB1, 0x3B, 0x95, 0x2F, 0xDB, 0x0F, 0xA5, 0xCE, 0xEE,
    0x02, 0x97, 0xAB, 0x68, 0x85, 0x21, 0x58, 0x65, 0x70, 0x61, 0x07, 0x29,
    0x28, 0xB6, 0x21, 0x15, 0x84, 0x2F, 0x6E, 0x5B, 0xAD, 0x7D, 0xEF, 0x2A,
    0x96, 0xBD, 0x61, 0xEB, 0x30, 0xA8, 0xCC, 0x13, 0x10, 0x15, 0x9F, 0x61,
    0x75, 0x47, 0xDD, 0xEC, 0x39, 0xA2, 0x70, 0x4C, 0x90, 0x5C, 0x73, 0xB5,
    0xCF, 0x63, 0x03, 0xAA, 0x1E, 0xFE, 0x34, 0x03, 0xA7, 0x2C, 0x62, 0x60,
    0xBC, 0x86, 0xCC, 0xEE, 0x14, 0xDE, 0xAA, 0xCB, 0x0B, 0x9E, 0x9E, 0xD5,
    0xCA, 0xF0, 0xBD, 0x19, 0xAF, 0x1E, 0x8B, 0x64, 0x6E, 0x84, 0xF3, 0xB2,
    0xAB, 0x5C, 0xAB, 0x9C, 0xB3, 0xB4, 0x2A, 0x3C, 0x32, 0x5A, 0x68, 0x40,
    0x50, 0xBB, 0x5A, 0x65, 0xB9, 0x69, 0x23, 0xA0, 0x99, 0xA0, 0x5F, 0x87,
    0x19, 0x0B, 0x54, 0x9B, 0xF7, 0xB8, 0x21, 0xC0, 0xD5, 0xE9, 0x9E, 0x31,
    0x77, 0x2D, 0xE3, 0x97, 0x9A, 0x88, 0x37, 0xF8, 0xA8, 0x7D, 0x3D, 0x62,
    0x7E, 0x99, 0xF7, 0x95, 0xD6, 0x1F, 0xE6, 0xC7, 0x29, 0x88, 0x35, 0x0E,
    0x81, 0x12, 0x68, 0x16, 0x5F, 0x93, 0xED, 0x11, 0x63, 0x72, 0x22, 0x1B,
    0xA5, 0x84, 0xF5, 0x57, 0x99, 0xBA, 0x58, 0x78, 0xA1, 0xDF, 0xDE, 0x96,
    0x54, 0x30, 0x2E, 0x53, 0xEB, 0x0A, 0xB3, 0xCD, 0x96, 0x46, 0xC2, 0x1A,
    0xFF, 0xC3, 0x83, 0x9B, 0xEA, 0xFF, 0xC6, 0x34, 0xEF, 0xF2, 0xEB, 0x58,
    0x28, 0x31, 0xBC, 0x6D, 0xE4, 0x48, 0xD9, 0x8F, 0xE3, 0xB7, 0x64, 0xE8,
    0xD9, 0x14, 0x4A, 0x5D, 0x73, 0x3C, 0x7C, 0xEE, 0x61, 0xED, 0x28, 0xFE,
    0xEA, 0xAB, 0xAA, 0xA3, 0xB6, 0xE2, 0xEE, 0x45, 0xE0, 0x13, 0x3E, 0x20,
    0x14, 0x5D, 0x10, 0x42, 0xB5, 0xBB, 0x6A, 0xEF, 0x42, 0xF4, 0x42, 0xC7,
    0xD0, 0x4F, 0xCB, 0xFA, 0x15, 0x4F, 0x6C, 0xDB, 0xC7, 0x4D, 0x85, 0x86,
    0x9E, 0x79, 0x1E, 0xD8, 0x05, 0x21, 0xCD, 0x41, 0x1D, 0x3B, 0x4F, 0x65,
    0x46, 0x26, 0x8D, 0x5B, 0xF2, 0xA1, 0x62, 0xCF, 0x50, 0x62, 0x81, 0x3D,
    0x6A, 0x47, 0x4B, 0xE4, 0x92, 0x74, 0xCB, 0x69, 0xC3, 0x24, 0x15, 0x7F,
    0xA3, 0xB6, 0xC7, 0xC1, 0xA0, 0x83, 0x88, 0xFC, 0x9D, 0x48, 0x19, 0xAD,
    0x00, 0xBF, 0x5B, 0x09, 0x85, 0xB2, 0x92, 0x56, 0x0B, 0x8A, 0x84, 0x47,
    0xEA, 0xF5, 0x55, 0x0C, 0x2A, 0x8D, 0x42, 0x58, 0x00, 0x0D, 0x82, 0x23,
    0x74, 0xB1, 0x62, 0x14, 0x41, 0x7E, 0x93, 0x8D, 0x92, 0xF0, 0x72, 0x33,
    0x61, 0x70, 0x3F, 0x23, 0x3E, 0xF4, 0xAD, 0x1D, 0x60, 0x74, 0xEE, 0xCB,
    0x59, 0x37, 0xDE, 0x7C, 0xDB, 0x3B, 0x22, 0x6C, 0xF1, 0xEC, 0x5F, 0xD6,
    0x9E, 0x50, 0xF8, 0x19, 0x84, 0x80, 0x07, 0xA6, 0x6E, 0x32, 0x77, 0xCE,
    0xA7, 0xF2, 0x85, 0x40, 0xC2, 0x06, 0x0C, 0xC5, 0xAA, 0xA7, 0x69, 0xA9,
    0x35, 0x97, 0xD9, 0x61, 0x55, 0xD8, 0xEF, 0xE8, 0x84, 0x34, 0x45, 0xC3,
    0x2E, 0x7A, 0x44, 0x9E, 0xDC, 0xCA, 0x0B, 0x80, 0xFC, 0xAB, 0x04, 0x5A,
    0xCD, 0x88, 0x55, 0x10, 0xD3, 0xDB, 0x73, 0xDB, 0xC9, 0x9E, 0x1E, 0x0E,
    0x05, 0x67, 0xD5, 0xFD, 0xD8, 0x38, 0x3E, 0x71, 0x65, 0x34, 0xC4, 0xC5,
    0x40, 0x43, 0x67, 0xE3, 0x79, 0xDA, 0x5F, 0x67, 0x4A, 0x3D, 0xB0, 0x8F,
    0xE7, 0x21, 0x3E, 0x15, 0x20, 0xFF, 0x6D, 0xF1, 0x9E, 0xF8, 0x28, 0x3D,
    0xF7, 0x40, 0x81, 0x94, 0x68, 0x5A, 0x3D, 0xE9, 0xF7, 0xAD, 0x83, 0xDB,
    0x2B, 0x9F, 0xE3, 0xE6, 0xF7, 0xD4, 0x02, 0x76, 0xF7, 0x20, 0x15, 0x41,
    0x34, 0x29, 0x69, 0x94, 0x1C, 0x26, 0x4C, 0xF6, 0x6A, 0xF4, 0x20, 0x33,
    0x71, 0x24, 0x08, 0xD4, 0x68, 0x00, 0xA1, 0xD4, 0x2E, 0x6B, 0xF4, 0xBC,
    0x46, 0x45, 0x24, 0x97, 0x2E, 0xF6, 0x39, 0x1E, 0xAF, 0x61, 0x00, 0x50,
    0xB7, 0xD4, 0xB7, 0x43,
};
Referenced by absl::random_internal::RandenSlow::GetKeys().
kRandenRoundKeysBE
const unsigned char absl::random_internal::kRandenRoundKeysBE
Definition at line 90 of file randen_round_keys.cc.
{
    0x24, 0x3F, 0x6A, 0x88, 0x85, 0xA3, 0x08, 0xD3, 0x13, 0x19, 0x8A, 0x2E,
    0x03, 0x70, 0x73, 0x44, 0xA4, 0x09, 0x38, 0x22, 0x29, 0x9F, 0x31, 0xD0,
    0x08, 0x2E, 0xFA, 0x98, 0xEC, 0x4E, 0x6C, 0x89, 0x45, 0x28, 0x21, 0xE6,
    0x38, 0xD0, 0x13, 0x77, 0xBE, 0x54, 0x66, 0xCF, 0x34, 0xE9, 0x0C, 0x6C,
    0xC0, 0xAC, 0x29, 0xB7, 0xC9, 0x7C, 0x50, 0xDD, 0x3F, 0x84, 0xD5, 0xB5,
    0xB5, 0x47, 0x09, 0x17, 0x92, 0x16, 0xD5, 0xD9, 0x89, 0x79, 0xFB, 0x1B,
    0xD1, 0x31, 0x0B, 0xA6, 0x98, 0xDF, 0xB5, 0xAC, 0x2F, 0xFD, 0x72, 0xDB,
    0xD0, 0x1A, 0xDF, 0xB7, 0xB8, 0xE1, 0xAF, 0xED, 0x6A, 0x26, 0x7E, 0x96,
    0xBA, 0x7C, 0x90, 0x45, 0xF1, 0x2C, 0x7F, 0x99, 0x24, 0xA1, 0x99, 0x47,
    0xB3, 0x91, 0x6C, 0xF7, 0x08, 0x01, 0xF2, 0xE2, 0x85, 0x8E, 0xFC, 0x16,
    0x63, 0x69, 0x20, 0xD8, 0x71, 0x57, 0x4E, 0x69, 0xA4, 0x58, 0xFE, 0xA3,
    0xF4, 0x93, 0x3D, 0x7E, 0x0D, 0x95, 0x74, 0x8F, 0x72, 0x8E, 0xB6, 0x58,
    0x71, 0x8B, 0xCD, 0x58, 0x82, 0x15, 0x4A, 0xEE, 0x7B, 0x54, 0xA4, 0x1D,
    0xC2, 0x5A, 0x59, 0xB5, 0x9C, 0x30, 0xD5, 0x39, 0x2A, 0xF2, 0x60, 0x13,
    0xC5, 0xD1, 0xB0, 0x23, 0x28, 0x60, 0x85, 0xF0, 0xCA, 0x41, 0x79, 0x18,
    0xB8, 0xDB, 0x38, 0xEF, 0x8E, 0x79, 0xDC, 0xB0, 0x60, 0x3A, 0x18, 0x0E,
    0x6C, 0x9E, 0x0E, 0x8B, 0xB0, 0x1E, 0x8A, 0x3E, 0xD7, 0x15, 0x77, 0xC1,
    0xBD, 0x31, 0x4B, 0x27, 0x78, 0xAF, 0x2F, 0xDA, 0x55, 0x60, 0x5C, 0x60,
    0xE6, 0x55, 0x25, 0xF3, 0xAA, 0x55, 0xAB, 0x94, 0x57, 0x48, 0x98, 0x62,
    0x63, 0xE8, 0x14, 0x40, 0x55, 0xCA, 0x39, 0x6A, 0x2A, 0xAB, 0x10, 0xB6,
    0xB4, 0xCC, 0x5C, 0x34, 0x11, 0x41, 0xE8, 0xCE, 0xA1, 0x54, 0x86, 0xAF,
    0x7C, 0x72, 0xE9, 0x93, 0xB3, 0xEE, 0x14, 0x11, 0x63, 0x6F, 0xBC, 0x2A,
    0x2B, 0xA9, 0xC5, 0x5D, 0x74, 0x18, 0x31, 0xF6, 0xCE, 0x5C, 0x3E, 0x16,
    0x9B, 0x87, 0x93, 0x1E, 0xAF, 0xD6, 0xBA, 0x33, 0x6C, 0x24, 0xCF, 0x5C,
    0x7A, 0x32, 0x53, 0x81, 0x28, 0x95, 0x86, 0x77, 0x3B, 0x8F, 0x48, 0x98,
    0x6B, 0x4B, 0xB9, 0xAF, 0xC4, 0xBF, 0xE8, 0x1B, 0x66, 0x28, 0x21, 0x93,
    0x61, 0xD8, 0x09, 0xCC, 0xFB, 0x21, 0xA9, 0x91, 0x48, 0x7C, 0xAC, 0x60,
    0x5D, 0xEC, 0x80, 0x32, 0xEF, 0x84, 0x5D, 0x5D, 0xE9, 0x85, 0x75, 0xB1,
    0xDC, 0x26, 0x23, 0x02, 0xEB, 0x65, 0x1B, 0x88, 0x23, 0x89, 0x3E, 0x81,
    0xD3, 0x96, 0xAC, 0xC5, 0x0F, 0x6D, 0x6F, 0xF3, 0x83, 0xF4, 0x42, 0x39,
    0x2E, 0x0B, 0x44, 0x82, 0xA4, 0x84, 0x20, 0x04, 0x69, 0xC8, 0xF0, 0x4A,
    0x9E, 0x1F, 0x9B, 0x5E, 0x21, 0xC6, 0x68, 0x42, 0xF6, 0xE9, 0x6C, 0x9A,
    0x67, 0x0C, 0x9C, 0x61, 0xAB, 0xD3, 0x88, 0xF0, 0x6A, 0x51, 0xA0, 0xD2,
    0xD8, 0x54, 0x2F, 0x68, 0x96, 0x0F, 0xA7, 0x28, 0xAB, 0x51, 0x33, 0xA3,
    0x6E, 0xEF, 0x0B, 0x6C, 0x13, 0x7A, 0x3B, 0xE4, 0xBA, 0x3B, 0xF0, 0x50,
    0x7E, 0xFB, 0x2A, 0x98, 0xA1, 0xF1, 0x65, 0x1D, 0x39, 0xAF, 0x01, 0x76,
    0x66, 0xCA, 0x59, 0x3E, 0x82, 0x43, 0x0E, 0x88, 0x8C, 0xEE, 0x86, 0x19,
    0x45, 0x6F, 0x9F, 0xB4, 0x7D, 0x84, 0xA5, 0xC3, 0x3B, 0x8B, 0x5E, 0xBE,
    0xE0, 0x6F, 0x75, 0xD8, 0x85, 0xC1, 0x20, 0x73, 0x40, 0x1A, 0x44, 0x9F,
    0x56, 0xC1, 0x6A, 0xA6, 0x4E, 0xD3, 0xAA, 0x62, 0x36, 0x3F, 0x77, 0x06,
    0x1B, 0xFE, 0xDF, 0x72, 0x42, 0x9B, 0x02, 0x3D, 0x37, 0xD0, 0xD7, 0x24,
    0xD0, 0x0A, 0x12, 0x48, 0xDB, 0x0F, 0xEA, 0xD3, 0x49, 0xF1, 0xC0, 0x9B,
    0x07, 0x53, 0x72, 0xC9, 0x80, 0x99, 0x1B, 0x7B, 0x25, 0xD4, 0x79, 0xD8,
    0xF6, 0xE8, 0xDE, 0xF7, 0xE3, 0xFE, 0x50, 0x1A, 0xB6, 0x79, 0x4C, 0x3B,
    0x97, 0x6C, 0xE0, 0xBD, 0x04, 0xC0, 0x06, 0xBA, 0xC1, 0xA9, 0x4F, 0xB6,
    0x40, 0x9F, 0x60, 0xC4, 0x5E, 0x5C, 0x9E, 0xC2, 0x19, 0x6A, 0x24, 0x63,
    0x68, 0xFB, 0x6F, 0xAF, 0x3E, 0x6C, 0x53, 0xB5, 0x13, 0x39, 0xB2, 0xEB,
    0x3B, 0x52, 0xEC, 0x6F, 0x6D, 0xFC, 0x51, 0x1F, 0x9B, 0x30, 0x95, 0x2C,
    0xCC, 0x81, 0x45, 0x44, 0xAF, 0x5E, 0xBD, 0x09, 0xBE, 0xE3, 0xD0, 0x04,
    0xDE, 0x33, 0x4A, 0xFD, 0x66, 0x0F, 0x28, 0x07, 0x19, 0x2E, 0x4B, 0xB3,
    0xC0, 0xCB, 0xA8, 0x57, 0x45, 0xC8, 0x74, 0x0F, 0xD2, 0x0B, 0x5F, 0x39,
    0xB9, 0xD3, 0xFB, 0xDB, 0x55, 0x79, 0xC0, 0xBD, 0x1A, 0x60, 0x32, 0x0A,
    0xD6, 0xA1, 0x00, 0xC6, 0x40, 0x2C, 0x72, 0x79, 0x67, 0x9F, 0x25, 0xFE,
    0xFB, 0x1F, 0xA3, 0xCC, 0x8E, 0xA5, 0xE9, 0xF8, 0xDB, 0x32, 0x22, 0xF8,
    0x3C, 0x75, 0x16, 0xDF, 0xFD, 0x61, 0x6B, 0x15, 0x2F, 0x50, 0x1E, 0xC8,
    0xAD, 0x05, 0x52, 0xAB, 0x32, 0x3D, 0xB5, 0xFA, 0xFD, 0x23, 0x87, 0x60,
    0x53, 0x31, 0x7B, 0x48, 0x3E, 0x00, 0xDF, 0x82, 0x9E, 0x5C, 0x57, 0xBB,
    0xCA, 0x6F, 0x8C, 0xA0, 0x1A, 0x87, 0x56, 0x2E, 0xDF, 0x17, 0x69, 0xDB,
    0xD5, 0x42, 0xA8, 0xF6, 0x28, 0x7E, 0xFF, 0xC3, 0xAC, 0x67, 0x32, 0xC6,
    0x8C, 0x4F, 0x55, 0x73, 0x69, 0x5B, 0x27, 0xB0, 0xBB, 0xCA, 0x58, 0xC8,
    0xE1, 0xFF, 0xA3, 0x5D, 0xB8, 0xF0, 0x11, 0xA0, 0x10, 0xFA, 0x3D, 0x98,
    0xFD, 0x21, 0x83, 0xB8, 0x4A, 0xFC, 0xB5, 0x6C, 0x2D, 0xD1, 0xD3, 0x5B,
    0x9A, 0x53, 0xE4, 0x79, 0xB6, 0xF8, 0x45, 0x65, 0xD2, 0x8E, 0x49, 0xBC,
    0x4B, 0xFB, 0x97, 0x90, 0xE1, 0xDD, 0xF2, 0xDA, 0xA4, 0xCB, 0x7E, 0x33,
    0x62, 0xFB, 0x13, 0x41, 0xCE, 0xE4, 0xC6, 0xE8, 0xEF, 0x20, 0xCA, 0xDA,
    0x36, 0x77, 0x4C, 0x01, 0xD0, 0x7E, 0x9E, 0xFE, 0x2B, 0xF1, 0x1F, 0xB4,
    0x95, 0xDB, 0xDA, 0x4D, 0xAE, 0x90, 0x91, 0x98, 0xEA, 0xAD, 0x8E, 0x71,
    0x6B, 0x93, 0xD5, 0xA0, 0xD0, 0x8E, 0xD1, 0xD0, 0xAF, 0xC7, 0x25, 0xE0,
    0x8E, 0x3C, 0x5B, 0x2F, 0x8E, 0x75, 0x94, 0xB7, 0x8F, 0xF6, 0xE2, 0xFB,
    0xF2, 0x12, 0x2B, 0x64, 0x88, 0x88, 0xB8, 0x12, 0x90, 0x0D, 0xF0, 0x1C,
    0x4F, 0xAD, 0x5E, 0xA0, 0x68, 0x8F, 0xC3, 0x1C, 0xD1, 0xCF, 0xF1, 0x91,
    0xB3, 0xA8, 0xC1, 0xAD, 0x2F, 0x2F, 0x22, 0x18, 0xBE, 0x0E, 0x17, 0x77,
    0xEA, 0x75, 0x2D, 0xFE, 0x8B, 0x02, 0x1F, 0xA1, 0xE5, 0xA0, 0xCC, 0x0F,
    0xB5, 0x6F, 0x74, 0xE8, 0x18, 0xAC, 0xF3, 0xD6, 0xCE, 0x89, 0xE2, 0x99,
    0xB4, 0xA8, 0x4F, 0xE0, 0xFD, 0x13, 0xE0, 0xB7, 0x7C, 0xC4, 0x3B, 0x81,
    0xD2, 0xAD, 0xA8, 0xD9, 0x16, 0x5F, 0xA2, 0x66, 0x80, 0x95, 0x77, 0x05,
    0x93, 0xCC, 0x73, 0x14, 0x21, 0x1A, 0x14, 0x77, 0xE6, 0xAD, 0x20, 0x65,
    0x77, 0xB5, 0xFA, 0x86, 0xC7, 0x54, 0x42, 0xF5, 0xFB, 0x9D, 0x35, 0xCF,
    0xEB, 0xCD, 0xAF, 0x0C, 0x7B, 0x3E, 0x89, 0xA0, 0xD6, 0x41, 0x1B, 0xD3,
    0xAE, 0x1E, 0x7E, 0x49, 0x00, 0x25, 0x0E, 0x2D, 0x20, 0x71, 0xB3, 0x5E,
    0x22, 0x68, 0x00, 0xBB, 0x57, 0xB8, 0xE0, 0xAF, 0x24, 0x64, 0x36, 0x9B,
    0xF0, 0x09, 0xB9, 0x1E, 0x55, 0x63, 0x91, 0x1D, 0x59, 0xDF, 0xA6, 0xAA,
    0x78, 0xC1, 0x43, 0x89, 0xD9, 0x5A, 0x53, 0x7F, 0x20, 0x7D, 0x5B, 0xA2,
    0x02, 0xE5, 0xB9, 0xC5, 0x83, 0x26, 0x03, 0x76, 0x62, 0x95, 0xCF, 0xA9,
    0x11, 0xC8, 0x19, 0x68, 0x4E, 0x73, 0x4A, 0x41, 0xB3, 0x47, 0x2D, 0xCA,
    0x7B, 0x14, 0xA9, 0x4A, 0x1B, 0x51, 0x00, 0x52, 0x9A, 0x53, 0x29, 0x15,
    0xD6, 0x0F, 0x57, 0x3F, 0xBC, 0x9B, 0xC6, 0xE4, 0x2B, 0x60, 0xA4, 0x76,
    0x81, 0xE6, 0x74, 0x00, 0x08, 0xBA, 0x6F, 0xB5, 0x57, 0x1B, 0xE9, 0x1F,
    0xF2, 0x96, 0xEC, 0x6B, 0x2A, 0x0D, 0xD9, 0x15, 0xB6, 0x63, 0x65, 0x21,
    0xE7, 0xB9, 0xF9, 0xB6, 0xFF, 0x34, 0x05, 0x2E, 0xC5, 0x85, 0x56, 0x64,
    0x53, 0xB0, 0x2D, 0x5D, 0xA9, 0x9F, 0x8F, 0xA1, 0x08, 0xBA, 0x47, 0x99,
    0x6E, 0x85, 0x07, 0x6A, 0x4B, 0x7A, 0x70, 0xE9, 0xB5, 0xB3, 0x29, 0x44,
    0xDB, 0x75, 0x09, 0x2E, 0xC4, 0x19, 0x26, 0x23, 0xAD, 0x6E, 0xA6, 0xB0,
    0x49, 0xA7, 0xDF, 0x7D, 0x9C, 0xEE, 0x60, 0xB8, 0x8F, 0xED, 0xB2, 0x66,
    0xEC, 0xAA, 0x8C, 0x71, 0x69, 0x9A, 0x18, 0xFF, 0x56, 0x64, 0x52, 0x6C,
    0xC2, 0xB1, 0x9E, 0xE1, 0x19, 0x36, 0x02, 0xA5, 0x75, 0x09, 0x4C, 0x29,
    0xA0, 0x59, 0x13, 0x40, 0xE4, 0x18, 0x3A, 0x3E, 0x3F, 0x54, 0x98, 0x9A,
    0x5B, 0x42, 0x9D, 0x65, 0x6B, 0x8F, 0xE4, 0xD6, 0x99, 0xF7, 0x3F, 0xD6,
    0xA1, 0xD2, 0x9C, 0x07, 0xEF, 0xE8, 0x30, 0xF5, 0x4D, 0x2D, 0x38, 0xE6,
    0xF0, 0x25, 0x5D, 0xC1, 0x4C, 0xDD, 0x20, 0x86, 0x84, 0x70, 0xEB, 0x26,
    0x63, 0x82, 0xE9, 0xC6, 0x02, 0x1E, 0xCC, 0x5E, 0x09, 0x68, 0x6B, 0x3F,
    0x3E, 0xBA, 0xEF, 0xC9, 0x3C, 0x97, 0x18, 0x14, 0x6B, 0x6A, 0x70, 0xA1,
    0x68, 0x7F, 0x35, 0x84, 0x52, 0xA0, 0xE2, 0x86, 0xB7, 0x9C, 0x53, 0x05,
    0xAA, 0x50, 0x07, 0x37, 0x3E, 0x07, 0x84, 0x1C, 0x7F, 0xDE, 0xAE, 0x5C,
    0x8E, 0x7D, 0x44, 0xEC, 0x57, 0x16, 0xF2, 0xB8, 0xB0, 0x3A, 0xDA, 0x37,
    0xF0, 0x50, 0x0C, 0x0D, 0xF0, 0x1C, 0x1F, 0x04, 0x02, 0x00, 0xB3, 0xFF,
    0xAE, 0x0C, 0xF5, 0x1A, 0x3C, 0xB5, 0x74, 0xB2, 0x25, 0x83, 0x7A, 0x58,
    0xDC, 0x09, 0x21, 0xBD, 0xD1, 0x91, 0x13, 0xF9, 0x7C, 0xA9, 0x2F, 0xF6,
    0x94, 0x32, 0x47, 0x73, 0x22, 0xF5, 0x47, 0x01, 0x3A, 0xE5, 0xE5, 0x81,
    0x37, 0xC2, 0xDA, 0xDC, 0xC8, 0xB5, 0x76, 0x34, 0x9A, 0xF3, 0xDD, 0xA7,
    0xA9, 0x44, 0x61, 0x46, 0x0F, 0xD0, 0x03, 0x0E, 0xEC, 0xC8, 0xC7, 0x3E,
    0xA4, 0x75, 0x1E, 0x41, 0xE2, 0x38, 0xCD, 0x99, 0x3B, 0xEA, 0x0E, 0x2F,
    0x32, 0x80, 0xBB, 0xA1, 0x18, 0x3E, 0xB3, 0x31, 0x4E, 0x54, 0x8B, 0x38,
    0x4F, 0x6D, 0xB9, 0x08, 0x6F, 0x42, 0x0D, 0x03, 0xF6, 0x0A, 0x04, 0xBF,
    0x2C, 0xB8, 0x12, 0x90, 0x24, 0x97, 0x7C, 0x79, 0x56, 0x79, 0xB0, 0x72,
    0xBC, 0xAF, 0x89, 0xAF, 0xDE, 0x9A, 0x77, 0x1F, 0xD9, 0x93, 0x08, 0x10,
    0xB3, 0x8B, 0xAE, 0x12, 0xDC, 0xCF, 0x3F, 0x2E, 0x55, 0x12, 0x72, 0x1F,
    0x2E, 0x6B, 0x71, 0x24, 0x50, 0x1A, 0xDD, 0xE6, 0x9F, 0x84, 0xCD, 0x87,
    0x7A, 0x58, 0x47, 0x18, 0x74, 0x08, 0xDA, 0x17, 0xBC, 0x9F, 0x9A, 0xBC,
    0xE9, 0x4B, 0x7D, 0x8C, 0xEC, 0x7A, 0xEC, 0x3A, 0xDB, 0x85, 0x1D, 0xFA,
    0x63, 0x09, 0x43, 0x66, 0xC4, 0x64, 0xC3, 0xD2, 0xEF, 0x1C, 0x18, 0x47,
    0x32, 0x15, 0xD8, 0x08, 0xDD, 0x43, 0x3B, 0x37, 0x24, 0xC2, 0xBA, 0x16,
    0x12, 0xA1, 0x4D, 0x43, 0x2A, 0x65, 0xC4, 0x51, 0x50, 0x94, 0x00, 0x02,
    0x13, 0x3A, 0xE4, 0xDD, 0x71, 0xDF, 0xF8, 0x9E, 0x10, 0x31, 0x4E, 0x55,
    0x81, 0xAC, 0x77, 0xD6, 0x5F, 0x11, 0x19, 0x9B, 0x04, 0x35, 0x56, 0xF1,
    0xD7, 0xA3, 0xC7, 0x6B, 0x3C, 0x11, 0x18, 0x3B, 0x59, 0x24, 0xA5, 0x09,
    0xF2, 0x8F, 0xE6, 0xED, 0x97, 0xF1, 0xFB, 0xFA, 0x9E, 0xBA, 0xBF, 0x2C,
    0x1E, 0x15, 0x3C, 0x6E, 0x86, 0xE3, 0x45, 0x70, 0xEA, 0xE9, 0x6F, 0xB1,
    0x86, 0x0E, 0x5E, 0x0A, 0x5A, 0x3E, 0x2A, 0xB3, 0x77, 0x1F, 0xE7, 0x1C,
    0x4E, 0x3D, 0x06, 0xFA, 0x29, 0x65, 0xDC, 0xB9, 0x99, 0xE7, 0x1D, 0x0F,
    0x80, 0x3E, 0x89, 0xD6, 0x52, 0x66, 0xC8, 0x25, 0x2E, 0x4C, 0xC9, 0x78,
    0x9C, 0x10, 0xB3, 0x6A, 0xC6, 0x15, 0x0E, 0xBA, 0x94, 0xE2, 0xEA, 0x78,
    0xA6, 0xFC, 0x3C, 0x53, 0x1E, 0x0A, 0x2D, 0xF4, 0xF2, 0xF7, 0x4E, 0xA7,
    0x36, 0x1D, 0x2B, 0x3D, 0x19, 0x39, 0x26, 0x0F, 0x19, 0xC2, 0x79, 0x60,
    0x52, 0x23, 0xA7, 0x08, 0xF7, 0x13, 0x12, 0xB6, 0xEB, 0xAD, 0xFE, 0x6E,
    0xEA, 0xC3, 0x1F, 0x66, 0xE3, 0xBC, 0x45, 0x95, 0xA6, 0x7B, 0xC8, 0x83,
    0xB1, 0x7F, 0x37, 0xD1, 0x01, 0x8C, 0xFF, 0x28, 0xC3, 0x32, 0xDD, 0xEF,
    0xBE, 0x6C, 0x5A, 0xA5, 0x65, 0x58, 0x21, 0x85, 0x68, 0xAB, 0x97, 0x02,
    0xEE, 0xCE, 0xA5, 0x0F, 0xDB, 0x2F, 0x95, 0x3B, 0x2A, 0xEF, 0x7D, 0xAD,
    0x5B, 0x6E, 0x2F, 0x84, 0x15, 0x21, 0xB6, 0x28, 0x29, 0x07, 0x61, 0x70,
    0xEC, 0xDD, 0x47, 0x75, 0x61, 0x9F, 0x15, 0x10, 0x13, 0xCC, 0xA8, 0x30,
    0xEB, 0x61, 0xBD, 0x96, 0x03, 0x34, 0xFE, 0x1E, 0xAA, 0x03, 0x63, 0xCF,
    0xB5, 0x73, 0x5C, 0x90, 0x4C, 0x70, 0xA2, 0x39, 0xD5, 0x9E, 0x9E, 0x0B,
    0xCB, 0xAA, 0xDE, 0x14, 0xEE, 0xCC, 0x86, 0xBC, 0x60, 0x62, 0x2C, 0xA7,
    0x9C, 0xAB, 0x5C, 0xAB, 0xB2, 0xF3, 0x84, 0x6E, 0x64, 0x8B, 0x1E, 0xAF,
    0x19, 0xBD, 0xF0, 0xCA, 0xA0, 0x23, 0x69, 0xB9, 0x65, 0x5A, 0xBB, 0x50,
    0x40, 0x68, 0x5A, 0x32, 0x3C, 0x2A, 0xB4, 0xB3, 0x31, 0x9E, 0xE9, 0xD5,
    0xC0, 0x21, 0xB8, 0xF7, 0x9B, 0x54, 0x0B, 0x19, 0x87, 0x5F, 0xA0, 0x99,
    0x95, 0xF7, 0x99, 0x7E, 0x62, 0x3D, 0x7D, 0xA8, 0xF8, 0x37, 0x88, 0x9A,
    0x97, 0xE3, 0x2D, 0x77, 0x11, 0xED, 0x93, 0x5F, 0x16, 0x68, 0x12, 0x81,
    0x0E, 0x35, 0x88, 0x29, 0xC7, 0xE6, 0x1F, 0xD6, 0x96, 0xDE, 0xDF, 0xA1,
    0x78, 0x58, 0xBA, 0x99, 0x57, 0xF5, 0x84, 0xA5, 0x1B, 0x22, 0x72, 0x63,
    0x9B, 0x83, 0xC3, 0xFF, 0x1A, 0xC2, 0x46, 0x96, 0xCD, 0xB3, 0x0A, 0xEB,
    0x53, 0x2E, 0x30, 0x54, 0x8F, 0xD9, 0x48, 0xE4, 0x6D, 0xBC, 0x31, 0x28,
    0x58, 0xEB, 0xF2, 0xEF, 0x34, 0xC6, 0xFF, 0xEA, 0xFE, 0x28, 0xED, 0x61,
    0xEE, 0x7C, 0x3C, 0x73, 0x5D, 0x4A, 0x14, 0xD9, 0xE8, 0x64, 0xB7, 0xE3,
    0x42, 0x10, 0x5D, 0x14, 0x20, 0x3E, 0x13, 0xE0, 0x45, 0xEE, 0xE2, 0xB6,
    0xA3, 0xAA, 0xAB, 0xEA, 0xDB, 0x6C, 0x4F, 0x15, 0xFA, 0xCB, 0x4F, 0xD0,
    0xC7, 0x42, 0xF4, 0x42, 0xEF, 0x6A, 0xBB, 0xB5, 0x65, 0x4F, 0x3B, 0x1D,
    0x41, 0xCD, 0x21, 0x05, 0xD8, 0x1E, 0x79, 0x9E, 0x86, 0x85, 0x4D, 0xC7,
    0xE4, 0x4B, 0x47, 0x6A, 0x3D, 0x81, 0x62, 0x50, 0xCF, 0x62, 0xA1, 0xF2,
    0x5B, 0x8D, 0x26, 0x46, 0xFC, 0x88, 0x83, 0xA0, 0xC1, 0xC7, 0xB6, 0xA3,
    0x7F, 0x15, 0x24, 0xC3, 0x69, 0xCB, 0x74, 0x92, 0x47, 0x84, 0x8A, 0x0B,
    0x56, 0x92, 0xB2, 0x85, 0x09, 0x5B, 0xBF, 0x00, 0xAD, 0x19, 0x48, 0x9D,
    0x14, 0x62, 0xB1, 0x74, 0x23, 0x82, 0x0D, 0x00, 0x58, 0x42, 0x8D, 0x2A,
    0x0C, 0x55, 0xF5, 0xEA, 0x1D, 0xAD, 0xF4, 0x3E, 0x23, 0x3F, 0x70, 0x61,
    0x33, 0x72, 0xF0, 0x92, 0x8D, 0x93, 0x7E, 0x41, 0xD6, 0x5F, 0xEC, 0xF1,
    0x6C, 0x22, 0x3B, 0xDB, 0x7C, 0xDE, 0x37, 0x59, 0xCB, 0xEE, 0x74, 0x60,
    0x40, 0x85, 0xF2, 0xA7, 0xCE, 0x77, 0x32, 0x6E, 0xA6, 0x07, 0x80, 0x84,
    0x19, 0xF8, 0x50, 0x9E, 0xE8, 0xEF, 0xD8, 0x55, 0x61, 0xD9, 0x97, 0x35,
    0xA9, 0x69, 0xA7, 0xAA, 0xC5, 0x0C, 0x06, 0xC2, 0x5A, 0x04, 0xAB, 0xFC,
    0x80, 0x0B, 0xCA, 0xDC, 0x9E, 0x44, 0x7A, 0x2E, 0xC3, 0x45, 0x34, 0x84,
    0xFD, 0xD5, 0x67, 0x05, 0x0E, 0x1E, 0x9E, 0xC9, 0xDB, 0x73, 0xDB, 0xD3,
    0x10, 0x55, 0x88, 0xCD, 0x67, 0x5F, 0xDA, 0x79, 0xE3, 0x67, 0x43, 0x40,
    0xC5, 0xC4, 0x34, 0x65, 0x71, 0x3E, 0x38, 0xD8, 0x3D, 0x28, 0xF8, 0x9E,
    0xF1, 0x6D, 0xFF, 0x20, 0x15, 0x3E, 0x21, 0xE7, 0x8F, 0xB0, 0x3D, 0x4A,
    0xE6, 0xE3, 0x9F, 0x2B, 0xDB, 0x83, 0xAD, 0xF7, 0xE9, 0x3D, 0x5A, 0x68,
    0x94, 0x81, 0x40, 0xF7, 0xF6, 0x4C, 0x26, 0x1C, 0x94, 0x69, 0x29, 0x34,
    0x41, 0x15, 0x20, 0xF7, 0x76, 0x02, 0xD4, 0xF7, 0xBC, 0xF4, 0x6B, 0x2E,
    0xD4, 0xA1, 0x00, 0x68, 0xD4, 0x08, 0x24, 0x71, 0x33, 0x20, 0xF4, 0x6A,
    0x43, 0xB7, 0xD4, 0xB7, 0x50, 0x00, 0x61, 0xAF, 0x1E, 0x39, 0xF6, 0x2E,
    0x97, 0x24, 0x45, 0x46,
};
Referenced by absl::random_internal::RandenSlow::GetKeys().