open spiel: open_spiel::amazons Namespace Reference
open_spiel::amazons Namespace Reference
Classes
class AmazonsGame
class AmazonsState
Enumerations
enum class CellState { kEmpty , kNought , kCross , kBlock }
Functions
CellState PlayerToState (Player player)
std::string StateToString (CellState state)
std::ostream & operator<< (std::ostream &stream, const CellState &state)
Variables
constexpr int kNumPlayers = 2
constexpr int kNumRows = 6
constexpr int kNumCols = 6
constexpr int kNumCells = kNumRows * kNumCols
constexpr int kCellStates = 4
constexpr int kNumberStates = 1000000000
Enumeration Type Documentation
CellState
enum class open_spiel::amazons::CellState strong
Enumerator
kEmpty
kNought
kCross
kBlock
Definition at line 46 of file amazons.h.
{ kEmpty, kNought, kCross, kBlock };
Function Documentation
operator<<()
std::ostream & open_spiel::amazons::operator<< (std::ostream & stream, const CellState & state) inline
Definition at line 143 of file amazons.h.
{
  return stream << StateToString(state);
}
References state, and StateToString().
PlayerToState()
CellState open_spiel::amazons::PlayerToState (Player player)
Definition at line 57 of file amazons.cc.
{
  switch (player) {
    case 0:
      return CellState::kCross;
    case 1:
      return CellState::kNought;
    default:
      SpielFatalError(absl::StrCat("Invalid player id ", player));
      return CellState::kEmpty;
  }
}
References kCross, kEmpty, kNought, player, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::amazons::AmazonsState::ActionToString(), open_spiel::amazons::AmazonsState::DoApplyAction(), open_spiel::amazons::AmazonsState::LegalActions(), and open_spiel::amazons::AmazonsState::UndoAction().
StateToString()
std::string open_spiel::amazons::StateToString (CellState state)
Definition at line 69 of file amazons.cc.
{
  switch (state) {
    case CellState::kEmpty:
      return ".";
    case CellState::kNought:
      return "O";
    case CellState::kCross:
      return "X";
    case CellState::kBlock:
      return "#";
    default:
      SpielFatalError("Unknown state.");
  }
}
References kBlock, kCross, kEmpty, kNought, open_spiel::SpielFatalError(), and state.
Referenced by open_spiel::amazons::AmazonsState::ActionToString(), operator<<(), and open_spiel::amazons::AmazonsState::ToString().
Variable Documentation
kCellStates
int open_spiel::amazons::kCellStates = 4 inline constexpr
Definition at line 40 of file amazons.h.
Referenced by open_spiel::amazons::AmazonsState::ObservationTensor(), and open_spiel::amazons::AmazonsGame::ObservationTensorShape().
kNumberStates
int open_spiel::amazons::kNumberStates = 1000000000 inline constexpr
Definition at line 43 of file amazons.h.
kNumCells
int open_spiel::amazons::kNumCells = kNumRows * kNumCols inline constexpr
Definition at line 39 of file amazons.h.
Referenced by open_spiel::amazons::AmazonsGame::MaxGameLength(), open_spiel::amazons::AmazonsGame::NumDistinctActions(), and open_spiel::amazons::AmazonsState::ObservationTensor().
kNumCols
int open_spiel::amazons::kNumCols = 6 inline constexpr
Definition at line 38 of file amazons.h.
Referenced by open_spiel::amazons::AmazonsState::ToString().
kNumPlayers
int open_spiel::amazons::kNumPlayers = 2 inline constexpr
Definition at line 36 of file amazons.h.
Referenced by open_spiel::amazons::AmazonsGame::NumPlayers().
kNumRows
int open_spiel::amazons::kNumRows = 6 inline constexpr
Definition at line 37 of file amazons.h.
Referenced by open_spiel::amazons::AmazonsGame::ObservationTensorShape(), and open_spiel::amazons::AmazonsState::ToString().