open spiel: open_spiel.python.algorithms.mmd_dilated Namespace Reference
open_spiel.python.algorithms.mmd_dilated Namespace Reference
Classes
class MMDDilatedEnt
Functions
neg_entropy (probs)
softmax (x)
divergence (x, y, psi_x, psi_y, grad_psi_y)
dilated_dgf_divergence (mmd_1, mmd_2)
Detailed Description
Python implementation of the magnetic mirror descent (MMD) algorithm.
The algorithm operated over the sequence-from with dilated entropy.
See https://arxiv.org/abs/2206.05825.
One iteration of MMD consists of:
1) Compute gradients of dilated entropy
   and payoffs for current sequence form policies.
2) Compute behavioural form policy starting from the bottom
    of the tree and updating gradients of parent nodes along the way.
3) Convert behavioural form policy to equivalent sequence form policy.
The last sequence form policy converges linearly (exponentially fast)
to a \alpha-reduced normal-form  QRE.
Function Documentation
dilated_dgf_divergence()
open_spiel.python.algorithms.mmd_dilated.dilated_dgf_divergence (mmd_1, mmd_2)
Bregman divergence between two MMDDilatedEnt objects.
    The value is equivalent to a sum of two Bregman divergences
    over the sequence form, one for each player.
Args:
    mmd_1: MMDDilatedEnt Object
    mmd_2: MMDDilatedEnt Object
Returns:
    Scalar.
Definition at line 74 of file mmd_dilated.py.
def dilated_dgf_divergence(mmd_1, mmd_2):
  """Bregman divergence between two MMDDilatedEnt objects.
      The value is equivalent to a sum of two Bregman divergences
      over the sequence form, one for each player.
  Args:
      mmd_1: MMDDilatedEnt Object
      mmd_2: MMDDilatedEnt Object
  Returns:
      Scalar.
  """
  dgf_values = [mmd_1.dgf_eval(), mmd_2.dgf_eval()]
  dgf_grads = mmd_2.dgf_grads()
  div = 0
  for player in range(2):
    div += divergence(mmd_1.sequences[player], mmd_2.sequences[player],
                      dgf_values[0][player], dgf_values[1][player],
                      dgf_grads[player])
  return div
References open_spiel.python.algorithms.mmd_dilated.divergence().
divergence()
open_spiel.python.algorithms.mmd_dilated.divergence (x, y, psi_x, psi_y, grad_psi_y)
Compute Bregman divergence between x and y, B_psi(x;y).
Args:
    x: Numpy array.
    y: Numpy array.
    psi_x: Value of psi evaluated at x.
    psi_y: Value of psi evaluated at y.
    grad_psi_y: Gradient of psi evaluated at y.
Returns:
    Scalar.
Definition at line 58 of file mmd_dilated.py.
def divergence(x, y, psi_x, psi_y, grad_psi_y):
  """Compute Bregman divergence between x and y, B_psi(x;y).
  Args:
      x: Numpy array.
      y: Numpy array.
      psi_x: Value of psi evaluated at x.
      psi_y: Value of psi evaluated at y.
      grad_psi_y: Gradient of psi evaluated at y.
  Returns:
      Scalar.
  """
  return psi_x - psi_y - np.dot(grad_psi_y, x - y)
Referenced by open_spiel.python.algorithms.mmd_dilated.dilated_dgf_divergence().
neg_entropy()
open_spiel.python.algorithms.mmd_dilated.neg_entropy (probs)
Definition at line 49 of file mmd_dilated.py.
def neg_entropy(probs):
  return -scipy_stats.entropy(probs)
Referenced by open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt._update_state_sequences(), and open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt.dgf_eval().
softmax()
open_spiel.python.algorithms.mmd_dilated.softmax (x)
Definition at line 53 of file mmd_dilated.py.
def softmax(x):
  unnormalized = np.exp(x - np.max(x))
  return unnormalized / np.sum(unnormalized)
Referenced by open_spiel.python.algorithms.mmd_dilated.MMDDilatedEnt._update_state_sequences().