open spiel: absl::little_endian Namespace Reference
absl::little_endian Namespace Reference
Functions
uint8_t FromHost (uint8_t x)
uint16_t FromHost (uint16_t x)
uint32_t FromHost (uint32_t x)
uint64_t FromHost (uint64_t x)
uint8_t ToHost (uint8_t x)
uint16_t ToHost (uint16_t x)
uint32_t ToHost (uint32_t x)
uint64_t ToHost (uint64_t x)
int8_t FromHost (int8_t x)
int16_t FromHost (int16_t x)
int32_t FromHost (int32_t x)
int64_t FromHost (int64_t x)
int8_t ToHost (int8_t x)
int16_t ToHost (int16_t x)
int32_t ToHost (int32_t x)
int64_t ToHost (int64_t x)
uint16_t Load16 (const void *p)
void Store16 (void *p, uint16_t v)
uint32_t Load32 (const void *p)
void Store32 (void *p, uint32_t v)
uint64_t Load64 (const void *p)
void Store64 (void *p, uint64_t v)
Function Documentation
FromHost() [1/8]
int16_t absl::little_endian::FromHost (int16_t x) inline
Definition at line 142 of file endian.h.
{
  return bit_cast<int16_t>(FromHost16(bit_cast<uint16_t>(x)));
}
References absl::bit_cast(), and absl::x.
FromHost() [2/8]
int32_t absl::little_endian::FromHost (int32_t x) inline
Definition at line 145 of file endian.h.
{
  return bit_cast<int32_t>(FromHost32(bit_cast<uint32_t>(x)));
}
References absl::bit_cast(), and absl::x.
FromHost() [3/8]
int64_t absl::little_endian::FromHost (int64_t x) inline
Definition at line 148 of file endian.h.
{
  return bit_cast<int64_t>(FromHost64(bit_cast<uint64_t>(x)));
}
References absl::bit_cast(), and absl::x.
FromHost() [4/8]
int8_t absl::little_endian::FromHost (int8_t x) inline
Definition at line 141 of file endian.h.
{ return x; }
References absl::x.
FromHost() [5/8]
uint16_t absl::little_endian::FromHost (uint16_t x) inline
Definition at line 133 of file endian.h.
{ return FromHost16(x); }
References absl::x.
FromHost() [6/8]
uint32_t absl::little_endian::FromHost (uint32_t x) inline
Definition at line 134 of file endian.h.
{ return FromHost32(x); }
References absl::x.
FromHost() [7/8]
uint64_t absl::little_endian::FromHost (uint64_t x) inline
Definition at line 135 of file endian.h.
{ return FromHost64(x); }
References absl::x.
FromHost() [8/8]
uint8_t absl::little_endian::FromHost (uint8_t x) inline
Definition at line 132 of file endian.h.
{ return x; }
References absl::x.
Referenced by absl::random_internal::randen_engine< T >::reseed().
Load16()
uint16_t absl::little_endian::Load16 (const void * p) inline
Definition at line 163 of file endian.h.
{
  return ToHost16(ABSL_INTERNAL_UNALIGNED_LOAD16(p));
}
References absl::p.
Referenced by absl::crc_internal::ExtendCrc32cInline(), and absl::ABSL_NAMESPACE_BEGIN::TEST().
Load32()
uint32_t absl::little_endian::Load32 (const void * p) inline
Definition at line 171 of file endian.h.
{
  return ToHost32(ABSL_INTERNAL_UNALIGNED_LOAD32(p));
}
References absl::p.
Referenced by absl::crc_internal::CRC32::Extend(), absl::crc_internal::ExtendCrc32cInline(), and absl::ABSL_NAMESPACE_BEGIN::TEST().
Load64()
uint64_t absl::little_endian::Load64 (const void * p) inline
Definition at line 179 of file endian.h.
{
  return ToHost64(ABSL_INTERNAL_UNALIGNED_LOAD64(p));
}
References absl::p.
Referenced by absl::crc_internal::ExtendCrc32cInline(), and absl::ABSL_NAMESPACE_BEGIN::TEST().
Store16()
void absl::little_endian::Store16 (void * p, uint16_t v) inline
Definition at line 167 of file endian.h.
{
  ABSL_INTERNAL_UNALIGNED_STORE16(p, FromHost16(v));
}
References absl::p, and absl::v.
Referenced by absl::ABSL_NAMESPACE_BEGIN::TEST().
Store32()
void absl::little_endian::Store32 (void * p, uint32_t v) inline
Definition at line 175 of file endian.h.
{
  ABSL_INTERNAL_UNALIGNED_STORE32(p, FromHost32(v));
}
References absl::p, and absl::v.
Referenced by absl::ABSL_NAMESPACE_BEGIN::TEST().
Store64()
void absl::little_endian::Store64 (void * p, uint64_t v) inline
Definition at line 183 of file endian.h.
{
  ABSL_INTERNAL_UNALIGNED_STORE64(p, FromHost64(v));
}
References absl::p, and absl::v.
Referenced by absl::container_internal::GroupPortableImpl::ConvertSpecialToEmptyAndFullToDeleted(), and absl::ABSL_NAMESPACE_BEGIN::TEST().
ToHost() [1/8]
int16_t absl::little_endian::ToHost (int16_t x) inline
Definition at line 152 of file endian.h.
{
  return bit_cast<int16_t>(ToHost16(bit_cast<uint16_t>(x)));
}
References absl::bit_cast(), and absl::x.
ToHost() [2/8]
int32_t absl::little_endian::ToHost (int32_t x) inline
Definition at line 155 of file endian.h.
{
  return bit_cast<int32_t>(ToHost32(bit_cast<uint32_t>(x)));
}
References absl::bit_cast(), and absl::x.
ToHost() [3/8]
int64_t absl::little_endian::ToHost (int64_t x) inline
Definition at line 158 of file endian.h.
{
  return bit_cast<int64_t>(ToHost64(bit_cast<uint64_t>(x)));
}
References absl::bit_cast(), and absl::x.
ToHost() [4/8]
int8_t absl::little_endian::ToHost (int8_t x) inline
Definition at line 151 of file endian.h.
{ return x; }
References absl::x.
ToHost() [5/8]
uint16_t absl::little_endian::ToHost (uint16_t x) inline
Definition at line 137 of file endian.h.
{ return ToHost16(x); }
References absl::x.
ToHost() [6/8]
uint32_t absl::little_endian::ToHost (uint32_t x) inline
Definition at line 138 of file endian.h.
{ return ToHost32(x); }
References absl::x.
ToHost() [7/8]
uint64_t absl::little_endian::ToHost (uint64_t x) inline
Definition at line 139 of file endian.h.
{ return ToHost64(x); }
References absl::x.
ToHost() [8/8]
uint8_t absl::little_endian::ToHost (uint8_t x) inline
Definition at line 136 of file endian.h.
{ return x; }
References absl::x.
Referenced by absl::random_internal::randen_engine< T >::operator()().