open spiel: open_spiel.python.algorithms.losses.rl_losses Namespace Reference
open_spiel.python.algorithms.losses.rl_losses Namespace Reference
Classes
class BatchA2CLoss
class BatchQPGLoss
class BatchRMLoss
class BatchRPGLoss
Functions
_assert_rank_and_shape_compatibility (tensors, rank)
compute_baseline (policy, action_values)
compute_regrets (policy_logits, action_values)
compute_advantages (policy_logits, action_values, use_relu=False)
compute_a2c_loss (policy_logits, actions, advantages)
compute_entropy (policy_logits)
compute_entropy_loss (policy_logits)
Detailed Description
Reinforcement learning loss functions.
All the loss functions implemented here compute the loss for the policy (actor).
The critic loss functions are typically regression loss are omitted for their
simplicity.
For the batch QPG, RM and RPG loss, please refer to the paper:
https://papers.nips.cc/paper/7602-actor-critic-policy-optimization-in-partially-observable-multiagent-environments.pdf
The BatchA2C loss uses code from the `TRFL` library:
https://github.com/deepmind/trfl/blob/master/trfl/discrete_policy_gradient_ops.py
Function Documentation
_assert_rank_and_shape_compatibility()
open_spiel.python.algorithms.losses.rl_losses._assert_rank_and_shape_compatibility (tensors, rank) protected
Definition at line 34 of file rl_losses.py.
def _assert_rank_and_shape_compatibility(tensors, rank):
  if not tensors:
    raise ValueError("List of tensors cannot be empty")
  union_of_shapes = tf.TensorShape(None)
  for tensor in tensors:
    tensor_shape = tensor.get_shape()
    tensor_shape.assert_has_rank(rank)
    union_of_shapes = union_of_shapes.merge_with(tensor_shape)
Referenced by open_spiel.python.algorithms.losses.rl_losses.BatchA2CLoss.loss(), open_spiel.python.algorithms.losses.rl_losses.BatchQPGLoss.loss(), open_spiel.python.algorithms.losses.rl_losses.BatchRMLoss.loss(), and open_spiel.python.algorithms.losses.rl_losses.BatchRPGLoss.loss().
compute_a2c_loss()
open_spiel.python.algorithms.losses.rl_losses.compute_a2c_loss (policy_logits, actions, advantages)
Definition at line 84 of file rl_losses.py.
def compute_a2c_loss(policy_logits, actions, advantages):
  cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(
      labels=actions, logits=policy_logits)
  advantages = tf.stop_gradient(advantages)
  advantages.get_shape().assert_is_compatible_with(cross_entropy.get_shape())
  return tf.multiply(cross_entropy, advantages)
Referenced by open_spiel.python.algorithms.losses.rl_losses.BatchA2CLoss.loss().
compute_advantages()
open_spiel.python.algorithms.losses.rl_losses.compute_advantages (policy_logits, action_values, use_relu = False)
Compute advantages using pi and Q.
Definition at line 66 of file rl_losses.py.
def compute_advantages(policy_logits, action_values, use_relu=False):
  """Compute advantages using pi and Q."""
  # Compute advantage.
  policy = tf.nn.softmax(policy_logits, axis=1)
  # Avoid computing gradients for action_values.
  action_values = tf.stop_gradient(action_values)
  baseline = compute_baseline(policy, action_values)
  advantages = action_values - tf.expand_dims(baseline, 1)
  if use_relu:
    advantages = tf.nn.relu(advantages)
  # Compute advantage weighted by policy.
  policy_advantages = -tf.multiply(policy, tf.stop_gradient(advantages))
  return tf.reduce_sum(policy_advantages, axis=1)
References open_spiel.python.algorithms.losses.rl_losses.compute_baseline().
Referenced by open_spiel.python.algorithms.losses.rl_losses.BatchQPGLoss.loss(), and open_spiel.python.algorithms.losses.rl_losses.BatchRMLoss.loss().
compute_baseline()
open_spiel.python.algorithms.losses.rl_losses.compute_baseline (policy, action_values)
Definition at line 45 of file rl_losses.py.
def compute_baseline(policy, action_values):
  # V = pi * Q, backprop through pi but not Q.
  return tf.reduce_sum(
      tf.multiply(policy, tf.stop_gradient(action_values)), axis=1)
Referenced by open_spiel.python.algorithms.losses.rl_losses.compute_advantages(), and open_spiel.python.algorithms.losses.rl_losses.compute_regrets().
compute_entropy()
open_spiel.python.algorithms.losses.rl_losses.compute_entropy (policy_logits)
Definition at line 92 of file rl_losses.py.
def compute_entropy(policy_logits):
  return tf.reduce_sum(
      -tf.nn.softmax(policy_logits) * tf.nn.log_softmax(policy_logits), axis=-1)
Referenced by open_spiel.python.algorithms.losses.rl_losses.compute_entropy_loss().
compute_entropy_loss()
open_spiel.python.algorithms.losses.rl_losses.compute_entropy_loss (policy_logits)
Compute an entropy loss.
We want a value that we can minimize along with other losses, and where
minimizing means driving the policy towards a uniform distribution over
the actions. We thus scale it by negative one so that it can be simply
added to other losses (and so it can be considered a bonus for having
entropy).
Args:
  policy_logits: the policy logits.
Returns:
  entropy loss (negative entropy).
Definition at line 97 of file rl_losses.py.
def compute_entropy_loss(policy_logits):
  """Compute an entropy loss.
  We want a value that we can minimize along with other losses, and where
  minimizing means driving the policy towards a uniform distribution over
  the actions. We thus scale it by negative one so that it can be simply
  added to other losses (and so it can be considered a bonus for having
  entropy).
  Args:
    policy_logits: the policy logits.
  Returns:
    entropy loss (negative entropy).
  """
  entropy = compute_entropy(policy_logits)
  scale = tf.constant(-1.0, dtype=tf.float32)
  entropy_loss = tf.multiply(scale, entropy, name="entropy_loss")
  return entropy_loss
References open_spiel.python.algorithms.losses.rl_losses.compute_entropy().
Referenced by open_spiel.python.algorithms.losses.rl_losses.BatchA2CLoss.loss(), open_spiel.python.algorithms.losses.rl_losses.BatchQPGLoss.loss(), open_spiel.python.algorithms.losses.rl_losses.BatchRMLoss.loss(), and open_spiel.python.algorithms.losses.rl_losses.BatchRPGLoss.loss().
compute_regrets()
open_spiel.python.algorithms.losses.rl_losses.compute_regrets (policy_logits, action_values)
Compute regrets using pi and Q.
Definition at line 51 of file rl_losses.py.
def compute_regrets(policy_logits, action_values):
  """Compute regrets using pi and Q."""
  # Compute regret.
  policy = tf.nn.softmax(policy_logits, axis=1)
  # Avoid computing gradients for action_values.
  action_values = tf.stop_gradient(action_values)
  baseline = compute_baseline(policy, action_values)
  regrets = tf.reduce_sum(
      tf.nn.relu(action_values - tf.expand_dims(baseline, 1)), axis=1)
  return regrets
References open_spiel.python.algorithms.losses.rl_losses.compute_baseline().
Referenced by open_spiel.python.algorithms.losses.rl_losses.BatchRPGLoss.loss().