open spiel: open_spiel.python.mfg.algorithms.distribution Namespace Reference
open_spiel.python.mfg.algorithms.distribution Namespace Reference
Classes
class DistributionPolicy
Functions
type_from_states (states)
_check_distribution_sum (DistributionDict distribution, int expected_sum)
Detailed Description
Computes the distribution of a policy.
Function Documentation
_check_distribution_sum()
open_spiel.python.mfg.algorithms.distribution._check_distribution_sum (DistributionDict distribution, int expected_sum) protected
Sanity check that the distribution sums to a given value.
Definition at line 31 of file distribution.py.
def _check_distribution_sum(distribution: DistributionDict, expected_sum: int):
  """Sanity check that the distribution sums to a given value."""
  sum_state_probabilities = sum(distribution.values())
  assert abs(sum_state_probabilities - expected_sum) < 1e-4, (
      "Sum of probabilities of all possible states should be the number of "
      f"population, it is {sum_state_probabilities}.")
Referenced by open_spiel.python.mfg.algorithms.distribution.DistributionPolicy.evaluate().
type_from_states()
open_spiel.python.mfg.algorithms.distribution.type_from_states (states)
Get node type of a list of states and assert they are the same.
Definition at line 24 of file distribution.py.
def type_from_states(states):
  """Get node type of a list of states and assert they are the same."""
  types = [state.get_type() for state in states]
  assert len(set(types)) == 1, f"types: {types}"
  return types[0]
References len.
Referenced by open_spiel.python.mfg.algorithms.distribution.DistributionPolicy._one_forward_step(), and open_spiel.python.mfg.algorithms.distribution.DistributionPolicy.evaluate().