open spiel: open_spiel.python.policy Namespace Reference
open_spiel.python.policy Namespace Reference
Classes
class FirstActionPolicy
class Policy
class TabularPolicy
class UniformRandomPolicy
Functions
child (state, action)
joint_action_probabilities_aux (state, policy)
joint_action_probabilities (state, policy)
get_tabular_policy_states (game)
tabular_policy_from_callable (game, callable_policy, players=None)
pyspiel_policy_to_python_policy (game, pyspiel_tabular_policy, players=None)
python_policy_to_pyspiel_policy (python_tabular_policy)
python_policies_to_pyspiel_policies (policies)
merge_tabular_policies (tabular_policies, game)
Detailed Description
Representation of a policy for a game.
This is a standard representation for passing policies into algorithms,
with currently the following implementations:
  TabularPolicy - an explicit policy per state, stored in an array
    of shape `(num_states, num_actions)`, convenient for tabular policy
    solution methods.
  UniformRandomPolicy - a uniform distribution over all legal actions for
    the specified player. This is computed as needed, so can be used for
    games where a tabular policy would be unfeasibly large.
The main way of using a policy is to call `action_probabilities(state,
player_id`), to obtain a dict of {action: probability}. `TabularPolicy`
objects expose a lower-level interface, which may be more efficient for
some use cases.
Function Documentation
child()
open_spiel.python.policy.child (state, action)
Returns a child state, handling the simultaneous node case.
Definition at line 43 of file policy.py.
def child(state, action):
  """Returns a child state, handling the simultaneous node case."""
  if isinstance(action, Iterable):
    child_state = state.clone()
    child_state.apply_actions(action)
    return child_state
  else:
    return state.child(action)
get_tabular_policy_states()
open_spiel.python.policy.get_tabular_policy_states (game)
Returns the states of the game for a tabular policy.
Definition at line 453 of file policy.py.
def get_tabular_policy_states(game):
  """Returns the states of the game for a tabular policy."""
  if game.get_type().dynamics == pyspiel.GameType.Dynamics.MEAN_FIELD:
    # TODO(author18): We use s.observation_string(DEFAULT_MFG_PLAYER) here as the
    # number of history is exponential on the depth of the MFG. What we really
    # need is a representation of the state. For many player Mean Field games,
    # the state will be (x0, x1, x2, ..., xn) and the observation_string(0) will
    # output the string of x0. In that case we would need something like
    # str([observation_string(i) for i in range(num_player)])
    to_string = lambda s: s.observation_string(pyspiel.PlayerId.
                                               DEFAULT_PLAYER_ID)
  else:
    to_string = lambda s: s.history_str()
  return get_all_states.get_all_states(
      game,
      depth_limit=-1,
      include_terminals=False,
      include_chance_states=False,
      include_mean_field_states=False,
      to_string=to_string)
Referenced by open_spiel.python.policy.Policy.to_tabular().
joint_action_probabilities()
open_spiel.python.policy.joint_action_probabilities (state, policy)
Yields action, probability pairs for a joint policy in simultaneous state.
Args:
  state: a game state at a simultaneous decision node.
  policy: policy that gives the probability distribution over the legal
    actions for each players.
Yields:
  (action, probability) pairs. An action is a tuple of individual
    actions for each player of the game. The probability is a single joint
    probability (product of all the individual probabilities).
Definition at line 76 of file policy.py.
def joint_action_probabilities(state, policy):
  """Yields action, probability pairs for a joint policy in simultaneous state.
  Args:
    state: a game state at a simultaneous decision node.
    policy: policy that gives the probability distribution over the legal
      actions for each players.
  Yields:
    (action, probability) pairs. An action is a tuple of individual
      actions for each player of the game. The probability is a single joint
      probability (product of all the individual probabilities).
  """
  actions_per_player, probs_per_player = joint_action_probabilities_aux(
      state, policy)
  for actions, probs in zip(
      itertools.product(*actions_per_player),
      itertools.product(*probs_per_player)):
    yield actions, np.prod(probs)
References open_spiel.python.policy.joint_action_probabilities_aux().
joint_action_probabilities_aux()
open_spiel.python.policy.joint_action_probabilities_aux (state, policy)
Auxiliary function for joint_action_probabilities.
Args:
  state: a game state at a simultaneous decision node.
  policy: policy that gives the probability distribution over the legal
    actions for each players.
Returns:
  actions_per_player: list of list of actions for each player
  probs_per_player: list of list of probabilities do the corresponding action
   in actions_per_player for each player.
Definition at line 53 of file policy.py.
def joint_action_probabilities_aux(state, policy):
  """Auxiliary function for joint_action_probabilities.
  Args:
    state: a game state at a simultaneous decision node.
    policy: policy that gives the probability distribution over the legal
      actions for each players.
  Returns:
    actions_per_player: list of list of actions for each player
    probs_per_player: list of list of probabilities do the corresponding action
     in actions_per_player for each player.
  """
  assert state.is_simultaneous_node()
  action_probs_per_player = [
      policy.action_probabilities(state, player)
      for player in range(state.get_game().num_players())
  ]
  actions_per_player = [pi.keys() for pi in action_probs_per_player]
  probs_per_player = [pi.values() for pi in action_probs_per_player]
  return actions_per_player, probs_per_player
Referenced by open_spiel.python.policy.joint_action_probabilities().
merge_tabular_policies()
open_spiel.python.policy.merge_tabular_policies (tabular_policies, game)
Merges n_player policies into single joint policy.
Missing states are filled with a valid uniform policy.
Args:
  tabular_policies: List of python TabularPolicy (one for each player).
  game: The game corresponding to the resulting TabularPolicy.
Returns:
  merged_policy: A TabularPolicy with each player i's policy taken from the
    ith joint_policy.
Definition at line 555 of file policy.py.
def merge_tabular_policies(tabular_policies, game):
  """Merges n_player policies into single joint policy.
  Missing states are filled with a valid uniform policy.
  Args:
    tabular_policies: List of python TabularPolicy (one for each player).
    game: The game corresponding to the resulting TabularPolicy.
  Returns:
    merged_policy: A TabularPolicy with each player i's policy taken from the
      ith joint_policy.
  """
  if len(tabular_policies) != game.num_players():
    raise ValueError("len(tabular_policies) != num_players: %d != %d" %
                     (len(tabular_policies), game.num_players()))
  merged_policy = TabularPolicy(game)
  for p, p_states in enumerate(merged_policy.states_per_player):
    for p_state in p_states:
      to_index = merged_policy.state_lookup[p_state]
      # Only copy if the state exists, otherwise fall back onto uniform.
      if p_state in tabular_policies[p].state_lookup:
        from_index = tabular_policies[p].state_lookup[p_state]
        merged_policy.action_probability_array[to_index] = (
            tabular_policies[p].action_probability_array[from_index])
  return merged_policy
pyspiel_policy_to_python_policy()
open_spiel.python.policy.pyspiel_policy_to_python_policy (game, pyspiel_tabular_policy, players = None)
Converts a pyspiel.TabularPolicy to a TabularPolicy.
Args:
  game: The OpenSpiel game.
  pyspiel_tabular_policy: Pyspiel tabular policy to copy from.
  players: List of integer player ids to copy policy from. For example,
    `players=[0]` will only copy player 0's policy over into the python policy
    (the other player's policies will be undefined). Default value of `None`
    will copy all players' policies.
Returns:
  python_policy
Definition at line 502 of file policy.py.
def pyspiel_policy_to_python_policy(game, pyspiel_tabular_policy, players=None):
  """Converts a pyspiel.TabularPolicy to a TabularPolicy.
  Args:
    game: The OpenSpiel game.
    pyspiel_tabular_policy: Pyspiel tabular policy to copy from.
    players: List of integer player ids to copy policy from. For example,
      `players=[0]` will only copy player 0's policy over into the python policy
      (the other player's policies will be undefined). Default value of `None`
      will copy all players' policies.
  Returns:
    python_policy
  """
  policy = TabularPolicy(game, players=players)
  for item in pyspiel_tabular_policy.policy_table().items():
    info_state_str, actions_probs = item
    # If requested, only populate a policy for particular players.
    if players is not None and info_state_str not in policy.state_lookup:
      continue
    state_policy = policy.policy_for_key(info_state_str)
    for action, prob in actions_probs:
      state_policy[action] = prob
  return policy
python_policies_to_pyspiel_policies()
open_spiel.python.policy.python_policies_to_pyspiel_policies (policies)
Same conversion as above (list version).
Args:
  policies: a list of python.TabularPolicy
Returns:
  a list of pyspiel.TabularPolicy.
Definition at line 543 of file policy.py.
def python_policies_to_pyspiel_policies(policies):
  """Same conversion as above (list version).
  Args:
    policies: a list of python.TabularPolicy
  Returns:
    a list of pyspiel.TabularPolicy.
  """
  return [python_policy_to_pyspiel_policy(p) for p in policies]
References open_spiel.python.policy.python_policy_to_pyspiel_policy().
python_policy_to_pyspiel_policy()
open_spiel.python.policy.python_policy_to_pyspiel_policy (python_tabular_policy)
Converts a TabularPolicy to a pyspiel.TabularPolicy.
Definition at line 528 of file policy.py.
def python_policy_to_pyspiel_policy(python_tabular_policy):
  """Converts a TabularPolicy to a pyspiel.TabularPolicy."""
  infostates_to_probabilities = dict()
  for infostate, index in python_tabular_policy.state_lookup.items():
    probs = python_tabular_policy.action_probability_array[index]
    legals = python_tabular_policy.legal_actions_mask[index]
    action_probs = []
    for action, (prob, is_legal) in enumerate(zip(probs, legals)):
      if is_legal == 1:
        action_probs.append((action, prob))
    infostates_to_probabilities[infostate] = action_probs
  return pyspiel.TabularPolicy(infostates_to_probabilities)
Referenced by open_spiel.python.policy.python_policies_to_pyspiel_policies().
tabular_policy_from_callable()
open_spiel.python.policy.tabular_policy_from_callable (game, callable_policy, players = None)
Converts a legacy callable policy into a TabularPolicy.
Recommendation - instead of using this to convert your policy for evaluation
purposes, work directly with a `TabularPolicy` if possible.
Second choice - work with a `Policy` class and call `to_tabular` as needed.
Args:
  game: The game for which we want a TabularPolicy.
  callable_policy: A callable: state -> action probabilities dict or list.
  players: List of players this policy applies to. If `None`, applies to all
    players.
Returns:
  A TabularPolicy that materializes the callable policy.
Definition at line 475 of file policy.py.
def tabular_policy_from_callable(game, callable_policy, players=None):
  """Converts a legacy callable policy into a TabularPolicy.
  Recommendation - instead of using this to convert your policy for evaluation
  purposes, work directly with a `TabularPolicy` if possible.
  Second choice - work with a `Policy` class and call `to_tabular` as needed.
  Args:
    game: The game for which we want a TabularPolicy.
    callable_policy: A callable: state -> action probabilities dict or list.
    players: List of players this policy applies to. If `None`, applies to all
      players.
  Returns:
    A TabularPolicy that materializes the callable policy.
  """
  tabular_policy = TabularPolicy(game, players)
  for state_index, state in enumerate(tabular_policy.states):
    action_probabilities = dict(callable_policy(state))
    infostate_policy = [
        action_probabilities.get(action, 0.)
        for action in range(game.num_distinct_actions())
    ]
    tabular_policy.action_probability_array[state_index, :] = infostate_policy
  return tabular_policy