open spiel: open_spiel::universal_poker Namespace Reference
open_spiel::universal_poker Namespace Reference
Namespaces
namespace acpc_cpp
namespace logic
Classes
class UniformRestrictedActions
class UniformRestrictedActionsFactory
class UniversalPokerGame
class UniversalPokerState
Enumerations
enum ActionType {
kFold = 0 , kCall = 1 , kBet = 2 , kAllIn = 3 ,
kHalfPot = 4
}
enum BettingAbstraction { kFCPA = 0 , kFC = 1 , kFULLGAME = 2 , kFCHPA = 3 }
enum StateActionType {
ACTION_DEAL = 1 , ACTION_FOLD = 2 , ACTION_CHECK_CALL = 4 , ACTION_BET = 8 ,
ACTION_ALL_IN = 16
}
Functions
std::shared_ptr< const Game > Factory (const GameParameters &params)
REGISTER_SPIEL_GAME (kGameType, Factory)
open_spiel::RegisterSingleTensorObserver single_tensor (kGameType.short_name)
uint32_t GetMaxBettingActions (const acpc_cpp::ACPCGame &acpc_game)
int GetHoleCardsReachIndex (int card_a, int card_b, int num_suits, int num_ranks)
void DistributeHands (const logic::CardSet &full_deck, uint8_t num_players, uint8_t num_hole_cards, std::function< void(std::vector< std::vector< uint8_t > >)> yield)
open_spiel::Action ACPCActionToOpenSpielAction (const project_acpc_server::Action &action, const UniversalPokerState &state)
std::shared_ptr< const Game > LoadUniversalPokerGameFromACPCGamedef (const std::string &acpc_gamedef)
std::shared_ptr< const Game > MakeRandomSubgame (std::mt19937 &rng, int pot_size, std::string board_cards, std::vector< double > hand_reach)
std::ostream & operator<< (std::ostream &os, const BettingAbstraction &betting)
REGISTER_SPIEL_BOT ("uniform_restricted_actions", UniformRestrictedActionsFactory)
Variables
const GameType kGameType
const char * actions = "0df0c000p0000000a"
constexpr uint8_t kMaxUniversalPokerPlayers = 10
constexpr int kNumActionsFCHPA
constexpr StateActionType ALL_ACTIONS [5]
constexpr int kSubgameUniqueHands = 1326
Enumeration Type Documentation
ActionType
enum open_spiel::universal_poker::ActionType
Enumerator
kFold
kCall
kBet
kAllIn
kHalfPot
Definition at line 48 of file universal_poker.h.
{ kFold = 0, kCall = 1, kBet = 2, kAllIn = 3, kHalfPot = 4 };
BettingAbstraction
enum open_spiel::universal_poker::BettingAbstraction
Enumerator
kFCPA
kFC
kFULLGAME
kFCHPA
Definition at line 54 of file universal_poker.h.
{ kFCPA = 0, kFC = 1, kFULLGAME = 2, kFCHPA = 3 };
StateActionType
enum open_spiel::universal_poker::StateActionType
Enumerator
ACTION_DEAL
ACTION_FOLD
ACTION_CHECK_CALL
ACTION_BET
ACTION_ALL_IN
Definition at line 57 of file universal_poker.h.
                     {
  ACTION_DEAL = 1,
  ACTION_FOLD = 2,
  ACTION_CHECK_CALL = 4,
  ACTION_BET = 8,
  ACTION_ALL_IN = 16
};
Function Documentation
ACPCActionToOpenSpielAction()
open_spiel::Action open_spiel::universal_poker::ACPCActionToOpenSpielAction (const project_acpc_server::Action & action, const UniversalPokerState & state)
Definition at line 1342 of file universal_poker.cc.
{
  // We assign this here as we cannot initialize a variable within a switch
  // statement.
  const auto &up_game =
      static_cast<const UniversalPokerGame &>(*state.GetGame());
  switch (action.type) {
    case project_acpc_server::ActionType::a_fold:
      return ActionType::kFold;
    case project_acpc_server::ActionType::a_call:
      return ActionType::kCall;
    case project_acpc_server::ActionType::a_raise:
      SPIEL_CHECK_NE(state.betting(), BettingAbstraction::kFC);
      // The maximum utility is exactly equal to the all-in amount for both
      // players.
      if (action.size == up_game.MaxCommitment() * up_game.NumPlayers()) {
        return ActionType::kCall;
      }
      if (action.size == state.PotSize(0.5)) {
        return ActionType::kHalfPot;
      }
      if (action.size == state.PotSize()) return ActionType::kBet;
      if (action.size == state.AllInSize()) return ActionType::kAllIn;
      if (state.betting() == BettingAbstraction::kFCHPA) {
        return action.size;
      }
      if (state.betting() != BettingAbstraction::kFULLGAME) {
        SpielFatalError(absl::StrCat(
            "Unsupported bet size: ", action.size, ", pot: ", state.PotSize(),
            ", all_in: ", state.AllInSize(),
            ", max_commitment: ", state.acpc_state().raw_state().maxSpent,
            ", state: ", state.ToString(),
            ", history: ", state.HistoryString()));
      }
      SPIEL_CHECK_EQ(state.betting(), BettingAbstraction::kFULLGAME);
      return ActionType::kBet + action.size;
    case project_acpc_server::ActionType::a_invalid:
      SpielFatalError("Invalid action type.");
    default:
      SpielFatalError(absl::StrCat("Type not found. Type: ", action.type));
  }
  // Will never get called.
  return kInvalidAction;
}
References action, kAllIn, kBet, kCall, kFC, kFCHPA, kFold, kFULLGAME, kHalfPot, open_spiel::kInvalidAction, SPIEL_CHECK_EQ, SPIEL_CHECK_NE, open_spiel::SpielFatalError(), state, and absl::StrCat().
DistributeHands()
void open_spiel::universal_poker::DistributeHands (const logic::CardSet & full_deck, uint8_t num_players, uint8_t num_hole_cards, std::function< void(std::vector< std::vector< uint8_t > >)> yield)
Definition at line 603 of file universal_poker.cc.
{
  // Taken and modified from CardSet::SampleCards()
  int nbCards = num_hole_cards * num_players;
  uint64_t p = 0;
  for (int i = 0; i < nbCards; ++i) {
    p += (1 << i);
  }
  // Enumerates all the uint64_t integers that with nbCards 1-bits.
  // The final n is ignored. It is fine as long as the rank < 16 (a property
  // satisfied by CardSet, as ranks >= 16 are not representable).
  int n_choose_k = 0;
  for (uint64_t n = logic::bit_twiddle_permute(p); n > p;
       p = n, n = logic::bit_twiddle_permute(p)) {
    // Checks whether the CardSet represented by p is inside the CardSet.
    uint64_t combo = p & full_deck.cs.cards;
    if (__builtin_popcountl(combo) == nbCards) {
      // Generate all partitions of size num_hole_cards:
      logic::CardSet c;
      c.cs.cards = combo;
      std::vector<uint8_t> x = c.ToCardArray();
      yield({{x[0], x[1]}, {x[2], x[3]}});
      yield({{x[0], x[2]}, {x[1], x[3]}});
      yield({{x[0], x[3]}, {x[1], x[2]}});
      yield({{x[2], x[3]}, {x[0], x[1]}});
      yield({{x[1], x[3]}, {x[0], x[2]}});
      yield({{x[1], x[2]}, {x[0], x[3]}});
      ++n_choose_k;
    }
  }
  // 52 choose 4
  SPIEL_CHECK_EQ(n_choose_k, 270725);
}
References open_spiel::universal_poker::logic::bit_twiddle_permute(), open_spiel::universal_poker::logic::CardSet::CardSetUnion::cards, open_spiel::universal_poker::logic::CardSet::cs, i, n, SPIEL_CHECK_EQ, and x.
Factory()
std::shared_ptr< const Game > open_spiel::universal_poker::Factory (const GameParameters & params)
Definition at line 190 of file universal_poker.cc.
{
  return absl::make_unique<UniversalPokerGame>(params);
}
GetHoleCardsReachIndex()
int open_spiel::universal_poker::GetHoleCardsReachIndex (int card_a, int card_b, int num_suits, int num_ranks)
Definition at line 562 of file universal_poker.cc.
{
  // CardSet uses kSuitChars of "cdhs", but we need the inverse i.e. "shdc"
  // according to https://github.com/Sandholm-Lab/LibratusEndgames
  const int a_suit = num_suits - 1 - suitOfCard(card_a);
  const int b_suit = num_suits - 1 - suitOfCard(card_b);
  const int a_rank = rankOfCard(card_a);
  const int b_rank = rankOfCard(card_b);
  // Order by rank, then order by suit.
  const int lesser_card = a_rank < b_rank
                              || (a_rank == b_rank && a_suit < b_suit)
                          ? card_a : card_b;
  // We use ints, so this is ok.
  const int higher_card = card_a + card_b - lesser_card;
  const int lesser_suit = num_suits - 1 - suitOfCard(lesser_card);
  const int higher_suit = num_suits - 1 - suitOfCard(higher_card);
  const int lesser_rank = rankOfCard(lesser_card);
  const int higher_rank = rankOfCard(higher_card);
  // There is an ordering on the cards, which indexes an upper triangular matrix
  // like so (example for num_cards_in_deck=4)
  //
  //       j ->
  //     0 1 2 3
  //   0 # 0 1 2
  // i 1   # 3 4
  // | 2     # 5
  // v 3       #
  //
  const int i = lesser_rank * num_suits + lesser_suit;
  const int j = higher_rank * num_suits + higher_suit;
  const int n = num_suits * num_ranks;
  // Compute index k in the triangle.
  return i * (2*n - i - 3) / 2 + j - 1;
}
References i, and n.
GetMaxBettingActions()
uint32_t open_spiel::universal_poker::GetMaxBettingActions (const acpc_cpp::ACPCGame & acpc_game) inline
Definition at line 202 of file universal_poker.cc.
{
  return acpc_game.IsLimitGame() ? 3 : 4;
}
References open_spiel::universal_poker::acpc_cpp::ACPCGame::IsLimitGame().
Referenced by open_spiel::universal_poker::UniversalPokerGame::NumDistinctActions().
LoadUniversalPokerGameFromACPCGamedef()
std::shared_ptr< const Game > open_spiel::universal_poker::LoadUniversalPokerGameFromACPCGamedef (const std::string & acpc_gamedef)
Definition at line 1388 of file universal_poker.cc.
{
  return LoadGame(logic::GamedefToOpenSpielParameters(acpc_gamedef));
}
References open_spiel::universal_poker::logic::GamedefToOpenSpielParameters(), and open_spiel::LoadGame().
Referenced by main().
MakeRandomSubgame()
std::shared_ptr< const Game > open_spiel::universal_poker::MakeRandomSubgame (std::mt19937 & rng, int pot_size, std::string board_cards, std::vector< double > hand_reach)
Definition at line 1393 of file universal_poker.cc.
{
  constexpr const char* base_game =
      "universal_poker("
      "betting=nolimit,"
      "numPlayers=2,"
      "numRounds=4,"
      "blind=100 50,"
      "firstPlayer=2 1 1 1,"
      "numSuits=4,"
      "numRanks=13,"
      "numHoleCards=2,"
      "numBoardCards=0 3 1 1,"
      "stack=20000 20000,"
      "bettingAbstraction=fcpa,"
      "potSize=%d,"
      "boardCards=%s,"
      "handReaches=%s"
    ")";
  if (pot_size == -1) {
    // 40k is total money in the game -- sum of the players stacks (20k+20k).
    // 50 is the size of the small blind, 2*50 is big blind = minimum pot size.
    // As both players need to match bets, the pot size must be divisible by 2.
    std::uniform_int_distribution<int> dist(50, 20000);
    pot_size = dist(rng) * 2;
  }
  if (board_cards.empty()) {
    // Pick a round, i.e. 3/4/5 cards.
    std::uniform_int_distribution<int> rnd_cards(3, 5);
    std::uniform_int_distribution<int> rnd_rank(0, MAX_RANKS);
    std::uniform_int_distribution<int> rnd_suit(0, MAX_SUITS);
    // Populate random non-repeating cards.
    int num_cards = rnd_cards(rng);
    std::vector<int> cards;
    cards.reserve(num_cards);
    while (cards.size() != num_cards) {
      int rank = rnd_rank(rng);
      int suit = rnd_suit(rng);
      int card = makeCard(rank, suit);
      if (std::find(cards.begin(), cards.end(), card) == cards.end()) {
        cards.push_back(card);
      }
    }
    logic::CardSet set(cards);
    board_cards = set.ToString();
  }
  if (hand_reach.empty()) {
    // Normally uniform_real_distribution is defined on open interval [0, 1)
    // We make it into a closed interval [0, 1] thanks to std::nextafter.
    double next_after_one = std::nextafter(1.0, 2.0);
    SPIEL_CHECK_NE(1.0, next_after_one);
    SPIEL_CHECK_LT(1.0, next_after_one);
    std::uniform_real_distribution<double> dist(0.0, next_after_one);
    for (int i = 0; i < 2*kSubgameUniqueHands; ++i) {
      hand_reach.push_back(dist(rng));
    }
  }
  std::string reach = absl::StrJoin(hand_reach.begin(), hand_reach.end(), " ");
  return LoadGame(absl::StrFormat(base_game, pot_size, board_cards, reach));
}
References i, kSubgameUniqueHands, open_spiel::LoadGame(), rank, SPIEL_CHECK_LT, SPIEL_CHECK_NE, absl::StrFormat(), absl::StrJoin(), and open_spiel::universal_poker::logic::CardSet::ToString().
operator<<()
std::ostream & open_spiel::universal_poker::operator<< (std::ostream & os, const BettingAbstraction & betting)
Definition at line 1456 of file universal_poker.cc.
{
  os << BettingAbstractionToString(betting);
  return os;
}
REGISTER_SPIEL_BOT()
open_spiel::universal_poker::REGISTER_SPIEL_BOT ("uniform_restricted_actions" , UniformRestrictedActionsFactory)
REGISTER_SPIEL_GAME()
open_spiel::universal_poker::REGISTER_SPIEL_GAME (kGameType , Factory)
single_tensor()
open_spiel::RegisterSingleTensorObserver open_spiel::universal_poker::single_tensor (kGameType. short_name)
Variable Documentation
actions
const char* open_spiel::universal_poker::actions = "0df0c000p0000000a"
Definition at line 1234 of file universal_poker.cc.
Referenced by open_spiel::universal_poker::UniversalPokerState::ApplyChoiceAction(), and open_spiel::universal_poker::UniversalPokerState::LegalActions().
ALL_ACTIONS
StateActionType open_spiel::universal_poker::ALL_ACTIONS[5] constexpr
Initial value:
= {
    ACTION_DEAL, ACTION_FOLD, ACTION_CHECK_CALL, ACTION_BET, ACTION_ALL_IN}
Definition at line 65 of file universal_poker.h.
{
    ACTION_DEAL, ACTION_FOLD, ACTION_CHECK_CALL, ACTION_BET, ACTION_ALL_IN};
Referenced by open_spiel::universal_poker::UniversalPokerState::ToString().
kGameType
const GameType open_spiel::universal_poker::kGameType
Definition at line 91 of file universal_poker.cc.
{
    /*short_name=*/"universal_poker",
    /*long_name=*/"Universal Poker",
    GameType::Dynamics::kSequential,
    GameType::ChanceMode::kExplicitStochastic,
    GameType::Information::kImperfectInformation,
    GameType::Utility::kZeroSum,
    GameType::RewardModel::kTerminal,
    /*max_num_players=*/10,
    /*min_num_players=*/2,
    /*provides_information_state_string=*/true,
    /*provides_information_state_tensor=*/true,
    /*provides_observation_string=*/true,
    /*provides_observation_tensor=*/true,
    /*parameter_specification=*/
    {
        // The ACPC code uses a specific configuration file to describe the
        // game. For more details, see
        // https://github.com/ethansbrown/acpc/blob/master/project_acpc_server/READMthird_party/open_spiel/integration_tests/playthrough_test.pyE
        // If you wish to construct a universal_poker game directly from one of
        // these ACPC gamedefs see the LoadUniversalPokerGameFromACPCGamedef()
        // wrapper function below.
        // (Note that this is just for convenience; we also support defining the
        // configuration as a typical OpenSpiel game state input. E.g. doing
        //   LoadGame("universal_poker(betting=limit,raiseSize=10 10 20,...)")
        // as per usual).
        // The following has been copied from ACPC documentation:
        //
        // Empty lines or lines with '#' as the very first character will be
        // ignored
        //
        // The Game definitions should start with "gamedef" and end with
        // "end gamedef" and can have the fields documented bellow (case is
        // ignored)
        //
        // If you are creating your own game definitions, please note that
        // game.h defines some constants for maximums in games (e.g., number of
        // rounds). These may need to be changed for games outside of the what
        // is being run for the Annual Computer Poker Competition.
        // The documentation below is adapted from project_acpc_server/game.cc.
        //
        // Number of Players (up to 10)
        {"numPlayers", GameParameter(2)},
        // Betting Type "limit" "nolimit"
        {"betting", GameParameter(std::string("nolimit"))},
        // The stack size for each player at the start of each hand (for
        // no-limit). It will be ignored on "limit".
        // TODO(author2): It's unclear what happens on limit. It defaults to
        // INT32_MAX for all players when not provided.
        {"stack", GameParameter(std::string("1200 1200"))},
        // The size of the blinds for each player (relative to the dealer)
        {"blind", GameParameter(std::string("100 100"))},
        // The size of raises on each round (for limit games only) as numrounds
        // integers. It will be ignored for nolimit games.
        {"raiseSize", GameParameter(std::string("100 100"))},
        // Number of betting rounds per hand of the game
        {"numRounds", GameParameter(2)},
        // The player that acts first (relative to the dealer) on each round
        {"firstPlayer", GameParameter(std::string("1 1"))},
        // maxraises - the maximum number of raises on each round. If not
        // specified, it will default to UINT8_MAX.
        {"maxRaises", GameParameter(std::string(""))},
        // The number of different suits in the deck
        {"numSuits", GameParameter(4)},
        // The number of different ranks in the deck
        {"numRanks", GameParameter(6)},
        // The number of private cards to  deal to each player
        {"numHoleCards", GameParameter(1)},
        // The number of cards revealed on each round
        {"numBoardCards", GameParameter(std::string("0 1"))},
        // Specify which actions are available to the player, in both limit and
        // nolimit games. Available options are: "fc" for fold and check/call.
        // "fcpa" for fold, check/call, bet pot and all in (default).
        // Use "fullgame" for the unabstracted game.
        {"bettingAbstraction", GameParameter(std::string("fcpa"))},
        // ------------------------------------------------------------------------
        // Following parameters are used to specify specific subgame.
        {"potSize", GameParameter(0)},
        // Board cards that have been revealed. Must be in the format
        // of logic::CardSet -- kSuitChars, kRankChars
        {"boardCards", GameParameter("")},
        // A space separated list of reach probabilities for each player in a
        // subgame. When there are in total N cards in the deck, two players,
        // and each player gets 2 cards, there should be:
        //
        //   N*(N-1) / 2                     * 2                 = N*(N-1)
        //           ^ ignore card order     ^ number of players
        //
        // N*(N-1) reach probabilities.
        // Currently supported only for the setting of 2 players, 4 suits, 13
        // cards
        {"handReaches", GameParameter("")},
    }};
kMaxUniversalPokerPlayers
uint8_t open_spiel::universal_poker::kMaxUniversalPokerPlayers = 10 constexpr
Definition at line 44 of file universal_poker.h.
kNumActionsFCHPA
int open_spiel::universal_poker::kNumActionsFCHPA inline constexpr
Initial value:
=
    static_cast<int>(ActionType::kHalfPot) + 1
Definition at line 51 of file universal_poker.h.
Referenced by open_spiel::universal_poker::UniversalPokerGame::NumDistinctActions().
kSubgameUniqueHands
int open_spiel::universal_poker::kSubgameUniqueHands = 1326 constexpr
Definition at line 313 of file universal_poker.h.
Referenced by MakeRandomSubgame(), and open_spiel::universal_poker::UniversalPokerState::UniversalPokerState().