open spiel: open_spiel::mancala Namespace Reference
open_spiel::mancala Namespace Reference
Classes
class MancalaGame
class MancalaState
Variables
constexpr int kNumPlayers = 2
constexpr int kNumPits = 6
constexpr int kTotalPits = (kNumPits + 1) * 2
Variable Documentation
kNumPits
int open_spiel::mancala::kNumPits = 6 inline constexpr
Definition at line 40 of file mancala.h.
Referenced by open_spiel::mancala::MancalaState::IsTerminal(), open_spiel::mancala::MancalaState::LegalActions(), and open_spiel::mancala::MancalaState::ToString().
kNumPlayers
int open_spiel::mancala::kNumPlayers = 2 inline constexpr
Definition at line 39 of file mancala.h.
Referenced by open_spiel::mancala::MancalaGame::NumPlayers().
kTotalPits
int open_spiel::mancala::kTotalPits = (kNumPits + 1) * 2 inline constexpr
Definition at line 41 of file mancala.h.
Referenced by open_spiel::mancala::MancalaGame::NumDistinctActions(), open_spiel::mancala::MancalaState::ObservationTensor(), open_spiel::mancala::MancalaGame::ObservationTensorShape(), and open_spiel::mancala::MancalaState::Returns().