open spiel: absl::base_internal Namespace Reference
absl::base_internal Namespace Reference
Classes
class AtomicHook
class AtomicHook< ReturnType(*)(Args...)>
struct Callable
class CycleClock
class CycleClockSource
struct DataMemAndPtr
struct DataMemAndRef
class ErrnoSaver
struct FastTypeTag
struct Invoker
struct IsInvocableRImpl
struct IsInvocableRImpl< absl::void_t< absl::base_internal::invoke_result_t< F, Args... > >, R, F, Args... >
class LowLevelAlloc
struct MemFunAndPtr
struct MemFunAndRef
struct PerThreadSynch
class SchedulingGuard
class SchedulingHelper
class ScopedSetEnv
class SpinLock
class SpinLockHolder
struct SpinLockTest
struct SpinLockWaitTransition
struct StrippedAccept
struct ThreadIdentity
Typedefs
using CycleClockSourceFunc = int64_t (*)()
using FastTypeIdType = const void*
template<typename F , typename... Args>
using invoke_result_t
template<typename R , typename F , typename... Args>
using is_invocable_r = IsInvocableRImpl<void, R, F, Args...>
using ThreadIdentityReclaimerFunction = void (*)(void*)
Enumerations
enum { kOnceInit = 0 , kOnceRunning = 0x65C2937B , kOnceWaiter = 0x05A308D2 , kOnceDone = 221 }
enum SchedulingMode { SCHEDULE_KERNEL_ONLY = 0 , SCHEDULE_COOPERATIVE_AND_KERNEL }
Functions
std::atomic< uint32_t > * ControlWord (absl::once_flag *flag)
template<typename Callable , typename... Args>
void LowLevelCallOnce (absl::once_flag *flag, Callable &&fn, Args &&... args)
template<typename Callable , typename... Args>
ABSL_ATTRIBUTE_NOINLINE void CallOnceImpl (std::atomic< uint32_t > *control, base_internal::SchedulingMode scheduling_mode, Callable &&fn, Args &&... args)
template<typename Type >
constexpr FastTypeIdType FastTypeId ()
constexpr uintptr_t HideMask ()
template<class T >
uintptr_t HidePtr (T *ptr)
template<class T >
T * UnhidePtr (uintptr_t hidden)
template<typename F , typename... Args>
invoke_result_t< F, Args... > invoke (F &&f, Args &&... args)
void PrefetchT0 (const void *addr)
void PrefetchT1 (const void *addr)
void PrefetchT2 (const void *addr)
void PrefetchNta (const void *addr)
void RegisterSpinLockProfiler (void(*fn)(const void *contendedlock, int64_t wait_cycles))
uint32_t SpinLockWait (std::atomic< uint32_t > *w, int n, const SpinLockWaitTransition trans[], base_internal::SchedulingMode scheduling_mode)
int SpinLockSuggestedDelayNS (int loop)
void SpinLockWake (std::atomic< uint32_t > *w, bool all)
void SpinLockDelay (std::atomic< uint32_t > *w, uint32_t value, int loop, base_internal::SchedulingMode scheduling_mode)
std::string StrError (int errnum)
int NumCPUs ()
double NominalCPUFrequency ()
pid_t GetTID ()
pid_t GetCachedTID ()
ABSL_CONST_INIT void SetCurrentThreadIdentity (ThreadIdentity *identity, ThreadIdentityReclaimerFunction reclaimer)
ThreadIdentity * CurrentThreadIdentityIfPresent ()
void ClearCurrentThreadIdentity ()
void ThrowStdLogicError (const std::string &what_arg)
void ThrowStdLogicError (const char *what_arg)
void ThrowStdInvalidArgument (const std::string &what_arg)
void ThrowStdInvalidArgument (const char *what_arg)
void ThrowStdDomainError (const std::string &what_arg)
void ThrowStdDomainError (const char *what_arg)
void ThrowStdLengthError (const std::string &what_arg)
void ThrowStdLengthError (const char *what_arg)
void ThrowStdOutOfRange (const std::string &what_arg)
void ThrowStdOutOfRange (const char *what_arg)
void ThrowStdRuntimeError (const std::string &what_arg)
void ThrowStdRuntimeError (const char *what_arg)
void ThrowStdRangeError (const std::string &what_arg)
void ThrowStdRangeError (const char *what_arg)
void ThrowStdOverflowError (const std::string &what_arg)
void ThrowStdOverflowError (const char *what_arg)
void ThrowStdUnderflowError (const std::string &what_arg)
void ThrowStdUnderflowError (const char *what_arg)
void ThrowStdBadFunctionCall ()
void ThrowStdBadAlloc ()
template<typename T >
const T & ts_unchecked_read (const T &v) ABSL_NO_THREAD_SAFETY_ANALYSIS
template<typename T >
T & ts_unchecked_read (T &v) ABSL_NO_THREAD_SAFETY_ANALYSIS
Typedef Documentation
CycleClockSourceFunc
using absl::base_internal::CycleClockSourceFunc = int64_t (*)()
Definition at line 57 of file cycleclock.h.
FastTypeIdType
using absl::base_internal::FastTypeIdType = const void*
Definition at line 39 of file fast_type_id.h.
invoke_result_t
template<typename F , typename... Args> using absl::base_internal::invoke_result_t
Initial value:
 decltype(Invoker<F, Args...>::type::Invoke(
    std::declval<F>(), std::declval<Args>()...))
Definition at line 205 of file invoke.h.
is_invocable_r
template<typename R , typename F , typename... Args> using absl::base_internal::is_invocable_r = IsInvocableRImpl<void, R, F, Args...>
Definition at line 233 of file invoke.h.
ThreadIdentityReclaimerFunction
using absl::base_internal::ThreadIdentityReclaimerFunction = void (*)(void*)
Definition at line 179 of file thread_identity.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kOnceInit
kOnceRunning
kOnceWaiter
kOnceDone
Definition at line 135 of file call_once.h.
     {
  kOnceInit = 0,
  kOnceRunning = 0x65C2937B,
  kOnceWaiter = 0x05A308D2,
  // A very small constant is chosen for kOnceDone so that it fit in a single
  // compare with immediate instruction for most common ISAs.  This is verified
  // for x86, POWER and ARM.
  kOnceDone = 221,    // Random Number
};
SchedulingMode
enum absl::base_internal::SchedulingMode
Enumerator
SCHEDULE_KERNEL_ONLY
SCHEDULE_COOPERATIVE_AND_KERNEL
Definition at line 49 of file scheduling_mode.h.
                    {
  SCHEDULE_KERNEL_ONLY = 0,         // Allow scheduling only the host OS.
  SCHEDULE_COOPERATIVE_AND_KERNEL,  // Also allow cooperative scheduling.
};
Function Documentation
CallOnceImpl()
template<typename Callable , typename... Args> ABSL_ATTRIBUTE_NOINLINE void absl::base_internal::CallOnceImpl (std::atomic< uint32_t > * control, base_internal::SchedulingMode scheduling_mode, Callable && fn, Args &&... args)
Definition at line 147 of file call_once.h.
{
#ifndef NDEBUG
  {
    uint32_t old_control = control->load(std::memory_order_relaxed);
    if (old_control != kOnceInit &&
        old_control != kOnceRunning &&
        old_control != kOnceWaiter &&
        old_control != kOnceDone) {
      ABSL_RAW_LOG(FATAL, "Unexpected value for control word: 0x%lx",
                   static_cast<unsigned long>(old_control));  // NOLINT
    }
  }
#endif  // NDEBUG
  static const base_internal::SpinLockWaitTransition trans[] = {
      {kOnceInit, kOnceRunning, true},
      {kOnceRunning, kOnceWaiter, false},
      {kOnceDone, kOnceDone, true}};
  // Must do this before potentially modifying control word's state.
  base_internal::SchedulingHelper maybe_disable_scheduling(scheduling_mode);
  // Short circuit the simplest case to avoid procedure call overhead.
  // The base_internal::SpinLockWait() call returns either kOnceInit or
  // kOnceDone. If it returns kOnceDone, it must have loaded the control word
  // with std::memory_order_acquire and seen a value of kOnceDone.
  uint32_t old_control = kOnceInit;
  if (control->compare_exchange_strong(old_control, kOnceRunning,
                                       std::memory_order_relaxed) ||
      base_internal::SpinLockWait(control, ABSL_ARRAYSIZE(trans), trans,
                                  scheduling_mode) == kOnceInit) {
    base_internal::invoke(std::forward<Callable>(fn),
                          std::forward<Args>(args)...);
    old_control =
        control->exchange(base_internal::kOnceDone, std::memory_order_release);
    if (old_control == base_internal::kOnceWaiter) {
      base_internal::SpinLockWake(control, true);
    }
  }  // else *control is already kOnceDone
}
References ABSL_ARRAYSIZE, ABSL_RAW_LOG, invoke(), kOnceDone, kOnceInit, kOnceRunning, kOnceWaiter, SpinLockWait(), and SpinLockWake().
Referenced by absl::call_once(), and LowLevelCallOnce().
ClearCurrentThreadIdentity()
void absl::base_internal::ClearCurrentThreadIdentity ()
Definition at line 132 of file thread_identity.cc.
{
#if ABSL_THREAD_IDENTITY_MODE == ABSL_THREAD_IDENTITY_MODE_USE_TLS || \
    ABSL_THREAD_IDENTITY_MODE == ABSL_THREAD_IDENTITY_MODE_USE_CPP11
  thread_identity_ptr = nullptr;
#elif ABSL_THREAD_IDENTITY_MODE == \
      ABSL_THREAD_IDENTITY_MODE_USE_POSIX_SETSPECIFIC
  // pthread_setspecific expected to clear value on destruction
  assert(CurrentThreadIdentityIfPresent() == nullptr);
#endif
}
References CurrentThreadIdentityIfPresent().
ControlWord()
std::atomic< uint32_t > * absl::base_internal::ControlWord (absl::once_flag * flag) inline
Definition at line 188 of file call_once.h.
{
  return &flag->control_;
}
Referenced by absl::call_once(), and LowLevelCallOnce().
CurrentThreadIdentityIfPresent()
ThreadIdentity * absl::base_internal::CurrentThreadIdentityIfPresent ()
Definition at line 128 of file thread_identity.cc.
{ return thread_identity_ptr; }
Referenced by ClearCurrentThreadIdentity(), absl::synchronization_internal::GetOrCreateCurrentThreadIdentity(), main(), and SetCurrentThreadIdentity().
FastTypeId()
template<typename Type > FastTypeIdType absl::base_internal::FastTypeId () inline constexpr
Definition at line 42 of file fast_type_id.h.
{
  return &FastTypeTag<Type>::dummy_var;
}
Referenced by absl::flags_internal::FlagOps(), absl::random_internal::DistributionCaller< typename >::Impl(), absl::CommandLineFlag::IsOfType(), absl::random_internal::MockHelpers::MockFor(), and absl::flags_internal::RetiredFlag< T >::Retire().
GetCachedTID()
pid_t absl::base_internal::GetCachedTID ()
Definition at line 500 of file sysinfo.cc.
                     {
#ifdef ABSL_HAVE_THREAD_LOCAL
  static thread_local pid_t thread_id = GetTID();
  return thread_id;
#else
  return GetTID();
#endif  // ABSL_HAVE_THREAD_LOCAL
}
References GetTID().
Referenced by absl::log_internal::LogMessage::LogMessageData::LogMessageData().
GetTID()
pid_t absl::base_internal::GetTID ()
Definition at line 456 of file sysinfo.cc.
               {
  absl::call_once(tid_once, InitGetTID);
  intptr_t tid = reinterpret_cast<intptr_t>(pthread_getspecific(tid_key));
  if (tid != 0) {
    return static_cast<pid_t>(tid);
  }
  int bit;  // tid_array[word] = 1u << bit;
  size_t word;
  {
    // Search for the first unused ID.
    absl::base_internal::SpinLockHolder lock(&tid_lock);
    // First search for a word in the array that is not all ones.
    word = 0;
    while (word < tid_array->size() && ~(*tid_array)[word] == 0) {
      ++word;
    }
    if (word == tid_array->size()) {
      tid_array->push_back(0);  // No space left, add kBitsPerWord more IDs.
    }
    // Search for a zero bit in the word.
    bit = 0;
    while (bit < kBitsPerWord && (((*tid_array)[word] >> bit) & 1) != 0) {
      ++bit;
    }
    tid =
        static_cast<intptr_t>((word * kBitsPerWord) + static_cast<size_t>(bit));
    (*tid_array)[word] |= 1u << bit;  // Mark the TID as allocated.
  }
  if (pthread_setspecific(tid_key, reinterpret_cast<void *>(tid)) != 0) {
    perror("pthread_setspecific failed");
    abort();
  }
  return static_cast<pid_t>(tid);
}
References absl::call_once(), and size.
Referenced by GetCachedTID(), absl_log_internal::TEST_P(), absl_log_internal::TEST_P(), absl_log_internal::TEST_P(), and absl_log_internal::TEST_P().
HideMask()
uintptr_t absl::base_internal::HideMask () constexpr
Definition at line 28 of file hide_ptr.h.
{
  return (uintptr_t{0xF03A5F7BU} << (sizeof(uintptr_t) - 4) * 8) | 0xF03A5F7BU;
}
Referenced by HidePtr(), and UnhidePtr().
HidePtr()
template<class T > uintptr_t absl::base_internal::HidePtr (T * ptr) inline
Definition at line 36 of file hide_ptr.h.
{
  return reinterpret_cast<uintptr_t>(ptr) ^ HideMask();
}
References HideMask(), and ptr.
Referenced by absl::synchronization_internal::GraphCycles::GetId(), and absl::synchronization_internal::GraphCycles::RemoveNode().
invoke()
template<typename F , typename... Args> invoke_result_t< F, Args... > absl::base_internal::invoke (F && f, Args &&... args)
Definition at line 211 of file invoke.h.
{
  return Invoker<F, Args...>::type::Invoke(std::forward<F>(f),
                                           std::forward<Args>(args)...);
}
References absl::f.
Referenced by absl::functional_internal::Apply(), absl::utility_internal::apply_helper(), CallOnceImpl(), absl::functional_internal::InvokeFunction(), absl::functional_internal::InvokeObject(), absl::internal_any_invocable::InvokeR(), absl::cord_internal::InvokeReleaser(), absl::cord_internal::InvokeReleaser(), absl::variant_internal::ReachableSwitchCase< Op, I >::Run(), and absl::variant_internal::VisitIndicesSwitch< EndIndex >::Run().
LowLevelCallOnce()
template<typename Callable , typename... Args> void absl::base_internal::LowLevelCallOnce (absl::once_flag * flag, Callable && fn, Args &&... args)
Definition at line 193 of file call_once.h.
{
  std::atomic<uint32_t>* once = base_internal::ControlWord(flag);
  uint32_t s = once->load(std::memory_order_acquire);
  if (ABSL_PREDICT_FALSE(s != base_internal::kOnceDone)) {
    base_internal::CallOnceImpl(once, base_internal::SCHEDULE_KERNEL_ONLY,
                                std::forward<Callable>(fn),
                                std::forward<Args>(args)...);
  }
}
References ABSL_PREDICT_FALSE, CallOnceImpl(), ControlWord(), kOnceDone, once, absl::s, and SCHEDULE_KERNEL_ONLY.
Referenced by absl::base_internal::LowLevelAlloc::DefaultArena(), NominalCPUFrequency(), and NumCPUs().
NominalCPUFrequency()
double absl::base_internal::NominalCPUFrequency ()
Definition at line 362 of file sysinfo.cc.
{
  base_internal::LowLevelCallOnce(
      &init_nominal_cpu_frequency_once,
      []() { nominal_cpu_frequency = GetNominalCPUFrequency(); });
  return nominal_cpu_frequency;
}
References LowLevelCallOnce().
NumCPUs()
int absl::base_internal::NumCPUs ()
Definition at line 350 of file sysinfo.cc.
              {
  base_internal::LowLevelCallOnce(
      &init_num_cpus_once, []() { num_cpus = GetNumCPUs(); });
  return num_cpus;
}
References LowLevelCallOnce().
PrefetchNta()
void absl::base_internal::PrefetchNta (const void * addr) inline
Definition at line 131 of file prefetch.h.
{}
Referenced by absl::crc_internal::CRC32::Extend().
PrefetchT0()
void absl::base_internal::PrefetchT0 (const void * addr) inline
Definition at line 128 of file prefetch.h.
{}
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::prefetch().
PrefetchT1()
void absl::base_internal::PrefetchT1 (const void * addr) inline
Definition at line 129 of file prefetch.h.
{}
PrefetchT2()
void absl::base_internal::PrefetchT2 (const void * addr) inline
Definition at line 130 of file prefetch.h.
{}
RegisterSpinLockProfiler()
void absl::base_internal::RegisterSpinLockProfiler (void(* fn)(const void *contendedlock, int64_t wait_cycles))
Definition at line 65 of file spinlock.cc.
{
  submit_profile_data.Store(fn);
}
SetCurrentThreadIdentity()
void absl::base_internal::SetCurrentThreadIdentity (ThreadIdentity * identity, ThreadIdentityReclaimerFunction reclaimer)
Definition at line 71 of file thread_identity.cc.
{
  assert(CurrentThreadIdentityIfPresent() == nullptr);
  // Associate our destructor.
  // NOTE: This call to pthread_setspecific is currently the only immovable
  // barrier to CurrentThreadIdentity() always being async signal safe.
#if ABSL_THREAD_IDENTITY_MODE == ABSL_THREAD_IDENTITY_MODE_USE_POSIX_SETSPECIFIC
  // NOTE: Not async-safe.  But can be open-coded.
  absl::call_once(init_thread_identity_key_once, AllocateThreadIdentityKey,
                  reclaimer);
#if defined(__EMSCRIPTEN__) || defined(__MINGW32__)
  // Emscripten and MinGW pthread implementations does not support signals.
  // See https://kripken.github.io/emscripten-site/docs/porting/pthreads.html
  // for more information.
  pthread_setspecific(thread_identity_pthread_key,
                      reinterpret_cast<void*>(identity));
#else
  // We must mask signals around the call to setspecific as with current glibc,
  // a concurrent getspecific (needed for GetCurrentThreadIdentityIfPresent())
  // may zero our value.
  //
  // While not officially async-signal safe, getspecific within a signal handler
  // is otherwise OK.
  sigset_t all_signals;
  sigset_t curr_signals;
  sigfillset(&all_signals);
  pthread_sigmask(SIG_SETMASK, &all_signals, &curr_signals);
  pthread_setspecific(thread_identity_pthread_key,
                      reinterpret_cast<void*>(identity));
  pthread_sigmask(SIG_SETMASK, &curr_signals, nullptr);
#endif  // !__EMSCRIPTEN__ && !__MINGW32__
#elif ABSL_THREAD_IDENTITY_MODE == ABSL_THREAD_IDENTITY_MODE_USE_TLS
  // NOTE: Not async-safe.  But can be open-coded.
  absl::call_once(init_thread_identity_key_once, AllocateThreadIdentityKey,
                  reclaimer);
  pthread_setspecific(thread_identity_pthread_key,
                      reinterpret_cast<void*>(identity));
  thread_identity_ptr = identity;
#elif ABSL_THREAD_IDENTITY_MODE == ABSL_THREAD_IDENTITY_MODE_USE_CPP11
  thread_local std::unique_ptr<ThreadIdentity, ThreadIdentityReclaimerFunction>
      holder(identity, reclaimer);
  thread_identity_ptr = identity;
#else
#error Unimplemented ABSL_THREAD_IDENTITY_MODE
#endif
}
References absl::call_once(), and CurrentThreadIdentityIfPresent().
Referenced by absl::synchronization_internal::CreateThreadIdentity().
SpinLockDelay()
void absl::base_internal::SpinLockDelay (std::atomic< uint32_t > * w, uint32_t value, int loop, base_internal::SchedulingMode scheduling_mode) inline
Definition at line 88 of file spinlock_wait.h.
{
  ABSL_INTERNAL_C_SYMBOL(AbslInternalSpinLockDelay)
  (w, value, loop, scheduling_mode);
}
References ABSL_INTERNAL_C_SYMBOL, AbslInternalSpinLockDelay(), and value.
Referenced by SpinLockWait().
SpinLockSuggestedDelayNS()
int absl::base_internal::SpinLockSuggestedDelayNS (int loop)
Definition at line 62 of file spinlock_wait.cc.
{
  // Weak pseudo-random number generator to get some spread between threads
  // when many are spinning.
  uint64_t r = delay_rand.load(std::memory_order_relaxed);
  r = 0x5deece66dLL * r + 0xb;   // numbers from nrand48()
  delay_rand.store(r, std::memory_order_relaxed);
  if (loop < 0 || loop > 32) {   // limit loop to 0..32
    loop = 32;
  }
  const int kMinDelay = 128 << 10;  // 128us
  // Double delay every 8 iterations, up to 16x (2ms).
  int delay = kMinDelay << (loop / 8);
  // Randomize in delay..2*delay range, for resulting 128us..4ms range.
  return delay | ((delay - 1) & static_cast<int>(r));
}
References r.
SpinLockWait()
uint32_t absl::base_internal::SpinLockWait (std::atomic< uint32_t > * w, int n, const SpinLockWaitTransition trans[], base_internal::SchedulingMode scheduling_mode)
Definition at line 39 of file spinlock_wait.cc.
{
  int loop = 0;
  for (;;) {
    uint32_t v = w->load(std::memory_order_acquire);
    int i;
    for (i = 0; i != n && v != trans[i].from; i++) {
    }
    if (i == n) {
      SpinLockDelay(w, v, ++loop, scheduling_mode);  // no matching transition
    } else if (trans[i].to == v ||                   // null transition
               w->compare_exchange_strong(v, trans[i].to,
                                          std::memory_order_acquire,
                                          std::memory_order_relaxed)) {
      if (trans[i].done) return v;
    }
  }
}
References absl::base_internal::SpinLockWaitTransition::from, absl::i, absl::n, SpinLockDelay(), absl::base_internal::SpinLockWaitTransition::to, to, and absl::v.
Referenced by CallOnceImpl().
SpinLockWake()
void absl::base_internal::SpinLockWake (std::atomic< uint32_t > * w, bool all) inline
Definition at line 83 of file spinlock_wait.h.
{
  ABSL_INTERNAL_C_SYMBOL(AbslInternalSpinLockWake)(w, all);
}
References ABSL_INTERNAL_C_SYMBOL, and AbslInternalSpinLockWake().
Referenced by CallOnceImpl().
StrError()
std::string absl::base_internal::StrError (int errnum)
Definition at line 77 of file strerror.cc.
{
  absl::base_internal::ErrnoSaver errno_saver;
  static const auto* table = NewStrErrorTable();
  if (errnum >= 0 && static_cast<size_t>(errnum) < table->size()) {
    return (*table)[static_cast<size_t>(errnum)];
  }
  return StrErrorInternal(errnum);
}
Referenced by absl::log_internal::LogMessage::Flush().
ThrowStdBadAlloc()
void absl::base_internal::ThrowStdBadAlloc ()
Definition at line 202 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::bad_alloc());
#else
  std::abort();
#endif
}
ThrowStdBadFunctionCall()
void absl::base_internal::ThrowStdBadFunctionCall ()
Definition at line 194 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::bad_function_call());
#else
  std::abort();
#endif
}
ThrowStdDomainError() [1/2]
void absl::base_internal::ThrowStdDomainError (const char * what_arg)
Definition at line 83 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::domain_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg);
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdDomainError() [2/2]
void absl::base_internal::ThrowStdDomainError (const std::string & what_arg)
Definition at line 75 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::domain_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg.c_str());
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdInvalidArgument() [1/2]
void absl::base_internal::ThrowStdInvalidArgument (const char * what_arg)
Definition at line 66 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::invalid_argument(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg);
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdInvalidArgument() [2/2]
void absl::base_internal::ThrowStdInvalidArgument (const std::string & what_arg)
Definition at line 58 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::invalid_argument(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg.c_str());
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdLengthError() [1/2]
void absl::base_internal::ThrowStdLengthError (const char * what_arg)
Definition at line 100 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::length_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg);
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdLengthError() [2/2]
void absl::base_internal::ThrowStdLengthError (const std::string & what_arg)
Definition at line 92 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::length_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg.c_str());
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdLogicError() [1/2]
void absl::base_internal::ThrowStdLogicError (const char * what_arg)
Definition at line 50 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::logic_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg);
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdLogicError() [2/2]
void absl::base_internal::ThrowStdLogicError (const std::string & what_arg)
Definition at line 42 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::logic_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg.c_str());
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdOutOfRange() [1/2]
void absl::base_internal::ThrowStdOutOfRange (const char * what_arg)
Definition at line 117 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::out_of_range(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg);
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdOutOfRange() [2/2]
void absl::base_internal::ThrowStdOutOfRange (const std::string & what_arg)
Definition at line 109 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::out_of_range(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg.c_str());
  std::abort();
#endif
}
References ABSL_RAW_LOG.
Referenced by absl::container_internal::btree_map_container< Tree >::at(), absl::container_internal::btree_map_container< Tree >::at(), absl::container_internal::raw_hash_map< Policy, Hash, Eq, Alloc >::at(), absl::container_internal::raw_hash_map< Policy, Hash, Eq, Alloc >::at(), absl::FixedArray< T, N, A >::at(), absl::FixedArray< T, N, A >::at(), absl::InlinedVector< T, N, A >::at(), absl::InlinedVector< T, N, A >::at(), absl::Span< T >::at(), absl::string_view::at(), absl::string_view::copy(), absl::Span< T >::first(), absl::Span< T >::last(), absl::Span< T >::subspan(), and absl::string_view::substr().
ThrowStdOverflowError() [1/2]
void absl::base_internal::ThrowStdOverflowError (const char * what_arg)
Definition at line 168 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::overflow_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg);
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdOverflowError() [2/2]
void absl::base_internal::ThrowStdOverflowError (const std::string & what_arg)
Definition at line 160 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::overflow_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg.c_str());
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdRangeError() [1/2]
void absl::base_internal::ThrowStdRangeError (const char * what_arg)
Definition at line 151 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::range_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg);
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdRangeError() [2/2]
void absl::base_internal::ThrowStdRangeError (const std::string & what_arg)
Definition at line 143 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::range_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg.c_str());
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdRuntimeError() [1/2]
void absl::base_internal::ThrowStdRuntimeError (const char * what_arg)
Definition at line 134 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::runtime_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg);
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdRuntimeError() [2/2]
void absl::base_internal::ThrowStdRuntimeError (const std::string & what_arg)
Definition at line 126 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::runtime_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg.c_str());
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdUnderflowError() [1/2]
void absl::base_internal::ThrowStdUnderflowError (const char * what_arg)
Definition at line 185 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::underflow_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg);
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ThrowStdUnderflowError() [2/2]
void absl::base_internal::ThrowStdUnderflowError (const std::string & what_arg)
Definition at line 177 of file throw_delegate.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  Throw(std::underflow_error(what_arg));
#else
  ABSL_RAW_LOG(FATAL, "%s", what_arg.c_str());
  std::abort();
#endif
}
References ABSL_RAW_LOG.
ts_unchecked_read() [1/2]
template<typename T > const T & absl::base_internal::ts_unchecked_read (const T & v) inline
Definition at line 322 of file thread_annotations.h.
{
  return v;
}
References absl::v.
ts_unchecked_read() [2/2]
template<typename T > T & absl::base_internal::ts_unchecked_read (T & v) inline
Definition at line 327 of file thread_annotations.h.
{
  return v;
}
References absl::v.
UnhidePtr()
template<class T > T * absl::base_internal::UnhidePtr (uintptr_t hidden) inline
Definition at line 43 of file hide_ptr.h.
{
  return reinterpret_cast<T*>(hidden ^ HideMask());
}
References HideMask().
Referenced by absl::synchronization_internal::GraphCycles::CheckInvariants(), and absl::synchronization_internal::GraphCycles::Ptr().