open spiel: open_spiel::phantom_go Namespace Reference
open_spiel::phantom_go Namespace Reference
Classes
class Neighbours4
class PhantomGoBoard
class PhantomGoGame
class PhantomGoObserver
class PhantomGoState
Typedefs
using VirtualPoint = uint16_t
Enumerations
enum class GoColor : uint8_t { kBlack = 0 , kWhite = 1 , kEmpty = 2 , kGuard = 3 }
Functions
char GoColorToChar (GoColor c)
constexpr int NumPlayers ()
constexpr double LossUtility ()
constexpr double WinUtility ()
constexpr int CellStates ()
constexpr double DrawUtility ()
int NumDistinctActions (int board_size)
int DefaultMaxGameLength (int board_size)
int MaxGameLength (int board_size)
int ColorToPlayer (GoColor c)
GoColor PlayerToColor (Player p)
int VirtualPointToBoardPoint (VirtualPoint p, int boardSize)
VirtualPoint VirtualPointFromBoardPoint (int boardPoint, int boardSize)
std::pair< int, int > VirtualPointTo2DPoint (VirtualPoint p)
VirtualPoint VirtualPointFrom2DPoint (std::pair< int, int > row_col)
Action VirtualActionToAction (int virtual_action, int board_size)
int ActionToVirtualAction (Action action, int board_size)
const std::vector< VirtualPoint > & BoardPoints (int board_size)
GoColor OppColor (GoColor c)
std::ostream & operator<< (std::ostream &os, GoColor c)
std::string GoColorToString (GoColor c)
std::ostream & operator<< (std::ostream &os, VirtualPoint p)
std::string VirtualPointToString (VirtualPoint p)
VirtualPoint MakePoint (std::string s)
std::ostream & operator<< (std::ostream &os, const PhantomGoBoard &board)
int NumSurroundedPoints (const PhantomGoBoard &board, const VirtualPoint p, std::array< bool, kVirtualBoardPoints > *marked, bool *reached_black, bool *reached_white)
float TrompTaylorScore (const PhantomGoBoard &board, float komi, int handicap)
PhantomGoBoard CreateBoard (const std::string &initial_stones)
Variables
constexpr int kMaxBoardSize = 19
constexpr int kVirtualBoardSize = kMaxBoardSize + 2
constexpr int kVirtualBoardPoints
constexpr VirtualPoint kInvalidPoint = 0
constexpr VirtualPoint kVirtualPass = kVirtualBoardPoints + 1
Typedef Documentation
VirtualPoint
using open_spiel::phantom_go::VirtualPoint = uint16_t
Definition at line 53 of file phantom_go_board.h.
Enumeration Type Documentation
GoColor
enum class open_spiel::phantom_go::GoColor : uint8_t strong
Enumerator
kBlack
kWhite
kEmpty
kGuard
Definition at line 28 of file phantom_go_board.h.
: uint8_t { kBlack = 0, kWhite = 1, kEmpty = 2, kGuard = 3 };
Function Documentation
ActionToVirtualAction()
int open_spiel::phantom_go::ActionToVirtualAction (Action action, int board_size)
Definition at line 156 of file phantom_go_board.cc.
{
  if (action == board_size * board_size) return kVirtualPass;
  int row = action / board_size;
  int column = action % board_size;
  return (row + 1) * kVirtualBoardSize + (column + 1);
}
References action, kVirtualBoardSize, and kVirtualPass.
Referenced by open_spiel::phantom_go::PhantomGoBoard::ActionToVirtualAction().
BoardPoints()
const std::vector< VirtualPoint > & open_spiel::phantom_go::BoardPoints (int board_size)
Definition at line 163 of file phantom_go_board.cc.
{
#define CASE_GET_POINTS(n) \
  case n:                  \
    return GetBoardPoints<n>()
  switch (board_size) {
    CASE_GET_POINTS(2);
    CASE_GET_POINTS(3);
    CASE_GET_POINTS(4);
    CASE_GET_POINTS(5);
    CASE_GET_POINTS(6);
    CASE_GET_POINTS(7);
    CASE_GET_POINTS(8);
    CASE_GET_POINTS(9);
    CASE_GET_POINTS(10);
    CASE_GET_POINTS(11);
    CASE_GET_POINTS(12);
    CASE_GET_POINTS(13);
    CASE_GET_POINTS(14);
    CASE_GET_POINTS(15);
    CASE_GET_POINTS(16);
    CASE_GET_POINTS(17);
    CASE_GET_POINTS(18);
    CASE_GET_POINTS(19);
    default:
      SpielFatalError(absl::StrCat("unsupported size",
                                   board_size));
  }
#undef CASE_GET_POINTS
}
References CASE_GET_POINTS, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::phantom_go::PhantomGoBoard::Clear(), open_spiel::phantom_go::PhantomGoState::LegalActions(), operator<<(), and TrompTaylorScore().
CellStates()
int open_spiel::phantom_go::CellStates () inline constexpr
Definition at line 49 of file phantom_go.h.
{ return 3; }  // Black, white, empty.
Referenced by open_spiel::phantom_go::PhantomGoGame::ObservationTensorShape().
ColorToPlayer()
int open_spiel::phantom_go::ColorToPlayer (GoColor c) inline
Definition at line 69 of file phantom_go.h.
{ return static_cast<int>(c); }
Referenced by open_spiel::phantom_go::PhantomGoState::CurrentPlayer(), and open_spiel::phantom_go::PhantomGoState::Returns().
CreateBoard()
PhantomGoBoard open_spiel::phantom_go::CreateBoard (const std::string & initial_stones)
Definition at line 805 of file phantom_go_board.cc.
{
  PhantomGoBoard board(9);
  int row = 0;
  for (const auto &line : absl::StrSplit(initial_stones, '\n')) {
    int col = 0;
    bool stones_started = false;
    for (const auto &c : line) {
      if (c == ' ') {
        if (stones_started) {
          SpielFatalError(
              "Whitespace is only allowed at the start of "
              "the line. To represent empty intersections, "
              "use +");
        }
        continue;
      } else if (c == 'X') {
        stones_started = true;
        SPIEL_CHECK_TRUE(board.PlayMove(VirtualPointFrom2DPoint({row, col}),
                                        GoColor::kBlack));
      } else if (c == 'O') {
        stones_started = true;
        SPIEL_CHECK_TRUE(board.PlayMove(VirtualPointFrom2DPoint({row, col}),
                                        GoColor::kWhite));
      }
      col++;
    }
    row++;
  }
  return board;
}
References kBlack, kWhite, open_spiel::phantom_go::PhantomGoBoard::PlayMove(), SPIEL_CHECK_TRUE, open_spiel::SpielFatalError(), and absl::StrSplit().
DefaultMaxGameLength()
int open_spiel::phantom_go::DefaultMaxGameLength (int board_size) inline
Definition at line 63 of file phantom_go.h.
{
  return board_size * board_size * 4;
}
DrawUtility()
double open_spiel::phantom_go::DrawUtility () inline constexpr
Definition at line 53 of file phantom_go.h.
{ return 0; }
Referenced by open_spiel::phantom_go::PhantomGoState::Returns().
GoColorToChar()
char open_spiel::phantom_go::GoColorToChar (GoColor c)
Definition at line 205 of file phantom_go.cc.
{
  switch (c) {
    case GoColor::kBlack:
      return 'X';
    case GoColor::kWhite:
      return 'O';
    case GoColor::kEmpty:
      return '+';
    case GoColor::kGuard:
      return '#';
    default:
      SpielFatalError(absl::StrCat("Unknown color ", c, " in GoColorToChar."));
      return '!';
  }
}
References kBlack, kEmpty, kGuard, kWhite, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::phantom_go::PhantomGoBoard::ObservationToString(), and operator<<().
GoColorToString()
std::string open_spiel::phantom_go::GoColorToString (GoColor c)
Definition at line 214 of file phantom_go_board.cc.
{
  switch (c) {
    case GoColor::kBlack:
      return "B";
    case GoColor::kWhite:
      return "W";
    case GoColor::kEmpty:
      return "E";
    case GoColor::kGuard:
      return "G";
    default:
      SpielFatalError(
          absl::StrCat("Unknown color ", c, " in GoColorToString."));
      return "This will never return.";
  }
}
References kBlack, kEmpty, kGuard, kWhite, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::phantom_go::PhantomGoState::ActionToString(), operator<<(), and open_spiel::phantom_go::PhantomGoState::ToString().
LossUtility()
double open_spiel::phantom_go::LossUtility () inline constexpr
Definition at line 47 of file phantom_go.h.
{ return -1; }
Referenced by open_spiel::phantom_go::PhantomGoGame::MinUtility(), open_spiel::phantom_go::PhantomGoState::Returns(), and open_spiel::phantom_go::PhantomGoGame::UtilitySum().
MakePoint()
VirtualPoint open_spiel::phantom_go::MakePoint (std::string s)
Definition at line 250 of file phantom_go_board.cc.
{
  std::transform(s.begin(), s.end(), s.begin(), ::tolower);
  if (s == "pass") return kVirtualPass;
  if (s.size() < 2 || s.size() > 3) return kInvalidPoint;
  int col = s[0] < 'i' ? s[0] - 'a' : s[0] - 'a' - 1;
  int row = s[1] - '0';
  if (s.size() == 3) {
    row *= 10;
    row += s[2] - '0';
  }
  return VirtualPointFrom2DPoint({row - 1, col});
}
References kInvalidPoint, kVirtualPass, and VirtualPointFrom2DPoint().
MaxGameLength()
int open_spiel::phantom_go::MaxGameLength (int board_size) inline
Definition at line 67 of file phantom_go.h.
{ return board_size * board_size * 4; }
NumDistinctActions()
int open_spiel::phantom_go::NumDistinctActions (int board_size) inline
Definition at line 56 of file phantom_go.h.
{
  return board_size * board_size + 1;
}
Referenced by open_spiel::phantom_go::PhantomGoGame::NumDistinctActions().
NumPlayers()
int open_spiel::phantom_go::NumPlayers () inline constexpr
Definition at line 46 of file phantom_go.h.
{ return 2; }
Referenced by open_spiel::phantom_go::PhantomGoGame::NumPlayers(), and open_spiel::phantom_go::PhantomGoState::Returns().
NumSurroundedPoints()
int open_spiel::phantom_go::NumSurroundedPoints (const PhantomGoBoard & board, const VirtualPoint p, std::array< bool, kVirtualBoardPoints > * marked, bool * reached_black, bool * reached_white)
Definition at line 732 of file phantom_go_board.cc.
{
  if ((*marked)[p]) return 0;
  (*marked)[p] = true;
  int num_points = 1;
  Neighbours(p, [&board, &num_points, marked, reached_black,
                 reached_white](VirtualPoint n) {
    switch (board.PointColor(n)) {
      case GoColor::kBlack:
        *reached_black = true;
        break;
      case GoColor::kWhite:
        *reached_white = true;
        break;
      case GoColor::kEmpty:
        num_points +=
            NumSurroundedPoints(board, n, marked, reached_black, reached_white);
        break;
      case GoColor::kGuard:
        // Ignore the border.
        break;
    }
  });
  return num_points;
}
References n, and open_spiel::phantom_go::PhantomGoBoard::PointColor().
Referenced by TrompTaylorScore().
operator<<() [1/3]
std::ostream & open_spiel::phantom_go::operator<< (std::ostream & os, const PhantomGoBoard & board)
Definition at line 686 of file phantom_go_board.cc.
{
  os << "\n";
  for (int row = board.board_size() - 1; row >= 0; --row) {
    os << std::setw(2) << std::setfill(' ') << (row + 1) << " ";
    for (int col = 0; col < board.board_size(); ++col) {
      os << GoColorToChar(
          board.PointColor(VirtualPointFrom2DPoint({row, col})));
    }
    os << std::endl;
  }
  std::string columns = "ABCDEFGHJKLMNOPQRST";
  os << "   " << columns.substr(0, board.board_size()) << std::endl;
  // Encode the stones and print a URL that can be used to view the board.
  std::string encoded;
  for (VirtualPoint p : BoardPoints(board.board_size())) {
    if (!board.IsEmpty(p)) {
      encoded += MoveAsAscii(p, board.PointColor(p));
    }
  }
  // TODO(author9): Make this a public URL.
  // os << "http://jumper/goboard/" << encoded << "&size=" << board.board_size()
  //    << std::endl;
  return os;
}
References open_spiel::phantom_go::PhantomGoBoard::board_size(), BoardPoints(), GoColorToChar(), open_spiel::phantom_go::PhantomGoBoard::IsEmpty(), and open_spiel::phantom_go::PhantomGoBoard::PointColor().
operator<<() [2/3]
std::ostream & open_spiel::phantom_go::operator<< (std::ostream & os, GoColor c)
Definition at line 210 of file phantom_go_board.cc.
{
  return os << GoColorToString(c);
}
References GoColorToString().
operator<<() [3/3]
std::ostream & open_spiel::phantom_go::operator<< (std::ostream & os, VirtualPoint p)
Definition at line 231 of file phantom_go_board.cc.
{
  return os << VirtualPointToString(p);
}
References VirtualPointToString().
OppColor()
GoColor open_spiel::phantom_go::OppColor (GoColor c)
Definition at line 195 of file phantom_go_board.cc.
{
  switch (c) {
    case GoColor::kBlack:
      return GoColor::kWhite;
    case GoColor::kWhite:
      return GoColor::kBlack;
    case GoColor::kEmpty:
    case GoColor::kGuard:
      return c;
    default:
      SpielFatalError(absl::StrCat("Unknown color ", c, " in OppColor."));
      return c;
  }
}
References kBlack, kEmpty, kGuard, kWhite, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::phantom_go::PhantomGoState::DoApplyAction(), open_spiel::phantom_go::PhantomGoBoard::IsLegalMoveObserver(), open_spiel::phantom_go::PhantomGoBoard::OppIter(), and open_spiel::phantom_go::PhantomGoBoard::PlayMove().
PlayerToColor()
GoColor open_spiel::phantom_go::PlayerToColor (Player p) inline
Definition at line 70 of file phantom_go.h.
{ return static_cast<GoColor>(p); }
TrompTaylorScore()
float open_spiel::phantom_go::TrompTaylorScore (const PhantomGoBoard & board, float komi, int handicap)
Definition at line 761 of file phantom_go_board.cc.
{
  // The delta of how many points on the board black and white have occupied,
  // from black's point of view, i.e. Black points - White points.
  int occupied_delta = 0;
  // We need to keep track of which empty points we've already counted as part
  // of a larger territory.
  std::array<bool, kVirtualBoardPoints> marked;
  marked.fill(false);
  for (VirtualPoint p : BoardPoints(board.board_size())) {
    switch (board.PointColor(p)) {
      case GoColor::kBlack:
        ++occupied_delta;
        break;
      case GoColor::kWhite:
        --occupied_delta;
        break;
      case GoColor::kEmpty: {
        if (marked[p]) continue;
        // If some empty points are surrounded entirely by one player, they
        // count as that player's territory.
        bool reached_black = false, reached_white = false;
        int n = NumSurroundedPoints(board, p, &marked, &reached_black,
                                    &reached_white);
        if (reached_black && !reached_white) {
          occupied_delta += n;
        } else if (!reached_black && reached_white) {
          occupied_delta -= n;
        }
        break;
      }
      case GoColor::kGuard:
        SpielFatalError("unexpected color");
    }
  }
  float score = occupied_delta - komi;
  if (handicap >= 2) {
    score -= handicap;
  }
  return score;
}
References open_spiel::phantom_go::PhantomGoBoard::board_size(), BoardPoints(), kBlack, kEmpty, kGuard, kWhite, n, NumSurroundedPoints(), open_spiel::phantom_go::PhantomGoBoard::PointColor(), and open_spiel::SpielFatalError().
Referenced by open_spiel::phantom_go::PhantomGoState::Returns().
VirtualActionToAction()
Action open_spiel::phantom_go::VirtualActionToAction (int virtual_action, int board_size)
Definition at line 149 of file phantom_go_board.cc.
{
  if (virtual_action == kVirtualPass) return board_size * board_size;
  const int virtual_row = static_cast<int>(virtual_action) / kVirtualBoardSize;
  const int virtual_col = static_cast<int>(virtual_action) % kVirtualBoardSize;
  return board_size * (virtual_row - 1) + (virtual_col - 1);
}
References kVirtualBoardSize, and kVirtualPass.
Referenced by open_spiel::phantom_go::PhantomGoBoard::VirtualActionToAction().
VirtualPointFrom2DPoint()
VirtualPoint open_spiel::phantom_go::VirtualPointFrom2DPoint (std::pair< int, int > row_col)
Definition at line 141 of file phantom_go_board.cc.
{
  return static_cast<VirtualPoint>((row_col.first + 1) * kVirtualBoardSize +
                                   row_col.second + 1);
}
References kVirtualBoardSize.
Referenced by MakePoint(), and VirtualPointFromBoardPoint().
VirtualPointFromBoardPoint()
VirtualPoint open_spiel::phantom_go::VirtualPointFromBoardPoint (int boardPoint, int boardSize)
Definition at line 126 of file phantom_go_board.cc.
{
  std::pair<int, int> pair;
  pair.second = boardPoint % boardSize;
  pair.first = boardPoint / boardSize;
  return VirtualPointFrom2DPoint(pair);
}
References pair, and VirtualPointFrom2DPoint().
Referenced by open_spiel::phantom_go::PhantomGoBoard::PlayMove().
VirtualPointTo2DPoint()
std::pair< int, int > open_spiel::phantom_go::VirtualPointTo2DPoint (VirtualPoint p)
Definition at line 133 of file phantom_go_board.cc.
{
  if (p == kInvalidPoint || p == kVirtualPass) return std::make_pair(-1, -1);
  const int row = static_cast<int>(p) / kVirtualBoardSize;
  const int col = static_cast<int>(p) % kVirtualBoardSize;
  return std::make_pair(row - 1, col - 1);
}
References kInvalidPoint, kVirtualBoardSize, and kVirtualPass.
Referenced by open_spiel::phantom_go::PhantomGoBoard::IsInBoardArea(), VirtualPointToBoardPoint(), and VirtualPointToString().
VirtualPointToBoardPoint()
int open_spiel::phantom_go::VirtualPointToBoardPoint (VirtualPoint p, int boardSize)
Definition at line 121 of file phantom_go_board.cc.
{
  std::pair<int, int> pair = VirtualPointTo2DPoint(p);
  return pair.first * boardSize + pair.second;
}
References pair, and VirtualPointTo2DPoint().
Referenced by open_spiel::phantom_go::PhantomGoBoard::IsLegalMove(), and open_spiel::phantom_go::PhantomGoBoard::PlayMove().
VirtualPointToString()
std::string open_spiel::phantom_go::VirtualPointToString (VirtualPoint p)
Definition at line 235 of file phantom_go_board.cc.
{
  switch (p) {
    case kInvalidPoint:
      return "INVALID_POINT";
    case kVirtualPass:
      return "PASS";
    default: {
      auto row_col = VirtualPointTo2DPoint(p);
      char col = 'a' + row_col.second;
      if (col >= 'i') ++col;  // Go / SGF labeling skips 'i'.
      return absl::StrCat(std::string(1, col), row_col.first + 1);
    }
  }
}
References kInvalidPoint, kVirtualPass, absl::StrCat(), and VirtualPointTo2DPoint().
Referenced by open_spiel::phantom_go::PhantomGoState::ActionToString(), and operator<<().
WinUtility()
double open_spiel::phantom_go::WinUtility () inline constexpr
Definition at line 48 of file phantom_go.h.
{ return 1; }
Referenced by open_spiel::phantom_go::PhantomGoGame::MaxUtility(), open_spiel::phantom_go::PhantomGoState::Returns(), and open_spiel::phantom_go::PhantomGoGame::UtilitySum().
Variable Documentation
kInvalidPoint
VirtualPoint open_spiel::phantom_go::kInvalidPoint = 0 inline constexpr
Definition at line 58 of file phantom_go_board.h.
Referenced by open_spiel::phantom_go::PhantomGoBoard::Clear(), MakePoint(), open_spiel::phantom_go::PhantomGoBoard::PlayMove(), VirtualPointTo2DPoint(), and VirtualPointToString().
kMaxBoardSize
int open_spiel::phantom_go::kMaxBoardSize = 19 inline constexpr
Definition at line 48 of file phantom_go_board.h.
kVirtualBoardPoints
int open_spiel::phantom_go::kVirtualBoardPoints inline constexpr
Initial value:
=
    kVirtualBoardSize * kVirtualBoardSize
Definition at line 50 of file phantom_go_board.h.
kVirtualBoardSize
int open_spiel::phantom_go::kVirtualBoardSize = kMaxBoardSize + 2 inline constexpr
Definition at line 49 of file phantom_go_board.h.
Referenced by ActionToVirtualAction(), VirtualActionToAction(), VirtualPointFrom2DPoint(), and VirtualPointTo2DPoint().
kVirtualPass
VirtualPoint open_spiel::phantom_go::kVirtualPass = kVirtualBoardPoints + 1 inline constexpr
Definition at line 59 of file phantom_go_board.h.
Referenced by ActionToVirtualAction(), open_spiel::phantom_go::PhantomGoBoard::IsLegalMoveObserver(), MakePoint(), open_spiel::phantom_go::PhantomGoBoard::PlayMove(), VirtualActionToAction(), VirtualPointTo2DPoint(), and VirtualPointToString().