open spiel: absl::numeric_internal Namespace Reference
absl::numeric_internal Namespace Reference
Functions
constexpr bool IsPowerOf2 (unsigned int x) noexcept
template<class T >
ABSL_MUST_USE_RESULT ABSL_ATTRIBUTE_ALWAYS_INLINE constexpr T RotateRight (T x, int s) noexcept
template<class T >
ABSL_MUST_USE_RESULT ABSL_ATTRIBUTE_ALWAYS_INLINE constexpr T RotateLeft (T x, int s) noexcept
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_POPCOUNT int Popcount32 (uint32_t x) noexcept
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_POPCOUNT int Popcount64 (uint64_t x) noexcept
template<class T >
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_POPCOUNT int Popcount (T x) noexcept
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ int CountLeadingZeroes32 (uint32_t x)
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ int CountLeadingZeroes16 (uint16_t x)
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ int CountLeadingZeroes64 (uint64_t x)
template<typename T >
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ int CountLeadingZeroes (T x)
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CTZ int CountTrailingZeroesNonzero32 (uint32_t x)
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CTZ int CountTrailingZeroesNonzero64 (uint64_t x)
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CTZ int CountTrailingZeroesNonzero16 (uint16_t x)
template<class T >
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CTZ int CountTrailingZeroes (T x) noexcept
template<class T >
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ std::enable_if< std::is_unsigned< T >::value, T >::type BitCeilPromotionHelper (T x, T promotion)
template<class T >
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ std::enable_if< std::is_unsigned< T >::value, T >::type BitCeilNonPowerOf2 (T x)
constexpr bool IsDoubleDouble ()
Function Documentation
BitCeilNonPowerOf2()
template<class T > ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ std::enable_if< std::is_unsigned< T >::value, T >::type absl::numeric_internal::BitCeilNonPowerOf2 (T x) inline
Definition at line 344 of file bits.h.
{
  // If T is narrower than unsigned, it undergoes promotion to unsigned when we
  // shift.  We calculate the number of bits added by the wider type.
  return BitCeilPromotionHelper(
      static_cast<T>(std::numeric_limits<T>::digits - CountLeadingZeroes(x)),
      T{sizeof(T) >= sizeof(unsigned) ? 0
                                      : std::numeric_limits<unsigned>::digits -
                                            std::numeric_limits<T>::digits});
}
References BitCeilPromotionHelper(), CountLeadingZeroes(), and absl::x.
Referenced by absl::bit_ceil().
BitCeilPromotionHelper()
template<class T > ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ std::enable_if< std::is_unsigned< T >::value, T >::type absl::numeric_internal::BitCeilPromotionHelper (T x, T promotion) inline
Definition at line 337 of file bits.h.
{
  return (T{1} << (x + promotion)) >> promotion;
}
References absl::x.
Referenced by BitCeilNonPowerOf2().
CountLeadingZeroes()
template<typename T > ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ int absl::numeric_internal::CountLeadingZeroes (T x) inline
Definition at line 234 of file bits.h.
{
  static_assert(std::is_unsigned<T>::value, "T must be unsigned");
  static_assert(IsPowerOf2(std::numeric_limits<T>::digits),
                "T must have a power-of-2 size");
  static_assert(sizeof(T) <= sizeof(uint64_t), "T too large");
  return sizeof(T) <= sizeof(uint16_t)
             ? CountLeadingZeroes16(static_cast<uint16_t>(x)) -
                   (std::numeric_limits<uint16_t>::digits -
                    std::numeric_limits<T>::digits)
             : (sizeof(T) <= sizeof(uint32_t)
                    ? CountLeadingZeroes32(static_cast<uint32_t>(x)) -
                          (std::numeric_limits<uint32_t>::digits -
                           std::numeric_limits<T>::digits)
                    : CountLeadingZeroes64(x));
}
References CountLeadingZeroes16(), CountLeadingZeroes32(), CountLeadingZeroes64(), IsPowerOf2(), and absl::x.
Referenced by BitCeilNonPowerOf2(), and absl::countl_zero().
CountLeadingZeroes16()
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ int absl::numeric_internal::CountLeadingZeroes16 (uint16_t x) inline
Definition at line 169 of file bits.h.
{
#if ABSL_HAVE_BUILTIN(__builtin_clzs)
  static_assert(sizeof(unsigned short) == sizeof(x),  // NOLINT(runtime/int)
                "__builtin_clzs does not take 16-bit arg");
  return x == 0 ? 16 : __builtin_clzs(x);
#else
  return CountLeadingZeroes32(x) - 16;
#endif
}
References CountLeadingZeroes32(), and absl::x.
Referenced by CountLeadingZeroes().
CountLeadingZeroes32()
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ int absl::numeric_internal::CountLeadingZeroes32 (uint32_t x) inline
Definition at line 133 of file bits.h.
{
#if ABSL_NUMERIC_INTERNAL_HAVE_BUILTIN_OR_GCC(__builtin_clz)
  // Use __builtin_clz, which uses the following instructions:
  //  x86: bsr, lzcnt
  //  ARM64: clz
  //  PPC: cntlzd
  static_assert(sizeof(unsigned int) == sizeof(x),
                "__builtin_clz does not take 32-bit arg");
  // Handle 0 as a special case because __builtin_clz(0) is undefined.
  return x == 0 ? 32 : __builtin_clz(x);
#elif defined(_MSC_VER) && !defined(__clang__)
  unsigned long result = 0;  // NOLINT(runtime/int)
  if (_BitScanReverse(&result, x)) {
    return 31 - result;
  }
  return 32;
#else
  int zeroes = 28;
  if (x >> 16) {
    zeroes -= 16;
    x >>= 16;
  }
  if (x >> 8) {
    zeroes -= 8;
    x >>= 8;
  }
  if (x >> 4) {
    zeroes -= 4;
    x >>= 4;
  }
  return "\4\3\2\2\1\1\1\1\0\0\0\0\0\0\0"[x] + zeroes;
#endif
}
References absl::x.
Referenced by CountLeadingZeroes(), and CountLeadingZeroes16().
CountLeadingZeroes64()
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CLZ int absl::numeric_internal::CountLeadingZeroes64 (uint64_t x) inline
Definition at line 180 of file bits.h.
{
#if ABSL_NUMERIC_INTERNAL_HAVE_BUILTIN_OR_GCC(__builtin_clzll)
  // Use __builtin_clzll, which uses the following instructions:
  //  x86: bsr, lzcnt
  //  ARM64: clz
  //  PPC: cntlzd
  static_assert(sizeof(unsigned long long) == sizeof(x),  // NOLINT(runtime/int)
                "__builtin_clzll does not take 64-bit arg");
  // Handle 0 as a special case because __builtin_clzll(0) is undefined.
  return x == 0 ? 64 : __builtin_clzll(x);
#elif defined(_MSC_VER) && !defined(__clang__) && \
    (defined(_M_X64) || defined(_M_ARM64))
  // MSVC does not have __buitin_clzll. Use _BitScanReverse64.
  unsigned long result = 0;  // NOLINT(runtime/int)
  if (_BitScanReverse64(&result, x)) {
    return 63 - result;
  }
  return 64;
#elif defined(_MSC_VER) && !defined(__clang__)
  // MSVC does not have __buitin_clzll. Compose two calls to _BitScanReverse
  unsigned long result = 0;  // NOLINT(runtime/int)
  if ((x >> 32) &&
      _BitScanReverse(&result, static_cast<unsigned long>(x >> 32))) {
    return 31 - result;
  }
  if (_BitScanReverse(&result, static_cast<unsigned long>(x))) {
    return 63 - result;
  }
  return 64;
#else
  int zeroes = 60;
  if (x >> 32) {
    zeroes -= 32;
    x >>= 32;
  }
  if (x >> 16) {
    zeroes -= 16;
    x >>= 16;
  }
  if (x >> 8) {
    zeroes -= 8;
    x >>= 8;
  }
  if (x >> 4) {
    zeroes -= 4;
    x >>= 4;
  }
  return "\4\3\2\2\1\1\1\1\0\0\0\0\0\0\0"[x] + zeroes;
#endif
}
References absl::x.
Referenced by CountLeadingZeroes().
CountTrailingZeroes()
template<class T > ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CTZ int absl::numeric_internal::CountTrailingZeroes (T x) inline noexcept
Definition at line 317 of file bits.h.
{
  static_assert(std::is_unsigned<T>::value, "T must be unsigned");
  static_assert(IsPowerOf2(std::numeric_limits<T>::digits),
                "T must have a power-of-2 size");
  static_assert(sizeof(T) <= sizeof(uint64_t), "T too large");
  return x == 0 ? std::numeric_limits<T>::digits
                : (sizeof(T) <= sizeof(uint16_t)
                       ? CountTrailingZeroesNonzero16(static_cast<uint16_t>(x))
                       : (sizeof(T) <= sizeof(uint32_t)
                              ? CountTrailingZeroesNonzero32(
                                    static_cast<uint32_t>(x))
                              : CountTrailingZeroesNonzero64(x)));
}
References CountTrailingZeroesNonzero16(), CountTrailingZeroesNonzero32(), CountTrailingZeroesNonzero64(), IsPowerOf2(), and absl::x.
Referenced by absl::countr_zero().
CountTrailingZeroesNonzero16()
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CTZ int absl::numeric_internal::CountTrailingZeroesNonzero16 (uint16_t x) inline
Definition at line 305 of file bits.h.
{
#if ABSL_HAVE_BUILTIN(__builtin_ctzs)
  static_assert(sizeof(unsigned short) == sizeof(x),  // NOLINT(runtime/int)
                "__builtin_ctzs does not take 16-bit arg");
  return __builtin_ctzs(x);
#else
  return CountTrailingZeroesNonzero32(x);
#endif
}
References CountTrailingZeroesNonzero32(), and absl::x.
Referenced by CountTrailingZeroes().
CountTrailingZeroesNonzero32()
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CTZ int absl::numeric_internal::CountTrailingZeroesNonzero32 (uint32_t x) inline
Definition at line 251 of file bits.h.
{
#if ABSL_NUMERIC_INTERNAL_HAVE_BUILTIN_OR_GCC(__builtin_ctz)
  static_assert(sizeof(unsigned int) == sizeof(x),
                "__builtin_ctz does not take 32-bit arg");
  return __builtin_ctz(x);
#elif defined(_MSC_VER) && !defined(__clang__)
  unsigned long result = 0;  // NOLINT(runtime/int)
  _BitScanForward(&result, x);
  return result;
#else
  int c = 31;
  x &= ~x + 1;
  if (x & 0x0000FFFF) c -= 16;
  if (x & 0x00FF00FF) c -= 8;
  if (x & 0x0F0F0F0F) c -= 4;
  if (x & 0x33333333) c -= 2;
  if (x & 0x55555555) c -= 1;
  return c;
#endif
}
References absl::c, and absl::x.
Referenced by CountTrailingZeroes(), and CountTrailingZeroesNonzero16().
CountTrailingZeroesNonzero64()
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_CTZ int absl::numeric_internal::CountTrailingZeroesNonzero64 (uint64_t x) inline
Definition at line 273 of file bits.h.
{
#if ABSL_NUMERIC_INTERNAL_HAVE_BUILTIN_OR_GCC(__builtin_ctzll)
  static_assert(sizeof(unsigned long long) == sizeof(x),  // NOLINT(runtime/int)
                "__builtin_ctzll does not take 64-bit arg");
  return __builtin_ctzll(x);
#elif defined(_MSC_VER) && !defined(__clang__) && \
    (defined(_M_X64) || defined(_M_ARM64))
  unsigned long result = 0;  // NOLINT(runtime/int)
  _BitScanForward64(&result, x);
  return result;
#elif defined(_MSC_VER) && !defined(__clang__)
  unsigned long result = 0;  // NOLINT(runtime/int)
  if (static_cast<uint32_t>(x) == 0) {
    _BitScanForward(&result, static_cast<unsigned long>(x >> 32));
    return result + 32;
  }
  _BitScanForward(&result, static_cast<unsigned long>(x));
  return result;
#else
  int c = 63;
  x &= ~x + 1;
  if (x & 0x00000000FFFFFFFF) c -= 32;
  if (x & 0x0000FFFF0000FFFF) c -= 16;
  if (x & 0x00FF00FF00FF00FF) c -= 8;
  if (x & 0x0F0F0F0F0F0F0F0F) c -= 4;
  if (x & 0x3333333333333333) c -= 2;
  if (x & 0x5555555555555555) c -= 1;
  return c;
#endif
}
References absl::c, and absl::x.
Referenced by CountTrailingZeroes().
IsDoubleDouble()
bool absl::numeric_internal::IsDoubleDouble () inline constexpr
Definition at line 28 of file representation.h.
{
  // A double-double value always has exactly twice the precision of a double
  // value--one double carries the high digits and one double carries the low
  // digits. This property is not shared with any other common floating-point
  // representation, so this test won't trigger false positives. For reference,
  // this table gives the number of bits of precision of each common
  // floating-point representation:
  //
  //                type     precision
  //         IEEE single          24 b
  //         IEEE double          53
  //     x86 long double          64
  //       double-double         106
  //      IEEE quadruple         113
  //
  // Note in particular that a quadruple-precision float has greater precision
  // than a double-double float despite taking up the same amount of memory; the
  // quad has more of its bits allocated to the mantissa than the double-double
  // has.
  return std::numeric_limits<long double>::digits ==
         2 * std::numeric_limits<double>::digits;
}
IsPowerOf2()
bool absl::numeric_internal::IsPowerOf2 (unsigned int x) constexpr noexcept
Definition at line 69 of file bits.h.
{
  return x != 0 && (x & (x - 1)) == 0;
}
References absl::x.
Referenced by CountLeadingZeroes(), CountTrailingZeroes(), Popcount(), RotateLeft(), and RotateRight().
Popcount()
template<class T > ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_POPCOUNT int absl::numeric_internal::Popcount (T x) inline noexcept
Definition at line 124 of file bits.h.
                       {
  static_assert(std::is_unsigned<T>::value, "T must be unsigned");
  static_assert(IsPowerOf2(std::numeric_limits<T>::digits),
                "T must have a power-of-2 size");
  static_assert(sizeof(x) <= sizeof(uint64_t), "T is too large");
  return sizeof(x) <= sizeof(uint32_t) ? Popcount32(x) : Popcount64(x);
}
References IsPowerOf2(), Popcount32(), Popcount64(), and absl::x.
Referenced by absl::popcount().
Popcount32()
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_POPCOUNT int absl::numeric_internal::Popcount32 (uint32_t x) inline noexcept
Definition at line 96 of file bits.h.
{
#if ABSL_NUMERIC_INTERNAL_HAVE_BUILTIN_OR_GCC(__builtin_popcount)
  static_assert(sizeof(unsigned int) == sizeof(x),
                "__builtin_popcount does not take 32-bit arg");
  return __builtin_popcount(x);
#else
  x -= ((x >> 1) & 0x55555555);
  x = ((x >> 2) & 0x33333333) + (x & 0x33333333);
  return static_cast<int>((((x + (x >> 4)) & 0xF0F0F0F) * 0x1010101) >> 24);
#endif
}
References absl::x.
Referenced by Popcount().
Popcount64()
ABSL_ATTRIBUTE_ALWAYS_INLINE ABSL_INTERNAL_CONSTEXPR_POPCOUNT int absl::numeric_internal::Popcount64 (uint64_t x) inline noexcept
Definition at line 109 of file bits.h.
{
#if ABSL_NUMERIC_INTERNAL_HAVE_BUILTIN_OR_GCC(__builtin_popcountll)
  static_assert(sizeof(unsigned long long) == sizeof(x),  // NOLINT(runtime/int)
                "__builtin_popcount does not take 64-bit arg");
  return __builtin_popcountll(x);
#else
  x -= (x >> 1) & 0x5555555555555555ULL;
  x = ((x >> 2) & 0x3333333333333333ULL) + (x & 0x3333333333333333ULL);
  return static_cast<int>(
      (((x + (x >> 4)) & 0xF0F0F0F0F0F0F0FULL) * 0x101010101010101ULL) >> 56);
#endif
}
References absl::x.
Referenced by Popcount().
RotateLeft()
template<class T > ABSL_MUST_USE_RESULT ABSL_ATTRIBUTE_ALWAYS_INLINE constexpr T absl::numeric_internal::RotateLeft (T x, int s) constexpr noexcept
Definition at line 85 of file bits.h.
{
  static_assert(std::is_unsigned<T>::value, "T must be unsigned");
  static_assert(IsPowerOf2(std::numeric_limits<T>::digits),
                "T must have a power-of-2 size");
  return static_cast<T>(x << (s & (std::numeric_limits<T>::digits - 1))) |
         static_cast<T>(x >> ((-s) & (std::numeric_limits<T>::digits - 1)));
}
References IsPowerOf2(), absl::s, and absl::x.
Referenced by absl::rotl().
RotateRight()
template<class T > ABSL_MUST_USE_RESULT ABSL_ATTRIBUTE_ALWAYS_INLINE constexpr T absl::numeric_internal::RotateRight (T x, int s) constexpr noexcept
Definition at line 74 of file bits.h.
{
  static_assert(std::is_unsigned<T>::value, "T must be unsigned");
  static_assert(IsPowerOf2(std::numeric_limits<T>::digits),
                "T must have a power-of-2 size");
  return static_cast<T>(x >> (s & (std::numeric_limits<T>::digits - 1))) |
         static_cast<T>(x << ((-s) & (std::numeric_limits<T>::digits - 1)));
}
References IsPowerOf2(), absl::s, and absl::x.
Referenced by absl::rotr().