open spiel: absl::time_internal::cctz::detail Namespace Reference
absl::time_internal::cctz::detail Namespace Reference
Namespaces
namespace impl
Classes
class civil_time
struct day_tag
struct fields
struct hour_tag
struct minute_tag
struct month_tag
struct second_tag
struct year_tag
Typedefs
using month_t = std::int_fast8_t
using day_t = std::int_fast8_t
using hour_t = std::int_fast8_t
using minute_t = std::int_fast8_t
using second_t = std::int_fast8_t
using civil_year = civil_time<year_tag>
using civil_month = civil_time<month_tag>
using civil_day = civil_time<day_tag>
using civil_hour = civil_time<hour_tag>
using civil_minute = civil_time<minute_tag>
using civil_second = civil_time<second_tag>
using femtoseconds = std::chrono::duration<std::int_fast64_t, std::femto>
Enumerations
enum class weekday {
monday , tuesday , wednesday , thursday ,
friday , saturday , sunday
}
Functions
CONSTEXPR_F fields step (second_tag, fields f, diff_t n) noexcept
CONSTEXPR_F fields step (minute_tag, fields f, diff_t n) noexcept
CONSTEXPR_F fields step (hour_tag, fields f, diff_t n) noexcept
CONSTEXPR_F fields step (day_tag, fields f, diff_t n) noexcept
CONSTEXPR_F fields step (month_tag, fields f, diff_t n) noexcept
CONSTEXPR_F fields step (year_tag, fields f, diff_t n) noexcept
CONSTEXPR_F diff_t difference (year_tag, fields f1, fields f2) noexcept
CONSTEXPR_F diff_t difference (month_tag, fields f1, fields f2) noexcept
CONSTEXPR_F diff_t difference (day_tag, fields f1, fields f2) noexcept
CONSTEXPR_F diff_t difference (hour_tag, fields f1, fields f2) noexcept
CONSTEXPR_F diff_t difference (minute_tag, fields f1, fields f2) noexcept
CONSTEXPR_F diff_t difference (second_tag, fields f1, fields f2) noexcept
CONSTEXPR_F fields align (second_tag, fields f) noexcept
CONSTEXPR_F fields align (minute_tag, fields f) noexcept
CONSTEXPR_F fields align (hour_tag, fields f) noexcept
CONSTEXPR_F fields align (day_tag, fields f) noexcept
CONSTEXPR_F fields align (month_tag, fields f) noexcept
CONSTEXPR_F fields align (year_tag, fields f) noexcept
template<typename T , typename U >
CONSTEXPR_F diff_t operator- (civil_time< T >, civil_time< U >)=delete
template<typename T1 , typename T2 >
CONSTEXPR_F bool operator< (const civil_time< T1 > &lhs, const civil_time< T2 > &rhs) noexcept
template<typename T1 , typename T2 >
CONSTEXPR_F bool operator<= (const civil_time< T1 > &lhs, const civil_time< T2 > &rhs) noexcept
template<typename T1 , typename T2 >
CONSTEXPR_F bool operator>= (const civil_time< T1 > &lhs, const civil_time< T2 > &rhs) noexcept
template<typename T1 , typename T2 >
CONSTEXPR_F bool operator> (const civil_time< T1 > &lhs, const civil_time< T2 > &rhs) noexcept
template<typename T1 , typename T2 >
CONSTEXPR_F bool operator== (const civil_time< T1 > &lhs, const civil_time< T2 > &rhs) noexcept
template<typename T1 , typename T2 >
CONSTEXPR_F bool operator!= (const civil_time< T1 > &lhs, const civil_time< T2 > &rhs) noexcept
CONSTEXPR_F weekday get_weekday (const civil_second &cs) noexcept
CONSTEXPR_F civil_day next_weekday (civil_day cd, weekday wd) noexcept
CONSTEXPR_F civil_day prev_weekday (civil_day cd, weekday wd) noexcept
CONSTEXPR_F int get_yearday (const civil_second &cs) noexcept
std::ostream & operator<< (std::ostream &os, const civil_year &y)
std::ostream & operator<< (std::ostream &os, const civil_month &m)
std::ostream & operator<< (std::ostream &os, const civil_day &d)
std::ostream & operator<< (std::ostream &os, const civil_hour &h)
std::ostream & operator<< (std::ostream &os, const civil_minute &m)
std::ostream & operator<< (std::ostream &os, const civil_second &s)
std::ostream & operator<< (std::ostream &os, weekday wd)
template<typename D >
std::pair< time_point< seconds >, D > split_seconds (const time_point< D > &tp)
std::pair< time_point< seconds >, seconds > split_seconds (const time_point< seconds > &tp)
std::string format (const std::string &, const time_point< seconds > &, const femtoseconds &, const time_zone &)
bool parse (const std::string &, const std::string &, const time_zone &, time_point< seconds > *, femtoseconds *, std::string *err=nullptr)
template<typename Rep , std::intmax_t Denom>
bool join_seconds (const time_point< seconds > &sec, const femtoseconds &fs, time_point< std::chrono::duration< Rep, std::ratio< 1, Denom > > > *tpp)
template<typename Rep , std::intmax_t Num>
bool join_seconds (const time_point< seconds > &sec, const femtoseconds &fs, time_point< std::chrono::duration< Rep, std::ratio< Num, 1 > > > *tpp)
template<typename Rep >
bool join_seconds (const time_point< seconds > &sec, const femtoseconds &fs, time_point< std::chrono::duration< Rep, std::ratio< 1, 1 > > > *tpp)
bool join_seconds (const time_point< seconds > &sec, const femtoseconds &, time_point< seconds > *tpp)
Typedef Documentation
civil_day
using absl::time_internal::cctz::detail::civil_day = civil_time<day_tag>
Definition at line 481 of file civil_time_detail.h.
civil_hour
using absl::time_internal::cctz::detail::civil_hour = civil_time<hour_tag>
Definition at line 482 of file civil_time_detail.h.
civil_minute
using absl::time_internal::cctz::detail::civil_minute = civil_time<minute_tag>
Definition at line 483 of file civil_time_detail.h.
civil_month
using absl::time_internal::cctz::detail::civil_month = civil_time<month_tag>
Definition at line 480 of file civil_time_detail.h.
civil_second
using absl::time_internal::cctz::detail::civil_second = civil_time<second_tag>
Definition at line 484 of file civil_time_detail.h.
civil_year
using absl::time_internal::cctz::detail::civil_year = civil_time<year_tag>
Definition at line 479 of file civil_time_detail.h.
day_t
using absl::time_internal::cctz::detail::day_t = std::int_fast8_t
Definition at line 52 of file civil_time_detail.h.
femtoseconds
using absl::time_internal::cctz::detail::femtoseconds = std::chrono::duration<std::int_fast64_t, std::femto>
Definition at line 267 of file time_zone.h.
hour_t
using absl::time_internal::cctz::detail::hour_t = std::int_fast8_t
Definition at line 53 of file civil_time_detail.h.
minute_t
using absl::time_internal::cctz::detail::minute_t = std::int_fast8_t
Definition at line 54 of file civil_time_detail.h.
month_t
using absl::time_internal::cctz::detail::month_t = std::int_fast8_t
Definition at line 51 of file civil_time_detail.h.
second_t
using absl::time_internal::cctz::detail::second_t = std::int_fast8_t
Definition at line 55 of file civil_time_detail.h.
Enumeration Type Documentation
weekday
enum class absl::time_internal::cctz::detail::weekday strong
Enumerator
monday
tuesday
wednesday
thursday
friday
saturday
sunday
Definition at line 535 of file civil_time_detail.h.
                   {
  monday,
  tuesday,
  wednesday,
  thursday,
  friday,
  saturday,
  sunday,
};
Function Documentation
align() [1/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::align (day_tag , fields f) noexcept
Definition at line 332 of file civil_time_detail.h.
{
  return fields{f.y, f.m, f.d, 0, 0, 0};
}
References absl::f, and absl::time_internal::cctz::detail::fields::y.
align() [2/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::align (hour_tag , fields f) noexcept
Definition at line 329 of file civil_time_detail.h.
{
  return fields{f.y, f.m, f.d, f.hh, 0, 0};
}
References absl::f, and absl::time_internal::cctz::detail::fields::y.
align() [3/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::align (minute_tag , fields f) noexcept
Definition at line 326 of file civil_time_detail.h.
{
  return fields{f.y, f.m, f.d, f.hh, f.mm, 0};
}
References absl::f, and absl::time_internal::cctz::detail::fields::y.
align() [4/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::align (month_tag , fields f) noexcept
Definition at line 335 of file civil_time_detail.h.
{
  return fields{f.y, f.m, 1, 0, 0, 0};
}
References absl::f, and absl::time_internal::cctz::detail::fields::y.
align() [5/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::align (second_tag , fields f) noexcept
Definition at line 325 of file civil_time_detail.h.
{ return f; }
References absl::f.
align() [6/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::align (year_tag , fields f) noexcept
Definition at line 338 of file civil_time_detail.h.
{
  return fields{f.y, 1, 1, 0, 0, 0};
}
References absl::f, and absl::time_internal::cctz::detail::fields::y.
difference() [1/6]
CONSTEXPR_F diff_t absl::time_internal::cctz::detail::difference (day_tag , fields f1, fields f2) noexcept
Definition at line 309 of file civil_time_detail.h.
{
  return impl::day_difference(f1.y, f1.m, f1.d, f2.y, f2.m, f2.d);
}
References absl::time_internal::cctz::detail::impl::day_difference().
difference() [2/6]
CONSTEXPR_F diff_t absl::time_internal::cctz::detail::difference (hour_tag , fields f1, fields f2) noexcept
Definition at line 312 of file civil_time_detail.h.
{
  return impl::scale_add(difference(day_tag{}, f1, f2), 24, (f1.hh - f2.hh));
}
References difference(), and absl::time_internal::cctz::detail::impl::scale_add().
difference() [3/6]
CONSTEXPR_F diff_t absl::time_internal::cctz::detail::difference (minute_tag , fields f1, fields f2) noexcept
Definition at line 315 of file civil_time_detail.h.
{
  return impl::scale_add(difference(hour_tag{}, f1, f2), 60, (f1.mm - f2.mm));
}
References difference(), and absl::time_internal::cctz::detail::impl::scale_add().
difference() [4/6]
CONSTEXPR_F diff_t absl::time_internal::cctz::detail::difference (month_tag , fields f1, fields f2) noexcept
Definition at line 306 of file civil_time_detail.h.
{
  return impl::scale_add(difference(year_tag{}, f1, f2), 12, (f1.m - f2.m));
}
References difference(), and absl::time_internal::cctz::detail::impl::scale_add().
difference() [5/6]
CONSTEXPR_F diff_t absl::time_internal::cctz::detail::difference (second_tag , fields f1, fields f2) noexcept
Definition at line 318 of file civil_time_detail.h.
{
  return impl::scale_add(difference(minute_tag{}, f1, f2), 60, f1.ss - f2.ss);
}
References difference(), and absl::time_internal::cctz::detail::impl::scale_add().
difference() [6/6]
CONSTEXPR_F diff_t absl::time_internal::cctz::detail::difference (year_tag , fields f1, fields f2) noexcept
Definition at line 303 of file civil_time_detail.h.
{
  return f1.y - f2.y;
}
Referenced by difference(), difference(), difference(), and difference().
format()
std::string absl::time_internal::cctz::detail::format (const std::string & format, const time_point< seconds > & tp, const femtoseconds & fs, const time_zone & tz)
Definition at line 333 of file time_zone_format.cc.
{
  std::string result;
  result.reserve(format.size());  // A reasonable guess for the result size.
  const time_zone::absolute_lookup al = tz.lookup(tp);
  const std::tm tm = ToTM(al);
  // Scratch buffer for internal conversions.
  char buf[3 + kDigits10_64];  // enough for longest conversion
  char* const ep = buf + sizeof(buf);
  char* bp;  // works back from ep
  // Maintain three, disjoint subsequences that span format.
  //   [format.begin() ... pending) : already formatted into result
  //   [pending ... cur) : formatting pending, but no special cases
  //   [cur ... format.end()) : unexamined
  // Initially, everything is in the unexamined part.
  const char* pending = format.c_str();  // NUL terminated
  const char* cur = pending;
  const char* end = pending + format.length();
  while (cur != end) {  // while something is unexamined
    // Moves cur to the next percent sign.
    const char* start = cur;
    while (cur != end && *cur != '%') ++cur;
    // If the new pending text is all ordinary, copy it out.
    if (cur != start && pending == start) {
      result.append(pending, static_cast<std::size_t>(cur - pending));
      pending = start = cur;
    }
    // Span the sequential percent signs.
    const char* percent = cur;
    while (cur != end && *cur == '%') ++cur;
    // If the new pending text is all percents, copy out one
    // percent for every matched pair, then skip those pairs.
    if (cur != start && pending == start) {
      std::size_t escaped = static_cast<std::size_t>(cur - pending) / 2;
      result.append(pending, escaped);
      pending += escaped * 2;
      // Also copy out a single trailing percent.
      if (pending != cur && cur == end) {
        result.push_back(*pending++);
      }
    }
    // Loop unless we have an unescaped percent.
    if (cur == end || (cur - percent) % 2 == 0) continue;
    // Simple specifiers that we handle ourselves.
    if (strchr("YmdeUuWwHMSzZs%", *cur)) {
      if (cur - 1 != pending) {
        FormatTM(&result, std::string(pending, cur - 1), tm);
      }
      switch (*cur) {
        case 'Y':
          // This avoids the tm.tm_year overflow problem for %Y, however
          // tm.tm_year will still be used by other specifiers like %D.
          bp = Format64(ep, 0, al.cs.year());
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'm':
          bp = Format02d(ep, al.cs.month());
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'd':
        case 'e':
          bp = Format02d(ep, al.cs.day());
          if (*cur == 'e' && *bp == '0') *bp = ' ';  // for Windows
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'U':
          bp = Format02d(ep, ToWeek(civil_day(al.cs), weekday::sunday));
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'u':
          bp = Format64(ep, 0, tm.tm_wday ? tm.tm_wday : 7);
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'W':
          bp = Format02d(ep, ToWeek(civil_day(al.cs), weekday::monday));
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'w':
          bp = Format64(ep, 0, tm.tm_wday);
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'H':
          bp = Format02d(ep, al.cs.hour());
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'M':
          bp = Format02d(ep, al.cs.minute());
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'S':
          bp = Format02d(ep, al.cs.second());
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'z':
          bp = FormatOffset(ep, al.offset, "");
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case 'Z':
          result.append(al.abbr);
          break;
        case 's':
          bp = Format64(ep, 0, ToUnixSeconds(tp));
          result.append(bp, static_cast<std::size_t>(ep - bp));
          break;
        case '%':
          result.push_back('%');
          break;
      }
      pending = ++cur;
      continue;
    }
    // More complex specifiers that we handle ourselves.
    if (*cur == ':' && cur + 1 != end) {
      if (*(cur + 1) == 'z') {
        // Formats %:z.
        if (cur - 1 != pending) {
          FormatTM(&result, std::string(pending, cur - 1), tm);
        }
        bp = FormatOffset(ep, al.offset, ":");
        result.append(bp, static_cast<std::size_t>(ep - bp));
        pending = cur += 2;
        continue;
      }
      if (*(cur + 1) == ':' && cur + 2 != end) {
        if (*(cur + 2) == 'z') {
          // Formats %::z.
          if (cur - 1 != pending) {
            FormatTM(&result, std::string(pending, cur - 1), tm);
          }
          bp = FormatOffset(ep, al.offset, ":*");
          result.append(bp, static_cast<std::size_t>(ep - bp));
          pending = cur += 3;
          continue;
        }
        if (*(cur + 2) == ':' && cur + 3 != end) {
          if (*(cur + 3) == 'z') {
            // Formats %:::z.
            if (cur - 1 != pending) {
              FormatTM(&result, std::string(pending, cur - 1), tm);
            }
            bp = FormatOffset(ep, al.offset, ":*:");
            result.append(bp, static_cast<std::size_t>(ep - bp));
            pending = cur += 4;
            continue;
          }
        }
      }
    }
    // Loop if there is no E modifier.
    if (*cur != 'E' || ++cur == end) continue;
    // Format our extensions.
    if (*cur == 'T') {
      // Formats %ET.
      if (cur - 2 != pending) {
        FormatTM(&result, std::string(pending, cur - 2), tm);
      }
      result.append("T");
      pending = ++cur;
    } else if (*cur == 'z') {
      // Formats %Ez.
      if (cur - 2 != pending) {
        FormatTM(&result, std::string(pending, cur - 2), tm);
      }
      bp = FormatOffset(ep, al.offset, ":");
      result.append(bp, static_cast<std::size_t>(ep - bp));
      pending = ++cur;
    } else if (*cur == '*' && cur + 1 != end && *(cur + 1) == 'z') {
      // Formats %E*z.
      if (cur - 2 != pending) {
        FormatTM(&result, std::string(pending, cur - 2), tm);
      }
      bp = FormatOffset(ep, al.offset, ":*");
      result.append(bp, static_cast<std::size_t>(ep - bp));
      pending = cur += 2;
    } else if (*cur == '*' && cur + 1 != end &&
               (*(cur + 1) == 'S' || *(cur + 1) == 'f')) {
      // Formats %E*S or %E*F.
      if (cur - 2 != pending) {
        FormatTM(&result, std::string(pending, cur - 2), tm);
      }
      char* cp = ep;
      bp = Format64(cp, 15, fs.count());
      while (cp != bp && cp[-1] == '0') --cp;
      switch (*(cur + 1)) {
        case 'S':
          if (cp != bp) *--bp = '.';
          bp = Format02d(bp, al.cs.second());
          break;
        case 'f':
          if (cp == bp) *--bp = '0';
          break;
      }
      result.append(bp, static_cast<std::size_t>(cp - bp));
      pending = cur += 2;
    } else if (*cur == '4' && cur + 1 != end && *(cur + 1) == 'Y') {
      // Formats %E4Y.
      if (cur - 2 != pending) {
        FormatTM(&result, std::string(pending, cur - 2), tm);
      }
      bp = Format64(ep, 4, al.cs.year());
      result.append(bp, static_cast<std::size_t>(ep - bp));
      pending = cur += 2;
    } else if (std::isdigit(*cur)) {
      // Possibly found %E#S or %E#f.
      int n = 0;
      if (const char* np = ParseInt(cur, 0, 0, 1024, &n)) {
        if (*np == 'S' || *np == 'f') {
          // Formats %E#S or %E#f.
          if (cur - 2 != pending) {
            FormatTM(&result, std::string(pending, cur - 2), tm);
          }
          bp = ep;
          if (n > 0) {
            if (n > kDigits10_64) n = kDigits10_64;
            bp = Format64(bp, n,
                          (n > 15) ? fs.count() * kExp10[n - 15]
                                   : fs.count() / kExp10[15 - n]);
            if (*np == 'S') *--bp = '.';
          }
          if (*np == 'S') bp = Format02d(bp, al.cs.second());
          result.append(bp, static_cast<std::size_t>(ep - bp));
          pending = cur = ++np;
        }
      }
    }
  }
  // Formats any remaining data.
  if (end != pending) {
    FormatTM(&result, std::string(pending, end), tm);
  }
  return result;
}
References absl::time_internal::cctz::time_zone::absolute_lookup::abbr, buf, absl::time_internal::cctz::time_zone::absolute_lookup::cs, absl::time_internal::cctz::detail::civil_time< T >::day(), format(), absl::time_internal::cctz::detail::civil_time< T >::hour(), absl::time_internal::cctz::detail::civil_time< T >::minute(), monday, absl::time_internal::cctz::detail::civil_time< T >::month(), absl::n, absl::time_internal::cctz::time_zone::absolute_lookup::offset, absl::time_internal::cctz::detail::civil_time< T >::second(), sunday, absl::ToTM(), absl::time_internal::cctz::ToUnixSeconds(), and absl::time_internal::cctz::detail::civil_time< T >::year().
Referenced by format(), absl::time_internal::cctz::format(), parse(), absl::time_internal::cctz::TEST(), and absl::time_internal::cctz::TEST().
get_weekday()
CONSTEXPR_F weekday absl::time_internal::cctz::detail::get_weekday (const civil_second & cs) noexcept
Definition at line 545 of file civil_time_detail.h.
{
  CONSTEXPR_D weekday k_weekday_by_mon_off[13] = {
      weekday::monday,    weekday::tuesday,  weekday::wednesday,
      weekday::thursday,  weekday::friday,   weekday::saturday,
      weekday::sunday,    weekday::monday,   weekday::tuesday,
      weekday::wednesday, weekday::thursday, weekday::friday,
      weekday::saturday,
  };
  CONSTEXPR_D int k_weekday_offsets[1 + 12] = {
      -1, 0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4,
  };
  year_t wd = 2400 + (cs.year() % 400) - (cs.month() < 3);
  wd += wd / 4 - wd / 100 + wd / 400;
  wd += k_weekday_offsets[cs.month()] + cs.day();
  return k_weekday_by_mon_off[wd % 7 + 6];
}
References CONSTEXPR_D, friday, monday, saturday, sunday, thursday, tuesday, and wednesday.
Referenced by next_weekday(), and prev_weekday().
get_yearday()
CONSTEXPR_F int absl::time_internal::cctz::detail::get_yearday (const civil_second & cs) noexcept
Definition at line 604 of file civil_time_detail.h.
{
  CONSTEXPR_D int k_month_offsets[1 + 12] = {
      -1, 0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334,
  };
  const int feb29 = (cs.month() > 2 && impl::is_leap_year(cs.year()));
  return k_month_offsets[cs.month()] + feb29 + cs.day();
}
References CONSTEXPR_D, and absl::time_internal::cctz::detail::impl::is_leap_year().
join_seconds() [1/4]
bool absl::time_internal::cctz::detail::join_seconds (const time_point< seconds > & sec, const femtoseconds & , time_point< seconds > * tpp) inline
Definition at line 447 of file time_zone.h.
{
  *tpp = sec;
  return true;
}
References sec.
join_seconds() [2/4]
template<typename Rep > bool absl::time_internal::cctz::detail::join_seconds (const time_point< seconds > & sec, const femtoseconds & fs, time_point< std::chrono::duration< Rep, std::ratio< 1, 1 > > > * tpp)
Definition at line 436 of file time_zone.h.
{
  using D = std::chrono::duration<Rep, std::ratio<1, 1>>;
  auto count = sec.time_since_epoch().count();
  if (count > (std::numeric_limits<Rep>::max)()) return false;
  if (count < (std::numeric_limits<Rep>::min)()) return false;
  *tpp = time_point<D>() + D{static_cast<Rep>(count)};
  return true;
}
References sec.
join_seconds() [3/4]
template<typename Rep , std::intmax_t Denom> bool absl::time_internal::cctz::detail::join_seconds (const time_point< seconds > & sec, const femtoseconds & fs, time_point< std::chrono::duration< Rep, std::ratio< 1, Denom > > > * tpp)
Definition at line 407 of file time_zone.h.
{
  using D = std::chrono::duration<Rep, std::ratio<1, Denom>>;
  // TODO(#199): Return false if result unrepresentable as a time_point<D>.
  *tpp = std::chrono::time_point_cast<D>(sec);
  *tpp += std::chrono::duration_cast<D>(fs);
  return true;
}
References sec.
Referenced by absl::time_internal::cctz::parse().
join_seconds() [4/4]
template<typename Rep , std::intmax_t Num> bool absl::time_internal::cctz::detail::join_seconds (const time_point< seconds > & sec, const femtoseconds & fs, time_point< std::chrono::duration< Rep, std::ratio< Num, 1 > > > * tpp)
Definition at line 418 of file time_zone.h.
{
  using D = std::chrono::duration<Rep, std::ratio<Num, 1>>;
  auto count = sec.time_since_epoch().count();
  if (count >= 0 || count % Num == 0) {
    count /= Num;
  } else {
    count /= Num;
    count -= 1;
  }
  if (count > (std::numeric_limits<Rep>::max)()) return false;
  if (count < (std::numeric_limits<Rep>::min)()) return false;
  *tpp = time_point<D>() + D{static_cast<Rep>(count)};
  return true;
}
References sec.
next_weekday()
CONSTEXPR_F civil_day absl::time_internal::cctz::detail::next_weekday (civil_day cd, weekday wd) noexcept
Definition at line 564 of file civil_time_detail.h.
{
  CONSTEXPR_D weekday k_weekdays_forw[14] = {
      weekday::monday,    weekday::tuesday,  weekday::wednesday,
      weekday::thursday,  weekday::friday,   weekday::saturday,
      weekday::sunday,    weekday::monday,   weekday::tuesday,
      weekday::wednesday, weekday::thursday, weekday::friday,
      weekday::saturday,  weekday::sunday,
  };
  weekday base = get_weekday(cd);
  for (int i = 0;; ++i) {
    if (base == k_weekdays_forw[i]) {
      for (int j = i + 1;; ++j) {
        if (wd == k_weekdays_forw[j]) {
          return cd + (j - i);
        }
      }
    }
  }
}
References CONSTEXPR_D, friday, get_weekday(), absl::i, monday, saturday, sunday, thursday, tuesday, and wednesday.
operator!=()
template<typename T1 , typename T2 > CONSTEXPR_F bool absl::time_internal::cctz::detail::operator!= (const civil_time< T1 > & lhs, const civil_time< T2 > & rhs) noexcept
Definition at line 528 of file civil_time_detail.h.
{
  return !(lhs == rhs);
}
operator-()
template<typename T , typename U > CONSTEXPR_F diff_t absl::time_internal::cctz::detail::operator- (civil_time< T > , civil_time< U >) delete
operator<()
template<typename T1 , typename T2 > CONSTEXPR_F bool absl::time_internal::cctz::detail::operator< (const civil_time< T1 > & lhs, const civil_time< T2 > & rhs) noexcept
Definition at line 491 of file civil_time_detail.h.
{
  return (
      lhs.year() < rhs.year() ||
      (lhs.year() == rhs.year() &&
       (lhs.month() < rhs.month() ||
        (lhs.month() == rhs.month() &&
         (lhs.day() < rhs.day() || (lhs.day() == rhs.day() &&
                                    (lhs.hour() < rhs.hour() ||
                                     (lhs.hour() == rhs.hour() &&
                                      (lhs.minute() < rhs.minute() ||
                                       (lhs.minute() == rhs.minute() &&
                                        (lhs.second() < rhs.second())))))))))));
}
operator<<() [1/7]
std::ostream & absl::time_internal::cctz::detail::operator<< (std::ostream & os, const civil_day & d)
Definition at line 43 of file civil_time_detail.cc.
{
  std::stringstream ss;
  ss << civil_month(d) << '-';
  ss << std::setfill('0') << std::setw(2) << d.day();
  return os << ss.str();
}
References absl::d.
operator<<() [2/7]
std::ostream & absl::time_internal::cctz::detail::operator<< (std::ostream & os, const civil_hour & h)
Definition at line 49 of file civil_time_detail.cc.
{
  std::stringstream ss;
  ss << civil_day(h) << 'T';
  ss << std::setfill('0') << std::setw(2) << h.hour();
  return os << ss.str();
}
operator<<() [3/7]
std::ostream & absl::time_internal::cctz::detail::operator<< (std::ostream & os, const civil_minute & m)
Definition at line 55 of file civil_time_detail.cc.
{
  std::stringstream ss;
  ss << civil_hour(m) << ':';
  ss << std::setfill('0') << std::setw(2) << m.minute();
  return os << ss.str();
}
References absl::time_internal::cctz::detail::civil_time< T >::minute().
operator<<() [4/7]
std::ostream & absl::time_internal::cctz::detail::operator<< (std::ostream & os, const civil_month & m)
Definition at line 37 of file civil_time_detail.cc.
{
  std::stringstream ss;
  ss << civil_year(m) << '-';
  ss << std::setfill('0') << std::setw(2) << m.month();
  return os << ss.str();
}
References absl::time_internal::cctz::detail::civil_time< T >::month().
operator<<() [5/7]
std::ostream & absl::time_internal::cctz::detail::operator<< (std::ostream & os, const civil_second & s)
Definition at line 61 of file civil_time_detail.cc.
{
  std::stringstream ss;
  ss << civil_minute(s) << ':';
  ss << std::setfill('0') << std::setw(2) << s.second();
  return os << ss.str();
}
References absl::s.
operator<<() [6/7]
std::ostream & absl::time_internal::cctz::detail::operator<< (std::ostream & os, const civil_year & y)
Definition at line 32 of file civil_time_detail.cc.
{
  std::stringstream ss;
  ss << y.year();  // No padding.
  return os << ss.str();
}
References y.
operator<<() [7/7]
std::ostream & absl::time_internal::cctz::detail::operator<< (std::ostream & os, weekday wd)
Definition at line 70 of file civil_time_detail.cc.
{
  switch (wd) {
    case weekday::monday:
      return os << "Monday";
    case weekday::tuesday:
      return os << "Tuesday";
    case weekday::wednesday:
      return os << "Wednesday";
    case weekday::thursday:
      return os << "Thursday";
    case weekday::friday:
      return os << "Friday";
    case weekday::saturday:
      return os << "Saturday";
    case weekday::sunday:
      return os << "Sunday";
  }
  return os;  // Should never get here, but -Wreturn-type may warn without this.
}
References friday, monday, saturday, sunday, thursday, tuesday, and wednesday.
operator<=()
template<typename T1 , typename T2 > CONSTEXPR_F bool absl::time_internal::cctz::detail::operator<= (const civil_time< T1 > & lhs, const civil_time< T2 > & rhs) noexcept
Definition at line 506 of file civil_time_detail.h.
{
  return !(rhs < lhs);
}
operator==()
template<typename T1 , typename T2 > CONSTEXPR_F bool absl::time_internal::cctz::detail::operator== (const civil_time< T1 > & lhs, const civil_time< T2 > & rhs) noexcept
Definition at line 521 of file civil_time_detail.h.
{
  return lhs.year() == rhs.year() && lhs.month() == rhs.month() &&
         lhs.day() == rhs.day() && lhs.hour() == rhs.hour() &&
         lhs.minute() == rhs.minute() && lhs.second() == rhs.second();
}
References absl::time_internal::cctz::detail::civil_time< T >::year().
operator>()
template<typename T1 , typename T2 > CONSTEXPR_F bool absl::time_internal::cctz::detail::operator> (const civil_time< T1 > & lhs, const civil_time< T2 > & rhs) noexcept
Definition at line 516 of file civil_time_detail.h.
{
  return rhs < lhs;
}
operator>=()
template<typename T1 , typename T2 > CONSTEXPR_F bool absl::time_internal::cctz::detail::operator>= (const civil_time< T1 > & lhs, const civil_time< T2 > & rhs) noexcept
Definition at line 511 of file civil_time_detail.h.
{
  return !(lhs < rhs);
}
parse()
bool absl::time_internal::cctz::detail::parse (const std::string & format, const std::string & input, const time_zone & tz, time_point< seconds > * sec, detail::femtoseconds * fs, std::string * err = nullptr)
Definition at line 692 of file time_zone_format.cc.
{
  // The unparsed input.
  const char* data = input.c_str();  // NUL terminated
  // Skips leading whitespace.
  while (std::isspace(*data)) ++data;
  const year_t kyearmax = std::numeric_limits<year_t>::max();
  const year_t kyearmin = std::numeric_limits<year_t>::min();
  // Sets default values for unspecified fields.
  bool saw_year = false;
  year_t year = 1970;
  std::tm tm{};
  tm.tm_year = 1970 - 1900;
  tm.tm_mon = 1 - 1;  // Jan
  tm.tm_mday = 1;
  tm.tm_hour = 0;
  tm.tm_min = 0;
  tm.tm_sec = 0;
  tm.tm_wday = 4;  // Thu
  tm.tm_yday = 0;
  tm.tm_isdst = 0;
  auto subseconds = detail::femtoseconds::zero();
  bool saw_offset = false;
  int offset = 0;  // No offset from passed tz.
  std::string zone = "UTC";
  const char* fmt = format.c_str();  // NUL terminated
  bool twelve_hour = false;
  bool afternoon = false;
  int week_num = -1;
  weekday week_start = weekday::sunday;
  bool saw_percent_s = false;
  std::int_fast64_t percent_s = 0;
  // Steps through format, one specifier at a time.
  while (data != nullptr && *fmt != '\0') {
    if (std::isspace(*fmt)) {
      while (std::isspace(*data)) ++data;
      while (std::isspace(*++fmt)) continue;
      continue;
    }
    if (*fmt != '%') {
      if (*data == *fmt) {
        ++data;
        ++fmt;
      } else {
        data = nullptr;
      }
      continue;
    }
    const char* percent = fmt;
    if (*++fmt == '\0') {
      data = nullptr;
      continue;
    }
    switch (*fmt++) {
      case 'Y':
        // Symmetrically with FormatTime(), directly handing %Y avoids the
        // tm.tm_year overflow problem.  However, tm.tm_year will still be
        // used by other specifiers like %D.
        data = ParseInt(data, 0, kyearmin, kyearmax, &year);
        if (data != nullptr) saw_year = true;
        continue;
      case 'm':
        data = ParseInt(data, 2, 1, 12, &tm.tm_mon);
        if (data != nullptr) tm.tm_mon -= 1;
        week_num = -1;
        continue;
      case 'd':
      case 'e':
        data = ParseInt(data, 2, 1, 31, &tm.tm_mday);
        week_num = -1;
        continue;
      case 'U':
        data = ParseInt(data, 0, 0, 53, &week_num);
        week_start = weekday::sunday;
        continue;
      case 'W':
        data = ParseInt(data, 0, 0, 53, &week_num);
        week_start = weekday::monday;
        continue;
      case 'u':
        data = ParseInt(data, 0, 1, 7, &tm.tm_wday);
        if (data != nullptr) tm.tm_wday %= 7;
        continue;
      case 'w':
        data = ParseInt(data, 0, 0, 6, &tm.tm_wday);
        continue;
      case 'H':
        data = ParseInt(data, 2, 0, 23, &tm.tm_hour);
        twelve_hour = false;
        continue;
      case 'M':
        data = ParseInt(data, 2, 0, 59, &tm.tm_min);
        continue;
      case 'S':
        data = ParseInt(data, 2, 0, 60, &tm.tm_sec);
        continue;
      case 'I':
      case 'l':
      case 'r':  // probably uses %I
        twelve_hour = true;
        break;
      case 'R':  // uses %H
      case 'T':  // uses %H
      case 'c':  // probably uses %H
      case 'X':  // probably uses %H
        twelve_hour = false;
        break;
      case 'z':
        data = ParseOffset(data, "", &offset);
        if (data != nullptr) saw_offset = true;
        continue;
      case 'Z':  // ignored; zone abbreviations are ambiguous
        data = ParseZone(data, &zone);
        continue;
      case 's':
        data =
            ParseInt(data, 0, std::numeric_limits<std::int_fast64_t>::min(),
                     std::numeric_limits<std::int_fast64_t>::max(), &percent_s);
        if (data != nullptr) saw_percent_s = true;
        continue;
      case ':':
        if (fmt[0] == 'z' ||
            (fmt[0] == ':' &&
             (fmt[1] == 'z' || (fmt[1] == ':' && fmt[2] == 'z')))) {
          data = ParseOffset(data, ":", &offset);
          if (data != nullptr) saw_offset = true;
          fmt += (fmt[0] == 'z') ? 1 : (fmt[1] == 'z') ? 2 : 3;
          continue;
        }
        break;
      case '%':
        data = (*data == '%' ? data + 1 : nullptr);
        continue;
      case 'E':
        if (fmt[0] == 'T') {
          if (*data == 'T' || *data == 't') {
            ++data;
            ++fmt;
          } else {
            data = nullptr;
          }
          continue;
        }
        if (fmt[0] == 'z' || (fmt[0] == '*' && fmt[1] == 'z')) {
          data = ParseOffset(data, ":", &offset);
          if (data != nullptr) saw_offset = true;
          fmt += (fmt[0] == 'z') ? 1 : 2;
          continue;
        }
        if (fmt[0] == '*' && fmt[1] == 'S') {
          data = ParseInt(data, 2, 0, 60, &tm.tm_sec);
          if (data != nullptr && *data == '.') {
            data = ParseSubSeconds(data + 1, &subseconds);
          }
          fmt += 2;
          continue;
        }
        if (fmt[0] == '*' && fmt[1] == 'f') {
          if (data != nullptr && std::isdigit(*data)) {
            data = ParseSubSeconds(data, &subseconds);
          }
          fmt += 2;
          continue;
        }
        if (fmt[0] == '4' && fmt[1] == 'Y') {
          const char* bp = data;
          data = ParseInt(data, 4, year_t{-999}, year_t{9999}, &year);
          if (data != nullptr) {
            if (data - bp == 4) {
              saw_year = true;
            } else {
              data = nullptr;  // stopped too soon
            }
          }
          fmt += 2;
          continue;
        }
        if (std::isdigit(*fmt)) {
          int n = 0;  // value ignored
          if (const char* np = ParseInt(fmt, 0, 0, 1024, &n)) {
            if (*np == 'S') {
              data = ParseInt(data, 2, 0, 60, &tm.tm_sec);
              if (data != nullptr && *data == '.') {
                data = ParseSubSeconds(data + 1, &subseconds);
              }
              fmt = ++np;
              continue;
            }
            if (*np == 'f') {
              if (data != nullptr && std::isdigit(*data)) {
                data = ParseSubSeconds(data, &subseconds);
              }
              fmt = ++np;
              continue;
            }
          }
        }
        if (*fmt == 'c') twelve_hour = false;  // probably uses %H
        if (*fmt == 'X') twelve_hour = false;  // probably uses %H
        if (*fmt != '\0') ++fmt;
        break;
      case 'O':
        if (*fmt == 'H') twelve_hour = false;
        if (*fmt == 'I') twelve_hour = true;
        if (*fmt != '\0') ++fmt;
        break;
    }
    // Parses the current specifier.
    const char* orig_data = data;
    std::string spec(percent, static_cast<std::size_t>(fmt - percent));
    data = ParseTM(data, spec.c_str(), &tm);
    // If we successfully parsed %p we need to remember whether the result
    // was AM or PM so that we can adjust tm_hour before time_zone::lookup().
    // So reparse the input with a known AM hour, and check if it is shifted
    // to a PM hour.
    if (spec == "%p" && data != nullptr) {
      std::string test_input = "1";
      test_input.append(orig_data, static_cast<std::size_t>(data - orig_data));
      const char* test_data = test_input.c_str();
      std::tm tmp{};
      ParseTM(test_data, "%I%p", &tmp);
      afternoon = (tmp.tm_hour == 13);
    }
  }
  // Adjust a 12-hour tm_hour value if it should be in the afternoon.
  if (twelve_hour && afternoon && tm.tm_hour < 12) {
    tm.tm_hour += 12;
  }
  if (data == nullptr) {
    if (err != nullptr) *err = "Failed to parse input";
    return false;
  }
  // Skip any remaining whitespace.
  while (std::isspace(*data)) ++data;
  // parse() must consume the entire input string.
  if (*data != '\0') {
    if (err != nullptr) *err = "Illegal trailing data in input string";
    return false;
  }
  // If we saw %s then we ignore anything else and return that time.
  if (saw_percent_s) {
    *sec = FromUnixSeconds(percent_s);
    *fs = detail::femtoseconds::zero();
    return true;
  }
  // If we saw %z, %Ez, or %E*z then we want to interpret the parsed fields
  // in UTC and then shift by that offset.  Otherwise we want to interpret
  // the fields directly in the passed time_zone.
  time_zone ptz = saw_offset ? utc_time_zone() : tz;
  // Allows a leap second of 60 to normalize forward to the following ":00".
  if (tm.tm_sec == 60) {
    tm.tm_sec -= 1;
    offset -= 1;
    subseconds = detail::femtoseconds::zero();
  }
  if (!saw_year) {
    year = year_t{tm.tm_year};
    if (year > kyearmax - 1900) {
      // Platform-dependent, maybe unreachable.
      if (err != nullptr) *err = "Out-of-range year";
      return false;
    }
    year += 1900;
  }
  // Compute year, tm.tm_mon and tm.tm_mday if we parsed a week number.
  if (week_num != -1) {
    if (!FromWeek(week_num, week_start, &year, &tm)) {
      if (err != nullptr) *err = "Out-of-range field";
      return false;
    }
  }
  const int month = tm.tm_mon + 1;
  civil_second cs(year, month, tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec);
  // parse() should not allow normalization. Due to the restricted field
  // ranges above (see ParseInt()), the only possibility is for days to roll
  // into months. That is, parsing "Sep 31" should not produce "Oct 1".
  if (cs.month() != month || cs.day() != tm.tm_mday) {
    if (err != nullptr) *err = "Out-of-range field";
    return false;
  }
  // Accounts for the offset adjustment before converting to absolute time.
  if ((offset < 0 && cs > civil_second::max() + offset) ||
      (offset > 0 && cs < civil_second::min() + offset)) {
    if (err != nullptr) *err = "Out-of-range field";
    return false;
  }
  cs -= offset;
  const auto tp = ptz.lookup(cs).pre;
  // Checks for overflow/underflow and returns an error as necessary.
  if (tp == time_point<seconds>::max()) {
    const auto al = ptz.lookup(time_point<seconds>::max());
    if (cs > al.cs) {
      if (err != nullptr) *err = "Out-of-range field";
      return false;
    }
  }
  if (tp == time_point<seconds>::min()) {
    const auto al = ptz.lookup(time_point<seconds>::min());
    if (cs < al.cs) {
      if (err != nullptr) *err = "Out-of-range field";
      return false;
    }
  }
  *sec = tp;
  *fs = subseconds;
  return true;
}
References data, absl::time_internal::cctz::detail::civil_time< T >::day(), format(), absl::time_internal::cctz::FromUnixSeconds(), absl::time_internal::cctz::time_zone::lookup(), absl::time_internal::cctz::detail::civil_time< T >::max(), absl::time_internal::cctz::detail::civil_time< T >::min(), monday, absl::time_internal::cctz::detail::civil_time< T >::month(), absl::n, sec, sunday, and absl::time_internal::cctz::utc_time_zone().
Referenced by absl::time_internal::cctz::parse(), and absl::time_internal::cctz::TEST().
prev_weekday()
CONSTEXPR_F civil_day absl::time_internal::cctz::detail::prev_weekday (civil_day cd, weekday wd) noexcept
Definition at line 584 of file civil_time_detail.h.
{
  CONSTEXPR_D weekday k_weekdays_back[14] = {
      weekday::sunday,   weekday::saturday,  weekday::friday,
      weekday::thursday, weekday::wednesday, weekday::tuesday,
      weekday::monday,   weekday::sunday,    weekday::saturday,
      weekday::friday,   weekday::thursday,  weekday::wednesday,
      weekday::tuesday,  weekday::monday,
  };
  weekday base = get_weekday(cd);
  for (int i = 0;; ++i) {
    if (base == k_weekdays_back[i]) {
      for (int j = i + 1;; ++j) {
        if (wd == k_weekdays_back[j]) {
          return cd - (j - i);
        }
      }
    }
  }
}
References CONSTEXPR_D, friday, get_weekday(), absl::i, monday, saturday, sunday, thursday, tuesday, and wednesday.
split_seconds() [1/2]
template<typename D > std::pair< time_point< seconds >, D > absl::time_internal::cctz::detail::split_seconds (const time_point< D > & tp)
Definition at line 388 of file time_zone.h.
{
  auto sec = std::chrono::time_point_cast<seconds>(tp);
  auto sub = tp - sec;
  if (sub.count() < 0) {
    sec -= seconds(1);
    sub += seconds(1);
  }
  return {sec, std::chrono::duration_cast<D>(sub)};
}
References sec.
Referenced by absl::time_internal::cctz::format(), absl::time_internal::cctz::time_zone::lookup(), absl::time_internal::cctz::time_zone::next_transition(), and absl::time_internal::cctz::time_zone::prev_transition().
split_seconds() [2/2]
std::pair< time_point< seconds >, seconds > absl::time_internal::cctz::detail::split_seconds (const time_point< seconds > & tp) inline
Definition at line 398 of file time_zone.h.
{
  return {tp, seconds::zero()};
}
step() [1/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::step (day_tag , fields f, diff_t n) noexcept
Definition at line 249 of file civil_time_detail.h.
{
  return impl::n_day(f.y, f.m, f.d, n, f.hh, f.mm, f.ss);
}
References absl::f, absl::n, and absl::time_internal::cctz::detail::impl::n_day().
step() [2/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::step (hour_tag , fields f, diff_t n) noexcept
Definition at line 246 of file civil_time_detail.h.
{
  return impl::n_hour(f.y, f.m, f.d + n / 24, 0, f.hh + n % 24, f.mm, f.ss);
}
References absl::f, absl::n, and absl::time_internal::cctz::detail::impl::n_hour().
step() [3/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::step (minute_tag , fields f, diff_t n) noexcept
Definition at line 243 of file civil_time_detail.h.
{
  return impl::n_min(f.y, f.m, f.d, f.hh + n / 60, 0, f.mm + n % 60, f.ss);
}
References absl::f, absl::n, and absl::time_internal::cctz::detail::impl::n_min().
step() [4/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::step (month_tag , fields f, diff_t n) noexcept
Definition at line 252 of file civil_time_detail.h.
{
  return impl::n_mon(f.y + n / 12, f.m + n % 12, f.d, 0, f.hh, f.mm, f.ss);
}
References absl::f, absl::n, and absl::time_internal::cctz::detail::impl::n_mon().
step() [5/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::step (second_tag , fields f, diff_t n) noexcept
Definition at line 240 of file civil_time_detail.h.
{
  return impl::n_sec(f.y, f.m, f.d, f.hh, f.mm + n / 60, f.ss + n % 60);
}
References absl::f, absl::n, and absl::time_internal::cctz::detail::impl::n_sec().
step() [6/6]
CONSTEXPR_F fields absl::time_internal::cctz::detail::step (year_tag , fields f, diff_t n) noexcept
Definition at line 255 of file civil_time_detail.h.
{
  return fields(f.y + n, f.m, f.d, f.hh, f.mm, f.ss);
}
References absl::f, and absl::n.