open spiel: open_spiel.python.jax.opponent_shaping_jax_test Namespace Reference
open_spiel.python.jax.opponent_shaping_jax_test Namespace Reference
Classes
class DicePolicyGradientTest
class LolaPolicyGradientTest
Functions
rl_environment.Environment make_iterated_matrix_game (str game, iterations=5, batch_size=8)
Tuple[hk.Transformed, hk.Transformed] make_agent_networks (int num_actions)
run_agents (typing.List[OpponentShapingAgent] agents, rl_environment.Environment env, num_steps=1000)
Variables
int SEED = 24984617
Detailed Description
Tests for open_spiel.python.jax.opponent_shaping.
Function Documentation
make_agent_networks()
Tuple[hk.Transformed, hk.Transformed] open_spiel.python.jax.opponent_shaping_jax_test.make_agent_networks (int num_actions)
Definition at line 42 of file opponent_shaping_jax_test.py.
) -> Tuple[hk.Transformed, hk.Transformed]:
  def policy(obs):
    logits = hk.nets.MLP(output_sizes=[8, 8, num_actions], with_bias=True)(obs)
    logits = jnp.nan_to_num(logits)
    return distrax.Categorical(logits=logits)
  def value_fn(obs):
    values = hk.nets.MLP(output_sizes=[8, 8, 1], with_bias=True)(obs)
    return values
  return hk.without_apply_rng(hk.transform(policy)), hk.without_apply_rng(
      hk.transform(value_fn)
  )
Referenced by open_spiel.python.jax.opponent_shaping_jax_test.DicePolicyGradientTest.test_run_game(), and open_spiel.python.jax.opponent_shaping_jax_test.LolaPolicyGradientTest.test_run_game().
make_iterated_matrix_game()
rl_environment.Environment open_spiel.python.jax.opponent_shaping_jax_test.make_iterated_matrix_game (str game, iterations = 5, batch_size = 8)
Definition at line 32 of file opponent_shaping_jax_test.py.
) -> rl_environment.Environment:
  matrix_game = pyspiel.load_matrix_game(game)
  config = {'num_repetitions': iterations, 'batch_size': batch_size}
  game = pyspiel.create_repeated_game(matrix_game, config)
  env = rl_environment.Environment(game)
  return env
Referenced by open_spiel.python.jax.opponent_shaping_jax_test.DicePolicyGradientTest.test_run_game(), and open_spiel.python.jax.opponent_shaping_jax_test.LolaPolicyGradientTest.test_run_game().
run_agents()
open_spiel.python.jax.opponent_shaping_jax_test.run_agents (typing.List[OpponentShapingAgent] agents, rl_environment.Environment env, num_steps = 1000)
Definition at line 59 of file opponent_shaping_jax_test.py.
):
  time_step = env.reset()
  for _ in range(num_steps):
    actions = []
    for agent in agents:
      action, _ = agent.step(time_step)
      if action is not None:
        action = action.squeeze()
      actions.append(action)
    if time_step.last():
      time_step = env.reset()
    else:
      time_step = env.step(actions)
      time_step.observations['actions'] = np.array(actions)
Referenced by open_spiel.python.jax.opponent_shaping_jax_test.DicePolicyGradientTest.test_run_game(), and open_spiel.python.jax.opponent_shaping_jax_test.LolaPolicyGradientTest.test_run_game().
Variable Documentation
SEED
int open_spiel.python.jax.opponent_shaping_jax_test.SEED = 24984617
Definition at line 29 of file opponent_shaping_jax_test.py.