open spiel: open_spiel::tic_tac_toe Namespace Reference
open_spiel::tic_tac_toe Namespace Reference
Classes
class TicTacToeGame
class TicTacToeState
Enumerations
enum class CellState { kEmpty , kNought , kCross }
Functions
CellState PlayerToState (Player player)
std::string StateToString (CellState state)
bool BoardHasLine (const std::array< CellState, kNumCells > &board, const Player player)
std::ostream & operator<< (std::ostream &stream, const CellState &state)
Variables
constexpr int kNumPlayers = 2
constexpr int kNumRows = 3
constexpr int kNumCols = 3
constexpr int kNumCells = kNumRows * kNumCols
constexpr int kCellStates = 1 + kNumPlayers
constexpr int kNumberStates = 5478
Enumeration Type Documentation
CellState
enum class open_spiel::tic_tac_toe::CellState strong
Enumerator
kEmpty
kNought
kCross
Definition at line 45 of file tic_tac_toe.h.
                     {
  kEmpty,
  kNought,  // O
  kCross,   // X
};
Function Documentation
BoardHasLine()
bool open_spiel::tic_tac_toe::BoardHasLine (const std::array< CellState, kNumCells > & board, const Player player)
Definition at line 82 of file tic_tac_toe.cc.
{
  CellState c = PlayerToState(player);
  return (board[0] == c && board[1] == c && board[2] == c) ||
         (board[3] == c && board[4] == c && board[5] == c) ||
         (board[6] == c && board[7] == c && board[8] == c) ||
         (board[0] == c && board[3] == c && board[6] == c) ||
         (board[1] == c && board[4] == c && board[7] == c) ||
         (board[2] == c && board[5] == c && board[8] == c) ||
         (board[0] == c && board[4] == c && board[8] == c) ||
         (board[2] == c && board[4] == c && board[6] == c);
}
References player, and PlayerToState().
Referenced by open_spiel::ultimate_tic_tac_toe::UltimateTTTState::DoApplyAction().
operator<<()
std::ostream & open_spiel::tic_tac_toe::operator<< (std::ostream & stream, const CellState & state) inline
Definition at line 120 of file tic_tac_toe.h.
{
  return stream << StateToString(state);
}
References state, and StateToString().
PlayerToState()
CellState open_spiel::tic_tac_toe::PlayerToState (Player player)
Definition at line 57 of file tic_tac_toe.cc.
{
  switch (player) {
    case 0:
      return CellState::kCross;
    case 1:
      return CellState::kNought;
    default:
      SpielFatalError(absl::StrCat("Invalid player id ", player));
      return CellState::kEmpty;
  }
}
References kCross, kEmpty, kNought, player, open_spiel::SpielFatalError(), and absl::StrCat().
Referenced by open_spiel::tic_tac_toe::TicTacToeGame::ActionToString(), BoardHasLine(), open_spiel::tic_tac_toe::TicTacToeState::DoApplyAction(), and open_spiel::ultimate_tic_tac_toe::UltimateTTTState::DoApplyAction().
StateToString()
std::string open_spiel::tic_tac_toe::StateToString (CellState state)
Definition at line 69 of file tic_tac_toe.cc.
{
  switch (state) {
    case CellState::kEmpty:
      return ".";
    case CellState::kNought:
      return "o";
    case CellState::kCross:
      return "x";
    default:
      SpielFatalError("Unknown state.");
  }
}
References kCross, kEmpty, kNought, open_spiel::SpielFatalError(), and state.
Referenced by open_spiel::tic_tac_toe::TicTacToeGame::ActionToString(), operator<<(), open_spiel::tic_tac_toe::TicTacToeState::ToString(), and open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ToString().
Variable Documentation
kCellStates
int open_spiel::tic_tac_toe::kCellStates = 1 + kNumPlayers inline constexpr
Definition at line 39 of file tic_tac_toe.h.
Referenced by open_spiel::tic_tac_toe::TicTacToeState::ObservationTensor(), open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ObservationTensor(), open_spiel::tic_tac_toe::TicTacToeGame::ObservationTensorShape(), and open_spiel::ultimate_tic_tac_toe::UltimateTTTGame::ObservationTensorShape().
kNumberStates
int open_spiel::tic_tac_toe::kNumberStates = 5478 inline constexpr
Definition at line 42 of file tic_tac_toe.h.
Referenced by main().
kNumCells
int open_spiel::tic_tac_toe::kNumCells = kNumRows * kNumCols inline constexpr
Definition at line 38 of file tic_tac_toe.h.
Referenced by open_spiel::ultimate_tic_tac_toe::UltimateTTTState::DoApplyAction(), open_spiel::tic_tac_toe::TicTacToeState::LegalActions(), open_spiel::tic_tac_toe::TicTacToeGame::MaxGameLength(), open_spiel::ultimate_tic_tac_toe::UltimateTTTGame::MaxGameLength(), open_spiel::tic_tac_toe::TicTacToeGame::NumDistinctActions(), open_spiel::ultimate_tic_tac_toe::UltimateTTTGame::NumDistinctActions(), open_spiel::tic_tac_toe::TicTacToeState::ObservationTensor(), open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ObservationTensor(), open_spiel::ultimate_tic_tac_toe::UltimateTTTGame::ObservationTensorShape(), open_spiel::ultimate_tic_tac_toe::UltimateTTTState::UltimateTTTState(), and open_spiel::ultimate_tic_tac_toe::UltimateTTTState::UltimateTTTState().
kNumCols
int open_spiel::tic_tac_toe::kNumCols = 3 inline constexpr
Definition at line 37 of file tic_tac_toe.h.
Referenced by open_spiel::ultimate_tic_tac_toe::UltimateTTTGame::ObservationTensorShape(), open_spiel::tic_tac_toe::TicTacToeState::ToString(), and open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ToString().
kNumPlayers
int open_spiel::tic_tac_toe::kNumPlayers = 2 inline constexpr
Definition at line 35 of file tic_tac_toe.h.
Referenced by open_spiel::ultimate_tic_tac_toe::UltimateTTTState::DoApplyAction(), open_spiel::tic_tac_toe::TicTacToeGame::NumPlayers(), and open_spiel::ultimate_tic_tac_toe::UltimateTTTGame::NumPlayers().
kNumRows
int open_spiel::tic_tac_toe::kNumRows = 3 inline constexpr
Definition at line 36 of file tic_tac_toe.h.
Referenced by open_spiel::tic_tac_toe::TicTacToeGame::ObservationTensorShape(), open_spiel::ultimate_tic_tac_toe::UltimateTTTGame::ObservationTensorShape(), open_spiel::tic_tac_toe::TicTacToeState::ToString(), and open_spiel::ultimate_tic_tac_toe::UltimateTTTState::ToString().