open spiel: absl::internal_any_invocable Namespace Reference
absl::internal_any_invocable Namespace Reference
Classes
struct ConversionConstruct
class CoreImpl
struct ForwardedParameter
class Impl
struct IsAnyInvocable
struct IsAnyInvocable< AnyInvocable< Sig > >
struct IsInPlaceType
struct IsInPlaceType< absl::in_place_type_t< T > >
class TrivialDeleter
struct TypedConversionConstruct
union TypeErasedState
struct UnwrapStdReferenceWrapperImpl
struct UnwrapStdReferenceWrapperImpl< std::reference_wrapper< T > >
Typedefs
template<class T >
using IsStoredLocally
template<class T >
using RemoveCVRef
template<class T >
using ForwardedParameterType = typename ForwardedParameter<T>::type
using ManagerType
template<bool SigIsNoexcept, class ReturnType , class... P>
using InvokerType
template<class T >
using UnwrapStdReferenceWrapper
template<class... T>
using TrueAlias
template<class Sig , class F , class = absl::enable_if_t< !std::is_same<RemoveCVRef<F>, AnyInvocable<Sig>>::value>>
using CanConvert
template<class Sig , class F , class... Args>
using CanEmplace
template<class Sig , class F , class = absl::enable_if_t< !std::is_same<RemoveCVRef<F>, AnyInvocable<Sig>>::value>>
using CanAssign
template<class Sig , class F >
using CanAssignReferenceWrapper
Enumerations
enum StorageProperty : std::size_t { kAlignment = alignof(std::max_align_t) , kStorageSize = sizeof(void*) * 2 }
enum class FunctionToCall : bool { relocate_from_to , dispose }
Functions
template<class ReturnType , class F , class... P, typename = absl::enable_if_t<std::is_void<ReturnType>::value>>
void InvokeR (F &&f, P &&... args)
template<class ReturnType , class F , class... P, absl::enable_if_t<!std::is_void< ReturnType >::value, int > = 0>
ReturnType InvokeR (F &&f, P &&... args)
template<typename T >
T ForwardImpl (std::true_type)
template<typename T >
T && ForwardImpl (std::false_type)
template<class T >
T & ObjectInLocalStorage (TypeErasedState *const state)
void EmptyManager (FunctionToCall, TypeErasedState *, TypeErasedState *) noexcept
void LocalManagerTrivial (FunctionToCall, TypeErasedState *const from, TypeErasedState *const to) noexcept
template<class T >
void LocalManagerNontrivial (FunctionToCall operation, TypeErasedState *const from, TypeErasedState *const to) noexcept
template<bool SigIsNoexcept, class ReturnType , class QualTRef , class... P>
ReturnType LocalInvoker (TypeErasedState *const state, ForwardedParameterType< P >... args) noexcept(SigIsNoexcept)
void RemoteManagerTrivial (FunctionToCall operation, TypeErasedState *const from, TypeErasedState *const to) noexcept
template<class T >
void RemoteManagerNontrivial (FunctionToCall operation, TypeErasedState *const from, TypeErasedState *const to) noexcept
template<bool SigIsNoexcept, class ReturnType , class QualTRef , class... P>
ReturnType RemoteInvoker (TypeErasedState *const state, ForwardedParameterType< P >... args) noexcept(SigIsNoexcept)
constexpr bool IsCompatibleConversion (void *, void *)
template<bool NoExceptSrc, bool NoExceptDest, class... T>
constexpr bool IsCompatibleConversion (CoreImpl< NoExceptSrc, T... > *, CoreImpl< NoExceptDest, T... > *)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL (,, &)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL (const,, const &)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL (, &, &)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL (const, &, const &)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL (, &&, &&)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL (const, &&, const &&)
Typedef Documentation
CanAssign
template<class Sig , class F , class = absl::enable_if_t< !std::is_same<RemoveCVRef<F>, AnyInvocable<Sig>>::value>> using absl::internal_any_invocable::CanAssign
Initial value:
 TrueAlias<
    absl::enable_if_t<Impl<Sig>::template CallIsValid<F>::value>,
    absl::enable_if_t<
        Impl<Sig>::template CallIsNoexceptIfSigIsNoexcept<F>::value>,
    absl::enable_if_t<std::is_constructible<absl::decay_t<F>, F>::value>>
Definition at line 713 of file any_invocable.h.
CanAssignReferenceWrapper
template<class Sig , class F > using absl::internal_any_invocable::CanAssignReferenceWrapper
Initial value:
 TrueAlias<
    absl::enable_if_t<
        Impl<Sig>::template CallIsValid<std::reference_wrapper<F>>::value>,
    absl::enable_if_t<Impl<Sig>::template CallIsNoexceptIfSigIsNoexcept<
        std::reference_wrapper<F>>::value>>
Definition at line 721 of file any_invocable.h.
CanConvert
template<class Sig , class F , class = absl::enable_if_t< !std::is_same<RemoveCVRef<F>, AnyInvocable<Sig>>::value>> using absl::internal_any_invocable::CanConvert
Initial value:
 TrueAlias<
    absl::enable_if_t<!IsInPlaceType<RemoveCVRef<F>>::value>,
    absl::enable_if_t<Impl<Sig>::template CallIsValid<F>::value>,
    absl::enable_if_t<
        Impl<Sig>::template CallIsNoexceptIfSigIsNoexcept<F>::value>,
    absl::enable_if_t<std::is_constructible<absl::decay_t<F>, F>::value>>
Definition at line 694 of file any_invocable.h.
CanEmplace
template<class Sig , class F , class... Args> using absl::internal_any_invocable::CanEmplace
Initial value:
 TrueAlias<
    absl::enable_if_t<Impl<Sig>::template CallIsValid<F>::value>,
    absl::enable_if_t<
        Impl<Sig>::template CallIsNoexceptIfSigIsNoexcept<F>::value>,
    absl::enable_if_t<std::is_constructible<absl::decay_t<F>, Args...>::value>>
Definition at line 703 of file any_invocable.h.
ForwardedParameterType
template<class T > using absl::internal_any_invocable::ForwardedParameterType = typename ForwardedParameter<T>::type
Definition at line 169 of file any_invocable.h.
InvokerType
template<bool SigIsNoexcept, class ReturnType , class... P> using absl::internal_any_invocable::InvokerType
Initial value:
 ReturnType(TypeErasedState*, ForwardedParameterType<P>...)
    ABSL_INTERNAL_NOEXCEPT_SPEC(SigIsNoexcept)
Definition at line 231 of file any_invocable.h.
IsStoredLocally
template<class T > using absl::internal_any_invocable::IsStoredLocally
Initial value:
 std::integral_constant<
    bool, sizeof(T) <= kStorageSize && alignof(T) <= kAlignment &&
              kAlignment % alignof(T) == 0 &&
              std::is_nothrow_move_constructible<T>::value>
Definition at line 112 of file any_invocable.h.
ManagerType
using absl::internal_any_invocable::ManagerType
Initial value:
 void(FunctionToCall ,
                         TypeErasedState* , TypeErasedState* )
    ABSL_INTERNAL_NOEXCEPT_SPEC(true)
Definition at line 224 of file any_invocable.h.
RemoveCVRef
template<class T > using absl::internal_any_invocable::RemoveCVRef
Initial value:
    typename std::remove_cv<typename std::remove_reference<T>::type>::type
Definition at line 119 of file any_invocable.h.
TrueAlias
template<class... T> using absl::internal_any_invocable::TrueAlias
Initial value:
    std::integral_constant<bool, sizeof(absl::void_t<T...>*) != 0>
Definition at line 687 of file any_invocable.h.
UnwrapStdReferenceWrapper
template<class T > using absl::internal_any_invocable::UnwrapStdReferenceWrapper
Initial value:
    typename UnwrapStdReferenceWrapperImpl<T>::type
Definition at line 679 of file any_invocable.h.
Enumeration Type Documentation
FunctionToCall
enum class absl::internal_any_invocable::FunctionToCall : bool strong
Enumerator
relocate_from_to
dispose
Definition at line 179 of file any_invocable.h.
: bool { relocate_from_to, dispose };
StorageProperty
enum absl::internal_any_invocable::StorageProperty : std::size_t
Enumerator
kAlignment
kStorageSize
Definition at line 92 of file any_invocable.h.
                     : std::size_t {
  kAlignment = alignof(std::max_align_t),  // The alignment of the storage
  kStorageSize = sizeof(void*) * 2         // The size of the storage
};
Function Documentation
ABSL_INTERNAL_ANY_INVOCABLE_IMPL() [1/6]
absl::internal_any_invocable::ABSL_INTERNAL_ANY_INVOCABLE_IMPL (&& , &&)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL() [2/6]
absl::internal_any_invocable::ABSL_INTERNAL_ANY_INVOCABLE_IMPL (& , &)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL() [3/6]
absl::internal_any_invocable::ABSL_INTERNAL_ANY_INVOCABLE_IMPL (&)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL() [4/6]
absl::internal_any_invocable::ABSL_INTERNAL_ANY_INVOCABLE_IMPL (const , && , const &&)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL() [5/6]
absl::internal_any_invocable::ABSL_INTERNAL_ANY_INVOCABLE_IMPL (const , & , const &)
ABSL_INTERNAL_ANY_INVOCABLE_IMPL() [6/6]
absl::internal_any_invocable::ABSL_INTERNAL_ANY_INVOCABLE_IMPL (const , const &)
EmptyManager()
void absl::internal_any_invocable::EmptyManager (FunctionToCall , TypeErasedState * , TypeErasedState *) inline noexcept
Definition at line 235 of file any_invocable.h.
                                                      {}
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Clear(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::CoreImpl(), absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::Initialize(), and absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::operator=().
ForwardImpl() [1/2]
template<typename T > T && absl::internal_any_invocable::ForwardImpl (std::false_type)
ForwardImpl() [2/2]
template<typename T > T absl::internal_any_invocable::ForwardImpl (std::true_type)
InvokeR() [1/2]
template<class ReturnType , class F , class... P, typename = absl::enable_if_t<std::is_void<ReturnType>::value>> void absl::internal_any_invocable::InvokeR (F && f, P &&... args)
Definition at line 130 of file any_invocable.h.
{
  absl::base_internal::invoke(std::forward<F>(f), std::forward<P>(args)...);
}
References absl::f, and absl::base_internal::invoke().
Referenced by LocalInvoker(), and RemoteInvoker().
InvokeR() [2/2]
template<class ReturnType , class F , class... P, absl::enable_if_t<!std::is_void< ReturnType >::value, int > = 0> ReturnType absl::internal_any_invocable::InvokeR (F && f, P &&... args)
Definition at line 136 of file any_invocable.h.
{
  return absl::base_internal::invoke(std::forward<F>(f),
                                     std::forward<P>(args)...);
}
References absl::f, and absl::base_internal::invoke().
IsCompatibleConversion() [1/2]
template<bool NoExceptSrc, bool NoExceptDest, class... T> bool absl::internal_any_invocable::IsCompatibleConversion (CoreImpl< NoExceptSrc, T... > * , CoreImpl< NoExceptDest, T... > *) constexpr
Definition at line 420 of file any_invocable.h.
{
  return !NoExceptDest || NoExceptSrc;
}
IsCompatibleConversion() [2/2]
bool absl::internal_any_invocable::IsCompatibleConversion (void * , void *) constexpr
Definition at line 418 of file any_invocable.h.
{ return false; }
LocalInvoker()
template<bool SigIsNoexcept, class ReturnType , class QualTRef , class... P> ReturnType absl::internal_any_invocable::LocalInvoker (TypeErasedState *const state, ForwardedParameterType< P >... args) noexcept
Definition at line 292 of file any_invocable.h.
{
  using RawT = RemoveCVRef<QualTRef>;
  static_assert(
      IsStoredLocally<RawT>::value,
      "Target object must be in local storage in order to be invoked from it.");
  auto& f = (ObjectInLocalStorage<RawT>)(state);
  return (InvokeR<ReturnType>)(static_cast<QualTRef>(f),
                               static_cast<ForwardedParameterType<P>>(args)...);
}
References absl::f, InvokeR(), ObjectInLocalStorage(), and state.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage().
LocalManagerNontrivial()
template<class T > void absl::internal_any_invocable::LocalManagerNontrivial (FunctionToCall operation, TypeErasedState *const from, TypeErasedState *const to) noexcept
Definition at line 266 of file any_invocable.h.
{
  static_assert(IsStoredLocally<T>::value,
                "Local storage must only be used for supported types.");
  static_assert(!std::is_trivially_copyable<T>::value,
                "Locally stored types must be trivially copyable.");
  T& from_object = (ObjectInLocalStorage<T>)(from);
  switch (operation) {
    case FunctionToCall::relocate_from_to:
      // NOTE: Requires that the left-hand operand is already empty.
      ::new (static_cast<void*>(&to->storage)) T(std::move(from_object));
      ABSL_FALLTHROUGH_INTENDED;
    case FunctionToCall::dispose:
      from_object.~T();  // Must not throw. // NOLINT
      return;
  }
  ABSL_UNREACHABLE();
}
References ABSL_FALLTHROUGH_INTENDED, ABSL_UNREACHABLE, dispose, from, ObjectInLocalStorage(), relocate_from_to, and to.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeLocalManager().
LocalManagerTrivial()
void absl::internal_any_invocable::LocalManagerTrivial (FunctionToCall , TypeErasedState *const from, TypeErasedState *const to) inline noexcept
Definition at line 241 of file any_invocable.h.
{
  // This single statement without branching handles both possible operations.
  //
  // For FunctionToCall::dispose, "from" and "to" point to the same state, and
  // so this assignment logically would do nothing.
  //
  // Note: Correctness here relies on http://wg21.link/p0593, which has only
  // become standard in C++20, though implementations do not break it in
  // practice for earlier versions of C++.
  //
  // The correct way to do this without that paper is to first placement-new a
  // default-constructed T in "to->storage" prior to the memmove, but doing so
  // requires a different function to be created for each T that is stored
  // locally, which can cause unnecessary bloat and be less cache friendly.
  *to = *from;
  // Note: Because the type is trivially copyable, the destructor does not need
  // to be called ("trivially copyable" requires a trivial destructor).
}
References from, and to.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeLocalManager().
ObjectInLocalStorage()
template<class T > T & absl::internal_any_invocable::ObjectInLocalStorage (TypeErasedState *const state)
Definition at line 197 of file any_invocable.h.
{
  // We launder here because the storage may be reused with the same type.
#if ABSL_INTERNAL_CPLUSPLUS_LANG >= 201703L
  return *std::launder(reinterpret_cast<T*>(&state->storage));
#elif ABSL_HAVE_BUILTIN(__builtin_launder)
  return *__builtin_launder(reinterpret_cast<T*>(&state->storage));
#else
  // When `std::launder` or equivalent are not available, we rely on undefined
  // behavior, which works as intended on Abseil's officially supported
  // platforms as of Q2 2022.
#if !defined(__clang__) && defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#pragma GCC diagnostic push
#endif
  return *reinterpret_cast<T*>(&state->storage);
#if !defined(__clang__) && defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
#endif
}
References state.
Referenced by LocalInvoker(), and LocalManagerNontrivial().
RemoteInvoker()
template<bool SigIsNoexcept, class ReturnType , class QualTRef , class... P> ReturnType absl::internal_any_invocable::RemoteInvoker (TypeErasedState *const state, ForwardedParameterType< P >... args) noexcept
Definition at line 350 of file any_invocable.h.
{
  using RawT = RemoveCVRef<QualTRef>;
  static_assert(!IsStoredLocally<RawT>::value,
                "Target object must be in remote storage in order to be "
                "invoked from it.");
  auto& f = *static_cast<RawT*>(state->remote.target);
  return (InvokeR<ReturnType>)(static_cast<QualTRef>(f),
                               static_cast<ForwardedParameterType<P>>(args)...);
}
References absl::f, InvokeR(), and state.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeStorage().
RemoteManagerNontrivial()
template<class T > void absl::internal_any_invocable::RemoteManagerNontrivial (FunctionToCall operation, TypeErasedState *const from, TypeErasedState *const to) noexcept
Definition at line 329 of file any_invocable.h.
{
  static_assert(!IsStoredLocally<T>::value,
                "Remote storage must only be used for types that do not "
                "qualify for local storage.");
  switch (operation) {
    case FunctionToCall::relocate_from_to:
      // NOTE: Requires that the left-hand operand is already empty.
      to->remote.target = from->remote.target;
      return;
    case FunctionToCall::dispose:
      ::delete static_cast<T*>(from->remote.target);  // Must not throw.
      return;
  }
  ABSL_UNREACHABLE();
}
References ABSL_UNREACHABLE, dispose, from, relocate_from_to, and to.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeRemoteManager().
RemoteManagerTrivial()
void absl::internal_any_invocable::RemoteManagerTrivial (FunctionToCall operation, TypeErasedState *const from, TypeErasedState *const to) inline noexcept
Definition at line 307 of file any_invocable.h.
{
  switch (operation) {
    case FunctionToCall::relocate_from_to:
      // NOTE: Requires that the left-hand operand is already empty.
      to->remote = from->remote;
      return;
    case FunctionToCall::dispose:
#if defined(__cpp_sized_deallocation)
      ::operator delete(from->remote.target, from->remote.size);
#else   // __cpp_sized_deallocation
      ::operator delete(from->remote.target);
#endif  // __cpp_sized_deallocation
      return;
  }
  ABSL_UNREACHABLE();
}
References ABSL_UNREACHABLE, dispose, from, relocate_from_to, and to.
Referenced by absl::internal_any_invocable::CoreImpl< SigIsNoexcept, ReturnType, P >::InitializeRemoteManager().