open spiel: open_spiel.python.pytorch.rcfr_pytorch_test Namespace Reference
open_spiel.python.pytorch.rcfr_pytorch_test Namespace Reference
Classes
class RcfrTest
Functions
_new_model ()
Variables
_GAME = pyspiel.load_game('kuhn_poker')
list _BOOLEANS = [False, True]
int _BATCH_SIZE = 12
int SEED = 24984617
Function Documentation
_new_model()
open_spiel.python.pytorch.rcfr_pytorch_test._new_model () protected
Definition at line 35 of file rcfr_pytorch_test.py.
def _new_model():
  return rcfr.DeepRcfrModel(
      _GAME,
      num_hidden_layers=1,
      num_hidden_units=13,
      num_hidden_factors=1,
      use_skip_connections=True)
Referenced by open_spiel.python.pytorch.rcfr_pytorch_test.RcfrTest.test_rcfr(), open_spiel.python.pytorch.rcfr_pytorch_test.RcfrTest.test_rcfr_functions(), and open_spiel.python.pytorch.rcfr_pytorch_test.RcfrTest.test_rcfr_with_buffer().
Variable Documentation
_BATCH_SIZE
int open_spiel.python.pytorch.rcfr_pytorch_test._BATCH_SIZE = 12 protected
Definition at line 31 of file rcfr_pytorch_test.py.
_BOOLEANS
list open_spiel.python.pytorch.rcfr_pytorch_test._BOOLEANS = [False, True] protected
Definition at line 29 of file rcfr_pytorch_test.py.
_GAME
open_spiel.python.pytorch.rcfr_pytorch_test._GAME = pyspiel.load_game('kuhn_poker') protected
Definition at line 28 of file rcfr_pytorch_test.py.
SEED
int open_spiel.python.pytorch.rcfr_pytorch_test.SEED = 24984617
Definition at line 32 of file rcfr_pytorch_test.py.