open spiel: pybind11::test Namespace Reference
pybind11::test Namespace Reference
Classes
struct A
struct B
class IntGetter
struct IntValue
struct ObjectForSpan
class PyIntGetter
class StringContainer
class TestClass
class VectorContainer
Typedefs
typedef absl::variant< A, B > AOrB
Functions
absl::Duration MakeDuration (double secs)
bool CheckDuration (const absl::Duration &duration, double secs)
absl::Time MakeTime (double secs)
bool CheckDatetime (const absl::Time &datetime, double secs)
absl::CivilSecond MakeCivilSecond (double secs)
absl::CivilMinute MakeCivilMinute (double secs)
absl::CivilHour MakeCivilHour (double secs)
absl::CivilDay MakeCivilDay (double secs)
absl::CivilMonth MakeCivilMonth (double secs)
absl::CivilYear MakeCivilYear (double secs)
bool CheckCivilSecond (absl::CivilSecond datetime, double secs)
bool CheckCivilMinute (absl::CivilMinute datetime, double secs)
bool CheckCivilHour (absl::CivilHour datetime, double secs)
bool CheckCivilDay (absl::CivilDay datetime, double secs)
bool CheckCivilMonth (absl::CivilMonth datetime, double secs)
bool CheckCivilYear (absl::CivilYear datetime, double secs)
absl::TimeZone RoundtripTimeZone (absl::TimeZone timezone)
bool CheckStringView (absl::string_view view, const std::string &values)
bool CheckAbslCord (absl::Cord cord, const std::string &values)
absl::Cord ReturnAbslCord (const std::string &values)
bool CheckOptional (const absl::optional< int > optional, bool given, int value)
absl::optional< int > MakeOptional ()
absl::optional< int > MakeOptional (int value)
absl::flat_hash_map< int, int > MakeMap (const std::vector< std::pair< int, int > > &keys_and_values)
bool CheckMap (const absl::flat_hash_map< int, int > &map, const std::vector< std::pair< int, int > > &keys_and_values)
absl::flat_hash_set< int > MakeSet (const std::vector< int > &values)
bool CheckSet (const absl::flat_hash_set< int > &set, const std::vector< int > &values)
absl::btree_map< int, int > MakeBtreeMap (const std::vector< std::pair< int, int > > &keys_and_values)
bool CheckBtreeMap (const absl::btree_map< int, int > &map, const std::vector< std::pair< int, int > > &keys_and_values)
bool CheckSpan (absl::Span< const int > span, const std::vector< int > &values)
bool CheckSpanCasterCopy (const handle &span, const std::vector< int > &values)
void FillSpan (int value, absl::Span< int > output_span)
void FillObjectPointersSpan (int value, absl::Span< ObjectForSpan *const > output_span)
void FillObjectSpan (int value, absl::Span< ObjectForSpan > output_span)
int SumObjectPointersSpan (absl::Span< const ObjectForSpan *const > span)
int SumObjectSpan (absl::Span< const ObjectForSpan > span)
int VariantToInt (AOrB value)
std::vector< AOrB > IdentityWithCopy (const std::vector< AOrB > &value)
std::vector< absl::variant< A *, B * > > Identity (const std::vector< absl::variant< A *, B * > > &value)
PYBIND11_MODULE (absl_example, m)
absl::Status ReturnStatus ()
absl::StatusOr< int > ReturnStatusOr ()
PYBIND11_MODULE (missing_import, m)
bool CheckStatus (const absl::Status &status, absl::StatusCode code)
absl::Status ReturnStatus (absl::StatusCode code, const std::string &text="")
pybind11::object ReturnStatusManualCast (absl::StatusCode code, const std::string &text="")
const absl::Status & ReturnStatusRef (absl::StatusCode code, const std::string &text="")
const absl::Status * ReturnStatusPtr (absl::StatusCode code, const std::string &text="")
absl::StatusOr< int > ReturnFailureStatusOr (absl::StatusCode code, const std::string &text="")
pybind11::object ReturnFailureStatusOrManualCast (absl::StatusCode code, const std::string &text="")
absl::StatusOr< int > ReturnValueStatusOr (int value)
absl::StatusOr< const IntValue * > ReturnPtrStatusOr (int value)
absl::StatusOr< std::unique_ptr< IntValue > > ReturnUniquePtrStatusOr (int value)
PYBIND11_MODULE (status_example, m)
Typedef Documentation
AOrB
typedef absl::variant<A, B> pybind11::test::AOrB
Definition at line 254 of file absl_example.cc.
Function Documentation
CheckAbslCord()
bool pybind11::test::CheckAbslCord (absl::Cord cord, const std::string & values)
Definition at line 127 of file absl_example.cc.
{
  return cord == values;
}
References values.
Referenced by PYBIND11_MODULE().
CheckBtreeMap()
bool pybind11::test::CheckBtreeMap (const absl::btree_map< int, int > & map, const std::vector< std::pair< int, int > > & keys_and_values)
Definition at line 187 of file absl_example.cc.
{
  for (const auto& kvp : keys_and_values) {
    auto found = map.find(kvp.first);
    if (found == map.end()) {
      return false;
    }
    if (found->second != kvp.second) {
      return false;
    }
  }
  return true;
}
Referenced by PYBIND11_MODULE().
CheckCivilDay()
bool pybind11::test::CheckCivilDay (absl::CivilDay datetime, double secs)
Definition at line 83 of file absl_example.cc.
{
  return datetime == MakeCivilDay(secs);
}
References MakeCivilDay().
Referenced by PYBIND11_MODULE().
CheckCivilHour()
bool pybind11::test::CheckCivilHour (absl::CivilHour datetime, double secs)
Definition at line 79 of file absl_example.cc.
{
  return datetime == MakeCivilHour(secs);
}
References MakeCivilHour().
Referenced by PYBIND11_MODULE().
CheckCivilMinute()
bool pybind11::test::CheckCivilMinute (absl::CivilMinute datetime, double secs)
Definition at line 75 of file absl_example.cc.
{
  return datetime == MakeCivilMinute(secs);
}
References MakeCivilMinute().
Referenced by PYBIND11_MODULE().
CheckCivilMonth()
bool pybind11::test::CheckCivilMonth (absl::CivilMonth datetime, double secs)
Definition at line 87 of file absl_example.cc.
{
  return datetime == MakeCivilMonth(secs);
}
References MakeCivilMonth().
Referenced by PYBIND11_MODULE().
CheckCivilSecond()
bool pybind11::test::CheckCivilSecond (absl::CivilSecond datetime, double secs)
Definition at line 71 of file absl_example.cc.
{
  return datetime == MakeCivilSecond(secs);
}
References MakeCivilSecond().
Referenced by PYBIND11_MODULE().
CheckCivilYear()
bool pybind11::test::CheckCivilYear (absl::CivilYear datetime, double secs)
Definition at line 91 of file absl_example.cc.
{
  return datetime == MakeCivilYear(secs);
}
References MakeCivilYear().
Referenced by PYBIND11_MODULE().
CheckDatetime()
bool pybind11::test::CheckDatetime (const absl::Time & datetime, double secs)
Definition at line 37 of file absl_example.cc.
{
  return datetime == MakeTime(secs);
}
References MakeTime().
Referenced by PYBIND11_MODULE().
CheckDuration()
bool pybind11::test::CheckDuration (const absl::Duration & duration, double secs)
Definition at line 28 of file absl_example.cc.
{
  return duration == MakeDuration(secs);
}
References MakeDuration().
Referenced by PYBIND11_MODULE().
CheckMap()
bool pybind11::test::CheckMap (const absl::flat_hash_map< int, int > & map, const std::vector< std::pair< int, int > > & keys_and_values)
Definition at line 154 of file absl_example.cc.
{
  for (const auto& kvp : keys_and_values) {
    auto found = map.find(kvp.first);
    if (found == map.end()) {
      return false;
    }
    if (found->second != kvp.second) {
      return false;
    }
  }
  return true;
}
Referenced by PYBIND11_MODULE().
CheckOptional()
bool pybind11::test::CheckOptional (const absl::optional< int > optional, bool given, int value)
Definition at line 136 of file absl_example.cc.
{
  if (!given && !optional.has_value()) return true;
  if (given && optional.has_value() && optional.value() == value) return true;
  return false;
}
References absl::optional< T >::has_value(), and absl::optional< T >::value().
Referenced by PYBIND11_MODULE().
CheckSet()
bool pybind11::test::CheckSet (const absl::flat_hash_set< int > & set, const std::vector< int > & values)
Definition at line 172 of file absl_example.cc.
{
  absl::flat_hash_set<int> check(values.begin(), values.end());
  return set == check;
}
References values.
Referenced by PYBIND11_MODULE().
CheckSpan()
bool pybind11::test::CheckSpan (absl::Span< const int > span, const std::vector< int > & values)
Definition at line 202 of file absl_example.cc.
{
  if (span.size() != values.size()) return false;
  for (size_t i = 0; i < span.size(); ++i) {
    if (span[i] != values[i]) return false;
  }
  return true;
}
References i, absl::Span< T >::size(), and values.
Referenced by CheckSpanCasterCopy(), and PYBIND11_MODULE().
CheckSpanCasterCopy()
bool pybind11::test::CheckSpanCasterCopy (const handle & span, const std::vector< int > & values)
Definition at line 210 of file absl_example.cc.
{
  pybind11::detail::make_caster<absl::Span<const int>> caster;
  caster = pybind11::detail::load_type<absl::Span<const int>>(span);
  return CheckSpan(pybind11::detail::cast_op<absl::Span<const int>>(caster),
                   values);
}
References CheckSpan(), and values.
Referenced by PYBIND11_MODULE().
CheckStatus()
bool pybind11::test::CheckStatus (const absl::Status & status, absl::StatusCode code)
Definition at line 33 of file status_example.cc.
{
  return status.code() == code;
}
Referenced by PYBIND11_MODULE().
CheckStringView()
bool pybind11::test::CheckStringView (absl::string_view view, const std::string & values)
Definition at line 110 of file absl_example.cc.
{
  return view == values;
}
References values.
Referenced by PYBIND11_MODULE().
FillObjectPointersSpan()
void pybind11::test::FillObjectPointersSpan (int value, absl::Span< ObjectForSpan *const > output_span)
Definition at line 226 of file absl_example.cc.
{
  for (ObjectForSpan* item : output_span) item->value = value;
}
Referenced by PYBIND11_MODULE().
FillObjectSpan()
void pybind11::test::FillObjectSpan (int value, absl::Span< ObjectForSpan > output_span)
Definition at line 231 of file absl_example.cc.
{
  for (auto& item : output_span) item.value = value;
}
Referenced by PYBIND11_MODULE().
FillSpan()
void pybind11::test::FillSpan (int value, absl::Span< int > output_span)
Definition at line 217 of file absl_example.cc.
{
  for (auto& i : output_span) i = value;
}
References i.
Referenced by PYBIND11_MODULE().
Identity()
std::vector< absl::variant< A *, B * > > pybind11::test::Identity (const std::vector< absl::variant< A *, B * > > & value)
Definition at line 269 of file absl_example.cc.
{
  return value;
}
References value.
Referenced by PYBIND11_MODULE().
IdentityWithCopy()
std::vector< AOrB > pybind11::test::IdentityWithCopy (const std::vector< AOrB > & value)
Definition at line 266 of file absl_example.cc.
{
  return value;
}
References value.
Referenced by PYBIND11_MODULE().
MakeBtreeMap()
absl::btree_map< int, int > pybind11::test::MakeBtreeMap (const std::vector< std::pair< int, int > > & keys_and_values)
Definition at line 178 of file absl_example.cc.
{
  absl::btree_map<int, int> map;
  for (const auto& kvp : keys_and_values) {
    map.insert(kvp);
  }
  return map;
}
Referenced by PYBIND11_MODULE().
MakeCivilDay()
absl::CivilDay pybind11::test::MakeCivilDay (double secs)
Definition at line 56 of file absl_example.cc.
{
  return absl::ToCivilDay(absl::FromUnixSeconds(static_cast<int64_t>(secs)),
                          absl::UTCTimeZone());
}
References absl::FromUnixSeconds(), absl::ToCivilDay(), and absl::UTCTimeZone().
Referenced by CheckCivilDay(), and PYBIND11_MODULE().
MakeCivilHour()
absl::CivilHour pybind11::test::MakeCivilHour (double secs)
Definition at line 51 of file absl_example.cc.
{
  return absl::ToCivilHour(absl::FromUnixSeconds(static_cast<int64_t>(secs)),
                           absl::UTCTimeZone());
}
References absl::FromUnixSeconds(), absl::ToCivilHour(), and absl::UTCTimeZone().
Referenced by CheckCivilHour(), and PYBIND11_MODULE().
MakeCivilMinute()
absl::CivilMinute pybind11::test::MakeCivilMinute (double secs)
Definition at line 46 of file absl_example.cc.
{
  return absl::ToCivilMinute(absl::FromUnixSeconds(static_cast<int64_t>(secs)),
                             absl::UTCTimeZone());
}
References absl::FromUnixSeconds(), absl::ToCivilMinute(), and absl::UTCTimeZone().
Referenced by CheckCivilMinute(), and PYBIND11_MODULE().
MakeCivilMonth()
absl::CivilMonth pybind11::test::MakeCivilMonth (double secs)
Definition at line 61 of file absl_example.cc.
{
  return absl::ToCivilMonth(absl::FromUnixSeconds(static_cast<int64_t>(secs)),
                            absl::UTCTimeZone());
}
References absl::FromUnixSeconds(), absl::ToCivilMonth(), and absl::UTCTimeZone().
Referenced by CheckCivilMonth(), and PYBIND11_MODULE().
MakeCivilSecond()
absl::CivilSecond pybind11::test::MakeCivilSecond (double secs)
Definition at line 41 of file absl_example.cc.
{
  return absl::ToCivilSecond(absl::FromUnixSeconds(static_cast<int64_t>(secs)),
                             absl::UTCTimeZone());
}
References absl::FromUnixSeconds(), absl::ToCivilSecond(), and absl::UTCTimeZone().
Referenced by CheckCivilSecond(), and PYBIND11_MODULE().
MakeCivilYear()
absl::CivilYear pybind11::test::MakeCivilYear (double secs)
Definition at line 66 of file absl_example.cc.
{
  return absl::ToCivilYear(absl::FromUnixSeconds(static_cast<int64_t>(secs)),
                           absl::UTCTimeZone());
}
References absl::FromUnixSeconds(), absl::ToCivilYear(), and absl::UTCTimeZone().
Referenced by CheckCivilYear(), and PYBIND11_MODULE().
MakeDuration()
absl::Duration pybind11::test::MakeDuration (double secs)
Definition at line 26 of file absl_example.cc.
{ return absl::Seconds(secs); }
References absl::Seconds().
Referenced by CheckDuration(), and PYBIND11_MODULE().
MakeMap()
absl::flat_hash_map< int, int > pybind11::test::MakeMap (const std::vector< std::pair< int, int > > & keys_and_values)
Definition at line 145 of file absl_example.cc.
{
  absl::flat_hash_map<int, int> map;
  for (const auto& kvp : keys_and_values) {
    map.insert(kvp);
  }
  return map;
}
Referenced by PYBIND11_MODULE().
MakeOptional() [1/2]
absl::optional< int > pybind11::test::MakeOptional ()
Definition at line 142 of file absl_example.cc.
{ return absl::nullopt; }
Referenced by PYBIND11_MODULE().
MakeOptional() [2/2]
absl::optional< int > pybind11::test::MakeOptional (int value)
Definition at line 143 of file absl_example.cc.
{ return value; }
References value.
MakeSet()
absl::flat_hash_set< int > pybind11::test::MakeSet (const std::vector< int > & values)
Definition at line 168 of file absl_example.cc.
{
  return absl::flat_hash_set<int>(values.begin(), values.end());
}
References values.
Referenced by PYBIND11_MODULE().
MakeTime()
absl::Time pybind11::test::MakeTime (double secs)
Definition at line 32 of file absl_example.cc.
{
  int64_t microsecs = static_cast<int64_t>(secs * 1e6);
  return absl::FromUnixMicros(microsecs);
}
References absl::FromUnixMicros().
Referenced by CheckDatetime(), and PYBIND11_MODULE().
PYBIND11_MODULE() [1/3]
pybind11::test::PYBIND11_MODULE (absl_example , m)
Definition at line 292 of file absl_example.cc.
{
  // absl::Time/Duration bindings.
  m.def("make_duration", &MakeDuration, arg("secs"));
  m.def("check_duration", &CheckDuration, arg("duration"), arg("secs"));
  m.def("make_datetime", &MakeTime, arg("secs"));
  m.def("check_datetime", &CheckDatetime, arg("datetime"), arg("secs"));
  // absl::TimeZone bindings
  m.def("roundtrip_timezone", &RoundtripTimeZone, arg("timezone"));
  // absl::CivilTime bindings
  m.def("make_civilsecond", &MakeCivilSecond, arg("secs"));
  m.def("check_civilsecond", &CheckCivilSecond, arg("datetime"), arg("secs"));
  m.def("make_civilminute", &MakeCivilMinute, arg("secs"));
  m.def("check_civilminute", &CheckCivilMinute, arg("datetime"), arg("secs"));
  m.def("make_civilhour", &MakeCivilHour, arg("secs"));
  m.def("check_civilhour", &CheckCivilHour, arg("datetime"), arg("secs"));
  m.def("make_civilday", &MakeCivilDay, arg("secs"));
  m.def("check_civilday", &CheckCivilDay, arg("datetime"), arg("secs"));
  m.def("make_civilmonth", &MakeCivilMonth, arg("secs"));
  m.def("check_civilmonth", &CheckCivilMonth, arg("datetime"), arg("secs"));
  m.def("make_civilyear", &MakeCivilYear, arg("secs"));
  m.def("check_civilyear", &CheckCivilYear, arg("datetime"), arg("secs"));
  // absl::Span bindings.
  m.def("check_span", &CheckSpan, arg("span"), arg("values"));
  m.def("check_span_no_convert", &CheckSpan, arg("span").noconvert(),
        arg("values"));
  m.def("check_span_caster_copy", &CheckSpanCasterCopy, arg("span"),
        arg("values"));
  class_<VectorContainer>(m, "VectorContainer")
      .def(init())
      .def("make_span", &VectorContainer::MakeSpan, arg("values"));
  // Non-const spans can never be converted, so `output_span` could be marked as
  // `noconvert`, but that would be redundant (so test that it is not needed).
  m.def("fill_span", &FillSpan, arg("value"), arg("output_span"));
  // Span of objects.
  class_<ObjectForSpan>(m, "ObjectForSpan")
      .def(init<int>())
      .def_readwrite("value", &ObjectForSpan::value);
  bind_vector<std::vector<ObjectForSpan>>(m, "ObjectVector");
  m.def("sum_object_pointers_span", &SumObjectPointersSpan, arg("span"));
  m.def("sum_object_span", &SumObjectSpan, arg("span"));
  m.def("sum_object_span_no_convert", &SumObjectSpan, arg("span").noconvert());
  m.def("fill_object_pointers_span", &FillObjectPointersSpan, arg("value"),
        arg("output_span"));
  m.def("fill_object_span", &FillObjectSpan, arg("value"), arg("output_span"));
  // absl::string_view bindings.
  m.def("check_string_view", &CheckStringView, arg("view"), arg("values"));
  class_<StringContainer>(m, "StringContainer")
      .def(init())
      .def("make_string_view", &StringContainer::MakeStringView, arg("values"));
  // absl::Cord bindings.
  m.def("check_absl_cord", &CheckAbslCord, arg("view"), arg("values"));
  m.def("return_absl_cord", &ReturnAbslCord, arg("values"));
  // absl::optional bindings.
  m.def("check_optional", &CheckOptional, arg("optional") = absl::nullopt,
        arg("given") = false, arg("value") = 0);
  m.def("make_optional", (absl::optional<int>(*)()) & MakeOptional);
  m.def("make_optional", (absl::optional<int>(*)(int)) & MakeOptional,
        arg("value"));
  // absl::flat_hash_map bindings
  m.def("make_map", &MakeMap, arg("keys_and_values"));
  m.def("check_map", &CheckMap, arg("map"), arg("keys_and_values"));
  // absl::flat_hash_set bindings
  m.def("make_set", &MakeSet, arg("values"));
  m.def("check_set", &CheckSet, arg("set"), arg("values"));
  // absl::btree_map bindings
  m.def("make_btree_map", &MakeBtreeMap, arg("keys_and_values"));
  m.def("check_btree_map", &CheckBtreeMap, arg("map"), arg("keys_and_values"));
  // absl::variant
  class_<A>(m, "A").def(init<int>()).def_readonly("a", &A::a);
  class_<B>(m, "B").def(init<int>()).def_readonly("b", &B::b);
  m.def("VariantToInt", &VariantToInt);
  m.def("Identity", &Identity);
  m.def("IdentityWithCopy", &IdentityWithCopy);
}
References pybind11::test::A::a, arg, pybind11::test::B::b, CheckAbslCord(), CheckBtreeMap(), CheckCivilDay(), CheckCivilHour(), CheckCivilMinute(), CheckCivilMonth(), CheckCivilSecond(), CheckCivilYear(), CheckDatetime(), CheckDuration(), CheckMap(), CheckOptional(), CheckSet(), CheckSpan(), CheckSpanCasterCopy(), CheckStringView(), FillObjectPointersSpan(), FillObjectSpan(), FillSpan(), Identity(), IdentityWithCopy(), MakeBtreeMap(), MakeCivilDay(), MakeCivilHour(), MakeCivilMinute(), MakeCivilMonth(), MakeCivilSecond(), MakeCivilYear(), MakeDuration(), MakeMap(), MakeOptional(), MakeSet(), pybind11::test::VectorContainer::MakeSpan(), pybind11::test::StringContainer::MakeStringView(), MakeTime(), ReturnAbslCord(), RoundtripTimeZone(), SumObjectPointersSpan(), SumObjectSpan(), pybind11::test::ObjectForSpan::value, and VariantToInt().
PYBIND11_MODULE() [2/3]
pybind11::test::PYBIND11_MODULE (missing_import , m)
Definition at line 15 of file missing_import.cc.
{
  m.def("returns_status", &ReturnStatus);
  m.def("returns_status_or", &ReturnStatusOr);
}
References ReturnStatus(), and ReturnStatusOr().
PYBIND11_MODULE() [3/3]
pybind11::test::PYBIND11_MODULE (status_example , m)
Definition at line 96 of file status_example.cc.
{
  auto status_module = pybind11::google::ImportStatusModule();
  m.attr("StatusNotOk") = status_module.attr("StatusNotOk");
  class_<IntValue>(m, "IntValue").def_readonly("value", &IntValue::value);
  class_<TestClass>(m, "TestClass")
      .def(init())
      .def("make_status", google::DoNotThrowStatus(&TestClass::MakeStatus),
           arg("code"), arg("text") = "")
      .def("make_status_const",
           google::DoNotThrowStatus(&TestClass::MakeStatusConst), arg("code"),
           arg("text") = "")
      .def("make_failure_status_or",
           google::DoNotThrowStatus(&TestClass::MakeFailureStatusOr),
           arg("code"), arg("text") = "");
  // absl::Status bindings
  m.def("check_status", &CheckStatus, arg("status"), arg("code"));
  m.def("return_status", &ReturnStatus, "Raise an error if code is not OK.",
        arg("code"), arg("text") = "");
  m.def("make_status", google::DoNotThrowStatus(&ReturnStatus),
        "Return a status without raising an error, regardless of what it is.",
        arg("code"), arg("text") = "");
  m.def("make_status_manual_cast", ReturnStatusManualCast,
        "Return a status without raising an error, regardless of what it is.",
        arg("code"), arg("text") = "");
  m.def("make_status_ref", google::DoNotThrowStatus(&ReturnStatusRef),
        "Return a reference to a static status value without raising an error.",
        arg("code"), arg("text") = "", return_value_policy::reference);
  m.def("make_status_ptr", google::DoNotThrowStatus(&ReturnStatusPtr),
        "Return a reference to a static status value without raising an error.",
        arg("code"), arg("text") = "", return_value_policy::reference);
  // absl::StatusOr bindings
  m.def("return_value_status_or", &ReturnValueStatusOr, arg("value"));
  m.def("return_failure_status_or", &ReturnFailureStatusOr,
        "Raise an error with the given code.", arg("code"), arg("text") = "");
  m.def("make_failure_status_or",
        google::DoNotThrowStatus(&ReturnFailureStatusOr), arg("code"),
        arg("text") = "", "Return a status without raising an error.");
  m.def("make_failure_status_or_manual_cast", &ReturnFailureStatusOrManualCast,
        arg("code"), arg("text") = "", "Return a status.");
  m.def("return_ptr_status_or", &ReturnPtrStatusOr, arg("value"),
        "Return a reference in a status or to a static value.",
        return_value_policy::reference);
  m.def("return_unique_ptr_status_or", &ReturnUniquePtrStatusOr, arg("value"));
  m.def("return_status_or_pointer", []() {
    static absl::StatusOr<int>* ptr = new absl::StatusOr<int>(42);
    return ptr;
  });
  m.def("return_failure_status_or_pointer", []() {
    static absl::StatusOr<int>* ptr =
        new absl::StatusOr<int>(absl::InvalidArgumentError("Uh oh!"));
    return ptr;
  });
  class_<IntGetter, PyIntGetter>(m, "IntGetter")
      .def(init())
      .def("Get", &IntGetter::Get);
  // Needed to exercise raw_code() != code().
  m.def("status_from_int_code", [](int code, const std::string& msg) {
    return google::DoNotThrowStatus(
        absl::Status(static_cast<absl::StatusCode>(code), msg));
  });
}
References arg, CheckStatus(), pybind11::google::DoNotThrowStatus(), pybind11::test::IntGetter::Get(), pybind11::google::ImportStatusModule(), absl::InvalidArgumentError(), pybind11::test::TestClass::MakeFailureStatusOr(), pybind11::test::TestClass::MakeStatus(), pybind11::test::TestClass::MakeStatusConst(), ptr, ReturnFailureStatusOr(), ReturnFailureStatusOrManualCast(), ReturnPtrStatusOr(), ReturnStatus(), ReturnStatusManualCast(), ReturnStatusPtr(), ReturnStatusRef(), ReturnUniquePtrStatusOr(), ReturnValueStatusOr(), absl::StatusOr, and pybind11::test::IntValue::value.
ReturnAbslCord()
absl::Cord pybind11::test::ReturnAbslCord (const std::string & values)
Definition at line 131 of file absl_example.cc.
{
  absl::Cord cord(values);
  return cord;
}
References values.
Referenced by PYBIND11_MODULE().
ReturnFailureStatusOr()
absl::StatusOr< int > pybind11::test::ReturnFailureStatusOr (absl::StatusCode code, const std::string & text = "")
Definition at line 60 of file status_example.cc.
{
  return absl::Status(code, text);
}
References absl::Status.
Referenced by PYBIND11_MODULE().
ReturnFailureStatusOrManualCast()
pybind11::object pybind11::test::ReturnFailureStatusOrManualCast (absl::StatusCode code, const std::string & text = "")
Definition at line 65 of file status_example.cc.
{
  return pybind11::cast(google::DoNotThrowStatus(absl::Status(code, text)));
}
References pybind11::google::DoNotThrowStatus().
Referenced by PYBIND11_MODULE().
ReturnPtrStatusOr()
absl::StatusOr< const IntValue * > pybind11::test::ReturnPtrStatusOr (int value)
Definition at line 72 of file status_example.cc.
{
  static IntValue static_object;
  static_object.value = value;
  return &static_object;
}
References pybind11::test::IntValue::value, and value.
Referenced by PYBIND11_MODULE().
ReturnStatus() [1/2]
absl::Status pybind11::test::ReturnStatus ()
Definition at line 12 of file missing_import.cc.
{ return absl::InternalError("test"); }
References absl::InternalError().
Referenced by PYBIND11_MODULE(), and PYBIND11_MODULE().
ReturnStatus() [2/2]
absl::Status pybind11::test::ReturnStatus (absl::StatusCode code, const std::string & text = "")
Definition at line 37 of file status_example.cc.
{
  return absl::Status(code, text);
}
References absl::Status.
ReturnStatusManualCast()
pybind11::object pybind11::test::ReturnStatusManualCast (absl::StatusCode code, const std::string & text = "")
Definition at line 41 of file status_example.cc.
{
  return pybind11::cast(google::DoNotThrowStatus(absl::Status(code, text)));
}
References pybind11::google::DoNotThrowStatus().
Referenced by PYBIND11_MODULE().
ReturnStatusOr()
absl::StatusOr< int > pybind11::test::ReturnStatusOr ()
Definition at line 13 of file missing_import.cc.
{ return absl::InternalError("test"); }
References absl::InternalError().
Referenced by PYBIND11_MODULE().
ReturnStatusPtr()
const absl::Status * pybind11::test::ReturnStatusPtr (absl::StatusCode code, const std::string & text = "")
Definition at line 53 of file status_example.cc.
{
  static absl::Status static_status;
  static_status = absl::Status(code, text);
  return &static_status;
}
References absl::Status.
Referenced by PYBIND11_MODULE().
ReturnStatusRef()
const absl::Status & pybind11::test::ReturnStatusRef (absl::StatusCode code, const std::string & text = "")
Definition at line 46 of file status_example.cc.
{
  static absl::Status static_status;
  static_status = absl::Status(code, text);
  return static_status;
}
References absl::Status.
Referenced by PYBIND11_MODULE().
ReturnUniquePtrStatusOr()
absl::StatusOr< std::unique_ptr< IntValue > > pybind11::test::ReturnUniquePtrStatusOr (int value)
Definition at line 78 of file status_example.cc.
{
  return absl::make_unique<IntValue>(value);
}
Referenced by PYBIND11_MODULE().
ReturnValueStatusOr()
absl::StatusOr< int > pybind11::test::ReturnValueStatusOr (int value)
Definition at line 70 of file status_example.cc.
{ return value; }
References value.
Referenced by PYBIND11_MODULE().
RoundtripTimeZone()
absl::TimeZone pybind11::test::RoundtripTimeZone (absl::TimeZone timezone)
Definition at line 95 of file absl_example.cc.
{ return timezone; }
Referenced by PYBIND11_MODULE().
SumObjectPointersSpan()
int pybind11::test::SumObjectPointersSpan (absl::Span< const ObjectForSpan *const > span)
Definition at line 235 of file absl_example.cc.
{
  int result = 0;
  for (const ObjectForSpan* item : span) result += item->value;
  return result;
}
Referenced by PYBIND11_MODULE().
SumObjectSpan()
int pybind11::test::SumObjectSpan (absl::Span< const ObjectForSpan > span)
Definition at line 241 of file absl_example.cc.
{
  int result = 0;
  for (auto& item : span) result += item.value;
  return result;
}
Referenced by PYBIND11_MODULE().
VariantToInt()
int pybind11::test::VariantToInt (AOrB value)
Definition at line 256 of file absl_example.cc.
{
  if (absl::holds_alternative<A>(value)) {
    return absl::get<A>(value).a;
  } else if (absl::holds_alternative<B>(value)) {
    return absl::get<B>(value).b;
  } else {
    throw std::exception();
  }
}
References absl::get(), and absl::holds_alternative().
Referenced by PYBIND11_MODULE().