open spiel: open_spiel.python.jax.cfr.compare_cfr_with_jax Namespace Reference
open_spiel.python.jax.cfr.compare_cfr_with_jax Namespace Reference
Functions
compare_cfr_with_jax_cfr (game)
compare_leduc ()
compare_battleship ()
compare_goofspiel_descending ()
compare_goofspiel_randomized ()
Detailed Description
This compares the speed/results of Jax CFR to of the original impl of CFR.
The results slightly differ due to different rounding of regrets between
original implmentation and CFR. When setting clamping of regrets to 1e-8 the
results are exactly the same.
Function Documentation
compare_battleship()
open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_battleship ()
Definition at line 74 of file compare_cfr_with_jax.py.
def compare_battleship():
  game_params = {
      "board_height": 2,
      "board_width": 2,
      "num_shots": 4,
      "ship_sizes": "[2]",
      "ship_values": "[1]",
      "allow_repeated_shots": False,
  }
  game = pyspiel.load_game("battleship", game_params)
  compare_cfr_with_jax_cfr(game)
# Speed Results:
#   Original: 14.667663097381592
#   Jax CPU: 1.068636417388916
References open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_cfr_with_jax_cfr().
Referenced by open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_randomized().
compare_cfr_with_jax_cfr()
open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_cfr_with_jax_cfr (game)
Do the comparison.
Definition at line 32 of file compare_cfr_with_jax.py.
def compare_cfr_with_jax_cfr(game):
  """Do the comparison."""
  start = time.time()
  jax_cfr = JaxCFR(game)
  print(time.time() - start)
  jax_cfr.multiple_steps(10000)
  print(time.time() - start)
  start = time.time()
  print(time.time() - start)
  cfr = CFRPlusSolver(game)
  for _ in range(1000):
    cfr.evaluate_and_update_policy()
  print(time.time() - start)
  jax_strat = jax_cfr.average_policy()
  jax_br1 = BestResponsePolicy(jax_cfr.game, 1, jax_strat)
  jax_br2 = BestResponsePolicy(jax_cfr.game, 0, jax_strat)
  cfr_strat = jax_cfr.average_policy()
  cfr_br1 = BestResponsePolicy(jax_cfr.game, 1, cfr_strat)
  cfr_br2 = BestResponsePolicy(jax_cfr.game, 0, cfr_strat)
  print("Jax P1: ", jax_br1.value(jax_cfr.game.new_initial_state()))
  print("CFR P1: ", cfr_br1.value(jax_cfr.game.new_initial_state()))
  print("Jax P2: ", jax_br2.value(jax_cfr.game.new_initial_state()))
  print("CFR P2: ", cfr_br2.value(jax_cfr.game.new_initial_state()))
# Speed Results:
#   Original: 139.60753107070923
#   Jax CPU: 3.7404067516326904
Referenced by open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_battleship(), open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_descending(), open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_randomized(), and open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_leduc().
compare_goofspiel_descending()
open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_descending ()
Definition at line 90 of file compare_cfr_with_jax.py.
def compare_goofspiel_descending():
  game_params = {"num_cards": 4, "imp_info": True, "points_order": "descending"}
  game = pyspiel.load_game_as_turn_based("goofspiel", game_params)
  compare_cfr_with_jax_cfr(game)
# Speed Results:
#   Original: 6.639796733856201
#   Jax CPU: 0.8599820137023926
References open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_cfr_with_jax_cfr().
Referenced by open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_randomized().
compare_goofspiel_randomized()
open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_randomized ()
Definition at line 99 of file compare_cfr_with_jax.py.
def compare_goofspiel_randomized():
  game_params = {"num_cards": 3, "imp_info": True, "points_order": "random"}
  game = pyspiel.load_game_as_turn_based("goofspiel", game_params)
  compare_cfr_with_jax_cfr(game)
References open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_battleship(), open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_cfr_with_jax_cfr(), open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_descending(), open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_randomized(), and open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_leduc().
Referenced by open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_randomized().
compare_leduc()
open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_leduc ()
Definition at line 66 of file compare_cfr_with_jax.py.
def compare_leduc():
  game = pyspiel.load_game("leduc_poker")
  compare_cfr_with_jax_cfr(game)
# Speed Results:
#   Original: 335.6707363128662
#   Jax CPU: 7.59996485710144
References open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_cfr_with_jax_cfr().
Referenced by open_spiel.python.jax.cfr.compare_cfr_with_jax.compare_goofspiel_randomized().