open spiel: absl::inlined_vector_internal Namespace Reference
absl::inlined_vector_internal Namespace Reference
Classes
struct Allocation
class AllocationTransaction
class ConstructionTransaction
class CopyValueAdapter
class DefaultValueAdapter
struct DestroyAdapter
struct DestroyAdapter< A, false >
struct DestroyAdapter< A, true >
class IteratorValueAdapter
struct MallocAdapter
class Storage
struct StorageView
struct TypeIdentity
Typedefs
template<typename A >
using AllocatorTraits = std::allocator_traits<A>
template<typename A >
using ValueType = typename AllocatorTraits<A>::value_type
template<typename A >
using SizeType = typename AllocatorTraits<A>::size_type
template<typename A >
using Pointer = typename AllocatorTraits<A>::pointer
template<typename A >
using ConstPointer = typename AllocatorTraits<A>::const_pointer
template<typename A >
using DifferenceType = typename AllocatorTraits<A>::difference_type
template<typename A >
using Reference = ValueType<A>&
template<typename A >
using ConstReference = const ValueType<A>&
template<typename A >
using Iterator = Pointer<A>
template<typename A >
using ConstIterator = ConstPointer<A>
template<typename A >
using ReverseIterator = typename std::reverse_iterator<Iterator<A>>
template<typename A >
using ConstReverseIterator = typename std::reverse_iterator<ConstIterator<A>>
template<typename A >
using MoveIterator = typename std::move_iterator<Iterator<A>>
template<typename Iterator >
using IsAtLeastForwardIterator
template<typename A >
using IsMemcpyOk
template<typename A >
using IsMoveAssignOk = std::is_move_assignable<ValueType<A>>
template<typename A >
using IsSwapOk = absl::type_traits_internal::IsSwappable<ValueType<A>>
template<typename T >
using NoTypeDeduction = typename TypeIdentity<T>::type
Functions
template<typename A , typename ValueAdapter >
void ConstructElements (NoTypeDeduction< A > &allocator, Pointer< A > construct_first, ValueAdapter &values, SizeType< A > construct_size)
template<typename A , typename ValueAdapter >
void AssignElements (Pointer< A > assign_first, ValueAdapter &values, SizeType< A > assign_size)
Typedef Documentation
AllocatorTraits
template<typename A > using absl::inlined_vector_internal::AllocatorTraits = std::allocator_traits<A>
Definition at line 46 of file inlined_vector.h.
ConstIterator
template<typename A > using absl::inlined_vector_internal::ConstIterator = ConstPointer<A>
Definition at line 66 of file inlined_vector.h.
ConstPointer
template<typename A > using absl::inlined_vector_internal::ConstPointer = typename AllocatorTraits<A>::const_pointer
Definition at line 54 of file inlined_vector.h.
ConstReference
template<typename A > using absl::inlined_vector_internal::ConstReference = const ValueType<A>&
Definition at line 62 of file inlined_vector.h.
ConstReverseIterator
template<typename A > using absl::inlined_vector_internal::ConstReverseIterator = typename std::reverse_iterator<ConstIterator<A>>
Definition at line 70 of file inlined_vector.h.
DifferenceType
template<typename A > using absl::inlined_vector_internal::DifferenceType = typename AllocatorTraits<A>::difference_type
Definition at line 58 of file inlined_vector.h.
IsAtLeastForwardIterator
template<typename Iterator > using absl::inlined_vector_internal::IsAtLeastForwardIterator
Initial value:
 std::is_convertible<
    typename std::iterator_traits<Iterator>::iterator_category,
    std::forward_iterator_tag>
Definition at line 75 of file inlined_vector.h.
IsMemcpyOk
template<typename A > using absl::inlined_vector_internal::IsMemcpyOk
Initial value:
    absl::conjunction<std::is_same<A, std::allocator<ValueType<A>>>,
                      absl::is_trivially_copy_constructible<ValueType<A>>,
                      absl::is_trivially_copy_assignable<ValueType<A>>,
                      absl::is_trivially_destructible<ValueType<A>>>
Definition at line 80 of file inlined_vector.h.
IsMoveAssignOk
template<typename A > using absl::inlined_vector_internal::IsMoveAssignOk = std::is_move_assignable<ValueType<A>>
Definition at line 87 of file inlined_vector.h.
IsSwapOk
template<typename A > using absl::inlined_vector_internal::IsSwapOk = absl::type_traits_internal::IsSwappable<ValueType<A>>
Definition at line 89 of file inlined_vector.h.
Iterator
template<typename A > using absl::inlined_vector_internal::Iterator = Pointer<A>
Definition at line 64 of file inlined_vector.h.
MoveIterator
template<typename A > using absl::inlined_vector_internal::MoveIterator = typename std::move_iterator<Iterator<A>>
Definition at line 72 of file inlined_vector.h.
NoTypeDeduction
template<typename T > using absl::inlined_vector_internal::NoTypeDeduction = typename TypeIdentity<T>::type
Definition at line 99 of file inlined_vector.h.
Pointer
template<typename A > using absl::inlined_vector_internal::Pointer = typename AllocatorTraits<A>::pointer
Definition at line 52 of file inlined_vector.h.
Reference
template<typename A > using absl::inlined_vector_internal::Reference = ValueType<A>&
Definition at line 60 of file inlined_vector.h.
ReverseIterator
template<typename A > using absl::inlined_vector_internal::ReverseIterator = typename std::reverse_iterator<Iterator<A>>
Definition at line 68 of file inlined_vector.h.
SizeType
template<typename A > using absl::inlined_vector_internal::SizeType = typename AllocatorTraits<A>::size_type
Definition at line 50 of file inlined_vector.h.
ValueType
template<typename A > using absl::inlined_vector_internal::ValueType = typename AllocatorTraits<A>::value_type
Definition at line 48 of file inlined_vector.h.
Function Documentation
AssignElements()
template<typename A , typename ValueAdapter > void absl::inlined_vector_internal::AssignElements (Pointer< A > assign_first, ValueAdapter & values, SizeType< A > assign_size)
Definition at line 161 of file inlined_vector.h.
{
  for (SizeType<A> i = 0; i < assign_size; ++i) {
    values.AssignNext(assign_first + i);
  }
}
References absl::i, and values.
Referenced by absl::inlined_vector_internal::Storage< T, N, A >::Assign(), absl::inlined_vector_internal::Storage< T, N, A >::Erase(), and absl::inlined_vector_internal::Storage< T, N, A >::Insert().
ConstructElements()
template<typename A , typename ValueAdapter > void absl::inlined_vector_internal::ConstructElements (NoTypeDeduction< A > & allocator, Pointer< A > construct_first, ValueAdapter & values, SizeType< A > construct_size)
Definition at line 148 of file inlined_vector.h.
{
  for (SizeType<A> i = 0; i < construct_size; ++i) {
    ABSL_INTERNAL_TRY { values.ConstructNext(allocator, construct_first + i); }
    ABSL_INTERNAL_CATCH_ANY {
      DestroyAdapter<A>::DestroyElements(allocator, construct_first, i);
      ABSL_INTERNAL_RETHROW;
    }
  }
}
References ABSL_INTERNAL_CATCH_ANY, ABSL_INTERNAL_RETHROW, ABSL_INTERNAL_TRY, absl::i, and values.
Referenced by absl::inlined_vector_internal::Storage< T, N, A >::Assign(), absl::inlined_vector_internal::ConstructionTransaction< A >::Construct(), absl::inlined_vector_internal::Storage< T, N, A >::EmplaceBackSlow(), absl::inlined_vector_internal::Storage< T, N, A >::InitFrom(), absl::inlined_vector_internal::Storage< T, N, A >::Initialize(), absl::InlinedVector< T, N, A >::InlinedVector(), absl::inlined_vector_internal::Storage< T, N, A >::Insert(), absl::inlined_vector_internal::Storage< T, N, A >::Reserve(), absl::inlined_vector_internal::Storage< T, N, A >::Resize(), absl::inlined_vector_internal::Storage< T, N, A >::ShrinkToFit(), and absl::inlined_vector_internal::Storage< T, N, A >::Swap().