open spiel: absl::hash_internal Namespace Reference
absl::hash_internal Namespace Reference
Classes
struct AggregateBarrier
struct ContainerAsVector
struct ContainerAsVector< std::tuple< T... > >
struct ContainerAsVector< std::tuple<> >
struct DefaultEquals
struct EqVisitor
struct ExpandVisitor
struct Hash
struct HashImpl
struct HashSelect
class HashStateBase
struct is_hashable
struct is_uniquely_represented
struct is_uniquely_represented< bool >
struct is_uniquely_represented< CustomHashType< Tags... >, typename EnableIfContained< InvokeTag::kUniquelyRepresented, Tags... >::type >
struct is_uniquely_represented< Integral, typename std::enable_if< std::is_integral< Integral >::value >::type >
struct is_uniquely_represented< unsigned char >
struct MakeTypeSet
struct MakeTypeSet< T, Ts... >
class MixingHashState
struct OdrUse
class PiecewiseCombiner
struct PoisonedHash
struct PrintVisitor
struct RunOnStartup
class SpyHashStateImpl
struct TypeSet
struct VariantVisitor
Typedefs
template<typename... T>
using VariantForTypes
using SpyHashState = SpyHashStateImpl<void>
Functions
template<typename Container , typename Eq >
ABSL_MUST_USE_RESULT testing::AssertionResult VerifyTypeImplementsAbslHashCorrectly (const Container &values, Eq equals)
uint32_t CityHash32 (const char *s, size_t len)
uint64_t CityHash64 (const char *s, size_t len)
uint64_t CityHash64WithSeed (const char *s, size_t len, uint64_t seed)
uint64_t CityHash64WithSeeds (const char *s, size_t len, uint64_t seed0, uint64_t seed1)
constexpr size_t PiecewiseChunkSize ()
template<typename H , typename T >
H hash_bytes (H hash_state, const T &value)
template<typename H , typename B >
std::enable_if< std::is_same< B, bool >::value, H >::type AbslHashValue (H hash_state, B value)
template<typename H , typename Enum >
std::enable_if< std::is_enum< Enum >::value, H >::type AbslHashValue (H hash_state, Enum e)
template<typename H , typename Float >
std::enable_if< std::is_same< Float, float >::value||std::is_same< Float, double >::value, H >::type AbslHashValue (H hash_state, Float value)
template<typename H , typename LongDouble >
std::enable_if< std::is_same< LongDouble, longdouble >::value, H >::type AbslHashValue (H hash_state, LongDouble value)
template<typename H , typename T >
H AbslHashValue (H hash_state, T *ptr)
template<typename H >
H AbslHashValue (H hash_state, std::nullptr_t)
template<typename H , typename T , typename C >
H AbslHashValue (H hash_state, T C::*ptr)
template<typename H , typename T1 , typename T2 >
std::enable_if< is_hashable< T1 >::value &&is_hashable< T2 >::value, H >::type AbslHashValue (H hash_state, const std::pair< T1, T2 > &p)
template<typename H , typename Tuple , size_t... Is>
H hash_tuple (H hash_state, const Tuple &t, absl::index_sequence< Is... >)
template<typename H , typename... Ts>
std::enable_if< absl::conjunction< is_hashable< Ts >... >::value, H >::type AbslHashValue (H hash_state, const std::tuple< Ts... > &t)
template<typename H , typename T , typename D >
H AbslHashValue (H hash_state, const std::unique_ptr< T, D > &ptr)
template<typename H , typename T >
H AbslHashValue (H hash_state, const std::shared_ptr< T > &ptr)
template<typename H >
H AbslHashValue (H hash_state, absl::string_view str)
template<typename Char , typename Alloc , typename H , typename = absl::enable_if_t<std::is_same<Char, wchar_t>::value || std::is_same<Char, char16_t>::value || std::is_same<Char, char32_t>::value>>
H AbslHashValue (H hash_state, const std::basic_string< Char, std::char_traits< Char >, Alloc > &str)
template<typename H , typename T , size_t N>
std::enable_if< is_hashable< T >::value, H >::type AbslHashValue (H hash_state, const std::array< T, N > &array)
template<typename H , typename T , typename Allocator >
std::enable_if< is_hashable< T >::value, H >::type AbslHashValue (H hash_state, const std::deque< T, Allocator > &deque)
template<typename H , typename T , typename Allocator >
std::enable_if< is_hashable< T >::value, H >::type AbslHashValue (H hash_state, const std::forward_list< T, Allocator > &list)
template<typename H , typename T , typename Allocator >
std::enable_if< is_hashable< T >::value, H >::type AbslHashValue (H hash_state, const std::list< T, Allocator > &list)
template<typename H , typename T , typename Allocator >
std::enable_if< is_hashable< T >::value &&!std::is_same< T, bool >::value, H >::type AbslHashValue (H hash_state, const std::vector< T, Allocator > &vector)
template<typename H , typename T , typename Allocator >
std::enable_if< is_hashable< T >::value &&std::is_same< T, bool >::value, H >::type AbslHashValue (H hash_state, const std::vector< T, Allocator > &vector)
template<typename H , typename Key , typename T , typename Compare , typename Allocator >
std::enable_if< is_hashable< Key >::value &&is_hashable< T >::value, H >::type AbslHashValue (H hash_state, const std::map< Key, T, Compare, Allocator > &map)
template<typename H , typename Key , typename T , typename Compare , typename Allocator >
std::enable_if< is_hashable< Key >::value &&is_hashable< T >::value, H >::type AbslHashValue (H hash_state, const std::multimap< Key, T, Compare, Allocator > &map)
template<typename H , typename Key , typename Compare , typename Allocator >
std::enable_if< is_hashable< Key >::value, H >::type AbslHashValue (H hash_state, const std::set< Key, Compare, Allocator > &set)
template<typename H , typename Key , typename Compare , typename Allocator >
std::enable_if< is_hashable< Key >::value, H >::type AbslHashValue (H hash_state, const std::multiset< Key, Compare, Allocator > &set)
template<typename H , typename Key , typename Hash , typename KeyEqual , typename Alloc >
std::enable_if< is_hashable< Key >::value, H >::type AbslHashValue (H hash_state, const std::unordered_set< Key, Hash, KeyEqual, Alloc > &s)
template<typename H , typename Key , typename Hash , typename KeyEqual , typename Alloc >
std::enable_if< is_hashable< Key >::value, H >::type AbslHashValue (H hash_state, const std::unordered_multiset< Key, Hash, KeyEqual, Alloc > &s)
template<typename H , typename Key , typename T , typename Hash , typename KeyEqual , typename Alloc >
std::enable_if< is_hashable< Key >::value &&is_hashable< T >::value, H >::type AbslHashValue (H hash_state, const std::unordered_map< Key, T, Hash, KeyEqual, Alloc > &s)
template<typename H , typename Key , typename T , typename Hash , typename KeyEqual , typename Alloc >
std::enable_if< is_hashable< Key >::value &&is_hashable< T >::value, H >::type AbslHashValue (H hash_state, const std::unordered_multimap< Key, T, Hash, KeyEqual, Alloc > &s)
template<typename H , typename T >
std::enable_if< is_hashable< T >::value, H >::type AbslHashValue (H hash_state, std::reference_wrapper< T > opt)
template<typename H , typename T >
std::enable_if< is_hashable< T >::value, H >::type AbslHashValue (H hash_state, const absl::optional< T > &opt)
template<typename H , typename... T>
std::enable_if< conjunction< is_hashable< T >... >::value, H >::type AbslHashValue (H hash_state, const absl::variant< T... > &v)
template<typename H , typename T >
std::enable_if< is_uniquely_represented< T >::value, H >::type hash_range_or_bytes (H hash_state, const T *data, size_t size)
template<typename H , typename T >
std::enable_if<!is_uniquely_represented< T >::value, H >::type hash_range_or_bytes (H hash_state, const T *data, size_t size)
uint64_t LowLevelHash (const void *data, size_t len, uint64_t seed, const uint64_t salt[5])
template<typename T , typename U , typename = absl::enable_if_t<!std::is_same<T, U>::value>, int = RunOnStartup<SpyHashStateImpl<T>::SetDirectAbslHashValueError>::run>
void AbslHashValue (SpyHashStateImpl< T >, const U &)
Variables
constexpr uint64_t kHashSalt [5]
Typedef Documentation
SpyHashState
using absl::hash_internal::SpyHashState = SpyHashStateImpl<void>
Definition at line 260 of file spy_hash_state.h.
VariantForTypes
template<typename... T> using absl::hash_internal::VariantForTypes
Initial value:
 typename MakeTypeSet<
    const typename std::decay<T>::type*...>::template apply<absl::variant>
Definition at line 299 of file hash_testing.h.
Function Documentation
AbslHashValue() [1/31]
template<typename H > H absl::hash_internal::AbslHashValue (H hash_state, absl::string_view str)
Definition at line 528 of file hash.h.
{
  return H::combine(
      H::combine_contiguous(std::move(hash_state), str.data(), str.size()),
      str.size());
}
AbslHashValue() [2/31]
template<typename H , typename B > std::enable_if< std::is_same< B, bool >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, B value)
Definition at line 345 of file hash.h.
{
  return H::combine(std::move(hash_state),
                    static_cast<unsigned char>(value ? 1 : 0));
}
AbslHashValue() [3/31]
template<typename H , typename T > std::enable_if< is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const absl::optional< T > & opt)
Definition at line 756 of file hash.h.
{
  if (opt) hash_state = H::combine(std::move(hash_state), *opt);
  return H::combine(std::move(hash_state), opt.has_value());
}
References absl::optional< T >::has_value().
AbslHashValue() [4/31]
template<typename H , typename... T> std::enable_if< conjunction< is_hashable< T >... >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const absl::variant< T... > & v)
Definition at line 775 of file hash.h.
{
  if (!v.valueless_by_exception()) {
    hash_state = absl::visit(VariantVisitor<H>{std::move(hash_state)}, v);
  }
  return H::combine(std::move(hash_state), v.index());
}
References absl::v, and absl::visit().
AbslHashValue() [5/31]
template<typename H , typename T , size_t N> std::enable_if< is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::array< T, N > & array)
Definition at line 553 of file hash.h.
{
  return H::combine_contiguous(std::move(hash_state), array.data(),
                               array.size());
}
AbslHashValue() [6/31]
template<typename Char , typename Alloc , typename H , typename = absl::enable_if_t<std::is_same<Char, wchar_t>::value || std::is_same<Char, char16_t>::value || std::is_same<Char, char32_t>::value>> H absl::hash_internal::AbslHashValue (H hash_state, const std::basic_string< Char, std::char_traits< Char >, Alloc > & str)
Definition at line 539 of file hash.h.
{
  return H::combine(
      H::combine_contiguous(std::move(hash_state), str.data(), str.size()),
      str.size());
}
AbslHashValue() [7/31]
template<typename H , typename T , typename Allocator > std::enable_if< is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::deque< T, Allocator > & deque)
Definition at line 561 of file hash.h.
{
  // TODO(gromer): investigate a more efficient implementation taking
  // advantage of the chunk structure.
  for (const auto& t : deque) {
    hash_state = H::combine(std::move(hash_state), t);
  }
  return H::combine(std::move(hash_state), deque.size());
}
AbslHashValue() [8/31]
template<typename H , typename T , typename Allocator > std::enable_if< is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::forward_list< T, Allocator > & list)
Definition at line 573 of file hash.h.
{
  size_t size = 0;
  for (const T& t : list) {
    hash_state = H::combine(std::move(hash_state), t);
    ++size;
  }
  return H::combine(std::move(hash_state), size);
}
References size.
AbslHashValue() [9/31]
template<typename H , typename T , typename Allocator > std::enable_if< is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::list< T, Allocator > & list)
Definition at line 585 of file hash.h.
{
  for (const auto& t : list) {
    hash_state = H::combine(std::move(hash_state), t);
  }
  return H::combine(std::move(hash_state), list.size());
}
AbslHashValue() [10/31]
template<typename H , typename Key , typename T , typename Compare , typename Allocator > std::enable_if< is_hashable< Key >::value &&is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::map< Key, T, Compare, Allocator > & map)
Definition at line 654 of file hash.h.
{
  for (const auto& t : map) {
    hash_state = H::combine(std::move(hash_state), t);
  }
  return H::combine(std::move(hash_state), map.size());
}
AbslHashValue() [11/31]
template<typename H , typename Key , typename T , typename Compare , typename Allocator > std::enable_if< is_hashable< Key >::value &&is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::multimap< Key, T, Compare, Allocator > & map)
Definition at line 666 of file hash.h.
{
  for (const auto& t : map) {
    hash_state = H::combine(std::move(hash_state), t);
  }
  return H::combine(std::move(hash_state), map.size());
}
AbslHashValue() [12/31]
template<typename H , typename Key , typename Compare , typename Allocator > std::enable_if< is_hashable< Key >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::multiset< Key, Compare, Allocator > & set)
Definition at line 686 of file hash.h.
{
  for (const auto& t : set) {
    hash_state = H::combine(std::move(hash_state), t);
  }
  return H::combine(std::move(hash_state), set.size());
}
AbslHashValue() [13/31]
template<typename H , typename T1 , typename T2 > std::enable_if< is_hashable< T1 >::value &&is_hashable< T2 >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::pair< T1, T2 > & p)
Definition at line 466 of file hash.h.
{
  return H::combine(std::move(hash_state), p.first, p.second);
}
References absl::p.
AbslHashValue() [14/31]
template<typename H , typename Key , typename Compare , typename Allocator > std::enable_if< is_hashable< Key >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::set< Key, Compare, Allocator > & set)
Definition at line 676 of file hash.h.
{
  for (const auto& t : set) {
    hash_state = H::combine(std::move(hash_state), t);
  }
  return H::combine(std::move(hash_state), set.size());
}
AbslHashValue() [15/31]
template<typename H , typename T > H absl::hash_internal::AbslHashValue (H hash_state, const std::shared_ptr< T > & ptr)
Definition at line 505 of file hash.h.
{
  return H::combine(std::move(hash_state), ptr.get());
}
References ptr.
AbslHashValue() [16/31]
template<typename H , typename... Ts> std::enable_if< absl::conjunction< is_hashable< Ts >... >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::tuple< Ts... > & t)
Definition at line 488 of file hash.h.
{
  return hash_internal::hash_tuple(std::move(hash_state), t,
                                   absl::make_index_sequence<sizeof...(Ts)>());
}
References hash_tuple().
AbslHashValue() [17/31]
template<typename H , typename T , typename D > H absl::hash_internal::AbslHashValue (H hash_state, const std::unique_ptr< T, D > & ptr)
Definition at line 499 of file hash.h.
{
  return H::combine(std::move(hash_state), ptr.get());
}
References ptr.
AbslHashValue() [18/31]
template<typename H , typename Key , typename T , typename Hash , typename KeyEqual , typename Alloc > std::enable_if< is_hashable< Key >::value &&is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::unordered_map< Key, T, Hash, KeyEqual, Alloc > & s)
Definition at line 724 of file hash.h.
{
  return H::combine(
      H::combine_unordered(std::move(hash_state), s.begin(), s.end()),
      s.size());
}
References absl::s.
AbslHashValue() [19/31]
template<typename H , typename Key , typename T , typename Hash , typename KeyEqual , typename Alloc > std::enable_if< is_hashable< Key >::value &&is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::unordered_multimap< Key, T, Hash, KeyEqual, Alloc > & s)
Definition at line 736 of file hash.h.
{
  return H::combine(
      H::combine_unordered(std::move(hash_state), s.begin(), s.end()),
      s.size());
}
References absl::s.
AbslHashValue() [20/31]
template<typename H , typename Key , typename Hash , typename KeyEqual , typename Alloc > std::enable_if< is_hashable< Key >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::unordered_multiset< Key, Hash, KeyEqual, Alloc > & s)
Definition at line 711 of file hash.h.
{
  return H::combine(
      H::combine_unordered(std::move(hash_state), s.begin(), s.end()),
      s.size());
}
References absl::s.
AbslHashValue() [21/31]
template<typename H , typename Key , typename Hash , typename KeyEqual , typename Alloc > std::enable_if< is_hashable< Key >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::unordered_set< Key, Hash, KeyEqual, Alloc > & s)
Definition at line 701 of file hash.h.
{
  return H::combine(
      H::combine_unordered(std::move(hash_state), s.begin(), s.end()),
      s.size());
}
References absl::s.
AbslHashValue() [22/31]
template<typename H , typename T , typename Allocator > std::enable_if< is_hashable< T >::value &&!std::is_same< T, bool >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::vector< T, Allocator > & vector)
Definition at line 601 of file hash.h.
{
  return H::combine(H::combine_contiguous(std::move(hash_state), vector.data(),
                                          vector.size()),
                    vector.size());
}
AbslHashValue() [23/31]
template<typename H , typename T , typename Allocator > std::enable_if< is_hashable< T >::value &&std::is_same< T, bool >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, const std::vector< T, Allocator > & vector)
Definition at line 638 of file hash.h.
{
  return H::combine(std::move(hash_state),
                    std::hash<std::vector<T, Allocator>>{}(vector),
                    vector.size());
}
AbslHashValue() [24/31]
template<typename H , typename Enum > std::enable_if< std::is_enum< Enum >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, Enum e)
Definition at line 353 of file hash.h.
{
  // In practice, we could almost certainly just invoke hash_bytes directly,
  // but it's possible that a sanitizer might one day want to
  // store data in the unused bits of an enum. To avoid that risk, we
  // convert to the underlying type before hashing. Hopefully this will get
  // optimized away; if not, we can reopen discussion with c-toolchain-team.
  return H::combine(std::move(hash_state),
                    static_cast<typename std::underlying_type<Enum>::type>(e));
}
References absl::e.
AbslHashValue() [25/31]
template<typename H , typename Float > std::enable_if< std::is_same< Float, float >::value||std::is_same< Float, double >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, Float value)
Definition at line 368 of file hash.h.
{
  return hash_internal::hash_bytes(std::move(hash_state),
                                   value == 0 ? 0 : value);
}
References hash_bytes(), and value.
AbslHashValue() [26/31]
template<typename H , typename LongDouble > std::enable_if< std::is_same< LongDouble, longdouble >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, LongDouble value)
Definition at line 379 of file hash.h.
{
  const int category = std::fpclassify(value);
  switch (category) {
    case FP_INFINITE:
      // Add the sign bit to differentiate between +Inf and -Inf
      hash_state = H::combine(std::move(hash_state), std::signbit(value));
      break;
    case FP_NAN:
    case FP_ZERO:
    default:
      // Category is enough for these.
      break;
    case FP_NORMAL:
    case FP_SUBNORMAL:
      // We can't convert `value` directly to double because this would have
      // undefined behavior if the value is out of range.
      // std::frexp gives us a value in the range (-1, -.5] or [.5, 1) that is
      // guaranteed to be in range for `double`. The truncation is
      // implementation defined, but that works as long as it is deterministic.
      int exp;
      auto mantissa = static_cast<double>(std::frexp(value, &exp));
      hash_state = H::combine(std::move(hash_state), mantissa, exp);
  }
  return H::combine(std::move(hash_state), category);
}
References mantissa.
AbslHashValue() [27/31]
template<typename H > H absl::hash_internal::AbslHashValue (H hash_state, std::nullptr_t)
Definition at line 421 of file hash.h.
{
  return H::combine(std::move(hash_state), static_cast<void*>(nullptr));
}
AbslHashValue() [28/31]
template<typename H , typename T > std::enable_if< is_hashable< T >::value, H >::type absl::hash_internal::AbslHashValue (H hash_state, std::reference_wrapper< T > opt)
Definition at line 749 of file hash.h.
{
  return H::combine(std::move(hash_state), opt.get());
}
AbslHashValue() [29/31]
template<typename H , typename T > H absl::hash_internal::AbslHashValue (H hash_state, T * ptr)
Definition at line 410 of file hash.h.
{
  auto v = reinterpret_cast<uintptr_t>(ptr);
  // Due to alignment, pointers tend to have low bits as zero, and the next few
  // bits follow a pattern since they are also multiples of some base value.
  // Mixing the pointer twice helps prevent stuck low bits for certain alignment
  // values.
  return H::combine(std::move(hash_state), v, v);
}
References ptr, and absl::v.
AbslHashValue() [30/31]
template<typename H , typename T , typename C > H absl::hash_internal::AbslHashValue (H hash_state, T C::* ptr)
Definition at line 427 of file hash.h.
{
  auto salient_ptm_size = [](std::size_t n) -> std::size_t {
#if defined(_MSC_VER)
    // Pointers-to-member-function on MSVC consist of one pointer plus 0, 1, 2,
    // or 3 ints. In 64-bit mode, they are 8-byte aligned and thus can contain
    // padding (namely when they have 1 or 3 ints). The value below is a lower
    // bound on the number of salient, non-padding bytes that we use for
    // hashing.
    if (alignof(T C::*) == alignof(int)) {
      // No padding when all subobjects have the same size as the total
      // alignment. This happens in 32-bit mode.
      return n;
    } else {
      // Padding for 1 int (size 16) or 3 ints (size 24).
      // With 2 ints, the size is 16 with no padding, which we pessimize.
      return n == 24 ? 20 : n == 16 ? 12 : n;
    }
#else
    // On other platforms, we assume that pointers-to-members do not have
    // padding.
#ifdef __cpp_lib_has_unique_object_representations
    static_assert(std::has_unique_object_representations<T C::*>::value);
#endif  // __cpp_lib_has_unique_object_representations
    return n;
#endif
  };
  return H::combine_contiguous(std::move(hash_state),
                               reinterpret_cast<unsigned char*>(&ptr),
                               salient_ptm_size(sizeof ptr));
}
References C, absl::n, and ptr.
AbslHashValue() [31/31]
template<typename T , typename U , typename = absl::enable_if_t<!std::is_same<T, U>::value>, int = RunOnStartup<SpyHashStateImpl<T>::SetDirectAbslHashValueError>::run> void absl::hash_internal::AbslHashValue (SpyHashStateImpl< T > , const U &)
CityHash32()
uint32_t absl::hash_internal::CityHash32 (const char * s, size_t len)
Definition at line 124 of file city.cc.
{
  if (len <= 24) {
    return len <= 12
               ? (len <= 4 ? Hash32Len0to4(s, len) : Hash32Len5to12(s, len))
               : Hash32Len13to24(s, len);
  }
  // len > 24
  uint32_t h = static_cast<uint32_t>(len), g = c1 * h, f = g;
  uint32_t a0 = Rotate32(Fetch32(s + len - 4) * c1, 17) * c2;
  uint32_t a1 = Rotate32(Fetch32(s + len - 8) * c1, 17) * c2;
  uint32_t a2 = Rotate32(Fetch32(s + len - 16) * c1, 17) * c2;
  uint32_t a3 = Rotate32(Fetch32(s + len - 12) * c1, 17) * c2;
  uint32_t a4 = Rotate32(Fetch32(s + len - 20) * c1, 17) * c2;
  h ^= a0;
  h = Rotate32(h, 19);
  h = h * 5 + 0xe6546b64;
  h ^= a2;
  h = Rotate32(h, 19);
  h = h * 5 + 0xe6546b64;
  g ^= a1;
  g = Rotate32(g, 19);
  g = g * 5 + 0xe6546b64;
  g ^= a3;
  g = Rotate32(g, 19);
  g = g * 5 + 0xe6546b64;
  f += a4;
  f = Rotate32(f, 19);
  f = f * 5 + 0xe6546b64;
  size_t iters = (len - 1) / 20;
  do {
    uint32_t b0 = Rotate32(Fetch32(s) * c1, 17) * c2;
    uint32_t b1 = Fetch32(s + 4);
    uint32_t b2 = Rotate32(Fetch32(s + 8) * c1, 17) * c2;
    uint32_t b3 = Rotate32(Fetch32(s + 12) * c1, 17) * c2;
    uint32_t b4 = Fetch32(s + 16);
    h ^= b0;
    h = Rotate32(h, 18);
    h = h * 5 + 0xe6546b64;
    f += b1;
    f = Rotate32(f, 19);
    f = f * c1;
    g += b2;
    g = Rotate32(g, 18);
    g = g * 5 + 0xe6546b64;
    h ^= b3 + b1;
    h = Rotate32(h, 19);
    h = h * 5 + 0xe6546b64;
    g ^= b4;
    g = absl::gbswap_32(g) * 5;
    h += b4 * 5;
    h = absl::gbswap_32(h);
    f += b0;
    PERMUTE3(f, h, g);
    s += 20;
  } while (--iters != 0);
  g = Rotate32(g, 11) * c1;
  g = Rotate32(g, 17) * c1;
  f = Rotate32(f, 11) * c1;
  f = Rotate32(f, 17) * c1;
  h = Rotate32(h + g, 19);
  h = h * 5 + 0xe6546b64;
  h = Rotate32(h, 17) * c1;
  h = Rotate32(h + f, 19);
  h = h * 5 + 0xe6546b64;
  h = Rotate32(h, 17) * c1;
  return h;
}
References a1, a2, b1, b2, absl::f, absl::g, absl::gbswap_32(), len, PERMUTE3, and absl::s.
CityHash64()
uint64_t absl::hash_internal::CityHash64 (const char * s, size_t len)
Definition at line 298 of file city.cc.
{
  if (len <= 32) {
    if (len <= 16) {
      return HashLen0to16(s, len);
    } else {
      return HashLen17to32(s, len);
    }
  } else if (len <= 64) {
    return HashLen33to64(s, len);
  }
  // For strings over 64 bytes we hash the end first, and then as we
  // loop we keep 56 bytes of state: v, w, x, y, and z.
  uint64_t x = Fetch64(s + len - 40);
  uint64_t y = Fetch64(s + len - 16) + Fetch64(s + len - 56);
  uint64_t z = HashLen16(Fetch64(s + len - 48) + len, Fetch64(s + len - 24));
  std::pair<uint64_t, uint64_t> v =
      WeakHashLen32WithSeeds(s + len - 64, len, z);
  std::pair<uint64_t, uint64_t> w =
      WeakHashLen32WithSeeds(s + len - 32, y + k1, x);
  x = x * k1 + Fetch64(s);
  // Decrease len to the nearest multiple of 64, and operate on 64-byte chunks.
  len = (len - 1) & ~static_cast<size_t>(63);
  do {
    x = Rotate(x + y + v.first + Fetch64(s + 8), 37) * k1;
    y = Rotate(y + v.second + Fetch64(s + 48), 42) * k1;
    x ^= w.second;
    y += v.first + Fetch64(s + 40);
    z = Rotate(z + w.first, 33) * k1;
    v = WeakHashLen32WithSeeds(s, v.second * k1, x + w.first);
    w = WeakHashLen32WithSeeds(s + 32, z + w.second, y + Fetch64(s + 16));
    std::swap(z, x);
    s += 64;
    len -= 64;
  } while (len != 0);
  return HashLen16(HashLen16(v.first, w.first) + ShiftMix(y) * k1 + z,
                   HashLen16(v.second, w.second) + x);
}
References len, absl::s, absl::v, absl::x, and y.
Referenced by CityHash64WithSeeds().
CityHash64WithSeed()
uint64_t absl::hash_internal::CityHash64WithSeed (const char * s, size_t len, uint64_t seed)
Definition at line 338 of file city.cc.
{
  return CityHash64WithSeeds(s, len, k2, seed);
}
References CityHash64WithSeeds(), len, and absl::s.
CityHash64WithSeeds()
uint64_t absl::hash_internal::CityHash64WithSeeds (const char * s, size_t len, uint64_t seed0, uint64_t seed1)
Definition at line 342 of file city.cc.
{
  return HashLen16(CityHash64(s, len) - seed0, seed1);
}
References CityHash64(), len, and absl::s.
Referenced by CityHash64WithSeed().
hash_bytes()
template<typename H , typename T > H absl::hash_internal::hash_bytes (H hash_state, const T & value)
Definition at line 326 of file hash.h.
{
  const unsigned char* start = reinterpret_cast<const unsigned char*>(&value);
  return H::combine_contiguous(std::move(hash_state), start, sizeof(value));
}
References value.
Referenced by AbslHashValue().
hash_range_or_bytes() [1/2]
template<typename H , typename T > std::enable_if< is_uniquely_represented< T >::value, H >::type absl::hash_internal::hash_range_or_bytes (H hash_state, const T * data, size_t size)
Definition at line 818 of file hash.h.
{
  const auto* bytes = reinterpret_cast<const unsigned char*>(data);
  return H::combine_contiguous(std::move(hash_state), bytes, sizeof(T) * size);
}
References data, and size.
Referenced by absl::hash_internal::HashStateBase< H >::combine_contiguous().
hash_range_or_bytes() [2/2]
template<typename H , typename T > std::enable_if<!is_uniquely_represented< T >::value, H >::type absl::hash_internal::hash_range_or_bytes (H hash_state, const T * data, size_t size)
Definition at line 826 of file hash.h.
{
  for (const auto end = data + size; data < end; ++data) {
    hash_state = H::combine(std::move(hash_state), *data);
  }
  return hash_state;
}
References data, end, and size.
hash_tuple()
template<typename H , typename Tuple , size_t... Is> H absl::hash_internal::hash_tuple (H hash_state, const Tuple & t, absl::index_sequence< Is... >)
Definition at line 475 of file hash.h.
{
  return H::combine(std::move(hash_state), std::get<Is>(t)...);
}
Referenced by AbslHashValue().
LowLevelHash()
uint64_t absl::hash_internal::LowLevelHash (const void * data, size_t len, uint64_t seed, const uint64_t salt[5])
Definition at line 30 of file low_level_hash.cc.
{
  const uint8_t* ptr = static_cast<const uint8_t*>(data);
  uint64_t starting_length = static_cast<uint64_t>(len);
  uint64_t current_state = seed ^ salt[0];
  if (len > 64) {
    // If we have more than 64 bytes, we're going to handle chunks of 64
    // bytes at a time. We're going to build up two separate hash states
    // which we will then hash together.
    uint64_t duplicated_state = current_state;
    do {
      uint64_t a = absl::base_internal::UnalignedLoad64(ptr);
      uint64_t b = absl::base_internal::UnalignedLoad64(ptr + 8);
      uint64_t c = absl::base_internal::UnalignedLoad64(ptr + 16);
      uint64_t d = absl::base_internal::UnalignedLoad64(ptr + 24);
      uint64_t e = absl::base_internal::UnalignedLoad64(ptr + 32);
      uint64_t f = absl::base_internal::UnalignedLoad64(ptr + 40);
      uint64_t g = absl::base_internal::UnalignedLoad64(ptr + 48);
      uint64_t h = absl::base_internal::UnalignedLoad64(ptr + 56);
      uint64_t cs0 = Mix(a ^ salt[1], b ^ current_state);
      uint64_t cs1 = Mix(c ^ salt[2], d ^ current_state);
      current_state = (cs0 ^ cs1);
      uint64_t ds0 = Mix(e ^ salt[3], f ^ duplicated_state);
      uint64_t ds1 = Mix(g ^ salt[4], h ^ duplicated_state);
      duplicated_state = (ds0 ^ ds1);
      ptr += 64;
      len -= 64;
    } while (len > 64);
    current_state = current_state ^ duplicated_state;
  }
  // We now have a data `ptr` with at most 64 bytes and the current state
  // of the hashing state machine stored in current_state.
  while (len > 16) {
    uint64_t a = absl::base_internal::UnalignedLoad64(ptr);
    uint64_t b = absl::base_internal::UnalignedLoad64(ptr + 8);
    current_state = Mix(a ^ salt[1], b ^ current_state);
    ptr += 16;
    len -= 16;
  }
  // We now have a data `ptr` with at most 16 bytes.
  uint64_t a = 0;
  uint64_t b = 0;
  if (len > 8) {
    // When we have at least 9 and at most 16 bytes, set A to the first 64
    // bits of the input and B to the last 64 bits of the input. Yes, they will
    // overlap in the middle if we are working with less than the full 16
    // bytes.
    a = absl::base_internal::UnalignedLoad64(ptr);
    b = absl::base_internal::UnalignedLoad64(ptr + len - 8);
  } else if (len > 3) {
    // If we have at least 4 and at most 8 bytes, set A to the first 32
    // bits and B to the last 32 bits.
    a = absl::base_internal::UnalignedLoad32(ptr);
    b = absl::base_internal::UnalignedLoad32(ptr + len - 4);
  } else if (len > 0) {
    // If we have at least 1 and at most 3 bytes, read all of the provided
    // bits into A, with some adjustments.
    a = static_cast<uint64_t>((ptr[0] << 16) | (ptr[len >> 1] << 8) |
                              ptr[len - 1]);
    b = 0;
  } else {
    a = 0;
    b = 0;
  }
  uint64_t w = Mix(a ^ salt[1], b ^ current_state);
  uint64_t z = salt[1] ^ starting_length;
  return Mix(w, z);
}
References absl::a, b, absl::c, absl::d, data, absl::e, absl::f, absl::g, len, and ptr.
PiecewiseChunkSize()
size_t absl::hash_internal::PiecewiseChunkSize () constexpr
Definition at line 68 of file hash.h.
{ return 1024; }
Referenced by absl::hash_internal::PiecewiseCombiner::add_buffer(), and absl::hash_internal::SpyHashStateImpl< T >::combine_contiguous().
VerifyTypeImplementsAbslHashCorrectly()
template<typename Container , typename Eq > ABSL_MUST_USE_RESULT testing::AssertionResult absl::hash_internal::VerifyTypeImplementsAbslHashCorrectly (const Container & values, Eq equals)
Definition at line 188 of file hash_testing.h.
{
  using V = typename Container::value_type;
  struct Info {
    const V& value;
    size_t index;
    std::string ToString() const {
      return absl::visit(PrintVisitor{index}, value);
    }
    SpyHashState expand() const { return absl::visit(ExpandVisitor{}, value); }
  };
  using EqClass = std::vector<Info>;
  std::vector<EqClass> classes;
  // Gather the values in equivalence classes.
  size_t i = 0;
  for (const auto& value : values) {
    EqClass* c = nullptr;
    for (auto& eqclass : classes) {
      if (absl::visit(EqVisitor<Eq>{equals}, value, eqclass[0].value)) {
        c = &eqclass;
        break;
      }
    }
    if (c == nullptr) {
      classes.emplace_back();
      c = &classes.back();
    }
    c->push_back({value, i});
    ++i;
    // Verify potential errors captured by SpyHashState.
    if (auto error = c->back().expand().error()) {
      return testing::AssertionFailure() << *error;
    }
  }
  if (classes.size() < 2) {
    return testing::AssertionFailure()
           << "At least two equivalence classes are expected.";
  }
  // We assume that equality is correctly implemented.
  // Now we verify that AbslHashValue is also correctly implemented.
  for (const auto& c : classes) {
    // All elements of the equivalence class must have the same hash
    // expansion.
    const SpyHashState expected = c[0].expand();
    for (const Info& v : c) {
      if (v.expand() != v.expand()) {
        return testing::AssertionFailure()
               << "Hash expansion for " << v.ToString()
               << " is non-deterministic.";
      }
      if (v.expand() != expected) {
        return testing::AssertionFailure()
               << "Values " << c[0].ToString() << " and " << v.ToString()
               << " evaluate as equal but have an unequal hash expansion.";
      }
    }
    // Elements from other classes must have different hash expansion.
    for (const auto& c2 : classes) {
      if (&c == &c2) continue;
      const SpyHashState c2_hash = c2[0].expand();
      switch (SpyHashState::Compare(expected, c2_hash)) {
        case SpyHashState::CompareResult::kEqual:
          return testing::AssertionFailure()
                 << "Values " << c[0].ToString() << " and " << c2[0].ToString()
                 << " evaluate as unequal but have an equal hash expansion.";
        case SpyHashState::CompareResult::kBSuffixA:
          return testing::AssertionFailure()
                 << "Hash expansion of " << c2[0].ToString()
                 << " is a suffix of the hash expansion of " << c[0].ToString()
                 << ".";
        case SpyHashState::CompareResult::kASuffixB:
          return testing::AssertionFailure()
                 << "Hash expansion of " << c[0].ToString()
                 << " is a suffix of the hash expansion of " << c2[0].ToString()
                 << ".";
        case SpyHashState::CompareResult::kUnequal:
          break;
      }
    }
  }
  return testing::AssertionSuccess();
}
References absl::c, absl::hash_internal::SpyHashStateImpl< T >::Compare(), absl::i, absl::hash_internal::SpyHashStateImpl< T >::kASuffixB, absl::hash_internal::SpyHashStateImpl< T >::kBSuffixA, absl::hash_internal::SpyHashStateImpl< T >::kEqual, absl::hash_internal::SpyHashStateImpl< T >::kUnequal, absl::v, value, values, and absl::visit().
Referenced by absl::VerifyTypeImplementsAbslHashCorrectly(), absl::VerifyTypeImplementsAbslHashCorrectly(), absl::VerifyTypeImplementsAbslHashCorrectly(), and absl::VerifyTypeImplementsAbslHashCorrectly().
Variable Documentation
kHashSalt
uint64_t absl::hash_internal::kHashSalt[5] constexpr
Initial value:
= {
    uint64_t{0x243F6A8885A308D3}, uint64_t{0x13198A2E03707344},
    uint64_t{0xA4093822299F31D0}, uint64_t{0x082EFA98EC4E6C89},
    uint64_t{0x452821E638D01377},
}
Definition at line 56 of file hash.cc.
{
    uint64_t{0x243F6A8885A308D3}, uint64_t{0x13198A2E03707344},
    uint64_t{0xA4093822299F31D0}, uint64_t{0x082EFA98EC4E6C89},
    uint64_t{0x452821E638D01377},
};