open spiel: open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre Namespace Reference
open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre Namespace Reference
Classes
class Solver
Functions
gradients (dist, y, payoff_matrices, num_players, temperature=0., proj_grad=True)
cheap_gradients (random, dist, y, payoff_matrices, num_players, temperature=0., proj_grad=True)
cheap_gradients_vr (random, dist, y, payoff_matrices, num_players, pm_vr, temperature=0., proj_grad=True, version=0)
euc_project (dist, y)
mirror_project (dist, y)
Detailed Description
Quantal Response Equilibrium (QRE) Stochastic Approximate Nash Solver.
Function Documentation
cheap_gradients()
open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.cheap_gradients (random, dist, y, payoff_matrices, num_players, temperature = 0., proj_grad = True)
Computes exploitablity gradient and aux variable gradients with samples.
This implementation takes payoff_matrices as input so technically uses O(d^2)
compute but only a single column of payoff_matrices is used to perform the
update so can be re-implemented in O(d) if needed.
Args:
  random: random number generator, np.random.RandomState(seed)
  dist: 1-d np.array, current estimate of nash distribution
  y: 1-d np.array (same shape as dist), current estimate of payoff gradient
  payoff_matrices: (>=2 x A x A) np.array, payoffs for each joint action
  num_players: int, number of players, in case payoff_matrices is abbreviated
  temperature: non-negative float, default 0.
  proj_grad: bool, if True, projects dist gradient onto simplex
Returns:
  gradient of exploitability w.r.t. (dist, y) as tuple
  unregularized exploitability (stochastic estimate)
  tsallis regularized exploitability (stochastic estimate)
Definition at line 197 of file qre.py.
                    temperature=0., proj_grad=True):
  """Computes exploitablity gradient and aux variable gradients with samples.
  This implementation takes payoff_matrices as input so technically uses O(d^2)
  compute but only a single column of payoff_matrices is used to perform the
  update so can be re-implemented in O(d) if needed.
  Args:
    random: random number generator, np.random.RandomState(seed)
    dist: 1-d np.array, current estimate of nash distribution
    y: 1-d np.array (same shape as dist), current estimate of payoff gradient
    payoff_matrices: (>=2 x A x A) np.array, payoffs for each joint action
    num_players: int, number of players, in case payoff_matrices is abbreviated
    temperature: non-negative float, default 0.
    proj_grad: bool, if True, projects dist gradient onto simplex
  Returns:
    gradient of exploitability w.r.t. (dist, y) as tuple
    unregularized exploitability (stochastic estimate)
    tsallis regularized exploitability (stochastic estimate)
  """
  action_1 = random.choice(dist.size, p=dist)
  nabla = payoff_matrices[0][:, action_1]
  if temperature > 0:
    br = special.softmax(y / temperature)
    br_policy_gradient = nabla - temperature * (np.log(br) + 1)
  else:
    power = np.inf
    s = np.linalg.norm(y, ord=power)
    br = np.zeros_like(dist)
    maxima = (y == s)
    br[maxima] = 1. / maxima.sum()
    br_policy_gradient = np.zeros_like(br)
  unreg_exp = np.max(y) - y.dot(dist)
  entr_br = temperature * special.entr(br).sum()
  entr_dist = temperature * special.entr(dist).sum()
  reg_exp = y.dot(br - dist) + entr_br - entr_dist
  policy_gradient = nabla
  if temperature > 0:
    policy_gradient -= temperature * (np.log(dist) + 1)
  other_player_fx = (br - dist)
  if temperature > 0:
    # much faster to avoid constructing br_mat and then computing
    # br_mat.dot(br_policy_gradient) -- instead, expand out and only compute
    # inner products
    temp = (br_policy_gradient - br.dot(br_policy_gradient))
    other_player_fx += br / temperature * temp
  action_u = random.choice(dist.size)  # uniform, ~importance sampling
  other_player_fx = dist.size * other_player_fx[action_u]
  other_player_fx_translated = payoff_matrices[1, :, action_u] * other_player_fx
  grad_dist = -policy_gradient + (num_players - 1) * other_player_fx_translated
  if proj_grad:
    grad_dist = simplex.project_grad(grad_dist)
  grad_y = y - nabla
  return (grad_dist, grad_y), unreg_exp, reg_exp
Referenced by open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver.compute_gradients().
cheap_gradients_vr()
open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.cheap_gradients_vr (random, dist, y, payoff_matrices, num_players, pm_vr, temperature = 0., proj_grad = True, version = 0)
Computes exploitablity gradient and aux variable gradients with samples.
This implementation takes payoff_matrices as input so technically uses O(d^2)
compute but only a single column of payoff_matrices is used to perform the
update so can be re-implemented in O(d) if needed.
Args:
  random: random number generator, np.random.RandomState(seed)
  dist: 1-d np.array, current estimate of nash distribution
  y: 1-d np.array (same shape as dist), current estimate of payoff gradient
  payoff_matrices: (>=2 x A x A) np.array, payoffs for each joint action
  num_players: int, number of players, in case payoff_matrices is abbreviated
  pm_vr: approximate payoff_matrix for variance reduction
  temperature: non-negative float, default 0.
  proj_grad: bool, if True, projects dist gradient onto simplex
  version: int, default 0, two options for variance reduction
Returns:
  gradient of exploitability w.r.t. (dist, y) as tuple
  unregularized exploitability (stochastic estimate)
  tsallis regularized exploitability (stochastic estimate)
Definition at line 258 of file qre.py.
                       temperature=0., proj_grad=True, version=0):
  """Computes exploitablity gradient and aux variable gradients with samples.
  This implementation takes payoff_matrices as input so technically uses O(d^2)
  compute but only a single column of payoff_matrices is used to perform the
  update so can be re-implemented in O(d) if needed.
  Args:
    random: random number generator, np.random.RandomState(seed)
    dist: 1-d np.array, current estimate of nash distribution
    y: 1-d np.array (same shape as dist), current estimate of payoff gradient
    payoff_matrices: (>=2 x A x A) np.array, payoffs for each joint action
    num_players: int, number of players, in case payoff_matrices is abbreviated
    pm_vr: approximate payoff_matrix for variance reduction
    temperature: non-negative float, default 0.
    proj_grad: bool, if True, projects dist gradient onto simplex
    version: int, default 0, two options for variance reduction
  Returns:
    gradient of exploitability w.r.t. (dist, y) as tuple
    unregularized exploitability (stochastic estimate)
    tsallis regularized exploitability (stochastic estimate)
  """
  if pm_vr is None:
    raise ValueError("pm_vr must be np.array of shape (num_strats, num_strats)")
  if (not isinstance(version, int)) or (version < 0) or (version > 1):
    raise ValueError("version must be non-negative int < 2")
  action_1 = random.choice(dist.size, p=dist)
  nabla = payoff_matrices[0][:, action_1]
  if temperature > 0:
    br = special.softmax(y / temperature)
    br_policy_gradient = nabla - temperature * (np.log(br) + 1)
  else:
    power = np.inf
    s = np.linalg.norm(y, ord=power)
    br = np.zeros_like(dist)
    maxima = (y == s)
    br[maxima] = 1. / maxima.sum()
    br_policy_gradient = np.zeros_like(br)
  unreg_exp = np.max(y) - y.dot(dist)
  entr_br = temperature * special.entr(br).sum()
  entr_dist = temperature * special.entr(dist).sum()
  reg_exp = y.dot(br - dist) + entr_br - entr_dist
  policy_gradient = nabla
  if temperature > 0:
    policy_gradient -= temperature * (np.log(dist) + 1)
  other_player_fx = (br - dist)
  if temperature > 0:
    # much faster to avoid constructing br_mat and then computing
    # br_mat.dot(br_policy_gradient) -- instead, expand out and only compute
    # inner products
    temp = (br_policy_gradient - br.dot(br_policy_gradient))
    other_player_fx += br / temperature * temp
  if version == 0:
    other_player_fx_translated = pm_vr.dot(other_player_fx)
    action_u = random.choice(dist.size)  # uniform, ~importance sampling
    other_player_fx = other_player_fx[action_u]
    pm_mod = dist.size * (payoff_matrices[1, :, action_u] - pm_vr[:, action_u])
    other_player_fx_translated += pm_mod * other_player_fx
  elif version == 1:
    other_player_fx_translated = np.sum(pm_vr, axis=1)
    action_u = random.choice(dist.size)  # uniform, ~importance sampling
    other_player_fx = other_player_fx[action_u]
    pm_mod = dist.size * payoff_matrices[1, :, action_u]
    r = dist.size * pm_vr[:, action_u]
    other_player_fx_translated += pm_mod * other_player_fx - r
  grad_dist = -policy_gradient + (num_players - 1) * other_player_fx_translated
  if proj_grad:
    grad_dist = simplex.project_grad(grad_dist)
  grad_y = y - nabla
  if version == 0:
    pm_vr[:, action_u] = payoff_matrices[1, :, action_u]
  elif version == 1:
    pm_vr[:, action_u] = payoff_matrices[1, :, action_u] * other_player_fx
  return (grad_dist, grad_y), pm_vr, unreg_exp, reg_exp
Referenced by open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver.compute_gradients().
euc_project()
open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.euc_project (dist, y)
Project variables onto their feasible sets (euclidean proj for dist).
Args:
  dist: 1-d np.array, current estimate of nash distribution
  y: 1-d np.array (same shape as dist), current estimate of payoff gradient
Returns:
  projected variables (dist, y) as tuple
Definition at line 342 of file qre.py.
def euc_project(dist, y):
  """Project variables onto their feasible sets (euclidean proj for dist).
  Args:
    dist: 1-d np.array, current estimate of nash distribution
    y: 1-d np.array (same shape as dist), current estimate of payoff gradient
  Returns:
    projected variables (dist, y) as tuple
  """
  dist = simplex.euclidean_projection_onto_simplex(dist)
  y = np.clip(y, 0., np.inf)
  return dist, y
Referenced by open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver.euc_descent_step().
gradients()
open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.gradients (dist, y, payoff_matrices, num_players, temperature = 0., proj_grad = True)
Computes exploitablity gradient and aux variable gradients.
Args:
  dist: 1-d np.array, current estimate of nash distribution
  y: 1-d np.array (same shape as dist), current estimate of payoff gradient
  payoff_matrices: (>=2 x A x A) np.array, payoffs for each joint action
  num_players: int, number of players, in case payoff_matrices is abbreviated
  temperature: non-negative float, default 0.
  proj_grad: bool, if True, projects dist gradient onto simplex
Returns:
  gradient of exploitability w.r.t. (dist, y) as tuple
  unregularized exploitability (stochastic estimate)
  tsallis regularized exploitability (stochastic estimate)
Definition at line 144 of file qre.py.
              proj_grad=True):
  """Computes exploitablity gradient and aux variable gradients.
  Args:
    dist: 1-d np.array, current estimate of nash distribution
    y: 1-d np.array (same shape as dist), current estimate of payoff gradient
    payoff_matrices: (>=2 x A x A) np.array, payoffs for each joint action
    num_players: int, number of players, in case payoff_matrices is abbreviated
    temperature: non-negative float, default 0.
    proj_grad: bool, if True, projects dist gradient onto simplex
  Returns:
    gradient of exploitability w.r.t. (dist, y) as tuple
    unregularized exploitability (stochastic estimate)
    tsallis regularized exploitability (stochastic estimate)
  """
  nabla = payoff_matrices[0].dot(dist)
  if temperature > 0:
    br = special.softmax(y / temperature)
    br_policy_gradient = nabla - temperature * (np.log(br) + 1)
  else:
    power = np.inf
    s = np.linalg.norm(y, ord=power)
    br = np.zeros_like(dist)
    maxima = (y == s)
    br[maxima] = 1. / maxima.sum()
    br_policy_gradient = np.zeros_like(br)
  unreg_exp = np.max(y) - y.dot(dist)
  entr_br = temperature * special.entr(br).sum()
  entr_dist = temperature * special.entr(dist).sum()
  reg_exp = y.dot(br - dist) + entr_br - entr_dist
  policy_gradient = nabla
  if temperature > 0:
    policy_gradient -= temperature * (np.log(dist) + 1)
  other_player_fx = (br - dist)
  if temperature > 0:
    # much faster to avoid constructing br_mat and then computing
    # br_mat.dot(br_policy_gradient) -- instead, expand out and only compute
    # inner products
    temp = (br_policy_gradient - br.dot(br_policy_gradient))
    other_player_fx += br / temperature * temp
  other_player_fx_translated = payoff_matrices[1].dot(other_player_fx)
  grad_dist = -policy_gradient + (num_players - 1) * other_player_fx_translated
  if proj_grad:
    grad_dist = simplex.project_grad(grad_dist)
  grad_y = y - nabla
  return (grad_dist, grad_y), unreg_exp, reg_exp
Referenced by open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver.compute_gradients().
mirror_project()
open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.mirror_project (dist, y)
Project variables onto their feasible sets (softmax for dist).
Args:
  dist: 1-d np.array, current estimate of nash distribution
  y: 1-d np.array (same shape as dist), current estimate of payoff gradient
Returns:
  projected variables (dist, y) as tuple
Definition at line 357 of file qre.py.
def mirror_project(dist, y):
  """Project variables onto their feasible sets (softmax for dist).
  Args:
    dist: 1-d np.array, current estimate of nash distribution
    y: 1-d np.array (same shape as dist), current estimate of payoff gradient
  Returns:
    projected variables (dist, y) as tuple
  """
  dist = special.softmax(dist)
  y = np.clip(y, 0., np.inf)
  return dist, y
Referenced by open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver.mirror_descent_step().