open spiel: absl::container_algorithm_internal Namespace Reference
absl::container_algorithm_internal Namespace Reference
Classes
struct IsUnorderedContainer
struct IsUnorderedContainer< absl::flat_hash_map< Key, T, Hash, KeyEqual, Allocator > >
struct IsUnorderedContainer< absl::flat_hash_set< Key, Hash, KeyEqual, Allocator > >
struct IsUnorderedContainer< absl::node_hash_map< Key, T, Hash, KeyEqual, Allocator > >
struct IsUnorderedContainer< absl::node_hash_set< Key, Hash, KeyEqual, Allocator > >
struct IsUnorderedContainer< std::unordered_map< Key, T, Hash, KeyEqual, Allocator > >
struct IsUnorderedContainer< std::unordered_set< Key, Hash, KeyEqual, Allocator > >
Typedefs
template<typename C >
using ContainerIter = decltype(begin(std::declval<C&>()))
template<typename C1 , typename C2 >
using ContainerIterPairType
template<typename C >
using ContainerDifferenceType
template<typename C >
using ContainerPointerType
Functions
template<typename C >
ContainerIter< C > c_begin (C &c)
template<typename C >
ContainerIter< C > c_end (C &c)
template<class C >
auto c_size (C &c) -> decltype(c.size())
template<class T , std::size_t N>
constexpr std::size_t c_size (T(&)[N])
Typedef Documentation
ContainerDifferenceType
template<typename C > using absl::container_algorithm_internal::ContainerDifferenceType
Initial value:
 decltype(std::distance(
    std::declval<ContainerIter<C>>(), std::declval<ContainerIter<C>>()))
Definition at line 80 of file container.h.
ContainerIter
template<typename C > using absl::container_algorithm_internal::ContainerIter = decltype(begin(std::declval<C&>()))
Definition at line 71 of file container.h.
ContainerIterPairType
template<typename C1 , typename C2 > using absl::container_algorithm_internal::ContainerIterPairType
Initial value:
    decltype(std::make_pair(ContainerIter<C1>(), ContainerIter<C2>()))
Definition at line 76 of file container.h.
ContainerPointerType
template<typename C > using absl::container_algorithm_internal::ContainerPointerType
Initial value:
    typename std::iterator_traits<ContainerIter<C>>::pointer
Definition at line 84 of file container.h.
Function Documentation
c_begin()
template<typename C > ContainerIter< C > absl::container_algorithm_internal::c_begin (C & c)
Definition at line 99 of file container.h.
{
  return begin(c);
}
References begin, and absl::c.
Referenced by absl::c_accumulate(), absl::c_accumulate(), absl::c_adjacent_difference(), absl::c_adjacent_difference(), absl::c_adjacent_find(), absl::c_adjacent_find(), absl::c_all_of(), absl::c_any_of(), absl::c_binary_search(), absl::c_binary_search(), absl::c_copy(), absl::c_copy_backward(), absl::c_copy_if(), absl::c_copy_n(), absl::c_count(), absl::c_count_if(), absl::c_distance(), absl::c_equal(), absl::c_equal(), absl::c_equal_range(), absl::c_equal_range(), absl::c_fill(), absl::c_fill_n(), absl::c_find(), absl::c_find_end(), absl::c_find_end(), absl::c_find_first_of(), absl::c_find_first_of(), absl::c_find_if(), absl::c_find_if_not(), absl::c_for_each(), absl::c_generate(), absl::c_generate_n(), absl::c_includes(), absl::c_includes(), absl::c_inner_product(), absl::c_inner_product(), absl::c_inplace_merge(), absl::c_inplace_merge(), absl::c_iota(), absl::c_is_heap(), absl::c_is_heap(), absl::c_is_heap_until(), absl::c_is_heap_until(), absl::c_is_partitioned(), absl::c_is_sorted(), absl::c_is_sorted(), absl::c_is_sorted_until(), absl::c_is_sorted_until(), absl::c_lexicographical_compare(), absl::c_lexicographical_compare(), absl::c_linear_search(), absl::c_lower_bound(), absl::c_lower_bound(), absl::c_make_heap(), absl::c_make_heap(), absl::c_max_element(), absl::c_max_element(), absl::c_merge(), absl::c_merge(), absl::c_min_element(), absl::c_min_element(), absl::c_minmax_element(), absl::c_minmax_element(), absl::c_mismatch(), absl::c_mismatch(), absl::c_move(), absl::c_move_backward(), absl::c_next_permutation(), absl::c_next_permutation(), absl::c_none_of(), absl::c_nth_element(), absl::c_nth_element(), absl::c_partial_sort(), absl::c_partial_sort(), absl::c_partial_sort_copy(), absl::c_partial_sort_copy(), absl::c_partial_sum(), absl::c_partial_sum(), absl::c_partition(), absl::c_partition_copy(), absl::c_partition_point(), absl::c_pop_heap(), absl::c_pop_heap(), absl::c_prev_permutation(), absl::c_prev_permutation(), absl::c_push_heap(), absl::c_push_heap(), absl::c_remove_copy(), absl::c_remove_copy_if(), absl::c_replace(), absl::c_replace_copy(), absl::c_replace_copy_if(), absl::c_replace_if(), absl::c_reverse(), absl::c_reverse_copy(), absl::c_rotate(), absl::c_rotate_copy(), absl::c_search(), absl::c_search(), absl::c_search_n(), absl::c_search_n(), absl::c_set_difference(), absl::c_set_difference(), absl::c_set_intersection(), absl::c_set_intersection(), absl::c_set_symmetric_difference(), absl::c_set_symmetric_difference(), absl::c_set_union(), absl::c_set_union(), absl::c_shuffle(), absl::c_sort(), absl::c_sort(), absl::c_sort_heap(), absl::c_sort_heap(), absl::c_stable_partition(), absl::c_stable_sort(), absl::c_stable_sort(), absl::c_swap_ranges(), absl::c_transform(), absl::c_transform(), absl::c_unique_copy(), absl::c_unique_copy(), absl::c_upper_bound(), and absl::c_upper_bound().
c_end()
template<typename C > ContainerIter< C > absl::container_algorithm_internal::c_end (C & c)
Definition at line 104 of file container.h.
{
  return end(c);
}
References absl::c, and end.
Referenced by absl::c_accumulate(), absl::c_accumulate(), absl::c_adjacent_difference(), absl::c_adjacent_difference(), absl::c_adjacent_find(), absl::c_adjacent_find(), absl::c_all_of(), absl::c_any_of(), absl::c_binary_search(), absl::c_binary_search(), absl::c_copy(), absl::c_copy_backward(), absl::c_copy_if(), absl::c_count(), absl::c_count_if(), absl::c_distance(), absl::c_equal(), absl::c_equal(), absl::c_equal_range(), absl::c_equal_range(), absl::c_fill(), absl::c_find(), absl::c_find_end(), absl::c_find_end(), absl::c_find_first_of(), absl::c_find_first_of(), absl::c_find_if(), absl::c_find_if_not(), absl::c_for_each(), absl::c_generate(), absl::c_includes(), absl::c_includes(), absl::c_inner_product(), absl::c_inner_product(), absl::c_inplace_merge(), absl::c_inplace_merge(), absl::c_iota(), absl::c_is_heap(), absl::c_is_heap(), absl::c_is_heap_until(), absl::c_is_heap_until(), absl::c_is_partitioned(), absl::c_is_sorted(), absl::c_is_sorted(), absl::c_is_sorted_until(), absl::c_is_sorted_until(), absl::c_lexicographical_compare(), absl::c_lexicographical_compare(), absl::c_linear_search(), absl::c_lower_bound(), absl::c_lower_bound(), absl::c_make_heap(), absl::c_make_heap(), absl::c_max_element(), absl::c_max_element(), absl::c_merge(), absl::c_merge(), absl::c_min_element(), absl::c_min_element(), absl::c_minmax_element(), absl::c_minmax_element(), absl::c_mismatch(), absl::c_mismatch(), absl::c_move(), absl::c_move_backward(), absl::c_next_permutation(), absl::c_next_permutation(), absl::c_none_of(), absl::c_nth_element(), absl::c_nth_element(), absl::c_partial_sort(), absl::c_partial_sort(), absl::c_partial_sort_copy(), absl::c_partial_sort_copy(), absl::c_partial_sum(), absl::c_partial_sum(), absl::c_partition(), absl::c_partition_copy(), absl::c_partition_point(), absl::c_pop_heap(), absl::c_pop_heap(), absl::c_prev_permutation(), absl::c_prev_permutation(), absl::c_push_heap(), absl::c_push_heap(), absl::c_remove_copy(), absl::c_remove_copy_if(), absl::c_replace(), absl::c_replace_copy(), absl::c_replace_copy_if(), absl::c_replace_if(), absl::c_reverse(), absl::c_reverse_copy(), absl::c_rotate(), absl::c_rotate_copy(), absl::c_search(), absl::c_search(), absl::c_search_n(), absl::c_search_n(), absl::c_set_difference(), absl::c_set_difference(), absl::c_set_intersection(), absl::c_set_intersection(), absl::c_set_symmetric_difference(), absl::c_set_symmetric_difference(), absl::c_set_union(), absl::c_set_union(), absl::c_shuffle(), absl::c_sort(), absl::c_sort(), absl::c_sort_heap(), absl::c_sort_heap(), absl::c_stable_partition(), absl::c_stable_sort(), absl::c_stable_sort(), absl::c_swap_ranges(), absl::c_transform(), absl::c_transform(), absl::c_unique_copy(), absl::c_unique_copy(), absl::c_upper_bound(), and absl::c_upper_bound().
c_size() [1/2]
template<class C > auto absl::container_algorithm_internal::c_size (C & c) -> decltype(c.size())
Definition at line 122 of file container.h.
{
  return c.size();
}
References absl::c.
Referenced by absl::c_equal(), and absl::c_equal().
c_size() [2/2]
template<class T , std::size_t N> std::size_t absl::container_algorithm_internal::c_size (T(&) [N]) constexpr
Definition at line 127 of file container.h.
{
  return N;
}