open spiel: generate_copts Namespace Reference
generate_copts Namespace Reference
Classes
class CMakeStyle
class StarlarkStyle
Functions
file_header_lines ()
flatten (*lists)
relative_filename (filename)
copt_list (name, arg_list, style)
generate_copt_file (style)
main (argv)
Detailed Description
Generate Abseil compile compile option configs.
Usage: <path_to_absl>/copts/generate_copts.py
The configs are generated from copts.py.
Function Documentation
copt_list()
generate_copts.copt_list (name, arg_list, style)
Copt file generation.
Definition at line 73 of file generate_copts.py.
def copt_list(name, arg_list, style):
  """Copt file generation."""
  make_line = lambda s: "    \"" + s + "\"" + style.separator()
  external_str_list = [make_line(s) for s in arg_list]
  return "\n".join(
      flatten(
          [style.list_introducer(name)],
          external_str_list,
          [style.list_closer()]))
References flatten().
Referenced by generate_copt_file().
file_header_lines()
generate_copts.file_header_lines ()
Definition at line 15 of file generate_copts.py.
def file_header_lines():
  return [
      "GENERATED! DO NOT MANUALLY EDIT THIS FILE.", "",
      "(1) Edit absl/copts/copts.py.",
      "(2) Run `python <path_to_absl>/copts/generate_copts.py`."
  ]
Referenced by generate_copts.CMakeStyle.docstring(), and generate_copts.StarlarkStyle.docstring().
flatten()
generate_copts.flatten (* lists)
Definition at line 23 of file generate_copts.py.
def flatten(*lists):
  return [item for sublist in lists for item in sublist]
Referenced by copt_list(), and generate_copts.StarlarkStyle.docstring().
generate_copt_file()
generate_copts.generate_copt_file (style)
Creates a generated copt file using the given style object.
Args:
  style: either StarlarkStyle() or CMakeStyle()
Definition at line 86 of file generate_copts.py.
def generate_copt_file(style):
  """Creates a generated copt file using the given style object.
  Args:
    style: either StarlarkStyle() or CMakeStyle()
  """
  with open(relative_filename(style.filename()), "w") as f:
    f.write(style.docstring())
    f.write("\n")
    for var_name, arg_list in sorted(COPT_VARS.items()):
      f.write("\n")
      f.write(copt_list(var_name, arg_list, style))
References copt_list(), and relative_filename().
Referenced by main().
main()
generate_copts.main (argv)
Definition at line 100 of file generate_copts.py.
def main(argv):
  if len(argv) > 1:
    raise RuntimeError("generate_copts needs no command line args")
  generate_copt_file(StarlarkStyle())
  generate_copt_file(CMakeStyle())
References generate_copt_file(), and len.
relative_filename()
generate_copts.relative_filename (filename)
Definition at line 27 of file generate_copts.py.
def relative_filename(filename):
  return path.join(path.dirname(__file__), filename)
# Style classes.  These contain all the syntactic styling needed to generate a
# copt file for different build tools.
Referenced by generate_copt_file().