open spiel: open_spiel::hearts Namespace Reference
open_spiel::hearts Namespace Reference
Classes
class HeartsGame
class HeartsState
class Trick
class XinxinBot
Enumerations
enum class Suit { kClubs = 0 , kDiamonds = 1 , kHearts = 2 , kSpades = 3 }
enum class PassDir { kNoPass = 0 , kLeft = 1 , kAcross = 2 , kRight = 3 }
enum Seat { kNorth , kEast , kSouth , kWest }
Functions
Action GetOpenSpielAction (::hearts::card card)
::hearts::card GetXinxinAction (Action action)
std::unique_ptr< Bot > MakeXinxinBot (GameParameters params, int uct_num_runs, double uct_c_val, int iimc_num_worlds, bool use_threads)
Suit CardSuit (int card)
int CardRank (int card)
int Card (Suit suit, int rank)
int CardPoints (int card, bool jd_bonus)
std::string DirString (int dir)
std::string CardString (int card)
Variables
constexpr int kNumPlayers = 4
constexpr int kNumSuits = 4
constexpr int kNumCardsPerSuit = 13
constexpr int kNumCards = 52
constexpr int kNumCardsInPass = 3
constexpr int kNumTricks = kNumCards / kNumPlayers
constexpr int kPointsForHeart = 1
constexpr int kPointsForQS = 13
constexpr int kPointsForJD = -10
constexpr int kTotalPositivePoints = 26
constexpr int kMinScore = 0
constexpr int kMaxScore = kTotalPositivePoints - kPointsForJD
constexpr int kAvoidAllTricksBonus = -5
constexpr int kTrickTensorSize = kNumCards * 7
constexpr int kInformationStateTensorSize
constexpr char kRankChar [] = "23456789TJQKA"
constexpr char kSuitChar [] = "CDHS"
constexpr char kDirChar [] = "NESW"
std::map< int, std::string > pass_dir_str
Enumeration Type Documentation
PassDir
enum class open_spiel::hearts::PassDir strong
Enumerator
kNoPass
kLeft
kAcross
kRight
Definition at line 75 of file hearts.h.
{ kNoPass = 0, kLeft = 1, kAcross = 2, kRight = 3 };
Seat
enum open_spiel::hearts::Seat
Enumerator
kNorth
kEast
kSouth
kWest
Definition at line 76 of file hearts.h.
{ kNorth, kEast, kSouth, kWest };
Suit
enum class open_spiel::hearts::Suit strong
Enumerator
kClubs
kDiamonds
kHearts
kSpades
Definition at line 74 of file hearts.h.
{ kClubs = 0, kDiamonds = 1, kHearts = 2, kSpades = 3 };
Function Documentation
Card()
int open_spiel::hearts::Card (Suit suit, int rank) inline
Definition at line 80 of file hearts.h.
{
  return rank * kNumSuits + static_cast<int>(suit);
}
References kNumSuits, and rank.
Referenced by CardPoints(), GetOpenSpielAction(), and open_spiel::hearts::HeartsState::ResampleFromInfostate().
CardPoints()
int open_spiel::hearts::CardPoints (int card, bool jd_bonus) inline
Definition at line 83 of file hearts.h.
{
  if (CardSuit(card) == Suit::kHearts) {
    return kPointsForHeart;
  } else if (card == Card(Suit::kSpades, 10)) {
    return kPointsForQS;
  } else if (card == Card(Suit::kDiamonds, 9) && jd_bonus) {
    return kPointsForJD;
  } else {
    return 0;
  }
}
References Card(), CardSuit(), kDiamonds, kHearts, kPointsForHeart, kPointsForJD, kPointsForQS, and kSpades.
Referenced by open_spiel::hearts::Trick::Play().
CardRank()
int open_spiel::hearts::CardRank (int card) inline
Definition at line 79 of file hearts.h.
{ return card / kNumSuits; }
References kNumSuits.
Referenced by CardString(), GetXinxinAction(), and open_spiel::hearts::Trick::Play().
CardString()
std::string open_spiel::hearts::CardString (int card) inline
Definition at line 98 of file hearts.h.
{
  return {kRankChar[CardRank(card)],
          kSuitChar[static_cast<int>(CardSuit(card))]};
}
References CardRank(), CardSuit(), kRankChar, and kSuitChar.
Referenced by open_spiel::hearts::HeartsState::ActionToString().
CardSuit()
Suit open_spiel::hearts::CardSuit (int card) inline
Definition at line 78 of file hearts.h.
{ return Suit(card % kNumSuits); }
References kNumSuits.
Referenced by CardPoints(), CardString(), GetXinxinAction(), and open_spiel::hearts::Trick::Play().
DirString()
std::string open_spiel::hearts::DirString (int dir) inline
Definition at line 97 of file hearts.h.
{ return {kDirChar[dir]}; }
References dir, and kDirChar.
GetOpenSpielAction()
Action open_spiel::hearts::GetOpenSpielAction (::hearts::card card)
Definition at line 30 of file xinxin_bot.cc.
{
  // xinxin keeps ranks in the reverse order of open_spiel
  int rank = kNumCardsPerSuit - ::hearts::Deck::getrank(card) - 1;
  Suit suit = kXinxinSuits[::hearts::Deck::getsuit(card)];
  return Card(suit, rank);
}
References Card(), kNumCardsPerSuit, and rank.
Referenced by open_spiel::hearts::XinxinBot::Step().
GetXinxinAction()
hearts::card open_spiel::hearts::GetXinxinAction (Action action)
Definition at line 37 of file xinxin_bot.cc.
{
  int rank = kNumCardsPerSuit - CardRank(action) - 1;
  int suit =
      std::find(kXinxinSuits, kXinxinSuits + kNumSuits, CardSuit(action)) -
      kXinxinSuits;
  return ::hearts::Deck::getcard(suit, rank);
}
References action, CardRank(), CardSuit(), kNumCardsPerSuit, kNumSuits, and rank.
Referenced by open_spiel::hearts::XinxinBot::ForceAction(), and open_spiel::hearts::XinxinBot::InformAction().
MakeXinxinBot()
std::unique_ptr< Bot > open_spiel::hearts::MakeXinxinBot (GameParameters params, int uct_num_runs, double uct_c_val, int iimc_num_worlds, bool use_threads)
Definition at line 230 of file xinxin_bot.cc.
{
  int rules = XinxinBot::XinxinRules(params);
  return std::make_unique<XinxinBot>(rules, uct_num_runs, uct_c_val,
                                     iimc_num_worlds, use_threads);
}
References open_spiel::hearts::XinxinBot::XinxinRules().
Referenced by open_spiel::init_pyspiel_xinxin().
Variable Documentation
kAvoidAllTricksBonus
int open_spiel::hearts::kAvoidAllTricksBonus = -5 inline constexpr
Definition at line 63 of file hearts.h.
kDirChar
char open_spiel::hearts::kDirChar[] = "NESW" constexpr
Definition at line 96 of file hearts.h.
Referenced by DirString().
kInformationStateTensorSize
int open_spiel::hearts::kInformationStateTensorSize inline constexpr
Initial value:
=
    kNumPlayers
    + kNumCards
    + kNumCards
    + kNumCards
    + kNumCards
    + kMaxScore * kNumPlayers
    + kNumTricks * kTrickTensorSize
Definition at line 65 of file hearts.h.
Referenced by open_spiel::hearts::HeartsState::InformationStateTensor(), and open_spiel::hearts::HeartsGame::InformationStateTensorShape().
kMaxScore
int open_spiel::hearts::kMaxScore = kTotalPositivePoints - kPointsForJD inline constexpr
Definition at line 62 of file hearts.h.
Referenced by open_spiel::hearts::HeartsState::InformationStateTensor(), and open_spiel::hearts::HeartsGame::MaxUtility().
kMinScore
int open_spiel::hearts::kMinScore = 0 inline constexpr
Definition at line 61 of file hearts.h.
Referenced by open_spiel::hearts::HeartsGame::MinUtility().
kNumCards
int open_spiel::hearts::kNumCards = 52 inline constexpr
Definition at line 54 of file hearts.h.
Referenced by open_spiel::hearts::HeartsState::ChanceOutcomes(), open_spiel::hearts::XinxinBot::InformAction(), open_spiel::hearts::HeartsState::InformationStateTensor(), open_spiel::hearts::HeartsGame::MaxChanceOutcomes(), open_spiel::hearts::HeartsGame::MaxGameLength(), open_spiel::hearts::HeartsGame::NumDistinctActions(), and open_spiel::hearts::HeartsState::ResampleFromInfostate().
kNumCardsInPass
int open_spiel::hearts::kNumCardsInPass = 3 inline constexpr
Definition at line 55 of file hearts.h.
Referenced by open_spiel::hearts::HeartsState::InformationStateTensor(), open_spiel::hearts::HeartsGame::MaxGameLength(), and open_spiel::hearts::HeartsState::ResampleFromInfostate().
kNumCardsPerSuit
int open_spiel::hearts::kNumCardsPerSuit = 13 inline constexpr
Definition at line 53 of file hearts.h.
Referenced by GetOpenSpielAction(), and GetXinxinAction().
kNumPlayers
int open_spiel::hearts::kNumPlayers = 4 inline constexpr
Definition at line 51 of file hearts.h.
Referenced by open_spiel::hearts::HeartsState::ChanceOutcomes(), open_spiel::hearts::XinxinBot::InformAction(), open_spiel::hearts::HeartsState::InformationStateTensor(), open_spiel::hearts::HeartsGame::MaxGameLength(), open_spiel::hearts::HeartsGame::NumPlayers(), open_spiel::hearts::HeartsState::ResampleFromInfostate(), open_spiel::hearts::HeartsState::Returns(), and open_spiel::hearts::XinxinBot::XinxinBot().
kNumSuits
int open_spiel::hearts::kNumSuits = 4 inline constexpr
Definition at line 52 of file hearts.h.
Referenced by Card(), CardRank(), CardSuit(), GetXinxinAction(), and open_spiel::hearts::HeartsState::InformationStateString().
kNumTricks
int open_spiel::hearts::kNumTricks = kNumCards / kNumPlayers inline constexpr
Definition at line 56 of file hearts.h.
Referenced by open_spiel::hearts::HeartsState::InformationStateTensor().
kPointsForHeart
int open_spiel::hearts::kPointsForHeart = 1 inline constexpr
Definition at line 57 of file hearts.h.
Referenced by CardPoints().
kPointsForJD
int open_spiel::hearts::kPointsForJD = -10 inline constexpr
Definition at line 59 of file hearts.h.
Referenced by CardPoints(), and open_spiel::hearts::HeartsState::InformationStateTensor().
kPointsForQS
int open_spiel::hearts::kPointsForQS = 13 inline constexpr
Definition at line 58 of file hearts.h.
Referenced by CardPoints().
kRankChar
char open_spiel::hearts::kRankChar[] = "23456789TJQKA" constexpr
Definition at line 94 of file hearts.h.
Referenced by CardString().
kSuitChar
char open_spiel::hearts::kSuitChar[] = "CDHS" constexpr
Definition at line 95 of file hearts.h.
Referenced by CardString().
kTotalPositivePoints
int open_spiel::hearts::kTotalPositivePoints = 26 inline constexpr
Definition at line 60 of file hearts.h.
Referenced by open_spiel::hearts::XinxinBot::InformAction(), and open_spiel::hearts::HeartsState::Returns().
kTrickTensorSize
int open_spiel::hearts::kTrickTensorSize = kNumCards * 7 inline constexpr
Definition at line 64 of file hearts.h.
Referenced by open_spiel::hearts::HeartsState::InformationStateTensor().
pass_dir_str
std::map<int, std::string> open_spiel::hearts::pass_dir_str inline
Initial value:
= {
    {0, "No Pass"}, {1, "Left"}, {2, "Across"}, {3, "Right"}}
Definition at line 102 of file hearts.h.
{
    {0, "No Pass"}, {1, "Left"}, {2, "Across"}, {3, "Right"}};
Referenced by open_spiel::hearts::HeartsState::ActionToString(), open_spiel::hearts::HeartsState::InformationStateString(), and open_spiel::hearts::HeartsState::ToString().