open spiel: open_spiel.python.algorithms.double_oracle Namespace Reference
open_spiel.python.algorithms.double_oracle Namespace Reference
Classes
class DoubleOracleSolver
Functions
lens (lists)
solve_subgame (subgame_payoffs)
Detailed Description
Double Oracle algorithm.
Solves two-player zero-sum games, for more information see:
McMahan et al. (2003). Planning in the presence of cost functions controlled by
  an adversary. In Proceedings of the 20th International Conference on Machine
  Learning (ICML-03) (pp. 536-543).
Function Documentation
lens()
open_spiel.python.algorithms.double_oracle.lens (lists)
Returns the sizes of lists in a list.
Definition at line 30 of file double_oracle.py.
def lens(lists):
  """Returns the sizes of lists in a list."""
  return list(map(len, lists))
Referenced by open_spiel.python.algorithms.double_oracle.DoubleOracleSolver.oracle(), open_spiel.python.algorithms.double_oracle.DoubleOracleSolver.solve_yield(), and open_spiel.python.algorithms.double_oracle.DoubleOracleSolver.subgame_payoffs().
solve_subgame()
open_spiel.python.algorithms.double_oracle.solve_subgame (subgame_payoffs)
Solves the subgame using OpenSpiel's LP solver.
Definition at line 35 of file double_oracle.py.
def solve_subgame(subgame_payoffs):
  """Solves the subgame using OpenSpiel's LP solver."""
  p0_sol, p1_sol, _, _ = lp_solver.solve_zero_sum_matrix_game(
      pyspiel.create_matrix_game(*subgame_payoffs))
  p0_sol, p1_sol = np.asarray(p0_sol), np.asarray(p1_sol)
  return [p0_sol / p0_sol.sum(), p1_sol / p1_sol.sum()]
Referenced by open_spiel.python.algorithms.double_oracle.DoubleOracleSolver.solve_yield(), and open_spiel.python.algorithms.double_oracle.DoubleOracleSolver.step().