open spiel: open_spiel.python.egt.visualization_test Namespace Reference
open_spiel.python.egt.visualization_test Namespace Reference
Classes
class VisualizationTest
Functions
_build_dynamics2x2 ()
_build_dynamics3x3 ()
_identity_dynamics (x)
Detailed Description
Tests for open_spiel.python.egt.visualization.
Function Documentation
_build_dynamics2x2()
open_spiel.python.egt.visualization_test._build_dynamics2x2 () protected
Build multi-population dynamics.
Definition at line 41 of file visualization_test.py.
def _build_dynamics2x2():
  """Build multi-population dynamics."""
  game = pyspiel.load_game("matrix_pd")
  payoff_tensor = utils.game_payoffs_array(game)
  return dynamics.MultiPopulationDynamics(payoff_tensor, dynamics.replicator)
Referenced by open_spiel.python.egt.visualization_test.VisualizationTest.test_quiver2x2(), and open_spiel.python.egt.visualization_test.VisualizationTest.test_streamplot2x2().
_build_dynamics3x3()
open_spiel.python.egt.visualization_test._build_dynamics3x3 () protected
Build single-population dynamics.
Definition at line 48 of file visualization_test.py.
def _build_dynamics3x3():
  """Build single-population dynamics."""
  game = pyspiel.load_game("matrix_rps")
  payoff_tensor = utils.game_payoffs_array(game)
  return dynamics.SinglePopulationDynamics(payoff_tensor, dynamics.replicator)
Referenced by open_spiel.python.egt.visualization_test.VisualizationTest.test_quiver3x3(), and open_spiel.python.egt.visualization_test.VisualizationTest.test_streamplot3x3().
_identity_dynamics()
open_spiel.python.egt.visualization_test._identity_dynamics (x) protected
Returns same input as output.
Definition at line 55 of file visualization_test.py.
def _identity_dynamics(x):
  """Returns same input as output."""
  return x