open spiel: absl::internal_statusor Namespace Reference
absl::internal_statusor Namespace Reference
Classes
struct CopyAssignBase
struct CopyAssignBase< T, false >
struct CopyCtorBase
struct CopyCtorBase< T, false >
struct HasConversionOperatorToStatusOr
struct HasConversionOperatorToStatusOr< T, U, decltype(test< T, U >(0))>
class Helper
struct IsDirectInitializationAmbiguous
struct IsDirectInitializationAmbiguous< T, absl::StatusOr< V > >
struct IsForwardingAssignmentAmbiguous
struct IsForwardingAssignmentAmbiguous< T, absl::StatusOr< U > >
struct MoveAssignBase
struct MoveAssignBase< T, false >
struct MoveCtorBase
struct MoveCtorBase< T, false >
class StatusOrData
Typedefs
template<typename T , typename U >
using IsConstructibleOrConvertibleFromStatusOr
template<typename T , typename U >
using IsConstructibleOrConvertibleOrAssignableFromStatusOr
template<typename T , typename U >
using IsDirectInitializationValid
template<typename T , typename U >
using IsForwardingAssignmentValid
Functions
template<typename T , typename U >
void test (char(*)[sizeof(std::declval< U >().operator absl::StatusOr< T >())])
template<typename T , typename... Args>
ABSL_ATTRIBUTE_NONNULL (1) void PlacementNew(void *p
ABSL_ATTRIBUTE_NORETURN void ThrowBadStatusOrAccess (absl::Status status)
Variables
Args && args
Typedef Documentation
IsConstructibleOrConvertibleFromStatusOr
template<typename T , typename U > using absl::internal_statusor::IsConstructibleOrConvertibleFromStatusOr
Initial value:
    absl::disjunction<std::is_constructible<T, StatusOr<U>&>,
                      std::is_constructible<T, const StatusOr<U>&>,
                      std::is_constructible<T, StatusOr<U>&&>,
                      std::is_constructible<T, const StatusOr<U>&&>,
                      std::is_convertible<StatusOr<U>&, T>,
                      std::is_convertible<const StatusOr<U>&, T>,
                      std::is_convertible<StatusOr<U>&&, T>,
                      std::is_convertible<const StatusOr<U>&&, T>>
Definition at line 47 of file statusor_internal.h.
IsConstructibleOrConvertibleOrAssignableFromStatusOr
template<typename T , typename U > using absl::internal_statusor::IsConstructibleOrConvertibleOrAssignableFromStatusOr
Initial value:
    absl::disjunction<IsConstructibleOrConvertibleFromStatusOr<T, U>,
                      std::is_assignable<T&, StatusOr<U>&>,
                      std::is_assignable<T&, const StatusOr<U>&>,
                      std::is_assignable<T&, StatusOr<U>&&>,
                      std::is_assignable<T&, const StatusOr<U>&&>>
Definition at line 60 of file statusor_internal.h.
IsDirectInitializationValid
template<typename T , typename U > using absl::internal_statusor::IsDirectInitializationValid
Initial value:
 absl::disjunction<
    std::is_same<T, absl::remove_cv_t<absl::remove_reference_t<U>>>,
    absl::negation<absl::disjunction<
        std::is_same<absl::StatusOr<T>,
                     absl::remove_cv_t<absl::remove_reference_t<U>>>,
        std::is_same<absl::Status,
                     absl::remove_cv_t<absl::remove_reference_t<U>>>,
        std::is_same<absl::in_place_t,
                     absl::remove_cv_t<absl::remove_reference_t<U>>>,
        IsDirectInitializationAmbiguous<T, U>>>>
Definition at line 85 of file statusor_internal.h.
IsForwardingAssignmentValid
template<typename T , typename U > using absl::internal_statusor::IsForwardingAssignmentValid
Initial value:
 absl::disjunction<
    std::is_same<T, absl::remove_cv_t<absl::remove_reference_t<U>>>,
    absl::negation<absl::disjunction<
        std::is_same<absl::StatusOr<T>,
                     absl::remove_cv_t<absl::remove_reference_t<U>>>,
        std::is_same<absl::Status,
                     absl::remove_cv_t<absl::remove_reference_t<U>>>,
        std::is_same<absl::in_place_t,
                     absl::remove_cv_t<absl::remove_reference_t<U>>>,
        IsForwardingAssignmentAmbiguous<T, U>>>>
Definition at line 123 of file statusor_internal.h.
Function Documentation
ABSL_ATTRIBUTE_NONNULL()
template<typename T , typename... Args> absl::internal_statusor::ABSL_ATTRIBUTE_NONNULL (1)
References args, and absl::p.
test()
template<typename T , typename U > void absl::internal_statusor::test (char(*) [sizeof(std::declval< U >().operator absl::StatusOr< T >())])
ThrowBadStatusOrAccess()
void absl::internal_statusor::ThrowBadStatusOrAccess (absl::Status status)
Definition at line 89 of file statusor.cc.
{
#ifdef ABSL_HAVE_EXCEPTIONS
  throw absl::BadStatusOrAccess(std::move(status));
#else
  ABSL_INTERNAL_LOG(
      FATAL,
      absl::StrCat("Attempting to fetch value instead of handling error ",
                   status.ToString()));
  std::abort();
#endif
}
References ABSL_INTERNAL_LOG, and absl::StrCat().
Referenced by absl::StatusOr< T >::value(), absl::StatusOr< T >::value(), absl::StatusOr< T >::value(), and absl::StatusOr< T >::value().
Variable Documentation
args
Args&& absl::internal_statusor::args
Initial value:
{
  new (p) T(std::forward<Args>(args)...)
Definition at line 146 of file statusor_internal.h.
Referenced by ABSL_ATTRIBUTE_NONNULL(), and absl::internal_statusor::StatusOrData< T >::MakeStatus().