open spiel: open_spiel/abseil-cpp/absl/random/internal/nonsecure_base_test.cc File Reference
nonsecure_base_test.cc File Reference
#include "absl/random/internal/nonsecure_base.h"
#include <algorithm>
#include <cstdint>
#include <iostream>
#include <memory>
#include <random>
#include <sstream>
#include "gtest/gtest.h"
#include "absl/random/distributions.h"
#include "absl/random/random.h"
#include "absl/strings/str_cat.h"
Functions
TEST (NonsecureURBGBase, DefaultConstructorIsValid)
TEST (RecommendedTemplates, CanBeConstructed)
TEST (RecommendedTemplates, CanDiscardValues)
TEST (NonsecureURBGBase, StandardInterface)
TEST (NonsecureURBGBase, SeedSeqConstructorIsValid)
TEST (NonsecureURBGBase, CompatibleWithDistributionUtils)
TEST (NonsecureURBGBase, CompatibleWithStdDistributions)
TEST (NonsecureURBGBase, ConsecutiveDefaultInstancesYieldUniqueVariates)
TEST (NonsecureURBGBase, EqualSeedSequencesYieldEqualVariates)
TEST (RandenPoolSeedSeqTest, SeederWorksForU32)
TEST (RandenPoolSeedSeqTest, SeederWorksForU64)
TEST (RandenPoolSeedSeqTest, SeederWorksForS32)
TEST (RandenPoolSeedSeqTest, SeederWorksForVector)
Function Documentation
TEST() [1/13]
TEST (NonsecureURBGBase , CompatibleWithDistributionUtils)
Definition at line 146 of file nonsecure_base_test.cc.
{
  ExampleNonsecureURBG rbg;
  absl::Uniform(rbg, 0, 100);
  absl::Uniform(rbg, 0.5, 0.7);
  absl::Poisson<uint32_t>(rbg);
  absl::Exponential<float>(rbg);
}
References absl::Exponential(), absl::Poisson(), and absl::Uniform().
TEST() [2/13]
TEST (NonsecureURBGBase , CompatibleWithStdDistributions)
Definition at line 155 of file nonsecure_base_test.cc.
{
  ExampleNonsecureURBG rbg;
  // Cast to void to suppress [[nodiscard]] warnings
  static_cast<void>(std::uniform_int_distribution<uint32_t>(0, 100)(rbg));
  static_cast<void>(std::uniform_real_distribution<float>()(rbg));
  static_cast<void>(std::bernoulli_distribution(0.2)(rbg));
}
TEST() [3/13]
TEST (NonsecureURBGBase , ConsecutiveDefaultInstancesYieldUniqueVariates)
Definition at line 164 of file nonsecure_base_test.cc.
{
  const size_t kNumSamples = 128;
  ExampleNonsecureURBG rbg1;
  ExampleNonsecureURBG rbg2;
  for (size_t i = 0; i < kNumSamples; i++) {
    EXPECT_NE(rbg1(), rbg2());
  }
}
References i.
TEST() [4/13]
TEST (NonsecureURBGBase , DefaultConstructorIsValid)
Definition at line 39 of file nonsecure_base_test.cc.
{
  ExampleNonsecureURBG urbg;
}
TEST() [5/13]
TEST (NonsecureURBGBase , EqualSeedSequencesYieldEqualVariates)
Definition at line 175 of file nonsecure_base_test.cc.
{
  std::seed_seq seq;
  ExampleNonsecureURBG rbg1(seq);
  ExampleNonsecureURBG rbg2(seq);
  // ExampleNonsecureURBG rbg3({1, 2, 3});  // Should not compile.
  for (uint32_t i = 0; i < 1000; i++) {
    EXPECT_EQ(rbg1(), rbg2());
  }
  rbg1.discard(100);
  rbg2.discard(100);
  // The sequences should continue after discarding
  for (uint32_t i = 0; i < 1000; i++) {
    EXPECT_EQ(rbg1(), rbg2());
  }
}
References i.
TEST() [6/13]
TEST (NonsecureURBGBase , SeedSeqConstructorIsValid)
Definition at line 141 of file nonsecure_base_test.cc.
{
  std::seed_seq seq;
  ExampleNonsecureURBG rbg(seq);
}
TEST() [7/13]
TEST (NonsecureURBGBase , StandardInterface)
Definition at line 57 of file nonsecure_base_test.cc.
{
  // Names after definition of [rand.req.urbg] in C++ standard.
  // e us a value of E
  // v is a lvalue of E
  // x, y are possibly const values of E
  // s is a value of T
  // q is a value satisfying requirements of seed_sequence
  // z is a value of type unsigned long long
  // os is a some specialization of basic_ostream
  // is is a some specialization of basic_istream
  using E = absl::random_internal::NonsecureURBGBase<std::minstd_rand>;
  using T = typename E::result_type;
  static_assert(!std::is_copy_constructible<E>::value,
                "NonsecureURBGBase should not be copy constructible");
  static_assert(!absl::is_copy_assignable<E>::value,
                "NonsecureURBGBase should not be copy assignable");
  static_assert(std::is_move_constructible<E>::value,
                "NonsecureURBGBase should be move constructible");
  static_assert(absl::is_move_assignable<E>::value,
                "NonsecureURBGBase should be move assignable");
  static_assert(std::is_same<decltype(std::declval<E>()()), T>::value,
                "return type of operator() must be result_type");
  {
    const E x, y;
    Use(x);
    Use(y);
    static_assert(std::is_same<decltype(x == y), bool>::value,
                  "return type of operator== must be bool");
    static_assert(std::is_same<decltype(x != y), bool>::value,
                  "return type of operator== must be bool");
  }
  E e;
  std::seed_seq q{1, 2, 3};
  E{};
  E{q};
  // Copy constructor not supported.
  // E{x};
  // result_type seed constructor not supported.
  // E{T{1}};
  // Move constructors are supported.
  {
    E tmp(q);
    E m = std::move(tmp);
    E n(std::move(m));
    EXPECT_TRUE(e != n);
  }
  // Comparisons work.
  {
    // MSVC emits error 2718 when using EXPECT_EQ(e, x)
    //  * actual parameter with __declspec(align('#')) won't be aligned
    E a(q);
    E b(q);
    EXPECT_TRUE(a != e);
    EXPECT_TRUE(a == b);
    a();
    EXPECT_TRUE(a != b);
  }
  // e.seed(s) not supported.
  // [rand.req.eng] specifies the parameter as 'unsigned long long'
  // e.discard(unsigned long long) is supported.
  unsigned long long z = 1;  // NOLINT(runtime/int)
  e.discard(z);
}
References a, b, n, Use(), value, x, and y.
TEST() [8/13]
TEST (RandenPoolSeedSeqTest , SeederWorksForS32)
Definition at line 213 of file nonsecure_base_test.cc.
{
  absl::random_internal::RandenPoolSeedSeq seeder;
  int32_t state[2] = {0, 0};
  seeder.generate(std::begin(state), std::end(state));
  EXPECT_FALSE(state[0] == 0 && state[1] == 0);
}
References absl::random_internal::RandenPoolSeedSeq::generate(), and state.
TEST() [9/13]
TEST (RandenPoolSeedSeqTest , SeederWorksForU32)
Definition at line 196 of file nonsecure_base_test.cc.
{
  absl::random_internal::RandenPoolSeedSeq seeder;
  uint32_t state[2] = {0, 0};
  seeder.generate(std::begin(state), std::end(state));
  EXPECT_FALSE(state[0] == 0 && state[1] == 0);
}
References absl::random_internal::RandenPoolSeedSeq::generate(), and state.
TEST() [10/13]
TEST (RandenPoolSeedSeqTest , SeederWorksForU64)
Definition at line 204 of file nonsecure_base_test.cc.
{
  absl::random_internal::RandenPoolSeedSeq seeder;
  uint64_t state[2] = {0, 0};
  seeder.generate(std::begin(state), std::end(state));
  EXPECT_FALSE(state[0] == 0 && state[1] == 0);
  EXPECT_FALSE((state[0] >> 32) == 0 && (state[1] >> 32) == 0);
}
References absl::random_internal::RandenPoolSeedSeq::generate(), and state.
TEST() [11/13]
TEST (RandenPoolSeedSeqTest , SeederWorksForVector)
Definition at line 221 of file nonsecure_base_test.cc.
{
  absl::random_internal::RandenPoolSeedSeq seeder;
  std::vector<uint32_t> state(2);
  seeder.generate(std::begin(state), std::end(state));
  EXPECT_FALSE(state[0] == 0 && state[1] == 0);
}
References absl::random_internal::RandenPoolSeedSeq::generate(), and state.
TEST() [12/13]
TEST (RecommendedTemplates , CanBeConstructed)
Definition at line 44 of file nonsecure_base_test.cc.
{
  absl::BitGen default_generator;
  absl::InsecureBitGen insecure_generator;
}
TEST() [13/13]
TEST (RecommendedTemplates , CanDiscardValues)
Definition at line 49 of file nonsecure_base_test.cc.
{
  absl::BitGen default_generator;
  absl::InsecureBitGen insecure_generator;
  default_generator.discard(5);
  insecure_generator.discard(5);
}
References absl::random_internal::NonsecureURBGBase< URBG, Seeder >::discard().