open spiel: open_spiel/abseil-cpp/absl/synchronization/internal/per_thread_sem.cc File Reference
per_thread_sem.cc File Reference
#include "absl/base/internal/low_level_alloc.h"
#include "absl/synchronization/internal/per_thread_sem.h"
#include <atomic>
#include "absl/base/attributes.h"
#include "absl/base/internal/thread_identity.h"
#include "absl/synchronization/internal/waiter.h"
Namespaces
namespace absl
namespace absl::synchronization_internal
Functions
ABSL_ATTRIBUTE_WEAK void ABSL_INTERNAL_C_SYMBOL AbslInternalPerThreadSemPost (absl::base_internal::ThreadIdentity *identity)
ABSL_ATTRIBUTE_WEAK bool ABSL_INTERNAL_C_SYMBOL AbslInternalPerThreadSemWait (absl::synchronization_internal::KernelTimeout t)
Function Documentation
AbslInternalPerThreadSemPost()
ABSL_ATTRIBUTE_WEAK void ABSL_INTERNAL_C_SYMBOL AbslInternalPerThreadSemPost (absl::base_internal::ThreadIdentity * identity)
Definition at line 67 of file per_thread_sem.cc.
{
  absl::synchronization_internal::Waiter::GetWaiter(identity)->Post();
}
References absl::synchronization_internal::Waiter::GetWaiter(), and absl::synchronization_internal::Waiter::Post().
AbslInternalPerThreadSemWait()
ABSL_ATTRIBUTE_WEAK bool ABSL_INTERNAL_C_SYMBOL AbslInternalPerThreadSemWait (absl::synchronization_internal::KernelTimeout t)
Definition at line 72 of file per_thread_sem.cc.
{
  bool timeout = false;
  absl::base_internal::ThreadIdentity *identity;
  identity = absl::synchronization_internal::GetOrCreateCurrentThreadIdentity();
  // Ensure wait_start != 0.
  int ticker = identity->ticker.load(std::memory_order_relaxed);
  identity->wait_start.store(ticker ? ticker : 1, std::memory_order_relaxed);
  identity->is_idle.store(false, std::memory_order_relaxed);
  if (identity->blocked_count_ptr != nullptr) {
    // Increment count of threads blocked in a given thread pool.
    identity->blocked_count_ptr->fetch_add(1, std::memory_order_relaxed);
  }
  timeout =
      !absl::synchronization_internal::Waiter::GetWaiter(identity)->Wait(t);
  if (identity->blocked_count_ptr != nullptr) {
    identity->blocked_count_ptr->fetch_sub(1, std::memory_order_relaxed);
  }
  identity->is_idle.store(false, std::memory_order_relaxed);
  identity->wait_start.store(0, std::memory_order_relaxed);
  return !timeout;
}
References absl::base_internal::ThreadIdentity::blocked_count_ptr, absl::synchronization_internal::GetOrCreateCurrentThreadIdentity(), absl::synchronization_internal::Waiter::GetWaiter(), absl::base_internal::ThreadIdentity::is_idle, absl::base_internal::ThreadIdentity::ticker, absl::synchronization_internal::Waiter::Wait(), and absl::base_internal::ThreadIdentity::wait_start.