open spiel: open_spiel/games/bridge/double_dummy_solver/test/print.cpp File Reference
print.cpp File Reference
#include <iostream>
#include <iomanip>
#include <algorithm>
#include "print.h"
#include "cst.h"
Functions
string equals_to_string (const int equals)
void set_constants ()
void print_PBN (const dealPBN &dl)
void print_FUT (const futureTricks &fut)
void print_TABLE (const ddTableResults &table)
void print_PAR (const parResults &par)
void print_DEALERPAR (const parResultsDealer &par)
void print_PLAY (const playTracePBN &play)
void print_TRACE (const solvedPlay &solved)
void print_double_TRACE (const solvedPlay &solved, const solvedPlay &ref)
Function Documentation
equals_to_string()
string equals_to_string (const int equals)
Definition at line 96 of file print.cpp.
{
  string st = "";
  for (unsigned i = 15; i >= 2; i--)
  {
    if (equals & dbitMapRank[i])
      st += static_cast<char>(dcardRank[i]);
  }
  return (st == "" ? "-" : st);
}
References dbitMapRank, dcardRank, and i.
Referenced by print_FUT().
print_DEALERPAR()
void print_DEALERPAR (const parResultsDealer & par)
Definition at line 142 of file print.cpp.
{
  cout << setw(6) << left << "Score" << par.score << "\n";
  cout << setw(6) << left << "Pars" << par.number << "\n";
  for (int i = 0; i < par.number; i++)
    cout << left << "Par " << setw(2) << i << par.contracts[i] << "\n";
}
References parResultsDealer::contracts, i, parResultsDealer::number, and parResultsDealer::score.
Referenced by loop_dealerpar().
print_double_TRACE()
void print_double_TRACE (const solvedPlay & solved, const solvedPlay & ref)
Definition at line 174 of file print.cpp.
{
  cout << "Number solved vs ref: " << solved.number << " vs. " <<
    ref.number << "\n";
  const int m = min(solved.number, ref.number);
  for (int i = 0; i < m; i++)
  {
    cout << "Trick " << i << ": " <<
      solved.tricks[i] << " vs " <<
      ref.tricks[i] <<
      (solved.tricks[i] == ref.tricks[i] ? "" : " ERROR") << "\n";
  }
  if (solved.number > m)
  {
    for (int i = m; i < solved.number; i++)
      cout << "Solved " << i << ": " << solved.tricks[i] << "\n";
  }
  else if (ref.number > m)
  {
    for (int i = m; i < ref.number; i++)
      cout << "Ref    " << i << ": " << ref.tricks[i] << "\n";
  }
}
References i, solvedPlay::number, and solvedPlay::tricks.
Referenced by loop_play().
print_FUT()
void print_FUT (const futureTricks & fut)
Definition at line 76 of file print.cpp.
{
  cout << setw(6) << left << "cards" << fut.cards << "\n";
  cout << setw(6) << right <<  "No." <<
    setw(7) << "suit" <<
    setw(7) << "rank" <<
    setw(7) << "equals" <<
    setw(7) << "score" << "\n";
  for (int i = 0; i < fut.cards; i++)
  {
    cout << setw(6) << right << i <<
      setw(7) << dcardSuit[ fut.suit[i] ] <<
      setw(7) << dcardRank[ fut.rank[i] ] <<
      setw(7) << equals_to_string(fut.equals[i]) <<
      setw(7) << fut.score[i] << "\n";
  }
}
References futureTricks::cards, dcardRank, dcardSuit, futureTricks::equals, equals_to_string(), i, futureTricks::rank, futureTricks::score, and futureTricks::suit.
Referenced by loop_solve().
print_PAR()
void print_PAR (const parResults & par)
Definition at line 133 of file print.cpp.
{
  cout << setw(9) << left << "NS score" << par.parScore[0] << "\n";
  cout << setw(9) << "EW score" << par.parScore[1] << "\n";
  cout << setw(9) << "NS list" << par.parContractsString[0] << "\n";
  cout << setw(9) << "EW list" << par.parContractsString[1] << "\n";
}
References parResults::parContractsString, and parResults::parScore.
Referenced by loop_par().
print_PBN()
void print_PBN (const dealPBN & dl)
Definition at line 68 of file print.cpp.
{
  cout << setw(10) << left << "trump" << dl.trump << "\n";
  cout << setw(10) << "first" << dl.first << "\n";
  cout << setw(10) << "cards" << dl.remainCards << "\n";
}
References dealPBN::first, dealPBN::remainCards, and dealPBN::trump.
print_PLAY()
void print_PLAY (const playTracePBN & play)
Definition at line 152 of file print.cpp.
{
  cout << setw(6) << right << "Number" <<
    setw(5) << play.number << "\n";
  for (int i = 0; i < play.number; i++)
     cout << setw(6) << i <<  "   " <<
       play.cards[2*i] << play.cards[2*i+1] << "\n";
}
References i, and play.
print_TABLE()
void print_TABLE (const ddTableResults & table)
Definition at line 108 of file print.cpp.
{
  cout << setw(5) << right << "" <<
    setw(6) << "North" <<
    setw(6) << "South" <<
    setw(6) << "East" <<
    setw(6) << "West" << "\n";
  cout << setw(5) << right << "NT" <<
    setw(6) << table.resTable[4][0] <<
    setw(6) << table.resTable[4][2] <<
    setw(6) << table.resTable[4][1] <<
    setw(6) << table.resTable[4][3] << "\n";
  for (int suit = 0; suit <= 3; suit++)
  {
    cout << setw(5) << right << dcardSuit[suit] <<
      setw(6) << table.resTable[suit][0] <<
      setw(6) << table.resTable[suit][2] <<
      setw(6) << table.resTable[suit][1] <<
      setw(6) << table.resTable[suit][3] << "\n";
  }
}
References dcardSuit, and ddTableResults::resTable.
Referenced by loop_calc().
print_TRACE()
void print_TRACE (const solvedPlay & solved)
Definition at line 163 of file print.cpp.
{
  cout << setw(6) << right << "Number" <<
    setw(5) << solved.number << "\n";
  for (int i = 0; i < solved.number; i++)
     cout << setw(6) << i <<
       setw(5) << solved.tricks[i] << "\n";
}
References i.
set_constants()
void set_constants ()
Definition at line 26 of file print.cpp.
{
  dbitMapRank[15] = 0x2000;
  dbitMapRank[14] = 0x1000;
  dbitMapRank[13] = 0x0800;
  dbitMapRank[12] = 0x0400;
  dbitMapRank[11] = 0x0200;
  dbitMapRank[10] = 0x0100;
  dbitMapRank[ 9] = 0x0080;
  dbitMapRank[ 8] = 0x0040;
  dbitMapRank[ 7] = 0x0020;
  dbitMapRank[ 6] = 0x0010;
  dbitMapRank[ 5] = 0x0008;
  dbitMapRank[ 4] = 0x0004;
  dbitMapRank[ 3] = 0x0002;
  dbitMapRank[ 2] = 0x0001;
  dbitMapRank[ 1] = 0;
  dbitMapRank[ 0] = 0;
  dcardRank[ 2] = '2';
  dcardRank[ 3] = '3';
  dcardRank[ 4] = '4';
  dcardRank[ 5] = '5';
  dcardRank[ 6] = '6';
  dcardRank[ 7] = '7';
  dcardRank[ 8] = '8';
  dcardRank[ 9] = '9';
  dcardRank[10] = 'T';
  dcardRank[11] = 'J';
  dcardRank[12] = 'Q';
  dcardRank[13] = 'K';
  dcardRank[14] = 'A';
  dcardRank[15] = '-';
  dcardSuit[0] = 'S';
  dcardSuit[1] = 'H';
  dcardSuit[2] = 'D';
  dcardSuit[3] = 'C';
  dcardSuit[4] = 'N';
}
References dbitMapRank, dcardRank, and dcardSuit.
Referenced by realMain().