open spiel: open_spiel/bots/uci/random_uci_bot.cc File Reference
random_uci_bot.cc File Reference
#include <iostream>
#include <memory>
#include <random>
#include "open_spiel/abseil-cpp/absl/flags/flag.h"
#include "open_spiel/abseil-cpp/absl/flags/parse.h"
#include "open_spiel/abseil-cpp/absl/random/distributions.h"
#include "open_spiel/abseil-cpp/absl/strings/match.h"
#include "open_spiel/abseil-cpp/absl/strings/str_split.h"
#include "open_spiel/games/chess/chess.h"
#include "open_spiel/spiel.h"
#include "open_spiel/spiel_utils.h"
#include "open_spiel/utils/init.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
namespace open_spiel::uci
Functions
ABSL_FLAG (int, seed, 0, "The seed to use.")
void open_spiel::uci::RandomUciBot ()
int main (int argc, char **argv)
Function Documentation
ABSL_FLAG()
ABSL_FLAG (int , seed , 0 , "The seed to use.")
main()
int main (int argc, char ** argv)
Definition at line 94 of file random_uci_bot.cc.
{
  open_spiel::Init("", &argc, &argv, false);
  absl::ParseCommandLine(argc, argv);
  open_spiel::uci::RandomUciBot();
}
References open_spiel::Init(), absl::ParseCommandLine(), and open_spiel::uci::RandomUciBot().