open spiel: open_spiel/abseil-cpp/absl/container/internal/raw_hash_set_allocator_test.cc File Reference
raw_hash_set_allocator_test.cc File Reference
#include <limits>
#include <scoped_allocator>
#include "gtest/gtest.h"
#include "absl/container/internal/raw_hash_set.h"
#include "absl/container/internal/tracked.h"
Namespaces
namespace absl
namespace absl::container_internal
Variable Documentation
a1
Alloc a1 = Alloc(1)
Definition at line 184 of file raw_hash_set_allocator_test.cc.
a2
Alloc a2 = Alloc(2)
Definition at line 186 of file raw_hash_set_allocator_test.cc.
num_allocs
size_t num_allocs = 0
Definition at line 34 of file raw_hash_set_allocator_test.cc.
owned
std::set<void*> owned
Definition at line 35 of file raw_hash_set_allocator_test.cc.
Referenced by absl::cord_internal::CordRepBtree::AddEdge(), and absl::cord_internal::CordRepBtree::SetEdge().
t1
Table t1 = Table(0, a1)
Definition at line 185 of file raw_hash_set_allocator_test.cc.
Referenced by absl::time_internal::cctz::TimeZoneLibC::MakeTime(), absl::ABSL_NAMESPACE_BEGIN::ParseAs(), SideSeats(), SidesParBin(), absl::ABSL_NAMESPACE_BEGIN::TestIntegral(), and absl::ABSL_NAMESPACE_BEGIN::TestMarshall().