open spiel: open_spiel/rust/src/rust_open_spiel.cc File Reference
rust_open_spiel.cc File Reference
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <memory>
#include <string>
#include "open_spiel/abseil-cpp/absl/algorithm/container.h"
#include "open_spiel/game_parameters.h"
#include "open_spiel/spiel.h"
#include "open_spiel/spiel_bots.h"
Functions
void * NewGameParameters ()
void DeleteGameParameters (void *params_ptr)
void GameParametersSetInt (void *params_ptr, const char *key, int value)
void GameParametersSetDouble (void *params_ptr, const char *key, double value)
void GameParametersSetString (void *params_ptr, const char *key, const char *value)
char * GameParametersSerialize (const void *params_ptr, unsigned long *length)
void * LoadGame (const char *name)
void * LoadGameFromParameters (const void *params_ptr)
void DeleteGame (void *game_ptr)
char * GameShortName (const void *game_ptr, unsigned long *length)
char * GameLongName (const void *game_ptr, unsigned long *length)
void * GameNewInitialState (const void *game_ptr)
int GameNumPlayers (const void *game_ptr)
int GameMaxGameLength (const void *game_ptr)
int GameNumDistinctActions (const void *game_ptr)
int * GameObservationTensorShape (const void *game_ptr, int *size)
int * GameInformationStateTensorShape (const void *game_ptr, int *size)
void DeleteState (void *state_ptr)
void * StateClone (const void *state_ptr)
char * StateToString (const void *state_ptr, unsigned long *length)
long * StateLegalActions (const void *state_ptr, int *num_legal_actions)
int StateCurrentPlayer (const void *state_ptr)
char * StateActionToString (const void *state_ptr, int player, int action, unsigned long *length)
int StateIsTerminal (const void *state_ptr)
int StateIsChanceNode (const void *state_ptr)
void StateApplyAction (void *state_ptr, long action)
double StatePlayerReturn (const void *state_ptr, int player)
int StateNumPlayers (const void *state_ptr)
void StateReturns (const void *state_ptr, double *returns_buf)
double * StateChanceOutcomeProbs (const void *state_ptr, int *size)
char * StateObservationString (const void *state_ptr, unsigned long *length)
char * StateInformationStateString (const void *state_ptr, unsigned long *length)
int StateInformationStateTensorSize (const void *state_ptr)
int StateObservationTensorSize (const void *state_ptr)
void StateObservationTensor (const void *state_ptr, int player, float *obs_buf, int length)
void StateInformationStateTensor (const void *state_ptr, int player, float *infostate_buf, int length)
void DeleteBot (void *bot_ptr)
long BotStep (void *bot_ptr, const void *state_ptr)
void BotInformAction (void *bot_ptr, const void *state_ptr, int player_id, long action)
void BotRestart (void *bot_ptr)
void * BotRegistererCreateByName (const char *bot_name_ptr, const void *game_ptr, int player_id, const void *params_ptr)
Function Documentation
BotInformAction()
void BotInformAction (void * bot_ptr, const void * state_ptr, int player_id, long action)
Definition at line 311 of file rust_open_spiel.cc.
                                  { /* NOLINT */
  Bot* bot = reinterpret_cast<Bot*>(bot_ptr);
  const State* state = reinterpret_cast<const State*>(state_ptr);
  bot->InformAction(*state, player_id, action);
}
References action, and state.
BotRegistererCreateByName()
void * BotRegistererCreateByName (const char * bot_name_ptr, const void * game_ptr, int player_id, const void * params_ptr)
Definition at line 324 of file rust_open_spiel.cc.
{
  const std::string bot_name(bot_name_ptr);
  const GamePointerHolder* game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr);
  const GameParameters* params =
      reinterpret_cast<const GameParameters*>(params_ptr);
  std::unique_ptr<Bot> bot =
      BotRegisterer::CreateByName(bot_name, game->ptr, player_id, *params);
  return reinterpret_cast<void*>(bot.release());
}
BotRestart()
void BotRestart (void * bot_ptr)
Definition at line 318 of file rust_open_spiel.cc.
{
  Bot* bot = reinterpret_cast<Bot*>(bot_ptr);
  bot->Restart();
}
BotStep()
long BotStep (void * bot_ptr, const void * state_ptr)
Definition at line 305 of file rust_open_spiel.cc.
                                                   { /* NOLINT */
  Bot* bot = reinterpret_cast<Bot*>(bot_ptr);
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return bot->Step(*state);
}
References state.
DeleteBot()
void DeleteBot (void * bot_ptr)
Definition at line 300 of file rust_open_spiel.cc.
{
  Bot* bot = reinterpret_cast<Bot*>(bot_ptr);
  delete bot;
}
DeleteGame()
void DeleteGame (void * game_ptr)
Definition at line 115 of file rust_open_spiel.cc.
{
  GamePointerHolder* game = reinterpret_cast<GamePointerHolder*>(game_ptr);
  delete game;
}
DeleteGameParameters()
void DeleteGameParameters (void * params_ptr)
Definition at line 72 of file rust_open_spiel.cc.
{
  GameParameters* params = reinterpret_cast<GameParameters*>(params_ptr);
  delete params;
}
DeleteState()
void DeleteState (void * state_ptr)
Definition at line 177 of file rust_open_spiel.cc.
{
  State* state = reinterpret_cast<State*>(state_ptr);
  delete state;
}
References state.
GameInformationStateTensorShape()
int * GameInformationStateTensorShape (const void * game_ptr, int * size)
Definition at line 169 of file rust_open_spiel.cc.
{
  const Game* game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr.get();
  std::vector<int> shape = game->InformationStateTensorShape();
  return AllocBuf(shape, size);
}
References ptr, and size.
GameLongName()
char * GameLongName (const void * game_ptr, unsigned long * length)
Definition at line 128 of file rust_open_spiel.cc.
                                                                {  // NOLINT
  const Game* game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr.get();
  std::string long_name = game->GetType().long_name;
  *length = long_name.length();
  return AllocAndCopyString(long_name);
}
References ptr.
GameMaxGameLength()
int GameMaxGameLength (const void * game_ptr)
Definition at line 150 of file rust_open_spiel.cc.
{
  const Game* game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr.get();
  return game->MaxGameLength();
}
References ptr.
GameNewInitialState()
void * GameNewInitialState (const void * game_ptr)
Definition at line 136 of file rust_open_spiel.cc.
{
  const Game* game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr.get();
  std::unique_ptr<State> state = game->NewInitialState();
  void* state_ptr = reinterpret_cast<void*>(state.release());
  return state_ptr;
}
References ptr, and state.
GameNumDistinctActions()
int GameNumDistinctActions (const void * game_ptr)
Definition at line 156 of file rust_open_spiel.cc.
{
  const Game* game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr.get();
  return game->NumDistinctActions();
}
References ptr.
GameNumPlayers()
int GameNumPlayers (const void * game_ptr)
Definition at line 144 of file rust_open_spiel.cc.
{
  const Game* game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr.get();
  return game->NumPlayers();
}
References ptr.
GameObservationTensorShape()
int * GameObservationTensorShape (const void * game_ptr, int * size)
Definition at line 162 of file rust_open_spiel.cc.
{
  const Game* game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr.get();
  std::vector<int> shape = game->ObservationTensorShape();
  return AllocBuf(shape, size);
}
References ptr, and size.
GameParametersSerialize()
char * GameParametersSerialize (const void * params_ptr, unsigned long * length)
Definition at line 93 of file rust_open_spiel.cc.
                                                     {  // NOLINT
  const GameParameters* params =
      reinterpret_cast<const GameParameters*>(params_ptr);
  std::string serialized = SerializeGameParameters(*params);
  *length = serialized.length();
  return AllocAndCopyString(serialized);
}
GameParametersSetDouble()
void GameParametersSetDouble (void * params_ptr, const char * key, double value)
Definition at line 82 of file rust_open_spiel.cc.
{
  GameParameters* params = reinterpret_cast<GameParameters*>(params_ptr);
  params->insert_or_assign(std::string(key), GameParameter(value));
}
References key.
GameParametersSetInt()
void GameParametersSetInt (void * params_ptr, const char * key, int value)
Definition at line 77 of file rust_open_spiel.cc.
{
  GameParameters* params = reinterpret_cast<GameParameters*>(params_ptr);
  params->insert_or_assign(std::string(key), GameParameter(value));
}
References key.
GameParametersSetString()
void GameParametersSetString (void * params_ptr, const char * key, const char * value)
Definition at line 87 of file rust_open_spiel.cc.
{
  GameParameters* params = reinterpret_cast<GameParameters*>(params_ptr);
  params->insert_or_assign(std::string(key), GameParameter(std::string(value)));
}
References key.
GameShortName()
char * GameShortName (const void * game_ptr, unsigned long * length)
Definition at line 120 of file rust_open_spiel.cc.
                                                                 {  // NOLINT
  const Game* game =
      reinterpret_cast<const GamePointerHolder*>(game_ptr)->ptr.get();
  std::string short_name = game->GetType().short_name;
  *length = short_name.length();
  return AllocAndCopyString(short_name);
}
References ptr.
LoadGame()
void * LoadGame (const char * name)
Definition at line 103 of file rust_open_spiel.cc.
{
  return reinterpret_cast<void*>(
      new GamePointerHolder{open_spiel::LoadGame(name)});
}
References open_spiel::LoadGame(), and name.
LoadGameFromParameters()
void * LoadGameFromParameters (const void * params_ptr)
Definition at line 108 of file rust_open_spiel.cc.
{
  const GameParameters* params =
      reinterpret_cast<const GameParameters*>(params_ptr);
  return reinterpret_cast<void*>(
      new GamePointerHolder{open_spiel::LoadGame(*params)});
}
References open_spiel::LoadGame().
NewGameParameters()
void * NewGameParameters ()
Definition at line 68 of file rust_open_spiel.cc.
{
  return reinterpret_cast<void*>(new GameParameters());
}
StateActionToString()
char * StateActionToString (const void * state_ptr, int player, int action, unsigned long * length)
Definition at line 208 of file rust_open_spiel.cc.
                                                 {  // NOLINT
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::string action_str = state->ActionToString(player, action);
  *length = action_str.length();
  return AllocAndCopyString(action_str);
}
References action, player, and state.
StateApplyAction()
void StateApplyAction (void * state_ptr, long action)
Definition at line 226 of file rust_open_spiel.cc.
                                                    {  // NOLINT
  State* state = reinterpret_cast<State*>(state_ptr);
  state->ApplyAction(action);
}
References action, and state.
StateChanceOutcomeProbs()
double * StateChanceOutcomeProbs (const void * state_ptr, int * size)
Definition at line 247 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  ActionsAndProbs chance_outcomes = state->ChanceOutcomes();
  *size = chance_outcomes.size();
  size_t num_bytes = *size * sizeof(double);
  double* buf = static_cast<double*>(malloc(num_bytes));
  for (int i = 0; i < chance_outcomes.size(); ++i) {
    buf[i] = chance_outcomes[i].second;
  }
  return buf;
}
References buf, i, size, and state.
StateClone()
void * StateClone (const void * state_ptr)
Definition at line 182 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::unique_ptr<State> state_copy = state->Clone();
  return reinterpret_cast<void*>(state_copy.release());
}
References state.
StateCurrentPlayer()
int StateCurrentPlayer (const void * state_ptr)
Definition at line 203 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->CurrentPlayer();
}
References state.
StateInformationStateString()
char * StateInformationStateString (const void * state_ptr, unsigned long * length)
Definition at line 267 of file rust_open_spiel.cc.
                                                         {  // NOLINT
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::string infostate_str = state->InformationStateString();
  *length = infostate_str.length();
  return AllocAndCopyString(infostate_str);
}
References state.
StateInformationStateTensor()
void StateInformationStateTensor (const void * state_ptr, int player, float * infostate_buf, int length)
Definition at line 293 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  state->InformationStateTensor(player, absl::MakeSpan(infostate_buf, length));
}
References absl::MakeSpan(), player, and state.
StateInformationStateTensorSize()
int StateInformationStateTensorSize (const void * state_ptr)
Definition at line 275 of file rust_open_spiel.cc.
{
  const Game* parent_game =
      reinterpret_cast<const State*>(state_ptr)->GetGame().get();
  return parent_game->InformationStateTensorSize();
}
StateIsChanceNode()
int StateIsChanceNode (const void * state_ptr)
Definition at line 221 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->IsChanceNode() ? 1 : 0;
}
References state.
StateIsTerminal()
int StateIsTerminal (const void * state_ptr)
Definition at line 216 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->IsTerminal() ? 1 : 0;
}
References state.
StateLegalActions()
long * StateLegalActions (const void * state_ptr, int * num_legal_actions)
Definition at line 195 of file rust_open_spiel.cc.
{
  assert(sizeof(long) == sizeof(Action));  // NOLINT
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::vector<Action> legal_actions = state->LegalActions();
  return AllocBuf(legal_actions, num_legal_actions);
}
References state.
StateNumPlayers()
int StateNumPlayers (const void * state_ptr)
Definition at line 236 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->NumPlayers();
}
References state.
StateObservationString()
char * StateObservationString (const void * state_ptr, unsigned long * length)
Definition at line 259 of file rust_open_spiel.cc.
                                                    {  // NOLINT
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::string obs_str = state->ObservationString();
  *length = obs_str.length();
  return AllocAndCopyString(obs_str);
}
References state.
StateObservationTensor()
void StateObservationTensor (const void * state_ptr, int player, float * obs_buf, int length)
Definition at line 287 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  state->ObservationTensor(player, absl::MakeSpan(obs_buf, length));
}
References absl::MakeSpan(), player, and state.
StateObservationTensorSize()
int StateObservationTensorSize (const void * state_ptr)
Definition at line 281 of file rust_open_spiel.cc.
{
  const Game* parent_game =
      reinterpret_cast<const State*>(state_ptr)->GetGame().get();
  return parent_game->ObservationTensorSize();
}
StatePlayerReturn()
double StatePlayerReturn (const void * state_ptr, int player)
Definition at line 231 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  return state->PlayerReturn(player);
}
References player, and state.
StateReturns()
void StateReturns (const void * state_ptr, double * returns_buf)
Definition at line 241 of file rust_open_spiel.cc.
{
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::vector<double> returns = state->Returns();
  memcpy(returns_buf, returns.data(), returns.size() * sizeof(double));
}
References state.
StateToString()
char * StateToString (const void * state_ptr, unsigned long * length)
Definition at line 188 of file rust_open_spiel.cc.
                                                                  {  // NOLINT
  const State* state = reinterpret_cast<const State*>(state_ptr);
  std::string state_str = state->ToString();
  *length = state_str.length();
  return AllocAndCopyString(state_str);
}
References state.