open spiel: open_spiel/games/bridge/double_dummy_solver/src/SolveBoard.cpp File Reference
SolveBoard.cpp File Reference
#include "SolverIF.h"
#include "SolveBoard.h"
#include "System.h"
#include "Memory.h"
#include "Scheduler.h"
#include "PBN.h"
#include "debug.h"
Functions
int SolveAllBoardsN (boards &bds, solvedBoards &solved)
bool SameBoard (const boards &bds, const unsigned index1, const unsigned index2)
void SolveSingleCommon (const int thrId, const int bno)
void CopySolveSingle (const vector< int > &crossrefs)
void SolveChunkCommon (const int thrId)
int STDCALL SolveBoardPBN (dealPBN dlpbn, int target, int solutions, int mode, futureTricks *futp, int thrId)
int STDCALL SolveAllBoards (boardsPBN *bop, solvedBoards *solvedp)
int STDCALL SolveAllChunksPBN (boardsPBN *bop, solvedBoards *solvedp, int chunkSize)
int STDCALL SolveAllChunks (boardsPBN *bop, solvedBoards *solvedp, int chunkSize)
int STDCALL SolveAllChunksBin (boards *bop, solvedBoards *solvedp, int chunkSize)
void DetectSolveDuplicates (const boards &bds, vector< int > &uniques, vector< int > &crossrefs)
Variables
paramType param
System sysdep
Memory memory
Scheduler scheduler
Function Documentation
CopySolveSingle()
void CopySolveSingle (const vector< int > & crossrefs)
Definition at line 59 of file SolveBoard.cpp.
{
  for (unsigned i = 0; i < crossrefs.size(); i++)
  {
    if (crossrefs[i] == -1)
      continue;
    START_THREAD_TIMER(thrId);
    param.solvedp->solvedBoard[i] =
      param.solvedp->solvedBoard[crossrefs[i]];
    END_THREAD_TIMER(thrId);
  }
}
References END_THREAD_TIMER, i, param, solvedBoards::solvedBoard, paramType::solvedp, and START_THREAD_TIMER.
Referenced by System::Reset().
DetectSolveDuplicates()
void DetectSolveDuplicates (const boards & bds, vector< int > & uniques, vector< int > & crossrefs)
Definition at line 246 of file SolveBoard.cpp.
{
  const unsigned nu = static_cast<unsigned>(bds.noOfBoards);
  uniques.clear();
  crossrefs.resize(nu);
  for (unsigned i = 0; i < nu; i++)
    crossrefs[i] = -1;
  for (unsigned i = 0; i < nu; i++)
  {
    if (crossrefs[i] != -1)
      continue;
    uniques.push_back(static_cast<int>(i));
    for (unsigned index = i+1; index < nu; index++)
    {
      if (SameBoard(bds, i, index))
        crossrefs[index] = static_cast<int>(i);
    }
  }
}
References i, boards::noOfBoards, and SameBoard().
Referenced by DetectCalcDuplicates(), and System::Reset().
SameBoard()
bool SameBoard (const boards & bds, const unsigned index1, const unsigned index2)
Definition at line 275 of file SolveBoard.cpp.
{
  for (int h = 0; h < DDS_HANDS; h++)
  {
    for (int s = 0; s < DDS_SUITS; s++)
    {
      if (bds.deals[index1].remainCards[h][s] !=
          bds.deals[index2].remainCards[h][s])
        return false;
    }
  }
  if (bds.mode[index1] != bds.mode[index2])
    return false;
  if (bds.solutions[index1] != bds.solutions[index2])
    return false;
  if (bds.target[index1] != bds.target[index2])
    return false;
  if (bds.deals[index1].first != bds.deals[index2].first)
    return false;
  if (bds.deals[index1].trump != bds.deals[index2].trump)
    return false;
  for (int k = 0; k < 3; k++)
  {
    if (bds.deals[index1].currentTrickSuit[k] !=
        bds.deals[index2].currentTrickSuit[k])
      return false;
    if (bds.deals[index1].currentTrickRank[k] !=
        bds.deals[index2].currentTrickRank[k])
      return false;
  }
  return true;
}
References deal::currentTrickRank, deal::currentTrickSuit, DDS_HANDS, DDS_SUITS, boards::deals, deal::first, boards::mode, deal::remainCards, boards::solutions, boards::target, and deal::trump.
Referenced by DetectSolveDuplicates().
SolveAllBoards()
int STDCALL SolveAllBoards (boardsPBN * bop, solvedBoards * solvedp)
Definition at line 174 of file SolveBoard.cpp.
{
  boards bo;
  bo.noOfBoards = bop->noOfBoards;
  if (bo.noOfBoards > MAXNOOFBOARDS)
    return RETURN_TOO_MANY_BOARDS;
  for (int k = 0; k < bop->noOfBoards; k++)
  {
    bo.mode[k] = bop->mode[k];
    bo.solutions[k] = bop->solutions[k];
    bo.target[k] = bop->target[k];
    bo.deals[k].first = bop->deals[k].first;
    bo.deals[k].trump = bop->deals[k].trump;
    for (int i = 0; i <= 2; i++)
    {
      bo.deals[k].currentTrickSuit[i] = bop->deals[k].currentTrickSuit[i];
      bo.deals[k].currentTrickRank[i] = bop->deals[k].currentTrickRank[i];
    }
    if (ConvertFromPBN(bop->deals[k].remainCards, bo.deals[k].remainCards)
        != 1)
      return RETURN_PBN_FAULT;
  }
  int res = SolveAllBoardsN(bo, * solvedp);
  return res;
}
References ConvertFromPBN(), deal::currentTrickRank, dealPBN::currentTrickRank, deal::currentTrickSuit, dealPBN::currentTrickSuit, boards::deals, boardsPBN::deals, deal::first, dealPBN::first, i, MAXNOOFBOARDS, boards::mode, boardsPBN::mode, boards::noOfBoards, boardsPBN::noOfBoards, deal::remainCards, dealPBN::remainCards, RETURN_PBN_FAULT, RETURN_TOO_MANY_BOARDS, boards::solutions, boardsPBN::solutions, SolveAllBoardsN(), boards::target, boardsPBN::target, deal::trump, and dealPBN::trump.
Referenced by main(), SolveAllChunks(), and SolveAllChunksPBN().
SolveAllBoardsN()
int SolveAllBoardsN (boards & bds, solvedBoards & solved)
Definition at line 110 of file SolveBoard.cpp.
{
  param.error = 0;
  if (bds.noOfBoards > MAXNOOFBOARDS)
    return RETURN_TOO_MANY_BOARDS;
  param.bop = &bds;
  param.solvedp = &solved;
  param.noOfBoards = bds.noOfBoards;
  scheduler.RegisterRun(DDS_RUN_SOLVE, bds);
  sysdep.RegisterRun(DDS_RUN_SOLVE, bds);
  for (int k = 0; k < MAXNOOFBOARDS; k++)
    solved.solvedBoard[k].cards = 0;
  START_BLOCK_TIMER;
  int retRun = sysdep.RunThreads();
  END_BLOCK_TIMER;
  if (retRun != RETURN_NO_FAULT)
    return retRun;
  solved.noOfBoards = param.noOfBoards;
#ifdef DDS_SCHEDULER
  scheduler.PrintTiming();
#endif
  if (param.error == 0)
    return RETURN_NO_FAULT;
  else
    return param.error;
}
References paramType::bop, DDS_RUN_SOLVE, END_BLOCK_TIMER, paramType::error, MAXNOOFBOARDS, boards::noOfBoards, paramType::noOfBoards, param, Scheduler::RegisterRun(), System::RegisterRun(), RETURN_NO_FAULT, RETURN_TOO_MANY_BOARDS, System::RunThreads(), scheduler, paramType::solvedp, START_BLOCK_TIMER, and sysdep.
Referenced by SolveAllBoards(), and SolveAllChunksBin().
SolveAllChunks()
int STDCALL SolveAllChunks (boardsPBN * bop, solvedBoards * solvedp, int chunkSize)
Definition at line 220 of file SolveBoard.cpp.
{
  // Historical aliases.  Don't use -- they may go away.
  if (chunkSize < 1)
    return RETURN_CHUNK_SIZE;
  return SolveAllBoards(bop, solvedp);
}
References RETURN_CHUNK_SIZE, and SolveAllBoards().
Referenced by loop_solve().
SolveAllChunksBin()
int STDCALL SolveAllChunksBin (boards * bop, solvedBoards * solvedp, int chunkSize)
Definition at line 233 of file SolveBoard.cpp.
{
  // Historical aliases.  Don't use -- they may go away.
  if (chunkSize < 1)
    return RETURN_CHUNK_SIZE;
  return SolveAllBoardsN(* bop, * solvedp);
}
References RETURN_CHUNK_SIZE, and SolveAllBoardsN().
SolveAllChunksPBN()
int STDCALL SolveAllChunksPBN (boardsPBN * bop, solvedBoards * solvedp, int chunkSize)
Definition at line 207 of file SolveBoard.cpp.
{
  // Historical aliases.  Don't use -- they may go away.
  if (chunkSize < 1)
    return RETURN_CHUNK_SIZE;
  return SolveAllBoards(bop, solvedp);
}
References RETURN_CHUNK_SIZE, and SolveAllBoards().
SolveBoardPBN()
int STDCALL SolveBoardPBN (dealPBN dlpbn, int target, int solutions, int mode, futureTricks * futp, int thrId)
Definition at line 149 of file SolveBoard.cpp.
{
  deal dl;
  if (ConvertFromPBN(dlpbn.remainCards, dl.remainCards) != RETURN_NO_FAULT)
    return RETURN_PBN_FAULT;
  for (int k = 0; k <= 2; k++)
  {
    dl.currentTrickRank[k] = dlpbn.currentTrickRank[k];
    dl.currentTrickSuit[k] = dlpbn.currentTrickSuit[k];
  }
  dl.first = dlpbn.first;
  dl.trump = dlpbn.trump;
  int res = SolveBoard(dl, target, solutions, mode, futp, thrId);
  return res;
}
References ConvertFromPBN(), deal::currentTrickRank, dealPBN::currentTrickRank, deal::currentTrickSuit, dealPBN::currentTrickSuit, deal::first, dealPBN::first, deal::remainCards, dealPBN::remainCards, RETURN_NO_FAULT, RETURN_PBN_FAULT, SolveBoard(), deal::trump, and dealPBN::trump.
Referenced by main().
SolveChunkCommon()
void SolveChunkCommon (const int thrId)
Definition at line 74 of file SolveBoard.cpp.
{
  int index;
  schedType st;
  while (1)
  {
    st = scheduler.GetNumber(thrId);
    index = st.number;
    if (index == -1)
      break;
    // This is not a perfect repeat detector, as the hands in
    // a group might have declarers N, S, N, N. Then the second
    // N would not reuse the first N. However, must reuses are
    // reasonably adjacent, and this is just an optimization anyway.
    if (st.repeatOf != -1 &&
        param.bop->deals[index ].first ==
        param.bop->deals[st.repeatOf].first)
    {
      START_THREAD_TIMER(thrId);
      param.solvedp->solvedBoard[index] =
        param.solvedp->solvedBoard[st.repeatOf];
      END_THREAD_TIMER(thrId);
      continue;
    }
    else
    {
      SolveSingleCommon(thrId, index);
    }
  }
}
References paramType::bop, boards::deals, END_THREAD_TIMER, deal::first, Scheduler::GetNumber(), schedType::number, param, schedType::repeatOf, scheduler, solvedBoards::solvedBoard, paramType::solvedp, SolveSingleCommon(), and START_THREAD_TIMER.
Referenced by System::Reset().
SolveSingleCommon()
void SolveSingleCommon (const int thrId, const int bno)
Definition at line 36 of file SolveBoard.cpp.
{
  futureTricks fut;
  START_THREAD_TIMER(thrId);
  int res = SolveBoard(
              param.bop->deals[bno],
              param.bop->target[bno],
              param.bop->solutions[bno],
              param.bop->mode[bno],
              &fut,
              thrId);
  END_THREAD_TIMER(thrId);
  if (res == 1)
    param.solvedp->solvedBoard[bno] = fut;
  else
    param.error = res;
}
References paramType::bop, boards::deals, END_THREAD_TIMER, paramType::error, boards::mode, param, boards::solutions, SolveBoard(), solvedBoards::solvedBoard, paramType::solvedp, START_THREAD_TIMER, and boards::target.
Referenced by System::Reset(), and SolveChunkCommon().
Variable Documentation
memory
Memory memory extern
Definition at line 22 of file Init.cpp.
param
paramType param
Definition at line 20 of file SolveBoard.cpp.
Referenced by CopySolveSingle(), absl::ABSL_NAMESPACE_BEGIN::CordRingBuildInputTest::CreateTestParams(), absl::ABSL_NAMESPACE_BEGIN::CordRingBuildTest::CreateTestParams(), absl::ABSL_NAMESPACE_BEGIN::CordRingSubTest::CreateTestParams(), absl::ABSL_NAMESPACE_BEGIN::MATCHER_P2(), absl::ABSL_NAMESPACE_BEGIN::MATCHER_P2(), absl::ABSL_NAMESPACE_BEGIN::MATCHER_P2(), absl::ABSL_NAMESPACE_BEGIN::MATCHER_P2(), absl::ABSL_NAMESPACE_BEGIN::operator<<(), SolveAllBoardsN(), SolveChunkCommon(), SolveSingleCommon(), CordAppendBufferTest::ToString(), and CordTest::ToString().
scheduler
Scheduler scheduler extern
Definition at line 23 of file Init.cpp.
Referenced by SolveAllBoardsN(), and SolveChunkCommon().
sysdep
System sysdep extern
Definition at line 21 of file Init.cpp.
Referenced by SolveAllBoardsN().