open spiel: absl::cord_internal::CordRepFlat Struct Reference
absl::cord_internal::CordRepFlat Struct Reference
#include <cord_rep_flat.h>
Classes
struct Large
Public Member Functions
char * Data ()
const char * Data () const
size_t Capacity () const
size_t AllocatedSize () const
Public Member Functions inherited from absl::cord_internal::CordRep
CordRep ()=default
constexpr CordRep (RefcountAndFlags::Immortal immortal, size_t l)
constexpr bool IsRing () const
constexpr bool IsSubstring () const
constexpr bool IsCrc () const
constexpr bool IsExternal () const
constexpr bool IsFlat () const
constexpr bool IsBtree () const
CordRepRing * ring ()
const CordRepRing * ring () const
CordRepSubstring * substring ()
const CordRepSubstring * substring () const
CordRepCrc * crc ()
const CordRepCrc * crc () const
CordRepExternal * external ()
const CordRepExternal * external () const
CordRepFlat * flat ()
const CordRepFlat * flat () const
CordRepBtree * btree ()
const CordRepBtree * btree () const
Static Public Member Functions
template<size_t max_flat_size, typename... Args>
static CordRepFlat * NewImpl (size_t len, Args... args ABSL_ATTRIBUTE_UNUSED)
static CordRepFlat * New (size_t len)
static CordRepFlat * New (Large, size_t len)
static void Delete (CordRep *rep)
static CordRepFlat * Create (absl::string_view data, size_t extra=0)
Static Public Member Functions inherited from absl::cord_internal::CordRep
static void Destroy (CordRep *rep)
static CordRep * Ref (CordRep *rep)
static void Unref (CordRep *rep)
Additional Inherited Members
Public Attributes inherited from absl::cord_internal::CordRep
size_t length
RefcountAndFlags refcount
uint8_t tag
uint8_t storage [3]
Detailed Description
Definition at line 107 of file cord_rep_flat.h.
Member Function Documentation
AllocatedSize()
size_t absl::cord_internal::CordRepFlat::AllocatedSize () const inline
Definition at line 169 of file cord_rep_flat.h.
{ return TagToAllocatedSize(tag); }
References absl::cord_internal::CordRep::tag, and absl::cord_internal::TagToAllocatedSize().
Capacity()
size_t absl::cord_internal::CordRepFlat::Capacity () const inline
Definition at line 166 of file cord_rep_flat.h.
{ return TagToLength(tag); }
References absl::cord_internal::CordRep::tag, and absl::cord_internal::TagToLength().
Referenced by absl::CordBuffer::capacity(), absl::cord_internal::CordRepBtree::ExtractAppendBuffer(), absl::cord_internal::CordRepBtree::GetAppendBuffer(), absl::Cord::operator=(), TEST(), TEST(), and TEST().
Create()
static CordRepFlat * absl::cord_internal::CordRepFlat::Create (absl::string_view data, size_t extra = 0) inline static
Definition at line 153 of file cord_rep_flat.h.
{
    assert(data.size() <= kMaxFlatLength);
    CordRepFlat* flat = New(data.size() + (std::min)(extra, kMaxFlatLength));
    memcpy(flat->Data(), data.data(), data.size());
    flat->length = data.size();
    return flat;
  }
References Data(), absl::cord_internal::CordRep::flat(), absl::cord_internal::CordRep::length, and New().
Data() [1/2]
char * absl::cord_internal::CordRepFlat::Data () inline
Definition at line 162 of file cord_rep_flat.h.
{ return reinterpret_cast<char*>(storage); }
References absl::cord_internal::CordRep::storage.
Referenced by Create(), absl::CordBuffer::data(), absl::CordBuffer::data(), absl::cord_internal::EdgeData(), absl::cord_internal::CordRepBtree::GetAppendBuffer(), absl::Cord::operator=(), absl::Cord::operator[](), absl::cord_internal::CordRepRing::Prepend(), TEST(), and absl::TestCordRep::TestCordRep().
Data() [2/2]
const char * absl::cord_internal::CordRepFlat::Data () const inline
Definition at line 163 of file cord_rep_flat.h.
{ return reinterpret_cast<const char*>(storage); }
References absl::cord_internal::CordRep::storage.
Delete()
static void absl::cord_internal::CordRepFlat::Delete (CordRep * rep) inline static
Definition at line 137 of file cord_rep_flat.h.
{
    assert(rep->tag >= FLAT && rep->tag <= MAX_FLAT_TAG);
#if defined(__cpp_sized_deallocation)
    size_t size = TagToAllocatedSize(rep->tag);
    rep->~CordRep();
    ::operator delete(rep, size);
#else
    rep->~CordRep();
    ::operator delete(rep);
#endif
  }
References absl::cord_internal::FLAT, absl::cord_internal::MAX_FLAT_TAG, rep, size, and absl::cord_internal::TagToAllocatedSize().
Referenced by absl::cord_internal::CordRep::Destroy(), absl::CordBuffer::operator=(), and absl::CordBuffer::~CordBuffer().
New() [1/2]
static CordRepFlat * absl::cord_internal::CordRepFlat::New (Large , size_t len) inline static
Definition at line 130 of file cord_rep_flat.h.
{
    return NewImpl<kMaxLargeFlatSize>(len);
  }
References len, and NewImpl().
New() [2/2]
static CordRepFlat * absl::cord_internal::CordRepFlat::New (size_t len) inline static
Definition at line 128 of file cord_rep_flat.h.
{ return NewImpl<kMaxFlatSize>(len); }
References len, and NewImpl().
Referenced by Create(), absl::CordBuffer::CreateWithDefaultLimit(), absl::cordrep_testing::MakeFlat(), TEST(), TEST(), TEST(), and absl::TestCordRep::TestCordRep().
NewImpl()
template<size_t max_flat_size, typename... Args> static CordRepFlat * absl::cord_internal::CordRepFlat::NewImpl (size_t len, Args... args ABSL_ATTRIBUTE_UNUSED) inline static
Definition at line 113 of file cord_rep_flat.h.
{
    if (len <= kMinFlatLength) {
      len = kMinFlatLength;
    } else if (len > max_flat_size - kFlatOverhead) {
      len = max_flat_size - kFlatOverhead;
    }
    // Round size up so it matches a size we can exactly express in a tag.
    const size_t size = RoundUpForTag(len + kFlatOverhead);
    void* const raw_rep = ::operator new(size);
    CordRepFlat* rep = new (raw_rep) CordRepFlat();
    rep->tag = AllocatedSizeToTag(size);
    return rep;
  }
References absl::cord_internal::AllocatedSizeToTag(), len, rep, absl::cord_internal::RoundUpForTag(), size, and absl::cord_internal::CordRep::tag.
Referenced by New(), and New().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_flat.h