open spiel: absl::container_internal::common_policy_traits< Policy, class > Struct Template Reference
absl::container_internal::common_policy_traits< Policy, class > Struct Template Reference
#include <common_policy_traits.h>
Public Types
using slot_type = typename Policy::slot_type
using reference = decltype(Policy::element(std::declval<slot_type*>()))
using value_type = typename std::remove_reference<reference>::type
Static Public Member Functions
template<class Alloc , class... Args>
static void construct (Alloc *alloc, slot_type *slot, Args &&... args)
template<class Alloc >
static void destroy (Alloc *alloc, slot_type *slot)
template<class Alloc >
static void transfer (Alloc *alloc, slot_type *new_slot, slot_type *old_slot)
template<class P = Policy>
static auto element (absl::remove_const_t< slot_type > *slot) -> decltype(P::element(slot))
template<class P = Policy>
static auto element (const slot_type *slot) -> decltype(P::element(slot))
static constexpr bool transfer_uses_memcpy ()
Detailed Description
template<class Policy, class = void>
struct absl::container_internal::common_policy_traits< Policy, class >
Definition at line 33 of file common_policy_traits.h.
Member Typedef Documentation
reference
template<class Policy , class = void> using absl::container_internal::common_policy_traits< Policy, class >::reference = decltype(Policy::element(std::declval<slot_type*>()))
Definition at line 36 of file common_policy_traits.h.
slot_type
template<class Policy , class = void> using absl::container_internal::common_policy_traits< Policy, class >::slot_type = typename Policy::slot_type
Definition at line 35 of file common_policy_traits.h.
value_type
template<class Policy , class = void> using absl::container_internal::common_policy_traits< Policy, class >::value_type = typename std::remove_reference<reference>::type
Definition at line 37 of file common_policy_traits.h.
Member Function Documentation
construct()
template<class Policy , class = void> template<class Alloc , class... Args> static void absl::container_internal::common_policy_traits< Policy, class >::construct (Alloc * alloc, slot_type * slot, Args &&... args) inline static
Definition at line 42 of file common_policy_traits.h.
{
    Policy::construct(alloc, slot, std::forward<Args>(args)...);
  }
References alloc.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace_at(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::constructor::operator()().
destroy()
template<class Policy , class = void> template<class Alloc > static void absl::container_internal::common_policy_traits< Policy, class >::destroy (Alloc * alloc, slot_type * slot) inline static
Definition at line 49 of file common_policy_traits.h.
{
    Policy::destroy(alloc, slot);
  }
References alloc.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::destroy_slots(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::erase().
element() [1/2]
template<class Policy , class = void> template<class P = Policy> static auto absl::container_internal::common_policy_traits< Policy, class >::element (absl::remove_const_t< slot_type > * slot) -> decltype(P::element(slot)) inline static
Definition at line 74 of file common_policy_traits.h.
{
    return P::element(slot);
  }
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find_or_prepare_insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::merge(), absl::container_internal::hash_policy_traits< Policy, class >::mutable_key(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::iterator::operator*().
element() [2/2]
template<class Policy , class = void> template<class P = Policy> static auto absl::container_internal::common_policy_traits< Policy, class >::element (const slot_type * slot) -> decltype(P::element(slot)) inline static
Definition at line 79 of file common_policy_traits.h.
{
    return P::element(slot);
  }
transfer()
template<class Policy , class = void> template<class Alloc > static void absl::container_internal::common_policy_traits< Policy, class >::transfer (Alloc * alloc, slot_type * new_slot, slot_type * old_slot) inline static
Definition at line 65 of file common_policy_traits.h.
{
    transfer_impl(alloc, new_slot, old_slot, Rank0{});
  }
References alloc.
transfer_uses_memcpy()
template<class Policy , class = void> static constexpr bool absl::container_internal::common_policy_traits< Policy, class >::transfer_uses_memcpy () inline static constexpr
Definition at line 83 of file common_policy_traits.h.
{
    return std::is_same<decltype(transfer_impl<std::allocator<char>>(
                            nullptr, nullptr, nullptr, Rank0{})),
                        std::true_type>::value;
  }
References value.
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/common_policy_traits.h