open spiel: absl::random_internal::DistributionCaller< typename > Struct Template Reference
absl::random_internal::DistributionCaller< typename > Struct Template Reference
#include <distribution_caller.h>
Classes
struct detector
struct detector< Trait, absl::void_t< Trait< Args... > >, Args... >
Public Types
template<class T >
using invoke_mock_t
using HasInvokeMock = typename detector<invoke_mock_t, void, URBG>::type
Static Public Member Functions
template<typename DistrT , typename... Args>
static DistrT::result_type Impl (std::false_type, URBG *urbg, Args &&... args)
template<typename DistrT , typename... Args>
static DistrT::result_type Impl (std::true_type, URBG *urbg, Args &&... args)
template<typename DistrT , typename... Args>
static DistrT::result_type Call (URBG *urbg, Args &&... args)
Detailed Description
template<typename>
struct absl::random_internal::DistributionCaller< typename >
Definition at line 57 of file mocking_bit_gen.h.
Member Typedef Documentation
HasInvokeMock
template<typename > using absl::random_internal::DistributionCaller< typename >::HasInvokeMock = typename detector<invoke_mock_t, void, URBG>::type
Definition at line 54 of file distribution_caller.h.
invoke_mock_t
template<typename > template<class T > using absl::random_internal::DistributionCaller< typename >::invoke_mock_t
Initial value:
 decltype(std::declval<T*>()->InvokeMock(
      std::declval<::absl::base_internal::FastTypeIdType>(),
      std::declval<void*>(), std::declval<void*>()))
Definition at line 50 of file distribution_caller.h.
Member Function Documentation
Call()
template<typename > template<typename DistrT , typename... Args> static DistrT::result_type absl::random_internal::DistributionCaller< typename >::Call (URBG * urbg, Args &&... args) inline static
Definition at line 85 of file distribution_caller.h.
{
    return Impl<DistrT, Args...>(HasInvokeMock{}, urbg,
                                 std::forward<Args>(args)...);
  }
References absl::random_internal::DistributionCaller< typename >::Impl().
Impl() [1/2]
template<typename > template<typename DistrT , typename... Args> static DistrT::result_type absl::random_internal::DistributionCaller< typename >::Impl (std::false_type , URBG * urbg, Args &&... args) inline static
Definition at line 58 of file distribution_caller.h.
{
    DistrT dist(std::forward<Args>(args)...);
    return dist(*urbg);
  }
Referenced by absl::random_internal::DistributionCaller< typename >::Call().
Impl() [2/2]
template<typename > template<typename DistrT , typename... Args> static DistrT::result_type absl::random_internal::DistributionCaller< typename >::Impl (std::true_type , URBG * urbg, Args &&... args) inline static
Definition at line 67 of file distribution_caller.h.
{
    using ResultT = typename DistrT::result_type;
    using ArgTupleT = std::tuple<absl::decay_t<Args>...>;
    using KeyT = ResultT(DistrT, ArgTupleT);
    ArgTupleT arg_tuple(std::forward<Args>(args)...);
    ResultT result;
    if (!urbg->InvokeMock(::absl::base_internal::FastTypeId<KeyT>(), &arg_tuple,
                          &result)) {
      auto dist = absl::make_from_tuple<DistrT>(arg_tuple);
      result = dist(*urbg);
    }
    return result;
  }
References absl::base_internal::FastTypeId(), and absl::make_from_tuple().
The documentation for this struct was generated from the following files:
open_spiel/abseil-cpp/absl/random/bit_gen_ref.h
open_spiel/abseil-cpp/absl/random/internal/distribution_caller.h
open_spiel/abseil-cpp/absl/random/mocking_bit_gen.h