open spiel: absl::container_internal::map_slot_policy< K, V > Struct Template Reference
absl::container_internal::map_slot_policy< K, V > Struct Template Reference
#include <container_memory.h>
Public Types
using slot_type = map_slot_type<K, V>
using value_type = std::pair<const K, V>
using mutable_value_type
Static Public Member Functions
static value_type & element (slot_type *slot)
static const value_type & element (const slot_type *slot)
static const K & mutable_key (slot_type *slot)
static const K & key (const slot_type *slot)
template<class Allocator , class... Args>
static void construct (Allocator *alloc, slot_type *slot, Args &&... args)
template<class Allocator >
static void construct (Allocator *alloc, slot_type *slot, slot_type *other)
template<class Allocator >
static void construct (Allocator *alloc, slot_type *slot, const slot_type *other)
template<class Allocator >
static void destroy (Allocator *alloc, slot_type *slot)
template<class Allocator >
static void transfer (Allocator *alloc, slot_type *new_slot, slot_type *old_slot)
Detailed Description
template<class K, class V>
struct absl::container_internal::map_slot_policy< K, V >
Definition at line 341 of file container_memory.h.
Member Typedef Documentation
mutable_value_type
template<class K , class V > using absl::container_internal::map_slot_policy< K, V >::mutable_value_type
Initial value:
      std::pair<absl::remove_const_t<K>, absl::remove_const_t<V>>
Definition at line 344 of file container_memory.h.
slot_type
template<class K , class V > using absl::container_internal::map_slot_policy< K, V >::slot_type = map_slot_type<K, V>
Definition at line 342 of file container_memory.h.
value_type
template<class K , class V > using absl::container_internal::map_slot_policy< K, V >::value_type = std::pair<const K, V>
Definition at line 343 of file container_memory.h.
Member Function Documentation
construct() [1/3]
template<class K , class V > template<class Allocator , class... Args> static void absl::container_internal::map_slot_policy< K, V >::construct (Allocator * alloc, slot_type * slot, Args &&... args) inline static
Definition at line 383 of file container_memory.h.
{
    emplace(slot);
    if (kMutableKeys::value) {
      absl::allocator_traits<Allocator>::construct(*alloc, &slot->mutable_value,
                                                   std::forward<Args>(args)...);
    } else {
      absl::allocator_traits<Allocator>::construct(*alloc, &slot->value,
                                                   std::forward<Args>(args)...);
    }
  }
References alloc, absl::container_internal::map_slot_type< K, V >::mutable_value, and absl::container_internal::map_slot_type< K, V >::value.
Referenced by absl::container_internal::FlatHashMapPolicy< K, V >::construct().
construct() [2/3]
template<class K , class V > template<class Allocator > static void absl::container_internal::map_slot_policy< K, V >::construct (Allocator * alloc, slot_type * slot, const slot_type * other) inline static
Definition at line 409 of file container_memory.h.
{
    emplace(slot);
    absl::allocator_traits<Allocator>::construct(*alloc, &slot->value,
                                                 other->value);
  }
References alloc, and absl::container_internal::map_slot_type< K, V >::value.
construct() [3/3]
template<class K , class V > template<class Allocator > static void absl::container_internal::map_slot_policy< K, V >::construct (Allocator * alloc, slot_type * slot, slot_type * other) inline static
Definition at line 396 of file container_memory.h.
{
    emplace(slot);
    if (kMutableKeys::value) {
      absl::allocator_traits<Allocator>::construct(
          *alloc, &slot->mutable_value, std::move(other->mutable_value));
    } else {
      absl::allocator_traits<Allocator>::construct(*alloc, &slot->value,
                                                   std::move(other->value));
    }
  }
References alloc, absl::container_internal::map_slot_type< K, V >::mutable_value, and absl::container_internal::map_slot_type< K, V >::value.
destroy()
template<class K , class V > template<class Allocator > static void absl::container_internal::map_slot_policy< K, V >::destroy (Allocator * alloc, slot_type * slot) inline static
Definition at line 417 of file container_memory.h.
{
    if (kMutableKeys::value) {
      absl::allocator_traits<Allocator>::destroy(*alloc, &slot->mutable_value);
    } else {
      absl::allocator_traits<Allocator>::destroy(*alloc, &slot->value);
    }
  }
References alloc, absl::container_internal::map_slot_type< K, V >::mutable_value, and absl::container_internal::map_slot_type< K, V >::value.
Referenced by absl::container_internal::FlatHashMapPolicy< K, V >::destroy().
element() [1/2]
template<class K , class V > static const value_type & absl::container_internal::map_slot_policy< K, V >::element (const slot_type * slot) inline static
Definition at line 360 of file container_memory.h.
{
    return slot->value;
  }
References absl::container_internal::map_slot_type< K, V >::value.
element() [2/2]
template<class K , class V > static value_type & absl::container_internal::map_slot_policy< K, V >::element (slot_type * slot) inline static
Definition at line 359 of file container_memory.h.
{ return slot->value; }
References absl::container_internal::map_slot_type< K, V >::value.
key()
template<class K , class V > static const K & absl::container_internal::map_slot_policy< K, V >::key (const slot_type * slot) inline static
Definition at line 378 of file container_memory.h.
{
    return kMutableKeys::value ? slot->key : slot->value.first;
  }
References absl::container_internal::map_slot_type< K, V >::key, and absl::container_internal::map_slot_type< K, V >::value.
mutable_key()
template<class K , class V > static const K & absl::container_internal::map_slot_policy< K, V >::mutable_key (slot_type * slot) inline static
Definition at line 375 of file container_memory.h.
{ return key(slot); }
References key.
transfer()
template<class K , class V > template<class Allocator > static void absl::container_internal::map_slot_policy< K, V >::transfer (Allocator * alloc, slot_type * new_slot, slot_type * old_slot) inline static
Definition at line 426 of file container_memory.h.
{
    emplace(new_slot);
#if defined(__cpp_lib_launder) && __cpp_lib_launder >= 201606
    if (absl::is_trivially_relocatable<value_type>()) {
      // TODO(b/247130232,b/251814870): remove casts after fixing warnings.
      std::memcpy(static_cast<void*>(std::launder(&new_slot->value)),
                  static_cast<const void*>(&old_slot->value),
                  sizeof(value_type));
      return;
    }
#endif
    if (kMutableKeys::value) {
      absl::allocator_traits<Allocator>::construct(
          *alloc, &new_slot->mutable_value, std::move(old_slot->mutable_value));
    } else {
      absl::allocator_traits<Allocator>::construct(*alloc, &new_slot->value,
                                                   std::move(old_slot->value));
    }
    destroy(alloc, old_slot);
  }
References alloc, absl::container_internal::map_slot_type< K, V >::mutable_value, and absl::container_internal::map_slot_type< K, V >::value.
Referenced by absl::container_internal::FlatHashMapPolicy< K, V >::transfer().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/container_memory.h