open spiel: absl::container_internal::btree_access Struct Reference
absl::container_internal::btree_access Struct Reference
#include <btree.h>
Static Public Member Functions
template<typename BtreeContainer , typename Pred >
static auto erase_if (BtreeContainer &container, Pred pred) -> typename BtreeContainer::size_type
Detailed Description
Definition at line 2934 of file btree.h.
Member Function Documentation
erase_if()
template<typename BtreeContainer , typename Pred > static auto absl::container_internal::btree_access::erase_if (BtreeContainer & container, Pred pred) -> typename BtreeContainer::size_type inline static
Definition at line 2936 of file btree.h.
{
    const auto initial_size = container.size();
    auto &tree = container.tree_;
    auto *alloc = tree.mutable_allocator();
    for (auto it = container.begin(); it != container.end();) {
      if (!pred(*it)) {
        ++it;
        continue;
      }
      auto *node = it.node_;
      if (node->is_internal()) {
        // Handle internal nodes normally.
        it = container.erase(it);
        continue;
      }
      // If this is a leaf node, then we do all the erases from this node
      // at once before doing rebalancing.
      // The current position to transfer slots to.
      int to_pos = it.position_;
      node->value_destroy(it.position_, alloc);
      while (++it.position_ < node->finish()) {
        it.update_generation();
        if (pred(*it)) {
          node->value_destroy(it.position_, alloc);
        } else {
          node->transfer(node->slot(to_pos++), node->slot(it.position_), alloc);
        }
      }
      const int num_deleted = node->finish() - to_pos;
      tree.size_ -= num_deleted;
      node->set_finish(to_pos);
      it.position_ = to_pos;
      it = tree.rebalance_after_delete(it);
    }
    return initial_size - container.size();
  }
Referenced by absl::erase_if(), absl::erase_if(), absl::erase_if(), and absl::erase_if().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/btree.h