open spiel: absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti > Struct Template Reference
absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti > Struct Template Reference
#include <btree_map.h>
Public Types
using super_type = typename map_params::common_params
using mapped_type = Data
using slot_policy = typename super_type::slot_policy
using slot_type = typename super_type::slot_type
using value_type = typename super_type::value_type
using init_type = typename super_type::init_type
Public Types inherited from absl::container_internal::common_params< Key, Compare, Alloc, TargetNodeSize, IsMulti, true, map_slot_policy< Key, Data > >
enum
using original_key_compare
using key_compare
using is_key_compare_to
using allocator_type
using key_type
using size_type
using difference_type
using slot_policy
using slot_type
using value_type
using init_type
using pointer
using const_pointer
using reference
using const_reference
using value_compare
using is_map_container
using node_count_type
Public Types inherited from absl::container_internal::common_policy_traits< map_slot_policy< Key, Data > >
using slot_type
using reference
using value_type
Static Public Member Functions
template<typename V >
static auto key (const V &value) -> decltype(value.first)
static const Key & key (const slot_type *s)
static const Key & key (slot_type *s)
static auto mutable_key (slot_type *s) -> decltype(slot_policy::mutable_key(s))
static mapped_type & value (value_type *value)
Static Public Member Functions inherited from absl::container_internal::common_params< Key, Compare, Alloc, TargetNodeSize, IsMulti, true, map_slot_policy< Key, Data > >
static constexpr bool can_have_multiple_equivalent_keys ()
Static Public Member Functions inherited from absl::container_internal::common_policy_traits< map_slot_policy< Key, Data > >
static void construct (Alloc *alloc, slot_type *slot, Args &&... args)
static void destroy (Alloc *alloc, slot_type *slot)
static void transfer (Alloc *alloc, slot_type *new_slot, slot_type *old_slot)
static auto element (absl::remove_const_t< slot_type > *slot) -> decltype(P::element(slot))
static auto element (const slot_type *slot) -> decltype(P::element(slot))
static constexpr bool transfer_uses_memcpy ()
Additional Inherited Members
Static Public Attributes inherited from absl::container_internal::common_params< Key, Compare, Alloc, TargetNodeSize, IsMulti, true, map_slot_policy< Key, Data > >
static constexpr bool kIsKeyCompareStringAdapted
static constexpr bool kIsKeyCompareTransparent
static constexpr bool kEnableGenerations
Detailed Description
template<typename Key, typename Data, typename Compare, typename Alloc, int TargetNodeSize, bool IsMulti>
struct absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >
Definition at line 855 of file btree_map.h.
Member Typedef Documentation
init_type
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> using absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::init_type = typename super_type::init_type
Definition at line 864 of file btree_map.h.
mapped_type
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> using absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::mapped_type = Data
Definition at line 858 of file btree_map.h.
slot_policy
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> using absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::slot_policy = typename super_type::slot_policy
Definition at line 861 of file btree_map.h.
slot_type
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> using absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::slot_type = typename super_type::slot_type
Definition at line 862 of file btree_map.h.
super_type
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> using absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::super_type = typename map_params::common_params
Definition at line 857 of file btree_map.h.
value_type
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> using absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::value_type = typename super_type::value_type
Definition at line 863 of file btree_map.h.
Member Function Documentation
key() [1/3]
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> static const Key & absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::key (const slot_type * s) inline static
Definition at line 870 of file btree_map.h.
{ return slot_policy::key(s); }
References absl::s.
key() [2/3]
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> template<typename V > static auto absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::key (const V & value) -> decltype(value.first) inline static
Definition at line 867 of file btree_map.h.
{
    return value.first;
  }
key() [3/3]
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> static const Key & absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::key (slot_type * s) inline static
Definition at line 871 of file btree_map.h.
{ return slot_policy::key(s); }
References absl::s.
mutable_key()
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> static auto absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::mutable_key (slot_type * s) -> decltype(slot_policy::mutable_key(s)) inline static
Definition at line 873 of file btree_map.h.
{
    return slot_policy::mutable_key(s);
  }
References absl::s.
value()
template<typename Key , typename Data , typename Compare , typename Alloc , int TargetNodeSize, bool IsMulti> static mapped_type & absl::container_internal::map_params< Key, Data, Compare, Alloc, TargetNodeSize, IsMulti >::value (value_type * value) inline static
Definition at line 877 of file btree_map.h.
{ return value->second; }
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/btree_map.h