open spiel: absl::random_internal::stream_u128_helper< absl::uint128 > Struct Reference
absl::random_internal::stream_u128_helper< absl::uint128 > Struct Reference
#include <iostream_state_saver.h>
Public Member Functions
template<typename IStream >
absl::uint128 read (IStream &in)
template<typename OStream >
void write (absl::uint128 val, OStream &out)
Detailed Description
Definition at line 184 of file iostream_state_saver.h.
Member Function Documentation
read()
template<typename IStream > absl::uint128 absl::random_internal::stream_u128_helper< absl::uint128 >::read (IStream & in) inline
Definition at line 186 of file iostream_state_saver.h.
{
    uint64_t h = 0;
    uint64_t l = 0;
    in >> h >> l;
    return absl::MakeUint128(h, l);
  }
References in, and absl::MakeUint128().
write()
template<typename OStream > void absl::random_internal::stream_u128_helper< absl::uint128 >::write (absl::uint128 val, OStream & out) inline
Definition at line 194 of file iostream_state_saver.h.
{
    uint64_t h = absl::Uint128High64(val);
    uint64_t l = absl::Uint128Low64(val);
    out << h << out.fill() << l;
  }
References absl::out, absl::Uint128High64(), and absl::Uint128Low64().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/random/internal/iostream_state_saver.h