open spiel: absl::cord_internal::CordRepCrc Struct Reference
absl::cord_internal::CordRepCrc Struct Reference
#include <cord_rep_crc.h>
Static Public Member Functions
static CordRepCrc * New (CordRep *child, crc_internal::CrcCordState state)
static void Destroy (CordRepCrc *node)
Static Public Member Functions inherited from absl::cord_internal::CordRep
static void Destroy (CordRep *rep)
static CordRep * Ref (CordRep *rep)
static void Unref (CordRep *rep)
Public Attributes
CordRep * child
absl::crc_internal::CrcCordState crc_cord_state
Public Attributes inherited from absl::cord_internal::CordRep
size_t length
RefcountAndFlags refcount
uint8_t tag
uint8_t storage [3]
Additional Inherited Members
Public Member Functions inherited from absl::cord_internal::CordRep
CordRep ()=default
constexpr CordRep (RefcountAndFlags::Immortal immortal, size_t l)
constexpr bool IsRing () const
constexpr bool IsSubstring () const
constexpr bool IsCrc () const
constexpr bool IsExternal () const
constexpr bool IsFlat () const
constexpr bool IsBtree () const
CordRepRing * ring ()
const CordRepRing * ring () const
CordRepSubstring * substring ()
const CordRepSubstring * substring () const
CordRepCrc * crc ()
const CordRepCrc * crc () const
CordRepExternal * external ()
const CordRepExternal * external () const
CordRepFlat * flat ()
const CordRepFlat * flat () const
CordRepBtree * btree ()
const CordRepBtree * btree () const
Detailed Description
Definition at line 36 of file cord_rep_crc.h.
Member Function Documentation
Destroy()
void absl::cord_internal::CordRepCrc::Destroy (CordRepCrc * node) static
Definition at line 47 of file cord_rep_crc.cc.
{
  if (node->child != nullptr) {
    CordRep::Unref(node->child);
  }
  delete node;
}
References child, and absl::cord_internal::CordRep::Unref().
Referenced by absl::cord_internal::CordRep::Destroy().
New()
CordRepCrc * absl::cord_internal::CordRepCrc::New (CordRep * child, crc_internal::CrcCordState state) static
Definition at line 28 of file cord_rep_crc.cc.
{
  if (child != nullptr && child->IsCrc()) {
    if (child->refcount.IsOne()) {
      child->crc()->crc_cord_state = std::move(state);
      return child->crc();
    }
    CordRep* old = child;
    child = old->crc()->child;
    CordRep::Ref(child);
    CordRep::Unref(old);
  }
  auto* new_cordrep = new CordRepCrc;
  new_cordrep->length = child != nullptr ? child->length : 0;
  new_cordrep->tag = cord_internal::CRC;
  new_cordrep->child = child;
  new_cordrep->crc_cord_state = std::move(state);
  return new_cordrep;
}
References child, absl::cord_internal::CRC, absl::cord_internal::CordRep::crc(), crc_cord_state, absl::cord_internal::CordRep::IsCrc(), absl::cord_internal::RefcountAndFlags::IsOne(), absl::cord_internal::CordRep::length, absl::cord_internal::CordRep::Ref(), absl::cord_internal::CordRep::refcount, state, and absl::cord_internal::CordRep::Unref().
Member Data Documentation
child
CordRep* absl::cord_internal::CordRepCrc::child
Definition at line 37 of file cord_rep_crc.h.
Referenced by Destroy(), New(), absl::cord_internal::RemoveCrcNode(), absl::cord_internal::SkipCrcNode(), and absl::cord_internal::SkipCrcNode().
crc_cord_state
absl::crc_internal::CrcCordState absl::cord_internal::CordRepCrc::crc_cord_state
Definition at line 38 of file cord_rep_crc.h.
Referenced by absl::Cord::ExpectedChecksum(), and New().
The documentation for this struct was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_crc.h
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_crc.cc