open spiel: absl::cord_internal::CordRep Struct Reference
absl::cord_internal::CordRep Struct Reference
#include <cord_internal.h>
Classes
struct ExtractResult
Public Member Functions
CordRep ()=default
constexpr CordRep (RefcountAndFlags::Immortal immortal, size_t l)
constexpr bool IsRing () const
constexpr bool IsSubstring () const
constexpr bool IsCrc () const
constexpr bool IsExternal () const
constexpr bool IsFlat () const
constexpr bool IsBtree () const
CordRepRing * ring ()
const CordRepRing * ring () const
CordRepSubstring * substring ()
const CordRepSubstring * substring () const
CordRepCrc * crc ()
const CordRepCrc * crc () const
CordRepExternal * external ()
const CordRepExternal * external () const
CordRepFlat * flat ()
const CordRepFlat * flat () const
CordRepBtree * btree ()
const CordRepBtree * btree () const
Static Public Member Functions
static void Destroy (CordRep *rep)
static CordRep * Ref (CordRep *rep)
static void Unref (CordRep *rep)
Public Attributes
size_t length
RefcountAndFlags refcount
uint8_t tag
uint8_t storage [3]
Detailed Description
Definition at line 261 of file cord_internal.h.
Constructor & Destructor Documentation
CordRep() [1/2]
absl::cord_internal::CordRep::CordRep () default
CordRep() [2/2]
absl::cord_internal::CordRep::CordRep (RefcountAndFlags::Immortal immortal, size_t l) inline constexpr
Definition at line 275 of file cord_internal.h.
      : length(l), refcount(immortal), tag(EXTERNAL), storage{} {}
Member Function Documentation
btree() [1/2]
CordRepBtree * absl::cord_internal::CordRep::btree () inline
Definition at line 590 of file cord_rep_btree.h.
{
  assert(IsBtree());
  return static_cast<CordRepBtree*>(this);
}
References IsBtree().
Referenced by absl::cord_internal::CordRepBtree::ExtractAppendBuffer(), absl::cord_internal::CordRepBtree::GetAppendBuffer(), absl::cord_internal::CordRepBtree::GetCharacter(), absl::cord_internal::CordRepBtree::IsFlat(), absl::Cord::operator[](), absl::cord_internal::CordRepBtreeNavigator::Read(), absl::Cord::RemovePrefix(), absl::Cord::RemoveSuffix(), absl::cord_internal::CordRepBtree::RemoveSuffix(), absl::cord_internal::CordRepBtreeNavigator::Seek(), absl::cord_internal::CordRepBtreeNavigator::Skip(), absl::Cord::Subcord(), and absl::cord_internal::CordRepBtree::SubTree().
btree() [2/2]
const CordRepBtree * absl::cord_internal::CordRep::btree () const inline
Definition at line 595 of file cord_rep_btree.h.
{
  assert(IsBtree());
  return static_cast<const CordRepBtree*>(this);
}
References IsBtree().
crc() [1/2]
CordRepCrc * absl::cord_internal::CordRep::crc () inline
Definition at line 89 of file cord_rep_crc.h.
{
  assert(IsCrc());
  return static_cast<CordRepCrc*>(this);
}
References IsCrc().
Referenced by absl::Cord::ExpectedChecksum(), absl::cord_internal::CordRepCrc::New(), absl::cord_internal::RemoveCrcNode(), absl::cord_internal::SkipCrcNode(), and absl::cord_internal::SkipCrcNode().
crc() [2/2]
const CordRepCrc * absl::cord_internal::CordRep::crc () const inline
Definition at line 94 of file cord_rep_crc.h.
{
  assert(IsCrc());
  return static_cast<const CordRepCrc*>(this);
}
References IsCrc().
Destroy()
void absl::cord_internal::CordRep::Destroy (CordRep * rep) static
Definition at line 43 of file cord_internal.cc.
{
  assert(rep != nullptr);
  while (true) {
    assert(!rep->refcount.IsImmortal());
    if (rep->tag == BTREE) {
      CordRepBtree::Destroy(rep->btree());
      return;
    } else if (rep->tag == RING) {
      CordRepRing::Destroy(rep->ring());
      return;
    } else if (rep->tag == EXTERNAL) {
      CordRepExternal::Delete(rep);
      return;
    } else if (rep->tag == SUBSTRING) {
      CordRepSubstring* rep_substring = rep->substring();
      rep = rep_substring->child;
      delete rep_substring;
      if (rep->refcount.Decrement()) {
        return;
      }
    } else if (rep->tag == CRC) {
      CordRepCrc::Destroy(rep->crc());
      return;
    } else {
      assert(rep->IsFlat());
      CordRepFlat::Delete(rep);
      return;
    }
  }
}
References absl::cord_internal::BTREE, absl::cord_internal::CordRepSubstring::child, absl::cord_internal::CRC, absl::cord_internal::CordRepExternal::Delete(), absl::cord_internal::CordRepFlat::Delete(), absl::cord_internal::CordRepBtree::Destroy(), absl::cord_internal::CordRepCrc::Destroy(), absl::cord_internal::EXTERNAL, rep, absl::cord_internal::RING, absl::cord_internal::SUBSTRING, and substring().
Referenced by Unref(), and absl::cord_internal::CordRepBtree::Unref().
external() [1/2]
CordRepExternal * absl::cord_internal::CordRep::external () inline
Definition at line 880 of file cord_internal.h.
{
  assert(IsExternal());
  return static_cast<CordRepExternal*>(this);
}
References IsExternal().
Referenced by absl::cord_internal::EdgeData(), and absl::Cord::operator[]().
external() [2/2]
const CordRepExternal * absl::cord_internal::CordRep::external () const inline
Definition at line 885 of file cord_internal.h.
{
  assert(IsExternal());
  return static_cast<const CordRepExternal*>(this);
}
References IsExternal().
flat() [1/2]
CordRepFlat * absl::cord_internal::CordRep::flat () inline
Definition at line 173 of file cord_rep_flat.h.
{
  assert(tag >= FLAT && tag <= MAX_FLAT_TAG);
  return reinterpret_cast<CordRepFlat*>(this);
}
References absl::cord_internal::FLAT, absl::cord_internal::MAX_FLAT_TAG, and tag.
Referenced by absl::cord_internal::CordRepFlat::Create(), absl::cord_internal::EdgeData(), absl::cord_internal::CordRepBtree::ExtractAppendBuffer(), absl::cord_internal::CordRepBtree::GetAppendBuffer(), absl::Cord::operator=(), and absl::Cord::operator[]().
flat() [2/2]
const CordRepFlat * absl::cord_internal::CordRep::flat () const inline
Definition at line 178 of file cord_rep_flat.h.
{
  assert(tag >= FLAT && tag <= MAX_FLAT_TAG);
  return reinterpret_cast<const CordRepFlat*>(this);
}
References absl::cord_internal::FLAT, absl::cord_internal::MAX_FLAT_TAG, and tag.
IsBtree()
bool absl::cord_internal::CordRep::IsBtree () const inline constexpr
Definition at line 307 of file cord_internal.h.
{ return tag == BTREE; }
References absl::cord_internal::BTREE, and tag.
Referenced by btree(), btree(), absl::cord_internal::CordRepBtree::IsValid(), absl::cord_internal::CordRepBtree::New(), absl::Cord::operator[](), absl::Cord::RemovePrefix(), absl::Cord::RemoveSuffix(), and absl::Cord::Subcord().
IsCrc()
bool absl::cord_internal::CordRep::IsCrc () const inline constexpr
Definition at line 304 of file cord_internal.h.
{ return tag == CRC; }
References absl::cord_internal::CRC, and tag.
Referenced by crc(), crc(), absl::Cord::ExpectedChecksum(), absl::cord_internal::CordRepCrc::New(), absl::cord_internal::RemoveCrcNode(), absl::cord_internal::SkipCrcNode(), and absl::cord_internal::SkipCrcNode().
IsExternal()
bool absl::cord_internal::CordRep::IsExternal () const inline constexpr
Definition at line 305 of file cord_internal.h.
{ return tag == EXTERNAL; }
References absl::cord_internal::EXTERNAL, and tag.
Referenced by absl::cord_internal::CordRepSubstring::Create(), external(), external(), absl::Cord::operator[](), and absl::Cord::RemoveSuffix().
IsFlat()
bool absl::cord_internal::CordRep::IsFlat () const inline constexpr
Definition at line 306 of file cord_internal.h.
{ return tag >= FLAT; }
References absl::cord_internal::FLAT, and tag.
Referenced by absl::cord_internal::CordRepSubstring::Create(), absl::Cord::operator=(), absl::Cord::operator[](), and absl::Cord::RemoveSuffix().
IsRing()
bool absl::cord_internal::CordRep::IsRing () const inline constexpr
Definition at line 302 of file cord_internal.h.
{ return tag == RING; }
References absl::cord_internal::RING, and tag.
Referenced by ring(), and ring().
IsSubstring()
bool absl::cord_internal::CordRep::IsSubstring () const inline constexpr
Definition at line 303 of file cord_internal.h.
{ return tag == SUBSTRING; }
References absl::cord_internal::SUBSTRING, and tag.
Referenced by absl::cord_internal::EdgeData(), absl::Cord::operator[](), absl::Cord::RemovePrefix(), absl::Cord::RemoveSuffix(), substring(), and substring().
Ref()
CordRep * absl::cord_internal::CordRep::Ref (CordRep * rep) inline static
Definition at line 890 of file cord_internal.h.
{
  // ABSL_ASSUME is a workaround for
  // https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105585
  ABSL_ASSUME(rep != nullptr);
  rep->refcount.Increment();
  return rep;
}
References ABSL_ASSUME, and rep.
Referenced by absl::cord_internal::CordRepCrc::New(), absl::Cord::Prepend(), absl::cord_internal::CordRepBtreeNavigator::Read(), absl::cordrep_testing::AutoUnref::Ref(), absl::cord_internal::CordzInfo::RefCordRep(), absl::cordrep_testing::AutoUnref::RefIf(), absl::cord_internal::RemoveCrcNode(), absl::cord_internal::CordRepBtree::SetEdge(), absl::cord_internal::CordRepSubstring::Substring(), absl::cord_internal::CordRepBtree::SubTree(), and absl::cord_internal::CordzInfo::Untrack().
ring() [1/2]
CordRepRing * absl::cord_internal::CordRep::ring () inline
Definition at line 572 of file cord_rep_ring.h.
{
  assert(IsRing());
  return static_cast<CordRepRing*>(this);
}
References IsRing().
ring() [2/2]
const CordRepRing * absl::cord_internal::CordRep::ring () const inline
Definition at line 577 of file cord_rep_ring.h.
{
  assert(IsRing());
  return static_cast<const CordRepRing*>(this);
}
References IsRing().
substring() [1/2]
CordRepSubstring * absl::cord_internal::CordRep::substring () inline
Definition at line 870 of file cord_internal.h.
{
  assert(IsSubstring());
  return static_cast<CordRepSubstring*>(this);
}
References IsSubstring().
Referenced by absl::cord_internal::Consume(), Destroy(), absl::cord_internal::EdgeData(), absl::cord_internal::IsDataEdge(), absl::Cord::operator[](), and absl::Cord::RemovePrefix().
substring() [2/2]
const CordRepSubstring * absl::cord_internal::CordRep::substring () const inline
Definition at line 875 of file cord_internal.h.
{
  assert(IsSubstring());
  return static_cast<const CordRepSubstring*>(this);
}
References IsSubstring().
Unref()
void absl::cord_internal::CordRep::Unref (CordRep * rep) inline static
Definition at line 898 of file cord_internal.h.
{
  assert(rep != nullptr);
  // Expect refcount to be 0. Avoiding the cost of an atomic decrement should
  // typically outweigh the cost of an extra branch checking for ref == 1.
  if (ABSL_PREDICT_FALSE(!rep->refcount.DecrementExpectHighRefcount())) {
    Destroy(rep);
  }
}
References ABSL_PREDICT_FALSE, Destroy(), and rep.
Referenced by absl::Cord::Clear(), absl::cord_internal::CordRepCrc::Destroy(), absl::cord_internal::CordzInfo::GetCordzStatistics(), absl::cord_internal::CordRepCrc::New(), absl::Cord::operator=(), absl::cord_internal::CordRepBtreeNavigator::Read(), absl::cord_internal::RemoveCrcNode(), absl::Cord::RemovePrefix(), absl::Cord::RemoveSuffix(), absl::cord_internal::CordRepBtree::RemoveSuffix(), absl::cord_internal::CordRepBtree::SetEdge(), TEST(), TEST(), TEST(), absl::cordrep_testing::AutoUnref::~AutoUnref(), and absl::TestCordRep::~TestCordRep().
Member Data Documentation
length
size_t absl::cord_internal::CordRep::length
Definition at line 284 of file cord_internal.h.
Referenced by absl::cord_internal::CordRepBtree::AddEdge(), absl::cord_internal::Consume(), absl::cord_internal::CordRepFlat::Create(), absl::cord_internal::CordRepSubstring::Create(), absl::cord_internal::EdgeData(), absl::cord_internal::CordRepBtree::ExtractAppendBuffer(), absl::cord_internal::CordRepRing::Find(), absl::cord_internal::CordRepRing::Find(), absl::cord_internal::CordRepRing::FindTail(), absl::cord_internal::CordRepRing::FindTail(), absl::cord_internal::CordRepBtree::GetAppendBuffer(), absl::cord_internal::CordRepBtree::GetCharacter(), absl::CordBuffer::IncreaseLengthBy(), absl::cord_internal::CordRepBtreeReader::Init(), absl::cord_internal::InitializeCordRepExternal(), absl::cord_internal::CordRepBtreeNavigator::InitOffset(), absl::cord_internal::CordRepBtree::IsFlat(), absl::cord_internal::CordRepBtree::IsValid(), absl::cord_internal::CordRepBtreeReader::length(), absl::cord_internal::CordRepRingReader::length(), absl::CordBuffer::length(), absl::cord_internal::CordRepBtree::New(), absl::cord_internal::CordRepBtree::New(), absl::cord_internal::CordRepBtree::New(), absl::cord_internal::CordRepCrc::New(), absl::cord_internal::CordRepBtreeReader::Next(), absl::Cord::operator=(), absl::cord_internal::CordRepRing::Prepend(), absl::cord_internal::CordRepBtreeNavigator::Read(), absl::cord_internal::CordRepBtreeReader::Read(), absl::Cord::RemovePrefix(), absl::Cord::RemoveSuffix(), absl::cord_internal::CordRepBtree::RemoveSuffix(), absl::cord_internal::CordRepBtreeNavigator::Seek(), absl::cord_internal::CordRepBtree::SetEdge(), absl::CordBuffer::SetLength(), absl::cord_internal::CordRepBtreeNavigator::Skip(), absl::cord_internal::CordRepBtreeReader::Skip(), absl::cord_internal::CordRepSubstring::Substring(), absl::cord_internal::CordRepBtree::SubTree(), absl::TestCordRep::TestCordRep(), and absl::cord_internal::CordRepExternalImpl< Releaser >::~CordRepExternalImpl().
refcount
RefcountAndFlags absl::cord_internal::CordRep::refcount
Definition at line 285 of file cord_internal.h.
Referenced by absl::cord_internal::CordRepBtree::ExtractAppendBuffer(), absl::cord_internal::CordRepBtree::GetAppendBuffer(), absl::cord_internal::CordRepCrc::New(), absl::Cord::operator=(), absl::cord_internal::RemoveCrcNode(), absl::Cord::RemovePrefix(), absl::Cord::RemoveSuffix(), and absl::cord_internal::CordRepBtree::RemoveSuffix().
storage
uint8_t absl::cord_internal::CordRep::storage[3]
Definition at line 298 of file cord_internal.h.
Referenced by absl::cord_internal::CordRepBtree::back(), absl::cord_internal::CordRepBtree::begin(), absl::cord_internal::CordRepFlat::Data(), absl::cord_internal::CordRepFlat::Data(), absl::cord_internal::CordRepBtree::end(), and absl::cord_internal::CordRepBtree::height().
tag
uint8_t absl::cord_internal::CordRep::tag
Definition at line 288 of file cord_internal.h.
Referenced by absl::cord_internal::CordRepFlat::AllocatedSize(), absl::cord_internal::CordRepFlat::Capacity(), absl::cord_internal::Consume(), absl::cord_internal::EdgeData(), flat(), flat(), absl::cord_internal::CordRepBtree::GetAppendBuffer(), absl::cord_internal::InitializeCordRepExternal(), IsBtree(), IsCrc(), absl::cord_internal::IsDataEdge(), IsExternal(), IsFlat(), IsRing(), IsSubstring(), absl::cord_internal::LogFatalNodeType(), absl::cordrep_testing::MakeSubstring(), absl::cord_internal::CordRepFlat::NewImpl(), and absl::cord_internal::CordRepSubstring::Substring().
The documentation for this struct was generated from the following files:
open_spiel/abseil-cpp/absl/strings/internal/cord_internal.h
open_spiel/abseil-cpp/absl/strings/internal/cord_internal.cc
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_btree.h
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_crc.h
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_flat.h
open_spiel/abseil-cpp/absl/strings/internal/cord_rep_ring.h