open spiel: absl::container_internal::StringBtreeDefaultGreater Struct Reference
absl::container_internal::StringBtreeDefaultGreater Struct Reference
#include <btree.h>
Public Types
using is_transparent = void
Public Member Functions
StringBtreeDefaultGreater ()=default
StringBtreeDefaultGreater (std::greater< std::string >)
StringBtreeDefaultGreater (std::greater< absl::string_view >)
operator std::greater< std::string > () const
operator std::greater< absl::string_view > () const
operator std::greater< absl::Cord > () const
absl::weak_ordering operator() (absl::string_view lhs, absl::string_view rhs) const
StringBtreeDefaultGreater (std::greater< absl::Cord >)
absl::weak_ordering operator() (const absl::Cord &lhs, const absl::Cord &rhs) const
absl::weak_ordering operator() (const absl::Cord &lhs, absl::string_view rhs) const
absl::weak_ordering operator() (absl::string_view lhs, const absl::Cord &rhs) const
Detailed Description
Definition at line 131 of file btree.h.
Member Typedef Documentation
is_transparent
using absl::container_internal::StringBtreeDefaultGreater::is_transparent = void
Definition at line 132 of file btree.h.
Constructor & Destructor Documentation
StringBtreeDefaultGreater() [1/4]
absl::container_internal::StringBtreeDefaultGreater::StringBtreeDefaultGreater () default
StringBtreeDefaultGreater() [2/4]
absl::container_internal::StringBtreeDefaultGreater::StringBtreeDefaultGreater (std::greater< std::string >) inline
Definition at line 136 of file btree.h.
{}        // NOLINT
StringBtreeDefaultGreater() [3/4]
absl::container_internal::StringBtreeDefaultGreater::StringBtreeDefaultGreater (std::greater< absl::string_view >) inline
Definition at line 137 of file btree.h.
{}  // NOLINT
StringBtreeDefaultGreater() [4/4]
absl::container_internal::StringBtreeDefaultGreater::StringBtreeDefaultGreater (std::greater< absl::Cord >) inline
Definition at line 148 of file btree.h.
{}  // NOLINT
Member Function Documentation
operator std::greater< absl::Cord >()
absl::container_internal::StringBtreeDefaultGreater::operator std::greater< absl::Cord > () const inline explicit
Definition at line 142 of file btree.h.
{ return {}; }
operator std::greater< absl::string_view >()
absl::container_internal::StringBtreeDefaultGreater::operator std::greater< absl::string_view > () const inline explicit
Definition at line 141 of file btree.h.
{ return {}; }
operator std::greater< std::string >()
absl::container_internal::StringBtreeDefaultGreater::operator std::greater< std::string > () const inline explicit
Definition at line 140 of file btree.h.
{ return {}; }
operator()() [1/4]
absl::weak_ordering absl::container_internal::StringBtreeDefaultGreater::operator() (absl::string_view lhs, absl::string_view rhs) const inline
Definition at line 144 of file btree.h.
{
    return compare_internal::compare_result_as_ordering(rhs.compare(lhs));
  }
References absl::string_view::compare(), and absl::compare_internal::compare_result_as_ordering().
operator()() [2/4]
absl::weak_ordering absl::container_internal::StringBtreeDefaultGreater::operator() (absl::string_view lhs, const absl::Cord & rhs) const inline
Definition at line 157 of file btree.h.
{
    return compare_internal::compare_result_as_ordering(rhs.Compare(lhs));
  }
References absl::Cord::Compare(), and absl::compare_internal::compare_result_as_ordering().
operator()() [3/4]
absl::weak_ordering absl::container_internal::StringBtreeDefaultGreater::operator() (const absl::Cord & lhs, absl::string_view rhs) const inline
Definition at line 153 of file btree.h.
{
    return compare_internal::compare_result_as_ordering(-lhs.Compare(rhs));
  }
References absl::Cord::Compare(), and absl::compare_internal::compare_result_as_ordering().
operator()() [4/4]
absl::weak_ordering absl::container_internal::StringBtreeDefaultGreater::operator() (const absl::Cord & lhs, const absl::Cord & rhs) const inline
Definition at line 149 of file btree.h.
{
    return compare_internal::compare_result_as_ordering(rhs.Compare(lhs));
  }
References absl::Cord::Compare(), and absl::compare_internal::compare_result_as_ordering().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/btree.h