open spiel: absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned > Struct Template Reference
absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned > Struct Template Reference
#include <inlined_vector.h>
Static Public Member Functions
static Allocation< A > Allocate (A &allocator, SizeType< A > requested_capacity)
static void Deallocate (A &allocator, Pointer< A > pointer, SizeType< A > capacity)
Detailed Description
template<typename A, bool IsOverAligned = (alignof(ValueType<A>) > ABSL_INTERNAL_DEFAULT_NEW_ALIGNMENT)>
struct absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned >
Definition at line 135 of file inlined_vector.h.
Member Function Documentation
Allocate()
template<typename A , bool IsOverAligned = (alignof(ValueType<A>) > ABSL_INTERNAL_DEFAULT_NEW_ALIGNMENT)> static Allocation< A > absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned >::Allocate (A & allocator, SizeType< A > requested_capacity) inline static
Definition at line 136 of file inlined_vector.h.
{
    return {AllocatorTraits<A>::allocate(allocator, requested_capacity),
            requested_capacity};
  }
Referenced by absl::inlined_vector_internal::AllocationTransaction< A >::Allocate(), absl::inlined_vector_internal::Storage< T, N, A >::InitFrom(), and absl::inlined_vector_internal::Storage< T, N, A >::Initialize().
Deallocate()
template<typename A , bool IsOverAligned = (alignof(ValueType<A>) > ABSL_INTERNAL_DEFAULT_NEW_ALIGNMENT)> static void absl::inlined_vector_internal::MallocAdapter< A, IsOverAligned >::Deallocate (A & allocator, Pointer< A > pointer, SizeType< A > capacity) inline static
Definition at line 141 of file inlined_vector.h.
{
    AllocatorTraits<A>::deallocate(allocator, pointer, capacity);
  }
Referenced by absl::inlined_vector_internal::Storage< T, N, A >::DeallocateIfAllocated(), absl::inlined_vector_internal::Storage< T, N, A >::ShrinkToFit(), and absl::inlined_vector_internal::AllocationTransaction< A >::~AllocationTransaction().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/inlined_vector.h