open spiel: open_spiel::NoCompress Struct Reference
open_spiel::NoCompress Struct Reference
Static Public Member Functions
static std::string Compress (absl::Span< const float > buffer)
static void Decompress (absl::string_view compressed, absl::Span< float > buffer)
Detailed Description
Definition at line 287 of file observer.cc.
Member Function Documentation
Compress()
static std::string open_spiel::NoCompress::Compress (absl::Span< const float > buffer) inline static
Definition at line 288 of file observer.cc.
{
    const int num_bytes = sizeof(float) * buffer.size();
    std::string str(num_bytes + 1, '\0');
    str[0] = kCompressionNone;
    memcpy(&str[kNumHeaderBytes], &buffer[0], num_bytes);
    return str;
  }
References open_spiel::kCompressionNone, open_spiel::kNumHeaderBytes, and absl::Span< T >::size().
Referenced by open_spiel::Observation::Compress().
Decompress()
static void open_spiel::NoCompress::Decompress (absl::string_view compressed, absl::Span< float > buffer) inline static
Definition at line 296 of file observer.cc.
{
    const int num_bytes = sizeof(float) * buffer.size();
    SPIEL_CHECK_EQ(compressed.size(), num_bytes + kNumHeaderBytes);
    memcpy(&buffer[0], &compressed[kNumHeaderBytes], num_bytes);
  }
References open_spiel::kNumHeaderBytes, absl::Span< T >::size(), absl::string_view::size(), and SPIEL_CHECK_EQ.
Referenced by open_spiel::Observation::Decompress().
The documentation for this struct was generated from the following file:
open_spiel/observer.cc