open spiel: absl::types_internal::ExpectMoveConstructOneGenerator< T, Prof > Struct Template Reference
absl::types_internal::ExpectMoveConstructOneGenerator< T, Prof > Struct Template Reference
#include <conformance_testing.h>
Public Member Functions
template<class Fun >
void operator() (const Fun &generator) const
Public Attributes
ConformanceErrors * errors
Detailed Description
template<class T, class Prof>
struct absl::types_internal::ExpectMoveConstructOneGenerator< T, Prof >
Definition at line 297 of file conformance_testing.h.
Member Function Documentation
operator()()
template<class T , class Prof > template<class Fun > void absl::types_internal::ExpectMoveConstructOneGenerator< T, Prof >::operator() (const Fun & generator) const inline
Definition at line 299 of file conformance_testing.h.
{
    const T object = generator();
    const T moved_object = absl::move(generator());  // Force no elision.
    (ExpectEquality<T, Prof>)(errors, "Move construction",
                              PrepareGivenContext(
                                  GivenDeclaration{"const _T object",
                                                   generator.description},
                                  GivenDeclaration{"const _T moved_object",
                                                   std::string("std::move(") +
                                                       generator.description +
                                                       ")"}),
                              object, moved_object, "object", "moved_object");
  }
References absl::types_internal::ExpectMoveConstructOneGenerator< T, Prof >::errors, absl::types_internal::ExpectEquality(), absl::move(), and absl::types_internal::PrepareGivenContext().
Member Data Documentation
errors
template<class T , class Prof > ConformanceErrors* absl::types_internal::ExpectMoveConstructOneGenerator< T, Prof >::errors
Definition at line 314 of file conformance_testing.h.
Referenced by absl::types_internal::ExpectMoveConstructOneGenerator< T, Prof >::operator()().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/types/internal/conformance_testing.h