open spiel: pybind11::detail::type_caster< absl::Time > Struct Reference
pybind11::detail::type_caster< absl::Time > Struct Reference
#include <absl_casters.h>
Public Member Functions
PYBIND11_TYPE_CASTER (absl::Time, const_name("absl::Time"))
bool load (handle src, bool convert)
Static Public Member Functions
static handle cast (const absl::Time &src, return_value_policy, handle)
Detailed Description
Definition at line 156 of file absl_casters.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< absl::Time >::cast (const absl::Time & src, return_value_policy , handle) inline static
Definition at line 205 of file absl_casters.h.
{
    // This function truncates fractional microseconds as the python datetime
    // objects cannot support a resolution higher than this.
    auto py_datetime_t = module::import("datetime").attr("datetime");
    auto py_from_timestamp = py_datetime_t.attr("fromtimestamp");
    auto py_timezone_t = module::import("dateutil.tz").attr("gettz");
    auto py_timezone = py_timezone_t(absl::LocalTimeZone().name());
    double as_seconds = static_cast<double>(absl::ToUnixMicros(src)) / 1e6;
    auto py_datetime = py_from_timestamp(as_seconds, "tz"_a = py_timezone);
    return py_datetime.release();
  }
References absl::LocalTimeZone(), name, and absl::ToUnixMicros().
load()
bool pybind11::detail::type_caster< absl::Time >::load (handle src, bool convert) inline
Definition at line 163 of file absl_casters.h.
{
    // Ensure that absl::Duration is converted from a Python datetime.date.
    if (!convert || !hasattr(src, "year") || !hasattr(src, "month") ||
        !hasattr(src, "day")) {
      return false;
    }
    if (hasattr(src, "timestamp")) {
      // python datetime.datetime object
      double timestamp = src.attr("timestamp")().cast<double>();
      int64_t as_micros = static_cast<int64_t>(timestamp * 1e6);
      value = absl::FromUnixMicros(as_micros);
    }
#if PY_MAJOR_VERSION < 3
    else if (hasattr(src, "microsecond")) {  // NOLINT(readability/braces)
      // python datetime.datetime object
      // This doesn't rely on datetime.datetime.timestamp(), which is not
      // available in Python 2.
      auto utc = module::import("dateutil.tz").attr("UTC");
      auto datetime = module_::import("datetime").attr("datetime");
      auto gettz = module::import("dateutil.tz").attr("gettz");
      auto epoch_dt = datetime.attr("fromtimestamp")(0, utc);
      auto tz = (src.attr("tzinfo").is_none()) ? gettz() : src.attr("tzinfo");
      auto src_with_tz = src.attr("replace")("tzinfo"_a = tz);
      double timestamp =
          (src_with_tz - epoch_dt).attr("total_seconds")().cast<double>();
      int64_t as_micros = static_cast<int64_t>(timestamp * 1e6);
      value = absl::FromUnixMicros(as_micros);
    }
#endif
    else {  // NOLINT(readability/braces)
      // python datetime.date object
      absl::CivilDay civil_day(GetInt64Attr(src, "year"),
                               GetInt64Attr(src, "month"),
                               GetInt64Attr(src, "day"));
      value = absl::FromCivil(civil_day, GetTimeZone(src));
    }
    return true;
  }
References absl::FromCivil(), absl::FromUnixMicros(), pybind11::detail::GetInt64Attr(), and pybind11::detail::GetTimeZone().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< absl::Time >::PYBIND11_TYPE_CASTER (absl::Time , const_name("absl::Time"))
The documentation for this struct was generated from the following file:
open_spiel/pybind11_abseil/pybind11_abseil/absl_casters.h