open spiel: pybind11::detail::type_caster< absl::Duration > Struct Reference
pybind11::detail::type_caster< absl::Duration > Struct Reference
#include <absl_casters.h>
Public Member Functions
PYBIND11_TYPE_CASTER (absl::Duration, const_name("absl::Duration"))
bool load (handle src, bool convert)
Static Public Member Functions
static handle cast (const absl::Duration &src, return_value_policy, handle)
Detailed Description
Definition at line 110 of file absl_casters.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< absl::Duration >::cast (const absl::Duration & src, return_value_policy , handle) inline static
Definition at line 143 of file absl_casters.h.
{
    absl::Duration remainder;
    int64_t secs = absl::IDivDuration(src, absl::Seconds(1), &remainder);
    int64_t microsecs = absl::ToInt64Microseconds(remainder);
    auto py_duration_t = module::import("datetime").attr("timedelta");
    auto py_duration =
        py_duration_t(arg("seconds") = secs, arg("microseconds") = microsecs);
    return py_duration.release();
  }
References arg, absl::IDivDuration(), absl::Seconds(), and absl::ToInt64Microseconds().
load()
bool pybind11::detail::type_caster< absl::Duration >::load (handle src, bool convert) inline
Definition at line 117 of file absl_casters.h.
{
    if (!convert) {
      return false;
    }
    if (PyFloat_Check(src.ptr())) {
      value = absl::Seconds(src.cast<double>());
      return true;
    } else if (PyLong_Check(src.ptr())) {
      value = absl::Seconds(src.cast<int64_t>());
      return true;
    } else {
      // Ensure that absl::Duration is converted from a Python
      // datetime.timedelta.
      if (!hasattr(src, "days") || !hasattr(src, "seconds") ||
          !hasattr(src, "microseconds")) {
        return false;
      }
      value = absl::Hours(24 * GetInt64Attr(src, "days")) +
              absl::Seconds(GetInt64Attr(src, "seconds")) +
              absl::Microseconds(GetInt64Attr(src, "microseconds"));
      return true;
    }
    return false;
  }
References pybind11::detail::GetInt64Attr(), absl::Hours(), absl::Microseconds(), and absl::Seconds().
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< absl::Duration >::PYBIND11_TYPE_CASTER (absl::Duration , const_name("absl::Duration"))
The documentation for this struct was generated from the following file:
open_spiel/pybind11_abseil/pybind11_abseil/absl_casters.h