open spiel: absl::variant_internal::VisitIndicesFallback< EndIndices > Struct Template Reference
absl::variant_internal::VisitIndicesFallback< EndIndices > Struct Template Reference
#include <variant.h>
Static Public Member Functions
template<class Op , class... SizeT>
static VisitIndicesResultT< Op, SizeT... > Run (Op &&op, SizeT... indices)
Detailed Description
template<std::size_t... EndIndices>
struct absl::variant_internal::VisitIndicesFallback< EndIndices >
Definition at line 433 of file variant.h.
Member Function Documentation
Run()
template<std::size_t... EndIndices> template<class Op , class... SizeT> static VisitIndicesResultT< Op, SizeT... > absl::variant_internal::VisitIndicesFallback< EndIndices >::Run (Op && op, SizeT... indices) inline static
Definition at line 435 of file variant.h.
{
    return AccessSimpleArray(
        MakeVisitationMatrix<VisitIndicesResultT<Op, SizeT...>, Op,
                             index_sequence<(EndIndices + 1)...>,
                             index_sequence<>>::Run(),
        (indices + 1)...)(absl::forward<Op>(op));
  }
References absl::variant_internal::AccessSimpleArray(), absl::forward(), and absl::variant_internal::VisitIndicesFallback< EndIndices >::Run().
Referenced by absl::variant_internal::VisitIndicesFallback< EndIndices >::Run().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/types/internal/variant.h