open spiel: absl::container_internal::hash_policy_traits< Policy, class > Struct Template Reference
absl::container_internal::hash_policy_traits< Policy, class > Struct Template Reference
#include <hash_policy_traits.h>
Public Types
using key_type = typename Policy::key_type
using slot_type = typename Policy::slot_type
using init_type = typename Policy::init_type
using reference = decltype(Policy::element(std::declval<slot_type*>()))
using pointer = typename std::remove_reference<reference>::type*
using value_type = typename std::remove_reference<reference>::type
using constant_iterators = ConstantIteratorsImpl<>
Public Types inherited from absl::container_internal::common_policy_traits< Policy, class >
using slot_type = typename Policy::slot_type
using reference = decltype(Policy::element(std::declval<slot_type*>()))
using value_type = typename std::remove_reference<reference>::type
Static Public Member Functions
template<class P = Policy>
static size_t space_used (const slot_type *slot)
template<class F , class... Ts, class P = Policy>
static auto apply (F &&f, Ts &&... ts) -> decltype(P::apply(std::forward< F >(f), std::forward< Ts >(ts)...))
template<class P = Policy>
static auto mutable_key (slot_type *slot) -> decltype(P::apply(ReturnKey(), hash_policy_traits::element(slot)))
template<class T , class P = Policy>
static auto value (T *elem) -> decltype(P::value(elem))
Static Public Member Functions inherited from absl::container_internal::common_policy_traits< Policy, class >
template<class Alloc , class... Args>
static void construct (Alloc *alloc, slot_type *slot, Args &&... args)
template<class Alloc >
static void destroy (Alloc *alloc, slot_type *slot)
template<class Alloc >
static void transfer (Alloc *alloc, slot_type *new_slot, slot_type *old_slot)
template<class P = Policy>
static auto element (absl::remove_const_t< slot_type > *slot) -> decltype(P::element(slot))
template<class P = Policy>
static auto element (const slot_type *slot) -> decltype(P::element(slot))
static constexpr bool transfer_uses_memcpy ()
Detailed Description
template<class Policy, class = void>
struct absl::container_internal::hash_policy_traits< Policy, class >
Definition at line 33 of file hash_policy_traits.h.
Member Typedef Documentation
constant_iterators
template<class Policy , class = void> using absl::container_internal::hash_policy_traits< Policy, class >::constant_iterators = ConstantIteratorsImpl<>
Definition at line 89 of file hash_policy_traits.h.
init_type
template<class Policy , class = void> using absl::container_internal::hash_policy_traits< Policy, class >::init_type = typename Policy::init_type
Definition at line 79 of file hash_policy_traits.h.
key_type
template<class Policy , class = void> using absl::container_internal::hash_policy_traits< Policy, class >::key_type = typename Policy::key_type
Definition at line 35 of file hash_policy_traits.h.
pointer
template<class Policy , class = void> using absl::container_internal::hash_policy_traits< Policy, class >::pointer = typename std::remove_reference<reference>::type*
Definition at line 82 of file hash_policy_traits.h.
reference
template<class Policy , class = void> using absl::container_internal::hash_policy_traits< Policy, class >::reference = decltype(Policy::element(std::declval<slot_type*>()))
Definition at line 81 of file hash_policy_traits.h.
slot_type
template<class Policy , class = void> using absl::container_internal::hash_policy_traits< Policy, class >::slot_type = typename Policy::slot_type
Definition at line 74 of file hash_policy_traits.h.
value_type
template<class Policy , class = void> using absl::container_internal::hash_policy_traits< Policy, class >::value_type = typename std::remove_reference<reference>::type
Definition at line 83 of file hash_policy_traits.h.
Member Function Documentation
apply()
template<class Policy , class = void> template<class F , class... Ts, class P = Policy> static auto absl::container_internal::hash_policy_traits< Policy, class >::apply (F && f, Ts &&... ts) -> decltype(P::apply(std::forward<F>(f), std::forward<Ts>(ts)...)) inline static
Definition at line 132 of file hash_policy_traits.h.
{
    return P::apply(std::forward<F>(f), std::forward<Ts>(ts)...);
  }
References absl::f.
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::emplace_at(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::find_or_prepare_insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert(), absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::merge(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::raw_hash_set().
mutable_key()
template<class Policy , class = void> template<class P = Policy> static auto absl::container_internal::hash_policy_traits< Policy, class >::mutable_key (slot_type * slot) -> decltype(P::apply(ReturnKey(), hash_policy_traits::element(slot))) inline static
Definition at line 140 of file hash_policy_traits.h.
{
    return P::apply(ReturnKey(), hash_policy_traits::element(slot));
  }
References absl::container_internal::common_policy_traits< Policy, class >::element().
space_used()
template<class Policy , class = void> template<class P = Policy> static size_t absl::container_internal::hash_policy_traits< Policy, class >::space_used (const slot_type * slot) inline static
Definition at line 98 of file hash_policy_traits.h.
{
    return P::space_used(slot);
  }
value()
template<class Policy , class = void> template<class T , class P = Policy> static auto absl::container_internal::hash_policy_traits< Policy, class >::value (T * elem) -> decltype(P::value(elem)) inline static
Definition at line 148 of file hash_policy_traits.h.
{
    return P::value(elem);
  }
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/hash_policy_traits.h