open spiel: absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > > Struct Template Reference
absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > > Struct Template Reference
#include <raw_hash_set.h>
Public Types
using Traits = typename Set::PolicyTraits
using Slot = typename Traits::slot_type
Static Public Member Functions
static size_t GetNumProbes (const Set &set, const typename Set::key_type &key)
static size_t AllocatedByteSize (const Set &c)
static size_t LowerBoundAllocatedByteSize (size_t size)
Detailed Description
template<typename Set>
struct absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >
Definition at line 2619 of file raw_hash_set.h.
Member Typedef Documentation
Slot
template<typename Set > using absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::Slot = typename Traits::slot_type
Definition at line 2621 of file raw_hash_set.h.
Traits
template<typename Set > using absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::Traits = typename Set::PolicyTraits
Definition at line 2620 of file raw_hash_set.h.
Member Function Documentation
AllocatedByteSize()
template<typename Set > static size_t absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::AllocatedByteSize (const Set & c) inline static
Definition at line 2645 of file raw_hash_set.h.
{
    size_t capacity = c.capacity();
    if (capacity == 0) return 0;
    size_t m = AllocSize(capacity, sizeof(Slot), alignof(Slot));
    size_t per_slot = Traits::space_used(static_cast<const Slot*>(nullptr));
    if (per_slot != ~size_t{}) {
      m += per_slot * c.size();
    } else {
      const ctrl_t* ctrl = c.control();
      for (size_t i = 0; i != capacity; ++i) {
        if (container_internal::IsFull(ctrl[i])) {
          m += Traits::space_used(c.slot_array() + i);
        }
      }
    }
    return m;
  }
References absl::container_internal::AllocSize(), absl::c, and i.
GetNumProbes()
template<typename Set > static size_t absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::GetNumProbes (const Set & set, const typename Set::key_type & key) inline static
Definition at line 2623 of file raw_hash_set.h.
{
    size_t num_probes = 0;
    size_t hash = set.hash_ref()(key);
    auto seq = probe(set.common(), hash);
    const ctrl_t* ctrl = set.control();
    while (true) {
      container_internal::Group g{ctrl + seq.offset()};
      for (uint32_t i : g.Match(container_internal::H2(hash))) {
        if (Traits::apply(
                typename Set::template EqualElement<typename Set::key_type>{
                    key, set.eq_ref()},
                Traits::element(set.slot_array() + seq.offset(i))))
          return num_probes;
        ++num_probes;
      }
      if (g.MaskEmpty()) return num_probes;
      seq.next();
      ++num_probes;
    }
  }
References absl::g, hash, i, key, and absl::container_internal::probe().
LowerBoundAllocatedByteSize()
template<typename Set > static size_t absl::container_internal::hashtable_debug_internal::HashtableDebugAccess< Set, absl::void_t< typename Set::raw_hash_set > >::LowerBoundAllocatedByteSize (size_t size) inline static
Definition at line 2664 of file raw_hash_set.h.
{
    size_t capacity = GrowthToLowerboundCapacity(size);
    if (capacity == 0) return 0;
    size_t m =
        AllocSize(NormalizeCapacity(capacity), sizeof(Slot), alignof(Slot));
    size_t per_slot = Traits::space_used(static_cast<const Slot*>(nullptr));
    if (per_slot != ~size_t{}) {
      m += per_slot * size;
    }
    return m;
  }
References absl::container_internal::AllocSize(), absl::container_internal::GrowthToLowerboundCapacity(), absl::container_internal::NormalizeCapacity(), and size.
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/raw_hash_set.h