open spiel: absl::span_internal::IsView< T, absl::void_t< decltype(span_internal::GetData(std::declval< const T & >()))>, absl::void_t< decltype(span_internal::GetData(std::declval< T & >()))> > Struct Template Reference
absl::span_internal::IsView< T, absl::void_t< decltype(span_internal::GetData(std::declval< const T & >()))>, absl::void_t< decltype(span_internal::GetData(std::declval< T & >()))> > Struct Template Reference
#include <span.h>
Static Public Attributes
static constexpr bool value = std::is_same<ConstData, MutData>::value
Detailed Description
template<typename T>
struct absl::span_internal::IsView< T, absl::void_t< decltype(span_internal::GetData(std::declval< const T & >()))>, absl::void_t< decltype(span_internal::GetData(std::declval< T & >()))> >
Definition at line 115 of file span.h.
Member Data Documentation
value
template<typename T > bool absl::span_internal::IsView< T, absl::void_t< decltype(span_internal::GetData(std::declval< const T & >()))>, absl::void_t< decltype(span_internal::GetData(std::declval< T & >()))> >::value = std::is_same<ConstData, MutData>::value static constexpr
Definition at line 124 of file span.h.
Referenced by open_spiel.python.algorithms.alpha_zero.model.Losses::__add__(), open_spiel.python.mfg.algorithms.utils.MixedDistribution::__call__(), open_spiel.python.mfg.distribution.Distribution::__call__(), open_spiel.python.mfg.value.ValueFunction::__call__(), open_spiel.python.utils.shared_value.SharedValue::__deepcopy__(), open_spiel.python.algorithms.alpha_zero.model.Losses::__truediv__(), open_spiel.python.mfg.algorithms.mirror_descent.ProjectedPolicy::action_probabilities(), open_spiel.python.mfg.algorithms.munchausen_mirror_descent.ProjectedPolicyMunchausen::action_probabilities(), open_spiel.python.mfg.value.ValueFunction::add_value(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::evaluator(), open_spiel.python.examples.twenty_forty_eight_td_n_tuple_network.NTupleNetwork::learn(), open_spiel.python.algorithms.best_response.BestResponsePolicy::q_value(), open_spiel.python.algorithms.best_response.CPPBestResponsePolicy::q_value(), and open_spiel.python.algorithms.alpha_zero.model.Losses::total().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/types/internal/span.h