open spiel: absl::variant_internal::UnreachableSwitchCase Struct Reference
absl::variant_internal::UnreachableSwitchCase Struct Reference
#include <variant.h>
Static Public Member Functions
template<class Op >
static VisitIndicesResultT< Op, std::size_t > Run (Op &&)
Detailed Description
Definition at line 271 of file variant.h.
Member Function Documentation
Run()
template<class Op > static VisitIndicesResultT< Op, std::size_t > absl::variant_internal::UnreachableSwitchCase::Run (Op &&) inline static
Definition at line 273 of file variant.h.
              {
#if ABSL_HAVE_BUILTIN(__builtin_unreachable) || \
    (defined(__GNUC__) && !defined(__clang__))
    __builtin_unreachable();
#elif defined(_MSC_VER)
    __assume(false);
#else
    // Try to use assert of false being identified as an unreachable intrinsic.
    // NOTE: We use assert directly to increase chances of exploiting an assume
    //       intrinsic.
    assert(false);  // NOLINT
    // Hack to silence potential no return warning -- cause an infinite loop.
    return Run(absl::forward<Op>(op));
#endif  // Checks for __builtin_unreachable
  }
References absl::forward(), and Run().
Referenced by Run().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/types/internal/variant.h