open spiel: pybind11::detail::type_caster< open_spiel::GameParameter > Struct Reference
pybind11::detail::type_caster< open_spiel::GameParameter > Struct Reference
#include <pybind11.h>
Public Member Functions
PYBIND11_TYPE_CASTER (open_spiel::GameParameter, _("GameParameter"))
bool load (handle src, bool convert)
Static Public Member Functions
static handle cast (const open_spiel::GameParameter &gp, return_value_policy policy, handle parent)
Detailed Description
Definition at line 222 of file pybind11.h.
Member Function Documentation
cast()
static handle pybind11::detail::type_caster< open_spiel::GameParameter >::cast (const open_spiel::GameParameter & gp, return_value_policy policy, handle parent) inline static
Definition at line 253 of file pybind11.h.
{
    if (gp.has_bool_value()) {
      return pybind11::bool_(gp.bool_value()).release();
    } else if (gp.has_double_value()) {
      return pybind11::float_(gp.double_value()).release();
    } else if (gp.has_string_value()) {
      return pybind11::str(gp.string_value()).release();
    } else if (gp.has_int_value()) {
      return pybind11::int_(gp.int_value()).release();
    } else if (gp.has_game_value()) {
      pybind11::dict d;
      for (const auto& [k, v] : gp.game_value()) {
        d[pybind11::str(k)] = pybind11::cast(v);
      }
      return d.release();
    } else {
      return pybind11::none();
    }
  }
References open_spiel::GameParameter::bool_value(), open_spiel::GameParameter::double_value(), open_spiel::GameParameter::game_value(), open_spiel::GameParameter::has_bool_value(), open_spiel::GameParameter::has_double_value(), open_spiel::GameParameter::has_game_value(), open_spiel::GameParameter::has_int_value(), open_spiel::GameParameter::has_string_value(), open_spiel::GameParameter::int_value(), and open_spiel::GameParameter::string_value().
load()
bool pybind11::detail::type_caster< open_spiel::GameParameter >::load (handle src, bool convert) inline
Definition at line 226 of file pybind11.h.
{
    if (src.is_none()) {
      // value is default-constructed to an unset value
      return true;
    } else if (PyBool_Check(src.ptr())) {
      value = open_spiel::GameParameter(src.cast<bool>());
      return true;
    } else if (auto str_val = maybe_load<std::string>(src, convert)) {
      value = open_spiel::GameParameter(*str_val);
      return true;
    } else if (PyFloat_Check(src.ptr())) {
      value = open_spiel::GameParameter(src.cast<double>());
      return true;
    } else if (PyLong_Check(src.ptr())) {
      value = open_spiel::GameParameter(src.cast<int>());
      return true;
    } else {
      auto dict = src.cast<pybind11::dict>();
      std::map<std::string, open_spiel::GameParameter> d;
      for (const auto& [k, v] : dict) {
        d[k.cast<std::string>()] = v.cast<open_spiel::GameParameter>();
      }
      value = open_spiel::GameParameter(d);
      return true;
    }
  }
PYBIND11_TYPE_CASTER()
pybind11::detail::type_caster< open_spiel::GameParameter >::PYBIND11_TYPE_CASTER (open_spiel::GameParameter , _("GameParameter"))
The documentation for this struct was generated from the following file:
open_spiel/python/pybind11/pybind11.h