open spiel: absl::log_internal::WriteEntryToStderr Struct Reference
absl::log_internal::WriteEntryToStderr Struct Reference final
#include <test_actions.h>
Public Member Functions
WriteEntryToStderr (absl::string_view m)
void operator() (const absl::LogEntry &entry) const
void operator() (absl::LogSeverity, absl::string_view, absl::string_view) const
Public Attributes
std::string message = ""
Detailed Description
Definition at line 62 of file test_actions.h.
Constructor & Destructor Documentation
WriteEntryToStderr()
absl::log_internal::WriteEntryToStderr::WriteEntryToStderr (absl::string_view m) inline explicit
Definition at line 63 of file test_actions.h.
: message(m) {}
Member Function Documentation
operator()() [1/2]
void absl::log_internal::WriteEntryToStderr::operator() (absl::LogSeverity severity, absl::string_view filename, absl::string_view log_message) const
Definition at line 60 of file test_actions.cc.
{
  if (!message.empty()) std::cerr << message << "\n";
  const std::string source_filename = absl::CHexEscape(filename);
  const std::string text_message = absl::CHexEscape(log_message);
  std::cerr << "LogEntry{\n"                                         //
            << "  source_filename: \"" << source_filename << "\"\n"  //
            << "  log_severity: " << severity << "\n"                //
            << "  text_message: \"" << text_message << "\"\n"        //
            << "}\n";
}
References absl::CHexEscape(), and message.
operator()() [2/2]
void absl::log_internal::WriteEntryToStderr::operator() (const absl::LogEntry & entry) const
Definition at line 38 of file test_actions.cc.
{
  if (!message.empty()) std::cerr << message << "\n";
  const std::string source_filename = absl::CHexEscape(entry.source_filename());
  const std::string source_basename = absl::CHexEscape(entry.source_basename());
  const std::string text_message = absl::CHexEscape(entry.text_message());
  const std::string encoded_message = absl::CHexEscape(entry.encoded_message());
  std::string encoded_message_str;
  std::cerr << "LogEntry{\n"                                               //
            << "  source_filename: \"" << source_filename << "\"\n"        //
            << "  source_basename: \"" << source_basename << "\"\n"        //
            << "  source_line: " << entry.source_line() << "\n"            //
            << "  prefix: " << (entry.prefix() ? "true\n" : "false\n")     //
            << "  log_severity: " << entry.log_severity() << "\n"          //
            << "  timestamp: " << entry.timestamp() << "\n"                //
            << "  text_message: \"" << text_message << "\"\n"              //
            << "  verbosity: " << entry.verbosity() << "\n"                //
            << "  encoded_message (raw): \"" << encoded_message << "\"\n"  //
            << encoded_message_str                                         //
            << "}\n";
}
References absl::CHexEscape(), absl::LogEntry::encoded_message(), absl::LogEntry::log_severity(), message, absl::LogEntry::prefix(), absl::LogEntry::source_basename(), absl::LogEntry::source_filename(), absl::LogEntry::source_line(), absl::LogEntry::text_message(), absl::LogEntry::timestamp(), and absl::LogEntry::verbosity().
Member Data Documentation
message
std::string absl::log_internal::WriteEntryToStderr::message = ""
Definition at line 65 of file test_actions.h.
Referenced by operator()(), and operator()().
The documentation for this struct was generated from the following files:
open_spiel/abseil-cpp/absl/log/internal/test_actions.h
open_spiel/abseil-cpp/absl/log/internal/test_actions.cc