open spiel: str_format_internal::ParsedFormatBase::ParsedFormatConsumer Struct Reference
str_format_internal::ParsedFormatBase::ParsedFormatConsumer Struct Reference
Public Member Functions
ParsedFormatConsumer (ParsedFormatBase *parsedformat)
bool Append (string_view s)
bool ConvertOne (const UnboundConversion &conv, string_view s)
size_t AppendText (string_view s)
Public Attributes
ParsedFormatBase * parsed
char * data_pos
Detailed Description
Definition at line 68 of file parser.cc.
Constructor & Destructor Documentation
ParsedFormatConsumer()
str_format_internal::ParsedFormatBase::ParsedFormatConsumer::ParsedFormatConsumer (ParsedFormatBase * parsedformat) inline explicit
Definition at line 69 of file parser.cc.
      : parsed(parsedformat), data_pos(parsedformat->data_.get()) {}
References str_format_internal::ParsedFormatBase::ParsedFormatConsumer::data_pos, and str_format_internal::ParsedFormatBase::ParsedFormatConsumer::parsed.
Member Function Documentation
Append()
bool str_format_internal::ParsedFormatBase::ParsedFormatConsumer::Append (string_view s) inline
Definition at line 72 of file parser.cc.
{
    if (s.empty()) return true;
    size_t text_end = AppendText(s);
    if (!parsed->items_.empty() && !parsed->items_.back().is_conversion) {
      // Let's extend the existing text run.
      parsed->items_.back().text_end = text_end;
    } else {
      // Let's make a new text run.
      parsed->items_.push_back({false, text_end, {}});
    }
    return true;
  }
References str_format_internal::ParsedFormatBase::ParsedFormatConsumer::AppendText(), and str_format_internal::ParsedFormatBase::ParsedFormatConsumer::parsed.
AppendText()
size_t str_format_internal::ParsedFormatBase::ParsedFormatConsumer::AppendText (string_view s) inline
Definition at line 93 of file parser.cc.
{
    memcpy(data_pos, s.data(), s.size());
    data_pos += s.size();
    return static_cast<size_t>(data_pos - parsed->data_.get());
  }
References str_format_internal::ParsedFormatBase::ParsedFormatConsumer::data_pos, and str_format_internal::ParsedFormatBase::ParsedFormatConsumer::parsed.
Referenced by str_format_internal::ParsedFormatBase::ParsedFormatConsumer::Append(), and str_format_internal::ParsedFormatBase::ParsedFormatConsumer::ConvertOne().
ConvertOne()
bool str_format_internal::ParsedFormatBase::ParsedFormatConsumer::ConvertOne (const UnboundConversion & conv, string_view s) inline
Definition at line 87 of file parser.cc.
{
    size_t text_end = AppendText(s);
    parsed->items_.push_back({true, text_end, conv});
    return true;
  }
References str_format_internal::ParsedFormatBase::ParsedFormatConsumer::AppendText(), conv, and str_format_internal::ParsedFormatBase::ParsedFormatConsumer::parsed.
Member Data Documentation
data_pos
char* str_format_internal::ParsedFormatBase::ParsedFormatConsumer::data_pos
Definition at line 100 of file parser.cc.
Referenced by str_format_internal::ParsedFormatBase::ParsedFormatConsumer::AppendText(), and str_format_internal::ParsedFormatBase::ParsedFormatConsumer::ParsedFormatConsumer().
parsed
ParsedFormatBase* str_format_internal::ParsedFormatBase::ParsedFormatConsumer::parsed
Definition at line 99 of file parser.cc.
Referenced by str_format_internal::ParsedFormatBase::ParsedFormatConsumer::Append(), str_format_internal::ParsedFormatBase::ParsedFormatConsumer::AppendText(), str_format_internal::ParsedFormatBase::ParsedFormatConsumer::ConvertOne(), and str_format_internal::ParsedFormatBase::ParsedFormatConsumer::ParsedFormatConsumer().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/strings/internal/str_format/parser.cc