open spiel: open_spiel::BinaryCompress Struct Reference
open_spiel::BinaryCompress Struct Reference
Static Public Member Functions
static std::string Compress (absl::Span< const float > buffer)
static void Decompress (absl::string_view compressed, absl::Span< float > buffer)
Static Public Attributes
static constexpr int kBitsPerByte = 8
Detailed Description
Definition at line 253 of file observer.cc.
Member Function Documentation
Compress()
static std::string open_spiel::BinaryCompress::Compress (absl::Span< const float > buffer) inline static
Definition at line 256 of file observer.cc.
{
    const int num_bytes = (buffer.size() + kBitsPerByte - 1) / kBitsPerByte;
    std::string str(num_bytes + kNumHeaderBytes, '\0');
    str[0] = kCompressionBinary;
    for (int i = 0; i < buffer.size(); ++i) {
      if (buffer[i]) {
        const int byte = i / kBitsPerByte;
        const int bit = i % kBitsPerByte;
        str[kNumHeaderBytes + byte] += (1 << bit);
      }
    }
    return str;
  }
References i, kBitsPerByte, open_spiel::kCompressionBinary, open_spiel::kNumHeaderBytes, and absl::Span< T >::size().
Referenced by open_spiel::Observation::Compress().
Decompress()
static void open_spiel::BinaryCompress::Decompress (absl::string_view compressed, absl::Span< float > buffer) inline static
Definition at line 271 of file observer.cc.
{
    const int num_bytes = (buffer.size() + kBitsPerByte - 1) / kBitsPerByte;
    absl::c_fill(buffer, 0);
    SPIEL_CHECK_EQ(compressed.size(), num_bytes + kNumHeaderBytes);
    for (int byte = 0; byte < num_bytes; ++byte) {
      for (int bit = 0; bit < kBitsPerByte; ++bit) {
        if (compressed[kNumHeaderBytes + byte] & (1 << bit)) {
          buffer[byte * kBitsPerByte + bit] = 1;
        }
      }
    }
  }
References absl::c_fill(), kBitsPerByte, open_spiel::kNumHeaderBytes, absl::Span< T >::size(), absl::string_view::size(), and SPIEL_CHECK_EQ.
Referenced by open_spiel::Observation::Decompress().
Member Data Documentation
kBitsPerByte
int open_spiel::BinaryCompress::kBitsPerByte = 8 static constexpr
Definition at line 254 of file observer.cc.
Referenced by Compress(), and Decompress().
The documentation for this struct was generated from the following file:
open_spiel/observer.cc