open spiel: absl::log_internal::LogMessage::LogMessageData Struct Reference
absl::log_internal::LogMessage::LogMessageData Struct Reference final
Public Member Functions
LogMessageData (const char *file, int line, absl::LogSeverity severity, absl::Time timestamp)
LogMessageData (const LogMessageData &)=delete
LogMessageData & operator= (const LogMessageData &)=delete
void FinalizeEncodingAndFormat ()
Public Attributes
absl::LogEntry entry
bool first_fatal
bool fail_quietly
bool is_perror
absl::InlinedVector< absl::LogSink *, 16 > extra_sinks
bool extra_sinks_only
std::ostream manipulated
std::array< char, kLogMessageBufferSize > encoded_buf
absl::Span< char > encoded_remaining
std::array< char, kLogMessageBufferSize > string_buf
Detailed Description
Definition at line 122 of file log_message.cc.
Constructor & Destructor Documentation
LogMessageData() [1/2]
absl::log_internal::LogMessage::LogMessageData::LogMessageData (const char * file, int line, absl::LogSeverity severity, absl::Time timestamp)
Definition at line 161 of file log_message.cc.
    : extra_sinks_only(false),
      manipulated(nullptr),
      // This `absl::MakeSpan` silences spurious -Wuninitialized from GCC:
      encoded_remaining(absl::MakeSpan(encoded_buf)) {
  // Legacy defaults for LOG's ostream:
  manipulated.setf(std::ios_base::showbase | std::ios_base::boolalpha);
  entry.full_filename_ = file;
  entry.base_filename_ = Basename(file);
  entry.line_ = line;
  entry.prefix_ = absl::ShouldPrependLogPrefix();
  entry.severity_ = absl::NormalizeLogSeverity(severity);
  entry.verbose_level_ = absl::LogEntry::kNoVerbosityLevel;
  entry.timestamp_ = timestamp;
  entry.tid_ = absl::base_internal::GetCachedTID();
}
References entry, absl::base_internal::GetCachedTID(), absl::LogEntry::kNoVerbosityLevel, manipulated, absl::NormalizeLogSeverity(), and absl::ShouldPrependLogPrefix().
LogMessageData() [2/2]
absl::log_internal::LogMessage::LogMessageData::LogMessageData (const LogMessageData &) delete
Member Function Documentation
FinalizeEncodingAndFormat()
void absl::log_internal::LogMessage::LogMessageData::FinalizeEncodingAndFormat ()
Definition at line 180 of file log_message.cc.
{
  // Note that `encoded_remaining` may have zero size without pointing past the
  // end of `encoded_buf`, so the difference between `data()` pointers is used
  // to compute the size of `encoded_data`.
  absl::Span<const char> encoded_data(
      encoded_buf.data(),
      static_cast<size_t>(encoded_remaining.data() - encoded_buf.data()));
  // `string_remaining` is the suffix of `string_buf` that has not been filled
  // yet.
  absl::Span<char> string_remaining(string_buf);
  // We may need to write a newline and nul-terminator at the end of the decoded
  // string data.  Rather than worry about whether those should overwrite the
  // end of the string (if the buffer is full) or be appended, we avoid writing
  // into the last two bytes so we always have space to append.
  string_remaining.remove_suffix(2);
  entry.prefix_len_ =
      entry.prefix() ? log_internal::FormatLogPrefix(
                           entry.log_severity(), entry.timestamp(), entry.tid(),
                           entry.source_basename(), entry.source_line(),
                           log_internal::ThreadIsLoggingToLogSink()
                               ? PrefixFormat::kRaw
                               : PrefixFormat::kNotRaw,
                           string_remaining)
                     : 0;
  // Decode data from `encoded_buf` until we run out of data or we run out of
  // `string_remaining`.
  ProtoField field;
  while (field.DecodeFrom(&encoded_data)) {
    switch (field.tag()) {
      case EventTag::kValue:
        if (field.type() != WireType::kLengthDelimited) continue;
        if (PrintValue(string_remaining, field.bytes_value())) continue;
        break;
    }
    break;
  }
  auto chars_written =
      static_cast<size_t>(string_remaining.data() - string_buf.data());
    string_buf[chars_written++] = '\n';
  string_buf[chars_written++] = '\0';
  entry.text_message_with_prefix_and_newline_and_nul_ =
      absl::MakeSpan(string_buf).subspan(0, chars_written);
}
References absl::log_internal::ProtoField::bytes_value(), absl::Span< T >::data(), absl::log_internal::ProtoField::DecodeFrom(), absl::log_internal::FormatLogPrefix(), absl::log_internal::kLengthDelimited, absl::log_internal::kNotRaw, absl::log_internal::kRaw, absl::MakeSpan(), absl::Span< T >::remove_suffix(), absl::log_internal::ProtoField::tag(), absl::log_internal::ThreadIsLoggingToLogSink(), and absl::log_internal::ProtoField::type().
operator=()
LogMessageData & absl::log_internal::LogMessage::LogMessageData::operator= (const LogMessageData &) delete
Member Data Documentation
encoded_buf
std::array<char, kLogMessageBufferSize> absl::log_internal::LogMessage::LogMessageData::encoded_buf
Definition at line 147 of file log_message.cc.
encoded_remaining
absl::Span<char> absl::log_internal::LogMessage::LogMessageData::encoded_remaining
Definition at line 153 of file log_message.cc.
entry
absl::LogEntry absl::log_internal::LogMessage::LogMessageData::entry
Definition at line 129 of file log_message.cc.
Referenced by LogMessageData().
extra_sinks
absl::InlinedVector<absl::LogSink*, 16> absl::log_internal::LogMessage::LogMessageData::extra_sinks
Definition at line 139 of file log_message.cc.
extra_sinks_only
bool absl::log_internal::LogMessage::LogMessageData::extra_sinks_only
Definition at line 142 of file log_message.cc.
fail_quietly
bool absl::log_internal::LogMessage::LogMessageData::fail_quietly
Definition at line 134 of file log_message.cc.
first_fatal
bool absl::log_internal::LogMessage::LogMessageData::first_fatal
Definition at line 132 of file log_message.cc.
is_perror
bool absl::log_internal::LogMessage::LogMessageData::is_perror
Definition at line 136 of file log_message.cc.
manipulated
std::ostream absl::log_internal::LogMessage::LogMessageData::manipulated
Definition at line 144 of file log_message.cc.
Referenced by LogMessageData().
string_buf
std::array<char, kLogMessageBufferSize> absl::log_internal::LogMessage::LogMessageData::string_buf
Definition at line 156 of file log_message.cc.
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/log/internal/log_message.cc