open spiel: absl::types_internal::ExpectSameHash Struct Reference
absl::types_internal::ExpectSameHash Struct Reference
#include <conformance_testing.h>
Public Member Functions
template<class T >
void operator() (absl::string_view test_name, absl::string_view context, const T &lhs, const T &rhs, absl::string_view lhs_name, absl::string_view rhs_name) const
Public Attributes
ConformanceErrors * errors
Detailed Description
Definition at line 220 of file conformance_testing.h.
Member Function Documentation
operator()()
template<class T > void absl::types_internal::ExpectSameHash::operator() (absl::string_view test_name, absl::string_view context, const T & lhs, const T & rhs, absl::string_view lhs_name, absl::string_view rhs_name) const inline
Definition at line 222 of file conformance_testing.h.
{
    if (std::hash<T>()(lhs) != std::hash<T>()(rhs)) {
      errors->addTestFailure(
          test_name, absl::StrCat(context,
                                  "**Unexpected hash result**\n"
                                  "\n"
                                  "Expression:\n"
                                  "  std::hash<T>()(",
                                  lhs_name, ") == std::hash<T>()(", rhs_name,
                                  ")\n"
                                  "\n"
                                  "Expected: true\n"
                                  "  Actual: false"));
    } else {
      errors->addTestSuccess(test_name);
    }
  }
References absl::types_internal::ConformanceErrors::addTestFailure(), absl::types_internal::ConformanceErrors::addTestSuccess(), errors, and absl::StrCat().
Member Data Documentation
errors
ConformanceErrors* absl::types_internal::ExpectSameHash::errors
Definition at line 242 of file conformance_testing.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/types/internal/conformance_testing.h