open spiel: open_spiel::gin_rummy::GinRummyUtils Struct Reference
open_spiel::gin_rummy::GinRummyUtils Struct Reference
#include <gin_rummy_utils.h>
Public Member Functions
GinRummyUtils (int num_ranks, int num_suits, int hand_size)
std::string CardString (absl::optional< int > card) const
std::string HandToString (const VecInt &cards) const
int CardInt (std::string card) const
std::vector< std::string > CardIntsToCardStrings (const VecInt &cards) const
VecInt CardStringsToCardInts (const std::vector< std::string > &cards) const
int CardValue (int card_index) const
int TotalCardValue (const VecInt &cards) const
int TotalCardValue (const VecVecInt &meld_group) const
int CardRank (const int card_index) const
int CardSuit (const int card_index) const
bool IsConsecutive (const VecInt &v) const
bool IsRankMeld (const VecInt &cards) const
bool IsSuitMeld (const VecInt &cards) const
VecVecInt RankMelds (VecInt cards) const
VecVecInt SuitMelds (VecInt cards) const
VecVecInt AllMelds (const VecInt &cards) const
bool VectorsIntersect (VecInt *v1, VecInt *v2) const
VecVecInt NonOverlappingMelds (VecInt *meld, VecVecInt *melds) const
void AllPaths (VecInt *meld, VecVecInt *all_melds, VecVecInt *path, VecVecVecInt *all_paths) const
VecVecVecInt AllMeldGroups (const VecInt &cards) const
VecVecInt BestMeldGroup (const VecInt &cards) const
int MinDeadwood (VecInt hand, absl::optional< int > card) const
int MinDeadwood (const VecInt &hand) const
int RankMeldLayoff (const VecInt &meld) const
VecInt SuitMeldLayoffs (const VecInt &meld) const
VecInt LegalMelds (const VecInt &hand, int knock_card) const
VecInt LegalDiscards (const VecInt &hand, int knock_card) const
VecInt AllLayoffs (const VecInt &layed_melds, const VecInt &previous_layoffs) const
int MeldToInt (VecInt meld) const
std::map< VecInt, int > BuildMeldToIntMap () const
std::map< int, VecInt > BuildIntToMeldMap () const
Public Attributes
const int num_ranks
const int num_suits
const int num_cards
const int hand_size
const SuitComparator suit_comp
const RankComparator rank_comp
const std::map< int, VecInt > int_to_meld
const std::map< VecInt, int > meld_to_int
Detailed Description
Definition at line 56 of file gin_rummy_utils.h.
Constructor & Destructor Documentation
GinRummyUtils()
open_spiel::gin_rummy::GinRummyUtils::GinRummyUtils (int num_ranks, int num_suits, int hand_size)
Definition at line 27 of file gin_rummy_utils.cc.
                                                                        :
      num_ranks(num_ranks),
      num_suits(num_suits),
      num_cards(num_ranks * num_suits),
      hand_size(hand_size),
      suit_comp(SuitComparator(num_ranks)),
      rank_comp(RankComparator(num_ranks)),
      int_to_meld(BuildIntToMeldMap()),
      meld_to_int(BuildMeldToIntMap()) {
}
Member Function Documentation
AllLayoffs()
VecInt open_spiel::gin_rummy::GinRummyUtils::AllLayoffs (const VecInt & layed_melds, const VecInt & previous_layoffs) const
Definition at line 408 of file gin_rummy_utils.cc.
{
  std::set<int> layoffs;
  for (int meld_id : layed_melds) {
    VecInt meld = int_to_meld.at(meld_id);
    if (IsRankMeld(meld) && meld.size() == 3) {
      layoffs.insert(RankMeldLayoff(meld));
    } else if (IsSuitMeld(meld)) {
      VecInt suit_layoffs = SuitMeldLayoffs(meld);
      for (int card : previous_layoffs) {
        if (absl::c_linear_search(suit_layoffs, card)) {
          meld.push_back(card);
        }
      }
      suit_layoffs = SuitMeldLayoffs(meld);
      for (int card : suit_layoffs) {
        layoffs.insert(card);
      }
    }
  }
  return VecInt(layoffs.begin(), layoffs.end());
}
References absl::c_linear_search(), int_to_meld, IsRankMeld(), IsSuitMeld(), RankMeldLayoff(), and SuitMeldLayoffs().
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
AllMeldGroups()
VecVecVecInt open_spiel::gin_rummy::GinRummyUtils::AllMeldGroups (const VecInt & cards) const
Definition at line 291 of file gin_rummy_utils.cc.
{
  VecVecInt all_melds = AllMelds(cards);
  VecVecVecInt all_meld_groups;
  for (VecInt meld : all_melds) {
    VecVecInt path;
    AllPaths(&meld, &all_melds, &path, &all_meld_groups);
  }
  return all_meld_groups;
}
References AllMelds(), AllPaths(), and path.
Referenced by BestMeldGroup(), open_spiel::init_pyspiel_games_gin_rummy(), and LegalMelds().
AllMelds()
VecVecInt open_spiel::gin_rummy::GinRummyUtils::AllMelds (const VecInt & cards) const
Definition at line 235 of file gin_rummy_utils.cc.
{
  VecVecInt rank_melds = RankMelds(cards);
  VecVecInt suit_melds = SuitMelds(cards);
  rank_melds.insert(rank_melds.end(), suit_melds.begin(), suit_melds.end());
  return rank_melds;
}
References RankMelds(), and SuitMelds().
Referenced by AllMeldGroups(), BuildIntToMeldMap(), BuildMeldToIntMap(), and open_spiel::init_pyspiel_games_gin_rummy().
AllPaths()
void open_spiel::gin_rummy::GinRummyUtils::AllPaths (VecInt * meld, VecVecInt * all_melds, VecVecInt * path, VecVecVecInt * all_paths) const
Definition at line 275 of file gin_rummy_utils.cc.
{
  path->push_back(*meld);
  VecVecInt child_melds = NonOverlappingMelds(meld, all_melds);
  if (child_melds.empty()) {
    all_paths->push_back(*path);
  } else {
    for (auto child_meld : child_melds) {
      AllPaths(&child_meld, &child_melds, path, all_paths);
    }
  }
  path->pop_back();
}
References AllPaths(), and NonOverlappingMelds().
Referenced by AllMeldGroups(), and AllPaths().
BestMeldGroup()
VecVecInt open_spiel::gin_rummy::GinRummyUtils::BestMeldGroup (const VecInt & cards) const
Definition at line 303 of file gin_rummy_utils.cc.
{
  int best_meld_group_total_value = 0;
  VecVecInt best_meld_group;
  VecVecVecInt all_meld_groups = AllMeldGroups(cards);
  for (const auto &meld_group : all_meld_groups) {
    int meld_group_total_value = TotalCardValue(meld_group);
    if (meld_group_total_value > best_meld_group_total_value) {
      best_meld_group_total_value = meld_group_total_value;
      best_meld_group = meld_group;
    }
  }
  return best_meld_group;
}
References AllMeldGroups(), and TotalCardValue().
Referenced by open_spiel::init_pyspiel_games_gin_rummy(), and MinDeadwood().
BuildIntToMeldMap()
std::map< int, VecInt > open_spiel::gin_rummy::GinRummyUtils::BuildIntToMeldMap () const
Definition at line 448 of file gin_rummy_utils.cc.
{
  const int kNumCards = 52;
  std::map<int, VecInt> rv;
  VecInt full_deck;
  for (int i = 0; i < kNumCards; ++i) full_deck.push_back(i);
  VecVecInt all_melds = AllMelds(full_deck);
  for (int i = 0; i < all_melds.size(); ++i) {
    for (const auto &meld : all_melds) {
      if (MeldToInt(meld) == i) {
        rv.insert(std::pair<int, VecInt>(i, meld));
        break;
      }
    }
  }
  return rv;
}
References AllMelds(), i, and MeldToInt().
BuildMeldToIntMap()
std::map< VecInt, int > open_spiel::gin_rummy::GinRummyUtils::BuildMeldToIntMap () const
Definition at line 434 of file gin_rummy_utils.cc.
{
  std::map<VecInt, int> rv;
  VecInt full_deck;
  for (int i = 0; i < num_cards; ++i) full_deck.push_back(i);
  VecVecInt all_melds = AllMelds(full_deck);
  for (int i = 0; i < all_melds.size(); ++i) {
    int meld_id = MeldToInt(all_melds[i]);
    rv.insert(std::pair<VecInt, int>(all_melds[i], meld_id));
  }
  return rv;
}
References AllMelds(), i, MeldToInt(), and num_cards.
CardInt()
int open_spiel::gin_rummy::GinRummyUtils::CardInt (std::string card) const
Definition at line 52 of file gin_rummy_utils.cc.
{
  SPIEL_CHECK_EQ(card.length(), 2);
  int rank = strchr(kRankChar, card[0]) - kRankChar;
  int suit = strchr(kSuitChar, card[1]) - kSuitChar;
  return suit * num_ranks + rank;
}
References open_spiel::gin_rummy::kRankChar, open_spiel::gin_rummy::kSuitChar, num_ranks, rank, and SPIEL_CHECK_EQ.
Referenced by CardStringsToCardInts(), and open_spiel::init_pyspiel_games_gin_rummy().
CardIntsToCardStrings()
std::vector< std::string > open_spiel::gin_rummy::GinRummyUtils::CardIntsToCardStrings (const VecInt & cards) const
Definition at line 59 of file gin_rummy_utils.cc.
{
  std::vector<std::string> rv;
  for (int card : cards) {
    rv.push_back(CardString(card));
  }
  return rv;
}
References CardString().
Referenced by open_spiel::gin_rummy::GinRummyState::ActionToString(), and open_spiel::init_pyspiel_games_gin_rummy().
CardRank()
int open_spiel::gin_rummy::GinRummyUtils::CardRank (const int card_index) const
Definition at line 39 of file gin_rummy_utils.cc.
{ return card % num_ranks; }
References num_ranks.
Referenced by CardString(), CardValue(), open_spiel::init_pyspiel_games_gin_rummy(), IsRankMeld(), IsSuitMeld(), MeldToInt(), RankMeldLayoff(), RankMelds(), and SuitMeldLayoffs().
CardString()
std::string open_spiel::gin_rummy::GinRummyUtils::CardString (absl::optional< int > card) const
Definition at line 45 of file gin_rummy_utils.cc.
{
  if (!card.has_value()) return "XX";
  SPIEL_CHECK_GE(card.value(), 0);
  SPIEL_CHECK_LT(card.value(), num_cards);
  return {kRankChar[CardRank(card.value())], kSuitChar[CardSuit(card.value())]};
}
References CardRank(), CardSuit(), open_spiel::gin_rummy::kRankChar, open_spiel::gin_rummy::kSuitChar, num_cards, SPIEL_CHECK_GE, and SPIEL_CHECK_LT.
Referenced by open_spiel::gin_rummy::GinRummyState::ActionToString(), CardIntsToCardStrings(), HandToString(), open_spiel::init_pyspiel_games_gin_rummy(), and open_spiel::gin_rummy::GinRummyState::ToString().
CardStringsToCardInts()
VecInt open_spiel::gin_rummy::GinRummyUtils::CardStringsToCardInts (const std::vector< std::string > & cards) const
Definition at line 68 of file gin_rummy_utils.cc.
{
  VecInt rv;
  for (const std::string &card : cards) {
    rv.push_back(CardInt(card));
  }
  return rv;
}
References CardInt().
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
CardSuit()
int open_spiel::gin_rummy::GinRummyUtils::CardSuit (const int card_index) const
Definition at line 38 of file gin_rummy_utils.cc.
{ return card / num_ranks; }
References num_ranks.
Referenced by CardString(), open_spiel::init_pyspiel_games_gin_rummy(), IsSuitMeld(), MeldToInt(), RankMeldLayoff(), and SuitMelds().
CardValue()
int open_spiel::gin_rummy::GinRummyUtils::CardValue (int card_index) const
Definition at line 108 of file gin_rummy_utils.cc.
{
  int value = CardRank(card_index) + 1;
  return std::min(10, value);
}
References CardRank().
Referenced by open_spiel::init_pyspiel_games_gin_rummy(), MinDeadwood(), TotalCardValue(), and TotalCardValue().
HandToString()
std::string open_spiel::gin_rummy::GinRummyUtils::HandToString (const VecInt & cards) const
Definition at line 78 of file gin_rummy_utils.cc.
{
  std::string rv;
  constexpr int kHandStringSize = 174;
  rv.reserve(kHandStringSize);
  // Top border
  absl::StrAppend(&rv, "+");
  for (int i = 0; i < num_ranks; ++i)
    absl::StrAppend(&rv, "--");
  absl::StrAppend(&rv, "+\n");
  // One row for each suit
  for (int i = 0; i < num_suits; ++i) {
    absl::StrAppend(&rv, "|");
    for (int j = 0; j < num_ranks; ++j) {
      if (absl::c_linear_search(cards, (i * num_ranks) + j)) {
        absl::StrAppend(&rv, CardString((i * num_ranks) + j));
      } else {
        absl::StrAppend(&rv, "  ");
      }
    }
    absl::StrAppend(&rv, "|\n");
  }
  // Bottom border
  absl::StrAppend(&rv, "+");
  for (int i = 0; i < num_ranks; ++i)
    absl::StrAppend(&rv, "--");
  absl::StrAppend(&rv, "+\n");
  return rv;
}
References absl::c_linear_search(), CardString(), i, num_ranks, num_suits, and absl::StrAppend().
Referenced by open_spiel::init_pyspiel_games_gin_rummy(), open_spiel::gin_rummy::SimpleGinRummyBot::Step(), and open_spiel::gin_rummy::GinRummyState::ToString().
IsConsecutive()
bool open_spiel::gin_rummy::GinRummyUtils::IsConsecutive (const VecInt & v) const
Definition at line 133 of file gin_rummy_utils.cc.
{
  for (int i = 1; i < v.size(); ++i) {
    if (v[i] != v[i - 1] + 1) return false;
  }
  return true;
}
References i.
Referenced by open_spiel::init_pyspiel_games_gin_rummy(), and IsSuitMeld().
IsRankMeld()
bool open_spiel::gin_rummy::GinRummyUtils::IsRankMeld (const VecInt & cards) const
Definition at line 140 of file gin_rummy_utils.cc.
{
  if (cards.size() != 3 && cards.size() != 4) {
    return false;
  }
  for (int i = 1; i < cards.size(); ++i) {
    if (CardRank(cards[0]) != CardRank(cards[i])) {
      return false;
    }
  }
  return true;
}
References CardRank(), and i.
Referenced by AllLayoffs(), open_spiel::init_pyspiel_games_gin_rummy(), MeldToInt(), and RankMeldLayoff().
IsSuitMeld()
bool open_spiel::gin_rummy::GinRummyUtils::IsSuitMeld (const VecInt & cards) const
Definition at line 152 of file gin_rummy_utils.cc.
{
  if (cards.size() < 3) {
    return false;
  }
  // Check all of the same suit.
  for (int i = 1; i < cards.size(); ++i) {
    if (CardSuit(cards[0]) != CardSuit(cards[i])) {
      return false;
    }
  }
  // Check ranks are consecutive.
  VecInt ranks;
  for (int i = 0; i < cards.size(); ++i) {
    ranks.push_back(CardRank(cards[i]));
  }
  absl::c_sort(ranks);
  return IsConsecutive(ranks);
}
References absl::c_sort(), CardRank(), CardSuit(), i, and IsConsecutive().
Referenced by AllLayoffs(), open_spiel::init_pyspiel_games_gin_rummy(), and MeldToInt().
LegalDiscards()
VecInt open_spiel::gin_rummy::GinRummyUtils::LegalDiscards (const VecInt & hand, int knock_card) const
Definition at line 395 of file gin_rummy_utils.cc.
{
  std::set<int> legal_discards;
  for (int i = 0; i < hand.size(); ++i) {
    VecInt hand_(hand);
    hand_.erase(hand_.begin() + i);
    int deadwood = MinDeadwood(hand_);
    if (deadwood <= knock_card) {
      legal_discards.insert(hand[i]);
    }
  }
  return VecInt(legal_discards.begin(), legal_discards.end());
}
References i, and MinDeadwood().
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
LegalMelds()
VecInt open_spiel::gin_rummy::GinRummyUtils::LegalMelds (const VecInt & hand, int knock_card) const
Definition at line 375 of file gin_rummy_utils.cc.
{
  int total_hand_value = TotalCardValue(hand);
  std::set<int> meld_set;
  VecInt hand_(hand);
  VecVecVecInt all_meld_groups = AllMeldGroups(hand_);
  for (const auto &meld_group : all_meld_groups) {
    int meld_group_total_value = TotalCardValue(meld_group);
    if (total_hand_value - meld_group_total_value <= knock_card) {
      for (const auto &meld : meld_group) {
        meld_set.insert(meld_to_int.at(meld));
      }
    }
  }
  return VecInt(meld_set.begin(), meld_set.end());
}
References AllMeldGroups(), meld_to_int, and TotalCardValue().
Referenced by open_spiel::init_pyspiel_games_gin_rummy().
MeldToInt()
int open_spiel::gin_rummy::GinRummyUtils::MeldToInt (VecInt meld) const
Definition at line 474 of file gin_rummy_utils.cc.
{
  const int kNumRanks = 13;
  const int kNumSuits = 4;
  if (IsRankMeld(meld)) {
    if (meld.size() == 3) {
      VecInt suits;
      for (int i = 0; i < kNumSuits; ++i) suits.push_back(i);
      for (int card : meld) {
        suits.erase(std::remove(suits.begin(), suits.end(), CardSuit(card)),
                    suits.end());
      }
      return (CardRank(meld[0]) * 5) + suits[0];
    } else if (meld.size() == 4) {
      return (CardRank(meld[0]) * 5) + 4;
    }
    SpielFatalError("Impossible meld size");
  } else if (IsSuitMeld(meld)) {
    absl::c_sort(meld, rank_comp);
    int offset = 65;  // 65 rank melds
    if (meld.size() == 3) {
      return offset + (CardSuit(meld[0]) * (kNumRanks - 2)) +
             CardRank(meld[0]);
    }
    offset += 44;  // 44 suit melds of size three
    if (meld.size() == 4) {
      return offset + (CardSuit(meld[0]) * (kNumRanks - 3)) +
             CardRank(meld[0]);
    }
    offset += 40;  // 40 suit melds of size four
    if (meld.size() == 5) {
      return offset + (CardSuit(meld[0]) * (kNumRanks - 4)) +
             CardRank(meld[0]);
    }
    SpielFatalError("Impossible meld size");
  } else {
    SpielFatalError("Not a meld");
  }
}
References absl::c_sort(), CardRank(), CardSuit(), i, IsRankMeld(), IsSuitMeld(), rank_comp, and open_spiel::SpielFatalError().
Referenced by BuildIntToMeldMap(), BuildMeldToIntMap(), and open_spiel::init_pyspiel_games_gin_rummy().
MinDeadwood() [1/2]
int open_spiel::gin_rummy::GinRummyUtils::MinDeadwood (const VecInt & hand) const
Definition at line 324 of file gin_rummy_utils.cc.
{
  VecInt deadwood = hand;
  VecVecInt best_melds = BestMeldGroup(hand);
  for (const auto &meld : best_melds) {
    for (auto card : meld) {
      deadwood.erase(std::remove(deadwood.begin(), deadwood.end(), card),
                     deadwood.end());
    }
  }
  // If we have just drawn a card, we can discard the one worth the most points.
  if (hand.size() == hand_size + 1 && !deadwood.empty()) {
    absl::c_sort(deadwood, rank_comp);
    deadwood.pop_back();
  }
  int deadwood_total = 0;
  for (int card : deadwood) deadwood_total += CardValue(card);
  return deadwood_total;
}
References BestMeldGroup(), absl::c_sort(), CardValue(), hand_size, and rank_comp.
MinDeadwood() [2/2]
int open_spiel::gin_rummy::GinRummyUtils::MinDeadwood (VecInt hand, absl::optional< int > card) const
Definition at line 318 of file gin_rummy_utils.cc.
{
  if (card.has_value()) hand.push_back(card.value());
  return MinDeadwood(hand);
}
References MinDeadwood().
Referenced by open_spiel::init_pyspiel_games_gin_rummy(), LegalDiscards(), MinDeadwood(), and open_spiel::gin_rummy::SimpleGinRummyBot::Step().
NonOverlappingMelds()
VecVecInt open_spiel::gin_rummy::GinRummyUtils::NonOverlappingMelds (VecInt * meld, VecVecInt * melds) const
Definition at line 263 of file gin_rummy_utils.cc.
{
  VecVecInt rv;
  for (int i = 0; i < melds->size(); ++i) {
    if (!VectorsIntersect(meld, &(*melds)[i])) {
      rv.push_back((*melds)[i]);
    }
  }
  return rv;
}
References i, and VectorsIntersect().
Referenced by AllPaths().
RankMeldLayoff()
int open_spiel::gin_rummy::GinRummyUtils::RankMeldLayoff (const VecInt & meld) const
Definition at line 345 of file gin_rummy_utils.cc.
{
  SPIEL_CHECK_EQ(meld.size(), 3);
  SPIEL_CHECK_TRUE(IsRankMeld(meld));
  VecInt suits = {0, 1, 2, 3};
  for (int card : meld) {
    suits.erase(std::remove(suits.begin(), suits.end(), CardSuit(card)),
                suits.end());
  }
  return CardRank(meld[0]) + suits[0] * num_ranks;
}
References CardRank(), CardSuit(), IsRankMeld(), num_ranks, SPIEL_CHECK_EQ, and SPIEL_CHECK_TRUE.
Referenced by AllLayoffs(), and open_spiel::init_pyspiel_games_gin_rummy().
RankMelds()
VecVecInt open_spiel::gin_rummy::GinRummyUtils::RankMelds (VecInt cards) const
Definition at line 172 of file gin_rummy_utils.cc.
{
  VecVecInt melds;
  if (cards.size() < 3) {
    return melds;
  }
  absl::c_sort(cards, rank_comp);
  // First do a sweep for 4 card melds.
  for (int i = 0; i < cards.size() - 3; ++i) {
    // Found 4 card meld - implies there are four 3 card melds as well.
    // We only add two of the 3 card melds here, the other two get added
    // during the 3 card meld sweep.
    if (CardRank(cards[i]) == CardRank(cards[i + 3])) {
      melds.emplace_back(VecInt(cards.begin() + i, cards.begin() + i + 4));
      melds.emplace_back(VecInt{cards[i], cards[i + 1], cards[i + 3]});
      melds.emplace_back(VecInt{cards[i], cards[i + 2], cards[i + 3]});
    }
  }
  // Sweep for 3 card melds.
  for (int i = 0; i < cards.size() - 2; ++i) {
    if (CardRank(cards[i]) == CardRank(cards[i + 2])) {
      melds.emplace_back(VecInt(cards.begin() + i, cards.begin() + i + 3));
    }
  }
  return melds;
}
References absl::c_sort(), CardRank(), i, and rank_comp.
Referenced by AllMelds(), and open_spiel::init_pyspiel_games_gin_rummy().
SuitMeldLayoffs()
VecInt open_spiel::gin_rummy::GinRummyUtils::SuitMeldLayoffs (const VecInt & meld) const
Definition at line 357 of file gin_rummy_utils.cc.
{
  VecInt layoffs;
  int min_card_index = *std::min_element(meld.begin(), meld.end());
  if (CardRank(min_card_index) > 0) {
    layoffs.push_back(min_card_index - 1);
  }
  int max_card_index = *std::max_element(meld.begin(), meld.end());
  if (CardRank(max_card_index) < num_ranks - 1) {
    layoffs.push_back(max_card_index + 1);
  }
  return layoffs;
}
References CardRank(), and num_ranks.
Referenced by AllLayoffs(), and open_spiel::init_pyspiel_games_gin_rummy().
SuitMelds()
VecVecInt open_spiel::gin_rummy::GinRummyUtils::SuitMelds (VecInt cards) const
Definition at line 199 of file gin_rummy_utils.cc.
{
  VecVecInt melds;
  if (cards.size() < 3) {
    return melds;
  }
  absl::c_sort(cards, suit_comp);
  // Find all suit melds of length 5.
  if (cards.size() >= 5) {
    for (int i = 0; i < cards.size() - 4; ++i) {
      if (cards[i] == cards[i + 4] - 4 &&
          CardSuit(cards[i]) == CardSuit(cards[i + 4])) {
        melds.emplace_back(VecInt(cards.begin() + i, cards.begin() + i + 5));
      }
    }
  }
  // Find all suit melds of length 4.
  if (cards.size() >= 4) {
    for (int i = 0; i < cards.size() - 3; ++i) {
      if (cards[i] == cards[i + 3] - 3 &&
          CardSuit(cards[i]) == CardSuit(cards[i + 3])) {
        melds.emplace_back(VecInt(cards.begin() + i, cards.begin() + i + 4));
      }
    }
  }
  // Find all suit melds of length 3.
  for (int i = 0; i < cards.size() - 2; ++i) {
    if (cards[i] == cards[i + 2] - 2 &&
        CardSuit(cards[i]) == CardSuit(cards[i + 2])) {
      melds.emplace_back(VecInt(cards.begin() + i, cards.begin() + i + 3));
    }
  }
  return melds;
}
References absl::c_sort(), CardSuit(), i, and suit_comp.
Referenced by AllMelds(), and open_spiel::init_pyspiel_games_gin_rummy().
TotalCardValue() [1/2]
int open_spiel::gin_rummy::GinRummyUtils::TotalCardValue (const VecInt & cards) const
Definition at line 114 of file gin_rummy_utils.cc.
{
  int total_value = 0;
  for (int card : cards) {
    total_value += CardValue(card);
  }
  return total_value;
}
References CardValue().
Referenced by BestMeldGroup(), open_spiel::init_pyspiel_games_gin_rummy(), and LegalMelds().
TotalCardValue() [2/2]
int open_spiel::gin_rummy::GinRummyUtils::TotalCardValue (const VecVecInt & meld_group) const
Definition at line 123 of file gin_rummy_utils.cc.
{
  int total_value = 0;
  for (const auto &meld : meld_group) {
    for (auto card : meld) {
      total_value += CardValue(card);
    }
  }
  return total_value;
}
References CardValue().
VectorsIntersect()
bool open_spiel::gin_rummy::GinRummyUtils::VectorsIntersect (VecInt * v1, VecInt * v2) const
Definition at line 242 of file gin_rummy_utils.cc.
{
  absl::c_sort(*v1);
  absl::c_sort(*v2);
  VecInt::iterator first1 = v1->begin();
  VecInt::iterator last1 = v1->end();
  VecInt::iterator first2 = v2->begin();
  VecInt::iterator last2 = v2->end();
  while (first1 != last1 && first2 != last2) {
    if (*first1 < *first2) {
      ++first1;
    } else if (*first2 < *first1) {
      ++first2;
    } else {
      return true;
    }
  }
  return false;
}
References absl::c_sort().
Referenced by NonOverlappingMelds().
Member Data Documentation
hand_size
const int open_spiel::gin_rummy::GinRummyUtils::hand_size
Definition at line 62 of file gin_rummy_utils.h.
Referenced by MinDeadwood().
int_to_meld
const std::map<int, VecInt> open_spiel::gin_rummy::GinRummyUtils::int_to_meld
Definition at line 68 of file gin_rummy_utils.h.
Referenced by open_spiel::gin_rummy::GinRummyState::ActionToString(), AllLayoffs(), open_spiel::init_pyspiel_games_gin_rummy(), and open_spiel::gin_rummy::GinRummyState::ToString().
meld_to_int
const std::map<VecInt, int> open_spiel::gin_rummy::GinRummyUtils::meld_to_int
Definition at line 69 of file gin_rummy_utils.h.
Referenced by LegalMelds().
num_cards
const int open_spiel::gin_rummy::GinRummyUtils::num_cards
Definition at line 61 of file gin_rummy_utils.h.
Referenced by BuildMeldToIntMap(), and CardString().
num_ranks
const int open_spiel::gin_rummy::GinRummyUtils::num_ranks
Definition at line 59 of file gin_rummy_utils.h.
Referenced by CardInt(), CardRank(), CardSuit(), HandToString(), RankMeldLayoff(), and SuitMeldLayoffs().
num_suits
const int open_spiel::gin_rummy::GinRummyUtils::num_suits
Definition at line 60 of file gin_rummy_utils.h.
Referenced by HandToString().
rank_comp
const RankComparator open_spiel::gin_rummy::GinRummyUtils::rank_comp
Definition at line 65 of file gin_rummy_utils.h.
Referenced by MeldToInt(), MinDeadwood(), and RankMelds().
suit_comp
const SuitComparator open_spiel::gin_rummy::GinRummyUtils::suit_comp
Definition at line 64 of file gin_rummy_utils.h.
Referenced by SuitMelds().
The documentation for this struct was generated from the following files:
open_spiel/games/gin_rummy/gin_rummy_utils.h
open_spiel/games/gin_rummy/gin_rummy_utils.cc