open spiel: open_spiel::colored_trails::Trade Struct Reference
open_spiel::colored_trails::Trade Struct Reference
#include <colored_trails.h>
Public Member Functions
Trade ()
Trade (const std::vector< int > _giving, const std::vector< int > _receiving)
Trade (const Trade &other)
std::string ToString () const
int DistanceTo (const Trade &other) const
bool operator== (const Trade &other) const
bool reduce ()
Public Attributes
std::vector< int > giving
std::vector< int > receiving
Detailed Description
Definition at line 90 of file colored_trails.h.
Constructor & Destructor Documentation
Trade() [1/3]
open_spiel::colored_trails::Trade::Trade () inline
Definition at line 93 of file colored_trails.h.
{}
Trade() [2/3]
open_spiel::colored_trails::Trade::Trade (const std::vector< int > _giving, const std::vector< int > _receiving)
Definition at line 267 of file colored_trails.cc.
    : giving(_giving), receiving(_receiving) {}
Trade() [3/3]
open_spiel::colored_trails::Trade::Trade (const Trade & other)
Definition at line 270 of file colored_trails.cc.
    : giving(other.giving), receiving(other.receiving) {}
Member Function Documentation
DistanceTo()
int open_spiel::colored_trails::Trade::DistanceTo (const Trade & other) const
Definition at line 244 of file colored_trails.cc.
{
  int sum = 0;
  if (other.giving.empty() || other.receiving.empty()) {
    // Pass trade is the furthest possible distance.
    return kDefaultTradeDistanceUpperBound + 1;
  }
  for (int i = 0; i < giving.size(); ++i) {
    sum += std::abs(other.giving[i] - giving[i]);
    sum += std::abs(other.receiving[i] - receiving[i]);
  }
  return sum;
}
References giving, i, open_spiel::colored_trails::kDefaultTradeDistanceUpperBound, and receiving.
Referenced by open_spiel::colored_trails::ColoredTrailsState::SetChipsAndTradeProposal().
operator==()
bool open_spiel::colored_trails::Trade::operator== (const Trade & other) const inline
Definition at line 98 of file colored_trails.h.
{
    return (giving == other.giving && receiving == other.receiving);
  }
References giving, and receiving.
reduce()
bool open_spiel::colored_trails::Trade::reduce ()
Definition at line 257 of file colored_trails.cc.
                   {
  for (int i = 0; i < giving.size(); ++i) {
    int min_val = std::min(giving[i], receiving[i]);
    giving[i] -= min_val;
    receiving[i] -= min_val;
  }
  return (std::accumulate(giving.begin(), giving.end(), 0) > 0 &&
          std::accumulate(receiving.begin(), receiving.end(), 0) > 0);
}
References giving, i, and receiving.
Referenced by open_spiel::colored_trails::InitTradeInfo(), and open_spiel::colored_trails::ColoredTrailsState::SetChipsAndTradeProposal().
ToString()
std::string open_spiel::colored_trails::Trade::ToString () const
Definition at line 237 of file colored_trails.cc.
{
  if (giving.empty() || receiving.empty()) {
    return "Pass trade.";
  }
  return absl::StrCat(ComboToString(giving), " for ", ComboToString(receiving));
}
References open_spiel::colored_trails::ComboToString(), giving, receiving, and absl::StrCat().
Referenced by open_spiel::colored_trails::ColoredTrailsState::ActionToString(), open_spiel::colored_trails::InitTradeInfo(), and open_spiel::colored_trails::ColoredTrailsState::SetChipsAndTradeProposal().
Member Data Documentation
giving
std::vector<int> open_spiel::colored_trails::Trade::giving
Definition at line 91 of file colored_trails.h.
Referenced by open_spiel::colored_trails::Board::ApplyTrade(), DistanceTo(), open_spiel::colored_trails::ColoredTrailsState::DoApplyAction(), operator==(), reduce(), and ToString().
receiving
std::vector<int> open_spiel::colored_trails::Trade::receiving
Definition at line 92 of file colored_trails.h.
Referenced by open_spiel::colored_trails::Board::ApplyTrade(), DistanceTo(), open_spiel::colored_trails::ColoredTrailsState::DoApplyAction(), operator==(), reduce(), and ToString().
The documentation for this struct was generated from the following files:
open_spiel/games/colored_trails/colored_trails.h
open_spiel/games/colored_trails/colored_trails.cc