open spiel: absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses > Struct Template Reference
absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses > Struct Template Reference
#include <conformance_testing.h>
Public Member Functions
template<class Fun , absl::enable_if_t< std::is_same< ResultOfGeneratorT< GeneratorType< Fun > >, T >::value > ** = nullptr>
ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses..., EquivalenceClassType< Fun > > initializer (GeneratorType< Fun > fun) &&
template<class... TestNames, absl::enable_if_t<!ExpectSuccess &&sizeof...(EqClasses)==0 &&absl::conjunction< std::is_convertible< TestNames, absl::string_view >... >::value > ** = nullptr>
ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses... > due_to (TestNames &&... test_names) &&
template<class... TestNames, int = 0, absl::enable_if_t< ExpectSuccess &&sizeof...(EqClasses)==0 &&absl::conjunction< std::is_convertible< TestNames, absl::string_view >... >::value > ** = nullptr>
ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses... > due_to (TestNames &&... test_names) &&
template<class Fun , absl::enable_if_t< std::is_same< ResultOfGeneratorT< GeneratorType< Fun > >, T >::value > ** = nullptr>
ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses..., EquivalenceClassType< Fun > > dont_class_directly_stateful_initializer (GeneratorType< Fun > fun) &&
template<class... Funs, absl::void_t< absl::enable_if_t< std::is_same< ResultOfGeneratorT< GeneratorType< Funs > >, T >::value >... > ** = nullptr>
ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses..., EquivalenceClassType< Funs... > > equivalence_class (GeneratorType< Funs >... funs) &&
template<class ProfRange , absl::enable_if_t< IsProfileOrProfileRange< ProfRange >::value > ** = nullptr>
ABSL_MUST_USE_RESULT::testing::AssertionResult with_strict_profile (ProfRange)
template<class Prof , absl::enable_if_t< IsProfile< Prof >::value > ** = nullptr>
ABSL_MUST_USE_RESULT::testing::AssertionResult with_loose_profile (Prof)
Public Attributes
OrderedEquivalenceClasses< EqClasses... > ordered_vals
std::set< std::string > expected_failed_tests
Detailed Description
template<bool ExpectSuccess, class T, class... EqClasses>
struct absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >
Definition at line 1151 of file conformance_testing.h.
Member Function Documentation
dont_class_directly_stateful_initializer()
template<bool ExpectSuccess, class T , class... EqClasses> template<class Fun , absl::enable_if_t< std::is_same< ResultOfGeneratorT< GeneratorType< Fun > >, T >::value > ** = nullptr> ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses..., EquivalenceClassType< Fun > > absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::dont_class_directly_stateful_initializer (GeneratorType< Fun > fun) && inline
Definition at line 1210 of file conformance_testing.h.
{
    return {
        {std::tuple_cat(absl::move(ordered_vals.eq_classes),
                        std::make_tuple((EquivalenceClass)(absl::move(fun))))},
        std::move(expected_failed_tests)};
  }
References absl::types_internal::OrderedEquivalenceClasses< EqClasses >::eq_classes, absl::types_internal::EquivalenceClass(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::expected_failed_tests, absl::move(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::ordered_vals.
due_to() [1/2]
template<bool ExpectSuccess, class T , class... EqClasses> template<class... TestNames, absl::enable_if_t<!ExpectSuccess &&sizeof...(EqClasses)==0 &&absl::conjunction< std::is_convertible< TestNames, absl::string_view >... >::value > ** = nullptr> ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses... > absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::due_to (TestNames &&... test_names) && inline
Definition at line 1177 of file conformance_testing.h.
{
    (InsertEach)(&expected_failed_tests,
                 absl::AsciiStrToLower(absl::string_view(test_names))...);
    return {absl::move(ordered_vals), std::move(expected_failed_tests)};
  }
References absl::AsciiStrToLower(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::expected_failed_tests, absl::types_internal::InsertEach(), absl::move(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::ordered_vals.
due_to() [2/2]
template<bool ExpectSuccess, class T , class... EqClasses> template<class... TestNames, int = 0, absl::enable_if_t< ExpectSuccess &&sizeof...(EqClasses)==0 &&absl::conjunction< std::is_convertible< TestNames, absl::string_view >... >::value > ** = nullptr> ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses... > absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::due_to (TestNames &&... test_names) && inline
Definition at line 1190 of file conformance_testing.h.
{
    // TODO(calabrese) Instead have DUE_TO only exist via a CRTP base.
    // This would produce better errors messages than the static_assert.
    static_assert(!ExpectSuccess,
                  "DUE_TO cannot be called when conformance is expected -- did "
                  "you mean to use ASSERT_NONCONFORMANCE_OF?");
  }
equivalence_class()
template<bool ExpectSuccess, class T , class... EqClasses> template<class... Funs, absl::void_t< absl::enable_if_t< std::is_same< ResultOfGeneratorT< GeneratorType< Funs > >, T >::value >... > ** = nullptr> ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses..., EquivalenceClassType< Funs... > > absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::equivalence_class (GeneratorType< Funs >... funs) && inline
Definition at line 1225 of file conformance_testing.h.
{
    return {{std::tuple_cat(
                absl::move(ordered_vals.eq_classes),
                std::make_tuple((EquivalenceClass)(absl::move(funs)...)))},
            std::move(expected_failed_tests)};
  }
References absl::types_internal::OrderedEquivalenceClasses< EqClasses >::eq_classes, absl::types_internal::EquivalenceClass(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::expected_failed_tests, absl::move(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::ordered_vals.
initializer()
template<bool ExpectSuccess, class T , class... EqClasses> template<class Fun , absl::enable_if_t< std::is_same< ResultOfGeneratorT< GeneratorType< Fun > >, T >::value > ** = nullptr> ABSL_MUST_USE_RESULT ExpectConformanceOf< ExpectSuccess, T, EqClasses..., EquivalenceClassType< Fun > > absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::initializer (GeneratorType< Fun > fun) && inline
Definition at line 1164 of file conformance_testing.h.
{
    return {
        {std::tuple_cat(absl::move(ordered_vals.eq_classes),
                        std::make_tuple((EquivalenceClass)(absl::move(fun))))},
        std::move(expected_failed_tests)};
  }
References absl::types_internal::OrderedEquivalenceClasses< EqClasses >::eq_classes, absl::types_internal::EquivalenceClass(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::expected_failed_tests, absl::move(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::ordered_vals.
with_loose_profile()
template<bool ExpectSuccess, class T , class... EqClasses> template<class Prof , absl::enable_if_t< IsProfile< Prof >::value > ** = nullptr> ABSL_MUST_USE_RESULT::testing::AssertionResult absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_loose_profile (Prof) inline
Definition at line 1253 of file conformance_testing.h.
              {
    ConformanceErrors test_result =
        (ExpectRegularityImpl<
            T, Prof, Prof,
            CombineProfiles<TriviallyCompleteProfile,
                            NothrowComparableProfile>>)(absl::
                                                            move(ordered_vals));
    return ExpectSuccess ? test_result.assertionResult()
                         : test_result.expectFailedTests(expected_failed_tests);
  }
References absl::types_internal::ConformanceErrors::assertionResult(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::expected_failed_tests, absl::types_internal::ConformanceErrors::expectFailedTests(), absl::types_internal::ExpectRegularityImpl(), absl::move(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::ordered_vals.
with_strict_profile()
template<bool ExpectSuccess, class T , class... EqClasses> template<class ProfRange , absl::enable_if_t< IsProfileOrProfileRange< ProfRange >::value > ** = nullptr> ABSL_MUST_USE_RESULT::testing::AssertionResult absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_strict_profile (ProfRange) inline
Definition at line 1237 of file conformance_testing.h.
                   {
    ConformanceErrors test_result =
        (ExpectRegularityImpl<
            T, LogicalProfileOfT<ProfRange>, MinProfileOfT<ProfRange>,
            MaxProfileOfT<ProfRange>>)(absl::move(ordered_vals));
    return ExpectSuccess ? test_result.assertionResult()
                         : test_result.expectFailedTests(expected_failed_tests);
  }
References absl::types_internal::ConformanceErrors::assertionResult(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::expected_failed_tests, absl::types_internal::ConformanceErrors::expectFailedTests(), absl::types_internal::ExpectRegularityImpl(), absl::move(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::ordered_vals.
Member Data Documentation
expected_failed_tests
template<bool ExpectSuccess, class T , class... EqClasses> std::set<std::string> absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::expected_failed_tests
Definition at line 1267 of file conformance_testing.h.
Referenced by absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::dont_class_directly_stateful_initializer(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::due_to(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::equivalence_class(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::initializer(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_loose_profile(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_strict_profile().
ordered_vals
template<bool ExpectSuccess, class T , class... EqClasses> OrderedEquivalenceClasses<EqClasses...> absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::ordered_vals
Definition at line 1266 of file conformance_testing.h.
Referenced by absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::dont_class_directly_stateful_initializer(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::due_to(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::equivalence_class(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::initializer(), absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_loose_profile(), and absl::types_internal::ExpectConformanceOf< ExpectSuccess, T, EqClasses >::with_strict_profile().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/types/internal/conformance_testing.h