open spiel: absl::variant_internal::VariantCoreAccess Struct Reference
absl::variant_internal::VariantCoreAccess Struct Reference
#include <variant.h>
Classes
struct ConversionAssignVisitor
struct CopyAssignVisitor
struct InitFromVisitor
struct MoveAssignVisitor
Static Public Member Functions
template<class VariantType >
static VariantType::Variant & Derived (VariantType &self)
template<class VariantType >
static const VariantType::Variant & Derived (const VariantType &self)
template<class VariantType >
static void Destroy (VariantType &self)
template<class Variant >
static void SetIndex (Variant &self, std::size_t i)
template<class Variant >
static void InitFrom (Variant &self, Variant &&other)
template<std::size_t I, class Variant >
static VariantAccessResult< I, Variant > Access (Variant &&self)
template<std::size_t I, class Variant >
static VariantAccessResult< I, Variant > CheckedAccess (Variant &&self)
template<class VType >
static MoveAssignVisitor< VType > MakeMoveAssignVisitor (VType *left, VType *other)
template<class VType >
static CopyAssignVisitor< VType > MakeCopyAssignVisitor (VType *left, const VType &other)
template<class Left , class QualifiedNew >
static ConversionAssignVisitor< Left, QualifiedNew > MakeConversionAssignVisitor (Left *left, QualifiedNew &&qual)
template<std::size_t NewIndex, class Self , class... Args>
static absl::variant_alternative< NewIndex, Self >::type & Replace (Self *self, Args &&... args)
Detailed Description
Definition at line 565 of file variant.h.
Member Function Documentation
Access()
template<std::size_t I, class Variant > static VariantAccessResult< I, Variant > absl::variant_internal::VariantCoreAccess::Access (Variant && self) inline static
Definition at line 599 of file variant.h.
{
    // This cast instead of invocation of AccessUnion with an rvalue is a
    // workaround for msvc. Without this there is a runtime failure when dealing
    // with rvalues.
    // TODO(calabrese) Reduce test case and find a simpler workaround.
    return static_cast<VariantAccessResult<I, Variant>>(
        variant_internal::AccessUnion(self.state_, SizeT<I>()));
  }
Referenced by absl::get_if(), and absl::get_if().
CheckedAccess()
template<std::size_t I, class Variant > static VariantAccessResult< I, Variant > absl::variant_internal::VariantCoreAccess::CheckedAccess (Variant && self) inline static
Definition at line 610 of file variant.h.
{
    if (ABSL_PREDICT_FALSE(self.index_ != I)) {
      TypedThrowBadVariantAccess<VariantAccessResult<I, Variant>>();
    }
    return Access<I>(absl::forward<Variant>(self));
  }
Referenced by absl::get(), absl::get(), absl::get(), and absl::get().
Derived() [1/2]
template<class VariantType > static const VariantType::Variant & absl::variant_internal::VariantCoreAccess::Derived (const VariantType & self) inline static
Definition at line 572 of file variant.h.
                               {  // NOLINT
    return static_cast<const typename VariantType::Variant&>(self);
  }
Derived() [2/2]
template<class VariantType > static VariantType::Variant & absl::variant_internal::VariantCoreAccess::Derived (VariantType & self) inline static
Definition at line 567 of file variant.h.
                                                                 {  // NOLINT
    return static_cast<typename VariantType::Variant&>(self);
  }
Destroy()
template<class VariantType > static void absl::variant_internal::VariantCoreAccess::Destroy (VariantType & self) inline static
Definition at line 578 of file variant.h.
                                         {  // NOLINT
    Derived(self).destroy();
    self.index_ = absl::variant_npos;
  }
InitFrom()
template<class Variant > static void absl::variant_internal::VariantCoreAccess::InitFrom (Variant & self, Variant && other) inline static
Definition at line 589 of file variant.h.
                                                       {  // NOLINT
    VisitIndices<absl::variant_size<Variant>::value>::Run(
        InitFromVisitor<Variant, Variant&&>{&self,
                                            std::forward<Variant>(other)},
        other.index());
    self.index_ = other.index();
  }
MakeConversionAssignVisitor()
template<class Left , class QualifiedNew > static ConversionAssignVisitor< Left, QualifiedNew > absl::variant_internal::VariantCoreAccess::MakeConversionAssignVisitor (Left * left, QualifiedNew && qual) inline static
Definition at line 714 of file variant.h.
{
    return {left, absl::forward<QualifiedNew>(qual)};
  }
References absl::forward().
Referenced by absl::variant< T0, Tn... >::operator=().
MakeCopyAssignVisitor()
template<class VType > static CopyAssignVisitor< VType > absl::variant_internal::VariantCoreAccess::MakeCopyAssignVisitor (VType * left, const VType & other) inline static
Definition at line 674 of file variant.h.
{
    return {left, &other};
  }
MakeMoveAssignVisitor()
template<class VType > static MoveAssignVisitor< VType > absl::variant_internal::VariantCoreAccess::MakeMoveAssignVisitor (VType * left, VType * other) inline static
Definition at line 641 of file variant.h.
{
    return {left, other};
  }
Replace()
template<std::size_t NewIndex, class Self , class... Args> static absl::variant_alternative< NewIndex, Self >::type & absl::variant_internal::VariantCoreAccess::Replace (Self * self, Args &&... args) inline static
Definition at line 721 of file variant.h.
{
    Destroy(*self);
    using New = typename absl::variant_alternative<NewIndex, Self>::type;
    New* const result = ::new (static_cast<void*>(&self->state_))
        New(absl::forward<Args>(args)...);
    self->index_ = NewIndex;
    return *result;
  }
References absl::forward().
Referenced by absl::variant< T0, Tn... >::emplace(), and absl::variant< T0, Tn... >::emplace().
SetIndex()
template<class Variant > static void absl::variant_internal::VariantCoreAccess::SetIndex (Variant & self, std::size_t i) inline static
Definition at line 584 of file variant.h.
                                                   {  // NOLINT
    self.index_ = i;
  }
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/types/internal/variant.h