open spiel: absl::container_internal::StringBtreeDefaultLess Struct Reference
absl::container_internal::StringBtreeDefaultLess Struct Reference
#include <btree.h>
Public Types
using is_transparent = void
Public Member Functions
StringBtreeDefaultLess ()=default
StringBtreeDefaultLess (std::less< std::string >)
StringBtreeDefaultLess (std::less< absl::string_view >)
operator std::less< std::string > () const
operator std::less< absl::string_view > () const
operator std::less< absl::Cord > () const
absl::weak_ordering operator() (absl::string_view lhs, absl::string_view rhs) const
StringBtreeDefaultLess (std::less< absl::Cord >)
absl::weak_ordering operator() (const absl::Cord &lhs, const absl::Cord &rhs) const
absl::weak_ordering operator() (const absl::Cord &lhs, absl::string_view rhs) const
absl::weak_ordering operator() (absl::string_view lhs, const absl::Cord &rhs) const
Detailed Description
Definition at line 98 of file btree.h.
Member Typedef Documentation
is_transparent
using absl::container_internal::StringBtreeDefaultLess::is_transparent = void
Definition at line 99 of file btree.h.
Constructor & Destructor Documentation
StringBtreeDefaultLess() [1/4]
absl::container_internal::StringBtreeDefaultLess::StringBtreeDefaultLess () default
StringBtreeDefaultLess() [2/4]
absl::container_internal::StringBtreeDefaultLess::StringBtreeDefaultLess (std::less< std::string >) inline
Definition at line 104 of file btree.h.
{}        // NOLINT
StringBtreeDefaultLess() [3/4]
absl::container_internal::StringBtreeDefaultLess::StringBtreeDefaultLess (std::less< absl::string_view >) inline
Definition at line 105 of file btree.h.
{}  // NOLINT
StringBtreeDefaultLess() [4/4]
absl::container_internal::StringBtreeDefaultLess::StringBtreeDefaultLess (std::less< absl::Cord >) inline
Definition at line 116 of file btree.h.
{}  // NOLINT
Member Function Documentation
operator std::less< absl::Cord >()
absl::container_internal::StringBtreeDefaultLess::operator std::less< absl::Cord > () const inline explicit
Definition at line 110 of file btree.h.
{ return {}; }
operator std::less< absl::string_view >()
absl::container_internal::StringBtreeDefaultLess::operator std::less< absl::string_view > () const inline explicit
Definition at line 109 of file btree.h.
{ return {}; }
operator std::less< std::string >()
absl::container_internal::StringBtreeDefaultLess::operator std::less< std::string > () const inline explicit
Definition at line 108 of file btree.h.
{ return {}; }
operator()() [1/4]
absl::weak_ordering absl::container_internal::StringBtreeDefaultLess::operator() (absl::string_view lhs, absl::string_view rhs) const inline
Definition at line 112 of file btree.h.
{
    return compare_internal::compare_result_as_ordering(lhs.compare(rhs));
  }
References absl::string_view::compare(), and absl::compare_internal::compare_result_as_ordering().
operator()() [2/4]
absl::weak_ordering absl::container_internal::StringBtreeDefaultLess::operator() (absl::string_view lhs, const absl::Cord & rhs) const inline
Definition at line 125 of file btree.h.
{
    return compare_internal::compare_result_as_ordering(-rhs.Compare(lhs));
  }
References absl::Cord::Compare(), and absl::compare_internal::compare_result_as_ordering().
operator()() [3/4]
absl::weak_ordering absl::container_internal::StringBtreeDefaultLess::operator() (const absl::Cord & lhs, absl::string_view rhs) const inline
Definition at line 121 of file btree.h.
{
    return compare_internal::compare_result_as_ordering(lhs.Compare(rhs));
  }
References absl::Cord::Compare(), and absl::compare_internal::compare_result_as_ordering().
operator()() [4/4]
absl::weak_ordering absl::container_internal::StringBtreeDefaultLess::operator() (const absl::Cord & lhs, const absl::Cord & rhs) const inline
Definition at line 117 of file btree.h.
{
    return compare_internal::compare_result_as_ordering(lhs.Compare(rhs));
  }
References absl::Cord::Compare(), and absl::compare_internal::compare_result_as_ordering().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/btree.h