open spiel: open_spiel::algorithms::CFRInfoStateValues Struct Reference
open_spiel::algorithms::CFRInfoStateValues Struct Reference
#include <cfr.h>
Public Member Functions
CFRInfoStateValues ()
CFRInfoStateValues (std::vector< Action > la, double init_value)
CFRInfoStateValues (std::vector< Action > la)
CFRInfoStateValues (std::vector< Action > la, std::mt19937 *rng, double magnitude_scale)
void ApplyRegretMatching ()
void ApplyRegretMatchingAllPositive (double delta)
bool empty () const
int num_actions () const
std::string ToString () const
std::string Serialize (int double_precision) const
int SampleActionIndex (double epsilon, double z)
ActionsAndProbs GetCurrentPolicy () const
int GetActionIndex (Action a)
Public Attributes
std::vector< Action > legal_actions
std::vector< double > cumulative_regrets
std::vector< double > cumulative_policy
std::vector< double > current_policy
Detailed Description
Definition at line 42 of file cfr.h.
Constructor & Destructor Documentation
CFRInfoStateValues() [1/4]
open_spiel::algorithms::CFRInfoStateValues::CFRInfoStateValues () inline
Definition at line 43 of file cfr.h.
{}
CFRInfoStateValues() [2/4]
open_spiel::algorithms::CFRInfoStateValues::CFRInfoStateValues (std::vector< Action > la, double init_value) inline
Definition at line 44 of file cfr.h.
      : legal_actions(la),
        cumulative_regrets(la.size(), init_value),
        cumulative_policy(la.size(), init_value),
        current_policy(la.size(), 1.0 / la.size()) {}
CFRInfoStateValues() [3/4]
open_spiel::algorithms::CFRInfoStateValues::CFRInfoStateValues (std::vector< Action > la) inline
Definition at line 49 of file cfr.h.
: CFRInfoStateValues(la, 0) {}
CFRInfoStateValues() [4/4]
open_spiel::algorithms::CFRInfoStateValues::CFRInfoStateValues (std::vector< Action > la, std::mt19937 * rng, double magnitude_scale) inline
Definition at line 52 of file cfr.h.
                                             : CFRInfoStateValues(la, 0) {
    for (int i = 0; i < cumulative_policy.size(); ++i) {
      cumulative_regrets[i] = magnitude_scale *
          absl::Uniform<double>(*rng, 0.0, 1.0);
    }
    ApplyRegretMatching();
  }
References ApplyRegretMatching(), cumulative_policy, cumulative_regrets, i, and absl::Uniform().
Member Function Documentation
ApplyRegretMatching()
void open_spiel::algorithms::CFRInfoStateValues::ApplyRegretMatching ()
Definition at line 596 of file cfr.cc.
{
  double sum_positive_regrets = 0.0;
  for (int aidx = 0; aidx < num_actions(); ++aidx) {
    if (cumulative_regrets[aidx] > 0) {
      sum_positive_regrets += cumulative_regrets[aidx];
    }
  }
  for (int aidx = 0; aidx < num_actions(); ++aidx) {
    if (sum_positive_regrets > 0) {
      current_policy[aidx] =
          cumulative_regrets[aidx] > 0
              ? cumulative_regrets[aidx] / sum_positive_regrets
              : 0;
    } else {
      current_policy[aidx] = 1.0 / legal_actions.size();
    }
  }
}
References cumulative_regrets, current_policy, legal_actions, and num_actions().
Referenced by CFRInfoStateValues().
ApplyRegretMatchingAllPositive()
void open_spiel::algorithms::CFRInfoStateValues::ApplyRegretMatchingAllPositive (double delta)
Definition at line 585 of file cfr.cc.
{
  SPIEL_CHECK_GT(delta, 0);
  double sum = 0;
  for (int aidx = 0; aidx < num_actions(); ++aidx) {
    sum += std::max(cumulative_regrets[aidx], delta);
  }
  for (int aidx = 0; aidx < num_actions(); ++aidx) {
    current_policy[aidx] = std::max(cumulative_regrets[aidx], delta) / sum;
  }
}
References cumulative_regrets, current_policy, num_actions(), and SPIEL_CHECK_GT.
empty()
bool open_spiel::algorithms::CFRInfoStateValues::empty () const inline
Definition at line 71 of file cfr.h.
{ return legal_actions.empty(); }
References legal_actions.
Referenced by open_spiel::algorithms::CFRSolverBase::ComputeCounterFactualRegret().
GetActionIndex()
int open_spiel::algorithms::CFRInfoStateValues::GetActionIndex (Action a)
Definition at line 630 of file cfr.cc.
{
  auto it = std::find(legal_actions.begin(), legal_actions.end(), a);
  if (it != legal_actions.end()) {
    return std::distance(legal_actions.begin(), it);
  }
  SpielFatalError(
      absl::StrCat("GetActionIndex: the action was not found: ", a));
}
References a, legal_actions, open_spiel::SpielFatalError(), and absl::StrCat().
GetCurrentPolicy()
ActionsAndProbs open_spiel::algorithms::CFRInfoStateValues::GetCurrentPolicy () const
Definition at line 576 of file cfr.cc.
{
  ActionsAndProbs actions_and_probs;
  actions_and_probs.reserve(legal_actions.size());
  for (int i = 0; i < legal_actions.size(); ++i) {
    actions_and_probs.push_back({legal_actions[i], current_policy[i]});
  }
  return actions_and_probs;
}
References actions_and_probs, current_policy, i, and legal_actions.
num_actions()
int open_spiel::algorithms::CFRInfoStateValues::num_actions () const inline
Definition at line 72 of file cfr.h.
{ return legal_actions.size(); }
References legal_actions.
Referenced by ApplyRegretMatching(), ApplyRegretMatchingAllPositive(), open_spiel.python.games.dynamic_routing_utils.Network::assert_valid_action(), open_spiel.python.pytorch.ppo.PPOAgent::get_action_and_value(), open_spiel.python.pytorch.ppo.PPOAtariAgent::get_action_and_value(), models.OptimizerModel::initialize_optimizer_model(), open_spiel.python.pytorch.ppo.PPO::learn(), regret_matching_agent.RegretMatchingAgent::regret_matching_policy(), and open_spiel.python.pytorch.ppo.PPO::step().
SampleActionIndex()
int open_spiel::algorithms::CFRInfoStateValues::SampleActionIndex (double epsilon, double z)
Definition at line 617 of file cfr.cc.
{
  double sum = 0;
  for (int aidx = 0; aidx < current_policy.size(); ++aidx) {
    double prob = epsilon * 1.0 / current_policy.size() +
                  (1.0 - epsilon) * current_policy[aidx];
    if (z >= sum && z < sum + prob) {
      return aidx;
    }
    sum += prob;
  }
  SpielFatalError(absl::StrCat("SampleActionIndex: sum of probs is ", sum));
}
References current_policy, open_spiel::SpielFatalError(), and absl::StrCat().
Serialize()
std::string open_spiel::algorithms::CFRInfoStateValues::Serialize (int double_precision) const
Definition at line 509 of file cfr.cc.
{
  std::string str = "";
  std::string cumulative_regrets_str, cumulative_policy_str, current_policy_str;
  if (double_precision == -1) {
    cumulative_regrets_str =
        absl::StrJoin(cumulative_regrets, ",", HexDoubleFormatter());
    cumulative_policy_str =
        absl::StrJoin(cumulative_policy, ",", HexDoubleFormatter());
    current_policy_str =
        absl::StrJoin(current_policy, ",", HexDoubleFormatter());
  } else {
    cumulative_regrets_str = absl::StrJoin(
        cumulative_regrets, ",", SimpleDoubleFormatter(double_precision));
    cumulative_policy_str = absl::StrJoin(
        cumulative_policy, ",", SimpleDoubleFormatter(double_precision));
    current_policy_str = absl::StrJoin(current_policy, ",",
                                       SimpleDoubleFormatter(double_precision));
  }
  absl::StrAppend(&str, absl::StrJoin(legal_actions, ","), ";");
  absl::StrAppend(&str, cumulative_regrets_str, ";");
  absl::StrAppend(&str, cumulative_policy_str, ";");
  absl::StrAppend(&str, current_policy_str);
  return str;
}
References cumulative_policy, cumulative_regrets, current_policy, legal_actions, absl::StrAppend(), and absl::StrJoin().
ToString()
std::string open_spiel::algorithms::CFRInfoStateValues::ToString () const
Definition at line 495 of file cfr.cc.
{
  std::string str = "";
  absl::StrAppend(&str, "Legal actions: ", absl::StrJoin(legal_actions, ", "),
                  "\n");
  absl::StrAppend(&str, "Current policy: ", absl::StrJoin(current_policy, ", "),
                  "\n");
  absl::StrAppend(&str, "Cumulative regrets: ",
                  absl::StrJoin(cumulative_regrets, ", "), "\n");
  absl::StrAppend(&str,
                  "Cumulative policy: ", absl::StrJoin(cumulative_policy, ", "),
                  "\n");
  return str;
}
References cumulative_policy, cumulative_regrets, current_policy, legal_actions, absl::StrAppend(), and absl::StrJoin().
Member Data Documentation
cumulative_policy
std::vector<double> open_spiel::algorithms::CFRInfoStateValues::cumulative_policy
Definition at line 96 of file cfr.h.
Referenced by CFRInfoStateValues(), open_spiel::algorithms::CFRSolverBase::ComputeCounterFactualRegret(), open_spiel::algorithms::DeserializeCFRInfoStateValues(), Serialize(), and ToString().
cumulative_regrets
std::vector<double> open_spiel::algorithms::CFRInfoStateValues::cumulative_regrets
Definition at line 95 of file cfr.h.
Referenced by ApplyRegretMatching(), ApplyRegretMatchingAllPositive(), CFRInfoStateValues(), open_spiel::algorithms::CFRSolverBase::ComputeCounterFactualRegret(), open_spiel::algorithms::DeserializeCFRInfoStateValues(), Serialize(), and ToString().
current_policy
std::vector<double> open_spiel::algorithms::CFRInfoStateValues::current_policy
Definition at line 97 of file cfr.h.
Referenced by open_spiel.python.algorithms.efr._EFRSolverBase::_compute_cumulative_immediate_regret_for_player(), ApplyRegretMatching(), ApplyRegretMatchingAllPositive(), open_spiel::algorithms::DeserializeCFRInfoStateValues(), GetCurrentPolicy(), SampleActionIndex(), Serialize(), and ToString().
legal_actions
std::vector<Action> open_spiel::algorithms::CFRInfoStateValues::legal_actions
Definition at line 94 of file cfr.h.
Referenced by ApplyRegretMatching(), open_spiel::algorithms::DeserializeCFRInfoStateValues(), empty(), GetActionIndex(), GetCurrentPolicy(), num_actions(), Serialize(), and ToString().
The documentation for this struct was generated from the following files:
open_spiel/algorithms/cfr.h
open_spiel/algorithms/cfr.cc