open spiel: absl::TestCordRep Struct Reference
absl::TestCordRep Struct Reference
#include <cordz_test_helpers.h>
Public Member Functions
TestCordRep ()
~TestCordRep ()
Public Attributes
cord_internal::CordRepFlat * rep
Detailed Description
Definition at line 121 of file cordz_test_helpers.h.
Constructor & Destructor Documentation
TestCordRep()
absl::TestCordRep::TestCordRep () inline
Definition at line 124 of file cordz_test_helpers.h.
                {
    rep = cord_internal::CordRepFlat::New(100);
    rep->length = 100;
    memset(rep->Data(), 1, 100);
  }
References absl::cord_internal::CordRepFlat::Data(), absl::cord_internal::CordRep::length, absl::cord_internal::CordRepFlat::New(), and rep.
~TestCordRep()
absl::TestCordRep::~TestCordRep () inline
Definition at line 129 of file cordz_test_helpers.h.
{ cord_internal::CordRep::Unref(rep); }
References rep, and absl::cord_internal::CordRep::Unref().
Member Data Documentation
rep
cord_internal::CordRepFlat* absl::TestCordRep::rep
Definition at line 122 of file cordz_test_helpers.h.
Referenced by TestCordRep(), and ~TestCordRep().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/strings/cordz_test_helpers.h