open spiel: absl::types_internal::ExpectSelfMoveAssign< T, Prof > Struct Template Reference
absl::types_internal::ExpectSelfMoveAssign< T, Prof > Struct Template Reference
#include <conformance_testing.h>
Public Member Functions
template<class Fun >
void operator() (const Fun &generator) const
Public Attributes
ConformanceErrors * errors
Detailed Description
template<class T, class Prof>
struct absl::types_internal::ExpectSelfMoveAssign< T, Prof >
Definition at line 412 of file conformance_testing.h.
Member Function Documentation
operator()()
template<class T , class Prof > template<class Fun > void absl::types_internal::ExpectSelfMoveAssign< T, Prof >::operator() (const Fun & generator) const inline
Definition at line 414 of file conformance_testing.h.
{
    T object = generator();
    object = absl::move(object);
    // NOTE: Self move-assign results in a valid-but-unspecified state.
    (ExpectEquality<T, Prof>)(errors, "Move assignment",
                              PrepareGivenContext(
                                  GivenDeclaration{"_T object",
                                                   generator.description},
                                  GivenDeclaration{"object",
                                                   "std::move(object)"}),
                              object, object, "object", "object");
  }
References absl::types_internal::ExpectSelfMoveAssign< T, Prof >::errors, absl::types_internal::ExpectEquality(), absl::move(), and absl::types_internal::PrepareGivenContext().
Member Data Documentation
errors
template<class T , class Prof > ConformanceErrors* absl::types_internal::ExpectSelfMoveAssign< T, Prof >::errors
Definition at line 429 of file conformance_testing.h.
Referenced by absl::types_internal::ExpectSelfMoveAssign< T, Prof >::operator()().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/types/internal/conformance_testing.h