open spiel: absl::container_internal::CommonAccess Struct Reference
absl::container_internal::CommonAccess Struct Reference
#include <common.h>
Static Public Member Functions
template<typename Node >
static auto GetSlot (const Node &node) -> decltype(node.slot())
template<typename Node >
static void Destroy (Node *node)
template<typename Node >
static void Reset (Node *node)
template<typename T , typename... Args>
static T Transfer (Args &&... args)
template<typename T , typename... Args>
static T Construct (Args &&... args)
Detailed Description
Definition at line 168 of file common.h.
Member Function Documentation
Construct()
template<typename T , typename... Args> static T absl::container_internal::CommonAccess::Construct (Args &&... args) inline static
Definition at line 190 of file common.h.
{
    return T(typename T::construct_tag_t{}, std::forward<Args>(args)...);
  }
Referenced by absl::container_internal::btree_multiset_container< Tree >::emplace(), absl::container_internal::btree_set_container< Tree >::emplace(), absl::container_internal::btree_multiset_container< Tree >::emplace_hint(), absl::container_internal::btree_set_container< Tree >::emplace_hint(), absl::container_internal::btree_container< Tree >::extract(), and absl::container_internal::btree_container< Tree >::extract_and_get_next().
Destroy()
template<typename Node > static void absl::container_internal::CommonAccess::Destroy (Node * node) inline static
Definition at line 175 of file common.h.
{
    node->destroy();
  }
Referenced by absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), and absl::container_internal::btree_set_container< Tree >::insert().
GetSlot()
template<typename Node > static auto absl::container_internal::CommonAccess::GetSlot (const Node & node) -> decltype(node.slot()) inline static
Definition at line 170 of file common.h.
{
    return node.slot();
  }
Referenced by absl::container_internal::btree_multiset_container< Tree >::emplace(), absl::container_internal::btree_set_container< Tree >::emplace(), absl::container_internal::btree_multiset_container< Tree >::emplace_hint(), absl::container_internal::btree_set_container< Tree >::emplace_hint(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_multiset_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), absl::container_internal::btree_set_container< Tree >::insert(), and absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
Reset()
template<typename Node > static void absl::container_internal::CommonAccess::Reset (Node * node) inline static
Definition at line 180 of file common.h.
{
    node->reset();
  }
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::insert().
Transfer()
template<typename T , typename... Args> static T absl::container_internal::CommonAccess::Transfer (Args &&... args) inline static
Definition at line 185 of file common.h.
{
    return T(typename T::transfer_tag_t{}, std::forward<Args>(args)...);
  }
Referenced by absl::container_internal::raw_hash_set< Policy, Hash, Eq, Alloc >::extract().
The documentation for this struct was generated from the following file:
open_spiel/abseil-cpp/absl/container/internal/common.h