open spiel: open_spiel::chess::Move Struct Reference
open_spiel::chess::Move Struct Reference
#include <chess_board.h>
Public Member Functions
Move ()
Move (const Square &from, const Square &to, const Piece &piece, PieceType promotion_type=PieceType::kEmpty, bool is_castling=false)
std::string ToString () const
std::string ToLAN () const
std::string ToSAN (const ChessBoard &board) const
bool operator== (const Move &other) const
Public Attributes
Square from
Square to
Piece piece
PieceType promotion_type
bool is_castling = false
Detailed Description
Definition at line 140 of file chess_board.h.
Constructor & Destructor Documentation
Move() [1/2]
open_spiel::chess::Move::Move () inline
Definition at line 150 of file chess_board.h.
: is_castling(false) {}
Move() [2/2]
open_spiel::chess::Move::Move (const Square & from, const Square & to, const Piece & piece, PieceType promotion_type = PieceType::kEmpty, bool is_castling = false) inline
Definition at line 151 of file chess_board.h.
      : from(from),
        to(to),
        piece(piece),
        promotion_type(promotion_type),
        is_castling(is_castling) {}
Member Function Documentation
operator==()
bool open_spiel::chess::Move::operator== (const Move & other) const inline
Definition at line 212 of file chess_board.h.
{
    return from == other.from && to == other.to && piece == other.piece &&
           promotion_type == other.promotion_type &&
           is_castling == other.is_castling;
  }
References from, is_castling, piece, promotion_type, and to.
ToLAN()
std::string open_spiel::chess::Move::ToLAN () const
Definition at line 201 of file chess_board.cc.
{
  std::string promotion;
  if (promotion_type != PieceType::kEmpty) {
    promotion = PieceTypeToString(promotion_type, false);
  }
  return absl::StrCat(SquareToString(from), SquareToString(to), promotion);
}
References from, open_spiel::chess::kEmpty, open_spiel::chess::PieceTypeToString(), promotion_type, absl::StrCat(), and to.
ToSAN()
std::string open_spiel::chess::Move::ToSAN (const ChessBoard & board) const
Definition at line 209 of file chess_board.cc.
{
  std::string move_text;
  PieceType piece_type = board.at(from).type;
  if (is_castling) {
    if (from.x < to.x) {
      move_text = "O-O";
    } else {
      move_text = "O-O-O";
    }
  } else {
    switch (piece_type) {
      case PieceType::kKing:
      case PieceType::kQueen:
      case PieceType::kRook:
      case PieceType::kBishop:
      case PieceType::kKnight:
        move_text += PieceTypeToString(piece_type);
        break;
      case PieceType::kPawn:
        // No piece type required.
        break;
      case PieceType::kEmpty:
        std::cerr << "Move doesn't have a piece type" << std::endl;
    }
    // Now we generate all moves from this position, and see if our file and
    // rank are unique.
    bool file_unique = true;
    bool rank_unique = true;
    bool disambiguation_required = false;
    board.GenerateLegalMoves([&](const Move &move) -> bool {
      if (move.piece.type != piece.type) {
        return true;  // Continue generating moves.
      }
      if (move.to != to) {
        return true;
      }
      if (move.from == from) {
        // This is either us, or a promotion to a different type. We don't count
        // them as ambiguous in either case.
        return true;
      }
      disambiguation_required = true;
      if (move.from.x == from.x) {
        file_unique = false;
      } else if (move.from.y == from.y) {
        rank_unique = false;
      }
      return true;
    });
    bool file_required = false;
    bool rank_required = false;
    if (piece_type == PieceType::kPawn && from.x != to.x) {
      // Pawn captures always need file, and they will never require rank dis-
      // ambiguation.
      file_required = true;
    } else if (disambiguation_required) {
      if (file_unique) {
        // This includes when both will disambiguate, in which case we have to
        // use file. [FIDE Laws of Chess (2018): C.10.3].
        file_required = true;
      } else if (rank_unique) {
        rank_required = true;
      } else {
        // We have neither unique file nor unique rank. This is only possible
        // with 3 or more pieces of the same type.
        file_required = true;
        rank_required = true;
      }
    }
    if (file_required) {
      absl::StrAppend(&move_text, FileToString(from.x));
    }
    if (rank_required) {
      absl::StrAppend(&move_text, RankToString(from.y));
    }
    // We have a capture if either 1) the destination square has a piece, or
    // 2) we are making a diagonal pawn move (which can also be an en-passant
    // capture, where the destination square would not have a piece).
    auto piece_at_to_square = board.at(to);
    if ((piece_at_to_square.type != PieceType::kEmpty) ||
        (piece_type == PieceType::kPawn && from.x != to.x)) {
      absl::StrAppend(&move_text, "x");
    }
    // Destination square is always fully encoded.
    absl::StrAppend(&move_text, SquareToString(to));
    // Encode the promotion type if we have a promotion.
    switch (promotion_type) {
      case PieceType::kEmpty:
        break;
      case PieceType::kQueen:
      case PieceType::kRook:
      case PieceType::kBishop:
      case PieceType::kKnight:
        absl::StrAppend(&move_text, "=", PieceTypeToString(promotion_type));
        break;
      case PieceType::kKing:
      case PieceType::kPawn:
        std::cerr << "Cannot promote to " << PieceTypeToString(promotion_type)
                  << "! Only Q, R, B, N are allowed" << std::endl;
        break;
    }
  }
  // Figure out if this is a check / checkmating move or not.
  if (!board.KingInCheckAllowed()) {
    auto board_copy = board;
    board_copy.ApplyMove(*this);
    if (board_copy.InCheck()) {
      bool has_escape = false;
      board_copy.GenerateLegalMoves([&](const Move &) -> bool {
        has_escape = true;
        return false;  // No need to keep generating moves.
      });
      if (has_escape) {
        // Check.
        absl::StrAppend(&move_text, "+");
      } else {
        // Checkmate.
        absl::StrAppend(&move_text, "#");
      }
    }
  }
  return move_text;
}
References open_spiel::chess::ChessBoard::ApplyMove(), open_spiel::chess::ChessBoard::at(), open_spiel::chess::FileToString(), from, open_spiel::chess::ChessBoard::GenerateLegalMoves(), is_castling, open_spiel::chess::kBishop, open_spiel::chess::kEmpty, open_spiel::chess::ChessBoard::KingInCheckAllowed(), open_spiel::chess::kKing, open_spiel::chess::kKnight, open_spiel::chess::kPawn, open_spiel::chess::kQueen, open_spiel::chess::kRook, piece, open_spiel::chess::PieceTypeToString(), promotion_type, open_spiel::chess::RankToString(), absl::StrAppend(), to, open_spiel::chess::Piece::type, open_spiel::chess_common::Square::x, and open_spiel::chess_common::Square::y.
ToString()
std::string open_spiel::chess::Move::ToString () const
Definition at line 188 of file chess_board.cc.
{
  std::string extra;
  if (promotion_type != PieceType::kEmpty) {
    absl::StrAppend(&extra, ", promotion to ",
                    PieceTypeToString(promotion_type));
  }
  if (is_castling) {
    absl::StrAppend(&extra, " (castle)");
  }
  return absl::StrCat(piece.ToString(), " ", SquareToString(from), " to ",
                      SquareToString(to), extra);
}
References from, is_castling, open_spiel::chess::kEmpty, piece, open_spiel::chess::PieceTypeToString(), promotion_type, absl::StrAppend(), absl::StrCat(), to, and open_spiel::chess::Piece::ToString().
Referenced by open_spiel::chess::operator<<().
Member Data Documentation
from
Square open_spiel::chess::Move::from
Definition at line 141 of file chess_board.h.
Referenced by open_spiel::chess::ChessBoard::IsBreachingMove(), open_spiel::chess::MoveToAction(), operator==(), ToLAN(), ToSAN(), and ToString().
is_castling
bool open_spiel::chess::Move::is_castling = false
Definition at line 148 of file chess_board.h.
Referenced by operator==(), ToSAN(), and ToString().
piece
Piece open_spiel::chess::Move::piece
Definition at line 143 of file chess_board.h.
Referenced by open_spiel::chess::ChessBoard::IsBreachingMove(), operator==(), ToSAN(), and ToString().
promotion_type
PieceType open_spiel::chess::Move::promotion_type
Definition at line 144 of file chess_board.h.
Referenced by open_spiel::rbc::RbcState::DoApplyAction(), operator==(), ToLAN(), ToSAN(), and ToString().
to
Square open_spiel::chess::Move::to
Definition at line 142 of file chess_board.h.
Referenced by open_spiel::rbc::RbcState::DoApplyAction(), open_spiel::chess::ChessBoard::IsBreachingMove(), open_spiel::chess::MoveToAction(), operator==(), ToLAN(), ToSAN(), and ToString().
The documentation for this struct was generated from the following files:
open_spiel/games/chess/chess_board.h
open_spiel/games/chess/chess_board.cc