open spiel: open_spiel/abseil-cpp/absl/debugging/symbolize_test.cc File Reference
symbolize_test.cc File Reference
#include "absl/debugging/symbolize.h"
#include <fcntl.h>
#include <sys/mman.h>
#include <cstring>
#include <iostream>
#include <memory>
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "absl/base/attributes.h"
#include "absl/base/casts.h"
#include "absl/base/config.h"
#include "absl/base/internal/per_thread_tls.h"
#include "absl/base/internal/raw_logging.h"
#include "absl/base/optimization.h"
#include "absl/debugging/internal/stack_consumption.h"
#include "absl/memory/memory.h"
#include "absl/strings/string_view.h"
Classes
struct Foo
Macros
#define ABSL_SYMBOLIZE_TEST_NOINLINE ABSL_ATTRIBUTE_NOINLINE
Functions
ABSL_SYMBOLIZE_TEST_NOINLINE void nonstatic_func ()
int ABSL_ATTRIBUTE_SECTION_VARIABLE (.text.unlikely) unlikely_func()
int regular_func ()
const char kHpageTextPadding[kHpageSize *4] ABSL_ATTRIBUTE_SECTION_VARIABLE (.text)
TEST (Symbolize, Unimplemented)
int main (int argc, char **argv)
Macro Definition Documentation
ABSL_SYMBOLIZE_TEST_NOINLINE
#define ABSL_SYMBOLIZE_TEST_NOINLINE ABSL_ATTRIBUTE_NOINLINE
Definition at line 43 of file symbolize_test.cc.
Function Documentation
ABSL_ATTRIBUTE_SECTION_VARIABLE() [1/2]
const char kHpageTextPadding[kHpageSize *4] ABSL_ATTRIBUTE_SECTION_VARIABLE (. text)
References ABSL_RAW_CHECK, and absl::Symbolize().
ABSL_ATTRIBUTE_SECTION_VARIABLE() [2/2]
int ABSL_ATTRIBUTE_SECTION_VARIABLE (.text. unlikely)
Definition at line 80 of file symbolize_test.cc.
{
  return 0;
}
main()
int main (int argc, char ** argv)
Definition at line 583 of file symbolize_test.cc.
{
#if !defined(__EMSCRIPTEN__)
  // Make sure kHpageTextPadding is linked into the binary.
  if (volatile_bool) {
    ABSL_RAW_LOG(INFO, "%s", kHpageTextPadding);
  }
#endif  // !defined(__EMSCRIPTEN__)
#if ABSL_PER_THREAD_TLS
  // Touch the per-thread variables.
  symbolize_test_thread_small[0] = 0;
  symbolize_test_thread_big[0] = 0;
#endif
  absl::InitializeSymbolizer(argv[0]);
  testing::InitGoogleTest(&argc, argv);
#if defined(ABSL_INTERNAL_HAVE_ELF_SYMBOLIZE) || \
    defined(ABSL_INTERNAL_HAVE_DARWIN_SYMBOLIZE)
  TestWithPCInsideInlineFunction();
  TestWithPCInsideNonInlineFunction();
  TestWithReturnAddress();
#if defined(__arm__) && ABSL_HAVE_ATTRIBUTE(target) && \
    ((__ARM_ARCH >= 7) || !defined(__ARM_PCS_VFP))
  TestArmThumbOverlap();
#endif
#endif
  return RUN_ALL_TESTS();
}
References ABSL_RAW_LOG, INFO, and absl::InitializeSymbolizer().
nonstatic_func()
ABSL_SYMBOLIZE_TEST_NOINLINE void nonstatic_func ()
Definition at line 48 of file symbolize_test.cc.
{
  // The next line makes this a unique function to prevent the compiler from
  // folding identical functions together.
  volatile int x = __LINE__;
  static_cast<void>(x);
  ABSL_BLOCK_TAIL_CALL_OPTIMIZATION();
}
References ABSL_BLOCK_TAIL_CALL_OPTIMIZATION, and x.
Referenced by TEST().
regular_func()
int regular_func ()
Definition at line 96 of file symbolize_test.cc.
                     {
  return 0;
}
TEST()
TEST (Symbolize , Unimplemented)
Definition at line 574 of file symbolize_test.cc.
{
  char buf[64];
  EXPECT_FALSE(absl::Symbolize((void *)(&nonstatic_func), buf, sizeof(buf)));
  EXPECT_FALSE(absl::Symbolize((void *)(&static_func), buf, sizeof(buf)));
  EXPECT_FALSE(absl::Symbolize((void *)(&Foo::func), buf, sizeof(buf)));
}
References buf, Foo::func(), nonstatic_func(), and absl::Symbolize().