open spiel: open_spiel/examples/tabular_q_learning_example.cc File Reference
tabular_q_learning_example.cc File Reference
#include <memory>
#include <string>
#include <vector>
#include "open_spiel/abseil-cpp/absl/container/flat_hash_map.h"
#include "open_spiel/algorithms/tabular_q_learning.h"
#include "open_spiel/games/tic_tac_toe/tic_tac_toe.h"
#include "open_spiel/spiel.h"
#include "open_spiel/spiel_globals.h"
#include "open_spiel/spiel_utils.h"
Functions
Action GetOptimalAction (absl::flat_hash_map< std::pair< std::string, Action >, double > q_values, const std::unique_ptr< State > &state)
void SolveTicTacToe ()
void SolveTicTacToeEligibilityTraces ()
void SolveCatch ()
int main (int argc, char **argv)
Function Documentation
GetOptimalAction()
Action GetOptimalAction (absl::flat_hash_map< std::pair< std::string, Action >, double > q_values, const std::unique_ptr< State > & state)
Definition at line 31 of file tabular_q_learning_example.cc.
{
  std::vector<Action> legal_actions = state->LegalActions();
  Action optimal_action = open_spiel::kInvalidAction;
  double value = -1;
  for (const Action& action : legal_actions) {
    double q_val = q_values[{state->ToString(), action}];
    if (q_val >= value) {
      value = q_val;
      optimal_action = action;
    }
  }
  return optimal_action;
}
References action, open_spiel::kInvalidAction, optimal_action, and state.
Referenced by SolveCatch(), SolveTicTacToe(), and SolveTicTacToeEligibilityTraces().
main()
int main (int argc, char ** argv)
Definition at line 139 of file tabular_q_learning_example.cc.
{
  SolveTicTacToe();
  SolveTicTacToeEligibilityTraces();
  SolveCatch();
  return 0;
}
References SolveCatch(), SolveTicTacToe(), and SolveTicTacToeEligibilityTraces().
SolveCatch()
void SolveCatch ()
Definition at line 113 of file tabular_q_learning_example.cc.
                  {
  std::shared_ptr<const Game> game = open_spiel::LoadGame("catch");
  open_spiel::algorithms::TabularQLearningSolver tabular_q_learning_solver(
      game);
  int training_iter = 100000;
  while (training_iter-- > 0) {
    tabular_q_learning_solver.RunIteration();
  }
  const absl::flat_hash_map<std::pair<std::string, Action>, double>& q_values =
      tabular_q_learning_solver.GetQValueTable();
  int eval_iter = 1000;
  int total_reward = 0;
  while (eval_iter-- > 0) {
    std::unique_ptr<State> state = game->NewInitialState();
    while (!state->IsTerminal()) {
      Action optimal_action = GetOptimalAction(q_values, state);
      state->ApplyAction(optimal_action);
      total_reward += state->Rewards()[0];
    }
  }
  SPIEL_CHECK_GT(total_reward, 0);
}
References GetOptimalAction(), open_spiel::algorithms::TabularQLearningSolver::GetQValueTable(), open_spiel::LoadGame(), optimal_action, open_spiel::algorithms::TabularQLearningSolver::RunIteration(), SPIEL_CHECK_GT, and state.
Referenced by main().
SolveTicTacToe()
void SolveTicTacToe ()
Definition at line 48 of file tabular_q_learning_example.cc.
                      {
  std::shared_ptr<const Game> game = open_spiel::LoadGame("tic_tac_toe");
  open_spiel::algorithms::TabularQLearningSolver tabular_q_learning_solver(
      game);
  int iter = 100000;
  while (iter-- > 0) {
    tabular_q_learning_solver.RunIteration();
  }
  const absl::flat_hash_map<std::pair<std::string, Action>, double>& q_values =
      tabular_q_learning_solver.GetQValueTable();
  std::unique_ptr<State> state = game->NewInitialState();
  while (!state->IsTerminal()) {
    Action optimal_action = GetOptimalAction(q_values, state);
    state->ApplyAction(optimal_action);
  }
  // Tie.
  SPIEL_CHECK_EQ(state->Rewards()[0], 0);
  SPIEL_CHECK_EQ(state->Rewards()[1], 0);
}
References GetOptimalAction(), open_spiel::algorithms::TabularQLearningSolver::GetQValueTable(), open_spiel::LoadGame(), optimal_action, open_spiel::algorithms::TabularQLearningSolver::RunIteration(), SPIEL_CHECK_EQ, and state.
Referenced by main().
SolveTicTacToeEligibilityTraces()
void SolveTicTacToeEligibilityTraces ()
Definition at line 71 of file tabular_q_learning_example.cc.
{
  std::shared_ptr<const Game> game = open_spiel::LoadGame("tic_tac_toe");
  open_spiel::algorithms::TabularQLearningSolver
      tabular_q_learning_solver_lambda00(game, -1.0, 0.0001, 0.01, 0.99, 0.0);
  open_spiel::algorithms::TabularQLearningSolver
      tabular_q_learning_solver_lambda01(game, -1.0, 0.0001, 0.001, 0.99, 0.1);
  int count_tie_games_lambda00 = 0;
  int count_tie_games_lambda01 = 0;
  for (int i = 1; i < 10000; i++) {
    tabular_q_learning_solver_lambda00.RunIteration();
    const absl::flat_hash_map<std::pair<std::string, Action>, double>&
        q_values_lambda00 = tabular_q_learning_solver_lambda00.GetQValueTable();
    std::unique_ptr<State> state = game->NewInitialState();
    while (!state->IsTerminal()) {
      state->ApplyAction(GetOptimalAction(q_values_lambda00, state));
    }
    count_tie_games_lambda00 += state->Rewards()[0] == 0 ? 1 : 0;
  }
  for (int i = 1; i < 10000; i++) {
    tabular_q_learning_solver_lambda01.RunIteration();
    const absl::flat_hash_map<std::pair<std::string, Action>, double>&
        q_values_lambda01 = tabular_q_learning_solver_lambda01.GetQValueTable();
    std::unique_ptr<State> state = game->NewInitialState();
    while (!state->IsTerminal()) {
      state->ApplyAction(GetOptimalAction(q_values_lambda01, state));
    }
    count_tie_games_lambda01 += state->Rewards()[0] == 0 ? 1 : 0;
  }
  //  Q-Learning(0.1) gets equilibrium faster than Q-Learning(0.0).
  //  More ties in the same amount of time.
  SPIEL_CHECK_GT(count_tie_games_lambda01, count_tie_games_lambda00);
}
References GetOptimalAction(), open_spiel::algorithms::TabularQLearningSolver::GetQValueTable(), i, open_spiel::LoadGame(), open_spiel::algorithms::TabularQLearningSolver::RunIteration(), SPIEL_CHECK_GT, and state.
Referenced by main().