open spiel: open_spiel/games/tarok/tarok_test.cc File Reference
tarok_test.cc File Reference
#include "open_spiel/games/tarok/tarok.h"
#include "open_spiel/spiel.h"
#include "open_spiel/tests/basic_tests.h"
Namespaces
namespace open_spiel
"obstype", string, "reveal-nothing" (default) or "reveal-numturns"
namespace open_spiel::tarok
Functions
std::shared_ptr< const TarokGame > open_spiel::tarok::NewTarokGame (const GameParameters &params)
std::unique_ptr< TarokState > open_spiel::tarok::StateAfterActions (const GameParameters &params, const std::vector< Action > &actions)
bool open_spiel::tarok::AllActionsInOtherActions (const std::vector< Action > &actions, const std::vector< Action > &other_actions)
Action open_spiel::tarok::CardLongNameToAction (const std::string &long_name)
std::vector< Action > open_spiel::tarok::CardLongNamesToActions (const std::vector< std::string > &long_names)
template<typename T >
bool open_spiel::tarok::AllEq (const std::vector< T > &xs0, const std::vector< T > &xs1)
void open_spiel::tarok::BasicGameTests ()
void open_spiel::tarok::CardDeckShufflingSeedTest ()
void open_spiel::tarok::DealtCardsSizeTest (int num_players)
void open_spiel::tarok::DealtCardsContentTest (int num_players)
void open_spiel::tarok::PlayersCardsSortedTest ()
void open_spiel::tarok::CountCardsTest ()
void open_spiel::tarok::CardDealingPhaseTest ()
void open_spiel::tarok::BiddingPhase3PlayersTest1 ()
void open_spiel::tarok::BiddingPhase3PlayersTest2 ()
void open_spiel::tarok::BiddingPhase3PlayersTest3 ()
void open_spiel::tarok::BiddingPhase3PlayersTest4 ()
void open_spiel::tarok::BiddingPhase4PlayersTest1 ()
void open_spiel::tarok::BiddingPhase4PlayersTest2 ()
void open_spiel::tarok::BiddingPhase4PlayersTest3 ()
void open_spiel::tarok::BiddingPhase4PlayersTest4 ()
void open_spiel::tarok::BiddingPhase4PlayersTest5 ()
void open_spiel::tarok::TalonExchangePhaseTest1 ()
void open_spiel::tarok::TalonExchangePhaseTest2 ()
void open_spiel::tarok::TalonExchangePhaseTest3 ()
void open_spiel::tarok::TalonExchangePhaseTest4 ()
void open_spiel::tarok::TalonExchangePhaseTest5 ()
void open_spiel::tarok::TalonExchangePhaseTest6 ()
void open_spiel::tarok::TalonExchangePhaseTest7 ()
void open_spiel::tarok::TalonExchangePhaseTest8 ()
void open_spiel::tarok::TricksPlayingPhaseTest1 ()
void open_spiel::tarok::TricksPlayingPhaseTest2 ()
void open_spiel::tarok::TricksPlayingPhaseTest3 ()
void open_spiel::tarok::TricksPlayingPhaseTest4 ()
void open_spiel::tarok::TricksPlayingPhaseTest5 ()
void open_spiel::tarok::TricksPlayingPhaseTest6 ()
void open_spiel::tarok::TricksPlayingPhaseTest7 ()
void open_spiel::tarok::CapturedMondTest1 ()
void open_spiel::tarok::CapturedMondTest2 ()
void open_spiel::tarok::CapturedMondTest3 ()
void open_spiel::tarok::CapturedMondTest4 ()
void open_spiel::tarok::CapturedMondTest5 ()
void open_spiel::tarok::CapturedMondTest6 ()
void open_spiel::tarok::CapturedMondTest7 ()
void open_spiel::tarok::CapturedMondTest8 ()
void open_spiel::tarok::CapturedMondTest9 ()
int main (int argc, char **argv)
Variables
constexpr int open_spiel::tarok::kDealCardsAction = 0
constexpr int open_spiel::tarok::kBidTwoAction = 3
constexpr int open_spiel::tarok::kBidOneAction = 4
constexpr int open_spiel::tarok::kBidSoloTwoAction = 6
constexpr int open_spiel::tarok::kBidBeggarAction = 8
constexpr int open_spiel::tarok::kBidSoloWithoutAction = 9
constexpr int open_spiel::tarok::kBidOpenBeggarAction = 10
constexpr int open_spiel::tarok::kBidColourValatAction = 11
constexpr int open_spiel::tarok::kBidValatWithoutAction = 12
const std::array< Card, 54 > open_spiel::tarok::card_deck = InitializeCardDeck()
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 1401 of file tarok_test.cc.
{
  open_spiel::tarok::BasicGameTests();
  // cards tests
  open_spiel::tarok::CardDeckShufflingSeedTest();
  open_spiel::tarok::DealtCardsSizeTest(3);
  open_spiel::tarok::DealtCardsSizeTest(4);
  open_spiel::tarok::DealtCardsContentTest(3);
  open_spiel::tarok::DealtCardsContentTest(4);
  open_spiel::tarok::PlayersCardsSortedTest();
  open_spiel::tarok::CountCardsTest();
  open_spiel::tarok::CardDealingPhaseTest();
  // bidding phase tests
  open_spiel::tarok::BiddingPhase3PlayersTest1();
  open_spiel::tarok::BiddingPhase3PlayersTest2();
  open_spiel::tarok::BiddingPhase3PlayersTest3();
  open_spiel::tarok::BiddingPhase3PlayersTest4();
  open_spiel::tarok::BiddingPhase4PlayersTest1();
  open_spiel::tarok::BiddingPhase4PlayersTest2();
  open_spiel::tarok::BiddingPhase4PlayersTest3();
  open_spiel::tarok::BiddingPhase4PlayersTest4();
  open_spiel::tarok::BiddingPhase4PlayersTest5();
  // talon exchange phase tests
  open_spiel::tarok::TalonExchangePhaseTest1();
  open_spiel::tarok::TalonExchangePhaseTest2();
  open_spiel::tarok::TalonExchangePhaseTest3();
  open_spiel::tarok::TalonExchangePhaseTest4();
  open_spiel::tarok::TalonExchangePhaseTest5();
  open_spiel::tarok::TalonExchangePhaseTest6();
  open_spiel::tarok::TalonExchangePhaseTest7();
  open_spiel::tarok::TalonExchangePhaseTest8();
  // tricks playing phase tests
  open_spiel::tarok::TricksPlayingPhaseTest1();
  open_spiel::tarok::TricksPlayingPhaseTest2();
  open_spiel::tarok::TricksPlayingPhaseTest3();
  open_spiel::tarok::TricksPlayingPhaseTest4();
  open_spiel::tarok::TricksPlayingPhaseTest5();
  open_spiel::tarok::TricksPlayingPhaseTest6();
  open_spiel::tarok::TricksPlayingPhaseTest7();
  // captured mond tests
  open_spiel::tarok::CapturedMondTest1();
  open_spiel::tarok::CapturedMondTest2();
  open_spiel::tarok::CapturedMondTest3();
  open_spiel::tarok::CapturedMondTest4();
  open_spiel::tarok::CapturedMondTest5();
  open_spiel::tarok::CapturedMondTest6();
  open_spiel::tarok::CapturedMondTest7();
  open_spiel::tarok::CapturedMondTest8();
  open_spiel::tarok::CapturedMondTest9();
}
References open_spiel::tarok::BasicGameTests(), open_spiel::tarok::BiddingPhase3PlayersTest1(), open_spiel::tarok::BiddingPhase3PlayersTest2(), open_spiel::tarok::BiddingPhase3PlayersTest3(), open_spiel::tarok::BiddingPhase3PlayersTest4(), open_spiel::tarok::BiddingPhase4PlayersTest1(), open_spiel::tarok::BiddingPhase4PlayersTest2(), open_spiel::tarok::BiddingPhase4PlayersTest3(), open_spiel::tarok::BiddingPhase4PlayersTest4(), open_spiel::tarok::BiddingPhase4PlayersTest5(), open_spiel::tarok::CapturedMondTest1(), open_spiel::tarok::CapturedMondTest2(), open_spiel::tarok::CapturedMondTest3(), open_spiel::tarok::CapturedMondTest4(), open_spiel::tarok::CapturedMondTest5(), open_spiel::tarok::CapturedMondTest6(), open_spiel::tarok::CapturedMondTest7(), open_spiel::tarok::CapturedMondTest8(), open_spiel::tarok::CapturedMondTest9(), open_spiel::tarok::CardDealingPhaseTest(), open_spiel::tarok::CardDeckShufflingSeedTest(), open_spiel::tarok::CountCardsTest(), open_spiel::tarok::DealtCardsContentTest(), open_spiel::tarok::DealtCardsSizeTest(), open_spiel::tarok::PlayersCardsSortedTest(), open_spiel::tarok::TalonExchangePhaseTest1(), open_spiel::tarok::TalonExchangePhaseTest2(), open_spiel::tarok::TalonExchangePhaseTest3(), open_spiel::tarok::TalonExchangePhaseTest4(), open_spiel::tarok::TalonExchangePhaseTest5(), open_spiel::tarok::TalonExchangePhaseTest6(), open_spiel::tarok::TalonExchangePhaseTest7(), open_spiel::tarok::TalonExchangePhaseTest8(), open_spiel::tarok::TricksPlayingPhaseTest1(), open_spiel::tarok::TricksPlayingPhaseTest2(), open_spiel::tarok::TricksPlayingPhaseTest3(), open_spiel::tarok::TricksPlayingPhaseTest4(), open_spiel::tarok::TricksPlayingPhaseTest5(), open_spiel::tarok::TricksPlayingPhaseTest6(), and open_spiel::tarok::TricksPlayingPhaseTest7().