open spiel: open_spiel/examples/universal_poker_mccfr_acpc_gamedef_example.cc File Reference
universal_poker_mccfr_acpc_gamedef_example.cc File Reference
#include <iostream>
#include <memory>
#include <string>
#include "open_spiel/abseil-cpp/absl/flags/flag.h"
#include "open_spiel/abseil-cpp/absl/flags/parse.h"
#include "open_spiel/algorithms/external_sampling_mccfr.h"
#include "open_spiel/algorithms/tabular_exploitability.h"
#include "open_spiel/games/universal_poker/universal_poker.h"
#include "open_spiel/spiel.h"
#include "open_spiel/spiel_utils.h"
Functions
ABSL_FLAG (std::string, acpc_gamedef, kCustom3PlayerAcpcGamedef, "ACPC gamedef.")
ABSL_FLAG (int, num_iters, 2000, "How many iters to run for.")
ABSL_FLAG (int, report_every, 500, "How often to report exploitability.")
int main (int argc, char **argv)
Variables
constexpr char kCustom3PlayerAcpcGamedef []
Function Documentation
ABSL_FLAG() [1/3]
ABSL_FLAG (int , num_iters , 2000 , "How many iters to run for.")
ABSL_FLAG() [2/3]
ABSL_FLAG (int , report_every , 500 , "How often to report exploitability.")
ABSL_FLAG() [3/3]
ABSL_FLAG (std::string , acpc_gamedef , kCustom3PlayerAcpcGamedef , "ACPC gamedef.")
main()
int main (int argc, char ** argv)
Definition at line 57 of file universal_poker_mccfr_acpc_gamedef_example.cc.
{
  absl::ParseCommandLine(argc, argv);
  std::cout << "Input ACPC gamedef (raw): " << absl::GetFlag(FLAGS_acpc_gamedef)
            << std::endl;
  std::shared_ptr<const open_spiel::Game> game =
      open_spiel::universal_poker::LoadUniversalPokerGameFromACPCGamedef(
          absl::GetFlag(FLAGS_acpc_gamedef));
  // Downcasting to UniversalPokerGame so we can call GetACPCGame(), which isn't
  // on the higher level open_spiel::Game.
  const open_spiel::universal_poker::UniversalPokerGame& game_down_cast =
      open_spiel::down_cast<
          const open_spiel::universal_poker::UniversalPokerGame&>(*game);
  std::cout << "Resulting ACPC gamedef used for universal_poker:\n"
            << game_down_cast.GetACPCGame()->ToString() << std::endl;
  open_spiel::algorithms::ExternalSamplingMCCFRSolver solver(*game);
  std::cerr << "Starting MCCFR on " << game->GetType().short_name << "..."
            << std::endl;
  for (int i = 0; i < absl::GetFlag(FLAGS_num_iters); ++i) {
    solver.RunIteration();
    if (i % absl::GetFlag(FLAGS_report_every) == 0 ||
        i == absl::GetFlag(FLAGS_num_iters) - 1) {
      double exploitability = open_spiel::algorithms::Exploitability(
          *game, *solver.AveragePolicy());
      std::cerr << "Iteration " << i << " exploitability=" << exploitability
                << std::endl;
    }
  }
}
References open_spiel::algorithms::ExternalSamplingMCCFRSolver::AveragePolicy(), open_spiel::down_cast(), open_spiel::algorithms::Exploitability(), open_spiel::universal_poker::UniversalPokerGame::GetACPCGame(), absl::GetFlag(), i, open_spiel::universal_poker::LoadUniversalPokerGameFromACPCGamedef(), absl::ParseCommandLine(), open_spiel::algorithms::ExternalSamplingMCCFRSolver::RunIteration(), and open_spiel::universal_poker::acpc_cpp::ACPCGame::ToString().
Variable Documentation
kCustom3PlayerAcpcGamedef
char kCustom3PlayerAcpcGamedef[] constexpr
Initial value:
= R"""(
# (Empty lines and lines starting with an '#' are all ignored)
GAMEDEF
nolimit
numPlayers = 3
numRounds = 1
numSuits = 2
numRanks = 4
numHoleCards = 1
# Set per player, so 3 total
stack = 15 15 15
blind = 0 1 0
# Set per round
firstPlayer = 3
numBoardCards = 0
END GAMEDEF
)"""
Definition at line 27 of file universal_poker_mccfr_acpc_gamedef_example.cc.