open spiel: open_spiel/abseil-cpp/absl/flags/internal/usage_test.cc File Reference
usage_test.cc File Reference
#include "absl/flags/internal/usage.h"
#include <stdint.h>
#include <sstream>
#include <string>
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "absl/flags/flag.h"
#include "absl/flags/internal/parse.h"
#include "absl/flags/internal/path_util.h"
#include "absl/flags/internal/program_name.h"
#include "absl/flags/reflection.h"
#include "absl/flags/usage.h"
#include "absl/flags/usage_config.h"
#include "absl/strings/match.h"
#include "absl/strings/string_view.h"
Classes
struct UDT
Functions
ABSL_FLAG (int, usage_reporting_test_flag_01, 101, "usage_reporting_test_flag_01 help message")
ABSL_FLAG (bool, usage_reporting_test_flag_02, false, "usage_reporting_test_flag_02 help message")
ABSL_FLAG (double, usage_reporting_test_flag_03, 1.03, "usage_reporting_test_flag_03 help message")
ABSL_FLAG (int64_t, usage_reporting_test_flag_04, 1000000000000004L, "usage_reporting_test_flag_04 help message")
ABSL_FLAG (UDT, usage_reporting_test_flag_05, {}, "usage_reporting_test_flag_05 help message")
ABSL_FLAG (std::string, usage_reporting_test_flag_06, {}, "usage_reporting_test_flag_06 help message.\n" "\n" "Some more help.\n" "Even more long long long long long long long long long long long long " "help message.")
int main (int argc, char *argv[])
Function Documentation
ABSL_FLAG() [1/6]
ABSL_FLAG (bool , usage_reporting_test_flag_02 , false , "usage_reporting_test_flag_02 help message")
ABSL_FLAG() [2/6]
ABSL_FLAG (double , usage_reporting_test_flag_03 , 1. 03, "usage_reporting_test_flag_03 help message")
ABSL_FLAG() [3/6]
ABSL_FLAG (int , usage_reporting_test_flag_01 , 101 , "usage_reporting_test_flag_01 help message")
ABSL_FLAG() [4/6]
ABSL_FLAG (int64_t , usage_reporting_test_flag_04 , 1000000000000004L , "usage_reporting_test_flag_04 help message")
ABSL_FLAG() [5/6]
ABSL_FLAG (std::string , usage_reporting_test_flag_06 , {} , "usage_reporting_test_flag_06 help message.\n" "\n" "Some more help.\n" "Even more long long long long long long long long long long long long " "help message.")
ABSL_FLAG() [6/6]
ABSL_FLAG (UDT , usage_reporting_test_flag_05 , {} , "usage_reporting_test_flag_05 help message")
main()
int main (int argc, char * argv[])
Definition at line 495 of file usage_test.cc.
{
  (void)absl::GetFlag(FLAGS_undefok);  // Force linking of parse.cc
  flags::SetProgramInvocationName("usage_test");
#if !defined(GTEST_HAS_ABSL) || !GTEST_HAS_ABSL
  // GoogleTest calls absl::SetProgramUsageMessage() already.
  absl::SetProgramUsageMessage(kTestUsageMessage);
#endif
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
References absl::GetFlag(), absl::flags_internal::SetProgramInvocationName(), and absl::SetProgramUsageMessage().