open spiel: open_spiel/examples/value_iteration_example.cc File Reference
value_iteration_example.cc File Reference
#include <memory>
#include <string>
#include "open_spiel/abseil-cpp/absl/flags/flag.h"
#include "open_spiel/abseil-cpp/absl/flags/parse.h"
#include "open_spiel/abseil-cpp/absl/strings/str_format.h"
#include "open_spiel/algorithms/value_iteration.h"
#include "open_spiel/spiel.h"
#include "open_spiel/spiel_utils.h"
Functions
ABSL_FLAG (std::string, game, "tic_tac_toe", "The name of the game to play.")
ABSL_FLAG (int, depth_limit, -1, "Depth limit until which to compute value iteration.")
ABSL_FLAG (double, threshold, 0.01, "Threshold accuracy at which to stop value iteration.")
int main (int argc, char **argv)
Function Documentation
ABSL_FLAG() [1/3]
ABSL_FLAG (double , threshold , 0. 01, "Threshold accuracy at which to stop value iteration.")
ABSL_FLAG() [2/3]
ABSL_FLAG (int , depth_limit , - 1, "Depth limit until which to compute value iteration.")
ABSL_FLAG() [3/3]
ABSL_FLAG (std::string , game , "tic_tac_toe" , "The name of the game to play.")
main()
int main (int argc, char ** argv)
Definition at line 32 of file value_iteration_example.cc.
{
  absl::ParseCommandLine(argc, argv);
  std::shared_ptr<const open_spiel::Game> game =
      open_spiel::LoadGame(absl::GetFlag(FLAGS_game));
  auto solution = open_spiel::algorithms::ValueIteration(
      *game, absl::GetFlag(FLAGS_depth_limit), absl::GetFlag(FLAGS_threshold));
  for (const auto& kv : solution) {
    std::cerr << "State: " << std::endl
              << kv.first << std::endl
              << "Value: " << kv.second << std::endl;
  }
  if (absl::GetFlag(FLAGS_game) == "tic_tac_toe") {
    std::string initial_state = "...\n...\n...";
    std::string cross_win_state = "...\n...\n.ox";
    std::string naught_win_state = "x..\noo.\nxx.";
    SPIEL_CHECK_EQ(solution[initial_state], 0);
    SPIEL_CHECK_EQ(solution[cross_win_state], 1);
    SPIEL_CHECK_EQ(solution[naught_win_state], -1);
  }
}
References absl::GetFlag(), open_spiel::LoadGame(), absl::ParseCommandLine(), SPIEL_CHECK_EQ, and open_spiel::algorithms::ValueIteration().