open spiel: open_spiel.python.voting.base.PreferenceProfile Class Reference
open_spiel.python.voting.base.PreferenceProfile Class Reference
Public Member Functions
__init__ (self, Union[List[PreferenceList], List[WeightedVote], None] votes=None, Union[List[AlternativeId], None] alternatives=None)
add_vote (self, Union[PreferenceList, WeightedVote] vote, int weight=1)
add_vote_from_values (self, Union[List[float], List[int]] values, float tie_tolerance=1e-10, int weight=1)
List[WeightedVote] votes (self)
List[AlternativeId] alternatives (self)
Dict[AlternativeId, int] alternatives_dict (self)
int num_alternatives (self)
int num_votes (self)
np.ndarray pref_matrix (self)
np.ndarray margin_matrix (self)
condorcet_winner (self, bool strong=True, Union[np.ndarray, None] margin_matrix=None)
group (self)
ungroup (self)
str __str__ (self)
int total_weight (self)
int get_weight (self, PreferenceList vote)
set_weight (self, int index, int value)
set_all_weights (self, int value)
Protected Member Functions
_register_index_based_alternatives (self, int num)
_register_alternative (self, AlternativeId alternative)
_register_alternatives_from_votes (self)
Protected Attributes
_alternatives_ids
_votes
Static Protected Attributes
List _votes [WeightedVote]
Dict _alternatives_dict [AlternativeId, int]
List _alternatives_ids [AlternativeId]
Detailed Description
Base class for preference profiles.
IMPORTANT NOTE: see the assumptions below about indexing of alternatives.
Definition at line 38 of file base.py.
Constructor & Destructor Documentation
__init__()
open_spiel.python.voting.base.PreferenceProfile.__init__ (self, Union[List[PreferenceList], List[WeightedVote], None] votes = None, Union[List[AlternativeId], None] alternatives = None)
Initialize the preference profile.
Args:
  votes: Either (i) a list of lists, each containing ids of alternatives,
    e.g. ["a", "b", "c"] signifiying a > b > c, or None for no votes, or
    (ii) a list of Vote tuples containing the weight and vote.
  alternatives: a list of alternatives ids.
Note regarding how alternatives are indexed: if the second argument is
passed, then the index of each alternative (e.g. when calling functions
like margin_matrix etc.) will be assigned 0 up to the (number of
alternatives) - 1 in the order of the list. If this argument is omitted,
then alternatives will be indexed depending on when they are first seen
(i.e. via a add_vote method) and so (only) in the latter case the indexing
could depend on the order votes are added. Hence it is advised to pass in
the list of alternatives to this function whenever they are known ahead of
time.
The alternatives_dict property below will return a dictionary of alternative
IDs to index.
Definition at line 48 of file base.py.
  ):
    """Initialize the preference profile.
    Args:
      votes: Either (i) a list of lists, each containing ids of alternatives,
        e.g. ["a", "b", "c"] signifiying a > b > c, or None for no votes, or
        (ii) a list of Vote tuples containing the weight and vote.
      alternatives: a list of alternatives ids.
    Note regarding how alternatives are indexed: if the second argument is
    passed, then the index of each alternative (e.g. when calling functions
    like margin_matrix etc.) will be assigned 0 up to the (number of
    alternatives) - 1 in the order of the list. If this argument is omitted,
    then alternatives will be indexed depending on when they are first seen
    (i.e. via a add_vote method) and so (only) in the latter case the indexing
    could depend on the order votes are added. Hence it is advised to pass in
    the list of alternatives to this function whenever they are known ahead of
    time.
    The alternatives_dict property below will return a dictionary of alternative
    IDs to index.
    """
    # List of Vote named tuples from above.
    self._votes: List[WeightedVote] = []
    # alternative id -> index (used for registering alternatives)
    self._alternatives_dict: Dict[AlternativeId, int] = {}
    # IDs (labels) of each alternative (usually strings). The alternative's
    # index is then the index of this array.
    self._alternatives_ids: List[AlternativeId] = []
    # Register the alternatives and add the votes, if any are provided.
    if alternatives is not None:
      for alternative in alternatives:
        self._register_alternative(alternative)
    if votes is not None:
      for vote in votes:
        self.add_vote(vote)
    if self._votes and not self._alternatives_ids:
      self._register_alternatives_from_votes()
References open_spiel.python.voting.base.PreferenceProfile._alternatives_dict, open_spiel.python.voting.base.PreferenceProfile._alternatives_ids, open_spiel.python.voting.base.PreferenceProfile._register_alternative(), open_spiel.python.voting.base.PreferenceProfile._register_alternatives_from_votes(), open_spiel.python.voting.base.PreferenceProfile._votes, and open_spiel.python.voting.base.PreferenceProfile.add_vote().
Member Function Documentation
__str__()
str open_spiel.python.voting.base.PreferenceProfile.__str__ (self)
Get a string representation of this profile.
Definition at line 306 of file base.py.
  def __str__(self) -> str:
    """Get a string representation of this profile."""
    string = ""
    for vote in self._votes:
      string += str(vote) + "\n"
    return string
References open_spiel.python.voting.base.PreferenceProfile._votes.
_register_alternative()
open_spiel.python.voting.base.PreferenceProfile._register_alternative (self, AlternativeId alternative) protected
Add this alternative to interal recors if not already there.
Definition at line 97 of file base.py.
  def _register_alternative(self, alternative: AlternativeId):
    """Add this alternative to interal recors if not already there."""
    idx = self._alternatives_dict.get(alternative)
    if idx is None:
      self._alternatives_ids.append(alternative)
      self._alternatives_dict[alternative] = len(self._alternatives_ids) - 1
    assert (self._alternatives_ids[self._alternatives_dict[alternative]]
            == alternative)
References open_spiel.python.voting.base.PreferenceProfile._alternatives_dict, open_spiel.python.voting.base.PreferenceProfile._alternatives_ids, open_spiel.python.voting.base.PreferenceProfile._register_alternative(), and open_spiel.python.voting.base.PreferenceProfile._votes.
Referenced by open_spiel.python.voting.base.PreferenceProfile.__init__(), open_spiel.python.voting.base.PreferenceProfile._register_alternative(), open_spiel.python.voting.base.PreferenceProfile._register_index_based_alternatives(), and open_spiel.python.voting.base.PreferenceProfile.add_vote().
_register_alternatives_from_votes()
open_spiel.python.voting.base.PreferenceProfile._register_alternatives_from_votes (self) protected
Definition at line 106 of file base.py.
  def _register_alternatives_from_votes(self):
    for vote in self._votes:
      for alternative in vote:
        self._register_alternative(alternative)
Referenced by open_spiel.python.voting.base.PreferenceProfile.__init__().
_register_index_based_alternatives()
open_spiel.python.voting.base.PreferenceProfile._register_index_based_alternatives (self, int num) protected
Register indices up to num-1 as possible alternatives.
Definition at line 92 of file base.py.
  def _register_index_based_alternatives(self, num: int):
    """Register indices up to num-1 as possible alternatives."""
    for idx in range(num):
      self._register_alternative(idx)
References open_spiel.python.voting.base.PreferenceProfile._register_alternative().
Referenced by open_spiel.python.voting.base.PreferenceProfile.add_vote_from_values().
add_vote()
open_spiel.python.voting.base.PreferenceProfile.add_vote (self, Union[PreferenceList, WeightedVote] vote, int weight = 1)
Add a vote to this preference profile.
Args:
  vote: Either (i) a list of ids, e.g. ["a", "b", "c"] signifying a > b > c,
      or, (ii) a Vote tuple containing both the weight and the vote of the
      form in (i).
  weight: the count, i.e. how many people have submitted this vote. Only
      used when the first argument is a list.
Definition at line 111 of file base.py.
  ):
    """Add a vote to this preference profile.
    Args:
      vote: Either (i) a list of ids, e.g. ["a", "b", "c"] signifying a > b > c,
          or, (ii) a Vote tuple containing both the weight and the vote of the
          form in (i).
      weight: the count, i.e. how many people have submitted this vote. Only
          used when the first argument is a list.
    """
    # For now support only integral weights (counts). Makes some things easier,
    # like N(x,y) and the margin matrices can be integers. Should be easy to
    # extend if we need to.
    assert isinstance(weight, int)
    assert weight > 0
    if isinstance(vote, WeightedVote):
      self._votes.append(vote)
      for alternative in vote.vote:
        self._register_alternative(alternative)
    else:
      weighted_vote = WeightedVote(weight, vote)
      self._votes.append(weighted_vote)
      for alternative in vote:
        self._register_alternative(alternative)
References open_spiel.python.voting.base.PreferenceProfile._register_alternative(), and open_spiel.python.voting.base.PreferenceProfile._votes.
Referenced by open_spiel.python.voting.base.PreferenceProfile.__init__(), and open_spiel.python.voting.base.PreferenceProfile.add_vote_from_values().
add_vote_from_values()
open_spiel.python.voting.base.PreferenceProfile.add_vote_from_values (self, Union[List[float], List[int]] values, float tie_tolerance = 1e-10, int weight = 1)
Adds a vote from a list of values.
Note: this list is expected to cover all of the alternatives.
WARNING: to ensure that ties are broken randomly, small random values are
added to the values (within [0, tie_tolarance]). If the values are smaller
than the tie_tolerance, this can be disabled by setting the tie_tolerance to
0.
Does not add the vote if the values are all within tie_tolerance of each
other. For all others, adds a uniform * tie_tolerance to break ties.
If the alternatives ids are not registered for this profile yet, then this
method uses the indices of these values as the alternative IDs. Otherwise,
the length of the array must be equal to the number of alternatives.
Args:
  values: a list or numpy array of values for the alternative labeled by
      the index.
  tie_tolerance: a numerical threshold for determining ties.
  weight: the weight for the resulting vote.
Definition at line 138 of file base.py.
  ):
    """Adds a vote from a list of values.
    Note: this list is expected to cover all of the alternatives.
    WARNING: to ensure that ties are broken randomly, small random values are
    added to the values (within [0, tie_tolarance]). If the values are smaller
    than the tie_tolerance, this can be disabled by setting the tie_tolerance to
    0.
    Does not add the vote if the values are all within tie_tolerance of each
    other. For all others, adds a uniform * tie_tolerance to break ties.
    If the alternatives ids are not registered for this profile yet, then this
    method uses the indices of these values as the alternative IDs. Otherwise,
    the length of the array must be equal to the number of alternatives.
    Args:
      values: a list or numpy array of values for the alternative labeled by
          the index.
      tie_tolerance: a numerical threshold for determining ties.
      weight: the weight for the resulting vote.
    """
    # Check if any alternatives are registered for this profile. If not, then
    # first register ids for them all first.
    if not self._alternatives_ids:
      self._register_index_based_alternatives(len(values))
    else:
      assert len(values) == len(self._alternatives_ids)
    vals_copy = np.copy(np.asarray(values))
    max_val = vals_copy.max()
    min_val = vals_copy.min()
    if (max_val - min_val) < tie_tolerance:
      print(f"Warning: not casting vote from values: {vals_copy}")
      return
    # Add noise for tie_breaking
    vals_copy += tie_tolerance * np.random.uniform(size=len(vals_copy))
    vote = np.argsort(-vals_copy)
    # The vote is currently based on indices. Now convert to names.
    alternatives = self.alternatives
    assert alternatives
    assert len(alternatives) == len(vote)
    named_vote = []
    for idx in vote:
      assert 0 <= idx < len(alternatives)
      named_vote.append(alternatives[idx])
    self.add_vote(named_vote, weight=weight)
References open_spiel.python.voting.base.PreferenceProfile._alternatives_ids, open_spiel.python.voting.base.PreferenceProfile._register_index_based_alternatives(), open_spiel.python.voting.base.PreferenceProfile.add_vote(), and open_spiel.python.voting.base.PreferenceProfile.alternatives().
alternatives()
List[AlternativeId] open_spiel.python.voting.base.PreferenceProfile.alternatives (self)
Returns a list of alternatives.
Definition at line 197 of file base.py.
  def alternatives(self) -> List[AlternativeId]:
    """Returns a list of alternatives."""
    return self._alternatives_ids
References open_spiel.python.voting.base.PreferenceProfile._alternatives_ids.
Referenced by open_spiel.python.voting.base.PreferenceProfile.add_vote_from_values().
alternatives_dict()
Dict[AlternativeId, int] open_spiel.python.voting.base.PreferenceProfile.alternatives_dict (self)
Returns a dict of alternative id -> index for each alternative.
Definition at line 202 of file base.py.
  def alternatives_dict(self) -> Dict[AlternativeId, int]:
    """Returns a dict of alternative id -> index for each alternative."""
    return self._alternatives_dict
References open_spiel.python.voting.base.PreferenceProfile._alternatives_dict, and open_spiel.python.voting.base.PreferenceProfile._alternatives_ids.
condorcet_winner()
open_spiel.python.voting.base.PreferenceProfile.condorcet_winner (self, bool strong = True, Union[np.ndarray, None] margin_matrix = None)
Returns the Condorcet winner(s).
Args:
  strong: whether it's a strong Condorcet winner (see below).
  margin_matrix: the margin matrix (optional: only used to to avoid
      recomputing).
Returns:
  A list containing the Condorcet winners. There may be multiple weak
  Condorcet winners, but there is at most one strong winner.
A strong Condorcet winner is an alternative a* in A such that for all
a' in A: N(a*, a') > N(a', a*). A weak Condorcet winner is a similar
definition using great-than-or-equal-to >=.
Definition at line 246 of file base.py.
  ):
    """Returns the Condorcet winner(s).
    Args:
      strong: whether it's a strong Condorcet winner (see below).
      margin_matrix: the margin matrix (optional: only used to to avoid
          recomputing).
    Returns:
      A list containing the Condorcet winners. There may be multiple weak
      Condorcet winners, but there is at most one strong winner.
    A strong Condorcet winner is an alternative a* in A such that for all
    a' in A: N(a*, a') > N(a', a*). A weak Condorcet winner is a similar
    definition using great-than-or-equal-to >=.
    """
    condorcet_winners = []
    if margin_matrix is None:
      margin_matrix = self.margin_matrix()
    for alt_idx in range(self.num_alternatives()):
      if strong and np.all(np.delete(margin_matrix[alt_idx] > 0, alt_idx)):
        # Don't count the diagonal 0 in the checking of > 0.
        condorcet_winners.append(self._alternatives_ids[alt_idx])
      elif not strong and np.all(margin_matrix[alt_idx] >= 0):
        condorcet_winners.append(self._alternatives_ids[alt_idx])
    if strong:
      assert len(condorcet_winners) <= 1
    return condorcet_winners
References open_spiel.python.voting.base.PreferenceProfile._alternatives_ids, open_spiel.python.voting.base.PreferenceProfile.margin_matrix(), and open_spiel.python.voting.base.PreferenceProfile.num_alternatives().
get_weight()
int open_spiel.python.voting.base.PreferenceProfile.get_weight (self, PreferenceList vote)
Definition at line 319 of file base.py.
  def get_weight(self, vote: PreferenceList) -> int:
    total_weight = 0
    for v in self._votes:
      if v.vote == vote:
        total_weight += v.weight
    return total_weight
group()
open_spiel.python.voting.base.PreferenceProfile.group (self)
Group up the votes.
This will combine multiple identical votes into the smallest set of unique
weighted votes.
Definition at line 277 of file base.py.
  def group(self):
    """Group up the votes.
    This will combine multiple identical votes into the smallest set of unique
    weighted votes.
    """
    old_votes = self._votes
    self._votes = []
    while old_votes:
      vote = old_votes[0].vote
      total_weight = old_votes[0].weight
      del old_votes[0]
      i = 0
      while i < len(old_votes):
        if old_votes[i].vote == vote:
          total_weight += old_votes[i].weight
          del old_votes[i]
        else:
          i += 1
      self._votes.append(WeightedVote(total_weight, vote))
References open_spiel.python.voting.base.PreferenceProfile._votes.
margin_matrix()
np.ndarray open_spiel.python.voting.base.PreferenceProfile.margin_matrix (self)
Returns the margin matrix for this profile.
Define N(x,y) = number of voters that prefer x > y. The margin matrix
is a num_alternatives x num_alternatives whose entry at (r,c) is:
delta(r,c) = N(r, c) - N(c, r). The r and c refer to columns, which
correspond to the indices in the list returned by self.alternatives.
Definition at line 235 of file base.py.
  def margin_matrix(self) -> np.ndarray:
    """Returns the margin matrix for this profile.
    Define N(x,y) = number of voters that prefer x > y. The margin matrix
    is a num_alternatives x num_alternatives whose entry at (r,c) is:
    delta(r,c) = N(r, c) - N(c, r). The r and c refer to columns, which
    correspond to the indices in the list returned by self.alternatives.
    """
    pref_matrix = self.pref_matrix()
    return pref_matrix - pref_matrix.T
References open_spiel.python.voting.base.PreferenceProfile.pref_matrix().
Referenced by open_spiel.python.voting.base.PreferenceProfile.condorcet_winner().
num_alternatives()
int open_spiel.python.voting.base.PreferenceProfile.num_alternatives (self)
Definition at line 206 of file base.py.
  def num_alternatives(self) -> int:
    return len(self._alternatives_ids)
Referenced by open_spiel.python.voting.base.PreferenceProfile.condorcet_winner(), and open_spiel.python.voting.base.PreferenceProfile.pref_matrix().
num_votes()
int open_spiel.python.voting.base.PreferenceProfile.num_votes (self)
Returns the number of votes.
Definition at line 209 of file base.py.
  def num_votes(self) -> int:
    """Returns the number of votes."""
    total = 0
    for vote in self._votes:
      total += vote.weight
    return total
References open_spiel.python.voting.base.PreferenceProfile._votes.
pref_matrix()
np.ndarray open_spiel.python.voting.base.PreferenceProfile.pref_matrix (self)
Returns the candidate preference matrix for this profile.
Define N(x,y) as number of voters that prefer x > y. The candidate
preference matrix is one whose entries are N(x,y) for row x and column y.
Definition at line 216 of file base.py.
  def pref_matrix(self) -> np.ndarray:
    """Returns the candidate preference matrix for this profile.
    Define N(x,y) as number of voters that prefer x > y. The candidate
    preference matrix is one whose entries are N(x,y) for row x and column y.
    """
    # First map the alternatives to indices.
    m = self.num_alternatives()
    mat = np.zeros(shape=(m, m), dtype=np.int32)
    for vote in self._votes:
      vote_len = len(vote.vote)
      for i in range(vote_len):
        for j in range(i + 1, vote_len):
          # vote.vote[i] > vote.vote[j]
          idx_i = self._alternatives_dict[vote.vote[i]]
          idx_j = self._alternatives_dict[vote.vote[j]]
          mat[idx_i, idx_j] += vote.weight
    return mat
References open_spiel.python.voting.base.PreferenceProfile._alternatives_dict, open_spiel.python.voting.base.PreferenceProfile._votes, and open_spiel.python.voting.base.PreferenceProfile.num_alternatives().
Referenced by open_spiel.python.voting.base.PreferenceProfile.margin_matrix().
set_all_weights()
open_spiel.python.voting.base.PreferenceProfile.set_all_weights (self, int value)
Sets the weight of all the votes to the specified value.
Definition at line 329 of file base.py.
  def set_all_weights(self, value: int):
    """Sets the weight of all the votes to the specified value."""
    for i in range(len(self._votes)):
      self.set_weight(i, value)
References open_spiel.python.voting.base.PreferenceProfile._votes, and open_spiel.python.voting.base.PreferenceProfile.set_weight().
set_weight()
open_spiel.python.voting.base.PreferenceProfile.set_weight (self, int index, int value)
Definition at line 326 of file base.py.
  def set_weight(self, index: int, value: int):
    self._votes[index] = self._votes[index]._replace(weight=value)
Referenced by open_spiel.python.voting.base.PreferenceProfile.set_all_weights().
total_weight()
int open_spiel.python.voting.base.PreferenceProfile.total_weight (self)
Definition at line 313 of file base.py.
  def total_weight(self) -> int:
    w = 0
    for vote in self._votes:
      w += vote.weight
    return w
ungroup()
open_spiel.python.voting.base.PreferenceProfile.ungroup (self)
Splits the votes into individual votes (each with weight of 1).
Definition at line 298 of file base.py.
  def ungroup(self):
    """Splits the votes into individual votes (each with weight of 1)."""
    old_votes = self._votes
    self._votes = []
    for vote in old_votes:
      for _ in range(vote.weight):
        self._votes.append(WeightedVote(1, vote.vote))
References open_spiel.python.voting.base.PreferenceProfile._votes.
votes()
List[WeightedVote] open_spiel.python.voting.base.PreferenceProfile.votes (self)
Returns a list of votes.
Definition at line 192 of file base.py.
  def votes(self) -> List[WeightedVote]:
    """Returns a list of votes."""
    return self._votes
References open_spiel.python.voting.base.PreferenceProfile._votes.
Member Data Documentation
_alternatives_dict
Dict open_spiel.python.voting.base.PreferenceProfile._alternatives_dict [AlternativeId, int] static protected
Definition at line 44 of file base.py.
Referenced by open_spiel.python.voting.base.PreferenceProfile.__init__(), open_spiel.python.voting.base.PreferenceProfile._register_alternative(), open_spiel.python.voting.base.PreferenceProfile.alternatives_dict(), and open_spiel.python.voting.base.PreferenceProfile.pref_matrix().
_alternatives_ids [1/2]
List open_spiel.python.voting.base.PreferenceProfile._alternatives_ids [AlternativeId] static protected
Definition at line 46 of file base.py.
Referenced by open_spiel.python.voting.base.PreferenceProfile.__init__(), open_spiel.python.voting.base.PreferenceProfile._register_alternative(), open_spiel.python.voting.base.PreferenceProfile.add_vote_from_values(), open_spiel.python.voting.base.PreferenceProfile.alternatives(), open_spiel.python.voting.base.PreferenceProfile.alternatives_dict(), and open_spiel.python.voting.base.PreferenceProfile.condorcet_winner().
_alternatives_ids [2/2]
open_spiel.python.voting.base.PreferenceProfile._alternatives_ids protected
Definition at line 207 of file base.py.
Referenced by open_spiel.python.voting.base.PreferenceProfile.__init__(), open_spiel.python.voting.base.PreferenceProfile._register_alternative(), open_spiel.python.voting.base.PreferenceProfile.add_vote_from_values(), open_spiel.python.voting.base.PreferenceProfile.alternatives(), open_spiel.python.voting.base.PreferenceProfile.alternatives_dict(), and open_spiel.python.voting.base.PreferenceProfile.condorcet_winner().
_votes [1/2]
List open_spiel.python.voting.base.PreferenceProfile._votes [WeightedVote] static protected
Definition at line 43 of file base.py.
Referenced by open_spiel.python.voting.base.PreferenceProfile.__init__(), open_spiel.python.voting.base.PreferenceProfile.__str__(), open_spiel.python.voting.base.PreferenceProfile._register_alternative(), open_spiel.python.voting.base.PreferenceProfile.add_vote(), open_spiel.python.voting.base.PreferenceProfile.group(), open_spiel.python.voting.base.PreferenceProfile.num_votes(), open_spiel.python.voting.base.PreferenceProfile.pref_matrix(), open_spiel.python.voting.base.PreferenceProfile.set_all_weights(), open_spiel.python.voting.base.PreferenceProfile.ungroup(), and open_spiel.python.voting.base.PreferenceProfile.votes().
_votes [2/2]
open_spiel.python.voting.base.PreferenceProfile._votes protected
Definition at line 331 of file base.py.
Referenced by open_spiel.python.voting.base.PreferenceProfile.__init__(), open_spiel.python.voting.base.PreferenceProfile.__str__(), open_spiel.python.voting.base.PreferenceProfile._register_alternative(), open_spiel.python.voting.base.PreferenceProfile.add_vote(), open_spiel.python.voting.base.PreferenceProfile.group(), open_spiel.python.voting.base.PreferenceProfile.num_votes(), open_spiel.python.voting.base.PreferenceProfile.pref_matrix(), open_spiel.python.voting.base.PreferenceProfile.set_all_weights(), open_spiel.python.voting.base.PreferenceProfile.ungroup(), and open_spiel.python.voting.base.PreferenceProfile.votes().
The documentation for this class was generated from the following file:
open_spiel/python/voting/base.py