open spiel: meta_learning Namespace Reference
meta_learning Namespace Reference
Classes
class MetaCFRRegretAgent
Functions
append_counterfactual_values (List[typing.InfostateNode] infostates, Dict[str, List[List[float]]] counterfactual_values)
tuple[Dict[str, jnp.ndarray], Dict[str, List[int]]] compute_next_policy_invariants (typing.InfostateMapping infostates, List[int] all_actions, typing.InfostateMapping infostate_map)
compute_next_policy (typing.InfostateMapping infostates, typing.ApplyFn net_apply, typing.Params net_params, int epoch, List[int] all_actions, Dict[str, jnp.ndarray] one_hot_representations, Dict[str, List[int]] illegal_actions, hk.PRNGSequence key)
tuple[Dict[str, jnp.ndarray], Dict[str, jnp.ndarray], List[float]] cfr_br_meta_data (typing.HistoryNode history_tree_node, List[typing.InfostateNode] infostate_nodes, List[typing.InfostateMapping] all_infostates_map, int epochs, typing.ApplyFn net_apply, typing.Params net_params, List[int] all_actions, typing.InfostateMapping infostate_map, hk.PRNGSequence key)
Variables
FLAGS = flags.FLAGS
Detailed Description
Meta learning algorithm.
Function Documentation
append_counterfactual_values()
meta_learning.append_counterfactual_values (List[typing.InfostateNode] infostates, Dict[str, List[List[float]]] counterfactual_values)
Definition at line 63 of file meta_learning.py.
    counterfactual_values: Dict[str, List[List[float]]]):
  for infostate in infostates:
    counterfactual_values[infostate.infostate_string].append([
        infostate.counterfactual_action_values[a]
        for a in infostate.get_actions()
    ])
cfr_br_meta_data()
tuple[Dict[str, jnp.ndarray], Dict[str, jnp.ndarray], List[float]] meta_learning.cfr_br_meta_data (typing.HistoryNode history_tree_node, List[typing.InfostateNode] infostate_nodes, List[typing.InfostateMapping] all_infostates_map, int epochs, typing.ApplyFn net_apply, typing.Params net_params, List[int] all_actions, typing.InfostateMapping infostate_map, hk.PRNGSequence key)
Collects counterfactual values for both players and best response for player_2.
Args:
  history_tree_node: Game tree HistoryTreeNode which is the root of the game
    tree.
  infostate_nodes: Infostates.
  all_infostates_map: List of mappings from infostate strings to infostates.
  epochs: Number of epochs.
  net_apply: Apply function.
  net_params: Network parameters.
  all_actions: List of all actions.
  infostate_map: A mapping from infostate strings to infostates.
  key: Haiku pseudo random number generator.
Returns:
  Returns counterfactual values for player_1, counterfactual values for
  player_2 and best response values for player_2.
Definition at line 186 of file meta_learning.py.
) -> tuple[Dict[str, jnp.ndarray], Dict[str, jnp.ndarray], List[float]]:
  """Collects counterfactual values for both players and best response for player_2.
  Args:
    history_tree_node: Game tree HistoryTreeNode which is the root of the game
      tree.
    infostate_nodes: Infostates.
    all_infostates_map: List of mappings from infostate strings to infostates.
    epochs: Number of epochs.
    net_apply: Apply function.
    net_params: Network parameters.
    all_actions: List of all actions.
    infostate_map: A mapping from infostate strings to infostates.
    key: Haiku pseudo random number generator.
  Returns:
    Returns counterfactual values for player_1, counterfactual values for
    player_2 and best response values for player_2.
  """
  counterfactual_values_player1 = {
      infostate.infostate_string: []
      for infostate in list(all_infostates_map[1].values())
  }
  counterfactual_values_player2 = {
      infostate.infostate_string: []
      for infostate in list(all_infostates_map[2].values())
  }
  non_terminal_infostates_map_player1 = utils.filter_terminal_infostates(
      all_infostates_map[1]
  )
  one_hot_representations_player1, illegal_actions_player1 = (
      compute_next_policy_invariants(
          non_terminal_infostates_map_player1, all_actions, infostate_map
      )
  )
  player_2_last_best_response_values = []
  for epoch in range(epochs):
    compute_next_policy(non_terminal_infostates_map_player1, net_apply,
                        net_params, epoch, all_actions,
                        one_hot_representations_player1,
                        illegal_actions_player1, key)
    cfr.compute_reach_probabilities(history_tree_node, all_infostates_map)
    cfr.cumulate_average_policy(list(all_infostates_map[1].values()))
    cfr.compute_best_response_policy(infostate_nodes[2])
    cfr.compute_reach_probabilities(history_tree_node, all_infostates_map)
    cfr.compute_counterfactual_values(infostate_nodes[1])
    cfr.update_regrets(list(all_infostates_map[1].values()))
    append_counterfactual_values(
        list(all_infostates_map[1].values()), counterfactual_values_player1)
    cfr.normalize_average_policy(all_infostates_map[1].values())
    cfr.compute_reach_probabilities(history_tree_node, all_infostates_map)
    player_2_last_best_response_values.append(
        float(cfr.compute_best_response_values(infostate_nodes[2]))
    )
    logging.info(
        "Epoch %d: player_2 best response value is %f",
        epoch,
        player_2_last_best_response_values[-1],
    )
  return (  # pytype: disable=bad-return-type  # jax-ndarray
      counterfactual_values_player1,
      counterfactual_values_player2,
      player_2_last_best_response_values,
  )
References cfr.compute_best_response_policy(), cfr.compute_best_response_values(), cfr.compute_counterfactual_values(), compute_next_policy(), compute_next_policy_invariants(), cfr.compute_reach_probabilities(), cfr.cumulate_average_policy(), utils.filter_terminal_infostates(), cfr.normalize_average_policy(), and cfr.update_regrets().
Referenced by meta_learning.MetaCFRRegretAgent.next_policy(), and meta_learning.MetaCFRRegretAgent.training_optimizer().
compute_next_policy()
meta_learning.compute_next_policy (typing.InfostateMapping infostates, typing.ApplyFn net_apply, typing.Params net_params, int epoch, List[int] all_actions, Dict[str, jnp.ndarray] one_hot_representations, Dict[str, List[int]] illegal_actions, hk.PRNGSequence key)
Computes next step policy from output of the model.
Args:
  infostates: List of infostate mappings.
  net_apply: Apply function.
  net_params: Model params.
  epoch: epoch.
  all_actions: List of actions.
  one_hot_representations: Dictionary from infostate string to infostate.
  illegal_actions: Dictionary from infostate string to the list of illegal
    actions.
  key: Haiku Pseudo random number generator.
Definition at line 113 of file meta_learning.py.
                                              List[int]], key: hk.PRNGSequence):
  """Computes next step policy from output of the model.
  Args:
    infostates: List of infostate mappings.
    net_apply: Apply function.
    net_params: Model params.
    epoch: epoch.
    all_actions: List of actions.
    one_hot_representations: Dictionary from infostate string to infostate.
    illegal_actions: Dictionary from infostate string to the list of illegal
      actions.
    key: Haiku Pseudo random number generator.
  """
  infostate_lst = []
  input_lst = []
  illegal_action_lst = []
  batched_net_output = []
  for (infostate_str, infostate) in infostates.items():
    if infostate.is_terminal():
      continue
    legal_actions = infostate.get_actions()
    if len(legal_actions) == 1:
      infostate.policy[infostate.get_actions()[0]] = 1
      continue
    regret_vec = np.array([
        infostate.regret[a] /
        (epoch + 1) if a in infostate.get_actions() else 0
        for a in all_actions
    ])
    if FLAGS.use_infostate_representation:
      one_hot_representation = one_hot_representations[infostate_str]
      net_input = jnp.concatenate([regret_vec, one_hot_representation])
    else:
      net_input = regret_vec
    input_lst.append(net_input)
    infostate_lst.append(infostate)
    illegal_action_lst.append(illegal_actions[infostate_str])
  batched_inputs, output_mappings, relevant_illegal_actions = (
      utils.get_batched_input(
          input_lst, infostate_lst, illegal_action_lst, FLAGS.batch_size
      )
  )
  idx = 0
  for _ in range(int(len(batched_inputs) / FLAGS.batch_size)):
    batched_input, output_mapping, relevant_illegal_action = batched_inputs[
        idx:idx + FLAGS.batch_size], output_mappings[
            idx:idx +
            FLAGS.batch_size], relevant_illegal_actions[idx:idx +
                                                        FLAGS.batch_size]
    idx += FLAGS.batch_size
    batched_input_jnp = jnp.array(
        np.expand_dims(np.array(batched_input), axis=1))
    batched_net_output = utils.get_network_output_batched(  # pytype: disable=wrong-arg-types  # jnp-type
        net_apply, net_params,
        batched_input_jnp,
        relevant_illegal_action, key)
    for i, infostate in enumerate(output_mapping):
      net_output = jnp.squeeze(batched_net_output[i])
      for ai, action in enumerate(infostate.get_actions()):
        infostate.policy[action] = float(net_output[ai])
References utils.get_batched_input(), and utils.get_network_output_batched().
Referenced by cfr_br_meta_data().
compute_next_policy_invariants()
tuple[Dict[str, jnp.ndarray], Dict[str, List[int]]] meta_learning.compute_next_policy_invariants (typing.InfostateMapping infostates, List[int] all_actions, typing.InfostateMapping infostate_map)
Computes information needed to calculate next policy.
This function computes one hot encodings of infostates and returns mappings
from infostate strings to one hot representations of infostates as well as
illegal actions.
Args:
  infostates: List of infostate mappings.
  all_actions: List of actions.
  infostate_map: Mapping from infostate string to infostate.
Returns:
  Returns mappings of infostate strings to one hot representation for
  infostates and illegal actions
Definition at line 73 of file meta_learning.py.
) -> tuple[Dict[str, jnp.ndarray], Dict[str, List[int]]]:
  """Computes information needed to calculate next policy.
  This function computes one hot encodings of infostates and returns mappings
  from infostate strings to one hot representations of infostates as well as
  illegal actions.
  Args:
    infostates: List of infostate mappings.
    all_actions: List of actions.
    infostate_map: Mapping from infostate string to infostate.
  Returns:
    Returns mappings of infostate strings to one hot representation for
    infostates and illegal actions
  """
  one_hot_representations = {}
  illegal_actions = {}
  for (infostate_str, infostate) in infostates.items():
    if infostate.is_terminal():
      continue
    legal_actions = infostate.get_actions()
    if len(legal_actions) == 1:
      infostate.policy[infostate.get_actions()[0]] = 1
      continue
    infostate_str_one_hot = jax.nn.one_hot(infostate_map[infostate_str],
                                           len(infostates))
    one_hot_representations[infostate_str] = infostate_str_one_hot
    illegal_actions[infostate_str] = [
        i for i, a in enumerate(all_actions) if a not in legal_actions
    ]
  return one_hot_representations, illegal_actions
Referenced by cfr_br_meta_data().
Variable Documentation
FLAGS
meta_learning.FLAGS = flags.FLAGS
Definition at line 37 of file meta_learning.py.