open spiel: open_spiel::ActionView Struct Reference
open_spiel::ActionView Struct Reference
Public Member Functions
ActionView (const State &state)
ActionView (const Player current_player, const std::vector< std::vector< Action > > legal_actions)
int num_players () const
int num_actions (Player pl) const
FlatJointActions flat_joint_actions () const
FixedActions fixed_action (Player player, int action_index) const
Public Attributes
const Player current_player
const std::vector< std::vector< Action > > legal_actions
Detailed Description
Definition at line 71 of file action_view.h.
Constructor & Destructor Documentation
ActionView() [1/2]
open_spiel::ActionView::ActionView (const State & state) explicit
Definition at line 41 of file action_view.cc.
    : ActionView(state.CurrentPlayer(), CollectActions(state)) {}
ActionView() [2/2]
open_spiel::ActionView::ActionView (const Player current_player, const std::vector< std::vector< Action > > legal_actions)
Definition at line 37 of file action_view.cc.
    : current_player(current_player), legal_actions(std::move(legal_actions)) {}
Member Function Documentation
fixed_action()
FixedActions open_spiel::ActionView::fixed_action (Player player, int action_index) const
Definition at line 78 of file action_view.cc.
{
  SPIEL_CHECK_EQ(current_player, kSimultaneousPlayerId);
  int prod_after = 1;
  for (int pl = player + 1; pl < legal_actions.size(); pl++) {
    const std::vector<Action>& actions = legal_actions[pl];
    if (!actions.empty()) prod_after *= actions.size();
  }
  int prod_before = 1;
  for (int pl = 0; pl < player; pl++) {
    const std::vector<Action>& actions = legal_actions[pl];
    if (!actions.empty()) prod_before *= actions.size();
  }
  int num_actions = legal_actions[player].size();
  return FixedActions{action_index, num_actions, prod_before, prod_after};
}
flat_joint_actions()
FlatJointActions open_spiel::ActionView::flat_joint_actions () const
Definition at line 46 of file action_view.cc.
{
  int num_flat_actions = 1;
  for (const std::vector<Action>& actions : legal_actions) {
    if (!actions.empty()) num_flat_actions *= actions.size();
  }
  return FlatJointActions{num_flat_actions};
}
num_actions()
int open_spiel::ActionView::num_actions (Player pl) const inline
Definition at line 81 of file action_view.h.
{ return legal_actions.at(pl).size(); }
Referenced by open_spiel.python.games.dynamic_routing_utils.Network::assert_valid_action(), models.OptimizerModel::initialize_optimizer_model(), and regret_matching_agent.RegretMatchingAgent::regret_matching_policy().
num_players()
int open_spiel::ActionView::num_players () const inline
Definition at line 80 of file action_view.h.
{ return legal_actions.size(); }
Referenced by open_spiel.python.algorithms.adidas_utils.games.gamut.GAMUT::__init__(), open_spiel.python.algorithms.adidas_utils.games.pyspiel_tensor_game.PyspielTensorGame::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.nonsymmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.helpers.symmetric.updates.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.regmatch.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal_noaux.Solver::__init__(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.regmatch.Solver::__init__(), open_spiel.python.games.liars_poker.LiarsPokerObserver::__init__(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::__init__(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::__init__(), open_spiel.python.algorithms.adidas_utils.games.big.TensorGame::best_response(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::chance_outcomes(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::chance_outcomes(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ped.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.pg.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre_anneal.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.regmatch.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.sgd.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ped.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal_noaux.Solver::compute_gradients(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.sgd.Solver::compute_gradients(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::distribution_support(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::distribution_support(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::get_pos_proba(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::get_pos_proba(), open_spiel.python.rl_environment.Environment::get_time_step(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::gradients(), open_spiel.python.algorithms.adidas_utils.helpers.nonsymmetric.updates.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.helpers.symmetric.updates.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_anneal.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_poly.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.ate_regmatch.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.qre_anneal.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.regmatch.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.nonsymmetric.sgd.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.ate_anneal.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.qre_anneal_noaux.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.regmatch.Solver::init_vars(), open_spiel.python.algorithms.adidas_utils.solvers.symmetric.sgd.Solver::init_vars(), open_spiel.python.coalitional_games.least_core_lagrangian.CoreSolver::loss_deficit(), open_spiel.python.games.dynamic_routing.DynamicRoutingGame::make_py_observer(), open_spiel.python.games.liars_poker.LiarsPoker::make_py_observer(), open_spiel.python.environments.iterated_matrix_game.IteratedMatrixGame::reset(), open_spiel.python.rl_environment.Environment::reset(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::rewards(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::rewards(), open_spiel.python.examples.chat_game_psro_example.PSRO::run(), open_spiel.python.coalitional_games.least_core_lagrangian.CoreLagrangian::solve(), open_spiel.python.coalitional_games.least_core_lagrangian.CoreOptimization::solve(), open_spiel.python.coalitional_games.least_core_lagrangian.CoreOptimizationLogits::solve(), open_spiel.python.environments.iterated_matrix_game.IteratedMatrixGame::step(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::update_distribution(), open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::update_distribution(), and open_spiel.python.rl_environment.Environment::use_observation().
Member Data Documentation
current_player
const Player open_spiel::ActionView::current_player
Definition at line 72 of file action_view.h.
Referenced by open_spiel.python.games.liars_poker.LiarsPokerState::__str__(), open_spiel.python.games.block_dominoes.BlockDominoesState::_apply_action(), open_spiel.python.games.team_dominoes.DominoesState::_apply_action(), open_spiel.python.mfg.games.crowd_avoidance.MFGCrowdAvoidanceState::_legal_actions(), open_spiel.python.mfg.games.crowd_modelling.MFGCrowdModellingState::_legal_actions(), open_spiel.python.mfg.games.linear_quadratic.MFGLinearQuadraticState::_legal_actions(), open_spiel.python.mfg.games.normal_form_game.MFGNormalFormState::_legal_actions(), open_spiel.python.mfg.games.periodic_aversion.MFGPeriodicAversionState::_legal_actions(), and open_spiel.python.mfg.games.predator_prey.MFGPredatorPreyState::_legal_actions().
legal_actions
const std::vector<std::vector<Action> > open_spiel::ActionView::legal_actions
Definition at line 73 of file action_view.h.
The documentation for this struct was generated from the following files:
open_spiel/action_view.h
open_spiel/action_view.cc